include::./index.adoc[]

[[v58-11-0]]
=== Hebreus, 11
// nvi ?, NVI - Nova Versão Internacional

[[v58-11-1]]

^<<v58-11-1,1>>^ Ora, a fé é a certeza daquilo que esperamos e a prova das coisas que não vemos.

[[v58-11-2]]

^<<v58-11-2,2>>^ Pois foi por meio dela que os antigos receberam bom testemunho.

[[v58-11-3]]

^<<v58-11-3,3>>^ Pela fé entendemos que o universo foi formado pela palavra de Deus, de modo que o que se vê não foi feito do que é visível.

[[v58-11-4]]

^<<v58-11-4,4>>^ Pela fé Abel ofereceu a Deus um sacrifício superior ao de Caim. Pela fé ele foi reconhecido como justo, quando Deus aprovou as suas ofertas. Embora esteja morto, por meio da fé ainda fala.

[[v58-11-5]]

^<<v58-11-5,5>>^ Pela fé Enoque foi arrebatado, de modo que não experimentou a morte; "ele já não foi encontrado porque Deus o havia arrebatado", pois antes de ser arrebatado recebeu testemunho de que tinha agradado a Deus.

[[v58-11-6]]

^<<v58-11-6,6>>^ Sem fé é impossível agradar a Deus, pois quem dele se aproxima precisa crer que ele existe e que recompensa aqueles que o buscam.

[[v58-11-7]]

^<<v58-11-7,7>>^ Pela fé Noé, quando avisado a respeito de coisas que ainda não se viam, movido por santo temor, construiu uma arca para salvar sua família. Por meio da fé ele condenou o mundo e tornou-se herdeiro da justiça que é segundo a fé.

[[v58-11-8]]

^<<v58-11-8,8>>^ Pela fé Abraão, quando chamado, obedeceu e dirigiu-se a um lugar que mais tarde receberia como herança, embora não soubesse para onde estava indo.

[[v58-11-9]]

^<<v58-11-9,9>>^ Pela fé peregrinou na terra prometida como se estivesse em terra estranha; viveu em tendas, bem como Isaque e Jacó, co-herdeiros da mesma promessa.

[[v58-11-10]]

^<<v58-11-10,10>>^ Pois ele esperava a cidade que tem alicerces, cujo arquiteto e edificador é Deus.

[[v58-11-11]]

^<<v58-11-11,11>>^ Pela fé, Abraão — e também a própria Sara, apesar de estéril e avançada em idade — recebeu poder para gerar um filho, porque considerou fiel aquele que lhe havia feito a promessa.

[[v58-11-12]]

^<<v58-11-12,12>>^ Assim, daquele homem já sem vitalidade originaram-se descendentes tão numerosos como as estrelas do céu e tão incontáveis como a areia da praia do mar.

[[v58-11-13]]

^<<v58-11-13,13>>^ Todos estes ainda viveram pela fé, e morreram sem receber o que tinha sido prometido; viram-nas de longe e de longe as saudaram, reconhecendo que eram estrangeiros e peregrinos na terra.

[[v58-11-14]]

^<<v58-11-14,14>>^ Os que assim falam mostram que estão buscando uma pátria.

[[v58-11-15]]

^<<v58-11-15,15>>^ Se estivessem pensando naquela de onde saíram, teriam oportunidade de voltar.

[[v58-11-16]]

^<<v58-11-16,16>>^ Em vez disso, esperavam eles uma pátria melhor, isto é, a pátria celestial. Por essa razão Deus não se envergonha de ser chamado o Deus deles, pois preparou-lhes uma cidade.

[[v58-11-17]]

^<<v58-11-17,17>>^ Pela fé Abraão, quando Deus o pôs à prova, ofereceu Isaque como sacrifício. Aquele que havia recebido as promessas estava a ponto de sacrificar o seu único filho,

[[v58-11-18]]

^<<v58-11-18,18>>^ embora Deus lhe tivesse dito: "Por meio de Isaque a sua descendência será considerada".

[[v58-11-19]]

^<<v58-11-19,19>>^ Abraão levou em conta que Deus pode ressuscitar os mortos; e, figuradamente, recebeu Isaque de volta dentre os mortos.

[[v58-11-20]]

^<<v58-11-20,20>>^ Pela fé Isaque abençoou Jacó e Esaú com respeito ao futuro deles.

[[v58-11-21]]

^<<v58-11-21,21>>^ Pela fé Jacó, à beira da morte, abençoou cada um dos filhos de José e adorou a Deus, apoiado na extremidade do seu bordão.

[[v58-11-22]]

^<<v58-11-22,22>>^ Pela fé José, no fim da vida, fez menção do êxodo dos israelitas do Egito e deu instruções acerca dos seus próprios ossos.

[[v58-11-23]]

^<<v58-11-23,23>>^ Pela fé Moisés, recém-nascido, foi escondido durante três meses por seus pais, pois estes viram que ele não era uma criança comum, e não temeram o decreto do rei.

[[v58-11-24]]

^<<v58-11-24,24>>^ Pela fé Moisés, já adulto, recusou ser chamado filho da filha do faraó,

[[v58-11-25]]

^<<v58-11-25,25>>^ preferindo ser maltratado com o povo de Deus a desfrutar os prazeres do pecado durante algum tempo.

[[v58-11-26]]

^<<v58-11-26,26>>^ Por amor de Cristo, considerou a desonra riqueza maior do que os tesouros do Egito, porque contemplava a sua recompensa.

[[v58-11-27]]

^<<v58-11-27,27>>^ Pela fé saiu do Egito, não temendo a ira do rei, e perseverou, porque via aquele que é invisível.

[[v58-11-28]]

^<<v58-11-28,28>>^ Pela fé celebrou a Páscoa e fez a aspersão do sangue, para que o destruidor não tocasse nos fihos mais velhos dos israelitas.

[[v58-11-29]]

^<<v58-11-29,29>>^ Pela fé o povo atravessou o mar Vermelho como em terra seca; mas, quando os egípcios tentaram fazê-lo, morreram afogados.

[[v58-11-30]]

^<<v58-11-30,30>>^ Pela fé caíram os muros de Jericó, depois de serem rodeados durante sete dias.

[[v58-11-31]]

^<<v58-11-31,31>>^ Pela fé a prostituta Raabe, por ter acolhido os espiões, não foi morta com os que haviam sido desobedientes.

[[v58-11-32]]

^<<v58-11-32,32>>^ Que mais direi? Não tenho tempo para falar de Gideão, Baraque, Sansão, Jefté, Davi, Samuel e os profetas,

[[v58-11-33]]

^<<v58-11-33,33>>^ os quais pela fé conquistaram reinos, praticaram a justiça, alcançaram o cumprimento de promessas, fecharam a boca de leões,

[[v58-11-34]]

^<<v58-11-34,34>>^ apagaram o poder do fogo e escaparam do fio da espada; da fraqueza tiraram força, tornaram-se poderosos na batalha e puseram em fuga exércitos estrangeiros.

[[v58-11-35]]

^<<v58-11-35,35>>^ Houve mulheres que, pela ressurreição, tiveram de volta os seus mortos. Alguns foram torturados e recusaram ser libertados, para poderem alcançar uma ressurreição superior.

[[v58-11-36]]

^<<v58-11-36,36>>^ Outros enfrentaram zombaria e açoites, outros ainda foram acorrentados e colocados na prisão,

[[v58-11-37]]

^<<v58-11-37,37>>^ apedrejados, serrados ao meio, postos à prova, mortos ao fio da espada. Andaram errantes, vestidos de pele de ovelhas e de cabras, necessitados, afligidos e maltratados.

[[v58-11-38]]

^<<v58-11-38,38>>^ O mundo não era digno deles. Vagaram pelos desertos e montes, pelas cavernas e grutas.

[[v58-11-39]]

^<<v58-11-39,39>>^ Todos estes receberam bom testemunho por meio da fé; no entanto, nenhum deles recebeu o que havia sido prometido.

[[v58-11-40]]

^<<v58-11-40,40>>^ Deus havia planejado algo melhor para nós, para que conosco fossem eles aperfeiçoados.

'''

xref:058-hebreus/058-hebreus-010.adoc#v58-10-0[&#60; Capítulo Anterior] | <<v58-11-0,Topo>> | xref:058-hebreus/058-hebreus-012.adoc#v58-12-0[Próximo Capítulo &#62;]