include::./index.adoc[]

[[v58-6-0]]
=== Hebreus, 6
// nvi ?, NVI - Nova Versão Internacional

[[v58-6-1]]

^<<v58-6-1,1>>^ Portanto, deixemos os ensinos elementares a respeito de Cristo e avancemos para a maturidade, sem lançar novamente o fundamento do arrependimento de atos que conduzem à morte, da fé em Deus,

[[v58-6-2]]

^<<v58-6-2,2>>^ da instrução a respeito de batismos, da imposição de mãos, da ressurreição dos mortos e do juízo eterno.

[[v58-6-3]]

^<<v58-6-3,3>>^ Assim faremos, se Deus o permitir.

[[v58-6-4]]

^<<v58-6-4,4>>^ Ora para aqueles que uma vez foram iluminados, provaram o dom celestial, tornaram-se participantes do Espírito Santo,

[[v58-6-5]]

^<<v58-6-5,5>>^ experimentaram a bondade da palavra de Deus e os poderes da era que há de vir,

[[v58-6-6]]

^<<v58-6-6,6>>^ e caíram, é impossível que sejam reconduzidos ao arrependimento; pois para si mesmos estão crucificando de novo o Filho de Deus, sujeitando-o à desonra pública.

[[v58-6-7]]

^<<v58-6-7,7>>^ Pois a terra que absorve a chuva, que cai freqüentemente e dá colheita proveitosa àqueles que a cultivam, recebe a bênção de Deus.

[[v58-6-8]]

^<<v58-6-8,8>>^ Mas a terra que produz espinhos e ervas daninhas, é inútil e logo será amaldiçoada. Seu fim é ser queimada.

[[v58-6-9]]

^<<v58-6-9,9>>^ Amados, mesmo falando dessa forma, estamos convictos de coisas melhores em relação a vocês, coisas próprias da salvação.

[[v58-6-10]]

^<<v58-6-10,10>>^ Deus não é injusto; ele não se esquecerá do trabalho de vocês e do amor que demonstraram por ele, pois ajudaram os santos e continuam a ajudá-los.

[[v58-6-11]]

^<<v58-6-11,11>>^ Queremos que cada um de vocês mostre essa mesma prontidão até o fim, para que tenham a plena certeza da esperança,

[[v58-6-12]]

^<<v58-6-12,12>>^ de modo que vocês não se tornem negligentes, mas imitem aqueles que, por meio da fé e da paciência, recebem a herança prometida.

[[v58-6-13]]

^<<v58-6-13,13>>^ Quando Deus fez a sua promessa a Abraão, por não haver ninguém superior por quem jurar, jurou por si mesmo,

[[v58-6-14]]

^<<v58-6-14,14>>^ dizendo: "Esteja certo de que o abençoarei e farei seus descendentes numerosos".

[[v58-6-15]]

^<<v58-6-15,15>>^ E foi assim que, depois de esperar pacientemente, Abraão alcançou a promessa.

[[v58-6-16]]

^<<v58-6-16,16>>^ Os homens juram por alguém superior a si mesmos, e o juramento confirma o que foi dito, pondo fim a toda discussão.

[[v58-6-17]]

^<<v58-6-17,17>>^ Querendo mostrar de forma bem clara a natureza imutável do seu propósito para com os herdeiros da promessa, Deus o confirmou com juramento,

[[v58-6-18]]

^<<v58-6-18,18>>^ para que, por meio de duas coisas imutáveis nas quais é impossível que Deus minta, sejamos firmemente encorajados, nós, que nos refugiamos nele para tomar posse da esperança a nós proposta.

[[v58-6-19]]

^<<v58-6-19,19>>^ Temos esta esperança como âncora da alma, firme e segura, a qual adentra o santuário interior, por trás do véu,

[[v58-6-20]]

^<<v58-6-20,20>>^ onde Jesus, que nos precedeu, entrou em nosso lugar, tornando-se sumo sacerdote para sempre, segundo a ordem de Melquisedeque.

'''

xref:058-hebreus/058-hebreus-005.adoc#v58-5-0[&#60; Capítulo Anterior] | <<v58-6-0,Topo>> | xref:058-hebreus/058-hebreus-007.adoc#v58-7-0[Próximo Capítulo &#62;]