include::./index.adoc[]

[[v58-4-0]]
=== Hebreus, 4
// nvi ?, NVI - Nova Versão Internacional

[[v58-4-1]]

^<<v58-4-1,1>>^ Visto que nos foi deixada a promessa de entrarmos no descanso de Deus, temamos que algum de vocês pense que tenha falhado.

[[v58-4-2]]

^<<v58-4-2,2>>^ Pois as boas novas foram pregadas também a nós, tanto quanto a eles; mas a mensagem que eles ouviram de nada lhes valeu, pois não foi acompanhada de fé por aqueles que a ouviram.

[[v58-4-3]]

^<<v58-4-3,3>>^ Pois nós, os que cremos, é que entramos naquele descanso, conforme Deus disse: "Assim jurei na minha ira: Jamais entrarão no meu descanso" — embora as suas obras estivessem concluídas desde a criação do mundo.

[[v58-4-4]]

^<<v58-4-4,4>>^ Pois em certo lugar ele falou sobre o sétimo dia, nestas palavras: "No sétimo dia Deus descansou de toda obra que realizara".

[[v58-4-5]]

^<<v58-4-5,5>>^ E de novo, na passagem citada há pouco, diz: "Jamais entrarão no meu descanso".

[[v58-4-6]]

^<<v58-4-6,6>>^ Entretanto, resta entrarem alguns naquele descanso, e aqueles a quem anteriormente as boas novas foram pregadas não entraram, por causa da desobediência.

[[v58-4-7]]

^<<v58-4-7,7>>^ Por isso Deus estabelece outra vez um determinado dia, chamando-o "hoje", ao declarar muito tempo depois, por meio de Davi, de acordo com o que fora dito antes: "Se hoje vocês ouvirem a sua voz, não endureçam o coração".

[[v58-4-8]]

^<<v58-4-8,8>>^ Porque, se Josué lhes tivesse dado descanso, Deus não teria falado posteriormente a respeito de outro dia.

[[v58-4-9]]

^<<v58-4-9,9>>^ Assim, ainda resta um descanso sabático para o povo de Deus;

[[v58-4-10]]

^<<v58-4-10,10>>^ pois todo aquele que entra no descanso de Deus, também descansa das suas obras, como Deus descansou das suas.

[[v58-4-11]]

^<<v58-4-11,11>>^ Portanto, esforcemo-nos por entrar nesse descanso, para que ninguém venha a cair, seguindo aquele exemplo de desobediência.

[[v58-4-12]]

^<<v58-4-12,12>>^ Pois a palavra de Deus é viva e eficaz, e mais afiada que qualquer espada de dois gumes; ela penetra ao ponto de dividir alma e espírito, juntas e medulas, e julga os pensamentos e intenções do coração.

[[v58-4-13]]

^<<v58-4-13,13>>^ Nada, em toda a criação, está oculto aos olhos de Deus. Tudo está descoberto e exposto diante dos olhos daquele a quem havemos de prestar contas.

[[v58-4-14]]

^<<v58-4-14,14>>^ Portanto, visto que temos um grande sumo sacerdote que adentrou os céus, Jesus, o Filho de Deus, apeguemo-nos com toda a firmeza à fé que professamos,

[[v58-4-15]]

^<<v58-4-15,15>>^ pois não temos um sumo sacerdote que não possa compadecer-se das nossas fraquezas, mas sim alguém que, como nós, passou por todo tipo de tentação, porém, sem pecado.

[[v58-4-16]]

^<<v58-4-16,16>>^ Assim sendo, aproximemo-nos do trono da graça com toda a confiança, a fim de recebermos misericórdia e encontrarmos graça que nos ajude no momento da necessidade.

'''

xref:058-hebreus/058-hebreus-003.adoc#v58-3-0[&#60; Capítulo Anterior] | <<v58-4-0,Topo>> | xref:058-hebreus/058-hebreus-005.adoc#v58-5-0[Próximo Capítulo &#62;]