include::./index.adoc[]

[[v58-3-0]]
=== Hebreus, 3
// nvi ?, NVI - Nova Versão Internacional

[[v58-3-1]]

^<<v58-3-1,1>>^ Portanto, santos irmãos, participantes do chamado celestial, fixem os seus pensamentos em Jesus, apóstolo e sumo sacerdote que confessamos.

[[v58-3-2]]

^<<v58-3-2,2>>^ Ele foi fiel àquele que o havia constituído, assim como Moisés foi fiel em toda a casa de Deus.

[[v58-3-3]]

^<<v58-3-3,3>>^ Jesus foi considerado digno de maior glória do que Moisés, da mesma forma que o construtor de uma casa tem mais honra do que a própria casa.

[[v58-3-4]]

^<<v58-3-4,4>>^ Pois toda casa é construída por alguém, mas Deus é o edificador de tudo.

[[v58-3-5]]

^<<v58-3-5,5>>^ Moisés foi fiel como servo em toda a casa de Deus, dando testemunho do que haveria de ser dito no futuro,

[[v58-3-6]]

^<<v58-3-6,6>>^ mas Cristo é fiel como Filho sobre a casa de Deus; e esta casa somos nós, se é que nos apegamos firmemente à confiança e à esperança da qual nos gloriamos.

[[v58-3-7]]

^<<v58-3-7,7>>^ Assim, como diz o Espírito Santo: "Hoje, se vocês ouvirem a sua voz,

[[v58-3-8]]

^<<v58-3-8,8>>^ não endureçam o coração, como na rebelião, durante o tempo de provação no deserto,

[[v58-3-9]]

^<<v58-3-9,9>>^ onde os seus antepassados me tentaram, pondo-me à prova, apesar de, durante quarenta anos, terem visto o que eu fiz.

[[v58-3-10]]

^<<v58-3-10,10>>^ Por isso fiquei irado contra aquela geração e disse: Os seus corações estão sempre se desviando, e eles não reconheceram os meus caminhos.

[[v58-3-11]]

^<<v58-3-11,11>>^ Assim jurei na minha ira: Jamais entrarão no meu descanso".

[[v58-3-12]]

^<<v58-3-12,12>>^ Cuidado, irmãos, para que nenhum de vocês tenha coração perverso e incrédulo, que se afaste do Deus vivo.

[[v58-3-13]]

^<<v58-3-13,13>>^ Pelo contrário, encorajem-se uns aos outros todos os dias, durante o tempo que se chama "hoje", de modo que nenhum de vocês seja endurecido pelo engano do pecado,

[[v58-3-14]]

^<<v58-3-14,14>>^ pois passamos a ser participantes de Cristo, desde que, de fato, nos apeguemos até o fim à confiança que tivemos no princípio.

[[v58-3-15]]

^<<v58-3-15,15>>^ Por isso é que se diz: "Se hoje vocês ouvirem a sua voz, não endureçam o coração, como na rebelião".

[[v58-3-16]]

^<<v58-3-16,16>>^ Quem foram os que ouviram e se rebelaram? Não foram todos os que Moisés tirou do Egito?

[[v58-3-17]]

^<<v58-3-17,17>>^ Contra quem Deus esteve irado durante quarenta anos? Não foi contra aqueles que pecaram, cujos corpos caíram no deserto?

[[v58-3-18]]

^<<v58-3-18,18>>^ E a quem jurou que nunca haveriam de entrar no seu descanso? Não foi àqueles que foram desobedientes?

[[v58-3-19]]

^<<v58-3-19,19>>^ Vemos, assim, que foi por causa da incredulidade que não puderam entrar.

'''

xref:058-hebreus/058-hebreus-002.adoc#v58-2-0[&#60; Capítulo Anterior] | <<v58-3-0,Topo>> | xref:058-hebreus/058-hebreus-004.adoc#v58-4-0[Próximo Capítulo &#62;]