include::./index.adoc[]

[[v58-10-0]]
=== Hebreus, 10
// nvi ?, NVI - Nova Versão Internacional

[[v58-10-1]]

^<<v58-10-1,1>>^ A Lei traz apenas uma sombra dos benefícios que hão de vir, e não a realidade dos mesmos. Por isso ela nunca consegue, mediante os mesmos sacrifícios repetidos ano após ano, aperfeiçoar os que se aproximam para adorar.

[[v58-10-2]]

^<<v58-10-2,2>>^ Se pudesse fazê-lo, não deixariam de ser oferecidos? Pois os adoradores, tendo sido purificados uma vez por todas, não mais se sentiriam culpados de seus pecados.

[[v58-10-3]]

^<<v58-10-3,3>>^ Contudo, esses sacrifícios são uma recordação anual dos pecados,

[[v58-10-4]]

^<<v58-10-4,4>>^ pois é impossível que o sangue de touros e bodes tire pecados.

[[v58-10-5]]

^<<v58-10-5,5>>^ Por isso, quando Cristo veio ao mundo, disse: "Sacrifício e oferta não quiseste, mas um corpo me preparaste;

[[v58-10-6]]

^<<v58-10-6,6>>^ de holocaustos e ofertas pelo pecado não te agradaste".

[[v58-10-7]]

^<<v58-10-7,7>>^ Então eu disse: Aqui estou, no livro está escrito a meu respeito; vim para fazer a tua vontade, ó Deus.

[[v58-10-8]]

^<<v58-10-8,8>>^ Primeiro ele disse: "Sacrifícios, ofertas, holocaustos e ofertas pelo pecado não quiseste, nem deles te agradaste" ( os quais eram feitos conforme a Lei ).

[[v58-10-9]]

^<<v58-10-9,9>>^ Então acrescentou: "Aqui estou; vim para fazer a tua vontade". Ele cancela o primeiro para estabelecer o segundo.

[[v58-10-10]]

^<<v58-10-10,10>>^ Pelo cumprimento dessa vontade fomos santificados, por meio do sacrifício do corpo de Jesus Cristo, oferecido uma vez por todas.

[[v58-10-11]]

^<<v58-10-11,11>>^ Dia após dia, todo sacerdote apresenta-se e exerce os seus deveres religiosos; repetidamente oferece os mesmos sacrifícios, que nunca podem remover os pecados.

[[v58-10-12]]

^<<v58-10-12,12>>^ Mas quando este sacerdote acabou de oferecer, para sempre, um único sacrifício pelos pecados, assentou-se à direita de Deus.

[[v58-10-13]]

^<<v58-10-13,13>>^ Daí em diante, ele está esperando até que os seus inimigos sejam colocados como estrado dos seus pés;

[[v58-10-14]]

^<<v58-10-14,14>>^ porque, por meio de um único sacrifício, ele aperfeiçoou para sempre os que estão sendo santificados.

[[v58-10-15]]

^<<v58-10-15,15>>^ O Espírito Santo também nos testifica a este respeito. Primeiro ele diz:

[[v58-10-16]]

^<<v58-10-16,16>>^ "Esta é a aliança que farei com eles, depois daqueles dias, diz o Senhor. Porei as minhas leis em seus corações e as escreverei em suas mentes";

[[v58-10-17]]

^<<v58-10-17,17>>^ e acrescenta: "Dos seus pecados e iniqüidades não me lembrarei mais".

[[v58-10-18]]

^<<v58-10-18,18>>^ Onde essas coisas foram perdoadas, não há mais necessidade de sacrifício pelo pecado.

[[v58-10-19]]

^<<v58-10-19,19>>^ Portanto, irmãos, temos plena confiança para entrar no Santo dos Santos pelo sangue de Jesus,

[[v58-10-20]]

^<<v58-10-20,20>>^ por um novo e vivo caminho que ele nos abriu por meio do véu, isto é, do seu corpo.

[[v58-10-21]]

^<<v58-10-21,21>>^ Temos, pois, um grande sacerdote sobre a casa de Deus.

[[v58-10-22]]

^<<v58-10-22,22>>^ Sendo assim, aproximemo-nos de Deus com um coração sincero e com plena convicção de fé, tendo os corações aspergidos para nos purificar de uma consciência culpada e tendo os nossos corpos lavados com água pura.

[[v58-10-23]]

^<<v58-10-23,23>>^ Apeguemo-nos com firmeza à esperança que professamos, pois aquele que prometeu é fiel.

[[v58-10-24]]

^<<v58-10-24,24>>^ E consideremo-nos uns aos outros para incentivar-nos ao amor e às boas obras.

[[v58-10-25]]

^<<v58-10-25,25>>^ Não deixemos de reunir-nos como igreja, segundo o costume de alguns, mas encorajemo-nos uns aos outros, ainda mais quando vocês vêem que se aproxima o Dia.

[[v58-10-26]]

^<<v58-10-26,26>>^ Se continuarmos a pecar deliberadamente depois que recebemos o conhecimento da verdade, já não resta sacrifício pelos pecados,

[[v58-10-27]]

^<<v58-10-27,27>>^ mas tão-somente uma terrível expectativa de juízo e de fogo intenso que consumirá os inimigos de Deus.

[[v58-10-28]]

^<<v58-10-28,28>>^ Quem rejeitava a lei de Moisés morria sem misericórdia pelo depoimento de duas ou três testemunhas.

[[v58-10-29]]

^<<v58-10-29,29>>^ Quão mais severo castigo, julgam vocês, merece aquele que pisou aos pés o Filho de Deus, que profanou o sangue da aliança pelo qual ele foi santificado, e insultou o Espírito da graça?

[[v58-10-30]]

^<<v58-10-30,30>>^ Pois conhecemos aquele que disse: "A mim pertence a vingança; eu retribuirei"; e outra vez: "O Senhor julgará o seu povo".

[[v58-10-31]]

^<<v58-10-31,31>>^ Terrível coisa é cair nas mãos do Deus vivo!

[[v58-10-32]]

^<<v58-10-32,32>>^ Lembrem-se dos primeiros dias, depois que vocês foram iluminados, quando suportaram muita luta e muito sofrimento.

[[v58-10-33]]

^<<v58-10-33,33>>^ Algumas vezes vocês foram expostos a insultos e tribulações; em outras ocasiões fizeram-se solidários com os que assim foram tratados.

[[v58-10-34]]

^<<v58-10-34,34>>^ Vocês se compadeceram dos que estavam na prisão e aceitaram alegremente o confisco dos próprios bens, pois sabiam que possuíam bens superiores e permanentes.

[[v58-10-35]]

^<<v58-10-35,35>>^ Por isso, não abram mão da confiança que vocês têm; ela será ricamente recompensada.

[[v58-10-36]]

^<<v58-10-36,36>>^ Vocês precisam perseverar, de modo que, quando tiverem feito a vontade de Deus, recebam o que ele prometeu;

[[v58-10-37]]

^<<v58-10-37,37>>^ pois em breve, muito em breve "Aquele que vem virá, e não demorará.

[[v58-10-38]]

^<<v58-10-38,38>>^ Mas o meu justo viverá pela fé. E, se retroceder, não me agradarei dele".

[[v58-10-39]]

^<<v58-10-39,39>>^ Nós, porém, não somos dos que retrocedem e são destruídos, mas dos que crêem e são salvos.

'''

xref:058-hebreus/058-hebreus-009.adoc#v58-9-0[&#60; Capítulo Anterior] | <<v58-10-0,Topo>> | xref:058-hebreus/058-hebreus-011.adoc#v58-11-0[Próximo Capítulo &#62;]