include::./index.adoc[]

[[v58-7-0]]
=== Hebreus, 7
// nvi ?, NVI - Nova Versão Internacional

[[v58-7-1]]

^<<v58-7-1,1>>^ Esse Melquisedeque, rei de Salém e sacerdote do Deus Altíssimo, encontrou-se com Abraão quando este voltava, depois de derrotar os reis, e o abençoou;

[[v58-7-2]]

^<<v58-7-2,2>>^ e Abraão lhe deu o dízimo de tudo. Em primeiro lugar, seu nome significa "rei de justiça"; depois, "rei de Salém" quer dizer "rei de paz".

[[v58-7-3]]

^<<v58-7-3,3>>^ Sem pai, sem mãe, sem genealogia, sem princípio de dias nem fim de vida, feito semelhante ao Filho de Deus, ele permanece sacerdote para sempre.

[[v58-7-4]]

^<<v58-7-4,4>>^ Considerem a grandeza desse homem: até mesmo o patriarca Abraão lhe deu o dízimo dos despojos!

[[v58-7-5]]

^<<v58-7-5,5>>^ A lei requer dos sacerdotes dentre os descendentes de Levi que recebam o dízimo do povo, isto é, dos seus irmãos, embora estes sejam descendentes de Abraão.

[[v58-7-6]]

^<<v58-7-6,6>>^ Este homem, porém, que não pertencia à linhagem de Levi, recebeu os dízimos de Abraão e abençoou aquele que tinha as promessas.

[[v58-7-7]]

^<<v58-7-7,7>>^ Sem dúvida alguma, o inferior é abençoado pelo superior.

[[v58-7-8]]

^<<v58-7-8,8>>^ No primeiro caso, quem recebe o dízimo são homens mortais; no outro caso é aquele de quem se declara que vive.

[[v58-7-9]]

^<<v58-7-9,9>>^ Pode-se até dizer que Levi, que recebe os dízimos, entregou-os por meio de Abraão,

[[v58-7-10]]

^<<v58-7-10,10>>^ pois, quando Melquisedeque se encontrou com Abraão, Levi ainda estava no corpo do seu antepassado.

[[v58-7-11]]

^<<v58-7-11,11>>^ Se fosse possível alcançar a perfeição por meio do sacerdócio levítico ( pois em sua vigência o povo recebeu a lei ), por que haveria ainda necessidade de se levantar outro sacerdote, segundo a ordem de Melquisedeque e não de Arão?

[[v58-7-12]]

^<<v58-7-12,12>>^ Pois quando há mudança de sacerdócio, é necessário que haja mudança de lei.

[[v58-7-13]]

^<<v58-7-13,13>>^ Ora, aquele de quem se dizem estas coisas pertencia a outra tribo, da qual ninguém jamais havia servido diante do altar,

[[v58-7-14]]

^<<v58-7-14,14>>^ pois é evidente que o nosso Senhor descende de Judá, tribo da qual Moisés nada fala quanto a sacerdócio.

[[v58-7-15]]

^<<v58-7-15,15>>^ O que acabamos de dizer fica ainda mais claro, quando aparece outro sacerdote semelhante a Melquisedeque,

[[v58-7-16]]

^<<v58-7-16,16>>^ alguém que se tornou sacerdote, não por regras relativas à linhagem, mas segundo o poder de uma vida indestrutível.

[[v58-7-17]]

^<<v58-7-17,17>>^ Pois sobre ele é afirmado: "Tu és sacerdote para sempre, segundo a ordem de Melquisedeque".

[[v58-7-18]]

^<<v58-7-18,18>>^ A ordenança anterior é revogada, porquanto era fraca e inútil

[[v58-7-19]]

^<<v58-7-19,19>>^ ( pois a lei não havia aperfeiçoado coisa alguma ), sendo introduzida uma esperança superior, pela qual nos aproximamos de Deus.

[[v58-7-20]]

^<<v58-7-20,20>>^ E isso não aconteceu sem juramento! Outros se tornaram sacerdotes sem qualquer juramento,

[[v58-7-21]]

^<<v58-7-21,21>>^ mas ele se tornou sacerdote com juramento, quando Deus lhe disse: "O Senhor jurou e não se arrependerá: ‘Tu és sacerdote para sempre’ ".

[[v58-7-22]]

^<<v58-7-22,22>>^ Jesus tornou-se, por isso mesmo, a garantia de uma aliança superior.

[[v58-7-23]]

^<<v58-7-23,23>>^ Ora, daqueles sacerdotes tem havido muitos, porque a morte os impede de continuar em seu ofício;

[[v58-7-24]]

^<<v58-7-24,24>>^ mas, visto que vive para sempre, Jesus tem um sacerdócio permanente.

[[v58-7-25]]

^<<v58-7-25,25>>^ Portanto ele é capaz de salvar definitivamente aqueles que, por meio dele, aproximam-se de Deus, pois vive sempre para interceder por eles.

[[v58-7-26]]

^<<v58-7-26,26>>^ É de um sumo sacerdote como este que precisávamos: santo, inculpável, puro, separado dos pecadores, exaltado acima dos céus.

[[v58-7-27]]

^<<v58-7-27,27>>^ Ao contrário dos outros sumos sacerdotes, ele não tem necessidade de oferecer sacrifícios dia após dia, primeiro por seus próprios pecados e, depois, pelos pecados do povo. E ele fez isso de uma vez por todas quando a si mesmo se ofereceu.

[[v58-7-28]]

^<<v58-7-28,28>>^ Pois a Lei constitui sumos sacerdotes a homens que têm fraquezas; mas o juramento, que veio depois da Lei, constitui o Filho, perfeito para sempre.

'''

xref:058-hebreus/058-hebreus-006.adoc#v58-6-0[&#60; Capítulo Anterior] | <<v58-7-0,Topo>> | xref:058-hebreus/058-hebreus-008.adoc#v58-8-0[Próximo Capítulo &#62;]