include::./index.adoc[]

[[v58-12-0]]
=== Hebreus, 12
// nvi ?, NVI - Nova Versão Internacional

[[v58-12-1]]

^<<v58-12-1,1>>^ Portanto, também nós, uma vez que estamos rodeados por tão grande nuvem de testemunhas, livremo-nos de tudo o que nos atrapalha e do pecado que nos envolve, e corramos com perseverança a corrida que nos é proposta,

[[v58-12-2]]

^<<v58-12-2,2>>^ tendo os olhos fitos em Jesus, autor e consumador da nossa fé. Ele, pela alegria que lhe fora proposta, suportou a cruz, desprezando a vergonha, e assentou-se à direita do trono de Deus.

[[v58-12-3]]

^<<v58-12-3,3>>^ Pensem bem naquele que suportou tal oposição dos pecadores contra si mesmo, para que vocês não se cansem nem se desanimem.

[[v58-12-4]]

^<<v58-12-4,4>>^ Na luta contra o pecado, vocês ainda não resistiram até o ponto de derramar o próprio sangue.

[[v58-12-5]]

^<<v58-12-5,5>>^ Vocês se esqueceram da palavra de ânimo que ele lhes dirige como a filhos: "Meu filho, não despreze a disciplina do Senhor, nem se magoe com a sua repreensão,

[[v58-12-6]]

^<<v58-12-6,6>>^ pois o Senhor disciplina a quem ama, e castiga todo aquele a quem aceita como filho".

[[v58-12-7]]

^<<v58-12-7,7>>^ Suportem as dificuldades, recebendo-as como disciplina; Deus os trata como filhos. Pois, qual o filho que não é disciplinado por seu pai?

[[v58-12-8]]

^<<v58-12-8,8>>^ Se vocês não são disciplinados, e a disciplina é para todos os filhos, então vocês não são filhos legítimos, mas sim ilegítimos.

[[v58-12-9]]

^<<v58-12-9,9>>^ Além disso, tínhamos pais humanos que nos disciplinavam, e nós os respeitávamos. Quanto mais devemos submeter-nos ao Pai dos espíritos, para assim vivermos!

[[v58-12-10]]

^<<v58-12-10,10>>^ Nossos pais nos disciplinavam por curto período, segundo lhes parecia melhor; mas Deus nos disciplina para o nosso bem, para que participemos da sua santidade.

[[v58-12-11]]

^<<v58-12-11,11>>^ Nenhuma disciplina parece ser motivo de alegria no momento, mas sim de tristeza. Mais tarde, porém, produz fruto de justiça e paz para aqueles que por ela foram exercitados.

[[v58-12-12]]

^<<v58-12-12,12>>^ Portanto, fortaleçam as mãos enfraquecidas e os joelhos vacilantes.

[[v58-12-13]]

^<<v58-12-13,13>>^ "Façam caminhos retos para os seus pés", para que o manco não se desvie, mas antes seja curado.

[[v58-12-14]]

^<<v58-12-14,14>>^ Esforcem-se para viver em paz com todos e para serem santos; sem santidade ninguém verá o Senhor.

[[v58-12-15]]

^<<v58-12-15,15>>^ Cuidem que ninguém se exclua da graça de Deus. Que nenhuma raiz de amargura brote e cause perturbação, contaminando a muitos.

[[v58-12-16]]

^<<v58-12-16,16>>^ Não haja nenhum imoral ou profano, como Esaú, que por uma única refeição vendeu os seus direitos de herança como filho mais velho.

[[v58-12-17]]

^<<v58-12-17,17>>^ Como vocês sabem, posteriormente, quando quis herdar a bênção, foi rejeitado; e não teve como alterar a sua decisão, embora buscasse a bênção com lágrimas.

[[v58-12-18]]

^<<v58-12-18,18>>^ Vocês não chegaram ao monte que se podia tocar, e que estava chamas, nem às trevas, à escuridão e à tempestade,

[[v58-12-19]]

^<<v58-12-19,19>>^ ao soar da trombeta e ao som de palavras tais, que os ouvintes rogaram que nada mais lhes fosse dito;

[[v58-12-20]]

^<<v58-12-20,20>>^ pois não podiam suportar o que lhes estava sendo ordenado: "Até um animal, se tocar no monte, deve ser apedrejado".

[[v58-12-21]]

^<<v58-12-21,21>>^ O espetáculo era tão terrível que até Moisés disse: "Estou apavorado e trêmulo! "

[[v58-12-22]]

^<<v58-12-22,22>>^ Mas vocês chegaram ao monte Sião, à Jerusalém celestial, à cidade do Deus vivo. Chegaram aos milhares de milhares de anjos em alegre reunião,

[[v58-12-23]]

^<<v58-12-23,23>>^ à igreja dos primogênitos, cujos nomes estão escritos nos céus. Vocês chegaram a Deus, juiz de todos os homens, aos espíritos dos justos aperfeiçoados,

[[v58-12-24]]

^<<v58-12-24,24>>^ a Jesus, mediador de uma nova aliança, e ao sangue aspergido, que fala melhor do que o sangue de Abel.

[[v58-12-25]]

^<<v58-12-25,25>>^ Cuidado! Não rejeitem aquele que fala. Se os que se recusaram a ouvir aquele que os advertia na terra não escaparam, quanto mais nós, se nos desviarmos daquele que nos adverte dos céus?

[[v58-12-26]]

^<<v58-12-26,26>>^ Aquele cuja voz outrora abalou a terra, agora promete: "Ainda uma vez abalarei não apenas a terra, mas também o céu".

[[v58-12-27]]

^<<v58-12-27,27>>^ As palavras "ainda uma vez" indicam a remoção do que pode ser abalado, isto é, coisas criadas, de forma que permaneça o que não pode ser abalado.

[[v58-12-28]]

^<<v58-12-28,28>>^ Portanto, já que estamos recebendo um Reino inabalável, sejamos agradecidos e, assim, adoremos a Deus de modo aceitável, com reverência e temor,

[[v58-12-29]]

^<<v58-12-29,29>>^ pois o nosso "Deus é fogo consumidor! "

'''

xref:058-hebreus/058-hebreus-011.adoc#v58-11-0[&#60; Capítulo Anterior] | <<v58-12-0,Topo>> | xref:058-hebreus/058-hebreus-013.adoc#v58-13-0[Próximo Capítulo &#62;]