include::./index.adoc[]

[[v58-8-0]]
=== Hebreus, 8
// nvi ?, NVI - Nova Versão Internacional

[[v58-8-1]]

^<<v58-8-1,1>>^ O mais importante do que estamos tratando é que temos um sumo sacerdote como esse, o qual se assentou à direita do trono da Majestade nos céus

[[v58-8-2]]

^<<v58-8-2,2>>^ e serve no santuário, no verdadeiro tabernáculo que o Senhor erigiu, e não o homem.

[[v58-8-3]]

^<<v58-8-3,3>>^ Todo sumo sacerdote é constituído para apresentar ofertas e sacrifícios, e por isso era necessário que também este tivesse algo a oferecer.

[[v58-8-4]]

^<<v58-8-4,4>>^ Se ele estivesse na terra, nem seria sumo sacerdote, visto que já existem aqueles que apresentam as ofertas prescritas pela lei.

[[v58-8-5]]

^<<v58-8-5,5>>^ Eles servem num santuário que é cópia e sombra daquele que está nos céus, já que Moisés foi avisado quando estava para construir o tabernáculo: "Tenha o cuidado de fazer tudo segundo o modelo que lhe foi mostrado no monte".

[[v58-8-6]]

^<<v58-8-6,6>>^ Agora, porém, o ministério que Jesus recebeu é superior ao deles, assim como também a aliança da qual ele é mediador é superior à antiga, sendo baseada em promessas superiores.

[[v58-8-7]]

^<<v58-8-7,7>>^ Pois se aquela primeira aliança fosse perfeita, não seria necessário procurar lugar para outra.

[[v58-8-8]]

^<<v58-8-8,8>>^ Deus, porém, achou o povo em falta e disse: "Estão chegando os dias, declara o Senhor, quando farei uma nova aliança com a comunidade de Israel e com a comunidade de Judá.

[[v58-8-9]]

^<<v58-8-9,9>>^ Não será como a aliança que fiz com os seus antepassados quando os tomei pela mão para tirá-los do Egito; visto que eles não permaneceram fiéis à minha aliança, eu me afastei deles", diz o Senhor.

[[v58-8-10]]

^<<v58-8-10,10>>^ "Esta é a aliança que farei com a comunidade de Israel depois daqueles dias", declara o Senhor. "Porei minhas leis em suas mentes e as escreverei em seus corações. Serei o Deus deles, e eles serão o meu povo.

[[v58-8-11]]

^<<v58-8-11,11>>^ Ninguém mais ensinará ao seu próximo nem ao seu irmão, dizendo: ‘Conheça ao Senhor’, porque todos eles me conhecerão, desde o menor até o maior.

[[v58-8-12]]

^<<v58-8-12,12>>^ Porque eu lhes perdoarei a maldade e não me lembrarei mais dos seus pecados".

[[v58-8-13]]

^<<v58-8-13,13>>^ Chamando "nova" esta aliança, ele tornou antiquada a primeira; e o que se torna antiquado e envelhecido, está a ponto de desaparecer.

'''

xref:058-hebreus/058-hebreus-007.adoc#v58-7-0[&#60; Capítulo Anterior] | <<v58-8-0,Topo>> | xref:058-hebreus/058-hebreus-009.adoc#v58-9-0[Próximo Capítulo &#62;]