include::./index.adoc[]

[[v58-2-0]]
=== Hebreus, 2
// nvi ?, NVI - Nova Versão Internacional

[[v58-2-1]]

^<<v58-2-1,1>>^ Por isso é preciso que prestemos maior atenção ao que temos ouvido, para que jamais nos desviemos.

[[v58-2-2]]

^<<v58-2-2,2>>^ Porque se a mensagem transmitida por anjos provou a sua firmeza, e toda transgressão e desobediência recebeu a devida punição,

[[v58-2-3]]

^<<v58-2-3,3>>^ como escaparemos nós, se negligenciarmos tão grande salvação? Esta salvação, primeiramente anunciada pelo Senhor, foi-nos confirmada pelos que a ouviram.

[[v58-2-4]]

^<<v58-2-4,4>>^ Deus também deu testemunho dela por meio de sinais, maravilhas, diversos milagres e dons do Espírito Santo distribuídos de acordo com a sua vontade.

[[v58-2-5]]

^<<v58-2-5,5>>^ Não foi a anjos que ele sujeitou o mundo que há de vir, a respeito do qual estamos falando,

[[v58-2-6]]

^<<v58-2-6,6>>^ mas alguém em certo lugar testemunhou, dizendo: "Que é o homem, para que com ele te importes? E o filho do homem, para que com ele te preocupes?

[[v58-2-7]]

^<<v58-2-7,7>>^ Tu o fizeste um pouco menor do que os anjos e o coroaste de glória e de honra;

[[v58-2-8]]

^<<v58-2-8,8>>^ tudo sujeitaste debaixo dos seus pés". Ao lhe sujeitar todas as coisas, nada deixou que não lhe estivesse sujeito. Agora, porém, ainda não vemos que todas as coisas lhe estejam sujeitas.

[[v58-2-9]]

^<<v58-2-9,9>>^ Vemos, todavia, aquele que por um pouco foi feito menor do que os anjos, Jesus, coroado de honra e glória por ter sofrido a morte, para que, pela graça de Deus, em favor de todos, experimentasse a morte.

[[v58-2-10]]

^<<v58-2-10,10>>^ Ao levar muitos filhos à glória, convinha que Deus, por causa de quem e por meio de quem tudo existe, tornasse perfeito, mediante o sofrimento, o autor da salvação deles.

[[v58-2-11]]

^<<v58-2-11,11>>^ Ora, tanto o que santifica quanto os que são santificados provêm de um só. Por isso Jesus não se envergonha de chamá-los irmãos.

[[v58-2-12]]

^<<v58-2-12,12>>^ Ele diz: "Proclamarei o teu nome a meus irmãos; na assembléia te louvarei".

[[v58-2-13]]

^<<v58-2-13,13>>^ E também: "Nele porei a minha confiança". Novamente ele diz: "Aqui estou eu com os filhos que Deus me deu".

[[v58-2-14]]

^<<v58-2-14,14>>^ Portanto, visto que os filhos são pessoas de carne e sangue, ele também participou dessa condição humana, para que, por sua morte, derrotasse aquele que tem o poder da morte, isto é, o diabo,

[[v58-2-15]]

^<<v58-2-15,15>>^ e libertasse aqueles que durante toda a vida estiveram escravizados pelo medo da morte.

[[v58-2-16]]

^<<v58-2-16,16>>^ Pois é claro que não é a anjos que ele ajuda, mas aos descendentes de Abraão.

[[v58-2-17]]

^<<v58-2-17,17>>^ Por essa razão era necessário que ele se tornasse semelhante a seus irmãos em todos os aspectos, para se tornar sumo sacerdote misericordioso e fiel com relação a Deus e fazer propiciação pelos pecados do povo.

[[v58-2-18]]

^<<v58-2-18,18>>^ Porque, tendo em vista o que ele mesmo sofreu quando tentado, ele é capaz de socorrer aqueles que também estão sendo tentados.

'''

xref:058-hebreus/058-hebreus-001.adoc#v58-1-0[&#60; Capítulo Anterior] | <<v58-2-0,Topo>> | xref:058-hebreus/058-hebreus-003.adoc#v58-3-0[Próximo Capítulo &#62;]