include::./index.adoc[]

[[v58-1-0]]
=== Hebreus, 1
// nvi ?, NVI - Nova Versão Internacional

[[v58-1-1]]

^<<v58-1-1,1>>^ Há muito tempo Deus falou muitas vezes e de várias maneiras aos nossos antepassados por meio dos profetas,

[[v58-1-2]]

^<<v58-1-2,2>>^ mas nestes últimos dias falou-nos por meio do Filho, a quem constituiu herdeiro de todas as coisas e por meio de quem fez o universo.

[[v58-1-3]]

^<<v58-1-3,3>>^ O Filho é o resplendor da glória de Deus e a expressão exata do seu ser, sustentando todas as coisas por sua palavra poderosa. Depois de ter realizado a purificação dos pecados, ele se assentou à direita da Majestade nas alturas,

[[v58-1-4]]

^<<v58-1-4,4>>^ tornando-se tão superior aos anjos quanto o nome que herdou é superior ao deles.

[[v58-1-5]]

^<<v58-1-5,5>>^ Pois a qual dos anjos Deus alguma vez disse: "Tu és meu Filho; eu hoje te gerei"? E outra vez: "Eu serei seu Pai, e ele será meu Filho"?

[[v58-1-6]]

^<<v58-1-6,6>>^ E ainda, quando Deus introduz o Primogênito no mundo, diz: "Todos os anjos de Deus o adorem".

[[v58-1-7]]

^<<v58-1-7,7>>^ Quanto aos anjos, ele diz: "Ele faz dos seus anjos ventos, e dos seus servos, clarões reluzentes".

[[v58-1-8]]

^<<v58-1-8,8>>^ Mas a respeito do Filho, diz: "O teu trono, ó Deus, subsiste para todo o sempre; cetro de eqüidade é o cetro do teu Reino.

[[v58-1-9]]

^<<v58-1-9,9>>^ Amas a justiça e odeias a iniqüidade; por isso, Deus, o teu Deus, escolheu-te dentre os teus companheiros, ungindo-te com óleo de alegria".

[[v58-1-10]]

^<<v58-1-10,10>>^ E também diz: "No princípio, Senhor, firmaste os fundamentos da terra, e os céus são obras das tuas mãos.

[[v58-1-11]]

^<<v58-1-11,11>>^ Eles perecerão, mas tu permanecerás; envelhecerão como vestimentas.

[[v58-1-12]]

^<<v58-1-12,12>>^ Tu os enrolarás como um manto, como roupas eles serão trocados. Mas tu permaneces o mesmo, e os teus dias jamais terão fim".

[[v58-1-13]]

^<<v58-1-13,13>>^ A qual dos anjos Deus alguma vez disse: "Senta-te à minha direita, até que eu faça dos teus inimigos um estrado para os teus pés"?

[[v58-1-14]]

^<<v58-1-14,14>>^ Os anjos não são, todos eles, espíritos ministradores enviados para servir aqueles que hão de herdar a salvação?

'''

xref:057-filemom/057-filemom-001.adoc#v57-1-0[&#60; Capítulo Anterior] | <<v58-1-0,Topo>> | xref:058-hebreus/058-hebreus-002.adoc#v58-2-0[Próximo Capítulo &#62;]