include::./index.adoc[]

[[v58-9-0]]
=== Hebreus, 9
// nvi ?, NVI - Nova Versão Internacional

[[v58-9-1]]

^<<v58-9-1,1>>^ Ora, a primeira aliança tinha regras para a adoração e também um tabernáculo terreno.

[[v58-9-2]]

^<<v58-9-2,2>>^ Foi levantado um tabernáculo; na parte da frente, chamada Lugar Santo, estavam o candelabro, a mesa e os pães da Presença.

[[v58-9-3]]

^<<v58-9-3,3>>^ Por trás do segundo véu havia a parte chamada Santo dos Santos,

[[v58-9-4]]

^<<v58-9-4,4>>^ onde se encontravam o altar de ouro para o incenso e a arca da aliança, totalmente revestida de ouro. Nessa arca estavam o vaso de ouro contendo o maná, a vara de Arão que floresceu e as tábuas da aliança.

[[v58-9-5]]

^<<v58-9-5,5>>^ Acima da arca estavam os querubins da Glória, que com sua sombra cobriam a tampa da arca. A respeito dessas coisas não cabe agora falar detalhadamente.

[[v58-9-6]]

^<<v58-9-6,6>>^ Estando tudo assim preparado, os sacerdotes entravam regularmente no Lugar Santo do tabernáculo, para exercer o seu ministério.

[[v58-9-7]]

^<<v58-9-7,7>>^ No entanto, somente o sumo sacerdote entrava no Santo dos Santos, apenas uma vez por ano, e nunca sem apresentar o sangue do sacrifício, que ele oferecia por si mesmo e pelos pecados que o povo havia cometido por ignorância.

[[v58-9-8]]

^<<v58-9-8,8>>^ Dessa forma, o Espírito Santo estava mostrando que ainda não havia sido manifestado o caminho para o Santo dos Santos enquanto ainda permanecia o primeiro tabernáculo.

[[v58-9-9]]

^<<v58-9-9,9>>^ Isso é uma ilustração para os nossos dias, indicando que as ofertas e os sacrifícios oferecidos não podiam dar ao adorador uma consciência perfeitamente limpa.

[[v58-9-10]]

^<<v58-9-10,10>>^ Eram apenas prescrições que tratavam de comida e bebida e de várias cerimônias de purificação com água; essas ordenanças exteriores foram impostas até o tempo da nova ordem.

[[v58-9-11]]

^<<v58-9-11,11>>^ Quando Cristo veio como sumo sacerdote dos benefícios agora presentes, ele adentrou o maior e mais perfeito tabernáculo, não feito pelo homem, isto é, não pertencente a esta criação.

[[v58-9-12]]

^<<v58-9-12,12>>^ Não por meio de sangue de bodes e novilhos, mas pelo seu próprio sangue, ele entrou no Santo dos Santos, uma vez por todas, e obteve eterna redenção.

[[v58-9-13]]

^<<v58-9-13,13>>^ Ora, se o sangue de bodes e touros e as cinzas de uma novilha espalhadas sobre os que estão cerimonialmente impuros os santificam de forma que se tornam exteriormente puros,

[[v58-9-14]]

^<<v58-9-14,14>>^ quanto mais, então, o sangue de Cristo, que pelo Espírito eterno se ofereceu de forma imaculada a Deus, purificará a nossa consciência de atos que levam à morte, de modo que sirvamos ao Deus vivo!

[[v58-9-15]]

^<<v58-9-15,15>>^ Por essa razão, Cristo é o mediador de uma nova aliança para que os que são chamados recebam a promessa da herança eterna, visto que ele morreu como resgate pelas transgressões cometidas sob a primeira aliança.

[[v58-9-16]]

^<<v58-9-16,16>>^ No caso de um testamento, é necessário que comprove a morte daquele que o fez;

[[v58-9-17]]

^<<v58-9-17,17>>^ pois um testamento só é validado no caso de morte, uma vez que nunca vigora enquanto está vivo aquele que o fez.

[[v58-9-18]]

^<<v58-9-18,18>>^ Por isso, nem a primeira aliança foi sancionada sem sangue.

[[v58-9-19]]

^<<v58-9-19,19>>^ Quando Moisés terminou de proclamar todos os mandamentos da Lei a todo o povo, levou sangue de novilhos e de bodes, juntamente com água, lã vermelha e ramos de hissopo, e aspergiu o próprio livro e todo o povo, dizendo:

[[v58-9-20]]

^<<v58-9-20,20>>^ "Este é o sangue da aliança que Deus ordenou que vocês obedeçam".

[[v58-9-21]]

^<<v58-9-21,21>>^ Da mesma forma, aspergiu com o sangue o tabernáculo e todos os utensílios das suas cerimônias.

[[v58-9-22]]

^<<v58-9-22,22>>^ De fato, segundo a Lei, quase todas as coisas são purificadas com sangue, e sem derramamento de sangue não há perdão.

[[v58-9-23]]

^<<v58-9-23,23>>^ Portanto, era necessário que as cópias das coisas que estão nos céus fossem purificadas com esses sacrifícios, mas as próprias coisas celestiais com sacrifícios superiores.

[[v58-9-24]]

^<<v58-9-24,24>>^ Pois Cristo não entrou em santuário feito por homens, uma simples representação do verdadeiro; ele entrou no próprio céu, para agora se apresentar diante de Deus em nosso favor;

[[v58-9-25]]

^<<v58-9-25,25>>^ não, porém, para se oferecer repetidas vezes à semelhança do sumo sacerdote que entra no Santo dos Santos todos os anos, com sangue alheio.

[[v58-9-26]]

^<<v58-9-26,26>>^ Se assim fosse, Cristo precisaria sofrer muitas vezes, desde o começo do mundo. Mas agora ele apareceu uma vez por todas no fim dos tempos, para aniquilar o pecado mediante o sacrifício de si mesmo.

[[v58-9-27]]

^<<v58-9-27,27>>^ Da mesma forma, como o homem está destinado a morrer uma só vez e depois disso enfrentar o juízo,

[[v58-9-28]]

^<<v58-9-28,28>>^ assim também Cristo foi oferecido em sacrifício uma única vez, para tirar os pecados de muitos; e aparecerá segunda vez, não para tirar o pecado, mas para trazer salvação aos que o aguardam.

'''

xref:058-hebreus/058-hebreus-008.adoc#v58-8-0[&#60; Capítulo Anterior] | <<v58-9-0,Topo>> | xref:058-hebreus/058-hebreus-010.adoc#v58-10-0[Próximo Capítulo &#62;]