include::./index.adoc[]

[[v63-1-0]]
=== 2 João, 1
// nvi ?, NVI - Nova Versão Internacional

[[v63-1-1]]

^<<v63-1-1,1>>^ O presbítero à senhora eleita e aos seus filhos, a quem amo na verdade, — e não apenas eu os amo, mas também todos os que conhecem a verdade —

[[v63-1-2]]

^<<v63-1-2,2>>^ por causa da verdade que permanece em nós e estará conosco para sempre.

[[v63-1-3]]

^<<v63-1-3,3>>^ A graça, a misericórdia e a paz da parte de Deus Pai e de Jesus Cristo, seu Filho, estarão conosco em verdade e em amor.

[[v63-1-4]]

^<<v63-1-4,4>>^ Ao encontrar alguns dos seus filhos, muito me alegrei, pois eles estão andando na verdade, conforme o mandamento que recebemos do Pai.

[[v63-1-5]]

^<<v63-1-5,5>>^ E agora eu lhe peço, senhora — não como se estivesse escrevendo um mandamento novo, o que já tínhamos desde o princípio — que nos amemos uns aos outros.

[[v63-1-6]]

^<<v63-1-6,6>>^ E este é o amor: que andemos em obediência aos seus mandamentos. Como vocês já têm ouvido desde o princípio, o mandamento é este: que vocês andem em amor.

[[v63-1-7]]

^<<v63-1-7,7>>^ De fato, muitos enganadores têm saído pelo mundo, os quais não confessam que Jesus Cristo veio em corpo. Tal é o enganador e o anticristo.

[[v63-1-8]]

^<<v63-1-8,8>>^ Tenham cuidado, para que vocês não destruam o fruto do nosso trabalho, antes sejam recompensados plenamente.

[[v63-1-9]]

^<<v63-1-9,9>>^ Todo aquele que não permanece no ensino de Cristo, mas vai além dele, não tem Deus; quem permanece no ensino tem o Pai e também o Filho.

[[v63-1-10]]

^<<v63-1-10,10>>^ Se alguém chega a vocês e não trouxer esse ensino, não o recebam em casa nem o saúdem.

[[v63-1-11]]

^<<v63-1-11,11>>^ Pois quem o saúda torna-se participante das suas obras malignas.

[[v63-1-12]]

^<<v63-1-12,12>>^ Tenho muito que lhes escrever, mas não é meu propósito fazê-lo com papel e tinta. Em vez disso, espero visitá-los e falar com vocês face a face, para que a nossa alegria seja completa.

[[v63-1-13]]

^<<v63-1-13,13>>^ Os filhos da sua irmã eleita lhe enviam saudações.

'''

xref:062-1-joao/062-1-joao-005.adoc#v62-5-0[&#60; Capítulo Anterior] | <<v63-1-0,Topo>> | xref:064-3-joao/064-3-joao-001.adoc#v64-1-0[Próximo Capítulo &#62;]