include::./index.adoc[]

[[v53-3-0]]
=== 2 Tessalonicenses, 3
// nvi ?, NVI - Nova Versão Internacional

[[v53-3-1]]

^<<v53-3-1,1>>^ Finalmente, irmãos, orem por nós, para que a palavra do Senhor se propague rapidamente e receba a hora merecida, como aconteceu entre vocês.

[[v53-3-2]]

^<<v53-3-2,2>>^ Orem também para que sejamos libertos dos homens perversos e maus, pois a fé não é de todos.

[[v53-3-3]]

^<<v53-3-3,3>>^ Mas o Senhor é fiel; ele os fortalecerá e os guardará do Maligno.

[[v53-3-4]]

^<<v53-3-4,4>>^ Confiamos no Senhor que vocês estão fazendo e continuarão a fazer as coisas que lhes ordenamos.

[[v53-3-5]]

^<<v53-3-5,5>>^ O Senhor conduza os seus corações ao amor de Deus e à perseverança de Cristo.

[[v53-3-6]]

^<<v53-3-6,6>>^ Irmãos, em nome do nosso Senhor Jesus Cristo nós lhes ordenamos que se afastem de todo irmão que vive ociosamente e não conforme a tradição que receberam de nós.

[[v53-3-7]]

^<<v53-3-7,7>>^ Pois vocês mesmos sabem como devem seguir o nosso exemplo, porque não vivemos ociosamente quando estivemos entre vocês,

[[v53-3-8]]

^<<v53-3-8,8>>^ nem comemos coisa alguma à custa de ninguém. Pelo contrário, trabalhamos arduamente e com fadiga, dia e noite, para não sermos pesados a nenhum de vocês,

[[v53-3-9]]

^<<v53-3-9,9>>^ não por que não tivéssemos tal direito, mas para que nos tornássemos um modelo para ser imitado por vocês.

[[v53-3-10]]

^<<v53-3-10,10>>^ Quando ainda estávamos com vocês, nós lhes ordenamos isto: se alguém não quiser trabalhar, também não coma.

[[v53-3-11]]

^<<v53-3-11,11>>^ Pois ouvimos que alguns de vocês estão ociosos; não trabalham, mas andam se intrometendo na vida alheia.

[[v53-3-12]]

^<<v53-3-12,12>>^ A tais pessoas ordenamos e exortamos no Senhor Jesus Cristo que trabalhem tranqüilamente e comam o seu próprio pão.

[[v53-3-13]]

^<<v53-3-13,13>>^ Quanto a vocês, irmãos, nunca se cansem de fazer o bem.

[[v53-3-14]]

^<<v53-3-14,14>>^ Se alguém não obedecer à nossa palavra por esta carta, marquem-no e não se associem com ele, para que se sinta envergonhado;

[[v53-3-15]]

^<<v53-3-15,15>>^ contudo, não o considerem como inimigo, mas chamem a atenção dele como irmão.

[[v53-3-16]]

^<<v53-3-16,16>>^ O próprio Senhor da paz lhes dê a paz em todo o tempo e de todas as formas. O Senhor seja com todos vocês.

[[v53-3-17]]

^<<v53-3-17,17>>^ Eu, Paulo, escrevo esta saudação de próprio punho, a qual é um sinal em todas as minhas cartas. É dessa forma que escrevo.

[[v53-3-18]]

^<<v53-3-18,18>>^ A graça de nosso Senhor Jesus Cristo seja com todos vocês.

'''

xref:053-2-tessalonicenses/053-2-tessalonicenses-002.adoc#v53-2-0[&#60; Capítulo Anterior] | <<v53-3-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-001.adoc#v54-1-0[Próximo Capítulo &#62;]