include::./index.adoc[]

[[v53-2-0]]
=== 2 Tessalonicenses, 2
// nvi ?, NVI - Nova Versão Internacional

[[v53-2-1]]

^<<v53-2-1,1>>^ Irmãos, quanto à vinda de nosso Senhor Jesus Cristo e à nossa reencontro com ele, rogamos a vocês

[[v53-2-2]]

^<<v53-2-2,2>>^ que não se deixem abalar nem alarmar tão facilmente, quer por profecia, quer por palavra, quer por carta supostamente vinda de nós, como se o dia do Senhor já tivesse chegado.

[[v53-2-3]]

^<<v53-2-3,3>>^ Não deixem que ninguém os engane de modo algum. Antes daquele dia virá a apostasia e, então, será revelado o homem do pecado, o filho da perdição.

[[v53-2-4]]

^<<v53-2-4,4>>^ Este se opõe e se exalta acima de tudo o que se chama Deus ou é objeto de adoração, a ponto de se assentar no santuário de Deus, proclamando que ele mesmo é Deus.

[[v53-2-5]]

^<<v53-2-5,5>>^ Não se lembram de que quando eu ainda estava com vocês costumava lhes falar essas coisas?

[[v53-2-6]]

^<<v53-2-6,6>>^ E agora vocês sabem o que o está detendo, para que ele seja revelado no seu devido tempo.

[[v53-2-7]]

^<<v53-2-7,7>>^ A verdade é que o mistério da iniqüidade já está em ação, restando apenas que seja afastado aquele que agora o detém.

[[v53-2-8]]

^<<v53-2-8,8>>^ Então será revelado o perverso, a quem o Senhor Jesus matará com o sopro de sua boca e destruirá pela manifestação de sua vinda.

[[v53-2-9]]

^<<v53-2-9,9>>^ A vinda desse perverso é segundo a ação de Satanás, com todo o poder, com sinais e com maravilhas enganadoras.

[[v53-2-10]]

^<<v53-2-10,10>>^ Ele fará uso de todas as formas de engano da injustiça para os que estão perecendo, porquanto rejeitaram o amor à verdade que os poderia salvar.

[[v53-2-11]]

^<<v53-2-11,11>>^ Por essa razão Deus lhes envia um poder sedutor, a fim de que creiam na mentira,

[[v53-2-12]]

^<<v53-2-12,12>>^ e sejam condenados todos os que não creram na verdade, mas tiveram prazer na injustiça.

[[v53-2-13]]

^<<v53-2-13,13>>^ Mas nós, devemos sempre dar graças a Deus por vocês, irmãos amados pelo Senhor, porque desde o princípio Deus os escolheu para serem salvos mediante a obra santificadora do Espírito e a fé na verdade.

[[v53-2-14]]

^<<v53-2-14,14>>^ Ele os chamou para isso por meio de nosso evangelho, a fim de tomarem posse da glória de nosso Senhor Jesus Cristo.

[[v53-2-15]]

^<<v53-2-15,15>>^ Portanto, irmãos, permaneçam firmes e apeguem-se às tradições que lhes foram ensinadas, quer de viva voz, quer por carta nossa.

[[v53-2-16]]

^<<v53-2-16,16>>^ Que o próprio Senhor Jesus Cristo e Deus nosso Pai, que nos amou e nos deu eterna consolação e boa esperança pela graça,

[[v53-2-17]]

^<<v53-2-17,17>>^ dê ânimo aos seus corações e os fortaleça para fazerem sempre o bem, tanto em atos como em palavras.

'''

xref:053-2-tessalonicenses/053-2-tessalonicenses-001.adoc#v53-1-0[&#60; Capítulo Anterior] | <<v53-2-0,Topo>> | xref:053-2-tessalonicenses/053-2-tessalonicenses-003.adoc#v53-3-0[Próximo Capítulo &#62;]