include::./index.adoc[]

[[v53-1-0]]
=== 2 Tessalonicenses, 1
// nvi ?, NVI - Nova Versão Internacional

[[v53-1-1]]

^<<v53-1-1,1>>^ Paulo, Silvano e Timóteo, à igreja dos tessalonicenses, em Deus nosso Pai e no Senhor Jesus Cristo:

[[v53-1-2]]

^<<v53-1-2,2>>^ A vocês, graça e paz da parte de Deus Pai e do Senhor Jesus Cristo.

[[v53-1-3]]

^<<v53-1-3,3>>^ Irmãos, devemos sempre dar graças a Deus por vocês; e isso é apropriado, porque a fé que vocês têm cresce cada vez mais, e muito aumenta o amor que todos vocês têm uns pelos outros.

[[v53-1-4]]

^<<v53-1-4,4>>^ Por esta causa nos gloriamos em vocês entre as igrejas de Deus pela perseverança e fé que mostram em todas as perseguições e tribulações que vocês estão suportando.

[[v53-1-5]]

^<<v53-1-5,5>>^ Elas dão prova do justo juízo de Deus, que deseja que vocês sejam considerados dignos do seu Reino, pelo qual vocês também estão sofrendo.

[[v53-1-6]]

^<<v53-1-6,6>>^ É justo da parte de Deus retribuir com tribulação aos que lhes causam tribulação,

[[v53-1-7]]

^<<v53-1-7,7>>^ e dar alívio a vocês, que estão sendo atribulados, e a nós também. Isso acontecerá quando o Senhor Jesus for revelado lá do céu, com os seus anjos poderosos, em meio a chamas flamejantes.

[[v53-1-8]]

^<<v53-1-8,8>>^ Ele punirá os que não conhecem a Deus e os que não obedecem ao evangelho de nosso Senhor Jesus.

[[v53-1-9]]

^<<v53-1-9,9>>^ Eles sofrerão a pena de destruição eterna, a separação da presença do Senhor e da majestade do seu poder.

[[v53-1-10]]

^<<v53-1-10,10>>^ Isso acontecerá no dia em que ele vier para ser glorificado em seus santos e admirado em todos os que creram, inclusive vocês que creram em nosso testemunho.

[[v53-1-11]]

^<<v53-1-11,11>>^ Conscientes disso, oramos constantemente por vocês, para que o nosso Deus os faça dignos da vocação e, com poder, cumpra todo bom propósito e toda obra que procede da fé.

[[v53-1-12]]

^<<v53-1-12,12>>^ Assim o nome de nosso Senhor Jesus será glorificado em vocês, e vocês nele, segundo a graça de nosso Deus e do Senhor Jesus Cristo.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-005.adoc#v52-5-0[&#60; Capítulo Anterior] | <<v53-1-0,Topo>> | xref:053-2-tessalonicenses/053-2-tessalonicenses-002.adoc#v53-2-0[Próximo Capítulo &#62;]