include::./index.adoc[]

[[v19-137-0]]
=== Salmos, 137
// nvi ?, NVI - Nova Versão Internacional

[[v19-137-1]]

^<<v19-137-1,1>>^ Junto aos rios da Babilônia nós nos sentamos e choramos com saudade de Sião.

[[v19-137-2]]

^<<v19-137-2,2>>^ Ali, nos salgueiros penduramos as nossas harpas;

[[v19-137-3]]

^<<v19-137-3,3>>^ ali os nossos captores pediam-nos canções, os nossos opressores exigiam canções alegres, dizendo: "Cantem para nós uma das canções de Sião! "

[[v19-137-4]]

^<<v19-137-4,4>>^ Como poderíamos cantar as canções do Senhor numa terra estrangeira?

[[v19-137-5]]

^<<v19-137-5,5>>^ Que a minha mão direita definhe, ó Jerusalém, se eu me esquecer de ti!

[[v19-137-6]]

^<<v19-137-6,6>>^ Que a língua se me grude ao céu da boca, se eu não me lembrar de ti, e não considerar Jerusalém a minha maior alegria!

[[v19-137-7]]

^<<v19-137-7,7>>^ Lembra-te, Senhor, dos edomitas e do que fizeram quando Jerusalém foi destruída, pois gritavam: "Arrasem-na! Arrasem-na até aos alicerces! "

[[v19-137-8]]

^<<v19-137-8,8>>^ Ó cidade de Babilônia, destinada à destruição, feliz aquele que lhe retribuir o mal que você nos fez!

[[v19-137-9]]

^<<v19-137-9,9>>^ Feliz aquele que pegar os seus filhos e os despedaçar contra a rocha!

'''

xref:019-salmos/019-salmos-136.adoc#v19-136-0[&#60; Capítulo Anterior] | <<v19-137-0,Topo>> | xref:019-salmos/019-salmos-138.adoc#v19-138-0[Próximo Capítulo &#62;]