include::./index.adoc[]

[[v19-19-0]]
=== Salmos, 19
// nvi ?, NVI - Nova Versão Internacional

[[v19-19-1]]

^<<v19-19-1,1>>^ Os céus declaram a glória de Deus; o firmamento proclama a obra das suas mãos.

[[v19-19-2]]

^<<v19-19-2,2>>^ Um dia fala disso a outro dia; uma noite o revela a outra noite.

[[v19-19-3]]

^<<v19-19-3,3>>^ Sem discurso nem palavras, não se ouve a sua voz.

[[v19-19-4]]

^<<v19-19-4,4>>^ Mas a sua voz ressoa por toda a terra, e as suas palavras, até os confins do mundo. Nos céus ele armou uma tenda para o sol,

[[v19-19-5]]

^<<v19-19-5,5>>^ que é como um noivo que sai de seu aposento, e se lança em sua carreira com a alegria de um herói.

[[v19-19-6]]

^<<v19-19-6,6>>^ Sai de uma extremidade dos céus e faz o seu trajeto até a outra; nada escapa ao seu calor.

[[v19-19-7]]

^<<v19-19-7,7>>^ A lei do Senhor é perfeita, e revigora a alma. Os testemunhos do Senhor são dignos de confiança, e tornam sábios os inexperientes.

[[v19-19-8]]

^<<v19-19-8,8>>^ Os preceitos do Senhor são justos, e dão alegria ao coração. Os mandamentos do Senhor são límpidos, e trazem luz aos olhos.

[[v19-19-9]]

^<<v19-19-9,9>>^ O temor do Senhor é puro, e dura para sempre. As ordenanças do Senhor são verdadeiras, são todas elas justas.

[[v19-19-10]]

^<<v19-19-10,10>>^ São mais desejáveis do que o ouro, do que muito ouro puro; são mais doces do que o mel, do que as gotas do favo.

[[v19-19-11]]

^<<v19-19-11,11>>^ Por elas o teu servo é advertido; há grande recompensa em obedecer-lhes.

[[v19-19-12]]

^<<v19-19-12,12>>^ Quem pode discernir os próprios erros? Absolve-me dos que desconheço!

[[v19-19-13]]

^<<v19-19-13,13>>^ Também guarda o teu servo dos pecados intencionais; que eles não me dominem! Então serei íntegro, inocente de grande transgressão.

[[v19-19-14]]

^<<v19-19-14,14>>^ Que as palavras da minha boca e a meditação do meu coração sejam agradáveis a ti, Senhor, minha Rocha e meu Resgatador!

'''

xref:019-salmos/019-salmos-018.adoc#v19-18-0[&#60; Capítulo Anterior] | <<v19-19-0,Topo>> | xref:019-salmos/019-salmos-020.adoc#v19-20-0[Próximo Capítulo &#62;]