include::./index.adoc[]

[[v19-69-0]]
=== Salmos, 69
// nvi ?, NVI - Nova Versão Internacional

[[v19-69-1]]

^<<v19-69-1,1>>^ Salva-me, ó Deus!, pois as águas subiram até o meu pescoço.

[[v19-69-2]]

^<<v19-69-2,2>>^ Nas profundezas lamacentas eu me afundo, não tenho onde firmar os pés. Entrei em águas profundas; as correntezas me arrastam.

[[v19-69-3]]

^<<v19-69-3,3>>^ Cansei-me de pedir socorro; minha garganta se abrasa. Meus olhos fraquejam de tanto esperar pelo meu Deus.

[[v19-69-4]]

^<<v19-69-4,4>>^ Os que sem razão me odeiam são mais do que os fios de cabelo da minha cabeça; muitos são os que me prejudicam sem motivo, muitos, os que procuram destruir-me. Sou forçado a devolver o que não roubei.

[[v19-69-5]]

^<<v19-69-5,5>>^ Tu bem sabes como fui insensato, ó Deus; a minha culpa não te é encoberta.

[[v19-69-6]]

^<<v19-69-6,6>>^ Não se decepcionem por minha causa aqueles que esperam em ti, ó Senhor, Senhor dos Exércitos! Não se frustrem por minha causa os que te buscam, ó Deus de Israel!

[[v19-69-7]]

^<<v19-69-7,7>>^ Pois por amor a ti suporto zombaria, e a vergonha cobre-me o rosto.

[[v19-69-8]]

^<<v19-69-8,8>>^ Sou um estrangeiro para os meus irmãos, um estranho até para os filhos da minha mãe;

[[v19-69-9]]

^<<v19-69-9,9>>^ pois o zelo pela tua casa me consome, e os insultos daqueles que te insultam caem sobre mim.

[[v19-69-10]]

^<<v19-69-10,10>>^ Até quando choro e jejuo, tenho que suportar zombaria;

[[v19-69-11]]

^<<v19-69-11,11>>^ quando ponho vestes de lamento, sou motivo de piada.

[[v19-69-12]]

^<<v19-69-12,12>>^ Os que se ajuntam na praça falam de mim, e sou a canção dos bêbados.

[[v19-69-13]]

^<<v19-69-13,13>>^ Mas eu, Senhor, no tempo oportuno, elevo a ti minha oração; responde-me, por teu grande amor, ó Deus, com a tua salvação infalível!

[[v19-69-14]]

^<<v19-69-14,14>>^ Tira-me do atoleiro, não me deixes afundar; liberta-me dos que me odeiam e das águas profundas.

[[v19-69-15]]

^<<v19-69-15,15>>^ Não permitas que as correntezas me arrastem, nem que as profundezas me engulam, nem que a cova feche sobre mim a sua boca!

[[v19-69-16]]

^<<v19-69-16,16>>^ Responde-me, Senhor, pela bondade do teu amor; por tua grande misericórdia, volta-te para mim.

[[v19-69-17]]

^<<v19-69-17,17>>^ Não escondas do teu servo a tua face; responde-me depressa, pois estou em perigo.

[[v19-69-18]]

^<<v19-69-18,18>>^ Aproxima-te e resgata-me; livra-me por causa dos meus inimigos.

[[v19-69-19]]

^<<v19-69-19,19>>^ Tu bem sabes como sofro zombaria, humilhação e vergonha; conheces todos os meus adversários.

[[v19-69-20]]

^<<v19-69-20,20>>^ A zombaria partiu-me o coração; estou em desespero! Supliquei por socorro, nada recebi, por consoladores, e a ninguém encontrei.

[[v19-69-21]]

^<<v19-69-21,21>>^ Puseram fel na minha comida e para matar-me a sede deram-me vinagre.

[[v19-69-22]]

^<<v19-69-22,22>>^ Que a mesa deles se lhes transforme em laço; torne-se retribuição e armadilha.

[[v19-69-23]]

^<<v19-69-23,23>>^ Escureçam-se os seus olhos para que não consigam ver; faze-lhes tremer o corpo sem parar.

[[v19-69-24]]

^<<v19-69-24,24>>^ Despeja sobre eles a tua ira; que o teu furor ardente os alcance.

[[v19-69-25]]

^<<v19-69-25,25>>^ Fique deserto o lugar deles; não haja ninguém que habite nas suas tendas.

[[v19-69-26]]

^<<v19-69-26,26>>^ Pois perseguem aqueles que tu feres e comentam a dor daqueles a quem castigas.

[[v19-69-27]]

^<<v19-69-27,27>>^ Acrescenta-lhes pecado sobre pecado; não os deixes alcançar a tua justiça.

[[v19-69-28]]

^<<v19-69-28,28>>^ Sejam eles tirados do livro da vida e não sejam incluídos no rol dos justos.

[[v19-69-29]]

^<<v19-69-29,29>>^ Grande é a minha aflição e a minha dor! Proteja-me, ó Deus, a tua salvação!

[[v19-69-30]]

^<<v19-69-30,30>>^ Louvarei o nome de Deus com cânticos e proclamarei sua grandeza com ações de graças;

[[v19-69-31]]

^<<v19-69-31,31>>^ isso agradará o Senhor mais do que bois, mais do que touros com seus chifres e cascos.

[[v19-69-32]]

^<<v19-69-32,32>>^ Os necessitados o verão e se alegrarão; a vocês que buscam a Deus, vida ao seu coração!

[[v19-69-33]]

^<<v19-69-33,33>>^ O Senhor ouve o pobre e não despreza o seu povo aprisionado.

[[v19-69-34]]

^<<v19-69-34,34>>^ Louvem-no os céus e a terra, os mares e tudo o que neles se move,

[[v19-69-35]]

^<<v19-69-35,35>>^ pois Deus salvará Sião e reconstruirá as cidades de Judá. Então o povo ali viverá e tomará posse da terra;

[[v19-69-36]]

^<<v19-69-36,36>>^ a descendência dos seus servos a herdará, e nela habitarão os que amam o seu nome.

'''

xref:019-salmos/019-salmos-068.adoc#v19-68-0[&#60; Capítulo Anterior] | <<v19-69-0,Topo>> | xref:019-salmos/019-salmos-070.adoc#v19-70-0[Próximo Capítulo &#62;]