include::./index.adoc[]

[[v19-103-0]]
=== Salmos, 103
// nvi ?, NVI - Nova Versão Internacional

[[v19-103-1]]

^<<v19-103-1,1>>^ Bendiga ao Senhor a minha alma! Bendiga ao Senhor todo o meu ser!

[[v19-103-2]]

^<<v19-103-2,2>>^ Bendiga ao Senhor a minha alma! Não esqueça de nenhuma de suas bênçãos!

[[v19-103-3]]

^<<v19-103-3,3>>^ É ele que perdoa todos os seus pecados e cura todas as suas doenças,

[[v19-103-4]]

^<<v19-103-4,4>>^ que resgata a sua vida da sepultura e o coroa de bondade e compaixão,

[[v19-103-5]]

^<<v19-103-5,5>>^ que enche de bens a sua existência, de modo que a sua juventude se renova como a águia.

[[v19-103-6]]

^<<v19-103-6,6>>^ O Senhor faz justiça e defende a causa dos oprimidos.

[[v19-103-7]]

^<<v19-103-7,7>>^ Ele manifestou os seus caminhos a Moisés, os seus feitos aos israelitas.

[[v19-103-8]]

^<<v19-103-8,8>>^ O Senhor é compassivo e misericordioso, mui paciente e cheio de amor.

[[v19-103-9]]

^<<v19-103-9,9>>^ Não acusa sem cessar nem fica ressentido para sempre;

[[v19-103-10]]

^<<v19-103-10,10>>^ não nos trata conforme os nossos pecados nem nos retribui conforme as nossas iniqüidades.

[[v19-103-11]]

^<<v19-103-11,11>>^ Pois como os céus se elevam acima da terra, assim é grande o seu amor para com os que o temem;

[[v19-103-12]]

^<<v19-103-12,12>>^ e como o Oriente está longe do Ocidente, assim ele afasta para longe de nós as nossas transgressões.

[[v19-103-13]]

^<<v19-103-13,13>>^ Como um pai tem compaixão de seus filhos, assim o Senhor tem compaixão dos que o temem;

[[v19-103-14]]

^<<v19-103-14,14>>^ pois ele sabe do que somos formados; lembra-se de que somos pó.

[[v19-103-15]]

^<<v19-103-15,15>>^ A vida do homem é semelhante à relva; ele floresce como a flor do campo,

[[v19-103-16]]

^<<v19-103-16,16>>^ que se vai quando sopra o vento e nem se sabe mais o lugar que ocupava.

[[v19-103-17]]

^<<v19-103-17,17>>^ Mas o amor leal do Senhor, o seu amor eterno está com os que o temem, e a sua justiça com os filhos dos seus filhos,

[[v19-103-18]]

^<<v19-103-18,18>>^ com os que guardam a sua aliança e se lembram de obedecer aos seus preceitos.

[[v19-103-19]]

^<<v19-103-19,19>>^ O Senhor estabeleceu o seu trono nos céus, e como rei domina sobre tudo o que existe.

[[v19-103-20]]

^<<v19-103-20,20>>^ Bendigam ao Senhor, vocês, seus anjos poderosos, que obedecem à sua palavra.

[[v19-103-21]]

^<<v19-103-21,21>>^ Bendigam ao Senhor, todos os seus exércitos, vocês, seus servos, que cumprem a sua vontade.

[[v19-103-22]]

^<<v19-103-22,22>>^ Bendigam ao Senhor, todas as suas obras em todos os lugares do seu domínio. Bendiga ao Senhor a minha alma!

'''

xref:019-salmos/019-salmos-102.adoc#v19-102-0[&#60; Capítulo Anterior] | <<v19-103-0,Topo>> | xref:019-salmos/019-salmos-104.adoc#v19-104-0[Próximo Capítulo &#62;]