include::./index.adoc[]

[[v19-63-0]]
=== Salmos, 63
// nvi ?, NVI - Nova Versão Internacional

[[v19-63-1]]

^<<v19-63-1,1>>^ Ó Deus, tu és o meu Deus, eu te busco intensamente; a minha alma tem sede de ti! Todo o meu ser anseia por ti, numa terra seca, exausta e sem água.

[[v19-63-2]]

^<<v19-63-2,2>>^ Quero contemplar-te no santuário e avistar o teu poder e a tua glória.

[[v19-63-3]]

^<<v19-63-3,3>>^ O teu amor é melhor do que a vida! Por isso os meus lábios te exaltarão.

[[v19-63-4]]

^<<v19-63-4,4>>^ Eu te bendirei enquanto viver, e em teu nome levantarei as minhas mãos.

[[v19-63-5]]

^<<v19-63-5,5>>^ A minha alma ficará satisfeita como de rico banquete; com lábios jubilosos a minha boca te louvará.

[[v19-63-6]]

^<<v19-63-6,6>>^ Quando me deito lembro-me de ti; penso em ti durante as vigílias da noite.

[[v19-63-7]]

^<<v19-63-7,7>>^ Porque és a minha ajuda, canto de alegria à sombra das tuas asas.

[[v19-63-8]]

^<<v19-63-8,8>>^ A minha alma apega-se a ti; a tua mão direita me sustém.

[[v19-63-9]]

^<<v19-63-9,9>>^ Aqueles, porém, que querem matar-me serão destruídos; descerão às profundezas da terra.

[[v19-63-10]]

^<<v19-63-10,10>>^ Serão entregues à espada e devorados por chacais.

[[v19-63-11]]

^<<v19-63-11,11>>^ Mas o rei se alegrará em Deus; todos os que juram pelo nome de Deus o louvarão, mas as bocas dos mentirosos serão tapadas.

'''

xref:019-salmos/019-salmos-062.adoc#v19-62-0[&#60; Capítulo Anterior] | <<v19-63-0,Topo>> | xref:019-salmos/019-salmos-064.adoc#v19-64-0[Próximo Capítulo &#62;]