include::./index.adoc[]

[[v19-79-0]]
=== Salmos, 79
// nvi ?, NVI - Nova Versão Internacional

[[v19-79-1]]

^<<v19-79-1,1>>^ Ó Deus, as nações invadiram a tua herança, profanaram o teu santo templo, reduziram Jerusalém a ruínas.

[[v19-79-2]]

^<<v19-79-2,2>>^ Deram os cadáveres dos teus servos às aves do céu por alimento, a carne dos teus fiéis, aos animais selvagens.

[[v19-79-3]]

^<<v19-79-3,3>>^ Derramaram o sangue deles como água ao redor de Jerusalém, e não há ninguém para sepultá-los.

[[v19-79-4]]

^<<v19-79-4,4>>^ Somos motivos de zombaria para os nossos vizinhos, de riso e menosprezo para os que vivem ao nosso redor.

[[v19-79-5]]

^<<v19-79-5,5>>^ Até quando, Senhor? Ficarás irado para sempre? Arderá o teu ciúme como o fogo?

[[v19-79-6]]

^<<v19-79-6,6>>^ Derrama a tua ira sobre as nações que não te reconhecem, sobre os reinos que não invocam o teu nome,

[[v19-79-7]]

^<<v19-79-7,7>>^ pois devoraram Jacó, deixando em ruínas a sua terra.

[[v19-79-8]]

^<<v19-79-8,8>>^ Não cobres de nós as maldades dos nossos antepassados; venha depressa ao nosso encontro a tua misericórdia, pois estamos totalmente desanimados!

[[v19-79-9]]

^<<v19-79-9,9>>^ Ajuda-nos, ó Deus, nosso Salvador, para a glória do teu nome; livra-nos e perdoa os nossos pecados, por amor do teu nome.

[[v19-79-10]]

^<<v19-79-10,10>>^ Por que as nações haverão de dizer: "Onde está o Deus deles? " Diante dos nossos olhos, mostra às nações a tua vingança pelo sangue dos teus servos.

[[v19-79-11]]

^<<v19-79-11,11>>^ Cheguem à tua presença os gemidos dos prisioneiros. Pela força do teu braço preserva os condenados à morte.

[[v19-79-12]]

^<<v19-79-12,12>>^ Retribui sete vezes mais aos nossos vizinhos as afrontas com que te insultaram, Senhor!

[[v19-79-13]]

^<<v19-79-13,13>>^ Então nós, o teu povo, as ovelhas das tuas pastagens, para sempre te louvaremos; de geração em geração cantaremos os teus louvores.

'''

xref:019-salmos/019-salmos-078.adoc#v19-78-0[&#60; Capítulo Anterior] | <<v19-79-0,Topo>> | xref:019-salmos/019-salmos-080.adoc#v19-80-0[Próximo Capítulo &#62;]