include::./index.adoc[]

[[v19-138-0]]
=== Salmos, 138
// nvi ?, NVI - Nova Versão Internacional

[[v19-138-1]]

^<<v19-138-1,1>>^ Eu te louvarei, Senhor, de todo o coração; diante dos deuses cantarei louvores a ti.

[[v19-138-2]]

^<<v19-138-2,2>>^ Voltado para o teu santo templo eu me prostrarei e renderei graças ao teu nome, por causa do teu amor e da tua fidelidade; pois exaltaste acima de todas as coisas o teu nome e a tua palavra.

[[v19-138-3]]

^<<v19-138-3,3>>^ Quando clamei, tu me respondeste; deste-me força e coragem.

[[v19-138-4]]

^<<v19-138-4,4>>^ Todos os reis da terra te renderão graças, Senhor, pois saberão das tuas promessas.

[[v19-138-5]]

^<<v19-138-5,5>>^ Celebrarão os feitos do Senhor, pois grande é a glória do Senhor!

[[v19-138-6]]

^<<v19-138-6,6>>^ Embora esteja nas alturas, o Senhor olha para os humildes, e de longe reconhece os arrogantes.

[[v19-138-7]]

^<<v19-138-7,7>>^ Ainda que eu passe por angústias, tu me preservas a vida da ira dos meus inimigos; estendes a tua mão direita e me livras.

[[v19-138-8]]

^<<v19-138-8,8>>^ O Senhor cumprirá o seu propósito para comigo! Teu amor, Senhor, permanece para sempre; não abandones as obras das tuas mãos!

'''

xref:019-salmos/019-salmos-137.adoc#v19-137-0[&#60; Capítulo Anterior] | <<v19-138-0,Topo>> | xref:019-salmos/019-salmos-139.adoc#v19-139-0[Próximo Capítulo &#62;]