include::./index.adoc[]

[[v19-148-0]]
=== Salmos, 148
// nvi ?, NVI - Nova Versão Internacional

[[v19-148-1]]

^<<v19-148-1,1>>^ Aleluia! Louvem o Senhor desde os céus, louvem-no nas alturas!

[[v19-148-2]]

^<<v19-148-2,2>>^ Louvem-no todos os seus anjos, louvem-no todos os seus exércitos celestiais.

[[v19-148-3]]

^<<v19-148-3,3>>^ Louvem-no sol e lua, louvem-no todas as estrelas cintilantes.

[[v19-148-4]]

^<<v19-148-4,4>>^ Louvem-no os mais altos céus e as águas acima do firmamento.

[[v19-148-5]]

^<<v19-148-5,5>>^ Louvem todos eles o nome do Senhor, pois ordenou, e eles foram criados.

[[v19-148-6]]

^<<v19-148-6,6>>^ Ele os estabeleceu em seus lugares para todo o sempre; deu-lhes um decreto que jamais mudará.

[[v19-148-7]]

^<<v19-148-7,7>>^ Louvem o Senhor, vocês que estão na terra, serpentes marinhas e todas as profundezas,

[[v19-148-8]]

^<<v19-148-8,8>>^ relâmpagos e granizo, neve e neblina, vendavais que cumprem o que ele determina,

[[v19-148-9]]

^<<v19-148-9,9>>^ todas as montanhas e colinas, árvores frutíferas e todos os cedros,

[[v19-148-10]]

^<<v19-148-10,10>>^ todos os animais selvagens e os rebanhos domésticos, todos os demais seres vivos e as aves,

[[v19-148-11]]

^<<v19-148-11,11>>^ reis da terra e todas as nações, todos os governantes e juízes da terra,

[[v19-148-12]]

^<<v19-148-12,12>>^ moços e moças, velhos e crianças.

[[v19-148-13]]

^<<v19-148-13,13>>^ Louvem todos o nome do Senhor, pois somente o seu nome é exaltado; a sua majestade está acima da terra e dos céus.

[[v19-148-14]]

^<<v19-148-14,14>>^ Ele concedeu poder ao seu povo, e recebeu louvor de todos os seus fiéis, dos israelitas, povo a quem tanto ama. Aleluia!

'''

xref:019-salmos/019-salmos-147.adoc#v19-147-0[&#60; Capítulo Anterior] | <<v19-148-0,Topo>> | xref:019-salmos/019-salmos-149.adoc#v19-149-0[Próximo Capítulo &#62;]