include::./index.adoc[]

[[v19-102-0]]
=== Salmos, 102
// nvi ?, NVI - Nova Versão Internacional

[[v19-102-1]]

^<<v19-102-1,1>>^ Ouve a minha oração, Senhor! Chegue a ti o meu grito de socorro!

[[v19-102-2]]

^<<v19-102-2,2>>^ Não escondas de mim o teu rosto, quando estou atribulado. Inclina para mim os teus ouvidos; quando eu clamar, responde-me depressa!

[[v19-102-3]]

^<<v19-102-3,3>>^ Esvaem-se os meus dias como fumaça; meus ossos queimam como brasas vivas.

[[v19-102-4]]

^<<v19-102-4,4>>^ Como a relva ressequida está o meu coração; esqueço até de comer!

[[v19-102-5]]

^<<v19-102-5,5>>^ De tanto gemer estou reduzido a pele e osso.

[[v19-102-6]]

^<<v19-102-6,6>>^ Sou como a coruja do deserto, como uma coruja entre as ruínas.

[[v19-102-7]]

^<<v19-102-7,7>>^ Não consigo dormir; tornei-me como um pássaro solitário no telhado.

[[v19-102-8]]

^<<v19-102-8,8>>^ Os meus inimigos zombam de mim o tempo todo; os que me insultam usam o meu nome para lançar maldições.

[[v19-102-9]]

^<<v19-102-9,9>>^ Cinzas são a minha comida, e com lágrimas misturo o que bebo,

[[v19-102-10]]

^<<v19-102-10,10>>^ por causa da tua indignação e da tua ira, pois me rejeitaste e me expulsaste para longe de ti.

[[v19-102-11]]

^<<v19-102-11,11>>^ Meus dias são como sombras crescentes; sou como a relva que vai murchando.

[[v19-102-12]]

^<<v19-102-12,12>>^ Tu, porém, Senhor, no trono reinarás para sempre; o teu nome será lembrado de geração em geração.

[[v19-102-13]]

^<<v19-102-13,13>>^ Tu te levantarás e terás misericórdia de Sião, pois é hora de lhe mostrares compaixão; o tempo certo é chegado.

[[v19-102-14]]

^<<v19-102-14,14>>^ Pois as suas pedras são amadas pelos teus servos, as suas ruínas os enchem de compaixão.

[[v19-102-15]]

^<<v19-102-15,15>>^ Então as nações temerão o nome do Senhor, e todos os reis da terra a sua glória.

[[v19-102-16]]

^<<v19-102-16,16>>^ Porque o Senhor reconstruirá Sião e se manifestará na glória que ele tem.

[[v19-102-17]]

^<<v19-102-17,17>>^ Responderá à oração dos desamparados; as suas súplicas não desprezará.

[[v19-102-18]]

^<<v19-102-18,18>>^ Escreva-se isto para as futuras gerações, e um povo que ainda será criado louvará o Senhor, proclamando:

[[v19-102-19]]

^<<v19-102-19,19>>^ "Do seu santuário nas alturas o Senhor olhou; dos céus observou a terra,

[[v19-102-20]]

^<<v19-102-20,20>>^ para ouvir os gemidos dos prisioneiros e libertar os condenados à morte".

[[v19-102-21]]

^<<v19-102-21,21>>^ Assim o nome do Senhor será anunciado em Sião e o seu louvor, em Jerusalém,

[[v19-102-22]]

^<<v19-102-22,22>>^ quando os povos e os reinos se reunirem para adorar ao Senhor.

[[v19-102-23]]

^<<v19-102-23,23>>^ No meio da minha vida ele me abateu com sua força; abreviou os meus dias.

[[v19-102-24]]

^<<v19-102-24,24>>^ Então pedi: "Ó meu Deus, não me leves no meio dos meus dias. Os teus dias duram por todas as gerações!

[[v19-102-25]]

^<<v19-102-25,25>>^ No princípio firmaste os fundamentos da terra, e os céus são obras das tuas mãos.

[[v19-102-26]]

^<<v19-102-26,26>>^ Eles perecerão, mas tu permanecerás; envelhecerão como vestimentas. Como roupas tu os trocarás e serão jogados fora.

[[v19-102-27]]

^<<v19-102-27,27>>^ Mas tu permaneces o mesmo, e os teus dias jamais terão fim.

[[v19-102-28]]

^<<v19-102-28,28>>^ Os filhos dos teus servos terão uma habitação; os seus descendentes serão estabelecidos na tua presença".

'''

xref:019-salmos/019-salmos-101.adoc#v19-101-0[&#60; Capítulo Anterior] | <<v19-102-0,Topo>> | xref:019-salmos/019-salmos-103.adoc#v19-103-0[Próximo Capítulo &#62;]