include::./index.adoc[]

[[v19-4-0]]
=== Salmos, 4
// nvi ?, NVI - Nova Versão Internacional

[[v19-4-1]]

^<<v19-4-1,1>>^ Responde-me quando clamo, ó Deus que me faz justiça! Dá-me alívio da minha angústia; Tem misericórdia de mim e ouve a minha oração.

[[v19-4-2]]

^<<v19-4-2,2>>^ Até quando vocês, ó poderosos, ultrajarão a minha honra? Até quando estarão amando ilusões e buscando mentiras? Pausa

[[v19-4-3]]

^<<v19-4-3,3>>^ Saibam que o Senhor escolheu o piedoso; o Senhor ouvirá quando eu o invocar.

[[v19-4-4]]

^<<v19-4-4,4>>^ Quando vocês ficarem irados, não pequem; ao deitar-se reflitam nisso, e aquietem-se. Pausa

[[v19-4-5]]

^<<v19-4-5,5>>^ Ofereçam sacrifícios como Deus exige e confiem no Senhor.

[[v19-4-6]]

^<<v19-4-6,6>>^ Muitos perguntam: "Quem nos fará desfrutar o bem? " Faze, ó Senhor, resplandecer sobre nós a luz do teu rosto!

[[v19-4-7]]

^<<v19-4-7,7>>^ Encheste o meu coração de alegria, alegria maior do que a daqueles que têm fartura de trigo e de vinho.

[[v19-4-8]]

^<<v19-4-8,8>>^ Em paz me deito e logo adormeço, pois só tu, Senhor, me fazes viver em segurança.

'''

xref:019-salmos/019-salmos-003.adoc#v19-3-0[&#60; Capítulo Anterior] | <<v19-4-0,Topo>> | xref:019-salmos/019-salmos-005.adoc#v19-5-0[Próximo Capítulo &#62;]