include::./index.adoc[]

[[v19-98-0]]
=== Salmos, 98
// nvi ?, NVI - Nova Versão Internacional

[[v19-98-1]]

^<<v19-98-1,1>>^ Cantem ao Senhor um novo cântico, pois ele fez coisas maravilhosas; a sua mão direita e o seu braço santo lhe deram a vitória!

[[v19-98-2]]

^<<v19-98-2,2>>^ O Senhor anunciou a sua vitória e revelou a sua justiça às nações.

[[v19-98-3]]

^<<v19-98-3,3>>^ Ele se lembrou do seu amor leal e da sua fidelidade para com a casa de Israel; todos os confins da terra viram a vitória do nosso Deus.

[[v19-98-4]]

^<<v19-98-4,4>>^ Aclamem o Senhor todos os habitantes da terra! Louvem-no com cânticos de alegria e ao som de música!

[[v19-98-5]]

^<<v19-98-5,5>>^ Ofereçam música ao Senhor com a harpa, com a harpa e ao som de canções,

[[v19-98-6]]

^<<v19-98-6,6>>^ com cornetas e ao som da trombeta; exultem diante do Senhor, o Rei!

[[v19-98-7]]

^<<v19-98-7,7>>^ Ressoe o mar e tudo o que nele existe, o mundo e os seus habitantes!

[[v19-98-8]]

^<<v19-98-8,8>>^ Batam palmas os rios, e juntos, cantem de alegria os montes;

[[v19-98-9]]

^<<v19-98-9,9>>^ cantem diante do Senhor, porque ele vem, vem julgar a terra; julgará o mundo com justiça e os povos, com retidão.

'''

xref:019-salmos/019-salmos-097.adoc#v19-97-0[&#60; Capítulo Anterior] | <<v19-98-0,Topo>> | xref:019-salmos/019-salmos-099.adoc#v19-99-0[Próximo Capítulo &#62;]