include::./index.adoc[]

[[v19-57-0]]
=== Salmos, 57
// nvi ?, NVI - Nova Versão Internacional

[[v19-57-1]]

^<<v19-57-1,1>>^ Misericórdia, ó Deus; misericórdia, pois em ti a minha alma se refugia. Eu me refugiarei à sombra das tuas asas, até que passe o perigo.

[[v19-57-2]]

^<<v19-57-2,2>>^ Clamo ao Deus Altíssimo, a Deus, que para comigo cumpre o seu propósito.

[[v19-57-3]]

^<<v19-57-3,3>>^ Dos céus ele me envia a salvação, põe em fuga os que me perseguem de perto; Pausa Deus envia o seu amor e a sua fidelidade.

[[v19-57-4]]

^<<v19-57-4,4>>^ Estou em meio a leões, ávidos para devorar; seus dentes são lanças e flechas, suas línguas são espadas afiadas.

[[v19-57-5]]

^<<v19-57-5,5>>^ Sê exaltado, ó Deus, acima dos céus! Sobre toda a terra esteja a tua glória!

[[v19-57-6]]

^<<v19-57-6,6>>^ Preparam armadilhas para os meus pés; fiquei muito abatido. Abriram uma cova no meu caminho, mas foram eles que nela caíram. Pausa

[[v19-57-7]]

^<<v19-57-7,7>>^ Meu coração está firme, ó Deus, meu coração está firme; cantarei ao som de instrumentos!

[[v19-57-8]]

^<<v19-57-8,8>>^ Acorde, minha alma! Acordem, harpa e lira! Vou despertar a alvorada!

[[v19-57-9]]

^<<v19-57-9,9>>^ Eu te louvarei, ó Senhor, entre as nações; cantarei teus louvores entre os povos.

[[v19-57-10]]

^<<v19-57-10,10>>^ Pois o teu amor é tão grande que alcança os céus; a tua fidelidade vai até às nuvens.

[[v19-57-11]]

^<<v19-57-11,11>>^ Sê exaltado, ó Deus, acima dos céus! Sobre toda a terra esteja a tua glória!

'''

xref:019-salmos/019-salmos-056.adoc#v19-56-0[&#60; Capítulo Anterior] | <<v19-57-0,Topo>> | xref:019-salmos/019-salmos-058.adoc#v19-58-0[Próximo Capítulo &#62;]