include::./index.adoc[]

[[v19-92-0]]
=== Salmos, 92
// nvi ?, NVI - Nova Versão Internacional

[[v19-92-1]]

^<<v19-92-1,1>>^ Como é bom render graças ao Senhor e cantar louvores ao teu nome, ó Altíssimo,

[[v19-92-2]]

^<<v19-92-2,2>>^ anunciar de manhã o teu amor leal e de noite a tua fidelidade,

[[v19-92-3]]

^<<v19-92-3,3>>^ ao som da lira de dez cordas e da cítara, e da melodia da harpa.

[[v19-92-4]]

^<<v19-92-4,4>>^ Tu me alegras, Senhor, com os teus feitos; as obras das tuas mãos levam-me a cantar de alegria.

[[v19-92-5]]

^<<v19-92-5,5>>^ Como são grandes as tuas obras, Senhor, como são profundos os teus propósitos!

[[v19-92-6]]

^<<v19-92-6,6>>^ O insensato não entende, o tolo não vê

[[v19-92-7]]

^<<v19-92-7,7>>^ que, embora os ímpios brotem como a erva e floresçam todos os malfeitores, serão destruídos para sempre.

[[v19-92-8]]

^<<v19-92-8,8>>^ Pois tu, Senhor, és exaltado para sempre.

[[v19-92-9]]

^<<v19-92-9,9>>^ Mas os teus inimigos, Senhor, os teus inimigos perecerão; serão dispersos todos os malfeitores!

[[v19-92-10]]

^<<v19-92-10,10>>^ Tu aumentaste a minha força como a do boi selvagem; derramaste sobre mim óleo novo.

[[v19-92-11]]

^<<v19-92-11,11>>^ Os meus olhos contemplaram a derrota dos meus inimigos; os meus ouvidos escutaram a debandada dos meus maldosos agressores.

[[v19-92-12]]

^<<v19-92-12,12>>^ Os justos florescerão como a palmeira, crescerão como o cedro do Líbano;

[[v19-92-13]]

^<<v19-92-13,13>>^ plantados na casa do Senhor, florescerão nos átrios do nosso Deus.

[[v19-92-14]]

^<<v19-92-14,14>>^ Mesmo na velhice darão fruto, permanecerão viçosos e verdejantes,

[[v19-92-15]]

^<<v19-92-15,15>>^ para proclamar que o Senhor é justo. Ele é a minha rocha; nele não há injustiça.

'''

xref:019-salmos/019-salmos-091.adoc#v19-91-0[&#60; Capítulo Anterior] | <<v19-92-0,Topo>> | xref:019-salmos/019-salmos-093.adoc#v19-93-0[Próximo Capítulo &#62;]