include::./index.adoc[]

[[v19-58-0]]
=== Salmos, 58
// nvi ?, NVI - Nova Versão Internacional

[[v19-58-1]]

^<<v19-58-1,1>>^ Será que vocês, poderosos, falam de fato com justiça? Será que vocês, homens, julgam retamente?

[[v19-58-2]]

^<<v19-58-2,2>>^ Não! No coração vocês tramam a injustiça, e na terra as suas mãos espalham a violência.

[[v19-58-3]]

^<<v19-58-3,3>>^ Os ímpios erram o caminho desde o ventre; desviam-se os mentirosos desde que nascem.

[[v19-58-4]]

^<<v19-58-4,4>>^ Seu veneno é como veneno de serpente; tapam os ouvidos, como a cobra que se faz de surda

[[v19-58-5]]

^<<v19-58-5,5>>^ para não ouvir a música dos encantadores, que fazem encantamentos com tanta habilidade.

[[v19-58-6]]

^<<v19-58-6,6>>^ Quebra os dentes deles, ó Deus; arranca, Senhor, as presas desses leões!

[[v19-58-7]]

^<<v19-58-7,7>>^ Desapareçam como a água que escorre! Quando empunharem o arco, caiam sem força as suas flechas!

[[v19-58-8]]

^<<v19-58-8,8>>^ Sejam como a lesma que se derrete pelo caminho; como feto abortado, não vejam eles o sol!

[[v19-58-9]]

^<<v19-58-9,9>>^ Os ímpios serão varridos antes que as suas panelas sintam o calor da lenha, esteja ela verde ou seca.

[[v19-58-10]]

^<<v19-58-10,10>>^ Os justos se alegrarão quando forem vingados, quando banharem seus pés no sangue dos ímpios.

[[v19-58-11]]

^<<v19-58-11,11>>^ Então os homens comentarão: "De fato os justos têm a sua recompensa; com certeza há um Deus que faz justiça na terra".

'''

xref:019-salmos/019-salmos-057.adoc#v19-57-0[&#60; Capítulo Anterior] | <<v19-58-0,Topo>> | xref:019-salmos/019-salmos-059.adoc#v19-59-0[Próximo Capítulo &#62;]