include::./index.adoc[]

[[v19-108-0]]
=== Salmos, 108
// nvi ?, NVI - Nova Versão Internacional

[[v19-108-1]]

^<<v19-108-1,1>>^ Meu coração está firme, ó Deus! Cantarei e louvarei, ó Glória minha!

[[v19-108-2]]

^<<v19-108-2,2>>^ Acordem, harpa e lira! Despertarei a alvorada.

[[v19-108-3]]

^<<v19-108-3,3>>^ Eu te darei graças, ó Senhor, entre os povos; cantarei louvores entre as nações,

[[v19-108-4]]

^<<v19-108-4,4>>^ porque o teu amor leal se eleva muito acima dos céus; a tua fidelidade alcança as nuvens!

[[v19-108-5]]

^<<v19-108-5,5>>^ Exalta-te, ó Deus, acima dos céus; estenda-se a tua glória sobre toda a terra!

[[v19-108-6]]

^<<v19-108-6,6>>^ Salva-nos com a tua mão direita e responde-nos, para que sejam libertos aqueles a quem amas.

[[v19-108-7]]

^<<v19-108-7,7>>^ Do seu santuário Deus falou: "No meu triunfo dividirei Siquém e repartirei o vale de Sucote.

[[v19-108-8]]

^<<v19-108-8,8>>^ Gileade me pertence, e Manassés também; Efraim é o meu capacete, Judá é o meu cetro.

[[v19-108-9]]

^<<v19-108-9,9>>^ Moabe é a pia em que me lavo, em Edom atiro a minha sandália, sobre a Filístia dou meu brado de vitória! "

[[v19-108-10]]

^<<v19-108-10,10>>^ Quem me levará à cidade fortificada? Quem me guiará a Edom?

[[v19-108-11]]

^<<v19-108-11,11>>^ Não foste tu, ó Deus, que nos rejeitaste e deixaste de sair com os nossos exércitos?

[[v19-108-12]]

^<<v19-108-12,12>>^ Dá-nos ajuda contra os adversários, pois inútil é o socorro do homem.

[[v19-108-13]]

^<<v19-108-13,13>>^ Com Deus conquistaremos a vitória, e ele pisará os nossos adversários.

'''

xref:019-salmos/019-salmos-107.adoc#v19-107-0[&#60; Capítulo Anterior] | <<v19-108-0,Topo>> | xref:019-salmos/019-salmos-109.adoc#v19-109-0[Próximo Capítulo &#62;]