include::./index.adoc[]

[[v19-89-0]]
=== Salmos, 89
// nvi ?, NVI - Nova Versão Internacional

[[v19-89-1]]

^<<v19-89-1,1>>^ Cantarei para sempre o amor do Senhor; com minha boca anunciarei a tua fidelidade por todas as gerações.

[[v19-89-2]]

^<<v19-89-2,2>>^ Sei que firme está o teu amor para sempre, e que firmaste nos céus a tua fidelidade.

[[v19-89-3]]

^<<v19-89-3,3>>^ Tu disseste: "Fiz aliança com o meu escolhido, jurei ao meu servo Davi:

[[v19-89-4]]

^<<v19-89-4,4>>^ Estabelecerei a tua linhagem para sempre e firmarei o teu trono por todas as gerações". Pausa

[[v19-89-5]]

^<<v19-89-5,5>>^ Os céus louvam as tuas maravilhas, Senhor, e a tua fidelidade na assembléia dos santos.

[[v19-89-6]]

^<<v19-89-6,6>>^ Pois, quem nos céus poderá comparar-se ao Senhor? Quem dentre os seres celestiais assemelha-se ao Senhor?

[[v19-89-7]]

^<<v19-89-7,7>>^ Na assembléia dos santos Deus é temível, mais do que todos os que o rodeiam.

[[v19-89-8]]

^<<v19-89-8,8>>^ Ó Senhor, Deus dos Exércitos, quem é semelhante a ti? És poderoso, Senhor, envolto em tua fidelidade.

[[v19-89-9]]

^<<v19-89-9,9>>^ Tu dominas o revolto mar; quando se agigantam as suas ondas, tu as acalmas.

[[v19-89-10]]

^<<v19-89-10,10>>^ Esmagaste e mataste o Monstro dos Mares; com teu braço forte dispersaste os teus inimigos.

[[v19-89-11]]

^<<v19-89-11,11>>^ Os céus são teus, e tua também é a terra; fundaste o mundo e tudo o que nele existe.

[[v19-89-12]]

^<<v19-89-12,12>>^ Tu criaste o Norte e o Sul; o Tabor e o Hermom cantam de alegria pelo teu nome.

[[v19-89-13]]

^<<v19-89-13,13>>^ O teu braço é poderoso; a tua mão é forte, exaltada é tua mão direita.

[[v19-89-14]]

^<<v19-89-14,14>>^ A retidão e a justiça são os alicerces do teu trono; o amor e a fidelidade vão à tua frente.

[[v19-89-15]]

^<<v19-89-15,15>>^ Como é feliz o povo que aprendeu a aclamar-te, Senhor, e que anda na luz da tua presença!

[[v19-89-16]]

^<<v19-89-16,16>>^ Sem cessar exultam no teu nome, e alegram-se na tua retidão,

[[v19-89-17]]

^<<v19-89-17,17>>^ pois tu és a nossa glória e a nossa força, e pelo teu favor exaltas a nossa força.

[[v19-89-18]]

^<<v19-89-18,18>>^ Sim, Senhor, tu és o nosso escudo, ó Santo de Israel, tu és o nosso rei.

[[v19-89-19]]

^<<v19-89-19,19>>^ Numa visão falaste um dia, e aos teus fiéis disseste: "Cobri de forças um guerreiro, exaltei um homem escolhido dentre o povo.

[[v19-89-20]]

^<<v19-89-20,20>>^ Encontrei o meu servo Davi; ungi-o com o meu óleo sagrado.

[[v19-89-21]]

^<<v19-89-21,21>>^ A minha mão o susterá, e o meu braço o fará forte.

[[v19-89-22]]

^<<v19-89-22,22>>^ Nenhum inimigo o sujeitará a tributos; nenhum injusto o oprimirá.

[[v19-89-23]]

^<<v19-89-23,23>>^ Esmagarei diante dele os seus adversários e destruirei os seus inimigos.

[[v19-89-24]]

^<<v19-89-24,24>>^ A minha fidelidade e o meu amor o acompanharão, e pelo meu nome aumentará o seu poder.

[[v19-89-25]]

^<<v19-89-25,25>>^ A sua mão dominará até o mar, e a sua mão direita, até os rios.

[[v19-89-26]]

^<<v19-89-26,26>>^ Ele me dirá: ‘Tu és o meu Pai, o meu Deus, a Rocha que me salva’.

[[v19-89-27]]

^<<v19-89-27,27>>^ Também o nomearei meu primogênito, o mais exaltado dos reis da terra.

[[v19-89-28]]

^<<v19-89-28,28>>^ Manterei o meu amor por ele para sempre, e a minha aliança com ele jamais se quebrará.

[[v19-89-29]]

^<<v19-89-29,29>>^ Firmarei a sua linhagem para sempre, o seu trono durará enquanto existirem céus.

[[v19-89-30]]

^<<v19-89-30,30>>^ Se os seus filhos abandonarem a minha lei e não seguirem as minhas ordenanças,

[[v19-89-31]]

^<<v19-89-31,31>>^ se violarem os meus decretos e deixarem de obedecer aos meus mandamentos,

[[v19-89-32]]

^<<v19-89-32,32>>^ com a vara castigarei o seu pecado, e a sua iniqüidade com açoites;

[[v19-89-33]]

^<<v19-89-33,33>>^ mas não afastarei dele o meu amor; jamais desistirei da minha fidelidade.

[[v19-89-34]]

^<<v19-89-34,34>>^ Não violarei a minha aliança nem modificarei as promessas dos meus lábios.

[[v19-89-35]]

^<<v19-89-35,35>>^ De uma vez para sempre jurei pela minha santidade, e não mentirei a Davi,

[[v19-89-36]]

^<<v19-89-36,36>>^ que a sua linhagem permanecerá para sempre, e o seu trono durará como o sol;

[[v19-89-37]]

^<<v19-89-37,37>>^ e será estabelecido para sempre como a lua, a fiel testemunha no céu". Pausa

[[v19-89-38]]

^<<v19-89-38,38>>^ Mas tu o rejeitaste, recusaste-o e te enfureceste com o teu ungido.

[[v19-89-39]]

^<<v19-89-39,39>>^ Revogaste a aliança com o teu servo e desonraste a sua coroa, lançando-a ao chão.

[[v19-89-40]]

^<<v19-89-40,40>>^ Derrubaste todos os seus muros e reduziste a ruínas as suas fortalezas.

[[v19-89-41]]

^<<v19-89-41,41>>^ Todos os que passam o saqueiam; tornou-se motivo de zombaria para os seus vizinhos.

[[v19-89-42]]

^<<v19-89-42,42>>^ Tu exaltaste a mão direita dos seus adversários e encheste de alegria todos os seus inimigos.

[[v19-89-43]]

^<<v19-89-43,43>>^ Tiraste o fio da sua espada e não o apoiaste na batalha.

[[v19-89-44]]

^<<v19-89-44,44>>^ Deste fim ao seu esplendor e atiraste ao chão o seu trono.

[[v19-89-45]]

^<<v19-89-45,45>>^ Encurtaste os dias da sua juventude; com um manto de vergonha o cobriste. Pausa

[[v19-89-46]]

^<<v19-89-46,46>>^ Até quando, Senhor? Para sempre te esconderás? Até quando a tua ira queimará como fogo?

[[v19-89-47]]

^<<v19-89-47,47>>^ Lembra-te de como é passageira a minha vida. Terás criado em vão todos os homens?

[[v19-89-48]]

^<<v19-89-48,48>>^ Que homem pode viver e não ver a morte, ou livrar-se do poder da sepultura? Pausa

[[v19-89-49]]

^<<v19-89-49,49>>^ Ó Senhor, onde está o teu antigo amor, que com fidelidade juraste a Davi?

[[v19-89-50]]

^<<v19-89-50,50>>^ Lembra-te, Senhor, das afrontas que o teu servo tem sofrido, das zombarias que no íntimo tenho que suportar de todos os povos,

[[v19-89-51]]

^<<v19-89-51,51>>^ das zombarias dos teus inimigos, Senhor, com que afrontam a cada passo o teu ungido.

[[v19-89-52]]

^<<v19-89-52,52>>^ Bendito seja o Senhor para sempre! Amém e amém.

'''

xref:019-salmos/019-salmos-088.adoc#v19-88-0[&#60; Capítulo Anterior] | <<v19-89-0,Topo>> | xref:019-salmos/019-salmos-090.adoc#v19-90-0[Próximo Capítulo &#62;]