include::./index.adoc[]

[[v19-39-0]]
=== Salmos, 39
// nvi ?, NVI - Nova Versão Internacional

[[v19-39-1]]

^<<v19-39-1,1>>^ Eu disse: Vigiarei a minha conduta e não pecarei em palavras; porei mordaça em minha boca enquanto os ímpios estiverem na minha presença.

[[v19-39-2]]

^<<v19-39-2,2>>^ Enquanto me calei resignado, e me contive inutilmente, minha angústia aumentou.

[[v19-39-3]]

^<<v19-39-3,3>>^ Meu coração ardia-me no peito e, enquanto eu meditava, o fogo aumentava; então comecei a dizer:

[[v19-39-4]]

^<<v19-39-4,4>>^ Mostra-me, Senhor, o fim da minha vida e o número dos meus dias, para que eu saiba quão frágil sou.

[[v19-39-5]]

^<<v19-39-5,5>>^ Deste aos meus dias o comprimento de um palmo; a duração da minha vida é nada diante de ti. De fato, o homem não passa de um sopro. Pausa

[[v19-39-6]]

^<<v19-39-6,6>>^ Sim, cada um vai e volta como a sombra. Em vão se agita, amontoando riqueza sem saber quem ficará com ela.

[[v19-39-7]]

^<<v19-39-7,7>>^ Mas agora, Senhor, que hei de esperar? Minha esperança está em ti.

[[v19-39-8]]

^<<v19-39-8,8>>^ Livra-me de todas as minhas transgressões; não faças de mim um motivo de zombaria dos tolos.

[[v19-39-9]]

^<<v19-39-9,9>>^ Estou calado! Não posso abrir a boca, pois tu mesmo fizeste isso.

[[v19-39-10]]

^<<v19-39-10,10>>^ Afasta de mim o teu açoite; fui vencido pelo golpe da tua mão.

[[v19-39-11]]

^<<v19-39-11,11>>^ Tu repreendes e disciplinas o homem por causa do seu pecado; como traça destróis o que ele mais valoriza; de fato, o homem não passa de um sopro. Pausa

[[v19-39-12]]

^<<v19-39-12,12>>^ Ouve a minha oração, Senhor; escuta o meu grito de socorro; não sejas indiferente ao meu lamento. Pois sou para ti um estrangeiro, como foram todos os meus antepassados.

[[v19-39-13]]

^<<v19-39-13,13>>^ Desvia de mim os teus olhos, para que eu volte a ter alegria, antes que eu me vá e deixe de existir.

'''

xref:019-salmos/019-salmos-038.adoc#v19-38-0[&#60; Capítulo Anterior] | <<v19-39-0,Topo>> | xref:019-salmos/019-salmos-040.adoc#v19-40-0[Próximo Capítulo &#62;]