include::./index.adoc[]

[[v19-105-0]]
=== Salmos, 105
// nvi ?, NVI - Nova Versão Internacional

[[v19-105-1]]

^<<v19-105-1,1>>^ Dêem graças ao Senhor, proclamem o seu nome; divulguem os seus feitos entre as nações.

[[v19-105-2]]

^<<v19-105-2,2>>^ Cantem para ele e louvem-no; relatem todas as suas maravilhas.

[[v19-105-3]]

^<<v19-105-3,3>>^ Gloriem-se no seu santo nome; alegre-se o coração dos que buscam o Senhor.

[[v19-105-4]]

^<<v19-105-4,4>>^ Recorram ao Senhor e ao seu poder; busquem sempre a sua presença.

[[v19-105-5]]

^<<v19-105-5,5>>^ Lembrem-se das maravilhas que ele fez, dos seus prodígios e das sentenças de juízo que pronunciou,

[[v19-105-6]]

^<<v19-105-6,6>>^ ó descendentes de Abraão, seu servo, ó filhos de Jacó, seus escolhidos.

[[v19-105-7]]

^<<v19-105-7,7>>^ Ele é o Senhor, o nosso Deus; seus decretos são para toda a terra.

[[v19-105-8]]

^<<v19-105-8,8>>^ Ele se lembra para sempre da sua aliança, por mil gerações, da palavra que ordenou,

[[v19-105-9]]

^<<v19-105-9,9>>^ da aliança que fez com Abraão, do juramento que fez a Isaque.

[[v19-105-10]]

^<<v19-105-10,10>>^ Ele o confirmou como decreto a Jacó, a Israel como aliança eterna, quando disse:

[[v19-105-11]]

^<<v19-105-11,11>>^ "Darei a você a terra de Canaã, a herança que lhe pertence".

[[v19-105-12]]

^<<v19-105-12,12>>^ Quando ainda eram poucos, um punhado de peregrinos na terra,

[[v19-105-13]]

^<<v19-105-13,13>>^ e vagueavam de nação em nação, de um reino a outro,

[[v19-105-14]]

^<<v19-105-14,14>>^ ele não permitiu que ninguém os oprimisse, mas a favor deles repreendeu reis, dizendo:

[[v19-105-15]]

^<<v19-105-15,15>>^ "Não toquem nos meus ungidos; não maltratem os meus profetas".

[[v19-105-16]]

^<<v19-105-16,16>>^ Ele mandou vir fome sobre a terra e destruiu todo o seu sustento;

[[v19-105-17]]

^<<v19-105-17,17>>^ mas enviou um homem adiante deles, José, que foi vendido como escravo.

[[v19-105-18]]

^<<v19-105-18,18>>^ Machucaram-lhe os pés com correntes e com ferros prenderam-lhe o pescoço,

[[v19-105-19]]

^<<v19-105-19,19>>^ até cumprir-se a sua predição, e a palavra do Senhor confirmar o que dissera.

[[v19-105-20]]

^<<v19-105-20,20>>^ O rei mandou soltá-lo, o governante dos povos o libertou.

[[v19-105-21]]

^<<v19-105-21,21>>^ Ele o constituiu senhor de seu palácio e administrador de todos os seus bens,

[[v19-105-22]]

^<<v19-105-22,22>>^ para instruir os seus oficiais como desejasse e ensinar a sabedoria às autoridades do rei.

[[v19-105-23]]

^<<v19-105-23,23>>^ Então Israel foi para o Egito, Jacó viveu como estrangeiro na terra de Cam.

[[v19-105-24]]

^<<v19-105-24,24>>^ Deus fez proliferar o seu povo, tornou-o mais poderoso do que os seus adversários,

[[v19-105-25]]

^<<v19-105-25,25>>^ e mudou o coração deles para que odiassem o seu povo, para que tramassem contra os seus servos.

[[v19-105-26]]

^<<v19-105-26,26>>^ Então enviou seu servo Moisés, e Arão, a quem tinha escolhido,

[[v19-105-27]]

^<<v19-105-27,27>>^ por meio dos quais realizou os seus sinais miraculosos e as suas maravilhas na terra de Cam.

[[v19-105-28]]

^<<v19-105-28,28>>^ Ele enviou trevas, e houve trevas, e eles não se rebelaram contra as suas palavras.

[[v19-105-29]]

^<<v19-105-29,29>>^ Ele transformou as águas deles em sangue, causando a morte dos seus peixes.

[[v19-105-30]]

^<<v19-105-30,30>>^ A terra deles ficou infestada de rãs, até mesmo os aposentos reais.

[[v19-105-31]]

^<<v19-105-31,31>>^ Ele ordenou, e enxames de moscas e piolhos invadiram o território deles.

[[v19-105-32]]

^<<v19-105-32,32>>^ Deu-lhes granizo, em vez de chuva, e raios flamejantes por toda a terra deles;

[[v19-105-33]]

^<<v19-105-33,33>>^ arrasou as suas videiras e figueiras e destruiu as árvores do seu território.

[[v19-105-34]]

^<<v19-105-34,34>>^ Ordenou, e vieram enxames de gafanhotos, gafanhotos inumeráveis,

[[v19-105-35]]

^<<v19-105-35,35>>^ e devoraram toda a vegetação daquela terra, e consumiram tudo o que a lavoura produziu.

[[v19-105-36]]

^<<v19-105-36,36>>^ Depois matou todos os primogênitos da terra deles, todas as primícias da virilidade deles.

[[v19-105-37]]

^<<v19-105-37,37>>^ Ele tirou de lá Israel, que saiu cheio de prata e ouro. Não havia em suas tribos quem fraquejasse.

[[v19-105-38]]

^<<v19-105-38,38>>^ Os egípcios alegraram-se quando eles saíram, pois estavam com verdadeiro pavor dos israelitas.

[[v19-105-39]]

^<<v19-105-39,39>>^ Ele estendeu uma nuvem para lhes dar sombra, e fogo para iluminar a noite.

[[v19-105-40]]

^<<v19-105-40,40>>^ Pediram, e ele enviou codornizes, e saciou-os com pão do céu.

[[v19-105-41]]

^<<v19-105-41,41>>^ Ele fendeu a rocha, e jorrou água, que escorreu como um rio pelo deserto.

[[v19-105-42]]

^<<v19-105-42,42>>^ Pois ele se lembrou da santa promessa que fizera ao seu servo Abraão.

[[v19-105-43]]

^<<v19-105-43,43>>^ Fez sair cheio de júbilo o seu povo, e os seus escolhidos, com cânticos alegres.

[[v19-105-44]]

^<<v19-105-44,44>>^ Deu-lhes as terras das nações, e eles tomaram posse do fruto do trabalho de outros povos,

[[v19-105-45]]

^<<v19-105-45,45>>^ para que obedecessem aos seus decretos e guardassem as suas leis. Aleluia!

'''

xref:019-salmos/019-salmos-104.adoc#v19-104-0[&#60; Capítulo Anterior] | <<v19-105-0,Topo>> | xref:019-salmos/019-salmos-106.adoc#v19-106-0[Próximo Capítulo &#62;]