include::./index.adoc[]

[[v19-104-0]]
=== Salmos, 104
// nvi ?, NVI - Nova Versão Internacional

[[v19-104-1]]

^<<v19-104-1,1>>^ Bendiga ao Senhor a minha alma! Ó Senhor, meu Deus, tu és tão grandioso! Estás vestido de majestade e esplendor!

[[v19-104-2]]

^<<v19-104-2,2>>^ Envolto de luz como numa veste, ele estende os céus como uma tenda,

[[v19-104-3]]

^<<v19-104-3,3>>^ e põe sobre as águas dos céus as vigas dos seus aposentos. Faz das nuvens a sua carruagem e cavalga nas asas do vento.

[[v19-104-4]]

^<<v19-104-4,4>>^ Faz dos ventos seus mensageiros e dos clarões reluzentes seus servos.

[[v19-104-5]]

^<<v19-104-5,5>>^ Ele firmou a terra sobre os seus fundamentos para que jamais se abale;

[[v19-104-6]]

^<<v19-104-6,6>>^ com as torrentes do abismo a cobriste, como se fossem uma veste; as águas subiram acima dos montes.

[[v19-104-7]]

^<<v19-104-7,7>>^ Diante das tuas ameaças as águas fugiram, puseram-se em fuga ao som do teu trovão;

[[v19-104-8]]

^<<v19-104-8,8>>^ subiram pelos montes e escorreram pelos vales, para os lugares que tu lhes designaste.

[[v19-104-9]]

^<<v19-104-9,9>>^ Estabeleceste um limite que não podem ultrapassar; jamais tornarão a cobrir a terra.

[[v19-104-10]]

^<<v19-104-10,10>>^ Fazes jorrar as nascentes nos vales e correrem as águas entre os montes;

[[v19-104-11]]

^<<v19-104-11,11>>^ delas bebem todos os animais selvagens, e os jumentos selvagens saciam a sua sede.

[[v19-104-12]]

^<<v19-104-12,12>>^ As aves do céu fazem ninho junto às águas e entre os galhos põem-se a cantar.

[[v19-104-13]]

^<<v19-104-13,13>>^ Dos seus aposentos celestes ele rega os montes; sacia-se a terra com o fruto das tuas obras!

[[v19-104-14]]

^<<v19-104-14,14>>^ É ele que faz crescer o pasto para o gado, e as plantas que o homem cultiva, para da terra tirar o alimento:

[[v19-104-15]]

^<<v19-104-15,15>>^ o vinho, que alegra o coração do homem; o azeite, que faz brilhar o rosto, e o pão que sustenta o seu vigor.

[[v19-104-16]]

^<<v19-104-16,16>>^ As árvores do Senhor são bem regadas, os cedros do Líbano que ele plantou;

[[v19-104-17]]

^<<v19-104-17,17>>^ nelas os pássaros fazem ninho, e nos pinheiros a cegonha tem o seu lar.

[[v19-104-18]]

^<<v19-104-18,18>>^ Os montes elevados pertencem aos bodes selvagens, e os penhascos são um refúgio para os coelhos.

[[v19-104-19]]

^<<v19-104-19,19>>^ Ele fez a lua para marcar estações; o sol sabe quando deve se pôr.

[[v19-104-20]]

^<<v19-104-20,20>>^ Trazes trevas, e cai a noite, quando os animais da floresta vagueiam.

[[v19-104-21]]

^<<v19-104-21,21>>^ Os leões rugem à procura da presa, buscando de Deus o alimento,

[[v19-104-22]]

^<<v19-104-22,22>>^ mas ao nascer do sol eles se vão e voltam a deitar-se em suas tocas.

[[v19-104-23]]

^<<v19-104-23,23>>^ Então o homem sai para o seu trabalho, para o seu labor até o entardecer.

[[v19-104-24]]

^<<v19-104-24,24>>^ Quantas são as tuas obras, Senhor! Fizeste todas elas com sabedoria! A terra está cheia de seres que criaste.

[[v19-104-25]]

^<<v19-104-25,25>>^ Eis o mar, imenso e vasto. Nele vivem inúmeras criaturas, seres vivos, pequenos e grandes.

[[v19-104-26]]

^<<v19-104-26,26>>^ Nele passam os navios, e também o Leviatã, que formaste para com ele brincar.

[[v19-104-27]]

^<<v19-104-27,27>>^ Todos eles esperam em ti para que lhes dês o alimento no tempo certo;

[[v19-104-28]]

^<<v19-104-28,28>>^ tu lhes dás, e eles o recolhem, abres a tua mão, e saciam-se de coisas boas.

[[v19-104-29]]

^<<v19-104-29,29>>^ Quando escondes o rosto, entram em pânico; quando lhes retiras o fôlego, morrem e voltam ao pó.

[[v19-104-30]]

^<<v19-104-30,30>>^ Quando sopras o teu fôlego, eles são criados, e renovas a face da terra.

[[v19-104-31]]

^<<v19-104-31,31>>^ Perdure para sempre a glória do Senhor! Alegre-se o Senhor em seus feitos!

[[v19-104-32]]

^<<v19-104-32,32>>^ Ele olha para a terra, e ela treme, toca os montes, e eles fumegam.

[[v19-104-33]]

^<<v19-104-33,33>>^ Cantarei ao Senhor toda a minha vida; louvarei ao meu Deus enquanto eu viver.

[[v19-104-34]]

^<<v19-104-34,34>>^ Seja-lhe agradável a minha meditação, pois no Senhor tenho alegria.

[[v19-104-35]]

^<<v19-104-35,35>>^ Sejam os pecadores eliminados da terra e deixem de existir os ímpios. Bendiga ao Senhor a minha alma! Aleluia!

'''

xref:019-salmos/019-salmos-103.adoc#v19-103-0[&#60; Capítulo Anterior] | <<v19-104-0,Topo>> | xref:019-salmos/019-salmos-105.adoc#v19-105-0[Próximo Capítulo &#62;]