include::./index.adoc[]

[[v19-65-0]]
=== Salmos, 65
// nvi ?, NVI - Nova Versão Internacional

[[v19-65-1]]

^<<v19-65-1,1>>^ O louvor te aguarda em Sião, ó Deus; os votos que te fizemos serão cumpridos.

[[v19-65-2]]

^<<v19-65-2,2>>^ Ó tu que ouves a oração, a ti virão todos os homens.

[[v19-65-3]]

^<<v19-65-3,3>>^ Quando os nossos pecados pesavam sobre nós, tu mesmo fizeste propiciação por nossas transgressões.

[[v19-65-4]]

^<<v19-65-4,4>>^ Como são felizes aqueles que escolhes e trazes a ti, para viverem nos teus átrios! Transbordamos de bênçãos da tua casa, do teu santo templo!

[[v19-65-5]]

^<<v19-65-5,5>>^ Tu nos respondes com temíveis feitos de justiça, ó Deus, nosso Salvador, esperança de todos os confins da terra e dos mais distantes mares.

[[v19-65-6]]

^<<v19-65-6,6>>^ Tu que firmaste os montes pela tua força, pelo teu grande poder.

[[v19-65-7]]

^<<v19-65-7,7>>^ Tu que acalmas o bramido dos mares, o bramido de suas ondas, e o tumulto das nações.

[[v19-65-8]]

^<<v19-65-8,8>>^ Tremem os habitantes das terras distantes diante das tuas maravilhas; do nascente ao poente despertas canções de alegria.

[[v19-65-9]]

^<<v19-65-9,9>>^ Cuidas da terra e a regas; fartamente a enriqueces. Os riachos de Deus transbordam para que nunca falte o trigo, pois assim ordenaste.

[[v19-65-10]]

^<<v19-65-10,10>>^ Encharcas os seus sulcos e aplainas os seus torrões; tu a amoleces com chuvas e abençoas as suas colheitas.

[[v19-65-11]]

^<<v19-65-11,11>>^ Coroas o ano com a tua bondade, e por onde passas emana fartura;

[[v19-65-12]]

^<<v19-65-12,12>>^ fartura vertem as pastagens do deserto, e as colinas se vestem de alegria.

[[v19-65-13]]

^<<v19-65-13,13>>^ Os campos se revestem de rebanhos e os vales se cobrem de trigo; eles exultam e cantam de alegria!

'''

xref:019-salmos/019-salmos-064.adoc#v19-64-0[&#60; Capítulo Anterior] | <<v19-65-0,Topo>> | xref:019-salmos/019-salmos-066.adoc#v19-66-0[Próximo Capítulo &#62;]