include::./index.adoc[]

[[v19-35-0]]
=== Salmos, 35
// nvi ?, NVI - Nova Versão Internacional

[[v19-35-1]]

^<<v19-35-1,1>>^ Defende-me, Senhor, dos que me acusam; luta contra os que lutam comigo.

[[v19-35-2]]

^<<v19-35-2,2>>^ Toma os escudos, o grande e o pequeno; levanta-te e vem socorrer-me.

[[v19-35-3]]

^<<v19-35-3,3>>^ Empunha a lança e o machado de guerra contra os meus perseguidores. Dize à minha alma: "Eu sou a sua salvação".

[[v19-35-4]]

^<<v19-35-4,4>>^ Sejam humilhados e desprezados os que procuram matar-me; retrocedam envergonhados aqueles que tramam a minha ruína.

[[v19-35-5]]

^<<v19-35-5,5>>^ Que eles sejam como a palha ao vento, quando o anjo do Senhor os expulsar;

[[v19-35-6]]

^<<v19-35-6,6>>^ seja a vereda deles sombria e escorregadia, quando o anjo do Senhor os perseguir.

[[v19-35-7]]

^<<v19-35-7,7>>^ Já que, sem motivo, prepararam contra mim uma armadilha oculta e, sem motivo, abriram uma cova para mim,

[[v19-35-8]]

^<<v19-35-8,8>>^ que a ruína lhes sobrevenha de surpresa: sejam presos pela armadilha que prepararam, caiam na cova que abriram, para a sua própria ruína.

[[v19-35-9]]

^<<v19-35-9,9>>^ Então a minha alma exultará no Senhor e se regozijará na sua salvação.

[[v19-35-10]]

^<<v19-35-10,10>>^ Todo o meu ser exclamará: "Quem se compara a ti, Senhor? Tu livras os necessitados daqueles que são mais poderosos do que eles, livras os necessitados e os pobres daqueles que os exploram".

[[v19-35-11]]

^<<v19-35-11,11>>^ Testemunhas maldosas enfrentam-me e questionam-me sobre coisas de que nada sei.

[[v19-35-12]]

^<<v19-35-12,12>>^ Elas me retribuem o bem com o mal e procuram tirar-me a vida.

[[v19-35-13]]

^<<v19-35-13,13>>^ Contudo, quando estavam doentes, usei vestes de lamento, humilhei-me com jejum e recolhi-me em oração.

[[v19-35-14]]

^<<v19-35-14,14>>^ Saí vagueando e pranteando, como por um amigo ou por um irmão. Eu me prostrei enlutado, como quem lamenta por sua mãe.

[[v19-35-15]]

^<<v19-35-15,15>>^ Mas, quando tropecei, eles se reuniram alegres; sem que eu o soubesse, ajuntaram-se para me atacar. Eles me agrediram sem cessar.

[[v19-35-16]]

^<<v19-35-16,16>>^ Como ímpios caçoando do meu refúgio, rosnaram contra mim.

[[v19-35-17]]

^<<v19-35-17,17>>^ Senhor, até quando ficarás olhando? Livra-me dos ataques deles, livra a minha vida preciosa desses leões.

[[v19-35-18]]

^<<v19-35-18,18>>^ Eu te darei graças na grande assembléia; no meio da grande multidão te louvarei.

[[v19-35-19]]

^<<v19-35-19,19>>^ Não deixes que os meus inimigos traiçoeiros se divirtam à minha custa; não permitas que aqueles que sem razão me odeiam troquem olhares de desprezo.

[[v19-35-20]]

^<<v19-35-20,20>>^ Não falam pacificamente, mas planejam acusações falsas contra os que vivem tranqüilamente na terra.

[[v19-35-21]]

^<<v19-35-21,21>>^ Com a boca escancarada, riem de mim e me acusam: "Nós vimos! Sabemos de tudo! "

[[v19-35-22]]

^<<v19-35-22,22>>^ Tu viste isso, Senhor! Não fiques calado. Não te afastes de mim, Senhor,

[[v19-35-23]]

^<<v19-35-23,23>>^ Acorda! Desperta! Faze-me justiça! Defende a minha causa, meu Deus e Senhor.

[[v19-35-24]]

^<<v19-35-24,24>>^ Senhor, meu Deus, tu és justo; faze-me justiça para que eles não se alegrem à minha custa.

[[v19-35-25]]

^<<v19-35-25,25>>^ Não deixes que pensem: "Ah! Era isso que queríamos! ", nem que digam: "Acabamos com ele! "

[[v19-35-26]]

^<<v19-35-26,26>>^ Sejam humilhados e frustrados todos os que se divertem à custa do meu sofrimento; cubram-se de vergonha e desonra todos os que se acham superiores a mim.

[[v19-35-27]]

^<<v19-35-27,27>>^ Cantem de alegria e regozijo todos os que desejam ver provada a minha inocência, e sempre repitam: "O Senhor seja engrandecido! Ele tem prazer no bem-estar do seu servo".

[[v19-35-28]]

^<<v19-35-28,28>>^ Minha língua proclamará a tua justiça e o teu louvor o dia inteiro.

'''

xref:019-salmos/019-salmos-034.adoc#v19-34-0[&#60; Capítulo Anterior] | <<v19-35-0,Topo>> | xref:019-salmos/019-salmos-036.adoc#v19-36-0[Próximo Capítulo &#62;]