include::./index.adoc[]

[[v19-118-0]]
=== Salmos, 118
// nvi ?, NVI - Nova Versão Internacional

[[v19-118-1]]

^<<v19-118-1,1>>^ Dêem graças ao Senhor porque ele é bom; o seu amor dura para sempre.

[[v19-118-2]]

^<<v19-118-2,2>>^ Que Israel diga: "O seu amor dura para sempre! "

[[v19-118-3]]

^<<v19-118-3,3>>^ Os sacerdotes digam: "O seu amor dura para sempre! "

[[v19-118-4]]

^<<v19-118-4,4>>^ Os que temem o Senhor digam: "O seu amor dura para sempre! "

[[v19-118-5]]

^<<v19-118-5,5>>^ Na minha angústia clamei ao Senhor; e o Senhor me respondeu, dando-me ampla liberdade.

[[v19-118-6]]

^<<v19-118-6,6>>^ O Senhor está comigo, não temerei. O que me podem fazer os homens?

[[v19-118-7]]

^<<v19-118-7,7>>^ O Senhor está comigo; ele é o meu ajudador. Verei a derrota dos meus inimigos.

[[v19-118-8]]

^<<v19-118-8,8>>^ É melhor buscar refúgio no Senhor do que confiar nos homens.

[[v19-118-9]]

^<<v19-118-9,9>>^ É melhor buscar refúgio no Senhor do que confiar em príncipes.

[[v19-118-10]]

^<<v19-118-10,10>>^ Todas as nações me cercaram, mas em nome do Senhor eu as derrotei.

[[v19-118-11]]

^<<v19-118-11,11>>^ Cercaram-me por todos os lados, mas em nome do Senhor eu as derrotei.

[[v19-118-12]]

^<<v19-118-12,12>>^ Cercaram-me como um enxame de abelhas, mas logo se extinguiram como espinheiros em chamas. Em nome do Senhor eu as derrotei!

[[v19-118-13]]

^<<v19-118-13,13>>^ Empurraram-me para forçar a minha queda, mas o Senhor me ajudou.

[[v19-118-14]]

^<<v19-118-14,14>>^ O Senhor é a minha força e o meu cântico; ele é a minha salvação.

[[v19-118-15]]

^<<v19-118-15,15>>^ Alegres brados de vitória ressoam nas tendas dos justos: "A mão direita do Senhor age com poder!

[[v19-118-16]]

^<<v19-118-16,16>>^ A mão direita do Senhor é exaltada! A mão direita do Senhor age com poder! "

[[v19-118-17]]

^<<v19-118-17,17>>^ Não morrerei; mas vivo ficarei para anunciar os feitos do Senhor.

[[v19-118-18]]

^<<v19-118-18,18>>^ O Senhor me castigou com severidade, mas não me entregou à morte.

[[v19-118-19]]

^<<v19-118-19,19>>^ Abram as portas da justiça para mim, pois quero entrar para dar graças ao Senhor.

[[v19-118-20]]

^<<v19-118-20,20>>^ Esta é a porta do Senhor, pela qual entram os justos.

[[v19-118-21]]

^<<v19-118-21,21>>^ Dou-te graças, porque me respondeste e foste a minha salvação.

[[v19-118-22]]

^<<v19-118-22,22>>^ A pedra que os construtores rejeitaram tornou-se a pedra angular.

[[v19-118-23]]

^<<v19-118-23,23>>^ Isso vem do Senhor, e é algo maravilhoso para nós.

[[v19-118-24]]

^<<v19-118-24,24>>^ Este é o dia em que o Senhor agiu; alegremo-nos e exultemos neste dia.

[[v19-118-25]]

^<<v19-118-25,25>>^ Salva-nos, Senhor! Nós imploramos. Faze-nos prosperar, Senhor! Nós suplicamos.

[[v19-118-26]]

^<<v19-118-26,26>>^ Bendito é o que vem em nome do Senhor. Da casa do Senhor nós os abençoamos.

[[v19-118-27]]

^<<v19-118-27,27>>^ O Senhor é Deus, fez resplandecer sobre nós a sua luz. Juntem-se ao cortejo festivo, levando ramos até as pontas do altar.

[[v19-118-28]]

^<<v19-118-28,28>>^ Tu és o meu Deus; graças te darei! Ó meu Deus, eu te exaltarei!

[[v19-118-29]]

^<<v19-118-29,29>>^ Dêem graças ao Senhor, porque ele é bom; o seu amor dura para sempre.

'''

xref:019-salmos/019-salmos-117.adoc#v19-117-0[&#60; Capítulo Anterior] | <<v19-118-0,Topo>> | xref:019-salmos/019-salmos-119.adoc#v19-119-0[Próximo Capítulo &#62;]