include::./index.adoc[]

[[v19-143-0]]
=== Salmos, 143
// nvi ?, NVI - Nova Versão Internacional

[[v19-143-1]]

^<<v19-143-1,1>>^ Ouve, Senhor, a minha oração, dá ouvidos à minha súplica; responde-me por tua fidelidade e por tua justiça.

[[v19-143-2]]

^<<v19-143-2,2>>^ Mas não leves o teu servo a julgamento, pois ninguém é justo diante de ti.

[[v19-143-3]]

^<<v19-143-3,3>>^ O inimigo persegue-me e esmaga-me ao chão; ele me faz morar nas trevas, como os que há muito morreram.

[[v19-143-4]]

^<<v19-143-4,4>>^ O meu espírito se desanima; o meu coração está em pânico.

[[v19-143-5]]

^<<v19-143-5,5>>^ Eu me recordo dos tempos antigos; medito em todas as tuas obras e considero o que as tuas mãos têm feito.

[[v19-143-6]]

^<<v19-143-6,6>>^ Estendo as minhas mãos para ti; como a terra árida, tenho sede de ti. Pausa

[[v19-143-7]]

^<<v19-143-7,7>>^ Apressa-te em responder-me, Senhor! O meu espírito se abate. Não escondas de mim o teu rosto, ou serei como os que descem à cova.

[[v19-143-8]]

^<<v19-143-8,8>>^ Faze-me ouvir do teu amor leal pela manhã, pois em ti confio. Mostra-me o caminho que devo seguir, pois a ti elevo a minha alma.

[[v19-143-9]]

^<<v19-143-9,9>>^ Livra-me dos meus inimigos, Senhor, pois em ti eu me abrigo.

[[v19-143-10]]

^<<v19-143-10,10>>^ Ensina-me a fazer a tua vontade, pois tu és o meu Deus; que o teu bondoso Espírito me conduza por terreno plano.

[[v19-143-11]]

^<<v19-143-11,11>>^ Preserva-me a vida, Senhor, por causa do teu nome, por tua justiça, tira-me desta angústia.

[[v19-143-12]]

^<<v19-143-12,12>>^ E no teu amor leal, aniquila os meus inimigos; destrói todos os meus adversários, pois sou teu servo.

'''

xref:019-salmos/019-salmos-142.adoc#v19-142-0[&#60; Capítulo Anterior] | <<v19-143-0,Topo>> | xref:019-salmos/019-salmos-144.adoc#v19-144-0[Próximo Capítulo &#62;]