include::./index.adoc[]

[[v19-41-0]]
=== Salmos, 41
// nvi ?, NVI - Nova Versão Internacional

[[v19-41-1]]

^<<v19-41-1,1>>^ Como é feliz aquele que se interessa pelo pobre! O Senhor o livra em tempos de adversidade.

[[v19-41-2]]

^<<v19-41-2,2>>^ O Senhor o protegerá e preservará a sua vida; ele o fará feliz na terra e não o entregará ao desejo dos seus inimigos.

[[v19-41-3]]

^<<v19-41-3,3>>^ O Senhor o susterá em seu leito de enfermidade, e da doença o restaurará.

[[v19-41-4]]

^<<v19-41-4,4>>^ Eu disse: Misericórdia, Senhor, cura-me, pois pequei contra ti.

[[v19-41-5]]

^<<v19-41-5,5>>^ Os meus inimigos dizem maldosamente a meu respeito: "Quando ele vai morrer? Quando vai desaparecer o seu nome? "

[[v19-41-6]]

^<<v19-41-6,6>>^ Sempre que alguém vem visitar-me, fala com falsidade, enche o coração de calúnias e depois sai espalhando-as.

[[v19-41-7]]

^<<v19-41-7,7>>^ Todos os que me odeiam juntam-se e cochicham contra mim, imaginando que o pior me acontecerá:

[[v19-41-8]]

^<<v19-41-8,8>>^ "Uma praga terrível o derrubou; está de cama, e jamais se levantará".

[[v19-41-9]]

^<<v19-41-9,9>>^ Até o meu melhor amigo, em quem eu confiava e que partilhava do meu pão, voltou-se contra mim.

[[v19-41-10]]

^<<v19-41-10,10>>^ Mas, tu, Senhor, tem misericórdia de mim; levanta-me, para que eu lhes retribua.

[[v19-41-11]]

^<<v19-41-11,11>>^ Sei que me queres bem, pois o meu inimigo não triunfa sobre mim.

[[v19-41-12]]

^<<v19-41-12,12>>^ Por causa da minha integridade me susténs e me pões na tua presença para sempre.

[[v19-41-13]]

^<<v19-41-13,13>>^ Louvado seja o Senhor, o Deus de Israel, de eternidade a eternidade! Amém e amém!

'''

xref:019-salmos/019-salmos-040.adoc#v19-40-0[&#60; Capítulo Anterior] | <<v19-41-0,Topo>> | xref:019-salmos/019-salmos-042.adoc#v19-42-0[Próximo Capítulo &#62;]