include::./index.adoc[]

[[v19-32-0]]
=== Salmos, 32
// nvi ?, NVI - Nova Versão Internacional

[[v19-32-1]]

^<<v19-32-1,1>>^ Como é feliz aquele que tem suas transgressões perdoadas e seus pecados apagados!

[[v19-32-2]]

^<<v19-32-2,2>>^ Como é feliz aquele a quem o Senhor não atribui culpa e em quem não há hipocrisia!

[[v19-32-3]]

^<<v19-32-3,3>>^ Enquanto escondi os meus pecados, o meu corpo definhava de tanto gemer.

[[v19-32-4]]

^<<v19-32-4,4>>^ Pois de dia e de noite a tua mão pesava sobre mim; minha força foi se esgotando como em tempo de seca. Pausa

[[v19-32-5]]

^<<v19-32-5,5>>^ Então reconheci diante de ti o meu pecado e não encobri as minhas culpas. Eu disse: "Confessarei as minhas transgressões ao Senhor", e tu perdoaste a culpa do meu pecado. Pausa

[[v19-32-6]]

^<<v19-32-6,6>>^ Portanto, que todos os que são fiéis orem a ti enquanto podes ser encontrado; quando as muitas águas se levantarem, elas não os atingirão.

[[v19-32-7]]

^<<v19-32-7,7>>^ Tu és o meu abrigo; tu me preservarás das angústias e me cercarás de canções de livramento. Pausa

[[v19-32-8]]

^<<v19-32-8,8>>^ Eu o instruirei e o ensinarei no caminho que você deve seguir; eu o aconselharei e cuidarei de você.

[[v19-32-9]]

^<<v19-32-9,9>>^ Não sejam como o cavalo ou o burro, que não têm entendimento mas precisam ser controlados com freios e rédeas, caso contrário não obedecem.

[[v19-32-10]]

^<<v19-32-10,10>>^ Muitas são as dores dos ímpios, mas a bondade do Senhor protege quem nele confia.

[[v19-32-11]]

^<<v19-32-11,11>>^ Alegrem-se no Senhor e exultem, vocês que são justos! Cantem de alegria, todos vocês que são retos de coração!

'''

xref:019-salmos/019-salmos-031.adoc#v19-31-0[&#60; Capítulo Anterior] | <<v19-32-0,Topo>> | xref:019-salmos/019-salmos-033.adoc#v19-33-0[Próximo Capítulo &#62;]