include::./index.adoc[]

[[v19-46-0]]
=== Salmos, 46
// nvi ?, NVI - Nova Versão Internacional

[[v19-46-1]]

^<<v19-46-1,1>>^ Deus é o nosso refúgio e a nossa fortaleza, auxílio sempre presente na adversidade.

[[v19-46-2]]

^<<v19-46-2,2>>^ Por isso não temeremos, embora a terra trema e os montes afundem no coração do mar,

[[v19-46-3]]

^<<v19-46-3,3>>^ embora estrondem as suas águas turbulentas e os montes sejam sacudidos pela sua fúria. Pausa

[[v19-46-4]]

^<<v19-46-4,4>>^ Há um rio cujos canais alegram a cidade de Deus, o Santo Lugar onde habita o Altíssimo.

[[v19-46-5]]

^<<v19-46-5,5>>^ Deus nela está! Não será abalada! Deus vem em seu auxílio desde o romper da manhã.

[[v19-46-6]]

^<<v19-46-6,6>>^ Nações se agitam, reinos se abalam; ele ergue a voz, e a terra se derrete.

[[v19-46-7]]

^<<v19-46-7,7>>^ O Senhor dos Exércitos está conosco; o Deus de Jacó é a nossa torre segura. Pausa

[[v19-46-8]]

^<<v19-46-8,8>>^ Venham! Vejam as obras do Senhor, seus feitos estarrecedores na terra.

[[v19-46-9]]

^<<v19-46-9,9>>^ Ele dá fim às guerras até os confins da terra; quebra o arco e despedaça a lança, destrói os escudos com fogo.

[[v19-46-10]]

^<<v19-46-10,10>>^ "Parem de lutar! Saibam que eu sou Deus! Serei exaltado entre as nações, serei exaltado na terra. "

[[v19-46-11]]

^<<v19-46-11,11>>^ O Senhor dos Exércitos está conosco; o Deus de Jacó é a nossa torre segura. Pausa

'''

xref:019-salmos/019-salmos-045.adoc#v19-45-0[&#60; Capítulo Anterior] | <<v19-46-0,Topo>> | xref:019-salmos/019-salmos-047.adoc#v19-47-0[Próximo Capítulo &#62;]