include::./index.adoc[]

[[v19-34-0]]
=== Salmos, 34
// nvi ?, NVI - Nova Versão Internacional

[[v19-34-1]]

^<<v19-34-1,1>>^ Bendirei o Senhor o tempo todo! Os meus lábios sempre o louvarão.

[[v19-34-2]]

^<<v19-34-2,2>>^ Minha alma se gloriará no Senhor; ouçam os oprimidos e se alegrem.

[[v19-34-3]]

^<<v19-34-3,3>>^ Proclamem a grandeza do Senhor comigo; juntos exaltemos o seu nome.

[[v19-34-4]]

^<<v19-34-4,4>>^ Busquei o Senhor, e ele me respondeu; livrou-me de todos os meus temores.

[[v19-34-5]]

^<<v19-34-5,5>>^ Os que olham para ele estão radiantes de alegria; seus rostos jamais mostrarão decepção.

[[v19-34-6]]

^<<v19-34-6,6>>^ Este pobre homem clamou, e o Senhor o ouviu; e o libertou de todas as suas tribulações.

[[v19-34-7]]

^<<v19-34-7,7>>^ O anjo do Senhor é sentinela ao redor daqueles que o temem, e os livra.

[[v19-34-8]]

^<<v19-34-8,8>>^ Provem, e vejam como o Senhor é bom. Como é feliz o homem que nele se refugia!

[[v19-34-9]]

^<<v19-34-9,9>>^ Temam o Senhor, vocês que são os seus santos, pois nada falta aos que o temem.

[[v19-34-10]]

^<<v19-34-10,10>>^ Os leões podem passar necessidade e fome, mas os que buscam o Senhor de nada têm falta.

[[v19-34-11]]

^<<v19-34-11,11>>^ Venham, meus filhos, ouçam-me; eu lhes ensinarei o temor do Senhor.

[[v19-34-12]]

^<<v19-34-12,12>>^ Quem de vocês quer amar a vida e deseja ver dias felizes?

[[v19-34-13]]

^<<v19-34-13,13>>^ Guarde a sua língua do mal e os seus lábios da falsidade.

[[v19-34-14]]

^<<v19-34-14,14>>^ Afaste-se do mal e faça o bem; busque a paz com perseverança.

[[v19-34-15]]

^<<v19-34-15,15>>^ Os olhos do Senhor voltam-se para os justos e os seus ouvidos estão atentos ao seu grito de socorro;

[[v19-34-16]]

^<<v19-34-16,16>>^ o rosto do Senhor volta-se contra os que praticam o mal, para apagar da terra a memória deles.

[[v19-34-17]]

^<<v19-34-17,17>>^ Os justos clamam, o Senhor os ouve e os livra de todas as suas tribulações.

[[v19-34-18]]

^<<v19-34-18,18>>^ O Senhor está perto dos que têm o coração quebrantado e salva os de espírito abatido.

[[v19-34-19]]

^<<v19-34-19,19>>^ O justo passa por muitas adversidades, mas o Senhor o livra de todas;

[[v19-34-20]]

^<<v19-34-20,20>>^ protege todos os seus ossos; nenhum deles será quebrado.

[[v19-34-21]]

^<<v19-34-21,21>>^ A desgraça matará os ímpios; os que odeiam o justo serão condenados.

[[v19-34-22]]

^<<v19-34-22,22>>^ O Senhor redime a vida dos seus servos; ninguém que nele se refugia será condenado.

'''

xref:019-salmos/019-salmos-033.adoc#v19-33-0[&#60; Capítulo Anterior] | <<v19-34-0,Topo>> | xref:019-salmos/019-salmos-035.adoc#v19-35-0[Próximo Capítulo &#62;]