include::./index.adoc[]

[[v19-16-0]]
=== Salmos, 16
// nvi ?, NVI - Nova Versão Internacional

[[v19-16-1]]

^<<v19-16-1,1>>^ Protege-me, ó Deus, pois em ti me refugio.

[[v19-16-2]]

^<<v19-16-2,2>>^ Ao Senhor declaro: "Tu és o meu Senhor; não tenho bem nenhum além de ti".

[[v19-16-3]]

^<<v19-16-3,3>>^ Quanto aos fiéis que há na terra, eles é que são os notáveis em quem está todo o meu prazer.

[[v19-16-4]]

^<<v19-16-4,4>>^ Grande será o sofrimento dos que correm atrás de outros deuses. Não participarei dos seus sacrifícios de sangue, e os meus lábios nem mencionarão os seus nomes.

[[v19-16-5]]

^<<v19-16-5,5>>^ Senhor, tu és a minha porção e o meu cálice; és tu que garantes o meu futuro.

[[v19-16-6]]

^<<v19-16-6,6>>^ As divisas caíram para mim em lugares agradáveis: Tenho uma bela herança!

[[v19-16-7]]

^<<v19-16-7,7>>^ Bendirei o Senhor, que me aconselha; na escura noite o meu coração me ensina!

[[v19-16-8]]

^<<v19-16-8,8>>^ Sempre tenho o Senhor diante de mim. Com ele à minha direita, não serei abalado.

[[v19-16-9]]

^<<v19-16-9,9>>^ Por isso o meu coração se alegra e no íntimo exulto; mesmo o meu corpo repousará tranqüilo,

[[v19-16-10]]

^<<v19-16-10,10>>^ porque tu não me abandonarás no sepulcro, nem permitirás que o teu santo sofra decomposição.

[[v19-16-11]]

^<<v19-16-11,11>>^ Tu me farás conhecer a vereda da vida, a alegria plena da tua presença, eterno prazer à tua direita.

'''

xref:019-salmos/019-salmos-015.adoc#v19-15-0[&#60; Capítulo Anterior] | <<v19-16-0,Topo>> | xref:019-salmos/019-salmos-017.adoc#v19-17-0[Próximo Capítulo &#62;]