include::./index.adoc[]

[[v19-132-0]]
=== Salmos, 132
// nvi ?, NVI - Nova Versão Internacional

[[v19-132-1]]

^<<v19-132-1,1>>^ Senhor, lembra-te de Davi e das dificuldades que enfrentou.

[[v19-132-2]]

^<<v19-132-2,2>>^ Ele jurou ao Senhor e fez um voto ao Poderoso de Jacó:

[[v19-132-3]]

^<<v19-132-3,3>>^ "Não entrarei na minha tenda e não me deitarei no meu leito;

[[v19-132-4]]

^<<v19-132-4,4>>^ não permitirei que os meus olhos peguem no sono nem que as minhas pálpebras descansem,

[[v19-132-5]]

^<<v19-132-5,5>>^ enquanto não encontrar um lugar para o Senhor, uma habitação para o Poderoso de Jacó".

[[v19-132-6]]

^<<v19-132-6,6>>^ Soubemos que a arca estava em Efrata, mas nós a encontramos nos campos de Jaar:

[[v19-132-7]]

^<<v19-132-7,7>>^ "Vamos para habitação dele! Vamos adorá-lo diante do estrado de seus pés!

[[v19-132-8]]

^<<v19-132-8,8>>^ Levanta-te, Senhor, e vem para o teu lugar de descanso, tu e a arca onde está o teu poder.

[[v19-132-9]]

^<<v19-132-9,9>>^ Vistam-se de retidão os teus sacerdotes; cantem de alegria os teus fiéis".

[[v19-132-10]]

^<<v19-132-10,10>>^ Por amor ao teu servo Davi, não rejeites o teu ungido.

[[v19-132-11]]

^<<v19-132-11,11>>^ O Senhor fez um juramento a Davi, um juramento firme que ele não revogará: "Colocarei um dos seus descendentes no seu trono.

[[v19-132-12]]

^<<v19-132-12,12>>^ Se os seus filhos forem fiéis à minha aliança e aos testemunhos que eu lhes ensino, também os filhos deles o sucederão no trono para sempre".

[[v19-132-13]]

^<<v19-132-13,13>>^ O Senhor escolheu Sião, com o desejo de fazê-la sua habitação:

[[v19-132-14]]

^<<v19-132-14,14>>^ "Este será o meu lugar de descanso para sempre; aqui firmarei o meu trono, pois esse é o meu desejo.

[[v19-132-15]]

^<<v19-132-15,15>>^ Abençoarei este lugar com fartura; os seus pobres suprirei de pão.

[[v19-132-16]]

^<<v19-132-16,16>>^ Vestirei de salvação os seus sacerdotes e os seus fiéis a celebrarão com grande alegria.

[[v19-132-17]]

^<<v19-132-17,17>>^ "Ali farei renascer o poder de Davi e farei brilhar a luz do meu ungido.

[[v19-132-18]]

^<<v19-132-18,18>>^ Vestirei de vergonha os seus inimigos, mas nele brilhará a sua coroa".

'''

xref:019-salmos/019-salmos-131.adoc#v19-131-0[&#60; Capítulo Anterior] | <<v19-132-0,Topo>> | xref:019-salmos/019-salmos-133.adoc#v19-133-0[Próximo Capítulo &#62;]