include::./index.adoc[]

[[v19-78-0]]
=== Salmos, 78
// nvi ?, NVI - Nova Versão Internacional

[[v19-78-1]]

^<<v19-78-1,1>>^ Povo meu, escute o meu ensino; incline os ouvidos para o que eu tenho a dizer.

[[v19-78-2]]

^<<v19-78-2,2>>^ Em parábolas abrirei a minha boca, proferirei enigmas do passado;

[[v19-78-3]]

^<<v19-78-3,3>>^ o que ouvimos e aprendemos, o que nossos pais nos contaram.

[[v19-78-4]]

^<<v19-78-4,4>>^ Não os esconderemos dos nossos filhos; contaremos à próxima geração os louváveis feitos do Senhor, o seu poder e as maravilhas que fez.

[[v19-78-5]]

^<<v19-78-5,5>>^ Ele decretou estatutos para Jacó, e em Israel estabeleceu a lei, e ordenou aos nossos antepassados que a ensinassem aos seus filhos,

[[v19-78-6]]

^<<v19-78-6,6>>^ de modo que a geração seguinte a conhecesse, e também os filhos que ainda nasceriam, e eles, por sua vez, contassem aos seus próprios filhos.

[[v19-78-7]]

^<<v19-78-7,7>>^ Então eles porão a confiança em Deus; não esquecerão os seus feitos e obedecerão aos seus mandamentos.

[[v19-78-8]]

^<<v19-78-8,8>>^ Eles não serão como os seus antepassados, obstinados e rebeldes, povo de coração desleal para com Deus, gente de espírito infiel.

[[v19-78-9]]

^<<v19-78-9,9>>^ Os homens de Efraim, flecheiros armados, viraram as costas no dia da batalha;

[[v19-78-10]]

^<<v19-78-10,10>>^ não guardaram a aliança de Deus e se recusaram a viver de acordo com a sua lei.

[[v19-78-11]]

^<<v19-78-11,11>>^ Esqueceram o que ele tinha feito, as maravilhas que lhes havia mostrado.

[[v19-78-12]]

^<<v19-78-12,12>>^ Ele fez milagres diante dos seus antepassados, na terra do Egito, na região de Zoã.

[[v19-78-13]]

^<<v19-78-13,13>>^ Dividiu o mar para que pudessem passar; fez a água erguer-se como um muro.

[[v19-78-14]]

^<<v19-78-14,14>>^ Ele os guiou com a nuvem de dia e com a luz do fogo de noite.

[[v19-78-15]]

^<<v19-78-15,15>>^ Fendeu as rochas no deserto e deu-lhes tanta água como a que flui das profundezas;

[[v19-78-16]]

^<<v19-78-16,16>>^ da pedra fez sair regatos e fluir água como um rio.

[[v19-78-17]]

^<<v19-78-17,17>>^ Mas contra ele continuaram a pecar, revoltando-se no deserto contra o Altíssimo.

[[v19-78-18]]

^<<v19-78-18,18>>^ Deliberadamente puseram Deus à prova, exigindo o que desejavam comer.

[[v19-78-19]]

^<<v19-78-19,19>>^ Duvidaram de Deus, dizendo: "Poderá Deus preparar uma mesa no deserto?

[[v19-78-20]]

^<<v19-78-20,20>>^ Sabemos que quando ele feriu a rocha a água brotou e jorrou em torrentes. Mas conseguirá também dar-nos de comer? Poderá suprir de carne o seu povo? "

[[v19-78-21]]

^<<v19-78-21,21>>^ O Senhor os ouviu e enfureceu-se; atacou Jacó com fogo, e sua ira levantou-se contra Israel,

[[v19-78-22]]

^<<v19-78-22,22>>^ pois eles não creram em Deus nem confiaram no seu poder salvador.

[[v19-78-23]]

^<<v19-78-23,23>>^ Contudo, ele deu ordens às nuvens e abriu as portas dos céus;

[[v19-78-24]]

^<<v19-78-24,24>>^ fez chover maná para que o povo comesse, deu-lhe o pão dos céus.

[[v19-78-25]]

^<<v19-78-25,25>>^ Os homens comeram o pão dos anjos; enviou-lhes comida à vontade.

[[v19-78-26]]

^<<v19-78-26,26>>^ Enviou dos céus o vento oriental e pelo seu poder fez avançar o vento sul.

[[v19-78-27]]

^<<v19-78-27,27>>^ Fez chover carne sobre eles como pó, bandos de aves como a areia da praia.

[[v19-78-28]]

^<<v19-78-28,28>>^ Levou-as a cair dentro do acampamento, ao redor das suas tendas.

[[v19-78-29]]

^<<v19-78-29,29>>^ Comeram à vontade, e assim ele satisfez o desejo deles.

[[v19-78-30]]

^<<v19-78-30,30>>^ Mas, antes de saciarem o apetite, quando ainda tinham a comida na boca,

[[v19-78-31]]

^<<v19-78-31,31>>^ acendeu-se contra eles a ira de Deus; e ele feriu de morte os mais fortes dentre eles, matando os jovens de Israel.

[[v19-78-32]]

^<<v19-78-32,32>>^ A despeito disso tudo, continuaram pecando; não creram nos seus prodígios.

[[v19-78-33]]

^<<v19-78-33,33>>^ Por isso ele encerrou os dias deles como um sopro e os anos deles em repentino pavor.

[[v19-78-34]]

^<<v19-78-34,34>>^ Sempre que Deus os castigava com a morte, eles o buscavam; com fervor se voltavam de novo para ele.

[[v19-78-35]]

^<<v19-78-35,35>>^ Lembravam-se de que Deus era a sua Rocha, de que o Deus Altíssimo era o seu Redentor.

[[v19-78-36]]

^<<v19-78-36,36>>^ Com a boca o adulavam, com a língua o enganavam;

[[v19-78-37]]

^<<v19-78-37,37>>^ o coração deles não era sincero; não foram fiéis à sua aliança.

[[v19-78-38]]

^<<v19-78-38,38>>^ Contudo, ele foi misericordioso; perdoou-lhes as maldades e não os destruiu. Vez após vez conteve a sua ira, sem despertá-la totalmente.

[[v19-78-39]]

^<<v19-78-39,39>>^ Lembrou-se de que eram meros mortais, brisa passageira que não retorna.

[[v19-78-40]]

^<<v19-78-40,40>>^ Quantas vezes mostraram-se rebeldes contra ele no deserto e o entristeceram na terra solitária!

[[v19-78-41]]

^<<v19-78-41,41>>^ Repetidas vezes puseram Deus à prova; irritaram o Santo de Israel.

[[v19-78-42]]

^<<v19-78-42,42>>^ Não se lembravam da sua mão poderosa, do dia em que os redimiu do opressor,

[[v19-78-43]]

^<<v19-78-43,43>>^ do dia em que mostrou os seus prodígios no Egito, as suas maravilhas na região de Zoã,

[[v19-78-44]]

^<<v19-78-44,44>>^ quando transformou os rios e os riachos dos egípcios em sangue, e não mais conseguiam beber das suas águas,

[[v19-78-45]]

^<<v19-78-45,45>>^ e enviou enxames de moscas que os devoraram, e rãs que os devastaram;

[[v19-78-46]]

^<<v19-78-46,46>>^ quando entregou as suas plantações às larvas, a produção da terra aos gafanhotos;

[[v19-78-47]]

^<<v19-78-47,47>>^ e destruiu as suas vinhas com a saraiva e as suas figueiras bravas, com a geada;

[[v19-78-48]]

^<<v19-78-48,48>>^ quando entregou o gado deles ao granizo, os seus rebanhos aos raios;

[[v19-78-49]]

^<<v19-78-49,49>>^ quando os atingiu com a sua ira ardente, com furor, indignação e hostilidade, com muitos anjos destruidores.

[[v19-78-50]]

^<<v19-78-50,50>>^ Abriu caminho para a sua ira; não os poupou da morte, mas os entregou à peste.

[[v19-78-51]]

^<<v19-78-51,51>>^ Matou todos os primogênitos do Egito, as primícias do vigor varonil das tendas de Cam.

[[v19-78-52]]

^<<v19-78-52,52>>^ Mas tirou o seu povo como ovelhas e o conduziu como a um rebanho pelo deserto.

[[v19-78-53]]

^<<v19-78-53,53>>^ Ele os guiou em segurança, e não tiveram medo; e os seus inimigos afundaram-se no mar.

[[v19-78-54]]

^<<v19-78-54,54>>^ Assim os trouxe à fronteira da sua terra santa, aos montes que a sua mão direita conquistou.

[[v19-78-55]]

^<<v19-78-55,55>>^ Expulsou nações que lá estavam, distribuiu-lhes as terras por herança e deu suas tendas às tribos de Israel para que nelas habitassem.

[[v19-78-56]]

^<<v19-78-56,56>>^ Mas eles puseram Deus à prova e foram rebeldes contra o Altíssimo; não obedeceram aos seus testemunhos.

[[v19-78-57]]

^<<v19-78-57,57>>^ Foram desleais e infiéis, como os seus antepassados, confiáveis como um arco defeituoso.

[[v19-78-58]]

^<<v19-78-58,58>>^ Eles o irritaram com os altares idólatras; com os seus ídolos lhe provocaram ciúmes.

[[v19-78-59]]

^<<v19-78-59,59>>^ Sabendo-o Deus, enfureceu-se e rejeitou totalmente a Israel;

[[v19-78-60]]

^<<v19-78-60,60>>^ abandonou o tabernáculo de Siló, a tenda onde habitava entre os homens.

[[v19-78-61]]

^<<v19-78-61,61>>^ Entregou o símbolo do seu poder ao cativeiro, e o seu esplendor, nas mãos do adversário.

[[v19-78-62]]

^<<v19-78-62,62>>^ Deixou que o seu povo fosse morto à espada, pois enfureceu-se com a sua herança.

[[v19-78-63]]

^<<v19-78-63,63>>^ O fogo consumiu os seus jovens, e as suas moças não tiveram canções de núpcias;

[[v19-78-64]]

^<<v19-78-64,64>>^ os sacerdotes foram mortos à espada! As viúvas já nem podiam chorar!

[[v19-78-65]]

^<<v19-78-65,65>>^ Então o Senhor despertou como que de um sono, como um guerreiro exaltado pelo vinho.

[[v19-78-66]]

^<<v19-78-66,66>>^ Fez retroceder a golpes os seus adversários e os entregou a permanente humilhação.

[[v19-78-67]]

^<<v19-78-67,67>>^ Também rejeitou as tendas de José, e não escolheu a tribo de Efraim;

[[v19-78-68]]

^<<v19-78-68,68>>^ ao contrário, escolheu a tribo de Judá e o monte Sião, o qual amou.

[[v19-78-69]]

^<<v19-78-69,69>>^ Construiu o seu santuário como as alturas; como a terra o firmou para sempre.

[[v19-78-70]]

^<<v19-78-70,70>>^ Escolheu o seu servo Davi e o tirou do aprisco das ovelhas,

[[v19-78-71]]

^<<v19-78-71,71>>^ do pastoreio de ovelhas para ser o pastor de Jacó, seu povo, de Israel, sua herança.

[[v19-78-72]]

^<<v19-78-72,72>>^ E de coração íntegro Davi os pastoreou, com mãos experientes os conduziu.

'''

xref:019-salmos/019-salmos-077.adoc#v19-77-0[&#60; Capítulo Anterior] | <<v19-78-0,Topo>> | xref:019-salmos/019-salmos-079.adoc#v19-79-0[Próximo Capítulo &#62;]