include::./index.adoc[]

[[v19-14-0]]
=== Salmos, 14
// nvi ?, NVI - Nova Versão Internacional

[[v19-14-1]]

^<<v19-14-1,1>>^ Diz o tolo em seu coração: "Deus não existe". Corromperam-se e cometeram atos detestáveis; não há ninguém que faça o bem.

[[v19-14-2]]

^<<v19-14-2,2>>^ O Senhor olha dos céus para os filhos dos homens, para ver se há alguém que tenha entendimento, alguém que busque a Deus.

[[v19-14-3]]

^<<v19-14-3,3>>^ Todos se desviaram, igualmente se corromperam; não há ninguém que faça o bem, não há nem um sequer.

[[v19-14-4]]

^<<v19-14-4,4>>^ Será que nenhum dos malfeitores aprende? Eles devoram o meu povo como quem come pão, e não clamam pelo Senhor!

[[v19-14-5]]

^<<v19-14-5,5>>^ Olhem! Estão tomados de pavor! Pois Deus está presente no meio dos justos.

[[v19-14-6]]

^<<v19-14-6,6>>^ Vocês, malfeitores, frustram os planos dos pobres, mas o refúgio deles é o Senhor.

[[v19-14-7]]

^<<v19-14-7,7>>^ Ah, se de Sião viesse a salvação para Israel! Quando o Senhor restaurar o seu povo, Jacó exultará! Israel se regozijará!

'''

xref:019-salmos/019-salmos-013.adoc#v19-13-0[&#60; Capítulo Anterior] | <<v19-14-0,Topo>> | xref:019-salmos/019-salmos-015.adoc#v19-15-0[Próximo Capítulo &#62;]