include::./index.adoc[]

[[v19-86-0]]
=== Salmos, 86
// nvi ?, NVI - Nova Versão Internacional

[[v19-86-1]]

^<<v19-86-1,1>>^ Inclina os teus ouvidos, ó Senhor, e responde-me, pois sou pobre e necessitado.

[[v19-86-2]]

^<<v19-86-2,2>>^ Guarda a minha vida, pois sou fiel a ti. Tu és o meu Deus; salva o teu servo que em ti confia!

[[v19-86-3]]

^<<v19-86-3,3>>^ Misericórdia, Senhor, pois clamo a ti sem cessar.

[[v19-86-4]]

^<<v19-86-4,4>>^ Alegra o coração do teu servo, pois a ti, Senhor, elevo a minha alma.

[[v19-86-5]]

^<<v19-86-5,5>>^ Tu és bondoso e perdoador, Senhor, rico em graça para com todos os que te invocam.

[[v19-86-6]]

^<<v19-86-6,6>>^ Escuta a minha oração, Senhor; atenta para a minha súplica!

[[v19-86-7]]

^<<v19-86-7,7>>^ No dia da minha angústia clamarei a ti, pois tu me responderás.

[[v19-86-8]]

^<<v19-86-8,8>>^ Nenhum dos deuses é comparável a ti, Senhor, nenhum deles pode fazer o que tu fazes.

[[v19-86-9]]

^<<v19-86-9,9>>^ Todas as nações que tu formaste virão e te adorarão, Senhor, glorificarão o teu nome.

[[v19-86-10]]

^<<v19-86-10,10>>^ Pois tu és grande e realizas feitos maravilhosos; só tu és Deus!

[[v19-86-11]]

^<<v19-86-11,11>>^ Ensina-me o teu caminho, Senhor, para que eu ande na tua verdade; dá-me um coração inteiramente fiel, para que eu tema o teu nome.

[[v19-86-12]]

^<<v19-86-12,12>>^ De todo o meu coração te louvarei, Senhor, meu Deus; glorificarei o teu nome para sempre.

[[v19-86-13]]

^<<v19-86-13,13>>^ Pois grande é o teu amor para comigo; tu me livraste das profundezas do Sheol.

[[v19-86-14]]

^<<v19-86-14,14>>^ Os arrogantes estão me atacando, ó Deus; um bando de homens cruéis, gente que não faz caso de ti procura tirar-me a vida.

[[v19-86-15]]

^<<v19-86-15,15>>^ Mas tu, Senhor, és Deus compassivo e misericordioso, muito paciente, rico em amor e em fidelidade.

[[v19-86-16]]

^<<v19-86-16,16>>^ Volta-te para mim! Tem misericórdia de mim! Concede a tua força a teu servo e salva o filho da tua serva.

[[v19-86-17]]

^<<v19-86-17,17>>^ Dá-me um sinal da tua bondade, para que os meus inimigos vejam e sejam humilhados, pois tu, Senhor, me ajudaste e me consolaste.

'''

xref:019-salmos/019-salmos-085.adoc#v19-85-0[&#60; Capítulo Anterior] | <<v19-86-0,Topo>> | xref:019-salmos/019-salmos-087.adoc#v19-87-0[Próximo Capítulo &#62;]