include::./index.adoc[]

[[v19-75-0]]
=== Salmos, 75
// nvi ?, NVI - Nova Versão Internacional

[[v19-75-1]]

^<<v19-75-1,1>>^ Damos-te graças, ó Deus, damos graças, pois perto está o teu nome; todos falam dos teus feitos maravilhosos.

[[v19-75-2]]

^<<v19-75-2,2>>^ Tu dizes: "Eu determino o tempo em que julgarei com justiça.

[[v19-75-3]]

^<<v19-75-3,3>>^ Quando treme a terra com todos os seus habitantes, sou eu que mantenho firmes as suas colunas. Pausa

[[v19-75-4]]

^<<v19-75-4,4>>^ Aos arrogantes digo: ‘Parem de vangloriar-se! ’ E aos ímpios: ‘Não se rebelem!

[[v19-75-5]]

^<<v19-75-5,5>>^ Não se rebelem contra os céus; não falem com insolência’ ".

[[v19-75-6]]

^<<v19-75-6,6>>^ Não é do Oriente nem do Ocidente nem do deserto que vem a exaltação.

[[v19-75-7]]

^<<v19-75-7,7>>^ É Deus quem julga: Humilha a um, a outro exalta.

[[v19-75-8]]

^<<v19-75-8,8>>^ Na mão do Senhor está um cálice cheio de vinho espumante e misturado; ele o derrama, e todos os ímpios da terra o bebem até a última gota.

[[v19-75-9]]

^<<v19-75-9,9>>^ Quanto a mim, para sempre anunciarei essas coisas; cantarei louvores ao Deus de Jacó.

[[v19-75-10]]

^<<v19-75-10,10>>^ Destruirei o poder de todos os ímpios, mas o poder dos justos aumentará.

'''

xref:019-salmos/019-salmos-074.adoc#v19-74-0[&#60; Capítulo Anterior] | <<v19-75-0,Topo>> | xref:019-salmos/019-salmos-076.adoc#v19-76-0[Próximo Capítulo &#62;]