include::./index.adoc[]

[[v19-73-0]]
=== Salmos, 73
// nvi ?, NVI - Nova Versão Internacional

[[v19-73-1]]

^<<v19-73-1,1>>^ Certamente Deus é bom para Israel, para os puros de coração.

[[v19-73-2]]

^<<v19-73-2,2>>^ Quanto a mim, os meus pés quase tropeçaram; por pouco não escorreguei.

[[v19-73-3]]

^<<v19-73-3,3>>^ Pois tive inveja dos arrogantes quando vi a prosperidade desses ímpios.

[[v19-73-4]]

^<<v19-73-4,4>>^ Eles não passam por sofrimento e têm o corpo saudável e forte.

[[v19-73-5]]

^<<v19-73-5,5>>^ Estão livres dos fardos de todos; não são atingidos por doenças como os outros homens.

[[v19-73-6]]

^<<v19-73-6,6>>^ Por isso o orgulho lhes serve de colar, e se vestem de violência.

[[v19-73-7]]

^<<v19-73-7,7>>^ Do seu íntimo brota a maldade; da sua mente transbordam maquinações.

[[v19-73-8]]

^<<v19-73-8,8>>^ Eles zombam e falam com más intenções; em sua arrogância ameaçam com opressão.

[[v19-73-9]]

^<<v19-73-9,9>>^ Com a boca arrogam a si os céus, e com a língua se apossam da terra.

[[v19-73-10]]

^<<v19-73-10,10>>^ Por isso o seu povo se volta para eles e bebem suas palavras até saciar-se.

[[v19-73-11]]

^<<v19-73-11,11>>^ Eles dizem: "Como saberá Deus? Terá conhecimento o Altíssimo? "

[[v19-73-12]]

^<<v19-73-12,12>>^ Assim são os ímpios; sempre despreocupados, aumentam suas riquezas.

[[v19-73-13]]

^<<v19-73-13,13>>^ Certamente foi-me inútil manter puro o coração e lavar as mãos na inocência,

[[v19-73-14]]

^<<v19-73-14,14>>^ pois o dia inteiro sou afligido, e todas as manhãs sou castigado.

[[v19-73-15]]

^<<v19-73-15,15>>^ Se eu tivesse dito "falarei com eles", teria traído os teus filhos.

[[v19-73-16]]

^<<v19-73-16,16>>^ Quando tentei entender tudo isso, achei muito difícil para mim,

[[v19-73-17]]

^<<v19-73-17,17>>^ até que entrei no santuário de Deus, e então compreendi o destino dos ímpios.

[[v19-73-18]]

^<<v19-73-18,18>>^ Certamente os pões em terreno escorregadio e os fazes cair na ruína.

[[v19-73-19]]

^<<v19-73-19,19>>^ Como são destruídos de repente, completamente tomados de pavor!

[[v19-73-20]]

^<<v19-73-20,20>>^ São como um sonho que se vai quando a gente acorda; quando te levantares, Senhor, tu os farás desaparecer.

[[v19-73-21]]

^<<v19-73-21,21>>^ Quando o meu coração estava amargurado e no íntimo eu sentia inveja,

[[v19-73-22]]

^<<v19-73-22,22>>^ agi como insensato e ignorante; minha atitude para contigo era a de um animal irracional.

[[v19-73-23]]

^<<v19-73-23,23>>^ Contudo, sempre estou contigo; tomas a minha mão direita e me susténs.

[[v19-73-24]]

^<<v19-73-24,24>>^ Tu me diriges com o teu conselho, e depois me receberás com honras.

[[v19-73-25]]

^<<v19-73-25,25>>^ A quem tenho nos céus senão a ti? E na terra, nada mais desejo além de estar junto a ti.

[[v19-73-26]]

^<<v19-73-26,26>>^ O meu corpo e o meu coração poderão fraquejar, mas Deus é a força do meu coração e a minha herança para sempre.

[[v19-73-27]]

^<<v19-73-27,27>>^ Os que te abandonam sem dúvida perecerão; tu destróis todos os infiéis.

[[v19-73-28]]

^<<v19-73-28,28>>^ Mas, para mim, bom é estar perto de Deus; fiz do Soberano Senhor o meu refúgio; proclamarei todos os teus feitos.

'''

xref:019-salmos/019-salmos-072.adoc#v19-72-0[&#60; Capítulo Anterior] | <<v19-73-0,Topo>> | xref:019-salmos/019-salmos-074.adoc#v19-74-0[Próximo Capítulo &#62;]