include::./index.adoc[]

[[v19-31-0]]
=== Salmos, 31
// nvi ?, NVI - Nova Versão Internacional

[[v19-31-1]]

^<<v19-31-1,1>>^ Em ti, Senhor, me refugio; nunca permitas que eu seja humilhado; livra-me pela tua justiça.

[[v19-31-2]]

^<<v19-31-2,2>>^ Inclina os teus ouvidos para mim, vem livrar-me depressa! Sê minha rocha de refúgio, uma fortaleza poderosa para me salvar.

[[v19-31-3]]

^<<v19-31-3,3>>^ Sim, tu és a minha rocha e a minha fortaleza; por amor do teu nome, conduze-me e guia-me.

[[v19-31-4]]

^<<v19-31-4,4>>^ Tira-me da armadilha que me prepararam, pois tu és o meu refúgio.

[[v19-31-5]]

^<<v19-31-5,5>>^ Nas tuas mãos entrego o meu espírito; resgata-me, Senhor, Deus da verdade.

[[v19-31-6]]

^<<v19-31-6,6>>^ Odeio aqueles que se apegam a ídolos inúteis; eu, porém, confio no Senhor.

[[v19-31-7]]

^<<v19-31-7,7>>^ Exultarei com grande alegria por teu amor, pois viste a minha aflição e conheceste a angústia da minha alma.

[[v19-31-8]]

^<<v19-31-8,8>>^ Não me entregaste nas mãos dos meus inimigos; deste-me segurança e liberdade.

[[v19-31-9]]

^<<v19-31-9,9>>^ Misericórdia, Senhor! Estou em desespero! A tristeza me consome a vista, o vigor e o apetite.

[[v19-31-10]]

^<<v19-31-10,10>>^ Minha vida é consumida pela angústia, e os meus anos pelo gemido; falta-me a força devido à minha aflição, e os meus ossos se enfraquecem.

[[v19-31-11]]

^<<v19-31-11,11>>^ Por causa de todos os meus adversários, sou motivo de ultraje para os meus vizinhos e de medo para os meus amigos; os que me vêem na rua fogem de mim.

[[v19-31-12]]

^<<v19-31-12,12>>^ Sou esquecido por eles como se estivesse morto; tornei-me como um pote quebrado.

[[v19-31-13]]

^<<v19-31-13,13>>^ Ouço muitos cochicharem a meu respeito; o pavor me domina, pois conspiram contra mim, tramando tirar-me a vida.

[[v19-31-14]]

^<<v19-31-14,14>>^ Mas eu confio em ti, Senhor, e digo: "Tu és o meu Deus".

[[v19-31-15]]

^<<v19-31-15,15>>^ O meu futuro está nas tuas mãos; livra-me dos meus inimigos e daqueles que me perseguem.

[[v19-31-16]]

^<<v19-31-16,16>>^ Faze o teu rosto resplandecer sobre o teu servo; salva-me por teu amor leal.

[[v19-31-17]]

^<<v19-31-17,17>>^ Não permitas que eu seja humilhado, Senhor, pois tenho clamado a ti; mas que os ímpios sejam humilhados e calados fiquem no Sheol.

[[v19-31-18]]

^<<v19-31-18,18>>^ Sejam emudecidos os seus lábios mentirosos, pois com arrogância e desprezo humilham os justos.

[[v19-31-19]]

^<<v19-31-19,19>>^ Como é grande a tua bondade, que reservaste para aqueles que te temem, e que, à vista dos homens, concedes àqueles que se refugiam em ti!

[[v19-31-20]]

^<<v19-31-20,20>>^ No abrigo da tua presença os escondes das intrigas dos homens; na tua habitação os proteges das línguas acusadoras.

[[v19-31-21]]

^<<v19-31-21,21>>^ Bendito seja o Senhor, pois mostrou o seu maravilhoso amor para comigo quando eu estava numa cidade cercada.

[[v19-31-22]]

^<<v19-31-22,22>>^ Alarmado, eu disse: "Fui excluído da tua presença! " Contudo, ouviste as minhas súplicas quando clamei a ti por socorro.

[[v19-31-23]]

^<<v19-31-23,23>>^ Amem o Senhor, todos vocês, os seus santos! O Senhor preserva os fiéis, mas aos arrogantes dá o que merecem.

[[v19-31-24]]

^<<v19-31-24,24>>^ Sejam fortes e corajosos, todos vocês que esperam no Senhor!

'''

xref:019-salmos/019-salmos-030.adoc#v19-30-0[&#60; Capítulo Anterior] | <<v19-31-0,Topo>> | xref:019-salmos/019-salmos-032.adoc#v19-32-0[Próximo Capítulo &#62;]