include::./index.adoc[]

[[v19-44-0]]
=== Salmos, 44
// nvi ?, NVI - Nova Versão Internacional

[[v19-44-1]]

^<<v19-44-1,1>>^ Com os nossos próprios ouvidos ouvimos, ó Deus; os nossos antepassados nos contaram os feitos que realizaste no tempo deles, nos dias da antigüidade.

[[v19-44-2]]

^<<v19-44-2,2>>^ Com a tua própria mão expulsaste as nações para estabelecer os nossos antepassados; arruinaste povos e fizeste prosperar os nossos antepassados.

[[v19-44-3]]

^<<v19-44-3,3>>^ Não foi pela espada que conquistaram a terra, nem pela força do braço que alcançaram a vitória; foi pela tua mão direita, pelo teu braço, e pela luz do teu rosto, por causa do teu amor para com eles.

[[v19-44-4]]

^<<v19-44-4,4>>^ És tu, meu Rei e meu Deus! Tu decretas vitórias para Jacó!

[[v19-44-5]]

^<<v19-44-5,5>>^ Contigo pomos em fuga os nossos adversários; pelo teu nome pisoteamos os que nos atacam.

[[v19-44-6]]

^<<v19-44-6,6>>^ Não confio em meu arco, minha espada não me concede a vitória;

[[v19-44-7]]

^<<v19-44-7,7>>^ mas tu nos concedes a vitória sobre os nossos adversários e humilhas os que nos odeiam.

[[v19-44-8]]

^<<v19-44-8,8>>^ Em Deus nos gloriamos o tempo todo, e louvaremos o teu nome para sempre. Pausa

[[v19-44-9]]

^<<v19-44-9,9>>^ Mas agora nos rejeitaste e nos humilhaste; já não sais com os nossos exércitos.

[[v19-44-10]]

^<<v19-44-10,10>>^ Diante dos nossos adversários fizeste-nos bater em retirada, e os que nos odeiam nos saquearam.

[[v19-44-11]]

^<<v19-44-11,11>>^ Tu nos entregaste para sermos devorados como ovelhas e nos dispersaste entre as nações.

[[v19-44-12]]

^<<v19-44-12,12>>^ Vendeste o teu povo por uma ninharia, nada lucrando com a sua venda.

[[v19-44-13]]

^<<v19-44-13,13>>^ Tu nos fizeste objeto de vergonha dos nossos vizinhos, de zombaria e menosprezo dos que nos rodeiam.

[[v19-44-14]]

^<<v19-44-14,14>>^ Fizeste de nós um provérbio entre as nações; os povos meneiam a cabeça quando nos vêem.

[[v19-44-15]]

^<<v19-44-15,15>>^ Sofro humilhação o tempo todo, e o meu rosto está coberto de vergonha

[[v19-44-16]]

^<<v19-44-16,16>>^ por causa da zombaria dos que me censuram e me provocam, por causa do inimigo, que busca vingança.

[[v19-44-17]]

^<<v19-44-17,17>>^ Tudo isso aconteceu conosco, sem que nos tivéssemos esquecido de ti, nem tivéssemos traído a tua aliança.

[[v19-44-18]]

^<<v19-44-18,18>>^ Nossos corações não voltaram atrás, nem os nossos pés se desviaram da tua vereda.

[[v19-44-19]]

^<<v19-44-19,19>>^ Todavia, tu nos esmagaste e fizeste de nós um covil de chacais e de densas trevas nos cobriste.

[[v19-44-20]]

^<<v19-44-20,20>>^ Se tivéssemos esquecido o nome do nosso Deus e tivéssemos estendido as nossas mãos a um deus estrangeiro,

[[v19-44-21]]

^<<v19-44-21,21>>^ Deus não o teria descoberto? Pois ele conhece os segredos do coração!

[[v19-44-22]]

^<<v19-44-22,22>>^ Contudo, por amor de ti enfrentamos a morte todos os dias; somos considerados como ovelhas destinadas ao matadouro.

[[v19-44-23]]

^<<v19-44-23,23>>^ Desperta, Senhor! Por que dormes? Levanta-te! Não nos rejeites para sempre.

[[v19-44-24]]

^<<v19-44-24,24>>^ Por que escondes o teu rosto e esqueces o nosso sofrimento e a nossa aflição?

[[v19-44-25]]

^<<v19-44-25,25>>^ Fomos humilhados até o pó; nossos corpos se apegam ao chão.

[[v19-44-26]]

^<<v19-44-26,26>>^ Levanta-te! Socorre-nos! Resgata-nos por causa da tua fidelidade.

'''

xref:019-salmos/019-salmos-043.adoc#v19-43-0[&#60; Capítulo Anterior] | <<v19-44-0,Topo>> | xref:019-salmos/019-salmos-045.adoc#v19-45-0[Próximo Capítulo &#62;]