include::./index.adoc[]

[[v19-22-0]]
=== Salmos, 22
// nvi ?, NVI - Nova Versão Internacional

[[v19-22-1]]

^<<v19-22-1,1>>^ Meu Deus! Meu Deus! Por que me abandonaste? Por que estás tão longe de salvar-me, tão longe dos meus gritos de angústia?

[[v19-22-2]]

^<<v19-22-2,2>>^ Meu Deus! Eu clamo de dia, mas não respondes; de noite, e não recebo alívio!

[[v19-22-3]]

^<<v19-22-3,3>>^ Tu, porém, és o Santo, és rei, és o louvor de Israel.

[[v19-22-4]]

^<<v19-22-4,4>>^ Em ti os nossos antepassados puseram a sua confiança; confiaram, e os livraste.

[[v19-22-5]]

^<<v19-22-5,5>>^ Clamaram a ti, e foram libertos; em ti confiaram, e não se decepcionaram.

[[v19-22-6]]

^<<v19-22-6,6>>^ Mas eu sou verme, e não homem, motivo de zombaria e objeto de desprezo do povo.

[[v19-22-7]]

^<<v19-22-7,7>>^ Caçoam de mim todos os que me vêem; balançando a cabeça, lançam insultos contra mim, dizendo:

[[v19-22-8]]

^<<v19-22-8,8>>^ "Recorra ao Senhor! Que o Senhor o liberte! Que ele o livre, já que lhe quer bem! "

[[v19-22-9]]

^<<v19-22-9,9>>^ Contudo, tu mesmo me tiraste do ventre; deste-me segurança junto ao seio de minha mãe.

[[v19-22-10]]

^<<v19-22-10,10>>^ Desde que nasci fui entregue a ti; desde o ventre materno és o meu Deus.

[[v19-22-11]]

^<<v19-22-11,11>>^ Não fiques distante de mim, pois a angústia está perto e não há ninguém que me socorra.

[[v19-22-12]]

^<<v19-22-12,12>>^ Muitos touros me cercam, sim, rodeiam-me os poderosos de Basã.

[[v19-22-13]]

^<<v19-22-13,13>>^ Como leão voraz rugindo escancaram a boca contra mim.

[[v19-22-14]]

^<<v19-22-14,14>>^ Como água me derramei, e todos os meus ossos estão desconjuntados. Meu coração se tornou como cera; derreteu-se no meu íntimo.

[[v19-22-15]]

^<<v19-22-15,15>>^ Meu vigor secou-se como um caco de barro, e a minha língua gruda no céu da boca; deixaste-me no pó, à beira da morte.

[[v19-22-16]]

^<<v19-22-16,16>>^ Cães me rodearam! Um bando de homens maus me cercou! Perfuraram minhas mãos e meus pés.

[[v19-22-17]]

^<<v19-22-17,17>>^ Posso contar todos os meus ossos, mas eles me encaram com desprezo.

[[v19-22-18]]

^<<v19-22-18,18>>^ Dividiram as minhas roupas entre si, e tiraram sortes pelas minhas vestes.

[[v19-22-19]]

^<<v19-22-19,19>>^ Tu, porém, Senhor, não fiques distante! Ó minha força, vem logo em meu socorro!

[[v19-22-20]]

^<<v19-22-20,20>>^ Livra-me da espada, livra a minha vida do ataque dos cães.

[[v19-22-21]]

^<<v19-22-21,21>>^ Salva-me da boca dos leões, e dos chifres dos bois selvagens. E tu me respondeste.

[[v19-22-22]]

^<<v19-22-22,22>>^ Proclamarei o teu nome a meus irmãos; na assembléia te louvarei.

[[v19-22-23]]

^<<v19-22-23,23>>^ Louvem-no, vocês que temem o Senhor! Glorifiquem-no, todos vocês, descendentes de Jacó! Tremam diante dele, todos vocês, descendentes de Israel!

[[v19-22-24]]

^<<v19-22-24,24>>^ Pois não menosprezou nem repudiou o sofrimento do aflito; não escondeu dele o rosto, mas ouviu o seu grito de socorro.

[[v19-22-25]]

^<<v19-22-25,25>>^ De ti vem o tema do meu louvor na grande assembléia; na presença dos que te temem cumprirei os meus votos.

[[v19-22-26]]

^<<v19-22-26,26>>^ Os pobres comerão até ficarem satisfeitos; aqueles que buscam o Senhor o louvarão! Que vocês tenham vida longa!

[[v19-22-27]]

^<<v19-22-27,27>>^ Todos os confins da terra se lembrarão e se voltarão para o Senhor, e todas as famílias das nações se prostrarão diante dele,

[[v19-22-28]]

^<<v19-22-28,28>>^ pois do Senhor é o reino; ele governa as nações.

[[v19-22-29]]

^<<v19-22-29,29>>^ Todos os ricos da terra se banquetearão e o adorarão; haverão de ajoelhar-se diante dele todos os que descem ao pó, cuja vida se esvai.

[[v19-22-30]]

^<<v19-22-30,30>>^ A posteridade o servirá; gerações futuras ouvirão falar do Senhor,

[[v19-22-31]]

^<<v19-22-31,31>>^ e a um povo que ainda não nasceu proclamarão seus feitos de justiça, pois ele agiu poderosamente.

'''

xref:019-salmos/019-salmos-021.adoc#v19-21-0[&#60; Capítulo Anterior] | <<v19-22-0,Topo>> | xref:019-salmos/019-salmos-023.adoc#v19-23-0[Próximo Capítulo &#62;]