include::./index.adoc[]

[[v19-8-0]]
=== Salmos, 8
// nvi ?, NVI - Nova Versão Internacional

[[v19-8-1]]

^<<v19-8-1,1>>^ Senhor, Senhor nosso, como é majestoso o teu nome em toda a terra! Tu, cuja glória é cantada nos céus.

[[v19-8-2]]

^<<v19-8-2,2>>^ Dos lábios das crianças e dos recém-nascidos firmaste o teu nome como fortaleza, por causa dos teus adversários, para silenciar o inimigo que busca vingança.

[[v19-8-3]]

^<<v19-8-3,3>>^ Quando contemplo os teus céus, obra dos teus dedos, a lua e as estrelas que ali firmaste,

[[v19-8-4]]

^<<v19-8-4,4>>^ pergunto: Que é o homem, para que com ele te importes? E o filho do homem, para que com ele te preocupes?

[[v19-8-5]]

^<<v19-8-5,5>>^ Tu o fizeste um pouco menor do que os seres celestiais e o coroaste de glória e de honra.

[[v19-8-6]]

^<<v19-8-6,6>>^ Tu o fizeste dominar sobre as obras das tuas mãos; sob os seus pés tudo puseste:

[[v19-8-7]]

^<<v19-8-7,7>>^ Todos os rebanhos e manadas, e até os animais selvagens,

[[v19-8-8]]

^<<v19-8-8,8>>^ as aves do céu, os peixes do mar e tudo o que percorre as veredas dos mares.

[[v19-8-9]]

^<<v19-8-9,9>>^ Senhor, Senhor nosso, como é majestoso o teu nome em toda a terra!

'''

xref:019-salmos/019-salmos-007.adoc#v19-7-0[&#60; Capítulo Anterior] | <<v19-8-0,Topo>> | xref:019-salmos/019-salmos-009.adoc#v19-9-0[Próximo Capítulo &#62;]