include::./index.adoc[]

[[v19-17-0]]
=== Salmos, 17
// nvi ?, NVI - Nova Versão Internacional

[[v19-17-1]]

^<<v19-17-1,1>>^ Ouve, Senhor, a minha justa queixa; atenta para o meu clamor. Dá ouvidos à minha oração, que não vem de lábios falsos.

[[v19-17-2]]

^<<v19-17-2,2>>^ Venha de ti a sentença em meu favor; vejam os teus olhos onde está a justiça!

[[v19-17-3]]

^<<v19-17-3,3>>^ Provas o meu coração e de noite me examinas, tu me sondas, e nada encontras; decidi que a minha boca não pecará

[[v19-17-4]]

^<<v19-17-4,4>>^ como fazem os homens. Pela palavra dos teus lábios eu evitei os caminhos do violento.

[[v19-17-5]]

^<<v19-17-5,5>>^ Meus passos seguem firmes nas tuas veredas; os meus pés não escorregaram.

[[v19-17-6]]

^<<v19-17-6,6>>^ Eu clamo a ti, ó Deus, pois tu me respondes; inclina para mim os teus ouvidos e ouve a minha oração.

[[v19-17-7]]

^<<v19-17-7,7>>^ Mostra a maravilha do teu amor, tu, que com a tua mão direita salvas os que em ti buscam proteção contra aqueles que os ameaçam.

[[v19-17-8]]

^<<v19-17-8,8>>^ Protege-me como à menina dos teus olhos; esconde-me à sombra das tuas asas,

[[v19-17-9]]

^<<v19-17-9,9>>^ dos ímpios que me atacam com violência, dos inimigos mortais que me cercam.

[[v19-17-10]]

^<<v19-17-10,10>>^ Eles fecham o coração insensível, e com a boca falam com arrogância.

[[v19-17-11]]

^<<v19-17-11,11>>^ Eles me seguem os passos, e já me cercam; seus olhos estão atentos, prontos para derrubar-me.

[[v19-17-12]]

^<<v19-17-12,12>>^ São como um leão ávido pela presa, como um leão forte agachado na emboscada.

[[v19-17-13]]

^<<v19-17-13,13>>^ Levanta-te, Senhor! Confronta-os! Derruba-os! Com a tua espada livra-me dos ímpios.

[[v19-17-14]]

^<<v19-17-14,14>>^ Com a tua mão, Senhor, livra-me de homens assim, de homens deste mundo, cuja recompensa está nesta vida. Enche-lhes o ventre de tudo o que lhes reservaste; sejam os seus filhos saciados, e o que sobrar fique para os seus pequeninos.

[[v19-17-15]]

^<<v19-17-15,15>>^ Quanto a mim, feita a justiça, verei a tua face; quando despertar ficarei satisfeito ao ver a tua semelhança.

'''

xref:019-salmos/019-salmos-016.adoc#v19-16-0[&#60; Capítulo Anterior] | <<v19-17-0,Topo>> | xref:019-salmos/019-salmos-018.adoc#v19-18-0[Próximo Capítulo &#62;]