include::./index.adoc[]

[[v19-53-0]]
=== Salmos, 53
// nvi ?, NVI - Nova Versão Internacional

[[v19-53-1]]

^<<v19-53-1,1>>^ Diz o tolo em seu coração: "Deus não existe! " Corromperam-se e cometeram injustiças detestáveis; não há ninguém que faça o bem.

[[v19-53-2]]

^<<v19-53-2,2>>^ Deus olha lá dos céus para os filhos dos homens, para ver se há alguém que tenha entendimento, alguém que busque a Deus.

[[v19-53-3]]

^<<v19-53-3,3>>^ Todos se desviaram, igualmente se corromperam; não há ninguém que faça o bem, não há nem um sequer.

[[v19-53-4]]

^<<v19-53-4,4>>^ Será que os malfeitores não aprendem? Eles devoram o meu povo como quem come pão, e não clamam a Deus!

[[v19-53-5]]

^<<v19-53-5,5>>^ Olhem! Estão tomados de pavor, quando não existe motivo algum para temer! Pois foi Deus quem espalhou os ossos dos que atacaram você; você os humilhou porque Deus os rejeitou.

[[v19-53-6]]

^<<v19-53-6,6>>^ Ah, se de Sião viesse a salvação para Israel! Quando Deus restaurar o seu povo, Jacó exultará! Israel se regozijará!

'''

xref:019-salmos/019-salmos-052.adoc#v19-52-0[&#60; Capítulo Anterior] | <<v19-53-0,Topo>> | xref:019-salmos/019-salmos-054.adoc#v19-54-0[Próximo Capítulo &#62;]