include::./index.adoc[]

[[v19-101-0]]
=== Salmos, 101
// nvi ?, NVI - Nova Versão Internacional

[[v19-101-1]]

^<<v19-101-1,1>>^ Cantarei a lealdade e a justiça. A ti, Senhor, cantarei louvores!

[[v19-101-2]]

^<<v19-101-2,2>>^ Seguirei o caminho da integridade; quando virás ao meu encontro? Em minha casa viverei de coração íntegro.

[[v19-101-3]]

^<<v19-101-3,3>>^ Repudiarei todo mal. Odeio a conduta dos infiéis; jamais me dominará!

[[v19-101-4]]

^<<v19-101-4,4>>^ Longe estou dos perversos de coração; não quero envolver-me com o mal.

[[v19-101-5]]

^<<v19-101-5,5>>^ Farei calar ao que difama o próximo às ocultas. Não vou tolerar o homem de olhos arrogantes e de coração orgulhoso.

[[v19-101-6]]

^<<v19-101-6,6>>^ Meus olhos aprovam os fiéis da terra, e eles habitarão comigo. Somente quem tem vida íntegra me servirá.

[[v19-101-7]]

^<<v19-101-7,7>>^ Quem pratica a fraude não habitará no meu santuário; o mentiroso não permanecerá na minha presença.

[[v19-101-8]]

^<<v19-101-8,8>>^ Cada manhã fiz calar todos os ímpios desta terra; eliminei todos os malfeitores da cidade do Senhor.

'''

xref:019-salmos/019-salmos-100.adoc#v19-100-0[&#60; Capítulo Anterior] | <<v19-101-0,Topo>> | xref:019-salmos/019-salmos-102.adoc#v19-102-0[Próximo Capítulo &#62;]