include::./index.adoc[]

[[v19-115-0]]
=== Salmos, 115
// nvi ?, NVI - Nova Versão Internacional

[[v19-115-1]]

^<<v19-115-1,1>>^ Não a nós, Senhor, nenhuma glória para nós, mas sim ao teu nome, por teu amor e por tua fidelidade!

[[v19-115-2]]

^<<v19-115-2,2>>^ Por que perguntam as nações: "Onde está o Deus deles? "

[[v19-115-3]]

^<<v19-115-3,3>>^ O nosso Deus está nos céus, e pode fazer tudo o que lhe agrada.

[[v19-115-4]]

^<<v19-115-4,4>>^ Os ídolos deles, de prata e ouro, são feitos por mãos humanas.

[[v19-115-5]]

^<<v19-115-5,5>>^ Têm boca, mas não podem falar, olhos, mas não podem ver;

[[v19-115-6]]

^<<v19-115-6,6>>^ têm ouvidos, mas não podem ouvir, nariz, mas não podem sentir cheiro;

[[v19-115-7]]

^<<v19-115-7,7>>^ têm mãos, mas nada podem apalpar, pés, mas não podem andar; nem emitem som algum com a garganta.

[[v19-115-8]]

^<<v19-115-8,8>>^ Tornem-se como eles aqueles que os fazem e todos os que neles confiam.

[[v19-115-9]]

^<<v19-115-9,9>>^ Confie no Senhor, ó Israel! Ele é o seu socorro e o seu escudo.

[[v19-115-10]]

^<<v19-115-10,10>>^ Confiem no Senhor, sacerdotes! Ele é o seu socorro e o seu escudo.

[[v19-115-11]]

^<<v19-115-11,11>>^ Vocês que temem ao Senhor, confiem no Senhor! Ele é o seu socorro e o seu escudo.

[[v19-115-12]]

^<<v19-115-12,12>>^ O Senhor lembra-se de nós e nos abençoará: Abençoará os israelitas, abençoará os sacerdotes,

[[v19-115-13]]

^<<v19-115-13,13>>^ abençoará os que temem o Senhor, do menor ao maior.

[[v19-115-14]]

^<<v19-115-14,14>>^ Que o Senhor os multiplique, a vocês e aos seus filhos.

[[v19-115-15]]

^<<v19-115-15,15>>^ Sejam vocês abençoados pelo Senhor, que fez os céus e a terra.

[[v19-115-16]]

^<<v19-115-16,16>>^ Os mais altos céus pertencem ao Senhor, mas a terra ele a confiou ao homem.

[[v19-115-17]]

^<<v19-115-17,17>>^ Os mortos não louvam o Senhor, tampouco nenhum dos que descem ao silêncio.

[[v19-115-18]]

^<<v19-115-18,18>>^ Mas nós bendiremos o Senhor, desde agora e para sempre! Aleluia!

'''

xref:019-salmos/019-salmos-114.adoc#v19-114-0[&#60; Capítulo Anterior] | <<v19-115-0,Topo>> | xref:019-salmos/019-salmos-116.adoc#v19-116-0[Próximo Capítulo &#62;]