include::./index.adoc[]

[[v19-149-0]]
=== Salmos, 149
// nvi ?, NVI - Nova Versão Internacional

[[v19-149-1]]

^<<v19-149-1,1>>^ Aleluia! Cantem ao Senhor uma nova canção, louvem-no na assembléia dos fiéis.

[[v19-149-2]]

^<<v19-149-2,2>>^ Alegre-se Israel no seu criador, exulte o povo de Sião no seu rei!

[[v19-149-3]]

^<<v19-149-3,3>>^ Louvem eles o seu nome com danças; ofereçam-lhe música com tamborim e harpa.

[[v19-149-4]]

^<<v19-149-4,4>>^ O Senhor agrada-se do seu povo; ele coroa de vitória os oprimidos.

[[v19-149-5]]

^<<v19-149-5,5>>^ Regozijem-se os seus fiéis nessa glória e em seus leitos cantem alegremente!

[[v19-149-6]]

^<<v19-149-6,6>>^ Altos louvores estejam em seus lábios e uma espada de dois gumes em suas mãos,

[[v19-149-7]]

^<<v19-149-7,7>>^ para imporem vingança às nações e trazerem castigo aos povos,

[[v19-149-8]]

^<<v19-149-8,8>>^ para prenderem os seus reis com grilhões e seus nobres com algemas de ferro,

[[v19-149-9]]

^<<v19-149-9,9>>^ para executarem a sentença escrita contra eles. Esta é a glória de todos os seus fiéis. Aleluia!

'''

xref:019-salmos/019-salmos-148.adoc#v19-148-0[&#60; Capítulo Anterior] | <<v19-149-0,Topo>> | xref:019-salmos/019-salmos-150.adoc#v19-150-0[Próximo Capítulo &#62;]