include::./index.adoc[]

[[v19-76-0]]
=== Salmos, 76
// nvi ?, NVI - Nova Versão Internacional

[[v19-76-1]]

^<<v19-76-1,1>>^ Em Judá Deus é conhecido; o seu nome é grande em Israel.

[[v19-76-2]]

^<<v19-76-2,2>>^ Sua tenda está em Salém; o lugar da sua habitação está em Sião.

[[v19-76-3]]

^<<v19-76-3,3>>^ Ali quebrou ele as flechas reluzentes, os escudos e as espadas, as armas de guerra. Pausa

[[v19-76-4]]

^<<v19-76-4,4>>^ Resplendes de luz! És mais majestoso que os montes cheios de despojos.

[[v19-76-5]]

^<<v19-76-5,5>>^ Os homens valorosos jazem saqueados, dormem o sono final; nenhum dos guerreiros foi capaz de erguer as mãos.

[[v19-76-6]]

^<<v19-76-6,6>>^ Diante da tua repreensão, ó Deus de Jacó, o cavalo e o carro estacaram.

[[v19-76-7]]

^<<v19-76-7,7>>^ Somente tu és temível. Quem poderá permanecer diante de ti quando estiveres irado?

[[v19-76-8]]

^<<v19-76-8,8>>^ Dos céus pronunciaste juízo, e a terra tremeu e emudeceu,

[[v19-76-9]]

^<<v19-76-9,9>>^ quando tu, ó Deus, te levantaste para julgar, para salvar todos os oprimidos da terra. Pausa

[[v19-76-10]]

^<<v19-76-10,10>>^ Até a tua ira contra os homens redundará em teu louvor, e os sobreviventes da tua ira se refrearão.

[[v19-76-11]]

^<<v19-76-11,11>>^ Façam votos ao Senhor, ao seu Deus, e não deixem de cumpri-los; que todas as nações vizinhas tragam presentes a quem todos devem temer.

[[v19-76-12]]

^<<v19-76-12,12>>^ Ele tira o ânimo dos governantes e é temido pelos reis da terra.

'''

xref:019-salmos/019-salmos-075.adoc#v19-75-0[&#60; Capítulo Anterior] | <<v19-76-0,Topo>> | xref:019-salmos/019-salmos-077.adoc#v19-77-0[Próximo Capítulo &#62;]