include::./index.adoc[]

[[v19-146-0]]
=== Salmos, 146
// nvi ?, NVI - Nova Versão Internacional

[[v19-146-1]]

^<<v19-146-1,1>>^ Aleluia! Louve, ó minha alma ao Senhor.

[[v19-146-2]]

^<<v19-146-2,2>>^ Louvarei ao Senhor por toda a minha vida; cantarei louvores ao meu Deus enquanto eu viver.

[[v19-146-3]]

^<<v19-146-3,3>>^ Não confiem em príncipes, em meros mortais, incapazes de salvar.

[[v19-146-4]]

^<<v19-146-4,4>>^ Quando o espírito deles se vai, voltam ao pó; naquele mesmo dia acabam-se os seus planos.

[[v19-146-5]]

^<<v19-146-5,5>>^ Como é feliz aquele cujo auxílio é o Deus de Jacó, cuja esperança está no Senhor, no seu Deus,

[[v19-146-6]]

^<<v19-146-6,6>>^ que fez os céus e a terra, o mar e tudo o que neles há, e que mantém a sua fidelidade para sempre!

[[v19-146-7]]

^<<v19-146-7,7>>^ Ele defende a causa dos oprimidos e dá alimento aos famintos. O Senhor liberta os presos,

[[v19-146-8]]

^<<v19-146-8,8>>^ o Senhor dá vista aos cegos, o Senhor levanta os abatidos, o Senhor ama os justos.

[[v19-146-9]]

^<<v19-146-9,9>>^ O Senhor protege o estrangeiro e sustém o órfão e a viúva, mas frustra o propósito dos ímpios.

[[v19-146-10]]

^<<v19-146-10,10>>^ O Senhor reina para sempre! O teu Deus, ó Sião, reina de geração em geração. Aleluia!

'''

xref:019-salmos/019-salmos-145.adoc#v19-145-0[&#60; Capítulo Anterior] | <<v19-146-0,Topo>> | xref:019-salmos/019-salmos-147.adoc#v19-147-0[Próximo Capítulo &#62;]