include::./index.adoc[]

[[v19-27-0]]
=== Salmos, 27
// nvi ?, NVI - Nova Versão Internacional

[[v19-27-1]]

^<<v19-27-1,1>>^ O Senhor é a minha luz e a minha salvação; de quem terei temor? O Senhor é o meu forte refúgio; de quem terei medo?

[[v19-27-2]]

^<<v19-27-2,2>>^ Quando homens maus avançarem contra mim para destruir-me, eles, meus inimigos e meus adversários, é que tropeçarão e cairão.

[[v19-27-3]]

^<<v19-27-3,3>>^ Ainda que um exército se acampe contra mim, meu coração não temerá; ainda que se declare guerra contra mim, mesmo assim estarei confiante.

[[v19-27-4]]

^<<v19-27-4,4>>^ Uma coisa pedi ao Senhor, é o que procuro: que eu possa viver na casa do Senhor todos os dias da minha vida, para contemplar a bondade do Senhor e buscar sua orientação no seu templo.

[[v19-27-5]]

^<<v19-27-5,5>>^ Pois no dia da adversidade ele me guardará protegido em sua habitação; no seu tabernáculo me esconderá e me porá em segurança sobre um rochedo.

[[v19-27-6]]

^<<v19-27-6,6>>^ Então triunfarei sobre os inimigos que me cercam. Em seu tabernáculo oferecerei sacrifícios com aclamações; cantarei e louvarei ao Senhor.

[[v19-27-7]]

^<<v19-27-7,7>>^ Ouve a minha voz quando clamo, ó Senhor; tem misericórdia de mim e responde-me.

[[v19-27-8]]

^<<v19-27-8,8>>^ A teu respeito diz o meu coração: "Busque a minha face! " A tua face, Senhor, buscarei.

[[v19-27-9]]

^<<v19-27-9,9>>^ Não escondas de mim a tua face, não rejeites com ira o teu servo; tu tens sido o meu ajudador. Não me desampares nem me abandones, ó Deus, meu salvador!

[[v19-27-10]]

^<<v19-27-10,10>>^ Ainda que me abandonem pai e mãe, o Senhor me acolherá.

[[v19-27-11]]

^<<v19-27-11,11>>^ Ensina-me o teu caminho, Senhor; conduze-me por uma vereda segura por causa dos meus inimigos.

[[v19-27-12]]

^<<v19-27-12,12>>^ Não me entregues ao capricho dos meus adversários, pois testemunhas falsas se levantam contra mim, respirando violência.

[[v19-27-13]]

^<<v19-27-13,13>>^ Apesar disso, esta certeza eu tenho: viverei até ver a bondade do Senhor na terra.

[[v19-27-14]]

^<<v19-27-14,14>>^ Espere no Senhor. Seja forte! Coragem! Espere no Senhor.

'''

xref:019-salmos/019-salmos-026.adoc#v19-26-0[&#60; Capítulo Anterior] | <<v19-27-0,Topo>> | xref:019-salmos/019-salmos-028.adoc#v19-28-0[Próximo Capítulo &#62;]