include::./index.adoc[]

[[v19-61-0]]
=== Salmos, 61
// nvi ?, NVI - Nova Versão Internacional

[[v19-61-1]]

^<<v19-61-1,1>>^ Ouve o meu clamor, ó Deus; atenta para a minha oração.

[[v19-61-2]]

^<<v19-61-2,2>>^ Desde os confins da terra eu clamo a ti, com o coração abatido; põe-me à salvo na rocha mais alta do que eu.

[[v19-61-3]]

^<<v19-61-3,3>>^ Pois tu tens sido o meu refúgio, uma torre forte contra o inimigo.

[[v19-61-4]]

^<<v19-61-4,4>>^ Para sempre anseio habitar na tua tenda e refugiar-me no abrigo das tuas asas. Pausa

[[v19-61-5]]

^<<v19-61-5,5>>^ Pois ouviste os meus votos, ó Deus; deste-me a herança que concedes aos que temem o teu nome.

[[v19-61-6]]

^<<v19-61-6,6>>^ Prolonga os dias do rei, por muitas gerações os seus anos de vida.

[[v19-61-7]]

^<<v19-61-7,7>>^ Para sempre esteja ele em seu trono, diante de Deus; envia o teu amor e a tua fidelidade para protegê-lo.

[[v19-61-8]]

^<<v19-61-8,8>>^ Então sempre cantarei louvores ao teu nome, cumprindo os meus votos cada dia.

'''

xref:019-salmos/019-salmos-060.adoc#v19-60-0[&#60; Capítulo Anterior] | <<v19-61-0,Topo>> | xref:019-salmos/019-salmos-062.adoc#v19-62-0[Próximo Capítulo &#62;]