include::./index.adoc[]

[[v19-95-0]]
=== Salmos, 95
// nvi ?, NVI - Nova Versão Internacional

[[v19-95-1]]

^<<v19-95-1,1>>^ Venham! Cantemos ao Senhor com alegria! Aclamemos a Rocha da nossa salvação.

[[v19-95-2]]

^<<v19-95-2,2>>^ Vamos à presença dele com ações de graças; vamos aclamá-lo com cânticos de louvor.

[[v19-95-3]]

^<<v19-95-3,3>>^ Pois o Senhor é o grande Deus, o grande Rei acima de todos os deuses.

[[v19-95-4]]

^<<v19-95-4,4>>^ Nas suas mãos estão as profundezas da terra, os cumes dos montes lhe pertencem.

[[v19-95-5]]

^<<v19-95-5,5>>^ Dele também é o mar, pois ele o fez; as suas mãos formaram a terra seca.

[[v19-95-6]]

^<<v19-95-6,6>>^ Venham! Adoremos prostrados e ajoelhemos diante do Senhor, o nosso Criador;

[[v19-95-7]]

^<<v19-95-7,7>>^ pois ele é o nosso Deus, e nós somos o povo do seu pastoreio, o rebanho que ele conduz. Hoje, se vocês ouvirem a sua voz,

[[v19-95-8]]

^<<v19-95-8,8>>^ não endureçam o coração, como em Meribá, como aquele dia em Massá, no deserto,

[[v19-95-9]]

^<<v19-95-9,9>>^ onde os seus antepassados me tentaram, pondo-me à prova, apesar de terem visto o que eu fiz.

[[v19-95-10]]

^<<v19-95-10,10>>^ Durante quarenta anos fiquei irado contra aquela geração e disse: "Eles são um povo de coração ingrato; não reconheceram os meus caminhos".

[[v19-95-11]]

^<<v19-95-11,11>>^ Por isso jurei na minha ira: "Jamais entrarão no meu descanso".

'''

xref:019-salmos/019-salmos-094.adoc#v19-94-0[&#60; Capítulo Anterior] | <<v19-95-0,Topo>> | xref:019-salmos/019-salmos-096.adoc#v19-96-0[Próximo Capítulo &#62;]