include::./index.adoc[]

[[v19-51-0]]
=== Salmos, 51
// nvi ?, NVI - Nova Versão Internacional

[[v19-51-1]]

^<<v19-51-1,1>>^ Tem misericórdia de mim, ó Deus, por teu amor; por tua grande compaixão apaga as minhas transgressões.

[[v19-51-2]]

^<<v19-51-2,2>>^ Lava-me de toda a minha culpa e purifica-me do meu pecado.

[[v19-51-3]]

^<<v19-51-3,3>>^ Pois eu mesmo reconheço as minhas transgressões, e o meu pecado sempre me persegue.

[[v19-51-4]]

^<<v19-51-4,4>>^ Contra ti, só contra ti, pequei e fiz o que tu reprovas, de modo que justa é a tua sentença e tens razão em condenar-me.

[[v19-51-5]]

^<<v19-51-5,5>>^ Sei que sou pecador desde que nasci, sim, desde que me concebeu minha mãe.

[[v19-51-6]]

^<<v19-51-6,6>>^ Sei que desejas a verdade no íntimo; e no coração me ensinas a sabedoria.

[[v19-51-7]]

^<<v19-51-7,7>>^ Purifica-me com hissopo, e ficarei puro; lava-me, e mais branco do que a neve serei.

[[v19-51-8]]

^<<v19-51-8,8>>^ Faze-me ouvir de novo júbilo e alegria; e os ossos que esmagaste exultarão.

[[v19-51-9]]

^<<v19-51-9,9>>^ Esconde o rosto dos meus pecados e apaga todas as minhas iniqüidades.

[[v19-51-10]]

^<<v19-51-10,10>>^ Cria em mim um coração puro, ó Deus, e renova dentro de mim um espírito estável.

[[v19-51-11]]

^<<v19-51-11,11>>^ Não me expulses da tua presença, nem tires de mim o teu Santo Espírito.

[[v19-51-12]]

^<<v19-51-12,12>>^ Devolve-me a alegria da tua salvação e sustenta-me com um espírito pronto a obedecer.

[[v19-51-13]]

^<<v19-51-13,13>>^ Então ensinarei os teus caminhos aos transgressores, para que os pecadores se voltem para ti.

[[v19-51-14]]

^<<v19-51-14,14>>^ Livra-me da culpa dos crimes de sangue, ó Deus, Deus da minha salvação! E a minha língua aclamará à tua justiça.

[[v19-51-15]]

^<<v19-51-15,15>>^ Ó Senhor, dá palavras aos meus lábios, e a minha boca anunciará o teu louvor.

[[v19-51-16]]

^<<v19-51-16,16>>^ Não te deleitas em sacrifícios nem te agradas em holocaustos, se não eu os traria.

[[v19-51-17]]

^<<v19-51-17,17>>^ Os sacrifícios que agradam a Deus são um espírito quebrantado; um coração quebrantado e contrito, ó Deus, não desprezarás.

[[v19-51-18]]

^<<v19-51-18,18>>^ Por tua boa vontade faze Sião prosperar; ergue os muros de Jerusalém.

[[v19-51-19]]

^<<v19-51-19,19>>^ Então te agradarás dos sacrifícios sinceros, das ofertas queimadas e dos holocaustos; e novilhos serão oferecidos sobre o teu altar.

'''

xref:019-salmos/019-salmos-050.adoc#v19-50-0[&#60; Capítulo Anterior] | <<v19-51-0,Topo>> | xref:019-salmos/019-salmos-052.adoc#v19-52-0[Próximo Capítulo &#62;]