include::./index.adoc[]

[[v19-48-0]]
=== Salmos, 48
// nvi ?, NVI - Nova Versão Internacional

[[v19-48-1]]

^<<v19-48-1,1>>^ Grande é o Senhor, e digno de todo louvor na cidade do nosso Deus.

[[v19-48-2]]

^<<v19-48-2,2>>^ Seu santo monte, belo e majestoso, é a alegria da terra toda. Como as alturas do Zafom é o monte Sião, a cidade do grande Rei.

[[v19-48-3]]

^<<v19-48-3,3>>^ Nas suas cidadelas Deus se revela como sua proteção.

[[v19-48-4]]

^<<v19-48-4,4>>^ Vejam! Os reis somaram forças, e juntos avançaram contra ela.

[[v19-48-5]]

^<<v19-48-5,5>>^ Quando a viram, ficaram atônitos, fugiram aterrorizados.

[[v19-48-6]]

^<<v19-48-6,6>>^ Ali mesmo o pavor os dominou; contorceram-se como a mulher no parto.

[[v19-48-7]]

^<<v19-48-7,7>>^ Foste como o vento oriental quando destruiu os navios de Társis.

[[v19-48-8]]

^<<v19-48-8,8>>^ Como já temos ouvido, agora também temos visto na cidade do Senhor dos Exércitos, na cidade de nosso Deus: Deus a preserva firme para sempre. Pausa

[[v19-48-9]]

^<<v19-48-9,9>>^ No teu templo, ó Deus, meditamos em teu amor leal.

[[v19-48-10]]

^<<v19-48-10,10>>^ Como o teu nome, ó Deus, o teu louvor alcança os confins da terra; a tua mão direita está cheia de justiça.

[[v19-48-11]]

^<<v19-48-11,11>>^ O monte Sião se alegra, as cidades de Judá exultam por causa das tuas decisões justas.

[[v19-48-12]]

^<<v19-48-12,12>>^ Percorram Sião, contornando-a, contem as suas torres,

[[v19-48-13]]

^<<v19-48-13,13>>^ observem bem as suas muralhas, examinem as suas cidadelas, para que vocês falem à próxima geração

[[v19-48-14]]

^<<v19-48-14,14>>^ que este Deus é o nosso Deus para todo o sempre; ele será o nosso guia até o fim.

'''

xref:019-salmos/019-salmos-047.adoc#v19-47-0[&#60; Capítulo Anterior] | <<v19-48-0,Topo>> | xref:019-salmos/019-salmos-049.adoc#v19-49-0[Próximo Capítulo &#62;]