include::./index.adoc[]

[[v19-64-0]]
=== Salmos, 64
// nvi ?, NVI - Nova Versão Internacional

[[v19-64-1]]

^<<v19-64-1,1>>^ Ouve-me, ó Deus, quando faço a minha queixa; protege a minha vida do inimigo ameaçador.

[[v19-64-2]]

^<<v19-64-2,2>>^ Defende-me da conspiração dos ímpios e da ruidosa multidão de malfeitores.

[[v19-64-3]]

^<<v19-64-3,3>>^ Eles afiam a língua como espada e apontam como flechas, palavras envenenadas.

[[v19-64-4]]

^<<v19-64-4,4>>^ De onde estão emboscados atiram no homem íntegro; atiram de surpresa, sem qualquer temor.

[[v19-64-5]]

^<<v19-64-5,5>>^ Animam-se uns aos outros com planos malignos, combinam como ocultar as suas armadilhas, e dizem: "Quem as verá? "

[[v19-64-6]]

^<<v19-64-6,6>>^ Tramam a injustiça e dizem: "Fizemos um plano perfeito! " A mente e o coração de cada um deles o encobrem!

[[v19-64-7]]

^<<v19-64-7,7>>^ Mas Deus atirará neles suas flechas; repentinamente serão atingidos.

[[v19-64-8]]

^<<v19-64-8,8>>^ Pelas próprias palavras farão cair uns aos outros; menearão a cabeça e zombarão deles todos os que os virem.

[[v19-64-9]]

^<<v19-64-9,9>>^ Todos os homens temerão, proclamarão as obras de Deus, refletindo no que ele fez.

[[v19-64-10]]

^<<v19-64-10,10>>^ Alegrem-se os justos no Senhor e nele busquem refúgio; congratulem-se todos os retos de coração!

'''

xref:019-salmos/019-salmos-063.adoc#v19-63-0[&#60; Capítulo Anterior] | <<v19-64-0,Topo>> | xref:019-salmos/019-salmos-065.adoc#v19-65-0[Próximo Capítulo &#62;]