include::./index.adoc[]

[[v19-38-0]]
=== Salmos, 38
// nvi ?, NVI - Nova Versão Internacional

[[v19-38-1]]

^<<v19-38-1,1>>^ Senhor, não me repreendas no teu furor nem me disciplines na tua ira.

[[v19-38-2]]

^<<v19-38-2,2>>^ Pois as tuas flechas me atravessaram, e a tua mão me atingiu.

[[v19-38-3]]

^<<v19-38-3,3>>^ Por causa de tua ira todo o meu corpo está doente; não há saúde nos meus ossos por causa do meu pecado.

[[v19-38-4]]

^<<v19-38-4,4>>^ As minhas culpas me afogam; são como um fardo pesado e insuportável.

[[v19-38-5]]

^<<v19-38-5,5>>^ Minhas feridas cheiram mal e supuram por causa da minha insensatez.

[[v19-38-6]]

^<<v19-38-6,6>>^ Estou encurvado e muitíssimo abatido; o dia todo saio vagueando e pranteando.

[[v19-38-7]]

^<<v19-38-7,7>>^ Estou ardendo em febre; todo o meu corpo está doente.

[[v19-38-8]]

^<<v19-38-8,8>>^ Sinto-me muito fraco e totalmente esmagado; meu coração geme de angústia.

[[v19-38-9]]

^<<v19-38-9,9>>^ Senhor, diante de ti estão todos os meus anseios; o meu suspiro não te é oculto.

[[v19-38-10]]

^<<v19-38-10,10>>^ Meu coração palpita, as forças me faltam; até a luz dos meus olhos se foi.

[[v19-38-11]]

^<<v19-38-11,11>>^ Meus amigos e companheiros me evitam por causa da doença que me aflige; ficam longe de mim os meus vizinhos.

[[v19-38-12]]

^<<v19-38-12,12>>^ Os que desejam matar-me preparam armadilhas, os que me querem prejudicar anunciam a minha ruína; passam o dia planejando traição.

[[v19-38-13]]

^<<v19-38-13,13>>^ Como um surdo, não ouço, como um mudo, não abro a boca.

[[v19-38-14]]

^<<v19-38-14,14>>^ Fiz-me como quem não ouve, e em cuja boca não há resposta.

[[v19-38-15]]

^<<v19-38-15,15>>^ Senhor, em ti espero; Tu me responderás, ó Senhor meu Deus!

[[v19-38-16]]

^<<v19-38-16,16>>^ Pois eu disse: "Não permitas que eles se divirtam à minha custa, nem triunfem sobre mim quando eu tropeçar".

[[v19-38-17]]

^<<v19-38-17,17>>^ Estou a ponto de cair, e a minha dor está sempre comigo.

[[v19-38-18]]

^<<v19-38-18,18>>^ Confesso a minha culpa; em angústia estou por causa do meu pecado.

[[v19-38-19]]

^<<v19-38-19,19>>^ Meus inimigos, porém, são muitos e poderosos; é grande o número dos que me odeiam sem motivo.

[[v19-38-20]]

^<<v19-38-20,20>>^ Os que me retribuem o bem com o mal caluniam-me porque é o bem que procuro.

[[v19-38-21]]

^<<v19-38-21,21>>^ Senhor, não me abandones! Não fiques longe de mim, ó meu Deus!

[[v19-38-22]]

^<<v19-38-22,22>>^ Apressa-te a ajudar-me, Senhor, meu Salvador!

'''

xref:019-salmos/019-salmos-037.adoc#v19-37-0[&#60; Capítulo Anterior] | <<v19-38-0,Topo>> | xref:019-salmos/019-salmos-039.adoc#v19-39-0[Próximo Capítulo &#62;]