include::./index.adoc[]

[[v19-62-0]]
=== Salmos, 62
// nvi ?, NVI - Nova Versão Internacional

[[v19-62-1]]

^<<v19-62-1,1>>^ A minha alma descansa somente em Deus; dele vem a minha salvação.

[[v19-62-2]]

^<<v19-62-2,2>>^ Somente ele é a rocha que me salva; ele é a minha torre segura! Jamais serei abalado!

[[v19-62-3]]

^<<v19-62-3,3>>^ Até quando todos vocês atacarão um homem, que está como um muro inclinado, como uma cerca prestes a cair?

[[v19-62-4]]

^<<v19-62-4,4>>^ Todo o propósito deles é derrubá-lo de sua posição elevada; eles se deliciam com mentiras. Com a boca abençoam, mas no íntimo amaldiçoam. Pausa

[[v19-62-5]]

^<<v19-62-5,5>>^ Descanse somente em Deus, ó minha alma; dele vem a minha esperança.

[[v19-62-6]]

^<<v19-62-6,6>>^ Somente ele é a rocha que me salva; ele é a minha torre alta! Não serei abalado!

[[v19-62-7]]

^<<v19-62-7,7>>^ A minha salvação e a minha honra de Deus dependem; ele é a minha rocha firme, o meu refúgio.

[[v19-62-8]]

^<<v19-62-8,8>>^ Confiem nele em todos os momentos, ó povo; derramem diante dele o coração, pois ele é o nosso refúgio. Pausa

[[v19-62-9]]

^<<v19-62-9,9>>^ Os homens de origem humilde não passam de um sopro, os de origem importante não passam de mentira; pesados na balança, juntos não chegam ao peso de um sopro.

[[v19-62-10]]

^<<v19-62-10,10>>^ Não confiem na extorsão, nem ponham a esperança em bens roubados; se as suas riquezas aumentam, não ponham nelas o coração.

[[v19-62-11]]

^<<v19-62-11,11>>^ Uma vez Deus falou, duas vezes eu ouvi, que o poder pertence a Deus.

[[v19-62-12]]

^<<v19-62-12,12>>^ Contigo também, Senhor, está a fidelidade. É certo que retribuirás a cada um conforme o seu procedimento.

'''

xref:019-salmos/019-salmos-061.adoc#v19-61-0[&#60; Capítulo Anterior] | <<v19-62-0,Topo>> | xref:019-salmos/019-salmos-063.adoc#v19-63-0[Próximo Capítulo &#62;]