include::./index.adoc[]

[[v19-142-0]]
=== Salmos, 142
// nvi ?, NVI - Nova Versão Internacional

[[v19-142-1]]

^<<v19-142-1,1>>^ Em alta voz clamo ao Senhor; elevo a minha voz ao Senhor, suplicando misericórdia.

[[v19-142-2]]

^<<v19-142-2,2>>^ Derramo diante dele o meu lamento; a ele apresento a minha angústia.

[[v19-142-3]]

^<<v19-142-3,3>>^ Quando o meu espírito se desanima, és tu quem conhece o caminho que devo seguir. Na vereda por onde ando esconderam uma armadilha contra mim.

[[v19-142-4]]

^<<v19-142-4,4>>^ Olha para a minha direita e vê; ninguém se preocupa comigo. Não tenho abrigo seguro; ninguém se importa com a minha vida.

[[v19-142-5]]

^<<v19-142-5,5>>^ Clamo a ti, Senhor, e digo: "Tu és o meu refúgio; és tudo o que tenho que na terra dos viventes.

[[v19-142-6]]

^<<v19-142-6,6>>^ Dá atenção ao meu clamor, pois estou muito abatido; livra-me dos que me perseguem, pois são mais fortes do que eu.

[[v19-142-7]]

^<<v19-142-7,7>>^ Liberta-me da prisão, e renderei graças ao teu nome. Então os justos se reunirão à minha volta por causa da tua bondade para comigo".

'''

xref:019-salmos/019-salmos-141.adoc#v19-141-0[&#60; Capítulo Anterior] | <<v19-142-0,Topo>> | xref:019-salmos/019-salmos-143.adoc#v19-143-0[Próximo Capítulo &#62;]