include::./index.adoc[]

[[v19-10-0]]
=== Salmos, 10
// nvi ?, NVI - Nova Versão Internacional

[[v19-10-1]]

^<<v19-10-1,1>>^ Senhor, por que estás tão longe? Por que te escondes em tempos de angústia?

[[v19-10-2]]

^<<v19-10-2,2>>^ Em sua arrogância o ímpio persegue o pobre, que é apanhado em suas tramas.

[[v19-10-3]]

^<<v19-10-3,3>>^ Ele se gaba de sua própria cobiça e, em sua ganância, amaldiçoa e insulta o Senhor.

[[v19-10-4]]

^<<v19-10-4,4>>^ Em sua presunção o ímpio não o busca; não há lugar para Deus em nenhum dos seus planos.

[[v19-10-5]]

^<<v19-10-5,5>>^ Os seus caminhos prosperam sempre; tão acima da sua compreensão estão as tuas leis que ele faz pouco caso de todos os seus adversários,

[[v19-10-6]]

^<<v19-10-6,6>>^ pensando consigo mesmo: "Nada me abalará! Desgraça alguma me atingirá, nem a mim nem aos meus descendentes".

[[v19-10-7]]

^<<v19-10-7,7>>^ Sua boca está cheia de maldições, mentiras e ameaças; violência e maldade estão em sua língua.

[[v19-10-8]]

^<<v19-10-8,8>>^ Fica à espreita perto dos povoados; em emboscadas mata os inocentes, procurando às escondidas as suas vítimas.

[[v19-10-9]]

^<<v19-10-9,9>>^ Fica à espreita como o leão escondido; fica à espreita para apanhar o necessitado; apanha o necessitado e o arrasta para a sua rede.

[[v19-10-10]]

^<<v19-10-10,10>>^ Agachado, fica de tocaia; as suas vítimas caem em seu poder.

[[v19-10-11]]

^<<v19-10-11,11>>^ Pensa consigo mesmo: "Deus se esqueceu; escondeu o rosto e nunca verá isto".

[[v19-10-12]]

^<<v19-10-12,12>>^ Levanta-te, Senhor! Ergue a tua mão, ó Deus! Não te esqueças dos necessitados.

[[v19-10-13]]

^<<v19-10-13,13>>^ Por que o ímpio insulta a Deus, dizendo no seu íntimo: "De nada me pedirás contas! "?

[[v19-10-14]]

^<<v19-10-14,14>>^ Mas tu enxergas o sofrimento e a dor; observa-os para tomá-los em tuas mãos. A vítima deles entrega-se a ti; tu és o protetor do órfão.

[[v19-10-15]]

^<<v19-10-15,15>>^ Quebra o braço do ímpio e do perverso, pede contas de sua impiedade até que dela nada mais se ache.

[[v19-10-16]]

^<<v19-10-16,16>>^ O Senhor é rei para todo o sempre; da sua terra desapareceram os outros povos.

[[v19-10-17]]

^<<v19-10-17,17>>^ Tu, Senhor, ouves a súplica dos necessitados; tu os reanimas e atendes ao seu clamor.

[[v19-10-18]]

^<<v19-10-18,18>>^ Defendes o órfão e o oprimido, a fim de que o homem, que é pó, já não cause terror.

'''

xref:019-salmos/019-salmos-009.adoc#v19-9-0[&#60; Capítulo Anterior] | <<v19-10-0,Topo>> | xref:019-salmos/019-salmos-011.adoc#v19-11-0[Próximo Capítulo &#62;]