include::./index.adoc[]

[[v19-144-0]]
=== Salmos, 144
// nvi ?, NVI - Nova Versão Internacional

[[v19-144-1]]

^<<v19-144-1,1>>^ Bendito seja o Senhor, a minha Rocha, que treina as minhas mãos para a guerra e os meus dedos para a batalha.

[[v19-144-2]]

^<<v19-144-2,2>>^ Ele é o meu aliado fiel, a minha fortaleza, a minha torre de proteção e o meu libertador, é o meu escudo, aquele em quem me refugio. Ele subjuga a mim os povos.

[[v19-144-3]]

^<<v19-144-3,3>>^ Senhor, que é o homem para que te importes com ele, ou o filho do homem para que por ele te interesses?

[[v19-144-4]]

^<<v19-144-4,4>>^ O homem é como um sopro; seus dias são como uma sombra passageira.

[[v19-144-5]]

^<<v19-144-5,5>>^ Estende, Senhor, os teus céus e desce; toca os montes para que fumeguem.

[[v19-144-6]]

^<<v19-144-6,6>>^ Envia relâmpagos e dispersa os inimigos; atira as tuas flechas e faze-os debandar.

[[v19-144-7]]

^<<v19-144-7,7>>^ Das alturas, estende a tua mão e liberta-me; salva-me da imensidão das águas, das mãos desses estrangeiros,

[[v19-144-8]]

^<<v19-144-8,8>>^ que têm lábios mentirosos e com a mão direita erguida juram falsamente.

[[v19-144-9]]

^<<v19-144-9,9>>^ Cantarei uma nova canção a ti, ó Deus; tocarei para ti a lira de dez cordas,

[[v19-144-10]]

^<<v19-144-10,10>>^ para aquele que dá vitória aos reis, que livra o seu servo Davi da espada mortal.

[[v19-144-11]]

^<<v19-144-11,11>>^ Dá-me libertação; salva-me das mãos dos estrangeiros, que têm lábios mentirosos e que, com a mão direita erguida, juram falsamente.

[[v19-144-12]]

^<<v19-144-12,12>>^ Então, na juventude, os nossos filhos serão como plantas viçosas, e as nossas filhas, como colunas esculpidas para ornar um palácio.

[[v19-144-13]]

^<<v19-144-13,13>>^ Os nossos celeiros estarão cheios das mais variadas provisões. Os nossos rebanhos se multiplicarão aos milhares, às dezenas de milhares em nossos campos;

[[v19-144-14]]

^<<v19-144-14,14>>^ o nosso gado dará suas crias; não haverá praga alguma nem aborto. Não haverá gritos de aflição em nossas ruas.

[[v19-144-15]]

^<<v19-144-15,15>>^ Como é feliz o povo assim abençoado! Como é feliz o povo cujo Deus é o Senhor!

'''

xref:019-salmos/019-salmos-143.adoc#v19-143-0[&#60; Capítulo Anterior] | <<v19-144-0,Topo>> | xref:019-salmos/019-salmos-145.adoc#v19-145-0[Próximo Capítulo &#62;]