include::./index.adoc[]

[[v19-47-0]]
=== Salmos, 47
// nvi ?, NVI - Nova Versão Internacional

[[v19-47-1]]

^<<v19-47-1,1>>^ Batam palmas, vocês, todos os povos; aclamem a Deus com cantos de alegria.

[[v19-47-2]]

^<<v19-47-2,2>>^ Pois o Senhor Altíssimo é temível, é o grande Rei sobre toda a terra!

[[v19-47-3]]

^<<v19-47-3,3>>^ Ele subjugou as nações ao nosso poder, os povos colocou debaixo de nossos pés,

[[v19-47-4]]

^<<v19-47-4,4>>^ e escolheu para nós a nossa herança, o orgulho de Jacó, a quem amou. Pausa

[[v19-47-5]]

^<<v19-47-5,5>>^ Deus subiu em meio a gritos de alegria; o Senhor, em meio ao som de trombetas.

[[v19-47-6]]

^<<v19-47-6,6>>^ Ofereçam música a Deus, cantem louvores! Ofereçam música ao nosso Rei, cantem louvores!

[[v19-47-7]]

^<<v19-47-7,7>>^ Pois Deus é o rei de toda a terra; cantem louvores com harmonia e arte.

[[v19-47-8]]

^<<v19-47-8,8>>^ Deus reina sobre as nações; Deus está assentado em seu santo trono.

[[v19-47-9]]

^<<v19-47-9,9>>^ Os soberanos das nações se juntam ao povo do Deus de Abraão, pois os governantes da terra pertencem a Deus; ele é soberanamente exaltado.

'''

xref:019-salmos/019-salmos-046.adoc#v19-46-0[&#60; Capítulo Anterior] | <<v19-47-0,Topo>> | xref:019-salmos/019-salmos-048.adoc#v19-48-0[Próximo Capítulo &#62;]