include::./index.adoc[]

[[v19-30-0]]
=== Salmos, 30
// nvi ?, NVI - Nova Versão Internacional

[[v19-30-1]]

^<<v19-30-1,1>>^ Eu te exaltarei, Senhor, pois tu me reergueste e não deixaste que os meus inimigos se divertissem à minha custa.

[[v19-30-2]]

^<<v19-30-2,2>>^ Senhor meu Deus, a ti clamei por socorro, e tu me curaste.

[[v19-30-3]]

^<<v19-30-3,3>>^ Senhor, tiraste-me da sepultura; prestes a descer à cova, devolveste-me à vida.

[[v19-30-4]]

^<<v19-30-4,4>>^ Cantem louvores ao Senhor, vocês, os seus fiéis; louvem o seu santo nome.

[[v19-30-5]]

^<<v19-30-5,5>>^ Pois a sua ira só dura um instante, mas o seu favor dura a vida toda; o choro pode persistir uma noite, mas de manhã irrompe a alegria.

[[v19-30-6]]

^<<v19-30-6,6>>^ Quando me senti seguro, disse: "Jamais serei abalado! "

[[v19-30-7]]

^<<v19-30-7,7>>^ Senhor, com o teu favor, deste-me firmeza e estabilidade; mas, quando escondeste a tua face, fiquei aterrorizado.

[[v19-30-8]]

^<<v19-30-8,8>>^ A ti, Senhor, clamei, ao Senhor pedi misericórdia:

[[v19-30-9]]

^<<v19-30-9,9>>^ "Se eu morrer, se eu descer à cova, que vantagem haverá? Acaso o pó te louvará? Proclamará a tua fidelidade?

[[v19-30-10]]

^<<v19-30-10,10>>^ Ouve, Senhor, e tem misericórdia de mim; Senhor, sê tu o meu auxílio".

[[v19-30-11]]

^<<v19-30-11,11>>^ Mudaste o meu pranto em dança, a minha veste de lamento em veste de alegria,

[[v19-30-12]]

^<<v19-30-12,12>>^ para que o meu coração cante louvores a ti e não se cale. Senhor, meu Deus, eu te darei graças para sempre.

'''

xref:019-salmos/019-salmos-029.adoc#v19-29-0[&#60; Capítulo Anterior] | <<v19-30-0,Topo>> | xref:019-salmos/019-salmos-031.adoc#v19-31-0[Próximo Capítulo &#62;]