include::./index.adoc[]

[[v19-52-0]]
=== Salmos, 52
// nvi ?, NVI - Nova Versão Internacional

[[v19-52-1]]

^<<v19-52-1,1>>^ Por que você se vangloria do mal e de ultrajar a Deus continuamente?, ó homem poderoso.

[[v19-52-2]]

^<<v19-52-2,2>>^ Sua língua trama destruição; é como navalha afiada, cheia de engano.

[[v19-52-3]]

^<<v19-52-3,3>>^ Você prefere o mal ao bem, a falsidade, em lugar da verdade. Pausa

[[v19-52-4]]

^<<v19-52-4,4>>^ Você ama toda palavra maldosa, ó língua mentirosa!

[[v19-52-5]]

^<<v19-52-5,5>>^ Saiba que Deus o arruinará para sempre: Ele o agarrará e o arrancará da sua tenda; ele o desarraigará da terra dos vivos. Pausa

[[v19-52-6]]

^<<v19-52-6,6>>^ Os justos verão isso e temerão; rirão dele, dizendo:

[[v19-52-7]]

^<<v19-52-7,7>>^ "Veja só o homem que rejeitou a Deus como refúgio; confiou em sua grande riqueza e buscou refúgio em sua maldade! "

[[v19-52-8]]

^<<v19-52-8,8>>^ Mas eu sou como uma oliveira que floresce na casa de Deus; confio no amor de Deus para todo o sempre.

[[v19-52-9]]

^<<v19-52-9,9>>^ Para sempre te louvarei pelo que fizeste; na presença dos teus fiéis proclamarei o teu nome, porque tu és bom.

'''

xref:019-salmos/019-salmos-051.adoc#v19-51-0[&#60; Capítulo Anterior] | <<v19-52-0,Topo>> | xref:019-salmos/019-salmos-053.adoc#v19-53-0[Próximo Capítulo &#62;]