include::./index.adoc[]

[[v19-140-0]]
=== Salmos, 140
// nvi ?, NVI - Nova Versão Internacional

[[v19-140-1]]

^<<v19-140-1,1>>^ Livra-me, Senhor, dos maus; protege-me dos violentos,

[[v19-140-2]]

^<<v19-140-2,2>>^ que no coração tramam planos perversos e estão sempre provocando guerra.

[[v19-140-3]]

^<<v19-140-3,3>>^ Afiam a língua como a da serpente; veneno de víbora está em seus lábios. Pausa

[[v19-140-4]]

^<<v19-140-4,4>>^ Protege-me, Senhor, das mãos dos ímpios; protege-me dos violentos, que pretendem fazer-me tropeçar.

[[v19-140-5]]

^<<v19-140-5,5>>^ Homens arrogantes prepararam armadilhas contra mim, perversos estenderam as suas redes; no meu caminho armaram ciladas contra mim. Pausa

[[v19-140-6]]

^<<v19-140-6,6>>^ Eu declaro ao Senhor: "Tu és o meu Deus". Ouve, Senhor, a minha súplica!

[[v19-140-7]]

^<<v19-140-7,7>>^ Ó Soberano Senhor, meu salvador poderoso, tu me proteges a cabeça no dia da batalha;

[[v19-140-8]]

^<<v19-140-8,8>>^ não atendas os desejos dos ímpios, Senhor! Não permitas que os planos deles tenham sucesso, para que não se orgulhem. Pausa

[[v19-140-9]]

^<<v19-140-9,9>>^ Recaia sobre a cabeça dos que me cercam a maldade que os seus lábios proferiram.

[[v19-140-10]]

^<<v19-140-10,10>>^ Caiam brasas sobre eles, e sejam lançados ao fogo, em covas das quais jamais possam sair.

[[v19-140-11]]

^<<v19-140-11,11>>^ Que os difamadores não se estabeleçam na terra, e a desgraça persiga os violentos até à morte.

[[v19-140-12]]

^<<v19-140-12,12>>^ Sei que o Senhor defenderá a causa do necessitado e fará justiça aos pobres.

[[v19-140-13]]

^<<v19-140-13,13>>^ Com certeza os justos darão graças ao teu nome, e os homens íntegros viverão na tua presença.

'''

xref:019-salmos/019-salmos-139.adoc#v19-139-0[&#60; Capítulo Anterior] | <<v19-140-0,Topo>> | xref:019-salmos/019-salmos-141.adoc#v19-141-0[Próximo Capítulo &#62;]