include::./index.adoc[]

[[v19-145-0]]
=== Salmos, 145
// nvi ?, NVI - Nova Versão Internacional

[[v19-145-1]]

^<<v19-145-1,1>>^ Eu te exaltarei, meu Deus e meu rei; bendirei o teu nome para todo o sempre!

[[v19-145-2]]

^<<v19-145-2,2>>^ Todos os dias te bendirei e louvarei o teu nome para todo o sempre!

[[v19-145-3]]

^<<v19-145-3,3>>^ Grande é o Senhor e digno de ser louvado; sua grandeza não tem limites.

[[v19-145-4]]

^<<v19-145-4,4>>^ Uma geração contará à outra a grandiosidade dos teus feitos; eles anunciarão os teus atos poderosos.

[[v19-145-5]]

^<<v19-145-5,5>>^ Proclamarão o glorioso esplendor da tua majestade, e meditarei nas maravilhas que fazes.

[[v19-145-6]]

^<<v19-145-6,6>>^ Anunciarão o poder dos teus feitos temíveis, e eu falarei das tuas grandes obras.

[[v19-145-7]]

^<<v19-145-7,7>>^ Comemorarão a tua imensa bondade e celebrarão a tua justiça.

[[v19-145-8]]

^<<v19-145-8,8>>^ O Senhor é misericordioso e compassivo, paciente e transbordante de amor.

[[v19-145-9]]

^<<v19-145-9,9>>^ O Senhor é bom para todos; a sua compaixão alcança todas as suas criaturas.

[[v19-145-10]]

^<<v19-145-10,10>>^ Rendam-te graças todas as tuas criaturas, Senhor; e os teus fiéis te bendigam.

[[v19-145-11]]

^<<v19-145-11,11>>^ Eles anunciarão a glória do teu reino e falarão do teu poder,

[[v19-145-12]]

^<<v19-145-12,12>>^ para que todos saibam dos teus feitos poderosos e do glorioso esplendor do teu reino.

[[v19-145-13]]

^<<v19-145-13,13>>^ O teu reino é reino eterno, e o teu domínio permanece de geração em geração. O Senhor é fiel em todas as suas promessas e é bondoso em tudo o que faz.

[[v19-145-14]]

^<<v19-145-14,14>>^ O Senhor ampara todos os que caem e levanta todos os que estão prostrados.

[[v19-145-15]]

^<<v19-145-15,15>>^ Os olhos de todos estão voltados para ti, e tu lhes dás o alimento no devido tempo.

[[v19-145-16]]

^<<v19-145-16,16>>^ Abres a tua mão e satisfazes os desejos de todos os seres vivos.

[[v19-145-17]]

^<<v19-145-17,17>>^ O Senhor é justo em todos os seus caminhos e é bondoso em tudo o que faz.

[[v19-145-18]]

^<<v19-145-18,18>>^ O Senhor está perto de todos os que o invocam, de todos os que o invocam com sinceridade.

[[v19-145-19]]

^<<v19-145-19,19>>^ Realiza os desejos daqueles que o temem; ouve-os gritar por socorro e os salva.

[[v19-145-20]]

^<<v19-145-20,20>>^ O Senhor cuida de todos os que o amam, mas a todos os ímpios destruirá.

[[v19-145-21]]

^<<v19-145-21,21>>^ Com meus lábios louvarei ao Senhor. Que todo ser vivo bendiga o seu santo nome para todo o sempre!

'''

xref:019-salmos/019-salmos-144.adoc#v19-144-0[&#60; Capítulo Anterior] | <<v19-145-0,Topo>> | xref:019-salmos/019-salmos-146.adoc#v19-146-0[Próximo Capítulo &#62;]