include::./index.adoc[]

[[v19-28-0]]
=== Salmos, 28
// nvi ?, NVI - Nova Versão Internacional

[[v19-28-1]]

^<<v19-28-1,1>>^ A ti eu clamo, Senhor, minha Rocha; não fiques indiferente para comigo. Se permaneceres calado, serei como os que descem à cova.

[[v19-28-2]]

^<<v19-28-2,2>>^ Ouve as minhas súplicas quando clamo a ti por socorro, quando ergo as mãos para o teu Lugar Santíssimo.

[[v19-28-3]]

^<<v19-28-3,3>>^ Não me dês o castigo reservado para os ímpios e para os malfeitores, que falam como amigos com o próximo, mas abrigam maldade no coração.

[[v19-28-4]]

^<<v19-28-4,4>>^ Retribui-lhes conforme os seus atos, conforme as suas más obras; retribui-lhes pelo que as suas mãos têm feito e dá-lhes o que merecem.

[[v19-28-5]]

^<<v19-28-5,5>>^ Visto que não consideram os feitos do Senhor, nem as obras de suas mãos, ele os arrasará e jamais os deixará reerguer-se.

[[v19-28-6]]

^<<v19-28-6,6>>^ Bendito seja o Senhor, pois ouviu as minhas súplicas.

[[v19-28-7]]

^<<v19-28-7,7>>^ O Senhor é a minha força e o meu escudo; nele o meu coração confia, e dele recebo ajuda. Meu coração exulta de alegria, e com o meu cântico lhe darei graças.

[[v19-28-8]]

^<<v19-28-8,8>>^ O Senhor é a força do seu povo, a fortaleza que salva o seu ungido.

[[v19-28-9]]

^<<v19-28-9,9>>^ Salva o teu povo e abençoa a tua herança! Cuida deles como o seu pastor e conduze-os para sempre.

'''

xref:019-salmos/019-salmos-027.adoc#v19-27-0[&#60; Capítulo Anterior] | <<v19-28-0,Topo>> | xref:019-salmos/019-salmos-029.adoc#v19-29-0[Próximo Capítulo &#62;]