include::./index.adoc[]

[[v19-116-0]]
=== Salmos, 116
// nvi ?, NVI - Nova Versão Internacional

[[v19-116-1]]

^<<v19-116-1,1>>^ Eu amo o Senhor, porque ele me ouviu quando lhe fiz a minha súplica.

[[v19-116-2]]

^<<v19-116-2,2>>^ Ele inclinou os seus ouvidos para mim; eu o invocarei toda a minha vida.

[[v19-116-3]]

^<<v19-116-3,3>>^ As cordas da morte me envolveram, as angústias do Sheol vieram sobre mim; aflição e tristeza me dominaram.

[[v19-116-4]]

^<<v19-116-4,4>>^ Então clamei pelo nome do Senhor: "Livra-me, Senhor! "

[[v19-116-5]]

^<<v19-116-5,5>>^ O Senhor é misericordioso e justo; o nosso Deus é compassivo.

[[v19-116-6]]

^<<v19-116-6,6>>^ O Senhor protege os simples; quando eu já estava sem forças, ele me salvou.

[[v19-116-7]]

^<<v19-116-7,7>>^ Retorne ao seu descanso, ó minha alma, porque o Senhor tem sido bom para você!

[[v19-116-8]]

^<<v19-116-8,8>>^ Pois tu me livraste da morte, os meus olhos, das lágrimas e os meus pés, de tropeçar,

[[v19-116-9]]

^<<v19-116-9,9>>^ para que eu pudesse andar diante do Senhor na terra dos viventes.

[[v19-116-10]]

^<<v19-116-10,10>>^ Eu cri, ainda que tenha dito: "Estou muito aflito".

[[v19-116-11]]

^<<v19-116-11,11>>^ Em pânico eu disse: "Ninguém merece confiança".

[[v19-116-12]]

^<<v19-116-12,12>>^ Como posso retribuir ao Senhor toda a sua bondade para comigo?

[[v19-116-13]]

^<<v19-116-13,13>>^ Erguerei o cálice da salvação e invocarei o nome do Senhor.

[[v19-116-14]]

^<<v19-116-14,14>>^ Cumprirei para com o Senhor os meus votos, na presença de todo o seu povo.

[[v19-116-15]]

^<<v19-116-15,15>>^ O Senhor vê com pesar a morte de seus fiéis.

[[v19-116-16]]

^<<v19-116-16,16>>^ Senhor, sou teu servo, Sim, sou teu servo, filho da tua serva; livraste-me das minhas correntes.

[[v19-116-17]]

^<<v19-116-17,17>>^ Oferecerei a ti um sacrifício de gratidão e invocarei o nome do Senhor.

[[v19-116-18]]

^<<v19-116-18,18>>^ Cumprirei para com o Senhor os meus votos, na presença de todo o seu povo,

[[v19-116-19]]

^<<v19-116-19,19>>^ nos pátios da casa do Senhor, no seu interior, ó Jerusalém! Aleluia!

'''

xref:019-salmos/019-salmos-115.adoc#v19-115-0[&#60; Capítulo Anterior] | <<v19-116-0,Topo>> | xref:019-salmos/019-salmos-117.adoc#v19-117-0[Próximo Capítulo &#62;]