include::./index.adoc[]

[[v19-68-0]]
=== Salmos, 68
// nvi ?, NVI - Nova Versão Internacional

[[v19-68-1]]

^<<v19-68-1,1>>^ Que Deus se levante! Sejam espalhados os seus inimigos, fujam dele os seus adversários.

[[v19-68-2]]

^<<v19-68-2,2>>^ Que tu os dissipes assim como o vento leva a fumaça; Como a cera se derrete na presença do fogo, assim pereçam os ímpios na presença de Deus.

[[v19-68-3]]

^<<v19-68-3,3>>^ Alegrem-se, porém, os justos! Exultem diante de Deus! Regozijem-se com grande alegria!

[[v19-68-4]]

^<<v19-68-4,4>>^ Cantem a Deus, louvem o seu nome, exaltem aquele que cavalga sobre as nuvens; seu nome é Senhor! Exultem diante dele!

[[v19-68-5]]

^<<v19-68-5,5>>^ Pai para os órfãos e defensor das viúvas é Deus em sua santa habitação.

[[v19-68-6]]

^<<v19-68-6,6>>^ Deus dá um lar aos solitários, liberta os presos para a prosperidade, mas os rebeldes vivem em terra árida.

[[v19-68-7]]

^<<v19-68-7,7>>^ Quando saíste à frente do teu povo, ó Deus, quando marchaste pelo ermo, Pausa

[[v19-68-8]]

^<<v19-68-8,8>>^ a terra tremeu, o céu derramou chuva diante de Deus, o Deus do Sinai, diante de Deus, o Deus de Israel.

[[v19-68-9]]

^<<v19-68-9,9>>^ Deste chuvas generosas, ó Deus; refrescaste a tua herança exausta.

[[v19-68-10]]

^<<v19-68-10,10>>^ O teu povo nela se instalou, e da tua bondade, ó Deus, supriste os pobres.

[[v19-68-11]]

^<<v19-68-11,11>>^ O Senhor anunciou a palavra, e muitos mensageiros a proclamavam:

[[v19-68-12]]

^<<v19-68-12,12>>^ "Reis e exércitos fogem em debandada; a dona de casa reparte os despojos.

[[v19-68-13]]

^<<v19-68-13,13>>^ Mesmo quando vocês dormem entre as fogueiras do acampamento, as asas da minha pomba estão recobertas de prata, as suas penas, de ouro reluzente".

[[v19-68-14]]

^<<v19-68-14,14>>^ Quando o Todo-poderoso espalhou os reis, foi como neve no monte Zalmom.

[[v19-68-15]]

^<<v19-68-15,15>>^ Os montes de Basã são majestosos; escarpados são os montes de Basã.

[[v19-68-16]]

^<<v19-68-16,16>>^ Por que, ó montes escarpados, estão com inveja do monte que Deus escolheu para sua habitação, onde o próprio Senhor habitará para sempre?

[[v19-68-17]]

^<<v19-68-17,17>>^ Os carros de Deus são incontáveis, milhares de milhares; neles o Senhor veio do Sinai para o seu Lugar Santo.

[[v19-68-18]]

^<<v19-68-18,18>>^ Quando subiste em triunfo às alturas, levaste cativo muitos prisioneiros; recebeste homens como dádivas, até mesmo rebeldes, para estabeleceres morada, ó Senhor Deus.

[[v19-68-19]]

^<<v19-68-19,19>>^ Bendito seja o Senhor, Deus, nosso Salvador, que cada dia suporta as nossas cargas. Pausa

[[v19-68-20]]

^<<v19-68-20,20>>^ O nosso Deus é um Deus que salva; ele é o Soberano Senhor que nos livra da morte.

[[v19-68-21]]

^<<v19-68-21,21>>^ Certamente Deus esmagará a cabeça dos seus inimigos, o crânio cabeludo dos que persistem em seus pecados.

[[v19-68-22]]

^<<v19-68-22,22>>^ "Eu os trarei de Basã", diz o Senhor, "eu os trarei das profundezas do mar,

[[v19-68-23]]

^<<v19-68-23,23>>^ para que você encharque os pés no sangue dos inimigos, sangue do qual a língua dos cães terá a sua porção. "

[[v19-68-24]]

^<<v19-68-24,24>>^ Já se vê a tua marcha triunfal, ó Deus, a marcha do meu Deus e Rei adentrando o santuário.

[[v19-68-25]]

^<<v19-68-25,25>>^ À frente estão os cantores, depois os músicos; com eles vão as jovens tocando tamborins.

[[v19-68-26]]

^<<v19-68-26,26>>^ Bendigam a Deus na grande congregação! Bendigam o Senhor, descendentes de Israel!

[[v19-68-27]]

^<<v19-68-27,27>>^ Ali está a pequena tribo de Benjamim, a conduzi-los, os príncipes de Judá acompanhados de suas tropas, e os príncipes de Zebulom e Naftali.

[[v19-68-28]]

^<<v19-68-28,28>>^ A favor de vocês, manifeste Deus o seu poder! Mostra, ó Deus, o poder que já tens operado para conosco.

[[v19-68-29]]

^<<v19-68-29,29>>^ Por causa do teu templo em Jerusalém, reis te trarão presentes.

[[v19-68-30]]

^<<v19-68-30,30>>^ Repreende a fera entre os juncos, a manada de touros entre os bezerros das nações. Humilhados, tragam barras de prata. Espalha as nações que têm prazer na guerra.

[[v19-68-31]]

^<<v19-68-31,31>>^ Ricos tecidos venham do Egito; a Etiópia corra para Deus de mãos cheias.

[[v19-68-32]]

^<<v19-68-32,32>>^ Cantem a Deus, reinos da terra, louvem o Senhor, Pausa

[[v19-68-33]]

^<<v19-68-33,33>>^ àquele que cavalga os céus, os antigos céus. Escutem! Ele troveja com voz poderosa.

[[v19-68-34]]

^<<v19-68-34,34>>^ Proclamem o poder de Deus! Sua majestade está sobre Israel, seu poder está nas altas nuvens.

[[v19-68-35]]

^<<v19-68-35,35>>^ Tu és temível no teu santuário, ó Deus; é o Deus de Israel que dá poder e força ao seu povo. Bendito seja Deus!

'''

xref:019-salmos/019-salmos-067.adoc#v19-67-0[&#60; Capítulo Anterior] | <<v19-68-0,Topo>> | xref:019-salmos/019-salmos-069.adoc#v19-69-0[Próximo Capítulo &#62;]