include::./index.adoc[]

[[v19-106-0]]
=== Salmos, 106
// nvi ?, NVI - Nova Versão Internacional

[[v19-106-1]]

^<<v19-106-1,1>>^ Aleluia! Dêem graças ao Senhor porque ele é bom; o seu amor dura para sempre.

[[v19-106-2]]

^<<v19-106-2,2>>^ Quem poderá descrever os feitos poderosos do Senhor, ou declarar todo o louvor que lhe é devido?

[[v19-106-3]]

^<<v19-106-3,3>>^ Como são felizes os que perseveram na retidão, que sempre praticam a justiça!

[[v19-106-4]]

^<<v19-106-4,4>>^ Lembra-te de mim, Senhor, quando tratares com bondade o teu povo; vem em meu auxílio quando o salvares,

[[v19-106-5]]

^<<v19-106-5,5>>^ para que eu possa testemunhar o bem-estar dos teus escolhidos, alegrar-me com a alegria do teu povo, e louvar-te junto com a tua herança.

[[v19-106-6]]

^<<v19-106-6,6>>^ Pecamos como os nossos antepassados; fizemos o mal e fomos rebeldes.

[[v19-106-7]]

^<<v19-106-7,7>>^ No Egito, os nossos antepassados não deram atenção às tuas maravilhas; não se lembraram das muitas manifestações do teu amor leal e rebelaram-se junto ao mar, o mar Vermelho.

[[v19-106-8]]

^<<v19-106-8,8>>^ Contudo, ele os salvou por causa do seu nome, para manifestar o seu poder.

[[v19-106-9]]

^<<v19-106-9,9>>^ Repreendeu o mar Vermelho, e este secou; ele os conduziu pelas profundezas como por um deserto.

[[v19-106-10]]

^<<v19-106-10,10>>^ Salvou-os das mãos daqueles que os odiavam; das mãos dos inimigos os resgatou.

[[v19-106-11]]

^<<v19-106-11,11>>^ As águas cobriram os seus adversários; nenhum deles sobreviveu.

[[v19-106-12]]

^<<v19-106-12,12>>^ Então creram nas suas promessas e a ele cantaram louvores.

[[v19-106-13]]

^<<v19-106-13,13>>^ Mas logo se esqueceram do que ele tinha feito e não esperaram para saber o seu plano.

[[v19-106-14]]

^<<v19-106-14,14>>^ Dominados pela gula no deserto, puseram Deus à prova nas regiões áridas.

[[v19-106-15]]

^<<v19-106-15,15>>^ Deu-lhes o que pediram, mas mandou sobre eles uma doença terrível.

[[v19-106-16]]

^<<v19-106-16,16>>^ No acampamento tiveram inveja de Moisés e de Arão, daquele que fora consagrado ao Senhor.

[[v19-106-17]]

^<<v19-106-17,17>>^ A terra abriu-se, engoliu Data e sepultou o grupo de Abirão;

[[v19-106-18]]

^<<v19-106-18,18>>^ fogo surgiu entre os seus seguidores; as chamas consumiram os ímpios.

[[v19-106-19]]

^<<v19-106-19,19>>^ Em Horebe fizeram um bezerro, adoraram um ídolo de metal.

[[v19-106-20]]

^<<v19-106-20,20>>^ Trocaram a Glória deles pela imagem de um boi que come capim.

[[v19-106-21]]

^<<v19-106-21,21>>^ Esqueceram-se de Deus, seu Salvador, que fizera coisas grandiosas no Egito,

[[v19-106-22]]

^<<v19-106-22,22>>^ maravilhas na terra de Cam e feitos temíveis junto ao mar Vermelho.

[[v19-106-23]]

^<<v19-106-23,23>>^ Por isso, ele ameaçou destruí-los; mas Moisés, seu escolhido, intercedeu diante dele, para evitar que a sua ira os destruísse.

[[v19-106-24]]

^<<v19-106-24,24>>^ Também rejeitaram a terra desejável; não creram na promessa dele.

[[v19-106-25]]

^<<v19-106-25,25>>^ Queixaram-se em suas tendas e não obedeceram ao Senhor.

[[v19-106-26]]

^<<v19-106-26,26>>^ Assim, de mão levantada, ele jurou que os abateria no deserto

[[v19-106-27]]

^<<v19-106-27,27>>^ e dispersaria os seus descendentes entre as nações e os espalharia por outras terras.

[[v19-106-28]]

^<<v19-106-28,28>>^ Sujeitaram-se ao jugo de Baal-Peor e comeram sacrifícios oferecidos a ídolos mortos;

[[v19-106-29]]

^<<v19-106-29,29>>^ provocaram a ira do Senhor com os seus atos, e uma praga irrompeu no meio deles.

[[v19-106-30]]

^<<v19-106-30,30>>^ Mas Finéias se interpôs para executar o juízo, e a praga foi interrompida.

[[v19-106-31]]

^<<v19-106-31,31>>^ Isso lhe foi creditado como um ato de justiça que para sempre será lembrado, por todas as gerações.

[[v19-106-32]]

^<<v19-106-32,32>>^ Provocaram a ira de Deus junto às águas de Meribá; e, por causa deles, Moisés foi castigado;

[[v19-106-33]]

^<<v19-106-33,33>>^ rebelaram-se contra o Espírito de Deus, e Moisés falou sem refletir.

[[v19-106-34]]

^<<v19-106-34,34>>^ Eles não destruíram os povos, como o Senhor tinha ordenado,

[[v19-106-35]]

^<<v19-106-35,35>>^ em vez disso, misturaram-se com as nações e imitaram as suas práticas.

[[v19-106-36]]

^<<v19-106-36,36>>^ Prestaram culto aos seus ídolos, que se tornaram uma armadilha para eles.

[[v19-106-37]]

^<<v19-106-37,37>>^ Sacrificaram seus filhos e suas filhas aos demônios.

[[v19-106-38]]

^<<v19-106-38,38>>^ Derramaram sangue inocente, o sangue de seus filhos e filhas sacrificados aos ídolos de Canaã; e a terra foi profanada pelo sangue deles.

[[v19-106-39]]

^<<v19-106-39,39>>^ Tornaram-se impuros pelos seus atos; prostituíram-se por suas ações.

[[v19-106-40]]

^<<v19-106-40,40>>^ Por isso acendeu-se a ira do Senhor contra o seu povo e ele sentiu aversão por sua herança.

[[v19-106-41]]

^<<v19-106-41,41>>^ Entregou-os nas mãos das nações, e os seus adversários dominaram sobre eles.

[[v19-106-42]]

^<<v19-106-42,42>>^ Os seus inimigos os oprimiram e os subjugaram com o seu poder.

[[v19-106-43]]

^<<v19-106-43,43>>^ Ele os libertou muitas vezes, embora eles persistissem em seus planos de rebelião e afundassem em sua maldade.

[[v19-106-44]]

^<<v19-106-44,44>>^ Mas Deus atentou para o sofrimento deles quando ouviu o seu clamor.

[[v19-106-45]]

^<<v19-106-45,45>>^ Lembrou-se da sua aliança com eles, e arrependeu-se, por causa do seu imenso amor leal.

[[v19-106-46]]

^<<v19-106-46,46>>^ Fez com que os seus captores tivessem misericórdia deles.

[[v19-106-47]]

^<<v19-106-47,47>>^ Salva-nos, Senhor, nosso Deus! Ajunta-nos dentre as nações, para que demos graças ao teu santo nome e façamos do teu louvor a nossa glória.

[[v19-106-48]]

^<<v19-106-48,48>>^ Bendito seja o Senhor, o Deus de Israel, por toda a eternidade. Que todo o povo diga: "Amém! " Aleluia!

'''

xref:019-salmos/019-salmos-105.adoc#v19-105-0[&#60; Capítulo Anterior] | <<v19-106-0,Topo>> | xref:019-salmos/019-salmos-107.adoc#v19-107-0[Próximo Capítulo &#62;]