include::./index.adoc[]

[[v19-141-0]]
=== Salmos, 141
// nvi ?, NVI - Nova Versão Internacional

[[v19-141-1]]

^<<v19-141-1,1>>^ Clamo a ti, Senhor; vem depressa! Escuta a minha voz quando clamo a ti.

[[v19-141-2]]

^<<v19-141-2,2>>^ Seja a minha oração como incenso diante de ti, e o levantar das minhas mãos, como a oferta da tarde.

[[v19-141-3]]

^<<v19-141-3,3>>^ Coloca, Senhor, uma guarda à minha boca; vigia a porta de meus lábios.

[[v19-141-4]]

^<<v19-141-4,4>>^ Não permitas que o meu coração se volte para o mal, nem que eu me envolva em práticas perversas com os malfeitores. Que eu nunca participe dos seus banquetes!

[[v19-141-5]]

^<<v19-141-5,5>>^ Fira-me o justo com amor leal e me repreenda, mas não perfume a minha cabeça o óleo do ímpio, pois a minha oração é contra as práticas dos malfeitores.

[[v19-141-6]]

^<<v19-141-6,6>>^ Quando eles caírem nas mãos da Rocha, o juiz deles, ouvirão as minhas palavras com apreço.

[[v19-141-7]]

^<<v19-141-7,7>>^ Como a terra é arada e fendida, assim foram espalhados os seus ossos à entrada da sepultura.

[[v19-141-8]]

^<<v19-141-8,8>>^ Mas os meus olhos estão fixos em ti, ó Soberano Senhor; em ti me refugio; não me entregues à morte.

[[v19-141-9]]

^<<v19-141-9,9>>^ Guarda-me das armadilhas que prepararam contra mim, das ciladas dos que praticam o mal.

[[v19-141-10]]

^<<v19-141-10,10>>^ Caiam os ímpios em sua própria rede, enquanto eu escapo ileso.

'''

xref:019-salmos/019-salmos-140.adoc#v19-140-0[&#60; Capítulo Anterior] | <<v19-141-0,Topo>> | xref:019-salmos/019-salmos-142.adoc#v19-142-0[Próximo Capítulo &#62;]