include::./index.adoc[]

[[v19-99-0]]
=== Salmos, 99
// nvi ?, NVI - Nova Versão Internacional

[[v19-99-1]]

^<<v19-99-1,1>>^ O Senhor reina! As nações tremem! O seu trono está sobre os querubins! Abala-se a terra!

[[v19-99-2]]

^<<v19-99-2,2>>^ Grande é o Senhor em Sião; ele é exaltado acima de todas as nações!

[[v19-99-3]]

^<<v19-99-3,3>>^ Seja louvado o teu grande e temível nome, que é santo.

[[v19-99-4]]

^<<v19-99-4,4>>^ Rei poderoso, amigo da justiça! Estabeleceste a eqüidade e fizeste em Jacó o que é direito e justo.

[[v19-99-5]]

^<<v19-99-5,5>>^ Exaltem o Senhor, o nosso Deus, prostrem-se diante do estrado dos seus pés. Ele é santo!

[[v19-99-6]]

^<<v19-99-6,6>>^ Moisés e Arão estavam entre os seus sacerdotes, Samuel, entre os que invocavam o seu nome; eles clamavam pelo Senhor, e ele lhes respondia.

[[v19-99-7]]

^<<v19-99-7,7>>^ Falava-lhes da coluna de nuvem, e eles obedeciam aos seus mandamentos e aos decretos que ele lhes dava.

[[v19-99-8]]

^<<v19-99-8,8>>^ Tu lhes respondeste, Senhor, nosso Deus; para eles, tu eras um Deus perdoador, embora os tenhas castigado por suas rebeliões.

[[v19-99-9]]

^<<v19-99-9,9>>^ Exaltem o Senhor nosso Deus; prostrem-se, voltados para o seu santo monte, porque o Senhor, o nosso Deus, é santo.

'''

xref:019-salmos/019-salmos-098.adoc#v19-98-0[&#60; Capítulo Anterior] | <<v19-99-0,Topo>> | xref:019-salmos/019-salmos-100.adoc#v19-100-0[Próximo Capítulo &#62;]