include::./index.adoc[]

[[v19-25-0]]
=== Salmos, 25
// nvi ?, NVI - Nova Versão Internacional

[[v19-25-1]]

^<<v19-25-1,1>>^ A ti, Senhor, elevo a minha alma.

[[v19-25-2]]

^<<v19-25-2,2>>^ Em ti confio, ó meu Deus. Não deixes que eu seja humilhado, nem que os meus inimigos triunfem sobre mim!

[[v19-25-3]]

^<<v19-25-3,3>>^ Nenhum dos que esperam em ti ficará decepcionado; decepcionados ficarão aqueles que, sem motivo, agem traiçoeiramente.

[[v19-25-4]]

^<<v19-25-4,4>>^ Mostra-me, Senhor, os teus caminhos, ensina-me as tuas veredas;

[[v19-25-5]]

^<<v19-25-5,5>>^ guia-me com a tua verdade e ensina-me, pois tu és Deus, meu Salvador, e a minha esperança está em ti o tempo todo.

[[v19-25-6]]

^<<v19-25-6,6>>^ Lembra-te, Senhor, da tua compaixão e da tua misericórdia, que tens mostrado desde a antigüidade.

[[v19-25-7]]

^<<v19-25-7,7>>^ Não te lembres dos pecados e transgressões da minha juventude; conforme a tua misericórdia, lembra-te de mim, pois tu, Senhor, és bom.

[[v19-25-8]]

^<<v19-25-8,8>>^ Bom e justo é o Senhor; por isso mostra o caminho aos pecadores.

[[v19-25-9]]

^<<v19-25-9,9>>^ Conduz os humildes na justiça e lhes ensina o seu caminho.

[[v19-25-10]]

^<<v19-25-10,10>>^ Todos os caminhos do Senhor são amor e fidelidade para com os que cumprem os preceitos da sua aliança.

[[v19-25-11]]

^<<v19-25-11,11>>^ Por amor do teu nome, Senhor, perdoa o meu pecado, que é tão grande!

[[v19-25-12]]

^<<v19-25-12,12>>^ Quem é o homem que teme o Senhor? Ele o instruirá no caminho que deve seguir.

[[v19-25-13]]

^<<v19-25-13,13>>^ Viverá em prosperidade, e os seus descendentes herdarão a terra.

[[v19-25-14]]

^<<v19-25-14,14>>^ O Senhor confia os seus segredos aos que o temem, e os leva a conhecer a sua aliança.

[[v19-25-15]]

^<<v19-25-15,15>>^ Os meus olhos estão sempre voltados para o Senhor, pois só ele tira os meus pés da armadilha.

[[v19-25-16]]

^<<v19-25-16,16>>^ Volta-te para mim e tem misericórdia de mim, pois estou só e aflito.

[[v19-25-17]]

^<<v19-25-17,17>>^ As angústias do meu coração se multiplicaram; liberta-me da minha aflição.

[[v19-25-18]]

^<<v19-25-18,18>>^ Olha para a minha tribulação e o meu sofrimento, e perdoa todos os meus pecados.

[[v19-25-19]]

^<<v19-25-19,19>>^ Vê como aumentaram os meus inimigos e com que fúria me odeiam!

[[v19-25-20]]

^<<v19-25-20,20>>^ Guarda a minha vida e livra-me! Não me deixes decepcionado, pois eu me refugio em ti.

[[v19-25-21]]

^<<v19-25-21,21>>^ Que a integridade e a retidão me protejam, porque a minha esperança está em ti.

[[v19-25-22]]

^<<v19-25-22,22>>^ Ó Deus, liberta Israel de todas as suas aflições!

'''

xref:019-salmos/019-salmos-024.adoc#v19-24-0[&#60; Capítulo Anterior] | <<v19-25-0,Topo>> | xref:019-salmos/019-salmos-026.adoc#v19-26-0[Próximo Capítulo &#62;]