include::./index.adoc[]

[[v19-82-0]]
=== Salmos, 82
// nvi ?, NVI - Nova Versão Internacional

[[v19-82-1]]

^<<v19-82-1,1>>^ É Deus quem preside na assembléia divina; no meio dos deuses, ele é o juiz.

[[v19-82-2]]

^<<v19-82-2,2>>^ "Até quando vocês vão absolver os culpados e favorecer os ímpios? Pausa

[[v19-82-3]]

^<<v19-82-3,3>>^ Garantam justiça para os fracos e para os órfãos; mantenham os direitos dos necessitados e dos oprimidos.

[[v19-82-4]]

^<<v19-82-4,4>>^ Livrem os fracos e os pobres; libertem-nos das mãos dos ímpios.

[[v19-82-5]]

^<<v19-82-5,5>>^ Nada sabem, nada entendem. Vagueiam pelas trevas; todos os fundamentos da terra estão abalados.

[[v19-82-6]]

^<<v19-82-6,6>>^ Eu disse: vocês são deuses, todos vocês são filhos do Altíssimo.

[[v19-82-7]]

^<<v19-82-7,7>>^ Mas vocês morrerão como simples homens; cairão como qualquer outro governante. "

[[v19-82-8]]

^<<v19-82-8,8>>^ Levanta-te, ó Deus, julga a terra, pois todas as nações te pertencem

'''

xref:019-salmos/019-salmos-081.adoc#v19-81-0[&#60; Capítulo Anterior] | <<v19-82-0,Topo>> | xref:019-salmos/019-salmos-083.adoc#v19-83-0[Próximo Capítulo &#62;]