include::./index.adoc[]

[[v19-94-0]]
=== Salmos, 94
// nvi ?, NVI - Nova Versão Internacional

[[v19-94-1]]

^<<v19-94-1,1>>^ Ó Senhor, Deus vingador; Deus vingador! Intervém!

[[v19-94-2]]

^<<v19-94-2,2>>^ Levanta-te, Juiz da terra; retribui aos orgulhosos o que merecem.

[[v19-94-3]]

^<<v19-94-3,3>>^ Até quando os ímpios, Senhor, até quando os ímpios exultarão?

[[v19-94-4]]

^<<v19-94-4,4>>^ Eles despejam palavras arrogantes, todos esses malfeitores enchem-se de vanglória.

[[v19-94-5]]

^<<v19-94-5,5>>^ Massacram o teu povo, Senhor, e oprimem a tua herança;

[[v19-94-6]]

^<<v19-94-6,6>>^ matam as viúvas e os estrangeiros, assassinam os órfãos,

[[v19-94-7]]

^<<v19-94-7,7>>^ e ainda dizem: "O Senhor não nos vê; o Deus de Jacó nada percebe".

[[v19-94-8]]

^<<v19-94-8,8>>^ Insensatos, procurem entender! E vocês, tolos, quando se tornarão sábios?

[[v19-94-9]]

^<<v19-94-9,9>>^ Será que quem fez o ouvido não ouve? Será que quem formou o olho não vê?

[[v19-94-10]]

^<<v19-94-10,10>>^ Aquele que disciplina as nações os deixará sem castigo? Não tem sabedoria aquele que dá ao homem o conhecimento?

[[v19-94-11]]

^<<v19-94-11,11>>^ O Senhor conhece os pensamentos do homem, e sabe como são fúteis.

[[v19-94-12]]

^<<v19-94-12,12>>^ Como é feliz o homem a quem disciplinas, Senhor, aquele a quem ensinas a tua lei;

[[v19-94-13]]

^<<v19-94-13,13>>^ tranqüilo, enfrentará os dias maus, enquanto que, para os ímpios, uma cova se abrirá.

[[v19-94-14]]

^<<v19-94-14,14>>^ O Senhor não desamparará o seu povo; jamais abandonará a sua herança.

[[v19-94-15]]

^<<v19-94-15,15>>^ Voltará a haver justiça nos julgamentos, e todos os retos de coração a seguirão.

[[v19-94-16]]

^<<v19-94-16,16>>^ Quem se levantará a meu favor contra os ímpios? Quem ficará a meu lado contra os malfeitores?

[[v19-94-17]]

^<<v19-94-17,17>>^ Não fosse a ajuda do Senhor, eu já estaria habitando no silêncio.

[[v19-94-18]]

^<<v19-94-18,18>>^ Quando eu disse: "Os meus pés escorregaram", o teu amor leal, Senhor, me amparou!

[[v19-94-19]]

^<<v19-94-19,19>>^ Quando a ansiedade já me dominava no íntimo, o teu consolo trouxe alívio à minha alma.

[[v19-94-20]]

^<<v19-94-20,20>>^ Poderá um trono corrupto estar em aliança contigo?, um trono que faz injustiças em nome da lei?

[[v19-94-21]]

^<<v19-94-21,21>>^ Eles planejam contra a vida dos justos e condenam os inocentes à morte.

[[v19-94-22]]

^<<v19-94-22,22>>^ Mas o Senhor é a minha torre segura; o meu Deus é a rocha em que encontro refúgio.

[[v19-94-23]]

^<<v19-94-23,23>>^ Fará cair sobre eles os seus crimes, e os destruirá por causa dos seus pecados; o Senhor, o nosso Deus, os destruirá!

'''

xref:019-salmos/019-salmos-093.adoc#v19-93-0[&#60; Capítulo Anterior] | <<v19-94-0,Topo>> | xref:019-salmos/019-salmos-095.adoc#v19-95-0[Próximo Capítulo &#62;]