include::./index.adoc[]

[[v19-36-0]]
=== Salmos, 36
// nvi ?, NVI - Nova Versão Internacional

[[v19-36-1]]

^<<v19-36-1,1>>^ Há no meu íntimo um oráculo a respeito da maldade do ímpio: Aos seus olhos é inútil temer a Deus.

[[v19-36-2]]

^<<v19-36-2,2>>^ Ele se acha tão importante, que não percebe nem rejeita o seu pecado.

[[v19-36-3]]

^<<v19-36-3,3>>^ As palavras da sua boca são maldosas e traiçoeiras; abandonou o bom senso e não quer fazer o bem.

[[v19-36-4]]

^<<v19-36-4,4>>^ Até na sua cama planeja maldade; nada há de bom no caminho a que se entregou, e ele nunca rejeita o mal.

[[v19-36-5]]

^<<v19-36-5,5>>^ O teu amor, Senhor, chega até os céus; a tua fidelidade até as nuvens.

[[v19-36-6]]

^<<v19-36-6,6>>^ A tua justiça é firme como as altas montanhas; as tuas decisões insondáveis como o grande mar. Tu, Senhor, preservas tanto os homens quanto os animais.

[[v19-36-7]]

^<<v19-36-7,7>>^ Como é precioso o teu amor, ó Deus! Os homens encontram refúgio à sombra das tuas asas.

[[v19-36-8]]

^<<v19-36-8,8>>^ Eles se banqueteiam na fartura da tua casa; tu lhes dás de beber do teu rio de delícias.

[[v19-36-9]]

^<<v19-36-9,9>>^ Pois em ti está a fonte da vida; graças à tua luz, vemos a luz.

[[v19-36-10]]

^<<v19-36-10,10>>^ Estende o teu amor aos que te conhecem, a tua justiça aos que são retos de coração.

[[v19-36-11]]

^<<v19-36-11,11>>^ Não permitas que o arrogante me pisoteie, nem que a mão do ímpio me faça recuar.

[[v19-36-12]]

^<<v19-36-12,12>>^ Lá estão os malfeitores caídos, lançados ao chão, incapazes de levantar-se!

'''

xref:019-salmos/019-salmos-035.adoc#v19-35-0[&#60; Capítulo Anterior] | <<v19-36-0,Topo>> | xref:019-salmos/019-salmos-037.adoc#v19-37-0[Próximo Capítulo &#62;]