include::./index.adoc[]

[[v19-135-0]]
=== Salmos, 135
// nvi ?, NVI - Nova Versão Internacional

[[v19-135-1]]

^<<v19-135-1,1>>^ Aleluia! Louvem o nome do Senhor; louvem-no, servos do Senhor,

[[v19-135-2]]

^<<v19-135-2,2>>^ vocês, que servem na casa do Senhor, nos pátios da casa de nosso Deus.

[[v19-135-3]]

^<<v19-135-3,3>>^ Louvem o Senhor, pois o Senhor é bom; cantem louvores ao seu nome, pois é nome amável.

[[v19-135-4]]

^<<v19-135-4,4>>^ Porque o Senhor escolheu a Jacó, a Israel como seu tesouro pessoal.

[[v19-135-5]]

^<<v19-135-5,5>>^ Na verdade, sei que o Senhor é grande, que o nosso Soberano é maior do que todos os deuses.

[[v19-135-6]]

^<<v19-135-6,6>>^ O Senhor faz tudo o que lhe agrada, nos céus e na terra, nos mares e em todas as suas profundezas.

[[v19-135-7]]

^<<v19-135-7,7>>^ Ele traz as nuvens desde os confins da terra; envia os relâmpagos que acompanham a chuva e faz que o vento saia dos seus depósitos.

[[v19-135-8]]

^<<v19-135-8,8>>^ Foi ele que matou os primogênitos do Egito, tanto dos homens como dos animais.

[[v19-135-9]]

^<<v19-135-9,9>>^ Ele realizou em pleno Egito sinais e maravilhas, contra o faraó e todos os seus conselheiros.

[[v19-135-10]]

^<<v19-135-10,10>>^ Foi ele quem feriu muitas nações e matou reis poderosos:

[[v19-135-11]]

^<<v19-135-11,11>>^ Seom, rei dos amorreus, Ogue, rei de Basã, e todos os reinos de Canaã;

[[v19-135-12]]

^<<v19-135-12,12>>^ e deu a terra deles como herança, como herança a seu povo Israel.

[[v19-135-13]]

^<<v19-135-13,13>>^ O teu nome, Senhor, permanece para sempre, a tua fama, Senhor, por todas as gerações!

[[v19-135-14]]

^<<v19-135-14,14>>^ O Senhor defenderá o seu povo e terá compaixão dos seus servos.

[[v19-135-15]]

^<<v19-135-15,15>>^ Os ídolos das nações não passam de prata e ouro, feitos por mãos humanas.

[[v19-135-16]]

^<<v19-135-16,16>>^ Têm boca, mas não podem falar, olhos, mas não podem ver;

[[v19-135-17]]

^<<v19-135-17,17>>^ têm ouvidos, mas não podem escutar, nem há respiração em sua boca.

[[v19-135-18]]

^<<v19-135-18,18>>^ Tornem-se como eles aqueles que os fazem e todos os que neles confiam.

[[v19-135-19]]

^<<v19-135-19,19>>^ Bendiga o Senhor, ó israelitas! Bendiga o Senhor, ó sacerdotes!

[[v19-135-20]]

^<<v19-135-20,20>>^ Bendiga o Senhor, ó levitas! Bendigam o Senhor os que temem ao Senhor!

[[v19-135-21]]

^<<v19-135-21,21>>^ Bendito seja o Senhor desde Sião, aquele que habita em Jerusalém. Aleluia!

'''

xref:019-salmos/019-salmos-134.adoc#v19-134-0[&#60; Capítulo Anterior] | <<v19-135-0,Topo>> | xref:019-salmos/019-salmos-136.adoc#v19-136-0[Próximo Capítulo &#62;]