include::./index.adoc[]

[[v19-42-0]]
=== Salmos, 42
// nvi ?, NVI - Nova Versão Internacional

[[v19-42-1]]

^<<v19-42-1,1>>^ Como a corça anseia por águas correntes, a minha alma anseia por ti, ó Deus.

[[v19-42-2]]

^<<v19-42-2,2>>^ A minha alma tem sede de Deus, do Deus vivo. Quando poderei entrar para apresentar-me a Deus?

[[v19-42-3]]

^<<v19-42-3,3>>^ Minhas lágrimas têm sido o meu alimento de dia e de noite, pois me perguntam o tempo todo: "Onde está o seu Deus? "

[[v19-42-4]]

^<<v19-42-4,4>>^ Quando me lembro destas coisas choro angustiado. Pois eu costumava ir com a multidão, conduzindo a procissão à casa de Deus, com cantos de alegria e de ação de graças entre a multidão que festejava.

[[v19-42-5]]

^<<v19-42-5,5>>^ Por que você está assim tão triste, ó minha alma? Por que está assim tão perturbada dentro de mim? Ponha a sua esperança em Deus! Pois ainda o louvarei; ele é o meu Salvador e

[[v19-42-6]]

^<<v19-42-6,6>>^ o meu Deus. A minha alma está profundamente triste; por isso de ti me lembro desde a terra do Jordão, das alturas do Hermom, desde o monte Mizar.

[[v19-42-7]]

^<<v19-42-7,7>>^ Abismo chama abismo ao rugir das tuas cachoeiras; todas as tuas ondas e vagalhões se abateram sobre mim.

[[v19-42-8]]

^<<v19-42-8,8>>^ Conceda-me o Senhor o seu fiel amor de dia; de noite esteja comigo a sua canção. É a minha oração ao Deus que me dá vida.

[[v19-42-9]]

^<<v19-42-9,9>>^ Direi a Deus, minha Rocha: "Por que te esqueceste de mim? Por que devo sair vagueando e pranteando, oprimido pelo inimigo? "

[[v19-42-10]]

^<<v19-42-10,10>>^ Até os meus ossos sofrem agonia mortal quando os meus adversários zombam de mim, perguntando-me o tempo todo: "Onde está o seu Deus? "

[[v19-42-11]]

^<<v19-42-11,11>>^ Por que você está assim tão triste, ó minha alma? Por que está assim tão perturbada dentro de mim? Ponha a sua esperança em Deus! Pois ainda o louvarei; ele é o meu Salvador e o meu Deus.

'''

xref:019-salmos/019-salmos-041.adoc#v19-41-0[&#60; Capítulo Anterior] | <<v19-42-0,Topo>> | xref:019-salmos/019-salmos-043.adoc#v19-43-0[Próximo Capítulo &#62;]