include::./index.adoc[]

[[v19-71-0]]
=== Salmos, 71
// nvi ?, NVI - Nova Versão Internacional

[[v19-71-1]]

^<<v19-71-1,1>>^ Em ti, Senhor, busquei refúgio; nunca permitas que eu seja humilhado.

[[v19-71-2]]

^<<v19-71-2,2>>^ Resgata-me e livra-me por tua justiça; inclina o teu ouvido para mim e salva-me.

[[v19-71-3]]

^<<v19-71-3,3>>^ Peço-te que sejas a minha rocha de refúgio, para onde eu sempre possa ir; dá ordem para que me libertem, pois és a minha rocha e a minha fortaleza.

[[v19-71-4]]

^<<v19-71-4,4>>^ Livra-me, ó meu Deus, das mãos dos ímpios, das garras dos perversos e cruéis.

[[v19-71-5]]

^<<v19-71-5,5>>^ Pois tu és a minha esperança, ó Soberano Senhor, em ti está a minha confiança desde a juventude.

[[v19-71-6]]

^<<v19-71-6,6>>^ Desde o ventre materno dependo de ti; tu me sustentaste desde as entranhas de minha mãe. Eu sempre te louvarei!

[[v19-71-7]]

^<<v19-71-7,7>>^ Tornei-me um exemplo para muitos, porque tu és o meu refúgio seguro.

[[v19-71-8]]

^<<v19-71-8,8>>^ Do teu louvor transborda a minha boca, que o tempo todo proclama o teu esplendor.

[[v19-71-9]]

^<<v19-71-9,9>>^ Não me rejeites na minha velhice; não me abandones quando se vão as minhas forças.

[[v19-71-10]]

^<<v19-71-10,10>>^ Pois os meus inimigos me caluniam; os que estão à espreita juntam-se e planejam matar-me.

[[v19-71-11]]

^<<v19-71-11,11>>^ "Deus o abandonou", dizem eles; "persigam-no e prendam-no, pois ninguém o livrará". -

[[v19-71-12]]

^<<v19-71-12,12>>^ Não fiques longe de mim, ó Deus; ó meu Deus, apressa-te em ajudar-me.

[[v19-71-13]]

^<<v19-71-13,13>>^ Pereçam humilhados os meus acusadores; sejam cobertos de zombaria e vergonha os que querem prejudicar-me.

[[v19-71-14]]

^<<v19-71-14,14>>^ Mas eu sempre terei esperança e te louvarei cada vez mais.

[[v19-71-15]]

^<<v19-71-15,15>>^ A minha boca falará sem cessar da tua justiça e dos teus incontáveis atos de salvação.

[[v19-71-16]]

^<<v19-71-16,16>>^ Falarei dos teus feitos poderosos, ó Soberano Senhor; proclamarei a tua justiça, unicamente a tua justiça.

[[v19-71-17]]

^<<v19-71-17,17>>^ Desde a minha juventude, ó Deus, tens me ensinado, e até hoje eu anuncio as tuas maravilhas.

[[v19-71-18]]

^<<v19-71-18,18>>^ Agora que estou velho, de cabelos brancos, não me abandones, ó Deus, para que eu possa falar da tua força aos nossos filhos, e do teu poder às futuras gerações.

[[v19-71-19]]

^<<v19-71-19,19>>^ Tua justiça chega até as alturas, ó Deus, tu, que tens feito coisas grandiosas. Quem se compara a ti, ó Deus?

[[v19-71-20]]

^<<v19-71-20,20>>^ Tu, que me fizeste passar muitas e duras tribulações, restaurarás a minha vida, e das profundezas da terra de novo me farás subir.

[[v19-71-21]]

^<<v19-71-21,21>>^ Tu me farás mais honrado e mais uma vez me consolarás.

[[v19-71-22]]

^<<v19-71-22,22>>^ E eu te louvarei com a lira por tua fidelidade, ó meu Deus; cantarei louvores a ti com a harpa, ó Santo de Israel.

[[v19-71-23]]

^<<v19-71-23,23>>^ Os meus lábios gritarão de alegria quando eu cantar louvores a ti, pois tu me redimiste.

[[v19-71-24]]

^<<v19-71-24,24>>^ Também a minha língua sempre falará dos teus atos de justiça, pois os que queriam prejudicar-me foram humilhados e ficaram frustrados.

'''

xref:019-salmos/019-salmos-070.adoc#v19-70-0[&#60; Capítulo Anterior] | <<v19-71-0,Topo>> | xref:019-salmos/019-salmos-072.adoc#v19-72-0[Próximo Capítulo &#62;]