include::./index.adoc[]

[[v19-12-0]]
=== Salmos, 12
// nvi ?, NVI - Nova Versão Internacional

[[v19-12-1]]

^<<v19-12-1,1>>^ Salva-nos, Senhor! Já não há quem seja fiel; já não se confia em ninguém entre os homens.

[[v19-12-2]]

^<<v19-12-2,2>>^ Cada um mente ao seu próximo; seus lábios bajuladores falam com segundas intenções.

[[v19-12-3]]

^<<v19-12-3,3>>^ Que o Senhor corte todos os lábios bajuladores e toda língua arrogante

[[v19-12-4]]

^<<v19-12-4,4>>^ dos que dizem: "Venceremos graças à nossa língua; somos donos dos nossos lábios! Quem é senhor sobre nós? "

[[v19-12-5]]

^<<v19-12-5,5>>^ "Por causa da opressão do necessitado e do gemido do pobre, agora me levantarei", diz o Senhor. "Eu lhes darei a segurança que tanto anseiam. "

[[v19-12-6]]

^<<v19-12-6,6>>^ As palavras do Senhor são puras, são como prata purificada num forno, sete vezes refinada.

[[v19-12-7]]

^<<v19-12-7,7>>^ Senhor, tu nos guardarás seguros, e dessa gente nos protegerás para sempre.

[[v19-12-8]]

^<<v19-12-8,8>>^ Os ímpios andam altivos por toda parte, quando a corrupção é exaltada entre os homens.

'''

xref:019-salmos/019-salmos-011.adoc#v19-11-0[&#60; Capítulo Anterior] | <<v19-12-0,Topo>> | xref:019-salmos/019-salmos-013.adoc#v19-13-0[Próximo Capítulo &#62;]