include::./index.adoc[]

[[v19-59-0]]
=== Salmos, 59
// nvi ?, NVI - Nova Versão Internacional

[[v19-59-1]]

^<<v19-59-1,1>>^ Livra-me dos meus inimigos, ó Deus; põe-me fora do alcance dos meus agressores.

[[v19-59-2]]

^<<v19-59-2,2>>^ Livra-me dos que praticam o mal e salva-me dos assassinos.

[[v19-59-3]]

^<<v19-59-3,3>>^ Vê como ficam à minha espreita! Homens cruéis conspiram contra mim, sem que eu tenha cometido qualquer delito ou pecado, ó Senhor.

[[v19-59-4]]

^<<v19-59-4,4>>^ Mesmo que de nada eu tenha culpa, eles se preparam às pressas para atacar-me. Levanta-te para ajudar-me; olha para a situação em que me encontro!

[[v19-59-5]]

^<<v19-59-5,5>>^ Ó Senhor, Deus dos Exércitos, ó Deus de Israel! Desperta para castigar todas as nações; não tenhas misericórdia dos traidores perversos. Pausa

[[v19-59-6]]

^<<v19-59-6,6>>^ Eles voltam ao cair da tarde, rosnando como cães e rondando a cidade.

[[v19-59-7]]

^<<v19-59-7,7>>^ Vê que ameaças saem de suas bocas; seus lábios são como espadas, e dizem: "Quem nos ouvirá? "

[[v19-59-8]]

^<<v19-59-8,8>>^ Mas tu, Senhor, vais rir deles; caçoarás de todas aquelas nações.

[[v19-59-9]]

^<<v19-59-9,9>>^ Ó tu, minha força, por ti vou aguardar; tu, ó Deus, és o meu alto refúgio.

[[v19-59-10]]

^<<v19-59-10,10>>^ O meu Deus fiel virá ao meu encontro e permitirá que eu triunfe sobre os meus inimigos.

[[v19-59-11]]

^<<v19-59-11,11>>^ Mas não os mates, ó Senhor, nosso escudo, se não, o meu povo o esquecerá. Em teu poder faze-os vaguearem, e abate-os.

[[v19-59-12]]

^<<v19-59-12,12>>^ Pelos pecados de suas bocas, pelas palavras de seus lábios, sejam apanhados em seu orgulho. Pelas maldições e mentiras que pronunciam,

[[v19-59-13]]

^<<v19-59-13,13>>^ consome-os em tua ira, consome-os até que não mais existam. Então se saberá até os confins da terra que Deus governa Jacó. Pausa

[[v19-59-14]]

^<<v19-59-14,14>>^ Eles voltam ao cair da tarde, rosnando como cães, e rondando a cidade.

[[v19-59-15]]

^<<v19-59-15,15>>^ À procura de comida perambulam e, se não ficam satisfeitos, uivam.

[[v19-59-16]]

^<<v19-59-16,16>>^ Mas eu cantarei louvores à tua força, de manhã louvarei a tua fidelidade; pois tu és o meu alto refúgio, abrigo seguro nos tempos difíceis.

[[v19-59-17]]

^<<v19-59-17,17>>^ Ó minha força, canto louvores a ti; tu és, ó Deus, o meu alto refúgio, o Deus que me ama.

'''

xref:019-salmos/019-salmos-058.adoc#v19-58-0[&#60; Capítulo Anterior] | <<v19-59-0,Topo>> | xref:019-salmos/019-salmos-060.adoc#v19-60-0[Próximo Capítulo &#62;]