include::./index.adoc[]

[[v19-112-0]]
=== Salmos, 112
// nvi ?, NVI - Nova Versão Internacional

[[v19-112-1]]

^<<v19-112-1,1>>^ Aleluia! Como é feliz o homem que teme o Senhor e tem grande prazer em seus mandamentos!

[[v19-112-2]]

^<<v19-112-2,2>>^ Seus descendentes serão poderosos na terra, serão uma geração abençoada, de homens íntegros.

[[v19-112-3]]

^<<v19-112-3,3>>^ Grande riqueza há em sua casa, e a sua justiça dura para sempre.

[[v19-112-4]]

^<<v19-112-4,4>>^ A luz raia nas trevas para o íntegro, para quem é misericordioso, compassivo e justo.

[[v19-112-5]]

^<<v19-112-5,5>>^ Feliz é o homem que empresta com generosidade e que com honestidade conduz os seus negócios.

[[v19-112-6]]

^<<v19-112-6,6>>^ O justo jamais será abalado; para sempre se lembrarão dele.

[[v19-112-7]]

^<<v19-112-7,7>>^ Não temerá más notícias; seu coração está firme, confiante no Senhor.

[[v19-112-8]]

^<<v19-112-8,8>>^ O seu coração está seguro e nada temerá. No final, verá a derrota dos seus adversários.

[[v19-112-9]]

^<<v19-112-9,9>>^ Reparte generosamente com os pobres; a sua justiça dura para sempre; seu poder será exaltado em honra.

[[v19-112-10]]

^<<v19-112-10,10>>^ O ímpio o vê e fica irado, range os dentes e definha. O desejo dos ímpios se frustrará.

'''

xref:019-salmos/019-salmos-111.adoc#v19-111-0[&#60; Capítulo Anterior] | <<v19-112-0,Topo>> | xref:019-salmos/019-salmos-113.adoc#v19-113-0[Próximo Capítulo &#62;]