include::./index.adoc[]

[[v19-96-0]]
=== Salmos, 96
// nvi ?, NVI - Nova Versão Internacional

[[v19-96-1]]

^<<v19-96-1,1>>^ Cantem ao Senhor um novo cântico; cantem ao Senhor, todos os habitantes da terra!

[[v19-96-2]]

^<<v19-96-2,2>>^ Cantem ao Senhor, bendigam o seu nome; cada dia proclamem a sua salvação!

[[v19-96-3]]

^<<v19-96-3,3>>^ Anunciem a sua glória entre as nações, seus feitos maravilhosos entre todos os povos!

[[v19-96-4]]

^<<v19-96-4,4>>^ Porque o Senhor é grande e digno de todo louvor, mais temível do que todos os deuses!

[[v19-96-5]]

^<<v19-96-5,5>>^ Todos os deuses das nações não passam de ídolos, mas o Senhor fez os céus.

[[v19-96-6]]

^<<v19-96-6,6>>^ Majestade e esplendor estão diante dele, poder e dignidade, no seu santuário.

[[v19-96-7]]

^<<v19-96-7,7>>^ Dêem ao Senhor, ó famílias das nações, dêem ao Senhor glória e força.

[[v19-96-8]]

^<<v19-96-8,8>>^ Dêem ao Senhor a glória devida ao seu nome, e entrem nos seus átrios trazendo ofertas.

[[v19-96-9]]

^<<v19-96-9,9>>^ Adorem ao Senhor no esplendor da sua santidade; tremam diante dele todos os habitantes da terra.

[[v19-96-10]]

^<<v19-96-10,10>>^ Digam entre as nações: "O Senhor reina! " Por isso firme está o mundo, e não se abalará, e ele julgará os povos com justiça.

[[v19-96-11]]

^<<v19-96-11,11>>^ Regozijem-se os céus e exulte a terra! Ressoe o mar e tudo o que nele existe!

[[v19-96-12]]

^<<v19-96-12,12>>^ Regozijem-se os campos e tudo o que neles há! Cantem de alegria todas as árvores da floresta,

[[v19-96-13]]

^<<v19-96-13,13>>^ cantem diante do Senhor, porque ele vem, vem julgar a terra; julgará o mundo com justiça e os povos, com a sua fidelidade!

'''

xref:019-salmos/019-salmos-095.adoc#v19-95-0[&#60; Capítulo Anterior] | <<v19-96-0,Topo>> | xref:019-salmos/019-salmos-097.adoc#v19-97-0[Próximo Capítulo &#62;]