include::./index.adoc[]

[[v19-77-0]]
=== Salmos, 77
// nvi ?, NVI - Nova Versão Internacional

[[v19-77-1]]

^<<v19-77-1,1>>^ Clamo a Deus por socorro; clamo a Deus que me escute.

[[v19-77-2]]

^<<v19-77-2,2>>^ Quando estou angustiado, busco o Senhor; de noite estendo as mãos sem cessar; a minha alma está inconsolável!

[[v19-77-3]]

^<<v19-77-3,3>>^ Lembro-me de ti, ó Deus, e suspiro; começo a meditar, e o meu espírito desfalece. Pausa

[[v19-77-4]]

^<<v19-77-4,4>>^ Não me permites fechar os olhos; tão inquieto estou que não consigo falar.

[[v19-77-5]]

^<<v19-77-5,5>>^ Fico a pensar nos dias que se foram, nos anos há muito passados;

[[v19-77-6]]

^<<v19-77-6,6>>^ de noite recordo minhas canções. O meu coração medita, e o meu espírito pergunta:

[[v19-77-7]]

^<<v19-77-7,7>>^ "Irá o Senhor rejeitar-nos para sempre? Jamais tornará a mostrar-nos o seu favor?

[[v19-77-8]]

^<<v19-77-8,8>>^ Desapareceu para sempre o seu amor? Acabou-se a sua promessa?

[[v19-77-9]]

^<<v19-77-9,9>>^ Esqueceu-se Deus de ser misericordioso? Em sua ira refreou sua compaixão? " Pausa

[[v19-77-10]]

^<<v19-77-10,10>>^ Então pensei: a razão da minha dor é que a mão direita do Altíssimo não age mais.

[[v19-77-11]]

^<<v19-77-11,11>>^ Recordarei os feitos do Senhor; recordarei os teus antigos milagres.

[[v19-77-12]]

^<<v19-77-12,12>>^ Meditarei em todas as tuas obras e considerarei todos os teus feitos.

[[v19-77-13]]

^<<v19-77-13,13>>^ Teus caminhos, ó Deus, são santos. Que deus é tão grande como o nosso Deus?

[[v19-77-14]]

^<<v19-77-14,14>>^ Tu és o Deus que realiza milagres; mostras o teu poder entre os povos.

[[v19-77-15]]

^<<v19-77-15,15>>^ Com o teu braço forte resgataste o teu povo, os descendentes de Jacó e de José. Pausa

[[v19-77-16]]

^<<v19-77-16,16>>^ As águas te viram, ó Deus, as águas te viram e se contorceram; até os abismos estremeceram.

[[v19-77-17]]

^<<v19-77-17,17>>^ As nuvens despejaram chuvas, ressoou nos céus o trovão; as tuas flechas reluziam em todas as direções.

[[v19-77-18]]

^<<v19-77-18,18>>^ No redemoinho, estrondou o teu trovão, os teus relâmpagos iluminaram o mundo; a terra tremeu e sacudiu-se.

[[v19-77-19]]

^<<v19-77-19,19>>^ A tua vereda passou pelo mar, o teu caminho pelas águas poderosas, e ninguém viu as tuas pegadas.

[[v19-77-20]]

^<<v19-77-20,20>>^ Guiaste o teu povo como a um rebanho pela mão de Moisés e de Arão.

'''

xref:019-salmos/019-salmos-076.adoc#v19-76-0[&#60; Capítulo Anterior] | <<v19-77-0,Topo>> | xref:019-salmos/019-salmos-078.adoc#v19-78-0[Próximo Capítulo &#62;]