include::./index.adoc[]

[[v19-81-0]]
=== Salmos, 81
// nvi ?, NVI - Nova Versão Internacional

[[v19-81-1]]

^<<v19-81-1,1>>^ Cantem de alegria a Deus, nossa força; aclamem o Deus de Jacó!

[[v19-81-2]]

^<<v19-81-2,2>>^ Comecem o louvor, façam ressoar o tamborim, toquem a lira e a harpa melodiosa.

[[v19-81-3]]

^<<v19-81-3,3>>^ Toquem a trombeta na lua nova e no dia de lua cheia, dia da nossa festa;

[[v19-81-4]]

^<<v19-81-4,4>>^ porque este é um decreto para Israel, uma ordenança do Deus de Jacó,

[[v19-81-5]]

^<<v19-81-5,5>>^ que ele estabeleceu como estatuto para José, quando atacou o Egito. Ali ouvimos uma língua que não conhecíamos.

[[v19-81-6]]

^<<v19-81-6,6>>^ Ele diz: "Tirei o peso dos seus ombros; suas mãos ficaram livres dos cestos de cargas.

[[v19-81-7]]

^<<v19-81-7,7>>^ Na sua aflição vocês clamaram e eu os livrei, do esconderijo dos trovões lhes respondi; eu os pus à prova nas águas de Meribá. Pausa

[[v19-81-8]]

^<<v19-81-8,8>>^ "Ouça, meu povo, as minhas advertências; se tão-somente você me escutasse, ó Israel!

[[v19-81-9]]

^<<v19-81-9,9>>^ Não tenha deus estrangeiro no seu meio; não se incline perante nenhum deus estranho.

[[v19-81-10]]

^<<v19-81-10,10>>^ Eu sou o Senhor, o seu Deus, que o tirei da terra do Egito. Abra a sua boca, e eu o alimentarei.

[[v19-81-11]]

^<<v19-81-11,11>>^ "Mas o meu povo não quis ouvir-me; Israel não quis obedecer-me.

[[v19-81-12]]

^<<v19-81-12,12>>^ Por isso os entreguei ao seu coração obstinado, para seguirem os seus próprios planos.

[[v19-81-13]]

^<<v19-81-13,13>>^ "Se o meu povo apenas me ouvisse, se Israel seguisse os meus caminhos,

[[v19-81-14]]

^<<v19-81-14,14>>^ com rapidez eu subjugaria os seus inimigos e voltaria a minha mão contra os seus adversários!

[[v19-81-15]]

^<<v19-81-15,15>>^ Os que odeiam o Senhor se renderiam diante dele, e receberiam um castigo perpétuo.

[[v19-81-16]]

^<<v19-81-16,16>>^ Mas eu sustentaria Israel com o melhor trigo, e com o mel da rocha eu o satisfaria".

'''

xref:019-salmos/019-salmos-080.adoc#v19-80-0[&#60; Capítulo Anterior] | <<v19-81-0,Topo>> | xref:019-salmos/019-salmos-082.adoc#v19-82-0[Próximo Capítulo &#62;]