include::./index.adoc[]

[[v19-136-0]]
=== Salmos, 136
// nvi ?, NVI - Nova Versão Internacional

[[v19-136-1]]

^<<v19-136-1,1>>^ Dêem graças ao Senhor, porque ele é bom. O seu amor dura para sempre!

[[v19-136-2]]

^<<v19-136-2,2>>^ Dêem graças ao Deus dos deuses. O seu amor dura para sempre!

[[v19-136-3]]

^<<v19-136-3,3>>^ Dêem graças ao Senhor dos senhores. O seu amor dura para sempre!

[[v19-136-4]]

^<<v19-136-4,4>>^ Ao único que faz grandes maravilhas, O seu amor dura para sempre!

[[v19-136-5]]

^<<v19-136-5,5>>^ que com habilidade fez os céus, O seu amor dura para sempre!

[[v19-136-6]]

^<<v19-136-6,6>>^ que estendeu a terra sobre as águas; O seu amor dura para sempre!

[[v19-136-7]]

^<<v19-136-7,7>>^ Àquele que fez os grandes luminares, O seu amor dura para sempre!

[[v19-136-8]]

^<<v19-136-8,8>>^ o sol para governar o dia, O seu amor dura para sempre!

[[v19-136-9]]

^<<v19-136-9,9>>^ a lua e as estrelas para governarem a noite; O seu amor dura para sempre!

[[v19-136-10]]

^<<v19-136-10,10>>^ Àquele que matou os primogênitos do Egito O seu amor dura para sempre!

[[v19-136-11]]

^<<v19-136-11,11>>^ e tirou Israel do meio deles O seu amor dura para sempre!

[[v19-136-12]]

^<<v19-136-12,12>>^ com mão poderosa e braço forte; O seu amor dura para sempre!

[[v19-136-13]]

^<<v19-136-13,13>>^ Àquele que dividiu o mar Vermelho O seu amor dura para sempre!

[[v19-136-14]]

^<<v19-136-14,14>>^ e fez Israel atravessá-lo, O seu amor dura para sempre!

[[v19-136-15]]

^<<v19-136-15,15>>^ mas lançou o faraó e o seu exército no mar Vermelho; O seu amor dura para sempre!

[[v19-136-16]]

^<<v19-136-16,16>>^ Àquele que conduziu seu povo pelo deserto, O seu amor dura para sempre!

[[v19-136-17]]

^<<v19-136-17,17>>^ que feriu grandes reis O seu amor dura para sempre!

[[v19-136-18]]

^<<v19-136-18,18>>^ e matou reis poderosos; O seu amor dura para sempre!

[[v19-136-19]]

^<<v19-136-19,19>>^ Seom, rei dos amorreus, O seu amor dura para sempre!

[[v19-136-20]]

^<<v19-136-20,20>>^ e Ogue, rei de Basã, O seu amor dura para sempre!

[[v19-136-21]]

^<<v19-136-21,21>>^ e deu a terra deles como herança, O seu amor dura para sempre!

[[v19-136-22]]

^<<v19-136-22,22>>^ como herança ao seu servo Israel; O seu amor dura para sempre!

[[v19-136-23]]

^<<v19-136-23,23>>^ Àquele que se lembrou de nós quando fomos humilhados O seu amor dura para sempre!

[[v19-136-24]]

^<<v19-136-24,24>>^ e nos livrou dos nossos adversários; O seu amor dura para sempre!

[[v19-136-25]]

^<<v19-136-25,25>>^ Àquele que dá alimento a todos os seres vivos. O seu amor dura para sempre!

[[v19-136-26]]

^<<v19-136-26,26>>^ Dêem graças ao Deus dos céus. O seu amor dura para sempre!

'''

xref:019-salmos/019-salmos-135.adoc#v19-135-0[&#60; Capítulo Anterior] | <<v19-136-0,Topo>> | xref:019-salmos/019-salmos-137.adoc#v19-137-0[Próximo Capítulo &#62;]