include::./index.adoc[]

[[v19-56-0]]
=== Salmos, 56
// nvi ?, NVI - Nova Versão Internacional

[[v19-56-1]]

^<<v19-56-1,1>>^ Tem misericórdia de mim, ó Deus, pois os homens me pressionam; o tempo todo me atacam e me oprimem.

[[v19-56-2]]

^<<v19-56-2,2>>^ Os meus inimigos pressionam-me sem parar; muitos atacam-me arrogantemente.

[[v19-56-3]]

^<<v19-56-3,3>>^ Mas eu, quando estiver com medo, confiarei em ti.

[[v19-56-4]]

^<<v19-56-4,4>>^ Em Deus, cuja palavra eu louvo, em Deus eu confio, e não temerei. Que poderá fazer-me o simples mortal?

[[v19-56-5]]

^<<v19-56-5,5>>^ O tempo todo eles distorcem as minhas palavras; estão sempre tramando prejudicar-me.

[[v19-56-6]]

^<<v19-56-6,6>>^ Conspiram, ficam à espreita, vigiam os meus passos, na esperança de tirar-me a vida.

[[v19-56-7]]

^<<v19-56-7,7>>^ Deixarás escapar essa gente tão perversa? Na tua ira, ó Deus, derruba as nações.

[[v19-56-8]]

^<<v19-56-8,8>>^ Registra, tu mesmo, o meu lamento; recolhe as minhas lágrimas em teu odre; acaso não estão anotadas em teu livro?

[[v19-56-9]]

^<<v19-56-9,9>>^ Os meus inimigos retrocederão, quando eu clamar por socorro. Com isso saberei que Deus está a meu favor.

[[v19-56-10]]

^<<v19-56-10,10>>^ Confio em Deus, cuja palavra louvo, no Senhor, cuja palavra louvo,

[[v19-56-11]]

^<<v19-56-11,11>>^ nesse Deus eu confio, e não temerei. Que poderá fazer-me o homem?

[[v19-56-12]]

^<<v19-56-12,12>>^ Cumprirei os votos que te fiz, ó Deus; a ti apresentarei minhas ofertas de gratidão.

[[v19-56-13]]

^<<v19-56-13,13>>^ Pois me livraste da morte e os meus pés de tropeçarem, para que eu ande diante de Deus na luz que ilumina os vivos.

'''

xref:019-salmos/019-salmos-055.adoc#v19-55-0[&#60; Capítulo Anterior] | <<v19-56-0,Topo>> | xref:019-salmos/019-salmos-057.adoc#v19-57-0[Próximo Capítulo &#62;]