include::./index.adoc[]

[[v19-97-0]]
=== Salmos, 97
// nvi ?, NVI - Nova Versão Internacional

[[v19-97-1]]

^<<v19-97-1,1>>^ O Senhor reina! Exulte a terra e alegrem-se as regiões costeiras distantes.

[[v19-97-2]]

^<<v19-97-2,2>>^ Nuvens escuras e espessas o cercam; retidão e justiça são a base do seu trono.

[[v19-97-3]]

^<<v19-97-3,3>>^ Fogo vai adiante dele e devora os adversários ao redor.

[[v19-97-4]]

^<<v19-97-4,4>>^ Seus relâmpagos iluminam o mundo; a terra os vê e estremece.

[[v19-97-5]]

^<<v19-97-5,5>>^ Os montes se derretem como cera diante do Senhor, diante do Soberano de toda a terra.

[[v19-97-6]]

^<<v19-97-6,6>>^ Os céus proclamam a sua justiça, e todos os povos contemplam a sua glória.

[[v19-97-7]]

^<<v19-97-7,7>>^ Ficam decepcionados todos os que adoram imagens e se vangloriam de ídolos. Prostram-se diante dele todos os deuses!

[[v19-97-8]]

^<<v19-97-8,8>>^ Sião ouve e se alegra, e as cidades de Judá exultam, por causa das tuas sentenças, Senhor.

[[v19-97-9]]

^<<v19-97-9,9>>^ Pois tu, Senhor, és o Altíssimo sobre toda a terra! És exaltado muito acima de todos os deuses!

[[v19-97-10]]

^<<v19-97-10,10>>^ Odeiem o mal, vocês que amam o Senhor, pois ele protege a vida dos seus fiéis e os livra das mãos dos ímpios.

[[v19-97-11]]

^<<v19-97-11,11>>^ A luz nasce sobre o justo e a alegria sobre os retos de coração.

[[v19-97-12]]

^<<v19-97-12,12>>^ Alegrem-se no Senhor, justos, louvem o seu santo nome.

'''

xref:019-salmos/019-salmos-096.adoc#v19-96-0[&#60; Capítulo Anterior] | <<v19-97-0,Topo>> | xref:019-salmos/019-salmos-098.adoc#v19-98-0[Próximo Capítulo &#62;]