include::./index.adoc[]

[[v19-50-0]]
=== Salmos, 50
// nvi ?, NVI - Nova Versão Internacional

[[v19-50-1]]

^<<v19-50-1,1>>^ Fala o Senhor, o Deus supremo; convoca toda a terra, do nascente ao poente.

[[v19-50-2]]

^<<v19-50-2,2>>^ Desde Sião, perfeita em beleza, Deus resplandece.

[[v19-50-3]]

^<<v19-50-3,3>>^ Nosso Deus vem! Certamente não ficará calado! À sua frente vai um fogo devorador, e, ao seu redor, uma violenta tempestade.

[[v19-50-4]]

^<<v19-50-4,4>>^ Ele convoca os altos céus e a terra, para o julgamento do seu povo:

[[v19-50-5]]

^<<v19-50-5,5>>^ "Ajuntem os que me são fiéis, que, mediante sacrifício, fizeram aliança comigo".

[[v19-50-6]]

^<<v19-50-6,6>>^ E os céus proclamam a sua justiça, pois o próprio Deus é o juiz. Pausa

[[v19-50-7]]

^<<v19-50-7,7>>^ "Ouça, meu povo, pois eu falarei; vou testemunhar contra você, Israel: eu sou Deus, o seu Deus.

[[v19-50-8]]

^<<v19-50-8,8>>^ Não o acuso pelos seus sacrifícios, nem pelos holocaustos, que você sempre me oferece.

[[v19-50-9]]

^<<v19-50-9,9>>^ Não tenho necessidade de nenhum novilho dos seus estábulos, nem dos bodes dos seus currais,

[[v19-50-10]]

^<<v19-50-10,10>>^ pois todos os animais da floresta são meus, como são as cabeças de gado aos milhares nas colinas.

[[v19-50-11]]

^<<v19-50-11,11>>^ Conheço todas as aves dos montes, e cuido das criaturas do campo.

[[v19-50-12]]

^<<v19-50-12,12>>^ Se eu tivesse fome, precisaria dizer a você? Pois o mundo é meu, e tudo o que nele existe.

[[v19-50-13]]

^<<v19-50-13,13>>^ Acaso como carne de touros ou bebo sangue de bodes?

[[v19-50-14]]

^<<v19-50-14,14>>^ Ofereça a Deus em sacrifício a sua gratidão, cumpra os seus votos para com o Altíssimo,

[[v19-50-15]]

^<<v19-50-15,15>>^ e clame a mim no dia da angústia; eu o livrarei, e você me honrará. "

[[v19-50-16]]

^<<v19-50-16,16>>^ Mas ao ímpio Deus diz: "Que direito você tem de recitar as minhas leis ou de ficar repetindo a minha aliança?

[[v19-50-17]]

^<<v19-50-17,17>>^ Pois você odeia a minha disciplina e dá as costas às minhas palavras!

[[v19-50-18]]

^<<v19-50-18,18>>^ Você vê um ladrão, e já se torna seu cúmplice, e com adúlteros se mistura.

[[v19-50-19]]

^<<v19-50-19,19>>^ Sua boca está cheia de maldade e a sua língua formula a fraude.

[[v19-50-20]]

^<<v19-50-20,20>>^ Deliberadamente você fala contra o seu irmão e calunia o filho de sua própria mãe.

[[v19-50-21]]

^<<v19-50-21,21>>^ Ficaria eu calado diante de tudo o que você tem feito? Você pensa que eu sou como você? Mas agora eu o acusarei diretamente, sem omitir coisa alguma.

[[v19-50-22]]

^<<v19-50-22,22>>^ "Considerem isto, vocês que se esquecem de Deus; caso contrário os despedaçarei, sem que ninguém os livre.

[[v19-50-23]]

^<<v19-50-23,23>>^ Quem me oferece sua gratidão como sacrifício, honra-me, e eu mostrarei a salvação de Deus ao que anda nos meus caminhos. "

'''

xref:019-salmos/019-salmos-049.adoc#v19-49-0[&#60; Capítulo Anterior] | <<v19-50-0,Topo>> | xref:019-salmos/019-salmos-051.adoc#v19-51-0[Próximo Capítulo &#62;]