include::./index.adoc[]

[[v19-91-0]]
=== Salmos, 91
// nvi ?, NVI - Nova Versão Internacional

[[v19-91-1]]

^<<v19-91-1,1>>^ Aquele que habita no abrigo do Altíssimo e descansa à sombra do Todo-poderoso

[[v19-91-2]]

^<<v19-91-2,2>>^ pode dizer ao Senhor: Tu és o meu refúgio e a minha fortaleza, o meu Deus, em quem confio.

[[v19-91-3]]

^<<v19-91-3,3>>^ Ele o livrará do laço do caçador e do veneno mortal.

[[v19-91-4]]

^<<v19-91-4,4>>^ Ele o cobrirá com as suas penas, e sob as suas asas você encontrará refúgio; a fidelidade dele será o seu escudo protetor.

[[v19-91-5]]

^<<v19-91-5,5>>^ Você não temerá o pavor da noite, nem a flecha que voa de dia,

[[v19-91-6]]

^<<v19-91-6,6>>^ nem a peste que se move sorrateira nas trevas, nem a praga que devasta ao meio-dia.

[[v19-91-7]]

^<<v19-91-7,7>>^ Mil poderão cair ao seu lado, dez mil à sua direita, mas nada o atingirá.

[[v19-91-8]]

^<<v19-91-8,8>>^ Você simplesmente olhará, e verá o castigo dos ímpios.

[[v19-91-9]]

^<<v19-91-9,9>>^ Se você fizer do Altíssimo o seu refúgio,

[[v19-91-10]]

^<<v19-91-10,10>>^ nenhum mal o atingirá, desgraça alguma chegará à sua tenda.

[[v19-91-11]]

^<<v19-91-11,11>>^ Porque a seus anjos ele dará ordens a seu respeito, para que o protejam em todos os seus caminhos;

[[v19-91-12]]

^<<v19-91-12,12>>^ com as mãos eles o segurarão, para que você não tropece em alguma pedra.

[[v19-91-13]]

^<<v19-91-13,13>>^ Você pisará o leão e a cobra; pisoteará o leão forte e a serpente.

[[v19-91-14]]

^<<v19-91-14,14>>^ "Porque ele me ama, eu o resgatarei; eu o protegerei, pois conhece o meu nome.

[[v19-91-15]]

^<<v19-91-15,15>>^ Ele clamará a mim, e eu lhe darei resposta, e na adversidade estarei com ele; vou livrá-lo e cobri-lo de honra.

[[v19-91-16]]

^<<v19-91-16,16>>^ Vida longa eu lhe darei, e lhe mostrarei a minha salvação. "

'''

xref:019-salmos/019-salmos-090.adoc#v19-90-0[&#60; Capítulo Anterior] | <<v19-91-0,Topo>> | xref:019-salmos/019-salmos-092.adoc#v19-92-0[Próximo Capítulo &#62;]