include::./index.adoc[]

[[v19-2-0]]
=== Salmos, 2
// nvi ?, NVI - Nova Versão Internacional

[[v19-2-1]]

^<<v19-2-1,1>>^ Por que se amotinam as nações e os povos tramam em vão?

[[v19-2-2]]

^<<v19-2-2,2>>^ Os reis da terra tomam posição e os governantes conspiram unidos contra o Senhor e contra o seu ungido, e dizem:

[[v19-2-3]]

^<<v19-2-3,3>>^ "Façamos em pedaços as suas correntes, lancemos de nós as suas algemas! "

[[v19-2-4]]

^<<v19-2-4,4>>^ Do seu trono nos céus o Senhor põe-se a rir e caçoa deles.

[[v19-2-5]]

^<<v19-2-5,5>>^ Em sua ira os repreende e em seu furor os aterroriza, dizendo:

[[v19-2-6]]

^<<v19-2-6,6>>^ "Eu mesmo estabeleci o meu rei em Sião, no meu santo monte".

[[v19-2-7]]

^<<v19-2-7,7>>^ Proclamarei o decreto do Senhor: Ele me disse: "Tu és meu filho; eu hoje te gerei.

[[v19-2-8]]

^<<v19-2-8,8>>^ Pede-me, e te darei as nações como herança e os confins da terra como tua propriedade.

[[v19-2-9]]

^<<v19-2-9,9>>^ Tu as quebrarás com vara de ferro e as despedaçarás como a um vaso de barro".

[[v19-2-10]]

^<<v19-2-10,10>>^ Por isso, ó reis, sejam prudentes; aceitem a advertência, autoridades da terra.

[[v19-2-11]]

^<<v19-2-11,11>>^ Adorem ao Senhor com temor; exultem com tremor.

[[v19-2-12]]

^<<v19-2-12,12>>^ Beijem o filho, para que ele não se ire e vocês não sejam destruídos de repente, pois num instante acende-se a sua ira. Como são felizes todos os que nele se refugiam!

'''

xref:019-salmos/019-salmos-001.adoc#v19-1-0[&#60; Capítulo Anterior] | <<v19-2-0,Topo>> | xref:019-salmos/019-salmos-003.adoc#v19-3-0[Próximo Capítulo &#62;]