include::./index.adoc[]

[[v19-11-0]]
=== Salmos, 11
// nvi ?, NVI - Nova Versão Internacional

[[v19-11-1]]

^<<v19-11-1,1>>^ No Senhor me refugio. Como então vocês podem dizer-me: "Fuja como um pássaro para os montes"?

[[v19-11-2]]

^<<v19-11-2,2>>^ Vejam! Os ímpios preparam os seus arcos; colocam as flechas contra as cordas para das sombras as atirarem nos retos de coração.

[[v19-11-3]]

^<<v19-11-3,3>>^ Quando os fundamentos estão sendo destruídos, que pode fazer o justo?

[[v19-11-4]]

^<<v19-11-4,4>>^ O Senhor está no seu santo templo; o Senhor tem o seu trono nos céus. Seus olhos observam; seus olhos examinam os filhos dos homens.

[[v19-11-5]]

^<<v19-11-5,5>>^ O Senhor prova o justo, mas o ímpio e a quem ama a injustiça, a sua alma odeia.

[[v19-11-6]]

^<<v19-11-6,6>>^ Sobre os ímpios ele fará chover brasas ardentes e enxofre incandescente; vento ressecante é o que terão.

[[v19-11-7]]

^<<v19-11-7,7>>^ Pois o Senhor é justo, e ama a justiça; os retos verão a sua face.

'''

xref:019-salmos/019-salmos-010.adoc#v19-10-0[&#60; Capítulo Anterior] | <<v19-11-0,Topo>> | xref:019-salmos/019-salmos-012.adoc#v19-12-0[Próximo Capítulo &#62;]