include::./index.adoc[]

[[v19-85-0]]
=== Salmos, 85
// nvi ?, NVI - Nova Versão Internacional

[[v19-85-1]]

^<<v19-85-1,1>>^ Foste favorável à tua terra, ó Senhor; trouxeste restauração a Jacó.

[[v19-85-2]]

^<<v19-85-2,2>>^ Perdoaste a culpa do teu povo e cobriste todos os seus pecados. Pausa

[[v19-85-3]]

^<<v19-85-3,3>>^ Retiraste todo o teu furor e te afastaste da tua ira tremenda.

[[v19-85-4]]

^<<v19-85-4,4>>^ Restaura-nos mais uma vez, ó Deus, nosso Salvador, e desfaze o teu furor para conosco.

[[v19-85-5]]

^<<v19-85-5,5>>^ Ficarás indignado conosco para sempre? Prolongarás a tua ira por todas as gerações?

[[v19-85-6]]

^<<v19-85-6,6>>^ Acaso não nos renovarás a vida, a fim de que o teu povo se alegre em ti?

[[v19-85-7]]

^<<v19-85-7,7>>^ Mostra-nos o teu amor, ó Senhor, e concede-nos a tua salvação!

[[v19-85-8]]

^<<v19-85-8,8>>^ Eu ouvirei o que Deus, o Senhor, disse: Ele promete paz ao seu povo, aos seus fiéis! Não voltem eles à insensatez!

[[v19-85-9]]

^<<v19-85-9,9>>^ Perto está a salvação que ele trará aos que o temem, e a sua glória habitará em nossa terra.

[[v19-85-10]]

^<<v19-85-10,10>>^ O amor e a fidelidade se encontrarão; a justiça e a paz se beijarão.

[[v19-85-11]]

^<<v19-85-11,11>>^ A fidelidade brotará da terra, e a justiça descerá dos céus.

[[v19-85-12]]

^<<v19-85-12,12>>^ O Senhor nos trará bênçãos, e a nossa terra dará a sua colheita.

[[v19-85-13]]

^<<v19-85-13,13>>^ A justiça irá adiante dele e preparará o caminho para os seus passos.

'''

xref:019-salmos/019-salmos-084.adoc#v19-84-0[&#60; Capítulo Anterior] | <<v19-85-0,Topo>> | xref:019-salmos/019-salmos-086.adoc#v19-86-0[Próximo Capítulo &#62;]