include::./index.adoc[]

[[v55-1-0]]
=== 2 Timóteo, 1
// nvi ?, NVI - Nova Versão Internacional

[[v55-1-1]]

^<<v55-1-1,1>>^ Paulo, apóstolo de Cristo Jesus pela vontade de Deus, segundo a promessa da vida que está em Cristo Jesus,

[[v55-1-2]]

^<<v55-1-2,2>>^ a Timóteo, meu amado filho: Graça, misericórdia e paz da parte de Deus Pai e de Cristo Jesus, nosso Senhor.

[[v55-1-3]]

^<<v55-1-3,3>>^ Dou graças a Deus, a quem sirvo com a consciência limpa, como o serviram os meus antepassados, ao lembrar-me constantemente de você noite e dia em minhas orações.

[[v55-1-4]]

^<<v55-1-4,4>>^ Lembro-me das suas lágrimas e desejo muito vê-lo, para que a minha alegria seja completa.

[[v55-1-5]]

^<<v55-1-5,5>>^ Recordo-me da sua fé não fingida, que primeiro habitou em sua avó Lóide e em sua mãe Eunice, e estou convencido de que também habita em você.

[[v55-1-6]]

^<<v55-1-6,6>>^ Por essa razão, torno a lembrar-lhe que mantenha viva a chama do dom de Deus que está em você mediante a imposição das minhas mãos.

[[v55-1-7]]

^<<v55-1-7,7>>^ Pois Deus não nos deu espírito de covardia, mas de poder, de amor e de equilíbrio.

[[v55-1-8]]

^<<v55-1-8,8>>^ Portanto, não se envergonhe de testemunhar do Senhor, nem de mim, que sou prisioneiro dele, mas suporte comigo os sofrimentos pelo evangelho, segundo o poder de Deus,

[[v55-1-9]]

^<<v55-1-9,9>>^ que nos salvou e nos chamou com uma santa vocação, não em virtude das nossas obras, mas por causa da sua própria determinação e graça. Esta graça nos foi dada em Cristo Jesus desde os tempos eternos,

[[v55-1-10]]

^<<v55-1-10,10>>^ sendo agora revelada pela manifestação de nosso Salvador, Cristo Jesus. Ele tornou inoperante a morte e trouxe à luz a vida e a imortalidade por meio do evangelho.

[[v55-1-11]]

^<<v55-1-11,11>>^ Deste evangelho fui constituído pregador, apóstolo e mestre.

[[v55-1-12]]

^<<v55-1-12,12>>^ Por essa causa também sofro, mas não me envergonho, porque sei em quem tenho crido e estou bem certo de que ele é poderoso para guardar o meu depósito até aquele dia.

[[v55-1-13]]

^<<v55-1-13,13>>^ Retenha, com fé e amor em Cristo Jesus, o modelo da sã doutrina que você ouviu de mim.

[[v55-1-14]]

^<<v55-1-14,14>>^ Quanto ao bom depósito, guarde-o por meio do Espírito Santo que habita em nós.

[[v55-1-15]]

^<<v55-1-15,15>>^ Você sabe que todos os da província da Ásia me abandonaram, inclusive Fígelo e Hermógenes.

[[v55-1-16]]

^<<v55-1-16,16>>^ O Senhor conceda misericórdia à casa de Onesíforo, porque muitas vezes ele me reanimou e não se envergonhou por eu estar preso;

[[v55-1-17]]

^<<v55-1-17,17>>^ pelo contrário, quando chegou a Roma procurou-me diligentemente até me encontrar.

[[v55-1-18]]

^<<v55-1-18,18>>^ Conceda-lhe o Senhor que, naquele dia, encontre misericórdia da parte do Senhor! Você sabe muito bem quantos serviços ele me prestou em Éfeso.

'''

xref:054-1-timoteo/054-1-timoteo-006.adoc#v54-6-0[&#60; Capítulo Anterior] | <<v55-1-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-002.adoc#v55-2-0[Próximo Capítulo &#62;]