include::./index.adoc[]

[[v55-4-0]]
=== 2 Timóteo, 4
// nvi ?, NVI - Nova Versão Internacional

[[v55-4-1]]

^<<v55-4-1,1>>^ Na presença de Deus e de Cristo Jesus, que há de julgar os vivos e os mortos por sua manifestação e por seu Reino, eu o exorto solenemente:

[[v55-4-2]]

^<<v55-4-2,2>>^ Pregue a palavra, esteja preparado a tempo e fora de tempo, repreenda, corrija, exorte com toda a paciência e doutrina.

[[v55-4-3]]

^<<v55-4-3,3>>^ Pois virá o tempo em que não suportarão a sã doutrina; pelo contrário, sentindo coceira nos ouvidos, segundo os seus próprios desejos juntarão mestres para si mesmos.

[[v55-4-4]]

^<<v55-4-4,4>>^ Eles se recusarão a dar ouvidos à verdade, voltando-se para os mitos.

[[v55-4-5]]

^<<v55-4-5,5>>^ Você, porém, seja sóbrio em tudo, suporte os sofrimentos, faça a obra de um evangelista, cumpra plenamente o seu ministério.

[[v55-4-6]]

^<<v55-4-6,6>>^ Eu já estou sendo derramado como uma oferta de bebida. Está próximo o tempo da minha partida.

[[v55-4-7]]

^<<v55-4-7,7>>^ Combati o bom combate, terminei a corrida, guardei a fé.

[[v55-4-8]]

^<<v55-4-8,8>>^ Agora me está reservada a coroa da justiça, que o Senhor, justo Juiz, me dará naquele dia; e não somente a mim, mas também a todos os que amam a sua vinda.

[[v55-4-9]]

^<<v55-4-9,9>>^ Procure vir logo ao meu encontro,

[[v55-4-10]]

^<<v55-4-10,10>>^ pois Demas, amando este mundo, abandonou-me e foi para Tessalônica. Crescente foi para a Galácia, e Tito, para a Dalmácia.

[[v55-4-11]]

^<<v55-4-11,11>>^ Só Lucas está comigo. Traga Marcos com você, porque ele me é útil para o ministério.

[[v55-4-12]]

^<<v55-4-12,12>>^ Enviei Tíquico a Éfeso.

[[v55-4-13]]

^<<v55-4-13,13>>^ Quando você vier, traga a capa que deixei na casa de Carpo, em Trôade, e os meus livros, especialmente os pergaminhos.

[[v55-4-14]]

^<<v55-4-14,14>>^ Alexandre, o ferreiro, causou-me muitos males. O Senhor lhe dará a retribuição pelo que fez.

[[v55-4-15]]

^<<v55-4-15,15>>^ Previna-se contra ele, porque se opôs fortemente às nossas palavras.

[[v55-4-16]]

^<<v55-4-16,16>>^ Na minha primeira defesa, ninguém apareceu para me apoiar; todos me abandonaram. Que isso não lhes cobrado.

[[v55-4-17]]

^<<v55-4-17,17>>^ Mas o Senhor permaneceu ao meu lado e me deu forças, para que por mim a mensagem fosse plenamente proclamada, e todos os gentios a ouvissem. E eu fui libertado da boca do leão.

[[v55-4-18]]

^<<v55-4-18,18>>^ O Senhor me livrará de toda obra maligna e me levará a salvo para o seu Reino celestial. A ele seja a glória para todo o sempre. Amém.

[[v55-4-19]]

^<<v55-4-19,19>>^ Saudações a Priscila e Áqüila, e à casa de Onesíforo.

[[v55-4-20]]

^<<v55-4-20,20>>^ Erasto permaneceu em Corinto, mas deixei Trófimo doente em Mileto.

[[v55-4-21]]

^<<v55-4-21,21>>^ Procure vir antes do inverno. Êubulo, Prudente, Lino, Cláudia e todos os irmãos enviam-lhe saudações.

[[v55-4-22]]

^<<v55-4-22,22>>^ O Senhor seja com o seu espírito. A graça seja com vocês.

'''

xref:055-2-timoteo/055-2-timoteo-003.adoc#v55-3-0[&#60; Capítulo Anterior] | <<v55-4-0,Topo>> | xref:056-tito/056-tito-001.adoc#v56-1-0[Próximo Capítulo &#62;]