include::./index.adoc[]

[[v55-2-0]]
=== 2 Timóteo, 2
// nvi ?, NVI - Nova Versão Internacional

[[v55-2-1]]

^<<v55-2-1,1>>^ Portanto, você, meu filho, fortifique-se na graça que há em Cristo Jesus.

[[v55-2-2]]

^<<v55-2-2,2>>^ E as coisas que me ouviu dizer na presença de muitas testemunhas, confie a homens fiéis que sejam também capazes de ensinar a outros.

[[v55-2-3]]

^<<v55-2-3,3>>^ Suporte comigo os sofrimentos, como bom soldado de Cristo Jesus.

[[v55-2-4]]

^<<v55-2-4,4>>^ Nenhum soldado se deixa envolver pelos negócios da vida civil, já que deseja agradar aquele que o alistou.

[[v55-2-5]]

^<<v55-2-5,5>>^ Semelhantemente, nenhum atleta é coroado como vencedor, se não competir de acordo com as regras.

[[v55-2-6]]

^<<v55-2-6,6>>^ O lavrador que trabalha arduamente deve ser o primeiro a participar dos frutos da colheita.

[[v55-2-7]]

^<<v55-2-7,7>>^ Reflita no que estou dizendo, pois o Senhor lhe dará entendimento em tudo.

[[v55-2-8]]

^<<v55-2-8,8>>^ Lembre-se de Jesus Cristo, ressuscitado dos mortos, descendente de Davi, conforme o meu evangelho,

[[v55-2-9]]

^<<v55-2-9,9>>^ pelo qual sofro a ponto de estar preso como criminoso; contudo a palavra de Deus não está presa.

[[v55-2-10]]

^<<v55-2-10,10>>^ Por isso, tudo suporto por causa dos eleitos, para que também eles alcancem a salvação que está em Cristo Jesus, com glória eterna.

[[v55-2-11]]

^<<v55-2-11,11>>^ Esta palavra é digna de confiança: Se morremos com ele, com ele também viveremos;

[[v55-2-12]]

^<<v55-2-12,12>>^ se perseveramos, com ele também reinaremos. Se o negamos, ele também nos negará;

[[v55-2-13]]

^<<v55-2-13,13>>^ se somos infiéis, ele permanece fiel, pois não pode negar-se a si mesmo.

[[v55-2-14]]

^<<v55-2-14,14>>^ Continue a lembrar essas coisas a todos, advertindo-os solenemente diante de Deus, para que não se envolvam em discussões acerca de palavras; isso não tem proveito, e serve apenas para perverter os ouvintes.

[[v55-2-15]]

^<<v55-2-15,15>>^ Procure apresentar-se a Deus aprovado, como obreiro que não tem do que se envergonhar, que maneja corretamente a palavra da verdade.

[[v55-2-16]]

^<<v55-2-16,16>>^ Evite as conversas inúteis e profanas, pois os que se dão a isso prosseguem cada vez mais para a impiedade.

[[v55-2-17]]

^<<v55-2-17,17>>^ O ensino deles alastra como câncer; entre eles estão Himeneu e Fileto.

[[v55-2-18]]

^<<v55-2-18,18>>^ Estes se desviaram da verdade, dizendo que a ressurreição já aconteceu, e assim a alguns pervertem a fé.

[[v55-2-19]]

^<<v55-2-19,19>>^ Entretanto, o firme fundamento de Deus permanece inabalável e selado com esta inscrição: "O Senhor conhece quem lhe pertence" e "afaste-se da iniqüidade todo aquele que confessa o nome do Senhor".

[[v55-2-20]]

^<<v55-2-20,20>>^ Numa grande casa há vasos não apenas de ouro e prata, mas também de madeira e barro; alguns para fins honrosos, outros para fins desonrosos.

[[v55-2-21]]

^<<v55-2-21,21>>^ Se alguém se purificar dessas coisas, será vaso para honra, santificado, útil para o Senhor e preparado para toda boa obra.

[[v55-2-22]]

^<<v55-2-22,22>>^ Fuja dos desejos malignos da juventude e siga a justiça, a fé, o amor e a paz, juntamente com os que, de coração puro, invocam o Senhor.

[[v55-2-23]]

^<<v55-2-23,23>>^ Evite as controvérsias tolas e fúteis, pois você sabe que acabam em brigas.

[[v55-2-24]]

^<<v55-2-24,24>>^ Ao servo do Senhor não convém brigar mas, sim, ser amável para com todos, apto para ensinar, paciente.

[[v55-2-25]]

^<<v55-2-25,25>>^ Deve corrigir com mansidão os que se lhe opõem, na esperança de que Deus lhes conceda o arrependimento, levando-os ao conhecimento da verdade,

[[v55-2-26]]

^<<v55-2-26,26>>^ para que assim voltem à sobriedade e escapem da armadilha do diabo, que os aprisionou para fazerem a sua vontade.

'''

xref:055-2-timoteo/055-2-timoteo-001.adoc#v55-1-0[&#60; Capítulo Anterior] | <<v55-2-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-003.adoc#v55-3-0[Próximo Capítulo &#62;]