include::./index.adoc[]

[[v55-3-0]]
=== 2 Timóteo, 3
// nvi ?, NVI - Nova Versão Internacional

[[v55-3-1]]

^<<v55-3-1,1>>^ Saiba disto: nos últimos dias sobrevirão tempos terríveis.

[[v55-3-2]]

^<<v55-3-2,2>>^ Os homens serão egoístas, avarentos, presunçosos, arrogantes, blasfemos, desobedientes aos pais, ingratos, ímpios,

[[v55-3-3]]

^<<v55-3-3,3>>^ sem amor pela família, irreconciliáveis, caluniadores, sem domínio próprio, cruéis, inimigos do bem,

[[v55-3-4]]

^<<v55-3-4,4>>^ traidores, precipitados, soberbos, mais amantes dos prazeres do que amigos de Deus,

[[v55-3-5]]

^<<v55-3-5,5>>^ tendo aparência de piedade, mas negando o seu poder. Afaste-se também destes.

[[v55-3-6]]

^<<v55-3-6,6>>^ São estes os que se introduzem pelas casas e conquistam mulherzinhas sobrecarregadas de pecados, as quais se deixam levar por toda espécie de desejos.

[[v55-3-7]]

^<<v55-3-7,7>>^ Elas estão sempre aprendendo, mas não conseguem nunca de chegar ao conhecimento da verdade.

[[v55-3-8]]

^<<v55-3-8,8>>^ Como Janes e Jambres se opuseram a Moisés, esses também resistem à verdade. A mente deles é depravada; são reprovados na fé.

[[v55-3-9]]

^<<v55-3-9,9>>^ Não irão longe, porém; como no caso daqueles, a sua insensatez se tornará evidente a todos.

[[v55-3-10]]

^<<v55-3-10,10>>^ Mas você tem seguido de perto o meu ensino, a minha conduta, o meu propósito, a minha fé, a minha paciência, o meu amor, a minha perseverança,

[[v55-3-11]]

^<<v55-3-11,11>>^ as perseguições e os sofrimentos que enfrentei, coisas que me aconteceram em Antioquia, Icônio e Listra. Quanta perseguição suportei! Mas, de todas essas coisas o Senhor me livrou!

[[v55-3-12]]

^<<v55-3-12,12>>^ De fato, todos os que desejam viver piedosamente em Cristo Jesus serão perseguidos.

[[v55-3-13]]

^<<v55-3-13,13>>^ Contudo, os perversos e impostores irão de mal a pior, enganando e sendo enganados.

[[v55-3-14]]

^<<v55-3-14,14>>^ Quanto a você, porém, permaneça nas coisas que aprendeu e das quais tem convicção, pois você sabe de quem o aprendeu.

[[v55-3-15]]

^<<v55-3-15,15>>^ Porque desde criança você conhece as sagradas letras, que são capazes de torná-lo sábio para a salvação mediante a fé em Cristo Jesus.

[[v55-3-16]]

^<<v55-3-16,16>>^ Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção e para a instrução na justiça,

[[v55-3-17]]

^<<v55-3-17,17>>^ para que o homem de Deus seja apto e plenamente preparado para toda boa obra.

'''

xref:055-2-timoteo/055-2-timoteo-002.adoc#v55-2-0[&#60; Capítulo Anterior] | <<v55-3-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-004.adoc#v55-4-0[Próximo Capítulo &#62;]