include::./index.adoc[]

[[v15-5-0]]
=== Esdras, 5
// nvi ?, NVI - Nova Versão Internacional

[[v15-5-1]]

^<<v15-5-1,1>>^ Ora, os profetas Ageu e Zacarias, descendente de Ido, profetizaram aos judeus de Judá e de Jerusalém, em nome do Deus de Israel, que estava sobre eles.

[[v15-5-2]]

^<<v15-5-2,2>>^ Então Zorobabel, filho de Sealtiel, e Jesua, filho de Jozadaque, começaram a reconstruir o templo de Deus em Jerusalém. E os profetas de Deus estavam com eles e os ajudavam.

[[v15-5-3]]

^<<v15-5-3,3>>^ Naquela época Tatenai, governador do território a oeste do Eufrates, Setar-Bozenai e seus companheiros foram perguntar a eles: "Quem os autorizou a reconstruir este templo e estes muros?

[[v15-5-4]]

^<<v15-5-4,4>>^ E como se chamam os homens que estão construíndo este edifício? "

[[v15-5-5]]

^<<v15-5-5,5>>^ Mas os olhos do seu Deus estavam sobre os líderes dos judeus, e eles não foram impedidos de trabalhar até que um relatório fosse enviado a Dario e dele se recebesse uma ordem oficial a respeito do assunto.

[[v15-5-6]]

^<<v15-5-6,6>>^ Temos aqui uma cópia da carta que Tatenai, governador do território a oeste do Eufrates, Setar-Bozenai e seus companheiros, os funcionários do oeste do Eufrates, enviaram ao rei Dario.

[[v15-5-7]]

^<<v15-5-7,7>>^ O relatório que lhe enviaram dizia o seguinte: "Ao rei Dario: Paz e prosperidade!

[[v15-5-8]]

^<<v15-5-8,8>>^ Informamos ao rei que fomos à província de Judá, ao templo do grande Deus. O povo o está reconstruindo com grandes pedras e colocando vigas de madeira nas paredes. A obra está sendo executada com diligência e está tendo rápido progresso.

[[v15-5-9]]

^<<v15-5-9,9>>^ Então perguntamos aos líderes: Quem os autorizou a reconstruir este templo e estes muros?

[[v15-5-10]]

^<<v15-5-10,10>>^ Também perguntamos os nomes dos líderes deles, para que registrássemos para a tua informação.

[[v15-5-11]]

^<<v15-5-11,11>>^ Esta é a resposta que nos deram: Somos servos do Deus dos céus e da terra, e estamos reconstruindo o templo construído há muitos anos, templo que foi construído e terminado por um grande rei de Israel.

[[v15-5-12]]

^<<v15-5-12,12>>^ Mas, visto que os nossos antepassados irritaram o Deus dos céus, ele os entregou nas mãos do babilônio Nabucodonosor, rei da Babilônia, que destruiu este templo e deportou o povo para a Babilônia.

[[v15-5-13]]

^<<v15-5-13,13>>^ Contudo, no seu primeiro ano como rei de Babilônia, o rei Ciro emitiu um decreto ordenando a reconstrução desta casa de Deus.

[[v15-5-14]]

^<<v15-5-14,14>>^ Ele até mesmo tirou do templo da Babilônia os utensílios de ouro e de prata da casa de Deus, os quais Nabucodonosor havia tirado do templo de Jerusalém e levara para o templo da Babilônia. O rei Ciro os confiou a um homem chamado Sesbazar, ao qual tinha nomeado governador,

[[v15-5-15]]

^<<v15-5-15,15>>^ e lhe disse: ‘Leve estes utensílios e coloque-os no templo de Jerusalém, e reconstrua a casa de Deus em seu antigo local’.

[[v15-5-16]]

^<<v15-5-16,16>>^ Então Sesbazar veio e lançou os alicerces do templo de Deus em Jerusalém. Desde aquele dia ela tem estado em construção, mas ainda não foi concluída.

[[v15-5-17]]

^<<v15-5-17,17>>^ Agora, se for do agrado do rei que se faça uma pesquisa nos arquivos reais da Babilônia para verificar se o rei Ciro de fato emitiu um decreto ordenando a reconstrução da casa de Deus de Jerusalém. E que o rei nos envie sua decisão sobre o assunto".

'''

xref:015-esdras/015-esdras-004.adoc#v15-4-0[&#60; Capítulo Anterior] | <<v15-5-0,Topo>> | xref:015-esdras/015-esdras-006.adoc#v15-6-0[Próximo Capítulo &#62;]