include::./index.adoc[]

[[v15-10-0]]
=== Esdras, 10
// nvi ?, NVI - Nova Versão Internacional

[[v15-10-1]]

^<<v15-10-1,1>>^ Enquanto Esdras estava orando e confessando, chorando prostrado diante do templo de Deus, uma grande multidão de israelitas, homens, mulheres e crianças, reuniram-se em volta dele. Eles também choravam amargamente.

[[v15-10-2]]

^<<v15-10-2,2>>^ Então Secanias, filho de Jeiel, um dos descendentes de Elão, disse a Esdras: "Fomos infiéis ao nosso Deus quando nos casamos com mulheres estrangeiras procedentes dos povos vizinhos. Mas, apesar disso, ainda há esperança para Israel.

[[v15-10-3]]

^<<v15-10-3,3>>^ Façamos agora um acordo diante do nosso Deus, e mandemos de volta todas essas mulheres e seus filhos, segundo o conselho do meu senhor e daqueles que tremem diante dos mandamentos de nosso Deus. Que isso seja feito em conformidade com a Lei.

[[v15-10-4]]

^<<v15-10-4,4>>^ Levante-se! Esta questão está em suas mãos, mas nós o apoiaremos. Tenha coragem e mãos à obra! "

[[v15-10-5]]

^<<v15-10-5,5>>^ Esdras levantou-se e fez os sacerdotes principais e os levitas e todo o Israel jurarem que fariam o que fora sugerido. E eles juraram.

[[v15-10-6]]

^<<v15-10-6,6>>^ Então Esdras retirou-se de diante do templo de Deus e foi para o quarto de Joanã, filho de Eliasibe. Enquanto esteve ali, não comeu nem bebeu nada, lamentando a infidelidade dos exilados.

[[v15-10-7]]

^<<v15-10-7,7>>^ Fez-se então uma proclamação em todo o Judá e em Jerusalém convocando todos os exilados a se reunirem em Jerusalém.

[[v15-10-8]]

^<<v15-10-8,8>>^ Os líderes e as demais autoridades tinham decidido que aquele que não viesse no prazo de três dias perderia todos os seus bens e seria excluído da comunidade dos exilados.

[[v15-10-9]]

^<<v15-10-9,9>>^ No prazo de três dias, todos os homens de Judá e de Benjamim tinham se reunido em Jerusalém, e no vigésimo dia do nono mês todo o povo estava sentado na praça que ficava diante do templo de Deus. Todos estavam profundamente abatidos por causa do motivo da reunião e também porque chovia muito.

[[v15-10-10]]

^<<v15-10-10,10>>^ Então o sacerdote Esdras levantou-se e disse-lhes: "Vocês têm sido infiéis! Vocês se casaram com mulheres estrangeiras, aumentando a culpa de Israel.

[[v15-10-11]]

^<<v15-10-11,11>>^ Agora confessem ao Senhor, o Deus dos seus antepassados, e façam a vontade dele. Separem-se dos povos vizinhos e das suas mulheres estrangeiras".

[[v15-10-12]]

^<<v15-10-12,12>>^ A comunidade toda respondeu em voz alta: "Você está certo! Devemos fazer o que você diz.

[[v15-10-13]]

^<<v15-10-13,13>>^ Mas há muita gente aqui, e esta é a estação das chuvas; por isso não podemos ficar do lado de fora. Além disso, essa questão não pode ser resolvida em um dia ou dois, porquanto foram muitos os que assim pecaram.

[[v15-10-14]]

^<<v15-10-14,14>>^ Que os nossos líderes decidam por toda a assembléia. Então que cada um de nossas cidades que se casou com mulher estrangeira venha numa data marcada, acompanhado dos líderes e juízes de cada cidade, para que se afaste de nós o furor da ira de nosso Deus por causa deste pecado".

[[v15-10-15]]

^<<v15-10-15,15>>^ Somente Jônatas, filho de Asael, e Jaseías, filho de Ticvá, apoiados por Mesulão e o levita Sabetai, discordaram.

[[v15-10-16]]

^<<v15-10-16,16>>^ E assim os exilados fizeram conforme proposto. O sacerdote Esdras escolheu chefes de famílias, um de cada grupo de famílias, todos eles chamados por nome. E no dia primeiro do décimo mês eles se assentaram para investigar cada caso.

[[v15-10-17]]

^<<v15-10-17,17>>^ No dia primeiro do primeiro mês terminaram de investigar todos os casos de casamento com mulheres estrangeiras.

[[v15-10-18]]

^<<v15-10-18,18>>^ Entre os descendentes dos sacerdotes, estes foram os que se casaram com mulheres estrangeiras: Dentre os descendentes de Jesua, filho de Jozadaque, e seus irmãos Maaséias, Eliézer, Jaribe e Gedalias.

[[v15-10-19]]

^<<v15-10-19,19>>^ Todos eles apertaram as mãos em sinal de garantia que iam despedir suas mulheres, e cada um apresentou um carneiro do rebanho como oferta por sua culpa.

[[v15-10-20]]

^<<v15-10-20,20>>^ Dentre os descendentes de Imer: Hanani e Zebadias.

[[v15-10-21]]

^<<v15-10-21,21>>^ Dentre os descendentes de Harim: Maaséias, Elias, Semaías, Jeiel e Uzias.

[[v15-10-22]]

^<<v15-10-22,22>>^ Dentre os descendentes de Pasur: Elioenai, Maaséias, Ismael, Natanael, Jozabade e Eleasa.

[[v15-10-23]]

^<<v15-10-23,23>>^ Dentre os levitas: Jozabade, Simei, Quelaías, também chamado Quelita, Petaías, Judá e Eliézer.

[[v15-10-24]]

^<<v15-10-24,24>>^ Dentre os cantores: Eliasibe. Dentre os porteiros: Salum, Telém e Uri.

[[v15-10-25]]

^<<v15-10-25,25>>^ E dentre os outros israelitas: Dentre os descendentes de Parós: Ramias, Jezias, Malquias, Miamim, Eleazar, Malquias e Benaia.

[[v15-10-26]]

^<<v15-10-26,26>>^ Dentre os descendentes de Elão: Matanias, Zacarias, Jeiel, Abdi, Jeremote e Elias.

[[v15-10-27]]

^<<v15-10-27,27>>^ Dentre os descendentes de Zatu: Elioenai, Eliasibe, Matanias, Jeremote, Zabade e Aziza.

[[v15-10-28]]

^<<v15-10-28,28>>^ Dentre os descendentes de Bebai: Joanã, Hananias, Zabai e Atlai.

[[v15-10-29]]

^<<v15-10-29,29>>^ Dentre os descendentes de Bani: Mesulão, Maluque, Adaías, Jasube, Seal e Jeremote.

[[v15-10-30]]

^<<v15-10-30,30>>^ Dentre os descendentes de Paate-Moabe: Adna, Quelal, Benaia, Maaséias, Matanias, Bezalel, Binui e Manassés.

[[v15-10-31]]

^<<v15-10-31,31>>^ Dentre os descendentes de Harim: Eliézer, Issias, Malquias, Semaías, Simeão,

[[v15-10-32]]

^<<v15-10-32,32>>^ Benjamim, Maluque e Semarias.

[[v15-10-33]]

^<<v15-10-33,33>>^ Dentre os descendentes de Hasum: Matenai, Matatá, Zabade, Elifelete, Jeremai, Manassés e Simei.

[[v15-10-34]]

^<<v15-10-34,34>>^ Dentre os descendentes de Bani: Maadai, Anrão, Uel,

[[v15-10-35]]

^<<v15-10-35,35>>^ Benaia, Bedias, Queluí,

[[v15-10-36]]

^<<v15-10-36,36>>^ Vanias, Meremote, Eliasibe,

[[v15-10-37]]

^<<v15-10-37,37>>^ Matanias, Matenai e Jaasai.

[[v15-10-38]]

^<<v15-10-38,38>>^ Dentre os descendentes de Binui: Simei,

[[v15-10-39]]

^<<v15-10-39,39>>^ Selemias, Natã, Adaías,

[[v15-10-40]]

^<<v15-10-40,40>>^ Macnadbai, Sasai, Sarai,

[[v15-10-41]]

^<<v15-10-41,41>>^ Azareel, Selemias, Semarias,

[[v15-10-42]]

^<<v15-10-42,42>>^ Salum, Amarias e José.

[[v15-10-43]]

^<<v15-10-43,43>>^ Dentre os descendentes de Nebo: Jeiel, Matitias, Zabade, Zebina, Jadai, Joel e Benaia.

[[v15-10-44]]

^<<v15-10-44,44>>^ Todos esses tinham se casado com mulheres estrangeiras, e alguns deles tiveram filhos dessas mulheres.

'''

xref:015-esdras/015-esdras-009.adoc#v15-9-0[&#60; Capítulo Anterior] | <<v15-10-0,Topo>> | xref:016-neemias/016-neemias-001.adoc#v16-1-0[Próximo Capítulo &#62;]