include::./index.adoc[]

[[v15-1-0]]
=== Esdras, 1
// nvi ?, NVI - Nova Versão Internacional

[[v15-1-1]]

^<<v15-1-1,1>>^ No primeiro ano do reinado de Ciro, rei da Pérsia, a fim de que se cumprisse a palavra do Senhor falada por Jeremias, o Senhor despertou o coração de Ciro, rei da Pérsia, para redigir uma proclamação e divulgá-la em todo o seu reino, nestes termos:

[[v15-1-2]]

^<<v15-1-2,2>>^ "Assim diz Ciro, rei da Pérsia: "O Senhor, o Deus dos céus, deu-me todos os reinos da terra e designou-me para construir um templo para ele em Jerusalém de Judá.

[[v15-1-3]]

^<<v15-1-3,3>>^ Qualquer do seu povo que esteja entre vocês, que o seu Deus esteja com ele, e que vá a Jerusalém de Judá reconstruir o templo do Senhor, o Deus de Israel, o Deus que em Jerusalém tem a sua morada.

[[v15-1-4]]

^<<v15-1-4,4>>^ E que todo sobrevivente, seja qual for o lugar em que está vivendo, receba dos que ali vivem em prata, ouro, bens e animais; e ofertas voluntárias para o templo de Deus em Jerusalém".

[[v15-1-5]]

^<<v15-1-5,5>>^ Então os líderes das famílias de Judá e de Benjamim, como também os sacerdotes e os levitas, todos aqueles cujo coração Deus despertou, dispuseram-se a ir para Jerusalém e a construir o templo do Senhor.

[[v15-1-6]]

^<<v15-1-6,6>>^ Todos os seus vizinhos os ajudaram, trazendo-lhes utensílios de prata e ouro, bens, animais, e presentes valiosos, além de todas as ofertas voluntárias que fizeram.

[[v15-1-7]]

^<<v15-1-7,7>>^ Além disso, o rei Ciro mandou tirar os utensílios pertencentes ao templo do Senhor, os quais Nabucodonosor tinha levado de Jerusalém e colocado no templo do seu deus.

[[v15-1-8]]

^<<v15-1-8,8>>^ Ciro, rei da Pérsia, ordenou que fossem tirados pelo tesoureiro Mitredate, que os enumerou e os entregou a Sesbazar, governador de Judá.

[[v15-1-9]]

^<<v15-1-9,9>>^ O total foi o seguinte: 30 tigelas de ouro, 1. 000 tigelas de prata, 29 panelas de prata,

[[v15-1-10]]

^<<v15-1-10,10>>^ 30 bacias de ouro, 410 bacias de prata de qualidade inferior e 1. 000 outros objetos

[[v15-1-11]]

^<<v15-1-11,11>>^ Ao todo foram, na verdade, cinco mil e quatrocentos utensílos de ouro e de prata. Sesbazar trouxe tudo isso consigo quando os exilados vieram da Babilônia para Jerusalém.

'''

xref:014-2-cronicas/014-2-cronicas-036.adoc#v14-36-0[&#60; Capítulo Anterior] | <<v15-1-0,Topo>> | xref:015-esdras/015-esdras-002.adoc#v15-2-0[Próximo Capítulo &#62;]