include::./index.adoc[]

[[v15-8-0]]
=== Esdras, 8
// nvi ?, NVI - Nova Versão Internacional

[[v15-8-1]]

^<<v15-8-1,1>>^ Estes são os chefes de suas famílias e dos que com eles foram registrados, os quais saíram comigo da Babilônia durante o reinado do rei Artaxerxes:

[[v15-8-2]]

^<<v15-8-2,2>>^ dos descendentes de Finéias, Gérson; dos descendentes de Itamar, Daniel; dos descendentes de Davi, Hatus,

[[v15-8-3]]

^<<v15-8-3,3>>^ dos descendentes de Secanias; dos descendentes de Parós, Zacarias, sendo registrados com ele 150 homens;

[[v15-8-4]]

^<<v15-8-4,4>>^ dos descendentes de Paate-Moabe, Elioenai, filho de Zeraías, e com ele 200 homens;

[[v15-8-5]]

^<<v15-8-5,5>>^ dos descendentes de Zatu, Secanias, filho de Jaaziel, e com ele 300 homens;

[[v15-8-6]]

^<<v15-8-6,6>>^ dos descendentes de Adim, Ebede, filho de Jônatas, e com ele 50 homens;

[[v15-8-7]]

^<<v15-8-7,7>>^ dos descendentes de Elão, Jesaías, filho de Atalias, e com ele 70 homens;

[[v15-8-8]]

^<<v15-8-8,8>>^ dos descendentes de Sefatias, Zebadias, filho de Micael, e com ele 80 homens;

[[v15-8-9]]

^<<v15-8-9,9>>^ dos descendentes de Joabe, Obadias, filho de Jeiel, e com ele 218 homens;

[[v15-8-10]]

^<<v15-8-10,10>>^ dos descendentes de Bani, Selomite, filho de Josifias, e com ele 160 homens;

[[v15-8-11]]

^<<v15-8-11,11>>^ dos descendentes de Bebai, Zacarias, filho de Bebai, e com ele 28 homens;

[[v15-8-12]]

^<<v15-8-12,12>>^ dos descendentes de Azgade, Joanã, filho de Hacatã, e com ele 110 homens;

[[v15-8-13]]

^<<v15-8-13,13>>^ dos descendentes de Adonicão, os últimos que chegaram, Elifelete, Jeiel e Semaías, e com eles 60 homens;

[[v15-8-14]]

^<<v15-8-14,14>>^ dos descendentes de Bigvai, Utai e Zabude, e com eles 70 homens.

[[v15-8-15]]

^<<v15-8-15,15>>^ Eu os reuni junto ao canal que corre para Aava, e acampamos ali por três dias. Quando passei em revista o povo e os sacerdotes, não encontrei nenhum levita.

[[v15-8-16]]

^<<v15-8-16,16>>^ Por isso convoquei Eliézer, Ariel, Semaías, Elnatã, Jaribe, Elnatã, Natã, Zacarias e Mesulão, que eram líderes, e Joiaribe e Natã, que eram homens sábios,

[[v15-8-17]]

^<<v15-8-17,17>>^ e eu os enviei a Ido, o líder de Casifia. Eu lhes falei o que deveriam dizer a Ido e aos parentes dele, os servidores do templo, em Casifia, para que nos trouxessem servidores para o templo de nosso Deus.

[[v15-8-18]]

^<<v15-8-18,18>>^ Como a bondosa mão de Deus estava sobre nós, eles nos trouxeram Serebias, homem capaz, dentre os descendentes de Mali, filho de Levi, neto de Israel, e os filhos e irmãos de Serebias, dezoito homens;

[[v15-8-19]]

^<<v15-8-19,19>>^ e também Hasabias, acompanhado de Jesaías, dentre os descendentes de Merari, e seus irmãos e filhos, vinte homens.

[[v15-8-20]]

^<<v15-8-20,20>>^ Eles trouxeram ainda duzentos e vinte dos servidores do templo, um grupo que Davi e os seus oficiais tinham formado para ajudar os levitas. Todos eles tinham seus nomes registrados.

[[v15-8-21]]

^<<v15-8-21,21>>^ Ali, junto ao canal de Aava, proclamei um jejum, a fim de que nos humilhássemos diante do nosso Deus e lhe pedíssemos uma viagem segura para nós e nossos filhos, com todos os nossos bens.

[[v15-8-22]]

^<<v15-8-22,22>>^ Tive vergonha de pedir soldados e cavaleiros ao rei para nos protegerem dos inimigos na estrada, pois tínhamos dito ao rei: "A mão bondosa de nosso Deus está sobre todos os que o buscam, mas o seu poder e a sua ira são contra todos os que o abandonam".

[[v15-8-23]]

^<<v15-8-23,23>>^ Por isso jejuamos e suplicamos essa bênção ao nosso Deus, e ele nos atendeu.

[[v15-8-24]]

^<<v15-8-24,24>>^ Depois separei doze dos principais sacerdotes, a saber, Serebias, Hasabias e com eles, dez dos seus irmãos,

[[v15-8-25]]

^<<v15-8-25,25>>^ e pesei diante deles a oferta de prata e de ouro e os utensílios que o rei, seus conselheiros, seus oficiais e todo o Israel ali presente tinham doado para a casa de nosso Deus.

[[v15-8-26]]

^<<v15-8-26,26>>^ Pesei e entreguei-lhes vinte e duas toneladas e setecentos e cinqüenta quilos de prata, três toneladas e meia de utensílios de prata, três toneladas e meia de ouro,

[[v15-8-27]]

^<<v15-8-27,27>>^ vinte tigelas de ouro pesando oito quilos e meio, e dois utensílios finos de bronze polido, tão valiosos quanto ouro.

[[v15-8-28]]

^<<v15-8-28,28>>^ E eu lhes disse: Tanto vocês quanto estes utensílios estão consagrados ao Senhor. A prata e o ouro são uma oferta voluntária ao Senhor, o Deus dos seus antepassados.

[[v15-8-29]]

^<<v15-8-29,29>>^ Guardem-nos bem até que os pesem nas salas do templo do Senhor em Jerusalém diante dos sacerdotes principais, dos levitas e dos chefes das famílias de Israel.

[[v15-8-30]]

^<<v15-8-30,30>>^ Então os sacerdotes e os levitas receberam a prata, o ouro e os utensílios sagrados, depois que tinham sido pesados, para levá-los a Jerusalém, ao templo do nosso Deus.

[[v15-8-31]]

^<<v15-8-31,31>>^ No décimo segundo dia do primeiro mês nós partimos do canal de Aava e fomos para Jerusalém. A mão do nosso Deus esteve sobre nós, e ele nos protegeu do ataque de inimigos e assaltantes pelo caminho.

[[v15-8-32]]

^<<v15-8-32,32>>^ Assim chegamos a Jerusalém, e ficamos descansando três dias.

[[v15-8-33]]

^<<v15-8-33,33>>^ No quarto dia, no templo do nosso Deus, pesamos a prata, o ouro e os utensílios sagrados, e os demos a Meremote, filho do sacerdote Urias. Estavam com ele Eleazar, filho de Finéias, e os levitas Jozabade, filho de Jesua, e Noadias, filho de Binui.

[[v15-8-34]]

^<<v15-8-34,34>>^ Tudo foi contado e pesado, e o peso total foi registrado naquela mesma hora.

[[v15-8-35]]

^<<v15-8-35,35>>^ Então os exilados que tinham voltado do cativeiro sacrificaram holocaustos ao Deus de Israel: doze touros em favor de todo o Israel, noventa e seis carneiros, setenta e sete cordeiros e, como oferta pelo pecado, doze bodes. Tudo isso foi oferecido como um holocausto ao Senhor.

[[v15-8-36]]

^<<v15-8-36,36>>^ Eles também entregaram as ordens do rei aos sátrapas e aos governadores do território a oeste do Eufrates, e eles ajudaram o povo na obra do templo de Deus.

'''

xref:015-esdras/015-esdras-007.adoc#v15-7-0[&#60; Capítulo Anterior] | <<v15-8-0,Topo>> | xref:015-esdras/015-esdras-009.adoc#v15-9-0[Próximo Capítulo &#62;]