include::./index.adoc[]

[[v15-3-0]]
=== Esdras, 3
// nvi ?, NVI - Nova Versão Internacional

[[v15-3-1]]

^<<v15-3-1,1>>^ Quando chegou o sétimo mês e os israelitas já estavam em suas cidades, o povo se reuniu como um só homem em Jerusalém.

[[v15-3-2]]

^<<v15-3-2,2>>^ Então Jesua, filho de Jozadaque, seus colegas, os sacerdotes, e Zorobabel, filho de Sealtiel, e seus companheiros começaram a construir o altar do Deus de Israel para nele sacrificarem holocaustos, conforme o que está escrito na Lei de Moisés, homem de Deus.

[[v15-3-3]]

^<<v15-3-3,3>>^ Apesar do receio que tinham dos povos ao redor, construíram o altar sobre a sua base e nele sacrificaram holocaustos ao Senhor, tanto os sacrifícios da manhã como os da tarde.

[[v15-3-4]]

^<<v15-3-4,4>>^ Então, de acordo com o que está escrito, celebraram a festa das cabanas com o número determinado de holocaustos prescritos para cada dia.

[[v15-3-5]]

^<<v15-3-5,5>>^ Depois disso, apresentaram os holocaustos regulares, os sacrifícios da lua nova e os sacrifícios requeridos para todas as festas sagradas determinadas pelo Senhor, bem como os que foram trazidos como ofertas voluntárias ao Senhor.

[[v15-3-6]]

^<<v15-3-6,6>>^ A partir do dia primeiro do sétimo mês começaram a oferecer holocaustos ao Senhor, embora ainda não tivessem sido lançados os alicerces do templo do Senhor.

[[v15-3-7]]

^<<v15-3-7,7>>^ Então eles deram dinheiro aos pedreiros e os carpinteiros, e deram comida, bebida e azeite ao povo de Sidom e de Tiro, para que, pelo mar, trouxessem do Líbano para Jope toras de cedro, o que tinha sido autorizado por Ciro, rei da Pérsia.

[[v15-3-8]]

^<<v15-3-8,8>>^ No segundo mês do segundo ano depois de chegarem ao templo de Deus em Jerusalém, Zorobabel, filho de Sealtiel, Jesua, filho de Jozadaque, e o restante dos seus irmãos, os sacerdotes, os levitas e todos os que tinham voltado do cativeiro para Jerusalém, começaram o trabalho, designando levitas de vinte anos para cima para supervisionarem a construção do templo do Senhor.

[[v15-3-9]]

^<<v15-3-9,9>>^ Jesua, seus filhos e seus irmãos, e Cadmiel e seus filhos, descendentes de Hodavias, e os filhos de Henadade e seus filhos e seus irmãos, todos eles levitas, uniram-se para supervisionar os que trabalhavam no templo de Deus.

[[v15-3-10]]

^<<v15-3-10,10>>^ Quando os construtores lançaram os alicerces do templo do Senhor, os sacerdotes, com suas vestes e suas trombetas, e os levitas, filhos de Asafe, com címbalos, tomaram seus lugares para louvar o Senhor, conforme prescrito por Davi, rei de Israel.

[[v15-3-11]]

^<<v15-3-11,11>>^ Com louvor e ações de graças, cantaram responsivamente ao Senhor: "Ele é bom; seu amor a Israel dura para sempre". E todo o povo louvou ao Senhor em alta voz, pois haviam sido lançados os alicerces do templo do Senhor.

[[v15-3-12]]

^<<v15-3-12,12>>^ Mas muitos dos sacerdotes, dos levitas e dos líderes de família mais velhos, que tinham visto o antigo templo, choraram em voz alta quando viram o lançamento dos alicerces desse templo; muitos, porém, gritavam de alegria.

[[v15-3-13]]

^<<v15-3-13,13>>^ Não era possível distinguir entre o som dos gritos de alegria e o som do choro, pois o povo fazia enorme barulho. E o som foi ouvido a grande distância.

'''

xref:015-esdras/015-esdras-002.adoc#v15-2-0[&#60; Capítulo Anterior] | <<v15-3-0,Topo>> | xref:015-esdras/015-esdras-004.adoc#v15-4-0[Próximo Capítulo &#62;]