include::./index.adoc[]

[[v15-6-0]]
=== Esdras, 6
// nvi ?, NVI - Nova Versão Internacional

[[v15-6-1]]

^<<v15-6-1,1>>^ O rei Dario mandou então fazer uma pesquisa nos arquivos da Babilônia, onde se guardavam os tesouros.

[[v15-6-2]]

^<<v15-6-2,2>>^ Encontrou-se um rolo na cidadela de Ecbatana, na província da Média, e nele estava escrito o seguinte, que Dario comunicou:

[[v15-6-3]]

^<<v15-6-3,3>>^ "No primeiro ano do seu reinado o rei Ciro promulgou um decreto acerca do templo de Deus em Jerusalém, nestes termos: " ‘Que o templo seja reconstruído como local para apresentar sacrifícios, e que se lancem os seus alicerces. Ele terá vinte e sete metros de altura e vinte e sete metros de largura,

[[v15-6-4]]

^<<v15-6-4,4>>^ com três carreiras de pedras grandes e uma carreira de madeira. O custo será pago pela tesouraria do rei.

[[v15-6-5]]

^<<v15-6-5,5>>^ E os utensílios de ouro e de prata da casa de Deus que Nabucodonosor tirou do templo de Jerusalém e trouxe para a Babilônia serão devolvidos aos seus lugares no templo de Jerusalém; devem ser colocados na casa de Deus’.

[[v15-6-6]]

^<<v15-6-6,6>>^ "Agora, então, Tatenai, governador do território a oeste do Eufrates, e Setar-Bozenai, e vocês, funcionários dessa província e amigos deles, mantenham-se afastados de lá.

[[v15-6-7]]

^<<v15-6-7,7>>^ Não interfiram na obra que se faz nesse templo de Deus. Deixem o governador e os líderes dos judeus reconstruírem este templo de Deus em seu antigo local.

[[v15-6-8]]

^<<v15-6-8,8>>^ "Além disso, promulgo o seguinte decreto a respeito do que vocês farão por esses líderes dos judeus na construção deste templo de Deus: "As despesas destes homens serão integralmente pagas pela tesouraria do rei, do tributo recebido do território a oeste do Eufrates, para que a obra não pare.

[[v15-6-9]]

^<<v15-6-9,9>>^ E o que for necessário: novilhos, carneiros, cordeiros para os holocaustos oferecidos ao Deus dos céus, e trigo, sal, vinho e azeite, conforme for solicitado pelos sacerdotes em Jerusalém, tudo deverá ser entregue diariamente a eles, sem falta,

[[v15-6-10]]

^<<v15-6-10,10>>^ para que ofereçam sacrifícios agradáveis ao Deus dos céus e orem pelo bem-estar do rei e dos seus filhos.

[[v15-6-11]]

^<<v15-6-11,11>>^ "Além disso determino que, se alguém alterar este decreto, atravessem-lhe o corpo com uma viga tirada de sua casa e deixem-no empalado. E seja a casa dele transformada num monte de entulho.

[[v15-6-12]]

^<<v15-6-12,12>>^ E que Deus, que fez o seu nome ali habitar, derrube qualquer rei ou povo que estender a mão para mudar este decreto ou para destruir esse templo de Jerusalém. "Eu, Dario, o decretei. Que seja plenamente executado".

[[v15-6-13]]

^<<v15-6-13,13>>^ Então, em vista do decreto do rei Dario, Tatenai, governador do território a oeste do Eufrates, Setar-Bozenai e os companheiros deles o cumpriram plenamente.

[[v15-6-14]]

^<<v15-6-14,14>>^ Dessa maneira, os líderes dos judeus continuaram a construir e a prosperar, encorajados pela pregação dos profetas Ageu e Zacarias, descendente de Ido. Eles terminaram a reconstrução do templo conforme a ordem do Deus de Israel e os decretos de Ciro, de Dario e de Artaxerxes, reis da Pérsia.

[[v15-6-15]]

^<<v15-6-15,15>>^ O templo foi concluído no terceiro dia do mês de adar, no sexto ano do reinado do rei Dario.

[[v15-6-16]]

^<<v15-6-16,16>>^ Então o povo de Israel, sacerdotes, levitas e o restante dos exilados, celebraram com alegria a dedicação do templo de Deus.

[[v15-6-17]]

^<<v15-6-17,17>>^ Para a dedicação do templo de Deus ofereceram cem touros, duzentos carneiros, quatrocentos cordeiros e, como oferta pelo pecado de todo o Israel, doze bodes, de acordo com o número das tribos de Israel.

[[v15-6-18]]

^<<v15-6-18,18>>^ E organizaram os sacerdotes em suas divisões e os levitas em seus grupos para o serviço de Deus em Jerusalém, de acordo com o que está escrito no Livro de Moisés.

[[v15-6-19]]

^<<v15-6-19,19>>^ No décimo quarto dia do primeiro mês, os exilados celebraram a Páscoa.

[[v15-6-20]]

^<<v15-6-20,20>>^ Os sacerdotes e os levitas tinham se purificado; estavam todos cerimonialmente puros. Os levitas sacrificaram o cordeiro da Páscoa para todos os exilados, para os seus colegas sacerdotes e para eles mesmos.

[[v15-6-21]]

^<<v15-6-21,21>>^ Assim os israelitas, que tinham voltado do exílio, comeram do cordeiro, juntamente com todos que se haviam separado das práticas impuras de seus vizinhos gentios, a fim de buscarem o Senhor, o Deus de Israel.

[[v15-6-22]]

^<<v15-6-22,22>>^ Durante sete dias eles celebraram com alegria a festa dos pães sem fermento, pois o Senhor os enchera de alegria ao mudar o coração do rei da Assíria, de maneira que ele lhes deu força para realizarem a obra de reconstrução do templo de Deus, do Deus de Israel.

'''

xref:015-esdras/015-esdras-005.adoc#v15-5-0[&#60; Capítulo Anterior] | <<v15-6-0,Topo>> | xref:015-esdras/015-esdras-007.adoc#v15-7-0[Próximo Capítulo &#62;]