include::./index.adoc[]

[[v15-7-0]]
=== Esdras, 7
// nvi ?, NVI - Nova Versão Internacional

[[v15-7-1]]

^<<v15-7-1,1>>^ Depois dessas coisas, no reinado de Artaxerxes, rei da Pérsia, vivia Esdras, filho de Seraías, filho de Azarias, filho de Hilquias,

[[v15-7-2]]

^<<v15-7-2,2>>^ filho de Salum, filho de Zadoque, filho de Aitube,

[[v15-7-3]]

^<<v15-7-3,3>>^ filho de Amarias, filho de Azarias, filho de Meraiote,

[[v15-7-4]]

^<<v15-7-4,4>>^ filho de Zeraías, filho de Uzi, filho de Buqui,

[[v15-7-5]]

^<<v15-7-5,5>>^ filho de Abisua, filho de Finéias, filho de Eleazar, filho do sumo sacerdote Arão.

[[v15-7-6]]

^<<v15-7-6,6>>^ Este Esdras veio da Babilônia. Ele era um escriba que conhecia muito a Lei de Moisés dada pelo Senhor, o Deus de Israel. O rei lhe concedera tudo o que ele tinha pedido, pois a mão do Senhor, o seu Deus, estava sobre ele.

[[v15-7-7]]

^<<v15-7-7,7>>^ Alguns dos israelitas, inclusive sacerdotes, levitas, cantores, porteiros e servidores do templo, também foram para Jerusalém no sétimo ano do reinado de Artaxerxes.

[[v15-7-8]]

^<<v15-7-8,8>>^ Esdras chegou a Jerusalém no quinto mês do sétimo ano desse reinado.

[[v15-7-9]]

^<<v15-7-9,9>>^ No dia primeiro do primeiro mês ele saiu da Babilônia, e chegou a Jerusalém no primeiro dia do quinto mês, porquanto a boa mão de seu Deus estava sobre ele.

[[v15-7-10]]

^<<v15-7-10,10>>^ Pois Esdras tinha decidido dedicar-se a estudar a Lei do Senhor e a praticá-la, e a ensinar os seus decretos e mandamentos aos israelitas.

[[v15-7-11]]

^<<v15-7-11,11>>^ Temos aqui uma cópia da carta que o rei Artaxerxes entregou ao sacerdote e escriba Esdras, conhecedor dos mandamentos e decretos do Senhor para Israel:

[[v15-7-12]]

^<<v15-7-12,12>>^ "Artaxerxes, rei dos reis, "Ao sacerdote Esdras, escriba da Lei do Deus dos céus: "Paz e prosperidade!

[[v15-7-13]]

^<<v15-7-13,13>>^ "Estou decretando que qualquer israelita em meu reino, inclusive sacerdotes e levitas, que desejar ir a Jerusalém com você, poderá fazê-lo.

[[v15-7-14]]

^<<v15-7-14,14>>^ Você está sendo enviado pelo rei e por seus sete conselheiros para fazer uma investigação em Judá e em Jerusalém com respeito à Lei do seu Deus, que está nas suas mãos.

[[v15-7-15]]

^<<v15-7-15,15>>^ Além disso, você levará a prata e o ouro que o rei e seus conselheiros voluntariamente ofereceram ao Deus de Israel, cuja habitação está em Jerusalém,

[[v15-7-16]]

^<<v15-7-16,16>>^ juntamente com toda a prata e ouro que você receber da província da Babilônia, bem como as ofertas voluntárias do povo e dos sacerdotes para o templo do Deus deles em Jerusalém.

[[v15-7-17]]

^<<v15-7-17,17>>^ Com esse dinheiro compre novilhos, carneiros e cordeiros, como também o que for necessário para as suas ofertas de cereal e de bebida, e sacrifique-os no altar do templo do seu Deus em Jerusalém.

[[v15-7-18]]

^<<v15-7-18,18>>^ "Você e seus irmãos poderão fazer o que acharem melhor com o restante da prata e do ouro, de acordo com a vontade do seu Deus.

[[v15-7-19]]

^<<v15-7-19,19>>^ Entregue ao Deus de Jerusalém todos os utensílios que foram confiados a você para o culto no templo de seu Deus.

[[v15-7-20]]

^<<v15-7-20,20>>^ E todas as demais despesas necessárias com relação ao templo de seu Deus serão pagas pelo tesouro real.

[[v15-7-21]]

^<<v15-7-21,21>>^ "Agora eu, o rei Artaxerxes, ordeno a todos os tesoureiros do território a oeste do Eufrates que forneçam tudo o que o sacerdote Esdras, escriba da Lei do Deus dos céus, solicitar a vocês,

[[v15-7-22]]

^<<v15-7-22,22>>^ até três toneladas e meia de prata, cem tonéis de trigo, dez barris de vinho, dez barris de azeite de oliva, e sal à vontade.

[[v15-7-23]]

^<<v15-7-23,23>>^ Tudo o que o Deus dos céus tenha prescrito, que se faça com presteza para o templo do Deus dos céus, para que a sua ira não venha contra o império do rei e dos seus descendentes.

[[v15-7-24]]

^<<v15-7-24,24>>^ Saibam também que vocês não têm autoridade para exigir impostos, tributos ou taxas de nenhum sacerdote, levita, cantor, porteiro, servidor do templo e de todos quantos trabalham neste templo de Deus.

[[v15-7-25]]

^<<v15-7-25,25>>^ "E você, Esdras, com a sabedoria que o seu Deus lhe deu, nomeie magistrados e juízes para ministrarem justiça a todo o povo do território a oeste do Eufrates, a todos os que conhecem as leis do seu Deus. E aos que não as conhecem, você deverá ensiná-las.

[[v15-7-26]]

^<<v15-7-26,26>>^ Aquele que não obedecer à lei do Deus de vocês e à lei do rei seja punido com a morte, ou com o exílio, ou com o confisco de bens ou com a prisão".

[[v15-7-27]]

^<<v15-7-27,27>>^ Bendito seja o Senhor, o Deus de nossos antepassados, que pôs no coração do rei o propósito de honrar desta maneira o templo do Senhor em Jerusalém,

[[v15-7-28]]

^<<v15-7-28,28>>^ e que, por sua bondade, levou o rei, os seus conselheiros e todos os seus altos oficiais. Como a mão do Senhor meu Deus esteve sobre mim, tomei coragem e reuni alguns líderes de Israel para me acompanharem.

'''

xref:015-esdras/015-esdras-006.adoc#v15-6-0[&#60; Capítulo Anterior] | <<v15-7-0,Topo>> | xref:015-esdras/015-esdras-008.adoc#v15-8-0[Próximo Capítulo &#62;]