include::./index.adoc[]

[[v25-1-0]]
=== Lamentações, 1
// nvi ?, NVI - Nova Versão Internacional

[[v25-1-1]]

^<<v25-1-1,1>>^ Como está deserta a cidade, antes tão cheia de gente! Como se parece com uma viúva, a que antes era grandiosa entre as nações! A que era a princesa das províncias agora tornou-se uma escrava.

[[v25-1-2]]

^<<v25-1-2,2>>^ Chora amargamente à noite, as lágrimas rolam por seu rosto. De todos os seus amantes nenhum a consola. Todos os seus amigos a traíram; tornaram-se seus inimigos.

[[v25-1-3]]

^<<v25-1-3,3>>^ Em aflição e sob trabalhos forçados, Judá foi levado ao exílio. Vive entre as nações sem encontrar repouso. Todos os que a perseguiram a capturaram em meio ao seu desespero.

[[v25-1-4]]

^<<v25-1-4,4>>^ Os caminhos para Sião pranteiam, porque ninguém comparece às suas festas fixas. Todas as suas portas estão desertas, seus sacerdotes gemem, suas moças se entristecem, e ela se encontra em angústia profunda.

[[v25-1-5]]

^<<v25-1-5,5>>^ Seus adversários são os seus chefes; seus inimigos estão tranqüilos. O Senhor lhe trouxe tristeza por causa dos seus muitos pecados. Seus filhos foram levados ao exílio, prisioneiros dos adversários.

[[v25-1-6]]

^<<v25-1-6,6>>^ Todo o esplendor fugiu da cidade de Sião. Seus líderes são como corças que não encontram pastagem; sem forças fugiram diante do perseguidor.

[[v25-1-7]]

^<<v25-1-7,7>>^ Nos dias de sua aflição e de seu desnorteio Jerusalém se lembra de todos os tesouros que lhe pertenciam nos tempos passados. Quando o seu povo caiu nas mãos do inimigo, ninguém veio ajudá-la. Seus inimigos olharam para ela e zombaram da sua queda.

[[v25-1-8]]

^<<v25-1-8,8>>^ Jerusalém cometeu graves pecados; por isso tornou-se impura. Todos os que a honravam agora a desprezam, porque viram a sua nudez; ela mesma geme e se desvia deles.

[[v25-1-9]]

^<<v25-1-9,9>>^ Sua impureza prende-se às suas saias; ela não esperava que chegaria o seu fim. Sua queda foi surpreendente; ninguém veio consolá-la. "Olha, Senhor, para a minha aflição, pois o inimigo triunfou. "

[[v25-1-10]]

^<<v25-1-10,10>>^ O adversário saqueia todos os seus tesouros; ela viu nações pagãs entrarem em seu santuário, sendo que tu as tinhas proibido de participar das tuas assembléias.

[[v25-1-11]]

^<<v25-1-11,11>>^ Todo o seu povo se lamenta enquanto vai em busca de pão; e para sobreviverem, trocam os tesouros por comida. "Olha, Senhor, e considera, pois tenho sido desprezada. "

[[v25-1-12]]

^<<v25-1-12,12>>^ "Vocês não se comovem, todos vocês que passam por aqui? Olhem ao redor e vejam se há sofrimento maior do que o que me foi imposto e que o Senhor trouxe sobre mim no dia em que se acendeu a sua ira.

[[v25-1-13]]

^<<v25-1-13,13>>^ Do alto ele fez cair fogo sobre os meus ossos. Armou uma rede para os meus pés e me derrubou de costas. Deixou-me desolada, desfalecida o dia todo.

[[v25-1-14]]

^<<v25-1-14,14>>^ Os meus pecados foram amarrados num jugo; suas mãos os ataram todos juntos, e os colocaram em meu pescoço; o Senhor abateu a minha força. Ele me entregou àqueles que não consigo vencer.

[[v25-1-15]]

^<<v25-1-15,15>>^ O Senhor dispersou todos os guerreiros que me apoiavam; convocou um exército contra mim para destruir os meus jovens. O Senhor pisou no seu lagar a virgem, a cidade de Judá.

[[v25-1-16]]

^<<v25-1-16,16>>^ É por isso que eu choro; as lágrimas inundam os meus olhos. Ninguém está por perto para consolar-me, não há ninguém que restaure o meu espírito. Meus filhos estão desamparados porque o inimigo prevaleceu. "

[[v25-1-17]]

^<<v25-1-17,17>>^ Sião estende as mãos suplicantes mas não há quem a console. O Senhor decretou que os vizinhos de Jacó se tornem seus adversários; Jerusalém tornou-se coisa imunda entre eles.

[[v25-1-18]]

^<<v25-1-18,18>>^ "O Senhor é justo, mas eu me rebelei contra a sua ordem. Ouçam, todos os povos; olhem para o meu sofrimento. Meus jovens e minhas moças foram para o exílio.

[[v25-1-19]]

^<<v25-1-19,19>>^ Chamei os meus aliados, mas eles me traíram. Meus sacerdotes e meus líderes pereceram na cidade, enquanto procuravam comida para poderem sobreviver.

[[v25-1-20]]

^<<v25-1-20,20>>^ Veja, Senhor, como estou angustiada! Estou atormentada no íntimo, e no meu coração me perturbo pois tenho sido muito rebelde. Lá fora, a espada a todos consome; dentro impera a morte.

[[v25-1-21]]

^<<v25-1-21,21>>^ Os meus lamentos têm sido ouvidos, mas não há ninguém que me console. Todos os meus inimigos sabem da minha agonia; eles se alegram com o que fizeste. Quem dera trouxesses o dia que anunciaste para que eles ficassem como eu.

[[v25-1-22]]

^<<v25-1-22,22>>^ Que toda a maldade deles seja conhecida diante de ti; faze com eles o que fizeste comigo por causa de todos os meus pecados. Os meus gemidos são muitos e o meu coração desfalece. "

'''

xref:024-jeremias/024-jeremias-052.adoc#v24-52-0[&#60; Capítulo Anterior] | <<v25-1-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-002.adoc#v25-2-0[Próximo Capítulo &#62;]