include::./index.adoc[]

[[v5-23-0]]
=== Deuteronômio, 23
// nvi ?, NVI - Nova Versão Internacional

[[v5-23-1]]

^<<v5-23-1,1>>^ Qualquer que tenha os testículos esmagados ou tenha amputado o membro viril, não poderá entrar na assembléia do Senhor.

[[v5-23-2]]

^<<v5-23-2,2>>^ Quem nasceu de união ilícita não poderá entrar na assembléia do Senhor, como também os seus descendentes, até a décima geração.

[[v5-23-3]]

^<<v5-23-3,3>>^ Nenhum amonita ou moabita ou qualquer dos seus descendentes, até a décima geração, poderá entrar na assembléia do Senhor.

[[v5-23-4]]

^<<v5-23-4,4>>^ Pois eles não vieram encontrar-se com vocês com pão e água no caminho, quando vocês saíram do Egito; além disso convocaram Balaão, filho de Beor, para vir de Petor, na Mesopotâmia, para pronunciar maldição contra vocês.

[[v5-23-5]]

^<<v5-23-5,5>>^ No entanto, o Senhor, o seu Deus, não atendeu Balaão, e transformou a maldição em bênção para vocês, pois o Senhor, o seu Deus, os ama.

[[v5-23-6]]

^<<v5-23-6,6>>^ Não façam um tratado de amizade com eles enquanto vocês viverem.

[[v5-23-7]]

^<<v5-23-7,7>>^ Não rejeitem o edomita, pois ele é seu irmão. Também não rejeitem o egípcio, pois vocês viveram como estrangeiros na terra deles.

[[v5-23-8]]

^<<v5-23-8,8>>^ A terceira geração dos filhos deles poderá entrar na assembléia do Senhor.

[[v5-23-9]]

^<<v5-23-9,9>>^ Quando estiverem acampados, em guerra contra os seus inimigos, mantenham-se afastados de todas as coisas impuras.

[[v5-23-10]]

^<<v5-23-10,10>>^ Se um de seus homens estiver impuro devido à polução noturna, ele terá que sair do acampamento.

[[v5-23-11]]

^<<v5-23-11,11>>^ Mas ao entardecer ele se lavará, e ao pôr-do-sol poderá voltar ao acampamento.

[[v5-23-12]]

^<<v5-23-12,12>>^ Determinem um local fora do acampamento onde se possa evacuar.

[[v5-23-13]]

^<<v5-23-13,13>>^ Como parte do seu equipamento, tenham algo com que cavar, e quando evacuarem, façam um buraco e cubram as fezes.

[[v5-23-14]]

^<<v5-23-14,14>>^ Pois o Senhor, o seu Deus, anda pelo seu acampamento para protegê-los e entregar-lhes os seus inimigos. O acampamento terá que ser santo, para que ele não veja no meio de vocês alguma coisa desagradável e se afaste de vocês.

[[v5-23-15]]

^<<v5-23-15,15>>^ Se um escravo refugiar-se entre vocês, não o entreguem nas mãos do seu senhor.

[[v5-23-16]]

^<<v5-23-16,16>>^ Deixem-no viver no meio de vocês pelo tempo que ele desejar e em qualquer cidade que ele escolher. Não o oprimam.

[[v5-23-17]]

^<<v5-23-17,17>>^ Nenhum israelita, homem ou mulher, poderá tornar-se prostituto cultual.

[[v5-23-18]]

^<<v5-23-18,18>>^ Não tragam ao santuário do Senhor, do seu Deus, os ganhos de uma prostituta ou de um prostituto, a fim de pagar algum voto, pois o Senhor, o seu Deus, por ambos têm repugnância.

[[v5-23-19]]

^<<v5-23-19,19>>^ Não cobrem juros de um israelita, por dinheiro, alimento, ou qualquer outra coisa que possa render juros.

[[v5-23-20]]

^<<v5-23-20,20>>^ Vocês poderão cobrar juros do estrangeiro, mas não do seu irmão israelita, para que o Senhor, o seu Deus, os abençoe em tudo o que vocês fizerem na terra em que estão entrando para dela tomar posse.

[[v5-23-21]]

^<<v5-23-21,21>>^ Se um de vocês fizer um voto ao Senhor, ao seu Deus, não demore a cumpri-lo, pois o Senhor, o seu Deus, certamente lhe pedirá contas, e você será culpado de pecado se não o cumprir.

[[v5-23-22]]

^<<v5-23-22,22>>^ Mas se você não fizer o voto, de nada será culpado.

[[v5-23-23]]

^<<v5-23-23,23>>^ Faça tudo para cumprir o que os seus lábios prometeram, pois com a sua própria boca você fez, espontaneamente, o seu voto ao Senhor, ao seu Deus.

[[v5-23-24]]

^<<v5-23-24,24>>^ Se vocês entrarem na vinha do seu próximo, poderão comer as uvas que desejarem, mas nada poderão levar em sua cesta.

[[v5-23-25]]

^<<v5-23-25,25>>^ Se entrarem na plantação de trigo do seu próximo, poderão apanhar espigas com as mãos, mas nunca usem foice para ceifar o trigo do seu próximo.

'''

xref:005-deuteronomio/005-deuteronomio-022.adoc#v5-22-0[&#60; Capítulo Anterior] | <<v5-23-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-024.adoc#v5-24-0[Próximo Capítulo &#62;]