include::./index.adoc[]

[[v5-13-0]]
=== Deuteronômio, 13
// nvi ?, NVI - Nova Versão Internacional

[[v5-13-1]]

^<<v5-13-1,1>>^ Se aparecer entre vocês um profeta ou alguém que faz predições por meio de sonhos e lhes anunciar um sinal miraculoso ou um prodígio,

[[v5-13-2]]

^<<v5-13-2,2>>^ e se o sinal ou prodígio de que ele falou acontecer, e ele disser: "Vamos seguir outros deuses que vocês não conhecem e vamos adorá-los",

[[v5-13-3]]

^<<v5-13-3,3>>^ não dêem ouvidos às palavras daquele profeta ou sonhador. O Senhor, o seu Deus, está pondo vocês à prova para ver se o amam de todo o coração e de toda a alma.

[[v5-13-4]]

^<<v5-13-4,4>>^ Sigam somente o Senhor, o seu Deus, e temam a ele somente. Cumpram os seus mandamentos e obedeçam-lhe; sirvam-no e apeguem-se a ele.

[[v5-13-5]]

^<<v5-13-5,5>>^ Aquele profeta ou sonhador terá que ser morto, pois pregou rebelião contra o Senhor, contra o seu Deus, que os tirou do Egito e os redimiu da terra da escravidão; ele tentou afastá-los do caminho que o Senhor, o seu Deus, lhes ordenou que seguissem. Eliminem o mal do meio de vocês.

[[v5-13-6]]

^<<v5-13-6,6>>^ Se o seu próprio irmão ou filho ou filha, ou a mulher que você ama ou o seu amigo mais chegado secretamente instigá-lo, dizendo: "Vamos adorar outros deuses! " — deuses que nem você nem os seus antepassados conheceram,

[[v5-13-7]]

^<<v5-13-7,7>>^ deuses dos povos que vivem ao seu redor, quer próximos, quer distantes, de um ao outro lado da terra —

[[v5-13-8]]

^<<v5-13-8,8>>^ não se deixe convencer nem ouça o que ele diz. Não tenha piedade nem compaixão dele e não o proteja.

[[v5-13-9]]

^<<v5-13-9,9>>^ Você terá que matá-lo. Seja a sua mão a primeira a levantar-se para matá-lo, e depois as mãos de todo o povo.

[[v5-13-10]]

^<<v5-13-10,10>>^ Apedreje-o até à morte, porque tentou desviá-lo do Senhor, o seu Deus, que o tirou do Egito, da terra da escravidão.

[[v5-13-11]]

^<<v5-13-11,11>>^ Então todo o Israel saberá disso; todos temerão e ninguém tornará a cometer uma maldade dessas.

[[v5-13-12]]

^<<v5-13-12,12>>^ Se vocês ouvirem dizer que numa das cidades que o Senhor, o seu Deus, lhes dá para nelas morarem,

[[v5-13-13]]

^<<v5-13-13,13>>^ surgiram homens perversos e desviaram os seus habitantes, dizendo: "Vamos adorar outros deuses! ", deuses que vocês não conhecem,

[[v5-13-14]]

^<<v5-13-14,14>>^ vocês deverão verificar e investigar. Se for verdade e ficar comprovado que se praticou esse ato detestável entre vocês,

[[v5-13-15]]

^<<v5-13-15,15>>^ matem ao fio da espada todos os que viverem naquela cidade. Destruam totalmente a cidade, matando tanto os seus habitantes quanto os seus animais.

[[v5-13-16]]

^<<v5-13-16,16>>^ Ajuntem todos os despojos no meio da praça pública e queimem totalmente a cidade e todos os seus despojos, como oferta ao Senhor, ao seu Deus. Fique ela em ruínas para sempre, e nunca mais seja reconstruída.

[[v5-13-17]]

^<<v5-13-17,17>>^ Não seja encontrado em suas mãos nada do que foi destinado à destruição, para que o Senhor se afaste do fogo da sua ira; terá misericórdia e compaixão de vocês, e os fará multiplicar, conforme prometeu sob juramento aos seus antepassados,

[[v5-13-18]]

^<<v5-13-18,18>>^ somente se obedecerem ao Senhor, ao seu Deus, guardando todos os seus mandamentos, que lhes estou dando, e fazendo o que é justo aos seus olhos.

'''

xref:005-deuteronomio/005-deuteronomio-012.adoc#v5-12-0[&#60; Capítulo Anterior] | <<v5-13-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-014.adoc#v5-14-0[Próximo Capítulo &#62;]