include::./index.adoc[]

[[v5-28-0]]
=== Deuteronômio, 28
// nvi ?, NVI - Nova Versão Internacional

[[v5-28-1]]

^<<v5-28-1,1>>^ Se vocês obedecerem fielmente ao Senhor, ao seu Deus, e seguirem cuidadosamente todos os seus mandamentos que hoje lhes dou, o Senhor, o seu Deus, os colocará muito acima de todas as nações da terra.

[[v5-28-2]]

^<<v5-28-2,2>>^ Todas estas bênçãos virão sobre vocês e os acompanharão, se vocês obedecerem ao Senhor, ao seu Deus:

[[v5-28-3]]

^<<v5-28-3,3>>^ Vocês serão abençoados na cidade e serão abençoados no campo.

[[v5-28-4]]

^<<v5-28-4,4>>^ Os filhos do seu ventre serão abençoados, como também as colheitas da sua terra e os bezerros e os cordeiros dos seus rebanhos.

[[v5-28-5]]

^<<v5-28-5,5>>^ A sua cesta e a sua amassadeira serão abençoadas.

[[v5-28-6]]

^<<v5-28-6,6>>^ Vocês serão abençoados em tudo o que fizerem.

[[v5-28-7]]

^<<v5-28-7,7>>^ O Senhor concederá que sejam derrotados diante de vocês os inimigos que os atacarem. Virão a vocês por um caminho, e por sete fugirão.

[[v5-28-8]]

^<<v5-28-8,8>>^ O Senhor enviará bênçãos aos seus celeiros e a tudo o que as suas mãos fizerem. O Senhor, o seu Deus, os abençoará na terra que lhes dá.

[[v5-28-9]]

^<<v5-28-9,9>>^ O Senhor fará de vocês o seu povo santo, conforme prometeu sob juramento, se guardarem os mandamentos do Senhor, do seu Deus, e andarem nos caminhos dele.

[[v5-28-10]]

^<<v5-28-10,10>>^ Então todos os povos da terra verão que vocês são chamados pelo nome do Senhor e terão medo de vocês.

[[v5-28-11]]

^<<v5-28-11,11>>^ O Senhor lhes concederá grande prosperidade, no fruto do seu ventre, nas crias dos seus animais e nas colheitas da sua terra, nesta terra que ele jurou aos seus antepassados que daria a vocês.

[[v5-28-12]]

^<<v5-28-12,12>>^ O Senhor abrirá o céu, o depósito do seu tesouro, para enviar chuva à sua terra no devido tempo e para abençoar todo o trabalho das suas mãos. Vocês emprestarão a muitas nações, e de nenhuma tomarão emprestado.

[[v5-28-13]]

^<<v5-28-13,13>>^ O Senhor fará de vocês a cabeça das nações, e não a cauda. Se obedecerem aos mandamentos do Senhor, do seu Deus, que hoje lhes dou e os seguirem cuidadosamente, vocês estarão sempre por cima, nunca por baixo.

[[v5-28-14]]

^<<v5-28-14,14>>^ Não se desviem, nem para a direita nem para a esquerda, de qualquer dos mandamentos que hoje lhes dou, para seguir outros deuses e prestar-lhes culto.

[[v5-28-15]]

^<<v5-28-15,15>>^ Entretanto, se vocês não obedecerem ao Senhor, ao seu Deus, e não seguirem cuidadosamente todos os seus mandamentos e decretos que hoje lhes dou, todas estas maldições cairão sobre vocês e os atingirão:

[[v5-28-16]]

^<<v5-28-16,16>>^ Vocês serão amaldiçoados na cidade e serão amaldiçoados no campo.

[[v5-28-17]]

^<<v5-28-17,17>>^ A sua cesta e a sua amassadeira serão amaldiçoadas.

[[v5-28-18]]

^<<v5-28-18,18>>^ Os filhos do seu ventre serão amaldiçoados, como também as colheitas da sua terra, os bezerros e os cordeiros dos seus rebanhos.

[[v5-28-19]]

^<<v5-28-19,19>>^ Vocês serão amaldiçoados em tudo o que fizerem.

[[v5-28-20]]

^<<v5-28-20,20>>^ O Senhor enviará sobre vocês maldições, confusão e repreensão em tudo o que fizerem, até que vocês sejam destruídos e sofram repentina ruína pelo mal que praticaram ao se esquecerem dele.

[[v5-28-21]]

^<<v5-28-21,21>>^ O Senhor os encherá de doenças até bani-los da terra em que vocês estão entrando para dela tomar posse.

[[v5-28-22]]

^<<v5-28-22,22>>^ O Senhor os ferirá com doenças devastadoras, febre e inflamação, com calor abrasador e seca, com ferrugem e mofo, que os infestarão até que morram.

[[v5-28-23]]

^<<v5-28-23,23>>^ O céu sobre a sua cabeça será como bronze; o chão debaixo de vocês, como ferro.

[[v5-28-24]]

^<<v5-28-24,24>>^ Na sua terra o Senhor transformará a chuva em cinza e pó, que descerão do céu até que vocês sejam destruídos.

[[v5-28-25]]

^<<v5-28-25,25>>^ O Senhor fará que vocês sejam derrotados pelos inimigos. Vocês irão a eles por um caminho, e por sete fugirão, e vocês se tornarão motivo de horror para todos os reinos da terra.

[[v5-28-26]]

^<<v5-28-26,26>>^ Os seus cadáveres servirão de alimento para todas as aves do céu e para os animais da terra e não haverá quem os espante.

[[v5-28-27]]

^<<v5-28-27,27>>^ O Senhor os castigará com as úlceras do Egito e com tumores, feridas purulentas e sarna, males dos quais vocês não poderão curar-se.

[[v5-28-28]]

^<<v5-28-28,28>>^ O Senhor os afligirá com loucura, cegueira e confusão mental.

[[v5-28-29]]

^<<v5-28-29,29>>^ Ao meio-dia vocês ficarão tateando às voltas, como um cego na escuridão. Vocês não serão bem sucedidos em nada que fizerem; dia após dia serão oprimidos e roubados, sem que ninguém os salve.

[[v5-28-30]]

^<<v5-28-30,30>>^ Você ficará noivo de uma mulher, mas outro homem a possuirá. Construirá uma casa, mas não morará nela. Plantará uma vinha, mas não provará dos seus frutos.

[[v5-28-31]]

^<<v5-28-31,31>>^ O seu boi será abatido diante dos seus olhos, mas você não comerá da sua carne. O seu jumento lhe será tirado à força e não lhe será devolvido. As suas ovelhas serão dadas aos inimigos, e ninguém as livrará.

[[v5-28-32]]

^<<v5-28-32,32>>^ Os seus filhos e as suas filhas serão entregues a outra nação e os seus olhos se consumirão à espera deles, dia após dia, sem que você possa erguer uma só mão para trazê-los de volta.

[[v5-28-33]]

^<<v5-28-33,33>>^ Um povo que vocês não conhecem comerá aquilo que a terra e o seu trabalho produzirem, e vocês sofrerão opressão cruel todos os seus dias.

[[v5-28-34]]

^<<v5-28-34,34>>^ Aquilo que os seus olhos virem os levarão à loucura.

[[v5-28-35]]

^<<v5-28-35,35>>^ O Senhor afligirá os seus joelhos e as suas pernas com feridas dolorosas e incuráveis, e que se espalharão sobre vocês desde a sola do pé até o alto da cabeça.

[[v5-28-36]]

^<<v5-28-36,36>>^ O Senhor os levará, e também o rei que os governar, a uma nação que você e seus antepassados nunca conheceram. Lá vocês adorarão outros deuses, deuses de madeira e de pedra.

[[v5-28-37]]

^<<v5-28-37,37>>^ Vocês serão motivo de horror e motivo de zombaria e de riso para todas as nações para onde o Senhor o levar.

[[v5-28-38]]

^<<v5-28-38,38>>^ Vocês semearão muito em sua terra, mas colherão bem pouco, porque gafanhotos devorarão quase tudo.

[[v5-28-39]]

^<<v5-28-39,39>>^ Plantarão vinhas e as cultivarão, mas não beberão o vinho nem colherão as uvas, porque os vermes as comerão.

[[v5-28-40]]

^<<v5-28-40,40>>^ Vocês terão oliveiras em todo o país, mas vocês mesmos não utilizarão o azeite, porque as azeitonas cairão.

[[v5-28-41]]

^<<v5-28-41,41>>^ Os seus filhos e filhas não ficarão com vocês, porque serão levados para o cativeiro.

[[v5-28-42]]

^<<v5-28-42,42>>^ Enxames de gafanhotos se apoderarão de todas as suas árvores e das plantações da sua terra.

[[v5-28-43]]

^<<v5-28-43,43>>^ Os estrangeiros que vivem no meio de vocês progredirão cada vez mais, e cada vez mais vocês regredirão.

[[v5-28-44]]

^<<v5-28-44,44>>^ Eles lhes emprestarão dinheiro, mas vocês não emprestarão a eles. Eles serão a cabeça, e vocês serão a cauda.

[[v5-28-45]]

^<<v5-28-45,45>>^ Todas essas maldições cairão sobre vocês. Elas o perseguirão e o alcançarão até que sejam destruídos, porque não obedeceram ao Senhor, ao seu Deus, nem guardaram os mandamentos e decretos que ele lhes deu.

[[v5-28-46]]

^<<v5-28-46,46>>^ Essas maldições serão um sinal e um prodígio para vocês e para os seus descendentes para sempre.

[[v5-28-47]]

^<<v5-28-47,47>>^ Uma vez que vocês não serviram com júbilo e alegria ao Senhor, ao seu Deus, na época da prosperidade,

[[v5-28-48]]

^<<v5-28-48,48>>^ então, em meio à fome e à sede, em nudez e pobreza extrema, vocês servirão aos inimigos que o Senhor enviará contra vocês. Ele porá um jugo de ferro sobre o seu pescoço, até que os tenham destruído.

[[v5-28-49]]

^<<v5-28-49,49>>^ O Senhor trará, de um lugar longínquo, dos confins da terra, uma nação que virá contra vocês como a águia em mergulho, nação cujo idioma não compreenderão,

[[v5-28-50]]

^<<v5-28-50,50>>^ nação de aparência feroz, sem respeito pelos idosos nem piedade para com os moços.

[[v5-28-51]]

^<<v5-28-51,51>>^ Ela devorará as crias dos seus animais e as plantações da sua terra até que vocês sejam destruídos. Ela não lhes deixará cereal, vinho, azeite, como também nenhum bezerro ou cordeiro dos seus rebanhos, até que vocês sejam arruinados.

[[v5-28-52]]

^<<v5-28-52,52>>^ Ela sitiará todas as cidades da sua terra, até que caiam os altos muros fortificados em que vocês confiam. Sitiará todas as suas cidades, em toda a terra que o Senhor, o seu Deus, lhe dá.

[[v5-28-53]]

^<<v5-28-53,53>>^ Por causa do sofrimento que o seu inimigo lhes infligirá durante o cerco, vocês comerão o fruto do próprio ventre, a carne dos filhos e filhas que o Senhor, o seu Deus, lhes deu.

[[v5-28-54]]

^<<v5-28-54,54>>^ Até mesmo o homem mais gentil e educado entre vocês não terá compaixão do seu irmão, da mulher que ama e dos filhos que sobreviverem,

[[v5-28-55]]

^<<v5-28-55,55>>^ de modo que não dará a nenhum deles nenhum pedaço da carne dos seus filhos que estiver comendo, pois nada lhe sobrará devido aos sofrimentos que o seu inimigo lhe infligirá durante o cerco de todas as suas cidades.

[[v5-28-56]]

^<<v5-28-56,56>>^ A mulher mais gentil e delicada entre vocês, tão delicada e gentil que não ousaria encostar no chão a sola do pé, será mesquinha com o marido a quem ama e com o filho e a filha,

[[v5-28-57]]

^<<v5-28-57,57>>^ não lhes dando a placenta do ventre nem os filhos que gerar. Pois a sua intenção é comê-los secretamente durante o cerco e no sofrimento que o seu inimigo infligirá a você em suas cidades.

[[v5-28-58]]

^<<v5-28-58,58>>^ Se vocês não seguirem fielmente todas as palavras desta lei, escritas neste livro, e não temerem este nome glorioso e terrível, o Senhor, o seu Deus,

[[v5-28-59]]

^<<v5-28-59,59>>^ ele enviará pestes terríveis sobre vocês e sobre os seus descendentes, desgraças horríveis e prolongadas, doenças graves e persistentes.

[[v5-28-60]]

^<<v5-28-60,60>>^ Ele trará sobre vocês todas as temíveis doenças do Egito, e vocês as contrairão.

[[v5-28-61]]

^<<v5-28-61,61>>^ O Senhor também fará vir sobre vocês todo tipo de enfermidade e desgraça não registradas neste Livro da Lei, até que sejam destruídos.

[[v5-28-62]]

^<<v5-28-62,62>>^ Vocês, que no passado foram tantos quanto as estrelas do céu, ficarão reduzidos a um pequeno número, porque não obedeceram ao Senhor, ao seu Deus.

[[v5-28-63]]

^<<v5-28-63,63>>^ Assim como foi agradável ao Senhor fazê-los prosperar e aumentar em número, também lhe será agradável arruiná-los e destruí-los. Vocês serão desarraigados da terra em que estão entrando para dela tomar posse.

[[v5-28-64]]

^<<v5-28-64,64>>^ Então o Senhor os espalhará pelas nações, de um lado ao outro da terra. Ali vocês adorarão outros deuses; deuses de madeira e de pedra, que vocês e os seus antepassados nunca conheceram.

[[v5-28-65]]

^<<v5-28-65,65>>^ No meio daquelas nações vocês não encontrarão repouso, nem mesmo um lugar de descanso para a sola dos pés. Lá o Senhor lhes dará coração desesperado, olhos exaustos de tanto esperar, e alma ansiosa.

[[v5-28-66]]

^<<v5-28-66,66>>^ Vocês viverão em constante incerteza, cheios de terror, dia e noite, sem nenhuma segurança na vida.

[[v5-28-67]]

^<<v5-28-67,67>>^ De manhã dirão: "Quem me dera fosse noite! " E de noite: "Ah, quem me dera fosse dia! ", por causa do terror que lhes encherá o coração e por aquilo que os seus olhos verão.

[[v5-28-68]]

^<<v5-28-68,68>>^ O Senhor os enviará de volta ao Egito, ou em navios ou pelo caminho que eu lhes disse que nunca mais poderiam percorrer. Lá vocês serão postos à venda como escravos e escravas, mas ninguém os comprará.

'''

xref:005-deuteronomio/005-deuteronomio-027.adoc#v5-27-0[&#60; Capítulo Anterior] | <<v5-28-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-029.adoc#v5-29-0[Próximo Capítulo &#62;]