include::./index.adoc[]

[[v5-16-0]]
=== Deuteronômio, 16
// nvi ?, NVI - Nova Versão Internacional

[[v5-16-1]]

^<<v5-16-1,1>>^ Observem o mês de abibe e celebrem a Páscoa do Senhor, do seu Deus, pois no mês de abibe, de noite, ele os tirou do Egito.

[[v5-16-2]]

^<<v5-16-2,2>>^ Ofereçam como sacrifício da Páscoa ao Senhor, ao seu Deus, um animal dos rebanhos de bois ou de ovelhas no local que o Senhor escolher para habitação do seu Nome.

[[v5-16-3]]

^<<v5-16-3,3>>^ Não o comam com pão fermentado, mas durante sete dias comam pães sem fermento, o pão da aflição, pois foi às pressas que vocês saíram do Egito, para que todos os dias da sua vida vocês se lembrem da época em que saíram do Egito.

[[v5-16-4]]

^<<v5-16-4,4>>^ Durante sete dias, não permitam que seja encontrado fermento com vocês em toda a sua terra. Tampouco permitam que alguma carne sacrificada à tarde do primeiro dia permaneça até a manhã seguinte.

[[v5-16-5]]

^<<v5-16-5,5>>^ Não ofereçam o sacrifício da Páscoa em nenhuma das cidades que o Senhor, o seu Deus, lhe der;

[[v5-16-6]]

^<<v5-16-6,6>>^ sacrifique-a apenas no local que ele escolher para habitação do seu Nome. Ali vocês oferecerão o sacrifício da Páscoa à tarde, ao pôr-do-sol, na data da sua partida do Egito.

[[v5-16-7]]

^<<v5-16-7,7>>^ Vocês cozinharão a carne do animal e a comerão no local que o Senhor, o seu Deus, escolher. E, pela manhã, cada um de vocês voltará para a sua tenda.

[[v5-16-8]]

^<<v5-16-8,8>>^ Durante seis dias comam pão sem fermento, e no sétimo dia façam uma assembléia em honra do Senhor, ao seu Deus; não façam trabalho algum.

[[v5-16-9]]

^<<v5-16-9,9>>^ Contem sete semanas a partir da época em que vocês começarem a colheita do cereal.

[[v5-16-10]]

^<<v5-16-10,10>>^ Celebrem então a festa das semanas ao Senhor, ao seu Deus, e tragam uma oferta voluntária conforme às bênçãos recebidas do Senhor, do seu Deus.

[[v5-16-11]]

^<<v5-16-11,11>>^ E alegrem-se perante o Senhor, o seu Deus, no local que ele escolher para habitação do seu Nome, junto com os seus filhos e as suas filhas, os seus servos e as suas servas, os levitas que vivem na sua cidade, os estrangeiros, os órfãos e as viúvas que vivem com vocês.

[[v5-16-12]]

^<<v5-16-12,12>>^ Lembrem-se de que vocês foram escravos no Egito e obedeçam fielmente a estes decretos.

[[v5-16-13]]

^<<v5-16-13,13>>^ Celebrem também a festa das cabanas durante sete dias, depois que ajuntarem o produto da eira e do lagar.

[[v5-16-14]]

^<<v5-16-14,14>>^ Alegrem-se nessa festa com os seus filhos e as suas filhas, os seus servos e as suas servas, os levitas, os estrangeiros, os órfãos e as viúvas que vivem na sua cidade.

[[v5-16-15]]

^<<v5-16-15,15>>^ Durante sete dias celebrem a festa, dedicada ao Senhor, ao seu Deus, no local que o Senhor escolher. Pois o Senhor, o seu Deus, os abençoará em toda a sua colheita e em todo o trabalho de suas mãos, e a sua alegria será completa.

[[v5-16-16]]

^<<v5-16-16,16>>^ Três vezes por ano todos os seus homens se apresentarão ao Senhor, ao seu Deus, no local que ele escolher, por ocasião da festa dos pães sem fermento, da festa das semanas e da festa das cabanas. Nenhum deles deverá apresentar-se ao Senhor de mãos vazias:

[[v5-16-17]]

^<<v5-16-17,17>>^ cada um de vocês trará uma dádiva conforme as bênçãos recebidas do Senhor, do seu Deus.

[[v5-16-18]]

^<<v5-16-18,18>>^ Nomeiem juízes e oficiais para cada uma de suas tribos em todas as cidades que o Senhor, o seu Deus, lhes dá, para que eles julguem o povo com justiça.

[[v5-16-19]]

^<<v5-16-19,19>>^ Não pervertam a justiça nem mostrem parcialidade. Não aceitem suborno, pois o suborno cega até os sábios e prejudica a causa dos justos.

[[v5-16-20]]

^<<v5-16-20,20>>^ Siga única e exclusivamente a justiça, para que tenham vida e tomem posse da terra que o Senhor, o seu Deus, lhes dá.

[[v5-16-21]]

^<<v5-16-21,21>>^ Não ergam nenhum poste sagrado além do altar que construírem em honra do Senhor, do seu Deus,

[[v5-16-22]]

^<<v5-16-22,22>>^ e não levantem nenhuma coluna sagrada, pois isto é detestável para o Senhor, o seu Deus.

'''

xref:005-deuteronomio/005-deuteronomio-015.adoc#v5-15-0[&#60; Capítulo Anterior] | <<v5-16-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-017.adoc#v5-17-0[Próximo Capítulo &#62;]