include::./index.adoc[]

[[v5-33-0]]
=== Deuteronômio, 33
// nvi ?, NVI - Nova Versão Internacional

[[v5-33-1]]

^<<v5-33-1,1>>^ Esta é a bênção com a qual Moisés, homem de Deus, abençoou os israelitas antes da sua morte.

[[v5-33-2]]

^<<v5-33-2,2>>^ Ele disse: "O Senhor veio do Sinai e alvoreceu sobre eles desde o Seir, resplandeceu desde o monte Parã. Veio com miríades de santos desde o sul, desde as encostas de suas montanhas.

[[v5-33-3]]

^<<v5-33-3,3>>^ Certamente és tu que amas o povo; todos os santos estão em tuas mãos. A teus pés todos eles se prostram e de ti recebem instrução,

[[v5-33-4]]

^<<v5-33-4,4>>^ a lei que Moisés nos deu, a herança da assembléia de Jacó.

[[v5-33-5]]

^<<v5-33-5,5>>^ Ele era rei sobre Jesurum, quando os chefes do povo se reuniam, juntamente com as tribos de Israel.

[[v5-33-6]]

^<<v5-33-6,6>>^ "Que Rúben viva e não morra, mesmo sendo poucos os seus homens".

[[v5-33-7]]

^<<v5-33-7,7>>^ E disse a respeito de Judá: "Ouve, ó Senhor, o grito de Judá; traze-o para o seu povo. Que as suas próprias mãos sejam suficientes, e que haja auxílio contra os seus adversários! "

[[v5-33-8]]

^<<v5-33-8,8>>^ A respeito de Levi disse: "O teu Urim e o teu Tumim pertencem ao homem a quem favoreceste. Tu o provaste em Massá; disputaste com ele junto às águas de Meribá.

[[v5-33-9]]

^<<v5-33-9,9>>^ Levi disse do seu pai e da sua mãe: ‘Não tenho consideração por eles’. Não reconheceu os seus irmãos, Nem conheceu os próprios filhos, apesar de que guardaram a tua palavra e observaram a tua aliança.

[[v5-33-10]]

^<<v5-33-10,10>>^ Ele ensina as tuas ordenanças a Jacó e a tua lei a Israel. Ele te oferece incenso e holocaustos completos no teu altar.

[[v5-33-11]]

^<<v5-33-11,11>>^ Abençoa todos os seus esforços, ó Senhor, e aprova a obra das suas mãos. Despedaça os lombos dos seus adversários, dos que o odeiam, sejam quem forem".

[[v5-33-12]]

^<<v5-33-12,12>>^ A respeito de Benjamim disse: "Que o amado do Senhor descanse nele em segurança, pois ele o protege o tempo inteiro, e aquele a quem o Senhor ama descansa nos seus braços".

[[v5-33-13]]

^<<v5-33-13,13>>^ A respeito de José disse: "Que o Senhor abençoe a sua terra com o precioso orvalho que vem de cima, do céu, e com as águas das profundezas;

[[v5-33-14]]

^<<v5-33-14,14>>^ com o melhor que o sol amadurece e com o melhor que a lua possa dar;

[[v5-33-15]]

^<<v5-33-15,15>>^ com as dádivas mais bem escolhidas dos montes antigos e com a fertilidade das colinas eternas;

[[v5-33-16]]

^<<v5-33-16,16>>^ com os melhores frutos da terra e a sua plenitude, e o favor daquele que apareceu na sarça ardente. Que tudo isso repouse sobre a cabeça de José, sobre a fronte do escolhido entre os seus irmãos.

[[v5-33-17]]

^<<v5-33-17,17>>^ É majestoso como a primeira cria de um touro; seus chifres são os chifres de um boi selvagem, com os quais ferirá as nações, até os confins da terra. Assim são as dezenas de milhares de Efraim; assim são os milhares de Manassés".

[[v5-33-18]]

^<<v5-33-18,18>>^ A respeito de Zebulom disse: "Alegre-se, Zebulom, em suas viagens, e você, Issacar, em suas tendas.

[[v5-33-19]]

^<<v5-33-19,19>>^ Eles convocarão povos para o monte e ali oferecerão sacrifícios de justiça; farão um banquete com a riqueza dos mares, com os tesouros ocultos das praias".

[[v5-33-20]]

^<<v5-33-20,20>>^ A respeito de Gade disse: "Bendito é aquele que amplia os domínios de Gade! Gade fica à espreita como um leão; despedaça um braço e também a cabeça.

[[v5-33-21]]

^<<v5-33-21,21>>^ Escolheu para si o melhor; a porção do líder lhe foi reservada. Tornou-se o chefe do povo e executou a justa vontade do Senhor e os seus juízos sobre Israel".

[[v5-33-22]]

^<<v5-33-22,22>>^ A respeito de Dã disse: "Dã é um filhote de leão, que vem saltando desde Basã".

[[v5-33-23]]

^<<v5-33-23,23>>^ A respeito de Naftali disse: "Naftali tem fartura do favor do Senhor e está repleto de suas bênçãos; suas posses estendem-se para o sul, em direção ao mar".

[[v5-33-24]]

^<<v5-33-24,24>>^ A respeito de Aser disse: "Bendito é Aser entre os filhos; seja ele favorecido por seus irmãos, e banhe os seus pés no azeite!

[[v5-33-25]]

^<<v5-33-25,25>>^ Sejam de ferro e bronze as trancas das suas portas, e dure a sua força como os seus dias.

[[v5-33-26]]

^<<v5-33-26,26>>^ "Não há ninguém como o Deus de Jesurum, que cavalga os céus para ajudá-lo, e cavalga as nuvens em sua majestade!

[[v5-33-27]]

^<<v5-33-27,27>>^ O Deus eterno é o seu refúgio, e para segurá-lo estão os braços eternos. Ele expulsará os inimigos da sua presença, dizendo: ‘Destrua-os! ’

[[v5-33-28]]

^<<v5-33-28,28>>^ Somente Israel viverá em segurança; a fonte de Jacó está segura numa terra de trigo e de vinho novo, onde os céus gotejam orvalho.

[[v5-33-29]]

^<<v5-33-29,29>>^ Como você é feliz, Israel! Quem é como você, povo salvo pelo Senhor? Ele é o seu abrigo, o seu ajudador e a sua espada gloriosa. Os seus inimigos se encolherão diante de você, mas você pisará os seus altos".

'''

xref:005-deuteronomio/005-deuteronomio-032.adoc#v5-32-0[&#60; Capítulo Anterior] | <<v5-33-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-034.adoc#v5-34-0[Próximo Capítulo &#62;]