include::./index.adoc[]

[[v5-9-0]]
=== Deuteronômio, 9
// nvi ?, NVI - Nova Versão Internacional

[[v5-9-1]]

^<<v5-9-1,1>>^ Ouça, ó Israel: Hoje você está atravessando o Jordão para entrar na terra e conquistar nações maiores e mais poderosas do que você, as quais têm cidades grandes, com muros que vão até o céu.

[[v5-9-2]]

^<<v5-9-2,2>>^ O povo é forte e alto. São enaquins! Você já ouviu falar deles e até conhece o que se diz: "Quem é capaz de resistir aos enaquins? "

[[v5-9-3]]

^<<v5-9-3,3>>^ Esteja, hoje, certo de que o Senhor, o seu Deus, ele mesmo, vai adiante de você como fogo consumidor. Ele os exterminará e os subjugará diante de você. E você os expulsará e os destruirá, como o Senhor lhe prometeu.

[[v5-9-4]]

^<<v5-9-4,4>>^ Depois que o Senhor, o seu Deus, os tiver expulsado da presença de você, não diga a si mesmo: "O Senhor nos trouxe aqui para tomarmos posse desta terra por causa da nossa justiça". Não! É devido à impiedade destas nações que o Senhor vai expulsá-las da presença de você.

[[v5-9-5]]

^<<v5-9-5,5>>^ Não é por causa de sua justiça ou de sua retidão que você conquistará a terra deles. Mas é por causa da maldade destas nações que o Senhor, o seu Deus, as expulsará de diante de você, para cumprir a palavra que o Senhor prometeu, sob juramento, aos seus antepassados, Abraão, Isaque e Jacó.

[[v5-9-6]]

^<<v5-9-6,6>>^ Portanto, esteja certo de que não é por causa de sua justiça que o Senhor seu Deus lhe dá esta boa terra para dela tomar posse, pois você é um povo obstinado.

[[v5-9-7]]

^<<v5-9-7,7>>^ Lembrem-se disto e jamais esqueçam como vocês provocaram a ira do Senhor, o seu Deus, no deserto. Desde o dia em que saíram do Egito até chegarem aqui, vocês têm sido rebeldes contra o Senhor.

[[v5-9-8]]

^<<v5-9-8,8>>^ Até mesmo em Horebe vocês provocaram o Senhor à ira, e ele ficou furioso, a ponto de querer exterminá-los.

[[v5-9-9]]

^<<v5-9-9,9>>^ Quando subi o monte para receber as tábuas de pedra, as tábuas da aliança que o Senhor tinha feito com vocês, fiquei no monte quarenta dias e quarenta noites; não comi pão, nem bebi água.

[[v5-9-10]]

^<<v5-9-10,10>>^ O Senhor me deu as duas tábuas de pedra escritas pelo dedo de Deus. Nelas estavam escritas todas as palavras que o Senhor proclamou a vocês no monte, de dentro do fogo, no dia da assembléia.

[[v5-9-11]]

^<<v5-9-11,11>>^ Passados os quarenta dias e quarenta noites, o Senhor me deu as duas tábuas de pedra, as tábuas da aliança,

[[v5-9-12]]

^<<v5-9-12,12>>^ e me disse: "Desça imediatamente, pois o seu povo, que você tirou do Egito, corrompeu-se. Eles se afastaram bem depressa do caminho que eu lhes ordenei e fizeram um ídolo de metal para si".

[[v5-9-13]]

^<<v5-9-13,13>>^ E o Senhor me disse: "Vejo que este povo é realmente um povo obstinado!

[[v5-9-14]]

^<<v5-9-14,14>>^ Deixe que eu os destrua e apague o nome deles de debaixo do céu. E farei de você uma nação mais forte e mais numerosa do que eles".

[[v5-9-15]]

^<<v5-9-15,15>>^ Então voltei e desci do monte, enquanto este ardia em chamas. E as duas tábuas da aliança estavam em minhas mãos.

[[v5-9-16]]

^<<v5-9-16,16>>^ E vi que vocês tinham pecado contra o Senhor, o Deus de vocês. Fizeram para si um ídolo de metal em forma de bezerro. Bem depressa vocês se desviaram do caminho que o Senhor, o Deus de vocês, lhes tinha ordenado.

[[v5-9-17]]

^<<v5-9-17,17>>^ Então peguei as duas tábuas e as lancei das minhas mãos, quebrando-as diante dos olhos de vocês.

[[v5-9-18]]

^<<v5-9-18,18>>^ Depois prostrei-me perante o Senhor outros quarenta dias e quarenta noites; não comi pão, nem bebi água, por causa do grande pecado que vocês tinham cometido, fazendo o que o Senhor reprova, provocando a ira dele.

[[v5-9-19]]

^<<v5-9-19,19>>^ Tive medo da ira e do furor do Senhor, pois ele estava suficientemente irado para destruí-los, mas de novo o Senhor me escutou.

[[v5-9-20]]

^<<v5-9-20,20>>^ O Senhor irou-se contra Arão a ponto de querer destruí-lo, mas naquela ocasião também orei por Arão.

[[v5-9-21]]

^<<v5-9-21,21>>^ Então peguei o bezerro, o bezerro do pecado de vocês, e o queimei no fogo; depois o esmigalhei e o moí até virar pó, e o joguei no riacho que desce do monte.

[[v5-9-22]]

^<<v5-9-22,22>>^ Além disso, vocês tornaram a provocar o Senhor à ira em Taberá, em Massá e em Quibrote-Hataavá.

[[v5-9-23]]

^<<v5-9-23,23>>^ E, quando o Senhor os enviou de Cades-Barnéia, disse: "Entrem lá e tomem posse da terra que lhes dei". Mas vocês se rebelaram contra a ordem do Senhor, do seu Deus. Não confiaram nele, nem lhe obedeceram.

[[v5-9-24]]

^<<v5-9-24,24>>^ Vocês têm sido rebeldes contra o Senhor desde que os conheço.

[[v5-9-25]]

^<<v5-9-25,25>>^ Fiquei prostrado perante o Senhor durante aqueles quarenta dias e quarenta noites porque o Senhor tinha dito que ia destruí-los.

[[v5-9-26]]

^<<v5-9-26,26>>^ Foi quando orei ao Senhor, dizendo: Ó Soberano Senhor, não destruas o teu povo, a tua própria herança! Tu o redimiste com a tua grandeza e o tiraste da terra do Egito com mão poderosa.

[[v5-9-27]]

^<<v5-9-27,27>>^ Lembra-te de teus servos Abraão, Isaque e Jacó. Não leves em conta a obstinação deste povo, a sua maldade e o seu pecado,

[[v5-9-28]]

^<<v5-9-28,28>>^ se não os habitantes da terra de onde nos tiraste dirão: "Como o Senhor não conseguiu levá-los à terra que lhes havia prometido, e como ele os odiava, tirou-os para fazê-los morrer no deserto".

[[v5-9-29]]

^<<v5-9-29,29>>^ Mas eles são o teu povo, a tua herança, que tiraste do Egito com o teu grande poder e com o teu braço forte.

'''

xref:005-deuteronomio/005-deuteronomio-008.adoc#v5-8-0[&#60; Capítulo Anterior] | <<v5-9-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-010.adoc#v5-10-0[Próximo Capítulo &#62;]