include::./index.adoc[]

[[v5-18-0]]
=== Deuteronômio, 18
// nvi ?, NVI - Nova Versão Internacional

[[v5-18-1]]

^<<v5-18-1,1>>^ Os sacerdotes levitas e todo o restante da tribo de Levi, não terão posse nem herança em Israel. Viverão das ofertas sacrificadas para o Senhor, preparadas no fogo, pois esta é a sua herança.

[[v5-18-2]]

^<<v5-18-2,2>>^ Não terão herança alguma entre os seus compatriotas; o Senhor é a sua herança, conforme lhes prometeu.

[[v5-18-3]]

^<<v5-18-3,3>>^ Quando o povo sacrificar um novilho ou uma ovelha, os sacerdotes receberão a porção devida: o espádua, as queixadas e o estômago.

[[v5-18-4]]

^<<v5-18-4,4>>^ Vocês terão que dar-lhes as primícias do trigo, do vinho e do azeite, e a primeira lã da tosquia das ovelhas,

[[v5-18-5]]

^<<v5-18-5,5>>^ pois, de todas as tribos, o Senhor, o seu Deus, escolheu os levitas e os seus descendentes para estarem na presença do Senhor, e para ministrarem sempre em seu nome.

[[v5-18-6]]

^<<v5-18-6,6>>^ Se um levita que estiver morando em qualquer cidade de Israel, desejar ir ao local escolhido pelo Senhor,

[[v5-18-7]]

^<<v5-18-7,7>>^ poderá ministrar em nome do Senhor, do seu Deus, à semelhança de todos os outros levitas que ali servem na presença do Senhor.

[[v5-18-8]]

^<<v5-18-8,8>>^ Ele receberá uma porção de alimento igual à dos outros levitas; além disso, ficará com o que receber com a venda dos bens da sua família.

[[v5-18-9]]

^<<v5-18-9,9>>^ Quando entrarem na terra que o Senhor, o seu Deus, lhes dá, não procurem imitar as coisas repugnantes que as nações de lá praticam.

[[v5-18-10]]

^<<v5-18-10,10>>^ Não permitam que se ache alguém entre vocês que queime em sacrifício o seu filho ou a sua filha; que pratique adivinhação, ou dedique-se à magia, ou faça presságios, ou pratique feitiçaria

[[v5-18-11]]

^<<v5-18-11,11>>^ ou faça encantamentos; que seja médium ou espírita ou que consulte os mortos.

[[v5-18-12]]

^<<v5-18-12,12>>^ O Senhor têm repugnância por quem pratica essas coisas, e é por causa dessas abominações que o Senhor, o seu Deus, vai expulsar aquelas nações da presença de vocês.

[[v5-18-13]]

^<<v5-18-13,13>>^ Permaneçam inculpáveis perante o Senhor, o seu Deus.

[[v5-18-14]]

^<<v5-18-14,14>>^ As nações que vocês vão expulsar dão ouvidos aos que praticam magia e adivinhação. Mas, a vocês, o Senhor, o seu Deus, não permitiu tais práticas.

[[v5-18-15]]

^<<v5-18-15,15>>^ O Senhor, o seu Deus, levantará do meio de seus próprios irmãos um profeta como eu; ouçam-no.

[[v5-18-16]]

^<<v5-18-16,16>>^ Pois foi isso que pediram ao Senhor, ao seu Deus, em Horebe, no dia em que se reuniram, quando disseram: "Não queremos ouvir a voz do Senhor, do nosso Deus, nem ver o seu grande fogo, se não morreremos! "

[[v5-18-17]]

^<<v5-18-17,17>>^ O Senhor me disse: "Eles têm razão!

[[v5-18-18]]

^<<v5-18-18,18>>^ Levantarei do meio dos seus irmãos um profeta como você; porei minhas palavras na sua boca, e ele lhes dirá tudo o que eu lhe ordenar.

[[v5-18-19]]

^<<v5-18-19,19>>^ Se alguém não ouvir as minhas palavras, que o profeta falará em meu nome, eu mesmo lhe pedirei contas.

[[v5-18-20]]

^<<v5-18-20,20>>^ Mas o profeta que ousar falar em meu nome alguma coisa que não lhe ordenei, ou que falar em nome de outros deuses, terá que ser morto".

[[v5-18-21]]

^<<v5-18-21,21>>^ Mas vocês perguntem a si mesmos: "Como saberemos se uma mensagem não vem do Senhor? "

[[v5-18-22]]

^<<v5-18-22,22>>^ Se o que o profeta proclamar em nome do Senhor não acontecer nem se cumprir, essa mensagem não vem do Senhor. Aquele profeta falou com presunção. Não tenham medo dele.

'''

xref:005-deuteronomio/005-deuteronomio-017.adoc#v5-17-0[&#60; Capítulo Anterior] | <<v5-18-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-019.adoc#v5-19-0[Próximo Capítulo &#62;]