include::./index.adoc[]

[[v5-22-0]]
=== Deuteronômio, 22
// nvi ?, NVI - Nova Versão Internacional

[[v5-22-1]]

^<<v5-22-1,1>>^ Se o boi ou a ovelha de um israelita se extraviar e você o vir, não ignore o fato, mas faça questão de levar o animal de volta ao dono.

[[v5-22-2]]

^<<v5-22-2,2>>^ Se este não morar perto de você ou se você não conhecê-lo, leve o animal para casa e fique com ele até que seu compatriota venha procurá-lo e você possa devolvê-lo.

[[v5-22-3]]

^<<v5-22-3,3>>^ Faça o mesmo com o jumento, com a capa e com qualquer coisa perdida que encontrar. Não ignore o fato.

[[v5-22-4]]

^<<v5-22-4,4>>^ Se você vir o jumento ou o boi de um israelita caído no caminho, não o ignore. Ajude-o a pôr o animal em pé.

[[v5-22-5]]

^<<v5-22-5,5>>^ A mulher não usará roupas de homem, e o homem não usará roupas de mulher, pois o Senhor, o seu Deus, tem aversão por todo aquele que assim procede.

[[v5-22-6]]

^<<v5-22-6,6>>^ Se você passar por um ninho de passarinho junto ao caminho, seja numa árvore ou no chão, e a mãe estiver sobre os filhotes ou sobre os ovos, não apanhe a mãe com os filhotes.

[[v5-22-7]]

^<<v5-22-7,7>>^ Você poderá apanhar os filhotes, mas deixe a mãe solta, para que tudo vá bem com você e você tenha vida longa.

[[v5-22-8]]

^<<v5-22-8,8>>^ Quando algum de vocês construir uma casa nova, faça um parapeito em torno do terraço, para que não traga sobre a sua casa a culpa pelo derramamento de sangue inocente, caso alguém caia do terraço.

[[v5-22-9]]

^<<v5-22-9,9>>^ Não plantem dois tipos de semente em sua vinha; se o fizerem, tanto a semente que plantarem como o fruto da vinha estarão contaminados.

[[v5-22-10]]

^<<v5-22-10,10>>^ Não arem a terra usando um boi e um jumento sob o mesmo jugo.

[[v5-22-11]]

^<<v5-22-11,11>>^ Não usem roupas de lã e de linho misturados no mesmo tecido.

[[v5-22-12]]

^<<v5-22-12,12>>^ Façam borlas nas quatro pontas do manto que vocês usam para cobrir-se.

[[v5-22-13]]

^<<v5-22-13,13>>^ Se um homem casar-se e, depois de deitar-se com a mulher, rejeitá-la

[[v5-22-14]]

^<<v5-22-14,14>>^ e falar mal dela e difamá-la, dizendo: "Casei-me com esta mulher, mas quando me cheguei a ela, descobri que não era mais virgem",

[[v5-22-15]]

^<<v5-22-15,15>>^ o pai e a mãe da moça trarão aos líderes da cidade, junto à porta, a prova da sua virgindade.

[[v5-22-16]]

^<<v5-22-16,16>>^ Então o pai da moça dirá aos líderes: "Dei a minha filha em casamento a este homem, mas ele a rejeita.

[[v5-22-17]]

^<<v5-22-17,17>>^ Ele também a difamou e disse: ‘Descobri que a sua filha não era virgem’. Mas aqui está a prova da virgindade da minha filha". Então os pais dela apresentarão a prova aos líderes da cidade,

[[v5-22-18]]

^<<v5-22-18,18>>^ e eles castigarão o homem.

[[v5-22-19]]

^<<v5-22-19,19>>^ Aplicarão a ele a multa de cem peças de prata, que serão dados ao pai da moça, pois esse homem prejudicou a reputação de uma virgem israelita. E ele não poderá divorciar-se dela enquanto viver.

[[v5-22-20]]

^<<v5-22-20,20>>^ Se, contudo, a acusação for verdadeira e não se encontrar prova de virgindade da moça,

[[v5-22-21]]

^<<v5-22-21,21>>^ ela será levada à porta da casa do seu pai e ali os homens da sua cidade a apedrejarão até à morte. Ela cometeu um ato vergonhoso em Israel, prostituindo-se enquanto estava na casa de seu pai. Eliminem o mal do meio de vocês.

[[v5-22-22]]

^<<v5-22-22,22>>^ Se um homem for surpreendido deitado com a mulher de outro, os dois terão que morrer, o homem e a mulher com quem se deitou. Eliminem o mal do meio de Israel.

[[v5-22-23]]

^<<v5-22-23,23>>^ Se numa cidade um homem se encontrar com uma jovem prometida em casamento e se deitar com ela,

[[v5-22-24]]

^<<v5-22-24,24>>^ levem os dois à porta daquela cidade e apedrejem-nos até à morte: a moça porque estava na cidade e não gritou por socorro, e o homem porque desonrou a mulher doutro homem. Eliminem o mal do meio de vocês.

[[v5-22-25]]

^<<v5-22-25,25>>^ Se, contudo, um homem encontrar no campo uma jovem prometida em casamento e a forçar, somente o homem morrerá.

[[v5-22-26]]

^<<v5-22-26,26>>^ Não façam nada, pois ela não cometeu pecado algum que mereça a morte. Este caso é semelhante ao daquele que ataca e mata o seu próximo,

[[v5-22-27]]

^<<v5-22-27,27>>^ pois o homem encontrou a moça virgem no campo, e, ainda que a jovem prometida em casamento gritasse, ninguém poderia socorrê-la.

[[v5-22-28]]

^<<v5-22-28,28>>^ Se um homem se encontrar com uma moça sem compromisso de casamento e a violentar, e eles forem descobertos,

[[v5-22-29]]

^<<v5-22-29,29>>^ ele pagará ao pai da moça cinqüenta peças de prata. Terá que casar-se com a moça, pois a violentou. Jamais poderá divorciar-se dela.

[[v5-22-30]]

^<<v5-22-30,30>>^ Nenhum homem poderá tomar por mulher a mulher do seu pai, pois isso desonraria a cama de seu pai.

'''

xref:005-deuteronomio/005-deuteronomio-021.adoc#v5-21-0[&#60; Capítulo Anterior] | <<v5-22-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-023.adoc#v5-23-0[Próximo Capítulo &#62;]