include::./index.adoc[]

[[v5-32-0]]
=== Deuteronômio, 32
// nvi ?, NVI - Nova Versão Internacional

[[v5-32-1]]

^<<v5-32-1,1>>^ Escutem, ó céus, e eu falarei; ouça, ó terra, as palavras da minha boca.

[[v5-32-2]]

^<<v5-32-2,2>>^ Que o meu ensino caia como chuva e as minhas palavras desçam como orvalho, como chuva branda sobre o pasto novo, como garoa sobre tenras plantas.

[[v5-32-3]]

^<<v5-32-3,3>>^ Proclamarei o nome do Senhor. Louvem a grandeza do nosso Deus!

[[v5-32-4]]

^<<v5-32-4,4>>^ Ele é a Rocha, as suas obras são perfeitas, e todos os seus caminhos são justos. É Deus fiel, que não comete erros; justo e reto ele é.

[[v5-32-5]]

^<<v5-32-5,5>>^ Seus filhos têm agido corruptamente para com ele, e não como filhos; que vergonha! São geração pervertida e transviada.

[[v5-32-6]]

^<<v5-32-6,6>>^ É assim que retribuem ao Senhor, povo insensato e ignorante? Não é ele o Pai de vocês, o seu Criador, que os fez e os formou?

[[v5-32-7]]

^<<v5-32-7,7>>^ Lembrem-se dos dias do passado; considerem as gerações há muito passadas. Perguntem aos seus pais, e estes lhes contarão, aos seus líderes, e eles lhes explicarão.

[[v5-32-8]]

^<<v5-32-8,8>>^ Quando o Altíssimo deu às nações a sua herança, quando dividiu toda a humanidade, estabeleceu fronteiras para os povos de acordo com o número dos filhos de Israel.

[[v5-32-9]]

^<<v5-32-9,9>>^ Pois o povo preferido do Senhor é este povo, Jacó é a herança que lhe coube.

[[v5-32-10]]

^<<v5-32-10,10>>^ Numa terra deserta ele o encontrou, numa região árida e de ventos uivantes. Ele o protegeu e dele cuidou; guardou-o como a menina dos seus olhos,

[[v5-32-11]]

^<<v5-32-11,11>>^ como a águia que desperta a sua ninhada, paira sobre os seus filhotes, e depois estende as asas para apanhá-los, levando-os sobre elas.

[[v5-32-12]]

^<<v5-32-12,12>>^ O Senhor sozinho o levou; nenhum deus estrangeiro o ajudou.

[[v5-32-13]]

^<<v5-32-13,13>>^ Ele o fez cavalgar nos lugares altos da terra e o alimentou com o fruto dos campos. Ele o nutriu com mel tirado da rocha, e com óleo extraído do penhasco pedregoso,

[[v5-32-14]]

^<<v5-32-14,14>>^ com coalhada e leite do gado e do rebanho, e com cordeiros e bodes cevados; com os melhores carneiros de Basã e com as mais excelentes sementes de trigo. Você bebeu o espumoso sangue das uvas.

[[v5-32-15]]

^<<v5-32-15,15>>^ Jesurum engordou e deu pontapés; você engordou, tornou-se pesado e farto de alimentos. Abandonou o Deus que o fez e rejeitou a Rocha, que é o seu Salvador.

[[v5-32-16]]

^<<v5-32-16,16>>^ Eles o deixaram com ciúmes por causa dos deuses estrangeiros, e o provocaram com os seus ídolos abomináveis.

[[v5-32-17]]

^<<v5-32-17,17>>^ Sacrificaram a demônios que não são Deus, a deuses que não conheceram, a deuses que surgiram recentemente, a deuses que os seus antepassados não adoraram.

[[v5-32-18]]

^<<v5-32-18,18>>^ Vocês abandonaram a Rocha, que os gerou; vocês se esqueceram do Deus que os fez nascer.

[[v5-32-19]]

^<<v5-32-19,19>>^ O Senhor viu isso e os rejeitou, porque foi provocado pelos seus filhos e suas filhas.

[[v5-32-20]]

^<<v5-32-20,20>>^ "Esconderei o meu rosto deles", disse, "e verei qual o fim que terão; pois são geração perversa, filhos infiéis.

[[v5-32-21]]

^<<v5-32-21,21>>^ Provocaram-me os ciúmes com aquilo que nem deus é e irritaram-me com seus ídolos inúteis. Farei que tenham ciúmes de quem não é meu povo; eu os provocarei à ira por meio de uma nação insensata.

[[v5-32-22]]

^<<v5-32-22,22>>^ Pois um fogo foi aceso pela minha ira, fogo que queimará até às profundezas do Sheol. Ele devorará a terra e as suas colheitas e consumirá os alicerces dos montes.

[[v5-32-23]]

^<<v5-32-23,23>>^ "Amontoarei desgraças sobre eles e contra eles gastarei as minhas flechas.

[[v5-32-24]]

^<<v5-32-24,24>>^ Enviarei dentes de feras, uma fome devastadora, uma peste avassaladora e uma praga mortal; enviarei contra eles dentes de animais selvagens, e veneno de víboras que se arrastam no pó.

[[v5-32-25]]

^<<v5-32-25,25>>^ Nas ruas a espada os deixará sem filhos; em seus lares reinará o terror. Morrerão moços e moças, crianças e homens já grisalhos.

[[v5-32-26]]

^<<v5-32-26,26>>^ Eu disse que os dispersaria e que apagaria da humanidade a lembrança deles.

[[v5-32-27]]

^<<v5-32-27,27>>^ Mas temi a provocação do inimigo, que o adversário entendesse mal e dissesse: ‘A nossa mão triunfou; o Senhor nada fez’. "

[[v5-32-28]]

^<<v5-32-28,28>>^ É uma nação sem juízo; não têm discernimento.

[[v5-32-29]]

^<<v5-32-29,29>>^ Quem dera fossem sábios e entendessem; e compreendessem qual será o seu fim!

[[v5-32-30]]

^<<v5-32-30,30>>^ Como poderia um só homem perseguir mil, ou dois porem em fuga dez mil, a não ser que a sua Rocha os tivesse vendido, a não ser que o Senhor os tivesse abandonado?

[[v5-32-31]]

^<<v5-32-31,31>>^ Pois a rocha deles não é como a nossa Rocha, com o que até mesmo os nossos inimigos concordam.

[[v5-32-32]]

^<<v5-32-32,32>>^ A vinha deles é de Sodoma e das lavouras de Gomorra. Suas uvas estão cheias de veneno, e seus cachos, de amargura.

[[v5-32-33]]

^<<v5-32-33,33>>^ O vinho deles é a peçonha das serpentes, o veneno mortal das cobras.

[[v5-32-34]]

^<<v5-32-34,34>>^ "Acaso não guardei isto em segredo? Não o selei em meus tesouros?

[[v5-32-35]]

^<<v5-32-35,35>>^ A mim pertence a vingança e a retribuição. No devido tempo os pés deles escorregarão; o dia da sua desgraça está chegando e o seu próprio destino se apressa sobre eles. "

[[v5-32-36]]

^<<v5-32-36,36>>^ O Senhor julgará o seu povo e terá compaixão dos seus servos, quando vir que a força deles se esvaiu e que ninguém sobrou, nem escravo nem livre.

[[v5-32-37]]

^<<v5-32-37,37>>^ Ele dirá: "Agora, onde estão os seus deuses, a rocha em que se refugiaram,

[[v5-32-38]]

^<<v5-32-38,38>>^ os deuses que comeram a gordura dos seus sacrifícios e beberam o vinho das suas ofertas derramadas? Que eles se levantem para ajudá-los! Que eles lhes ofereçam abrigo!

[[v5-32-39]]

^<<v5-32-39,39>>^ "Vejam agora que eu sou o único, eu mesmo. Não há deus além de mim. Faço morrer e faço viver, feri e curarei, e ninguém é capaz de livrar-se da minha mão.

[[v5-32-40]]

^<<v5-32-40,40>>^ Ergo a minha mão para os céus e declaro: Juro pelo meu nome que,

[[v5-32-41]]

^<<v5-32-41,41>>^ quando eu afiar a minha espada refulgente e a minha mão empunhá-la para julgar, eu me vingarei dos meus adversários e retribuirei àqueles que me odeiam.

[[v5-32-42]]

^<<v5-32-42,42>>^ Embeberei as minhas flechas em sangue, enquanto a minha espada devorar carne: o sangue dos mortos e dos cativos, as cabeças dos líderes inimigos".

[[v5-32-43]]

^<<v5-32-43,43>>^ Cantem de alegria, ó nações, com o povo dele, pois ele vingará o sangue dos seus servos; retribuirá com vingança aos seus adversários e fará propiciação por sua terra e por seu povo.

[[v5-32-44]]

^<<v5-32-44,44>>^ Moisés veio com Josué, filho de Num, e recitou todas as palavras desta canção na presença do povo.

[[v5-32-45]]

^<<v5-32-45,45>>^ Quando Moisés terminou de recitar todas essas palavras a todo o Israel,

[[v5-32-46]]

^<<v5-32-46,46>>^ disse-lhes: "Guardem no coração todas as palavras que hoje lhes declarei solenemente, para que ordenem aos seus filhos que obedeçam fielmente a todas as palavras desta lei.

[[v5-32-47]]

^<<v5-32-47,47>>^ Elas não são palavras inúteis. São a sua vida. Por meio delas vocês viverão muito tempo na terra da qual tomarão posse do outro lado do Jordão".

[[v5-32-48]]

^<<v5-32-48,48>>^ Naquele mesmo dia o Senhor disse a Moisés:

[[v5-32-49]]

^<<v5-32-49,49>>^ "Suba as montanhas de Abarim, até o monte Nebo, em Moabe, em frente de Jericó, e contemple Canaã, a terra que dou aos israelitas como propriedade.

[[v5-32-50]]

^<<v5-32-50,50>>^ Ali, na montanha que você tiver subido, você morrerá e será reunido aos seus antepassados, assim como o seu irmão Arão morreu no monte Hor e foi reunido aos seus antepassados.

[[v5-32-51]]

^<<v5-32-51,51>>^ Assim será porque vocês dois foram infiéis para comigo na presença dos israelitas, junto às águas de Meribá, em Cades, no deserto de Zim, e porque vocês não sustentaram a minha santidade no meio dos israelitas.

[[v5-32-52]]

^<<v5-32-52,52>>^ Portanto, você verá a terra somente à distância, mas não entrará na terra que estou dando ao povo de Israel".

'''

xref:005-deuteronomio/005-deuteronomio-031.adoc#v5-31-0[&#60; Capítulo Anterior] | <<v5-32-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-033.adoc#v5-33-0[Próximo Capítulo &#62;]