include::./index.adoc[]

[[v5-4-0]]
=== Deuteronômio, 4
// nvi ?, NVI - Nova Versão Internacional

[[v5-4-1]]

^<<v5-4-1,1>>^ E agora, ó Israel, ouça os decretos e as leis que lhes estou ensinando a cumprir, para que vivam e tomem posse da terra, que o Senhor, o Deus dos seus antepassados, dá a vocês.

[[v5-4-2]]

^<<v5-4-2,2>>^ Nada acrescentem às palavras que eu lhes ordeno e delas nada retirem, mas obedeçam aos mandamentos do Senhor, o Deus de vocês, que eu lhes ordeno.

[[v5-4-3]]

^<<v5-4-3,3>>^ Vocês viram com os próprios olhos o que o Senhor fez em Baal-Peor. O Senhor, o seu Deus, destruiu do meio de vocês todos os que seguiram a Baal-Peor,

[[v5-4-4]]

^<<v5-4-4,4>>^ mas vocês, que permaneceram fiéis ao Senhor, o Deus de vocês, estão hoje todos vivos.

[[v5-4-5]]

^<<v5-4-5,5>>^ Eu lhes ensinei decretos e leis, como me ordenou o Senhor, o meu Deus, para que sejam cumpridos na terra na qual vocês estão entrando para dela tomar posse.

[[v5-4-6]]

^<<v5-4-6,6>>^ Vocês devem obedecer-lhes e cumpri-los, pois assim os outros povos verão a sabedoria e o discernimento de vocês. Quando eles ouvirem todos estes decretos dirão: "De fato esta grande nação é um povo sábio e inteligente".

[[v5-4-7]]

^<<v5-4-7,7>>^ Pois, que grande nação tem um Deus tão próximo como o Senhor, o nosso Deus, sempre que o invocamos?

[[v5-4-8]]

^<<v5-4-8,8>>^ Ou, que grande nação tem decretos e preceitos tão justos como esta lei que estou apresentando a vocês hoje?

[[v5-4-9]]

^<<v5-4-9,9>>^ Apenas cuidado! Muito cuidado, para que vocês nunca se esqueçam das coisas que os seus olhos viram; conservem-nas na memória por toda a sua vida. Contem-nas a seus filhos e a seus netos.

[[v5-4-10]]

^<<v5-4-10,10>>^ Houve um dia em que vocês estiveram diante do Senhor, o seu Deus, em Horebe, quando o Senhor me disse: "Reúna o povo diante de mim para ouvir as minhas palavras, a fim de que aprendam a me temer enquanto viverem sobre a terra, e as ensinem a seus filhos".

[[v5-4-11]]

^<<v5-4-11,11>>^ Vocês se aproximaram e ficaram ao pé do monte. O monte ardia em chamas que subiam até o céu, e estava envolvido por uma nuvem escura e densa.

[[v5-4-12]]

^<<v5-4-12,12>>^ Então o Senhor falou a vocês do meio do fogo. Vocês ouviram as palavras, mas não viram forma alguma; apenas se ouvia a voz.

[[v5-4-13]]

^<<v5-4-13,13>>^ Ele lhes anunciou a sua aliança, os Dez Mandamentos. E escreveu-os sobre duas tábuas de pedra e ordenou que os cumprissem.

[[v5-4-14]]

^<<v5-4-14,14>>^ Naquela ocasião, o Senhor mandou-me ensinar-lhes decretos e leis para que vocês os cumprissem na terra da qual vão tomar posse.

[[v5-4-15]]

^<<v5-4-15,15>>^ No dia em que o Senhor lhes falou do meio do fogo em Horebe, vocês não viram forma alguma. Portanto, tenham muito cuidado,

[[v5-4-16]]

^<<v5-4-16,16>>^ para que não se corrompam e não façam para si um ídolo, uma imagem de qualquer forma semelhante a homem ou mulher,

[[v5-4-17]]

^<<v5-4-17,17>>^ ou a qualquer animal da terra ou a qualquer ave que voa no céu,

[[v5-4-18]]

^<<v5-4-18,18>>^ ou a qualquer criatura que se move rente ao chão ou a qualquer peixe que vive nas águas debaixo da terra.

[[v5-4-19]]

^<<v5-4-19,19>>^ E para que, ao erguerem os olhos ao céu e virem o sol, a lua e as estrelas, todos os corpos celestes, vocês não se desviem e se prostrem diante deles, e prestem culto àquilo que o Senhor, o seu Deus, distribuiu a todos os povos debaixo do céu.

[[v5-4-20]]

^<<v5-4-20,20>>^ A vocês, o Senhor tomou e os tirou da fornalha de fundir ferro, do Egito, para serem o povo de sua herança, como hoje se pode ver.

[[v5-4-21]]

^<<v5-4-21,21>>^ O Senhor irou-se contra mim por causa de vocês e jurou que eu não atravessaria o Jordão e não entraria na boa terra que o Senhor, o seu Deus, está lhes dando por herança.

[[v5-4-22]]

^<<v5-4-22,22>>^ Eu morrerei nesta terra; não atravessarei o Jordão. Mas vocês atravessarão e tomarão posse daquela boa terra.

[[v5-4-23]]

^<<v5-4-23,23>>^ Tenham o cuidado de não esquecer da aliança que o Senhor, o seu Deus, fez com vocês; não façam para si ídolo algum com a forma de qualquer coisa que o Senhor, o seu Deus, proibiu.

[[v5-4-24]]

^<<v5-4-24,24>>^ Pois o Senhor, o seu Deus, é Deus zeloso; é fogo consumidor.

[[v5-4-25]]

^<<v5-4-25,25>>^ Quando vocês tiverem filhos e netos, e já estiverem a muito tempo na terra, e se corromperem e fizerem ídolos de qualquer tipo, fazendo o que o Senhor, o seu Deus, reprova, provocando a sua ira,

[[v5-4-26]]

^<<v5-4-26,26>>^ invoco hoje o céu e a terra como testemunhas contra vocês de que vocês serão rapidamente eliminados da terra, da qual estão tomando posse ao atravessar o Jordão. Vocês não viverão muito ali; serão totalmente destruídos.

[[v5-4-27]]

^<<v5-4-27,27>>^ O Senhor os espalhará entre os povos, e restarão apenas alguns de vocês entre as nações às quais o Senhor os levará.

[[v5-4-28]]

^<<v5-4-28,28>>^ Lá vocês prestarão culto a deuses de madeira e de pedra, deuses feitos por mãos humanas, deuses que não podem ver, nem ouvir, nem comer, nem cheirar.

[[v5-4-29]]

^<<v5-4-29,29>>^ E lá procurarão o Senhor, o seu Deus, e o acharão, se o procurarem de todo o seu coração e de toda a sua alma.

[[v5-4-30]]

^<<v5-4-30,30>>^ Quando vocês estiverem sofrendo e todas essas coisas tiverem acontecido com vocês, então, em dias futuros, vocês voltarão para o Senhor, o seu Deus, e lhe obedecerão.

[[v5-4-31]]

^<<v5-4-31,31>>^ Pois o Senhor, o seu Deus, é Deus misericordioso; ele não os abandonará, nem os destruirá nem se esquecerá da aliança que com juramento fez com os seus antepassados.

[[v5-4-32]]

^<<v5-4-32,32>>^ Perguntem, agora, aos tempos antigos, antes de vocês existirem, desde o dia em que Deus criou o homem sobre a terra. Perguntem de um lado ao outro do céu: Já aconteceu algo tão grandioso ou já se ouviu algo parecido?

[[v5-4-33]]

^<<v5-4-33,33>>^ Que povo ouviu a voz de Deus falando do meio do fogo, como vocês ouviram, e continua vivo?

[[v5-4-34]]

^<<v5-4-34,34>>^ Ou que deus decidiu tirar uma nação do meio de outra para lhe pertencer, com provas, sinais, maravilhas e lutas, com mão poderosa e braço forte, e com feitos temíveis e grandiosos, conforme tudo o que o Senhor fez por vocês no Egito, como vocês viram com os seus próprios olhos?

[[v5-4-35]]

^<<v5-4-35,35>>^ Tudo isso foi mostrado a vocês para que soubessem que o Senhor é Deus; e que não há outro além dele.

[[v5-4-36]]

^<<v5-4-36,36>>^ Do céu ele fez com que vocês ouvissem a sua voz, para discipliná-los. Na terra, mostrou-lhes o seu grande fogo, e vocês ouviram as suas palavras vindas do meio do fogo.

[[v5-4-37]]

^<<v5-4-37,37>>^ E porque amou os seus antepassados e escolheu a descendência deles, ele foi em pessoa tirá-los do Egito com o seu grande poder,

[[v5-4-38]]

^<<v5-4-38,38>>^ para expulsar diante de vocês nações maiores e mais fortes, a fim de fazê-los entrar e possuir como herança a terra deles, como hoje se vê.

[[v5-4-39]]

^<<v5-4-39,39>>^ Reconheçam isso hoje, e ponham no coração que o Senhor é Deus em cima nos céus e embaixo na terra. Não há nenhum outro.

[[v5-4-40]]

^<<v5-4-40,40>>^ Obedeçam aos seus decretos e mandamentos que hoje eu lhes ordeno, para que tudo vá bem com vocês e com seus descendentes, e para que vivam muito tempo na terra que o Senhor, o seu Deus, lhes dá para sempre.

[[v5-4-41]]

^<<v5-4-41,41>>^ Então Moisés separou três cidades a leste do Jordão,

[[v5-4-42]]

^<<v5-4-42,42>>^ para onde poderia fugir quem tivesse matado alguém sem intenção e sem premeditação. O perseguido poderia fugir para uma dessas cidades a fim de salvar a vida.

[[v5-4-43]]

^<<v5-4-43,43>>^ As cidades eram as seguintes: Bezer, no planalto do deserto, para a tribo de Rúben; Ramote, em Gileade, para a tribo de Gade; e Golã, em Basã, para a tribo de Manassés.

[[v5-4-44]]

^<<v5-4-44,44>>^ Esta é a lei que Moisés apresentou aos israelitas.

[[v5-4-45]]

^<<v5-4-45,45>>^ Estes são os mandamentos, os decretos e as ordenanças que Moisés promulgou como leis para os israelitas quando saíram do Egito,

[[v5-4-46]]

^<<v5-4-46,46>>^ do outro lado do Jordão, no vale fronteiro a Bete-Peor, na terra de Seom, rei dos amorreus, que habitava em Hesbom, a quem Moisés e os israelitas derrotaram quando saíram do Egito.

[[v5-4-47]]

^<<v5-4-47,47>>^ Eles tomaram posse da terra dele e da terra de Ogue, rei de Basã, os dois reis amorreus que viviam a leste do Jordão.

[[v5-4-48]]

^<<v5-4-48,48>>^ Essa terra estendia-se desde Aroer, na margem do ribeiro do Arnom, até o monte Siom, isto é, o Hermom,

[[v5-4-49]]

^<<v5-4-49,49>>^ e incluía toda a região da Arabá, a leste do Jordão, até o mar da Arabá, abaixo das encostas do Pisga.

'''

xref:005-deuteronomio/005-deuteronomio-003.adoc#v5-3-0[&#60; Capítulo Anterior] | <<v5-4-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-005.adoc#v5-5-0[Próximo Capítulo &#62;]