include::./index.adoc[]

[[v5-3-0]]
=== Deuteronômio, 3
// nvi ?, NVI - Nova Versão Internacional

[[v5-3-1]]

^<<v5-3-1,1>>^ Depois, voltamos e subimos rumo a Basã. Ogue, rei de Basã, atacou-nos com todo o seu exército, em Edrei.

[[v5-3-2]]

^<<v5-3-2,2>>^ O Senhor me disse: "Não tenha medo dele, pois eu o entreguei em suas mãos, com todo o seu exército, e dei-lhe também a terra dele. Você fará com ele como fez com Seom, rei dos amorreus, que habitava em Hesbom".

[[v5-3-3]]

^<<v5-3-3,3>>^ Então o Senhor, o nosso Deus, também nos entregou em nossas mãos Ogue, rei de Basã, e todo o seu exército. Nós os derrotamos, sem deixar nenhum sobrevivente.

[[v5-3-4]]

^<<v5-3-4,4>>^ Naquela ocasião conquistamos todas as suas cidades. Não houve cidades que não tomássemos. Foram sessenta cidades, em toda a região de Argobe, o reino de Ogue, em Basã.

[[v5-3-5]]

^<<v5-3-5,5>>^ Todas essas cidades eram fortificadas com muros altos e com portas e trancas. Além delas havia muitas cidades sem muros.

[[v5-3-6]]

^<<v5-3-6,6>>^ Nós as destruímos completamente, tal como havíamos feito com Seom, rei de Hesbom, destruindo todas as cidades, matando também os homens, as mulheres e as crianças.

[[v5-3-7]]

^<<v5-3-7,7>>^ Mas os animais todos e o despojo das cidades tomamos como espólio de guerra.

[[v5-3-8]]

^<<v5-3-8,8>>^ Foi assim que, naquela ocasião, tomamos desses dois reis amorreus o território a leste do Jordão, que vai desde o ribeiro do Arnom até o monte Hermom.

[[v5-3-9]]

^<<v5-3-9,9>>^ ( Os sidônios chamam o Hermom de Siriom; e os amorreus o chamam Senir. )

[[v5-3-10]]

^<<v5-3-10,10>>^ Conquistamos todas as cidades do planalto, e toda a Gileade, e também toda a Basã, até Salcá e Edrei, cidades do reino de Ogue, em Basã.

[[v5-3-11]]

^<<v5-3-11,11>>^ Ogue, rei de Basã, era o único sobrevivente dos refains. Sua cama era de ferro e tinha, pela medida comum, quatro metros de comprimento e um metro e oitenta centímetros de largura. Ela ainda está em Rabá dos amonitas.

[[v5-3-12]]

^<<v5-3-12,12>>^ Da terra da qual tomamos posse naquela época, o território que vai de Aroer, junto ao ribeiro do Arnom, até mais da metade dos montes de Gileade com as suas cidades, dei-o às tribos de Rúben e de Gade.

[[v5-3-13]]

^<<v5-3-13,13>>^ O restante de Gileade e também toda a Basã, o reino de Ogue, dei-o à metade da tribo de Manassés. ( Toda a região de Argobe em Basã era conhecida no passado como a terra dos refains.

[[v5-3-14]]

^<<v5-3-14,14>>^ Jair, um descendente de Manassés, conquistou toda a região de Argobe até à fronteira dos gesuritas e dos maacatitas; essa região recebeu o seu nome, de modo que até hoje Basã é chamada Povoados de Jair. )

[[v5-3-15]]

^<<v5-3-15,15>>^ E dei Gileade a Maquir.

[[v5-3-16]]

^<<v5-3-16,16>>^ Às tribos de Rúben e de Gade dei a região que vai de Gileade, até o ribeiro do Arnom ( a fronteira passava bem no meio do vale ) e até o vale do Jaboque, na fronteira dos amonitas.

[[v5-3-17]]

^<<v5-3-17,17>>^ Dei-lhe também a Arabá, tendo como fronteira ocidental o Jordão, desde Quinerete até o mar da Arabá, que é o mar Salgado, abaixo das encostas do Pisga.

[[v5-3-18]]

^<<v5-3-18,18>>^ Naquela ocasião eu lhes ordenei o seguinte: O Senhor, o Deus de vocês, deu-lhes esta terra para que dela tomem posse. Todos os guerreiros devem marchar à frente dos seus irmãos israelitas, armados para a guerra!

[[v5-3-19]]

^<<v5-3-19,19>>^ Deixem nas cidades que lhes dei as mulheres, as crianças e os grandes rebanhos, que eu sei que vocês possuem,

[[v5-3-20]]

^<<v5-3-20,20>>^ até que o Senhor conceda descanso aos seus outros irmãos israelitas como deu a vocês, e tomem eles posse da terra que o Senhor, o Deus de vocês, está dando a eles, do outro lado do Jordão. Depois vocês poderão retornar, cada um à propriedade que lhes dei.

[[v5-3-21]]

^<<v5-3-21,21>>^ Naquela ocasião também ordenei a Josué: "Você viu com os seus próprios olhos tudo o que o Senhor, o Deus de vocês, fez com estes dois reis. Assim o Senhor fará com todos os reinos pelos quais vocês terão que passar.

[[v5-3-22]]

^<<v5-3-22,22>>^ Não tenham medo deles. O Senhor, o Deus de vocês, é quem lutará por vocês".

[[v5-3-23]]

^<<v5-3-23,23>>^ Naquela ocasião implorei ao Senhor:

[[v5-3-24]]

^<<v5-3-24,24>>^ "Ó Soberano Senhor, tu começaste a mostrar a teu servo a tua grandeza e a tua mão poderosa! Que Deus existe no céu ou na terra que possa realizar as tuas obras e os teus feitos poderosos?

[[v5-3-25]]

^<<v5-3-25,25>>^ Deixa-me atravessar, eu te suplico, e ver a boa terra do outro lado do Jordão, a bela região montanhosa e o Líbano! "

[[v5-3-26]]

^<<v5-3-26,26>>^ Todavia, por causa de vocês, o Senhor irou-se contra mim e não quis me atender. "Basta", ele disse. "Não me fale mais sobre isso.

[[v5-3-27]]

^<<v5-3-27,27>>^ Suba ao ponto mais alto do Pisga e olhe para o Oeste, para o Norte, para o Sul, e para o Leste. Veja a terra com os seus próprios olhos, pois você não atravessará o Jordão.

[[v5-3-28]]

^<<v5-3-28,28>>^ Portanto, dê ordens a Josué, fortaleça-o e encoraje-o; porque será ele que atravessará à frente deste povo, e lhes repartirá por herança a terra que você apenas verá".

[[v5-3-29]]

^<<v5-3-29,29>>^ Então ficamos acampados no vale, diante de Bete-Peor.

'''

xref:005-deuteronomio/005-deuteronomio-002.adoc#v5-2-0[&#60; Capítulo Anterior] | <<v5-3-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-004.adoc#v5-4-0[Próximo Capítulo &#62;]