include::./index.adoc[]

[[v5-15-0]]
=== Deuteronômio, 15
// nvi ?, NVI - Nova Versão Internacional

[[v5-15-1]]

^<<v5-15-1,1>>^ No final de cada sete anos as dívidas deverão ser canceladas.

[[v5-15-2]]

^<<v5-15-2,2>>^ Isso deverá ser feito da seguinte forma: Todo credor cancelará o empréstimo que fez ao seu próximo. Nenhum israelita exigirá pagamento de seu próximo ou de seu parente, porque foi proclamado o tempo do Senhor para o cancelamento das dívidas.

[[v5-15-3]]

^<<v5-15-3,3>>^ Vocês poderão exigir pagamento do estrangeiro, mas terão que cancelar qualquer dívida de seus irmãos israelitas.

[[v5-15-4]]

^<<v5-15-4,4>>^ Assim, não deverá haver pobre algum no meio de vocês, pois na terra que o Senhor, o seu Deus, lhes está dando como herança para que dela tomem posse, ele os abençoará ricamente,

[[v5-15-5]]

^<<v5-15-5,5>>^ contanto que obedeçam em tudo ao Senhor, ao seu Deus, e colocarem em prática toda esta lei que hoje lhes estou dando.

[[v5-15-6]]

^<<v5-15-6,6>>^ Pois o Senhor, o seu Deus, os abençoará conforme prometeu, e vocês emprestarão a muitas nações, mas de nenhuma tomarão emprestado. Vocês dominarão muitas nações, mas por nenhuma serão dominados.

[[v5-15-7]]

^<<v5-15-7,7>>^ Se houver algum israelita pobre em qualquer das cidades da terra que o Senhor, o seu Deus, lhe está dando, não endureçam o coração, nem fechem a mão para com o seu irmão pobre.

[[v5-15-8]]

^<<v5-15-8,8>>^ Ao contrário, tenham mão aberta e emprestem-lhe liberalmente o que ele precisar.

[[v5-15-9]]

^<<v5-15-9,9>>^ Cuidado! Que nenhum de vocês alimente este pensamento ímpio: "O sétimo ano, o ano do cancelamento das dívidas, está se aproximando, e não quero ajudar o meu irmão pobre". Ele poderá apelar para o Senhor contra você, e você será culpado pelo pecado.

[[v5-15-10]]

^<<v5-15-10,10>>^ Dê-lhe generosamente, e sem relutância no coração; pois, por isso, o Senhor, o seu Deus, o abençoará em todo o seu trabalho e em tudo o que você fizer.

[[v5-15-11]]

^<<v5-15-11,11>>^ Sempre haverá pobres na terra. Portanto, eu lhe ordeno que abra o coração para o seu irmão israelita, tanto para o pobre como para o necessitado de sua terra.

[[v5-15-12]]

^<<v5-15-12,12>>^ Se seu concidadão hebreu, homem ou mulher, vender-se a você e servi-lo seis anos, no sétimo ano dê-lhe a liberdade.

[[v5-15-13]]

^<<v5-15-13,13>>^ E, quando o fizer, não o mande embora de mãos vazias.

[[v5-15-14]]

^<<v5-15-14,14>>^ Dê-lhe com generosidade dos animais do seu rebanho, do produto da sua eira e do seu lagar. Dê-lhe conforme a bênção que o Senhor, o seu Deus, lhe tem dado.

[[v5-15-15]]

^<<v5-15-15,15>>^ Lembre-se de que você foi escravo no Egito e que o Senhor, o seu Deus, o redimiu. É por isso que hoje lhe dou essa ordem.

[[v5-15-16]]

^<<v5-15-16,16>>^ Mas se o seu escravo lhe disser que não quer deixá-lo, porque ama você e sua família e não tem falta de nada,

[[v5-15-17]]

^<<v5-15-17,17>>^ então apanhe um furador e fure a orelha dele contra a porta, e ele se tornará seu escravo para o resto da vida. Faça o mesmo com a sua escrava.

[[v5-15-18]]

^<<v5-15-18,18>>^ Não se sinta prejudicado ao libertar o seu escravo, pois o serviço que ele prestou a você nesses seis anos custou a metade do serviço de um trabalhador contratado. Além disso, o Senhor, o seu Deus, o abençoará em tudo o que você fizer.

[[v5-15-19]]

^<<v5-15-19,19>>^ Separe para o Senhor, para o seu Deus, todo primeiro macho de todos os seus rebanhos. Não use a primeira cria das suas vacas para trabalhar, nem tosquie a primeira cria das suas ovelhas.

[[v5-15-20]]

^<<v5-15-20,20>>^ Todo ano você e a sua família as comerão na presença do Senhor, do seu Deus, no local que ele escolher.

[[v5-15-21]]

^<<v5-15-21,21>>^ Se o animal tiver defeito, ou for manco ou cego, ou tiver qualquer outro defeito grave, você não poderá sacrificá-lo ao Senhor, ao seu Deus.

[[v5-15-22]]

^<<v5-15-22,22>>^ Coma-o na cidade onde estiver morando. Tanto o cerimonialmente impuro quanto o puro o comerão, como se come a carne da gazela ou do veado.

[[v5-15-23]]

^<<v5-15-23,23>>^ Mas não poderá comer o sangue; derrame-o no chão como se fosse água.

'''

xref:005-deuteronomio/005-deuteronomio-014.adoc#v5-14-0[&#60; Capítulo Anterior] | <<v5-15-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-016.adoc#v5-16-0[Próximo Capítulo &#62;]