include::./index.adoc[]

[[v5-26-0]]
=== Deuteronômio, 26
// nvi ?, NVI - Nova Versão Internacional

[[v5-26-1]]

^<<v5-26-1,1>>^ Quando vocês tiverem entrado na terra que o Senhor, o seu Deus, lhes dá por herança e dela tiverem tomado posse e lá estiverem estabelecidos,

[[v5-26-2]]

^<<v5-26-2,2>>^ apanhem alguns dos primeiros frutos de tudo o que produzirem na terra que o Senhor, o seu Deus, lhes dá e ponha tudo numa cesta. Depois vocês deverão ir ao local que o Senhor, o seu Deus, escolher para habitação do seu Nome

[[v5-26-3]]

^<<v5-26-3,3>>^ e dizer ao sacerdote que estiver exercendo o cargo naquela ocasião: "Declaro hoje ao Senhor, ao seu Deus, que vim para a terra que o Senhor jurou aos nossos antepassados que nos daria".

[[v5-26-4]]

^<<v5-26-4,4>>^ O sacerdote apanhará a cesta das suas mãos e a colocará em frente do altar do Senhor, do seu Deus.

[[v5-26-5]]

^<<v5-26-5,5>>^ Então vocês declararão perante o Senhor, o seu Deus: "O meu pai era um arameu errante. Ele desceu ao Egito com pouca gente e ali viveu e se tornou uma grande nação, poderosa e numerosa.

[[v5-26-6]]

^<<v5-26-6,6>>^ Mas os egípcios nos maltrataram e nos oprimiram, sujeitando-nos a trabalhos forçados.

[[v5-26-7]]

^<<v5-26-7,7>>^ Então clamamos ao Senhor, ao Deus dos nossos antepassados, e o Senhor ouviu a nossa voz e viu o nosso sofrimento, a nossa fadiga e a opressão que sofríamos.

[[v5-26-8]]

^<<v5-26-8,8>>^ Por isso o Senhor nos tirou do Egito com mão poderosa e braço forte, com feitos temíveis e com sinais e maravilhas.

[[v5-26-9]]

^<<v5-26-9,9>>^ Ele nos trouxe a este lugar e nos deu esta terra, terra onde manam leite e mel.

[[v5-26-10]]

^<<v5-26-10,10>>^ E agora trago os primeiros frutos do solo que tu, ó Senhor, me deste". Ponham a cesta perante o Senhor, o seu Deus, e curvem-se perante ele.

[[v5-26-11]]

^<<v5-26-11,11>>^ Vocês e os levitas e os estrangeiros que estiverem no meio de vocês se alegrarão com todas as coisas boas que o Senhor, o seu Deus, dá a vocês e às suas famílias.

[[v5-26-12]]

^<<v5-26-12,12>>^ Quando tiverem separado o dízimo de tudo quanto produziram no terceiro ano, o ano do dízimo, entreguem-no ao levita, ao estrangeiro, ao órfão e à viúva, para que possam comer até saciar-se nas cidades de vocês.

[[v5-26-13]]

^<<v5-26-13,13>>^ Depois digam ao Senhor, ao seu Deus: "Retirei da minha casa a porção sagrada e dei-a ao levita, ao estrangeiro, ao órfão e à viúva, de acordo com tudo o que ordenaste. Não me afastei dos teus mandamentos nem esqueci nenhum deles.

[[v5-26-14]]

^<<v5-26-14,14>>^ Não comi nada da porção sagrada enquanto estive de luto, nada retirei dela enquanto estive impuro, e dela não ofereci nada aos mortos. Obedeci ao Senhor, ao meu Deus; fiz tudo o que me ordenaste.

[[v5-26-15]]

^<<v5-26-15,15>>^ Olha dos céus, da tua santa habitação, e abençoa Israel, o teu povo, e a terra que nos deste, conforme prometeste sob juramento aos nossos antepassados, terra onde manam leite e mel".

[[v5-26-16]]

^<<v5-26-16,16>>^ O Senhor, o seu Deus, lhes ordena hoje que sigam estes decretos e ordenanças; obedeçam-lhes atentamente, de todo o seu coração e de toda a sua alma.

[[v5-26-17]]

^<<v5-26-17,17>>^ Hoje vocês declararam que o Senhor é o seu Deus e que vocês andarão nos seus caminhos, que guardarão os seus decretos, os seus mandamentos e as suas ordenanças, e que vocês lhe obedecerão.

[[v5-26-18]]

^<<v5-26-18,18>>^ E hoje o Senhor declarou que vocês são o seu povo, o seu tesouro pessoal, conforme ele prometeu, e que vocês terão que guardar todos os seus mandamentos.

[[v5-26-19]]

^<<v5-26-19,19>>^ Ele declarou que lhes dará uma posição de glória, fama e honra muito acima de todas as nações que ele fez, e que vocês serão um povo santo para o Senhor, para o seu Deus, conforme ele prometeu.

'''

xref:005-deuteronomio/005-deuteronomio-025.adoc#v5-25-0[&#60; Capítulo Anterior] | <<v5-26-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-027.adoc#v5-27-0[Próximo Capítulo &#62;]