include::./index.adoc[]

[[v5-24-0]]
=== Deuteronômio, 24
// nvi ?, NVI - Nova Versão Internacional

[[v5-24-1]]

^<<v5-24-1,1>>^ Se um homem casar-se com uma mulher e depois não a quiser mais por encontrar nela algo que ele reprova, dará certidão de divórcio à mulher e a mandará embora.

[[v5-24-2]]

^<<v5-24-2,2>>^ Se, depois de sair da casa, ela se tornar mulher de outro homem,

[[v5-24-3]]

^<<v5-24-3,3>>^ e o seu segundo marido não gostar mais dela, lhe dará certidão de divórcio, e mandará embora a mulher. Ou também, se ele morrer,

[[v5-24-4]]

^<<v5-24-4,4>>^ o primeiro marido, que se divorciou dela, não poderá casar-se com ela de novo, visto que ela foi contaminada. Seria detestável para o Senhor. Não tragam pecado sobre a terra que o Senhor, o seu Deus, lhes dá por herança.

[[v5-24-5]]

^<<v5-24-5,5>>^ Se um homem tiver se casado recentemente, não será enviado à guerra, nem assumirá nenhum compromisso público. Durante um ano estará livre para ficar em casa e fazer feliz à mulher com quem se casou.

[[v5-24-6]]

^<<v5-24-6,6>>^ Não tomem as duas pedras de moinho, nem mesmo apenas a pedra de cima, como garantia de uma dívida, pois isso seria tomar como garantia o meio de subsistência do devedor.

[[v5-24-7]]

^<<v5-24-7,7>>^ Se um homem for pego seqüestrando um dos seus irmãos israelitas, tratando-o como escravo ou vendendo-o, o seqüestrador terá que morrer. Eliminem o mal do meio de vocês.

[[v5-24-8]]

^<<v5-24-8,8>>^ Nos casos de doenças de lepra, tenham todo o cuidado de seguir exatamente as instruções dos sacerdotes levitas. Sigam cuidadosamente o que eu ordenei a eles.

[[v5-24-9]]

^<<v5-24-9,9>>^ Lembrem-se do que o Senhor, o seu Deus, fez com Miriã no caminho, depois que vocês saíram do Egito.

[[v5-24-10]]

^<<v5-24-10,10>>^ Quando um de vocês fizer um empréstimo de qualquer tipo ao seu próximo, não entre na casa dele para apanhar o que ele lhe oferecer como penhor.

[[v5-24-11]]

^<<v5-24-11,11>>^ Fique do lado de fora e deixe que o homem, a quem você está fazendo o empréstimo, traga a você o penhor.

[[v5-24-12]]

^<<v5-24-12,12>>^ Se o homem for pobre, não vá dormir tendo com você o penhor.

[[v5-24-13]]

^<<v5-24-13,13>>^ Devolva-lhe o manto ao pôr-do-sol, para que ele possa usá-lo para dormir, e lhe seja grato. Isso será considerado um ato de justiça pelo Senhor, o seu Deus.

[[v5-24-14]]

^<<v5-24-14,14>>^ Não se aproveitem do pobre e necessitado, seja ele um irmão israelita ou um estrangeiro que viva numa das suas cidades.

[[v5-24-15]]

^<<v5-24-15,15>>^ Paguem-lhe o seu salário diariamente, antes do pôr-do-sol, pois ele é necessitado e depende disso. Se não, ele poderá clamar ao Senhor contra você, e você será culpado de pecado.

[[v5-24-16]]

^<<v5-24-16,16>>^ Os pais não serão mortos em lugar dos filhos, nem os filhos em lugar dos pais; cada um morrerá pelo seu próprio pecado.

[[v5-24-17]]

^<<v5-24-17,17>>^ Não neguem justiça ao estrangeiro e ao órfão, nem tomem como penhor o manto de uma viúva.

[[v5-24-18]]

^<<v5-24-18,18>>^ Lembrem-se de que vocês foram escravos no Egito e de que o Senhor, o seu Deus, os libertou; por isso lhes ordeno que façam tudo isso.

[[v5-24-19]]

^<<v5-24-19,19>>^ Quando vocês estiverem fazendo a colheita de sua lavoura e deixarem um feixe de trigo para trás, não voltem para apanhá-lo. Deixem-no para o estrangeiro, para o órfão e para a viúva, para que o Senhor, o seu Deus, os abençoe em todo o trabalho das suas mãos.

[[v5-24-20]]

^<<v5-24-20,20>>^ Quando sacudirem as azeitonas das suas oliveiras, não voltem para colher o que ficar nos ramos. Deixem o que sobrar para o estrangeiro, para o órfão e para a viúva.

[[v5-24-21]]

^<<v5-24-21,21>>^ E quando colherem as uvas da sua vinha, não passem de novo por ela. Deixem o que sobrar para o estrangeiro, para o órfão e para a viúva.

[[v5-24-22]]

^<<v5-24-22,22>>^ Lembrem-se de que vocês foram escravos no Egito; por isso lhes ordeno que façam tudo isso.

'''

xref:005-deuteronomio/005-deuteronomio-023.adoc#v5-23-0[&#60; Capítulo Anterior] | <<v5-24-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-025.adoc#v5-25-0[Próximo Capítulo &#62;]