include::./index.adoc[]

[[v5-14-0]]
=== Deuteronômio, 14
// nvi ?, NVI - Nova Versão Internacional

[[v5-14-1]]

^<<v5-14-1,1>>^ Vocês são os filhos do Senhor, do seu Deus. Não façam cortes no corpo nem rapem a frente da cabeça por causa dos mortos,

[[v5-14-2]]

^<<v5-14-2,2>>^ pois vocês são povo consagrado ao Senhor, ao seu Deus. Dentre todos os povos da face da terra, o Senhor os escolheu para serem o seu tesouro pessoal.

[[v5-14-3]]

^<<v5-14-3,3>>^ Não comam nada que seja proibido.

[[v5-14-4]]

^<<v5-14-4,4>>^ São estes os animais que vocês podem comer: o boi, a ovelha, o bode,

[[v5-14-5]]

^<<v5-14-5,5>>^ o veado, a gazela, a corça, o bode montês, o antílope, o bode selvagem e a ovelha montês.

[[v5-14-6]]

^<<v5-14-6,6>>^ Vocês poderão comer qualquer animal que tenha o casco fendido e dividido em duas unhas e que rumine.

[[v5-14-7]]

^<<v5-14-7,7>>^ Contudo, dos que ruminam ou têm o casco fendido, vocês não poderão comer o camelo, o coelho e o rato silvestre. Embora ruminem, não têm casco fendido; são impuros para vocês.

[[v5-14-8]]

^<<v5-14-8,8>>^ O porco também é impuro; embora tenha casco fendido, não rumina. Vocês não poderão comer a carne deles nem tocar em seus cadáveres.

[[v5-14-9]]

^<<v5-14-9,9>>^ De todas as criaturas que vivem nas águas vocês poderão comer as que possuem barbatanas e escamas.

[[v5-14-10]]

^<<v5-14-10,10>>^ Mas não poderão comer nenhuma criatura que não tiver barbatanas nem escamas; é impura para vocês.

[[v5-14-11]]

^<<v5-14-11,11>>^ Vocês poderão comer qualquer ave pura.

[[v5-14-12]]

^<<v5-14-12,12>>^ Mas estas vocês não poderão comer: a águia, o urubu, a águia-marinha,

[[v5-14-13]]

^<<v5-14-13,13>>^ o milhafre, qualquer espécie de falcão,

[[v5-14-14]]

^<<v5-14-14,14>>^ qualquer espécie de corvo,

[[v5-14-15]]

^<<v5-14-15,15>>^ a coruja-de-chifre, a coruja-de-orelha-pequena, a coruja-orelhuda, qualquer espécie de gavião,

[[v5-14-16]]

^<<v5-14-16,16>>^ o mocho, o corujão, a coruja-branca,

[[v5-14-17]]

^<<v5-14-17,17>>^ a coruja-do-deserto, o abutre, a coruja-pescadora,

[[v5-14-18]]

^<<v5-14-18,18>>^ a cegonha, qualquer tipo de garça, a poupa e o morcego.

[[v5-14-19]]

^<<v5-14-19,19>>^ Todas as pequenas criaturas que enxameiam e têm asas são impuras para vocês; não as comam.

[[v5-14-20]]

^<<v5-14-20,20>>^ Mas qualquer criatura que têm asas, sendo pura, vocês poderão comer.

[[v5-14-21]]

^<<v5-14-21,21>>^ Não comam nada que encontrarem morto. Vocês poderão dá-lo a um estrangeiro residente de qualquer cidade de vocês, e ele poderá comê-lo, ou vocês poderão vendê-lo a outros estrangeiros. Mas vocês são povo consagrado ao Senhor, ao seu Deus. Não cozinhem o cabrito no leite da própria mãe.

[[v5-14-22]]

^<<v5-14-22,22>>^ Separem o dízimo de tudo o que a terra produzir anualmente.

[[v5-14-23]]

^<<v5-14-23,23>>^ Comam o dízimo do cereal, do vinho novo e do azeite, e a primeira cria de todos os seus rebanhos na presença do Senhor, o seu Deus, no local que ele escolher como habitação do seu Nome, para que aprendam a temer sempre o Senhor, o seu Deus.

[[v5-14-24]]

^<<v5-14-24,24>>^ Mas, se o local for longe demais e vocês tiverem sido abençoados pelo Senhor, pelo seu Deus, e não puderem carregar o dízimo, pois o local escolhido pelo Senhor para ali pôr o seu Nome é longe demais,

[[v5-14-25]]

^<<v5-14-25,25>>^ troquem o dízimo por prata, e levem a prata ao local que o Senhor, o seu Deus, tiver escolhido.

[[v5-14-26]]

^<<v5-14-26,26>>^ Com prata comprem o que quiserem: bois, ovelhas, vinho ou outra bebida fermentada, ou qualquer outra coisa que desejarem. Então juntamente com suas famílias comam e alegrem-se ali, na presença do Senhor, do seu Deus.

[[v5-14-27]]

^<<v5-14-27,27>>^ E nunca se esqueçam dos levitas que vivem em suas cidades, pois eles não possuem propriedade nem herança próprias.

[[v5-14-28]]

^<<v5-14-28,28>>^ Ao final de cada três anos, tragam todos os dízimos da colheita do terceiro ano e armazene-os em sua própria cidade,

[[v5-14-29]]

^<<v5-14-29,29>>^ para que os levitas, que não possuem propriedade nem herança, e os estrangeiros, os órfãos e as viúvas que vivem na sua cidade venham comer e saciar-se, e para que o Senhor, o seu Deus, o abençoe em todo o trabalho das suas mãos.

'''

xref:005-deuteronomio/005-deuteronomio-013.adoc#v5-13-0[&#60; Capítulo Anterior] | <<v5-14-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-015.adoc#v5-15-0[Próximo Capítulo &#62;]