include::./index.adoc[]

[[v5-30-0]]
=== Deuteronômio, 30
// nvi ?, NVI - Nova Versão Internacional

[[v5-30-1]]

^<<v5-30-1,1>>^ Quando todas essas bênçãos e maldições que coloquei diante de vocês lhes sobrevierem, e elas os atingirem onde quer que o Senhor, o seu Deus, os dispersar entre as nações,

[[v5-30-2]]

^<<v5-30-2,2>>^ e quando vocês e os seus filhos voltarem para o Senhor, para o seu Deus, e lhe obedecerem de todo o coração e de toda a alma, de acordo com tudo o que hoje lhes ordeno,

[[v5-30-3]]

^<<v5-30-3,3>>^ então o Senhor, o seu Deus, lhes trará restauração e terá compaixão de vocês e os reunirá novamente de todas as nações por onde os tiver espalhado.

[[v5-30-4]]

^<<v5-30-4,4>>^ Mesmo que tenham sido levados para a terra mais distante debaixo do céu, de lá o Senhor, o seu Deus, os reunirá e os trará de volta.

[[v5-30-5]]

^<<v5-30-5,5>>^ Ele os trará para a terra dos seus antepassados, e vocês tomarão posse dela. Ele fará com que vocês sejam mais prósperos e mais numerosos do que os seus antepassados.

[[v5-30-6]]

^<<v5-30-6,6>>^ O Senhor, o seu Deus, dará um coração fiel a vocês e aos seus descendentes, para que o amem de todo o coração e de toda a alma e vivam.

[[v5-30-7]]

^<<v5-30-7,7>>^ O Senhor, o seu Deus, enviará então todas essas maldições sobre os inimigos que os odeiam e os perseguem.

[[v5-30-8]]

^<<v5-30-8,8>>^ Vocês obedecerão de novo ao Senhor e seguirão todos os seus mandamentos que lhes dou hoje.

[[v5-30-9]]

^<<v5-30-9,9>>^ Então o Senhor, o seu Deus, abençoará o que as suas mãos fizerem, os filhos do seu ventre, a cria dos seus animais e as colheitas da sua terra. O Senhor se alegrará novamente em vocês e os tornará prósperos, como se alegrou em seus antepassados,

[[v5-30-10]]

^<<v5-30-10,10>>^ se vocês obedecerem ao Senhor, ao seu Deus, e guardarem os seus mandamentos e decretos que estão escritos neste Livro da Lei, e se se voltarem para o Senhor, para o seu Deus, de todo o coração e de toda a alma. Vida ou Morte

[[v5-30-11]]

^<<v5-30-11,11>>^ O que hoje lhes estou ordenando não é difícil fazer, nem está além do seu alcance.

[[v5-30-12]]

^<<v5-30-12,12>>^ Não está lá em cima no céu, de modo que vocês tenham que perguntar: "Quem subirá ao céu para consegui-lo e vir proclamá-lo a nós a fim de que lhe obedeçamos? "

[[v5-30-13]]

^<<v5-30-13,13>>^ Nem está além do mar, de modo que vocês tenham que perguntar: "Quem atravessará o mar para consegui-lo e, voltando, proclamá-lo a nós a fim de que lhe obedeçamos? "

[[v5-30-14]]

^<<v5-30-14,14>>^ Nada disso. A palavra está bem próxima de vocês; está em sua boca e em seu coração; por isso vocês poderão obedecer-lhe.

[[v5-30-15]]

^<<v5-30-15,15>>^ Vejam que hoje ponho diante de vocês vida e prosperidade, ou morte e destruição.

[[v5-30-16]]

^<<v5-30-16,16>>^ Pois hoje lhes ordeno que amem o Senhor, o seu Deus, andem nos seus caminhos e guardem os seus mandamentos, decretos e ordenanças; então vocês terão vida e aumentarão em número, e o Senhor, o seu Deus, os abençoará na terra em que vocês estão entrando para dela tomar posse.

[[v5-30-17]]

^<<v5-30-17,17>>^ Se, todavia, o seu coração se desviar e vocês não forem obedientes, e se deixarem levar, prostrando-se diante de outros deuses para adorá-los,

[[v5-30-18]]

^<<v5-30-18,18>>^ eu hoje lhes declaro que sem dúvida vocês serão destruídos. Vocês não viverão muito tempo na terra em que vão entrar e da qual vão tomar posse, depois de atravessarem o Jordão.

[[v5-30-19]]

^<<v5-30-19,19>>^ Hoje invoco os céus e a terra como testemunhas contra vocês, de que coloquei diante de vocês a vida e a morte, a bênção e a maldição. Agora escolham a vida, para que vocês e os seus filhos vivam,

[[v5-30-20]]

^<<v5-30-20,20>>^ e para que vocês amem o Senhor, o seu Deus, ouçam a sua voz e se apeguem firmemente a ele. Pois o Senhor é a sua vida, e ele lhes dará muitos anos na terra que jurou dar aos seus antepassados, Abraão, Isaque e Jacó.

'''

xref:005-deuteronomio/005-deuteronomio-029.adoc#v5-29-0[&#60; Capítulo Anterior] | <<v5-30-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-031.adoc#v5-31-0[Próximo Capítulo &#62;]