include::./index.adoc[]

[[v5-1-0]]
=== Deuteronômio, 1
// nvi ?, NVI - Nova Versão Internacional

[[v5-1-1]]

^<<v5-1-1,1>>^ Estas são as palavras ditas por Moisés a todo o Israel no deserto, a leste do Jordão, na Arabá, defronte de Sufe, entre Parã e Tofel, Labã, Hazerote e Di-Zaabe.

[[v5-1-2]]

^<<v5-1-2,2>>^ Em onze dias se vai de Horebe a Cades-Barnéia pelo caminho dos montes de Seir.

[[v5-1-3]]

^<<v5-1-3,3>>^ No quadragésimo ano, no primeiro dia do décimo primeiro mês, Moisés proclamou aos israelitas todas as ordens do Senhor acerca deles.

[[v5-1-4]]

^<<v5-1-4,4>>^ Isso foi depois que ele derrotou Seom, rei dos amorreus, que habitava em Hesbom, e em Edrei derrotou Ogue, rei de Basã, que habitava em Asterote.

[[v5-1-5]]

^<<v5-1-5,5>>^ A leste do Jordão, na terra de Moabe, Moisés tomou sobre si a responsabilidade de expor esta lei:

[[v5-1-6]]

^<<v5-1-6,6>>^ O Senhor, o nosso Deus, disse-nos em Horebe: "Vocês já ficaram bastante tempo nesta montanha.

[[v5-1-7]]

^<<v5-1-7,7>>^ Levantem acampamento e avancem para a serra dos amorreus; vão a todos os povos vizinhos na Arabá, nas montanhas, na Sefelá, no Neguebe e ao longo do litoral, à terra dos cananeus e ao Líbano, até o grande rio, o Eufrates.

[[v5-1-8]]

^<<v5-1-8,8>>^ "Ponho esta terra diante de vocês. Entrem e tomem posse da terra que o Senhor prometeu sob juramento dar aos seus antepassados, Abraão, Isaque e Jacó, e aos seus descendentes".

[[v5-1-9]]

^<<v5-1-9,9>>^ Naquela ocasião eu lhes disse: "Não posso levá-los sozinho.

[[v5-1-10]]

^<<v5-1-10,10>>^ O Senhor, o seu Deus, os fez multiplicar de tal modo que hoje vocês são tão numerosos quanto as estrelas do céu.

[[v5-1-11]]

^<<v5-1-11,11>>^ Que o Senhor, o Deus dos seus antepassados, os multiplique mil vezes mais e os abençoe, conforme lhes prometeu!

[[v5-1-12]]

^<<v5-1-12,12>>^ Mas como poderei levar sozinho os seus problemas, as suas cargas e as suas disputas?

[[v5-1-13]]

^<<v5-1-13,13>>^ Escolham homens sábios, criteriosos e experientes de cada uma de suas tribos, e eu os colocarei como chefes de vocês".

[[v5-1-14]]

^<<v5-1-14,14>>^ Vocês me disseram que essa era uma boa proposta.

[[v5-1-15]]

^<<v5-1-15,15>>^ Então convoquei os chefes das tribos, homens sábios e experientes, e os designei como chefes de mil, de cem, de cinqüenta e de dez, além de oficiais para cada tribo.

[[v5-1-16]]

^<<v5-1-16,16>>^ Naquela ocasião ordenei aos juízes de vocês: "Atendam as questões de seus irmãos e julguem com justiça, não só as questões entre os seus compatriotas como também entre um israelita e um estrangeiro.

[[v5-1-17]]

^<<v5-1-17,17>>^ Não sejam parciais no julgamento! Atendam tanto o pequeno como o grande. Não se deixem intimidar por ninguém, pois o veredicto pertence a Deus. Tragam-me os casos mais difíceis e eu os ouvirei.

[[v5-1-18]]

^<<v5-1-18,18>>^ Naquela ocasião eu lhes ordenei tudo o que deveriam fazer".

[[v5-1-19]]

^<<v5-1-19,19>>^ Depois, conforme o Senhor, o nosso Deus, nos tinha ordenado, partimos de Horebe e fomos para a serra dos amorreus, passando por todo aquele imenso e terrível deserto que vocês viram, e assim chegamos a Cades-Barnéia.

[[v5-1-20]]

^<<v5-1-20,20>>^ Então eu lhes disse: "Vocês chegaram à serra dos amorreus, a qual o Senhor, o nosso Deus, nos dá.

[[v5-1-21]]

^<<v5-1-21,21>>^ Vejam, o Senhor, o seu Deus, põe diante de vocês esta terra. Entrem na terra e tomem posse dela, conforme o Senhor, o Deus dos seus antepassados, lhes disse. Não tenham medo nem se desanimem".

[[v5-1-22]]

^<<v5-1-22,22>>^ Vocês todos vieram dizer-me: "Mandemos alguns homens à nossa frente em missão de reconhecimento da região, para que nos indiquem por qual caminho subiremos e a quais cidades iremos".

[[v5-1-23]]

^<<v5-1-23,23>>^ A sugestão pareceu-me boa; por isso escolhi doze de vocês, um homem de cada tribo.

[[v5-1-24]]

^<<v5-1-24,24>>^ Eles subiram a região montanhosa, chegaram ao vale de Escol e o exploraram.

[[v5-1-25]]

^<<v5-1-25,25>>^ Trouxeram alguns frutos da região, com o seguinte relato: "Essa terra que o Senhor, o nosso Deus, nos dá é boa".

[[v5-1-26]]

^<<v5-1-26,26>>^ Vocês, contudo, não quiseram ir, e se rebelaram contra a ordem do Senhor, o seu Deus.

[[v5-1-27]]

^<<v5-1-27,27>>^ Queixaram-se em suas tendas, dizendo: "O Senhor nos odeia; por isso nos trouxe do Egito para nos entregar nas mãos dos amorreus e destruir-nos.

[[v5-1-28]]

^<<v5-1-28,28>>^ Para onde iremos? Nossos compatriotas nos desanimaram quando disseram: O povo é mais forte e mais alto do que nós; as cidades são grandes, com muros que vão até o céu. Vimos ali os enaquins".

[[v5-1-29]]

^<<v5-1-29,29>>^ Então eu lhes disse: Não fiquem apavorados; não tenham medo deles.

[[v5-1-30]]

^<<v5-1-30,30>>^ O Senhor, o seu Deus, que está indo à frente de vocês, lutará por vocês, como fez no Egito, diante de seus próprios olhos.

[[v5-1-31]]

^<<v5-1-31,31>>^ Também no deserto vocês viram como o Senhor, o seu Deus, os carregou, como um pai carrega seu filho, por todo o caminho que percorreram até chegarem a este lugar.

[[v5-1-32]]

^<<v5-1-32,32>>^ Apesar disso, vocês não confiaram no Senhor, o seu Deus,

[[v5-1-33]]

^<<v5-1-33,33>>^ que foi à frente de vocês, numa coluna de fogo de noite e numa nuvem de dia, para procurar lugares para vocês acamparem e para mostrar-lhes o caminho que vocês deviam seguir.

[[v5-1-34]]

^<<v5-1-34,34>>^ Quando o Senhor ouviu o que vocês diziam, irou-se e jurou:

[[v5-1-35]]

^<<v5-1-35,35>>^ "Ninguém desta geração má verá a boa terra que jurei dar aos seus antepassados,

[[v5-1-36]]

^<<v5-1-36,36>>^ exceto Calebe, filho de Jefoné. Ele a verá, e eu darei a ele e a seus descendentes a terra em que pisou, pois seguiu o Senhor de todo o coração".

[[v5-1-37]]

^<<v5-1-37,37>>^ Por causa de vocês o Senhor irou-se contra mim e me disse: "Você também não entrará na terra.

[[v5-1-38]]

^<<v5-1-38,38>>^ Mas o seu auxiliar, Josué, filho de Num, entrará. Encoraje-o, pois ele fará com que Israel tome posse dela.

[[v5-1-39]]

^<<v5-1-39,39>>^ Mas as crianças que vocês disseram que seriam levadas como despojo, os seus filhos que ainda não distinguem entre o bem e o mal, eles entrarão na terra. Eu a darei a eles, e eles tomarão posse dela.

[[v5-1-40]]

^<<v5-1-40,40>>^ Mas quanto a vocês, dêem meia-volta e partam para o deserto pelo caminho do mar Vermelho".

[[v5-1-41]]

^<<v5-1-41,41>>^ Então vocês responderam: "Pecamos contra o Senhor. Nós subiremos e lutaremos, conforme tudo o que o Senhor, o nosso Deus, nos ordenou". Cada um de vocês preparou-se com as suas armas de guerra, achando que seria fácil subir a região montanhosa.

[[v5-1-42]]

^<<v5-1-42,42>>^ Mas o Senhor me disse: "Diga-lhes que não subam nem lutem, porque não estarei com vocês. Vocês serão derrotados pelos seus inimigos".

[[v5-1-43]]

^<<v5-1-43,43>>^ Eu lhes disse isso, mas vocês não me deram ouvidos, rebelaram-se contra o Senhor e, com presunção, subiram a região montanhosa.

[[v5-1-44]]

^<<v5-1-44,44>>^ Os amorreus que lá viviam os atacaram, os perseguiram como um enxame de abelhas e os arrasaram desde Seir até Hormá.

[[v5-1-45]]

^<<v5-1-45,45>>^ Vocês voltaram e choraram perante o Senhor, mas ele não ouviu o seu clamor nem lhes deu atenção.

[[v5-1-46]]

^<<v5-1-46,46>>^ Então vocês ficaram em Cades, onde permaneceram muito tempo.

'''

xref:004-numeros/004-numeros-036.adoc#v4-36-0[&#60; Capítulo Anterior] | <<v5-1-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-002.adoc#v5-2-0[Próximo Capítulo &#62;]