include::./index.adoc[]

[[v34-2-0]]
=== Naum, 2
// nvi ?, NVI - Nova Versão Internacional

[[v34-2-1]]

^<<v34-2-1,1>>^ O destruidor avança contra você, Nínive! Guarde a fortaleza! Vigie a estrada! Prepare a resistência! Reúna todas as suas forças!

[[v34-2-2]]

^<<v34-2-2,2>>^ O SENHOR restaurará o esplendor de Jacó; restaurará o esplendor de Israel, embora os saqueadores tenham devastado e destruído as suas videiras.

[[v34-2-3]]

^<<v34-2-3,3>>^ Os escudos e os uniformes dos soldados inimigos são vermelhos. Os seus carros de guerra reluzem quando se alinham para a batalha; agitam-se as lanças de pinho.

[[v34-2-4]]

^<<v34-2-4,4>>^ Os carros de guerra percorrem loucamente as ruas e se cruzam velozmente pelos quarteirões. Parecem tochas de fogo e arremessam-se como relâmpagos.

[[v34-2-5]]

^<<v34-2-5,5>>^ Convocam-se as suas tropas de elite, mas elas vêm tropeçando; correm para a muralha da cidade para formar a linha de proteção.

[[v34-2-6]]

^<<v34-2-6,6>>^ As comportas dos canais são abertas, e o palácio desaba.

[[v34-2-7]]

^<<v34-2-7,7>>^ Está decretado: a cidade irá para o exílio, será deportada. As jovens tomadas como escravas batem no peito; seu gemer é como o arrulhar das pombas.

[[v34-2-8]]

^<<v34-2-8,8>>^ Nínive é como um açude antigo cujas águas estão vazando. "Parem, parem", eles gritam, mas ninguém sequer olha para trás.

[[v34-2-9]]

^<<v34-2-9,9>>^ Saqueiem a prata! Saqueiem o ouro! Sua riqueza não tem fim; está repleta de objetos de valor!

[[v34-2-10]]

^<<v34-2-10,10>>^ Ah! Devastação! Destruição! Desolação! Os corações se derretem, os joelhos vacilam, todos os corpos tremem e o rosto de todos empalidece!

[[v34-2-11]]

^<<v34-2-11,11>>^ Onde está agora a toca dos leões? Onde o lugar em que alimentavam seus filhotes, para onde iam o leão, a leoa e os leõezinhos, sem nada temer?

[[v34-2-12]]

^<<v34-2-12,12>>^ Onde está o leão que caçava o bastante para os seus filhotes e estrangulava animais para as suas leoas, e que enchia as suas covas de presas e suas tocas de vítimas?

[[v34-2-13]]

^<<v34-2-13,13>>^ "Estou contra você", declara o SENHOR dos Exércitos, "queimarei no fogo os seus carros de guerra, e a espada matará os seus leões. Eliminarei da terra a sua caça, e a voz dos seus mensageiros jamais será ouvida".

'''

xref:034-naum/034-naum-001.adoc#v34-1-0[&#60; Capítulo Anterior] | <<v34-2-0,Topo>> | xref:034-naum/034-naum-003.adoc#v34-3-0[Próximo Capítulo &#62;]