include::./index.adoc[]

[[v34-3-0]]
=== Naum, 3
// nvi ?, NVI - Nova Versão Internacional

[[v34-3-1]]

^<<v34-3-1,1>>^ Ai da cidade sanguinária, repleta de fraudes e cheia de roubos, sempre fazendo as suas vítimas!

[[v34-3-2]]

^<<v34-3-2,2>>^ Ah, o estalo dos chicotes, o barulho das rodas, o galope dos cavalos e o sacudir dos carros de guerra!

[[v34-3-3]]

^<<v34-3-3,3>>^ Cavaleiros atacando, espadas reluzentes e lanças cintilantes! Muitos mortos, montanhas de cadáveres, corpos sem conta, gente tropeçando por cima deles!

[[v34-3-4]]

^<<v34-3-4,4>>^ Tudo por causa do desejo desenfreado de uma prostituta sedutora, mestra de feitiçarias, que escravizou nações com a sua prostituição e povos, com a sua feitiçaria.

[[v34-3-5]]

^<<v34-3-5,5>>^ "Eu estou contra você", declara o SENHOR dos Exércitos, "vou levantar o seu vestido até a altura do seu rosto. Mostrarei às nações a sua nudez e aos reinos, as suas vergonhas.

[[v34-3-6]]

^<<v34-3-6,6>>^ Eu jogarei imundície sobre você, e a tratarei com desprezo; farei de você um exemplo.

[[v34-3-7]]

^<<v34-3-7,7>>^ Todos os que a virem fugirão dizendo: ‘Nínive está arrasada! Quem a lamentará? ’ Onde encontrarei quem a console? "

[[v34-3-8]]

^<<v34-3-8,8>>^ Acaso és melhor do que Tebas, situada junto ao Nilo, rodeada de águas? O rio era a sua defesa; as águas, o seu muro.

[[v34-3-9]]

^<<v34-3-9,9>>^ A Etiópia e o Egito eram a sua força ilimitada; Fute e a Líbia estavam entre os seus aliados.

[[v34-3-10]]

^<<v34-3-10,10>>^ Apesar disso, ela foi deportada, levada para o exílio. Em cada esquina as suas crianças foram massacradas. Tiraram sortes para decidir o destino dos seus nobres; todos os poderosos foram acorrentados.

[[v34-3-11]]

^<<v34-3-11,11>>^ Você também ficará embriagada; irá esconder-se, tentando proteger-se do inimigo.

[[v34-3-12]]

^<<v34-3-12,12>>^ Todas as suas fortalezas são como figueiras carregadas de figos maduros; basta sacudi-las, e os figos caem em bocas vorazes.

[[v34-3-13]]

^<<v34-3-13,13>>^ Olhe bem para as suas tropas: não passam de mulheres! As suas portas estão escancaradas para os seus inimigos; o fogo devorou as suas trancas.

[[v34-3-14]]

^<<v34-3-14,14>>^ Reserve água para o tempo do cerco! Reforce as suas fortalezas! Entre no barro, pise a argamassa, prepare a forma para os tijolos!

[[v34-3-15]]

^<<v34-3-15,15>>^ Mesmo assim o fogo consumirá você; a espada a eliminará, e, como gafanhotos devastadores, a devorará! Multiplique-se como gafanhotos devastadores, multiplique-se como gafanhotos peregrinos!

[[v34-3-16]]

^<<v34-3-16,16>>^ Você multiplicou os seus comerciantes, tornando-os mais numerosos do que as estrelas do céu; mas como gafanhotos devastadores, devoram o país e depois voam para longe.

[[v34-3-17]]

^<<v34-3-17,17>>^ Os seus guardas são como gafanhotos peregrinos, os seus oficiais, como enxames de gafanhotos que se ajuntam sobre os muros em dias frios; mas quando o sol aparece, eles voam, ninguém sabe para onde.

[[v34-3-18]]

^<<v34-3-18,18>>^ Ó rei da Assíria, os seus pastores dormem; os seus nobres adormecem. O seu povo está espalhado pelos montes e não há ninguém para reuni-lo.

[[v34-3-19]]

^<<v34-3-19,19>>^ Não há cura para a sua chaga; a sua ferida é mortal. Quem ouve notícias a seu respeito bate palmas pela sua queda, pois, quem não sofreu a sua crueldade sem limites?

'''

xref:034-naum/034-naum-002.adoc#v34-2-0[&#60; Capítulo Anterior] | <<v34-3-0,Topo>> | xref:035-habacuque/035-habacuque-001.adoc#v35-1-0[Próximo Capítulo &#62;]