include::./index.adoc[]

[[v48-5-0]]
=== Gálatas, 5
// nvi ?, NVI - Nova Versão Internacional

[[v48-5-1]]

^<<v48-5-1,1>>^ Foi para a liberdade que Cristo nos libertou. Portanto, permaneçam firmes e não se deixem submeter novamente a um jugo de escravidão.

[[v48-5-2]]

^<<v48-5-2,2>>^ Ouçam bem o que eu, Paulo, lhes digo: Caso se deixem circuncidar, Cristo de nada lhes servirá.

[[v48-5-3]]

^<<v48-5-3,3>>^ De novo declaro a todo homem que se deixa circuncidar que está obrigado a cumprir toda a lei.

[[v48-5-4]]

^<<v48-5-4,4>>^ Vocês, que procuram ser justificados pela lei, separaram-se de Cristo; caíram da graça.

[[v48-5-5]]

^<<v48-5-5,5>>^ Pois é mediante o Espírito que nós aguardamos pela fé a justiça que é a nossa esperança.

[[v48-5-6]]

^<<v48-5-6,6>>^ Porque em Cristo Jesus nem circuncisão nem incircuncisão têm efeito algum, mas sim a fé que atua pelo amor.

[[v48-5-7]]

^<<v48-5-7,7>>^ Vocês corriam bem. Quem os impediu de continuar obedecendo à verdade?

[[v48-5-8]]

^<<v48-5-8,8>>^ Tal persuasão não provém daquele que os chama.

[[v48-5-9]]

^<<v48-5-9,9>>^ "Um pouco de fermento leveda toda a massa".

[[v48-5-10]]

^<<v48-5-10,10>>^ Estou convencido no Senhor de que vocês não pensarão de nenhum outro modo. Aquele que os perturba, seja quem for, sofrerá a condenação.

[[v48-5-11]]

^<<v48-5-11,11>>^ Irmãos, se ainda estou pregando a circuncisão, por que continuo sendo perseguido? Nesse caso, o escândalo da cruz foi removido.

[[v48-5-12]]

^<<v48-5-12,12>>^ Quanto a esses que os perturbam, quem dera que se castrassem!

[[v48-5-13]]

^<<v48-5-13,13>>^ Irmãos, vocês foram chamados para a liberdade. Mas não usem a liberdade para dar ocasião à vontade da carne; pelo contrário, sirvam uns aos outros mediante o amor.

[[v48-5-14]]

^<<v48-5-14,14>>^ Toda a lei se resume num só mandamento: "Ame o seu próximo como a si mesmo".

[[v48-5-15]]

^<<v48-5-15,15>>^ Mas se vocês se mordem e se devoram uns aos outros, cuidado para não se destruírem mutuamente.

[[v48-5-16]]

^<<v48-5-16,16>>^ Por isso digo: vivam pelo Espírito, e de modo nenhum satisfarão os desejos da carne.

[[v48-5-17]]

^<<v48-5-17,17>>^ Pois a carne deseja o que é contrário ao Espírito; e o Espírito, o que é contrário à carne. Eles estão em conflito um com o outro, de modo que vocês não fazem o que desejam.

[[v48-5-18]]

^<<v48-5-18,18>>^ Mas, se vocês são guiados pelo Espírito, não estão debaixo da lei.

[[v48-5-19]]

^<<v48-5-19,19>>^ Ora, as obras da carne são manifestas: imoralidade sexual, impureza e libertinagem;

[[v48-5-20]]

^<<v48-5-20,20>>^ idolatria e feitiçaria; ódio, discórdia, ciúmes, ira, egoísmo, dissensões, facções

[[v48-5-21]]

^<<v48-5-21,21>>^ e inveja; embriaguez, orgias e coisas semelhantes. Eu os advirto, como antes já os adverti, que os que praticam essas coisas não herdarão o Reino de Deus.

[[v48-5-22]]

^<<v48-5-22,22>>^ Mas o fruto do Espírito é amor, alegria, paz, paciência, amabilidade, bondade, fidelidade,

[[v48-5-23]]

^<<v48-5-23,23>>^ mansidão e domínio próprio. Contra essas coisas não há lei.

[[v48-5-24]]

^<<v48-5-24,24>>^ Os que pertencem a Cristo Jesus crucificaram a carne, com as suas paixões e os seus desejos.

[[v48-5-25]]

^<<v48-5-25,25>>^ Se vivemos pelo Espírito, andemos também pelo Espírito.

[[v48-5-26]]

^<<v48-5-26,26>>^ Não sejamos presunçosos, provocando uns aos outros e tendo inveja uns dos outros.

'''

xref:048-galatas/048-galatas-004.adoc#v48-4-0[&#60; Capítulo Anterior] | <<v48-5-0,Topo>> | xref:048-galatas/048-galatas-006.adoc#v48-6-0[Próximo Capítulo &#62;]