include::./index.adoc[]

[[v48-3-0]]
=== Gálatas, 3
// nvi ?, NVI - Nova Versão Internacional

[[v48-3-1]]

^<<v48-3-1,1>>^ Ó gálatas insensatos! Quem os enfeitiçou? Não foi diante dos seus olhos que Jesus Cristo foi exposto como crucificado?

[[v48-3-2]]

^<<v48-3-2,2>>^ Gostaria de saber apenas uma coisa: foi pela prática da lei que vocês receberam o Espírito, ou pela fé naquilo que ouviram?

[[v48-3-3]]

^<<v48-3-3,3>>^ Será que vocês são tão insensatos que, tendo começado pelo Espírito, querem agora se aperfeiçoar pelo esforço próprio?

[[v48-3-4]]

^<<v48-3-4,4>>^ Será que foi inútil sofrerem tantas coisas? Se é que foi inútil!

[[v48-3-5]]

^<<v48-3-5,5>>^ Aquele que lhes dá o seu Espírito e opera milagres entre vocês, realiza essas coisas pela prática da lei ou pela fé com a qual receberam a palavra?

[[v48-3-6]]

^<<v48-3-6,6>>^ Considerem o exemplo de Abraão: "Ele creu em Deus, e isso lhe foi creditado como justiça".

[[v48-3-7]]

^<<v48-3-7,7>>^ Estejam certos, portanto, de que os que são da fé, estes é que são filhos de Abraão.

[[v48-3-8]]

^<<v48-3-8,8>>^ Prevendo a Escritura que Deus justificaria pela fé os gentios, anunciou primeiro as boas novas a Abraão: "Por meio de você todas as nações serão abençoadas".

[[v48-3-9]]

^<<v48-3-9,9>>^ Assim, os que são da fé são abençoados juntamente com Abraão, homem de fé.

[[v48-3-10]]

^<<v48-3-10,10>>^ Já os que são pela prática da lei estão debaixo de maldição, pois está escrito: "Maldito todo aquele que não persiste em praticar todas as coisas escritas no livro da Lei".

[[v48-3-11]]

^<<v48-3-11,11>>^ É evidente que diante de Deus ninguém é justificado pela lei, pois "o justo viverá pela fé".

[[v48-3-12]]

^<<v48-3-12,12>>^ A lei não é baseada na fé; pelo contrário, "quem praticar estas coisas, por elas viverá".

[[v48-3-13]]

^<<v48-3-13,13>>^ Cristo nos redimiu da maldição da lei quando se tornou maldição em nosso lugar, pois está escrito: "Maldito todo aquele que for pendurado num madeiro".

[[v48-3-14]]

^<<v48-3-14,14>>^ Isso para que em Cristo Jesus a bênção de Abraão chegasse também aos gentios, para que recebêssemos a promessa do Espírito mediante a fé.

[[v48-3-15]]

^<<v48-3-15,15>>^ Irmãos, humanamente falando, ninguém pode anular um testamento depois de ratificado, nem acrescentar-lhe algo.

[[v48-3-16]]

^<<v48-3-16,16>>^ Assim também as promessas foram feitas a Abraão e ao seu descendente. A Escritura não diz: "E aos seus descendentes", como se falando de muitos, mas: "Ao seu descendente", dando a entender que se trata de um só, isto é, Cristo.

[[v48-3-17]]

^<<v48-3-17,17>>^ Quero dizer isto: A lei, que veio quatrocentos e trinta anos depois, não anula a aliança previamente estabelecida por Deus, de modo que venha a invalidar a promessa.

[[v48-3-18]]

^<<v48-3-18,18>>^ Pois, se a herança depende da lei, já não depende de promessa. Deus, porém, concedeu-a gratuitamente a Abraão mediante promessa.

[[v48-3-19]]

^<<v48-3-19,19>>^ Qual era então o propósito da lei? Foi acrescentada por causa das transgressões, até que viesse o Descendente a quem se referia a promessa, e foi promulgada por meio de anjos, pela mão de um mediador.

[[v48-3-20]]

^<<v48-3-20,20>>^ Contudo, o mediador representa mais de um; Deus, porém, é um.

[[v48-3-21]]

^<<v48-3-21,21>>^ Então, a lei opõe-se às promessas de Deus? De maneira nenhuma! Pois, se tivesse sido dada uma lei que pudesse conceder vida, certamente a justiça viria da lei.

[[v48-3-22]]

^<<v48-3-22,22>>^ Mas a Escritura encerrou tudo debaixo do pecado, a fim de que a promessa, que é pela fé em Jesus Cristo, fosse dada aos que crêem.

[[v48-3-23]]

^<<v48-3-23,23>>^ Antes que viesse esta fé, estávamos sob a custódia da lei, nela encerrados, até que a fé que haveria de vir fosse revelada.

[[v48-3-24]]

^<<v48-3-24,24>>^ Assim, a lei foi o nosso tutor até Cristo, para que fôssemos justificados pela fé.

[[v48-3-25]]

^<<v48-3-25,25>>^ Agora, porém, tendo chegado a fé, já não estamos mais sob o controle do tutor.

[[v48-3-26]]

^<<v48-3-26,26>>^ Todos vocês são filhos de Deus mediante a fé em Cristo Jesus,

[[v48-3-27]]

^<<v48-3-27,27>>^ pois os que em Cristo foram batizados, de Cristo se revestiram.

[[v48-3-28]]

^<<v48-3-28,28>>^ Não há judeu nem grego, escravo nem livre, homem nem mulher; pois todos são um em Cristo Jesus.

[[v48-3-29]]

^<<v48-3-29,29>>^ E, se vocês são de Cristo, são descendência de Abraão e herdeiros segundo a promessa.

'''

xref:048-galatas/048-galatas-002.adoc#v48-2-0[&#60; Capítulo Anterior] | <<v48-3-0,Topo>> | xref:048-galatas/048-galatas-004.adoc#v48-4-0[Próximo Capítulo &#62;]