include::./index.adoc[]

[[v48-2-0]]
=== Gálatas, 2
// nvi ?, NVI - Nova Versão Internacional

[[v48-2-1]]

^<<v48-2-1,1>>^ Catorze anos depois, subi novamente a Jerusalém, dessa vez com Barnabé, levando também Tito comigo.

[[v48-2-2]]

^<<v48-2-2,2>>^ Fui para lá por causa de uma revelação e expus diante deles o evangelho que prego entre os gentios, fazendo-o, porém, em particular aos que pareciam mais influentes, para não correr ou ter corrido em vão.

[[v48-2-3]]

^<<v48-2-3,3>>^ Mas nem mesmo Tito, que estava comigo, foi obrigado a circuncidar-se, apesar de ser grego.

[[v48-2-4]]

^<<v48-2-4,4>>^ Essa questão foi levantada porque alguns falsos irmãos infiltraram-se em nosso meio para espionar a liberdade que temos em Cristo Jesus e nos reduzir à escravidão.

[[v48-2-5]]

^<<v48-2-5,5>>^ Não nos submetemos a eles nem por um instante, para que a verdade do evangelho permanecesse com vocês.

[[v48-2-6]]

^<<v48-2-6,6>>^ Quanto aos que pareciam influentes — o que eram então não faz diferença para mim; Deus não julga pela aparência — tais homens influentes não me acrescentaram nada.

[[v48-2-7]]

^<<v48-2-7,7>>^ Pelo contrário, reconheceram que a mim havia sido confiada a pregação do evangelho aos incircuncisos, assim como a Pedro, aos circuncisos.

[[v48-2-8]]

^<<v48-2-8,8>>^ Pois Deus, que operou por meio de Pedro como apóstolo aos circuncisos, também operou por meu intermédio para com os gentios.

[[v48-2-9]]

^<<v48-2-9,9>>^ Reconhecendo a graça que me fora concedida, Tiago, Pedro e João, tidos como colunas, estenderam a mão direita a mim e a Barnabé em sinal de comunhão. Eles concordaram em que devíamos nos dirigir aos gentios, e eles, aos circuncisos.

[[v48-2-10]]

^<<v48-2-10,10>>^ Somente pediram que nos lembrássemos dos pobres, o que me esforcei por fazer.

[[v48-2-11]]

^<<v48-2-11,11>>^ Quando, porém, Pedro veio a Antioquia, enfrentei-o face a face, por sua atitude condenável.

[[v48-2-12]]

^<<v48-2-12,12>>^ Pois, antes de chegarem alguns da parte de Tiago, ele comia com os gentios. Quando, porém, eles chegaram, afastou-se e separou-se dos gentios, temendo os que eram da circuncisão.

[[v48-2-13]]

^<<v48-2-13,13>>^ Os demais judeus também se uniram a ele nessa hipocrisia, de modo que até Barnabé se deixou levar.

[[v48-2-14]]

^<<v48-2-14,14>>^ Quando vi que não estavam andando de acordo com a verdade do evangelho, declarei a Pedro, diante de todos: "Você é judeu, mas vive como gentio e não como judeu. Portanto, como pode obrigar gentios a viverem como judeus?

[[v48-2-15]]

^<<v48-2-15,15>>^ "Nós, judeus de nascimento e não ‘gentios pecadores’,

[[v48-2-16]]

^<<v48-2-16,16>>^ sabemos que o ninguém é justificado pela prática da lei, mas mediante a fé em Jesus Cristo. Assim, nós também cremos em Cristo Jesus para sermos justificados pela fé em Cristo, e não pela prática da lei, porque pela prática da lei ninguém será justificado.

[[v48-2-17]]

^<<v48-2-17,17>>^ "Se, porém, procurando ser justificados em Cristo descobrimos que nós mesmos somos pecadores, será Cristo então ministro do pecado? De modo algum!

[[v48-2-18]]

^<<v48-2-18,18>>^ Se reconstruo o que destruí, provo que sou transgressor.

[[v48-2-19]]

^<<v48-2-19,19>>^ Pois, por meio da lei eu morri para a lei, a fim de viver para Deus.

[[v48-2-20]]

^<<v48-2-20,20>>^ Fui crucificado com Cristo. Assim, já não sou eu quem vive, mas Cristo vive em mim. A vida que agora vivo no corpo, vivo-a pela fé no filho de Deus, que me amou e se entregou por mim.

[[v48-2-21]]

^<<v48-2-21,21>>^ Não anulo a graça de Deus; pois, se a justiça vem pela lei, Cristo morreu inutilmente! "

'''

xref:048-galatas/048-galatas-001.adoc#v48-1-0[&#60; Capítulo Anterior] | <<v48-2-0,Topo>> | xref:048-galatas/048-galatas-003.adoc#v48-3-0[Próximo Capítulo &#62;]