include::./index.adoc[]

[[v48-4-0]]
=== Gálatas, 4
// nvi ?, NVI - Nova Versão Internacional

[[v48-4-1]]

^<<v48-4-1,1>>^ Digo porém que, enquanto o herdeiro é menor de idade, em nada difere de um escravo, embora seja dono de tudo.

[[v48-4-2]]

^<<v48-4-2,2>>^ No entanto, ele está sujeito a guardiães e administradores até o tempo determinado por seu pai.

[[v48-4-3]]

^<<v48-4-3,3>>^ Assim também nós, quando éramos menores, estávamos escravizados aos princípios elementares do mundo.

[[v48-4-4]]

^<<v48-4-4,4>>^ Mas, quando chegou a plenitude do tempo, Deus enviou seu Filho, nascido de mulher, nascido debaixo da lei,

[[v48-4-5]]

^<<v48-4-5,5>>^ a fim de redimir os que estavam sob a lei, para que recebêssemos a adoção de filhos.

[[v48-4-6]]

^<<v48-4-6,6>>^ E, porque vocês são filhos, Deus enviou o Espírito de seu Filho aos seus corações, o qual clama: "Aba, Pai".

[[v48-4-7]]

^<<v48-4-7,7>>^ Assim, você já não é mais escravo, mas filho; e, por ser filho, Deus também o tornou herdeiro.

[[v48-4-8]]

^<<v48-4-8,8>>^ Antes, quando vocês não conheciam a Deus, eram escravos daqueles que, por natureza, não são deuses.

[[v48-4-9]]

^<<v48-4-9,9>>^ Mas agora, conhecendo a Deus, ou melhor, sendo por ele conhecidos, como é que estão voltando àqueles mesmos princípios elementares, fracos e sem poder? Querem ser escravizados por eles outra vez?

[[v48-4-10]]

^<<v48-4-10,10>>^ Vocês estão observando dias especiais, meses, ocasiões específicas e anos!

[[v48-4-11]]

^<<v48-4-11,11>>^ Temo que os meus esforços por vocês tenham sido inúteis.

[[v48-4-12]]

^<<v48-4-12,12>>^ Eu lhes suplico, irmãos, que se tornem como eu, pois eu me tornei como vocês. Em nada vocês me ofenderam;

[[v48-4-13]]

^<<v48-4-13,13>>^ como sabem, foi por causa de uma doença que lhes preguei o evangelho pela primeira vez.

[[v48-4-14]]

^<<v48-4-14,14>>^ Embora a minha doença lhes tenha sido uma provação, vocês não me trataram com desprezo ou desdém; pelo contrário, receberam-me como se eu fosse um anjo de Deus, como o próprio Cristo Jesus.

[[v48-4-15]]

^<<v48-4-15,15>>^ Que aconteceu com a alegria de vocês? Tenho certeza que, se fosse possível, vocês teriam arrancado os próprios olhos para dá-los a mim.

[[v48-4-16]]

^<<v48-4-16,16>>^ Tornei-me inimigo de vocês por lhes dizer a verdade?

[[v48-4-17]]

^<<v48-4-17,17>>^ Os que fazem tanto esforço para agradá-los, não agem bem, mas querem isolá-los a fim de que vocês também mostrem zelo por eles.

[[v48-4-18]]

^<<v48-4-18,18>>^ É bom sempre ser zeloso pelo bem, e não apenas quando estou presente.

[[v48-4-19]]

^<<v48-4-19,19>>^ Meus filhos, novamente estou sofrendo dores de parto por sua causa, até que Cristo seja formado em vocês.

[[v48-4-20]]

^<<v48-4-20,20>>^ Eu gostaria de estar com vocês agora e mudar o meu tom de voz, pois estou perplexo quanto a vocês.

[[v48-4-21]]

^<<v48-4-21,21>>^ Digam-me vocês, os que querem estar debaixo da lei: Acaso vocês não ouvem a lei?

[[v48-4-22]]

^<<v48-4-22,22>>^ Pois está escrito que Abraão teve dois filhos, um da escrava e outro da livre.

[[v48-4-23]]

^<<v48-4-23,23>>^ O filho da escrava nasceu de modo natural, mas o filho da livre nasceu mediante promessa.

[[v48-4-24]]

^<<v48-4-24,24>>^ Isso é usado aqui como uma ilustração; estas mulheres representam duas alianças. Uma aliança procede do monte Sinai e gera filhos para a escravidão: esta é Hagar.

[[v48-4-25]]

^<<v48-4-25,25>>^ Hagar representa o monte Sinai, na Arábia, e corresponde à atual cidade de Jerusalém, que está escravizada com os seus filhos.

[[v48-4-26]]

^<<v48-4-26,26>>^ Mas a Jerusalém do alto é livre, e essa é a nossa mãe.

[[v48-4-27]]

^<<v48-4-27,27>>^ Pois está escrito: "Regozije-se, ó estéril, você que nunca teve um filho; grite de alegria, você que nunca esteve em trabalho de parto; porque mais são os filhos da mulher abandonada do que os daquela que tem marido".

[[v48-4-28]]

^<<v48-4-28,28>>^ Vocês, irmãos, são filhos da promessa, como Isaque.

[[v48-4-29]]

^<<v48-4-29,29>>^ Naquele tempo, o filho nascido de modo natural perseguia o filho nascido segundo o Espírito. O mesmo acontece agora.

[[v48-4-30]]

^<<v48-4-30,30>>^ Mas o que diz a Escritura? "Mande embora a escrava e o seu filho, porque o filho da escrava jamais será herdeiro com o filho da livre".

[[v48-4-31]]

^<<v48-4-31,31>>^ Portanto, irmãos, não somos filhos da escrava, mas da livre.

'''

xref:048-galatas/048-galatas-003.adoc#v48-3-0[&#60; Capítulo Anterior] | <<v48-4-0,Topo>> | xref:048-galatas/048-galatas-005.adoc#v48-5-0[Próximo Capítulo &#62;]