include::./index.adoc[]

[[v48-6-0]]
=== Gálatas, 6
// nvi ?, NVI - Nova Versão Internacional

[[v48-6-1]]

^<<v48-6-1,1>>^ Irmãos, se alguém for surpreendido em algum pecado, vocês, que são espirituais deverão restaurá-lo com mansidão. Cuide-se, porém, cada um para que também não seja tentado.

[[v48-6-2]]

^<<v48-6-2,2>>^ Levem os fardos pesados uns dos outros e, assim, cumpram a lei de Cristo.

[[v48-6-3]]

^<<v48-6-3,3>>^ Se alguém se considera alguma coisa, não sendo nada, engana-se a si mesmo.

[[v48-6-4]]

^<<v48-6-4,4>>^ Cada um examine os próprios atos, e então poderá orgulhar-se de si mesmo, sem se comparar com ninguém,

[[v48-6-5]]

^<<v48-6-5,5>>^ pois cada um deverá levar a própria carga.

[[v48-6-6]]

^<<v48-6-6,6>>^ O que está sendo instruído na palavra partilhe todas as coisas boas com quem o instrui.

[[v48-6-7]]

^<<v48-6-7,7>>^ Não se deixem enganar: de Deus não se zomba. Pois o que o homem semear, isso também colherá.

[[v48-6-8]]

^<<v48-6-8,8>>^ Quem semeia para a sua carne, da carne colherá destruição; mas quem semeia para o Espírito, do Espírito colherá a vida eterna.

[[v48-6-9]]

^<<v48-6-9,9>>^ E não nos cansemos de fazer o bem, pois no tempo próprio colheremos, se não desanimarmos.

[[v48-6-10]]

^<<v48-6-10,10>>^ Portanto, enquanto temos oportunidade, façamos o bem a todos, especialmente aos da família da fé.

[[v48-6-11]]

^<<v48-6-11,11>>^ Vejam com que letras grandes estou lhes escrevendo de próprio punho!

[[v48-6-12]]

^<<v48-6-12,12>>^ Os que desejam causar boa impressão exteriormente, tentando obrigá-los a se circuncidarem, agem desse modo apenas para não serem perseguidos por causa da cruz de Cristo.

[[v48-6-13]]

^<<v48-6-13,13>>^ Nem mesmo os que são circuncidados cumprem a lei; querem, no entanto, que vocês sejam circuncidados a fim de se gloriarem no corpo de vocês.

[[v48-6-14]]

^<<v48-6-14,14>>^ Quanto a mim, que eu jamais me glorie, a não ser na cruz de nosso Senhor Jesus Cristo, por meio da qual o mundo foi crucificado para mim, e eu para o mundo.

[[v48-6-15]]

^<<v48-6-15,15>>^ De nada vale ser circuncidado ou não. O que importa é ser uma nova criação.

[[v48-6-16]]

^<<v48-6-16,16>>^ Paz e misericórdia estejam sobre todos os que andam conforme essa regra, e também sobre o Israel de Deus.

[[v48-6-17]]

^<<v48-6-17,17>>^ Sem mais, que ninguém me perturbe, pois trago em meu corpo as marcas de Jesus.

[[v48-6-18]]

^<<v48-6-18,18>>^ Irmãos, que a graça de nosso Senhor Jesus Cristo seja com o espírito de vocês. Amém.

'''

xref:048-galatas/048-galatas-005.adoc#v48-5-0[&#60; Capítulo Anterior] | <<v48-6-0,Topo>> | xref:049-efesios/049-efesios-001.adoc#v49-1-0[Próximo Capítulo &#62;]