include::./index.adoc[]

[[v21-9-0]]
=== Eclesiastes, 9
// nvi ?, NVI - Nova Versão Internacional

[[v21-9-1]]

^<<v21-9-1,1>>^ Refleti nisso tudo e cheguei à conclusão de que os justos e os sábios, e aquilo que eles fazem, estão nas mãos de Deus. O que os espera, se amor ou ódio, ninguém sabe.

[[v21-9-2]]

^<<v21-9-2,2>>^ Todos partilham um destino comum: o justo e o ímpio, o bom e o mau, o puro e o impuro, o que oferece sacrifícios e o que não oferece. O que acontece com o homem bom, acontece com o pecador; o que acontece com quem faz juramentos, acontece com quem teme fazê-los.

[[v21-9-3]]

^<<v21-9-3,3>>^ Este é o mal que há em tudo o que acontece debaixo do sol: O destino de todos é o mesmo. O coração dos homens, além do mais, está cheio de maldade e de loucura durante toda a vida; e por fim eles se juntarão aos mortos.

[[v21-9-4]]

^<<v21-9-4,4>>^ Quem está entre os vivos tem esperança; até um cachorro vivo é melhor do que um leão morto!

[[v21-9-5]]

^<<v21-9-5,5>>^ Pois os vivos sabem que morrerão, mas os mortos nada sabem; para eles não haverá mais recompensa, e já não se tem lembrança deles.

[[v21-9-6]]

^<<v21-9-6,6>>^ Para eles o amor, o ódio e a inveja há muito desapareceram; nunca mais terão parte em nada do que acontece debaixo do sol.

[[v21-9-7]]

^<<v21-9-7,7>>^ Portanto, vá, coma com prazer a sua comida, e beba o seu vinho de coração alegre, pois Deus já se agradou do que você faz.

[[v21-9-8]]

^<<v21-9-8,8>>^ Esteja sempre vestido com roupas de festa, e unja sempre a sua cabeça com óleo.

[[v21-9-9]]

^<<v21-9-9,9>>^ Desfrute a vida com a mulher a quem você ama, todos os dias desta vida sem sentido que Deus dá a você debaixo do sol; todos os seus dias sem sentido! Pois essa é a sua recompensa na vida pelo seu árduo trabalho debaixo do sol.

[[v21-9-10]]

^<<v21-9-10,10>>^ O que as suas mãos tiverem que fazer, que o façam com toda a sua força, pois na sepultura, para onde você vai, não há atividade nem planejamento, não há conhecimento nem sabedoria.

[[v21-9-11]]

^<<v21-9-11,11>>^ Percebi ainda outra coisa debaixo do sol: Os velozes nem sempre vencem a corrida; os fortes nem sempre triunfam na guerra; os sábios nem sempre têm comida; os prudentes nem sempre são ricos; os instruídos nem sempre têm prestígio; pois o tempo e o acaso afetam a todos.

[[v21-9-12]]

^<<v21-9-12,12>>^ Além do mais, ninguém sabe quando virá a sua hora: Assim como os peixes são apanhados numa rede fatal e os pássaros são pegos num laço, também os homens são enredados pelos tempos de desgraça que caem inesperadamente sobre eles.

[[v21-9-13]]

^<<v21-9-13,13>>^ Também vi debaixo do sol este exemplo de sabedoria que muito me impressionou.

[[v21-9-14]]

^<<v21-9-14,14>>^ Havia uma pequena cidade, de poucos habitantes. Um rei poderoso veio contra ela, cercou-a com muitos dispositivos de guerra.

[[v21-9-15]]

^<<v21-9-15,15>>^ Ora, naquela cidade vivia um homem pobre mas sábio, e com sua sabedoria ele salvou a cidade. No entanto, ninguém se lembrou daquele pobre.

[[v21-9-16]]

^<<v21-9-16,16>>^ Por isso pensei: Embora a sabedoria seja melhor do que a força, a sabedoria do pobre é desprezada, e logo já não se dá atenção às suas palavras.

[[v21-9-17]]

^<<v21-9-17,17>>^ As palavras dos sábios devem ser ouvidas com mais atenção do que os gritos de quem domina sobre tolos.

[[v21-9-18]]

^<<v21-9-18,18>>^ A sabedoria é melhor do que as armas de guerra, mas um só pecador destrói muita coisa boa.

'''

xref:021-eclesiastes/021-eclesiastes-008.adoc#v21-8-0[&#60; Capítulo Anterior] | <<v21-9-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-010.adoc#v21-10-0[Próximo Capítulo &#62;]