include::./index.adoc[]

[[v21-12-0]]
=== Eclesiastes, 12
// nvi ?, NVI - Nova Versão Internacional

[[v21-12-1]]

^<<v21-12-1,1>>^ Lembre-se do seu Criador nos dias da sua juventude, antes que venham os dias difíceis e antes que se aproximem os anos em que você dirá: "Não tenho satisfação neles";

[[v21-12-2]]

^<<v21-12-2,2>>^ antes que se escureçam o sol e a luz, a lua e as estrelas, e as nuvens voltem depois da chuva;

[[v21-12-3]]

^<<v21-12-3,3>>^ quando os guardas da casa tremerem e os homens fortes caminharem encurvados, e pararem os moedores por serem poucos, e aqueles que olham pelas janelas enxergarem embaçado;

[[v21-12-4]]

^<<v21-12-4,4>>^ quando as portas da rua forem fechadas e diminuir o som da moagem; quando o barulho das aves o fizer despertar, mas o som de todas as canções lhe parecer fraco;

[[v21-12-5]]

^<<v21-12-5,5>>^ quando você tiver medo de altura, e dos perigos das ruas; quando florir a amendoeira, o gafanhoto for um peso e o desejo já não se despertar. Então o homem se vai para o seu lar eterno, e os pranteadores já vagueiam pelas ruas.

[[v21-12-6]]

^<<v21-12-6,6>>^ Sim, lembre-se dele, antes que se rompa o cordão de prata, ou se quebre a taça de ouro; antes que o cântaro se despedace junto à fonte, a roda se quebre junto ao poço,

[[v21-12-7]]

^<<v21-12-7,7>>^ o pó volte à terra, de onde veio, e o espírito volte a Deus, que o deu.

[[v21-12-8]]

^<<v21-12-8,8>>^ "Tudo sem sentido! Sem sentido! ", diz o mestre. "Nada faz sentido! Nada faz sentido! "

[[v21-12-9]]

^<<v21-12-9,9>>^ Além de ser sábio, o mestre também ensinou conhecimento ao povo. Ele escutou, examinou e colecionou muitos provérbios.

[[v21-12-10]]

^<<v21-12-10,10>>^ Procurou também encontrar as palavras certas, e o que ele escreveu era reto e verdadeiro.

[[v21-12-11]]

^<<v21-12-11,11>>^ As palavras dos sábios são como aguilhões, a coleção dos seus ditos como pregos bem fixados, provenientes do único Pastor.

[[v21-12-12]]

^<<v21-12-12,12>>^ Cuidado, meu filho; nada acrescente a eles. Não há limite para a produção de livros, e estudar demais deixa exausto o corpo.

[[v21-12-13]]

^<<v21-12-13,13>>^ Agora que já se ouviu tudo, aqui está a conclusão: Tema a Deus e guarde os seus mandamentos, pois isso é o essencial para o homem.

[[v21-12-14]]

^<<v21-12-14,14>>^ Pois Deus trará a julgamento tudo o que foi feito, inclusive tudo o que está escondido, seja bom, seja mal.

'''

xref:021-eclesiastes/021-eclesiastes-011.adoc#v21-11-0[&#60; Capítulo Anterior] | <<v21-12-0,Topo>> | xref:022-canticos/022-canticos-001.adoc#v22-1-0[Próximo Capítulo &#62;]