include::./index.adoc[]

[[v21-7-0]]
=== Eclesiastes, 7
// nvi ?, NVI - Nova Versão Internacional

[[v21-7-1]]

^<<v21-7-1,1>>^ Um bom nome é melhor do que um perfume finíssimo, e o dia da morte é melhor do que o dia do nascimento.

[[v21-7-2]]

^<<v21-7-2,2>>^ É melhor ir a uma casa onde há luto do que a uma casa em festa, pois a morte é o destino de todos; os vivos devem levar isso a sério!

[[v21-7-3]]

^<<v21-7-3,3>>^ A tristeza é melhor do que o riso, porque o rosto triste melhora o coração.

[[v21-7-4]]

^<<v21-7-4,4>>^ O coração do sábio está na casa onde há luto, mas o dos tolos, na casa da alegria.

[[v21-7-5]]

^<<v21-7-5,5>>^ É melhor ouvir a repreensão de um sábio do que a canção dos tolos.

[[v21-7-6]]

^<<v21-7-6,6>>^ Tal como o estalo de espinhos debaixo da panela, assim é o riso dos tolos. Isso também não faz sentido.

[[v21-7-7]]

^<<v21-7-7,7>>^ A opressão transforma o sábio em tolo, e o suborno corrompe o coração.

[[v21-7-8]]

^<<v21-7-8,8>>^ O fim das coisas é melhor do que o seu início, e o paciente é melhor que o orgulhoso.

[[v21-7-9]]

^<<v21-7-9,9>>^ Não permita que a ira domine depressa o seu espírito, pois a ira se aloja no íntimo dos tolos.

[[v21-7-10]]

^<<v21-7-10,10>>^ Não diga: "Por que os dias do passado foram melhores que os de hoje? " Pois não é sábio fazer tais perguntas.

[[v21-7-11]]

^<<v21-7-11,11>>^ A sabedoria, como uma herança, é coisa boa e beneficia aqueles que vêem o sol.

[[v21-7-12]]

^<<v21-7-12,12>>^ A sabedoria oferece proteção, como o faz o dinheiro, mas a vantagem do conhecimento é esta: a sabedoria preserva a vida de quem a possui.

[[v21-7-13]]

^<<v21-7-13,13>>^ Considere o que Deus fez: Quem pode endireitar o que ele fez torto?

[[v21-7-14]]

^<<v21-7-14,14>>^ Quando os dias forem bons, aproveite-os bem; mas, quando forem ruins, considere: Deus fez tanto um quanto o outro, para evitar que o homem descubra qualquer coisa sobre o seu futuro.

[[v21-7-15]]

^<<v21-7-15,15>>^ Nesta vida sem sentido eu já vi de tudo: um justo que morreu apesar da sua justiça, e um ímpio que teve vida longa apesar da sua impiedade.

[[v21-7-16]]

^<<v21-7-16,16>>^ Não seja excessivamente justo nem demasiadamente sábio; por que destruir-se a si mesmo?

[[v21-7-17]]

^<<v21-7-17,17>>^ Não seja demasiadamente ímpio e não seja tolo; por que morrer antes do tempo?

[[v21-7-18]]

^<<v21-7-18,18>>^ É bom reter uma coisa e não abrir mão da outra, pois quem teme a Deus evitará ambos os extremos.

[[v21-7-19]]

^<<v21-7-19,19>>^ A sabedoria torna o sábio mais poderoso que uma cidade guardada por dez valentes.

[[v21-7-20]]

^<<v21-7-20,20>>^ Todavia, não há um só justo na terra, ninguém que pratique o bem e nunca peque.

[[v21-7-21]]

^<<v21-7-21,21>>^ Não dê atenção a todas as palavras que o povo diz, caso contrário, poderá ouvir o seu próprio servo falando mal de você;

[[v21-7-22]]

^<<v21-7-22,22>>^ pois em seu coração você sabe que muitas vezes você mesmo também falou mal de outros.

[[v21-7-23]]

^<<v21-7-23,23>>^ Tudo isso eu examinei mediante a sabedoria e disse: Estou decidido a ser sábio; mas isso estava fora do meu alcance.

[[v21-7-24]]

^<<v21-7-24,24>>^ A realidade está bem distante e é muito profunda; quem pode descobri-la?

[[v21-7-25]]

^<<v21-7-25,25>>^ Por isso dediquei-me a aprender, a investigar, a buscar a sabedoria e a razão de ser das coisas, para compreender a insensatez da impiedade e a loucura da insensatez.

[[v21-7-26]]

^<<v21-7-26,26>>^ Descobri que muito mais amarga do que a morte é a mulher que serve de laço, cujo coração é uma armadilha e cujas mãos são correntes. O homem que agrada a Deus escapará dela, mas ao pecador ela apanhará.

[[v21-7-27]]

^<<v21-7-27,27>>^ "Veja", diz o Mestre, "foi isto que descobri: Ao comparar uma coisa com outra para descobrir a sua razão de ser,

[[v21-7-28]]

^<<v21-7-28,28>>^ sim, durante essa minha busca que ainda não terminou, entre mil homens, descobri apenas um que julgo digno, mas entre as mulheres não achei uma sequer.

[[v21-7-29]]

^<<v21-7-29,29>>^ Assim, cheguei a esta conclusão: Deus fez os homens justos, mas eles foram em busca de muitas intrigas. "

'''

xref:021-eclesiastes/021-eclesiastes-006.adoc#v21-6-0[&#60; Capítulo Anterior] | <<v21-7-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-008.adoc#v21-8-0[Próximo Capítulo &#62;]