include::./index.adoc[]

[[v21-10-0]]
=== Eclesiastes, 10
// nvi ?, NVI - Nova Versão Internacional

[[v21-10-1]]

^<<v21-10-1,1>>^ Assim como a mosca morta produz mau cheiro e estraga o perfume, também um pouco de insensatez pesa mais que a sabedoria e a honra.

[[v21-10-2]]

^<<v21-10-2,2>>^ O coração do sábio se inclina para o bem, mas o coração do tolo, para o mal.

[[v21-10-3]]

^<<v21-10-3,3>>^ Mesmo quando anda pelo caminho, o tolo age sem o mínimo bom senso e mostra a todos que não passa de um tolo.

[[v21-10-4]]

^<<v21-10-4,4>>^ Se a ira de uma autoridade se levantar contra você, não abandone o seu posto; a tranqüilidade evita grandes erros.

[[v21-10-5]]

^<<v21-10-5,5>>^ Há outro mal que vi debaixo do sol, um erro cometido pelos que governam:

[[v21-10-6]]

^<<v21-10-6,6>>^ Tolos são postos em cargos elevados, enquanto ricos ocupam cargos inferiores.

[[v21-10-7]]

^<<v21-10-7,7>>^ Tenho visto servos andando a cavalo, e príncipes andando a pé, como servos.

[[v21-10-8]]

^<<v21-10-8,8>>^ Quem cava um poço cairá nele; quem derruba um muro será picado por uma cobra.

[[v21-10-9]]

^<<v21-10-9,9>>^ Quem arranca pedras, com elas se ferirá; quem racha lenha se arrisca.

[[v21-10-10]]

^<<v21-10-10,10>>^ Se o machado está cego e sua lâmina não foi afiada, é preciso golpear com mais força; agir com sabedoria assegura o sucesso.

[[v21-10-11]]

^<<v21-10-11,11>>^ Se a cobra morder antes de ser encantada, para que servirá o encantador?

[[v21-10-12]]

^<<v21-10-12,12>>^ As palavras do sábio lhe trazem benefícios, mas os lábios do insensato o destroem.

[[v21-10-13]]

^<<v21-10-13,13>>^ No início as suas palavras são mera tolice, mas no final são loucura perversa.

[[v21-10-14]]

^<<v21-10-14,14>>^ Embora o tolo fale sem parar, ninguém sabe o que está para vir; quem poderá dizer a outrem o que lhe acontecerá depois?

[[v21-10-15]]

^<<v21-10-15,15>>^ O trabalho do tolo o deixa tão exausto que ele nem consegue achar o caminho de casa.

[[v21-10-16]]

^<<v21-10-16,16>>^ Pobre da terra cujo rei é jovem demais e cujos líderes fazem banquetes logo de manhã.

[[v21-10-17]]

^<<v21-10-17,17>>^ Feliz é a terra cujo rei é de origem nobre, e cujos líderes comem no devido tempo, para recuperar as forças, e não para embriagar-se.

[[v21-10-18]]

^<<v21-10-18,18>>^ Por causa da preguiça, o telhado se enverga; por causa das mãos indolentes, a casa tem goteiras.

[[v21-10-19]]

^<<v21-10-19,19>>^ O banquete é feito para divertir, e o vinho torna a vida alegre, mas isso tudo se paga com dinheiro.

[[v21-10-20]]

^<<v21-10-20,20>>^ Nem em pensamento insulte o rei! Nem mesmo em seu quarto amaldiçoe o rico! Porque uma ave do céu poderá levar as suas palavras, e seres alados poderão divulgar o que você disser.

'''

xref:021-eclesiastes/021-eclesiastes-009.adoc#v21-9-0[&#60; Capítulo Anterior] | <<v21-10-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-011.adoc#v21-11-0[Próximo Capítulo &#62;]