include::./index.adoc[]

[[v21-2-0]]
=== Eclesiastes, 2
// nvi ?, NVI - Nova Versão Internacional

[[v21-2-1]]

^<<v21-2-1,1>>^ Pensei comigo mesmo: Vamos. Vou experimentar a alegria. Descubra as coisas boas da vida! Mas isso também se revelou inútil.

[[v21-2-2]]

^<<v21-2-2,2>>^ Concluí que o rir é loucura, e a alegria de nada vale.

[[v21-2-3]]

^<<v21-2-3,3>>^ Decidi-me entregar ao vinho e à extravagância; mantendo, porém, a mente orientada pela sabedoria. Eu queria saber o que valesse a pena, debaixo do céu, nos poucos dias da vida humana.

[[v21-2-4]]

^<<v21-2-4,4>>^ Lancei-me a grandes projetos: construí casas e plantei vinhas para mim.

[[v21-2-5]]

^<<v21-2-5,5>>^ Fiz jardins e pomares, e neles plantei todo tipo de árvore frutífera.

[[v21-2-6]]

^<<v21-2-6,6>>^ Construí também reservatórios para regar os meus bosques verdejantes.

[[v21-2-7]]

^<<v21-2-7,7>>^ Comprei escravos e escravas e tive escravos que nasceram em minha casa. Além disso tive também mais bois e ovelhas do que todos os que viveram antes de mim em Jerusalém.

[[v21-2-8]]

^<<v21-2-8,8>>^ Ajuntei para mim prata e ouro, tesouros de reis e de províncias. Servi-me de cantores e cantoras, e também de um harém, as delícias do homem.

[[v21-2-9]]

^<<v21-2-9,9>>^ Tornei-me mais famoso e poderoso do que todos os que viveram em Jerusalém antes de mim, conservando comigo a minha sabedoria.

[[v21-2-10]]

^<<v21-2-10,10>>^ Não me neguei nada que os meus olhos desejaram; não me recusei a dar prazer algum ao meu coração. Na verdade, eu me alegrei em todo o meu trabalho; essa foi a recompensa de todo o meu esforço.

[[v21-2-11]]

^<<v21-2-11,11>>^ Contudo, quando avaliei tudo o que as minhas mãos haviam feito e o trabalho que eu tanto me esforçara para realizar, percebi que tudo foi inútil, foi correr atrás do vento; não há qualquer proveito no que se faz debaixo do sol.

[[v21-2-12]]

^<<v21-2-12,12>>^ Então passei a refletir na sabedoria, na loucura e na insensatez. O que pode fazer o sucessor do rei a não ser repetir o que já foi feito?

[[v21-2-13]]

^<<v21-2-13,13>>^ Percebi que a sabedoria é melhor que a insensatez, assim como a luz é melhor do que as trevas.

[[v21-2-14]]

^<<v21-2-14,14>>^ O homem sábio tem olhos que enxergam, mas o tolo anda nas trevas; todavia, percebi que ambos têm o mesmo destino.

[[v21-2-15]]

^<<v21-2-15,15>>^ Então pensei comigo mesmo: O que acontece ao tolo também me acontecerá. Que proveito eu tive em ser sábio? Então eu disse no meu íntimo: Isso não faz o menor sentido!

[[v21-2-16]]

^<<v21-2-16,16>>^ Nem o sábio, nem o tolo, serão lembrados para sempre; nos dias futuros ambos serão esquecidos. Como pode o sábio morrer como morre o tolo?

[[v21-2-17]]

^<<v21-2-17,17>>^ Por isso desprezei a vida, pois o trabalho que se faz debaixo do sol pareceu-me muito pesado. Tudo era inútil, era correr atrás do vento.

[[v21-2-18]]

^<<v21-2-18,18>>^ Desprezei todas as coisas pelas quais eu tanto me esforçara debaixo do sol, pois terei que deixá-las para aquele que me suceder.

[[v21-2-19]]

^<<v21-2-19,19>>^ E quem pode dizer se ele será sábio ou tolo? Contudo, terá domínio sobre tudo o que realizei com o meu trabalho e com a minha sabedoria debaixo do sol. Isso também não faz sentido.

[[v21-2-20]]

^<<v21-2-20,20>>^ Cheguei ao ponto de me desesperar por causa de todo o trabalho em que tanto me esforcei debaixo do sol.

[[v21-2-21]]

^<<v21-2-21,21>>^ Pois um homem pode realizar o seu trabalho com sabedoria, conhecimento e habilidade, mas terá que deixar tudo o que possui como herança para alguém que não se esforçou por aquilo. Isso também é um absurdo e uma grande injustiça.

[[v21-2-22]]

^<<v21-2-22,22>>^ Que proveito tem um homem de todo o esforço e de toda a ansiedade com que trabalha debaixo do sol?

[[v21-2-23]]

^<<v21-2-23,23>>^ Durante toda a sua vida, seu trabalho não passa de dor e tristeza; mesmo à noite a sua mente não descansa. Isso também é absurdo.

[[v21-2-24]]

^<<v21-2-24,24>>^ Para o homem não existe nada melhor do que comer, beber e encontrar prazer em seu trabalho. E vi que isso também vem da mão de Deus.

[[v21-2-25]]

^<<v21-2-25,25>>^ E quem aproveitou melhor as comidas e os prazeres do que eu?

[[v21-2-26]]

^<<v21-2-26,26>>^ Ao homem que o agrada, Deus recompensa com sabedoria, conhecimento e felicidade. Quanto ao pecador, Deus o encarrega de ajuntar e armazenar riquezas para entregá-las a quem o agrada. Isso também é inútil, é correr atrás do vento.

'''

xref:021-eclesiastes/021-eclesiastes-001.adoc#v21-1-0[&#60; Capítulo Anterior] | <<v21-2-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-003.adoc#v21-3-0[Próximo Capítulo &#62;]