include::./index.adoc[]

[[v6-12-0]]
=== Josué, 12
// nvi ?, NVI - Nova Versão Internacional

[[v6-12-1]]

^<<v6-12-1,1>>^ São estes os reis que os israelitas derrotaram, e de cujo território se apossaram a leste do Jordão, desde o ribeiro do Arnom até o monte Hermom, inclusive todo o lado leste da Arabá:

[[v6-12-2]]

^<<v6-12-2,2>>^ Seom, rei dos amorreus, que reinou em Hesbom. Governou desde Aroer, na borda do ribeiro do Arnom, desde o meio do ribeiro, até o rio Jaboque, que é a fronteira dos amonitas. Esse território incluía a metade de Gileade.

[[v6-12-3]]

^<<v6-12-3,3>>^ Também governou a Arabá oriental, desde o mar de Quinerete até o mar da Arabá, o mar Salgado, até Bete-Jesimote, e mais ao sul, ao pé das encostas do Pisga.

[[v6-12-4]]

^<<v6-12-4,4>>^ Tomaram o território de Ogue, rei de Basã, um dos últimos refains, que reinou em Asterote e Edrei.

[[v6-12-5]]

^<<v6-12-5,5>>^ Ele governou o monte Hermom, Salcá, toda a Basã, até a fronteira do povo de Gesur e de Maaca, e metade de Gileade, até a fronteira de Seom, rei de Hesbom.

[[v6-12-6]]

^<<v6-12-6,6>>^ Moisés, servo do Senhor, e os israelitas os derrotaram. E Moisés, servo do Senhor, deu a terra deles como propriedade às tribos de Rúben, de Gade e à metade da tribo de Manassés.

[[v6-12-7]]

^<<v6-12-7,7>>^ São estes os reis que Josué e os israelitas derrotaram no lado ocidental do Jordão, desde Baal-Gade, no vale do Líbano, até o monte Halaque, que se ergue na direção de Seir. Josué deu a terra deles por herança às tribos de Israel, repartindo-a entre elas —

[[v6-12-8]]

^<<v6-12-8,8>>^ a serra central, a Sefelá, a Arabá, as encostas das montanhas, o deserto e o Neguebe — as terras dos hititas, dos amorreus, dos cananeus, dos ferezeus, dos heveus e dos jebuseus:

[[v6-12-9]]

^<<v6-12-9,9>>^ o rei de Jericó, o rei de Ai, próxima a Betel,

[[v6-12-10]]

^<<v6-12-10,10>>^ o rei de Jerusalém, o rei de Hebrom,

[[v6-12-11]]

^<<v6-12-11,11>>^ o rei de Jarmute, o rei de Láquis,

[[v6-12-12]]

^<<v6-12-12,12>>^ o rei de Eglom, o rei de Gezer,

[[v6-12-13]]

^<<v6-12-13,13>>^ o rei de Debir, o rei de Geder,

[[v6-12-14]]

^<<v6-12-14,14>>^ o rei de Hormá, o rei de Arade,

[[v6-12-15]]

^<<v6-12-15,15>>^ o rei de Libna, o rei de Adulão,

[[v6-12-16]]

^<<v6-12-16,16>>^ o rei de Maquedá, o rei de Betel,

[[v6-12-17]]

^<<v6-12-17,17>>^ o rei de Tapua, o rei de Héfer,

[[v6-12-18]]

^<<v6-12-18,18>>^ o rei de Afeque, o rei de Lasarom,

[[v6-12-19]]

^<<v6-12-19,19>>^ o rei de Madom, o rei de Hazor,

[[v6-12-20]]

^<<v6-12-20,20>>^ o rei de Sinrom-Merom, o rei de Acsafe,

[[v6-12-21]]

^<<v6-12-21,21>>^ o rei de Taanaque, o rei de Megido,

[[v6-12-22]]

^<<v6-12-22,22>>^ o rei de Quedes, o rei de Jocneão do Carmelo,

[[v6-12-23]]

^<<v6-12-23,23>>^ o rei de Dor em Nafote-Dor, o rei de Goim de Gilgal,

[[v6-12-24]]

^<<v6-12-24,24>>^ e o rei de Tirza. Trinta e um reis ao todo.

'''

xref:006-josue/006-josue-011.adoc#v6-11-0[&#60; Capítulo Anterior] | <<v6-12-0,Topo>> | xref:006-josue/006-josue-013.adoc#v6-13-0[Próximo Capítulo &#62;]