include::./index.adoc[]

[[v6-6-0]]
=== Josué, 6
// nvi ?, NVI - Nova Versão Internacional

[[v6-6-1]]

^<<v6-6-1,1>>^ Jericó estava completamente fechada por causa dos israelitas. Ninguém saía nem entrava.

[[v6-6-2]]

^<<v6-6-2,2>>^ Então o Senhor disse a Josué: "Saiba que entreguei nas suas mãos Jericó, seu rei e seus homens de guerra.

[[v6-6-3]]

^<<v6-6-3,3>>^ Marche uma vez ao redor da cidade, com todos os homens armados. Faça isso durante seis dias.

[[v6-6-4]]

^<<v6-6-4,4>>^ Sete sacerdotes levarão cada um uma trombeta de chifre de carneiro à frente da arca. No sétimo dia, marchem todos sete vezes ao redor da cidade, e os sacerdotes toquem as trombetas.

[[v6-6-5]]

^<<v6-6-5,5>>^ Quando as trombetas soarem um longo toque, todo o povo dará um forte grito; o muro da cidade cairá e o povo atacará, cada um do lugar onde estiver".

[[v6-6-6]]

^<<v6-6-6,6>>^ Josué, filho de Num, chamou os sacerdotes e lhes disse: "Levem a arca da aliança do Senhor. Sete de vocês levarão trombetas à frente da arca".

[[v6-6-7]]

^<<v6-6-7,7>>^ E ordenou ao povo: "Avancem! Marchem ao redor da cidade! Os soldados armados irão à frente da arca do Senhor".

[[v6-6-8]]

^<<v6-6-8,8>>^ Quando Josué terminou de falar ao povo, os sete sacerdotes que levavam suas trombetas perante o Senhor saíram à frente, tocando as trombetas. E a arca da aliança do Senhor ia atrás deles.

[[v6-6-9]]

^<<v6-6-9,9>>^ Os soldados armados marchavam à frente dos sacerdotes que tocavam as trombetas, e o restante dos soldados seguia a arca. Durante todo esse tempo tocavam-se as trombetas.

[[v6-6-10]]

^<<v6-6-10,10>>^ Mas, Josué tinha ordenado ao povo: "Não dêem o brado de guerra, não levantem a voz, não digam palavra alguma, até ao dia em que eu lhes ordenar. Então vocês gritarão! "

[[v6-6-11]]

^<<v6-6-11,11>>^ Assim se fez a arca do Senhor rodear a cidade, dando uma volta em torno dela. Então o povo voltou para o acampamento, onde passou a noite.

[[v6-6-12]]

^<<v6-6-12,12>>^ Josué levantou-se na manhã seguinte, e os sacerdotes levaram a arca do Senhor.

[[v6-6-13]]

^<<v6-6-13,13>>^ Os sete sacerdotes que levavam as trombetas iam adiante da arca do Senhor, tocando as trombetas. Os homens armados iam à frente deles, e o restante dos soldados seguia a arca do Senhor, enquanto as trombetas tocavam continuamente.

[[v6-6-14]]

^<<v6-6-14,14>>^ No segundo dia também rodearam a cidade uma vez, e voltaram ao acampamento. E durante seis dias repetiram aquilo.

[[v6-6-15]]

^<<v6-6-15,15>>^ No sétimo dia, levantaram-se ao romper da manhã e marcharam da mesma maneira sete vezes ao redor da cidade; foi apenas nesse dia que rodearam a cidade sete vezes.

[[v6-6-16]]

^<<v6-6-16,16>>^ Na sétima vez, quando os sacerdotes deram o toque de trombeta, Josué ordenou ao povo: "Gritem! O Senhor lhes entregou a cidade!

[[v6-6-17]]

^<<v6-6-17,17>>^ A cidade, com tudo o que nela existe, será consagrada ao Senhor para destruição. Somente a prostituta Raabe e todos os que estão com ela em sua casa serão poupados, pois ela escondeu os espiões que enviamos.

[[v6-6-18]]

^<<v6-6-18,18>>^ Mas fiquem longe das coisas consagradas, não se apossem de nenhuma delas, para que não sejam destruídos. Do contrário trarão destruição e desgraça ao acampamento de Israel.

[[v6-6-19]]

^<<v6-6-19,19>>^ Toda a prata, todo o ouro e todos os utensílios de bronze e de ferro são sagrados e pertencem ao Senhor e deverão ser levados para o seu tesouro".

[[v6-6-20]]

^<<v6-6-20,20>>^ Quando soaram as trombetas o povo gritou. Ao som das trombetas, e do forte grito, o muro caiu. Cada um atacou do lugar onde estava, e tomaram a cidade.

[[v6-6-21]]

^<<v6-6-21,21>>^ Consagraram a cidade ao Senhor, destruindo ao fio da espada homens, mulheres, jovens, velhos, bois, ovelhas e jumentos, todos os seres vivos que nela havia.

[[v6-6-22]]

^<<v6-6-22,22>>^ Josué disse aos dois homens que tinham espionado a terra: "Entrem na casa da prostituta e tirem-na de lá com todos os seus parentes, conforme o juramento que fizeram a ela".

[[v6-6-23]]

^<<v6-6-23,23>>^ Então os jovens que tinham espionado a terra entraram e trouxeram Raabe, seu pai, sua mãe, seus irmãos e todos os seus parentes. Tiraram de lá todos os da sua família e os deixaram num local fora do acampamento de Israel.

[[v6-6-24]]

^<<v6-6-24,24>>^ Depois incendiaram a cidade inteira e tudo o que nela havia, mas entregaram a prata, o ouro e os utensílios de bronze e de ferro ao tesouro do santuário do Senhor.

[[v6-6-25]]

^<<v6-6-25,25>>^ Mas Josué poupou a prostituta Raabe, a sua família, e todos os seus pertences, pois ela escondeu os homens que Josué tinha enviado a Jericó como espiões. E Raabe vive entre os israelitas até hoje.

[[v6-6-26]]

^<<v6-6-26,26>>^ Naquela ocasião Josué pronunciou este juramento solene: "Maldito seja diante do Senhor o homem que reconstruir esta cidade de Jericó: "Ao preço de seu filho mais velho lançará os alicerces da cidade; ao preço de seu filho mais novo porá suas portas! "

[[v6-6-27]]

^<<v6-6-27,27>>^ Assim o Senhor esteve com Josué, cuja fama espalhou-se por toda a região.

'''

xref:006-josue/006-josue-005.adoc#v6-5-0[&#60; Capítulo Anterior] | <<v6-6-0,Topo>> | xref:006-josue/006-josue-007.adoc#v6-7-0[Próximo Capítulo &#62;]