include::./index.adoc[]

[[v6-18-0]]
=== Josué, 18
// nvi ?, NVI - Nova Versão Internacional

[[v6-18-1]]

^<<v6-18-1,1>>^ Toda a comunidade dos israelitas reuniu-se em Siló e ali armou a Tenda do Encontro. A terra foi dominada por eles;

[[v6-18-2]]

^<<v6-18-2,2>>^ mas, sete tribos ainda não tinham recebido a sua herança.

[[v6-18-3]]

^<<v6-18-3,3>>^ Então Josué disse aos israelitas: "Até quando vocês vão negligenciar a posse da terra que o Senhor, o Deus dos seus antepassados, lhes deu?

[[v6-18-4]]

^<<v6-18-4,4>>^ Escolham três homens de cada tribo, e eu os enviarei. Eles vão examinar a terra e mapeá-la, conforme a herança de cada tribo. Depois voltarão a mim.

[[v6-18-5]]

^<<v6-18-5,5>>^ Dividam a terra em sete partes. Judá ficará em seu território ao sul, e a tribo de José em seu território ao norte.

[[v6-18-6]]

^<<v6-18-6,6>>^ Depois que fizerem um mapa das sete partes da terra, tragam-no para mim, e eu farei sorteio para vocês na presença do Senhor, do nosso Deus.

[[v6-18-7]]

^<<v6-18-7,7>>^ Mas os levitas nada receberão entre vocês, pois o sacerdócio do Senhor é a herança deles. Gade, Rúben e a metade da tribo de Manassés já receberam a sua herança no lado leste do Jordão, dada a eles por Moisés, servo do Senhor".

[[v6-18-8]]

^<<v6-18-8,8>>^ Quando os homens estavam de partida para mapear a terra, Josué os instruiu: "Vão examinar a terra e façam uma descrição dela. Depois voltem, e eu farei um sorteio para vocês aqui em Siló, na presença do Senhor".

[[v6-18-9]]

^<<v6-18-9,9>>^ Os homens partiram e percorreram a terra. Descreveram-na num rolo, cidade por cidade, em sete partes, e retornaram a Josué, ao acampamento de Siló.

[[v6-18-10]]

^<<v6-18-10,10>>^ Josué fez então um sorteio para eles em Siló, na presença do Senhor, e ali distribuiu a terra aos israelitas, conforme a porção devida a cada tribo.

[[v6-18-11]]

^<<v6-18-11,11>>^ Saiu a sorte para a tribo de Benjamim, clã por clã. O território sorteado ficava entre as tribos de Judá e José:

[[v6-18-12]]

^<<v6-18-12,12>>^ No lado norte a sua fronteira começava no Jordão, passava pela encosta norte de Jericó e prosseguia para o oeste, para a região montanhosa, terminando no deserto de Bete-Áven.

[[v6-18-13]]

^<<v6-18-13,13>>^ Dali ia para a encosta sul de Luz, que é Betel, e descia para Atarote-Adar, na montanha que está ao sul de Bete-Horom Baixa.

[[v6-18-14]]

^<<v6-18-14,14>>^ Da montanha que fica defronte de Bete-Horom, no sul, a fronteira virava para o sul, ao longo do lado ocidental, e terminava em Quiriate-Baal, que é Quiriate-Jearim, cidade do povo de Judá. Esse era o lado ocidental.

[[v6-18-15]]

^<<v6-18-15,15>>^ A fronteira sul começava no oeste, nos arredores de Quiriate-Jearim, e chegava à fonte de Neftoa.

[[v6-18-16]]

^<<v6-18-16,16>>^ A fronteira descia até o sopé da montanha que fica defronte do vale de Ben-Hinom, ao norte do vale de Refaim. Depois, prosseguia, descendo pelo vale de Hinom ao longo da encosta sul da cidade dos jebuseus e chegava até En-Rogel.

[[v6-18-17]]

^<<v6-18-17,17>>^ Fazia então uma curva para o norte, ia para En-Semes, continuava até Gelilote, que fica defronte da subida de Adumim, e descia até a Pedra de Boã, nome filho de Rúben.

[[v6-18-18]]

^<<v6-18-18,18>>^ Prosseguia para a encosta norte de Bete-Arabá, e daí descia para a Arabá.

[[v6-18-19]]

^<<v6-18-19,19>>^ Depois ia para a encosta norte de Bete-Hogla e terminava na baía norte do mar Salgado, na foz do Jordão, no sul. Essa era a fronteira sul.

[[v6-18-20]]

^<<v6-18-20,20>>^ O Jordão delimitava a fronteira oriental. Essas eram as fronteiras que demarcavam por todos os lados a herança dos clãs de Benjamim.

[[v6-18-21]]

^<<v6-18-21,21>>^ A tribo de Benjamim, clã por clã, recebeu as seguintes cidades: Jericó, Bete-Hogla, Emeque-Queziz,

[[v6-18-22]]

^<<v6-18-22,22>>^ Bete-Arabá, Zemaraim, Betel,

[[v6-18-23]]

^<<v6-18-23,23>>^ Avim, Pará, Ofra,

[[v6-18-24]]

^<<v6-18-24,24>>^ Quefar-Amonai, Ofni e Geba. Eram doze cidades com os seus povoados.

[[v6-18-25]]

^<<v6-18-25,25>>^ Gibeom, Ramá, Beerote,

[[v6-18-26]]

^<<v6-18-26,26>>^ Mispá, Quefira, Mosa,

[[v6-18-27]]

^<<v6-18-27,27>>^ Requém, Irpeel, Tarala,

[[v6-18-28]]

^<<v6-18-28,28>>^ Zela, Elefe, Jebus, que é Jerusalém, Gibeá e Quiriate. Eram catorze cidades com os seus povoados. Essa foi a herança dos clãs de Benjamim.

'''

xref:006-josue/006-josue-017.adoc#v6-17-0[&#60; Capítulo Anterior] | <<v6-18-0,Topo>> | xref:006-josue/006-josue-019.adoc#v6-19-0[Próximo Capítulo &#62;]