include::./index.adoc[]

[[v6-1-0]]
=== Josué, 1
// nvi ?, NVI - Nova Versão Internacional

[[v6-1-1]]

^<<v6-1-1,1>>^ Depois da morte de Moisés, servo do Senhor, disse o Senhor a Josué, filho de Num, auxiliar de Moisés:

[[v6-1-2]]

^<<v6-1-2,2>>^ "Meu servo Moisés está morto. Agora, pois, você e todo este povo, preparem-se para atravessar o rio Jordão e entrar na terra que eu estou para dar aos israelitas.

[[v6-1-3]]

^<<v6-1-3,3>>^ Como prometi a Moisés, todo lugar onde puserem os pés eu darei a vocês.

[[v6-1-4]]

^<<v6-1-4,4>>^ Seu território se estenderá do deserto ao Líbano, e do grande rio, o Eufrates, toda a terra dos hititas, até o mar Grande, no oeste.

[[v6-1-5]]

^<<v6-1-5,5>>^ Ninguém conseguirá resistir a você, todos os dias da sua vida. Assim como estive com Moisés, estarei com você; nunca o deixarei, nunca o abandonarei.

[[v6-1-6]]

^<<v6-1-6,6>>^ "Seja forte e corajoso, porque você conduzirá esse povo para herdar a terra que prometi sob juramento aos seus antepassados.

[[v6-1-7]]

^<<v6-1-7,7>>^ Somente seja forte e muito corajoso! Tenha o cuidado de obedecer a toda a lei que o meu servo Moisés lhe ordenou; não se desvie dela, nem para a direita nem para a esquerda, para que você seja bem sucedido por onde quer que andar.

[[v6-1-8]]

^<<v6-1-8,8>>^ Não deixe de falar as palavras deste Livro da Lei e de meditar nelas de dia e de noite, para que você cumpra fielmente tudo o que nele está escrito. Só então os seus caminhos prosperarão e você será bem sucedido.

[[v6-1-9]]

^<<v6-1-9,9>>^ Não fui eu que lhe ordenei? Seja forte e corajoso! Não se apavore, nem se desanime, pois o Senhor, o seu Deus, estará com você por onde você andar".

[[v6-1-10]]

^<<v6-1-10,10>>^ Assim Josué ordenou aos oficiais do povo:

[[v6-1-11]]

^<<v6-1-11,11>>^ "Percorram o acampamento e ordenem ao povo que preparem as provisões. Daqui a três dias vocês atravessarão o Jordão neste ponto para entrar e tomar posse da terra que o Senhor, o seu Deus, lhes dá".

[[v6-1-12]]

^<<v6-1-12,12>>^ Mas às tribos de Rúben, de Gade e à metade da tribo de Manassés Josué disse:

[[v6-1-13]]

^<<v6-1-13,13>>^ "Lembrem-se da ordem que Moisés, servo do Senhor, deu a vocês, quando o Senhor, o seu Deus, lhes prometeu descanso e dar-lhes esta terra:

[[v6-1-14]]

^<<v6-1-14,14>>^ ‘As suas mulheres, os seus filhos e os seus rebanhos poderão ficar na terra que Moisés lhes deu a leste do Jordão, mas todos os homens de guerra, preparados para lutar, atravessarão à frente dos seus irmãos israelitas’. Vocês os ajudarão

[[v6-1-15]]

^<<v6-1-15,15>>^ até que o Senhor conceda um lugar de descanso para eles, como deu a vocês, e até que eles também tenham tomado posse da terra que o Senhor, o seu Deus, lhes dá. Depois disso vocês poderão voltar e ocupar a sua própria terra, que Moisés, servo do Senhor, lhes deu a leste do Jordão, na direção do nascer do sol".

[[v6-1-16]]

^<<v6-1-16,16>>^ Então eles responderam a Josué: "Tudo o que você nos ordenar, faremos, e aonde quer que nos enviar, iremos.

[[v6-1-17]]

^<<v6-1-17,17>>^ Assim como obedecemos totalmente a Moisés, também obedeceremos a você. Somente que o Senhor, o seu Deus, seja com você, como foi com Moisés.

[[v6-1-18]]

^<<v6-1-18,18>>^ Todo aquele que se rebelar contra as suas instruções e não obedecer às suas ordens, seja o que for que você lhe ordenar, será morto. Somente seja forte e corajoso! "

'''

xref:005-deuteronomio/005-deuteronomio-034.adoc#v5-34-0[&#60; Capítulo Anterior] | <<v6-1-0,Topo>> | xref:006-josue/006-josue-002.adoc#v6-2-0[Próximo Capítulo &#62;]