include::./index.adoc[]

[[v6-9-0]]
=== Josué, 9
// nvi ?, NVI - Nova Versão Internacional

[[v6-9-1]]

^<<v6-9-1,1>>^ E souberam disso todos os reis que viviam a oeste do Jordão, nas montanhas, na Sefelá e em todo o litoral do mar Grande até o Líbano. Eram os reis dos hititas, dos amorreus, dos cananeus, dos ferezeus, dos heveus e dos jebuseus.

[[v6-9-2]]

^<<v6-9-2,2>>^ Eles se ajuntaram para guerrear contra Josué, contra Israel.

[[v6-9-3]]

^<<v6-9-3,3>>^ Contudo, quando os habitantes de Gibeom souberam o que Josué tinha feito com Jericó e Ai,

[[v6-9-4]]

^<<v6-9-4,4>>^ recorreram a um ardil. Enviaram uma delegação, com jumentos carregados de sacos gastos e vasilhas de couro velhas, rachadas e remendadas.

[[v6-9-5]]

^<<v6-9-5,5>>^ Os homens calçavam sandálias gastas e remendadas e vestiam roupas velhas. Todos os pães do suprimento deles estavam secos e esmigalhados.

[[v6-9-6]]

^<<v6-9-6,6>>^ Foram a Josué, ao acampamento de Gilgal, e disseram a ele e aos homens de Israel: "Viemos de uma terra distante. Queremos que façam um acordo conosco".

[[v6-9-7]]

^<<v6-9-7,7>>^ Os israelitas disseram aos heveus: "Talvez vocês vivam perto de nós. Como poderemos fazer um acordo com vocês? "

[[v6-9-8]]

^<<v6-9-8,8>>^ "Somos seus servos", disseram a Josué. Josué, porém, perguntou: "Quem são vocês? De onde vocês vêm? "

[[v6-9-9]]

^<<v6-9-9,9>>^ Ele responderam: "Seus servos vieram de uma terra muito distante por causa da fama do Senhor, do seu Deus. Pois ouvimos falar dele, de tudo o que fez no Egito,

[[v6-9-10]]

^<<v6-9-10,10>>^ e de tudo o que fez aos dois reis dos amorreus a leste do Jordão: Seom, rei de Hesbom, e Ogue, rei de Basã, que reinava em Asterote.

[[v6-9-11]]

^<<v6-9-11,11>>^ E os nossos líderes e todos os habitantes de nossa terra nos disseram: ‘Juntem provisões para a viagem, vão encontrar-se com eles e digam-lhes: Somos seus servos, façam um acordo conosco’.

[[v6-9-12]]

^<<v6-9-12,12>>^ Este nosso pão estava quente quando o embrulhamos em casa no dia em que saímos de viagem para cá. Mas vejam como agora está seco e esmigalhado.

[[v6-9-13]]

^<<v6-9-13,13>>^ Estas vasilhas de couro que enchemos de vinho eram novas, mas agora estão rachadas. E as nossas roupas e sandálias estão gastas por causa da longa viagem".

[[v6-9-14]]

^<<v6-9-14,14>>^ Os israelitas examinaram as provisões dos heveus, mas não consultaram o Senhor.

[[v6-9-15]]

^<<v6-9-15,15>>^ Então Josué fez um acordo de paz com eles, garantindo poupar-lhes a vida, e os líderes da comunidade o ratificaram com juramento.

[[v6-9-16]]

^<<v6-9-16,16>>^ Três dias depois de fazerem o acordo com os gibeonitas, os israelitas souberam que eram vizinhos e que viviam perto deles.

[[v6-9-17]]

^<<v6-9-17,17>>^ Por isso partiram de viagem, e três dias depois chegaram às cidades dos heveus, que eram Gibeom, Quefira, Beerote e Quiriate-Jearim.

[[v6-9-18]]

^<<v6-9-18,18>>^ Mas não os atacaram, porque os líderes da comunidade lhes haviam feito um juramento em nome do Senhor, o Deus de Israel. Toda a comunidade, porém, queixou-se contra os líderes,

[[v6-9-19]]

^<<v6-9-19,19>>^ que lhes responderam: "Fizemos a eles o nosso juramento em nome do Senhor, o Deus de Israel; por isso não podemos tocar neles.

[[v6-9-20]]

^<<v6-9-20,20>>^ Todavia, nós os trataremos assim: Vamos deixá-los viver, para que não caia sobre nós a ira divina por quebrarmos o juramento que lhes fizemos".

[[v6-9-21]]

^<<v6-9-21,21>>^ E acrescentaram: "Eles ficarão vivos, mas serão lenhadores e carregadores de água para toda a comunidade". E assim se manteve a promessa dos líderes.

[[v6-9-22]]

^<<v6-9-22,22>>^ Então Josué convocou os gibeonitas e disse: "Por que vocês nos enganaram dizendo que viviam muito longe de nós, quando na verdade vivem perto?

[[v6-9-23]]

^<<v6-9-23,23>>^ Agora vocês estão debaixo de maldição: Nunca deixarão de ser escravos, rachando lenha e carregando água para a casa do meu Deus".

[[v6-9-24]]

^<<v6-9-24,24>>^ Eles responderam a Josué: "Os seus servos ficaram sabendo como o Senhor, o seu Deus, ordenou que o seu servo Moisés lhes desse toda esta terra e que destruísse todos os seus habitantes da presença de vocês. Tivemos medo do que poderia acontecer conosco por causa de vocês. Por isso agimos assim.

[[v6-9-25]]

^<<v6-9-25,25>>^ Estamos agora nas suas mãos. Faça conosco o que lhe parecer bom e justo".

[[v6-9-26]]

^<<v6-9-26,26>>^ Josué então os protegeu e não permitiu que os matassem.

[[v6-9-27]]

^<<v6-9-27,27>>^ Mas naquele dia fez dos gibeonitas lenhadores e carregadores de água para a comunidade e para o altar do Senhor, no local que o Senhor escolhesse. É o que eles são até hoje.

'''

xref:006-josue/006-josue-008.adoc#v6-8-0[&#60; Capítulo Anterior] | <<v6-9-0,Topo>> | xref:006-josue/006-josue-010.adoc#v6-10-0[Próximo Capítulo &#62;]