include::./index.adoc[]

[[v6-15-0]]
=== Josué, 15
// nvi ?, NVI - Nova Versão Internacional

[[v6-15-1]]

^<<v6-15-1,1>>^ As terras distribuídas à tribo de Judá, clã por clã, estendiam-se para o sul até a fronteira com Edom, até o deserto de Zim, no extremo sul.

[[v6-15-2]]

^<<v6-15-2,2>>^ Sua fronteira sul começava na ponta de terra do extremo sul do mar Salgado,

[[v6-15-3]]

^<<v6-15-3,3>>^ passava pelo sul da subida de Acrabim, prosseguia até Zim e daí até o sul de Cades-Barnéia. Depois passava por Hezrom, indo até Adar e fazia uma curva em direção a Carca.

[[v6-15-4]]

^<<v6-15-4,4>>^ Dali continuava até Azmom, indo até o ribeiro do Egito e terminando no mar. Essa é a fronteira sul deles.

[[v6-15-5]]

^<<v6-15-5,5>>^ A fronteira oriental é o mar Salgado, até a foz do Jordão. A fronteira norte começava na enseada, na foz do Jordão,

[[v6-15-6]]

^<<v6-15-6,6>>^ subia até Bete-Hogla e passava ao norte de Bete-Arabá, até a Pedra de Boã, filho de Rúben.

[[v6-15-7]]

^<<v6-15-7,7>>^ A fronteira subia então do vale de Acor até Debir, e virava para o norte, na direção de Gilgal, que fica defronte da subida de Adumim, ao sul do ribeiro. Passava pelas águas de En-Semes, indo até En-Rogel.

[[v6-15-8]]

^<<v6-15-8,8>>^ Depois subia pelo vale de Ben-Hinom, ao longo da encosta sul da cidade dos jebuseus, isto é, Jerusalém. Dali subia até o alto da montanha, a oeste do vale de Hinom, no lado norte do vale de Refaim.

[[v6-15-9]]

^<<v6-15-9,9>>^ Do alto da montanha a fronteira prosseguia para a fonte de Neftoa, ia para as cidades do monte Efrom e descia na direção de Baalá, que é Quiriate-Jearim.

[[v6-15-10]]

^<<v6-15-10,10>>^ De Baalá fazia uma curva em direção ao oeste, até o monte Seir, prosseguia pela encosta norte do monte Jearim, isto é Quesalom; em seguida continuava descendo até Bete-Semes e passava por Timna.

[[v6-15-11]]

^<<v6-15-11,11>>^ Depois ia para a encosta norte de Ecrom, virava na direção de Sicrom, continuava até o monte Baalá e chegava a Jabneel, terminando no mar.

[[v6-15-12]]

^<<v6-15-12,12>>^ A fronteira ocidental era o litoral do mar Grande. Eram essas as fronteiras que demarcavam Judá por todos os lados, de acordo com os seus clãs.

[[v6-15-13]]

^<<v6-15-13,13>>^ Conforme a ordem dada pelo Senhor, Josué deu a Calebe, filho de Jefoné, uma porção de terra em Judá, que foi Quiriate-Arba, isto é, Hebrom. Arba era antepassado de Enaque.

[[v6-15-14]]

^<<v6-15-14,14>>^ Calebe expulsou de Hebrom os três enaquins: Sesai, Aimã e Talmai, descendentes de Enaque.

[[v6-15-15]]

^<<v6-15-15,15>>^ Dali avançou contra o povo de Debir, anteriormente chamada Quiriate-Sefer.

[[v6-15-16]]

^<<v6-15-16,16>>^ E Calebe disse: "Darei minha filha Acsa por mulher ao homem que atacar e conquistar Quiriate-Sefer".

[[v6-15-17]]

^<<v6-15-17,17>>^ Otoniel, filho de Quenaz, irmão de Calebe, a conquistou; e Calebe lhe deu sua filha Acsa por mulher.

[[v6-15-18]]

^<<v6-15-18,18>>^ Quando Acsa foi viver com Otoniel, ela o pressionou para que pedisse um campo ao pai dela. Assim que ela desceu do jumento, perguntou-lhe Calebe: "O que você quer? "

[[v6-15-19]]

^<<v6-15-19,19>>^ "Quero um presente", respondeu ela. "Já que me deu terras no Neguebe, dê-me também fontes de água. " Então Calebe lhe deu as fontes superiores e as inferiores.

[[v6-15-20]]

^<<v6-15-20,20>>^ Esta é a herança da tribo de Judá, clã por clã:

[[v6-15-21]]

^<<v6-15-21,21>>^ As cidades que ficavam no extremo sul da tribo de Judá, no Neguebe, na direção da fronteira de Edom, eram: Cabzeel, Eder, Jagur,

[[v6-15-22]]

^<<v6-15-22,22>>^ Quiná, Dimona, Adada,

[[v6-15-23]]

^<<v6-15-23,23>>^ Quedes, Hazor, Itnã,

[[v6-15-24]]

^<<v6-15-24,24>>^ Zife, Telém, Bealote,

[[v6-15-25]]

^<<v6-15-25,25>>^ Hazor-Hadata, Queriote-Hezrom, que é Hazor,

[[v6-15-26]]

^<<v6-15-26,26>>^ Amã, Sema, Moladá,

[[v6-15-27]]

^<<v6-15-27,27>>^ Hazar-Gada, Hesmom, Bete-Pelete,

[[v6-15-28]]

^<<v6-15-28,28>>^ Hazar-Sual, Berseba, Biziotiá,

[[v6-15-29]]

^<<v6-15-29,29>>^ Baalá, Iim, Azém,

[[v6-15-30]]

^<<v6-15-30,30>>^ Eltolade, Quesil, Hormá,

[[v6-15-31]]

^<<v6-15-31,31>>^ Ziclague, Madmana, Sansana,

[[v6-15-32]]

^<<v6-15-32,32>>^ Lebaote, Silim, Aim e Rimom. Eram um total de vinte e nove cidades com seus povoados.

[[v6-15-33]]

^<<v6-15-33,33>>^ Na Sefelá: Estaol, Zorá, Asná,

[[v6-15-34]]

^<<v6-15-34,34>>^ Zanoa, En-Ganim, Tapua, Enã,

[[v6-15-35]]

^<<v6-15-35,35>>^ Jarmute, Adulão, Socó, Azeca,

[[v6-15-36]]

^<<v6-15-36,36>>^ Saaraim, Aditaim, e Gederá ou Gederotaim. Eram catorze cidades com seus povoados.

[[v6-15-37]]

^<<v6-15-37,37>>^ Zenã, Hadasa, Migdal-Gade,

[[v6-15-38]]

^<<v6-15-38,38>>^ Dileã, Mispá, Jocteel,

[[v6-15-39]]

^<<v6-15-39,39>>^ Láquis, Bozcate, Eglom,

[[v6-15-40]]

^<<v6-15-40,40>>^ Cabom, Laamás, Quitlis,

[[v6-15-41]]

^<<v6-15-41,41>>^ Gederote, Bete-Dagom, Naamá e Maquedá. Eram dezesseis cidades com seus povoados.

[[v6-15-42]]

^<<v6-15-42,42>>^ Libna, Eter, Asã,

[[v6-15-43]]

^<<v6-15-43,43>>^ Iftá, Asná, Nezibe,

[[v6-15-44]]

^<<v6-15-44,44>>^ Queila, Aczibe e Maressa. Eram nove cidades com seus povoados.

[[v6-15-45]]

^<<v6-15-45,45>>^ Ecrom, com suas vilas e seus povoados;

[[v6-15-46]]

^<<v6-15-46,46>>^ de Ecrom até o mar, todas as cidades nas proximidades de Asdode, juntamente com os seus povoados;

[[v6-15-47]]

^<<v6-15-47,47>>^ Asdode, com suas vilas e seus povoados; e Gaza, com suas vilas e seus povoados, até o ribeiro do Egito e o litoral do mar Grande.

[[v6-15-48]]

^<<v6-15-48,48>>^ Na região montanhosa: Samir, Jatir, Socó,

[[v6-15-49]]

^<<v6-15-49,49>>^ Daná, Quiriate-Sana, que é Debir,

[[v6-15-50]]

^<<v6-15-50,50>>^ Anabe, Estemo, Anim,

[[v6-15-51]]

^<<v6-15-51,51>>^ Gósen, Holom e Gilo. Eram onze cidades com seus povoados.

[[v6-15-52]]

^<<v6-15-52,52>>^ Arabe, Dumá, Esã,

[[v6-15-53]]

^<<v6-15-53,53>>^ Janim, Bete-Tapua, Afeca,

[[v6-15-54]]

^<<v6-15-54,54>>^ Hunta, Quiriate-Arba, que é Hebrom e Zior. Eram nove cidades com seus povoados.

[[v6-15-55]]

^<<v6-15-55,55>>^ Maom, Carmelo, Zife, Jutá,

[[v6-15-56]]

^<<v6-15-56,56>>^ Jezreel, Jocdeão, Zanoa,

[[v6-15-57]]

^<<v6-15-57,57>>^ Caim, Gibeá e Timna. Eram dez cidades com seus povoados.

[[v6-15-58]]

^<<v6-15-58,58>>^ Halul, Bete-Zur, Gedor,

[[v6-15-59]]

^<<v6-15-59,59>>^ Maarate, Bete-Anote e Eltecom. Eram seis cidades com seus povoados.

[[v6-15-60]]

^<<v6-15-60,60>>^ Quiriate-Baal, que é Quiriate-Jearim e Rabá. Eram duas cidades com seus povoados.

[[v6-15-61]]

^<<v6-15-61,61>>^ No deserto: Bete-Arabá, Midim, Secacá,

[[v6-15-62]]

^<<v6-15-62,62>>^ Nibsã, Cidade do Sal e En-Gedi. Eram seis cidades com seus povoados.

[[v6-15-63]]

^<<v6-15-63,63>>^ Os descendentes de Judá não conseguiram expulsar os jebuseus, que viviam em Jerusalém; até hoje os jebuseus vivem ali com o povo de Judá.

'''

xref:006-josue/006-josue-014.adoc#v6-14-0[&#60; Capítulo Anterior] | <<v6-15-0,Topo>> | xref:006-josue/006-josue-016.adoc#v6-16-0[Próximo Capítulo &#62;]