include::./index.adoc[]

[[v6-10-0]]
=== Josué, 10
// nvi ?, NVI - Nova Versão Internacional

[[v6-10-1]]

^<<v6-10-1,1>>^ Sucedeu que Adoni-Zedeque, rei de Jerusalém, soube que Josué tinha conquistado Ai e a tinha destruído totalmente, fazendo com Ai e seu rei o que fizera com Jericó e seu rei, e que o povo de Gibeom tinha feito a paz com Israel e estava vivendo no meio deles.

[[v6-10-2]]

^<<v6-10-2,2>>^ Ele e o seu povo ficaram com muito medo, pois Gibeom era tão importante como uma cidade governada por um rei; era maior do que Ai, e todos os seus homens eram bons guerreiros.

[[v6-10-3]]

^<<v6-10-3,3>>^ Por isso Adoni-Zedeque, rei de Jerusalém, fez o seguinte apelo a Hoão, rei de Hebrom, a Piram, rei de Jarmute, a Jafia, rei de Láquis, e a Debir, rei de Eglom:

[[v6-10-4]]

^<<v6-10-4,4>>^ "Venham para cá e ajudem-me a atacar Gibeom, pois ela fez a paz com Josué e com os israelitas".

[[v6-10-5]]

^<<v6-10-5,5>>^ Então os cinco reis dos amorreus, os reis de Jerusalém, de Hebrom, de Jarmute, de Láquis e de Eglom reuniram-se e vieram com todos os seus exércitos. Cercaram Gibeom e a atacaram.

[[v6-10-6]]

^<<v6-10-6,6>>^ Os gibeonitas enviaram esta mensagem a Josué, ao acampamento de Gilgal: "Não abandone os seus servos. Venha depressa! Salve-nos! Ajude-nos, pois todos os reis amorreus que vivem nas montanhas se uniram contra nós! "

[[v6-10-7]]

^<<v6-10-7,7>>^ Josué partiu de Gilgal com todo o seu exército, inclusive com os seus melhores guerreiros.

[[v6-10-8]]

^<<v6-10-8,8>>^ E disse o Senhor a Josué: "Não tenha medo desses reis; eu os entreguei nas suas mãos. Nenhum deles conseguirá resistir a você".

[[v6-10-9]]

^<<v6-10-9,9>>^ Depois de uma noite inteira de marcha desde Gilgal, Josué os apanhou de surpresa.

[[v6-10-10]]

^<<v6-10-10,10>>^ O Senhor os lançou em confusão diante de Israel, que lhes impôs grande derrota em Gibeom. Os israelitas os perseguiram na subida para Bete-Horom e os mataram por todo o caminho, até Azeca e Maquedá.

[[v6-10-11]]

^<<v6-10-11,11>>^ Enquanto fugiam de Israel na descida de Bete-Horom para Azeca, do céu o Senhor lançou sobre eles grandes pedras de granizo, que mataram mais gente do que as espadas dos israelitas.

[[v6-10-12]]

^<<v6-10-12,12>>^ No dia em que o Senhor entregou os amorreus aos israelitas, Josué exclamou ao Senhor, na presença de Israel: "Sol, pare sobre Gibeom! E você, ó lua, sobre o vale de Aijalom! "

[[v6-10-13]]

^<<v6-10-13,13>>^ O sol parou, e a lua se deteve, até a nação vingar-se dos seus inimigos, como está escrito no Livro de Jasar. O sol parou no meio do céu e por quase um dia inteiro não se pôs.

[[v6-10-14]]

^<<v6-10-14,14>>^ Nunca antes nem depois houve um dia como aquele, quando o Senhor atendeu a um homem. Sem dúvida o Senhor lutava por Israel!

[[v6-10-15]]

^<<v6-10-15,15>>^ Então Josué voltou com todo o Israel ao acampamento de Gilgal.

[[v6-10-16]]

^<<v6-10-16,16>>^ Os cinco reis fugiram e se esconderam na caverna de Maquedá.

[[v6-10-17]]

^<<v6-10-17,17>>^ Avisaram a Josué que eles tinham sido achados numa caverna em Maquedá.

[[v6-10-18]]

^<<v6-10-18,18>>^ Disse ele: "Rolem grandes pedras até a entrada da caverna, e deixem ali alguns homens de guarda.

[[v6-10-19]]

^<<v6-10-19,19>>^ Mas não se detenham! Persigam os inimigos. Ataquem-nos pela retaguarda e não os deixem chegar às suas cidades, pois o Senhor, o seu Deus, os entregou em suas mãos".

[[v6-10-20]]

^<<v6-10-20,20>>^ Assim Josué e os israelitas os derrotaram por completo, quase exterminando-os. Mas alguns conseguiram escapar e refugiaram-se em suas cidades fortificadas.

[[v6-10-21]]

^<<v6-10-21,21>>^ O exército inteiro voltou então em segurança a Josué, ao acampamento de Maquedá, e depois disso, ninguém mais ousou abrir a boca para provocar os israelitas.

[[v6-10-22]]

^<<v6-10-22,22>>^ Então disse Josué: "Abram a entrada da caverna e tragam-me aqueles cinco reis".

[[v6-10-23]]

^<<v6-10-23,23>>^ Os cinco reis foram tirados da caverna. Eram os reis de Jerusalém, de Hebrom, de Jarmute, de Láquis e de Eglom.

[[v6-10-24]]

^<<v6-10-24,24>>^ Quando os levaram a Josué, ele convocou todos os homens de Israel e disse aos comandantes do exército que o tinham acompanhado: "Venham aqui e ponham o pé no pescoço destes reis". E eles obedeceram.

[[v6-10-25]]

^<<v6-10-25,25>>^ Disse-lhes Josué: "Não tenham medo! Não se desanimem! Sejam fortes e corajosos! É isso que o Senhor fará com todos os inimigos que vocês tiverem que combater".

[[v6-10-26]]

^<<v6-10-26,26>>^ Depois Josué matou os reis e mandou pendurá-los em cinco árvores, onde ficaram até à tarde.

[[v6-10-27]]

^<<v6-10-27,27>>^ Ao pôr-do-sol, sob as ordens de Josué, eles foram tirados das árvores e jogados na caverna onde haviam se escondido. Na entrada da caverna colocaram grandes pedras, que lá estão até hoje.

[[v6-10-28]]

^<<v6-10-28,28>>^ Naquele dia Josué tomou Maquedá. Atacou a cidade e matou o seu rei à espada e exterminou todos os que nela viviam, sem deixar sobreviventes. E fez com o rei de Maquedá o que tinha feito com o rei de Jericó.

[[v6-10-29]]

^<<v6-10-29,29>>^ Então Josué, e todo o Israel com ele, avançou de Maquedá para Libna e a atacou.

[[v6-10-30]]

^<<v6-10-30,30>>^ O Senhor entregou também aquela cidade e seu rei nas mãos dos israelitas. Josué atacou a cidade e matou à espada todos os que nela viviam, sem deixar nenhum sobrevivente ali. E fez com o seu rei o que fizera com o rei de Jericó.

[[v6-10-31]]

^<<v6-10-31,31>>^ Depois Josué, e todo o Israel com ele, avançou de Libna para Láquis, cercou-a e a atacou.

[[v6-10-32]]

^<<v6-10-32,32>>^ O Senhor entregou Láquis nas mãos dos israelitas, e Josué tomou-a no dia seguinte. Atacou a cidade e matou à espada todos os que nela viviam, como tinha feito com Libna.

[[v6-10-33]]

^<<v6-10-33,33>>^ Nesse meio tempo Horão, rei de Gezer, fora socorrer Láquis, mas Josué o derrotou, a ele e ao seu exército, sem deixar sobrevivente algum.

[[v6-10-34]]

^<<v6-10-34,34>>^ Josué, e todo o Israel com ele, avançou de Láquis para Eglom, cercou-a e a atacou.

[[v6-10-35]]

^<<v6-10-35,35>>^ Eles a conquistaram naquele mesmo dia, feriram-na à espada e exterminaram os que nela viviam, como tinham feito com Láquis.

[[v6-10-36]]

^<<v6-10-36,36>>^ Então Josué, e todo o Israel com ele, foi de Eglom para Hebrom e a atacou.

[[v6-10-37]]

^<<v6-10-37,37>>^ Tomaram a cidade e a feriram à espada, como também o seu rei, os seus povoados e todos os que nela viviam, sem deixar sobrevivente algum. Destruíram totalmente a cidade e todos os que nela viviam, como tinham feito com Eglom.

[[v6-10-38]]

^<<v6-10-38,38>>^ Depois Josué, e todo o Israel com ele, voltou e atacou Debir.

[[v6-10-39]]

^<<v6-10-39,39>>^ Tomaram a cidade, seu rei e seus povoados, e os mataram à espada. Exterminaram os que nela viviam, sem deixar sobrevivente algum. Fizeram com Debir e seu rei o que tinham feito com Libna e seu rei e com Hebrom.

[[v6-10-40]]

^<<v6-10-40,40>>^ Assim Josué conquistou a região toda, incluindo a serra central, o Neguebe, as encostas e as vertentes, e derrotou todos os seus reis, sem deixar sobrevivente algum. Exterminou tudo o que respirava, conforme o Senhor, o Deus de Israel, tinha ordenado.

[[v6-10-41]]

^<<v6-10-41,41>>^ Josué os derrotou desde Cades-Barnéia até Gaza, e toda a região de Gósen, e de lá até Gibeom.

[[v6-10-42]]

^<<v6-10-42,42>>^ Também subjugou todos esses reis e conquistou suas terras numa única campanha, pois o Senhor, o Deus de Israel, lutou por Israel.

[[v6-10-43]]

^<<v6-10-43,43>>^ Então Josué retornou com todo o Israel ao acampamento de Gilgal.

'''

xref:006-josue/006-josue-009.adoc#v6-9-0[&#60; Capítulo Anterior] | <<v6-10-0,Topo>> | xref:006-josue/006-josue-011.adoc#v6-11-0[Próximo Capítulo &#62;]