include::./index.adoc[]

[[v6-8-0]]
=== Josué, 8
// nvi ?, NVI - Nova Versão Internacional

[[v6-8-1]]

^<<v6-8-1,1>>^ E disse o Senhor a Josué: "Não tenha medo! Não se desanime! Leve todo o exército com você e avance contra Ai. Eu entreguei nas suas mãos o rei de Ai, seu povo, sua cidade e sua terra.

[[v6-8-2]]

^<<v6-8-2,2>>^ Você fará com Ai e seu rei o que fez com Jericó e seu rei; e desta vez vocês poderão se apossar dos despojos e dos animais. Prepare uma emboscada atrás da cidade".

[[v6-8-3]]

^<<v6-8-3,3>>^ Então Josué e todo o exército se prepararam para atacar a cidade de Ai. Ele escolheu trinta mil dos seus melhores homens de guerra e os enviou de noite

[[v6-8-4]]

^<<v6-8-4,4>>^ com a seguinte ordem: "Atenção! Preparem uma emboscada atrás da cidade, e não se afastem muito dela. Fiquem todos alerta.

[[v6-8-5]]

^<<v6-8-5,5>>^ Eu e todos os que estiverem comigo nos aproximaremos da cidade. Quando os homens nos atacarem como fizeram antes, fugiremos deles.

[[v6-8-6]]

^<<v6-8-6,6>>^ Eles nos perseguirão até que os tenhamos atraído para longe da cidade, pois dirão: ‘Estão fugindo de nós como fizeram antes’. Quando estivermos fugindo,

[[v6-8-7]]

^<<v6-8-7,7>>^ vocês sairão da emboscada e tomarão a cidade. O Senhor, o seu Deus, a entregará em suas mãos.

[[v6-8-8]]

^<<v6-8-8,8>>^ Depois que tomarem a cidade, vocês a incendiarão. Façam o que o Senhor ordenou. Atentem bem para as minhas instruções".

[[v6-8-9]]

^<<v6-8-9,9>>^ Então Josué os enviou. Eles foram ficar de emboscada, entre Betel e Ai, a oeste de Ai. Josué, porém, passou aquela noite com o povo.

[[v6-8-10]]

^<<v6-8-10,10>>^ Na manhã seguinte Josué passou em revista os homens, e ele e os líderes de Israel partiram à frente deles para atacar a cidade.

[[v6-8-11]]

^<<v6-8-11,11>>^ Todos os homens de guerra que estavam com ele avançaram, aproximaram-se da cidade pela frente e armaram acampamento ao norte de Ai, onde o vale os separava da cidade.

[[v6-8-12]]

^<<v6-8-12,12>>^ Josué pôs de emboscada cerca de cinco mil homens entre Betel e Ai, a oeste da cidade.

[[v6-8-13]]

^<<v6-8-13,13>>^ Os que estavam no acampamento ao norte da cidade, e os que estavam na emboscada a oeste, tomaram posição. Naquela noite Josué foi ao vale.

[[v6-8-14]]

^<<v6-8-14,14>>^ Quando o rei de Ai viu isso, ele e todos os homens da cidade se apressaram, levantaram-se logo cedo e saíram para enfrentar Israel no campo de batalha, no local de onde se avista a Arabá. Ele não sabia da emboscada armada contra ele atrás da cidade.

[[v6-8-15]]

^<<v6-8-15,15>>^ Josué e todo o Israel deixaram-se perseguir por eles e fugiram para o deserto.

[[v6-8-16]]

^<<v6-8-16,16>>^ Todos os homens de Ai foram chamados para persegui-los. Eles perseguiram Josué e foram atraídos para longe da cidade.

[[v6-8-17]]

^<<v6-8-17,17>>^ Nem um só homem ficou em Ai e em Betel; todos foram atrás de Israel. Deixaram a cidade aberta e saíram em perseguição de Israel.

[[v6-8-18]]

^<<v6-8-18,18>>^ Disse então o Senhor a Josué: "Estende a lança que você tem na mão na direção de Ai, pois nas suas mãos entregarei a cidade". Josué estendeu a lança na direção de Ai,

[[v6-8-19]]

^<<v6-8-19,19>>^ e assim que o fez, os homens da emboscada saíram correndo da sua posição, entraram na cidade, tomaram-na e depressa a incendiaram.

[[v6-8-20]]

^<<v6-8-20,20>>^ Quando os homens de Ai olharam para trás e viram a fumaça da cidade subindo ao céu, não tinham para onde escapar, pois os israelitas que fugiam para o deserto se voltaram contra os seus perseguidores.

[[v6-8-21]]

^<<v6-8-21,21>>^ Vendo Josué e todo o Israel que os homens da emboscada tinham tomado a cidade e que desta subia fumaça, deram meia-volta e atacaram os homens de Ai.

[[v6-8-22]]

^<<v6-8-22,22>>^ Os outros israelitas também saíram da cidade para lutar contra eles, de modo que foram cercados, tendo os israelitas dos dois lados. Então os israelitas os mataram, sem deixar sobreviventes nem fugitivos,

[[v6-8-23]]

^<<v6-8-23,23>>^ mas prenderam vivo o rei de Ai e o levaram a Josué.

[[v6-8-24]]

^<<v6-8-24,24>>^ Israel terminou de matar os habitantes de Ai no campo e no deserto, onde os tinha perseguido; eles morreram ao fio da espada. Depois disso, todos os israelitas voltaram à cidade de Ai e mataram os que lá haviam ficado.

[[v6-8-25]]

^<<v6-8-25,25>>^ Doze mil homens e mulheres caíram mortos naquele dia. Era toda a população de Ai.

[[v6-8-26]]

^<<v6-8-26,26>>^ Pois Josué não recuou a lança até exterminar todos os habitantes de Ai.

[[v6-8-27]]

^<<v6-8-27,27>>^ Mas Israel se apossou dos animais e dos despojos daquela cidade, conforme a ordem que o Senhor tinha dado a Josué.

[[v6-8-28]]

^<<v6-8-28,28>>^ Assim Josué incendiou Ai e fez dela um perpétuo monte de ruínas, um lugar abandonado até hoje.

[[v6-8-29]]

^<<v6-8-29,29>>^ Enforcou o rei de Ai numa árvore e ali o deixou até à tarde. Ao pôr-do-sol Josué ordenou que tirassem o corpo da árvore e que o atirassem à entrada da cidade. E sobre ele ergueram um grande monte de pedras, que perdura até hoje.

[[v6-8-30]]

^<<v6-8-30,30>>^ Então Josué construiu no monte Ebal um altar ao Senhor, ao Deus de Israel,

[[v6-8-31]]

^<<v6-8-31,31>>^ conforme Moisés, servo do Senhor, tinha ordenado aos israelitas. Ele o construiu de acordo com o que está escrito no Livro da Lei de Moisés: um altar de pedras não lavradas, nas quais não se usou ferramenta de ferro. Sobre ele ofereceram ao Senhor holocaustos e sacrifícios de comunhão.

[[v6-8-32]]

^<<v6-8-32,32>>^ Ali, na presença dos israelitas, Josué copiou nas pedras a Lei que Moisés havia escrito.

[[v6-8-33]]

^<<v6-8-33,33>>^ Todo o Israel, estrangeiros e naturais da terra, com os seus líderes, os seus oficiais e os seus juízes, estavam de pé dos dois lados da arca da aliança do Senhor, diante dos sacerdotes levitas, que a carregavam. Metade do povo estava de pé, defronte do monte Gerizim, e metade, defronte do monte Ebal. Tudo conforme Moisés, servo do Senhor, tinha ordenado anteriormente, para que o povo de Israel fosse abençoado.

[[v6-8-34]]

^<<v6-8-34,34>>^ Em seguida Josué leu todas as palavras da lei, a bênção e a maldição, segundo o que está escrito no Livro da Lei.

[[v6-8-35]]

^<<v6-8-35,35>>^ Não houve uma só palavra de tudo o que Moisés tinha ordenado que Josué não lesse para toda a assembléia de Israel, inclusive mulheres, crianças, e os estrangeiros que viviam no meio deles.

'''

xref:006-josue/006-josue-007.adoc#v6-7-0[&#60; Capítulo Anterior] | <<v6-8-0,Topo>> | xref:006-josue/006-josue-009.adoc#v6-9-0[Próximo Capítulo &#62;]