include::./index.adoc[]

[[v6-13-0]]
=== Josué, 13
// nvi ?, NVI - Nova Versão Internacional

[[v6-13-1]]

^<<v6-13-1,1>>^ Sendo Josué já velho, de idade bastante avançada, o Senhor lhe disse: "Você já está velho, e ainda há muita terra para ser conquistada.

[[v6-13-2]]

^<<v6-13-2,2>>^ "Esta é a terra que resta: todas as regiões dos filisteus e dos gesuritas;

[[v6-13-3]]

^<<v6-13-3,3>>^ desde o rio Sior, próximo ao Egito, até o território de Ecrom, ao norte, todo esse território considerado cananeu. Abrange a região dos aveus, isto é, dos cinco chefes filisteus, governantes de Gaza, de Asdode, de Ascalom, de Gate e de Ecrom.

[[v6-13-4]]

^<<v6-13-4,4>>^ Resta ainda, desde o sul, toda a terra dos cananeus, desde Ara dos sidônios até Afeque, a região dos amorreus,

[[v6-13-5]]

^<<v6-13-5,5>>^ a dos gibleus, todo o Líbano, para o leste, desde Baal-Gade, ao pé do monte Hermom, até Lebo-Hamate.

[[v6-13-6]]

^<<v6-13-6,6>>^ "Todos os habitantes das montanhas, desde o Líbano até Misrefote-Maim, isto é, todos os sidônios; eu mesmo os expulsarei da presença dos israelitas. Você, porém, distribuirá esta terra a Israel por herança, como lhe ordenei,

[[v6-13-7]]

^<<v6-13-7,7>>^ repartindo-a agora entre as nove tribos e a metade da tribo de Manassés".

[[v6-13-8]]

^<<v6-13-8,8>>^ Com a outra metade da tribo de Manassés, as tribos de Rúben e de Gade já haviam recebido a herança a leste do Jordão, conforme Moisés, servo do Senhor, lhes tinha designado.

[[v6-13-9]]

^<<v6-13-9,9>>^ Esse território se estendia de Aroer, na margem do ribeiro do Arnom, e da cidade situada no meio do vale desse ribeiro, e incluía todo o planalto de Medeba, até Dibom,

[[v6-13-10]]

^<<v6-13-10,10>>^ e todas as cidades de Seom, rei dos amorreus, que governava em Hesbom, e prosseguia até a fronteira dos amonitas.

[[v6-13-11]]

^<<v6-13-11,11>>^ Também incluía Gileade, o território dos gesuritas e maacatitas, toda a região do monte Hermom e toda a Basã, até Salcá,

[[v6-13-12]]

^<<v6-13-12,12>>^ isto é, todo o reino de Ogue, em Basã, que tinha reinado em Asterote e Edrei, um dos últimos refains sobreviventes. Moisés os tinha derrotado e tomado as suas terras.

[[v6-13-13]]

^<<v6-13-13,13>>^ Mas os israelitas não expulsaram os gesuritas e maacatitas, de modo que até hoje continuam a viver no meio deles.

[[v6-13-14]]

^<<v6-13-14,14>>^ Mas à tribo de Levi não deu herança alguma, visto que as ofertas preparadas no fogo ao Senhor, ao Deus de Israel, são a herança deles, como já lhes dissera.

[[v6-13-15]]

^<<v6-13-15,15>>^ À tribo de Rúben, clã por clã, Moisés dera o seguinte território:

[[v6-13-16]]

^<<v6-13-16,16>>^ Desde Aroer, na margem do ribeiro do Arnom, e desde a cidade situada no meio do vale desse ribeiro, e todo o planalto depois de Medeba,

[[v6-13-17]]

^<<v6-13-17,17>>^ até Hesbom e todas as suas cidades no planalto, inclusive Dibom, Bamote-Baal, Bete-Baal-Meom,

[[v6-13-18]]

^<<v6-13-18,18>>^ Jaza, Quedemote, Mefaate,

[[v6-13-19]]

^<<v6-13-19,19>>^ Quiriataim, Sibma, Zerete-Saar, na encosta do vale,

[[v6-13-20]]

^<<v6-13-20,20>>^ Bete-Peor, as encostas do Pisga, e Bete-Jesimote:

[[v6-13-21]]

^<<v6-13-21,21>>^ todas as cidades do planalto e todo o domínio de Seom, rei dos amorreus, que governava em Hesbom. Moisés o tinha derrotado, bem como aos líderes midianitas Evi, Requém, Zur, Hur e Reba, aliados de Seom, que viviam naquela terra.

[[v6-13-22]]

^<<v6-13-22,22>>^ Além dos que foram mortos na guerra, os israelitas mataram à espada Balaão, filho de Beor, que praticava adivinhação.

[[v6-13-23]]

^<<v6-13-23,23>>^ A fronteira da tribo de Rúben era a margem do Jordão. Essas cidades e os seus povoados foram a herança de Rúben, clã por clã.

[[v6-13-24]]

^<<v6-13-24,24>>^ À tribo de Gade, clã por clã, Moisés dera o seguinte território:

[[v6-13-25]]

^<<v6-13-25,25>>^ O território de Jazar, todas as cidades de Gileade e metade do território amonita até Aroer, perto de Rabá.

[[v6-13-26]]

^<<v6-13-26,26>>^ Estendia-se desde Hesbom até Ramate-Mispa e Betonim, e desde Maanaim até o território de Debir.

[[v6-13-27]]

^<<v6-13-27,27>>^ No vale do Jordão incluía Bete-Arã, Bete-Ninra, Sucote e Zafom; o restante do domínio de Seom, rei de Hesbom. Abrangia a margem leste do Jordão até o mar de Quinerete.

[[v6-13-28]]

^<<v6-13-28,28>>^ Essa região com suas cidades e povoados foram a herança de Gade, clã por clã.

[[v6-13-29]]

^<<v6-13-29,29>>^ À metade da tribo de Manassés, isto é, à metade dos descendentes de Manassés, clã por clã, Moisés dera o seguinte território:

[[v6-13-30]]

^<<v6-13-30,30>>^ O seu território se estendia desde Maanaim e incluía toda a região de Basã, todo o domínio de Ogue, rei de Basã: todos os povoados de Jair em Basã, sessenta cidades;

[[v6-13-31]]

^<<v6-13-31,31>>^ metade de Gileade, e Asterote e Edrei, cidades do reino de Ogue, em Basã. Esse foi o território destinado à metade dos descendentes de Maquir, filho de Manassés, clã por clã.

[[v6-13-32]]

^<<v6-13-32,32>>^ Essa foi a herança que Moisés lhes deu quando estava na planície de Moabe, do outro lado do Jordão, a leste de Jericó.

[[v6-13-33]]

^<<v6-13-33,33>>^ Mas à tribo de Levi, Moisés não deu herança alguma; o Senhor, o Deus de Israel, é a herança deles, como já lhes dissera.

'''

xref:006-josue/006-josue-012.adoc#v6-12-0[&#60; Capítulo Anterior] | <<v6-13-0,Topo>> | xref:006-josue/006-josue-014.adoc#v6-14-0[Próximo Capítulo &#62;]