include::./index.adoc[]

[[v6-7-0]]
=== Josué, 7
// nvi ?, NVI - Nova Versão Internacional

[[v6-7-1]]

^<<v6-7-1,1>>^ Mas os israelitas foram infiéis com relação às coisas consagradas. Acã, filho de Carmi, filho de Zinri, filho de Zerá, da tribo de Judá, apossou-se de algumas delas. E a ira do Senhor acendeu-se contra Israel.

[[v6-7-2]]

^<<v6-7-2,2>>^ Sucedeu que Josué enviou homens de Jericó a Ai, que fica perto de Bete-Áven, a leste de Betel, e ordenou-lhes: "Subam e espionem a região". Os homens subiram e espionaram Ai.

[[v6-7-3]]

^<<v6-7-3,3>>^ Quando voltaram a Josué, disseram: "Não é preciso que todos avancem contra Ai. Envie uns dois ou três mil homens para atacá-la. Não canse todo o exército, pois eles são poucos".

[[v6-7-4]]

^<<v6-7-4,4>>^ Por isso cerca de três mil homens atacaram a cidade; mas os homens de Ai os puseram em fuga,

[[v6-7-5]]

^<<v6-7-5,5>>^ chegando a matar trinta e seis deles. Eles perseguiram os israelitas desde a porta da cidade até Sebarim, e os feriram na descida. Diante disso o povo desanimou-se completamente.

[[v6-7-6]]

^<<v6-7-6,6>>^ Então Josué, com as autoridades de Israel, rasgou as vestes, prostrou-se, rosto em terra, diante da arca do Senhor, cobrindo de terra a cabeça, e ali permaneceu até à tarde.

[[v6-7-7]]

^<<v6-7-7,7>>^ Disse então Josué: "Ah, Soberano Senhor, por que fizeste este povo atravessar o Jordão? Foi para nos entregar nas mãos dos amorreus e nos destruir? Antes nos contentássemos em continuar no outro lado do Jordão!

[[v6-7-8]]

^<<v6-7-8,8>>^ Que poderei dizer, Senhor, agora que Israel foi derrotado por seus inimigos?

[[v6-7-9]]

^<<v6-7-9,9>>^ Os cananeus e os demais habitantes desta terra saberão disso, nos cercarão e eliminarão o nosso nome da terra. Que farás, então, pelo teu grande nome? "

[[v6-7-10]]

^<<v6-7-10,10>>^ O Senhor disse a Josué: "Levante-se! Por que você está aí prostrado?

[[v6-7-11]]

^<<v6-7-11,11>>^ Israel pecou. Violaram a aliança que eu lhes ordenei. Eles se apossaram de coisas consagradas, roubaram-nas, esconderam-nas, e as colocaram junto de seus bens.

[[v6-7-12]]

^<<v6-7-12,12>>^ Por isso os israelitas não conseguem resistir aos inimigos; fogem deles porque se tornaram merecedores da sua destruição. Não estarei mais com vocês, se não destruírem do meio de vocês o que foi consagrado à destruição.

[[v6-7-13]]

^<<v6-7-13,13>>^ "Vá, santifique o povo! Diga-lhes: Santifiquem-se para amanhã, pois assim diz o Senhor, o Deus de Israel: Há coisas consagradas à destruição no meio de vocês, ó Israel. Vocês não conseguirão resistir aos seus inimigos enquanto não as retirarem.

[[v6-7-14]]

^<<v6-7-14,14>>^ "Apresentem-se de manhã, uma tribo de cada vez. A tribo que o Senhor escolher virá à frente, um clã de cada vez; o clã que o Senhor escolher virá à frente, uma família de cada vez; e a família que o Senhor escolher virá à frente, um homem de cada vez.

[[v6-7-15]]

^<<v6-7-15,15>>^ Aquele que for pego com as coisas consagradas será queimado no fogo com tudo o que lhe pertence. Violou a aliança do Senhor e cometeu loucura em Israel! "

[[v6-7-16]]

^<<v6-7-16,16>>^ Na manhã seguinte Josué mandou os israelitas virem à frente segundo as suas tribos, e a de Judá foi a escolhida.

[[v6-7-17]]

^<<v6-7-17,17>>^ Os clãs de Judá vieram à frente, e ele escolheu os zeraítas. Fez o clã dos zeraítas vir à frente, família por família, e o escolhido foi Zinri.

[[v6-7-18]]

^<<v6-7-18,18>>^ Josué fez a família de Zinri vir à frente, homem por homem, e Acã, filho de Carmi, filho de Zinri, filho de Zerá, da tribo de Judá, foi o escolhido.

[[v6-7-19]]

^<<v6-7-19,19>>^ Então Josué disse a Acã: "Meu filho, para a glória do Senhor, o Deus de Israel, diga a verdade. Conte-me o que você fez; não me esconda nada".

[[v6-7-20]]

^<<v6-7-20,20>>^ Acã respondeu: "É verdade que pequei contra o Senhor, contra o Deus de Israel. O que fiz foi o seguinte:

[[v6-7-21]]

^<<v6-7-21,21>>^ quando vi entre os despojos uma bela capa feita na Babilônia, dois quilos e quatrocentos gramas de prata e uma barra de ouro de seiscentos gramas, eu os cobicei e me apossei deles. Estão escondidos no chão da minha tenda, com a prata por baixo".

[[v6-7-22]]

^<<v6-7-22,22>>^ Josué enviou alguns homens que correram à tenda de Acã; lá estavam escondidas as coisas, com a prata por baixo.

[[v6-7-23]]

^<<v6-7-23,23>>^ Retiraram-nas da tenda e as levaram a Josué e a todos os israelitas, e as puseram perante o Senhor.

[[v6-7-24]]

^<<v6-7-24,24>>^ Então Josué, junto com todo o Israel, levou Acã, bisneto de Zerá, e a prata, a capa, a barra de ouro, seus filhos e filhas, seus bois, seus jumentos, suas ovelhas, sua tenda e tudo o que lhe pertencia, ao vale de Acor.

[[v6-7-25]]

^<<v6-7-25,25>>^ Disse Josué: "Por que você nos causou esta desgraça? Hoje o Senhor lhe causará desgraça". E todo o Israel o apedrejou, e depois apedrejou também os seus, e os queimou no fogo.

[[v6-7-26]]

^<<v6-7-26,26>>^ Sobre Acã ergueram um grande monte de pedras, que existe até hoje. Então o Senhor se afastou do fogo da sua ira. Por isso foi dado àquele lugar o nome de vale de Acor, nome que permanece até hoje.

'''

xref:006-josue/006-josue-006.adoc#v6-6-0[&#60; Capítulo Anterior] | <<v6-7-0,Topo>> | xref:006-josue/006-josue-008.adoc#v6-8-0[Próximo Capítulo &#62;]