include::./index.adoc[]

[[v6-14-0]]
=== Josué, 14
// nvi ?, NVI - Nova Versão Internacional

[[v6-14-1]]

^<<v6-14-1,1>>^ Foram estas as terras que os israelitas receberam por herança em Canaã, e que o sacerdote Eleazar, Josué, filho de Num, e os chefes dos clãs das tribos dos israelitas repartiram entre eles.

[[v6-14-2]]

^<<v6-14-2,2>>^ A divisão da herança foi decidida por sorteio entre as nove tribos e meia, como o Senhor tinha ordenado por meio de Moisés,

[[v6-14-3]]

^<<v6-14-3,3>>^ pois Moisés já tinha dado herança às duas tribos e meia a leste do Jordão. Mas aos levitas não dera herança entre os demais.

[[v6-14-4]]

^<<v6-14-4,4>>^ Os filhos de José formaram as duas tribos de Manassés e Efraim. Os levitas não receberam porção alguma da terra; receberam apenas cidades onde viver, com pastagens para os seus rebanhos.

[[v6-14-5]]

^<<v6-14-5,5>>^ Os israelitas dividiram a terra conforme o Senhor tinha ordenado a Moisés.

[[v6-14-6]]

^<<v6-14-6,6>>^ Os homens de Judá vieram a Josué em Gilgal, e Calebe, filho do quenezeu Jefoné, lhe disse: "Você sabe o que o Senhor disse a Moisés, homem de Deus, em Cades-Barnéia, sobre mim e sobre você.

[[v6-14-7]]

^<<v6-14-7,7>>^ Eu tinha quarenta anos quando Moisés, servo do Senhor, enviou-me de Cades-Barnéia para espionar a terra. Eu lhe dei um relatório digno de confiança,

[[v6-14-8]]

^<<v6-14-8,8>>^ mas os meus irmãos israelitas que foram comigo fizeram o povo desanimar-se de medo. Eu, porém, fui inteiramente fiel ao Senhor, ao meu Deus.

[[v6-14-9]]

^<<v6-14-9,9>>^ Por isso naquele dia Moisés me jurou: ‘Certamente a terra em que você pisou será uma herança perpétua para você e para os seus descendentes, porquanto você foi inteiramente fiel ao Senhor, ao meu Deus’.

[[v6-14-10]]

^<<v6-14-10,10>>^ "Pois bem, o Senhor manteve-me vivo, como prometeu. E foi há quarenta e cinco anos que ele disse isso a Moisés, quando Israel caminhava pelo deserto. Por isso aqui estou hoje, com oitenta e cinco anos de idade!

[[v6-14-11]]

^<<v6-14-11,11>>^ Ainda estou tão forte como no dia em que Moisés me enviou; tenho agora tanto vigor para ir à guerra como naquela época.

[[v6-14-12]]

^<<v6-14-12,12>>^ Dê-me, pois, a região montanhosa que naquela ocasião o Senhor me prometeu. Na época, você ficou sabendo que os enaquins lá viviam com suas cidades grandes e fortificadas; mas, se o Senhor estiver comigo, eu os expulsarei de lá, como ele prometeu".

[[v6-14-13]]

^<<v6-14-13,13>>^ Então Josué abençoou Calebe, filho de Jefoné, e lhe deu Hebrom por herança.

[[v6-14-14]]

^<<v6-14-14,14>>^ Por isso, até hoje, Hebrom pertence aos descendentes de Calebe, filho do quenezeu Jefoné, pois ele foi inteiramente fiel ao Senhor, ao Deus de Israel.

[[v6-14-15]]

^<<v6-14-15,15>>^ Hebrom era chamada Quiriate-Arba, em homenagem a Arba, o maior dos enaquins. E a terra teve descanso da guerra.

'''

xref:006-josue/006-josue-013.adoc#v6-13-0[&#60; Capítulo Anterior] | <<v6-14-0,Topo>> | xref:006-josue/006-josue-015.adoc#v6-15-0[Próximo Capítulo &#62;]