include::./index.adoc[]

[[v6-24-0]]
=== Josué, 24
// nvi ?, NVI - Nova Versão Internacional

[[v6-24-1]]

^<<v6-24-1,1>>^ Então Josué reuniu todas as tribos de Israel em Siquém. Convocou as autoridades, os líderes, os juízes e os oficiais de Israel, e eles compareceram diante de Deus.

[[v6-24-2]]

^<<v6-24-2,2>>^ Josué disse a todo o povo: "Assim diz o Senhor, o Deus de Israel: ‘Há muito tempo, os seus antepassados, inclusive Terá, pai de Abraão e de Naor, viviam além do Eufrates e prestavam culto a outros deuses.

[[v6-24-3]]

^<<v6-24-3,3>>^ Mas eu tirei seu pai Abraão da terra dalém do Eufrates e o conduzi por toda a Canaã e lhe dei muitos descendentes. Dei-lhe Isaque,

[[v6-24-4]]

^<<v6-24-4,4>>^ e a Isaque dei Jacó e Esaú. A Esaú dei os montes de Seir, mas Jacó e seus filhos desceram para o Egito.

[[v6-24-5]]

^<<v6-24-5,5>>^ " ‘Então enviei Moisés e Arão e feri os egípcios com pragas, com as quais os castiguei, e depois tirei vocês de lá.

[[v6-24-6]]

^<<v6-24-6,6>>^ Quando tirei os seus antepassados do Egito, vocês vieram para o mar, e os egípcios os perseguiram com carros de guerra e cavaleiros até o mar Vermelho.

[[v6-24-7]]

^<<v6-24-7,7>>^ Mas os seus antepassados clamaram a mim, e eu coloquei trevas entre vocês e os egípcios; fiz voltar o mar sobre eles e os encobrir. Vocês viram com os seus próprios olhos o que eu fiz com os egípcios. Depois disso vocês viveram no deserto longo tempo.

[[v6-24-8]]

^<<v6-24-8,8>>^ " ‘Eu os trouxe para a terra dos amorreus que viviam a leste do Jordão. Eles lutaram contra vocês, mas eu os entreguei nas suas mãos. Eu os destruí diante de vocês, e vocês se apossaram da terra deles.

[[v6-24-9]]

^<<v6-24-9,9>>^ Quando Balaque, rei de Moabe, filho de Zipor, se preparava para lutar contra Israel, mandou buscar Balaão, filho de Beor, para lançar maldição sobre vocês.

[[v6-24-10]]

^<<v6-24-10,10>>^ Mas eu não quis ouvir Balaão, de modo que ele os abençoou vez após vez, e eu os livrei das mãos dele.

[[v6-24-11]]

^<<v6-24-11,11>>^ " ‘Depois vocês atravessaram o Jordão e chegaram a Jericó. Os chefes de Jericó lutaram contra vocês, assim como os amorreus, os ferezeus, os cananeus, os hititas, os girgaseus, os heveus e os jebuseus, mas eu os entreguei nas mãos de vocês.

[[v6-24-12]]

^<<v6-24-12,12>>^ Eu lhes causei pânico para expulsá-los de diante de vocês, como fiz aos dois reis amorreus. Não foi a espada e o arco que lhes deram a vitória.

[[v6-24-13]]

^<<v6-24-13,13>>^ Foi assim que lhes dei uma terra que vocês não cultivaram e cidades que vocês não construíram. Nelas vocês moram, e comem de vinhas e olivais que não plantaram’.

[[v6-24-14]]

^<<v6-24-14,14>>^ "Agora temam o Senhor e sirvam-no com integridade e fidelidade. Joguem fora os deuses que os seus antepassados adoraram além do Eufrates e no Egito, e sirvam ao Senhor.

[[v6-24-15]]

^<<v6-24-15,15>>^ Se, porém, não lhes agrada servir ao Senhor, escolham hoje a quem irão servir, se aos deuses que os seus antepassados serviram além do Eufrates, ou aos deuses dos amorreus, em cuja terra vocês estão vivendo. Mas, eu e a minha família serviremos ao Senhor".

[[v6-24-16]]

^<<v6-24-16,16>>^ Então o povo respondeu: "Longe de nós abandonar o Senhor para servir outros deuses!

[[v6-24-17]]

^<<v6-24-17,17>>^ Foi o próprio Senhor, o nosso Deus, que nos tirou, a nós e a nossos pais, do Egito, daquela terra de escravidão, e realizou aquelas grandes maravilhas diante dos nossos olhos. Ele nos protegeu no caminho e entre as nações pelas quais passamos.

[[v6-24-18]]

^<<v6-24-18,18>>^ Além disso, o Senhor expulsou de diante de nós todas as nações, inclusive os amorreus, que viviam nesta terra. Nós também serviremos ao Senhor, porque ele é o nosso Deus".

[[v6-24-19]]

^<<v6-24-19,19>>^ Josué disse ao povo: "Vocês não têm condições de servir ao Senhor. Ele é Deus santo! É Deus zeloso! Ele não perdoará a rebelião e o pecado de vocês.

[[v6-24-20]]

^<<v6-24-20,20>>^ Se abandonarem o Senhor e servirem a deuses estrangeiros, ele se voltará contra vocês e os castigará. Mesmo depois de ter sido bondoso com vocês, ele os exterminará".

[[v6-24-21]]

^<<v6-24-21,21>>^ O povo, porém, respondeu a Josué: "De maneira nenhuma! Nós serviremos ao Senhor".

[[v6-24-22]]

^<<v6-24-22,22>>^ Disse então Josué: "Vocês são testemunhas contra vocês mesmos de que escolheram servir ao Senhor". "Somos", responderam eles.

[[v6-24-23]]

^<<v6-24-23,23>>^ Disse Josué: "Agora, então, joguem fora os deuses estrangeiros que estão com vocês e voltem-se de coração para o Senhor, o Deus de Israel".

[[v6-24-24]]

^<<v6-24-24,24>>^ E o povo disse a Josué: "Serviremos ao Senhor nosso Deus e lhe obedeceremos".

[[v6-24-25]]

^<<v6-24-25,25>>^ Naquele dia Josué firmou um acordo com o povo em Siquém, e lhe deu decretos e leis.

[[v6-24-26]]

^<<v6-24-26,26>>^ Josué registrou essas coisas no Livro da Lei de Deus. Depois ergueu uma grande pedra ali, sob a Grande Árvore, perto do santuário do Senhor.

[[v6-24-27]]

^<<v6-24-27,27>>^ Então disse ele a todo o povo: "Vejam esta pedra! Ela será uma testemunha contra nós, pois ouviu todas as palavras que o Senhor nos disse. Será uma testemunha contra vocês, caso sejam infiéis ao Deus de vocês".

[[v6-24-28]]

^<<v6-24-28,28>>^ Depois Josué despediu o povo, e cada um foi para a sua propriedade.

[[v6-24-29]]

^<<v6-24-29,29>>^ Passado algum tempo, Josué, filho de Num, servo do Senhor, morreu. Tinha cento e dez anos de idade.

[[v6-24-30]]

^<<v6-24-30,30>>^ E o sepultaram na terra que recebeu por herança, em Timnate-Sera, nos montes de Efraim, ao norte do monte Gaás.

[[v6-24-31]]

^<<v6-24-31,31>>^ Israel serviu ao Senhor durante toda a vida de Josué e dos líderes que sobreviveram depois dele e que sabiam de tudo o que o Senhor fizera em favor de Israel.

[[v6-24-32]]

^<<v6-24-32,32>>^ Os ossos de José, que os israelitas haviam trazido do Egito, foram enterrados em Siquém, no quinhão de terra que Jacó havia comprado dos filhos de Hamor, pai de Siquém, por cem peças de prata. Aquele terreno tornou-se herança dos descendentes de José.

[[v6-24-33]]

^<<v6-24-33,33>>^ Sucedeu também que Eleazar, filho de Arão, morreu e foi sepultado em Gibeá, que fora dada a seu filho Finéias, nos montes de Efraim.

'''

xref:006-josue/006-josue-023.adoc#v6-23-0[&#60; Capítulo Anterior] | <<v6-24-0,Topo>> | xref:007-juizes/007-juizes-001.adoc#v7-1-0[Próximo Capítulo &#62;]