include::./index.adoc[]

[[v6-17-0]]
=== Josué, 17
// nvi ?, NVI - Nova Versão Internacional

[[v6-17-1]]

^<<v6-17-1,1>>^ Estas foram as terras distribuídas à tribo de Manassés, filho mais velho de José. Foram entregues a Maquir, filho mais velho de Manassés. Maquir, pai de Gileade, guerreiro valente, recebeu Gileade e Basã.

[[v6-17-2]]

^<<v6-17-2,2>>^ Também foram dadas terras para os clãs dos outros filhos de Manassés: Abiezer, Heleque, Asriel, Siquém, Héfer e Semida. Esses são os filhos homens de Manassés, filho de José, de acordo com os seus clãs.

[[v6-17-3]]

^<<v6-17-3,3>>^ Zelofeade, porém, filho de Héfer, neto de Gileade, bisneto de Maquir, trineto de Manassés, não teve nenhum filho, mas somente filhas. Seus nomes eram Maalá, Noa, Hogla, Milca e Tirza.

[[v6-17-4]]

^<<v6-17-4,4>>^ Elas foram ao sacerdote Eleazar, a Josué, filho de Num, e aos líderes, e disseram: "O Senhor ordenou a Moisés que nos desse uma herança entre os nossos parentes". Josué deu-lhes então uma herança entre os irmãos de seu pai, de acordo com a ordem do Senhor.

[[v6-17-5]]

^<<v6-17-5,5>>^ A tribo de Manassés recebeu dez quinhões de terra, além de Gileade e Basã, que ficam a leste do Jordão,

[[v6-17-6]]

^<<v6-17-6,6>>^ pois tanto as descendentes de Manassés como os filhos dele receberam herança. A terra de Gileade ficou para os outros descendentes de Manassés.

[[v6-17-7]]

^<<v6-17-7,7>>^ O território de Manassés estendia-se desde Aser até Micmetá, a leste de Siquém. A fronteira ia dali para o sul, chegando até o povo que vivia em En-Tapua.

[[v6-17-8]]

^<<v6-17-8,8>>^ As terras de Tapua eram de Manassés, mas a cidade de Tapua, na fronteira de Manassés, pertencia aos efraimitas.

[[v6-17-9]]

^<<v6-17-9,9>>^ Depois a fronteira descia até o ribeiro de Caná. Ao sul do ribeiro havia cidades pertencentes a Efraim que ficavam em meio às cidades de Manassés, mas a fronteira de Manassés ficava ao norte do ribeiro e terminava no mar.

[[v6-17-10]]

^<<v6-17-10,10>>^ Do lado sul a terra pertencia a Efraim; do lado norte, a Manassés. O território de Manassés chegava até o mar e alcançava Aser, ao norte, e Issacar, a leste.

[[v6-17-11]]

^<<v6-17-11,11>>^ Em Issacar e Aser, Manassés tinha também Bete-Seã, Ibleã e as populações de Dor, En-Dor, Taanaque e Megido, com os seus respectivos povoados. A terceira da lista é Nafote.

[[v6-17-12]]

^<<v6-17-12,12>>^ Mas os manassitas não conseguiram expulsar os habitantes dessas cidades, pois os cananeus estavam decididos a viver naquela região.

[[v6-17-13]]

^<<v6-17-13,13>>^ Entretanto, quando os israelitas se fortaleceram, submeteram os cananeus a trabalhos forçados, mas não os expulsaram totalmente.

[[v6-17-14]]

^<<v6-17-14,14>>^ Os descendentes de José disseram então a Josué: "Por que nos deste apenas um quinhão, uma só porção de herança? Somos um povo numeroso, e o Senhor nos tem abençoado ricamente".

[[v6-17-15]]

^<<v6-17-15,15>>^ Respondeu Josué: "Se vocês são tão numerosos, e se os montes de Efraim têm pouco espaço para vocês, subam, entrem na floresta e limpem o terreno para vocês na terra dos ferezeus e dos refains".

[[v6-17-16]]

^<<v6-17-16,16>>^ Os descendentes de José responderam: "Os montes não são suficientes para nós; além disso todos os cananeus que vivem na planície possuem carros de ferro, tanto os que vivem em Bete-Seã e seus povoados como os que vivem no vale de Jezreel".

[[v6-17-17]]

^<<v6-17-17,17>>^ Josué, porém, disse à tribo de José, a Efraim e a Manassés: "Vocês são numerosos e poderosos. Vocês não terão apenas um quinhão.

[[v6-17-18]]

^<<v6-17-18,18>>^ Os montes cobertos de floresta serão de vocês. Limpem o terreno, e será de vocês, até os seus limites mais distantes. Embora os cananeus possuam carros de ferro e sejam fortes, vocês poderão expulsá-los".

'''

xref:006-josue/006-josue-016.adoc#v6-16-0[&#60; Capítulo Anterior] | <<v6-17-0,Topo>> | xref:006-josue/006-josue-018.adoc#v6-18-0[Próximo Capítulo &#62;]