include::./index.adoc[]

[[v6-2-0]]
=== Josué, 2
// nvi ?, NVI - Nova Versão Internacional

[[v6-2-1]]

^<<v6-2-1,1>>^ Então Josué, filho de Num, enviou secretamente de Sitim dois espiões e lhes disse: "Vão examinar a terra, especialmente Jericó". Eles foram e entraram na casa de uma prostituta chamada Raabe, e ali passaram a noite.

[[v6-2-2]]

^<<v6-2-2,2>>^ Todavia o rei de Jericó foi avisado: "Alguns israelitas vieram aqui esta noite para espionar a terra".

[[v6-2-3]]

^<<v6-2-3,3>>^ Diante disso, o rei de Jericó enviou esta mensagem a Raabe: "Mande embora os homens que entraram em sua casa, pois vieram espionar a terra toda".

[[v6-2-4]]

^<<v6-2-4,4>>^ Mas a mulher que tinha escondido os dois homens respondeu: "É verdade que os homens vieram a mim, mas eu não sabia de onde tinham vindo.

[[v6-2-5]]

^<<v6-2-5,5>>^ Ao anoitecer, na hora de fechar a porta da cidade, eles partiram. Não sei por onde foram. Corram atrás deles. Talvez os alcancem".

[[v6-2-6]]

^<<v6-2-6,6>>^ Ela, porém, os tinha levado para o terraço e os tinha escondido sob os talos de linho que havia arrumado lá.

[[v6-2-7]]

^<<v6-2-7,7>>^ Os perseguidores partiram atrás deles pelo caminho que vai para o lugar de passagem do Jordão. E logo que saíram, a porta foi trancada.

[[v6-2-8]]

^<<v6-2-8,8>>^ Antes dos espiões se deitarem, Raabe subiu ao terraço

[[v6-2-9]]

^<<v6-2-9,9>>^ e lhes disse: "Sei que o Senhor lhes deu esta terra. Vocês nos causaram um medo terrível, e todos os habitantes desta terra estão apavorados por causa de vocês.

[[v6-2-10]]

^<<v6-2-10,10>>^ Pois temos ouvido como o Senhor secou as águas do mar Vermelho perante vocês quando saíram do Egito, e o que vocês fizeram a leste do Jordão com Seom e Ogue, os dois reis amorreus que aniquilaram.

[[v6-2-11]]

^<<v6-2-11,11>>^ Quando soubemos disso, o povo desanimou-se completamente, e por causa de vocês todos perderam a coragem, pois o Senhor, o seu Deus, é Deus em cima nos céus e embaixo na terra.

[[v6-2-12]]

^<<v6-2-12,12>>^ Jurem-me pelo Senhor que, assim como eu fui bondosa com vocês, vocês também serão bondosos com a minha família. Dêem-me um sinal seguro

[[v6-2-13]]

^<<v6-2-13,13>>^ de que pouparão a vida de meu pai e de minha mãe, de meus irmãos e minhas irmãs, e de tudo o que lhes pertence. Livrem-nos da morte".

[[v6-2-14]]

^<<v6-2-14,14>>^ "As nossas vidas pelas de vocês! ", os homens lhe garantiram. "Se você não contar o que estamos fazendo, nós a trataremos com bondade e fidelidade quando o Senhor nos der a terra".

[[v6-2-15]]

^<<v6-2-15,15>>^ Então Raabe os ajudou a descer pela janela com uma corda, pois a casa em que morava fazia parte do muro da cidade,

[[v6-2-16]]

^<<v6-2-16,16>>^ e lhes disse: "Vão para aquela montanha, para que os perseguidores não os encontrem. Escondam-se lá por três dias, até que eles voltem; depois poderão seguir o seu caminho".

[[v6-2-17]]

^<<v6-2-17,17>>^ Os homens lhe disseram: "Estaremos livres do juramento que você nos levou a fazer

[[v6-2-18]]

^<<v6-2-18,18>>^ se, quando entrarmos na terra, você não tiver amarrado este cordão vermelho na janela pela qual nos ajudou a descer, e se não tiver trazido para a sua casa o seu pai e a sua mãe, os seus irmãos e toda a sua família.

[[v6-2-19]]

^<<v6-2-19,19>>^ Qualquer pessoa que sair da casa será responsável por sua própria morte; nós seremos inocentes. Mas, seremos responsáveis pela morte de quem estiver na casa com você, caso alguém toque nessa pessoa.

[[v6-2-20]]

^<<v6-2-20,20>>^ E se você contar o que estamos fazendo, estaremos livres do juramento que você nos levou a fazer".

[[v6-2-21]]

^<<v6-2-21,21>>^ "Seja como vocês disseram", respondeu Raabe. Assim ela os despediu, e eles partiram. Depois ela amarrou o cordão vermelho na janela.

[[v6-2-22]]

^<<v6-2-22,22>>^ Quando partiram, foram para a montanha e ali ficaram três dias, até que os seus perseguidores regressassem. Estes os procuraram ao longo de todo o caminho e não os acharam.

[[v6-2-23]]

^<<v6-2-23,23>>^ Por fim os dois homens voltaram; desceram a montanha, atravessaram o rio e chegaram a Josué, filho de Num, e lhe contaram tudo o que lhes havia acontecido.

[[v6-2-24]]

^<<v6-2-24,24>>^ E disseram a Josué: "Sem dúvida o Senhor entregou a terra toda em nossas mãos; todos estão apavorados por nossa causa".

'''

xref:006-josue/006-josue-001.adoc#v6-1-0[&#60; Capítulo Anterior] | <<v6-2-0,Topo>> | xref:006-josue/006-josue-003.adoc#v6-3-0[Próximo Capítulo &#62;]