include::./index.adoc[]

[[v6-3-0]]
=== Josué, 3
// nvi ?, NVI - Nova Versão Internacional

[[v6-3-1]]

^<<v6-3-1,1>>^ De manhã bem cedo Josué e todos os israelitas partiram de Sitim e foram para o Jordão, onde acamparam antes de atravessar o rio.

[[v6-3-2]]

^<<v6-3-2,2>>^ Três dias depois, os oficiais percorreram o acampamento,

[[v6-3-3]]

^<<v6-3-3,3>>^ e deram esta ordem ao povo: "Quando virem a arca da aliança do Senhor, o seu Deus, e os sacerdotes levitas carregando a arca, saiam das suas posições e sigam-na.

[[v6-3-4]]

^<<v6-3-4,4>>^ Mas mantenham a distância de cerca de novecentos metros entre vocês e a arca; não se aproximem! Desse modo saberão que caminho seguir, pois vocês nunca passaram por lá".

[[v6-3-5]]

^<<v6-3-5,5>>^ Josué ordenou ao povo: "Santifiquem-se, pois amanhã o Senhor fará maravilhas entre vocês".

[[v6-3-6]]

^<<v6-3-6,6>>^ E disse aos sacerdotes: "Levantem a arca da aliança e passem à frente do povo". Eles a levantaram e foram na frente.

[[v6-3-7]]

^<<v6-3-7,7>>^ E o Senhor disse a Josué: "Hoje começarei a exaltá-lo à vista de todo o Israel, para que saibam que estarei com você como estive com Moisés.

[[v6-3-8]]

^<<v6-3-8,8>>^ Portanto, você é quem dará a seguinte ordem aos sacerdotes que carregam a arca da aliança: ‘Quando chegarem às margens das águas do Jordão, parem junto ao rio’ ".

[[v6-3-9]]

^<<v6-3-9,9>>^ Então Josué disse aos israelitas: "Venham ouvir as palavras do Senhor, o seu Deus.

[[v6-3-10]]

^<<v6-3-10,10>>^ Assim saberão que o Deus vivo está no meio de vocês e que certamente expulsará de diante de vocês os cananeus, os hititas, os heveus, os ferezeus, os girgaseus, os amorreus e os jebuseus.

[[v6-3-11]]

^<<v6-3-11,11>>^ Vejam, a arca da aliança do Soberano de toda a terra atravessará o Jordão à frente de vocês.

[[v6-3-12]]

^<<v6-3-12,12>>^ Agora, escolham doze israelitas, um de cada tribo.

[[v6-3-13]]

^<<v6-3-13,13>>^ Quando os sacerdotes que carregam a arca do Senhor, o Soberano de toda a terra, puserem os pés no Jordão, a correnteza será represada e as águas formarão uma muralha".

[[v6-3-14]]

^<<v6-3-14,14>>^ Quando, pois, o povo desmontou o acampamento para atravessar o Jordão, os sacerdotes que carregavam a arca da aliança foram adiante.

[[v6-3-15]]

^<<v6-3-15,15>>^ ( O Jordão transborda em ambas as margens na época da colheita. ) Assim que os sacerdotes que carregavam a arca da aliança chegaram ao Jordão e seus pés tocaram as águas,

[[v6-3-16]]

^<<v6-3-16,16>>^ a correnteza que descia parou de correr e formou uma muralha a grande distância, perto de uma cidade chamada Adã, nas proximidades de Zaretã; e as águas que desciam para o mar da Arabá, o mar Salgado, escoaram totalmente. E assim o povo atravessou o rio em frente de Jericó.

[[v6-3-17]]

^<<v6-3-17,17>>^ Os sacerdotes que carregavam a arca da aliança do Senhor ficaram parados em terra seca no meio do Jordão, enquanto todo o Israel passava, até que toda a nação o atravessou também em terra seca.

'''

xref:006-josue/006-josue-002.adoc#v6-2-0[&#60; Capítulo Anterior] | <<v6-3-0,Topo>> | xref:006-josue/006-josue-004.adoc#v6-4-0[Próximo Capítulo &#62;]