include::./index.adoc[]

[[v6-5-0]]
=== Josué, 5
// nvi ?, NVI - Nova Versão Internacional

[[v6-5-1]]

^<<v6-5-1,1>>^ Todos os reis amorreus que habitavam a oeste do Jordão e todos os reis cananeus que viviam ao longo do litoral souberam como o Senhor tinha secado o Jordão diante dos israelitas até que tivéssemos atravessado. Por isso, desanimaram-se e perderam a coragem de enfrentar os israelitas.

[[v6-5-2]]

^<<v6-5-2,2>>^ Naquela ocasião o Senhor disse a Josué: "Faça facas de pedra e circuncide os israelitas de novo".

[[v6-5-3]]

^<<v6-5-3,3>>^ Josué fez facas de pedra e circuncidou os israelitas em Gibeate-Aralote.

[[v6-5-4]]

^<<v6-5-4,4>>^ Ele fez isso porque todos os homens aptos para a guerra morreram no deserto depois de terem saído do Egito.

[[v6-5-5]]

^<<v6-5-5,5>>^ Todos os que saíram haviam sido circuncidados, mas todos os que nasceram no deserto, no caminho, depois da saída do Egito, não passaram pela circuncisão.

[[v6-5-6]]

^<<v6-5-6,6>>^ Os israelitas tinham andado quarenta anos pelo deserto, até que todos os guerreiros que saíram do Egito morressem, visto que não tinham obedecido ao Senhor. Pois o Senhor lhes havia jurado que não veriam a terra que prometera aos seus antepassados que nos daria, terra onde manam leite e mel.

[[v6-5-7]]

^<<v6-5-7,7>>^ Assim, em lugar deles colocou os seus filhos, e foram os filhos que Josué circuncidou. Ainda estavam incircuncisos porque não tinham sido circuncidados durante a viagem.

[[v6-5-8]]

^<<v6-5-8,8>>^ E, depois que a nação inteira foi circuncidada, eles ficaram onde estavam, no acampamento, até se recuperarem.

[[v6-5-9]]

^<<v6-5-9,9>>^ Então o Senhor disse a Josué: "Hoje removi de vocês a humilhação sofrida no Egito". Por isso até hoje o lugar se chama Gilgal.

[[v6-5-10]]

^<<v6-5-10,10>>^ Na tarde do décimo quarto dia do mês, enquanto estavam acampados em Gilgal, na planície de Jericó, os israelitas celebraram a Páscoa.

[[v6-5-11]]

^<<v6-5-11,11>>^ No dia seguinte ao da Páscoa, nesse mesmo dia, eles comeram pães sem fermento e grãos de trigo tostados, produtos daquela terra.

[[v6-5-12]]

^<<v6-5-12,12>>^ Um dia depois de comerem do produto da terra, o maná cessou. Já não havia maná para os israelitas, e naquele mesmo ano eles comeram do fruto da terra de Canaã.

[[v6-5-13]]

^<<v6-5-13,13>>^ Estando Josué já perto de Jericó, olhou para cima e viu um homem de pé, empunhando uma espada. Aproximou-se dele e perguntou-lhe: "Você é por nós, ou por nossos inimigos? "

[[v6-5-14]]

^<<v6-5-14,14>>^ "Nem uma coisa nem outra", respondeu ele. "Venho na qualidade de comandante do exército do Senhor". Então Josué prostrou-se, rosto em terra, em sinal de respeito, e lhe perguntou: "Que mensagem o meu senhor tem para o seu servo? "

[[v6-5-15]]

^<<v6-5-15,15>>^ O comandante do exército do Senhor respondeu: "Tire as sandálias dos pés, pois o lugar em que você está é santo". E Josué as tirou.

'''

xref:006-josue/006-josue-004.adoc#v6-4-0[&#60; Capítulo Anterior] | <<v6-5-0,Topo>> | xref:006-josue/006-josue-006.adoc#v6-6-0[Próximo Capítulo &#62;]