include::./index.adoc[]

[[v6-16-0]]
=== Josué, 16
// nvi ?, NVI - Nova Versão Internacional

[[v6-16-1]]

^<<v6-16-1,1>>^ As terras distribuídas aos descendentes de José iam desde o Jordão, perto de Jericó, a leste das águas de Jericó, e daí subiam pelo deserto até a serra que vai de Jericó a Betel.

[[v6-16-2]]

^<<v6-16-2,2>>^ De Betel, que é Luz, iam para o território dos arquitas, em Atarote,

[[v6-16-3]]

^<<v6-16-3,3>>^ desciam para o oeste, até o território dos jafletitas, chegando à região de Bete-Horom Baixa, e prosseguiam até Gezer, terminando no mar.

[[v6-16-4]]

^<<v6-16-4,4>>^ Assim os descendentes de Manassés e Efraim, filhos de José, receberam a sua herança.

[[v6-16-5]]

^<<v6-16-5,5>>^ Este era o território de Efraim, clã por clã: A fronteira da sua herança ia de Atarote-Adar, a leste, até Bete-Horom Alta,

[[v6-16-6]]

^<<v6-16-6,6>>^ e prosseguia até o mar. De Micmetá, ao norte, fazia uma curva para o leste, até Taanate-Siló, e, passando por ela, ia até Janoa, a leste.

[[v6-16-7]]

^<<v6-16-7,7>>^ Depois descia de Janoa para Atarote e Naarate, encostava em Jericó e terminava no Jordão.

[[v6-16-8]]

^<<v6-16-8,8>>^ De Tapua a fronteira seguia rumo oeste até o ribeiro de Caná e terminava no mar. Essa foi a herança da tribo dos efraimitas, clã por clã,

[[v6-16-9]]

^<<v6-16-9,9>>^ que incluía todas as cidades com os seus povoados, separadas para os efraimitas na herança dos manassitas.

[[v6-16-10]]

^<<v6-16-10,10>>^ Os cananeus de Gezer não foram expulsos, e até hoje vivem no meio do povo de Efraim, mas são sujeitos a trabalhos forçados.

'''

xref:006-josue/006-josue-015.adoc#v6-15-0[&#60; Capítulo Anterior] | <<v6-16-0,Topo>> | xref:006-josue/006-josue-017.adoc#v6-17-0[Próximo Capítulo &#62;]