include::./index.adoc[]

[[v50-4-0]]
=== Filipenses, 4
// nvi ?, NVI - Nova Versão Internacional

[[v50-4-1]]

^<<v50-4-1,1>>^ Portanto, meus irmãos, a quem amo e de quem tenho saudade, vocês que são a minha alegria e a minha coroa, permaneçam assim firmes no Senhor, ó amados!

[[v50-4-2]]

^<<v50-4-2,2>>^ O que eu rogo a Evódia e também a Síntique é que vivam em harmonia no Senhor.

[[v50-4-3]]

^<<v50-4-3,3>>^ Sim, e peço a você, leal companheiro de jugo, que as ajude; pois lutaram ao meu lado na causa do evangelho, com Clemente e meus demais cooperadores. Os seus nomes estão no livro da vida.

[[v50-4-4]]

^<<v50-4-4,4>>^ Alegrem-se sempre no Senhor. Novamente direi: alegrem-se!

[[v50-4-5]]

^<<v50-4-5,5>>^ Seja a amabilidade de vocês conhecida por todos. Perto está o Senhor.

[[v50-4-6]]

^<<v50-4-6,6>>^ Não andem ansiosos por coisa alguma, mas em tudo, pela oração e súplicas, e com ação de graças, apresentem seus pedidos a Deus.

[[v50-4-7]]

^<<v50-4-7,7>>^ E a paz de Deus, que excede todo o entendimento, guardará os seus corações e as suas mentes em Cristo Jesus.

[[v50-4-8]]

^<<v50-4-8,8>>^ Finalmente, irmãos, tudo o que for verdadeiro, tudo o que for nobre, tudo o que for correto, tudo o que for puro, tudo o que for amável, tudo o que for de boa fama, se houver algo de excelente ou digno de louvor, pensem nessas coisas.

[[v50-4-9]]

^<<v50-4-9,9>>^ Tudo o que vocês aprenderam, receberam, ouviram e viram em mim, ponham-no em prática. E o Deus da paz estará com vocês.

[[v50-4-10]]

^<<v50-4-10,10>>^ Alegro-me grandemente no Senhor, porque finalmente vocês renovaram o seu interesse por mim. De fato, vocês já se interessavam, mas não tinham oportunidade para demonstrá-lo.

[[v50-4-11]]

^<<v50-4-11,11>>^ Não estou dizendo isso porque esteja necessitado, pois aprendi a adaptar-me a toda e qualquer circunstância.

[[v50-4-12]]

^<<v50-4-12,12>>^ Sei o que é passar necessidade e sei o que é ter fartura. Aprendi o segredo de viver contente em toda e qualquer situação, seja bem alimentado, seja com fome, tendo muito, ou passando necessidade.

[[v50-4-13]]

^<<v50-4-13,13>>^ Tudo posso naquele que me fortalece.

[[v50-4-14]]

^<<v50-4-14,14>>^ Apesar disso, vocês fizeram bem em participar de minhas tribulações.

[[v50-4-15]]

^<<v50-4-15,15>>^ Como vocês sabem, filipenses, nos seus primeiros dias no evangelho, quando parti da Macedônia, nenhuma igreja partilhou comigo no que se refere a dar e receber, exceto vocês;

[[v50-4-16]]

^<<v50-4-16,16>>^ pois, estando eu em Tessalônica, vocês me mandaram ajuda, não apenas uma vez, mas duas, quando tive necessidade.

[[v50-4-17]]

^<<v50-4-17,17>>^ Não que eu esteja procurando ofertas, mas o que pode ser creditado na conta de vocês.

[[v50-4-18]]

^<<v50-4-18,18>>^ Recebi tudo, e o que tenho é mais que suficiente. Estou amplamente suprido, agora que recebi de Epafrodito os donativos que vocês enviaram. Elas são uma oferta de aroma suave, um sacrifício aceitável e agradável a Deus.

[[v50-4-19]]

^<<v50-4-19,19>>^ O meu Deus suprirá todas as necessidades de vocês, de acordo com as suas gloriosas riquezas em Cristo Jesus.

[[v50-4-20]]

^<<v50-4-20,20>>^ A nosso Deus e Pai seja a glória para todo o sempre. Amém.

[[v50-4-21]]

^<<v50-4-21,21>>^ Saúdem a todos os santos em Cristo Jesus. Os irmãos que estão comigo enviam saudações.

[[v50-4-22]]

^<<v50-4-22,22>>^ Todos os santos lhes enviam saudações, especialmente os que estão no palácio de César.

[[v50-4-23]]

^<<v50-4-23,23>>^ A graça do Senhor Jesus Cristo seja com o espírito de vocês. Amém.

'''

xref:050-filipenses/050-filipenses-003.adoc#v50-3-0[&#60; Capítulo Anterior] | <<v50-4-0,Topo>> | xref:051-colossenses/051-colossenses-001.adoc#v51-1-0[Próximo Capítulo &#62;]