include::./index.adoc[]

[[v50-2-0]]
=== Filipenses, 2
// nvi ?, NVI - Nova Versão Internacional

[[v50-2-1]]

^<<v50-2-1,1>>^ Se por estarmos em Cristo, nós temos alguma motivação, alguma exortação de amor, alguma comunhão no Espírito, alguma profunda afeição e compaixão,

[[v50-2-2]]

^<<v50-2-2,2>>^ completem a minha alegria, tendo o mesmo modo de pensar, o mesmo amor, um só espírito e uma só atitude.

[[v50-2-3]]

^<<v50-2-3,3>>^ Nada façam por ambição egoísta ou por vaidade, mas humildemente considerem os outros superiores a si mesmos.

[[v50-2-4]]

^<<v50-2-4,4>>^ Cada um cuide, não somente dos seus interesses, mas também dos interesses dos outros.

[[v50-2-5]]

^<<v50-2-5,5>>^ Seja a atitude de vocês a mesma de Cristo Jesus,

[[v50-2-6]]

^<<v50-2-6,6>>^ que, embora sendo Deus, não considerou que o ser igual a Deus era algo a que devia apegar-se;

[[v50-2-7]]

^<<v50-2-7,7>>^ mas esvaziou-se a si mesmo, vindo a ser servo, tornando-se semelhante aos homens.

[[v50-2-8]]

^<<v50-2-8,8>>^ E, sendo encontrado em forma humana, humilhou-se a si mesmo e foi obediente até à morte, e morte de cruz!

[[v50-2-9]]

^<<v50-2-9,9>>^ Por isso Deus o exaltou à mais alta posição e lhe deu o nome que está acima de todo nome,

[[v50-2-10]]

^<<v50-2-10,10>>^ para que ao nome de Jesus se dobre todo joelho, no céu, na terra e debaixo da terra,

[[v50-2-11]]

^<<v50-2-11,11>>^ e toda língua confesse que Jesus Cristo é o Senhor, para a glória de Deus Pai.

[[v50-2-12]]

^<<v50-2-12,12>>^ Assim, meus amados, como sempre vocês obedeceram, não apenas em minha presença, porém muito mais agora na minha ausência, ponham em ação a salvação de vocês com temor e tremor,

[[v50-2-13]]

^<<v50-2-13,13>>^ pois é Deus quem efetua em vocês tanto o querer quanto o realizar, de acordo com a boa vontade dele.

[[v50-2-14]]

^<<v50-2-14,14>>^ Façam tudo sem queixas nem discussões,

[[v50-2-15]]

^<<v50-2-15,15>>^ para que venham a tornar-se puros e irrepreensíveis, filhos de Deus inculpáveis no meio de uma geração corrompida e depravada, na qual vocês brilham como estrelas no universo,

[[v50-2-16]]

^<<v50-2-16,16>>^ retendo firmemente a palavra da vida. Assim, no dia de Cristo eu me orgulharei de não ter corrido nem me esforçado inutilmente.

[[v50-2-17]]

^<<v50-2-17,17>>^ Contudo, mesmo que eu esteja sendo derramado como oferta de bebida sobre o serviço que provém da fé que vocês têm, o sacrifício que oferecem a Deus, estou alegre e me regozijo com todos vocês.

[[v50-2-18]]

^<<v50-2-18,18>>^ Estejam vocês também alegres, e regozijem-se comigo.

[[v50-2-19]]

^<<v50-2-19,19>>^ Espero no Senhor Jesus enviar-lhes Timóteo brevemente, para que eu também me sinta animado quando receber notícias de vocês.

[[v50-2-20]]

^<<v50-2-20,20>>^ Não tenho ninguém como ele, que tenha interesse sincero pelo bem-estar de vocês,

[[v50-2-21]]

^<<v50-2-21,21>>^ pois todos buscam os seus próprios interesses e não os de Jesus Cristo.

[[v50-2-22]]

^<<v50-2-22,22>>^ Mas vocês sabem que Timóteo foi aprovado, porque serviu comigo no trabalho do evangelho como um filho ao lado de seu pai.

[[v50-2-23]]

^<<v50-2-23,23>>^ Portanto, é ele quem espero enviar, tão logo me certifique da minha situação,

[[v50-2-24]]

^<<v50-2-24,24>>^ confiando no Senhor que em breve também poderei ir.

[[v50-2-25]]

^<<v50-2-25,25>>^ Contudo, penso que será necessário enviar-lhes de volta Epafrodito, meu irmão, cooperador e companheiro de lutas, mensageiro que vocês enviaram para atender às minhas necessidades.

[[v50-2-26]]

^<<v50-2-26,26>>^ Pois ele tem saudade de todos vocês e está angustiado porque ficaram sabendo que ele esteve doente.

[[v50-2-27]]

^<<v50-2-27,27>>^ De fato, ficou doente e quase morreu. Mas Deus teve misericórdia dele, e não somente dele, mas também de mim, para que eu não tivesse tristeza sobre tristeza.

[[v50-2-28]]

^<<v50-2-28,28>>^ Por isso, logo o enviarei, para que, quando o virem novamente, fiquem alegres e eu tenha menos tristeza.

[[v50-2-29]]

^<<v50-2-29,29>>^ E peço que vocês o recebam no Senhor com grande alegria e honrem a homens como este,

[[v50-2-30]]

^<<v50-2-30,30>>^ porque ele quase morreu por amor à causa de Cristo, arriscando a vida para suprir a ajuda que vocês não me podiam dar.

'''

xref:050-filipenses/050-filipenses-001.adoc#v50-1-0[&#60; Capítulo Anterior] | <<v50-2-0,Topo>> | xref:050-filipenses/050-filipenses-003.adoc#v50-3-0[Próximo Capítulo &#62;]