include::./index.adoc[]

[[v50-3-0]]
=== Filipenses, 3
// nvi ?, NVI - Nova Versão Internacional

[[v50-3-1]]

^<<v50-3-1,1>>^ Finalmente, meus irmãos, alegrem-se no Senhor! Escrever-lhes de novo as mesmas coisas não é cansativo para mim e é uma segurança para vocês.

[[v50-3-2]]

^<<v50-3-2,2>>^ Cuidado com os cães, cuidado com esses que praticam o mal, cuidado com a falsa circuncisão!

[[v50-3-3]]

^<<v50-3-3,3>>^ Pois nós é que somos a circuncisão, nós que adoramos pelo Espírito de Deus, que nos gloriamos em Cristo Jesus e não temos confiança alguma na carne,

[[v50-3-4]]

^<<v50-3-4,4>>^ embora eu mesmo tivesse razões para ter tal confiança. Se alguém pensa que tem razões para confiar na carne, eu ainda mais:

[[v50-3-5]]

^<<v50-3-5,5>>^ circuncidado no oitavo dia de vida, pertencente ao povo de Israel, à tribo de Benjamim, verdadeiro hebreu; quanto à lei, fariseu;

[[v50-3-6]]

^<<v50-3-6,6>>^ quanto ao zelo, perseguidor da igreja; quanto à justiça que há na lei, irrepreensível.

[[v50-3-7]]

^<<v50-3-7,7>>^ Mas o que para mim era lucro, passei a considerar perda, por causa de Cristo.

[[v50-3-8]]

^<<v50-3-8,8>>^ Mais do que isso, considero tudo como perda, comparado com a suprema grandeza do conhecimento de Cristo Jesus, meu Senhor, por cuja causa perdi todas as coisas. Eu as considero como esterco para poder ganhar a Cristo

[[v50-3-9]]

^<<v50-3-9,9>>^ e ser encontrado nele, não tendo a minha própria justiça que procede da lei, mas a que vem mediante a fé em Cristo, a justiça que procede de Deus e se baseia na fé.

[[v50-3-10]]

^<<v50-3-10,10>>^ Quero conhecer a Cristo, ao poder da sua ressurreição e à participação em seus sofrimentos, tornando-me como ele em sua morte

[[v50-3-11]]

^<<v50-3-11,11>>^ para, de alguma forma, alcançar a ressurreição dentre os mortos.

[[v50-3-12]]

^<<v50-3-12,12>>^ Não que eu já tenha obtido tudo isso ou tenha sido aperfeiçoado, mas prossigo para alcançá-lo, pois para isso também fui alcançado por Cristo Jesus.

[[v50-3-13]]

^<<v50-3-13,13>>^ Irmãos, não penso que eu mesmo já o tenha alcançado, mas uma coisa faço: esquecendo-me das coisas que ficaram para trás e avançando para as que estão adiante,

[[v50-3-14]]

^<<v50-3-14,14>>^ prossigo para o alvo, a fim de ganhar o prêmio do chamado celestial de Deus em Cristo Jesus.

[[v50-3-15]]

^<<v50-3-15,15>>^ Todos nós que alcançamos a maturidade devemos ver as coisas dessa forma, e se em algum aspecto vocês pensam de modo diferente, isso também Deus lhes esclarecerá.

[[v50-3-16]]

^<<v50-3-16,16>>^ Tão-somente vivamos de acordo com o que já alcançamos.

[[v50-3-17]]

^<<v50-3-17,17>>^ Irmãos, sigam unidos o meu exemplo e observem os que vivem de acordo com o padrão que lhes apresentamos.

[[v50-3-18]]

^<<v50-3-18,18>>^ Pois, como já lhes disse repetidas vezes, e agora repito com lágrimas, há muitos que vivem como inimigos da cruz de Cristo.

[[v50-3-19]]

^<<v50-3-19,19>>^ Quanto a estes, o seu destino é a perdição, o seu deus é o estômago e têm orgulho do que é vergonhoso; eles só pensam nas coisas terrenas.

[[v50-3-20]]

^<<v50-3-20,20>>^ A nossa cidadania, porém, está nos céus, de onde esperamos ansiosamente um Salvador, o Senhor Jesus Cristo.

[[v50-3-21]]

^<<v50-3-21,21>>^ Pelo poder que o capacita a colocar todas as coisas debaixo do seu domínio, ele transformará os nossos corpos humilhados, para serem semelhantes ao seu corpo glorioso.

'''

xref:050-filipenses/050-filipenses-002.adoc#v50-2-0[&#60; Capítulo Anterior] | <<v50-3-0,Topo>> | xref:050-filipenses/050-filipenses-004.adoc#v50-4-0[Próximo Capítulo &#62;]