include::./index.adoc[]

[[v31-1-0]]
=== Obadias, 1
// nvi ?, NVI - Nova Versão Internacional

[[v31-1-1]]

^<<v31-1-1,1>>^ Visão de Obadias. Assim diz o Soberano, o SENHOR, a respeito de Edom: Nós ouvimos uma mensagem do SENHOR. Um mensageiro foi enviado às nações para dizer: "Levantem-se! Vamos atacar Edom! "

[[v31-1-2]]

^<<v31-1-2,2>>^ "Veja! Eu tornarei você pequeno entre as nações. Será completamente desprezado!

[[v31-1-3]]

^<<v31-1-3,3>>^ A arrogância do seu coração o tem enganado, você que vive nas cavidades das rochas e constrói sua morada no alto dos montes; você que diz a si mesmo: ‘Quem pode me derrubar? ’

[[v31-1-4]]

^<<v31-1-4,4>>^ Ainda que você suba tão alto como a águia e faça o seu ninho entre as estrelas, dali eu o derrubarei", declara o SENHOR.

[[v31-1-5]]

^<<v31-1-5,5>>^ "Se ladrões o atacassem, saqueadores no meio da noite — como você está destruído! — não roubariam apenas quanto achassem suficiente? Se os que colhem uvas chegassem a você, não deixariam para trás pelo menos alguns cachos?

[[v31-1-6]]

^<<v31-1-6,6>>^ Entretanto, como Esaú foi saqueado! Como foram pilhados os seus tesouros ocultos!

[[v31-1-7]]

^<<v31-1-7,7>>^ Empurram você para as fronteiras todos os seus aliados; enganam você e o sobrepujarão os seus melhores amigos; aqueles que comem com você lhe armam ciladas". E Esaú não percebe nada!

[[v31-1-8]]

^<<v31-1-8,8>>^ "Naquele dia", declara o SENHOR, "destruirei os sábios de Edom, e os mestres dos montes de Esaú.

[[v31-1-9]]

^<<v31-1-9,9>>^ Então os seus guerreiros, ó Temã, ficarão apavorados, e serão eliminados todos os homens dos montes de Esaú.

[[v31-1-10]]

^<<v31-1-10,10>>^ Por causa da violenta matança que você fez contra o seu irmão Jacó, você será coberto de vergonha e eliminado para sempre.

[[v31-1-11]]

^<<v31-1-11,11>>^ No dia em que você ficou por perto, quando estrangeiros roubaram os bens dele, e estranhos entraram por suas portas e lançaram sortes sobre Jerusalém, você fez exatamente como eles.

[[v31-1-12]]

^<<v31-1-12,12>>^ Você não devia ter olhado com satisfação o dia da desgraça de seu irmão; nem ter se alegrado com a destruição do povo de Judá; não devia ter falado com arrogância no dia da sua aflição.

[[v31-1-13]]

^<<v31-1-13,13>>^ Não devia ter entrado pelas portas do meu povo no dia da sua calamidade; nem devia ter ficado alegre com o sofrimento dele no dia da sua ruína; nem ter roubado a riqueza dele no dia da sua desgraça.

[[v31-1-14]]

^<<v31-1-14,14>>^ Não devia ter esperado nas encruzilhadas, para matar os que conseguiram escapar; nem ter entregado os sobreviventes no dia da sua aflição.

[[v31-1-15]]

^<<v31-1-15,15>>^ "Pois o dia do SENHOR está próximo para todas as nações. Como você fez, assim lhe será feito. A maldade que você praticou recairá sobre você.

[[v31-1-16]]

^<<v31-1-16,16>>^ Assim como vocês beberam do meu castigo no meu santo monte, também todas as nações beberão sem parar. Beberão até o fim, e serão como se nunca tivessem existido.

[[v31-1-17]]

^<<v31-1-17,17>>^ Mas no monte Sião estarão os que escaparam; ele será santo e a descendência de Jacó possuirá a sua herança.

[[v31-1-18]]

^<<v31-1-18,18>>^ A descendência de Jacó será um fogo, e a de José uma chama; a descendência de Esaú será a palha. Eles a incendiarão e a consumirão. Não haverá sobreviventes da descendência de Esaú", declara o SENHOR.

[[v31-1-19]]

^<<v31-1-19,19>>^ Os do Neguebe se apossarão dos montes de Esaú, e os da Sefelá ocuparão a terra dos filisteus. Eles tomarão posse dos campos de Efraim e de Samaria, e Benjamim se apossará de Gileade.

[[v31-1-20]]

^<<v31-1-20,20>>^ Os israelitas exilados se apossarão do território dos cananeus até Sarepta; os exilados de Jerusalém que estão em Sefarade ocuparão as cidades do Neguebe.

[[v31-1-21]]

^<<v31-1-21,21>>^ Os vencedores subirão ao monte Sião para governar a montanha de Esaú. E o reino será do SENHOR.

'''

xref:030-amos/030-amos-009.adoc#v30-9-0[&#60; Capítulo Anterior] | <<v31-1-0,Topo>> | xref:032-jonas/032-jonas-001.adoc#v32-1-0[Próximo Capítulo &#62;]