include::./index.adoc[]

[[v64-1-0]]
=== 3 João, 1
// nvi ?, NVI - Nova Versão Internacional

[[v64-1-1]]

^<<v64-1-1,1>>^ O presbítero ao amado Gaio, a quem amo na verdade.

[[v64-1-2]]

^<<v64-1-2,2>>^ Amado, oro para que você tenha boa saúde e tudo lhe corra bem, assim como vai bem a sua alma.

[[v64-1-3]]

^<<v64-1-3,3>>^ Muito me alegrei ao receber a visita de alguns irmãos que falaram a respeito da sua fidelidade, de como você continua andando na verdade.

[[v64-1-4]]

^<<v64-1-4,4>>^ Não tenho alegria maior do que ouvir que meus filhos estão andando na verdade.

[[v64-1-5]]

^<<v64-1-5,5>>^ Amado, você é fiel no que está fazendo pelos irmãos, apesar de lhe serem desconhecidos.

[[v64-1-6]]

^<<v64-1-6,6>>^ Eles falaram à igreja a respeito deste seu amor. Você fará bem se os encaminhar em sua viagem de modo agradável a Deus,

[[v64-1-7]]

^<<v64-1-7,7>>^ pois foi por causa do Nome que eles saíram, sem receber ajuda alguma dos gentios.

[[v64-1-8]]

^<<v64-1-8,8>>^ É, pois, nosso dever receber com hospitalidade a irmãos como esses, para que nos tornemos cooperadores em favor da verdade.

[[v64-1-9]]

^<<v64-1-9,9>>^ Escrevi à igreja, mas Diótrefes, que gosta muito de ser o mais importante entre eles, não nos recebe.

[[v64-1-10]]

^<<v64-1-10,10>>^ Portanto, se eu for, chamarei a atenção dele para o que está fazendo com suas palavras maldosas contra nós. Não satisfeito com isso, ele se recusa a receber os irmãos, impede os que desejam recebê-los e os expulsa da igreja.

[[v64-1-11]]

^<<v64-1-11,11>>^ Amado, não imite o que é mau, mas sim o que é bom. Aquele que faz o bem é de Deus; aquele que faz o mal não viu a Deus.

[[v64-1-12]]

^<<v64-1-12,12>>^ Quanto a Demétrio, todos dão bom testemunho dele, inclusive a própria verdade. Nós também damos, e você sabe que o nosso testemunho é verdadeiro.

[[v64-1-13]]

^<<v64-1-13,13>>^ Tenho muito que lhe escrever, mas não desejo fazê-lo com pena e tinta.

[[v64-1-14]]

^<<v64-1-14,14>>^ Espero vê-lo em breve, e então conversaremos face a face.

[[v64-1-15]]

^<<v64-1-15,15>>^ A paz seja com você. Os amigos daqui lhe enviam saudações. Saúde os amigos daí, um por um.

'''

xref:063-2-joao/063-2-joao-001.adoc#v63-1-0[&#60; Capítulo Anterior] | <<v64-1-0,Topo>> | xref:065-judas/065-judas-001.adoc#v65-1-0[Próximo Capítulo &#62;]