include::./index.adoc[]

[[v26-31-0]]
=== Ezequiel, 31
// nvi ?, NVI - Nova Versão Internacional

[[v26-31-1]]

^<<v26-31-1,1>>^ No dia primeiro do terceiro mês do décimo primeiro ano, a palavra do Senhor veio a mim:

[[v26-31-2]]

^<<v26-31-2,2>>^ "Filho do homem, diga ao faraó, rei do Egito, e ao seu povo: " ‘Quem é comparável a você em majestade?

[[v26-31-3]]

^<<v26-31-3,3>>^ Considere a Assíria, outrora um cedro no Líbano, com belos galhos que faziam sombra à floresta; era alto; seu topo ficava acima da espessa folhagem.

[[v26-31-4]]

^<<v26-31-4,4>>^ As águas o nutriam, correntes profundas o faziam crescer a grande altura; seus riachos fluíam de onde ele estava para todas as árvores do campo.

[[v26-31-5]]

^<<v26-31-5,5>>^ Erguia-se mais alto que todas as árvores do campo; seus ramos cresceram e seus galhos ficaram maiores, espalhando-se, graças à fartura de água.

[[v26-31-6]]

^<<v26-31-6,6>>^ Todas as aves do céu se aninhavam em seus ramos, todos os animais do campo davam à luz debaixo dos seus galhos; todas as grandes nações viviam à sua sombra.

[[v26-31-7]]

^<<v26-31-7,7>>^ Era de uma beleza majestosa, com seus ramos que tanto se espalhavam, pois as suas raízes desciam até às muitas águas.

[[v26-31-8]]

^<<v26-31-8,8>>^ Os cedros do jardim de Deus não eram rivais para ele, nem os pinheiros conseguiam igualar-se aos seus ramos, nem os plátanos podiam comparar-se com os seus galhos; nenhuma árvore do jardim de Deus podia equiparar-se à sua beleza.

[[v26-31-9]]

^<<v26-31-9,9>>^ Eu o fiz belo com rica ramagem, a inveja de todas as árvores do Éden, do jardim de Deus.

[[v26-31-10]]

^<<v26-31-10,10>>^ " ‘Portanto, assim diz o Soberano Senhor: Como ele se ergueu e se tornou tão alto, alçando seu topo acima da folhagem espessa, e como ficou orgulhoso da sua altura,

[[v26-31-11]]

^<<v26-31-11,11>>^ eu o entreguei ao governante das nações para que este o tratasse de acordo com a sua maldade. Eu o rejeitei,

[[v26-31-12]]

^<<v26-31-12,12>>^ e a mais impiedosa das nações estrangeiras o derrubou e o deixou. Seus ramos caíram sobre os montes e em todos os vales; seus galhos jaziam quebrados em todas as ravinas da terra. Todas as nações da terra saíram de sua sombra e o abandonaram.

[[v26-31-13]]

^<<v26-31-13,13>>^ Todas as aves do céu se instalaram na árvore caída, e todos os animais do campo se abrigaram em seus galhos.

[[v26-31-14]]

^<<v26-31-14,14>>^ Por isso nenhuma outra árvore junto às águas chegará a erguer-se orgulhosamente tão alto, alçando o seu topo acima da folhagem espessa. Nenhuma outra árvore igualmente bem regada chegará a essa altura; estão todas destinadas à morte, e irão para baixo da terra, entre os homens mortais, com os que descem à cova.

[[v26-31-15]]

^<<v26-31-15,15>>^ " ‘Assim diz o Soberano Senhor: No dia em que ele foi baixado à sepultura, fiz o abismo encher-se de pranto por ele; estanquei os seus riachos, e a sua fartura de água foi retida. Por causa dele eu vesti o Líbano de trevas, e todas as árvores do campo secaram-se completamente.

[[v26-31-16]]

^<<v26-31-16,16>>^ Fiz as nações tremerem ao som da sua queda, quando o fiz descer à sepultura junto com os que descem à cova. Então todas as árvores do Éden, as mais belas e melhores do Líbano, todas as árvores bem regadas, consolavam-se embaixo da terra.

[[v26-31-17]]

^<<v26-31-17,17>>^ Todos os que viviam à sombra dele, seus aliados entre as nações, também haviam descido com ele à sepultura, juntando-se aos que foram mortos pela espada.

[[v26-31-18]]

^<<v26-31-18,18>>^ " ‘Qual das árvores do Éden pode comparar-se a você em esplendor e majestade? No entanto, você também será derrubado e irá para baixo da terra, junto com as árvores do Éden; você jazerá entre os incircuncisos, com os que foram mortos pela espada. " ‘Aí estão o faraó e todo o seu grande povo, palavra do Soberano Senhor’ ".

'''

xref:026-ezequiel/026-ezequiel-030.adoc#v26-30-0[&#60; Capítulo Anterior] | <<v26-31-0,Topo>> | xref:026-ezequiel/026-ezequiel-032.adoc#v26-32-0[Próximo Capítulo &#62;]