include::./index.adoc[]

[[v26-34-0]]
=== Ezequiel, 34
// nvi ?, NVI - Nova Versão Internacional

[[v26-34-1]]

^<<v26-34-1,1>>^ Veio a mim esta palavra do Senhor:

[[v26-34-2]]

^<<v26-34-2,2>>^ "Filho do homem, profetize contra os pastores de Israel; profetize e diga-lhes: ‘Assim diz o Soberano Senhor: Ai dos pastores de Israel que só cuidam de si mesmos! Acaso os pastores não deveriam cuidar do rebanho?

[[v26-34-3]]

^<<v26-34-3,3>>^ Vocês comem a coalhada, vestem-se de lã e abatem os melhores animais, mas não tomam conta do rebanho.

[[v26-34-4]]

^<<v26-34-4,4>>^ Vocês não fortaleceram a fraca nem curaram a doente nem enfaixaram a ferida. Vocês não trouxeram de volta as desviadas nem procuraram as perdidas. Vocês têm dominado sobre elas com dureza e brutalidade.

[[v26-34-5]]

^<<v26-34-5,5>>^ Por isso elas estão dispersas, porque não há pastor algum, e, quando foram dispersas, elas se tornaram comida de todos os animais selvagens.

[[v26-34-6]]

^<<v26-34-6,6>>^ As minhas ovelhas vaguearam por todos os montes e por todas as altas colinas. Elas foram dispersas por toda a terra, e ninguém se preocupou com elas nem as procurou.

[[v26-34-7]]

^<<v26-34-7,7>>^ " ‘Por isso, pastores, ouçam a palavra do Senhor:

[[v26-34-8]]

^<<v26-34-8,8>>^ Juro pela minha vida, palavra do Soberano Senhor, que visto que o meu rebanho ficou sem pastor, foi saqueado e se tornou comida de todos os animais selvagens, e uma vez que os meus pastores não se preocuparam com o meu rebanho, mas cuidaram de si mesmos em vez de cuidarem do rebanho,

[[v26-34-9]]

^<<v26-34-9,9>>^ ouçam a palavra do Senhor, ó pastores:

[[v26-34-10]]

^<<v26-34-10,10>>^ Assim diz o Soberano Senhor: Estou contra os pastores e os considerarei responsáveis pelo meu rebanho. Eu lhes tirarei a função de apascentar o rebanho para que os pastores não mais se alimentem a si mesmos. Livrarei o meu rebanho da boca deles, e ele não lhes servirá mais de comida.

[[v26-34-11]]

^<<v26-34-11,11>>^ " ‘Porque assim diz o Soberano Senhor: Eu mesmo buscarei as minhas ovelhas e delas cuidarei.

[[v26-34-12]]

^<<v26-34-12,12>>^ Assim como o pastor busca as ovelhas dispersas quando está cuidando do rebanho, também tomarei conta de minhas ovelhas. Eu as resgatarei de todos os lugares para onde foram dispersas num dia de nuvens e de trevas.

[[v26-34-13]]

^<<v26-34-13,13>>^ Eu as farei sair das outras nações e as reunirei, trazendo-as dos outros povos para a sua própria terra. E as apascentarei nos montes de Israel, nos vales e em todos os povoados do país.

[[v26-34-14]]

^<<v26-34-14,14>>^ Tomarei conta delas numa boa pastagem, e os altos dos montes de Israel serão a terra onde pastarão; ali se alimentarão num rico pasto nos montes de Israel.

[[v26-34-15]]

^<<v26-34-15,15>>^ Eu mesmo tomarei conta das minhas ovelhas e as farei deitar-se, palavra do Soberano Senhor.

[[v26-34-16]]

^<<v26-34-16,16>>^ Procurarei as perdidas e trarei de volta as desviadas. Enfaixarei a ferida e fortalecerei a fraca, mas a rebelde e forte, eu a destruirei. Apascentarei o rebanho com justiça.

[[v26-34-17]]

^<<v26-34-17,17>>^ " ‘Quanto a você, meu rebanho, assim diz o Soberano Senhor: Julgarei entre uma ovelha e outra, e entre carneiros e bodes.

[[v26-34-18]]

^<<v26-34-18,18>>^ Não lhes basta comerem em boa pastagem? Deverão também pisotear o restante da pastagem? Não lhes basta beberem água límpida? Deverão também enlamear o restante com os pés?

[[v26-34-19]]

^<<v26-34-19,19>>^ Deverá o meu rebanho alimentar-se daquilo que vocês pisotearam e beber daquilo que vocês enlamearam com os pés?

[[v26-34-20]]

^<<v26-34-20,20>>^ " ‘Por isso assim diz o Soberano Senhor a eles: Vejam, eu mesmo julgarei entre a ovelha gorda e a magra.

[[v26-34-21]]

^<<v26-34-21,21>>^ Pois vocês forçaram passagem com o corpo e com o ombro, empurrando todas as ovelhas fracas com os chifres até expulsá-las,

[[v26-34-22]]

^<<v26-34-22,22>>^ eu salvarei o meu rebanho, e elas não serão mais saqueadas. Julgarei entre uma ovelha e outra.

[[v26-34-23]]

^<<v26-34-23,23>>^ Porei sobre elas um pastor, o meu servo Davi, e ele cuidará delas; cuidará delas e será o seu pastor.

[[v26-34-24]]

^<<v26-34-24,24>>^ Eu, o Senhor, serei o seu Deus, e o meu servo Davi será o líder no meio delas. Eu, o Senhor, falei.

[[v26-34-25]]

^<<v26-34-25,25>>^ " ‘Farei uma aliança de paz com elas e deixarei a terra livre de animais selvagens para que possam, com segurança, viver no deserto e dormir nas florestas.

[[v26-34-26]]

^<<v26-34-26,26>>^ Eu as abençoarei e abençoarei os lugares em torno da minha colina. Na estação própria farei descer chuva; haverá chuvas de bênçãos.

[[v26-34-27]]

^<<v26-34-27,27>>^ As árvores do campo produzirão o seu fruto, e a terra produzirá a sua safra; o povo estará seguro na terra. Eles saberão que eu sou o Senhor, quando eu quebrar as cangas de seu jugo e livrá-los das mãos daqueles que os escravizaram.

[[v26-34-28]]

^<<v26-34-28,28>>^ Eles não serão mais saqueados pelas nações, nem os animais selvagens os devorarão. Viverão em segurança, e ninguém lhes causará medo.

[[v26-34-29]]

^<<v26-34-29,29>>^ Eu lhes darei uma terra famosa por suas colheitas, e eles não serão mais vítimas de fome na terra nem carregarão a zombaria das nações.

[[v26-34-30]]

^<<v26-34-30,30>>^ Então eles saberão que eu, o Senhor, o seu Deus, estou com eles, e que eles, a nação de Israel, são meu povo, palavra do Soberano Senhor.

[[v26-34-31]]

^<<v26-34-31,31>>^ Vocês, minhas ovelhas, ovelhas da minha pastagem, são o meu povo, e eu sou o Deus de vocês, palavra do Soberano Senhor’ ".

'''

xref:026-ezequiel/026-ezequiel-033.adoc#v26-33-0[&#60; Capítulo Anterior] | <<v26-34-0,Topo>> | xref:026-ezequiel/026-ezequiel-035.adoc#v26-35-0[Próximo Capítulo &#62;]