include::./index.adoc[]

[[v26-18-0]]
=== Ezequiel, 18
// nvi ?, NVI - Nova Versão Internacional

[[v26-18-1]]

^<<v26-18-1,1>>^ Esta palavra do Senhor veio a mim:

[[v26-18-2]]

^<<v26-18-2,2>>^ "Que é que vocês querem dizer quando citam este provérbio sobre Israel: " ‘Os pais comem uvas verdes, e os dentes dos filhos se embotam’?

[[v26-18-3]]

^<<v26-18-3,3>>^ "Juro pela minha vida, palavra do Soberano Senhor, que vocês não citarão mais esse provérbio em Israel.

[[v26-18-4]]

^<<v26-18-4,4>>^ Pois todos me pertencem. Tanto o pai como o filho me pertencem. Aquele que pecar é que morrerá.

[[v26-18-5]]

^<<v26-18-5,5>>^ "Suponhamos que haja um certo justo que faz o que é certo e direito.

[[v26-18-6]]

^<<v26-18-6,6>>^ Ele não come nos santuários que há nos montes e nem olha para os ídolos da nação de Israel. Ele não contamina a mulher do próximo nem se deita com uma mulher durante os seus dias de fluxo.

[[v26-18-7]]

^<<v26-18-7,7>>^ Ele não oprime a ninguém, mas devolve o que tomou como garantia num empréstimo. Não comete roubos, mas dá a comida aos famintos e fornece roupas para os despidos.

[[v26-18-8]]

^<<v26-18-8,8>>^ Ele não empresta visando lucro nem cobra juros. Ele retém a sua mão para não cometer erro e julga com justiça entre dois homens.

[[v26-18-9]]

^<<v26-18-9,9>>^ Ele age segundo os meus decretos e obedece fielmente às minhas leis. Aquele homem é justo; com certeza ele viverá, palavra do Soberano Senhor.

[[v26-18-10]]

^<<v26-18-10,10>>^ "Suponhamos que ele tenha um filho violento, que derrama sangue ou faz qualquer uma dessas outras coisas,

[[v26-18-11]]

^<<v26-18-11,11>>^ embora o pai não tenha feito nenhuma delas: "Ele come nos santuários que há nos montes. Contamina a mulher do próximo.

[[v26-18-12]]

^<<v26-18-12,12>>^ Oprime os pobres e os necessitados. Comete roubos. Não devolve o que tomou como garantia. Volta-se para os ídolos, comete práticas detestáveis.

[[v26-18-13]]

^<<v26-18-13,13>>^ Empresta visando lucro e cobra juros. Haverá de viver um homem desses? Não! Por todas essas práticas detestáveis, com certeza será morto, e ele será o culpado por sua própria morte.

[[v26-18-14]]

^<<v26-18-14,14>>^ "Mas suponhamos que esse filho tenha ele mesmo um filho que vê todos os pecados que seu pai comete e, embora os veja, não os comete.

[[v26-18-15]]

^<<v26-18-15,15>>^ "Ele não come nos santuários que há nos montes e nem olha para os ídolos da nação de Israel. Não contamina a mulher do próximo.

[[v26-18-16]]

^<<v26-18-16,16>>^ Ele não oprime a ninguém, nem exige garantia para um empréstimo. Não comete roubos, mas dá comida aos famintos e fornece roupas aos despidos.

[[v26-18-17]]

^<<v26-18-17,17>>^ Ele retém a mão para não pecar e não empresta visando lucro nem cobra juros. Guarda as minhas leis e age segundo os meus decretos. Ele não morrerá por causa da iniqüidade do seu pai; certamente viverá.

[[v26-18-18]]

^<<v26-18-18,18>>^ Mas seu pai morrerá por causa de sua própria iniqüidade, pois praticou extorsão, roubou seu compatriota e fez o que era errado no meio de seu povo.

[[v26-18-19]]

^<<v26-18-19,19>>^ "Contudo, vocês perguntam: ‘Por que o filho não partilha da culpa de seu pai? ’ Uma vez que o filho fez o que é justo e direito e teve o cuidado de guardar todos os meus decretos, com certeza ele viverá.

[[v26-18-20]]

^<<v26-18-20,20>>^ Aquele que pecar é que morrerá. O filho não levará a culpa do pai, nem o pai levará a culpa do filho. A justiça do justo lhe será creditada, e a impiedade do ímpio lhe será cobrada.

[[v26-18-21]]

^<<v26-18-21,21>>^ "Mas, se um ímpio se desviar de todos os pecados que cometeu e obedecer a todos os meus decretos e fizer o que é justo e direito, com certeza viverá; não morrerá.

[[v26-18-22]]

^<<v26-18-22,22>>^ Não se terá lembrança de nenhuma das ofensas que cometeu. Devido às coisas justas que tiver feito, ele viverá.

[[v26-18-23]]

^<<v26-18-23,23>>^ Teria eu algum prazer na morte do ímpio?, palavra do Soberano Senhor. Pelo contrário, acaso não me agrada vê-lo desviar-se dos seus caminhos e viver?

[[v26-18-24]]

^<<v26-18-24,24>>^ "Se, porém, um justo se desviar de sua justiça, e cometer pecado e as mesmas práticas detestáveis dos ímpios, deverá ele viver? Nenhuma das coisas justas que fez será lembrada! Por causa da infidelidade de que é culpado e por causa dos pecados que cometeu, ele morrerá.

[[v26-18-25]]

^<<v26-18-25,25>>^ "Contudo, vocês dizem: ‘O caminho do Senhor não é justo’. Ouça, ó nação de Israel: O meu caminho é injusto? Não são os seus caminhos que são injustos?

[[v26-18-26]]

^<<v26-18-26,26>>^ Se um justo desviar-se de sua justiça e cometer pecado, ele morrerá por causa disso; por causa do pecado que cometeu morrerá.

[[v26-18-27]]

^<<v26-18-27,27>>^ Mas, se um ímpio se desviar de sua maldade e fizer o que é justo e direito, ele salvará sua vida.

[[v26-18-28]]

^<<v26-18-28,28>>^ Por considerar todas as ofensas que cometeu e se desviar delas, ele com certeza viverá; não morrerá.

[[v26-18-29]]

^<<v26-18-29,29>>^ Contudo, a nação de Israel diz: ‘O caminho do Senhor não é justo’. São injustos os meus caminhos, ó nação de Israel? Não são os seus caminhos que são injustos?

[[v26-18-30]]

^<<v26-18-30,30>>^ "Portanto, ó nação de Israel, eu os julgarei, a cada um de acordo com os seus caminhos; palavra do Soberano Senhor. Arrependam-se! Desviem-se de todos os seus males, para que o pecado não cause a queda de vocês.

[[v26-18-31]]

^<<v26-18-31,31>>^ Livrem-se de todos os males que vocês cometeram, e busquem um coração novo e um espírito novo. Por que deveriam morrer, ó nação de Israel?

[[v26-18-32]]

^<<v26-18-32,32>>^ Pois não me agrada a morte de ninguém; palavra do Soberano Senhor. Arrependam-se e vivam!

'''

xref:026-ezequiel/026-ezequiel-017.adoc#v26-17-0[&#60; Capítulo Anterior] | <<v26-18-0,Topo>> | xref:026-ezequiel/026-ezequiel-019.adoc#v26-19-0[Próximo Capítulo &#62;]