include::./index.adoc[]

[[v26-47-0]]
=== Ezequiel, 47
// nvi ?, NVI - Nova Versão Internacional

[[v26-47-1]]

^<<v26-47-1,1>>^ O homem levou-me de volta à entrada do templo, e vi água saindo de debaixo da soleira do templo e indo para o leste, pois o templo estava voltado para o oriente. A água descia de debaixo do lado sul do templo, ao sul do altar.

[[v26-47-2]]

^<<v26-47-2,2>>^ Ele então me levou para fora, pela porta norte, e conduziu-me pelo lado de fora até a porta externa que dá para o leste, e a água fluía do lado sul.

[[v26-47-3]]

^<<v26-47-3,3>>^ O homem foi para o lado leste com uma linha de medir na mão, e, enquanto ia, mediu quinhentos metros e levou-me pela água, que batia no tornozelo.

[[v26-47-4]]

^<<v26-47-4,4>>^ Ele mediu mais quinhentos e levou-me pela água, que batia na cintura. Mediu mais quinhentos e levou-me pela água, que chegava ao joelho.

[[v26-47-5]]

^<<v26-47-5,5>>^ Mediu mais quinhentos, mas agora era um rio que eu não conseguia atravessar, porque a água havia aumentado e era tão profunda que só se podia atravessar a nado; era um rio que não se podia atravessar andando.

[[v26-47-6]]

^<<v26-47-6,6>>^ Ele me perguntou: "Filho do homem, você vê isto? " Levou-me então de volta à margem do rio.

[[v26-47-7]]

^<<v26-47-7,7>>^ Quando ali cheguei, vi muitas árvores em cada lado do rio.

[[v26-47-8]]

^<<v26-47-8,8>>^ Ele me disse: "Esta água flui na direção da região situada a leste e desce até a Arabá, onde entra no Mar. Quando deságua no Mar, a água ali será saneada.

[[v26-47-9]]

^<<v26-47-9,9>>^ Por onde passar o rio haverá todo tipo de animais e de peixes. Porque essa água flui para lá e saneia a água salgada; de modo que onde o rio fluir tudo viverá.

[[v26-47-10]]

^<<v26-47-10,10>>^ Pescadores estarão ao longo do litoral; desde En-Gedi até En-Eglaim haverá locais próprios para estender as redes. Os peixes serão de muitos tipos, como os peixes do mar Grande.

[[v26-47-11]]

^<<v26-47-11,11>>^ Mas os charcos e os pântanos não ficarão saneados; serão deixados para o sal.

[[v26-47-12]]

^<<v26-47-12,12>>^ Árvores frutíferas de toda espécie crescerão em ambas as margens do rio. Suas folhas não murcharão e os seus frutos não cairão. Todo mês produzirão, porque a água vinda do santuário chega a elas. Seus frutos servirão de comida, e suas folhas de remédio".

[[v26-47-13]]

^<<v26-47-13,13>>^ Assim diz o Soberano Senhor: "Estas são as fronteiras pelas quais vocês devem dividir a terra como herança entre as doze tribos de Israel, com duas porções para José.

[[v26-47-14]]

^<<v26-47-14,14>>^ Vocês a dividirão igualmente entre elas. Visto que eu jurei de mão erguida que a daria aos seus antepassados, esta terra se tornará herança de vocês.

[[v26-47-15]]

^<<v26-47-15,15>>^ "Esta é a fronteira da terra: "No lado norte ela irá desde o mar Grande, indo pela estrada de Hetlom, passando por Lebo-Hamate até Zedade,

[[v26-47-16]]

^<<v26-47-16,16>>^ Berota e Sibraim, que fica na fronteira entre Damasco e Hamate, e indo até Hazer-Haticom, que fica na extremidade de Haurã.

[[v26-47-17]]

^<<v26-47-17,17>>^ A fronteira se estenderá desde o Mar até Hazar-Enã, ao longo da fronteira norte de Damasco, com a fronteira de Hamate ao norte. Essa será a fronteira norte.

[[v26-47-18]]

^<<v26-47-18,18>>^ "No lado leste a fronteira irá entre Haurã e Damasco, ao longo do Jordão entre Gileade e a terra de Israel, até o mar oriental, prosseguindo até Tamar. Essa será a fronteira leste.

[[v26-47-19]]

^<<v26-47-19,19>>^ "No lado sul ela irá desde Tamar até as águas de Meribá-Cades, prosseguindo então ao longo do ribeiro do Egito até o mar Grande. Essa será a fronteira sul.

[[v26-47-20]]

^<<v26-47-20,20>>^ "No lado oeste, o mar Grande será a fronteira até de frente a Lebo-Hamate. Essa será a fronteira oeste.

[[v26-47-21]]

^<<v26-47-21,21>>^ "Distribuam essa terra entre vocês de acordo com as tribos de Israel.

[[v26-47-22]]

^<<v26-47-22,22>>^ Vocês a distribuirão como herança para vocês mesmos e para os estrangeiros residentes no meio de vocês e que têm filhos. Vocês os considerarão como israelitas de nascimento; juntamente com vocês, a eles deverá ser designada uma herança entre as tribos de Israel.

[[v26-47-23]]

^<<v26-47-23,23>>^ Qualquer que seja a tribo no qual o estrangeiro se instale, ali vocês lhe darão a herança que lhe cabe", palavra do Soberano Senhor.

'''

xref:026-ezequiel/026-ezequiel-046.adoc#v26-46-0[&#60; Capítulo Anterior] | <<v26-47-0,Topo>> | xref:026-ezequiel/026-ezequiel-048.adoc#v26-48-0[Próximo Capítulo &#62;]