include::./index.adoc[]

[[v26-5-0]]
=== Ezequiel, 5
// nvi ?, NVI - Nova Versão Internacional

[[v26-5-1]]

^<<v26-5-1,1>>^ "Agora, filho do homem, apanhe uma espada afiada e use-a como navalha de barbeiro para rapar a cabeça e a barba. Depois tome uma balança de pesos e reparta o cabelo.

[[v26-5-2]]

^<<v26-5-2,2>>^ Quando os dias do cerco da cidade chegarem ao fim, queime no fogo um terço do cabelo dentro da cidade. Pegue um terço e corte-o com a espada ao redor de toda a cidade. E espalhe um terço ao vento. Porque eu os perseguirei com espada desembainhada.

[[v26-5-3]]

^<<v26-5-3,3>>^ Mas apanhe umas poucas mechas de cabelo e esconda-as nas dobras de sua roupa.

[[v26-5-4]]

^<<v26-5-4,4>>^ E destas ainda, pegue algumas e atire-as ao fogo, para que se queimem. Dali um fogo se espalhará para toda a nação de Israel.

[[v26-5-5]]

^<<v26-5-5,5>>^ "Assim diz o Soberano Senhor: Esta é Jerusalém, que pus no meio dos povos, com nações ao seu redor.

[[v26-5-6]]

^<<v26-5-6,6>>^ Contudo, em sua maldade, ela se revoltou contra as minhas leis e contra os meus decretos mais do que os povos e as nações ao seu redor. Ela rejeitou as minhas leis e não agiu segundo os meus decretos.

[[v26-5-7]]

^<<v26-5-7,7>>^ "Portanto assim diz o Soberano Senhor: Você tem sido mais rebelde do que as nações ao seu redor e não agiu segundo os meus decretos nem guardou as minhas leis. Você nem mesmo alcançou os padrões das nações ao seu redor.

[[v26-5-8]]

^<<v26-5-8,8>>^ "Por isso diz o Soberano Senhor: Eu estou contra você, Jerusalém, e lhe infligirei castigo à vista das nações.

[[v26-5-9]]

^<<v26-5-9,9>>^ Por causa de todos os seus ídolos detestáveis, farei com você o que nunca fiz nem jamais voltarei a fazer.

[[v26-5-10]]

^<<v26-5-10,10>>^ Por isso, entre vocês sucederá que os pais comerão os seus próprios filhos, e os filhos comerão os seus pais. Castigarei você e dispersarei aos ventos os seus sobreviventes.

[[v26-5-11]]

^<<v26-5-11,11>>^ Por isso, juro pela minha vida, palavra do Soberano Senhor, que por ter contaminado meu santuário com suas imagens detestáveis e com suas práticas repugnantes, eu retirarei o meu favor. Não olharei com piedade para ti e não a pouparei.

[[v26-5-12]]

^<<v26-5-12,12>>^ Um terço de seu povo morrerá de peste ou perecerá de fome dentro de seus muros; um terço cairá pela espada fora da cidade; e um terço dispersarei aos ventos e perseguirei com a espada em punho.

[[v26-5-13]]

^<<v26-5-13,13>>^ "Então a minha ira cessará, e diminuirá a minha indignação contra eles, e serei vingado. E, quando tiver esgotado a minha ira sobre eles, saberão que eu, o Senhor, falei segundo o meu zelo.

[[v26-5-14]]

^<<v26-5-14,14>>^ "Farei de você uma ruína e a tornarei desprezível entre as nações ao seu redor, à vista de todos quantos por você passarem.

[[v26-5-15]]

^<<v26-5-15,15>>^ Você será motivo de desprezo e de escárnio, e servirá de advertência e de causa de pavor às nações ao redor, quando eu castigar você com ira, indignação e violência. Eu, o Senhor, falei.

[[v26-5-16]]

^<<v26-5-16,16>>^ Quando eu atirar em você minhas flechas mortais e destruidoras, minhas flechas de fome, atirarei para destruí-la. Aumentarei a sua fome e cortarei o seu sustento.

[[v26-5-17]]

^<<v26-5-17,17>>^ Enviarei contra você a fome e animais selvagens, que acabarão com os seus filhos. A peste e o derramamento de sangue a alcançarão, e trarei a espada contra você. Eu, o Senhor, falei".

'''

xref:026-ezequiel/026-ezequiel-004.adoc#v26-4-0[&#60; Capítulo Anterior] | <<v26-5-0,Topo>> | xref:026-ezequiel/026-ezequiel-006.adoc#v26-6-0[Próximo Capítulo &#62;]