include::./index.adoc[]

[[v26-4-0]]
=== Ezequiel, 4
// nvi ?, NVI - Nova Versão Internacional

[[v26-4-1]]

^<<v26-4-1,1>>^ "Agora, filho do homem, apanhe uma tabuinha de barro, coloque-a à sua frente e nela desenhe a cidade de Jerusalém.

[[v26-4-2]]

^<<v26-4-2,2>>^ Cerque-a então, e erga obras de cerco contra ela; construa uma rampa, monte acampamentos e ponha aríetes ao redor dela.

[[v26-4-3]]

^<<v26-4-3,3>>^ Depois apanhe uma panela de ferro, coloque-a como muro de ferro entre você e a cidade e ponha-se de frente para ela. Ela estará cercada, e você a sitiará. Isto será um sinal para a nação de Israel.

[[v26-4-4]]

^<<v26-4-4,4>>^ "Deite-se então sobre o seu lado esquerdo e sobre você ponha a iniqüidade da nação de Israel. Você terá que carregar a iniqüidade dela durante o número de dias em que estiver deitado sobre o lado esquerdo.

[[v26-4-5]]

^<<v26-4-5,5>>^ Determinei que o número de dias seja equivalente ao número de anos da iniqüidade dela, ou seja, durante trezentos e noventa dias você carregará a iniqüidade da nação de Israel.

[[v26-4-6]]

^<<v26-4-6,6>>^ "Terminado esse prazo, deite-se sobre o seu lado direito, e carregue a iniqüidade da nação de Judá,

[[v26-4-7]]

^<<v26-4-7,7>>^ durante quarenta dias, tempo que eu determinei para você, um dia para cada ano. Olhe para o cerco de Jerusalém e, com braço desnudo, profetize contra ela.

[[v26-4-8]]

^<<v26-4-8,8>>^ Vou amarrá-lo com cordas para que você não possa virar-se de lado enquanto não cumprir os dias da sua aflição.

[[v26-4-9]]

^<<v26-4-9,9>>^ "Pegue trigo e cevada, feijão e lentilha, painço e espelta; ponha-os numa vasilha e com eles faça pão para você. Você deverá comê-lo durante os trezentos e noventa dias em que estiver deitado sobre o seu lado.

[[v26-4-10]]

^<<v26-4-10,10>>^ Pese duzentos e quarenta gramas do pão por dia e coma-o em horas determinadas.

[[v26-4-11]]

^<<v26-4-11,11>>^ Também meça meio litro de água e beba-a em horas determinadas.

[[v26-4-12]]

^<<v26-4-12,12>>^ Coma o pão como você comeria um bolo de cevada; asse-o à vista do povo, usando fezes humanas como combustível".

[[v26-4-13]]

^<<v26-4-13,13>>^ O Senhor disse: "Desse modo os israelitas comerão sua comida imunda entre as nações para onde eu os expulsar".

[[v26-4-14]]

^<<v26-4-14,14>>^ Então eu disse: "Ah! Soberano Senhor! Eu jamais me contaminei. Desde a minha infância até agora, jamais comi qualquer coisa achada morta ou que tivesse sido despedaçada por animais selvagens. Jamais entrou em minha boca qualquer carne impura".

[[v26-4-15]]

^<<v26-4-15,15>>^ "Está bem", disse ele, "deixarei que você asse o seu pão em cima de esterco de vaca, e não em cima de fezes humanas. "

[[v26-4-16]]

^<<v26-4-16,16>>^ E acrescentou: "Filho do homem, cortarei o suprimento de comida em Jerusalém. O povo comerá com ansiedade comida racionada e beberá com desespero água racionada,

[[v26-4-17]]

^<<v26-4-17,17>>^ pois haverá falta de comida e de água. Ficarão chocados ao se verem uns aos outros, e definharão por causa de sua iniqüidade.

'''

xref:026-ezequiel/026-ezequiel-003.adoc#v26-3-0[&#60; Capítulo Anterior] | <<v26-4-0,Topo>> | xref:026-ezequiel/026-ezequiel-005.adoc#v26-5-0[Próximo Capítulo &#62;]