include::./index.adoc[]

[[v26-15-0]]
=== Ezequiel, 15
// nvi ?, NVI - Nova Versão Internacional

[[v26-15-1]]

^<<v26-15-1,1>>^ A palavra do Senhor veio a mim. Disse ele:

[[v26-15-2]]

^<<v26-15-2,2>>^ "Filho do homem, em que a madeira da videira é melhor do que o galho de qualquer das árvores da floresta?

[[v26-15-3]]

^<<v26-15-3,3>>^ Alguma vez a madeira dela é usada para fazer algo útil? Alguém faz suportes com ela para neles pendurar coisas?

[[v26-15-4]]

^<<v26-15-4,4>>^ E, depois de ser lançada no fogo como combustível e o fogo queimar as duas extremidades e carbonizar o meio, servirá para alguma coisa?

[[v26-15-5]]

^<<v26-15-5,5>>^ Se não foi útil para coisa alguma enquanto estava inteira, muito menos o será quando o fogo a queimar e ela estiver carbonizada.

[[v26-15-6]]

^<<v26-15-6,6>>^ "Por isso diz o Soberano Senhor: Assim como destinei a madeira da videira dentre as árvores da floresta para servir de lenha para o fogo, também tratarei os habitantes de Jerusalém.

[[v26-15-7]]

^<<v26-15-7,7>>^ Voltarei contra eles o meu rosto. Do fogo saíram, mas o fogo os consumirá. E, quando eu voltar o meu rosto contra eles, vocês saberão que eu sou o Senhor.

[[v26-15-8]]

^<<v26-15-8,8>>^ Arrasarei a terra porque eles foram infiéis, palavra do Soberano Senhor".

'''

xref:026-ezequiel/026-ezequiel-014.adoc#v26-14-0[&#60; Capítulo Anterior] | <<v26-15-0,Topo>> | xref:026-ezequiel/026-ezequiel-016.adoc#v26-16-0[Próximo Capítulo &#62;]