include::./index.adoc[]

[[v26-23-0]]
=== Ezequiel, 23
// nvi ?, NVI - Nova Versão Internacional

[[v26-23-1]]

^<<v26-23-1,1>>^ Esta palavra do Senhor veio a mim:

[[v26-23-2]]

^<<v26-23-2,2>>^ "Filho do homem, existiam duas mulheres, filhas da mesma mãe.

[[v26-23-3]]

^<<v26-23-3,3>>^ Elas se tornaram prostitutas no Egito, envolvendo-se na prostituição desde a juventude. Naquela terra os seus peitos foram acariciados e os seus seios virgens foram afagados.

[[v26-23-4]]

^<<v26-23-4,4>>^ A mais velha chamava-se Oolá, e sua irmã, Oolibá. Elas eram minhas e deram à luz filhos e filhas. Oolá é Samaria, e Oolibá é Jerusalém.

[[v26-23-5]]

^<<v26-23-5,5>>^ "Oolá envolveu-se em prostituição enquanto ainda era minha; ela se encheu de cobiça por seus amantes, os assírios, guerreiros

[[v26-23-6]]

^<<v26-23-6,6>>^ vestidos de vermelho, governadores e comandantes, todos eles cavaleiros jovens e elegantes.

[[v26-23-7]]

^<<v26-23-7,7>>^ Ela se entregou como prostituta a toda a elite dos assírios e contaminou-se com todos os ídolos de cada homem por ela cobiçado.

[[v26-23-8]]

^<<v26-23-8,8>>^ Ela não abandonou a prostituição iniciada no Egito, quando em sua juventude homens dormiram com ela, afagaram seus seios virgens e a envolveram em suas práticas dissolutas.

[[v26-23-9]]

^<<v26-23-9,9>>^ "Por isso eu a entreguei nas mãos de seus amantes, os assírios, os quais ela desejou ardentemente.

[[v26-23-10]]

^<<v26-23-10,10>>^ Eles lhe arrancaram as roupas, deixando-a nua, levaram embora seus filhos e suas filhas e a mataram com à espada. Ela se tornou um provérbio entre as mulheres. Foi-lhe infligido castigo.

[[v26-23-11]]

^<<v26-23-11,11>>^ "Sua irmã Oolibá viu isso. No entanto, em sua cobiça e prostituição, ela foi mais depravada do que a irmã.

[[v26-23-12]]

^<<v26-23-12,12>>^ Também desejou ardentemente os assírios, governadores e comandantes, guerreiros em uniforme completo, todos eles jovens e belos cavaleiros.

[[v26-23-13]]

^<<v26-23-13,13>>^ Vi que ela também se contaminou; ambas seguiram o mesmo caminho.

[[v26-23-14]]

^<<v26-23-14,14>>^ "Mas ela levou sua prostituição ainda mais longe. Viu homens desenhados numa parede, figuras de caldeus em vermelho,

[[v26-23-15]]

^<<v26-23-15,15>>^ usando cinturões e esvoaçantes turbantes na cabeça; todos se pareciam com oficiais que chefiam os carros da Babilônia, nativos da Caldéia.

[[v26-23-16]]

^<<v26-23-16,16>>^ Assim que ela os viu, desejou-os ardentemente e lhes mandou mensageiros até a Caldéia.

[[v26-23-17]]

^<<v26-23-17,17>>^ Então os babilônios vieram procurá-la, até a cama do amor, e em sua cobiça a contaminaram. Depois de haver sido contaminada por eles, ela se afastou deles desgostosa.

[[v26-23-18]]

^<<v26-23-18,18>>^ Ela, então, prosseguiu abertamente em sua prostituição e expôs a sua nudez, e eu me afastei dela desgostoso, assim como eu tinha me afastado de sua irmã.

[[v26-23-19]]

^<<v26-23-19,19>>^ Contudo, ela ia se tornando cada vez mais promíscua à medida que se recordava dos dias de sua juventude, quando era prostituta no Egito.

[[v26-23-20]]

^<<v26-23-20,20>>^ Desejou ardentemente os seus amantes, cujos membros eram como os de jumentos e cuja ejaculação era como a de cavalos.

[[v26-23-21]]

^<<v26-23-21,21>>^ De modo que você ansiou pela lascívia de sua juventude, quando no Egito seus peitos eram afagados e seus seios virgens eram acariciados.

[[v26-23-22]]

^<<v26-23-22,22>>^ "Portanto, Oolibá, assim diz o Soberano Senhor: Incitarei os seus amantes contra você, aqueles de quem você se afastou desgostosa, e os trarei para atacá-la de todos os lados,

[[v26-23-23]]

^<<v26-23-23,23>>^ os babilônios e todos os caldeus, os homens de Pecode, de Soa e de Coa, e com eles todos os assírios, belos rapazes, todos eles governadores e comandantes, oficiais que chefiam os carros e homens de posto elevado, todos galantes cavaleiros.

[[v26-23-24]]

^<<v26-23-24,24>>^ Eles virão contra você com armas, carros e carroças e com uma multidão de povos; por todos os lados tomarão posição contra você com escudos grandes e pequenos e com capacetes. Eu a entregarei a eles para castigo, e eles a castigarão conforme o costume deles.

[[v26-23-25]]

^<<v26-23-25,25>>^ Dirigirei contra você a ira do meu ciúme, e, enfurecidos, eles saberão como tratá-la. Cortarão fora o seu nariz e as suas orelhas, e os que forem deixados cairão pela espada. Levarão embora seus filhos e suas filhas, e os que forem deixados serão consumidos pelo fogo.

[[v26-23-26]]

^<<v26-23-26,26>>^ Também arrancarão as suas roupas e tomarão suas lindas jóias.

[[v26-23-27]]

^<<v26-23-27,27>>^ Assim darei um basta à lascívia e à prostituição que você começou no Egito. Você deixará de olhar com desejo para essas coisas e não se lembrará mais do Egito.

[[v26-23-28]]

^<<v26-23-28,28>>^ "Pois assim diz o Soberano Senhor: Estou a ponto de entregá-la nas mãos daqueles que você odeia, daqueles de quem você se afastou desgostosa.

[[v26-23-29]]

^<<v26-23-29,29>>^ Eles a tratarão com ódio e levarão embora tudo aquilo pelo que você trabalhou. Eles a deixarão despida e nua, e a vergonha de sua prostituição será exposta. Sua lascívia e sua promiscuidade

[[v26-23-30]]

^<<v26-23-30,30>>^ trouxeram isto sobre você, porque você desejou ardentemente as nações e se contaminou com os ídolos delas.

[[v26-23-31]]

^<<v26-23-31,31>>^ Você seguiu pelo caminho de sua irmã; por essa razão porei o copo dela nas suas mãos.

[[v26-23-32]]

^<<v26-23-32,32>>^ "Assim diz o Soberano Senhor: "Você beberá do copo de sua irmã, copo grande e fundo; ele causará riso e zombaria, de tão grande que é.

[[v26-23-33]]

^<<v26-23-33,33>>^ Você será dominada pela embriaguez e pela tristeza, com esse copo de desgraça e desolação, o copo de sua irmã Samaria.

[[v26-23-34]]

^<<v26-23-34,34>>^ Você o beberá, engolindo até a última gota; depois você o despedaçará e mutilará os próprios seios. "Eu o disse: Palavra do Soberano, do Senhor.

[[v26-23-35]]

^<<v26-23-35,35>>^ "Agora, assim diz o Soberano Senhor: Visto que você se esqueceu de mim e me deu as costas, você vai sofrer as conseqüências de sua lascívia e de sua prostituição".

[[v26-23-36]]

^<<v26-23-36,36>>^ O Senhor me disse: "Filho do homem, você julgará Oolá e Oolibá? Então confronte-as com suas práticas repugnantes,

[[v26-23-37]]

^<<v26-23-37,37>>^ pois elas cometeram adultério e há sangue em suas mãos. Cometeram adultério com seus ídolos; até os seus filhos, os quais elas geraram para mim, sacrificaram aos ídolos.

[[v26-23-38]]

^<<v26-23-38,38>>^ Também me fizeram isto: ao mesmo tempo contaminaram o meu santuário e profanaram os meus sábados.

[[v26-23-39]]

^<<v26-23-39,39>>^ No mesmo dia em que sacrificavam seus filhos a seus ídolos, elas entravam em meu santuário e o profanavam. Foi isso que elas fizeram em minha casa.

[[v26-23-40]]

^<<v26-23-40,40>>^ "Elas até enviaram mensageiros atrás de homens, que vieram de bem longe, e, quando eles chegaram, você se banhou para recebê-los, pintou os olhos e pôs suas jóias.

[[v26-23-41]]

^<<v26-23-41,41>>^ Você se sentou num belo sofá, tendo à frente uma mesa, na qual você havia colocado o incenso e o óleo que me pertenciam.

[[v26-23-42]]

^<<v26-23-42,42>>^ "O ruído de uma multidão despreocupada estava em torno dela; sabeus foram trazidos do deserto junto com homens do povo, e eles puseram braceletes nos braços da mulher e da sua irmã e belíssimas coroas na cabeças delas.

[[v26-23-43]]

^<<v26-23-43,43>>^ Então eu disse a respeito daquela que fora destruída pelo adultério: ‘Que agora a usem como prostituta, pois isso é tudo o que ela é’.

[[v26-23-44]]

^<<v26-23-44,44>>^ E eles dormiram com ela. Dormiram com aquelas mulheres lascivas, Oolá e Oolibá, como quem dorme com uma prostituta.

[[v26-23-45]]

^<<v26-23-45,45>>^ Mas justos as condenarão ao castigo que merecem as mulheres que cometem adultério e derramam sangue, porque são adúlteras e há sangue em suas mãos.

[[v26-23-46]]

^<<v26-23-46,46>>^ "Assim diz o Soberano Senhor: Que uma multidão as ataque e que elas sejam entregues ao pavor e ao saque.

[[v26-23-47]]

^<<v26-23-47,47>>^ A multidão as apedrejará e as retalhará à espada; matarão seus filhos e suas filhas e destruirão suas casas, incendiando-as.

[[v26-23-48]]

^<<v26-23-48,48>>^ "Dessa maneira darei fim à lascívia na terra, para que todas as mulheres fiquem advertidas e não imitem vocês.

[[v26-23-49]]

^<<v26-23-49,49>>^ Vocês sofrerão o castigo de sua cobiça e as conseqüências de seus pecados de idolatria. E vocês saberão que eu sou o Soberano Senhor".

'''

xref:026-ezequiel/026-ezequiel-022.adoc#v26-22-0[&#60; Capítulo Anterior] | <<v26-23-0,Topo>> | xref:026-ezequiel/026-ezequiel-024.adoc#v26-24-0[Próximo Capítulo &#62;]