include::./index.adoc[]

[[v26-44-0]]
=== Ezequiel, 44
// nvi ?, NVI - Nova Versão Internacional

[[v26-44-1]]

^<<v26-44-1,1>>^ Depois o homem trouxe-me de volta para a porta externa do santuário, que dava para o lado leste, e ela estava trancada.

[[v26-44-2]]

^<<v26-44-2,2>>^ O Senhor me disse: "Esta porta deve permanecer trancada. Não deverá ser aberta; ninguém poderá entrar por ela. Deve permanecer trancada porque o Senhor, o Deus de Israel, entrou por ela.

[[v26-44-3]]

^<<v26-44-3,3>>^ O príncipe é o único que poderá entrar e sentar-se dentro para comer na presença do Senhor. Ele entrará pelo pórtico da entrada e sairá pelo mesmo caminho".

[[v26-44-4]]

^<<v26-44-4,4>>^ Então o homem levou-me até a frente do templo, passando pela porta norte. Olhei e vi a glória do Senhor enchendo o templo do Senhor, e prostrei-me, rosto em terra.

[[v26-44-5]]

^<<v26-44-5,5>>^ O Senhor me disse: "Filho do homem preste atenção, olhe e ouça atentamente tudo o que eu lhe disser acerca de todos os regulamentos a respeito do templo do Senhor. Preste atenção à entrada do templo e a todas as saídas do santuário.

[[v26-44-6]]

^<<v26-44-6,6>>^ Diga à rebelde nação de Israel: ‘Assim diz o Soberano Senhor: Já bastam suas práticas repugnantes, ó nação de Israel!

[[v26-44-7]]

^<<v26-44-7,7>>^ Além de todas as suas outras práticas repugnantes, vocês trouxeram estrangeiros incircuncisos no coração e na carne para dentro do meu santuário, profanando o meu templo enquanto me ofereciam comida, gordura e sangue, e assim vocês romperam a minha aliança.

[[v26-44-8]]

^<<v26-44-8,8>>^ Ao invés de cumprirem seu dever quanto às minhas coisas sagradas, vocês encarregaram outros do meu santuário.

[[v26-44-9]]

^<<v26-44-9,9>>^ Assim diz o Soberano Senhor: Nenhum estrangeiro incircunciso no coração e na carne entrará no meu santuário, nem tampouco os estrangeiros que vivem entre os israelitas.

[[v26-44-10]]

^<<v26-44-10,10>>^ " ‘Os levitas que tanto se distanciaram de mim quando Israel se desviou e que vaguearam para longe de mim, indo atrás de seus ídolos, sofrerão as conseqüências de sua iniqüidade.

[[v26-44-11]]

^<<v26-44-11,11>>^ Poderão servir no meu santuário, como encarregados das portas do templo e servindo nele; poderão matar os animais dos holocaustos e outros sacrifícios em lugar do povo e colocar-se diante do povo e servi-lo.

[[v26-44-12]]

^<<v26-44-12,12>>^ Mas, porque os serviram na presença de seus ídolos e fizeram a nação de Israel cair em pecado, jurei de mão erguida que eles sofrerão as conseqüências de sua iniqüidade, palavra do Soberano Senhor.

[[v26-44-13]]

^<<v26-44-13,13>>^ Não se aproximarão para me servir como sacerdotes nem se aproximarão de nenhuma de minhas coisas sagradas e das minhas ofertas santíssimas; carregarão a vergonha de suas práticas repugnantes.

[[v26-44-14]]

^<<v26-44-14,14>>^ Contudo, eu os encarregarei dos deveres do templo e de todo o trabalho que nele deve ser feito.

[[v26-44-15]]

^<<v26-44-15,15>>^ " ‘Contudo, os sacerdotes levitas e descendentes de Zadoque e que fielmente executaram os deveres do meu santuário quando os israelitas se desviaram de mim, se aproximarão para ministrar diante de mim; eles ficarão diante de mim para oferecer sacrifícios de gordura e de sangue, palavra do Soberano Senhor.

[[v26-44-16]]

^<<v26-44-16,16>>^ Só eles entrarão em meu santuário e se aproximarão da minha mesa para ministrar diante de mim e realizar o meu serviço.

[[v26-44-17]]

^<<v26-44-17,17>>^ " ‘Quando entrarem pelas portas do pátio interno, estejam vestindo roupas de linho; não usem nenhuma veste de lã enquanto estiverem ministrando junto às portas do pátio interno ou dentro do templo.

[[v26-44-18]]

^<<v26-44-18,18>>^ Usarão turbantes de linho na cabeça e calções de linho na cintura. Não vestirão nada que os faça transpirar.

[[v26-44-19]]

^<<v26-44-19,19>>^ Quando saírem para o pátio externo onde fica o povo, tirarão as roupas com que estiveram ministrando e as deixarão nos quartos sagrados, e vestirão outras roupas, para que não consagrem o povo por meio de suas roupas sacerdotais.

[[v26-44-20]]

^<<v26-44-20,20>>^ " ‘Não raparão a cabeça nem deixarão o cabelo comprido, mas o manterão aparado.

[[v26-44-21]]

^<<v26-44-21,21>>^ Nenhum sacerdote beberá vinho quando entrar no pátio interno.

[[v26-44-22]]

^<<v26-44-22,22>>^ Eles não se casarão com viúva ou divorciada; só poderão casar-se com mulher virgem, de ascendência israelita, ou com viúva de sacerdote.

[[v26-44-23]]

^<<v26-44-23,23>>^ Eles ensinarão ao meu povo a diferença entre o santo e o comum e lhe mostrarão como fazer distinção entre o puro e o impuro.

[[v26-44-24]]

^<<v26-44-24,24>>^ " ‘Em qualquer disputa, os sacerdotes servirão como juízes e a decisão será tomada de acordo com as minhas sentenças. Eles obedecerão às minhas leis e aos meus decretos com respeito a todas as minhas festas fixas, e manterão santos os meus sábados.

[[v26-44-25]]

^<<v26-44-25,25>>^ " ‘O sacerdote não se contaminará por aproximar-se do cadáver de alguém; no entanto, se o morto for seu pai, sua mãe, seu filho, sua filha, seu irmão ou sua irmã não-casada, ele poderá contaminar-se.

[[v26-44-26]]

^<<v26-44-26,26>>^ Depois de se purificar, esperará sete dias.

[[v26-44-27]]

^<<v26-44-27,27>>^ No dia em que entrar no pátio interno do santuário para ministrar no santuário, ele oferecerá em favor de si mesmo uma oferta pelo pecado, palavra do Soberano Senhor.

[[v26-44-28]]

^<<v26-44-28,28>>^ " ‘Eu serei a única herança dos sacerdotes. Vocês não lhes darão propriedade alguma em Israel; eu serei a sua herança.

[[v26-44-29]]

^<<v26-44-29,29>>^ Eles comerão as ofertas de cereal, as ofertas pelo pecado e as ofertas pela culpa; e tudo o que em Israel for consagrado ao Senhor será deles.

[[v26-44-30]]

^<<v26-44-30,30>>^ O melhor de todos os primeiros frutos e de todas as contribuições que vocês fizerem pertencerá aos sacerdotes. Vocês darão a eles a primeira porção de sua refeição de cereal moído, para que haja bênçãos sobre as suas casas.

[[v26-44-31]]

^<<v26-44-31,31>>^ Os sacerdotes não comerão a carne de aves ou de animais, encontrados mortos ou despedaçados por animais selvagens.

'''

xref:026-ezequiel/026-ezequiel-043.adoc#v26-43-0[&#60; Capítulo Anterior] | <<v26-44-0,Topo>> | xref:026-ezequiel/026-ezequiel-045.adoc#v26-45-0[Próximo Capítulo &#62;]