include::./index.adoc[]

[[v26-45-0]]
=== Ezequiel, 45
// nvi ?, NVI - Nova Versão Internacional

[[v26-45-1]]

^<<v26-45-1,1>>^ " ‘Quando vocês distribuírem a terra como herança, apresentem ao Senhor como distrito sagrado uma porção da terra, com doze quilômetros e meio de comprimento e dez quilômetros de largura; toda essa área será santa.

[[v26-45-2]]

^<<v26-45-2,2>>^ Desse terreno, uma área quadrada de duzentos e cinqüenta metros de lado servirá para o santuário, com vinte e cinco metros em redor para terreno aberto.

[[v26-45-3]]

^<<v26-45-3,3>>^ No distrito sagrado, separe um pedaço de doze quilômetros e meio de comprimento e cinco quilômetros de largura. Nele estará o santuário, o Lugar Santíssimo.

[[v26-45-4]]

^<<v26-45-4,4>>^ Essa será a porção sagrada da terra para os sacerdotes, os quais ministrarão no santuário e se aproximarão para ministrar diante do Senhor. Esse será um lugar para as suas casas, bem como um lugar santo para o santuário.

[[v26-45-5]]

^<<v26-45-5,5>>^ Uma área de doze quilômetros e meio de comprimento e cinco quilômetros de largura pertencerá aos levitas, os quais servirão no templo; essa será a propriedade deles para ali viverem.

[[v26-45-6]]

^<<v26-45-6,6>>^ " ‘Vocês darão, para que seja propriedade da cidade, uma área de dois quilômetros e meio de largura e doze quilômetros e meio de comprimento, adjacente à porção sagrada; ela pertencerá a toda a nação de Israel.

[[v26-45-7]]

^<<v26-45-7,7>>^ " ‘O príncipe terá a terra que fica dos dois lados da área formada pelo distrito sagrado e pela propriedade da cidade. Ela se estenderá para o oeste desde o lado oeste e para o leste desde o lado leste, indo desde a fronteira ocidental até a fronteira oriental que é paralela a uma das porções tribais.

[[v26-45-8]]

^<<v26-45-8,8>>^ Essa terra será sua propriedade em Israel. E os meus príncipes não oprimirão mais o meu povo, mas permitirão que a nação de Israel possua a terra de acordo com as suas tribos.

[[v26-45-9]]

^<<v26-45-9,9>>^ " ‘Assim diz o Soberano Senhor: Vocês já foram muito longe, ó príncipes de Israel! Abandonem a violência e a opressão e façam o que é justo e direito. Parem de apossar-se do que é do meu povo, palavra do Soberano Senhor.

[[v26-45-10]]

^<<v26-45-10,10>>^ Usem balanças honestas, arroba honesta e pote honesto.

[[v26-45-11]]

^<<v26-45-11,11>>^ A arroba e o pote devem ser iguais, o pote terá um décimo de um barril; o barril deve ser a medida padrão para os dois.

[[v26-45-12]]

^<<v26-45-12,12>>^ O peso padrão deve consistir de doze gramas. Vinte pesos mais vinte e cinco pesos mais quinze pesos equivalem a setecentos e vinte gramas.

[[v26-45-13]]

^<<v26-45-13,13>>^ " ‘Esta é a oferta sagrada que vocês apresentarão: um sexto de uma arroba de cada barril de trigo e um sexto de uma arroba de cada barril de cevada.

[[v26-45-14]]

^<<v26-45-14,14>>^ A porção prescrita de azeite, medida pelo pote, é de um décimo de pote de cada tonel, o qual consiste de dez potes ou um barril, pois dez potes equivalem a um barril.

[[v26-45-15]]

^<<v26-45-15,15>>^ Também se deve tomar uma ovelha de cada rebanho de duzentas ovelhas das pastagens bem regadas de Israel. Isso será usado para as ofertas de cereal, os holocaustos e as ofertas de comunhão para fazer propiciação pelo povo, palavra do Soberano Senhor.

[[v26-45-16]]

^<<v26-45-16,16>>^ Todo o povo da terra participará nessa oferta sagrada para o uso do príncipe em Israel.

[[v26-45-17]]

^<<v26-45-17,17>>^ Será dever do príncipe fornecer os holocaustos, as ofertas de cereal e as ofertas derramadas nas festas, nas luas novas e nos sábados, em todas as festas fixas da nação de Israel. Ele fornecerá as ofertas pelo pecado, as ofertas de cereal, os holocaustos e as ofertas de comunhão para fazer propiciação em favor da nação de Israel.

[[v26-45-18]]

^<<v26-45-18,18>>^ " ‘Assim diz o Soberano Senhor: No primeiro dia do primeiro mês você apanhará um novilho sem defeito e purificará o santuário.

[[v26-45-19]]

^<<v26-45-19,19>>^ O sacerdote apanhará um pouco do sangue da oferta pelo pecado e o colocará nos batentes do templo, nos quatro cantos da saliência superior do altar e nos batentes do pátio interno.

[[v26-45-20]]

^<<v26-45-20,20>>^ Você fará o mesmo no dia sete do mês em favor de qualquer pessoa que pecar sem intenção ou por ignorância; assim vocês deverão fazer propiciação em favor do templo.

[[v26-45-21]]

^<<v26-45-21,21>>^ " ‘No dia catorze do primeiro mês vocês observarão a Páscoa, uma festa de sete dias, na qual vocês comerão pão sem fermento.

[[v26-45-22]]

^<<v26-45-22,22>>^ Naquele dia o príncipe fornecerá um novilho em favor de si mesmo e de todo o povo da terra como oferta pelo pecado.

[[v26-45-23]]

^<<v26-45-23,23>>^ Diariamente, durante os sete dias da festa, ele fornecerá sete novilhos e sete carneiros sem defeito como holocaustos ao Senhor, e um bode como oferta pelo pecado.

[[v26-45-24]]

^<<v26-45-24,24>>^ Ele fornecerá como oferta de cereal, uma arroba para cada novilho e uma arroba para cada carneiro, juntamente com um galão de azeite para cada arroba.

[[v26-45-25]]

^<<v26-45-25,25>>^ " ‘Durante os sete dias da festa, que começa no dia quinze do sétimo mês, ele trará as mesmas dádivas para ofertas pelo pecado, os holocaustos, e as ofertas de cereal e azeite.

'''

xref:026-ezequiel/026-ezequiel-044.adoc#v26-44-0[&#60; Capítulo Anterior] | <<v26-45-0,Topo>> | xref:026-ezequiel/026-ezequiel-046.adoc#v26-46-0[Próximo Capítulo &#62;]