include::./index.adoc[]

[[v26-30-0]]
=== Ezequiel, 30
// nvi ?, NVI - Nova Versão Internacional

[[v26-30-1]]

^<<v26-30-1,1>>^ Esta palavra do Senhor veio a mim:

[[v26-30-2]]

^<<v26-30-2,2>>^ "Filho do homem, profetize e diga: ‘Assim diz o Soberano Senhor: " ‘Clamem e digam: "Ai! Aquele dia! "

[[v26-30-3]]

^<<v26-30-3,3>>^ Pois o dia está próximo, o dia do Senhor está próximo; será dia de nuvens, uma época de condenação para as nações.

[[v26-30-4]]

^<<v26-30-4,4>>^ A espada virá contra o Egito, e angústia virá sobre a Etiópia. Quando os mortos caírem no Egito, sua riqueza lhe será tirada e os seus alicerces serão despedaçados.

[[v26-30-5]]

^<<v26-30-5,5>>^ A Etiópia e Fute, Lude e toda a Arábia, a Líbia e o povo da terra da aliança cairão pela espada junto com o Egito.

[[v26-30-6]]

^<<v26-30-6,6>>^ " ‘Assim diz o Senhor: " ‘Os aliados do Egito cairão, e a sua orgulhosa força fracassará. Desde Migdol até Sevene eles cairão pela espada, palavra do Soberano Senhor’ ".

[[v26-30-7]]

^<<v26-30-7,7>>^ " ‘Serão arrasados no meio de terras devastadas, e as suas cidades jazerão no meio de cidades em ruínas.

[[v26-30-8]]

^<<v26-30-8,8>>^ E eles saberão que eu sou o Senhor, quando eu incendiar o Egito e todos os que o apóiam forem esmagados.

[[v26-30-9]]

^<<v26-30-9,9>>^ " ‘Naquele dia de mim partirão mensageiros em navios para assustar o povo da Etiópia, que se sente seguro. A angústia se apoderará deles no dia da condenação do Egito, pois é certo que isso acontecerá.

[[v26-30-10]]

^<<v26-30-10,10>>^ " ‘Assim diz o Soberano Senhor: " ‘Darei fim à população do Egito pelas mãos do rei Nabucodonosor da Babilônia.

[[v26-30-11]]

^<<v26-30-11,11>>^ Ele e o seu exército, a nação mais impiedosa, serão levados para destruir a terra. Eles empunharão a espada contra o Egito e a terra ficará cheia de mortos.

[[v26-30-12]]

^<<v26-30-12,12>>^ Eu secarei os regatos do Nilo e venderei a terra a homens maus; pela mão de estrangeiros deixarei arrasada a terra e tudo o que nela há. Eu, o Senhor, falei.

[[v26-30-13]]

^<<v26-30-13,13>>^ " ‘Assim diz o Soberano Senhor: " ‘Destruirei os ídolos e darei fim às imagens que há em Mênfis. Não haverá mais príncipe no Egito, e espalharei medo por toda a terra.

[[v26-30-14]]

^<<v26-30-14,14>>^ Arrasarei o alto Egito, incendiarei Zoa e infligirei castigo a Tebas.

[[v26-30-15]]

^<<v26-30-15,15>>^ Derramarei a minha ira sobre Pelúsio, a fortaleza do Egito, e acabarei com a população de Tebas.

[[v26-30-16]]

^<<v26-30-16,16>>^ Incendiarei o Egito; Pelúsio se contorcerá de agonia. Tebas será levada pela tempestade; Mênfis estará em constante aflição.

[[v26-30-17]]

^<<v26-30-17,17>>^ Os jovens de Heliópolis e de Bubastis cairão pela espada, e a população das cidades irão para o cativeiro.

[[v26-30-18]]

^<<v26-30-18,18>>^ As trevas imperarão em pleno dia em Tafnes quando eu quebrar o jugo do Egito; ali sua força orgulhosa chegará a um fim. Ficará coberta de nuvens, e os moradores dos seus povoados irão para o cativeiro.

[[v26-30-19]]

^<<v26-30-19,19>>^ Assim eu trarei castigo ao Egito, e todos ali saberão que eu sou o Senhor. ’ "

[[v26-30-20]]

^<<v26-30-20,20>>^ No sétimo dia do primeiro mês do décimo primeiro ano, a palavra do Senhor veio a mim:

[[v26-30-21]]

^<<v26-30-21,21>>^ "Filho do homem, quebrei o braço do faraó, rei do Egito. Não foi enfaixado para sarar nem lhe foi posta uma tala para fortalecê-lo o bastante para poder manejar a espada.

[[v26-30-22]]

^<<v26-30-22,22>>^ Portanto, assim diz o Soberano Senhor: Estou contra o faraó, rei do Egito. Quebrarei os seus dois braços, o bom e o que já foi quebrado, e farei a espada cair da sua mão.

[[v26-30-23]]

^<<v26-30-23,23>>^ Dispersarei os egípcios entre as nações e os espalharei entre os povos.

[[v26-30-24]]

^<<v26-30-24,24>>^ Fortalecerei os braços do rei da Babilônia e porei a minha espada nas mãos dele, mas quebrarei os braços do faraó, e este gemerá diante dele como um homem mortalmente ferido.

[[v26-30-25]]

^<<v26-30-25,25>>^ Fortalecerei os braços do rei da Babilônia, mas os braços do faraó penderão sem firmeza. Quando eu puser minha espada na mão do rei da Babilônia e ele a brandir contra o Egito, eles saberão que eu sou o Senhor.

[[v26-30-26]]

^<<v26-30-26,26>>^ Eu dispersarei os egípcios no meio das nações e os espalharei entre os povos. Então eles saberão que eu sou o Senhor".

'''

xref:026-ezequiel/026-ezequiel-029.adoc#v26-29-0[&#60; Capítulo Anterior] | <<v26-30-0,Topo>> | xref:026-ezequiel/026-ezequiel-031.adoc#v26-31-0[Próximo Capítulo &#62;]