include::./index.adoc[]

[[v26-10-0]]
=== Ezequiel, 10
// nvi ?, NVI - Nova Versão Internacional

[[v26-10-1]]

^<<v26-10-1,1>>^ Olhei e vi algo semelhante a um trono de safira sobre a abóbada que estava por cima das cabeças dos querubins.

[[v26-10-2]]

^<<v26-10-2,2>>^ O Senhor disse ao homem vestido de linho: "Vá entre as rodas por baixo dos querubins. Encha as mãos com brasas ardentes de entre os querubins e espalhe-as sobre a cidade". E, enquanto eu observava, ele foi.

[[v26-10-3]]

^<<v26-10-3,3>>^ Ora, os querubins estavam no lado sul do templo quando o homem entrou, e uma nuvem encheu o pátio interno.

[[v26-10-4]]

^<<v26-10-4,4>>^ Então a glória do Senhor levantou-se de cima dos querubins e moveu-se para a entrada do templo. A nuvem encheu o templo, e o pátio foi tomado pelo resplendor da glória do Senhor.

[[v26-10-5]]

^<<v26-10-5,5>>^ O som das asas dos querubins podia ser ouvido até no pátio externo, como a voz do Deus Todo-poderoso, quando ele fala.

[[v26-10-6]]

^<<v26-10-6,6>>^ Quando o Senhor ordenou ao homem vestido de linho: "Apanhe fogo do meio das rodas, do meio dos querubins", o homem foi e colocou-se ao lado de uma roda.

[[v26-10-7]]

^<<v26-10-7,7>>^ Então um dos querubins estendeu a mão no fogo que estava no meio deles. Apanhou algumas brasas e as colocou nas mãos do homem vestido de linho, que as recebeu e saiu.

[[v26-10-8]]

^<<v26-10-8,8>>^ ( Debaixo das asas dos querubins podia-se ver o que se parecia com mãos humanas. )

[[v26-10-9]]

^<<v26-10-9,9>>^ Olhei e vi ao lado dos querubins quatro rodas, uma ao lado de cada um dos querubins; as rodas reluziam como berilo.

[[v26-10-10]]

^<<v26-10-10,10>>^ Quanto à sua aparência, eram iguais, e cada uma parecia estar entrosada na outra.

[[v26-10-11]]

^<<v26-10-11,11>>^ Enquanto se moviam, elas iam em qualquer uma das quatro direções que tomavam os querubins; as rodas não se viravam enquanto os querubins se moviam. Eles seguiam qualquer direção à sua frente, sem se virar.

[[v26-10-12]]

^<<v26-10-12,12>>^ Seus corpos, inclusive as costas, as mãos e as asas, estavam completamente cheios de olhos, como as suas quatro rodas.

[[v26-10-13]]

^<<v26-10-13,13>>^ Ouvi que chamavam às rodas, "rodas rotatórias".

[[v26-10-14]]

^<<v26-10-14,14>>^ Cada um dos querubins tinha quatro rostos: Um rosto era o de um querubim, o segundo, de um homem, o terceiro, de um leão, e o quarto, de uma águia.

[[v26-10-15]]

^<<v26-10-15,15>>^ Então os querubins se elevaram. Eram os mesmos seres viventes que eu tinha visto junto ao rio Quebar.

[[v26-10-16]]

^<<v26-10-16,16>>^ Quando os querubins se moviam, as rodas ao lado deles se moviam; e, quando os querubins estendiam as asas para erguer-se do chão, as rodas também iam com eles.

[[v26-10-17]]

^<<v26-10-17,17>>^ Quando os querubins se mantinham imóveis, elas também ficavam imóveis; e, quando os querubins se levantavam, elas se levantavam com eles, porque o espírito dos seres viventes estava nelas.

[[v26-10-18]]

^<<v26-10-18,18>>^ Então a glória do Senhor afastou-se da entrada do templo e parou sobre os querubins.

[[v26-10-19]]

^<<v26-10-19,19>>^ Enquanto eu observava, os querubins estenderam as asas e se ergueram do chão, e as rodas foram com eles. Eles pararam à entrada da porta oriental do templo do Senhor, e a glória do Deus de Israel estava sobre eles.

[[v26-10-20]]

^<<v26-10-20,20>>^ Esses seres viventes eram os mesmos que eu vi debaixo do Deus de Israel junto ao rio Quebar, e percebi que eles eram querubins.

[[v26-10-21]]

^<<v26-10-21,21>>^ Cada um tinha quatro rostos e quatro asas, e debaixo de suas asas havia o que pareciam mãos humanas.

[[v26-10-22]]

^<<v26-10-22,22>>^ Seus rostos tinham a mesma aparência daqueles que eu tinha visto junto ao rio Quebar. Todos iam sempre para a frente.

'''

xref:026-ezequiel/026-ezequiel-009.adoc#v26-9-0[&#60; Capítulo Anterior] | <<v26-10-0,Topo>> | xref:026-ezequiel/026-ezequiel-011.adoc#v26-11-0[Próximo Capítulo &#62;]