include::./index.adoc[]

[[v26-37-0]]
=== Ezequiel, 37
// nvi ?, NVI - Nova Versão Internacional

[[v26-37-1]]

^<<v26-37-1,1>>^ A mão do Senhor estava sobre mim, e por seu Espírito ele me levou a um vale cheio de ossos.

[[v26-37-2]]

^<<v26-37-2,2>>^ Ele me levou de um lado para outro, e pude ver que era enorme o número de ossos no vale, e que os ossos estavam muito secos.

[[v26-37-3]]

^<<v26-37-3,3>>^ Ele me perguntou: "Filho do homem, esses ossos poderão tornar a viver? " Eu respondi: "Ó Soberano Senhor, só tu o sabes".

[[v26-37-4]]

^<<v26-37-4,4>>^ Então ele me disse: "Profetize a esses ossos e diga-lhes: ‘Ossos secos, ouçam a palavra do Senhor!

[[v26-37-5]]

^<<v26-37-5,5>>^ Assim diz o Soberano Senhor a estes ossos: Farei um espírito entrar em vocês, e vocês terão vida.

[[v26-37-6]]

^<<v26-37-6,6>>^ Porei tendões em vocês e farei aparecer carne sobre vocês e os cobrirei com pele; porei um espírito em vocês, e vocês terão vida. Então vocês saberão que eu sou o Senhor’ ".

[[v26-37-7]]

^<<v26-37-7,7>>^ E eu profetizei conforme a ordem recebida. E, enquanto profetizava, houve um barulho, um som de chocalho, e os ossos se juntaram, osso com osso.

[[v26-37-8]]

^<<v26-37-8,8>>^ Olhei, e os ossos foram cobertos de tendões e de carne, e depois de pele, mas não havia espírito neles.

[[v26-37-9]]

^<<v26-37-9,9>>^ A seguir ele me disse: "Profetize ao espírito; profetize, filho do homem, e diga-lhe: ‘Assim diz o Soberano Senhor: Venha desde os quatro ventos, ó espírito, e sopre dentro desses mortos, para que vivam’ ".

[[v26-37-10]]

^<<v26-37-10,10>>^ Profetizei conforme a ordem recebida, e o espírito entrou neles; eles receberam vida e se puseram de pé. Era um exército enorme!

[[v26-37-11]]

^<<v26-37-11,11>>^ Então ele me disse: "Filho do homem, esses ossos são toda a nação de Israel. Eles dizem: ‘Nossos ossos se secaram e nossa esperança se foi; fomos exterminados’.

[[v26-37-12]]

^<<v26-37-12,12>>^ Por isso profetize e diga-lhes: ‘Assim diz o Soberano Senhor: Ó meu povo, vou abrir os seus túmulos e fazê-los sair; trarei vocês de volta à terra de Israel.

[[v26-37-13]]

^<<v26-37-13,13>>^ E, quando eu abrir os seus túmulos e os fizer sair, vocês, meu povo, saberão que eu sou o Senhor.

[[v26-37-14]]

^<<v26-37-14,14>>^ Porei o meu Espírito em vocês, e vocês viverão, e eu os estabelecerei em sua própria terra. Então vocês saberão que eu, o Senhor, falei, e o fiz seus companheiros, palavra do Senhor’ ".

[[v26-37-15]]

^<<v26-37-15,15>>^ Esta palavra do Senhor veio a mim:

[[v26-37-16]]

^<<v26-37-16,16>>^ "Filho do homem, escreva num pedaço de madeira: ‘Pertencente a Judá e aos israelitas, seus companheiros’. Depois escreva noutro pedaço de madeira: ‘Vara de Efraim, pertencente a José e a toda a nação de Israel, seus companheiros’.

[[v26-37-17]]

^<<v26-37-17,17>>^ Junte-os numa única vara para que se tornem uma só em sua mão.

[[v26-37-18]]

^<<v26-37-18,18>>^ "Quando os seus compatriotas lhe perguntarem: ‘Você não vai nos dizer o que isso significa? ’

[[v26-37-19]]

^<<v26-37-19,19>>^ Diga-lhes: ‘Assim diz o Soberano Senhor: Vou apanhar a vara pertencente a José, que está na mão de Efraim, e às tribos israelitas, seus companheiros, e juntá-la com a vara de Judá, fazendo delas um único pedaço de madeira, e elas se tornarão uma só na minha mão’.

[[v26-37-20]]

^<<v26-37-20,20>>^ Segure diante dos olhos deles os pedaços de madeira em que você escreveu

[[v26-37-21]]

^<<v26-37-21,21>>^ e diga-lhes: ‘Assim diz o Soberano Senhor: Tirarei os israelitas das nações para onde foram. Vou ajuntá-los de todos os lugares ao redor e trazê-los de volta à sua própria terra.

[[v26-37-22]]

^<<v26-37-22,22>>^ Eu os farei uma única nação na terra, nos montes de Israel. Haverá um único rei sobre todos eles, e eles nunca mais serão duas nações nem estarão divididos em dois reinos.

[[v26-37-23]]

^<<v26-37-23,23>>^ Não se contaminarão mais com seus ídolos e imagens detestáveis nem com nenhuma de suas transgressões, pois eu os salvarei de todas as suas apostasias pecaminosas, e os purificarei. Eles serão o meu povo, e eu serei o seu Deus.

[[v26-37-24]]

^<<v26-37-24,24>>^ " ‘O meu servo Davi será rei sobre eles, e todos eles terão um só pastor. Eles seguirão as minhas leis e terão o cuidado de obedecer aos meus decretos.

[[v26-37-25]]

^<<v26-37-25,25>>^ Viverão na terra que dei ao meu servo Jacó, a terra onde os seus antepassados viveram. Eles e os seus filhos e os filhos de seus filhos viverão ali para sempre, e o meu servo Davi será o seu líder para sempre.

[[v26-37-26]]

^<<v26-37-26,26>>^ Farei uma aliança de paz com eles; será uma aliança eterna. Eu os firmarei e os multiplicarei, e porei o meu santuário no meio deles para sempre.

[[v26-37-27]]

^<<v26-37-27,27>>^ Minha morada estará com eles; eu serei o seu Deus, e eles serão o meu povo.

[[v26-37-28]]

^<<v26-37-28,28>>^ Então, quando o meu santuário estiver entre eles para sempre, as nações saberão que eu, o Senhor, santifico Israel’ ".

'''

xref:026-ezequiel/026-ezequiel-036.adoc#v26-36-0[&#60; Capítulo Anterior] | <<v26-37-0,Topo>> | xref:026-ezequiel/026-ezequiel-038.adoc#v26-38-0[Próximo Capítulo &#62;]