include::./index.adoc[]

[[v26-40-0]]
=== Ezequiel, 40
// nvi ?, NVI - Nova Versão Internacional

[[v26-40-1]]

^<<v26-40-1,1>>^ No vigésimo quinto ano do exílio, no início do ano, no décimo dia do mês, no décimo quarto ano depois da queda da cidade, naquele exato dia a mão do Senhor esteve sobre mim e ele me levou para lá.

[[v26-40-2]]

^<<v26-40-2,2>>^ Em visões de Deus ele me levou a Israel e me pôs num monte muito alto, em cujo lado sul estavam alguns prédios que tinham a aparência de uma cidade.

[[v26-40-3]]

^<<v26-40-3,3>>^ Ele me levou para lá, e eu vi um homem que parecia de bronze; ele estava de pé junto à entrada, com uma corda de linho e uma vara de medir na mão.

[[v26-40-4]]

^<<v26-40-4,4>>^ E ele me disse: "Filho do homem, fixe bem os olhos e procure ouvir bem, e preste atenção a tudo o que vou lhe mostrar, pois por isso você foi trazido aqui. Conte à nação de Israel tudo o que você vai ver".

[[v26-40-5]]

^<<v26-40-5,5>>^ Vi um muro que cercava completamente a área do templo. O comprimento da vara de medir na mão do homem era de seis medidas longas, cada uma com meio metro. Ele mediu o muro, que tinha três metros de espessura e três de altura.

[[v26-40-6]]

^<<v26-40-6,6>>^ Depois ele foi até a porta que dá para o oriente. Subiu os seus degraus e mediu a soleira da porta, que tinha três metros de fundo.

[[v26-40-7]]

^<<v26-40-7,7>>^ As salas dos guardas tinham três metros de comprimento e três metros de largura, e as paredes entre elas tinham dois metros e meio de espessura. E a soleira da porta junto ao pórtico, defronte ao templo, tinha três metros de fundo.

[[v26-40-8]]

^<<v26-40-8,8>>^ Depois ele mediu o pórtico,

[[v26-40-9]]

^<<v26-40-9,9>>^ que tinha quatro metros de fundo e seus batentes tinham um metro de espessura. O pórtico estava voltado para o templo.

[[v26-40-10]]

^<<v26-40-10,10>>^ Da porta oriental para dentro havia três salas de cada lado; as três tinham as mesmas medidas, e as faces das paredes salientes de cada lado tinham as mesmas medidas.

[[v26-40-11]]

^<<v26-40-11,11>>^ A seguir ele mediu a largura da porta, à entrada; era de cinco metros, e seu comprimento era de seis metros e meio.

[[v26-40-12]]

^<<v26-40-12,12>>^ Defronte de cada sala havia um muro de meio metro de altura, e os nichos eram quadrados, com três metros em cada lado.

[[v26-40-13]]

^<<v26-40-13,13>>^ Depois ele mediu a entrada a partir do alto da parte de trás do muro de uma sala até o alto da sala oposta; a distância era de doze metros e meio, da abertura de um parapeito até a abertura do parapeito oposto.

[[v26-40-14]]

^<<v26-40-14,14>>^ E mediu ao longo das faces das paredes salientes por todo o interior da entrada; eram trinta metros. A medida era até ao pórtico que dá para o pátio.

[[v26-40-15]]

^<<v26-40-15,15>>^ A distância desde a entrada da porta até a extremidade do seu pórtico era de vinte e cinco metros.

[[v26-40-16]]

^<<v26-40-16,16>>^ As salas e os muros salientes dentro da entrada eram guarnecidos de estreitas aberturas com parapeito ao redor, como o pórtico; as aberturas que os circundavam davam para o interior. As faces dos muros salientes eram decoradas com tamareiras.

[[v26-40-17]]

^<<v26-40-17,17>>^ Depois ele me levou ao pátio externo. Ali eu vi alguns quartos e um piso que havia sido construído ao redor de todo o pátio; ali havia trinta quartos ao longo de todo o piso.

[[v26-40-18]]

^<<v26-40-18,18>>^ Era adjacente às laterais das entradas e sua largura era igual ao comprimento; esse era o piso inferior.

[[v26-40-19]]

^<<v26-40-19,19>>^ A seguir ele mediu a distância do interior da entrada inferior até o exterior do pátio interno, o que deu cinqüenta metros, tanto no lado leste como no lado norte.

[[v26-40-20]]

^<<v26-40-20,20>>^ Mediu depois o comprimento e a largura da porta que dá para o norte, que dá para o pátio externo.

[[v26-40-21]]

^<<v26-40-21,21>>^ Seus compartimentos, três de cada lado, suas paredes salientes e seu pórtico tinham as mesmas medidas dos da primeira entrada. Tinham vinte e cinco metros de comprimento e doze metros e meio de largura.

[[v26-40-22]]

^<<v26-40-22,22>>^ Suas aberturas, seu pórtico e sua decoração com tamareiras tinham as mesmas medidas dos da porta que dava para o oriente. Sete degraus subiam até ela, e o seu pórtico ficava no lado oposto a eles.

[[v26-40-23]]

^<<v26-40-23,23>>^ Havia uma porta que abria o pátio interno e que dava para a porta norte, como também uma que dava para a porta leste. Ele mediu de uma porta à porta oposta; eram cinqüenta metros.

[[v26-40-24]]

^<<v26-40-24,24>>^ Depois ele me levou para o lado sul, e eu vi uma porta que dava para o sul. Ele mediu seus batentes e seu pórtico, e eles tinham as mesmas medidas das outras portas.

[[v26-40-25]]

^<<v26-40-25,25>>^ A entrada e o pórtico tinham aberturas estreitas ao seu redor, como as aberturas das outras. Tinham vinte e cinco metros de comprimento e doze metros e meio de largura.

[[v26-40-26]]

^<<v26-40-26,26>>^ Sete degraus subiam até ela, e o seu pórtico ficava no lado oposto a eles; havia uma decoração de tamareiras nas faces dos muros salientes em cada lado.

[[v26-40-27]]

^<<v26-40-27,27>>^ O pátio interior também tinha uma porta que dava para o sul, e ele mediu desde essa porta até a porta externa no lado sul; eram cinqüenta metros.

[[v26-40-28]]

^<<v26-40-28,28>>^ A seguir ele me levou ao pátio interno pela porta sul, e mediu a porta sul; e ela tinha as mesmas medidas das outras.

[[v26-40-29]]

^<<v26-40-29,29>>^ Suas salas, seus muros salientes e seu pórtico tinham as mesmas medidas dos outros. A entrada e seu pórtico tinha aberturas ao seu redor. Tinham vinte e cinco metros de comprimento e doze metros e meio de largura.

[[v26-40-30]]

^<<v26-40-30,30>>^ ( Os pórticos das entradas ao redor do pátio interior tinham doze metros e meio de largura e dois metros e meio de fundo. )

[[v26-40-31]]

^<<v26-40-31,31>>^ Seu pórtico dava para o pátio externo; tamareiras decoravam seus batentes, e oito degraus subiam até ele.

[[v26-40-32]]

^<<v26-40-32,32>>^ Depois ele me levou ao pátio interno no lado leste, e mediu a entrada; e ela tinha as mesmas medidas das outras.

[[v26-40-33]]

^<<v26-40-33,33>>^ Suas salas, suas paredes salientes e seu pórtico tinham as mesmas medidas dos outros. A entrada e seu pórtico tinha aberturas ao seu redor. Tinham vinte e cinco metros de comprimento e doze metros e meio de largura.

[[v26-40-34]]

^<<v26-40-34,34>>^ Seu pórtico dava para o pátio externo; tamareiras decoravam os batentes em cada lado, e oito degraus subiam até ela.

[[v26-40-35]]

^<<v26-40-35,35>>^ Depois ele me levou à porta norte e a mediu; e ela tinha as mesmas medidas das outras,

[[v26-40-36]]

^<<v26-40-36,36>>^ como também as suas salas, as suas paredes salientes e o seu pórtico, e tinha aberturas ao seu redor. Tinha vinte e cinco metros de comprimento e doze metros e meio de largura.

[[v26-40-37]]

^<<v26-40-37,37>>^ Seu pórtico dava para o pátio externo; tamareiras decoravam os batentes em ambos os lados, e oito degraus subiam até ela.

[[v26-40-38]]

^<<v26-40-38,38>>^ Um quarto com sua entrada ficava junto do pórtico de cada uma das entradas internas, onde os holocaustos eram lavados.

[[v26-40-39]]

^<<v26-40-39,39>>^ No pórtico da entrada havia duas mesas de cada lado, em que os holocaustos, as ofertas pelo pecado e as ofertas pela culpa eram abatidos.

[[v26-40-40]]

^<<v26-40-40,40>>^ Junto à parede externa do pórtico da entrada, perto dos degraus da porta norte, ficavam duas mesas, e do outro lado dos degraus havia duas mesas.

[[v26-40-41]]

^<<v26-40-41,41>>^ Havia, pois, quatro mesas num lado da entrada e quatro no outro, onde os sacrifícios eram abatidos. Eram oito mesas ao todo.

[[v26-40-42]]

^<<v26-40-42,42>>^ Também havia quatro mesas de pedra lavrada para os holocaustos, cada uma com setenta e cinco centímetros de comprimento e de largura, e cinqüenta centímetros de altura. Nelas eram colocados os utensílios para o abate dos holocaustos e dos outros sacrifícios.

[[v26-40-43]]

^<<v26-40-43,43>>^ E ganchos de duas pontas, cada um com quatro dedos de comprimento, estavam presos à parede, em toda a sua extensão. As mesas eram para a carne das ofertas.

[[v26-40-44]]

^<<v26-40-44,44>>^ Fora da porta interna, dentro do pátio interno, havia dois quartos, um ao lado da porta norte que dava para o sul, e outro ao lado da porta sul que dava para o norte.

[[v26-40-45]]

^<<v26-40-45,45>>^ Ele me disse: "O quarto que dá para o sul é para os sacerdotes encarregados do templo,

[[v26-40-46]]

^<<v26-40-46,46>>^ e o quarto que dá para o norte é para os sacerdotes encarregados do altar. São eles os filhos de Zadoque, os únicos levitas que podem aproximar-se do Senhor para ministrarem diante dele".

[[v26-40-47]]

^<<v26-40-47,47>>^ Depois ele mediu o pátio: Era quadrado e tinha cinqüenta metros de comprimento e cinqüenta de largura. E o altar ficava em frente do templo.

[[v26-40-48]]

^<<v26-40-48,48>>^ A seguir me levou ao pórtico do templo e mediu os batentes do pórtico; eles tinham dois metros e meio de largura em ambos os lados. A largura da entrada era de sete metros, e suas paredes salientes tinham um metro e meio de largura em cada lado.

[[v26-40-49]]

^<<v26-40-49,49>>^ O pórtico tinha dez metros de largura e seis metros da frente aos fundos. O acesso a ele era por um lance de escadas, e havia três colunas em cada lado dos batentes.

'''

xref:026-ezequiel/026-ezequiel-039.adoc#v26-39-0[&#60; Capítulo Anterior] | <<v26-40-0,Topo>> | xref:026-ezequiel/026-ezequiel-041.adoc#v26-41-0[Próximo Capítulo &#62;]