include::./index.adoc[]

[[v26-26-0]]
=== Ezequiel, 26
// nvi ?, NVI - Nova Versão Internacional

[[v26-26-1]]

^<<v26-26-1,1>>^ No décimo primeiro ano, no primeiro dia do mês, veio a mim esta palavra do Senhor:

[[v26-26-2]]

^<<v26-26-2,2>>^ "Filho do homem, visto que Tiro falou de Jerusalém: ‘Ah! Ah! O portal das nações está quebrado, e as suas portas se me abriram; agora que ela jaz em ruínas, eu prosperarei’,

[[v26-26-3]]

^<<v26-26-3,3>>^ por essa razão assim diz o Soberano Senhor: Estou contra você, ó Tiro, e trarei muitas nações contra você; virão como o mar quando eleva as suas ondas.

[[v26-26-4]]

^<<v26-26-4,4>>^ Elas destruirão os muros de Tiro e derrubarão suas torres; eu espalharei o seu entulho e farei dela uma rocha nua.

[[v26-26-5]]

^<<v26-26-5,5>>^ Fora, no mar, ela se tornará um local propício para estender redes de pesca, pois eu falei, palavra do Soberano Senhor. Ela se tornará despojo para as nações,

[[v26-26-6]]

^<<v26-26-6,6>>^ e em seus territórios no continente será feita grande destruição pela espada. E saberão que eu sou o Senhor.

[[v26-26-7]]

^<<v26-26-7,7>>^ "Pois assim diz o Soberano Senhor: Do norte vou trazer contra você, Tiro, o rei da Babilônia, Nabucodonosor, rei de reis, com cavalos e carros, com cavaleiros e um grande exército.

[[v26-26-8]]

^<<v26-26-8,8>>^ Ele desfechará com a espada um violento ataque contra os seus territórios no continente. Construirá obras de cerco e uma rampa de acesso aos seus muros. E armará uma barreira de escudos contra você.

[[v26-26-9]]

^<<v26-26-9,9>>^ Ele dirigirá as investidas dos seus aríetes contra os seus muros e com armas de ferro demolirá as suas torres.

[[v26-26-10]]

^<<v26-26-10,10>>^ Seus cavalos serão tantos que cobrirão você de poeira. Seus muros tremerão com o barulho dos cavalos de guerra, das carroças e dos carros, quando ele entrar por suas portas com a facilidade com que se entra numa cidade cujos muros foram derrubados.

[[v26-26-11]]

^<<v26-26-11,11>>^ Os cascos de seus cavalos pisarão em todas as suas ruas; ele matará o seu povo à espada, e as suas resistentes colunas ruirão.

[[v26-26-12]]

^<<v26-26-12,12>>^ Despojarão a sua riqueza e saquearão os seus suprimentos; derrubarão seus muros e demolirão suas lindas casas, e lançarão as suas pedras, o seu madeiramento e todo o entulho ao mar.

[[v26-26-13]]

^<<v26-26-13,13>>^ Porei fim a seus cânticos barulhentos, e não se ouvirá mais a música de suas harpas.

[[v26-26-14]]

^<<v26-26-14,14>>^ Farei de você uma rocha nua, e você se tornará um local propício para estender redes de pesca. Você jamais será reconstruída, pois eu, o Senhor, falei, palavra do Soberano Senhor.

[[v26-26-15]]

^<<v26-26-15,15>>^ "Assim diz o Soberano Senhor a Tiro: Acaso as regiões litorâneas não tremerão ao som de sua queda, quando o ferido gemer e a matança acontecer em seu meio?

[[v26-26-16]]

^<<v26-26-16,16>>^ Então todos os príncipes do litoral descerão do trono e porão de lado seus mantos e tirarão suas roupas bordadas. Vestidos de pavor, se assentarão no chão, tremendo a todo instante, apavorados por sua causa.

[[v26-26-17]]

^<<v26-26-17,17>>^ Depois entoarão um lamento acerca de você e lhe dirão: " ‘Como você está destruída, ó cidade de renome, povoada por homens do mar! Você era um poder nos mares, você e os seus cidadãos; você impunha pavor a todos que ali vivem.

[[v26-26-18]]

^<<v26-26-18,18>>^ Agora as regiões litorâneas tremem no dia de sua queda; as ilhas do mar estão apavoradas diante de sua ruína’.

[[v26-26-19]]

^<<v26-26-19,19>>^ "Assim diz o Soberano Senhor: Quando eu fizer de você uma cidade abandonada, como uma cidade inabitável, e quando eu a cobrir com as vastas águas do abismo,

[[v26-26-20]]

^<<v26-26-20,20>>^ então farei você descer com os que descem à cova, para fazer companhia aos antigos. Eu a farei habitar embaixo da terra, como em ruínas antigas, com aqueles que descem à cova, e você não voltará e não retomará o seu lugar na terra dos viventes.

[[v26-26-21]]

^<<v26-26-21,21>>^ Levarei você a um fim terrível e você já não existirá. Você será procurada, e jamais será achada, palavra do Soberano Senhor".

'''

xref:026-ezequiel/026-ezequiel-025.adoc#v26-25-0[&#60; Capítulo Anterior] | <<v26-26-0,Topo>> | xref:026-ezequiel/026-ezequiel-027.adoc#v26-27-0[Próximo Capítulo &#62;]