include::./index.adoc[]

[[v26-3-0]]
=== Ezequiel, 3
// nvi ?, NVI - Nova Versão Internacional

[[v26-3-1]]

^<<v26-3-1,1>>^ E ele me disse: "Filho do homem, coma este rolo; depois vá falar à nação de Israel".

[[v26-3-2]]

^<<v26-3-2,2>>^ Eu abri a boca, e ele me deu o rolo para eu comer.

[[v26-3-3]]

^<<v26-3-3,3>>^ E acrescentou: "Filho do homem, coma este rolo que estou lhe dando e encha o seu estômago com ele". Então eu o comi, e em minha boca era doce como mel.

[[v26-3-4]]

^<<v26-3-4,4>>^ Depois ele me disse: "Filho do homem, vá agora à nação de Israel e diga-lhe as minhas palavras.

[[v26-3-5]]

^<<v26-3-5,5>>^ Você não está sendo enviado a um povo de fala obscura e de língua difícil, mas à nação de Israel;

[[v26-3-6]]

^<<v26-3-6,6>>^ não irá a muitos povos de fala obscura e de língua difícil, cujas palavras você não conseguiria entender. Certamente, se eu lhes enviasse você, eles o ouviriam.

[[v26-3-7]]

^<<v26-3-7,7>>^ Mas a nação de Israel não vai querer ouvi-lo porque não quer me ouvir, pois toda a nação de Israel está endurecida e obstinada.

[[v26-3-8]]

^<<v26-3-8,8>>^ Mas eu tornarei você tão inflexível e endurecido quanto eles.

[[v26-3-9]]

^<<v26-3-9,9>>^ Tornarei a sua testa como a mais dura das pedras, mais dura que a pederneira. Não tenha medo deles, nem fique apavorado ao vê-los, embora sejam uma nação rebelde".

[[v26-3-10]]

^<<v26-3-10,10>>^ E continuou: "Filho do homem, ouça atentamente e guarde no coração todas as palavras que eu lhe disser.

[[v26-3-11]]

^<<v26-3-11,11>>^ Vá agora aos seus compatriotas que estão no exílio e fale com eles. Diga-lhes, quer ouçam quer deixem de ouvir: Assim diz o Soberano Senhor".

[[v26-3-12]]

^<<v26-3-12,12>>^ Depois o Espírito elevou-me, e ouvi esta estrondosa aclamação: "Que a glória do Senhor seja louvada em sua habitação! "

[[v26-3-13]]

^<<v26-3-13,13>>^ E ouvi o som das asas dos seres viventes, roçando umas nas outras, e, atrás deles, o som das rodas — um forte estrondo!

[[v26-3-14]]

^<<v26-3-14,14>>^ Então o Espírito elevou-me e tirou-me de lá, com o meu espírito cheio de amargura e de ira, e com a forte mão do Senhor sobre mim.

[[v26-3-15]]

^<<v26-3-15,15>>^ Fui aos exilados que moravam em Tel-Abibe, perto do rio Quebar. Lá fiquei entre eles sete dias, atônito!

[[v26-3-16]]

^<<v26-3-16,16>>^ Ao fim dos sete dias a palavra do Senhor veio a mim:

[[v26-3-17]]

^<<v26-3-17,17>>^ "Filho do homem", disse ele, "eu o fiz sentinela para a nação de Israel; por isso ouça a palavra que digo e leve-lhes a minha advertência.

[[v26-3-18]]

^<<v26-3-18,18>>^ Quando eu disser a um ímpio que ele vai morrer, e você não o advertir nem lhe falar para dissuadi-lo dos seus maus caminhos para salvar a vida dele, aquele ímpio morrerá por sua iniqüidade; mas para mim você será responsável pela morte dele.

[[v26-3-19]]

^<<v26-3-19,19>>^ Se, porém, você advertir o ímpio e ele não se desviar de sua impiedade ou dos seus maus caminhos, ele morrerá por sua iniqüidade, mas você estará livre de culpa.

[[v26-3-20]]

^<<v26-3-20,20>>^ "Também, quando um justo se desviar de sua justiça e fizer o mal, e eu puser uma pedra de tropeço diante dele, ele morrerá. Uma vez que você não o advertiu ele morrerá pelo pecado que cometeu. As práticas justas dele não serão lembradas; para mim, porém, você será responsável pela morte dele.

[[v26-3-21]]

^<<v26-3-21,21>>^ Se, porém, você advertir o justo e ele não pecar, certamente ele viverá, porque aceitou a advertência, e você estará livre de culpa".

[[v26-3-22]]

^<<v26-3-22,22>>^ A mão do Senhor esteve ali sobre mim, e ele me disse: "Levante-se e vá para a planície, e lá falarei com você".

[[v26-3-23]]

^<<v26-3-23,23>>^ Então me levantei e fui para a planície. E lá estava a glória do Senhor, glória como a que eu tinha visto junto ao rio Quebar. Prostrei-me, rosto em terra,

[[v26-3-24]]

^<<v26-3-24,24>>^ mas o Espírito entrou em mim e me pôs de pé. Ele me disse: "Vá para casa, e tranque-se.

[[v26-3-25]]

^<<v26-3-25,25>>^ Pois você, filho do homem, será amarrado com cordas; você ficará preso, e não conseguirá sair para o meio do povo.

[[v26-3-26]]

^<<v26-3-26,26>>^ Farei sua língua apegar-se ao céu da boca para que você fique calado e não possa repreendê-los, embora sejam uma nação rebelde.

[[v26-3-27]]

^<<v26-3-27,27>>^ Mas, quando eu falar com você, abrirei sua boca e você lhes dirá: Assim diz o Soberano Senhor. Quem quiser ouvir ouça, e quem não quiser não ouça; pois são uma nação rebelde.

'''

xref:026-ezequiel/026-ezequiel-002.adoc#v26-2-0[&#60; Capítulo Anterior] | <<v26-3-0,Topo>> | xref:026-ezequiel/026-ezequiel-004.adoc#v26-4-0[Próximo Capítulo &#62;]