include::./index.adoc[]

[[v26-41-0]]
=== Ezequiel, 41
// nvi ?, NVI - Nova Versão Internacional

[[v26-41-1]]

^<<v26-41-1,1>>^ Depois o homem me levou ao santuário externo e mediu os batentes; a largura dos batentes era de três metros em cada lado.

[[v26-41-2]]

^<<v26-41-2,2>>^ A entrada tinha cinco metros de largura, e as paredes salientes em cada lado tinham dois metros e meio de largura. Ele mediu também o santuário externo; e ele tinha vinte metros de comprimento e dez metros de largura.

[[v26-41-3]]

^<<v26-41-3,3>>^ Depois entrou no santuário interno e mediu os batentes da entrada; cada um tinha um metro de largura. A entrada tinha três metros de largura, e as paredes salientes em cada lado dela tinham três metros e meio de largura.

[[v26-41-4]]

^<<v26-41-4,4>>^ E ele mediu o comprimento do santuário interno; tinha dez metros, e sua largura era de dez metros até o fim do santuário externo. Ele me disse: "Este é o Lugar Santíssimo".

[[v26-41-5]]

^<<v26-41-5,5>>^ Depois mediu a parede do templo; tinha três metros de espessura, e cada quarto lateral em torno do templo tinha dois metros de largura.

[[v26-41-6]]

^<<v26-41-6,6>>^ Os quartos laterais, sobrepostos uns aos outros, ficavam em três andares, havendo trinta em cada andar. Havia saliências em torno de toda a parede do templo para servirem de pontos de apoio para os quartos laterais, para que não fossem incrustados na parede do templo.

[[v26-41-7]]

^<<v26-41-7,7>>^ As paredes laterais em torno de todo o templo eram mais largas em cada andar superior. A estrutura em torno do templo foi construída em plataformas ascendentes, de modo que os quartos ficavam mais largos à medida que se subia. Uma escada subia do andar inferior até o andar superior, servindo também o andar do meio.

[[v26-41-8]]

^<<v26-41-8,8>>^ Vi que ao redor de todo o templo fora construída uma base, formando o alicerce dos quartos laterais. Era do comprimento da vara de medir, ou seja, três metros.

[[v26-41-9]]

^<<v26-41-9,9>>^ A parede externa dos quartos laterais era de dois metros e meio de espessura. A área aberta entre os quartos laterais do templo

[[v26-41-10]]

^<<v26-41-10,10>>^ e os quartos dos sacerdotes era de dez metros de largura ao redor de todo o templo.

[[v26-41-11]]

^<<v26-41-11,11>>^ Havia entradas para os quartos laterais a partir da área aberta, uma ao norte e outra ao sul; e a base vizinha à área aberta era de dois metros e meio ao redor de todo o templo.

[[v26-41-12]]

^<<v26-41-12,12>>^ O prédio que ficara em frente do pátio do templo no lado oeste media trinta e cinco metros de largura. A parede do prédio tinha dois metros e meio de espessura em toda a sua volta, e o seu comprimento era de quarenta e cinco metros.

[[v26-41-13]]

^<<v26-41-13,13>>^ Depois ele mediu o templo; e ele tinha cinqüenta metros de comprimento, e o pátio do templo e o prédio com suas paredes também tinham cinqüenta metros de comprimento.

[[v26-41-14]]

^<<v26-41-14,14>>^ A largura do pátio do templo no lado oeste, inclusive a frente do templo, era de cinqüenta metros.

[[v26-41-15]]

^<<v26-41-15,15>>^ A seguir ele mediu o comprimento do prédio que ficava em frente do pátio, na parte de trás do templo, inclusive suas galerias em cada lado; era de cinqüenta metros. O santuário externo, o santuário interno e o pórtico que dava para o pátio,

[[v26-41-16]]

^<<v26-41-16,16>>^ bem como as soleiras, as janelas estreitas e as galerias em volta dos três, tudo o que estava do lado de fora, inclusive a soleira, fora revestido de madeira. O piso, a parede até a altura das janelas, e as janelas estavam revestidas.

[[v26-41-17]]

^<<v26-41-17,17>>^ No espaço acima do lado exterior da entrada do santuário interno e nas paredes, a intervalos regulares, em volta de todo o santuário interior e exterior,

[[v26-41-18]]

^<<v26-41-18,18>>^ havia querubins e tamareiras em relevo. As tamareiras alternavam com os querubins. Cada querubim tinha dois rostos:

[[v26-41-19]]

^<<v26-41-19,19>>^ o rosto de um homem virado para a tamareira de um dos lados, e o rosto de um leão virado para a tamareira do outro lado. Estavam em relevo ao redor do templo inteiro.

[[v26-41-20]]

^<<v26-41-20,20>>^ Desde o chão até a área acima da entrada, havia querubins e tamareiras em relevo na parede do santuário exterior.

[[v26-41-21]]

^<<v26-41-21,21>>^ O santuário exterior tinha batentes retangulares, e o que ficava em frente do Lugar Santíssimo era semelhante.

[[v26-41-22]]

^<<v26-41-22,22>>^ Havia um altar de madeira com um metro e meio de altura e um metro em cada lado; seus cantos, sua base e seus lados eram de madeira. O homem me disse: "Esta é a mesa que fica diante do Senhor".

[[v26-41-23]]

^<<v26-41-23,23>>^ Tanto o santuário externo quanto o Lugar Santíssimo tinham portas duplas.

[[v26-41-24]]

^<<v26-41-24,24>>^ Cada porta tinha duas folhas; duas folhas articuladas para cada porta.

[[v26-41-25]]

^<<v26-41-25,25>>^ E nas portas do santuário externo havia querubins e tamareiras esculpidos em relevo, como os que havia nas paredes, e havia também uma saliência de madeira na frente do pórtico.

[[v26-41-26]]

^<<v26-41-26,26>>^ Nas paredes laterais do pórtico havia janelas estreitas com tamareiras em relevo em cada lado. Os quartos laterais do templo também tinham saliências.

'''

xref:026-ezequiel/026-ezequiel-040.adoc#v26-40-0[&#60; Capítulo Anterior] | <<v26-41-0,Topo>> | xref:026-ezequiel/026-ezequiel-042.adoc#v26-42-0[Próximo Capítulo &#62;]