include::./index.adoc[]

[[v26-8-0]]
=== Ezequiel, 8
// nvi ?, NVI - Nova Versão Internacional

[[v26-8-1]]

^<<v26-8-1,1>>^ No quinto dia do sexto mês do sexto ano do exílio, eu e as autoridades de Judá estávamos sentados em minha casa quando a mão do Soberano Senhor veio ali sobre mim.

[[v26-8-2]]

^<<v26-8-2,2>>^ Olhei e vi uma figura como a de um homem. Do que parecia ser a sua cintura para baixo, ele era como fogo, e dali para cima sua aparência era tão brilhante como metal reluzente.

[[v26-8-3]]

^<<v26-8-3,3>>^ Ele estendeu o que parecia um braço e pegou-me pelo cabelo. O Espírito levantou-me entre a terra e o céu e, em visões de Deus, ele me levou a Jerusalém, à entrada da porta do norte do pátio interno, onde estava colocado o ídolo que desperta o zelo de Deus.

[[v26-8-4]]

^<<v26-8-4,4>>^ E ali, diante de mim, estava a glória do Deus de Israel, como na visão que eu havia tido na planície.

[[v26-8-5]]

^<<v26-8-5,5>>^ Então ele me disse: "Filho do homem, olhe para o norte". Olhei e, no lado norte, à porta do altar, vi o ídolo que desperta o zelo de Deus.

[[v26-8-6]]

^<<v26-8-6,6>>^ E ele me disse: "Filho do homem, vê você o que estão fazendo? As grandes práticas repugnantes da nação de Israel, coisas que me levarão para longe do meu santuário? Mas você verá práticas ainda piores que estas".

[[v26-8-7]]

^<<v26-8-7,7>>^ Então ele me levou para a entrada do pátio. Olhei e vi um buraco no muro.

[[v26-8-8]]

^<<v26-8-8,8>>^ Ele me disse: "Filho do homem, agora escave o muro". Escavei o muro e vi a abertura de uma porta ali.

[[v26-8-9]]

^<<v26-8-9,9>>^ E ele me disse: "Entre e veja as coisas repugnantes e más que estão fazendo".

[[v26-8-10]]

^<<v26-8-10,10>>^ Eu entrei e olhei. Lá eu vi, desenhadas por todas as paredes, todo tipo de criaturas rastejantes e animais impuros e todos os ídolos da nação de Israel.

[[v26-8-11]]

^<<v26-8-11,11>>^ Na frente deles estavam setenta autoridades da nação de Israel, e Jazanias, filho de Safã, estava no meio deles. Cada um tinha um incensário na mão, e se elevava uma nuvem aromática de incenso.

[[v26-8-12]]

^<<v26-8-12,12>>^ Ele me disse: "Filho do homem, você viu o que as autoridades da nação de Israel estão fazendo nas trevas, cada um no santuário de sua própria imagem esculpida? Eles dizem: ‘O Senhor não nos vê; o Senhor abandonou o país’ ".

[[v26-8-13]]

^<<v26-8-13,13>>^ E de novo disse: "Você os verá cometerem práticas ainda mais repugnantes".

[[v26-8-14]]

^<<v26-8-14,14>>^ Então ele me levou para a entrada da porta norte da casa do Senhor. Lá eu vi mulheres sentadas, chorando por Tamuz.

[[v26-8-15]]

^<<v26-8-15,15>>^ Ele me disse: "Você vê isso, filho do homem? Você verá práticas ainda mais repugnantes do que essa".

[[v26-8-16]]

^<<v26-8-16,16>>^ Ele então me levou para dentro do pátio interno da casa do Senhor, e ali, à entrada do templo, entre o pórtico e o altar, havia uns vinte e cinco homens. Com as costas para o templo do Senhor e os rostos voltados para o oriente, estavam se prostrando na direção do sol.

[[v26-8-17]]

^<<v26-8-17,17>>^ Ele me disse: "Você viu isso, filho do homem? Será algo corriqueiro para a nação de Judá essas práticas repugnantes? Deverão também encher a terra de violência e continuamente me provocar a ira? E veja! Eles estão pondo o ramo perto do nariz!

[[v26-8-18]]

^<<v26-8-18,18>>^ Por isso com ira eu os tratarei; não olharei com piedade para eles nem os pouparei. Mesmo que gritem aos meus ouvidos, não os ouvirei".

'''

xref:026-ezequiel/026-ezequiel-007.adoc#v26-7-0[&#60; Capítulo Anterior] | <<v26-8-0,Topo>> | xref:026-ezequiel/026-ezequiel-009.adoc#v26-9-0[Próximo Capítulo &#62;]