include::./index.adoc[]

[[v26-36-0]]
=== Ezequiel, 36
// nvi ?, NVI - Nova Versão Internacional

[[v26-36-1]]

^<<v26-36-1,1>>^ "Filho do homem, profetize para os montes de Israel e diga: ‘Ó montes de Israel, ouçam a palavra do Senhor.

[[v26-36-2]]

^<<v26-36-2,2>>^ Assim diz o Soberano Senhor: O inimigo disse a respeito de vocês: "Ah! Ah! As antigas elevações se tornaram nossas" ’.

[[v26-36-3]]

^<<v26-36-3,3>>^ Por isso profetize e diga: ‘Assim diz o Soberano Senhor: Por eles terem devastado e perseguido vocês por todos os lados de maneira que vocês se tornaram propriedade do restante das nações e objeto de conversa e de calúnia maliciosas de todos,

[[v26-36-4]]

^<<v26-36-4,4>>^ por isso, ó montes de Israel, ouçam a palavra do Soberano Senhor: Assim diz o Soberano Senhor aos montes, às colinas, às ravinas, aos vales, às ruínas arrasadas e às cidades abandonadas que foram saqueadas e ridicularizadas pelo restante das nações ao redor,

[[v26-36-5]]

^<<v26-36-5,5>>^ assim diz o Soberano Senhor: Em meu zelo ardente falei contra o restante das nações e contra todo o Edom, pois, com satisfação e com maldade em seus corações, eles fizeram de minha terra sua propriedade, para que saqueassem suas pastagens’.

[[v26-36-6]]

^<<v26-36-6,6>>^ Por isso profetize acerca da terra de Israel e diga aos montes, às colinas, às ravinas e aos vales: ‘Assim diz o Soberano Senhor: Falo com ciúme em minha ira porque vocês sofreram a zombaria das nações.

[[v26-36-7]]

^<<v26-36-7,7>>^ Por isso assim diz o Soberano Senhor: Juro de mão erguida que as nações ao redor também sofrerão zombaria.

[[v26-36-8]]

^<<v26-36-8,8>>^ " ‘Mas vocês, ó montes de Israel, produzirão galhos e frutos para o meu povo Israel, pois ele logo virá para casa.

[[v26-36-9]]

^<<v26-36-9,9>>^ Estou preocupado com vocês e olharei para vocês com favor; vocês serão arados e semeados,

[[v26-36-10]]

^<<v26-36-10,10>>^ e multiplicarei o número de vocês, a saber, de toda a nação de Israel. As cidades serão habitadas e as ruínas reconstruídas.

[[v26-36-11]]

^<<v26-36-11,11>>^ Multiplicarei os homens e os animais, e eles serão frutíferos e se tornarão numerosos. Tornarei a povoá-los como no passado, e farei vocês prosperarem mais do que antes. Então vocês saberão que eu sou o Senhor.

[[v26-36-12]]

^<<v26-36-12,12>>^ Farei Israel, o meu povo, andar sobre vocês. Eles os possuirão, e vocês serão a herança deles; vocês nunca mais os privarão dos filhos deles.

[[v26-36-13]]

^<<v26-36-13,13>>^ " ‘Assim diz o Soberano Senhor: Como é fato que estão dizendo a você: "Você devora homens e priva a sua nação de filhos",

[[v26-36-14]]

^<<v26-36-14,14>>^ você não mais devorará nem tornará sua nação sem filhos, palavra do Soberano Senhor.

[[v26-36-15]]

^<<v26-36-15,15>>^ Eu não farei mais você ouvir o sarcasmo das nações, e você não sofrerá mais a zombaria dos povos nem fará mais a sua nação cair, palavra do Soberano Senhor’. "

[[v26-36-16]]

^<<v26-36-16,16>>^ De novo a palavra do Senhor veio a mim, dizendo:

[[v26-36-17]]

^<<v26-36-17,17>>^ "Filho do homem, quando Israel morava em sua própria terra, eles a contaminaram com a sua conduta e com suas ações. A sua conduta era à minha vista como a impureza menstrual de uma mulher.

[[v26-36-18]]

^<<v26-36-18,18>>^ Por essa razão derramei sobre eles a minha ira, porque eles derramaram sangue na terra e porque se contaminaram com seus ídolos.

[[v26-36-19]]

^<<v26-36-19,19>>^ Eu os dispersei entre as nações, e eles foram espalhados entre os povos; eu os julguei de acordo com a conduta e as ações deles.

[[v26-36-20]]

^<<v26-36-20,20>>^ E, por onde andaram entre as nações, eles profanaram o meu santo nome, pois se dizia a respeito deles: ‘Esse é o povo do Senhor, mas assim mesmo ele teve que sair da terra que o Senhor lhe deu’.

[[v26-36-21]]

^<<v26-36-21,21>>^ Tive preocupação com o meu santo nome, o qual a nação de Israel profanou entre as nações para onde tinham ido.

[[v26-36-22]]

^<<v26-36-22,22>>^ "Por isso diga à nação de Israel: ‘Assim diz o Soberano Senhor: Não é por causa de vocês, ó nação de Israel, que vou fazer essas coisas, mas por causa do meu santo nome, o qual vocês profanaram entre as nações para onde foram.

[[v26-36-23]]

^<<v26-36-23,23>>^ Mostrarei a santidade do meu santo nome, o qual foi profanado entre as nações, o nome que vocês profanaram no meio delas. Então as nações saberão que eu sou o Senhor, palavra do Soberano Senhor, quando eu me mostrar santo por meio de vocês diante dos olhos delas.

[[v26-36-24]]

^<<v26-36-24,24>>^ " ‘Pois eu os tirarei das nações, os ajuntarei do meio de todas as terras e os trarei de volta para a sua própria terra.

[[v26-36-25]]

^<<v26-36-25,25>>^ Aspergirei água pura sobre vocês, e vocês ficarão puros; eu os purificarei de todas as suas impurezas e de todos os seus ídolos.

[[v26-36-26]]

^<<v26-36-26,26>>^ Darei a vocês um coração novo e porei um espírito novo em vocês; tirarei de vocês o coração de pedra e lhes darei um coração de carne.

[[v26-36-27]]

^<<v26-36-27,27>>^ Porei o meu Espírito em vocês e os levarei a agirem segundo os meus decretos e a obedecerem fielmente às minhas leis.

[[v26-36-28]]

^<<v26-36-28,28>>^ Vocês habitarão na terra que dei aos seus antepassados; vocês serão o meu povo, e eu serei o seu Deus.

[[v26-36-29]]

^<<v26-36-29,29>>^ Eu os livrarei de toda a sua impureza. Convocarei o cereal e o tornarei numeroso, e não trarei fome sobre vocês.

[[v26-36-30]]

^<<v26-36-30,30>>^ Aumentarei os frutos das árvores e as safras dos campos, de modo que vocês não sofrerão mais vergonha entre as nações por causa da fome.

[[v26-36-31]]

^<<v26-36-31,31>>^ Então vocês se lembrarão dos seus caminhos maus e das suas ações ímpias, e terão nojo de si mesmos por causa das suas iniqüidades e das suas práticas repugnantes.

[[v26-36-32]]

^<<v26-36-32,32>>^ Quero que vocês saibam que não estou fazendo isso por causa de vocês, palavra do Soberano Senhor. Envergonhem-se e humilhem-se por causa de sua conduta, ó nação de Israel!

[[v26-36-33]]

^<<v26-36-33,33>>^ " ‘Assim diz o Soberano Senhor: No dia em que eu os purificar de todos os seus pecados, eu restabelecerei as suas cidades, e as ruínas serão reconstruídas.

[[v26-36-34]]

^<<v26-36-34,34>>^ A terra arrasada será cultivada, e não permanecerá arrasada à vista de todos que passarem por ela.

[[v26-36-35]]

^<<v26-36-35,35>>^ Estes dirão: "Esta terra que estava arrasada tornou-se como o jardim do Éden; as cidades que jaziam em ruínas, arrasadas e destruídas, agora estão fortificadas e habitadas".

[[v26-36-36]]

^<<v26-36-36,36>>^ Então as nações que estiverem ao redor de vocês e que subsistirem saberão que eu, o Senhor, reconstruí o que estava destruído e replantei o que estava arrasado. Eu, o Senhor, falei, e o farei’.

[[v26-36-37]]

^<<v26-36-37,37>>^ "Assim diz o Soberano Senhor: Uma vez mais cederei à súplica da nação de Israel e farei isto por eles: Tornarei o povo deles tão numeroso como as ovelhas,

[[v26-36-38]]

^<<v26-36-38,38>>^ e como os grandes rebanhos destinados às ofertas das festas fixas de Jerusalém. Desse modo as cidades em ruínas ficarão cheias de rebanhos de gente. Então eles saberão que eu sou o Senhor".

'''

xref:026-ezequiel/026-ezequiel-035.adoc#v26-35-0[&#60; Capítulo Anterior] | <<v26-36-0,Topo>> | xref:026-ezequiel/026-ezequiel-037.adoc#v26-37-0[Próximo Capítulo &#62;]