include::./index.adoc[]

[[v26-32-0]]
=== Ezequiel, 32
// nvi ?, NVI - Nova Versão Internacional

[[v26-32-1]]

^<<v26-32-1,1>>^ No dia primeiro do décimo segundo mês do décimo segundo ano, esta palavra do Senhor veio a mim:

[[v26-32-2]]

^<<v26-32-2,2>>^ "Filho do homem, entoe um lamento a respeito do faraó, rei do Egito, e diga a ele: " ‘Você é como um leão entre as nações, como um monstro nos mares, contorcendo-se em seus riachos, agitando e enlameando as suas águas com os pés.

[[v26-32-3]]

^<<v26-32-3,3>>^ " ‘Assim diz o Soberano Senhor: " ‘Com uma imensa multidão de povos lançarei sobre você a minha rede, e eles o puxarão para cima em minha rede.

[[v26-32-4]]

^<<v26-32-4,4>>^ Atirarei você na terra e o lançarei no campo. Deixarei que todas as aves do céu se abriguem em você e os animais de toda a terra hão de empanturrar-se de você.

[[v26-32-5]]

^<<v26-32-5,5>>^ Estenderei a sua carne sobre os montes e encherei os vales com os seus restos.

[[v26-32-6]]

^<<v26-32-6,6>>^ Encharcarei a terra com o sangue que sair de você por todo o caminho, até os montes, e os vales ficarão cheias da sua carne.

[[v26-32-7]]

^<<v26-32-7,7>>^ Quando eu o extinguir, cobrirei o céu e escurecerei as suas estrelas; cobrirei o sol com uma nuvem, e a lua não dará a sua luz.

[[v26-32-8]]

^<<v26-32-8,8>>^ Todas as estrelas que brilham nos céus, eu as escurecerei sobre você, e trarei escuridão sobre a sua terra, palavra do Soberano Senhor.

[[v26-32-9]]

^<<v26-32-9,9>>^ Perturbarei os corações de muitos povos quando eu provocar a sua destruição entre as nações, em terras que você não conheceu.

[[v26-32-10]]

^<<v26-32-10,10>>^ Farei que muitos povos fiquem chocados ao vê-lo, e que os seus reis fiquem arrepiados de horror por sua causa, quando eu brandir a minha espada diante deles. No dia da sua queda todos eles tremerão de medo a todo instante por suas vidas.

[[v26-32-11]]

^<<v26-32-11,11>>^ " ‘Porque assim diz o Soberano Senhor: " ‘A espada do rei da Babilônia virá contra você.

[[v26-32-12]]

^<<v26-32-12,12>>^ Farei multidões do seu povo cair pela espada de poderosos, da mais impiedosa das nações. Eles destruirão o orgulho do Egito, e toda a sua população será vencida.

[[v26-32-13]]

^<<v26-32-13,13>>^ Destruirei todo o seu rebanho, junto às muitas águas, as quais não serão mais agitadas pelo pé do homem nem serão enlameadas pelos cascos do gado.

[[v26-32-14]]

^<<v26-32-14,14>>^ Então deixarei que as suas águas se assentem e farei os seus riachos fluírem como azeite, palavra do Soberano Senhor.

[[v26-32-15]]

^<<v26-32-15,15>>^ Quando eu arrasar o Egito e arrancar da terra tudo o que nela existe, quando eu abater todos os que ali moram, então eles saberão que eu sou o Senhor’.

[[v26-32-16]]

^<<v26-32-16,16>>^ "Esse é o lamento que entoarão por causa dele. As filhas das nações o entoarão; por causa do Egito e de todas as suas multidões de povo, elas o entoarão; palavra do Soberano Senhor".

[[v26-32-17]]

^<<v26-32-17,17>>^ No décimo quinto dia do mês do décimo segundo ano, esta palavra do Senhor veio a mim:

[[v26-32-18]]

^<<v26-32-18,18>>^ "Filho do homem, lamente pelas multidões do Egito e faça descer para baixo da terra tanto elas como as filhas das nações poderosas, junto com aqueles que descem à cova.

[[v26-32-19]]

^<<v26-32-19,19>>^ Diga-lhe: ‘Acaso você merece mais favores do que os outros? Desça e deite-se com os incircuncisos’.

[[v26-32-20]]

^<<v26-32-20,20>>^ Eles cairão entre os que foram mortos pela espada. A espada está preparada; sejam eles arrastados junto com toda a multidão do seu povo.

[[v26-32-21]]

^<<v26-32-21,21>>^ De dentro da sepultura os poderosos líderes dirão ao Egito e aos seus aliados: ‘Eles desceram e jazem com os incircuncisos, com os que foram mortos à espada’.

[[v26-32-22]]

^<<v26-32-22,22>>^ "A Assíria está ali com todo o seu exército; está cercada pelos túmulos de todos os seus mortos, de todos os que caíram pela espada.

[[v26-32-23]]

^<<v26-32-23,23>>^ Seus túmulos estão nas profundezas, e o seu exército jaz ao redor de seu túmulo. Todos os que haviam espalhado pavor na terra dos viventes estão mortos, caídos pela espada.

[[v26-32-24]]

^<<v26-32-24,24>>^ "Elão está ali, com toda a sua população ao redor de seu túmulo. Todos eles estão mortos, caídos pela espada. Todos os que haviam espalhado pavor na terra dos viventes desceram incircuncisos para baixo da terra. Carregam sua vergonha com os que descem à cova.

[[v26-32-25]]

^<<v26-32-25,25>>^ Uma cama está preparada para ele entre os mortos, com todas as suas hordas em torno de seu túmulo. Todos eles são incircuncisos, mortos pela espada. Porque o seu terror havia se espalhado na terra dos viventes, eles carregam sua desonra com aqueles que descem à cova; jazem entre os mortos.

[[v26-32-26]]

^<<v26-32-26,26>>^ "Meseque e Tubal estão ali, com todas a sua população ao redor de seus túmulos. Todos eles são incircuncisos, mortos à espada porque espalharam o seu terror na terra dos viventes.

[[v26-32-27]]

^<<v26-32-27,27>>^ Acaso não jazem com os outros guerreiros incircuncisos que caíram, que desceram à sepultura com suas armas de guerra, cujas espadas foram postas debaixo de suas cabeças? O castigo de suas iniqüidades está sobre seus ossos, embora o pavor causado por esses guerreiros tenha percorrido a terra dos viventes.

[[v26-32-28]]

^<<v26-32-28,28>>^ "Você também, ó faraó, será abatido e jazerá entre os incircuncisos, com os que foram mortos à espada.

[[v26-32-29]]

^<<v26-32-29,29>>^ "Edom está ali, seus reis e todos os seus príncipes; a despeito de seu poder, jazem com os que foram mortos à espada. Jazem com os incircuncisos, com aqueles que descem à cova.

[[v26-32-30]]

^<<v26-32-30,30>>^ "Todos os príncipes do norte e todos os sidônios estão ali; eles desceram com os mortos cobertos de vergonha, apesar do pavor provocado pelo poder que tinham. Eles jazem incircuncisos com os que foram mortos à espada e carregam sua desonra com aqueles que descem à cova.

[[v26-32-31]]

^<<v26-32-31,31>>^ "O faraó, ele e todo o seu exército, os verá e será consolado da perda de todo o seu povo que foi morto à espada, palavra do Soberano Senhor.

[[v26-32-32]]

^<<v26-32-32,32>>^ Embora eu o tenha feito espalhar pavor na terra dos viventes, o faraó e todo o seu povo jazerão entre os incircuncisos, com os que foram mortos pela espada, palavra do Soberano Senhor".

'''

xref:026-ezequiel/026-ezequiel-031.adoc#v26-31-0[&#60; Capítulo Anterior] | <<v26-32-0,Topo>> | xref:026-ezequiel/026-ezequiel-033.adoc#v26-33-0[Próximo Capítulo &#62;]