include::./index.adoc[]

[[v26-28-0]]
=== Ezequiel, 28
// nvi ?, NVI - Nova Versão Internacional

[[v26-28-1]]

^<<v26-28-1,1>>^ Veio a mim esta palavra do Senhor:

[[v26-28-2]]

^<<v26-28-2,2>>^ "Filho do homem, diga ao governante de Tiro: ‘Assim diz o Soberano Senhor: " ‘No orgulho do seu coração você diz: "Sou um deus; sento-me no trono de um deus no coração dos mares". Mas você é um homem, e não um deus, embora se ache tão sábio quanto um deus.

[[v26-28-3]]

^<<v26-28-3,3>>^ Você é mais sábio que Daniel? Não haverá segredo que lhe seja oculto?

[[v26-28-4]]

^<<v26-28-4,4>>^ Mediante a sua sabedoria e o seu entendimento, você granjeou riquezas e acumulou ouro e prata em seus tesouros.

[[v26-28-5]]

^<<v26-28-5,5>>^ Pela sua grande habilidade comercial você aumentou as suas riquezas, e, por causa das suas riquezas, o seu coração ficou cada vez mais orgulhoso.

[[v26-28-6]]

^<<v26-28-6,6>>^ " ‘Por isso, assim diz o Soberano Senhor: " ‘Porque você pensa que é sábio, tão sábio quanto um deus,

[[v26-28-7]]

^<<v26-28-7,7>>^ trarei estrangeiros contra você, das mais impiedosas nações; eles empunharão suas espadas contra a sua beleza e a sua sabedoria e traspassarão o seu esplendor fulgurante.

[[v26-28-8]]

^<<v26-28-8,8>>^ Eles o farão descer à cova, e você terá morte violenta no coração dos mares.

[[v26-28-9]]

^<<v26-28-9,9>>^ Será que então você dirá: "Eu sou um deus" na presença daqueles que o matarem? Você será tão-somente um homem, e não um deus, nas mãos daqueles que o abaterem.

[[v26-28-10]]

^<<v26-28-10,10>>^ Você terá a morte dos incircuncisos nas mãos de estrangeiros. Eu falei; palavra do Soberano Senhor’ ".

[[v26-28-11]]

^<<v26-28-11,11>>^ Esta palavra do Senhor veio a mim:

[[v26-28-12]]

^<<v26-28-12,12>>^ "Filho do homem, erga um lamento a respeito do rei de Tiro e diga-lhe: ‘Assim diz o Soberano Senhor: " ‘Você era o modelo de perfeição, cheio de sabedoria e de perfeita beleza.

[[v26-28-13]]

^<<v26-28-13,13>>^ Você estava no Éden, no jardim de Deus; todas as pedras preciosas o enfeitavam: sárdio, topázio e diamante, berilo, ônix e jaspe, safira, carbúnculo e esmeralda. Seus engastes e guarnições eram feitos de ouro; tudo foi preparado no dia em que você foi criado.

[[v26-28-14]]

^<<v26-28-14,14>>^ Você foi ungido como um querubim guardião, pois para isso eu o determinei. Você estava no monte santo de Deus e caminhava entre as pedras fulgurantes.

[[v26-28-15]]

^<<v26-28-15,15>>^ Você era inculpável em seus caminhos desde o dia em que foi criado até que se achou maldade em você.

[[v26-28-16]]

^<<v26-28-16,16>>^ Por meio do seu amplo comércio, você encheu-se de violência e pecou. Por isso eu o lancei em desgraça para longe do monte de Deus, e eu o expulsei, ó querubim guardião, do meio das pedras fulgurantes.

[[v26-28-17]]

^<<v26-28-17,17>>^ Seu coração tornou-se orgulhoso por causa da sua beleza, e você corrompeu a sua sabedoria por causa do seu esplendor. Por isso eu o atirei à terra; fiz de você um espetáculo para os reis.

[[v26-28-18]]

^<<v26-28-18,18>>^ Por meio dos seus muitos pecados e do seu comércio desonesto você profanou os seus santuários. Por isso fiz sair de você um fogo, que o consumiu, e eu reduzi você a cinzas no chão, à vista de todos os que estavam observando.

[[v26-28-19]]

^<<v26-28-19,19>>^ Todas as nações que o conheciam ficaram chocadas ao vê-la; chegou o seu terrível fim, você não mais existirá’ ".

[[v26-28-20]]

^<<v26-28-20,20>>^ Veio a mim esta palavra do Senhor:

[[v26-28-21]]

^<<v26-28-21,21>>^ "Filho do homem, vire o rosto contra Sidom; profetize contra ela

[[v26-28-22]]

^<<v26-28-22,22>>^ e diga: ‘Assim diz o Soberano Senhor: " ‘Estou contra você, Sidom, e manifestarei a minha glória dentro de você. Todos saberão que eu sou o Senhor, quando eu castigá-lo e mostrar-me santo em seu meio.

[[v26-28-23]]

^<<v26-28-23,23>>^ Enviarei uma peste sobre você e farei sangue correr em suas ruas. Os mortos cairão pela espada que a ataca por todos os lados. E todos saberão que eu sou o Senhor.

[[v26-28-24]]

^<<v26-28-24,24>>^ " ‘Israel não terá mais vizinhos maldosos agindo como roseiras bravas dolorosas e espinhos pontudos. Pois eles saberão que eu sou o Soberano Senhor.

[[v26-28-25]]

^<<v26-28-25,25>>^ " ‘Assim diz o Soberano Senhor: Quando eu reunir Israel de entre as nações nas quais foi espalhado, eu me mostrarei santo entre eles à vista das nações. Então eles viverão em sua própria terra, a qual dei ao meu servo Jacó.

[[v26-28-26]]

^<<v26-28-26,26>>^ Eles viverão ali em segurança, construirão casas e plantarão vinhas; viverão em segurança quando eu castigar todos os seus vizinhos que lhes fizeram mal. Então eles saberão que eu sou o Senhor, o seu Deus’ ".

'''

xref:026-ezequiel/026-ezequiel-027.adoc#v26-27-0[&#60; Capítulo Anterior] | <<v26-28-0,Topo>> | xref:026-ezequiel/026-ezequiel-029.adoc#v26-29-0[Próximo Capítulo &#62;]