include::./index.adoc[]

[[v26-9-0]]
=== Ezequiel, 9
// nvi ?, NVI - Nova Versão Internacional

[[v26-9-1]]

^<<v26-9-1,1>>^ Então o ouvi clamar em alta voz: "Tragam aqui os guardas da cidade, cada um com uma arma na mão".

[[v26-9-2]]

^<<v26-9-2,2>>^ E vi seis homens que vinham da porta superior, que está voltada para o norte, cada um com uma arma mortal na mão. Com eles estava um homem vestido de linho e que tinha um estojo de escrevente à cintura. Eles entraram e se puseram ao lado do altar de bronze.

[[v26-9-3]]

^<<v26-9-3,3>>^ Então a glória do Deus de Israel subiu de cima do querubim, onde havia estado, e se moveu para a entrada do templo. E o Senhor chamou o homem vestido de linho e que tinha o estojo de escrevente à cintura

[[v26-9-4]]

^<<v26-9-4,4>>^ e lhe disse: "Percorra a cidade de Jerusalém e ponha um sinal na testa daqueles que suspiram e gemem por causa de todas as práticas repugnantes que são feitas nela".

[[v26-9-5]]

^<<v26-9-5,5>>^ Enquanto eu escutava, ele disse aos outros: "Sigam-no por toda a cidade e matem, sem piedade ou compaixão,

[[v26-9-6]]

^<<v26-9-6,6>>^ velhos, rapazes e moças, mulheres e crianças. Mas não toquem em ninguém que tenha o sinal. Comecem no meu santuário". Então eles começaram com as autoridades que estavam em frente do templo.

[[v26-9-7]]

^<<v26-9-7,7>>^ E ele lhes disse: "Contaminem o templo e encham de mortos os pátios. Podem ir! " Eles saíram e começaram a matança em toda a cidade.

[[v26-9-8]]

^<<v26-9-8,8>>^ Enquanto isso eu fiquei sozinho. Então prostrei-me, rosto em terra, clamando: "Ah! Soberano Senhor! Vais destruir todo o remanescente de Israel lançando a tua ira sobre Jerusalém? "

[[v26-9-9]]

^<<v26-9-9,9>>^ Ele me respondeu: "A iniqüidade da nação de Israel e de Judá é enorme; a terra está cheia de sangue derramado e a cidade está cheia de injustiça. Eles dizem: ‘O Senhor abandonou o país; o Senhor não nos vê’.

[[v26-9-10]]

^<<v26-9-10,10>>^ Então eu, de minha parte, não olharei para eles com piedade nem os pouparei, mas farei cair sobre as suas cabeças o que eles têm feito".

[[v26-9-11]]

^<<v26-9-11,11>>^ Então o homem de linho com o estojo de escrevente à cintura voltou com um relatório, e disse: "Fiz o que me ordenaste".

'''

xref:026-ezequiel/026-ezequiel-008.adoc#v26-8-0[&#60; Capítulo Anterior] | <<v26-9-0,Topo>> | xref:026-ezequiel/026-ezequiel-010.adoc#v26-10-0[Próximo Capítulo &#62;]