include::./index.adoc[]

[[v26-48-0]]
=== Ezequiel, 48
// nvi ?, NVI - Nova Versão Internacional

[[v26-48-1]]

^<<v26-48-1,1>>^ "Estas são as tribos, relacionadas nominalmente: Na fronteira norte Dã terá uma porção; ela seguirá a estrada de Hetlom até Lebo-Hamate; Hazar-Enã e a fronteira norte, vizinha a Damasco, próxima de Hamate farão parte dos seus limites, desde o lado leste até o lado oeste.

[[v26-48-2]]

^<<v26-48-2,2>>^ "Aser terá uma porção; esta margeará o território de Dã do leste ao oeste.

[[v26-48-3]]

^<<v26-48-3,3>>^ "Naftali terá uma porção; esta margeará o território de Aser do leste ao oeste.

[[v26-48-4]]

^<<v26-48-4,4>>^ "Manassés terá uma porção; esta margeará o território de Naftali do leste ao oeste.

[[v26-48-5]]

^<<v26-48-5,5>>^ "Efraim terá uma porção; esta margeará o território de Manassés do leste ao oeste.

[[v26-48-6]]

^<<v26-48-6,6>>^ "Rúben terá uma porção; esta margeará o território de Efraim do leste ao oeste.

[[v26-48-7]]

^<<v26-48-7,7>>^ "Judá terá uma porção; esta margeará o território de Rúben do leste ao oeste.

[[v26-48-8]]

^<<v26-48-8,8>>^ "Margeando o território de Judá do leste ao oeste, estará a porção que vocês apresentarão como dádiva sagrada. Terá doze quilômetros e meio de largura, e o seu comprimento, do leste ao oeste, equivalerá a uma das porções tribais; o santuário estará no centro dela.

[[v26-48-9]]

^<<v26-48-9,9>>^ "A porção sagrada que vocês devem oferecer ao Senhor terá doze quilômetros e meio de comprimento e cinco quilômetros de largura.

[[v26-48-10]]

^<<v26-48-10,10>>^ Esta será a porção sagrada para os sacerdotes. Terá doze quilômetros e meio de comprimento no lado norte, cinco quilômetros de largura no lado ocidental, cinco quilômetros de largura no lado oriental e doze quilômetros e meio de comprimento no lado sul. No centro dela estará o santuário do Senhor.

[[v26-48-11]]

^<<v26-48-11,11>>^ Pertencerá aos sacerdotes consagrados, os zadoquitas, que foram fiéis em me servir e não se desviaram como fizeram os levitas quando os israelitas se desviaram.

[[v26-48-12]]

^<<v26-48-12,12>>^ Será um presente especial para eles da parte da porção sagrada da terra, uma porção santíssima, margeando o território dos levitas.

[[v26-48-13]]

^<<v26-48-13,13>>^ "Ao longo do território dos sacerdotes, os levitas terão uma área de doze quilômetros e meio de comprimento e cinco quilômetros de largura. Seu comprimento total medirá doze quilômetros e meio, e sua largura cinco quilômetros.

[[v26-48-14]]

^<<v26-48-14,14>>^ Eles não o venderão nem trocarão parte alguma dele. Essa área é a melhor de todo o território, e não poderá passar para outras mãos, porque é santo para o Senhor.

[[v26-48-15]]

^<<v26-48-15,15>>^ "A área restante, dois quilômetros e meio de largura e doze quilômetros e meio de comprimento, será para o uso comum da cidade, para casas e para pastagens. A cidade será o centro dela

[[v26-48-16]]

^<<v26-48-16,16>>^ e terá estas medidas: o lado norte, dois mil e duzentos e cinqüenta metros, o lado sul, com dois mil e duzentos e cinqüenta metros, o lado leste, dois mil e duzentos e cinqüenta metros e o lado oeste, dois mil e duzentos e cinqüenta metros.

[[v26-48-17]]

^<<v26-48-17,17>>^ A cidade terá uma área livre, de cento e vinte e cinco metros ao norte, cento e vinte e cinco metros ao sul, cento e vinte e cinco metros a leste e cento e vinte e cinco metros a oeste, que servirá para pasto.

[[v26-48-18]]

^<<v26-48-18,18>>^ O que restar da área, margeando a porção sagrada e indo ao longo dela, será de cinco quilômetros no lado leste e cinco quilômetros no lado oeste. Suas colheitas fornecerão comida para os trabalhadores da cidade.

[[v26-48-19]]

^<<v26-48-19,19>>^ Estes poderão vir de todas as tribos de Israel.

[[v26-48-20]]

^<<v26-48-20,20>>^ A porção toda, incluindo a cidade, será um quadrado, com doze quilômetros e meio de cada lado. É uma dádiva sagrada, que como tal vocês reservarão.

[[v26-48-21]]

^<<v26-48-21,21>>^ "As terras que restarem em ambos os lados da área formada pela porção sagrada e pela cidade pertencerão ao príncipe. Elas se estenderão para o leste a partir dos doze quilômetros e meio da porção sagrada até a fronteira leste, e para o oeste a partir dos doze quilômetros e meio até a fronteira oeste. Essas duas áreas, que correm paralelamente ao comprimento das porções das tribos, pertencerão ao príncipe, e a porção sagrada, inclusive o santuário do templo, estará no centro delas.

[[v26-48-22]]

^<<v26-48-22,22>>^ Assim a propriedade dos levitas e a propriedade da cidade estarão no centro da área que pertence ao príncipe. A área pertencente ao príncipe estará entre a fronteira de Judá e a fronteira de Benjamim.

[[v26-48-23]]

^<<v26-48-23,23>>^ "Quanto ao restante das tribos: Benjamim terá uma porção; esta se estenderá do lado leste ao lado oeste.

[[v26-48-24]]

^<<v26-48-24,24>>^ "Simeão terá uma porção; esta margeará o território de Benjamim do leste ao oeste.

[[v26-48-25]]

^<<v26-48-25,25>>^ "Issacar terá uma porção; esta margeará o território de Simeão do leste ao oeste.

[[v26-48-26]]

^<<v26-48-26,26>>^ "Zebulom terá uma porção; esta margeará o território de Issacar do leste ao oeste.

[[v26-48-27]]

^<<v26-48-27,27>>^ "Gade terá uma porção; esta margeará o território de Zebulom do leste ao oeste.

[[v26-48-28]]

^<<v26-48-28,28>>^ "A fronteira sul de Gade irá pelo sul desde Tamar até às águas de Meribá-Cades, e depois ao longo do ribeiro do Egito até o mar Grande.

[[v26-48-29]]

^<<v26-48-29,29>>^ "Esta é a terra que vocês distribuirão às tribos de Israel como herança, e serão essas as suas porções", palavra do Soberano Senhor.

[[v26-48-30]]

^<<v26-48-30,30>>^ "Estas serão as saídas da cidade: Começando pelo lado norte, que tem dois mil e duzentos e cinqüenta metros de comprimento,

[[v26-48-31]]

^<<v26-48-31,31>>^ as portas da cidade receberão os nomes das tribos de Israel. As três portas do lado norte serão a porta de Rúben, a porta de Judá e a porta de Levi.

[[v26-48-32]]

^<<v26-48-32,32>>^ "No lado leste, que tem dois mil e duzentos e cinqüenta metros de comprimento, haverá três portas: a de José, a de Benjamim e a de Dã.

[[v26-48-33]]

^<<v26-48-33,33>>^ "No lado sul, que tem dois mil e duzentos e cinqüenta metros de comprimento, haverá três portas: a de Simeão, a de Issacar e a de Zebulom.

[[v26-48-34]]

^<<v26-48-34,34>>^ "No lado oeste, que tem dois mil e duzentos e cinqüenta metros de comprimento, haverá três portas: a porta de Gade, a porta de Aser e a porta de Naftali.

[[v26-48-35]]

^<<v26-48-35,35>>^ "A distância total ao redor será de nove quilômetros. E daquele momento em diante, o nome da cidade será: O SENHOR ESTÁ AQUI. "

'''

xref:026-ezequiel/026-ezequiel-047.adoc#v26-47-0[&#60; Capítulo Anterior] | <<v26-48-0,Topo>> | xref:027-daniel/027-daniel-001.adoc#v27-1-0[Próximo Capítulo &#62;]