include::./index.adoc[]

[[v26-25-0]]
=== Ezequiel, 25
// nvi ?, NVI - Nova Versão Internacional

[[v26-25-1]]

^<<v26-25-1,1>>^ Esta palavra do Senhor veio a mim:

[[v26-25-2]]

^<<v26-25-2,2>>^ "Filho do homem, vire o rosto contra os amonitas e profetize contra eles.

[[v26-25-3]]

^<<v26-25-3,3>>^ Diga-lhes: ‘Ouçam a palavra do Soberano Senhor. Assim diz o Soberano Senhor: Visto que vocês exclamaram: "Ah! Ah! " quando o meu santuário foi profanado, quando a terra de Israel foi arrasada e quando a nação de Judá foi para o exílio,

[[v26-25-4]]

^<<v26-25-4,4>>^ vou entregar vocês como propriedade do povo do oriente. Eles instalarão seus acampamentos e armarão suas tendas no meio de vocês; comerão suas frutas e beberão seu leite.

[[v26-25-5]]

^<<v26-25-5,5>>^ Farei de Rabá num cercado para camelos e Amom um local de descanso para ovelhas. Então vocês saberão que eu sou o Senhor.

[[v26-25-6]]

^<<v26-25-6,6>>^ Porque assim diz o Soberano Senhor: Visto que vocês bateram palmas e pularam de alegria com o coração cheio de maldade contra Israel,

[[v26-25-7]]

^<<v26-25-7,7>>^ por essa razão estenderei o meu braço contra vocês e os darei às nações como despojo. Eliminarei vocês do meio das nações e os exterminarei do meio dos povos. Eu os destruirei, e vocês saberão que eu sou o Senhor’.

[[v26-25-8]]

^<<v26-25-8,8>>^ "Assim diz o Soberano Senhor: ‘Uma vez que Moabe e Seir disseram: "Vejam, a nação de Judá se tornou como todas as outras nações",

[[v26-25-9]]

^<<v26-25-9,9>>^ por essa razão abrirei o flanco de Moabe, começando por suas cidades fronteiriças, Bete-Jesimote, Baal-Meom e Quiriataim, que são a glória dessa terra.

[[v26-25-10]]

^<<v26-25-10,10>>^ Darei Moabe junto com os amonitas como propriedade ao povo do oriente. Os amonitas não serão lembrados entre as nações,

[[v26-25-11]]

^<<v26-25-11,11>>^ e a Moabe trarei castigo. Então eles saberão que eu sou o Senhor’.

[[v26-25-12]]

^<<v26-25-12,12>>^ "Assim diz o Soberano Senhor: ‘Visto que Edom vingou-se da nação de Judá e com isso trouxe grande culpa sobre si,

[[v26-25-13]]

^<<v26-25-13,13>>^ assim diz o Soberano Senhor: Estenderei o braço contra Edom e matarei os seus homens e os seus animais. Eu o arrasarei, e desde Temã até Dedã eles cairão pela espada.

[[v26-25-14]]

^<<v26-25-14,14>>^ Eu me vingarei de Edom pelas mãos do meu povo Israel, e este lidará com Edom de acordo com a minha ira e a minha indignação; eles conhecerão a minha vingança, palavra do Soberano Senhor’.

[[v26-25-15]]

^<<v26-25-15,15>>^ "Assim diz o Soberano Senhor: ‘Uma vez que a Filístia agiu por vingança e com maldade no coração, e com antiga hostilidade buscou destruir Judá,

[[v26-25-16]]

^<<v26-25-16,16>>^ assim diz o Soberano Senhor: estou a ponto de estender meu braço contra os filisteus. Eliminarei os queretitas e destruirei os que restarem no litoral.

[[v26-25-17]]

^<<v26-25-17,17>>^ Executarei neles grande vingança e os castigarei na minha ira. Então, quando eu me vingar deles, saberão que eu sou o Senhor’ ".

'''

xref:026-ezequiel/026-ezequiel-024.adoc#v26-24-0[&#60; Capítulo Anterior] | <<v26-25-0,Topo>> | xref:026-ezequiel/026-ezequiel-026.adoc#v26-26-0[Próximo Capítulo &#62;]