include::./index.adoc[]

[[v26-1-0]]
=== Ezequiel, 1
// nvi ?, NVI - Nova Versão Internacional

[[v26-1-1]]

^<<v26-1-1,1>>^ Era o quinto dia do quarto mês do trigésimo ano, e eu estava entre os exilados, junto ao rio Quebar. Abriram-se os céus, e eu tive visões de Deus.

[[v26-1-2]]

^<<v26-1-2,2>>^ Foi no quinto ano do exílio do rei Joaquim, no quinto dia do quarto mês.

[[v26-1-3]]

^<<v26-1-3,3>>^ A palavra do Senhor veio ao sacerdote Ezequiel, filho de Buzi, junto ao rio Quebar, na terra dos caldeus. Ali a mão do Senhor esteve sobre ele.

[[v26-1-4]]

^<<v26-1-4,4>>^ Olhei e vi uma tempestade que vinha do norte: uma nuvem imensa, com relâmpagos e faíscas, e cercada por uma luz brilhante. O centro do fogo parecia metal reluzente,

[[v26-1-5]]

^<<v26-1-5,5>>^ e no meio do fogo havia quatro vultos que pareciam seres viventes. Na aparência tinham forma de homem,

[[v26-1-6]]

^<<v26-1-6,6>>^ mas cada um deles tinha quatro rostos e quatro asas.

[[v26-1-7]]

^<<v26-1-7,7>>^ Suas pernas eram retas; seus pés eram como os de um bezerro e reluziam como bronze polido.

[[v26-1-8]]

^<<v26-1-8,8>>^ Debaixo de suas asas, nos quatro lados, tinham mãos humanas. Os quatro tinham rostos e asas,

[[v26-1-9]]

^<<v26-1-9,9>>^ e as suas asas encostavam umas nas outras. Quando se moviam andavam para a frente, e não se viravam.

[[v26-1-10]]

^<<v26-1-10,10>>^ Quanto à aparência dos seus rostos, os quatro tinham rosto de homem, rosto de leão no lado direito, rosto de boi no lado esquerdo, e rosto de águia.

[[v26-1-11]]

^<<v26-1-11,11>>^ Assim eram os seus rostos. Suas asas estavam estendidas para cima; cada um deles tinha duas asas que se encostavam na de outro ser vivente, de um lado e do outro, e duas asas que cobriam os seus corpos.

[[v26-1-12]]

^<<v26-1-12,12>>^ Cada um deles ia sempre para a frente. Para onde quer que fosse o Espírito eles iam, e não se viravam quando se moviam.

[[v26-1-13]]

^<<v26-1-13,13>>^ Os seres viventes pareciam carvão aceso; eram como tochas. O fogo ia de um lado a outro entre os seres viventes, e do fogo saíam relâmpagos e faíscas.

[[v26-1-14]]

^<<v26-1-14,14>>^ Os seres viventes iam e vinham como relâmpagos.

[[v26-1-15]]

^<<v26-1-15,15>>^ Enquanto eu olhava para eles, vi uma roda ao lado de cada um deles, diante dos seus quatro rostos.

[[v26-1-16]]

^<<v26-1-16,16>>^ Esta era a aparência das rodas e a sua estrutura: Reluziam como o berilo; e as quatro tinham aparência semelhante. Cada roda parecia estar entrosada na outra.

[[v26-1-17]]

^<<v26-1-17,17>>^ Quando se moviam, seguiam nas quatro direções dos quatro rostos, e não se viravam enquanto iam.

[[v26-1-18]]

^<<v26-1-18,18>>^ Seus aros eram altos e impressionantes e estavam cheios de olhos ao redor.

[[v26-1-19]]

^<<v26-1-19,19>>^ Quando os seres viventes se moviam, as rodas ao seu lado se moviam; e, quando se elevavam do chão, as rodas também se elevavam.

[[v26-1-20]]

^<<v26-1-20,20>>^ Para onde quer que o Espírito fosse, os seres viventes iam, e as rodas os seguiam, porque o mesmo Espírito estava nelas.

[[v26-1-21]]

^<<v26-1-21,21>>^ Quando os seres viventes se moviam, elas também se moviam; quando eles ficavam imóveis, elas também ficavam; e quando os seres viventes se elevavam do chão, as rodas também se elevavam com eles, porque o mesmo Espírito deles estava nelas.

[[v26-1-22]]

^<<v26-1-22,22>>^ Acima das cabeças dos seres viventes estava o que parecia uma abóboda, reluzente como gelo, e impressionante.

[[v26-1-23]]

^<<v26-1-23,23>>^ Debaixo dela cada ser vivente estendia duas asas ao que lhe estava mais próximo, e com as outras duas asas cobria o corpo.

[[v26-1-24]]

^<<v26-1-24,24>>^ Ouvi o ruído de suas asas quando voavam. Parecia o ruído de muitas águas, parecia a voz do Todo-poderoso. Era um ruído estrondoso, como o de um exército. Quando paravam, fechavam as asas.

[[v26-1-25]]

^<<v26-1-25,25>>^ Então veio uma voz de cima da abóboda sobre as suas cabeças, enquanto eles ficavam de asas fechadas.

[[v26-1-26]]

^<<v26-1-26,26>>^ Acima da abóboda sobre as suas cabeças havia o que parecia um trono de safira, e, bem no alto, sobre o trono, havia uma figura que parecia um homem.

[[v26-1-27]]

^<<v26-1-27,27>>^ A parte de cima do que parecia ser a cintura dele, vi que parecia metal brilhante, como que cheia de fogo, e que a parte de baixo parecia fogo; e uma luz brilhante o cercava.

[[v26-1-28]]

^<<v26-1-28,28>>^ Tal como a aparência do arco-íris nas nuvens de um dia chuvoso, assim era o resplendor ao seu redor. Essa era a aparência da figura da glória do Senhor. Quando a vi, prostrei-me com o rosto em terra, e ouvi a voz de alguém falando.

'''

xref:025-lamentacoes/025-lamentacoes-005.adoc#v25-5-0[&#60; Capítulo Anterior] | <<v26-1-0,Topo>> | xref:026-ezequiel/026-ezequiel-002.adoc#v26-2-0[Próximo Capítulo &#62;]