include::./index.adoc[]

[[v26-12-0]]
=== Ezequiel, 12
// nvi ?, NVI - Nova Versão Internacional

[[v26-12-1]]

^<<v26-12-1,1>>^ Veio a mim esta palavra do Senhor:

[[v26-12-2]]

^<<v26-12-2,2>>^ "Filho do homem, você vive no meio de uma nação rebelde. Eles têm olhos para ver, mas não vêem, e ouvidos para ouvir, mas não ouvem, pois são uma nação rebelde.

[[v26-12-3]]

^<<v26-12-3,3>>^ "Portanto, filho do homem, arrume os seus pertences para o exílio e, durante o dia, à vista de todos, parta, e vá para outro lugar. Talvez eles compreendam, embora sejam uma nação rebelde.

[[v26-12-4]]

^<<v26-12-4,4>>^ Durante o dia, sem fugir aos olhares do povo, leve para fora os seus pertences arrumados para o exílio. Então, à tarde, saia como aqueles que vão para o exílio. E que os outros o vejam fazer isso.

[[v26-12-5]]

^<<v26-12-5,5>>^ Enquanto eles o observam, faça um buraco no muro e passe os seus pertences através dele.

[[v26-12-6]]

^<<v26-12-6,6>>^ Ponha-os nos ombros, enquanto o povo estiver observando, e carregue-os ao entardecer. Cubra o rosto para que você não possa ver nada do país, pois eu fiz de você um sinal para a nação de Israel".

[[v26-12-7]]

^<<v26-12-7,7>>^ Então eu fiz o que me foi ordenado. Durante o dia levei para fora as minhas coisas arrumadas para o exílio. Depois, à tarde, fiz com as mãos um buraco no muro. Ao entardecer saí com os meus pertences carregando-os nos ombros à vista de todos.

[[v26-12-8]]

^<<v26-12-8,8>>^ De manhã me veio esta palavra do Senhor:

[[v26-12-9]]

^<<v26-12-9,9>>^ "Filho do homem, acaso aquela nação rebelde de Israel não lhe perguntou: ‘Que é que você está fazendo? ’

[[v26-12-10]]

^<<v26-12-10,10>>^ "Diga-lhes: ‘Assim diz o Soberano Senhor: Esta advertência diz respeito ao príncipe de Jerusalém e a toda a nação de Israel que está ali’.

[[v26-12-11]]

^<<v26-12-11,11>>^ Diga-lhes: ‘Eu sou um sinal para vocês. Como eu fiz, assim lhes será feito. Eles irão para o exílio como prisioneiros’.

[[v26-12-12]]

^<<v26-12-12,12>>^ "O príncipe deles porá os seus pertences nos ombros ao entardecer e sairá por um buraco que será escavado no muro para ele passar. Ele cobrirá o rosto para que não possa ver nada do país.

[[v26-12-13]]

^<<v26-12-13,13>>^ Estenderei a minha rede para ele, e ele será apanhado em meu laço; eu o trarei para a Babilônia, terra dos caldeus, mas ele não a verá, e ali morrerá.

[[v26-12-14]]

^<<v26-12-14,14>>^ Espalharei aos ventos todos os que estão ao seu redor, os seus oficiais e todas as suas tropas, e os perseguirei com a espada em punho.

[[v26-12-15]]

^<<v26-12-15,15>>^ "Eles saberão que eu sou o Senhor, quando eu os dispersar entre as nações e os espalhar pelas terras.

[[v26-12-16]]

^<<v26-12-16,16>>^ Mas pouparei uns poucos deles da espada, da fome e da peste para que, nas nações aonde forem, contem todas as suas práticas repugnantes. Então saberão que eu sou o Senhor".

[[v26-12-17]]

^<<v26-12-17,17>>^ Esta palavra do Senhor veio a mim:

[[v26-12-18]]

^<<v26-12-18,18>>^ "Filho do homem, trema enquanto come a sua comida, e fique arrepiado de medo enquanto bebe a sua água.

[[v26-12-19]]

^<<v26-12-19,19>>^ Diga ao povo do país: ‘Assim diz o Senhor Soberano acerca daqueles que vivem em Jerusalém e em Israel: Eles comerão sua comida com ansiedade e beberão sua água desesperados, pois tudo o que existe em sua terra dela será arrancado por causa da violência de todos os que ali vivem.

[[v26-12-20]]

^<<v26-12-20,20>>^ As cidades habitadas serão arrasadas e a terra ficará abandonada. Então vocês saberão que eu sou o Senhor’ ".

[[v26-12-21]]

^<<v26-12-21,21>>^ O Senhor me falou:

[[v26-12-22]]

^<<v26-12-22,22>>^ "Filho do homem, que provérbio é este que vocês têm em Israel: ‘Os dias passam e todas as visões dão em nada’?

[[v26-12-23]]

^<<v26-12-23,23>>^ Diga-lhes, pois: ‘Assim diz o Soberano Senhor: Vou dar fim a esse provérbio, e não será mais citado em Israel’. Diga-lhes: ‘Estão chegando os dias em que toda visão se cumprirá.

[[v26-12-24]]

^<<v26-12-24,24>>^ Pois não haverá mais visões falsas ou adivinhações bajuladoras entre o povo de Israel.

[[v26-12-25]]

^<<v26-12-25,25>>^ Mas eu, o Senhor, falarei o que eu quiser, e isso se cumprirá sem demora. Pois em seus dias, ó nação rebelde, cumprirei tudo o que eu disser, palavra do Soberano Senhor’ ".

[[v26-12-26]]

^<<v26-12-26,26>>^ Veio a mim esta palavra do Senhor:

[[v26-12-27]]

^<<v26-12-27,27>>^ "Filho do homem, a nação de Israel está dizendo: ‘A visão que ele vê é para daqui a muitos anos, e ele profetiza sobre o futuro distante’.

[[v26-12-28]]

^<<v26-12-28,28>>^ "Pois diga a eles: ‘Assim diz o Soberano Senhor: Nenhuma de minhas palavras sofrerá mais demora; tudo o que eu disser se cumprirá, palavra do Soberano Senhor’ ".

'''

xref:026-ezequiel/026-ezequiel-011.adoc#v26-11-0[&#60; Capítulo Anterior] | <<v26-12-0,Topo>> | xref:026-ezequiel/026-ezequiel-013.adoc#v26-13-0[Próximo Capítulo &#62;]