include::./index.adoc[]

[[v26-22-0]]
=== Ezequiel, 22
// nvi ?, NVI - Nova Versão Internacional

[[v26-22-1]]

^<<v26-22-1,1>>^ Veio a mim esta palavra do Senhor:

[[v26-22-2]]

^<<v26-22-2,2>>^ "Filho do homem, você a julgará? Você julgará essa cidade sanguinária? Então confronte-a com todas as suas práticas repugnantes

[[v26-22-3]]

^<<v26-22-3,3>>^ e diga: ‘Assim diz o Soberano Senhor: Ó cidade que traz condenação sobre si mesma por derramar sangue em seu meio e por se contaminar fazendo ídolos!

[[v26-22-4]]

^<<v26-22-4,4>>^ Você se tornou culpada por causa do sangue que derramou e por ter se contaminado com os ídolos que fez. Você deu cabo dos seus dias, e chegou o fim dos seus anos. Por isso farei de você objeto de zombaria para as nações e motivo de escárnio em todas as terras.

[[v26-22-5]]

^<<v26-22-5,5>>^ Tanto as nações vizinhas como as distantes zombarão de você, ó cidade infame e inquieta!

[[v26-22-6]]

^<<v26-22-6,6>>^ " ‘Veja como cada um dos príncipes de Israel que aí estão usa o seu poder para derramar sangue.

[[v26-22-7]]

^<<v26-22-7,7>>^ Em seu meio eles têm tratado pai e mãe com desprezo, e têm oprimido o estrangeiro e maltratado o órfão e a viúva.

[[v26-22-8]]

^<<v26-22-8,8>>^ Você desprezou as minhas dádivas sagradas e profanou os meus sábados.

[[v26-22-9]]

^<<v26-22-9,9>>^ Em seu meio há caluniadores, prontas para derramar sangue; em seu meio há os que comem nos santuários dos montes e praticam atos lascivos.

[[v26-22-10]]

^<<v26-22-10,10>>^ Em seu meio há aqueles que desonram a cama dos seus pais, e também há aqueles que têm relações com as mulheres nos dias de sua menstruação.

[[v26-22-11]]

^<<v26-22-11,11>>^ Um homem comete adultério com a mulher do seu próximo, outro contamina vergonhosamente a sua nora, e outro desonra a sua irmã, filha de seu próprio pai.

[[v26-22-12]]

^<<v26-22-12,12>>^ Em seu meio há homens que aceitam suborno para derramar sangue; você empresta visando lucro e a juros e obtém ganhos injustos, extorquindo o próximo. E você se esqueceu de mim; palavra do Soberano Senhor.

[[v26-22-13]]

^<<v26-22-13,13>>^ " ‘Mas você me verá bater as minhas mãos uma na outra contra os ganhos injustos que você obteve e contra o sangue que você derramou.

[[v26-22-14]]

^<<v26-22-14,14>>^ Será que a sua coragem suportará ou as suas mãos serão fortes para o que eu vou fazer no dia em que eu tratar com você? Eu, o Senhor, falei, e o farei.

[[v26-22-15]]

^<<v26-22-15,15>>^ Dispersarei você entre as nações e a espalharei pelas terras; e darei fim à sua impureza.

[[v26-22-16]]

^<<v26-22-16,16>>^ Quando você tiver sido desonrada aos olhos das nações, você saberá que eu sou o Senhor’ ".

[[v26-22-17]]

^<<v26-22-17,17>>^ E depois veio a mim esta palavra do Senhor:

[[v26-22-18]]

^<<v26-22-18,18>>^ "Filho do homem, a nação de Israel tornou-se escória para mim; cobre, estanho, ferro e chumbo deixados na fornalha. Não passa de escória de prata.

[[v26-22-19]]

^<<v26-22-19,19>>^ Por isso assim diz o Soberano Senhor: ‘Visto que vocês todos se tornaram escória, eu os ajuntarei em Jerusalém.

[[v26-22-20]]

^<<v26-22-20,20>>^ Assim como os homens ajuntam prata, cobre, ferro, chumbo e estanho numa fornalha a fim de fundi-los com um sopro, também na minha ira e na minha indignação ajuntarei vocês dentro da cidade e os fundirei.

[[v26-22-21]]

^<<v26-22-21,21>>^ Eu os ajuntarei e soprarei sobre vocês a minha ira impetuosa, e vocês se derreterão.

[[v26-22-22]]

^<<v26-22-22,22>>^ Assim como a prata se derrete numa fornalha, também vocês se derreterão dentro dela, e vocês saberão que eu, o Senhor, derramei a minha ira sobre vocês’ ".

[[v26-22-23]]

^<<v26-22-23,23>>^ De novo a palavra do Senhor veio a mim. Disse ele:

[[v26-22-24]]

^<<v26-22-24,24>>^ "Filho do homem, diga a esta terra: ‘Você é uma terra que não tem tido chuva nem aguaceiros no dia da ira’.

[[v26-22-25]]

^<<v26-22-25,25>>^ Há nela uma conspiração de seus príncipes como um leão que ruge ao despedaçar sua presa; devoram pessoas, apanham tesouros e coisas preciosas e fazem muitas viúvas.

[[v26-22-26]]

^<<v26-22-26,26>>^ Seus sacerdotes cometem violência contra a minha lei e profanam minhas ofertas sagradas; não fazem distinção entre o sagrado e o comum; ensinam que não existe nenhuma diferença entre o puro e o impuro; e fecham os olhos quanto à guarda dos meus sábados, de maneira que sou desonrado no meio deles.

[[v26-22-27]]

^<<v26-22-27,27>>^ Seus oficiais são como lobos que despedaçam suas presas; derramam sangue e matam gente para obter ganhos injustos.

[[v26-22-28]]

^<<v26-22-28,28>>^ Seus profetas disfarçam esses feitos enganando o povo com visões falsas e adivinhações mentirosas. Dizem: ‘Assim diz o Soberano Senhor’, quando o Senhor não falou.

[[v26-22-29]]

^<<v26-22-29,29>>^ O povo da terra pratica extorsão e comete roubos; oprime os pobres e os necessitados e maltrata os estrangeiros, negando-lhes justiça.

[[v26-22-30]]

^<<v26-22-30,30>>^ "Procurei entre eles um homem que erguesse o muro e se pusesse na brecha diante de mim e em favor da terra, para que eu não a destruísse, mas não encontrei nem um só.

[[v26-22-31]]

^<<v26-22-31,31>>^ Por isso derramarei a minha ira sobre eles e os consumirei com o meu grande furor; sofrerão as conseqüências de tudo o que eles fizeram, palavra do Soberano Senhor".

'''

xref:026-ezequiel/026-ezequiel-021.adoc#v26-21-0[&#60; Capítulo Anterior] | <<v26-22-0,Topo>> | xref:026-ezequiel/026-ezequiel-023.adoc#v26-23-0[Próximo Capítulo &#62;]