include::./index.adoc[]

[[v26-24-0]]
=== Ezequiel, 24
// nvi ?, NVI - Nova Versão Internacional

[[v26-24-1]]

^<<v26-24-1,1>>^ No décimo dia do décimo mês do nono ano, a palavra do Senhor veio a mim. Disse ele:

[[v26-24-2]]

^<<v26-24-2,2>>^ "Filho do homem, registre esta data, a data de hoje, porque o rei da Babilônia sitiou Jerusalém exatamente neste dia.

[[v26-24-3]]

^<<v26-24-3,3>>^ Conte a essa nação rebelde uma parábola e diga-lhes: ‘Assim diz o Soberano Senhor: " ‘Ponha a panela para esquentar; ponha-a para esquentar e coloque água nela.

[[v26-24-4]]

^<<v26-24-4,4>>^ Ponha dentro dela pedaços de carne, os melhores pedaços da coxa e da espádua. Encha-a com o melhor desses ossos;

[[v26-24-5]]

^<<v26-24-5,5>>^ apanhe o melhor do rebanho. Empilhe lenha debaixo dela para os cozinhar; faça-a ferver a água e cozinhe tudo o que está na panela.

[[v26-24-6]]

^<<v26-24-6,6>>^ " ‘Porque assim diz o Soberano Senhor: " ‘Ai da cidade sanguinária, da panela que agora tem uma crosta, cujo resíduo não desaparecerá! Esvazie-a pedaço por pedaço, sem sorteá-los.

[[v26-24-7]]

^<<v26-24-7,7>>^ " ‘Pois o sangue que ela derramou está no meio dela: Ela o derramou na rocha nua; não o derramou no chão, onde o pó o cobriria.

[[v26-24-8]]

^<<v26-24-8,8>>^ Para atiçar a minha ira e me vingar, pus o sangue dela sobre a rocha nua, para que ele não fosse coberto.

[[v26-24-9]]

^<<v26-24-9,9>>^ " ‘Portanto assim diz o Soberano Senhor: " ‘Ai da cidade sanguinária! Eu também farei uma pilha de lenha, uma pilha bem alta.

[[v26-24-10]]

^<<v26-24-10,10>>^ Por isso amontoem a lenha e acendam o fogo. Cozinhem bem a carne, misturando os temperos; e reduzam os ossos a cinzas.

[[v26-24-11]]

^<<v26-24-11,11>>^ Ponham depois a panela vazia sobre as brasas para que se esquente até que o seu bronze fique incandescente, e as suas impurezas se derretam, e o seu resíduo seja queimado e desapareça.

[[v26-24-12]]

^<<v26-24-12,12>>^ Mas ela frustrou todos os esforços; nem o fogo pôde eliminar seu resíduo espesso!

[[v26-24-13]]

^<<v26-24-13,13>>^ " ‘Ora, a sua impureza é a lascívia. Como eu desejei purificá-la mas você não quis ser purificada de sua impureza, você não voltará a estar limpa, enquanto não se abrandar a minha ira contra você.

[[v26-24-14]]

^<<v26-24-14,14>>^ " ‘Eu, o Senhor, falei. Chegou a hora de eu agir. Não me conterei; não terei piedade, nem voltarei atrás. Você será julgada de acordo com o seu comportamento e com as suas ações, palavra do Soberano Senhor’ ".

[[v26-24-15]]

^<<v26-24-15,15>>^ Veio a mim esta palavra do Senhor:

[[v26-24-16]]

^<<v26-24-16,16>>^ "Filho do homem, com um único golpe estou para tirar de você o prazer dos seus olhos. Contudo não lamente nem chore nem derrame nenhuma lágrima.

[[v26-24-17]]

^<<v26-24-17,17>>^ Não permita que ninguém ouça o seu gemer; não pranteie pelos mortos. Mantenha apertado o seu turbante e as sandálias nos pés; não cubra o rosto nem coma a comida costumeira dos pranteadores".

[[v26-24-18]]

^<<v26-24-18,18>>^ Por isso falei de manhã ao povo, e à tarde a minha mulher morreu. No dia seguinte fiz o que me havia sido ordenado.

[[v26-24-19]]

^<<v26-24-19,19>>^ Então o povo me perguntou: "Você não vai nos dizer que relação essas coisas têm conosco? "

[[v26-24-20]]

^<<v26-24-20,20>>^ E eu lhes respondi: "Esta palavra do Senhor veio a mim:

[[v26-24-21]]

^<<v26-24-21,21>>^ Diga à nação de Israel: ‘Assim diz o Soberano Senhor: Estou a ponto de profanar o meu santuário, a fortaleza de que vocês se orgulham, o prazer dos seus olhos, o objeto da sua afeição. Os filhos e as filhas que vocês deixaram lá, cairão pela espada.

[[v26-24-22]]

^<<v26-24-22,22>>^ E vocês farão o que eu fiz. Vocês não cobrirão o rosto nem comerão a comida costumeira dos pranteadores.

[[v26-24-23]]

^<<v26-24-23,23>>^ Vocês manterão os turbantes na cabeça e as sandálias nos pés. Não prantearão nem chorarão, mas irão consumir-se por causa de suas iniqüidades e gemerão uns pelos outros.

[[v26-24-24]]

^<<v26-24-24,24>>^ Ezequiel será um sinal para vocês; vocês farão o que ele fez. Quando isso acontecer, vocês saberão que eu sou o Soberano Senhor’.

[[v26-24-25]]

^<<v26-24-25,25>>^ "E você, filho do homem, no dia em que eu tirar deles a sua fortaleza, sua alegria e sua glória, o prazer dos seus olhos, e também os seus filhos e as suas filhas, o maior desejo de suas vidas,

[[v26-24-26]]

^<<v26-24-26,26>>^ naquele dia um fugitivo virá dar-lhe a notícia.

[[v26-24-27]]

^<<v26-24-27,27>>^ Naquela hora sua boca será aberta; você falará com ele e não ficará calado. E assim você será um sinal para eles, e eles saberão que eu sou o Senhor".

'''

xref:026-ezequiel/026-ezequiel-023.adoc#v26-23-0[&#60; Capítulo Anterior] | <<v26-24-0,Topo>> | xref:026-ezequiel/026-ezequiel-025.adoc#v26-25-0[Próximo Capítulo &#62;]