include::./index.adoc[]

[[v26-29-0]]
=== Ezequiel, 29
// nvi ?, NVI - Nova Versão Internacional

[[v26-29-1]]

^<<v26-29-1,1>>^ No décimo segundo dia do décimo mês do décimo ano do exílio, esta palavra do Senhor veio a mim:

[[v26-29-2]]

^<<v26-29-2,2>>^ "Filho do homem, vire o rosto contra o faraó, rei do Egito, e profetize contra ele e contra todo o Egito.

[[v26-29-3]]

^<<v26-29-3,3>>^ Diga-lhe: ‘Assim diz o Soberano Senhor: " ‘Estou contra você, faraó, rei do Egito, contra você, grande monstro deitado em meio a seus riachos. Você diz: "O Nilo é meu; eu o fiz para mim mesmo".

[[v26-29-4]]

^<<v26-29-4,4>>^ Mas porei anzóis em seu queixo e farei os peixes dos seus regatos se apegarem às suas próprias escamas. Puxarei você para fora dos seus riachos, com todos os peixes grudados em suas escamas.

[[v26-29-5]]

^<<v26-29-5,5>>^ Deixarei você no deserto, você e todos os peixes dos seus regatos. Você cairá em campo aberto e não será recolhido nem sepultado. Darei você como comida aos animais selvagens e às aves do céu.

[[v26-29-6]]

^<<v26-29-6,6>>^ " ‘Então todos os que vivem no Egito saberão que eu sou o Senhor. " ‘Você tem sido um bordão de junco para a nação de Israel.

[[v26-29-7]]

^<<v26-29-7,7>>^ Quando eles o pegaram com as mãos, você rachou e rasgou os ombros deles; quando eles se apoiaram em você, você se quebrou, e as costas deles sofreram torção.

[[v26-29-8]]

^<<v26-29-8,8>>^ " ‘Portanto, assim diz o Soberano Senhor: Trarei uma espada contra você e matarei os seus homens e os seus animais.

[[v26-29-9]]

^<<v26-29-9,9>>^ O Egito se tornará um deserto arrasado. Então eles saberão que eu sou o Senhor. " ‘Visto que você disse: "O Nilo é meu; eu o fiz",

[[v26-29-10]]

^<<v26-29-10,10>>^ estou contra você e contra os seus regatos, e tornarei o Egito uma desgraça e um deserto arrasado desde Migdol até Sevene, chegando até a fronteira da Etiópia.

[[v26-29-11]]

^<<v26-29-11,11>>^ Nenhum pé de homem ou pata de animal o atravessará; ninguém morará ali por quarenta anos.

[[v26-29-12]]

^<<v26-29-12,12>>^ Farei a terra do Egito arrasada em meio a terras devastadas, e suas cidades estarão arrasadas durante quarenta anos entre cidades em ruínas. E espalharei os egípcios entre as nações e os dispersarei entre os povos.

[[v26-29-13]]

^<<v26-29-13,13>>^ " ‘Contudo, assim diz o Soberano Senhor: Ao fim dos quarenta anos ajuntarei os egípcios de entre as nações nos quais foram espalhados.

[[v26-29-14]]

^<<v26-29-14,14>>^ Eu os trarei de volta do cativeiro e os farei voltar ao alto Egito, à terra dos seus antepassados. Ali serão um reino humilde.

[[v26-29-15]]

^<<v26-29-15,15>>^ Será o mais humilde dos reinos, e nunca mais se exaltará sobre as outras nações. Eu o farei tão fraco que nunca mais dominará sobre as nações.

[[v26-29-16]]

^<<v26-29-16,16>>^ O Egito não inspirará mais confiança a Israel, mas será uma lembrança de sua iniqüidade por ir atrás dele em busca de ajuda. Então eles saberão que eu sou o Soberano Senhor’ ".

[[v26-29-17]]

^<<v26-29-17,17>>^ No dia primeiro do primeiro mês do vigésimo sétimo ano do exílio, esta palavra do Senhor veio a mim:

[[v26-29-18]]

^<<v26-29-18,18>>^ "Filho do homem, o rei Nabucodonosor, da Babilônia, conduziu o seu exército numa dura campanha contra Tiro; toda cabeça foi esfregada até não ter ficar cabelo algum e todo ombro ficou esfolado. Contudo, ele e o seu exército não obtiveram nenhuma recompensa com a campanha que ele conduziu contra Tiro.

[[v26-29-19]]

^<<v26-29-19,19>>^ Por isso, assim diz o Soberano Senhor: Vou dar o Egito ao rei Nabucodonosor, da Babilônia, e ele levará embora a riqueza dessa nação. Ele saqueará e despojará a terra como pagamento para o seu exército.

[[v26-29-20]]

^<<v26-29-20,20>>^ Eu lhe dei o Egito como recompensa por seus esforços, por aquilo que ele e o seu exército fizeram para mim, palavra do Soberano Senhor.

[[v26-29-21]]

^<<v26-29-21,21>>^ "Naquele dia farei crescer o poder da nação de Israel, e abrirei a minha boca no meio deles. Então eles saberão que eu sou o Senhor".

'''

xref:026-ezequiel/026-ezequiel-028.adoc#v26-28-0[&#60; Capítulo Anterior] | <<v26-29-0,Topo>> | xref:026-ezequiel/026-ezequiel-030.adoc#v26-30-0[Próximo Capítulo &#62;]