include::./index.adoc[]

[[v26-33-0]]
=== Ezequiel, 33
// nvi ?, NVI - Nova Versão Internacional

[[v26-33-1]]

^<<v26-33-1,1>>^ Esta palavra do Senhor veio a mim:

[[v26-33-2]]

^<<v26-33-2,2>>^ "Filho do homem, fale com os seus compatriotas e diga-lhes: ‘Quando eu trouxer a espada contra uma terra e o povo da terra escolher um homem para ser sentinela,

[[v26-33-3]]

^<<v26-33-3,3>>^ e ele vir a espada vindo contra a terra e tocar a trombeta para advertir o povo,

[[v26-33-4]]

^<<v26-33-4,4>>^ então, se alguém ouvir a trombeta mas não der atenção à advertência e a espada vier e tirar a sua vida, ele será culpado de sua própria morte.

[[v26-33-5]]

^<<v26-33-5,5>>^ Uma vez que ele ouviu o som da trombeta mas não deu atenção à advertência, será culpado de sua própria morte. Se ele desse atenção à advertência, se livraria.

[[v26-33-6]]

^<<v26-33-6,6>>^ Mas, se a sentinela vir chegar a espada e não tocar a trombeta para advertir o povo e a espada vier e tirar a vida de um deles, aquele homem morrerá por causa de sua iniqüidade, mas considerarei a sentinela responsável pela morte daquele homem’.

[[v26-33-7]]

^<<v26-33-7,7>>^ "Filho do homem, eu o fiz uma sentinela para a nação de Israel; por isso ouça a minha palavra, e advirta-os em meu nome.

[[v26-33-8]]

^<<v26-33-8,8>>^ Quando eu disser ao ímpio que é certo que ele morrerá, e você não falar para dissuadi-lo de seus caminhos, aquele ímpio morrerá por sua iniqüidade, mas eu considerarei você responsável pela morte dele.

[[v26-33-9]]

^<<v26-33-9,9>>^ Mas, se você de fato advertir o ímpio para que se desvie dos seus caminhos e ele não se desviar, ele morrerá por sua iniqüidade, mas você estará livre da sua responsabilidade.

[[v26-33-10]]

^<<v26-33-10,10>>^ "Filho do homem, diga à nação de Israel: ‘É isto que vocês estão dizendo: "Nossas ofensas e pecados são um peso sobre nós, e estamos desfalecendo por causa deles. Como então poderemos viver? " ’

[[v26-33-11]]

^<<v26-33-11,11>>^ Diga-lhes: ‘Juro pela minha vida, palavra do Soberano Senhor, que não tenho prazer na morte dos ímpios, antes tenho prazer em que eles se desviem dos seus caminhos e vivam. Voltem! Voltem-se dos seus maus caminhos! Por que iriam morrer, ó nação de Israel? ’

[[v26-33-12]]

^<<v26-33-12,12>>^ "Por isso, filho do homem, diga aos seus compatriotas: ‘A retidão do justo não o livrará se ele voltar-se para a desobediência, e a maldade do ímpio não o fará cair se ele se desviar dela. E se o justo pecar, não viverá por causa de sua justiça’.

[[v26-33-13]]

^<<v26-33-13,13>>^ Se eu garantir ao justo que ele vai viver, mas ele, confiando em sua justiça, fizer o mal, nada de justo que fez será lembrado; ele morrerá por causa do mal que fez.

[[v26-33-14]]

^<<v26-33-14,14>>^ E, se você disser ao ímpio: ‘Certamente você morrerá’, mas ele se desviar do seu pecado e fizer o que é justo e certo;

[[v26-33-15]]

^<<v26-33-15,15>>^ se ele devolver o que apanhou como penhor de um empréstimo, se devolver o que roubou, se agir segundo os decretos que dão vida e não fizer mal algum, é certo que viverá; não morrerá.

[[v26-33-16]]

^<<v26-33-16,16>>^ Nenhum dos pecados que cometeu será lembrado contra ele. Ele fez o que é justo e certo; certamente viverá.

[[v26-33-17]]

^<<v26-33-17,17>>^ "Contudo, os seus compatriotas dizem: ‘O caminho do Senhor não é justo’. Mas é o caminho deles que não é justo.

[[v26-33-18]]

^<<v26-33-18,18>>^ Se um justo se afastar de sua justiça e fizer o mal, morrerá.

[[v26-33-19]]

^<<v26-33-19,19>>^ E, se um ímpio se desviar de sua maldade e fizer o que é justo e certo, viverá por assim proceder.

[[v26-33-20]]

^<<v26-33-20,20>>^ No entanto, ó nação de Israel, vocês dizem: ‘O caminho do Senhor não é justo’. Mas eu julgarei cada um de acordo com os seus próprios caminhos".

[[v26-33-21]]

^<<v26-33-21,21>>^ No quinto dia do décimo mês do décimo segundo ano do nosso exílio, um homem que havia escapado de Jerusalém veio a mim e disse: "A cidade caiu! "

[[v26-33-22]]

^<<v26-33-22,22>>^ Ora, na tarde do dia anterior, a mão do Senhor esteve sobre mim, e ele abriu a minha boca antes de chegar aquele homem. Assim foi aberta a minha boca, e eu não me calei mais.

[[v26-33-23]]

^<<v26-33-23,23>>^ Então me veio esta palavra do Senhor:

[[v26-33-24]]

^<<v26-33-24,24>>^ "Filho do homem, o povo que vive naquelas ruínas em Israel está dizendo: ‘Abraão era apenas um único homem, e, contudo, possuiu a terra. Mas nós somos muitos; com certeza receberemos a terra como propriedade’.

[[v26-33-25]]

^<<v26-33-25,25>>^ Então diga a eles: ‘Assim diz o Soberano Senhor: Uma vez que vocês comem carne com sangue, voltam-se para os seus ídolos e derramam sangue, deveriam possuir a terra?

[[v26-33-26]]

^<<v26-33-26,26>>^ Vocês confiam na espada, cometem práticas repugnantes, e cada um de vocês contamina a mulher do seu próximo. E deveriam possuir a terra? ’

[[v26-33-27]]

^<<v26-33-27,27>>^ "Diga isto a eles: ‘Assim diz o Soberano Senhor: Juro pela minha vida, que os que restam nas ruínas cairão pela espada, e que entregarei os que estão no campo aos animais selvagens para serem devorados, e que os que se abrigam em fortalezas e em cavernas morrerão de peste.

[[v26-33-28]]

^<<v26-33-28,28>>^ Tornarei a terra um deserto abandonado. Darei fim ao poder que se orgulha, e tão arrasados estarão os montes de Israel que ninguém vai querer passar por lá.

[[v26-33-29]]

^<<v26-33-29,29>>^ Eles saberão que eu sou o Senhor, quando eu tiver tornado a terra um deserto abandonado por causa de todas as práticas repugnantes que eles cometeram’.

[[v26-33-30]]

^<<v26-33-30,30>>^ "Quanto a você, filho do homem, seus compatriotas estão conversando sobre você junto aos muros e às portas das casas, dizendo uns aos outros: ‘Venham ouvir a mensagem que veio da parte do Senhor’.

[[v26-33-31]]

^<<v26-33-31,31>>^ O meu povo vem a você, como costuma fazer, e se assenta diante de você para ouvir as suas palavras, mas não as põe em prática. Com a boca eles expressam devoção, mas o coração deles está ávido de ganhos injustos.

[[v26-33-32]]

^<<v26-33-32,32>>^ De fato, para eles você não é nada mais do que alguém que entoa cânticos de amor com uma bela voz e que sabe tocar um instrumento, pois eles ouvem as suas palavras, mas não as põem em prática.

[[v26-33-33]]

^<<v26-33-33,33>>^ "Quando tudo isso acontecer — e certamente acontecerá — eles saberão que um profeta esteve no meio deles".

'''

xref:026-ezequiel/026-ezequiel-032.adoc#v26-32-0[&#60; Capítulo Anterior] | <<v26-33-0,Topo>> | xref:026-ezequiel/026-ezequiel-034.adoc#v26-34-0[Próximo Capítulo &#62;]