include::./index.adoc[]

[[v26-11-0]]
=== Ezequiel, 11
// nvi ?, NVI - Nova Versão Internacional

[[v26-11-1]]

^<<v26-11-1,1>>^ Então o Espírito me ergueu e me levou para a porta do templo do Senhor, que dá para o oriente. Ali, à entrada da porta, havia vinte e cinco homens, e vi entre eles Jazanias, filho de Azur, e Pelatias, filho de Benaia, líderes do povo.

[[v26-11-2]]

^<<v26-11-2,2>>^ O Senhor me disse: "Filho do homem, estes são os homens que estão tramando o mal e dando maus conselhos nesta cidade.

[[v26-11-3]]

^<<v26-11-3,3>>^ Eles dizem: ‘Não será logo o tempo de construir casas? Esta cidade é uma panela, e nós somos a carne dentro dela’.

[[v26-11-4]]

^<<v26-11-4,4>>^ Portanto, profetize contra eles; profetize, filho do homem".

[[v26-11-5]]

^<<v26-11-5,5>>^ Então o Espírito do Senhor veio sobre mim, e mandou-me dizer: "Assim diz o Senhor: É isso que vocês estão dizendo, ó nação de Israel, mas eu sei em que vocês estão pensando.

[[v26-11-6]]

^<<v26-11-6,6>>^ Vocês mataram muita gente nesta cidade e encheram as suas ruas de cadáveres.

[[v26-11-7]]

^<<v26-11-7,7>>^ "Portanto, assim diz o Soberano Senhor: Os corpos que vocês jogaram nas ruas são a carne, e esta cidade é a panela, mas eu os expulsarei dela.

[[v26-11-8]]

^<<v26-11-8,8>>^ Vocês têm medo da espada, e a espada é o que trarei contra vocês, palavra do Soberano Senhor.

[[v26-11-9]]

^<<v26-11-9,9>>^ Eu os expulsarei da cidade e os entregarei nas mãos de estrangeiros e lhes castigarei.

[[v26-11-10]]

^<<v26-11-10,10>>^ Vocês cairão pela espada, e eu os julgarei nas fronteiras de Israel. Então vocês saberão que eu sou o Senhor.

[[v26-11-11]]

^<<v26-11-11,11>>^ Esta cidade não será uma panela para vocês, nem vocês serão carne nela; eu os julgarei nas fronteiras de Israel.

[[v26-11-12]]

^<<v26-11-12,12>>^ E vocês saberão que eu sou o Senhor, pois vocês não agiram segundo os meus decretos nem obedeceram às minhas leis, mas se conformaram aos padrões das nações ao seu redor".

[[v26-11-13]]

^<<v26-11-13,13>>^ Ora, enquanto eu estava profetizando, Pelatias, filho de Benaia, morreu. Então prostrei-me, rosto em terra, e clamei em alta voz: "Ah! Soberano Senhor! Destruirás totalmente o remanescente de Israel? "

[[v26-11-14]]

^<<v26-11-14,14>>^ Esta palavra do Senhor veio a mim:

[[v26-11-15]]

^<<v26-11-15,15>>^ "Filho do homem, seus irmãos, sim, seus irmãos que são seus parentes consangüíneos e toda a nação de Israel, são aqueles de quem o povo de Jerusalém tem dito: ‘Eles estão longe do Senhor. É a nós que esta terra foi dada, para ser nossa propriedade’.

[[v26-11-16]]

^<<v26-11-16,16>>^ "Portanto diga: ‘Assim diz o Soberano Senhor: Embora eu os tenha mandado para terras muito distantes entre os povos e os tenha espalhado entre as nações, por breve período tenho sido um santuário para eles nas terras para onde foram’.

[[v26-11-17]]

^<<v26-11-17,17>>^ "Portanto, diga: ‘Assim diz o Soberano Senhor: Eu os ajuntarei dentre as nações e os trarei de volta das terras para onde vocês foram espalhados, e lhes devolverei a terra de Israel’.

[[v26-11-18]]

^<<v26-11-18,18>>^ "Eles voltarão para ela e retirarão todas as suas imagens repugnantes e os seus ídolos detestáveis.

[[v26-11-19]]

^<<v26-11-19,19>>^ Darei a eles um coração não dividido e porei um novo espírito dentro deles; retirarei deles o coração de pedra e lhes darei um coração de carne.

[[v26-11-20]]

^<<v26-11-20,20>>^ Então agirão segundo os meus decretos e serão cuidadosos em obedecer às minhas leis. Eles serão o meu povo, e eu serei o seu Deus.

[[v26-11-21]]

^<<v26-11-21,21>>^ Mas, quanto àqueles cujos corações estão afeiçoados às suas imagens repugnantes e aos ídolos detestáveis, farei cair sobre suas próprias cabeças aquilo que eles têm feito, palavra do Soberano Senhor".

[[v26-11-22]]

^<<v26-11-22,22>>^ Então os querubins, com as rodas ao lado, estenderam as asas, e a glória do Deus de Israel estava sobre eles.

[[v26-11-23]]

^<<v26-11-23,23>>^ A glória do Senhor subiu da cidade e parou sobre o monte que fica a leste dela.

[[v26-11-24]]

^<<v26-11-24,24>>^ Então o Espírito ergueu-me e levou-me aos que estavam exilados na Babilônia, na visão dada pelo Espírito de Deus. Findou-se então a visão que eu estava tendo,

[[v26-11-25]]

^<<v26-11-25,25>>^ e contei aos exilados tudo o que o Senhor tinha me mostrado.

'''

xref:026-ezequiel/026-ezequiel-010.adoc#v26-10-0[&#60; Capítulo Anterior] | <<v26-11-0,Topo>> | xref:026-ezequiel/026-ezequiel-012.adoc#v26-12-0[Próximo Capítulo &#62;]