include::./index.adoc[]

[[v26-27-0]]
=== Ezequiel, 27
// nvi ?, NVI - Nova Versão Internacional

[[v26-27-1]]

^<<v26-27-1,1>>^ Esta palavra do Senhor veio a mim:

[[v26-27-2]]

^<<v26-27-2,2>>^ "Filho do homem, faça um lamento a respeito de Tiro.

[[v26-27-3]]

^<<v26-27-3,3>>^ Diga a Tiro, que está junto à entrada para o mar, mercadora de povos em muitos litorais: ‘Assim diz o Soberano Senhor: " ‘Você diz, ó Tiro: "Minha beleza é perfeita".

[[v26-27-4]]

^<<v26-27-4,4>>^ Seu domínio abrangia o coração dos mares; seus construtores levaram a sua beleza à perfeição.

[[v26-27-5]]

^<<v26-27-5,5>>^ Eles fizeram todo o seu madeiramento com pinheiros de Senir; apanharam um cedro do Líbano para fazer-lhe um mastro.

[[v26-27-6]]

^<<v26-27-6,6>>^ Dos carvalhos de Basã fizeram os seus remos; de cipreste procedente das costas de Chipre fizeram seu convés, revestido de mármore.

[[v26-27-7]]

^<<v26-27-7,7>>^ De belo linho bordado, procedente do Egito foram feitas as suas velas e lhe serviu de bandeira; seus toldos, em vermelho e azul, provinham das costas de Elisá.

[[v26-27-8]]

^<<v26-27-8,8>>^ Habitantes de Sidom e Arvade eram os seus remadores; os seus homens hábeis, ó Tiro, estavam a bordo na qualidade de marinheiros.

[[v26-27-9]]

^<<v26-27-9,9>>^ Artesãos veteranos de Gebal estavam a bordo como construtores de barcos para calafetarem as suas juntas. Todos os navios do mar e seus marinheiros vinham para negociar as mercadorias que você tem.

[[v26-27-10]]

^<<v26-27-10,10>>^ " ‘Os persas, os lídios e os homens de Fute serviam como soldados em seu exército. Eles penduravam os seus escudos e capacetes nos seus muros, trazendo-lhe esplendor.

[[v26-27-11]]

^<<v26-27-11,11>>^ Homens de Arvade e de Heleque guarneciam os seus muros em todos os lados; homens de Gamade estavam em suas torres. Eles penduravam os seus escudos em seus muros ao redor; levaram a beleza de você à perfeição.

[[v26-27-12]]

^<<v26-27-12,12>>^ " ‘Társis fez negócios com você, tendo em vista os seus muitos bens; eles deram prata, ferro, estanho e chumbo em troca de suas mercadorias.

[[v26-27-13]]

^<<v26-27-13,13>>^ " ‘Javã, Tubal e Meseque fizeram comércio com você; trocaram escravos e utensílios de bronze pelos seus bens.

[[v26-27-14]]

^<<v26-27-14,14>>^ " ‘Homens de Bete-Togarma trocaram cavalos de carga, cavalos de guerra e mulas pelas suas mercadorias.

[[v26-27-15]]

^<<v26-27-15,15>>^ " ‘Os homens de Rodes fizeram comércio com você, e muitas regiões costeiras se tornaram seus clientes; eles lhe pagaram com presas de marfim e com ébano.

[[v26-27-16]]

^<<v26-27-16,16>>^ " ‘Arã fez negócios com você atraídos por seus muitos produtos; em troca de suas mercadorias deram-lhe turquesa, tecido vermelho, trabalhos bordados, linho fino, coral e rubis.

[[v26-27-17]]

^<<v26-27-17,17>>^ " ‘Judá e Israel fizeram comércio com você; pelos seus bens eles trocaram trigo de Minite, confeitos, mel, azeite e bálsamo.

[[v26-27-18]]

^<<v26-27-18,18>>^ " ‘Damasco, em razão dos muitos produtos de que você dispõe e da grande riqueza de seus bens, fez negócios com você, pagando-lhe com vinho de Helbom e lã de Zaar.

[[v26-27-19]]

^<<v26-27-19,19>>^ " ‘Também Dã e Javã de Uzal, compraram mercadorias de vocês, trocando-as por ferro, cássia e cálamo.

[[v26-27-20]]

^<<v26-27-20,20>>^ " ‘Dedã negociou com você mantos de sela.

[[v26-27-21]]

^<<v26-27-21,21>>^ " ‘A Arábia e todos os príncipes de Quedar eram seus clientes; fizeram negócios com você, fornecendo-lhes cordeiros, carneiros e bodes.

[[v26-27-22]]

^<<v26-27-22,22>>^ " ‘Os mercadores de Sabá e de Raamá fizeram comércio com você; pelas mercadorias que você vende eles trocaram o que há de melhor em toda espécie de especiarias, pedras preciosas, e ouro.

[[v26-27-23]]

^<<v26-27-23,23>>^ " ‘Harã, Cane e Éden e os mercadores de Sabá, Assur e Quilmade fizeram comércio com você.

[[v26-27-24]]

^<<v26-27-24,24>>^ No seu mercado eles negociaram com você lindas roupas, tecido azul, trabalhos bordados e tapetes multicoloridos com cordéis retorcidos e de nós firmes.

[[v26-27-25]]

^<<v26-27-25,25>>^ " ‘Os navios de Társis transportam os seus bens. Você está cheia de carga pesada no coração do mar.

[[v26-27-26]]

^<<v26-27-26,26>>^ Seus remadores a levam para alto mar. Mas o vento oriental a despedaçará no coração do mar.

[[v26-27-27]]

^<<v26-27-27,27>>^ Sua riqueza, suas mercadorias e seus bens, seus marujos, seus homens do mar e seus construtores de barcos, seus mercadores e todos os seus soldados, todos quantos estão a bordo sucumbirão no coração do mar no dia do seu naufrágio.

[[v26-27-28]]

^<<v26-27-28,28>>^ As praias tremerão quando os seus marujos clamarem.

[[v26-27-29]]

^<<v26-27-29,29>>^ Todos os que manejam os remos abandonarão os seus navios; os marujos e todos os marinheiros ficarão na praia.

[[v26-27-30]]

^<<v26-27-30,30>>^ Erguerão a voz e gritarão com amargura por sua causa; espalharão poeira sobre as suas cabeças e rolarão na cinza.

[[v26-27-31]]

^<<v26-27-31,31>>^ Raparão a cabeça por sua causa e porão vestes de lamento. Chorarão por você com angústia na alma e com pranto amargurado.

[[v26-27-32]]

^<<v26-27-32,32>>^ Quando estiverem gritando e pranteando por você, erguerão este lamento a seu respeito: "Quem chegou a ser silenciada como Tiro, cercada pelo mar? "

[[v26-27-33]]

^<<v26-27-33,33>>^ Quando as suas mercadorias saíam para o mar, você satisfazia muitas nações; com sua grande riqueza e com seus bens você enriqueceu os reis da terra.

[[v26-27-34]]

^<<v26-27-34,34>>^ Agora, destruída pelo mar, você jaz nas profundezas das águas; seus bens e todos os que a acompanham afundaram com você.

[[v26-27-35]]

^<<v26-27-35,35>>^ Todos os que moram nas regiões litorâneas estão chocados com o que aconteceu com você; seus reis arrepiam-se horrorizados e os seus rostos estão desfigurados de medo.

[[v26-27-36]]

^<<v26-27-36,36>>^ Os mercadores entre as nações gritam de medo, ao vê-la; chegou o seu terrível fim, e você não mais existirá’ ".

'''

xref:026-ezequiel/026-ezequiel-026.adoc#v26-26-0[&#60; Capítulo Anterior] | <<v26-27-0,Topo>> | xref:026-ezequiel/026-ezequiel-028.adoc#v26-28-0[Próximo Capítulo &#62;]