include::./index.adoc[]

[[v26-20-0]]
=== Ezequiel, 20
// nvi ?, NVI - Nova Versão Internacional

[[v26-20-1]]

^<<v26-20-1,1>>^ No décimo dia do quinto mês do sétimo ano do exílio, alguns dos líderes de Israel vieram consultar o Senhor, e se sentaram diante de mim.

[[v26-20-2]]

^<<v26-20-2,2>>^ Então me veio esta palavra do Senhor:

[[v26-20-3]]

^<<v26-20-3,3>>^ "Filho do homem, fale com os líderes de Israel e diga-lhes: ‘Assim diz o Soberano Senhor: Vocês vieram consultar-me? Juro pela minha vida que não deixarei que vocês me consultem, palavra do Soberano Senhor’.

[[v26-20-4]]

^<<v26-20-4,4>>^ "Você os julgará? Você os julgará, filho do homem? Então confronte-os com as práticas repugnantes dos seus antepassados

[[v26-20-5]]

^<<v26-20-5,5>>^ e diga a eles: ‘Assim diz o Soberano Senhor: No dia em que escolhi Israel, jurei com mão erguida aos descendentes da família de Jacó e me revelei a eles no Egito. Com mão erguida eu lhes disse: "Eu sou o Senhor, o seu Deus".

[[v26-20-6]]

^<<v26-20-6,6>>^ Naquele dia jurei a eles que os tiraria do Egito e os levaria para uma terra que eu havia procurado para eles, terra onde manam leite e mel, a mais linda de todas as terras.

[[v26-20-7]]

^<<v26-20-7,7>>^ E eu lhes disse: "Desfaçam-se, todos vocês, das imagens repugnantes em que vocês puseram os seus olhos, e não se contaminem com os ídolos do Egito. Eu sou o Senhor, o seu Deus".

[[v26-20-8]]

^<<v26-20-8,8>>^ " ‘Mas eles se rebelaram contra mim e não quiseram ouvir-me; não se desfizeram das imagens repugnantes em que haviam posto os seus olhos, nem abandonaram os ídolos do Egito. Por isso eu disse que derramaria a minha ira sobre eles e que lançaria a minha indignação contra eles no Egito.

[[v26-20-9]]

^<<v26-20-9,9>>^ Mas, por amor do meu nome, eu agi, evitando que o meu nome fosse profanado aos olhos das nações entre as quais estavam e à vista de quem eu tinha me revelado aos israelitas para tirá-los do Egito.

[[v26-20-10]]

^<<v26-20-10,10>>^ Por isso eu os tirei do Egito e os trouxe para o deserto.

[[v26-20-11]]

^<<v26-20-11,11>>^ Eu lhes dei os meus decretos e lhes tornei conhecidas as minhas leis, pois aquele que lhes obedecer viverá por elas.

[[v26-20-12]]

^<<v26-20-12,12>>^ Também lhes dei os meus sábados como um sinal entre nós, para que soubessem que eu, o Senhor, fiz deles um povo santo.

[[v26-20-13]]

^<<v26-20-13,13>>^ " ‘Contudo, os israelitas se rebelaram contra mim no deserto. Não agiram segundo os meus decretos, mas rejeitaram as minhas leis, sendo que aquele que lhes obedecer viverá por elas, e profanaram os meus sábados. Por isso eu disse que derramaria a minha ira sobre eles e os destruiria no deserto.

[[v26-20-14]]

^<<v26-20-14,14>>^ Mas, por amor do meu nome, eu agi, evitando que o meu nome fosse profanado aos olhos das nações à vista das quais eu os havia tirado dali.

[[v26-20-15]]

^<<v26-20-15,15>>^ Também, com mão erguida, jurei a eles que não os levaria para a terra que eu lhes dei, terra onde manam leite e mel, a mais linda de todas as terras,

[[v26-20-16]]

^<<v26-20-16,16>>^ porque eles rejeitaram as minhas leis, não agiram segundo os meus decretos e profanaram os meus sábados. Pois os seus corações estavam voltados paras os seus ídolos.

[[v26-20-17]]

^<<v26-20-17,17>>^ Olhei, porém, para eles com piedade e não os destruí, não os exterminei no deserto.

[[v26-20-18]]

^<<v26-20-18,18>>^ Eu disse aos filhos deles no deserto: Não sigam as normas dos seus pais nem obedeçam às leis deles nem se contaminem com os seus ídolos.

[[v26-20-19]]

^<<v26-20-19,19>>^ Eu sou o Senhor, o seu Deus; ajam conforme os meus decretos e tenham o cuidado de guardar as minhas leis.

[[v26-20-20]]

^<<v26-20-20,20>>^ Santifiquem os meus sábados, para que eles sejam um sinal entre nós. Então vocês saberão que eu sou o Senhor, o seu Deus.

[[v26-20-21]]

^<<v26-20-21,21>>^ " ‘Mas os filhos se rebelaram contra mim: Não agiram de acordo com os meus decretos, não tiveram o cuidado de obedecer às minhas leis, sendo que aquele que lhes obedecer viverá por elas, e profanaram os meus sábados. Por isso eu disse que derramaria a minha ira sobre eles e lançaria o meu furor contra eles no deserto.

[[v26-20-22]]

^<<v26-20-22,22>>^ Mas contive o meu braço e, por amor do meu nome, agi evitando que o meu nome fosse profanado aos olhos das nações à vista das quais eu os havia tirado dali.

[[v26-20-23]]

^<<v26-20-23,23>>^ Também, com mão erguida, jurei a eles no deserto que os espalharia entre as nações e os dispersaria por outras terras,

[[v26-20-24]]

^<<v26-20-24,24>>^ porque não obedeceram às minhas leis, mas rejeitaram os meus decretos e profanaram os meus sábados, e os seus olhos cobiçaram os ídolos de seus país.

[[v26-20-25]]

^<<v26-20-25,25>>^ Também os abandonei a decretos que não eram bons e a leis pelas quais não conseguiam viver;

[[v26-20-26]]

^<<v26-20-26,26>>^ deixei que se contaminassem por meio de suas ofertas o sacrifício de cada filho mais velho, para que eu os enchesse de pavor e para que eles soubessem que eu sou o Senhor’.

[[v26-20-27]]

^<<v26-20-27,27>>^ "Portanto, filho do homem, fale à nação de Israel e diga-lhes: ‘Assim diz o Soberano Senhor: Nisto os seus antepassados também blasfemaram contra mim ao me abandonarem:

[[v26-20-28]]

^<<v26-20-28,28>>^ Quando eu os trouxe para a terra que eu havia jurado dar-lhes, bastava que vissem um monte alto ou uma árvore frondosa, ali ofereciam os seus sacrifícios, faziam ofertas que provocaram a minha ira, apresentavam seu incenso aromático e derramavam suas ofertas de bebidas.

[[v26-20-29]]

^<<v26-20-29,29>>^ Perguntei-lhes então: Que altar é este no monte para onde vocês vão? ’ " É chamado Bama até o dia de hoje.

[[v26-20-30]]

^<<v26-20-30,30>>^ "Portanto, diga à nação de Israel: ‘Assim diz o Soberano Senhor: Vocês não estão se contaminando como os seus antepassados se contaminaram? E não estão cobiçando as suas imagens repugnantes?

[[v26-20-31]]

^<<v26-20-31,31>>^ Quando vocês apresentam as suas ofertas, o sacrifício de seus filhos no fogo, continuam a contaminar-se com todos os seus ídolos até o dia de hoje. E eu deverei deixar que me consultem, ó nação de Israel. Juro pela minha vida, palavra do Soberano Senhor, que não lhes permitirei que me consultem.

[[v26-20-32]]

^<<v26-20-32,32>>^ " ‘Vocês dizem: "Queremos ser como as nações, como os povos do mundo, que servem à madeira e à pedra". Mas o que vocês têm em mente jamais acontecerá.

[[v26-20-33]]

^<<v26-20-33,33>>^ Juro pela minha vida, palavra do Soberano Senhor, que dominarei sobre vocês com mão poderosa e braço forte e com ira que já transbordou.

[[v26-20-34]]

^<<v26-20-34,34>>^ Trarei vocês dentre as nações e os ajuntarei dentre as terras para onde vocês foram espalhados, com mão poderosa e braço forte e com ira que já transbordou.

[[v26-20-35]]

^<<v26-20-35,35>>^ Trarei vocês para o deserto das nações e ali, face a face, os julgarei.

[[v26-20-36]]

^<<v26-20-36,36>>^ Assim como julguei os seus antepassados no deserto do Egito, também eu os julgarei, palavra do Soberano Senhor.

[[v26-20-37]]

^<<v26-20-37,37>>^ Contarei vocês enquanto estiverem passando debaixo da minha vara, e os trarei para o vínculo da aliança.

[[v26-20-38]]

^<<v26-20-38,38>>^ Eu os separarei daqueles que se revoltam e se rebelam contra mim. Embora eu os tire da terra onde habitam, eles não entrarão na terra de Israel. Então vocês saberão que eu sou o Senhor.

[[v26-20-39]]

^<<v26-20-39,39>>^ " ‘Quanto a vocês, ó nação de Israel, assim diz o Soberano Senhor: Vão prestar culto a seus ídolos, cada um de vocês! Mas depois disso vocês certamente me ouvirão e não profanarão mais o meu nome santo com as suas ofertas e com os seus ídolos.

[[v26-20-40]]

^<<v26-20-40,40>>^ Pois no meu santo monte, no alto monte de Israel, palavra do Soberano Senhor, na sua terra, toda a nação de Israel me prestará culto, e ali eu os aceitarei. Ali exigirei as ofertas de vocês e as suas melhores dádivas, junto com todos as suas dádivas sagradas.

[[v26-20-41]]

^<<v26-20-41,41>>^ Eu os aceitarei como incenso aromático quando eu os tirar dentre as nações e os ajuntar dentre as terras pelas quais vocês foram espalhados, e eu me mostrarei santo no meio de vocês à vista das nações.

[[v26-20-42]]

^<<v26-20-42,42>>^ Vocês saberão que eu sou o Senhor, quando eu os trouxer para a terra de Israel, a terra que, de mão erguida, jurei dar aos seus antepassados.

[[v26-20-43]]

^<<v26-20-43,43>>^ Ali vocês se lembrarão da conduta que tiveram e de todas as ações pelas quais vocês se contaminaram, e terão nojo de si mesmos por causa de todo mal que vocês fizeram.

[[v26-20-44]]

^<<v26-20-44,44>>^ Vocês saberão que eu sou o Senhor, quando eu tratar com vocês por amor do meu nome e não de acordo com os seus caminhos maus e suas práticas perversas, ó nação de Israel; palavra do Soberano Senhor’. "

[[v26-20-45]]

^<<v26-20-45,45>>^ Veio a mim esta palavra do Senhor:

[[v26-20-46]]

^<<v26-20-46,46>>^ "Filho do homem, vire o rosto para o sul; pregue contra o sul e profetize contra a floresta da terra do Neguebe.

[[v26-20-47]]

^<<v26-20-47,47>>^ Diga à floresta do Neguebe: ‘Ouça a palavra do Senhor. Assim diz o Soberano Senhor: Estou a ponto de incendiá-la, consumindo assim todas as suas árvores, tanto as verdes quanto as secas. A chama abrasadora não será apagada, e todo rosto, do Neguebe até o norte, será ressecado por ela.

[[v26-20-48]]

^<<v26-20-48,48>>^ Todos verão que eu o Senhor a acendi; não será apagada’ ".

[[v26-20-49]]

^<<v26-20-49,49>>^ Então eu disse: "Ah, Soberano Senhor! Estão dizendo a meu respeito: ‘Acaso ele não está apenas contando parábolas? ’ "

'''

xref:026-ezequiel/026-ezequiel-019.adoc#v26-19-0[&#60; Capítulo Anterior] | <<v26-20-0,Topo>> | xref:026-ezequiel/026-ezequiel-021.adoc#v26-21-0[Próximo Capítulo &#62;]