include::./index.adoc[]

[[v26-19-0]]
=== Ezequiel, 19
// nvi ?, NVI - Nova Versão Internacional

[[v26-19-1]]

^<<v26-19-1,1>>^ "Levante um lamento pelos príncipes de Israel

[[v26-19-2]]

^<<v26-19-2,2>>^ e diga: " ‘Que leoa era a sua mãe entre os leões! Ela se deitava entre os leõezinhos e criava os seus filhotes.

[[v26-19-3]]

^<<v26-19-3,3>>^ Criou um dos seus filhotes, e ele se tornou um leão forte. Ele aprendeu a despedaçar a presa e devorou homens.

[[v26-19-4]]

^<<v26-19-4,4>>^ As nações ouviram a seu respeito, e ele foi pego na cova delas. Elas o levaram com ganchos para o Egito.

[[v26-19-5]]

^<<v26-19-5,5>>^ " ‘Quando ela viu que a sua esperança não se cumpria, quando viu que se havia ido a sua expectativa, escolheu outro de seus filhotes e fez dele um leão forte.

[[v26-19-6]]

^<<v26-19-6,6>>^ Ele vagueou entre os leões, pois agora era um leão forte. Ele aprendeu a despedaçar a presa e devorou homens.

[[v26-19-7]]

^<<v26-19-7,7>>^ Arrebentou suas fortalezas e devastou suas cidades. A terra e todos que nela estavam ficaram aterrorizados com o seu rugido.

[[v26-19-8]]

^<<v26-19-8,8>>^ Então as nações vizinhas o atacaram. Estenderam sua rede para apanhá-lo, e ele foi pego na armadilha que fizeram.

[[v26-19-9]]

^<<v26-19-9,9>>^ Com ganchos elas o puxaram para dentro de uma jaula e o levaram ao rei da Babilônia. Elas o colocaram na prisão, de modo que não se ouviu mais o seu rugido nos montes de Israel.

[[v26-19-10]]

^<<v26-19-10,10>>^ " ‘Sua mãe era como uma vide em sua vinha plantada junto à água; era frutífera e cheia de ramos, graças às muitas águas.

[[v26-19-11]]

^<<v26-19-11,11>>^ Seus ramos eram fortes, próprios para o cetro de um governante. Ela cresceu e subiu muito, sobressaindo à folhagem espessa; chamava a atenção por sua altura e por seus muitos ramos.

[[v26-19-12]]

^<<v26-19-12,12>>^ Mas foi desarraigada com fúria e atirada ao chão. O vento oriental a fez murchar, seus frutos foram arrancados, seus fortes galhos secaram e o fogo os consumiu.

[[v26-19-13]]

^<<v26-19-13,13>>^ Agora está plantada no deserto, numa terra seca e sedenta.

[[v26-19-14]]

^<<v26-19-14,14>>^ O fogo espalhou-se de um dos seus ramos principais e consumiu toda a ramagem. Nela não resta nenhum ramo forte que seja próprio para o cetro de um governante’. Esse é um lamento e como lamento deverá ser empregado".

'''

xref:026-ezequiel/026-ezequiel-018.adoc#v26-18-0[&#60; Capítulo Anterior] | <<v26-19-0,Topo>> | xref:026-ezequiel/026-ezequiel-020.adoc#v26-20-0[Próximo Capítulo &#62;]