include::./index.adoc[]

[[v26-2-0]]
=== Ezequiel, 2
// nvi ?, NVI - Nova Versão Internacional

[[v26-2-1]]

^<<v26-2-1,1>>^ Ele me disse: "Filho do homem, fique de pé, que eu vou falar com você".

[[v26-2-2]]

^<<v26-2-2,2>>^ Enquanto ele falava, o Espírito entrou em mim e me pôs de pé, e ouvi aquele que me falava.

[[v26-2-3]]

^<<v26-2-3,3>>^ Ele disse: "Filho do homem, vou enviá-lo aos israelitas, nação rebelde que se revoltou contra mim; até hoje eles e os seus antepassados têm se revoltado contra mim.

[[v26-2-4]]

^<<v26-2-4,4>>^ O povo a quem vou enviá-lo é obstinado e rebelde. Diga-lhe: Assim diz o Senhor Soberano.

[[v26-2-5]]

^<<v26-2-5,5>>^ E, quer aquela nação rebelde ouça, quer deixe de ouvir, saberá que um profeta esteve no meio dela.

[[v26-2-6]]

^<<v26-2-6,6>>^ E você, filho do homem, não tenha medo dessa gente nem das suas palavras. Não tenha medo, ainda que o cerquem espinheiros, e você viva entre escorpiões. Não tenha medo do que disserem, nem fique apavorado ao vê-los, embora sejam uma nação rebelde.

[[v26-2-7]]

^<<v26-2-7,7>>^ Você lhes falará as minhas palavras, quer ouçam quer deixem de ouvir, pois são rebeldes.

[[v26-2-8]]

^<<v26-2-8,8>>^ Mas você, filho do homem, ouça o que lhe digo. Não seja rebelde como aquela nação; abra a boca e coma o que lhe vou dar".

[[v26-2-9]]

^<<v26-2-9,9>>^ Então olhei, e vi a mão de alguém estendida para mim. Nela estava o rolo de um livro,

[[v26-2-10]]

^<<v26-2-10,10>>^ que ele desenrolou diante de mim. Em ambos os lados dele estavam escritas palavras de lamento, pranto e ais.

'''

xref:026-ezequiel/026-ezequiel-001.adoc#v26-1-0[&#60; Capítulo Anterior] | <<v26-2-0,Topo>> | xref:026-ezequiel/026-ezequiel-003.adoc#v26-3-0[Próximo Capítulo &#62;]