include::./index.adoc[]

[[v26-46-0]]
=== Ezequiel, 46
// nvi ?, NVI - Nova Versão Internacional

[[v26-46-1]]

^<<v26-46-1,1>>^ " ‘Assim diz o Soberano Senhor: A porta do pátio interno que dá para o leste ficará trancada nos seis dias úteis, mas no sábado e no dia da lua nova será aberta.

[[v26-46-2]]

^<<v26-46-2,2>>^ O príncipe, vindo do pátio externo, entrará pelo pórtico da entrada e ficará junto ao batente. Os sacerdotes sacrificarão os holocaustos e as ofertas de comunhão dele. Ele adorará o Senhor na soleira da entrada e depois sairá, mas a porta não será fechada até à tarde.

[[v26-46-3]]

^<<v26-46-3,3>>^ Nos sábados e nas luas novas o povo da terra adorará o Senhor junto à entrada que leva à porta.

[[v26-46-4]]

^<<v26-46-4,4>>^ O holocausto que o príncipe trouxer ao Senhor no dia de sábado deverá ser de seis cordeiros e um carneiro, todos sem defeito.

[[v26-46-5]]

^<<v26-46-5,5>>^ A oferta de cereal dada junto com o carneiro será de uma arroba, e a oferta de cereal com os cordeiros será de quanto ele quiser dar, mais um galão de azeite para cada arroba de ceral.

[[v26-46-6]]

^<<v26-46-6,6>>^ No dia da lua nova ele oferecerá um novilho, seis cordeiros e um carneiro, todos sem defeito.

[[v26-46-7]]

^<<v26-46-7,7>>^ Como oferta de cereal ele fornecerá uma arroba com o novilho, uma arroba com o carneiro, e com os cordeiros, quantos ele quiser dar, e mais um galão de azeite para cada uma arroba de cereal.

[[v26-46-8]]

^<<v26-46-8,8>>^ Quando o príncipe entrar, ele o fará pelo pórtico da entrada, e sairá pelo mesmo caminho.

[[v26-46-9]]

^<<v26-46-9,9>>^ " ‘Quando o povo da terra vier perante o Senhor nas festas fixas, todo aquele que entrar pela porta norte para adorá-lo sairá pela porta sul, e todo aquele que entrar pela porta sul sairá pela porta norte. Ninguém voltará pela porta pela qual entrou, mas todos sairão pela porta oposta.

[[v26-46-10]]

^<<v26-46-10,10>>^ O príncipe deverá estar no meio deles, entrando quando eles entrarem e saindo quando eles saírem.

[[v26-46-11]]

^<<v26-46-11,11>>^ " ‘Nas festas, inclusive nas festas fixas, a oferta de cereal será de uma arroba com um novilho, uma arroba com um carneiro, e de uma arroba com os cordeiros, quantos ele quiser dar, mais um galão de azeite para cada arroba.

[[v26-46-12]]

^<<v26-46-12,12>>^ Quando o príncipe fornecer uma oferta voluntária ao Senhor, seja holocausto seja oferta de comunhão, a porta que dá para o leste será aberta para ele. Ele oferecerá seu holocausto ou suas ofertas de comunhão como o faz no dia de sábado. Então ele sairá, e, depois de ter saído, a porta será trancada.

[[v26-46-13]]

^<<v26-46-13,13>>^ " ‘Diariamente vocês fornecerão um cordeiro de um ano sem defeito como holocausto ao Senhor; manhã após manhã vocês o trarão.

[[v26-46-14]]

^<<v26-46-14,14>>^ Com ele vocês também trarão, manhã após manhã, uma oferta de cereal, de um sexto de arroba e um terço de galão de azeite para umedecer a farinha. A apresentação dessa oferta de cereal será feita em obediência a um decreto perpétuo.

[[v26-46-15]]

^<<v26-46-15,15>>^ Assim o cordeiro, a oferta de cereal e o azeite serão trazidos manhã após manhã para o holocausto que será apresentado regularmente.

[[v26-46-16]]

^<<v26-46-16,16>>^ " ‘Assim diz o Soberano Senhor: Se da sua herança o príncipe fizer um presente a um de seus filhos, ele pertencerá também aos seus descendentes; será propriedade deles por herança.

[[v26-46-17]]

^<<v26-46-17,17>>^ Se, porém, da sua herança ele fizer um presente a um dos seus escravos, o escravo poderá mantê-lo consigo até o ano da liberdade; então ele voltará para o príncipe. Sua herança pertence unicamente a seus filhos; deles será.

[[v26-46-18]]

^<<v26-46-18,18>>^ O príncipe não tomará coisa alguma da herança do povo, expulsando-os de sua propriedade. Dará a seus filhos a herança daquilo que é sua própria propriedade, para que ninguém do meu povo seja separado de sua propriedade’ ".

[[v26-46-19]]

^<<v26-46-19,19>>^ Depois o homem me levou, pela entrada ao lado da porta, até os quartos sagrados que davam para o norte, os quais pertenciam aos sacerdotes, e mostrou-me um local no lado oeste.

[[v26-46-20]]

^<<v26-46-20,20>>^ Ele me disse: "Este é o lugar onde os sacerdotes cozinharão a oferta pela culpa e a oferta pelo pecado e assarão a oferta de cereal, para levá-las ao pátio externo e consagrar o povo".

[[v26-46-21]]

^<<v26-46-21,21>>^ Ele então me trouxe para o pátio externo e me fez passar por seus quatro cantos, e em cada canto vi um pátio.

[[v26-46-22]]

^<<v26-46-22,22>>^ Eram pátios fechados, com vinte metros de comprimento e quinze metros de largura; os pátios dos quatro cantos tinham a mesma medida.

[[v26-46-23]]

^<<v26-46-23,23>>^ Em volta de cada um dos quatro pátios, pelo lado de dentro, havia uma saliência de pedras, com lugares para fogo construídos em toda a sua volta debaixo da saliência.

[[v26-46-24]]

^<<v26-46-24,24>>^ Ele me disse: "Estas são as cozinhas onde aqueles que ministram no templo cozinharão os sacrifícios do povo".

'''

xref:026-ezequiel/026-ezequiel-045.adoc#v26-45-0[&#60; Capítulo Anterior] | <<v26-46-0,Topo>> | xref:026-ezequiel/026-ezequiel-047.adoc#v26-47-0[Próximo Capítulo &#62;]