include::./index.adoc[]

[[v26-14-0]]
=== Ezequiel, 14
// nvi ?, NVI - Nova Versão Internacional

[[v26-14-1]]

^<<v26-14-1,1>>^ Algumas das autoridades de Israel vieram e se sentaram diante de mim.

[[v26-14-2]]

^<<v26-14-2,2>>^ Então o Senhor me falou:

[[v26-14-3]]

^<<v26-14-3,3>>^ "Filho do homem, estes homens ergueram ídolos em seus corações e puseram tropeços ímpios diante de si. Devo deixar que me consultem?

[[v26-14-4]]

^<<v26-14-4,4>>^ Ora, diga-lhes: ‘Assim diz o Soberano Senhor: Quando qualquer israelita erguer ídolos em seu coração e puser um tropeço ímpio diante do seu rosto e depois for consultar um profeta, eu o Senhor, eu mesmo, responderei a ele conforme a sua idolatria.

[[v26-14-5]]

^<<v26-14-5,5>>^ Isto farei para reconquistar o coração da nação de Israel, que me abandonou em troca de seus ídolos’.

[[v26-14-6]]

^<<v26-14-6,6>>^ "Por isso diga à nação de Israel: ‘Assim diz o Soberano Senhor: Arrependem-se! Desviem-se dos seus ídolos e renunciem a todas as práticas detestáveis!

[[v26-14-7]]

^<<v26-14-7,7>>^ " ‘Quando qualquer israelita ou qualquer estrangeiro residente em Israel separar-se de mim e erguer ídolos em seu coração e puser um tropeço ímpio diante de si e depois for a um profeta para me consultar, eu o Senhor, eu mesmo, responderei a ele.

[[v26-14-8]]

^<<v26-14-8,8>>^ Voltarei o meu rosto contra aquele homem e farei dele um exemplo e um motivo de zombaria. Eu o eliminarei do meio do meu povo. E vocês saberão que eu sou o Senhor.

[[v26-14-9]]

^<<v26-14-9,9>>^ " ‘E, se o profeta for enganado e levado a proferir uma profecia, eu o Senhor terei enganado aquele profeta, e estenderei o meu braço contra ele e o destruirei, tirando-o do meio de Israel, meu povo.

[[v26-14-10]]

^<<v26-14-10,10>>^ O profeta será tão culpado quanto aquele que o consultar; ambos serão castigados.

[[v26-14-11]]

^<<v26-14-11,11>>^ E isso para que a nação de Israel não se desvie mais de mim, nem mais se contamine com todos os seus pecados. Serão o meu povo, e eu serei o seu Deus, palavra do Soberano Senhor’ ".

[[v26-14-12]]

^<<v26-14-12,12>>^ Esta palavra do Senhor veio a mim:

[[v26-14-13]]

^<<v26-14-13,13>>^ "Filho do homem, se uma nação pecar contra mim por infidelidade, estenderei contra ela o meu braço para cortar o seu sustento, enviar fome sobre ela e exterminar seus homens e seus animais.

[[v26-14-14]]

^<<v26-14-14,14>>^ Mesmo que estes três homens — Noé, Daniel e Jó — estivessem nela, por sua retidão eles só poderiam livrar a si mesmos, palavra do Soberano Senhor.

[[v26-14-15]]

^<<v26-14-15,15>>^ "Ou, se eu enviar animais selvagens para aquela nação e eles a deixarem sem filhos e ela for abandonada de tal forma que ninguém passe por ela, com medo dos animais,

[[v26-14-16]]

^<<v26-14-16,16>>^ juro pela minha vida, palavra do Soberano Senhor, mesmo que aqueles três homens estivessem nela, eles não poderiam livrar os seus próprios filhos ou filhas. Só a si mesmos se livrariam, e a nação seria arrasada.

[[v26-14-17]]

^<<v26-14-17,17>>^ "Ou, se eu trouxer a espada contra aquela nação e disser: ‘Que a espada passe por toda esta terra’, e eu exterminar dela os homens e os animais,

[[v26-14-18]]

^<<v26-14-18,18>>^ juro pela minha vida, palavra do Soberano Senhor, mesmo que aqueles três homens estivessem nela, eles não poderiam livrar seus próprios filhos ou filhas. Somente eles se livrariam.

[[v26-14-19]]

^<<v26-14-19,19>>^ "Ou, se eu enviar uma peste contra aquela terra e despejar sobre ela a minha ira derramando sangue, exterminando seus homens e seus animais,

[[v26-14-20]]

^<<v26-14-20,20>>^ juro pela minha vida, palavra do Soberano Senhor, mesmo que Noé, Daniel e Jó estivessem nela, eles não poderiam livrar seus filhos e suas filhas. Por sua justiça só poderiam livrar a si mesmos.

[[v26-14-21]]

^<<v26-14-21,21>>^ "Pois assim diz o Soberano Senhor: Quanto pior será quando eu enviar contra Jerusalém os meus quatro terríveis juízos: a espada, a fome, os animais selvagens e a peste, para com eles exterminar os seus homens e os seus animais!

[[v26-14-22]]

^<<v26-14-22,22>>^ Contudo, haverá alguns sobreviventes; filhos e filhas que serão retirados dela. Eles virão a vocês, e, quando vocês virem a conduta e as ações deles, vocês se sentirão consolados com relação à desgraça que eu trouxe sobre Jerusalém.

[[v26-14-23]]

^<<v26-14-23,23>>^ Vocês se sentirão consolados quando virem a conduta e as ações deles, pois saberão que não agi sem motivo em tudo quanto fiz ali, palavra do Soberano Senhor".

'''

xref:026-ezequiel/026-ezequiel-013.adoc#v26-13-0[&#60; Capítulo Anterior] | <<v26-14-0,Topo>> | xref:026-ezequiel/026-ezequiel-015.adoc#v26-15-0[Próximo Capítulo &#62;]