include::./index.adoc[]

[[v26-7-0]]
=== Ezequiel, 7
// nvi ?, NVI - Nova Versão Internacional

[[v26-7-1]]

^<<v26-7-1,1>>^ Veio a mim esta palavra do Senhor:

[[v26-7-2]]

^<<v26-7-2,2>>^ "Filho do homem, assim diz o Soberano Senhor à nação de Israel: Chegou o fim! O fim chegou aos quatro cantos da terra de Israel.

[[v26-7-3]]

^<<v26-7-3,3>>^ O fim está agora sobre você, e sobre você eu soltarei a minha ira. Eu a julgarei de acordo com a sua conduta e lhe retribuirei todas as suas práticas repugnantes.

[[v26-7-4]]

^<<v26-7-4,4>>^ Não olharei com piedade para você nem a pouparei; com certeza eu lhe retribuirei sua conduta e suas práticas em seu meio. Então você saberá que eu sou o Senhor".

[[v26-7-5]]

^<<v26-7-5,5>>^ Assim diz o Soberano Senhor: Chegou a desgraça! Uma desgraça jamais imaginada vem aí.

[[v26-7-6]]

^<<v26-7-6,6>>^ Chegou o fim! Chegou o fim! Ele se insurgiu contra você. O fim chegou!

[[v26-7-7]]

^<<v26-7-7,7>>^ A condenação chegou sobre você, você que habita no país. Chegou a hora, o dia está próximo; há pânico, e não alegria, sobre os montes.

[[v26-7-8]]

^<<v26-7-8,8>>^ Estou para derramar a minha ira sobre você e esgotar a minha indignação contra você; eu a julgarei de acordo com a sua conduta e lhe retribuirei todas as suas práticas repugnantes.

[[v26-7-9]]

^<<v26-7-9,9>>^ Não olharei com piedade para você nem a pouparei; eu lhe retribuirei de acordo com todas as práticas repugnantes que há no seu meio. Então tu saberás que é o Senhor que desfere o golpe.

[[v26-7-10]]

^<<v26-7-10,10>>^ "Aqui está o dia! Já chegou! A condenação irrompeu, a vara brotou, a arrogância floresceu!

[[v26-7-11]]

^<<v26-7-11,11>>^ A violência encarnou-se numa vara para castigar a maldade; ninguém do povo será deixado, ninguém daquela multidão, como também nenhuma riqueza, nada que tenha algum valor.

[[v26-7-12]]

^<<v26-7-12,12>>^ Chegou a hora, o dia chegou. Que o comprador não se regozije nem o vendedor se entristeça, pois a ira está sobre toda a multidão.

[[v26-7-13]]

^<<v26-7-13,13>>^ Nenhum vendedor viverá o suficiente para recuperar a terra que vendeu, mesmo que viva por muito tempo, pois a visão acerca de toda a multidão não voltará atrás. Por causa de sua iniqüidade, a vida de ninguém será preservada.

[[v26-7-14]]

^<<v26-7-14,14>>^ Embora toquem a trombeta e deixem tudo pronto, ninguém irá a combate, pois a minha ira está sobre toda a sua multidão".

[[v26-7-15]]

^<<v26-7-15,15>>^ "Fora está a espada, dentro estão a peste e a fome; quem estiver no campo morrerá pela espada, e quem estiver na cidade será devorado pela fome e pela peste.

[[v26-7-16]]

^<<v26-7-16,16>>^ Todos os que se livrarem e escaparem estarão nos montes, gemendo como pombas nos vales, cada um por causa de sua própria iniqüidade.

[[v26-7-17]]

^<<v26-7-17,17>>^ Toda mão ficará pendendo, frouxa, e todo joelho ficará como água, de tão fraco.

[[v26-7-18]]

^<<v26-7-18,18>>^ Eles se cobrirão de vestes de luto e se vestirão de pavor. Seus rostos serão cobertos de vergonha, e suas cabeças serão rapadas.

[[v26-7-19]]

^<<v26-7-19,19>>^ Atirarão sua prata nas ruas, e seu ouro será tratado como coisa impura. Sua prata e seu ouro serão incapazes de livrá-los no dia da ira do Senhor e, não poderão saciar sua fome e encher os seus estômagos; serviram apenas para fazê-los tropeçar na iniqüidade.

[[v26-7-20]]

^<<v26-7-20,20>>^ Tinham orgulho de suas lindas jóias e as usavam para fazer os seus ídolos repugnantes e as suas imagens detestáveis. Por isso tornarei essas coisas em algo impuro para eles.

[[v26-7-21]]

^<<v26-7-21,21>>^ Entregarei tudo isso como despojo nas mãos de estrangeiros e como saque nas mãos dos ímpios da terra, e eles o contaminarão.

[[v26-7-22]]

^<<v26-7-22,22>>^ Desviarei deles o meu rosto, e eles profanarão o lugar que tanto amo; nele entrarão ladrões e o profanarão.

[[v26-7-23]]

^<<v26-7-23,23>>^ "Preparem correntes, porque a terra está cheia de sangue derramado e a cidade está cheia de violência.

[[v26-7-24]]

^<<v26-7-24,24>>^ Trarei os piores elementos das nações para se apossarem das casas deles; darei fim ao orgulho dos poderosos, e os santuários deles serão profanados.

[[v26-7-25]]

^<<v26-7-25,25>>^ Quando chegar o pavor, eles buscarão paz, mas não a encontrarão.

[[v26-7-26]]

^<<v26-7-26,26>>^ Virá uma desgraça após a outra, e um alarme após o outro. Tentarão conseguir uma visão da parte do profeta; o ensino da lei pelo sacerdote se perderá, como também o conselho das autoridades.

[[v26-7-27]]

^<<v26-7-27,27>>^ O rei pranteará, o príncipe se vestirá de desespero, e as mãos do povo da terra tremerão. Lidarei com eles de acordo com a sua conduta, e pelos padrões deles mesmos eu os julgarei. Então saberão que eu sou o Senhor".

'''

xref:026-ezequiel/026-ezequiel-006.adoc#v26-6-0[&#60; Capítulo Anterior] | <<v26-7-0,Topo>> | xref:026-ezequiel/026-ezequiel-008.adoc#v26-8-0[Próximo Capítulo &#62;]