include::./index.adoc[]

[[v26-39-0]]
=== Ezequiel, 39
// nvi ?, NVI - Nova Versão Internacional

[[v26-39-1]]

^<<v26-39-1,1>>^ "Filho do homem, profetize contra Gogue e diga: ‘Assim diz o Soberano Senhor: Eu estou contra você, ó Gogue, príncipe maior de Meseque e de Tubal.

[[v26-39-2]]

^<<v26-39-2,2>>^ Farei você girar e o arrastarei. Eu o trarei do extremo norte e o enviarei contra os montes de Israel.

[[v26-39-3]]

^<<v26-39-3,3>>^ Então derrubarei o arco da sua mão esquerda e farei suas flechas caírem da sua mão direita.

[[v26-39-4]]

^<<v26-39-4,4>>^ Nos montes de Israel você cairá, você e todas as suas tropas e as nações que estiverem com você. Eu darei você como comida a todo tipo de ave que come carniça e aos animais do campo.

[[v26-39-5]]

^<<v26-39-5,5>>^ Você cairá em campo aberto, pois eu falei, palavra do Soberano Senhor.

[[v26-39-6]]

^<<v26-39-6,6>>^ Mandarei fogo sobre Magogue e sobre aqueles que vivem em segurança nas regiões costeiras, e eles saberão que eu sou o Senhor.

[[v26-39-7]]

^<<v26-39-7,7>>^ " ‘Farei conhecido o meu santo nome no meio do meu povo Israel. Não mais deixarei que o meu nome seja profanado, e as nações saberão que eu, o Senhor, sou o Santo de Israel.

[[v26-39-8]]

^<<v26-39-8,8>>^ E aí vem! É certo que acontecerá, palavra do Soberano Senhor. Este é o dia de que eu falei.

[[v26-39-9]]

^<<v26-39-9,9>>^ " ‘Então aqueles que morarem nas cidades de Israel sairão e usarão armas como combustível e as queimarão: os escudos, pequenos e grandes, os arcos e flechas, os bastões de guerra e as lanças. Durante sete anos eles as utilizarão como combustível.

[[v26-39-10]]

^<<v26-39-10,10>>^ Não precisarão ajuntar lenha nos campos nem cortá-la nas florestas, porque eles usarão as armas como combustível. E eles despojarão aqueles que os despojaram e saquearão aqueles que os saquearam, palavra do Soberano Senhor.

[[v26-39-11]]

^<<v26-39-11,11>>^ " ‘Naquele dia darei a Gogue um túmulo em Israel, no vale dos que viajam para o oriente na direção do Mar. Ele bloqueará o caminho dos viajantes porque Gogue e todos os seus batalhões serão sepultados ali. Por isso será chamado vale de Hamom-Gogue.

[[v26-39-12]]

^<<v26-39-12,12>>^ " ‘Durante sete meses a nação de Israel os estará sepultando a fim de purificar a terra.

[[v26-39-13]]

^<<v26-39-13,13>>^ Todo o povo da terra os sepultará, e o dia em que eu for glorificado será para eles um dia memorável, palavra do Soberano Senhor.

[[v26-39-14]]

^<<v26-39-14,14>>^ " ‘Depois dos sete meses serão contratados homens para percorrer a terra e sepultar os que ainda restarem. E assim a terra será purificada.

[[v26-39-15]]

^<<v26-39-15,15>>^ Quando estiverem percorrendo a terra e um deles vir um osso humano, fincará um marco ao lado do osso até que os coveiros o sepultem no vale de Hamom-Gogue.

[[v26-39-16]]

^<<v26-39-16,16>>^ ( Também haverá ali uma cidade à qual se dará o nome de Hamoná. ) E assim eles purificarão a terra’.

[[v26-39-17]]

^<<v26-39-17,17>>^ "Filho do homem, assim diz o Soberano Senhor: Chame todo tipo de ave e todos os animais do campo: ‘Venham de todos os lugares ao redor e reúnam-se para o sacrifício que estou preparando para vocês, o grande sacrifício nos montes de Israel. Ali vocês comerão carne e beberão sangue.

[[v26-39-18]]

^<<v26-39-18,18>>^ Comerão a carne de poderosos e beberão o sangue dos príncipes da terra como se eles fossem carneiros, cordeiros, bodes e novilhos, todos eles animais gordos de Basã.

[[v26-39-19]]

^<<v26-39-19,19>>^ No sacrifício que lhes estou preparando, vocês comerão gordura até empanturrar-se e beberão sangue até embriagar-se.

[[v26-39-20]]

^<<v26-39-20,20>>^ À minha mesa vocês comerão sua porção de cavalos e cavaleiros, de homens poderosos e soldados de todo tipo’, palavra do Soberano Senhor.

[[v26-39-21]]

^<<v26-39-21,21>>^ "Exibirei a minha glória entre as nações, e todas as nações verão o castigo que eu trouxer e a mão que eu colocar sobre eles.

[[v26-39-22]]

^<<v26-39-22,22>>^ Daquele dia em diante a nação de Israel saberá que eu sou o Senhor, o seu Deus.

[[v26-39-23]]

^<<v26-39-23,23>>^ E as nações saberão que o povo de Israel foi para o exílio por causa de sua iniqüidade, porque me foram infiéis. Por isso escondi deles o meu rosto e os entreguei nas mãos de seus inimigos, e eles caíram pela espada.

[[v26-39-24]]

^<<v26-39-24,24>>^ Tratei com eles de acordo com a sua impureza e com as suas transgressões, e escondi deles o meu rosto.

[[v26-39-25]]

^<<v26-39-25,25>>^ "Por isso, assim diz o Soberano Senhor: Agora trarei Jacó de volta do cativeiro e terei compaixão de toda a nação de Israel, e serei zeloso pelo meu santo nome.

[[v26-39-26]]

^<<v26-39-26,26>>^ Eles se esquecerão da vergonha por que passaram e de toda a infidelidade que mostraram para comigo enquanto viviam em segurança em sua terra sem que ninguém lhes causasse medo.

[[v26-39-27]]

^<<v26-39-27,27>>^ Quando eu os tiver trazido de volta das nações e os tiver ajuntado de entre as terras de seus inimigos, eu me revelarei santo por meio deles à vista de muitas nações.

[[v26-39-28]]

^<<v26-39-28,28>>^ Então eles saberão que eu sou o Senhor, o seu Deus, pois, embora os tenha enviado para o exílio entre as nações, eu os reunirei em sua própria terra, sem deixar um único deles para trás.

[[v26-39-29]]

^<<v26-39-29,29>>^ Não mais esconderei deles o rosto, pois derramarei o meu Espírito sobre a nação de Israel, palavra do Soberano Senhor".

'''

xref:026-ezequiel/026-ezequiel-038.adoc#v26-38-0[&#60; Capítulo Anterior] | <<v26-39-0,Topo>> | xref:026-ezequiel/026-ezequiel-040.adoc#v26-40-0[Próximo Capítulo &#62;]