include::./index.adoc[]

[[v61-3-0]]
=== 2 Pedro, 3
// nvi ?, NVI - Nova Versão Internacional

[[v61-3-1]]

^<<v61-3-1,1>>^ Amados, esta é agora a segunda carta que lhes escrevo. Em ambas quero despertar com estas lembranças a sua mente sincera para que vocês se lembrem

[[v61-3-2]]

^<<v61-3-2,2>>^ das palavras proferidas no passado pelos santos profetas, e do mandamento de nosso Senhor e Salvador que os apóstolos de vocês lhes ensinaram.

[[v61-3-3]]

^<<v61-3-3,3>>^ Antes de tudo saibam que, nos últimos dias, surgirão escarnecedores zombando e seguindo suas próprias paixões.

[[v61-3-4]]

^<<v61-3-4,4>>^ Eles dirão: "O que houve com a promessa da sua vinda? Desde que os antepassados morreram, tudo continua como desde o princípio da criação".

[[v61-3-5]]

^<<v61-3-5,5>>^ Mas eles deliberadamente se esquecem de que há muito tempo, pela palavra de Deus, existiam céus e terra, esta formada da água e pela água.

[[v61-3-6]]

^<<v61-3-6,6>>^ E pela água o mundo daquele tempo foi submerso e destruído.

[[v61-3-7]]

^<<v61-3-7,7>>^ Pela mesma palavra os céus e a terra que agora existem estão reservados para o fogo, guardados para o dia do juízo e para a destruição dos ímpios.

[[v61-3-8]]

^<<v61-3-8,8>>^ Não se esqueçam disto, amados: para o Senhor um dia é como mil anos, e mil anos como um dia.

[[v61-3-9]]

^<<v61-3-9,9>>^ O Senhor não demora em cumprir a sua promessa, como julgam alguns. Pelo contrário, ele é paciente com vocês, não querendo que ninguém pereça, mas que todos cheguem ao arrependimento.

[[v61-3-10]]

^<<v61-3-10,10>>^ O dia do Senhor, porém, virá como ladrão. Os céus desaparecerão com um grande estrondo, os elementos serão desfeitos pelo calor, e a terra, e tudo o que nela há, será desnudada.

[[v61-3-11]]

^<<v61-3-11,11>>^ Visto que tudo será assim desfeito, que tipo de pessoas é necessário que vocês sejam? Vivam de maneira santa e piedosa,

[[v61-3-12]]

^<<v61-3-12,12>>^ esperando o dia de Deus e apressando a sua vinda. Naquele dia os céus serão desfeitos pelo fogo, e os elementos se derreterão pelo calor.

[[v61-3-13]]

^<<v61-3-13,13>>^ Todavia, de acordo com a sua promessa, esperamos novos céus e nova terra, onde habita a justiça.

[[v61-3-14]]

^<<v61-3-14,14>>^ Portanto, amados, enquanto esperam estas coisas, empenhem-se para serem encontrados por ele em paz, imaculados e inculpáveis.

[[v61-3-15]]

^<<v61-3-15,15>>^ Tenham em mente que a paciência de nosso Senhor significa salvação, como também o nosso amado irmão Paulo lhes escreveu, com a sabedoria que Deus lhe deu.

[[v61-3-16]]

^<<v61-3-16,16>>^ Ele escreve da mesma forma em todas as suas cartas, falando nelas destes assuntos. Suas cartas contêm algumas coisas difíceis de entender, as quais os ignorantes e instáveis torcem, como também o fazem com as demais Escrituras, para a própria destruição deles.

[[v61-3-17]]

^<<v61-3-17,17>>^ Portanto, amados, sabendo disso, guardem-se para que não sejam levados pelo erro dos que não têm princípios morais, nem percam a sua firmeza e caiam.

[[v61-3-18]]

^<<v61-3-18,18>>^ Cresçam, porém, na graça e no conhecimento de nosso Senhor e Salvador Jesus Cristo. A ele seja a glória, agora e para sempre! Amém.

'''

xref:061-2-pedro/061-2-pedro-002.adoc#v61-2-0[&#60; Capítulo Anterior] | <<v61-3-0,Topo>> | xref:062-1-joao/062-1-joao-001.adoc#v62-1-0[Próximo Capítulo &#62;]