include::./index.adoc[]

[[v61-2-0]]
=== 2 Pedro, 2
// nvi ?, NVI - Nova Versão Internacional

[[v61-2-1]]

^<<v61-2-1,1>>^ No passado surgiram falsos profetas no meio do povo, como também surgirão entre vocês falsos mestres. Estes introduzirão secretamente heresias destruidoras, chegando a negar o Soberano que os resgatou, trazendo sobre si mesmos repentina destruição.

[[v61-2-2]]

^<<v61-2-2,2>>^ Muitos seguirão os caminhos vergonhosos desses homens e, por causa deles, será difamado o caminho da verdade.

[[v61-2-3]]

^<<v61-2-3,3>>^ Em sua cobiça, tais mestres os explorarão com histórias que inventaram. Há muito tempo a sua condenação paira sobre eles, e a sua destruição não tarda.

[[v61-2-4]]

^<<v61-2-4,4>>^ Pois Deus não poupou os anjos que pecaram, mas os lançou no inferno, prendendo-os em abismos tenebrosos a fim de serem reservados para o juízo.

[[v61-2-5]]

^<<v61-2-5,5>>^ Ele não poupou o mundo antigo quando trouxe o dilúvio sobre aquele povo ímpio, mas preservou Noé, pregador da justiça, e mais sete pessoas.

[[v61-2-6]]

^<<v61-2-6,6>>^ Também condenou as cidades de Sodoma e Gomorra, reduzindo-as a cinzas, tornando-as exemplo do que acontecerá aos ímpios;

[[v61-2-7]]

^<<v61-2-7,7>>^ mas livrou Ló, homem justo, que se afligia com o procedimento libertino dos que não tinham princípios morais

[[v61-2-8]]

^<<v61-2-8,8>>^ ( pois, vivendo entre eles, todos os dias aquele justo se atormentava em sua alma justa por causa das maldades que via e ouvia ).

[[v61-2-9]]

^<<v61-2-9,9>>^ Vemos, portanto, que o Senhor sabe livrar os piedosos da provação e manter em castigo os ímpios para o dia do juízo,

[[v61-2-10]]

^<<v61-2-10,10>>^ especialmente os que seguem os desejos impuros da carne e desprezam a autoridade. Insolentes e arrogantes, tais homens não têm medo de difamar os seres celestiais;

[[v61-2-11]]

^<<v61-2-11,11>>^ contudo, nem os anjos, embora sendo maiores em força e poder, fazem acusações injuriosas contra aqueles seres na presença do Senhor.

[[v61-2-12]]

^<<v61-2-12,12>>^ Mas eles difamam o que desconhecem e são como criaturas irracionais, guiadas pelo instinto, nascidas para serem capturadas e destruídas; serão corrompidos pela sua própria corrupção!

[[v61-2-13]]

^<<v61-2-13,13>>^ Eles receberão retribuição pela injustiça que causaram. Consideram prazer entregar-se à devassidão em plena luz do dia. São nódoas e manchas, regalando-se em seus prazeres, quando participam das festas de vocês.

[[v61-2-14]]

^<<v61-2-14,14>>^ Tendo os olhos cheios de adultério, nunca param de pecar, iludem os instáveis e têm o coração exercitado na ganância. Malditos!

[[v61-2-15]]

^<<v61-2-15,15>>^ Eles abandonaram o caminho reto e se desviaram, seguindo o caminho de Balaão, filho de Beor, que amou o salário da injustiça,

[[v61-2-16]]

^<<v61-2-16,16>>^ mas em sua transgressão foi repreendido por uma jumenta, um animal mudo, que falou com voz humana e refreou a insensatez do profeta.

[[v61-2-17]]

^<<v61-2-17,17>>^ Esses homens são fontes sem água e névoas impelidas pela tempestade. A escuridão das trevas lhes está reservada,

[[v61-2-18]]

^<<v61-2-18,18>>^ pois eles, com palavras de vaidosa arrogância e provocando os desejos libertinos da carne, seduzem os que estão quase conseguindo fugir daqueles que vivem no erro.

[[v61-2-19]]

^<<v61-2-19,19>>^ Prometendo-lhes liberdade, eles mesmos são escravos da corrupção, pois o homem é escravo daquilo que o domina.

[[v61-2-20]]

^<<v61-2-20,20>>^ Se, tendo escapado das contaminações do mundo por meio do conhecimento de nosso Senhor e Salvador Jesus Cristo, encontram-se novamente nelas enredados e por elas dominados, estão em pior estado do que no princípio.

[[v61-2-21]]

^<<v61-2-21,21>>^ Teria sido melhor que não tivessem conhecido o caminho da justiça, do que, depois de o terem conhecido, voltarem as costas para o santo mandamento que lhes foi transmitido.

[[v61-2-22]]

^<<v61-2-22,22>>^ Confirma-se neles que é verdadeiro o provérbio: "O cão voltou ao seu vômito" e ainda: "A porca lavada voltou a revolver-se na lama".

'''

xref:061-2-pedro/061-2-pedro-001.adoc#v61-1-0[&#60; Capítulo Anterior] | <<v61-2-0,Topo>> | xref:061-2-pedro/061-2-pedro-003.adoc#v61-3-0[Próximo Capítulo &#62;]