include::./index.adoc[]

[[v61-1-0]]
=== 2 Pedro, 1
// nvi ?, NVI - Nova Versão Internacional

[[v61-1-1]]

^<<v61-1-1,1>>^ Simão Pedro, servo e apóstolo de Jesus Cristo, àqueles que, mediante a justiça de nosso Deus e Salvador Jesus Cristo, receberam conosco uma fé igualmente valiosa:

[[v61-1-2]]

^<<v61-1-2,2>>^ Graça e paz lhes sejam multiplicadas, pelo pleno conhecimento de Deus e de Jesus, o nosso Senhor.

[[v61-1-3]]

^<<v61-1-3,3>>^ Seu divino poder nos deu todas as coisas de que necessitamos para a vida e para a piedade, por meio do pleno conhecimento daquele que nos chamou para a sua própria glória e virtude.

[[v61-1-4]]

^<<v61-1-4,4>>^ Por intermédio destas ele nos deu as suas grandiosas e preciosas promessas, para que por elas vocês se tornassem participantes da natureza divina e fugissem da corrupção que há no mundo, causada pela cobiça.

[[v61-1-5]]

^<<v61-1-5,5>>^ Por isso mesmo, empenhem-se para acrescentar à sua fé a virtude; à virtude o conhecimento;

[[v61-1-6]]

^<<v61-1-6,6>>^ ao conhecimento o domínio próprio; ao domínio próprio a perseverança; à perseverança a piedade;

[[v61-1-7]]

^<<v61-1-7,7>>^ à piedade a fraternidade; e à fraternidade o amor.

[[v61-1-8]]

^<<v61-1-8,8>>^ Porque, se essas qualidades existirem e estiverem crescendo em suas vidas, elas impedirão que vocês, no pleno conhecimento de nosso Senhor Jesus Cristo, sejam inoperantes e improdutivos.

[[v61-1-9]]

^<<v61-1-9,9>>^ Todavia, se alguém não as tem, está cego, só vê o que está perto, esquecendo-se da purificação dos seus antigos pecados.

[[v61-1-10]]

^<<v61-1-10,10>>^ Portanto, irmãos, empenhem-se ainda mais para consolidar o chamado e a eleição de vocês, pois se agirem dessa forma, jamais tropeçarão,

[[v61-1-11]]

^<<v61-1-11,11>>^ e assim vocês estarão ricamente providos quando entrarem no Reino eterno de nosso Senhor e Salvador Jesus Cristo.

[[v61-1-12]]

^<<v61-1-12,12>>^ Por isso, sempre terei o cuidado de lembrar-lhes estas coisas, se bem que vocês já as sabem e estão solidamente firmados na verdade que receberam.

[[v61-1-13]]

^<<v61-1-13,13>>^ Considero importante, enquanto estiver no tabernáculo deste corpo, despertar a memória de vocês,

[[v61-1-14]]

^<<v61-1-14,14>>^ porque sei que em breve deixarei este tabernáculo, como o nosso Senhor Jesus Cristo já me revelou.

[[v61-1-15]]

^<<v61-1-15,15>>^ Eu me empenharei para que, também depois da minha partida, vocês sejam sempre capazes de lembrar-se destas coisas.

[[v61-1-16]]

^<<v61-1-16,16>>^ De fato, não seguimos fábulas engenhosamente inventadas, quando lhes falamos a respeito do poder e da vinda de nosso Senhor Jesus Cristo; pelo contrário, nós fomos testemunhas oculares da sua majestade.

[[v61-1-17]]

^<<v61-1-17,17>>^ Ele recebeu honra e glória da parte de Deus Pai, quando da suprema glória lhe foi dirigida a voz que disse: "Este é o meu filho amado, em quem me agrado".

[[v61-1-18]]

^<<v61-1-18,18>>^ Nós mesmos ouvimos essa voz vinda do céu, quando estávamos com ele no monte santo.

[[v61-1-19]]

^<<v61-1-19,19>>^ Assim, temos ainda mais firme a palavra dos profetas, e vocês farão bem se a ela prestarem atenção, como a uma candeia que brilha em lugar escuro, até que o dia clareie e a estrela da alva nasça em seus corações.

[[v61-1-20]]

^<<v61-1-20,20>>^ Antes de mais nada, saibam que nenhuma profecia da Escritura provém de interpretação pessoal,

[[v61-1-21]]

^<<v61-1-21,21>>^ pois jamais a profecia teve origem na vontade humana, mas homens falaram da parte de Deus, impelidos pelo Espírito Santo.

'''

xref:060-1-pedro/060-1-pedro-005.adoc#v60-5-0[&#60; Capítulo Anterior] | <<v61-1-0,Topo>> | xref:061-2-pedro/061-2-pedro-002.adoc#v61-2-0[Próximo Capítulo &#62;]