include::./index.adoc[]

[[v38-11-0]]
=== Zacarias, 11
// nvi ?, NVI - Nova Versão Internacional

[[v38-11-1]]

^<<v38-11-1,1>>^ Abra as suas portas, ó Líbano, para que o fogo devore os seus cedros.

[[v38-11-2]]

^<<v38-11-2,2>>^ Agonize, ó pinheiro, porque o cedro caiu e as majestosas árvores foram devastadas. Agonizem, carvalhos de Basã, pois a floresta densa está sendo derrubada.

[[v38-11-3]]

^<<v38-11-3,3>>^ Ouçam o gemido dos pastores; os seus formosos pastos foram desvastados. Ouçam o rugido dos leões; pois a rica floresta do Jordão foi destruída.

[[v38-11-4]]

^<<v38-11-4,4>>^ Assim diz o Senhor, o meu Deus: "Pastoreie o rebanho destinado à matança,

[[v38-11-5]]

^<<v38-11-5,5>>^ porque os seus compradores o matam e ninguém os castiga. Aqueles que o vendem dizem: ‘Bendito seja Deus, estou rico! ’ Nem os próprios pastores poupam o rebanho.

[[v38-11-6]]

^<<v38-11-6,6>>^ Por isso, não pouparei mais os habitantes desta terra", diz o Senhor. "Entregarei cada um ao seu próximo e a seu rei. Eles acabarão com a terra e eu não livrarei ninguém das suas mãos".

[[v38-11-7]]

^<<v38-11-7,7>>^ Eu me tornei pastor do rebanho destinado à matança, os oprimidos do rebanho. Então peguei duas varas e chamei a uma Favor e à outra União, e com elas pastoreei o rebanho.

[[v38-11-8]]

^<<v38-11-8,8>>^ Num mês eu me livrei dos três pastores. Porque eu me cansei deles e o rebanho me detestava.

[[v38-11-9]]

^<<v38-11-9,9>>^ Então eu disse: Não serei o pastor de vocês. Morram as que estão morrendo, pereçam as que estão perecendo. E as que sobrarem comam a carne umas das outras.

[[v38-11-10]]

^<<v38-11-10,10>>^ Então peguei a vara chamada Favor e a quebrei, cancelando a aliança que tinha feito com todas as nações.

[[v38-11-11]]

^<<v38-11-11,11>>^ Foi cancelada naquele dia, e assim os aflitos do rebanho que estavam me olhando entenderam que essa palavra era do Senhor.

[[v38-11-12]]

^<<v38-11-12,12>>^ Eu lhes disse: Se acharem melhor assim, paguem-me; se não, não me paguem. Então eles me pagaram trinta moedas de prata.

[[v38-11-13]]

^<<v38-11-13,13>>^ E o Senhor me disse: "Lance isto ao oleiro", o ótimo preço pelo qual me avaliaram! Por isso tomei as trinta moedas de prata e as atirei no templo do Senhor para o oleiro.

[[v38-11-14]]

^<<v38-11-14,14>>^ Depois disso, quebrei minha segunda vara, chamada União, rompendo a relação de irmãos entre Judá e Israel.

[[v38-11-15]]

^<<v38-11-15,15>>^ Então o Senhor me disse: "Pegue novamente os utensílios de um pastor insensato.

[[v38-11-16]]

^<<v38-11-16,16>>^ Porque levantarei nesta terra um pastor que não se preocupará com as ovelhas perdidas, nem procurará a que está solta, nem curará as machucadas, nem alimentará as sadias, mas comerá a carne das ovelhas mais gordas, arrancando as suas patas.

[[v38-11-17]]

^<<v38-11-17,17>>^ Ai do pastor imprestável, que abandona o rebanho! Que a espada fira o seu braço e fure o seu olho direito! Que o seu braço seque completamente, e fique totalmente cego o seu olho direito! "

'''

xref:038-zacarias/038-zacarias-010.adoc#v38-10-0[&#60; Capítulo Anterior] | <<v38-11-0,Topo>> | xref:038-zacarias/038-zacarias-012.adoc#v38-12-0[Próximo Capítulo &#62;]