include::./index.adoc[]

[[v38-4-0]]
=== Zacarias, 4
// nvi ?, NVI - Nova Versão Internacional

[[v38-4-1]]

^<<v38-4-1,1>>^ Depois o anjo que falava comigo tornou a despertar-me, como se desperta alguém do sono,

[[v38-4-2]]

^<<v38-4-2,2>>^ e me perguntou: "O que você está vendo? " Respondi: "Vejo um candelabro de ouro maciço com um recipiente para azeite na parte superior e sete lâmpadas e sete canos para as lâmpadas.

[[v38-4-3]]

^<<v38-4-3,3>>^ Há também duas oliveiras junto ao recipiente, uma à direita e outra à esquerda".

[[v38-4-4]]

^<<v38-4-4,4>>^ Perguntei ao anjo que falava comigo: "O que significa isto, meu senhor? "

[[v38-4-5]]

^<<v38-4-5,5>>^ Ele disse: "Você não sabe? " "Não, meu senhor", respondi.

[[v38-4-6]]

^<<v38-4-6,6>>^ "Esta é a palavra do Senhor para Zorobabel: ‘Não por força nem por violência, mas pelo meu Espírito’, diz o Senhor dos Exércitos.

[[v38-4-7]]

^<<v38-4-7,7>>^ "Quem você pensa que é, ó montanha majestosa? Diante de Zorobabel você se tornará uma planície. Ele colocará a pedra principal aos gritos de ‘Deus abençoe! Deus abençoe! ’ "

[[v38-4-8]]

^<<v38-4-8,8>>^ Então o Senhor me falou:

[[v38-4-9]]

^<<v38-4-9,9>>^ "As mãos de Zorobabel colocacaram os fundamentos deste templo; suas mãos também o terminarão. Assim saberão que o Senhor dos Exércitos me enviou a vocês.

[[v38-4-10]]

^<<v38-4-10,10>>^ "Pois aqueles que desprezaram o dia das pequenas coisas terão grande alegria ao verem a pedra principal nas mãos de Zorobabel". Então ele me disse: "Estas sete lâmpadas são os olhos do Senhor, que sondam toda a terra".

[[v38-4-11]]

^<<v38-4-11,11>>^ A seguir perguntei ao anjo: "O que significam estas duas oliveiras à direita e à esquerda do candelabro? "

[[v38-4-12]]

^<<v38-4-12,12>>^ E perguntei também: "O que significam estes dois ramos de oliveira ao lado dos dois tubos de ouro que derramam azeite dourado? "

[[v38-4-13]]

^<<v38-4-13,13>>^ Ele disse: "Você não sabe? " "Não, meu senhor", respondi.

[[v38-4-14]]

^<<v38-4-14,14>>^ Então ele me disse: "São os dois homens que foram ungidos para servir ao Soberano de toda a terra! "

'''

xref:038-zacarias/038-zacarias-003.adoc#v38-3-0[&#60; Capítulo Anterior] | <<v38-4-0,Topo>> | xref:038-zacarias/038-zacarias-005.adoc#v38-5-0[Próximo Capítulo &#62;]