include::./index.adoc[]

[[v38-8-0]]
=== Zacarias, 8
// nvi ?, NVI - Nova Versão Internacional

[[v38-8-1]]

^<<v38-8-1,1>>^ Mais uma vez veio a mim a palavra do Senhor dos Exércitos:

[[v38-8-2]]

^<<v38-8-2,2>>^ Assim diz o Senhor dos Exércitos: "Tenho muito ciúme de Sião; estou me consumindo de ciúmes por ela".

[[v38-8-3]]

^<<v38-8-3,3>>^ Assim diz o Senhor: "Estou voltando para Sião e habitarei em Jerusalém. Então Jerusalém será chamada Cidade da Verdade, e o monte do Senhor dos Exércitos será chamado Monte Sagrado".

[[v38-8-4]]

^<<v38-8-4,4>>^ Assim diz o Senhor dos Exércitos: "Homens e mulheres de idade avançada voltarão a sentar-se nas praças de Jerusalém, cada um com sua bengala, por causa da idade.

[[v38-8-5]]

^<<v38-8-5,5>>^ As ruas da cidade ficarão cheias de meninos e meninas brincando".

[[v38-8-6]]

^<<v38-8-6,6>>^ Assim diz o Senhor dos Exércitos: "Mesmo que isso pareça impossível para o remanescente deste povo naquela época, será impossível para mim? ", declara o Senhor dos Exércitos.

[[v38-8-7]]

^<<v38-8-7,7>>^ Assim diz o Senhor dos Exércitos: "Salvarei meu povo dos países do leste e do oeste.

[[v38-8-8]]

^<<v38-8-8,8>>^ Eu os trarei de volta para que habitem em Jerusalém; serão meu povo e eu serei o Deus deles, com fidelidade e justiça".

[[v38-8-9]]

^<<v38-8-9,9>>^ Assim diz o Senhor dos Exércitos: "Vocês que estão ouvindo hoje estas palavras já proferidas pelos profetas quando foram lançados os alicerces do templo do Senhor dos Exércitos, fortaleçam as mãos para que o templo seja construído.

[[v38-8-10]]

^<<v38-8-10,10>>^ Pois antes daquele tempo não havia salários para os homens nem para os animais. Ninguém podia tratar os seus negócios com segurança por causa de seus adversários, porque eu tinha posto cada um contra o seu próximo.

[[v38-8-11]]

^<<v38-8-11,11>>^ Mas agora não vou mais tratar com o remanescente deste povo como fiz no passado", declara o Senhor dos Exércitos.

[[v38-8-12]]

^<<v38-8-12,12>>^ "Haverá uma rica semeadura, a videira dará o seu fruto, a terra produzirá suas colheitas e o céu derramará o orvalho. E darei todas essas coisas como uma herança ao remanescente deste povo.

[[v38-8-13]]

^<<v38-8-13,13>>^ Assim como vocês foram uma maldição para as nações, ó Judá e Israel, também os salvarei e vocês serão uma bênção. Não tenham medo, antes sejam fortes. "

[[v38-8-14]]

^<<v38-8-14,14>>^ Assim diz o Senhor dos Exércitos: "Assim como eu havia decidido castigar vocês sem compaixão quando os seus antepassados me enfureceram", diz o Senhor dos Exércitos,

[[v38-8-15]]

^<<v38-8-15,15>>^ "também agora decidi fazer de novo o bem a Jerusalém e a Judá. Não tenham medo!

[[v38-8-16]]

^<<v38-8-16,16>>^ Eis o que devem fazer: Falem somente a verdade uns com os outros, e julguem retamente em seus tribunais;

[[v38-8-17]]

^<<v38-8-17,17>>^ não planejem no íntimo o mal contra o seu próximo, e não queiram jurar com falsidade. Porque eu odeio todas essas coisas", declara o Senhor.

[[v38-8-18]]

^<<v38-8-18,18>>^ Mais uma vez veio a mim a palavra do Senhor dos Exércitos.

[[v38-8-19]]

^<<v38-8-19,19>>^ Assim diz o Senhor dos Exércitos: "Os jejuns do quarto, do quinto, do sétimo e do décimo meses serão ocasiões alegres e cheias de júbilo, festas felizes para o povo de Judá. Por isso amem a verdade e a paz".

[[v38-8-20]]

^<<v38-8-20,20>>^ Assim diz o Senhor dos Exércitos: "Povos e habitantes de muitas cidades ainda virão,

[[v38-8-21]]

^<<v38-8-21,21>>^ e os habitantes de uma cidade irão a outra e dirão: ‘Vamos logo suplicar o favor do Senhor e buscar o Senhor dos Exércitos. Eu mesmo já estou indo’.

[[v38-8-22]]

^<<v38-8-22,22>>^ E muitos povos e nações poderosas virão buscar o Senhor dos Exércitos em Jerusalém e suplicar o seu favor".

[[v38-8-23]]

^<<v38-8-23,23>>^ Assim diz o Senhor dos Exércitos: "Naqueles dias, dez homens de todas as línguas e nações agarrarão firmemente a barra das vestes de um judeu e dirão: ‘Nós vamos com você porque ouvimos dizer que Deus está com vocês’ ".

'''

xref:038-zacarias/038-zacarias-007.adoc#v38-7-0[&#60; Capítulo Anterior] | <<v38-8-0,Topo>> | xref:038-zacarias/038-zacarias-009.adoc#v38-9-0[Próximo Capítulo &#62;]