include::./index.adoc[]

[[v38-10-0]]
=== Zacarias, 10
// nvi ?, NVI - Nova Versão Internacional

[[v38-10-1]]

^<<v38-10-1,1>>^ Peça ao Senhor a chuva de primavera, pois, é o Senhor quem faz o trovão, quem manda a chuva e lhes dá as plantas do campo.

[[v38-10-2]]

^<<v38-10-2,2>>^ Porque os ídolos falam mentiras, os adivinhadores têm falsas visões, e contam sonhos enganadores; o consolo que trazem é vão. Por isso o povo vagueia como ovelhas, aflitas pela falta de um pastor.

[[v38-10-3]]

^<<v38-10-3,3>>^ "Contra os pastores acende-se a minha ira, e contra os líderes eu agirei". Porque o Senhor dos Exércitos cuida de seu rebanho, o povo de Judá. Ele fará dele o seu brioso corcel na batalha.

[[v38-10-4]]

^<<v38-10-4,4>>^ Dele virão a pedra fundamental, e a estaca da tenda, o arco da batalha e os governantes.

[[v38-10-5]]

^<<v38-10-5,5>>^ Juntos serão como guerreiros que pisam a lama das ruas na batalha. Lutarão e derrubarão os cavaleiros porque o Senhor estará com eles.

[[v38-10-6]]

^<<v38-10-6,6>>^ "Assim, eu fortalecerei a tribo de Judá e salvarei a casa de José. Eu os restaurarei porque tenho compaixão deles. Eles serão como se eu nunca os tivesse rejeitado, porque eu sou o Senhor, o Deus deles, e lhes responderei.

[[v38-10-7]]

^<<v38-10-7,7>>^ Efraim será como um homem poderoso; seu coração se alegrará como se fosse com vinho, seus filhos o verão e se alegrarão; seus corações exultarão no Senhor.

[[v38-10-8]]

^<<v38-10-8,8>>^ Assobiarei para eles e os ajuntarei, pois eu já os resgatei. Serão numerosos como antes.

[[v38-10-9]]

^<<v38-10-9,9>>^ Embora eu os espalhe por entre os povos de terras distantes, eles se lembrarão de mim. Criarão seus filhos e voltarão.

[[v38-10-10]]

^<<v38-10-10,10>>^ Eu os farei retornar do Egito e os ajuntarei de volta da Assíria. Eu os levarei para as terras de Gileade e do Líbano, e mesmo assim não haverá espaço suficiente para eles.

[[v38-10-11]]

^<<v38-10-11,11>>^ Passarei pelo mar da aflição, ferirei o mar revoltoso, e as profundezas do Nilo se secarão. O orgulho da Assíria será abatido e o poder do Egito será derrubado.

[[v38-10-12]]

^<<v38-10-12,12>>^ Eu os fortalecerei no Senhor, em meu nome marcharão", diz o Senhor.

'''

xref:038-zacarias/038-zacarias-009.adoc#v38-9-0[&#60; Capítulo Anterior] | <<v38-10-0,Topo>> | xref:038-zacarias/038-zacarias-011.adoc#v38-11-0[Próximo Capítulo &#62;]