include::./index.adoc[]

[[v38-14-0]]
=== Zacarias, 14
// nvi ?, NVI - Nova Versão Internacional

[[v38-14-1]]

^<<v38-14-1,1>>^ Vejam, o dia do Senhor vem, quando no meio de vocês os seus bens serão divididos.

[[v38-14-2]]

^<<v38-14-2,2>>^ Reunirei todos os povos para lutarem contra Jerusalém; a cidade será conquistada, as casas saqueadas e as mulheres violentadas. Metade da população será levada para o exílio, mas o restante do povo não será tirado da cidade.

[[v38-14-3]]

^<<v38-14-3,3>>^ Depois o Senhor sairá à guerra contra aquelas nações, como ele faz em dia de batalha.

[[v38-14-4]]

^<<v38-14-4,4>>^ Naquele dia os seus pés estarão sobre o monte das Oliveiras, a leste de Jerusalém, e o monte se dividirá ao meio, de leste a oeste, por um grande vale, metade do monte será removido para o norte, a outra metade para o sul.

[[v38-14-5]]

^<<v38-14-5,5>>^ Vocês fugirão pelo meu vale entre os montes, pois ele se estenderá até Azel. Fugirão como fugiram do terremoto nos dias de Uzias, rei de Judá. Então o Senhor, o meu Deus, virá com todos os seus santos.

[[v38-14-6]]

^<<v38-14-6,6>>^ Naquele dia não haverá calor nem frio.

[[v38-14-7]]

^<<v38-14-7,7>>^ Será um dia único, no qual não haverá separação entre dia e noite, porque quando chegar a noite ainda estará claro. Um dia que o Senhor conhece.

[[v38-14-8]]

^<<v38-14-8,8>>^ Naquele dia águas correntes fluirão de Jerusalém, metade delas para o mar do leste e metade para o mar do oeste. Isto acontecerá tanto no verão quanto no inverno.

[[v38-14-9]]

^<<v38-14-9,9>>^ O Senhor será rei de toda a terra. Naquele dia haverá um só Senhor e o seu nome será o único nome.

[[v38-14-10]]

^<<v38-14-10,10>>^ A terra toda, de Geba até Rimom, ao sul de Jerusalém, será semelhante à Arabá. Mas Jerusalém será restabelecida e permanecerá em seu lugar, desde a porta de Benjamim até o lugar da primeira porta, até a porta da Esquina, e desde a torre de Hananeel até aos lagares do rei.

[[v38-14-11]]

^<<v38-14-11,11>>^ Será habitada; nunca mais será destruída. Jerusalém estará segura.

[[v38-14-12]]

^<<v38-14-12,12>>^ Esta é a praga com a qual o Senhor castigará todas as nações que lutarem contra Jerusalém: Sua carne apodrecerá enquanto estiverem ainda em pé, seus olhos apodrecerão em suas órbitas e sua língua apodrecerá dentro de suas bocas.

[[v38-14-13]]

^<<v38-14-13,13>>^ Naquele dia grande confusão dominará essas nações, causada pelo Senhor. Cada um atacará o que estiver ao seu lado.

[[v38-14-14]]

^<<v38-14-14,14>>^ Também Judá lutará em Jerusalém. A riqueza de todas as nações vizinhas será recolhida, grandes quantidades de ouro, prata e roupas.

[[v38-14-15]]

^<<v38-14-15,15>>^ A mesma praga cairá sobre cavalos e mulas, camelos e burros, sobre todos os animais daquelas nações.

[[v38-14-16]]

^<<v38-14-16,16>>^ Então, os sobreviventes de todas as nações que atacaram Jerusalém subirão ano após ano para adorar o rei, o Senhor dos Exércitos, para celebrar a festa das Cabanas.

[[v38-14-17]]

^<<v38-14-17,17>>^ Se algum dentre os povos da terra não subir a Jerusalém para adorar o Rei, o Senhor dos Exércitos, não virá para ele a chuva.

[[v38-14-18]]

^<<v38-14-18,18>>^ Se os egípcios não subirem para participar, o Senhor mandará sobre eles a praga com a qual afligirá as nações que se recusarem a ir celebrar a festa das Cabanas.

[[v38-14-19]]

^<<v38-14-19,19>>^ Sim, essa será a punição do Egito e de todas as nações que não forem celebrar a festa das Cabanas.

[[v38-14-20]]

^<<v38-14-20,20>>^ Naquele dia estará inscrito nas sinetas penduradas nos cavalos: "Separado para o Senhor". Os caldeirões do templo do Senhor serão tão sagrados quanto as bacias diante do altar.

[[v38-14-21]]

^<<v38-14-21,21>>^ Cada panela de Jerusalém e de Judá será separada para o Senhor dos Exércitos, e todos os que vierem sacrificar pegarão panelas e cozinharão nelas. E a partir daquele dia, nunca mais haverá comerciantes no templo do Senhor dos Exércitos.

'''

xref:038-zacarias/038-zacarias-013.adoc#v38-13-0[&#60; Capítulo Anterior] | <<v38-14-0,Topo>> | xref:039-malaquias/039-malaquias-001.adoc#v39-1-0[Próximo Capítulo &#62;]