include::./index.adoc[]

[[v38-13-0]]
=== Zacarias, 13
// nvi ?, NVI - Nova Versão Internacional

[[v38-13-1]]

^<<v38-13-1,1>>^ "Naquele dia uma fonte jorrará para os descendentes de Davi e para os habitantes de Jerusalém, para purificá-los do pecado e da impureza.

[[v38-13-2]]

^<<v38-13-2,2>>^ "Naquele dia eliminarei da terra de Israel os nomes dos ídolos, e nunca mais serão lembrados", diz o Senhor dos Exércitos. "Removerei da terra tanto os profetas como o espírito imundo.

[[v38-13-3]]

^<<v38-13-3,3>>^ E se alguém ainda profetizar, seu próprio pai e sua mãe lhe advertirão: ‘Você tem que morrer porque disse mentiras em nome do Senhor’. Quando ele profetizar, os seus próprios pais o esfaquearão.

[[v38-13-4]]

^<<v38-13-4,4>>^ "Naquele dia todo profeta se envergonhará de sua visão profética. Não usará o manto de profeta feito de pele, para enganar.

[[v38-13-5]]

^<<v38-13-5,5>>^ Ele dirá: ‘Eu não sou profeta. Sou um homem do campo; a terra tem sido o meu sustento desde a minha mocidade’.

[[v38-13-6]]

^<<v38-13-6,6>>^ Se alguém lhe perguntar: ‘Que feridas são estas no seu corpo? ’, ele responderá: ‘Eu fui ferido na casa de meus amigos’.

[[v38-13-7]]

^<<v38-13-7,7>>^ "Levante-se, ó espada, contra o meu pastor, contra o meu companheiro! ", declara o Senhor dos Exércitos. "Fira o pastor, e as ovelhas se dispersarão, e voltarei minha mão para os pequeninos.

[[v38-13-8]]

^<<v38-13-8,8>>^ Na terra toda, dois terços serão ceifados e morrerão; todavia a terça parte permanecerá", diz o Senhor.

[[v38-13-9]]

^<<v38-13-9,9>>^ "Colocarei essa terça parte no fogo, e a refinarei como prata, e a purificarei como ouro. Ela invocará o meu nome, e eu lhe responderei. É o meu povo, direi; e ela dirá: ‘O Senhor é o meu Deus’. "

'''

xref:038-zacarias/038-zacarias-012.adoc#v38-12-0[&#60; Capítulo Anterior] | <<v38-13-0,Topo>> | xref:038-zacarias/038-zacarias-014.adoc#v38-14-0[Próximo Capítulo &#62;]