include::./index.adoc[]

[[v38-7-0]]
=== Zacarias, 7
// nvi ?, NVI - Nova Versão Internacional

[[v38-7-1]]

^<<v38-7-1,1>>^ No quarto ano do reinado do rei Dario, a palavra do Senhor veio a Zacarias, no quarto dia do nono mês, o mês de quisleu.

[[v38-7-2]]

^<<v38-7-2,2>>^ Foi quando o povo de Betel enviou Sarezer e Régen-Meleque com seus homens, para suplicarem ao Senhor

[[v38-7-3]]

^<<v38-7-3,3>>^ perguntando aos sacerdotes do templo do Senhor dos Exércitos e aos profetas: "Devemos lamentar e jejuar no quinto mês, como já faz tantos anos que estamos fazendo? "

[[v38-7-4]]

^<<v38-7-4,4>>^ Então o Senhor dos Exércitos me falou:

[[v38-7-5]]

^<<v38-7-5,5>>^ "Pergunte a todo o povo e aos sacerdotes: Quando vocês jejuaram no quinto e no sétimo meses durante os últimos setenta anos, foi de fato para mim que jejuaram?

[[v38-7-6]]

^<<v38-7-6,6>>^ E quando comiam e bebiam, não era para vocês mesmos que o faziam?

[[v38-7-7]]

^<<v38-7-7,7>>^ Não são essas as palavras do Senhor proclamadas pelos antigos profetas quando Jerusalém e as cidades ao seu redor estavam em paz e prosperavam, e o Neguebe e a Sefelá eram habitados? "

[[v38-7-8]]

^<<v38-7-8,8>>^ E a palavra do Senhor veio novamente a Zacarias:

[[v38-7-9]]

^<<v38-7-9,9>>^ "Assim diz o Senhor dos Exércitos: ‘Administrem a verdadeira justiça, mostrem misericórdia e compaixão uns para com os outros.

[[v38-7-10]]

^<<v38-7-10,10>>^ Não oprimam a viúva e o órfão, nem o estrangeiro e o necessitado. Nem tramem maldades uns contra os outros’.

[[v38-7-11]]

^<<v38-7-11,11>>^ "Mas eles se recusaram a dar atenção; teimosamente viraram as costas e taparam os ouvidos.

[[v38-7-12]]

^<<v38-7-12,12>>^ Endureceram o coração para não ouvirem a Lei e as palavras que o Senhor dos Exércitos tinha falado pelo seu Espírito por meio dos antigos profetas. Por isso o Senhor dos Exércitos irou-se muito".

[[v38-7-13]]

^<<v38-7-13,13>>^ " ‘Quando eu os chamei, não deram ouvidos; por isso, quando eles me chamarem, também não ouvirei’, diz o Senhor dos Exércitos.

[[v38-7-14]]

^<<v38-7-14,14>>^ ‘Eu os espalhei com um vendaval entre nações que eles nem conhecem. A terra que deixaram para trás ficou tão destruída que ninguém podia atravessá-la. Foi assim que transformaram a terra aprazível em ruínas’ ".

'''

xref:038-zacarias/038-zacarias-006.adoc#v38-6-0[&#60; Capítulo Anterior] | <<v38-7-0,Topo>> | xref:038-zacarias/038-zacarias-008.adoc#v38-8-0[Próximo Capítulo &#62;]