include::./index.adoc[]

[[v38-12-0]]
=== Zacarias, 12
// nvi ?, NVI - Nova Versão Internacional

[[v38-12-1]]

^<<v38-12-1,1>>^ Esta é a palavra do Senhor para Israel. Palavra do Senhor, que estende os céus, assenta o alicerce da terra e forma o espírito do homem dentro dele:

[[v38-12-2]]

^<<v38-12-2,2>>^ "Farei de Jerusalém uma taça que embriague todos os povos ao seu redor, que estarão no cerco contra Judá e Jerusalém.

[[v38-12-3]]

^<<v38-12-3,3>>^ Naquele dia, quando todas as nações da terra estiverem reunidas para atacá-la, farei de Jerusalém uma pedra pesada para todas as nações. Todos que tentarem levantá-la se machucarão muito.

[[v38-12-4]]

^<<v38-12-4,4>>^ Naquele dia deixarei todos os cavalos em pânico e os seus cavaleiros loucos", diz o Senhor. "Protegerei o povo de Judá, mas cegarei todos os cavalos das nações.

[[v38-12-5]]

^<<v38-12-5,5>>^ Então os líderes de Judá pensarão: ‘Os habitantes de Jerusalém são fortes porque o Senhor dos Exércitos é o seu Deus! ’

[[v38-12-6]]

^<<v38-12-6,6>>^ "Naquele dia farei que os líderes de Judá sejam semelhantes a um braseiro no meio de um monte de lenha, como uma tocha incandescente entre gravetos. Eles consumirão à direita e à esquerda todos os povos ao redor, mas Jerusalém permanecerá intacta em seu lugar.

[[v38-12-7]]

^<<v38-12-7,7>>^ "O Senhor salvará primeiro as tendas de Judá, para que a honra da família de Davi e dos habitantes de Jerusalém não seja superior à de Judá.

[[v38-12-8]]

^<<v38-12-8,8>>^ Naquele dia o Senhor protegerá os que vivem em Jerusalém, de forma que o mais fraco dentre eles será como Davi, e a família de Davi será como Deus, como o anjo do Senhor que vai adiante deles.

[[v38-12-9]]

^<<v38-12-9,9>>^ "Naquele dia procurarei destruir todas as nações que atacarem Jerusalém.

[[v38-12-10]]

^<<v38-12-10,10>>^ E derramarei sobre a família de Davi e sobre os habitantes de Jerusalém um espírito de ação de graças e de súplicas. Olharão para mim, aquele a quem traspassaram, e chorarão por ele como quem chora a perda de um filho único, e lamentarão amargamente por ele como quem lamenta a perda do filho mais velho.

[[v38-12-11]]

^<<v38-12-11,11>>^ Naquele dia muitos chorarão em Jerusalém, como os que choraram em Hadade-Rimon no vale de Megido.

[[v38-12-12]]

^<<v38-12-12,12>>^ Todo o país chorará, separadamente cada família com suas mulheres chorará: a família de Davi com suas mulheres; a família de Natã com suas mulheres;

[[v38-12-13]]

^<<v38-12-13,13>>^ a família de Levi com suas mulheres; a família de Simei com suas mulheres,

[[v38-12-14]]

^<<v38-12-14,14>>^ e todas as demais famílias com suas mulheres.

'''

xref:038-zacarias/038-zacarias-011.adoc#v38-11-0[&#60; Capítulo Anterior] | <<v38-12-0,Topo>> | xref:038-zacarias/038-zacarias-013.adoc#v38-13-0[Próximo Capítulo &#62;]