include::./index.adoc[]

[[v38-2-0]]
=== Zacarias, 2
// nvi ?, NVI - Nova Versão Internacional

[[v38-2-1]]

^<<v38-2-1,1>>^ Olhei em seguida, e vi um homem segurando uma corda de medir.

[[v38-2-2]]

^<<v38-2-2,2>>^ Eu lhe perguntei: "Aonde você vai? " Ele me respondeu: "Vou medir Jerusalém para saber o seu comprimento e a sua largura".

[[v38-2-3]]

^<<v38-2-3,3>>^ Então o anjo que falava comigo retirou-se, e outro anjo foi ao seu encontro

[[v38-2-4]]

^<<v38-2-4,4>>^ e lhe disse: "Corra e diga àquele jovem: ‘Jerusalém será habitada como uma cidade sem muros por causa dos seus muitos habitantes e rebanhos.

[[v38-2-5]]

^<<v38-2-5,5>>^ E eu mesmo serei para ela um muro de fogo ao seu redor’, declara o Senhor, ‘e dentro dela serei a sua glória’.

[[v38-2-6]]

^<<v38-2-6,6>>^ "Atenção! Atenção! Fujam da terra do norte", declara o Senhor, "porque eu os espalhei aos quatro ventos da terra", diz o Senhor.

[[v38-2-7]]

^<<v38-2-7,7>>^ "Atenção, ó Sião! Escapem, vocês que vivem na cidade da Babilônia!

[[v38-2-8]]

^<<v38-2-8,8>>^ Porque assim diz o Senhor dos Exércitos: ‘Ele me enviou para buscar a sua glória entre as nações que saquearam vocês, porque todo o que neles tocar, toca na pupila dos olhos dele’.

[[v38-2-9]]

^<<v38-2-9,9>>^ Certamente levantarei a minha mão contra elas de forma que serão um espólio para os seus servos. Então vocês saberão que foi o Senhor dos Exércitos que me enviou.

[[v38-2-10]]

^<<v38-2-10,10>>^ "Cante e alegre-se, ó cidade de Sião! Porque venho fazer de você a minha habitação", declara o Senhor.

[[v38-2-11]]

^<<v38-2-11,11>>^ "Muitas nações se unirão ao Senhor naquele dia e se tornarão meu povo. Então você será a minha habitação e você reconhecerá que o Senhor dos Exércitos me enviou a você.

[[v38-2-12]]

^<<v38-2-12,12>>^ O Senhor herdará Judá como sua propriedade na terra santa e escolherá de novo Jerusalém.

[[v38-2-13]]

^<<v38-2-13,13>>^ Aquietem-se todos perante o Senhor, porque ele se levantou de sua santa habitação".

'''

xref:038-zacarias/038-zacarias-001.adoc#v38-1-0[&#60; Capítulo Anterior] | <<v38-2-0,Topo>> | xref:038-zacarias/038-zacarias-003.adoc#v38-3-0[Próximo Capítulo &#62;]