include::./index.adoc[]

[[v38-6-0]]
=== Zacarias, 6
// nvi ?, NVI - Nova Versão Internacional

[[v38-6-1]]

^<<v38-6-1,1>>^ Olhei novamente, e vi diante de mim quatro carruagens que vinham saindo do meio de duas montanhas de bronze.

[[v38-6-2]]

^<<v38-6-2,2>>^ À primeira estavam atrelados cavalos vermelhos, à segunda, cavalos pretos,

[[v38-6-3]]

^<<v38-6-3,3>>^ à terceira, cavalos brancos, e à quarta, cavalos malhados. Todos eram vigorosos.

[[v38-6-4]]

^<<v38-6-4,4>>^ Perguntei ao anjo que falava comigo: "Que representam estes cavalos atrelados, meu senhor? "

[[v38-6-5]]

^<<v38-6-5,5>>^ O anjo me respondeu: "Estes são os quatro espíritos do céu, que acabam de sair da presença do Soberano de toda a terra.

[[v38-6-6]]

^<<v38-6-6,6>>^ A carruagem puxada pelos cavalos pretos vai em direção à terra do norte, a que tem cavalos brancos vai em direção ao oriente, e a que tem cavalos malhados vai para a terra do sul".

[[v38-6-7]]

^<<v38-6-7,7>>^ Os vigorosos cavalos avançavam, impacientes por percorrer a terra. E o anjo lhes disse: "Percorram toda a terra! " E eles foram.

[[v38-6-8]]

^<<v38-6-8,8>>^ Então ele me chamou e disse: "Veja, os que foram para a terra do norte deram repouso ao meu Espírito naquela terra".

[[v38-6-9]]

^<<v38-6-9,9>>^ E o Senhor me ordenou:

[[v38-6-10]]

^<<v38-6-10,10>>^ "Tome prata e ouro dos exilados Heldai, Tobias e Jedaías, que chegaram da Babilônia. No mesmo dia vá à casa de Josias, filho de Sofonias.

[[v38-6-11]]

^<<v38-6-11,11>>^ Pegue a prata e o ouro, faça uma coroa, e coloque-a na cabeça do sumo sacerdote Josué, filho de Jeozadaque.

[[v38-6-12]]

^<<v38-6-12,12>>^ Diga-lhe que assim diz o Senhor dos Exércitos: ‘Aqui está o homem cujo nome é Renovo, e ele sairá do seu lugar e construirá o templo do Senhor.

[[v38-6-13]]

^<<v38-6-13,13>>^ Ele construirá o templo do Senhor, será revestido de majestade e se assentará em seu trono para governar. E ele será sacerdote no trono. E haverá harmonia entre os dois’.

[[v38-6-14]]

^<<v38-6-14,14>>^ A coroa será para Heldai, Tobias, Jedaías e Hem, filho de Sofonias como um memorial no templo do Senhor.

[[v38-6-15]]

^<<v38-6-15,15>>^ Gente de longe virá ajudar a construir o templo do Senhor. Então vocês saberão que o Senhor dos Exércitos me enviou a vocês. Isto só acontecerá se obedecerem fielmente à voz do Senhor, o seu Deus".

'''

xref:038-zacarias/038-zacarias-005.adoc#v38-5-0[&#60; Capítulo Anterior] | <<v38-6-0,Topo>> | xref:038-zacarias/038-zacarias-007.adoc#v38-7-0[Próximo Capítulo &#62;]