include::./index.adoc[]

[[v38-1-0]]
=== Zacarias, 1
// nvi ?, NVI - Nova Versão Internacional

[[v38-1-1]]

^<<v38-1-1,1>>^ No oitavo mês do segundo ano do reinado de Dario, a palavra do Senhor veio ao profeta Zacarias, filho de Berequias e neto de Ido:

[[v38-1-2]]

^<<v38-1-2,2>>^ "O Senhor muito se irou contra os seus antepassados.

[[v38-1-3]]

^<<v38-1-3,3>>^ Por isso diga ao povo: Assim diz o Senhor dos Exércitos: ‘Voltem para mim, e eu me voltarei para vocês’, diz o Senhor dos Exércitos.

[[v38-1-4]]

^<<v38-1-4,4>>^ Não sejam como os seus antepassados aos quais os antigos profetas proclamaram: Assim diz o Senhor dos Exércitos: ‘Deixem os seus caminhos e as suas más obras. Mas eles não me ouviram nem me deram atenção’, declara o Senhor.

[[v38-1-5]]

^<<v38-1-5,5>>^ Onde estão agora os seus antepassados? E os profetas, acaso vivem eles para sempre?

[[v38-1-6]]

^<<v38-1-6,6>>^ Mas as minhas palavras e os meus decretos, que ordenei aos meus servos, os profetas, alcançaram os seus antepassados e os levaram a converter-se e a dizer: ‘O Senhor dos Exércitos fez conosco o que os nossos caminhos e práticas mereciam, conforme prometeu’ ".

[[v38-1-7]]

^<<v38-1-7,7>>^ No dia vigésimo quarto do décimo primeiro mês, o mês de sebate, no segundo ano do reinado de Dario, a palavra do Senhor veio ao profeta Zacarias, filho de Berequias e neto de Ido:

[[v38-1-8]]

^<<v38-1-8,8>>^ Durante a noite tive uma visão; apareceu na minha frente um homem montado num cavalo vermelho. Ele estava parado entre as murtas num desfiladeiro. Atrás dele havia cavalos vermelhos, marrons e brancos.

[[v38-1-9]]

^<<v38-1-9,9>>^ Então perguntei: Quem são estes, meu senhor? O anjo que estava falando comigo respondeu: "Eu lhe mostrarei quem são".

[[v38-1-10]]

^<<v38-1-10,10>>^ Então o homem que estava entre as murtas explicou: "São aqueles que o Senhor enviou por toda a terra".

[[v38-1-11]]

^<<v38-1-11,11>>^ E eles relataram ao anjo do Senhor que estava entre as murtas: "Percorremos toda a terra e a encontramos em paz e tranqüila".

[[v38-1-12]]

^<<v38-1-12,12>>^ Então o anjo do Senhor respondeu: "Senhor dos Exércitos, até quando deixarás de ter misericórdia de Jerusalém e das cidades de Judá, com as quais estás indignado há setenta anos? "

[[v38-1-13]]

^<<v38-1-13,13>>^ Então o Senhor respondeu palavras boas e confortadoras ao anjo que falava comigo.

[[v38-1-14]]

^<<v38-1-14,14>>^ E o anjo me disse: "Proclame: Assim diz o Senhor dos Exércitos: ‘Eu tenho sido muito zeloso com Jerusalém e Sião,

[[v38-1-15]]

^<<v38-1-15,15>>^ mas estou muito irado contra as nações que se sentem seguras. Porque eu estava apenas um pouco irado com meu povo, mas elas aumentaram a dor que ele sofria! ’

[[v38-1-16]]

^<<v38-1-16,16>>^ "Por isso, assim diz o Senhor: ‘Estou voltando-me para Jerusalém com misericórdia, e ali o meu templo será reconstruído. A corda de medir será esticada sobre Jerusalém’, declara o Senhor dos Exércitos.

[[v38-1-17]]

^<<v38-1-17,17>>^ "Diga mais: Assim diz o Senhor dos Exércitos: ‘As minhas cidades transbordarão de prosperidade novamente, e o Senhor consolará novamente a Sião e escolherá Jerusalém’ ".

[[v38-1-18]]

^<<v38-1-18,18>>^ Depois eu olhei para o alto, e vi quatro chifres.

[[v38-1-19]]

^<<v38-1-19,19>>^ Então perguntei ao anjo que falava comigo: "O que são estes? " Ele me respondeu: "Estes são os chifres que dispersaram Judá, Israel e Jerusalém".

[[v38-1-20]]

^<<v38-1-20,20>>^ Depois o Senhor mostrou-me quatro artesãos.

[[v38-1-21]]

^<<v38-1-21,21>>^ Eu perguntei: "O que eles vêm fazer? " Ele respondeu: "Estes são os chifres que dispersaram Judá a ponto de ninguém sequer conseguir levantar a cabeça, mas os artesãos vieram aterrorizar e quebrar esses chifres das nações que se levantaram contra o povo de Judá para dispersá-lo".

'''

xref:037-ageu/037-ageu-002.adoc#v37-2-0[&#60; Capítulo Anterior] | <<v38-1-0,Topo>> | xref:038-zacarias/038-zacarias-002.adoc#v38-2-0[Próximo Capítulo &#62;]