include::./index.adoc[]

[[v38-3-0]]
=== Zacarias, 3
// nvi ?, NVI - Nova Versão Internacional

[[v38-3-1]]

^<<v38-3-1,1>>^ Depois disso ele me mostrou o sumo sacerdote Josué diante do anjo do Senhor, e Satanás, à sua direita, para acusá-lo.

[[v38-3-2]]

^<<v38-3-2,2>>^ O anjo do Senhor disse a Satanás: "O Senhor o repreenda, Satanás! O Senhor que escolheu Jerusalém o repreenda! Este homem não parece um tição tirado do fogo? "

[[v38-3-3]]

^<<v38-3-3,3>>^ Ora, Josué, vestido de roupas impuras, estava de pé diante do anjo.

[[v38-3-4]]

^<<v38-3-4,4>>^ O anjo disse aos que estavam diante dele: "Tirem as roupas impuras dele". Depois disse a Josué: "Veja, eu tirei de você o seu pecado, e coloquei vestes nobres sobre você".

[[v38-3-5]]

^<<v38-3-5,5>>^ Disse também: "Coloquem um turbante limpo em sua cabeça". Colocaram o turbante nele e o vestiram, enquanto o anjo do Senhor observava.

[[v38-3-6]]

^<<v38-3-6,6>>^ O anjo do Senhor exortou a Josué, dizendo:

[[v38-3-7]]

^<<v38-3-7,7>>^ "Assim diz o Senhor dos Exércitos: ‘Se você andar nos meus caminhos e obedecer aos meus preceitos, você governará a minha casa e também estará encarregado das minhas cortes, e eu lhe darei um lugar entre estes que estão aqui.

[[v38-3-8]]

^<<v38-3-8,8>>^ " ‘Ouçam bem, sumo sacerdote Josué e seus companheiros sentados diante de você, homens que prefiguram coisas que virão: Vou trazer o meu servo, o Renovo.

[[v38-3-9]]

^<<v38-3-9,9>>^ Vejam a pedra que coloquei na frente de Josué! Ela tem sete pares de olhos, e eu gravarei nela uma inscrição’, declara o Senhor dos Exércitos, ‘e removerei o pecado desta terra num único dia.

[[v38-3-10]]

^<<v38-3-10,10>>^ " ‘Naquele dia’, declara o Senhor dos Exércitos, ‘cada um de vocês convidará seu próximo para assentar-se debaixo da sua videira e debaixo da sua figueira’ ".

'''

xref:038-zacarias/038-zacarias-002.adoc#v38-2-0[&#60; Capítulo Anterior] | <<v38-3-0,Topo>> | xref:038-zacarias/038-zacarias-004.adoc#v38-4-0[Próximo Capítulo &#62;]