include::./index.adoc[]

[[v38-5-0]]
=== Zacarias, 5
// nvi ?, NVI - Nova Versão Internacional

[[v38-5-1]]

^<<v38-5-1,1>>^ Levantei novamente os olhos, e vi diante de mim um pergaminho que voava.

[[v38-5-2]]

^<<v38-5-2,2>>^ O anjo me perguntou: "O que você está vendo? " Respondi: "Vejo um pergaminho voando, com nove metros de comprimento por quatro e meio de largura".

[[v38-5-3]]

^<<v38-5-3,3>>^ Então ele me disse: "Nele está escrita a maldição que está sendo derramada sobre toda a terra: porque tanto o ladrão como o que jura falsamente serão expulsos, conforme essa maldição.

[[v38-5-4]]

^<<v38-5-4,4>>^ Assim declara o Senhor dos Exércitos: ‘Eu lancei essa maldição para que ela entre na casa do ladrão e na casa do que jura falsamente pelo meu nome. Ela ficará em sua casa e destruirá tanto as vigas como os tijolos! ’ "

[[v38-5-5]]

^<<v38-5-5,5>>^ Em seguida o anjo que falava comigo se adiantou e me disse: "Olhe e veja o que vem surgindo".

[[v38-5-6]]

^<<v38-5-6,6>>^ Perguntei o que era aquilo, e ele me respondeu: "É um cesto". E disse mais: "Aí está o pecado de todo o povo desta terra".

[[v38-5-7]]

^<<v38-5-7,7>>^ Então a tampa de chumbo foi retirada, e ali dentro do cesto estava uma mulher sentada!

[[v38-5-8]]

^<<v38-5-8,8>>^ Ele disse: "Esta é a Perversidade", e a empurrou para dentro do cesto e o tapou de novo com a tampa de chumbo.

[[v38-5-9]]

^<<v38-5-9,9>>^ De novo ergui os olhos e vi chegarem à minha frente duas mulheres com asas como de cegonha; o vento impeliu suas asas, e elas ergueram o cesto entre o céu e a terra.

[[v38-5-10]]

^<<v38-5-10,10>>^ Perguntei ao anjo: "Para onde estão levando o cesto? "

[[v38-5-11]]

^<<v38-5-11,11>>^ Ele respondeu: "Para a Babilônia, onde vão construir um santuário para ele. Quando ficar pronto, o cesto será colocado lá, em seu pedestal".

'''

xref:038-zacarias/038-zacarias-004.adoc#v38-4-0[&#60; Capítulo Anterior] | <<v38-5-0,Topo>> | xref:038-zacarias/038-zacarias-006.adoc#v38-6-0[Próximo Capítulo &#62;]