include::./index.adoc[]

[[v38-9-0]]
=== Zacarias, 9
// nvi ?, NVI - Nova Versão Internacional

[[v38-9-1]]

^<<v38-9-1,1>>^ A advertência do Senhor é contra a terra de Hadraque e cairá sobre Damasco, porque os olhos do Senhor estão sobre toda a humanidade e sobre todas as tribos de Israel,

[[v38-9-2]]

^<<v38-9-2,2>>^ e também sobre Hamate que faz fronteira com Damasco, e sobre Tiro e Sidom, embora sejam muito sábias.

[[v38-9-3]]

^<<v38-9-3,3>>^ Tiro construiu para si uma fortaleza; acumulou prata como pó, e ouro como lama das ruas.

[[v38-9-4]]

^<<v38-9-4,4>>^ Mas o Senhor se apossará dela e lançará no mar suas riquezas, e ela será consumida pelo fogo.

[[v38-9-5]]

^<<v38-9-5,5>>^ Ao ver isso Ascalom ficará com medo; Gaza também se contorcerá de agonia, assim como Ecrom, porque a sua esperança fracassou. Gaza perderá o seu rei, e Ascalom ficará deserta.

[[v38-9-6]]

^<<v38-9-6,6>>^ Um povo bastardo ocupará Asdode, e assim eu acabarei com o orgulho dos filisteus.

[[v38-9-7]]

^<<v38-9-7,7>>^ Tirarei o sangue de suas bocas, e a comida proibida dentre os seus dentes. Aquele que restar pertencerá ao nosso Deus e se tornará chefe em Judá, e Ecrom será como os jebuseus.

[[v38-9-8]]

^<<v38-9-8,8>>^ Defenderei a minha casa contra os invasores. Nunca mais um opressor passará por cima do meu povo, porque agora eu vejo isso com os meus próprios olhos.

[[v38-9-9]]

^<<v38-9-9,9>>^ Alegre-se muito, cidade de Sião! Exulte, Jerusalém! Eis que o seu rei vem a você, justo e vitorioso, humilde e montado num jumento, um jumentinho, cria de jumenta.

[[v38-9-10]]

^<<v38-9-10,10>>^ Ele destruirá os carros de guerra de Efraim e os cavalos de Jerusalém, e os arcos de batalha serão quebrados. Ele proclamará paz às nações e dominará de um mar a outro, e do Eufrates até aos confins da terra.

[[v38-9-11]]

^<<v38-9-11,11>>^ Quanto a você, por causa do sangue da minha aliança com você, libertarei os seus prisioneiros de um poço sem água.

[[v38-9-12]]

^<<v38-9-12,12>>^ Voltem à sua fortaleza, ó prisioneiros da esperança; pois hoje mesmo anuncio que restaurarei tudo em dobro para vocês.

[[v38-9-13]]

^<<v38-9-13,13>>^ Quando eu curvar Judá como se curva um arco e usar Efraim como flecha, levantarei os filhos de Sião contra os filhos da Grécia, e farei você semelhante à espada de um guerreiro.

[[v38-9-14]]

^<<v38-9-14,14>>^ Então o Senhor aparecerá sobre eles; sua flecha brilhará como o relâmpago. O Soberano Senhor tocará a trombeta e marchará em meio às tempestades do sul;

[[v38-9-15]]

^<<v38-9-15,15>>^ o Senhor dos Exércitos os protegerá. Eles pisotearão e destruirão as pedras das atiradeiras. Eles beberão o sangue do inimigo como se fosse vinho; estarão cheios como a bacia usada para aspergir água nos cantos do altar.

[[v38-9-16]]

^<<v38-9-16,16>>^ Naquele dia o Senhor, o seu Deus, os salvará como rebanho do seu povo, e como jóias de uma coroa brilharão em sua terra.

[[v38-9-17]]

^<<v38-9-17,17>>^ Ah! Como serão belos! Como serão formosos! O trigo dará vigor aos rapazes, e o vinho novo às moças.

'''

xref:038-zacarias/038-zacarias-008.adoc#v38-8-0[&#60; Capítulo Anterior] | <<v38-9-0,Topo>> | xref:038-zacarias/038-zacarias-010.adoc#v38-10-0[Próximo Capítulo &#62;]