include::./index.adoc[]

[[v27-9-0]]
=== Daniel, 9
// nvi ?, NVI - Nova Versão Internacional

[[v27-9-1]]

^<<v27-9-1,1>>^ Dario, filho de Xerxes, de origem meda, foi constituído governante do reino babilônio.

[[v27-9-2]]

^<<v27-9-2,2>>^ No primeiro ano do seu reinado, eu, Daniel, compreendi pelas Escrituras, conforme a palavra do Senhor dada ao profeta Jeremias, que a desolação de Jerusalém iria durar setenta anos.

[[v27-9-3]]

^<<v27-9-3,3>>^ Por isso me voltei para o Senhor Deus com orações e súplicas, em jejum, em pano de saco e coberto de cinza.

[[v27-9-4]]

^<<v27-9-4,4>>^ Orei ao Senhor, ao meu Deus, e confessei: "Ó Senhor, Deus grande e temível, que mantém a sua aliança de amor com todos aqueles que o amam e obedecem aos seus mandamentos,

[[v27-9-5]]

^<<v27-9-5,5>>^ nós temos pecado e somos culpados. Temos sido ímpios e rebeldes, e nos afastamos dos teus mandamentos e das tuas leis.

[[v27-9-6]]

^<<v27-9-6,6>>^ Não demos ouvido aos teus servos, os profetas, que falaram em teu nome aos nossos reis, aos nossos líderes e aos nossos antepassados, e a todo o povo desta terra.

[[v27-9-7]]

^<<v27-9-7,7>>^ "Senhor, tu és justo, e hoje estamos envergonhados. Sim, nós, o povo de Judá, de Jerusalém e de todo o Israel, tanto os que estão perto como os que estão distantes, em todas as terras pelas quais nos espalhaste por causa de nossa infidelidade para contigo.

[[v27-9-8]]

^<<v27-9-8,8>>^ Ó Senhor, nós e nossos reis, nossos líderes e nossos antepassados estamos envergonhados por termos pecado contra ti.

[[v27-9-9]]

^<<v27-9-9,9>>^ O Senhor nosso Deus é misericordioso e perdoador, apesar de termos sido rebeldes;

[[v27-9-10]]

^<<v27-9-10,10>>^ não te demos ouvidos, Senhor, nosso Deus, nem obedecemos às leis que nos deste por meio dos teus servos, os profetas.

[[v27-9-11]]

^<<v27-9-11,11>>^ Todo o Israel tem transgredido a tua lei e se desviou, recusando-se a te ouvir. "Por isso as maldições e as pragas escritas na Lei de Moisés, servo de Deus, têm sido derramadas sobre nós, porque temos pecado contra ti.

[[v27-9-12]]

^<<v27-9-12,12>>^ Tu tens cumprido as palavras faladas contra nós e contra os nossos governantes, trazendo-nos grande desgraça. Debaixo de todo o céu jamais se fez algo como o que foi feito a Jerusalém.

[[v27-9-13]]

^<<v27-9-13,13>>^ Assim como está escrito na Lei de Moisés, toda essa desgraça nos atingiu, e ainda assim não temos buscado o favor do Senhor, do nosso Deus, afastando-nos de nossas maldades e obedecendo à tua verdade.

[[v27-9-14]]

^<<v27-9-14,14>>^ O Senhor não hesitou em trazer desgraça sobre nós, pois o Senhor, o nosso Deus, é justo em tudo o que faz; ainda assim nós não o temos ouvido.

[[v27-9-15]]

^<<v27-9-15,15>>^ Ó Senhor, nosso Deus, que tiraste o teu povo do Egito com mão poderosa e que fizeste para ti um nome que permanece até hoje, nós temos pecado e somos culpados.

[[v27-9-16]]

^<<v27-9-16,16>>^ Agora Senhor, conforme todos os teus feitos justos, afasta de Jerusalém, da tua cidade, do teu santo monte, a tua ira e a tua indignação. Os nossos pecados e as iniqüidades de nossos antepassados fizeram de Jerusalém e do teu povo motivo de zombaria para todos os que nos rodeiam.

[[v27-9-17]]

^<<v27-9-17,17>>^ Ouve, nosso Deus, as orações e as súplicas do teu servo. Por amor de ti, Senhor, olha com bondade para o teu santuário abandonado.

[[v27-9-18]]

^<<v27-9-18,18>>^ Inclina os teus ouvidos, ó Deus, e ouve; abre os teus olhos e vê a desolação da cidade que leva o teu nome. Não te fazemos pedidos por sermos justos, mas por causa da tua grande misericórdia.

[[v27-9-19]]

^<<v27-9-19,19>>^ Senhor, ouve! Senhor, perdoa! Senhor, vê e age! Por amor de ti, meu Deus, não te demores, pois a tua cidade e o teu povo levam o teu nome".

[[v27-9-20]]

^<<v27-9-20,20>>^ Enquanto eu estava falando e orando, confessando o meu pecado e o pecado de Israel, meu povo, e fazendo o meu pedido ao Senhor, ao meu Deus, em favor do seu santo monte;

[[v27-9-21]]

^<<v27-9-21,21>>^ enquanto eu ainda estava em oração, Gabriel, o homem que eu tinha visto na visão anterior, veio a mim, voando rapidamente para onde eu estava, à hora do sacrifício da tarde.

[[v27-9-22]]

^<<v27-9-22,22>>^ Ele me instruiu e me disse: "Daniel, agora vim para dar-lhe percepção e entendimento.

[[v27-9-23]]

^<<v27-9-23,23>>^ Assim que você começou a orar, houve uma resposta, que eu lhe trouxe porque você é muito amado. Por isso, preste atenção à mensagem para entender a visão:

[[v27-9-24]]

^<<v27-9-24,24>>^ "Setenta semanas estão decretadas para o seu povo e sua santa cidade para acabar com a transgressão, para dar fim ao pecado, para expiar as culpas, para trazer justiça eterna, para cumprir a visão e a profecia, e para ungir o santíssimo.

[[v27-9-25]]

^<<v27-9-25,25>>^ "Saiba e entenda que a partir da promulgação do decreto que manda restaurar e reconstruir Jerusalém até que o Ungido, o líder, venha, haverá sete semanas, e sessenta e duas semanas. Ela será reconstruída com ruas e muros, mas em tempos difíceis.

[[v27-9-26]]

^<<v27-9-26,26>>^ Depois das sessenta e duas semanas, o Ungido será morto, e já não haverá lugar para ele. A cidade e o lugar santo serão destruídos pelo povo do governante que virá. O fim virá como uma inundação: Guerras continuarão até o fim, e desolações foram decretadas.

[[v27-9-27]]

^<<v27-9-27,27>>^ Com muitos ele fará uma aliança que durará uma semana. No meio da semana ele dará fim ao sacrifício e à oferta. E numa ala do templo será colocado o sacrilégio terrível, até que chegue sobre ele o fim que lhe está decretado".

'''

xref:027-daniel/027-daniel-008.adoc#v27-8-0[&#60; Capítulo Anterior] | <<v27-9-0,Topo>> | xref:027-daniel/027-daniel-010.adoc#v27-10-0[Próximo Capítulo &#62;]