include::./index.adoc[]

[[v27-12-0]]
=== Daniel, 12
// nvi ?, NVI - Nova Versão Internacional

[[v27-12-1]]

^<<v27-12-1,1>>^ "Naquela ocasião Miguel, o grande príncipe que protege o seu povo, se levantará. Haverá um tempo de angústia tal como nunca houve desde o início das nações e até então. Mas naquela ocasião o seu povo, todo aquele cujo nome está escrito no livro, será liberto.

[[v27-12-2]]

^<<v27-12-2,2>>^ Multidões que dormem no pó da terra acordarão: uns para a vida eterna, outros para a vergonha, para o desprezo eterno.

[[v27-12-3]]

^<<v27-12-3,3>>^ Aqueles que são sábios reluzirão como o brilho do céu, e aqueles que conduzem muitos à justiça serão como as estrelas, para todo o sempre.

[[v27-12-4]]

^<<v27-12-4,4>>^ Mas você, Daniel, feche com um selo as palavras do livro até o tempo do fim. Muitos irão ali e acolá para aumentarem o conhecimento".

[[v27-12-5]]

^<<v27-12-5,5>>^ Então eu, Daniel, olhei, e diante de mim estavam dois outros, um na margem de cá do rio e outro na margem de lá.

[[v27-12-6]]

^<<v27-12-6,6>>^ Um deles disse ao homem vestido de linho, que estava acima das águas do rio: "Quanto tempo decorrerá antes de se cumprirem essas coisas estupendas? "

[[v27-12-7]]

^<<v27-12-7,7>>^ O homem vestido de linho, que estava acima das águas do rio, ergueu para o céu a mão direita e a mão esquerda, e eu o ouvi jurar por aquele que vive para sempre, dizendo: "Haverá um tempo, tempos e meio tempo. Quando o poder do povo santo for finalmente quebrado, todas essas coisas se cumprirão".

[[v27-12-8]]

^<<v27-12-8,8>>^ Eu ouvi, mas não compreendi. Por isso perguntei: "Meu senhor, qual será o resultado disso tudo? "

[[v27-12-9]]

^<<v27-12-9,9>>^ Ele respondeu: "Siga o seu caminho, Daniel, pois as palavras estão seladas e lacradas até o tempo do fim.

[[v27-12-10]]

^<<v27-12-10,10>>^ Muitos serão purificados, alvejados e refinados, mas os ímpios continuarão ímpios. Nenhum dos ímpios levará isto em consideração, mas os sábios sim.

[[v27-12-11]]

^<<v27-12-11,11>>^ "A partir do momento em que for abolido o sacrifício diário e for colocado o sacrilégio terrível, haverá mil e duzentos e noventa dias.

[[v27-12-12]]

^<<v27-12-12,12>>^ Feliz aquele que esperar e alcançar o fim dos mil trezentos e trinta e cinco dias.

[[v27-12-13]]

^<<v27-12-13,13>>^ "Quanto a você, siga o seu caminho até o fim. Você descansará, e então, no final dos dias, você se levantará para receber a herança que lhe cabe".

'''

xref:027-daniel/027-daniel-011.adoc#v27-11-0[&#60; Capítulo Anterior] | <<v27-12-0,Topo>> | xref:028-oseias/028-oseias-001.adoc#v28-1-0[Próximo Capítulo &#62;]