include::./index.adoc[]

[[v27-7-0]]
=== Daniel, 7
// nvi ?, NVI - Nova Versão Internacional

[[v27-7-1]]

^<<v27-7-1,1>>^ No primeiro ano de Belsazar, rei da Babilônia, Daniel teve um sonho, e certas visões passaram por sua mente, estando ele deitado em sua cama. Ele escreveu o resumo do seu sonho.

[[v27-7-2]]

^<<v27-7-2,2>>^ Daniel disse: "Na minha visão à noite, eu vi os quatro ventos do céu agitando o grande mar.

[[v27-7-3]]

^<<v27-7-3,3>>^ Quatro grandes animais, cada um diferente dos outros, subiram do mar.

[[v27-7-4]]

^<<v27-7-4,4>>^ "O primeiro parecia um leão, e tinha as asas de águia. Eu o observei até que as suas asas foram arrancadas, e ele foi erguido do chão de modo que levantou-se sobre dois pés como um homem, e recebeu coração de homem.

[[v27-7-5]]

^<<v27-7-5,5>>^ "A seguir vi um segundo animal, que tinha a aparência de um urso. Ele foi erguido por um dos seus lados, e na boca, entre os dentes, tinha três costelas. E lhe foi dito: ‘Levante-se e coma quanta carne puder! ’

[[v27-7-6]]

^<<v27-7-6,6>>^ "Depois disso, vi um outro animal, que se parecia com um leopardo. E nas costas tinha quatro asas, como asas de uma ave. Esse animal tinha quatro cabeças, e recebeu autoridade para governar.

[[v27-7-7]]

^<<v27-7-7,7>>^ "Na minha visão à noite, vi ainda um quarto animal, aterrorizante, assustador e muito poderoso. Tinha grandes dentes de ferro, com as quais despedaçava e devorava suas vítimas, e pisoteava tudo o que sobrava. Era diferente de todos os animais anteriores, e tinha dez chifres.

[[v27-7-8]]

^<<v27-7-8,8>>^ "Enquanto eu estava refletindo nos chifres, vi um outro chifre, pequeno, que surgiu entre eles; e três dos primeiros chifres foram arrancados para dar lugar a ele. Esse chifre possuía olhos como os olhos de um homem e uma boca que falava com arrogância.

[[v27-7-9]]

^<<v27-7-9,9>>^ "Enquanto eu olhava, "tronos foram postos no lugar, e um ancião se assentou. Sua veste era branca como a neve; o cabelo era branco como a lã. Seu trono ardia em fogo, e as rodas do trono estavam todas incandescentes.

[[v27-7-10]]

^<<v27-7-10,10>>^ E saía um rio de fogo, de diante dele. Milhares de milhares o serviam; milhões e milhões estavam diante dele. O tribunal iniciou o julgamento, e os livros foram abertos.

[[v27-7-11]]

^<<v27-7-11,11>>^ "Continuei a observar por causa das palavras arrogantes que o chifre falava. Fiquei olhando até que o animal foi morto, e o seu corpo foi destruído e atirado no fogo.

[[v27-7-12]]

^<<v27-7-12,12>>^ E foi tirada a autoridade dos outros animais, mas eles tiveram permissão para viver por um período de tempo.

[[v27-7-13]]

^<<v27-7-13,13>>^ "Na minha visão à noite, vi alguém semelhante a um filho de um homem, vindo com as nuvens dos céus. Ele se aproximou do ancião e foi conduzido à sua presença.

[[v27-7-14]]

^<<v27-7-14,14>>^ A ele foram dados autoridade, glória e reino; todos os povos, nações e homens de todas as línguas o adoraram. Seu domínio é um domínio eterno que não acabará, e seu reino jamais será destruído.

[[v27-7-15]]

^<<v27-7-15,15>>^ "Eu, Daniel, fiquei agitado em meu espírito, e as visões que passaram pela minha mente me aterrorizaram.

[[v27-7-16]]

^<<v27-7-16,16>>^ Então me aproximei de um dos que ali estavam e lhe perguntei o significado disso tudo. "E ele me respondeu, dando-me a interpretação:

[[v27-7-17]]

^<<v27-7-17,17>>^ ‘Os quatro grandes animais são quatro reinos que se levantarão na terra.

[[v27-7-18]]

^<<v27-7-18,18>>^ Mas os santos do Altíssimo receberão o reino e o possuirão para sempre; sim, para todo o sempre’.

[[v27-7-19]]

^<<v27-7-19,19>>^ "Então eu quis saber o significado do quarto animal, diferente de todos os outros e o mais aterrorizante, com seus dentes de ferro e garras de bronze, o animal que despedaçava e devorava suas vítimas, e pisoteava tudo o que sobrava.

[[v27-7-20]]

^<<v27-7-20,20>>^ E também quis saber sobre os dez chifres da sua cabeça e sobre o outro chifre que surgiu para ocupar o lugar dos três chifres que caíram, o chifre que era maior do que os demais e que tinha olhos e uma boca que falava com arrogância.

[[v27-7-21]]

^<<v27-7-21,21>>^ Enquanto eu observava, esse chifre guerreava contra os santos e os derrotava,

[[v27-7-22]]

^<<v27-7-22,22>>^ até que o ancião veio e pronunciou a sentença a favor dos santos do Altíssimo, e chegou a hora de eles tomarem posse do reino.

[[v27-7-23]]

^<<v27-7-23,23>>^ "Ele me deu a seguinte explicação: ‘O quarto animal é um quarto reino que aparecerá na terra. Será diferente de todos os outros reinos e devorará a terra inteira, despedaçando-a e pisoteando-a.

[[v27-7-24]]

^<<v27-7-24,24>>^ Os dez chifres são dez reis que sairão desse reino. Depois deles um outro rei se levantará, e será diferente dos primeiros reis.

[[v27-7-25]]

^<<v27-7-25,25>>^ Ele falará contra o Altíssimo, oprimirá os seus santos e tentará mudar os tempos e as leis. Os santos serão entregues nas mãos dele por um tempo, tempos e meio tempo’.

[[v27-7-26]]

^<<v27-7-26,26>>^ "Mas o tribunal o julgará, e o seu poder será tirado e totalmente destruído para sempre.

[[v27-7-27]]

^<<v27-7-27,27>>^ Então a soberania, o poder e a grandeza dos reinos debaixo de todo o céu serão entregues nas mãos dos santos, o povo do Altíssimo. O reino dele será um reino eterno, e todos os governantes o adorarão e lhe obedecerão.

[[v27-7-28]]

^<<v27-7-28,28>>^ "Esse é o fim da visão. Eu, Daniel, fiquei aterrorizado por causa de meus pensamentos, e meu rosto empalideceu, mas guardei essas coisas comigo".

'''

xref:027-daniel/027-daniel-006.adoc#v27-6-0[&#60; Capítulo Anterior] | <<v27-7-0,Topo>> | xref:027-daniel/027-daniel-008.adoc#v27-8-0[Próximo Capítulo &#62;]