include::./index.adoc[]

[[v27-11-0]]
=== Daniel, 11
// nvi ?, NVI - Nova Versão Internacional

[[v27-11-1]]

^<<v27-11-1,1>>^ sendo que, no primeiro ano de Dario, rei dos medos, ajudei-o e dei-lhe apoio.

[[v27-11-2]]

^<<v27-11-2,2>>^ "Agora, pois, vou dar-lhe a conhecer a verdade: Outros três reis aparecerão na Pérsia, e depois virá um quarto rei, que será bem mais rico do que todos os outros. Quando ele tiver conquistado o poder com sua riqueza, instigará todos contra o reino da Grécia.

[[v27-11-3]]

^<<v27-11-3,3>>^ Então surgirá um rei guerreiro, que governará com grande poder e fará o que quiser.

[[v27-11-4]]

^<<v27-11-4,4>>^ Depois que ele surgir, o seu império se desfará e será repartido para os quatro ventos do céu. Não passará para os seus descendentes, e o império não será poderoso como antes, pois será desarraigado e dado a outros.

[[v27-11-5]]

^<<v27-11-5,5>>^ "O rei do sul se tornará forte, mas um dos seus príncipes se tornará ainda mais forte que ele e governará o seu próprio reino com grande poder.

[[v27-11-6]]

^<<v27-11-6,6>>^ Depois de alguns anos, eles se tornarão aliados. A filha do rei do sul fará um tratado com o rei do norte, mas ela não manterá o seu poder, nem ele conservará o dele. Naqueles dias ela será entregue à morte, junto com sua escolta real e com seu pai e com aquele que a apoiou.

[[v27-11-7]]

^<<v27-11-7,7>>^ "Alguém da linhagem dela se levantará para tomar-lhe o lugar. Ele atacará as forças do rei do norte e invadirá a sua fortaleza; lutará contra eles e será vitorioso.

[[v27-11-8]]

^<<v27-11-8,8>>^ Também se apoderará dos deuses deles, das suas imagens de metal e dos seus utensílios valiosos de prata e de ouro, e os levará para o Egito. E por alguns anos ele deixará o rei do norte em paz.

[[v27-11-9]]

^<<v27-11-9,9>>^ Então o rei do norte invadirá as terras do rei do sul, mas terá que se retirar para a sua própria terra.

[[v27-11-10]]

^<<v27-11-10,10>>^ Seus filhos se prepararão para a guerra e reunirão um grande exército, que avançará como uma inundação irresistível e levará os combates até a fortaleza do rei do sul.

[[v27-11-11]]

^<<v27-11-11,11>>^ "Em face disso, o rei do sul marchará furioso para combater o rei do norte, que o enfrentará com um enorme exército, mas mesmo assim será derrotado.

[[v27-11-12]]

^<<v27-11-12,12>>^ Quando o exército for vencido, o rei do sul se encherá de orgulho e matará milhares, mas o seu triunfo será breve.

[[v27-11-13]]

^<<v27-11-13,13>>^ Pois o rei do norte reunirá um outro exército, maior do que o primeiro; e depois de alguns anos voltará a atacá-lo com um exército enorme e bem equipado.

[[v27-11-14]]

^<<v27-11-14,14>>^ "Naquela época muitos se rebelarão contra o rei do sul. E os homens violentos do povo a que você pertence se revoltarão para cumprirem esta visão, mas não terão sucesso.

[[v27-11-15]]

^<<v27-11-15,15>>^ Então o rei do norte virá e construirá rampas de cerco e conquistará uma cidade fortificada. As forças do sul serão incapazes de resistir; mesmo as suas melhores tropas não terão forças para resistir.

[[v27-11-16]]

^<<v27-11-16,16>>^ O invasor fará o que bem entender; ninguém conseguirá resistir-lhe. Ele se instalará na Terra Magnífica e terá poder para destruí-la.

[[v27-11-17]]

^<<v27-11-17,17>>^ Virá com o poder de todo o seu reino e fará uma aliança com o rei do sul. Ele lhe dará uma filha em casamento a fim de derrubar o reino, mas o seu plano não terá sucesso nem o ajudará.

[[v27-11-18]]

^<<v27-11-18,18>>^ Então ele voltará a atenção para as regiões costeiras e tomará muitas delas, mas um comandante dará fim à arrogância dele e lhe devolverá a sua arrogância.

[[v27-11-19]]

^<<v27-11-19,19>>^ Depois disso ele se dirigirá para as fortalezas de sua própria terra, mas tropeçará e cairá, para nunca mais aparecer.

[[v27-11-20]]

^<<v27-11-20,20>>^ "Seu sucessor enviará um cobrador de impostos para manter o esplendor real. Contudo, em poucos anos ele será destruído, ainda que não com ira nem em combate.

[[v27-11-21]]

^<<v27-11-21,21>>^ "Ele será sucedido por um ser desprezível, a quem não tinha sido dada a honra da realeza. Este invadirá o reino quando o povo do reino sentir-se seguro, e ele se apoderará dele mediante intrigas.

[[v27-11-22]]

^<<v27-11-22,22>>^ Então um exército avassalador será arrasado diante dele; tanto o exército como um príncipe da aliança serão destruídos.

[[v27-11-23]]

^<<v27-11-23,23>>^ Depois de um acordo feito com ele, agirá traiçoeiramente, e com apenas uns poucos chegará ao poder.

[[v27-11-24]]

^<<v27-11-24,24>>^ Quando as províncias mais ricas se sentirem seguras, ele as invadirá e realizará o que nem seus pais nem seus antepassados conseguiram. Distribuirá despojos, saques e riquezas entre seus seguidores. Ele tramará a tomada de fortalezas, mas só por algum tempo.

[[v27-11-25]]

^<<v27-11-25,25>>^ "Com um grande exército juntará suas forças e sua coragem contra o rei do sul. O rei do sul guerreará com um exército grande e poderoso, mas não conseguirá resistir por causa dos golpes tramados contra ele.

[[v27-11-26]]

^<<v27-11-26,26>>^ Mesmo os que estiverem sendo alimentados pelo rei tentarão destruí-lo; seu exército será arrasado, e muitos cairão em combate.

[[v27-11-27]]

^<<v27-11-27,27>>^ Os dois reis, com seus corações inclinados para o mal, sentarão à mesma mesa e mentirão um para o outro, mas sem resultado, pois o fim só virá no tempo determinado.

[[v27-11-28]]

^<<v27-11-28,28>>^ O rei do norte voltará para a sua terra com grande riqueza, mas o seu coração estará voltado contra a santa aliança. Ele empreenderá ação contra ela e então voltará para a sua terra.

[[v27-11-29]]

^<<v27-11-29,29>>^ "No tempo determinado ele invadirá de novo o sul, mas dessa vez o resultado será diferente do anterior.

[[v27-11-30]]

^<<v27-11-30,30>>^ Navios das regiões da costa ocidental se oporão a ele, e ele perderá o ânimo. Então se voltará e despejará sua fúria contra a santa aliança. Ele retornará e será bondoso com aqueles que abandonarem a santa aliança.

[[v27-11-31]]

^<<v27-11-31,31>>^ "Suas forças armadas se levantarão para profanar a fortaleza e o templo, acabarão com o sacrifício diário e colocarão o sacrilégio terrível.

[[v27-11-32]]

^<<v27-11-32,32>>^ Com lisonjas corromperá aqueles que tiverem violado a aliança, mas o povo que conhece o seu Deus resistirá com firmeza.

[[v27-11-33]]

^<<v27-11-33,33>>^ "Aqueles que são sábios instruirão a muitos, mas por certo período cairão pela espada e serão queimados, capturados e saqueados.

[[v27-11-34]]

^<<v27-11-34,34>>^ Quando caírem, receberão uma pequena ajuda, e muitos que não são sinceros se juntarão a eles.

[[v27-11-35]]

^<<v27-11-35,35>>^ Alguns dos sábios tropeçarão para que sejam refinados, purificados e alvejados até a época do fim, pois isso só virá no tempo determinado.

[[v27-11-36]]

^<<v27-11-36,36>>^ "O rei fará o que bem entender. Ele se exaltará e se engrandecerá acima de todos os deuses e dirá coisas jamais ouvidas contra o Deus dos deuses. Ele terá sucesso até que o tempo da ira se complete, pois o que foi decidido irá acontecer.

[[v27-11-37]]

^<<v27-11-37,37>>^ Ele não terá consideração pelos deuses dos seus antepassados nem pelo deus preferido das mulheres, nem por deus algum, mas se exaltará acima deles todos.

[[v27-11-38]]

^<<v27-11-38,38>>^ Em seu lugar adorará um deus das fortalezas; um deus desconhecido de seus antepassados ele honrará com ouro e prata, com pedras preciosas e presentes caros.

[[v27-11-39]]

^<<v27-11-39,39>>^ Atacará as fortalezas mais poderosas com a ajuda de um deus estrangeiro e dará grande honra àqueles que o reconhecerem. Ele os fará governantes sobre muitos e distribuirá a terra, mas a um preço elevado.

[[v27-11-40]]

^<<v27-11-40,40>>^ "No tempo do fim o rei do sul se envolverá em combate, e o rei do norte o atacará com carros e cavaleiros e uma grande frota de navios. Ele invadirá muitos países e avançará por eles como uma inundação.

[[v27-11-41]]

^<<v27-11-41,41>>^ Também invadirá a Terra Magnífica. Muitos países cairão, mas Edom, Moabe e os líderes de Amom ficarão livres da sua mão.

[[v27-11-42]]

^<<v27-11-42,42>>^ Ele estenderá o seu poder sobre muitos países; o Egito não escapará,

[[v27-11-43]]

^<<v27-11-43,43>>^ pois ele terá o controle dos tesouros de ouro e de prata e de todas as riquezas do Egito; os líbios e os núbios a ele se submeterão.

[[v27-11-44]]

^<<v27-11-44,44>>^ Mas, informações provenientes do leste e do norte o deixarão alarmado, e irado partirá para destruir e aniquilar a muitos.

[[v27-11-45]]

^<<v27-11-45,45>>^ Armará suas tendas reais entre os mares, no belo monte santo. No entanto, ele chegará ao seu fim, e ninguém o socorrerá.

'''

xref:027-daniel/027-daniel-010.adoc#v27-10-0[&#60; Capítulo Anterior] | <<v27-11-0,Topo>> | xref:027-daniel/027-daniel-012.adoc#v27-12-0[Próximo Capítulo &#62;]