include::./index.adoc[]

[[v27-8-0]]
=== Daniel, 8
// nvi ?, NVI - Nova Versão Internacional

[[v27-8-1]]

^<<v27-8-1,1>>^ No terceiro ano do reinado do rei Belsazar, eu, Daniel, tive outra visão, depois da primeira.

[[v27-8-2]]

^<<v27-8-2,2>>^ Na minha visão eu me vi na cidadela de Susã, na província de Elão; na visão eu estava junto do canal de Ulai.

[[v27-8-3]]

^<<v27-8-3,3>>^ Olhei para cima, e diante de mim, junto ao canal, estava um carneiro, seus dois chifres eram compridos, um mais que o outro, mas o mais comprido cresceu depois do outro.

[[v27-8-4]]

^<<v27-8-4,4>>^ Observei o carneiro enquanto ele avançava para o oeste, para o norte e para o sul. Nenhum animal conseguia resistir-lhe, e ninguém podia livrar-se do seu poder. Ele fazia o que bem queria e foi ficando cada vez maior.

[[v27-8-5]]

^<<v27-8-5,5>>^ Enquanto eu estava considerando isso, de repente um bode, com um chifre enorme entre os olhos, veio do oeste, percorrendo toda a extensão da terra sem encostar no chão.

[[v27-8-6]]

^<<v27-8-6,6>>^ Ele veio na direção do carneiro de dois chifres que eu tinha visto ao lado do canal, e avançou contra ele com grande fúria.

[[v27-8-7]]

^<<v27-8-7,7>>^ Eu o vi atacar furiosamente o carneiro, atingi-lo e quebrar os seus dois chifres. O carneiro não teve forças para resistir-lhe; o bode o derrubou no chão e o pisoteou, e ninguém foi capaz de livrar o carneiro do seu poder.

[[v27-8-8]]

^<<v27-8-8,8>>^ O bode tornou-se muito grande, mas no auge da sua força o seu grande chifre foi quebrado, e em seu lugar cresceram quatro chifres enormes, na direção dos quatro ventos da terra.

[[v27-8-9]]

^<<v27-8-9,9>>^ De um deles saiu um outro chifre, que começou pequeno, mas cresceu em poder na direção do sul, do leste e da Terra Magnífica.

[[v27-8-10]]

^<<v27-8-10,10>>^ Cresceu até alcançar o exército dos céus, e atirou na terra alguns componentes do exército das estrelas e os pisoteou.

[[v27-8-11]]

^<<v27-8-11,11>>^ Tanto cresceu que chegou a desafiar o príncipe do exército; suprimiu o sacrifício diário oferecido ao príncipe, e o local do santuário foi destruído.

[[v27-8-12]]

^<<v27-8-12,12>>^ Por causa da rebelião, o exército dos santos e o sacrifício diário foram dados ao chifre. Ele tinha êxito em tudo o que fazia, e a verdade foi lançada por terra.

[[v27-8-13]]

^<<v27-8-13,13>>^ Então ouvi dois anjos conversando, e um deles perguntou ao outro: "Quanto tempo durarão os acontecimentos anunciados por essa visão? Até quando será suprimido o sacrifício diário e a rebelião devastadora prevalecerá? Até quando o santuário e o exército ficarão entregues ao poder do chifre e serão pisoteados? "

[[v27-8-14]]

^<<v27-8-14,14>>^ Ele me disse: "Isso tudo levará duas mil e trezentas tardes e manhãs; então o santuário será reconsagrado".

[[v27-8-15]]

^<<v27-8-15,15>>^ Enquanto eu, Daniel, observava a visão e tentava entendê-la, diante de mim apareceu um ser que parecia homem.

[[v27-8-16]]

^<<v27-8-16,16>>^ E ouvi a voz de um homem que vinha do Ulai: "Gabriel, dê a esse homem o significado da visão".

[[v27-8-17]]

^<<v27-8-17,17>>^ Quando ele se aproximou de mim, fiquei aterrorizado e caí prostrado. E ele me disse: "Filho do homem, saiba que a visão refere-se aos tempos do fim".

[[v27-8-18]]

^<<v27-8-18,18>>^ Enquanto ele falava comigo, caí prostrado, rosto em terra, e perdi os sentidos. Então ele tocou em mim e me pôs de pé.

[[v27-8-19]]

^<<v27-8-19,19>>^ E disse: "Vou contar-lhe o que acontecerá depois, no tempo da ira, pois a visão se refere ao tempo do fim.

[[v27-8-20]]

^<<v27-8-20,20>>^ O carneiro de dois chifres que você viu representa os reis da Média e da Pérsia.

[[v27-8-21]]

^<<v27-8-21,21>>^ O bode peludo é o rei da Grécia, e o grande chifre entre os seus olhos é o primeiro rei.

[[v27-8-22]]

^<<v27-8-22,22>>^ Os quatro chifres que tomaram o lugar do chifre que foi quebrado são quatro reinos que surgirão da nação daquele rei, mas não terão o mesmo poder.

[[v27-8-23]]

^<<v27-8-23,23>>^ "No final do reinado deles, quando a rebelião dos ímpios tiver chegado ao máximo, surgirá um rei de duro semblante, mestre em astúcias.

[[v27-8-24]]

^<<v27-8-24,24>>^ Ele se tornará muito forte, mas não pelo seu próprio poder. Provocará devastações terríveis e será bem sucedido em tudo o que fizer. Destruirá os homens poderosos e o povo santo.

[[v27-8-25]]

^<<v27-8-25,25>>^ Com o intuito de prosperar, ele enganará a muitos, e se considerará superior aos outros. Destruirá muitos que nele confiam e se insurgirá contra o Príncipe dos príncipes. Apesar disso, ele será destruído, mas não pelo poder dos homens.

[[v27-8-26]]

^<<v27-8-26,26>>^ "A visão das tardes e das manhãs que você recebeu é verdadeira; sela porém a visão, pois refere-se ao futuro distante".

[[v27-8-27]]

^<<v27-8-27,27>>^ Eu, Daniel, fiquei exausto e doente por vários dias. Depois levantei-me e voltei a cuidar dos negócios do rei. Fiquei assustado com a visão; estava além da compreensão.

'''

xref:027-daniel/027-daniel-007.adoc#v27-7-0[&#60; Capítulo Anterior] | <<v27-8-0,Topo>> | xref:027-daniel/027-daniel-009.adoc#v27-9-0[Próximo Capítulo &#62;]