include::./index.adoc[]

[[v27-10-0]]
=== Daniel, 10
// nvi ?, NVI - Nova Versão Internacional

[[v27-10-1]]

^<<v27-10-1,1>>^ No terceiro ano de Ciro, rei da Pérsia, Daniel, chamado Beltessazar, recebeu uma revelação. A mensagem era verdadeira e falava de uma grande guerra. E numa visão veio-lhe o entendimento da mensagem.

[[v27-10-2]]

^<<v27-10-2,2>>^ Naquela ocasião eu, Daniel, passei três semanas chorando.

[[v27-10-3]]

^<<v27-10-3,3>>^ Não comi nada saboroso; carne e vinho nem provei; e não usei nenhuma fragrância perfumada, até se passarem as três semanas.

[[v27-10-4]]

^<<v27-10-4,4>>^ No vigésimo quarto dia do primeiro mês, estava eu de pé junto à margem do grande rio, o Tigre.

[[v27-10-5]]

^<<v27-10-5,5>>^ Olhei para cima, e diante de mim estava um homem vestido de linho, com um cinto de ouro puríssimo na cintura.

[[v27-10-6]]

^<<v27-10-6,6>>^ Seu corpo era como o berilo, o rosto como o relâmpago, os olhos como tochas acesas, os braços e pernas como o reflexo do bronze polido, e a sua voz era como o som de uma multidão.

[[v27-10-7]]

^<<v27-10-7,7>>^ Somente eu, Daniel, vi a visão; os que me acompanhavam nada viram, mas apoderou-se deles tanto pavor que eles fugiram e se esconderam.

[[v27-10-8]]

^<<v27-10-8,8>>^ Assim fiquei sozinho, olhando para aquela grande visão; fiquei sem forças, muito pálido, e quase desfaleci.

[[v27-10-9]]

^<<v27-10-9,9>>^ Então eu o ouvi falando, e, ao ouvi-lo, caí prostrado, rosto em terra, e perdi os sentidos.

[[v27-10-10]]

^<<v27-10-10,10>>^ Em seguida, a mão de alguém tocou em mim e me pôs sobre as minhas mãos e os meus joelhos vacilantes.

[[v27-10-11]]

^<<v27-10-11,11>>^ E ele disse: "Daniel, você é muito amado. Preste bem atenção ao que vou lhe falar; levante-se, pois eu fui enviado a você". Quando ele me disse isso, pus-me de pé, tremendo.

[[v27-10-12]]

^<<v27-10-12,12>>^ E ele prosseguiu: "Não tenha medo, Daniel. Desde o primeiro dia em que você decidiu buscar entendimento e humilhar-se diante do seu Deus, suas palavras foram ouvidas, e eu vim em resposta a elas.

[[v27-10-13]]

^<<v27-10-13,13>>^ Mas o príncipe do reino da Pérsia me resistiu vinte e um dias. Então Miguel, um dos príncipes supremos, veio em minha ajuda, pois eu fui impedido de prosseguir ali com os reis da Pérsia.

[[v27-10-14]]

^<<v27-10-14,14>>^ Agora vim explicar-lhe o que acontecerá ao seu povo no futuro, pois a visão se refere a uma época futura".

[[v27-10-15]]

^<<v27-10-15,15>>^ Enquanto ele me dizia isso, prostrei-me, rosto em terra, sem conseguir falar.

[[v27-10-16]]

^<<v27-10-16,16>>^ Então um ser que parecia homem tocou nos meus lábios, e eu abri a minha boca e comecei a falar. Eu disse àquele que estava de pé diante de mim: Estou angustiado por causa da visão, meu senhor, e quase desfaleço.

[[v27-10-17]]

^<<v27-10-17,17>>^ Como posso eu, teu servo, conversar contigo, meu senhor? Minhas forças se foram, e mal posso respirar.

[[v27-10-18]]

^<<v27-10-18,18>>^ O ser que parecia homem tocou em mim outra vez e me deu forças.

[[v27-10-19]]

^<<v27-10-19,19>>^ Ele disse: "Não tenha medo, você, que é muito amado. Que a paz seja com você! Seja forte! Seja forte! " Ditas essas palavras, senti-me fortalecido e disse: "Fala, meu senhor, visto que me deste forças".

[[v27-10-20]]

^<<v27-10-20,20>>^ Então ele me disse: "Você sabe por que vim? Vou ter que voltar para lutar contra o príncipe da Pérsia, e, logo que eu for, chegará o príncipe da Grécia;

[[v27-10-21]]

^<<v27-10-21,21>>^ mas antes lhe revelarei o que está escrito no Livro da Verdade. E nessa luta ninguém me ajuda contra eles, senão Miguel, o príncipe de vocês,

'''

xref:027-daniel/027-daniel-009.adoc#v27-9-0[&#60; Capítulo Anterior] | <<v27-10-0,Topo>> | xref:027-daniel/027-daniel-011.adoc#v27-11-0[Próximo Capítulo &#62;]