include::./index.adoc[]

[[v27-6-0]]
=== Daniel, 6
// nvi ?, NVI - Nova Versão Internacional

[[v27-6-1]]

^<<v27-6-1,1>>^ Dario achou por bem nomear cento e vinte sátrapas para governarem todo o reino;

[[v27-6-2]]

^<<v27-6-2,2>>^ e colocou três supervisores sobre eles, um dos quais era Daniel. Os sátrapas tinham que prestar contas a eles para que o rei não sofresse nenhuma perda.

[[v27-6-3]]

^<<v27-6-3,3>>^ Ora, Daniel se destacou tanto entre os supervisores e os sátrapas por suas grandes qualidades, que o rei planejava colocá-lo à frente do governo de todo o império.

[[v27-6-4]]

^<<v27-6-4,4>>^ Diante disso, os supervisores e os sátrapas procuraram motivos para acusar Daniel em sua administração governamental, mas nada conseguiram. Não puderam achar falta alguma nele, pois ele era fiel; não era desonesto nem negligente.

[[v27-6-5]]

^<<v27-6-5,5>>^ Finalmente esses homens disseram: "Jamais encontraremos algum motivo para acusar esse Daniel, a menos que seja algo relacionado com a lei do Deus dele".

[[v27-6-6]]

^<<v27-6-6,6>>^ E assim os supervisores e os sátrapas de comum acordo foram falar com o rei: "Ó rei Dario, vive para sempre!

[[v27-6-7]]

^<<v27-6-7,7>>^ Todos os supervisores reais, os prefeitos, os sátrapas, os conselheiros e os governadores concordaram em que o rei deve emitir um decreto ordenando que todo aquele que orar a qualquer deus ou a qualquer homem nos próximos trinta dias, exceto a ti, ó rei, seja atirado na cova dos leões.

[[v27-6-8]]

^<<v27-6-8,8>>^ Agora, ó rei, emite o decreto e assina-o para que não seja alterado, conforme a lei dos medos e dos persas, que não pode ser revogada".

[[v27-6-9]]

^<<v27-6-9,9>>^ E o rei Dario assinou o decreto.

[[v27-6-10]]

^<<v27-6-10,10>>^ Quando Daniel soube que o decreto tinha sido publicado, foi para casa, para o seu quarto, no andar de cima, onde as janelas davam para Jerusalém. Três vezes por dia ele se ajoelhava e orava, agradecendo ao seu Deus, como costumava fazer.

[[v27-6-11]]

^<<v27-6-11,11>>^ Então aqueles homens foram ver e encontraram Daniel orando, pedindo ajuda a Deus.

[[v27-6-12]]

^<<v27-6-12,12>>^ Assim foram falar com o rei acerca do decreto real: "Tu não publicaste um decreto ordenando que nos próximos trinta dias todo aquele que fizesse algum pedido a qualquer deus ou a qualquer homem, exceto a ti, ó rei, seria lançado na cova dos leões? " O rei respondeu: "O decreto está em vigor, conforme a lei dos medos e dos persas, que não pode ser revogada".

[[v27-6-13]]

^<<v27-6-13,13>>^ Então disseram ao rei: "Daniel, um dos exilados de Judá, não te dá ouvidos, ó rei, nem ao decreto que assinaste. Ele continua orando três vezes por dia".

[[v27-6-14]]

^<<v27-6-14,14>>^ Quando o rei ouviu isso, ficou muito contrariado, e como estava decidido a salvar Daniel, até o pôr-do-sol fez todo o esforço que pôde para livrá-lo.

[[v27-6-15]]

^<<v27-6-15,15>>^ Mas os homens lhe disseram: "Lembra-te, ó rei, que, conforme a lei dos medos e dos persas, nenhum decreto ou edito do rei pode ser modificado".

[[v27-6-16]]

^<<v27-6-16,16>>^ Então o rei deu ordens, e eles trouxeram Daniel e o jogaram na cova dos leões. O rei, porém, disse a Daniel: "Que o seu Deus, a quem você serve continuamente, o livre! "

[[v27-6-17]]

^<<v27-6-17,17>>^ Taparam a cova com uma pedra, e o rei a selou com o seu próprio anel-selo e com os anéis dos seus nobres, para que a situação de Daniel não se modificasse.

[[v27-6-18]]

^<<v27-6-18,18>>^ Tendo voltado ao palácio, o rei passou a noite sem comer e não aceitou nenhum divertimento em sua presença. Além disso, não conseguiu dormir.

[[v27-6-19]]

^<<v27-6-19,19>>^ Logo ao alvorecer, o rei se levantou e correu para a cova dos leões.

[[v27-6-20]]

^<<v27-6-20,20>>^ Quando ia se aproximando da cova, chamou Daniel com voz aflita: "Daniel, servo do Deus vivo, será que o seu Deus, a quem você serve continuamente, pôde livrá-lo dos leões? "

[[v27-6-21]]

^<<v27-6-21,21>>^ Daniel respondeu: "Ó rei, vive para sempre!

[[v27-6-22]]

^<<v27-6-22,22>>^ O meu Deus enviou o seu anjo, que fechou a boca dos leões. Eles não me fizeram mal algum, pois fui considerado inocente à vista de Deus. Também contra ti não cometi mal algum, ó rei".

[[v27-6-23]]

^<<v27-6-23,23>>^ O rei muito se alegrou e ordenou que tirassem Daniel da cova. Quando o tiraram da cova, viram que não havia nele nenhum ferimento, pois ele tinha confiado no seu Deus.

[[v27-6-24]]

^<<v27-6-24,24>>^ E por ordem do rei, os homens que tinham acusado Daniel foram atirados na cova dos leões, juntamente com as suas mulheres e os seus filhos. E, antes de chegarem ao fundo, os leões os atacaram e despedaçaram todos os seus ossos.

[[v27-6-25]]

^<<v27-6-25,25>>^ Então o rei Dario escreveu aos homens de todas as nações, povos e línguas de toda a terra: "Paz e prosperidade!

[[v27-6-26]]

^<<v27-6-26,26>>^ "Estou editando um decreto para que nos domínios do império os homens temam e reverenciem o Deus de Daniel. "Pois ele é o Deus vivo e permanece para sempre; o seu reino não será destruído, o seu domínio jamais acabará.

[[v27-6-27]]

^<<v27-6-27,27>>^ Ele livra e salva; faz sinais e maravilhas nos céus e na terra. Ele livrou Daniel do poder dos leões".

[[v27-6-28]]

^<<v27-6-28,28>>^ Assim Daniel prosperou durante os reinados de Dario e de Ciro, o persa.

'''

xref:027-daniel/027-daniel-005.adoc#v27-5-0[&#60; Capítulo Anterior] | <<v27-6-0,Topo>> | xref:027-daniel/027-daniel-007.adoc#v27-7-0[Próximo Capítulo &#62;]