include::./index.adoc[]

[[v27-1-0]]
=== Daniel, 1
// nvi ?, NVI - Nova Versão Internacional

[[v27-1-1]]

^<<v27-1-1,1>>^ No terceiro ano do reinado de Jeoaquim, rei de Judá, Nabucodonosor, rei da Babilônia, veio a Jerusalém e a sitiou.

[[v27-1-2]]

^<<v27-1-2,2>>^ E o Senhor entregou Jeoaquim, rei de Judá, nas suas mãos, e também alguns dos utensílios do templo de Deus. Ele levou os utensílios para o templo do seu deus na terra de Sinear e os colocou na casa do tesouro do seu deus.

[[v27-1-3]]

^<<v27-1-3,3>>^ Então o rei ordenou que Aspenaz, o chefe dos oficiais da sua corte, trouxesse alguns dos israelitas da família real e da nobreza;

[[v27-1-4]]

^<<v27-1-4,4>>^ jovens sem defeito físico, de boa aparência, cultos, inteligentes, que dominassem os vários campos do conhecimento e fossem capacitados para servir no palácio do rei. Ele devia ensinar-lhes a língua e a literatura dos babilônios.

[[v27-1-5]]

^<<v27-1-5,5>>^ O rei designou-lhes uma porção diária de comida e de vinho da própria mesa do rei. Eles receberiam um treinamento durante três anos, e depois disso passariam a servir o rei.

[[v27-1-6]]

^<<v27-1-6,6>>^ Entre esses estavam alguns que vieram de Judá: Daniel, Hananias, Misael e Azarias.

[[v27-1-7]]

^<<v27-1-7,7>>^ O chefe dos oficiais deu-lhes novos nomes: a Daniel deu o nome de Beltessazar; a Hananias, Sadraque; a Misael, Mesaque; e a Azarias, Abede-Nego.

[[v27-1-8]]

^<<v27-1-8,8>>^ Daniel, contudo, decidiu não se tornar impuro com a comida e com o vinho do rei, e pediu ao chefe dos oficiais permissão para se abster deles.

[[v27-1-9]]

^<<v27-1-9,9>>^ E Deus fez com que o homem fosse bondoso para com Daniel e tivesse simpatia por ele.

[[v27-1-10]]

^<<v27-1-10,10>>^ Apesar disso, ele disse a Daniel: "Tenho medo do rei, o meu senhor, que determinou a comida e a bebida de vocês. E se ele os achar menos saudáveis que os outros jovens da mesma idade? O rei poderia pedir a minha cabeça por causa de vocês".

[[v27-1-11]]

^<<v27-1-11,11>>^ Daniel disse então ao homem que o chefe dos oficiais tinha encarregado de cuidar de Daniel, Hananias, Misael e Azarias:

[[v27-1-12]]

^<<v27-1-12,12>>^ "Peço-lhe que faça uma experiência com os seus servos durante dez dias: Não nos dê nada além de vegetais para comer e água para beber.

[[v27-1-13]]

^<<v27-1-13,13>>^ Depois compare a nossa aparência com a dos jovens que comem a comida do rei, e trate os seus servos de acordo com o que você concluir".

[[v27-1-14]]

^<<v27-1-14,14>>^ Ele concordou e fez a experiência com eles durante dez dias.

[[v27-1-15]]

^<<v27-1-15,15>>^ Passados os dez dias eles pareciam mais saudáveis e mais fortes do que todos os jovens que comiam a comida da mesa do rei.

[[v27-1-16]]

^<<v27-1-16,16>>^ Assim o encarregado tirou a comida especial e o vinho que haviam sido designados e em lugar disso lhes dava vegetais.

[[v27-1-17]]

^<<v27-1-17,17>>^ A esses quatro jovens Deus deu sabedoria e inteligência para conhecerem todos os aspectos da cultura e da ciência. E Daniel, além disso, sabia interpretar todo tipo de visões e sonhos.

[[v27-1-18]]

^<<v27-1-18,18>>^ Ao final do tempo estabelecido pelo rei para que os jovens fossem trazidos à sua presença, o chefe dos oficiais os apresentou a Nabucodonosor.

[[v27-1-19]]

^<<v27-1-19,19>>^ O rei conversou com eles, e não encontrou ninguém comparável a Daniel, Hananias, Misael e Azarias; de modo que eles passaram a servir o rei.

[[v27-1-20]]

^<<v27-1-20,20>>^ O rei lhes fez perguntas sobre todos os assuntos nos quais se exigia sabedoria e conhecimento, e descobriu que eram dez vezes mais sábios do que todos os magos e encantadores de todo o seu reino.

[[v27-1-21]]

^<<v27-1-21,21>>^ E Daniel permaneceu ali até o primeiro ano do rei Ciro.

'''

xref:026-ezequiel/026-ezequiel-048.adoc#v26-48-0[&#60; Capítulo Anterior] | <<v27-1-0,Topo>> | xref:027-daniel/027-daniel-002.adoc#v27-2-0[Próximo Capítulo &#62;]