include::./index.adoc[]

[[v13-7-0]]
=== 1 Crônicas, 7
// nvi ?, NVI - Nova Versão Internacional

[[v13-7-1]]

^<<v13-7-1,1>>^ Estes foram os quatro filhos de Issacar: Tolá, Puá, Jasube e Sinrom.

[[v13-7-2]]

^<<v13-7-2,2>>^ Estes foram os filhos de Tolá: Uzi, Refaías, Jeriel, Jamai, Ibsão e Samuel, chefes dos seus clãs. No reinado de Davi, os descendentes de Tolá alistados em suas genealogias como homens de combate chegavam a 22. 600.

[[v13-7-3]]

^<<v13-7-3,3>>^ O filho de Uzi foi Israías. Estes foram os filhos de Israías: Micael, Obadias, Joel e Issias. Todos os cinco eram chefes

[[v13-7-4]]

^<<v13-7-4,4>>^ que tinham muitas mulheres e filhos. Por isso, conforme a genealogia de sua família, eles contavam com 36. 000 homens prontos para o combate.

[[v13-7-5]]

^<<v13-7-5,5>>^ Juntamente com seus parentes, os homens de combate de todos os clãs de Issacar, conforme alistados em sua genealogia, chegavam ao todo a 87. 000.

[[v13-7-6]]

^<<v13-7-6,6>>^ Estes foram os três filhos de Benjamim: Belá, Bequer e Jediael.

[[v13-7-7]]

^<<v13-7-7,7>>^ Estes foram os filhos de Belá: Esbom, Uzi, Uziel, Jeremote e Iri, cinco chefes de famílias. Seu registro genealógico alistava 22. 034 homens de combate.

[[v13-7-8]]

^<<v13-7-8,8>>^ Estes foram os filhos de Bequer: Zemira, Joás, Eliézer, Elioenai, Onri, Jeremote, Abias, Anatote e Alemete. Todos esses eram filhos de Bequer.

[[v13-7-9]]

^<<v13-7-9,9>>^ O registro genealógico deles alistava os chefes de famílias e 20. 200 homens de combate.

[[v13-7-10]]

^<<v13-7-10,10>>^ O filho de Jediael foi Bilã. Estes foram os filhos de Bilã: Jeús, Benjamim, Eúde, Quenaaná, Zetã, Társis e Aisaar.

[[v13-7-11]]

^<<v13-7-11,11>>^ Todos esses descendentes de Jediael eram chefes de famílias que contavam com 17. 200 homens de combate prontos para a guerra.

[[v13-7-12]]

^<<v13-7-12,12>>^ Supim e Hupim eram filhos de Ir; e Husim era filho de Aer.

[[v13-7-13]]

^<<v13-7-13,13>>^ Estes foram os filhos de Naftali: Jaziel, Guni, Jezer e Silém, netos de Bila.

[[v13-7-14]]

^<<v13-7-14,14>>^ Estes foram os descendentes de Manassés: Asriel, filho de sua concubina araméia, que também deu à luz Maquir, pai de Gileade.

[[v13-7-15]]

^<<v13-7-15,15>>^ Maquir casou-se com Maaca, irmã de Hupim e Supim. Outro descendente de Manassés chamava-se Zelofeade, o qual só teve filhas.

[[v13-7-16]]

^<<v13-7-16,16>>^ Maaca, mulher de Maquir, deu à luz um filho, a quem deu o nome de Perez. O nome de seu irmão era Seres, cujos filhos chamavam-se Ulão e Requém.

[[v13-7-17]]

^<<v13-7-17,17>>^ O filho de Ulão foi Bedã. Esses foram os descendentes de Gileade, filho de Maquir, e neto de Manassés.

[[v13-7-18]]

^<<v13-7-18,18>>^ Sua irmã Hamolequete deu à luz Isode, Abiezer e Maalá.

[[v13-7-19]]

^<<v13-7-19,19>>^ Estes foram os filhos de Semida: Aiã, Siquém, Liqui e Anião.

[[v13-7-20]]

^<<v13-7-20,20>>^ Estes foram os descendentes de Efraim: Sutela, que foi o pai de Berede, pai de Taate, pai de Eleada, que foi o pai de Taate,

[[v13-7-21]]

^<<v13-7-21,21>>^ pai de Zabade, pai de Sutela. Ézer e Eleade, filhos de Efraim, foram mortos por homens da cidade de Gate, quando tentavam roubar os rebanhos deles.

[[v13-7-22]]

^<<v13-7-22,22>>^ Efraim chorou muitos dias por eles, e seus parentes vieram consolá-lo.

[[v13-7-23]]

^<<v13-7-23,23>>^ Depois ele se deitou de novo com sua mulher, e ela engravidou e deu à luz um filho. Ele o chamou Berias, pois tinha acontecido uma desgraça em sua família.

[[v13-7-24]]

^<<v13-7-24,24>>^ Sua filha chamava-se Seerá. Foi ela que fundou Bete-Horom Alta e Bete-Horom Baixa e também Uzém-Seerá.

[[v13-7-25]]

^<<v13-7-25,25>>^ O filho de Berias foi Refa, pai de Resefe, que foi o pai de Telá, pai de Taã,

[[v13-7-26]]

^<<v13-7-26,26>>^ pai de Ladã, pai de Amiúde, que foi o pai de Elisama,

[[v13-7-27]]

^<<v13-7-27,27>>^ pai de Num, que foi o pai de Josué.

[[v13-7-28]]

^<<v13-7-28,28>>^ Suas terras e cidades incluíam Betel e os povoados ao redor, Naarã a leste, Gezer e seus povoados a oeste, e Siquém e Aiá com os seus povoados.

[[v13-7-29]]

^<<v13-7-29,29>>^ A tribo de Manassés controlava as cidades de Bete-Seã, Taanaque, Megido e Dor, com seus respectivos povoados. Os descendentes de José, filho de Israel, viviam nessas cidades.

[[v13-7-30]]

^<<v13-7-30,30>>^ Estes foram os filhos de Aser: Imna, Isvá, Isvi e Berias. A irmã deles chamava-se Sera.

[[v13-7-31]]

^<<v13-7-31,31>>^ Estes foram os filhos de Berias: Héber e Malquiel, que foi o pai de Birzavite.

[[v13-7-32]]

^<<v13-7-32,32>>^ Héber gerou Jaflete, Somer e Hotão, e da irmã deles, Suá.

[[v13-7-33]]

^<<v13-7-33,33>>^ Estes foram os filhos de Jaflete: Pasaque, Bimal e Asvate. Esses foram os filhos de Jaflete.

[[v13-7-34]]

^<<v13-7-34,34>>^ Estes foram os filhos de Somer: Aí, Roga, Jeubá e Arã.

[[v13-7-35]]

^<<v13-7-35,35>>^ Estes foram os filhos de Helém, irmão de Somer: Zofa, Imna, Seles e Amal.

[[v13-7-36]]

^<<v13-7-36,36>>^ Estes foram os filhos de Zofa: Suá, Harnefer, Sual, Beri, Inra,

[[v13-7-37]]

^<<v13-7-37,37>>^ Bezer, Hode, Samá, Silsa, Itrã e Beera.

[[v13-7-38]]

^<<v13-7-38,38>>^ Estes foram os filhos de Jéter: Jefoné, Pispa e Ara.

[[v13-7-39]]

^<<v13-7-39,39>>^ Estes foram os filhos de Ula: Ara, Haniel e Rizia.

[[v13-7-40]]

^<<v13-7-40,40>>^ Todos esses foram descendentes de Aser. Eram chefes de famílias, homens escolhidos, soldados valentes e líderes de destaque. O número dos alistados para combate no exército deles chegou a 26. 000.

'''

xref:013-1-cronicas/013-1-cronicas-006.adoc#v13-6-0[&#60; Capítulo Anterior] | <<v13-7-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-008.adoc#v13-8-0[Próximo Capítulo &#62;]