include::./index.adoc[]

[[v13-5-0]]
=== 1 Crônicas, 5
// nvi ?, NVI - Nova Versão Internacional

[[v13-5-1]]

^<<v13-5-1,1>>^ Estes são os filhos de Rúben, o filho mais velho de Israel. ( De fato, ele era o mais velho, mas, por ter desonrado o leito de seu pai, seus direitos de filho mais velho foram dados aos filhos de José, filho de Israel, de modo que não foi alistado nos registros genealógicos como o primeiro filho.

[[v13-5-2]]

^<<v13-5-2,2>>^ Embora Judá tenha sido o mais poderoso de seus irmãos e dele tenha vindo um líder, os direitos de filho mais velho foram dados a José ).

[[v13-5-3]]

^<<v13-5-3,3>>^ Os filhos de Rúben, filho mais velho de Israel, foram: Enoque, Palu, Hezrom e Carmi.

[[v13-5-4]]

^<<v13-5-4,4>>^ Estes foram os descendentes de Joel: Seu filho Semaías, pai de Gogue, que foi o pai de Simei,

[[v13-5-5]]

^<<v13-5-5,5>>^ pai de Mica, que foi o pai de Reaías, pai de Baal,

[[v13-5-6]]

^<<v13-5-6,6>>^ que foi o pai de Beera, a quem Tiglate-Pileser, rei da Assíria levou para o exílio. Beera era um líder da tribo de Rúben.

[[v13-5-7]]

^<<v13-5-7,7>>^ Estes foram os parentes dele, de acordo com seus clãs, alistados conforme os seus registros genealógicos: Jeiel, o chefe, Zacarias

[[v13-5-8]]

^<<v13-5-8,8>>^ e Belá, filho de Azaz, neto de Sema e bisneto de Joel. Eles foram viver na região que vai desde Aroer até o monte Nebo e Baal-Meom.

[[v13-5-9]]

^<<v13-5-9,9>>^ A leste ocuparam a terra que vai até o deserto que se estende na direção do rio Eufrates, pois os seus rebanhos tinham aumentado muito em Gileade.

[[v13-5-10]]

^<<v13-5-10,10>>^ Durante o reinado de Saul eles entraram em guerra contra os hagarenos e os derrotaram, passando a ocupar o acampamento deles por toda a região a leste de Gileade.

[[v13-5-11]]

^<<v13-5-11,11>>^ Ao lado da tribo de Rúben ficou a tribo de Gade, desde a região de Basã até Salcá.

[[v13-5-12]]

^<<v13-5-12,12>>^ Joel foi o primeiro chefe de clãs em Basã, Safã, o segundo; os outros foram Janai e Safate.

[[v13-5-13]]

^<<v13-5-13,13>>^ Estes foram os parentes deles, por famílias: Micael, Mesulão, Seba, Jorai, Jacã, Zia e Héber. Eram sete ao todo.

[[v13-5-14]]

^<<v13-5-14,14>>^ Eles eram descendentes de Abiail, filho de Huri, neto de Jaroa, bisneto de Gileade e trineto de Micael, que foi filho de Jesisai, neto de Jado e bisneto de Buz.

[[v13-5-15]]

^<<v13-5-15,15>>^ Aí, filho de Abdiel e neto de Guni, foi o chefe dessas famílias.

[[v13-5-16]]

^<<v13-5-16,16>>^ A tribo de Gade habitou em Gileade, em Basã e seus povoados, e em toda a extensão das terras de pastagem de Sarom.

[[v13-5-17]]

^<<v13-5-17,17>>^ Todos esses entraram nos registros genealógicos durante os reinados de Jotão, rei de Judá, e de Jeroboão, rei de Israel.

[[v13-5-18]]

^<<v13-5-18,18>>^ As tribos de Rúben, Gade e a metade da tribo de Manassés tinham juntas quarenta e quatro mil e setecentos e sessenta homens de combate, capazes de empunhar escudo e espada, de usar o arco, e treinados para a guerra.

[[v13-5-19]]

^<<v13-5-19,19>>^ Eles entraram em guerra contra os hagarenos e seus aliados Jetur, Nafis e Nodabe.

[[v13-5-20]]

^<<v13-5-20,20>>^ Durante a batalha clamaram a Deus, que os ajudou, entregando os hagarenos e todos os seus aliados nas suas mãos. Deus os atendeu, porque confiaram nele.

[[v13-5-21]]

^<<v13-5-21,21>>^ Tomaram dos hagarenos o rebanho de cinqüenta mil camelos, duzentas e cinqüenta mil ovelhas e dois mil jumentos. Também fizeram cem mil prisioneiros.

[[v13-5-22]]

^<<v13-5-22,22>>^ E muitos foram os inimigos mortos, pois a batalha era de Deus. Eles ocuparam aquela terra até a época do exílio.

[[v13-5-23]]

^<<v13-5-23,23>>^ A metade da tribo de Manassés era numerosa e se estabeleceu na região que vai de Basã a Baal-Hermom, isto é, até Senir, o monte Hermom.

[[v13-5-24]]

^<<v13-5-24,24>>^ Estes eram os chefes das famílias dessa tribo: Éfer, Isi, Eliel, Azriel, Jeremias, Hodavias e Jadiel. Eram soldados valentes, homens famosos, e chefes das famílias.

[[v13-5-25]]

^<<v13-5-25,25>>^ Mas foram infiéis para com o Deus dos seus antepassados e se prostituíram, seguindo os deuses dos povos que Deus tinha destruído diante deles.

[[v13-5-26]]

^<<v13-5-26,26>>^ Por isso o Deus de Israel incitou Pul, que é Tiglate-Pileser, rei da Assíria, a levar as tribos de Rúben, de Gade e a metade da tribo de Manassés para Hala, para Habor, para Hara e para o rio Gozã, onde estão até hoje.

'''

xref:013-1-cronicas/013-1-cronicas-004.adoc#v13-4-0[&#60; Capítulo Anterior] | <<v13-5-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-006.adoc#v13-6-0[Próximo Capítulo &#62;]