include::./index.adoc[]

[[v13-10-0]]
=== 1 Crônicas, 10
// nvi ?, NVI - Nova Versão Internacional

[[v13-10-1]]

^<<v13-10-1,1>>^ E aconteceu que, em combate com os filisteus, os israelitas foram postos em fuga, e muitos caíram mortos no monte Gilboa.

[[v13-10-2]]

^<<v13-10-2,2>>^ Os filisteus perseguiram Saul e seus filhos, e mataram Jônatas, Abinadabe e Malquisua, filhos de Saul.

[[v13-10-3]]

^<<v13-10-3,3>>^ O combate foi se tornando cada vez mais violento em torno de Saul, até que os flecheiros o alcançaram e o feriram gravemente.

[[v13-10-4]]

^<<v13-10-4,4>>^ Então Saul ordenou ao seu escudeiro: "Tire sua espada e mate-me com ela, senão sofrerei a vergonha de cair nas mãos desses incircuncisos". Mas o seu escudeiro estava apavorado e não quis fazê-lo. Saul, então, apanhou a própria espada e jogou-se sobre ela.

[[v13-10-5]]

^<<v13-10-5,5>>^ Quando o escudeiro viu que Saul estava morto, jogou-se também sobre sua espada e morreu.

[[v13-10-6]]

^<<v13-10-6,6>>^ Dessa maneira Saul e seus três filhos morreram, e, assim, toda a descendência real.

[[v13-10-7]]

^<<v13-10-7,7>>^ Quando os israelitas que habitavam no vale viram que o exército tinha fugido e que Saul e seus filhos estavam mortos, fugiram abandonando suas cidades. Depois os filisteus foram ocupá-las.

[[v13-10-8]]

^<<v13-10-8,8>>^ No dia seguinte, quando os filisteus foram saquear os mortos, encontraram Saul e seus filhos caídos no monte Gilboa.

[[v13-10-9]]

^<<v13-10-9,9>>^ Cortaram a cabeça de Saul, pegaram suas armas e enviaram mensageiros por toda a terra dos filisteus proclamando a notícia entre os seus ídolos e o seu povo.

[[v13-10-10]]

^<<v13-10-10,10>>^ Expuseram suas armas num dos templos dos seus deuses e penduraram sua cabeça no templo de Dagom.

[[v13-10-11]]

^<<v13-10-11,11>>^ Quando os habitantes de Jabes-Gileade ficaram sabendo o que os filisteus haviam feito com Saul,

[[v13-10-12]]

^<<v13-10-12,12>>^ os mais corajosos dentre eles foram e apanharam os corpos de Saul e de seus filhos e os levaram a Jabes. Lá sepultaram seus ossos sob a Grande Árvore, e jejuaram por sete dias.

[[v13-10-13]]

^<<v13-10-13,13>>^ Saul morreu porque foi infiel ao Senhor; não guardou a palavra do Senhor e chegou a consultar uma médiun em busca de orientação,

[[v13-10-14]]

^<<v13-10-14,14>>^ em vez de consultar o Senhor. Por isso o Senhor o entregou à morte e deu o reino a Davi, filho de Jessé.

'''

xref:013-1-cronicas/013-1-cronicas-009.adoc#v13-9-0[&#60; Capítulo Anterior] | <<v13-10-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-011.adoc#v13-11-0[Próximo Capítulo &#62;]