include::./index.adoc[]

[[v13-15-0]]
=== 1 Crônicas, 15
// nvi ?, NVI - Nova Versão Internacional

[[v13-15-1]]

^<<v13-15-1,1>>^ Depois de Davi ter construído casas para si na cidade de Davi, ele preparou um lugar para a arca de Deus e armou uma tenda para ela.

[[v13-15-2]]

^<<v13-15-2,2>>^ Então Davi disse: "Somente os levitas poderão carregar a arca de Deus, pois o Senhor os escolheu para transportarem a arca do Senhor e para ficarem sempre ao seu serviço".

[[v13-15-3]]

^<<v13-15-3,3>>^ Davi reuniu todo o Israel em Jerusalém para levar a arca do Senhor para o lugar que ele lhe havia preparado.

[[v13-15-4]]

^<<v13-15-4,4>>^ Reuniu também os descendentes de Arão e os levitas:

[[v13-15-5]]

^<<v13-15-5,5>>^ Dos descendentes de Coate, Uriel, liderando outros 120;

[[v13-15-6]]

^<<v13-15-6,6>>^ dos descendentes de Merari, Asaías, liderando outros 220;

[[v13-15-7]]

^<<v13-15-7,7>>^ dos descendentes de Gérson, Joel, liderando outros 130;

[[v13-15-8]]

^<<v13-15-8,8>>^ dos descendentes de Elisafã, Semaías, liderando outros 200;

[[v13-15-9]]

^<<v13-15-9,9>>^ dos descendentes de Hebrom, Eliel, liderando outros 80;

[[v13-15-10]]

^<<v13-15-10,10>>^ dos descendentes de Uziel, Aminadabe, liderando outros 112.

[[v13-15-11]]

^<<v13-15-11,11>>^ Então Davi convocou os sacerdotes Zadoque e Abiatar, e os levitas Uriel, Asaías, Joel, Semaías, Eliel e Aminadabe, e

[[v13-15-12]]

^<<v13-15-12,12>>^ lhes disse: "Vocês são os chefes das famílias levitas; vocês e seus companheiros levitas deverão consagrar-se e levar a arca do Senhor, o Deus de Israel, para o local que preparei para ela.

[[v13-15-13]]

^<<v13-15-13,13>>^ Pelo fato de vocês não terem carregado a arca na primeira vez, a ira do Senhor nosso Deus causou destruição entre nós. Nós não o tínhamos consultado sobre como proceder".

[[v13-15-14]]

^<<v13-15-14,14>>^ Então os sacerdotes e os levitas se consagraram para transportar a arca do Senhor, o Deus de Israel.

[[v13-15-15]]

^<<v13-15-15,15>>^ E os levitas carregaram a arca de Deus apoiando as varas da arca sobre os ombros, conforme Moisés tinha ordenado, de acordo com a palavra do Senhor.

[[v13-15-16]]

^<<v13-15-16,16>>^ Davi também ordenou aos líderes dos levitas que encarregassem os músicos que havia entre eles de cantar músicas alegres, acompanhados por instrumentos musicais: liras, harpas e címbalos sonoros.

[[v13-15-17]]

^<<v13-15-17,17>>^ Assim, os levitas escolheram Hemã, filho de Joel, e Asafe, um parente dele; e dentre os meraritas, seus parentes, escolheram Etã, filho de Cuxaías;

[[v13-15-18]]

^<<v13-15-18,18>>^ e com eles seus parentes que estavam no segundo escalão: Zacarias, Jaaziel, Semiramote, Jeiel, Uni, Eliabe, Benaia, Maaséias, Matitias, Elifeleu, Micnéias, Obede-Edom e Jeiel, os porteiros.

[[v13-15-19]]

^<<v13-15-19,19>>^ Os músicos Hemã, Asafe e Etã deviam tocar os címbalos de bronze;

[[v13-15-20]]

^<<v13-15-20,20>>^ Zacarias, Aziel, Semiramote, Jeiel, Uni, Eliabe, Maaséias e Benaia deviam tocar as liras, acompanhando o soprano,

[[v13-15-21]]

^<<v13-15-21,21>>^ e Matitias, Elifeleu, Micnéias, Obede-Edom, Jeiel e Azazias deviam tocar as harpas em oitava, marcando o ritmo.

[[v13-15-22]]

^<<v13-15-22,22>>^ Quenanias, o chefe dos levitas, ficou encarregado dos cânticos; essa era sua responsabilidade, pois ele era capaz nisso.

[[v13-15-23]]

^<<v13-15-23,23>>^ Berequias e Elcana seriam porteiros. Eles deveriam proteger a arca.

[[v13-15-24]]

^<<v13-15-24,24>>^ Os sacerdotes Sebanias, Josafá, Natanael, Amasai, Zacarias, Benaia e Eliézer deviam tocar as cornetas diante da arca de Deus. Obede-Edom e Jeías também deviam ser porteiros, para vigiar a arca.

[[v13-15-25]]

^<<v13-15-25,25>>^ Assim, com grande festa, foram Davi, as autoridades de Israel e os líderes de batalhões de mil buscar a arca da aliança do Senhor na casa de Obede-Edom.

[[v13-15-26]]

^<<v13-15-26,26>>^ Como Deus havia poupado os levitas que carregavam a arca da aliança do Senhor, sete novilhos e sete carneiros foram sacrificados.

[[v13-15-27]]

^<<v13-15-27,27>>^ E Davi vestia um manto de linho fino, assim como também todos os levitas que carregavam a arca, os músicos e Quenanias, chefe dos músicos. E Davi vestia também o colete sacerdotal de linho.

[[v13-15-28]]

^<<v13-15-28,28>>^ E todo Israel acompanhou a arca da aliança do Senhor alegremente, ao som de trombetas, cornetas e címbalos, ao toque de liras e de harpas.

[[v13-15-29]]

^<<v13-15-29,29>>^ Aconteceu que, entrando a arca da aliança do Senhor na cidade de Davi, Mical, filha de Saul, observava de uma janela. E, ao ver o rei Davi dançando e comemorando, ela o desprezou em seu coração.

'''

xref:013-1-cronicas/013-1-cronicas-014.adoc#v13-14-0[&#60; Capítulo Anterior] | <<v13-15-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-016.adoc#v13-16-0[Próximo Capítulo &#62;]