include::./index.adoc[]

[[v13-27-0]]
=== 1 Crônicas, 27
// nvi ?, NVI - Nova Versão Internacional

[[v13-27-1]]

^<<v13-27-1,1>>^ Esta é a lista dos israelitas, chefes de famílias, comandantes de mil e comandantes de cem; oficiais que serviam o rei na supervisão das divisões do exército que estavam de serviço mês a mês, durante o ano. Cada divisão era constituída por 24. 000 homens.

[[v13-27-2]]

^<<v13-27-2,2>>^ Encarregado da primeira divisão de 24. 000 homens, para o primeiro mês, estava Jasobeão, filho de Zabdiel.

[[v13-27-3]]

^<<v13-27-3,3>>^ Ele era descendente de Perez e chefe de todos os oficiais do exército para o primeiro mês.

[[v13-27-4]]

^<<v13-27-4,4>>^ Encarregado da divisão para o segundo mês estava Dodai, descendente de Aoí; Miclote era o líder da sua divisão que contava 24. 000 homens.

[[v13-27-5]]

^<<v13-27-5,5>>^ O terceiro comandante do exército, para o terceiro mês, foi Benaia, filho do sacerdote Joiada. Ele era chefe da sua divisão de 24. 000 homens.

[[v13-27-6]]

^<<v13-27-6,6>>^ Esse Benaia foi guerreiro, chefe dos Trinta. Seu filho Amizabade estava encarregado da sua divisão.

[[v13-27-7]]

^<<v13-27-7,7>>^ O quarto, para o quarto mês, foi Asael, irmão de Joabe; seu filho Zebadias foi seu sucessor. Havia 24. 000 homens em sua divisão.

[[v13-27-8]]

^<<v13-27-8,8>>^ O quinto, para o quinto mês, foi o comandante Samute, o izraíta. Havia 24. 000 homens em sua divisão.

[[v13-27-9]]

^<<v13-27-9,9>>^ O sexto, para o sexto mês, foi Ira, filho de Iques, de Tecoa. Havia 24. 000 homens em sua divisão.

[[v13-27-10]]

^<<v13-27-10,10>>^ O sétimo, para o sétimo mês, foi Helez, de Pelom, descendente de Efraim. Havia 24. 000 homens em sua divisão.

[[v13-27-11]]

^<<v13-27-11,11>>^ O oitavo, para o oitavo mês, foi Sibecai, de Husate, da família de Zerá. Havia 24. 000 homens em sua divisão.

[[v13-27-12]]

^<<v13-27-12,12>>^ O nono, para o nono mês, foi Abiezer, de Anatote, da tribo de Benjamim. Havia 24. 000 homens em sua divisão.

[[v13-27-13]]

^<<v13-27-13,13>>^ O décimo, para o décimo mês, foi Maarai, de Netofate, da família de Zerá. Havia 24. 000 homens em sua divisão.

[[v13-27-14]]

^<<v13-27-14,14>>^ O décimo primeiro, para o décimo primeiro mês, foi Benaia, de Piratom, descendente de Efraim. Havia 24. 000 homens em sua divisão.

[[v13-27-15]]

^<<v13-27-15,15>>^ O décimo segundo, para o décimo segundo mês, foi Heldai, de Netofate, da família de Otoniel. Havia 24. 000 homens em sua divisão.

[[v13-27-16]]

^<<v13-27-16,16>>^ Estes foram os líderes das tribos de Israel: de Rúben: Eliézer, filho de Zicri; de Simeão: Sefatias, filho de Maaca;

[[v13-27-17]]

^<<v13-27-17,17>>^ de Levi: Hasabias, filho de Quemuel; de Arão: Zadoque;

[[v13-27-18]]

^<<v13-27-18,18>>^ de Judá: Eliú, irmão de Davi; de Issacar: Onri, filho de Micael;

[[v13-27-19]]

^<<v13-27-19,19>>^ de Zebulom: Ismaías, filho de Obadias; de Naftali: Jeremote, filho de Azriel;

[[v13-27-20]]

^<<v13-27-20,20>>^ dos descendentes de Efraim: Oséias, filho de Azazias; da metade da tribo de Manassés: Joel, filho de Pedaías;

[[v13-27-21]]

^<<v13-27-21,21>>^ da outra metade da tribo de Manassés, em Gileade: Ido, filho de Zacarias; de Benjamim: Jaasiel, filho de Abner;

[[v13-27-22]]

^<<v13-27-22,22>>^ de Dã: Azareel, filho de Jeroão. Foram esses os líderes das tribos de Israel.

[[v13-27-23]]

^<<v13-27-23,23>>^ Davi não contou os homens com menos de vinte anos, pois o Senhor havia prometido tornar Israel tão numeroso quanto as estrelas do céu.

[[v13-27-24]]

^<<v13-27-24,24>>^ Joabe, filho de Zeruia, começou a contar os homens, mas não pôde terminar. A ira divina caiu sobre Israel por causa desse recenseamento, e o resultado não entrou nos registros históricos do rei Davi.

[[v13-27-25]]

^<<v13-27-25,25>>^ Azmavete, filho de Adiel, estava encarregado dos tesouros do palácio. Jônatas, filho de Uzias, estava encarregado dos depósitos do rei nos distritos distantes, nas cidades, nos povoados e nas torres de sentinela.

[[v13-27-26]]

^<<v13-27-26,26>>^ Ezri, filho de Quelube, estava encarregado dos trabalhadores rurais, que cultivavam a terra.

[[v13-27-27]]

^<<v13-27-27,27>>^ Simei, de Ramá, estava encarregado das vinhas. Zabdi, de Sifá, estava encarregado do vinho que era armazenado em tonéis.

[[v13-27-28]]

^<<v13-27-28,28>>^ Baal-Hanã, de Gederá, estava encarregado das oliveiras e das figueiras bravas, na Sefelá. Joás estava encarregado do fornecimento de azeite.

[[v13-27-29]]

^<<v13-27-29,29>>^ Sitrai, de Sarom, estava encarregado dos rebanhos que pastavam em Sarom. Safate, filho de Adlai, estava encarregado dos rebanhos nos vales.

[[v13-27-30]]

^<<v13-27-30,30>>^ O ismaelita Obil estava encarregado dos camelos. Jedias, de Meronote, estava encarregado dos jumentos.

[[v13-27-31]]

^<<v13-27-31,31>>^ O hagareno Jaziz estava encarregado das ovelhas. Todos esses eram encarregados de cuidar dos bens do rei Davi.

[[v13-27-32]]

^<<v13-27-32,32>>^ Jônatas, tio de Davi, era conselheiro; homem sábio e também escriba. Jeiel, filho de Hacmoni, cuidava dos filhos do rei.

[[v13-27-33]]

^<<v13-27-33,33>>^ Aitofel era conselheiro do rei. Husai, o arquita, era amigo do rei.

[[v13-27-34]]

^<<v13-27-34,34>>^ Aitofel foi sucedido por Joiada, filho de Benaia, e por Abiatar. Joabe era o comandante do exército real.

'''

xref:013-1-cronicas/013-1-cronicas-026.adoc#v13-26-0[&#60; Capítulo Anterior] | <<v13-27-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-028.adoc#v13-28-0[Próximo Capítulo &#62;]