include::./index.adoc[]

[[v13-4-0]]
=== 1 Crônicas, 4
// nvi ?, NVI - Nova Versão Internacional

[[v13-4-1]]

^<<v13-4-1,1>>^ Estes foram os descendentes de Judá: Perez, Hezrom, Carmi, Hur e Sobal.

[[v13-4-2]]

^<<v13-4-2,2>>^ Reaías, filho de Sobal, gerou Jaate, e Jaate gerou Aumai e Laade. Esses foram os clãs dos zoratitas.

[[v13-4-3]]

^<<v13-4-3,3>>^ Estes foram os filhos de Etã: Jezreel, Isma e Idbás. A irmã deles chamava-se Hazelelponi.

[[v13-4-4]]

^<<v13-4-4,4>>^ Depois teve Penuel, pai de Gedor, e Ézer, pai de Husá. Esses foram os descendentes de Hur, o filho mais velho de Efrate e pai de Belém.

[[v13-4-5]]

^<<v13-4-5,5>>^ Asur, fundador de Tecoa, teve duas mulheres: Helá e Naará.

[[v13-4-6]]

^<<v13-4-6,6>>^ Naará lhe deu Auzã, Héfer, Temeni e Haastari. Esses foram os filhos de Naará.

[[v13-4-7]]

^<<v13-4-7,7>>^ Estes foram os filhos de Helá: Zerete, Zoar, Etnã

[[v13-4-8]]

^<<v13-4-8,8>>^ e Coz, que gerou Anube e Zobeba e os clãs de Aarel, filho de Harum.

[[v13-4-9]]

^<<v13-4-9,9>>^ Jabez foi o homem mais respeitado de sua família. Sua mãe lhe deu o nome de Jabez, dizendo: "Com muitas dores o dei à luz".

[[v13-4-10]]

^<<v13-4-10,10>>^ Jabez orou ao Deus de Israel: "Ah, abençoa-me e aumenta as minhas terras! Que a tua mão esteja comigo, guardando-me de males e livrando-me de dores". E Deus atendeu ao seu pedido.

[[v13-4-11]]

^<<v13-4-11,11>>^ Quelube, irmão de Suá, gerou Meir, pai de Estom.

[[v13-4-12]]

^<<v13-4-12,12>>^ Estom gerou Bete-Rafa, Paséia e Teína, fundador de Ir-Naás. Esses habitaram em Reca.

[[v13-4-13]]

^<<v13-4-13,13>>^ Estes foram os filhos de Quenaz: Otoniel e Seraías. Estes foram os filhos de Otoniel: Hatate e Meonotai.

[[v13-4-14]]

^<<v13-4-14,14>>^ Meonotai gerou Ofra. Seraías gerou Joabe, fundador de Ge-Harasim que recebeu esse nome porque os seus habitantes eram artesãos.

[[v13-4-15]]

^<<v13-4-15,15>>^ Estes foram os filhos de Calebe, filho de Jefoné: Iru, Elá e Naã. O filho de Elá foi Quenaz.

[[v13-4-16]]

^<<v13-4-16,16>>^ Estes foram os filhos de Jealelel: Zife, Zifa, Tiria e Asareel.

[[v13-4-17]]

^<<v13-4-17,17>>^ Estes foram os filhos de Ezra: Jéter, Merede, Éfer e Jalom. Merede casou-se com Bitia, filha do faraó, e teve os seguintes filhos: Miriã, Samai e Isbá, fundador de Estemoa.

[[v13-4-18]]

^<<v13-4-18,18>>^ Sua mulher judia deu à luz a Jerede, fundador de Gedor, a Héber, fundador de Socó, e a Jecutiel, fundador de Zanoa.

[[v13-4-19]]

^<<v13-4-19,19>>^ Estes foram os filhos da mulher de Hodias, irmã de Naã: o pai de Queila, o garmita, e Estemoa, o maacatita.

[[v13-4-20]]

^<<v13-4-20,20>>^ Estes foram os filhos de Simão: Amnom, Rina, Bene-Hanã e Tilom. Estes foram os filhos de Isi: Zoete e Ben-Zoete.

[[v13-4-21]]

^<<v13-4-21,21>>^ Estes foram os filhos de Selá, filho de Judá: Er, pai de Leca; Lada, pai de Maressa. Selá também foi antepassado dos clãs dos que trabalhavam com linho em Bete-Asbéia,

[[v13-4-22]]

^<<v13-4-22,22>>^ de Joquim, dos homens de Cozeba, de Joás e de Sarafe, que governavam em Moabe e Jasubi-Leém. ( Estes registros são de épocas antigas. )

[[v13-4-23]]

^<<v13-4-23,23>>^ Eles eram oleiros e habitavam em Netaim e em Gederá, perto do rei, para quem trabalhavam.

[[v13-4-24]]

^<<v13-4-24,24>>^ Estes foram os filhos de Simeão: Nemuel, Jamim, Jaribe, Zerá e Saul;

[[v13-4-25]]

^<<v13-4-25,25>>^ O filho de Saul era Salum, pai de Mibsão, que foi o pai de Misma.

[[v13-4-26]]

^<<v13-4-26,26>>^ Estes foram os descendentes de Misma: seu filho Hamuel, pai de Zacur, que foi o pai de Simei.

[[v13-4-27]]

^<<v13-4-27,27>>^ Simei teve dezesseis filhos e seis filhas, mas seus irmãos não tiveram muitos filhos; por isso todos os seus clãs não se igualam em número à tribo de Judá.

[[v13-4-28]]

^<<v13-4-28,28>>^ Eles viviam em Berseba, Moladá, Hazar-Sual,

[[v13-4-29]]

^<<v13-4-29,29>>^ Bila, Ezém, Tolade,

[[v13-4-30]]

^<<v13-4-30,30>>^ Betuel, Hormá, Ziclague,

[[v13-4-31]]

^<<v13-4-31,31>>^ Bete-Marcabote, Hazar-Susim, Bete-Biri e Saaraim. Essas foram as suas cidades até o reinado de Davi.

[[v13-4-32]]

^<<v13-4-32,32>>^ Tinham também as cinco cidades de Etã, Aim, Rimom, Toquém e Asã,

[[v13-4-33]]

^<<v13-4-33,33>>^ com todos os povoados ao redor delas até Baalate. Nessas cidades viviam e mantinham um registro genealógico.

[[v13-4-34]]

^<<v13-4-34,34>>^ Mesobabe, Janleque, Josa, filho de Amazias,

[[v13-4-35]]

^<<v13-4-35,35>>^ Joel, Jeú, filho de Josibias, neto de Seraías e bisneto de Asiel;

[[v13-4-36]]

^<<v13-4-36,36>>^ também Elioenai, Jaacobá, Jesoaías, Asaías, Adiel, Jesimiel, Benaia,

[[v13-4-37]]

^<<v13-4-37,37>>^ e Ziza, filho de Sifi, neto de Alom, bisneto de Jedaías, trineto de Sinri e tetraneto de Semaías.

[[v13-4-38]]

^<<v13-4-38,38>>^ Essa é a lista dos líderes dos seus clãs. Suas famílias cresceram muito,

[[v13-4-39]]

^<<v13-4-39,39>>^ e por isso foram para os arredores de Gedor, a leste do vale, em busca de pastagens para os seus rebanhos.

[[v13-4-40]]

^<<v13-4-40,40>>^ Encontraram muitas pastagens boas, numa região vasta, pacífica e tranqüila, onde alguns camitas tinham vivido anteriormente.

[[v13-4-41]]

^<<v13-4-41,41>>^ Durante o reinado de Ezequias, rei de Judá, esses homens aqui alistados chegaram e atacaram os camitas e os meunitas da região e os destruíram totalmente, como até hoje se pode ver. Depois ocuparam o lugar daqueles povos, pois havia pastagens para os seus rebanhos.

[[v13-4-42]]

^<<v13-4-42,42>>^ E quinhentos desses simeonitas, liderados por Pelatias, Nearias, Refaías e Uziel, filhos de Isi, invadiram as colinas de Seir.

[[v13-4-43]]

^<<v13-4-43,43>>^ Eles mataram o restante dos amalequitas que tinha escapado, e ali vivem até hoje.

'''

xref:013-1-cronicas/013-1-cronicas-003.adoc#v13-3-0[&#60; Capítulo Anterior] | <<v13-4-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-005.adoc#v13-5-0[Próximo Capítulo &#62;]