include::./index.adoc[]

[[v13-1-0]]
=== 1 Crônicas, 1
// nvi ?, NVI - Nova Versão Internacional

[[v13-1-1]]

^<<v13-1-1,1>>^ Adão, Sete, Enos,

[[v13-1-2]]

^<<v13-1-2,2>>^ Cainã, Malaleel, Jarede,

[[v13-1-3]]

^<<v13-1-3,3>>^ Enoque, Matusalém, Lameque, Noé.

[[v13-1-4]]

^<<v13-1-4,4>>^ Estes foram os filhos de Noé: Sem, Cam e Jafé.

[[v13-1-5]]

^<<v13-1-5,5>>^ Estes foram os filhos de Jafé: Gômer, Magogue, Madai, Javã, Tubal, Meseque e Tirás.

[[v13-1-6]]

^<<v13-1-6,6>>^ Estes foram os filhos de Gômer: Asquenaz, Rifate e Togarma.

[[v13-1-7]]

^<<v13-1-7,7>>^ Estes foram os filhos de Javã: Elisá, Társis, Quitim e Rodanim.

[[v13-1-8]]

^<<v13-1-8,8>>^ Estes foram os filhos de Cam: Cuxe, Mizraim, Fute e Canaã.

[[v13-1-9]]

^<<v13-1-9,9>>^ Estes foram os filhos de Cuxe: Sebá, Havilá, Sabtá, Raamá e Sabtecá. Estes foram os filhos de Raamá: Sabá e Dedã.

[[v13-1-10]]

^<<v13-1-10,10>>^ Cuxe gerou Ninrode, o primeiro homem poderoso na terra.

[[v13-1-11]]

^<<v13-1-11,11>>^ Mizraim gerou os luditas, os anamitas, os leabitas, os naftuítas,

[[v13-1-12]]

^<<v13-1-12,12>>^ os patrusitas, os casluítas, dos quais se originaram os filisteus, e os caftoritas.

[[v13-1-13]]

^<<v13-1-13,13>>^ Canaã gerou Sidom, seu filho mais velho, e Hete,

[[v13-1-14]]

^<<v13-1-14,14>>^ como também os jebuseus, os amorreus, os girgaseus,

[[v13-1-15]]

^<<v13-1-15,15>>^ os heveus, os arqueus, os sineus,

[[v13-1-16]]

^<<v13-1-16,16>>^ os arvadeus, os zemareus e os hamateus.

[[v13-1-17]]

^<<v13-1-17,17>>^ Estes foram os filhos de Sem: Elão, Assur, Arfaxade, Lude e Arã. Estes foram os filhos de Arã: Uz, Hul, Géter e Meseque.

[[v13-1-18]]

^<<v13-1-18,18>>^ Arfaxade gerou Salá, e este gerou Héber.

[[v13-1-19]]

^<<v13-1-19,19>>^ A Héber nasceram dois filhos: Um deles se chamou Pelegue, porque em sua época a terra foi dividida; seu irmão chamou-se Joctã.

[[v13-1-20]]

^<<v13-1-20,20>>^ Joctã gerou Almodá, Salefe, Hazarmavé, Jerá,

[[v13-1-21]]

^<<v13-1-21,21>>^ Hadorão, Uzal, Dicla,

[[v13-1-22]]

^<<v13-1-22,22>>^ Obal, Abimael, Sabá,

[[v13-1-23]]

^<<v13-1-23,23>>^ Ofir, Havilá e Jobabe. Todos esses foram filhos de Joctã.

[[v13-1-24]]

^<<v13-1-24,24>>^ Sem, Arfaxade, Salá,

[[v13-1-25]]

^<<v13-1-25,25>>^ Héber, Pelegue, Reú,

[[v13-1-26]]

^<<v13-1-26,26>>^ Serugue, Naor, Terá

[[v13-1-27]]

^<<v13-1-27,27>>^ e Abrão, que é Abraão.

[[v13-1-28]]

^<<v13-1-28,28>>^ Estes foram os filhos de Abraão: Isaque e Ismael.

[[v13-1-29]]

^<<v13-1-29,29>>^ Foram estes os seus descendentes: Nebaiote, o filho mais velho de Ismael, Quedar, Adbeel, Mibsão,

[[v13-1-30]]

^<<v13-1-30,30>>^ Misma, Dumá, Massá, Hadade, Temá,

[[v13-1-31]]

^<<v13-1-31,31>>^ Jetur, Nafis e Quedemá. Esses foram os filhos de Ismael.

[[v13-1-32]]

^<<v13-1-32,32>>^ Estes foram os filhos de Abraão com sua concubina Quetura: Zinrã, Jocsã, Medã, Midiã, Isbaque e Suá. Foram estes os filhos de Jocsã: Sabá e Dedã.

[[v13-1-33]]

^<<v13-1-33,33>>^ Foram estes os filhos de Midiã: Efá, Éfer, Enoque, Abida e Elda. Todos esses foram descendentes de Quetura.

[[v13-1-34]]

^<<v13-1-34,34>>^ Abraão gerou Isaque. Estes foram os filhos de Isaque: Esaú e Israel.

[[v13-1-35]]

^<<v13-1-35,35>>^ Estes foram os filhos de Esaú: Elifaz, Reuel, Jeús, Jalão e Corá.

[[v13-1-36]]

^<<v13-1-36,36>>^ Estes foram os filhos de Elifaz: Temã, Omar, Zefô, Gaetã e Quenaz; e Amaleque, de Timna, sua concumbina.

[[v13-1-37]]

^<<v13-1-37,37>>^ Estes foram os filhos de Reuel: Naate, Zerá, Samá e Mizá.

[[v13-1-38]]

^<<v13-1-38,38>>^ Estes foram os filhos de Seir: Lotã, Sobal, Zibeão, Aná, Disom, Eser e Disã. Lotã tinha uma irmã chamada Timna.

[[v13-1-39]]

^<<v13-1-39,39>>^ Estes foram os filhos de Lotã: Hori e Homã.

[[v13-1-40]]

^<<v13-1-40,40>>^ Estes foram os filhos de Sobal: Alvã, Manaate, Ebal, Sefô e Onã. Estes foram os filhos de Zibeão: Aiá e Aná.

[[v13-1-41]]

^<<v13-1-41,41>>^ Este foi o filho de Aná: Disom. Estes foram os filhos de Disom: Hendã, Esbã, Itrã e Querã.

[[v13-1-42]]

^<<v13-1-42,42>>^ Estes foram os filhos de Eser: Bilã, Zaavã e Acã. Estes foram os filhos de Disã: Uz e Arã.

[[v13-1-43]]

^<<v13-1-43,43>>^ Estes foram os reis que reinaram no território de Edom antes que os israelitas tivessem um rei: Belá, filho de Beor. Sua cidade chamava-se Dinabá.

[[v13-1-44]]

^<<v13-1-44,44>>^ Belá morreu, e Jobabe, filho de Zerá, de Bozra, foi o seu sucessor.

[[v13-1-45]]

^<<v13-1-45,45>>^ Jobabe morreu, e Husã, da terra dos temanitas, foi o seu sucessor.

[[v13-1-46]]

^<<v13-1-46,46>>^ Husã morreu, e Hadade, filho de Bedade, que tinha derrotado os midianitas na terra de Moabe, foi o seu sucessor. Sua cidade chamava-se Avite.

[[v13-1-47]]

^<<v13-1-47,47>>^ Hadade morreu, e Samlá de Masreca foi o seu sucessor.

[[v13-1-48]]

^<<v13-1-48,48>>^ Samlá morreu, e Saul, de Reobote, próxima ao Eufrates, foi o seu sucessor.

[[v13-1-49]]

^<<v13-1-49,49>>^ Saul morreu, e Baal-Hanã, filho de Acbor, foi o seu sucessor.

[[v13-1-50]]

^<<v13-1-50,50>>^ Baal-Hanã morreu, e Hadade foi o seu sucessor. Sua cidade chamava-se Paú, e o nome de sua mulher era Meetabel, filha de Matrede e neta de Mezaabe.

[[v13-1-51]]

^<<v13-1-51,51>>^ Após a morte de Hadade, Edom foi governada pelos seguintes chefes: Timna, Alva, Jetete,

[[v13-1-52]]

^<<v13-1-52,52>>^ Oolibama, Elá, Pinom,

[[v13-1-53]]

^<<v13-1-53,53>>^ Quenaz, Temã, Mibzar,

[[v13-1-54]]

^<<v13-1-54,54>>^ Magdiel e Irã. Foram esses os chefes de Edom.

'''

xref:012-2-reis/012-2-reis-025.adoc#v12-25-0[&#60; Capítulo Anterior] | <<v13-1-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-002.adoc#v13-2-0[Próximo Capítulo &#62;]