include::./index.adoc[]

[[v13-2-0]]
=== 1 Crônicas, 2
// nvi ?, NVI - Nova Versão Internacional

[[v13-2-1]]

^<<v13-2-1,1>>^ Estes foram os filhos de Israel: Rúben, Simeão, Levi, Judá, Issacar, Zebulom,

[[v13-2-2]]

^<<v13-2-2,2>>^ Dã, José, Benjamim, Naftali, Gade e Aser.

[[v13-2-3]]

^<<v13-2-3,3>>^ Estes foram os filhos de Judá: Er, Onã e Selá. Ele teve esses três filhos com uma mulher cananéia, a filha de Suá. Mas o Senhor reprovou a conduta perversa de Er, filho mais velho de Judá, e por isso o matou.

[[v13-2-4]]

^<<v13-2-4,4>>^ Tamar, nora de Judá, deu-lhe os filhos Perez e Zerá. A Judá nasceram ao todo cinco filhos.

[[v13-2-5]]

^<<v13-2-5,5>>^ Estes foram os filhos de Perez: Hezrom e Hamul.

[[v13-2-6]]

^<<v13-2-6,6>>^ Estes foram os filhos de Zerá: Zinri, Etã, Hemã, Calcol e Darda. Foram cinco ao todo.

[[v13-2-7]]

^<<v13-2-7,7>>^ O filho de Carmi foi Acar. Ele causou desgraça a Israel ao violar a proibição de se apossar das coisas consagradas.

[[v13-2-8]]

^<<v13-2-8,8>>^ Este foi o filho de Etã: Azarias.

[[v13-2-9]]

^<<v13-2-9,9>>^ Os filhos que nasceram a Hezrom foram Jerameel, Rão e Calebe.

[[v13-2-10]]

^<<v13-2-10,10>>^ Rão gerou Aminadabe, e Aminadabe gerou Naassom, o líder da tribo de Judá.

[[v13-2-11]]

^<<v13-2-11,11>>^ Naassom gerou Salmom, Salmom gerou Boaz,

[[v13-2-12]]

^<<v13-2-12,12>>^ Boaz gerou Obede, e Obede gerou Jessé.

[[v13-2-13]]

^<<v13-2-13,13>>^ Jessé gerou Eliabe, o seu filho mais velho; o segundo foi Abinadabe, o terceiro Siméia,

[[v13-2-14]]

^<<v13-2-14,14>>^ o quarto Natanael, o quinto Radai,

[[v13-2-15]]

^<<v13-2-15,15>>^ o sexto Ozém, e o sétimo Davi.

[[v13-2-16]]

^<<v13-2-16,16>>^ As irmãs deles foram Zeruia e Abigail. Os três filhos de Zeruia foram Abisai, Joabe e Asael.

[[v13-2-17]]

^<<v13-2-17,17>>^ Abigail deu à luz Amasa, filho do ismaelita Jéter.

[[v13-2-18]]

^<<v13-2-18,18>>^ Calebe, filho de Hezrom, teve uma filha chamada Jeriote com sua mulher Azuba. Estes foram os filhos de Azuba: Jeser, Sobabe e Ardom.

[[v13-2-19]]

^<<v13-2-19,19>>^ Quando Azuba morreu, Calebe tomou por mulher a Efrate, com quem teve Hur.

[[v13-2-20]]

^<<v13-2-20,20>>^ Hur gerou Uri, e Uri gerou Bezalel.

[[v13-2-21]]

^<<v13-2-21,21>>^ Depois disso, Hezrom, aos sessenta anos, tomou por mulher a filha de Maquir, pai de Gileade e ela deu-lhe um filho chamado Segube.

[[v13-2-22]]

^<<v13-2-22,22>>^ Segube gerou Jair, que governou vinte e três cidades em Gileade.

[[v13-2-23]]

^<<v13-2-23,23>>^ Gesur e Arã conquistaram Havote-Jair, bem como Quenate e os povoados ao redor, ao todo sessenta cidades. Todos esses foram descendentes de Maquir, pai de Gileade.

[[v13-2-24]]

^<<v13-2-24,24>>^ Depois que Hezrom morreu em Calebe-Efrata, Abia, a mulher de Hezrom, deu-lhe Asur, fundador de Tecoa.

[[v13-2-25]]

^<<v13-2-25,25>>^ Estes foram os filhos de Jerameel, o filho mais velho de Hezrom: Rão, o mais velho, Buna, Orém, Ozém e Aías.

[[v13-2-26]]

^<<v13-2-26,26>>^ Jerameel teve outra mulher, chamada Atara, que foi a mãe de Onã.

[[v13-2-27]]

^<<v13-2-27,27>>^ Estes foram os filhos de Rão, o filho mais velho de Jerameel: Maaz, Jamim e Equer.

[[v13-2-28]]

^<<v13-2-28,28>>^ Estes foram os filhos de Onã: Samai e Jada. Estes foram os filhos de Samai: Nadabe e Abisur.

[[v13-2-29]]

^<<v13-2-29,29>>^ O nome da mulher de Abisur era Abiail. Ela deu-lhe dois filhos: Abã e Molide.

[[v13-2-30]]

^<<v13-2-30,30>>^ Estes foram os filhos de Nadabe: Selede e Apaim. Selede morreu sem filhos.

[[v13-2-31]]

^<<v13-2-31,31>>^ O filho de Apaim foi Isi, pai de Sesã, pai de Alai.

[[v13-2-32]]

^<<v13-2-32,32>>^ Estes foram os filhos de Jada, irmão de Samai: Jéter e Jônatas. Jéter morreu sem filhos.

[[v13-2-33]]

^<<v13-2-33,33>>^ Estes foram os filhos de Jônatas: Pelete e Zaza. Foram esses os descendentes de Jera-meel.

[[v13-2-34]]

^<<v13-2-34,34>>^ Sesã não teve filhos, apenas filhas. Tinha ele um escravo egípcio chamado Jará,

[[v13-2-35]]

^<<v13-2-35,35>>^ a quem deu uma de suas filhas por mulher. E ela deu-lhe um filho chamado Atai.

[[v13-2-36]]

^<<v13-2-36,36>>^ Atai gerou Natã, Natã gerou Zabade,

[[v13-2-37]]

^<<v13-2-37,37>>^ Zabade gerou Eflal, Eflal gerou Obede,

[[v13-2-38]]

^<<v13-2-38,38>>^ Obede gerou Jeú, Jeú gerou Azarias,

[[v13-2-39]]

^<<v13-2-39,39>>^ Azarias gerou Helez, Helez gerou Eleasa,

[[v13-2-40]]

^<<v13-2-40,40>>^ Eleasa gerou Sismai, Sismai gerou Salum,

[[v13-2-41]]

^<<v13-2-41,41>>^ Salum gerou Jecamias, e Jecamias gerou Elisama.

[[v13-2-42]]

^<<v13-2-42,42>>^ Estes foram os filhos de Calebe, irmão de Jerameel: Messa, o mais velho, que foi o pai de Zife, e seu filho Maressa, pai de Hebrom.

[[v13-2-43]]

^<<v13-2-43,43>>^ Estes foram os filhos de Hebrom: Corá, Tapua, Requém e Sema.

[[v13-2-44]]

^<<v13-2-44,44>>^ Sema gerou Raão, pai de Jorqueão. Requém gerou Samai.

[[v13-2-45]]

^<<v13-2-45,45>>^ O filho de Samai foi Maom, e Maom foi o pai de Bete-Zur.

[[v13-2-46]]

^<<v13-2-46,46>>^ A concubina de Calebe, Efá teve três filhos: Harã, Mosa e Gazez. Harã gerou Gazez.

[[v13-2-47]]

^<<v13-2-47,47>>^ Estes foram os filhos de Jadai: Regém, Jotão, Gesã, Pelete, Efá e Saafe.

[[v13-2-48]]

^<<v13-2-48,48>>^ A concubina de Calebe, Maaca teve dois filhos: Seber e Tiraná.

[[v13-2-49]]

^<<v13-2-49,49>>^ Ela também teve Saafe, pai de Madmana, e Seva, pai de Macbena e de Gibeá. A filha de Calebe chamava-se Acsa.

[[v13-2-50]]

^<<v13-2-50,50>>^ Calebe teve também estes outros descendentes: Os filhos de Hur, o filho mais velho de Efrate: Sobal, fundador de Quiriate-Jearim,

[[v13-2-51]]

^<<v13-2-51,51>>^ Salma, fundador de Belém, e Harefe, fundador de Bete-Gader.

[[v13-2-52]]

^<<v13-2-52,52>>^ Os descendentes de Sobal, fundador de Quiriate-Jearim: O povo de Haroé, metade dos manaatitas,

[[v13-2-53]]

^<<v13-2-53,53>>^ e os clãs de Quiriate-Jearim: os itritas, os fateus, os sumateus e os misraeus. Desses descenderam os zoratitas e os estaoleus.

[[v13-2-54]]

^<<v13-2-54,54>>^ Os descendentes de Salma: O povo de Belém e de Atrote-Bete-Joabe, os netofatitas, metade dos manaatitas, os zoreus,

[[v13-2-55]]

^<<v13-2-55,55>>^ e os clãs dos escribas que viviam em Jabez: os tiratitas, os simeatitas e os sucatitas. Esses foram os queneus, descendentes de Hamate, antepassado da família de Recabe.

'''

xref:013-1-cronicas/013-1-cronicas-001.adoc#v13-1-0[&#60; Capítulo Anterior] | <<v13-2-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-003.adoc#v13-3-0[Próximo Capítulo &#62;]