include::./index.adoc[]

[[v13-21-0]]
=== 1 Crônicas, 21
// nvi ?, NVI - Nova Versão Internacional

[[v13-21-1]]

^<<v13-21-1,1>>^ Satanás levantou-se contra Israel e levou Davi a fazer um recenseamento do povo.

[[v13-21-2]]

^<<v13-21-2,2>>^ Davi disse a Joabe e aos outros comandantes do exército: "Vão e contem os israelitas desde Berseba até Dã e tragam-me um relatório para que eu saiba quantos são".

[[v13-21-3]]

^<<v13-21-3,3>>^ Joabe, porém, respondeu: "Que o Senhor multiplique o povo dele por cem. Ó rei, meu senhor, não são, porventura, todos eles súditos do meu senhor? Por que o meu senhor deseja fazer isso? Por que deveria trazer culpa sobre Israel? "

[[v13-21-4]]

^<<v13-21-4,4>>^ Mas a palavra do rei prevaleceu, de modo que Joabe partiu, percorreu todo o Israel e então voltou a Jerusalém.

[[v13-21-5]]

^<<v13-21-5,5>>^ Joabe apresentou a Davi o relatório com o número dos homens de combate: Em todo o Israel havia um milhão e cem mil homens habilitados para o serviço militar, sendo quatrocentos e setenta mil de Judá.

[[v13-21-6]]

^<<v13-21-6,6>>^ Mas Joabe não incluiu as tribos de Levi e de Benjamim na contagem, pois a ordem do rei lhe parecera absurda.

[[v13-21-7]]

^<<v13-21-7,7>>^ Essa ordem foi reprovada por Deus, e por isso ele puniu Israel.

[[v13-21-8]]

^<<v13-21-8,8>>^ Então Davi disse a Deus: "Pequei gravemente com o que fiz. Agora eu te imploro que perdoes o pecado do teu servo, porque cometi uma grande loucura! "

[[v13-21-9]]

^<<v13-21-9,9>>^ O Senhor disse a Gade, o vidente de Davi:

[[v13-21-10]]

^<<v13-21-10,10>>^ "Vá dizer a Davi: ‘Assim diz o Senhor: Estou lhe dando três opções. Escolha uma delas, e eu a executarei contra você’ ".

[[v13-21-11]]

^<<v13-21-11,11>>^ Então Gade foi a Davi e lhe disse: "Assim diz o Senhor: ‘Escolha:

[[v13-21-12]]

^<<v13-21-12,12>>^ três anos de fome, três meses fugindo de seus adversários, perseguido pela espada deles, ou três dias da espada do Senhor, isto é, três dias de praga, com o anjo do Senhor assolando todas as regiões de Israel’. Decida agora como devo responder àquele que me enviou".

[[v13-21-13]]

^<<v13-21-13,13>>^ Davi respondeu: "É grande a minha angustia! Prefiro cair nas mãos do Senhor, pois é grande a sua misericórdia, e não nas mãos dos homens".

[[v13-21-14]]

^<<v13-21-14,14>>^ Então o Senhor enviou uma praga sobre Israel, e setenta mil homens de Israel morreram.

[[v13-21-15]]

^<<v13-21-15,15>>^ E Deus enviou um anjo para destruir Jerusalém. Mas, quando o anjo ia fazê-lo, o Senhor olhou e arrependeu-se de trazer a catástrofe, e ele disse ao anjo destruidor: "Pare! Já basta! " Naquele momento o anjo do Senhor estava perto da eira de Araúna, o jebuseu.

[[v13-21-16]]

^<<v13-21-16,16>>^ Davi olhou para cima e viu o anjo do Senhor entre o céu e a terra, com uma espada na mão erguida sobre Jerusalém. Então Davi e as autoridades de Israel, vestidos de luto, prostraram-se, rosto em terra.

[[v13-21-17]]

^<<v13-21-17,17>>^ Davi disse a Deus: "Não fui eu que ordenei contar o povo? Fui eu que pequei e fiz o mal. Estes não passam de ovelhas. O que eles fizeram? Ó Senhor meu Deus, que o teu castigo caia sobre mim e sobre a minha família, mas não sobre o teu povo! "

[[v13-21-18]]

^<<v13-21-18,18>>^ Então o anjo do Senhor mandou Gade dizer a Davi que construísse um altar na eira de Araúna, o jebuseu.

[[v13-21-19]]

^<<v13-21-19,19>>^ Davi foi para lá, em obediência à palavra que Gade havia falado em nome do Senhor.

[[v13-21-20]]

^<<v13-21-20,20>>^ Araúna estava debulhando o trigo; virando-se, viu o anjo, e ele e seus quatro filhos que estavam com ele se esconderam.

[[v13-21-21]]

^<<v13-21-21,21>>^ Nisso chegou Davi e, quando Araúna o viu, saiu da eira e prostrou-se diante de Davi, rosto em terra.

[[v13-21-22]]

^<<v13-21-22,22>>^ E Davi lhe pediu: "Ceda-me o terreno da sua eira para eu construir um altar em honra do Senhor, para que cesse a praga sobre o povo. Venda-me o terreno pelo preço justo".

[[v13-21-23]]

^<<v13-21-23,23>>^ Mas Araúna disse a Davi: "Considera-o teu! Que o meu rei e senhor faça dele o que desejar. Eu darei os bois para os holocaustos, o debulhador para servir de lenha, e o trigo para a oferta de cereal. Tudo isso eu dou a ti".

[[v13-21-24]]

^<<v13-21-24,24>>^ O rei Davi, porém, respondeu a Araúna: "Não! Faço questão de pagar o preço justo. Não darei ao Senhor aquilo que pertence a você, nem oferecerei um holocausto que não me custe nada".

[[v13-21-25]]

^<<v13-21-25,25>>^ Então Davi pagou a Araúna sete quilos e duzentos gramas de ouro pelo terreno.

[[v13-21-26]]

^<<v13-21-26,26>>^ E Davi edificou ali um altar ao Senhor e ofereceu holocaustos e sacrifícios de comunhão. Davi invocou o Senhor, e o Senhor lhe respondeu com fogo que veio do céu sobre o altar de holocaustos.

[[v13-21-27]]

^<<v13-21-27,27>>^ E o Senhor ordenou ao anjo que pusesse a espada na bainha.

[[v13-21-28]]

^<<v13-21-28,28>>^ Nessa ocasião viu Davi que o Senhor lhe havia respondido na eira de Araúna, o jebuseu, e passou a oferecer sacrifícios ali.

[[v13-21-29]]

^<<v13-21-29,29>>^ Naquela época, o tabernáculo do Senhor que Moisés fizera no deserto, e o altar de holocaustos, estavam em Gibeom.

[[v13-21-30]]

^<<v13-21-30,30>>^ Mas Davi não podia consultar a Deus lá, pois tinha medo da espada do anjo do Senhor.

'''

xref:013-1-cronicas/013-1-cronicas-020.adoc#v13-20-0[&#60; Capítulo Anterior] | <<v13-21-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-022.adoc#v13-22-0[Próximo Capítulo &#62;]