include::./index.adoc[]

[[v13-26-0]]
=== 1 Crônicas, 26
// nvi ?, NVI - Nova Versão Internacional

[[v13-26-1]]

^<<v13-26-1,1>>^ Esta é a relação dos grupos dos porteiros: Dos coreítas, Meselemias, filho de Coré, da família de Asafe.

[[v13-26-2]]

^<<v13-26-2,2>>^ Foram estes os filhos de Meselemias: Zacarias, o primeiro, Jediael, o segundo, Zebadias, o terceiro, Jatniel, o quarto,

[[v13-26-3]]

^<<v13-26-3,3>>^ Elão, o quinto, Joanã, o sexto, e Elioenai, o sétimo.

[[v13-26-4]]

^<<v13-26-4,4>>^ Foram estes os filhos de Obede-Edom: Semaías, o primeiro, Jeozabade, o segundo, Joá, o terceiro, Sacar, o quarto, Natanael, o quinto,

[[v13-26-5]]

^<<v13-26-5,5>>^ Amiel, o sexto, Issacar, o sétimo, e Peuletai, o oitavo. Pois Deus havia abençoado Obede-Edom.

[[v13-26-6]]

^<<v13-26-6,6>>^ Seu filho Semaías também teve filhos, que foram líderes na família do seu pai, pois eram homens capazes.

[[v13-26-7]]

^<<v13-26-7,7>>^ Foram estes os filhos de Semaías: Otni, Rafael, Obede e Elzabade. Os parentes dele, Eliú e Semaquias, também foram homens capazes.

[[v13-26-8]]

^<<v13-26-8,8>>^ Todos esses foram descendentes de Obede-Edom; eles e os seus filhos e parentes eram capazes e aptos para a obra. Eram ao todo 62 descendentes de Obede-Edom.

[[v13-26-9]]

^<<v13-26-9,9>>^ Meselemias teve 18 filhos e parentes chegados, todos eles homens capazes.

[[v13-26-10]]

^<<v13-26-10,10>>^ Foram estes os filhos de Hosa, o merarita: Sinri, que foi nomeado chefe por seu pai, mesmo não sendo o mais velho,

[[v13-26-11]]

^<<v13-26-11,11>>^ Hilquias, o segundo, Tebalias, o terceiro, e Zacarias, o quarto. Os filhos e parentes de Hosa foram 13 ao todo.

[[v13-26-12]]

^<<v13-26-12,12>>^ Essas divisões dos porteiros, feitas pelos chefes deles; eles cumpriam tarefas no serviço do templo do Senhor, assim como seus parentes.

[[v13-26-13]]

^<<v13-26-13,13>>^ Tiraram sortes entre as famílias, incluindo jovens e velhos, para que cuidassem de cada porta.

[[v13-26-14]]

^<<v13-26-14,14>>^ E a porta leste coube a Selemias. Então tiraram sortes para seu filho Zacarias, sábio conselheiro, e a porta norte foi sorteada para ele.

[[v13-26-15]]

^<<v13-26-15,15>>^ A sorte da porta sul saiu para Obede-Edom, e a do depósito, para seus filhos.

[[v13-26-16]]

^<<v13-26-16,16>>^ A sorte da porta oeste e da porta Salequete, na rua de cima, saíram para Supim e Hosa. Os guardas ficavam um ao lado do outro:

[[v13-26-17]]

^<<v13-26-17,17>>^ Havia seis levitas por dia no leste, quatro no norte, quatro no sul e dois de cada vez no depósito.

[[v13-26-18]]

^<<v13-26-18,18>>^ Quanto ao pátio a oeste, havia quatro na rua e dois no próprio pátio.

[[v13-26-19]]

^<<v13-26-19,19>>^ Foram essas as divisões dos porteiros, descendentes de Coré e Merari.

[[v13-26-20]]

^<<v13-26-20,20>>^ Outros dos seus irmãos levitas estavam encarregados dos depósitos dos tesouros do templo de Deus e do depósito das dádivas sagradas.

[[v13-26-21]]

^<<v13-26-21,21>>^ Os gersonitas, descendentes de Ladã, que eram chefes de famílias pertencentes a Ladã, foram Jeieli

[[v13-26-22]]

^<<v13-26-22,22>>^ e seus filhos Zetã e seu irmão Joel. Estavam encarregados da tesouraria do templo do Senhor.

[[v13-26-23]]

^<<v13-26-23,23>>^ Dos filhos de Anrão, de Isar, de Hebrom e de Uziel:

[[v13-26-24]]

^<<v13-26-24,24>>^ Sebuel, um descendente de Gérson, filho de Moisés, era o oficial encarregado dos depósitos dos tesouros.

[[v13-26-25]]

^<<v13-26-25,25>>^ Seus parentes por parte de Eliézer foram seu filho Reabias, que foi o pai de Jesaías, o avô de Jorão, o bisavô de Zicri, o tataravô de Selomote.

[[v13-26-26]]

^<<v13-26-26,26>>^ Selomote e seus parentes estavam encarregados de todos os tesouros consagrados pelo rei Davi, pelos chefes de famílias que eram os comandantes de mil e de cem, e pelos outros líderes do exército.

[[v13-26-27]]

^<<v13-26-27,27>>^ Eles consagravam parte dos despojos tomados em combate para a manutenção do templo do Senhor.

[[v13-26-28]]

^<<v13-26-28,28>>^ E todas as dádivas consagradas pelo vidente Samuel e por Saul, filho de Quis, por Abner, filho de Ner, e por Joabe, filho de Zeruia, e todas as demais dádivas sagradas estavam sob os cuidados de Selomote e seus parentes.

[[v13-26-29]]

^<<v13-26-29,29>>^ Dos filhos de Isar, Quenanias e seus filhos ficaram responsáveis pelos negócios públicos de Israel, atuando como oficiais e juízes.

[[v13-26-30]]

^<<v13-26-30,30>>^ Dos filhos de Hebrom, Hasabias e seus parentes, que ficaram responsáveis em Israel, a oeste do Jordão, por todo o trabalho do Senhor e pelo serviço do rei; ao todo eram mil e setecentos homens capazes.

[[v13-26-31]]

^<<v13-26-31,31>>^ De acordo com os registros genealógicos das famílias hebronitas, Jerias foi o chefe delas. No ano quarenta do reinado de Davi fez-se uma busca nos registros, e entre os descendentes de Hebrom encontraram-se homens capazes, em Jazar de Gileade.

[[v13-26-32]]

^<<v13-26-32,32>>^ Jerias tinha dois mil e setecentos parentes, homens capazes e chefes de famílias, que o rei Davi encarregou de todas as questões pertinentes a Deus e aos negócios do rei nas tribos de Rúben e de Gade, e da metade da tribo de Manassés.

'''

xref:013-1-cronicas/013-1-cronicas-025.adoc#v13-25-0[&#60; Capítulo Anterior] | <<v13-26-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-027.adoc#v13-27-0[Próximo Capítulo &#62;]