include::./index.adoc[]

[[v13-14-0]]
=== 1 Crônicas, 14
// nvi ?, NVI - Nova Versão Internacional

[[v13-14-1]]

^<<v13-14-1,1>>^ Hirão, rei de Tiro, enviou a Davi uma delegação, que lhe trouxe toras de cedro, e também pedreiros e carpinteiros, para lhe construírem um palácio.

[[v13-14-2]]

^<<v13-14-2,2>>^ Então Davi teve certeza de que o Senhor o confirmara como rei de Israel e que seu reino estava prosperando por amor de seu povo Israel.

[[v13-14-3]]

^<<v13-14-3,3>>^ Em Jerusalém Davi tomou para si mais mulheres e gerou mais filhos e filhas.

[[v13-14-4]]

^<<v13-14-4,4>>^ Estes são os nomes dos que lhe nasceram ali: Samua, Sobabe, Natã, Salomão,

[[v13-14-5]]

^<<v13-14-5,5>>^ Ibar, Elisua, Elpelete,

[[v13-14-6]]

^<<v13-14-6,6>>^ Nogá, Nefegue, Jafia,

[[v13-14-7]]

^<<v13-14-7,7>>^ Elisama, Beeliada e Elifelete.

[[v13-14-8]]

^<<v13-14-8,8>>^ Quando os filisteus ficaram sabendo que Davi tinha sido ungido rei de todo o Israel, foram com todo o exército prendê-lo, mas Davi soube disso e saiu para enfrentá-los.

[[v13-14-9]]

^<<v13-14-9,9>>^ Tendo os filisteus invadido o vale de Refaim,

[[v13-14-10]]

^<<v13-14-10,10>>^ Davi perguntou a Deus: "Devo atacar os filisteus? Tu os entregarás nas minhas mãos? " O Senhor lhe respondeu: "Vá, eu os entregarei nas suas mãos".

[[v13-14-11]]

^<<v13-14-11,11>>^ Então Davi e seus soldados foram a Baal-Perazim, e Davi os derrotou e disse: "Assim como as águas de uma enchente causam destruição, pelas minhas mãos Deus destruiu os meus inimigos". Então, aquele lugar passou a ser chamado Baal-Perazim.

[[v13-14-12]]

^<<v13-14-12,12>>^ Como os filisteus haviam abandonado os seus ídolos ali, Davi ordenou que fossem queimados.

[[v13-14-13]]

^<<v13-14-13,13>>^ Os filisteus voltaram a atacar o vale;

[[v13-14-14]]

^<<v13-14-14,14>>^ então Davi consultou Deus de novo, que lhe respondeu: "Não ataque pela frente, mas dê a volta por trás deles e ataque-os em frente das amoreiras.

[[v13-14-15]]

^<<v13-14-15,15>>^ Assim que você ouvir um som de passos por cima das amoreiras, saia para o combate, pois este é o sinal de que Deus saiu à sua frente para ferir o exército filisteu".

[[v13-14-16]]

^<<v13-14-16,16>>^ E Davi fez como Deus lhe tinha ordenado, e eles derrotaram o exército filisteu, por todo o caminho, desde Gibeom até Gezer.

[[v13-14-17]]

^<<v13-14-17,17>>^ Assim, a fama de Davi espalhou-se por todas as terras, e o Senhor fez com que todas as nações o temessem.

'''

xref:013-1-cronicas/013-1-cronicas-013.adoc#v13-13-0[&#60; Capítulo Anterior] | <<v13-14-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-015.adoc#v13-15-0[Próximo Capítulo &#62;]