include::./index.adoc[]

[[v13-22-0]]
=== 1 Crônicas, 22
// nvi ?, NVI - Nova Versão Internacional

[[v13-22-1]]

^<<v13-22-1,1>>^ Então disse Davi: "Este é o lugar para o templo de Deus, o Senhor, e do altar de holocaustos para Israel".

[[v13-22-2]]

^<<v13-22-2,2>>^ Então Davi deu ordens para que se reunissem os estrangeiros que viviam em Israel, e dentre eles designou cortadores de pedra para prepararem pedras lavradas para a construção do templo de Deus.

[[v13-22-3]]

^<<v13-22-3,3>>^ Ele providenciou grande quantidade de ferro para a fabricação de pregos e dobradiças para as portas, e mais bronze do que se podia pesar.

[[v13-22-4]]

^<<v13-22-4,4>>^ Também providenciou mais toras de cedro do que se podia contar, pois os sidônios e os tírios haviam trazido muito cedro para Davi.

[[v13-22-5]]

^<<v13-22-5,5>>^ Davi pensava: "Meu filho Salomão é jovem e inexperiente, e o templo que será construído para o Senhor deve ser extraordinariamente magnífico, famoso e cheio de esplendor à vista de todas as nações. Por isso deixarei tudo preparado para a construção". Assim, Davi deixou tudo preparado antes de morrer.

[[v13-22-6]]

^<<v13-22-6,6>>^ Davi mandou chamar seu filho Salomão e ordenou que ele construísse um templo para o Senhor, o Deus de Israel,

[[v13-22-7]]

^<<v13-22-7,7>>^ dizendo: "Meu filho, eu tinha no coração o propósito de construir um templo em honra do nome do Senhor, o meu Deus.

[[v13-22-8]]

^<<v13-22-8,8>>^ Mas veio a mim esta palavra do Senhor: ‘Você matou muita gente e empreendeu muitas guerras. Por isso você não construirá um templo em honra do meu nome, pois derramou muito sangue na terra, diante de mim.

[[v13-22-9]]

^<<v13-22-9,9>>^ Mas você terá um filho que será um homem de paz, e eu farei com que ele tenha paz com todos os inimigos ao redor dele. Seu nome será Salomão, e eu darei paz e tranqüilidade a Israel durante o reinado dele.

[[v13-22-10]]

^<<v13-22-10,10>>^ É ele que vai construir um templo em honra do meu nome. Eu serei seu pai e ele será meu filho. E eu firmarei para sempre o trono do reinado dele sobre Israel’.

[[v13-22-11]]

^<<v13-22-11,11>>^ "Agora, meu filho, que o Senhor seja com você, para que você consiga construir o templo do Senhor, o seu Deus, conforme ele disse que você faria.

[[v13-22-12]]

^<<v13-22-12,12>>^ Que o Senhor lhe dê prudência e entendimento para que você obedeça à lei do Senhor, o seu Deus, quando ele o puser como líder de Israel.

[[v13-22-13]]

^<<v13-22-13,13>>^ E você prosperará se for cuidadoso em obedecer aos decretos e às leis que o Senhor deu a Israel por meio de Moisés. Seja forte e corajoso! Não tenha medo nem se desanime!

[[v13-22-14]]

^<<v13-22-14,14>>^ "Com muito esforço providenciei para o templo do Senhor três mil e quinhentas toneladas de ouro, trinta e cinco mil toneladas de prata, e tanto bronze e ferro que nem dá para calcular, além de madeira e pedra. E você ainda poderá aumentar a quantidade desse material.

[[v13-22-15]]

^<<v13-22-15,15>>^ Você tem muitos trabalhadores: cortadores de pedras, pedreiros e carpinteiros, bem como especialistas em todo tipo de trabalho

[[v13-22-16]]

^<<v13-22-16,16>>^ em ouro, prata, bronze e ferro. Agora comece o trabalho, e que o Senhor esteja com você".

[[v13-22-17]]

^<<v13-22-17,17>>^ Então Davi ordenou a todos os líderes de Israel que ajudassem seu filho Salomão.

[[v13-22-18]]

^<<v13-22-18,18>>^ Disse ele: "Certamente o Senhor, o seu Deus, está com vocês, e lhes concedeu paz. Pois ele entregou os habitantes dessa terra em minhas mãos, e ela foi submetida ao Senhor e ao seu povo.

[[v13-22-19]]

^<<v13-22-19,19>>^ Agora consagrem o coração e a alma para buscarem o Senhor, o seu Deus. Comecem a construir o santuário de Deus, o Senhor, para que vocês possam trazer a arca da aliança do Senhor e os utensílios sagrados que pertencem a Deus para dentro do templo que será construído em honra do nome do Senhor".

'''

xref:013-1-cronicas/013-1-cronicas-021.adoc#v13-21-0[&#60; Capítulo Anterior] | <<v13-22-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-023.adoc#v13-23-0[Próximo Capítulo &#62;]