include::./index.adoc[]

[[v13-8-0]]
=== 1 Crônicas, 8
// nvi ?, NVI - Nova Versão Internacional

[[v13-8-1]]

^<<v13-8-1,1>>^ Benjamim gerou Belá, seu filho mais velho; Asbel, seu segundo filho, Aará, o terceiro,

[[v13-8-2]]

^<<v13-8-2,2>>^ Noá, o quarto, e Rafa, o quinto.

[[v13-8-3]]

^<<v13-8-3,3>>^ Estes foram os filhos de Belá: Adar, Gera, pai de Eúde,

[[v13-8-4]]

^<<v13-8-4,4>>^ Abisua, Naamã, Aoá,

[[v13-8-5]]

^<<v13-8-5,5>>^ Gera, Sefufá e Hurão.

[[v13-8-6]]

^<<v13-8-6,6>>^ Estes foram os descendentes de Eúde, chefes das famílias dos habitantes de Geba, que foram deportados para Manaate:

[[v13-8-7]]

^<<v13-8-7,7>>^ Naamã, Aías e Gera. Esse Gera, pai de Uzá e de Aiúde, foi quem os deportou.

[[v13-8-8]]

^<<v13-8-8,8>>^ Depois de ter se divorciado de suas mulheres Husim e Baara, Saaraim teve filhos na terra de Moabe.

[[v13-8-9]]

^<<v13-8-9,9>>^ Com sua mulher Hodes ele gerou Jobabe, Zíbia, Messa, Malcã,

[[v13-8-10]]

^<<v13-8-10,10>>^ Jeús, Saquias e Mirma. Esses foram seus filhos, chefes de famílias.

[[v13-8-11]]

^<<v13-8-11,11>>^ Com Husim ele gerou Abitube e Elpaal.

[[v13-8-12]]

^<<v13-8-12,12>>^ Estes foram os filhos de Elpaal: Héber, Misã, Semede, que fundou Ono e Lode com seus povoados.

[[v13-8-13]]

^<<v13-8-13,13>>^ Berias e Sema foram os chefes das famílias dos habitantes de Aijalom, e foram eles que expulsaram os habitantes de Gate.

[[v13-8-14]]

^<<v13-8-14,14>>^ Aiô, Sasaque, Jeremote,

[[v13-8-15]]

^<<v13-8-15,15>>^ Zebadias, Arade, Éder,

[[v13-8-16]]

^<<v13-8-16,16>>^ Micael, Ispa e Joá foram descendentes de Berias.

[[v13-8-17]]

^<<v13-8-17,17>>^ Zebadias, Mesulão, Hizqui, Héber,

[[v13-8-18]]

^<<v13-8-18,18>>^ Ismerai, Izlias e Jobabe foram descendentes de Elpaal.

[[v13-8-19]]

^<<v13-8-19,19>>^ Jaquim, Zicri, Zabdi,

[[v13-8-20]]

^<<v13-8-20,20>>^ Elienai, Ziletai, Eliel,

[[v13-8-21]]

^<<v13-8-21,21>>^ Adaías, Beraías e Sinrate foram descendentes de Simei.

[[v13-8-22]]

^<<v13-8-22,22>>^ Ispã, Héber, Eliel,

[[v13-8-23]]

^<<v13-8-23,23>>^ Abdom, Zicri, Hanã,

[[v13-8-24]]

^<<v13-8-24,24>>^ Hananias, Elão, Antotias,

[[v13-8-25]]

^<<v13-8-25,25>>^ Ifdéias e Penuel foram descendentes de Sasaque.

[[v13-8-26]]

^<<v13-8-26,26>>^ Sanserai, Searias, Atalias,

[[v13-8-27]]

^<<v13-8-27,27>>^ Jaaresias, Elias e Zicri foram descendentes de Jeroão.

[[v13-8-28]]

^<<v13-8-28,28>>^ Todos esses foram chefes de famílias, líderes conforme alistados em suas genealogias, e moravam em Jerusalém.

[[v13-8-29]]

^<<v13-8-29,29>>^ Jeiel, pai de Gibeom morou na cidade de Gibeom. O nome de sua mulher era Maaca,

[[v13-8-30]]

^<<v13-8-30,30>>^ o de seu filho mais velho, Abdom, e o de seus outros filhos, Zur, Quis, Baal, Ner, Nadabe,

[[v13-8-31]]

^<<v13-8-31,31>>^ Gedor, Aiô, Zequer

[[v13-8-32]]

^<<v13-8-32,32>>^ e Miclote, que gerou Siméia. Eles também moravam perto de seus parentes, em Jerusalém.

[[v13-8-33]]

^<<v13-8-33,33>>^ Ner gerou Quis, que gerou Saul. Saul gerou Jônatas, Malquisua, Abinadabe e Esbaal.

[[v13-8-34]]

^<<v13-8-34,34>>^ O filho de Jônatas foi Meribe-Baal, que gerou Mica.

[[v13-8-35]]

^<<v13-8-35,35>>^ Estes foram os filhos de Mica: Pitom, Meleque, Taréia e Acaz.

[[v13-8-36]]

^<<v13-8-36,36>>^ Acaz gerou Jeoada, Jeoada gerou Alemete, Azmavete e Zinri, e Zinri gerou Mosa.

[[v13-8-37]]

^<<v13-8-37,37>>^ Mosa gerou Bineá, pai de Rafa, que foi o pai de Eleasa, pai de Azel.

[[v13-8-38]]

^<<v13-8-38,38>>^ Azel teve seis filhos chamados Azricão, Bocru, Ismael, Searias, Obadias e Hanã. Todos esses foram filhos de Azel.

[[v13-8-39]]

^<<v13-8-39,39>>^ Estes foram os filhos de Eseque, seu irmão: Ulão, o mais velho, Jeús, o segundo e Elifelete, o terceiro.

[[v13-8-40]]

^<<v13-8-40,40>>^ Os filhos de Ulão eram soldados valentes e bons flecheiros. Tiveram muitos filhos e netos; eram cento e cinqüenta ao todo. Todos esses foram descendentes de Benjamim.

'''

xref:013-1-cronicas/013-1-cronicas-007.adoc#v13-7-0[&#60; Capítulo Anterior] | <<v13-8-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-009.adoc#v13-9-0[Próximo Capítulo &#62;]