include::./index.adoc[]

[[v13-16-0]]
=== 1 Crônicas, 16
// nvi ?, NVI - Nova Versão Internacional

[[v13-16-1]]

^<<v13-16-1,1>>^ Eles trouxeram a arca de Deus e a colocaram na tenda que Davi lhe havia preparado, e ofereceram holocaustos e sacrifícios de comunhão diante de Deus.

[[v13-16-2]]

^<<v13-16-2,2>>^ Após oferecer os holocaustos e os sacrifícios de comunhão, Davi abençoou o povo em nome do Senhor,

[[v13-16-3]]

^<<v13-16-3,3>>^ e deu um pão, um bolo de tâmaras e um bolo de uvas passas a cada homem e a cada mulher israelita.

[[v13-16-4]]

^<<v13-16-4,4>>^ Davi nomeou alguns dos levitas para ministrarem diante da arca do Senhor, fazendo petições, dando graças, e louvando o Senhor, o Deus de Israel.

[[v13-16-5]]

^<<v13-16-5,5>>^ Desses, Asafe era o chefe, Zacarias vinha em seguida, e depois Jeiel, Semiramote, Jeiel, Matitias, Eliabe, Benaia, Obede-Edom e Jeiel. Eles deviam tocar lira e harpa, enquanto Asafe tocava os címbalos.

[[v13-16-6]]

^<<v13-16-6,6>>^ Os sacerdotes Benaia e Jaaziel deviam tocar diariamente as trombetas diante da arca da aliança de Deus.

[[v13-16-7]]

^<<v13-16-7,7>>^ Foi naquele dia que pela primeira vez Davi encarregou a Asafe e seus parentes de louvar ao Senhor com salmos de gratidão:

[[v13-16-8]]

^<<v13-16-8,8>>^ Dêem graças ao Senhor, clamem pelo seu nome, divulguem entre as nações o que ele tem feito.

[[v13-16-9]]

^<<v13-16-9,9>>^ Cantem para ele, louvem-no; contem todos os seus atos maravilhosos.

[[v13-16-10]]

^<<v13-16-10,10>>^ Gloriem-se no seu santo nome; alegrem-se os corações dos que buscam o Senhor.

[[v13-16-11]]

^<<v13-16-11,11>>^ Olhem para o Senhor e para a sua força; busquem sempre a sua face.

[[v13-16-12]]

^<<v13-16-12,12>>^ Lembrem-se das maravilhas que ele fez, dos seus prodígios e das ordenanças que pronunciou,

[[v13-16-13]]

^<<v13-16-13,13>>^ ó descendentes de Israel, seu servo, ó filhos de Jacó, seus escolhidos.

[[v13-16-14]]

^<<v13-16-14,14>>^ Ele é o Senhor, o nosso Deus; seus domínio alcança toda a terra.

[[v13-16-15]]

^<<v13-16-15,15>>^ Para sempre se lembra da sua aliança, da palavra que ordenou para mil gerações,

[[v13-16-16]]

^<<v13-16-16,16>>^ da aliança que fez com Abraão, do juramento que fez a Isaque,

[[v13-16-17]]

^<<v13-16-17,17>>^ que confirmou para Jacó como um decreto, e para Israel como uma aliança eterna, dizendo:

[[v13-16-18]]

^<<v13-16-18,18>>^ "A vocês darei a terra de Canaã, a herança que possuirão".

[[v13-16-19]]

^<<v13-16-19,19>>^ Quando eles ainda eram poucos, muito poucos, e estrangeiros nela,

[[v13-16-20]]

^<<v13-16-20,20>>^ e vagueavam de nação em nação, de um reino a outro,

[[v13-16-21]]

^<<v13-16-21,21>>^ ele não permitiu que ninguém os oprimisse; por causa deles repreendeu reis, ordenando:

[[v13-16-22]]

^<<v13-16-22,22>>^ "Não maltratem os meus ungidos; não façam mal aos meus profetas".

[[v13-16-23]]

^<<v13-16-23,23>>^ Cantem ao Senhor, todas as terras! Proclamem a sua salvação dia após dia!

[[v13-16-24]]

^<<v13-16-24,24>>^ Anunciem a sua glória entre as nações, seus feitos maravilhosos entre todos os povos!

[[v13-16-25]]

^<<v13-16-25,25>>^ Pois o Senhor é grande e muitíssimo digno de louvor; ele deve ser mais temido que todos os deuses.

[[v13-16-26]]

^<<v13-16-26,26>>^ Pois todos os deuses das nações não passam de ídolos, mas o Senhor fez os céus.

[[v13-16-27]]

^<<v13-16-27,27>>^ O esplendor e a majestade estão diante dele; força e alegria na sua habitação.

[[v13-16-28]]

^<<v13-16-28,28>>^ Dêem ao Senhor, ó famílias das nações, dêem ao Senhor glória e força.

[[v13-16-29]]

^<<v13-16-29,29>>^ Dêem ao Senhor a glória devida ao seu nome. Tragam ofertas e venham à sua presença. Adorem o Senhor no esplendor da sua santidade,

[[v13-16-30]]

^<<v13-16-30,30>>^ tremam diante dele, todas as nações! Firmou o mundo, que não se abalará!

[[v13-16-31]]

^<<v13-16-31,31>>^ Que os céus se alegrem e a terra exulte, e diga-se entre as nações: "O Senhor reina! "

[[v13-16-32]]

^<<v13-16-32,32>>^ Ressoe o mar, e tudo o que nele existe; exultem os campos, e tudo o que neles há!

[[v13-16-33]]

^<<v13-16-33,33>>^ Então as árvores da floresta cantarão de alegria, cantarão diante do Senhor, pois ele vem julgar a terra.

[[v13-16-34]]

^<<v13-16-34,34>>^ Rendam graças ao Senhor, pois ele é bom; o seu amor dura para sempre.

[[v13-16-35]]

^<<v13-16-35,35>>^ Clamem: "Salva-nos, ó Deus, nosso Salvador! Reúne-nos e livra-nos das nações, para que demos graças ao teu santo nome e façamos do teu louvor a nossa glória".

[[v13-16-36]]

^<<v13-16-36,36>>^ Bendito seja o Senhor, o Deus de Israel, de eternidade a eternidade. Então todo o povo exclamou: "Amém! " e "Louvado seja o Senhor! "

[[v13-16-37]]

^<<v13-16-37,37>>^ Então Davi deixou Asafe e seus parentes diante da arca da aliança do Senhor para ali ministrarem regularmente, de acordo com as prescrições para cada dia.

[[v13-16-38]]

^<<v13-16-38,38>>^ Também deixou Obede-Edom e seus sessenta e oito parentes para ministrarem com eles. Obede-Edom, filho de Jedutum, e também Hosa foram porteiros.

[[v13-16-39]]

^<<v13-16-39,39>>^ Davi deixou o sacerdote Zadoque e seus parentes sacerdotes diante do tabernáculo do Senhor em Gibeom

[[v13-16-40]]

^<<v13-16-40,40>>^ para regularmente, de manhã e à tarde, apresentarem holocaustos no altar de holocaustos, de acordo com tudo o que está escrito na Lei do Senhor, que ele deu a Israel.

[[v13-16-41]]

^<<v13-16-41,41>>^ Com eles estavam Hemã e Jedutum e os outros designados para darem graças ao Senhor, exclamando: "O seu amor dura para sempre".

[[v13-16-42]]

^<<v13-16-42,42>>^ Hemã e Jedutum eram responsáveis pelas trombetas, pelos címbalos e pelos outros instrumentos musicais para o culto. Os filhos de Jedutum foram designados como porteiros.

[[v13-16-43]]

^<<v13-16-43,43>>^ Então todo o povo partiu, cada um para a sua casa, e Davi voltou para casa para abençoar sua família.

'''

xref:013-1-cronicas/013-1-cronicas-015.adoc#v13-15-0[&#60; Capítulo Anterior] | <<v13-16-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-017.adoc#v13-17-0[Próximo Capítulo &#62;]