include::./index.adoc[]

[[v13-19-0]]
=== 1 Crônicas, 19
// nvi ?, NVI - Nova Versão Internacional

[[v13-19-1]]

^<<v13-19-1,1>>^ Algum tempo depois, Naás, rei dos amonitas, morreu, e seu filho foi o seu sucessor.

[[v13-19-2]]

^<<v13-19-2,2>>^ Davi pensou: "Serei bondoso com Hanum, filho de Naás, porque seu pai foi bondoso comigo". Então Davi enviou uma delegação para transmitir a Hanum seu pesar pela morte do pai. Mas, quando os mensageiros de Davi chegaram à terra dos amonitas para expressar condolências a Hanum,

[[v13-19-3]]

^<<v13-19-3,3>>^ os líderes amonitas lhe disseram: "Achas que Davi está honrando teu pai ao enviar mensageiros para expressar condolências? Não é nada disso! Davi os enviou como espiões para examinar o país e destruí-lo".

[[v13-19-4]]

^<<v13-19-4,4>>^ Então Hanum prendeu os mensageiros de Davi, rapou-lhes a barba, cortou metade de suas roupas até as nádegas, e os mandou embora.

[[v13-19-5]]

^<<v13-19-5,5>>^ Quando Davi soube disso, enviou mensageiros ao encontro deles, pois haviam sido profundamente humilhados, e lhes mandou dizer: "Fiquem em Jericó até que a barba cresça, e então voltem para casa".

[[v13-19-6]]

^<<v13-19-6,6>>^ Vendo Hanum e os amonitas que tinham atraído sobre si o ódio de Davi, alugaram da Mesopotâmia, de Arã Maaca e de Zobá, carros de guerra e condutores de carros, por trinta e cinco toneladas de prata.

[[v13-19-7]]

^<<v13-19-7,7>>^ Alugaram trinta e dois mil carros e seus condutores, e contrataram o rei de Maaca com suas tropas, o qual veio e acampou perto de Medeba, e os amonitas foram convocados de suas cidades e partiram para a batalha.

[[v13-19-8]]

^<<v13-19-8,8>>^ Ao saber disso, Davi ordenou a Joabe que marchasse com todo o exército.

[[v13-19-9]]

^<<v13-19-9,9>>^ Os amonitas saíram e se puseram em posição de combate na entrada da cidade, e os reis que tinham vindo posicionaram-se em campo aberto.

[[v13-19-10]]

^<<v13-19-10,10>>^ Vendo Joabe que estava cercado pelas linhas de combate, escolheu alguns dos melhores soldados de Israel e os posicionou contra os arameus.

[[v13-19-11]]

^<<v13-19-11,11>>^ Pôs o restante dos homens sob o comando de seu irmão Abisai e os posicionou contra os amonitas.

[[v13-19-12]]

^<<v13-19-12,12>>^ E Joabe disse a Abisai: "Se os arameus forem fortes demais para mim, venha me ajudar; mas, se os amonitas forem fortes demais para você, eu irei ajudá-lo.

[[v13-19-13]]

^<<v13-19-13,13>>^ Seja forte e lutemos com bravura pelo nosso povo e pelas cidades do nosso Deus. E que o Senhor faça o que for de sua vontade".

[[v13-19-14]]

^<<v13-19-14,14>>^ Então Joabe e seus soldados avançaram contra os arameus, que fugiram dele.

[[v13-19-15]]

^<<v13-19-15,15>>^ Quando os amonitas viram que os arameus estavam fugindo de Joabe, também fugiram de seu irmão Abisai e entraram na cidade. Assim, Joabe voltou para Jerusalém.

[[v13-19-16]]

^<<v13-19-16,16>>^ Ao perceberem os arameus que haviam sido derrotados por Israel, enviaram mensageiros para trazer arameus que viviam do outro lado do Eufrates, e Sofaque, o comandante do exército de Hadadezer, veio à frente deles.

[[v13-19-17]]

^<<v13-19-17,17>>^ Informado disso, Davi reuniu todo o Israel e atravessou o Jordão; avançou contra eles e formou linhas de combate defronte deles. Mas, começado o combate,

[[v13-19-18]]

^<<v13-19-18,18>>^ eles fugiram de diante de Israel, e Davi matou sete mil dos seus condutores de carros de guerra e quarenta mil dos seus soldados de infantaria. Também matou Sofaque, o comandante do exército deles.

[[v13-19-19]]

^<<v13-19-19,19>>^ Quando os vassalos de Hadadezer viram que tinham sido derrotados por Israel, fizeram a paz com Davi e se sujeitaram a ele. E os arameus não quiseram mais ajudar os amonitas.

'''

xref:013-1-cronicas/013-1-cronicas-018.adoc#v13-18-0[&#60; Capítulo Anterior] | <<v13-19-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-020.adoc#v13-20-0[Próximo Capítulo &#62;]