include::./index.adoc[]

[[v13-9-0]]
=== 1 Crônicas, 9
// nvi ?, NVI - Nova Versão Internacional

[[v13-9-1]]

^<<v13-9-1,1>>^ Todos os israelitas foram alistados nas genealogias dos registros históricos dos reis de Israel. O povo de Judá foi levado prisioneiro para a Babilônia por sua infidelidade.

[[v13-9-2]]

^<<v13-9-2,2>>^ Os primeiros a voltarem às suas propriedades e às suas cidades foram algumas pessoas do povo e alguns sacerdotes, levitas e servidores do templo.

[[v13-9-3]]

^<<v13-9-3,3>>^ Os de Judá, de Benjamim e de Efraim e Manassés que se instalaram em Jerusalém foram:

[[v13-9-4]]

^<<v13-9-4,4>>^ Utai, filho de Amiúde, neto de Onri, bisneto de Inri e trineto de Bani, um descendente de Perez, filho de Judá.

[[v13-9-5]]

^<<v13-9-5,5>>^ Dos descendentes de Selá: O primogênito Asaías com seus filhos.

[[v13-9-6]]

^<<v13-9-6,6>>^ Dos descendentes de Zerá: Jeuel. Os de Judá chegaram a 690.

[[v13-9-7]]

^<<v13-9-7,7>>^ Dos benjamitas: Salu, filho de Mesulão, neto de Hodavias e bisneto de Hassenua;

[[v13-9-8]]

^<<v13-9-8,8>>^ Ibnéias, filho de Jeroão; Elá, filho de Uzi, filho de Micri; e Mesulão, filho de Sefatias, filho de Reuel, filho de Ibnias.

[[v13-9-9]]

^<<v13-9-9,9>>^ Da tribo de Benjamim, relacionados em sua genealogia, eram 956. Todos esses homens eram chefes de suas famílias.

[[v13-9-10]]

^<<v13-9-10,10>>^ Dos sacerdotes: Jedaías, Jeoiaribe, Jaquim;

[[v13-9-11]]

^<<v13-9-11,11>>^ Azarias, filho de Hilquias, neto de Mesulão, bisneto de Zadoque, trineto de Meraiote e tetraneto de Aitube, o líder encarregado do templo de Deus;

[[v13-9-12]]

^<<v13-9-12,12>>^ Adaías, filho de Jeroão, neto de Pasur e bisneto de Malquias; e Masai, filho de Adiel, neto de Jazera, bisneto de Mesulão, trineto de Mesilemite e tetraneto de Imer.

[[v13-9-13]]

^<<v13-9-13,13>>^ O número de sacerdotes que eram chefes de famílias era 1. 760. Eram homens capazes, e sua responsabilidade era ministrar no templo de Deus.

[[v13-9-14]]

^<<v13-9-14,14>>^ Dos levitas: Semaías, filho de Hassube, neto de Azricão e bisneto de Hasabias, um merarita;

[[v13-9-15]]

^<<v13-9-15,15>>^ Baquebacar, Heres, Galal e Matanias, filho de Mica, neto de Zicri e bisneto de Asafe;

[[v13-9-16]]

^<<v13-9-16,16>>^ Obadias, filho de Semaías, neto de Galal e bisneto de Jedutum; e Berequias, filho de Asa e neto de Elcana, que vivia nos povoados dos netofatitas.

[[v13-9-17]]

^<<v13-9-17,17>>^ Os guardas das portas eram: Salum, o chefe, Acube, Talmom, Aimã e os irmãos deles, sendo até hoje

[[v13-9-18]]

^<<v13-9-18,18>>^ os guardas da porta do Rei, a leste. Salum era o chefe. Esses eram os guardas das portas que pertenciam ao acampamento dos levitas.

[[v13-9-19]]

^<<v13-9-19,19>>^ Salum, filho de Coré, neto de Ebiasafe e bisneto de Corá, e seus parentes, os coreítas, guardas das portas, responsáveis por guardar as entradas da Tenda, como os seus antepassados tinham sido responsáveis por guardar a entrada da habitação do Senhor.

[[v13-9-20]]

^<<v13-9-20,20>>^ Naquela época, Finéias, filho de Eleazar, estivera encarregado dos guardas das portas, e o Senhor estava com ele.

[[v13-9-21]]

^<<v13-9-21,21>>^ Zacarias, filho de Meselemias, era o guarda das portas da entrada da Tenda do Encontro.

[[v13-9-22]]

^<<v13-9-22,22>>^ A soma total dos escolhidos para serem guardas das portas, registrados nas genealogias dos seus povoados, era de 212. Eles haviam sido designados para esses postos de confiança por Davi e pelo vidente Samuel.

[[v13-9-23]]

^<<v13-9-23,23>>^ Eles e os seus descendentes foram encarregados de vigiar as portas do templo do Senhor, o templo chamado Tenda.

[[v13-9-24]]

^<<v13-9-24,24>>^ Os guardas vigiavam as portas nos quatro lados: norte, sul, leste e oeste.

[[v13-9-25]]

^<<v13-9-25,25>>^ Seus parentes, residentes em seus povoados, tinham que vir de tempos em tempos e trabalhar com eles por períodos de sete dias.

[[v13-9-26]]

^<<v13-9-26,26>>^ Mas os quatro principais guardas das portas, que eram levitas, receberam a responsabilidade de tomar conta das salas e da tesouraria do templo de Deus.

[[v13-9-27]]

^<<v13-9-27,27>>^ Eles passavam a noite perto do templo de Deus, pois tinham o dever de vigiá-la e de abrir as portas todas as manhãs.

[[v13-9-28]]

^<<v13-9-28,28>>^ Alguns levitas estavam encarregados dos utensílios utilizados no culto no templo; eles os contavam quando eram retirados e quando eram devolvidos.

[[v13-9-29]]

^<<v13-9-29,29>>^ Outros eram responsáveis pelos móveis e por todos os demais utensílios do santuário, bem como pela farinha, pelo vinho, pelo óleo, pelo incenso e pelas especiarias.

[[v13-9-30]]

^<<v13-9-30,30>>^ E ainda outros cuidavam da manipulação das especiarias.

[[v13-9-31]]

^<<v13-9-31,31>>^ Um levita chamado Matitias, filho mais velho do coreíta Salum, tinha a responsabilidade de assar os pães para as ofertas.

[[v13-9-32]]

^<<v13-9-32,32>>^ E dentre os coatitas, seus irmãos, alguns estavam encarregados de preparar os pães que são postos sobre a mesa todo sábado.

[[v13-9-33]]

^<<v13-9-33,33>>^ Os cantores, chefes de famílias levitas, permaneciam nas salas do templo e estavam isentos de outros deveres, pois dia e noite se dedicavam à sua própria tarefa.

[[v13-9-34]]

^<<v13-9-34,34>>^ Todos esses eram chefes de famílias levitas, alistados como líderes em suas genealogias, e moravam em Jerusalém.

[[v13-9-35]]

^<<v13-9-35,35>>^ Jeiel, pai de Gibeom, morava em Gibeom. O nome de sua mulher era Maaca,

[[v13-9-36]]

^<<v13-9-36,36>>^ e o de seu filho mais velho, Abdom. Depois nasceram Zur, Quis, Baal, Ner, Nadabe,

[[v13-9-37]]

^<<v13-9-37,37>>^ Gedor, Aiô, Zacarias e Miclote.

[[v13-9-38]]

^<<v13-9-38,38>>^ Miclote gerou Siméia. Eles também moravam perto de seus parentes em Jerusalém.

[[v13-9-39]]

^<<v13-9-39,39>>^ Ner gerou Quis, Quis gerou Saul, Saul gerou Jônatas, Malquisua, Abinadabe e Esbaal.

[[v13-9-40]]

^<<v13-9-40,40>>^ Este foi o filho de Jônatas: Meribe-Baal, que gerou Mica.

[[v13-9-41]]

^<<v13-9-41,41>>^ Estes foram os filhos de Mica: Pitom, Meleque, Taréia e Acaz.

[[v13-9-42]]

^<<v13-9-42,42>>^ Acaz gerou Jadá, Jadá gerou Alemete, Azmavete e Zinri, e Zinri gerou Mosa.

[[v13-9-43]]

^<<v13-9-43,43>>^ Mosa gerou Bineá, cujo filho foi Refaías, o filho deste foi Eleasa, pai de Azel.

[[v13-9-44]]

^<<v13-9-44,44>>^ Azel teve seis filhos, e os nomes deles foram: Azricão, Bocru, Ismael, Searias, Obadias e Hanã. Esses foram os filhos de Azel.

'''

xref:013-1-cronicas/013-1-cronicas-008.adoc#v13-8-0[&#60; Capítulo Anterior] | <<v13-9-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-010.adoc#v13-10-0[Próximo Capítulo &#62;]