include::./index.adoc[]

[[v13-20-0]]
=== 1 Crônicas, 20
// nvi ?, NVI - Nova Versão Internacional

[[v13-20-1]]

^<<v13-20-1,1>>^ Na primavera seguinte, na época em que os reis saem à guerra, Joabe conduziu o seu exército até a terra dos amonitas e a arrasou. Enquanto Davi ainda estava em Jerusalém, Joabe cercou Rabá, a capital, atacou-a e deixou-a em ruínas.

[[v13-20-2]]

^<<v13-20-2,2>>^ Davi tirou a coroa da cabeça de Milcon, uma coroa de ouro de trinta e cinco quilos, ornamentada com pedras preciosas. E ela foi colocada na cabeça de Davi. Ele levou uma grande quantidade de bens da cidade,

[[v13-20-3]]

^<<v13-20-3,3>>^ e levou também os seus habitantes, designando-lhes trabalhos com serras, picaretas de ferro e machados. Davi fez assim com todas as cidades amonitas. Depois voltou com todo seu exército para Jerusalém.

[[v13-20-4]]

^<<v13-20-4,4>>^ E houve depois disso uma guerra com os filisteus, em Gezer. Naquela época, Sibecai, de Husate, matou Sipai, um dos descendentes dos refains, e os filisteus foram subjugados.

[[v13-20-5]]

^<<v13-20-5,5>>^ Noutra batalha contra os filisteus, Elanã, filho de Jair, matou Lami, irmão de Golias, de Gate, que possuía uma lança cuja haste parecia uma lançadeira de tecelão.

[[v13-20-6]]

^<<v13-20-6,6>>^ Noutra batalha, em Gate, havia um homem de grande estatura e que tinha seis dedos em cada mão e seis dedos em cada pé; vinte e quatro dedos ao todo. Ele também era descendente de Rafa,

[[v13-20-7]]

^<<v13-20-7,7>>^ e ele desafiou Israel, mas Jônatas, filho de Siméia, irmão de Davi, o matou.

[[v13-20-8]]

^<<v13-20-8,8>>^ Esses eram descendentes de Rafa, em Gate, e foram mortos por Davi e seus soldados.

'''

xref:013-1-cronicas/013-1-cronicas-019.adoc#v13-19-0[&#60; Capítulo Anterior] | <<v13-20-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-021.adoc#v13-21-0[Próximo Capítulo &#62;]