include::./index.adoc[]

[[v13-3-0]]
=== 1 Crônicas, 3
// nvi ?, NVI - Nova Versão Internacional

[[v13-3-1]]

^<<v13-3-1,1>>^ Estes foram os filhos de Davi nascidos em Hebrom: O seu filho mais velho era Amnom, filho de Ainoã de Jezreel; o segundo, Daniel, de Abigail, de Carmelo;

[[v13-3-2]]

^<<v13-3-2,2>>^ o terceiro, Absalão, de Maaca, filha de Talmai, rei de Gesur; o quarto, Adonias, de Hagite;

[[v13-3-3]]

^<<v13-3-3,3>>^ o quinto, Sefatias, de Abital; e o sexto, Itreão, de sua mulher Eglá.

[[v13-3-4]]

^<<v13-3-4,4>>^ São esses os seis filhos de Davi que nasceram em Hebrom, onde ele reinou sete anos e seis meses. E, em Jerusalém,

[[v13-3-5]]

^<<v13-3-5,5>>^ onde Davi reinou trinta e três anos, nasceram-lhe os seguintes filhos: Siméia, Sobabe, Natã e Salomão, os quatro filhos que ele teve com Bate-Seba, filha de Amiel.

[[v13-3-6]]

^<<v13-3-6,6>>^ Davi teve ainda mais nove filhos: Ibar, Elisua, Elpalete,

[[v13-3-7]]

^<<v13-3-7,7>>^ Nogá, Nefegue, Jafia,

[[v13-3-8]]

^<<v13-3-8,8>>^ Elisama, Eliada e Elifelete.

[[v13-3-9]]

^<<v13-3-9,9>>^ Todos esses foram filhos de Davi, sem contar os filhos que teve com suas concubinas, e sua filha Tamar, irmã deles.

[[v13-3-10]]

^<<v13-3-10,10>>^ O filho de Salomão foi Roboão; o filho de Roboão foi Abias; o filho de Abias, Asa; o filho de Asa, Josafá;

[[v13-3-11]]

^<<v13-3-11,11>>^ o filho de Josafá, Jeorão; o filho de Jeorão, Acazias; o filho de Acazias, Joás;

[[v13-3-12]]

^<<v13-3-12,12>>^ o filho de Joás, Amazias; o filho de Amazias, Azarias; o filho de Azarias, Jotão;

[[v13-3-13]]

^<<v13-3-13,13>>^ o filho de Jotão, Acaz; o filho de Acaz, Ezequias; o filho de Ezequias, Manassés;

[[v13-3-14]]

^<<v13-3-14,14>>^ o filho de Manassés, Amom; o filho de Amom, Josias.

[[v13-3-15]]

^<<v13-3-15,15>>^ Os filhos de Josias foram: Joanã, o primeiro, Jeoaquim, o segundo, Zedequias, o terceiro, e Salum, o quarto.

[[v13-3-16]]

^<<v13-3-16,16>>^ Os sucessores de Jeoaquim foram: Joaquim e Zedequias.

[[v13-3-17]]

^<<v13-3-17,17>>^ Estes foram os filhos de Joaquim, que foi levado para o cativeiro: Sealtiel,

[[v13-3-18]]

^<<v13-3-18,18>>^ Malquirão, Pedaías, Senazar, Jecamias, Hosama e Nedabias.

[[v13-3-19]]

^<<v13-3-19,19>>^ Estes foram os filhos de Pedaías: Zorobabel e Simei. Estes foram os filhos de Zorobabel: Mesulão, Hananias e Selomite, irmã deles.

[[v13-3-20]]

^<<v13-3-20,20>>^ Teve ainda mais cinco filhos: Hasubá, Oel, Berequias, Hasadias e Jusabe-Hesede.

[[v13-3-21]]

^<<v13-3-21,21>>^ Estes foram os descendentes de Hananias: Pelatias e Jesaías, e os filhos de Refaías, de Arnã, de Obadias e de Secanias.

[[v13-3-22]]

^<<v13-3-22,22>>^ Estes foram os descendentes de Secanias: Semaías e seus filhos Hatus, Igal, Bariá, Nearias e Safate; seis descendentes ao todo.

[[v13-3-23]]

^<<v13-3-23,23>>^ Estes foram os três filhos de Nearias: Elioenai, Ezequias e Azricão.

[[v13-3-24]]

^<<v13-3-24,24>>^ Estes foram os sete filhos de Elioenai: Hodavias, Eliasibe, Pelaías, Acube, Joanã, Delaías e Anani.

'''

xref:013-1-cronicas/013-1-cronicas-002.adoc#v13-2-0[&#60; Capítulo Anterior] | <<v13-3-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-004.adoc#v13-4-0[Próximo Capítulo &#62;]