include::./index.adoc[]

[[v13-18-0]]
=== 1 Crônicas, 18
// nvi ?, NVI - Nova Versão Internacional

[[v13-18-1]]

^<<v13-18-1,1>>^ Depois disso, Davi derrotou os filisteus e os subjugou, e tirou do controle deles a cidade de Gate e seus povoados.

[[v13-18-2]]

^<<v13-18-2,2>>^ Davi derrotou também os moabitas, que ficaram sujeitos a ele, pagando-lhe impostos.

[[v13-18-3]]

^<<v13-18-3,3>>^ Além disso, Davi derrotou Hadadezer, rei de Zobá, nas proximidades de Hamate, quando Hadadezer tentava obter o controle na região do rio Eufrates.

[[v13-18-4]]

^<<v13-18-4,4>>^ Davi se apossou de mil dos seus carros de guerra, sete mil cavaleiros e vinte mil soldados de infantaria. Ainda levou cem cavalos de carros de guerra, e aleijou todos os outros.

[[v13-18-5]]

^<<v13-18-5,5>>^ Quando os arameus de Damasco vieram ajudar Hadadezer, rei de Zobá, Davi matou vinte e dois mil deles.

[[v13-18-6]]

^<<v13-18-6,6>>^ Em seguida estabeleceu guarnições militares no reino dos arameus de Damasco, sujeitando-os a lhe pagarem impostos. E o Senhor dava vitórias a Davi aonde quer que ele fosse.

[[v13-18-7]]

^<<v13-18-7,7>>^ Davi também levou para Jerusalém os escudos de ouro usados pelos oficiais de Hadadezer.

[[v13-18-8]]

^<<v13-18-8,8>>^ De Tebá e Cum, cidades que pertenciam a Hadadezer, o rei Davi levou grande quantidade de bronze, que Salomão utilizou para fazer o tanque de bronze, as colunas e vários utensílios.

[[v13-18-9]]

^<<v13-18-9,9>>^ Quando Toú, rei de Hamate, soube que Davi tinha derrotado todo o exército de Hadadezer, rei de Zobá,

[[v13-18-10]]

^<<v13-18-10,10>>^ enviou seu filho Hadorão ao rei Davi para saudá-lo e parabenizá-lo por sua vitória na batalha contra Hadadezer, que tinha estado em guerra com Toú. E, com Hadorão, mandou todo tipo de utensílios de ouro, de prata e de bronze.

[[v13-18-11]]

^<<v13-18-11,11>>^ O rei Davi consagrou esses utensílios ao Senhor, como fizera com a prata e o ouro tomados de todas estas nações: Edom e Moabe, os amonitas e os filisteus, e Amaleque.

[[v13-18-12]]

^<<v13-18-12,12>>^ Abisai, filho de Zeruia, derrotou dezoito mil edomitas no vale do Sal.

[[v13-18-13]]

^<<v13-18-13,13>>^ Depois colocou guarnições militares em Edom, sujeitando todos os edomitas a Davi. O Senhor dava vitórias a Davi aonde quer que ele fosse.

[[v13-18-14]]

^<<v13-18-14,14>>^ Davi reinou sobre todo o Israel, administrando o direito e a justiça a todo o seu povo.

[[v13-18-15]]

^<<v13-18-15,15>>^ Joabe, filho de Zeruia, era comandante do exército; Josafá, filho de Ailude, era o arquivista real;

[[v13-18-16]]

^<<v13-18-16,16>>^ Zadoque, filho de Aitube, e Aimeleque, filho de Abiatar, eram sacerdotes; Sausa era secretário;

[[v13-18-17]]

^<<v13-18-17,17>>^ Benaia, filho de Joiada, comandava os queretitas e os peletitas; e os filhos do rei Davi eram seus principais oficiais.

'''

xref:013-1-cronicas/013-1-cronicas-017.adoc#v13-17-0[&#60; Capítulo Anterior] | <<v13-18-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-019.adoc#v13-19-0[Próximo Capítulo &#62;]