include::./index.adoc[]

[[v13-29-0]]
=== 1 Crônicas, 29
// nvi ?, NVI - Nova Versão Internacional

[[v13-29-1]]

^<<v13-29-1,1>>^ Então o rei Davi disse a toda a assembléia: "Meu filho Salomão, e só ele, foi quem Deus escolheu. Mas ele é jovem e inexperiente e a tarefa é grande, pois o palácio não será feito para homens, mas para o Senhor Deus.

[[v13-29-2]]

^<<v13-29-2,2>>^ Forneci grande quantidade de recursos para o trabalho do templo do meu Deus: ouro, prata, bronze, ferro e madeira, bem como ônix para os engastes, e ainda turquesas, pedras de várias cores e todo tipo de pedras preciosas, e mármore.

[[v13-29-3]]

^<<v13-29-3,3>>^ Além disso, pelo meu amor ao templo do meu Deus, agora entrego das minhas próprias riquezas, ouro e prata para o templo do meu Deus, além de tudo o que já tenho dado para este santo templo.

[[v13-29-4]]

^<<v13-29-4,4>>^ Ofereço, pois, cento e cinco toneladas de ouro puro de Ofir e duzentos e quarenta e cinco toneladas de prata refinada, para o revestimento das paredes do templo,

[[v13-29-5]]

^<<v13-29-5,5>>^ para o trabalho em ouro e em prata, e para todo o trabalho dos artesãos. Agora, quem hoje está disposto a ofertar dádivas ao Senhor? "

[[v13-29-6]]

^<<v13-29-6,6>>^ Então os chefes das famílias, os líderes das tribos de Israel, os comandantes de mil e de cem, e os oficiais encarregados do trabalho do rei ofertaram espontaneamente.

[[v13-29-7]]

^<<v13-29-7,7>>^ Para a obra do templo de Deus eles deram cento e setenta e cinco toneladas de ouro e dez mil moedas de ouro, trezentas e cinqüenta toneladas de prata, seiscentas e trinta toneladas de bronze e três mil e quinhentas toneladas de ferro.

[[v13-29-8]]

^<<v13-29-8,8>>^ Quem tinha pedras preciosas deu-as para o depósito dos tesouros do templo do Senhor, cujo responsável era Jeiel, o gersonita.

[[v13-29-9]]

^<<v13-29-9,9>>^ O povo alegrou-se diante da atitude de seus líderes, pois fizeram essas ofertas voluntariamente e de coração íntegro ao Senhor. E o rei Davi também encheu-se de alegria.

[[v13-29-10]]

^<<v13-29-10,10>>^ Davi louvou o Senhor na presença de toda a assembléia, dizendo: "Bendito sejas, ó Senhor, Deus de Israel, nosso pai, de eternidade a eternidade.

[[v13-29-11]]

^<<v13-29-11,11>>^ Teus, ó Senhor, são a grandeza, o poder, a glória, a majestade e o esplendor, pois tudo o que há nos céus e na terra é teu. Teu, ó Senhor, é o reino; tu estás acima de tudo.

[[v13-29-12]]

^<<v13-29-12,12>>^ A riqueza e a honra vêm de ti; tu dominas sobre todas as coisas. Nas tuas mãos estão a força e o poder para exaltar e dar força a todos.

[[v13-29-13]]

^<<v13-29-13,13>>^ Agora, nosso Deus, damos-te graças, e louvamos o teu glorioso nome.

[[v13-29-14]]

^<<v13-29-14,14>>^ "Mas quem sou eu, e quem é o meu povo para que pudéssemos contribuir tão generosamente como fizemos? Tudo vem de ti, e nós apenas te demos o que vem das tuas mãos.

[[v13-29-15]]

^<<v13-29-15,15>>^ Diante de ti somos estrangeiros e forasteiros, como os nossos antepassados. Os nossos dias na terra são como uma sombra, sem esperança.

[[v13-29-16]]

^<<v13-29-16,16>>^ Ó Senhor, nosso Deus, toda essa riqueza que ofertamos para construir um templo em honra do teu santo nome vem das tuas mãos, e toda ela pertence a ti.

[[v13-29-17]]

^<<v13-29-17,17>>^ Sei, ó meu Deus, que sondas o coração e que te agradas com a integridade. Tudo o que dei foi espontaneamente e com integridade de coração. E agora vi com alegria com quanta disposição o teu povo, que aqui está, tem contribuído.

[[v13-29-18]]

^<<v13-29-18,18>>^ Ó Senhor, Deus de nossos antepassados Abraão, Isaque e Israel, conserva para sempre este desejo no coração de teu povo, e mantém o coração deles leal a ti.

[[v13-29-19]]

^<<v13-29-19,19>>^ E dá ao meu filho Salomão um coração íntegro para obedecer aos teus mandamentos, aos teus preceitos e aos teus decretos, a fim de construir este templo para o qual fiz os preparativos necessários".

[[v13-29-20]]

^<<v13-29-20,20>>^ Então Davi disse a toda a assembléia: "Louvem o Senhor, o seu Deus". E todos eles louvaram o Senhor, o Deus dos seus antepassados, inclinando-se e prostrando-se diante do Senhor e diante do rei.

[[v13-29-21]]

^<<v13-29-21,21>>^ No dia seguinte fizeram sacrifícios ao Senhor e lhe apresentaram holocaustos: mil novilhos, mil carneiros e mil cordeiros, acompanhados de ofertas derramadas, e muitos outros sacrifícios, em favor de todo o Israel.

[[v13-29-22]]

^<<v13-29-22,22>>^ Naquele dia, comeram e beberam com grande alegria na presença do Senhor. Então pela segunda vez proclamaram Salomão, filho de Davi, como rei, ungindo-o diante do Senhor como soberano, e Zadoque como sacerdote.

[[v13-29-23]]

^<<v13-29-23,23>>^ De maneira que Salomão assentou-se como rei no trono do Senhor, em lugar de Davi, seu pai. Ele prosperou, e todo o Israel lhe obedecia.

[[v13-29-24]]

^<<v13-29-24,24>>^ Todos os líderes e principais guerreiros, bem como todos os filhos do rei Davi prometeram submissão ao rei Salomão.

[[v13-29-25]]

^<<v13-29-25,25>>^ O Senhor exaltou muitíssimo Salomão em todo o Israel e concedeu-lhe tal esplendor em seu reinado como nenhum rei de Israel jamais tivera.

[[v13-29-26]]

^<<v13-29-26,26>>^ Davi, filho de Jessé, reinou sobre todo Israel.

[[v13-29-27]]

^<<v13-29-27,27>>^ Ele reinou quarenta anos em Israel: sete anos em Hebrom e trinta e três em Jerusalém.

[[v13-29-28]]

^<<v13-29-28,28>>^ Morreu em boa velhice, tendo desfrutado vida longa, riqueza e honra. Seu filho Salomão foi o seu sucessor.

[[v13-29-29]]

^<<v13-29-29,29>>^ Os feitos do rei Davi, desde o início até o fim do seu reinado, estão escritos nos registros do vidente Samuel, do profeta Natã e do vidente Gade,

[[v13-29-30]]

^<<v13-29-30,30>>^ incluindo os detalhes do seu reinado e do seu poder, e os acontecimentos relacionados a ele, com Israel e com os reinos das outras terras.

'''

xref:013-1-cronicas/013-1-cronicas-028.adoc#v13-28-0[&#60; Capítulo Anterior] | <<v13-29-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-001.adoc#v14-1-0[Próximo Capítulo &#62;]