include::./index.adoc[]

[[v13-17-0]]
=== 1 Crônicas, 17
// nvi ?, NVI - Nova Versão Internacional

[[v13-17-1]]

^<<v13-17-1,1>>^ O rei Davi já morava em seu palácio quando, certo dia disse ao profeta Natã: "Aqui estou eu, morando num palácio de cedro, enquanto a arca da aliança do Senhor permanece numa simples tenda".

[[v13-17-2]]

^<<v13-17-2,2>>^ Natã respondeu a Davi: "Faze o que tiveres em mente, pois Deus está contigo".

[[v13-17-3]]

^<<v13-17-3,3>>^ E naquela mesma noite Deus falou a Natã:

[[v13-17-4]]

^<<v13-17-4,4>>^ "Vá dizer ao meu servo Davi que assim diz o Senhor: Não será você quem vai construir uma casa para eu morar.

[[v13-17-5]]

^<<v13-17-5,5>>^ Não tenho morado em nenhuma casa, desde o dia em que tirei Israel do Egito, mas fui de uma tenda para outra, e de um tabernáculo para outro.

[[v13-17-6]]

^<<v13-17-6,6>>^ Por onde tenho acompanhado todo o Israel, alguma vez perguntei a algum líder deles, a quem ordenei que pastoreasse o meu povo: Por que você não me construiu um templo de cedro? "

[[v13-17-7]]

^<<v13-17-7,7>>^ "Agora pois, diga ao meu servo Davi: ‘Assim diz o Senhor dos Exércitos: Eu o tirei das pastagens, onde cuidava dos rebanhos, para ser o soberano do meu povo Israel.

[[v13-17-8]]

^<<v13-17-8,8>>^ Sempre estive com você por onde você andou, e eliminei todos os seus inimigos. Agora eu o farei tão famoso quanto os homens mais importantes da terra.

[[v13-17-9]]

^<<v13-17-9,9>>^ E providenciarei um lugar para o meu povo Israel e os plantarei lá, para que tenham o seu próprio lar; e não mais sejam incomodados. Povos ímpios não mais os oprimirão, como fizeram no início

[[v13-17-10]]

^<<v13-17-10,10>>^ e têm feito desde a época em que nomeei juízes sobre meu povo Israel. Também subjugarei todos os seus inimigos. Saiba também que eu, o Senhor, lhe estabelecerei uma dinastia.

[[v13-17-11]]

^<<v13-17-11,11>>^ Quando a sua vida chegar ao fim e você se juntar aos seus antepassados, escolherei um dos seus filhos para sucedê-lo, e eu estabelecerei o reino dele.

[[v13-17-12]]

^<<v13-17-12,12>>^ Será ele quem construirá um templo para mim, e eu firmarei o trono dele para sempre.

[[v13-17-13]]

^<<v13-17-13,13>>^ Eu serei seu pai, e ele será meu filho. Nunca retirarei dele o meu amor, como retirei de Saul.

[[v13-17-14]]

^<<v13-17-14,14>>^ Eu o farei líder do meu povo e do meu reino para sempre; seu reinado será estabelecido para sempre’. "

[[v13-17-15]]

^<<v13-17-15,15>>^ E Natã transmitiu a Davi tudo o que o Senhor lhe tinha falado e revelado.

[[v13-17-16]]

^<<v13-17-16,16>>^ Então o rei Davi entrou no tabernáculo, assentou-se diante do Senhor, e orou: "Quem sou eu, ó Senhor Deus, e o que é a minha família, para que me trouxesses a este ponto?

[[v13-17-17]]

^<<v13-17-17,17>>^ E, como se isso não bastasse para ti, ó Deus, tu falaste sobre o futuro da família deste teu servo. Tens me tratado como um homem de grande importância, ó Senhor Deus".

[[v13-17-18]]

^<<v13-17-18,18>>^ "O que mais Davi poderá dizer-te por honrares o teu servo? Tu conheces o teu servo,

[[v13-17-19]]

^<<v13-17-19,19>>^ ó Senhor. Por amor do teu servo e de acordo com tua vontade, realizaste este feito grandioso e tornaste conhecidas todas essas grandes promessas.

[[v13-17-20]]

^<<v13-17-20,20>>^ "Não há ninguém como tu, ó Senhor, nem há outro Deus além de ti, conforme tudo o que sabemos.

[[v13-17-21]]

^<<v13-17-21,21>>^ E quem é como o teu povo Israel, a única nação da terra que tu, ó Deus, resgataste para ti mesmo, e assim tornaste o teu nome famoso, realizaste grandes e impressionantes maravilhas ao expulsar nações de diante do povo que libertaste do Egito?

[[v13-17-22]]

^<<v13-17-22,22>>^ Tu fizeste do teu povo Israel o teu povo particular para sempre, e tu, ó Senhor, te tornaste o seu Deus.

[[v13-17-23]]

^<<v13-17-23,23>>^ "Agora, Senhor, que a promessa que fizeste a respeito de teu servo e de sua descendência se confirme para sempre. Faze conforme prometeste,

[[v13-17-24]]

^<<v13-17-24,24>>^ para que tudo se confirme, para que o teu nome seja engrandecido para sempre e os homens digam: ‘O Senhor dos Exércitos, o Deus de Israel, é Deus para Israel! ’ E a descendência de teu servo Davi se manterá firme diante de ti.

[[v13-17-25]]

^<<v13-17-25,25>>^ "Tu, meu Deus, revelaste a teu servo que formarás uma dinastia para ele. Por isso teu servo achou coragem para orar a ti.

[[v13-17-26]]

^<<v13-17-26,26>>^ Ó Senhor, tu és Deus! Tu fizeste essa boa promessa a teu servo.

[[v13-17-27]]

^<<v13-17-27,27>>^ Agora, por tua bondade, abençoa a família de teu servo, para que ela continue para sempre na tua presença; pois o que tu, Senhor, abençoas, abençoado está para sempre".

'''

xref:013-1-cronicas/013-1-cronicas-016.adoc#v13-16-0[&#60; Capítulo Anterior] | <<v13-17-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-018.adoc#v13-18-0[Próximo Capítulo &#62;]