include::./index.adoc[]

[[v13-28-0]]
=== 1 Crônicas, 28
// nvi ?, NVI - Nova Versão Internacional

[[v13-28-1]]

^<<v13-28-1,1>>^ Davi reuniu em Jerusalém todos os líderes de Israel: os líderes das tribos, os líderes das divisões a serviço do rei, os comandantes de mil e de cem, e os líderes encarregados de todos os bens e rebanhos que pertenciam ao rei e a seus filhos, juntamente com os funcionários do palácio, os principais guerreiros e todos os soldados valentes.

[[v13-28-2]]

^<<v13-28-2,2>>^ O rei Davi se pôs de pé e disse: "Escutem-me, meus irmãos e meu povo. Eu tinha no coração o propósito de construir um templo para nele colocar a arca da aliança do Senhor, o estrado dos pés de nosso Deus; fiz planos para construí-lo,

[[v13-28-3]]

^<<v13-28-3,3>>^ mas Deus me disse: ‘Você não construirá um templo em honra do meu nome, pois você é um guerreiro e matou muita gente’.

[[v13-28-4]]

^<<v13-28-4,4>>^ "No entanto, o Senhor, o Deus de Israel, escolheu-me dentre toda a minha família para ser rei em Israel, para sempre. Ele escolheu Judá como líder, e da tribo de Judá escolheu minha família, e entre os filhos de meu pai ele quis fazer-me rei de todo o Israel.

[[v13-28-5]]

^<<v13-28-5,5>>^ E, dentre todos os muitos filhos que me deu, ele escolheu Salomão para sentar-se no trono de Israel, o reino do Senhor.

[[v13-28-6]]

^<<v13-28-6,6>>^ Ele me disse: ‘Seu filho Salomão é quem construirá o meu templo e os meus pátios, pois eu o escolhi para ser meu filho, e eu serei o pai dele.

[[v13-28-7]]

^<<v13-28-7,7>>^ Firmarei para sempre o reino dele, se ele continuar a obedecer os meus mandamentos e as minhas ordenanças, como faz agora’.

[[v13-28-8]]

^<<v13-28-8,8>>^ "Por isso agora declaro-lhes perante todo o Israel e a assembléia do Senhor, e diante dos ouvidos de nosso Deus: Tenham o cuidado de obedecer a todos os mandamentos do Senhor, do seu Deus, para que mantenham a posse dessa boa terra e a dêem por herança aos seus descendentes para sempre.

[[v13-28-9]]

^<<v13-28-9,9>>^ "E você, meu filho Salomão, reconheça o Deus de seu pai, e sirva-o de todo o coração e espontaneamente, pois o Senhor sonda todos os corações e conhece a motivação dos pensamentos. Se você o buscar, o encontrará, mas, se você o abandonar, ele o rejeitará para sempre.

[[v13-28-10]]

^<<v13-28-10,10>>^ Veja que o Senhor o escolheu para construir um templo que me sirva de santuário. Seja forte e mãos ao trabalho! "

[[v13-28-11]]

^<<v13-28-11,11>>^ Então Davi deu a seu filho Salomão a planta do pórtico do templo, para os seus edifícios, para os seus depósitos, para os andares superiores e suas salas, e para o lugar do propiciatório.

[[v13-28-12]]

^<<v13-28-12,12>>^ Entregou-lhe também as plantas de tudo o que o Espírito havia posto em seu coração acerca dos pátios do templo do Senhor e de todas as salas ao redor, para os depósitos dos tesouros do templo de Deus e para os depósitos das dádivas sagradas.

[[v13-28-13]]

^<<v13-28-13,13>>^ Deu-lhe instruções sobre as divisões dos sacerdotes e dos levitas, e sobre à execução de todas as tarefas no templo do Senhor, e os utensílios que seriam utilizados.

[[v13-28-14]]

^<<v13-28-14,14>>^ Determinou o peso do ouro para todos os utensílios de ouro e o peso da prata para todos os utensílios de prata que seriam utilizados nas diferentes tarefas:

[[v13-28-15]]

^<<v13-28-15,15>>^ o peso de ouro para cada candelabro e suas lâmpadas; e o peso de prata para cada candelabro de prata e suas lâmpadas, de acordo com a finalidade de cada um;

[[v13-28-16]]

^<<v13-28-16,16>>^ o peso de ouro para cada mesa de pães consagrados; o peso de prata para as mesas de prata;

[[v13-28-17]]

^<<v13-28-17,17>>^ o peso de ouro puro para os garfos, para as bacias de aspersão e para os jarros; o peso de ouro para cada tigela de ouro; o peso de prata para cada tigela de prata;

[[v13-28-18]]

^<<v13-28-18,18>>^ e o peso de ouro refinado para o altar de incenso. Também lhe deu o desenho do carro dos querubins de ouro que, com suas asas estendidas, abrigam a arca da aliança do Senhor.

[[v13-28-19]]

^<<v13-28-19,19>>^ "Tudo isso", disse Davi a Salomão, "foi me dado por escrito pela mão do Senhor, e ele me deu entendimento para executar todos esses projetos. "

[[v13-28-20]]

^<<v13-28-20,20>>^ E acrescentou: "Seja forte e corajoso! Mãos ao trabalho! Não tenha medo nem se desanime, pois Deus, o Senhor, o meu Deus, está com você. Ele não o deixará nem o abandonará até que se termine toda a construção do templo do Senhor.

[[v13-28-21]]

^<<v13-28-21,21>>^ As divisões dos sacerdotes e dos levitas estão definidas para todas as tarefas que se farão no templo de Deus, e você receberá ajuda de homens peritos em todo tipo de serviço. Os líderes e todo o povo obedecerão a todas as suas ordens".

'''

xref:013-1-cronicas/013-1-cronicas-027.adoc#v13-27-0[&#60; Capítulo Anterior] | <<v13-28-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-029.adoc#v13-29-0[Próximo Capítulo &#62;]