include::./index.adoc[]

[[v13-13-0]]
=== 1 Crônicas, 13
// nvi ?, NVI - Nova Versão Internacional

[[v13-13-1]]

^<<v13-13-1,1>>^ Depois de consultar todos os seus oficiais, os comandantes de mil e de cem,

[[v13-13-2]]

^<<v13-13-2,2>>^ Davi disse a toda a assembléia de Israel: "Se vocês estão de acordo e se esta é a vontade do Senhor nosso Deus, enviemos uma mensagem a nossos irmãos em todo o território de Israel, e também aos sacerdotes e aos levitas que estão com eles em suas cidades, para virem unir-se a nós.

[[v13-13-3]]

^<<v13-13-3,3>>^ Vamos trazer de volta a arca de nosso Deus, pois não nos importamos com ela durante o reinado de Saul".

[[v13-13-4]]

^<<v13-13-4,4>>^ Toda a assembléia concordou, pois isso pareceu bem a todo o povo.

[[v13-13-5]]

^<<v13-13-5,5>>^ Então Davi reuniu todos os israelitas, desde o rio Sior, no Egito, até Lebo-Hamate, para trazerem de Quiriate-Jearim a arca de Deus.

[[v13-13-6]]

^<<v13-13-6,6>>^ Davi e todos os israelitas foram a Baalá, que é Quiriate-Jearim, em Judá, para buscar a arca de Deus, o Senhor, entronizado entre os querubins; a arca sobre a qual seu nome é invocado.

[[v13-13-7]]

^<<v13-13-7,7>>^ Da casa de Abinadabe levaram a arca de Deus num carroção novo, conduzido por Uzá e Aiô.

[[v13-13-8]]

^<<v13-13-8,8>>^ Davi e todos os israelitas iam dançando e cantando com todo o vigor diante de Deus, ao som de harpas, liras, tamborins, címbalos e cornetas.

[[v13-13-9]]

^<<v13-13-9,9>>^ Quando chegaram à eira de Quidom, Uzá esticou o braço e segurou a arca, porque os bois haviam tropeçado.

[[v13-13-10]]

^<<v13-13-10,10>>^ A ira do Senhor acendeu-se contra Uzá, e ele o feriu por ter tocado na arca. Uzá morreu ali mesmo, diante de Deus.

[[v13-13-11]]

^<<v13-13-11,11>>^ Davi ficou contrariado porque o Senhor, em sua ira, havia fulminado Uzá. Até hoje aquele lugar é chamado Perez-Uzá.

[[v13-13-12]]

^<<v13-13-12,12>>^ Naquele dia, Davi teve medo de Deus e se perguntou: "Como vou conseguir levar a arca de Deus? "

[[v13-13-13]]

^<<v13-13-13,13>>^ Por isso desistiu de levar a arca para a cidade de Davi. Em vez disso, levou-a para a casa de Obede-Edom, de Gate.

[[v13-13-14]]

^<<v13-13-14,14>>^ A arca de Deus ficou na casa dele por três meses, e o Senhor abençoou sua família e tudo o que possuía.

'''

xref:013-1-cronicas/013-1-cronicas-012.adoc#v13-12-0[&#60; Capítulo Anterior] | <<v13-13-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-014.adoc#v13-14-0[Próximo Capítulo &#62;]