include::./index.adoc[]

[[v13-25-0]]
=== 1 Crônicas, 25
// nvi ?, NVI - Nova Versão Internacional

[[v13-25-1]]

^<<v13-25-1,1>>^ Davi, junto com os comandantes do exército, separou alguns dos filhos de Asafe, de Hemã e de Jedutum para o ministério de profetizar ao som de harpas, liras e címbalos. Esta é a lista dos escolhidos para essa função:

[[v13-25-2]]

^<<v13-25-2,2>>^ Dos filhos de Asafe: Zacur, José, Netanias e Asarela. Os filhos de Asafe estavam sob a sua supervisão que, por sua vez, profetizava sob a supervisão do rei.

[[v13-25-3]]

^<<v13-25-3,3>>^ Dos filhos de Jedutum: Gedalias, Zeri, Jesaías, Simei, Hasabias e Matitias, seis ao todo, sob a supervisão de seu pai, Jedutum, que profetizava ao som da harpa para agradecer e louvar ao Senhor.

[[v13-25-4]]

^<<v13-25-4,4>>^ Dos filhos de Hemã: Buquias, Matanias, Uziel, Sebuel, Jeremote, Hananias, Hanani, Eliata, Gidalti, Romanti-Ézer, Josbecasa, Maloti, Hotir e Maaziote.

[[v13-25-5]]

^<<v13-25-5,5>>^ Todos esses eram filhos de Hemã, o vidente do rei. Esses lhe nasceram conforme as promessas de que Deus haveria de torná-lo poderoso. E Deus deu a Hemã catorze filhos e três filhas.

[[v13-25-6]]

^<<v13-25-6,6>>^ Todos esses homens estavam sob a supervisão de seus pais quando ministravam a música do templo do Senhor, com címbalos, liras e harpas, na casa de Deus. Asafe, Jedutum e Hemã estavam sob a supervisão do rei.

[[v13-25-7]]

^<<v13-25-7,7>>^ Junto com seus parentes, todos capazes e preparados para o ministério do louvor do Senhor, totalizavam 288.

[[v13-25-8]]

^<<v13-25-8,8>>^ Então tiraram sortes entre jovens e velhos, mestres e discípulos para designar-lhes suas responsabilidades.

[[v13-25-9]]

^<<v13-25-9,9>>^ A primeira sorte, caiu para José, filho de Asafe, com seus filhos e parentes; eram ao todo 12; a segunda, para Gedalias, com seus filhos e parentes, eram ao todo 12;

[[v13-25-10]]

^<<v13-25-10,10>>^ a terceira, para Zacur, com seus filhos e parentes, eram ao todo 12;

[[v13-25-11]]

^<<v13-25-11,11>>^ a quarta, para Izri, com seus filhos e parentes, eram ao todo 12;

[[v13-25-12]]

^<<v13-25-12,12>>^ a quinta, para Netanias, com seus filhos e parentes, eram ao todo 12;

[[v13-25-13]]

^<<v13-25-13,13>>^ a sexta, para Buquias, com seus filhos e parentes, eram ao todo 12;

[[v13-25-14]]

^<<v13-25-14,14>>^ a sétima, para Jesarela, com seus filhos e parentes, eram ao todo 12;

[[v13-25-15]]

^<<v13-25-15,15>>^ a oitava, para Jesaías, com seus filhos e parentes, eram ao todo 12;

[[v13-25-16]]

^<<v13-25-16,16>>^ a nona, para Matanias, com seus filhos e parentes, eram ao todo 12;

[[v13-25-17]]

^<<v13-25-17,17>>^ a décima, para Simei, com seus filhos e parentes, eram ao todo 12;

[[v13-25-18]]

^<<v13-25-18,18>>^ a décima primeira, para Azareel, com seus filhos e parentes, eram ao todo 12;

[[v13-25-19]]

^<<v13-25-19,19>>^ a décima segunda, para Hasabias, com seus filhos e parentes, eram ao todo 12;

[[v13-25-20]]

^<<v13-25-20,20>>^ a décima terceira, para Subael, com seus filhos e parentes, eram ao todo 12;

[[v13-25-21]]

^<<v13-25-21,21>>^ a décima quarta, para Matitias, com seus filhos e parentes, eram ao todo 12;

[[v13-25-22]]

^<<v13-25-22,22>>^ a décima quinta, para Jeremote, com seus filhos e parentes, eram ao todo 12;

[[v13-25-23]]

^<<v13-25-23,23>>^ a décima sexta, para Hananias, com seus filhos e parentes, eram ao todo 12;

[[v13-25-24]]

^<<v13-25-24,24>>^ a décima sétima, para Josbecasa, com seus filhos e parentes, eram ao todo 12;

[[v13-25-25]]

^<<v13-25-25,25>>^ a décima oitava, para Hanani, com seus filhos e parentes, eram ao todo 12;

[[v13-25-26]]

^<<v13-25-26,26>>^ a décima nona, para Maloti, com seus filhos e parentes, eram ao todo 12;

[[v13-25-27]]

^<<v13-25-27,27>>^ a vigésima, para Eliata, com seus filhos e parentes, eram ao todo 12;

[[v13-25-28]]

^<<v13-25-28,28>>^ a vigésima primeira, para Hotir, com seus filhos e parentes, eram ao todo 12;

[[v13-25-29]]

^<<v13-25-29,29>>^ a vigésima segunda, para Gidalti, com seus filhos e parentes, eram ao todo 12;

[[v13-25-30]]

^<<v13-25-30,30>>^ a vigésima terceira, para Maaziote, com seus filhos e parentes, eram ao todo 12;

[[v13-25-31]]

^<<v13-25-31,31>>^ a vigésima quarta, para Romanti-Ézer, com seus filhos e parentes, eram ao todo 12.

'''

xref:013-1-cronicas/013-1-cronicas-024.adoc#v13-24-0[&#60; Capítulo Anterior] | <<v13-25-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-026.adoc#v13-26-0[Próximo Capítulo &#62;]