include::./index.adoc[]

[[v59-5-0]]
=== Tiago, 5
// nvi ?, NVI - Nova Versão Internacional

[[v59-5-1]]

^<<v59-5-1,1>>^ Ouçam agora vocês, ricos! Chorem e lamentem-se, tendo em vista a miséria que lhes sobrevirá.

[[v59-5-2]]

^<<v59-5-2,2>>^ A riqueza de vocês apodreceu, e as traças corroeram as suas roupas.

[[v59-5-3]]

^<<v59-5-3,3>>^ O ouro e a prata de vocês enferrujaram, e a ferrugem deles testemunhará contra vocês e como fogo lhes devorará a carne. Vocês acumularam bens nestes últimos dias.

[[v59-5-4]]

^<<v59-5-4,4>>^ Vejam, o salário dos trabalhadores que ceifaram os seus campos, e que por vocês foi retido com fraude, está clamando contra vocês. O lamento dos ceifeiros chegou aos ouvidos do Senhor dos Exércitos.

[[v59-5-5]]

^<<v59-5-5,5>>^ Vocês viveram luxuosamente na terra, desfrutando prazeres, e fartaram-se de comida em dia de abate.

[[v59-5-6]]

^<<v59-5-6,6>>^ Vocês têm condenado e matado o justo, sem que ele ofereça resistência.

[[v59-5-7]]

^<<v59-5-7,7>>^ Portanto, irmãos, sejam pacientes até a vinda do Senhor. Vejam como o agricultor aguarda que a terra produza a preciosa colheita e como espera com paciência até virem as chuvas do outono e da primavera.

[[v59-5-8]]

^<<v59-5-8,8>>^ Sejam também pacientes e fortaleçam o coração, pois a vinda do Senhor está próxima.

[[v59-5-9]]

^<<v59-5-9,9>>^ Irmãos, não se queixem uns dos outros, para que não sejam julgados. O Juiz já está às portas!

[[v59-5-10]]

^<<v59-5-10,10>>^ Irmãos, tenham os profetas que falaram em nome do Senhor como exemplo de paciência diante do sofrimento.

[[v59-5-11]]

^<<v59-5-11,11>>^ Como vocês sabem, nós consideramos felizes aqueles que mostraram perseverança. Vocês ouviram falar sobre a paciência de Jó e viram o fim que o Senhor lhe proporcionou. O Senhor é cheio de compaixão e misericórdia.

[[v59-5-12]]

^<<v59-5-12,12>>^ Sobretudo, meus irmãos, não jurem nem pelo céu, nem pela terra, nem por qualquer outra coisa. Seja o sim de vocês, sim, e o não, não, para que não caiam em condenação.

[[v59-5-13]]

^<<v59-5-13,13>>^ Entre vocês há alguém que está sofrendo? Que ele ore. Há alguém que se sente feliz? Que ele cante louvores.

[[v59-5-14]]

^<<v59-5-14,14>>^ Entre vocês há alguém que está doente? Que ele mande chamar os presbíteros da igreja, para que estes orem sobre ele e o unjam com óleo, em nome do Senhor.

[[v59-5-15]]

^<<v59-5-15,15>>^ E a oração feita com fé curará o doente; o Senhor o levantará. E se houver cometido pecados, ele será perdoado.

[[v59-5-16]]

^<<v59-5-16,16>>^ Portanto, confessem os seus pecados uns aos outros e orem uns pelos outros para serem curados. A oração de um justo é poderosa e eficaz.

[[v59-5-17]]

^<<v59-5-17,17>>^ Elias era humano como nós. Ele orou fervorosamente para que não chovesse, e não choveu sobre a terra durante três anos e meio.

[[v59-5-18]]

^<<v59-5-18,18>>^ Orou outra vez, e o céu enviou chuva, e a terra produziu os seus frutos.

[[v59-5-19]]

^<<v59-5-19,19>>^ Meus irmãos, se algum de vocês se desviar da verdade e alguém o trouxer de volta,

[[v59-5-20]]

^<<v59-5-20,20>>^ lembrem-se disso: Quem converte um pecador do erro do seu caminho, salvará a vida dessa pessoa e fará que muitíssimos pecados sejam perdoados.

'''

xref:059-tiago/059-tiago-004.adoc#v59-4-0[&#60; Capítulo Anterior] | <<v59-5-0,Topo>> | xref:060-1-pedro/060-1-pedro-001.adoc#v60-1-0[Próximo Capítulo &#62;]