include::./index.adoc[]

[[v59-3-0]]
=== Tiago, 3
// nvi ?, NVI - Nova Versão Internacional

[[v59-3-1]]

^<<v59-3-1,1>>^ Meus irmãos, não sejam muitos de vocês mestres, pois vocês sabem que nós, os que ensinamos, seremos julgados com maior rigor.

[[v59-3-2]]

^<<v59-3-2,2>>^ Todos tropeçamos de muitas maneiras. Se alguém não tropeça no falar, tal homem é perfeito, sendo também capaz de dominar todo o seu corpo.

[[v59-3-3]]

^<<v59-3-3,3>>^ Quando colocamos freios na boca dos cavalos para que eles nos obedeçam, podemos controlar o animal todo.

[[v59-3-4]]

^<<v59-3-4,4>>^ Tomem também como exemplo os navios; embora sejam tão grandes e impelidos por fortes ventos, são dirigidos por um leme muito pequeno, conforme a vontade do piloto.

[[v59-3-5]]

^<<v59-3-5,5>>^ Semelhantemente, a língua é um pequeno órgão do corpo, mas se vangloria de grandes coisas. Vejam como um grande bosque é incendiado por uma simples fagulha.

[[v59-3-6]]

^<<v59-3-6,6>>^ Assim também, a língua é um fogo; é um mundo de iniqüidade. Colocada entre os membros do nosso corpo, contamina a pessoa por inteiro, incendeia todo o curso de sua vida, sendo ela mesma incendiada pelo inferno.

[[v59-3-7]]

^<<v59-3-7,7>>^ Toda espécie de animais, aves, répteis e criaturas do mar doma-se e é domada pela espécie humana;

[[v59-3-8]]

^<<v59-3-8,8>>^ a língua, porém, ninguém consegue domar. É um mal incontrolável, cheio de veneno mortífero.

[[v59-3-9]]

^<<v59-3-9,9>>^ Com a língua bendizemos ao Senhor e Pai, e com ela amaldiçoamos os homens, feitos à semelhança de Deus.

[[v59-3-10]]

^<<v59-3-10,10>>^ Da mesma boca procedem bênção e maldição. Meus irmãos, não pode ser assim!

[[v59-3-11]]

^<<v59-3-11,11>>^ Acaso pode sair água doce e água amarga da mesma fonte?

[[v59-3-12]]

^<<v59-3-12,12>>^ Meus irmãos, pode uma figueira produzir azeitonas ou uma videira, figos? Da mesma forma, uma fonte de água salgada não pode produzir água doce.

[[v59-3-13]]

^<<v59-3-13,13>>^ Quem é sábio e tem entendimento entre vocês? Que o demonstre por seu bom procedimento, mediante obras praticadas com a humildade que provém da sabedoria.

[[v59-3-14]]

^<<v59-3-14,14>>^ Contudo, se vocês abrigam no coração inveja amarga e ambição egoísta, não se gloriem disso, nem neguem a verdade.

[[v59-3-15]]

^<<v59-3-15,15>>^ Esse tipo de "sabedoria" não vem do céu, mas é terrena, não é espiritual e é demoníaca.

[[v59-3-16]]

^<<v59-3-16,16>>^ Pois onde há inveja e ambição egoísta, aí há confusão e toda espécie de males.

[[v59-3-17]]

^<<v59-3-17,17>>^ Mas a sabedoria que vem do alto é antes de tudo pura; depois, pacífica, amável, compreensiva, cheia de misericórdia e de bons frutos, imparcial e sincera.

[[v59-3-18]]

^<<v59-3-18,18>>^ O fruto da justiça semeia-se em paz para os pacificadores.

'''

xref:059-tiago/059-tiago-002.adoc#v59-2-0[&#60; Capítulo Anterior] | <<v59-3-0,Topo>> | xref:059-tiago/059-tiago-004.adoc#v59-4-0[Próximo Capítulo &#62;]