include::./index.adoc[]

[[v59-4-0]]
=== Tiago, 4
// nvi ?, NVI - Nova Versão Internacional

[[v59-4-1]]

^<<v59-4-1,1>>^ De onde vêm as guerras e contendas que há entre vocês? Não vêm das paixões que guerreiam dentro de vocês?

[[v59-4-2]]

^<<v59-4-2,2>>^ Vocês cobiçam coisas, e não as têm; matam e invejam, mas não conseguem obter o que desejam. Vocês vivem a lutar e a fazer guerras. Não têm, porque não pedem.

[[v59-4-3]]

^<<v59-4-3,3>>^ Quando pedem, não recebem, pois pedem por motivos errados, para gastar em seus prazeres.

[[v59-4-4]]

^<<v59-4-4,4>>^ Adúlteros, vocês não sabem que a amizade com o mundo é inimizade com Deus? Quem quer ser amigo do mundo faz-se inimigo de Deus.

[[v59-4-5]]

^<<v59-4-5,5>>^ Ou vocês acham que é sem razão que a Escritura diz que o Espírito que ele fez habitar em nós tem fortes ciúmes?

[[v59-4-6]]

^<<v59-4-6,6>>^ Mas ele nos concede graça maior. Por isso diz a Escritura: "Deus se opõe aos orgulhosos, mas concede graça aos humildes".

[[v59-4-7]]

^<<v59-4-7,7>>^ Portanto, submetam-se a Deus. Resistam ao diabo, e ele fugirá de vocês.

[[v59-4-8]]

^<<v59-4-8,8>>^ Aproximem-se de Deus, e ele se aproximará de vocês! Pecadores, limpem as mãos, e vocês, que têm a mente dividida, purifiquem o coração.

[[v59-4-9]]

^<<v59-4-9,9>>^ Entristeçam-se, lamentem e chorem. Troquem o riso por lamento e a alegria por tristeza.

[[v59-4-10]]

^<<v59-4-10,10>>^ Humilhem-se diante do Senhor, e ele os exaltará.

[[v59-4-11]]

^<<v59-4-11,11>>^ Irmãos, não falem mal uns dos outros. Quem fala contra o seu irmão ou julga o seu irmão, fala contra a Lei e a julga. Quando você julga a Lei, não a está cumprindo, mas está se colocando como juiz.

[[v59-4-12]]

^<<v59-4-12,12>>^ Há apenas um Legislador e Juiz, aquele que pode salvar e destruir. Mas quem é você para julgar o seu próximo?

[[v59-4-13]]

^<<v59-4-13,13>>^ Ouçam agora, vocês que dizem: "Hoje ou amanhã iremos para esta ou aquela cidade, passaremos um ano ali, faremos negócios e ganharemos dinheiro".

[[v59-4-14]]

^<<v59-4-14,14>>^ Vocês nem sabem o que lhes acontecerá amanhã! Que é a sua vida? Vocês são como a neblina que aparece por um pouco de tempo e depois se dissipa.

[[v59-4-15]]

^<<v59-4-15,15>>^ Ao invés disso, deveriam dizer: "Se o Senhor quiser, viveremos e faremos isto ou aquilo".

[[v59-4-16]]

^<<v59-4-16,16>>^ Agora, porém, vocês se vangloriam das suas pretensões. Toda vanglória como essa é maligna.

[[v59-4-17]]

^<<v59-4-17,17>>^ Pensem nisto, pois: Quem sabe que deve fazer o bem e não o faz, comete pecado.

'''

xref:059-tiago/059-tiago-003.adoc#v59-3-0[&#60; Capítulo Anterior] | <<v59-4-0,Topo>> | xref:059-tiago/059-tiago-005.adoc#v59-5-0[Próximo Capítulo &#62;]