include::./index.adoc[]

[[v59-2-0]]
=== Tiago, 2
// nvi ?, NVI - Nova Versão Internacional

[[v59-2-1]]

^<<v59-2-1,1>>^ Meus irmãos, como crentes em nosso glorioso Senhor Jesus Cristo, não façam diferença entre as pessoas, tratando-as com favoritismo.

[[v59-2-2]]

^<<v59-2-2,2>>^ Suponham que na reunião de vocês entre um homem com anel de ouro e roupas finas, e também entre um homem pobre com roupas velhas e sujas.

[[v59-2-3]]

^<<v59-2-3,3>>^ Se vocês derem atenção especial ao homem que está vestido com roupas finas e disserem: "Aqui está um lugar apropriado para o senhor", mas disserem ao pobre: "Você, fique de pé ali", ou: "Sente-se no chão, junto ao estrado onde ponho os meus pés",

[[v59-2-4]]

^<<v59-2-4,4>>^ não estarão fazendo discriminação, fazendo julgamentos com critérios errados?

[[v59-2-5]]

^<<v59-2-5,5>>^ Ouçam, meus amados irmãos: não escolheu Deus os que são pobres aos olhos do mundo para serem ricos em fé e herdarem o Reino que ele prometeu aos que o amam?

[[v59-2-6]]

^<<v59-2-6,6>>^ Mas vocês têm desprezado o pobre. Não são os ricos que oprimem vocês? Não são eles os que os arrastam para os tribunais?

[[v59-2-7]]

^<<v59-2-7,7>>^ Não são eles que difamam o bom nome que sobre vocês foi invocado?

[[v59-2-8]]

^<<v59-2-8,8>>^ Se vocês de fato obedecerem à lei real encontrada na Escritura que diz: "Ame o seu próximo como a si mesmo", estarão agindo corretamente.

[[v59-2-9]]

^<<v59-2-9,9>>^ Mas se tratarem os outros com favoritismo, estarão cometendo pecado e serão condenados pela Lei como transgressores.

[[v59-2-10]]

^<<v59-2-10,10>>^ Pois quem obedece a toda a Lei, mas tropeça em apenas um ponto, torna-se culpado de quebrá-la inteiramente.

[[v59-2-11]]

^<<v59-2-11,11>>^ Pois aquele que disse: "Não adulterarás", também disse: "Não matarás". Se você não comete adultério, mas comete assassinato, torna-se transgressor da Lei.

[[v59-2-12]]

^<<v59-2-12,12>>^ Falem e ajam como quem vai ser julgado pela lei da liberdade;

[[v59-2-13]]

^<<v59-2-13,13>>^ porque será exercido juízo sem misericórdia sobre quem não foi misericordioso. A misericórdia triunfa sobre o juízo!

[[v59-2-14]]

^<<v59-2-14,14>>^ De que adianta, meus irmãos, alguém dizer que tem fé, se não tem obras? Acaso a fé pode salvá-lo?

[[v59-2-15]]

^<<v59-2-15,15>>^ Se um irmão ou irmã estiver necessitando de roupas e do alimento de cada dia

[[v59-2-16]]

^<<v59-2-16,16>>^ e um de vocês lhe disser: "Vá em paz, aqueça-se e alimente-se até satisfazer-se", sem porém lhe dar nada, de que adianta isso?

[[v59-2-17]]

^<<v59-2-17,17>>^ Assim também a fé, por si só, se não for acompanhada de obras, está morta.

[[v59-2-18]]

^<<v59-2-18,18>>^ Mas alguém dirá: "Você tem fé; eu tenho obras". Mostre-me a sua fé sem obras, e eu lhe mostrarei a minha fé pelas obras.

[[v59-2-19]]

^<<v59-2-19,19>>^ Você crê que existe um só Deus? Muito bem! Até mesmo os demônios crêem — e tremem!

[[v59-2-20]]

^<<v59-2-20,20>>^ Insensato! Quer certificar-se de que a fé sem obras é inútil?

[[v59-2-21]]

^<<v59-2-21,21>>^ Não foi Abraão, nosso antepassado, justificado por obras, quando ofereceu seu filho Isaque sobre o altar?

[[v59-2-22]]

^<<v59-2-22,22>>^ Você pode ver que tanto a fé como as suas obras estavam atuando juntas, e a fé foi aperfeiçoada pelas obras.

[[v59-2-23]]

^<<v59-2-23,23>>^ Cumpriu-se assim a Escritura que diz: "Abraão creu em Deus, e isso lhe foi creditado como justiça", e ele foi chamado amigo de Deus.

[[v59-2-24]]

^<<v59-2-24,24>>^ Vejam que uma pessoa é justificada por obras, e não apenas pela fé.

[[v59-2-25]]

^<<v59-2-25,25>>^ Caso semelhante é o de Raabe, a prostituta: não foi ela justificada pelas obras, quando acolheu os espias e os fez sair por outro caminho?

[[v59-2-26]]

^<<v59-2-26,26>>^ Assim como o corpo sem espírito está morto, também a fé sem obras está morta.

'''

xref:059-tiago/059-tiago-001.adoc#v59-1-0[&#60; Capítulo Anterior] | <<v59-2-0,Topo>> | xref:059-tiago/059-tiago-003.adoc#v59-3-0[Próximo Capítulo &#62;]