include::./index.adoc[]

[[v56-3-0]]
=== Tito, 3
// nvi ?, NVI - Nova Versão Internacional

[[v56-3-1]]

^<<v56-3-1,1>>^ Lembre a todos que se sujeitem aos governantes e às autoridades, sejam obedientes, estejam sempre prontos a fazer tudo o que é bom,

[[v56-3-2]]

^<<v56-3-2,2>>^ não caluniem a ninguém, sejam pacíficos e amáveis e mostrem sempre verdadeira mansidão para com todos os homens.

[[v56-3-3]]

^<<v56-3-3,3>>^ Houve tempo em que nós também éramos insensatos e desobedientes, vivíamos enganados e escravizados por toda espécie de paixões e prazeres. Vivíamos na maldade e na inveja, sendo detestáveis e odiando-nos uns aos outros.

[[v56-3-4]]

^<<v56-3-4,4>>^ Mas quando se manifestaram a bondade e o amor pelos homens da parte de Deus, nosso Salvador,

[[v56-3-5]]

^<<v56-3-5,5>>^ não por causa de atos de justiça por nós praticados, mas devido à sua misericórdia, ele nos salvou pelo lavar regenerador e renovador do Espírito Santo,

[[v56-3-6]]

^<<v56-3-6,6>>^ que ele derramou sobre nós generosamente, por meio de Jesus Cristo, nosso Salvador.

[[v56-3-7]]

^<<v56-3-7,7>>^ Ele o fez a fim de que, justificados por sua graça, nos tornemos seus herdeiros, tendo a esperança da vida eterna.

[[v56-3-8]]

^<<v56-3-8,8>>^ Fiel é esta palavra, e quero que você afirme categoricamente essas coisas, para que os que crêem em Deus se empenhem na prática de boas obras. Tais coisas são excelentes e úteis aos homens.

[[v56-3-9]]

^<<v56-3-9,9>>^ Evite, porém, controvérsias tolas, genealogias, discussões e contendas a respeito da lei, porque essas coisas são inúteis e sem valor.

[[v56-3-10]]

^<<v56-3-10,10>>^ Quanto àquele que provoca divisões, advirta-o uma e duas vezes. Depois disso, rejeite-o.

[[v56-3-11]]

^<<v56-3-11,11>>^ Você sabe que tal pessoa se perverteu e está em pecado; por si mesma está condenada.

[[v56-3-12]]

^<<v56-3-12,12>>^ Quando eu lhe enviar Ártemas ou Tíquico, faça o possível para vir ao meu encontro em Nicópolis, pois decidi passar o inverno ali.

[[v56-3-13]]

^<<v56-3-13,13>>^ Providencie tudo o que for necessário para a viagem de Zenas, o jurista, e de Apolo, de modo que nada lhes falte.

[[v56-3-14]]

^<<v56-3-14,14>>^ Quanto aos nossos, que aprendam a dedicar-se à prática de boas obras, a fim de que supram as necessidades diárias e não sejam improdutivos.

[[v56-3-15]]

^<<v56-3-15,15>>^ Todos os que estão comigo lhe enviam saudações. Saudações àqueles que nos amam na fé. A graça seja com todos vocês.

'''

xref:056-tito/056-tito-002.adoc#v56-2-0[&#60; Capítulo Anterior] | <<v56-3-0,Topo>> | xref:057-filemom/057-filemom-001.adoc#v57-1-0[Próximo Capítulo &#62;]