include::./index.adoc[]

[[v56-1-0]]
=== Tito, 1
// nvi ?, NVI - Nova Versão Internacional

[[v56-1-1]]

^<<v56-1-1,1>>^ Paulo, servo de Deus e apóstolo de Jesus Cristo para levar os eleitos de Deus à fé e ao conhecimento da verdade que conduz à piedade,

[[v56-1-2]]

^<<v56-1-2,2>>^ fé e conhecimento que se fundamentam na esperança da vida eterna, a qual o Deus que não mente prometeu antes dos tempos eternos.

[[v56-1-3]]

^<<v56-1-3,3>>^ No devido tempo, ele trouxe à luz a sua palavra, por meio da pregação a mim confiada por ordem de Deus, nosso Salvador,

[[v56-1-4]]

^<<v56-1-4,4>>^ a Tito, meu verdadeiro filho em nossa fé comum: Graça e paz da parte de Deus Pai e de Cristo Jesus, nosso Salvador.

[[v56-1-5]]

^<<v56-1-5,5>>^ A razão de tê-lo deixado em Creta foi para que você pusesse em ordem o que ainda faltava e constituísse presbíteros em cada cidade, como eu o instruí.

[[v56-1-6]]

^<<v56-1-6,6>>^ É preciso que o presbítero seja irrepreensível, marido de uma só mulher, e tenha filhos crentes que não sejam acusados de libertinagem ou de insubmissão.

[[v56-1-7]]

^<<v56-1-7,7>>^ Por ser encarregado da obra de Deus, é necessário que o bispo seja irrepreensível: não orgulhoso, não briguento, não apegado ao vinho, não violento, nem ávido por lucro desonesto.

[[v56-1-8]]

^<<v56-1-8,8>>^ É preciso, porém, que ele seja hospitaleiro, amigo do bem, sensato, justo, consagrado, tenha domínio próprio

[[v56-1-9]]

^<<v56-1-9,9>>^ e apegue-se firmemente à mensagem fiel, da maneira como foi ensinada, para que seja capaz de encorajar outros pela sã doutrina e de refutar os que se opõem a ela.

[[v56-1-10]]

^<<v56-1-10,10>>^ Pois há muitos insubordinados, que não passam de faladores e enganadores, especialmente os do grupo da circuncisão.

[[v56-1-11]]

^<<v56-1-11,11>>^ É necessário que eles sejam silenciados, pois estão arruinando famílias inteiras, ensinando coisas que não devem, e tudo por ganância.

[[v56-1-12]]

^<<v56-1-12,12>>^ Um dos seus próprios profetas chegou a dizer: "Cretenses, sempre mentirosos, feras malignas, glutões preguiçosos".

[[v56-1-13]]

^<<v56-1-13,13>>^ Tal testemunho é verdadeiro. Portanto, repreenda-os severamente, para que sejam sadios na fé

[[v56-1-14]]

^<<v56-1-14,14>>^ e não dêem atenção a lendas judaicas nem a mandamentos de homens que rejeitam a verdade.

[[v56-1-15]]

^<<v56-1-15,15>>^ Para os puros, todas as coisas são puras; mas para os impuros e descrentes, nada é puro. De fato, tanto a mente como a consciência deles estão corrompidas.

[[v56-1-16]]

^<<v56-1-16,16>>^ Eles afirmam que conhecem a Deus, mas por seus atos o negam; são detestáveis, desobedientes e desqualificados para qualquer boa obra.

'''

xref:055-2-timoteo/055-2-timoteo-004.adoc#v55-4-0[&#60; Capítulo Anterior] | <<v56-1-0,Topo>> | xref:056-tito/056-tito-002.adoc#v56-2-0[Próximo Capítulo &#62;]