include::./index.adoc[]

[[v62-2-0]]
=== 1 João, 2
// nvi ?, NVI - Nova Versão Internacional

[[v62-2-1]]

^<<v62-2-1,1>>^ Meus filhinhos, escrevo-lhes estas coisas para que vocês não pequem. Se, porém, alguém pecar, temos um intercessor junto ao Pai, Jesus Cristo, o Justo.

[[v62-2-2]]

^<<v62-2-2,2>>^ Ele é a propiciação pelos nossos pecados, e não somente pelos nossos, mas também pelos pecados de todo o mundo.

[[v62-2-3]]

^<<v62-2-3,3>>^ Sabemos que o conhecemos, se obedecemos aos seus mandamentos.

[[v62-2-4]]

^<<v62-2-4,4>>^ Aquele que diz: "Eu o conheço", mas não obedece aos seus mandamentos, é mentiroso, e a verdade não está nele.

[[v62-2-5]]

^<<v62-2-5,5>>^ Mas, se alguém obedece à sua palavra, nele verdadeiramente o amor de Deus está aperfeiçoado. Desta forma sabemos que estamos nele:

[[v62-2-6]]

^<<v62-2-6,6>>^ aquele que afirma que permanece nele, deve andar como ele andou.

[[v62-2-7]]

^<<v62-2-7,7>>^ Amados, não lhes escrevo um mandamento novo, mas um mandamento antigo, que vocês têm desde o princípio: a mensagem que ouviram.

[[v62-2-8]]

^<<v62-2-8,8>>^ No entanto, eu lhes escrevo um mandamento novo, o qual é verdadeiro nele e em vocês, pois as trevas estão se dissipando e já brilha a verdadeira luz.

[[v62-2-9]]

^<<v62-2-9,9>>^ Quem afirma estar na luz mas odeia seu irmão, continua nas trevas.

[[v62-2-10]]

^<<v62-2-10,10>>^ Quem ama seu irmão permanece na luz, e nele não há causa de tropeço.

[[v62-2-11]]

^<<v62-2-11,11>>^ Mas quem odeia seu irmão está nas trevas e anda nas trevas; não sabe para onde vai, porque as trevas o cegaram.

[[v62-2-12]]

^<<v62-2-12,12>>^ Filhinhos, eu lhes escrevo porque os seus pecados foram perdoados, graças ao nome de Jesus.

[[v62-2-13]]

^<<v62-2-13,13>>^ Pais, eu lhes escrevo porque vocês conhecem aquele que é desde o princípio. Jovens, eu lhes escrevo porque venceram o Maligno.

[[v62-2-14]]

^<<v62-2-14,14>>^ Filhinhos, eu lhes escrevi porque vocês conhecem o Pai. Pais, eu lhes escrevi porque vocês conhecem aquele que é desde o princípio. Jovens, eu lhes escrevi, porque vocês são fortes, e em vocês a Palavra de Deus permanece e vocês venceram o Maligno.

[[v62-2-15]]

^<<v62-2-15,15>>^ Não amem o mundo nem o que nele há. Se alguém amar o mundo, o amor do Pai não está nele.

[[v62-2-16]]

^<<v62-2-16,16>>^ Pois tudo o que há no mundo — a cobiça da carne, a cobiça dos olhos e a ostentação dos bens — não provém do Pai, mas do mundo.

[[v62-2-17]]

^<<v62-2-17,17>>^ O mundo e a sua cobiça passam, mas aquele que faz a vontade de Deus permanece para sempre.

[[v62-2-18]]

^<<v62-2-18,18>>^ Filhinhos, esta é a última hora; e, assim como vocês ouviram que o anticristo está vindo, já agora muitos anticristos têm surgido. Por isso sabemos que esta é a última hora.

[[v62-2-19]]

^<<v62-2-19,19>>^ Eles saíram do nosso meio, mas na realidade não eram dos nossos, pois, se fossem dos nossos, teriam permanecido conosco; o fato de terem saído mostra que nenhum deles era dos nossos.

[[v62-2-20]]

^<<v62-2-20,20>>^ Mas vocês têm uma unção que procede do Santo, e todos vocês têm conhecimento.

[[v62-2-21]]

^<<v62-2-21,21>>^ Não lhes escrevo porque não conhecem a verdade, mas porque vocês a conhecem e porque nenhuma mentira procede da verdade.

[[v62-2-22]]

^<<v62-2-22,22>>^ Quem é o mentiroso, senão aquele que nega que Jesus é o Cristo? Este é o anticristo: aquele que nega o Pai e o Filho.

[[v62-2-23]]

^<<v62-2-23,23>>^ Todo o que nega o Filho também não tem o Pai; quem confessa publicamente o Filho tem também o Pai.

[[v62-2-24]]

^<<v62-2-24,24>>^ Quanto a vocês, cuidem para que aquilo que ouviram desde o princípio permaneça em vocês. Se o que ouviram desde o princípio permanecer em vocês, vocês também permanecerão no Filho e no Pai.

[[v62-2-25]]

^<<v62-2-25,25>>^ E esta é a promessa que ele nos fez: a vida eterna.

[[v62-2-26]]

^<<v62-2-26,26>>^ Escrevo-lhes estas coisas a respeito daqueles que os querem enganar.

[[v62-2-27]]

^<<v62-2-27,27>>^ Quanto a vocês, a unção que receberam dele permanece em vocês, e não precisam que alguém os ensine; mas, como a unção dele recebida, que é verdadeira e não falsa, os ensina acerca de todas as coisas, permaneçam nele como ele os ensinou.

[[v62-2-28]]

^<<v62-2-28,28>>^ Filhinhos, agora permaneçam nele para que, quando ele se manifestar, tenhamos confiança e não sejamos envergonhados diante dele na sua vinda.

[[v62-2-29]]

^<<v62-2-29,29>>^ Se vocês sabem que ele é justo, saibam também que todo aquele que pratica a justiça é nascido dele.

'''

xref:062-1-joao/062-1-joao-001.adoc#v62-1-0[&#60; Capítulo Anterior] | <<v62-2-0,Topo>> | xref:062-1-joao/062-1-joao-003.adoc#v62-3-0[Próximo Capítulo &#62;]