include::./index.adoc[]

[[v62-5-0]]
=== 1 João, 5
// nvi ?, NVI - Nova Versão Internacional

[[v62-5-1]]

^<<v62-5-1,1>>^ Todo aquele que crê que Jesus é o Cristo é nascido de Deus, e todo aquele que ama o Pai ama também ao que dele foi gerado.

[[v62-5-2]]

^<<v62-5-2,2>>^ Assim sabemos que amamos os filhos de Deus: amando a Deus e obedecendo aos seus mandamentos.

[[v62-5-3]]

^<<v62-5-3,3>>^ Porque nisto consiste o amor a Deus: obedecer aos seus mandamentos. E os seus mandamentos não são pesados.

[[v62-5-4]]

^<<v62-5-4,4>>^ O que é nascido de Deus vence o mundo; e esta é a vitória que vence o mundo: a nossa fé.

[[v62-5-5]]

^<<v62-5-5,5>>^ Quem é que vence o mundo? Somente aquele que crê que Jesus é o Filho de Deus.

[[v62-5-6]]

^<<v62-5-6,6>>^ Este é aquele que veio por meio de água e sangue, Jesus Cristo: não somente por água, mas por água e sangue. E o Espírito é quem dá testemunho, porque o Espírito é a verdade.

[[v62-5-7]]

^<<v62-5-7,7>>^ Há três que dão testemunho:

[[v62-5-8]]

^<<v62-5-8,8>>^ o Espírito, a água e o sangue; e os três são unânimes.

[[v62-5-9]]

^<<v62-5-9,9>>^ Nós aceitamos o testemunho dos homens, mas o testemunho de Deus tem maior valor, pois é o testemunho de Deus, que ele dá acerca de seu Filho.

[[v62-5-10]]

^<<v62-5-10,10>>^ Quem crê no Filho de Deus tem em si mesmo esse testemunho. Quem não crê em Deus o faz mentiroso, porque não crê no testemunho que Deus dá acerca de seu Filho.

[[v62-5-11]]

^<<v62-5-11,11>>^ E este é o testemunho: Deus nos deu a vida eterna, e essa vida está em seu Filho.

[[v62-5-12]]

^<<v62-5-12,12>>^ Quem tem o Filho, tem a vida; quem não tem o Filho de Deus, não tem a vida.

[[v62-5-13]]

^<<v62-5-13,13>>^ Escrevi-lhes estas coisas, a vocês que crêem no nome do Filho de Deus, para que vocês saibam que têm a vida eterna.

[[v62-5-14]]

^<<v62-5-14,14>>^ Esta é a confiança que temos ao nos aproximarmos de Deus: se pedirmos alguma coisa de acordo com a sua vontade, ele nos ouve.

[[v62-5-15]]

^<<v62-5-15,15>>^ E se sabemos que ele nos ouve em tudo o que pedimos, sabemos que temos o que dele pedimos.

[[v62-5-16]]

^<<v62-5-16,16>>^ Se alguém vir seu irmão cometer pecado que não leva à morte, ore, e Deus lhe dará vida. Refiro-me àqueles cujo pecado não leva à morte. Há pecado que leva à morte; não estou dizendo que se deva orar por este.

[[v62-5-17]]

^<<v62-5-17,17>>^ Toda injustiça é pecado, mas há pecado que não leva à morte.

[[v62-5-18]]

^<<v62-5-18,18>>^ Sabemos que todo aquele que é nascido de Deus não está no pecado; aquele que nasceu de Deus o protege, e o Maligno não o atinge.

[[v62-5-19]]

^<<v62-5-19,19>>^ Sabemos que somos de Deus e que o mundo todo está sob o poder do Maligno.

[[v62-5-20]]

^<<v62-5-20,20>>^ Sabemos também que o Filho de Deus veio e nos deu entendimento, para que conheçamos aquele que é o Verdadeiro. E nós estamos naquele que é o Verdadeiro, em seu Filho Jesus Cristo. Este é o verdadeiro Deus e a vida eterna.

[[v62-5-21]]

^<<v62-5-21,21>>^ Filhinhos, guardem-se dos ídolos.

'''

xref:062-1-joao/062-1-joao-004.adoc#v62-4-0[&#60; Capítulo Anterior] | <<v62-5-0,Topo>> | xref:063-2-joao/063-2-joao-001.adoc#v63-1-0[Próximo Capítulo &#62;]