include::./index.adoc[]

[[v62-1-0]]
=== 1 João, 1
// nvi ?, NVI - Nova Versão Internacional

[[v62-1-1]]

^<<v62-1-1,1>>^ O que era desde o princípio, o que ouvimos, o que vimos com os nossos olhos, o que contemplamos e as nossas mãos apalparam — isto proclamamos a respeito da Palavra da vida.

[[v62-1-2]]

^<<v62-1-2,2>>^ A vida se manifestou; nós a vimos e dela testemunhamos, e proclamamos a vocês a vida eterna, que estava com o Pai e nos foi manifestada.

[[v62-1-3]]

^<<v62-1-3,3>>^ Nós lhes proclamamos o que vimos e ouvimos para que vocês também tenham comunhão conosco. Nossa comunhão é com o Pai e com seu Filho Jesus Cristo.

[[v62-1-4]]

^<<v62-1-4,4>>^ Escrevemos estas coisas para que a nossa alegria seja completa.

[[v62-1-5]]

^<<v62-1-5,5>>^ Esta é a mensagem que dele ouvimos e transmitimos a vocês: Deus é luz; nele não há treva alguma.

[[v62-1-6]]

^<<v62-1-6,6>>^ Se afirmarmos que temos comunhão com ele, mas andamos nas trevas, mentimos e não praticamos a verdade.

[[v62-1-7]]

^<<v62-1-7,7>>^ Se, porém, andamos na luz, como ele está na luz, temos comunhão uns com os outros, e o sangue de Jesus, seu Filho, nos purifica de todo pecado.

[[v62-1-8]]

^<<v62-1-8,8>>^ Se afirmarmos que estamos sem pecado, enganamo-nos a nós mesmos, e a verdade não está em nós.

[[v62-1-9]]

^<<v62-1-9,9>>^ Se confessarmos os nossos pecados, ele é fiel e justo para perdoar os nossos pecados e nos purificar de toda injustiça.

[[v62-1-10]]

^<<v62-1-10,10>>^ Se afirmarmos que não temos cometido pecado, fazemos de Deus um mentiroso, e a sua palavra não está em nós.

'''

xref:061-2-pedro/061-2-pedro-003.adoc#v61-3-0[&#60; Capítulo Anterior] | <<v62-1-0,Topo>> | xref:062-1-joao/062-1-joao-002.adoc#v62-2-0[Próximo Capítulo &#62;]