include::./index.adoc[]

[[v62-4-0]]
=== 1 João, 4
// nvi ?, NVI - Nova Versão Internacional

[[v62-4-1]]

^<<v62-4-1,1>>^ Amados, não creiam em qualquer espírito, mas examinem os espíritos para ver se eles procedem de Deus, porque muitos falsos profetas têm saído pelo mundo.

[[v62-4-2]]

^<<v62-4-2,2>>^ Vocês podem reconhecer o Espírito de Deus deste modo: todo espírito que confessa que Jesus Cristo veio em carne procede de Deus;

[[v62-4-3]]

^<<v62-4-3,3>>^ mas todo espírito que não confessa a Jesus não procede de Deus. Esse é o espírito do anticristo, acerca do qual vocês ouviram que está vindo, e agora já está no mundo.

[[v62-4-4]]

^<<v62-4-4,4>>^ Filhinhos, vocês são de Deus e os venceram, porque aquele que está em vocês é maior do que aquele que está no mundo.

[[v62-4-5]]

^<<v62-4-5,5>>^ Eles vêm do mundo. Por isso o que falam procede do mundo, e o mundo os ouve.

[[v62-4-6]]

^<<v62-4-6,6>>^ Nós viemos de Deus, e todo aquele que conhece a Deus nos ouve; mas quem não vem de Deus não nos ouve. Dessa forma reconhecemos o Espírito da verdade e o espírito do erro.

[[v62-4-7]]

^<<v62-4-7,7>>^ Amados, amemo-nos uns aos outros, pois o amor procede de Deus. Aquele que ama é nascido de Deus e conhece a Deus.

[[v62-4-8]]

^<<v62-4-8,8>>^ Quem não ama não conhece a Deus, porque Deus é amor.

[[v62-4-9]]

^<<v62-4-9,9>>^ Foi assim que Deus manifestou o seu amor entre nós: enviou o seu Filho Unigênito ao mundo, para que pudéssemos viver por meio dele.

[[v62-4-10]]

^<<v62-4-10,10>>^ Nisto consiste o amor: não em que nós tenhamos amado a Deus, mas em que ele nos amou e enviou seu Filho como propiciação pelos nossos pecados.

[[v62-4-11]]

^<<v62-4-11,11>>^ Amados, visto que Deus assim nos amou, nós também devemos amar-nos uns aos outros.

[[v62-4-12]]

^<<v62-4-12,12>>^ Ninguém jamais viu a Deus; se nos amarmos uns aos outros, Deus permanece em nós, e o seu amor está aperfeiçoado em nós.

[[v62-4-13]]

^<<v62-4-13,13>>^ Sabemos que permanecemos nele, e ele em nós, porque ele nos deu do seu Espírito.

[[v62-4-14]]

^<<v62-4-14,14>>^ E vimos e testemunhamos que o Pai enviou seu Filho para ser o Salvador do mundo.

[[v62-4-15]]

^<<v62-4-15,15>>^ Se alguém confessa publicamente que Jesus é o Filho de Deus, Deus permanece nele, e ele em Deus.

[[v62-4-16]]

^<<v62-4-16,16>>^ Assim conhecemos o amor que Deus tem por nós e confiamos nesse amor. Deus é amor. Todo aquele que permanece no amor permanece em Deus, e Deus nele.

[[v62-4-17]]

^<<v62-4-17,17>>^ Dessa forma o amor está aperfeiçoado entre nós, para que no dia do juízo tenhamos confiança, porque neste mundo somos como ele.

[[v62-4-18]]

^<<v62-4-18,18>>^ No amor não há medo; pelo contrário o perfeito amor expulsa o medo, porque o medo supõe castigo. Aquele que tem medo não está aperfeiçoado no amor.

[[v62-4-19]]

^<<v62-4-19,19>>^ Nós amamos porque ele nos amou primeiro.

[[v62-4-20]]

^<<v62-4-20,20>>^ Se alguém afirmar: "Eu amo a Deus", mas odiar seu irmão, é mentiroso, pois quem não ama seu irmão, a quem vê, não pode amar a Deus, a quem não vê.

[[v62-4-21]]

^<<v62-4-21,21>>^ Ele nos deu este mandamento: Quem ama a Deus, ame também seu irmão.

'''

xref:062-1-joao/062-1-joao-003.adoc#v62-3-0[&#60; Capítulo Anterior] | <<v62-4-0,Topo>> | xref:062-1-joao/062-1-joao-005.adoc#v62-5-0[Próximo Capítulo &#62;]