include::./index.adoc[]

[[v16-11-0]]
=== Neemias, 11
// nvi ?, NVI - Nova Versão Internacional

[[v16-11-1]]

^<<v16-11-1,1>>^ Os líderes do povo passaram a morar em Jerusalém, e o restante do povo fez um sorteio para que, de cada dez pessoas, uma viesse morar em Jerusalém, a santa cidade; as outras nove deveriam ficar em suas próprias cidades.

[[v16-11-2]]

^<<v16-11-2,2>>^ O povo abençoou todos os homens que se apresentaram voluntariamente para morar em Jerusalém.

[[v16-11-3]]

^<<v16-11-3,3>>^ Alguns israelitas, sacerdotes, levitas, servos do templo e descendentes dos servos de Salomão viviam nas cidades de Judá, cada um em sua propriedade. Estes são os líderes da província que passaram a morar em Jerusalém;

[[v16-11-4]]

^<<v16-11-4,4>>^ além deles veio gente tanto de Judá quanto de Benjamim viver em Jerusalém. Dentre os descendentes de Judá: Ataías, filho de Uzias, neto de Zacarias, bisneto de Amarias; Amarias era filho de Sefatias e neto de Maalaleel, descendente de Perez.

[[v16-11-5]]

^<<v16-11-5,5>>^ Maaséias, filho de Baruque, neto de Col-Hozé, bisneto de Hazaías; Hazaías era filho de Adaías, neto de Joiaribe e bisneto de Zacarias, descendente de Selá.

[[v16-11-6]]

^<<v16-11-6,6>>^ Os descendentes de Perez que viviam em Jerusalém totalizavam 468 homens de destaque.

[[v16-11-7]]

^<<v16-11-7,7>>^ Dentre os descendentes de Benjamim: Salu, filho de Mesulão, neto de Joede, bisneto de Pedaías; Pedaías era filho de Colaías, neto de Maaséias, bisneto de Itiel, tataraneto de Jesaías;

[[v16-11-8]]

^<<v16-11-8,8>>^ os seguidores de Salu, Gabai e Salai totalizavam 928 homens.

[[v16-11-9]]

^<<v16-11-9,9>>^ Joel, filho de Zicri, era o oficial superior entre eles, e Judá, filho de Senua, era responsável pelo segundo distrito da cidade.

[[v16-11-10]]

^<<v16-11-10,10>>^ Dentre os sacerdotes: Jedaías; o filho de Joiaribe; Jaquim;

[[v16-11-11]]

^<<v16-11-11,11>>^ Seraías, filho de Hilquias, neto de Mesulão, bisneto de Zadoque; Zadoque era filho de Meraiote, neto de Aitube, supervisor na casa de Deus,

[[v16-11-12]]

^<<v16-11-12,12>>^ e seus colegas, que faziam o trabalho do templo totalizavam 822 homens. Adaías, filho de Jeroão, neto de Pelaías, bisneto de Anzi; Anzi que era filho de Zacarias, neto de Pasur, bisneto de Malquias,

[[v16-11-13]]

^<<v16-11-13,13>>^ e seus colegas, que eram chefes de famílias, totalizavam 242 homens. Amassai, filho de Azareel, neto de Azai, bisneto de Mesilemote, tataraneto de Imer,

[[v16-11-14]]

^<<v16-11-14,14>>^ e os seus colegas, que eram homens de destaque, totalizavam 128. O oficial superior deles era Zabdiel, filho de Gedolim.

[[v16-11-15]]

^<<v16-11-15,15>>^ Dentre os levitas: Semaías, filho de Hassube, neto de Azricão, bisneto de Hasabias, tataraneto de Buni;

[[v16-11-16]]

^<<v16-11-16,16>>^ Sabetai e Jozabade, dois dos líderes dos levitas, encarregados do trabalho externo do templo de Deus;

[[v16-11-17]]

^<<v16-11-17,17>>^ Matanias, filho de Mica, neto de Zabdi, bisneto de Asafe, o dirigente que conduzia as ações de graça e as orações; Bacbuquias, o segundo entre os seus colegas; e Abda, filho de Samua, neto de Galal, bisneto de Jedutum.

[[v16-11-18]]

^<<v16-11-18,18>>^ Os levitas totalizavam 284 na cidade santa.

[[v16-11-19]]

^<<v16-11-19,19>>^ Os porteiros: Acube, Talmom e os homens dos seus clãs; eram 172 homens que guardavam as portas.

[[v16-11-20]]

^<<v16-11-20,20>>^ Os demais israelitas, incluindo os sacerdotes e os levitas, estavam em todas as cidades de Judá, cada um na propriedade de sua herança.

[[v16-11-21]]

^<<v16-11-21,21>>^ Os que prestavam serviço no templo moravam na colina de Ofel, e Zia e Gispa estavam encarregados deles.

[[v16-11-22]]

^<<v16-11-22,22>>^ O oficial superior dos levitas em Jerusalém era Uzi, filho de Bani, neto de Hasabias, bisneto de Matanias, tataraneto de Mica. Uzi era um dos descendentes de Asafe, que eram responsáveis pela música do templo de Deus.

[[v16-11-23]]

^<<v16-11-23,23>>^ Eles estavam sujeitos às prescrições do rei, que regulamentavam suas atividades diárias.

[[v16-11-24]]

^<<v16-11-24,24>>^ Petaías, filho de Mesezabeel, descendente de Zerá, filho de Judá, representavam o rei nas questões de ordem civil.

[[v16-11-25]]

^<<v16-11-25,25>>^ Alguns do povo de Judá foram morar em Quiriate-Arba e em seus povoados ao redor, em Dibom e seus povoados, em Jecabzeel e seus povoados,

[[v16-11-26]]

^<<v16-11-26,26>>^ em Jesua, em Moladá, em Bete-Pelete,

[[v16-11-27]]

^<<v16-11-27,27>>^ em Hazar-Sual, em Berseba e seus povoados,

[[v16-11-28]]

^<<v16-11-28,28>>^ em Ziclague, em Meconá e seus povoados,

[[v16-11-29]]

^<<v16-11-29,29>>^ em En-Rimom, em Zorá, em Jarmute,

[[v16-11-30]]

^<<v16-11-30,30>>^ em Zanoa, em Adulão e em seus povoados, em Láquis e seus arredores, e em Azeca e seus povoados. Eles se estabeleceram desde Berseba até o vale de Hinom.

[[v16-11-31]]

^<<v16-11-31,31>>^ Os descendentes dos benjamitas foram viver em Geba, Micmás, Aia, Betel e seus povoados,

[[v16-11-32]]

^<<v16-11-32,32>>^ em Anatote, Nobe e Ananias,

[[v16-11-33]]

^<<v16-11-33,33>>^ Hazor, Ramá e Gitaim,

[[v16-11-34]]

^<<v16-11-34,34>>^ Hadide, Zeboim e Nebalate,

[[v16-11-35]]

^<<v16-11-35,35>>^ Lode e Ono, e no vale dos Artesãos.

[[v16-11-36]]

^<<v16-11-36,36>>^ Alguns grupos dos levitas de Judá se estabeleceram em Benjamim.

'''

xref:016-neemias/016-neemias-010.adoc#v16-10-0[&#60; Capítulo Anterior] | <<v16-11-0,Topo>> | xref:016-neemias/016-neemias-012.adoc#v16-12-0[Próximo Capítulo &#62;]