include::./index.adoc[]

[[v16-6-0]]
=== Neemias, 6
// nvi ?, NVI - Nova Versão Internacional

[[v16-6-1]]

^<<v16-6-1,1>>^ Quando Sambalate, Tobias, Gesém, o árabe, e o restante de nossos inimigos souberam que eu havia reconstruído o muro e que não havia ficado nenhuma brecha, embora até então eu ainda não tivesse colocado as portas nos seus lugares,

[[v16-6-2]]

^<<v16-6-2,2>>^ Sambalate e Gesém mandaram-me a seguinte mensagem: "Venha, vamos nos encontrar num dos povoados da planície de Ono". Eles, contudo, estavam tramando fazer-me mal;

[[v16-6-3]]

^<<v16-6-3,3>>^ por isso enviei-lhes mensageiros com esta resposta: "Estou executando um grande projeto e não posso descer. Por que parar a obra para ir encontrar-me com vocês? "

[[v16-6-4]]

^<<v16-6-4,4>>^ Eles me mandaram quatro vezes a mesma mensagem, e em todas elas dei-lhes a mesma resposta.

[[v16-6-5]]

^<<v16-6-5,5>>^ Então, na quinta vez, Sambalate mandou-me um dos seus homens de confiança com a mesma mensagem; ele tinha na mão uma carta aberta

[[v16-6-6]]

^<<v16-6-6,6>>^ em que estava escrito: "Dizem entre as nações, e Gesém diz que é verdade, que você e os judeus estão tramando uma revolta e que, por isso, estão reconstruindo o muro. Além do mais, conforme dizem, você está na iminência de se tornar o rei deles,

[[v16-6-7]]

^<<v16-6-7,7>>^ e até nomeou profetas para fazerem em Jerusalém a seguinte proclamação a seu respeito: ‘Há um rei em Judá! ’ Ora, essa informação será levada ao rei; por isso, vamos conversar".

[[v16-6-8]]

^<<v16-6-8,8>>^ Eu lhe mandei esta resposta: Nada disso que você diz está acontecendo; é pura invenção da sua cabeça.

[[v16-6-9]]

^<<v16-6-9,9>>^ Estavam todos tentando intimidar-nos, pensando: "Eles serão enfraquecidos e não concluirão a obra". Eu, porém, orei: Agora, fortalece as minhas mãos!

[[v16-6-10]]

^<<v16-6-10,10>>^ Um dia fui à casa de Semaías, filho de Delaías, neto de Meetabel, que estava trancado portas adentro. Ele disse: "Vamos encontrar-nos na casa de Deus, no templo, a portas fechadas, pois estão querendo matá-lo; eles virão esta noite".

[[v16-6-11]]

^<<v16-6-11,11>>^ Todavia, eu lhe respondi: Acha que um homem como eu deveria fugir? Alguém como eu deveria entrar no templo para salvar a vida? Não, eu não irei!

[[v16-6-12]]

^<<v16-6-12,12>>^ Percebi que Deus não o tinha enviado, e que ele tinha profetizado contra mim porque Tobias e Sambalate o tinham contratado.

[[v16-6-13]]

^<<v16-6-13,13>>^ Ele tinha sido pago para me intimidar, a fim de que eu cometesse um pecado agindo assim, e então eles poderiam difamar-me e desacreditar-me.

[[v16-6-14]]

^<<v16-6-14,14>>^ Lembra-te do que fizeram Tobias e Sambalate, meu Deus, lembra-te também da profetisa Noadia e do restante dos profetas que estão tentando me intimidar.

[[v16-6-15]]

^<<v16-6-15,15>>^ O muro ficou pronto no dia vinte e cinco de elul, em cinqüenta e dois dias.

[[v16-6-16]]

^<<v16-6-16,16>>^ Quando todos os nossos inimigos souberam disso, todas as nações vizinhas ficaram atemorizadas e abateu-se o seu orgulho, pois perceberam que essa obra havia sido executada com a ajuda de nosso Deus.

[[v16-6-17]]

^<<v16-6-17,17>>^ E também, naqueles dias, os nobres de Judá estavam enviando muitas cartas a Tobias, que lhes enviava suas respostas.

[[v16-6-18]]

^<<v16-6-18,18>>^ Porque muitos de Judá estavam comprometidos com ele por juramento, visto que era genro de Secanias, filho de Ara, e seu filho Joanã havia se casado com a filha de Mesulão, neto de Berequias.

[[v16-6-19]]

^<<v16-6-19,19>>^ Até ousavam elogiá-lo na minha presença e iam contar-lhe o que eu dizia. E Tobias continuou a enviar-me cartas para me intimidar.

'''

xref:016-neemias/016-neemias-005.adoc#v16-5-0[&#60; Capítulo Anterior] | <<v16-6-0,Topo>> | xref:016-neemias/016-neemias-007.adoc#v16-7-0[Próximo Capítulo &#62;]