include::./index.adoc[]

[[v16-12-0]]
=== Neemias, 12
// nvi ?, NVI - Nova Versão Internacional

[[v16-12-1]]

^<<v16-12-1,1>>^ Estes foram os sacerdotes e os levitas que voltaram com Zorobabel, filho de Sealtiel, e com Jesua: Seraías, Jeremias, Esdras,

[[v16-12-2]]

^<<v16-12-2,2>>^ Amarias, Maluque, Hatus,

[[v16-12-3]]

^<<v16-12-3,3>>^ Secanias, Reum, Meremote,

[[v16-12-4]]

^<<v16-12-4,4>>^ Ido, Ginetom, Abias,

[[v16-12-5]]

^<<v16-12-5,5>>^ Miamim, Maadias, Bilga,

[[v16-12-6]]

^<<v16-12-6,6>>^ Semaías, Joiaribe, Jedaías,

[[v16-12-7]]

^<<v16-12-7,7>>^ Salu, Amoque, Hilquias e Jedaías. Esses foram os chefes dos sacerdotes e seus colegas nos dias de Jesua.

[[v16-12-8]]

^<<v16-12-8,8>>^ Os levitas foram Jesua, Binui, Cadmiel, Serebias, Judá, e também Matanias, que, junto com seus colegas, estava encarregado dos cânticos de ações de graças.

[[v16-12-9]]

^<<v16-12-9,9>>^ Bacbuquias e Uni, colegas deles, ficavam em frente deles para responder-lhes.

[[v16-12-10]]

^<<v16-12-10,10>>^ Jesua foi o pai de Joiaquim, Joiaquim foi o pai de Eliasibe, Eliasibe foi o pai de Joiada,

[[v16-12-11]]

^<<v16-12-11,11>>^ Joiada foi o pai de Jônatas, Jônatas foi o pai de Jadua.

[[v16-12-12]]

^<<v16-12-12,12>>^ Nos dias de Joiaquim estes foram os líderes das famílias dos sacerdotes: da família de Seraías, Meraías; da família de Jeremias, Hananias;

[[v16-12-13]]

^<<v16-12-13,13>>^ da família de Esdras, Mesulão; da família de Amarias, Joanã;

[[v16-12-14]]

^<<v16-12-14,14>>^ da família de Maluqui, Jônatas; da família de Secanias, José;

[[v16-12-15]]

^<<v16-12-15,15>>^ da família de Harim, Adna; da família de Meremote, Helcai;

[[v16-12-16]]

^<<v16-12-16,16>>^ da família de Ido, Zacarias; da família de Ginetom, Mesulão;

[[v16-12-17]]

^<<v16-12-17,17>>^ da família de Abias, Zicri; da família de Miniamim e de Maadias, Piltai;

[[v16-12-18]]

^<<v16-12-18,18>>^ da família de Bilga, Samua; da família de Semaías, Jônatas;

[[v16-12-19]]

^<<v16-12-19,19>>^ da família de Joiaribe, Matenai; da família de Jedaías, Uzi;

[[v16-12-20]]

^<<v16-12-20,20>>^ da família de Salai, Calai; da família de Amoque, Héber;

[[v16-12-21]]

^<<v16-12-21,21>>^ da família de Hilquias, Hasabias; da família de Jedaías, Natanael.

[[v16-12-22]]

^<<v16-12-22,22>>^ Os chefes das famílias dos levitas e dos sacerdotes, nos dias de Eliasibe, Joiada, Joanã e Jadua, foram registrados no reinado de Dario, o persa.

[[v16-12-23]]

^<<v16-12-23,23>>^ Os chefes das famílias dos descendentes de Levi até à época de Joanã, filho de Eliasibe, foram registrados no livro das crônicas.

[[v16-12-24]]

^<<v16-12-24,24>>^ Os líderes dos levitas foram Hasabias, Serebias, Jesua, filho de Cadmiel, e seus colegas, que ficavam em frente deles quando entoavam louvores e ações de graças; um grupo respondia ao outro, conforme prescrito por Davi, homem de Deus.

[[v16-12-25]]

^<<v16-12-25,25>>^ Matanias, Bacbuquias, Obadias, Mesulão, Talmom e Acube eram porteiros; vigiavam os depósitos junto às portas.

[[v16-12-26]]

^<<v16-12-26,26>>^ Eles serviram nos dias de Joiaquim, filho de Jesua, neto de Jozadaque, e nos dias do governador Neemias e de Esdras, sacerdote e escriba.

[[v16-12-27]]

^<<v16-12-27,27>>^ Por ocasião da dedicação dos muros de Jerusalém, os levitas foram procurados e trazidos de onde moravam para Jerusalém para celebrarem a dedicação alegremente, com cânticos e ações de graças, ao som de címbalos, harpas e liras.

[[v16-12-28]]

^<<v16-12-28,28>>^ Os cantores foram trazidos dos arredores de Jerusalém, dos povoados dos netofatitas,

[[v16-12-29]]

^<<v16-12-29,29>>^ de Bete-Gilgal, e da região de Geba e Azmavete, pois os cantores haviam construído povoados para si ao redor de Jerusalém.

[[v16-12-30]]

^<<v16-12-30,30>>^ Os sacerdotes e os levitas se purificaram cerimonialmente, e depois purificaram também o povo, as portas e os muros.

[[v16-12-31]]

^<<v16-12-31,31>>^ Ordenei aos líderes de Judá que subissem ao alto do muro. Também designei dois grandes coros para darem graças. Um deles avançou em cima do muro, para a direita, até à porta do Esterco.

[[v16-12-32]]

^<<v16-12-32,32>>^ Hosaías e metade dos líderes de Judá os seguiram,

[[v16-12-33]]

^<<v16-12-33,33>>^ e mais Azarias, Esdras, Mesulão,

[[v16-12-34]]

^<<v16-12-34,34>>^ Judá, Benjamim, Semaías, Jeremias,

[[v16-12-35]]

^<<v16-12-35,35>>^ bem como alguns sacerdotes com trombetas, além de Zacarias, filho de Jônatas, neto de Semaías, bisneto de Matanias, que era filho de Micaías, neto de Zacur, bisneto de Asafe,

[[v16-12-36]]

^<<v16-12-36,36>>^ e seus colegas, Semaías, Azareel, Milalai, Gilalai, Maai, Natanael, Judá e Hanani, que tocavam os instrumentos musicais prescritos por Davi, homem de Deus. Esdras, o escriba, ia na frente deles.

[[v16-12-37]]

^<<v16-12-37,37>>^ À porta da Fonte eles subiram diretamente os degraus da cidade de Davi, na subida para o muro, e passaram sobre a casa de Davi até à porta das Águas, a leste.

[[v16-12-38]]

^<<v16-12-38,38>>^ O segundo coro avançou no sentido oposto. Eu os acompanhei, quando iam sobre o muro, levando comigo a metade do povo; passamos pela torre dos Fornos até à porta Larga,

[[v16-12-39]]

^<<v16-12-39,39>>^ sobre a porta de Efraim, a porta Jesaná, a porta do Peixe, a torre de Hananeel e a torre dos Cem, indo até à porta das Ovelhas. Junto à porta da Guarda eles pararam.

[[v16-12-40]]

^<<v16-12-40,40>>^ Então, os dois coros encarregados das ações de graças, assumiram os seus lugares no templo de Deus, o que também fiz eu acompanhado da metade dos oficiais,

[[v16-12-41]]

^<<v16-12-41,41>>^ e também dos sacerdotes Eliaquim, Maaséias, Miniamim, Micaías, Elioenai, Zacarias e Hananias, com suas trombetas

[[v16-12-42]]

^<<v16-12-42,42>>^ e também de Maaséias, Semaías, Eleazar, Uzi, Joanã, Malquias, Elão e Ézer. Os coros cantaram sob a direção de Jezraías.

[[v16-12-43]]

^<<v16-12-43,43>>^ E naquele dia contentes ofereceram grandes sacrifícios, pois Deus lhes enchera de grande alegria. As mulheres e as crianças também se alegravam, e os sons da alegria de Jerusalém podiam ser ouvidos de longe.

[[v16-12-44]]

^<<v16-12-44,44>>^ Naquela ocasião foram designados alguns encarregados dos depósitos onde se recebiam as contribuições gerais, os primeiros frutos e os dízimos. Das lavouras que havia em torno das cidades eles deviam trazer para os depósitos as porções exigidas pela Lei para os sacerdotes e os levitas. E, de fato, o povo de Judá estava satisfeito com os sacerdotes e os levitas que ministravam no templo.

[[v16-12-45]]

^<<v16-12-45,45>>^ Eles celebravam o culto ao seu Deus e o ritual de purificação, dos quais também participavam os cantores e os porteiros, de acordo com as ordens de Davi e do seu filho Salomão.

[[v16-12-46]]

^<<v16-12-46,46>>^ Pois muito tempo antes, nos dias de Davi e de Asafe, havia dirigentes dos cantores e que dirigiam os cânticos de louvor e de graças a Deus.

[[v16-12-47]]

^<<v16-12-47,47>>^ Sucedeu, pois, que nos dias de Zorobabel e de Neemias, todo o Israel contribuía com ofertas diárias para os cantores e para os porteiros, além de separar a parte dos outros levitas, e os levitas separavam a porção dos descendentes de Arão.

'''

xref:016-neemias/016-neemias-011.adoc#v16-11-0[&#60; Capítulo Anterior] | <<v16-12-0,Topo>> | xref:016-neemias/016-neemias-013.adoc#v16-13-0[Próximo Capítulo &#62;]