include::./index.adoc[]

[[v16-2-0]]
=== Neemias, 2
// nvi ?, NVI - Nova Versão Internacional

[[v16-2-1]]

^<<v16-2-1,1>>^ No mês de nisã do vigésimo ano do rei Artaxerxes, na hora de servir-lhe o vinho, levei-o ao rei. Nunca antes eu tinha estado triste na presença dele;

[[v16-2-2]]

^<<v16-2-2,2>>^ Por isso o rei me perguntou: "Por que o seu rosto parece tão triste, se você não está doente? Essa tristeza só, pode ser do coração! " Com muito medo,

[[v16-2-3]]

^<<v16-2-3,3>>^ eu disse ao rei: "Que o rei viva para sempre! Como não estaria triste o meu rosto, se a cidade em que estão sepultados os meus pais está em ruínas, e as suas portas foram destruídas pelo fogo? "

[[v16-2-4]]

^<<v16-2-4,4>>^ O rei me disse: "O que você gostaria de pedir? " Então orei ao Deus dos céus,

[[v16-2-5]]

^<<v16-2-5,5>>^ e respondi ao rei: "Se for do agrado do rei e se o seu servo puder contar com a benevolência do rei, que ele me deixe ir à cidade de Judá onde meus pais estão enterrados, para que eu possa reconstruí-la".

[[v16-2-6]]

^<<v16-2-6,6>>^ Então o rei, com a rainha sentada ao seu lado, perguntou-me: "Quanto tempo levará a viagem? Quando você voltará? " Marquei um prazo com o rei, e ele concordou que eu fosse.

[[v16-2-7]]

^<<v16-2-7,7>>^ E a seguir acrescentei: Se for do agrado do rei, que me dê cartas aos governadores do Trans-Eufrates para que me deixem passar até chegar a Judá.

[[v16-2-8]]

^<<v16-2-8,8>>^ Que me dê também uma carta para Asafe, guarda da floresta do rei, para que ele me forneça madeira para as vigas das portas da cidadela que fica junto ao templo, do muro da cidade e da residência que irei ocupar. Visto que a bondosa mão de Deus estava sobre mim, o rei atendeu os meus pedidos.

[[v16-2-9]]

^<<v16-2-9,9>>^ Com isso fui aos governadores do Trans-Eufrates e lhes entreguei as cartas do rei. O rei fez-me acompanhar uma escolta de oficiais do exército e de cavaleiros.

[[v16-2-10]]

^<<v16-2-10,10>>^ Sambalate, o horonita, e Tobias, o oficial amonita, ficaram muito irritados quando que alguém estava interessado no bem dos israelitas.

[[v16-2-11]]

^<<v16-2-11,11>>^ Cheguei a Jerusalém e, depois de três dias de permanência ali,

[[v16-2-12]]

^<<v16-2-12,12>>^ saí de noite com alguns dos meus amigos. Eu não havia contado a ninguém o que o meu Deus havia posto em meu coração que eu fizesse por Jerusalém. Não levava nenhum outro animal além daquele em que eu estava montado.

[[v16-2-13]]

^<<v16-2-13,13>>^ De noite saí pela porta do Vale na direção da fonte do Dragão e da porta do Esterco, examinando o muro de Jerusalém que havia sido derrubado, e suas portas, que haviam sido destruídas pelo fogo.

[[v16-2-14]]

^<<v16-2-14,14>>^ Fui até a porta da Fonte e do tanque do rei, mas ali não havia espaço para o meu animal passar;

[[v16-2-15]]

^<<v16-2-15,15>>^ por isso subi o vale, de noite, examinando o muro. Finalmente voltei e tornei a entrar pela porta do Vale.

[[v16-2-16]]

^<<v16-2-16,16>>^ Os oficiais não sabiam aonde eu tinha ido ou o que eu estava fazendo, pois até então eu não tinha dito nada aos judeus, aos sacerdotes, aos nobres, aos oficiais e aos outros que iriam realizar a obra.

[[v16-2-17]]

^<<v16-2-17,17>>^ Então eu lhes disse: Vocês estão vendo a situação terrível em que estamos: Jerusalém está em ruínas, e suas portas foram destruídas pelo fogo. Venham, vamos reconstruir o muro de Jerusalém, para que não fiquemos mais nesta situação humilhante.

[[v16-2-18]]

^<<v16-2-18,18>>^ Também lhes contei como Deus tinha sido bondoso comigo e o que o rei me tinha dito. Eles responderam: "Sim, vamos começar a reconstrução". E se encorajaram para esse bom projeto.

[[v16-2-19]]

^<<v16-2-19,19>>^ Quando, porém, Sambalate, o horonita, Tobias, o oficial amonita, e Gesém, o árabe, souberam disso, zombaram de nós, desprezaram-nos e perguntaram: "O que é isso que vocês estão fazendo? Estão se rebelando contra o rei? "

[[v16-2-20]]

^<<v16-2-20,20>>^ Eu lhes respondi: O Deus dos céus fará que sejamos bem sucedidos. Nós, os seus servos, começaremos a reconstrução, mas, no que lhes diz respeito, vocês não têm parte nem direito legal sobre Jerusalém, e em sua história não há nada de memorável que favoreça vocês!

'''

xref:016-neemias/016-neemias-001.adoc#v16-1-0[&#60; Capítulo Anterior] | <<v16-2-0,Topo>> | xref:016-neemias/016-neemias-003.adoc#v16-3-0[Próximo Capítulo &#62;]