include::./index.adoc[]

[[v16-3-0]]
=== Neemias, 3
// nvi ?, NVI - Nova Versão Internacional

[[v16-3-1]]

^<<v16-3-1,1>>^ O sumo sacerdote Eliasibe e os seus colegas sacerdotes começaram o seu trabalho e reconstruíram a porta das Ovelhas. Eles a consagraram e colocaram as portas no lugar. Depois construíram o muro até a torre dos Cem, que consagraram, e até a torre de Hananeel.

[[v16-3-2]]

^<<v16-3-2,2>>^ Os homens de Jericó construíram o trecho seguinte, e Zacur, filho de Inri, construiu logo adiante.

[[v16-3-3]]

^<<v16-3-3,3>>^ A porta do Peixe foi reconstruída pelos filhos de Hassenaá. Eles puseram as vigas e colocaram as portas, os ferrolhos e as trancas no lugar.

[[v16-3-4]]

^<<v16-3-4,4>>^ Meremote, filho de Urias, neto de Coz, fez os reparos do trecho seguinte. Ao lado dele Mesulão, filho de Berequias, neto de Mesezabel, fez os reparos, e ao lado dele Zadoque, filho de Baaná, também fez os reparos.

[[v16-3-5]]

^<<v16-3-5,5>>^ O trecho seguinte foi reparado pelos homens de Tecoa, mas os nobres dessa cidade não quiseram se juntar ao serviço, rejeitando a orientação de seus supervisores.

[[v16-3-6]]

^<<v16-3-6,6>>^ A porta Jesaná foi consertada por Joiada, filho de Paséia, e por Mesulão, filho de Besodias. Eles puseram as vigas e colocaram as portas, os ferrolhos e as trancas no lugar.

[[v16-3-7]]

^<<v16-3-7,7>>^ No trecho seguinte, os reparos foram feitos por homens de Gibeom e de Mispá, Melatias de Gibeom e Jadom de Meronote, locais que estavam sob a autoridade do governador da província do Trans-Eufrates.

[[v16-3-8]]

^<<v16-3-8,8>>^ Uziel, filho de Haraías, um dos ourives, fez os reparos do trecho seguinte; e Hananias, um dos perfumistas, fez os reparos ao seu lado. Eles resconstruíram Jerusalém até o muro Largo.

[[v16-3-9]]

^<<v16-3-9,9>>^ Refaías, filho de Hur, governador da metade do distrito de Jerusalém, fez os reparos do trecho seguinte.

[[v16-3-10]]

^<<v16-3-10,10>>^ Ao seu lado, Jedaías, filho de Harumafe, fez os reparos em frente da sua casa, e Hatus, filho de Hasabnéias, fez os reparos ao lado dele.

[[v16-3-11]]

^<<v16-3-11,11>>^ Malquias, filho de Harim, e Hassube, filho de Paate-Moabe, repararam outro trecho e a torre dos Fornos.

[[v16-3-12]]

^<<v16-3-12,12>>^ Salum, filho de Haloés, governador da outra metade do distrito de Jerusalém, fez os reparos do trecho seguinte com a ajuda de suas filhas.

[[v16-3-13]]

^<<v16-3-13,13>>^ A porta do Vale foi reparada por Hanum e pelos moradores de Zanoa. Eles a reconstruíram e colocaram as portas, os ferrolhos e as trancas no lugar. Também repararam quatrocentos e cinqüenta metros do muro, até a porta do Esterco.

[[v16-3-14]]

^<<v16-3-14,14>>^ A porta do Esterco foi reparada por Malquias, filho de Recabe, governador do distrito de Bete-Haquerém. Ele a reconstruiu e colocou as portas, os ferrolhos e as trancas no lugar.

[[v16-3-15]]

^<<v16-3-15,15>>^ A porta da Fonte foi reparada por Salum, filho de Col-Hozé, governador do distrito de Mispá. Ele a reconstruiu, a cobriu e colocou as portas, os ferrolhos e as trancas no lugar. Também fez os reparos do muro do tanque de Siloé, junto ao jardim do Rei, até aos degraus que descem da cidade de Davi.

[[v16-3-16]]

^<<v16-3-16,16>>^ Além dele, Neemias, filho de Azbuque, governador de meio distrito de Bete-Zur, fez os reparos até em frente dos túmulos de Davi, até o açude artificial e a casa dos soldados.

[[v16-3-17]]

^<<v16-3-17,17>>^ Depois dele os reparos foram feitos pelos levitas que estavam sob a responsabilidade de Reum, filho de Bani. Junto a ele Hasabias, governador de meio distrito de Queila, fez os reparos em seu distrito.

[[v16-3-18]]

^<<v16-3-18,18>>^ Depois dele os reparos foram feitos pelos seus compatriotas que estavam sob a responsabilidade de Binui, filho de Henadade, governador de meio distrito de Queila.

[[v16-3-19]]

^<<v16-3-19,19>>^ Ao seu lado Ézer, filho de Jesua, governador de Mispá, reconstruiu outro trecho, começando de um ponto que fica em frente da subida para a casa das armas, indo até à esquina do muro.

[[v16-3-20]]

^<<v16-3-20,20>>^ Depois dele Baruque, filho de Zabai, reparou com zelo outro trecho, desde a esquina do muro até à entrada da casa do sumo sacerdote Eliasibe.

[[v16-3-21]]

^<<v16-3-21,21>>^ Em seguida Meremote, filho de Urias, neto de Coz, reparou outro trecho, desde a entrada da casa de Eliasibe até o fim dela.

[[v16-3-22]]

^<<v16-3-22,22>>^ Os demais reparos foram feitos pelos sacerdotes das redondezas.

[[v16-3-23]]

^<<v16-3-23,23>>^ Depois, Benjamim e Hassube fizeram os reparos em frente da sua casa; e ao lado deles Azarias, filho de Maaséias, filho de Ananias, fez os reparos ao lado de sua casa.

[[v16-3-24]]

^<<v16-3-24,24>>^ Depois dele, Binui, filho de Henadade, reparou outro trecho, desde a casa de Azarias até à esquina do muro,

[[v16-3-25]]

^<<v16-3-25,25>>^ e Palal, filho de Uzai, trabalhou em frente da esquina do muro e da torre que sai do palácio superior, perto do pátio da guarda. Junto a ele, Pedaías, filho de Parós,

[[v16-3-26]]

^<<v16-3-26,26>>^ e os servos do templo que viviam na colina de Ofel fizeram os reparos até em frente da porta das Águas, na direção do leste e da torre que ali sobressaía.

[[v16-3-27]]

^<<v16-3-27,27>>^ Depois dele os homens de Tecoa repararam outro trecho, desde a grande torre até o muro de Ofel.

[[v16-3-28]]

^<<v16-3-28,28>>^ Acima da porta dos Cavalos, os sacerdotes fizeram os reparos, cada um em frente da sua própria casa.

[[v16-3-29]]

^<<v16-3-29,29>>^ Depois deles Zadoque, filho de Imer, fez os reparos em frente da sua casa. Ao seu lado Semaías, filho de Secanias, o guarda da porta Oriental, fez os reparos.

[[v16-3-30]]

^<<v16-3-30,30>>^ Depois, Hananias, filho de Selemias, e Hanum, filho de Zalafe, fez os reparos do outro trecho. Ao seu lado, Mesulão, filho de Berequias, fez os reparos em frente da sua moradia.

[[v16-3-31]]

^<<v16-3-31,31>>^ Depois dele, Malquias, um ourives, fez os reparos do muro até à casa dos servos do templo e dos comerciantes, em frente à porta da Inspeção, até o posto de vigia da esquina;

[[v16-3-32]]

^<<v16-3-32,32>>^ e entre a sala acima da esquina e a porta das Ovelhas os ourives e os comerciantes fizeram os reparos.

'''

xref:016-neemias/016-neemias-002.adoc#v16-2-0[&#60; Capítulo Anterior] | <<v16-3-0,Topo>> | xref:016-neemias/016-neemias-004.adoc#v16-4-0[Próximo Capítulo &#62;]