include::./index.adoc[]

[[v16-10-0]]
=== Neemias, 10
// nvi ?, NVI - Nova Versão Internacional

[[v16-10-1]]

^<<v16-10-1,1>>^ Esta é a relação dos que o assinaram: Neemias, o governador, filho de Hacalias, e Zedequias,

[[v16-10-2]]

^<<v16-10-2,2>>^ Seraías, Azarias, Jeremias,

[[v16-10-3]]

^<<v16-10-3,3>>^ Pasur, Amarias, Malquias,

[[v16-10-4]]

^<<v16-10-4,4>>^ Hatus, Sebanias, Maluque,

[[v16-10-5]]

^<<v16-10-5,5>>^ Harim, Meremote, Obadias,

[[v16-10-6]]

^<<v16-10-6,6>>^ Daniel, Ginetom, Baruque,

[[v16-10-7]]

^<<v16-10-7,7>>^ Mesulão, Abias, Miamim,

[[v16-10-8]]

^<<v16-10-8,8>>^ Maazias, Bilgai e Semaías. Esses eram sacerdotes.

[[v16-10-9]]

^<<v16-10-9,9>>^ Dos levitas: Jesua, filho de Azanias, Binui, dos filhos de Henadade, Cadmiel

[[v16-10-10]]

^<<v16-10-10,10>>^ e seus colegas: Sebanias, Hodias, Quelita, Pelaías, Hanã,

[[v16-10-11]]

^<<v16-10-11,11>>^ Mica, Reobe, Hasabias,

[[v16-10-12]]

^<<v16-10-12,12>>^ Zacur, Serebias, Sebanias,

[[v16-10-13]]

^<<v16-10-13,13>>^ Hodias, Bani e Beninu.

[[v16-10-14]]

^<<v16-10-14,14>>^ Dos líderes do povo: Parós, Paate-Moabe, Elão, Zatu, Bani,

[[v16-10-15]]

^<<v16-10-15,15>>^ Buni, Azgade, Bebai,

[[v16-10-16]]

^<<v16-10-16,16>>^ Adonias, Bigvai, Adim,

[[v16-10-17]]

^<<v16-10-17,17>>^ Ater, Ezequias, Azur,

[[v16-10-18]]

^<<v16-10-18,18>>^ Hodias, Hasum, Besai,

[[v16-10-19]]

^<<v16-10-19,19>>^ Harife, Anatote, Nebai,

[[v16-10-20]]

^<<v16-10-20,20>>^ Magpias, Mesulão, Hezir,

[[v16-10-21]]

^<<v16-10-21,21>>^ Mesezabeel, Zadoque, Jadua,

[[v16-10-22]]

^<<v16-10-22,22>>^ Pelatias, Hanã, Anaías,

[[v16-10-23]]

^<<v16-10-23,23>>^ Oséias, Hananias, Hassube,

[[v16-10-24]]

^<<v16-10-24,24>>^ Haloés, Pílea, Sobeque,

[[v16-10-25]]

^<<v16-10-25,25>>^ Reum, Hasabna, Maaséias,

[[v16-10-26]]

^<<v16-10-26,26>>^ Aías, Hanã, Anã,

[[v16-10-27]]

^<<v16-10-27,27>>^ Maluque, Harim e Baaná.

[[v16-10-28]]

^<<v16-10-28,28>>^ "O restante do povo: sacerdotes, levitas, porteiros, cantores, servidores do templo e todos os que se separaram dos povos vizinhos por amor à Lei de Deus, juntamente com suas mulheres e com todos os seus filhos e filhas que eram capazes de entender,

[[v16-10-29]]

^<<v16-10-29,29>>^ agora se unem aos seus irmãos, os nobres, e se obrigam sob maldição e sob juramento a seguir a Lei de Deus dada por meio do servo de Deus Moisés e a obedecer fielmente a todos os mandamentos, ordenanças e decretos do Senhor, o nosso Senhor.

[[v16-10-30]]

^<<v16-10-30,30>>^ "Prometemos não dar nossas filhas em casamento aos povos vizinhos nem aceitar que as filhas deles se casem com os nossos filhos.

[[v16-10-31]]

^<<v16-10-31,31>>^ "Quando os povos vizinhos trouxerem mercadorias ou cereal para venderem em dia de sábado ou de festa, não compraremos deles nesses dias. Cada sete anos abriremos mão de trabalhar a terra e cancelaremos todas as dívidas.

[[v16-10-32]]

^<<v16-10-32,32>>^ "Assumimos a responsabilidade de, conforme o mandamento, dar anualmente quatro gramas para o serviço do templo de nosso Deus:

[[v16-10-33]]

^<<v16-10-33,33>>^ para os pães consagrados, para as ofertas regulares de cereal e para os holocaustos, para as ofertas dos sábados, das festas de lua nova e para as festas fixas, para as ofertas sagradas, para as ofertas pelo pecado para fazer propiciação por Israel, e para as necessidades do templo de nosso Deus.

[[v16-10-34]]

^<<v16-10-34,34>>^ "Também tiramos sorte entre as famílias dos sacerdotes, dos levitas e do povo, para escalar anualmente a que deverá trazer lenha ao templo de nosso Deus, no tempo determinado, para queimar sobre o altar do Senhor, o nosso Deus, conforme está escrito na Lei.

[[v16-10-35]]

^<<v16-10-35,35>>^ "Também assumimos a responsabilidade de trazer anualmente ao templo do Senhor os primeiros frutos de nossas colheitas e de toda árvore frutífera.

[[v16-10-36]]

^<<v16-10-36,36>>^ "Conforme também está escrito na Lei, traremos o primeiro de nossos filhos e a primeira cria de nossos rebanhos, tanto de ovelhas como de bois, para o templo de nosso Deus, para os sacerdotes que ali estiverem ministrando.

[[v16-10-37]]

^<<v16-10-37,37>>^ "Além do mais, traremos para os depósitos do templo de nosso Deus, para os sacerdotes, a nossa primeira massa de cereal moído, e as nossas primeiras ofertas de cereal, do fruto de todas as nossas árvores e de nosso vinho e azeite. E traremos o dízimo das nossas colheitas para os levitas, pois são eles que recolhem os dízimos em todas as cidades onde trabalhamos.

[[v16-10-38]]

^<<v16-10-38,38>>^ Um sacerdote descendente de Arão deverá acompanhar os levitas quando receberem os dízimos, e os levitas terão que trazer um décimo dos dízimos ao templo de nosso Deus, aos depósitos do templo.

[[v16-10-39]]

^<<v16-10-39,39>>^ O povo de Israel, inclusive os levitas, deverão trazer ofertas de cereal, de vinho novo e de azeite aos depósitos onde se guardam os utensílios para o santuário. É ali que os sacerdotes ministram e que os porteiros e os cantores ficam. "Não negligenciaremos o templo de nosso Deus".

'''

xref:016-neemias/016-neemias-009.adoc#v16-9-0[&#60; Capítulo Anterior] | <<v16-10-0,Topo>> | xref:016-neemias/016-neemias-011.adoc#v16-11-0[Próximo Capítulo &#62;]