include::./index.adoc[]

[[v16-13-0]]
=== Neemias, 13
// nvi ?, NVI - Nova Versão Internacional

[[v16-13-1]]

^<<v16-13-1,1>>^ Naquele dia o livro de Moisés foi lido em voz alta diante do povo, e ali achou-se escrito que nenhum amonita ou moabita jamais poderia ser admitido no povo de Deus,

[[v16-13-2]]

^<<v16-13-2,2>>^ pois eles, em vez de dar água e comida aos israelitas, tinham contratado Balaão para invocar uma maldição sobre eles. O nosso Deus, porém, transformou a maldição em bênção.

[[v16-13-3]]

^<<v16-13-3,3>>^ Quando o povo ouviu essa Lei, excluiu de Israel todos que eram de ascendência estrangeira.

[[v16-13-4]]

^<<v16-13-4,4>>^ Antes disso o sacerdote Eliasibe tinha sido encarregado dos depósitos do templo de nosso Deus. Ele era parente próximo de Tobias,

[[v16-13-5]]

^<<v16-13-5,5>>^ e lhe havia cedido uma grande sala, anteriormente utilizada para guardar as ofertas de cereal, o incenso, os utensílios do templo, e também os dízimos do trigo, do vinho novo e do azeite prescritos para os levitas, para os cantores e para os porteiros, e as ofertas para os sacerdotes.

[[v16-13-6]]

^<<v16-13-6,6>>^ Mas, enquanto tudo isso estava acontecendo, eu não estava em Jerusalém, pois no trigésimo segundo ano do reinado de Artaxerxes, rei da Babilônia, voltei ao rei. Algum tempo depois pedi sua permissão

[[v16-13-7]]

^<<v16-13-7,7>>^ e voltei para Jerusalém. Aqui soube do mal que Eliasibe fizera ao ceder uma sala para Tobias nos pátios do templo de Deus.

[[v16-13-8]]

^<<v16-13-8,8>>^ Fiquei muito aborrecido e joguei todos os móveis de Tobias fora da sala.

[[v16-13-9]]

^<<v16-13-9,9>>^ Mandei purificar as salas, e coloquei de volta nelas os utensílios do templo de Deus, com as ofertas de cereal e o incenso.

[[v16-13-10]]

^<<v16-13-10,10>>^ Também fiquei sabendo que os levitas não tinham recebido a parte que lhes era devida, e que todos os levitas e cantores responsáveis pelo culto haviam voltado para suas próprias terras.

[[v16-13-11]]

^<<v16-13-11,11>>^ Por isso repreendi os oficiais e lhes perguntei: "Por que essa negligência com o templo de Deus? " Então eu convoquei os levitas e cantores e os coloquei em seus postos.

[[v16-13-12]]

^<<v16-13-12,12>>^ E todo o povo de Judá trouxe os dízimos do trigo, do vinho novo e do azeite aos depósitos.

[[v16-13-13]]

^<<v16-13-13,13>>^ Coloquei o sacerdote Selemias, o escriba Zadoque e um levita chamado Pedaías como encarregados dos depósitos e fiz de Hanã, filho de Zacur, neto de Matanias, assistente deles, porque esses homens eram de confiança, e ficaram responsáveis pela distribuição de suprimentos aos seus colegas.

[[v16-13-14]]

^<<v16-13-14,14>>^ Lembra-te de mim por isso, meu Deus, e não te esqueças do que fiz com tanta fidelidade pelo templo de meu Deus e pelo seu culto.

[[v16-13-15]]

^<<v16-13-15,15>>^ Naqueles dias vi que em Judá alguns pisavam uvas nos tanques de prensá-las no sábado e ajuntavam trigo e o carregavam em jumentos, junto com vinho, uvas, figos e todo tipo de carga. Tudo isso era trazido para Jerusalém em pleno sábado. Então os adverti que não vendessem alimento nesse dia.

[[v16-13-16]]

^<<v16-13-16,16>>^ Havia alguns da cidade de Tiro que moravam em Jerusalém e traziam peixes e toda espécie de mercadoria e as vendiam em Jerusalém, no sábado, para o povo de Judá.

[[v16-13-17]]

^<<v16-13-17,17>>^ Diante disso, repreendi os nobres de Judá e disse-lhes: "Que mal é esse que vocês estão fazendo, profanando o dia de sábado?

[[v16-13-18]]

^<<v16-13-18,18>>^ Por acaso os seus antepassados não fizeram o mesmo, levando o nosso Deus a trazer toda essa desgraça sobre nós e sobre esta cidade? Pois agora, profanando o sábado, vocês provocam mais ira contra Israel! "

[[v16-13-19]]

^<<v16-13-19,19>>^ Quando as sombras da tarde cobriram as portas de Jerusalém na véspera do sábado, ordenei que fossem fechadas e só fossem abertas depois que o sábado tivesse terminado. Coloquei alguns de meus homens de confiança junto às portas, para que nenhum carregamento pudesse ser introduzido no dia de sábado.

[[v16-13-20]]

^<<v16-13-20,20>>^ Uma ou duas vezes os comerciantes e vendedores de todo tipo de mercadoria passaram a noite do lado de fora de Jerusalém.

[[v16-13-21]]

^<<v16-13-21,21>>^ Mas eu os adverti, dizendo: Por que vocês passam a noite junto ao muro? Se fizerem isso de novo, mandarei prendê-los. Depois disso não vieram mais no sábado.

[[v16-13-22]]

^<<v16-13-22,22>>^ Então ordenei aos levitas que se purificassem e fossem vigiar as portas a fim de que o dia de sábado fosse respeitado como sagrado. Lembra-te de mim também por isso, ó meu Deus, e tenha misericórdia de mim conforme o teu grande amor.

[[v16-13-23]]

^<<v16-13-23,23>>^ Além disso, naqueles dias vi alguns judeus que se haviam casado com mulheres de Asdode, de Amom e de Moabe.

[[v16-13-24]]

^<<v16-13-24,24>>^ A metade dos seus filhos falavam a língua de Asdode ou a língua de um dos outros povos, e não sabiam falar a língua de Judá.

[[v16-13-25]]

^<<v16-13-25,25>>^ Eu os repreendi e invoquei maldições sobre eles. Bati em alguns deles e arranquei os seus cabelos. Fiz com que jurassem em nome de Deus e disse-lhes: "Não consintam mais em dar suas filhas em casamento aos filhos deles, nem haja casamento das filhas deles com seus filhos ou com vocês.

[[v16-13-26]]

^<<v16-13-26,26>>^ Não foi por causa de casamentos como esses que Salomão, rei de Israel, pecou? Entre as muitas nações não havia rei algum como ele. Ele era amado de seu Deus, e Deus o fez rei sobre todo o Israel, mas até mesmo ele foi induzido ao pecado por mulheres estrangeiras.

[[v16-13-27]]

^<<v16-13-27,27>>^ Como podemos tolerar o que ouvimos? Como podem vocês cometer essa terrível maldade e serem infiéis ao nosso Deus, casando-se com mulheres estrangeiras? "

[[v16-13-28]]

^<<v16-13-28,28>>^ Um dos filhos de Joiada, filho do sumo sacerdote Eliasibe, era genro de Sambalate, o horonita. E eu o expulsei para longe de mim.

[[v16-13-29]]

^<<v16-13-29,29>>^ Não te esqueças deles, ó meu Deus, pois profanaram o ofício sacerdotal e a aliança do sacerdócio e dos levitas.

[[v16-13-30]]

^<<v16-13-30,30>>^ Dessa forma purifiquei os sacerdotes e os levitas de tudo o que era estrangeiro, e designei-lhes responsabilidades, cada um em seu próprio cargo.

[[v16-13-31]]

^<<v16-13-31,31>>^ Também estabeleci regras para as provisões de lenha, determinando as datas certas para serem trazidas, e para os primeiros frutos. Em tua bondade, lembra-te de mim, ó meu Deus.

'''

xref:016-neemias/016-neemias-012.adoc#v16-12-0[&#60; Capítulo Anterior] | <<v16-13-0,Topo>> | xref:017-ester/017-ester-001.adoc#v17-1-0[Próximo Capítulo &#62;]