include::./index.adoc[]

[[v16-7-0]]
=== Neemias, 7
// nvi ?, NVI - Nova Versão Internacional

[[v16-7-1]]

^<<v16-7-1,1>>^ Depois que o muro foi reconstruído e que eu coloquei as portas no lugar, foram nomeados os porteiros, os cantores e os levitas.

[[v16-7-2]]

^<<v16-7-2,2>>^ Para governar Jerusalém encarreguei o meu irmão Hanani e, com ele, Hananias, comandante da cidade forte, pois Hananias era íntegro e temia a Deus mais do que a maioria dos homens.

[[v16-7-3]]

^<<v16-7-3,3>>^ Eu lhes disse: As portas de Jerusalém não deverão ser abertas enquanto o sol não estiver alto. E antes de deixarem o serviço, os porteiros deverão fechar e travar as portas. Também designei moradores de Jerusalém para sentinelas, alguns em postos no muro, outros em frente das suas casas.

[[v16-7-4]]

^<<v16-7-4,4>>^ Ora, a cidade era grande e espaçosa, mas havia poucos moradores, e as casas ainda não tinham sido reconstruídas.

[[v16-7-5]]

^<<v16-7-5,5>>^ Por isso o meu Deus pôs no meu coração reunir os nobres, os oficiais e todo o povo para registrá-los por famílias. Encontrei o registro genealógico dos que foram os primeiros a voltar. E assim estava registrado ali:

[[v16-7-6]]

^<<v16-7-6,6>>^ Estes são os homens da província que voltaram do exílio, os quais Nabucodonosor, rei da Babilônia, havia levado prisioneiros. Eles voltaram para Jerusalém e para Judá, cada um para a sua própria cidade,

[[v16-7-7]]

^<<v16-7-7,7>>^ em companhia de Zorobabel, Jesua, Neemias, Azarias, Raamias, Naamani, Mardoqueu, Bilsã, Misperete, Bigvai, Neum e Baaná. E esta é a lista e o número dos que retornaram, pelos chefes de família e respectivas cidades:

[[v16-7-8]]

^<<v16-7-8,8>>^ os descendentes de Parós 2. 172

[[v16-7-9]]

^<<v16-7-9,9>>^ de Sefatias 372

[[v16-7-10]]

^<<v16-7-10,10>>^ de Ara 652

[[v16-7-11]]

^<<v16-7-11,11>>^ de Paate-Moabe, por meio da linhagem de Jesua e Joabe, 2. 818

[[v16-7-12]]

^<<v16-7-12,12>>^ de Elão 1. 254

[[v16-7-13]]

^<<v16-7-13,13>>^ de Zatu 845

[[v16-7-14]]

^<<v16-7-14,14>>^ de Zacai 760

[[v16-7-15]]

^<<v16-7-15,15>>^ de Binui 648

[[v16-7-16]]

^<<v16-7-16,16>>^ de Bebai 628

[[v16-7-17]]

^<<v16-7-17,17>>^ de Azgade 2. 322

[[v16-7-18]]

^<<v16-7-18,18>>^ de Adonicão 667

[[v16-7-19]]

^<<v16-7-19,19>>^ de Bigvai 2. 067

[[v16-7-20]]

^<<v16-7-20,20>>^ de Adim 655

[[v16-7-21]]

^<<v16-7-21,21>>^ de Ater, por meio de Ezequias, 98

[[v16-7-22]]

^<<v16-7-22,22>>^ de Hasum 328

[[v16-7-23]]

^<<v16-7-23,23>>^ de Besai 324

[[v16-7-24]]

^<<v16-7-24,24>>^ de Harife 112

[[v16-7-25]]

^<<v16-7-25,25>>^ de Gibeom 95

[[v16-7-26]]

^<<v16-7-26,26>>^ das cidades de Belém e de Netofate 188

[[v16-7-27]]

^<<v16-7-27,27>>^ de Anatote 128

[[v16-7-28]]

^<<v16-7-28,28>>^ de Bete-Azmavete 42

[[v16-7-29]]

^<<v16-7-29,29>>^ de Quiriate-Jearim, Cefira e Beerote 743

[[v16-7-30]]

^<<v16-7-30,30>>^ de Ramá e Geba 621

[[v16-7-31]]

^<<v16-7-31,31>>^ de Micmás 122

[[v16-7-32]]

^<<v16-7-32,32>>^ de Betel e Ai 123

[[v16-7-33]]

^<<v16-7-33,33>>^ do outro Nebo 52

[[v16-7-34]]

^<<v16-7-34,34>>^ do outro Elão 1. 254

[[v16-7-35]]

^<<v16-7-35,35>>^ de Harim 320

[[v16-7-36]]

^<<v16-7-36,36>>^ de Jericó 345

[[v16-7-37]]

^<<v16-7-37,37>>^ de Lode, Hadide e Ono 721

[[v16-7-38]]

^<<v16-7-38,38>>^ de Senaá 3. 930.

[[v16-7-39]]

^<<v16-7-39,39>>^ Os sacerdotes: os descendentes de Jedaías, por meio da família de Jesua, 973

[[v16-7-40]]

^<<v16-7-40,40>>^ de Imer 1. 052

[[v16-7-41]]

^<<v16-7-41,41>>^ de Pasur 1. 247

[[v16-7-42]]

^<<v16-7-42,42>>^ de Harim 1. 017.

[[v16-7-43]]

^<<v16-7-43,43>>^ Os levitas: os descendentes de Jesua, por meio de Cadmiel, pela linhagem de Hodeva 74.

[[v16-7-44]]

^<<v16-7-44,44>>^ Os cantores: os descendentes de Asafe 148.

[[v16-7-45]]

^<<v16-7-45,45>>^ Os porteiros do templo: os descendentes de Salum, Ater, Talmom, Acube, Hatita e Sobai 138.

[[v16-7-46]]

^<<v16-7-46,46>>^ Os servidores do templo: os descendentes de Zia, Hasufa, Tabaote,

[[v16-7-47]]

^<<v16-7-47,47>>^ Queros, Sia, Padom,

[[v16-7-48]]

^<<v16-7-48,48>>^ Lebana, Hagaba, Salmai,

[[v16-7-49]]

^<<v16-7-49,49>>^ Hanã, Gidel, Gaar,

[[v16-7-50]]

^<<v16-7-50,50>>^ Reaías, Rezim, Necoda,

[[v16-7-51]]

^<<v16-7-51,51>>^ Gazão, Uzá, Paséia,

[[v16-7-52]]

^<<v16-7-52,52>>^ Besai, Meunim, Nefusim,

[[v16-7-53]]

^<<v16-7-53,53>>^ Baquebuque, Hacufa, Harur,

[[v16-7-54]]

^<<v16-7-54,54>>^ Baslite, Meída, Harsa,

[[v16-7-55]]

^<<v16-7-55,55>>^ Barcos, Sísera, Tamá,

[[v16-7-56]]

^<<v16-7-56,56>>^ Nesias e Hatifa.

[[v16-7-57]]

^<<v16-7-57,57>>^ Os descendentes dos servos de Salomão: os descendentes de Sotai, Soferete, Perida,

[[v16-7-58]]

^<<v16-7-58,58>>^ Jaala, Darcom, Gidel,

[[v16-7-59]]

^<<v16-7-59,59>>^ Sefatias, Hatil, Poquerete-Hazebaim e Amom.

[[v16-7-60]]

^<<v16-7-60,60>>^ Os servos do templo e os descendentes dos servos de Salomão 392.

[[v16-7-61]]

^<<v16-7-61,61>>^ Os que chegaram das cidades de Tel-Melá, Tel-Harsa, Querube, Adom e Imer, mas não puderam provar que suas famílias eram descendentes de Israel:

[[v16-7-62]]

^<<v16-7-62,62>>^ Os descendentes de Delaías, Tobias e Necoda 642.

[[v16-7-63]]

^<<v16-7-63,63>>^ E dentre os sacerdotes: os descendentes de Habaías, Coz e Barzilai, homem que se casou com uma filha de Barzilai, de Gileade, e que era chamado por aquele nome.

[[v16-7-64]]

^<<v16-7-64,64>>^ Esses procuraram seus registros de família, mas não conseguiram achá-los e, dessa forma, foram considerados impuros para o sacerdócio.

[[v16-7-65]]

^<<v16-7-65,65>>^ Por isso o governador determinou que eles não comessem das ofertas santíssimas enquanto não houvesse um sacerdote para consultar o Urim e o Tumim.

[[v16-7-66]]

^<<v16-7-66,66>>^ O total de todos os registrados foi 42. 360 homens,

[[v16-7-67]]

^<<v16-7-67,67>>^ além de seus 7. 337 servos e servas; havia entre eles 245 cantores e cantoras.

[[v16-7-68]]

^<<v16-7-68,68>>^ Possuíam 736 cavalos, 245 mulas,

[[v16-7-69]]

^<<v16-7-69,69>>^ 435 camelos e 6. 720 jumentos.

[[v16-7-70]]

^<<v16-7-70,70>>^ Alguns dos chefes das famílias contribuíram para o trabalho. O governador deu à tesouraria oito quilos de ouro, 50 bacias e 530 vestes para os sacerdotes.

[[v16-7-71]]

^<<v16-7-71,71>>^ Alguns dos chefes das famílias deram à tesouraria, para a realização do trabalho, cento e sessenta quilos de ouro e uma tonelada e trezentos e vinte quilos de prata.

[[v16-7-72]]

^<<v16-7-72,72>>^ O total dado pelo restante do povo foi de cento e sessenta quilos de ouro, uma tonelada e duzentos quilos de prata e 67 vestes para os sacerdotes.

[[v16-7-73]]

^<<v16-7-73,73>>^ Os sacerdotes, os levitas, os porteiros, os cantores e os servidores do templo, e também alguns do povo e os demais israelitas, estabeleceram-se em suas próprias cidades. Quando chegou o sétimo mês e os israelitas tinham se instalado em suas cidades,

'''

xref:016-neemias/016-neemias-006.adoc#v16-6-0[&#60; Capítulo Anterior] | <<v16-7-0,Topo>> | xref:016-neemias/016-neemias-008.adoc#v16-8-0[Próximo Capítulo &#62;]