include::./index.adoc[]

[[v16-8-0]]
=== Neemias, 8
// nvi ?, NVI - Nova Versão Internacional

[[v16-8-1]]

^<<v16-8-1,1>>^ todo o povo juntou-se como se fosse um só homem na praça, em frente da porta das Águas. Pediram ao escriba Esdras que trouxesse o Livro da Lei de Moisés, que o Senhor dera a Israel.

[[v16-8-2]]

^<<v16-8-2,2>>^ Assim, no dia primeiro do sétimo mês, o sacerdote Esdras trouxe a Lei diante da assembléia, que era constituída de homens e mulheres e de todos os que podiam entender.

[[v16-8-3]]

^<<v16-8-3,3>>^ Ele a leu em voz alta desde o raiar da manhã até o meio-dia, de frente para a praça, em frente da porta das Águas, na presença dos homens, mulheres e de outros que podiam entender. E todo o povo ouvia com atenção a leitura do Livro da Lei.

[[v16-8-4]]

^<<v16-8-4,4>>^ O escriba Esdras estava numa plataforma elevada, de madeira, construída para a ocasião. Ao seu lado, à direita, estavam Matitias, Sema, Anaías, Urias, Hilquias e Maaséias; e à esquerda estavam Pedaías, Misael, Malquias, Hasum, Hasbadana, Zacarias e Mesulão.

[[v16-8-5]]

^<<v16-8-5,5>>^ Esdras abriu o livro diante de todo o povo, e este podia vê-lo, pois ele estava num lugar mais alto. E, quando abriu o livro, o povo todo se levantou.

[[v16-8-6]]

^<<v16-8-6,6>>^ Esdras louvou o Senhor, o grande Deus, e todo o povo ergueu as mãos e respondeu: "Amém! Amém! " Então eles adoraram o Senhor, prostrados, rosto em terra.

[[v16-8-7]]

^<<v16-8-7,7>>^ Os levitas Jesua, Bani, Serebias, Jamim, Acube, Sabetai, Hodias, Maaséias, Quelita, Azarias, Jozabade, Hanã e Pelaías, instruíram o povo na Lei, e todos permaneciam ali.

[[v16-8-8]]

^<<v16-8-8,8>>^ Leram o Livro da Lei de Deus, interpretando-o e explicando-o, a fim de que o povo entendesse o que estava sendo lido.

[[v16-8-9]]

^<<v16-8-9,9>>^ Então Neemias, o governador, Esdras, o sacerdote e escriba, e os levitas que estavam instruindo o povo disseram a todos: "Este dia é consagrado ao Senhor Deus. Nada de tristeza e de choro! " Pois todo o povo estava chorando enquanto ouvia as palavras da Lei.

[[v16-8-10]]

^<<v16-8-10,10>>^ E Neemias acrescentou: "Podem sair, e comam e bebam do melhor que tiverem, e repartam com os que nada têm preparado. Este dia é consagrado ao nosso Senhor. Não se entristeçam, porque a alegria do Senhor os fortalecerá".

[[v16-8-11]]

^<<v16-8-11,11>>^ Os levitas tranqüilizaram todo o povo, dizendo: "Acalmem-se porque este é um dia santo. Não fiquem tristes! "

[[v16-8-12]]

^<<v16-8-12,12>>^ Então todo o povo saiu para comer, beber, repartir com os que nada tinham preparado e para comemorar com grande alegria, pois agora compreendiam as palavras que lhes foram explicadas.

[[v16-8-13]]

^<<v16-8-13,13>>^ No segundo dia do mês, os chefes de todas as famílias, os sacerdotes e os levitas reuniram-se com o escriba Esdras para estudar as palavras da Lei.

[[v16-8-14]]

^<<v16-8-14,14>>^ Descobriram que estava escrito na Lei, que o Senhor tinha ordenado por meio de Moisés, que os israelitas deviam morar em tendas durante a festa do sétimo mês.

[[v16-8-15]]

^<<v16-8-15,15>>^ Por isso anunciaram em todas as suas cidades e em Jerusalém: "Saiam às montanhas e tragam ramos de oliveiras cultivadas, de oliveiras silvestres, de murtas, de tamareiras e de árvores frondosas, para fazerem tendas", conforme está escrito.

[[v16-8-16]]

^<<v16-8-16,16>>^ Então o povo saiu e trouxe os ramos, e eles mesmos construíram tendas nos seus terraços, nos seus pátios, nos pátios do templo de Deus e na praça junto à porta das Águas e na que fica junto à porta de Efraim.

[[v16-8-17]]

^<<v16-8-17,17>>^ Todos os que tinham voltado do exílio construíram tendas e moraram nelas. Desde os dias de Josué, filho de Num, até aquele dia, os israelitas não tinham celebrado a festa dessa maneira. E a alegria deles foi muito grande.

[[v16-8-18]]

^<<v16-8-18,18>>^ Dia após dia, desde o primeiro até o último dia da festa, Esdras leu o Livro da Lei de Deus. Eles celebraram a festa durante sete dias, e no oitavo dia, conforme o ritual, houve uma reunião solene.

'''

xref:016-neemias/016-neemias-007.adoc#v16-7-0[&#60; Capítulo Anterior] | <<v16-8-0,Topo>> | xref:016-neemias/016-neemias-009.adoc#v16-9-0[Próximo Capítulo &#62;]