include::./index.adoc[]

[[v4-32-0]]
=== Números, 32
// nvi ?, NVI - Nova Versão Internacional

[[v4-32-1]]

^<<v4-32-1,1>>^ As tribos de Rúben e de Gade, donas de numerosos rebanhos, viram que as terras de Jazar e de Gileade eram próprias para a criação de gado.

[[v4-32-2]]

^<<v4-32-2,2>>^ Por isso foram a Moisés, ao sacerdote Eleazar e aos líderes da comunidade, e disseram:

[[v4-32-3]]

^<<v4-32-3,3>>^ "Atarote, Dibom, Jazar, Ninra, Hesbom, Eleale, Sebã, Nebo e Beom,

[[v4-32-4]]

^<<v4-32-4,4>>^ terras que o Senhor subjugou perante a comunidade de Israel, são próprias para a criação de gado, e os seus servos possuem gado".

[[v4-32-5]]

^<<v4-32-5,5>>^ E acrescentaram: "Se podemos contar com o favor de vocês, deixem que essa terra seja dada a estes seus servos como nossa herança. Não nos façam atravessar o Jordão".

[[v4-32-6]]

^<<v4-32-6,6>>^ Moisés respondeu aos homens de Gade e de Rúben: "E os seus compatriotas irão à guerra enquanto vocês ficam aqui?

[[v4-32-7]]

^<<v4-32-7,7>>^ Por que vocês desencorajam os israelitas de entrar na terra que o Senhor lhes deu?

[[v4-32-8]]

^<<v4-32-8,8>>^ Foi isso que os pais de vocês fizeram quando os enviei de Cades-Barnéia para verem a terra.

[[v4-32-9]]

^<<v4-32-9,9>>^ Depois de subirem ao vale de Escol e examinarem a terra, desencorajaram os israelitas de entrar na terra que o Senhor lhes tinha dado.

[[v4-32-10]]

^<<v4-32-10,10>>^ A ira do Senhor se acendeu naquele dia, e ele fez este juramento:

[[v4-32-11]]

^<<v4-32-11,11>>^ ‘Como não me seguiram de coração íntegro, nenhum dos homens de vinte anos para cima que saíram do Egito verá a terra que prometi sob juramento a Abraão, a Isaque e a Jacó,

[[v4-32-12]]

^<<v4-32-12,12>>^ com exceção de Calebe, filho de Jefoné, o quenezeu, e Josué, filho de Num, seguiram ao Senhor com integridade de coração’.

[[v4-32-13]]

^<<v4-32-13,13>>^ A ira do Senhor acendeu-se contra Israel, e ele os fez andar errantes no deserto durante quarenta anos, até que passou toda a geração daqueles que lhe tinham desagradado com seu mau procedimento.

[[v4-32-14]]

^<<v4-32-14,14>>^ "E aí estão vocês, raça de pecadores, pondo-se no lugar dos seus antepassados e acendendo ainda mais a ira do Senhor contra Israel.

[[v4-32-15]]

^<<v4-32-15,15>>^ Se deixarem de segui-lo, de novo ele os abandonará no deserto, e vocês serão o motivo da destruição de todo este povo".

[[v4-32-16]]

^<<v4-32-16,16>>^ Então se aproximaram dele e disseram: "Gostaríamos de construir aqui currais para o nosso gado e cidades para as nossas mulheres e filhos.

[[v4-32-17]]

^<<v4-32-17,17>>^ Mas nós nos armaremos e estaremos prontos para ir à frente dos israelitas até que os tenhamos levado ao seu lugar. Enquanto isso, nossas mulheres e nossos filhos morarão em cidades fortificadas para se proteger dos habitantes da terra.

[[v4-32-18]]

^<<v4-32-18,18>>^ Não retornaremos aos nossos lares enquanto todos os israelitas não receberem a sua herança.

[[v4-32-19]]

^<<v4-32-19,19>>^ Não receberemos herança alguma com eles do outro lado do Jordão, uma vez que a nossa herança nos seja dada no lado leste do Jordão".

[[v4-32-20]]

^<<v4-32-20,20>>^ Disse-lhes Moisés: "Se fizerem isso, se perante o Senhor vocês se armarem para a guerra,

[[v4-32-21]]

^<<v4-32-21,21>>^ e se, armados, todos vocês atravessarem o Jordão perante o Senhor até que ele tenha expulsado os seus inimigos da frente dele,

[[v4-32-22]]

^<<v4-32-22,22>>^ então, quando a terra estiver subjugada perante o Senhor, vocês poderão voltar e estarão livres da sua obrigação para com o Senhor e para com Israel. E esta terra será propriedade de vocês perante o Senhor.

[[v4-32-23]]

^<<v4-32-23,23>>^ "Mas, se vocês não fizerem isso, estarão pecando contra o Senhor; e estejam certos de que vocês não escaparão do pecado que cometeram.

[[v4-32-24]]

^<<v4-32-24,24>>^ Construam cidades para as suas mulheres e crianças, e currais para os seus rebanhos, mas façam o que vocês prometeram".

[[v4-32-25]]

^<<v4-32-25,25>>^ Então os homens de Gade e de Rúben disseram a Moisés: "Nós, seus servos, faremos como o meu senhor ordena.

[[v4-32-26]]

^<<v4-32-26,26>>^ Nossos filhos e mulheres, todos os nossos rebanhos ficarão aqui nas cidades de Gileade.

[[v4-32-27]]

^<<v4-32-27,27>>^ Mas os seus servos, todos os homens armados para a batalha, atravessarão para lutar perante o Senhor, assim como o meu senhor está dizendo".

[[v4-32-28]]

^<<v4-32-28,28>>^ Moisés deu as seguintes instruções acerca deles ao sacerdote Eleazar, a Josué, filho de Num, e aos chefes de família das tribos israelitas:

[[v4-32-29]]

^<<v4-32-29,29>>^ "Se os homens de Gade e de Rúben, todos eles armados para a batalha, atravessarem o Jordão com vocês perante o Senhor, então, quando a terra for subjugada perante vocês, entreguem-lhes como propriedade a terra de Gileade.

[[v4-32-30]]

^<<v4-32-30,30>>^ Mas, se não atravessarem armados com vocês, terão que aceitar a propriedade deles com vocês em Canaã".

[[v4-32-31]]

^<<v4-32-31,31>>^ Os homens de Gade e de Rúben responderam: "Os seus servos farão o que o Senhor disse.

[[v4-32-32]]

^<<v4-32-32,32>>^ Atravessaremos o Jordão perante o Senhor e entraremos armados em Canaã, mas a propriedade que vamos herdar estará deste lado do Jordão".

[[v4-32-33]]

^<<v4-32-33,33>>^ Então Moisés deu às tribos de Gade e de Rúben e à metade da tribo de Manassés, filho de José, o reino de Seom, rei dos amorreus, e o reino de Ogue, rei de Basã, toda a terra com as suas cidades e o território ao redor delas.

[[v4-32-34]]

^<<v4-32-34,34>>^ A tribo de Gade construiu Dibom, Atarote, Aroer,

[[v4-32-35]]

^<<v4-32-35,35>>^ Atarote-Sofã, Jazar, Jogbeá,

[[v4-32-36]]

^<<v4-32-36,36>>^ Bete-Ninra e Bete-Harã como cidades fortificadas, e fez currais para os seus rebanhos.

[[v4-32-37]]

^<<v4-32-37,37>>^ E a tribo de Rúben reconstruiu Hesbom, Eleale e Quiriataim,

[[v4-32-38]]

^<<v4-32-38,38>>^ bem como Nebo e Baal-Meom ( esses nomes foram mudados ) e Sibma. E deu outros nomes a essas cidades.

[[v4-32-39]]

^<<v4-32-39,39>>^ Os descendentes de Maquir, filho de Manassés, foram a Gileade, tomaram posse dela e expulsaram os amorreus que lá estavam.

[[v4-32-40]]

^<<v4-32-40,40>>^ Então Moisés deu Gileade aos maquiritas, descendentes de Manassés, e eles passaram a habitar ali.

[[v4-32-41]]

^<<v4-32-41,41>>^ Jair, descendente de Manassés, conquistou os povoados deles e os chamou Havote-Jair.

[[v4-32-42]]

^<<v4-32-42,42>>^ E Noba conquistou Quenate e os seus povoados e a chamou Noba, de acordo com o seu nome.

'''

xref:004-numeros/004-numeros-031.adoc#v4-31-0[&#60; Capítulo Anterior] | <<v4-32-0,Topo>> | xref:004-numeros/004-numeros-033.adoc#v4-33-0[Próximo Capítulo &#62;]