include::./index.adoc[]

[[v4-14-0]]
=== Números, 14
// nvi ?, NVI - Nova Versão Internacional

[[v4-14-1]]

^<<v4-14-1,1>>^ Naquela noite toda a comunidade começou a chorar em alta voz.

[[v4-14-2]]

^<<v4-14-2,2>>^ Todos os israelitas queixaram-se contra Moisés e contra Arão, e toda a comunidade lhes disse: "Quem dera tivéssemos morrido no Egito! Ou neste deserto!

[[v4-14-3]]

^<<v4-14-3,3>>^ Por que o Senhor está nos trazendo para esta terra? Só para nos deixar cair à espada? Nossas mulheres e nossos filhos serão tomados como despojo de guerra. Não seria melhor voltar para o Egito? "

[[v4-14-4]]

^<<v4-14-4,4>>^ E disseram uns aos outros: "Escolheremos um chefe e voltaremos para o Egito! "

[[v4-14-5]]

^<<v4-14-5,5>>^ Então Moisés e Arão prostraram-se, rosto em terra, diante de toda a assembléia dos israelitas.

[[v4-14-6]]

^<<v4-14-6,6>>^ Josué, filho de Num, e Calebe, filho de Jefoné, dentre os que haviam observado a terra, rasgaram as suas vestes

[[v4-14-7]]

^<<v4-14-7,7>>^ e disseram a toda à comunidade dos israelitas: "A terra que percorremos em missão de reconhecimento é excelente.

[[v4-14-8]]

^<<v4-14-8,8>>^ Se o Senhor se agradar de nós, ele nos fará entrar nessa terra, onde manam leite e mel, e a dará a nós.

[[v4-14-9]]

^<<v4-14-9,9>>^ Somente não sejam rebeldes contra o Senhor. E não tenham medo do povo da terra, porque nós os devoraremos como se fossem pão. A proteção deles se foi, mas o Senhor está conosco. Não tenham medo deles! "

[[v4-14-10]]

^<<v4-14-10,10>>^ Mas a comunidade toda falou em apedrejá-los. Então a glória do Senhor apareceu a todos os israelitas na Tenda do Encontro.

[[v4-14-11]]

^<<v4-14-11,11>>^ E o Senhor disse a Moisés: "Até quando este povo me tratará com pouco caso? Até quando se recusará a crer em mim, apesar de todos os sinais que realizei entre eles?

[[v4-14-12]]

^<<v4-14-12,12>>^ Eu os ferirei com praga e os destruirei, mas farei de você uma nação maior e mais forte do que eles".

[[v4-14-13]]

^<<v4-14-13,13>>^ Moisés disse ao Senhor: "Então os egípcios ouvirão que pelo teu poder fizeste este povo sair dentre eles,

[[v4-14-14]]

^<<v4-14-14,14>>^ e falarão disso aos habitantes desta terra. Eles ouviram que tu, ó Senhor, estás com este povo e que te vêem face a face, Senhor, e que a tua nuvem paira sobre eles, e que vais adiante deles numa coluna de nuvem de dia e numa coluna de fogo de noite.

[[v4-14-15]]

^<<v4-14-15,15>>^ Se exterminares este povo, as nações que ouvirem falar do que fizeste dirão:

[[v4-14-16]]

^<<v4-14-16,16>>^ ‘O Senhor não conseguiu levar esse povo à terra que lhes prometeu em juramento; por isso os matou no deserto’.

[[v4-14-17]]

^<<v4-14-17,17>>^ "Mas agora, que a força do Senhor se manifeste, segundo prometeste:

[[v4-14-18]]

^<<v4-14-18,18>>^ ‘O Senhor é muito paciente e grande em fidelidade, e perdoa a iniqüidade e a rebelião, se bem que não deixa o pecado sem punição, e castiga os filhos pela iniqüidade dos pais até a terceira e quarta geração’.

[[v4-14-19]]

^<<v4-14-19,19>>^ Segundo a tua grande fidelidade, perdoa a iniqüidade deste povo, assim como a tens perdoado desde que saíram do Egito até agora".

[[v4-14-20]]

^<<v4-14-20,20>>^ O Senhor respondeu: "Eu os perdoei, conforme você pediu.

[[v4-14-21]]

^<<v4-14-21,21>>^ No entanto, juro pela glória do Senhor que enche toda a terra,

[[v4-14-22]]

^<<v4-14-22,22>>^ que nenhum dos que viram a minha glória e os sinais miraculosos que realizei no Egito e no deserto, e me puseram à prova e me desobedeceram dez vezes —

[[v4-14-23]]

^<<v4-14-23,23>>^ nenhum deles chegará a ver a terra que prometi com juramento aos seus antepassados. Ninguém que me tratou com desprezo a verá.

[[v4-14-24]]

^<<v4-14-24,24>>^ Mas, como o meu servo Calebe tem outro espírito e me segue com integridade, eu o farei entrar na terra que foi observar, e seus descendentes a herdarão.

[[v4-14-25]]

^<<v4-14-25,25>>^ Visto que os amalequitas e os cananeus habitam nos vales, amanhã dêem meia-volta e partam em direção ao deserto pelo caminho que vai para o mar Vermelho".

[[v4-14-26]]

^<<v4-14-26,26>>^ Disse mais o Senhor a Moisés e a Arão:

[[v4-14-27]]

^<<v4-14-27,27>>^ "Até quando esta comunidade ímpia se queixará contra mim? Tenho ouvido as queixas desses israelitas murmuradores.

[[v4-14-28]]

^<<v4-14-28,28>>^ Diga-lhes: ‘Juro pelo meu nome, declara o Senhor, que farei a vocês tudo o que pediram:

[[v4-14-29]]

^<<v4-14-29,29>>^ Cairão neste deserto os cadáveres de todos vocês, de vinte anos para cima, que foram contados no recenseamento e que se queixaram contra mim.

[[v4-14-30]]

^<<v4-14-30,30>>^ Nenhum de vocês entrará na terra que, com mão levantada, jurei dar-lhes para sua habitação, exceto Calebe, filho de Jefoné, e Josué, filho de Num.

[[v4-14-31]]

^<<v4-14-31,31>>^ Mas, quanto aos seus filhos, sobre os quais vocês disseram que seriam tomados como despojo de guerra, eu os farei entrar para desfrutarem a terra que vocês rejeitaram.

[[v4-14-32]]

^<<v4-14-32,32>>^ O cadáveres de vocês, porém, cairão neste deserto.

[[v4-14-33]]

^<<v4-14-33,33>>^ Os filhos de vocês serão pastores aqui durante quarenta anos, sofrendo pela infidelidade de vocês, até que o último cadáver de vocês seja destruído no deserto.

[[v4-14-34]]

^<<v4-14-34,34>>^ Durante quarenta anos vocês sofrerão a conseqüência dos seus pecados e experimentarão a minha rejeição; cada ano corresponderá a cada um dos quarenta dias em que vocês observaram a terra’.

[[v4-14-35]]

^<<v4-14-35,35>>^ Eu, o Senhor, falei, e certamente farei essas coisas a toda esta comunidade ímpia, que conspirou contra mim. Encontrarão o seu fim neste deserto; aqui morrerão".

[[v4-14-36]]

^<<v4-14-36,36>>^ Os homens enviados por Moisés em missão de reconhecimento daquela terra voltaram e fizeram toda a comunidade queixar-se contra ele ao espalharem um relatório negativo;

[[v4-14-37]]

^<<v4-14-37,37>>^ esses homens responsáveis por espalhar o relatório negativo sobre a terra morreram subitamente de praga perante o Senhor.

[[v4-14-38]]

^<<v4-14-38,38>>^ De todos os que foram observar a terra, somente Josué, filho de Num, e Calebe, filho de Jefoné, sobreviveram.

[[v4-14-39]]

^<<v4-14-39,39>>^ Quando Moisés transmitiu essas palavras a todos os israelitas, eles choraram amargamente.

[[v4-14-40]]

^<<v4-14-40,40>>^ Na madrugada seguinte subiram para o alto da região montanhosa, e disseram: "Subiremos ao lugar que o Senhor prometeu, pois cometemos pecado".

[[v4-14-41]]

^<<v4-14-41,41>>^ Moisés, porém, disse: "Por que vocês estão desobedecendo à ordem do Senhor? Isso não terá sucesso!

[[v4-14-42]]

^<<v4-14-42,42>>^ Não subam, porque o Senhor não está com vocês. Vocês serão derrotados pelos inimigos,

[[v4-14-43]]

^<<v4-14-43,43>>^ pois os amalequitas e os cananeus os enfrentarão ali, e vocês cairão à espada. Visto que deixaram de seguir ao Senhor, ele não estará com vocês".

[[v4-14-44]]

^<<v4-14-44,44>>^ Apesar disso, eles subiram desafiadoramente ao alto da região montanhosa, mas nem Moisés nem a arca da aliança do Senhor saíram do acampamento.

[[v4-14-45]]

^<<v4-14-45,45>>^ Então os amalequitas e os cananeus que lá viviam desceram e os derrotaram e os perseguiram até Hormá.

'''

xref:004-numeros/004-numeros-013.adoc#v4-13-0[&#60; Capítulo Anterior] | <<v4-14-0,Topo>> | xref:004-numeros/004-numeros-015.adoc#v4-15-0[Próximo Capítulo &#62;]