include::./index.adoc[]

[[v4-35-0]]
=== Números, 35
// nvi ?, NVI - Nova Versão Internacional

[[v4-35-1]]

^<<v4-35-1,1>>^ Nas campinas de Moabe, junto ao Jordão, do outro lado de Jericó, o Senhor disse a Moisés:

[[v4-35-2]]

^<<v4-35-2,2>>^ "Ordene aos israelitas que, da herança que possuem, dêem cidades para os levitas morarem. E dêem-lhes também pastagens ao redor das cidades.

[[v4-35-3]]

^<<v4-35-3,3>>^ Assim eles terão cidades para habitar e pastagens para o gado, para os rebanhos e para todos os seus outros animais de criação.

[[v4-35-4]]

^<<v4-35-4,4>>^ "As pastagens ao redor das cidades que vocês derem aos levitas se estenderão para fora quatrocentos e cinqüenta metros, a partir do muro da cidade.

[[v4-35-5]]

^<<v4-35-5,5>>^ Do lado de fora da cidade, meçam novecentos metros para o lado leste, para o lado sul, para o lado oeste e para o lado norte, tendo a cidade no centro. Eles terão essa área para pastagens das cidades.

[[v4-35-6]]

^<<v4-35-6,6>>^ "Seis das cidades que vocês derem aos levitas serão cidades de refúgio, para onde poderá fugir quem tiver matado alguém. Além disso, dêem a eles outras quarenta e duas cidades.

[[v4-35-7]]

^<<v4-35-7,7>>^ Ao todo, vocês darão aos levitas quarenta e oito cidades, juntamente com as suas pastagens.

[[v4-35-8]]

^<<v4-35-8,8>>^ As cidades que derem aos levitas, das terras dos israelitas, deverão ser dadas proporcionalmente à herança de cada tribo; tomem muitas cidades da tribo que tem muitas, mas poucas da que tem poucas".

[[v4-35-9]]

^<<v4-35-9,9>>^ Disse também o Senhor a Moisés:

[[v4-35-10]]

^<<v4-35-10,10>>^ "Diga aos israelitas: Quando vocês atravessarem o Jordão e entrarem em Canaã,

[[v4-35-11]]

^<<v4-35-11,11>>^ escolham algumas cidades para serem suas cidades de refúgio, para onde poderá fugir quem tiver matado alguém sem intenção.

[[v4-35-12]]

^<<v4-35-12,12>>^ Elas serão locais de refúgio contra o vingador da vítima, a fim de que alguém acusado de assassinato não morra antes de apresentar-se para julgamento perante a comunidade.

[[v4-35-13]]

^<<v4-35-13,13>>^ As seis cidades que vocês derem serão suas cidades de refúgio.

[[v4-35-14]]

^<<v4-35-14,14>>^ Designem três cidades de refúgio deste lado do Jordão e três outras em Canaã.

[[v4-35-15]]

^<<v4-35-15,15>>^ As seis cidades servirão de refúgio para os israelitas, para os estrangeiros residentes e para quaisquer outros estrangeiros que vivam entre eles, para que todo aquele que tiver matado alguém sem intenção possa fugir para lá.

[[v4-35-16]]

^<<v4-35-16,16>>^ "Se um homem ferir alguém com um objeto de ferro de modo que esta pessoa morra, ele é assassino; o assassino terá que ser executado.

[[v4-35-17]]

^<<v4-35-17,17>>^ Ou, se alguém tiver nas mãos uma pedra que possa matar, e ferir uma pessoa de modo que ela morra, é assassino; o assassino terá que ser executado.

[[v4-35-18]]

^<<v4-35-18,18>>^ Ou, se alguém tiver nas mãos um pedaço de madeira que possa matar, e ferir uma pessoa de modo que ela morra, é assassino; o assassino terá que ser executado.

[[v4-35-19]]

^<<v4-35-19,19>>^ O vingador da vítima matará o assassino; quando o encontrar o matará.

[[v4-35-20]]

^<<v4-35-20,20>>^ Se alguém, com ódio, empurrar uma pessoa premeditadamente ou atirar alguma coisa contra ela de modo que ela morra,

[[v4-35-21]]

^<<v4-35-21,21>>^ ou se com hostilidade der-lhe um soco provocando a sua morte, ele terá que ser executado; é assassino. O vingador da vítima matará o assassino quando encontrá-lo.

[[v4-35-22]]

^<<v4-35-22,22>>^ "Todavia, se alguém, sem hostilidade, empurrar uma pessoa ou atirar alguma coisa contra ela sem intenção,

[[v4-35-23]]

^<<v4-35-23,23>>^ ou se, sem vê-la, deixar cair sobre ela uma pedra que possa matá-la, e ela morrer, então, como não era sua inimiga e não pretendia feri-la,

[[v4-35-24]]

^<<v4-35-24,24>>^ a comunidade deverá julgar entre ele e o vingador da vítima de acordo com essas leis.

[[v4-35-25]]

^<<v4-35-25,25>>^ A comunidade protegerá o acusado de assassinato do vingador da vítima e o enviará de volta à cidade de refúgio para onde tinha fugido. Ali permanecerá até a morte do sumo sacerdote, que foi ungido com o óleo santo.

[[v4-35-26]]

^<<v4-35-26,26>>^ "Se, contudo, o acusado sair dos limites da cidade de refúgio para onde fugiu

[[v4-35-27]]

^<<v4-35-27,27>>^ e o vingador da vítima o encontrar fora da cidade, ele poderá matar o acusado sem ser culpado de assassinato.

[[v4-35-28]]

^<<v4-35-28,28>>^ O acusado deverá permanecer em sua cidade de refúgio até a morte do sumo sacerdote; somente depois da morte do sumo sacerdote poderá voltar à sua propriedade.

[[v4-35-29]]

^<<v4-35-29,29>>^ "Estas exigências legais serão para vocês e para as suas futuras gerações, onde quer que vocês vivam.

[[v4-35-30]]

^<<v4-35-30,30>>^ "Quem matar uma pessoa terá que ser executado como assassino mediante depoimento de testemunhas. Mas ninguém será executado mediante o depoimento de apenas uma testemunha.

[[v4-35-31]]

^<<v4-35-31,31>>^ "Não aceitem resgate pela vida de um assassino; ele merece morrer. Certamente terá que ser executado.

[[v4-35-32]]

^<<v4-35-32,32>>^ "Não aceitem resgate por alguém que tenha fugido para uma cidade de refúgio, permitindo que ele retorne e viva em sua própria terra antes da morte do sumo sacerdote.

[[v4-35-33]]

^<<v4-35-33,33>>^ "Não profanem a terra onde vocês estão. O derramamento de sangue profana a terra, e só se pode fazer propiciação em favor da terra em que se derramou sangue, mediante o sangue do assassino que o derramou.

[[v4-35-34]]

^<<v4-35-34,34>>^ Não contaminem a terra onde vocês vivem e onde eu habito, pois eu, o Senhor, habito entre os israelitas".

'''

xref:004-numeros/004-numeros-034.adoc#v4-34-0[&#60; Capítulo Anterior] | <<v4-35-0,Topo>> | xref:004-numeros/004-numeros-036.adoc#v4-36-0[Próximo Capítulo &#62;]