include::./index.adoc[]

[[v4-12-0]]
=== Números, 12
// nvi ?, NVI - Nova Versão Internacional

[[v4-12-1]]

^<<v4-12-1,1>>^ Miriã e Arão começaram a criticar Moisés porque ele havia se casado com uma mulher cuxita.

[[v4-12-2]]

^<<v4-12-2,2>>^ "Será que o Senhor tem falado apenas por meio de Moisés? ", perguntaram. "Também não tem ele falado por meio de nós? " E o Senhor ouviu isso.

[[v4-12-3]]

^<<v4-12-3,3>>^ Ora, Moisés era um homem muito paciente, mais do que qualquer outro que havia na terra.

[[v4-12-4]]

^<<v4-12-4,4>>^ Imediatamente o Senhor disse a Moisés, a Arão e a Miriã: "Dirijam-se à Tenda do Encontro, vocês três". E os três foram para lá.

[[v4-12-5]]

^<<v4-12-5,5>>^ Então o Senhor desceu numa coluna de nuvem e, pondo-se à entrada da Tenda, chamou Arão e Miriã. Os dois vieram à frente,

[[v4-12-6]]

^<<v4-12-6,6>>^ e ele disse: "Ouçam as minhas palavras: Quando entre vocês há um profeta do Senhor, a ele me revelo em visões, em sonhos falo com ele.

[[v4-12-7]]

^<<v4-12-7,7>>^ Não é assim, porém, com meu servo Moisés, que é fiel em toda a minha casa.

[[v4-12-8]]

^<<v4-12-8,8>>^ Com ele falo face a face, claramente, e não por enigmas; e ele vê a forma do Senhor. Por que não temeram criticar meu servo Moisés? "

[[v4-12-9]]

^<<v4-12-9,9>>^ Então a ira do Senhor acendeu-se contra eles, e ele os deixou.

[[v4-12-10]]

^<<v4-12-10,10>>^ Quando a nuvem se afastou da Tenda, Miriã estava leprosa; sua aparência era como a da neve. Arão voltou-se para ela, viu que ela estava com lepra

[[v4-12-11]]

^<<v4-12-11,11>>^ e disse a Moisés: "Por favor, meu senhor, não nos castigue pelo pecado que tão tolamente cometemos.

[[v4-12-12]]

^<<v4-12-12,12>>^ Não permita que ela fique como um feto abortado que sai do ventre de sua mãe com a metade do corpo destruído".

[[v4-12-13]]

^<<v4-12-13,13>>^ Então Moisés clamou ao Senhor: "Ó Deus, por misericórdia, cura-a! "

[[v4-12-14]]

^<<v4-12-14,14>>^ O Senhor respondeu a Moisés: "Se o pai dela lhe tivesse cuspido no rosto, não estaria ela envergonhada sete dias? Que fique isolada fora do acampamento sete dias; depois ela poderá ser trazida de volta".

[[v4-12-15]]

^<<v4-12-15,15>>^ Então Miriã ficou isolada sete dias fora do acampamento, e o povo não partiu enquanto ela não foi trazida de volta.

[[v4-12-16]]

^<<v4-12-16,16>>^ Depois disso, partiram de Hazerote e acamparam no deserto de Parã.

'''

xref:004-numeros/004-numeros-011.adoc#v4-11-0[&#60; Capítulo Anterior] | <<v4-12-0,Topo>> | xref:004-numeros/004-numeros-013.adoc#v4-13-0[Próximo Capítulo &#62;]