include::./index.adoc[]

[[v4-22-0]]
=== Números, 22
// nvi ?, NVI - Nova Versão Internacional

[[v4-22-1]]

^<<v4-22-1,1>>^ Os israelitas partiram e acamparam nas campinas de Moabe, para além do Jordão, perto de Jericó.

[[v4-22-2]]

^<<v4-22-2,2>>^ Balaque, filho de Zipor, viu tudo o que Israel tinha feito aos amorreus,

[[v4-22-3]]

^<<v4-22-3,3>>^ e Moabe teve muito medo do povo, porque era muita gente. Moabe teve pavor dos israelitas.

[[v4-22-4]]

^<<v4-22-4,4>>^ Então os moabitas disseram aos líderes de Midiã: "Essa multidão devorará tudo o que há ao nosso redor, como o boi devora o capim do pasto". Balaque, filho de Zipor, rei de Moabe naquela época,

[[v4-22-5]]

^<<v4-22-5,5>>^ enviou mensageiros para chamar Balaão, filho de Beor, que estava em Petor, perto do Rio, em sua terra natal. A mensagem de Balaque dizia: "Um povo que saiu do Egito cobre a face da terra e se estabeleceu perto de mim.

[[v4-22-6]]

^<<v4-22-6,6>>^ Venha agora lançar uma maldição contra ele, pois é forte demais para mim. Talvez então eu tenha condições de derrotá-lo e de expulsá-lo da terra. Pois sei que quem você abençoa é abençoado, e quem você amaldiçoa é amaldiçoado".

[[v4-22-7]]

^<<v4-22-7,7>>^ Os líderes de Moabe e os de Midiã partiram, levando consigo o preço para os encantamentos mágicos. Quando chegaram, comunicaram a Balaão o que Balaque tinha dito.

[[v4-22-8]]

^<<v4-22-8,8>>^ Disse-lhes Balaão: "Passem a noite aqui, e eu lhes trarei a resposta que o Senhor me der". E os líderes moabitas ficaram com ele.

[[v4-22-9]]

^<<v4-22-9,9>>^ Deus veio a Balaão e lhe perguntou: "Quem são esses homens que estão com você? "

[[v4-22-10]]

^<<v4-22-10,10>>^ Balaão respondeu a Deus: "Balaque, filho de Zipor, rei de Moabe, enviou-me esta mensagem:

[[v4-22-11]]

^<<v4-22-11,11>>^ ‘Um povo que saiu do Egito cobre a face da terra. Venha agora lançar uma maldição contra ele. Talvez então eu tenha condições de derrotá-lo e de expulsá-lo’ ".

[[v4-22-12]]

^<<v4-22-12,12>>^ Mas Deus disse a Balaão: "Não vá com eles. Você não poderá amaldiçoar este povo, porque é povo abençoado".

[[v4-22-13]]

^<<v4-22-13,13>>^ Na manhã seguinte Balaão se levantou e disse aos líderes de Balaque: "Voltem para a sua terra, pois o Senhor não permitiu que eu os acompanhe".

[[v4-22-14]]

^<<v4-22-14,14>>^ Os líderes moabitas voltaram a Balaque e lhe disseram: "Balaão recusou-se a acompanhar-nos".

[[v4-22-15]]

^<<v4-22-15,15>>^ Balaque enviou outros líderes, em maior número e mais importantes do que os primeiros.

[[v4-22-16]]

^<<v4-22-16,16>>^ Eles foram a Balaão e lhe disseram: "Assim diz Balaque, filho de Zipor: Que nada o impeça de vir a mim,

[[v4-22-17]]

^<<v4-22-17,17>>^ porque o recompensarei generosamente e farei tudo o que você me disser. Venha, por favor, e lance para mim uma maldição contra este povo".

[[v4-22-18]]

^<<v4-22-18,18>>^ Balaão, porém, respondeu aos conselheiros de Balaque: "Mesmo que Balaque me desse o seu palácio cheio de prata e de ouro, eu não poderia fazer coisa alguma, grande ou pequena, que vá além da ordem do Senhor meu Deus.

[[v4-22-19]]

^<<v4-22-19,19>>^ Agora, fiquem também vocês aqui esta noite, e eu descobrirei o que mais o Senhor tem para dizer-me".

[[v4-22-20]]

^<<v4-22-20,20>>^ Naquela noite Deus veio a Balaão e lhe disse: "Visto que esses homens vieram chamá-lo, vá com eles, mas faça apenas o que eu lhe disser".

[[v4-22-21]]

^<<v4-22-21,21>>^ Balaão levantou-se pela manhã, pôs a sela sobre a sua jumenta e foi com os líderes de Moabe.

[[v4-22-22]]

^<<v4-22-22,22>>^ Mas acendeu-se a ira de Deus quando ele foi, e o anjo do Senhor pôs-se no caminho para impedi-lo de prosseguir. Balaão ia montado em sua jumenta, e seus dois servos o acompanhavam.

[[v4-22-23]]

^<<v4-22-23,23>>^ Quando a jumenta viu o anjo do Senhor parado no caminho, empunhando uma espada, saiu do caminho e foi-se pelo campo. Balaão bateu nela para fazê-la voltar ao caminho.

[[v4-22-24]]

^<<v4-22-24,24>>^ Então o anjo do Senhor se pôs num caminho estreito entre duas vinhas, com muros dos dois lados.

[[v4-22-25]]

^<<v4-22-25,25>>^ Quando a jumenta viu o anjo do Senhor, encostou-se no muro, apertando o pé de Balaão contra ele. Por isso ele bateu nela de novo.

[[v4-22-26]]

^<<v4-22-26,26>>^ O anjo do Senhor foi adiante e se colocou num lugar estreito, e não havia espaço para desviar, nem para a direita nem para a esquerda.

[[v4-22-27]]

^<<v4-22-27,27>>^ Quando a jumenta viu o anjo do Senhor, deitou-se debaixo de Balaão. Acendeu-se a ira de Balaão, que bateu nela com a sua vara.

[[v4-22-28]]

^<<v4-22-28,28>>^ Então o Senhor abriu a boca da jumenta, e ela disse a Balaão: "Que foi que eu lhe fiz, para você bater em mim três vezes? "

[[v4-22-29]]

^<<v4-22-29,29>>^ Balaão respondeu à jumenta: "Você me fez de tolo! Quem dera eu tivesse uma espada na mão; eu a mataria agora mesmo".

[[v4-22-30]]

^<<v4-22-30,30>>^ Mas a jumenta disse a Balaão: "Não sou sua jumenta, que você sempre montou até o dia de hoje? Tenho eu o costume de fazer isso com você? " "Não", disse ele.

[[v4-22-31]]

^<<v4-22-31,31>>^ Então o Senhor abriu os olhos de Balaão, e ele viu o anjo do Senhor parado no caminho, empunhando a sua espada. Então Balaão inclinou-se e prostrou-se, rosto em terra.

[[v4-22-32]]

^<<v4-22-32,32>>^ E o anjo do Senhor lhe perguntou: "Por que você bateu três vezes em sua jumenta? Eu vim aqui para impedi-lo de prosseguir porque o seu caminho me desagrada.

[[v4-22-33]]

^<<v4-22-33,33>>^ A jumenta me viu e se afastou de mim por três vezes. Se ela não se afastasse a esta altura eu certamente o teria matado; mas a ela eu teria poupado".

[[v4-22-34]]

^<<v4-22-34,34>>^ Balaão disse ao anjo do Senhor: "Pequei. Não percebi que estavas parado no caminho para me impedires de prosseguir. Agora, se o que estou fazendo te desagrada, eu voltarei".

[[v4-22-35]]

^<<v4-22-35,35>>^ Então o anjo do Senhor disse a Balaão: "Vá com os homens, mas fale apenas o que eu lhe disser". Assim Balaão foi com os príncipes de Balaque.

[[v4-22-36]]

^<<v4-22-36,36>>^ Quando Balaque soube que Balaão estava chegando, foi ao seu encontro na cidade moabita da fronteira do Arnom, no limite do seu território.

[[v4-22-37]]

^<<v4-22-37,37>>^ E Balaque disse a Balaão: "Não mandei chamá-lo urgentemente? Por que não veio? Acaso não tenho condições de recompensá-lo? "

[[v4-22-38]]

^<<v4-22-38,38>>^ "Aqui estou! ", respondeu Balaão. "Mas, seria eu capaz de dizer alguma coisa? Direi somente o que Deus puser em minha boca".

[[v4-22-39]]

^<<v4-22-39,39>>^ Então Balaão foi com Balaque até Quiriate-Huzote.

[[v4-22-40]]

^<<v4-22-40,40>>^ Balaque sacrificou bois e ovelhas, e deu parte da carne a Balaão e aos líderes que com ele estavam.

[[v4-22-41]]

^<<v4-22-41,41>>^ Na manhã seguinte Balaque levou Balaão até o alto de Bamote-Baal, de onde viu uma parte do povo.

'''

xref:004-numeros/004-numeros-021.adoc#v4-21-0[&#60; Capítulo Anterior] | <<v4-22-0,Topo>> | xref:004-numeros/004-numeros-023.adoc#v4-23-0[Próximo Capítulo &#62;]