include::./index.adoc[]

[[v4-2-0]]
=== Números, 2
// nvi ?, NVI - Nova Versão Internacional

[[v4-2-1]]

^<<v4-2-1,1>>^ O Senhor disse a Moisés e a Arão:

[[v4-2-2]]

^<<v4-2-2,2>>^ "Os israelitas acamparão ao redor da Tenda do Encontro, a certa distância, cada homem junto à sua bandeira com os emblemas da sua família".

[[v4-2-3]]

^<<v4-2-3,3>>^ A leste, os exércitos de Judá acamparão junto à sua bandeira. O líder de Judá será Naassom, filho de Aminadabe.

[[v4-2-4]]

^<<v4-2-4,4>>^ Seu exército é de 74. 600 homens.

[[v4-2-5]]

^<<v4-2-5,5>>^ A tribo de Issacar acampará ao lado de Judá. O líder de Issacar será Natanael, filho de Zuar.

[[v4-2-6]]

^<<v4-2-6,6>>^ Seu exército é de 54. 400 homens.

[[v4-2-7]]

^<<v4-2-7,7>>^ A tribo de Zebulom virá em seguida. O líder de Zebulom será Eliabe, filho de Helom.

[[v4-2-8]]

^<<v4-2-8,8>>^ Seu exército é de 57. 400 homens.

[[v4-2-9]]

^<<v4-2-9,9>>^ O número total dos homens recenseados do acampamento de Judá, de acordo com os seus exércitos, foi 186. 400. Esses marcharão primeiro.

[[v4-2-10]]

^<<v4-2-10,10>>^ Ao sul estarão os exércitos do acampamento de Rúben, junto à sua bandeira. O líder de Rúben será Elizur, filho de Sedeur.

[[v4-2-11]]

^<<v4-2-11,11>>^ Seu exército é de 46. 500 homens.

[[v4-2-12]]

^<<v4-2-12,12>>^ A tribo de Simeão acampará ao lado de Rúben. O líder de Simeão será Selumiel, filho de Zurisadai.

[[v4-2-13]]

^<<v4-2-13,13>>^ Seu exército é de 59. 300 homens.

[[v4-2-14]]

^<<v4-2-14,14>>^ A tribo de Gade virá em seguida. O líder de Gade será Eliasafe, filho de Deuel.

[[v4-2-15]]

^<<v4-2-15,15>>^ Seu exército é de 45. 650 homens.

[[v4-2-16]]

^<<v4-2-16,16>>^ O número total dos homens recenseados do acampamento de Rúben, de acordo com os seus exércitos, foi 151. 450. Esses marcharão em segundo lugar.

[[v4-2-17]]

^<<v4-2-17,17>>^ Em seguida os levitas marcharão levando a Tenda do Encontro no meio dos outros acampamentos, na mesma ordem em que acamparem, cada um em seu próprio lugar, junto à sua bandeira.

[[v4-2-18]]

^<<v4-2-18,18>>^ A oeste estarão os exércitos do acampamento de Efraim, junto à sua bandeira. O líder de Efraim será Elisama, filho de Amiúde.

[[v4-2-19]]

^<<v4-2-19,19>>^ Seu exército é de 40. 500 homens.

[[v4-2-20]]

^<<v4-2-20,20>>^ A tribo de Manassés acampará ao lado de Efraim. O líder de Manassés será Gamaliel, filho de Pedazur.

[[v4-2-21]]

^<<v4-2-21,21>>^ Seu exército é de 32. 200 homens.

[[v4-2-22]]

^<<v4-2-22,22>>^ A tribo de Benjamim virá em seguida. O líder de Benjamim será Abidã, filho de Gideoni.

[[v4-2-23]]

^<<v4-2-23,23>>^ Seu exército é de 35. 400 homens.

[[v4-2-24]]

^<<v4-2-24,24>>^ O número total dos homens recenseados do acampamento de Efraim, de acordo com os seus exércitos, foi 108. 100. Esses marcharão em terceiro lugar.

[[v4-2-25]]

^<<v4-2-25,25>>^ Ao norte estarão os exércitos do acampamento de Dã, junto à sua bandeira. O líder de Dã será Aieser, filho de Amisadai.

[[v4-2-26]]

^<<v4-2-26,26>>^ Seu exército é de 62. 700 homens.

[[v4-2-27]]

^<<v4-2-27,27>>^ A tribo de Aser acampará ao lado de Dã. O líder de Aser será Pagiel, filho de Ocrã.

[[v4-2-28]]

^<<v4-2-28,28>>^ Seu exército é de 41. 500 homens.

[[v4-2-29]]

^<<v4-2-29,29>>^ A tribo de Naftali virá em seguida. O líder de Naftali será Aira, filho de Enã.

[[v4-2-30]]

^<<v4-2-30,30>>^ Seu exército é de 53. 400 homens.

[[v4-2-31]]

^<<v4-2-31,31>>^ O número total dos homens recenseados do acampamento de Dã, de acordo com os seus exércitos, foi 157. 600. Estes marcharão por último, junto às suas bandeiras.

[[v4-2-32]]

^<<v4-2-32,32>>^ Foram esses os israelitas contados de acordo com as suas famílias. O número total dos que foram contados nos acampamentos, de acordo com os seus exércitos, foi 603. 550.

[[v4-2-33]]

^<<v4-2-33,33>>^ Os levitas, contudo, não foram contados com os outros israelitas, conforme o Senhor tinha ordenado a Moisés.

[[v4-2-34]]

^<<v4-2-34,34>>^ Assim os israelitas fizeram tudo o que o Senhor tinha ordenado a Moisés; eles acampavam junto às suas bandeiras e depois partiam, cada um com o seu clã e com a sua família.

'''

xref:004-numeros/004-numeros-001.adoc#v4-1-0[&#60; Capítulo Anterior] | <<v4-2-0,Topo>> | xref:004-numeros/004-numeros-003.adoc#v4-3-0[Próximo Capítulo &#62;]