include::./index.adoc[]

[[v4-26-0]]
=== Números, 26
// nvi ?, NVI - Nova Versão Internacional

[[v4-26-1]]

^<<v4-26-1,1>>^ Depois da praga, o Senhor disse a Moisés e a Eleazar, filho do sacerdote Arão:

[[v4-26-2]]

^<<v4-26-2,2>>^ "Façam um recenseamento de toda a comunidade de Israel, segundo as suas famílias; contem todos os de vinte anos para cima que possam servir no exército de Israel".

[[v4-26-3]]

^<<v4-26-3,3>>^ Nas campinas de Moabe, junto ao Jordão, do outro lado de Jericó, Moisés e o sacerdote Eleazar falaram com eles e disseram:

[[v4-26-4]]

^<<v4-26-4,4>>^ "Façam um recenseamento dos homens de vinte anos para cima", conforme o Senhor tinha ordenado a Moisés. Estes foram os israelitas que saíram do Egito:

[[v4-26-5]]

^<<v4-26-5,5>>^ Os descendentes de Rúben, filho mais velho de Israel, foram: de Enoque, o clã enoquita; de Palu, o clã paluíta;

[[v4-26-6]]

^<<v4-26-6,6>>^ de Hezrom, o clã hezronita; de Carmi, o clã carmita.

[[v4-26-7]]

^<<v4-26-7,7>>^ Esses foram os clãs de Rúben; foram contados 43. 730 homens.

[[v4-26-8]]

^<<v4-26-8,8>>^ O filho de Palu foi Eliabe,

[[v4-26-9]]

^<<v4-26-9,9>>^ e os filhos de Eliabe foram Nemuel, Datã e Abirão. Estes, Datã e Abirão, foram os líderes da comunidade que se rebelaram contra Moisés e contra Arão, estando entre os seguidores de Corá quando se rebelaram contra o Senhor.

[[v4-26-10]]

^<<v4-26-10,10>>^ A terra abriu a boca e os engoliu juntamente com Corá, cujos seguidores morreram quando o fogo devorou duzentos e cinqüenta homens, que serviram como sinal de advertência.

[[v4-26-11]]

^<<v4-26-11,11>>^ A descendência de Corá, contudo, não desapareceu.

[[v4-26-12]]

^<<v4-26-12,12>>^ Os descendentes de Simeão segundo os seus clãs foram: de Nemuel, o clã nemuelita; de Jamim, o clã jaminita; de Jaquim, o clã jaquinita;

[[v4-26-13]]

^<<v4-26-13,13>>^ de Zerá, o clã zeraíta; de Saul, o clã saulita.

[[v4-26-14]]

^<<v4-26-14,14>>^ Esses foram os clãs de Simeão; havia 22. 200 homens.

[[v4-26-15]]

^<<v4-26-15,15>>^ Os descendentes de Gade segundo os seus clãs foram: de Zefom, o clã zefonita; de Hagi, o clã hagita; de Suni, o clã sunita;

[[v4-26-16]]

^<<v4-26-16,16>>^ de Ozni, o clã oznita; de Eri, o clã erita;

[[v4-26-17]]

^<<v4-26-17,17>>^ de Arodi, o clã arodita; de Areli, o clã arelita.

[[v4-26-18]]

^<<v4-26-18,18>>^ Esses foram os clãs de Gade; foram contados 40. 500 homens.

[[v4-26-19]]

^<<v4-26-19,19>>^ Er e Onã eram filhos de Judá, mas morreram em Canaã.

[[v4-26-20]]

^<<v4-26-20,20>>^ Os descendentes de Judá segundo os seus clãs foram: de Selá, o clã selanita; de Perez, o clã perezita; de Zerá, o clã zeraíta.

[[v4-26-21]]

^<<v4-26-21,21>>^ Os descendentes de Perez foram: de Hezrom, o clã hezronita; de Hamul, o clã hamulita.

[[v4-26-22]]

^<<v4-26-22,22>>^ Esses foram os clãs de Judá; foram contados 76. 500 homens.

[[v4-26-23]]

^<<v4-26-23,23>>^ Os descendentes de Issacar segundo os seus clãs foram: de Tolá, o clã tolaíta; de Puá, o clã puvita;

[[v4-26-24]]

^<<v4-26-24,24>>^ de Jasube, o clã jasubita; de Sinrom, o clã sinronita.

[[v4-26-25]]

^<<v4-26-25,25>>^ Esses foram os clãs de Issacar; foram contados 64. 300 homens.

[[v4-26-26]]

^<<v4-26-26,26>>^ Os descendentes de Zebulom segundo os seus clãs foram: de Serede, o clã seredita; de Elom, o clã elonita; de Jaleel, o clã jaleelita.

[[v4-26-27]]

^<<v4-26-27,27>>^ Esses foram os clãs de Zebulom; foram contados 60. 500 homens.

[[v4-26-28]]

^<<v4-26-28,28>>^ Os descendentes de José segundo os seus clãs, por meio de Manassés e Efraim, foram:

[[v4-26-29]]

^<<v4-26-29,29>>^ Os descendentes de Manassés: de Maquir, o clã maquirita ( Maquir foi o pai de Gileade ); de Gileade, o clã gileadita.

[[v4-26-30]]

^<<v4-26-30,30>>^ Estes foram os descendentes de Gileade: de Jezer, o clã jezerita; de Heleque, o clã helequita;

[[v4-26-31]]

^<<v4-26-31,31>>^ de Asriel, o clã asrielita; de Siquém, o clã siquemita;

[[v4-26-32]]

^<<v4-26-32,32>>^ de Semida, o clã semidaíta; de Héfer, o clã heferita.

[[v4-26-33]]

^<<v4-26-33,33>>^ ( Zelofeade, filho de Héfer, não teve filhos; teve somente filhas, cujos nomes eram Maalá, Noa, Hogla, Milca e Tirza. )

[[v4-26-34]]

^<<v4-26-34,34>>^ Esses foram os clãs de Manassés; foram contados 52. 700 homens.

[[v4-26-35]]

^<<v4-26-35,35>>^ Os descendentes de Efraim segundo os seus clãs foram: de Sutela, o clã sutelaíta; de Bequer, o clã bequerita; de Taã, o clã taanita.

[[v4-26-36]]

^<<v4-26-36,36>>^ Estes foram os descendentes de Sutela: de Erã, o clã eranita.

[[v4-26-37]]

^<<v4-26-37,37>>^ Esses foram os clãs de Efraim; foram contados 32. 500 homens. Esses foram os descendentes de José segundo os seus clãs.

[[v4-26-38]]

^<<v4-26-38,38>>^ Os descendentes de Benjamim segundo os seus clãs foram: de Belá, o clã belaíta; de Asbel, o clã asbelita; de Airã, o clã airamita;

[[v4-26-39]]

^<<v4-26-39,39>>^ de Sufã; o clã sufamita; de Hufã, o clã hufamita.

[[v4-26-40]]

^<<v4-26-40,40>>^ Os descendentes de Belá por meio de Arde e Naamã foram: de Arde, o clã ardita; de Naamã, o clã naamanita.

[[v4-26-41]]

^<<v4-26-41,41>>^ Esses foram os clãs de Benjamim; foram contados 45. 600 homens.

[[v4-26-42]]

^<<v4-26-42,42>>^ Os descendentes de Dã segundo os seus clãs foram: de Suã, o clã suamita. Esses foram os clãs de Dã:

[[v4-26-43]]

^<<v4-26-43,43>>^ Todos eles eram clãs suamitas; foram contados 64. 400 homens.

[[v4-26-44]]

^<<v4-26-44,44>>^ Os descendentes de Aser segundo os seus clãs foram: de Imna, o clã imnaíta; de Isvi, o clã isvita; de Berias, o clã beriaíta;

[[v4-26-45]]

^<<v4-26-45,45>>^ e dos descendentes de Berias: de Héber, o clã heberita; de Malquiel, o clã malquielita.

[[v4-26-46]]

^<<v4-26-46,46>>^ Aser teve uma filha chamada Sera.

[[v4-26-47]]

^<<v4-26-47,47>>^ Esses foram os clãs de Aser; foram contados 53. 400 homens.

[[v4-26-48]]

^<<v4-26-48,48>>^ Os descendentes de Naftali segundo os seus clãs foram: de Jazeel, o clã jazeelita; de Guni, o clã gunita;

[[v4-26-49]]

^<<v4-26-49,49>>^ de Jezer, o clã jezerita; de Silém, o clã silemita.

[[v4-26-50]]

^<<v4-26-50,50>>^ Esses foram os clãs de Naftali; foram contados 45. 400 homens.

[[v4-26-51]]

^<<v4-26-51,51>>^ O número total dos homens de Israel foi 601. 730.

[[v4-26-52]]

^<<v4-26-52,52>>^ Disse ainda o Senhor a Moisés:

[[v4-26-53]]

^<<v4-26-53,53>>^ "A terra será repartida entre eles como herança, de acordo com o número dos nomes alistados.

[[v4-26-54]]

^<<v4-26-54,54>>^ A um clã maior dê uma herança maior, e a um clã menor, uma herança menor; cada um receberá a sua herança de acordo com o seu número de recenseados.

[[v4-26-55]]

^<<v4-26-55,55>>^ A terra, porém, será distribuída por sorteio. Cada um herdará sua parte de acordo com o nome da tribo de seus antepassados.

[[v4-26-56]]

^<<v4-26-56,56>>^ Cada herança será distribuída por sorteio entre os clãs maiores e entre os clãs menores". O Segundo Recenseamento dos Levitas

[[v4-26-57]]

^<<v4-26-57,57>>^ Estes foram os levitas contados segundo os seus clãs: de Gérson, o clã gersonita; de Coate, o clã coatita; de Merari, o clã merarita.

[[v4-26-58]]

^<<v4-26-58,58>>^ Estes também eram clãs levitas: o clã libnita; o clã hebronita; o clã malita; o clã musita; o clã coreíta. Coate foi o pai de Anrão;

[[v4-26-59]]

^<<v4-26-59,59>>^ o nome da mulher de Anrão era Joquebede, descendente de Levi, que nasceu no Egito. Ela lhe deu à luz Arão, Moisés e Miriã, irmã deles.

[[v4-26-60]]

^<<v4-26-60,60>>^ Arão foi o pai de Nadabe, Abiú, Eleazar e Itamar.

[[v4-26-61]]

^<<v4-26-61,61>>^ Mas Nadabe e Abiú morreram quando apresentaram uma oferta com fogo profano perante o Senhor.

[[v4-26-62]]

^<<v4-26-62,62>>^ O total de levitas do sexo masculino de um mês de idade para cima que foram contados foi 23. 000. Não foram contados junto com os outros israelitas porque não receberam herança entre eles.

[[v4-26-63]]

^<<v4-26-63,63>>^ São esses os que foram recenseados por Moisés e pelo sacerdote Eleazar quando contaram os israelitas nas campinas de Moabe, junto ao Jordão, do outro lado de Jericó.

[[v4-26-64]]

^<<v4-26-64,64>>^ Nenhum deles estava entre os que foram contados por Moisés e pelo sacerdote Arão quando contaram os israelitas no deserto do Sinai.

[[v4-26-65]]

^<<v4-26-65,65>>^ Pois o Senhor tinha dito àqueles israelitas que iriam morrer no deserto, e nenhum deles sobreviveu, exceto Calebe, filho de Jefoné, e Josué, filho de Num.

'''

xref:004-numeros/004-numeros-025.adoc#v4-25-0[&#60; Capítulo Anterior] | <<v4-26-0,Topo>> | xref:004-numeros/004-numeros-027.adoc#v4-27-0[Próximo Capítulo &#62;]