include::./index.adoc[]

[[v4-33-0]]
=== Números, 33
// nvi ?, NVI - Nova Versão Internacional

[[v4-33-1]]

^<<v4-33-1,1>>^ Estas são as jornadas dos israelitas quando saíram do Egito, organizados segundo as suas divisões, sob a liderança de Moisés e Arão.

[[v4-33-2]]

^<<v4-33-2,2>>^ Por ordem do Senhor Moisés registrou as etapas da jornada deles. Esta foi a jornada deles, por etapas:

[[v4-33-3]]

^<<v4-33-3,3>>^ Os israelitas partiram de Ramessés no décimo quinto dia do primeiro mês, no dia seguinte ao da Páscoa. Saíram, marchando desafiadoramente à vista de todos os egípcios,

[[v4-33-4]]

^<<v4-33-4,4>>^ enquanto estes sepultavam o primeiro filho de cada um deles, que o Senhor matou. O Senhor impôs castigo aos seus deuses.

[[v4-33-5]]

^<<v4-33-5,5>>^ Os israelitas partiram de Ramessés e acamparam em Sucote.

[[v4-33-6]]

^<<v4-33-6,6>>^ Partiram de Sucote e acamparam em Etã, nos limites do deserto.

[[v4-33-7]]

^<<v4-33-7,7>>^ Partiram de Etã, voltaram para Pi-Hairote, a leste de Baal-Zefom, e acamparam perto de Migdol.

[[v4-33-8]]

^<<v4-33-8,8>>^ Partiram de Pi-Hairote e atravessaram o mar chegando ao deserto, e, depois de viajarem três dias no deserto de Etã, acamparam em Mara.

[[v4-33-9]]

^<<v4-33-9,9>>^ Partiram de Mara e foram para Elim, onde havia doze fontes e setenta palmeiras, e acamparam ali.

[[v4-33-10]]

^<<v4-33-10,10>>^ Partiram de Elim e acamparam junto ao mar Vermelho.

[[v4-33-11]]

^<<v4-33-11,11>>^ Partiram do mar Vermelho e acamparam no deserto de Sim.

[[v4-33-12]]

^<<v4-33-12,12>>^ Partiram do deserto de Sim e acamparam em Dofca.

[[v4-33-13]]

^<<v4-33-13,13>>^ Partiram de Dofca e acamparam em Alus.

[[v4-33-14]]

^<<v4-33-14,14>>^ Partiram de Alus e acamparam em Refidim, onde não havia água para o povo beber.

[[v4-33-15]]

^<<v4-33-15,15>>^ Partiram de Refidim e acamparam no deserto do Sinai.

[[v4-33-16]]

^<<v4-33-16,16>>^ Partiram do deserto do Sinai e acamparam em Quibrote-Hataavá.

[[v4-33-17]]

^<<v4-33-17,17>>^ Partiram de Quibrote-Hataavá e acamparam em Hazerote.

[[v4-33-18]]

^<<v4-33-18,18>>^ Partiram de Hazerote e acamparam em Ritmá.

[[v4-33-19]]

^<<v4-33-19,19>>^ Partiram de Ritmá e acamparam em Rimom-Perez.

[[v4-33-20]]

^<<v4-33-20,20>>^ Partiram de Rimom-Perez e acamparam em Libna.

[[v4-33-21]]

^<<v4-33-21,21>>^ Partiram de Libna e acamparam em Rissa.

[[v4-33-22]]

^<<v4-33-22,22>>^ Partiram de Rissa e acamparam em Queelata.

[[v4-33-23]]

^<<v4-33-23,23>>^ Partiram de Queelata e acamparam no monte Séfer.

[[v4-33-24]]

^<<v4-33-24,24>>^ Partiram do monte Séfer e acamparam em Harada.

[[v4-33-25]]

^<<v4-33-25,25>>^ Partiram de Harada e acamparam em Maquelote.

[[v4-33-26]]

^<<v4-33-26,26>>^ Partiram de Maquelote e acamparam em Taate.

[[v4-33-27]]

^<<v4-33-27,27>>^ Partiram de Taate e acamparam em Terá.

[[v4-33-28]]

^<<v4-33-28,28>>^ Partiram de Terá e acamparam em Mitca.

[[v4-33-29]]

^<<v4-33-29,29>>^ Partiram de Mitca e acamparam em Hasmona.

[[v4-33-30]]

^<<v4-33-30,30>>^ Partiram de Hasmona e acamparam em Moserote.

[[v4-33-31]]

^<<v4-33-31,31>>^ Partiram de Moserote e acamparam em Benê-Jaacã.

[[v4-33-32]]

^<<v4-33-32,32>>^ Partiram de Benê-Jaacã e acamparam em Hor-Gidgade.

[[v4-33-33]]

^<<v4-33-33,33>>^ Partiram de Hor-Gidgade e acamparam em Jotbatá.

[[v4-33-34]]

^<<v4-33-34,34>>^ Partiram de Jotbatá e acamparam em Abrona.

[[v4-33-35]]

^<<v4-33-35,35>>^ Partiram de Abrona e acamparam em Eziom-Geber.

[[v4-33-36]]

^<<v4-33-36,36>>^ Partiram de Eziom-Geber e acamparam em Cades, no deserto de Zim.

[[v4-33-37]]

^<<v4-33-37,37>>^ Partiram de Cades e acamparam no monte Hor, na fronteira de Edom.

[[v4-33-38]]

^<<v4-33-38,38>>^ Por ordem do Senhor, o sacerdote Arão subiu o monte Hor, onde morreu no dia primeiro do quinto mês do quadragésimo ano depois que os israelitas saíram do Egito.

[[v4-33-39]]

^<<v4-33-39,39>>^ Arão tinha cento e vinte e três anos de idade quando morreu no monte Hor.

[[v4-33-40]]

^<<v4-33-40,40>>^ O rei cananeu de Arade, que vivia no Neguebe, na terra de Canaã, soube que os israelitas estavam chegando.

[[v4-33-41]]

^<<v4-33-41,41>>^ Eles partiram do monte Hor e acamparam em Zalmona.

[[v4-33-42]]

^<<v4-33-42,42>>^ Partiram de Zalmona e acamparam em Punom.

[[v4-33-43]]

^<<v4-33-43,43>>^ Partiram de Punom e acamparam em Obote.

[[v4-33-44]]

^<<v4-33-44,44>>^ Partiram de Obote e acamparam em Ijé-Abarim, na fronteira de Moabe.

[[v4-33-45]]

^<<v4-33-45,45>>^ Partiram de Ijim e acamparam em Dibom-Gade.

[[v4-33-46]]

^<<v4-33-46,46>>^ Partiram de Dibom-Gade e acamparam em Almom-Diblataim.

[[v4-33-47]]

^<<v4-33-47,47>>^ Partiram de Almom-Diblataim e acamparam nos montes de Abarim, defronte de Nebo.

[[v4-33-48]]

^<<v4-33-48,48>>^ Partiram dos montes de Abarim e acamparam nas campinas de Moabe junto ao Jordão, do outro lado de Jericó.

[[v4-33-49]]

^<<v4-33-49,49>>^ Nas campinas de Moabe eles acamparam junto ao Jordão, desde Bete-Jesimote até Abel-Sitim.

[[v4-33-50]]

^<<v4-33-50,50>>^ Nas campinas de Moabe, junto ao Jordão, do outro lado de Jericó, o Senhor disse a Moisés:

[[v4-33-51]]

^<<v4-33-51,51>>^ "Diga aos israelitas: Quando vocês atravessarem o Jordão para entrar em Canaã,

[[v4-33-52]]

^<<v4-33-52,52>>^ expulsem da frente de vocês todos os habitantes da terra. Destruam todas as imagens esculpidas e todos os ídolos fundidos, e derrubem todos os altares idólatras deles.

[[v4-33-53]]

^<<v4-33-53,53>>^ Apoderem-se da terra e instalem-se nela, pois eu lhes dei a terra para que dela tomem posse.

[[v4-33-54]]

^<<v4-33-54,54>>^ Distribuam a terra por sorteio, de acordo com os seus clãs. Aos clãs vocês darão uma herança maior, e aos menores, uma herança menor. Cada clã receberá a terra que lhe cair por sorte. Distribuam-na entre as tribos dos seus antepassados.

[[v4-33-55]]

^<<v4-33-55,55>>^ "Se, contudo, vocês não expulsarem os habitantes da terra, aqueles que vocês permitirem ficar se tornarão farpas em seus olhos e espinhos em suas costas. Eles lhes causarão problemas na terra em que vocês irão morar.

[[v4-33-56]]

^<<v4-33-56,56>>^ Então farei a vocês o mesmo que planejo fazer a eles".

'''

xref:004-numeros/004-numeros-032.adoc#v4-32-0[&#60; Capítulo Anterior] | <<v4-33-0,Topo>> | xref:004-numeros/004-numeros-034.adoc#v4-34-0[Próximo Capítulo &#62;]