include::./index.adoc[]

[[v4-27-0]]
=== Números, 27
// nvi ?, NVI - Nova Versão Internacional

[[v4-27-1]]

^<<v4-27-1,1>>^ Aproximaram-se as filhas de Zelofeade, filho de Héfer, neto de Gileade, bisneto de Maquir, trineto de Manassés; pertencia aos clãs de Manassés, filho de José. Os nomes das suas filhas eram Maalá, Noa, Hogla, Milca e Tirza.

[[v4-27-2]]

^<<v4-27-2,2>>^ Elas se prostraram à entrada da Tenda do Encontro diante de Moisés, do sacerdote Eleazar, dos líderes de toda a comunidade, e disseram:

[[v4-27-3]]

^<<v4-27-3,3>>^ "Nosso pai morreu no deserto. Ele não estava entre os seguidores de Corá, que se ajuntaram contra o Senhor, mas morreu por causa do seu próprio pecado e não deixou filhos.

[[v4-27-4]]

^<<v4-27-4,4>>^ Por que o nome de nosso pai deveria desaparecer de seu clã por não ter tido um filho? Dê-nos propriedade entre os parentes de nosso pai".

[[v4-27-5]]

^<<v4-27-5,5>>^ Moisés levou o caso perante o Senhor,

[[v4-27-6]]

^<<v4-27-6,6>>^ e o Senhor lhe disse:

[[v4-27-7]]

^<<v4-27-7,7>>^ "As filhas de Zelofeade têm razão. Você lhes dará propriedade como herança entre os parentes do pai delas, e lhes passará a herança do pai.

[[v4-27-8]]

^<<v4-27-8,8>>^ "Diga aos israelitas: Se um homem morrer e não deixar filho, transfiram a sua herança para a sua filha.

[[v4-27-9]]

^<<v4-27-9,9>>^ Se ele não tiver filha, dêem a sua herança aos irmãos dele.

[[v4-27-10]]

^<<v4-27-10,10>>^ Se não tiver irmãos, dêem-na aos irmãos de seu pai.

[[v4-27-11]]

^<<v4-27-11,11>>^ Se ainda seu pai não tiver irmãos, dêem a herança ao parente mais próximo em seu clã". Esta será uma exigência legal para os israelitas, como o Senhor ordenou a Moisés.

[[v4-27-12]]

^<<v4-27-12,12>>^ Então o Senhor disse a Moisés: "Suba este monte da serra de Abarim e veja a terra que dei aos israelitas.

[[v4-27-13]]

^<<v4-27-13,13>>^ Depois de vê-la, você também será reunido ao seu povo, como seu irmão Arão,

[[v4-27-14]]

^<<v4-27-14,14>>^ pois, quando a comunidade se rebelou nas águas do deserto de Zim, vocês dois desobedeceram à minha ordem de honrar minha santidade perante eles". Isso aconteceu nas águas de Meribá, em Cades, no deserto de Zim.

[[v4-27-15]]

^<<v4-27-15,15>>^ Moisés disse ao Senhor:

[[v4-27-16]]

^<<v4-27-16,16>>^ "Que o Senhor, o Deus que a todos dá vida, designe um homem como líder desta comunidade

[[v4-27-17]]

^<<v4-27-17,17>>^ para conduzi-los em suas batalhas, para que a comunidade do Senhor não seja como ovelhas sem pastor".

[[v4-27-18]]

^<<v4-27-18,18>>^ Então o Senhor disse a Moisés: "Chame Josué, filho de Num, homem em quem está o Espírito, e imponha as mãos sobre ele.

[[v4-27-19]]

^<<v4-27-19,19>>^ Faça-o apresentar-se ao sacerdote Eleazar e a toda a comunidade e o comissione na presença deles.

[[v4-27-20]]

^<<v4-27-20,20>>^ Dê-lhe parte da sua autoridade para que toda a comunidade de Israel lhe obedeça.

[[v4-27-21]]

^<<v4-27-21,21>>^ Ele deverá apresentar-se ao sacerdote Eleazar, que lhe dará diretrizes ao consultar o Urim perante o Senhor. Josué e toda a comunidade dos israelitas seguirão suas instruções quando saírem para a batalha".

[[v4-27-22]]

^<<v4-27-22,22>>^ Moisés fez como o Senhor lhe ordenou. Chamou Josué e o apresentou ao sacerdote Eleazar e a toda a comunidade.

[[v4-27-23]]

^<<v4-27-23,23>>^ Impôs as mãos sobre ele e o comissionou. Tudo conforme o Senhor tinha dito por meio de Moisés.

'''

xref:004-numeros/004-numeros-026.adoc#v4-26-0[&#60; Capítulo Anterior] | <<v4-27-0,Topo>> | xref:004-numeros/004-numeros-028.adoc#v4-28-0[Próximo Capítulo &#62;]