include::./index.adoc[]

[[v4-15-0]]
=== Números, 15
// nvi ?, NVI - Nova Versão Internacional

[[v4-15-1]]

^<<v4-15-1,1>>^ O Senhor disse a Moisés:

[[v4-15-2]]

^<<v4-15-2,2>>^ "Diga o seguinte aos israelitas: Quando entrarem na terra que lhes dou para sua habitação,

[[v4-15-3]]

^<<v4-15-3,3>>^ e apresentarem ao Senhor uma oferta, de bois ou de ovelhas, preparada no fogo como aroma agradável ao Senhor, seja holocausto, seja sacrifício, para cumprir um voto ou como oferta voluntária ou como oferta relativa a uma festa,

[[v4-15-4]]

^<<v4-15-4,4>>^ aquele que trouxer a sua oferta apresentará também ao Senhor uma oferta de cereal de um jarro da melhor farinha amassada com um litro de óleo.

[[v4-15-5]]

^<<v4-15-5,5>>^ Para cada cordeiro do holocausto ou do sacrifício, prepare um litro de vinho como oferta derramada.

[[v4-15-6]]

^<<v4-15-6,6>>^ "Para um carneiro, prepare uma oferta de cereal de dois jarros da melhor farinha com um litro de óleo

[[v4-15-7]]

^<<v4-15-7,7>>^ e um litro de vinho como oferta derramada. Apresente-a como aroma agradável ao Senhor.

[[v4-15-8]]

^<<v4-15-8,8>>^ "Quando algum de vocês preparar um novilho para holocausto ou para sacrifício para cumprir voto especial, ou como oferta de comunhão ao Senhor,

[[v4-15-9]]

^<<v4-15-9,9>>^ traga com o novilho uma oferta de cereal de três jarros da melhor farinha amassada com meio galão de óleo.

[[v4-15-10]]

^<<v4-15-10,10>>^ Traga também meio galão de vinho para a oferta derramada. Será uma oferta preparada no fogo, de aroma agradável ao Senhor.

[[v4-15-11]]

^<<v4-15-11,11>>^ Cada novilho ou carneiro, ou cordeiro ou cabrito, deverá ser preparado dessa maneira.

[[v4-15-12]]

^<<v4-15-12,12>>^ Façam isso com cada animal, com tantos quantos vocês prepararem.

[[v4-15-13]]

^<<v4-15-13,13>>^ "Todo o que for natural da terra deverá proceder dessa maneira quando trouxer uma oferta preparada no fogo de aroma agradável ao Senhor.

[[v4-15-14]]

^<<v4-15-14,14>>^ E se um estrangeiro que vive entre vocês, ou entre os descendentes de vocês, apresentar uma oferta preparada no fogo, de aroma agradável ao Senhor, deverá fazer o mesmo.

[[v4-15-15]]

^<<v4-15-15,15>>^ A assembléia deverá ter as mesmas leis, que valerão tanto para vocês como para o estrangeiro que vive entre vocês; este é um decreto perpétuo pelas suas gerações, que, perante o Senhor, valerá tanto para vocês quanto para o estrangeiro residente.

[[v4-15-16]]

^<<v4-15-16,16>>^ A mesma lei e ordenança se aplicará tanto a vocês como ao estrangeiro residente".

[[v4-15-17]]

^<<v4-15-17,17>>^ O Senhor disse ainda a Moisés:

[[v4-15-18]]

^<<v4-15-18,18>>^ "Diga aos israelitas: Quando vocês entrarem na terra para onde os levo

[[v4-15-19]]

^<<v4-15-19,19>>^ e comerem do fruto da terra, apresentem uma porção como contribuição ao Senhor.

[[v4-15-20]]

^<<v4-15-20,20>>^ Apresentem um bolo feito das primícias da farinha de vocês. Apresentem-no como contribuição da sua colheita.

[[v4-15-21]]

^<<v4-15-21,21>>^ Em todas as suas gerações vocês apresentarão das primícias da farinha uma contribuição ao Senhor.

[[v4-15-22]]

^<<v4-15-22,22>>^ "Mas se vocês pecarem e deixarem de cumprir todos esses mandamentos

[[v4-15-23]]

^<<v4-15-23,23>>^ — tudo o que o Senhor lhes ordenou por meio de Moisés, desde o dia em que os ordenou e pelas suas gerações —

[[v4-15-24]]

^<<v4-15-24,24>>^ e se isso for feito sem intenção e não for do conhecimento da comunidade, toda a comunidade terá que oferecer um novilho para o holocausto de aroma agradável ao Senhor. Também apresentarão com sua oferta de cereal uma oferta derramada, conforme as prescrições, e um bode como oferta pelo pecado.

[[v4-15-25]]

^<<v4-15-25,25>>^ O sacerdote fará propiciação por toda a comunidade de Israel, e eles serão perdoados, pois o seu pecado não foi intencional e eles trouxeram ao Senhor uma oferta preparada no fogo e uma oferta pelo pecado.

[[v4-15-26]]

^<<v4-15-26,26>>^ A comunidade de Israel toda e os estrangeiros residentes entre eles serão perdoados, porque todo o povo esteve envolvido num pecado involuntário.

[[v4-15-27]]

^<<v4-15-27,27>>^ "Se, contudo, apenas uma pessoa pecar sem intenção, ela terá que trazer uma cabra de um ano como oferta pelo pecado.

[[v4-15-28]]

^<<v4-15-28,28>>^ O sacerdote fará propiciação pela pessoa que pecar, cometendo uma falta involuntária perante o Senhor, e ela será perdoada.

[[v4-15-29]]

^<<v4-15-29,29>>^ Somente uma lei haverá para todo aquele que pecar sem intenção, seja ele israelita nato, seja estrangeiro residente.

[[v4-15-30]]

^<<v4-15-30,30>>^ "Mas todo aquele que pecar com atitude desafiadora, seja natural da terra, seja estrangeiro residente, insulta ao Senhor, e será eliminado do meio do seu povo.

[[v4-15-31]]

^<<v4-15-31,31>>^ Por ter desprezado a palavra do Senhor e quebrado os seus mandamentos, terá que ser eliminado; sua culpa estará sobre ele".

[[v4-15-32]]

^<<v4-15-32,32>>^ Certo dia, quando os israelitas estavam no deserto, encontraram um homem recolhendo lenha no dia de sábado.

[[v4-15-33]]

^<<v4-15-33,33>>^ Aqueles que o encontraram recolhendo lenha levaram-no a Moisés, a Arão e a toda a comunidade,

[[v4-15-34]]

^<<v4-15-34,34>>^ que o prenderam, porque não sabiam o que deveria ser feito com ele.

[[v4-15-35]]

^<<v4-15-35,35>>^ Então o Senhor disse a Moisés: "O homem terá que ser executado. Toda a comunidade o apedrejará fora do acampamento".

[[v4-15-36]]

^<<v4-15-36,36>>^ Assim, toda a comunidade o levou para fora do acampamento e o apedrejou até à morte, conforme o Senhor tinha ordenado a Moisés.

[[v4-15-37]]

^<<v4-15-37,37>>^ O Senhor disse a Moisés:

[[v4-15-38]]

^<<v4-15-38,38>>^ "Diga o seguinte aos israelitas: Façam borlas nas extremidades das suas roupas e ponham um cordão azul em cada uma delas; façam isso por todas as suas gerações.

[[v4-15-39]]

^<<v4-15-39,39>>^ Quando virem essas borlas vocês se lembrarão de todos os mandamentos do Senhor, para que lhes obedeçam e não se prostituam nem sigam as inclinações dos seus corações e dos seus olhos.

[[v4-15-40]]

^<<v4-15-40,40>>^ Assim vocês se lembrarão de obedecer a todos os meus mandamentos, e para o seu Deus vocês serão um povo consagrado.

[[v4-15-41]]

^<<v4-15-41,41>>^ Eu sou o Senhor, o seu Deus, que os trouxe do Egito para ser o Deus de vocês. Eu sou o Senhor, o seu Deus".

'''

xref:004-numeros/004-numeros-014.adoc#v4-14-0[&#60; Capítulo Anterior] | <<v4-15-0,Topo>> | xref:004-numeros/004-numeros-016.adoc#v4-16-0[Próximo Capítulo &#62;]