include::./index.adoc[]

[[v4-24-0]]
=== Números, 24
// nvi ?, NVI - Nova Versão Internacional

[[v4-24-1]]

^<<v4-24-1,1>>^ Quando Balaão viu que agradava ao Senhor abençoar Israel, não recorreu à magia como nas outras vezes, mas voltou o rosto para o deserto.

[[v4-24-2]]

^<<v4-24-2,2>>^ Então viu Israel acampado, tribo por tribo; e o Espírito de Deus veio sobre ele,

[[v4-24-3]]

^<<v4-24-3,3>>^ e ele pronunciou este oráculo: "Palavra de Balaão, filho de Beor, palavra daquele cujos olhos vêem claramente,

[[v4-24-4]]

^<<v4-24-4,4>>^ palavra daquele que ouve as palavras de Deus, daquele que vê a visão que vem do Todo-poderoso, daquele que cai prostrado e vê com clareza:

[[v4-24-5]]

^<<v4-24-5,5>>^ "Quão belas são as suas tendas, ó Jacó, as suas habitações, ó Israel!

[[v4-24-6]]

^<<v4-24-6,6>>^ Como vales estendem-se, como jardins que margeiam rios, como aloés plantados pelo Senhor, como cedros junto às águas.

[[v4-24-7]]

^<<v4-24-7,7>>^ Seus reservatórios de água transbordarão; suas lavouras serão bem irrigadas. "O seu rei será maior do que Agague; o seu reino será exaltado.

[[v4-24-8]]

^<<v4-24-8,8>>^ Deus os está trazendo do Egito; eles têm a força do boi selvagem. Devoram nações inimigas e despedaçam seus ossos; com suas flechas os atravessam.

[[v4-24-9]]

^<<v4-24-9,9>>^ Como o leão e a leoa eles se abaixam e se deitam, quem ousará despertá-los? Sejam abençoados os que os abençoarem, e amaldiçoados os que os amaldiçoarem! "

[[v4-24-10]]

^<<v4-24-10,10>>^ Então acendeu-se a ira de Balaque contra Balaão, e, batendo as palmas das mãos, disse: "Eu o chamei para amaldiçoar meus inimigos, mas você já os abençoou três vezes!

[[v4-24-11]]

^<<v4-24-11,11>>^ Agora, fuja para a sua casa! Eu disse que lhe daria generosa recompensa, mas o Senhor o impediu de recebê-la".

[[v4-24-12]]

^<<v4-24-12,12>>^ Mas Balaão respondeu a Balaque: "Eu não disse aos mensageiros que você me enviou:

[[v4-24-13]]

^<<v4-24-13,13>>^ Mesmo que Balaque me desse o seu palácio cheio de prata e de ouro, eu não poderia fazer coisa alguma de minha própria vontade, boa ou má, que vá além da ordem do Senhor, e que devo dizer somente o que o Senhor disser?

[[v4-24-14]]

^<<v4-24-14,14>>^ Agora estou voltando para o meu povo, mas venha, deixe-me adverti-lo do que este povo fará ao seu povo nos dias futuros". O Quarto Oráculo de Balaão

[[v4-24-15]]

^<<v4-24-15,15>>^ Então pronunciou este seu oráculo: "Palavra de Balaão, filho de Beor, palavra daquele cujos olhos vêem claramente,

[[v4-24-16]]

^<<v4-24-16,16>>^ daquele que ouve as palavras de Deus, que possui o conhecimento do Altíssimo, daquele que vê a visão que vem do Todo-poderoso, daquele que cai prostrado, e vê com clareza:

[[v4-24-17]]

^<<v4-24-17,17>>^ Eu o vejo, mas não agora; eu o avisto, mas não de perto. Uma estrela surgirá de Jacó; um cetro se levantará de Israel. Ele esmagará as frontes de Moabe e o crânio de todos os descendentes de Sete.

[[v4-24-18]]

^<<v4-24-18,18>>^ Edom será dominado; Seir, seu inimigo, também será dominado, mas Israel se fortalecerá.

[[v4-24-19]]

^<<v4-24-19,19>>^ De Jacó sairá o governo; ele destruirá os sobreviventes das cidades".

[[v4-24-20]]

^<<v4-24-20,20>>^ Balaão viu Amaleque e pronunciou este oráculo: "Amaleque foi o primeiro entre as nações, mas o seu fim será destruição".

[[v4-24-21]]

^<<v4-24-21,21>>^ Depois viu os queneus e pronunciou este oráculo: "Sua habitação é segura, seu ninho está firmado na rocha;

[[v4-24-22]]

^<<v4-24-22,22>>^ todavia, vocês, queneus, serão destruídos quando Assur os levar prisioneiros".

[[v4-24-23]]

^<<v4-24-23,23>>^ Finalmente pronunciou este oráculo: "Ah, quem poderá viver quando Deus fizer isto?

[[v4-24-24]]

^<<v4-24-24,24>>^ Navios virão da costa de Quitim e subjugarão Assur e Héber, mas o seu fim também será destruição".

[[v4-24-25]]

^<<v4-24-25,25>>^ Então Balaão se levantou e voltou para casa, e Balaque seguiu o seu caminho.

'''

xref:004-numeros/004-numeros-023.adoc#v4-23-0[&#60; Capítulo Anterior] | <<v4-24-0,Topo>> | xref:004-numeros/004-numeros-025.adoc#v4-25-0[Próximo Capítulo &#62;]