include::./index.adoc[]

[[v4-9-0]]
=== Números, 9
// nvi ?, NVI - Nova Versão Internacional

[[v4-9-1]]

^<<v4-9-1,1>>^ O Senhor falou com Moisés no deserto do Sinai no primeiro mês do segundo ano depois que o povo saiu do Egito. Ele disse:

[[v4-9-2]]

^<<v4-9-2,2>>^ "Os israelitas devem celebrar a Páscoa na ocasião própria.

[[v4-9-3]]

^<<v4-9-3,3>>^ Celebrem-na no tempo determinado, ao pôr-do-sol do dia catorze deste mês, de acordo com todas as suas leis e ordenanças".

[[v4-9-4]]

^<<v4-9-4,4>>^ Então Moisés ordenou aos israelitas que celebrassem a Páscoa,

[[v4-9-5]]

^<<v4-9-5,5>>^ e eles o fizeram no deserto do Sinai, ao pôr-do-sol do dia catorze do primeiro mês. Os israelitas fizeram tudo conforme o Senhor tinha ordenado a Moisés.

[[v4-9-6]]

^<<v4-9-6,6>>^ Mas alguns deles não puderam celebrar a Páscoa naquele dia porque se haviam tornado impuros por terem tocado num cadáver. Por isso procuraram Moisés e Arão naquele mesmo dia

[[v4-9-7]]

^<<v4-9-7,7>>^ e disseram a Moisés: "Nós nos tornamos impuros por termos tocado num cadáver, mas por que deveríamos ser impedidos de apresentar a nossa oferta ao Senhor na ocasião própria, como os demais israelitas? "

[[v4-9-8]]

^<<v4-9-8,8>>^ Moisés respondeu-lhes: "Esperem até que eu saiba o que o Senhor ordena a respeito de vocês".

[[v4-9-9]]

^<<v4-9-9,9>>^ Então o Senhor disse a Moisés:

[[v4-9-10]]

^<<v4-9-10,10>>^ "Diga o seguinte aos israelitas: Quando algum de vocês ou dos seus descendentes se tornar impuro por tocar algum cadáver ou estiver distante por motivo de viagem, ainda assim poderá celebrar a Páscoa do Senhor.

[[v4-9-11]]

^<<v4-9-11,11>>^ Deverão celebrá-la no dia catorze do segundo mês, ao pôr-do-sol. Comerão o cordeiro com pães sem fermento e com ervas amargas.

[[v4-9-12]]

^<<v4-9-12,12>>^ Não deixarão sobrar nada até o amanhecer e não quebrarão nenhum osso do cordeiro. Quando a celebrarem, obedeçam a todas as leis da Páscoa.

[[v4-9-13]]

^<<v4-9-13,13>>^ Se, porém, um homem estiver puro e não estiver distante por motivo de viagem e ainda assim não celebrar a Páscoa, ele será eliminado do meio do seu povo porque não apresentou a oferta do Senhor na ocasião própria. Ele sofrerá as conseqüências do seu pecado.

[[v4-9-14]]

^<<v4-9-14,14>>^ "Um estrangeiro residente entre vocês, que queira celebrar a Páscoa do Senhor, deverá fazê-lo de acordo com as leis e ordenanças da Páscoa. Vocês terão as mesmas leis para o estrangeiro e para o natural da terra".

[[v4-9-15]]

^<<v4-9-15,15>>^ No dia em que foi armado o tabernáculo, a tenda que guarda as tábuas da aliança, a nuvem o cobriu. Desde o entardecer até o amanhecer a nuvem por cima do tabernáculo tinha a aparência de fogo.

[[v4-9-16]]

^<<v4-9-16,16>>^ Era assim que sempre acontecia: de dia a nuvem o cobria, e de noite tinha a aparência de fogo.

[[v4-9-17]]

^<<v4-9-17,17>>^ Sempre que a nuvem se levantava de cima da Tenda, os israelitas partiam; no lugar em que a nuvem descia, ali acampavam.

[[v4-9-18]]

^<<v4-9-18,18>>^ Conforme a ordem do Senhor os israelitas partiam, e conforme a ordem do Senhor, acampavam. Enquanto a nuvem estivesse por cima do tabernáculo, eles permaneciam acampados.

[[v4-9-19]]

^<<v4-9-19,19>>^ Enquanto a nuvem ficava sobre o tabernáculo por muito tempo, os israelitas cumpriam suas responsabilidades para com o Senhor, e não partiam.

[[v4-9-20]]

^<<v4-9-20,20>>^ Às vezes a nuvem ficava sobre o tabernáculo poucos dias; conforme a ordem do Senhor eles acampavam, e também conforme a ordem do Senhor, partiam.

[[v4-9-21]]

^<<v4-9-21,21>>^ Outras vezes a nuvem permanecia somente desde o entardecer até o amanhecer, e quando se levantava pela manhã, eles partiam. De dia ou de noite, sempre que a nuvem se levantava, eles partiam.

[[v4-9-22]]

^<<v4-9-22,22>>^ Quer a nuvem ficasse sobre o tabernáculo dois dias, quer um mês, quer mais tempo, os israelitas permaneciam no acampamento e não partiam; mas, quando ela se levantava, partiam.

[[v4-9-23]]

^<<v4-9-23,23>>^ Conforme a ordem do Senhor acampavam, e conforme a ordem do Senhor partiam. Nesse meio tempo, cumpriam suas responsabilidades para com o Senhor, de acordo com as suas ordens, anunciadas por Moisés.

'''

xref:004-numeros/004-numeros-008.adoc#v4-8-0[&#60; Capítulo Anterior] | <<v4-9-0,Topo>> | xref:004-numeros/004-numeros-010.adoc#v4-10-0[Próximo Capítulo &#62;]