include::./index.adoc[]

[[v4-10-0]]
=== Números, 10
// nvi ?, NVI - Nova Versão Internacional

[[v4-10-1]]

^<<v4-10-1,1>>^ O Senhor disse a Moisés:

[[v4-10-2]]

^<<v4-10-2,2>>^ "Faça duas cornetas de prata batida a fim de usá-las para reunir a comunidade e para dar aos acampamentos o sinal para partirem.

[[v4-10-3]]

^<<v4-10-3,3>>^ Quando as duas cornetas tocarem, a comunidade inteira se reunirá diante de você, à entrada da Tenda do Encontro.

[[v4-10-4]]

^<<v4-10-4,4>>^ Se apenas uma tocar, os líderes, chefes dos clãs de Israel, se reunirão diante de você.

[[v4-10-5]]

^<<v4-10-5,5>>^ Quando a corneta der um toque de alerta, as tribos acampadas a leste deverão partir.

[[v4-10-6]]

^<<v4-10-6,6>>^ Ao som do segundo toque, os acampamentos do lado sul partirão. O toque de alerta será o sinal para partir.

[[v4-10-7]]

^<<v4-10-7,7>>^ Para reunir a assembléia, faça soar as cornetas, mas não com o mesmo toque.

[[v4-10-8]]

^<<v4-10-8,8>>^ "Os filhos de Arão, os sacerdotes, tocarão as cornetas. Este é um decreto perpétuo para vocês e para as suas gerações.

[[v4-10-9]]

^<<v4-10-9,9>>^ Quando em sua terra vocês entrarem em guerra contra um adversário que os esteja oprimindo, toquem as cornetas; e o Senhor, o Deus de vocês se lembrará de vocês e os libertará dos seus inimigos.

[[v4-10-10]]

^<<v4-10-10,10>>^ Também em seus dias festivos, nas festas fixas e no primeiro dia de cada mês, vocês deverão tocar as cornetas por ocasião dos seus holocaustos e das suas ofertas de comunhão, e elas serão um memorial em favor de vocês perante o seu Deus. Eu sou o Senhor, o Deus de vocês".

[[v4-10-11]]

^<<v4-10-11,11>>^ No vigésimo dia do segundo mês do segundo ano, a nuvem se levantou de cima do tabernáculo que guarda as tábuas da aliança.

[[v4-10-12]]

^<<v4-10-12,12>>^ Então os israelitas partiram do deserto do Sinai e viajaram por etapas, até que a nuvem pousou no deserto de Parã.

[[v4-10-13]]

^<<v4-10-13,13>>^ Assim partiram pela primeira vez, conforme a ordem do Senhor anunciada por Moisés.

[[v4-10-14]]

^<<v4-10-14,14>>^ Os exércitos do acampamento de Judá partiram primeiro, junto à sua bandeira. Naassom, filho de Aminadabe, estava no comando.

[[v4-10-15]]

^<<v4-10-15,15>>^ Natanael, filho de Zuar, comandava os exércitos da tribo de Issacar,

[[v4-10-16]]

^<<v4-10-16,16>>^ e Eliabe, filho de Helom, chefiava os exércitos da tribo de Zebulom.

[[v4-10-17]]

^<<v4-10-17,17>>^ Quando o tabernáculo era desmontado, os gersonitas e os meraritas o carregavam e partiam.

[[v4-10-18]]

^<<v4-10-18,18>>^ Os exércitos do acampamento de Rúben partiram em seguida, junto à sua bandeira. Elizur, filho de Sedeur, estava no comando.

[[v4-10-19]]

^<<v4-10-19,19>>^ Selumiel, filho de Zurisadai, comandava os exércitos da tribo de Simeão,

[[v4-10-20]]

^<<v4-10-20,20>>^ e Eliasafe, filho de Deuel, chefiava os exércitos da tribo de Gade.

[[v4-10-21]]

^<<v4-10-21,21>>^ Então os coatitas partiam carregando as coisas sagradas. Antes que eles chegassem, o tabernáculo já deveria estar armado.

[[v4-10-22]]

^<<v4-10-22,22>>^ Os exércitos do acampamento de Efraim partiram em seguida, junto à sua bandeira. Elisama, filho de Amiúde, estava no comando.

[[v4-10-23]]

^<<v4-10-23,23>>^ Gamaliel, filho de Pedazur, comandava os exércitos da tribo de Manassés,

[[v4-10-24]]

^<<v4-10-24,24>>^ e Abidã, filho de Gideoni, os exércitos da tribo de Benjamim.

[[v4-10-25]]

^<<v4-10-25,25>>^ Finalmente, partiram os exércitos do acampamento de Dã, junto à sua bandeira, como retaguarda para todos os acampamentos. Aieser, filho de Amisadai, estava no comando.

[[v4-10-26]]

^<<v4-10-26,26>>^ Pagiel, filho de Ocrã, comandava os exércitos da tribo de Aser,

[[v4-10-27]]

^<<v4-10-27,27>>^ e Aira, filho de Enã, a divisão da tribo de Naftali.

[[v4-10-28]]

^<<v4-10-28,28>>^ Essa era a ordem que os exércitos israelitas seguiam quando se punham em marcha.

[[v4-10-29]]

^<<v4-10-29,29>>^ Então Moisés disse a Hobabe, filho do midianita Reuel, sogro de Moisés: "Estamos partindo para o lugar sobre o qual o Senhor disse: ‘Eu o darei a vocês’. Venha conosco e lhe trataremos bem, pois o Senhor prometeu boas coisas para Israel".

[[v4-10-30]]

^<<v4-10-30,30>>^ Ele respondeu: "Não, não irei; voltarei para a minha terra e para o meu povo".

[[v4-10-31]]

^<<v4-10-31,31>>^ Moisés, porém, disse: "Por favor, não nos deixe. Você sabe onde devemos acampar no deserto e pode ser o nosso guia.

[[v4-10-32]]

^<<v4-10-32,32>>^ Se vier conosco, partilharemos com você todas as coisas boas que o Senhor nos der".

[[v4-10-33]]

^<<v4-10-33,33>>^ Então eles partiram do monte do Senhor e viajaram três dias. A arca da aliança do Senhor foi à frente deles durante aqueles três dias para encontrar um lugar para descansarem.

[[v4-10-34]]

^<<v4-10-34,34>>^ A nuvem do Senhor estava sobre eles de dia, sempre que partiam de um acampamento.

[[v4-10-35]]

^<<v4-10-35,35>>^ Sempre que a arca partia, Moisés dizia: "Levanta-te, ó Senhor! Sejam espalhados os teus inimigos e fujam de diante de ti os teus adversários".

[[v4-10-36]]

^<<v4-10-36,36>>^ Sempre que a arca parava, ele dizia: "Volta, ó Senhor, para os incontáveis milhares de Israel".

'''

xref:004-numeros/004-numeros-009.adoc#v4-9-0[&#60; Capítulo Anterior] | <<v4-10-0,Topo>> | xref:004-numeros/004-numeros-011.adoc#v4-11-0[Próximo Capítulo &#62;]