include::./index.adoc[]

[[v4-4-0]]
=== Números, 4
// nvi ?, NVI - Nova Versão Internacional

[[v4-4-1]]

^<<v4-4-1,1>>^ Disse ainda o Senhor a Moisés e a Arão:

[[v4-4-2]]

^<<v4-4-2,2>>^ "Façam um recenseamento dos coatitas na tribo de Levi, pelos seus clãs e famílias;

[[v4-4-3]]

^<<v4-4-3,3>>^ contem todos os homens entre trinta e cinqüenta anos, aptos para servir, para que façam o serviço da Tenda do Encontro.

[[v4-4-4]]

^<<v4-4-4,4>>^ "O serviço dos coatitas na Tenda do Encontro será o cuidado das coisas santíssimas.

[[v4-4-5]]

^<<v4-4-5,5>>^ Quando o acampamento tiver que mudar, Arão e os seus filhos entrarão e descerão o véu protetor e com ele cobrirão a arca da aliança.

[[v4-4-6]]

^<<v4-4-6,6>>^ Depois a cobrirão com couro, estenderão um pano inteiramente azul sobre ela e colocarão as varas no lugar.

[[v4-4-7]]

^<<v4-4-7,7>>^ "Sobre a mesa da Presença eles estenderão um pano azul e colocarão os pratos, os recipientes para incenso, as tigelas e as bacias para as ofertas derramadas, e os pães da Presença, que devem estar sempre sobre ela.

[[v4-4-8]]

^<<v4-4-8,8>>^ Sobre tudo isso estenderão um pano vermelho e o cobrirão com couro. Depois colocarão as varas no lugar.

[[v4-4-9]]

^<<v4-4-9,9>>^ "Pegarão também um pano azul e cobrirão o candelabro usado para iluminação, as suas candeias, as suas tesouras de aparo, os seus apagadores e todos os seus jarros necessários para alimentá-la de óleo.

[[v4-4-10]]

^<<v4-4-10,10>>^ Então o embrulharão com todos os seus utensílios numa cobertura de couro e o colocarão num suporte para carregar.

[[v4-4-11]]

^<<v4-4-11,11>>^ "Sobre o altar de ouro estenderão um pano azul e o cobrirão com couro. E colocarão as suas varas no lugar.

[[v4-4-12]]

^<<v4-4-12,12>>^ "Apanharão todos os utensílios usados na ministração no santuário, depois os embrulharão num pano azul e os cobrirão com couro; a seguir os colocarão num suporte para carregar.

[[v4-4-13]]

^<<v4-4-13,13>>^ "Tirarão a cinza do altar de bronze e estenderão sobre ele um pano roxo.

[[v4-4-14]]

^<<v4-4-14,14>>^ Colocarão sobre ele todos os utensílios usados na ministração no altar: os braseiros, os garfos de carne, as pás e as bacias da aspersão. Sobre ele estenderão uma cobertura de couro e colocarão as varas no lugar.

[[v4-4-15]]

^<<v4-4-15,15>>^ "Quando Arão e os seus filhos terminarem de cobrir os utensílios sagrados e todos os artigos sagrados, e o acampamento estiver pronto para partir, os coatitas virão carregá-los. Mas não tocarão nas coisas sagradas; se o fizerem, morrerão. São esses os utensílios da Tenda do Encontro que os coatitas carregarão.

[[v4-4-16]]

^<<v4-4-16,16>>^ "Eleazar, filho do sacerdote Arão, ficará encarregado do azeite para a iluminação, do incenso aromático, da oferta costumeira de cereal e do óleo da unção. Ficará encarregado de todo o tabernáculo e de tudo o que nele há, seus utensílios e seus artigos sagrados".

[[v4-4-17]]

^<<v4-4-17,17>>^ O Senhor disse a Moisés e a Arão:

[[v4-4-18]]

^<<v4-4-18,18>>^ "Não permitam que o ramo dos clãs coatitas seja eliminado dentre os levitas.

[[v4-4-19]]

^<<v4-4-19,19>>^ Mas, para que continuem vivos e não morram quando se aproximarem das coisas santíssimas, Arão e os seus filhos entrarão no santuário e designarão a cada homem a sua tarefa e o que deverá carregar.

[[v4-4-20]]

^<<v4-4-20,20>>^ Os coatitas não entrarão para ver as coisas sagradas, nem por um breve momento, para que não morram".

[[v4-4-21]]

^<<v4-4-21,21>>^ E o Senhor disse a Moisés:

[[v4-4-22]]

^<<v4-4-22,22>>^ "Faça também um recenseamento dos gersonitas, pelas suas famílias e clãs;

[[v4-4-23]]

^<<v4-4-23,23>>^ conte todos os homens entre trinta e cinqüenta anos, aptos para servir, para que façam o serviço da Tenda do Encontro.

[[v4-4-24]]

^<<v4-4-24,24>>^ "Este é o serviço dos clãs gersonitas, o que devem fazer e carregar:

[[v4-4-25]]

^<<v4-4-25,25>>^ Eles levarão as cortinas internas do tabernáculo, a Tenda do Encontro, a sua cobertura, a cobertura exterior de couro, as cortinas da entrada da Tenda do Encontro.

[[v4-4-26]]

^<<v4-4-26,26>>^ Farão tudo o que for necessário com aquelas coisas e com as cortinas externas do pátio que rodeia o tabernáculo e o altar, com a cortina da entrada, com as cordas e com todos os utensílios usados em seu serviço.

[[v4-4-27]]

^<<v4-4-27,27>>^ Todo o serviço deles, tudo o que devem fazer e carregar estará sob a direção de Arão e de seus filhos. Designe como responsabilidade deles tudo o que tiverem que carregar.

[[v4-4-28]]

^<<v4-4-28,28>>^ Esse é o serviço dos clãs gersonitas na Tenda do Encontro. Suas atividades estarão sob a supervisão de Itamar, filho do sacerdote Arão.

[[v4-4-29]]

^<<v4-4-29,29>>^ "Conte os meraritas conforme os seus clãs e famílias,

[[v4-4-30]]

^<<v4-4-30,30>>^ todos os homens entre trinta e cinqüenta anos, aptos para servir, para que façam o serviço da Tenda do Encontro.

[[v4-4-31]]

^<<v4-4-31,31>>^ Esta é a responsabilidade deles no serviço que realizam na Tenda do Encontro: carregar as armações do tabernáculo, seus travessões, suas colunas e suas bases,

[[v4-4-32]]

^<<v4-4-32,32>>^ bem como as colunas do pátio, que rodeia a tenda, com suas bases, suas estacas e suas cordas; todos os seus utensílios e tudo o que está relacionado com o seu uso. Designe a cada um aquilo que deverá levar.

[[v4-4-33]]

^<<v4-4-33,33>>^ Este é o serviço dos clãs meraritas. Todo o serviço deles na Tenda do Encontro estará sob a supervisão de Itamar, filho do sacerdote Arão".

[[v4-4-34]]

^<<v4-4-34,34>>^ Moisés, Arão e os líderes da comunidade contaram os coatitas, conforme seus clãs e famílias,

[[v4-4-35]]

^<<v4-4-35,35>>^ todos os homens entre trinta e cinqüenta anos, aptos para servir, para que fizessem o serviço da Tenda do Encontro.

[[v4-4-36]]

^<<v4-4-36,36>>^ Foram contados, conforme os seus clãs, 2. 750 homens.

[[v4-4-37]]

^<<v4-4-37,37>>^ Esse foi o total de recenseados dos clãs coatitas que serviam na Tenda do Encontro. Moisés e Arão os contaram de acordo com a ordem do Senhor, anunciada por Moisés.

[[v4-4-38]]

^<<v4-4-38,38>>^ Os gersonitas foram contados conforme os seus clãs e famílias,

[[v4-4-39]]

^<<v4-4-39,39>>^ todos os homens entre trinta e cinqüenta anos, aptos para servir, para fazer o serviço da Tenda do Encontro.

[[v4-4-40]]

^<<v4-4-40,40>>^ Foram contados conforme os seus clãs e famílias 2. 630.

[[v4-4-41]]

^<<v4-4-41,41>>^ Esse foi o total de recenseados dos clãs gersonitas que serviam na Tenda do Encontro. Moisés e Arão os contaram de acordo com a ordem do Senhor.

[[v4-4-42]]

^<<v4-4-42,42>>^ Os meraritas foram contados conforme os seus clãs e famílias,

[[v4-4-43]]

^<<v4-4-43,43>>^ todos os homens entre trinta e cinqüenta anos, aptos para servir, para fazer o serviço da Tenda do Encontro.

[[v4-4-44]]

^<<v4-4-44,44>>^ Foram contados conforme os seus clãs 3. 200.

[[v4-4-45]]

^<<v4-4-45,45>>^ Esse foi o total de recenseados dos clãs meraritas que serviam na Tenda do Encontro. Moisés e Arão os contaram de acordo com a ordem do Senhor, anunciada por Moisés.

[[v4-4-46]]

^<<v4-4-46,46>>^ Assim Moisés, Arão e os líderes de Israel contaram todos os levitas conforme os seus clãs e famílias,

[[v4-4-47]]

^<<v4-4-47,47>>^ todos os homens entre trinta e cinqüenta anos de idade que vieram para servir e carregar a Tenda do Encontro

[[v4-4-48]]

^<<v4-4-48,48>>^ somavam 8. 580.

[[v4-4-49]]

^<<v4-4-49,49>>^ Conforme a ordem do Senhor anunciada por Moisés, a cada um foi designado o seu trabalho e foi dito o que deveria carregar. Assim foram todos contados, conforme o Senhor tinha ordenado a Moisés.

'''

xref:004-numeros/004-numeros-003.adoc#v4-3-0[&#60; Capítulo Anterior] | <<v4-4-0,Topo>> | xref:004-numeros/004-numeros-005.adoc#v4-5-0[Próximo Capítulo &#62;]