include::./index.adoc[]

[[v4-21-0]]
=== Números, 21
// nvi ?, NVI - Nova Versão Internacional

[[v4-21-1]]

^<<v4-21-1,1>>^ Quando o rei cananeu de Arade, que vivia no Neguebe, soube que Israel vinha pela estrada de Atarim, atacou os israelitas e capturou alguns deles.

[[v4-21-2]]

^<<v4-21-2,2>>^ Então Israel fez este voto ao Senhor: "Se entregares este povo em nossas mãos, destruiremos totalmente as suas cidades".

[[v4-21-3]]

^<<v4-21-3,3>>^ O Senhor ouviu o pedido de Israel e lhes entregou os cananeus. Israel os destruiu completamente, a eles e às suas cidades; de modo que o lugar foi chamado Hormá.

[[v4-21-4]]

^<<v4-21-4,4>>^ Partiram eles do monte Hor pelo caminho do mar Vermelho, para contornarem a terra de Edom. Mas o povo ficou impaciente no caminho

[[v4-21-5]]

^<<v4-21-5,5>>^ e falou contra Deus e contra Moisés, dizendo: "Por que vocês nos tiraram do Egito para morrermos no deserto? Não há pão! Não há água! E nós detestamos esta comida miserável! "

[[v4-21-6]]

^<<v4-21-6,6>>^ Então o Senhor enviou serpentes venenosas que morderam o povo, e muitos morreram.

[[v4-21-7]]

^<<v4-21-7,7>>^ O povo foi a Moisés e disse: "Pecamos quando falamos contra o Senhor e contra você. Ore pedindo ao Senhor que tire as serpentes do meio de nós". E Moisés orou pelo povo.

[[v4-21-8]]

^<<v4-21-8,8>>^ O Senhor disse a Moisés: "Faça uma serpente e coloque-a no alto de um poste; quem for mordido e olhar para ela viverá".

[[v4-21-9]]

^<<v4-21-9,9>>^ Moisés fez então uma serpente de bronze e a colocou num poste. Quando alguém era mordido por uma serpente e olhava para a serpente de bronze, permanecia vivo.

[[v4-21-10]]

^<<v4-21-10,10>>^ Os israelitas partiram e acamparam em Obote.

[[v4-21-11]]

^<<v4-21-11,11>>^ Depois partiram de Obote e acamparam em Ijé-Abarim, no deserto defronte de Moabe, ao leste.

[[v4-21-12]]

^<<v4-21-12,12>>^ Dali partiram e acamparam no vale de Zerede.

[[v4-21-13]]

^<<v4-21-13,13>>^ Partiram dali e acamparam do outro lado do Arnom, que fica no deserto que se estende até o território amorreu. O Arnom é a fronteira de Moabe, entre Moabe e os amorreus.

[[v4-21-14]]

^<<v4-21-14,14>>^ É por isso que se diz no Livro das Guerras do Senhor: "... Vaebe, em Sufá, e os vales, o Arnom

[[v4-21-15]]

^<<v4-21-15,15>>^ e as ravinas dos vales que se estendem até a cidade de Ar e chegam até a fronteira de Moabe".

[[v4-21-16]]

^<<v4-21-16,16>>^ De lá prosseguiram até Beer, ao poço do qual o Senhor disse a Moisés: "Reúna o povo, e eu lhe darei água".

[[v4-21-17]]

^<<v4-21-17,17>>^ Então Israel cantou esta canção: "Brote água, ó poço! Cantem a seu respeito,

[[v4-21-18]]

^<<v4-21-18,18>>^ a respeito do poço que os líderes cavaram, que os nobres abriram com cetros e cajados". Então saíram do deserto para Mataná,

[[v4-21-19]]

^<<v4-21-19,19>>^ de Mataná para Naaliel, de Naaliel para Bamote,

[[v4-21-20]]

^<<v4-21-20,20>>^ e de Bamote para o vale de Moabe, onde o topo do Pisga defronta com o deserto de Jesimom.

[[v4-21-21]]

^<<v4-21-21,21>>^ Israel enviou mensageiros para dizer a Seom, rei dos amorreus:

[[v4-21-22]]

^<<v4-21-22,22>>^ "Deixa-nos atravessar a tua terra. Não entraremos em nenhuma plantação, em nenhuma vinha, nem beberemos água de poço algum. Passaremos pela estrada do rei até que tenhamos atravessado o teu território".

[[v4-21-23]]

^<<v4-21-23,23>>^ Seom, porém, não deixou Israel atravessar o seu território. Convocou todo o seu exército e atacou Israel no deserto. Quando chegou a Jaza, lutou contra Israel.

[[v4-21-24]]

^<<v4-21-24,24>>^ Porém Israel o destruiu com a espada e tomou-lhe as terras desde o Arnom até o Jaboque, até o território dos amonitas, pois Jazar estava na fronteira dos amonitas.

[[v4-21-25]]

^<<v4-21-25,25>>^ Israel capturou todas as cidades dos amorreus e as ocupou, inclusive Hesbom e todos os seus povoados.

[[v4-21-26]]

^<<v4-21-26,26>>^ Hesbom era a cidade de Seom, rei dos amorreus, que havia lutado contra o antigo rei de Moabe, tendo lhe tomado todas as suas terras até o Arnom.

[[v4-21-27]]

^<<v4-21-27,27>>^ É por isso que os poetas dizem: "Venham a Hesbom! Seja ela reconstruída; seja restaurada a cidade de Seom!

[[v4-21-28]]

^<<v4-21-28,28>>^ "Fogo saiu de Hesbom, uma chama da cidade de Seom; consumiu Ar, de Moabe, os senhores do alto Arnom.

[[v4-21-29]]

^<<v4-21-29,29>>^ Ai de você, Moabe! Você está destruído, ó povo de Camos! Ele fez de seus filhos, fugitivos e de suas filhas, prisioneiras de Seom, rei dos amorreus.

[[v4-21-30]]

^<<v4-21-30,30>>^ "Mas nós os derrotamos; Hesbom está destruída por todo o caminho até Dibom. Nós os arrasamos até Nofá, e até Medeba".

[[v4-21-31]]

^<<v4-21-31,31>>^ Assim Israel habitou na terra dos amorreus.

[[v4-21-32]]

^<<v4-21-32,32>>^ Moisés enviou espiões a Jazar, e os israelitas tomaram os povoados ao redor e expulsaram os amorreus que ali estavam.

[[v4-21-33]]

^<<v4-21-33,33>>^ Depois voltaram e subiram pelo caminho de Basã, e Ogue, rei de Basã, com todo o seu exército, marchou para enfrentá-los em Edrei.

[[v4-21-34]]

^<<v4-21-34,34>>^ Mas o Senhor disse a Moisés: "Não tenha medo dele, pois eu o entreguei a você, juntamente com todo o seu exército e com a sua terra. Você fará com ele o que fez com Seom, rei dos amorreus, que habitava em Hesbom".

[[v4-21-35]]

^<<v4-21-35,35>>^ Então eles o derrotaram, bem como os seus filhos e todo o seu exército, não lhes deixando sobrevivente algum. E tomaram posse da terra dele.

'''

xref:004-numeros/004-numeros-020.adoc#v4-20-0[&#60; Capítulo Anterior] | <<v4-21-0,Topo>> | xref:004-numeros/004-numeros-022.adoc#v4-22-0[Próximo Capítulo &#62;]