include::./index.adoc[]

[[v4-16-0]]
=== Números, 16
// nvi ?, NVI - Nova Versão Internacional

[[v4-16-1]]

^<<v4-16-1,1>>^ Corá, filho de Isar, neto de Coate, bisneto de Levi, reuniu Datã e Abirão, filhos de Eliabe, e Om, filho de Pelete, todos da tribo de Rúben,

[[v4-16-2]]

^<<v4-16-2,2>>^ e eles se insurgiram contra Moisés. Com eles estavam duzentos e cinqüenta israelitas, líderes bem conhecidos na comunidade e que haviam sido nomeados membros do concílio.

[[v4-16-3]]

^<<v4-16-3,3>>^ Eles se ajuntaram contra Moisés e Arão, e lhes disseram: "Basta! A assembléia toda é santa, cada um deles é santo, e o Senhor está no meio deles. Então, por que vocês se colocam acima da assembléia do Senhor? "

[[v4-16-4]]

^<<v4-16-4,4>>^ Quando ouviu isso, Moisés prostrou-se, rosto em terra.

[[v4-16-5]]

^<<v4-16-5,5>>^ Depois disse a Corá e a todos os seus seguidores: "Pela manhã o Senhor mostrará quem lhe pertence e fará aproximar-se dele aquele que é santo, o homem a quem ele escolher.

[[v4-16-6]]

^<<v4-16-6,6>>^ Você, Corá, e todos os seus seguidores deverão fazer o seguinte: peguem incensarios

[[v4-16-7]]

^<<v4-16-7,7>>^ e amanhã coloquem neles fogo e incenso perante o Senhor. Quem o Senhor escolher será o homem consagrado. Basta, levitas! "

[[v4-16-8]]

^<<v4-16-8,8>>^ Moisés disse também a Corá: "Agora ouçam-me, levitas!

[[v4-16-9]]

^<<v4-16-9,9>>^ Não lhes é suficiente que o Deus de Israel os tenha separado do restante da comunidade de Israel e os tenha trazido para junto de si a fim de realizarem o trabalho no tabernáculo do Senhor e para estarem preparados para servir a comunidade?

[[v4-16-10]]

^<<v4-16-10,10>>^ Ele trouxe você e todos os seus irmãos levitas para junto dele, e agora vocês querem também o sacerdócio?

[[v4-16-11]]

^<<v4-16-11,11>>^ É contra o Senhor que você e todos os seus seguidores se ajuntaram! Quem é Arão, para que se queixem contra ele? "

[[v4-16-12]]

^<<v4-16-12,12>>^ Então Moisés mandou chamar Datã e Abirão, filhos de Eliabe. Mas eles disseram: "Nós não iremos!

[[v4-16-13]]

^<<v4-16-13,13>>^ Não lhe basta nos ter tirado de uma terra onde manam leite e mel para matar-nos no deserto? E ainda quer se fazer chefe sobre nós?

[[v4-16-14]]

^<<v4-16-14,14>>^ Além disso, você não nos levou a uma terra onde manam leite e mel, nem nos deu uma herança de campos e vinhas. Você pensa que pode cegar os olhos destes homens? Nós não iremos! "

[[v4-16-15]]

^<<v4-16-15,15>>^ Moisés indignou-se e disse ao Senhor: "Não aceites a oferta deles. Não tomei deles nem sequer um jumento, nem prejudiquei a nenhum deles".

[[v4-16-16]]

^<<v4-16-16,16>>^ Moisés disse a Corá: "Você e todos os seus seguidores terão que apresentar-se amanhã ao Senhor, você, eles e Arão.

[[v4-16-17]]

^<<v4-16-17,17>>^ Cada homem pegará o seu incensário, nele colocará incenso e o apresentará ao Senhor. Serão duzentos e cinqüenta incensários ao todo. Você e Arão também apresentarão os seus incensários".

[[v4-16-18]]

^<<v4-16-18,18>>^ Assim, cada um deles pegou o seu incensário, acendeu o incenso, e se colocou com Moisés e com Arão à entrada da Tenda do Encontro.

[[v4-16-19]]

^<<v4-16-19,19>>^ Quando Corá reuniu todos os seus seguidores em oposição a eles à entrada da Tenda do Encontro, a glória do Senhor apareceu a toda a comunidade.

[[v4-16-20]]

^<<v4-16-20,20>>^ E o Senhor disse a Moisés e a Arão:

[[v4-16-21]]

^<<v4-16-21,21>>^ "Afastem-se dessa comunidade para que eu acabe com eles imediatamente".

[[v4-16-22]]

^<<v4-16-22,22>>^ Mas Moisés e Arão prostraram-se, rosto em terra, e disseram: "Ó Deus, Deus que a todos dá vida, ficarás tu irado contra toda a comunidade quando um só homem pecou? "

[[v4-16-23]]

^<<v4-16-23,23>>^ Então o Senhor disse a Moisés:

[[v4-16-24]]

^<<v4-16-24,24>>^ "Diga à comunidade que se afaste das tendas de Corá, Datã e Abirão".

[[v4-16-25]]

^<<v4-16-25,25>>^ Moisés levantou-se e foi para onde estavam Datã e Abirão, e as autoridades de Israel o seguiram.

[[v4-16-26]]

^<<v4-16-26,26>>^ Ele advertiu a comunidade: "Afastem-se das tendas desses ímpios! Não toquem em nada do que pertence a eles, senão vocês serão eliminados por causa dos pecados deles".

[[v4-16-27]]

^<<v4-16-27,27>>^ Eles se afastaram das tendas de Corá, Datã e Abirão. Datã e Abirão tinham saído e estavam de pé, à entrada de suas tendas, junto com suas mulheres, seus filhos e suas crianças pequenas.

[[v4-16-28]]

^<<v4-16-28,28>>^ E disse Moisés: "Assim vocês saberão que o Senhor me enviou para fazer todas essas coisas e que isso não partiu de mim.

[[v4-16-29]]

^<<v4-16-29,29>>^ Se estes homens tiverem morte natural e experimentarem somente aquilo que normalmente acontece aos homens, então o Senhor não me enviou.

[[v4-16-30]]

^<<v4-16-30,30>>^ Mas, se o Senhor fizer acontecer algo totalmente novo, e a terra abrir a sua boca e os engolir, junto com tudo o que é deles, e eles descerem vivos ao Sheol, então vocês saberão que estes homens desprezaram o Senhor".

[[v4-16-31]]

^<<v4-16-31,31>>^ Assim que Moisés acabou de dizer tudo isso, o chão debaixo deles fendeu-se

[[v4-16-32]]

^<<v4-16-32,32>>^ e a terra abriu a sua boca e os engoliu juntamente com suas famílias, com todos os seguidores de Corá e com todos os seus bens.

[[v4-16-33]]

^<<v4-16-33,33>>^ Desceram vivos à sepultura, com tudo o que possuíam; a terra fechou-se sobre eles, e pereceram dentre a assembléia.

[[v4-16-34]]

^<<v4-16-34,34>>^ Diante dos seus gritos, todos os israelitas ao redor fugiram, gritando: "A terra vai nos engolir também! "

[[v4-16-35]]

^<<v4-16-35,35>>^ Então veio fogo da parte do Senhor e consumiu os duzentos e cinqüenta homens que ofereciam incenso.

[[v4-16-36]]

^<<v4-16-36,36>>^ O Senhor disse a Moisés:

[[v4-16-37]]

^<<v4-16-37,37>>^ "Diga a Eleazar, filho do sacerdote Arão, que apanhe os incensários dentre os restos fumegastes e espalhe as brasas, porque os incensários são santos.

[[v4-16-38]]

^<<v4-16-38,38>>^ Os incensários dos homens que pelo seu pecado perderam a vida serão batidos em forma de lâminas e servirão de revestimento do altar, pois foram apresentados ao Senhor e se tornaram sagrados. Que sejam um sinal para os israelitas".

[[v4-16-39]]

^<<v4-16-39,39>>^ O sacerdote Eleazar juntou os incensários de bronze que tinham sido apresentados pelos que foram consumidos pelo fogo. Os incensários foram batidos e serviram de revestimento do altar,

[[v4-16-40]]

^<<v4-16-40,40>>^ como o Senhor tinha dito por meio de Moisés. Isso foi feito como memorial para os israelitas, a fim de que ninguém que não fosse descendente de Arão, queimasse incenso perante o Senhor, para não sofrer o que Corá e os seus seguidores sofreram.

[[v4-16-41]]

^<<v4-16-41,41>>^ No dia seguinte toda a comunidade de Israel começou a queixar-se contra Moisés e Arão, dizendo: "Vocês mataram o povo do Senhor".

[[v4-16-42]]

^<<v4-16-42,42>>^ Quando, porém, a comunidade se ajuntou contra Moisés e contra Arão, e eles se voltaram para a Tenda do Encontro, repentinamente a nuvem a cobriu e a glória do Senhor apareceu.

[[v4-16-43]]

^<<v4-16-43,43>>^ Então Moisés e Arão foram para a frente da Tenda do Encontro,

[[v4-16-44]]

^<<v4-16-44,44>>^ e o Senhor disse a Moisés:

[[v4-16-45]]

^<<v4-16-45,45>>^ "Saia do meio dessa comunidade para que eu acabe com eles imediatamente". Mas eles se prostraram, rosto em terra;

[[v4-16-46]]

^<<v4-16-46,46>>^ e Moisés disse a Arão: "Pegue o seu incensário e ponha incenso nele, com fogo tirado do altar, e vá depressa até a comunidade para fazer propiciação por eles, porque saiu grande ira da parte do Senhor e a praga começou".

[[v4-16-47]]

^<<v4-16-47,47>>^ Arão fez o que Moisés ordenou e correu para o meio da assembléia. A praga já havia começado entre o povo, mas Arão ofereceu o incenso e fez propiciação por eles.

[[v4-16-48]]

^<<v4-16-48,48>>^ Arão se pôs entre os mortos e os vivos, e a praga cessou.

[[v4-16-49]]

^<<v4-16-49,49>>^ Foram catorze mil e setecentos os que morreram daquela praga, além dos que haviam morrido por causa de Corá.

[[v4-16-50]]

^<<v4-16-50,50>>^ Então Arão voltou a Moisés, à entrada da Tenda do Encontro, pois a praga já havia cessado.

'''

xref:004-numeros/004-numeros-015.adoc#v4-15-0[&#60; Capítulo Anterior] | <<v4-16-0,Topo>> | xref:004-numeros/004-numeros-017.adoc#v4-17-0[Próximo Capítulo &#62;]