include::./index.adoc[]

[[v4-28-0]]
=== Números, 28
// nvi ?, NVI - Nova Versão Internacional

[[v4-28-1]]

^<<v4-28-1,1>>^ O Senhor disse a Moisés:

[[v4-28-2]]

^<<v4-28-2,2>>^ "Ordene aos israelitas e diga-lhes: Tenham o cuidado de apresentar-me na época designada a comida para as minhas ofertas preparadas no fogo, como um aroma que me seja agradável.

[[v4-28-3]]

^<<v4-28-3,3>>^ Diga-lhes: Esta é a oferta preparada no fogo que vocês apresentarão ao Senhor: dois cordeiros de um ano, sem defeito, como holocausto diário.

[[v4-28-4]]

^<<v4-28-4,4>>^ Ofereçam um cordeiro pela manhã e um ao cair da tarde,

[[v4-28-5]]

^<<v4-28-5,5>>^ juntamente com uma oferta de cereal de um jarro da melhor farinha amassada com um litro de azeite de olivas batidas.

[[v4-28-6]]

^<<v4-28-6,6>>^ Este é o holocausto diário instituído no monte Sinai de aroma agradável; é oferta dedicada ao Senhor, preparada no fogo.

[[v4-28-7]]

^<<v4-28-7,7>>^ A oferta derramada que a acompanha será um litro de bebida fermentada junto com cada cordeiro. Derramem a oferta de bebida para o Senhor no Lugar Santo.

[[v4-28-8]]

^<<v4-28-8,8>>^ Ofereçam o segundo cordeiro ao cair da tarde, juntamente com o mesmo tipo de oferta de cereal e de oferta derramada que vocês prepararem de manhã. É uma oferta preparada no fogo, de aroma agradável ao Senhor.

[[v4-28-9]]

^<<v4-28-9,9>>^ "No dia de sábado, façam uma oferta de dois cordeiros de um ano de idade e sem defeito, juntamente com a oferta derramada e com uma oferta de cereal de dois jarros da melhor farinha amassada com óleo.

[[v4-28-10]]

^<<v4-28-10,10>>^ Este é o holocausto para cada sábado, além do holocausto diário e da oferta derramada.

[[v4-28-11]]

^<<v4-28-11,11>>^ "No primeiro dia de cada mês, apresentem ao Senhor um holocausto de dois novilhos, um carneiro e sete cordeiros de um ano, todos sem defeito.

[[v4-28-12]]

^<<v4-28-12,12>>^ Com cada novilho deverá haver uma oferta de cereal de três jarros da melhor farinha amassada com óleo; com o carneiro, uma oferta de cereal de dois jarros da melhor farinha amassada com óleo;

[[v4-28-13]]

^<<v4-28-13,13>>^ e com cada cordeiro, uma oferta de cereal de um jarro da melhor farinha amassada com óleo. É um holocausto, de aroma agradável, uma oferta dedicada ao Senhor, preparada no fogo.

[[v4-28-14]]

^<<v4-28-14,14>>^ Com cada novilho deverá haver uma oferta derramada de meio galão de vinho; com o carneiro, um litro; e com cada cordeiro, um litro. É o holocausto mensal que deve ser oferecido cada lua nova durante o ano.

[[v4-28-15]]

^<<v4-28-15,15>>^ Além do holocausto diário com a oferta derramada, um bode será oferecido ao Senhor como sacrifício pelo pecado.

[[v4-28-16]]

^<<v4-28-16,16>>^ "No décimo quarto dia do primeiro mês é a Páscoa do Senhor.

[[v4-28-17]]

^<<v4-28-17,17>>^ No décimo quinto dia desse mês haverá uma festa; durante sete dias comam pão sem fermento.

[[v4-28-18]]

^<<v4-28-18,18>>^ No primeiro dia convoquem uma santa assembléia e não façam trabalho algum.

[[v4-28-19]]

^<<v4-28-19,19>>^ Apresentem ao Senhor uma oferta preparada no fogo, um holocausto de dois novilhos, um carneiro e sete cordeiros de um ano, todos sem defeito.

[[v4-28-20]]

^<<v4-28-20,20>>^ Com cada novilho preparem uma oferta de cereal de três jarros da melhor farinha amassada com óleo; com o carneiro, dois jarros;

[[v4-28-21]]

^<<v4-28-21,21>>^ e com cada cordeiro, um jarro.

[[v4-28-22]]

^<<v4-28-22,22>>^ Ofereçam um bode como sacrifício pela culpa, para fazer propiciação por vocês.

[[v4-28-23]]

^<<v4-28-23,23>>^ Apresentem essas ofertas além do holocausto diário oferecido pela manhã.

[[v4-28-24]]

^<<v4-28-24,24>>^ Façam assim diariamente, durante sete dias: apresentem a comida para a oferta preparada no fogo, de aroma agradável ao Senhor; isso será feito além do holocausto diário e da sua oferta derramada.

[[v4-28-25]]

^<<v4-28-25,25>>^ No sétimo dia convoquem uma santa reunião e não façam trabalho algum.

[[v4-28-26]]

^<<v4-28-26,26>>^ "No dia da festa da colheita dos primeiros frutos, a Festa das Semanas, quando apresentarem ao Senhor uma oferta do cereal novo, convoquem uma santa assembléia e não façam trabalho algum.

[[v4-28-27]]

^<<v4-28-27,27>>^ Apresentem um holocausto de dois novilhos, de um carneiro e de sete cordeiros de um ano como aroma agradável ao Senhor.

[[v4-28-28]]

^<<v4-28-28,28>>^ Com cada novilho deverá haver uma oferta de cereal de três jarros da melhor farinha amassada com óleo; com o carneiro, dois jarros;

[[v4-28-29]]

^<<v4-28-29,29>>^ e com cada um dos cordeiros, um jarro.

[[v4-28-30]]

^<<v4-28-30,30>>^ Ofereçam também um bode para fazer propiciação por vocês.

[[v4-28-31]]

^<<v4-28-31,31>>^ Preparem tudo isso junto com a oferta derramada, além do holocausto diário e da oferta de cereal. Verifiquem que os animais sejam sem defeito".

'''

xref:004-numeros/004-numeros-027.adoc#v4-27-0[&#60; Capítulo Anterior] | <<v4-28-0,Topo>> | xref:004-numeros/004-numeros-029.adoc#v4-29-0[Próximo Capítulo &#62;]