include::./index.adoc[]

[[v4-8-0]]
=== Números, 8
// nvi ?, NVI - Nova Versão Internacional

[[v4-8-1]]

^<<v4-8-1,1>>^ Disse também o Senhor a Moisés:

[[v4-8-2]]

^<<v4-8-2,2>>^ "Diga o seguinte a Arão: Quando você preparar as sete lâmpadas, estas deverão iluminar a área da frente do candelabro".

[[v4-8-3]]

^<<v4-8-3,3>>^ Arão assim fez; dispôs as lâmpadas de modo que estivessem voltadas para a frente do candelabro, como o Senhor tinha ordenado a Moisés.

[[v4-8-4]]

^<<v4-8-4,4>>^ O candelabro foi feito da seguinte maneira: de ouro batido do pedestal às flores, conforme o modelo que o Senhor tinha mostrado a Moisés.

[[v4-8-5]]

^<<v4-8-5,5>>^ O Senhor disse a Moisés:

[[v4-8-6]]

^<<v4-8-6,6>>^ "Separe os levitas do meio dos israelitas e os purifique.

[[v4-8-7]]

^<<v4-8-7,7>>^ A purificação deles será assim: você aspergirá a água da purificação sobre eles; fará com que rapem o corpo todo e lavem as roupas, para que se purifiquem.

[[v4-8-8]]

^<<v4-8-8,8>>^ Depois eles trarão um novilho com a oferta de cereal da melhor farinha amassada com óleo; e você trará um segundo novilho como oferta pelo pecado.

[[v4-8-9]]

^<<v4-8-9,9>>^ Você levará os levitas para a frente da Tenda do Encontro e reunirá toda a comunidade de Israel.

[[v4-8-10]]

^<<v4-8-10,10>>^ Levará os levitas à presença do Senhor, e os israelitas imporão as mãos sobre eles.

[[v4-8-11]]

^<<v4-8-11,11>>^ Arão apresentará os levitas ao Senhor como oferta ritualmente movida da parte dos israelitas: eles serão dedicados ao trabalho do Senhor.

[[v4-8-12]]

^<<v4-8-12,12>>^ "Depois que os levitas impuserem as mãos sobre a cabeça dos novilhos, você oferecerá um novilho como oferta pelo pecado e o outro como holocausto ao Senhor, para fazer propiciação pelos levitas.

[[v4-8-13]]

^<<v4-8-13,13>>^ Disponha os levitas em frente de Arão e dos filhos dele e apresente-os como oferta movida ao Senhor.

[[v4-8-14]]

^<<v4-8-14,14>>^ Dessa maneira você separará os levitas do meio dos israelitas, e os levitas serão meus.

[[v4-8-15]]

^<<v4-8-15,15>>^ "Depois que você purificar os levitas e os apresentar como oferta movida, eles entrarão na Tenda do Encontro para ministrar.

[[v4-8-16]]

^<<v4-8-16,16>>^ Eles são os israelitas que deverão ser inteiramente dedicados a mim. Eu os separei para serem meus em lugar dos primogênitos, do primeiro filho homem de cada mulher israelita.

[[v4-8-17]]

^<<v4-8-17,17>>^ Todo primogênito em Israel, entre os homens ou entre os rebanhos, é meu. Eu os separei para mim quando feri todos os primogênitos no Egito

[[v4-8-18]]

^<<v4-8-18,18>>^ e escolhi os levitas em lugar de todos os primogênitos em Israel.

[[v4-8-19]]

^<<v4-8-19,19>>^ Dentre todos os israelitas, dediquei os levitas como dádivas a Arão e aos seus filhos; eles ministrarão na Tenda do Encontro em nome dos israelitas e farão propiciação por eles, para que nenhuma praga atinja os israelitas quando se aproximarem do santuário".

[[v4-8-20]]

^<<v4-8-20,20>>^ Moisés, Arão e toda a comunidade de Israel fizeram com os levitas como o Senhor tinha ordenado a Moisés.

[[v4-8-21]]

^<<v4-8-21,21>>^ Os levitas se purificaram e lavaram suas roupas; e Arão os apresentou como oferta ritualmente movida perante o Senhor e fez propiciação por eles para purificá-los.

[[v4-8-22]]

^<<v4-8-22,22>>^ Depois disso os levitas passaram a ministrar na Tenda do Encontro sob a supervisão de Arão e dos seus filhos. Fizeram com os levitas como o Senhor tinha ordenado a Moisés.

[[v4-8-23]]

^<<v4-8-23,23>>^ O Senhor disse ainda a Moisés:

[[v4-8-24]]

^<<v4-8-24,24>>^ "Isto diz respeito aos levitas: os homens de vinte e cinco anos para cima, aptos para servir, tomarão parte no trabalho que se faz na Tenda do Encontro,

[[v4-8-25]]

^<<v4-8-25,25>>^ mas aos cinqüenta anos deverão afastar-se do serviço regular e nele não mais trabalharão.

[[v4-8-26]]

^<<v4-8-26,26>>^ Poderão ajudar seus companheiros de ofício na responsabilidade de cuidar da Tenda do Encontro, mas eles mesmos não deverão fazer o trabalho. Assim você designará as responsabilidades dos levitas".

'''

xref:004-numeros/004-numeros-007.adoc#v4-7-0[&#60; Capítulo Anterior] | <<v4-8-0,Topo>> | xref:004-numeros/004-numeros-009.adoc#v4-9-0[Próximo Capítulo &#62;]