include::./index.adoc[]

[[v4-36-0]]
=== Números, 36
// nvi ?, NVI - Nova Versão Internacional

[[v4-36-1]]

^<<v4-36-1,1>>^ Os chefes de família do clã de Gileade, filho de Maquir, neto de Manassés, que pertenciam aos clãs dos descendentes de José, foram falar com Moisés e com os líderes, os chefes das famílias israelitas.

[[v4-36-2]]

^<<v4-36-2,2>>^ E disseram: "Quando o Senhor ordenou ao meu senhor que, por sorteio, desse a terra como herança para os israelitas, ordenou que vocês dessem a herança de nosso irmão Zelofeade às suas filhas.

[[v4-36-3]]

^<<v4-36-3,3>>^ Agora, suponham que elas se casem com homens de outras tribos israelitas; nesse caso a herança delas será tirada da herança dos nossos antepassados e acrescentada à herança da tribo com a qual se unirem pelo casamento.

[[v4-36-4]]

^<<v4-36-4,4>>^ Quando chegar o Ano do Jubileu para os israelitas, a herança delas será acrescentada à da tribo com a qual se unirem pelo casamento, e a propriedade delas será tirada da herança da tribo de nossos antepassados".

[[v4-36-5]]

^<<v4-36-5,5>>^ Então, instruído pelo Senhor, Moisés deu esta ordem aos israelitas: "A tribo dos descendentes de José tem razão.

[[v4-36-6]]

^<<v4-36-6,6>>^ É isto que o Senhor ordena quanto às filhas de Zelofeade: Elas poderão casar-se com quem lhes agradar, contanto que se casem dentro do clã da tribo de seu pai.

[[v4-36-7]]

^<<v4-36-7,7>>^ Nenhuma herança em Israel poderá passar de uma tribo para outra, pois todos os israelitas manterão as terras das tribos que herdaram de seus antepassados.

[[v4-36-8]]

^<<v4-36-8,8>>^ Toda filha que herdar terras em qualquer tribo israelita se casará com alguém do clã da tribo de seu pai, para que cada israelita possua a herança dos seus antepassados.

[[v4-36-9]]

^<<v4-36-9,9>>^ Nenhuma herança poderá passar de uma tribo para outra, pois cada tribo israelita deverá manter as terras que herdou".

[[v4-36-10]]

^<<v4-36-10,10>>^ As filhas de Zelofeade fizeram conforme o Senhor havia ordenado a Moisés.

[[v4-36-11]]

^<<v4-36-11,11>>^ As filhas de Zelofeade, Maalá, Tirza, Hogla, Milca e Noa, casaram-se com seus primos paternos,

[[v4-36-12]]

^<<v4-36-12,12>>^ dentro dos clãs dos descendentes de Manassés, filho de José, e a herança delas permaneceu no clã e na tribo de seu pai.

[[v4-36-13]]

^<<v4-36-13,13>>^ São esses os mandamentos e as ordenanças que o Senhor deu aos israelitas por intermédio de Moisés nas campinas de Moabe, junto ao Jordão, do outro lado de Jericó.

'''

xref:004-numeros/004-numeros-035.adoc#v4-35-0[&#60; Capítulo Anterior] | <<v4-36-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-001.adoc#v5-1-0[Próximo Capítulo &#62;]