include::./index.adoc[]

[[v4-5-0]]
=== Números, 5
// nvi ?, NVI - Nova Versão Internacional

[[v4-5-1]]

^<<v4-5-1,1>>^ O Senhor disse a Moisés:

[[v4-5-2]]

^<<v4-5-2,2>>^ "Ordene aos israelitas que mandem para fora do acampamento todo aquele que tiver lepra, ou que tiver um fluxo, ou que se tornar impuro por tocar um cadáver.

[[v4-5-3]]

^<<v4-5-3,3>>^ Mande-os para fora do acampamento tanto homens como mulheres, para que não contaminem o seu próprio acampamento, onde habito entre eles".

[[v4-5-4]]

^<<v4-5-4,4>>^ Os israelitas assim fizeram e os mandaram para fora do acampamento, como o Senhor tinha ordenado a Moisés.

[[v4-5-5]]

^<<v4-5-5,5>>^ E o Senhor disse a Moisés:

[[v4-5-6]]

^<<v4-5-6,6>>^ "Diga aos israelitas: Quando um homem ou uma mulher prejudicar outra pessoa e, portanto, ofender ao Senhor, será culpado.

[[v4-5-7]]

^<<v4-5-7,7>>^ Confessará o pecado que cometeu, fará restituição total, acrescentará um quinto a esse valor e entregará tudo isso a quem ele prejudicou.

[[v4-5-8]]

^<<v4-5-8,8>>^ Mas, se o prejudicado não tiver nenhum parente próximo para receber a restituição, esta pertencerá ao Senhor e será entregue ao sacerdote, juntamente com o carneiro com o qual se faz propiciação pelo culpado.

[[v4-5-9]]

^<<v4-5-9,9>>^ Todas as contribuições, ou seja, todas as dádivas sagradas que os israelitas trouxerem ao sacerdote, pertencerão a ele.

[[v4-5-10]]

^<<v4-5-10,10>>^ As dádivas sagradas de cada pessoa pertencem a ela, mas o que ela der ao sacerdote pertencerá ao sacerdote".

[[v4-5-11]]

^<<v4-5-11,11>>^ Então o Senhor disse a Moisés:

[[v4-5-12]]

^<<v4-5-12,12>>^ "Diga o seguinte aos israelitas: Se a mulher de alguém se desviar e lhe for infiel,

[[v4-5-13]]

^<<v4-5-13,13>>^ e outro homem deitar-se com ela, e isso estiver oculto de seu marido, e a impureza dela não for descoberta, por não haver testemunha contra ela nem tiver ela sido pega no ato;

[[v4-5-14]]

^<<v4-5-14,14>>^ e se o marido dela tiver ciúmes e suspeitar de sua mulher, esteja ela pura ou impura,

[[v4-5-15]]

^<<v4-5-15,15>>^ ele a levará ao sacerdote, com uma oferta de um jarro de farinha de cevada em favor dela. Não derramará azeite nem porá incenso sobre a farinha, porque é uma oferta de cereal pelo ciúme, para que se revele a verdade sobre o pecado.

[[v4-5-16]]

^<<v4-5-16,16>>^ "O sacerdote trará a mulher e a colocará perante o Senhor.

[[v4-5-17]]

^<<v4-5-17,17>>^ Então apanhará um pouco de água sagrada num jarro de barro e colocará na água um pouco do pó do chão do tabernáculo.

[[v4-5-18]]

^<<v4-5-18,18>>^ Depois de colocar a mulher perante o Senhor, o sacerdote soltará o cabelo dela e porá nas mãos dela a oferta memorial, a oferta pelo ciúme, enquanto ele mesmo terá em sua mão a água amarga que traz maldição.

[[v4-5-19]]

^<<v4-5-19,19>>^ Então o sacerdote fará a mulher jurar e lhe dirá: Se nenhum outro homem se deitou com você e se você não foi infiel nem se tornou impura enquanto casada, que esta água amarga que traz maldição não lhe faça mal.

[[v4-5-20]]

^<<v4-5-20,20>>^ Mas, se você foi infiel enquanto casada e se contaminou por ter se deitado com um homem que não é seu marido —

[[v4-5-21]]

^<<v4-5-21,21>>^ então o sacerdote fará a mulher pronunciar este juramento com maldição — que o Senhor faça de você objeto de maldição e de desprezo no meio do povo fazendo que a sua barriga inche e que você jamais tenha filhos.

[[v4-5-22]]

^<<v4-5-22,22>>^ Que esta água que traz maldição entre em seu corpo, inche a sua barriga e a impeça de ter filhos. "Então a mulher dirá: ‘Amém. Assim seja’.

[[v4-5-23]]

^<<v4-5-23,23>>^ "O sacerdote escreverá essas maldições num documento e depois as lavará na água amarga.

[[v4-5-24]]

^<<v4-5-24,24>>^ Ele a fará beber a água amarga que traz maldição, e essa água entrará nela, causando-lhe amargo sofrimento.

[[v4-5-25]]

^<<v4-5-25,25>>^ O sacerdote apanhará das mãos dela a oferta de cereal pelo ciúme, a moverá ritualmente perante o Senhor e a trará ao altar.

[[v4-5-26]]

^<<v4-5-26,26>>^ Então apanhará um punhado da oferta de cereal como oferta memorial e a queimará sobre o altar; depois disso fará a mulher beber a água.

[[v4-5-27]]

^<<v4-5-27,27>>^ Se ela houver se contaminado, sendo infiel ao seu marido, quando o sacerdote fizer que ela beba a água que traz maldição, essa água entrará nela e causará um amargo sofrimento; sua barriga inchará e ela, incapaz de ter filhos, se tornará objeto de maldição entre o seu povo.

[[v4-5-28]]

^<<v4-5-28,28>>^ Se, porém, a mulher não houver se contaminado, mas estiver pura, não sofrerá punição e será capaz de ter filhos.

[[v4-5-29]]

^<<v4-5-29,29>>^ "Esse é, pois, o ritual quanto ao ciúme, quando uma mulher for infiel e se contaminar enquanto casada,

[[v4-5-30]]

^<<v4-5-30,30>>^ ou quando o ciúme se apoderar de um homem porque suspeita de sua mulher. O sacerdote a colocará perante o Senhor e a fará passar por todo esse ritual.

[[v4-5-31]]

^<<v4-5-31,31>>^ Se a suspeita não se confirmar, o marido estará inocente, do contrário a mulher sofrerá as conseqüências da sua iniqüidade".

'''

xref:004-numeros/004-numeros-004.adoc#v4-4-0[&#60; Capítulo Anterior] | <<v4-5-0,Topo>> | xref:004-numeros/004-numeros-006.adoc#v4-6-0[Próximo Capítulo &#62;]