include::./index.adoc[]

[[v4-23-0]]
=== Números, 23
// nvi ?, NVI - Nova Versão Internacional

[[v4-23-1]]

^<<v4-23-1,1>>^ Balaão disse a Balaque: "Construa para mim aqui sete altares e prepare-me sete novilhos e sete carneiros".

[[v4-23-2]]

^<<v4-23-2,2>>^ Balaque fez o que Balaão pediu, e os dois ofereceram um novilho e um carneiro em cada altar.

[[v4-23-3]]

^<<v4-23-3,3>>^ E Balaão disse a Balaque: "Fique aqui junto ao seu holocausto, enquanto eu me retiro. Talvez o Senhor venha ao meu encontro. O que ele me revelar eu lhe contarei". E foi para um monte.

[[v4-23-4]]

^<<v4-23-4,4>>^ Deus o encontrou, e Balaão disse: "Preparei sete altares, e em cada altar ofereci um novilho e um carneiro".

[[v4-23-5]]

^<<v4-23-5,5>>^ O Senhor pôs uma mensagem na boca de Balaão e disse: "Volte a Balaque e dê-lhe essa mensagem".

[[v4-23-6]]

^<<v4-23-6,6>>^ Ele voltou a Balaque e o encontrou ao lado de seu holocausto, e com ele todos os líderes de Moabe.

[[v4-23-7]]

^<<v4-23-7,7>>^ Então Balaão pronunciou este oráculo: "Balaque trouxe-me de Arã, o rei de Moabe, buscou-me nas montanhas do Oriente. ‘Venha, amaldiçoe a Jacó para mim’, disse ele, ‘venha, pronuncie ameaças contra Israel! ’

[[v4-23-8]]

^<<v4-23-8,8>>^ Como posso amaldiçoar a quem Deus não amaldiçoou? Como posso pronunciar ameaças quem o Senhor não quis ameaçar?

[[v4-23-9]]

^<<v4-23-9,9>>^ Dos cumes rochosos eu os vejo, dos montes eu os avisto. Vejo um povo que vive separado e não se considera como qualquer nação.

[[v4-23-10]]

^<<v4-23-10,10>>^ Quem pode contar o pó de Jacó ou o número da quarta parte de Israel? Morra eu a morte dos justos, e seja o meu fim como o deles! "

[[v4-23-11]]

^<<v4-23-11,11>>^ Então Balaque disse a Balaão: "Que foi que você me fez? Eu o chamei para amaldiçoar meus inimigos, mas você nada fez senão abençoá-los! "

[[v4-23-12]]

^<<v4-23-12,12>>^ E ele respondeu: "Será que não devo dizer o que o Senhor põe em minha boca? "

[[v4-23-13]]

^<<v4-23-13,13>>^ Balaque lhe disse: "Venha comigo a outro lugar de onde você poderá vê-los; você verá só uma parte, mas não todos eles. E dali amaldiçoe este povo para mim".

[[v4-23-14]]

^<<v4-23-14,14>>^ Então ele o levou para o campo de Zofim, no topo do Pisga, e ali construiu sete altares e ofereceu um novilho e um carneiro em cada altar.

[[v4-23-15]]

^<<v4-23-15,15>>^ Balaão disse a Balaque: "Fique aqui ao lado de seu holocausto enquanto vou me encontrar com ele ali adiante".

[[v4-23-16]]

^<<v4-23-16,16>>^ Encontrando-se o Senhor com Balaão, pôs uma mensagem em sua boca e disse: "Volte a Balaque e dê-lhe essa mensagem".

[[v4-23-17]]

^<<v4-23-17,17>>^ Ele voltou e o encontrou ao lado de seu holocausto, e com ele os líderes de Moabe. Balaque perguntou-lhe: "O que o Senhor disse? "

[[v4-23-18]]

^<<v4-23-18,18>>^ Então ele pronunciou este oráculo: "Levante-se, Balaque, e ouça-me; escute-me, filho de Zipor.

[[v4-23-19]]

^<<v4-23-19,19>>^ Deus não é homem para que minta, nem filho de homem para que se arrependa. Acaso ele fala, e deixa de agir? Acaso promete, e deixa de cumprir?

[[v4-23-20]]

^<<v4-23-20,20>>^ Recebi uma ordem para abençoar; ele abençoou, e não o posso mudar.

[[v4-23-21]]

^<<v4-23-21,21>>^ Nenhuma desgraça se vê em Jacó, nenhum sofrimento em Israel. O Senhor, o seu Deus, está com eles; o brado de aclamação do Rei está no meio deles.

[[v4-23-22]]

^<<v4-23-22,22>>^ Deus os está trazendo do Egito; eles têm a força do boi selvagem.

[[v4-23-23]]

^<<v4-23-23,23>>^ Não há magia que possa contra Jacó, nem encantamento contra Israel. Agora se dirá de Jacó e de Israel: ‘Vejam o que Deus tem feito! ’

[[v4-23-24]]

^<<v4-23-24,24>>^ O povo se levanta como leoa; levanta-se como o leão, que não se deita até que devore a sua presa e beba o sangue das suas vítimas".

[[v4-23-25]]

^<<v4-23-25,25>>^ Balaque disse então a Balaão: "Não os amaldiçoe nem os abençoe! "

[[v4-23-26]]

^<<v4-23-26,26>>^ Balaão respondeu: "Não lhe disse que devo fazer tudo o que o Senhor disser? "

[[v4-23-27]]

^<<v4-23-27,27>>^ Balaque disse a Balaão: "Venha, deixe-me levá-lo a outro lugar. Talvez Deus se agrade que dali você os amaldiçoe para mim".

[[v4-23-28]]

^<<v4-23-28,28>>^ E Balaque levou Balaão para o topo do Peor, de onde se vê o deserto de Jesimom.

[[v4-23-29]]

^<<v4-23-29,29>>^ Balaão disse a Balaque: "Edifique-me aqui sete altares, e prepare-me sete novilhos e sete carneiros".

[[v4-23-30]]

^<<v4-23-30,30>>^ Balaque fez o que Balaão disse, e ofereceu um novilho e um carneiro em cada altar.

'''

xref:004-numeros/004-numeros-022.adoc#v4-22-0[&#60; Capítulo Anterior] | <<v4-23-0,Topo>> | xref:004-numeros/004-numeros-024.adoc#v4-24-0[Próximo Capítulo &#62;]