include::./index.adoc[]

[[v11-4-0]]
=== 1 Reis, 4
// nvi ?, NVI - Nova Versão Internacional

[[v11-4-1]]

^<<v11-4-1,1>>^ E assim o rei Salomão tornou-se rei sobre todo o Israel.

[[v11-4-2]]

^<<v11-4-2,2>>^ E estes foram os seus principais assessores: Azarias, filho de Zadoque: o sacerdote;

[[v11-4-3]]

^<<v11-4-3,3>>^ Eliorefe e Aías, filhos de Sisa: secretários; Josafá, filho de Ailude: arquivista real;

[[v11-4-4]]

^<<v11-4-4,4>>^ Benaia, filho de Joiada: comandante do exército; Zadoque e Abiatar: sacerdotes;

[[v11-4-5]]

^<<v11-4-5,5>>^ Azarias, filho de Natã: responsável pelos governadores distritais; Zabude, filho de Natã: sacerdote e conselheiro pessoal do rei;

[[v11-4-6]]

^<<v11-4-6,6>>^ Aisar: responsável pelo palácio; Adonirão, filho de Abda: chefe de trabalhos forçados.

[[v11-4-7]]

^<<v11-4-7,7>>^ Salomão tinha também, doze governadores distritais em todo o Israel, que forneciam provisões para o rei e para o palácio real. Cada um deles tinha que fornecer suprimentos durante um mês do ano.

[[v11-4-8]]

^<<v11-4-8,8>>^ Estes são os seus nomes: Ben-Hur, nos montes de Efraim;

[[v11-4-9]]

^<<v11-4-9,9>>^ Ben-Dequer, em Macaz, Saalbim, Bete-Semes e Elom-Bete-Hanã;

[[v11-4-10]]

^<<v11-4-10,10>>^ Ben-Hesede, em Arubote, Socó e toda a terra de Héfer;

[[v11-4-11]]

^<<v11-4-11,11>>^ Ben-Abinadabe, em Nafote-Dor. Tafate, filha de Salomão, era sua mulher;

[[v11-4-12]]

^<<v11-4-12,12>>^ Baaná, filho de Ailude, em Taanaque e Megido e toda Bete-Seã, próxima de Zaretã, abaixo de Jezreel, desde Bete-Seã até Abel-Meolá, indo além dos limites de Jocmeão;

[[v11-4-13]]

^<<v11-4-13,13>>^ Ben-Geder, em Ramote-Gileade e nos povoados de Jair, filho de Manassés, em Gileade, bem como o distrito de Argobe, em Basã, e as suas sessenta grandes cidades muradas com trancas de bronze nos portões;

[[v11-4-14]]

^<<v11-4-14,14>>^ Ainadabe, filho de Ido, em Maanaim;

[[v11-4-15]]

^<<v11-4-15,15>>^ Aimaás, em Naftali. Ele se casou com Basemate, filha de Salomão;

[[v11-4-16]]

^<<v11-4-16,16>>^ Baaná, filho de Husai, em Aser e em Bealote;

[[v11-4-17]]

^<<v11-4-17,17>>^ Josafá, filho de Parua, em Issacar;

[[v11-4-18]]

^<<v11-4-18,18>>^ Simei, filho de Elá, em Benjamim;

[[v11-4-19]]

^<<v11-4-19,19>>^ Geber, filho de Uri, em Gileade, a terra de Seom, rei dos amorreus, e de Ogue, rei de Basã. Ele era o único governador desse distrito.

[[v11-4-20]]

^<<v11-4-20,20>>^ Judá e Israel eram tão numerosos como a areia da praia; eles comiam, bebiam e eram felizes.

[[v11-4-21]]

^<<v11-4-21,21>>^ E Salomão governava todos os reinos, desde o Rio até a terra dos filisteus, chegando até a fronteira do Egito. Esses reinos traziam tributos e foram submissos a Salomão durante toda a sua vida.

[[v11-4-22]]

^<<v11-4-22,22>>^ As provisões diárias de Salomão eram trinta tonéis da melhor farinha e sessenta tonéis de farinha comum,

[[v11-4-23]]

^<<v11-4-23,23>>^ dez cabeças de gado engordado em cocheiras, vinte de gado engordado no pasto e cem ovelhas e bodes, bem como cervos, gazelas, corças e aves escolhidas.

[[v11-4-24]]

^<<v11-4-24,24>>^ Ele governava todos os reinos a oeste do Rio, desde Tifsa até Gaza, e tinha paz em todas as fronteiras.

[[v11-4-25]]

^<<v11-4-25,25>>^ Durante a vida de Salomão, Judá e Israel viveram em segurança, cada homem debaixo da sua videira e da sua figueira, desde Dã até Berseba.

[[v11-4-26]]

^<<v11-4-26,26>>^ Salomão possuía quatro mil cocheiras para cavalos de carros de guerra, e doze mil cavalos.

[[v11-4-27]]

^<<v11-4-27,27>>^ Todo mês um dos governadores distritais fornecia provisões ao rei Salomão e a todos os que vinham participar de sua mesa. Cuidavam para que não faltasse nada.

[[v11-4-28]]

^<<v11-4-28,28>>^ Também traziam ao devido lugar suas quotas de cevada e de palha para os cavalos de carros de guerra e para os outros cavalos.

[[v11-4-29]]

^<<v11-4-29,29>>^ Deus deu a Salomão sabedoria, discernimento extraordinário e uma abrangência de conhecimento tão imensurável quanto a areia do mar.

[[v11-4-30]]

^<<v11-4-30,30>>^ A sabedoria de Salomão era maior do que a de todos os homens do oriente, bem como de toda a sabedoria do Egito.

[[v11-4-31]]

^<<v11-4-31,31>>^ Ele era mais sábio do que qualquer outro homem, mais do que o ezraíta Etã; mais sábio do que Hemã, Calcol e Darda, filhos de Maol. E a sua fama espalhou-se por todas as nações em redor.

[[v11-4-32]]

^<<v11-4-32,32>>^ Ele compôs três mil provérbios, e os seus cânticos chegaram a mil e cinco.

[[v11-4-33]]

^<<v11-4-33,33>>^ Descreveu as plantas, desde o cedro do Líbano até o hissopo que brota nos muros. Também discorreu sobre os quadrúpedes, as aves, os animais que se movem rente ao chão e os peixes.

[[v11-4-34]]

^<<v11-4-34,34>>^ Homens de todas as nações vinham ouvir a sabedoria de Salomão. Eram enviados por todos os reis que tinham ouvido falar de sua sabedoria.

'''

xref:011-1-reis/011-1-reis-003.adoc#v11-3-0[&#60; Capítulo Anterior] | <<v11-4-0,Topo>> | xref:011-1-reis/011-1-reis-005.adoc#v11-5-0[Próximo Capítulo &#62;]