include::./index.adoc[]

[[v11-21-0]]
=== 1 Reis, 21
// nvi ?, NVI - Nova Versão Internacional

[[v11-21-1]]

^<<v11-21-1,1>>^ Algum tempo depois houve um incidente envolvendo uma vinha que pertencia a Nabote, de Jezreel. A vinha ficava em Jezreel, ao lado do palácio de Acabe, rei de Samaria.

[[v11-21-2]]

^<<v11-21-2,2>>^ Acabe tinha dito a Nabote: "Dê-me a sua vinha para eu usar como horta, já que fica ao lado do meu palácio. Em troca eu lhe darei uma vinha melhor ou, se preferir, eu lhe pagarei, seja qual for o seu valor".

[[v11-21-3]]

^<<v11-21-3,3>>^ Nabote, contudo, respondeu: "O SENHOR me livre de dar a ti a herança dos meus pais! "

[[v11-21-4]]

^<<v11-21-4,4>>^ Então Acabe foi para casa, aborrecido e indignado porque Nabote, de Jezreel, lhe dissera: "Não te darei a herança dos meus pais". Deitou-se na cama, virou o rosto para a parede e recusou-se a comer.

[[v11-21-5]]

^<<v11-21-5,5>>^ Sua mulher Jezabel entrou e lhe perguntou: "Por que você está tão aborrecido? Por que não come? "

[[v11-21-6]]

^<<v11-21-6,6>>^ Ele respondeu-lhe: "Porque eu disse a Nabote, de Jezreel: Venda-me a sua vinha; ou, se preferir, eu lhe darei outra vinha em lugar dessa. Mas ele disse: ‘Não te darei minha vinha’ ".

[[v11-21-7]]

^<<v11-21-7,7>>^ Disse-lhe Jezabel, sua mulher: "É assim que você age como rei de Israel? Levante-se e coma! Anime-se. Conseguirei para você a vinha de Nabote, de Jezreel".

[[v11-21-8]]

^<<v11-21-8,8>>^ Então ela escreveu cartas em nome de Acabe, pôs nelas o selo do rei, e as enviou às autoridades e aos nobres da cidade de Nabote.

[[v11-21-9]]

^<<v11-21-9,9>>^ Naquelas cartas ela escreveu: "Decretem um dia de jejum e ponham Nabote sentado num lugar de destaque entre o povo.

[[v11-21-10]]

^<<v11-21-10,10>>^ E mandem dois homens vadios sentar-se em frente dele e façam com que testemunhem que ele amaldiçoou tanto a Deus quanto ao rei. Levem-no para fora e apedrejem-no até a morte".

[[v11-21-11]]

^<<v11-21-11,11>>^ As autoridades e os nobres da cidade de Nabote fizeram conforme Jezabel os orientara nas cartas que lhes tinha escrito.

[[v11-21-12]]

^<<v11-21-12,12>>^ Decretaram jejum e fizeram Nabote sentar-se num local destacado no meio do povo.

[[v11-21-13]]

^<<v11-21-13,13>>^ Então dois homens vadios vieram e se sentaram em frente dele e o acusaram diante do povo, dizendo: "Nabote amaldiçoou tanto a Deus quanto ao rei". Por isso o levaram para fora da cidade e o apedrejaram até a morte.

[[v11-21-14]]

^<<v11-21-14,14>>^ Então mandaram informar a Jezabel: "Nabote foi apedrejado e está morto".

[[v11-21-15]]

^<<v11-21-15,15>>^ Assim que Jezabel soube que Nabote tinha sido apedrejado até a morte, disse a Acabe: "Levante-se e tome posse da vinha que Nabote, de Jezreel, recusou-se a vender-lhe. Ele não está mais vivo; está morto! "

[[v11-21-16]]

^<<v11-21-16,16>>^ Quando Acabe ouviu que Nabote estava morto, levantou-se e foi tomar posse da vinha.

[[v11-21-17]]

^<<v11-21-17,17>>^ Então a palavra do Senhor veio ao tesbita Elias:

[[v11-21-18]]

^<<v11-21-18,18>>^ "Vá encontrar-se com Acabe, o rei de Israel, que reina em Samaria. Agora ele está na vinha de Nabote para tomar posse dela.

[[v11-21-19]]

^<<v11-21-19,19>>^ Diga-lhe: Assim diz o Senhor: Você assassinou um homem e ainda se apossou de sua propriedade? E acrescentou: Assim diz o Senhor: No local onde os cães lamberam o sangue de Nabote, lamberão também o seu sangue; isso mesmo, o seu sangue! "

[[v11-21-20]]

^<<v11-21-20,20>>^ Acabe disse a Elias: "Então você me encontrou, meu inimigo! " "Eu o encontrei", ele respondeu, "porque você se vendeu para fazer o que o Senhor reprova.

[[v11-21-21]]

^<<v11-21-21,21>>^ ‘Vou trazer desgraça sobre você. Devorarei os seus descendentes e eliminarei da sua família todos os do sexo masculino em Israel, sejam escravos ou livres.

[[v11-21-22]]

^<<v11-21-22,22>>^ Farei à sua família o que fiz à de Jeroboão, filho de Nebate, e à de Baasa, filho de Aías, pois você provocou a minha ira e fez Israel pecar. ’

[[v11-21-23]]

^<<v11-21-23,23>>^ "E, acerca de Jezabel, o Senhor diz: ‘Os cães devorarão Jezabel junto ao muro de Jezreel’.

[[v11-21-24]]

^<<v11-21-24,24>>^ "Os que pertencem a Acabe e que morrerem na cidade os cães comerão, e as aves do céu se alimentarão dos que morrerem no campo".

[[v11-21-25]]

^<<v11-21-25,25>>^ ( Nunca existiu ninguém como Acabe, que se vendeu para fazer o que o Senhor reprova, pressionado por sua mulher Jezabel.

[[v11-21-26]]

^<<v11-21-26,26>>^ Ele se comportou da maneira mais detestável possível, indo atrás de ídolos, como faziam os amorreus, que o Senhor tinha expulsado de diante de Israel. )

[[v11-21-27]]

^<<v11-21-27,27>>^ Quando Acabe ouviu essas palavras, rasgou as suas vestes, vestiu-se de pano de saco e jejuou. Passou a dormir sobre panos de saco e agia com mansidão.

[[v11-21-28]]

^<<v11-21-28,28>>^ Então a palavra do Senhor veio ao tesbita Elias:

[[v11-21-29]]

^<<v11-21-29,29>>^ "Você notou como Acabe se humilhou diante de mim? Visto que se humilhou, não trarei essa desgraça durante o seu reinado, mas durante o reinado de seu filho".

'''

xref:011-1-reis/011-1-reis-020.adoc#v11-20-0[&#60; Capítulo Anterior] | <<v11-21-0,Topo>> | xref:011-1-reis/011-1-reis-022.adoc#v11-22-0[Próximo Capítulo &#62;]