include::./index.adoc[]

[[v11-19-0]]
=== 1 Reis, 19
// nvi ?, NVI - Nova Versão Internacional

[[v11-19-1]]

^<<v11-19-1,1>>^ Ora, Acabe contou a Jezabel tudo o que Elias tinha feito e como havia matado todos aqueles profetas à espada.

[[v11-19-2]]

^<<v11-19-2,2>>^ Por isso Jezabel mandou um mensageiro a Elias para dizer-lhe: "Que os deuses me castiguem com todo o rigor, caso amanhã nesta hora eu não faça com a sua vida o que você fez com a deles".

[[v11-19-3]]

^<<v11-19-3,3>>^ Elias teve medo e fugiu para salvar a vida. Em Berseba de Judá ele deixou o seu servo

[[v11-19-4]]

^<<v11-19-4,4>>^ e entrou no deserto, caminhando um dia. Chegou a um pé de giesta, sentou-se debaixo dele e orou, pedindo a morte. "Já tive o bastante, Senhor. Tira a minha vida; não sou melhor do que os meus antepassados. "

[[v11-19-5]]

^<<v11-19-5,5>>^ Depois se deitou debaixo da árvore e dormiu. De repente um anjo tocou nele e disse: "Levante-se e coma".

[[v11-19-6]]

^<<v11-19-6,6>>^ Elias olhou ao redor e ali, junto à sua cabeça, havia um pão assado sobre brasas quentes e um jarro de água. Ele comeu, bebeu e deitou-se de novo.

[[v11-19-7]]

^<<v11-19-7,7>>^ O anjo do Senhor voltou, tocou nele e disse: "Levante-se e coma, pois a sua viagem será muito longa".

[[v11-19-8]]

^<<v11-19-8,8>>^ Então ele se levantou, comeu e bebeu. Fortalecido com aquela comida, viajou quarenta dias e quarenta noites, até que chegou a Horebe, o monte de Deus.

[[v11-19-9]]

^<<v11-19-9,9>>^ Ali entrou numa caverna e passou a noite. E a palavra do Senhor veio a ele: "O que você está fazendo aqui, Elias? "

[[v11-19-10]]

^<<v11-19-10,10>>^ Ele respondeu: "Tenho sido muito zeloso pelo Senhor, Deus dos Exércitos. Os israelitas rejeitaram a tua aliança, quebraram os teus altares, e mataram os teus profetas à espada. Sou o único que sobrou, e agora também estão procurando matar-me".

[[v11-19-11]]

^<<v11-19-11,11>>^ O Senhor lhe disse: "Saia e fique no monte, na presença do Senhor, pois o Senhor vai passar". Então veio um vento fortíssimo que separou os montes e esmigalhou as rochas diante do Senhor, mas o Senhor não estava no vento. Depois do vento houve um terremoto, mas o Senhor não estava no terremoto.

[[v11-19-12]]

^<<v11-19-12,12>>^ Depois do terremoto houve um fogo, mas o Senhor não estava nele. E depois do fogo houve o murmúrio de uma brisa suave.

[[v11-19-13]]

^<<v11-19-13,13>>^ Quando Elias ouviu, puxou a capa para cobrir o rosto, saiu e ficou à entrada da caverna. E uma voz lhe perguntou: "O que você está fazendo aqui, Elias? "

[[v11-19-14]]

^<<v11-19-14,14>>^ Ele respondeu: "Tenho sido muito zeloso pelo Senhor, Deus dos Exércitos. Os israelitas rejeitaram a tua aliança, quebraram os teus altares, e mataram os teus profetas à espada. Sou o único que sobrou, e agora também estão procurando matar-me".

[[v11-19-15]]

^<<v11-19-15,15>>^ O Senhor lhe disse: "Volte pelo caminho por onde veio, e vá para o deserto de Damasco. Chegando lá, unja Hazael como rei da Síria.

[[v11-19-16]]

^<<v11-19-16,16>>^ Unja também Jeú, filho de Ninsi, como rei de Israel, e unja Eliseu, filho de Safate, de Abel-Meolá, para suceder a você como profeta.

[[v11-19-17]]

^<<v11-19-17,17>>^ Jeú matará todo aquele que escapar da espada de Hazael, e Eliseu matará todo aquele que escapar da espada de Jeú.

[[v11-19-18]]

^<<v11-19-18,18>>^ No entanto, fiz sobrar sete mil em Israel, todos aqueles cujos joelhos não se inclinaram diante de Baal e todos aqueles cujas bocas não o beijaram".

[[v11-19-19]]

^<<v11-19-19,19>>^ Então Elias saiu de lá e encontrou Eliseu, filho de Safate. Ele estava arando com doze parelhas de bois, e estava conduzindo a décima-segunda parelha. Elias o alcançou e lançou a sua capa sobre ele.

[[v11-19-20]]

^<<v11-19-20,20>>^ Eliseu deixou os bois e correu atrás de Elias. "Deixa-me dar um beijo de despedida em meu pai e minha mãe", disse, "e então irei contigo. " "Vá e volte", respondeu Elias, "pelo que lhe fiz. "

[[v11-19-21]]

^<<v11-19-21,21>>^ E Eliseu voltou, apanhou a sua parelha de bois e os matou. Queimou o equipamento de arar para cozinhar a carne e a deu ao povo, e eles comeram. Depois partiu com Elias, e se tornou o seu auxiliar.

'''

xref:011-1-reis/011-1-reis-018.adoc#v11-18-0[&#60; Capítulo Anterior] | <<v11-19-0,Topo>> | xref:011-1-reis/011-1-reis-020.adoc#v11-20-0[Próximo Capítulo &#62;]