include::./index.adoc[]

[[v11-12-0]]
=== 1 Reis, 12
// nvi ?, NVI - Nova Versão Internacional

[[v11-12-1]]

^<<v11-12-1,1>>^ Roboão foi a Siquém, onde todos os israelitas tinham se reunido para proclamá-lo rei.

[[v11-12-2]]

^<<v11-12-2,2>>^ Assim que Jeroboão, filho de Nebate, que estava no Egito fugindo do rei Salomão, soube disso, voltou de lá.

[[v11-12-3]]

^<<v11-12-3,3>>^ E mandaram chamá-lo. Então ele e toda a assembléia de Israel foram ao encontro de Roboão e disseram:

[[v11-12-4]]

^<<v11-12-4,4>>^ "Teu pai colocou sobre nós um jugo pesado, mas agora diminui o trabalho árduo e este jugo pesado, e nós te serviremos".

[[v11-12-5]]

^<<v11-12-5,5>>^ Roboão respondeu: "Voltem a mim daqui a três dias". Então o povo foi embora.

[[v11-12-6]]

^<<v11-12-6,6>>^ O rei Roboão perguntou às autoridades que haviam servido ao seu pai Salomão durante a vida dele: "Como vocês me aconselham a responder a este povo? "

[[v11-12-7]]

^<<v11-12-7,7>>^ Eles responderam: "Se hoje fores um servo desse povo e servi-lo, dando-lhe uma resposta favorável, eles sempre serão teus servos".

[[v11-12-8]]

^<<v11-12-8,8>>^ Roboão, contudo, rejeitou o conselho que as autoridades de Israel lhe tinham dito e consultou os jovens que haviam crescido com ele e o estavam servindo.

[[v11-12-9]]

^<<v11-12-9,9>>^ Perguntou-lhes: "Qual é o conselho de vocês? Como devemos responder a este povo que me diz: ‘Diminui o jugo que teu pai colocou sobre nós’? "

[[v11-12-10]]

^<<v11-12-10,10>>^ Os jovens que haviam crescido com ele responderam: "A este povo que te disse: ‘Teu pai colocou sobre nós um jugo pesado; torna-o mais leve’ — dize: ‘Meu dedo mínimo é mais grosso do que a cintura do meu pai.

[[v11-12-11]]

^<<v11-12-11,11>>^ Pois bem, meu pai lhes impôs um jugo pesado; eu o tornarei ainda mais pesado. Meu pai os castigou com simples chicotes; eu os castigarei com chicotes pontiagudos’ ".

[[v11-12-12]]

^<<v11-12-12,12>>^ Três dias depois, Jeroboão e todo o povo voltaram a Roboão, segundo a orientação dada pelo rei: "Voltem a mim daqui a três dias".

[[v11-12-13]]

^<<v11-12-13,13>>^ Mas o rei lhes respondeu asperamente. Rejeitando o conselho das autoridades de Israel,

[[v11-12-14]]

^<<v11-12-14,14>>^ seguiu o conselho dos jovens e disse: "Meu pai lhes tornou pesado o jugo; eu o tornarei ainda mais pesado. Meu pai os castigou com simples chicotes; eu os castigarei com chicotes pontiagudos".

[[v11-12-15]]

^<<v11-12-15,15>>^ E o rei não ouviu o povo, pois esta mudança nos acontecimentos vinha da parte do Senhor, para que se cumprisse a palavra que o Senhor havia falado a Jeroboão, filho de Nebate, por meio do silonita Aías.

[[v11-12-16]]

^<<v11-12-16,16>>^ Quando todo o Israel viu que o rei se recusava a ouvi-los, responderam ao rei: "Que temos em comum com Davi? Que temos em comum com o filho de Jessé? Para as suas tendas, ó Israel! Cuide da sua própria casa, ó Davi! " E assim os israelitas foram para as suas casas.

[[v11-12-17]]

^<<v11-12-17,17>>^ Quanto, porém, aos israelitas que moravam nas cidades de Judá, Roboão continuou como rei deles.

[[v11-12-18]]

^<<v11-12-18,18>>^ O rei Roboão enviou Adonirão, chefe de trabalhos forçados, mas todo o Israel o apedrejou até à morte. O rei, contudo, conseguiu subir em sua carruagem e fugir para Jerusalém.

[[v11-12-19]]

^<<v11-12-19,19>>^ Desta forma Israel se rebelou contra a dinastia de Davi, e assim permanece até hoje.

[[v11-12-20]]

^<<v11-12-20,20>>^ Quando todos os israelitas souberam que Jeroboão tinha voltado, mandaram chamá-lo para a reunião da comunidade e o fizeram rei sobre todo o Israel. Somente a tribo de Judá permaneceu leal à dinastia de Davi.

[[v11-12-21]]

^<<v11-12-21,21>>^ Quando Roboão chegou em Jerusalém, convocou cento e oitenta mil homens de combate, das tribos de Judá e de Benjamim, para guerrearem contra Israel e recuperarem o reino para Roboão, filho de Salomão.

[[v11-12-22]]

^<<v11-12-22,22>>^ Entretanto, veio esta palavra de Deus a Semaías, homem de Deus:

[[v11-12-23]]

^<<v11-12-23,23>>^ "Diga a Roboão, filho de Salomão, rei de Judá, às tribos de Judá e Benjamim, e ao restante do povo:

[[v11-12-24]]

^<<v11-12-24,24>>^ ‘Assim diz o Senhor: Não saiam à guerra contra os seus irmãos israelitas. Voltem para casa, todos vocês, pois fui eu que fiz isso’ ". E eles obedeceram à palavra do Senhor e voltaram para as suas casas, conforme o Senhor tinha ordenado.

[[v11-12-25]]

^<<v11-12-25,25>>^ Jeroboão fortificou Siquém, nos montes de Efraim, onde passou a morar. Depois ele saiu e fortificou Peniel.

[[v11-12-26]]

^<<v11-12-26,26>>^ Jeroboão pensou: "O reino agora provavelmente voltará para a dinastia de Davi.

[[v11-12-27]]

^<<v11-12-27,27>>^ Se esse povo subir a Jerusalém para oferecer sacrifícios no templo do Senhor, novamente dedicarão sua lealdade ao senhor deles, Roboão, rei de Judá. Eles vão me matar e voltar para o rei Roboão".

[[v11-12-28]]

^<<v11-12-28,28>>^ Depois de aconselhar-se, o rei fez dois bezerros de ouro e disse ao povo: "Vocês já subiram muito a Jerusalém. Aqui estão os seus deuses, ó Israel, que tiraram vocês do Egito".

[[v11-12-29]]

^<<v11-12-29,29>>^ Mandou por um bezerro em Betel, e o outro em Dã.

[[v11-12-30]]

^<<v11-12-30,30>>^ E isso veio a ser um pecado, pois o povo ia até Dã para adorar aquele bezerro.

[[v11-12-31]]

^<<v11-12-31,31>>^ Jeroboão construiu altares idólatras e designou sacerdotes dentre o povo, apesar de não serem levitas.

[[v11-12-32]]

^<<v11-12-32,32>>^ Instituiu uma festa no dia quinze do oitavo mês, semelhante à festa realizada em Judá, e ofereceu sacrifícios no altar. Ele fez isso em Betel, onde também sacrificou aos bezerros que havia feito. Também estabeleceu lá sacerdotes nos seus altares idólatras.

[[v11-12-33]]

^<<v11-12-33,33>>^ No dia quinze do oitavo mês, data que ele mesmo escolheu, ofereceu sacrifícios no altar que havia construído em Betel. Assim ele instituiu a festa para os israelitas e foi ao altar para queimar incenso.

'''

xref:011-1-reis/011-1-reis-011.adoc#v11-11-0[&#60; Capítulo Anterior] | <<v11-12-0,Topo>> | xref:011-1-reis/011-1-reis-013.adoc#v11-13-0[Próximo Capítulo &#62;]