include::./index.adoc[]

[[v11-20-0]]
=== 1 Reis, 20
// nvi ?, NVI - Nova Versão Internacional

[[v11-20-1]]

^<<v11-20-1,1>>^ O rei Ben-Hadade, da Síria, convocou todo o seu exército e, acompanhado de trinta e dois reis com seus cavalos e carros de guerra, cercou e atacou Samaria.

[[v11-20-2]]

^<<v11-20-2,2>>^ Ele enviou mensageiros à cidade, a Acabe, o rei de Israel, que lhe disseram: "Isto é o que diz Ben-Hadade:

[[v11-20-3]]

^<<v11-20-3,3>>^ ‘A sua prata e o seu ouro são meus, e o melhor de suas mulheres e filhos também’ ".

[[v11-20-4]]

^<<v11-20-4,4>>^ O rei respondeu: "Que seja conforme tu dizes, ó rei, meu senhor. Eu e tudo o que tenho somos teus".

[[v11-20-5]]

^<<v11-20-5,5>>^ Os mensageiros voltaram e disseram: "Assim diz Ben-Hadade: ‘Mandei tomar sua prata e seu ouro, suas mulheres e seus filhos.

[[v11-20-6]]

^<<v11-20-6,6>>^ Mas amanhã, a esta hora, enviarei meus oficiais para vasculharem o seu palácio e as casas dos seus oficiais. Eles me trarão tudo o que você considera de valor’ ".

[[v11-20-7]]

^<<v11-20-7,7>>^ O rei de Israel convocou todas as autoridades de Israel e lhes disse: "Vejam como esse homem está querendo a nossa desgraça! Quando mandou tomar as minhas mulheres e os meus filhos, a minha prata e o meu ouro, eu não lhe neguei! "

[[v11-20-8]]

^<<v11-20-8,8>>^ As autoridades e todo o povo responderam: "Não lhe dês atenção nem concordes com as suas exigências".

[[v11-20-9]]

^<<v11-20-9,9>>^ E ele respondeu aos mensageiros de Ben-Hadade: "Digam ao rei, meu senhor: Teu servo fará tudo o que exigiste na primeira vez, mas não posso atender a esta exigência". E eles levaram a resposta a Ben-Hadade.

[[v11-20-10]]

^<<v11-20-10,10>>^ Então Ben-Hadade mandou esta outra mensagem a Acabe: "Que os deuses me castiguem com todo o rigor, caso fique em Samaria pó suficiente para dar um punhado a cada um dos meus homens".

[[v11-20-11]]

^<<v11-20-11,11>>^ O rei de Israel respondeu: "Digam-lhe: ‘Quem está vestindo a sua armadura não deve se gabar como aquele que a está tirando’ ".

[[v11-20-12]]

^<<v11-20-12,12>>^ Ben-Hadade recebeu essa mensagem quando ele e os reis estavam bebendo em suas tendas, e ordenou aos seus homens: "Preparem-se para atacar a cidade". E eles lhe obedeceram.

[[v11-20-13]]

^<<v11-20-13,13>>^ Nessa ocasião, um profeta foi até Acabe, rei de Israel, e anunciou: "Assim diz o Senhor: ‘Vê este exército enorme? Hoje eu o entregarei nas suas mãos, e então você saberá que eu sou o Senhor’ ".

[[v11-20-14]]

^<<v11-20-14,14>>^ "Mas quem fará isso? ", perguntou Acabe. O profeta respondeu: "Assim diz o Senhor: ‘Os jovens soldados dos líderes das províncias o farão’ ". "E quem começará a batalha? ", perguntou. O profeta respondeu: "Você".

[[v11-20-15]]

^<<v11-20-15,15>>^ Então Acabe convocou os jovens soldados dos líderes das províncias, duzentos e trinta e dois homens. Em seguida reuniu o restante dos israelitas, sete mil ao todo.

[[v11-20-16]]

^<<v11-20-16,16>>^ Eles partiram ao meio-dia, enquanto Ben-Hadade e os trinta e dois reis aliados a ele estavam se embriagando nas suas tendas.

[[v11-20-17]]

^<<v11-20-17,17>>^ Os jovens soldados dos líderes das províncias saíram primeiro. Nisso, uma patrulha de Ben-Hadade informou: "Saíram alguns homens de Samaria".

[[v11-20-18]]

^<<v11-20-18,18>>^ Ele disse: "Quer tenham saído para a paz, quer para a guerra, tragam-nos vivos".

[[v11-20-19]]

^<<v11-20-19,19>>^ Os jovens soldados dos líderes das províncias marcharam para fora da cidade, com o exército na retaguarda,

[[v11-20-20]]

^<<v11-20-20,20>>^ e cada um matou o seu adversário. Diante disso, os arameus fugiram, perseguidos pelos israelitas. Mas Ben-Hadade, rei da Síria, escapou a cavalo com alguns de seus cavaleiros.

[[v11-20-21]]

^<<v11-20-21,21>>^ O rei de Israel avançou e destruiu os cavalos e carros de guerra e infligiu pesadas baixas aos arameus.

[[v11-20-22]]

^<<v11-20-22,22>>^ Depois disso, o profeta foi ao rei de Israel e disse: "Fortaleça a sua posição e veja o que deve ser feito, pois na próxima primavera o rei da Síria o atacará de novo".

[[v11-20-23]]

^<<v11-20-23,23>>^ Enquanto isso, os conselheiros do rei da Síria lhe diziam: "Os deuses deles são deuses das montanhas. É por isso que eles foram fortes demais para nós. Mas, se os combatermos nas planícies, com certeza seremos mais fortes do que eles.

[[v11-20-24]]

^<<v11-20-24,24>>^ Deves tirá-los todos os reis dos seus comandos e substituí-los por outros oficiais.

[[v11-20-25]]

^<<v11-20-25,25>>^ Também deves organizar um exército como o que perdeste, cavalo por cavalo e carro por carro, para que possamos combater Israel nas planícies. Então é certo que os venceremos". Ele concordou com eles e fez como foi aconselhado.

[[v11-20-26]]

^<<v11-20-26,26>>^ Na primavera seguinte Ben-Hadade convocou os arameus e marchou até Afeque para lutar contra Israel.

[[v11-20-27]]

^<<v11-20-27,27>>^ Os israelitas foram convocados e, tendo recebido provisões, saíram para enfrentar os arameus. Os israelitas acamparam no lado oposto como dois pequenos rebanhos de cabras, enquanto que os arameus cobriam todo o campo.

[[v11-20-28]]

^<<v11-20-28,28>>^ O homem de Deus foi ao rei de Israel e lhe disse: "Assim diz o Senhor: ‘Como os arameus pensam que o Senhor é um deus das montanhas e não um deus dos vales, eu entregarei esse exército enorme nas suas mãos, e vocês saberão que eu sou o Senhor’ ".

[[v11-20-29]]

^<<v11-20-29,29>>^ Durante sete dias estiveram acampados em frente um do outro, e no sétimo dia entraram em combate. Num só dia os israelitas mataram cem mil soldados de infantaria arameus.

[[v11-20-30]]

^<<v11-20-30,30>>^ O restante deles escapou para a cidade de Afeque, onde o muro caiu sobre vinte e sete mil deles. Ben-Hadade também fugiu para a cidade e se escondeu, ora num aposento, ora noutro.

[[v11-20-31]]

^<<v11-20-31,31>>^ Seus oficiais lhe disseram: "Soubemos que os reis do povo de Israel são misericordiosos. Nós vamos até o rei de Israel vestidos com panos de saco e com cordas no pescoço. Talvez ele poupe a tua vida".

[[v11-20-32]]

^<<v11-20-32,32>>^ Vestindo panos de saco e tendo cordas envolvendo o pescoço, foram ao rei de Israel e disseram: "Teu servo Ben-Hadade diz: ‘Rogo-te que me deixes viver’ ". O rei respondeu: "Ele ainda está vivo? Ele é meu irmão! "

[[v11-20-33]]

^<<v11-20-33,33>>^ Os homens interpretaram isso como um bom sinal e de imediato aproveitaram o que ele tinha dito. "Isso mesmo, teu irmão Ben-Hadade! ", disseram. "Tragam-no aqui", disse o rei. Quando Ben-Hadade chegou, Acabe o fez subir no seu carro.

[[v11-20-34]]

^<<v11-20-34,34>>^ "Devolverei as cidades que o meu pai tomou do teu pai", ofereceu Ben-Hadade. "Tu poderás estabelecer os teus próprios mercados em Damasco, como fez meu pai em Samaria. " Acabe disse: "Mediante um tratado, libertarei você". Então fizeram um tratado, e Acabe o deixou ir.

[[v11-20-35]]

^<<v11-20-35,35>>^ Por ordem do Senhor um dos discípulos dos profetas disse ao seu companheiro: "Fira-me", mas o homem se recusou a fazê-lo.

[[v11-20-36]]

^<<v11-20-36,36>>^ Então o profeta disse: "Como você não obedeceu ao Senhor, assim que você sair daqui um leão o ferirá". E, logo que o homem partiu, um leão o atacou e o feriu.

[[v11-20-37]]

^<<v11-20-37,37>>^ O profeta encontrou outro homem e lhe disse: "Fira-me, por favor". Este o atingiu e o feriu.

[[v11-20-38]]

^<<v11-20-38,38>>^ Então o profeta saiu e ficou ao lado da estrada, à espera do rei. Ele se disfarçou, cobrindo os olhos com sua testeira.

[[v11-20-39]]

^<<v11-20-39,39>>^ Quando o rei ia passando, o profeta gritou para ele: "Teu servo entrou no auge do combate, e alguém veio a mim com um prisioneiro e me disse: ‘Vigie este homem. Se ele escapar, será a sua vida pela dele, ou você deverá pagar trinta e cinco quilos de prata’.

[[v11-20-40]]

^<<v11-20-40,40>>^ Enquanto o teu servo estava ocupado com outras coisas, o homem desapareceu". "Essa é a sua sentença", disse o rei de Israel. "Você mesmo a pronunciou. "

[[v11-20-41]]

^<<v11-20-41,41>>^ Então o profeta rapidamente removeu a testeira dos olhos, e o rei o reconheceu como um dos profetas.

[[v11-20-42]]

^<<v11-20-42,42>>^ Ele disse ao rei: "Assim diz o Senhor: ‘Você libertou um homem que eu havia decidido que devia morrer. Por isso, é a sua vida pela vida dele, o seu povo pelo povo dele’ ".

[[v11-20-43]]

^<<v11-20-43,43>>^ Aborrecido e irritado, o rei de Israel voltou para o seu palácio em Samaria.

'''

xref:011-1-reis/011-1-reis-019.adoc#v11-19-0[&#60; Capítulo Anterior] | <<v11-20-0,Topo>> | xref:011-1-reis/011-1-reis-021.adoc#v11-21-0[Próximo Capítulo &#62;]