include::./index.adoc[]

[[v11-2-0]]
=== 1 Reis, 2
// nvi ?, NVI - Nova Versão Internacional

[[v11-2-1]]

^<<v11-2-1,1>>^ Quando se aproximava o dia de sua morte, Davi deu instruções ao seu filho Salomão:

[[v11-2-2]]

^<<v11-2-2,2>>^ "Estou para seguir o caminho de toda a terra. Por isso, seja forte e seja homem.

[[v11-2-3]]

^<<v11-2-3,3>>^ Obedeça ao que o Senhor, o seu Deus, exige: Ande nos seus caminhos e obedeça aos seus decretos, aos seus mandamentos, às suas ordenanças e aos seus testemunhos, conforme se acham escritos na Lei de Moisés; assim você prosperará em tudo o que fizer e por onde quer que for,

[[v11-2-4]]

^<<v11-2-4,4>>^ e o Senhor manterá a promessa que me fez: ‘Se os seus descendentes cuidarem de sua conduta, e se me seguirem fielmente de todo o coração e de toda a alma, você jamais ficará sem descendente no trono de Israel’.

[[v11-2-5]]

^<<v11-2-5,5>>^ "Você sabe muito bem o que Joabe, filho de Zeruia, me fez; o que fez com os dois comandantes dos exércitos de Israel, Abner, filho de Ner, e Amasa, filho de Jéter. Ele os matou, derramando sangue em tempos de paz; agiu como se estivesse em guerra, e com aquele sangue manchou o seu cinto e as suas sandálias.

[[v11-2-6]]

^<<v11-2-6,6>>^ Proceda com a sabedoria que você tem, e não o deixe envelhecer e descer em paz à sepultura.

[[v11-2-7]]

^<<v11-2-7,7>>^ "Mas seja bondoso com os filhos de Barzilai, de Gileade, admita-os entre os que comem à mesa com você, pois eles me apoiaram quando fugi do seu irmão Absalão.

[[v11-2-8]]

^<<v11-2-8,8>>^ "Saiba que também está com você Simei, filho de Gera, o benjamita de Baurim. Ele lançou terríveis maldições contra mim no dia em que fui a Maanaim. Mas depois desceu ao meu encontro no Jordão e lhe prometi jurando pelo Senhor que não o mataria à espada.

[[v11-2-9]]

^<<v11-2-9,9>>^ Mas, agora, não o considere inocente. Você é um homem sábio e saberá o que fazer com ele; apesar de ele já ser idoso, faça-o descer ensangüentado à sepultura".

[[v11-2-10]]

^<<v11-2-10,10>>^ Então Davi descansou com os seus antepassados e foi sepultado na cidade de Davi.

[[v11-2-11]]

^<<v11-2-11,11>>^ Ele reinou quarenta anos em Israel: sete anos em Hebrom e trinta e três em Jerusalém.

[[v11-2-12]]

^<<v11-2-12,12>>^ Salomão assentou-se no trono de Davi, seu pai, e o seu reinado foi firmemente estabelecido.

[[v11-2-13]]

^<<v11-2-13,13>>^ Adonias, o filho de Hagite, foi até Bate-Seba, mãe de Salomão. E esta lhe perguntou: "Você vem em paz? " Ele respondeu: "Sim".

[[v11-2-14]]

^<<v11-2-14,14>>^ E acrescentou: "Tenho algo para lhe dizer". Ela disse: Fale!

[[v11-2-15]]

^<<v11-2-15,15>>^ "Você sabe", disse ele, "que o reino era meu. Todo o Israel me via como o seu rei. Mas as circunstâncias mudaram, e o reino foi para o meu irmão; pois o Senhor o concedeu a ele.

[[v11-2-16]]

^<<v11-2-16,16>>^ Agora, quero fazer-lhe um pedido e espero que não me seja negado. " Ela disse: "Fale! "

[[v11-2-17]]

^<<v11-2-17,17>>^ Então ele prosseguiu: "Peça, por favor, ao rei Salomão que me dê a sunamita Abisague por mulher, pois ele não deixará de atender você".

[[v11-2-18]]

^<<v11-2-18,18>>^ "Está bem", respondeu Bate-Seba, "falarei com o rei em seu favor. "

[[v11-2-19]]

^<<v11-2-19,19>>^ Quando Bate-Seba foi falar ao rei em favor de Adonias, Salomão levantou-se para recebê-la e inclinou-se diante dela. Depois assentou-se no seu trono, mandou que trouxessem um trono para a sua mãe, e ela se assentou à sua direita.

[[v11-2-20]]

^<<v11-2-20,20>>^ "Tenho um pequeno pedido para lhe fazer", disse ela. "Não deixe de me atender. " O rei respondeu: "Faça o pedido, minha mãe; não deixarei de atendê-lo".

[[v11-2-21]]

^<<v11-2-21,21>>^ Então ela disse: "Dê a sunamita Abisague por mulher a seu irmão Adonias".

[[v11-2-22]]

^<<v11-2-22,22>>^ O rei Salomão perguntou à sua mãe: "Por que você pede somente a sunamita Abisague para Adonias? Peça logo o reino para ele, para o sacerdote Abiatar e para Joabe, filho de Zeruia; afinal ele é o meu irmão mais velho! "

[[v11-2-23]]

^<<v11-2-23,23>>^ Então o rei Salomão jurou pelo Senhor: "Que Deus me castigue com todo o rigor, se isso que Adonias falou não lhe custar a sua própria vida!

[[v11-2-24]]

^<<v11-2-24,24>>^ E agora eu juro pelo nome do Senhor, que me estabeleceu no trono de meu pai Davi, e, conforme prometeu, fundou uma dinastia para mim, que hoje mesmo Adonias será morto! "

[[v11-2-25]]

^<<v11-2-25,25>>^ E o rei Salomão deu ordem a Benaia, filho de Joiada, e este feriu e matou Adonias.

[[v11-2-26]]

^<<v11-2-26,26>>^ Ao sacerdote Abiatar o rei ordenou: "Vá para Anatote, para as suas terras! Você merece morrer, mas hoje eu não o matarei, pois você carregou a arca do Soberano Senhor diante de Davi, meu pai, e partilhou de todas as aflições dele".

[[v11-2-27]]

^<<v11-2-27,27>>^ Então Salomão expulsou Abiatar do sacerdócio do Senhor, cumprindo a palavra que o Senhor tinha dito em Siló a respeito da família de Eli.

[[v11-2-28]]

^<<v11-2-28,28>>^ Quando a notícia chegou a Joabe, que havia conspirado com Adonias, ainda que não com Absalão, ele fugiu para a Tenda do Senhor e agarrou-se às pontas do altar.

[[v11-2-29]]

^<<v11-2-29,29>>^ Foi dito ao rei Salomão que Joabe havia se refugiado na Tenda do Senhor e estava ao lado do altar. Então Salomão ordenou a Benaia, filho de Joiada: "Vá matá-lo! "

[[v11-2-30]]

^<<v11-2-30,30>>^ Então Benaia entrou na Tenda do Senhor e disse a Joabe: "O rei lhe ordena que saia". "Não", respondeu ele, "Vou morrer aqui". Benaia relatou ao rei a resposta de Joabe.

[[v11-2-31]]

^<<v11-2-31,31>>^ Então o rei ordenou a Benaia: "Faça o que ele diz. Mate-o e sepulte-o, e assim você retirará de mim e da minha família a culpa do sangue inocente que Joabe derramou.

[[v11-2-32]]

^<<v11-2-32,32>>^ O Senhor fará recair sobre a cabeça dele o sangue que derramou: ele atacou dois homens mais justos e melhores do que ele, sem o conhecimento de meu pai Davi, e os matou à espada. Os dois homens eram Abner, filho de Ner, comandante do exército de Israel, e Amasa, filho de Jéter, comandante do exército de Judá.

[[v11-2-33]]

^<<v11-2-33,33>>^ Que o sangue deles recaia sobre a cabeça de Joabe e sobre a dos seus descendentes para sempre. Mas que a paz do Senhor esteja para sempre sobre Davi, sobre os seus descendentes, sobre a sua dinastia e sobre o seu trono".

[[v11-2-34]]

^<<v11-2-34,34>>^ Então Benaia, filho de Joiada, foi e atacou Joabe e o matou, e ele foi sepultado em sua casa no campo.

[[v11-2-35]]

^<<v11-2-35,35>>^ No lugar dele o rei nomeou Benaia, filho de Joiada, no comando do exército, e o sacerdote Zadoque no lugar de Abiatar.

[[v11-2-36]]

^<<v11-2-36,36>>^ Depois o rei mandou chamar Simei e lhe ordenou: "Construa para você uma casa em Jerusalém. Você morará nela e não poderá ir para nenhum outro lugar.

[[v11-2-37]]

^<<v11-2-37,37>>^ Esteja certo de que no dia em que sair e atravessar o vale de Cedrom, você será morto; e você será responsável por sua própria morte".

[[v11-2-38]]

^<<v11-2-38,38>>^ Simei respondeu ao rei: "A ordem do rei é boa! O teu servo lhe obedecerá". E Simei permaneceu em Jerusalém por muito tempo.

[[v11-2-39]]

^<<v11-2-39,39>>^ Mas três anos depois, dois escravos de Simei fugiram para a casa de Aquis, filho de Maaca, rei de Gate. Alguém contou a Simei: "Seus escravos estão em Gate".

[[v11-2-40]]

^<<v11-2-40,40>>^ Então Simei selou um jumento e foi até Aquis, em Gate, procurar os seus escravos. E de lá Simei trouxe os escravos de volta.

[[v11-2-41]]

^<<v11-2-41,41>>^ Quando Salomão soube que Simei tinha ido a Gate e voltado a Jerusalém,

[[v11-2-42]]

^<<v11-2-42,42>>^ mandou chamá-lo e lhe perguntou: "Eu não fiz você jurar pelo Senhor e não o adverti: No dia em que você for para qualquer outro lugar, esteja certo que você morrerá? E você me respondeu: ‘Esta ordem é boa! Obedecerei’.

[[v11-2-43]]

^<<v11-2-43,43>>^ Por que não manteve o juramento ao Senhor e não obedeceu à ordem que lhe dei? "

[[v11-2-44]]

^<<v11-2-44,44>>^ E acrescentou: "No seu coração você sabe como você prejudicou o meu pai Davi. Agora o Senhor faz recair sua maldade sobre a sua cabeça.

[[v11-2-45]]

^<<v11-2-45,45>>^ Mas o rei Salomão será abençoado, e o trono de Davi será estabelecido perante o Senhor para sempre".

[[v11-2-46]]

^<<v11-2-46,46>>^ Então o rei deu ordem a Benaia, filho de Joiada, e este atacou Simei e o matou. Assim o reino ficou bem estabelecido nas mãos de Salomão.

'''

xref:011-1-reis/011-1-reis-001.adoc#v11-1-0[&#60; Capítulo Anterior] | <<v11-2-0,Topo>> | xref:011-1-reis/011-1-reis-003.adoc#v11-3-0[Próximo Capítulo &#62;]