include::./index.adoc[]

[[v11-10-0]]
=== 1 Reis, 10
// nvi ?, NVI - Nova Versão Internacional

[[v11-10-1]]

^<<v11-10-1,1>>^ A rainha de Sabá soube da fama que Salomão tinha alcançado, graças ao nome do Senhor, e foi a Jerusalém para pô-lo à prova com perguntas difíceis.

[[v11-10-2]]

^<<v11-10-2,2>>^ Quando chegou, acompanhada de uma enorme caravana, com camelos carregados de especiarias, grande quantidade de ouro e pedras preciosas, foi até Salomão e lhe fez todas as perguntas que tinha em mente.

[[v11-10-3]]

^<<v11-10-3,3>>^ Salomão respondeu a todas; nenhuma lhe foi tão difícil que não pudesse responder.

[[v11-10-4]]

^<<v11-10-4,4>>^ Vendo toda a sabedoria de Salomão, bem como o palácio que ele havia construído,

[[v11-10-5]]

^<<v11-10-5,5>>^ o que era servido em sua mesa, o lugar de seus oficiais, os criados e copeiros, todos uniformizados, e os holocaustos que ele fazia no templo do Senhor, ela ficou impressionada.

[[v11-10-6]]

^<<v11-10-6,6>>^ Disse ela então ao rei: "Tudo o que ouvi em meu país acerca de tuas realizações e de tua sabedoria era verdade.

[[v11-10-7]]

^<<v11-10-7,7>>^ Mas eu não acreditava no que diziam, até ver com os meus próprios olhos. Na realidade, não me contaram nem a metade; tu ultrapassas em muito o que ouvi, tanto em sabedoria como em riqueza.

[[v11-10-8]]

^<<v11-10-8,8>>^ Como devem ser felizes os homens da tua corte, que continuamente estão diante de ti e ouvem a tua sabedoria!

[[v11-10-9]]

^<<v11-10-9,9>>^ Bendito seja o Senhor, o teu Deus, que se agradou de ti e te colocou no trono de Israel. Por causa do amor eterno do Senhor para com Israel, ele te fez rei, para manter a justiça e a retidão".

[[v11-10-10]]

^<<v11-10-10,10>>^ E ela deu ao rei quatro toneladas e duzentos quilos de ouro e grande quantidade de especiarias e pedras preciosas. E nunca mais foram trazidas tantas especiarias quanto as que a rainha de Sabá deu ao rei Salomão.

[[v11-10-11]]

^<<v11-10-11,11>>^ ( Os navios de Hirão, que carregavam ouro de Ofir, também trouxeram de lá grande quantidade de madeira de junípero e pedras preciosas.

[[v11-10-12]]

^<<v11-10-12,12>>^ O rei utilizou a madeira para fazer a escadaria do templo do Senhor e a do palácio real, além de harpas e liras para os músicos. Nunca mais foi importada nem se viu tanta madeira de junípero. )

[[v11-10-13]]

^<<v11-10-13,13>>^ O rei Salomão deu à rainha de Sabá tudo o que ela desejou e pediu, além do que já lhe tinha dado por sua generosidade real. Então ela e os seus servos voltaram para o seu país.

[[v11-10-14]]

^<<v11-10-14,14>>^ O peso do ouro que Salomão recebia anualmente era de vinte e três toneladas e trezentos quilos,

[[v11-10-15]]

^<<v11-10-15,15>>^ fora os impostos pagos por mercadores e comerciantes e por todos os reis da Arábia e pelos governadores do país.

[[v11-10-16]]

^<<v11-10-16,16>>^ O rei Salomão fez duzentos escudos grandes de ouro batido, utilizando três quilos e seiscentos gramas de ouro em cada um.

[[v11-10-17]]

^<<v11-10-17,17>>^ Também fez trezentos escudos pequenos de ouro batido, com um quilo e oitocentos gramas de ouro em cada um. O rei os colocou no Palácio da Floresta do Líbano.

[[v11-10-18]]

^<<v11-10-18,18>>^ O rei mandou fazer ainda um grande trono de marfim revestido de ouro puro.

[[v11-10-19]]

^<<v11-10-19,19>>^ O trono tinha seis degraus, e o seu encosto tinha a parte alta arredondada. Nos dois lados do assento havia braços, com um leão junto a cada braço.

[[v11-10-20]]

^<<v11-10-20,20>>^ Doze leões ficavam nos seis degraus, um de cada lado. Nada igual havia sido feito em nenhum outro reino.

[[v11-10-21]]

^<<v11-10-21,21>>^ Todas as taças do rei Salomão eram de ouro, bem como todos os utensílios do Palácio da Floresta do Líbano. Não havia nada de prata, pois a prata quase não tinha valor nos dias de Salomão.

[[v11-10-22]]

^<<v11-10-22,22>>^ O rei tinha no mar uma frota de navios mercantes junto com os navios de Hirão. Cada três anos a frota voltava, trazendo ouro, prata, marfim, macacos e pavões.

[[v11-10-23]]

^<<v11-10-23,23>>^ O rei Salomão era o mais rico e o mais sábio de todos os reis da terra.

[[v11-10-24]]

^<<v11-10-24,24>>^ Gente de todo o mundo pedia audiência a Salomão para ouvir a sabedoria que Deus lhe tinha dado.

[[v11-10-25]]

^<<v11-10-25,25>>^ Ano após ano, todos os que vinham traziam algum presente: utensílios de prata e de ouro, mantos, armas e especiarias, cavalos e mulas.

[[v11-10-26]]

^<<v11-10-26,26>>^ Salomão juntou carros e cavalos; possuía mil e quatrocentos carros e doze mil cavalos, dos quais mantinha uma parte nas guarnições de algumas cidades e a outra perto dele, em Jerusalém.

[[v11-10-27]]

^<<v11-10-27,27>>^ O rei tornou a prata tão comum em Jerusalém quanto as pedras, e o cedro tão numeroso quanto as figueiras bravas da Sefelá.

[[v11-10-28]]

^<<v11-10-28,28>>^ Os cavalos de Salomão eram importados do Egito e da Cilícia, onde os fornecedores do rei os compravam.

[[v11-10-29]]

^<<v11-10-29,29>>^ Importavam do Egito um carro por sete quilos e duzentos gramas de prata, e um cavalo por um quilo e oitocentos gramas, e os exportavam para todos os reis dos hititas e dos arameus.

'''

xref:011-1-reis/011-1-reis-009.adoc#v11-9-0[&#60; Capítulo Anterior] | <<v11-10-0,Topo>> | xref:011-1-reis/011-1-reis-011.adoc#v11-11-0[Próximo Capítulo &#62;]