include::./index.adoc[]

[[v11-22-0]]
=== 1 Reis, 22
// nvi ?, NVI - Nova Versão Internacional

[[v11-22-1]]

^<<v11-22-1,1>>^ Durante três anos não houve guerra entre a Síria e Israel.

[[v11-22-2]]

^<<v11-22-2,2>>^ Mas no terceiro ano, Josafá, rei de Judá, foi visitar o rei de Israel.

[[v11-22-3]]

^<<v11-22-3,3>>^ Este havia perguntado aos seus oficiais: "Por acaso vocês não sabem que Ramote-Gileade nos pertence, e ainda assim não estamos fazendo nada para retomá-la do rei da Síria? "

[[v11-22-4]]

^<<v11-22-4,4>>^ Então perguntou a Josafá: "Irás comigo lutar contra Ramote-Gileade? " Josafá respondeu ao rei de Israel: "Sou como tu, e meu povo é como o teu povo, e os meus cavalos são como se fossem teus".

[[v11-22-5]]

^<<v11-22-5,5>>^ Mas acrescentou: "Peço-te que busques primeiro o conselho do Senhor".

[[v11-22-6]]

^<<v11-22-6,6>>^ Então o rei de Israel reuniu quatrocentos profetas, e lhes perguntou: "Devo ir à guerra contra Ramote-Gileade, ou não? " Eles responderam: "Sim, pois o Senhor a entregará nas mãos do rei".

[[v11-22-7]]

^<<v11-22-7,7>>^ Josafá, porém, perguntou: "Não existe aqui mais nenhum profeta do Senhor, a quem possamos consultar? "

[[v11-22-8]]

^<<v11-22-8,8>>^ O rei de Israel respondeu a Josafá: "Ainda há um homem por meio de quem podemos consultar o Senhor, mas eu o odeio, porque nunca profetiza coisas boas a meu respeito, mas sempre coisas ruins. É Micaías, filho de Inlá". "O rei não deveria dizer isso", Josafá respondeu.

[[v11-22-9]]

^<<v11-22-9,9>>^ Então o rei de Israel chamou um dos seus oficiais e disse: "Traga Micaías, filho de Inlá, imediatamente".

[[v11-22-10]]

^<<v11-22-10,10>>^ Usando vestes reais, o rei de Israel e Josafá, rei de Judá, estavam sentados em seus tronos, na eira, junto à porta de Samaria, e todos os profetas estavam profetizando em transe diante deles.

[[v11-22-11]]

^<<v11-22-11,11>>^ E Zedequias, filho de Quenaaná, tinha feito chifres de ferro, e declarou: "Assim diz o Senhor: ‘Com estes chifres tu ferirás os arameus até que sejam destruídos’ ".

[[v11-22-12]]

^<<v11-22-12,12>>^ Todos os outros profetas estavam profetizando a mesma coisa, dizendo: "Ataca Ramote-Gileade, e serás vitorioso, pois o Senhor a entregará nas mãos do rei".

[[v11-22-13]]

^<<v11-22-13,13>>^ O mensageiro que tinha ido chamar Micaías lhe disse: "Veja, todos os outros profetas estão predizendo que o rei terá sucesso. Sua palavra também deve ser favorável".

[[v11-22-14]]

^<<v11-22-14,14>>^ Micaías, porém, disse: "Juro pelo nome do Senhor, que direi o que o Senhor me mandar".

[[v11-22-15]]

^<<v11-22-15,15>>^ Quando ele chegou, o rei lhe perguntou: "Micaías, devemos ir à guerra contra Ramote-Gileade, ou não? " Ele respondeu: "Ataca, e serás vitorioso, pois o Senhor a entregará nas mãos do rei".

[[v11-22-16]]

^<<v11-22-16,16>>^ O rei lhe disse: "Quantas vezes devo fazer você jurar que irá me dizer somente a verdade em nome do Senhor? "

[[v11-22-17]]

^<<v11-22-17,17>>^ Então Micaías respondeu: "Vi todo o Israel espalhado pelas colinas, como ovelhas sem pastor, e o Senhor dizer: ‘Estes não têm dono. Cada um volte para casa em paz’ ".

[[v11-22-18]]

^<<v11-22-18,18>>^ O rei de Israel disse a Josafá: "Não lhe disse que ele nunca profetiza nada de bom a meu respeito, mas apenas coisas ruins? "

[[v11-22-19]]

^<<v11-22-19,19>>^ Micaías prosseguiu: "Ouça a palavra do Senhor: Vi o Senhor assentado em seu trono, com todo o exército dos céus ao seu redor, à sua direita e à sua esquerda.

[[v11-22-20]]

^<<v11-22-20,20>>^ E o Senhor disse: ‘Quem enganará Acabe para que ataque Ramote-Gileade e morra lá? ’ "E um sugeria uma coisa, outro sugeria outra,

[[v11-22-21]]

^<<v11-22-21,21>>^ até que, finalmente, um espírito colocou-se diante do Senhor e disse: ‘Eu o enganarei’.

[[v11-22-22]]

^<<v11-22-22,22>>^ " ‘De que maneira? ’, perguntou o Senhor. "Ele respondeu: ‘Irei e serei um espírito mentiroso na boca de todos os profetas do rei’. "Disse o Senhor: ‘Você conseguirá enganá-lo; vá e engane-o’.

[[v11-22-23]]

^<<v11-22-23,23>>^ "E o Senhor pôs um espírito mentiroso na boca destes seus profetas. O Senhor decretou a sua desgraça".

[[v11-22-24]]

^<<v11-22-24,24>>^ Então Zedequias, filho de Quenaaná, aproximou-se, deu um tapa no rosto de Micaías e perguntou: "Por qual caminho foi o espírito da parte do Senhor, quando saiu de mim para falar a você? "

[[v11-22-25]]

^<<v11-22-25,25>>^ Micaías respondeu: "Você descobrirá no dia em que estiver se escondendo de quarto em quarto".

[[v11-22-26]]

^<<v11-22-26,26>>^ O rei então ordenou: "Enviem Micaías de volta a Amom, o governador da cidade, e a Joás, filho do rei,

[[v11-22-27]]

^<<v11-22-27,27>>^ e digam: ‘Assim diz o rei: Ponham este homem na prisão a pão e água, até que eu volte em segurança’ ".

[[v11-22-28]]

^<<v11-22-28,28>>^ Micaías declarou: "Se você de fato voltar em segurança, o Senhor não falou por meu intermédio". E acrescentou: "Ouçam o que estou dizendo, todos vocês! "

[[v11-22-29]]

^<<v11-22-29,29>>^ Então o rei de Israel e Josafá, rei de Judá, foram atacar Ramote-Gileade.

[[v11-22-30]]

^<<v11-22-30,30>>^ E o rei de Israel disse a Josafá: "Entrarei disfarçado em combate, mas tu, usa as tuas vestes reais". O rei de Israel disfarçou-se, e ambos foram para o combate.

[[v11-22-31]]

^<<v11-22-31,31>>^ O rei da Síria havia ordenado aos seus trinta e dois chefes de carros de guerra: "Não lutem contra ninguém, seja soldado seja oficial, senão contra o rei de Israel".

[[v11-22-32]]

^<<v11-22-32,32>>^ Quando os chefes dos carros viram Josafá, pensaram: "É o rei de Israel", e o cercaram para atacá-lo, mas Josafá gritou,

[[v11-22-33]]

^<<v11-22-33,33>>^ e quando os comandantes dos carros viram que não era o rei de Israel, deixaram de persegui-lo.

[[v11-22-34]]

^<<v11-22-34,34>>^ De repente, um soldado disparou seu arco ao acaso, e atingiu o rei de Israel entre os encaixes da sua armadura. Então o rei disse ao condutor do seu carro: "Tire-me do combate. Fui ferido! "

[[v11-22-35]]

^<<v11-22-35,35>>^ A batalha foi violenta durante todo o dia, e assim, o rei teve que enfrentar os arameus em pé no seu carro. O sangue de seu ferimento ficou escorrendo até o piso do carro de guerra, e ao cair da tarde, ele morreu.

[[v11-22-36]]

^<<v11-22-36,36>>^ Quando o sol estava se pondo, propagou-se um grito por todo o exército: "Cada homem para a sua cidade; cada um para a sua terra! "

[[v11-22-37]]

^<<v11-22-37,37>>^ Assim o rei morreu e foi levado para Samaria, e ali o sepultaram.

[[v11-22-38]]

^<<v11-22-38,38>>^ Lavaram o seu carro de guerra num açude em Samaria onde as prostitutas se banhavam, e os cães lamberam o seu sangue, conforme a palavra do Senhor havia declarado.

[[v11-22-39]]

^<<v11-22-39,39>>^ Os demais acontecimentos do reinado de Acabe, e tudo o que fez, o palácio que construiu com revestimento de marfim, e as cidades que fortificou, tudo está escrito nos registros históricos dos reis de Israel.

[[v11-22-40]]

^<<v11-22-40,40>>^ Acabe descansou com os seus antepassados, e o seu filho Acazias foi o seu sucessor.

[[v11-22-41]]

^<<v11-22-41,41>>^ Josafá, filho de Asa, tornou-se rei de Judá no quarto ano do reinado de Acabe, rei de Israel.

[[v11-22-42]]

^<<v11-22-42,42>>^ Josafá tinha trinta e cinco anos de idade quando se tornou rei, e reinou vinte e cinco anos em Jerusalém. O nome da sua mãe era Azuba, filha de Sili.

[[v11-22-43]]

^<<v11-22-43,43>>^ Em tudo andou nos caminhos de seu pai Asa, e não se desviou deles; fez o que o Senhor aprova. Contudo, não acabou com os altares idólatras, nos quais o povo continuou a oferecer sacrifícios e a queimar incenso.

[[v11-22-44]]

^<<v11-22-44,44>>^ Josafá teve paz com o rei de Israel.

[[v11-22-45]]

^<<v11-22-45,45>>^ Os demais acontecimentos do reinado de Josafá, as suas realizações e façanhas militares, tudo está escrito nos registros históricos dos reis de Judá.

[[v11-22-46]]

^<<v11-22-46,46>>^ Ele livrou o país dos prostitutos cultuais que restaram depois do reinado do seu pai Asa.

[[v11-22-47]]

^<<v11-22-47,47>>^ Ora, na época não havia rei em Edom, mas sim um governador nomeado.

[[v11-22-48]]

^<<v11-22-48,48>>^ Josafá construiu uma frota de navios mercantes para buscar ouro em Ofir, mas nunca foram, pois eles naufragaram em Eziom-Geber.

[[v11-22-49]]

^<<v11-22-49,49>>^ Naquela ocasião, Acazias, filho de Acabe, disse a Josafá: "Os meus marinheiros poderão navegar com os teus", mas Josafá recusou.

[[v11-22-50]]

^<<v11-22-50,50>>^ Josafá descansou com seus antepassados e foi sepultado junto deles na cidade de Davi, seu pai. E o seu filho Jeorão foi o seu sucessor.

[[v11-22-51]]

^<<v11-22-51,51>>^ Acazias, filho de Acabe, tornou-se rei de Israel em Samaria no décimo sétimo ano do reinado de Josafá, rei de Judá, e reinou dois anos sobre Israel.

[[v11-22-52]]

^<<v11-22-52,52>>^ Fez o que o Senhor reprova, pois andou nos caminhos de seu pai e de sua mãe e nos caminhos de Jeroboão, filho de Nebate, que fez Israel pecar.

[[v11-22-53]]

^<<v11-22-53,53>>^ Prestou culto a Baal e adorou-o, e provocou a ira do Senhor, o Deus de Israel, como o seu pai tinha feito.

'''

xref:011-1-reis/011-1-reis-021.adoc#v11-21-0[&#60; Capítulo Anterior] | <<v11-22-0,Topo>> | xref:012-2-reis/012-2-reis-001.adoc#v12-1-0[Próximo Capítulo &#62;]