include::./index.adoc[]

[[v11-6-0]]
=== 1 Reis, 6
// nvi ?, NVI - Nova Versão Internacional

[[v11-6-1]]

^<<v11-6-1,1>>^ Quatrocentos e oitenta anos depois que os israelitas saíram do Egito, no quarto ano do reinado de Salomão em Israel, no mês de zive, o segundo mês, ele começou a construir o templo do Senhor.

[[v11-6-2]]

^<<v11-6-2,2>>^ O templo que o rei Salomão construiu para o Senhor media vinte e sete metros de comprimento, nove metros de largura e treze metros e meio de altura.

[[v11-6-3]]

^<<v11-6-3,3>>^ O pórtico da entrada do santuário tinha a largura do templo, que era de nove metros, e avançava quatro metros e meio à frente do templo.

[[v11-6-4]]

^<<v11-6-4,4>>^ Ele fez para o templo, janelas com grades estreitas.

[[v11-6-5]]

^<<v11-6-5,5>>^ Junto às paredes do átrio principal e do santuário interior, construiu uma estrutura em torno do edifício, na qual havia salas laterais.

[[v11-6-6]]

^<<v11-6-6,6>>^ O andar inferior tinha dois metros e vinte e cinco centímetros de largura, o andar intermediário tinha dois metros e setenta centímetros e o terceiro andar tinha três metros e quinze centímetros. Ele fez saliências de apoio nas paredes externas do templo, de modo que não houve necessidade de perfurar as paredes.

[[v11-6-7]]

^<<v11-6-7,7>>^ Na construção do templo só foram usados blocos lavrados nas pedreiras, e não se ouviu no templo nenhum barulho de martelo, nem de talhadeira, nem de qualquer outra ferramenta de ferro durante a sua construção.

[[v11-6-8]]

^<<v11-6-8,8>>^ A entrada para o andar inferior ficava no lado sul do templo; uma escada conduzia até o andar intermediário e dali ao terceiro.

[[v11-6-9]]

^<<v11-6-9,9>>^ Assim ele construiu o templo e o terminou, fazendo-lhe um forro com vigas e tábuas de cedro.

[[v11-6-10]]

^<<v11-6-10,10>>^ E fez as salas laterais ao longo de todo o templo. Cada uma tinha dois metros e vinte e cinco centímetros de altura, e elas estavam ligadas ao templo por vigas de cedro.

[[v11-6-11]]

^<<v11-6-11,11>>^ E a palavra do Senhor veio a Salomão dizendo:

[[v11-6-12]]

^<<v11-6-12,12>>^ "Quanto a este templo que você está construindo, se você seguir os meus decretos, executar os meus juízos e obedecer a todos os meus mandamentos, cumprirei por meio de você a promessa que fiz ao seu pai Davi,

[[v11-6-13]]

^<<v11-6-13,13>>^ viverei no meio dos israelitas e não abandonarei Israel, o meu povo".

[[v11-6-14]]

^<<v11-6-14,14>>^ E assim Salomão concluiu a construção do templo.

[[v11-6-15]]

^<<v11-6-15,15>>^ Forrou as paredes do templo por dentro com tábuas de cedro, cobrindo-as desde o chão até o teto, e fez o soalho do templo com tábuas de pinho.

[[v11-6-16]]

^<<v11-6-16,16>>^ Separou nove metros na parte de trás do templo, fazendo uma divisão com tábuas de cedro, do chão ao teto, para formar dentro do templo o santuário interno, o Lugar Santíssimo.

[[v11-6-17]]

^<<v11-6-17,17>>^ O átrio principal em frente dessa sala media dezoito metros de comprimento.

[[v11-6-18]]

^<<v11-6-18,18>>^ O interior do templo era de cedro, com figuras entalhadas de frutos e flores abertas. Tudo era de cedro; não se via pedra alguma.

[[v11-6-19]]

^<<v11-6-19,19>>^ Preparou também o santuário interno no templo para ali colocar a arca da aliança do Senhor.

[[v11-6-20]]

^<<v11-6-20,20>>^ O santuário interno tinha nove metros de comprimento, nove de largura e nove de altura. Ele revestiu o interior de ouro puro, e também revestiu de ouro o altar de cedro.

[[v11-6-21]]

^<<v11-6-21,21>>^ Salomão cobriu o interior do templo de ouro puro, e estendeu correntes de ouro em frente do santuário interno, que também foi revestido de ouro.

[[v11-6-22]]

^<<v11-6-22,22>>^ Assim, revestiu de ouro todo o interior do templo e também o altar que pertencia ao santuário interno.

[[v11-6-23]]

^<<v11-6-23,23>>^ No santuário interno ele esculpiu dois querubins de madeira de oliveira, cada um com quatro metros e meio de altura.

[[v11-6-24]]

^<<v11-6-24,24>>^ As asas abertas dos querubins mediam dois metros e vinte e cinco centímetros: quatro metros e meio da ponta de uma asa à ponta da outra.

[[v11-6-25]]

^<<v11-6-25,25>>^ Os dois querubins tinham a mesma medida e a mesma forma.

[[v11-6-26]]

^<<v11-6-26,26>>^ A altura de cada querubim era de quatro metros e meio.

[[v11-6-27]]

^<<v11-6-27,27>>^ Ele colocou os querubins, com as asas abertas, no santuário interno do templo. A asa de um querubim encostava numa parede, e a do outro encostava na outra. As suas outras asas encostavam uma na outra no meio do santuário.

[[v11-6-28]]

^<<v11-6-28,28>>^ Ele revestiu os querubins de ouro.

[[v11-6-29]]

^<<v11-6-29,29>>^ Nas paredes ao redor do templo, tanto na parte interna como na externa, ele esculpiu querubins, tamareiras e flores abertas.

[[v11-6-30]]

^<<v11-6-30,30>>^ Também revestiu de ouro os pisos, tanto na parte interna como na externa do templo.

[[v11-6-31]]

^<<v11-6-31,31>>^ Para a entrada do santuário interno fez portas de oliveira com batentes de cinco lados.

[[v11-6-32]]

^<<v11-6-32,32>>^ E nas duas portas de madeira de oliveira esculpiu querubins, tamareiras e flores abertas, e revestiu os querubins e as tamareiras de ouro batido.

[[v11-6-33]]

^<<v11-6-33,33>>^ Também fez pilares de quatro lados, de madeira de oliveira para a entrada do templo.

[[v11-6-34]]

^<<v11-6-34,34>>^ Fez também duas portas de pinho, cada uma com duas folhas que se articulavam por meio de dobradiças.

[[v11-6-35]]

^<<v11-6-35,35>>^ Entalhou figuras de querubins, de tamareiras e de flores abertas nas portas e as revestiu todas igualmente de ouro batido.

[[v11-6-36]]

^<<v11-6-36,36>>^ E construiu o pátio interno com três camadas de pedra lavrada e uma de vigas de cedro.

[[v11-6-37]]

^<<v11-6-37,37>>^ O alicerce do templo do Senhor foi lançado no mês de zive do quarto ano.

[[v11-6-38]]

^<<v11-6-38,38>>^ No mês de bul, o oitavo mês, do décimo primeiro ano, o templo foi terminado em todos os seus detalhes, de acordo com as suas especificações. Ele levou sete anos para construí-lo.

'''

xref:011-1-reis/011-1-reis-005.adoc#v11-5-0[&#60; Capítulo Anterior] | <<v11-6-0,Topo>> | xref:011-1-reis/011-1-reis-007.adoc#v11-7-0[Próximo Capítulo &#62;]