include::./index.adoc[]

[[v11-13-0]]
=== 1 Reis, 13
// nvi ?, NVI - Nova Versão Internacional

[[v11-13-1]]

^<<v11-13-1,1>>^ Por ordem do Senhor um homem de Deus foi de Judá a Betel, quando Jeroboão estava de pé junto ao altar para queimar incenso.

[[v11-13-2]]

^<<v11-13-2,2>>^ Ele clamou contra o altar, segundo a ordem do Senhor: "Ó altar, ó altar! Assim diz o Senhor: ‘Um filho nascerá na família de Davi e se chamará Josias. Sobre você ele sacrificará os sacerdotes dos altares idólatras que agora queimam incenso aqui, e ossos humanos serão queimados sobre você’ ".

[[v11-13-3]]

^<<v11-13-3,3>>^ Naquele mesmo dia o homem de Deus deu um sinal: "Este é o sinal que o Senhor declarou: O altar se fenderá, e as cinzas que estão sobre ele se derramarão".

[[v11-13-4]]

^<<v11-13-4,4>>^ Quando o rei Jeroboão ouviu o que o homem de Deus proclamava contra o altar de Betel, apontou para ele e ordenou: "Prendam-no! " Mas o braço que ele tinha estendido ficou paralisado, e não voltava ao normal.

[[v11-13-5]]

^<<v11-13-5,5>>^ Além disso, o altar se fendeu, e as suas cinzas se derramaram, conforme o sinal dado pelo homem de Deus por ordem do Senhor.

[[v11-13-6]]

^<<v11-13-6,6>>^ Então o rei disse ao homem de Deus: "Interceda junto ao Senhor, o seu Deus, e ore por mim para que meu braço se recupere". O homem de Deus intercedeu junto ao Senhor, e o braço do rei recuperou-se e voltou ao normal.

[[v11-13-7]]

^<<v11-13-7,7>>^ O rei disse ao homem de Deus: "Venha à minha casa e coma algo, e eu o recompensarei".

[[v11-13-8]]

^<<v11-13-8,8>>^ Mas o homem de Deus respondeu ao rei: "Mesmo que me desse a metade dos seus bens, eu não iria com você, nem comeria nem beberia nada neste lugar.

[[v11-13-9]]

^<<v11-13-9,9>>^ Pois recebi estas ordens pela palavra do Senhor: ‘Não coma pão nem beba água nem volte pelo mesmo caminho por onde veio’ ".

[[v11-13-10]]

^<<v11-13-10,10>>^ Por isso, quando ele voltou, não foi pelo caminho pelo qual tinha vindo a Betel.

[[v11-13-11]]

^<<v11-13-11,11>>^ Ora, havia um certo profeta, já idoso, morando em Betel. Seus filhos lhe contaram tudo o que o homem de Deus havia feito naquele dia e também o que ele dissera ao rei.

[[v11-13-12]]

^<<v11-13-12,12>>^ O pai lhes perguntou: "Por qual caminho ele foi? " E os seus filhos lhe mostraram por onde tinha ido o homem de Deus que viera de Judá.

[[v11-13-13]]

^<<v11-13-13,13>>^ Então disse aos filhos: "Selem o jumento para mim". E, depois de selarem o jumento, ele montou

[[v11-13-14]]

^<<v11-13-14,14>>^ e cavalgou à procura do homem de Deus, até que o encontrou sentado embaixo da Grande Árvore. E lhe perguntou: "Você é o homem de Deus que veio de Judá? " "Sou", respondeu.

[[v11-13-15]]

^<<v11-13-15,15>>^ Então o profeta lhe disse: "Venha à minha casa, comer alguma coisa".

[[v11-13-16]]

^<<v11-13-16,16>>^ O homem de Deus disse: "Não posso ir com você, nem posso comer pão ou beber água neste lugar.

[[v11-13-17]]

^<<v11-13-17,17>>^ A palavra do Senhor deu-me esta ordem: ‘Não coma pão nem beba água lá, nem volte pelo mesmo caminho por onde você foi’ ".

[[v11-13-18]]

^<<v11-13-18,18>>^ O profeta idoso respondeu: "Eu também sou profeta como você. E um anjo me disse por ordem do Senhor: ‘Faça-o voltar com você para a sua casa para que coma pão e beba água’ ". Mas ele estava mentindo.

[[v11-13-19]]

^<<v11-13-19,19>>^ E o homem de Deus voltou com ele e foi comer e beber em sua casa.

[[v11-13-20]]

^<<v11-13-20,20>>^ Enquanto ainda estavam sentados à mesa, a palavra do Senhor veio ao profeta idoso que o havia feito voltar.

[[v11-13-21]]

^<<v11-13-21,21>>^ Ele bradou ao homem de Deus que tinha vindo de Judá: "Assim diz o Senhor: ‘Você desafiou a palavra do Senhor e não obedeceu à ordem que o Senhor, o seu Deus, lhe deu.

[[v11-13-22]]

^<<v11-13-22,22>>^ Você voltou e comeu pão e bebeu água no lugar onde ele lhe falou que não comesse nem bebesse. Por isso o seu corpo não será sepultado no túmulo dos seus antepassados’ ".

[[v11-13-23]]

^<<v11-13-23,23>>^ Quando o homem de Deus acabou de comer e beber, o outro profeta selou seu jumento para ele.

[[v11-13-24]]

^<<v11-13-24,24>>^ No caminho, um leão o atacou e o matou, e o seu corpo ficou estendido no chão, ao lado do leão e do jumento.

[[v11-13-25]]

^<<v11-13-25,25>>^ Algumas pessoas que passaram viram o cadáver estendido ali, com o leão ao lado, e foram dar a notícia na cidade onde o profeta idoso vivia.

[[v11-13-26]]

^<<v11-13-26,26>>^ Quando o outro profeta soube disso, exclamou: "É o homem de Deus que desafiou a palavra do Senhor! O Senhor o entregou ao leão, que o feriu e o matou, conforme a palavra do Senhor o tinha advertido".

[[v11-13-27]]

^<<v11-13-27,27>>^ O profeta disse aos seus filhos: "Selem o jumento para mim", e eles o fizeram.

[[v11-13-28]]

^<<v11-13-28,28>>^ Ele foi e encontrou o cadáver caído no caminho, com o jumento e o leão ao seu lado. O leão não tinha comido o corpo nem ferido o jumento.

[[v11-13-29]]

^<<v11-13-29,29>>^ O profeta apanhou o corpo do homem de Deus, colocou-o sobre o jumento, e o levou de volta para Betel, a fim de chorar por ele e sepultá-lo.

[[v11-13-30]]

^<<v11-13-30,30>>^ Ele o pôs no seu próprio túmulo, e lamentaram por ele, exclamando: "Ah, meu irmão! "

[[v11-13-31]]

^<<v11-13-31,31>>^ Depois de sepultá-lo, disse aos seus filhos: "Quando eu morrer, enterrem-me no túmulo onde está sepultado o homem de Deus; ponham os meus ossos ao lado dos ossos dele.

[[v11-13-32]]

^<<v11-13-32,32>>^ Pois a mensagem que declarou por ordem do Senhor contra o altar de Betel e contra todos os altares idólatras das cidades de Samaria certamente se cumprirá".

[[v11-13-33]]

^<<v11-13-33,33>>^ Mesmo depois disso Jeroboão não mudou o seu mau procedimento, mas continuou a nomear dentre o povo sacerdotes para os altares idólatras. Ele consagrava para esses altares todo aquele que quisesse tornar-se sacerdote.

[[v11-13-34]]

^<<v11-13-34,34>>^ Esse foi o pecado da família de Jeroboão, que levou à sua queda e à sua eliminação da face da terra.

'''

xref:011-1-reis/011-1-reis-012.adoc#v11-12-0[&#60; Capítulo Anterior] | <<v11-13-0,Topo>> | xref:011-1-reis/011-1-reis-014.adoc#v11-14-0[Próximo Capítulo &#62;]