include::./index.adoc[]

[[v11-14-0]]
=== 1 Reis, 14
// nvi ?, NVI - Nova Versão Internacional

[[v11-14-1]]

^<<v11-14-1,1>>^ Naquela época, Abias, filho de Jeroboão, ficou doente,

[[v11-14-2]]

^<<v11-14-2,2>>^ e este disse à sua mulher: "Use um disfarce para não ser reconhecida como a mulher de Jeroboão, e vá a Siló, onde vive o profeta Aías, aquele que me disse que eu seria rei sobre este povo.

[[v11-14-3]]

^<<v11-14-3,3>>^ Leve para ele dez pães, alguns bolos e uma garrafa de mel. Ele lhe dirá o que vai acontecer com o menino".

[[v11-14-4]]

^<<v11-14-4,4>>^ A mulher de Jeroboão atendeu o seu pedido e foi à casa de Aías, em Siló. Ora, Aías já não conseguia enxergar; tinha ficado cego por causa da idade.

[[v11-14-5]]

^<<v11-14-5,5>>^ Mas o Senhor lhe tinha dito: "A mulher de Jeroboão está vindo para lhe perguntar acerca do filho dela, pois ele está doente, e você deve responder-lhe assim e assim. Quando ela chegar, vai fingir que é outra pessoa".

[[v11-14-6]]

^<<v11-14-6,6>>^ Quando Aías ouviu o som dos passos junto da porta, disse: "Entre, mulher de Jeroboão. Por que esse fingimento? Fui encarregado de lhe dar más notícias.

[[v11-14-7]]

^<<v11-14-7,7>>^ Vá dizer a Jeroboão que é isto o que o Senhor, o Deus de Israel, diz: ‘Tirei-o dentre o povo e o tornei líder sobre o meu povo Israel.

[[v11-14-8]]

^<<v11-14-8,8>>^ Tirei o reino da família de Davi e o dei a você, mas você não tem sido como o meu servo Davi, que obedecia aos meus mandamentos e me seguia de todo o coração, fazendo apenas o que eu aprovo.

[[v11-14-9]]

^<<v11-14-9,9>>^ Você tem feito mais mal do que todos os que viveram antes de você, pois fez para si outros deuses, ídolos de metal; você provocou a minha ira e voltou as costas para mim.

[[v11-14-10]]

^<<v11-14-10,10>>^ " ‘Por isso, trarei desgraça à família de Jeroboão. Matarei de Jeroboão até o último indivíduo do sexo masculino em Israel, seja escravo ou livre. Queimarei a família de Jeroboão até o fim como quem queima esterco.

[[v11-14-11]]

^<<v11-14-11,11>>^ Dos que pertencem a Jeroboão, os cães comerão os que morrerem na cidade, e as aves do céu se alimentarão dos que morrerem no campo. O Senhor falou! ’

[[v11-14-12]]

^<<v11-14-12,12>>^ "Quanto a você, volte para casa. Quando você puser os pés na cidade, o menino morrerá.

[[v11-14-13]]

^<<v11-14-13,13>>^ Todo o Israel chorará por ele e o sepultará. Ele é o único da família de Jeroboão que será sepultado, pois é o único da família de Jeroboão em quem o Senhor, o Deus de Israel, encontrou alguma coisa boa.

[[v11-14-14]]

^<<v11-14-14,14>>^ "O Senhor levantará para si um rei sobre Israel que eliminará a família de Jeroboão. Este é o dia! Como? Sim, agora mesmo.

[[v11-14-15]]

^<<v11-14-15,15>>^ E o Senhor ferirá Israel, de maneira que ficará como um junco balançando na água. Ele desarraigará Israel desta boa terra que deu aos seus antepassados e os espalhará para além do Rio, pois provocaram a ira do Senhor com os postes sagrados que fizeram.

[[v11-14-16]]

^<<v11-14-16,16>>^ E ele abandonará Israel por causa dos pecados que Jeroboão cometeu e tem feito Israel cometer".

[[v11-14-17]]

^<<v11-14-17,17>>^ Então a mulher de Jeroboão levantou-se e voltou para Tirza. Assim que entrou em casa, o menino morreu.

[[v11-14-18]]

^<<v11-14-18,18>>^ Eles o sepultaram, e todo o Israel chorou por ele, conforme o Senhor predissera por meio do seu servo, o profeta Aías.

[[v11-14-19]]

^<<v11-14-19,19>>^ Os demais acontecimentos do reinado de Jeroboão, suas guerras e como governou, estão escritos nos registros históricos dos reis de Israel.

[[v11-14-20]]

^<<v11-14-20,20>>^ Ele reinou durante vinte e dois anos, e então descansou com os seus antepassados. E o seu filho Nadabe foi o seu sucessor.

[[v11-14-21]]

^<<v11-14-21,21>>^ Roboão, filho de Salomão, foi rei de Judá. Tinha quarenta e um anos de idade quando começou a reinar, e reinou dezessete anos em Jerusalém, cidade que o Senhor havia escolhido dentre todas as tribos de Israel para nela pôr o seu nome. Sua mãe, uma amonita, chamava-se Naamá.

[[v11-14-22]]

^<<v11-14-22,22>>^ Judá fez o que o Senhor reprova. Pelos pecados que cometeram, eles despertaram a sua ira zelosa mais do que os seus antepassados o tinham feito.

[[v11-14-23]]

^<<v11-14-23,23>>^ Também construíram para si altares idólatras, colunas sagradas e postes sagrados sobre todos os montes e debaixo de todas as árvores frondosas.

[[v11-14-24]]

^<<v11-14-24,24>>^ Havia no país até prostitutos cultuais; o povo se envolvia em todas as práticas detestáveis das nações que o Senhor havia expulsado de diante dos israelitas.

[[v11-14-25]]

^<<v11-14-25,25>>^ No quinto ano do reinado de Roboão, Sisaque, rei do Egito, atacou Jerusalém.

[[v11-14-26]]

^<<v11-14-26,26>>^ Levou embora todos os tesouros do templo do Senhor e do palácio real, inclusive os escudos de ouro que Salomão havia feito.

[[v11-14-27]]

^<<v11-14-27,27>>^ Por isso o rei Roboão mandou fazer escudos de bronze para substituí-los, e os entregou aos chefes da guarda da entrada do palácio real.

[[v11-14-28]]

^<<v11-14-28,28>>^ Sempre que o rei ia ao templo do Senhor, os guardas empunhavam os escudos, e, em seguida, os devolviam à sala da guarda.

[[v11-14-29]]

^<<v11-14-29,29>>^ Os demais acontecimentos do reinado de Roboão, e tudo o que fez, estão escritos nos registros históricos dos reis de Judá.

[[v11-14-30]]

^<<v11-14-30,30>>^ Houve guerra constante entre Roboão e Jeroboão.

[[v11-14-31]]

^<<v11-14-31,31>>^ Roboão descansou com os seus antepassados e foi sepultado com eles na cidade de Davi. Sua mãe, uma amonita, chamava-se Naamá. E o seu filho Abias foi o seu sucessor.

'''

xref:011-1-reis/011-1-reis-013.adoc#v11-13-0[&#60; Capítulo Anterior] | <<v11-14-0,Topo>> | xref:011-1-reis/011-1-reis-015.adoc#v11-15-0[Próximo Capítulo &#62;]