include::./index.adoc[]

[[v11-18-0]]
=== 1 Reis, 18
// nvi ?, NVI - Nova Versão Internacional

[[v11-18-1]]

^<<v11-18-1,1>>^ Depois de um longo tempo, no terceiro ano da seca, a palavra do Senhor veio a Elias: "Vá apresentar-se a Acabe, pois enviarei chuva sobre a terra".

[[v11-18-2]]

^<<v11-18-2,2>>^ E Elias foi. Como a fome era grande em Samaria,

[[v11-18-3]]

^<<v11-18-3,3>>^ Acabe convocou Obadias, o responsável por seu palácio, homem que temia muito ao Senhor.

[[v11-18-4]]

^<<v11-18-4,4>>^ Enquanto Jezabel estava eliminando os profetas do Senhor, Obadias reuniu cem profetas e os escondeu em duas cavernas, cinqüenta em cada uma, e lhes forneceu comida e água.

[[v11-18-5]]

^<<v11-18-5,5>>^ Certa vez Acabe disse a Obadias: "Vamos a todas as fontes e vales do país. Talvez consigamos achar um pouco de capim para manter vivos os cavalos e as mulas e assim não será preciso matar nenhum animal".

[[v11-18-6]]

^<<v11-18-6,6>>^ De modo que dividiram o território que iam percorrer; Acabe foi numa direção e Obadias noutra.

[[v11-18-7]]

^<<v11-18-7,7>>^ Quando Obadias estava a caminho, Elias o encontrou. Obadias o reconheceu, inclinou-se até o chão e perguntou: "És tu mesmo, meu senhor Elias? "

[[v11-18-8]]

^<<v11-18-8,8>>^ "Sou", respondeu Elias. "Vá dizer ao seu senhor: Elias está aqui. "

[[v11-18-9]]

^<<v11-18-9,9>>^ "O que eu fiz de errado", perguntou Obadias, "para que entregues o teu servo a Acabe para ser morto?

[[v11-18-10]]

^<<v11-18-10,10>>^ Juro pelo nome do Senhor, o teu Deus, que não há uma só nação ou reino aonde o rei, meu senhor, não enviou alguém para procurar por ti. E, sempre que uma nação ou reino afirmava que tu não estavas lá, ele os fazia jurar que não conseguiram encontrar-te.

[[v11-18-11]]

^<<v11-18-11,11>>^ Mas agora me dizes para ir até o meu senhor e dizer-lhe: ‘Elias está aqui’.

[[v11-18-12]]

^<<v11-18-12,12>>^ Não sei para onde o Espírito do Senhor poderá levar-te quando eu te deixar. Se eu for dizer a Acabe e ele não te encontrar, ele me matará. E eu, que sou teu servo, tenho adorado o Senhor desde a minha juventude.

[[v11-18-13]]

^<<v11-18-13,13>>^ Por acaso não ouviste, meu senhor, o que eu fiz enquanto Jezabel estava matando os profetas do Senhor? Escondi cem dos profetas do Senhor em duas cavernas, cinqüenta em cada uma, e os abasteci de comida e água.

[[v11-18-14]]

^<<v11-18-14,14>>^ E agora me dizes para ir ao meu senhor e dizer-lhe: ‘Elias está aqui’. Ele vai me matar! "

[[v11-18-15]]

^<<v11-18-15,15>>^ E disse Elias: "Juro pelo nome do Senhor dos Exércitos, a quem eu sirvo, que hoje eu me apresentarei a Acabe".

[[v11-18-16]]

^<<v11-18-16,16>>^ Então Obadias dirigiu-se a Acabe e passou-lhe a informação, e Acabe foi ao encontro de Elias.

[[v11-18-17]]

^<<v11-18-17,17>>^ Quando viu Elias, disse-lhe: "É você mesmo, perturbador de Israel? "

[[v11-18-18]]

^<<v11-18-18,18>>^ "Não tenho perturbado Israel", Elias respondeu. "Mas você e a família do seu pai têm. Vocês abandonaram os mandamentos do Senhor e seguiram os baalins.

[[v11-18-19]]

^<<v11-18-19,19>>^ Agora convoque todo o povo de Israel para encontrar-se comigo no monte Carmelo. E traga os quatrocentos e cinqüenta profetas de Baal e os quatrocentos profetas de Aserá, que comem à mesa de Jezabel. "

[[v11-18-20]]

^<<v11-18-20,20>>^ Acabe convocou então todo o Israel e reuniu os profetas no monte Carmelo.

[[v11-18-21]]

^<<v11-18-21,21>>^ Elias dirigiu-se ao povo e disse: "Até quando vocês vão oscilar entre duas opiniões? Se o Senhor é Deus, sigam-no; mas, se Baal é Deus, sigam-no". O povo, porém, nada respondeu.

[[v11-18-22]]

^<<v11-18-22,22>>^ Disse então Elias: "Eu sou o único que restou dos profetas do Senhor, mas Baal tem quatrocentos e cinqüenta profetas.

[[v11-18-23]]

^<<v11-18-23,23>>^ Tragam dois novilhos. Escolham eles um, e cortem-no em pedaços e o ponham sobre a lenha, mas não acendam fogo. Eu prepararei o outro novilho e o colocarei sobre a lenha, e também não acenderei fogo nela.

[[v11-18-24]]

^<<v11-18-24,24>>^ Então vocês invocarão o nome do seu deus, e eu invocarei o nome do Senhor. O deus que responder por meio do fogo, esse é Deus". Então todo o povo disse: "O que você disse é bom".

[[v11-18-25]]

^<<v11-18-25,25>>^ Elias disse aos profetas de Baal: "Escolham um dos novilhos e preparem-no primeiro, visto que vocês são tantos. Clamem pelo nome do seu deus, mas não acendam o fogo".

[[v11-18-26]]

^<<v11-18-26,26>>^ Então pegaram o novilho que lhes foi dado e o prepararam. E clamaram pelo nome de Baal desde a manhã até o meio-dia. "Ó Baal, responde-nos! ", gritavam. E dançavam em volta do altar que haviam feito. Mas não houve nenhuma resposta; ninguém respondeu.

[[v11-18-27]]

^<<v11-18-27,27>>^ Ao meio-dia Elias começou a zombar deles. "Gritem mais alto! ", dizia, "já que ele é um deus. Quem sabe está meditando, ou ocupado, ou viajando. Talvez esteja dormindo e precise ser despertado. "

[[v11-18-28]]

^<<v11-18-28,28>>^ Então passaram a gritar ainda mais alto e a ferir-se com espadas e lanças, de acordo com o costume deles, até sangrarem.

[[v11-18-29]]

^<<v11-18-29,29>>^ Passou o meio-dia, e eles continuaram profetizando em transe até a hora do sacrifício da tarde. Mas não houve resposta alguma; ninguém respondeu, ninguém deu atenção.

[[v11-18-30]]

^<<v11-18-30,30>>^ Então Elias disse a todo o povo: "Aproximem-se de mim". O povo aproximou-se, e Elias reparou o altar do Senhor, que estava em ruínas.

[[v11-18-31]]

^<<v11-18-31,31>>^ Depois apanhou doze pedras, uma para cada tribo dos descendentes de Jacó, a quem a palavra do Senhor tinha sido dirigida, e disse: "Seu nome será Israel".

[[v11-18-32]]

^<<v11-18-32,32>>^ Com as pedras construiu um altar em honra do nome do Senhor, e cavou ao redor do altar uma valeta com capacidade de duas medidas de semente.

[[v11-18-33]]

^<<v11-18-33,33>>^ Depois arrumou a lenha, cortou o novilho em pedaços e o pôs sobre a lenha. Então lhes disse: "Encham de água quatro jarras grandes e derramem-na sobre o holocausto e sobre a lenha".

[[v11-18-34]]

^<<v11-18-34,34>>^ "Façam-no novamente", disse, e eles o fizeram de novo. "Façam-no pela terceira vez", ordenou, e eles o fizeram pela terceira vez.

[[v11-18-35]]

^<<v11-18-35,35>>^ A água escorria do altar, chegando a encher a valeta.

[[v11-18-36]]

^<<v11-18-36,36>>^ À hora do sacrifício, o profeta Elias colocou-se à frente e orou: "Ó Senhor, Deus de Abraão, de Isaque e de Israel, que hoje fique conhecido que tu és Deus em Israel e que sou o teu servo e que fiz todas estas coisas por ordem tua.

[[v11-18-37]]

^<<v11-18-37,37>>^ Responde-me, ó Senhor, responde-me, para que este povo saiba que tu, ó Senhor, és Deus, e que fazes o coração deles voltar para ti".

[[v11-18-38]]

^<<v11-18-38,38>>^ Então o fogo do Senhor caiu e queimou completamente o holocausto, a lenha, as pedras e o chão, e também secou totalmente a água na valeta.

[[v11-18-39]]

^<<v11-18-39,39>>^ Quando o povo viu isso, todos caíram prostrados e gritaram: "O Senhor é Deus! O Senhor é Deus! "

[[v11-18-40]]

^<<v11-18-40,40>>^ Então Elias ordenou-lhes: "Prendam os profetas de Baal. Não deixem nenhum escapar! " Eles os prenderam, e Elias os fez descer ao riacho de Quisom e lá os matou.

[[v11-18-41]]

^<<v11-18-41,41>>^ E Elias disse a Acabe: "Vá comer e beber, pois já ouço o barulho de chuva pesada".

[[v11-18-42]]

^<<v11-18-42,42>>^ Então Acabe foi comer e beber, mas Elias subiu até o alto do Carmelo, dobrou-se até o chão e pôs o rosto entre os joelhos.

[[v11-18-43]]

^<<v11-18-43,43>>^ "Vá e olhe na direção do mar", disse ao seu servo. E ele foi e olhou. "Não há nada lá", disse ele. Sete vezes Elias mandou: "Volte para ver".

[[v11-18-44]]

^<<v11-18-44,44>>^ Na sétima vez o servo disse: "Uma nuvem tão pequena quanto a mão de um homem está se levantando do mar". Então Elias disse: "Vá dizer a Acabe: Prepare o seu carro e desça, antes que a chuva o impeça".

[[v11-18-45]]

^<<v11-18-45,45>>^ Enquanto isso, nuvens escuras apareceram no céu, começou a ventar e começou a chover forte, e Acabe partiu de carro para Jezreel.

[[v11-18-46]]

^<<v11-18-46,46>>^ O poder do Senhor veio sobre Elias, e este, prendendo a capa com o cinto, correu à frente de Acabe por todo o caminho até Jezreel.

'''

xref:011-1-reis/011-1-reis-017.adoc#v11-17-0[&#60; Capítulo Anterior] | <<v11-18-0,Topo>> | xref:011-1-reis/011-1-reis-019.adoc#v11-19-0[Próximo Capítulo &#62;]