include::./index.adoc[]

[[v11-1-0]]
=== 1 Reis, 1
// nvi ?, NVI - Nova Versão Internacional

[[v11-1-1]]

^<<v11-1-1,1>>^ Quando o rei Davi envelheceu, já de idade bem avançada, cobriam-no de cobertores, mas ele não se aquecia.

[[v11-1-2]]

^<<v11-1-2,2>>^ Por isso os seus servos lhe propuseram: "Nós vamos procurar uma jovem virgem para servir e cuidar do rei. Ela se deitará ao seu lado, afim de aquecer o rei".

[[v11-1-3]]

^<<v11-1-3,3>>^ Então procuraram em todo o território de Israel uma jovem que fosse bonita e encontraram Abisague, uma sunamita, e a levaram ao rei.

[[v11-1-4]]

^<<v11-1-4,4>>^ A jovem, muito bonita, cuidava do rei e o servia, mas o rei não teve relações com ela.

[[v11-1-5]]

^<<v11-1-5,5>>^ Ora, Adonias, cuja mãe se chamava Hagite, tomou a dianteira e disse: "Eu serei o rei". Providenciou uma carruagem e cavalos, além de cinqüenta homens para correrem à sua frente.

[[v11-1-6]]

^<<v11-1-6,6>>^ Seu pai nunca o havia contrariado; nunca lhe perguntava: "Por que você age assim? " Adonias também tinha boa aparência e havia nascido depois de Absalão.

[[v11-1-7]]

^<<v11-1-7,7>>^ Adonias fez acordo com Joabe, filho de Zeruia, e com o sacerdote Abiatar, e eles, o seguiram e o apoiaram.

[[v11-1-8]]

^<<v11-1-8,8>>^ Mas o sacerdote Zadoque, Benaia, filho de Joiada, o profeta Natã, Simei, Reí e a guarda especial de Davi não deram apoio a Adonias.

[[v11-1-9]]

^<<v11-1-9,9>>^ Então Adonias sacrificou ovelhas, bois e novilhos gordos junto à pedra de Zoelete, próximo a En-Rogel. Convidou todos os seus irmãos, filhos do rei, e todos os homens de Judá que eram conselheiros do rei,

[[v11-1-10]]

^<<v11-1-10,10>>^ mas não convidou o profeta Natã nem Benaia nem a guarda especial nem o seu irmão Salomão.

[[v11-1-11]]

^<<v11-1-11,11>>^ Natã perguntou então a Bate-Seba, mãe de Salomão: "Você ainda não sabe que Adonias, o filho de Hagite, tornou-se rei, sem que o nosso senhor Davi ficasse sabendo?

[[v11-1-12]]

^<<v11-1-12,12>>^ Agora, vou dar-lhe um conselho para salvar a sua vida e também a vida do seu filho Salomão.

[[v11-1-13]]

^<<v11-1-13,13>>^ Vá perguntar ao rei Davi: Ó rei, meu senhor, não juraste a esta tua serva, prometendo: ‘Tenha certeza que o seu filho Salomão me sucederá como rei, e se assentará no meu trono? ’ Por que foi então, que Adonias se tornou rei?

[[v11-1-14]]

^<<v11-1-14,14>>^ Enquanto você ainda estiver conversando com o rei, eu entrarei e confirmarei as suas palavras".

[[v11-1-15]]

^<<v11-1-15,15>>^ Então Bate-Seba foi até o quarto do rei, já idoso, onde a sunamita Abisague cuidava dele.

[[v11-1-16]]

^<<v11-1-16,16>>^ Bate-Seba ajoelhou-se e prostrou-se diante do rei. "O que você quer? ", o rei perguntou.

[[v11-1-17]]

^<<v11-1-17,17>>^ Ela respondeu: "Meu senhor, tu mesmo juraste a esta tua serva, pelo Senhor o teu Deus: ‘Seu filho Salomão o sucederá como rei e se assentará no meu trono’.

[[v11-1-18]]

^<<v11-1-18,18>>^ Mas agora Adonias se tornou rei, sem que o rei meu senhor o soubesse.

[[v11-1-19]]

^<<v11-1-19,19>>^ Ele sacrificou muitos bois, novilhos gordos e ovelhas, e convidou todos os filhos do rei, o sacerdote Abiatar, e Joabe, o comandante do exército, mas não convidou o teu servo Salomão.

[[v11-1-20]]

^<<v11-1-20,20>>^ Agora, ó rei, meu senhor, os olhos de todo o Israel estão sobre ti para saber de tua parte, quem sucederá ao rei, meu senhor, no trono.

[[v11-1-21]]

^<<v11-1-21,21>>^ De outro modo, tão logo o rei, meu senhor descanse com os seus antepassados, eu e o meu filho Salomão seremos tratados como traidores".

[[v11-1-22]]

^<<v11-1-22,22>>^ Ela ainda conversava com o rei, quando o profeta Natã chegou.

[[v11-1-23]]

^<<v11-1-23,23>>^ Assim que informaram o rei que o profeta Natã havia chegado, ele entrou e prostrou-se, rosto em terra, diante do rei.

[[v11-1-24]]

^<<v11-1-24,24>>^ E Natã lhe perguntou: "Ó rei, meu senhor, por acaso declaraste que Adonias te sucederia como rei e que ele se assentaria no teu trono?

[[v11-1-25]]

^<<v11-1-25,25>>^ Hoje ele foi matar muitos bois, novilhos gordos e ovelhas. Convidou todos os filhos do rei, os comandantes do exército e o sacerdote Abiatar. Agora eles estão comendo e bebendo com ele e comemorando: ‘Viva o rei Adonias! ’

[[v11-1-26]]

^<<v11-1-26,26>>^ Mas ele não convidou a mim, que sou teu servo, nem ao sacerdote Zadoque nem a Benaia, filho de Joiada, nem a teu servo Salomão.

[[v11-1-27]]

^<<v11-1-27,27>>^ Seria isto algo que o rei, meu senhor, fez sem deixar que os seus conselheiros soubessem quem sucederia ao rei, meu senhor, no trono? "

[[v11-1-28]]

^<<v11-1-28,28>>^ Então o rei Davi ordenou: "Chamem Bate-Seba". Ela entrou e ficou de pé diante dele.

[[v11-1-29]]

^<<v11-1-29,29>>^ O rei fez então um juramento: "Juro pelo nome do Senhor, o qual me livrou de todas as adversidades,

[[v11-1-30]]

^<<v11-1-30,30>>^ que sem dúvida hoje mesmo vou executar o que jurei pelo Senhor, o Deus de Israel. O seu filho Salomão me sucederá como rei e se assentará no meu trono em meu lugar".

[[v11-1-31]]

^<<v11-1-31,31>>^ Então Bate-Seba prostrou-se, rosto em terra, e, ajoelhando-se diante do rei, disse: "Que o rei Davi, meu senhor, viva para sempre! "

[[v11-1-32]]

^<<v11-1-32,32>>^ O rei Davi ordenou: "Chamem o sacerdote Zadoque, o profeta Natã e Benaia, filho de Joiada". Quando chegaram à presença do rei,

[[v11-1-33]]

^<<v11-1-33,33>>^ ele os instruiu: "Levem os conselheiros do seu senhor com vocês e ponham o meu filho Salomão sobre a minha mula e levem-no a Giom.

[[v11-1-34]]

^<<v11-1-34,34>>^ Ali o sacerdote Zadoque e o profeta Natã o ungirão rei sobre Israel. Então toquem a trombeta e gritem: Viva o rei Salomão!

[[v11-1-35]]

^<<v11-1-35,35>>^ Depois acompanhem-no, e ele virá assentar-se no meu trono e reinará em meu lugar. Eu o designei para governar Israel e Judá".

[[v11-1-36]]

^<<v11-1-36,36>>^ Benaia, filho de Joiada, respondeu ao rei: "Assim se fará! Que o Senhor, o Deus do rei, meu senhor, o confirme.

[[v11-1-37]]

^<<v11-1-37,37>>^ Assim como o Senhor esteve com o rei, meu senhor, também esteja ele com Salomão para que ele tenha um reinado ainda mais glorioso do que o meu senhor, o rei Davi! "

[[v11-1-38]]

^<<v11-1-38,38>>^ Então o sacerdote Zadoque, o profeta Natã, Benaia, filho de Joiada, os queretitas e os peletitas fizeram Salomão montar a mula do rei Davi e o escoltaram até Giom.

[[v11-1-39]]

^<<v11-1-39,39>>^ O sacerdote Zadoque pegou na Tenda o chifre com óleo e ungiu Salomão. Então tocaram a trombeta e todo o povo gritou: "Viva o rei Salomão! "

[[v11-1-40]]

^<<v11-1-40,40>>^ E todo o povo o acompanhou, tocando flautas e comemorando, de tal forma que o chão tremia com o barulho.

[[v11-1-41]]

^<<v11-1-41,41>>^ Adonias e todos os seus convidados souberam disso quando estavam terminando o banquete. Ao ouvir o toque da trombeta, Joabe perguntou: "O que significa esta gritaria, esse alvoroço na cidade? "

[[v11-1-42]]

^<<v11-1-42,42>>^ Falava ele ainda, quando chegou Jônatas, filho do sacerdote Abiatar. E Adonias lhe disse: "Entre, pois um homem digno como você deve estar trazendo boas notícias! "

[[v11-1-43]]

^<<v11-1-43,43>>^ "De modo algum", respondeu Jônatas a Adonias. "Davi, o nosso rei e senhor, constituiu rei a Salomão.

[[v11-1-44]]

^<<v11-1-44,44>>^ O rei enviou com ele o sacerdote Zadoque, o profeta Natã, Benaia, filho de Joiada, os queretitas e os peletitas, e eles o fizeram montar a mula do rei.

[[v11-1-45]]

^<<v11-1-45,45>>^ Depois o sacerdote Zadoque e o profeta Natã o ungiram rei em Giom. De lá eles saíram comemorando, e a cidade está alvoroçada. É esse o barulho que vocês ouvem.

[[v11-1-46]]

^<<v11-1-46,46>>^ Além disso, Salomão já se assentou no trono real.

[[v11-1-47]]

^<<v11-1-47,47>>^ Até mesmo os oficiais do rei foram cumprimentar Davi, o nosso rei e senhor, dizendo: ‘Que o teu Deus torne o nome de Salomão mais famoso que o teu, e o seu reinado mais glorioso do que o teu! ’ E o rei curvou-se reverentemente em sua cama,

[[v11-1-48]]

^<<v11-1-48,48>>^ e disse: ‘Bendito seja o Senhor, o Deus de Israel, que permitiu que os meus olhos vissem hoje um sucessor em meu trono’ ".

[[v11-1-49]]

^<<v11-1-49,49>>^ Diante disso, todos os convidados de Adonias entraram em pânico e se dispersaram.

[[v11-1-50]]

^<<v11-1-50,50>>^ Mas Adonias, com medo de Salomão, foi agarrar-se às pontas do altar.

[[v11-1-51]]

^<<v11-1-51,51>>^ Então informaram a Salomão: "Adonias está com medo do rei Salomão e está agarrado às pontas do altar. Ele diz: ‘Que o rei Salomão me jure que não matará o seu servo pela espada’ ".

[[v11-1-52]]

^<<v11-1-52,52>>^ Salomão respondeu: "Se ele se mostrar confiável, não cairá nem um só fio de cabelo da sua cabeça; mas se nele se descobrir alguma maldade, ele morrerá".

[[v11-1-53]]

^<<v11-1-53,53>>^ Então o rei enviou alguns soldados, e eles o fizeram descer do altar. E Adonias veio e se curvou solenemente perante o rei Salomão, que lhe disse: "Vá para casa".

'''

xref:010-2-samuel/010-2-samuel-024.adoc#v10-24-0[&#60; Capítulo Anterior] | <<v11-1-0,Topo>> | xref:011-1-reis/011-1-reis-002.adoc#v11-2-0[Próximo Capítulo &#62;]