include::./index.adoc[]

[[v42-17-0]]
=== Lucas, 17
// nvi ?, NVI - Nova Versão Internacional

[[v42-17-1]]

^<<v42-17-1,1>>^ Jesus disse aos seus discípulos: "É inevitável que aconteçam coisas que levem o povo a tropeçar, mas ai da pessoa por meio de quem elas acontecem.

[[v42-17-2]]

^<<v42-17-2,2>>^ Seria melhor que ela fosse lançada no mar com uma pedra de moinho amarrada no pescoço, do que levar um desses pequeninos a pecar.

[[v42-17-3]]

^<<v42-17-3,3>>^ Tomem cuidado. "Se o seu irmão pecar, repreenda-o e, se ele se arrepender, perdoe-lhe.

[[v42-17-4]]

^<<v42-17-4,4>>^ Se pecar contra você sete vezes no dia, e sete vezes voltar a você e disser: ‘Estou arrependido’, perdoe-lhe".

[[v42-17-5]]

^<<v42-17-5,5>>^ Os apóstolos disseram ao Senhor: "Aumenta a nossa fé! "

[[v42-17-6]]

^<<v42-17-6,6>>^ Ele respondeu: "Se vocês tiverem fé do tamanho de uma semente de mostarda, poderão dizer a esta amoreira: ‘Arranque-se e plante-se no mar’, e ela lhes obedecerá.

[[v42-17-7]]

^<<v42-17-7,7>>^ "Qual de vocês que, tendo um servo que esteja arando ou cuidando das ovelhas, lhe dirá, quando ele chegar do campo: ‘Venha agora e sente-se para comer’?

[[v42-17-8]]

^<<v42-17-8,8>>^ Pelo contrário, não dirá: ‘Prepare o meu jantar, apronte-se e sirva-me enquanto como e bebo; depois disso você pode comer e beber’?

[[v42-17-9]]

^<<v42-17-9,9>>^ Será que ele agradecerá ao servo por ter feito o que lhe foi ordenado?

[[v42-17-10]]

^<<v42-17-10,10>>^ Assim também vocês, quando tiverem feito tudo o que lhes for ordenado, devem dizer: ‘Somos servos inúteis; apenas cumprimos o nosso dever’ ".

[[v42-17-11]]

^<<v42-17-11,11>>^ A caminho de Jerusalém, Jesus passou pela divisa entre Samaria e Galiléia.

[[v42-17-12]]

^<<v42-17-12,12>>^ Ao entrar num povoado, dez leprosos dirigiram-se a ele. Ficaram a certa distância

[[v42-17-13]]

^<<v42-17-13,13>>^ e gritaram em alta voz: "Jesus, Mestre, tem piedade de nós! "

[[v42-17-14]]

^<<v42-17-14,14>>^ Ao vê-los, ele disse: "Vão mostrar-se aos sacerdotes". Enquanto eles iam, foram purificados.

[[v42-17-15]]

^<<v42-17-15,15>>^ Um deles, quando viu que estava curado, voltou, louvando a Deus em alta voz.

[[v42-17-16]]

^<<v42-17-16,16>>^ Prostrou-se aos pés de Jesus e lhe agradeceu. Este era samaritano.

[[v42-17-17]]

^<<v42-17-17,17>>^ Jesus perguntou: "Não foram purificados todos os dez? Onde estão os outros nove?

[[v42-17-18]]

^<<v42-17-18,18>>^ Não se achou nenhum que voltasse e desse louvor a Deus, a não ser este estrangeiro? "

[[v42-17-19]]

^<<v42-17-19,19>>^ Então ele lhe disse: "Levante-se e vá; a sua fé o salvou".

[[v42-17-20]]

^<<v42-17-20,20>>^ Certa vez, tendo sido interrogado pelos fariseus sobre quando viria o Reino de Deus, Jesus respondeu: "O Reino de Deus não vem de modo visível,

[[v42-17-21]]

^<<v42-17-21,21>>^ nem se dirá: ‘Aqui está ele’, ou ‘Lá está’; porque o Reino de Deus está entre vocês".

[[v42-17-22]]

^<<v42-17-22,22>>^ Depois disse aos seus discípulos: "Chegará o tempo em que vocês desejarão ver um dos dias do Filho do homem, mas não verão.

[[v42-17-23]]

^<<v42-17-23,23>>^ Dirão a vocês: ‘Lá está ele! ’ ou ‘Aqui está! ’ Não se apressem em segui-los.

[[v42-17-24]]

^<<v42-17-24,24>>^ Pois o Filho do homem no seu dia será como o relâmpago cujo brilho vai de uma extremidade à outra do céu.

[[v42-17-25]]

^<<v42-17-25,25>>^ Mas antes é necessário que ele sofra muito e seja rejeitado por esta geração.

[[v42-17-26]]

^<<v42-17-26,26>>^ "Assim como foi nos dias de Noé, também será nos dias do Filho do homem.

[[v42-17-27]]

^<<v42-17-27,27>>^ O povo vivia comendo, bebendo, casando-se e sendo dado em casamento, até o dia em que Noé entrou na arca. Então veio o dilúvio e os destruiu a todos.

[[v42-17-28]]

^<<v42-17-28,28>>^ "Aconteceu a mesma coisa nos dias de Ló. O povo estava comendo e bebendo, comprando e vendendo, plantando e construindo.

[[v42-17-29]]

^<<v42-17-29,29>>^ Mas no dia em que Ló saiu de Sodoma, choveu fogo e enxofre do céu e os destruiu a todos.

[[v42-17-30]]

^<<v42-17-30,30>>^ "Acontecerá exatamente assim no dia em que o Filho do homem for revelado.

[[v42-17-31]]

^<<v42-17-31,31>>^ Naquele dia, quem estiver no telhado de sua casa, não deve desça para apanhar os seus bens dentro de casa. Semelhantemente, quem estiver no campo, não deve voltar atrás por coisa alguma.

[[v42-17-32]]

^<<v42-17-32,32>>^ Lembrem-se da mulher de Ló!

[[v42-17-33]]

^<<v42-17-33,33>>^ Quem tentar conservar a sua vida a perderá, e quem perder a sua vida a preservará.

[[v42-17-34]]

^<<v42-17-34,34>>^ Eu lhes digo: naquela noite duas pessoas estarão numa cama; uma será tirada e a outra deixada.

[[v42-17-35]]

^<<v42-17-35,35>>^ Duas mulheres estarão moendo trigo juntas; uma será tirada e a outra deixada.

[[v42-17-36]]

^<<v42-17-36,36>>^ Duas pessoas estarão no campo; uma será tirada e a outra deixada".

[[v42-17-37]]

^<<v42-17-37,37>>^ "Onde, Senhor? ", perguntaram eles. Ele respondeu: "Onde houver um cadáver, ali se ajuntarão os abutres".

'''

xref:042-lucas/042-lucas-016.adoc#v42-16-0[&#60; Capítulo Anterior] | <<v42-17-0,Topo>> | xref:042-lucas/042-lucas-018.adoc#v42-18-0[Próximo Capítulo &#62;]