include::./index.adoc[]

[[v42-22-0]]
=== Lucas, 22
// nvi ?, NVI - Nova Versão Internacional

[[v42-22-1]]

^<<v42-22-1,1>>^ Estava se aproximando a festa dos pães sem fermento, chamada Páscoa,

[[v42-22-2]]

^<<v42-22-2,2>>^ e os chefes dos sacerdotes e os mestres da lei estavam procurando um meio de matar Jesus, mas tinham medo do povo.

[[v42-22-3]]

^<<v42-22-3,3>>^ Então Satanás entrou em Judas, chamado Iscariotes, um dos Doze.

[[v42-22-4]]

^<<v42-22-4,4>>^ Judas dirigiu-se aos chefes dos sacerdotes e aos oficiais da guarda do templo e tratou com eles como lhes poderia entregar Jesus.

[[v42-22-5]]

^<<v42-22-5,5>>^ A proposta muito os alegrou, e lhe prometeram dinheiro.

[[v42-22-6]]

^<<v42-22-6,6>>^ Ele consentiu e ficou esperando uma oportunidade para lhes entregar Jesus quando a multidão não estivesse presente.

[[v42-22-7]]

^<<v42-22-7,7>>^ Finalmente, chegou o dia dos pães sem fermento, no qual devia ser sacrificado o cordeiro pascal.

[[v42-22-8]]

^<<v42-22-8,8>>^ Jesus enviou Pedro e João, dizendo: "Vão preparar a refeição da Páscoa".

[[v42-22-9]]

^<<v42-22-9,9>>^ "Onde queres que a preparemos? ", perguntaram eles.

[[v42-22-10]]

^<<v42-22-10,10>>^ Ele respondeu: "Ao entrarem na cidade, vocês encontrarão um homem carregando um pote de água. Sigam-no até a casa em que ele entrar

[[v42-22-11]]

^<<v42-22-11,11>>^ e digam ao dono da casa: ‘O Mestre pergunta: Onde é o salão de hóspedes no qual poderei comer a Páscoa com os meus discípulos? ’

[[v42-22-12]]

^<<v42-22-12,12>>^ Ele lhes mostrará uma ampla sala no andar superior, toda mobiliada. Façam ali os preparativos".

[[v42-22-13]]

^<<v42-22-13,13>>^ Eles saíram e encontraram tudo como Jesus lhes tinha dito. Então, prepararam a Páscoa.

[[v42-22-14]]

^<<v42-22-14,14>>^ Quando chegou a hora, Jesus e os seus apóstolos reclinaram-se à mesa.

[[v42-22-15]]

^<<v42-22-15,15>>^ E disse-lhes: "Desejei ansiosamente comer esta Páscoa com vocês antes de sofrer.

[[v42-22-16]]

^<<v42-22-16,16>>^ Pois eu lhes digo: Não comerei dela novamente até que se cumpra no Reino de Deus".

[[v42-22-17]]

^<<v42-22-17,17>>^ Recebendo um cálice, ele deu graças e disse: "Tomem isto e partilhem uns com os outros.

[[v42-22-18]]

^<<v42-22-18,18>>^ Pois eu lhes digo que não beberei outra vez do fruto da videira até que venha o Reino de Deus".

[[v42-22-19]]

^<<v42-22-19,19>>^ Tomando o pão, deu graças, partiu-o e o deu aos discípulos, dizendo: "Isto é o meu corpo dado em favor de vocês; façam isto em memória de mim".

[[v42-22-20]]

^<<v42-22-20,20>>^ Da mesma forma, depois da ceia, tomou o cálice, dizendo: "Este cálice é a nova aliança no meu sangue, derramado em favor de vocês.

[[v42-22-21]]

^<<v42-22-21,21>>^ "Mas eis que a mão daquele que vai me trair está com a minha sobre a mesa.

[[v42-22-22]]

^<<v42-22-22,22>>^ O Filho do homem vai, como foi determinado; mas ai daquele que o trai! "

[[v42-22-23]]

^<<v42-22-23,23>>^ Eles começaram a perguntar entre si qual deles iria fazer aquilo.

[[v42-22-24]]

^<<v42-22-24,24>>^ Surgiu também uma discussão entre eles, acerca de qual deles era considerado o maior.

[[v42-22-25]]

^<<v42-22-25,25>>^ Jesus lhes disse: "Os reis das nações dominam sobre elas; e os que exercem autoridade sobre elas são chamados benfeitores.

[[v42-22-26]]

^<<v42-22-26,26>>^ Mas, vocês não serão assim. Pelo contrário, o maior entre vocês deverá ser como o mais jovem, e aquele que governa como o que serve.

[[v42-22-27]]

^<<v42-22-27,27>>^ Pois quem é maior: o que está à mesa, ou o que serve? Não é o que está à mesa? Mas eu estou entre vocês como quem serve.

[[v42-22-28]]

^<<v42-22-28,28>>^ Vocês são os que têm permanecido ao meu lado durante as minhas provações.

[[v42-22-29]]

^<<v42-22-29,29>>^ E eu lhes designo um Reino, assim como meu Pai o designou a mim,

[[v42-22-30]]

^<<v42-22-30,30>>^ para que vocês possam comer e beber à minha mesa no meu Reino e sentar-se em tronos, julgando as doze tribos de Israel.

[[v42-22-31]]

^<<v42-22-31,31>>^ "Simão, Simão, Satanás pediu vocês para peneirá-los como trigo.

[[v42-22-32]]

^<<v42-22-32,32>>^ Mas eu orei por você, para que a sua fé não desfaleça. E quando você se converter, fortaleça os seus irmãos".

[[v42-22-33]]

^<<v42-22-33,33>>^ Mas ele respondeu: "Estou pronto para ir contigo para a prisão e para a morte".

[[v42-22-34]]

^<<v42-22-34,34>>^ Respondeu Jesus: "Eu lhe digo, Pedro, que antes que o galo cante hoje, três vezes você negará que me conhece".

[[v42-22-35]]

^<<v42-22-35,35>>^ Então Jesus lhes perguntou: "Quando eu os enviei sem bolsa, saco de viagem ou sandálias, faltou-lhes alguma coisa? " "Nada", responderam eles.

[[v42-22-36]]

^<<v42-22-36,36>>^ Ele lhes disse: "Mas agora, se vocês têm bolsa, levem-na, e também o saco de viagem; e se não têm espada, vendam a sua capa e comprem uma.

[[v42-22-37]]

^<<v42-22-37,37>>^ Está escrito: ‘E ele foi contado com os transgressores’; e eu lhes digo que isto precisa cumprir-se em mim. Sim, o que está escrito a meu respeito está para se cumprir".

[[v42-22-38]]

^<<v42-22-38,38>>^ Os discípulos disseram: "Vê, Senhor, aqui estão duas espadas". "É o suficiente! ", respondeu ele.

[[v42-22-39]]

^<<v42-22-39,39>>^ Como de costume, Jesus foii para o monte das Oliveiras, e os seus discípulos o seguiram.

[[v42-22-40]]

^<<v42-22-40,40>>^ Chegando ao lugar, ele lhes disse: "Orem para que vocês não caiam em tentação".

[[v42-22-41]]

^<<v42-22-41,41>>^ Ele se afastou deles a uma pequena distância, ajoelhou-se e começou a orar:

[[v42-22-42]]

^<<v42-22-42,42>>^ "Pai, se queres, afasta de mim este cálice; contudo, não seja feita a minha vontade, mas a tua".

[[v42-22-43]]

^<<v42-22-43,43>>^ Apareceu-lhe então um anjo do céu que o fortalecia.

[[v42-22-44]]

^<<v42-22-44,44>>^ Estando angustiado, ele orou ainda mais intensamente; e o seu suor era como gotas de sangue que caíam no chão.

[[v42-22-45]]

^<<v42-22-45,45>>^ Quando se levantou da oração e voltou aos discípulos, encontrou-os dormindo, dominados pela tristeza.

[[v42-22-46]]

^<<v42-22-46,46>>^ "Por que estão dormindo? ", perguntou-lhes. "Levantem-se e orem para que vocês não caiam em tentação! "

[[v42-22-47]]

^<<v42-22-47,47>>^ Enquanto ele ainda falava, apareceu uma multidão conduzida por Judas, um dos Doze. Este se aproximou de Jesus para saudá-lo com um beijo.

[[v42-22-48]]

^<<v42-22-48,48>>^ Mas Jesus lhe perguntou: "Judas, com um beijo você está traindo o Filho do homem? "

[[v42-22-49]]

^<<v42-22-49,49>>^ Ao verem o que ia acontecer, os que estavam com Jesus lhe disseram: "Senhor, atacaremos com espadas? "

[[v42-22-50]]

^<<v42-22-50,50>>^ E um deles feriu o servo do sumo sacerdote, decepando-lhe a orelha direita.

[[v42-22-51]]

^<<v42-22-51,51>>^ Jesus, porém, respondeu: "Basta! " E tocando na orelha do homem, ele o curou.

[[v42-22-52]]

^<<v42-22-52,52>>^ Então Jesus disse aos chefes dos sacerdotes, aos oficiais da guarda do templo e aos líderes religiosos que tinham vindo procurá-lo: "Estou eu chefiando alguma rebelião, para que vocês tenham vindo com espadas e varas?

[[v42-22-53]]

^<<v42-22-53,53>>^ Todos os dias eu estava com vocês no templo e vocês não levantaram a mão contra mim. Mas esta é a hora de vocês — quando as trevas reinam".

[[v42-22-54]]

^<<v42-22-54,54>>^ Então, prendendo-o, levaram-no para a casa do sumo sacerdote. Pedro os seguia à distância.

[[v42-22-55]]

^<<v42-22-55,55>>^ Mas, quando acenderam um fogo no meio do pátio e se sentaram ao redor dele, Pedro sentou-se com eles.

[[v42-22-56]]

^<<v42-22-56,56>>^ Uma criada o viu sentado ali à luz do fogo. Olhou fixamente para ele e disse: "Este homem estava com ele".

[[v42-22-57]]

^<<v42-22-57,57>>^ Mas ele negou: "Mulher, não o conheço".

[[v42-22-58]]

^<<v42-22-58,58>>^ Pouco depois, um homem o viu e disse: "Você também é um deles". "Homem, não sou! ", respondeu Pedro.

[[v42-22-59]]

^<<v42-22-59,59>>^ Cerca de uma hora mais tarde, outro afirmou: "Certamente este homem estava com ele, pois é galileu".

[[v42-22-60]]

^<<v42-22-60,60>>^ Pedro respondeu: "Homem, não sei do que você está falando! " Falava ele ainda, quando o galo cantou.

[[v42-22-61]]

^<<v42-22-61,61>>^ O Senhor voltou-se e olhou diretamente para Pedro. Então Pedro se lembrou da palavra que o Senhor lhe tinha dito: "Antes que o galo cante hoje, você me negará três vezes".

[[v42-22-62]]

^<<v42-22-62,62>>^ Saindo dali, chorou amargamente.

[[v42-22-63]]

^<<v42-22-63,63>>^ Os homens que estavam detendo Jesus começaram a zombar dele e a bater nele.

[[v42-22-64]]

^<<v42-22-64,64>>^ Cobriam seus olhos e perguntavam: "Profetize! Quem foi que lhe bateu? "

[[v42-22-65]]

^<<v42-22-65,65>>^ E lhe dirigiam muitas outras palavras de insulto.

[[v42-22-66]]

^<<v42-22-66,66>>^ Ao romper do dia, reuniu-se o Sinédrio, tanto os chefes dos sacerdotes quanto os mestres da lei, e Jesus foi levado perante eles.

[[v42-22-67]]

^<<v42-22-67,67>>^ "Se você é o Cristo, diga-nos", disseram eles. Jesus respondeu: "Se eu vos disser, não crereis em mim

[[v42-22-68]]

^<<v42-22-68,68>>^ e, se eu vos perguntar, não me respondereis.

[[v42-22-69]]

^<<v42-22-69,69>>^ Mas de agora em diante o Filho do homem estará assentado à direita do Deus Todo-poderoso".

[[v42-22-70]]

^<<v42-22-70,70>>^ Perguntaram-lhe todos: "Então, você é o Filho de Deus? " "Vós estais dizendo que eu sou", respondeu ele.

[[v42-22-71]]

^<<v42-22-71,71>>^ Eles disseram: "Por que precisamos de mais testemunhas? Acabamos de ouvir dos próprios lábios dele".

'''

xref:042-lucas/042-lucas-021.adoc#v42-21-0[&#60; Capítulo Anterior] | <<v42-22-0,Topo>> | xref:042-lucas/042-lucas-023.adoc#v42-23-0[Próximo Capítulo &#62;]