include::./index.adoc[]

[[v42-9-0]]
=== Lucas, 9
// nvi ?, NVI - Nova Versão Internacional

[[v42-9-1]]

^<<v42-9-1,1>>^ Reunindo os Doze, Jesus deu-lhes poder e autoridade para expulsar todos os demônios e curar doenças,

[[v42-9-2]]

^<<v42-9-2,2>>^ e os enviou a pregar o Reino de Deus e a curar os enfermos.

[[v42-9-3]]

^<<v42-9-3,3>>^ E disse-lhes: "Não levem nada pelo caminho: nem bordão, nem saco de viagem, nem pão, nem dinheiro, nem túnica extra.

[[v42-9-4]]

^<<v42-9-4,4>>^ Na casa em que vocês entrarem, fiquem ali até partirem.

[[v42-9-5]]

^<<v42-9-5,5>>^ Se não os receberem, sacudam a poeira dos seus pés quando saírem daquela cidade, como testemunho contra eles".

[[v42-9-6]]

^<<v42-9-6,6>>^ Assim, eles saíram e foram pelos povoados, pregando o evangelho e fazendo curas por toda parte.

[[v42-9-7]]

^<<v42-9-7,7>>^ Herodes, o tetrarca, ouviu falar de tudo o que estava acontecendo e ficou perplexo, porque algumas pessoas estavam dizendo que João tinha ressuscitado dos mortos;

[[v42-9-8]]

^<<v42-9-8,8>>^ outros, que Elias tinha aparecido; e ainda outros, que um dos profetas do passado tinha voltado à vida.

[[v42-9-9]]

^<<v42-9-9,9>>^ Mas Herodes disse: "João, eu decapitei! Quem, pois, é este de quem ouço essas coisas? " E procurava vê-lo.

[[v42-9-10]]

^<<v42-9-10,10>>^ Ao voltarem, os apóstolos relataram a Jesus o que tinham feito. Então ele os tomou consigo, e retiraram-se para uma cidade chamada Betsaida;

[[v42-9-11]]

^<<v42-9-11,11>>^ mas as multidões ficaram sabendo, e o seguiram. Ele as acolheu, e falava-lhes acerca do Reino de Deus, e curava os que precisavam de cura.

[[v42-9-12]]

^<<v42-9-12,12>>^ Ao fim da tarde os Doze aproximaram-se dele e disseram: "Manda embora a multidão para que eles possam ir aos campos vizinhos e aos povoados, e encontrem comida e pousada, porque aqui estamos em lugar deserto".

[[v42-9-13]]

^<<v42-9-13,13>>^ Ele, porém, respondeu: "Dêem-lhes vocês algo para comer". Eles disseram: "Temos apenas cinco pães e dois peixes — a menos que compremos alimento para toda esta multidão".

[[v42-9-14]]

^<<v42-9-14,14>>^ ( E estavam ali cerca de cinco mil homens ). Mas ele disse aos seus discípulos: "Façam-nos sentar-se em grupos de cinqüenta".

[[v42-9-15]]

^<<v42-9-15,15>>^ Os discípulos assim fizeram, e todos se assentaram.

[[v42-9-16]]

^<<v42-9-16,16>>^ Tomando os cinco pães e os dois peixes, e olhando para o céu, deu graças e os partiu. Em seguida, entregou-os aos discípulos para que os servissem ao povo.

[[v42-9-17]]

^<<v42-9-17,17>>^ Todos comeram e ficaram satisfeitos, e os discípulos recolheram doze cestos cheios de pedaços que sobraram.

[[v42-9-18]]

^<<v42-9-18,18>>^ Certa vez Jesus estava orando em particular, e com ele estavam os seus discípulos; então lhes perguntou: "Quem as multidões dizem que eu sou? "

[[v42-9-19]]

^<<v42-9-19,19>>^ Eles responderam: "Alguns dizem que és João Batista; outros, Elias; e, ainda outros, que és um dos profetas do passado que ressuscitou".

[[v42-9-20]]

^<<v42-9-20,20>>^ "E vocês, o que dizem? ", perguntou. "Quem vocês dizem que eu sou? " Pedro respondeu: "O Cristo de Deus".

[[v42-9-21]]

^<<v42-9-21,21>>^ Jesus os advertiu severamente que não contassem isso a ninguém.

[[v42-9-22]]

^<<v42-9-22,22>>^ E disse: "É necessário que o Filho do homem sofra muitas coisas e seja rejeitado pelos líderes religiosos, pelos chefes dos sacerdotes e pelos mestres da lei, seja morto e ressuscite no terceiro dia".

[[v42-9-23]]

^<<v42-9-23,23>>^ Jesus dizia a todos: "Se alguém quiser acompanhar-me, negue-se a si mesmo, tome diariamente a sua cruz e siga-me.

[[v42-9-24]]

^<<v42-9-24,24>>^ Pois quem quiser salvar a sua vida a perderá; mas quem perder a vida por minha causa, este a salvará.

[[v42-9-25]]

^<<v42-9-25,25>>^ Pois que adianta ao homem ganhar o mundo inteiro, e perder-se ou destruir a si mesmo?

[[v42-9-26]]

^<<v42-9-26,26>>^ Se alguém se envergonhar de mim e das minhas palavras, o Filho do homem se envergonhará dele, quando vier em sua glória e na glória do Pai e dos santos anjos.

[[v42-9-27]]

^<<v42-9-27,27>>^ Garanto-lhes que alguns que aqui se acham de modo nenhum experimentarão a morte antes de verem o Reino de Deus".

[[v42-9-28]]

^<<v42-9-28,28>>^ Aproximadamente oito dias depois de dizer essas coisas, Jesus tomou consigo a Pedro, João e Tiago e subiu a um monte para orar.

[[v42-9-29]]

^<<v42-9-29,29>>^ Enquanto orava, a aparência de seu rosto se transformou, e suas roupas ficaram alvas e resplandecentes como o brilho de um relâmpago.

[[v42-9-30]]

^<<v42-9-30,30>>^ Surgiram dois homens que começaram a conversar com Jesus. Eram Moisés e Elias.

[[v42-9-31]]

^<<v42-9-31,31>>^ Apareceram em glorioso esplendor, e falavam sobre a partida de Jesus, que estava para se cumprir em Jerusalém.

[[v42-9-32]]

^<<v42-9-32,32>>^ Pedro e os seus companheiros estavam dominados pelo sono; acordando subitamente, viram a glória de Jesus e os dois homens que estavam com ele.

[[v42-9-33]]

^<<v42-9-33,33>>^ Quando estes estavam se retirando, Pedro disse a Jesus: "Mestre, é bom estarmos aqui. Façamos três tendas: uma para ti, uma para Moisés e uma para Elias". ( Ele não sabia o que estava dizendo. )

[[v42-9-34]]

^<<v42-9-34,34>>^ Enquanto ele estava falando, uma nuvem apareceu e os envolveu, e eles ficaram com medo ao entrarem na nuvem.

[[v42-9-35]]

^<<v42-9-35,35>>^ Dela saiu uma voz que dizia: "Este é o meu Filho, o Escolhido; ouçam a ele! "

[[v42-9-36]]

^<<v42-9-36,36>>^ Tendo-se ouvido a voz, Jesus ficou só. Os discípulos guardaram isto somente para si; naqueles dias, não contaram a ninguém nada do que tinham visto.

[[v42-9-37]]

^<<v42-9-37,37>>^ No dia seguinte, quando desceram do monte, uma grande multidão veio ao encontro dele.

[[v42-9-38]]

^<<v42-9-38,38>>^ Um homem da multidão bradou: "Mestre, rogo-te que dês atenção ao meu filho, pois é o único que tenho.

[[v42-9-39]]

^<<v42-9-39,39>>^ Um espírito o domina; de repente ele grita; lança-o em convulsões e o faz espumar; quase nunca o abandona, e o está destruindo.

[[v42-9-40]]

^<<v42-9-40,40>>^ Roguei aos teus discípulos que o expulsassem, mas eles não conseguiram".

[[v42-9-41]]

^<<v42-9-41,41>>^ Respondeu Jesus: "Ó geração incrédula e perversa, até quando estarei com vocês e terei que suportá-los? Traga-me aqui o seu filho".

[[v42-9-42]]

^<<v42-9-42,42>>^ Quando o menino vinha vindo, o demônio o lançou por terra, em convulsão. Mas Jesus repreendeu o espírito imundo, curou o menino e o entregou de volta a seu pai.

[[v42-9-43]]

^<<v42-9-43,43>>^ E todos ficaram atônitos ante a grandeza de Deus. Estando todos maravilhados com tudo o que Jesus fazia, ele disse aos seus discípulos:

[[v42-9-44]]

^<<v42-9-44,44>>^ "Ouçam atentamente o que vou lhes dizer: o Filho do homem será traído e entregue nas mãos dos homens".

[[v42-9-45]]

^<<v42-9-45,45>>^ Mas eles não entendiam o que isso significava; era-lhes encoberto, para que não o entendessem. E tinham receio de perguntar-lhe a respeito dessa palavra.

[[v42-9-46]]

^<<v42-9-46,46>>^ Começou uma discussão entre os discípulos, acerca de qual deles seria o maior.

[[v42-9-47]]

^<<v42-9-47,47>>^ Jesus, conhecendo os seus pensamentos, tomou uma criança e a colocou em pé, a seu lado.

[[v42-9-48]]

^<<v42-9-48,48>>^ Então lhes disse: "Quem recebe esta criança em meu nome, está me recebendo; e quem me recebe, está recebendo aquele que me enviou. Pois aquele que entre vocês for o menor, este será o maior".

[[v42-9-49]]

^<<v42-9-49,49>>^ Disse João: "Mestre, vimos um homem expulsando demônios em teu nome e procuramos impedi-lo, porque ele não era um dos nossos. "

[[v42-9-50]]

^<<v42-9-50,50>>^ "Não o impeçam", disse Jesus, "pois quem não é contra vocês, é a favor de vocês".

[[v42-9-51]]

^<<v42-9-51,51>>^ Aproximando-se o tempo em que seria elevado ao céu, Jesus partiu resolutamente em direção a Jerusalém.

[[v42-9-52]]

^<<v42-9-52,52>>^ E enviou mensageiros à sua frente. Indo estes, entraram num povoado samaritano para lhe fazer os preparativos;

[[v42-9-53]]

^<<v42-9-53,53>>^ mas o povo dali não o recebeu porque se notava em seu semblante que ele ia para Jerusalém.

[[v42-9-54]]

^<<v42-9-54,54>>^ Ao verem isso, os discípulos Tiago e João perguntaram: "Senhor, queres que façamos cair fogo do céu para destruí-los? "

[[v42-9-55]]

^<<v42-9-55,55>>^ Mas Jesus, voltando-se, os repreendeu, dizendo: "Vocês não sabem de que espécie de espírito são, pois o Filho do homem não veio para destruir a vida dos homens, mas para salvá-los";

[[v42-9-56]]

^<<v42-9-56,56>>^ e foram para outro povoado.

[[v42-9-57]]

^<<v42-9-57,57>>^ Quando andavam pelo caminho, um homem lhe disse: "Eu te seguirei por onde quer que fores".

[[v42-9-58]]

^<<v42-9-58,58>>^ Jesus respondeu: "As raposas têm suas tocas e as aves do céu têm seus ninhos, mas o Filho do homem não tem onde repousar a cabeça".

[[v42-9-59]]

^<<v42-9-59,59>>^ A outro disse: "Siga-me". Mas o homem respondeu: "Senhor, deixa-me ir primeiro sepultar meu pai".

[[v42-9-60]]

^<<v42-9-60,60>>^ Jesus lhe disse: "Deixe que os mortos sepultem os seus próprios mortos; você, porém, vá e proclame o Reino de Deus".

[[v42-9-61]]

^<<v42-9-61,61>>^ Ainda outro disse: "Vou seguir-te, Senhor, mas deixa-me primeiro voltar e me despedir da minha família".

[[v42-9-62]]

^<<v42-9-62,62>>^ Jesus respondeu: "Ninguém que põe a mão no arado e olha para trás é apto para o Reino de Deus".

'''

xref:042-lucas/042-lucas-008.adoc#v42-8-0[&#60; Capítulo Anterior] | <<v42-9-0,Topo>> | xref:042-lucas/042-lucas-010.adoc#v42-10-0[Próximo Capítulo &#62;]