include::./index.adoc[]

[[v42-21-0]]
=== Lucas, 21
// nvi ?, NVI - Nova Versão Internacional

[[v42-21-1]]

^<<v42-21-1,1>>^ Jesus olhou e viu os ricos colocando suas contribuições nas caixas de ofertas.

[[v42-21-2]]

^<<v42-21-2,2>>^ Viu também uma viúva pobre colocar duas pequeninas moedas de cobre.

[[v42-21-3]]

^<<v42-21-3,3>>^ E disse: "Afirmo-lhes que esta viúva pobre colocou mais do que todos os outros.

[[v42-21-4]]

^<<v42-21-4,4>>^ Todos esses deram do que lhes sobrava; mas ela, da sua pobreza, deu tudo o que possuía para viver".

[[v42-21-5]]

^<<v42-21-5,5>>^ Alguns dos seus discípulos estavam comentando como o templo era adornado com lindas pedras e dádivas dedicadas a Deus. Mas Jesus disse:

[[v42-21-6]]

^<<v42-21-6,6>>^ "Disso que vocês estão vendo, dias virão em que não ficará pedra sobre pedra; serão todas derrubadas".

[[v42-21-7]]

^<<v42-21-7,7>>^ "Mestre", perguntaram eles, "quando acontecerão essas coisas? E qual será o sinal de que elas estão prestes a acontecer? "

[[v42-21-8]]

^<<v42-21-8,8>>^ Ele respondeu: "Cuidado para não serem enganados. Pois muitos virão em meu nome, dizendo: ‘Sou eu! ’ e ‘o tempo está próximo’. Não os sigam.

[[v42-21-9]]

^<<v42-21-9,9>>^ Quando ouvirem falar de guerras e rebeliões, não tenham medo. É necessário que primeiro aconteçam essas coisas, mas o fim não virá imediatamente".

[[v42-21-10]]

^<<v42-21-10,10>>^ Então lhes disse: "Nação se levantará contra nação, e reino contra reino.

[[v42-21-11]]

^<<v42-21-11,11>>^ Haverá grandes terremotos, fomes e pestes em vários lugares, e acontecimentos terríveis e grandes sinais provenientes do céu.

[[v42-21-12]]

^<<v42-21-12,12>>^ "Mas antes de tudo isso, prenderão e perseguirão vocês. Então os entregarão às sinagogas e prisões, e vocês serão levados à presença de reis e governadores, tudo por causa do meu nome.

[[v42-21-13]]

^<<v42-21-13,13>>^ Será para vocês uma oportunidade de dar testemunho.

[[v42-21-14]]

^<<v42-21-14,14>>^ Mas convençam-se de uma vez de que não devem preocupar-se com o que dirão para se defender.

[[v42-21-15]]

^<<v42-21-15,15>>^ Pois eu lhes darei palavras e sabedoria a que nenhum dos seus adversários será capaz de resistir ou contradizer.

[[v42-21-16]]

^<<v42-21-16,16>>^ Vocês serão traídos até por pais, irmãos, parentes e amigos, e eles entregarão alguns de vocês à morte.

[[v42-21-17]]

^<<v42-21-17,17>>^ Todos odiarão vocês por causa do meu nome.

[[v42-21-18]]

^<<v42-21-18,18>>^ Contudo, nenhum fio de cabelo da cabeça de vocês se perderá.

[[v42-21-19]]

^<<v42-21-19,19>>^ É perseverando que vocês obterão a vida.

[[v42-21-20]]

^<<v42-21-20,20>>^ "Quando virem Jerusalém rodeada de exércitos, vocês saberão que a sua devastação está próxima.

[[v42-21-21]]

^<<v42-21-21,21>>^ Então os que estiverem na Judéia fujam para os montes, os que estiverem na cidade saiam, e os que estiverem no campo não entrem na cidade.

[[v42-21-22]]

^<<v42-21-22,22>>^ Pois esses são os dias da vingança, em cumprimento de tudo o que foi escrito.

[[v42-21-23]]

^<<v42-21-23,23>>^ Como serão terríveis aqueles dias para as grávidas e para as que estiverem amamentando! Haverá grande aflição na terra e ira contra este povo.

[[v42-21-24]]

^<<v42-21-24,24>>^ Cairão pela espada e serão levados como prisioneiros para todas as nações. Jerusalém será pisada pelos gentios, até que os tempos deles se cumpram.

[[v42-21-25]]

^<<v42-21-25,25>>^ "Haverá sinais no sol, na lua e nas estrelas. Na terra, as nações se verão em angústia e perplexidade com o bramido e a agitação do mar.

[[v42-21-26]]

^<<v42-21-26,26>>^ Os homens desmaiarão de terror, apreensivos com o que estará sobrevindo ao mundo; e os poderes celestes serão abalados.

[[v42-21-27]]

^<<v42-21-27,27>>^ Então se verá o Filho do homem vindo numa nuvem com poder e grande glória.

[[v42-21-28]]

^<<v42-21-28,28>>^ Quando começarem a acontecer estas coisas, levantem-se e ergam a cabeça, porque estará próxima a redenção de vocês".

[[v42-21-29]]

^<<v42-21-29,29>>^ Ele lhes contou esta parábola: "Observem a figueira e todas as árvores.

[[v42-21-30]]

^<<v42-21-30,30>>^ Quando elas brotam, vocês mesmos percebem e sabem que o verão está próximo.

[[v42-21-31]]

^<<v42-21-31,31>>^ Assim também, quando virem estas coisas acontecendo, saibam que o Reino de Deus está próximo.

[[v42-21-32]]

^<<v42-21-32,32>>^ "Eu lhes asseguro que não passará esta geração até que todas essas coisas aconteçam.

[[v42-21-33]]

^<<v42-21-33,33>>^ O céu e a terra passarão, mas as minhas palavras jamais passarão.

[[v42-21-34]]

^<<v42-21-34,34>>^ "Tenham cuidado, para que os seus corações não fiquem carregados de libertinagem, bebedeira e ansiedades da vida, e aquele dia venha sobre vocês inesperadamente.

[[v42-21-35]]

^<<v42-21-35,35>>^ Porque ele virá sobre todos os que vivem na face de toda a terra.

[[v42-21-36]]

^<<v42-21-36,36>>^ Estejam sempre atentos e orem para que vocês possam escapar de tudo o que está para acontecer, e estar de pé diante do Filho do homem".

[[v42-21-37]]

^<<v42-21-37,37>>^ Jesus passava o dia ensinando no templo; e, ao entardecer, saía para passar a noite no monte chamado das Oliveiras.

[[v42-21-38]]

^<<v42-21-38,38>>^ Todo o povo ia de manhã cedo ouvi-lo no templo.

'''

xref:042-lucas/042-lucas-020.adoc#v42-20-0[&#60; Capítulo Anterior] | <<v42-21-0,Topo>> | xref:042-lucas/042-lucas-022.adoc#v42-22-0[Próximo Capítulo &#62;]