include::./index.adoc[]

[[v42-5-0]]
=== Lucas, 5
// nvi ?, NVI - Nova Versão Internacional

[[v42-5-1]]

^<<v42-5-1,1>>^ Certo dia Jesus estava perto do lago de Genesaré, e uma multidão o comprimia de todos os lados para ouvir a palavra de Deus.

[[v42-5-2]]

^<<v42-5-2,2>>^ Viu à beira do lago dois barcos, deixados ali pelos pescadores, que estavam lavando as suas redes.

[[v42-5-3]]

^<<v42-5-3,3>>^ Entrou num dos barcos, o que pertencia a Simão, e pediu-lhe que o afastasse um pouco da praia. Então sentou-se, e do barco ensinava o povo.

[[v42-5-4]]

^<<v42-5-4,4>>^ Tendo acabado de falar, disse a Simão: "Vá para onde as águas são mais fundas", e a todos: "Lancem as redes para a pesca".

[[v42-5-5]]

^<<v42-5-5,5>>^ Simão respondeu: "Mestre, esforçamo-nos a noite inteira e não pegamos nada. Mas, porque és tu quem está dizendo isto, vou lançar as redes".

[[v42-5-6]]

^<<v42-5-6,6>>^ Quando o fizeram, pegaram tal quantidade de peixe que as redes começaram a rasgar-se.

[[v42-5-7]]

^<<v42-5-7,7>>^ Então fizeram sinais a seus companheiros no outro barco, para que viessem ajudá-lo; e eles vieram e encheram ambos os barcos, a ponto de quase começarem a afundar.

[[v42-5-8]]

^<<v42-5-8,8>>^ Quando Simão Pedro viu isso, prostrou-se aos pés de Jesus e disse: "Afasta-te de mim, Senhor, porque sou um homem pecador! "

[[v42-5-9]]

^<<v42-5-9,9>>^ Pois ele e todos os seus companheiros estavam perplexos com a pesca que haviam feito,

[[v42-5-10]]

^<<v42-5-10,10>>^ como também Tiago e João, os filhos de Zebedeu, sócios de Simão. Então Jesus disse a Simão: "Não tenha medo; de agora em diante você será pescador de homens".

[[v42-5-11]]

^<<v42-5-11,11>>^ Eles então arrastaram seus barcos para a praia, deixaram tudo e o seguiram.

[[v42-5-12]]

^<<v42-5-12,12>>^ Estando Jesus numa das cidades, passou um homem coberto de lepra. Quando viu a Jesus, prostrou-se com o rosto em terra e rogou-lhe: "Se quiseres, podes purificar-me".

[[v42-5-13]]

^<<v42-5-13,13>>^ Jesus estendeu a mão e tocou nele, dizendo: "Quero. Seja purificado! " E imediatamente a lepra o deixou.

[[v42-5-14]]

^<<v42-5-14,14>>^ Então Jesus lhe ordenou: "Não conte isso a ninguém; mas vá mostrar-se ao sacerdote e ofereça pela sua purificação os sacrifícios que Moisés ordenou, para que sirva de testemunho".

[[v42-5-15]]

^<<v42-5-15,15>>^ Todavia, as notícias a respeito dele se espalhavam ainda mais, de forma que multidões vinham para ouvi-lo e para serem curadas de suas doenças.

[[v42-5-16]]

^<<v42-5-16,16>>^ Mas Jesus retirava-se para lugares solitários, e orava.

[[v42-5-17]]

^<<v42-5-17,17>>^ Certo dia, quando ele ensinava, estavam sentados ali fariseus e mestres da lei, procedentes de todos os povoados da Galiléia, da Judéia e de Jerusalém. E o poder do Senhor estava com ele para curar os doentes.

[[v42-5-18]]

^<<v42-5-18,18>>^ Vieram alguns homens trazendo um paralítico numa maca e tentaram fazê-lo entrar na casa, para colocá-lo diante de Jesus.

[[v42-5-19]]

^<<v42-5-19,19>>^ Não conseguindo fazer isso, por causa da multidão, subiram ao terraço e o baixaram em sua maca, através de uma abertura, até o meio da multidão, bem em frente de Jesus.

[[v42-5-20]]

^<<v42-5-20,20>>^ Vendo a fé que eles tinham, Jesus disse: "Homem, os seus pecados estão perdoados".

[[v42-5-21]]

^<<v42-5-21,21>>^ Os fariseus e os mestres da lei começaram a pensar: "Quem é esse que blasfema? Quem pode perdoar pecados, a não ser somente Deus? "

[[v42-5-22]]

^<<v42-5-22,22>>^ Jesus, sabendo o que eles estavam pensando, perguntou: "Por que vocês estão pensando assim?

[[v42-5-23]]

^<<v42-5-23,23>>^ Que é mais fácil dizer: ‘Os seus pecados estão perdoados’, ou: ‘Levante-se e ande’?

[[v42-5-24]]

^<<v42-5-24,24>>^ Mas, para que vocês saibam que o Filho do homem tem na terra autoridade para perdoar pecados" — disse ao paralítico — "eu lhe digo: levante-se, pegue a sua maca e vá para casa".

[[v42-5-25]]

^<<v42-5-25,25>>^ Imediatamente ele se levantou na frente deles, pegou a maca em que estivera deitado e foi para casa louvando a Deus.

[[v42-5-26]]

^<<v42-5-26,26>>^ Todos ficaram atônitos e glorificavam a Deus, e, cheios de temor, diziam: "Hoje vimos coisas extraordinárias! "

[[v42-5-27]]

^<<v42-5-27,27>>^ Depois disso, Jesus saiu e viu um publicano chamado Levi, sentado na coletoria, e disse-lhe: "Siga-me".

[[v42-5-28]]

^<<v42-5-28,28>>^ Levi levantou-se, deixou tudo e o seguiu.

[[v42-5-29]]

^<<v42-5-29,29>>^ Então Levi ofereceu um grande banquete a Jesus em sua casa. Havia muita gente comendo com eles: publicanos e outras pessoas.

[[v42-5-30]]

^<<v42-5-30,30>>^ Mas os fariseus e aqueles mestres da lei que eram da mesma facção queixaram-se aos discípulos de Jesus: "Por que vocês comem e bebem com publicanos e ‘pecadores’? "

[[v42-5-31]]

^<<v42-5-31,31>>^ Jesus lhes respondeu: "Não são os que têm saúde que precisam de médico, mas sim os doentes.

[[v42-5-32]]

^<<v42-5-32,32>>^ Eu não vim chamar justos, mas pecadores ao arrependimento".

[[v42-5-33]]

^<<v42-5-33,33>>^ E eles lhe disseram: "Os discípulos de João jejuam e oram freqüentemente, bem como os discípulos dos fariseus; mas os teus vivem comendo e bebendo".

[[v42-5-34]]

^<<v42-5-34,34>>^ Jesus respondeu: "Podem vocês fazer os convidados do noivo jejuar enquanto o noivo está com eles?

[[v42-5-35]]

^<<v42-5-35,35>>^ Mas virão dias quando o noivo lhes será tirado; naqueles dias jejuarão".

[[v42-5-36]]

^<<v42-5-36,36>>^ Então lhes contou esta parábola: "Ninguém tira remendo de roupa nova e o costura em roupa velha; se o fizer, estragará a roupa nova, além do que o remendo da nova não se ajustará à velha.

[[v42-5-37]]

^<<v42-5-37,37>>^ E ninguém põe vinho novo em vasilhas de couro velhas; se o fizer, o vinho novo rebentará as vasilhas, se derramará, e as vasilhas se estragarão.

[[v42-5-38]]

^<<v42-5-38,38>>^ Pelo contrário, vinho novo deve ser posto em vasilhas de couro novas.

[[v42-5-39]]

^<<v42-5-39,39>>^ E ninguém, depois de beber o vinho velho, prefere o novo, pois diz: ‘O vinho velho é melhor! ’ "

'''

xref:042-lucas/042-lucas-004.adoc#v42-4-0[&#60; Capítulo Anterior] | <<v42-5-0,Topo>> | xref:042-lucas/042-lucas-006.adoc#v42-6-0[Próximo Capítulo &#62;]