include::./index.adoc[]

[[v42-12-0]]
=== Lucas, 12
// nvi ?, NVI - Nova Versão Internacional

[[v42-12-1]]

^<<v42-12-1,1>>^ Nesse meio tempo, tendo-se juntado uma multidão de milhares de pessoas, a ponto de se atropelarem umas às outras, Jesus começou a falar primeiramente aos seus discípulos, dizendo: "Tenham cuidado com o fermento dos fariseus, que é a hipocrisia.

[[v42-12-2]]

^<<v42-12-2,2>>^ Não há nada escondido que não venha a ser descoberto, ou oculto que não venha a ser conhecido.

[[v42-12-3]]

^<<v42-12-3,3>>^ O que vocês disseram nas trevas será ouvido à luz do dia, e o que vocês sussurraram aos ouvidos dentro de casa, será proclamado dos telhados.

[[v42-12-4]]

^<<v42-12-4,4>>^ "Eu lhes digo, meus amigos: não tenham medo dos que matam o corpo e depois nada mais podem fazer.

[[v42-12-5]]

^<<v42-12-5,5>>^ Mas eu lhes mostrarei a quem vocês devem temer: temam aquele que, depois de matar o corpo, tem poder para lançar no inferno. Sim, eu lhes digo, esse vocês devem temer.

[[v42-12-6]]

^<<v42-12-6,6>>^ Não se vendem cinco pardais por duas moedinhas? Contudo, nenhum deles é esquecido por Deus.

[[v42-12-7]]

^<<v42-12-7,7>>^ Até os cabelos da cabeça de vocês estão todos contados. Não tenham medo; vocês valem mais do que muitos pardais!

[[v42-12-8]]

^<<v42-12-8,8>>^ "Eu lhes digo: quem me confessar diante dos homens, também o Filho do homem o confessará diante dos anjos de Deus.

[[v42-12-9]]

^<<v42-12-9,9>>^ Mas aquele que me negar diante dos homens será negado diante dos anjos de Deus.

[[v42-12-10]]

^<<v42-12-10,10>>^ Todo aquele que disser uma palavra contra o Filho do homem será perdoado, mas quem blasfemar contra o Espírito Santo não será perdoado.

[[v42-12-11]]

^<<v42-12-11,11>>^ "Quando vocês forem levados às sinagogas e diante dos governantes e das autoridades, não se preocupem com a forma pela qual se defenderão, ou com o que dirão,

[[v42-12-12]]

^<<v42-12-12,12>>^ pois naquela hora o Espírito Santo lhes ensinará o que devem dizer".

[[v42-12-13]]

^<<v42-12-13,13>>^ Alguém da multidão lhe disse: "Mestre, dize a meu irmão que divida a herança comigo".

[[v42-12-14]]

^<<v42-12-14,14>>^ Respondeu Jesus: "Homem, quem me designou juiz ou árbitro entre vocês? "

[[v42-12-15]]

^<<v42-12-15,15>>^ Então lhes disse: "Cuidado! Fiquem de sobreaviso contra todo tipo de ganância; a vida de um homem não consiste na quantidade dos seus bens".

[[v42-12-16]]

^<<v42-12-16,16>>^ Então lhes contou esta parábola: "A terra de certo homem rico produziu muito bem.

[[v42-12-17]]

^<<v42-12-17,17>>^ Ele pensou consigo mesmo: ‘O que vou fazer? Não tenho onde armazenar minha colheita’.

[[v42-12-18]]

^<<v42-12-18,18>>^ "Então disse: ‘Já sei o que vou fazer. Vou derrubar os meus celeiros e construir outros maiores, e ali guardarei toda a minha safra e todos os meus bens.

[[v42-12-19]]

^<<v42-12-19,19>>^ E direi a mim mesmo: Você tem grande quantidade de bens, armazenados para muitos anos. Descanse, coma, beba e alegre-se’.

[[v42-12-20]]

^<<v42-12-20,20>>^ "Contudo, Deus lhe disse: ‘Insensato! Esta mesma noite a sua vida lhe será exigida. Então, quem ficará com o que você preparou? ’

[[v42-12-21]]

^<<v42-12-21,21>>^ "Assim acontece com quem guarda para si riquezas, mas não é rico para com Deus".

[[v42-12-22]]

^<<v42-12-22,22>>^ Dirigindo-se aos seus discípulos, Jesus acrescentou: "Portanto eu lhes digo: não se preocupem com suas próprias vidas, quanto ao que comer; nem com seus próprios corpos, quanto ao que vestir.

[[v42-12-23]]

^<<v42-12-23,23>>^ A vida é mais importante do que a comida, e o corpo, mais do que as roupas.

[[v42-12-24]]

^<<v42-12-24,24>>^ Observem os corvos: não semeiam nem colhem, não têm armazéns nem celeiros; contudo, Deus os alimenta. E vocês têm muito mais valor do que as aves!

[[v42-12-25]]

^<<v42-12-25,25>>^ Quem de vocês, por mais que se preocupe, pode acrescentar uma hora que seja à sua vida?

[[v42-12-26]]

^<<v42-12-26,26>>^ Visto que vocês não podem sequer fazer uma coisa tão pequena, por que se preocupar com o restante?

[[v42-12-27]]

^<<v42-12-27,27>>^ "Observem como crescem os lírios. Eles não trabalham nem tecem. Contudo, eu lhes digo que nem Salomão, em todo o seu esplendor, vestiu-se como um deles.

[[v42-12-28]]

^<<v42-12-28,28>>^ Se Deus veste assim a erva do campo, que hoje existe e amanhã é lançada ao fogo, quanto mais vestirá vocês, homens de pequena fé!

[[v42-12-29]]

^<<v42-12-29,29>>^ Não busquem ansiosamente o que hão de comer ou beber; não se preocupem com isso.

[[v42-12-30]]

^<<v42-12-30,30>>^ Pois o mundo pagão é que corre atrás dessas coisas; mas o Pai sabe que vocês precisam delas.

[[v42-12-31]]

^<<v42-12-31,31>>^ Busquem, pois, o Reino de Deus, e essas coisas lhes serão acrescentadas.

[[v42-12-32]]

^<<v42-12-32,32>>^ "Não tenham medo, pequeno rebanho, pois foi do agrado do Pai dar-lhes o Reino.

[[v42-12-33]]

^<<v42-12-33,33>>^ Vendam o que têm e dêem esmolas. Façam para vocês bolsas que não se gastem com o tempo, um tesouro nos céus que não se acabe, onde ladrão algum chega perto e nenhuma traça destrói.

[[v42-12-34]]

^<<v42-12-34,34>>^ Pois onde estiver o seu tesouro, ali também estará o seu coração".

[[v42-12-35]]

^<<v42-12-35,35>>^ "Estejam prontos para servir, e conservem acesas as suas candeias,

[[v42-12-36]]

^<<v42-12-36,36>>^ como aqueles que esperam seu senhor voltar de um banquete de casamento; para que, quando ele chegar e bater, possam abrir-lhe a porta imediatamente.

[[v42-12-37]]

^<<v42-12-37,37>>^ Felizes os servos cujo senhor os encontrar vigiando, quando voltar. Eu lhes afirmo que ele se vestirá para servir, fará que se reclinem à mesa, e virá servi-los.

[[v42-12-38]]

^<<v42-12-38,38>>^ Mesmo que ele chegue de noite ou de madrugada, felizes os servos que o senhor encontrar preparados.

[[v42-12-39]]

^<<v42-12-39,39>>^ Entendam, porém, isto: se o dono da casa soubesse a que hora viria o ladrão, não permitiria que a sua casa fosse arrombada.

[[v42-12-40]]

^<<v42-12-40,40>>^ Estejam também vocês preparados, porque o Filho do homem virá numa hora em que não o esperam".

[[v42-12-41]]

^<<v42-12-41,41>>^ Pedro perguntou: "Senhor, estás contando esta parábola para nós ou para todos? "

[[v42-12-42]]

^<<v42-12-42,42>>^ O Senhor respondeu: "Quem é, pois, o administrador fiel e sensato, a quem seu senhor encarrega dos seus servos, para lhes dar sua porção de alimento no tempo devido?

[[v42-12-43]]

^<<v42-12-43,43>>^ Feliz o servo a quem o seu senhor encontrar fazendo assim quando voltar.

[[v42-12-44]]

^<<v42-12-44,44>>^ Garanto-lhes que ele o encarregará de todos os seus bens.

[[v42-12-45]]

^<<v42-12-45,45>>^ Mas suponham que esse servo diga a si mesmo: ‘Meu senhor se demora a voltar’, e então comece a bater nos servos e nas servas, a comer, a beber e a embriagar-se.

[[v42-12-46]]

^<<v42-12-46,46>>^ O senhor daquele servo virá num dia em que ele não o espera e numa hora que não sabe, e o punirá severamente e lhe dará um lugar com os infiéis.

[[v42-12-47]]

^<<v42-12-47,47>>^ "Aquele servo que conhece a vontade de seu senhor e não prepara o que ele deseja, nem o realiza, receberá muitos açoites.

[[v42-12-48]]

^<<v42-12-48,48>>^ Mas aquele que não a conhece e pratica coisas merecedoras de castigo, receberá poucos açoites. A quem muito foi dado, muito será exigido; e a quem muito foi confiado, muito mais será pedido".

[[v42-12-49]]

^<<v42-12-49,49>>^ "Vim trazer fogo à terra, e como gostaria que já estivesse aceso!

[[v42-12-50]]

^<<v42-12-50,50>>^ Mas tenho que passar por um batismo, e como estou angustiado até que ele se realize!

[[v42-12-51]]

^<<v42-12-51,51>>^ Vocês pensam que vim trazer paz à terra? Não, eu lhes digo. Pelo contrário, vim trazer divisão!

[[v42-12-52]]

^<<v42-12-52,52>>^ De agora em diante haverá cinco numa família divididos uns contra os outros: três contra dois e dois contra três.

[[v42-12-53]]

^<<v42-12-53,53>>^ Estarão divididos pai contra filho e filho contra pai, mãe contra filha e filha contra mãe, sogra contra nora e nora contra sogra".

[[v42-12-54]]

^<<v42-12-54,54>>^ Dizia ele à multidão: "Quando vocês vêem uma nuvem se levantando no ocidente, logo dizem: ‘Vai chover’, e assim acontece.

[[v42-12-55]]

^<<v42-12-55,55>>^ E quando sopra o vento sul, vocês dizem: ‘Vai fazer calor’, e assim ocorre.

[[v42-12-56]]

^<<v42-12-56,56>>^ Hipócritas! Vocês sabem interpretar o aspecto da terra e do céu. Como não sabem interpretar o tempo presente?

[[v42-12-57]]

^<<v42-12-57,57>>^ "Por que vocês não julgam por si mesmos o que é justo?

[[v42-12-58]]

^<<v42-12-58,58>>^ Quando algum de vocês estiver indo com seu adversário para o magistrado, faça tudo para se reconciliar com ele no caminho; para que ele não o arraste ao juiz, o juiz o entregue ao oficial de justiça, e o oficial de justiça o jogue na prisão.

[[v42-12-59]]

^<<v42-12-59,59>>^ Eu lhe digo que você não sairá de lá enquanto não pagar o último centavo".

'''

xref:042-lucas/042-lucas-011.adoc#v42-11-0[&#60; Capítulo Anterior] | <<v42-12-0,Topo>> | xref:042-lucas/042-lucas-013.adoc#v42-13-0[Próximo Capítulo &#62;]