include::./index.adoc[]

[[v42-13-0]]
=== Lucas, 13
// nvi ?, NVI - Nova Versão Internacional

[[v42-13-1]]

^<<v42-13-1,1>>^ Naquela ocasião, alguns dos que estavam presentes contaram a Jesus que Pilatos misturara o sangue de alguns galileus com os sacrifícios deles.

[[v42-13-2]]

^<<v42-13-2,2>>^ Jesus respondeu: "Vocês pensam que esses galileus eram mais pecadores que todos os outros, por terem sofrido dessa maneira?

[[v42-13-3]]

^<<v42-13-3,3>>^ Eu lhes digo que não! Mas se não se arrependerem, todos vocês também perecerão.

[[v42-13-4]]

^<<v42-13-4,4>>^ Ou vocês pensam que aqueles dezoito que morreram, quando caiu sobre eles a torre de Siloé, eram mais culpados do que todos os outros habitantes de Jerusalém?

[[v42-13-5]]

^<<v42-13-5,5>>^ Eu lhes digo que não! Mas se não se arrependerem, todos vocês também perecerão".

[[v42-13-6]]

^<<v42-13-6,6>>^ Então contou esta parábola: "Um homem tinha uma figueira plantada em sua vinha. Foi procurar fruto nela, e não achou nenhum.

[[v42-13-7]]

^<<v42-13-7,7>>^ Por isso disse ao que cuidava da vinha: ‘Já faz três anos que venho procurar fruto nesta figueira e não acho. Corte-a! Por que deixá-la inutilizar a terra? ’

[[v42-13-8]]

^<<v42-13-8,8>>^ "Respondeu o homem: ‘Senhor, deixe-a por mais um ano, e eu cavarei ao redor dela e a adubarei.

[[v42-13-9]]

^<<v42-13-9,9>>^ Se der fruto no ano que vem, muito bem! Se não, corte-a’ ".

[[v42-13-10]]

^<<v42-13-10,10>>^ Certo sábado Jesus estava ensinando numa das sinagogas,

[[v42-13-11]]

^<<v42-13-11,11>>^ e ali estava uma mulher que tinha um espírito que a mantinha doente havia dezoito anos. Ela andava encurvada e de forma alguma podia endireitar-se.

[[v42-13-12]]

^<<v42-13-12,12>>^ Ao vê-la, Jesus chamou-a à frente e lhe disse: "Mulher, você está livre da sua doença".

[[v42-13-13]]

^<<v42-13-13,13>>^ Então lhe impôs as mãos; e imediatamente ela se endireitou, e louvava a Deus.

[[v42-13-14]]

^<<v42-13-14,14>>^ Indignado porque Jesus havia curado no sábado, o dirigente da sinagoga disse ao povo: "Há seis dias em que se deve trabalhar. Venham para ser curados nesses dias, e não no sábado".

[[v42-13-15]]

^<<v42-13-15,15>>^ O Senhor lhe respondeu: "Hipócritas! Cada um de vocês não desamarra no sábado o seu boi ou jumento do estábulo e o leva dali para dar-lhe água?

[[v42-13-16]]

^<<v42-13-16,16>>^ Então, esta mulher, uma filha de Abraão a quem Satanás mantinha presa por dezoito longos anos, não deveria no dia de sábado ser libertada daquilo que a prendia? "

[[v42-13-17]]

^<<v42-13-17,17>>^ Tendo dito isso, todos os seus oponentes ficaram envergonhados, mas o povo se alegrava com todas as maravilhas que ele estava fazendo.

[[v42-13-18]]

^<<v42-13-18,18>>^ Então Jesus perguntou: "Com que se parece o Reino de Deus? Com que o compararei?

[[v42-13-19]]

^<<v42-13-19,19>>^ É como um grão de mostarda que um homem semeou em sua horta. Ele cresceu e se tornou uma árvore, e as aves do céu se fizaram ninhos em seus ramos".

[[v42-13-20]]

^<<v42-13-20,20>>^ Mais uma vez ele perguntou: "A que compararei o Reino de Deus?

[[v42-13-21]]

^<<v42-13-21,21>>^ É como o fermento que uma mulher misturou com uma grande quantidade de farinha, e toda a massa ficou fermentada".

[[v42-13-22]]

^<<v42-13-22,22>>^ Depois Jesus foi pelas cidades e povoados e ensinava, prosseguindo em direção a Jerusalém.

[[v42-13-23]]

^<<v42-13-23,23>>^ Alguém lhe perguntou: "Senhor, serão poucos os salvos? " Ele lhes disse:

[[v42-13-24]]

^<<v42-13-24,24>>^ "Esforcem-se para entrar pela porta estreita, porque eu lhes digo que muitos tentarão entrar e não conseguirão.

[[v42-13-25]]

^<<v42-13-25,25>>^ Quando o dono da casa se levantar e fechar a porta, vocês ficarão do lado de fora, batendo e pedindo: ‘Senhor, abre-nos a porta’. "Ele, porém, responderá: ‘Não os conheço, nem sei de onde são vocês’.

[[v42-13-26]]

^<<v42-13-26,26>>^ "Então vocês dirão: ‘Comemos e bebemos contigo, e ensinaste em nossas ruas’.

[[v42-13-27]]

^<<v42-13-27,27>>^ "Mas ele responderá: ‘Não os conheço, nem sei de onde são vocês. Afastem-se de mim, todos vocês, que praticam o mal! ’

[[v42-13-28]]

^<<v42-13-28,28>>^ "Ali haverá choro e ranger de dentes, quando vocês virem Abraão, Isaque e Jacó e todos os profetas no Reino de Deus, mas vocês excluídos.

[[v42-13-29]]

^<<v42-13-29,29>>^ Pessoas virão do oriente e do ocidente, do norte e do sul, e ocuparão os seus lugares à mesa no Reino de Deus.

[[v42-13-30]]

^<<v42-13-30,30>>^ De fato, há últimos que serão primeiros, e primeiros que serão últimos".

[[v42-13-31]]

^<<v42-13-31,31>>^ Naquela mesma hora alguns fariseus aproximaram-se de Jesus e lhe disseram: "Saia e vá embora daqui, pois Herodes quer matá-lo".

[[v42-13-32]]

^<<v42-13-32,32>>^ Ele respondeu: "Vão dizer àquela raposa: ‘Expulsarei demônios e curarei o povo hoje e amanhã, e no terceiro dia estarei pronto’.

[[v42-13-33]]

^<<v42-13-33,33>>^ Mas, preciso prosseguir hoje, amanhã e depois de amanhã, pois certamente nenhum profeta deve morrer fora de Jerusalém!

[[v42-13-34]]

^<<v42-13-34,34>>^ "Jerusalém, Jerusalém, você, que mata os profetas e apedrejas os que lhe são enviados! Quantas vezes eu quis reunir os seus filhos, como a galinha reúne os seus pintinhos debaixo das suas asas, mas vocês não quiseram!

[[v42-13-35]]

^<<v42-13-35,35>>^ Eis que a casa de vocês ficará deserta. Eu lhes digo que vocês não me verão mais até que digam: ‘Bendito o que vem em nome do Senhor’".

'''

xref:042-lucas/042-lucas-012.adoc#v42-12-0[&#60; Capítulo Anterior] | <<v42-13-0,Topo>> | xref:042-lucas/042-lucas-014.adoc#v42-14-0[Próximo Capítulo &#62;]