include::./index.adoc[]

[[v42-23-0]]
=== Lucas, 23
// nvi ?, NVI - Nova Versão Internacional

[[v42-23-1]]

^<<v42-23-1,1>>^ Então toda a assembléia levantou-se e o levou a Pilatos.

[[v42-23-2]]

^<<v42-23-2,2>>^ E começaram a acusá-lo, dizendo: "Encontramos este homem subvertendo a nossa nação. Ele proíbe o pagamento de imposto a César e se declara ele próprio o Cristo, um rei".

[[v42-23-3]]

^<<v42-23-3,3>>^ Pilatos perguntou a Jesus: "Você é o rei dos judeus? " "Tu o dizes", respondeu Jesus.

[[v42-23-4]]

^<<v42-23-4,4>>^ Então Pilatos disse aos chefes dos sacerdotes e à multidão: "Não encontro motivo para acusar este homem".

[[v42-23-5]]

^<<v42-23-5,5>>^ Mas eles insistiam: "Ele está subvertendo o povo em toda a Judéia com os seus ensinamentos. Começou na Galiléia e chegou até aqui".

[[v42-23-6]]

^<<v42-23-6,6>>^ Ouvindo isso, Pilatos perguntou se Jesus era galileu.

[[v42-23-7]]

^<<v42-23-7,7>>^ Quando ficou sabendo que ele era da jurisdição de Herodes, enviou-o a Herodes, que também estava em Jerusalém naqueles dias.

[[v42-23-8]]

^<<v42-23-8,8>>^ Quando Herodes viu Jesus, ficou muito alegre, porque havia muito tempo queria vê-lo. Pelo que ouvira falar dele, esperava vê-lo realizar algum milagre.

[[v42-23-9]]

^<<v42-23-9,9>>^ Interrogou-o com muitas perguntas, mas Jesus não lhe deu resposta.

[[v42-23-10]]

^<<v42-23-10,10>>^ Os chefes dos sacerdotes e os mestres da lei estavam ali, acusando-o com veemência.

[[v42-23-11]]

^<<v42-23-11,11>>^ Então Herodes e os seus soldados ridicularizaram-no e zombaram dele. Vestindo-o com um manto esplêndido, mandaram-no de volta a Pilatos.

[[v42-23-12]]

^<<v42-23-12,12>>^ Herodes e Pilatos, que até ali eram inimigos, naquele dia tornaram-se amigos.

[[v42-23-13]]

^<<v42-23-13,13>>^ Pilatos reuniu os chefes dos sacerdotes, as autoridades e o povo,

[[v42-23-14]]

^<<v42-23-14,14>>^ dizendo-lhes: "Vocês me trouxeram este homem como alguém que estava incitando o povo à rebelião. Eu o examinei na presença de vocês e não achei nenhuma base para as acusações que fazem contra ele.

[[v42-23-15]]

^<<v42-23-15,15>>^ Nem Herodes, pois ele o mandou de volta para nós. Como podem ver, ele nada fez que mereça a morte.

[[v42-23-16]]

^<<v42-23-16,16>>^ Portanto, eu o castigarei e depois o soltarei.

[[v42-23-17]]

^<<v42-23-17,17>>^ Ele era obrigado a soltar-lhes um preso durante a festa".

[[v42-23-18]]

^<<v42-23-18,18>>^ A uma só voz eles gritaram: "Acaba com ele! Solta-nos Barrabás! "

[[v42-23-19]]

^<<v42-23-19,19>>^ ( Barrabás havia sido lançado na prisão por causa de uma insurreição na cidade e por assassinato. )

[[v42-23-20]]

^<<v42-23-20,20>>^ Desejando soltar a Jesus, Pilatos dirigiu-se a eles novamente.

[[v42-23-21]]

^<<v42-23-21,21>>^ Mas eles continuaram gritando: "Crucifica-o! Crucifica-o! "

[[v42-23-22]]

^<<v42-23-22,22>>^ Pela terceira vez ele lhes falou: "Por quê? Que crime este homem cometeu? Não encontrei nele nada digno de morte. Vou mandar castigá-lo e depois o soltarei".

[[v42-23-23]]

^<<v42-23-23,23>>^ Eles, porém, pediam insistentemente, com fortes gritos, que ele fosse crucificado; e a gritaria prevaleceu.

[[v42-23-24]]

^<<v42-23-24,24>>^ Então Pilatos decidiu fazer a vontade deles.

[[v42-23-25]]

^<<v42-23-25,25>>^ Libertou o homem que havia sido lançado na prisão por insurreição e assassinato, aquele que eles haviam pedido, e entregou Jesus à vontade deles.

[[v42-23-26]]

^<<v42-23-26,26>>^ Enquanto o levavam, agarraram Simão de Cirene, que estava chegando do campo, e lhe colocaram a cruz às costas, fazendo-o carregá-la atrás de Jesus.

[[v42-23-27]]

^<<v42-23-27,27>>^ Um grande número de pessoas o seguia, inclusive mulheres que lamentavam e choravam por ele.

[[v42-23-28]]

^<<v42-23-28,28>>^ Jesus voltou-se e disse-lhes: "Filhas de Jerusalém, não chorem por mim; chorem por vocês mesmas e por seus filhos!

[[v42-23-29]]

^<<v42-23-29,29>>^ Pois chegará a hora em que vocês dirão: ‘Felizes as estéreis, os ventres que nunca geraram e os seios que nunca amamentaram! ’

[[v42-23-30]]

^<<v42-23-30,30>>^ "Então dirão às montanhas: ‘Caiam sobre nós! ’ e às colinas: ‘Cubram-nos! ’

[[v42-23-31]]

^<<v42-23-31,31>>^ Pois, se fazem isto com a árvore verde, o que acontecerá quando ela estiver seca? "

[[v42-23-32]]

^<<v42-23-32,32>>^ Dois outros homens, ambos criminosos, também foram levados com ele, para serem executados.

[[v42-23-33]]

^<<v42-23-33,33>>^ Quando chegaram ao lugar chamado Caveira, ali o crucificaram com os criminosos, um à sua direita e o outro à sua esquerda.

[[v42-23-34]]

^<<v42-23-34,34>>^ Jesus disse: "Pai, perdoa-lhes, pois não sabem o que estão fazendo". Então eles dividiram as roupas dele, tirando sortes.

[[v42-23-35]]

^<<v42-23-35,35>>^ O povo ficou observando, e as autoridades o ridicularizavam. "Salvou os outros", diziam; "salve-se a si mesmo, se é o Cristo de Deus, o Escolhido".

[[v42-23-36]]

^<<v42-23-36,36>>^ Os soldados, aproximando-se, também zombavam dele. Oferecendo-lhe vinagre,

[[v42-23-37]]

^<<v42-23-37,37>>^ diziam: "Se você é o rei dos judeus, salve-se a si mesmo".

[[v42-23-38]]

^<<v42-23-38,38>>^ Havia uma inscrição acima dele, que dizia: ESTE É O REI DOS JUDEUS.

[[v42-23-39]]

^<<v42-23-39,39>>^ Um dos criminosos que ali estavam dependurados lançava-lhe insultos: "Você não é o Cristo? Salve-se a si mesmo e a nós! "

[[v42-23-40]]

^<<v42-23-40,40>>^ Mas o outro criminoso o repreendeu, dizendo: "Você não teme a Deus, nem estando sob a mesma sentença?

[[v42-23-41]]

^<<v42-23-41,41>>^ Nós estamos sendo punidos com justiça, porque estamos recebendo o que os nossos atos merecem. Mas este homem não cometeu nenhum mal".

[[v42-23-42]]

^<<v42-23-42,42>>^ Então ele disse: "Jesus, lembra-te de mim quando entrares no teu Reino".

[[v42-23-43]]

^<<v42-23-43,43>>^ Jesus lhe respondeu: "Eu lhe garanto: Hoje você estará comigo no paraíso".

[[v42-23-44]]

^<<v42-23-44,44>>^ Já era quase meio dia, e trevas cobriram toda a terra até às três horas da tarde;

[[v42-23-45]]

^<<v42-23-45,45>>^ o sol deixara de brilhar. E o véu do santuário rasgou-se ao meio.

[[v42-23-46]]

^<<v42-23-46,46>>^ Jesus bradou em alta voz: "Pai, nas tuas mãos entrego o meu espírito". Tendo dito isso, expirou.

[[v42-23-47]]

^<<v42-23-47,47>>^ O centurião, vendo o que havia acontecido, louvou a Deus, dizendo: "Certamente este homem era justo".

[[v42-23-48]]

^<<v42-23-48,48>>^ E todo o povo que se havia juntado para presenciar o que estava acontecendo, ao ver isso, começou a bater no peito e a afastar-se.

[[v42-23-49]]

^<<v42-23-49,49>>^ Mas todos os que o conheciam, inclusive as mulheres que o haviam seguido desde a Galiléia, ficaram de longe, observando essas coisas.

[[v42-23-50]]

^<<v42-23-50,50>>^ Havia um homem chamado José, membro do Conselho, homem bom e justo,

[[v42-23-51]]

^<<v42-23-51,51>>^ que não tinha consentido na decisão e no procedimento dos outros. Ele era da cidade de Arimatéia, na Judéia, e esperava o Reino de Deus.

[[v42-23-52]]

^<<v42-23-52,52>>^ Dirigindo-se a Pilatos, pediu o corpo de Jesus.

[[v42-23-53]]

^<<v42-23-53,53>>^ Então, desceu-o, envolveu-o num lençol de linho e o colocou num sepulcro cavado na rocha, no qual ninguém ainda fora colocado.

[[v42-23-54]]

^<<v42-23-54,54>>^ Era o Dia da Preparação, e estava para começar o sábado.

[[v42-23-55]]

^<<v42-23-55,55>>^ As mulheres que haviam acompanhado Jesus desde a Galiléia, seguiram José e viram o sepulcro, e como o corpo de Jesus fora colocado nele.

[[v42-23-56]]

^<<v42-23-56,56>>^ Então, foram para casa e prepararam perfumes e especiarias aromáticas. E descansaram no sábado, em obediência ao mandamento.

'''

xref:042-lucas/042-lucas-022.adoc#v42-22-0[&#60; Capítulo Anterior] | <<v42-23-0,Topo>> | xref:042-lucas/042-lucas-024.adoc#v42-24-0[Próximo Capítulo &#62;]