include::./index.adoc[]

[[v42-1-0]]
=== Lucas, 1
// nvi ?, NVI - Nova Versão Internacional

[[v42-1-1]]

^<<v42-1-1,1>>^ Muitos já se dedicaram a elaborar um relato dos fatos que se cumpriram entre nós,

[[v42-1-2]]

^<<v42-1-2,2>>^ conforme nos foram transmitidos por aqueles que desde o início foram testemunhas oculares e servos da palavra.

[[v42-1-3]]

^<<v42-1-3,3>>^ Eu mesmo investiguei tudo cuidadosamente, desde o começo, e decidi escrever-te um relato ordenado, ó excelentíssimo Teófilo,

[[v42-1-4]]

^<<v42-1-4,4>>^ para que tenhas a certeza das coisas que te foram ensinadas.

[[v42-1-5]]

^<<v42-1-5,5>>^ No tempo de Herodes, rei da Judéia, havia um sacerdote chamado Zacarias, que pertencia ao grupo sacerdotal de Abias; Isabel, sua mulher, também era descendente de Arão.

[[v42-1-6]]

^<<v42-1-6,6>>^ Ambos eram justos aos olhos de Deus, obedecendo de modo irrepreensível a todos os mandamentos e preceitos do Senhor.

[[v42-1-7]]

^<<v42-1-7,7>>^ Mas eles não tinham filhos, porque Isabel era estéril; e ambos eram de idade avançada.

[[v42-1-8]]

^<<v42-1-8,8>>^ Certa vez, estando de serviço o seu grupo, Zacarias estava servindo como sacerdote diante de Deus.

[[v42-1-9]]

^<<v42-1-9,9>>^ Ele foi escolhido por sorteio, de acordo com o costume do sacerdócio, para entrar no santuário do Senhor e oferecer incenso.

[[v42-1-10]]

^<<v42-1-10,10>>^ Chegando a hora de oferecer incenso, o povo todo estava orando do lado de fora.

[[v42-1-11]]

^<<v42-1-11,11>>^ Então um anjo do Senhor apareceu a Zacarias, à direita do altar do incenso.

[[v42-1-12]]

^<<v42-1-12,12>>^ Quando Zacarias o viu, perturbou-se e foi dominado pelo medo.

[[v42-1-13]]

^<<v42-1-13,13>>^ Mas o anjo lhe disse: "Não tenha medo, Zacarias; sua oração foi ouvida. Isabel, sua mulher, lhe dará um filho, e você lhe dará o nome de João.

[[v42-1-14]]

^<<v42-1-14,14>>^ Ele será motivo de prazer e de alegria para você, e muitos se alegrarão por causa do nascimento dele,

[[v42-1-15]]

^<<v42-1-15,15>>^ pois será grande aos olhos do Senhor. Ele nunca tomará vinho nem bebida fermentada, e será cheio do Espírito Santo desde antes do seu nascimento.

[[v42-1-16]]

^<<v42-1-16,16>>^ Fará retornar muitos dentre o povo de Israel ao Senhor, o seu Deus.

[[v42-1-17]]

^<<v42-1-17,17>>^ E irá adiante do Senhor, no espírito e no poder de Elias, para fazer voltar o coração dos pais a seus filhos e os desobedientes à sabedoria dos justos, para deixar um povo preparado para o Senhor".

[[v42-1-18]]

^<<v42-1-18,18>>^ Zacarias perguntou ao anjo: "Como posso ter certeza disso? Sou velho, e minha mulher é de idade avançada".

[[v42-1-19]]

^<<v42-1-19,19>>^ O anjo respondeu: "Sou Gabriel, o que está sempre na presença de Deus. Fui enviado para lhe transmitir estas boas novas.

[[v42-1-20]]

^<<v42-1-20,20>>^ Agora você ficará mudo. Não poderá falar até o dia em que isso acontecer, porque não acreditou em minhas palavras, que se cumprirão no tempo oportuno".

[[v42-1-21]]

^<<v42-1-21,21>>^ Enquanto isso, o povo esperava por Zacarias, estranhando sua demora no santuário.

[[v42-1-22]]

^<<v42-1-22,22>>^ Quando saiu, não conseguia falar nada; o povo percebeu então que ele tivera uma visão no santuário. Zacarias fazia sinais para eles, mas permanecia mudo.

[[v42-1-23]]

^<<v42-1-23,23>>^ Quando se completou seu período de serviço, ele voltou para casa.

[[v42-1-24]]

^<<v42-1-24,24>>^ Depois disso, Isabel, sua mulher, engravidou e durante cinco meses não saiu de casa.

[[v42-1-25]]

^<<v42-1-25,25>>^ E ela dizia: "Isto é obra do Senhor fez! Agora ele olhou para mim com favor, para desfazer a minha humilhação perante o povo. "

[[v42-1-26]]

^<<v42-1-26,26>>^ No sexto mês Deus enviou o anjo Gabriel a Nazaré, cidade da Galiléia,

[[v42-1-27]]

^<<v42-1-27,27>>^ a uma virgem prometida em casamento a certo homem chamado José, descendente de Davi. O nome da virgem era Maria.

[[v42-1-28]]

^<<v42-1-28,28>>^ O anjo, aproximando-se dela, disse: "Alegre-se, agraciada! O Senhor está com você! "

[[v42-1-29]]

^<<v42-1-29,29>>^ Maria ficou perturbada com essas palavras, pensando no que poderia significar esta saudação.

[[v42-1-30]]

^<<v42-1-30,30>>^ Mas o anjo lhe disse: "Não tenha medo, Maria; você foi agraciada por Deus!

[[v42-1-31]]

^<<v42-1-31,31>>^ Você ficará grávida e dará à luz um filho, e lhe porá o nome de Jesus.

[[v42-1-32]]

^<<v42-1-32,32>>^ Ele será grande e será chamado Filho do Altíssimo. O Senhor Deus lhe dará o trono de seu pai Davi,

[[v42-1-33]]

^<<v42-1-33,33>>^ e ele reinará para sempre sobre o povo de Jacó; seu Reino jamais terá fim".

[[v42-1-34]]

^<<v42-1-34,34>>^ Perguntou Maria ao anjo: "Como acontecerá isso, se sou virgem? "

[[v42-1-35]]

^<<v42-1-35,35>>^ O anjo respondeu: "O Espírito Santo virá sobre você, e o poder do Altíssimo a cobrirá com a sua sombra. Assim, aquele que há de nascer será chamado santo, Filho de Deus.

[[v42-1-36]]

^<<v42-1-36,36>>^ Também Isabel, sua parenta, terá um filho na velhice; aquela que diziam ser estéril já está em seu sexto mês de gestação.

[[v42-1-37]]

^<<v42-1-37,37>>^ Pois nada é impossível para Deus".

[[v42-1-38]]

^<<v42-1-38,38>>^ Respondeu Maria: "Sou serva do Senhor; que aconteça comigo conforme a tua palavra". Então o anjo a deixou.

[[v42-1-39]]

^<<v42-1-39,39>>^ Naqueles dias, Maria preparou-se e foi depressa para a uma cidade da região montanhosa da Judéia,

[[v42-1-40]]

^<<v42-1-40,40>>^ onde entrou na casa de Zacarias e saudou Isabel.

[[v42-1-41]]

^<<v42-1-41,41>>^ Quando Isabel ouviu a saudação de Maria, o bebê agitou-se em seu ventre, e Isabel ficou cheia do Espírito Santo.

[[v42-1-42]]

^<<v42-1-42,42>>^ Em alta voz exclamou: "Bendita é você entre as mulheres, e bendito é o filho que você dará à luz!

[[v42-1-43]]

^<<v42-1-43,43>>^ Mas por que sou tão agraciada, a ponto de me visitar a mãe do meu Senhor?

[[v42-1-44]]

^<<v42-1-44,44>>^ Logo que a sua saudação chegou aos meus ouvidos, o bebê que está em meu ventre agitou-se de alegria.

[[v42-1-45]]

^<<v42-1-45,45>>^ Feliz é aquela que creu que se cumprirá aquilo que o Senhor lhe disse! "

[[v42-1-46]]

^<<v42-1-46,46>>^ Então disse Maria: "Minha alma engrandece ao Senhor

[[v42-1-47]]

^<<v42-1-47,47>>^ e o meu espírito se alegra em Deus, meu Salvador,

[[v42-1-48]]

^<<v42-1-48,48>>^ pois atentou para a humildade da sua serva. De agora em diante, todas as gerações me chamarão bem-aventurada,

[[v42-1-49]]

^<<v42-1-49,49>>^ pois o Poderoso fez grandes coisas em meu favor; santo é o seu nome.

[[v42-1-50]]

^<<v42-1-50,50>>^ A sua misericórdia estende-se aos que o temem, de geração em geração.

[[v42-1-51]]

^<<v42-1-51,51>>^ Ele realizou poderosos feitos com seu braço; dispersou os que são soberbos no mais íntimo do coração.

[[v42-1-52]]

^<<v42-1-52,52>>^ Derrubou governantes dos seus tronos, mas exaltou os humildes.

[[v42-1-53]]

^<<v42-1-53,53>>^ Encheu de coisas boas os famintos, mas despediu de mãos vazias os ricos.

[[v42-1-54]]

^<<v42-1-54,54>>^ Ajudou a seu servo Israel, lembrando-se da sua misericórdia

[[v42-1-55]]

^<<v42-1-55,55>>^ para com Abraão e seus descendentes para sempre, como dissera aos nossos antepassados".

[[v42-1-56]]

^<<v42-1-56,56>>^ Maria ficou com Isabel cerca de três meses e depois voltou para casa.

[[v42-1-57]]

^<<v42-1-57,57>>^ Ao se completar o tempo de Isabel dar à luz, ela teve um filho.

[[v42-1-58]]

^<<v42-1-58,58>>^ Seus vizinhos e parentes ouviram falar da grande misericórdia que o Senhor lhe havia demonstrado e se alegraram com ela.

[[v42-1-59]]

^<<v42-1-59,59>>^ No oitavo dia foram circuncidar o menino e queriam dar-lhe o nome do pai, Zacarias;

[[v42-1-60]]

^<<v42-1-60,60>>^ mas sua mãe tomou a palavra e disse: "Não! Ele será chamado João".

[[v42-1-61]]

^<<v42-1-61,61>>^ Disseram-lhe: "Você não há nenhum parente com esse nome".

[[v42-1-62]]

^<<v42-1-62,62>>^ Então fizeram sinais ao pai do menino, para saber como queria que a criança se chamasse.

[[v42-1-63]]

^<<v42-1-63,63>>^ Ele pediu uma tabuinha e, para admiração de todos, escreveu: "O nome dele é João".

[[v42-1-64]]

^<<v42-1-64,64>>^ Imediatamente sua boca se abriu, sua língua se soltou e ele começou a falar, louvando a Deus.

[[v42-1-65]]

^<<v42-1-65,65>>^ Todos os vizinhos ficaram cheios de temor, e por toda a região montanhosa da Judéia se falava sobre essas coisas.

[[v42-1-66]]

^<<v42-1-66,66>>^ Todos os que ouviam falar disso se perguntavam: "O que vai ser este menino? " Pois a mão do Senhor estava com ele.

[[v42-1-67]]

^<<v42-1-67,67>>^ Seu pai, Zacarias, foi cheio do Espírito Santo e profetizou:

[[v42-1-68]]

^<<v42-1-68,68>>^ "Louvado seja o Senhor, o Deus de Israel, porque visitou e redimiu o seu povo.

[[v42-1-69]]

^<<v42-1-69,69>>^ Ele promoveu poderosa salvação para nós, na linhagem do seu servo Davi,

[[v42-1-70]]

^<<v42-1-70,70>>^ ( como falara pelos seus santos profetas, na antigüidade ),

[[v42-1-71]]

^<<v42-1-71,71>>^ salvando-nos dos nossos inimigos e da mão de todos os que nos odeiam,

[[v42-1-72]]

^<<v42-1-72,72>>^ para mostrar sua misericórdia aos nossos antepassados e lembrar sua santa aliança,

[[v42-1-73]]

^<<v42-1-73,73>>^ o juramento que fez ao nosso pai Abraão:

[[v42-1-74]]

^<<v42-1-74,74>>^ resgatar-nos da mão dos nossos inimigos para servi-lo sem medo,

[[v42-1-75]]

^<<v42-1-75,75>>^ em santidade e justiça, diante dele todos os nossos dias.

[[v42-1-76]]

^<<v42-1-76,76>>^ E você, menino, será chamado profeta do Altíssimo, pois irá adiante do Senhor, para lhe preparar o caminho,

[[v42-1-77]]

^<<v42-1-77,77>>^ para dar ao seu povo o conhecimento da salvação, mediante o perdão dos seus pecados,

[[v42-1-78]]

^<<v42-1-78,78>>^ por causa das ternas misericórdias de nosso Deus, pelas quais do alto nos visitará o sol nascente

[[v42-1-79]]

^<<v42-1-79,79>>^ para brilhar sobre aqueles que estão vivendo nas trevas e na sombra da morte, e guiar nossos pés no caminho da paz".

[[v42-1-80]]

^<<v42-1-80,80>>^ E o menino crescia e se fortalecia no espírito; e viveu no deserto, até aparecer publicamente a Israel.

'''

xref:041-marcos/041-marcos-016.adoc#v41-16-0[&#60; Capítulo Anterior] | <<v42-1-0,Topo>> | xref:042-lucas/042-lucas-002.adoc#v42-2-0[Próximo Capítulo &#62;]