include::./index.adoc[]

[[v42-8-0]]
=== Lucas, 8
// nvi ?, NVI - Nova Versão Internacional

[[v42-8-1]]

^<<v42-8-1,1>>^ Depois disso Jesus ia passando pelas cidades e povoados proclamando as boas novas do Reino de Deus. Os Doze estavam com ele,

[[v42-8-2]]

^<<v42-8-2,2>>^ e também algumas mulheres que haviam sido curadas de espíritos malignos e doenças: Maria, chamada Madalena, de quem haviam saído sete demônios;

[[v42-8-3]]

^<<v42-8-3,3>>^ Joana, mulher de Cuza, administrador da casa de Herodes; Susana e muitas outras. Essas mulheres ajudavam a sustentá-los com os seus bens.

[[v42-8-4]]

^<<v42-8-4,4>>^ Reunindo-se uma grande multidão e vindo a Jesus gente de várias cidades, ele contou esta parábola:

[[v42-8-5]]

^<<v42-8-5,5>>^ "O semeador saiu a semear. Enquanto lançava a semente, parte dela caiu à beira do caminho; foi pisada, e as aves do céu a comeram.

[[v42-8-6]]

^<<v42-8-6,6>>^ Parte dela caiu sobre pedras e, quando germinou, as plantas secaram, porque não havia umidade.

[[v42-8-7]]

^<<v42-8-7,7>>^ Outra parte caiu entre espinhos, que cresceram com ela e sufocaram as plantas.

[[v42-8-8]]

^<<v42-8-8,8>>^ Outra ainda caiu em boa terra. Cresceu e deu boa colheita, a cem por um". Tendo dito isso, exclamou: "Aquele que tem ouvidos para ouvir, ouça! "

[[v42-8-9]]

^<<v42-8-9,9>>^ Seus discípulos perguntaram-lhe o que significava aquela parábola.

[[v42-8-10]]

^<<v42-8-10,10>>^ Ele disse: "A vocês foi dado o conhecimento dos mistérios do Reino de Deus, mas aos outros falo por parábolas, para que ‘vendo, não vejam; e ouvindo, não entendam’.

[[v42-8-11]]

^<<v42-8-11,11>>^ "Este é o significado da parábola: A semente é a palavra de Deus.

[[v42-8-12]]

^<<v42-8-12,12>>^ As que caíram à beira do caminho são os que ouvem, e então vem o diabo e tira a palavra dos seus corações, para que não creiam e não sejam salvos.

[[v42-8-13]]

^<<v42-8-13,13>>^ As que caíram sobre as pedras são os que recebem a palavra com alegria quando a ouvem, mas não têm raiz. Crêem durante algum tempo, mas desistem na hora da provação.

[[v42-8-14]]

^<<v42-8-14,14>>^ As que caíram entre espinhos são os que ouvem, mas, ao seguirem seu caminho, são sufocados pelas preocupações, pelas riquezas e pelos prazeres desta vida, e não amadurecem.

[[v42-8-15]]

^<<v42-8-15,15>>^ Mas as que caíram em boa terra são os que, com coração bom e generoso, ouvem a palavra, a retêm e dão fruto, com perseverança".

[[v42-8-16]]

^<<v42-8-16,16>>^ "Ninguém acende uma candeia e a esconde num jarro ou a coloca debaixo de uma cama. Pelo contrário, coloca-a num lugar apropriado, de modo que os que entram possam ver a luz.

[[v42-8-17]]

^<<v42-8-17,17>>^ Porque não há nada oculto que não venha a ser revelado, e nada escondido que não venha a ser conhecido e trazido à luz.

[[v42-8-18]]

^<<v42-8-18,18>>^ Portanto, considerem atentamente como vocês estão ouvindo. A quem tiver, mais lhe será dado; de quem não tiver, até o que pensa que tem lhe será tirado".

[[v42-8-19]]

^<<v42-8-19,19>>^ A mãe e os irmãos de Jesus foram vê-lo, mas não conseguiam aproximar-se dele, por causa da multidão.

[[v42-8-20]]

^<<v42-8-20,20>>^ Alguém lhe disse: "Tua mãe e teus irmãos estão lá fora e querem ver-te".

[[v42-8-21]]

^<<v42-8-21,21>>^ Ele lhe respondeu: "Minha mãe e meus irmãos são aqueles que ouvem a palavra de Deus e a praticam".

[[v42-8-22]]

^<<v42-8-22,22>>^ Certo dia Jesus disse aos seus discípulos: "Vamos para o outro lado do lago". Eles entraram num barco e partiram.

[[v42-8-23]]

^<<v42-8-23,23>>^ Enquanto navegavam, ele adormeceu. Abateu-se sobre o lago um forte vendaval, de modo que o barco estava sendo inundado, e eles corriam grande perigo.

[[v42-8-24]]

^<<v42-8-24,24>>^ Os discípulos foram acordá-lo, clamando: "Mestre, Mestre, vamos morrer! " Ele se levantou e repreendeu o vento e a violência das águas; tudo se acalmou e ficou tranqüilo.

[[v42-8-25]]

^<<v42-8-25,25>>^ "Onde está a sua fé? ", perguntou ele aos seus discípulos. Amedrontados e admirados, eles perguntaram uns aos outros: "Quem é este que até aos ventos e às águas dá ordens, e eles lhe obedecem? "

[[v42-8-26]]

^<<v42-8-26,26>>^ Navegaram para a região dos gerasenos que fica do outro lado do lago, frente à Galiléia.

[[v42-8-27]]

^<<v42-8-27,27>>^ Quando Jesus pisou em terra, foi ao encontro dele um endemoninhado daquela cidade. Fazia muito tempo que aquele homem não usava roupas, nem vivia em casa alguma, mas nos sepulcros.

[[v42-8-28]]

^<<v42-8-28,28>>^ Quando viu Jesus, gritou, prostrou-se aos seus pés e disse em alta voz: "Que queres comigo, Jesus, Filho do Deus Altíssimo? Rogo-te que não me atormentes! "

[[v42-8-29]]

^<<v42-8-29,29>>^ Pois Jesus havia ordenado que o espírito imundo saísse daquele homem. Muitas vezes ele tinha se apoderado dele. Mesmo com os pés e as mãos acorrentados e entregue aos cuidados de guardas, quebrava as correntes, e era levado pelo demônio a lugares solitários.

[[v42-8-30]]

^<<v42-8-30,30>>^ Jesus lhe perguntou: "Qual é o seu nome? " "Legião", respondeu ele; porque muitos demônios haviam entrado nele.

[[v42-8-31]]

^<<v42-8-31,31>>^ E imploravam-lhe que não os mandasse para o abismo.

[[v42-8-32]]

^<<v42-8-32,32>>^ Uma grande manada de porcos estava pastando naquela colina. Os demônios imploraram a Jesus que lhes permitisse entrar neles, e Jesus lhes deu permissão.

[[v42-8-33]]

^<<v42-8-33,33>>^ Saindo do homem, os demônios entraram nos porcos, e toda a manada atirou-se precipício abaixo em direção ao lago e se afogou.

[[v42-8-34]]

^<<v42-8-34,34>>^ Vendo o que acontecera, os que cuidavam dos porcos fugiram e contaram esses fatos, na cidade e nos campos,

[[v42-8-35]]

^<<v42-8-35,35>>^ e o povo foi ver o que havia acontecido. Quando se aproximaram de Jesus, viram que o homem de quem haviam saído os demônios estava assentado aos pés de Jesus, vestido e em perfeito juízo, e ficaram com medo.

[[v42-8-36]]

^<<v42-8-36,36>>^ Os que o tinham visto contaram ao povo como o endemoninhado fora curado.

[[v42-8-37]]

^<<v42-8-37,37>>^ Então, todo o povo da região dos gerasenos suplicou a Jesus que se retirasse, porque estavam dominados pelo medo. Ele entrou no barco e regressou.

[[v42-8-38]]

^<<v42-8-38,38>>^ O homem de quem haviam saído os demônios suplicava-lhe que o deixasse ir com ele; mas Jesus o mandou embora, dizendo:

[[v42-8-39]]

^<<v42-8-39,39>>^ "Volte para casa e conte o quanto Deus lhe fez". Assim, o homem se foi e anunciou a toda a cidade o quanto Jesus tinha feito por ele.

[[v42-8-40]]

^<<v42-8-40,40>>^ Quando Jesus voltou, uma multidão o recebeu, pois todos o esperavam.

[[v42-8-41]]

^<<v42-8-41,41>>^ Então um homem chamado Jairo, dirigente da sinagoga, veio e prostrou-se aos pés de Jesus, implorando-lhe que fosse à sua casa

[[v42-8-42]]

^<<v42-8-42,42>>^ porque sua única filha, de cerca de doze anos, estava à morte. Estando Jesus a caminho, a multidão o comprimia.

[[v42-8-43]]

^<<v42-8-43,43>>^ E estava ali certa mulher que havia doze anos vinha sofrendo de uma hemorragia e gastara tudo o que tinha com os médicos; mas ninguém pudera curá-la.

[[v42-8-44]]

^<<v42-8-44,44>>^ Ela chegou por trás dele, tocou na borda de seu manto, e imediatamente cessou sua hemorragia.

[[v42-8-45]]

^<<v42-8-45,45>>^ "Quem tocou em mim? ", perguntou Jesus. Como todos negassem, Pedro disse: "Mestre, a multidão se aglomera e te comprime".

[[v42-8-46]]

^<<v42-8-46,46>>^ Mas Jesus disse: "Alguém tocou em mim; eu sei que de mim saiu poder".

[[v42-8-47]]

^<<v42-8-47,47>>^ Então a mulher, vendo que não conseguiria passar despercebida, veio tremendo e prostrou-se aos seus pés. Na presença de todo o povo contou por que tinha tocado nele e como fora instantaneamente curada.

[[v42-8-48]]

^<<v42-8-48,48>>^ Então ele lhe disse: "Filha, a sua fé a curou! Vá em paz".

[[v42-8-49]]

^<<v42-8-49,49>>^ Enquanto Jesus ainda estava falando, chegou alguém da casa de Jairo, o dirigente da sinagoga, e disse: "Sua filha morreu. Não incomode mais o Mestre".

[[v42-8-50]]

^<<v42-8-50,50>>^ Ouvindo isso, Jesus disse a Jairo: "Não tenha medo; tão-somente creia, e ela será curada".

[[v42-8-51]]

^<<v42-8-51,51>>^ Quando chegou à casa de Jairo, não deixou ninguém entrar com ele, exceto Pedro, João, Tiago e o pai e a mãe da criança.

[[v42-8-52]]

^<<v42-8-52,52>>^ Enquanto isso, todo o povo estava se lamentando e chorando por ela. "Não chorem", disse Jesus. "Ela não está morta, mas dorme".

[[v42-8-53]]

^<<v42-8-53,53>>^ Todos começaram a rir dele, pois sabiam que ela estava morta.

[[v42-8-54]]

^<<v42-8-54,54>>^ Mas ele a tomou pela mão e disse: "Menina, levante-se! "

[[v42-8-55]]

^<<v42-8-55,55>>^ O espírito dela voltou, e ela se levantou imediatamente. Então Jesus lhes ordenou que lhe dessem de comer.

[[v42-8-56]]

^<<v42-8-56,56>>^ Os pais dela ficaram maravilhados, mas ele lhes ordenou que não contassem a ninguém o que tinha acontecido.

'''

xref:042-lucas/042-lucas-007.adoc#v42-7-0[&#60; Capítulo Anterior] | <<v42-8-0,Topo>> | xref:042-lucas/042-lucas-009.adoc#v42-9-0[Próximo Capítulo &#62;]