include::./index.adoc[]

[[v42-19-0]]
=== Lucas, 19
// nvi ?, NVI - Nova Versão Internacional

[[v42-19-1]]

^<<v42-19-1,1>>^ Jesus entrou em Jericó, e atravessava a cidade.

[[v42-19-2]]

^<<v42-19-2,2>>^ Havia ali um homem rico chamado Zaqueu, chefe dos publicanos.

[[v42-19-3]]

^<<v42-19-3,3>>^ Ele queria ver quem era Jesus, mas, sendo de pequena estatura, não o conseguia, por causa da multidão.

[[v42-19-4]]

^<<v42-19-4,4>>^ Assim, correu adiante e subiu numa figueira brava para vê-lo, pois Jesus ia passar por ali.

[[v42-19-5]]

^<<v42-19-5,5>>^ Quando Jesus chegou àquele lugar, olhou para cima e lhe disse: "Zaqueu, desça depressa. Quero ficar em sua casa hoje".

[[v42-19-6]]

^<<v42-19-6,6>>^ Então ele desceu rapidamente e o recebeu com alegria.

[[v42-19-7]]

^<<v42-19-7,7>>^ Todo o povo viu isso e começou a se queixar: "Ele se hospedou na casa de um ‘pecador’ ".

[[v42-19-8]]

^<<v42-19-8,8>>^ Mas Zaqueu levantou-se e disse ao Senhor: "Olha, Senhor! Estou dando a metade dos meus bens aos pobres; e se de alguém extorqui alguma coisa, devolverei quatro vezes mais".

[[v42-19-9]]

^<<v42-19-9,9>>^ Jesus lhe disse: "Hoje houve salvação nesta casa! Porque este homem também é filho de Abraão.

[[v42-19-10]]

^<<v42-19-10,10>>^ Pois o Filho do homem veio buscar e salvar o que estava perdido".

[[v42-19-11]]

^<<v42-19-11,11>>^ Estando eles a ouvi-lo, Jesus passou a contar-lhes uma parábola, porque estava perto de Jerusalém e o povo pensava que o Reino de Deus ia se manifestar de imediato.

[[v42-19-12]]

^<<v42-19-12,12>>^ Ele disse: "Um homem de nobre nascimento foi para uma terra distante para ser coroado rei e depois voltar.

[[v42-19-13]]

^<<v42-19-13,13>>^ Então, chamou dez dos seus servos e lhes deu dez minas. Disse ele: ‘Façam esse dinheiro render até à minha volta’.

[[v42-19-14]]

^<<v42-19-14,14>>^ "Mas os seus súditos o odiavam e depois enviaram uma delegação para lhe dizer: ‘Não queremos que este homem seja nosso rei’.

[[v42-19-15]]

^<<v42-19-15,15>>^ "Contudo, foi feito rei e voltou. Então mandou chamar os servos a quem dera o dinheiro, a fim de saber quanto tinham lucrado.

[[v42-19-16]]

^<<v42-19-16,16>>^ "O primeiro veio e disse: ‘Senhor, a tua mina rendeu outras dez’.

[[v42-19-17]]

^<<v42-19-17,17>>^ " ‘Muito bem, meu bom servo! ’, respondeu o seu senhor. ‘Por ter sido confiável no pouco, governe sobre dez cidades’.

[[v42-19-18]]

^<<v42-19-18,18>>^ "O segundo veio e disse: ‘Senhor, a tua mina rendeu cinco vezes mais’.

[[v42-19-19]]

^<<v42-19-19,19>>^ "O seu senhor respondeu: ‘Também você, encarregue-se de cinco cidades’.

[[v42-19-20]]

^<<v42-19-20,20>>^ "Então veio outro servo e disse: ‘Senhor, aqui está a tua mina; eu a conservei guardada num pedaço de pano.

[[v42-19-21]]

^<<v42-19-21,21>>^ Tive medo, porque és um homem severo. Tiras o que não puseste e colhes o que não semeaste’.

[[v42-19-22]]

^<<v42-19-22,22>>^ "O seu senhor respondeu: ‘Eu o julgarei pelas suas próprias palavras, servo mau! Você sabia que sou homem severo, que tiro o que não pus e colho o que não semeei.

[[v42-19-23]]

^<<v42-19-23,23>>^ Então, por que não confiou o meu dinheiro ao banco? Assim, quando eu voltasse o receberia com os juros’.

[[v42-19-24]]

^<<v42-19-24,24>>^ "E disse aos que estavam ali: ‘Tomem dele a sua mina e dêem-na ao que tem dez’.

[[v42-19-25]]

^<<v42-19-25,25>>^ " ‘Senhor’, disseram, ‘ele já tem dez! ’

[[v42-19-26]]

^<<v42-19-26,26>>^ "Ele respondeu: ‘Eu lhes digo que a quem tem, mais será dado, mas a quem não tem, até o que tiver lhe será tirado.

[[v42-19-27]]

^<<v42-19-27,27>>^ E aqueles inimigos meus, que não queriam que eu reinasse sobre eles, tragam-nos aqui e matem-nos na minha frente! ’ "

[[v42-19-28]]

^<<v42-19-28,28>>^ Depois de dizer isso, Jesus foi adiante, subindo para Jerusalém.

[[v42-19-29]]

^<<v42-19-29,29>>^ Ao aproximar-se de Betfagé e de Betânia, no monte chamado das Oliveiras, enviou dois dos seus discípulos, dizendo-lhes:

[[v42-19-30]]

^<<v42-19-30,30>>^ "Vão ao povoado que está adiante e, ao entrarem, encontrarão um jumentinho amarrado, no qual ninguém jamais montou. Desamarrem-no e tragam-no aqui.

[[v42-19-31]]

^<<v42-19-31,31>>^ Se alguém lhes perguntar: ‘Por que o estão desamarrando? ’ digam-lhe: ‘O Senhor precisa dele’ ".

[[v42-19-32]]

^<<v42-19-32,32>>^ Os que tinham sido enviados foram e encontraram o animal exatamente como ele lhes tinha dito.

[[v42-19-33]]

^<<v42-19-33,33>>^ Quando estavam desamarrando o jumentinho, os seus donos lhes perguntaram: "Por que vocês estão desamarrando o jumentinho? "

[[v42-19-34]]

^<<v42-19-34,34>>^ Eles responderam: "O Senhor precisa dele".

[[v42-19-35]]

^<<v42-19-35,35>>^ Levaram-no a Jesus, lançaram seus mantos sobre o jumentinho e fizeram que Jesus montasse nele.

[[v42-19-36]]

^<<v42-19-36,36>>^ Enquanto ele prosseguia, o povo estendia os seus mantos pelo caminho.

[[v42-19-37]]

^<<v42-19-37,37>>^ Quando ele já estava perto da descida do monte das Oliveiras, toda a multidão dos discípulos começou a louvar a Deus alegremente, em alta voz, por todos os milagres que tinham visto. Exclamavam:

[[v42-19-38]]

^<<v42-19-38,38>>^ "Bendito é o rei que vem em nome do Senhor! " "Paz no céu e glória nas alturas! "

[[v42-19-39]]

^<<v42-19-39,39>>^ Alguns dos fariseus que estavam no meio da multidão disseram a Jesus: "Mestre, repreende os teus discípulos! "

[[v42-19-40]]

^<<v42-19-40,40>>^ "Eu lhes digo", respondeu ele, "se eles se calarem, as pedras clamarão".

[[v42-19-41]]

^<<v42-19-41,41>>^ Quando se aproximou e viu a cidade, Jesus chorou sobre ela

[[v42-19-42]]

^<<v42-19-42,42>>^ e disse: "Se você compreendesse neste dia, sim, você também, o que traz a paz! Mas agora isso está oculto aos seus olhos.

[[v42-19-43]]

^<<v42-19-43,43>>^ Virão dias em que os seus inimigos construirão trincheiras contra você, e a rodearão e a cercarão de todos os lados.

[[v42-19-44]]

^<<v42-19-44,44>>^ Também a lançarão por terra, você e os seus filhos. Não deixarão pedra sobre pedra, porque você não reconheceu o tempo em que Deus a visitaria".

[[v42-19-45]]

^<<v42-19-45,45>>^ Então ele entrou no templo e começou a expulsar os que estavam vendendo.

[[v42-19-46]]

^<<v42-19-46,46>>^ Disse-lhes: "Está escrito: ‘A minha casa será casa de oração’; mas vocês fizeram dela ‘um covil de ladrões’".

[[v42-19-47]]

^<<v42-19-47,47>>^ Todos os dias ele ensinava no templo. Mas os chefes dos sacerdotes, os mestres da lei e os líderes do povo procuravam matá-lo.

[[v42-19-48]]

^<<v42-19-48,48>>^ Todavia, não conseguiam encontrar uma forma de fazê-lo, porque todo o povo estava fascinado pelas suas palavras.

'''

xref:042-lucas/042-lucas-018.adoc#v42-18-0[&#60; Capítulo Anterior] | <<v42-19-0,Topo>> | xref:042-lucas/042-lucas-020.adoc#v42-20-0[Próximo Capítulo &#62;]