include::./index.adoc[]

[[v42-18-0]]
=== Lucas, 18
// nvi ?, NVI - Nova Versão Internacional

[[v42-18-1]]

^<<v42-18-1,1>>^ Então Jesus contou aos seus discípulos uma parábola, para mostrar-lhes que eles deviam orar sempre e nunca desanimar.

[[v42-18-2]]

^<<v42-18-2,2>>^ Ele disse: "Em certa cidade havia um juiz que não temia a Deus nem se importava com os homens.

[[v42-18-3]]

^<<v42-18-3,3>>^ E havia naquela cidade uma viúva que se dirigia continuamente a ele, suplicando-lhe: ‘Faze-me justiça contra o meu adversário’.

[[v42-18-4]]

^<<v42-18-4,4>>^ "Por algum tempo ele se recusou. Mas finalmente disse a si mesmo: ‘Embora eu não tema a Deus e nem me importe com os homens,

[[v42-18-5]]

^<<v42-18-5,5>>^ esta viúva está me aborrecendo; vou fazer-lhe justiça para que ela não venha me importunar’ ".

[[v42-18-6]]

^<<v42-18-6,6>>^ E o Senhor continuou: "Ouçam o que diz o juiz injusto.

[[v42-18-7]]

^<<v42-18-7,7>>^ Acaso Deus não fará justiça aos seus escolhidos, que clamam a ele dia e noite? Continuará fazendo-os esperar?

[[v42-18-8]]

^<<v42-18-8,8>>^ Eu lhes digo: ele lhes fará justiça, e depressa. Contudo, quando o Filho do homem vier, encontrará fé na terra? "

[[v42-18-9]]

^<<v42-18-9,9>>^ A alguns que confiavam em sua própria justiça e desprezavam os outros, Jesus contou esta parábola:

[[v42-18-10]]

^<<v42-18-10,10>>^ "Dois homens subiram ao templo para orar; um era fariseu e o outro, publicano.

[[v42-18-11]]

^<<v42-18-11,11>>^ O fariseu, em pé, orava no íntimo: ‘Deus, eu te agradeço porque não sou como os outros homens: ladrões, corruptos, adúlteros; nem mesmo como este publicano.

[[v42-18-12]]

^<<v42-18-12,12>>^ Jejuo duas vezes por semana e dou o dízimo de tudo quanto ganho’.

[[v42-18-13]]

^<<v42-18-13,13>>^ "Mas o publicano ficou à distância. Ele nem ousava olhar para o céu, mas batendo no peito, dizia: ‘Deus, tem misericórdia de mim, que sou pecador’.

[[v42-18-14]]

^<<v42-18-14,14>>^ "Eu lhes digo que este homem, e não o outro, foi para casa justificado diante de Deus. Pois quem se exalta será humilhado, e quem se humilha será exaltado".

[[v42-18-15]]

^<<v42-18-15,15>>^ O povo também estava trazendo criancinhas para que Jesus tocasse nelas. Ao verem isto, os discípulos repreendiam os que as tinham trazido.

[[v42-18-16]]

^<<v42-18-16,16>>^ Mas Jesus chamou a si as crianças e disse: "Deixem vir a mim as crianças e não as impeçam; pois o Reino de Deus pertence aos que são semelhantes a elas.

[[v42-18-17]]

^<<v42-18-17,17>>^ Digo-lhes a verdade: Quem não receber o Reino de Deus como uma criança, nunca entrará nele".

[[v42-18-18]]

^<<v42-18-18,18>>^ Certo homem importante lhe perguntou: "Bom Mestre, que farei para herdar a vida eterna? "

[[v42-18-19]]

^<<v42-18-19,19>>^ "Por que você me chama bom? ", respondeu Jesus. "Não há ninguém que seja bom, a não ser somente Deus.

[[v42-18-20]]

^<<v42-18-20,20>>^ Você conhece os mandamentos: ‘Não adulterarás, não matarás, não furtarás, não darás falso testemunho, honra teu pai e tua mãe’".

[[v42-18-21]]

^<<v42-18-21,21>>^ "A tudo isso tenho obedecido desde a adolescência", disse ele.

[[v42-18-22]]

^<<v42-18-22,22>>^ Ao ouvir isso, disse-lhe Jesus: "Falta-lhe ainda uma coisa. Venda tudo o que você possui e dê o dinheiro aos pobres, e você terá um tesouro nos céus. Depois venha e siga-me".

[[v42-18-23]]

^<<v42-18-23,23>>^ Ouvindo isso, ele ficou triste, porque era muito rico.

[[v42-18-24]]

^<<v42-18-24,24>>^ Vendo-o entristecido, Jesus disse: "Como é difícil aos ricos entrar no Reino de Deus!

[[v42-18-25]]

^<<v42-18-25,25>>^ De fato, é mais fácil passar um camelo pelo fundo de uma agulha do que um rico entrar no Reino de Deus".

[[v42-18-26]]

^<<v42-18-26,26>>^ Os que ouviram isso perguntaram: "Então, quem pode ser salvo? "

[[v42-18-27]]

^<<v42-18-27,27>>^ Jesus respondeu: "O que é impossível para os homens é possível para Deus".

[[v42-18-28]]

^<<v42-18-28,28>>^ Pedro lhe disse: "Nós deixamos tudo o que tínhamos para seguir-te! "

[[v42-18-29]]

^<<v42-18-29,29>>^ Respondeu Jesus: "Digo-lhes a verdade: Ninguém que tenha deixado casa, mulher, irmãos, pai ou filhos por causa do Reino de Deus

[[v42-18-30]]

^<<v42-18-30,30>>^ deixará de receber, na presente era, muitas vezes mais, e, na era futura, a vida eterna".

[[v42-18-31]]

^<<v42-18-31,31>>^ Jesus chamou à parte os Doze e lhes disse: "Estamos subindo para Jerusalém, e tudo o que está escrito pelos profetas acerca do Filho do homem se cumprirá.

[[v42-18-32]]

^<<v42-18-32,32>>^ Ele será entregue aos gentios que zombarão dele, o insultarão, cuspirão nele, o açoitarão e o matarão.

[[v42-18-33]]

^<<v42-18-33,33>>^ No terceiro dia ele ressuscitará".

[[v42-18-34]]

^<<v42-18-34,34>>^ Os discípulos não entenderam nada dessas coisas. O significado dessas palavras lhes estava oculto, e eles não sabiam do que ele estava falando.

[[v42-18-35]]

^<<v42-18-35,35>>^ Ao aproximar-se Jesus de Jericó, um homem cego estava sentado à beira do caminho, pedindo esmola.

[[v42-18-36]]

^<<v42-18-36,36>>^ Quando ouviu a multidão passando, ele perguntou o que estava acontecendo.

[[v42-18-37]]

^<<v42-18-37,37>>^ Disseram-lhe: "Jesus de Nazaré está passando".

[[v42-18-38]]

^<<v42-18-38,38>>^ Então ele se pôs a gritar: "Jesus, filho de Davi, tem misericórdia de mim! "

[[v42-18-39]]

^<<v42-18-39,39>>^ Os que iam adiante o repreendiam para que ficasse quieto, mas ele gritava ainda mais: "Filho de Davi, tem misericórdia de mim! "

[[v42-18-40]]

^<<v42-18-40,40>>^ Jesus parou e ordenou que o homem lhe fosse trazido. Quando ele chegou perto, Jesus perguntou-lhe:

[[v42-18-41]]

^<<v42-18-41,41>>^ "O que você quer que eu lhe faça? " "Senhor, eu quero ver", respondeu ele.

[[v42-18-42]]

^<<v42-18-42,42>>^ Jesus lhe disse: "Recupere a visão! A sua fé o curou".

[[v42-18-43]]

^<<v42-18-43,43>>^ Imediatamente ele recuperou a visão; e seguia a Jesus glorificando a Deus. Quando todo o povo viu isso, deu louvores a Deus.

'''

xref:042-lucas/042-lucas-017.adoc#v42-17-0[&#60; Capítulo Anterior] | <<v42-18-0,Topo>> | xref:042-lucas/042-lucas-019.adoc#v42-19-0[Próximo Capítulo &#62;]