include::./index.adoc[]

[[v42-10-0]]
=== Lucas, 10
// nvi ?, NVI - Nova Versão Internacional

[[v42-10-1]]

^<<v42-10-1,1>>^ Depois disso o Senhor designou outros setenta e dois e os enviou dois a dois, adiante dele, a todas as cidades e lugares para onde ele estava prestes a ir.

[[v42-10-2]]

^<<v42-10-2,2>>^ E lhes disse: "A colheita é grande, mas os trabalhadores são poucos. Portanto, peçam ao Senhor da colheita que mande trabalhadores para a sua colheita.

[[v42-10-3]]

^<<v42-10-3,3>>^ Vão! Eu os estou enviando como cordeiros entre lobos.

[[v42-10-4]]

^<<v42-10-4,4>>^ Não levem bolsa nem saco de viagem nem sandálias; e não saúdem ninguém pelo caminho.

[[v42-10-5]]

^<<v42-10-5,5>>^ "Quando entrarem numa casa, digam primeiro: ‘Paz a esta casa’.

[[v42-10-6]]

^<<v42-10-6,6>>^ Se houver ali um homem de paz, a paz de vocês repousará sobre ele; se não, ela voltará para vocês.

[[v42-10-7]]

^<<v42-10-7,7>>^ Fiquem naquela casa, e comam e bebam o que lhes derem, pois o trabalhador merece o seu salário. Não fiquem mudando de casa em casa.

[[v42-10-8]]

^<<v42-10-8,8>>^ "Quando entrarem numa cidade e forem bem recebidos, comam o que for posto diante de vocês.

[[v42-10-9]]

^<<v42-10-9,9>>^ Curem os doentes que ali houver e digam-lhes: ‘O Reino de Deus está próximo de vocês’.

[[v42-10-10]]

^<<v42-10-10,10>>^ Mas quando entrarem numa cidade e não forem bem recebidos, saiam por suas ruas e digam:

[[v42-10-11]]

^<<v42-10-11,11>>^ ‘Até o pó da sua cidade, que se apegou aos nossos pés, sacudimos contra vocês. Fiquem certos disto: O Reino de Deus está próximo’.

[[v42-10-12]]

^<<v42-10-12,12>>^ Eu lhes digo: Naquele dia haverá mais tolerância para Sodoma do que para aquela cidade.

[[v42-10-13]]

^<<v42-10-13,13>>^ "Ai de você, Corazim! Ai de você, Betsaida! Porque se os milagres que foram realizados entre vocês o fossem em Tiro e Sidom, há muito tempo elas se teriam arrependido, vestindo roupas de saco e cobrindo-se de cinzas.

[[v42-10-14]]

^<<v42-10-14,14>>^ Mas no juízo haverá menor rigor para Tiro e Sidom do que para vocês.

[[v42-10-15]]

^<<v42-10-15,15>>^ E você, Cafarnaum: será elevada até o céu? Não; você descerá até ao Hades!

[[v42-10-16]]

^<<v42-10-16,16>>^ "Aquele que lhes dá ouvidos, está me dando ouvidos; aquele que os rejeita, está me rejeitando; mas aquele que me rejeita, está rejeitando aquele que me enviou".

[[v42-10-17]]

^<<v42-10-17,17>>^ Os setenta e dois voltaram alegres e disseram: "Senhor, até os demônios se submetem a nós, em teu nome".

[[v42-10-18]]

^<<v42-10-18,18>>^ Ele respondeu: "Eu vi Satanás caindo do céu como relâmpago.

[[v42-10-19]]

^<<v42-10-19,19>>^ Eu lhes dei autoridade para pisarem sobre cobras e escorpiões, e sobre todo o poder do inimigo; nada lhes fará dano.

[[v42-10-20]]

^<<v42-10-20,20>>^ Contudo, alegrem-se, não porque os espíritos se submetem a vocês, mas porque seus nomes estão escritos nos céus".

[[v42-10-21]]

^<<v42-10-21,21>>^ Naquela hora Jesus, exultando no Espírito Santo, disse: "Eu te louvo, Pai, Senhor do céu e da terra, porque escondeste estas coisas dos sábios e cultos e as revelaste aos pequeninos. Sim, Pai, pois assim foi do teu agrado.

[[v42-10-22]]

^<<v42-10-22,22>>^ "Todas as coisas me foram entregues por meu Pai. Ninguém sabe quem é o Filho, a não ser o Pai; e ninguém sabe quem é o Pai, a não ser o Filho e aqueles a quem o Filho o quiser revelar".

[[v42-10-23]]

^<<v42-10-23,23>>^ Então ele se voltou para os seus discípulos e lhes disse em particular: "Felizes são os olhos que vêem o que vocês vêem.

[[v42-10-24]]

^<<v42-10-24,24>>^ Pois eu lhes digo que muitos profetas e reis desejaram ver o que vocês estão vendo, mas não viram; e ouvir o que vocês estão ouvindo, mas não ouviram".

[[v42-10-25]]

^<<v42-10-25,25>>^ Certa ocasião, um perito na lei levantou-se para pôr Jesus à prova e lhe perguntou: "Mestre, o que preciso fazer para herdar a vida eterna? "

[[v42-10-26]]

^<<v42-10-26,26>>^ "O que está escrito na Lei? ", respondeu Jesus. "Como você a lê? "

[[v42-10-27]]

^<<v42-10-27,27>>^ Ele respondeu: " ‘Ame o Senhor, o seu Deus de todo o seu coração, de toda a sua alma, de todas as suas forças e de todo o seu entendimento’ e ‘Ame o seu próximo como a si mesmo’".

[[v42-10-28]]

^<<v42-10-28,28>>^ Disse Jesus: "Você respondeu corretamente. Faça isso, e viverá".

[[v42-10-29]]

^<<v42-10-29,29>>^ Mas ele, querendo justificar-se, perguntou a Jesus: "E quem é o meu próximo? "

[[v42-10-30]]

^<<v42-10-30,30>>^ Em resposta, disse Jesus: "Um homem descia de Jerusalém para Jericó, quando caiu nas mãos de assaltantes. Estes lhe tiraram as roupas, espancaram-no e se foram, deixando-o quase morto.

[[v42-10-31]]

^<<v42-10-31,31>>^ Aconteceu estar descendo pela mesma estrada um sacerdote. Quando viu o homem, passou pelo outro lado.

[[v42-10-32]]

^<<v42-10-32,32>>^ E assim também um levita; quando chegou ao lugar e o viu, passou pelo outro lado.

[[v42-10-33]]

^<<v42-10-33,33>>^ Mas um samaritano, estando de viagem, chegou onde se encontrava o homem e, quando o viu, teve piedade dele.

[[v42-10-34]]

^<<v42-10-34,34>>^ Aproximou-se, enfaixou-lhe as feridas, derramando nelas vinho e óleo. Depois colocou-o sobre o seu próprio animal, levou-o para uma hospedaria e cuidou dele.

[[v42-10-35]]

^<<v42-10-35,35>>^ No dia seguinte, deu dois denários ao hospedeiro e disse-lhe: ‘Cuide dele. Quando voltar lhe pagarei todas as despesas que você tiver’.

[[v42-10-36]]

^<<v42-10-36,36>>^ "Qual destes três você acha que foi o próximo do homem que caiu nas mãos dos assaltantes? "

[[v42-10-37]]

^<<v42-10-37,37>>^ "Aquele que teve misericórdia dele", respondeu o perito na lei. Jesus lhe disse: "Vá e faça o mesmo".

[[v42-10-38]]

^<<v42-10-38,38>>^ Caminhando Jesus e os seus discípulos, chegaram a um povoado, onde certa mulher chamada Marta o recebeu em sua casa.

[[v42-10-39]]

^<<v42-10-39,39>>^ Maria, sua irmã, ficou sentada aos pés do Senhor, ouvindo-lhe a palavra.

[[v42-10-40]]

^<<v42-10-40,40>>^ Marta, porém, estava ocupada com muito serviço. E, aproximando-se dele, perguntou: "Senhor, não te importas que minha irmã tenha me deixado sozinha com o serviço? Dize-lhe que me ajude! "

[[v42-10-41]]

^<<v42-10-41,41>>^ Respondeu o Senhor: "Marta! Marta! Você está preocupada e inquieta com muitas coisas;

[[v42-10-42]]

^<<v42-10-42,42>>^ todavia apenas uma é necessária. Maria escolheu a boa parte, e esta não lhe será tirada".

'''

xref:042-lucas/042-lucas-009.adoc#v42-9-0[&#60; Capítulo Anterior] | <<v42-10-0,Topo>> | xref:042-lucas/042-lucas-011.adoc#v42-11-0[Próximo Capítulo &#62;]