include::./index.adoc[]

[[v42-11-0]]
=== Lucas, 11
// nvi ?, NVI - Nova Versão Internacional

[[v42-11-1]]

^<<v42-11-1,1>>^ Certo dia Jesus estava orando em determinado lugar. Tendo terminado, um dos seus discípulos lhe disse: "Senhor, ensina-nos a orar, como João ensinou aos discípulos dele".

[[v42-11-2]]

^<<v42-11-2,2>>^ Ele lhes disse: "Quando vocês orarem, digam: ‘Pai! Santificado seja o teu nome. Venha o teu Reino.

[[v42-11-3]]

^<<v42-11-3,3>>^ Dá-nos cada dia o nosso pão cotidiano.

[[v42-11-4]]

^<<v42-11-4,4>>^ Perdoa-nos os nossos pecados, pois também perdoamos a todos os que nos devem. E não nos deixes cair em tentação’ ".

[[v42-11-5]]

^<<v42-11-5,5>>^ Então lhes disse: "Suponham que um de vocês tenha um amigo e que recorra a ele à meia-noite e diga: ‘Amigo, empreste-me três pães,

[[v42-11-6]]

^<<v42-11-6,6>>^ porque um amigo meu chegou de viagem, e não tenho nada para lhe oferecer’.

[[v42-11-7]]

^<<v42-11-7,7>>^ "E o que estiver dentro responda: ‘Não me incomode. A porta já está fechada, e meus filhos estão deitados comigo. Não posso me levantar e lhe dar o que me pede’.

[[v42-11-8]]

^<<v42-11-8,8>>^ Eu lhes digo: embora ele não se levante para dar-lhe o pão por ser seu amigo, por causa da importunação se levantará e lhe dará tudo o que precisar.

[[v42-11-9]]

^<<v42-11-9,9>>^ "Por isso lhes digo: Peçam, e lhes será dado; busquem, e encontrarão; batam, e a porta lhes será aberta.

[[v42-11-10]]

^<<v42-11-10,10>>^ Pois todo o que pede, recebe; o que busca, encontra; e àquele que bate, a porta será aberta.

[[v42-11-11]]

^<<v42-11-11,11>>^ "Qual pai, entre vocês, se o filho lhe pedir um peixe, em lugar disso lhe dará uma cobra?

[[v42-11-12]]

^<<v42-11-12,12>>^ Ou se pedir um ovo, lhe dará um escorpião?

[[v42-11-13]]

^<<v42-11-13,13>>^ Se vocês, apesar de serem maus, sabem dar boas coisas aos seus filhos, quanto mais o Pai que está no céu dará o Espírito Santo a quem o pedir! "

[[v42-11-14]]

^<<v42-11-14,14>>^ Jesus estava expulsando um demônio que era mudo. Quando o demônio saiu, o mudo falou, e a multidão ficou admirada.

[[v42-11-15]]

^<<v42-11-15,15>>^ Mas alguns deles disseram: "É por Belzebu, o príncipe dos demônios, que ele expulsa demônios".

[[v42-11-16]]

^<<v42-11-16,16>>^ Outros o punham à prova, pedindo-lhe um sinal do céu.

[[v42-11-17]]

^<<v42-11-17,17>>^ Jesus, conhecendo os seus pensamentos, disse-lhes: "Todo reino dividido contra si mesmo será arruinado, e uma casa dividida contra si mesma cairá.

[[v42-11-18]]

^<<v42-11-18,18>>^ Se Satanás está dividido contra si mesmo, como o seu reino pode subsistir? Digo isso porque vocês estão dizendo que expulso demônios por Belzebu.

[[v42-11-19]]

^<<v42-11-19,19>>^ Se eu expulso demônios por Belzebu, por quem os expulsam os filhos de vocês? Por isso, eles mesmos estarão como juízes sobre vocês.

[[v42-11-20]]

^<<v42-11-20,20>>^ Mas se é pelo dedo de Deus que eu expulso demônios, então chegou a vocês o Reino de Deus.

[[v42-11-21]]

^<<v42-11-21,21>>^ "Quando um homem forte, bem armado, guarda sua casa, seus bens estão seguros.

[[v42-11-22]]

^<<v42-11-22,22>>^ Mas quando alguém mais forte o ataca e vence, tira-lhe a armadura em que confiava e divide os despojos.

[[v42-11-23]]

^<<v42-11-23,23>>^ "Aquele que não está comigo é contra mim, e aquele que comigo não ajunta, espalha.

[[v42-11-24]]

^<<v42-11-24,24>>^ "Quando um espírito imundo sai de um homem, passa por lugares áridos procurando descanso, e não o encontrando, diz: ‘Voltarei para a casa de onde saí’.

[[v42-11-25]]

^<<v42-11-25,25>>^ Quando chega, encontra a casa varrida e em ordem.

[[v42-11-26]]

^<<v42-11-26,26>>^ Então vai e traz outros sete espíritos piores do que ele, e entrando passam a viver ali. E o estado final daquele homem torna-se pior do que o primeiro".

[[v42-11-27]]

^<<v42-11-27,27>>^ Quando Jesus dizia estas coisas, uma mulher da multidão exclamou: "Feliz é a mulher que te deu à luz e te amamentou".

[[v42-11-28]]

^<<v42-11-28,28>>^ Ele respondeu: "Antes, felizes são aqueles que ouvem a palavra de Deus e lhe obedecem".

[[v42-11-29]]

^<<v42-11-29,29>>^ Aumentando a multidão, Jesus começou a dizer: "Esta é uma geração perversa. Ela pede um sinal miraculoso, mas nenhum sinal lhe será dado, exceto o sinal de Jonas.

[[v42-11-30]]

^<<v42-11-30,30>>^ Pois assim como Jonas foi um sinal para os ninivitas, o Filho do homem também o será para esta geração.

[[v42-11-31]]

^<<v42-11-31,31>>^ A rainha do Sul se levantará no juízo com os homens desta geração e os condenará, pois ela veio dos confins da terra para ouvir a sabedoria de Salomão, e agora está aqui o que é maior do que Salomão.

[[v42-11-32]]

^<<v42-11-32,32>>^ Os homens de Nínive se levantarão no juízo com esta geração e a condenarão; pois eles se arrependeram com a pregação de Jonas, e agora está aqui o que é maior do que Jonas".

[[v42-11-33]]

^<<v42-11-33,33>>^ "Ninguém acende uma candeia e a coloca em lugar onde fique escondida ou debaixo de uma vasilha. Pelo contrário, coloca-a no lugar apropriado, para que os que entram possam ver a luz.

[[v42-11-34]]

^<<v42-11-34,34>>^ Os olhos são a candeia do corpo. Quando os seus olhos forem bons, igualmente todo o seu corpo estará cheio de luz. Mas quando forem maus, igualmente o seu corpo estará cheio de trevas.

[[v42-11-35]]

^<<v42-11-35,35>>^ Portanto, cuidado para que a luz que está em seu interior não sejam trevas.

[[v42-11-36]]

^<<v42-11-36,36>>^ Logo, se todo o seu corpo estiver cheio de luz, e nenhuma parte dele estiver em trevas, estará completamente iluminado, como quando a luz de uma candeia brilha sobre você".

[[v42-11-37]]

^<<v42-11-37,37>>^ Tendo terminado de falar, um fariseu o convidou para comer com ele. Então Jesus foi, e reclinou-se à mesa;

[[v42-11-38]]

^<<v42-11-38,38>>^ mas o fariseu, notando que Jesus não se lavara cerimonialmente antes da refeição, ficou surpreso.

[[v42-11-39]]

^<<v42-11-39,39>>^ Então o Senhor lhe disse: "Vocês, fariseus, limpam o exterior do copo e do prato, mas interiormente estão cheios de ganância e da maldade.

[[v42-11-40]]

^<<v42-11-40,40>>^ Insensatos! Quem fez o exterior não fez também o interior?

[[v42-11-41]]

^<<v42-11-41,41>>^ Mas dêem o que está dentro do prato como esmola, e verão que tudo lhes ficará limpo.

[[v42-11-42]]

^<<v42-11-42,42>>^ "Ai de vocês, fariseus, porque dão a Deus o dízimo da hortelã, da arruda e de toda a sorte de hortaliças, mas desprezam a justiça e o amor de Deus! Vocês deviam praticar estas coisas, sem deixar de fazer aquelas.

[[v42-11-43]]

^<<v42-11-43,43>>^ "Ai de vocês, fariseus, porque amam os lugares de honra nas sinagogas e as saudações em público!

[[v42-11-44]]

^<<v42-11-44,44>>^ "Ai de vocês, porque são como túmulos que não se vêem, por sobre os quais os homens andam sem o saber! "

[[v42-11-45]]

^<<v42-11-45,45>>^ Um dos peritos na lei lhe respondeu: "Mestre, quando dizes essas coisas, insultas também a nós".

[[v42-11-46]]

^<<v42-11-46,46>>^ "Quanto a vocês, peritos na lei", disse Jesus, "ai de vocês também! porque sobrecarregam os homens com fardos que dificilmente eles podem carregar, e vocês mesmos não levantam nem um dedo para ajudá-los.

[[v42-11-47]]

^<<v42-11-47,47>>^ "Ai de vocês, porque edificam os túmulos dos profetas, sendo que foram os seus próprios antepassados que os mataram.

[[v42-11-48]]

^<<v42-11-48,48>>^ Assim vocês dão testemunho de que aprovam o que os seus antepassados fizeram. Eles mataram os profetas, e vocês lhes edificam os túmulos.

[[v42-11-49]]

^<<v42-11-49,49>>^ Por isso, Deus disse em sua sabedoria: ‘Eu lhes mandarei profetas e apóstolos, dos quais eles matarão alguns, e a outros perseguirão’.

[[v42-11-50]]

^<<v42-11-50,50>>^ Pelo que, esta geração será considerada responsável pelo sangue de todos os profetas, derramado desde o princípio do mundo:

[[v42-11-51]]

^<<v42-11-51,51>>^ desde o sangue de Abel até o sangue de Zacarias, que foi morto entre o altar e o santuário. Sim, eu lhes digo, esta geração será considerada responsável por tudo isso.

[[v42-11-52]]

^<<v42-11-52,52>>^ "Ai de vocês, peritos na lei, porque se apoderaram da chave do conhecimento. Vocês mesmos não entraram e impediram os que estavam prestes a entrar! "

[[v42-11-53]]

^<<v42-11-53,53>>^ Quando Jesus saiu dali, os fariseus e os mestres da lei começaram a opor-se fortemente a ele e a interrogá-lo com muitas perguntas,

[[v42-11-54]]

^<<v42-11-54,54>>^ esperando apanhá-lo em algo que dissesse.

'''

xref:042-lucas/042-lucas-010.adoc#v42-10-0[&#60; Capítulo Anterior] | <<v42-11-0,Topo>> | xref:042-lucas/042-lucas-012.adoc#v42-12-0[Próximo Capítulo &#62;]