include::./index.adoc[]

[[v42-6-0]]
=== Lucas, 6
// nvi ?, NVI - Nova Versão Internacional

[[v42-6-1]]

^<<v42-6-1,1>>^ Certo sábado, enquanto Jesus passava pelas lavouras de cereal, seus discípulos começaram a colher e a debulhar espigas com as mãos, comendo os grãos.

[[v42-6-2]]

^<<v42-6-2,2>>^ Alguns fariseus perguntaram: "Por que vocês estão fazendo o que não é permitido no sábado? "

[[v42-6-3]]

^<<v42-6-3,3>>^ Jesus lhes respondeu: "Vocês nunca leram o que fez Davi, quando ele e seus companheiros estavam com fome?

[[v42-6-4]]

^<<v42-6-4,4>>^ Ele entrou na casa de Deus e, tomando os pães da Presença, comeu o que apenas aos sacerdotes era permitido comer, e os deu também aos seus companheiros".

[[v42-6-5]]

^<<v42-6-5,5>>^ E então lhes disse: "O Filho do homem é Senhor do sábado".

[[v42-6-6]]

^<<v42-6-6,6>>^ Noutro sábado, ele entrou na sinagoga e começou a ensinar; estava ali um homem cuja mão direita era atrofiada.

[[v42-6-7]]

^<<v42-6-7,7>>^ Os fariseus e os mestres da lei estavam procurando um motivo para acusar Jesus; por isso o observavam atentamente, para ver se ele iria curá-lo no sábado.

[[v42-6-8]]

^<<v42-6-8,8>>^ Mas Jesus sabia o que eles estavam pensando e disse ao homem da mão atrofiada: "Levante-se e venha para o meio". Ele se levantou e foi.

[[v42-6-9]]

^<<v42-6-9,9>>^ Jesus lhes disse: "Eu lhes pergunto: o que é permitido fazer no sábado: o bem ou o mal, salvar a vida ou destruí-la? "

[[v42-6-10]]

^<<v42-6-10,10>>^ Então, olhou para todos os que estavam à sua volta e disse ao homem: "Estenda a mão". Ele a estendeu, e ela foi restaurada.

[[v42-6-11]]

^<<v42-6-11,11>>^ Mas eles ficaram furiosos e começaram a discutir entre si o que poderiam fazer contra Jesus.

[[v42-6-12]]

^<<v42-6-12,12>>^ Num daqueles dias, Jesus saiu para o monte a fim de orar, e passou a noite orando a Deus.

[[v42-6-13]]

^<<v42-6-13,13>>^ Ao amanhecer, chamou seus discípulos e escolheu doze deles, a quem também designou como apóstolos:

[[v42-6-14]]

^<<v42-6-14,14>>^ Simão, a quem deu o nome de Pedro; seu irmão André; Tiago; João; Filipe; Bartolomeu;

[[v42-6-15]]

^<<v42-6-15,15>>^ Mateus; Tomé; Tiago, filho de Alfeu; Simão, chamado zelote;

[[v42-6-16]]

^<<v42-6-16,16>>^ Judas, filho de Tiago; e Judas Iscariotes, que veio a ser o traidor.

[[v42-6-17]]

^<<v42-6-17,17>>^ Jesus desceu com eles e parou num lugar plano. Estava ali muitos dos seus discípulos e imensa multidão procedente de toda a Judéia, de Jerusalém e do litoral de Tiro e de Sidom;

[[v42-6-18]]

^<<v42-6-18,18>>^ que vieram para ouvi-lo e serem curadas de suas doenças. Os que eram perturbados por espíritos imundos ficaram curados,

[[v42-6-19]]

^<<v42-6-19,19>>^ e todos procuravam tocar nele, porque dele saía poder que curava a todos.

[[v42-6-20]]

^<<v42-6-20,20>>^ Olhando para os seus discípulos, ele disse: "Bem-aventurados vocês os pobres, pois a vocês pertence o Reino de Deus.

[[v42-6-21]]

^<<v42-6-21,21>>^ Bem-aventurados vocês, que agora têm fome, pois serão satisfeitos. Bem-aventurados vocês, que agora choram, pois haverão de rir.

[[v42-6-22]]

^<<v42-6-22,22>>^ Bem-aventurados serão vocês, quando os odiarem, expulsarem e insultarem, e eliminarem o nome de vocês, como sendo mau, por causa do Filho do homem.

[[v42-6-23]]

^<<v42-6-23,23>>^ "Regozijem-se nesse dia e saltem de alegria, porque grande é a recompensa de vocês no céu. Pois assim os antepassados deles trataram os profetas.

[[v42-6-24]]

^<<v42-6-24,24>>^ "Mas ai de vocês, os ricos, pois já receberam sua consolação.

[[v42-6-25]]

^<<v42-6-25,25>>^ Ai de vocês, que agora têm fartura, porque passarão fome. Ai de vocês, que agora riem, pois haverão de se lamentar e chorar.

[[v42-6-26]]

^<<v42-6-26,26>>^ Ai de vocês, quando todos falarem bem de vocês, pois assim os antepassados deles trataram os falsos profetas".

[[v42-6-27]]

^<<v42-6-27,27>>^ "Mas eu digo a vocês que estão me ouvindo: Amem os seus inimigos, façam o bem aos que os odeiam,

[[v42-6-28]]

^<<v42-6-28,28>>^ abençoem os que os amaldiçoam, orem por aqueles que os maltratam.

[[v42-6-29]]

^<<v42-6-29,29>>^ Se alguém lhe bater numa face, ofereça-lhe também a outra. Se alguém lhe tirar a capa, não o impeça de tirar-lhe a túnica.

[[v42-6-30]]

^<<v42-6-30,30>>^ Dê a todo o que lhe pedir, e se alguém tirar o que pertence a você, não lhe exija que o devolva.

[[v42-6-31]]

^<<v42-6-31,31>>^ Como vocês querem que os outros lhes façam, façam também vocês a eles.

[[v42-6-32]]

^<<v42-6-32,32>>^ "Que mérito vocês terão, se amarem aos que os amam? Até os ‘pecadores’ amam aos que os amam.

[[v42-6-33]]

^<<v42-6-33,33>>^ E que mérito terão, se fizerem o bem àqueles que são bons para com vocês? Até os ‘pecadores’ agem assim.

[[v42-6-34]]

^<<v42-6-34,34>>^ E que mérito terão, se emprestarem a pessoas de quem esperam devolução? Até os ‘pecadores’ emprestam a ‘pecadores’, esperando receber devolução integral.

[[v42-6-35]]

^<<v42-6-35,35>>^ Amem, porém, os seus inimigos, façam-lhes o bem e emprestem a eles, sem esperar receber nada de volta. Então, a recompensa que terão será grande e vocês serão filhos do Altíssimo, porque ele é bondoso para com os ingratos e maus.

[[v42-6-36]]

^<<v42-6-36,36>>^ Sejam misericordiosos, assim como o Pai de vocês é misericordioso".

[[v42-6-37]]

^<<v42-6-37,37>>^ "Não julguem, e vocês não serão julgados. Não condenem, e não serão condenados. Perdoem, e serão perdoados.

[[v42-6-38]]

^<<v42-6-38,38>>^ Dêem, e lhes será dado: uma boa medida, calcada, sacudida e transbordante será dada a vocês. Pois a medida que usarem, também será usada para medir vocês".

[[v42-6-39]]

^<<v42-6-39,39>>^ Jesus fez também a seguinte comparação: "Pode um cego guiar outro cego? Não cairão os dois no buraco?

[[v42-6-40]]

^<<v42-6-40,40>>^ O discípulo não está acima do seu mestre, mas todo aquele que for bem preparado será como o seu mestre.

[[v42-6-41]]

^<<v42-6-41,41>>^ "Por que você repara no cisco que está no olho do seu irmão e não se dá conta da viga que está em seu próprio olho?

[[v42-6-42]]

^<<v42-6-42,42>>^ Como você pode dizer ao seu irmão: ‘Irmão, deixe-me tirar o cisco do seu olho’, se você mesmo não consegue ver a viga que está em seu próprio olho? Hipócrita, tire primeiro a viga do seu olho, e então você verá claramente para tirar o cisco do olho do seu irmão".

[[v42-6-43]]

^<<v42-6-43,43>>^ "Nenhuma árvore boa dá fruto ruim, nenhuma árvore ruim dá fruto bom.

[[v42-6-44]]

^<<v42-6-44,44>>^ Toda árvore é reconhecida por seus frutos. Ninguém colhe figos de espinheiros, nem uvas de ervas daninhas.

[[v42-6-45]]

^<<v42-6-45,45>>^ O homem bom tira coisas boas do bom tesouro que está em seu coração, e o homem mau tira coisas más do mal que está em seu coração, porque a sua boca fala do que está cheio o coração".

[[v42-6-46]]

^<<v42-6-46,46>>^ "Por que vocês me chamam ‘Senhor, Senhor’ e não fazem o que eu digo?

[[v42-6-47]]

^<<v42-6-47,47>>^ Eu lhes mostrarei a que se compara aquele que vem a mim, ouve as minhas palavras e as pratica.

[[v42-6-48]]

^<<v42-6-48,48>>^ É como um homem que, ao construir uma casa, cavou fundo e colocou os alicerces na rocha. Quando veio a inundação, a torrente deu contra aquela casa, mas não a conseguiu abalar, porque estava bem construída.

[[v42-6-49]]

^<<v42-6-49,49>>^ Mas aquele que ouve as minhas palavras e não as pratica, é como um homem que construiu uma casa sobre o chão, sem alicerces. No momento em que a torrente deu contra aquela casa, ela caiu, e a sua destruição foi completa".

'''

xref:042-lucas/042-lucas-005.adoc#v42-5-0[&#60; Capítulo Anterior] | <<v42-6-0,Topo>> | xref:042-lucas/042-lucas-007.adoc#v42-7-0[Próximo Capítulo &#62;]