include::./index.adoc[]

[[v42-3-0]]
=== Lucas, 3
// nvi ?, NVI - Nova Versão Internacional

[[v42-3-1]]

^<<v42-3-1,1>>^ No décimo quinto ano do reinado de Tibério César, quando Pôncio Pilatos era governador da Judéia; Herodes, tetrarca da Galiléia; seu irmão Filipe, tetrarca da Ituréia e Traconites; e Lisânias, tetrarca de Abilene;

[[v42-3-2]]

^<<v42-3-2,2>>^ Anás e Caifás exerciam o sumo sacerdócio. Foi nesse ano que veio a palavra do Senhor a João, filho de Zacarias, no deserto.

[[v42-3-3]]

^<<v42-3-3,3>>^ Ele percorreu toda a região próxima ao Jordão, pregando um batismo de arrependimento para o perdão dos pecados.

[[v42-3-4]]

^<<v42-3-4,4>>^ Como está escrito no livro das palavras de Isaías, o profeta: "Voz do que clama no deserto: ‘Preparem o caminho para o Senhor, façam veredas retas para ele.

[[v42-3-5]]

^<<v42-3-5,5>>^ Todo vale será aterrado e todas as montanhas e colinas, niveladas. As estradas tortuosas serão endireitadas e os caminhos acidentados, aplanados.

[[v42-3-6]]

^<<v42-3-6,6>>^ E toda a humanidade verá a salvação de Deus’".

[[v42-3-7]]

^<<v42-3-7,7>>^ João dizia às multidões que saíam para serem batizadas por ele: "Raça de víboras! Quem lhes deu a idéia de fugir da ira que se aproxima?

[[v42-3-8]]

^<<v42-3-8,8>>^ Dêem frutos que mostrem o arrependimento. E não comecem a dizer a si mesmos: ‘Abraão é nosso pai’. Pois eu lhes digo que destas pedras Deus pode fazer surgir filhos a Abraão.

[[v42-3-9]]

^<<v42-3-9,9>>^ O machado já está posto à raiz das árvores, e toda árvore que não der bom fruto será cortada e lançada ao fogo".

[[v42-3-10]]

^<<v42-3-10,10>>^ "O que devemos fazer então? ", perguntavam as multidões.

[[v42-3-11]]

^<<v42-3-11,11>>^ João respondia: "Quem tem duas túnicas reparta-as com quem não tem nenhuma; e quem tem comida faça o mesmo".

[[v42-3-12]]

^<<v42-3-12,12>>^ Alguns publicanos também vieram para serem batizados. Eles perguntaram: "Mestre, o que devemos fazer? "

[[v42-3-13]]

^<<v42-3-13,13>>^ Ele respondeu: "Não cobrem nada além do que lhes foi estipulado".

[[v42-3-14]]

^<<v42-3-14,14>>^ Então alguns soldados lhe perguntaram: "E nós, o que devemos fazer? " Ele respondeu: "Não pratiquem extorsão nem acusem ninguém falsamente; contentem-se com o seu salário".

[[v42-3-15]]

^<<v42-3-15,15>>^ O povo estava em grande expectativa, questionando em seus corações se acaso João não seria o Cristo.

[[v42-3-16]]

^<<v42-3-16,16>>^ João respondeu a todos: "Eu os batizo com água. Mas virá alguém mais poderoso do que eu, tanto que não sou digno nem de curvar-me e desamarrar as correias das suas sandálias. Ele os batizará com o Espírito Santo e com fogo.

[[v42-3-17]]

^<<v42-3-17,17>>^ Ele traz a pá em sua mão, a fim de limpar sua eira e juntar o trigo em seu celeiro; mas queimará a palha com fogo que nunca se apaga".

[[v42-3-18]]

^<<v42-3-18,18>>^ E com muitas outras palavras João exortava o povo e lhe pregava as boas novas.

[[v42-3-19]]

^<<v42-3-19,19>>^ Todavia, quando João repreendeu Herodes, o tetrarca, por causa de Herodias, mulher do próprio irmão de Herodes, e por todas as outras coisas más que ele tinha feito,

[[v42-3-20]]

^<<v42-3-20,20>>^ Herodes acrescentou a todas elas a de colocar João na prisão.

[[v42-3-21]]

^<<v42-3-21,21>>^ Quando todo o povo estava sendo batizado, também Jesus o foi. E, enquanto ele estava orando, o céu se abriu

[[v42-3-22]]

^<<v42-3-22,22>>^ e o Espírito Santo desceu sobre ele em forma corpórea, como pomba. Então veio do céu uma voz: "Tu és o meu Filho amado; em ti me agrado".

[[v42-3-23]]

^<<v42-3-23,23>>^ Jesus tinha cerca de trinta anos de idade quando começou seu ministério. Ele era, como se pensava, filho de José, filho de Eli,

[[v42-3-24]]

^<<v42-3-24,24>>^ filho de Matate, filho de Levi, filho de Melqui, filho de Janai, filho de José,

[[v42-3-25]]

^<<v42-3-25,25>>^ filho de Matatias, filho de Amós, filho de Naum, filho de Esli, filho de Nagai,

[[v42-3-26]]

^<<v42-3-26,26>>^ filho de Maate, filho de Matatias, filho de Semei, filho de Joseque, filho de Jodá,

[[v42-3-27]]

^<<v42-3-27,27>>^ filho de Joanã, filho de Ressa, filho de Zorobabel, filho de Salatiel, filho de Neri,

[[v42-3-28]]

^<<v42-3-28,28>>^ filho de Melqui, filho de Adi, filho de Cosã, filho de Elmadã, filho de Er,

[[v42-3-29]]

^<<v42-3-29,29>>^ filho de Josué, filho de Eliézer, filho de Jorim, filho de Matate, filho de Levi,

[[v42-3-30]]

^<<v42-3-30,30>>^ filho de Simeão, filho de Judá, filho de José, filho de Jonã, filho de Eliaquim,

[[v42-3-31]]

^<<v42-3-31,31>>^ filho de Meleá, filho de Mená, filho de Matatá, filho de Natã, filho de Davi,

[[v42-3-32]]

^<<v42-3-32,32>>^ filho de Jessé, filho de Obede, filho de Boaz, filho de Salmom, filho de Naassom,

[[v42-3-33]]

^<<v42-3-33,33>>^ filho de Aminadabe, filho de Ram, filho de Esrom, filho de Perez, filho de Judá,

[[v42-3-34]]

^<<v42-3-34,34>>^ filho de Jacó, filho de Isaque, filho de Abraão, filho de Terá, filho de Naor,

[[v42-3-35]]

^<<v42-3-35,35>>^ filho de Serugue, filho de Ragaú, filho de Faleque, filho de Éber, filho de Salá,

[[v42-3-36]]

^<<v42-3-36,36>>^ filho de Cainã, filho de Arfaxade, filho de Sem, filho de Noé, filho de Lameque,

[[v42-3-37]]

^<<v42-3-37,37>>^ filho de Matusalém, filho de Enoque, filho de Jarede, filho de Maalaleel, filho de Cainã,

[[v42-3-38]]

^<<v42-3-38,38>>^ filho de Enos, filho de Sete, filho de Adão, filho de Deus.

'''

xref:042-lucas/042-lucas-002.adoc#v42-2-0[&#60; Capítulo Anterior] | <<v42-3-0,Topo>> | xref:042-lucas/042-lucas-004.adoc#v42-4-0[Próximo Capítulo &#62;]