include::./index.adoc[]

[[v42-14-0]]
=== Lucas, 14
// nvi ?, NVI - Nova Versão Internacional

[[v42-14-1]]

^<<v42-14-1,1>>^ Certo sábado, entrando Jesus para comer na casa de um fariseu importante, observavam-no atentamente.

[[v42-14-2]]

^<<v42-14-2,2>>^ À frente dele estava um homem doente, com o corpo inchado.

[[v42-14-3]]

^<<v42-14-3,3>>^ Jesus perguntou aos fariseus e peritos na lei: "É permitido ou não curar no sábado? "

[[v42-14-4]]

^<<v42-14-4,4>>^ Mas eles ficaram em silêncio. Assim, tomando o homem pela mão, Jesus o curou e o mandou embora.

[[v42-14-5]]

^<<v42-14-5,5>>^ Então ele lhes perguntou: "Se um de vocês tiver um filho ou um boi, e este cair num poço no dia de sábado, não irá tirá-lo imediatamente? "

[[v42-14-6]]

^<<v42-14-6,6>>^ E eles nada puderam responder.

[[v42-14-7]]

^<<v42-14-7,7>>^ Quando notou como os convidados escolhiam os lugares de honra à mesa, Jesus lhes contou esta parábola:

[[v42-14-8]]

^<<v42-14-8,8>>^ "Quando alguém o convidar para um banquete de casamento, não ocupe o lugar de honra, pois pode ser que tenha sido convidado alguém de maior honra do que você.

[[v42-14-9]]

^<<v42-14-9,9>>^ Se for assim, aquele que convidou os dois virá e lhe dirá: ‘Dê o lugar a este’. Então, humilhado, você precisará ocupar o lugar menos importante.

[[v42-14-10]]

^<<v42-14-10,10>>^ Mas quando você for convidado, ocupe o lugar menos importante, de forma que, quando vier aquele que o convidou, diga-lhe: ‘Amigo, passe para um lugar mais importante’. Então você será honrado na presença de todos os convidados.

[[v42-14-11]]

^<<v42-14-11,11>>^ Pois todo o que se exalta será humilhado, e o que se humilha será exaltado".

[[v42-14-12]]

^<<v42-14-12,12>>^ Então Jesus disse ao que o tinha convidado: "Quando você der um banquete ou jantar, não convide seus amigos, irmãos ou parentes, nem seus vizinhos ricos; se o fizer, eles poderão também, por sua vez, convidá-lo, e assim você será recompensado.

[[v42-14-13]]

^<<v42-14-13,13>>^ Mas, quando der um banquete, convide os pobres, os aleijados, os mancos, e os cegos.

[[v42-14-14]]

^<<v42-14-14,14>>^ Feliz será você, porque estes não têm como retribuir. A sua recompensa virá na ressurreição dos justos".

[[v42-14-15]]

^<<v42-14-15,15>>^ Ao ouvir isso, um dos que estavam à mesa com Jesus, disse-lhe: "Feliz será aquele que comer no banquete do Reino de Deus".

[[v42-14-16]]

^<<v42-14-16,16>>^ Jesus respondeu: "Certo homem estava preparando um grande banquete e convidou muitas pessoas.

[[v42-14-17]]

^<<v42-14-17,17>>^ Na hora de começar, enviou seu servo para dizer aos que haviam sido convidados: ‘Venham, pois tudo já está pronto’.

[[v42-14-18]]

^<<v42-14-18,18>>^ "Mas eles começaram, um por um, a apresentar desculpas. O primeiro disse: ‘Acabei de comprar uma propriedade, e preciso ir vê-la. Por favor, desculpe-me’.

[[v42-14-19]]

^<<v42-14-19,19>>^ "Outro disse: ‘Acabei de comprar cinco juntas de bois e estou indo experimentá-las. Por favor, desculpe-me’.

[[v42-14-20]]

^<<v42-14-20,20>>^ "Ainda outro disse: ‘Acabo de me casar, por isso não posso ir’.

[[v42-14-21]]

^<<v42-14-21,21>>^ "O servo voltou e relatou isso ao seu senhor. Então o dono da casa irou-se e ordenou ao seu servo: ‘Vá rapidamente para as ruas e becos da cidade e traga os pobres, os aleijados, os cegos e os mancos’.

[[v42-14-22]]

^<<v42-14-22,22>>^ "Disse o servo: ‘O que o senhor ordenou foi feito, e ainda há lugar’.

[[v42-14-23]]

^<<v42-14-23,23>>^ "Então o senhor disse ao servo: ‘Vá pelos caminhos e valados e obrigue-os a entrar, para que a minha casa fique cheia.

[[v42-14-24]]

^<<v42-14-24,24>>^ Eu lhes digo: nenhum daqueles que foram convidados provará do meu banquete’ ".

[[v42-14-25]]

^<<v42-14-25,25>>^ Uma grande multidão ia acompanhando Jesus; este, voltando-se para ela, disse:

[[v42-14-26]]

^<<v42-14-26,26>>^ "Se alguém vem a mim e ama o seu pai, sua mãe, sua mulher, seus filhos, seus irmãos e irmãs, e até sua própria vida mais do que a mim, não pode ser meu discípulo.

[[v42-14-27]]

^<<v42-14-27,27>>^ E aquele que não carrega sua cruz e não me segue não pode ser meu discípulo.

[[v42-14-28]]

^<<v42-14-28,28>>^ "Qual de vocês, se quiser construir uma torre, primeiro não se assenta e calcula o preço, para ver se tem dinheiro suficiente para completá-la?

[[v42-14-29]]

^<<v42-14-29,29>>^ Pois, se lançar o alicerce e não for capaz de terminá-la, todos os que a virem rirão dele,

[[v42-14-30]]

^<<v42-14-30,30>>^ dizendo: ‘Este homem começou a construir e não foi capaz de terminar’.

[[v42-14-31]]

^<<v42-14-31,31>>^ "Ou, qual é o rei que, pretendendo sair à guerra contra outro rei, primeiro não se assenta e pensa se com dez mil homens é capaz de enfrentar aquele que vem contra ele com vinte mil?

[[v42-14-32]]

^<<v42-14-32,32>>^ Se não for capaz, enviará uma delegação, enquanto o outro ainda está longe, e pedirá um acordo de paz.

[[v42-14-33]]

^<<v42-14-33,33>>^ Da mesma forma, qualquer de vocês que não renunciar a tudo o que possui não pode ser meu discípulo.

[[v42-14-34]]

^<<v42-14-34,34>>^ "O sal é bom, mas se ele perder o sabor, como restaurá-lo?

[[v42-14-35]]

^<<v42-14-35,35>>^ Não serve nem para o solo nem para adubo; é jogado fora. "Aquele que tem ouvidos para ouvir, ouça".

'''

xref:042-lucas/042-lucas-013.adoc#v42-13-0[&#60; Capítulo Anterior] | <<v42-14-0,Topo>> | xref:042-lucas/042-lucas-015.adoc#v42-15-0[Próximo Capítulo &#62;]