include::./index.adoc[]

[[v42-24-0]]
=== Lucas, 24
// nvi ?, NVI - Nova Versão Internacional

[[v42-24-1]]

^<<v42-24-1,1>>^ No primeiro dia da semana, de manhã bem cedo, as mulheres tomaram as especiarias aromáticas que haviam preparado e foram ao sepulcro.

[[v42-24-2]]

^<<v42-24-2,2>>^ Encontraram removida a pedra do sepulcro,

[[v42-24-3]]

^<<v42-24-3,3>>^ mas, quando entraram, não encontraram o corpo do Senhor Jesus.

[[v42-24-4]]

^<<v42-24-4,4>>^ Ficaram perplexas, sem saber o que fazer. De repente dois homens com roupas que brilhavam como a luz do sol colocaram-se ao lado delas.

[[v42-24-5]]

^<<v42-24-5,5>>^ Amedrontadas, as mulheres baixaram o rosto para o chão, e os homens lhes disseram: "Por que vocês estão procurando entre os mortos aquele que vive?

[[v42-24-6]]

^<<v42-24-6,6>>^ Ele não está aqui! Ressuscitou! Lembrem-se do que ele lhes disse, quando ainda estava com vocês na Galiléia:

[[v42-24-7]]

^<<v42-24-7,7>>^ ‘É necessário que o Filho do homem seja entregue nas mãos de homens pecadores, seja crucificado e ressuscite no terceiro dia’ ".

[[v42-24-8]]

^<<v42-24-8,8>>^ Então se lembraram das suas palavras.

[[v42-24-9]]

^<<v42-24-9,9>>^ Quando voltaram do sepulcro, elas contaram todas estas coisas aos Onze e a todos os outros.

[[v42-24-10]]

^<<v42-24-10,10>>^ As que contaram estas coisas aos apóstolos foram Maria Madalena, Joana e Maria, mãe de Tiago, e as outras que estavam com elas.

[[v42-24-11]]

^<<v42-24-11,11>>^ Mas eles não acreditaram nas mulheres; as palavras delas lhes pareciam loucura.

[[v42-24-12]]

^<<v42-24-12,12>>^ Pedro, todavia, levantou-se e correu ao sepulcro. Abaixando-se, viu as faixas de linho e mais nada; afastou-se, e voltou admirado com o que acontecera.

[[v42-24-13]]

^<<v42-24-13,13>>^ Naquele mesmo dia, dois deles estavam indo para um povoado chamado Emaús, a onze quilômetros de Jerusalém.

[[v42-24-14]]

^<<v42-24-14,14>>^ No caminho, conversavam a respeito de tudo o que havia acontecido.

[[v42-24-15]]

^<<v42-24-15,15>>^ Enquanto conversavam e discutiam, o próprio Jesus se aproximou e começou a caminhar com eles;

[[v42-24-16]]

^<<v42-24-16,16>>^ mas os olhos deles foram impedidos de reconhecê-lo.

[[v42-24-17]]

^<<v42-24-17,17>>^ Ele lhes perguntou: "Sobre o que vocês estão discutindo enquanto caminham? " Eles pararam, com os rostos entristecidos.

[[v42-24-18]]

^<<v42-24-18,18>>^ Um deles, chamado Cleopas, perguntou-lhe: "Você é o único visitante em Jerusalém que não sabe das coisas que ali aconteceram nestes dias? "

[[v42-24-19]]

^<<v42-24-19,19>>^ "Que coisas? ", perguntou ele. "O que aconteceu com Jesus de Nazaré", responderam eles. "Ele era um profeta, poderoso em palavras e em obras diante de Deus e de todo o povo.

[[v42-24-20]]

^<<v42-24-20,20>>^ Os chefes dos sacerdotes e as nossas autoridades o entregaram para ser condenado à morte, e o crucificaram;

[[v42-24-21]]

^<<v42-24-21,21>>^ e nós esperávamos que era ele que ia trazer a redenção a Israel. E hoje é o terceiro dia desde que tudo isso aconteceu.

[[v42-24-22]]

^<<v42-24-22,22>>^ Algumas das mulheres entre nós nos deram um susto hoje. Foram de manhã bem cedo ao sepulcro

[[v42-24-23]]

^<<v42-24-23,23>>^ e não acharam o corpo dele. Voltaram e nos contaram que tinham tido uma visão de anjos, que disseram que ele está vivo.

[[v42-24-24]]

^<<v42-24-24,24>>^ Alguns dos nossos companheiros foram ao sepulcro e encontraram tudo exatamente como as mulheres tinham dito, mas não o viram".

[[v42-24-25]]

^<<v42-24-25,25>>^ Ele lhes disse: "Como vocês custam a entender e como demoram a crer em tudo o que os profetas falaram!

[[v42-24-26]]

^<<v42-24-26,26>>^ Não devia o Cristo sofrer estas coisas, para entrar na sua glória? "

[[v42-24-27]]

^<<v42-24-27,27>>^ E começando por Moisés e todos os profetas, explicou-lhes o que constava a respeito dele em todas as Escrituras.

[[v42-24-28]]

^<<v42-24-28,28>>^ Ao se aproximarem do povoado para o qual estavam indo, Jesus fez como quem ia mais adiante.

[[v42-24-29]]

^<<v42-24-29,29>>^ Mas eles insistiram muito com ele: "Fique conosco, pois a noite já vem; o dia já está quase findando". Então, ele entrou para ficar com eles.

[[v42-24-30]]

^<<v42-24-30,30>>^ Quando estava à mesa com eles, tomou o pão, deu graças, partiu-o e o deu a eles.

[[v42-24-31]]

^<<v42-24-31,31>>^ Então os olhos deles foram abertos e o reconheceram, e ele desapareceu da vista deles.

[[v42-24-32]]

^<<v42-24-32,32>>^ Perguntaram-se um ao outro: "Não estavam ardendo os nossos corações dentro de nós, enquanto ele nos falava no caminho e nos expunha as Escrituras? "

[[v42-24-33]]

^<<v42-24-33,33>>^ Levantaram-se e voltaram imediatamente para Jesuralém. Ali encontraram os Onze e os que estavam com eles reunidos,

[[v42-24-34]]

^<<v42-24-34,34>>^ que diziam: "É verdade! O Senhor ressuscitou e apareceu a Simão! "

[[v42-24-35]]

^<<v42-24-35,35>>^ Então os dois contaram o que tinha acontecido no caminho, e como Jesus fora reconhecido por eles quando partia o pão.

[[v42-24-36]]

^<<v42-24-36,36>>^ Enquanto falavam sobre isso, o próprio Jesus apresentou-se entre eles e lhes disse: "Paz seja com vocês! "

[[v42-24-37]]

^<<v42-24-37,37>>^ Eles ficaram assustados e com medo, pensando que estavam vendo um espírito.

[[v42-24-38]]

^<<v42-24-38,38>>^ Ele lhes disse: "Por que vocês estão perturbados e por que se levantam dúvidas em seus corações?

[[v42-24-39]]

^<<v42-24-39,39>>^ Vejam as minhas mãos e os meus pés. Sou eu mesmo! Toquem-me e vejam; um espírito não tem carne nem ossos, como vocês estão vendo que eu tenho".

[[v42-24-40]]

^<<v42-24-40,40>>^ Tendo dito isso, mostrou-lhes as mãos e os pés.

[[v42-24-41]]

^<<v42-24-41,41>>^ E por não crerem ainda, tão cheios estavam de alegria e de espanto, ele lhes perguntou: "Vocês têm aqui algo para comer? "

[[v42-24-42]]

^<<v42-24-42,42>>^ Deram-lhe um pedaço de peixe assado,

[[v42-24-43]]

^<<v42-24-43,43>>^ e ele o comeu na presença deles.

[[v42-24-44]]

^<<v42-24-44,44>>^ E disse-lhes: "Foi isso que eu lhes falei enquanto ainda estava com vocês: Era necessário que se cumprisse tudo o que a meu respeito estava escrito na Lei de Moisés, nos Profetas e nos Salmos".

[[v42-24-45]]

^<<v42-24-45,45>>^ Então lhes abriu o entendimento, para que pudessem compreender as Escrituras.

[[v42-24-46]]

^<<v42-24-46,46>>^ E lhes disse: "Está escrito que o Cristo haveria de sofrer e ressuscitar dos mortos no terceiro dia,

[[v42-24-47]]

^<<v42-24-47,47>>^ e que em seu nome seria pregado o arrependimento para perdão de pecados a todas as nações, começando por Jerusalém.

[[v42-24-48]]

^<<v42-24-48,48>>^ Vocês são testemunhas destas coisas.

[[v42-24-49]]

^<<v42-24-49,49>>^ Eu lhes envio a promessa de meu Pai; mas fiquem na cidade até serem revestidos do poder do alto".

[[v42-24-50]]

^<<v42-24-50,50>>^ Tendo-os levado até as proximidades de Betânia, Jesus levantou as mãos e os abençoou.

[[v42-24-51]]

^<<v42-24-51,51>>^ Estando ainda a abençoá-los, ele os deixou e foi elevado ao céu.

[[v42-24-52]]

^<<v42-24-52,52>>^ Então eles o adoraram e voltaram para Jerusalém com grande alegria.

[[v42-24-53]]

^<<v42-24-53,53>>^ E permaneciam constantemente no templo, louvando a Deus.

'''

xref:042-lucas/042-lucas-023.adoc#v42-23-0[&#60; Capítulo Anterior] | <<v42-24-0,Topo>> | xref:043-joao/043-joao-001.adoc#v43-1-0[Próximo Capítulo &#62;]