include::./index.adoc[]

[[v42-16-0]]
=== Lucas, 16
// nvi ?, NVI - Nova Versão Internacional

[[v42-16-1]]

^<<v42-16-1,1>>^ Jesus disse aos seus discípulos: "O administrador de um homem rico foi acusado de estar desperdiçando os seus bens.

[[v42-16-2]]

^<<v42-16-2,2>>^ Então ele o chamou e lhe perguntou: ‘Que é isso que estou ouvindo a seu respeito? Preste contas da sua administração, porque você não pode continuar sendo o administrador’.

[[v42-16-3]]

^<<v42-16-3,3>>^ "O administrador disse a si mesmo: ‘Meu senhor está me despedindo. Que farei? Para cavar não tenho força, e tenho vergonha de mendigar...

[[v42-16-4]]

^<<v42-16-4,4>>^ Já sei o que vou fazer para que, quando perder o meu emprego aqui, as pessoas me recebam em suas casas’.

[[v42-16-5]]

^<<v42-16-5,5>>^ "Então chamou cada um dos devedores do seu senhor. Perguntou ao primeiro: ‘Quanto você deve ao meu senhor? ’

[[v42-16-6]]

^<<v42-16-6,6>>^ ‘Cem potes de azeite’, respondeu ele. "O administrador lhe disse: ‘Tome a sua conta, sente-se depressa e escreva cinqüenta’.

[[v42-16-7]]

^<<v42-16-7,7>>^ "A seguir ele perguntou ao segundo: ‘E você, quanto deve? ’ ‘Cem tonéis de trigo’, respondeu ele. "Ele lhe disse: ‘Tome a sua conta e escreva oitenta’.

[[v42-16-8]]

^<<v42-16-8,8>>^ "O senhor elogiou o administrador desonesto, porque agiu astutamente. Pois os filhos deste mundo são mais astutos no trato entre si do que os filhos da luz.

[[v42-16-9]]

^<<v42-16-9,9>>^ Por isso, eu lhes digo: usem a riqueza deste mundo ímpio para ganhar amigos, de forma que, quando ela acabar, estes os recebam nas moradas eternas.

[[v42-16-10]]

^<<v42-16-10,10>>^ "Quem é fiel no pouco, também é fiel no muito, e quem é desonesto no pouco, também é desonesto no muito.

[[v42-16-11]]

^<<v42-16-11,11>>^ Assim, se vocês não forem dignos de confiança em lidar com as riquezas deste mundo ímpio, quem lhes confiará as verdadeiras riquezas?

[[v42-16-12]]

^<<v42-16-12,12>>^ E se vocês não forem dignos de confiança em relação ao que é dos outros, quem lhes dará o que é de vocês?

[[v42-16-13]]

^<<v42-16-13,13>>^ "Nenhum servo pode servir a dois senhores; pois odiará a um e amará ao outro, ou se dedicará a um e desprezará ao outro. Vocês não podem servir a Deus e ao Dinheiro".

[[v42-16-14]]

^<<v42-16-14,14>>^ Os fariseus, que amavam o dinheiro, ouviam tudo isso e zombavam de Jesus.

[[v42-16-15]]

^<<v42-16-15,15>>^ Ele lhes disse: "Vocês são os que se justificam a si mesmos aos olhos dos homens, mas Deus conhece os corações de vocês. Aquilo que tem muito valor entre os homens é detestável aos olhos de Deus".

[[v42-16-16]]

^<<v42-16-16,16>>^ "A Lei e os Profetas profetizaram até João. Desse tempo em diante estão sendo pregadas as boas novas do Reino de Deus, e todos tentam forçar sua entrada nele.

[[v42-16-17]]

^<<v42-16-17,17>>^ É mais fácil o céu e a terra desaparecerem do que cair da Lei o menor traço.

[[v42-16-18]]

^<<v42-16-18,18>>^ "Quem se divorciar de sua mulher e se casar com outra mulher estará cometendo adultério, e o homem que se casar com uma mulher divorciada do seu marido estará cometendo adultério".

[[v42-16-19]]

^<<v42-16-19,19>>^ "Havia um homem rico que se vestia de púrpura e de linho fino e vivia no luxo todos os dias.

[[v42-16-20]]

^<<v42-16-20,20>>^ Diante do seu portão fora deixado um mendigo chamado Lázaro, coberto de chagas;

[[v42-16-21]]

^<<v42-16-21,21>>^ este ansiava comer o que caía da mesa do rico. Em vez disso, os cães vinham lamber as suas feridas.

[[v42-16-22]]

^<<v42-16-22,22>>^ "Chegou o dia em que o mendigo morreu, e os anjos o levaram para junto de Abraão. O rico também morreu e foi sepultado.

[[v42-16-23]]

^<<v42-16-23,23>>^ No Hades, onde estava sendo atormentado, ele olhou para cima e viu Abraão de longe, com Lázaro ao seu lado.

[[v42-16-24]]

^<<v42-16-24,24>>^ Então, chamou-o: ‘Pai Abraão, tem misericórdia de mim e manda que Lázaro molhe a ponta do dedo na água e refresque a minha língua, porque estou sofrendo muito neste fogo’.

[[v42-16-25]]

^<<v42-16-25,25>>^ "Mas Abraão respondeu: ‘Filho, lembre-se de que durante a sua vida você recebeu coisas boas, enquanto que Lázaro recebeu coisas más. Agora, porém, ele está sendo consolado aqui e você está em sofrimento.

[[v42-16-26]]

^<<v42-16-26,26>>^ E além disso, entre vocês e nós há um grande abismo, de forma que os que desejam passar do nosso lado para o seu, ou do seu lado para o nosso, não conseguem’.

[[v42-16-27]]

^<<v42-16-27,27>>^ "Ele respondeu: ‘Então eu lhe suplico, pai: manda Lázaro ir à casa de meu pai,

[[v42-16-28]]

^<<v42-16-28,28>>^ pois tenho cinco irmãos. Deixa que ele os avise, a fim de que eles não venham também para este lugar de tormento’.

[[v42-16-29]]

^<<v42-16-29,29>>^ "Abraão respondeu: ‘Eles têm Moisés e os Profetas; que os ouçam’.

[[v42-16-30]]

^<<v42-16-30,30>>^ " ‘Não, pai Abraão’, disse ele, ‘mas se alguém dentre os mortos fosse até eles, eles se arrependeriam’.

[[v42-16-31]]

^<<v42-16-31,31>>^ "Abraão respondeu: ‘Se não ouvem a Moisés e aos Profetas, tampouco se deixarão convencer, ainda que ressuscite alguém dentre os mortos’ ".

'''

xref:042-lucas/042-lucas-015.adoc#v42-15-0[&#60; Capítulo Anterior] | <<v42-16-0,Topo>> | xref:042-lucas/042-lucas-017.adoc#v42-17-0[Próximo Capítulo &#62;]