include::./index.adoc[]

[[v20-8-0]]
=== Provérbios, 8
// nvi ?, NVI - Nova Versão Internacional

[[v20-8-1]]

^<<v20-8-1,1>>^ A sabedoria está clamando, o discernimento ergue a sua voz;

[[v20-8-2]]

^<<v20-8-2,2>>^ nos lugares altos, junto ao caminho, nos cruzamentos ela se coloca;

[[v20-8-3]]

^<<v20-8-3,3>>^ ao lado das portas, à entrada da cidade, portas adentro, ela clama em alta voz:

[[v20-8-4]]

^<<v20-8-4,4>>^ "A vocês, homens, eu clamo; a todos levanto a minha voz.

[[v20-8-5]]

^<<v20-8-5,5>>^ Vocês, inexperientes, adquiram a prudência; e vocês, tolos, tenham bom senso.

[[v20-8-6]]

^<<v20-8-6,6>>^ Ouçam, pois tenho coisas importantes para dizer; os meus lábios falarão do que é certo.

[[v20-8-7]]

^<<v20-8-7,7>>^ Minha boca fala a verdade, pois a maldade causa repulsa aos meus lábios.

[[v20-8-8]]

^<<v20-8-8,8>>^ Todas as minhas palavras são justas; nenhuma delas é distorcida ou perversa.

[[v20-8-9]]

^<<v20-8-9,9>>^ Para os que têm discernimento, são todas claras, e retas para os que têm conhecimento.

[[v20-8-10]]

^<<v20-8-10,10>>^ Prefiram a minha instrução à prata, e o conhecimento ao ouro puro,

[[v20-8-11]]

^<<v20-8-11,11>>^ pois a sabedoria é mais preciosa do que rubis; nada do que vocês possam desejar compara-se a ela.

[[v20-8-12]]

^<<v20-8-12,12>>^ "Eu, a sabedoria, moro com a prudência, e tenho o conhecimento que vem do bom senso.

[[v20-8-13]]

^<<v20-8-13,13>>^ Temer ao Senhor é odiar o mal; odeio o orgulho e a arrogância, o mau comportamento e o falar perverso.

[[v20-8-14]]

^<<v20-8-14,14>>^ Meu é o conselho sensato; a mim pertencem o entendimento e o poder.

[[v20-8-15]]

^<<v20-8-15,15>>^ Por meu intermédio os reis governam, e as autoridades exercem a justiça;

[[v20-8-16]]

^<<v20-8-16,16>>^ também por meu intermédio governam os nobres, todos os juízes da terra.

[[v20-8-17]]

^<<v20-8-17,17>>^ Amo os que me amam, e quem me procura me encontra.

[[v20-8-18]]

^<<v20-8-18,18>>^ Comigo estão riquezas e honra, prosperidade e justiça duradouras.

[[v20-8-19]]

^<<v20-8-19,19>>^ Meu fruto é melhor do que o ouro, do que o ouro puro; o que ofereço é superior à prata escolhida.

[[v20-8-20]]

^<<v20-8-20,20>>^ Ando pelo caminho da retidão, pelas veredas da justiça,

[[v20-8-21]]

^<<v20-8-21,21>>^ concedendo riqueza aos que me amam e enchendo os seus tesouros.

[[v20-8-22]]

^<<v20-8-22,22>>^ "O Senhor me criou como o princípio de seu caminho, antes das suas obras mais antigas;

[[v20-8-23]]

^<<v20-8-23,23>>^ fui formada desde a eternidade, desde o princípio, antes de existir a terra.

[[v20-8-24]]

^<<v20-8-24,24>>^ Nasci quando ainda não havia abismos, quando não existiam fontes de águas;

[[v20-8-25]]

^<<v20-8-25,25>>^ antes de serem estabelecidos os montes e de existirem colinas eu nasci.

[[v20-8-26]]

^<<v20-8-26,26>>^ Ele ainda não havia feito a terra, nem os campos, nem o pó com o qual formou o mundo.

[[v20-8-27]]

^<<v20-8-27,27>>^ Quando ele estabeleceu os céus, lá estava eu, quando traçou o horizonte sobre a superfície do abismo,

[[v20-8-28]]

^<<v20-8-28,28>>^ quando colocou as nuvens em cima e estabeleceu as fontes do abismo,

[[v20-8-29]]

^<<v20-8-29,29>>^ quando determinou as fronteiras do mar para que as águas não violassem a sua ordem, quando marcou os limites dos alicerces da terra,

[[v20-8-30]]

^<<v20-8-30,30>>^ eu estava ao seu lado, e era o seu arquiteto; dia a dia eu era o seu prazer e me alegrava continuamente com a sua presença.

[[v20-8-31]]

^<<v20-8-31,31>>^ Eu me alegrava com o mundo que ele criou, e a humanidade me dava alegria.

[[v20-8-32]]

^<<v20-8-32,32>>^ "Ouçam-me agora, meus filhos: Como são felizes os que guardam os meus caminhos!

[[v20-8-33]]

^<<v20-8-33,33>>^ Ouçam a minha instrução, e serão sábios. Não a desprezem.

[[v20-8-34]]

^<<v20-8-34,34>>^ Como é feliz o homem que me ouve, vigiando diariamente à minha porta, esperando junto às portas da minha casa.

[[v20-8-35]]

^<<v20-8-35,35>>^ Pois todo aquele que me encontra, encontra a vida e recebe o favor do Senhor.

[[v20-8-36]]

^<<v20-8-36,36>>^ Mas aquele que de mim se afasta, a si mesmo se agride; todos os que me odeiam amam a morte".

'''

xref:020-proverbios/020-proverbios-007.adoc#v20-7-0[&#60; Capítulo Anterior] | <<v20-8-0,Topo>> | xref:020-proverbios/020-proverbios-009.adoc#v20-9-0[Próximo Capítulo &#62;]