include::./index.adoc[]

[[v20-16-0]]
=== Provérbios, 16
// nvi ?, NVI - Nova Versão Internacional

[[v20-16-1]]

^<<v20-16-1,1>>^ Ao homem pertencem os planos do coração, mas do Senhor vem a resposta da língua.

[[v20-16-2]]

^<<v20-16-2,2>>^ Todos os caminhos do homem lhe parecem puros, mas o Senhor avalia o espírito.

[[v20-16-3]]

^<<v20-16-3,3>>^ Consagre ao Senhor tudo o que você faz, e os seus planos serão bem-sucedidos.

[[v20-16-4]]

^<<v20-16-4,4>>^ O Senhor faz tudo com um propósito; até os ímpios para o dia do castigo.

[[v20-16-5]]

^<<v20-16-5,5>>^ O Senhor detesta os orgulhosos de coração. Sem dúvida serão punidos.

[[v20-16-6]]

^<<v20-16-6,6>>^ Com amor e fidelidade se faz expiação pelo pecado; com o temor do Senhor o homem evita o mal.

[[v20-16-7]]

^<<v20-16-7,7>>^ Quando os caminhos de um homem são agradáveis ao Senhor, ele faz que até os seus inimigos vivam em paz com ele.

[[v20-16-8]]

^<<v20-16-8,8>>^ É melhor ter pouco com retidão do que muito com injustiça.

[[v20-16-9]]

^<<v20-16-9,9>>^ Em seu coração o homem planeja o seu caminho, mas o Senhor determina os seus passos.

[[v20-16-10]]

^<<v20-16-10,10>>^ Os lábios do rei falam com grande autoridade; sua boca não deve trair a justiça.

[[v20-16-11]]

^<<v20-16-11,11>>^ Balanças e pesos honestos vêm do Senhor; todos os pesos da bolsa são feitos por ele.

[[v20-16-12]]

^<<v20-16-12,12>>^ Os reis detestam a prática da maldade, porquanto o trono se firma pela justiça.

[[v20-16-13]]

^<<v20-16-13,13>>^ O rei se agrada dos lábios honestos; e dá valor ao homem que fala a verdade.

[[v20-16-14]]

^<<v20-16-14,14>>^ A ira do rei é um mensageiro da morte, mas o homem sábio a acalmará.

[[v20-16-15]]

^<<v20-16-15,15>>^ Alegria no rosto do rei é sinal de vida; seu favor é como nuvem de chuva na primavera.

[[v20-16-16]]

^<<v20-16-16,16>>^ É melhor obter sabedoria do que ouro! É melhor obter entendimento do que prata!

[[v20-16-17]]

^<<v20-16-17,17>>^ A vereda do justo evita o mal; quem guarda o seu caminho preserva a sua vida.

[[v20-16-18]]

^<<v20-16-18,18>>^ O orgulho vem antes da destruição; o espírito altivo, antes da queda.

[[v20-16-19]]

^<<v20-16-19,19>>^ Melhor é ter espírito humilde entre os oprimidos do que partilhar despojos com os orgulhosos.

[[v20-16-20]]

^<<v20-16-20,20>>^ Quem examina cada questão com cuidado, prospera, e feliz é aquele que confia no Senhor.

[[v20-16-21]]

^<<v20-16-21,21>>^ O sábio de coração é considerado prudente; quem fala com equilíbrio promove a instrução.

[[v20-16-22]]

^<<v20-16-22,22>>^ O entendimento é fonte de vida para aqueles que o têm, mas a insensatez traz castigo aos insensatos.

[[v20-16-23]]

^<<v20-16-23,23>>^ O coração do sábio ensina a sua boca, e os seus lábios promovem a instrução.

[[v20-16-24]]

^<<v20-16-24,24>>^ As palavras agradáveis são como um favo de mel, são doces para a alma e trazem cura para os ossos.

[[v20-16-25]]

^<<v20-16-25,25>>^ Há caminho que parece reto ao homem, mas no final conduz à morte.

[[v20-16-26]]

^<<v20-16-26,26>>^ O apetite do trabalhador o obriga a trabalhar; a sua fome o impulsiona.

[[v20-16-27]]

^<<v20-16-27,27>>^ O homem sem caráter maquina o mal, suas palavras são um fogo devorador.

[[v20-16-28]]

^<<v20-16-28,28>>^ O homem perverso provoca dissensão, e o que espalha boatos afasta bons amigos.

[[v20-16-29]]

^<<v20-16-29,29>>^ O violento recruta o seu próximo e o leva por um caminho ruim.

[[v20-16-30]]

^<<v20-16-30,30>>^ Quem pisca os olhos planeja o mal; quem franze os lábios já o vai praticar.

[[v20-16-31]]

^<<v20-16-31,31>>^ O cabelo grisalho é uma coroa de esplendor, e se obtém mediante uma vida justa.

[[v20-16-32]]

^<<v20-16-32,32>>^ Melhor é o homem paciente do que o guerreiro, mais vale controlar o seu espírito do que conquistar uma cidade.

[[v20-16-33]]

^<<v20-16-33,33>>^ A sorte é lançada no colo, mas a decisão vem do Senhor.

'''

xref:020-proverbios/020-proverbios-015.adoc#v20-15-0[&#60; Capítulo Anterior] | <<v20-16-0,Topo>> | xref:020-proverbios/020-proverbios-017.adoc#v20-17-0[Próximo Capítulo &#62;]