include::./index.adoc[]

[[v20-24-0]]
=== Provérbios, 24
// nvi ?, NVI - Nova Versão Internacional

[[v20-24-1]]

^<<v20-24-1,1>>^ Não tenha inveja dos ímpios, nem deseje a companhia deles;

[[v20-24-2]]

^<<v20-24-2,2>>^ pois destruição é o que planejam no coração, e só falam de violência.

[[v20-24-3]]

^<<v20-24-3,3>>^ Com sabedoria se constrói a casa, e com discernimento se consolida.

[[v20-24-4]]

^<<v20-24-4,4>>^ Pelo conhecimento os seus cômodos se enchem do que é precioso e agradável.

[[v20-24-5]]

^<<v20-24-5,5>>^ O homem sábio é poderoso, e quem tem conhecimento aumenta a sua força;

[[v20-24-6]]

^<<v20-24-6,6>>^ quem sai à guerra precisa de orientação, e com muitos conselheiros se obtém a vitória.

[[v20-24-7]]

^<<v20-24-7,7>>^ A sabedoria é elevada demais para o insensato; ele não sabe o que dizer nas assembléias.

[[v20-24-8]]

^<<v20-24-8,8>>^ Quem maquina o mal será conhecido como criador de intrigas.

[[v20-24-9]]

^<<v20-24-9,9>>^ A intriga do insensato é pecado, e o zombador é detestado pelos homens.

[[v20-24-10]]

^<<v20-24-10,10>>^ Se você vacila no dia da dificuldade, como será limitada a sua força!

[[v20-24-11]]

^<<v20-24-11,11>>^ Liberte os que estão sendo levados para a morte; socorra os que caminham trêmulos para a matança!

[[v20-24-12]]

^<<v20-24-12,12>>^ Mesmo que você diga: "Não sabíamos o que estava acontecendo! " Não o perceberia aquele que pesa os corações? Não o saberia aquele que preserva a sua vida? Não retribuirá ele a cada um segundo o seu procedimento?

[[v20-24-13]]

^<<v20-24-13,13>>^ Coma mel, meu filho. É bom. O favo é doce ao paladar.

[[v20-24-14]]

^<<v20-24-14,14>>^ Saiba que a sabedoria também será boa para a sua alma; se você a encontrar, certamente haverá futuro para você, e a sua esperança não vai decepcioná-lo.

[[v20-24-15]]

^<<v20-24-15,15>>^ Não fique de tocaia, como faz o ímpio, contra a casa do justo, e não destrua o seu local de repouso;

[[v20-24-16]]

^<<v20-24-16,16>>^ pois ainda que o justo caia sete vezes, tornará a erguer-se, mas os ímpios são arrastados pela calamidade.

[[v20-24-17]]

^<<v20-24-17,17>>^ Não se alegre quando o seu inimigo cair, nem exulte o seu coração quando ele tropeçar,

[[v20-24-18]]

^<<v20-24-18,18>>^ para que o Senhor não veja isso, e se desagrade, e desvie dele a sua ira.

[[v20-24-19]]

^<<v20-24-19,19>>^ Não se aborreça por causa dos maus, nem tenha inveja dos ímpios,

[[v20-24-20]]

^<<v20-24-20,20>>^ pois não há futuro para o mau, e a lâmpada dos ímpios se apagará.

[[v20-24-21]]

^<<v20-24-21,21>>^ Tema ao Senhor e ao rei, meu filho, e não se associe aos dissidentes,

[[v20-24-22]]

^<<v20-24-22,22>>^ pois terão repentina destruição, e quem pode imaginar a ruína que o Senhor e o rei podem causar?

[[v20-24-23]]

^<<v20-24-23,23>>^ Aqui vão outros ditados dos sábios: Agir com parcialidade nos julgamentos não é nada bom.

[[v20-24-24]]

^<<v20-24-24,24>>^ Quem disser ao ímpio: "Você é justo", será amaldiçoado pelos povos e sofrerá a indignação das nações.

[[v20-24-25]]

^<<v20-24-25,25>>^ Mas os que condenam o culpado terão vida agradável; receberão grandes bênçãos.

[[v20-24-26]]

^<<v20-24-26,26>>^ A resposta sincera é como beijo nos lábios.

[[v20-24-27]]

^<<v20-24-27,27>>^ Termine primeiro o seu trabalho a céu aberto; deixe pronta a sua lavoura. Depois constitua família.

[[v20-24-28]]

^<<v20-24-28,28>>^ Não testemunhe sem motivo contra o seu próximo nem use os seus lábios para enganá-lo.

[[v20-24-29]]

^<<v20-24-29,29>>^ Não diga: "Farei com ele o que fez comigo; ele pagará pelo que fez".

[[v20-24-30]]

^<<v20-24-30,30>>^ Passei pelo campo do preguiçoso, pela vinha do homem sem juízo;

[[v20-24-31]]

^<<v20-24-31,31>>^ havia espinheiros por toda parte, o chão estava coberto de ervas daninhas e o muro de pedra estava em ruínas.

[[v20-24-32]]

^<<v20-24-32,32>>^ Observei aquilo, e fiquei pensando, olhei e aprendi esta lição:

[[v20-24-33]]

^<<v20-24-33,33>>^ "Vou dormir um pouco", você diz. "Vou cochilar um momento; vou cruzar os braços e descansar mais um pouco",

[[v20-24-34]]

^<<v20-24-34,34>>^ mas a pobreza lhe virá como um assaltante, e a sua miséria como um homem armado.

'''

xref:020-proverbios/020-proverbios-023.adoc#v20-23-0[&#60; Capítulo Anterior] | <<v20-24-0,Topo>> | xref:020-proverbios/020-proverbios-025.adoc#v20-25-0[Próximo Capítulo &#62;]