include::./index.adoc[]

[[v20-31-0]]
=== Provérbios, 31
// nvi ?, NVI - Nova Versão Internacional

[[v20-31-1]]

^<<v20-31-1,1>>^ Ditados do rei Lemuel; uma exortação que sua mãe lhe fez:

[[v20-31-2]]

^<<v20-31-2,2>>^ "Ó meu filho, filho do meu ventre, filho de meus votos,

[[v20-31-3]]

^<<v20-31-3,3>>^ não gaste sua força com mulheres, seu vigor com aquelas que destroem reis.

[[v20-31-4]]

^<<v20-31-4,4>>^ "Não convém aos reis, ó Lemuel; não convém aos reis beber vinho, não convém aos governantes desejar bebida fermentada,

[[v20-31-5]]

^<<v20-31-5,5>>^ para não suceder que bebam e se esqueçam do que a lei determina, e deixem de fazer justiça aos oprimidos.

[[v20-31-6]]

^<<v20-31-6,6>>^ Dê bebida fermentada aos que estão prestes a morrer, vinho aos que estão angustiados;

[[v20-31-7]]

^<<v20-31-7,7>>^ para que bebam e se esqueçam da sua pobreza, e não mais se lembrem da sua infelicidade.

[[v20-31-8]]

^<<v20-31-8,8>>^ "Erga a voz em favor dos que não podem defender-se, seja o defensor de todos os desamparados.

[[v20-31-9]]

^<<v20-31-9,9>>^ Erga a voz e julgue com justiça; defenda os direitos dos pobres e dos necessitados".

[[v20-31-10]]

^<<v20-31-10,10>>^ Uma esposa exemplar; feliz quem a encontrar! É muito mais valiosa que os rubis.

[[v20-31-11]]

^<<v20-31-11,11>>^ Seu marido tem plena confiança nela e nunca lhe falta coisa alguma.

[[v20-31-12]]

^<<v20-31-12,12>>^ Ela só lhe faz o bem, e nunca o mal, todos os dias da sua vida.

[[v20-31-13]]

^<<v20-31-13,13>>^ Escolhe a lã e o linho e com prazer trabalha com as mãos.

[[v20-31-14]]

^<<v20-31-14,14>>^ Como os navios mercantes, ela traz de longe as suas provisões.

[[v20-31-15]]

^<<v20-31-15,15>>^ Antes de clarear o dia ela se levanta, prepara comida para todos os de casa, e dá tarefas as suas servas.

[[v20-31-16]]

^<<v20-31-16,16>>^ Ela avalia um campo e o compra; com o que ganha planta uma vinha.

[[v20-31-17]]

^<<v20-31-17,17>>^ Entrega-se com vontade ao seu trabalho; seus braços são fortes e vigorosos.

[[v20-31-18]]

^<<v20-31-18,18>>^ Administra bem o seu comércio lucrativo, e a sua lâmpada fica acesa durante a noite.

[[v20-31-19]]

^<<v20-31-19,19>>^ Nas mãos segura o fuso e com os dedos pega a roca.

[[v20-31-20]]

^<<v20-31-20,20>>^ Acolhe os necessitados e estende as mãos aos pobres.

[[v20-31-21]]

^<<v20-31-21,21>>^ Não receia a neve por seus familiares, pois todos eles vestem agasalhos.

[[v20-31-22]]

^<<v20-31-22,22>>^ Faz cobertas para a sua cama; veste-se de linho fino e de púrpura.

[[v20-31-23]]

^<<v20-31-23,23>>^ Seu marido é respeitado na porta da cidade, onde toma assento entre as autoridades da sua terra.

[[v20-31-24]]

^<<v20-31-24,24>>^ Ela faz vestes de linho e as vende, e fornece cintos aos comerciantes.

[[v20-31-25]]

^<<v20-31-25,25>>^ Reveste-se de força e dignidade; sorri diante do futuro.

[[v20-31-26]]

^<<v20-31-26,26>>^ Fala com sabedoria e ensina com amor.

[[v20-31-27]]

^<<v20-31-27,27>>^ Cuida dos negócios de sua casa e não dá lugar à preguiça.

[[v20-31-28]]

^<<v20-31-28,28>>^ Seus filhos se levantam e a elogiam; seu marido também a elogia, dizendo:

[[v20-31-29]]

^<<v20-31-29,29>>^ "Muitas mulheres são exemplares, mas você a todas supera".

[[v20-31-30]]

^<<v20-31-30,30>>^ A beleza é enganosa, e a formosura é passageira; mas a mulher que teme ao Senhor será elogiada.

[[v20-31-31]]

^<<v20-31-31,31>>^ Que ela receba a recompensa merecida, e as suas obras sejam elogiadas à porta da cidade.

'''

xref:020-proverbios/020-proverbios-030.adoc#v20-30-0[&#60; Capítulo Anterior] | <<v20-31-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-001.adoc#v21-1-0[Próximo Capítulo &#62;]