include::./index.adoc[]

[[v20-20-0]]
=== Provérbios, 20
// nvi ?, NVI - Nova Versão Internacional

[[v20-20-1]]

^<<v20-20-1,1>>^ O vinho é zombadore a bebida fermentada provoca brigas; não é sábio deixar-se dominar por eles.

[[v20-20-2]]

^<<v20-20-2,2>>^ O medo que o rei provoca é como o do rugido de um leão; quem o irrita põe em risco a própria vida.

[[v20-20-3]]

^<<v20-20-3,3>>^ É uma honra dar fim a contendas, mas todos insensatos envolvem-se nelas.

[[v20-20-4]]

^<<v20-20-4,4>>^ O preguiçoso não ara a terra na estação própria; mas na época da colheita procura, e não acha nada.

[[v20-20-5]]

^<<v20-20-5,5>>^ Os propósitos do coração do homem são águas profundas, mas quem tem discernimento os traz à tona.

[[v20-20-6]]

^<<v20-20-6,6>>^ Muitos se dizem amigos leais, mas um homem fiel, quem poderá achar?

[[v20-20-7]]

^<<v20-20-7,7>>^ O homem justo leva uma vida íntegra; como são felizes os seus filhos!

[[v20-20-8]]

^<<v20-20-8,8>>^ Quando o rei se assenta no trono para julgar, com o olhar esmiúça todo o mal.

[[v20-20-9]]

^<<v20-20-9,9>>^ Quem poderá dizer: "Purifiquei o coração; estou livre do meu pecado? "

[[v20-20-10]]

^<<v20-20-10,10>>^ Pesos adulterados e medidas falsificadas, são coisas que o Senhor detesta.

[[v20-20-11]]

^<<v20-20-11,11>>^ Até a criança mostra o que é por suas ações; o seu procedimento revelará se ela é pura e justa.

[[v20-20-12]]

^<<v20-20-12,12>>^ Os ouvidos que ouvem e os olhos que vêem foram feitos pelo Senhor.

[[v20-20-13]]

^<<v20-20-13,13>>^ Não ame o sono, ou você acabará ficando pobre; fique desperto, e terá alimento de sobra.

[[v20-20-14]]

^<<v20-20-14,14>>^ "Não vale isso! Não vale isso! ", diz o comprador, mas, quando se vai, gaba-se do bom negócio.

[[v20-20-15]]

^<<v20-20-15,15>>^ Mesmo onde há ouro e rubis em grande quantidade, os lábios que transmitem conhecimento são uma rara preciosidade.

[[v20-20-16]]

^<<v20-20-16,16>>^ Tome-se a veste de quem serve de fiador ao estranho; sirva ela de penhor de quem dá garantia a uma mulher leviana.

[[v20-20-17]]

^<<v20-20-17,17>>^ Saborosa é a comida que se obtém com mentiras, mas depois dá areia na boca.

[[v20-20-18]]

^<<v20-20-18,18>>^ Os conselhos são importantes para quem quiser fazer planos, e quem sai à guerra precisa de orientação.

[[v20-20-19]]

^<<v20-20-19,19>>^ Quem vive contando casos não guarda segredo; por isso, evite quem fala demais.

[[v20-20-20]]

^<<v20-20-20,20>>^ Se alguém amaldiçoar seu pai ou sua mãe, a luz de sua vida se extinguirá na mais profunda escuridão.

[[v20-20-21]]

^<<v20-20-21,21>>^ A herança que se obtém com ganância no princípio, no final não será abençoada.

[[v20-20-22]]

^<<v20-20-22,22>>^ Não diga: "Eu o farei pagar pelo mal que me fez! " Espere pelo Senhor, e ele dará a vitória a você.

[[v20-20-23]]

^<<v20-20-23,23>>^ O Senhor detesta pesos adulterados, e balanças falsificadas não o agradam.

[[v20-20-24]]

^<<v20-20-24,24>>^ Os passos do homem são dirigidos pelo Senhor. Como poderia alguém discernir o seu próprio caminho?

[[v20-20-25]]

^<<v20-20-25,25>>^ É uma armadilha consagrar algo precipitadamente, e só pensar nas conseqüências depois que se fez o voto.

[[v20-20-26]]

^<<v20-20-26,26>>^ O rei sábio abana os ímpios, e passa sobre eles a roda de debulhar.

[[v20-20-27]]

^<<v20-20-27,27>>^ O espírito do homem é a lâmpada do Senhor, e vasculha cada parte do seu ser.

[[v20-20-28]]

^<<v20-20-28,28>>^ A bondade e a fidelidade preservam o rei; por sua bondade ele dá firmeza ao seu trono.

[[v20-20-29]]

^<<v20-20-29,29>>^ A beleza dos jovens está na sua força; a glória dos idosos, nos seus cabelos brancos.

[[v20-20-30]]

^<<v20-20-30,30>>^ Os golpes e os ferimentos eliminam o mal; os açoites limpam as profundezas do ser.

'''

xref:020-proverbios/020-proverbios-019.adoc#v20-19-0[&#60; Capítulo Anterior] | <<v20-20-0,Topo>> | xref:020-proverbios/020-proverbios-021.adoc#v20-21-0[Próximo Capítulo &#62;]