include::./index.adoc[]

[[v20-21-0]]
=== Provérbios, 21
// nvi ?, NVI - Nova Versão Internacional

[[v20-21-1]]

^<<v20-21-1,1>>^ O coração do rei é como um rio controlado pelo Senhor; ele o dirige para onde quer.

[[v20-21-2]]

^<<v20-21-2,2>>^ Todos os caminhos do homem lhe parecem justos, mas o Senhor pesa o coração.

[[v20-21-3]]

^<<v20-21-3,3>>^ Fazer o que é justo e certo é mais aceitável ao Senhor do que oferecer sacrifícios.

[[v20-21-4]]

^<<v20-21-4,4>>^ A vida de pecado dos ímpios se vê no olhar orgulhoso e no coração arrogante,

[[v20-21-5]]

^<<v20-21-5,5>>^ Os planos bem elaborados levam à fartura; mas o apressado sempre acaba na miséria.

[[v20-21-6]]

^<<v20-21-6,6>>^ A fortuna obtida com língua mentirosa é ilusão fugidia e armadilha mortal.

[[v20-21-7]]

^<<v20-21-7,7>>^ A violência dos ímpios os arrastará, pois recusam-se a agir corretamente.

[[v20-21-8]]

^<<v20-21-8,8>>^ O caminho do culpado é tortuoso, mas a conduta do inocente é reta.

[[v20-21-9]]

^<<v20-21-9,9>>^ Melhor é viver num canto sob o telhado do que repartir a casa com uma mulher briguenta.

[[v20-21-10]]

^<<v20-21-10,10>>^ O desejo do perverso é fazer o mal; ele não tem dó do próximo.

[[v20-21-11]]

^<<v20-21-11,11>>^ Quando o zombador é castigado, o inexperiente obtém sabedoria; quando o sábio recebe instrução, obtém conhecimento.

[[v20-21-12]]

^<<v20-21-12,12>>^ O justo observa a casa dos ímpios e os faz cair na desgraça.

[[v20-21-13]]

^<<v20-21-13,13>>^ Quem fecha os ouvidos ao clamor dos pobres também clamará e não terá resposta.

[[v20-21-14]]

^<<v20-21-14,14>>^ O presente que se faz em segredo acalma a ira, e o suborno oferecido às ocultas apazigua a maior fúria.

[[v20-21-15]]

^<<v20-21-15,15>>^ Quando se faz justiça, o justo se alegra, mas os malfeitores se apavoram.

[[v20-21-16]]

^<<v20-21-16,16>>^ Quem se afasta do caminho da sensatez repousará na companhia dos mortos.

[[v20-21-17]]

^<<v20-21-17,17>>^ Quem se entrega aos prazeres passará necessidade; quem se apega ao vinho e ao azeite jamais será rico.

[[v20-21-18]]

^<<v20-21-18,18>>^ O ímpio serve de resgate para o justo, e o infiel, para o homem íntegro.

[[v20-21-19]]

^<<v20-21-19,19>>^ Melhor é viver no deserto do que com uma mulher briguenta e amargurada.

[[v20-21-20]]

^<<v20-21-20,20>>^ Na casa do sábio há comida e azeite armazenados, mas o tolo devora tudo o que pode.

[[v20-21-21]]

^<<v20-21-21,21>>^ Quem segue a justiça e a lealdade encontra vida, justiça e honra.

[[v20-21-22]]

^<<v20-21-22,22>>^ O sábio conquista a cidade dos valentes e derruba a fortaleza em que eles confiam.

[[v20-21-23]]

^<<v20-21-23,23>>^ Quem é cuidadoso no que fala evita muito sofrimento.

[[v20-21-24]]

^<<v20-21-24,24>>^ O vaidoso e arrogante, chama-se zombador; ele age com extremo orgulho.

[[v20-21-25]]

^<<v20-21-25,25>>^ O preguiçoso morre de tanto desejar e de nunca pôr as mãos no trabalho.

[[v20-21-26]]

^<<v20-21-26,26>>^ O dia inteiro ele deseja mais e mais, enquanto o justo reparte sem cessar.

[[v20-21-27]]

^<<v20-21-27,27>>^ O sacrifício dos ímpios já por si é detestável; quanto mais quando oferecido com más intenções.

[[v20-21-28]]

^<<v20-21-28,28>>^ A testemunha falsa perecerá, mas o testemunho do homem bem informado permanecerá.

[[v20-21-29]]

^<<v20-21-29,29>>^ O ímpio mostra no rosto a sua arrogância, mas o justo mantém em ordem o seu caminho.

[[v20-21-30]]

^<<v20-21-30,30>>^ Não há sabedoria alguma, nem discernimento algum, nem plano algum que possa opor-se ao Senhor.

[[v20-21-31]]

^<<v20-21-31,31>>^ Prepara-se o cavalo para o dia da batalha, mas o Senhor é que dá a vitória.

'''

xref:020-proverbios/020-proverbios-020.adoc#v20-20-0[&#60; Capítulo Anterior] | <<v20-21-0,Topo>> | xref:020-proverbios/020-proverbios-022.adoc#v20-22-0[Próximo Capítulo &#62;]