include::./index.adoc[]

[[v20-3-0]]
=== Provérbios, 3
// nvi ?, NVI - Nova Versão Internacional

[[v20-3-1]]

^<<v20-3-1,1>>^ Meu filho, não se esqueça da minha lei, mas guarde no coração os meus mandamentos,

[[v20-3-2]]

^<<v20-3-2,2>>^ pois eles prolongarão a sua vida por muitos anos e lhe darão prosperidade e paz.

[[v20-3-3]]

^<<v20-3-3,3>>^ Que o amor e a fidelidade jamais o abandonem; prenda-os ao redor do seu pescoço, escreva-os na tábua do seu coração.

[[v20-3-4]]

^<<v20-3-4,4>>^ Então você terá o favor de Deus e dos homens, e boa reputação.

[[v20-3-5]]

^<<v20-3-5,5>>^ Confie no Senhor de todo o seu coração e não se apóie em seu próprio entendimento;

[[v20-3-6]]

^<<v20-3-6,6>>^ reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas.

[[v20-3-7]]

^<<v20-3-7,7>>^ Não seja sábio aos seus próprios olhos; tema ao Senhor e evite o mal.

[[v20-3-8]]

^<<v20-3-8,8>>^ Isso lhe dará saúde ao corpo e vigor aos ossos.

[[v20-3-9]]

^<<v20-3-9,9>>^ Honre o Senhor com todos os seus recursos e com os primeiros frutos de todas as suas plantações;

[[v20-3-10]]

^<<v20-3-10,10>>^ os seus celeiros ficarão plenamente cheios, e os seus barris transbordarão de vinho.

[[v20-3-11]]

^<<v20-3-11,11>>^ Meu filho, não despreze a disciplina do Senhor nem se magoe com a sua repreensão,

[[v20-3-12]]

^<<v20-3-12,12>>^ pois o Senhor disciplina a quem ama, assim como o pai faz ao filho de quem deseja o bem.

[[v20-3-13]]

^<<v20-3-13,13>>^ Como é feliz o homem que acha a sabedoria, o homem que obtém entendimento,

[[v20-3-14]]

^<<v20-3-14,14>>^ pois a sabedoria é mais proveitosa do que a prata e rende mais do que o ouro.

[[v20-3-15]]

^<<v20-3-15,15>>^ É mais preciosa do que rubis; nada do que você possa desejar se compara a ela.

[[v20-3-16]]

^<<v20-3-16,16>>^ Na mão direita, a sabedoria lhe garante vida longa; na mão esquerda, riquezas e honra.

[[v20-3-17]]

^<<v20-3-17,17>>^ Os caminhos da sabedoria são caminhos agradáveis, e todas as suas veredas são paz.

[[v20-3-18]]

^<<v20-3-18,18>>^ A sabedoria é árvore que dá vida a quem a abraça; quem a ela se apega será abençoado.

[[v20-3-19]]

^<<v20-3-19,19>>^ Por sua sabedoria o Senhor lançou os alicerces da terra, por seu entendimento fixou no lugar os céus;

[[v20-3-20]]

^<<v20-3-20,20>>^ por seu conhecimento as fontes profundas se rompem, e as nuvens gotejam o orvalho.

[[v20-3-21]]

^<<v20-3-21,21>>^ Meu filho, guarde consigo a sensatez e o equilíbrio, nunca os perca de vista;

[[v20-3-22]]

^<<v20-3-22,22>>^ trarão vida a você e serão um enfeite para o seu pescoço.

[[v20-3-23]]

^<<v20-3-23,23>>^ Então você seguirá o seu caminho em segurança, e não tropeçará;

[[v20-3-24]]

^<<v20-3-24,24>>^ quando se deitar, não terá medo, e o seu sono será tranqüilo.

[[v20-3-25]]

^<<v20-3-25,25>>^ Não terá medo da calamidade repentina nem da ruína que atinge os ímpios,

[[v20-3-26]]

^<<v20-3-26,26>>^ pois o Senhor será a sua segurança e o impedirá de cair em armadilha.

[[v20-3-27]]

^<<v20-3-27,27>>^ Quanto lhe for possível, não deixe de fazer o bem a quem dele precisa,

[[v20-3-28]]

^<<v20-3-28,28>>^ Não diga ao seu próximo: "Volte amanhã, e eu lhe darei algo", se pode ajudá-lo hoje.

[[v20-3-29]]

^<<v20-3-29,29>>^ Não planeje o mal contra o seu próximo, que confiantemente mora perto de você.

[[v20-3-30]]

^<<v20-3-30,30>>^ Não acuse alguém sem motivo, se ele não lhe fez nenhum mal.

[[v20-3-31]]

^<<v20-3-31,31>>^ Não tenha inveja de quem é violento nem adote nenhum dos seus procedimentos,

[[v20-3-32]]

^<<v20-3-32,32>>^ pois o Senhor detesta o perverso, mas o justo é seu grande amigo.

[[v20-3-33]]

^<<v20-3-33,33>>^ A maldição do Senhor está sobre a casa dos ímpios, mas ele abençoa o lar dos justos.

[[v20-3-34]]

^<<v20-3-34,34>>^ Ele zomba dos zombadores, mas concede graça aos humildes.

[[v20-3-35]]

^<<v20-3-35,35>>^ A honra é herança dos sábios, mas o Senhor expõe os tolos ao ridículo.

'''

xref:020-proverbios/020-proverbios-002.adoc#v20-2-0[&#60; Capítulo Anterior] | <<v20-3-0,Topo>> | xref:020-proverbios/020-proverbios-004.adoc#v20-4-0[Próximo Capítulo &#62;]