include::./index.adoc[]

[[v20-7-0]]
=== Provérbios, 7
// nvi ?, NVI - Nova Versão Internacional

[[v20-7-1]]

^<<v20-7-1,1>>^ Meu filho, obedeça às minhas palavras e no íntimo guarde os meus mandamentos.

[[v20-7-2]]

^<<v20-7-2,2>>^ Obedeça aos meus mandamentos, e você terá vida; guarde os meus ensinos como a pupila dos seus olhos.

[[v20-7-3]]

^<<v20-7-3,3>>^ Amarre-os aos dedos; escreva-os na tábua do seu coração.

[[v20-7-4]]

^<<v20-7-4,4>>^ Diga à sabedoria: "Você é minha irmã", e chame ao entendimento seu parente;

[[v20-7-5]]

^<<v20-7-5,5>>^ eles o manterão afastado da mulher imoral, da mulher leviana e suas palavras sedutoras.

[[v20-7-6]]

^<<v20-7-6,6>>^ Da janela de minha casa olhei através da grade

[[v20-7-7]]

^<<v20-7-7,7>>^ e vi entre os inexperientes, no meio dos jovens, um rapaz sem juízo.

[[v20-7-8]]

^<<v20-7-8,8>>^ Ele vinha pela rua, próximo à esquina de certa mulher, andando em direção à casa dela

[[v20-7-9]]

^<<v20-7-9,9>>^ Era crepúsculo, o entardecer do dia, chegavam as sombras da noite, crescia a escuridão.

[[v20-7-10]]

^<<v20-7-10,10>>^ A mulher veio então ao seu encontro, vestida como prostituta, cheia de astúcia no coração.

[[v20-7-11]]

^<<v20-7-11,11>>^ ( Ela é espalhafatosa e provocadora, seus pés nunca param em casa;

[[v20-7-12]]

^<<v20-7-12,12>>^ uma hora na rua, outra nas praças, em cada esquina fica à espreita. )

[[v20-7-13]]

^<<v20-7-13,13>>^ Ela agarrou o rapaz, beijou-o e lhe disse descaradamente:

[[v20-7-14]]

^<<v20-7-14,14>>^ "Tenho em casa a carne dos sacrifícios de comunhão, que hoje fiz para cumprir os meus votos.

[[v20-7-15]]

^<<v20-7-15,15>>^ Por isso saí para encontrá-lo; vim à sua procura e o encontrei!

[[v20-7-16]]

^<<v20-7-16,16>>^ Estendi sobre o meu leito cobertas de linho fino do Egito.

[[v20-7-17]]

^<<v20-7-17,17>>^ Perfumei a minha cama com mirra, aloés e canela.

[[v20-7-18]]

^<<v20-7-18,18>>^ Venha, vamos embriagar-nos de carícias até o amanhecer; gozemos as delícias do amor!

[[v20-7-19]]

^<<v20-7-19,19>>^ Pois o meu marido não está em casa; partiu para uma longa viagem.

[[v20-7-20]]

^<<v20-7-20,20>>^ Levou uma bolsa cheia de prata e não voltará antes da lua cheia".

[[v20-7-21]]

^<<v20-7-21,21>>^ Com a sedução das palavras o persuadiu, e o atraiu com o dulçor dos lábios.

[[v20-7-22]]

^<<v20-7-22,22>>^ Imediatamente ele a seguiu como o boi levado ao matadouro, ou como o cervo que vai cair no laço

[[v20-7-23]]

^<<v20-7-23,23>>^ até que uma flecha lhe atravesse o fígado, ou como o pássaro que salta para dentro do alçapão, sem saber que isso lhe custará a vida.

[[v20-7-24]]

^<<v20-7-24,24>>^ Então, meu filho, ouça-me; dê atenção às minhas palavras.

[[v20-7-25]]

^<<v20-7-25,25>>^ Não deixe que o seu coração se volte para os caminhos dela, nem se perca em tais veredas.

[[v20-7-26]]

^<<v20-7-26,26>>^ Muitas foram as suas vítimas; os que matou são uma grande multidão.

[[v20-7-27]]

^<<v20-7-27,27>>^ A casa dela é um caminho que desce para a sepultura, para as moradas da morte.

'''

xref:020-proverbios/020-proverbios-006.adoc#v20-6-0[&#60; Capítulo Anterior] | <<v20-7-0,Topo>> | xref:020-proverbios/020-proverbios-008.adoc#v20-8-0[Próximo Capítulo &#62;]