include::./index.adoc[]

[[v20-6-0]]
=== Provérbios, 6
// nvi ?, NVI - Nova Versão Internacional

[[v20-6-1]]

^<<v20-6-1,1>>^ Meu filho, se você serviu de fiador do seu próximo, se, com um aperto de mãos, empenhou-se por um estranho

[[v20-6-2]]

^<<v20-6-2,2>>^ e caiu na armadilha das palavras que você mesmo disse, está prisioneiro do que falou.

[[v20-6-3]]

^<<v20-6-3,3>>^ Então, meu filho, uma vez que você caiu nas mãos do seu próximo, vá e humilhe-se; insista, incomode o seu próximo!

[[v20-6-4]]

^<<v20-6-4,4>>^ Não se entregue ao sono, não procure descansar.

[[v20-6-5]]

^<<v20-6-5,5>>^ Livre-se como a gazela se livra do caçador, como a ave do laço que a pode prender.

[[v20-6-6]]

^<<v20-6-6,6>>^ Observe a formiga, preguiçoso, reflita nos caminhos dela e seja sábio!

[[v20-6-7]]

^<<v20-6-7,7>>^ Ela não tem nem chefe, nem supervisor, nem governante,

[[v20-6-8]]

^<<v20-6-8,8>>^ e ainda assim armazena as suas provisões no verão e na época da colheita ajunta o seu alimento.

[[v20-6-9]]

^<<v20-6-9,9>>^ Até quando você vai ficar deitado, preguiçoso? Quando se levantará de seu sono?

[[v20-6-10]]

^<<v20-6-10,10>>^ Tirando uma soneca, cochilando um pouco, cruzando um pouco os braços para descansar,

[[v20-6-11]]

^<<v20-6-11,11>>^ a sua pobreza o surpreenderá como um assaltante, e a sua necessidade lhe virá como um homem armado.

[[v20-6-12]]

^<<v20-6-12,12>>^ O perverso não tem caráter. Anda de um lado para o outro dizendo coisas maldosas;

[[v20-6-13]]

^<<v20-6-13,13>>^ pisca o olho, arrasta os pés e faz sinais com os dedos;

[[v20-6-14]]

^<<v20-6-14,14>>^ tem no coração o propósito de enganar; planeja sempre o mal e semeia discórdia.

[[v20-6-15]]

^<<v20-6-15,15>>^ Por isso a desgraça se abaterá repentinamente sobre ele; de um golpe será destruído, irremediavelmente.

[[v20-6-16]]

^<<v20-6-16,16>>^ Há seis coisas que o Senhor odeia, sete coisas que ele detesta:

[[v20-6-17]]

^<<v20-6-17,17>>^ olhos altivos, língua mentirosa, mãos que derramam sangue inocente,

[[v20-6-18]]

^<<v20-6-18,18>>^ coração que traça planos perversos, pés que se apressam para fazer o mal,

[[v20-6-19]]

^<<v20-6-19,19>>^ a testemunha falsa que espalha mentiras e aquele que provoca discórdia entre irmãos.

[[v20-6-20]]

^<<v20-6-20,20>>^ Meu filho, obedeça aos mandamentos de seu pai e não abandone o ensino de sua mãe.

[[v20-6-21]]

^<<v20-6-21,21>>^ Amarre-os sempre junto ao coração; ate-os ao redor do pescoço.

[[v20-6-22]]

^<<v20-6-22,22>>^ Quando você andar, eles o guiarão; quando dormir, o estarão protegendo; quando acordar, falarão com você.

[[v20-6-23]]

^<<v20-6-23,23>>^ Pois o mandamento é lâmpada, a instrução é luz, e as advertências da disciplina são o caminho que conduz à vida,

[[v20-6-24]]

^<<v20-6-24,24>>^ eles o protegerão da mulher imoral, e dos falsos elogios da mulher leviana.

[[v20-6-25]]

^<<v20-6-25,25>>^ Não cobice em seu coração a sua beleza nem se deixe seduzir por seus olhares,

[[v20-6-26]]

^<<v20-6-26,26>>^ pois o preço de uma prostituta é um pedaço de pão, mas a adúltera sai à caça de vidas preciosas.

[[v20-6-27]]

^<<v20-6-27,27>>^ Pode alguém colocar fogo no peito sem queimar a roupa?

[[v20-6-28]]

^<<v20-6-28,28>>^ Pode alguém andar sobre brasas sem queimar os pés?

[[v20-6-29]]

^<<v20-6-29,29>>^ Assim acontece com quem se deita com mulher alheia; ninguém que a toque ficará sem castigo.

[[v20-6-30]]

^<<v20-6-30,30>>^ O ladrão não é desprezado se, faminto, rouba para matar a fome.

[[v20-6-31]]

^<<v20-6-31,31>>^ Contudo, se for pego, deverá pagar sete vezes o que roubou, embora isso lhe custe tudo o que tem em casa.

[[v20-6-32]]

^<<v20-6-32,32>>^ Mas o homem que comete adultério não tem juízo; todo aquele que assim procede a si mesmo se destrói.

[[v20-6-33]]

^<<v20-6-33,33>>^ Sofrerá ferimentos e vergonha, e a sua humilhação jamais se apagará,

[[v20-6-34]]

^<<v20-6-34,34>>^ pois o ciúme desperta a fúria do marido, que não terá misericórdia quando se vingar.

[[v20-6-35]]

^<<v20-6-35,35>>^ Não aceitará nenhuma compensação; os melhores presentes não o acalmarão.

'''

xref:020-proverbios/020-proverbios-005.adoc#v20-5-0[&#60; Capítulo Anterior] | <<v20-6-0,Topo>> | xref:020-proverbios/020-proverbios-007.adoc#v20-7-0[Próximo Capítulo &#62;]