include::./index.adoc[]

[[v20-4-0]]
=== Provérbios, 4
// nvi ?, NVI - Nova Versão Internacional

[[v20-4-1]]

^<<v20-4-1,1>>^ Ouçam, meus filhos, a instrução de um pai; estejam atentos, e obterão discernimento.

[[v20-4-2]]

^<<v20-4-2,2>>^ O ensino que lhes ofereço é bom; por isso não abandonem a minha instrução.

[[v20-4-3]]

^<<v20-4-3,3>>^ Quando eu era menino, ainda pequeno, em companhia de meu pai, um filho muito especial para minha mãe,

[[v20-4-4]]

^<<v20-4-4,4>>^ ele me ensinava e me dizia: "Apegue-se às minhas palavras de todo o coração; obedeça aos meus mandamentos, e você terá vida.

[[v20-4-5]]

^<<v20-4-5,5>>^ Procure obter sabedoria e entendimento; não se esqueça das minhas palavras nem delas se afaste.

[[v20-4-6]]

^<<v20-4-6,6>>^ Não abandone a sabedoria, e ela o protegerá; ame-a, e ela cuidará de você.

[[v20-4-7]]

^<<v20-4-7,7>>^ O conselho da sabedoria é: procure obter sabedoria; use tudo que você possui para adquirir entendimento.

[[v20-4-8]]

^<<v20-4-8,8>>^ Dedique alta estima à sabedoria, e ela o exaltará; abrace-a, e ela o honrará.

[[v20-4-9]]

^<<v20-4-9,9>>^ Ela porá um belo diadema sobre a sua cabeça e lhe dará de presente uma coroa de esplendor".

[[v20-4-10]]

^<<v20-4-10,10>>^ Ouça, meu filho, e aceite o que digo, e você terá vida longa.

[[v20-4-11]]

^<<v20-4-11,11>>^ Eu o conduzi pelo caminho da sabedoria e o encaminhei por veredas retas.

[[v20-4-12]]

^<<v20-4-12,12>>^ Assim, quando você por elas seguir, não encontrará obstáculos; quando correr, não tropeçará.

[[v20-4-13]]

^<<v20-4-13,13>>^ Apegue-se à instrução, não a abandone; guarde-a bem, pois dela depende a sua vida.

[[v20-4-14]]

^<<v20-4-14,14>>^ Não siga pela vereda dos ímpios nem ande no caminho dos maus.

[[v20-4-15]]

^<<v20-4-15,15>>^ Evite-o, não passe por ele; afaste-se e não se detenha.

[[v20-4-16]]

^<<v20-4-16,16>>^ Pois eles não conseguem dormir enquanto não fazem o mal; perdem o sono se não causarem a ruína de alguém.

[[v20-4-17]]

^<<v20-4-17,17>>^ Pois eles se alimentam de maldade, e se embriagam de violência.

[[v20-4-18]]

^<<v20-4-18,18>>^ A vereda do justo é como a luz da alvorada, que brilha cada vez mais até à plena claridade do dia.

[[v20-4-19]]

^<<v20-4-19,19>>^ Mas o caminho dos ímpios é como densas trevas; nem sequer sabem em que tropeçam.

[[v20-4-20]]

^<<v20-4-20,20>>^ Meu filho, escute o que lhe digo; preste atenção às minhas palavras.

[[v20-4-21]]

^<<v20-4-21,21>>^ Nunca as perca de vista; guarde-as no fundo do coração,

[[v20-4-22]]

^<<v20-4-22,22>>^ pois são vida para quem as encontra e saúde para todo o seu ser.

[[v20-4-23]]

^<<v20-4-23,23>>^ Acima de tudo, guarde o seu coração, pois dele depende toda a sua vida.

[[v20-4-24]]

^<<v20-4-24,24>>^ Afaste da sua boca as palavras perversas; fique longe dos seus lábios a maldade.

[[v20-4-25]]

^<<v20-4-25,25>>^ Olhe sempre para a frente, mantenha o olhar fixo no que está adiante de você.

[[v20-4-26]]

^<<v20-4-26,26>>^ Veja bem por onde anda, e os seus passos serão seguros.

[[v20-4-27]]

^<<v20-4-27,27>>^ Não se desvie nem para a direita nem para a esquerda; afaste os seus pés da maldade.

'''

xref:020-proverbios/020-proverbios-003.adoc#v20-3-0[&#60; Capítulo Anterior] | <<v20-4-0,Topo>> | xref:020-proverbios/020-proverbios-005.adoc#v20-5-0[Próximo Capítulo &#62;]