include::./index.adoc[]

[[v20-9-0]]
=== Provérbios, 9
// nvi ?, NVI - Nova Versão Internacional

[[v20-9-1]]

^<<v20-9-1,1>>^ A sabedoria construiu sua casa; ergueu suas sete colunas.

[[v20-9-2]]

^<<v20-9-2,2>>^ Matou animais para a refeição, preparou seu vinho e arrumou sua mesa.

[[v20-9-3]]

^<<v20-9-3,3>>^ E enviou as servas para fazerem convites desde o ponto mais alto da cidade, clamando:

[[v20-9-4]]

^<<v20-9-4,4>>^ "Venham todos os inexperientes! " Aos que não têm bom senso ela diz:

[[v20-9-5]]

^<<v20-9-5,5>>^ "Venham comer a minha comida e beber o vinho que preparei.

[[v20-9-6]]

^<<v20-9-6,6>>^ Deixem a insensatez, e vocês terão vida; andem pelo caminho do entendimento.

[[v20-9-7]]

^<<v20-9-7,7>>^ "Quem corrige o zombador traz sobre si o insulto; quem repreende o ímpio mancha o próprio nome.

[[v20-9-8]]

^<<v20-9-8,8>>^ Não repreenda o zombador, caso contrário ele o odiará; repreenda o sábio, e ele o amará.

[[v20-9-9]]

^<<v20-9-9,9>>^ Instrua o homem sábio, e ele será ainda mais sábio; ensine o homem justo, e ele aumentará o seu saber.

[[v20-9-10]]

^<<v20-9-10,10>>^ "O temor do Senhor é o princípio da sabedoria, e o conhecimento do Santo é entendimento.

[[v20-9-11]]

^<<v20-9-11,11>>^ Pois por meu intermédio os seus dias serão multiplicados, e o tempo da sua vida se prolongará.

[[v20-9-12]]

^<<v20-9-12,12>>^ Se você for sábio, o benefício será seu; se for zombador, sofrerá as conseqüências".

[[v20-9-13]]

^<<v20-9-13,13>>^ A insensatez é pura exibição, sedução e ignorância.

[[v20-9-14]]

^<<v20-9-14,14>>^ Sentada à porta de sua casa, no ponto mais alto da cidade,

[[v20-9-15]]

^<<v20-9-15,15>>^ clama aos que passam por ali seguindo o seu caminho.

[[v20-9-16]]

^<<v20-9-16,16>>^ "Venham todos os inexperientes! " Aos que não têm bom senso ela diz:

[[v20-9-17]]

^<<v20-9-17,17>>^ "A água roubada é doce, e o pão que se come escondido é saboroso! "

[[v20-9-18]]

^<<v20-9-18,18>>^ Mas eles nem imaginam que ali estão os espíritos dos mortos, que os seus convidados estão nas profundezas da sepultura.

'''

xref:020-proverbios/020-proverbios-008.adoc#v20-8-0[&#60; Capítulo Anterior] | <<v20-9-0,Topo>> | xref:020-proverbios/020-proverbios-010.adoc#v20-10-0[Próximo Capítulo &#62;]