include::./index.adoc[]

[[v20-1-0]]
=== Provérbios, 1
// nvi ?, NVI - Nova Versão Internacional

[[v20-1-1]]

^<<v20-1-1,1>>^ Estes são os provérbios de Salomão, filho de Davi, rei de Israel.

[[v20-1-2]]

^<<v20-1-2,2>>^ Eles ajudarão a experimentar a sabedoria e a disciplina; a compreender as palavras que dão entendimento;

[[v20-1-3]]

^<<v20-1-3,3>>^ a viver com disciplina e sensatez, fazendo o que é justo, direito e correto;

[[v20-1-4]]

^<<v20-1-4,4>>^ ajudarão a dar prudência aos inexperientes e conhecimento e bom senso aos jovens.

[[v20-1-5]]

^<<v20-1-5,5>>^ Se o sábio der ouvidos, aumentará seu conhecimento, e quem tem discernimento obterá orientação

[[v20-1-6]]

^<<v20-1-6,6>>^ para compreender provérbios e parábolas, ditados e enigmas dos sábios.

[[v20-1-7]]

^<<v20-1-7,7>>^ O temor do Senhor é o princípio do conhecimento, mas os insensatos desprezam a sabedoria e a disciplina.

[[v20-1-8]]

^<<v20-1-8,8>>^ Ouça, meu filho, a instrução de seu pai e não despreze o ensino de sua mãe.

[[v20-1-9]]

^<<v20-1-9,9>>^ Eles serão um enfeite para a sua cabeça, um adorno para o seu pescoço.

[[v20-1-10]]

^<<v20-1-10,10>>^ Meu filho, se os maus tentarem seduzi-lo, não ceda!

[[v20-1-11]]

^<<v20-1-11,11>>^ Se disserem: "Venha conosco; fiquemos de tocaia para matar alguém, vamos divertir-nos armando emboscada contra quem de nada suspeita!

[[v20-1-12]]

^<<v20-1-12,12>>^ Vamos engoli-los vivos, como a sepultura engole os mortos; vamos destruí-los inteiros, como são destruídos os que descem à cova;

[[v20-1-13]]

^<<v20-1-13,13>>^ acharemos todo tipo de objetos valiosos e encheremos as nossas casas com o que roubarmos;

[[v20-1-14]]

^<<v20-1-14,14>>^ junte-se ao nosso bando; dividiremos em partes iguais tudo o que conseguirmos! "

[[v20-1-15]]

^<<v20-1-15,15>>^ Meu filho, não vá pela vereda dessa gente! Afaste os pés do caminho que eles seguem,

[[v20-1-16]]

^<<v20-1-16,16>>^ pois os pés deles correm para fazer o mal, estão sempre prontos para derramar sangue.

[[v20-1-17]]

^<<v20-1-17,17>>^ Assim como é inútil estender a rede se as aves o observam,

[[v20-1-18]]

^<<v20-1-18,18>>^ também esses homens não percebem que fazem tocaia contra a própria vida; armam emboscadas contra eles mesmos!

[[v20-1-19]]

^<<v20-1-19,19>>^ Tal é o caminho de todos os gananciosos; quem assim procede se destrói.

[[v20-1-20]]

^<<v20-1-20,20>>^ A sabedoria clama em voz alta nas ruas, ergue a voz nas praças públicas;

[[v20-1-21]]

^<<v20-1-21,21>>^ nas esquinas das ruas barulhentas ela clama, nas portas da cidade faz o seu discurso:

[[v20-1-22]]

^<<v20-1-22,22>>^ "Até quando vocês, inexperientes, irão contentar-se com a sua inexperiência? Vocês, zombadores, até quando terão prazer na zombaria? E vocês, tolos, até quando desprezarão o conhecimento?

[[v20-1-23]]

^<<v20-1-23,23>>^ Se acatarem a minha repreensão, eu lhes darei um espírito de sabedoria e lhes revelarei os meus pensamentos.

[[v20-1-24]]

^<<v20-1-24,24>>^ Vocês, porém, rejeitaram o meu convite; ninguém se importou quando estendi minha mão!

[[v20-1-25]]

^<<v20-1-25,25>>^ Visto que desprezaram totalmente o meu conselho e não quiseram aceitar a minha repreensão,

[[v20-1-26]]

^<<v20-1-26,26>>^ eu, de minha parte, vou rir-me da sua desgraça; zombarei quando o que temem se abater sobre vocês,

[[v20-1-27]]

^<<v20-1-27,27>>^ quando aquilo que temem abater-se sobre vocês como uma tempestade, quando a desgraça os atingir como um vendaval, quando a angústia e a dor os dominarem.

[[v20-1-28]]

^<<v20-1-28,28>>^ "Então vocês me chamarão, mas não responderei; procurarão por mim, mas não me encontrarão.

[[v20-1-29]]

^<<v20-1-29,29>>^ Visto que desprezaram o conhecimento e recusaram o temor do Senhor,

[[v20-1-30]]

^<<v20-1-30,30>>^ não quiseram aceitar o meu conselho e fizeram pouco caso da minha advertência,

[[v20-1-31]]

^<<v20-1-31,31>>^ comerão do fruto da sua conduta e se fartarão de suas próprias maquinações.

[[v20-1-32]]

^<<v20-1-32,32>>^ Pois a inconstância dos inexperientes os matará, e a falsa segurança dos tolos os destruirá;

[[v20-1-33]]

^<<v20-1-33,33>>^ mas quem me ouvir viverá em segurança e estará tranqüilo, sem temer nenhum mal".

'''

xref:019-salmos/019-salmos-150.adoc#v19-150-0[&#60; Capítulo Anterior] | <<v20-1-0,Topo>> | xref:020-proverbios/020-proverbios-002.adoc#v20-2-0[Próximo Capítulo &#62;]