include::./index.adoc[]

[[v20-13-0]]
=== Provérbios, 13
// nvi ?, NVI - Nova Versão Internacional

[[v20-13-1]]

^<<v20-13-1,1>>^ O filho sábio acolhe a instrução do pai, mas o zombador não ouve a repreensão.

[[v20-13-2]]

^<<v20-13-2,2>>^ Do fruto de sua boca o homem desfruta coisas boas, mas o que os infiéis desejam é violência.

[[v20-13-3]]

^<<v20-13-3,3>>^ Quem guarda a sua boca guarda a sua vida, mas quem fala demais acaba se arruinando.

[[v20-13-4]]

^<<v20-13-4,4>>^ O preguiçoso deseja e nada consegue, mas os desejos do diligente são amplamente satisfeitos.

[[v20-13-5]]

^<<v20-13-5,5>>^ Os justos odeiam o que é falso, mas os ímpios trazem vergonha e desgraça.

[[v20-13-6]]

^<<v20-13-6,6>>^ A retidão protege o homem íntegro, mas a impiedade derruba o pecador.

[[v20-13-7]]

^<<v20-13-7,7>>^ Alguns fingem que são ricos e nada têm; outros fingem que são pobres, e têm grande riqueza.

[[v20-13-8]]

^<<v20-13-8,8>>^ As riquezas de um homem servem de resgate para a sua vida, mas o pobre nunca recebe ameaças.

[[v20-13-9]]

^<<v20-13-9,9>>^ A luz dos justos resplandece esplendidamente, mas a lâmpada dos ímpios apaga-se.

[[v20-13-10]]

^<<v20-13-10,10>>^ O orgulho só gera discussões, mas a sabedoria está com os que tomam conselho.

[[v20-13-11]]

^<<v20-13-11,11>>^ O dinheiro ganho com desonestidade diminuirá, mas quem o ajunta aos poucos terá cada vez mais.

[[v20-13-12]]

^<<v20-13-12,12>>^ A esperança que se retarda deixa o coração doente, mas o anseio satisfeito é árvore de vida.

[[v20-13-13]]

^<<v20-13-13,13>>^ Quem zomba da instrução pagará por ela, mas aquele que respeita o mandamento será recompensado.

[[v20-13-14]]

^<<v20-13-14,14>>^ O ensino dos sábios é fonte de vida, e afasta o homem das armadilhas da morte.

[[v20-13-15]]

^<<v20-13-15,15>>^ O bom entendimento conquista favor, mas o caminho do infiel é áspero.

[[v20-13-16]]

^<<v20-13-16,16>>^ Todo homem prudente age com base no conhecimento, mas o tolo expõe a sua insensatez.

[[v20-13-17]]

^<<v20-13-17,17>>^ O mensageiro ímpio cai em dificuldade, mas o enviado digno de confiança traz a cura.

[[v20-13-18]]

^<<v20-13-18,18>>^ Quem despreza a disciplina cai na pobreza e na vergonha, mas quem acolhe a repreensão recebe tratamento honroso.

[[v20-13-19]]

^<<v20-13-19,19>>^ O anseio satisfeito agrada a alma, mas o tolo detesta afastar-se do mal.

[[v20-13-20]]

^<<v20-13-20,20>>^ Aquele que anda com os sábios será cada vez mais sábio, mas o companheiro dos tolos acabará mal.

[[v20-13-21]]

^<<v20-13-21,21>>^ O infortúnio persegue o pecador, mas a prosperidade é a recompensa do justo.

[[v20-13-22]]

^<<v20-13-22,22>>^ O homem bom deixa herança para os filhos de seus filhos, mas a riqueza do pecador é armazenada para os justos.

[[v20-13-23]]

^<<v20-13-23,23>>^ A lavoura do pobre produz alimento com fartura, mas por falta de justiça ele o perde.

[[v20-13-24]]

^<<v20-13-24,24>>^ Quem se nega a castigar seu filho não o ama; quem o ama não hesita em discipliná-lo.

[[v20-13-25]]

^<<v20-13-25,25>>^ O justo come até satisfazer o apetite, mas os ímpios permanecem famintos.

'''

xref:020-proverbios/020-proverbios-012.adoc#v20-12-0[&#60; Capítulo Anterior] | <<v20-13-0,Topo>> | xref:020-proverbios/020-proverbios-014.adoc#v20-14-0[Próximo Capítulo &#62;]