include::./index.adoc[]

[[v20-23-0]]
=== Provérbios, 23
// nvi ?, NVI - Nova Versão Internacional

[[v20-23-1]]

^<<v20-23-1,1>>^ Quando você se assentar para uma refeição com alguma autoridade, observe com atenção quem está diante de você,

[[v20-23-2]]

^<<v20-23-2,2>>^ e encoste a faca à sua própria garganta, se estiver com grande apetite.

[[v20-23-3]]

^<<v20-23-3,3>>^ Não deseje as iguarias que lhe oferece, pois podem ser enganosas.

[[v20-23-4]]

^<<v20-23-4,4>>^ Não esgote suas forças tentando ficar rico; tenha bom senso!

[[v20-23-5]]

^<<v20-23-5,5>>^ As riquezas desaparecem assim que você as contempla; elas criam asas e voam como águias pelo céu.

[[v20-23-6]]

^<<v20-23-6,6>>^ Não aceite a refeição de um hospedeiro invejoso, nem deseje as iguarias que lhe oferece;

[[v20-23-7]]

^<<v20-23-7,7>>^ pois ele só pensa nos gastos. Ele lhe diz: "Coma e beba! ", mas não fala com sinceridade.

[[v20-23-8]]

^<<v20-23-8,8>>^ Você vomitará o pouco que comeu, e desperdiçará a sua cordialidade.

[[v20-23-9]]

^<<v20-23-9,9>>^ Não vale a pena conversar com o tolo, pois ele despreza a sabedoria do que você fala.

[[v20-23-10]]

^<<v20-23-10,10>>^ Não mude de lugar os antigos marcos de propriedade, nem invada as terras dos órfãos,

[[v20-23-11]]

^<<v20-23-11,11>>^ pois Aquele que defende os direitos deles é forte. Ele lutará contra você para defendê-los.

[[v20-23-12]]

^<<v20-23-12,12>>^ Dedique à disciplina o seu coração, e os seus ouvidos às palavras que dão conhecimento.

[[v20-23-13]]

^<<v20-23-13,13>>^ Não evite disciplinar a criança; se você a castigar com a vara, ela não morrerá.

[[v20-23-14]]

^<<v20-23-14,14>>^ Castigue-a, você mesmo, com a vara, e assim a livrará da sepultura.

[[v20-23-15]]

^<<v20-23-15,15>>^ Meu filho, se o seu coração for sábio, o meu coração se alegrará.

[[v20-23-16]]

^<<v20-23-16,16>>^ Sentirei grande alegria quando os seus lábios falarem com retidão.

[[v20-23-17]]

^<<v20-23-17,17>>^ Não inveje os pecadores em seu coração; melhor será que tema sempre ao Senhor.

[[v20-23-18]]

^<<v20-23-18,18>>^ Se agir assim, certamente haverá bom futuro para você, e a sua esperança não falhará.

[[v20-23-19]]

^<<v20-23-19,19>>^ Ouça, meu filho, e seja sábio; guie o seu coração pelo bom caminho.

[[v20-23-20]]

^<<v20-23-20,20>>^ Não ande com os que se encharcam de vinho, nem com os que se empanturram de carne.

[[v20-23-21]]

^<<v20-23-21,21>>^ Pois os bêbados e os glutões se empobrecerão, e a sonolência os vestirá de trapos.

[[v20-23-22]]

^<<v20-23-22,22>>^ Ouça o seu pai, que o gerou; não despreze sua mãe quando ela envelhecer.

[[v20-23-23]]

^<<v20-23-23,23>>^ Compre a verdade e não abra mão dela, nem tampouco da sabedoria, da disciplina e do discernimento.

[[v20-23-24]]

^<<v20-23-24,24>>^ O pai do justo exultará de júbilo; quem tem filho sábio nele se alegra.

[[v20-23-25]]

^<<v20-23-25,25>>^ Bom será que se alegrem seu pai e sua mãe e que exulte a mulher que o deu à luz!

[[v20-23-26]]

^<<v20-23-26,26>>^ Meu filho, dê-me o seu coração; mantenha os seus olhos em meus caminhos,

[[v20-23-27]]

^<<v20-23-27,27>>^ pois a prostituta é uma cova profunda, e a mulher pervertida é um poço estreito.

[[v20-23-28]]

^<<v20-23-28,28>>^ Como o assaltante, ela fica de tocaia, e multiplica entre os homens os infiéis.

[[v20-23-29]]

^<<v20-23-29,29>>^ De quem são os ais? De quem as tristezas? E as brigas, de quem são? E os ferimentos desnecessários? De quem são os olhos vermelhos?

[[v20-23-30]]

^<<v20-23-30,30>>^ Dos que se demoram bebendo vinho, dos que andam à procura de bebida misturada.

[[v20-23-31]]

^<<v20-23-31,31>>^ Não se deixe atrair pelo vinho quando está vermelho, quando cintila no copo e escorre suavemente!

[[v20-23-32]]

^<<v20-23-32,32>>^ No fim, ele morde como serpente e envenena como víbora.

[[v20-23-33]]

^<<v20-23-33,33>>^ Seus olhos verão coisas estranhas, e sua mente imaginará coisas distorcidas.

[[v20-23-34]]

^<<v20-23-34,34>>^ Você será como quem dorme no meio do mar, como quem se deita no alto das cordas do mastro.

[[v20-23-35]]

^<<v20-23-35,35>>^ E dirá: "Espancaram-me, mas eu nada senti! Bateram em mim, mas nem percebi! Quando acordarei para que possa beber mais uma vez? "

'''

xref:020-proverbios/020-proverbios-022.adoc#v20-22-0[&#60; Capítulo Anterior] | <<v20-23-0,Topo>> | xref:020-proverbios/020-proverbios-024.adoc#v20-24-0[Próximo Capítulo &#62;]