include::./index.adoc[]

[[v20-17-0]]
=== Provérbios, 17
// nvi ?, NVI - Nova Versão Internacional

[[v20-17-1]]

^<<v20-17-1,1>>^ Melhor é um pedaço de pão seco com paz e tranqüilidade do que uma casa onde há banquetes, e muitas brigas.

[[v20-17-2]]

^<<v20-17-2,2>>^ O servo sábio dominará sobre o filho de conduta vergonhosa, e participará da herança como um dos irmãos.

[[v20-17-3]]

^<<v20-17-3,3>>^ O crisol é para a prata e o forno é para o ouro, mas o Senhor prova o coração.

[[v20-17-4]]

^<<v20-17-4,4>>^ O ímpio dá atenção aos lábios maus; o mentiroso dá ouvidos à língua destruidora.

[[v20-17-5]]

^<<v20-17-5,5>>^ Quem zomba dos pobres mostra desprezo pelo Criador deles; quem se alegra com a desgraça não ficará sem castigo.

[[v20-17-6]]

^<<v20-17-6,6>>^ Os filhos dos filhos são uma coroa para os idosos, e os pais são o orgulho dos seus filhos.

[[v20-17-7]]

^<<v20-17-7,7>>^ Os lábios arrogantes não ficam bem ao insensato; muito menos os lábios mentirosos ao governante!

[[v20-17-8]]

^<<v20-17-8,8>>^ O suborno é um recurso fascinante para aquele que o oferece; aonde quer que vá, ele tem sucesso.

[[v20-17-9]]

^<<v20-17-9,9>>^ Aquele que cobre uma ofensa promove amor, mas quem a lança em rosto separa bons amigos.

[[v20-17-10]]

^<<v20-17-10,10>>^ A repreensão faz marca mais profunda no homem de entendimento do que cem açoites no tolo.

[[v20-17-11]]

^<<v20-17-11,11>>^ O homem mau só pende para a rebeldia; por isso um oficial impiedoso será enviado contra ele.

[[v20-17-12]]

^<<v20-17-12,12>>^ Melhor é encontrar uma ursa da qual roubaram os filhotes do que um tolo em sua insensatez.

[[v20-17-13]]

^<<v20-17-13,13>>^ Quem retribui o bem com o mal, jamais deixará de ter mal no seu lar.

[[v20-17-14]]

^<<v20-17-14,14>>^ Começar uma discussão é como abrir brecha num dique; por isso resolva a questão antes que surja a contenda.

[[v20-17-15]]

^<<v20-17-15,15>>^ Absolver o ímpio e condenar o justo, são coisas que o Senhor odeia.

[[v20-17-16]]

^<<v20-17-16,16>>^ De que serve o dinheiro na mão do tolo, já que ele não quer obter sabedoria?

[[v20-17-17]]

^<<v20-17-17,17>>^ O amigo ama em todos os momentos; é um irmão na adversidade.

[[v20-17-18]]

^<<v20-17-18,18>>^ O homem sem juízo, com um aperto de mãos se compromete e se torna fiador do seu próximo.

[[v20-17-19]]

^<<v20-17-19,19>>^ Quem ama a discussão ama o pecado; quem constrói portas altas está procurando a sua ruína.

[[v20-17-20]]

^<<v20-17-20,20>>^ O homem de coração perverso não prospera, e o de língua enganosa cai na desgraça.

[[v20-17-21]]

^<<v20-17-21,21>>^ O filho tolo só dá tristeza, e nenhuma alegria tem o pai do insensato.

[[v20-17-22]]

^<<v20-17-22,22>>^ O coração bem disposto é remédio eficiente, mas o espírito oprimido resseca os ossos.

[[v20-17-23]]

^<<v20-17-23,23>>^ O ímpio aceita às escondidas o suborno para desviar o curso da justiça.

[[v20-17-24]]

^<<v20-17-24,24>>^ O homem de discernimento mantém a sabedoria em vista, mas os olhos do tolo perambulam até os confins da terra.

[[v20-17-25]]

^<<v20-17-25,25>>^ O filho tolo é a tristeza do seu pai e a amargura daquela que o deu à luz.

[[v20-17-26]]

^<<v20-17-26,26>>^ Não é bom castigar o inocente, nem açoitar quem merece ser honrado.

[[v20-17-27]]

^<<v20-17-27,27>>^ Quem tem conhecimento é comedido no falar, e quem tem entendimento é de espírito sereno.

[[v20-17-28]]

^<<v20-17-28,28>>^ Até o insensato passará por sábio, se ficar quieto, e, se contiver a língua, parecerá que tem discernimento.

'''

xref:020-proverbios/020-proverbios-016.adoc#v20-16-0[&#60; Capítulo Anterior] | <<v20-17-0,Topo>> | xref:020-proverbios/020-proverbios-018.adoc#v20-18-0[Próximo Capítulo &#62;]