include::./index.adoc[]

[[v40-4-0]]
=== Mateus, 4
// nvi ?, NVI - Nova Versão Internacional

[[v40-4-1]]

^<<v40-4-1,1>>^ Então Jesus foi levado pelo Espírito ao deserto, para ser tentado pelo diabo.

[[v40-4-2]]

^<<v40-4-2,2>>^ Depois de jejuar quarenta dias e quarenta noites, teve fome.

[[v40-4-3]]

^<<v40-4-3,3>>^ O tentador aproximou-se dele e disse: "Se você é o Filho de Deus, mande que estas pedras se transformem em pães".

[[v40-4-4]]

^<<v40-4-4,4>>^ Jesus respondeu: "Está escrito: ‘Nem só de pão viverá o homem, mas de toda palavra que procede da boca de Deus’".

[[v40-4-5]]

^<<v40-4-5,5>>^ Então o diabo o levou à cidade santa, colocou-o na parte mais alta do templo e lhe disse:

[[v40-4-6]]

^<<v40-4-6,6>>^ "Se você é o Filho de Deus, jogue-se daqui para baixo. Pois está escrito: ‘Ele dará ordens a seus anjos a seu respeito, e com as mãos eles o segurarão, para que você não tropece em alguma pedra’".

[[v40-4-7]]

^<<v40-4-7,7>>^ Jesus lhe respondeu: "Também está escrito: ‘Não ponha à prova o Senhor, o seu Deus’".

[[v40-4-8]]

^<<v40-4-8,8>>^ Depois, o diabo o levou a um monte muito alto e mostrou-lhe todos os reinos do mundo e o seu esplendor.

[[v40-4-9]]

^<<v40-4-9,9>>^ E lhe disse: "Tudo isto lhe darei, se você se prostrar e me adorar".

[[v40-4-10]]

^<<v40-4-10,10>>^ Jesus lhe disse: "Retire-se, Satanás! Pois está escrito: ‘Adore o Senhor, o seu Deus e só a ele preste culto’".

[[v40-4-11]]

^<<v40-4-11,11>>^ Então o diabo o deixou, e anjos vieram e o serviram.

[[v40-4-12]]

^<<v40-4-12,12>>^ Quando Jesus ouviu que João tinha sido preso, voltou para a Galiléia.

[[v40-4-13]]

^<<v40-4-13,13>>^ Saindo de Nazaré, foi viver em Cafarnaum, que ficava junto ao mar, na região de Zebulom e Naftali,

[[v40-4-14]]

^<<v40-4-14,14>>^ para cumprir o que fora dito pelo profeta Isaías:

[[v40-4-15]]

^<<v40-4-15,15>>^ "Terra de Zebulom e terra de Naftali, caminho do mar, além do Jordão, Galiléia dos gentios;

[[v40-4-16]]

^<<v40-4-16,16>>^ o povo que vivia nas trevas viu uma grande luz; sobre os que viviam na terra da sombra da morte raiou uma luz".

[[v40-4-17]]

^<<v40-4-17,17>>^ Daí em diante Jesus começou a pregar: "Arrependam-se, pois o Reino dos céus está próximo".

[[v40-4-18]]

^<<v40-4-18,18>>^ Andando à beira do mar da Galiléia, Jesus viu dois irmãos: Simão, chamado Pedro, e seu irmão André. Eles estavam lançando redes ao mar, pois eram pescadores.

[[v40-4-19]]

^<<v40-4-19,19>>^ E disse Jesus: "Sigam-me, e eu os farei pescadores de homens".

[[v40-4-20]]

^<<v40-4-20,20>>^ No mesmo instante eles deixaram as suas redes e o seguiram.

[[v40-4-21]]

^<<v40-4-21,21>>^ Indo adiante, viu outros dois irmãos: Tiago, filho de Zebedeu, e João, seu irmão. Eles estavam num barco com seu pai, Zebedeu, preparando as suas redes. Jesus os chamou,

[[v40-4-22]]

^<<v40-4-22,22>>^ e eles, deixando imediatamente o barco e seu pai, o seguiram.

[[v40-4-23]]

^<<v40-4-23,23>>^ Jesus foi por toda a Galiléia, ensinando nas sinagogas deles, pregando as boas novas do Reino e curando todas as enfermidades e doenças entre o povo.

[[v40-4-24]]

^<<v40-4-24,24>>^ Notícias sobre ele se espalharam por toda a Síria, e o povo lhe trouxe todos os que estavam padecendo vários males e tormentos: endemoninhados, epiléticos e paralíticos; e ele os curou.

[[v40-4-25]]

^<<v40-4-25,25>>^ Grandes multidões o seguiam, vindas da Galiléia, Decápolis, Jerusalém, Judéia e da região do outro lado do Jordão.

'''

xref:040-mateus/040-mateus-003.adoc#v40-3-0[&#60; Capítulo Anterior] | <<v40-4-0,Topo>> | xref:040-mateus/040-mateus-005.adoc#v40-5-0[Próximo Capítulo &#62;]