include::./index.adoc[]

[[v40-13-0]]
=== Mateus, 13
// nvi ?, NVI - Nova Versão Internacional

[[v40-13-1]]

^<<v40-13-1,1>>^ Naquele mesmo dia Jesus saiu de casa e assentou-se à beira-mar.

[[v40-13-2]]

^<<v40-13-2,2>>^ Reuniu-se ao seu redor uma multidão tão grande que ele teve que entrar num barco e assentar-se nele, enquanto todo o povo ficou na praia.

[[v40-13-3]]

^<<v40-13-3,3>>^ Então lhes falou muitas coisas por parábolas, dizendo: "O semeador saiu a semear.

[[v40-13-4]]

^<<v40-13-4,4>>^ Enquanto lançava a semente, parte dela caiu à beira do caminho, e as aves vieram e a comeram.

[[v40-13-5]]

^<<v40-13-5,5>>^ Parte dela caiu em terreno pedregoso, onde não havia muita terra; e logo brotou, porque a terra não era profunda.

[[v40-13-6]]

^<<v40-13-6,6>>^ Mas quando saiu o sol, as plantas se queimaram e secaram, porque não tinham raiz.

[[v40-13-7]]

^<<v40-13-7,7>>^ Outra parte caiu entre espinhos, que cresceram e sufocaram as plantas.

[[v40-13-8]]

^<<v40-13-8,8>>^ Outra ainda caiu em boa terra, deu boa colheita, a cem, sessenta e trinta por um.

[[v40-13-9]]

^<<v40-13-9,9>>^ Aquele que tem ouvidos para ouvir, ouça! "

[[v40-13-10]]

^<<v40-13-10,10>>^ Os discípulos aproximaram-se dele e perguntaram: "Por que falas ao povo por parábolas? "

[[v40-13-11]]

^<<v40-13-11,11>>^ Ele respondeu: "A vocês foi dado o conhecimento dos mistérios do Reino dos céus, mas a eles não.

[[v40-13-12]]

^<<v40-13-12,12>>^ A quem tem será dado, e este terá em grande quantidade. De quem não tem, até o que tem lhe será tirado.

[[v40-13-13]]

^<<v40-13-13,13>>^ Por essa razão eu lhes falo por parábolas: ‘Porque vendo, eles não vêem e, ouvindo, não ouvem nem entendem’.

[[v40-13-14]]

^<<v40-13-14,14>>^ Neles se cumpre a profecia de Isaías: ‘Ainda que estejam sempre ouvindo, vocês nunca entenderão; ainda que estejam sempre vendo, jamais perceberão.

[[v40-13-15]]

^<<v40-13-15,15>>^ Pois o coração deste povo se tornou insensível; de má vontade ouviram com os seus ouvidos, e fecharam os seus olhos. Se assim não fosse, poderiam ver com os olhos, ouvir com os ouvidos, entender com o coração e converter-se, e eu os curaria’.

[[v40-13-16]]

^<<v40-13-16,16>>^ Mas, felizes são os olhos de vocês, porque vêem; e os ouvidos de vocês, porque ouvem.

[[v40-13-17]]

^<<v40-13-17,17>>^ Pois eu lhes digo a verdade: Muitos profetas e justos desejaram ver o que vocês estão vendo, mas não viram, e ouvir o que vocês estão ouvindo, mas não ouviram.

[[v40-13-18]]

^<<v40-13-18,18>>^ "Portanto, ouçam o que significa a parábola do semeador:

[[v40-13-19]]

^<<v40-13-19,19>>^ Quando alguém ouve a mensagem do Reino e não a entende, o Maligno vem e lhe arranca o que foi semeado em seu coração. Este é o que foi semeado à beira do caminho.

[[v40-13-20]]

^<<v40-13-20,20>>^ Quanto ao que foi semeado em terreno pedregoso, este é aquele que ouve a palavra e logo a recebe com alegria.

[[v40-13-21]]

^<<v40-13-21,21>>^ Todavia, visto que não tem raiz em si mesmo, permanece por pouco tempo. Quando surge alguma tribulação ou perseguição por causa da palavra, logo a abandona.

[[v40-13-22]]

^<<v40-13-22,22>>^ Quanto ao que foi semeado entre os espinhos, este é aquele que ouve a palavra, mas a preocupação desta vida e o engano das riquezas a sufocam, tornando-a infrutífera.

[[v40-13-23]]

^<<v40-13-23,23>>^ E, finalmente, o que foi semeado em boa terra: este é aquele que ouve a palavra e a entende, e dá uma colheita de cem, sessenta e trinta por um".

[[v40-13-24]]

^<<v40-13-24,24>>^ Jesus lhes contou outra parábola, dizendo: "O Reino dos céus é como um homem que semeou boa semente em seu campo.

[[v40-13-25]]

^<<v40-13-25,25>>^ Mas enquanto todos dormiam, veio o seu inimigo e semeou o joio no meio do trigo e se foi.

[[v40-13-26]]

^<<v40-13-26,26>>^ Quando o trigo brotou e formou espigas, o joio também apareceu.

[[v40-13-27]]

^<<v40-13-27,27>>^ "Os servos do dono do campo dirigiram-se a ele e disseram: ‘O senhor não semeou boa semente em seu campo? Então, de onde veio o joio? ’

[[v40-13-28]]

^<<v40-13-28,28>>^ " ‘Um inimigo fez isso’, respondeu ele. "Os servos lhe perguntaram: ‘O senhor quer que vamos tirá-lo? ’

[[v40-13-29]]

^<<v40-13-29,29>>^ "Ele respondeu: ‘Não, porque, ao tirar o joio, vocês poderão arrancar com ele o trigo.

[[v40-13-30]]

^<<v40-13-30,30>>^ Deixem que cresçam juntos até à colheita. Então direi aos encarregados da colheita: Juntem primeiro o joio e amarrem-no em feixes para ser queimado; depois juntem o trigo e guardem-no no meu celeiro’ ".

[[v40-13-31]]

^<<v40-13-31,31>>^ E contou-lhes outra parábola: "O Reino dos céus é como um grão de mostarda que um homem plantou em seu campo.

[[v40-13-32]]

^<<v40-13-32,32>>^ Embora seja a menor dentre todas as sementes, quando cresce torna-se a maior das hortaliças e se transforma numa árvore, de modo que as aves do céu vêm fazer os seus ninhos em seus ramos".

[[v40-13-33]]

^<<v40-13-33,33>>^ E contou-lhes ainda outra parábola: "O Reino dos céus é como o fermento que uma mulher tomou e misturou com uma grande quantidade de farinha, e toda a massa ficou fermentada".

[[v40-13-34]]

^<<v40-13-34,34>>^ Jesus falou todas estas coisas à multidão por parábolas. Nada lhes dizia sem usar alguma parábola,

[[v40-13-35]]

^<<v40-13-35,35>>^ cumprindo-se, assim, o que fora dito pelo profeta: "Abrirei minha boca em parábolas, Proclamarei coisas ocultas Desde a criação do mundo".

[[v40-13-36]]

^<<v40-13-36,36>>^ Então ele deixou a multidão e foi para casa. Seus discípulos aproximaram-se dele e disseram: "Explica-nos a parábola do joio no campo".

[[v40-13-37]]

^<<v40-13-37,37>>^ Ele respondeu: "Aquele que semeou a boa semente é o Filho do homem.

[[v40-13-38]]

^<<v40-13-38,38>>^ O campo é o mundo, e a boa semente são os filhos do Reino. O joio são os filhos do Maligno,

[[v40-13-39]]

^<<v40-13-39,39>>^ e o inimigo que o semeia é o diabo. A colheita é o fim desta era, e os encarregados da colheita são anjos.

[[v40-13-40]]

^<<v40-13-40,40>>^ "Assim como o joio é colhido e queimado no fogo, assim também acontecerá no fim desta era.

[[v40-13-41]]

^<<v40-13-41,41>>^ O Filho do homem enviará os seus anjos, e eles tirarão do seu Reino tudo o que faz tropeçar e todos os que praticam o mal.

[[v40-13-42]]

^<<v40-13-42,42>>^ Eles os lançarão na fornalha ardente, onde haverá choro e ranger de dentes.

[[v40-13-43]]

^<<v40-13-43,43>>^ Então os justos brilharão como o sol no Reino do seu Pai. Aquele que tem ouvidos, ouça".

[[v40-13-44]]

^<<v40-13-44,44>>^ "O Reino dos céus é como um tesouro escondido num campo. Certo homem, tendo-o encontrado, escondeu-o de novo e, então, cheio de alegria, foi, vendeu tudo o que tinha e comprou aquele campo.

[[v40-13-45]]

^<<v40-13-45,45>>^ "O Reino dos céus também é como um negociante que procura pérolas preciosas.

[[v40-13-46]]

^<<v40-13-46,46>>^ Encontrando uma pérola de grande valor, foi, vendeu tudo o que tinha e a comprou".

[[v40-13-47]]

^<<v40-13-47,47>>^ "O Reino dos céus é ainda como uma rede que é lançada ao mar e apanha toda sorte de peixes.

[[v40-13-48]]

^<<v40-13-48,48>>^ Quando está cheia, os pescadores a puxam para a praia. Então se assentam e juntam os peixes bons em cestos, mas jogam fora os ruins.

[[v40-13-49]]

^<<v40-13-49,49>>^ Assim acontecerá no fim desta era. Os anjos virão, separarão os perversos dos justos

[[v40-13-50]]

^<<v40-13-50,50>>^ e lançarão aqueles na fornalha ardente, onde haverá choro e ranger de dentes".

[[v40-13-51]]

^<<v40-13-51,51>>^ Então perguntou Jesus: "Vocês entenderam todas essas coisas? " "Sim", responderam eles.

[[v40-13-52]]

^<<v40-13-52,52>>^ Ele lhes disse: "Por isso, todo mestre da lei instruído quanto ao Reino dos céus é como o dono de uma casa que tira do seu tesouro coisas novas e coisas velhas".

[[v40-13-53]]

^<<v40-13-53,53>>^ Tendo terminado de contar estas parábolas, Jesus saiu dali.

[[v40-13-54]]

^<<v40-13-54,54>>^ Chegando à sua cidade, começou a ensinar o povo na sinagoga. Todos ficaram admirados e perguntavam: "De onde lhe vêm esta sabedoria e estes poderes miraculosos?

[[v40-13-55]]

^<<v40-13-55,55>>^ Não é este o filho do carpinteiro? O nome de sua mãe não é Maria, e não são seus irmãos Tiago, José, Simão e Judas?

[[v40-13-56]]

^<<v40-13-56,56>>^ Não estão conosco todas as suas irmãs? De onde, pois, ele obteve todas essas coisas? "

[[v40-13-57]]

^<<v40-13-57,57>>^ E ficavam escandalizados por causa dele. Mas Jesus lhes disse: "Só em sua própria terra e em sua própria casa é que um profeta não tem honra".

[[v40-13-58]]

^<<v40-13-58,58>>^ E não realizou muitos milagres ali, por causa da incredulidade deles.

'''

xref:040-mateus/040-mateus-012.adoc#v40-12-0[&#60; Capítulo Anterior] | <<v40-13-0,Topo>> | xref:040-mateus/040-mateus-014.adoc#v40-14-0[Próximo Capítulo &#62;]