include::./index.adoc[]

[[v40-16-0]]
=== Mateus, 16
// nvi ?, NVI - Nova Versão Internacional

[[v40-16-1]]

^<<v40-16-1,1>>^ Os fariseus e os saduceus aproximaram-se de Jesus e o puseram à prova, pedindo-lhe que lhes mostrasse um sinal do céu.

[[v40-16-2]]

^<<v40-16-2,2>>^ Ele respondeu: "Quando a tarde vem, vocês dizem: ‘Vai fazer bom tempo, porque o céu está vermelho’,

[[v40-16-3]]

^<<v40-16-3,3>>^ e de manhã: ‘Hoje haverá tempestade, porque o céu está vermelho e nublado’. Vocês sabem interpretar o aspecto do céu, mas não sabem interpretar os sinais dos tempos!

[[v40-16-4]]

^<<v40-16-4,4>>^ Uma geração perversa e adúltera pede um sinal miraculoso, mas nenhum sinal lhe será dado, a não ser o sinal de Jonas". Então Jesus os deixou e retirou-se.

[[v40-16-5]]

^<<v40-16-5,5>>^ Indo os discípulos para o outro lado do mar, esqueceram-se de levar pão.

[[v40-16-6]]

^<<v40-16-6,6>>^ Disse-lhes Jesus: "Estejam atentos e tenham cuidado com o fermento dos fariseus e dos saduceus".

[[v40-16-7]]

^<<v40-16-7,7>>^ E eles discutiam entre si, dizendo: "É porque não trouxemos pão".

[[v40-16-8]]

^<<v40-16-8,8>>^ Percebendo a discussão, Jesus lhes perguntou: "Homens de pequena fé, por que vocês estão discutindo entre si sobre não terem pão?

[[v40-16-9]]

^<<v40-16-9,9>>^ Ainda não compreendem? Não se lembram dos cinco pães para os cinco mil e de quantos cestos vocês recolheram?

[[v40-16-10]]

^<<v40-16-10,10>>^ Nem dos sete pães para os quatro mil e de quantos cestos recolheram?

[[v40-16-11]]

^<<v40-16-11,11>>^ Como é que vocês não entendem que não era de pão que eu estava lhes falando? Mas tomem cuidado com o fermento dos fariseus e dos saduceus".

[[v40-16-12]]

^<<v40-16-12,12>>^ Então entenderam que não estava lhes dizendo que tomassem cuidado com o fermento de pão, mas com o ensino dos fariseus e dos saduceus.

[[v40-16-13]]

^<<v40-16-13,13>>^ Chegando Jesus à região de Cesaréia de Filipe, perguntou aos seus discípulos: "Quem os homens dizem que o Filho do homem é? "

[[v40-16-14]]

^<<v40-16-14,14>>^ Eles responderam: "Alguns dizem que é João Batista; outros, Elias; e, ainda outros, Jeremias ou um dos profetas".

[[v40-16-15]]

^<<v40-16-15,15>>^ "E vocês? ", perguntou ele. "Quem vocês dizem que eu sou? "

[[v40-16-16]]

^<<v40-16-16,16>>^ Simão Pedro respondeu: "Tu és o Cristo, o Filho do Deus vivo".

[[v40-16-17]]

^<<v40-16-17,17>>^ Respondeu Jesus: "Feliz é você, Simão, filho de Jonas! Porque isto não lhe foi revelado por carne ou sangue, mas por meu Pai que está nos céus.

[[v40-16-18]]

^<<v40-16-18,18>>^ E eu lhe digo que você é Pedro, e sobre esta pedra edificarei a minha igreja, e as portas do Hades não poderão vencê-la.

[[v40-16-19]]

^<<v40-16-19,19>>^ Eu lhe darei as chaves do Reino dos céus; o que você ligar na terra terá sido ligado nos céus, e o que você desligar na terra terá sido desligado nos céus".

[[v40-16-20]]

^<<v40-16-20,20>>^ Então advertiu a seus discípulos que não contassem a ninguém que ele era o Cristo.

[[v40-16-21]]

^<<v40-16-21,21>>^ Desde aquele momento Jesus começou a explicar aos seus discípulos que era necessário que ele fosse para Jerusalém e sofresse muitas coisas nas mãos dos líderes religiosos, dos chefes dos sacerdotes e dos mestres da lei, e fosse morto e ressuscitasse no terceiro dia.

[[v40-16-22]]

^<<v40-16-22,22>>^ Então Pedro, chamando-o à parte, começou a repreendê-lo, dizendo: "Nunca, Senhor! Isso nunca te acontecerá! "

[[v40-16-23]]

^<<v40-16-23,23>>^ Jesus virou-se e disse a Pedro: "Para trás de mim, Satanás! Você é uma pedra de tropeço para mim, e não pensa nas coisas de Deus, mas nas dos homens".

[[v40-16-24]]

^<<v40-16-24,24>>^ Então Jesus disse aos seus discípulos: "Se alguém quiser acompanhar-me, negue-se a si mesmo, tome a sua cruz e siga-me.

[[v40-16-25]]

^<<v40-16-25,25>>^ Pois quem quiser salvar a sua vida, a perderá, mas quem perder a vida por minha causa, a encontrará.

[[v40-16-26]]

^<<v40-16-26,26>>^ Pois, que adiantará ao homem ganhar o mundo inteiro e perder a sua alma? Ou, o que o homem poderá dar em troca de sua alma?

[[v40-16-27]]

^<<v40-16-27,27>>^ Pois o Filho do homem virá na glória de seu Pai, com os seus anjos, e então recompensará a cada um de acordo com o que tenha feito.

[[v40-16-28]]

^<<v40-16-28,28>>^ Garanto-lhes que alguns dos que aqui se acham não experimentarão a morte antes de verem o Filho do homem vindo em seu Reino".

'''

xref:040-mateus/040-mateus-015.adoc#v40-15-0[&#60; Capítulo Anterior] | <<v40-16-0,Topo>> | xref:040-mateus/040-mateus-017.adoc#v40-17-0[Próximo Capítulo &#62;]