include::./index.adoc[]

[[v40-19-0]]
=== Mateus, 19
// nvi ?, NVI - Nova Versão Internacional

[[v40-19-1]]

^<<v40-19-1,1>>^ Tendo acabado de dizer essas coisas, Jesus saiu da Galiléia e foi para a região da Judéia, no outro lado do Jordão.

[[v40-19-2]]

^<<v40-19-2,2>>^ Grandes multidões o seguiam, e ele as curou ali.

[[v40-19-3]]

^<<v40-19-3,3>>^ Alguns fariseus aproximaram-se dele para pô-lo à prova. E perguntaram-lhe: "É permitido ao homem divorciar-se de sua mulher por qualquer motivo? "

[[v40-19-4]]

^<<v40-19-4,4>>^ Ele respondeu: "Vocês não leram que, no princípio, o Criador ‘os fez homem e mulher’

[[v40-19-5]]

^<<v40-19-5,5>>^ e disse: ‘Por essa razão, o homem deixará pai e mãe e se unirá à sua mulher, e os dois se tornarão uma só carne’?

[[v40-19-6]]

^<<v40-19-6,6>>^ Assim, eles já não são dois, mas sim uma só carne. Portanto, o que Deus uniu, ninguém o separe".

[[v40-19-7]]

^<<v40-19-7,7>>^ Perguntaram eles: "Então, por que Moisés mandou dar uma certidão de divórcio à mulher e mandá-la embora? "

[[v40-19-8]]

^<<v40-19-8,8>>^ Jesus respondeu: "Moisés lhes permitiu divorciar-se de suas mulheres por causa da dureza de coração de vocês. Mas não foi assim desde o princípio.

[[v40-19-9]]

^<<v40-19-9,9>>^ Eu lhes digo que todo aquele que se divorciar de sua mulher, exceto por imoralidade sexual, e se casar com outra mulher, estará cometendo adultério".

[[v40-19-10]]

^<<v40-19-10,10>>^ Os discípulos lhe disseram: "Se esta é a situação entre o homem e sua mulher, é melhor não casar".

[[v40-19-11]]

^<<v40-19-11,11>>^ Jesus respondeu: "Nem todos têm condições de aceitar esta palavra; somente aqueles a quem isso é dado.

[[v40-19-12]]

^<<v40-19-12,12>>^ Alguns são eunucos porque nasceram assim; outros foram feitos assim pelos homens; outros ainda se fizeram eunucos por causa do Reino dos céus. Quem puder aceitar isso, aceite".

[[v40-19-13]]

^<<v40-19-13,13>>^ Depois trouxeram crianças a Jesus, para que lhes impusesse as mãos e orasse por elas. Mas os discípulos os repreendiam.

[[v40-19-14]]

^<<v40-19-14,14>>^ Então disse Jesus: "Deixem vir a mim as crianças e não as impeçam; pois o Reino dos céus pertence aos que são semelhantes a elas".

[[v40-19-15]]

^<<v40-19-15,15>>^ Depois de lhes impor as mãos, partiu dali.

[[v40-19-16]]

^<<v40-19-16,16>>^ Eis que alguém se aproximou de Jesus e lhe perguntou: "Mestre, que farei de bom para ter a vida eterna? "

[[v40-19-17]]

^<<v40-19-17,17>>^ Respondeu-lhe Jesus: "Por que você me pergunta sobre o que é bom? Há somente um que é bom. Se você quer entrar na vida, obedeça aos mandamentos".

[[v40-19-18]]

^<<v40-19-18,18>>^ "Quais? ", perguntou ele. Jesus respondeu: " ‘Não matarás, não adulterarás, não furtarás, não darás falso testemunho,

[[v40-19-19]]

^<<v40-19-19,19>>^ honra teu pai e tua mãe’ e ‘amarás o teu próximo como a ti mesmo’".

[[v40-19-20]]

^<<v40-19-20,20>>^ Disse-lhe o jovem: "A tudo isso tenho obedecido. O que me falta ainda? "

[[v40-19-21]]

^<<v40-19-21,21>>^ Jesus respondeu: "Se você quer ser perfeito, vá, venda os seus bens e dê o dinheiro aos pobres, e você terá um tesouro no céu. Depois, venha e siga-me".

[[v40-19-22]]

^<<v40-19-22,22>>^ Ouvindo isso, o jovem afastou-se triste, porque tinha muitas riquezas.

[[v40-19-23]]

^<<v40-19-23,23>>^ Então Jesus disse aos discípulos: "Digo-lhes a verdade: Dificilmente um rico entrará no Reino dos céus.

[[v40-19-24]]

^<<v40-19-24,24>>^ E lhes digo ainda: é mais fácil passar um camelo pelo fundo de uma agulha do que um rico entrar no Reino de Deus".

[[v40-19-25]]

^<<v40-19-25,25>>^ Ao ouvirem isso, os discípulos ficaram perplexos e perguntaram: "Neste caso, quem pode ser salvo? "

[[v40-19-26]]

^<<v40-19-26,26>>^ Jesus olhou para eles e respondeu: "Para o homem é impossível, mas para Deus todas as coisas são possíveis".

[[v40-19-27]]

^<<v40-19-27,27>>^ Então Pedro lhe respondeu: "Nós deixamos tudo para seguir-te! Que será de nós? "

[[v40-19-28]]

^<<v40-19-28,28>>^ Jesus lhes disse: "Digo-lhes a verdade: Por ocasião da regeneração de todas as coisas, quando o Filho do homem se assentar em seu trono glorioso, vocês que me seguiram também se assentarão em doze tronos, para julgar as doze tribos de Israel.

[[v40-19-29]]

^<<v40-19-29,29>>^ E todos os que tiverem deixado casas, irmãos, irmãs, pai, mãe, filhos ou campos, por minha causa, receberão cem vezes mais e herdarão a vida eterna.

[[v40-19-30]]

^<<v40-19-30,30>>^ Contudo, muitos primeiros serão últimos, e muitos últimos serão primeiros".

'''

xref:040-mateus/040-mateus-018.adoc#v40-18-0[&#60; Capítulo Anterior] | <<v40-19-0,Topo>> | xref:040-mateus/040-mateus-020.adoc#v40-20-0[Próximo Capítulo &#62;]