include::./index.adoc[]

[[v40-14-0]]
=== Mateus, 14
// nvi ?, NVI - Nova Versão Internacional

[[v40-14-1]]

^<<v40-14-1,1>>^ Por aquele tempo Herodes, o tetrarca, ouviu os relatos a respeito de Jesus

[[v40-14-2]]

^<<v40-14-2,2>>^ e disse aos que o serviam: "Este é João Batista; ele ressuscitou dos mortos! Por isso estão operando nele poderes miraculosos".

[[v40-14-3]]

^<<v40-14-3,3>>^ Pois Herodes havia prendido e amarrado João, colocando-o na prisão por causa de Herodias, mulher de Filipe, seu irmão,

[[v40-14-4]]

^<<v40-14-4,4>>^ porquanto João lhe dizia: "Não te é permitido viver com ela".

[[v40-14-5]]

^<<v40-14-5,5>>^ Herodes queria matá-lo, mas tinha medo do povo, porque este o considerava profeta.

[[v40-14-6]]

^<<v40-14-6,6>>^ No aniversário de Herodes, a filha de Herodias dançou diante de todos, e agradou tanto a Herodes

[[v40-14-7]]

^<<v40-14-7,7>>^ que ele prometeu sob juramento dar-lhe o que ela pedisse.

[[v40-14-8]]

^<<v40-14-8,8>>^ Influenciada por sua mãe, ela disse: "Dá-me aqui, num prato, a cabeça de João Batista".

[[v40-14-9]]

^<<v40-14-9,9>>^ O rei ficou aflito, mas, por causa dos juramento e dos convidados, ordenou que lhe fosse dado o que ela pedia

[[v40-14-10]]

^<<v40-14-10,10>>^ e mandou decapitar João na prisão.

[[v40-14-11]]

^<<v40-14-11,11>>^ Sua cabeça foi levada num prato e entregue à jovem, que a levou à sua mãe.

[[v40-14-12]]

^<<v40-14-12,12>>^ Os discípulos de João vieram, levaram o seu corpo e o sepultaram. Depois foram contar isso a Jesus.

[[v40-14-13]]

^<<v40-14-13,13>>^ Ouvindo o que havia ocorrido, Jesus retirou-se de barco em particular para um lugar deserto. As multidões, ao ouvirem falar disso, saíram das cidades e o seguiram a pé.

[[v40-14-14]]

^<<v40-14-14,14>>^ Quando Jesus saiu do barco e viu tão grande multidão, teve compaixão deles e curou os seus doentes.

[[v40-14-15]]

^<<v40-14-15,15>>^ Ao cair da tarde, os discípulos aproximaram-se dele e disseram: "Este é um lugar deserto, e já está ficando tarde. Manda embora a multidão para que possam ir aos povoados comprar comida".

[[v40-14-16]]

^<<v40-14-16,16>>^ Respondeu Jesus: "Eles não precisam ir. Dêem-lhes vocês algo para comer".

[[v40-14-17]]

^<<v40-14-17,17>>^ Eles lhe disseram: "Tudo o que temos aqui são cinco pães e dois peixes".

[[v40-14-18]]

^<<v40-14-18,18>>^ "Tragam-nos aqui para mim", disse ele.

[[v40-14-19]]

^<<v40-14-19,19>>^ E ordenou que a multidão se assentasse na grama. Tomando os cinco pães e os dois peixes e, olhando para o céu, deu graças e partiu os pães. Em seguida, deu-os aos discípulos, e estes à multidão.

[[v40-14-20]]

^<<v40-14-20,20>>^ Todos comeram e ficaram satisfeitos, e os discípulos recolheram doze cestos cheios de pedaços que sobraram.

[[v40-14-21]]

^<<v40-14-21,21>>^ Os que comeram foram cerca de cinco mil homens, sem contar mulheres e crianças.

[[v40-14-22]]

^<<v40-14-22,22>>^ Logo em seguida, Jesus insistiu com os discípulos para que entrassem no barco e fossem adiante dele para o outro lado, enquanto ele despedia a multidão.

[[v40-14-23]]

^<<v40-14-23,23>>^ Tendo despedido a multidão, subiu sozinho a um monte para orar. Ao anoitecer, ele estava ali sozinho,

[[v40-14-24]]

^<<v40-14-24,24>>^ mas o barco já estava a considerável distância da terra, fustigado pelas ondas, porque o vento soprava contra ele.

[[v40-14-25]]

^<<v40-14-25,25>>^ Alta madrugada, Jesus dirigiu-se a eles, andando sobre o mar.

[[v40-14-26]]

^<<v40-14-26,26>>^ Quando o viram andando sobre o mar, ficaram aterrorizados e disseram: "É um fantasma! " E gritaram de medo.

[[v40-14-27]]

^<<v40-14-27,27>>^ Mas Jesus imediatamente lhes disse: "Coragem! Sou eu. Não tenham medo! "

[[v40-14-28]]

^<<v40-14-28,28>>^ "Senhor", disse Pedro, "se és tu, manda-me ir ao teu encontro por sobre as águas".

[[v40-14-29]]

^<<v40-14-29,29>>^ "Venha", respondeu ele. Então Pedro saiu do barco, andou sobre a água e foi na direção de Jesus.

[[v40-14-30]]

^<<v40-14-30,30>>^ Mas, quando reparou no vento, ficou com medo e, começando a afundar, gritou: "Senhor, salva-me! "

[[v40-14-31]]

^<<v40-14-31,31>>^ Imediatamente Jesus estendeu a mão e o segurou. E disse: "Homem de pequena fé, porque você duvidou? "

[[v40-14-32]]

^<<v40-14-32,32>>^ Quando entraram no barco, o vento cessou.

[[v40-14-33]]

^<<v40-14-33,33>>^ Então os que estavam no barco o adoraram, dizendo: "Verdadeiramente tu és o Filho de Deus".

[[v40-14-34]]

^<<v40-14-34,34>>^ Depois de atravessarem o mar, chegaram a Genesaré.

[[v40-14-35]]

^<<v40-14-35,35>>^ Quando os homens daquele lugar reconheceram Jesus, espalharam a notícia em toda aquela região e lhe trouxeram os seus doentes.

[[v40-14-36]]

^<<v40-14-36,36>>^ Suplicavam-lhe que apenas pudessem tocar na borda do seu manto; e todos os que nele tocaram foram curados.

'''

xref:040-mateus/040-mateus-013.adoc#v40-13-0[&#60; Capítulo Anterior] | <<v40-14-0,Topo>> | xref:040-mateus/040-mateus-015.adoc#v40-15-0[Próximo Capítulo &#62;]