include::./index.adoc[]

[[v40-1-0]]
=== Mateus, 1
// nvi ?, NVI - Nova Versão Internacional

[[v40-1-1]]

^<<v40-1-1,1>>^ Registro da genealogia de Jesus Cristo, filho de Davi, filho de Abraão:

[[v40-1-2]]

^<<v40-1-2,2>>^ Abraão gerou Isaque; Isaque gerou Jacó; Jacó gerou Judá e seus irmãos;

[[v40-1-3]]

^<<v40-1-3,3>>^ Judá gerou Perez e Zerá, cuja mãe foi Tamar; Perez gerou Esrom; Esrom gerou Arão;

[[v40-1-4]]

^<<v40-1-4,4>>^ Arão gerou Aminadabe; Aminadabe gerou Naassom; Naassom gerou Salmom;

[[v40-1-5]]

^<<v40-1-5,5>>^ Salmom gerou Boaz, cuja mãe foi Raabe; Boaz gerou Obede, cuja mãe foi Rute; Obede gerou Jessé;

[[v40-1-6]]

^<<v40-1-6,6>>^ e Jessé gerou o rei Davi. Davi gerou Salomão, cuja mãe tinha sido mulher de Urias;

[[v40-1-7]]

^<<v40-1-7,7>>^ Salomão gerou Roboão; Roboão gerou Abias; Abias gerou Asa;

[[v40-1-8]]

^<<v40-1-8,8>>^ Asa gerou Josafá; Josafá gerou Jorão; Jorão gerou Uzias;

[[v40-1-9]]

^<<v40-1-9,9>>^ Uzias gerou Jotão; Jotão gerou Acaz; Acaz gerou Ezequias;

[[v40-1-10]]

^<<v40-1-10,10>>^ Ezequias gerou Manassés; Manassés gerou Amom; Amom gerou Josias;

[[v40-1-11]]

^<<v40-1-11,11>>^ e Josias gerou Jeconias e seus irmãos, no tempo do exílio na Babilônia.

[[v40-1-12]]

^<<v40-1-12,12>>^ Depois do exílio na Babilônia: Jeconias gerou Salatiel; Salatiel gerou Zorobabel;

[[v40-1-13]]

^<<v40-1-13,13>>^ Zorobabel gerou Abiúde; Abiúde gerou Eliaquim; Eliaquim gerou Azor;

[[v40-1-14]]

^<<v40-1-14,14>>^ Azor gerou Sadoque; Sadoque gerou Aquim; Aquim gerou Eliúde;

[[v40-1-15]]

^<<v40-1-15,15>>^ Eliúde gerou Eleazar; Eleazar gerou Matã; Matã gerou Jacó;

[[v40-1-16]]

^<<v40-1-16,16>>^ e Jacó gerou José, marido de Maria, da qual nasceu Jesus, que é chamado Cristo.

[[v40-1-17]]

^<<v40-1-17,17>>^ Assim, ao todo houve catorze gerações de Abraão a Davi, catorze de Davi até o exílio na Babilônia e catorze do exílio até o Cristo.

[[v40-1-18]]

^<<v40-1-18,18>>^ Foi assim o nascimento de Jesus Cristo: Maria, sua mãe, estava prometida em casamento a José, mas, antes que se unissem, achou-se grávida pelo Espírito Santo.

[[v40-1-19]]

^<<v40-1-19,19>>^ Por ser José, seu marido, um homem justo, e não querendo expô-la à desonra pública, pretendia anular o casamento secretamente.

[[v40-1-20]]

^<<v40-1-20,20>>^ Mas, depois de ter pensado nisso, apareceu-lhe um anjo do Senhor em sonho e disse: "José, filho de Davi, não tema receber Maria como sua esposa, pois o que nela foi gerado procede do Espírito Santo.

[[v40-1-21]]

^<<v40-1-21,21>>^ Ela dará à luz um filho, e você deverá dar-lhe o nome de Jesus, porque ele salvará o seu povo dos seus pecados".

[[v40-1-22]]

^<<v40-1-22,22>>^ Tudo isso aconteceu para que se cumprisse o que o Senhor dissera pelo profeta:

[[v40-1-23]]

^<<v40-1-23,23>>^ "A virgem ficará grávida e dará à luz um filho, e lhe chamarão Emanuel" que significa "Deus conosco".

[[v40-1-24]]

^<<v40-1-24,24>>^ Ao acordar, José fez o que o anjo do Senhor lhe tinha ordenado e recebeu Maria como sua esposa.

[[v40-1-25]]

^<<v40-1-25,25>>^ Mas não teve relações com ela enquanto ela não deu à luz um filho. E ele lhe pôs o nome de Jesus.

'''

xref:039-malaquias/039-malaquias-004.adoc#v39-4-0[&#60; Capítulo Anterior] | <<v40-1-0,Topo>> | xref:040-mateus/040-mateus-002.adoc#v40-2-0[Próximo Capítulo &#62;]