include::./index.adoc[]

[[v40-3-0]]
=== Mateus, 3
// nvi ?, NVI - Nova Versão Internacional

[[v40-3-1]]

^<<v40-3-1,1>>^ Naqueles dias surgiu João Batista, pregando no deserto da Judéia.

[[v40-3-2]]

^<<v40-3-2,2>>^ Ele dizia: "Arrependam-se, porque o Reino dos céus está próximo".

[[v40-3-3]]

^<<v40-3-3,3>>^ Este é aquele que foi anunciado pelo profeta Isaías: "Voz do que clama no deserto: ‘Preparem o caminho para o Senhor, façam veredas retas para ele’ ".

[[v40-3-4]]

^<<v40-3-4,4>>^ As roupas de João eram feitas de pêlos de camelo, e ele usava um cinto de couro na cintura. O seu alimento era gafanhotos e mel silvestre.

[[v40-3-5]]

^<<v40-3-5,5>>^ A ele vinha gente de Jerusalém, de toda a Judéia e de toda a região ao redor do Jordão.

[[v40-3-6]]

^<<v40-3-6,6>>^ Confessando os seus pecados, eram batizados por ele no rio Jordão.

[[v40-3-7]]

^<<v40-3-7,7>>^ Quando viu que muitos fariseus e saduceus vinham para onde ele estava batizando, disse-lhes: "Raça de víboras! Quem lhes deu a idéia de fugir da ira que se aproxima?

[[v40-3-8]]

^<<v40-3-8,8>>^ Dêem fruto que mostre o arrependimento!

[[v40-3-9]]

^<<v40-3-9,9>>^ Não pensem que vocês podem dizer a si mesmos: ‘Abraão é nosso pai’. Pois eu lhes digo que destas pedras Deus pode fazer surgir filhos a Abraão.

[[v40-3-10]]

^<<v40-3-10,10>>^ O machado já está posto à raiz das árvores, e toda árvore que não der bom fruto será cortada e lançada ao fogo.

[[v40-3-11]]

^<<v40-3-11,11>>^ "Eu os batizo com água para arrependimento. Mas depois de mim vem alguém mais poderoso do que eu, tanto que não sou digno nem de levar as suas sandálias. Ele os batizará com o Espírito Santo e com fogo.

[[v40-3-12]]

^<<v40-3-12,12>>^ Ele traz a pá em sua mão e limpará sua eira, juntando seu trigo no celeiro, mas queimará a palha com fogo que nunca se apaga".

[[v40-3-13]]

^<<v40-3-13,13>>^ Então Jesus veio da Galiléia ao Jordão para ser batizado por João.

[[v40-3-14]]

^<<v40-3-14,14>>^ João, porém, tentou impedi-lo, dizendo: "Eu preciso ser batizado por ti, e tu vens a mim? "

[[v40-3-15]]

^<<v40-3-15,15>>^ Respondeu Jesus: "Deixe assim por enquanto; convém que assim façamos, para cumprir toda a justiça". E João concordou.

[[v40-3-16]]

^<<v40-3-16,16>>^ Assim que Jesus foi batizado, saiu da água. Naquele momento os céus se abriram, e ele viu o Espírito de Deus descendo como pomba e pousando sobre ele.

[[v40-3-17]]

^<<v40-3-17,17>>^ Então uma voz dos céus disse: "Este é o meu Filho amado, em quem me agrado".

'''

xref:040-mateus/040-mateus-002.adoc#v40-2-0[&#60; Capítulo Anterior] | <<v40-3-0,Topo>> | xref:040-mateus/040-mateus-004.adoc#v40-4-0[Próximo Capítulo &#62;]