include::./index.adoc[]

[[v40-18-0]]
=== Mateus, 18
// nvi ?, NVI - Nova Versão Internacional

[[v40-18-1]]

^<<v40-18-1,1>>^ Naquele momento os discípulos chegaram a Jesus e perguntaram: "Quem é o maior no Reino dos céus? "

[[v40-18-2]]

^<<v40-18-2,2>>^ Chamando uma criança, colocou-a no meio deles,

[[v40-18-3]]

^<<v40-18-3,3>>^ e disse: "Eu lhes asseguro que, a não ser que vocês se convertam e se tornem como crianças, jamais entrarão no Reino dos céus.

[[v40-18-4]]

^<<v40-18-4,4>>^ Portanto, quem se faz humilde como esta criança, este é o maior no Reino dos céus.

[[v40-18-5]]

^<<v40-18-5,5>>^ "Quem recebe uma destas crianças em meu nome, está me recebendo.

[[v40-18-6]]

^<<v40-18-6,6>>^ Mas se alguém fizer tropeçar um destes pequeninos que crêem em mim, melhor lhe seria amarrar uma pedra de moinho no pescoço e se afogar nas profundezas do mar.

[[v40-18-7]]

^<<v40-18-7,7>>^ "Ai do mundo, por causa das coisas que fazem tropeçar! É inevitável que tais coisas aconteçam, mas ai daquele por meio de quem elas acontecem!

[[v40-18-8]]

^<<v40-18-8,8>>^ Se a sua mão ou o seu pé o fizerem tropeçar, corte-os e jogue-os fora. É melhor entrar na vida mutilado ou aleijado do que, tendo as duas mãos ou os dois pés, ser lançado no fogo eterno.

[[v40-18-9]]

^<<v40-18-9,9>>^ E se o seu olho o fizer tropeçar, arranque-o e jogue-o fora. É melhor entrar na vida com um só olho do que, tendo os dois olhos, ser lançado no fogo do inferno".

[[v40-18-10]]

^<<v40-18-10,10>>^ "Cuidado para não desprezarem um só destes pequeninos! Pois eu lhes digo que os anjos deles nos céus estão sempre vendo a face de meu Pai celeste.

[[v40-18-11]]

^<<v40-18-11,11>>^ O Filho do homem veio para salvar o que se havia perdido.

[[v40-18-12]]

^<<v40-18-12,12>>^ "O que acham vocês? Se alguém possui cem ovelhas, e uma delas se perde, não deixará as noventa e nove nos montes, indo procurar a que se perdeu?

[[v40-18-13]]

^<<v40-18-13,13>>^ E se conseguir encontrá-la, garanto-lhes que ele ficará mais contente com aquela ovelha do que com as noventa e nove que não se perderam.

[[v40-18-14]]

^<<v40-18-14,14>>^ Da mesma forma, o Pai de vocês, que está nos céus, não quer que nenhum destes pequeninos se perca".

[[v40-18-15]]

^<<v40-18-15,15>>^ "Se o seu irmão pecar contra você, vá e, a sós com ele, mostre-lhe o erro. Se ele o ouvir, você ganhou seu irmão.

[[v40-18-16]]

^<<v40-18-16,16>>^ Mas se ele não o ouvir, leve consigo mais um ou dois outros, de modo que ‘qualquer acusação seja confirmada pelo depoimento de duas ou três testemunhas’.

[[v40-18-17]]

^<<v40-18-17,17>>^ Se ele se recusar a ouvi-los, conte à igreja; e se ele se recusar a ouvir também a igreja, trate-o como pagão ou publicano.

[[v40-18-18]]

^<<v40-18-18,18>>^ "Digo-lhes a verdade: Tudo o que vocês ligarem na terra terá sido ligado no céu, e tudo o que vocês desligarem na terra terá sido desligado no céu.

[[v40-18-19]]

^<<v40-18-19,19>>^ "Também lhes digo que se dois de vocês concordarem na terra em qualquer assunto sobre o qual pedirem, isso lhes será feito por meu Pai que está nos céus.

[[v40-18-20]]

^<<v40-18-20,20>>^ Pois onde se reunirem dois ou três em meu nome, ali eu estou no meio deles".

[[v40-18-21]]

^<<v40-18-21,21>>^ Então Pedro aproximou-se de Jesus e perguntou: "Senhor, quantas vezes deverei perdoar a meu irmão quando ele pecar contra mim? Até sete vezes? "

[[v40-18-22]]

^<<v40-18-22,22>>^ Jesus respondeu: "Eu lhe digo: não até sete, mas até setenta vezes sete.

[[v40-18-23]]

^<<v40-18-23,23>>^ "Por isso, o Reino dos céus é como um rei que desejava acertar contas com seus servos.

[[v40-18-24]]

^<<v40-18-24,24>>^ Quando começou o acerto, foi trazido à sua presença um que lhe devia uma enorme quantidade de prata.

[[v40-18-25]]

^<<v40-18-25,25>>^ Como não tinha condições de pagar, o senhor ordenou que ele, sua mulher, seus filhos e tudo o que ele possuía fossem vendidos para pagar a dívida.

[[v40-18-26]]

^<<v40-18-26,26>>^ "O servo prostrou-se diante dele e lhe implorou: ‘Tem paciência comigo, e eu te pagarei tudo’.

[[v40-18-27]]

^<<v40-18-27,27>>^ O senhor daquele servo teve compaixão dele, cancelou a dívida e o deixou ir.

[[v40-18-28]]

^<<v40-18-28,28>>^ "Mas quando aquele servo saiu, encontrou um de seus conservos, que lhe devia cem denários. Agarrou-o e começou a sufocá-lo, dizendo: ‘Pague-me o que me deve! ’

[[v40-18-29]]

^<<v40-18-29,29>>^ "Então o seu conservo caiu de joelhos e implorou-lhe: ‘Tenha paciência comigo, e eu lhe pagarei’.

[[v40-18-30]]

^<<v40-18-30,30>>^ "Mas ele não quis. Antes, saiu e mandou lançá-lo na prisão, até que pagasse a dívida.

[[v40-18-31]]

^<<v40-18-31,31>>^ Quando os outros servos, companheiros dele, viram o que havia acontecido, ficaram muito tristes e foram contar ao seu senhor tudo o que havia acontecido.

[[v40-18-32]]

^<<v40-18-32,32>>^ "Então o senhor chamou o servo e disse: ‘Servo mau, cancelei toda a sua dívida porque você me implorou.

[[v40-18-33]]

^<<v40-18-33,33>>^ Você não devia ter tido misericórdia do seu conservo como eu tive de você? ’

[[v40-18-34]]

^<<v40-18-34,34>>^ Irado, seu senhor entregou-o aos torturadores, até que pagasse tudo o que devia.

[[v40-18-35]]

^<<v40-18-35,35>>^ "Assim também lhes fará meu Pai celestial, se cada um de vocês não perdoar de coração a seu irmão".

'''

xref:040-mateus/040-mateus-017.adoc#v40-17-0[&#60; Capítulo Anterior] | <<v40-18-0,Topo>> | xref:040-mateus/040-mateus-019.adoc#v40-19-0[Próximo Capítulo &#62;]