include::./index.adoc[]

[[v40-22-0]]
=== Mateus, 22
// nvi ?, NVI - Nova Versão Internacional

[[v40-22-1]]

^<<v40-22-1,1>>^ Jesus lhes falou novamente por parábolas, dizendo:

[[v40-22-2]]

^<<v40-22-2,2>>^ "O Reino dos céus é como um rei que preparou um banquete de casamento para seu filho.

[[v40-22-3]]

^<<v40-22-3,3>>^ Enviou seus servos aos que tinham sido convidados para o banquete, dizendo-lhes que viessem; mas eles não quiseram vir.

[[v40-22-4]]

^<<v40-22-4,4>>^ "De novo enviou outros servos e disse: ‘Digam aos que foram convidados que preparei meu banquete: meus bois e meus novilhos gordos foram abatidos, e tudo está preparado. Venham para o banquete de casamento! ’

[[v40-22-5]]

^<<v40-22-5,5>>^ "Mas eles não lhes deram atenção e saíram, um para o seu campo, outro para os seus negócios.

[[v40-22-6]]

^<<v40-22-6,6>>^ Os restantes, agarrando os servos, maltrataram-nos e os mataram.

[[v40-22-7]]

^<<v40-22-7,7>>^ O rei ficou irado e, enviando o seu exército, destruiu aqueles assassinos e queimou a cidade deles.

[[v40-22-8]]

^<<v40-22-8,8>>^ "Então disse a seus servos: ‘O banquete de casamento está pronto, mas os meus convidados não eram dignos.

[[v40-22-9]]

^<<v40-22-9,9>>^ Vão às esquinas e convidem para o banquete todos os que vocês encontrarem’.

[[v40-22-10]]

^<<v40-22-10,10>>^ Então os servos saíram para as ruas e reuniram todas as pessoas que puderam encontrar, gente boa e gente má, e a sala do banquete de casamento ficou cheia de convidados.

[[v40-22-11]]

^<<v40-22-11,11>>^ "Mas quando o rei entrou para ver os convidados, notou ali um homem que não estava usando veste nupcial.

[[v40-22-12]]

^<<v40-22-12,12>>^ E lhe perguntou: ‘Amigo, como você entrou aqui sem veste nupcial? ’ O homem emudeceu.

[[v40-22-13]]

^<<v40-22-13,13>>^ "Então o rei disse aos que serviam: ‘Amarrem-lhe as mãos e os pés, e lancem-no para fora, nas trevas; ali haverá choro e ranger de dentes’.

[[v40-22-14]]

^<<v40-22-14,14>>^ "Pois muitos são chamados, mas poucos são escolhidos".

[[v40-22-15]]

^<<v40-22-15,15>>^ Então os fariseus saíram e começaram a planejar um meio de enredá-lo em suas próprias palavras.

[[v40-22-16]]

^<<v40-22-16,16>>^ Enviaram-lhe seus discípulos juntamente com os herodianos que lhe disseram: "Mestre, sabemos que és íntegro e que ensinas o caminho de Deus conforme a verdade. Tu não te deixas influenciar por ninguém, porque não te prendes à aparência dos homens.

[[v40-22-17]]

^<<v40-22-17,17>>^ Dize-nos, pois: Qual é a tua opinião? É certo pagar imposto a César ou não? "

[[v40-22-18]]

^<<v40-22-18,18>>^ Mas Jesus, percebendo a má intenção deles, perguntou: "Hipócritas! Por que vocês estão me pondo à prova?

[[v40-22-19]]

^<<v40-22-19,19>>^ Mostrem-me a moeda usada para pagar o imposto". Eles lhe mostraram um denário,

[[v40-22-20]]

^<<v40-22-20,20>>^ e ele lhes perguntou: "De quem é esta imagem e esta inscrição? "

[[v40-22-21]]

^<<v40-22-21,21>>^ "De César", responderam eles. E ele lhes disse: "Então, dêem a César o que é de César e a Deus o que é de Deus".

[[v40-22-22]]

^<<v40-22-22,22>>^ Ao ouvirem isso, eles ficaram admirados; e, deixando-o, retiraram-se.

[[v40-22-23]]

^<<v40-22-23,23>>^ Naquele mesmo dia, os saduceus, que dizem que não há ressurreição, aproximaram-se dele com a seguinte questão:

[[v40-22-24]]

^<<v40-22-24,24>>^ "Mestre, Moisés disse que se um homem morrer sem deixar filhos, seu irmão deverá casar-se com a viúva e dar-lhe descendência.

[[v40-22-25]]

^<<v40-22-25,25>>^ Entre nós havia sete irmãos. O primeiro casou-se e morreu. Como não teve filhos, deixou a mulher para seu irmão.

[[v40-22-26]]

^<<v40-22-26,26>>^ A mesma coisa aconteceu com o segundo, com o terceiro, até o sétimo.

[[v40-22-27]]

^<<v40-22-27,27>>^ Finalmente, depois de todos, morreu a mulher.

[[v40-22-28]]

^<<v40-22-28,28>>^ Pois bem, na ressurreição, de qual dos sete ela será esposa, visto que todos foram casados com ela? "

[[v40-22-29]]

^<<v40-22-29,29>>^ Jesus respondeu: "Vocês estão enganados porque não conhecem as Escrituras nem o poder de Deus!

[[v40-22-30]]

^<<v40-22-30,30>>^ Na ressurreição, as pessoas não se casam nem são dadas em casamento; mas são como os anjos no céu.

[[v40-22-31]]

^<<v40-22-31,31>>^ E quanto à ressurreição dos mortos, vocês não leram o que Deus lhes disse:

[[v40-22-32]]

^<<v40-22-32,32>>^ ‘Eu sou o Deus de Abraão, o Deus de Isaque e o Deus de Jacó’? Ele não é Deus de mortos, mas de vivos! "

[[v40-22-33]]

^<<v40-22-33,33>>^ Ouvindo isso, a multidão ficou admirada com o seu ensino.

[[v40-22-34]]

^<<v40-22-34,34>>^ Ao ouvirem dizer que Jesus havia deixado os saduceus sem resposta, os fariseus se reuniram.

[[v40-22-35]]

^<<v40-22-35,35>>^ Um deles, perito na lei, o pôs à prova com esta pergunta:

[[v40-22-36]]

^<<v40-22-36,36>>^ "Mestre, qual é o maior mandamento da Lei? "

[[v40-22-37]]

^<<v40-22-37,37>>^ Respondeu Jesus: " ‘Ame o Senhor, o seu Deus de todo o seu coração, de toda a sua alma e de todo o seu entendimento’.

[[v40-22-38]]

^<<v40-22-38,38>>^ Este é o primeiro e maior mandamento.

[[v40-22-39]]

^<<v40-22-39,39>>^ E o segundo é semelhante a ele: ‘Ame o seu próximo como a si mesmo’.

[[v40-22-40]]

^<<v40-22-40,40>>^ Destes dois mandamentos dependem toda a Lei e os Profetas".

[[v40-22-41]]

^<<v40-22-41,41>>^ Estando os fariseus reunidos, Jesus lhes perguntou:

[[v40-22-42]]

^<<v40-22-42,42>>^ "O que vocês pensam a respeito do Cristo? De quem ele é filho? " "É filho de Davi", responderam eles.

[[v40-22-43]]

^<<v40-22-43,43>>^ Ele lhes disse: "Então, como é que Davi, falando pelo Espírito, o chama ‘Senhor’? Pois ele afirma:

[[v40-22-44]]

^<<v40-22-44,44>>^ ‘O Senhor disse ao meu Senhor: "Senta-te à minha direita, até que eu ponha os teus inimigos debaixo de teus pés" ’.

[[v40-22-45]]

^<<v40-22-45,45>>^ Se, pois, Davi o chama ‘Senhor’, como pode ser ele seu filho? "

[[v40-22-46]]

^<<v40-22-46,46>>^ Ninguém conseguia responder-lhe uma palavra; e daquele dia em diante, ninguém jamais se atreveu a lhe fazer perguntas.

'''

xref:040-mateus/040-mateus-021.adoc#v40-21-0[&#60; Capítulo Anterior] | <<v40-22-0,Topo>> | xref:040-mateus/040-mateus-023.adoc#v40-23-0[Próximo Capítulo &#62;]