include::./index.adoc[]

[[v40-12-0]]
=== Mateus, 12
// nvi ?, NVI - Nova Versão Internacional

[[v40-12-1]]

^<<v40-12-1,1>>^ Naquela ocasião Jesus passou pelas lavouras de cereal no sábado. Seus discípulos estavam com fome e começaram a colher espigas para comê-las.

[[v40-12-2]]

^<<v40-12-2,2>>^ Os fariseus, vendo aquilo, lhe disseram: "Olha, os teus discípulos estão fazendo o que não é permitido no sábado".

[[v40-12-3]]

^<<v40-12-3,3>>^ Ele respondeu: "Vocês não leram o que fez Davi quando ele e seus companheiros estavam com fome?

[[v40-12-4]]

^<<v40-12-4,4>>^ Ele entrou na casa de Deus, e juntamente com os seus companheiros comeu os pães da Presença, o que não lhes era permitido fazer, mas apenas aos sacerdotes.

[[v40-12-5]]

^<<v40-12-5,5>>^ Ou vocês não leram na Lei que, no sábado, os sacerdotes no templo profanam esse dia e, contudo, ficam sem culpa?

[[v40-12-6]]

^<<v40-12-6,6>>^ Eu lhes digo que aqui está o que é maior do que o templo.

[[v40-12-7]]

^<<v40-12-7,7>>^ Se vocês soubessem o que significam estas palavras: ‘Desejo misericórdia, não sacrifícios’, não teriam condenado inocentes.

[[v40-12-8]]

^<<v40-12-8,8>>^ Pois o Filho do homem é Senhor do sábado".

[[v40-12-9]]

^<<v40-12-9,9>>^ Saindo daquele lugar, dirigiu-se à sinagoga deles,

[[v40-12-10]]

^<<v40-12-10,10>>^ e estava ali um homem com uma das mãos atrofiada. Procurando um motivo para acusar Jesus, eles lhe perguntaram: "É permitido curar no sábado? "

[[v40-12-11]]

^<<v40-12-11,11>>^ Ele lhes respondeu: "Qual de vocês, se tiver uma ovelha e ela cair num buraco no sábado, não irá pegá-la e tirá-la de lá?

[[v40-12-12]]

^<<v40-12-12,12>>^ Quanto mais vale um homem do que uma ovelha! Portanto, é permitido fazer o bem no sábado".

[[v40-12-13]]

^<<v40-12-13,13>>^ Então ele disse ao homem: "Estenda a mão". Ele a estendeu, e ela foi restaurada, e ficou boa como a outra.

[[v40-12-14]]

^<<v40-12-14,14>>^ Então os fariseus saíram e começaram a conspirar sobre como poderiam matar Jesus.

[[v40-12-15]]

^<<v40-12-15,15>>^ Sabendo disso, Jesus retirou-se daquele lugar. Muitos o seguiram, e ele curou a todos os doentes que havia entre eles,

[[v40-12-16]]

^<<v40-12-16,16>>^ advertindo-os que não dissessem quem ele era.

[[v40-12-17]]

^<<v40-12-17,17>>^ Isso aconteceu para se cumprir o que fora dito pelo do profeta Isaías:

[[v40-12-18]]

^<<v40-12-18,18>>^ "Eis o meu servo, a quem escolhi, o meu amado, em quem tenho prazer. Porei sobre ele o meu Espírito, e ele anunciará justiça às nações.

[[v40-12-19]]

^<<v40-12-19,19>>^ Não discutirá nem gritará; ninguém ouvirá sua voz nas ruas.

[[v40-12-20]]

^<<v40-12-20,20>>^ Não quebrará o caniço rachado, não apagará o pavio fumegante, até que leve à vitória a justiça.

[[v40-12-21]]

^<<v40-12-21,21>>^ Em seu nome as nações porão sua esperança".

[[v40-12-22]]

^<<v40-12-22,22>>^ Então levaram-lhe um endemoninhado que era cego e mudo, e Jesus o curou, de modo que ele pôde falar e ver.

[[v40-12-23]]

^<<v40-12-23,23>>^ Todo o povo ficou atônito e disse: "Não será este o Filho de Davi? "

[[v40-12-24]]

^<<v40-12-24,24>>^ Mas quando os fariseus ouviram isso, disseram: "É somente por Belzebu, o príncipe dos demônios, que ele expulsa demônios".

[[v40-12-25]]

^<<v40-12-25,25>>^ Jesus, conhecendo os seus pensamentos, disse-lhes: "Todo reino dividido contra si mesmo será arruinado, e toda cidade ou casa dividida contra si mesma não subsistirá.

[[v40-12-26]]

^<<v40-12-26,26>>^ Se Satanás expulsa Satanás, está dividido contra si mesmo. Como, então, subsistirá seu reino?

[[v40-12-27]]

^<<v40-12-27,27>>^ E se eu expulso demônios por Belzebu, por quem os expulsam os filhos de vocês? Por isso, eles mesmos serão juízes sobre vocês.

[[v40-12-28]]

^<<v40-12-28,28>>^ Mas se é pelo Espírito de Deus que eu expulso demônios, então chegou a vocês o Reino de Deus.

[[v40-12-29]]

^<<v40-12-29,29>>^ "Ou como alguém pode entrar na casa do homem forte e levar dali seus bens, sem antes amarrá-lo? Só então poderá roubar a casa dele.

[[v40-12-30]]

^<<v40-12-30,30>>^ "Aquele que não está comigo, está contra mim; e aquele que comigo não ajunta, espalha.

[[v40-12-31]]

^<<v40-12-31,31>>^ Por esse motivo eu lhes digo: todo pecado e blasfêmia serão perdoados aos homens, mas a blasfêmia contra o Espírito não será perdoada.

[[v40-12-32]]

^<<v40-12-32,32>>^ Todo aquele que disser uma palavra contra o Filho do homem será perdoado, mas quem falar contra o Espírito Santo não será perdoado, nem nesta era nem na era que há de vir.

[[v40-12-33]]

^<<v40-12-33,33>>^ "Considerem: uma árvore boa dá bom fruto; uma árvore ruim, dá fruto ruim, pois uma árvore é conhecida por seu fruto.

[[v40-12-34]]

^<<v40-12-34,34>>^ Raça de víboras, como podem vocês, que são maus, dizer coisas boas? Pois a boca fala do que está cheio o coração.

[[v40-12-35]]

^<<v40-12-35,35>>^ O homem bom, do seu bom tesouro, tira coisas boas, e o homem mau, do seu mau tesouro, tira coisas más.

[[v40-12-36]]

^<<v40-12-36,36>>^ Mas eu lhes digo que, no dia do juízo, os homens haverão de dar conta de toda palavra inútil que tiverem falado.

[[v40-12-37]]

^<<v40-12-37,37>>^ Pois por suas palavras você será absolvido, e por suas palavras será condenado".

[[v40-12-38]]

^<<v40-12-38,38>>^ Então alguns dos fariseus e mestres da lei lhe disseram: "Mestre, queremos ver um sinal miraculoso feito por ti".

[[v40-12-39]]

^<<v40-12-39,39>>^ Ele respondeu: "Uma geração perversa e adúltera pede um sinal miraculoso! Mas nenhum sinal lhe será dado, exceto o sinal do profeta Jonas.

[[v40-12-40]]

^<<v40-12-40,40>>^ Pois assim como Jonas esteve três dias e três noites no ventre de um grande peixe, assim o Filho do homem ficará três dias e três noites no coração da terra.

[[v40-12-41]]

^<<v40-12-41,41>>^ Os homens de Nínive se levantarão no juízo com esta geração e a condenarão; pois eles se arrependeram com a pregação de Jonas, e agora está aqui o que é maior do que Jonas.

[[v40-12-42]]

^<<v40-12-42,42>>^ A rainha do Sul se levantará no juízo com esta geração e a condenará, pois ela veio dos confins da terra para ouvir a sabedoria de Salomão, e agora está aqui o que é maior do que Salomão.

[[v40-12-43]]

^<<v40-12-43,43>>^ "Quando um espírito imundo sai de um homem, passa por lugares áridos procurando descanso e não encontra,

[[v40-12-44]]

^<<v40-12-44,44>>^ e diz: ‘Voltarei para a casa de onde saí’. Chegando, encontra a casa desocupada, varrida e em ordem.

[[v40-12-45]]

^<<v40-12-45,45>>^ Então vai e traz consigo outros sete espíritos piores do que ele, e entrando passam a viver ali. E o estado final daquele homem torna-se pior do que o primeiro. Assim acontecerá a esta geração perversa".

[[v40-12-46]]

^<<v40-12-46,46>>^ Falava ainda Jesus à multidão quando sua mãe e seus irmãos chegaram do lado de fora, querendo falar com ele.

[[v40-12-47]]

^<<v40-12-47,47>>^ Alguém lhe disse: "Tua mãe e teus irmãos estão lá fora e querem falar contigo".

[[v40-12-48]]

^<<v40-12-48,48>>^ "Quem é minha mãe, e quem são meus irmãos? ", perguntou ele.

[[v40-12-49]]

^<<v40-12-49,49>>^ E, estendendo a mão para os discípulos, disse: "Aqui estão minha mãe e meus irmãos!

[[v40-12-50]]

^<<v40-12-50,50>>^ Pois quem faz a vontade de meu Pai que está nos céus, este é meu irmão, minha irmã e minha mãe".

'''

xref:040-mateus/040-mateus-011.adoc#v40-11-0[&#60; Capítulo Anterior] | <<v40-12-0,Topo>> | xref:040-mateus/040-mateus-013.adoc#v40-13-0[Próximo Capítulo &#62;]