include::./index.adoc[]

[[v40-11-0]]
=== Mateus, 11
// nvi ?, NVI - Nova Versão Internacional

[[v40-11-1]]

^<<v40-11-1,1>>^ Depois que terminou de instruir seus doze discípulos, Jesus saiu para ensinar e pregar nas cidades da Galiléia.

[[v40-11-2]]

^<<v40-11-2,2>>^ João, ao ouvir na prisão o que Cristo estava fazendo, enviou seus discípulos para lhe perguntarem:

[[v40-11-3]]

^<<v40-11-3,3>>^ "És tu aquele que haveria de vir ou devemos esperar algum outro? "

[[v40-11-4]]

^<<v40-11-4,4>>^ Jesus respondeu: "Voltem e anunciem a João o que vocês estão ouvindo e vendo:

[[v40-11-5]]

^<<v40-11-5,5>>^ os cegos vêem, os mancos andam, os leprosos são purificados, os surdos ouvem, os mortos são ressuscitados, e as boas novas são pregadas aos pobres;

[[v40-11-6]]

^<<v40-11-6,6>>^ e feliz é aquele que não se escandaliza por minha causa".

[[v40-11-7]]

^<<v40-11-7,7>>^ Enquanto saíam os discípulos de João, Jesus começou a falar à multidão a respeito de João: "O que vocês foram ver no deserto? Um caniço agitado pelo vento?

[[v40-11-8]]

^<<v40-11-8,8>>^ Ou, o que foram ver? Um homem vestido de roupas finas? Ora, os que usam roupas finas estão nos palácios reais.

[[v40-11-9]]

^<<v40-11-9,9>>^ Afinal, o que foram ver? Um profeta? Sim, eu lhes digo, e mais que profeta.

[[v40-11-10]]

^<<v40-11-10,10>>^ Este é aquele a respeito de quem está escrito: ‘Enviarei o meu mensageiro à tua frente; ele preparará o teu caminho diante de ti’.

[[v40-11-11]]

^<<v40-11-11,11>>^ Digo-lhes a verdade: Entre os nascidos de mulher não surgiu ninguém maior do que João Batista; todavia, o menor no Reino dos céus é maior do que ele.

[[v40-11-12]]

^<<v40-11-12,12>>^ Desde os dias de João Batista até agora, o Reino dos céus é tomado à força, e os que usam de força se apoderam dele.

[[v40-11-13]]

^<<v40-11-13,13>>^ Pois todos os Profetas e a Lei profetizaram até João.

[[v40-11-14]]

^<<v40-11-14,14>>^ E se vocês quiserem aceitar, este é o Elias que havia de vir.

[[v40-11-15]]

^<<v40-11-15,15>>^ Aquele que tem ouvidos, ouça!

[[v40-11-16]]

^<<v40-11-16,16>>^ "A que posso comparar esta geração? São como crianças que ficam sentadas nas praças e gritam umas às outras:

[[v40-11-17]]

^<<v40-11-17,17>>^ ‘Nós lhes tocamos flauta, mas vocês não dançaram; cantamos um lamento, mas vocês não se entristeceram’.

[[v40-11-18]]

^<<v40-11-18,18>>^ Pois veio João, que jejua e não bebe vinho, e dizem: ‘Ele tem demônio’.

[[v40-11-19]]

^<<v40-11-19,19>>^ Veio o Filho do homem comendo e bebendo, e dizem: ‘Aí está um comilão e beberrão, amigo de publicanos e "pecadores" ’. Mas a sabedoria é comprovada pelas obras que a acompanham".

[[v40-11-20]]

^<<v40-11-20,20>>^ Então Jesus começou a denunciar as cidades em que havia sido realizada a maioria dos seus milagres, porque não se arrependeram.

[[v40-11-21]]

^<<v40-11-21,21>>^ "Ai de você, Corazim! Ai de você, Betsaida! Porque se os milagres que foram realizados entre vocês tivessem sido realizados em Tiro e Sidom, há muito tempo elas se teriam arrependido, vestindo roupas de saco e cobrindo-se de cinzas.

[[v40-11-22]]

^<<v40-11-22,22>>^ Mas eu lhes afirmo que no dia do juízo haverá menor rigor para Tiro e Sidom do que para vocês.

[[v40-11-23]]

^<<v40-11-23,23>>^ E você, Cafarnaum: será elevada até o céu? Não, você descerá até ao Hades! Se os milagres que em você foram realizados tivessem sido realizados em Sodoma, ela teria permanecido até hoje.

[[v40-11-24]]

^<<v40-11-24,24>>^ Mas eu lhes afirmo que no dia do juízo haverá menor rigor para Sodoma do que para você".

[[v40-11-25]]

^<<v40-11-25,25>>^ Naquela ocasião Jesus disse: "Eu te louvo, Pai, Senhor dos céus e da terra, porque escondeste estas coisas dos sábios e cultos, e as revelaste aos pequeninos.

[[v40-11-26]]

^<<v40-11-26,26>>^ Sim, Pai, pois assim foi do teu agrado.

[[v40-11-27]]

^<<v40-11-27,27>>^ "Todas as coisas me foram entregues por meu Pai. Ninguém conhece o Filho a não ser o Pai, e ninguém conhece o Pai a não ser o Filho e aqueles a quem o Filho o quiser revelar.

[[v40-11-28]]

^<<v40-11-28,28>>^ "Venham a mim, todos os que estão cansados e sobrecarregados, e eu lhes darei descanso.

[[v40-11-29]]

^<<v40-11-29,29>>^ Tomem sobre vocês o meu jugo e aprendam de mim, pois sou manso e humilde de coração, e vocês encontrarão descanso para as suas almas.

[[v40-11-30]]

^<<v40-11-30,30>>^ Pois o meu jugo é suave e o meu fardo é leve".

'''

xref:040-mateus/040-mateus-010.adoc#v40-10-0[&#60; Capítulo Anterior] | <<v40-11-0,Topo>> | xref:040-mateus/040-mateus-012.adoc#v40-12-0[Próximo Capítulo &#62;]