include::./index.adoc[]

[[v40-8-0]]
=== Mateus, 8
// nvi ?, NVI - Nova Versão Internacional

[[v40-8-1]]

^<<v40-8-1,1>>^ Quando ele desceu do monte, grandes multidões o seguiram.

[[v40-8-2]]

^<<v40-8-2,2>>^ Um leproso, aproximando-se, adorou-o de joelhos e disse: "Senhor, se quiseres, podes purificar-me! "

[[v40-8-3]]

^<<v40-8-3,3>>^ Jesus estendeu a mão, tocou nele e disse: "Quero. Seja purificado! " Imediatamente ele foi purificado da lepra.

[[v40-8-4]]

^<<v40-8-4,4>>^ Em seguida Jesus lhe disse: "Olhe, não conte isso a ninguém. Mas vá mostrar-se ao sacerdote e apresente a oferta que Moisés ordenou, para que sirva de testemunho".

[[v40-8-5]]

^<<v40-8-5,5>>^ Entrando Jesus em Cafarnaum, dirigiu-se a ele um centurião, pedindo-lhe ajuda.

[[v40-8-6]]

^<<v40-8-6,6>>^ E disse: "Senhor, meu servo está em casa, paralítico, em terrível sofrimento".

[[v40-8-7]]

^<<v40-8-7,7>>^ Jesus lhe disse: "Eu irei curá-lo".

[[v40-8-8]]

^<<v40-8-8,8>>^ Respondeu o centurião: "Senhor, não mereço receber-te debaixo do meu teto. Mas dize apenas uma palavra, e o meu servo será curado.

[[v40-8-9]]

^<<v40-8-9,9>>^ Pois eu também sou homem sujeito à autoridade, com soldados sob o meu comando. Digo a um: ‘Vá’, e ele vai; e a outro: ‘Venha’, e ele vem. Digo a meu servo: ‘Faça isto’, e ele faz".

[[v40-8-10]]

^<<v40-8-10,10>>^ Ao ouvir isso, Jesus admirou-se e disse aos que o seguiam: "Digo-lhes a verdade: Não encontrei em Israel ninguém com tamanha fé.

[[v40-8-11]]

^<<v40-8-11,11>>^ Eu lhes digo que muitos virão do Oriente e do Ocidente, e se sentarão à mesa com Abraão, Isaque e Jacó no Reino dos céus.

[[v40-8-12]]

^<<v40-8-12,12>>^ Mas os súditos do Reino serão lançados para fora, nas trevas, onde haverá choro e ranger de dentes".

[[v40-8-13]]

^<<v40-8-13,13>>^ Então Jesus disse ao centurião: "Vá! Como você creu, assim lhe acontecerá! " Na mesma hora o seu servo foi curado.

[[v40-8-14]]

^<<v40-8-14,14>>^ Entrando Jesus na casa de Pedro, viu a sogra deste de cama, com febre.

[[v40-8-15]]

^<<v40-8-15,15>>^ Tomando-a pela mão, a febre a deixou, e ela se levantou e começou a servi-lo.

[[v40-8-16]]

^<<v40-8-16,16>>^ Ao anoitecer foram trazidos a ele muitos endemoninhados, e ele expulsou os espíritos com uma palavra e curou todos os doentes.

[[v40-8-17]]

^<<v40-8-17,17>>^ E assim se cumpriu o que fora dito pelo profeta Isaías: "Ele tomou sobre si as nossas enfermidades e sobre si levou as nossas doenças".

[[v40-8-18]]

^<<v40-8-18,18>>^ Quando Jesus viu a multidão ao seu redor, deu ordens para que atravessassem para o outro lado do mar.

[[v40-8-19]]

^<<v40-8-19,19>>^ Então, um mestre da lei aproximou-se e disse: "Mestre, eu te seguirei por onde quer que fores".

[[v40-8-20]]

^<<v40-8-20,20>>^ Jesus respondeu: "As raposas têm suas tocas e as aves do céu têm seus ninhos, mas o Filho do homem não tem onde repousar a cabeça".

[[v40-8-21]]

^<<v40-8-21,21>>^ Outro discípulo lhe disse: "Senhor, deixa-me ir primeiro sepultar meu pai".

[[v40-8-22]]

^<<v40-8-22,22>>^ Mas Jesus lhe disse: "Siga-me, e deixe que os mortos sepultem os seus próprios mortos".

[[v40-8-23]]

^<<v40-8-23,23>>^ Entrando ele no barco, seus discípulos o seguiram.

[[v40-8-24]]

^<<v40-8-24,24>>^ De repente, uma violenta tempestade abateu-se sobre o mar, de forma que as ondas inundavam o barco. Jesus, porém, dormia.

[[v40-8-25]]

^<<v40-8-25,25>>^ Os discípulos foram acordá-lo, clamando: "Senhor, salva-nos! Vamos morrer! "

[[v40-8-26]]

^<<v40-8-26,26>>^ Ele perguntou: "Por que vocês estão com tanto medo, homens de pequena fé? " Então ele se levantou e repreendeu os ventos e o mar, e fez-se completa bonança.

[[v40-8-27]]

^<<v40-8-27,27>>^ Os homens ficaram perplexos e perguntaram: "Quem é este que até os ventos e o mar lhe obedecem? "

[[v40-8-28]]

^<<v40-8-28,28>>^ Quando ele chegou ao outro lado, à região dos gadarenos, foram ao seu encontro dois endemoninhados, que vinham dos sepulcros. Eles eram tão violentos que ninguém podia passar por aquele caminho.

[[v40-8-29]]

^<<v40-8-29,29>>^ Então eles gritaram: "Que queres conosco, Filho de Deus? Vieste aqui para nos atormentar antes do devido tempo? "

[[v40-8-30]]

^<<v40-8-30,30>>^ A certa distância deles estava pastando uma grande manada de porcos.

[[v40-8-31]]

^<<v40-8-31,31>>^ Os demônios imploravam a Jesus: "Se nos expulsas, manda-nos entrar naquela manada de porcos".

[[v40-8-32]]

^<<v40-8-32,32>>^ Ele lhes disse: "Vão! " Eles saíram e entraram nos porcos, e toda a manada atirou-se precipício abaixo, em direção ao mar, e morreu afogada.

[[v40-8-33]]

^<<v40-8-33,33>>^ Os que cuidavam dos porcos fugiram, foram à cidade e contaram tudo, inclusive o que acontecera aos endemoninhados.

[[v40-8-34]]

^<<v40-8-34,34>>^ Toda a cidade saiu ao encontro de Jesus, e quando o viram, suplicaram-lhe que saísse do território deles.

'''

xref:040-mateus/040-mateus-007.adoc#v40-7-0[&#60; Capítulo Anterior] | <<v40-8-0,Topo>> | xref:040-mateus/040-mateus-009.adoc#v40-9-0[Próximo Capítulo &#62;]