include::./index.adoc[]

[[v40-2-0]]
=== Mateus, 2
// nvi ?, NVI - Nova Versão Internacional

[[v40-2-1]]

^<<v40-2-1,1>>^ Depois que Jesus nasceu em Belém da Judéia, nos dias do rei Herodes, magos vindos do Oriente chegaram a Jerusalém

[[v40-2-2]]

^<<v40-2-2,2>>^ e perguntaram: "Onde está o recém-nascido rei dos judeus? Vimos a sua estrela no Oriente e viemos adorá-lo".

[[v40-2-3]]

^<<v40-2-3,3>>^ Quando o rei Herodes ouviu isso, ficou perturbado, e com ele toda a Jerusalém.

[[v40-2-4]]

^<<v40-2-4,4>>^ Tendo reunido todos os chefes dos sacerdotes do povo e os mestres da lei, perguntou-lhes onde deveria nascer o Cristo.

[[v40-2-5]]

^<<v40-2-5,5>>^ E eles responderam: "Em Belém da Judéia; pois assim escreveu o profeta:

[[v40-2-6]]

^<<v40-2-6,6>>^ ‘Mas tu, Belém, da terra de Judá, de forma alguma és a menor entre as principais cidades de Judá; pois de ti virá o líder que, como pastor, conduzirá Israel, o meu povo’ ".

[[v40-2-7]]

^<<v40-2-7,7>>^ Então Herodes chamou os magos secretamente e informou-se com eles a respeito do tempo exato em que a estrela tinha aparecido.

[[v40-2-8]]

^<<v40-2-8,8>>^ Enviou-os a Belém e disse: "Vão informar-se com exatidão sobre o menino. Logo que o encontrarem, avisem-me, para que eu também vá adorá-lo".

[[v40-2-9]]

^<<v40-2-9,9>>^ Depois de ouvirem o rei, eles seguiram o seu caminho, e a estrela que tinham visto no Oriente foi adiante deles, até que finalmente parou sobre o lugar onde estava o menino.

[[v40-2-10]]

^<<v40-2-10,10>>^ Quando tornaram a ver a estrela, encheram-se de júbilo.

[[v40-2-11]]

^<<v40-2-11,11>>^ Ao entrarem na casa, viram o menino com Maria, sua mãe, e, prostrando-se, o adoraram. Então abriram os seus tesouros e lhe deram presentes: ouro, incenso e mirra.

[[v40-2-12]]

^<<v40-2-12,12>>^ E, tendo sido advertidos em sonho para não voltarem a Herodes, retornaram a sua terra por outro caminho.

[[v40-2-13]]

^<<v40-2-13,13>>^ Depois que partiram, um anjo do Senhor apareceu a José em sonho e disse-lhe: "Levante-se, tome o menino e sua mãe, e fuja para o Egito. Fique lá até que eu lhe diga, pois Herodes vai procurar o menino para matá-lo".

[[v40-2-14]]

^<<v40-2-14,14>>^ Então ele se levantou, tomou o menino e sua mãe durante a noite, e partiu para o Egito,

[[v40-2-15]]

^<<v40-2-15,15>>^ onde ficou até a morte de Herodes. E assim se cumpriu o que o Senhor tinha dito pelo profeta: "Do Egito chamei o meu filho".

[[v40-2-16]]

^<<v40-2-16,16>>^ Quando Herodes percebeu que havia sido enganado pelos magos, ficou furioso e ordenou que matassem todos os meninos de dois anos para baixo, em Belém e nas proximidades, de acordo com a informação que havia obtido dos magos.

[[v40-2-17]]

^<<v40-2-17,17>>^ Então se cumpriu o que fora dito pelo profeta Jeremias:

[[v40-2-18]]

^<<v40-2-18,18>>^ "Ouviu-se uma voz em Ramá, choro e grande lamentação; é Raquel que chora por seus filhos e recusa ser consolada, porque já não existem".

[[v40-2-19]]

^<<v40-2-19,19>>^ Depois que Herodes morreu, um anjo do Senhor apareceu em sonho a José, no Egito,

[[v40-2-20]]

^<<v40-2-20,20>>^ e disse: "Levante-se, tome o menino e sua mãe, e vá para a terra de Israel, pois estão mortos os que procuravam tirar a vida do menino".

[[v40-2-21]]

^<<v40-2-21,21>>^ Ele se levantou, tomou o menino e sua mãe, e foi para a terra de Israel.

[[v40-2-22]]

^<<v40-2-22,22>>^ Mas, ao ouvir que Arquelau estava reinando na Judéia em lugar de seu pai Herodes, teve medo de ir para lá. Tendo sido avisado em sonho, retirou-se para a região da Galiléia

[[v40-2-23]]

^<<v40-2-23,23>>^ e foi viver numa cidade chamada Nazaré. Assim cumpriu-se o que fora dito pelos profetas: Ele será chamado Nazareno.

'''

xref:040-mateus/040-mateus-001.adoc#v40-1-0[&#60; Capítulo Anterior] | <<v40-2-0,Topo>> | xref:040-mateus/040-mateus-003.adoc#v40-3-0[Próximo Capítulo &#62;]