include::./index.adoc[]

[[v40-10-0]]
=== Mateus, 10
// nvi ?, NVI - Nova Versão Internacional

[[v40-10-1]]

^<<v40-10-1,1>>^ Chamando seus doze discípulos, deu-lhes autoridade para expulsar espíritos imundos e curar todas as doenças e enfermidades.

[[v40-10-2]]

^<<v40-10-2,2>>^ Estes são os nomes dos doze apóstolos: primeiro, Simão, chamado Pedro, e André, seu irmão; Tiago, filho de Zebedeu, e João, seu irmão;

[[v40-10-3]]

^<<v40-10-3,3>>^ Filipe e Bartolomeu; Tomé e Mateus, o publicano; Tiago, filho de Alfeu, e Tadeu;

[[v40-10-4]]

^<<v40-10-4,4>>^ Simão, o zelote, e Judas Iscariotes, que o traiu.

[[v40-10-5]]

^<<v40-10-5,5>>^ Jesus enviou estes doze com as seguintes instruções: "Não se dirijam aos gentios, nem entrem em cidade alguma dos samaritanos.

[[v40-10-6]]

^<<v40-10-6,6>>^ Antes, dirijam-se às ovelhas perdidas de Israel.

[[v40-10-7]]

^<<v40-10-7,7>>^ Por onde forem, preguem esta mensagem: ‘O Reino dos céus está próximo’.

[[v40-10-8]]

^<<v40-10-8,8>>^ Curem os enfermos, ressuscitem os mortos, purifiquem os leprosos, expulsem os demônios. Vocês receberam de graça; dêem também de graça.

[[v40-10-9]]

^<<v40-10-9,9>>^ Não levem nem ouro, nem prata, nem cobre em seus cintos;

[[v40-10-10]]

^<<v40-10-10,10>>^ não levem nenhum saco de viagem, nem túnica extra, nem sandálias, nem bordão; pois o trabalhador é digno do seu sustento.

[[v40-10-11]]

^<<v40-10-11,11>>^ "Na cidade ou povoado em que entrarem, procurem alguém digno de recebê-los, e fiquem em sua casa até partirem.

[[v40-10-12]]

^<<v40-10-12,12>>^ Ao entrarem na casa, saúdem-na.

[[v40-10-13]]

^<<v40-10-13,13>>^ Se a casa for digna, que a paz de vocês repouse sobre ela; se não for, que a paz retorne para vocês.

[[v40-10-14]]

^<<v40-10-14,14>>^ Se alguém não os receber nem ouvir suas palavras, sacudam a poeira dos pés, quando saírem daquela casa ou cidade.

[[v40-10-15]]

^<<v40-10-15,15>>^ Eu lhes digo a verdade: No dia do juízo haverá menor rigor para Sodoma e Gomorra do que para aquela cidade.

[[v40-10-16]]

^<<v40-10-16,16>>^ Eu os estou enviando como ovelhas entre lobos. Portanto, sejam prudentes como as serpentes e simples como as pombas.

[[v40-10-17]]

^<<v40-10-17,17>>^ "Tenham cuidado, pois os homens os entregarão aos tribunais e os açoitarão nas sinagogas deles.

[[v40-10-18]]

^<<v40-10-18,18>>^ Por minha causa vocês serão levados à presença de governadores e reis como testemunhas a eles e aos gentios.

[[v40-10-19]]

^<<v40-10-19,19>>^ Mas quando os prenderem, não se preocupem quanto ao que dizer, ou como dizer. Naquela hora lhes será dado o que dizer,

[[v40-10-20]]

^<<v40-10-20,20>>^ pois não serão vocês que estarão falando, mas o Espírito do Pai de vocês falará por intermédio de vocês.

[[v40-10-21]]

^<<v40-10-21,21>>^ "O irmão entregará à morte o seu irmão, e o pai o seu filho; filhos se rebelarão contra seus pais e os matarão.

[[v40-10-22]]

^<<v40-10-22,22>>^ Todos odiarão vocês por minha causa, mas aquele que perseverar até o fim será salvo.

[[v40-10-23]]

^<<v40-10-23,23>>^ Quando forem perseguidos num lugar, fujam para outro. Eu lhes garanto que vocês não terão percorrido todas as cidades de Israel antes que venha o Filho do homem.

[[v40-10-24]]

^<<v40-10-24,24>>^ "O discípulo não está acima do seu mestre, nem o servo acima do seu senhor.

[[v40-10-25]]

^<<v40-10-25,25>>^ Basta ao discípulo ser como o seu mestre, e ao servo, como o seu senhor. Se o dono da casa foi chamado Belzebu, quanto mais os membros da sua família!

[[v40-10-26]]

^<<v40-10-26,26>>^ "Portanto, não tenham medo deles. Não há nada escondido que não venha a ser revelado, nem oculto que não venha a se tornar conhecido.

[[v40-10-27]]

^<<v40-10-27,27>>^ O que eu lhes digo na escuridão, falem à luz do dia; o que é sussurrado em seus ouvidos, proclamem dos telhados.

[[v40-10-28]]

^<<v40-10-28,28>>^ Não tenham medo dos que matam o corpo, mas não podem matar a alma. Antes, tenham medo daquele que pode destruir tanto a alma como o corpo no inferno.

[[v40-10-29]]

^<<v40-10-29,29>>^ Não se vendem dois pardais por uma moedinha? Contudo, nenhum deles cai no chão sem o consentimento do Pai de vocês.

[[v40-10-30]]

^<<v40-10-30,30>>^ Até os cabelos da cabeça de vocês estão todos contados.

[[v40-10-31]]

^<<v40-10-31,31>>^ Portanto, não tenham medo; vocês valem mais do que muitos pardais!

[[v40-10-32]]

^<<v40-10-32,32>>^ "Quem, pois, me confessar diante dos homens, eu também o confessarei diante do meu Pai que está nos céus.

[[v40-10-33]]

^<<v40-10-33,33>>^ Mas aquele que me negar diante dos homens, eu também o negarei diante do meu Pai que está nos céus.

[[v40-10-34]]

^<<v40-10-34,34>>^ "Não pensem que vim trazer paz à terra; não vim trazer paz, mas espada.

[[v40-10-35]]

^<<v40-10-35,35>>^ Pois vim para fazer que ‘o homem fique contra seu pai, a filha contra sua mãe, a nora contra sua sogra;

[[v40-10-36]]

^<<v40-10-36,36>>^ os inimigos do homem serão os da sua própria família’.

[[v40-10-37]]

^<<v40-10-37,37>>^ "Quem ama seu pai ou sua mãe mais do que a mim não é digno de mim; quem ama seu filho ou sua filha mais do que a mim não é digno de mim;

[[v40-10-38]]

^<<v40-10-38,38>>^ e quem não toma a sua cruz e não me segue, não é digno de mim.

[[v40-10-39]]

^<<v40-10-39,39>>^ Quem acha a sua vida a perderá, e quem perde a sua vida por minha causa a encontrará.

[[v40-10-40]]

^<<v40-10-40,40>>^ "Quem recebe vocês, recebe a mim; e quem me recebe, recebe aquele que me enviou.

[[v40-10-41]]

^<<v40-10-41,41>>^ Quem recebe um profeta, porque ele é profeta, receberá a recompensa de profeta, e quem recebe um justo, porque ele é justo, receberá a recompensa de justo.

[[v40-10-42]]

^<<v40-10-42,42>>^ E se alguém der mesmo que seja apenas um copo de água fria a um destes pequeninos, porque ele é meu discípulo, eu lhes asseguro que não perderá a sua recompensa".

'''

xref:040-mateus/040-mateus-009.adoc#v40-9-0[&#60; Capítulo Anterior] | <<v40-10-0,Topo>> | xref:040-mateus/040-mateus-011.adoc#v40-11-0[Próximo Capítulo &#62;]