include::./index.adoc[]

[[v40-21-0]]
=== Mateus, 21
// nvi ?, NVI - Nova Versão Internacional

[[v40-21-1]]

^<<v40-21-1,1>>^ Quando se aproximaram de Jerusalém e chegaram a Betfagé, ao monte das Oliveiras, Jesus enviou dois discípulos,

[[v40-21-2]]

^<<v40-21-2,2>>^ dizendo-lhes: "Vão ao povoado que está adiante de vocês; logo encontrarão uma jumenta amarrada, com um jumentinho ao lado. Desamarrem-nos e tragam-nos para mim.

[[v40-21-3]]

^<<v40-21-3,3>>^ Se alguém lhes perguntar algo, digam-lhe que o Senhor precisa deles e logo os enviará de volta".

[[v40-21-4]]

^<<v40-21-4,4>>^ Isso aconteceu para que se cumprisse o que fora dito pelo profeta:

[[v40-21-5]]

^<<v40-21-5,5>>^ "Digam à cidade de Sião: ‘Eis que o seu rei vem a você, humilde e montado num jumento, num jumentinho, cria de jumenta’ ".

[[v40-21-6]]

^<<v40-21-6,6>>^ Os discípulos foram e fizeram o que Jesus tinha ordenado.

[[v40-21-7]]

^<<v40-21-7,7>>^ Trouxeram a jumenta e o jumentinho, colocaram sobre eles os seus mantos, e sobre estes Jesus montou.

[[v40-21-8]]

^<<v40-21-8,8>>^ Uma grande multidão estendeu seus mantos pelo caminho, outros cortavam ramos de árvores e os espalhavam pelo caminho.

[[v40-21-9]]

^<<v40-21-9,9>>^ A multidão que ia adiante dele e os que o seguiam gritavam: "Hosana ao Filho de Davi! " "Bendito é o que vem em nome do Senhor! " "Hosana nas alturas! "

[[v40-21-10]]

^<<v40-21-10,10>>^ Quando Jesus entrou em Jerusalém, toda a cidade ficou agitada e perguntava: "Quem é este? "

[[v40-21-11]]

^<<v40-21-11,11>>^ A multidão respondia: "Este é Jesus, o profeta de Nazaré da Galiléia".

[[v40-21-12]]

^<<v40-21-12,12>>^ Jesus entrou no templo e expulsou todos os que ali estavam comprando e vendendo. Derrubou as mesas dos cambistas e as cadeiras dos que vendiam pombas,

[[v40-21-13]]

^<<v40-21-13,13>>^ e lhes disse: "Está escrito: ‘A minha casa será chamada casa de oração’; mas vocês estão fazendo dela um ‘covil de ladrões’".

[[v40-21-14]]

^<<v40-21-14,14>>^ Os cegos e os mancos aproximaram-se dele no templo, e ele os curou.

[[v40-21-15]]

^<<v40-21-15,15>>^ Mas quando os chefes dos sacerdotes e os mestres da lei viram as coisas maravilhosas que Jesus fazia e as crianças gritando no templo: "Hosana ao Filho de Davi", ficaram indignados,

[[v40-21-16]]

^<<v40-21-16,16>>^ e lhe perguntaram: "Não estás ouvindo o que estas crianças estão dizendo? " Respondeu Jesus: "Sim, vocês nunca leram: ‘dos lábios das crianças e dos recém-nascidos suscitaste louvor’? "

[[v40-21-17]]

^<<v40-21-17,17>>^ E, deixando-os, saiu da cidade para Betânia, onde passou a noite.

[[v40-21-18]]

^<<v40-21-18,18>>^ De manhã cedo, quando voltava para a cidade, Jesus teve fome.

[[v40-21-19]]

^<<v40-21-19,19>>^ Vendo uma figueira à beira do caminho, aproximou-se dela, mas nada encontrou, a não ser folhas. Então lhe disse: "Nunca mais dê frutos! " Imediatamente a árvore secou.

[[v40-21-20]]

^<<v40-21-20,20>>^ Ao verem isso, os discípulos ficaram espantados e perguntaram: "Como a figueira secou tão depressa? "

[[v40-21-21]]

^<<v40-21-21,21>>^ Jesus respondeu: "Eu lhes asseguro que, se vocês tiverem fé e não duvidarem, poderão fazer não somente o que foi feito à figueira, mas também dizer a este monte: ‘Levante-se e atire-se no mar’, e assim será feito.

[[v40-21-22]]

^<<v40-21-22,22>>^ E tudo o que pedirem em oração, se crerem, vocês receberão".

[[v40-21-23]]

^<<v40-21-23,23>>^ Jesus entrou no templo e, enquanto ensinava, aproximaram-se dele os chefes dos sacerdotes e os líderes religiosos do povo e perguntaram: "Com que autoridade estás fazendo estas coisas? E quem te deu tal autoridade? "

[[v40-21-24]]

^<<v40-21-24,24>>^ Respondeu Jesus: "Eu também lhes farei uma pergunta. Se vocês me responderem, eu lhes direi com que autoridade estou fazendo estas coisas.

[[v40-21-25]]

^<<v40-21-25,25>>^ De onde era o batismo de João? Do céu ou dos homens? " Eles discutiam entre si, dizendo: "Se dissermos: ‘do céu’, ele perguntará: ‘Então por que vocês não creram nele? ’

[[v40-21-26]]

^<<v40-21-26,26>>^ Mas se dissermos: ‘dos homens’ — temos medo do povo, pois todos consideram João um profeta".

[[v40-21-27]]

^<<v40-21-27,27>>^ Eles responderam a Jesus: "Não sabemos". E ele lhes disse: "Tampouco lhes direi com que autoridade estou fazendo estas coisas".

[[v40-21-28]]

^<<v40-21-28,28>>^ "O que acham? Havia um homem que tinha dois filhos. Chegando ao primeiro, disse: ‘Filho, vá trabalhar hoje na vinha’.

[[v40-21-29]]

^<<v40-21-29,29>>^ "E este respondeu: ‘Não quero! ’ Mas depois mudou de idéia e foi.

[[v40-21-30]]

^<<v40-21-30,30>>^ "O pai chegou ao outro filho e disse a mesma coisa. Ele respondeu: ‘Sim, senhor! ’ Mas não foi.

[[v40-21-31]]

^<<v40-21-31,31>>^ "Qual dos dois fez a vontade do pai? " "O primeiro", responderam eles. Jesus lhes disse: "Digo-lhes a verdade: Os publicanos e as prostitutas estão entrando antes de vocês no Reino de Deus.

[[v40-21-32]]

^<<v40-21-32,32>>^ Porque João veio para lhes mostrar o caminho da justiça, e vocês não creram nele, mas os publicanos e as prostitutas creram. E, mesmo depois de verem isso, vocês não se arrependeram nem creram nele".

[[v40-21-33]]

^<<v40-21-33,33>>^ "Ouçam outra parábola: Havia um proprietário de terras que plantou uma vinha. Colocou uma cerca ao redor dela, cavou um tanque para prensar as uvas e construiu uma torre. Depois arrendou a vinha a alguns lavradores e foi fazer uma viagem.

[[v40-21-34]]

^<<v40-21-34,34>>^ Aproximando-se a época da colheita, enviou seus servos aos lavradores, para receber os frutos que lhe pertenciam.

[[v40-21-35]]

^<<v40-21-35,35>>^ "Os lavradores agarraram seus servos; a um espancaram, a outro mataram e apedrejaram o terceiro.

[[v40-21-36]]

^<<v40-21-36,36>>^ Então enviou-lhes outros servos em maior número, e os lavradores os trataram da mesma forma.

[[v40-21-37]]

^<<v40-21-37,37>>^ Por último, enviou-lhes seu filho, dizendo: ‘A meu filho respeitarão’.

[[v40-21-38]]

^<<v40-21-38,38>>^ "Mas quando os lavradores viram o filho, disseram uns aos outros: ‘Este é o herdeiro. Venham, vamos matá-lo e tomar a sua herança’.

[[v40-21-39]]

^<<v40-21-39,39>>^ Assim eles o agarraram, lançaram-no para fora da vinha e o mataram.

[[v40-21-40]]

^<<v40-21-40,40>>^ "Portanto, quando vier o dono da vinha, o que fará àqueles lavradores? "

[[v40-21-41]]

^<<v40-21-41,41>>^ Responderam eles: "Matará de modo horrível esses perversos e arrendará a vinha a outros lavradores, que lhe dêem a sua parte no tempo da colheita".

[[v40-21-42]]

^<<v40-21-42,42>>^ Jesus lhes disse: "Vocês nunca leram nas Escrituras? ‘A pedra que os construtores rejeitaram tornou-se a pedra angular; isso vem do Senhor, e é algo maravilhoso para nós’.

[[v40-21-43]]

^<<v40-21-43,43>>^ "Portanto eu lhes digo que o Reino de Deus será tirado de vocês e será dado a um povo que dê os frutos do Reino.

[[v40-21-44]]

^<<v40-21-44,44>>^ Aquele que cair sobre esta pedra será despedaçado, e aquele sobre quem ela cair será reduzido a pó".

[[v40-21-45]]

^<<v40-21-45,45>>^ Quando os chefes dos sacerdotes e os fariseus ouviram as parábolas de Jesus, compreenderam que ele falava a respeito deles.

[[v40-21-46]]

^<<v40-21-46,46>>^ E procuravam um meio de prendê-lo; mas tinham medo das multidões, pois elas o consideravam profeta.

'''

xref:040-mateus/040-mateus-020.adoc#v40-20-0[&#60; Capítulo Anterior] | <<v40-21-0,Topo>> | xref:040-mateus/040-mateus-022.adoc#v40-22-0[Próximo Capítulo &#62;]