include::./index.adoc[]

[[v40-15-0]]
=== Mateus, 15
// nvi ?, NVI - Nova Versão Internacional

[[v40-15-1]]

^<<v40-15-1,1>>^ Então alguns fariseus e mestres da lei, vindos de Jerusalém, foram a Jesus e perguntaram:

[[v40-15-2]]

^<<v40-15-2,2>>^ "Por que os seus discípulos transgridem a tradição dos líderes religiosos? Pois não lavam as mãos antes de comer! "

[[v40-15-3]]

^<<v40-15-3,3>>^ Respondeu Jesus: "E por que vocês transgridem o mandamento de Deus por causa da tradição de vocês?

[[v40-15-4]]

^<<v40-15-4,4>>^ Pois Deus disse: ‘Honra teu pai e tua mãe’ e ‘quem amaldiçoar seu pai ou sua mãe terá que ser executado’.

[[v40-15-5]]

^<<v40-15-5,5>>^ Mas vocês afirmam que se alguém disser a seu pai ou a sua mãe: ‘Qualquer ajuda que vocês poderiam receber de mim é uma oferta dedicada a Deus’,

[[v40-15-6]]

^<<v40-15-6,6>>^ ele não é obrigado a ‘honrar seu pai’ dessa forma. Assim vocês anulam a palavra de Deus por causa da tradição de vocês.

[[v40-15-7]]

^<<v40-15-7,7>>^ Hipócritas! Bem profetizou Isaías acerca de vocês, dizendo:

[[v40-15-8]]

^<<v40-15-8,8>>^ ‘Este povo me honra com os lábios, mas o seu coração está longe de mim.

[[v40-15-9]]

^<<v40-15-9,9>>^ Em vão me adoram; seus ensinamentos não passam de regras ensinadas por homens’".

[[v40-15-10]]

^<<v40-15-10,10>>^ Jesus chamou para junto de si a multidão e disse: "Ouçam e entendam.

[[v40-15-11]]

^<<v40-15-11,11>>^ O que entra pela boca não torna o homem ‘impuro’; mas o que sai de sua boca, isto o torna ‘impuro’ ".

[[v40-15-12]]

^<<v40-15-12,12>>^ Então os discípulos se aproximaram dele e perguntaram: "Sabes que os fariseus ficaram ofendidos quando ouviram isso? "

[[v40-15-13]]

^<<v40-15-13,13>>^ Ele respondeu: "Toda planta que meu Pai celestial não plantou será arrancada pelas raízes.

[[v40-15-14]]

^<<v40-15-14,14>>^ Deixem-nos; eles são guias cegos. Se um cego conduzir outro cego, ambos cairão num buraco".

[[v40-15-15]]

^<<v40-15-15,15>>^ Então Pedro pediu-lhe: "Explica-nos a parábola".

[[v40-15-16]]

^<<v40-15-16,16>>^ "Será que vocês ainda não conseguem entender? ", perguntou Jesus:

[[v40-15-17]]

^<<v40-15-17,17>>^ "Não percebem que o que entra pela boca vai para o estômago e mais tarde é expelido?

[[v40-15-18]]

^<<v40-15-18,18>>^ Mas as coisas que saem da boca vêm do coração, e são essas que tornam o homem ‘impuro’.

[[v40-15-19]]

^<<v40-15-19,19>>^ Pois do coração saem os maus pensamentos, os homicídios, os adultérios, as imoralidades sexuais, os roubos, os falsos testemunhos e as calúnias.

[[v40-15-20]]

^<<v40-15-20,20>>^ Essas coisas tornam o homem ‘impuro’; mas o comer sem lavar as mãos não o torna ‘impuro’ ".

[[v40-15-21]]

^<<v40-15-21,21>>^ Saindo daquele lugar, Jesus retirou-se para a região de Tiro e de Sidom.

[[v40-15-22]]

^<<v40-15-22,22>>^ Uma mulher cananéia, natural dali, veio a ele, gritando: "Senhor, Filho de Davi, tem misericórdia de mim! Minha filha está endemoninhada e está sofrendo muito".

[[v40-15-23]]

^<<v40-15-23,23>>^ Mas Jesus não lhe respondeu palavra. Então seus discípulos se aproximaram dele e pediram: "Manda-a embora, pois vem gritando atrás de nós".

[[v40-15-24]]

^<<v40-15-24,24>>^ Ele respondeu: "Eu fui enviado apenas às ovelhas perdidas de Israel".

[[v40-15-25]]

^<<v40-15-25,25>>^ A mulher veio, adorou-o de joelhos e disse: "Senhor, ajuda-me! "

[[v40-15-26]]

^<<v40-15-26,26>>^ Ele respondeu: "Não é certo tirar o pão dos filhos e lançá-lo aos cachorrinhos".

[[v40-15-27]]

^<<v40-15-27,27>>^ Disse ela, porém: "Sim, Senhor, mas até os cachorrinhos comem das migalhas que caem da mesa dos seus donos".

[[v40-15-28]]

^<<v40-15-28,28>>^ Jesus respondeu: "Mulher, grande é a sua fé! Seja conforme você deseja". E naquele mesmo instante a sua filha foi curada.

[[v40-15-29]]

^<<v40-15-29,29>>^ Jesus saiu dali e foi para a beira do mar da Galiléia. Depois subiu a um monte e se assentou.

[[v40-15-30]]

^<<v40-15-30,30>>^ Uma grande multidão dirigiu-se a ele, levando-lhe os mancos, os aleijados, os cegos, os mudos e muitos outros, e os colocaram aos seus pés; e ele os curou.

[[v40-15-31]]

^<<v40-15-31,31>>^ O povo ficou admirado quando viu os mudos falando, os aleijados curados, os mancos andando e os cegos vendo. E louvaram o Deus de Israel.

[[v40-15-32]]

^<<v40-15-32,32>>^ Jesus chamou os seus discípulos e disse: "Tenho compaixão desta multidão; já faz três dias que eles estão comigo e nada têm para comer. Não quero mandá-los embora com fome, porque podem desfalecer no caminho".

[[v40-15-33]]

^<<v40-15-33,33>>^ Os seus discípulos responderam: "Onde poderíamos encontrar, neste lugar deserto, pão suficiente para alimentar tanta gente? "

[[v40-15-34]]

^<<v40-15-34,34>>^ "Quantos pães vocês têm? ", perguntou Jesus. "Sete", responderam eles, "e alguns peixinhos".

[[v40-15-35]]

^<<v40-15-35,35>>^ Ele ordenou à multidão que se assentasse no chão.

[[v40-15-36]]

^<<v40-15-36,36>>^ Depois de tomar os sete pães e os peixes e dar graças, partiu-os e os entregou aos discípulos, e os discípulos à multidão.

[[v40-15-37]]

^<<v40-15-37,37>>^ Todos comeram até se fartar. E ajuntaram sete cestos cheios de pedaços que sobraram.

[[v40-15-38]]

^<<v40-15-38,38>>^ Os que comeram foram quatro mil homens, sem contar mulheres e crianças.

[[v40-15-39]]

^<<v40-15-39,39>>^ E, havendo despedido a multidão, Jesus entrou no barco e foi para a região de Magadã.

'''

xref:040-mateus/040-mateus-014.adoc#v40-14-0[&#60; Capítulo Anterior] | <<v40-15-0,Topo>> | xref:040-mateus/040-mateus-016.adoc#v40-16-0[Próximo Capítulo &#62;]