include::./index.adoc[]

[[v40-28-0]]
=== Mateus, 28
// nvi ?, NVI - Nova Versão Internacional

[[v40-28-1]]

^<<v40-28-1,1>>^ Depois do sábado, tendo começado o primeiro dia da semana, Maria Madalena e a outra Maria foram ver o sepulcro.

[[v40-28-2]]

^<<v40-28-2,2>>^ E eis que sobreveio um grande terremoto, pois um anjo do Senhor desceu do céu e, chegando ao sepulcro, rolou a pedra da entrada e assentou-se sobre ela.

[[v40-28-3]]

^<<v40-28-3,3>>^ Sua aparência era como um relâmpago, e suas vestes eram brancas como a neve.

[[v40-28-4]]

^<<v40-28-4,4>>^ Os guardas tremeram de medo e ficaram como mortos.

[[v40-28-5]]

^<<v40-28-5,5>>^ O anjo disse às mulheres: "Não tenham medo! Sei que vocês estão procurando Jesus, que foi crucificado.

[[v40-28-6]]

^<<v40-28-6,6>>^ Ele não está aqui; ressuscitou, como tinha dito. Venham ver o lugar onde ele jazia.

[[v40-28-7]]

^<<v40-28-7,7>>^ Vão depressa e digam aos discípulos dele: ‘Ele ressuscitou dentre os mortos e está indo adiante de vocês para a Galiléia. Lá vocês o verão’. Notem que eu já os avisei".

[[v40-28-8]]

^<<v40-28-8,8>>^ As mulheres saíram depressa do sepulcro, amedrontadas e cheias de alegria, e foram correndo anunciá-lo aos discípulos de Jesus.

[[v40-28-9]]

^<<v40-28-9,9>>^ De repente, Jesus as encontrou e disse: "Salve! " Elas se aproximaram dele, abraçaram-lhe os pés e o adoraram.

[[v40-28-10]]

^<<v40-28-10,10>>^ Então Jesus lhes disse: "Não tenham medo. Vão dizer a meus irmãos que se dirijam para a Galiléia; lá eles me verão".

[[v40-28-11]]

^<<v40-28-11,11>>^ Enquanto as mulheres estavam a caminho, alguns dos guardas dirigiram-se à cidade e contaram aos chefes dos sacerdotes tudo o que havia acontecido.

[[v40-28-12]]

^<<v40-28-12,12>>^ Quando os chefes dos sacerdotes se reuniram com os líderes religiosos, elaboraram um plano. Deram aos soldados grande soma de dinheiro,

[[v40-28-13]]

^<<v40-28-13,13>>^ dizendo-lhes: "Vocês devem declarar o seguinte: ‘Os discípulos dele vieram durante a noite e furtaram o corpo, enquanto estávamos dormindo’.

[[v40-28-14]]

^<<v40-28-14,14>>^ Se isso chegar aos ouvidos do governador, nós lhe daremos explicações e livraremos vocês de qualquer problema".

[[v40-28-15]]

^<<v40-28-15,15>>^ Assim, os soldados receberam o dinheiro e fizeram como tinham sido instruídos. E esta versão se divulgou entre os judeus até o dia de hoje.

[[v40-28-16]]

^<<v40-28-16,16>>^ Os onze discípulos foram para a Galiléia, para o monte que Jesus lhes indicara.

[[v40-28-17]]

^<<v40-28-17,17>>^ Quando o viram o adoraram; mas alguns duvidaram.

[[v40-28-18]]

^<<v40-28-18,18>>^ Então, Jesus aproximou-se deles e disse: "Foi-me dada toda a autoridade no céu e na terra.

[[v40-28-19]]

^<<v40-28-19,19>>^ Portanto, vão e façam discípulos de todas as nações, batizando-os em nome do Pai e do Filho e do Espírito Santo,

[[v40-28-20]]

^<<v40-28-20,20>>^ ensinando-os a obedecer a tudo o que eu lhes ordenei. E eu estarei sempre com vocês, até o fim dos tempos".

'''

xref:040-mateus/040-mateus-027.adoc#v40-27-0[&#60; Capítulo Anterior] | <<v40-28-0,Topo>> | xref:041-marcos/041-marcos-001.adoc#v41-1-0[Próximo Capítulo &#62;]