include::./index.adoc[]

[[v40-17-0]]
=== Mateus, 17
// nvi ?, NVI - Nova Versão Internacional

[[v40-17-1]]

^<<v40-17-1,1>>^ Seis dias depois, Jesus tomou consigo Pedro, Tiago e João, irmão de Tiago, e os levou, em particular, a um alto monte.

[[v40-17-2]]

^<<v40-17-2,2>>^ Ali ele foi transfigurado diante deles. Sua face brilhou como o sol, e suas roupas se tornaram brancas como a luz.

[[v40-17-3]]

^<<v40-17-3,3>>^ Naquele mesmo momento apareceram diante deles Moisés e Elias, conversando com Jesus.

[[v40-17-4]]

^<<v40-17-4,4>>^ Então Pedro disse a Jesus: "Senhor, é bom estarmos aqui. Se quiseres, farei três tendas: uma para ti, uma para Moisés e outra para Elias".

[[v40-17-5]]

^<<v40-17-5,5>>^ Enquanto ele ainda estava falando, uma nuvem resplandecente os envolveu, e dela saiu uma voz, que dizia: "Este é o meu Filho amado em quem me agrado. Ouçam-no! "

[[v40-17-6]]

^<<v40-17-6,6>>^ Ouvindo isso, os discípulos prostraram-se com o rosto em terra e ficaram aterrorizados.

[[v40-17-7]]

^<<v40-17-7,7>>^ Mas Jesus se aproximou, tocou neles e disse: "Levantem-se! Não tenham medo! "

[[v40-17-8]]

^<<v40-17-8,8>>^ E erguendo eles os olhos, não viram mais ninguém a não ser Jesus.

[[v40-17-9]]

^<<v40-17-9,9>>^ Enquanto desciam do monte, Jesus lhes ordenou: "Não contem a ninguém o que vocês viram, até que o Filho do homem tenha sido ressuscitado dos mortos".

[[v40-17-10]]

^<<v40-17-10,10>>^ Os discípulos lhe perguntaram: "Então, por que os mestres da lei dizem que é necessário que Elias venha primeiro? "

[[v40-17-11]]

^<<v40-17-11,11>>^ Jesus respondeu: "De fato, Elias vem e restaurará todas as coisas.

[[v40-17-12]]

^<<v40-17-12,12>>^ Mas eu lhes digo: Elias já veio, e eles não o reconheceram, mas fizeram com ele tudo o que quiseram. Da mesma forma o Filho do homem será maltratado por eles".

[[v40-17-13]]

^<<v40-17-13,13>>^ Então os discípulos entenderam que era de João Batista que ele tinha falado.

[[v40-17-14]]

^<<v40-17-14,14>>^ Quando chegaram onde estava a multidão, um homem aproximou-se de Jesus, ajoelhou-se diante dele e disse:

[[v40-17-15]]

^<<v40-17-15,15>>^ "Senhor, tem misericórdia do meu filho. Ele tem ataques e está sofrendo muito. Muitas vezes cai no fogo ou na água.

[[v40-17-16]]

^<<v40-17-16,16>>^ Eu o trouxe aos teus discípulos, mas eles não puderam curá-lo".

[[v40-17-17]]

^<<v40-17-17,17>>^ Respondeu Jesus: "Ó geração incrédula e perversa, até quando estarei com vocês? Até quando terei que suportá-los? Tragam-me o menino".

[[v40-17-18]]

^<<v40-17-18,18>>^ Jesus repreendeu o demônio; este saiu do menino e, desde aquele momento, ele ficou curado.

[[v40-17-19]]

^<<v40-17-19,19>>^ Então os discípulos aproximaram-se de Jesus em particular e perguntaram: "Por que não conseguimos expulsá-lo? "

[[v40-17-20]]

^<<v40-17-20,20>>^ Ele respondeu: "Por que a fé que vocês têm é pequena. Eu lhes asseguro que se vocês tiverem fé do tamanho de um grão de mostarda, poderão dizer a este monte: ‘Vá daqui para lá’, e ele irá. Nada lhes será impossível.

[[v40-17-21]]

^<<v40-17-21,21>>^ Mas esta espécie só sai pela oração e pelo jejum".

[[v40-17-22]]

^<<v40-17-22,22>>^ Reunindo-se eles na Galiléia, Jesus lhes disse: "O Filho do homem será entregue nas mãos dos homens.

[[v40-17-23]]

^<<v40-17-23,23>>^ Eles o matarão, e no terceiro dia ele ressuscitará". E os discípulos ficaram cheios de tristeza.

[[v40-17-24]]

^<<v40-17-24,24>>^ Quando Jesus e seus discípulos chegaram a Cafarnaum, os coletores do imposto de duas dracmas vieram a Pedro e perguntaram: "O mestre de vocês não paga o imposto do templo? "

[[v40-17-25]]

^<<v40-17-25,25>>^ "Sim, paga", respondeu ele. Quando Pedro entrou na casa, Jesus foi o primeiro a falar, perguntando-lhe: "O que você acha, Simão? De quem os reis da terra cobram tributos e impostos: de seus próprios filhos ou dos outros? "

[[v40-17-26]]

^<<v40-17-26,26>>^ "Dos outros", respondeu Pedro. Disse-lhe Jesus: "Então os filhos estão isentos.

[[v40-17-27]]

^<<v40-17-27,27>>^ Mas, para não escandalizá-los, vá ao mar e jogue o anzol. Tire o primeiro peixe que você pegar, abra-lhe a boca, e você encontrará uma moeda de quatro dracmas. Pegue-a e entregue-a a eles, para pagar o meu imposto e o seu".

'''

xref:040-mateus/040-mateus-016.adoc#v40-16-0[&#60; Capítulo Anterior] | <<v40-17-0,Topo>> | xref:040-mateus/040-mateus-018.adoc#v40-18-0[Próximo Capítulo &#62;]