include::./index.adoc[]

[[v40-6-0]]
=== Mateus, 6
// nvi ?, NVI - Nova Versão Internacional

[[v40-6-1]]

^<<v40-6-1,1>>^ "Tenham o cuidado de não praticar suas ‘obras de justiça’ diante dos outros para serem vistos por eles. Se fizerem isso, vocês não terão nenhuma recompensa do Pai celestial.

[[v40-6-2]]

^<<v40-6-2,2>>^ "Portanto, quando você der esmola, não anuncie isso com trombetas, como fazem os hipócritas nas sinagogas e nas ruas, a fim de serem honrados pelos outros. Eu lhes garanto que eles já receberam sua plena recompensa.

[[v40-6-3]]

^<<v40-6-3,3>>^ Mas quando você der esmola, que a sua mão esquerda não saiba o que está fazendo a direita,

[[v40-6-4]]

^<<v40-6-4,4>>^ de forma que você preste a sua ajuda em segredo. E seu Pai, que vê o que é feito em segredo, o recompensará".

[[v40-6-5]]

^<<v40-6-5,5>>^ "E quando vocês orarem, não sejam como os hipócritas. Eles gostam de ficar orando em pé nas sinagogas e nas esquinas, a fim de serem vistos pelos outros. Eu lhes asseguro que eles já receberam sua plena recompensa.

[[v40-6-6]]

^<<v40-6-6,6>>^ Mas quando você orar, vá para seu quarto, feche a porta e ore a seu Pai, que está no secreto. Então seu Pai, que vê no secreto, o recompensará.

[[v40-6-7]]

^<<v40-6-7,7>>^ E quando orarem, não fiquem sempre repetindo a mesma coisa, como fazem os pagãos. Eles pensam que por muito falarem serão ouvidos.

[[v40-6-8]]

^<<v40-6-8,8>>^ Não sejam iguais a eles, porque o seu Pai sabe do que vocês precisam, antes mesmo de o pedirem.

[[v40-6-9]]

^<<v40-6-9,9>>^ Vocês, orem assim: ‘Pai nosso, que estás nos céus! Santificado seja o teu nome.

[[v40-6-10]]

^<<v40-6-10,10>>^ Venha o teu Reino; seja feita a tua vontade, assim na terra como no céu.

[[v40-6-11]]

^<<v40-6-11,11>>^ Dá-nos hoje o nosso pão de cada dia.

[[v40-6-12]]

^<<v40-6-12,12>>^ Perdoa as nossas dívidas, assim como perdoamos aos nossos devedores.

[[v40-6-13]]

^<<v40-6-13,13>>^ E não nos deixes cair em tentação, mas livra-nos do mal, porque teu é o Reino, o poder e a glória para sempre. Amém’.

[[v40-6-14]]

^<<v40-6-14,14>>^ Pois se perdoarem as ofensas uns dos outros, o Pai celestial também lhes perdoará.

[[v40-6-15]]

^<<v40-6-15,15>>^ Mas se não perdoarem uns aos outros, o Pai celestial não lhes perdoará as ofensas".

[[v40-6-16]]

^<<v40-6-16,16>>^ "Quando jejuarem, não mostrem uma aparência triste como os hipócritas, pois eles mudam a aparência do rosto a fim de que os homens vejam que eles estão jejuando. Eu lhes digo verdadeiramente que eles já receberam sua plena recompensa.

[[v40-6-17]]

^<<v40-6-17,17>>^ Ao jejuar, ponha óleo sobre a cabeça e lave o rosto,

[[v40-6-18]]

^<<v40-6-18,18>>^ para que não pareça aos outros que você está jejuando, mas apenas a seu Pai, que vê no secreto. E seu Pai, que vê no secreto, o recompensará".

[[v40-6-19]]

^<<v40-6-19,19>>^ "Não acumulem para vocês tesouros na terra, onde a traça e a ferrugem destroem, e onde os ladrões arrombam e furtam.

[[v40-6-20]]

^<<v40-6-20,20>>^ Mas acumulem para vocês tesouros no céu, onde a traça e a ferrugem não destroem, e onde os ladrões não arrombam nem furtam.

[[v40-6-21]]

^<<v40-6-21,21>>^ Pois onde estiver o seu tesouro, aí também estará o seu coração.

[[v40-6-22]]

^<<v40-6-22,22>>^ "Os olhos são a candeia do corpo. Se os seus olhos forem bons, todo o seu corpo será cheio de luz.

[[v40-6-23]]

^<<v40-6-23,23>>^ Mas se os seus olhos forem maus, todo o seu corpo será cheio de trevas. Portanto, se a luz que está dentro de você são trevas, que tremendas trevas são!

[[v40-6-24]]

^<<v40-6-24,24>>^ "Ninguém pode servir a dois senhores; pois odiará a um e amará o outro, ou se dedicará a um e desprezará o outro. Vocês não podem servir a Deus e ao Dinheiro".

[[v40-6-25]]

^<<v40-6-25,25>>^ "Portanto eu lhes digo: não se preocupem com suas próprias vidas, quanto ao que comer ou beber; nem com seus próprios corpos, quanto ao que vestir. Não é a vida mais importante do que a comida, e o corpo mais importante do que a roupa?

[[v40-6-26]]

^<<v40-6-26,26>>^ Observem as aves do céu: não semeiam nem colhem nem armazenam em celeiros; contudo, o Pai celestial as alimenta. Não têm vocês muito mais valor do que elas?

[[v40-6-27]]

^<<v40-6-27,27>>^ Quem de vocês, por mais que se preocupe, pode acrescentar uma hora que seja à sua vida?

[[v40-6-28]]

^<<v40-6-28,28>>^ "Por que vocês se preocupam com roupas? Vejam como crescem os lírios do campo. Eles não trabalham nem tecem.

[[v40-6-29]]

^<<v40-6-29,29>>^ Contudo, eu lhes digo que nem Salomão, em todo o seu esplendor, vestiu-se como um deles.

[[v40-6-30]]

^<<v40-6-30,30>>^ Se Deus veste assim a erva do campo, que hoje existe e amanhã é lançada ao fogo, não vestirá muito mais a vocês, homens de pequena fé?

[[v40-6-31]]

^<<v40-6-31,31>>^ Portanto, não se preocupem, dizendo: ‘Que vamos comer? ’ ou ‘que vamos beber? ’ ou ‘que vamos vestir? ’

[[v40-6-32]]

^<<v40-6-32,32>>^ Pois os pagãos é que correm atrás dessas coisas; mas o Pai celestial sabe que vocês precisam delas.

[[v40-6-33]]

^<<v40-6-33,33>>^ Busquem, pois, em primeiro lugar o Reino de Deus e a sua justiça, e todas essas coisas lhes serão acrescentadas.

[[v40-6-34]]

^<<v40-6-34,34>>^ Portanto, não se preocupem com o amanhã, pois o amanhã se preocupará consigo mesmo. Basta a cada dia o seu próprio mal".

'''

xref:040-mateus/040-mateus-005.adoc#v40-5-0[&#60; Capítulo Anterior] | <<v40-6-0,Topo>> | xref:040-mateus/040-mateus-007.adoc#v40-7-0[Próximo Capítulo &#62;]