include::./index.adoc[]

[[v40-27-0]]
=== Mateus, 27
// nvi ?, NVI - Nova Versão Internacional

[[v40-27-1]]

^<<v40-27-1,1>>^ De manhã cedo, todos os chefes dos sacerdotes e líderes religiosos do povo tomaram a decisão de condenar Jesus à morte.

[[v40-27-2]]

^<<v40-27-2,2>>^ E, amarrando-o, levaram-no e o entregaram a Pilatos, o governador.

[[v40-27-3]]

^<<v40-27-3,3>>^ Quando Judas, que o havia traído, viu que Jesus fora condenado, foi tomado de remorso e devolveu aos chefes dos sacerdotes e aos líderes religiosos as trinta moedas de prata.

[[v40-27-4]]

^<<v40-27-4,4>>^ E disse: "Pequei, pois traí sangue inocente". E eles retrucaram: "Que nos importa? A responsabilidade é sua".

[[v40-27-5]]

^<<v40-27-5,5>>^ Então Judas jogou o dinheiro dentro do templo, saindo, foi e enforcou-se.

[[v40-27-6]]

^<<v40-27-6,6>>^ Os chefes dos sacerdotes ajuntaram as moedas e disseram: "É contra a lei colocar este dinheiro no tesouro, visto que é preço de sangue".

[[v40-27-7]]

^<<v40-27-7,7>>^ Então decidiram usar aquele dinheiro para comprar o campo do Oleiro, para cemitério de estrangeiros.

[[v40-27-8]]

^<<v40-27-8,8>>^ Por isso ele se chama campo de Sangue até o dia de hoje.

[[v40-27-9]]

^<<v40-27-9,9>>^ Então se cumpriu o que fora dito pelo profeta Jeremias: "Tomaram as trinta moedas de prata, preço em que foi avaliado pelo povo de Israel,

[[v40-27-10]]

^<<v40-27-10,10>>^ e as usaram para comprar o campo do Oleiro, como o Senhor me ordenou".

[[v40-27-11]]

^<<v40-27-11,11>>^ Jesus foi posto diante do governador, e este lhe perguntou: "Você é o rei dos judeus? " Respondeu-lhe Jesus: "Tu o dizes".

[[v40-27-12]]

^<<v40-27-12,12>>^ Acusado pelos chefes dos sacerdotes e pelos líderes religiosos, ele nada respondeu.

[[v40-27-13]]

^<<v40-27-13,13>>^ Então Pilatos lhe perguntou: "Você não ouve a acusação que eles estão fazendo contra você? "

[[v40-27-14]]

^<<v40-27-14,14>>^ Mas Jesus não lhe respondeu nenhuma palavra, de modo que o governador ficou muito impressionado.

[[v40-27-15]]

^<<v40-27-15,15>>^ Por ocasião da festa era costume do governador soltar um prisioneiro escolhido pela multidão.

[[v40-27-16]]

^<<v40-27-16,16>>^ Eles tinham, naquela ocasião, um prisioneiro muito conhecido, chamado Barrabás.

[[v40-27-17]]

^<<v40-27-17,17>>^ Pilatos perguntou à multidão que ali se havia reunido: "Qual destes vocês querem que lhes solte: Barrabás ou Jesus, chamado Cristo? "

[[v40-27-18]]

^<<v40-27-18,18>>^ Porque sabia que o haviam entregado por inveja.

[[v40-27-19]]

^<<v40-27-19,19>>^ Estando Pilatos sentado no tribunal, sua mulher lhe enviou esta mensagem: "Não se envolva com este inocente, porque hoje, em sonho, sofri muito por causa dele".

[[v40-27-20]]

^<<v40-27-20,20>>^ Mas os chefes dos sacerdotes e os líderes religiosos convenceram a multidão a que pedisse Barrabás e mandasse executar a Jesus.

[[v40-27-21]]

^<<v40-27-21,21>>^ Então perguntou o governador: "Qual dos dois vocês querem que eu lhes solte? " Responderam eles: "Barrabás! "

[[v40-27-22]]

^<<v40-27-22,22>>^ Perguntou Pilatos: "Que farei então com Jesus, chamado Cristo? " Todos responderam: "Crucifica-o! "

[[v40-27-23]]

^<<v40-27-23,23>>^ "Por quê? Que crime ele cometeu? ", perguntou Pilatos. Mas eles gritavam ainda mais: "Crucifica-o! "

[[v40-27-24]]

^<<v40-27-24,24>>^ Quando Pilatos percebeu que não estava obtendo nenhum resultado, mas, pelo contrário, estava se iniciando um tumulto, mandou trazer água, lavou as mãos diante da multidão e disse: "Estou inocente do sangue deste homem; a responsabilidade é de vocês".

[[v40-27-25]]

^<<v40-27-25,25>>^ Todo o povo respondeu: "Que o sangue dele caia sobre nós e sobre nossos filhos! "

[[v40-27-26]]

^<<v40-27-26,26>>^ Então Pilatos soltou-lhes Barrabás, mandou açoitar Jesus e o entregou para ser crucificado.

[[v40-27-27]]

^<<v40-27-27,27>>^ Então, os soldados do governador levaram Jesus ao Pretório e reuniram toda a tropa ao seu redor.

[[v40-27-28]]

^<<v40-27-28,28>>^ Tiraram-lhe as vestes e puseram nele um manto vermelho;

[[v40-27-29]]

^<<v40-27-29,29>>^ fizeram uma coroa de espinhos e a colocaram em sua cabeça. Puseram uma vara em sua mão direita e, ajoelhando-se diante dele, zombavam: "Salve, rei dos judeus! "

[[v40-27-30]]

^<<v40-27-30,30>>^ Cuspiram nele e, tirando-lhe a vara, batiam-lhe com ela na cabeça.

[[v40-27-31]]

^<<v40-27-31,31>>^ Depois de terem zombado dele, tiraram-lhe o manto e vestiram-lhe suas próprias roupas. Então o levaram para crucificá-lo.

[[v40-27-32]]

^<<v40-27-32,32>>^ Ao saírem, encontraram um homem de Cirene, chamado Simão, e o forçaram a carregar a cruz.

[[v40-27-33]]

^<<v40-27-33,33>>^ Chegaram a um lugar chamado Gólgota, que quer dizer Lugar da Caveira,

[[v40-27-34]]

^<<v40-27-34,34>>^ e lhe deram para beber vinho misturado com fel; mas, depois de prová-lo, recusou-se a beber.

[[v40-27-35]]

^<<v40-27-35,35>>^ Depois de o crucificarem, dividiram as roupas dele, tirando sortes.

[[v40-27-36]]

^<<v40-27-36,36>>^ E, sentando-se, vigiavam-no ali.

[[v40-27-37]]

^<<v40-27-37,37>>^ Por cima de sua cabeça colocaram por escrito a acusação feita contra ele: ESTE É JESUS, O REI DOS JUDEUS.

[[v40-27-38]]

^<<v40-27-38,38>>^ Dois ladrões foram crucificados com ele, um à sua direita e outro à sua esquerda.

[[v40-27-39]]

^<<v40-27-39,39>>^ Os que passavam lançavam-lhe insultos, balançando a cabeça

[[v40-27-40]]

^<<v40-27-40,40>>^ e dizendo: "Você que destrói o templo e o reedifica em três dias, salve-se! Desça da cruz, se é Filho de Deus! "

[[v40-27-41]]

^<<v40-27-41,41>>^ Da mesma forma, os chefes dos sacerdotes, os mestres da lei e os líderes religiosos zombavam dele,

[[v40-27-42]]

^<<v40-27-42,42>>^ dizendo: "Salvou os outros, mas não é capaz de salvar a si mesmo! E é o rei de Israel! Desça agora da cruz, e creremos nele.

[[v40-27-43]]

^<<v40-27-43,43>>^ Ele confiou em Deus. Que Deus o salve agora, se dele tem compaixão, pois disse: ‘Sou o Filho de Deus! ’ "

[[v40-27-44]]

^<<v40-27-44,44>>^ Igualmente o insultavam os ladrões que haviam sido crucificados com ele.

[[v40-27-45]]

^<<v40-27-45,45>>^ E houve trevas sobre toda a terra, do meio dia às três horas da tarde.

[[v40-27-46]]

^<<v40-27-46,46>>^ Por volta das três horas da tarde, Jesus bradou em alta voz: "Eloí, Eloí, lamá sabactâni? " que significa: "Meu Deus! Meu Deus! Por que me abandonaste? "

[[v40-27-47]]

^<<v40-27-47,47>>^ Quando alguns dos que estavam ali ouviram isso, disseram: "Ele está chamando Elias".

[[v40-27-48]]

^<<v40-27-48,48>>^ Imediatamente, um deles correu em busca de uma esponja, embebeu-a em vinagre, colocou-a na ponta de uma vara e deu-a a Jesus para beber.

[[v40-27-49]]

^<<v40-27-49,49>>^ Mas os outros disseram: "Deixem-no. Vejamos se Elias vem salvá-lo".

[[v40-27-50]]

^<<v40-27-50,50>>^ Depois de ter bradado novamente em alta voz, Jesus entregou o espírito.

[[v40-27-51]]

^<<v40-27-51,51>>^ Naquele momento, o véu do santuário rasgou-se em duas partes, de alto a baixo. A terra tremeu, e as rochas se partiram.

[[v40-27-52]]

^<<v40-27-52,52>>^ Os sepulcros se abriram, e os corpos de muitos santos que tinham morrido foram ressuscitados.

[[v40-27-53]]

^<<v40-27-53,53>>^ E, saindo dos sepulcros, depois da ressurreição de Jesus, entraram na cidade santa e apareceram a muitos.

[[v40-27-54]]

^<<v40-27-54,54>>^ Quando o centurião e os que com ele vigiavam Jesus viram o terremoto e tudo o que havia acontecido, ficaram aterrorizados e exclamaram: "Verdadeiramente este era o Filho de Deus! "

[[v40-27-55]]

^<<v40-27-55,55>>^ Muitas mulheres estavam ali, observando de longe. Elas haviam seguido Jesus desde a Galiléia, para o servir.

[[v40-27-56]]

^<<v40-27-56,56>>^ Entre elas estavam Maria Madalena; Maria, mãe de Tiago e de José; e a mãe dos filhos de Zebedeu.

[[v40-27-57]]

^<<v40-27-57,57>>^ Ao cair da tarde chegou um homem rico, de Arimatéia, chamado José, que se tornara discípulo de Jesus.

[[v40-27-58]]

^<<v40-27-58,58>>^ Dirigindo-se a Pilatos, pediu o corpo de Jesus, e Pilatos ordenou que lhe fosse entregue.

[[v40-27-59]]

^<<v40-27-59,59>>^ José tomou o corpo, envolveu-o num limpo lençol de linho

[[v40-27-60]]

^<<v40-27-60,60>>^ e o colocou num sepulcro novo, que ele havia mandado cavar na rocha. E, fazendo rolar uma grande pedra sobre a entrada do sepulcro, retirou-se.

[[v40-27-61]]

^<<v40-27-61,61>>^ Maria Madalena e a outra Maria estavam assentadas ali, em frente do sepulcro.

[[v40-27-62]]

^<<v40-27-62,62>>^ No outro dia, que era o seguinte ao da Preparação, os chefes dos sacerdotes e os fariseus dirigiram-se a Pilatos

[[v40-27-63]]

^<<v40-27-63,63>>^ e disseram: "Senhor, lembramos que, enquanto ainda estava vivo, aquele impostor disse: ‘Depois de três dias ressuscitarei’.

[[v40-27-64]]

^<<v40-27-64,64>>^ Ordena, pois, que o sepulcro dele seja guardado até o terceiro dia, para que não venham seus discípulos e, roubando o corpo, digam ao povo que ele ressuscitou dentre os mortos. Este último engano será pior do que o primeiro".

[[v40-27-65]]

^<<v40-27-65,65>>^ "Levem um destacamento", respondeu Pilatos. "Podem ir, e mantenham o sepulcro em segurança como acharem melhor".

[[v40-27-66]]

^<<v40-27-66,66>>^ Eles foram e armaram um esquema de segurança no sepulcro; e além de deixarem um destacamento montando guarda, lacraram a pedra.

'''

xref:040-mateus/040-mateus-026.adoc#v40-26-0[&#60; Capítulo Anterior] | <<v40-27-0,Topo>> | xref:040-mateus/040-mateus-028.adoc#v40-28-0[Próximo Capítulo &#62;]