include::./index.adoc[]

[[v40-25-0]]
=== Mateus, 25
// nvi ?, NVI - Nova Versão Internacional

[[v40-25-1]]

^<<v40-25-1,1>>^ "O Reino dos céus, pois, será semelhante a dez virgens que pegaram suas candeias e saíram para encontrar-se com o noivo.

[[v40-25-2]]

^<<v40-25-2,2>>^ Cinco delas eram insensatas, e cinco eram prudentes.

[[v40-25-3]]

^<<v40-25-3,3>>^ As insensatas pegaram suas candeias, mas não levaram óleo consigo.

[[v40-25-4]]

^<<v40-25-4,4>>^ As prudentes, porém, levaram óleo em vasilhas juntamente com suas candeias.

[[v40-25-5]]

^<<v40-25-5,5>>^ O noivo demorou a chegar, e todas ficaram com sono e adormeceram.

[[v40-25-6]]

^<<v40-25-6,6>>^ "À meia-noite, ouviu-se um grito: ‘O noivo se aproxima! Saiam para encontrá-lo! ’

[[v40-25-7]]

^<<v40-25-7,7>>^ "Então todas as virgens acordaram e prepararam suas candeias.

[[v40-25-8]]

^<<v40-25-8,8>>^ As insensatas disseram às prudentes: ‘Dêem-nos um pouco do seu óleo, pois as nossas candeias estão se apagando’.

[[v40-25-9]]

^<<v40-25-9,9>>^ "Elas responderam: ‘Não, pois pode ser que não haja o suficiente para nós e para vocês. Vão comprar óleo para vocês’.

[[v40-25-10]]

^<<v40-25-10,10>>^ "E saindo elas para comprar o óleo, chegou o noivo. As virgens que estavam preparadas entraram com ele para o banquete nupcial. E a porta foi fechada.

[[v40-25-11]]

^<<v40-25-11,11>>^ "Mais tarde vieram também as outras e disseram: ‘Senhor! Senhor! Abra a porta para nós! ’

[[v40-25-12]]

^<<v40-25-12,12>>^ "Mas ele respondeu: ‘A verdade é que não as conheço! ’

[[v40-25-13]]

^<<v40-25-13,13>>^ "Portanto, vigiem, porque vocês não sabem o dia nem a hora! "

[[v40-25-14]]

^<<v40-25-14,14>>^ "E também será como um homem que, ao sair de viagem, chamou seus servos e confiou-lhes os seus bens.

[[v40-25-15]]

^<<v40-25-15,15>>^ A um deu cinco talentos, a outro dois, e a outro um; a cada um de acordo com a sua capacidade. Em seguida partiu de viagem.

[[v40-25-16]]

^<<v40-25-16,16>>^ O que havia recebido cinco talentos saiu imediatamente, aplicou-os, e ganhou mais cinco.

[[v40-25-17]]

^<<v40-25-17,17>>^ Também o que tinha dois talentos ganhou mais dois.

[[v40-25-18]]

^<<v40-25-18,18>>^ Mas o que tinha recebido um talento saiu, cavou um buraco no chão e escondeu o dinheiro do seu senhor.

[[v40-25-19]]

^<<v40-25-19,19>>^ "Depois de muito tempo o senhor daqueles servos voltou e acertou contas com eles.

[[v40-25-20]]

^<<v40-25-20,20>>^ O que tinha recebido cinco talentos trouxe os outros cinco e disse: ‘O senhor me confiou cinco talentos; veja, eu ganhei mais cinco’.

[[v40-25-21]]

^<<v40-25-21,21>>^ "O senhor respondeu: ‘Muito bem, servo bom e fiel! Você foi fiel no pouco; eu o porei sobre o muito. Venha e participe da alegria do seu senhor! ’

[[v40-25-22]]

^<<v40-25-22,22>>^ "Veio também o que tinha recebido dois talentos e disse: ‘O senhor me confiou dois talentos; veja, eu ganhei mais dois’.

[[v40-25-23]]

^<<v40-25-23,23>>^ "O senhor respondeu: ‘Muito bem, servo bom e fiel! Você foi fiel no pouco; eu o porei sobre o muito. Venha e participe da alegria do seu senhor! ’

[[v40-25-24]]

^<<v40-25-24,24>>^ "Por fim veio o que tinha recebido um talento e disse: ‘Eu sabia que o senhor é um homem severo, que colhe onde não plantou e junta onde não semeou.

[[v40-25-25]]

^<<v40-25-25,25>>^ Por isso, tive medo, saí e escondi o seu talento no chão. Veja, aqui está o que lhe pertence’.

[[v40-25-26]]

^<<v40-25-26,26>>^ "O senhor respondeu: ‘Servo mau e negligente! Você sabia que eu colho onde não plantei e junto onde não semeei?

[[v40-25-27]]

^<<v40-25-27,27>>^ Então você devia ter confiado o meu dinheiro aos banqueiros, para que, quando eu voltasse, o recebesse de volta com juros.

[[v40-25-28]]

^<<v40-25-28,28>>^ " ‘Tirem o talento dele e entreguem-no ao que tem dez.

[[v40-25-29]]

^<<v40-25-29,29>>^ Pois a quem tem, mais será dado, e terá em grande quantidade. Mas a quem não tem, até o que tem lhe será tirado.

[[v40-25-30]]

^<<v40-25-30,30>>^ E lancem fora o servo inútil, nas trevas, onde haverá choro e ranger de dentes’ ".

[[v40-25-31]]

^<<v40-25-31,31>>^ "Quando o Filho do homem vier em sua glória, com todos os anjos, assentar-se-á em seu trono na glória celestial.

[[v40-25-32]]

^<<v40-25-32,32>>^ Todas as nações serão reunidas diante dele, e ele separará umas das outras como o pastor separa as ovelhas dos bodes.

[[v40-25-33]]

^<<v40-25-33,33>>^ E colocará as ovelhas à sua direita e os bodes à sua esquerda.

[[v40-25-34]]

^<<v40-25-34,34>>^ "Então o Rei dirá aos que estiverem à sua direita: ‘Venham, benditos de meu Pai! Recebam como herança o Reino que lhes foi preparado desde a criação do mundo.

[[v40-25-35]]

^<<v40-25-35,35>>^ Pois eu tive fome, e vocês me deram de comer; tive sede, e vocês me deram de beber; fui estrangeiro, e vocês me acolheram;

[[v40-25-36]]

^<<v40-25-36,36>>^ necessitei de roupas, e vocês me vestiram; estive enfermo, e vocês cuidaram de mim; estive preso, e vocês me visitaram’.

[[v40-25-37]]

^<<v40-25-37,37>>^ "Então os justos lhe responderão: ‘Senhor, quando te vimos com fome e te demos de comer, ou com sede e te demos de beber?

[[v40-25-38]]

^<<v40-25-38,38>>^ Quando te vimos como estrangeiro e te acolhemos, ou necessitado de roupas e te vestimos?

[[v40-25-39]]

^<<v40-25-39,39>>^ Quando te vimos enfermo ou preso e fomos te visitar? ’

[[v40-25-40]]

^<<v40-25-40,40>>^ "O Rei responderá: ‘Digo-lhes a verdade: o que vocês fizeram a algum dos meus menores irmãos, a mim o fizeram’.

[[v40-25-41]]

^<<v40-25-41,41>>^ "Então ele dirá aos que estiverem à sua esquerda: ‘Malditos, apartem-se de mim para o fogo eterno, preparado para o diabo e os seus anjos.

[[v40-25-42]]

^<<v40-25-42,42>>^ Pois eu tive fome, e vocês não me deram de comer; tive sede, e nada me deram para beber;

[[v40-25-43]]

^<<v40-25-43,43>>^ fui estrangeiro, e vocês não me acolheram; necessitei de roupas, e vocês não me vestiram; estive enfermo e preso, e vocês não me visitaram’.

[[v40-25-44]]

^<<v40-25-44,44>>^ "Eles também responderão: ‘Senhor, quando te vimos com fome ou com sede ou estrangeiro ou necessitado de roupas ou enfermo ou preso, e não te ajudamos? ’

[[v40-25-45]]

^<<v40-25-45,45>>^ "Ele responderá: ‘Digo-lhes a verdade: o que vocês deixaram de fazer a alguns destes mais pequeninos, também a mim deixaram de fazê-lo’.

[[v40-25-46]]

^<<v40-25-46,46>>^ "E estes irão para o castigo eterno, mas os justos para a vida eterna".

'''

xref:040-mateus/040-mateus-024.adoc#v40-24-0[&#60; Capítulo Anterior] | <<v40-25-0,Topo>> | xref:040-mateus/040-mateus-026.adoc#v40-26-0[Próximo Capítulo &#62;]