include::./index.adoc[]

[[v40-20-0]]
=== Mateus, 20
// nvi ?, NVI - Nova Versão Internacional

[[v40-20-1]]

^<<v40-20-1,1>>^ "Pois o Reino dos céus é como um proprietário que saiu de manhã cedo para contratar trabalhadores para a sua vinha.

[[v40-20-2]]

^<<v40-20-2,2>>^ Ele combinou pagar-lhes um denário pelo dia e mandou-os para a sua vinha.

[[v40-20-3]]

^<<v40-20-3,3>>^ "Por volta das noves hora da manhã, ele saiu e viu outros que estavam desocupados na praça,

[[v40-20-4]]

^<<v40-20-4,4>>^ e lhes disse: ‘Vão também trabalhar na vinha, e eu lhes pagarei o que for justo’.

[[v40-20-5]]

^<<v40-20-5,5>>^ E eles foram. "Saindo outra vez, por volta do meio dia e das três horas da tarde e nona, fez a mesma coisa.

[[v40-20-6]]

^<<v40-20-6,6>>^ Saindo por volta da cinco horas da tarde, encontrou ainda outros que estavam desocupados e lhes perguntou: ‘Por que vocês estiveram aqui desocupados o dia todo? ’

[[v40-20-7]]

^<<v40-20-7,7>>^ ‘Porque ninguém nos contratou’, responderam eles. "Ele lhes disse: ‘Vão vocês também trabalhar na vinha’.

[[v40-20-8]]

^<<v40-20-8,8>>^ "Ao cair da tarde, o dono da vinha disse a seu administrador: ‘Chame os trabalhadores e pague-lhes o salário, começando com os últimos contratados e terminando nos primeiros’.

[[v40-20-9]]

^<<v40-20-9,9>>^ "Vieram os trabalhadores contratados por volta das cinco horas da tarde, e cada um recebeu um denário.

[[v40-20-10]]

^<<v40-20-10,10>>^ Quando vieram os que tinham sido contratados primeiro, esperavam receber mais. Mas cada um deles também recebeu um denário.

[[v40-20-11]]

^<<v40-20-11,11>>^ Quando o receberam, começaram a se queixar do proprietário da vinha,

[[v40-20-12]]

^<<v40-20-12,12>>^ dizendo-lhe: ‘Estes homens contratados por último trabalharam apenas uma hora, e o senhor os igualou a nós, que suportamos o peso do trabalho e o calor do dia’.

[[v40-20-13]]

^<<v40-20-13,13>>^ "Mas ele respondeu a um deles: ‘Amigo, não estou sendo injusto com você. Você não concordou em trabalhar por um denário?

[[v40-20-14]]

^<<v40-20-14,14>>^ Receba o que é seu e vá. Eu quero dar ao que foi contratado por último o mesmo que lhe dei.

[[v40-20-15]]

^<<v40-20-15,15>>^ Não tenho o direito de fazer o que quero com o meu dinheiro? Ou você está com inveja porque sou generoso? ’

[[v40-20-16]]

^<<v40-20-16,16>>^ "Assim, os últimos serão primeiros, e os primeiros serão últimos".

[[v40-20-17]]

^<<v40-20-17,17>>^ Enquanto estava subindo para Jerusalém, Jesus chamou em particular os doze discípulos e lhes disse:

[[v40-20-18]]

^<<v40-20-18,18>>^ "Estamos subindo para Jerusalém, e o Filho do homem será entregue aos chefes dos sacerdotes e aos mestres da lei. Eles o condenarão à morte

[[v40-20-19]]

^<<v40-20-19,19>>^ e o entregarão aos gentios para que zombem dele, o açoitem e o crucifiquem. No terceiro dia ele ressuscitará! "

[[v40-20-20]]

^<<v40-20-20,20>>^ Então, aproximou-se de Jesus a mãe dos filhos de Zebedeu com seus filhos e, prostrando-se, fez-lhe um pedido.

[[v40-20-21]]

^<<v40-20-21,21>>^ "O que você quer? ", perguntou ele. Ela respondeu: "Declara que no teu Reino estes meus dois filhos se assentarão um à tua direita e o outro à tua esquerda".

[[v40-20-22]]

^<<v40-20-22,22>>^ Disse-lhes Jesus: "Vocês não sabem o que estão pedindo. Podem vocês beber o cálice que eu vou beber? " "Podemos", responderam eles.

[[v40-20-23]]

^<<v40-20-23,23>>^ Jesus lhes disse: "Certamente vocês beberão do meu cálice; mas o assentar-se à minha direita ou à minha esquerda não cabe a mim conceder. Esses lugares pertencem àqueles para quem foram preparados por meu Pai".

[[v40-20-24]]

^<<v40-20-24,24>>^ Quando os outros dez ouviram isso, ficaram indignados com os dois irmãos.

[[v40-20-25]]

^<<v40-20-25,25>>^ Jesus os chamou e disse: "Vocês sabem que os governantes das nações as dominam, e as pessoas importantes exercem poder sobre elas.

[[v40-20-26]]

^<<v40-20-26,26>>^ Não será assim entre vocês. Pelo contrário, quem quiser tornar-se importante entre vocês deverá ser servo,

[[v40-20-27]]

^<<v40-20-27,27>>^ e quem quiser ser o primeiro deverá ser escravo;

[[v40-20-28]]

^<<v40-20-28,28>>^ como o Filho do homem, que não veio para ser servido, mas para servir e dar a sua vida em resgate por muitos".

[[v40-20-29]]

^<<v40-20-29,29>>^ Ao saírem de Jericó, uma grande multidão seguiu a Jesus.

[[v40-20-30]]

^<<v40-20-30,30>>^ Dois cegos estavam sentados à beira do caminho e, quando ouviram falar que Jesus estava passando, puseram-se a gritar: "Senhor, Filho de Davi, tem misericórdia de nós! "

[[v40-20-31]]

^<<v40-20-31,31>>^ A multidão os repreendeu para que ficassem quietos, mas eles gritavam ainda mais: "Senhor, Filho de Davi, tem misericórdia de nós! "

[[v40-20-32]]

^<<v40-20-32,32>>^ Jesus, parando, chamou-os e perguntou-lhes: "O que vocês querem que eu lhes faça? "

[[v40-20-33]]

^<<v40-20-33,33>>^ Responderam eles: "Senhor, queremos que se abram os nossos olhos".

[[v40-20-34]]

^<<v40-20-34,34>>^ Jesus teve compaixão deles e tocou nos olhos deles. Imediatamente eles recuperaram a visão e o seguiram.

'''

xref:040-mateus/040-mateus-019.adoc#v40-19-0[&#60; Capítulo Anterior] | <<v40-20-0,Topo>> | xref:040-mateus/040-mateus-021.adoc#v40-21-0[Próximo Capítulo &#62;]