include::./index.adoc[]

[[v22-4-0]]
=== Cânticos, 4
// nvi ?, NVI - Nova Versão Internacional

[[v22-4-1]]

^<<v22-4-1,1>>^ Como você é linda, minha querida! Ah, como é linda! Seus olhos, por trás do véu, são pombas. Seu cabelo é como um rebanho de cabras que vem descendo do monte Gileade.

[[v22-4-2]]

^<<v22-4-2,2>>^ Seus dentes são como um rebanho de ovelhas recém-tosquiadas que vão subindo do lavadouro. Cada uma tem o seu par; não há nenhuma sem crias.

[[v22-4-3]]

^<<v22-4-3,3>>^ Seus lábios são como um fio vermelho; sua boca é belíssima. Suas faces, por trás do véu, são como as metades de uma romã.

[[v22-4-4]]

^<<v22-4-4,4>>^ Seu pescoço é como a torre de Davi, construída como arsenal. Nela estão pendurados mil escudos, todos eles escudos de heróicos guerreiros.

[[v22-4-5]]

^<<v22-4-5,5>>^ Seus dois seios são como filhotes de cervo, como filhotes gêmeos de uma gazela que repousam entre os lírios.

[[v22-4-6]]

^<<v22-4-6,6>>^ Enquanto não raia o dia e as sombras não fogem, irei à montanha da mirra e à colina do incenso.

[[v22-4-7]]

^<<v22-4-7,7>>^ Você é toda linda, minha querida; em você não há defeito algum.

[[v22-4-8]]

^<<v22-4-8,8>>^ Venha do Líbano comigo, minha noiva, venha do Líbano comigo. Desça do alto do Amana, do topo do Senir, do alto do Hermom, das covas dos leões e das tocas dos leopardos nas montanhas.

[[v22-4-9]]

^<<v22-4-9,9>>^ Você fez disparar o meu coração, minha irmã, minha noiva; fez disparar o meu coração com um simples olhar, com uma simples jóia dos seus colares.

[[v22-4-10]]

^<<v22-4-10,10>>^ Quão deliciosas são as suas carícias, minha irmã, minha noiva! Suas carícias são mais agradáveis que o vinho, e a fragrância do seu perfume supera o de qualquer especiaria!

[[v22-4-11]]

^<<v22-4-11,11>>^ Os seus lábios gotejam a doçura dos favos de mel, minha noiva; leite e mel estão debaixo da sua língua. A fragrância das suas vestes é como a fragrância do Líbano.

[[v22-4-12]]

^<<v22-4-12,12>>^ Você é um jardim fechado, minha irmã, minha noiva; você é uma nascente fechada, uma fonte selada.

[[v22-4-13]]

^<<v22-4-13,13>>^ De você brota um pomar de romãs com frutos seletos, com flores de hena e nardo,

[[v22-4-14]]

^<<v22-4-14,14>>^ nardo e açafrão, cálamo e canela, com todas as madeiras aromáticas, mirra e aloés e as mais finas especiarias.

[[v22-4-15]]

^<<v22-4-15,15>>^ Você é uma fonte de jardim, um poço de águas vivas, que descem do Líbano.

[[v22-4-16]]

^<<v22-4-16,16>>^ Acorde, vento norte! Venha, vento sul! Soprem em meu jardim, para que a sua fragrância se espalhe ao seu redor. Que o meu amado entre em seu jardim e saboreie os seus deliciosos frutos.

'''

xref:022-canticos/022-canticos-003.adoc#v22-3-0[&#60; Capítulo Anterior] | <<v22-4-0,Topo>> | xref:022-canticos/022-canticos-005.adoc#v22-5-0[Próximo Capítulo &#62;]