include::./index.adoc[]

[[v22-6-0]]
=== Cânticos, 6
// nvi ?, NVI - Nova Versão Internacional

[[v22-6-1]]

^<<v22-6-1,1>>^ Para onde foi o seu amado, ó mais linda das mulheres? Diga-nos para onde foi o seu amado e o procuraremos junto com você!

[[v22-6-2]]

^<<v22-6-2,2>>^ O meu amado desceu ao seu jardim, aos canteiros de especiarias, para descansar nos jardins e colher lírios.

[[v22-6-3]]

^<<v22-6-3,3>>^ Eu sou do meu amado, e o meu amado é meu; ele descansa entre os lírios.

[[v22-6-4]]

^<<v22-6-4,4>>^ Minha querida, você é linda como Tirza, bela como Jerusalém, admirável como um exército e suas bandeiras.

[[v22-6-5]]

^<<v22-6-5,5>>^ Desvie de mim os seus olhos, pois eles me perturbam. Seu cabelo é como um rebanho de cabras que desce de Gileade.

[[v22-6-6]]

^<<v22-6-6,6>>^ Seus dentes são como um rebanho de ovelhas que sobem do lavadouro. Cada uma tem o seu par, não há nenhuma sem crias.

[[v22-6-7]]

^<<v22-6-7,7>>^ Suas faces, por trás do véu, são como as metades de uma romã.

[[v22-6-8]]

^<<v22-6-8,8>>^ Pode haver sessenta rainhas, e oitenta concubinas, e um número sem fim de virgens,

[[v22-6-9]]

^<<v22-6-9,9>>^ mas ela é única, a minha pomba, minha mulher ideal! Ela é a filha favorita de sua mãe, a predileta daquela que a deu à luz. Quando outras jovens a vêem, dizem que ela é muito feliz; as rainhas e as concubinas a elogiam.

[[v22-6-10]]

^<<v22-6-10,10>>^ Quem é essa que aparece como o alvorecer, bela como a lua, brilhante como o sol, admirável como um exército e suas bandeiras?

[[v22-6-11]]

^<<v22-6-11,11>>^ Desci ao bosque das nogueiras para ver os renovos no vale, para ver se as videiras tinham brotado e se as romãs estavam em flor.

[[v22-6-12]]

^<<v22-6-12,12>>^ Antes que eu o percebesse, você me colocou entre as carruagens, com um príncipe ao meu lado.

[[v22-6-13]]

^<<v22-6-13,13>>^ Volte, volte, Sulamita; volte, volte, para que a contemplemos. Por que vocês querem contemplar a Sulamita, como na dança de Maanaim?

'''

xref:022-canticos/022-canticos-005.adoc#v22-5-0[&#60; Capítulo Anterior] | <<v22-6-0,Topo>> | xref:022-canticos/022-canticos-007.adoc#v22-7-0[Próximo Capítulo &#62;]