include::./index.adoc[]

[[v22-2-0]]
=== Cânticos, 2
// nvi ?, NVI - Nova Versão Internacional

[[v22-2-1]]

^<<v22-2-1,1>>^ Sou uma flor de Sarom, um lírio dos vales.

[[v22-2-2]]

^<<v22-2-2,2>>^ Como um lírio entre os espinhos é a minha amada entre as jovens.

[[v22-2-3]]

^<<v22-2-3,3>>^ Como uma macieira entre as árvores da floresta é o meu amado entre os jovens. Tenho prazer em sentar-me à sua sombra; o seu fruto é doce ao meu paladar.

[[v22-2-4]]

^<<v22-2-4,4>>^ Ele me levou ao salão de banquetes, e o seu estandarte sobre mim é o amor.

[[v22-2-5]]

^<<v22-2-5,5>>^ Por favor, sustentem-me com passas, revigorem-me com maçãs, pois estou doente de amor.

[[v22-2-6]]

^<<v22-2-6,6>>^ O seu braço esquerdo esteja debaixo da minha cabeça, e o seu braço direito me abrace.

[[v22-2-7]]

^<<v22-2-7,7>>^ Mulheres de Jerusalém, eu as faço jurar pelas gazelas e pelas corças do campo: não despertem nem provoquem o amor enquanto ele não o quiser.

[[v22-2-8]]

^<<v22-2-8,8>>^ Escutem! É o meu amado! Vejam! Aí vem ele, saltando pelos montes, pulando sobre as colinas.

[[v22-2-9]]

^<<v22-2-9,9>>^ O meu amado é como uma gazela, como um cervo novo. Vejam! Lá está ele atrás do nosso muro, observando pelas janelas, espiando pelas grades.

[[v22-2-10]]

^<<v22-2-10,10>>^ O meu amado falou e me disse: Levante-se, minha querida, minha bela, e venha comigo.

[[v22-2-11]]

^<<v22-2-11,11>>^ Veja! O inverno passou; as chuvas acabaram e já se foram.

[[v22-2-12]]

^<<v22-2-12,12>>^ Aparecem flores sobre a terra, e chegou o tempo de cantar; já se ouve em nossa terra o arrulhar dos pombos.

[[v22-2-13]]

^<<v22-2-13,13>>^ A figueira produz os primeiros frutos; as vinhas florescem e espalham sua fragrância. Levante-se, venha, minha querida; minha bela, venha comigo.

[[v22-2-14]]

^<<v22-2-14,14>>^ Minha pomba que está nas fendas da rocha, nos esconderijos, nas encostas dos montes, mostre-me o seu rosto, deixe-me ouvir a sua voz; pois a sua voz é suave, e o seu rosto é lindo.

[[v22-2-15]]

^<<v22-2-15,15>>^ Apanhem para nós as raposas, as raposinhas que estragam as vinhas, pois as nossas vinhas estão floridas.

[[v22-2-16]]

^<<v22-2-16,16>>^ O meu amado é meu, e eu sou dele; ele pastoreia entre os lírios.

[[v22-2-17]]

^<<v22-2-17,17>>^ Volte, amado meu, antes que rompa o dia e fujam as sombras, e seja como a gazela ou como o cervo novo nas colinas escarpadas.

'''

xref:022-canticos/022-canticos-001.adoc#v22-1-0[&#60; Capítulo Anterior] | <<v22-2-0,Topo>> | xref:022-canticos/022-canticos-003.adoc#v22-3-0[Próximo Capítulo &#62;]