include::./index.adoc[]

[[v22-8-0]]
=== Cânticos, 8
// nvi ?, NVI - Nova Versão Internacional

[[v22-8-1]]

^<<v22-8-1,1>>^ Ah, quem dera você fosse meu irmão, amamentado nos seios de minha mãe! Então, se eu o encontrasse fora de casa, eu o beijaria, e ninguém me desprezaria.

[[v22-8-2]]

^<<v22-8-2,2>>^ Eu o conduziria e o traria à casa de minha mãe, e você me ensinaria. Eu lhe daria vinho aromatizado para beber, o néctar das minhas romãs.

[[v22-8-3]]

^<<v22-8-3,3>>^ O seu braço esquerdo esteja debaixo da minha cabeça e o seu braço direito me abrace.

[[v22-8-4]]

^<<v22-8-4,4>>^ Mulheres de Jerusalém, eu as faço jurar: Não despertem nem incomodem o amor enquanto ele não o quiser.

[[v22-8-5]]

^<<v22-8-5,5>>^ Quem vem subindo do deserto, apoiada em seu amado? Debaixo da macieira eu o despertei; ali esteve a sua mãe em trabalho de parto, ali sofreu as dores aquela que o deu à luz.

[[v22-8-6]]

^<<v22-8-6,6>>^ Coloque-me como um selo sobre o seu coração; como um selo sobre o seu braço; pois o amor é tão forte quanto a morte, e o ciúme é tão inflexível quanto a sepultura. Suas brasas são fogo ardente, são labaredas do Senhor.

[[v22-8-7]]

^<<v22-8-7,7>>^ Nem muitas águas conseguem apagar o amor; os rios não conseguem levá-lo na correnteza. Se alguém oferecesse todas as riquezas da sua casa para adquirir o amor, seria totalmente desprezado.

[[v22-8-8]]

^<<v22-8-8,8>>^ Temos uma irmãzinha; seus seios ainda não estão crescidos. O que faremos com nossa irmã no dia em que for pedida em casamento?

[[v22-8-9]]

^<<v22-8-9,9>>^ Se ela for um muro, construiremos sobre ela uma torre de prata. Se ela for uma porta, nós a reforçaremos com tábuas de cedro.

[[v22-8-10]]

^<<v22-8-10,10>>^ Eu sou um muro, e meus seios são as suas torres. Assim me tornei aos olhos dele como alguém que dá paz.

[[v22-8-11]]

^<<v22-8-11,11>>^ Salomão possuía uma vinha em Baal-Hamom; ele entregou a sua vinha a arrendatários. Cada um devia trazer pelos frutos da vinha doze quilos de prata.

[[v22-8-12]]

^<<v22-8-12,12>>^ Quanto à minha própria vinha, essa está em meu poder; os doze quilos de prata são para você, ó Salomão, e dois quilos e meio são para os que tomaram conta dos seus frutos.

[[v22-8-13]]

^<<v22-8-13,13>>^ Você, que habita nos jardins, os amigos desejam ouvi-la; deixe-me ouvir a sua voz!

[[v22-8-14]]

^<<v22-8-14,14>>^ Venha depressa, meu amado, e seja como uma gazela, ou como um cervo novo saltando sobre os montes carregados de especiarias.

'''

xref:022-canticos/022-canticos-007.adoc#v22-7-0[&#60; Capítulo Anterior] | <<v22-8-0,Topo>> | xref:023-isaias/023-isaias-001.adoc#v23-1-0[Próximo Capítulo &#62;]