include::./index.adoc[]

[[v22-3-0]]
=== Cânticos, 3
// nvi ?, NVI - Nova Versão Internacional

[[v22-3-1]]

^<<v22-3-1,1>>^ A noite toda procurei em meu leito aquele a quem o meu coração ama, mas não o encontrei.

[[v22-3-2]]

^<<v22-3-2,2>>^ Vou levantar-me agora e percorrer a cidade, irei por suas ruas e praças; buscarei aquele a quem o meu coração ama. Eu o procurei, mas não o encontrei.

[[v22-3-3]]

^<<v22-3-3,3>>^ As sentinelas me encontraram quando faziam as suas rondas na cidade. "Vocês viram aquele a quem o meu coração ama? ", perguntei.

[[v22-3-4]]

^<<v22-3-4,4>>^ Mal havia passado por elas, quando encontrei aquele a quem o meu coração ama. Eu o segurei e não o deixei ir até que o trouxe para a casa de minha mãe, para o quarto daquela que me concebeu.

[[v22-3-5]]

^<<v22-3-5,5>>^ Mulheres de Jerusalém, eu as faço jurar pelas gazelas e pelas corças do campo: Não despertem nem incomodem o amor enquanto ele não o quiser.

[[v22-3-6]]

^<<v22-3-6,6>>^ Que é que vem subindo do deserto, como uma coluna de fumaça, perfumado com mirra e incenso com extrato de todas as especiarias dos mercadores?

[[v22-3-7]]

^<<v22-3-7,7>>^ Vejam! É a liteira de Salomão, escoltada por sessenta guerreiros, os mais nobres de Israel;

[[v22-3-8]]

^<<v22-3-8,8>>^ todos eles trazem espada, todos são experientes na guerra, cada um com a sua espada, preparado para enfrentar os pavores da noite.

[[v22-3-9]]

^<<v22-3-9,9>>^ O rei Salomão fez para si uma liteira; ele a fez com madeira do Líbano.

[[v22-3-10]]

^<<v22-3-10,10>>^ Suas traves ele fez de prata, seu teto, de ouro. Seu banco foi estofado em púrpura, seu interior foi cuidadosamente preparado pelas mulheres de Jerusalém.

[[v22-3-11]]

^<<v22-3-11,11>>^ Mulheres de Sião, saiam! Venham ver o rei Salomão! Ele está usando a coroa, a coroa que sua mãe lhe colocou no dia do seu casamento, no dia em que o seu coração se alegrou.

'''

xref:022-canticos/022-canticos-002.adoc#v22-2-0[&#60; Capítulo Anterior] | <<v22-3-0,Topo>> | xref:022-canticos/022-canticos-004.adoc#v22-4-0[Próximo Capítulo &#62;]