include::./index.adoc[]

[[v22-1-0]]
=== Cânticos, 1
// nvi ?, NVI - Nova Versão Internacional

[[v22-1-1]]

^<<v22-1-1,1>>^ Cântico dos Cânticos de Salomão.

[[v22-1-2]]

^<<v22-1-2,2>>^ Ah, se ele me beijasse, se a sua boca me cobrisse de beijos...  Sim, as suas carícias são mais agradáveis que o vinho.

[[v22-1-3]]

^<<v22-1-3,3>>^ A fragrância dos seus perfumes é suave; o seu nome é como perfume derramado. Não é à toa que as jovens o amam!

[[v22-1-4]]

^<<v22-1-4,4>>^ Leve-me com você! Vamos depressa! Leve-me o rei para os seus aposentos! Estamos alegres e felizes por sua causa; celebraremos o seu amor mais do que o vinho. Com toda a razão você é amado!

[[v22-1-5]]

^<<v22-1-5,5>>^ Estou escura, mas sou bela, ó mulheres de Jerusalém; escura como as tendas de Quedar, bela como as cortinas de Salomão.

[[v22-1-6]]

^<<v22-1-6,6>>^ Não me fiquem olhando assim porque estou escura; foi o sol que me queimou a pele. Os filhos de minha mãe zangaram-se comigo e fizeram-me tomar conta das vinhas; da minha própria vinha, porém, eu não pude cuidar.

[[v22-1-7]]

^<<v22-1-7,7>>^ Conte-me, você a quem amo, onde faz pastar o seu rebanho e onde faz as suas ovelhas descansarem ao meio-dia? Se eu não o souber, serei como uma mulher coberta com véu junto aos rebanhos dos seus amigos.

[[v22-1-8]]

^<<v22-1-8,8>>^ Se você, a mais linda das mulheres, se você não o sabe, siga a trilha das ovelhas e faça as suas cabritas pastarem junto às tendas dos pastores.

[[v22-1-9]]

^<<v22-1-9,9>>^ Comparo você, minha querida, a uma égua das carruagens do faraó.

[[v22-1-10]]

^<<v22-1-10,10>>^ Como são belas as suas faces entre os brincos, e o seu pescoço com os colares de jóias!

[[v22-1-11]]

^<<v22-1-11,11>>^ Faremos para você brincos de ouro com incrustações de prata.

[[v22-1-12]]

^<<v22-1-12,12>>^ Enquanto o rei estava em seus aposentos, o meu nardo espalhou a sua fragrância.

[[v22-1-13]]

^<<v22-1-13,13>>^ O meu amado é para mim como uma pequenina bolsa de mirra que passa a noite entre os meus seios.

[[v22-1-14]]

^<<v22-1-14,14>>^ O meu amado é para mim um ramalhete de flores de hena das vinhas de En-Gedi.

[[v22-1-15]]

^<<v22-1-15,15>>^ Como você é linda, minha querida! Ah, como é linda! Seus olhos são pombas.

[[v22-1-16]]

^<<v22-1-16,16>>^ Como você é belo, meu amado! Ah, como é encantador! Verdejante é o nosso leito.

[[v22-1-17]]

^<<v22-1-17,17>>^ De cedro são as vigas da nossa casa, e de cipreste os caibros do nosso telhado.

'''

xref:021-eclesiastes/021-eclesiastes-012.adoc#v21-12-0[&#60; Capítulo Anterior] | <<v22-1-0,Topo>> | xref:022-canticos/022-canticos-002.adoc#v22-2-0[Próximo Capítulo &#62;]