include::./index.adoc[]

[[v17-8-0]]
=== Ester, 8
// nvi ?, NVI - Nova Versão Internacional

[[v17-8-1]]

^<<v17-8-1,1>>^ Naquele mesmo dia, o rei Xerxes deu à rainha Ester todos os bens de Hamã, o inimigo dos judeus. E Mardoqueu foi trazido à presença do rei, pois Ester lhe dissera que este era seu parente.

[[v17-8-2]]

^<<v17-8-2,2>>^ O rei tirou seu anel-selo, que havia tomado de Hamã, e o deu a Mardoqueu; e Ester o nomeou para administrar os bens de Hamã.

[[v17-8-3]]

^<<v17-8-3,3>>^ Mas Ester tornou a implorar ao rei, chorando aos seus pés, que revogasse o plano maligno de Hamã, o agagita, contra os judeus.

[[v17-8-4]]

^<<v17-8-4,4>>^ Então o rei estendeu o cetro de ouro para Ester, e ela se levantou diante dele e disse:

[[v17-8-5]]

^<<v17-8-5,5>>^ "Se for do agrado do rei, se posso contar com o seu favor, e se ele considerar justo, que se escreva uma ordem revogando as cartas que Hamã, filho do agagita Hamedata, escreveu para que os judeus fossem exterminados em todas as províncias do império.

[[v17-8-6]]

^<<v17-8-6,6>>^ Pois, como suportarei ver a desgraça que cairá sobre meu o povo? Como suportarei a destruição da minha própria família? "

[[v17-8-7]]

^<<v17-8-7,7>>^ O rei Xerxes respondeu à rainha Ester e ao judeu Mardoqueu: "Mandei enforcar Hamã e dei os seus bens a Ester porque ele atentou contra os judeus.

[[v17-8-8]]

^<<v17-8-8,8>>^ Escrevam agora outro decreto em nome do rei, em favor dos judeus, como melhor lhes parecer, e selem-no com o anel-selo do rei, pois nenhum documento escrito em nome do rei e selado com o seu anel pode ser revogado".

[[v17-8-9]]

^<<v17-8-9,9>>^ Isso aconteceu no dia vinte e três do terceiro mês, o mês de sivã. Os secretários do rei foram imediatamente convocados e escreveram todas as ordens de Mardoqueu aos judeus, aos sátrapas, aos governadores e aos nobres das cento e vinte e sete províncias que se estendiam da Índia até a Etiópia. Essas ordens foram redigidas na língua e na escrita de cada província e de cada povo, e também na língua e na escrita dos judeus.

[[v17-8-10]]

^<<v17-8-10,10>>^ Mardoqueu escreveu em nome do rei Xerxes, selou as cartas com o anel-selo do rei, e as enviou por meio de mensageiros montados em cavalos velozes, das estrebarias do próprio rei.

[[v17-8-11]]

^<<v17-8-11,11>>^ O decreto do rei concedia aos judeus de cada cidade o direito de reunir-se e de proteger-se, de destruir, matar e aniquilar qualquer força armada de qualquer povo ou província que os ameaçasse, a eles, suas mulheres e seus filhos, e de saquear os bens dos seus inimigos.

[[v17-8-12]]

^<<v17-8-12,12>>^ O decretou entrou em vigor nas províncias do rei Xerxes no décimo terceiro dia do décimo segundo mês, o mês de adar.

[[v17-8-13]]

^<<v17-8-13,13>>^ Uma cópia do texto do decreto foi publicada como lei em cada província e levada ao conhecimento do povo de cada nação, a fim de que naquele dia os judeus estivessem prontos para vingar-se dos seus inimigos.

[[v17-8-14]]

^<<v17-8-14,14>>^ Os mensageiros, montando cavalos das estrebarias do rei, saíram a galope, por causa da ordem do rei. O decreto também foi publicado na cidadela de Susã.

[[v17-8-15]]

^<<v17-8-15,15>>^ Mardoqueu saiu da presença do rei usando vestes reais em azul e branco, uma grande coroa de ouro e um manto púrpura de linho fino. E a cidadela de Susã exultava de alegria.

[[v17-8-16]]

^<<v17-8-16,16>>^ Para os judeus foi uma ocasião de felicidade, alegria, júbilo e honra.

[[v17-8-17]]

^<<v17-8-17,17>>^ Em cada província e em cada cidade, onde quer que chegasse o decreto do rei, havia alegria e júbilo entre os judeus, com banquetes e festas. Muitos que pertenciam a outros povos do reino tornaram-se judeus, porque o temor dos judeus tinha se apoderado deles.

'''

xref:017-ester/017-ester-007.adoc#v17-7-0[&#60; Capítulo Anterior] | <<v17-8-0,Topo>> | xref:017-ester/017-ester-009.adoc#v17-9-0[Próximo Capítulo &#62;]