include::./index.adoc[]

[[v17-7-0]]
=== Ester, 7
// nvi ?, NVI - Nova Versão Internacional

[[v17-7-1]]

^<<v17-7-1,1>>^ Então o rei e Hamã foram ao banquete com a rainha Ester,

[[v17-7-2]]

^<<v17-7-2,2>>^ e, enquanto estavam bebendo vinho no segundo dia, o rei perguntou de novo: "Rainha Ester, qual é o seu pedido? Você será atendida. Qual o seu desejo? Mesmo que seja a metade do reino, isso lhe será concedido".

[[v17-7-3]]

^<<v17-7-3,3>>^ Então a rainha Ester respondeu: "Se posso contar com o favor do rei, e se isto lhe agrada, poupe a minha vida e a vida do meu povo; este é o meu pedido e o meu desejo.

[[v17-7-4]]

^<<v17-7-4,4>>^ Pois eu e meu povo fomos vendidos para destruição, morte e aniquilação. Se apenas tivéssemos sido vendidos como escravos e escravas, eu teria ficado em silêncio, porque nenhuma aflição como essa justificaria perturbar o rei".

[[v17-7-5]]

^<<v17-7-5,5>>^ O rei Xerxes perguntou à rainha Ester: "Quem se atreveu a uma coisa dessas? Onde está ele? "

[[v17-7-6]]

^<<v17-7-6,6>>^ Respondeu Ester: "O adversário e inimigo é Hamã, esse perverso". Diante disso, Hamã ficou apavorado na presença do rei e da rainha.

[[v17-7-7]]

^<<v17-7-7,7>>^ Furioso, o rei levantou-se, deixou o vinho, saiu dali e foi para o jardim do palácio. E percebendo Hamã que o rei já tinha decidido condená-lo, ficou ali para implorar por sua vida à rainha Ester.

[[v17-7-8]]

^<<v17-7-8,8>>^ E voltando o rei do jardim do palácio ao salão do banquete, viu Hamã caído sobre o assento onde Ester estava reclinada. E então exclamou: "Chegaria ele ao cúmulo de violentar a rainha na minha presença e em minha própria casa? " Mal o rei terminou de dizer isso, alguns oficiais cobriram o rosto de Hamã.

[[v17-7-9]]

^<<v17-7-9,9>>^ E um deles, chamado Harbona, que estava a serviço do rei, disse: "Há uma forca de mais de vinte metros de altura junto à casa de Hamã, que ele fez para Mardoqueu, que intercedeu pela vida do rei". Então o rei ordenou: "Enforquem-no nela! "

[[v17-7-10]]

^<<v17-7-10,10>>^ Assim Hamã morreu na forca que tinha preparado para Mardoqueu; e a ira do rei se acalmou.

'''

xref:017-ester/017-ester-006.adoc#v17-6-0[&#60; Capítulo Anterior] | <<v17-7-0,Topo>> | xref:017-ester/017-ester-008.adoc#v17-8-0[Próximo Capítulo &#62;]