include::./index.adoc[]

[[v17-5-0]]
=== Ester, 5
// nvi ?, NVI - Nova Versão Internacional

[[v17-5-1]]

^<<v17-5-1,1>>^ Três dias depois, Ester vestiu seus trajes de rainha e colocou-se no pátio interno do palácio, em frente ao salão do rei. O rei estava no trono, de frente para a entrada.

[[v17-5-2]]

^<<v17-5-2,2>>^ Quando viu a rainha Ester ali no pátio, teve misericórdia dela e estendeu-lhe o cetro de ouro que tinha na mão. Ester aproximou-se e tocou a ponta do cetro.

[[v17-5-3]]

^<<v17-5-3,3>>^ E o rei lhe perguntou: "Que há, rainha Ester? Qual é o seu pedido? Mesmo que seja a metade do reino, lhe será dado".

[[v17-5-4]]

^<<v17-5-4,4>>^ Respondeu Ester: "Se for do agrado do rei, venha com Hamã a um banquete que lhe preparei".

[[v17-5-5]]

^<<v17-5-5,5>>^ Disse o rei: "Tragam Hamã imediatamente, para que ele atenda ao pedido de Ester". Então o rei e Hamã foram ao banquete que Ester havia preparado.

[[v17-5-6]]

^<<v17-5-6,6>>^ Enquanto bebiam vinho, o rei tornou a perguntar a Ester: "Qual é o seu pedido? Você será atendida. Qual o seu desejo? Mesmo que seja a metade do reino, lhe será concedido".

[[v17-5-7]]

^<<v17-5-7,7>>^ E Ester respondeu: "Este é o meu pedido e o meu desejo:

[[v17-5-8]]

^<<v17-5-8,8>>^ Se o rei tem consideração por mim, e se lhe agrada atender e conceder o meu pedido, que o rei e Hamã venham amanhã ao banquete que lhes prepararei. Então responderei à pergunta do rei".

[[v17-5-9]]

^<<v17-5-9,9>>^ Naquele dia Hamã saiu alegre e contente. Mas, ficou furioso quando viu que Mardoqueu, que estava junto à porta do palácio real, não se levantou nem mostrou respeito em sua presença.

[[v17-5-10]]

^<<v17-5-10,10>>^ Hamã, porém, controlou-se e foi para casa. Reunindo seus amigos e Zeres, sua mulher,

[[v17-5-11]]

^<<v17-5-11,11>>^ Hamã vangloriou-se de sua grande riqueza, de seus muitos filhos e de como o rei o havia honrado e promovido acima de todos os outros nobres e oficiais.

[[v17-5-12]]

^<<v17-5-12,12>>^ E acrescentou Hamã: "Além disso, sou o único que a rainha Ester convidou para acompanhar o rei ao banquete que ela lhe ofereceu. Ela me convidou para comparecer amanhã, junto com o rei.

[[v17-5-13]]

^<<v17-5-13,13>>^ Mas tudo isso não me dará satisfação, enquanto eu vir aquele judeu Mardoqueu sentado junto à porta do palácio real".

[[v17-5-14]]

^<<v17-5-14,14>>^ Então Zeres, sua mulher, e todos os seus amigos lhe sugeriram: "Mande fazer uma forca, de mais de vinte metros de altura, e logo pela manhã peça ao rei que Mardoqueu seja enforcado nela. Assim você poderá acompanhar o rei ao jantar e alegrar-se". A sugestão agradou Hamã, e ele mandou fazer a forca.

'''

xref:017-ester/017-ester-004.adoc#v17-4-0[&#60; Capítulo Anterior] | <<v17-5-0,Topo>> | xref:017-ester/017-ester-006.adoc#v17-6-0[Próximo Capítulo &#62;]