include::./index.adoc[]

[[v17-9-0]]
=== Ester, 9
// nvi ?, NVI - Nova Versão Internacional

[[v17-9-1]]

^<<v17-9-1,1>>^ No décimo terceiro dia do décimo segundo mês, o mês de adar, entraria em vigor o decreto do rei. Naquele dia os inimigos dos judeus esperavam vencê-los, mas aconteceu o contrário; os judeus dominaram aqueles que os odiavam,

[[v17-9-2]]

^<<v17-9-2,2>>^ reunindo-se em suas cidades, em todas as províncias do rei Xerxes, para atacar os que buscavam a sua destruição. Ninguém conseguia resistir-lhes, porquanto todos os povos estavam com medo deles.

[[v17-9-3]]

^<<v17-9-3,3>>^ E todos os nobres das províncias, os sátrapas, os governadores e os administradores do rei apoiaram os judeus, porque o medo que tinham de Mardoqueu havia se apoderado deles.

[[v17-9-4]]

^<<v17-9-4,4>>^ Mardoqueu era influente no palácio; sua fama espalhou-se pelas províncias, e ele se tornava cada vez mais poderoso.

[[v17-9-5]]

^<<v17-9-5,5>>^ Os judeus feriram todos os seus inimigos à espada, matando-os e destruindo-os, e fizeram o que quiseram com os seus inimigos.

[[v17-9-6]]

^<<v17-9-6,6>>^ Na cidadela de Susã os judeus mataram e destruíram quinhentos homens.

[[v17-9-7]]

^<<v17-9-7,7>>^ Também mataram Parsandata, Dalfom, Aspata,

[[v17-9-8]]

^<<v17-9-8,8>>^ Porata, Adalia, Aridata,

[[v17-9-9]]

^<<v17-9-9,9>>^ Farmasta, Arisai, Aridai e Vaisata,

[[v17-9-10]]

^<<v17-9-10,10>>^ os dez filhos de Hamã, filho de Hamedata, o inimigo dos judeus. Mas não se apossaram dos seus bens.

[[v17-9-11]]

^<<v17-9-11,11>>^ Naquele mesmo dia o total de mortos na cidadela de Susã foi relatado ao rei,

[[v17-9-12]]

^<<v17-9-12,12>>^ que disse à rainha Ester: "Os judeus mataram e destruíram quinhentos homens e os dez filhos de Hamã na cidadela de Susã. Que terão feito nas outras províncias do império? Agora, diga qual é o seu pedido, e você será atendida. Tem ainda algum desejo? Este lhe será concedido".

[[v17-9-13]]

^<<v17-9-13,13>>^ Respondeu Ester: "Se for do agrado do rei, que os judeus de Susã tenham autorização para executar também amanhã o decreto de hoje, para que os corpos dos dez filhos de Hamã sejam pendurados na forca".

[[v17-9-14]]

^<<v17-9-14,14>>^ Então o rei deu ordens para que assim sem fizesse. O decreto foi publicado em Susã, e os corpos dos dez filhos de Hamã foram pendurados na forca.

[[v17-9-15]]

^<<v17-9-15,15>>^ Os judeus de Susã ajuntaram-se no décimo quarto dia do mês de adar e mataram trezentos homens em Susã, mas não se apossaram de seus bens.

[[v17-9-16]]

^<<v17-9-16,16>>^ Enquanto isso, ajuntou-se também o restante dos judeus que viviam nas províncias do império, para se protegerem e se livrarem dos seus inimigos. Eles mataram setenta e cinco mil deles, mas não se apossaram de seus bens.

[[v17-9-17]]

^<<v17-9-17,17>>^ Isso aconteceu no décimo terceiro dia do mês de adar, e no décimo quarto dia descansaram e fizeram dessa data um dia de festa e de alegria.

[[v17-9-18]]

^<<v17-9-18,18>>^ Os judeus de Susã, porém, tinham se reunido no décimo terceiro e no décimo quarto dias, e no décimo quinto descansaram e dele fizeram um dia de festa e de alegria.

[[v17-9-19]]

^<<v17-9-19,19>>^ Por isso os judeus que vivem em vilas e povoados comemoram o décimo quarto dia do mês de adar como um dia de festa e de alegria, um dia de troca de presentes.

[[v17-9-20]]

^<<v17-9-20,20>>^ Mardoqueu registrou esses acontecimentos e enviou cartas a todos os judeus de todas as províncias do rei Xerxes, próximas e distantes,

[[v17-9-21]]

^<<v17-9-21,21>>^ determinado que anualmente se comemorassem os dias décimo quarto e décimo quinto do mês de adar,

[[v17-9-22]]

^<<v17-9-22,22>>^ pois nesses dias os judeus livraram-se dos seus inimigos, e nesse mês a sua tristeza tornou-se em alegria, e o seu pranto, num dia de festa. Escreveu-lhes dizendo que comemorassem aquelas datas como dias de festa e de alegria, de troca de presentes e de ofertas aos pobres.

[[v17-9-23]]

^<<v17-9-23,23>>^ E assim os judeus adotaram como costume aquela comemoração, conforme o que Mardoqueu lhes tinha ordenado por escrito.

[[v17-9-24]]

^<<v17-9-24,24>>^ Pois Hamã, filho do agagita Hamedata, inimigo de todos os judeus, tinha tramado contra eles para destruí-los e tinha lançado o pur, isto é, a sorte para a ruína e destruição deles.

[[v17-9-25]]

^<<v17-9-25,25>>^ Mas quando isso chegou ao conhecimento do rei, ele deu ordens escritas para que o plano maligno de Hamã contra os judeus se voltasse contra a sua própria cabeça, e para que ele e seus filhos fossem enforcados.

[[v17-9-26]]

^<<v17-9-26,26>>^ Por isso aqueles dias foram chamados Purim, da palavra pur. Considerando tudo o que estava escrito nessa carta, o que tinham visto e o que tinha acontecido,

[[v17-9-27]]

^<<v17-9-27,27>>^ os judeus decidiram estabelecer o costume de que eles e os seus descendentes e todos os que se tornassem judeus não deixariam de comemorar anualmente esses dois dias, na forma prescrita e na data certa.

[[v17-9-28]]

^<<v17-9-28,28>>^ Esses dias seriam lembrados e comemorados em cada família de cada geração, em cada província e em cada cidade, e jamais deveriam deixar de ser comemorados pelos judeus. E os seus descendentes jamais deveriam esquecer-se de tais dias.

[[v17-9-29]]

^<<v17-9-29,29>>^ Então a rainha Ester, filha de Abiail, e o judeu Mardoqueu, escreveram com toda a autoridade uma segunda carta para confirmar a primeira carta acerca do Purim.

[[v17-9-30]]

^<<v17-9-30,30>>^ Mardoqueu enviou cartas a todos os judeus das cento e vinte e sete províncias do império de Xerxes, desejando-lhes paz e segurança,

[[v17-9-31]]

^<<v17-9-31,31>>^ e confirmando que os dias de Purim deveriam ser comemorados nas datas determinadas, conforme o judeu Mardoqueu e a rainha Ester tinham decretado e estabelecido para si mesmos, para todos os judeus e para os seus descendentes, e acrescentou observações sobre tempos de jejum e de lamentação.

[[v17-9-32]]

^<<v17-9-32,32>>^ O decreto de Ester confirmou as regras do Purim, e isso foi escrito nos registros.

'''

xref:017-ester/017-ester-008.adoc#v17-8-0[&#60; Capítulo Anterior] | <<v17-9-0,Topo>> | xref:017-ester/017-ester-010.adoc#v17-10-0[Próximo Capítulo &#62;]