include::./index.adoc[]

[[v17-6-0]]
=== Ester, 6
// nvi ?, NVI - Nova Versão Internacional

[[v17-6-1]]

^<<v17-6-1,1>>^ Naquela noite o rei não conseguiu dormir; por isso ordenou que trouxessem o livro das crônicas do seu reinado, e que o lessem para ele.

[[v17-6-2]]

^<<v17-6-2,2>>^ E foi lido o registro de que Mardoqueu tinha denunciado Bigtã e Teres, dois dos oficiais do rei que guardavam a entrada do Palácio, que haviam conspirado para assassinar o rei Xerxes.

[[v17-6-3]]

^<<v17-6-3,3>>^ "Que honra e reconhecimento Mardoqueu recebeu por isso? ", perguntou o rei. Seus oficiais responderam: "Nada lhe foi feito".

[[v17-6-4]]

^<<v17-6-4,4>>^ O rei perguntou: "Quem está no pátio? " Ora, Hamã havia acabado de entrar no pátio externo do palácio para pedir ao rei o enforcamento de Mardoqueu na forca que ele lhe havia preparado.

[[v17-6-5]]

^<<v17-6-5,5>>^ Os oficiais do rei responderam: "É Hamã que está no pátio". "Façam-no entrar", ordenou o rei.

[[v17-6-6]]

^<<v17-6-6,6>>^ Entrando Hamã, o rei lhe perguntou: "O que se deve fazer ao homem que o rei tem o prazer de honrar? " E Hamã pensou consigo: "A quem o rei teria prazer de honrar, senão a mim? "

[[v17-6-7]]

^<<v17-6-7,7>>^ Por isso respondeu ao rei: "Ao homem que o rei tem prazer de honrar,

[[v17-6-8]]

^<<v17-6-8,8>>^ ordena que tragam um manto do próprio rei e um cavalo que o rei montou, e que leve o brasão do rei na cabeça.

[[v17-6-9]]

^<<v17-6-9,9>>^ Em seguida, sejam o manto e o cavalo confiados a alguns dos príncipes mais nobres do rei, e ponham eles o manto sobre o homem que o rei deseja honrar e o conduzam sobre o cavalo pelas ruas da cidade, proclamando diante dele: ‘Isto é o que se faz ao homem que o rei tem o prazer de honrar! ’ "

[[v17-6-10]]

^<<v17-6-10,10>>^ O rei ordenou então a Hamã: "Vá depressa apanhar o manto e o cavalo, e faça ao judeu Mardoqueu o que você sugeriu. Ele está sentado junto à porta do palácio real. Não omita nada do que você recomendou".

[[v17-6-11]]

^<<v17-6-11,11>>^ Então, Hamã apanhou o cavalo, vestiu Mardoqueu com o manto e o conduziu sobre o cavalo pelas ruas da cidade, proclamando à frente dele: "Isto é o que se faz ao homem que o rei tem o prazer de honrar! "

[[v17-6-12]]

^<<v17-6-12,12>>^ Depois disso, Mardoqueu voltou para a porta do palácio real. Hamã, porém, correu para casa com o rosto coberto, muito aborrecido

[[v17-6-13]]

^<<v17-6-13,13>>^ e contou a Zeres, sua mulher, e a todos os seus amigos tudo o que lhe havia acontecido. Tanto o seus conselheiros como Zeres, sua mulher, lhe disseram: "Visto que Mardoqueu, diante de quem começou a sua queda, é de origem judaica, você não terá condições de enfrentá-lo. Sem dúvida, você ficará arruinado! "

[[v17-6-14]]

^<<v17-6-14,14>>^ E, enquanto ainda conversavam, chegaram os oficiais do rei e, às pressas, levaram Hamã para o banquete que Ester havia preparado.

'''

xref:017-ester/017-ester-005.adoc#v17-5-0[&#60; Capítulo Anterior] | <<v17-6-0,Topo>> | xref:017-ester/017-ester-007.adoc#v17-7-0[Próximo Capítulo &#62;]