include::./index.adoc[]

[[v17-1-0]]
=== Ester, 1
// nvi ?, NVI - Nova Versão Internacional

[[v17-1-1]]

^<<v17-1-1,1>>^ Foi no tempo de Xerxes, que reinou sobre cento e vinte e sete províncias, desde a Índia até a Etiópia:

[[v17-1-2]]

^<<v17-1-2,2>>^ naquela época o rei Xerxes reinava em seu trono na cidadela de Susã

[[v17-1-3]]

^<<v17-1-3,3>>^ e, no terceiro ano do seu reinado, deu um banquete a todos os seus nobres e seus oficiais. Estavam presentes os líderes militares da Pérsia e da Média, os príncipes e os nobres das províncias.

[[v17-1-4]]

^<<v17-1-4,4>>^ Durante cento e oitenta dias ele mostrou a enorme riqueza de seu reino e o esplendor e a glória de sua majestade.

[[v17-1-5]]

^<<v17-1-5,5>>^ Terminados esses dias, no jardim interno do palácio, o rei deu um banquete de sete dias para todo o povo que estava na cidadela de Susã, do mais rico ao mais pobre.

[[v17-1-6]]

^<<v17-1-6,6>>^ O jardim possuía forrações em branco e azul, presas com cordas de linho branco, tecido vermelho ligado por anéis de prata em colunas de mármore. Tinha assentos de ouro e prata num piso de mosaicos de pórfiro, mármore, madrepérola e outras pedras preciosas.

[[v17-1-7]]

^<<v17-1-7,7>>^ Pela generosidade do rei, o vinho real era servido em grande quantidade, em diferentes taças de ouro.

[[v17-1-8]]

^<<v17-1-8,8>>^ Por ordem real, cada convidado tinha permissão de beber conforme desejasse, pois o rei tinha instruído todos os mordomos do palácio que os servissem à vontade.

[[v17-1-9]]

^<<v17-1-9,9>>^ Enquanto isso, a rainha Vasti também oferecia um banquete às mulheres, no palácio do rei Xerxes.

[[v17-1-10]]

^<<v17-1-10,10>>^ Ao sétimo dia, quando o rei Xerxes já estava alegre por causa do vinho, ordenou que os sete oficiais que o serviam: Meumã, Bizta, Harbona, Bigtá, Abagta, Zetar e Carcas,

[[v17-1-11]]

^<<v17-1-11,11>>^ trouxessem à sua presença a rainha Vasti, usando a coroa real, para mostrar sua beleza aos súditos e aos nobres, pois ela era muito bonita.

[[v17-1-12]]

^<<v17-1-12,12>>^ Quando, porém, os oficiais transmitiram a ordem do rei à rainha Vasti, esta se recusou a ir, de modo que o rei ficou furioso e indignado.

[[v17-1-13]]

^<<v17-1-13,13>>^ Como era costume o rei consultar especialistas em questões de direito e justiça, ele mandou chamar os sábios que entendiam das leis

[[v17-1-14]]

^<<v17-1-14,14>>^ e eram muito amigos do rei: Carsena, Setar, Adamata, Társis, Meres, Marsena e Memucã; os sete nobres da Pérsia e da Média que tinham acesso direto ao rei e eram os mais importantes do reino.

[[v17-1-15]]

^<<v17-1-15,15>>^ E o rei lhes perguntou: "De acordo com a lei, o que se deve fazer à rainha Vasti? Ela não obedeceu à ordem do rei Xerxes transmitida pelos oficiais".

[[v17-1-16]]

^<<v17-1-16,16>>^ Então Memucã respondeu na presença do rei e dos nobres: "A rainha Vasti não ofendeu somente ao rei, mas também a todos os nobres e os povos de todas as províncias do rei Xerxes,

[[v17-1-17]]

^<<v17-1-17,17>>^ pois a conduta da rainha se tornará conhecida entre todas as mulheres, e assim também elas desprezarão seus maridos e dirão: ‘O rei Xerxes ordenou que a rainha Vasti fosse à sua presença, mas ela não foi’.

[[v17-1-18]]

^<<v17-1-18,18>>^ Hoje mesmo as mulheres persas e medas da nobreza que ficarem sabendo do comportamento da rainha agirão da mesma maneira com todos os nobres do rei. Isso provocará desrespeito e discórdia sem fim.

[[v17-1-19]]

^<<v17-1-19,19>>^ "Por isso, se for do agrado do rei, que ele emita um decreto real, e que seja escrito na lei da Pérsia e da Média, que não se pode revogar, determinando que Vasti nunca mais compareça na presença do rei Xerxes. Também dê o rei a sua posição de rainha a outra que seja melhor do que ela.

[[v17-1-20]]

^<<v17-1-20,20>>^ Assim, quando o decreto real for proclamado por todo o seu imenso domínio, todas as mulheres respeitarão seus maridos, do mais rico ao mais pobre".

[[v17-1-21]]

^<<v17-1-21,21>>^ O rei e seus nobres ficaram satisfeitos com o conselho, de modo que o rei acatou a proposta de Memucã.

[[v17-1-22]]

^<<v17-1-22,22>>^ Assim enviou cartas a todas as partes do reino, a cada província e a cada povo em sua própria escrita e em sua própria língua, proclamando que cada homem deveria mandar em sua própria casa.

'''

xref:016-neemias/016-neemias-013.adoc#v16-13-0[&#60; Capítulo Anterior] | <<v17-1-0,Topo>> | xref:017-ester/017-ester-002.adoc#v17-2-0[Próximo Capítulo &#62;]