include::./index.adoc[]

[[v17-2-0]]
=== Ester, 2
// nvi ?, NVI - Nova Versão Internacional

[[v17-2-1]]

^<<v17-2-1,1>>^ Depois disso, quando cessou a indignação do rei Xerxes, ele se lembrou de Vasti, do que ela havia feito e do que ele tinha decretado contra ela.

[[v17-2-2]]

^<<v17-2-2,2>>^ Então os conselheiros do rei sugeriram que se procurassem virgens lindas para o rei

[[v17-2-3]]

^<<v17-2-3,3>>^ e que se nomeassem comissários em cada província do império para trazer todas essas lindas moças ao harém da cidadela de Susã. Elas estariam sob os cuidados de Hegai, oficial responsável pelo harém; e deveriam receber tratamento de beleza.

[[v17-2-4]]

^<<v17-2-4,4>>^ A moça que mais agradasse o rei seria rainha no lugar de Vasti. Esse conselho agradou o rei, e ele o acatou.

[[v17-2-5]]

^<<v17-2-5,5>>^ Ora, na cidadela de Susã havia um judeu chamado Mardoqueu, da tribo de Benjamim, filho de Jair, neto de Simei e bisneto de Quis,

[[v17-2-6]]

^<<v17-2-6,6>>^ que fora levado de Jerusalém para o exílio por Nabucodonosor, rei da Babilônia, entre os que foram levados prisioneiros com Joaquim, rei de Judá.

[[v17-2-7]]

^<<v17-2-7,7>>^ Mardoqueu tinha uma prima chamada Hadassa, que havia sido criada por ele, por não ter pai nem mãe. Essa moça, também conhecida como Ester, era atraente e muito bonita, e Mardoqueu a havia tomado como filha quando o pai e a mãe dela morreram.

[[v17-2-8]]

^<<v17-2-8,8>>^ Quando a ordem e o decreto do rei foram proclamados, muitas moças foram trazidas à cidadela de Susã e colocadas sob os cuidados de Hegai. Ester também foi trazida ao palácio do rei e confiada a Hegai, encarregado do harém.

[[v17-2-9]]

^<<v17-2-9,9>>^ A moça o agradou e ele a favoreceu. Ele logo lhe providenciou tratamento de beleza e comida especial. Designou-lhe sete moças escolhidas do palácio do rei e transferiu-a, junto com suas jovens, para o melhor lugar do harém.

[[v17-2-10]]

^<<v17-2-10,10>>^ Ester não tinha revelado a que povo pertencia nem a origem da sua família, pois Mardoqueu a havia proibido de fazê-lo.

[[v17-2-11]]

^<<v17-2-11,11>>^ Diariamente ele caminhava de um lado para outro perto do pátio do harém, para saber como Ester estava e o que lhe estava acontecendo.

[[v17-2-12]]

^<<v17-2-12,12>>^ Antes de qualquer daquelas moças apresentar-se ao rei Xerxes, devia completar doze meses de tratamento de beleza prescritos para as mulheres, seis meses com óleo de mirra e seis meses com perfumes e cosméticos.

[[v17-2-13]]

^<<v17-2-13,13>>^ Quando ia apresentar-se ao rei, a moça recebia tudo o que quisesse levar consigo do harém para o palácio do rei.

[[v17-2-14]]

^<<v17-2-14,14>>^ À tarde ela ia para lá e de manhã voltava para outra parte do harém, que ficava sob os cuidados de Saasgaz, oficial responsável pelas concubinas. Ela não voltava ao rei, a menos que dela ele se agradasse e a mandasse chamar pelo nome.

[[v17-2-15]]

^<<v17-2-15,15>>^ Quando chegou a vez de Ester, a moça adotada por Mardoqueu, filha de seu tio Abiail, ela não pediu nada além daquilo que Hegai, oficial responsável pelo harém, sugeriu. Ester agradava a todos os que a viam.

[[v17-2-16]]

^<<v17-2-16,16>>^ Ela foi levada ao rei Xerxes, à residência real, no décimo mês, o mês de tebete, no sétimo ano do seu reinado.

[[v17-2-17]]

^<<v17-2-17,17>>^ Ora, o rei gostou mais de Ester do que de qualquer outra mulher, e ela foi favorecida por ele e ganhou sua aprovação mais do que qualquer das outras virgens. Então ele lhe colocou uma coroa real e tornou-a rainha no lugar de Vasti.

[[v17-2-18]]

^<<v17-2-18,18>>^ E o rei deu um grande banquete, o banquete de Ester, para todos os seus nobres e oficiais. Proclamou feriado em todas as províncias e distribuiu presentes por sua generosidade real.

[[v17-2-19]]

^<<v17-2-19,19>>^ Quando as virgens foram reunidas pela segunda vez, Mardoqueu estava sentado junto à porta do palácio real.

[[v17-2-20]]

^<<v17-2-20,20>>^ Ester havia mantido segredo sobre seu povo e sobre a origem de sua família, conforme a ordem de Mardoqueu, pois continuava a seguir as instruções de Mardoqueu, como fazia quando ainda estava sob sua tutela.

[[v17-2-21]]

^<<v17-2-21,21>>^ Um dia, quando Mardoqueu estava sentado junto à porta do palácio real, Bigtã e Teres, dois dos oficiais do rei que guardavam a entrada, estavam indignados e conspiravam para assassinar o rei Xerxes.

[[v17-2-22]]

^<<v17-2-22,22>>^ Mardoqueu, porém, descobriu o plano e contou-o à rainha Ester, que, por sua vez, passou a informação ao rei, em nome de Mardoqueu.

[[v17-2-23]]

^<<v17-2-23,23>>^ Depois de investigada a informação e descobrindo-se que era verdadeira, os dois funcionários foram enforcados. Tudo isso foi escrito nos registros históricos, na presença do rei.

'''

xref:017-ester/017-ester-001.adoc#v17-1-0[&#60; Capítulo Anterior] | <<v17-2-0,Topo>> | xref:017-ester/017-ester-003.adoc#v17-3-0[Próximo Capítulo &#62;]