include::./index.adoc[]

[[v3-4-0]]
=== Levítico, 4
// nvi ?, NVI - Nova Versão Internacional

[[v3-4-1]]

^<<v3-4-1,1>>^ O Senhor ordenou a Moisés:

[[v3-4-2]]

^<<v3-4-2,2>>^ "Diga aos israelitas: Quando alguém pecar sem intenção, fazendo o que é proibido em qualquer dos mandamentos do Senhor, assim se fará:

[[v3-4-3]]

^<<v3-4-3,3>>^ "Se for o sacerdote ungido que pecar, trazendo culpa sobre o povo, trará ao Senhor um novilho sem defeito como oferta pelo pecado que cometeu.

[[v3-4-4]]

^<<v3-4-4,4>>^ Apresentará ao Senhor o novilho na entrada da Tenda do Encontro. Porá a mão sobre a cabeça do novilho que será morto perante o Senhor.

[[v3-4-5]]

^<<v3-4-5,5>>^ Então o sacerdote ungido pegará um pouco do sangue do novilho e o levará à Tenda do Encontro;

[[v3-4-6]]

^<<v3-4-6,6>>^ molhará o dedo no sangue e o aspergirá sete vezes perante o Senhor, diante do véu do santuário.

[[v3-4-7]]

^<<v3-4-7,7>>^ O sacerdote porá um pouco do sangue nas pontas do altar do incenso aromático que está perante o Senhor na Tenda do Encontro. Derramará todo o restante do sangue do novilho na base do altar do holocausto, na entrada da Tenda do Encontro.

[[v3-4-8]]

^<<v3-4-8,8>>^ Então retirará toda a gordura do novilho da oferta pelo pecado: a gordura que cobre as vísceras e está ligada a elas,

[[v3-4-9]]

^<<v3-4-9,9>>^ os dois rins com a gordura que os cobre e que está perto dos lombos, e o lóbulo do fígado, que ele removerá junto com os rins,

[[v3-4-10]]

^<<v3-4-10,10>>^ como se retira a gordura do boi sacrificado como oferta de comunhão. Então o sacerdote os queimará no altar dos holocaustos.

[[v3-4-11]]

^<<v3-4-11,11>>^ Mas o couro do novilho e toda a sua carne, bem como a cabeça e as pernas, as vísceras e os excrementos,

[[v3-4-12]]

^<<v3-4-12,12>>^ isto é, tudo o que restar do novilho, ele os levará para fora do acampamento, a um local cerimonialmente puro, onde se lançam as cinzas. Ali os queimará sobre a lenha de uma fogueira, sobre o monte de cinzas.

[[v3-4-13]]

^<<v3-4-13,13>>^ "Se for toda a comunidade de Israel que pecar sem intenção, fazendo o que é proibido em qualquer dos mandamentos do Senhor, ainda que não tenha consciência disso, a comunidade será culpada.

[[v3-4-14]]

^<<v3-4-14,14>>^ Quando tiver consciência do pecado que cometeu, a comunidade trará um novilho como oferta pelo pecado e o apresentará diante da Tenda do Encontro.

[[v3-4-15]]

^<<v3-4-15,15>>^ As autoridades da comunidade porão as mãos sobre a cabeça do novilho perante o Senhor. E o novilho será morto perante o Senhor.

[[v3-4-16]]

^<<v3-4-16,16>>^ Então o sacerdote ungido levará um pouco do sangue do novilho para a Tenda do Encontro;

[[v3-4-17]]

^<<v3-4-17,17>>^ molhará o dedo no sangue e o aspergirá sete vezes perante o Senhor, diante do véu.

[[v3-4-18]]

^<<v3-4-18,18>>^ Porá o sangue nas pontas do altar que está perante o Senhor na Tenda do Encontro e derramará todo o restante do sangue na base do altar dos holocaustos, na entrada da Tenda do Encontro.

[[v3-4-19]]

^<<v3-4-19,19>>^ Então retirará toda a gordura do animal e a queimará no altar,

[[v3-4-20]]

^<<v3-4-20,20>>^ e fará com este novilho como fez com o novilho da oferta pelo pecado. Assim o sacerdote fará propiciação por eles, e eles serão perdoados.

[[v3-4-21]]

^<<v3-4-21,21>>^ Depois levará o novilho para fora do acampamento e o queimará como queimou o primeiro. É oferta pelo pecado da comunidade.

[[v3-4-22]]

^<<v3-4-22,22>>^ "Quando for um líder que pecar sem intenção, fazendo o que é proibido em qualquer dos mandamentos do Senhor seu Deus, será culpado.

[[v3-4-23]]

^<<v3-4-23,23>>^ Quando o conscientizarem do seu pecado, trará como oferta um bode sem defeito.

[[v3-4-24]]

^<<v3-4-24,24>>^ Porá a mão sobre a cabeça do bode, que será morto no local onde o holocausto é sacrificado, perante o Senhor. Esta é a oferta pelo pecado.

[[v3-4-25]]

^<<v3-4-25,25>>^ Então o sacerdote pegará com o dedo um pouco do sangue da oferta pelo pecado, o porá nas pontas do altar dos holocaustos e derramará o restante do sangue na base do altar do holocausto.

[[v3-4-26]]

^<<v3-4-26,26>>^ Queimará toda a gordura no altar, como queimou a gordura do sacrifício de comunhão. Assim o sacerdote fará propiciação pelo pecado do líder, e ele será perdoado.

[[v3-4-27]]

^<<v3-4-27,27>>^ "Se for alguém da comunidade que pecar sem intenção, fazendo o que é proibido em qualquer dos mandamentos do Senhor seu Deus, será culpado.

[[v3-4-28]]

^<<v3-4-28,28>>^ Quando o conscientizarem do seu pecado, trará como oferta pelo pecado que cometeu uma cabra sem defeito.

[[v3-4-29]]

^<<v3-4-29,29>>^ Porá a mão sobre a cabeça do animal da oferta pelo pecado, que será morto no lugar dos holocaustos.

[[v3-4-30]]

^<<v3-4-30,30>>^ Então o sacerdote pegará com o dedo um pouco do sangue, o porá nas pontas do altar dos holocaustos e derramará o restante do sangue na base do altar.

[[v3-4-31]]

^<<v3-4-31,31>>^ Então retirará toda a gordura, como se retira a gordura do sacrifício de comunhão; o sacerdote a queimará no altar como aroma agradável ao Senhor. Assim o sacerdote fará propiciação por esse homem, e ele será perdoado.

[[v3-4-32]]

^<<v3-4-32,32>>^ "Se trouxer uma ovelha como oferta pelo pecado, terá que ser sem defeito.

[[v3-4-33]]

^<<v3-4-33,33>>^ Porá a mão sobre a cabeça do animal, que será morto como oferta pelo pecado no lugar onde é sacrificado o holocausto.

[[v3-4-34]]

^<<v3-4-34,34>>^ Então o sacerdote pegará com o dedo um pouco do sangue da oferta pelo pecado e o porá nas pontas do altar dos holocaustos, e derramará o restante do sangue na base do altar.

[[v3-4-35]]

^<<v3-4-35,35>>^ Retirará toda a gordura, como se retira a gordura do cordeiro do sacrifício de comunhão; o sacerdote a queimará no altar, em cima das ofertas dedicadas ao Senhor, preparadas no fogo. Assim o sacerdote fará em favor dele propiciação pelo pecado que cometeu, e ele será perdoado".

'''

xref:003-levitico/003-levitico-003.adoc#v3-3-0[&#60; Capítulo Anterior] | <<v3-4-0,Topo>> | xref:003-levitico/003-levitico-005.adoc#v3-5-0[Próximo Capítulo &#62;]