include::./index.adoc[]

[[v3-25-0]]
=== Levítico, 25
// nvi ?, NVI - Nova Versão Internacional

[[v3-25-1]]

^<<v3-25-1,1>>^ Então disse o Senhor a Moisés no monte Sinai:

[[v3-25-2]]

^<<v3-25-2,2>>^ "Diga o seguinte aos israelitas: Quando vocês entrarem na terra que lhes dou, a própria terra guardará um sábado para o Senhor.

[[v3-25-3]]

^<<v3-25-3,3>>^ Durante seis anos semeiem as suas lavouras, aparem as suas vinhas e façam a colheita de suas plantações.

[[v3-25-4]]

^<<v3-25-4,4>>^ Mas no sétimo ano a terra terá um sábado de descanso, um sábado dedicado ao Senhor. Não semeiem as suas lavouras, nem aparem as suas vinhas.

[[v3-25-5]]

^<<v3-25-5,5>>^ Não colham o que crescer por si, nem colham as uvas das suas vinhas que não serão podadas. A terra terá um ano de descanso.

[[v3-25-6]]

^<<v3-25-6,6>>^ Vocês se sustentarão do que a terra produzir no ano de descanso, você, o seu escravo, a sua escrava, o trabalhador contratado e o residente temporário que vive entre vocês,

[[v3-25-7]]

^<<v3-25-7,7>>^ bem como os seus rebanhos e os animais selvagens de sua terra. Tudo o que a terra produzir poderá ser comido.

[[v3-25-8]]

^<<v3-25-8,8>>^ "Contem sete semanas de anos, sete vezes sete anos; essas sete semanas de anos totalizam quarenta e nove anos.

[[v3-25-9]]

^<<v3-25-9,9>>^ Então façam soar a trombeta no décimo dia do sétimo mês; no Dia da Expiação façam soar a trombeta por toda a terra de vocês.

[[v3-25-10]]

^<<v3-25-10,10>>^ Consagrem o qüinquagésimo ano e proclamem libertação por toda a terra a todos os seus moradores. Este lhes será um ano de jubileu, quando cada um de vocês voltará para a propriedade da sua família e para o seu próprio clã.

[[v3-25-11]]

^<<v3-25-11,11>>^ O quinquagésimo ano lhes será jubileu; não semeiem e não ceifem o que cresce por si mesmo nem colham das vinhas não podadas.

[[v3-25-12]]

^<<v3-25-12,12>>^ É jubileu, e lhes será santo; comam apenas o que a terra produzir.

[[v3-25-13]]

^<<v3-25-13,13>>^ "Nesse ano do jubileu cada um de vocês voltará para a sua propriedade.

[[v3-25-14]]

^<<v3-25-14,14>>^ "Se vocês venderem alguma propriedade ao seu próximo ou se comprarem alguma propriedade dele, não explore o seu irmão.

[[v3-25-15]]

^<<v3-25-15,15>>^ O que comprarem do seu próximo será avaliado com base no número de anos desde o Jubileu. E fará a venda com base no número de anos que restam de colheitas.

[[v3-25-16]]

^<<v3-25-16,16>>^ Quando os anos forem muitos, vocês deverão aumentar o preço, mas quando forem poucos, deverão diminuir o preço, pois o que ele está lhes vendendo é o número de colheitas.

[[v3-25-17]]

^<<v3-25-17,17>>^ Não explorem um ao outro, mas temam ao Deus de vocês. Eu sou o Senhor, o Deus de vocês.

[[v3-25-18]]

^<<v3-25-18,18>>^ "Pratiquem os meus decretos e obedeçam às minhas ordenanças, e vocês viverão com segurança na terra.

[[v3-25-19]]

^<<v3-25-19,19>>^ Então a terra dará o seu fruto, e vocês comerão até fartar-se e ali viverão em segurança.

[[v3-25-20]]

^<<v3-25-20,20>>^ Vocês poderão perguntar: ‘Que iremos comer no sétimo ano, se não plantarmos nem fizermos a colheita? ’

[[v3-25-21]]

^<<v3-25-21,21>>^ Saibam que eu lhes enviarei a minha bênção no sexto ano, e a terra produzirá o suficiente para três anos.

[[v3-25-22]]

^<<v3-25-22,22>>^ Quando vocês estiverem plantando no oitavo ano, comerão ainda da colheita anterior e dela continuarão a comer até a colheita do nono ano.

[[v3-25-23]]

^<<v3-25-23,23>>^ "A terra não poderá ser vendida definitivamente, porque ela é minha, e vocês são apenas estrangeiros e imigrantes.

[[v3-25-24]]

^<<v3-25-24,24>>^ Em toda terra em que tiverem propriedade, concedam o direito de resgate da terra.

[[v3-25-25]]

^<<v3-25-25,25>>^ "Se alguém do seu povo empobrecer e vender parte da sua propriedade, seu parente mais próximo virá e resgatará aquilo que o seu compatriota vendeu.

[[v3-25-26]]

^<<v3-25-26,26>>^ Se, contudo, um homem não tiver quem lhe resgate a terra, mas ele mesmo prosperar e adquirir recursos para resgatá-la,

[[v3-25-27]]

^<<v3-25-27,27>>^ calculará os anos desde que a vendeu e devolverá a diferença àquele a quem a vendeu; então poderá voltar para a sua propriedade.

[[v3-25-28]]

^<<v3-25-28,28>>^ Mas, se não adquirir recursos para devolver-lhe o valor, a propriedade que vendeu permanecerá em posse do comprador até o ano do jubileu. Será devolvida no Jubileu, e ele então poderá voltar para a sua propriedade.

[[v3-25-29]]

^<<v3-25-29,29>>^ "Se um homem vender uma casa numa cidade murada, terá o direito de resgate até que se complete um ano após a venda. Nesse período poderá resgatá-la.

[[v3-25-30]]

^<<v3-25-30,30>>^ Se não for resgatada antes de se completar um ano, a casa da cidade murada pertencerá definitivamente ao comprador e aos seus descendentes; não será devolvida no Jubileu.

[[v3-25-31]]

^<<v3-25-31,31>>^ Mas as casas dos povoados sem muros ao redor serão consideradas campo aberto. Poderão ser resgatadas e serão devolvidas no Jubileu.

[[v3-25-32]]

^<<v3-25-32,32>>^ "No caso das cidades dos levitas, eles sempre terão direito de resgatar suas casas nas cidades que lhes pertencem.

[[v3-25-33]]

^<<v3-25-33,33>>^ Assim, a propriedade dos levitas, isto é, uma casa vendida em qualquer cidade deles, é resgatável e deverá ser devolvida no Jubileu, porque as casas das cidades dos levitas são propriedade deles entre os israelitas.

[[v3-25-34]]

^<<v3-25-34,34>>^ Mas as pastagens pertencentes às suas cidades não serão vendidas; são propriedade permanente deles.

[[v3-25-35]]

^<<v3-25-35,35>>^ "Se alguém do seu povo empobrecer e não puder sustentar-se, ajudem-no como se faz ao estrangeiro e ao residente temporário, para que possa continuar a viver entre vocês.

[[v3-25-36]]

^<<v3-25-36,36>>^ Não cobrem dele juro algum, mas temam o seu Deus, para que o seu próximo continue a viver entre vocês.

[[v3-25-37]]

^<<v3-25-37,37>>^ Vocês não poderão exigir dele juros nem emprestar-lhe mantimento visando lucro.

[[v3-25-38]]

^<<v3-25-38,38>>^ Eu sou o Senhor, o Deus de vocês, que os tirou da terra do Egito para dar-lhes a terra de Canaã e para ser o seu Deus.

[[v3-25-39]]

^<<v3-25-39,39>>^ "Se alguém do seu povo empobrecer e se vender a algum de vocês, não o façam trabalhar como escravo.

[[v3-25-40]]

^<<v3-25-40,40>>^ Ele deverá ser tratado como trabalhador contratado ou como residente temporário; trabalhará para quem o comprou até o ano do jubileu.

[[v3-25-41]]

^<<v3-25-41,41>>^ Então ele e os seus filhos estarão livres, e ele poderá voltar para o seu próprio clã e para a propriedade dos seus antepassados.

[[v3-25-42]]

^<<v3-25-42,42>>^ Pois os israelitas são meus servos, a quem tirei da terra do Egito; não poderão ser vendidos como escravos.

[[v3-25-43]]

^<<v3-25-43,43>>^ Não dominem impiedosamente sobre eles, mas temam o seu Deus.

[[v3-25-44]]

^<<v3-25-44,44>>^ "Os seus escravos e as suas escravas deverão vir dos povos que vivem ao redor de vocês; deles vocês poderão comprar escravos e escravas.

[[v3-25-45]]

^<<v3-25-45,45>>^ Também poderão comprá-los entre os filhos dos residentes temporários que vivem entre vocês e entre os que pertencem aos clãs deles, ainda que nascidos na terra de vocês; eles se tornarão propriedade de vocês.

[[v3-25-46]]

^<<v3-25-46,46>>^ Vocês poderão deixá-los como herança para os seus filhos e poderão fazê-los escravos para sempre, mas sobre os seus irmãos israelitas vocês não poderão dominar impiedosamente.

[[v3-25-47]]

^<<v3-25-47,47>>^ "Se um estrangeiro ou um residente temporário entre vocês enriquecer e alguém do seu povo empobrecer e se vender a esse estrangeiro ou a alguém que pertence ao clã desse estrangeiro,

[[v3-25-48]]

^<<v3-25-48,48>>^ manterá o direito de resgate mesmo depois de vender a si mesmo. Um dos seus parentes poderá resgatá-lo:

[[v3-25-49]]

^<<v3-25-49,49>>^ ou tio, ou primo, ou qualquer parente próximo poderá resgatá-lo. Se, todavia, prosperar, poderá resgatar a si mesmo.

[[v3-25-50]]

^<<v3-25-50,50>>^ Ele e o seu comprador contarão o tempo desde o ano em que vendeu a si mesmo até o ano do jubileu. O preço do resgate se baseará no salário de um empregado contratado por aquele número de anos.

[[v3-25-51]]

^<<v3-25-51,51>>^ Se restarem muitos anos, pagará o seu resgate proporcionalmente ao preço de compra.

[[v3-25-52]]

^<<v3-25-52,52>>^ Se restarem apenas poucos anos até o ano do jubileu, fará o cálculo, e pagará o seu resgate proporcionalmente aos anos.

[[v3-25-53]]

^<<v3-25-53,53>>^ Ele deverá ser tratado como um empregado contratado anualmente; não permitam que o seu senhor domine impiedosamente sobre ele.

[[v3-25-54]]

^<<v3-25-54,54>>^ "Se não for resgatado por nenhuma dessas maneiras, ele e os seus filhos estarão livres no ano do jubileu,

[[v3-25-55]]

^<<v3-25-55,55>>^ porque os israelitas são meus servos, os quais tirei da terra do Egito. Eu sou o Senhor, o Deus de vocês".

'''

xref:003-levitico/003-levitico-024.adoc#v3-24-0[&#60; Capítulo Anterior] | <<v3-25-0,Topo>> | xref:003-levitico/003-levitico-026.adoc#v3-26-0[Próximo Capítulo &#62;]