include::./index.adoc[]

[[v3-26-0]]
=== Levítico, 26
// nvi ?, NVI - Nova Versão Internacional

[[v3-26-1]]

^<<v3-26-1,1>>^ "Não façam ídolos, nem imagens, nem colunas sagradas para vocês, e não coloquem nenhuma pedra esculpida em sua terra para curvar-se diante dela. Eu sou o Senhor, o Deus de vocês.

[[v3-26-2]]

^<<v3-26-2,2>>^ "Guardem os meus sábados e reverenciem o meu santuário. Eu sou o Senhor.

[[v3-26-3]]

^<<v3-26-3,3>>^ "Se vocês seguirem os meus decretos e obedecerem aos meus mandamentos, e os colocarem em prática,

[[v3-26-4]]

^<<v3-26-4,4>>^ eu lhes mandarei chuva na estação certa, e a terra dará a sua colheita e as árvores do campo darão o seu fruto.

[[v3-26-5]]

^<<v3-26-5,5>>^ A debulha prosseguirá até a colheita das uvas, e a colheita das uvas prosseguirá até a época da plantação, e vocês comerão até ficarem satisfeitos e viverão em segurança na terra de vocês.

[[v3-26-6]]

^<<v3-26-6,6>>^ "Estabelecerei paz na terra, e vocês se deitarão, e ninguém os amedrontará. Farei desaparecer da terra os animais selvagens, e a espada não passará pela terra de vocês.

[[v3-26-7]]

^<<v3-26-7,7>>^ Vocês perseguirão os seus inimigos, e estes cairão à espada diante de vocês.

[[v3-26-8]]

^<<v3-26-8,8>>^ Cinco de vocês perseguirão cem, cem de vocês perseguirão dez mil, e os seus inimigos cairão à espada diante de vocês.

[[v3-26-9]]

^<<v3-26-9,9>>^ "Eu me voltarei para vocês e os farei prolíferos; e os multiplicarei e guardarei a minha aliança com vocês.

[[v3-26-10]]

^<<v3-26-10,10>>^ Vocês ainda estarão comendo da colheita armazenada no ano anterior, quando terão que se livrar dela para dar espaço para a nova colheita.

[[v3-26-11]]

^<<v3-26-11,11>>^ Estabelecerei a minha habitação entre vocês e não os rejeitarei.

[[v3-26-12]]

^<<v3-26-12,12>>^ Andarei entre vocês e serei o seu Deus, e vocês serão o meu povo.

[[v3-26-13]]

^<<v3-26-13,13>>^ Eu sou o Senhor, o Deus de vocês, que os tirou da terra do Egito para que não mais fossem escravos deles; quebrei as traves do jugo que os prendia e os fiz andar de cabeça erguida. "

[[v3-26-14]]

^<<v3-26-14,14>>^ "Mas, se vocês não me ouvirem e não colocarem em prática todos esses mandamentos,

[[v3-26-15]]

^<<v3-26-15,15>>^ e desprezarem os meus decretos, rejeitarem as minhas ordenanças, deixarem de colocar em prática todos os meus mandamentos e forem infiéis à minha aliança,

[[v3-26-16]]

^<<v3-26-16,16>>^ então assim os tratarei: eu lhes trarei pavor repentino, doenças e febre que tirarão a visão e lhes definharão a vida. Vocês semearão inutilmente, porque os seus inimigos comerão as suas sementes.

[[v3-26-17]]

^<<v3-26-17,17>>^ O meu rosto estará contra vocês, e vocês serão derrotados pelos inimigos; os seus adversários os dominarão, e vocês fugirão mesmo quando ninguém os estiver perseguindo.

[[v3-26-18]]

^<<v3-26-18,18>>^ "Se depois disso tudo vocês não me ouvirem, eu os castigarei sete vezes mais pelos seus pecados.

[[v3-26-19]]

^<<v3-26-19,19>>^ Eu lhes quebrarei o orgulho rebelde e farei que o céu sobre vocês fique como ferro e a terra de vocês fique como bronze.

[[v3-26-20]]

^<<v3-26-20,20>>^ A força de vocês será gasta em vão, porque a terra não lhes dará colheita, nem as árvores da terra lhes darão fruto.

[[v3-26-21]]

^<<v3-26-21,21>>^ "Se continuarem se opondo a mim e recusarem ouvir-me, eu os castigarei sete vezes mais, conforme os seus pecados.

[[v3-26-22]]

^<<v3-26-22,22>>^ Mandarei contra vocês animais selvagens que matarão os seus filhos, acabarei com os seus rebanhos e reduzirei vocês a tão poucos que os seus caminhos ficarão desertos.

[[v3-26-23]]

^<<v3-26-23,23>>^ "Se apesar disso vocês não aceitarem a minha disciplina, mas continuarem a opor-se a mim,

[[v3-26-24]]

^<<v3-26-24,24>>^ eu mesmo me oporei a vocês e os castigarei sete vezes mais por causa dos seus pecados.

[[v3-26-25]]

^<<v3-26-25,25>>^ E trarei a espada contra vocês para vingar a aliança. Quando se refugiarem em suas cidades, eu lhes mandarei uma praga, e vocês serão entregues em mãos inimigas.

[[v3-26-26]]

^<<v3-26-26,26>>^ Quando eu lhes cortar o suprimento de pão, dez mulheres assarão o pão num único forno e repartirão o pão a peso. Vocês comerão, mas não ficarão satisfeitos.

[[v3-26-27]]

^<<v3-26-27,27>>^ "Se apesar disso tudo vocês ainda não me ouvirem, mas continuarem a opor-se a mim,

[[v3-26-28]]

^<<v3-26-28,28>>^ então com furor me oporei a vocês, e eu mesmo os castigarei sete vezes mais por causa dos seus pecados.

[[v3-26-29]]

^<<v3-26-29,29>>^ Vocês comerão a carne dos seus filhos e das suas filhas.

[[v3-26-30]]

^<<v3-26-30,30>>^ Destruirei os seus altares idólatras, despedaçarei os seus altares de incenso e empilharei os seus cadáveres sobre os seus ídolos mortos, e rejeitarei vocês.

[[v3-26-31]]

^<<v3-26-31,31>>^ Deixarei as cidades de vocês em ruínas e arrasarei os seus santuários, e não terei prazer no aroma das suas ofertas.

[[v3-26-32]]

^<<v3-26-32,32>>^ Desolarei a terra a ponto de ficarem perplexos os seus inimigos que vierem ocupá-la.

[[v3-26-33]]

^<<v3-26-33,33>>^ Espalharei vocês entre as nações e desembainharei a espada contra vocês. Sua terra ficará desolada, e as suas cidades, em ruínas.

[[v3-26-34]]

^<<v3-26-34,34>>^ Então a terra desfrutará os seus anos sabáticos enquanto estiver desolada e enquanto vocês estiverem na terra dos seus inimigos; e a terra descansará e desfrutará os seus sábados.

[[v3-26-35]]

^<<v3-26-35,35>>^ Enquanto estiver desolada, a terra terá o descanso sabático que não teve quando vocês a habitaram.

[[v3-26-36]]

^<<v3-26-36,36>>^ "Quanto aos que sobreviverem, eu lhes encherei o coração de tanto medo na terra do inimigo, que o som de uma folha levada pelo vento os porá em fuga. Correrão como quem foge da espada, e cairão, sem que ninguém os persiga.

[[v3-26-37]]

^<<v3-26-37,37>>^ Tropeçarão uns nos outros, como que fugindo da espada, sem que ninguém os esteja perseguindo. Assim vocês não poderão subsistir diante dos inimigos.

[[v3-26-38]]

^<<v3-26-38,38>>^ Vocês perecerão entre as nações, e a terra dos seus inimigos os devorará.

[[v3-26-39]]

^<<v3-26-39,39>>^ Os que sobreviverem apodrecerão na terra do inimigo por causa dos seus pecados, e também por causa dos pecados dos seus antepassados.

[[v3-26-40]]

^<<v3-26-40,40>>^ "Mas, se confessarem os seus pecados e os pecados dos seus antepassados, sua infidelidade e oposição a mim,

[[v3-26-41]]

^<<v3-26-41,41>>^ que me levaram a opor-me a eles e a enviá-los para a terra dos seus inimigos; se o seu coração obstinado se humilhar, e eles aceitarem o castigo do seu pecado,

[[v3-26-42]]

^<<v3-26-42,42>>^ eu me lembrarei da minha aliança com Jacó e da minha aliança com Isaque e da minha aliança com Abraão, e também me lembrarei da terra,

[[v3-26-43]]

^<<v3-26-43,43>>^ que por eles será abandonada e desfrutará os seus sábados enquanto permanecer desolada. Receberão o castigo pelos seus pecados porque desprezaram as minhas ordenanças e rejeitaram os meus decretos.

[[v3-26-44]]

^<<v3-26-44,44>>^ Apesar disso, quando estiverem na terra do inimigo, não os desprezarei, nem os rejeitarei, para destruí-los totalmente, quebrando a minha aliança com eles, pois eu sou o Senhor, o Deus deles.

[[v3-26-45]]

^<<v3-26-45,45>>^ Mas por amor deles eu me lembrarei da aliança com os seus antepassados que tirei da terra do Egito à vista das nações, para ser o Deus deles. Eu sou o Senhor. "

[[v3-26-46]]

^<<v3-26-46,46>>^ São esses os decretos, as ordenanças e as leis que o Senhor estabeleceu no monte Sinai entre ele próprio e os israelitas, por intermédio de Moisés.

'''

xref:003-levitico/003-levitico-025.adoc#v3-25-0[&#60; Capítulo Anterior] | <<v3-26-0,Topo>> | xref:003-levitico/003-levitico-027.adoc#v3-27-0[Próximo Capítulo &#62;]