include::./index.adoc[]

[[v3-12-0]]
=== Levítico, 12
// nvi ?, NVI - Nova Versão Internacional

[[v3-12-1]]

^<<v3-12-1,1>>^ Disse o Senhor a Moisés:

[[v3-12-2]]

^<<v3-12-2,2>>^ "Diga aos israelitas: Quando uma mulher engravidar e der à luz um menino, estará impura por sete dias, assim como está impura durante o seu período menstrual.

[[v3-12-3]]

^<<v3-12-3,3>>^ No oitavo dia o menino terá que ser circuncidado.

[[v3-12-4]]

^<<v3-12-4,4>>^ Então a mulher aguardará trinta e três dias para ser purificada do seu sangramento. Não poderá tocar em nenhuma coisa sagrada e não poderá ir ao santuário, até que se completem os dias da sua purificação.

[[v3-12-5]]

^<<v3-12-5,5>>^ Se der à luz uma menina, estará impura por duas semanas, como durante o seu período menstrual. Nesse caso aguardará sessenta e seis dias para ser purificada do seu sangramento.

[[v3-12-6]]

^<<v3-12-6,6>>^ "Quando se completarem os dias da sua purificação pelo nascimento de um menino ou de uma menina, ela trará ao sacerdote, à entrada da Tenda do Encontro, um cordeiro de um ano para o holocausto e um pombinho ou uma rolinha como oferta pelo pecado.

[[v3-12-7]]

^<<v3-12-7,7>>^ Ele os oferecerá ao Senhor para fazer propiciação por ela, que ficará pura do fluxo do seu sangramento. Essa é a regulamentação para a mulher que der à luz um menino ou uma menina.

[[v3-12-8]]

^<<v3-12-8,8>>^ Se ela não tiver recursos para oferecer um cordeiro, poderá trazer duas rolinhas ou dois pombinhos, um para o holocausto e o outro para a oferta pelo pecado. Assim o sacerdote fará propiciação por ela, e ela ficará pura".

'''

xref:003-levitico/003-levitico-011.adoc#v3-11-0[&#60; Capítulo Anterior] | <<v3-12-0,Topo>> | xref:003-levitico/003-levitico-013.adoc#v3-13-0[Próximo Capítulo &#62;]