include::./index.adoc[]

[[v3-23-0]]
=== Levítico, 23
// nvi ?, NVI - Nova Versão Internacional

[[v3-23-1]]

^<<v3-23-1,1>>^ Disse o Senhor a Moisés:

[[v3-23-2]]

^<<v3-23-2,2>>^ "Diga o seguinte aos israelitas: Estas são as minhas festas, as festas fixas do Senhor, que vocês proclamarão como reuniões sagradas:

[[v3-23-3]]

^<<v3-23-3,3>>^ "Em seis dias realize os seus trabalhos, mas o sétimo dia é sábado, dia de descanso e de reunião sagrada. Não realizem trabalho algum; onde quer que morarem, será sábado dedicado ao Senhor.

[[v3-23-4]]

^<<v3-23-4,4>>^ "Estas são as festas fixas do Senhor, as reuniões sagradas que vocês proclamarão no tempo devido:

[[v3-23-5]]

^<<v3-23-5,5>>^ A páscoa do Senhor começa no entardecer do décimo quarto dia do primeiro mês.

[[v3-23-6]]

^<<v3-23-6,6>>^ No décimo quinto dia daquele mês começa a festa do Senhor, a festa dos pães sem fermento; durante sete dias vocês comerão pães sem fermento.

[[v3-23-7]]

^<<v3-23-7,7>>^ No primeiro dia façam uma reunião sagrada e não realizem trabalho algum.

[[v3-23-8]]

^<<v3-23-8,8>>^ Durante sete dias apresentem ao Senhor ofertas preparadas no fogo. E no sétimo dia façam uma reunião sagrada e não realizem trabalho algum".

[[v3-23-9]]

^<<v3-23-9,9>>^ Disse o Senhor a Moisés:

[[v3-23-10]]

^<<v3-23-10,10>>^ "Diga o seguinte aos israelitas: Quando vocês entrarem na terra que lhes dou e fizerem colheita, tragam ao sacerdote um feixe do primeiro cereal que colherem.

[[v3-23-11]]

^<<v3-23-11,11>>^ O sacerdote moverá ritualmente o feixe perante o Senhor para que seja aceito em favor de vocês; ele o moverá no dia seguinte ao sábado.

[[v3-23-12]]

^<<v3-23-12,12>>^ No dia em que moverem o feixe, vocês oferecerão em holocausto ao Senhor um cordeiro de um ano de idade e sem defeito.

[[v3-23-13]]

^<<v3-23-13,13>>^ Apresentem também uma oferta de cereal de dois jarros da melhor farinha amassada com óleo, oferta ao Senhor preparada no fogo, de aroma agradável, e uma oferta derramada de um litro de vinho.

[[v3-23-14]]

^<<v3-23-14,14>>^ Vocês não poderão comer pão algum, nem cereal tostado, nem cereal novo, até o dia em que trouxerem essa oferta ao Deus de vocês. Este é um decreto perpétuo para as suas gerações, onde quer que morarem.

[[v3-23-15]]

^<<v3-23-15,15>>^ "A partir do dia seguinte ao sábado, o dia em que vocês trarão o feixe da oferta ritualmente movida, contem sete semanas completas.

[[v3-23-16]]

^<<v3-23-16,16>>^ Contem cinqüenta dias, até um dia depois do sétimo sábado, e então apresentem uma oferta de cereal novo ao Senhor.

[[v3-23-17]]

^<<v3-23-17,17>>^ Onde quer que morarem, tragam de casa dois pães feitos com dois jarros da melhor farinha, cozidos com fermento, como oferta movida dos primeiros frutos ao Senhor.

[[v3-23-18]]

^<<v3-23-18,18>>^ Junto com os pães apresentem sete cordeiros, cada um com um ano de idade e sem defeito, um novilho e dois carneiros. Eles serão holocausto ao Senhor, juntamente com as suas ofertas de cereal e ofertas derramadas; é oferta preparada no fogo, de aroma agradável ao Senhor.

[[v3-23-19]]

^<<v3-23-19,19>>^ Depois sacrifiquem um bode como oferta pelo pecado e dois cordeiros, cada um com um ano de idade, como oferta de comunhão.

[[v3-23-20]]

^<<v3-23-20,20>>^ O sacerdote moverá os dois cordeiros perante o Senhor como gesto ritual de apresentação, juntamente com o pão dos primeiros frutos. São uma oferta sagrada ao Senhor que pertencem ao sacerdote.

[[v3-23-21]]

^<<v3-23-21,21>>^ Naquele mesmo dia vocês proclamarão uma reunião sagrada e não realizarão trabalho algum. Este é um decreto perpétuo para as suas gerações, onde quer que vocês morarem.

[[v3-23-22]]

^<<v3-23-22,22>>^ "Quando fizerem a colheita da sua terra, não colham até às extremidades da sua lavoura, nem ajuntem as espigas caídas da sua colheita. Deixem-nas para o necessitado e para o estrangeiro. Eu sou o Senhor, o Deus de vocês".

[[v3-23-23]]

^<<v3-23-23,23>>^ Disse o Senhor a Moisés:

[[v3-23-24]]

^<<v3-23-24,24>>^ "Diga também aos israelitas: No dia primeiro do sétimo mês vocês terão um dia de descanso, uma reunião sagrada, comemorada com toques de trombeta.

[[v3-23-25]]

^<<v3-23-25,25>>^ Não realizem trabalho algum, mas apresentem ao Senhor uma oferta preparada no fogo".

[[v3-23-26]]

^<<v3-23-26,26>>^ Disse o Senhor a Moisés:

[[v3-23-27]]

^<<v3-23-27,27>>^ "O décimo dia deste sétimo mês é o Dia da Expiação. Façam uma reunião sagrada e humilhem-se, e apresentem ao Senhor uma oferta preparada no fogo.

[[v3-23-28]]

^<<v3-23-28,28>>^ Não realizem trabalho algum nesse dia, porque é o Dia da Expiação, quando se faz propiciação por vocês perante o Senhor, o Deus de vocês.

[[v3-23-29]]

^<<v3-23-29,29>>^ Quem não se humilhar nesse dia será eliminado do seu povo.

[[v3-23-30]]

^<<v3-23-30,30>>^ Eu destruirei do meio do seu povo todo aquele que realizar algum trabalho nesse dia.

[[v3-23-31]]

^<<v3-23-31,31>>^ Vocês não realizarão trabalho algum. Este é um decreto perpétuo para as suas gerações, onde quer que vocês morarem.

[[v3-23-32]]

^<<v3-23-32,32>>^ É um sábado de descanso para vocês, e vocês se humilharão. Desde o entardecer do nono dia do mês até ao entardecer do dia seguinte vocês guardarão esse sábado".

[[v3-23-33]]

^<<v3-23-33,33>>^ Disse o Senhor a Moisés:

[[v3-23-34]]

^<<v3-23-34,34>>^ "Diga ainda aos israelitas: No décimo quinto dia deste sétimo mês começa a Festa das Cabanas do Senhor, que dura sete dias.

[[v3-23-35]]

^<<v3-23-35,35>>^ No primeiro dia haverá reunião sagrada; não realizem trabalho algum.

[[v3-23-36]]

^<<v3-23-36,36>>^ Durante sete dias apresentem ao Senhor ofertas preparadas no fogo, e no oitavo dia façam outra reunião sagrada, e também apresentem ao Senhor uma oferta preparada no fogo. É reunião solene; não realizem trabalho algum.

[[v3-23-37]]

^<<v3-23-37,37>>^ ( Estas são as festas fixas do Senhor, que vocês proclamarão como reuniões sagradas para trazerem ao Senhor ofertas preparadas no fogo, holocaustos e ofertas de cereal, sacrifícios e ofertas derramadas exigidas para cada dia.

[[v3-23-38]]

^<<v3-23-38,38>>^ Isso fora as do sábado do Senhor e fora as dádivas e votos de vocês, e todas as ofertas voluntárias que vocês derem ao Senhor. )

[[v3-23-39]]

^<<v3-23-39,39>>^ "Assim, começando no décimo quinto dia do sétimo mês, depois de terem colhido o que a terra produziu, comemorem a festa do Senhor durante sete dias; o primeiro dia e também o oitavo serão dias de descanso.

[[v3-23-40]]

^<<v3-23-40,40>>^ No primeiro dia vocês apanharão os melhores frutos das árvores, folhagem de tamareira, galhos frondosos e salgueiros, e se alegrarão perante o Senhor, o Deus de vocês, durante sete dias.

[[v3-23-41]]

^<<v3-23-41,41>>^ Comemorem essa festa do Senhor durante sete dias todos os anos. Este é um decreto perpétuo para as suas gerações; comemorem-na no sétimo mês.

[[v3-23-42]]

^<<v3-23-42,42>>^ Morem em tendas durante sete dias; todos os israelitas de nascimento morarão em tendas,

[[v3-23-43]]

^<<v3-23-43,43>>^ para que os descendentes de vocês saibam que eu fiz os israelitas morarem em tendas quando os tirei da terra do Egito. Eu sou o Senhor, o Deus de vocês".

[[v3-23-44]]

^<<v3-23-44,44>>^ Assim anunciou Moisés aos israelitas as festas fixas do Senhor.

'''

xref:003-levitico/003-levitico-022.adoc#v3-22-0[&#60; Capítulo Anterior] | <<v3-23-0,Topo>> | xref:003-levitico/003-levitico-024.adoc#v3-24-0[Próximo Capítulo &#62;]