include::./index.adoc[]

[[v3-18-0]]
=== Levítico, 18
// nvi ?, NVI - Nova Versão Internacional

[[v3-18-1]]

^<<v3-18-1,1>>^ Disse o Senhor a Moisés:

[[v3-18-2]]

^<<v3-18-2,2>>^ "Diga o seguinte aos israelitas: Eu sou o Senhor, o Deus de vocês.

[[v3-18-3]]

^<<v3-18-3,3>>^ Não procedam como se procede no Egito, onde vocês moraram, nem como se procede na terra de Canaã, para onde os estou levando. Não sigam as suas práticas.

[[v3-18-4]]

^<<v3-18-4,4>>^ Pratiquem as minhas ordenanças, obedeçam aos meus decretos e sigam-nos. Eu sou o Senhor, o Deus de vocês.

[[v3-18-5]]

^<<v3-18-5,5>>^ Obedeçam aos meus decretos e ordenanças, pois o homem que os praticar viverá por eles. Eu sou o Senhor.

[[v3-18-6]]

^<<v3-18-6,6>>^ "Ninguém poderá se aproximar de uma parenta próxima para se envolver sexualmente com ela. Eu sou o Senhor.

[[v3-18-7]]

^<<v3-18-7,7>>^ "Não desonre o seu pai, envolvendo-se sexualmente com a sua mãe. Ela é sua mãe; não se envolva sexualmente com ela.

[[v3-18-8]]

^<<v3-18-8,8>>^ "Não se envolva sexualmente com a mulher do seu pai; isso desonraria seu pai.

[[v3-18-9]]

^<<v3-18-9,9>>^ "Não se envolva sexualmente com a sua irmã, filha do seu pai ou da sua mãe, tenha ela nascido na mesma casa ou em outro lugar.

[[v3-18-10]]

^<<v3-18-10,10>>^ "Não se envolva sexualmente com a filha do seu filho ou com a filha da sua filha; isso desonraria você.

[[v3-18-11]]

^<<v3-18-11,11>>^ "Não se envolva sexualmente com a filha da mulher do seu pai, gerada por seu pai; ela é sua irmã.

[[v3-18-12]]

^<<v3-18-12,12>>^ "Não se envolva sexualmente com a irmã do seu pai; ela é parenta próxima do seu pai.

[[v3-18-13]]

^<<v3-18-13,13>>^ "Não se envolva sexualmente com a irmã da sua mãe; ela é parenta próxima da sua mãe.

[[v3-18-14]]

^<<v3-18-14,14>>^ "Não desonre o irmão do seu pai aproximando-se da sua mulher para com ela se envolver sexualmente; ela é sua tia.

[[v3-18-15]]

^<<v3-18-15,15>>^ "Não se envolva sexualmente com a sua nora. Ela é mulher do seu filho; não se envolva sexualmente com ela.

[[v3-18-16]]

^<<v3-18-16,16>>^ "Não se envolva sexualmente com a mulher do seu irmão; isso desonraria seu irmão.

[[v3-18-17]]

^<<v3-18-17,17>>^ "Não se envolva sexualmente com uma mulher e sua filha. Não se envolva sexualmente com a filha do seu filho ou com a filha da sua filha; são parentes próximos. É perversidade.

[[v3-18-18]]

^<<v3-18-18,18>>^ "Não tome por mulher a irmã da sua mulher, tornando-a rival, envolvendo-se sexualmente com ela, estando a sua mulher ainda viva.

[[v3-18-19]]

^<<v3-18-19,19>>^ "Não se aproxime de uma mulher para se envolver sexualmente com ela quando ela estiver na impureza da sua menstruação.

[[v3-18-20]]

^<<v3-18-20,20>>^ "Não se deite com a mulher do seu próximo, contaminando-se com ela.

[[v3-18-21]]

^<<v3-18-21,21>>^ "Não entregue os seus filhos para serem sacrificados a Moloque. Não profanem o nome do seu Deus. Eu sou o Senhor.

[[v3-18-22]]

^<<v3-18-22,22>>^ "Não se deite com um homem como quem se deita com uma mulher; é repugnante.

[[v3-18-23]]

^<<v3-18-23,23>>^ "Não tenha relações sexuais com um animal, contaminando-se com ele. Mulher nenhuma se porá diante de um animal para ajuntar-se com ele; é depravação.

[[v3-18-24]]

^<<v3-18-24,24>>^ "Não se contaminem com nenhuma dessas coisas, porque assim se contaminaram as nações que vou expulsar da presença de vocês.

[[v3-18-25]]

^<<v3-18-25,25>>^ Até a terra ficou contaminada; e eu castiguei a sua iniqüidade, e a terra vomitou os seus habitantes.

[[v3-18-26]]

^<<v3-18-26,26>>^ Mas vocês obedecerão aos meus decretos e às minhas leis. Nem o natural da terra nem o estrangeiro residente entre vocês farão nenhuma dessas abominações,

[[v3-18-27]]

^<<v3-18-27,27>>^ pois todas estas abominações foram praticadas pelos que habitaram essa terra antes de vocês; por isso a terra ficou contaminada.

[[v3-18-28]]

^<<v3-18-28,28>>^ E, se vocês contaminarem a terra, ela os vomitará, como vomitou os povos que ali estavam antes de vocês.

[[v3-18-29]]

^<<v3-18-29,29>>^ "Todo aquele que fizer alguma destas abominações, aqueles que assim procederem serão eliminados do meio do seu povo.

[[v3-18-30]]

^<<v3-18-30,30>>^ Obedeçam aos meus preceitos, e não pratiquem os costumes repugnantes praticados antes de vocês, nem se contaminem com eles. Eu sou o Senhor, o Deus de vocês".

'''

xref:003-levitico/003-levitico-017.adoc#v3-17-0[&#60; Capítulo Anterior] | <<v3-18-0,Topo>> | xref:003-levitico/003-levitico-019.adoc#v3-19-0[Próximo Capítulo &#62;]