include::./index.adoc[]

[[v3-1-0]]
=== Levítico, 1
// nvi ?, NVI - Nova Versão Internacional

[[v3-1-1]]

^<<v3-1-1,1>>^ Da Tenda do Encontro o Senhor chamou Moisés e lhe ordenou:

[[v3-1-2]]

^<<v3-1-2,2>>^ "Diga o seguinte aos israelitas: Quando alguém trouxer um animal como oferta ao Senhor, que seja do gado ou do rebanho de ovelhas.

[[v3-1-3]]

^<<v3-1-3,3>>^ "Se o holocausto for de gado, oferecerá um macho sem defeito. Ele o apresentará à entrada da Tenda do Encontro para que seja aceito pelo Senhor,

[[v3-1-4]]

^<<v3-1-4,4>>^ e porá a mão sobre a cabeça do animal do holocausto para que seja aceito como propiciação em seu lugar.

[[v3-1-5]]

^<<v3-1-5,5>>^ Então o novilho será morto perante o Senhor, e os sacerdotes, descendentes de Arão, trarão o sangue e o derramarão nos lados do altar, que está na entrada da Tenda do Encontro.

[[v3-1-6]]

^<<v3-1-6,6>>^ Depois se tirará a pele do animal, que será cortado em pedaços.

[[v3-1-7]]

^<<v3-1-7,7>>^ Então os descendentes do sacerdote Arão acenderão o fogo do altar e arrumarão a lenha sobre o fogo.

[[v3-1-8]]

^<<v3-1-8,8>>^ Em seguida arrumarão os pedaços, inclusive a cabeça e a gordura, sobre a lenha que está no fogo do altar.

[[v3-1-9]]

^<<v3-1-9,9>>^ As vísceras e as pernas serão lavadas com água. E o sacerdote queimará tudo isso no altar. É um holocausto, oferta preparada no fogo, de aroma agradável ao Senhor.

[[v3-1-10]]

^<<v3-1-10,10>>^ "Se a oferta for um holocausto do rebanho, quer de cordeiros quer de cabritos, oferecerá um macho sem defeito.

[[v3-1-11]]

^<<v3-1-11,11>>^ O animal será morto no lado norte do altar, perante o Senhor; os sacerdotes, descendentes de Arão, derramarão o sangue nos lados do altar.

[[v3-1-12]]

^<<v3-1-12,12>>^ Então o animal será cortado em pedaços. O sacerdote arrumará os pedaços, inclusive a cabeça e a gordura, sobre a lenha que está no fogo do altar.

[[v3-1-13]]

^<<v3-1-13,13>>^ As vísceras e as pernas serão lavadas com água. O sacerdote trará tudo isso como oferta e o queimará no altar. É um holocausto, oferta preparada no fogo, de aroma agradável ao Senhor.

[[v3-1-14]]

^<<v3-1-14,14>>^ "Se a sua oferta ao Senhor for um holocausto de aves, traga uma rolinha ou um pombinho.

[[v3-1-15]]

^<<v3-1-15,15>>^ O sacerdote trará a ave ao altar, destroncará o pescoço dela e a queimará, e deixará escorrer o sangue da ave na parede do altar.

[[v3-1-16]]

^<<v3-1-16,16>>^ Ele retirará o papo com o seu conteúdo e o jogará ao lado leste do altar, onde ficam as cinzas.

[[v3-1-17]]

^<<v3-1-17,17>>^ Rasgará a ave pelas asas, sem dividi-la totalmente, e então o sacerdote a queimará sobre a lenha acesa no altar. É um holocausto, oferta preparada no fogo, de aroma agradável ao Senhor".

'''

xref:002-exodo/002-exodo-040.adoc#v2-40-0[&#60; Capítulo Anterior] | <<v3-1-0,Topo>> | xref:003-levitico/003-levitico-002.adoc#v3-2-0[Próximo Capítulo &#62;]