include::./index.adoc[]

[[v3-13-0]]
=== Levítico, 13
// nvi ?, NVI - Nova Versão Internacional

[[v3-13-1]]

^<<v3-13-1,1>>^ Disse o Senhor a Moisés e a Arão:

[[v3-13-2]]

^<<v3-13-2,2>>^ "Quando alguém tiver um inchaço, uma erupção ou uma mancha brilhante na pele que possa ser sinal de lepra, será levado ao sacerdote Arão ou a um dos seus filhos que seja sacerdote.

[[v3-13-3]]

^<<v3-13-3,3>>^ Este examinará a parte afetada da pele, e, se naquela parte o pêlo tiver se tornado branco e o lugar parecer mais profundo do que a pele, é sinal de lepra. Depois de examiná-lo, o sacerdote o declarará impuro.

[[v3-13-4]]

^<<v3-13-4,4>>^ Se a mancha na pele for branca, mas não parecer mais profunda do que a pele e sobre ela o pêlo não tiver se tornado branco, o sacerdote o porá em isolamento por sete dias.

[[v3-13-5]]

^<<v3-13-5,5>>^ No sétimo dia o sacerdote o examinará, e, se verificar que a parte afetada não se alterou nem se espalhou pela pele, o manterá em isolamento por mais sete dias.

[[v3-13-6]]

^<<v3-13-6,6>>^ Ao sétimo dia o sacerdote o examinará de novo, e, se a parte afetada diminuiu e não se espalhou pela pele, o sacerdote o declarará puro; é apenas uma erupção. Então ele lavará as suas roupas, e estará puro.

[[v3-13-7]]

^<<v3-13-7,7>>^ Mas, se depois que se apresentou ao sacerdote para ser declarado puro a erupção se espalhar pela pele, ele terá que se apresentar novamente ao sacerdote.

[[v3-13-8]]

^<<v3-13-8,8>>^ O sacerdote o examinará, e, se a erupção espalhou-se pela pele, ele o declarará impuro; trata-se de lepra.

[[v3-13-9]]

^<<v3-13-9,9>>^ "Quando alguém apresentar sinal de lepra, será levado ao sacerdote.

[[v3-13-10]]

^<<v3-13-10,10>>^ Este o examinará, e, se houver inchaço branco na pele, o qual tornou branco o pêlo, e se houver carne viva no inchaço,

[[v3-13-11]]

^<<v3-13-11,11>>^ é lepra crônica na pele, e o sacerdote o declarará impuro. Não o porá em isolamento, porquanto já está impuro.

[[v3-13-12]]

^<<v3-13-12,12>>^ "Se a doença se alastrar por toda a pele e cobrir toda a pele da pessoa infectada, da cabeça aos pés, até onde é possível ao sacerdote verificar,

[[v3-13-13]]

^<<v3-13-13,13>>^ este o examinará e, se observar que a lepra cobriu todo o corpo, ele a declarará pura. Visto que tudo ficou branco, ela está pura.

[[v3-13-14]]

^<<v3-13-14,14>>^ Mas quando nela aparecer carne viva, ficará impura.

[[v3-13-15]]

^<<v3-13-15,15>>^ Quando o sacerdote vir a carne viva, ele a declarará impura. A carne viva é impura; trata-se de lepra.

[[v3-13-16]]

^<<v3-13-16,16>>^ Se a carne viva retroceder e a pele se tornar branca, a pessoa voltará ao sacerdote.

[[v3-13-17]]

^<<v3-13-17,17>>^ Este a examinará, e, se a parte afetada se tornou branca, o sacerdote declarará pura a pessoa infectada, que então estará pura.

[[v3-13-18]]

^<<v3-13-18,18>>^ "Quando alguém tiver uma ferida purulenta em sua pele e ela sarar,

[[v3-13-19]]

^<<v3-13-19,19>>^ e no lugar da ferida aparecer um inchaço branco ou uma mancha avermelhada, ele se apresentará ao sacerdote.

[[v3-13-20]]

^<<v3-13-20,20>>^ Este examinará o local, e, se parecer mais profundo do que a pele e o pêlo ali tiver se tornado branco, o sacerdote o declarará impuro. É sinal de lepra que se alastrou onde estava a ferida.

[[v3-13-21]]

^<<v3-13-21,21>>^ Mas se, quando o sacerdote o examinar não houver nenhum pêlo branco e o lugar não estiver mais profundo do que a pele e tiver diminuído, então o sacerdote o porá em isolamento por sete dias.

[[v3-13-22]]

^<<v3-13-22,22>>^ Se de fato estiver se espalhando pela pele, o sacerdote o declarará impuro; é sinal de lepra.

[[v3-13-23]]

^<<v3-13-23,23>>^ Mas, se a mancha não tiver se alterado nem se espalhado, é apenas a cicatriz da ferida, e o sacerdote o declarará puro.

[[v3-13-24]]

^<<v3-13-24,24>>^ "Quando alguém tiver uma queimadura na pele, e uma mancha avermelhada ou branca aparecer na carne viva da queimadura,

[[v3-13-25]]

^<<v3-13-25,25>>^ o sacerdote examinará a mancha, e, se o pêlo sobre ela tiver se tornado branco e ela parecer mais profunda do que a pele, é lepra que surgiu na queimadura. O sacerdote o declarará impuro; é sinal de lepra na pele.

[[v3-13-26]]

^<<v3-13-26,26>>^ Mas, se o sacerdote examinar a mancha e nela não houver pêlo branco e esta não estiver mais profunda do que a pele e tiver diminuído, então o sacerdote o porá em isolamento por sete dias.

[[v3-13-27]]

^<<v3-13-27,27>>^ No sétimo dia o sacerdote o examinará, e, se a mancha estiver se espalhado pela pele, o sacerdote o declarará impuro; é sinal de lepra.

[[v3-13-28]]

^<<v3-13-28,28>>^ Se, todavia, a mancha não tiver se alterado nem se espalhado pela pele, mas tiver diminuído, é um inchaço da queimadura, e o sacerdote o declarará puro; é apenas a cicatriz da queimadura.

[[v3-13-29]]

^<<v3-13-29,29>>^ "Quando um homem ou uma mulher tiver uma ferida na cabeça ou no queixo,

[[v3-13-30]]

^<<v3-13-30,30>>^ o sacerdote examinará a ferida, e, se ela parecer mais profunda do que a pele e o pêlo nela for amarelado e fino, o sacerdote declarará impura aquela pessoa; é sarna, isto é, lepra da cabeça ou do queixo.

[[v3-13-31]]

^<<v3-13-31,31>>^ Mas, se quando o sacerdote examinar o sinal de sarna, este não parecer mais profundo do que a pele e não houver pêlo escuro nela, então o sacerdote porá a pessoa infectada em isolamento por sete dias.

[[v3-13-32]]

^<<v3-13-32,32>>^ No sétimo dia o sacerdote examinará a parte afetada, e, se a sarna não tiver se espalhado e não houver pêlo amarelado nela e não parecer mais profunda do que a pele,

[[v3-13-33]]

^<<v3-13-33,33>>^ a pessoa rapará os pêlos, exceto na parte afetada, e o sacerdote a porá em isolamento por mais sete dias.

[[v3-13-34]]

^<<v3-13-34,34>>^ No sétimo dia o sacerdote examinará a sarna, e, se não tiver se espalhado mais e não parecer mais profunda do que a pele, o sacerdote declarará pura a pessoa. Esta lavará suas roupas e estará pura.

[[v3-13-35]]

^<<v3-13-35,35>>^ Mas, se a sarna se espalhar pela pele depois que a pessoa for declarada pura,

[[v3-13-36]]

^<<v3-13-36,36>>^ o sacerdote a examinará, e, se a sarna tiver se espalhado pela pele, o sacerdote não precisará procurar pêlo amarelado; a pessoa está impura.

[[v3-13-37]]

^<<v3-13-37,37>>^ Se, entretanto, verificar que não houve alteração e cresceu pêlo escuro, a sarna está curada. Ela está pura, e o sacerdote a declarará pura.

[[v3-13-38]]

^<<v3-13-38,38>>^ "Quando um homem ou uma mulher tiver manchas brancas na pele,

[[v3-13-39]]

^<<v3-13-39,39>>^ o sacerdote examinará as manchas; se forem brancas e sem brilho, é um eczema que se alastrou; essa pessoa está pura.

[[v3-13-40]]

^<<v3-13-40,40>>^ "Quando os cabelos de um homem caírem, ele está calvo, todavia puro.

[[v3-13-41]]

^<<v3-13-41,41>>^ Se lhe caírem os cabelos da frente da cabeça, ele está meio-calvo, porém puro.

[[v3-13-42]]

^<<v3-13-42,42>>^ Mas, se tiver uma ferida avermelhada na parte calva da frente ou de trás da cabeça, é lepra que se alastra pela calva da frente ou de trás da cabeça.

[[v3-13-43]]

^<<v3-13-43,43>>^ O sacerdote o examinará, e, se a ferida inchada na parte da frente ou de trás da calva for avermelhada como a lepra de pele,

[[v3-13-44]]

^<<v3-13-44,44>>^ o homem está leproso e impuro. O sacerdote terá que declará-lo impuro devido à ferida na cabeça.

[[v3-13-45]]

^<<v3-13-45,45>>^ "Quem ficar leproso, apresentando quaisquer desses sintomas, usará roupas rasgadas, andará descabelado, cobrirá a parte inferior do rosto e gritará: ‘Impuro! Impuro! ’

[[v3-13-46]]

^<<v3-13-46,46>>^ Enquanto tiver a doença, estará impuro. Viverá separado, fora do acampamento.

[[v3-13-47]]

^<<v3-13-47,47>>^ "Quando aparecer mancha de mofo em alguma roupa, seja roupa de lã, seja de linho,

[[v3-13-48]]

^<<v3-13-48,48>>^ ou em qualquer peça tecida ou entrelaçada de linho ou de lã, ou em algum pedaço ou objeto de couro,

[[v3-13-49]]

^<<v3-13-49,49>>^ se a mancha na roupa, ou no pedaço de couro, ou na peça tecida ou entrelaçada, ou em qualquer objeto de couro, for esverdeada ou avermelhada, é mancha de mofo que deverá ser mostrada ao sacerdote.

[[v3-13-50]]

^<<v3-13-50,50>>^ O sacerdote examinará a mancha e isolará o objeto afetado por sete dias.

[[v3-13-51]]

^<<v3-13-51,51>>^ No sétimo dia examinará a mancha, e, se ela tiver se espalhado pela roupa, ou pela peça tecida ou entrelaçada, ou pelo pedaço de couro, qualquer que seja o seu uso, é mofo corrosivo; o objeto está impuro.

[[v3-13-52]]

^<<v3-13-52,52>>^ Ele queimará a roupa, ou a peça tecida ou entrelaçada, ou qualquer objeto de couro que tiver a mancha, pois é mofo corrosivo; o objeto será queimado.

[[v3-13-53]]

^<<v3-13-53,53>>^ "Mas se, quando o sacerdote o examinar, a mancha não tiver se espalhado pela roupa, ou pela peça tecida ou entrelaçada, ou pelo objeto de couro,

[[v3-13-54]]

^<<v3-13-54,54>>^ ordenará que o objeto afetado seja lavado. Então ele o isolará por mais sete dias.

[[v3-13-55]]

^<<v3-13-55,55>>^ Depois de lavado o objeto afetado, o sacerdote o examinará, e, se a mancha não tiver alterado sua cor, ainda que não tenha se espalhado, o objeto estará impuro. Queime-o com fogo, quer o mofo corrosivo tenha afetado um lado, quer o outro do objeto.

[[v3-13-56]]

^<<v3-13-56,56>>^ Se quando o sacerdote o examinar, a mancha tiver diminuído depois de lavado o objeto, ele cortará a parte afetada da roupa, ou do pedaço de couro, ou da peça tecida ou entrelaçada.

[[v3-13-57]]

^<<v3-13-57,57>>^ Mas, se a mancha ainda aparecer na roupa, ou na peça tecida ou entrelaçada, ou no objeto de couro, é mofo que se alastra, e tudo o que tiver o mofo será queimado com fogo.

[[v3-13-58]]

^<<v3-13-58,58>>^ Mas se, depois de lavada, a mancha desaparecer da roupa, ou da peça tecida ou entrelaçada, ou do objeto de couro, será lavado de novo, e então estará puro".

[[v3-13-59]]

^<<v3-13-59,59>>^ Essa é a regulamentação acerca da mancha de mofo nas roupas de lã ou de linho, nas peças tecidas ou entrelaçadas, ou nos objetos de couro, para declará-los puros ou impuros.

'''

xref:003-levitico/003-levitico-012.adoc#v3-12-0[&#60; Capítulo Anterior] | <<v3-13-0,Topo>> | xref:003-levitico/003-levitico-014.adoc#v3-14-0[Próximo Capítulo &#62;]