include::./index.adoc[]

[[v3-10-0]]
=== Levítico, 10
// nvi ?, NVI - Nova Versão Internacional

[[v3-10-1]]

^<<v3-10-1,1>>^ Nadabe e Abiú, filhos de Arão, pegaram cada um o seu incensário, nos quais acenderam fogo, acrescentaram incenso, e trouxeram fogo profano perante o Senhor, sem que tivessem sido autorizados.

[[v3-10-2]]

^<<v3-10-2,2>>^ Então saiu fogo da presença do Senhor e os consumiu. Morreram perante o Senhor.

[[v3-10-3]]

^<<v3-10-3,3>>^ Moisés então disse a Arão: "Foi isto que o Senhor disse: ‘Aos que de mim se aproximam santo me mostrarei; à vista de todo o povo glorificado serei’ ". Arão, porém, ficou em silêncio.

[[v3-10-4]]

^<<v3-10-4,4>>^ Então Moisés chamou Misael e Elzafã, filhos de Uziel, tio de Arão, e lhes disse: "Venham cá; tirem os seus primos da frente do santuário e levem-nos para fora do acampamento".

[[v3-10-5]]

^<<v3-10-5,5>>^ Eles foram e os puxaram pelas túnicas, para fora do acampamento, conforme Moisés tinha ordenado.

[[v3-10-6]]

^<<v3-10-6,6>>^ Então Moisés disse a Arão e a seus filhos Eleazar e Itamar: "Não andem descabelados, nem rasguem as roupas em sinal de luto, senão vocês morrerão e a ira do Senhor cairá sobre toda a comunidade. Mas os seus parentes, e toda a nação de Israel, poderão chorar por aqueles que o Senhor destruiu pelo fogo.

[[v3-10-7]]

^<<v3-10-7,7>>^ Não saiam da entrada da Tenda do Encontro, senão vocês morrerão, porquanto o óleo da unção do Senhor está sobre vocês". E eles fizeram conforme Moisés tinha ordenado.

[[v3-10-8]]

^<<v3-10-8,8>>^ Depois o Senhor disse a Arão:

[[v3-10-9]]

^<<v3-10-9,9>>^ "Você e seus filhos não devem beber vinho nem outra bebida fermentada antes de entrar na Tenda do Encontro, senão vocês morrerão. É um decreto perpétuo para as suas gerações.

[[v3-10-10]]

^<<v3-10-10,10>>^ Vocês têm que fazer separação entre o santo e o profano, entre o puro e o impuro,

[[v3-10-11]]

^<<v3-10-11,11>>^ e ensinar aos israelitas todos os decretos que o Senhor lhes deu por meio de Moisés".

[[v3-10-12]]

^<<v3-10-12,12>>^ Então Moisés disse a Arão e aos seus filhos que ficaram vivos, Eleazar e Itamar: "Peguem a oferta de cereal que sobrou das ofertas dedicadas ao Senhor, preparadas no fogo, e comam-na sem fermento junto ao altar, pois é santíssima.

[[v3-10-13]]

^<<v3-10-13,13>>^ Comam-na em lugar sagrado, porquanto é a porção que lhes cabe por decreto, a você e a seus filhos, das ofertas dedicadas ao Senhor, preparadas no fogo; pois assim me foi ordenado.

[[v3-10-14]]

^<<v3-10-14,14>>^ O peito ritualmente movido e a coxa ofertada, você, seus filhos e suas filhas poderão comer num lugar cerimonialmente puro; foi dado a você e a seus filhos como porção das ofertas de comunhão dos israelitas.

[[v3-10-15]]

^<<v3-10-15,15>>^ A coxa ofertada e o peito ritualmente movido devem ser trazidos junto com as porções de gordura das ofertas preparadas no fogo, para serem movidos perante o Senhor como gesto ritual de apresentação. Esta será a porção por decreto perpétuo para você e seus descendentes, conforme o Senhor tinha ordenado".

[[v3-10-16]]

^<<v3-10-16,16>>^ Quando Moisés procurou por toda parte o bode da oferta pelo pecado e soube que já fora queimado, irou-se contra Eleazar e Itamar, os filhos de Arão que ficaram vivos, e perguntou:

[[v3-10-17]]

^<<v3-10-17,17>>^ "Por que vocês não comeram a carne da oferta pelo pecado no Lugar Santo? É santíssima; foi-lhes dada para retirar a culpa da comunidade e fazer propiciação por ela perante o Senhor.

[[v3-10-18]]

^<<v3-10-18,18>>^ Como o sangue do animal não foi levado para dentro do Lugar Santo, vocês deviam tê-lo comido no Lugar Santo, conforme ordenei".

[[v3-10-19]]

^<<v3-10-19,19>>^ Arão respondeu a Moisés: "Hoje eles ofereceram o seu sacrifício pelo pecado e o seu holocausto perante o Senhor; mesmo assim coisas como essas aconteceram comigo. Será que teria agradado ao Senhor se eu tivesse comido a oferta pelo pecado hoje? "

[[v3-10-20]]

^<<v3-10-20,20>>^ Quando Moisés ouviu isso, ficou satisfeito.

'''

xref:003-levitico/003-levitico-009.adoc#v3-9-0[&#60; Capítulo Anterior] | <<v3-10-0,Topo>> | xref:003-levitico/003-levitico-011.adoc#v3-11-0[Próximo Capítulo &#62;]