include::./index.adoc[]

[[v3-6-0]]
=== Levítico, 6
// nvi ?, NVI - Nova Versão Internacional

[[v3-6-1]]

^<<v3-6-1,1>>^ E disse o Senhor a Moisés:

[[v3-6-2]]

^<<v3-6-2,2>>^ "Se alguém pecar, cometendo uma ofensa contra o Senhor, enganando o seu próximo no que diz respeito a algo que lhe foi confiado ou deixado como penhor ou roubado, ou se lhe extorquir algo,

[[v3-6-3]]

^<<v3-6-3,3>>^ ou se achar algum bem perdido e mentir a respeito disso, ou se jurar falsamente a respeito de qualquer coisa, cometendo pecado;

[[v3-6-4]]

^<<v3-6-4,4>>^ quando assim pecar, tornando-se por isso culpado, terá que devolver o que roubou ou tomou mediante extorsão, ou o que lhe foi confiado, ou os bens perdidos que achou,

[[v3-6-5]]

^<<v3-6-5,5>>^ ou qualquer coisa sobre a qual tenha jurado falsamente. Fará restituição plena, acrescentará a isso um quinto do valor e dará tudo ao proprietário no dia em que apresentar a sua oferta pela culpa.

[[v3-6-6]]

^<<v3-6-6,6>>^ E por sua culpa trará ao sacerdote uma oferta dedicada ao Senhor: um carneiro do rebanho, sem defeito e devidamente avaliado.

[[v3-6-7]]

^<<v3-6-7,7>>^ Dessa forma o sacerdote fará propiciação por ele perante o Senhor, e ele será perdoado de qualquer dessas coisas que fez e que o tornou culpado".

[[v3-6-8]]

^<<v3-6-8,8>>^ O Senhor disse a Moisés:

[[v3-6-9]]

^<<v3-6-9,9>>^ "Dê este mandamento a Arão e a seus filhos: Esta é a regulamentação acerca do holocausto: ele terá que ficar queimando até de manhã sobre as brasas do altar, onde o fogo terá que ser mantido aceso.

[[v3-6-10]]

^<<v3-6-10,10>>^ O sacerdote vestirá suas roupas de linho e os calções de linho por baixo, retirará as cinzas do holocausto que o fogo consumiu no altar e as colocará ao lado do altar.

[[v3-6-11]]

^<<v3-6-11,11>>^ Depois trocará de roupa, e levará as cinzas para fora do acampamento, a um lugar cerimonialmente puro.

[[v3-6-12]]

^<<v3-6-12,12>>^ Mantenha-se aceso o fogo no altar; não deve ser apagado. Toda manhã o sacerdote acrescentará lenha, arrumará o holocausto sobre o fogo e queimará sobre ele a gordura das ofertas de comunhão.

[[v3-6-13]]

^<<v3-6-13,13>>^ Mantenha-se o fogo continuamente aceso no altar; não deve ser apagado.

[[v3-6-14]]

^<<v3-6-14,14>>^ "Esta é a regulamentação da oferta de cereal: os filhos de Arão a apresentarão ao Senhor, em frente do altar.

[[v3-6-15]]

^<<v3-6-15,15>>^ O sacerdote apanhará um punhado da melhor farinha com óleo, juntamente com todo o incenso que está sobre a oferta de cereal, e queimará no altar a porção memorial como aroma agradável ao Senhor.

[[v3-6-16]]

^<<v3-6-16,16>>^ Arão e seus filhos comerão o restante da oferta, mas deverão comê-lo sem fermento e em lugar sagrado, no pátio da Tenda do Encontro.

[[v3-6-17]]

^<<v3-6-17,17>>^ Essa oferta não será assada com fermento; eu a dei a eles como porção das ofertas feitas a mim com fogo. É santíssima, como a oferta pelo pecado e como a oferta pela culpa.

[[v3-6-18]]

^<<v3-6-18,18>>^ Somente os homens descendentes de Arão poderão comer da porção das ofertas dedicadas ao Senhor, preparadas no fogo. É um decreto perpétuo para as suas gerações. Tudo o que nelas tocar se tornará santo".

[[v3-6-19]]

^<<v3-6-19,19>>^ O Senhor disse também a Moisés:

[[v3-6-20]]

^<<v3-6-20,20>>^ "Esta é a oferta que Arão e os seus descendentes terão que trazer ao Senhor no dia em que ele for ungido: um jarro da melhor farinha, como na oferta regular de cereal, metade pela manhã e metade à tarde.

[[v3-6-21]]

^<<v3-6-21,21>>^ Prepare-a com óleo numa assadeira; traga-a bem misturada e apresente a oferta de cereal partida em pedaços, como aroma agradável ao Senhor.

[[v3-6-22]]

^<<v3-6-22,22>>^ Todo sacerdote ungido, descendentes de Arão, também preparará essa oferta. É a porção do Senhor por decreto perpétuo e será totalmente queimada.

[[v3-6-23]]

^<<v3-6-23,23>>^ Toda oferta de cereal do sacerdote será totalmente queimada; não será comida".

[[v3-6-24]]

^<<v3-6-24,24>>^ O Senhor disse a Moisés:

[[v3-6-25]]

^<<v3-6-25,25>>^ "Diga a Arão e aos seus filhos: Esta é a regulamentação da oferta pelo pecado: O animal da oferta pelo pecado será morto perante o Senhor no local onde é sacrificado o holocausto; é uma oferta santíssima.

[[v3-6-26]]

^<<v3-6-26,26>>^ O sacerdote que oferecer o animal, o comerá em lugar sagrado, no pátio da Tenda do Encontro.

[[v3-6-27]]

^<<v3-6-27,27>>^ Tudo o que tocar na carne se tornará santo, e se o sangue respingar na roupa, será lavada em lugar sagrado.

[[v3-6-28]]

^<<v3-6-28,28>>^ A vasilha de barro em que a carne for cozida deverá ser quebrada; mas, se for cozida numa vasilha de bronze, a vasilha deverá ser esfregada e enxaguada com água.

[[v3-6-29]]

^<<v3-6-29,29>>^ Somente os homens da família dos sacerdotes poderão comê-la; é uma oferta santíssima.

[[v3-6-30]]

^<<v3-6-30,30>>^ Mas toda oferta pelo pecado, cujo sangue for trazido para a Tenda do Encontro para propiciação no Lugar Santo, não será comida; terá que ser queimada".

'''

xref:003-levitico/003-levitico-005.adoc#v3-5-0[&#60; Capítulo Anterior] | <<v3-6-0,Topo>> | xref:003-levitico/003-levitico-007.adoc#v3-7-0[Próximo Capítulo &#62;]