include::./index.adoc[]

[[v3-20-0]]
=== Levítico, 20
// nvi ?, NVI - Nova Versão Internacional

[[v3-20-1]]

^<<v3-20-1,1>>^ Disse o Senhor a Moisés:

[[v3-20-2]]

^<<v3-20-2,2>>^ "Diga aos israelitas: Qualquer israelita ou estrangeiro residente em Israel que entregar um dos seus filhos a Moloque, terá que ser executado. O povo da terra o apedrejará.

[[v3-20-3]]

^<<v3-20-3,3>>^ Voltarei o meu rosto contra ele e o eliminarei do meio do seu povo; pois deu os seus filhos a Moloque, contaminando assim o meu santuário e profanando o meu santo nome.

[[v3-20-4]]

^<<v3-20-4,4>>^ Se o povo deliberadamente fechar os olhos quando alguém entregar um dos seus filhos a Moloque, e deixar de executá-lo,

[[v3-20-5]]

^<<v3-20-5,5>>^ voltarei o meu rosto contra aquele homem e contra o seu clã e eliminarei do meio do seu povo tanto ele quanto todos os que o seguem, prostituindo-se com Moloque.

[[v3-20-6]]

^<<v3-20-6,6>>^ "Voltarei o meu rosto contra aquele que procurar médiuns e espíritas para segui-los, prostituindo-se com eles. Eu o eliminarei do meio do seu povo.

[[v3-20-7]]

^<<v3-20-7,7>>^ "Consagrem-se, porém, e sejam santos, porque eu sou o Senhor, o Deus de vocês.

[[v3-20-8]]

^<<v3-20-8,8>>^ Obedeçam aos meus decretos e pratiquem-nos. Eu sou o Senhor que os santifica.

[[v3-20-9]]

^<<v3-20-9,9>>^ "Se alguém amaldiçoar seu pai ou sua mãe, terá que ser executado. Por ter amaldiçoado o seu pai ou a sua mãe, merece a morte.

[[v3-20-10]]

^<<v3-20-10,10>>^ "Se um homem cometer adultério com a mulher de outro homem, com a mulher do seu próximo, tanto o adúltero quanto a adúltera terão que ser executados.

[[v3-20-11]]

^<<v3-20-11,11>>^ "Se um homem se deitar com a mulher do seu pai, desonrou seu pai. Tanto o homem quanto a mulher terão que ser executados, pois merecem a morte.

[[v3-20-12]]

^<<v3-20-12,12>>^ "Se um homem se deitar com a sua nora, ambos terão que ser executados. O que fizeram é depravação; merecem a morte.

[[v3-20-13]]

^<<v3-20-13,13>>^ "Se um homem se deitar com outro homem como quem se deita com uma mulher, ambos praticaram um ato repugnante. Terão que ser executados, pois merecem a morte.

[[v3-20-14]]

^<<v3-20-14,14>>^ "Se um homem tomar uma mulher e a mãe dela, comete perversidade. Tanto ele quanto elas serão queimados com fogo, para que não haja perversidade entre vocês.

[[v3-20-15]]

^<<v3-20-15,15>>^ "Se um homem tiver relações sexuais com um animal, terá que ser executado, e vocês matarão também o animal.

[[v3-20-16]]

^<<v3-20-16,16>>^ "Se uma mulher se aproximar de algum animal para ajuntar-se com ele, vocês matarão a mulher e o animal. Ambos terão que ser executados, pois merecem a morte.

[[v3-20-17]]

^<<v3-20-17,17>>^ "Se um homem tomar por mulher sua irmã, filha de seu pai ou de sua mãe, e se envolver sexualmente com ela, pratica um ato vergonhoso. Serão eliminados à vista de todo o povo. Desonrou sua irmã e sofrerá as conseqüências da sua iniqüidade.

[[v3-20-18]]

^<<v3-20-18,18>>^ "Se um homem se deitar com uma mulher durante a menstruação e com ela se envolver sexualmente, ambos serão eliminados do meio do seu povo, pois expuseram o sangramento dela.

[[v3-20-19]]

^<<v3-20-19,19>>^ "Não se envolva sexualmente com a irmã de sua mãe, nem com a irmã de seu pai; pois quem se envolver sexualmente com uma parenta próxima sofrerá as conseqüências da sua iniqüidade.

[[v3-20-20]]

^<<v3-20-20,20>>^ "Se um homem se deitar com a mulher do seu tio, desonrou seu tio. Eles sofrerão as conseqüências do seu pecado; morrerão sem filhos.

[[v3-20-21]]

^<<v3-20-21,21>>^ "Se um homem tomar por mulher a mulher do seu irmão, comete impureza; desonrou seu irmão. Ficarão sem filhos.

[[v3-20-22]]

^<<v3-20-22,22>>^ "Obedeçam a todos os meus decretos e leis e pratiquem-nos, para que a terra para onde os estou levando para habitarem não os vomite.

[[v3-20-23]]

^<<v3-20-23,23>>^ Não sigam os costumes dos povos que vou expulsar de diante de vocês. Por terem feito todas essas coisas, causam-me repugnância.

[[v3-20-24]]

^<<v3-20-24,24>>^ Mas a vocês prometi que herdarão a terra deles; eu a darei a vocês como herança, terra que mana leite e mel. Eu sou o Senhor, o Deus de vocês, que os separou dentre os povos.

[[v3-20-25]]

^<<v3-20-25,25>>^ "Portanto, façam separação entre animais puros e impuros e entre aves puras e impuras. Não se contaminem com animal, ou ave, ou com qualquer criatura que se move rente ao chão, os quais separei de vocês por serem eles impuros.

[[v3-20-26]]

^<<v3-20-26,26>>^ Vocês serão santos para mim, porque eu, o Senhor, sou santo, e os separei dentre os povos para serem meus.

[[v3-20-27]]

^<<v3-20-27,27>>^ "Os homens ou mulheres que, entre vocês, forem médiuns ou espíritas, terão que ser executados. Serão apedrejados, pois merecem a morte".

'''

xref:003-levitico/003-levitico-019.adoc#v3-19-0[&#60; Capítulo Anterior] | <<v3-20-0,Topo>> | xref:003-levitico/003-levitico-021.adoc#v3-21-0[Próximo Capítulo &#62;]