include::./index.adoc[]

[[v3-21-0]]
=== Levítico, 21
// nvi ?, NVI - Nova Versão Internacional

[[v3-21-1]]

^<<v3-21-1,1>>^ Disse ainda o Senhor a Moisés: "Diga o seguinte aos sacerdotes, os filhos de Arão: Um sacerdote não poderá tornar-se impuro por causa de alguém do seu povo que venha a morrer,

[[v3-21-2]]

^<<v3-21-2,2>>^ a não ser por um parente próximo, como mãe ou pai, filho ou filha, irmão,

[[v3-21-3]]

^<<v3-21-3,3>>^ ou irmã virgem dependente dele por ainda não ter marido; por causa dela, poderá tornar-se impuro.

[[v3-21-4]]

^<<v3-21-4,4>>^ Não poderá tornar-se impuro e contaminar-se por causa de parentes por casamento.

[[v3-21-5]]

^<<v3-21-5,5>>^ "Os sacerdotes não raparão a cabeça, nem apararão as pontas da barba, nem farão cortes no corpo.

[[v3-21-6]]

^<<v3-21-6,6>>^ Serão santos ao seu Deus, e não profanarão o nome do seu Deus. Pelo fato de apresentarem ao Senhor as ofertas preparadas no fogo, ofertas de alimento do seu Deus, serão santos.

[[v3-21-7]]

^<<v3-21-7,7>>^ "Não poderão tomar por mulher uma prostituta, uma moça que tenha perdido a virgindade, ou uma mulher divorciada do seu marido, porque o sacerdote é santo ao seu Deus.

[[v3-21-8]]

^<<v3-21-8,8>>^ Considerem-no santo, porque ele oferece o alimento do seu Deus. Considerem-no santo, porque eu, o Senhor, que os santifico, sou santo.

[[v3-21-9]]

^<<v3-21-9,9>>^ "Se a filha de um sacerdote se corromper, tornando-se prostituta, desonra seu pai; será queimada com fogo.

[[v3-21-10]]

^<<v3-21-10,10>>^ "O sumo sacerdote, aquele entre seus irmãos sobre cuja cabeça tiver sido derramado o óleo da unção, e que tiver sido consagrado para usar as vestes sacerdotais, não andará descabelado, nem rasgará as roupas em sinal de luto.

[[v3-21-11]]

^<<v3-21-11,11>>^ Não entrará onde houver um cadáver. Não se tornará impuro, nem mesmo por causa do seu pai ou da sua mãe;

[[v3-21-12]]

^<<v3-21-12,12>>^ e não deixará o santuário do seu Deus, nem o profanará, porquanto foi consagrado pelo óleo da unção do seu Deus. Eu sou o Senhor.

[[v3-21-13]]

^<<v3-21-13,13>>^ "A mulher que ele tomar terá que ser virgem.

[[v3-21-14]]

^<<v3-21-14,14>>^ Não poderá ser viúva, nem divorciada, nem moça que perdeu a virgindade, nem prostituta, mas terá que ser uma virgem do seu próprio povo,

[[v3-21-15]]

^<<v3-21-15,15>>^ assim ele não profanará a sua descendência entre o seu povo. Eu sou o Senhor, que o santifico".

[[v3-21-16]]

^<<v3-21-16,16>>^ Disse ainda o Senhor a Moisés:

[[v3-21-17]]

^<<v3-21-17,17>>^ "Diga a Arão: Pelas suas gerações, nenhum dos seus descendentes que tenha algum defeito poderá aproximar-se para trazer ao seu Deus ofertas de alimento.

[[v3-21-18]]

^<<v3-21-18,18>>^ Nenhum homem que tenha algum defeito poderá aproximar-se: ninguém que seja cego ou aleijado, que tenha o rosto defeituoso ou o corpo deformado;

[[v3-21-19]]

^<<v3-21-19,19>>^ ninguém que tenha o pé ou a mão defeituosos,

[[v3-21-20]]

^<<v3-21-20,20>>^ ou que seja corcunda ou anão, ou que tenha qualquer defeito na vista, ou que esteja com feridas purulentas ou com fluxo, ou que tenha testículos defeituosos.

[[v3-21-21]]

^<<v3-21-21,21>>^ Nenhum descendente do sacerdote Arão que tenha qualquer defeito poderá aproximar-se para apresentar ao Senhor ofertas preparadas no fogo. Tem defeito; não poderá aproximar-se para trazê-las ao seu Deus.

[[v3-21-22]]

^<<v3-21-22,22>>^ Poderá comer o alimento santíssimo de seu Deus, e também o alimento santo;

[[v3-21-23]]

^<<v3-21-23,23>>^ contudo, por causa do seu defeito, não se aproximará do véu nem do altar, para que não profane o meu santuário. Eu sou o Senhor, que os santifico".

[[v3-21-24]]

^<<v3-21-24,24>>^ Foi isso que Moisés falou a Arão e a seus filhos e a todos os israelitas.

'''

xref:003-levitico/003-levitico-020.adoc#v3-20-0[&#60; Capítulo Anterior] | <<v3-21-0,Topo>> | xref:003-levitico/003-levitico-022.adoc#v3-22-0[Próximo Capítulo &#62;]