include::./index.adoc[]

[[v3-11-0]]
=== Levítico, 11
// nvi ?, NVI - Nova Versão Internacional

[[v3-11-1]]

^<<v3-11-1,1>>^ Disse o Senhor a Moisés e a Arão:

[[v3-11-2]]

^<<v3-11-2,2>>^ "Digam aos israelitas: De todos os animais que vivem na terra, estes são os que vocês poderão comer:

[[v3-11-3]]

^<<v3-11-3,3>>^ Qualquer animal que tem casco fendido e dividido em duas unhas, e que rumina.

[[v3-11-4]]

^<<v3-11-4,4>>^ "Vocês não poderão comer aqueles que só ruminam nem os que só têm o casco fendido. O camelo, embora rumine, não tem casco fendido; considerem-no impuro.

[[v3-11-5]]

^<<v3-11-5,5>>^ O coelho, embora rumine, não tem casco fendido; é impuro para vocês.

[[v3-11-6]]

^<<v3-11-6,6>>^ A lebre, embora rumine, não tem casco fendido; considerem-na impura.

[[v3-11-7]]

^<<v3-11-7,7>>^ E o porco, embora tenha casco fendido e dividido em duas unhas, não rumina; considerem-no impuro.

[[v3-11-8]]

^<<v3-11-8,8>>^ Vocês não comerão a carne desses animais nem tocarão em seus cadáveres; considerem-nos impuros.

[[v3-11-9]]

^<<v3-11-9,9>>^ "De todas as criaturas que vivem nas águas do mar e dos rios, vocês poderão comer todas as que possuem barbatanas e escamas.

[[v3-11-10]]

^<<v3-11-10,10>>^ Mas todas as criaturas que vivem nos mares ou nos rios, que não possuem barbatanas e escamas, quer dentre todas as pequenas criaturas que povoam as águas quer dentre todos os outros animais das águas, serão proibidas para vocês.

[[v3-11-11]]

^<<v3-11-11,11>>^ Por isso, não poderão comer sua carne e considerarão impuros os seus cadáveres.

[[v3-11-12]]

^<<v3-11-12,12>>^ Tudo o que vive na água e não possui barbatanas e escamas será proibido para vocês.

[[v3-11-13]]

^<<v3-11-13,13>>^ "Estas são as aves que vocês considerarão impuras, das quais não poderão comer porque são proibidas: a águia, o urubu, a águia-marinha,

[[v3-11-14]]

^<<v3-11-14,14>>^ o milhafre, o falcão,

[[v3-11-15]]

^<<v3-11-15,15>>^ qualquer espécie de corvo,

[[v3-11-16]]

^<<v3-11-16,16>>^ a coruja-de-chifre, a coruja-de-orelha-pequena, a coruja-orelhuda, qualquer espécie de gavião,

[[v3-11-17]]

^<<v3-11-17,17>>^ o mocho, a coruja-pescadora e o corujão,

[[v3-11-18]]

^<<v3-11-18,18>>^ a coruja-branca, a coruja-do-deserto, o abutre,

[[v3-11-19]]

^<<v3-11-19,19>>^ a cegonha, qualquer tipo de garça, a poupa e o morcego.

[[v3-11-20]]

^<<v3-11-20,20>>^ "Todas as pequenas criaturas que enxameiam, que têm asas, mas que se movem pelo chão serão proibidas para vocês.

[[v3-11-21]]

^<<v3-11-21,21>>^ Dentre estas, porém, vocês poderão comer aquelas que têm pernas articuladas para saltar no chão.

[[v3-11-22]]

^<<v3-11-22,22>>^ Dessas vocês poderão comer os diversos tipos de gafanhotos.

[[v3-11-23]]

^<<v3-11-23,23>>^ Mas considerarão impuras todas as outras criaturas que enxameiam, que têm asas e que se movem pelo chão.

[[v3-11-24]]

^<<v3-11-24,24>>^ "Por meio deles vocês ficarão impuros; todo aquele que tocar em seus cadáveres estará impuro até à tarde.

[[v3-11-25]]

^<<v3-11-25,25>>^ Todo o que carregar o cadáver de algum deles lavará as suas roupas e estará impuro até à tarde.

[[v3-11-26]]

^<<v3-11-26,26>>^ "Todo animal de casco não dividido em duas unhas ou que não rumina é impuro para vocês; quem tocar qualquer um deles ficará impuro.

[[v3-11-27]]

^<<v3-11-27,27>>^ Todos os animais de quatro pés, que andam sobre a planta dos pés são impuros para vocês; todo o que tocar os seus cadáveres ficará impuro até à tarde.

[[v3-11-28]]

^<<v3-11-28,28>>^ Quem carregar o cadáver de algum deles lavará suas roupas, e estará impuro até à tarde. São impuros para vocês.

[[v3-11-29]]

^<<v3-11-29,29>>^ "Dos animais que se movem rente ao chão, estes vocês considerarão impuros: a doninha, o rato, qualquer espécie de lagarto grande,

[[v3-11-30]]

^<<v3-11-30,30>>^ a lagartixa, o lagarto-pintado, o lagarto, o lagarto da areia e o camaleão.

[[v3-11-31]]

^<<v3-11-31,31>>^ De todos os que se movem rente ao chão, esses vocês considerarão impuros. Quem neles tocar depois de mortos estará impuro até à tarde.

[[v3-11-32]]

^<<v3-11-32,32>>^ E tudo sobre o que um deles cair depois de morto, qualquer que seja o seu uso, ficará impuro, seja objeto feito de madeira, de pano, de couro ou de pano de saco. Deverá ser posto em água e estará impuro até a tarde, e então ficará puro.

[[v3-11-33]]

^<<v3-11-33,33>>^ Se um deles cair dentro de uma vasilha de barro, tudo o que nela houver ficará impuro, e vocês quebrarão a vasilha.

[[v3-11-34]]

^<<v3-11-34,34>>^ Qualquer alimento sobre o qual cair essa água, ficará impuro, e qualquer bebida que estiver dentro da vasilha, ficará impura.

[[v3-11-35]]

^<<v3-11-35,35>>^ Tudo aquilo sobre o que o cadáver de um desses animais cair ficará impuro; se for um forno ou um fogão de barro vocês o quebrarão. Estão impuros, e vocês os considerarão como tais.

[[v3-11-36]]

^<<v3-11-36,36>>^ Mas, se cair numa fonte ou numa cisterna onde se recolhe água, ela permanece pura; mas quem tocar no cadáver ficará impuro.

[[v3-11-37]]

^<<v3-11-37,37>>^ Se um cadáver cair sobre alguma semente a ser plantada, ela permanece pura;

[[v3-11-38]]

^<<v3-11-38,38>>^ mas se foi derramada água sobre a semente, vocês a considerarão impura.

[[v3-11-39]]

^<<v3-11-39,39>>^ "Quando morrer um animal que vocês têm permissão para comer, quem tocar no seu cadáver ficará impuro até à tarde.

[[v3-11-40]]

^<<v3-11-40,40>>^ Quem comer da carne do animal morto terá que lavar as suas roupas e ficará impuro até à tarde. Quem carregar o cadáver do animal terá que lavar as suas roupas, e ficará impuro até à tarde.

[[v3-11-41]]

^<<v3-11-41,41>>^ "Todo animal que se move rente ao chão lhes será proibido e não poderá ser comido.

[[v3-11-42]]

^<<v3-11-42,42>>^ Vocês não poderão comer animal algum que se move rente ao chão, quer se arraste sobre o ventre quer ande de quatro ou com o auxílio de muitos pés; eles lhes são proibidos.

[[v3-11-43]]

^<<v3-11-43,43>>^ Não se contaminem com qualquer desses animais. Não se tornem impuros com eles nem deixem que eles os tornem impuros.

[[v3-11-44]]

^<<v3-11-44,44>>^ Pois eu sou o Senhor Deus de vocês; consagrem-se e sejam santos, porque eu sou santo. Não se tornem impuros com qualquer animal que se move rente ao chão.

[[v3-11-45]]

^<<v3-11-45,45>>^ Eu sou o Senhor que os tirou da terra do Egito para ser o seu Deus; por isso, sejam santos, porque eu sou santo.

[[v3-11-46]]

^<<v3-11-46,46>>^ "Essa é a regulamentação acerca dos animais, das aves, de todos os seres vivos que se movem na água e de todo animal que se move rente ao chão.

[[v3-11-47]]

^<<v3-11-47,47>>^ Vocês farão separação entre o impuro e o puro, entre animais que podem e os que não podem ser comidos".

'''

xref:003-levitico/003-levitico-010.adoc#v3-10-0[&#60; Capítulo Anterior] | <<v3-11-0,Topo>> | xref:003-levitico/003-levitico-012.adoc#v3-12-0[Próximo Capítulo &#62;]