include::./index.adoc[]

[[v3-27-0]]
=== Levítico, 27
// nvi ?, NVI - Nova Versão Internacional

[[v3-27-1]]

^<<v3-27-1,1>>^ Disse também o SENHOR a Moisés:

[[v3-27-2]]

^<<v3-27-2,2>>^ "Diga o seguinte aos israelitas: Se alguém fizer um voto especial, dedicando pessoas ao Senhor, faça-o conforme o devido valor;

[[v3-27-3]]

^<<v3-27-3,3>>^ atribua aos homens entre vinte e sessenta anos o valor de seiscentos gramas de prata, com base no peso padrão do santuário;

[[v3-27-4]]

^<<v3-27-4,4>>^ e, se for mulher, atribua-lhe o valor de trezentos e sessenta gramas.

[[v3-27-5]]

^<<v3-27-5,5>>^ Se for alguém que tenha entre cinco e vinte anos, atribua aos homens o valor de duzentos e quarenta gramas e às mulheres o valor de cento e vinte gramas.

[[v3-27-6]]

^<<v3-27-6,6>>^ Se for alguém que tenha entre um mês e cinco anos de idade, atribua aos meninos o valor de sessenta gramas de prata e às meninas o valor de trinta e seis gramas de prata.

[[v3-27-7]]

^<<v3-27-7,7>>^ Se for alguém que tenha de sessenta anos para cima, atribua aos homens o valor de cento e oitenta gramas e às mulheres o valor de cento e vinte gramas.

[[v3-27-8]]

^<<v3-27-8,8>>^ Se quem fizer o voto for pobre demais para pagar o valor especificado, apresentará a pessoa ao sacerdote, que estabelecerá o valor de acordo com as possibilidades do homem que fez o voto.

[[v3-27-9]]

^<<v3-27-9,9>>^ "Se o que ele prometeu mediante voto for um animal aceitável como oferta ao Senhor, um animal assim dado ao Senhor torna-se santo.

[[v3-27-10]]

^<<v3-27-10,10>>^ Ele não poderá trocá-lo nem substituir um animal ruim por um bom, nem um animal bom por um ruim; caso troque um animal por outro, tanto o substituto quanto o substituído se tornarão santos.

[[v3-27-11]]

^<<v3-27-11,11>>^ Se o que ele prometeu mediante voto for um animal impuro, não aceitável como oferta ao Senhor, o animal será apresentado ao sacerdote,

[[v3-27-12]]

^<<v3-27-12,12>>^ que o avaliará por suas qualidades. A avaliação do sacerdote determinará o valor do animal.

[[v3-27-13]]

^<<v3-27-13,13>>^ Se o dono desejar resgatar o animal, terá que acrescentar um quinto ao seu valor.

[[v3-27-14]]

^<<v3-27-14,14>>^ "Se um homem consagrar a sua casa ao Senhor, o sacerdote avaliará a casa por suas qualidades. A avaliação do sacerdote determinará o valor da casa.

[[v3-27-15]]

^<<v3-27-15,15>>^ Se o homem que consagrar a sua casa quiser resgatá-la, terá que acrescentar um quinto ao seu valor, e a casa voltará a ser sua.

[[v3-27-16]]

^<<v3-27-16,16>>^ "Se um homem consagrar ao Senhor parte das terras da sua família, sua avaliação será de acordo com a semeadura: seiscentos gramas de prata para cada barril de semente de cevada.

[[v3-27-17]]

^<<v3-27-17,17>>^ Se consagrar a sua terra durante o ano do jubileu, o valor será integral.

[[v3-27-18]]

^<<v3-27-18,18>>^ Mas, se a consagrar depois do Jubileu, o sacerdote calculará o valor de acordo com o número de anos que faltarem para o próximo ano do jubileu, e o valor será reduzido.

[[v3-27-19]]

^<<v3-27-19,19>>^ Se o homem que consagrar a sua terra desejar resgatá-la, terá que acrescentar um quinto ao seu valor, e a terra voltará a ser sua.

[[v3-27-20]]

^<<v3-27-20,20>>^ Mas se não a resgatar, ou se a tiver vendido, não poderá mais ser resgatada;

[[v3-27-21]]

^<<v3-27-21,21>>^ quando a terra for liberada no Jubileu, será santa, consagrada ao Senhor, e se tornará propriedade dos sacerdotes.

[[v3-27-22]]

^<<v3-27-22,22>>^ "Se um homem consagrar ao Senhor terras que tenha comprado, terras que não fazem parte da propriedade da sua família,

[[v3-27-23]]

^<<v3-27-23,23>>^ o sacerdote determinará o valor de acordo com o tempo que falta para o ano do jubileu; o homem pagará o valor no mesmo dia, consagrando-o ao Senhor.

[[v3-27-24]]

^<<v3-27-24,24>>^ No ano do jubileu as terras serão devolvidas àquele de quem ele as comprou.

[[v3-27-25]]

^<<v3-27-25,25>>^ Todos os valores serão calculados com base no peso padrão do santuário, que são doze gramas.

[[v3-27-26]]

^<<v3-27-26,26>>^ "Ninguém poderá consagrar a primeira cria de um animal, pois já pertence ao Senhor; seja cria de vaca, seja de cabra, seja de ovelha, pertence ao Senhor.

[[v3-27-27]]

^<<v3-27-27,27>>^ Mas se for a cria de um animal impuro, poderá resgatá-la pelo valor estabelecido, acrescentando um quinto a esse valor. Se não for resgatada, será vendida pelo valor estabelecido.

[[v3-27-28]]

^<<v3-27-28,28>>^ "Todavia, nada que um homem possua e consagre ao Senhor, seja homem, seja animal, sejam terras de sua propriedade, poderá ser vendido ou resgatado; todas as coisas assim consagradas são santíssimas ao Senhor.

[[v3-27-29]]

^<<v3-27-29,29>>^ "Nenhuma pessoa consagrada para a destruição poderá ser resgatada; terá que ser executada.

[[v3-27-30]]

^<<v3-27-30,30>>^ "Todos os dízimos da terra, seja dos cereais, seja das frutas das árvores, pertencem ao Senhor; são consagrados ao Senhor.

[[v3-27-31]]

^<<v3-27-31,31>>^ Se um homem desejar resgatar parte do seu dízimo, terá que acrescentar um quinto ao seu valor.

[[v3-27-32]]

^<<v3-27-32,32>>^ O dízimo dos seus rebanhos, um de cada dez animais que passem debaixo da vara do pastor, será consagrado ao Senhor.

[[v3-27-33]]

^<<v3-27-33,33>>^ O dono não poderá retirar os bons dentre os ruins, nem fazer qualquer troca. Se fizer alguma troca, tanto o animal quanto o substituto se tornarão consagrados e não poderão ser resgatados".

[[v3-27-34]]

^<<v3-27-34,34>>^ São esses os mandamentos que o Senhor ordenou a Moisés no monte Sinai para os israelitas.

'''

xref:003-levitico/003-levitico-026.adoc#v3-26-0[&#60; Capítulo Anterior] | <<v3-27-0,Topo>> | xref:004-numeros/004-numeros-001.adoc#v4-1-0[Próximo Capítulo &#62;]