include::./index.adoc[]

[[v3-7-0]]
=== Levítico, 7
// nvi ?, NVI - Nova Versão Internacional

[[v3-7-1]]

^<<v3-7-1,1>>^ "Esta é a regulamentação da oferta pela culpa, que é oferta santíssima:

[[v3-7-2]]

^<<v3-7-2,2>>^ O animal da oferta pela culpa será morto no local onde são sacrificados os holocaustos, e seu sangue será derramado nos lados do altar.

[[v3-7-3]]

^<<v3-7-3,3>>^ Toda a sua gordura será oferecida: a parte gorda da cauda e a gordura que cobre as vísceras,

[[v3-7-4]]

^<<v3-7-4,4>>^ os dois rins com a gordura que os cobre e que está perto dos lombos, e o lóbulo do fígado, que será removido juntamente com os rins.

[[v3-7-5]]

^<<v3-7-5,5>>^ O sacerdote os queimará no altar como oferta dedicada ao Senhor, preparada no fogo. É oferta pela culpa.

[[v3-7-6]]

^<<v3-7-6,6>>^ Somente os homens da família dos sacerdotes poderão comê-la, mas deve ser comida em lugar sagrado; é oferta santíssima.

[[v3-7-7]]

^<<v3-7-7,7>>^ "A mesma regulamentação aplica-se tanto à oferta pelo pecado quanto à oferta pela culpa: a carne pertence ao sacerdote que faz propiciação pela culpa.

[[v3-7-8]]

^<<v3-7-8,8>>^ O sacerdote que oferecer um holocausto por alguém ficará com o couro do animal.

[[v3-7-9]]

^<<v3-7-9,9>>^ Toda oferta de cereal, assada num forno ou cozida numa panela ou numa assadeira, pertence ao sacerdote que a oferecer,

[[v3-7-10]]

^<<v3-7-10,10>>^ e toda oferta de cereal, amassada com óleo ou não, pertence igualmente aos descendentes de Arão.

[[v3-7-11]]

^<<v3-7-11,11>>^ "Esta é a regulamentação da oferta de comunhão que pode ser apresentada ao Senhor:

[[v3-7-12]]

^<<v3-7-12,12>>^ "Se alguém a fizer por gratidão, então, junto com sua oferta de gratidão, terá que oferecer bolos sem fermento e amassados com óleo, pães finos sem fermento e untados com óleo, e bolos da melhor farinha bem amassados e misturados com óleo.

[[v3-7-13]]

^<<v3-7-13,13>>^ Juntamente com sua oferta de comunhão por gratidão, apresentará uma oferta que inclua bolos com fermento.

[[v3-7-14]]

^<<v3-7-14,14>>^ De cada oferta trará uma contribuição ao Senhor que será dada ao sacerdote que asperge o sangue das ofertas de comunhão.

[[v3-7-15]]

^<<v3-7-15,15>>^ A carne da sua oferta de comunhão por gratidão será comida no dia em que for oferecida; nada poderá sobrar até o amanhecer.

[[v3-7-16]]

^<<v3-7-16,16>>^ "Se, contudo, sua oferta for resultado de um voto ou for uma oferta voluntária, a carne do sacrifício será comida no dia em que for oferecida, e o que sobrar poderá ser comido no dia seguinte.

[[v3-7-17]]

^<<v3-7-17,17>>^ Mas a carne que sobrar do sacrifício até o terceiro dia será queimada no fogo.

[[v3-7-18]]

^<<v3-7-18,18>>^ Se a carne da oferta de comunhão for comida ao terceiro dia, ela não será aceita. A oferta não será atribuída àquele que a ofereceu, pois a carne estará estragada; e quem dela comer sofrerá as conseqüências da sua iniqüidade.

[[v3-7-19]]

^<<v3-7-19,19>>^ "A carne que tocar em qualquer coisa impura não será comida; será queimada no fogo. A carne do sacrifício, porém, poderá ser comida por quem estiver puro.

[[v3-7-20]]

^<<v3-7-20,20>>^ Mas se alguém que está impuro comer da carne da oferta de comunhão que pertence ao Senhor, será eliminado do meio do seu povo.

[[v3-7-21]]

^<<v3-7-21,21>>^ Se alguém tocar em alguma coisa impura, seja impureza humana, seja de animal, seja qualquer outra coisa impura e proibida, e comer da carne da oferta de comunhão que pertence ao Senhor, será eliminado do meio do seu povo. "

[[v3-7-22]]

^<<v3-7-22,22>>^ E disse o Senhor a Moisés:

[[v3-7-23]]

^<<v3-7-23,23>>^ "Diga aos israelitas: Não comam gordura alguma de boi, carneiro ou cabrito.

[[v3-7-24]]

^<<v3-7-24,24>>^ A gordura de um animal encontrado morto ou despedaçado por animais selvagens pode ser usada para qualquer outra finalidade, mas nunca poderá ser comida.

[[v3-7-25]]

^<<v3-7-25,25>>^ Quem comer a gordura de um animal, dedicado ao Senhor numa oferta preparada no fogo, será eliminado do meio do seu povo.

[[v3-7-26]]

^<<v3-7-26,26>>^ Onde quer que vocês vivam, não comam o sangue de nenhuma ave nem de animal.

[[v3-7-27]]

^<<v3-7-27,27>>^ Quem comer sangue será eliminado do meio do seu povo".

[[v3-7-28]]

^<<v3-7-28,28>>^ Disse mais o Senhor a Moisés:

[[v3-7-29]]

^<<v3-7-29,29>>^ "Diga aos israelitas: Todo aquele que trouxer sacrifício de comunhão ao Senhor terá que dedicar parte dele ao Senhor.

[[v3-7-30]]

^<<v3-7-30,30>>^ Com suas próprias mãos trará ao Senhor as ofertas preparadas no fogo; trará a gordura juntamente com o peito, e o moverá perante o Senhor como gesto ritual de apresentação.

[[v3-7-31]]

^<<v3-7-31,31>>^ O sacerdote queimará a gordura no altar, mas o peito pertence a Arão e a seus descendentes.

[[v3-7-32]]

^<<v3-7-32,32>>^ Vocês deverão dar a coxa direita das ofertas de comunhão ao sacerdote como contribuição.

[[v3-7-33]]

^<<v3-7-33,33>>^ O descendente de Arão que oferecer o sangue e a gordura da oferta de comunhão receberá a coxa direita como porção.

[[v3-7-34]]

^<<v3-7-34,34>>^ Das ofertas de comunhão dos israelitas, tomei o peito que é movido ritualmente e a coxa que é ofertada, e os dei ao sacerdote Arão e a seus descendentes por decreto perpétuo para os israelitas".

[[v3-7-35]]

^<<v3-7-35,35>>^ Essa é a parte das ofertas dedicadas ao Senhor, preparadas no fogo, designada a Arão e a seus filhos no dia em que foram apresentados para servirem ao Senhor como sacerdotes.

[[v3-7-36]]

^<<v3-7-36,36>>^ Foi isso que o Senhor ordenou dar a eles, no dia em que foram ungidos dentre os israelitas. É um decreto perpétuo para as suas gerações.

[[v3-7-37]]

^<<v3-7-37,37>>^ Essa é a regulamentação acerca do holocausto, da oferta de cereal, da oferta pelo pecado, da oferta pela culpa, da oferta de ordenação e da oferta de comunhão.

[[v3-7-38]]

^<<v3-7-38,38>>^ O Senhor entregou-a a Moisés no monte Sinai, no dia em que ordenou aos israelitas que trouxessem suas ofertas ao Senhor, no deserto do Sinai.

'''

xref:003-levitico/003-levitico-006.adoc#v3-6-0[&#60; Capítulo Anterior] | <<v3-7-0,Topo>> | xref:003-levitico/003-levitico-008.adoc#v3-8-0[Próximo Capítulo &#62;]