include::./index.adoc[]

[[v3-5-0]]
=== Levítico, 5
// nvi ?, NVI - Nova Versão Internacional

[[v3-5-1]]

^<<v3-5-1,1>>^ "Se alguém pecar porque, tendo sido testemunha de algo que viu ou soube, não o declarou, sofrerá as conseqüências da sua iniqüidade.

[[v3-5-2]]

^<<v3-5-2,2>>^ "Se alguém tocar qualquer coisa impura, seja um cadáver de animal selvagem ou de animal do rebanho ou de uma das pequenas criaturas que povoam a terra, ainda que não tenha consciência disso, ele se tornará impuro e será culpado.

[[v3-5-3]]

^<<v3-5-3,3>>^ "Se alguém tocar impureza humana, qualquer coisa que o torne impuro, sem ter consciência disso, quando o souber será culpado.

[[v3-5-4]]

^<<v3-5-4,4>>^ "Se alguém impensadamente jurar fazer algo bom ou mau, em qualquer assunto que alguém possa jurar descuidadamente, ainda que não tenha consciência disso, quando o souber será culpado.

[[v3-5-5]]

^<<v3-5-5,5>>^ "Quando alguém for culpado de qualquer dessas coisas, confessará em que pecou

[[v3-5-6]]

^<<v3-5-6,6>>^ e, pelo pecado que cometeu, trará ao Senhor uma ovelha ou uma cabra do rebanho como oferta de reparação; e em favor dele o sacerdote fará propiciação pelo pecado.

[[v3-5-7]]

^<<v3-5-7,7>>^ "Se não tiver recursos para oferecer uma ovelha, trará pela culpa do seu pecado duas rolinhas ou dois pombinhos ao Senhor: um como oferta pelo pecado e o outro como holocausto.

[[v3-5-8]]

^<<v3-5-8,8>>^ Ele os trará ao sacerdote, que oferecerá primeiro o que for oferecido como sacrifício pelo pecado. E destroncará o pescoço da ave, sem arrancar-lhe a cabeça totalmente,

[[v3-5-9]]

^<<v3-5-9,9>>^ e aspergirá no lado do altar o sangue da oferta pelo pecado e deixará escorrer o restante do sangue na base do altar. É oferta pelo pecado.

[[v3-5-10]]

^<<v3-5-10,10>>^ O sacerdote então oferecerá a outra ave como holocausto, de acordo com a forma prescrita, e fará propiciação em favor dele pelo pecado que cometeu, e ele será perdoado.

[[v3-5-11]]

^<<v3-5-11,11>>^ "Se, contudo, não tiver recursos para oferecer duas rolinhas ou dois pombinhos, trará como oferta pelo pecado um jarro da melhor farinha como oferta pelo pecado. Mas sobre ela não derramará óleo nem colocará incenso, porquanto é oferta pelo pecado.

[[v3-5-12]]

^<<v3-5-12,12>>^ Ele a trará ao sacerdote, que apanhará um punhado dela como porção memorial e queimará essa porção no altar, em cima das ofertas dedicadas ao Senhor, preparadas no fogo. É oferta pelo pecado.

[[v3-5-13]]

^<<v3-5-13,13>>^ Assim o sacerdote fará propiciação em favor dele por qualquer desses pecados que tiver cometido, e ele será perdoado. O restante da oferta pertence ao sacerdote, como no caso da oferta de cereal".

[[v3-5-14]]

^<<v3-5-14,14>>^ O Senhor disse a Moisés:

[[v3-5-15]]

^<<v3-5-15,15>>^ "Quando alguém cometer uma ofensa, pecando sem intenção em qualquer coisa consagrada ao Senhor, trará ao Senhor um carneiro do rebanho, sem defeito, avaliado em prata com base no peso padrão do santuário, como oferta pela culpa.

[[v3-5-16]]

^<<v3-5-16,16>>^ Fará restituição pelo que deixou de fazer em relação às coisas consagradas, acrescentará um quinto do valor e o entregará ao sacerdote. Este fará propiciação por ele com o carneiro da oferta pela culpa, e ele será perdoado.

[[v3-5-17]]

^<<v3-5-17,17>>^ "Se alguém pecar, fazendo o que é proibido em qualquer dos mandamentos do Senhor, ainda que não o saiba, será culpado e sofrerá as conseqüências da sua iniqüidade.

[[v3-5-18]]

^<<v3-5-18,18>>^ Do rebanho ele trará ao sacerdote um carneiro, sem defeito e devidamente avaliado, como oferta pela culpa. Assim o sacerdote fará propiciação em favor dele pelo erro que cometeu sem intenção, e ele será perdoado.

[[v3-5-19]]

^<<v3-5-19,19>>^ É oferta pela culpa, pois com certeza tornou-se culpado perante o Senhor".

'''

xref:003-levitico/003-levitico-004.adoc#v3-4-0[&#60; Capítulo Anterior] | <<v3-5-0,Topo>> | xref:003-levitico/003-levitico-006.adoc#v3-6-0[Próximo Capítulo &#62;]