include::./index.adoc[]

[[v3-8-0]]
=== Levítico, 8
// nvi ?, NVI - Nova Versão Internacional

[[v3-8-1]]

^<<v3-8-1,1>>^ O Senhor disse a Moisés:

[[v3-8-2]]

^<<v3-8-2,2>>^ "Traga Arão e seus filhos, suas vestes, o óleo da unção, o novilho para a oferta pelo pecado, os dois carneiros e o cesto de pães sem fermento;

[[v3-8-3]]

^<<v3-8-3,3>>^ e reúna toda a comunidade à entrada da Tenda do Encontro".

[[v3-8-4]]

^<<v3-8-4,4>>^ Moisés fez como o Senhor lhe ordenou, e a comunidade reuniu-se à entrada da Tenda do Encontro.

[[v3-8-5]]

^<<v3-8-5,5>>^ Então Moisés disse à comunidade: "Foi isto que o Senhor mandou fazer";

[[v3-8-6]]

^<<v3-8-6,6>>^ e levou Arão e seus filhos à frente e mandou-os banhar-se com água;

[[v3-8-7]]

^<<v3-8-7,7>>^ pôs a túnica em Arão, colocou-lhe o cinto e o manto, e pôs sobre ele o colete sacerdotal; depois a ele prendeu o manto sacerdotal com o cinturão;

[[v3-8-8]]

^<<v3-8-8,8>>^ colocou também o peitoral, e nele pôs o Urim e o Tumim;

[[v3-8-9]]

^<<v3-8-9,9>>^ e colocou o turbante na cabeça de Arão com a lâmina de ouro, isto é, a coroa sagrada, na frente do turbante, conforme o Senhor tinha ordenado a Moisés.

[[v3-8-10]]

^<<v3-8-10,10>>^ Depois Moisés pegou o óleo da unção e ungiu o tabernáculo e tudo o que nele havia, e assim os consagrou.

[[v3-8-11]]

^<<v3-8-11,11>>^ Aspergiu sete vezes o óleo sobre o altar, ungindo o altar e todos os seus utensílios e a bacia com o seu suporte, para consagrá-los.

[[v3-8-12]]

^<<v3-8-12,12>>^ Derramou o óleo da unção sobre a cabeça de Arão para ungi-lo e consagrá-lo.

[[v3-8-13]]

^<<v3-8-13,13>>^ Trouxe então os filhos de Arão à frente, vestiu-os com suas túnicas e cintos, e colocou-lhes gorros, conforme o Senhor lhe havia ordenado.

[[v3-8-14]]

^<<v3-8-14,14>>^ Em seguida trouxe o novilho para a oferta pelo pecado, e Arão e seus filhos puseram-lhe as mãos sobre a cabeça.

[[v3-8-15]]

^<<v3-8-15,15>>^ Moisés sacrificou o novilho, e com o dedo pôs um pouco do sangue em todas as pontas do altar para purificá-lo. Derramou o restante do sangue na base do altar e assim o consagrou para fazer propiciação por ele.

[[v3-8-16]]

^<<v3-8-16,16>>^ Moisés pegou também toda a gordura que cobre as vísceras, o lóbulo do fígado e os dois rins com a gordura que os cobre, e os queimou no altar.

[[v3-8-17]]

^<<v3-8-17,17>>^ Mas o novilho com o seu couro, a sua carne e o seu excremento, ele os queimou fora do acampamento, conforme o Senhor lhe havia ordenado.

[[v3-8-18]]

^<<v3-8-18,18>>^ Mandou trazer então o carneiro para o holocausto, e Arão e seus filhos puseram as mãos sobre a cabeça do carneiro.

[[v3-8-19]]

^<<v3-8-19,19>>^ A seguir Moisés sacrificou o carneiro e derramou o sangue nos lados do altar.

[[v3-8-20]]

^<<v3-8-20,20>>^ Depois, cortou o carneiro em pedaços; queimou a cabeça, os pedaços e a gordura.

[[v3-8-21]]

^<<v3-8-21,21>>^ Lavou as vísceras e as pernas, e queimou o carneiro inteiro sobre o altar, como holocausto, oferta de aroma agradável ao Senhor, preparado no fogo, conforme o Senhor lhe havia ordenado.

[[v3-8-22]]

^<<v3-8-22,22>>^ Depois mandou trazer o outro carneiro, o carneiro para a oferta de ordenação, e Arão e seus filhos colocaram as mãos sobre a cabeça do carneiro.

[[v3-8-23]]

^<<v3-8-23,23>>^ Moisés sacrificou o carneiro e pôs um pouco do sangue na ponta da orelha direita de Arão, no polegar da sua mão direita e no polegar do seu pé direito.

[[v3-8-24]]

^<<v3-8-24,24>>^ Moisés também mandou que os filhos de Arão se aproximassem, e sobre cada um pôs um pouco do sangue na ponta da orelha direita, no polegar da mão direita e no polegar do pé direito; e derramou o restante do sangue nos lados do altar.

[[v3-8-25]]

^<<v3-8-25,25>>^ Apanhou a gordura, a cauda gorda, toda a gordura que cobre as vísceras, o lóbulo do fígado, os dois rins e a gordura que os cobre e a coxa direita.

[[v3-8-26]]

^<<v3-8-26,26>>^ Então, do cesto de pães sem fermento, que estava perante o Senhor, apanhou um pão comum, outro feito com óleo e um pão fino, colocando-os sobre as porções de gordura e sobre a coxa direita.

[[v3-8-27]]

^<<v3-8-27,27>>^ Pôs tudo nas mãos de Arão e de seus filhos e os moveu perante o Senhor como gesto ritual de apresentação.

[[v3-8-28]]

^<<v3-8-28,28>>^ Depois Moisés pegou de volta das mãos deles e queimou tudo no altar, em cima do holocausto, como uma oferta de ordenação, preparada no fogo, de aroma agradável ao Senhor.

[[v3-8-29]]

^<<v3-8-29,29>>^ Moisés também pegou o peito e a sua própria porção do carneiro da ordenação, e o moveu perante o Senhor como gesto ritual de apresentação, como o Senhor lhe havia ordenado.

[[v3-8-30]]

^<<v3-8-30,30>>^ Então pegou um pouco do óleo da unção e um pouco do sangue que estava no altar e os aspergiu sobre Arão e suas vestes, bem como sobre seus filhos e suas vestes. Assim consagrou Arão e suas vestes, e seus filhos e suas vestes.

[[v3-8-31]]

^<<v3-8-31,31>>^ Moisés então disse a Arão e a seus filhos: "Cozinhem a carne na entrada da Tenda do Encontro, onde a deverão comer com o pão do cesto das ofertas de ordenação, conforme me foi ordenado: ‘Arão e seus filhos deverão comê-la’.

[[v3-8-32]]

^<<v3-8-32,32>>^ Depois queimem o restante da carne e do pão.

[[v3-8-33]]

^<<v3-8-33,33>>^ Não saiam da entrada da Tenda do Encontro por sete dias, até que se completem os dias da ordenação de vocês, pois essa cerimônia de ordenação durará sete dias.

[[v3-8-34]]

^<<v3-8-34,34>>^ O que se fez hoje foi ordenado pelo Senhor para fazer propiciação por vocês.

[[v3-8-35]]

^<<v3-8-35,35>>^ Vocês terão que permanecer dia e noite à entrada da Tenda do Encontro por sete dias e obedecer às exigências do Senhor, para que não morram; pois isso me foi ordenado".

[[v3-8-36]]

^<<v3-8-36,36>>^ Arão e seus filhos fizeram tudo o que o Senhor tinha ordenado por meio de Moisés.

'''

xref:003-levitico/003-levitico-007.adoc#v3-7-0[&#60; Capítulo Anterior] | <<v3-8-0,Topo>> | xref:003-levitico/003-levitico-009.adoc#v3-9-0[Próximo Capítulo &#62;]