include::./index.adoc[]

[[v3-14-0]]
=== Levítico, 14
// nvi ?, NVI - Nova Versão Internacional

[[v3-14-1]]

^<<v3-14-1,1>>^ Disse também o Senhor a Moisés:

[[v3-14-2]]

^<<v3-14-2,2>>^ "Esta é a regulamentação acerca da purificação de um leproso: ele será levado ao sacerdote,

[[v3-14-3]]

^<<v3-14-3,3>>^ que sairá do acampamento e o examinará. Se a pessoa foi curada da lepra,

[[v3-14-4]]

^<<v3-14-4,4>>^ o sacerdote ordenará que duas aves puras, vivas, um pedaço de madeira de cedro, um pano vermelho e um ramo de hissopo sejam trazidos em favor daquele que será purificado.

[[v3-14-5]]

^<<v3-14-5,5>>^ Então o sacerdote ordenará que uma das aves seja morta numa vasilha de barro com água da fonte.

[[v3-14-6]]

^<<v3-14-6,6>>^ Então pegará a ave viva e a molhará, juntamente com o pedaço de madeira de cedro, com o pano vermelho e com o ramo de hissopo, no sangue da ave morta em água corrente.

[[v3-14-7]]

^<<v3-14-7,7>>^ Sete vezes ele aspergirá aquele que está sendo purificado da lepra e o declarará puro. Depois soltará a ave viva em campo aberto.

[[v3-14-8]]

^<<v3-14-8,8>>^ "Aquele que estiver sendo purificado lavará as suas roupas, rapará todos os seus pêlos e se banhará com água; e assim estará puro. Depois disso poderá entrar no acampamento, mas ficará fora da sua tenda por sete dias.

[[v3-14-9]]

^<<v3-14-9,9>>^ No sétimo dia rapará todos os seus pêlos: o cabelo, a barba, as sobrancelhas e o restante dos pêlos. Lavará suas roupas e banhará o corpo com água; então ficará puro.

[[v3-14-10]]

^<<v3-14-10,10>>^ "No oitavo dia pegará dois cordeiros sem defeito e uma cordeira de um ano sem defeito, juntamente com três jarros da melhor farinha amassada com óleo, como oferta de cereal, e uma caneca de óleo.

[[v3-14-11]]

^<<v3-14-11,11>>^ O sacerdote que faz a purificação apresentará ao Senhor, à entrada da Tenda do Encontro, tanto aquele que estiver para ser purificado como as suas ofertas.

[[v3-14-12]]

^<<v3-14-12,12>>^ "Então o sacerdote pegará um dos cordeiros e o sacrificará como oferta pela culpa, juntamente com a caneca de óleo; ele os moverá perante o Senhor como gesto ritual de apresentação e

[[v3-14-13]]

^<<v3-14-13,13>>^ matará o cordeiro no Lugar Santo, onde são sacrificados a oferta pelo pecado e o holocausto. Como se dá com a oferta pelo pecado, também a oferta pela culpa pertence ao sacerdote; é santíssima.

[[v3-14-14]]

^<<v3-14-14,14>>^ O sacerdote porá um pouco do sangue da oferta pela culpa na ponta da orelha direita daquele que será purificado, no polegar da sua mão direita e no polegar do seu pé direito.

[[v3-14-15]]

^<<v3-14-15,15>>^ Então o sacerdote pegará um pouco de óleo da caneca e o derramará na palma da sua própria mão esquerda,

[[v3-14-16]]

^<<v3-14-16,16>>^ molhará o dedo direito no óleo que está na palma da mão esquerda, e com o dedo o aspergirá sete vezes perante o Senhor.

[[v3-14-17]]

^<<v3-14-17,17>>^ O sacerdote ainda porá um pouco do óleo restante na palma da sua mão, na ponta da orelha direita daquele que está sendo purificado, no polegar da sua mão direita e no polegar do seu pé direito, em cima do sangue da oferta pela culpa.

[[v3-14-18]]

^<<v3-14-18,18>>^ O óleo que restar na palma da sua mão, o sacerdote derramará sobre a cabeça daquele que está sendo purificado e fará propiciação por ele perante o Senhor.

[[v3-14-19]]

^<<v3-14-19,19>>^ "Então o sacerdote sacrificará a oferta pelo pecado e fará propiciação em favor daquele que está sendo purificado da sua impureza. Depois disso, o sacerdote matará o animal do holocausto

[[v3-14-20]]

^<<v3-14-20,20>>^ e o oferecerá sobre o altar, juntamente com a oferta de cereal; e assim fará propiciação pelo ofertante, o qual estará puro.

[[v3-14-21]]

^<<v3-14-21,21>>^ "Se, todavia, for alguém pobre, sem recursos para isso, pegará um cordeiro como oferta pela culpa para ser movido para fazer propiciação por ele, juntamente com um jarro da melhor farinha, amassada com óleo, como oferta de cereal; uma caneca de óleo

[[v3-14-22]]

^<<v3-14-22,22>>^ e duas rolinhas ou dois pombinhos, os quais ele tenha condições de ofertar, um como oferta pelo pecado e o outro como holocausto.

[[v3-14-23]]

^<<v3-14-23,23>>^ "No oitavo dia ele os trará ao sacerdote, para a sua purificação, à entrada da Tenda do Encontro, perante o Senhor.

[[v3-14-24]]

^<<v3-14-24,24>>^ O sacerdote pegará o cordeiro da oferta pela culpa, juntamente com uma caneca de óleo, e os moverá perante o Senhor como gesto ritual de apresentação.

[[v3-14-25]]

^<<v3-14-25,25>>^ Matará o cordeiro da oferta pela culpa e pegará um pouco do sangue e o porá na ponta da orelha direita daquele que está sendo purificado, no polegar da sua mão direita e no polegar do seu pé direito.

[[v3-14-26]]

^<<v3-14-26,26>>^ O sacerdote derramará um pouco do óleo na palma da sua mão esquerda,

[[v3-14-27]]

^<<v3-14-27,27>>^ e com o dedo indicador direito aspergirá um pouco do óleo da palma da sua mão esquerda sete vezes perante o Senhor.

[[v3-14-28]]

^<<v3-14-28,28>>^ Ele porá o óleo da palma da sua mão nos mesmos lugares em que pôs o sangue da oferta pela culpa: na ponta da orelha direita daquele que está sendo purificado, no polegar da sua mão direita e no polegar do seu pé direito.

[[v3-14-29]]

^<<v3-14-29,29>>^ O que restar do óleo na palma da sua mão, o sacerdote derramará sobre a cabeça daquele que está sendo purificado, para fazer propiciação por ele perante o Senhor.

[[v3-14-30]]

^<<v3-14-30,30>>^ Depois sacrificará uma das rolinhas ou um dos pombinhos, os quais a pessoa tem condições de ofertar,

[[v3-14-31]]

^<<v3-14-31,31>>^ um como oferta pelo pecado e o outro como holocausto, juntamente com a oferta de cereal. Assim o sacerdote fará propiciação perante o Senhor em favor daquele que está sendo purificado".

[[v3-14-32]]

^<<v3-14-32,32>>^ Essa é a regulamentação para todo aquele que tem lepra e não tem recursos para fazer a oferta da sua purificação.

[[v3-14-33]]

^<<v3-14-33,33>>^ O Senhor disse a Moisés e a Arão:

[[v3-14-34]]

^<<v3-14-34,34>>^ "Quando vocês entrarem na terra de Canaã, que lhes dou como propriedade, e eu puser mancha de mofo numa casa, na terra que lhes pertence,

[[v3-14-35]]

^<<v3-14-35,35>>^ o dono da casa irá ao sacerdote e dirá: ‘Parece-me que há mancha de mofo em minha casa’.

[[v3-14-36]]

^<<v3-14-36,36>>^ Antes de examinar o mofo, o sacerdote ordenará que desocupem a casa para que nada que houver na casa se torne impuro. Depois disso, o sacerdote irá examinar a casa.

[[v3-14-37]]

^<<v3-14-37,37>>^ Examinará as manchas nas paredes, e, se elas forem esverdeadas ou avermelhadas e parecerem mais profundas do que a superfície da parede,

[[v3-14-38]]

^<<v3-14-38,38>>^ o sacerdote sairá da casa e a deixará fechada por sete dias.

[[v3-14-39]]

^<<v3-14-39,39>>^ No sétimo dia voltará para examinar a casa. Se as manchas se houverem espalhado pelas paredes da casa,

[[v3-14-40]]

^<<v3-14-40,40>>^ ordenará que as pedras contaminadas pelas manchas sejam retiradas e jogadas num local impuro, fora da cidade.

[[v3-14-41]]

^<<v3-14-41,41>>^ Fará que a casa seja raspada por dentro e que o reboco raspado seja jogado num local impuro, fora da cidade.

[[v3-14-42]]

^<<v3-14-42,42>>^ Depois colocarão outras pedras no lugar das primeiras, e rebocarão a casa com barro novo.

[[v3-14-43]]

^<<v3-14-43,43>>^ "Se as manchas tornarem a alastrar-se na casa depois de retiradas as pedras e de raspada e rebocada a casa,

[[v3-14-44]]

^<<v3-14-44,44>>^ o sacerdote irá examiná-la, e, se as manchas se espalharam pela casa, é mofo corrosivo; a casa está impura.

[[v3-14-45]]

^<<v3-14-45,45>>^ Ela terá que ser demolida: as pedras, as madeiras e todo o reboco da casa; tudo será levado para um local impuro, fora da cidade.

[[v3-14-46]]

^<<v3-14-46,46>>^ "Quem entrar na casa enquanto estiver fechada estará impuro até à tarde.

[[v3-14-47]]

^<<v3-14-47,47>>^ Aquele que dormir ou comer na casa terá que lavar as suas roupas.

[[v3-14-48]]

^<<v3-14-48,48>>^ "Mas, se o sacerdote for examiná-la e as manchas não se houverem espalhado depois de rebocada a casa, declarará pura a casa, pois as manchas de mofo desapareceram.

[[v3-14-49]]

^<<v3-14-49,49>>^ Para purificar a casa, ele pegará duas aves, um pedaço de madeira de cedro, um pano vermelho e hissopo.

[[v3-14-50]]

^<<v3-14-50,50>>^ Depois matará uma das aves numa vasilha de barro com água da fonte.

[[v3-14-51]]

^<<v3-14-51,51>>^ Então pegará o pedaço de madeira de cedro, o hissopo, o pano vermelho e a ave viva, e os molhará no sangue da ave morta e na água da fonte, e aspergirá a casa sete vezes.

[[v3-14-52]]

^<<v3-14-52,52>>^ Ele purificará a casa com o sangue da ave, com a água da fonte, com a ave viva, com o pedaço de madeira de cedro, com o hissopo e com o pano vermelho.

[[v3-14-53]]

^<<v3-14-53,53>>^ Depois soltará a ave viva em campo aberto, fora da cidade. Assim fará propiciação pela casa, que ficará pura".

[[v3-14-54]]

^<<v3-14-54,54>>^ Essa é a regulamentação acerca de qualquer tipo de lepra, de sarna,

[[v3-14-55]]

^<<v3-14-55,55>>^ de mofo nas roupas ou numa casa

[[v3-14-56]]

^<<v3-14-56,56>>^ e de inchaço, erupção ou mancha brilhante,

[[v3-14-57]]

^<<v3-14-57,57>>^ para se determinar quando uma coisa é pura ou impura. Essa é a regulamentação acerca de qualquer tipo de lepra e de mofo.

'''

xref:003-levitico/003-levitico-013.adoc#v3-13-0[&#60; Capítulo Anterior] | <<v3-14-0,Topo>> | xref:003-levitico/003-levitico-015.adoc#v3-15-0[Próximo Capítulo &#62;]