include::./index.adoc[]

[[v3-3-0]]
=== Levítico, 3
// nvi ?, NVI - Nova Versão Internacional

[[v3-3-1]]

^<<v3-3-1,1>>^ "Quando a oferta de alguém for sacrifício de comunhão, assim se fará: se oferecer um animal do gado, seja macho ou fêmea, apresentará ao Senhor um animal sem defeito.

[[v3-3-2]]

^<<v3-3-2,2>>^ Porá a mão sobre a cabeça do animal, que será morto na entrada da Tenda do Encontro. Os descendentes de Arão, os sacerdotes, derramarão o sangue nos lados do altar.

[[v3-3-3]]

^<<v3-3-3,3>>^ Desse sacrifício de comunhão, oferta preparada no fogo, ele trará ao Senhor toda a gordura que cobre as vísceras e está ligada a elas,

[[v3-3-4]]

^<<v3-3-4,4>>^ os dois rins com a gordura que os cobre e que está perto dos lombos, e o lóbulo do fígado, que ele removerá junto com os rins.

[[v3-3-5]]

^<<v3-3-5,5>>^ Os descendentes de Arão queimarão tudo isso em cima do holocausto que está sobre a lenha acesa no altar como oferta preparada no fogo, de aroma agradável ao Senhor.

[[v3-3-6]]

^<<v3-3-6,6>>^ "Se oferecer um animal do rebanho como sacrifício de comunhão ao Senhor, traga um macho ou fêmea sem defeito.

[[v3-3-7]]

^<<v3-3-7,7>>^ Se oferecer um cordeiro, apresente-o ao Senhor.

[[v3-3-8]]

^<<v3-3-8,8>>^ Porá a mão sobre a cabeça do animal, que será morto diante da Tenda do Encontro. Então os descendentes de Arão derramarão o sangue nos lados do altar.

[[v3-3-9]]

^<<v3-3-9,9>>^ Desse sacrifício de comunhão, oferta preparada no fogo, ele trará ao Senhor a gordura, tanto a da cauda gorda cortada rente à espinha, como toda a gordura que cobre as vísceras e está ligada a elas,

[[v3-3-10]]

^<<v3-3-10,10>>^ os dois rins com a gordura que os cobre e que está perto dos lombos, e o lóbulo do fígado, que ele removerá junto com os rins.

[[v3-3-11]]

^<<v3-3-11,11>>^ O sacerdote os queimará no altar como alimento oferecido ao Senhor, preparado no fogo.

[[v3-3-12]]

^<<v3-3-12,12>>^ "Se a sua oferta for um cabrito, ele o apresentará ao Senhor.

[[v3-3-13]]

^<<v3-3-13,13>>^ Porá a mão sobre a cabeça do animal, que será morto diante da Tenda do Encontro. Então os descendentes de Arão derramarão o sangue nos lados do altar.

[[v3-3-14]]

^<<v3-3-14,14>>^ Desse animal, que é uma oferta preparada no fogo, trará ao Senhor a gordura que cobre as vísceras e está ligada a elas,

[[v3-3-15]]

^<<v3-3-15,15>>^ os dois rins com a gordura que os cobre e que está perto dos lombos, e o lóbulo do fígado, que ele removerá junto com os rins.

[[v3-3-16]]

^<<v3-3-16,16>>^ O sacerdote os queimará no altar como alimento, como oferta feita com fogo, de aroma agradável. Toda a gordura será do Senhor.

[[v3-3-17]]

^<<v3-3-17,17>>^ "Este é um decreto perpétuo para as suas gerações, onde quer que vivam: Não comam gordura alguma, nem sangue algum".

'''

xref:003-levitico/003-levitico-002.adoc#v3-2-0[&#60; Capítulo Anterior] | <<v3-3-0,Topo>> | xref:003-levitico/003-levitico-004.adoc#v3-4-0[Próximo Capítulo &#62;]