include::./index.adoc[]

[[v3-22-0]]
=== Levítico, 22
// nvi ?, NVI - Nova Versão Internacional

[[v3-22-1]]

^<<v3-22-1,1>>^ Disse o Senhor a Moisés:

[[v3-22-2]]

^<<v3-22-2,2>>^ "Diga a Arão e a seus filhos que tratem com respeito as ofertas sagradas que os israelitas me consagrarem, para que não profanem o meu santo nome. Eu sou o Senhor.

[[v3-22-3]]

^<<v3-22-3,3>>^ "Avise-lhes que se, em suas futuras gerações, algum dos seus descendentes estiver impuro quando se aproximar das ofertas sagradas que os israelitas consagrarem ao Senhor, será eliminado da minha presença. Eu sou o Senhor.

[[v3-22-4]]

^<<v3-22-4,4>>^ "Nenhum descendente de Arão que tenha lepra ou fluxo no corpo poderá comer das ofertas sagradas até que esteja purificado. Também estará impuro se tocar em algo contaminado por um cadáver, ou se lhe sair o sêmen,

[[v3-22-5]]

^<<v3-22-5,5>>^ ou se tocar em alguma criatura, ou em alguém que o torne impuro, seja qual for a impureza.

[[v3-22-6]]

^<<v3-22-6,6>>^ Aquele que neles tocar ficará impuro até à tarde. Não poderá comer das ofertas sagradas, a menos que se tenha banhado com água.

[[v3-22-7]]

^<<v3-22-7,7>>^ Depois do pôr do sol estará puro, e então poderá comer as ofertas sagradas, pois são o seu alimento.

[[v3-22-8]]

^<<v3-22-8,8>>^ Também não poderá comer animal encontrado morto ou despedaçado por animais selvagens, pois se tornaria impuro por causa deles. Eu sou o Senhor.

[[v3-22-9]]

^<<v3-22-9,9>>^ "Os sacerdotes obedecerão aos meus preceitos, para que não sofram as conseqüências do seu pecado nem sejam executados por tê-los profanado. Eu sou o Senhor, que os santifico.

[[v3-22-10]]

^<<v3-22-10,10>>^ "Somente o sacerdote e a sua família poderão comer da oferta sagrada; não poderá comê-la o seu hóspede, nem o seu empregado.

[[v3-22-11]]

^<<v3-22-11,11>>^ Mas, se um sacerdote comprar um escravo, ou se um escravo nascer em sua casa, esse escravo poderá comer do seu alimento.

[[v3-22-12]]

^<<v3-22-12,12>>^ Se a filha de um sacerdote se casar com alguém que não seja sacerdote, não poderá comer das ofertas sagradas.

[[v3-22-13]]

^<<v3-22-13,13>>^ Mas, se a filha de um sacerdote ficar viúva ou se divorciar, e não tiver filhos, e voltar a viver na casa do pai como na sua juventude, poderá comer do alimento do pai, mas dele não poderá comer ninguém que não seja da família do sacerdote.

[[v3-22-14]]

^<<v3-22-14,14>>^ "Se alguém, sem intenção, comer uma oferta sagrada, fará restituição da oferta ao sacerdote e lhe acrescentará um quinto do seu valor.

[[v3-22-15]]

^<<v3-22-15,15>>^ "Os sacerdotes não profanarão as ofertas sagradas que os israelitas apresentam ao Senhor,

[[v3-22-16]]

^<<v3-22-16,16>>^ permitindo-lhes comê-las e trazendo assim sobre eles culpa que exige reparação. Eu sou o Senhor que os santifico".

[[v3-22-17]]

^<<v3-22-17,17>>^ Disse o Senhor a Moisés:

[[v3-22-18]]

^<<v3-22-18,18>>^ "Diga o seguinte a Arão e a seus filhos e a todos os israelitas: Se algum de vocês, seja israelita, seja estrangeiro residente em Israel, apresentar uma oferta como holocausto ao Senhor, quer para cumprir voto, quer como oferta voluntária,

[[v3-22-19]]

^<<v3-22-19,19>>^ apresentará um macho sem defeito do rebanho, boi, carneiro ou bode, a fim de que seja aceita em seu favor.

[[v3-22-20]]

^<<v3-22-20,20>>^ Não tragam nenhum animal defeituoso, porque não será aceito em favor de vocês.

[[v3-22-21]]

^<<v3-22-21,21>>^ Quando alguém trouxer um animal do gado ou do rebanho de ovelhas como oferta de comunhão para o Senhor, em cumprimento de voto, ou como oferta voluntária, para ser aceitável o animal terá que ser sem defeito e sem mácula.

[[v3-22-22]]

^<<v3-22-22,22>>^ Não ofereçam ao Senhor animal cego, aleijado, mutilado, ulceroso, cheio de feridas purulentas ou com fluxo. Não coloquem nenhum desses animais sobre o altar como oferta ao Senhor, preparada no fogo.

[[v3-22-23]]

^<<v3-22-23,23>>^ Todavia, poderão apresentar como oferta voluntária um boi ou um carneiro ou um cabrito deformados ou atrofiados, mas no caso do cumprimento de voto não serão aceitos.

[[v3-22-24]]

^<<v3-22-24,24>>^ Não poderão oferecer ao Senhor um animal cujos testículos estejam machucados, esmagados, despedaçados ou cortados. Não façam isso em sua própria terra,

[[v3-22-25]]

^<<v3-22-25,25>>^ nem aceitem animais como esses das mãos de um estrangeiro para oferecê-los como alimento do seu Deus. Não serão aceitos em favor de vocês, pois são deformados e apresentam defeitos".

[[v3-22-26]]

^<<v3-22-26,26>>^ Disse ainda o Senhor a Moisés:

[[v3-22-27]]

^<<v3-22-27,27>>^ "Quando nascer um bezerro, um cordeiro ou um cabrito, ficará sete dias com sua mãe. Do oitavo dia em diante será aceito como oferta ao Senhor preparada no fogo.

[[v3-22-28]]

^<<v3-22-28,28>>^ Não matem uma vaca ou uma ovelha ou uma cabra e sua cria no mesmo dia.

[[v3-22-29]]

^<<v3-22-29,29>>^ "Quando vocês oferecerem um sacrifício de gratidão ao Senhor, ofereçam-no de maneira que seja aceito em favor de vocês.

[[v3-22-30]]

^<<v3-22-30,30>>^ Será comido naquele mesmo dia; não deixem nada até a manhã seguinte. Eu sou o Senhor.

[[v3-22-31]]

^<<v3-22-31,31>>^ "Obedeçam aos meus mandamentos e os coloquem em prática. Eu sou o Senhor.

[[v3-22-32]]

^<<v3-22-32,32>>^ Não profanem o meu santo nome. Eu serei reconhecido como santo pelos israelitas. Eu sou o Senhor que os santifico

[[v3-22-33]]

^<<v3-22-33,33>>^ e que os tirou do Egito para ser o Deus de vocês. Eu sou o Senhor".

'''

xref:003-levitico/003-levitico-021.adoc#v3-21-0[&#60; Capítulo Anterior] | <<v3-22-0,Topo>> | xref:003-levitico/003-levitico-023.adoc#v3-23-0[Próximo Capítulo &#62;]