include::./index.adoc[]

[[v3-2-0]]
=== Levítico, 2
// nvi ?, NVI - Nova Versão Internacional

[[v3-2-1]]

^<<v3-2-1,1>>^ "Quando alguém trouxer uma oferta de cereal ao Senhor, terá que ser da melhor farinha. Sobre ela derramará óleo, colocará incenso

[[v3-2-2]]

^<<v3-2-2,2>>^ e a levará aos descendentes de Arão, os sacerdotes. Um deles apanhará um punhado da melhor farinha com óleo, juntamente com todo o incenso, e o queimará no altar como porção memorial. É oferta preparada no fogo, de aroma agradável ao Senhor.

[[v3-2-3]]

^<<v3-2-3,3>>^ O que restar da oferta de cereal pertence a Arão e a seus descendentes; é parte santíssima das ofertas dedicadas ao Senhor preparadas no fogo.

[[v3-2-4]]

^<<v3-2-4,4>>^ "Se um de vocês trouxer uma oferta de cereal assada no forno, seja da melhor farinha: bolos feitos sem fermento, amassados com óleo, ou pães finos sem fermento e untados com óleo.

[[v3-2-5]]

^<<v3-2-5,5>>^ Se a sua oferta de cereal for preparada numa assadeira, seja da melhor farinha, amassada com óleo e sem fermento.

[[v3-2-6]]

^<<v3-2-6,6>>^ Divida-as em pedaços e derrame óleo sobre ela; é uma oferta de cereal.

[[v3-2-7]]

^<<v3-2-7,7>>^ Se a sua oferta de cereal for cozida numa panela, seja da melhor farinha com óleo.

[[v3-2-8]]

^<<v3-2-8,8>>^ Traga ao Senhor a oferta de cereal feita desses ingredientes, apresente-a ao sacerdote, que a levará ao altar.

[[v3-2-9]]

^<<v3-2-9,9>>^ Ele apanhará a porção memorial da oferta de cereal e a queimará no altar; é oferta preparada no fogo, de aroma agradável ao Senhor.

[[v3-2-10]]

^<<v3-2-10,10>>^ O restante da oferta de cereal pertence a Arão e a seus descendentes; é parte santíssima das ofertas dedicadas ao Senhor preparadas no fogo.

[[v3-2-11]]

^<<v3-2-11,11>>^ "Nenhuma oferta de cereal que vocês trouxerem ao Senhor será feita com fermento, pois vocês não queimarão fermento nem mel como oferta preparada no fogo ao Senhor.

[[v3-2-12]]

^<<v3-2-12,12>>^ Podem trazê-los como oferta dos primeiros frutos ao Senhor, mas não poderão oferecê-los no altar como aroma agradável.

[[v3-2-13]]

^<<v3-2-13,13>>^ Tempere com sal todas as suas ofertas de cereal. Não exclua de suas ofertas de cereal o sal da aliança do seu Deus; acrescente sal a todas as suas ofertas.

[[v3-2-14]]

^<<v3-2-14,14>>^ "Se você trouxer ao Senhor uma oferta de cereal dos primeiros frutos, ofereça grãos esmagados de cereal novo, tostados no fogo.

[[v3-2-15]]

^<<v3-2-15,15>>^ Sobre ela derrame óleo e coloque incenso; é oferta de cereal.

[[v3-2-16]]

^<<v3-2-16,16>>^ O sacerdote queimará a porção memorial do cereal esmagado e do óleo, juntamente com todo o incenso, como uma oferta ao Senhor, preparada no fogo. "

'''

xref:003-levitico/003-levitico-001.adoc#v3-1-0[&#60; Capítulo Anterior] | <<v3-2-0,Topo>> | xref:003-levitico/003-levitico-003.adoc#v3-3-0[Próximo Capítulo &#62;]