include::./index.adoc[]

[[v28-14-0]]
=== Oséias, 14
// nvi ?, NVI - Nova Versão Internacional

[[v28-14-1]]

^<<v28-14-1,1>>^ Volte, ó Israel, para o Senhor, para o seu Deus. Seus pecados causaram sua queda!

[[v28-14-2]]

^<<v28-14-2,2>>^ Preparem o que vão dizer e voltem para o Senhor. Peçam-lhe: "Perdoa todos os nossos pecados e, por misericórdia, recebe-nos, para que te ofereçamos o fruto dos nossos lábios.

[[v28-14-3]]

^<<v28-14-3,3>>^ A Assíria não nos pode salvar; não montaremos cavalos de guerra. Nunca mais diremos: ‘Nossos deuses’ àquilo que as nossas próprias mãos fizeram, porque tu amas o órfão.

[[v28-14-4]]

^<<v28-14-4,4>>^ "Eu curarei a infidelidade deles e os amarei de todo o meu coração, pois a minha ira desviou-se deles.

[[v28-14-5]]

^<<v28-14-5,5>>^ Serei como orvalho para Israel; ele florescerá como o lírio. Como o cedro do Líbano aprofundará suas raízes;

[[v28-14-6]]

^<<v28-14-6,6>>^ seus brotos crescerão. Seu esplendor será como o da oliveira, sua fragrância como a do cedro do Líbano.

[[v28-14-7]]

^<<v28-14-7,7>>^ Os que habitavam à sua sombra voltarão. Reviverão como o trigo. Florescerão como a videira, e a fama de Israel será como o do vinho do Líbano.

[[v28-14-8]]

^<<v28-14-8,8>>^ O que Efraim ainda tem com ídolos? Sou eu que lhe respondo e dele cuidarei. Sou como um pinheiro verde; o fruto que você produz de mim procede".

[[v28-14-9]]

^<<v28-14-9,9>>^ Quem é sábio? Aquele que considerar essas coisas. Quem tem discernimento? Aquele que as compreender. Os caminhos do Senhor são justos; os justos andam neles, mas os rebeldes neles tropeçam.

'''

xref:028-oseias/028-oseias-013.adoc#v28-13-0[&#60; Capítulo Anterior] | <<v28-14-0,Topo>> | xref:029-joel/029-joel-001.adoc#v29-1-0[Próximo Capítulo &#62;]