include::./index.adoc[]

[[v28-6-0]]
=== Oséias, 6
// nvi ?, NVI - Nova Versão Internacional

[[v28-6-1]]

^<<v28-6-1,1>>^ "Venham, voltemos para o Senhor. Ele nos despedaçou, mas nos trará cura; ele nos feriu, mas sarará nossas feridas.

[[v28-6-2]]

^<<v28-6-2,2>>^ Depois de dois dias ele nos dará vida novamente; ao terceiro dia nos restaurará, para que vivamos em sua presença.

[[v28-6-3]]

^<<v28-6-3,3>>^ Conheçamos o Senhor; esforcemo-nos por conhecê-lo. Tão certo como nasce o sol, ele aparecerá; virá para nós como as chuvas de inverno, como as chuvas de primavera que regam a terra. "

[[v28-6-4]]

^<<v28-6-4,4>>^ "Que posso fazer com você, Efraim? Que posso fazer com você, Judá? Seu amor é como a neblina da manhã, como o primeiro orvalho que logo evapora.

[[v28-6-5]]

^<<v28-6-5,5>>^ Por isso eu os despedacei por meio dos meus profetas, eu os matei com as palavras da minha boca; os meus juízos reluziram como relâmpagos sobre vocês.

[[v28-6-6]]

^<<v28-6-6,6>>^ Pois desejo misericórdia, não sacrifícios, e conhecimento de Deus em vez de holocaustos.

[[v28-6-7]]

^<<v28-6-7,7>>^ Na cidade de Adão, eles quebraram a aliança, e me foram infiéis.

[[v28-6-8]]

^<<v28-6-8,8>>^ Gileade é uma cidade de ímpios, maculada de sangue.

[[v28-6-9]]

^<<v28-6-9,9>>^ Assim como os assaltantes ficam de emboscada à espera de um homem, assim fazem também os bandos de sacerdotes; eles assassinam na estrada de Siquém e cometem outros crimes vergonhosos.

[[v28-6-10]]

^<<v28-6-10,10>>^ Vi uma coisa terrível na terra de Israel. Ali Efraim se prostitui, e Israel está contaminado".

[[v28-6-11]]

^<<v28-6-11,11>>^ "Também para você, Judá, foi determinada uma colheita para quando eu trouxer de volta o meu povo.

'''

xref:028-oseias/028-oseias-005.adoc#v28-5-0[&#60; Capítulo Anterior] | <<v28-6-0,Topo>> | xref:028-oseias/028-oseias-007.adoc#v28-7-0[Próximo Capítulo &#62;]