include::./index.adoc[]

[[v28-2-0]]
=== Oséias, 2
// nvi ?, NVI - Nova Versão Internacional

[[v28-2-1]]

^<<v28-2-1,1>>^ "Chamem a seus irmãos ‘meu povo’, e a suas irmãs ‘minhas amadas’.

[[v28-2-2]]

^<<v28-2-2,2>>^ "Repreendam sua mãe, repreendam-na, pois ela não é minha mulher, e eu não sou seu marido. Retire ela do rosto a aparência adúltera e do meio dos seios a infidelidade.

[[v28-2-3]]

^<<v28-2-3,3>>^ Do contrário, eu a deixarei nua, como no dia em que nasceu; eu farei dela um deserto, eu a transformarei em terra ressequida, e a matarei de sede.

[[v28-2-4]]

^<<v28-2-4,4>>^ Não tratarei com amor os seus filhos, porque são filhos de adultério.

[[v28-2-5]]

^<<v28-2-5,5>>^ A mãe deles foi infiel, engravidou deles e está coberta de vergonha. Pois ela disse: ‘Irei atrás dos meus amantes, que me dão comida, água, lã, linho, azeite e bebida’.

[[v28-2-6]]

^<<v28-2-6,6>>^ Por isso bloquearei o caminho dela com espinheiros; eu a cercarei de tal modo que ela não poderá encontrar o seu caminho.

[[v28-2-7]]

^<<v28-2-7,7>>^ Ela correrá atrás dos seus amantes, mas não os alcançará; procurará por eles, mas não os encontrará. Então ela dirá: ‘Voltarei para o meu marido como no início, pois eu estava bem melhor do que agora’.

[[v28-2-8]]

^<<v28-2-8,8>>^ Ela não reconheceu que fui eu quem lhe deu o trigo, o vinho e o azeite, quem a cobriu de ouro e de prata, que eles usaram para Baal.

[[v28-2-9]]

^<<v28-2-9,9>>^ "Por isso levarei o meu trigo quando ele ficar maduro, e o meu vinho quando ficar pronto. Arrancarei dela minha lã e meu linho, que serviam para cobrir a sua nudez.

[[v28-2-10]]

^<<v28-2-10,10>>^ Agora, pois, vou expor a sua lascívia diante dos olhos dos seus amantes; ninguém a livrará das minhas mãos.

[[v28-2-11]]

^<<v28-2-11,11>>^ Acabarei com a sua alegria: suas festas anuais, suas luas novas, seus dias de sábado e todas as suas festas fixas.

[[v28-2-12]]

^<<v28-2-12,12>>^ Arruinarei suas videiras e suas figueiras, que, segundo ela, foi pagamento recebido de seus amantes; farei delas um matagal, e os animais selvagens as devorarão.

[[v28-2-13]]

^<<v28-2-13,13>>^ Eu a castigarei pelos dias em que ela queimou incenso aos baalins; ela se enfeitou com anéis e jóias, e foi atrás dos seus amantes, mas de mim, ela se esqueceu", declara o Senhor.

[[v28-2-14]]

^<<v28-2-14,14>>^ "Portanto, agora vou atraí-la; vou levá-la para o deserto e vou falar-lhe com carinho.

[[v28-2-15]]

^<<v28-2-15,15>>^ Ali devolverei a ela as suas vinhas, e farei do vale de Açor uma porta de esperança. Ali ela me responderá como nos dias de sua infância, como no dia em que saiu do Egito.

[[v28-2-16]]

^<<v28-2-16,16>>^ "Naquele dia", declara o Senhor, "você me chamará ‘meu marido’; não me chamará mais ‘meu senhor’.

[[v28-2-17]]

^<<v28-2-17,17>>^ Tirarei dos seus lábios os nomes dos baalins; seus nomes não serão mais invocados.

[[v28-2-18]]

^<<v28-2-18,18>>^ Naquele dia farei em favor deles um acordo com os animais do campo, com as aves do céu e com os animais que rastejam pelo chão. Arco, espada e guerra, eu os abolirei da terra, para que todos possam viver em paz.

[[v28-2-19]]

^<<v28-2-19,19>>^ Eu me casarei com você para sempre; eu me casarei com você com justiça e retidão, com amor e compaixão.

[[v28-2-20]]

^<<v28-2-20,20>>^ Eu me casarei com você com fidelidade, e você reconhecerá o Senhor.

[[v28-2-21]]

^<<v28-2-21,21>>^ "Naquele dia eu responderei", declara o Senhor. "Responderei aos céus, e eles responderão à terra;

[[v28-2-22]]

^<<v28-2-22,22>>^ e a terra responderá ao cereal, ao vinho e ao azeite, e eles responderão a Jezreel.

[[v28-2-23]]

^<<v28-2-23,23>>^ Eu a plantarei para mim mesmo na terra; tratarei com amor aquela que chamei Não amada. Direi àquele chamado ‘Não-meu-povo’: Você é meu povo; e ele dirá: ‘Tu és o meu Deus’.  "

'''

xref:028-oseias/028-oseias-001.adoc#v28-1-0[&#60; Capítulo Anterior] | <<v28-2-0,Topo>> | xref:028-oseias/028-oseias-003.adoc#v28-3-0[Próximo Capítulo &#62;]