include::./index.adoc[]

[[v28-8-0]]
=== Oséias, 8
// nvi ?, NVI - Nova Versão Internacional

[[v28-8-1]]

^<<v28-8-1,1>>^ "Coloquem a trombeta em seus lábios! É como uma águia sobre o templo do Senhor, porquanto quebraram a minha aliança e se rebelaram contra a minha Lei.

[[v28-8-2]]

^<<v28-8-2,2>>^ Israel clama a mim: ‘Ó nosso Deus, nós te reconhecemos! ’

[[v28-8-3]]

^<<v28-8-3,3>>^ Mas Israel rejeitou o que é bom; um inimigo o perseguirá.

[[v28-8-4]]

^<<v28-8-4,4>>^ Eles instituíram reis sem o meu consentimento; escolheram líderes sem a minha aprovação. Com prata e ouro fizeram ídolos para si, para a sua própria destruição.

[[v28-8-5]]

^<<v28-8-5,5>>^ Lance fora o seu ídolo em forma de bezerro, ó Samaria! A minha ira se acende contra eles. Até quando serão incapazes de pureza?

[[v28-8-6]]

^<<v28-8-6,6>>^ Este bezerro procede de Israel! Um escultor o fez. Ele não é Deus. Será partido em pedaços o bezerro de Samaria.

[[v28-8-7]]

^<<v28-8-7,7>>^ "Eles semeiam vento e colhem tempestade. O talo não tem espiga; não produzirá farinha. Caso produzisse o trigo, estrangeiros o devorariam.

[[v28-8-8]]

^<<v28-8-8,8>>^ Israel é devorado; agora está entre as nações como algo sem valor.

[[v28-8-9]]

^<<v28-8-9,9>>^ Pois eles foram para a Assíria. O jumento selvagem mantém-se livre, mas Efraim vendeu-se para os seus amantes.

[[v28-8-10]]

^<<v28-8-10,10>>^ Embora se tenham vendido às nações, agora os ajuntarei, e logo começarão a definhar sob a opressão do rei poderoso.

[[v28-8-11]]

^<<v28-8-11,11>>^ "Embora Efraim tenha construído muitos altares para ofertas pelo pecado, eles se tornaram altares para o pecado.

[[v28-8-12]]

^<<v28-8-12,12>>^ Eu lhes escrevi todos os ensinos da minha Lei, mas eles os consideraram algo estranho.

[[v28-8-13]]

^<<v28-8-13,13>>^ Eles me oferecem sacrifícios e comem a carne, mas o Senhor não se agrada deles. Doravante, ele se lembrará da impiedade deles e castigará os seus pecados: eles voltarão para o Egito.

[[v28-8-14]]

^<<v28-8-14,14>>^ Israel esqueceu o seu Criador e construiu palácios; Judá fortificou muitas cidades. Mas sobre as suas cidades enviarei fogo que consumirá suas fortalezas. "

'''

xref:028-oseias/028-oseias-007.adoc#v28-7-0[&#60; Capítulo Anterior] | <<v28-8-0,Topo>> | xref:028-oseias/028-oseias-009.adoc#v28-9-0[Próximo Capítulo &#62;]