include::./index.adoc[]

[[v28-13-0]]
=== Oséias, 13
// nvi ?, NVI - Nova Versão Internacional

[[v28-13-1]]

^<<v28-13-1,1>>^ Quando Efraim falava, os homens tremiam; ele era exaltado em Israel. Mas tornou-se culpado da adoração de Baal e começou a morrer.

[[v28-13-2]]

^<<v28-13-2,2>>^ Agora eles pecam cada vez mais; com sua prata fazem ídolos de metal para si, imagens modeladas com muita inteligência, todas elas obras de artesãos. Dizem desse povo: "Eles oferecem sacrifício humano e beijam os ídolos feitos em forma de bezerro".

[[v28-13-3]]

^<<v28-13-3,3>>^ Por isso serão como a neblina da manhã, como o orvalho que bem cedo evapora, como palha que num redemoinho vai-se de uma eira, como a fumaça que sai pela chaminé.

[[v28-13-4]]

^<<v28-13-4,4>>^ "Mas eu sou o Senhor, o seu Deus, desde a terra do Egito. Vocês não reconhecerão nenhum outro Deus além de mim, nenhum outro Salvador senão a mim.

[[v28-13-5]]

^<<v28-13-5,5>>^ Eu cuidei de vocês no deserto, naquela terra de calor ardente.

[[v28-13-6]]

^<<v28-13-6,6>>^ Quando eu os alimentava, ficavam satisfeitos; quando ficavam satisfeitos, se orgulhavam, e então me esqueciam.

[[v28-13-7]]

^<<v28-13-7,7>>^ Por isso virei sobre eles como leão, como leopardo, ficarei à espreita junto ao caminho.

[[v28-13-8]]

^<<v28-13-8,8>>^ Como uma ursa de quem roubaram os filhotes, eu os atacarei e os rasgarei. Como leão eu os devorarei; um animal selvagem os despedaçará.

[[v28-13-9]]

^<<v28-13-9,9>>^ "Você foi destruído, ó Israel, porque está contra mim, contra o seu ajudador.

[[v28-13-10]]

^<<v28-13-10,10>>^ E agora? Onde está o seu rei que havia de salvá-lo em todas as suas cidades? E os oficiais que você pediu, dizendo: ‘Dá-me um rei e líderes’?

[[v28-13-11]]

^<<v28-13-11,11>>^ Dei-lhe um rei na minha ira, e o tirei na minha indignação.

[[v28-13-12]]

^<<v28-13-12,12>>^ A culpa de Efraim foi anotada, seus pecados são mantidos em registro.

[[v28-13-13]]

^<<v28-13-13,13>>^ Chegam-lhe dores como as da mulher em trabalho de parto, mas ele não é uma criança inteligente; quando chega a hora, não sai do ventre que abrigou.

[[v28-13-14]]

^<<v28-13-14,14>>^ "Eu os redimirei do poder da sepultura; eu os resgatarei da morte. Onde estão, ó morte, as suas pragas? Onde está, ó sepultura, a sua destruição? "Não terei compaixão alguma,

[[v28-13-15]]

^<<v28-13-15,15>>^ embora ele floresça entre os seus irmãos. Um vento oriental virá da parte do Senhor, soprando desde o deserto; sua fonte falhará, e seu poço secará. Todos os seus tesouros serão saqueados dos seus depósitos.

[[v28-13-16]]

^<<v28-13-16,16>>^ O povo de Samaria carregará sua culpa, porque se rebelou contra o seu Deus. Eles serão mortos à espada; seus pequeninos serão pisados e despedaçados, suas mulheres grávidas terão rasgados os seus ventres. "

'''

xref:028-oseias/028-oseias-012.adoc#v28-12-0[&#60; Capítulo Anterior] | <<v28-13-0,Topo>> | xref:028-oseias/028-oseias-014.adoc#v28-14-0[Próximo Capítulo &#62;]