include::./index.adoc[]

[[v28-11-0]]
=== Oséias, 11
// nvi ?, NVI - Nova Versão Internacional

[[v28-11-1]]

^<<v28-11-1,1>>^ "Quando Israel era menino, eu o amei, e do Egito chamei o meu filho.

[[v28-11-2]]

^<<v28-11-2,2>>^ Mas, quanto mais eu o chamava, mais eles se afastavam de mim. Eles ofereceram sacrifícios aos baalins e queimaram incenso os ídolos esculpidos.

[[v28-11-3]]

^<<v28-11-3,3>>^ Mas fui eu quem ensinou Efraim a andar, tomando-o nos braços; mas eles não perceberam que fui eu quem os curou.

[[v28-11-4]]

^<<v28-11-4,4>>^ Eu os conduzi com laços de bondade humana e de amor; tirei do seu pescoço o jugo e me inclinei para alimentá-los.

[[v28-11-5]]

^<<v28-11-5,5>>^ "Acaso não voltarão ao Egito e a Assíria não os dominará porque eles se recusam a arrepender-se?

[[v28-11-6]]

^<<v28-11-6,6>>^ A espada reluzirá em suas cidades, destruirá as trancas de suas portas e dará fim aos seus planos.

[[v28-11-7]]

^<<v28-11-7,7>>^ O meu povo está decidido a desviar-se de mim. Embora sejam conclamados a servir ao Altíssimo, de modo algum o exaltam.

[[v28-11-8]]

^<<v28-11-8,8>>^ "Como posso desistir de você, Efraim? Como posso entregar você nas mãos de outros, Israel? Como posso tratá-lo como tratei Admá? Como posso fazer com você o que fiz com Zeboim? O meu coração está enternecido, despertou-se toda a minha compaixão.

[[v28-11-9]]

^<<v28-11-9,9>>^ Não executarei a minha ira impetuosa, não tornarei a destruir Efraim. Pois sou Deus, e não homem, o Santo no meio de vocês. Não virei com ira.

[[v28-11-10]]

^<<v28-11-10,10>>^ Eles seguirão o Senhor; ele rugirá como leão. Quando ele rugir, os seus filhos virão tremendo desde o Ocidente.

[[v28-11-11]]

^<<v28-11-11,11>>^ Virão voando do Egito como aves, da Assíria como pombas. Eu os estabelecerei em seus lares"; palavra do Senhor.

[[v28-11-12]]

^<<v28-11-12,12>>^ Efraim me cercou de mentiras, a casa de Israel de enganos, e Judá é rebelde contra Deus, a saber, contra o Santo fiel.

'''

xref:028-oseias/028-oseias-010.adoc#v28-10-0[&#60; Capítulo Anterior] | <<v28-11-0,Topo>> | xref:028-oseias/028-oseias-012.adoc#v28-12-0[Próximo Capítulo &#62;]