include::./index.adoc[]

[[v28-4-0]]
=== Oséias, 4
// nvi ?, NVI - Nova Versão Internacional

[[v28-4-1]]

^<<v28-4-1,1>>^ Israelitas, ouçam a palavra do Senhor, porque o Senhor tem uma acusação contra vocês que vivem nesta terra: "A fidelidade e o amor desapareceram desta terra, como também o conhecimento de Deus.

[[v28-4-2]]

^<<v28-4-2,2>>^ Só se vêem maldição, mentira e assassinatos, roubo e mais roubo, adultério mais adultério; ultrapassam todos os limites! E o derramamento de sangue é constante.

[[v28-4-3]]

^<<v28-4-3,3>>^ Por causa disso a terra pranteia, e todos os seus habitantes desfalecem; os animais do campo, as aves do céu e os peixes do mar estão morrendo.

[[v28-4-4]]

^<<v28-4-4,4>>^ "Mas, que ninguém discuta, que ninguém faça acusação, pois sou eu quem acusa os sacerdotes.

[[v28-4-5]]

^<<v28-4-5,5>>^ Vocês tropeçam dia e noite, e os profetas tropeçam com vocês. Por isso destruirei sua mãe.

[[v28-4-6]]

^<<v28-4-6,6>>^ Meu povo foi destruído por falta de conhecimento. "Uma vez que vocês rejeitaram o conhecimento, eu também os rejeito como meus sacerdotes; uma vez que vocês ignoraram a lei do seu Deus, eu também ignorarei seus filhos.

[[v28-4-7]]

^<<v28-4-7,7>>^ Quanto mais aumentaram os sacerdotes, mais eles pecaram contra mim; trocaram a Glória deles por algo vergonhoso.

[[v28-4-8]]

^<<v28-4-8,8>>^ Eles se alimentam dos pecados do meu povo e têm prazer em sua iniqüidade.

[[v28-4-9]]

^<<v28-4-9,9>>^ Portanto, castigarei tanto o povo quanto os sacerdotes por causa dos seus caminhos, e lhes retribuirei seus atos.

[[v28-4-10]]

^<<v28-4-10,10>>^ "Eles comerão, mas não terão o suficiente; eles se prostituirão, mas não aumentarão a prole, porque abandonaram o Senhor para se entregarem

[[v28-4-11]]

^<<v28-4-11,11>>^ à prostituição, ao vinho velho e ao novo, o que prejudica o discernimento do meu povo.

[[v28-4-12]]

^<<v28-4-12,12>>^ Eles pedem conselhos a um ídolo de madeira, e de um pedaço de pau recebem resposta. Um espírito de prostituição os leva a desviar-se; eles são infiéis ao seu Deus.

[[v28-4-13]]

^<<v28-4-13,13>>^ Sacrificam no alto dos montes e queimam incenso nas colinas, debaixo de um carvalho, de um estoraque ou de um terebinto, onde a sombra é agradável. Por isso as suas filhas se prostituem e as suas noras adulteram.

[[v28-4-14]]

^<<v28-4-14,14>>^ "Não castigarei suas filhas por se prostituírem, nem suas noras por adulterarem, porque os próprios homens se associam a meretrizes e participam dos sacrifícios oferecidos pelas prostitutas cultuais — um povo sem entendimento precipita-se à ruína!

[[v28-4-15]]

^<<v28-4-15,15>>^ "Embora você adultere, ó Israel, que Judá não se torne culpada! "Deixem de ir a Gilgal; não subam a Bete-Áven. E não digam: ‘Juro pelo nome do Senhor! ’

[[v28-4-16]]

^<<v28-4-16,16>>^ Os israelitas são rebeldes como bezerra indomável. Como pode o Senhor apascentá-los como cordeiros na campina?

[[v28-4-17]]

^<<v28-4-17,17>>^ Efraim está ligado a ídolos; deixem-no só!

[[v28-4-18]]

^<<v28-4-18,18>>^ Mesmo quando acaba a bebida, eles continuam em sua prostituição; seus governantes amam profundamente os caminhos vergonhosos.

[[v28-4-19]]

^<<v28-4-19,19>>^ Um redemoinho os varrerá para longe, e os seus altares lhes trarão vergonha.

'''

xref:028-oseias/028-oseias-003.adoc#v28-3-0[&#60; Capítulo Anterior] | <<v28-4-0,Topo>> | xref:028-oseias/028-oseias-005.adoc#v28-5-0[Próximo Capítulo &#62;]