include::./index.adoc[]

[[v28-9-0]]
=== Oséias, 9
// nvi ?, NVI - Nova Versão Internacional

[[v28-9-1]]

^<<v28-9-1,1>>^ Não se regozije, ó Israel; não se alegre como as outras nações. Pois você se prostituiu, abandonando o seu Deus; você ama o salário da prostituição em cada eira de trigo.

[[v28-9-2]]

^<<v28-9-2,2>>^ Os produtos da eira e do lagar não alimentarão o povo; o vinho novo lhes faltará.

[[v28-9-3]]

^<<v28-9-3,3>>^ Eles não permanecerão na terra do Senhor; Efraim voltará para o Egito, e na Assíria comerá comida impura.

[[v28-9-4]]

^<<v28-9-4,4>>^ Eles não derramarão ofertas de vinho para o Senhor, nem o agradarão os seus sacrifícios. Tais sacrifícios serão para eles como o pão dos pranteadores, que torna impuro quem o come. Essa comida será para eles mesmos; não entrará no templo do Senhor.

[[v28-9-5]]

^<<v28-9-5,5>>^ O que farão vocês no dia de suas festas fixas, nos dias de festa do Senhor?

[[v28-9-6]]

^<<v28-9-6,6>>^ Vejam! Fogem da destruição, mas o Egito os ajuntará, e Mênfis os sepultará. Os seus tesouros de prata as urtigas vão herdar; os cardos cobrirão totalmente as suas tendas.

[[v28-9-7]]

^<<v28-9-7,7>>^ Os dias de castigo vêm, os dias de punição estão chegando. Que Israel o saiba. Por serem tantos os pecados, e tanta a hostilidade de vocês, o profeta é considerado um tolo, o homem inspirado, um louco violento.

[[v28-9-8]]

^<<v28-9-8,8>>^ O profeta, junto ao meu Deus, é a sentinela que vigia Efraim, contudo, laços o aguardam em todas as suas veredas, e a hostilidade no templo do seu Deus.

[[v28-9-9]]

^<<v28-9-9,9>>^ Eles mergulharam na corrupção, como nos dias de Gibeá. Deus se lembrará de sua iniqüidade e os castigará por seus pecados.

[[v28-9-10]]

^<<v28-9-10,10>>^ "Quando encontrei Israel, foi como encontrar uvas no deserto; quando vi os antepassados de vocês, foi como ver os primeiros frutos de uma figueira. Mas, quando eles vieram a Baal-Peor, consagraram-se àquele ídolo vergonhoso e se tornaram tão repugnantes quanto aquilo que amaram.

[[v28-9-11]]

^<<v28-9-11,11>>^ A glória de Efraim lhe fugirá como pássaro: nenhum nascimento, nenhuma gravidez, nenhuma concepção.

[[v28-9-12]]

^<<v28-9-12,12>>^ Mesmo que criem filhos, porei de luto cada um deles. Ai deles quando eu me afastar!

[[v28-9-13]]

^<<v28-9-13,13>>^ Vi Efraim, plantado num lugar agradável, como Tiro. Mas Efraim entregará seus filhos ao matador. "

[[v28-9-14]]

^<<v28-9-14,14>>^ Ó Senhor, que darás a eles? Dá-lhes ventres que abortem e seios ressecados.

[[v28-9-15]]

^<<v28-9-15,15>>^ "Toda a sua impiedade começou em Gilgal; de fato, ali eu os odiei. Por causa dos seus pecados, eu os expulsarei da minha terra. Não os amarei mais; todos os seus líderes são rebeldes.

[[v28-9-16]]

^<<v28-9-16,16>>^ Efraim está ferido, sua raiz está seca, eles não produzem frutos. Mesmo que criem filhos, eu matarei sua querida prole. "

[[v28-9-17]]

^<<v28-9-17,17>>^ Meu Deus os rejeitará porque não lhe deram ouvidos; serão peregrinos entre as nações.

'''

xref:028-oseias/028-oseias-008.adoc#v28-8-0[&#60; Capítulo Anterior] | <<v28-9-0,Topo>> | xref:028-oseias/028-oseias-010.adoc#v28-10-0[Próximo Capítulo &#62;]