include::./index.adoc[]

[[v28-3-0]]
=== Oséias, 3
// nvi ?, NVI - Nova Versão Internacional

[[v28-3-1]]

^<<v28-3-1,1>>^ O Senhor me disse: "Vá, trate novamente com amor sua mulher, apesar de ela ser amada por outro e ser adúltera. Ame-a como o Senhor ama os israelitas, apesar de eles se voltarem para outros deuses e de amarem os bolos sagrados de uvas passas".

[[v28-3-2]]

^<<v28-3-2,2>>^ Por isso eu a comprei por cento e oitenta gramas de prata e um barril e meio de cevada.

[[v28-3-3]]

^<<v28-3-3,3>>^ E eu lhe disse: Você viverá comigo por muitos dias; você não será mais prostituta nem será de nenhum outro homem, e eu viverei com você.

[[v28-3-4]]

^<<v28-3-4,4>>^ Pois os israelitas viverão muitos dias sem rei e sem líder, sem sacrifício e sem colunas sagradas, sem colete sacerdotal e sem ídolos da família.

[[v28-3-5]]

^<<v28-3-5,5>>^ Depois disso os israelitas voltarão e buscarão o Senhor, o seu Deus, e Davi, seu rei. Virão tremendo atrás do Senhor e das suas bênçãos, nos últimos dias.

'''

xref:028-oseias/028-oseias-002.adoc#v28-2-0[&#60; Capítulo Anterior] | <<v28-3-0,Topo>> | xref:028-oseias/028-oseias-004.adoc#v28-4-0[Próximo Capítulo &#62;]