include::./index.adoc[]

[[v28-1-0]]
=== Oséias, 1
// nvi ?, NVI - Nova Versão Internacional

[[v28-1-1]]

^<<v28-1-1,1>>^ Palavra do Senhor que veio a Oséias, filho de Beeri, durante os reinados de Uzias, Jotão, Acaz e Ezequias, reis de Judá, e de Jeroboão, filho de Jeoás, rei de Israel:

[[v28-1-2]]

^<<v28-1-2,2>>^ Quando o Senhor começou a falar por meio de Oséias, o Senhor lhe disse: "Vá, tome uma mulher adúltera e filhos da infidelidade, porque a nação é culpada do mais vergonhoso adultério por afastar-se do Senhor".

[[v28-1-3]]

^<<v28-1-3,3>>^ Por isso ele se casou com Gômer, filha de Diblaim; ela engravidou e lhe deu um filho.

[[v28-1-4]]

^<<v28-1-4,4>>^ Então o Senhor disse a Oséias: "Dê a ele o nome de Jezreel, porque logo castigarei a dinastia de Jeú por causa do massacre ocorrido em Jezreel, e darei fim ao reino de Israel.

[[v28-1-5]]

^<<v28-1-5,5>>^ Naquele dia quebrarei o arco de Israel no vale de Jezreel".

[[v28-1-6]]

^<<v28-1-6,6>>^ Gômer engravidou novamente e deu à luz uma filha. Então o Senhor disse a Oséias: "Dê a ela o nome de Lo-Ruama, pois não mais mostrarei amor para com a nação de Israel, a ponto de perdoá-la.

[[v28-1-7]]

^<<v28-1-7,7>>^ Contudo, tratarei com amor a nação de Judá; e eu lhes concederei vitória, não pelo arco, pela espada ou por combate, nem por cavalos e cavaleiros, mas pelo Senhor, o seu Deus".

[[v28-1-8]]

^<<v28-1-8,8>>^ Depois de ter desmamado Lo-Ruama, Gômer teve outro filho.

[[v28-1-9]]

^<<v28-1-9,9>>^ Então o Senhor disse: "Dê a ele o nome de Lo-Ami, pois vocês não são meu povo, e eu não sou seu Deus.

[[v28-1-10]]

^<<v28-1-10,10>>^ "Contudo os israelitas ainda serão como a areia da praia, que não se pode medir nem contar. No lugar onde se dizia a eles: ‘Vocês não são meu povo’, eles serão chamados ‘filhos do Deus vivo’.

[[v28-1-11]]

^<<v28-1-11,11>>^ O povo de Judá e o povo de Israel serão reunidos, e eles designarão para si um só líder, e se levantarão da terra, pois será grande o dia de Jezreel.

'''

xref:027-daniel/027-daniel-012.adoc#v27-12-0[&#60; Capítulo Anterior] | <<v28-1-0,Topo>> | xref:028-oseias/028-oseias-002.adoc#v28-2-0[Próximo Capítulo &#62;]