include::./index.adoc[]

[[v41-7-0]]
=== Marcos, 7
// nvi ?, NVI - Nova Versão Internacional

[[v41-7-1]]

^<<v41-7-1,1>>^ Os fariseus e alguns dos mestres da lei, vindos de Jerusalém, reuniram-se a Jesus e

[[v41-7-2]]

^<<v41-7-2,2>>^ viram alguns dos seus discípulos comerem com as mãos "impuras", isto é, por lavar.

[[v41-7-3]]

^<<v41-7-3,3>>^ ( Os fariseus e todos os judeus não comem sem lavar as mãos cerimonialmente, apegando-se, assim, à tradição dos líderes religiosos.

[[v41-7-4]]

^<<v41-7-4,4>>^ Quando chegam da rua, não comem sem antes se lavarem. E observam muitas outras tradições, tais como o lavar de copos, jarros e vasilhas de metal. )

[[v41-7-5]]

^<<v41-7-5,5>>^ Então os fariseus e os mestres da lei perguntaram a Jesus: "Por que os seus discípulos não vivem de acordo com a tradição dos líderes religiosos, em vez de comerem o alimento com as mãos ‘impuras’? "

[[v41-7-6]]

^<<v41-7-6,6>>^ Ele respondeu: "Bem profetizou Isaías acerca de vocês, hipócritas; como está escrito: ‘Este povo me honra com os lábios, mas o seu coração está longe de mim.

[[v41-7-7]]

^<<v41-7-7,7>>^ Em vão me adoram; seus ensinamentos não passam de regras ensinadas por homens’.

[[v41-7-8]]

^<<v41-7-8,8>>^ Vocês negligenciam os mandamentos de Deus e se apegam às tradições dos homens".

[[v41-7-9]]

^<<v41-7-9,9>>^ E disse-lhes: "Vocês estão sempre encontrando uma boa maneira para pôr de lado os mandamentos de Deus, a fim de obedecer às suas tradições!

[[v41-7-10]]

^<<v41-7-10,10>>^ Pois Moisés disse: ‘Honra teu pai e tua mãe’, e ‘quem amaldiçoar seu pai ou sua mãe terá que ser executado’.

[[v41-7-11]]

^<<v41-7-11,11>>^ Mas vocês afirmam que se alguém disser a seu pai ou a sua mãe: ‘Qualquer ajuda que vocês poderiam receber de mim é Corbã’, isto é, uma oferta dedicada a Deus,

[[v41-7-12]]

^<<v41-7-12,12>>^ vocês o desobrigam de qualquer dever para com seu pai ou sua mãe.

[[v41-7-13]]

^<<v41-7-13,13>>^ Assim vocês anulam a palavra de Deus, por meio da tradição que vocês mesmos transmitiram. E fazem muitas coisas como essa".

[[v41-7-14]]

^<<v41-7-14,14>>^ Jesus chamou novamente a multidão para junto de si e disse: "Ouçam-me todos e entendam isto:

[[v41-7-15]]

^<<v41-7-15,15>>^ não há nada fora do homem que, nele entrando, possa torná-lo ‘impuro’. Pelo contrário, o que sai do homem é que o torna ‘impuro’.

[[v41-7-16]]

^<<v41-7-16,16>>^ Se alguém tem ouvidos para ouvir, ouça! "

[[v41-7-17]]

^<<v41-7-17,17>>^ Depois de deixar a multidão e entrar em casa, os discípulos lhe pediram explicação da parábola.

[[v41-7-18]]

^<<v41-7-18,18>>^ "Será que vocês também não conseguem entender? ", perguntou-lhes Jesus. "Não percebem que nada que entre no homem pode torná-lo ‘impuro’?

[[v41-7-19]]

^<<v41-7-19,19>>^ Porque não entra em seu coração, mas em seu estômago, sendo depois eliminado". Ao dizer isto, Jesus declarou "puros" todos os alimentos.

[[v41-7-20]]

^<<v41-7-20,20>>^ E continuou: "O que sai do homem é que o torna ‘impuro’.

[[v41-7-21]]

^<<v41-7-21,21>>^ Pois do interior do coração dos homens vêm os maus pensamentos, as imoralidades sexuais, os roubos, os homicídios, os adultérios,

[[v41-7-22]]

^<<v41-7-22,22>>^ as cobiças, as maldades, o engano, a devassidão, a inveja, a calúnia, a arrogância e a insensatez.

[[v41-7-23]]

^<<v41-7-23,23>>^ Todos esses males vêm de dentro e tornam o homem ‘impuro’ ".

[[v41-7-24]]

^<<v41-7-24,24>>^ Jesus saiu daquele lugar e foi para os arredores de Tiro e de Sidom. Entrou numa casa e não queria que ninguém o soubesse; contudo, não conseguiu manter em segredo a sua presença.

[[v41-7-25]]

^<<v41-7-25,25>>^ De fato, logo que ouviu falar dele, certa mulher, cuja filha estava com um espírito imundo, veio e lançou-se aos seus pés.

[[v41-7-26]]

^<<v41-7-26,26>>^ A mulher era grega, siro-fenícia de origem, e rogava a Jesus que expulsasse de sua filha o demônio.

[[v41-7-27]]

^<<v41-7-27,27>>^ Ele lhe disse: "Deixe que primeiro os filhos comam até se fartar; pois não é correto tirar o pão dos filhos e lançá-lo aos cachorrinhos".

[[v41-7-28]]

^<<v41-7-28,28>>^ Ela respondeu: "Sim, Senhor, mas até os cachorrinhos, debaixo da mesa, comem das migalhas das crianças".

[[v41-7-29]]

^<<v41-7-29,29>>^ Então ele lhe disse: "Por causa desta resposta, você pode ir; o demônio já saiu da sua filha".

[[v41-7-30]]

^<<v41-7-30,30>>^ Ela foi para casa e encontrou sua filha deitada na cama, e o demônio já a tinha deixado.

[[v41-7-31]]

^<<v41-7-31,31>>^ A seguir Jesus saiu dos arredores de Tiro e atravessou Sidom, até o mar da Galiléia e a região de Decápolis.

[[v41-7-32]]

^<<v41-7-32,32>>^ Ali algumas pessoas lhe trouxeram um homem que era surdo e mal podia falar, suplicando que lhe impusesse as mãos.

[[v41-7-33]]

^<<v41-7-33,33>>^ Depois de levá-lo à parte, longe da multidão, Jesus colocou os dedos nos ouvidos dele. Em seguida, cuspiu e tocou na língua do homem.

[[v41-7-34]]

^<<v41-7-34,34>>^ Então voltou os olhos para os céus e, com um profundo suspiro, disse-lhe: "Efatá! ", que significa: Abra-se.

[[v41-7-35]]

^<<v41-7-35,35>>^ Com isso, os ouvidos do homem se abriram, sua língua ficou livre e ele começou a falar corretamente.

[[v41-7-36]]

^<<v41-7-36,36>>^ Jesus ordenou-lhes que não o contassem a ninguém. Contudo, quanto mais ele os proibia, mais eles falavam.

[[v41-7-37]]

^<<v41-7-37,37>>^ O povo ficava simplesmente maravilhado e dizia: "Ele faz tudo muito bem. Faz até o surdo ouvir e o mudo falar".

'''

xref:041-marcos/041-marcos-006.adoc#v41-6-0[&#60; Capítulo Anterior] | <<v41-7-0,Topo>> | xref:041-marcos/041-marcos-008.adoc#v41-8-0[Próximo Capítulo &#62;]