include::./index.adoc[]

[[v41-1-0]]
=== Marcos, 1
// nvi ?, NVI - Nova Versão Internacional

[[v41-1-1]]

^<<v41-1-1,1>>^ Princípio do evangelho de Jesus Cristo, o Filho de Deus.

[[v41-1-2]]

^<<v41-1-2,2>>^ Conforme está escrito no profeta Isaías: "Enviarei à tua frente o meu mensageiro; ele preparará o teu caminho"—

[[v41-1-3]]

^<<v41-1-3,3>>^ "voz do que clama no deserto: ‘Preparem o caminho para o Senhor, façam veredas retas para ele’ ".

[[v41-1-4]]

^<<v41-1-4,4>>^ Assim surgiu João, batizando no deserto e pregando um batismo de arrependimento para o perdão dos pecados.

[[v41-1-5]]

^<<v41-1-5,5>>^ A ele vinha toda a região da Judéia e todo o povo de Jerusalém. Confessando os seus pecados, eram batizados por ele no rio Jordão.

[[v41-1-6]]

^<<v41-1-6,6>>^ João vestia roupas feitas de pêlos de camelo, usava um cinto de couro e comia gafanhotos e mel silvestre.

[[v41-1-7]]

^<<v41-1-7,7>>^ E esta era a sua mensagem: "Depois de mim vem alguém mais poderoso do que eu, tanto que não sou digno nem de curvar-me e desamarrar as correias das suas sandálias.

[[v41-1-8]]

^<<v41-1-8,8>>^ Eu os batizo com água, mas ele os batizará com o Espírito Santo".

[[v41-1-9]]

^<<v41-1-9,9>>^ Naquela ocasião Jesus veio de Nazaré da Galiléia e foi batizado por João no Jordão.

[[v41-1-10]]

^<<v41-1-10,10>>^ Assim que saiu da água, Jesus viu os céus se abrindo, e o Espírito descendo como pomba sobre ele.

[[v41-1-11]]

^<<v41-1-11,11>>^ Então veio dos céus uma voz: "Tu és o meu Filho amado; em ti me agrado".

[[v41-1-12]]

^<<v41-1-12,12>>^ Logo após, o Espírito o impeliu para o deserto.

[[v41-1-13]]

^<<v41-1-13,13>>^ Ali esteve quarenta dias, sendo tentado por Satanás. Estava com os animais selvagens, e os anjos o serviam.

[[v41-1-14]]

^<<v41-1-14,14>>^ Depois que João foi preso, Jesus foi para a Galiléia, proclamando as boas novas de Deus.

[[v41-1-15]]

^<<v41-1-15,15>>^ "O tempo é chegado", dizia ele. "O Reino de Deus está próximo. Arrependam-se e creiam nas boas novas! "

[[v41-1-16]]

^<<v41-1-16,16>>^ Andando à beira do mar da Galiléia, Jesus viu Simão e seu irmão André lançando redes ao mar, pois eram pescadores.

[[v41-1-17]]

^<<v41-1-17,17>>^ E disse Jesus: "Sigam-me, e eu os farei pescadores de homens".

[[v41-1-18]]

^<<v41-1-18,18>>^ No mesmo instante eles deixaram as suas redes e o seguiram.

[[v41-1-19]]

^<<v41-1-19,19>>^ Indo um pouco mais adiante, viu num barco Tiago, filho de Zebedeu, e João, seu irmão, preparando as suas redes.

[[v41-1-20]]

^<<v41-1-20,20>>^ Logo os chamou, e eles o seguiram, deixando Zebedeu, seu pai, com os empregados no barco.

[[v41-1-21]]

^<<v41-1-21,21>>^ Eles foram para Cafarnaum e, assim que chegou o sábado, Jesus entrou na sinagoga e começou a ensinar.

[[v41-1-22]]

^<<v41-1-22,22>>^ Todos ficavam maravilhados com o seu ensino, porque lhes ensinava como alguém que tem autoridade e não como os mestres da lei.

[[v41-1-23]]

^<<v41-1-23,23>>^ Justamente naquela hora, na sinagoga, um homem possesso de um espírito imundo gritou:

[[v41-1-24]]

^<<v41-1-24,24>>^ "O que queres conosco, Jesus de Nazaré? Vieste para nos destruir? Sei quem tu és: o Santo de Deus! "

[[v41-1-25]]

^<<v41-1-25,25>>^ "Cale-se e saia dele! ", repreendeu-o Jesus.

[[v41-1-26]]

^<<v41-1-26,26>>^ O espírito imundo sacudiu o homem violentamente e saiu dele gritando.

[[v41-1-27]]

^<<v41-1-27,27>>^ Todos ficaram tão admirados que perguntavam uns aos outros: "O que é isto? Um novo ensino — e com autoridade! Até aos espíritos imundos ele dá ordens, e eles lhe obedecem! "

[[v41-1-28]]

^<<v41-1-28,28>>^ As notícias a seu respeito se espalharam rapidamente por toda a região da Galiléia.

[[v41-1-29]]

^<<v41-1-29,29>>^ Logo que saíram da sinagoga, foram com Tiago e João à casa de Simão e André.

[[v41-1-30]]

^<<v41-1-30,30>>^ A sogra de Simão estava de cama, com febre, e falaram a respeito dela a Jesus.

[[v41-1-31]]

^<<v41-1-31,31>>^ Então ele se aproximou dela, tomou-a pela mão e ajudou-a a levantar-se. A febre a deixou, e ela começou a servi-los.

[[v41-1-32]]

^<<v41-1-32,32>>^ Ao anoitecer, depois do pôr-do-sol, o povo levou a Jesus todos os doentes e os endemoninhados.

[[v41-1-33]]

^<<v41-1-33,33>>^ Toda a cidade se reuniu à porta da casa,

[[v41-1-34]]

^<<v41-1-34,34>>^ e Jesus curou muitos que sofriam de várias doenças. Também expulsou muitos demônios; não permitia, porém, que estes falassem, porque sabiam quem ele era.

[[v41-1-35]]

^<<v41-1-35,35>>^ De madrugada, quando ainda estava escuro, Jesus levantou-se, saiu de casa e foi para um lugar deserto, onde ficou orando.

[[v41-1-36]]

^<<v41-1-36,36>>^ Simão e seus companheiros foram procurá-lo

[[v41-1-37]]

^<<v41-1-37,37>>^ e, ao encontrá-lo, disseram: "Todos estão te procurando! "

[[v41-1-38]]

^<<v41-1-38,38>>^ Jesus respondeu: "Vamos para outro lugar, para os povoados vizinhos, para que também lá eu pregue. Foi para isso que eu vim".

[[v41-1-39]]

^<<v41-1-39,39>>^ Então ele percorreu toda a Galiléia, pregando nas sinagogas e expulsando os demônios.

[[v41-1-40]]

^<<v41-1-40,40>>^ Um leproso aproximou-se dele e suplicou-lhe de joelhos: "Se quiseres, podes purificar-me! "

[[v41-1-41]]

^<<v41-1-41,41>>^ Cheio de compaixão, Jesus estendeu a mão, tocou nele e disse: "Quero. Seja purificado! "

[[v41-1-42]]

^<<v41-1-42,42>>^ Imediatamente a lepra o deixou, e ele foi purificado.

[[v41-1-43]]

^<<v41-1-43,43>>^ Em seguida Jesus o despediu, com uma severa advertência:

[[v41-1-44]]

^<<v41-1-44,44>>^ "Olhe, não conte isso a ninguém. Mas vá mostrar-se ao sacerdote e ofereça pela sua purificação os sacrifícios que Moisés ordenou, para que sirva de testemunho".

[[v41-1-45]]

^<<v41-1-45,45>>^ Ele, porém, saiu e começou a tornar público o fato, espalhando a notícia. Por isso Jesus não podia mais entrar publicamente em nenhuma cidade, mas ficava fora, em lugares solitários. Todavia, assim mesmo vinha a ele gente de todas as partes.

'''

xref:040-mateus/040-mateus-028.adoc#v40-28-0[&#60; Capítulo Anterior] | <<v41-1-0,Topo>> | xref:041-marcos/041-marcos-002.adoc#v41-2-0[Próximo Capítulo &#62;]