include::./index.adoc[]

[[v41-4-0]]
=== Marcos, 4
// nvi ?, NVI - Nova Versão Internacional

[[v41-4-1]]

^<<v41-4-1,1>>^ Novamente Jesus começou a ensinar à beira-mar. Reuniu-se ao seu redor uma multidão tão grande que ele teve que entrar num barco e assentar-se nele. O barco estava no mar, enquanto todo o povo ficava na beira da praia.

[[v41-4-2]]

^<<v41-4-2,2>>^ Ele lhes ensinava muitas coisas por parábolas, dizendo em seu ensino:

[[v41-4-3]]

^<<v41-4-3,3>>^ "Ouçam! O semeador saiu a semear.

[[v41-4-4]]

^<<v41-4-4,4>>^ Enquanto lançava a semente, parte dela caiu à beira do caminho, e as aves vieram e a comeram.

[[v41-4-5]]

^<<v41-4-5,5>>^ Parte dela caiu em terreno pedregoso, onde não havia muita terra; e logo brotou, porque a terra não era profunda.

[[v41-4-6]]

^<<v41-4-6,6>>^ Mas quando saiu o sol, as plantas se queimaram e secaram, porque não tinham raiz.

[[v41-4-7]]

^<<v41-4-7,7>>^ Outra parte caiu entre espinhos, que cresceram e sufocaram as plantas, de forma que ela não deu fruto.

[[v41-4-8]]

^<<v41-4-8,8>>^ Outra ainda caiu em boa terra, germinou, cresceu e deu boa colheita, a trinta, sessenta e até cem por um".

[[v41-4-9]]

^<<v41-4-9,9>>^ A seguir Jesus acrescentou: "Aquele que tem ouvidos para ouvir, ouça! "

[[v41-4-10]]

^<<v41-4-10,10>>^ Quando ele ficou sozinho, os Doze e os outros que estavam ao seu redor lhe fizeram perguntas acerca das parábolas.

[[v41-4-11]]

^<<v41-4-11,11>>^ Ele lhes disse: "A vocês foi dado o mistério do Reino de Deus, mas aos que estão fora tudo é dito por parábolas,

[[v41-4-12]]

^<<v41-4-12,12>>^ a fim de que, ‘ainda que vejam, não percebam, ainda que ouçam, não entendam; de outro modo, poderiam converter-se e ser perdoados! ’"

[[v41-4-13]]

^<<v41-4-13,13>>^ Então Jesus lhes perguntou: "Vocês não entendem esta parábola? Como, então, compreenderão todas as outras parábolas?

[[v41-4-14]]

^<<v41-4-14,14>>^ O semeador semeia a palavra.

[[v41-4-15]]

^<<v41-4-15,15>>^ Algumas pessoas são como a semente à beira do caminho, onde a palavra é semeada. Logo que a ouvem, Satanás vem e retira a palavra nelas semeada.

[[v41-4-16]]

^<<v41-4-16,16>>^ Outras, como a semente lançada em terreno pedregoso, ouvem a palavra e logo a recebem com alegria.

[[v41-4-17]]

^<<v41-4-17,17>>^ Todavia, visto que não têm raiz em si mesmas, permanecem por pouco tempo. Quando surge alguma tribulação ou perseguição por causa da palavra, logo a abandonam.

[[v41-4-18]]

^<<v41-4-18,18>>^ Outras ainda, como a semente lançada entre espinhos, ouvem a palavra;

[[v41-4-19]]

^<<v41-4-19,19>>^ mas quando chegam as preocupações desta vida, o engano das riquezas e os anseios por outras coisas, sufocam a palavra, tornando-a infrutífera.

[[v41-4-20]]

^<<v41-4-20,20>>^ Outras pessoas são como a semente lançada em boa terra: ouvem a palavra, aceitam-na e dão uma colheita de trinta, sessenta e até cem por um".

[[v41-4-21]]

^<<v41-4-21,21>>^ Ele lhes disse: "Quem traz uma candeia para ser colocada debaixo de uma vasilha ou de uma cama? Acaso não a coloca num lugar apropriado?

[[v41-4-22]]

^<<v41-4-22,22>>^ Porque não há nada oculto, senão para ser revelado, e nada escondido senão para ser trazido à luz.

[[v41-4-23]]

^<<v41-4-23,23>>^ Se alguém tem ouvidos para ouvir, ouça!

[[v41-4-24]]

^<<v41-4-24,24>>^ "Considerem atentamente o que vocês estão ouvindo", continuou ele. "Com a medida com que medirem, vocês serão medidos; e ainda mais lhes acrescentarão.

[[v41-4-25]]

^<<v41-4-25,25>>^ A quem tiver, mais lhe será dado; de quem não tiver, até o que tem lhe será tirado".

[[v41-4-26]]

^<<v41-4-26,26>>^ Ele prosseguiu dizendo: "O Reino de Deus é semelhante a um homem que lança a semente sobre a terra.

[[v41-4-27]]

^<<v41-4-27,27>>^ Noite e dia, quer ele durma quer se levante, a semente germina e cresce, embora ele não saiba como.

[[v41-4-28]]

^<<v41-4-28,28>>^ A terra por si própria produz o grão: primeiro o talo, depois a espiga e, então, o grão cheio na espiga.

[[v41-4-29]]

^<<v41-4-29,29>>^ Logo que o grão fica maduro, o homem lhe passa a foice, porque chegou a colheita".

[[v41-4-30]]

^<<v41-4-30,30>>^ Novamente ele disse: "Com que compararemos o Reino de Deus? Que parábola usaremos para descrevê-lo?

[[v41-4-31]]

^<<v41-4-31,31>>^ É como um grão de mostarda, que, quando plantada, é a menor semente de todas.

[[v41-4-32]]

^<<v41-4-32,32>>^ No entanto, plantada, ela cresce e se torna a maior de todas as hortaliças, com ramos tão grandes que as aves do céu podem abrigar-se à sua sombra".

[[v41-4-33]]

^<<v41-4-33,33>>^ Com muitas parábolas semelhantes Jesus lhes anunciava a palavra, tanto quanto podiam receber.

[[v41-4-34]]

^<<v41-4-34,34>>^ Não lhes dizia nada sem usar alguma parábola. Quando, porém, estava a sós com os seus discípulos, explicava-lhes tudo.

[[v41-4-35]]

^<<v41-4-35,35>>^ Naquele dia, ao anoitecer, disse ele aos seus discípulos: "Vamos atravessar para o outro lado".

[[v41-4-36]]

^<<v41-4-36,36>>^ Deixando a multidão, eles o levaram no barco, assim como estava. Outros barcos também o acompanhavam.

[[v41-4-37]]

^<<v41-4-37,37>>^ Levantou-se um forte vendaval, e as ondas se lançavam sobre o barco, de forma que este foi se enchendo de água.

[[v41-4-38]]

^<<v41-4-38,38>>^ Jesus estava na popa, dormindo com a cabeça sobre um travesseiro. Os discípulos o acordaram e clamaram: "Mestre, não te importas que morramos? "

[[v41-4-39]]

^<<v41-4-39,39>>^ Ele se levantou, repreendeu o vento e disse ao mar: "Aquiete-se! Acalme-se! " O vento se aquietou, e fez-se completa bonança.

[[v41-4-40]]

^<<v41-4-40,40>>^ Então perguntou aos seus discípulos: "Por que vocês estão com tanto medo? Ainda não têm fé? "

[[v41-4-41]]

^<<v41-4-41,41>>^ Eles estavam apavorados e perguntavam uns aos outros: "Quem é este que até o vento e o mar lhe obedecem? "

'''

xref:041-marcos/041-marcos-003.adoc#v41-3-0[&#60; Capítulo Anterior] | <<v41-4-0,Topo>> | xref:041-marcos/041-marcos-005.adoc#v41-5-0[Próximo Capítulo &#62;]