include::./index.adoc[]

[[v41-9-0]]
=== Marcos, 9
// nvi ?, NVI - Nova Versão Internacional

[[v41-9-1]]

^<<v41-9-1,1>>^ E lhes disse: "Garanto-lhes que alguns dos que aqui estão de modo nenhum experimentarão a morte, antes de verem o Reino de Deus vindo com poder".

[[v41-9-2]]

^<<v41-9-2,2>>^ Seis dias depois, Jesus tomou consigo Pedro, Tiago e João e os levou a um alto monte, onde ficaram a sós. Ali ele foi transfigurado diante deles.

[[v41-9-3]]

^<<v41-9-3,3>>^ Suas roupas se tornaram brancas, de um branco resplandecente, como nenhum lavandeiro no mundo seria capaz de branqueá-las.

[[v41-9-4]]

^<<v41-9-4,4>>^ E apareceram diante deles Elias e Moisés, os quais conversavam com Jesus.

[[v41-9-5]]

^<<v41-9-5,5>>^ Então Pedro disse a Jesus: "Mestre, é bom estarmos aqui. Façamos três tendas: uma para ti, uma para Moisés e uma para Elias".

[[v41-9-6]]

^<<v41-9-6,6>>^ Ele não sabia o que dizer, pois estavam apavorados.

[[v41-9-7]]

^<<v41-9-7,7>>^ A seguir apareceu uma nuvem e os envolveu, e dela saiu uma voz, que disse: "Este é o meu Filho amado. Ouçam-no! "

[[v41-9-8]]

^<<v41-9-8,8>>^ Repentinamente, quando olharam ao redor, não viram mais ninguém, a não ser Jesus.

[[v41-9-9]]

^<<v41-9-9,9>>^ Enquanto desciam do monte, Jesus lhes ordenou que não contassem a ninguém o que tinham visto, até que o Filho do homem tivesse ressuscitado dos mortos.

[[v41-9-10]]

^<<v41-9-10,10>>^ Eles guardaram o assunto apenas entre si, discutindo o que significaria "ressuscitar dos mortos".

[[v41-9-11]]

^<<v41-9-11,11>>^ E lhe perguntaram: "Por que os mestres da lei dizem que é necessário que Elias venha primeiro? "

[[v41-9-12]]

^<<v41-9-12,12>>^ Jesus respondeu: "De fato, Elias vem primeiro e restaura todas as coisas. Então, por que está escrito que é necessário que o Filho do homem sofra muito e seja rejeitado com desprezo?

[[v41-9-13]]

^<<v41-9-13,13>>^ Mas eu lhes digo: Elias já veio, e fizeram com ele tudo o que quiseram, como está escrito a seu respeito".

[[v41-9-14]]

^<<v41-9-14,14>>^ Quando chegaram onde estavam os outros discípulos, viram uma grande multidão ao redor deles e os mestres da lei discutindo com eles.

[[v41-9-15]]

^<<v41-9-15,15>>^ Logo que todo o povo viu Jesus, ficou muito surpreso e correu para saudá-lo.

[[v41-9-16]]

^<<v41-9-16,16>>^ Perguntou Jesus: "O que vocês estão discutindo? "

[[v41-9-17]]

^<<v41-9-17,17>>^ Um homem, no meio da multidão, respondeu: "Mestre, eu te trouxe o meu filho, que está com um espírito que o impede de falar.

[[v41-9-18]]

^<<v41-9-18,18>>^ Onde quer que o apanhe, joga-o no chão. Ele espuma pela boca, range os dentes e fica rígido. Pedi aos teus discípulos que expulsassem o espírito, mas eles não conseguiram".

[[v41-9-19]]

^<<v41-9-19,19>>^ Respondeu Jesus: "Ó geração incrédula, até quando estarei com vocês? Até quando terei que suportá-los? Tragam-me o menino".

[[v41-9-20]]

^<<v41-9-20,20>>^ Então, eles o trouxeram. Quando o espírito viu Jesus, imediatamente causou uma convulsão no menino. Este caiu no chão e começou a rolar, espumando pela boca.

[[v41-9-21]]

^<<v41-9-21,21>>^ Jesus perguntou ao pai do menino: "Há quanto tempo ele está assim? " "Desde a infância", respondeu ele.

[[v41-9-22]]

^<<v41-9-22,22>>^ "Muitas vezes o tem lançado no fogo e na água para matá-lo. Mas, se podes fazer alguma coisa, tem compaixão de nós e ajuda-nos. "

[[v41-9-23]]

^<<v41-9-23,23>>^ "Se podes? ", disse Jesus. "Tudo é possível àquele que crê. "

[[v41-9-24]]

^<<v41-9-24,24>>^ Imediatamente o pai do menino exclamou: "Creio, ajuda-me a vencer a minha incredulidade! "

[[v41-9-25]]

^<<v41-9-25,25>>^ Quando Jesus viu que uma multidão estava se ajuntando, repreendeu o espírito imundo, dizendo: "Espírito mudo e surdo, eu ordeno que o deixe e nunca mais entre nele".

[[v41-9-26]]

^<<v41-9-26,26>>^ O espírito gritou, agitou-o violentamente e saiu. O menino ficou como morto, a ponto de muitos dizerem: "Ele morreu".

[[v41-9-27]]

^<<v41-9-27,27>>^ Mas Jesus tomou-o pela mão e o levantou, e ele ficou em pé.

[[v41-9-28]]

^<<v41-9-28,28>>^ Depois de Jesus ter entrado em casa, seus discípulos lhe perguntaram em particular: "Por que não conseguimos expulsá-lo? "

[[v41-9-29]]

^<<v41-9-29,29>>^ Ele respondeu: "Essa espécie só sai pela oração e pelo jejum".

[[v41-9-30]]

^<<v41-9-30,30>>^ Eles saíram daquele lugar e atravessaram a Galiléia. Jesus não queria que ninguém soubesse onde eles estavam,

[[v41-9-31]]

^<<v41-9-31,31>>^ porque estava ensinando os seus discípulos. E lhes dizia: "O Filho do homem está para ser entregue nas mãos dos homens. Eles o matarão, e três dias depois ele ressuscitará".

[[v41-9-32]]

^<<v41-9-32,32>>^ Mas eles não entendiam o que ele queria dizer e tinham receio de perguntar-lhe.

[[v41-9-33]]

^<<v41-9-33,33>>^ E chegaram a Cafarnaum. Quando ele estava em casa, perguntou-lhes: "O que vocês estavam discutindo no caminho? "

[[v41-9-34]]

^<<v41-9-34,34>>^ Mas eles guardaram silêncio, porque no caminho haviam discutido sobre quem era o maior.

[[v41-9-35]]

^<<v41-9-35,35>>^ Assentando-se, Jesus chamou os Doze e disse: "Se alguém quiser ser o primeiro, será o último, e servo de todos".

[[v41-9-36]]

^<<v41-9-36,36>>^ E, tomando uma criança, colocou-a no meio deles. Pegando-a nos braços, disse-lhes:

[[v41-9-37]]

^<<v41-9-37,37>>^ "Quem recebe uma destas crianças em meu nome, está me recebendo; e quem me recebe, não está apenas me recebendo, mas também àquele que me enviou".

[[v41-9-38]]

^<<v41-9-38,38>>^ "Mestre", disse João, "vimos um homem expulsando demônios em teu nome e procuramos impedi-lo, porque ele não era um dos nossos. "

[[v41-9-39]]

^<<v41-9-39,39>>^ "Não o impeçam", disse Jesus. "Ninguém que faça um milagre em meu nome, pode falar mal de mim logo em seguida,

[[v41-9-40]]

^<<v41-9-40,40>>^ pois quem não é contra nós está a nosso favor.

[[v41-9-41]]

^<<v41-9-41,41>>^ Eu lhes digo a verdade: Quem lhes der um copo de água em meu nome, por vocês pertencerem a Cristo, de modo nenhum perderá a sua recompensa. "

[[v41-9-42]]

^<<v41-9-42,42>>^ "Se alguém fizer tropeçar um destes pequeninos que crêem em mim, seria melhor que fosse lançado no mar com uma grande pedra amarrada no pescoço.

[[v41-9-43]]

^<<v41-9-43,43>>^ Se a sua mão o fizer tropeçar, corte-a. É melhor entrar na vida mutilado do que, tendo as duas mãos, ir para o inferno, onde o fogo nunca se apaga,

[[v41-9-44]]

^<<v41-9-44,44>>^ onde o seu verme não morre, e o fogo não se apaga.

[[v41-9-45]]

^<<v41-9-45,45>>^ E se o seu pé o fizer tropeçar, corte-o. É melhor entrar na vida aleijado do que, tendo os dois pés, ser lançado no inferno.

[[v41-9-46]]

^<<v41-9-46,46>>^ onde o seu verme não morre, e o fogo não se apaga.

[[v41-9-47]]

^<<v41-9-47,47>>^ E se o seu olho o fizer tropeçar, arranque-o. É melhor entrar no Reino de Deus com um só olho do que, tendo os dois olhos, ser lançado no inferno,

[[v41-9-48]]

^<<v41-9-48,48>>^ onde ‘o seu verme não morre, e o fogo não se apaga’.

[[v41-9-49]]

^<<v41-9-49,49>>^ Cada um será salgado com fogo.

[[v41-9-50]]

^<<v41-9-50,50>>^ "O sal é bom, mas se deixar de ser salgado, como restaurar o seu sabor? Tenham sal em vocês mesmos e vivam em paz uns com os outros".

'''

xref:041-marcos/041-marcos-008.adoc#v41-8-0[&#60; Capítulo Anterior] | <<v41-9-0,Topo>> | xref:041-marcos/041-marcos-010.adoc#v41-10-0[Próximo Capítulo &#62;]