include::./index.adoc[]

[[v41-3-0]]
=== Marcos, 3
// nvi ?, NVI - Nova Versão Internacional

[[v41-3-1]]

^<<v41-3-1,1>>^ Noutra ocasião ele entrou na sinagoga, e estava ali um homem com uma das mãos atrofiada.

[[v41-3-2]]

^<<v41-3-2,2>>^ Alguns deles estavam procurando um motivo para acusar Jesus; por isso o observavam atentamente, para ver se ele iria curá-lo no sábado.

[[v41-3-3]]

^<<v41-3-3,3>>^ Jesus disse ao homem da mão atrofiada: "Levante-se e venha para o meio".

[[v41-3-4]]

^<<v41-3-4,4>>^ Depois Jesus lhes perguntou: "O que é permitido fazer no sábado: o bem ou o mal, salvar a vida ou matar? " Mas eles permaneceram em silêncio.

[[v41-3-5]]

^<<v41-3-5,5>>^ Irado, olhou para os que estavam à sua volta e, profundamente entristecido por causa dos seus corações endurecidos, disse ao homem: "Estenda a mão". Ele a estendeu, e ela foi restaurada.

[[v41-3-6]]

^<<v41-3-6,6>>^ Então os fariseus saíram e começaram a conspirar com os herodianos contra Jesus, sobre como poderiam matá-lo.

[[v41-3-7]]

^<<v41-3-7,7>>^ Jesus retirou-se com os seus discípulos para o mar, e uma grande multidão vinda da Galiléia o seguia.

[[v41-3-8]]

^<<v41-3-8,8>>^ Quando ouviram a respeito de tudo o que ele estava fazendo, muitas pessoas procedentes da Judéia, de Jerusalém, da Iduméia e das regiões do outro lado do Jordão e dos arredores de Tiro e de Sidom foram atrás dele.

[[v41-3-9]]

^<<v41-3-9,9>>^ Por causa da multidão, ele disse aos discípulos que lhe preparassem um pequeno barco, para evitar que o comprimissem.

[[v41-3-10]]

^<<v41-3-10,10>>^ Pois ele havia curado a muitos, de modo que os que sofriam de doenças ficavam se empurrando para conseguir tocar nele.

[[v41-3-11]]

^<<v41-3-11,11>>^ Sempre que os espíritos imundos o viam, prostravam-se diante dele e gritavam: "Tu és o Filho de Deus".

[[v41-3-12]]

^<<v41-3-12,12>>^ Mas ele lhes dava ordens severas para que não dissessem quem ele era.

[[v41-3-13]]

^<<v41-3-13,13>>^ Jesus subiu a um monte e chamou a si aqueles que ele quis, os quais vieram para junto dele.

[[v41-3-14]]

^<<v41-3-14,14>>^ Escolheu doze, designando-os como apóstolos, para que estivessem com ele, os enviasse a pregar

[[v41-3-15]]

^<<v41-3-15,15>>^ e tivessem autoridade para expulsar demônios.

[[v41-3-16]]

^<<v41-3-16,16>>^ Estes são os doze que ele escolheu: Simão, a quem deu o nome de Pedro;

[[v41-3-17]]

^<<v41-3-17,17>>^ Tiago, filho de Zebedeu, e João, seu irmão, aos quais deu o nome de Boanerges, que significa filhos do trovão;

[[v41-3-18]]

^<<v41-3-18,18>>^ André; Filipe; Bartolomeu; Mateus; Tomé; Tiago, filho de Alfeu; Tadeu; Simão, o zelote,

[[v41-3-19]]

^<<v41-3-19,19>>^ e Judas Iscariotes, que o traiu.

[[v41-3-20]]

^<<v41-3-20,20>>^ Então Jesus entrou numa casa, e novamente reuniu-se ali uma multidão, de modo que ele e os seus discípulos não conseguiam nem comer.

[[v41-3-21]]

^<<v41-3-21,21>>^ Quando seus familiares ouviram falar disso, saíram para apoderar-se dele, pois diziam: "Ele está fora de si".

[[v41-3-22]]

^<<v41-3-22,22>>^ E os mestres da lei que haviam descido de Jerusalém diziam: "Ele está com Belzebu! Pelo príncipe dos demônios é que ele expulsa demônios".

[[v41-3-23]]

^<<v41-3-23,23>>^ Então Jesus os chamou e lhes falou por parábolas: "Como pode Satanás expulsar Satanás?

[[v41-3-24]]

^<<v41-3-24,24>>^ Se um reino estiver dividido contra si mesmo, não poderá subsistir.

[[v41-3-25]]

^<<v41-3-25,25>>^ Se uma casa estiver dividida contra si mesma, também não poderá subsistir.

[[v41-3-26]]

^<<v41-3-26,26>>^ E se Satanás se opuser a si mesmo e estiver dividido, não poderá subsistir; chegou o seu fim.

[[v41-3-27]]

^<<v41-3-27,27>>^ De fato, ninguém pode entrar na casa do homem forte e levar dali os seus bens, sem que antes o amarre. Só então poderá roubar a casa dele.

[[v41-3-28]]

^<<v41-3-28,28>>^ Eu lhes asseguro que todos os pecados e blasfêmias dos homens lhes serão perdoados,

[[v41-3-29]]

^<<v41-3-29,29>>^ mas quem blasfemar contra o Espírito Santo nunca terá perdão: é culpado de pecado eterno".

[[v41-3-30]]

^<<v41-3-30,30>>^ Jesus falou isso porque eles estavam dizendo: "Ele está com um espírito imundo".

[[v41-3-31]]

^<<v41-3-31,31>>^ Então chegaram a mãe e os irmãos de Jesus. Ficando do lado de fora, mandaram alguém chamá-lo.

[[v41-3-32]]

^<<v41-3-32,32>>^ Havia muita gente assentada ao seu redor; e lhe disseram: "Tua mãe e teus irmãos estão lá fora e te procuram".

[[v41-3-33]]

^<<v41-3-33,33>>^ "Quem é minha mãe, e quem são meus irmãos? ", perguntou ele.

[[v41-3-34]]

^<<v41-3-34,34>>^ Então olhou para os que estavam assentados ao seu redor e disse: "Aqui estão minha mãe e meus irmãos!

[[v41-3-35]]

^<<v41-3-35,35>>^ Quem faz a vontade de Deus, este é meu irmão, minha irmã e minha mãe".

'''

xref:041-marcos/041-marcos-002.adoc#v41-2-0[&#60; Capítulo Anterior] | <<v41-3-0,Topo>> | xref:041-marcos/041-marcos-004.adoc#v41-4-0[Próximo Capítulo &#62;]