include::./index.adoc[]

[[v41-14-0]]
=== Marcos, 14
// nvi ?, NVI - Nova Versão Internacional

[[v41-14-1]]

^<<v41-14-1,1>>^ Faltavam apenas dois dias para a Páscoa e para a festa dos pães sem fermento. Os chefes dos sacerdotes e os mestres da lei estavam procurando um meio de flagrar Jesus em algum erro e matá-lo.

[[v41-14-2]]

^<<v41-14-2,2>>^ Mas diziam: "Não durante a festa, para que não haja tumulto entre o povo".

[[v41-14-3]]

^<<v41-14-3,3>>^ Estando Jesus em Betânia, reclinado à mesa na casa de um homem conhecido como Simão, o leproso, aproximou-se dele certa mulher com um frasco de alabastro contendo um perfume muito caro, feito de nardo puro. Ela quebrou o frasco e derramou o perfume sobre a cabeça de Jesus.

[[v41-14-4]]

^<<v41-14-4,4>>^ Alguns dos presentes começaram a dizer uns aos outros, indignados: "Por que este desperdício de perfume?

[[v41-14-5]]

^<<v41-14-5,5>>^ Ele poderia ser vendido por trezentos denários, e o dinheiro dado aos pobres". E a repreendiam severamente.

[[v41-14-6]]

^<<v41-14-6,6>>^ "Deixem-na em paz", disse Jesus. "Por que a estão perturbando? Ela praticou uma boa ação para comigo.

[[v41-14-7]]

^<<v41-14-7,7>>^ Pois os pobres vocês sempre terão consigo, e poderão ajudá-los sempre que o desejarem. Mas a mim vocês nem sempre terão.

[[v41-14-8]]

^<<v41-14-8,8>>^ Ela fez o que pôde. Derramou o perfume em meu corpo antecipadamente, preparando-o para o sepultamento.

[[v41-14-9]]

^<<v41-14-9,9>>^ Eu lhes asseguro que onde quer que o evangelho for anunciado, em todo o mundo, também o que ela fez será contado em sua memória".

[[v41-14-10]]

^<<v41-14-10,10>>^ Então Judas Iscariotes, um dos Doze, dirigiu-se aos chefes dos sacerdotes a fim de lhes entregar Jesus.

[[v41-14-11]]

^<<v41-14-11,11>>^ A proposta muito os alegrou, e lhe prometeram dinheiro. Assim, ele procurava uma oportunidade para entregá-lo.

[[v41-14-12]]

^<<v41-14-12,12>>^ No primeiro dia da festa dos pães sem fermento, quando se costumava sacrificar o cordeiro pascal, os discípulos de Jesus lhe perguntaram: "Aonde queres que vamos e te preparemos a refeição da Páscoa? "

[[v41-14-13]]

^<<v41-14-13,13>>^ Então ele enviou dois de seus discípulos, dizendo-lhes: "Entrem na cidade, e um homem carregando um pote de água virá ao encontro de vocês. Sigam-no

[[v41-14-14]]

^<<v41-14-14,14>>^ e digam ao dono da casa em que ele entrar: ‘O Mestre pergunta: Onde é o meu salão de hóspedes, no qual poderei comer a Páscoa com meus discípulos? ’

[[v41-14-15]]

^<<v41-14-15,15>>^ Ele lhes mostrará uma ampla sala no andar superior, mobiliada e pronta. Façam ali os preparativos para nós".

[[v41-14-16]]

^<<v41-14-16,16>>^ Os discípulos se retiraram, entraram na cidade e encontraram tudo como Jesus lhes tinha dito. E prepararam a Páscoa.

[[v41-14-17]]

^<<v41-14-17,17>>^ Ao anoitecer, Jesus chegou com os Doze.

[[v41-14-18]]

^<<v41-14-18,18>>^ Quando estavam comendo, reclinados à mesa, Jesus disse: "Digo-lhes que certamente um de vocês me trairá, alguém que está comendo comigo".

[[v41-14-19]]

^<<v41-14-19,19>>^ Eles ficaram tristes e, um por um, lhe disseram: "Com certeza não sou eu! "

[[v41-14-20]]

^<<v41-14-20,20>>^ Afirmou Jesus: "É um dos Doze, alguém que come comigo do mesmo prato.

[[v41-14-21]]

^<<v41-14-21,21>>^ O Filho do homem vai, como está escrito a seu respeito. Mas ai daquele que trai o Filho do homem! Melhor lhe seria não haver nascido".

[[v41-14-22]]

^<<v41-14-22,22>>^ Enquanto comiam, Jesus tomou o pão, deu graças, partiu-o, e o deu aos discípulos, dizendo: "Tomem; isto é o meu corpo".

[[v41-14-23]]

^<<v41-14-23,23>>^ Em seguida tomou o cálice, deu graças, ofereceu-o aos discípulos, e todos beberam.

[[v41-14-24]]

^<<v41-14-24,24>>^ E lhes disse: "Isto é o meu sangue da aliança, que é derramado em favor de muitos.

[[v41-14-25]]

^<<v41-14-25,25>>^ Eu lhes afirmo que não beberei outra vez do fruto da videira, até aquele dia em que beberei o vinho novo no Reino de Deus".

[[v41-14-26]]

^<<v41-14-26,26>>^ Depois de terem cantado um hino, saíram para o monte das Oliveiras.

[[v41-14-27]]

^<<v41-14-27,27>>^ Disse-lhes Jesus: "Vocês todos me abandonarão. Pois está escrito: ‘Ferirei o pastor, e as ovelhas serão dispersas’.

[[v41-14-28]]

^<<v41-14-28,28>>^ Mas, depois de ressuscitar, irei adiante de vocês para a Galiléia".

[[v41-14-29]]

^<<v41-14-29,29>>^ Pedro declarou: "Ainda que todos te abandonem, eu não te abandonarei! "

[[v41-14-30]]

^<<v41-14-30,30>>^ Respondeu Jesus: "Asseguro-lhe que ainda hoje, esta noite, antes que duas vezes cante o galo, três vezes você me negará".

[[v41-14-31]]

^<<v41-14-31,31>>^ Mas Pedro insistia ainda mais: "Mesmo que seja preciso que eu morra contigo, nunca te negarei". E todos os outros disseram o mesmo.

[[v41-14-32]]

^<<v41-14-32,32>>^ Então foram para um lugar chamado Getsêmani, e Jesus disse aos seus discípulos: "Sentem-se aqui enquanto vou orar".

[[v41-14-33]]

^<<v41-14-33,33>>^ Levou consigo Pedro, Tiago e João, e começou a ficar aflito e angustiado.

[[v41-14-34]]

^<<v41-14-34,34>>^ E lhes disse: "A minha alma está profundamente triste, numa tristeza mortal. Fiquem aqui e vigiem".

[[v41-14-35]]

^<<v41-14-35,35>>^ Indo um pouco mais adiante, prostrou-se e orava para que, se possível, fosse afastada dele aquela hora.

[[v41-14-36]]

^<<v41-14-36,36>>^ E dizia: "Aba, Pai, tudo te é possível. Afasta de mim este cálice; contudo, não seja o que eu quero, mas sim o que tu queres".

[[v41-14-37]]

^<<v41-14-37,37>>^ Então, voltou aos seus discípulos e os encontrou dormindo. "Simão", disse ele a Pedro, "você está dormindo? Não pôde vigiar nem por uma hora?

[[v41-14-38]]

^<<v41-14-38,38>>^ Vigiem e orem para que não caiam em tentação. O espírito está pronto, mas a carne é fraca. "

[[v41-14-39]]

^<<v41-14-39,39>>^ Mais uma vez ele se afastou e orou, repetindo as mesmas palavras.

[[v41-14-40]]

^<<v41-14-40,40>>^ Quando voltou, de novo os encontrou dormindo, porque seus olhos estavam pesados. Eles não sabiam o que lhe dizer.

[[v41-14-41]]

^<<v41-14-41,41>>^ Voltando pela terceira vez, ele lhes disse: "Vocês ainda dormem e descansam? Basta! Chegou a hora! Eis que o Filho do homem está sendo entregue nas mãos dos pecadores.

[[v41-14-42]]

^<<v41-14-42,42>>^ Levantem-se e vamos! Aí vem aquele que me trai! "

[[v41-14-43]]

^<<v41-14-43,43>>^ Enquanto ele ainda falava, apareceu Judas, um dos Doze. Com ele estava uma multidão armada de espadas e varas, enviada pelos chefes dos sacerdotes, mestres da lei e líderes religiosos.

[[v41-14-44]]

^<<v41-14-44,44>>^ O traidor havia combinado um sinal com eles: "Aquele a quem eu saudar com um beijo, é ele: prendam-no e levem-no em segurança".

[[v41-14-45]]

^<<v41-14-45,45>>^ Dirigindo-se imediatamente a Jesus, Judas disse: "Mestre! ", e o beijou.

[[v41-14-46]]

^<<v41-14-46,46>>^ Os homens agarraram Jesus e o prenderam.

[[v41-14-47]]

^<<v41-14-47,47>>^ Então, um dos que estavam por perto puxou a espada e feriu o servo do sumo sacerdote, decepando-lhe a orelha.

[[v41-14-48]]

^<<v41-14-48,48>>^ Disse Jesus: "Estou eu chefiando alguma rebelião, para que vocês venham me prender com espadas e varas?

[[v41-14-49]]

^<<v41-14-49,49>>^ Todos os dias eu estava com vocês, ensinando no templo, e vocês não me prenderam. Mas as Escrituras precisam ser cumpridas".

[[v41-14-50]]

^<<v41-14-50,50>>^ Então todos o abandonaram e fugiram.

[[v41-14-51]]

^<<v41-14-51,51>>^ Um jovem, vestindo apenas um lençol de linho, estava seguindo a Jesus. Quando tentaram prendê-lo,

[[v41-14-52]]

^<<v41-14-52,52>>^ ele fugiu nu, deixando o lençol para trás.

[[v41-14-53]]

^<<v41-14-53,53>>^ Levaram Jesus ao sumo sacerdote; e então se reuniram todos os chefes dos sacerdotes, os líderes religiosos e os mestres da lei.

[[v41-14-54]]

^<<v41-14-54,54>>^ Pedro o seguiu de longe até o pátio do sumo sacerdote. Sentando-se ali com os guardas, esquentava-se junto ao fogo.

[[v41-14-55]]

^<<v41-14-55,55>>^ Os chefes dos sacerdotes e todo o Sinédrio estavam procurando depoimentos contra Jesus, para que pudessem condená-lo à morte, mas não encontravam nenhum.

[[v41-14-56]]

^<<v41-14-56,56>>^ Muitos testemunharam falsamente contra ele, mas as declarações deles não eram coerentes.

[[v41-14-57]]

^<<v41-14-57,57>>^ Então se levantaram alguns e declararam falsamente contra ele:

[[v41-14-58]]

^<<v41-14-58,58>>^ "Nós o ouvimos dizer: ‘Destruirei este templo feito por mãos humanas e em três dias construirei outro, não feito por mãos de homens’ ".

[[v41-14-59]]

^<<v41-14-59,59>>^ Mas, nem mesmo assim, o depoimento deles era coerente.

[[v41-14-60]]

^<<v41-14-60,60>>^ Depois o sumo sacerdote levantou-se diante deles e perguntou a Jesus: "Você não vai responder à acusação que estes lhe fazem? "

[[v41-14-61]]

^<<v41-14-61,61>>^ Mas Jesus permaneceu em silêncio e nada respondeu. Outra vez o sumo sacerdote lhe perguntou: "Você é o Cristo, o Filho do Deus Bendito? "

[[v41-14-62]]

^<<v41-14-62,62>>^ "Sou", disse Jesus. "E vereis o Filho do homem assentado à direita do Poderoso vindo com as nuvens do céu".

[[v41-14-63]]

^<<v41-14-63,63>>^ O sumo sacerdote, rasgando as próprias vestes, perguntou: "Por que precisamos de mais testemunhas?

[[v41-14-64]]

^<<v41-14-64,64>>^ Vocês ouviram a blasfêmia. Que acham? " Todos o julgaram digno de morte.

[[v41-14-65]]

^<<v41-14-65,65>>^ Então alguns começaram a cuspir nele; vendaram-lhe os olhos e, dando-lhe murros, diziam: "Profetize! " E os guardas o levaram, dando-lhe tapas.

[[v41-14-66]]

^<<v41-14-66,66>>^ Estando Pedro em baixo, no pátio, uma das criadas do sumo sacerdote passou por ali.

[[v41-14-67]]

^<<v41-14-67,67>>^ Vendo Pedro a aquecer-se, olhou bem para ele e disse: "Você também estava com Jesus, o Nazareno".

[[v41-14-68]]

^<<v41-14-68,68>>^ Contudo ele o negou, dizendo: "Não o conheço, nem sei do que você está falando". E saiu para o alpendre.

[[v41-14-69]]

^<<v41-14-69,69>>^ Quando a criada o viu lá, disse novamente aos que estavam por perto: "Esse aí é um deles".

[[v41-14-70]]

^<<v41-14-70,70>>^ De novo ele negou. Pouco tempo depois, os que estavam sentados ali perto disseram a Pedro: "Certamente você é um deles. Você é galileu! "

[[v41-14-71]]

^<<v41-14-71,71>>^ Ele começou a se amaldiçoar e a jurar: "Não conheço o homem de quem vocês estão falando! "

[[v41-14-72]]

^<<v41-14-72,72>>^ E logo o galo cantou pela segunda vez. Então Pedro se lembrou da palavra que Jesus lhe tinha dito: "Antes que duas vezes cante o galo, você me negará três vezes". E se pôs a chorar.

'''

xref:041-marcos/041-marcos-013.adoc#v41-13-0[&#60; Capítulo Anterior] | <<v41-14-0,Topo>> | xref:041-marcos/041-marcos-015.adoc#v41-15-0[Próximo Capítulo &#62;]