include::./index.adoc[]

[[v41-15-0]]
=== Marcos, 15
// nvi ?, NVI - Nova Versão Internacional

[[v41-15-1]]

^<<v41-15-1,1>>^ De manhã bem cedo, os chefes dos sacerdotes com os líderes religiosos, os mestres da lei e todo o Sinédrio chegaram a uma decisão. Amarrando Jesus, levaram-no e o entregaram a Pilatos.

[[v41-15-2]]

^<<v41-15-2,2>>^ "Você é o rei dos judeus? ", perguntou Pilatos. "Tu o dizes", respondeu Jesus.

[[v41-15-3]]

^<<v41-15-3,3>>^ Os chefes dos sacerdotes o acusavam de muitas coisas.

[[v41-15-4]]

^<<v41-15-4,4>>^ Então Pilatos lhe perguntou novamente: "Você não vai responder? Veja de quantas coisas o estão acusando".

[[v41-15-5]]

^<<v41-15-5,5>>^ Mas Jesus não respondeu nada, e Pilatos ficou impressionado.

[[v41-15-6]]

^<<v41-15-6,6>>^ Por ocasião da festa, era costume soltar um prisioneiro que o povo pedisse.

[[v41-15-7]]

^<<v41-15-7,7>>^ Um homem chamado Barrabás estava na prisão com os rebeldes que haviam cometido assassinato durante uma rebelião.

[[v41-15-8]]

^<<v41-15-8,8>>^ A multidão chegou e pediu a Pilatos que lhe fizesse o que costumava fazer.

[[v41-15-9]]

^<<v41-15-9,9>>^ "Vocês querem que eu lhes solte o rei dos judeus? ", perguntou Pilatos,

[[v41-15-10]]

^<<v41-15-10,10>>^ sabendo que fora por inveja que os chefes dos sacerdotes lhe haviam entregado Jesus.

[[v41-15-11]]

^<<v41-15-11,11>>^ Mas os chefes dos sacerdotes incitaram a multidão a pedir que Pilatos, ao contrário, soltasse Barrabás.

[[v41-15-12]]

^<<v41-15-12,12>>^ "Então, que farei com aquele a quem vocês chamam rei dos judeus? ", perguntou-lhes Pilatos.

[[v41-15-13]]

^<<v41-15-13,13>>^ "Crucifica-o", gritaram eles.

[[v41-15-14]]

^<<v41-15-14,14>>^ "Por quê? Que crime ele cometeu? ", perguntou Pilatos. Mas eles gritavam ainda mais: "Crucifica-o! "

[[v41-15-15]]

^<<v41-15-15,15>>^ Desejando agradar a multidão, Pilatos soltou-lhes Barrabás, mandou açoitar Jesus e o entregou para ser crucificado.

[[v41-15-16]]

^<<v41-15-16,16>>^ Os soldados levaram Jesus para dentro do palácio, isto é, ao Pretório e reuniram toda a tropa.

[[v41-15-17]]

^<<v41-15-17,17>>^ Vestiram-no com um manto de púrpura, depois fizeram uma coroa de espinhos e a colocaram nele.

[[v41-15-18]]

^<<v41-15-18,18>>^ E começaram a saudá-lo: "Salve, rei dos judeus! "

[[v41-15-19]]

^<<v41-15-19,19>>^ Batiam-lhe na cabeça com uma vara e cuspiam nele. Ajoelhavam-se e lhe prestavam adoração.

[[v41-15-20]]

^<<v41-15-20,20>>^ Depois de terem zombado dele, tiraram-lhe o manto de púrpura e vestiram-lhe suas próprias roupas. Então o levaram para fora, a fim de crucificá-lo.

[[v41-15-21]]

^<<v41-15-21,21>>^ Certo homem de Cirene, chamado Simão, pai de Alexandre e de Rufo, passava por ali, chegando do campo. Eles o forçaram a carregar a cruz.

[[v41-15-22]]

^<<v41-15-22,22>>^ Levaram Jesus ao lugar chamado Gólgota, que quer dizer Lugar da Caveira.

[[v41-15-23]]

^<<v41-15-23,23>>^ Então lhe deram vinho misturado com mirra, mas ele não o bebeu.

[[v41-15-24]]

^<<v41-15-24,24>>^ E o crucificaram. Dividindo as roupas dele, tiraram sortes para saber com o que cada um iria ficar.

[[v41-15-25]]

^<<v41-15-25,25>>^ Eram nove horas da manhã quando o crucificaram.

[[v41-15-26]]

^<<v41-15-26,26>>^ E assim estava escrito na acusação contra ele: O REI DOS JUDEUS.

[[v41-15-27]]

^<<v41-15-27,27>>^ Com ele crucificaram dois ladrões, um à sua direita e outro à sua esquerda,

[[v41-15-28]]

^<<v41-15-28,28>>^ e cumpriu-se a Escritura que diz: "Ele foi contado entre os transgressores".

[[v41-15-29]]

^<<v41-15-29,29>>^ Os que passavam lançavam-lhe insultos, balançando a cabeça e dizendo: "Ora, você que destrói o templo e o reedifica em três dias,

[[v41-15-30]]

^<<v41-15-30,30>>^ desça da cruz e salve-se a si mesmo! "

[[v41-15-31]]

^<<v41-15-31,31>>^ Da mesma forma, os chefes dos sacerdotes e os mestres da lei zombavam dele entre si, dizendo: "Salvou os outros, mas não é capaz de salvar a si mesmo.

[[v41-15-32]]

^<<v41-15-32,32>>^ O Cristo, o Rei de Israel... Desça da cruz, para que o vejamos e creiamos! " Os que foram crucificados com ele também o insultavam.

[[v41-15-33]]

^<<v41-15-33,33>>^ E houve trevas sobre toda a terra, do meio dia às três horas da tarde.

[[v41-15-34]]

^<<v41-15-34,34>>^ Por volta das três horas da tarde, Jesus bradou em alta voz: "Eloí, Eloí, lamá sabactâni? " que significa: "Meu Deus! Meu Deus! Por que me abandonaste? "

[[v41-15-35]]

^<<v41-15-35,35>>^ Quando alguns dos que estavam presentes ouviram isso, disseram: "Ouçam! Ele está chamando Elias".

[[v41-15-36]]

^<<v41-15-36,36>>^ Um deles correu, embebeu uma esponja em vinagre, colocou-a na ponta de uma vara e deu-a a Jesus para beber. E disse: "Deixem-no. Vejamos se Elias vem tirá-lo daí".

[[v41-15-37]]

^<<v41-15-37,37>>^ Mas Jesus, com um alto brado, expirou.

[[v41-15-38]]

^<<v41-15-38,38>>^ E o véu do santuário rasgou-se em duas partes, de alto a baixo.

[[v41-15-39]]

^<<v41-15-39,39>>^ Quando o centurião que estava em frente de Jesus ouviu o seu brado e viu como ele morreu, disse: "Realmente este homem era o Filho de Deus! "

[[v41-15-40]]

^<<v41-15-40,40>>^ Algumas mulheres estavam observando de longe. Entre elas estavam Maria Madalena, Salomé e Maria, mãe de Tiago, o mais jovem, e de José.

[[v41-15-41]]

^<<v41-15-41,41>>^ Na Galiléia elas tinham seguido e servido a Jesus. Muitas outras mulheres que tinham subido com ele para Jerusalém também estavam ali.

[[v41-15-42]]

^<<v41-15-42,42>>^ Era o Dia da Preparação, isto é, a véspera do sábado. Ao cair da tarde,

[[v41-15-43]]

^<<v41-15-43,43>>^ José de Arimatéia, membro de destaque do Sinédrio, que também esperava o Reino de Deus, dirigiu-se corajosamente a Pilatos e pediu o corpo de Jesus.

[[v41-15-44]]

^<<v41-15-44,44>>^ Pilatos ficou surpreso ao ouvir que ele já tinha morrido. Chamando o centurião, perguntou-lhe se Jesus já tinha morrido.

[[v41-15-45]]

^<<v41-15-45,45>>^ Sendo informado pelo centurião, entregou o corpo a José.

[[v41-15-46]]

^<<v41-15-46,46>>^ Então José comprou um lençol de linho, baixou o corpo da cruz, envolveu-o no lençol e o colocou num sepulcro cavado na rocha. Depois, fez rolar uma pedra sobre a entrada do sepulcro.

[[v41-15-47]]

^<<v41-15-47,47>>^ Maria Madalena e Maria, mãe de José, viram onde ele fora colocado.

'''

xref:041-marcos/041-marcos-014.adoc#v41-14-0[&#60; Capítulo Anterior] | <<v41-15-0,Topo>> | xref:041-marcos/041-marcos-016.adoc#v41-16-0[Próximo Capítulo &#62;]