include::./index.adoc[]

[[v41-13-0]]
=== Marcos, 13
// nvi ?, NVI - Nova Versão Internacional

[[v41-13-1]]

^<<v41-13-1,1>>^ Quando ele estava saindo do templo, um de seus discípulos lhe disse: "Olha, Mestre! Que pedras enormes! Que construções magníficas! "

[[v41-13-2]]

^<<v41-13-2,2>>^ "Você está vendo todas estas grandes construções? ", perguntou Jesus. "Aqui não ficará pedra sobre pedra; serão todas derrubadas".

[[v41-13-3]]

^<<v41-13-3,3>>^ Tendo Jesus se assentado no monte das Oliveiras, de frente para o templo, Pedro, Tiago, João e André lhe perguntaram em particular:

[[v41-13-4]]

^<<v41-13-4,4>>^ "Dize-nos, quando acontecerão essas coisas? E qual será o sinal de que tudo isso está prestes a cumprir-se? "

[[v41-13-5]]

^<<v41-13-5,5>>^ Jesus lhes disse: "Cuidado, que ninguém os engane.

[[v41-13-6]]

^<<v41-13-6,6>>^ Muitos virão em meu nome, dizendo: ‘Sou eu! ’ e enganarão a muitos.

[[v41-13-7]]

^<<v41-13-7,7>>^ Quando ouvirem falar de guerras e rumores de guerras, não tenham medo. É necessário que tais coisas aconteçam, mas ainda não é o fim.

[[v41-13-8]]

^<<v41-13-8,8>>^ Nação se levantará contra nação, e reino contra reino. Haverá terremotos em vários lugares e também fomes. Essas coisas são o início das dores.

[[v41-13-9]]

^<<v41-13-9,9>>^ "Fiquem atentos, pois vocês serão entregues aos tribunais e serão açoitados nas sinagogas. Por minha causa vocês serão levados à presença de governadores e reis, como testemunho a eles.

[[v41-13-10]]

^<<v41-13-10,10>>^ E é necessário que antes o evangelho seja pregado a todas as nações.

[[v41-13-11]]

^<<v41-13-11,11>>^ Sempre que forem presos e levados a julgamento, não fiquem preocupados com o que vão dizer. Digam tão-somente o que lhes for dado naquela hora, pois não serão vocês que estarão falando, mas o Espírito Santo.

[[v41-13-12]]

^<<v41-13-12,12>>^ "O irmão trairá seu próprio irmão, entregando-o à morte, e o mesmo fará o pai a seu filho. Filhos se rebelarão contra seus pais e os matarão.

[[v41-13-13]]

^<<v41-13-13,13>>^ Todos odiarão vocês por minha causa; mas aquele que perseverar até o fim será salvo.

[[v41-13-14]]

^<<v41-13-14,14>>^ "Quando vocês virem ‘o sacrilégio terrível’ no lugar onde não deve estar — quem lê, entenda — então, os que estiverem na Judéia fujam para os montes.

[[v41-13-15]]

^<<v41-13-15,15>>^ Quem estiver no telhado de sua casa não desça nem entre em casa para tirar dela coisa alguma.

[[v41-13-16]]

^<<v41-13-16,16>>^ Quem estiver no campo não volte para pegar seu manto.

[[v41-13-17]]

^<<v41-13-17,17>>^ Como serão terríveis aqueles dias para as grávidas e para as que estiverem amamentando!

[[v41-13-18]]

^<<v41-13-18,18>>^ Orem para que essas coisas não aconteçam no inverno.

[[v41-13-19]]

^<<v41-13-19,19>>^ Porque aqueles serão dias de tribulação como nunca houve desde que Deus criou o mundo até agora, nem jamais haverá.

[[v41-13-20]]

^<<v41-13-20,20>>^ Se o Senhor não tivesse abreviado tais dias, ninguém sobreviveria. Mas, por causa dos eleitos por ele escolhidos, ele os abreviou.

[[v41-13-21]]

^<<v41-13-21,21>>^ Se, então, alguém lhes disser: ‘Vejam, aqui está o Cristo! ’ ou: ‘Vejam, ali está ele! ’, não acreditem.

[[v41-13-22]]

^<<v41-13-22,22>>^ Pois aparecerão falsos cristos e falsos profetas que realizarão sinais e maravilhas para, se possível, enganar os eleitos.

[[v41-13-23]]

^<<v41-13-23,23>>^ Por isso, fiquem atentos: avisei-os de tudo antecipadamente.

[[v41-13-24]]

^<<v41-13-24,24>>^ "Mas naqueles dias, após aquela tribulação, ‘o sol escurecerá e a lua não dará a sua luz;

[[v41-13-25]]

^<<v41-13-25,25>>^ as estrelas cairão do céu e os poderes celestes serão abalados’.

[[v41-13-26]]

^<<v41-13-26,26>>^ "Então se verá o Filho do homem vindo nas nuvens com grande poder e glória.

[[v41-13-27]]

^<<v41-13-27,27>>^ E ele enviará os seus anjos e reunirá os seus eleitos dos quatro ventos, dos confins da terra até os confins do céu.

[[v41-13-28]]

^<<v41-13-28,28>>^ "Aprendam a lição da figueira: quando seus ramos se renovam e suas folhas começam a brotar, vocês sabem que o verão está próximo.

[[v41-13-29]]

^<<v41-13-29,29>>^ Assim também, quando virem estas coisas acontecendo, saibam que ele está próximo, às portas.

[[v41-13-30]]

^<<v41-13-30,30>>^ Eu lhes asseguro que não passará esta geração até que todas essas coisas aconteçam.

[[v41-13-31]]

^<<v41-13-31,31>>^ O céu e a terra passarão, mas as minhas palavras jamais passarão".

[[v41-13-32]]

^<<v41-13-32,32>>^ "Quanto ao dia e à hora ninguém sabe, nem os anjos no céu, nem o Filho, senão somente o Pai.

[[v41-13-33]]

^<<v41-13-33,33>>^ Fiquem atentos! Vigiem! Vocês não sabem quando virá esse tempo.

[[v41-13-34]]

^<<v41-13-34,34>>^ É como um homem que sai de viagem. Ele deixa sua casa, encarrega de tarefas cada um dos seus servos e ordena ao porteiro que vigie.

[[v41-13-35]]

^<<v41-13-35,35>>^ Portanto, vigiem, porque vocês não sabem quando o dono da casa voltará: se à tarde, à meia-noite, ao cantar do galo ou ao amanhecer.

[[v41-13-36]]

^<<v41-13-36,36>>^ Se ele vier de repente, que não os encontre dormindo!

[[v41-13-37]]

^<<v41-13-37,37>>^ O que lhes digo, digo a todos: Vigiem! "

'''

xref:041-marcos/041-marcos-012.adoc#v41-12-0[&#60; Capítulo Anterior] | <<v41-13-0,Topo>> | xref:041-marcos/041-marcos-014.adoc#v41-14-0[Próximo Capítulo &#62;]