include::./index.adoc[]

[[v41-6-0]]
=== Marcos, 6
// nvi ?, NVI - Nova Versão Internacional

[[v41-6-1]]

^<<v41-6-1,1>>^ Jesus saiu dali e foi para a sua cidade, acompanhado dos seus discípulos.

[[v41-6-2]]

^<<v41-6-2,2>>^ Quando chegou o sábado, começou a ensinar na sinagoga, e muitos dos que o ouviam ficavam admirados. "De onde lhe vêm estas coisas? ", perguntavam eles. "Que sabedoria é esta que lhe foi dada? E estes milagres que ele faz?

[[v41-6-3]]

^<<v41-6-3,3>>^ Não é este o carpinteiro, filho de Maria e irmão de Tiago, José, Judas e Simão? Não estão aqui conosco as suas irmãs? " E ficavam escandalizados por causa dele.

[[v41-6-4]]

^<<v41-6-4,4>>^ Jesus lhes disse: "Só em sua própria terra, entre seus parentes e em sua própria casa, é que um profeta não tem honra".

[[v41-6-5]]

^<<v41-6-5,5>>^ E não pôde fazer ali nenhum milagre, exceto impor as mãos sobre alguns doentes e curá-los.

[[v41-6-6]]

^<<v41-6-6,6>>^ E ficou admirado com a incredulidade deles. Então Jesus passou a percorrer os povoados, ensinando.

[[v41-6-7]]

^<<v41-6-7,7>>^ Chamando os Doze para junto de si, enviou-os de dois em dois e deu-lhes autoridade sobre os espíritos imundos.

[[v41-6-8]]

^<<v41-6-8,8>>^ Estas foram as suas instruções: "Não levem nada pelo caminho, a não ser um bordão. Não levem pão, nem saco de viagem, nem dinheiro em seus cintos;

[[v41-6-9]]

^<<v41-6-9,9>>^ calcem sandálias, mas não levem túnica extra;

[[v41-6-10]]

^<<v41-6-10,10>>^ sempre que entrarem numa casa, fiquem ali até partirem;

[[v41-6-11]]

^<<v41-6-11,11>>^ e, se algum povoado não os receber nem os ouvir, sacudam a poeira dos seus pés quando saírem de lá, como testemunho contra eles".

[[v41-6-12]]

^<<v41-6-12,12>>^ Eles saíram e pregaram ao povo que se arrependesse.

[[v41-6-13]]

^<<v41-6-13,13>>^ Expulsavam muitos demônios, ungiam muitos doentes com óleo e os curavam.

[[v41-6-14]]

^<<v41-6-14,14>>^ O rei Herodes ouviu falar dessas coisas, pois o nome de Jesus havia se tornado bem conhecido. Algumas pessoas estavam dizendo: "João Batista ressuscitou dos mortos! Por isso estão operando nele poderes miraculosos".

[[v41-6-15]]

^<<v41-6-15,15>>^ Outros diziam: "Ele é Elias". E ainda outros afirmavam: "Ele é um profeta, como um dos antigos profetas".

[[v41-6-16]]

^<<v41-6-16,16>>^ Mas quando Herodes ouviu essas coisas, disse: "João, o homem a quem decapitei, ressuscitou dos mortos! "

[[v41-6-17]]

^<<v41-6-17,17>>^ Pois o próprio Herodes tinha dado ordens para que prendessem João, o amarrassem e o colocassem na prisão, por causa de Herodias, mulher de Filipe, seu irmão, com a qual se casara.

[[v41-6-18]]

^<<v41-6-18,18>>^ Porquanto João dizia a Herodes: "Não te é permitido viver com a mulher do teu irmão".

[[v41-6-19]]

^<<v41-6-19,19>>^ Assim, Herodias o odiava e queria matá-lo. Mas não podia fazê-lo,

[[v41-6-20]]

^<<v41-6-20,20>>^ porque Herodes temia a João e o protegia, sabendo que ele era um homem justo e santo; e quando o ouvia, ficava perplexo. Mesmo assim gostava de ouvi-lo.

[[v41-6-21]]

^<<v41-6-21,21>>^ Finalmente chegou uma ocasião oportuna. No seu aniversário, Herodes ofereceu um banquete aos seus líderes mais importantes, aos comandantes militares e às principais personalidades da Galiléia.

[[v41-6-22]]

^<<v41-6-22,22>>^ Quando a filha de Herodias entrou e dançou, agradou a Herodes e aos convidados. O rei disse à jovem: "Peça-me qualquer coisa que você quiser, e eu lhe darei".

[[v41-6-23]]

^<<v41-6-23,23>>^ E prometeu-lhe sob juramento: "Seja o que for que me pedir, eu lhe darei, até a metade do meu reino".

[[v41-6-24]]

^<<v41-6-24,24>>^ Ela saiu e disse à sua mãe: "Que pedirei? " "A cabeça de João Batista", respondeu ela.

[[v41-6-25]]

^<<v41-6-25,25>>^ Imediatamente a jovem apressou-se em apresentar-se ao rei com o pedido: "Desejo que me dês agora mesmo a cabeça de João Batista num prato".

[[v41-6-26]]

^<<v41-6-26,26>>^ O rei ficou muito aflito, mas por causa do seu juramento e dos convidados, não quis negar o pedido à jovem.

[[v41-6-27]]

^<<v41-6-27,27>>^ Assim enviou imediatamente um carrasco com ordens para trazer a cabeça de João. O homem foi, decapitou João na prisão

[[v41-6-28]]

^<<v41-6-28,28>>^ e trouxe sua cabeça num prato. Ele a entregou à jovem, e esta a deu à sua mãe.

[[v41-6-29]]

^<<v41-6-29,29>>^ Tendo ouvido isso, os discípulos de João vieram, levaram o seu corpo e o colocaram num túmulo.

[[v41-6-30]]

^<<v41-6-30,30>>^ Os apóstolos reuniram-se a Jesus e lhe relataram tudo o que tinham feito e ensinado.

[[v41-6-31]]

^<<v41-6-31,31>>^ Havia muita gente indo e vindo, a ponto de eles não terem tempo para comer. Jesus lhes disse: "Venham comigo para um lugar deserto e descansem um pouco".

[[v41-6-32]]

^<<v41-6-32,32>>^ Assim, eles se afastaram num barco para um lugar deserto.

[[v41-6-33]]

^<<v41-6-33,33>>^ Mas muitos dos que os viram retirar-se, tendo-os reconhecido, correram a pé de todas as cidades e chegaram lá antes deles.

[[v41-6-34]]

^<<v41-6-34,34>>^ Quando Jesus saiu do barco e viu uma grande multidão, teve compaixão deles, porque eram como ovelhas sem pastor. Então começou a ensinar-lhes muitas coisas.

[[v41-6-35]]

^<<v41-6-35,35>>^ Já era tarde e, por isso, os seus discípulos aproximaram-se dele e disseram: "Este é um lugar deserto, e já é tarde.

[[v41-6-36]]

^<<v41-6-36,36>>^ Manda embora o povo para que possa ir aos campos e povoados vizinhos comprar algo para comer".

[[v41-6-37]]

^<<v41-6-37,37>>^ Ele, porém, respondeu: "Dêem-lhes vocês algo para comer". Eles lhe disseram: "Isto exigiria duzentos denários! Devemos gastar tanto dinheiro em pão e dar-lhes de comer? "

[[v41-6-38]]

^<<v41-6-38,38>>^ Perguntou ele: "Quantos pães vocês têm? Verifiquem". Quando ficaram sabendo, disseram: "Cinco pães e dois peixes".

[[v41-6-39]]

^<<v41-6-39,39>>^ Então Jesus ordenou que fizessem todo o povo assentar-se em grupos na grama verde.

[[v41-6-40]]

^<<v41-6-40,40>>^ Assim, eles se assentaram em grupos de cem e de cinqüenta.

[[v41-6-41]]

^<<v41-6-41,41>>^ Tomando os cinco pães e os dois peixes e, olhando para o céu, deu graças e partiu os pães. Em seguida, entregou-os aos seus discípulos para que os servissem ao povo. E também dividiu os dois peixes entre todos eles.

[[v41-6-42]]

^<<v41-6-42,42>>^ Todos comeram e ficaram satisfeitos,

[[v41-6-43]]

^<<v41-6-43,43>>^ e os discípulos recolheram doze cestos cheios de pedaços de pão e de peixe.

[[v41-6-44]]

^<<v41-6-44,44>>^ Os que comeram foram cinco mil homens.

[[v41-6-45]]

^<<v41-6-45,45>>^ Logo em seguida, Jesus insistiu com os discípulos para que entrassem no barco e fossem adiante dele para Betsaida, enquanto ele despedia a multidão.

[[v41-6-46]]

^<<v41-6-46,46>>^ Tendo-a despedido, subiu a um monte para orar.

[[v41-6-47]]

^<<v41-6-47,47>>^ Ao anoitecer, o barco estava no meio do mar, e Jesus se achava sozinho em terra.

[[v41-6-48]]

^<<v41-6-48,48>>^ Ele viu os discípulos remando com dificuldade, porque o vento soprava contra eles. Alta madrugada, Jesus dirigiu-se a eles, andando sobre o mar; e estava já a ponto de passar por eles.

[[v41-6-49]]

^<<v41-6-49,49>>^ Quando o viram andando sobre o mar, pensaram que fosse um fantasma. Então gritaram,

[[v41-6-50]]

^<<v41-6-50,50>>^ pois todos o tinham visto e ficam aterrorizados. Mas Jesus imediatamente lhes disse: "Coragem! Sou eu! Não tenham medo! "

[[v41-6-51]]

^<<v41-6-51,51>>^ Então subiu no barco para junto deles, e o vento se acalmou; e eles ficaram atônitos,

[[v41-6-52]]

^<<v41-6-52,52>>^ pois não tinham entendido o milagre dos pães. Seus corações estavam endurecidos.

[[v41-6-53]]

^<<v41-6-53,53>>^ Depois de atravessarem o mar, chegaram a Genesaré e ali amarraram o barco.

[[v41-6-54]]

^<<v41-6-54,54>>^ Logo que desembarcaram, o povo reconheceu Jesus.

[[v41-6-55]]

^<<v41-6-55,55>>^ Eles percorriam toda aquela região e levavam os doentes em macas, para onde ouviam que ele estava.

[[v41-6-56]]

^<<v41-6-56,56>>^ E aonde quer que ele fosse, povoados, cidades ou campos, levavam os doentes para as praças. Suplicavam-lhe que pudessem pelo menos tocar na borda do seu manto; e todos os que nele tocavam eram curados.

'''

xref:041-marcos/041-marcos-005.adoc#v41-5-0[&#60; Capítulo Anterior] | <<v41-6-0,Topo>> | xref:041-marcos/041-marcos-007.adoc#v41-7-0[Próximo Capítulo &#62;]