include::./index.adoc[]

[[v41-2-0]]
=== Marcos, 2
// nvi ?, NVI - Nova Versão Internacional

[[v41-2-1]]

^<<v41-2-1,1>>^ Poucos dias depois, tendo Jesus entrado novamente em Cafarnaum, o povo ouviu falar que ele estava em casa.

[[v41-2-2]]

^<<v41-2-2,2>>^ Então muita gente se reuniu ali, de forma que não havia lugar nem junto à porta; e ele lhes pregava a palavra.

[[v41-2-3]]

^<<v41-2-3,3>>^ Vieram alguns homens, trazendo-lhe um paralítico, carregado por quatro deles.

[[v41-2-4]]

^<<v41-2-4,4>>^ Não podendo levá-lo até Jesus, por causa da multidão, removeram parte da cobertura do lugar onde Jesus estava e, através de uma abertura no teto, baixaram a maca em que estava deitado o paralítico.

[[v41-2-5]]

^<<v41-2-5,5>>^ Vendo a fé que eles tinham, Jesus disse ao paralítico: "Filho, os seus pecados estão perdoados".

[[v41-2-6]]

^<<v41-2-6,6>>^ Estavam sentados ali alguns mestres da lei, raciocinando em seu íntimo:

[[v41-2-7]]

^<<v41-2-7,7>>^ "Por que esse homem fala assim? Está blasfemando! Quem pode perdoar pecados, a não ser somente Deus? "

[[v41-2-8]]

^<<v41-2-8,8>>^ Jesus percebeu logo em seu espírito que era isso que eles estavam pensando e lhes disse: "Por que vocês estão remoendo essas coisas em seus corações?

[[v41-2-9]]

^<<v41-2-9,9>>^ Que é mais fácil dizer ao paralítico: ‘Os seus pecados estão perdoados’, ou: ‘Levante-se, pegue a sua maca e ande’?

[[v41-2-10]]

^<<v41-2-10,10>>^ Mas, para que vocês saibam que o Filho do homem tem na terra autoridade para perdoar pecados — disse ao paralítico —

[[v41-2-11]]

^<<v41-2-11,11>>^ eu lhe digo: Levante-se, pegue a sua maca e vá para casa".

[[v41-2-12]]

^<<v41-2-12,12>>^ Ele se levantou, pegou a maca e saiu à vista de todos. Estes ficaram atônitos e glorificaram a Deus, dizendo: "Nunca vimos nada igual! "

[[v41-2-13]]

^<<v41-2-13,13>>^ Jesus saiu outra vez para beira-mar. Uma grande multidão aproximou-se, e ele começou a ensiná-los.

[[v41-2-14]]

^<<v41-2-14,14>>^ Passando por ali, viu Levi, filho de Alfeu, sentado na coletoria, e disse-lhe: "Siga-me". Levi levantou-se e o seguiu.

[[v41-2-15]]

^<<v41-2-15,15>>^ Durante uma refeição na casa de Levi, muitos publicanos e "pecadores" estavam comendo com Jesus e seus discípulos, pois havia muitos que o seguiam.

[[v41-2-16]]

^<<v41-2-16,16>>^ Quando os mestres da lei que eram fariseus o viram comendo com "pecadores" e publicanos, perguntaram aos discípulos de Jesus: "Por que ele come com publicanos e ‘pecadores’? "

[[v41-2-17]]

^<<v41-2-17,17>>^ Ouvindo isso, Jesus lhes disse: "Não são os que têm saúde que precisam de médico, mas sim os doentes. Eu não vim para chamar justos, mas pecadores".

[[v41-2-18]]

^<<v41-2-18,18>>^ Os discípulos de João e os fariseus estavam jejuando. Algumas pessoas vieram a Jesus e lhe perguntaram: "Por que os discípulos de João e os dos fariseus jejuam, mas os teus não? "

[[v41-2-19]]

^<<v41-2-19,19>>^ Jesus respondeu: "Como podem os convidados do noivo jejuar enquanto este está com eles? Não podem, enquanto o têm consigo.

[[v41-2-20]]

^<<v41-2-20,20>>^ Mas virão dias quando o noivo lhes será tirado; e nesse tempo jejuarão.

[[v41-2-21]]

^<<v41-2-21,21>>^ "Ninguém põe remendo de pano novo em roupa velha, pois o remendo forçará a roupa, tornando pior o rasgo.

[[v41-2-22]]

^<<v41-2-22,22>>^ E ninguém põe vinho novo em vasilhas de couro velhas; se o fizer, o vinho rebentará as vasilhas, e tanto o vinho quanto as vasilhas se estragarão. Pelo contrário, põe-se vinho novo em vasilhas de couro novas".

[[v41-2-23]]

^<<v41-2-23,23>>^ Certo sábado Jesus estava passando pelas lavouras de cereal. Enquanto caminhavam, seus discípulos começaram a colher espigas.

[[v41-2-24]]

^<<v41-2-24,24>>^ Os fariseus lhe perguntaram: "Olha, por que eles estão fazendo o que não é permitido no sábado? "

[[v41-2-25]]

^<<v41-2-25,25>>^ Ele respondeu: "Vocês nunca leram o que fez Davi quando ele e seus companheiros estavam necessitados e com fome?

[[v41-2-26]]

^<<v41-2-26,26>>^ Nos dias de Abiatar, o sumo sacerdote, ele entrou na casa de Deus e comeu os pães da Presença, que apenas aos sacerdotes era permitido comer, e os deu também aos seus companheiros".

[[v41-2-27]]

^<<v41-2-27,27>>^ E então lhes disse: "O sábado foi feito por causa do homem, e não o homem por causa do sábado.

[[v41-2-28]]

^<<v41-2-28,28>>^ Assim, pois, o Filho do homem é Senhor até mesmo do sábado".

'''

xref:041-marcos/041-marcos-001.adoc#v41-1-0[&#60; Capítulo Anterior] | <<v41-2-0,Topo>> | xref:041-marcos/041-marcos-003.adoc#v41-3-0[Próximo Capítulo &#62;]