include::./index.adoc[]

[[v41-5-0]]
=== Marcos, 5
// nvi ?, NVI - Nova Versão Internacional

[[v41-5-1]]

^<<v41-5-1,1>>^ Eles atravessaram o mar e foram para a região dos gerasenos.

[[v41-5-2]]

^<<v41-5-2,2>>^ Quando Jesus desembarcou, um homem com um espírito imundo veio dos sepulcros ao seu encontro.

[[v41-5-3]]

^<<v41-5-3,3>>^ Esse homem vivia nos sepulcros, e ninguém conseguia prendê-lo, nem mesmo com correntes;

[[v41-5-4]]

^<<v41-5-4,4>>^ pois muitas vezes lhe haviam sido acorrentados pés e mãos, mas ele arrebentara as correntes e quebrara os ferros de seus pés. Ninguém era suficientemente forte para dominá-lo.

[[v41-5-5]]

^<<v41-5-5,5>>^ Noite e dia ele andava gritando e cortando-se com pedras entre os sepulcros e nas colinas.

[[v41-5-6]]

^<<v41-5-6,6>>^ Quando ele viu Jesus de longe, correu e prostrou-se diante dele,

[[v41-5-7]]

^<<v41-5-7,7>>^ e gritou em alta voz: "Que queres comigo, Jesus, Filho do Deus Altíssimo? Rogo-te por Deus que não me atormentes! "

[[v41-5-8]]

^<<v41-5-8,8>>^ Pois Jesus lhe tinha dito: "Saia deste homem, espírito imundo! "

[[v41-5-9]]

^<<v41-5-9,9>>^ Então Jesus lhe perguntou: "Qual é o seu nome? " "Meu nome é Legião", respondeu ele, "porque somos muitos".

[[v41-5-10]]

^<<v41-5-10,10>>^ E implorava a Jesus, com insistência, que não os mandasse sair daquela região.

[[v41-5-11]]

^<<v41-5-11,11>>^ Uma grande manada de porcos estava pastando numa colina próxima.

[[v41-5-12]]

^<<v41-5-12,12>>^ Os demônios imploraram a Jesus: "Manda-nos para os porcos, para que entremos neles".

[[v41-5-13]]

^<<v41-5-13,13>>^ Ele lhes deu permissão, e os espíritos imundos saíram e entraram nos porcos. A manada de cerca de dois mil porcos atirou-se precipício abaixo, em direção ao mar, e nele se afogou.

[[v41-5-14]]

^<<v41-5-14,14>>^ Os que cuidavam dos porcos fugiram e contaram esses fatos na cidade e nos campos, e o povo foi ver o que havia acontecido.

[[v41-5-15]]

^<<v41-5-15,15>>^ Quando se aproximaram de Jesus, viram ali o homem que fora possesso da legião de demônios, assentado, vestido e em perfeito juízo; e ficaram com medo.

[[v41-5-16]]

^<<v41-5-16,16>>^ Os que o tinham visto contaram ao povo o que acontecera ao endemoninhado, e falaram também sobre os porcos.

[[v41-5-17]]

^<<v41-5-17,17>>^ Então o povo começou a suplicar a Jesus que saísse do território deles.

[[v41-5-18]]

^<<v41-5-18,18>>^ Quando Jesus estava entrando no barco, o homem que estivera endemoninhado suplicava-lhe que o deixasse ir com ele.

[[v41-5-19]]

^<<v41-5-19,19>>^ Jesus não o permitiu, mas disse: "Vá para casa, para a sua família e anuncie-lhes quanto o Senhor fez por você e como teve misericórdia de você".

[[v41-5-20]]

^<<v41-5-20,20>>^ Então, aquele homem se foi e começou a anunciar em Decápolis quanto Jesus tinha feito por ele. Todos ficavam admirados.

[[v41-5-21]]

^<<v41-5-21,21>>^ Tendo Jesus voltado de barco para a outra margem, uma grande multidão se reuniu ao seu redor, enquanto ele estava à beira do mar.

[[v41-5-22]]

^<<v41-5-22,22>>^ Então chegou ali um dos dirigentes da sinagoga, chamado Jairo. Vendo Jesus, prostrou-se aos seus pés

[[v41-5-23]]

^<<v41-5-23,23>>^ e lhe implorou insistentemente: "Minha filhinha está morrendo! Vem, por favor, e impõe as mãos sobre ela, para que seja curada e viva".

[[v41-5-24]]

^<<v41-5-24,24>>^ Jesus foi com ele. Uma grande multidão o seguia e o comprimia.

[[v41-5-25]]

^<<v41-5-25,25>>^ E estava ali certa mulher que havia doze anos vinha sofrendo de uma hemorragia.

[[v41-5-26]]

^<<v41-5-26,26>>^ Ela padecera muito sob o cuidado de vários médicos e gastara tudo o que tinha, mas, em vez de melhorar, piorava.

[[v41-5-27]]

^<<v41-5-27,27>>^ Quando ouviu falar de Jesus, chegou-se por trás dele, no meio da multidão, e tocou em seu manto,

[[v41-5-28]]

^<<v41-5-28,28>>^ porque pensava: "Se eu tão-somente tocar em seu manto, ficarei curada".

[[v41-5-29]]

^<<v41-5-29,29>>^ Imediatamente cessou sua hemorragia e ela sentiu em seu corpo que estava livre do seu sofrimento.

[[v41-5-30]]

^<<v41-5-30,30>>^ No mesmo instante, Jesus percebeu que dele havia saído poder, virou-se para a multidão e perguntou: "Quem tocou em meu manto? "

[[v41-5-31]]

^<<v41-5-31,31>>^ Responderam os seus discípulos: "Vês a multidão aglomerada ao teu redor e ainda perguntas: ‘Quem tocou em mim? ’ "

[[v41-5-32]]

^<<v41-5-32,32>>^ Mas Jesus continuou olhando ao seu redor para ver quem tinha feito aquilo.

[[v41-5-33]]

^<<v41-5-33,33>>^ Então a mulher, sabendo o que lhe tinha acontecido, aproximou-se, prostrou-se aos seus pés e, tremendo de medo, contou-lhe toda a verdade.

[[v41-5-34]]

^<<v41-5-34,34>>^ Então ele lhe disse: "Filha, a sua fé a curou! Vá em paz e fique livre do seu sofrimento".

[[v41-5-35]]

^<<v41-5-35,35>>^ Enquanto Jesus ainda estava falando, chegaram algumas pessoas da casa de Jairo, o dirigente da sinagoga. "Sua filha morreu", disseram eles. "Não precisa mais incomodar o mestre! "

[[v41-5-36]]

^<<v41-5-36,36>>^ Não fazendo caso do que eles disseram, Jesus disse ao dirigente da sinagoga: "Não tenha medo; tão-somente creia".

[[v41-5-37]]

^<<v41-5-37,37>>^ E não deixou ninguém segui-lo, senão Pedro, Tiago e João, irmão de Tiago.

[[v41-5-38]]

^<<v41-5-38,38>>^ Quando chegaram à casa do dirigente da sinagoga, Jesus viu um alvoroço, com gente chorando e se lamentando em alta voz.

[[v41-5-39]]

^<<v41-5-39,39>>^ Então entrou e lhes disse: "Por que todo este alvoroço e lamento? A criança não está morta, mas dorme".

[[v41-5-40]]

^<<v41-5-40,40>>^ Mas todos começaram a rir de Jesus. Ele, porém, ordenou que eles saíssem, tomou consigo o pai e a mãe da criança e os discípulos que estavam com ele, e entrou onde se encontrava a criança.

[[v41-5-41]]

^<<v41-5-41,41>>^ Tomou-a pela mão e lhe disse: "Talita cumi! ", que significa: "Menina, eu lhe ordeno, levante-se! ".

[[v41-5-42]]

^<<v41-5-42,42>>^ Imediatamente a menina, que tinha doze anos de idade, levantou-se e começou a andar. Isso os deixou atônitos.

[[v41-5-43]]

^<<v41-5-43,43>>^ Ele deu ordens expressas para que não dissessem nada a ninguém e mandou que dessem a ela alguma coisa para comer.

'''

xref:041-marcos/041-marcos-004.adoc#v41-4-0[&#60; Capítulo Anterior] | <<v41-5-0,Topo>> | xref:041-marcos/041-marcos-006.adoc#v41-6-0[Próximo Capítulo &#62;]