include::./index.adoc[]

[[v41-12-0]]
=== Marcos, 12
// nvi ?, NVI - Nova Versão Internacional

[[v41-12-1]]

^<<v41-12-1,1>>^ Então Jesus começou a lhes falar por parábolas: "Certo homem plantou uma vinha, colocou uma cerca ao redor dela, cavou um tanque para prensar as uvas e construiu uma torre. Depois arrendou a vinha a alguns lavradores e foi fazer uma viagem.

[[v41-12-2]]

^<<v41-12-2,2>>^ Na época da colheita, enviou um servo aos lavradores, para receber deles parte do fruto da vinha.

[[v41-12-3]]

^<<v41-12-3,3>>^ Mas eles o agarraram e espancaram, e o mandaram embora de mãos vazias.

[[v41-12-4]]

^<<v41-12-4,4>>^ Então enviou-lhes outro servo; e lhe bateram na cabeça e o humilharam.

[[v41-12-5]]

^<<v41-12-5,5>>^ E enviou ainda outro, o qual mataram. Enviou muitos outros; em alguns bateram, a outros mataram.

[[v41-12-6]]

^<<v41-12-6,6>>^ "Faltava-lhe ainda um para enviar: seu filho amado. Por fim o enviou, dizendo: ‘A meu filho respeitarão’.

[[v41-12-7]]

^<<v41-12-7,7>>^ "Mas os lavradores disseram uns aos outros: ‘Este é o herdeiro. Venham, vamos matá-lo, e a herança será nossa’.

[[v41-12-8]]

^<<v41-12-8,8>>^ Assim eles o agarraram, e o mataram, e o lançaram para fora da vinha.

[[v41-12-9]]

^<<v41-12-9,9>>^ "O que fará então o dono da vinha? Virá e matará aqueles lavradores e dará a vinha a outros.

[[v41-12-10]]

^<<v41-12-10,10>>^ Vocês nunca leram esta passagem das Escrituras? ‘A pedra que os construtores rejeitaram tornou-se a pedra angular;

[[v41-12-11]]

^<<v41-12-11,11>>^ isso vem do Senhor, e é algo maravilhoso para nós’ ".

[[v41-12-12]]

^<<v41-12-12,12>>^ Então começaram a procurar um meio de prendê-lo, pois perceberam que era contra eles que ele havia contado aquela parábola. Mas tinham medo da multidão; por isso o deixaram e foram embora.

[[v41-12-13]]

^<<v41-12-13,13>>^ Mais tarde enviaram a Jesus alguns dos fariseus e herodianos para o apanharem em alguma coisa que ele dissesse.

[[v41-12-14]]

^<<v41-12-14,14>>^ Estes se aproximaram dele e disseram: "Mestre, sabemos que és íntegro e que não te deixas influenciar por ninguém, porque não te prendes à aparência dos homens, mas ensinas o caminho de Deus conforme a verdade. É certo pagar imposto a César ou não?

[[v41-12-15]]

^<<v41-12-15,15>>^ Devemos pagar ou não? " Mas Jesus, percebendo a hipocrisia deles, perguntou: "Por que vocês estão me pondo à prova? Tragam-me um denário para que eu o veja".

[[v41-12-16]]

^<<v41-12-16,16>>^ Eles lhe trouxeram a moeda, e ele lhes perguntou: "De quem é esta imagem e esta inscrição? " "De César", responderam eles.

[[v41-12-17]]

^<<v41-12-17,17>>^ Então Jesus lhes disse: "Dêem a César o que é de César e a Deus o que é de Deus". E ficaram admirados com ele.

[[v41-12-18]]

^<<v41-12-18,18>>^ Depois os saduceus, que dizem que não há ressurreição, aproximaram-se dele com a seguinte questão:

[[v41-12-19]]

^<<v41-12-19,19>>^ "Mestre, Moisés nos deixou escrito que, se o irmão de um homem morrer e deixar mulher sem filhos, este deverá casar-se com a viúva e ter filhos para seu irmão.

[[v41-12-20]]

^<<v41-12-20,20>>^ Havia sete irmãos. O primeiro casou-se e morreu sem deixar filhos.

[[v41-12-21]]

^<<v41-12-21,21>>^ O segundo casou-se com a viúva, mas também morreu sem deixar filhos. O mesmo aconteceu com o terceiro.

[[v41-12-22]]

^<<v41-12-22,22>>^ Nenhum dos sete deixou filhos. Finalmente, morreu também a mulher.

[[v41-12-23]]

^<<v41-12-23,23>>^ Na ressurreição, de quem ela será esposa, visto que os sete foram casados com ela? "

[[v41-12-24]]

^<<v41-12-24,24>>^ Jesus respondeu: "Vocês estão enganados! Pois não conhecem as Escrituras nem o poder de Deus!

[[v41-12-25]]

^<<v41-12-25,25>>^ Quando os mortos ressuscitam, não se casam nem são dados em casamento, mas são como os anjos nos céus.

[[v41-12-26]]

^<<v41-12-26,26>>^ Quanto à ressurreição dos mortos, vocês não leram no livro de Moisés, no relato da sarça, como Deus lhe disse: ‘Eu sou o Deus de Abraão, o Deus de Isaque e o Deus de Jacó’?

[[v41-12-27]]

^<<v41-12-27,27>>^ Ele não é Deus de mortos, mas de vivos. Vocês estão muito enganados! "

[[v41-12-28]]

^<<v41-12-28,28>>^ Um dos mestres da lei aproximou-se e os ouviu discutindo. Notando que Jesus lhes dera uma boa resposta, perguntou-lhe: "De todos os mandamentos, qual é o mais importante? "

[[v41-12-29]]

^<<v41-12-29,29>>^ Respondeu Jesus: "O mais importante é este: ‘Ouve, ó Israel, o Senhor, o nosso Deus, o Senhor é o único Senhor.

[[v41-12-30]]

^<<v41-12-30,30>>^ Ame o Senhor, o seu Deus de todo o seu coração, de toda a sua alma, de todo o seu entendimento e de todas as suas forças’.

[[v41-12-31]]

^<<v41-12-31,31>>^ O segundo é este: ‘Ame o seu próximo como a si mesmo’. Não existe mandamento maior do que estes".

[[v41-12-32]]

^<<v41-12-32,32>>^ "Muito bem, mestre", disse o homem. "Estás certo ao dizeres que Deus é único e que não existe outro além dele.

[[v41-12-33]]

^<<v41-12-33,33>>^ Amá-lo de todo o coração, de todo o entendimento e de todas as forças, e amar ao próximo como a si mesmo é mais importante do que todos os sacrifícios e ofertas".

[[v41-12-34]]

^<<v41-12-34,34>>^ Vendo que ele tinha respondido sabiamente, Jesus lhe disse: "Você não está longe do Reino de Deus". Daí por diante ninguém mais ousava lhe fazer perguntas.

[[v41-12-35]]

^<<v41-12-35,35>>^ Ensinando no templo, Jesus perguntou: "Como os mestres da lei dizem que o Cristo é filho de Davi?

[[v41-12-36]]

^<<v41-12-36,36>>^ O próprio Davi, falando pelo Espírito Santo, disse: ‘O Senhor disse ao meu Senhor: Senta-te à minha direita até que eu ponha os teus inimigos debaixo de teus pés’.

[[v41-12-37]]

^<<v41-12-37,37>>^ O próprio Davi o chama ‘Senhor’. Como pode, então, ser ele seu filho? " E a grande multidão o ouvia com prazer.

[[v41-12-38]]

^<<v41-12-38,38>>^ Ao ensinar, Jesus dizia: "Cuidado com os mestres da lei. Eles fazem questão de andar com roupas especiais, de receber saudações nas praças

[[v41-12-39]]

^<<v41-12-39,39>>^ e de ocupar os lugares mais importantes nas sinagogas e os lugares de honra nos banquetes.

[[v41-12-40]]

^<<v41-12-40,40>>^ Eles devoram as casas das viúvas, e, para disfarçar, fazem longas orações. Esses receberão condenação mais severa! "

[[v41-12-41]]

^<<v41-12-41,41>>^ Jesus sentou-se em frente do lugar onde eram colocadas as contribuições, e observava a multidão colocando o dinheiro nas caixas de ofertas. Muitos ricos lançavam ali grandes quantias.

[[v41-12-42]]

^<<v41-12-42,42>>^ Então, uma viúva pobre chegou-se e colocou duas pequeninas moedas de cobre, de muito pouco valor.

[[v41-12-43]]

^<<v41-12-43,43>>^ Chamando a si os seus discípulos, Jesus declarou: "Afirmo-lhes que esta viúva pobre colocou na caixa de ofertas mais do que todos os outros.

[[v41-12-44]]

^<<v41-12-44,44>>^ Todos deram do que lhes sobrava; mas ela, da sua pobreza, deu tudo o que possuía para viver".

'''

xref:041-marcos/041-marcos-011.adoc#v41-11-0[&#60; Capítulo Anterior] | <<v41-12-0,Topo>> | xref:041-marcos/041-marcos-013.adoc#v41-13-0[Próximo Capítulo &#62;]