include::./index.adoc[]

[[v43-20-0]]
=== João, 20
// nvi ?, NVI - Nova Versão Internacional

[[v43-20-1]]

^<<v43-20-1,1>>^ No primeiro dia da semana, bem cedo, estando ainda escuro, Maria Madalena chegou ao sepulcro e viu que a pedra da entrada tinha sido removida.

[[v43-20-2]]

^<<v43-20-2,2>>^ Então correu ao encontro de Simão Pedro e do outro discípulo, aquele a quem Jesus amava, e disse: "Tiraram o Senhor do sepulcro, e não sabemos onde o colocaram! "

[[v43-20-3]]

^<<v43-20-3,3>>^ Pedro e o outro discípulo saíram e foram para o sepulcro.

[[v43-20-4]]

^<<v43-20-4,4>>^ Os dois corriam, mas o outro discípulo foi mais rápido que Pedro e chegou primeiro ao sepulcro.

[[v43-20-5]]

^<<v43-20-5,5>>^ Ele se curvou e olhou para dentro, viu as faixas de linho ali, mas não entrou.

[[v43-20-6]]

^<<v43-20-6,6>>^ A seguir Simão Pedro, que vinha atrás dele, chegou, entrou no sepulcro e viu as faixas de linho,

[[v43-20-7]]

^<<v43-20-7,7>>^ bem como o lenço que estivera sobre a cabeça de Jesus. Ele estava dobrado à parte, separado das faixas de linho.

[[v43-20-8]]

^<<v43-20-8,8>>^ Depois o outro discípulo, que chegara primeiro ao sepulcro, também entrou. Ele viu e creu.

[[v43-20-9]]

^<<v43-20-9,9>>^ ( Eles ainda não haviam compreendido que, conforme a Escritura, era necessário que Jesus ressuscitasse dos mortos. )

[[v43-20-10]]

^<<v43-20-10,10>>^ Os discípulos voltaram para casa.

[[v43-20-11]]

^<<v43-20-11,11>>^ Maria, porém, ficou à entrada do sepulcro, chorando. Enquanto chorava, curvou-se para olhar dentro do sepulcro

[[v43-20-12]]

^<<v43-20-12,12>>^ e viu dois anjos vestidos de branco, sentados onde estivera o corpo de Jesus, um à cabeceira e o outro aos pés.

[[v43-20-13]]

^<<v43-20-13,13>>^ Eles lhe perguntaram: "Mulher, por que você está chorando? " "Levaram embora o meu Senhor", respondeu ela, "e não sei onde o puseram".

[[v43-20-14]]

^<<v43-20-14,14>>^ Nisso ela se voltou e viu Jesus ali, em pé, mas não o reconheceu.

[[v43-20-15]]

^<<v43-20-15,15>>^ Disse ele: "Mulher, por que está chorando? Quem você está procurando? " Pensando que fosse o jardineiro, ela disse: "Se o senhor o levou embora, diga-me onde o colocou, e eu o levarei".

[[v43-20-16]]

^<<v43-20-16,16>>^ Jesus lhe disse: "Maria! " Então, voltando-se para ele, Maria exclamou em aramaico: "Rabôni! " ( que significa Mestre ).

[[v43-20-17]]

^<<v43-20-17,17>>^ Jesus disse: "Não me segure, pois ainda não voltei para o Pai. Vá, porém, a meus irmãos e diga-lhes: Estou voltando para meu Pai e Pai de vocês, para meu Deus e Deus de vocês".

[[v43-20-18]]

^<<v43-20-18,18>>^ Maria Madalena foi e anunciou aos discípulos: "Eu vi o Senhor! " E contou o que ele lhe dissera.

[[v43-20-19]]

^<<v43-20-19,19>>^ Ao cair da tarde daquele primeiro dia da semana, estando os discípulos reunidos a portas trancadas, por medo dos judeus, Jesus entrou, pôs-se no meio deles e disse: "Paz seja com vocês! "

[[v43-20-20]]

^<<v43-20-20,20>>^ Tendo dito isso, mostrou-lhes as mãos e o lado. Os discípulos alegraram-se quando viram o Senhor.

[[v43-20-21]]

^<<v43-20-21,21>>^ Novamente Jesus disse: "Paz seja com vocês! Assim como o Pai me enviou, eu os envio".

[[v43-20-22]]

^<<v43-20-22,22>>^ E com isso, soprou sobre eles e disse: "Recebam o Espírito Santo.

[[v43-20-23]]

^<<v43-20-23,23>>^ Se perdoarem os pecados de alguém, estarão perdoados; se não os perdoarem, não estarão perdoados".

[[v43-20-24]]

^<<v43-20-24,24>>^ Tomé, chamado Dídimo, um dos Doze, não estava com os discípulos quando Jesus apareceu.

[[v43-20-25]]

^<<v43-20-25,25>>^ Os outros discípulos lhe disseram: "Vimos o Senhor! " Mas ele lhes disse: "Se eu não vir as marcas dos pregos nas suas mãos, não colocar o meu dedo onde estavam os pregos e não puser a minha mão no seu lado, não crerei".

[[v43-20-26]]

^<<v43-20-26,26>>^ Uma semana mais tarde, os seus discípulos estavam outra vez ali, e Tomé com eles. Apesar de estarem trancadas as portas, Jesus entrou, pôs-se no meio deles e disse: "Paz seja com vocês! "

[[v43-20-27]]

^<<v43-20-27,27>>^ E Jesus disse a Tomé: "Coloque o seu dedo aqui; veja as minhas mãos. Estenda a mão e coloque-a no meu lado. Pare de duvidar e creia".

[[v43-20-28]]

^<<v43-20-28,28>>^ Disse-lhe Tomé: "Senhor meu e Deus meu! "

[[v43-20-29]]

^<<v43-20-29,29>>^ Então Jesus lhe disse: "Porque me viu, você creu? Felizes os que não viram e creram".

[[v43-20-30]]

^<<v43-20-30,30>>^ Jesus realizou na presença dos seus discípulos muitos outros sinais miraculosos, que não estão registrados neste livro.

[[v43-20-31]]

^<<v43-20-31,31>>^ Mas estes foram escritos para que vocês creiam que Jesus é o Cristo, o Filho de Deus e, crendo, tenham vida em seu nome.

'''

xref:043-joao/043-joao-019.adoc#v43-19-0[&#60; Capítulo Anterior] | <<v43-20-0,Topo>> | xref:043-joao/043-joao-021.adoc#v43-21-0[Próximo Capítulo &#62;]