include::./index.adoc[]

[[v43-1-0]]
=== João, 1
// nvi ?, NVI - Nova Versão Internacional

[[v43-1-1]]

^<<v43-1-1,1>>^ No princípio era aquele que é a Palavra. Ele estava com Deus, e era Deus.

[[v43-1-2]]

^<<v43-1-2,2>>^ Ela estava com Deus no princípio.

[[v43-1-3]]

^<<v43-1-3,3>>^ Todas as coisas foram feitas por intermédio dele; sem ele, nada do que existe teria sido feito.

[[v43-1-4]]

^<<v43-1-4,4>>^ Nele estava a vida, e esta era a luz dos homens.

[[v43-1-5]]

^<<v43-1-5,5>>^ A luz brilha nas trevas, e as trevas não a derrotaram.

[[v43-1-6]]

^<<v43-1-6,6>>^ Surgiu um homem enviado por Deus, chamado João.

[[v43-1-7]]

^<<v43-1-7,7>>^ Ele veio como testemunha, para testificar acerca da luz, a fim de que por meio dele todos os homens cressem.

[[v43-1-8]]

^<<v43-1-8,8>>^ Ele próprio não era a luz, mas veio como testemunha da luz.

[[v43-1-9]]

^<<v43-1-9,9>>^ Estava chegando ao mundo a verdadeira luz, que ilumina todos os homens.

[[v43-1-10]]

^<<v43-1-10,10>>^ Aquele que é a Palavra estava no mundo, e o mundo foi feito por intermédio dele, mas o mundo não o reconheceu.

[[v43-1-11]]

^<<v43-1-11,11>>^ Veio para o que era seu, mas os seus não o receberam.

[[v43-1-12]]

^<<v43-1-12,12>>^ Contudo, aos que o receberam, aos que creram em seu nome, deu-lhes o direito de se tornarem filhos de Deus,

[[v43-1-13]]

^<<v43-1-13,13>>^ os quais não nasceram por descendência natural, nem pela vontade da carne nem pela vontade de algum homem, mas nasceram de Deus.

[[v43-1-14]]

^<<v43-1-14,14>>^ Aquele que é a Palavra tornou-se carne e viveu entre nós. Vimos a sua glória, glória como do Unigênito vindo do Pai, cheio de graça e de verdade.

[[v43-1-15]]

^<<v43-1-15,15>>^ João dá testemunho dele. Ele exclama: "Este é aquele de quem eu falei: Aquele que vem depois de mim é superior a mim, porque já existia antes de mim".

[[v43-1-16]]

^<<v43-1-16,16>>^ Todos recebemos da sua plenitude, graça sobre graça.

[[v43-1-17]]

^<<v43-1-17,17>>^ Pois a Lei foi dada por intermédio de Moisés; a graça e a verdade vieram por intermédio de Jesus Cristo.

[[v43-1-18]]

^<<v43-1-18,18>>^ Ninguém jamais viu a Deus, mas o Deus Unigênito, que está junto do Pai, o tornou conhecido.

[[v43-1-19]]

^<<v43-1-19,19>>^ Esse foi o testemunho de João, quando os judeus de Jerusalém enviaram sacerdotes e levitas para lhe perguntarem quem ele era.

[[v43-1-20]]

^<<v43-1-20,20>>^ Ele confessou e não negou; declarou abertamente: "Não sou o Cristo".

[[v43-1-21]]

^<<v43-1-21,21>>^ Perguntaram-lhe: "E então, quem é você? É Elias? " Ele disse: "Não sou". "É o Profeta? " Ele respondeu: "Não".

[[v43-1-22]]

^<<v43-1-22,22>>^ Finalmente perguntaram: "Quem é você? Dê-nos uma resposta, para que a levemos àqueles que nos enviaram. Que diz você acerca de si próprio? "

[[v43-1-23]]

^<<v43-1-23,23>>^ João respondeu com as palavras do profeta Isaías: "Eu sou a voz do que clama no deserto: ‘Façam um caminho reto para o Senhor’ ".

[[v43-1-24]]

^<<v43-1-24,24>>^ Alguns fariseus que tinham sido enviados

[[v43-1-25]]

^<<v43-1-25,25>>^ interrogaram-no: "Então, por que você batiza, se não é o Cristo, nem Elias, nem o Profeta? "

[[v43-1-26]]

^<<v43-1-26,26>>^ Respondeu João: "Eu batizo com água, mas entre vocês está alguém que vocês não conhecem.

[[v43-1-27]]

^<<v43-1-27,27>>^ Ele é aquele que vem depois de mim, cujas correias das sandálias não sou digno de desamarrar".

[[v43-1-28]]

^<<v43-1-28,28>>^ Tudo isso aconteceu em Betânia, do outro lado do Jordão, onde João estava batizando.

[[v43-1-29]]

^<<v43-1-29,29>>^ No dia seguinte João viu Jesus aproximando-se e disse: "Vejam! É o Cordeiro de Deus, que tira o pecado do mundo!

[[v43-1-30]]

^<<v43-1-30,30>>^ Este é aquele a quem eu me referi, quando disse: Vem depois de mim um homem que é superior a mim, porque já existia antes de mim.

[[v43-1-31]]

^<<v43-1-31,31>>^ Eu mesmo não o conhecia, mas por isso é que vim batizando com água: para que ele viesse a ser revelado a Israel".

[[v43-1-32]]

^<<v43-1-32,32>>^ Então João deu o seguinte testemunho: "Eu vi o Espírito descer do céu como pomba e permanecer sobre ele.

[[v43-1-33]]

^<<v43-1-33,33>>^ Eu não o teria reconhecido, se aquele que me enviou para batizar com água não me tivesse dito: ‘Aquele sobre quem você vir o Espírito descer e permanecer, esse é o que batiza com o Espírito Santo’.

[[v43-1-34]]

^<<v43-1-34,34>>^ Eu vi e testifico que este é o Filho de Deus".

[[v43-1-35]]

^<<v43-1-35,35>>^ No dia seguinte João estava ali novamente com dois dos seus discípulos.

[[v43-1-36]]

^<<v43-1-36,36>>^ Quando viu Jesus passando, disse: "Vejam! É o Cordeiro de Deus! "

[[v43-1-37]]

^<<v43-1-37,37>>^ Ouvindo-o dizer isso, os dois discípulos seguiram a Jesus.

[[v43-1-38]]

^<<v43-1-38,38>>^ Voltando-se e vendo Jesus que os dois o seguiam, perguntou-lhes: "O que vocês querem? " Eles disseram: "Rabi", ( que significa Mestre ), "onde estás hospedado? "

[[v43-1-39]]

^<<v43-1-39,39>>^ Respondeu ele: "Venham e verão". Então foram, por volta das quatro horas da tarde, viram onde ele estava hospedado e passaram com ele aquele dia.

[[v43-1-40]]

^<<v43-1-40,40>>^ André, irmão de Simão Pedro, era um dos dois que tinham ouvido o que João dissera e que haviam seguido a Jesus.

[[v43-1-41]]

^<<v43-1-41,41>>^ O primeiro que ele encontrou foi Simão, seu irmão, e lhe disse: "Achamos o Messias" ( isto é, o Cristo ).

[[v43-1-42]]

^<<v43-1-42,42>>^ E o levou a Jesus. Jesus olhou para ele e disse: "Você é Simão, filho de João. Será chamado Cefas" ( que significa Pedro ).

[[v43-1-43]]

^<<v43-1-43,43>>^ No dia seguinte Jesus decidiu partir para a Galiléia. Quando encontrou Filipe, disse-lhe: "Siga-me".

[[v43-1-44]]

^<<v43-1-44,44>>^ Filipe, como André e Pedro, era da cidade de Betsaida.

[[v43-1-45]]

^<<v43-1-45,45>>^ Filipe encontrou Natanael e lhe disse: "Achamos aquele sobre quem Moisés escreveu na Lei, e a respeito de quem os profetas também escreveram: Jesus de Nazaré, filho de José".

[[v43-1-46]]

^<<v43-1-46,46>>^ Perguntou Natanael: "Nazaré? Pode vir alguma coisa boa de lá? " Disse Filipe: "Venha e veja".

[[v43-1-47]]

^<<v43-1-47,47>>^ Ao ver Natanael se aproximando, disse Jesus: "Aí está um verdadeiro israelita, em quem não há falsidade".

[[v43-1-48]]

^<<v43-1-48,48>>^ Perguntou Natanael: "De onde me conheces? " Jesus respondeu: "Eu o vi quando você ainda estava debaixo da figueira, antes de Filipe o chamar".

[[v43-1-49]]

^<<v43-1-49,49>>^ Então Natanael declarou: "Mestre, tu és o Filho de Deus, tu és o Rei de Israel! "

[[v43-1-50]]

^<<v43-1-50,50>>^ Jesus disse: "Você crê porque eu disse que o vi debaixo da figueira. Você verá coisas maiores do que essa! "

[[v43-1-51]]

^<<v43-1-51,51>>^ E então acrescentou: "Digo-lhes a verdade: Vocês verão o céu aberto e os anjos de Deus subindo e descendo sobre o Filho do homem".

'''

xref:042-lucas/042-lucas-024.adoc#v42-24-0[&#60; Capítulo Anterior] | <<v43-1-0,Topo>> | xref:043-joao/043-joao-002.adoc#v43-2-0[Próximo Capítulo &#62;]