include::./index.adoc[]

[[v43-13-0]]
=== João, 13
// nvi ?, NVI - Nova Versão Internacional

[[v43-13-1]]

^<<v43-13-1,1>>^ Um pouco antes da festa da Páscoa, sabendo Jesus que havia chegado o tempo em que deixaria este mundo e iria para o Pai, tendo amado os seus que estavam no mundo, amou-os até o fim.

[[v43-13-2]]

^<<v43-13-2,2>>^ Estava sendo servido o jantar, e o diabo já havia induzido Judas Iscariotes, filho de Simão, a trair Jesus.

[[v43-13-3]]

^<<v43-13-3,3>>^ Jesus sabia que o Pai havia colocado todas as coisas debaixo do seu poder, e que viera de Deus e estava voltando para Deus;

[[v43-13-4]]

^<<v43-13-4,4>>^ assim, levantou-se da mesa, tirou sua capa e colocou uma toalha em volta da cintura.

[[v43-13-5]]

^<<v43-13-5,5>>^ Depois disso, derramou água numa bacia e começou a lavar os pés dos seus discípulos, enxugando-os com a toalha que estava em sua cintura.

[[v43-13-6]]

^<<v43-13-6,6>>^ Chegou-se a Simão Pedro, que lhe disse: "Senhor, vais lavar os meus pés? "

[[v43-13-7]]

^<<v43-13-7,7>>^ Respondeu Jesus: "Você não compreende agora o que estou lhe fazendo; mais tarde, porém, entenderá".

[[v43-13-8]]

^<<v43-13-8,8>>^ Disse Pedro: "Não; nunca lavarás os meus pés". Jesus respondeu: "Se eu não os lavar, você não terá parte comigo".

[[v43-13-9]]

^<<v43-13-9,9>>^ Respondeu Simão Pedro: "Então, Senhor, não apenas os meus pés, mas também as minhas mãos e a minha cabeça! "

[[v43-13-10]]

^<<v43-13-10,10>>^ Respondeu Jesus: "Quem já se banhou precisa apenas lavar os pés; todo o seu corpo está limpo. Vocês estão limpos, mas nem todos".

[[v43-13-11]]

^<<v43-13-11,11>>^ Pois ele sabia quem iria traí-lo, e por isso disse que nem todos estavam limpos.

[[v43-13-12]]

^<<v43-13-12,12>>^ Quando terminou de lavar-lhes os pés, Jesus tornou a vestir sua capa e voltou ao seu lugar. Então lhes perguntou: "Vocês entendem o que lhes fiz?

[[v43-13-13]]

^<<v43-13-13,13>>^ Vocês me chamam ‘Mestre’ e ‘Senhor’, e com razão, pois eu o sou.

[[v43-13-14]]

^<<v43-13-14,14>>^ Pois bem, se eu, sendo Senhor e Mestre de vocês, lavei-lhes os pés, vocês também devem lavar os pés uns dos outros.

[[v43-13-15]]

^<<v43-13-15,15>>^ Eu lhes dei o exemplo, para que vocês façam como lhes fiz.

[[v43-13-16]]

^<<v43-13-16,16>>^ Digo-lhes verdadeiramente que nenhum escravo é maior do que o seu senhor, como também nenhum mensageiro é maior do que aquele que o enviou.

[[v43-13-17]]

^<<v43-13-17,17>>^ Agora que vocês sabem estas coisas, felizes serão se as praticarem".

[[v43-13-18]]

^<<v43-13-18,18>>^ "Não estou me referindo a todos vocês; conheço os que escolhi. Mas isto acontece para que se cumpra a Escritura: ‘Aquele que patilhava do meu pão voltou-se contra mim’.

[[v43-13-19]]

^<<v43-13-19,19>>^ "Estou lhes dizendo antes que aconteça, a fim de que, quando acontecer, vocês creiam que Eu Sou.

[[v43-13-20]]

^<<v43-13-20,20>>^ Eu lhes garanto: Quem receber aquele que eu enviar, estará me recebendo; e quem me recebe, recebe aquele que me enviou".

[[v43-13-21]]

^<<v43-13-21,21>>^ Depois de dizer isso, Jesus perturbou-se em espírito e declarou: "Digo-lhes que certamente um de vocês me trairá".

[[v43-13-22]]

^<<v43-13-22,22>>^ Seus discípulos olharam uns para os outros, sem saber a quem ele se referia.

[[v43-13-23]]

^<<v43-13-23,23>>^ Um deles, o discípulo a quem Jesus amava, estava reclinado ao lado dele.

[[v43-13-24]]

^<<v43-13-24,24>>^ Simão Pedro fez sinais para esse discípulo, como a dizer: "Pergunte-lhe a quem ele está se referindo".

[[v43-13-25]]

^<<v43-13-25,25>>^ Inclinando-se para Jesus, perguntou-lhe: "Senhor, quem é? "

[[v43-13-26]]

^<<v43-13-26,26>>^ Respondeu Jesus: "Aquele a quem eu der este pedaço de pão molhado no prato". Então, molhando o pedaço de pão, deu-o a Judas Iscariotes, filho de Simão.

[[v43-13-27]]

^<<v43-13-27,27>>^ Tão logo Judas comeu o pão, Satanás entrou nele. "O que você está para fazer, faça depressa", disse-lhe Jesus.

[[v43-13-28]]

^<<v43-13-28,28>>^ Mas ninguém à mesa entendeu por que Jesus lhe disse isso.

[[v43-13-29]]

^<<v43-13-29,29>>^ Visto que Judas era o encarregado do dinheiro, alguns pensaram que Jesus estava lhe dizendo que comprasse o necessário para a festa, ou que desse algo aos pobres.

[[v43-13-30]]

^<<v43-13-30,30>>^ Assim que comeu o pão, Judas saiu. E era noite.

[[v43-13-31]]

^<<v43-13-31,31>>^ Depois que Judas saiu, Jesus disse: "Agora o Filho do homem é glorificado, e Deus é glorificado nele.

[[v43-13-32]]

^<<v43-13-32,32>>^ Se Deus é glorificado nele, Deus também glorificará o Filho nele mesmo, e o glorificará em breve.

[[v43-13-33]]

^<<v43-13-33,33>>^ "Meus filhinhos, vou estar com vocês apenas mais um pouco. Vocês procurarão por mim e, como eu disse aos judeus, agora lhes digo: Para onde eu vou, vocês não podem ir.

[[v43-13-34]]

^<<v43-13-34,34>>^ "Um novo mandamento lhes dou: Amem-se uns aos outros. Como eu os amei, vocês devem amar-se uns aos outros.

[[v43-13-35]]

^<<v43-13-35,35>>^ Com isso todos saberão que vocês são meus discípulos, se vocês se amarem uns aos outros".

[[v43-13-36]]

^<<v43-13-36,36>>^ Simão Pedro lhe perguntou: "Senhor, para onde vais? " Jesus respondeu: "Para onde vou, vocês não podem me seguir agora, mas me seguirão mais tarde".

[[v43-13-37]]

^<<v43-13-37,37>>^ Pedro perguntou: "Senhor, por que não posso seguir-te agora? Darei a minha vida por ti! "

[[v43-13-38]]

^<<v43-13-38,38>>^ Então Jesus respondeu: "Você dará a vida por mim? Asseguro-lhe que, antes que o galo cante, você me negará três vezes! "

'''

xref:043-joao/043-joao-012.adoc#v43-12-0[&#60; Capítulo Anterior] | <<v43-13-0,Topo>> | xref:043-joao/043-joao-014.adoc#v43-14-0[Próximo Capítulo &#62;]