include::./index.adoc[]

[[v43-8-0]]
=== João, 8
// nvi ?, NVI - Nova Versão Internacional

[[v43-8-1]]

^<<v43-8-1,1>>^ Jesus, porém, foi para o monte das Oliveiras.

[[v43-8-2]]

^<<v43-8-2,2>>^ Ao amanhecer ele apareceu novamente no templo, onde todo o povo se reuniu ao seu redor, e ele se assentou para ensiná-lo.

[[v43-8-3]]

^<<v43-8-3,3>>^ Os mestres da lei e os fariseus trouxeram-lhe uma mulher surpreendida em adultério. Fizeram-na ficar em pé diante de todos

[[v43-8-4]]

^<<v43-8-4,4>>^ e disseram a Jesus: "Mestre, esta mulher foi surpreendida em ato de adultério.

[[v43-8-5]]

^<<v43-8-5,5>>^ Na Lei, Moisés nos ordena apedrejar tais mulheres. E o senhor, que diz? "

[[v43-8-6]]

^<<v43-8-6,6>>^ Eles estavam usando essa pergunta como armadilha, a fim de terem uma base para acusá-lo. Mas Jesus inclinou-se e começou a escrever no chão com o dedo.

[[v43-8-7]]

^<<v43-8-7,7>>^ Visto que continuavam a interrogá-lo, ele se levantou e lhes disse: "Se algum de vocês estiver sem pecado, seja o primeiro a atirar pedra nela".

[[v43-8-8]]

^<<v43-8-8,8>>^ Inclinou-se novamente e continuou escrevendo no chão.

[[v43-8-9]]

^<<v43-8-9,9>>^ Os que o ouviram foram saindo, um de cada vez, começando com os mais velhos. Jesus ficou só, com a mulher em pé diante dele.

[[v43-8-10]]

^<<v43-8-10,10>>^ Então Jesus pôs-se de pé e perguntou-lhe: "Mulher, onde estão eles? Ninguém a condenou? "

[[v43-8-11]]

^<<v43-8-11,11>>^ "Ninguém, Senhor", disse ela. Declarou Jesus: "Eu também não a condeno. Agora vá e abandone sua vida de pecado".

[[v43-8-12]]

^<<v43-8-12,12>>^ Falando novamente ao povo, Jesus disse: "Eu sou a luz do mundo. Quem me segue, nunca andará em trevas, mas terá a luz da vida".

[[v43-8-13]]

^<<v43-8-13,13>>^ Os fariseus lhe disseram: "Você está testemunhando a respeito de si próprio. O seu testemunho não é válido! "

[[v43-8-14]]

^<<v43-8-14,14>>^ Respondeu Jesus: "Ainda que eu mesmo testemunhe em meu favor, o meu testemunho é válido, pois sei de onde vim e para onde vou. Mas vocês não sabem de onde vim nem para onde vou.

[[v43-8-15]]

^<<v43-8-15,15>>^ Vocês julgam por padrões humanos; eu não julgo ninguém.

[[v43-8-16]]

^<<v43-8-16,16>>^ Mesmo que eu julgue, as minhas decisões são verdadeiras, porque não estou sozinho. Eu estou com o Pai, que me enviou.

[[v43-8-17]]

^<<v43-8-17,17>>^ Na Lei de vocês está escrito que o testemunho de dois homens é válido.

[[v43-8-18]]

^<<v43-8-18,18>>^ Eu testemunho acerca de mim mesmo; a minha outra testemunha é o Pai, que me enviou".

[[v43-8-19]]

^<<v43-8-19,19>>^ Então lhe perguntaram: "Onde está o seu pai? " Respondeu Jesus: "Vocês não conhecem nem a mim nem a meu Pai. Se me conhecessem, também conheceriam a meu Pai".

[[v43-8-20]]

^<<v43-8-20,20>>^ Ele proferiu essas palavras enquanto ensinava no templo, perto do lugar onde se colocavam as ofertas. No entanto, ninguém o prendeu, porque a sua hora ainda não havia chegado.

[[v43-8-21]]

^<<v43-8-21,21>>^ Mais uma vez, Jesus lhes disse: "Eu vou embora, e vocês procurarão por mim, e morrerão em seus pecados. Para onde vou, vocês não podem ir".

[[v43-8-22]]

^<<v43-8-22,22>>^ Isso levou os judeus a perguntarem: "Será que ele irá matar-se? Será por isso que ele diz: ‘Para onde vou, vocês não podem ir’? "

[[v43-8-23]]

^<<v43-8-23,23>>^ Mas ele continuou: "Vocês são daqui de baixo; eu sou lá de cima. Vocês são deste mundo; eu não sou deste mundo.

[[v43-8-24]]

^<<v43-8-24,24>>^ Eu lhes disse que vocês morrerão em seus pecados. Se vocês não crerem que Eu Sou, de fato morrerão em seus pecados".

[[v43-8-25]]

^<<v43-8-25,25>>^ "Quem é você? ", perguntaram eles. "Exatamente o que tenho dito o tempo todo", respondeu Jesus.

[[v43-8-26]]

^<<v43-8-26,26>>^ "Tenho muitas coisas para dizer e julgar a respeito de vocês. Pois aquele que me enviou merece confiança, e digo ao mundo aquilo que dele ouvi".

[[v43-8-27]]

^<<v43-8-27,27>>^ Eles não entenderam que lhes estava falando a respeito do Pai.

[[v43-8-28]]

^<<v43-8-28,28>>^ Então Jesus disse: "Quando vocês levantarem o Filho do homem, saberão que Eu Sou, e que nada faço de mim mesmo, mas falo exatamente o que o Pai me ensinou.

[[v43-8-29]]

^<<v43-8-29,29>>^ Aquele que me enviou está comigo; ele não me deixou sozinho, pois sempre faço o que lhe agrada".

[[v43-8-30]]

^<<v43-8-30,30>>^ Tendo dito essas coisas, muitos creram nele.

[[v43-8-31]]

^<<v43-8-31,31>>^ Disse Jesus aos judeus que haviam crido nele: "Se vocês permanecerem firmes na minha palavra, verdadeiramente serão meus discípulos.

[[v43-8-32]]

^<<v43-8-32,32>>^ E conhecerão a verdade, e a verdade os libertará".

[[v43-8-33]]

^<<v43-8-33,33>>^ Eles lhe responderam: "Somos descendentes de Abraão e nunca fomos escravos de ninguém. Como você pode dizer que seremos livres? "

[[v43-8-34]]

^<<v43-8-34,34>>^ Jesus respondeu: "Digo-lhes a verdade: Todo aquele que vive pecando é escravo do pecado.

[[v43-8-35]]

^<<v43-8-35,35>>^ O escravo não tem lugar permanente na família, mas o filho pertence a ela para sempre.

[[v43-8-36]]

^<<v43-8-36,36>>^ Portanto, se o Filho os libertar, vocês de fato serão livres.

[[v43-8-37]]

^<<v43-8-37,37>>^ Eu sei que vocês são descendentes de Abraão. Contudo, estão procurando matar-me, porque em vocês não há lugar para a minha palavra.

[[v43-8-38]]

^<<v43-8-38,38>>^ Eu lhes estou dizendo o que vi na presença do Pai, e vocês fazem o que ouviram do pai de vocês".

[[v43-8-39]]

^<<v43-8-39,39>>^ "Abraão é o nosso pai", responderam eles. Disse Jesus: "Se vocês fossem filhos de Abraão, fariam as obras que Abraão fez.

[[v43-8-40]]

^<<v43-8-40,40>>^ Mas vocês estão procurando matar-me, sendo que eu lhes falei a verdade que ouvi de Deus; Abraão não agiu assim.

[[v43-8-41]]

^<<v43-8-41,41>>^ Vocês estão fazendo as obras do pai de vocês". Protestaram eles: "Nós não somos filhos ilegítimos. O único Pai que temos é Deus".

[[v43-8-42]]

^<<v43-8-42,42>>^ Disse-lhes Jesus: "Se Deus fosse o Pai de vocês, vocês me amariam, pois eu vim de Deus e agora estou aqui. Eu não vim por mim mesmo, mas ele me enviou.

[[v43-8-43]]

^<<v43-8-43,43>>^ Por que a minha linguagem não é clara para vocês? Porque são incapazes de ouvir o que eu digo.

[[v43-8-44]]

^<<v43-8-44,44>>^ "Vocês pertencem ao pai de vocês, o diabo, e querem realizar o desejo dele. Ele foi homicida desde o princípio e não se apegou à verdade, pois não há verdade nele. Quando mente, fala a sua própria língua, pois é mentiroso e pai da mentira.

[[v43-8-45]]

^<<v43-8-45,45>>^ No entanto, vocês não crêem em mim, porque lhes digo a verdade!

[[v43-8-46]]

^<<v43-8-46,46>>^ Qual de vocês pode me acusar de algum pecado? Se estou falando a verdade, porque vocês não crêem em mim?

[[v43-8-47]]

^<<v43-8-47,47>>^ Aquele que pertence a Deus ouve o que Deus diz. Vocês não ouvem porque não pertencem a Deus".

[[v43-8-48]]

^<<v43-8-48,48>>^ Os judeus lhe responderam: "Não estamos certos em dizer que você é samaritano e está endemoninhado? "

[[v43-8-49]]

^<<v43-8-49,49>>^ Disse Jesus: "Não estou endemoninhado! Pelo contrário, honro o meu Pai, e vocês me desonram.

[[v43-8-50]]

^<<v43-8-50,50>>^ Não estou buscando glória para mim mesmo; mas, há quem a busque e julgue.

[[v43-8-51]]

^<<v43-8-51,51>>^ Asseguro-lhes que, se alguém guardar a minha palavra, jamais verá a morte".

[[v43-8-52]]

^<<v43-8-52,52>>^ Diante disso, os judeus exclamaram: "Agora sabemos que você está endemoninhado! Abraão morreu, bem como os profetas, mas você diz que se alguém guardar a sua palavra, nunca experimentará a morte.

[[v43-8-53]]

^<<v43-8-53,53>>^ Você é maior do que o nosso pai Abraão? Ele morreu, bem como os profetas. Quem você pensa que é? "

[[v43-8-54]]

^<<v43-8-54,54>>^ Respondeu Jesus: "Se glorifico a mim mesmo, a minha glória nada significa. Meu Pai, que vocês dizem ser o Deus de vocês, é quem me glorifica.

[[v43-8-55]]

^<<v43-8-55,55>>^ Vocês não o conhecem, mas eu o conheço. Se eu dissesse que não o conheço, seria mentiroso como vocês, mas eu de fato o conheço e guardo a sua palavra.

[[v43-8-56]]

^<<v43-8-56,56>>^ Abraão, pai de vocês, regozijou-se porque veria o meu dia; ele o viu e alegrou-se".

[[v43-8-57]]

^<<v43-8-57,57>>^ Disseram-lhe os judeus: "Você ainda não tem cinqüenta anos, e viu Abraão? "

[[v43-8-58]]

^<<v43-8-58,58>>^ Respondeu Jesus: "Eu lhes afirmo que antes de Abraão nascer, Eu Sou! "

[[v43-8-59]]

^<<v43-8-59,59>>^ Então eles apanharam pedras para apedrejá-lo, mas Jesus escondeu-se e saiu do templo.

'''

xref:043-joao/043-joao-007.adoc#v43-7-0[&#60; Capítulo Anterior] | <<v43-8-0,Topo>> | xref:043-joao/043-joao-009.adoc#v43-9-0[Próximo Capítulo &#62;]