include::./index.adoc[]

[[v43-15-0]]
=== João, 15
// nvi ?, NVI - Nova Versão Internacional

[[v43-15-1]]

^<<v43-15-1,1>>^ "Eu sou a videira verdadeira, e meu Pai é o agricultor.

[[v43-15-2]]

^<<v43-15-2,2>>^ Todo ramo que, estando em mim, não dá fruto, ele corta; e todo que dá fruto ele poda, para que dê mais fruto ainda.

[[v43-15-3]]

^<<v43-15-3,3>>^ Vocês já estão limpos, pela palavra que lhes tenho falado.

[[v43-15-4]]

^<<v43-15-4,4>>^ Permaneçam em mim, e eu permanecerei em vocês. Nenhum ramo pode dar fruto por si mesmo, se não permanecer na videira. Vocês também não podem dar fruto, se não permanecerem em mim.

[[v43-15-5]]

^<<v43-15-5,5>>^ "Eu sou a videira; vocês são os ramos. Se alguém permanecer em mim e eu nele, esse dá muito fruto; pois sem mim vocês não podem fazer coisa alguma.

[[v43-15-6]]

^<<v43-15-6,6>>^ Se alguém não permanecer em mim, será como o ramo que é jogado fora e seca. Tais ramos são apanhados, lançados ao fogo e queimados.

[[v43-15-7]]

^<<v43-15-7,7>>^ Se vocês permanecerem em mim, e as minhas palavras permanecerem em vocês, pedirão o que quiserem, e lhes será concedido.

[[v43-15-8]]

^<<v43-15-8,8>>^ Meu Pai é glorificado pelo fato de vocês darem muito fruto; e assim serão meus discípulos.

[[v43-15-9]]

^<<v43-15-9,9>>^ "Como o Pai me amou, assim eu os amei; permaneçam no meu amor.

[[v43-15-10]]

^<<v43-15-10,10>>^ Se vocês obedecerem aos meus mandamentos, permanecerão no meu amor, assim como tenho obedecido aos mandamentos de meu Pai e em seu amor permaneço.

[[v43-15-11]]

^<<v43-15-11,11>>^ Tenho lhes dito estas palavras para que a minha alegria esteja em vocês e a alegria de vocês seja completa.

[[v43-15-12]]

^<<v43-15-12,12>>^ O meu mandamento é este: amem-se uns aos outros como eu os amei.

[[v43-15-13]]

^<<v43-15-13,13>>^ Ninguém tem maior amor do que aquele que dá a sua vida pelos seus amigos.

[[v43-15-14]]

^<<v43-15-14,14>>^ Vocês serão meus amigos, se fizerem o que eu lhes ordeno.

[[v43-15-15]]

^<<v43-15-15,15>>^ Já não os chamo servos, porque o servo não sabe o que o seu senhor faz. Em vez disso, eu os tenho chamado amigos, porque tudo o que ouvi de meu Pai eu lhes tornei conhecido.

[[v43-15-16]]

^<<v43-15-16,16>>^ Vocês não me escolheram, mas eu os escolhi para irem e darem fruto, fruto que permaneça, a fim de que o Pai lhes conceda o que pedirem em meu nome.

[[v43-15-17]]

^<<v43-15-17,17>>^ Este é o meu mandamento: amem-se uns aos outros".

[[v43-15-18]]

^<<v43-15-18,18>>^ "Se o mundo os odeia, tenham em mente que antes odiou a mim.

[[v43-15-19]]

^<<v43-15-19,19>>^ Se vocês pertencessem ao mundo, ele os amaria como se fossem dele. Todavia, vocês não são do mundo, mas eu os escolhi, tirando-os do mundo; por isso o mundo os odeia.

[[v43-15-20]]

^<<v43-15-20,20>>^ Lembrem-se das palavras que eu lhes disse: nenhum escravo é maior do que o seu senhor. Se me perseguiram, também perseguirão vocês. Se obedeceram à minha palavra, também obedecerão à de vocês.

[[v43-15-21]]

^<<v43-15-21,21>>^ Tratarão assim vocês por causa do meu nome, pois não conhecem aquele que me enviou.

[[v43-15-22]]

^<<v43-15-22,22>>^ Se eu não tivesse vindo e lhes falado, não seriam culpados de pecado. Agora, contudo, eles não têm desculpa para o seu pecado.

[[v43-15-23]]

^<<v43-15-23,23>>^ Aquele que me odeia, também odeia o meu Pai.

[[v43-15-24]]

^<<v43-15-24,24>>^ Se eu não tivesse realizado no meio deles obras que ninguém mais fez, eles não seriam culpados de pecado. Mas agora eles as viram e odiaram a mim e a meu Pai.

[[v43-15-25]]

^<<v43-15-25,25>>^ Mas isto aconteceu para se cumprir o que está escrito na Lei deles: ‘Odiaram-me sem razão’.

[[v43-15-26]]

^<<v43-15-26,26>>^ "Quando vier o Conselheiro, que eu enviarei a vocês da parte do Pai, o Espírito da verdade que provém do Pai, ele testemunhará a meu respeito.

[[v43-15-27]]

^<<v43-15-27,27>>^ E vocês também testemunharão, pois estão comigo desde o princípio".

'''

xref:043-joao/043-joao-014.adoc#v43-14-0[&#60; Capítulo Anterior] | <<v43-15-0,Topo>> | xref:043-joao/043-joao-016.adoc#v43-16-0[Próximo Capítulo &#62;]