include::./index.adoc[]

[[v43-2-0]]
=== João, 2
// nvi ?, NVI - Nova Versão Internacional

[[v43-2-1]]

^<<v43-2-1,1>>^ No terceiro dia houve um casamento em Caná da Galiléia. A mãe de Jesus estava ali;

[[v43-2-2]]

^<<v43-2-2,2>>^ Jesus e seus discípulos também haviam sido convidados para o casamento.

[[v43-2-3]]

^<<v43-2-3,3>>^ Tendo acabado o vinho, a mãe de Jesus lhe disse: "Eles não têm mais vinho".

[[v43-2-4]]

^<<v43-2-4,4>>^ Respondeu Jesus: "Que temos nós em comum, mulher? A minha hora ainda não chegou".

[[v43-2-5]]

^<<v43-2-5,5>>^ Sua mãe disse aos serviçais: "Façam tudo o que ele lhes mandar".

[[v43-2-6]]

^<<v43-2-6,6>>^ Ali perto havia seis potes de pedra, do tipo usado pelos judeus para as purificações cerimoniais; em cada pote cabia entre oitenta a cento e vinte litros.

[[v43-2-7]]

^<<v43-2-7,7>>^ Disse Jesus aos serviçais: "Encham os potes com água". E os encheram até à borda.

[[v43-2-8]]

^<<v43-2-8,8>>^ Então lhes disse: "Agora, levem um pouco do vinho ao encarregado da festa". Eles assim o fizeram,

[[v43-2-9]]

^<<v43-2-9,9>>^ e o encarregado da festa provou a água que fora transformada em vinho, sem saber de onde este viera, embora o soubessem os serviçais que haviam tirado a água. Então chamou o noivo

[[v43-2-10]]

^<<v43-2-10,10>>^ e disse: "Todos servem primeiro o melhor vinho e, depois que os convidados já beberam bastante, o vinho inferior é servido; mas você guardou o melhor até agora".

[[v43-2-11]]

^<<v43-2-11,11>>^ Este sinal miraculoso, em Caná da Galiléia, foi o primeiro que Jesus realizou. Revelou assim a sua glória, e os seus discípulos creram nele.

[[v43-2-12]]

^<<v43-2-12,12>>^ Depois disso ele desceu a Cafarnaum com sua mãe, seus irmãos e seus discípulos. Ali ficaram durante alguns dias.

[[v43-2-13]]

^<<v43-2-13,13>>^ Quando já estava chegando a Páscoa judaica, Jesus subiu a Jerusalém.

[[v43-2-14]]

^<<v43-2-14,14>>^ No pátio do templo viu alguns vendendo bois, ovelhas e pombas, e outros assentados diante de mesas, trocando dinheiro.

[[v43-2-15]]

^<<v43-2-15,15>>^ Então ele fez um chicote de cordas e expulsou todos do templo, bem como as ovelhas e os bois; espalhou as moedas dos cambistas e virou as suas mesas.

[[v43-2-16]]

^<<v43-2-16,16>>^ Aos que vendiam pombas disse: "Tirem estas coisas daqui! Parem de fazer da casa de meu Pai um mercado! "

[[v43-2-17]]

^<<v43-2-17,17>>^ Seus discípulos lembraram-se que está escrito: "O zelo pela tua casa me consumirá".

[[v43-2-18]]

^<<v43-2-18,18>>^ Então os judeus lhe perguntaram: "Que sinal miraculoso o senhor pode mostrar-nos como prova da sua autoridade para fazer tudo isso? "

[[v43-2-19]]

^<<v43-2-19,19>>^ Jesus lhes respondeu: "Destruam este templo, e eu o levantarei em três dias".

[[v43-2-20]]

^<<v43-2-20,20>>^ Os judeus responderam: "Este templo levou quarenta e seis anos para ser edificado, e o senhor vai levantá-lo em três dias? "

[[v43-2-21]]

^<<v43-2-21,21>>^ Mas o templo do qual ele falava era o seu corpo.

[[v43-2-22]]

^<<v43-2-22,22>>^ Depois que ressuscitou dos mortos, os seus discípulos lembraram-se do que ele tinha dito. Então creram na Escritura e na palavra que Jesus dissera.

[[v43-2-23]]

^<<v43-2-23,23>>^ Enquanto estava em Jerusalém, na festa da Páscoa, muitos viram os sinais miraculosos que ele estava realizando e creram em seu nome.

[[v43-2-24]]

^<<v43-2-24,24>>^ Mas Jesus não se confiava a eles, pois conhecia a todos.

[[v43-2-25]]

^<<v43-2-25,25>>^ Não precisava que ninguém lhe desse testemunho a respeito do homem, pois ele bem sabia o que havia no homem.

'''

xref:043-joao/043-joao-001.adoc#v43-1-0[&#60; Capítulo Anterior] | <<v43-2-0,Topo>> | xref:043-joao/043-joao-003.adoc#v43-3-0[Próximo Capítulo &#62;]