include::./index.adoc[]

[[v43-6-0]]
=== João, 6
// nvi ?, NVI - Nova Versão Internacional

[[v43-6-1]]

^<<v43-6-1,1>>^ Algum tempo depois Jesus partiu para a outra margem do mar da Galiléia ( ou seja, do mar de Tiberíades ),

[[v43-6-2]]

^<<v43-6-2,2>>^ e grande multidão continuava a segui-lo, porque vira os sinais miraculosos que ele tinha realizado nos doentes.

[[v43-6-3]]

^<<v43-6-3,3>>^ Então Jesus subiu ao monte e sentou-se com os seus discípulos.

[[v43-6-4]]

^<<v43-6-4,4>>^ Estava próxima a festa judaica da Páscoa.

[[v43-6-5]]

^<<v43-6-5,5>>^ Levantando os olhos e vendo uma grande multidão que se aproximava, Jesus disse a Filipe: "Onde compraremos pão para esse povo comer? "

[[v43-6-6]]

^<<v43-6-6,6>>^ Fez essa pergunta apenas para pô-lo à prova, pois já tinha em mente o que ia fazer.

[[v43-6-7]]

^<<v43-6-7,7>>^ Filipe lhe respondeu: "Duzentos denários não comprariam pão suficiente para que cada um recebesse um pedaço! "

[[v43-6-8]]

^<<v43-6-8,8>>^ Outro discípulo, André, irmão de Simão Pedro, tomou a palavra:

[[v43-6-9]]

^<<v43-6-9,9>>^ "Aqui está um rapaz com cinco pães de cevada e dois peixinhos, mas o que é isto para tanta gente? "

[[v43-6-10]]

^<<v43-6-10,10>>^ Disse Jesus: "Mandem o povo assentar-se". Havia muita grama naquele lugar, e todos se assentaram. Eram cerca de cinco mil homens.

[[v43-6-11]]

^<<v43-6-11,11>>^ Então Jesus tomou os pães, deu graças e os repartiu entre os que estavam assentados, tanto quanto queriam; e fez o mesmo com os peixes.

[[v43-6-12]]

^<<v43-6-12,12>>^ Depois que todos receberam o suficiente para comer, disse aos seus discípulos: "Ajuntem os pedaços que sobraram. Que nada seja desperdiçado".

[[v43-6-13]]

^<<v43-6-13,13>>^ Então eles os ajuntaram e encheram doze cestos com os pedaços dos cinco pães de cevada deixados por aqueles que tinham comido.

[[v43-6-14]]

^<<v43-6-14,14>>^ Depois de ver o sinal miraculoso que Jesus tinha realizado, o povo começou a dizer: "Sem dúvida este é o Profeta que devia vir ao mundo".

[[v43-6-15]]

^<<v43-6-15,15>>^ Sabendo Jesus que pretendiam proclamá-lo rei à força, retirou-se novamente sozinho para o monte.

[[v43-6-16]]

^<<v43-6-16,16>>^ Ao anoitecer seus discípulos desceram para o mar,

[[v43-6-17]]

^<<v43-6-17,17>>^ entraram num barco e começaram a travessia para Cafarnaum. Já estava escuro, e Jesus ainda não tinha ido até onde eles estavam.

[[v43-6-18]]

^<<v43-6-18,18>>^ Soprava um vento forte, e as águas estavam agitadas.

[[v43-6-19]]

^<<v43-6-19,19>>^ Depois de terem remado cerca de cinco ou seis quilômetros, viram Jesus aproximando-se do barco, andando sobre o mar, e ficaram aterrorizados.

[[v43-6-20]]

^<<v43-6-20,20>>^ Mas ele lhes disse: "Sou eu! Não tenham medo! "

[[v43-6-21]]

^<<v43-6-21,21>>^ Então se animaram a recebê-lo no barco, e logo chegaram à praia para a qual se dirigiam.

[[v43-6-22]]

^<<v43-6-22,22>>^ No dia seguinte, a multidão que tinha ficado no outro lado do mar percebeu que apenas um barco estivera ali, e que Jesus não havia entrado nele com os seus discípulos, mas que eles tinham partido sozinhos.

[[v43-6-23]]

^<<v43-6-23,23>>^ Então alguns barcos de Tiberíades aproximaram-se do lugar onde o povo tinha comido o pão após o Senhor ter dado graças.

[[v43-6-24]]

^<<v43-6-24,24>>^ Quando a multidão percebeu que nem Jesus nem os discípulos estavam ali, entrou nos barcos e foi para Cafarnaum em busca de Jesus.

[[v43-6-25]]

^<<v43-6-25,25>>^ Quando o encontraram do outro lado do mar, perguntaram-lhe: "Mestre, quando chegaste aqui? "

[[v43-6-26]]

^<<v43-6-26,26>>^ Jesus respondeu: "A verdade é que vocês estão me procurando, não porque viram os sinais miraculosos, mas porque comeram os pães e ficaram satisfeitos.

[[v43-6-27]]

^<<v43-6-27,27>>^ Não trabalhem pela comida que se estraga, mas pela comida que permanece para a vida eterna, a qual o Filho do homem lhes dará. Deus, o Pai, nele colocou o seu selo de aprovação".

[[v43-6-28]]

^<<v43-6-28,28>>^ Então lhe perguntaram: "O que precisamos fazer para realizar as obras que Deus requer? "

[[v43-6-29]]

^<<v43-6-29,29>>^ Jesus respondeu: "A obra de Deus é esta: crer naquele que ele enviou".

[[v43-6-30]]

^<<v43-6-30,30>>^ Então lhe perguntaram: "Que sinal miraculoso mostrarás para que o vejamos e creiamos em ti? Que farás?

[[v43-6-31]]

^<<v43-6-31,31>>^ Os nossos antepassados comeram o maná no deserto; como está escrito: ‘Ele lhes deu a comer pão do céu’".

[[v43-6-32]]

^<<v43-6-32,32>>^ Declarou-lhes Jesus: "Digo-lhes a verdade: Não foi Moisés quem lhes deu pão do céu, mas é meu Pai quem lhes dá o verdadeiro pão do céu.

[[v43-6-33]]

^<<v43-6-33,33>>^ Pois o pão de Deus é aquele que desceu do céu e dá vida ao mundo".

[[v43-6-34]]

^<<v43-6-34,34>>^ Disseram eles: "Senhor, dá-nos sempre desse pão! "

[[v43-6-35]]

^<<v43-6-35,35>>^ Então Jesus declarou: "Eu sou o pão da vida. Aquele que vem a mim nunca terá fome; aquele que crê em mim nunca terá sede.

[[v43-6-36]]

^<<v43-6-36,36>>^ Mas, como eu lhes disse, vocês me viram, mas ainda não crêem.

[[v43-6-37]]

^<<v43-6-37,37>>^ Todo o que o Pai me der virá a mim, e quem vier a mim eu jamais rejeitarei.

[[v43-6-38]]

^<<v43-6-38,38>>^ Pois desci do céu, não para fazer a minha vontade, mas para fazer a vontade daquele que me enviou.

[[v43-6-39]]

^<<v43-6-39,39>>^ E esta é a vontade daquele que me enviou: que eu não perca nenhum dos que ele me deu, mas os ressuscite no último dia.

[[v43-6-40]]

^<<v43-6-40,40>>^ Porque a vontade de meu Pai é que todo o que olhar para o Filho e nele crer tenha a vida eterna, e eu o ressuscitarei no último dia".

[[v43-6-41]]

^<<v43-6-41,41>>^ Com isso os judeus começaram a criticar Jesus, porque dissera: "Eu sou o pão que desceu do céu".

[[v43-6-42]]

^<<v43-6-42,42>>^ E diziam: "Este não é Jesus, o filho de José? Não conhecemos seu pai e sua mãe? Como ele pode dizer: ‘Desci do céu’? "

[[v43-6-43]]

^<<v43-6-43,43>>^ Respondeu Jesus: "Parem de fazer-me críticas.

[[v43-6-44]]

^<<v43-6-44,44>>^ Ninguém pode vir a mim, se o Pai, que me enviou, não o atrair; e eu o ressuscitarei no último dia.

[[v43-6-45]]

^<<v43-6-45,45>>^ Está escrito nos Profetas: ‘Todos serão ensinados por Deus’. Todos os que ouvem o Pai e dele aprendem vêm a mim.

[[v43-6-46]]

^<<v43-6-46,46>>^ Ninguém viu o Pai, a não ser aquele que vem de Deus; somente ele viu ao Pai.

[[v43-6-47]]

^<<v43-6-47,47>>^ Asseguro-lhes que aquele que crê tem a vida eterna.

[[v43-6-48]]

^<<v43-6-48,48>>^ Eu sou o pão da vida.

[[v43-6-49]]

^<<v43-6-49,49>>^ Os seus antepassados comeram o maná no deserto, mas morreram.

[[v43-6-50]]

^<<v43-6-50,50>>^ Todavia, aqui está o pão que desce do céu, para que não morra quem dele comer.

[[v43-6-51]]

^<<v43-6-51,51>>^ Eu sou o pão vivo que desceu do céu. Se alguém comer deste pão, viverá para sempre. Este pão é a minha carne, que eu darei pela vida do mundo".

[[v43-6-52]]

^<<v43-6-52,52>>^ Então os judeus começaram a discutir exaltadamente entre si: "Como pode este homem nos oferecer a sua carne para comermos? "

[[v43-6-53]]

^<<v43-6-53,53>>^ Jesus lhes disse: "Eu lhes digo a verdade: Se vocês não comerem a carne do Filho do homem e não beberem o seu sangue, não terão vida em si mesmos.

[[v43-6-54]]

^<<v43-6-54,54>>^ Todo o que come a minha carne e bebe o meu sangue tem a vida eterna, e eu o ressuscitarei no último dia.

[[v43-6-55]]

^<<v43-6-55,55>>^ Pois a minha carne é verdadeira comida e o meu sangue é verdadeira bebida.

[[v43-6-56]]

^<<v43-6-56,56>>^ Todo o que come a minha carne e bebe o meu sangue permanece em mim e eu nele.

[[v43-6-57]]

^<<v43-6-57,57>>^ Da mesma forma como o Pai que vive me enviou e eu vivo por causa do Pai, assim aquele que se alimenta de mim viverá por minha causa.

[[v43-6-58]]

^<<v43-6-58,58>>^ Este é o pão que desceu do céu. Os antepassados de vocês comeram o maná e morreram, mas aquele que se alimenta deste pão viverá para sempre".

[[v43-6-59]]

^<<v43-6-59,59>>^ Ele disse isso quando ensinava na sinagoga de Cafarnaum.

[[v43-6-60]]

^<<v43-6-60,60>>^ Ao ouvirem isso, muitos dos seus discípulos disseram: "Dura é essa palavra. Quem consegue ouvi-la? "

[[v43-6-61]]

^<<v43-6-61,61>>^ Sabendo em seu íntimo que os seus discípulos estavam se queixando do que ouviram, Jesus lhes disse: "Isso os escandaliza?

[[v43-6-62]]

^<<v43-6-62,62>>^ Que acontecerá se vocês virem o Filho do homem subir para onde estava antes!

[[v43-6-63]]

^<<v43-6-63,63>>^ O Espírito dá vida; a carne não produz nada que se aproveite. As palavras que eu lhes disse são espírito e vida.

[[v43-6-64]]

^<<v43-6-64,64>>^ Contudo, há alguns de vocês que não crêem". Pois Jesus sabia desde o princípio quais deles não criam e quem o iria trair.

[[v43-6-65]]

^<<v43-6-65,65>>^ E prosseguiu: "É por isso que eu lhes disse que ninguém pode vir a mim, a não ser que isto lhe seja dado pelo Pai".

[[v43-6-66]]

^<<v43-6-66,66>>^ Daquela hora em diante, muitos dos seus discípulos voltaram atrás e deixaram de segui-lo.

[[v43-6-67]]

^<<v43-6-67,67>>^ Jesus perguntou aos Doze: "Vocês também não querem ir? "

[[v43-6-68]]

^<<v43-6-68,68>>^ Simão Pedro lhe respondeu: "Senhor, para quem iremos? Tu tens as palavras de vida eterna.

[[v43-6-69]]

^<<v43-6-69,69>>^ Nós cremos e sabemos que és o Santo de Deus".

[[v43-6-70]]

^<<v43-6-70,70>>^ Então Jesus respondeu: "Não fui eu que os escolhi, os Doze? Todavia, um de vocês é um diabo! "

[[v43-6-71]]

^<<v43-6-71,71>>^ ( Ele se referia a Judas, filho de Simão Iscariotes, que, embora fosse um dos Doze, mais tarde haveria de traí-lo. )

'''

xref:043-joao/043-joao-005.adoc#v43-5-0[&#60; Capítulo Anterior] | <<v43-6-0,Topo>> | xref:043-joao/043-joao-007.adoc#v43-7-0[Próximo Capítulo &#62;]