include::./index.adoc[]

[[v43-7-0]]
=== João, 7
// nvi ?, NVI - Nova Versão Internacional

[[v43-7-1]]

^<<v43-7-1,1>>^ Depois disso Jesus percorreu a Galiléia, mantendo-se deliberadamente longe da Judéia, porque ali os judeus procuravam tirar-lhe a vida.

[[v43-7-2]]

^<<v43-7-2,2>>^ Mas, ao se aproximar a festa judaica dos tabernáculos,

[[v43-7-3]]

^<<v43-7-3,3>>^ os irmãos de Jesus lhe disseram: "Você deve sair daqui e ir para a Judéia, para que os seus discípulos possam ver as obras que você faz.

[[v43-7-4]]

^<<v43-7-4,4>>^ Ninguém que deseja ser reconhecido publicamente age em segredo. Visto que você está fazendo estas coisas, mostre-se ao mundo".

[[v43-7-5]]

^<<v43-7-5,5>>^ Pois nem os seus irmãos criam nele.

[[v43-7-6]]

^<<v43-7-6,6>>^ Então Jesus lhes disse: "Para mim ainda não chegou o tempo certo; para vocês qualquer tempo é certo.

[[v43-7-7]]

^<<v43-7-7,7>>^ O mundo não pode odiá-los, mas a mim odeia porque dou testemunho de que o que ele faz é mau.

[[v43-7-8]]

^<<v43-7-8,8>>^ Vão vocês à festa; eu ainda não subirei a esta festa, porque para mim ainda não chegou o tempo apropriado".

[[v43-7-9]]

^<<v43-7-9,9>>^ Tendo dito isso, permaneceu na Galiléia.

[[v43-7-10]]

^<<v43-7-10,10>>^ Contudo, depois que os seus irmãos subiram para a festa, ele também subiu, não abertamente, mas em segredo.

[[v43-7-11]]

^<<v43-7-11,11>>^ Na festa os judeus o estavam esperando e perguntavam: "Onde está aquele homem? "

[[v43-7-12]]

^<<v43-7-12,12>>^ Entre a multidão havia muitos boatos a respeito dele. Alguns diziam: "É um bom homem". Outros respondiam: "Não, ele está enganando o povo".

[[v43-7-13]]

^<<v43-7-13,13>>^ Mas ninguém falava dele em público, por medo dos judeus.

[[v43-7-14]]

^<<v43-7-14,14>>^ Quando a festa estava na metade, Jesus subiu ao templo e começou a ensinar.

[[v43-7-15]]

^<<v43-7-15,15>>^ Os judeus ficaram admirados e perguntaram: "Como foi que este homem adquiriu tanta instrução, sem ter estudado? "

[[v43-7-16]]

^<<v43-7-16,16>>^ Jesus respondeu: "O meu ensino não é de mim mesmo. Vem daquele que me enviou.

[[v43-7-17]]

^<<v43-7-17,17>>^ Se alguém decidir fazer a vontade de Deus, descobrirá se o meu ensino vem de Deus ou se falo por mim mesmo.

[[v43-7-18]]

^<<v43-7-18,18>>^ Aquele que fala por si mesmo busca a sua própria glória, mas aquele que busca a glória de quem o enviou, este é verdadeiro; não há nada de falso a seu respeito.

[[v43-7-19]]

^<<v43-7-19,19>>^ Moisés não lhes deu a lei? No entanto, nenhum de vocês lhe obedece. Por que vocês procuram matar-me? "

[[v43-7-20]]

^<<v43-7-20,20>>^ "Você está endemoninhado", respondeu a multidão. "Quem está procurando matá-lo? "

[[v43-7-21]]

^<<v43-7-21,21>>^ Jesus lhes disse: "Fiz um milagre, e vocês todos estão admirados.

[[v43-7-22]]

^<<v43-7-22,22>>^ No entanto, porque Moisés lhes deu a circuncisão ( embora, na verdade, ela não tenha vindo de Moisés, mas dos patriarcas ), vocês circuncidam no sábado.

[[v43-7-23]]

^<<v43-7-23,23>>^ Ora, se um menino pode ser circuncidado no sábado para que a lei de Moisés não seja quebrada, por que vocês ficam cheias de ira contra mim por ter curado completamente um homem no sábado?

[[v43-7-24]]

^<<v43-7-24,24>>^ Não julguem apenas pela aparência, mas façam julgamentos justos".

[[v43-7-25]]

^<<v43-7-25,25>>^ Então alguns habitantes de Jerusalém começaram a perguntar: "Não é este o homem que estão procurando matar?

[[v43-7-26]]

^<<v43-7-26,26>>^ Aqui está ele, falando publicamente, e não lhe dizem uma palavra. Será que as autoridades chegaram à conclusão de que ele é realmente o Cristo?

[[v43-7-27]]

^<<v43-7-27,27>>^ Mas nós sabemos de onde é este homem; quando o Cristo vier, ninguém saberá de onde ele é".

[[v43-7-28]]

^<<v43-7-28,28>>^ Enquanto ensinava no pátio do templo, Jesus exclamou: "Sim, vocês me conhecem e sabem de onde sou. Eu não estou aqui por mim mesmo, mas aquele que me enviou é verdadeiro. Vocês não o conhecem,

[[v43-7-29]]

^<<v43-7-29,29>>^ mas eu o conheço porque venho da parte dele, e ele me enviou".

[[v43-7-30]]

^<<v43-7-30,30>>^ Então tentaram prendê-lo, mas ninguém lhe pôs as mãos, porque a sua hora ainda não havia chegado.

[[v43-7-31]]

^<<v43-7-31,31>>^ Assim mesmo, muitos dentre a multidão creram nele e diziam: "Quando o Cristo vier, fará mais sinais miraculosos do que este homem fez? "

[[v43-7-32]]

^<<v43-7-32,32>>^ Os fariseus ouviram a multidão falando essas coisas a respeito dele. Então os chefes dos sacerdotes e os fariseus enviaram guardas do templo para o prenderem.

[[v43-7-33]]

^<<v43-7-33,33>>^ Disse-lhes Jesus: "Estou com vocês apenas por pouco tempo e logo irei para aquele que me enviou.

[[v43-7-34]]

^<<v43-7-34,34>>^ Vocês procurarão por mim, mas não me encontrarão; onde eu estou, vocês não podem vir".

[[v43-7-35]]

^<<v43-7-35,35>>^ Os judeus disseram uns aos outros: "Aonde pretende ir este homem, que não o possamos encontrar? Para onde vive o nosso povo, espalhado entre os gregos, a fim de ensiná-lo?

[[v43-7-36]]

^<<v43-7-36,36>>^ O que ele quis dizer quando falou: ‘Vocês procurarão por mim, mas não me encontrarão’ e ‘onde eu estou, vocês não podem vir’? "

[[v43-7-37]]

^<<v43-7-37,37>>^ No último e mais importante dia da festa, Jesus levantou-se e disse em alta voz: "Se alguém tem sede, venha a mim e beba.

[[v43-7-38]]

^<<v43-7-38,38>>^ Quem crer em mim, como diz a Escritura, do seu interior fluirão rios de água viva".

[[v43-7-39]]

^<<v43-7-39,39>>^ Ele estava se referindo ao Espírito, que mais tarde receberiam os que nele cressem. Até então o Espírito ainda não tinha sido dado, pois Jesus ainda não fora glorificado.

[[v43-7-40]]

^<<v43-7-40,40>>^ Ouvindo as suas palavras, alguns dentre o povo disseram: "Certamente este homem é o Profeta".

[[v43-7-41]]

^<<v43-7-41,41>>^ Outros disseram: "Ele é o Cristo". Ainda outros perguntaram: "Como pode o Cristo vir da Galiléia?

[[v43-7-42]]

^<<v43-7-42,42>>^ A Escritura não diz que o Cristo virá da descendência de Davi, da cidade de Belém, onde viveu Davi? "

[[v43-7-43]]

^<<v43-7-43,43>>^ Assim o povo ficou dividido por causa de Jesus.

[[v43-7-44]]

^<<v43-7-44,44>>^ Alguns queriam prendê-lo, mas ninguém lhe pôs as mãos.

[[v43-7-45]]

^<<v43-7-45,45>>^ Finalmente, os guardas do templo voltaram aos chefes dos sacerdotes e aos fariseus, os quais lhes perguntaram: "Por que vocês não o trouxeram? "

[[v43-7-46]]

^<<v43-7-46,46>>^ "Ninguém jamais falou da maneira como esse homem fala", declararam os guardas.

[[v43-7-47]]

^<<v43-7-47,47>>^ "Será que vocês também foram enganados? ", perguntaram os fariseus.

[[v43-7-48]]

^<<v43-7-48,48>>^ "Por acaso alguém das autoridades ou dos fariseus creu nele?

[[v43-7-49]]

^<<v43-7-49,49>>^ Não! Mas essa ralé que nada entende da lei é maldita".

[[v43-7-50]]

^<<v43-7-50,50>>^ Nicodemos, um deles, que antes tinha procurando Jesus, perguntou-lhes:

[[v43-7-51]]

^<<v43-7-51,51>>^ "A nossa lei condena alguém, sem primeiro ouvi-lo para saber o que ele está fazendo? "

[[v43-7-52]]

^<<v43-7-52,52>>^ Eles responderam: "Você também é da Galiléia? Verifique, e descobrirá que da Galiléia não surge profeta".

[[v43-7-53]]

^<<v43-7-53,53>>^ Então cada um foi para a sua casa.

'''

xref:043-joao/043-joao-006.adoc#v43-6-0[&#60; Capítulo Anterior] | <<v43-7-0,Topo>> | xref:043-joao/043-joao-008.adoc#v43-8-0[Próximo Capítulo &#62;]