include::./index.adoc[]

[[v43-9-0]]
=== João, 9
// nvi ?, NVI - Nova Versão Internacional

[[v43-9-1]]

^<<v43-9-1,1>>^ Ao passar, Jesus viu um cego de nascença.

[[v43-9-2]]

^<<v43-9-2,2>>^ Seus discípulos lhe perguntaram: "Mestre, quem pecou: este homem ou seus pais, para que ele nascesse cego? "

[[v43-9-3]]

^<<v43-9-3,3>>^ Disse Jesus: "Nem ele nem seus pais pecaram, mas isto aconteceu para que a obra de Deus se manifestasse na vida dele.

[[v43-9-4]]

^<<v43-9-4,4>>^ Enquanto é dia, precisamos realizar a obra daquele que me enviou. A noite se aproxima, quando ninguém pode trabalhar.

[[v43-9-5]]

^<<v43-9-5,5>>^ Enquanto estou no mundo, sou a luz do mundo".

[[v43-9-6]]

^<<v43-9-6,6>>^ Tendo dito isso, ele cuspiu no chão, misturou terra com saliva e aplicou-a aos olhos do homem.

[[v43-9-7]]

^<<v43-9-7,7>>^ Então lhe disse: "Vá lavar-se no tanque de Siloé" ( que significa Enviado ). O homem foi, lavou-se e voltou vendo.

[[v43-9-8]]

^<<v43-9-8,8>>^ Seus vizinhos e os que anteriormente o tinham visto mendigando perguntaram: "Não é este o mesmo homem que costumava ficar sentado, mendigando? "

[[v43-9-9]]

^<<v43-9-9,9>>^ Alguns afirmavam que era ele. Outros diziam: "Não, apenas se parece com ele". Mas ele próprio insistia: "Sou eu mesmo".

[[v43-9-10]]

^<<v43-9-10,10>>^ "Então, como foram abertos os seus olhos? ", interrogaram-no eles.

[[v43-9-11]]

^<<v43-9-11,11>>^ Ele respondeu: "O homem chamado Jesus misturou terra com saliva, colocou-a nos meus olhos e me disse que fosse lavar-me em Siloé. Fui, lavei-me, e agora vejo".

[[v43-9-12]]

^<<v43-9-12,12>>^ Eles lhe perguntaram: "Onde está esse homem? " "Não sei", disse ele.

[[v43-9-13]]

^<<v43-9-13,13>>^ Levaram aos fariseus o homem que fora cego.

[[v43-9-14]]

^<<v43-9-14,14>>^ Era sábado o dia em que Jesus havia misturado terra com saliva e aberto os olhos daquele homem.

[[v43-9-15]]

^<<v43-9-15,15>>^ Então os fariseus também lhe perguntaram como ele recebera a visão. O homem respondeu: "Ele colocou uma mistura de terra e saliva em meus olhos, eu me lavei e agora vejo".

[[v43-9-16]]

^<<v43-9-16,16>>^ Alguns dos fariseus disseram: "Esse homem não é de Deus, pois não guarda o sábado". Mas outros perguntavam: "Como pode um pecador fazer tais sinais miraculosos? " E houve divisão entre eles.

[[v43-9-17]]

^<<v43-9-17,17>>^ Tornaram, pois, a perguntar ao cego: "Que diz você a respeito dele? Foram os seus olhos que ele abriu". O homem respondeu: "Ele é um profeta".

[[v43-9-18]]

^<<v43-9-18,18>>^ Os judeus não acreditaram que ele fora cego e havia sido curado enquanto não mandaram buscar os seus pais.

[[v43-9-19]]

^<<v43-9-19,19>>^ Então perguntaram: "É este o seu filho, o qual vocês dizem que nasceu cego? Como ele pode ver agora? "

[[v43-9-20]]

^<<v43-9-20,20>>^ Responderam os pais: "Sabemos que ele é nosso filho e que nasceu cego.

[[v43-9-21]]

^<<v43-9-21,21>>^ Mas não sabemos como ele pode ver agora ou quem lhe abriu os olhos. Perguntem a ele. Idade ele tem; falará por si mesmo".

[[v43-9-22]]

^<<v43-9-22,22>>^ Seus pais disseram isso porque tinham medo dos judeus, pois estes já haviam decidido que, se alguém confessasse que Jesus era o Cristo, seria expulso da sinagoga.

[[v43-9-23]]

^<<v43-9-23,23>>^ Foi por isso que seus pais disseram: "Idade ele tem; perguntem a ele".

[[v43-9-24]]

^<<v43-9-24,24>>^ Pela segunda vez, chamaram o homem que fora cego e lhe disseram: "Para a glória de Deus, diga a verdade. Sabemos que esse homem é pecador".

[[v43-9-25]]

^<<v43-9-25,25>>^ Ele respondeu: "Não sei se ele é pecador ou não. Uma coisa sei: eu era cego e agora vejo! "

[[v43-9-26]]

^<<v43-9-26,26>>^ Então lhe perguntaram: "O que ele lhe fez? Como lhe abriu os olhos? "

[[v43-9-27]]

^<<v43-9-27,27>>^ Ele respondeu: "Eu já lhes disse, e vocês não me deram ouvidos. Por que querem ouvir outra vez? Acaso vocês também querem ser discípulos dele? "

[[v43-9-28]]

^<<v43-9-28,28>>^ Então o insultaram e disseram: "Discípulo dele é você! Nós somos discípulos de Moisés!

[[v43-9-29]]

^<<v43-9-29,29>>^ Sabemos que Deus falou a Moisés, mas, quanto a esse, nem sabemos de onde ele vem".

[[v43-9-30]]

^<<v43-9-30,30>>^ O homem respondeu: "Ora, isso é extraordinário! Vocês não sabem de onde ele vem, contudo ele me abriu os olhos.

[[v43-9-31]]

^<<v43-9-31,31>>^ Sabemos que Deus não ouve a pecadores, mas ouve ao homem que o teme e pratica a sua vontade.

[[v43-9-32]]

^<<v43-9-32,32>>^ "Ninguém jamais ouviu que os olhos de um cego de nascença tivessem sido abertos.

[[v43-9-33]]

^<<v43-9-33,33>>^ Se esse homem não fosse de Deus, não poderia fazer coisa alguma".

[[v43-9-34]]

^<<v43-9-34,34>>^ Diante disso, eles responderam: "Você nasceu cheio de pecado; como tem a ousadia de nos ensinar? " E o expulsaram.

[[v43-9-35]]

^<<v43-9-35,35>>^ Jesus ouviu que o haviam expulsado, e, ao encontrá-lo, disse: "Você crê no Filho do homem? "

[[v43-9-36]]

^<<v43-9-36,36>>^ Perguntou o homem: "Quem é ele, Senhor, para que eu nele creia? "

[[v43-9-37]]

^<<v43-9-37,37>>^ Disse Jesus: "Você já o tem visto. É aquele que está falando com você".

[[v43-9-38]]

^<<v43-9-38,38>>^ Então o homem disse: "Senhor, eu creio". E o adorou.

[[v43-9-39]]

^<<v43-9-39,39>>^ Disse Jesus: "Eu vim a este mundo para julgamento, a fim de que os cegos vejam e os que vêem se tornem cegos".

[[v43-9-40]]

^<<v43-9-40,40>>^ Alguns fariseus que estavam com ele ouviram-no dizer isso e perguntaram: "Acaso nós também somos cegos? "

[[v43-9-41]]

^<<v43-9-41,41>>^ Disse Jesus: "Se vocês fossem cegos, não seriam culpados de pecado; mas agora que dizem que podem ver, a culpa de vocês permanece".

'''

xref:043-joao/043-joao-008.adoc#v43-8-0[&#60; Capítulo Anterior] | <<v43-9-0,Topo>> | xref:043-joao/043-joao-010.adoc#v43-10-0[Próximo Capítulo &#62;]