include::./index.adoc[]

[[v43-5-0]]
=== João, 5
// nvi ?, NVI - Nova Versão Internacional

[[v43-5-1]]

^<<v43-5-1,1>>^ Algum tempo depois, Jesus subiu a Jerusalém para uma festa dos judeus.

[[v43-5-2]]

^<<v43-5-2,2>>^ Há em Jerusalém, perto da porta das Ovelhas, um tanque que, em aramaico, é chamado Betesda, tendo cinco entradas em volta.

[[v43-5-3]]

^<<v43-5-3,3>>^ Ali costumava ficar grande número de pessoas doentes e inválidas: cegos, mancos e paralíticos. Eles esperavam um movimento nas águas.

[[v43-5-4]]

^<<v43-5-4,4>>^ De vez em quando descia um anjo do Senhor e agitava as águas. O primeiro que entrasse no tanque, depois de agitada as águas, era curado de qualquer doença que tivesse.

[[v43-5-5]]

^<<v43-5-5,5>>^ Um dos que estavam ali era paralítico fazia trinta e oito anos.

[[v43-5-6]]

^<<v43-5-6,6>>^ Quando o viu deitado e soube que ele vivia naquele estado durante tanto tempo, Jesus lhe perguntou: "Você quer ser curado? "

[[v43-5-7]]

^<<v43-5-7,7>>^ Disse o paralítico: "Senhor, não tenho ninguém que me ajude a entrar no tanque quando a água é agitada. Enquanto estou tentando entrar, outro chega antes de mim".

[[v43-5-8]]

^<<v43-5-8,8>>^ Então Jesus lhe disse: "Levante-se! Pegue a sua maca e ande".

[[v43-5-9]]

^<<v43-5-9,9>>^ Imediatamente o homem ficou curado, pegou a maca e começou a andar. Isso aconteceu num sábado,

[[v43-5-10]]

^<<v43-5-10,10>>^ e, por essa razão, os judeus disseram ao homem que havia sido curado: "Hoje é sábado, não lhe é permitido carregar a maca".

[[v43-5-11]]

^<<v43-5-11,11>>^ Mas ele respondeu: "O homem que me curou me disse: ‘Pegue a sua maca e ande’ ".

[[v43-5-12]]

^<<v43-5-12,12>>^ Então lhe perguntaram: "Quem é esse homem que lhe mandar pegar a maca e andar? "

[[v43-5-13]]

^<<v43-5-13,13>>^ O homem que fora curado não tinha idéia de quem era ele, pois Jesus havia desaparecido no meio da multidão.

[[v43-5-14]]

^<<v43-5-14,14>>^ Mais tarde Jesus o encontrou no templo e lhe disse: "Olhe, você está curado. Não volte a pecar, para que algo pior não lhe aconteça".

[[v43-5-15]]

^<<v43-5-15,15>>^ O homem foi contar aos judeus que fora Jesus quem o tinha curado.

[[v43-5-16]]

^<<v43-5-16,16>>^ Então os judeus passaram a perseguir Jesus, porque ele estava fazendo essas coisas no sábado.

[[v43-5-17]]

^<<v43-5-17,17>>^ Disse-lhes Jesus: "Meu Pai continua trabalhando até hoje, e eu também estou trabalhando".

[[v43-5-18]]

^<<v43-5-18,18>>^ Por essa razão, os judeus mais ainda queriam matá-lo, pois não somente estava violando o sábado, mas também estava até mesmo dizendo que Deus era seu próprio Pai, igualando-se a Deus.

[[v43-5-19]]

^<<v43-5-19,19>>^ Jesus lhes deu esta resposta: "Eu lhes digo verdadeiramente que o Filho não pode fazer nada de si mesmo; só pode fazer o que vê o Pai fazer, porque o que o Pai faz o Filho também faz.

[[v43-5-20]]

^<<v43-5-20,20>>^ Pois o Pai ama ao Filho e lhe mostra tudo o que faz. Sim, para admiração de vocês, ele lhe mostrará obras ainda maiores do que estas.

[[v43-5-21]]

^<<v43-5-21,21>>^ Pois, da mesma forma que o Pai ressuscita os mortos e lhes dá vida, o Filho também dá vida a quem ele quer dá-la.

[[v43-5-22]]

^<<v43-5-22,22>>^ Além disso, o Pai a ninguém julga, mas confiou todo julgamento ao Filho,

[[v43-5-23]]

^<<v43-5-23,23>>^ para que todos honrem o Filho como honram o Pai. Aquele que não honra o Filho, também não honra o Pai que o enviou.

[[v43-5-24]]

^<<v43-5-24,24>>^ "Eu lhes asseguro: Quem ouve a minha palavra e crê naquele que me enviou, tem a vida eterna e não será condenado, mas já passou da morte para a vida.

[[v43-5-25]]

^<<v43-5-25,25>>^ Eu lhes afirmo que está chegando a hora, e já chegou, em que os mortos ouvirão a voz do Filho de Deus, e aqueles que a ouvirem, viverão.

[[v43-5-26]]

^<<v43-5-26,26>>^ Pois, da mesma forma como o Pai tem vida em si mesmo, ele concedeu ao Filho ter vida em si mesmo.

[[v43-5-27]]

^<<v43-5-27,27>>^ E deu-lhe autoridade para julgar, porque é o Filho do homem.

[[v43-5-28]]

^<<v43-5-28,28>>^ "Não fiquem admirados com isto, pois está chegando a hora em que todos os que estiverem nos túmulos ouvirão a sua voz

[[v43-5-29]]

^<<v43-5-29,29>>^ e sairão; os que fizeram o bem ressuscitarão para a vida, e os que fizeram o mal ressuscitarão para serem condenados.

[[v43-5-30]]

^<<v43-5-30,30>>^ Por mim mesmo, nada posso fazer; eu julgo apenas conforme ouço, e o meu julgamento é justo, pois não procuro agradar a mim mesmo, mas àquele que me enviou".

[[v43-5-31]]

^<<v43-5-31,31>>^ "Se testifico acerca de mim mesmo, o meu testemunho não é válido.

[[v43-5-32]]

^<<v43-5-32,32>>^ Há outro que testemunha em meu favor, e sei que o seu testemunho a meu respeito é válido.

[[v43-5-33]]

^<<v43-5-33,33>>^ "Vocês enviaram representantes a João, e ele testemunhou da verdade.

[[v43-5-34]]

^<<v43-5-34,34>>^ Não que eu busque testemunho humano, mas menciono isso para que vocês sejam salvos.

[[v43-5-35]]

^<<v43-5-35,35>>^ João era uma candeia que queimava e irradiava luz, e durante certo tempo vocês quiseram alegrar-se com a sua luz.

[[v43-5-36]]

^<<v43-5-36,36>>^ "Eu tenho um testemunho maior que o de João; a própria obra que o Pai me deu para concluir, e que estou realizando, testemunha que o Pai me enviou.

[[v43-5-37]]

^<<v43-5-37,37>>^ E o Pai que me enviou, ele mesmo testemunhou a meu respeito. Vocês nunca ouviram a sua voz, nem viram a sua forma,

[[v43-5-38]]

^<<v43-5-38,38>>^ nem a sua palavra habita em vocês, pois não crêem naquele que ele enviou.

[[v43-5-39]]

^<<v43-5-39,39>>^ Vocês estudam cuidadosamente as Escrituras, porque pensam que nelas vocês têm a vida eterna. E são as Escrituras que testemunham a meu respeito;

[[v43-5-40]]

^<<v43-5-40,40>>^ contudo, vocês não querem vir a mim para terem vida.

[[v43-5-41]]

^<<v43-5-41,41>>^ "Eu não aceito glória dos homens,

[[v43-5-42]]

^<<v43-5-42,42>>^ mas conheço vocês. Sei que vocês não têm o amor de Deus.

[[v43-5-43]]

^<<v43-5-43,43>>^ Eu vim em nome de meu Pai, e vocês não me aceitaram; mas, se outro vier em seu próprio nome, vocês o aceitarão.

[[v43-5-44]]

^<<v43-5-44,44>>^ Como vocês podem crer, se aceitam glória uns dos outros, mas não procuram a glória que vem do Deus único?

[[v43-5-45]]

^<<v43-5-45,45>>^ "Contudo, não pensem que eu os acusarei perante o Pai. Quem os acusa é Moisés, em quem estão as suas esperanças.

[[v43-5-46]]

^<<v43-5-46,46>>^ Se vocês cressem em Moisés, creriam em mim, pois ele escreveu a meu respeito.

[[v43-5-47]]

^<<v43-5-47,47>>^ Visto, porém, que não crêem no que ele escreveu, como crerão no que eu digo? "

'''

xref:043-joao/043-joao-004.adoc#v43-4-0[&#60; Capítulo Anterior] | <<v43-5-0,Topo>> | xref:043-joao/043-joao-006.adoc#v43-6-0[Próximo Capítulo &#62;]