include::./index.adoc[]

[[v43-10-0]]
=== João, 10
// nvi ?, NVI - Nova Versão Internacional

[[v43-10-1]]

^<<v43-10-1,1>>^ "Eu lhes asseguro que aquele que não entra no aprisco das ovelhas pela porta, mas sobe por outro lugar, é ladrão e assaltante.

[[v43-10-2]]

^<<v43-10-2,2>>^ Aquele que entra pela porta é o pastor das ovelhas.

[[v43-10-3]]

^<<v43-10-3,3>>^ O porteiro abre-lhe a porta, e as ovelhas ouvem a sua voz. Ele chama as suas ovelhas pelo nome e as leva para fora.

[[v43-10-4]]

^<<v43-10-4,4>>^ Depois de conduzir para fora todas as suas ovelhas, vai adiante delas, e estas o seguem, porque conhecem a sua voz.

[[v43-10-5]]

^<<v43-10-5,5>>^ Mas nunca seguirão um estranho; na verdade, fugirão dele, porque não reconhecem a voz de estranhos".

[[v43-10-6]]

^<<v43-10-6,6>>^ Jesus usou essa comparação, mas eles não compreenderam o que lhes estava falando.

[[v43-10-7]]

^<<v43-10-7,7>>^ Então Jesus afirmou de novo: "Digo-lhes a verdade: Eu sou a porta das ovelhas.

[[v43-10-8]]

^<<v43-10-8,8>>^ Todos os que vieram antes de mim eram ladrões e assaltantes, mas as ovelhas não os ouviram.

[[v43-10-9]]

^<<v43-10-9,9>>^ Eu sou a porta; quem entra por mim será salvo. Entrará e sairá, e encontrará pastagem.

[[v43-10-10]]

^<<v43-10-10,10>>^ O ladrão vem apenas para furtar, matar e destruir; eu vim para que tenham vida, e a tenham plenamente.

[[v43-10-11]]

^<<v43-10-11,11>>^ "Eu sou o bom pastor. O bom pastor dá a sua vida pelas ovelhas.

[[v43-10-12]]

^<<v43-10-12,12>>^ O assalariado não é o pastor a quem as ovelhas pertencem. Assim, quando vê que o lobo vem, abandona as ovelhas e foge. Então o lobo ataca o rebanho e o dispersa.

[[v43-10-13]]

^<<v43-10-13,13>>^ Ele foge porque é assalariado e não se importa com as ovelhas.

[[v43-10-14]]

^<<v43-10-14,14>>^ "Eu sou o bom pastor; conheço as minhas ovelhas; e elas me conhecem;

[[v43-10-15]]

^<<v43-10-15,15>>^ assim como o Pai me conhece e eu conheço o Pai; e dou a minha vida pelas ovelhas.

[[v43-10-16]]

^<<v43-10-16,16>>^ Tenho outras ovelhas que não são deste aprisco. É necessário que eu as conduza também. Elas ouvirão a minha voz, e haverá um só rebanho e um só pastor.

[[v43-10-17]]

^<<v43-10-17,17>>^ Por isso é que meu Pai me ama, porque eu dou a minha vida para retomá-la.

[[v43-10-18]]

^<<v43-10-18,18>>^ Ninguém a tira de mim, mas eu a dou por minha espontânea vontade. Tenho autoridade para dá-la e para retomá-la. Esta ordem recebi de meu Pai".

[[v43-10-19]]

^<<v43-10-19,19>>^ Diante dessas palavras, os judeus ficaram outra vez divididos.

[[v43-10-20]]

^<<v43-10-20,20>>^ Muitos deles diziam: "Ele está endemoninhado e enlouqueceu. Por que ouvi-lo? "

[[v43-10-21]]

^<<v43-10-21,21>>^ Mas outros diziam: "Essas palavras não são de um endemoninhado. Pode um demônio abrir os olhos dos cegos? "

[[v43-10-22]]

^<<v43-10-22,22>>^ Celebrava-se a festa da Dedicação, em Jerusalém. Era inverno,

[[v43-10-23]]

^<<v43-10-23,23>>^ e Jesus estava no templo, caminhando pelo Pórtico de Salomão.

[[v43-10-24]]

^<<v43-10-24,24>>^ Os judeus reuniram-se ao redor dele e perguntaram: "Até quando nos deixará em suspense? Se é você o Cristo, diga-nos abertamente".

[[v43-10-25]]

^<<v43-10-25,25>>^ Jesus respondeu: "Eu já lhes disse, mas vocês não crêem. As obras que eu realizo em nome de meu Pai falam por mim,

[[v43-10-26]]

^<<v43-10-26,26>>^ mas vocês não crêem, porque não são minhas ovelhas.

[[v43-10-27]]

^<<v43-10-27,27>>^ As minhas ovelhas ouvem a minha voz; eu as conheço, e elas me seguem.

[[v43-10-28]]

^<<v43-10-28,28>>^ Eu lhes dou a vida eterna, e elas jamais perecerão; ninguém as poderá arrancar da minha mão.

[[v43-10-29]]

^<<v43-10-29,29>>^ Meu Pai, que as deu para mim, é maior do que todos; ninguém as pode arrancar da mão de meu Pai.

[[v43-10-30]]

^<<v43-10-30,30>>^ Eu e o Pai somos um".

[[v43-10-31]]

^<<v43-10-31,31>>^ Novamente os judeus pegaram pedras para apedrejá-lo,

[[v43-10-32]]

^<<v43-10-32,32>>^ mas Jesus lhes disse: "Eu lhes mostrei muitas boas obras da parte do Pai. Por qual delas vocês querem me apedrejar? "

[[v43-10-33]]

^<<v43-10-33,33>>^ Responderam os judeus: "Não vamos apedrejá-lo por nenhuma boa obra, mas pela blasfêmia, porque você é um simples homem e se apresenta como Deus".

[[v43-10-34]]

^<<v43-10-34,34>>^ Jesus lhes respondeu: "Não está escrito na Lei de vocês: ‘Eu disse: Vocês são deuses’?

[[v43-10-35]]

^<<v43-10-35,35>>^ Se ele chamou ‘deuses’ àqueles a quem veio a palavra de Deus ( e a Escritura não pode ser anulada )

[[v43-10-36]]

^<<v43-10-36,36>>^ que dizer a respeito daquele a quem o Pai santificou e enviou ao mundo? Então, por que vocês me acusam de blasfêmia porque eu disse: ‘Sou Filho de Deus’?

[[v43-10-37]]

^<<v43-10-37,37>>^ Se eu não realizo as obras do meu Pai, não creiam em mim.

[[v43-10-38]]

^<<v43-10-38,38>>^ Mas se as realizo, mesmo que não creiam em mim, creiam nas obras, para que possam saber e entender que o Pai está em mim, e eu no Pai".

[[v43-10-39]]

^<<v43-10-39,39>>^ Outra vez tentaram prendê-lo, mas ele se livrou das mãos deles.

[[v43-10-40]]

^<<v43-10-40,40>>^ Então Jesus atravessou novamente o Jordão e foi para o lugar onde João batizava nos primeiros dias do seu ministério. Ali ficou,

[[v43-10-41]]

^<<v43-10-41,41>>^ e muita gente foi até onde ele estava, dizendo: "Embora João nunca tenha realizado um sinal miraculoso, tudo o que ele disse a respeito deste homem era verdade".

[[v43-10-42]]

^<<v43-10-42,42>>^ E ali muitos creram em Jesus.

'''

xref:043-joao/043-joao-009.adoc#v43-9-0[&#60; Capítulo Anterior] | <<v43-10-0,Topo>> | xref:043-joao/043-joao-011.adoc#v43-11-0[Próximo Capítulo &#62;]