include::./index.adoc[]

[[v43-14-0]]
=== João, 14
// nvi ?, NVI - Nova Versão Internacional

[[v43-14-1]]

^<<v43-14-1,1>>^ "Não se perturbe o coração de vocês. Creiam em Deus; creiam também em mim.

[[v43-14-2]]

^<<v43-14-2,2>>^ Na casa de meu Pai há muitos aposentos; se não fosse assim, eu lhes teria dito. Vou preparar-lhes lugar.

[[v43-14-3]]

^<<v43-14-3,3>>^ E se eu for e lhes preparar lugar, voltarei e os levarei para mim, para que vocês estejam onde eu estiver.

[[v43-14-4]]

^<<v43-14-4,4>>^ Vocês conhecem o caminho para onde vou".

[[v43-14-5]]

^<<v43-14-5,5>>^ Disse-lhe Tomé: "Senhor, não sabemos para onde vais; como então podemos saber o caminho? "

[[v43-14-6]]

^<<v43-14-6,6>>^ Respondeu Jesus: "Eu sou o caminho, a verdade e a vida. Ninguém vem ao Pai, a não ser por mim.

[[v43-14-7]]

^<<v43-14-7,7>>^ Se vocês realmente me conhecessem, conheceriam também o meu Pai. Já agora vocês o conhecem e o têm visto".

[[v43-14-8]]

^<<v43-14-8,8>>^ Disse Filipe: "Senhor, mostra-nos o Pai, e isso nos basta".

[[v43-14-9]]

^<<v43-14-9,9>>^ Jesus respondeu: "Você não me conhece, Filipe, mesmo depois de eu ter estado com vocês durante tanto tempo? Quem me vê, vê o Pai. Como você pode dizer: ‘Mostra-nos o Pai’?

[[v43-14-10]]

^<<v43-14-10,10>>^ Você não crê que eu estou no Pai e que o Pai está em mim? As palavras que eu lhes digo não são apenas minhas. Pelo contrário, o Pai, que vive em mim, está realizando a sua obra.

[[v43-14-11]]

^<<v43-14-11,11>>^ Creiam em mim quando digo que estou no Pai e que o Pai está em mim; ou pelo menos creiam por causa das mesmas obras.

[[v43-14-12]]

^<<v43-14-12,12>>^ Digo-lhes a verdade: Aquele que crê em mim fará também as obras que tenho realizado. Fará coisas ainda maiores do que estas, porque eu estou indo para o Pai.

[[v43-14-13]]

^<<v43-14-13,13>>^ E eu farei o que vocês pedirem em meu nome, para que o Pai seja glorificado no Filho.

[[v43-14-14]]

^<<v43-14-14,14>>^ O que vocês pedirem em meu nome, eu farei".

[[v43-14-15]]

^<<v43-14-15,15>>^ "Se vocês me amam, obedecerão aos meus mandamentos.

[[v43-14-16]]

^<<v43-14-16,16>>^ E eu pedirei ao Pai, e ele lhes dará outro Conselheiro para estar com vocês para sempre,

[[v43-14-17]]

^<<v43-14-17,17>>^ o Espírito da verdade. O mundo não pode recebê-lo, porque não o vê nem o conhece. Mas vocês o conhecem, pois ele vive com vocês e estará em vocês.

[[v43-14-18]]

^<<v43-14-18,18>>^ Não os deixarei órfãos; voltarei para vocês.

[[v43-14-19]]

^<<v43-14-19,19>>^ Dentro de pouco tempo o mundo já não me verá mais; vocês, porém, me verão. Porque eu vivo, vocês também viverão.

[[v43-14-20]]

^<<v43-14-20,20>>^ Naquele dia compreenderão que estou em meu Pai, vocês em mim, e eu em vocês.

[[v43-14-21]]

^<<v43-14-21,21>>^ Quem tem os meus mandamentos e lhes obedece, esse é o que me ama. Aquele que me ama será amado por meu Pai, e eu também o amarei e me revelarei a ele".

[[v43-14-22]]

^<<v43-14-22,22>>^ Disse então Judas ( não o Iscariotes ): "Senhor, mas por que te revelarás a nós e não ao mundo? "

[[v43-14-23]]

^<<v43-14-23,23>>^ Respondeu Jesus: "Se alguém me ama, guardará a minha palavra. Meu Pai o amará, nós viremos a ele e faremos nele morada.

[[v43-14-24]]

^<<v43-14-24,24>>^ Aquele que não me ama não guarda as minhas palavras. Estas palavras que vocês estão ouvindo não são minhas; são de meu Pai que me enviou.

[[v43-14-25]]

^<<v43-14-25,25>>^ "Tudo isso lhes tenho dito enquanto ainda estou com vocês.

[[v43-14-26]]

^<<v43-14-26,26>>^ Mas o Conselheiro, o Espírito Santo, que o Pai enviará em meu nome, lhes ensinará todas as coisas e lhes fará lembrar tudo o que eu lhes disse.

[[v43-14-27]]

^<<v43-14-27,27>>^ Deixo-lhes a paz; a minha paz lhes dou. Não a dou como o mundo a dá. Não se perturbem os seus corações, nem tenham medo.

[[v43-14-28]]

^<<v43-14-28,28>>^ "Vocês me ouviram dizer: Vou, mas volto para vocês. Se vocês me amassem, ficariam contentes porque vou para o Pai, pois o Pai é maior do que eu.

[[v43-14-29]]

^<<v43-14-29,29>>^ Isso eu lhes disse agora, antes que aconteça, para que, quando acontecer, vocês creiam.

[[v43-14-30]]

^<<v43-14-30,30>>^ Já não lhes falarei muito, pois o príncipe deste mundo está vindo. Ele não tem nenhum direito sobre mim.

[[v43-14-31]]

^<<v43-14-31,31>>^ Todavia para que o mundo saiba que amo o Pai e que faço o que meu Pai me ordenou. Levantem-se, vamo-nos daqui! "

'''

xref:043-joao/043-joao-013.adoc#v43-13-0[&#60; Capítulo Anterior] | <<v43-14-0,Topo>> | xref:043-joao/043-joao-015.adoc#v43-15-0[Próximo Capítulo &#62;]