include::./index.adoc[]

[[v43-4-0]]
=== João, 4
// nvi ?, NVI - Nova Versão Internacional

[[v43-4-1]]

^<<v43-4-1,1>>^ Os fariseus ouviram falar que Jesus estava fazendo e batizando mais discípulos do que João,

[[v43-4-2]]

^<<v43-4-2,2>>^ embora não fosse Jesus quem batizasse, mas os seus discípulos.

[[v43-4-3]]

^<<v43-4-3,3>>^ Quando o Senhor ficou sabendo disso, saiu da Judéia e voltou uma vez mais à Galiléia.

[[v43-4-4]]

^<<v43-4-4,4>>^ Era-lhe necessário passar por Samaria.

[[v43-4-5]]

^<<v43-4-5,5>>^ Assim, chegou a uma cidade de Samaria, chamada Sicar, perto das terras que Jacó dera a seu filho José.

[[v43-4-6]]

^<<v43-4-6,6>>^ Havia ali o poço de Jacó. Jesus, cansado da viagem, sentou-se à beira do poço. Isto se deu por volta do meio-dia.

[[v43-4-7]]

^<<v43-4-7,7>>^ Nisso veio uma mulher samaritana tirar água. Disse-lhe Jesus: "Dê-me um pouco de água".

[[v43-4-8]]

^<<v43-4-8,8>>^ ( Os seus discípulos tinham ido à cidade comprar comida. )

[[v43-4-9]]

^<<v43-4-9,9>>^ A mulher samaritana lhe perguntou: "Como o senhor, sendo judeu, pede a mim, uma samaritana, água para beber? " ( Pois os judeus não se dão bem com os samaritanos. )

[[v43-4-10]]

^<<v43-4-10,10>>^ Jesus lhe respondeu: "Se você conhecesse o dom de Deus e quem lhe está pedindo água, você lhe teria pedido e ele lhe teria dado água viva".

[[v43-4-11]]

^<<v43-4-11,11>>^ Disse a mulher: "O senhor não tem com que tirar a água, e o poço é fundo. Onde pode conseguir essa água viva?

[[v43-4-12]]

^<<v43-4-12,12>>^ Acaso o senhor é maior do que o nosso pai Jacó, que nos deu o poço, do qual ele mesmo bebeu, bem como seus filhos e seu gado? "

[[v43-4-13]]

^<<v43-4-13,13>>^ Jesus respondeu: "Quem beber desta água terá sede outra vez,

[[v43-4-14]]

^<<v43-4-14,14>>^ mas quem beber da água que eu lhe der nunca mais terá sede. Pelo contrário, a água que eu lhe der se tornará nele uma fonte de água a jorrar para a vida eterna".

[[v43-4-15]]

^<<v43-4-15,15>>^ A mulher lhe disse: "Senhor, dê-me dessa água, para que eu não tenha mais sede, nem precise voltar aqui para tirar água".

[[v43-4-16]]

^<<v43-4-16,16>>^ Ele lhe disse: "Vá, chame o seu marido e volte".

[[v43-4-17]]

^<<v43-4-17,17>>^ "Não tenho marido", respondeu ela. Disse-lhe Jesus: "Você falou corretamente, dizendo que não tem marido.

[[v43-4-18]]

^<<v43-4-18,18>>^ O fato é que você já teve cinco; e o homem com quem agora vive não é seu marido. O que você acabou de dizer é verdade".

[[v43-4-19]]

^<<v43-4-19,19>>^ Disse a mulher: "Senhor, vejo que é profeta.

[[v43-4-20]]

^<<v43-4-20,20>>^ Nossos antepassados adoraram neste monte, mas vocês, judeus, dizem que Jerusalém é o lugar onde se deve adorar".

[[v43-4-21]]

^<<v43-4-21,21>>^ Jesus declarou: "Creia em mim, mulher: está próxima a hora em que vocês não adorarão o Pai nem neste monte, nem em Jerusalém.

[[v43-4-22]]

^<<v43-4-22,22>>^ Vocês, samaritanos, adoram o que não conhecem; nós adoramos o que conhecemos, pois a salvação vem dos judeus.

[[v43-4-23]]

^<<v43-4-23,23>>^ No entanto, está chegando a hora, e de fato já chegou, em que os verdadeiros adoradores adorarão o Pai em espírito e em verdade. São estes os adoradores que o Pai procura.

[[v43-4-24]]

^<<v43-4-24,24>>^ Deus é espírito, e é necessário que os seus adoradores o adorem em espírito e em verdade".

[[v43-4-25]]

^<<v43-4-25,25>>^ Disse a mulher: "Eu sei que o Messias ( chamado Cristo ) está para vir. Quando ele vier, explicará tudo para nós".

[[v43-4-26]]

^<<v43-4-26,26>>^ Então Jesus declarou: "Eu sou o Messias! Eu, que estou falando com você".

[[v43-4-27]]

^<<v43-4-27,27>>^ Naquele momento os seus discípulos voltaram e ficaram surpresos ao encontrá-lo conversando com uma mulher. Mas ninguém perguntou: "Que queres saber? " ou: "Por que estás conversando com ela? "

[[v43-4-28]]

^<<v43-4-28,28>>^ Então, deixando o seu cântaro, a mulher voltou à cidade e disse ao povo:

[[v43-4-29]]

^<<v43-4-29,29>>^ "Venham ver um homem que me disse tudo o que tenho feito. Será que ele não é o Cristo? "

[[v43-4-30]]

^<<v43-4-30,30>>^ Então saíram da cidade e foram para onde ele estava.

[[v43-4-31]]

^<<v43-4-31,31>>^ Enquanto isso, os discípulos insistiam com ele: "Mestre, come alguma coisa".

[[v43-4-32]]

^<<v43-4-32,32>>^ Mas ele lhes disse: "Tenho algo para comer que vocês não conhecem".

[[v43-4-33]]

^<<v43-4-33,33>>^ Então os seus discípulos disseram uns aos outros: "Será que alguém lhe trouxe comida? "

[[v43-4-34]]

^<<v43-4-34,34>>^ Disse Jesus: "A minha comida é fazer a vontade daquele que me enviou e concluir a sua obra.

[[v43-4-35]]

^<<v43-4-35,35>>^ Vocês não dizem: ‘Daqui a quatro meses haverá a colheita’? Eu lhes digo: Abram os olhos e vejam os campos! Eles estão maduros para a colheita.

[[v43-4-36]]

^<<v43-4-36,36>>^ Aquele que colhe já recebe o seu salário e colhe fruto para a vida eterna, de forma que se alegram juntos o que semeia e o que colhe.

[[v43-4-37]]

^<<v43-4-37,37>>^ Assim é verdadeiro o ditado: ‘Um semeia, e outro colhe’.

[[v43-4-38]]

^<<v43-4-38,38>>^ Eu os enviei para colherem o que vocês não cultivaram. Outros realizaram o trabalho árduo, e vocês vieram a usufruir do trabalho deles".

[[v43-4-39]]

^<<v43-4-39,39>>^ Muitos samaritanos daquela cidade creram nele por causa do seguinte testemunho dado pela mulher: "Ele me disse tudo o que tenho feito".

[[v43-4-40]]

^<<v43-4-40,40>>^ Assim, quando se aproximaram dele, os samaritanos insistiram em que ficasse com eles, e ele ficou dois dias.

[[v43-4-41]]

^<<v43-4-41,41>>^ E por causa da sua palavra, muitos outros creram.

[[v43-4-42]]

^<<v43-4-42,42>>^ E disseram à mulher: "Agora cremos não somente por causa do que você disse, pois nós mesmos o ouvimos e sabemos que este é realmente o Salvador do mundo".

[[v43-4-43]]

^<<v43-4-43,43>>^ Depois daqueles dois dias, ele partiu para a Galiléia.

[[v43-4-44]]

^<<v43-4-44,44>>^ ( Jesus tinha afirmado que nenhum profeta tem honra em sua própria terra. )

[[v43-4-45]]

^<<v43-4-45,45>>^ Quando chegou à Galiléia, os galileus deram-lhe boas-vindas. Eles tinham visto tudo o que ele fizera em Jerusalém, por ocasião da festa da Páscoa, pois também haviam estado lá.

[[v43-4-46]]

^<<v43-4-46,46>>^ Mais uma vez, ele visitou Caná da Galiléia, onde tinha transformado água em vinho. E havia ali um oficial do rei, cujo filho estava doente em Cafarnaum.

[[v43-4-47]]

^<<v43-4-47,47>>^ Quando ele ouviu falar que Jesus tinha chegado à Galiléia, vindo da Judéia, procurou-o e suplicou-lhe que fosse curar seu filho, que estava à beira da morte.

[[v43-4-48]]

^<<v43-4-48,48>>^ Disse-lhe Jesus: "Se vocês não virem sinais e maravilhas, nunca crerão".

[[v43-4-49]]

^<<v43-4-49,49>>^ O oficial do rei disse: "Senhor, vem, antes que o meu filho morra".

[[v43-4-50]]

^<<v43-4-50,50>>^ Jesus respondeu: "Pode ir. O seu filho continuará vivo". O homem confiou na palavra de Jesus e partiu.

[[v43-4-51]]

^<<v43-4-51,51>>^ Estando ele ainda a caminho, seus servos vieram ao seu encontro com notícias de que o menino estava vivo.

[[v43-4-52]]

^<<v43-4-52,52>>^ Quando perguntou a que horas o seu filho tinha melhorado, eles lhe disseram: "A febre o deixou ontem, à uma hora da tarde".

[[v43-4-53]]

^<<v43-4-53,53>>^ Então o pai percebeu que aquela fora exatamente a hora em que Jesus lhe dissera: "O seu filho continuará vivo". Assim, creram ele e todos os de sua casa.

[[v43-4-54]]

^<<v43-4-54,54>>^ Esse foi o segundo sinal miraculoso que Jesus realizou, depois que veio da Judéia para a Galiléia.

'''

xref:043-joao/043-joao-003.adoc#v43-3-0[&#60; Capítulo Anterior] | <<v43-4-0,Topo>> | xref:043-joao/043-joao-005.adoc#v43-5-0[Próximo Capítulo &#62;]