include::./index.adoc[]

[[v36-2-0]]
=== Sofonias, 2
// nvi ?, NVI - Nova Versão Internacional

[[v36-2-1]]

^<<v36-2-1,1>>^ Reúna-se e ajunte-se, nação sem pudor,

[[v36-2-2]]

^<<v36-2-2,2>>^ antes que chegue o tempo determinado e aquele dia passe como a palha, antes que venha sobre vocês a ira impetuosa do Senhor, antes que o dia da ira do Senhor os alcance.

[[v36-2-3]]

^<<v36-2-3,3>>^ Busquem o Senhor, todos vocês humildes do país, vocês que fazem o que ele ordena. Busquem a justiça, busquem a humildade; talvez vocês tenham abrigo no dia da ira do Senhor.

[[v36-2-4]]

^<<v36-2-4,4>>^ Gaza será abandonada, e Ascalom ficará arruinada. Ao meio-dia Asdode será banida, e Ecrom será desarraigada.

[[v36-2-5]]

^<<v36-2-5,5>>^ Ai de vocês que vivem junto ao mar, nação dos quereteus; A palavra do Senhor está contra você, ó Canaã, terra dos filisteus. "Eu a destruirei, e não sobrará ninguém".

[[v36-2-6]]

^<<v36-2-6,6>>^ Essa terra junto ao mar, onde habitam os quereteus, será morada de pastores e curral de ovelhas.

[[v36-2-7]]

^<<v36-2-7,7>>^ Ela pertencerá ao remanescente da tribo de Judá. Ali encontrarão pastagem; e ao entardecer, eles se deitarão nas casas de Ascalom. Pois o Senhor, o seu Deus, cuidará deles; ele restaurará a sorte deles.

[[v36-2-8]]

^<<v36-2-8,8>>^ "Ouvi os insultos de Moabe e as zombarias dos amonitas, que insultaram o meu povo e fizeram ameaças contra o seu território.

[[v36-2-9]]

^<<v36-2-9,9>>^ Por isso, juro pela minha vida", declara o Senhor dos Exércitos, o Deus de Israel, "Moabe se tornará como Sodoma e os amonitas como Gomorra: um lugar tomado por ervas daninhas e poços de sal, uma desolação perpétua. O remanescente do meu povo os saqueará; os sobreviventes da minha nação herdarão a terra deles".

[[v36-2-10]]

^<<v36-2-10,10>>^ É isso que eles receberão como recompensa pelo seu orgulho, por insultarem e ridicularizarem o povo do Senhor dos Exércitos.

[[v36-2-11]]

^<<v36-2-11,11>>^ O Senhor será terrível com eles, quando destruir todos os deuses da terra. As nações de todo o mundo o adorarão, cada uma em sua própria terra.

[[v36-2-12]]

^<<v36-2-12,12>>^ "Vocês também, ó etíopes, serão mortos pela minha espada. "

[[v36-2-13]]

^<<v36-2-13,13>>^ Ele estenderá a mão contra o norte e destruirá a Assíria, deixando Nínive totalmente em ruínas, tão seca como o deserto.

[[v36-2-14]]

^<<v36-2-14,14>>^ No meio dela se deitarão rebanhos e todo tipo de animais selvagens. Até a coruja do deserto e o mocho se empoleirarão no topo de suas colunas. Seus gritos ecoarão pelas janelas. Haverá entulho nas entradas, e as vigas de cedro ficarão expostas.

[[v36-2-15]]

^<<v36-2-15,15>>^ Essa é a cidade que exultava, vivendo despreocupada, e dizia para si mesma: "Eu, e mais ninguém! " Que ruínas sobraram! Uma toca de animais selvagens! Todos os que passam por ela zombam e sacodem os punhos.

'''

xref:036-sofonias/036-sofonias-001.adoc#v36-1-0[&#60; Capítulo Anterior] | <<v36-2-0,Topo>> | xref:036-sofonias/036-sofonias-003.adoc#v36-3-0[Próximo Capítulo &#62;]