include::./index.adoc[]

[[v32-3-0]]
=== Jonas, 3
// nvi ?, NVI - Nova Versão Internacional

[[v32-3-1]]

^<<v32-3-1,1>>^ A palavra do Senhor veio a Jonas pela segunda vez com esta ordem:

[[v32-3-2]]

^<<v32-3-2,2>>^ "Vá à grande cidade de Nínive e pregue contra ela a mensagem que eu vou dar a você".

[[v32-3-3]]

^<<v32-3-3,3>>^ E Jonas obedeceu à palavra do Senhor e foi para Nínive. Era uma cidade muito grande; demorava-se três dias para percorrê-la.

[[v32-3-4]]

^<<v32-3-4,4>>^ Jonas entrou na cidade e a percorreu durante um dia, proclamando: "Daqui a quarenta dias Nínive será destruída".

[[v32-3-5]]

^<<v32-3-5,5>>^ Os ninivitas creram em Deus. Proclamaram jejum, e todos eles, do maior ao menor, vestiram-se de pano de saco.

[[v32-3-6]]

^<<v32-3-6,6>>^ Quando as notícias chegaram ao rei de Nínive, ele se levantou do trono, tirou o manto real, vestiu-se de pano de saco e sentou-se sobre cinza.

[[v32-3-7]]

^<<v32-3-7,7>>^ Então fez uma proclamação em Nínive: "Por decreto do rei e de seus nobres: Não é permitido a nenhum homem ou animal, bois ou ovelhas provar coisa alguma; não comam nem bebam!

[[v32-3-8]]

^<<v32-3-8,8>>^ Cubram-se de pano de saco, homens e animais. E todos clamem a Deus com todas as suas forças. Deixem os maus caminhos e a violência.

[[v32-3-9]]

^<<v32-3-9,9>>^ Talvez Deus se arrependa e abandone a sua ira, e não sejamos destruídos".

[[v32-3-10]]

^<<v32-3-10,10>>^ Deus viu o que eles fizeram e como abandonaram os seus maus caminhos. Então Deus se arrependeu e não os destruiu como tinha ameaçado.

'''

xref:032-jonas/032-jonas-002.adoc#v32-2-0[&#60; Capítulo Anterior] | <<v32-3-0,Topo>> | xref:032-jonas/032-jonas-004.adoc#v32-4-0[Próximo Capítulo &#62;]