include::./index.adoc[]

[[v32-1-0]]
=== Jonas, 1
// nvi ?, NVI - Nova Versão Internacional

[[v32-1-1]]

^<<v32-1-1,1>>^ A palavra do Senhor veio a Jonas, filho de Amitai com esta ordem:

[[v32-1-2]]

^<<v32-1-2,2>>^ "Vá depressa à grande cidade de Nínive e pregue contra ela, porque a sua maldade subiu até a minha presença".

[[v32-1-3]]

^<<v32-1-3,3>>^ Mas Jonas fugiu da presença do Senhor, dirigindo-se para Társis. Desceu à cidade de Jope, onde encontrou um navio que se destinava àquele porto. Depois de pagar a passagem, embarcou para Társis, para fugir do Senhor.

[[v32-1-4]]

^<<v32-1-4,4>>^ O Senhor, porém, fez soprar um forte vento sobre o mar, e caiu uma tempestade tão violenta que o barco ameaçava arrebentar-se.

[[v32-1-5]]

^<<v32-1-5,5>>^ Todos os marinheiros ficaram com medo e cada um clamava ao seu próprio deus. E atiraram as cargas ao mar para tornar mais leve o navio. Enquanto isso, Jonas, que tinha descido para o porão e se deitado, dormia profundamente.

[[v32-1-6]]

^<<v32-1-6,6>>^ O capitão dirigiu-se a ele e disse: "Como você pode ficar aí dormindo? Levante-se e clame ao seu deus! Talvez ele tenha piedade de nós e não morramos".

[[v32-1-7]]

^<<v32-1-7,7>>^ Então os marinheiros combinaram entre si: "Vamos tirar sortes para descobrir quem é o responsável por esta desgraça que se abateu sobre nós". Tiraram sortes, e a sorte caiu sobre Jonas.

[[v32-1-8]]

^<<v32-1-8,8>>^ Por isso lhe perguntaram: "Diga-nos, quem é o responsável por esta calamidade? Qual é a sua profissão? De onde você vem? Qual é a sua terra? A que povo você pertence? "

[[v32-1-9]]

^<<v32-1-9,9>>^ Ele respondeu: "Eu sou hebreu, adorador do Senhor, o Deus dos céus, que fez o mar e a terra".

[[v32-1-10]]

^<<v32-1-10,10>>^ Com isso eles ficaram apavorados e perguntaram: "O que foi que você fez? ", pois sabiam que Jonas estava fugindo do Senhor, porque ele já lhes tinha dito.

[[v32-1-11]]

^<<v32-1-11,11>>^ Visto que o mar estava cada vez mais agitado, eles lhe perguntaram: "O que devemos fazer com você, para que o mar se acalme? "

[[v32-1-12]]

^<<v32-1-12,12>>^ Respondeu ele: "Peguem-me e joguem-me ao mar, e ele se acalmará. Pois eu sei que é por minha causa que esta violenta tempestade caiu sobre vocês".

[[v32-1-13]]

^<<v32-1-13,13>>^ Ao invés disso, os homens se esforçaram ao máximo para remar de volta à terra. Mas não conseguiram, porque o mar tinha ficado ainda mais violento.

[[v32-1-14]]

^<<v32-1-14,14>>^ Então eles clamaram ao Senhor: "Senhor, nós suplicamos, não nos deixes morrer por tirarmos a vida deste homem. Não caia sobre nós a culpa de matar um inocente, porque tu, ó Senhor, fizeste o que desejavas".

[[v32-1-15]]

^<<v32-1-15,15>>^ Então, pegaram Jonas e o lançaram ao mar enfurecido, e este se aquietou.

[[v32-1-16]]

^<<v32-1-16,16>>^ Ao verem isso, os homens adoraram ao Senhor com temor, oferecendo-lhe sacrifício e fazendo-lhe votos.

[[v32-1-17]]

^<<v32-1-17,17>>^ Então o Senhor fez com que um grande peixe engolisse Jonas, e ele ficou dentro do peixe três dias e três noites.

'''

xref:031-obadias/031-obadias-001.adoc#v31-1-0[&#60; Capítulo Anterior] | <<v32-1-0,Topo>> | xref:032-jonas/032-jonas-002.adoc#v32-2-0[Próximo Capítulo &#62;]