include::./index.adoc[]

[[v47-1-0]]
=== 2 Coríntios, 1
// nvi ?, NVI - Nova Versão Internacional

[[v47-1-1]]

^<<v47-1-1,1>>^ Paulo, apóstolo de Cristo Jesus pela vontade de Deus, e o irmão Timóteo, à igreja de Deus que está em Corinto, juntamente com todos os santos de toda a Acaia:

[[v47-1-2]]

^<<v47-1-2,2>>^ A vocês, graça e paz da parte de Deus nosso Pai e do Senhor Jesus Cristo.

[[v47-1-3]]

^<<v47-1-3,3>>^ Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, Pai das misericórdias e Deus de toda consolação,

[[v47-1-4]]

^<<v47-1-4,4>>^ que nos consola em todas as nossas tribulações, para que, com a consolação que recebemos de Deus, possamos consolar os que estão passando por tribulações.

[[v47-1-5]]

^<<v47-1-5,5>>^ Pois assim como os sofrimentos de Cristo transbordam sobre nós, também por meio de Cristo transborda a nossa consolação.

[[v47-1-6]]

^<<v47-1-6,6>>^ Se somos atribulados, é para consolação e salvação de vocês; se somos consolados, é para consolação de vocês, a qual lhes dá paciência para suportarem os mesmos sofrimentos que nós estamos padecendo.

[[v47-1-7]]

^<<v47-1-7,7>>^ E a nossa esperança em relação a vocês está firme, porque sabemos que, da mesma forma como vocês participam dos nossos sofrimentos, participam também da nossa consolação.

[[v47-1-8]]

^<<v47-1-8,8>>^ Irmãos, não queremos que vocês desconheçam as tribulações que sofremos na província da Ásia, as quais foram muito além da nossa capacidade de suportar, a ponto de perdermos a esperança da própria vida.

[[v47-1-9]]

^<<v47-1-9,9>>^ De fato, já tínhamos sobre nós a sentença de morte, para que não confiássemos em nós mesmos, mas em Deus, que ressuscita os mortos.

[[v47-1-10]]

^<<v47-1-10,10>>^ Ele nos livrou e continuará nos livrando de tal perigo de morte. Nele temos colocado a nossa esperança de que continuará a livrar-nos,

[[v47-1-11]]

^<<v47-1-11,11>>^ enquanto vocês nos ajudam com as suas orações. Assim muitos darão graças por nossa causa, pelo favor a nós concedido em resposta às orações de muitos.

[[v47-1-12]]

^<<v47-1-12,12>>^ Este é o nosso orgulho: A nossa consciência dá testemunho de que nos temos conduzido no mundo, especialmente em nosso relacionamento com vocês, com santidade e sinceridade provenientes de Deus, não de acordo com a sabedoria do mundo, mas de acordo com a graça de Deus.

[[v47-1-13]]

^<<v47-1-13,13>>^ Pois nada lhes escrevemos que vocês não sejam capazes de ler ou entender. E espero que,

[[v47-1-14]]

^<<v47-1-14,14>>^ assim como vocês nos entenderam em parte, venham a entender plenamente que podem orgulhar-se de nós, assim como nos orgulharemos de vocês no dia do Senhor Jesus.

[[v47-1-15]]

^<<v47-1-15,15>>^ Confiando nisso, e para que vocês fossem duplamente beneficiados, planejava primeiro visitá-los

[[v47-1-16]]

^<<v47-1-16,16>>^ em minha ida à Macedônia e voltar a vocês vindo de lá, para que me ajudassem em minha viagem para a Judéia.

[[v47-1-17]]

^<<v47-1-17,17>>^ Quando planejei isso, será que o fiz levianamente? Ou será que faço meus planos de modo mundano, dizendo ao mesmo tempo "sim" e "não"?

[[v47-1-18]]

^<<v47-1-18,18>>^ Todavia, como Deus é fiel, nossa mensagem a vocês não é "sim" e "não",

[[v47-1-19]]

^<<v47-1-19,19>>^ pois o Filho de Deus, Jesus Cristo, pregado entre vocês por mim e também por Silvano e Timóteo, não foi "sim" e "não", mas nele sempre houve "sim";

[[v47-1-20]]

^<<v47-1-20,20>>^ pois quantas forem as promessas feitas por Deus, tantas têm em Cristo o "sim". Por isso, por meio dele, o "Amém" é pronunciado por nós para a glória de Deus.

[[v47-1-21]]

^<<v47-1-21,21>>^ Ora, é Deus que faz que nós e vocês permaneçamos firmes em Cristo. Ele nos ungiu,

[[v47-1-22]]

^<<v47-1-22,22>>^ nos selou como sua propriedade e pôs o seu Espírito em nossos corações como garantia do que está por vir.

[[v47-1-23]]

^<<v47-1-23,23>>^ Invoco a Deus como testemunha de que foi a fim de poupá-los que não voltei a Corinto.

[[v47-1-24]]

^<<v47-1-24,24>>^ Não que tenhamos domínio sobre a sua fé, mas cooperamos com vocês para que tenham alegria, pois é pela fé que vocês permanecem firmes.

'''

xref:046-1-corintios/046-1-corintios-016.adoc#v46-16-0[&#60; Capítulo Anterior] | <<v47-1-0,Topo>> | xref:047-2-corintios/047-2-corintios-002.adoc#v47-2-0[Próximo Capítulo &#62;]