include::./index.adoc[]

[[v47-9-0]]
=== 2 Coríntios, 9
// nvi ?, NVI - Nova Versão Internacional

[[v47-9-1]]

^<<v47-9-1,1>>^ Não tenho necessidade de escrever-lhes a respeito dessa assistência aos santos.

[[v47-9-2]]

^<<v47-9-2,2>>^ Reconheço a sua disposição em ajudar e já mostrei aos macedônios o orgulho que tenho de vocês, dizendo-lhes que, desde o ano passado, vocês da Acaia estavam prontos a contribuir; e a dedicação de vocês motivou a muitos.

[[v47-9-3]]

^<<v47-9-3,3>>^ Contudo, estou enviando os irmãos para que o orgulho que temos de vocês a esse respeito não seja em vão, mas que vocês estejam preparados, como eu disse que estariam,

[[v47-9-4]]

^<<v47-9-4,4>>^ a fim de que, se alguns macedônios forem comigo e os encontrarem despreparados, nós, para não mencionar vocês, não fiquemos envergonhados por tanta confiança que tivemos.

[[v47-9-5]]

^<<v47-9-5,5>>^ Assim, achei necessário recomendar que os irmãos os visitem antes e concluam os preparativos para a contribuição que vocês prometeram. Então ela estará pronta como oferta generosa, e não como algo dado com avareza.

[[v47-9-6]]

^<<v47-9-6,6>>^ Lembrem-se: aquele que semeia pouco, também colherá pouco, e aquele que semeia com fartura, também colherá fartamente.

[[v47-9-7]]

^<<v47-9-7,7>>^ Cada um dê conforme determinou em seu coração, não com pesar ou por obrigação, pois Deus ama quem dá com alegria.

[[v47-9-8]]

^<<v47-9-8,8>>^ E Deus é poderoso para fazer que lhes seja acrescentada toda a graça, para que em todas as coisas, em todo o tempo, tendo tudo o que é necessário, vocês transbordem em toda boa obra.

[[v47-9-9]]

^<<v47-9-9,9>>^ Como está escrito: "Distribuiu, deu os seus bens aos necessitados; a sua justiça dura para sempre".

[[v47-9-10]]

^<<v47-9-10,10>>^ Aquele que supre a semente ao que semeia e o pão ao que come, também lhes suprirá e aumentará a semente e fará crescer os frutos da sua justiça.

[[v47-9-11]]

^<<v47-9-11,11>>^ Vocês serão enriquecidos de todas as formas, para que possam ser generosos em qualquer ocasião e, por nosso intermédio, a sua generosidade resulte em ação de graças a Deus.

[[v47-9-12]]

^<<v47-9-12,12>>^ O serviço ministerial que vocês estão realizando não está apenas suprindo as necessidades do povo de Deus, mas também transbordando em muitas expressões de gratidão a Deus.

[[v47-9-13]]

^<<v47-9-13,13>>^ Por meio dessa prova de serviço ministerial, outros louvarão a Deus pela obediência que acompanha a confissão que vocês fazem do evangelho de Cristo e pela generosidade de vocês em compartilhar seus bens com eles e com todos os outros.

[[v47-9-14]]

^<<v47-9-14,14>>^ E nas orações que fazem por vocês, eles estarão cheios de amor por vocês, por causa da insuperável graça que Deus tem dado a vocês.

[[v47-9-15]]

^<<v47-9-15,15>>^ Graças a Deus por seu dom indescritível!

'''

xref:047-2-corintios/047-2-corintios-008.adoc#v47-8-0[&#60; Capítulo Anterior] | <<v47-9-0,Topo>> | xref:047-2-corintios/047-2-corintios-010.adoc#v47-10-0[Próximo Capítulo &#62;]