include::./index.adoc[]

[[v47-4-0]]
=== 2 Coríntios, 4
// nvi ?, NVI - Nova Versão Internacional

[[v47-4-1]]

^<<v47-4-1,1>>^ Portanto, visto que temos este ministério pela misericórdia que nos foi dada, não desanimamos.

[[v47-4-2]]

^<<v47-4-2,2>>^ Antes, renunciamos aos procedimentos secretos e vergonhosos; não usamos de engano nem torcemos a palavra de Deus. Pelo contrário, mediante a clara exposição da verdade, recomendamo-nos à consciência de todos, diante de Deus.

[[v47-4-3]]

^<<v47-4-3,3>>^ Mas se o nosso evangelho está encoberto, para os que estão perecendo é que está encoberto.

[[v47-4-4]]

^<<v47-4-4,4>>^ O deus desta era cegou o entendimento dos descrentes, para que não vejam a luz do evangelho da glória de Cristo, que é a imagem de Deus.

[[v47-4-5]]

^<<v47-4-5,5>>^ Pois não nos pregamos a nós mesmos, mas a Jesus Cristo, o Senhor, e a nós como escravos de vocês, por amor de Jesus.

[[v47-4-6]]

^<<v47-4-6,6>>^ Pois Deus que disse: "Das trevas resplandeça a luz", ele mesmo brilhou em nossos corações, para iluminação do conhecimento da glória de Deus na face de Cristo.

[[v47-4-7]]

^<<v47-4-7,7>>^ Mas temos esse tesouro em vasos de barro, para mostrar que este poder que a tudo excede provém de Deus, e não de nós.

[[v47-4-8]]

^<<v47-4-8,8>>^ De todos os lados somos pressionados, mas não desanimados; ficamos perplexos, mas não desesperados;

[[v47-4-9]]

^<<v47-4-9,9>>^ somos perseguidos, mas não abandonados; abatidos, mas não destruídos.

[[v47-4-10]]

^<<v47-4-10,10>>^ Trazemos sempre em nosso corpo o morrer de Jesus, para que a vida de Jesus também seja revelada em nosso corpo.

[[v47-4-11]]

^<<v47-4-11,11>>^ Pois nós, que estamos vivos, somos sempre entregues à morte por amor a Jesus, para que a sua vida também se manifeste em nosso corpo mortal.

[[v47-4-12]]

^<<v47-4-12,12>>^ De modo que em nós atua a morte; mas em vocês, a vida.

[[v47-4-13]]

^<<v47-4-13,13>>^ Está escrito: "Cri, por isso falei". Com esse mesmo espírito de fé nós também cremos e, por isso, falamos,

[[v47-4-14]]

^<<v47-4-14,14>>^ porque sabemos que aquele que ressuscitou ao Senhor Jesus dentre os mortos, também nos ressuscitará com Jesus e nos apresentará com vocês.

[[v47-4-15]]

^<<v47-4-15,15>>^ Tudo isso é para o bem de vocês, para que a graça, que está alcançando um número cada vez maior de pessoas, faça que transbordem as ações de graças para a glória de Deus.

[[v47-4-16]]

^<<v47-4-16,16>>^ Por isso não desanimamos. Embora exteriormente estejamos a desgastar-nos, interiormente estamos sendo renovados dia após dia,

[[v47-4-17]]

^<<v47-4-17,17>>^ pois os nossos sofrimentos leves e momentâneos estão produzindo para nós uma glória eterna que pesa mais do que todos eles.

[[v47-4-18]]

^<<v47-4-18,18>>^ Assim, fixamos os olhos, não naquilo que se vê, mas no que não se vê, pois o que se vê é transitório, mas o que não se vê é eterno.

'''

xref:047-2-corintios/047-2-corintios-003.adoc#v47-3-0[&#60; Capítulo Anterior] | <<v47-4-0,Topo>> | xref:047-2-corintios/047-2-corintios-005.adoc#v47-5-0[Próximo Capítulo &#62;]