include::./index.adoc[]

[[v47-12-0]]
=== 2 Coríntios, 12
// nvi ?, NVI - Nova Versão Internacional

[[v47-12-1]]

^<<v47-12-1,1>>^ É necessário que eu continue a gloriar-me com isso. Ainda que eu não ganhe nada com isso, passarei às visões e revelações do Senhor.

[[v47-12-2]]

^<<v47-12-2,2>>^ Conheço um homem em Cristo que há catorze anos foi arrebatado ao terceiro céu. Se foi no corpo ou fora do corpo, não sei; Deus o sabe.

[[v47-12-3]]

^<<v47-12-3,3>>^ E sei que esse homem — se no corpo ou fora do corpo, não sei, mas Deus o sabe —

[[v47-12-4]]

^<<v47-12-4,4>>^ foi arrebatado ao paraíso e ouviu coisas indizíveis, coisas que ao homem não é permitido falar.

[[v47-12-5]]

^<<v47-12-5,5>>^ Nesse homem me gloriarei, mas não em mim mesmo, a não ser em minhas fraquezas.

[[v47-12-6]]

^<<v47-12-6,6>>^ Mesmo que eu preferisse gloriar-me não seria insensato, porque estaria falando a verdade. Evito fazer isso para que ninguém pense a meu respeito mais do que em mim vê ou de mim ouve.

[[v47-12-7]]

^<<v47-12-7,7>>^ Para impedir que eu me exaltasse por causa da grandeza dessas revelações, foi-me dado um espinho na carne, um mensageiro de Satanás, para me atormentar.

[[v47-12-8]]

^<<v47-12-8,8>>^ Três vezes roguei ao Senhor que o tirasse de mim.

[[v47-12-9]]

^<<v47-12-9,9>>^ Mas ele me disse: "Minha graça é suficiente para você, pois o meu poder se aperfeiçoa na fraqueza". Portanto, eu me gloriarei ainda mais alegremente em minhas fraquezas, para que o poder de Cristo repouse em mim.

[[v47-12-10]]

^<<v47-12-10,10>>^ Por isso, por amor de Cristo, regozijo-me nas fraquezas, nos insultos, nas necessidades, nas perseguições, nas angústias. Pois, quando sou fraco é que sou forte.

[[v47-12-11]]

^<<v47-12-11,11>>^ Fui insensato, mas vocês me obrigaram a isso. Eu devia ser recomendado por vocês, pois em nada sou inferior aos "super-apóstolos", embora eu nada seja.

[[v47-12-12]]

^<<v47-12-12,12>>^ As marcas de um apóstolo — sinais, maravilhas e milagres — foram demonstradas entre vocês, com grande perseverança.

[[v47-12-13]]

^<<v47-12-13,13>>^ Em que vocês foram inferiores às outras igrejas, exceto no fato de eu nunca ter sido um peso para vocês? Perdoem-me esta ofensa!

[[v47-12-14]]

^<<v47-12-14,14>>^ Agora, estou pronto para visitá-los pela terceira vez e não lhes serei um peso, porque o que desejo não são os seus bens, mas vocês mesmos. Além disso, os filhos não devem ajuntar riquezas para os pais, mas os pais para os filhos.

[[v47-12-15]]

^<<v47-12-15,15>>^ Assim, de boa vontade, por amor de vocês, gastarei tudo o que tenho e também me desgastarei pessoalmente. Visto que os amo tanto, devo ser menos amado?

[[v47-12-16]]

^<<v47-12-16,16>>^ Seja como for, não lhes tenho sido um peso. No entanto, como sou astuto, eu os prendi com astúcia.

[[v47-12-17]]

^<<v47-12-17,17>>^ Porventura eu os explorei por meio de alguém que lhes enviei?

[[v47-12-18]]

^<<v47-12-18,18>>^ Recomendei a Tito que os visitasse, acompanhado de outro irmão. Por acaso Tito os explorou? Não agimos nós no mesmo espírito e não seguimos os mesmos passos?

[[v47-12-19]]

^<<v47-12-19,19>>^ Vocês pensam que durante todo este tempo estamos nos defendendo perante vocês? Falamos diante de Deus como alguém que está em Cristo; e tudo o que fazemos, amados irmãos, é para fortalecê-los.

[[v47-12-20]]

^<<v47-12-20,20>>^ Pois temo que, ao visitá-los, não os encontre como eu esperava, e que vocês não me encontrem como esperavam. Temo que haja entre vocês brigas, invejas, manifestações de ira, divisões, calúnias, intrigas, arrogância e desordem.

[[v47-12-21]]

^<<v47-12-21,21>>^ Receio que, ao visitá-los outra vez, o meu Deus me humilhe diante de vocês e eu lamente por causa de muitos que pecaram anteriormente e não se arrependeram da impureza, da imoralidade sexual e da libertinagem que praticaram.

'''

xref:047-2-corintios/047-2-corintios-011.adoc#v47-11-0[&#60; Capítulo Anterior] | <<v47-12-0,Topo>> | xref:047-2-corintios/047-2-corintios-013.adoc#v47-13-0[Próximo Capítulo &#62;]