include::./index.adoc[]

[[v47-13-0]]
=== 2 Coríntios, 13
// nvi ?, NVI - Nova Versão Internacional

[[v47-13-1]]

^<<v47-13-1,1>>^ Esta será minha terceira visita a vocês. "Toda questão precisa ser confirmada pelo depoimento de duas ou três testemunhas".

[[v47-13-2]]

^<<v47-13-2,2>>^ Já os adverti quando estive com vocês pela segunda vez. Agora, estando ausente, escrevo aos que antes pecaram e aos demais: quando voltar, não os pouparei,

[[v47-13-3]]

^<<v47-13-3,3>>^ visto que vocês estão exigindo uma prova de que Cristo fala por meu intermédio. Ele não é fraco ao tratar com vocês, mas poderoso entre vocês.

[[v47-13-4]]

^<<v47-13-4,4>>^ Pois, na verdade, foi crucificado em fraqueza, mas vive pelo poder de Deus. Da mesma forma, somos fracos nele, mas, pelo poder de Deus, viveremos com ele para servir a vocês.

[[v47-13-5]]

^<<v47-13-5,5>>^ Examinem-se para ver se vocês estão na fé; provem-se a si mesmos. Não percebem que Cristo Jesus está em vocês? A não ser que tenham sido reprovados!

[[v47-13-6]]

^<<v47-13-6,6>>^ E espero que saibam que nós não fomos reprovados.

[[v47-13-7]]

^<<v47-13-7,7>>^ Agora, oramos a Deus para que vocês não pratiquem mal algum. Não para que os outros vejam que temos sido aprovados, mas para que vocês façam o que é certo, embora pareça que tenhamos falhado.

[[v47-13-8]]

^<<v47-13-8,8>>^ Pois nada podemos contra a verdade, mas somente em favor da verdade.

[[v47-13-9]]

^<<v47-13-9,9>>^ Ficamos alegres sempre que estamos fracos, e vocês estão fortes; nossa oração é que vocês sejam aperfeiçoados.

[[v47-13-10]]

^<<v47-13-10,10>>^ Por isso escrevo estas coisas estando ausente, para que, quando eu for, não precise ser rigoroso no uso da autoridade que o Senhor me deu para edificá-los, e não para destruí-los.

[[v47-13-11]]

^<<v47-13-11,11>>^ Sem mais, irmãos, despeço-me de vocês! Procurem aperfeiçoar-se, exortem-se mutuamente, tenham um só pensamento, vivam em paz. E o Deus de amor e paz estará com vocês.

[[v47-13-12]]

^<<v47-13-12,12>>^ Saúdem uns aos outros com beijo santo.

[[v47-13-13]]

^<<v47-13-13,13>>^ Todos os santos lhes enviam saudações.

[[v47-13-14]]

^<<v47-13-14,14>>^ A graça do Senhor Jesus Cristo, o amor de Deus e a comunhão do Espírito Santo sejam com todos vocês.

'''

xref:047-2-corintios/047-2-corintios-012.adoc#v47-12-0[&#60; Capítulo Anterior] | <<v47-13-0,Topo>> | xref:048-galatas/048-galatas-001.adoc#v48-1-0[Próximo Capítulo &#62;]