include::./index.adoc[]

[[v47-5-0]]
=== 2 Coríntios, 5
// nvi ?, NVI - Nova Versão Internacional

[[v47-5-1]]

^<<v47-5-1,1>>^ Sabemos que, se for destruída a temporária habitação terrena em que vivemos, temos da parte de Deus um edifício, uma casa eterna no céu, não construída por mãos humanas.

[[v47-5-2]]

^<<v47-5-2,2>>^ Enquanto isso, gememos, desejando ser revestidos da nossa habitação celestial,

[[v47-5-3]]

^<<v47-5-3,3>>^ porque, estando vestidos, não seremos encontrados nus.

[[v47-5-4]]

^<<v47-5-4,4>>^ Pois, enquanto estamos nesta casa, gememos e nos angustiamos, porque não queremos ser despidos, mas revestidos da nossa habitação celestial, para que aquilo que é mortal seja absorvido pela vida.

[[v47-5-5]]

^<<v47-5-5,5>>^ Foi Deus que nos preparou para esse propósito, dando-nos o Espírito como garantia do que está por vir.

[[v47-5-6]]

^<<v47-5-6,6>>^ Portanto, temos sempre confiança e sabemos que, enquanto estamos no corpo, estamos longe do Senhor.

[[v47-5-7]]

^<<v47-5-7,7>>^ Porque vivemos por fé, e não pelo que vemos.

[[v47-5-8]]

^<<v47-5-8,8>>^ Temos, pois, confiança e preferimos estar ausentes do corpo e habitar com o Senhor.

[[v47-5-9]]

^<<v47-5-9,9>>^ Por isso, temos o propósito de lhe agradar, quer estejamos no corpo, quer o deixemos.

[[v47-5-10]]

^<<v47-5-10,10>>^ Pois todos nós devemos comparecer perante o tribunal de Cristo, para que cada um receba de acordo com as obras praticadas por meio do corpo, quer sejam boas quer sejam más.

[[v47-5-11]]

^<<v47-5-11,11>>^ Uma vez que conhecemos o temor ao Senhor, procuramos persuadir os homens. O que somos está manifesto diante de Deus, e esperamos que esteja manifesto também diante da consciência de vocês.

[[v47-5-12]]

^<<v47-5-12,12>>^ Não estamos tentando novamente recomendar-nos a vocês, porém lhes estamos dando a oportunidade de exultarem em nós, para que tenham o que responder aos que se vangloriam das aparências e não do que está no coração.

[[v47-5-13]]

^<<v47-5-13,13>>^ Se enlouquecemos, é por amor a Deus; se conservamos o juízo, é por amor a vocês.

[[v47-5-14]]

^<<v47-5-14,14>>^ Pois o amor de Cristo nos constrange, porque estamos convencidos de que um morreu por todos; logo, todos morreram.

[[v47-5-15]]

^<<v47-5-15,15>>^ E ele morreu por todos para que aqueles que vivem já não vivam mais para si mesmos, mas para aquele que por eles morreu e ressuscitou.

[[v47-5-16]]

^<<v47-5-16,16>>^ De modo que, de agora em diante, a ninguém mais consideramos do ponto de vista humano. Ainda que antes tenhamos considerado a Cristo dessa forma, agora já não o consideramos assim.

[[v47-5-17]]

^<<v47-5-17,17>>^ Portanto, se alguém está em Cristo, é nova criação. As coisas antigas já passaram; eis que surgiram coisas novas!

[[v47-5-18]]

^<<v47-5-18,18>>^ Tudo isso provém de Deus, que nos reconciliou consigo mesmo por meio de Cristo e nos deu o ministério da reconciliação,

[[v47-5-19]]

^<<v47-5-19,19>>^ ou seja, que Deus em Cristo estava reconciliando consigo o mundo, não lançando em conta os pecados dos homens, e nos confiou a mensagem da reconciliação.

[[v47-5-20]]

^<<v47-5-20,20>>^ Portanto, somos embaixadores de Cristo, como se Deus estivesse fazendo o seu apelo por nosso intermédio. Por amor a Cristo lhes suplicamos: Reconciliem-se com Deus.

[[v47-5-21]]

^<<v47-5-21,21>>^ Deus tornou pecado por nós aquele que não tinha pecado, para que nele nos tornássemos justiça de Deus.

'''

xref:047-2-corintios/047-2-corintios-004.adoc#v47-4-0[&#60; Capítulo Anterior] | <<v47-5-0,Topo>> | xref:047-2-corintios/047-2-corintios-006.adoc#v47-6-0[Próximo Capítulo &#62;]