include::./index.adoc[]

[[v47-3-0]]
=== 2 Coríntios, 3
// nvi ?, NVI - Nova Versão Internacional

[[v47-3-1]]

^<<v47-3-1,1>>^ Será que com isso, estamos começando a nos recomendar a nós mesmos novamente? Será que precisamos, como alguns, de cartas de recomendação para vocês ou da parte de vocês?

[[v47-3-2]]

^<<v47-3-2,2>>^ Vocês mesmos são a nossa carta, escrita em nosso coração, conhecida e lida por todos.

[[v47-3-3]]

^<<v47-3-3,3>>^ Vocês demonstram que são uma carta de Cristo, resultado do nosso ministério, escrita não com tinta, mas com o Espírito do Deus vivo, não em tábuas de pedra, mas em tábuas de corações humanos.

[[v47-3-4]]

^<<v47-3-4,4>>^ Tal é a confiança que temos diante de Deus, por meio de Cristo.

[[v47-3-5]]

^<<v47-3-5,5>>^ Não que possamos reivindicar qualquer coisa com base em nossos próprios méritos, mas a nossa capacidade vem de Deus.

[[v47-3-6]]

^<<v47-3-6,6>>^ Ele nos capacitou para sermos ministros de uma nova aliança, não da letra, mas do Espírito; pois a letra mata, mas o Espírito vivifica.

[[v47-3-7]]

^<<v47-3-7,7>>^ O ministério que trouxe a morte foi gravado com letras em pedras; mas esse ministério veio com tal glória que os israelitas não podiam fixar os olhos na face de Moisés por causa do resplendor do seu rosto, ainda que desvanecente.

[[v47-3-8]]

^<<v47-3-8,8>>^ Não será o ministério do Espírito ainda muito mais glorioso?

[[v47-3-9]]

^<<v47-3-9,9>>^ Se era glorioso o ministério que trouxe condenação, quanto mais glorioso será o ministério que produz justiça!

[[v47-3-10]]

^<<v47-3-10,10>>^ Pois o que outrora foi glorioso, agora não tem glória, em comparação com a glória insuperável.

[[v47-3-11]]

^<<v47-3-11,11>>^ E se o que estava se desvanecendo se manifestou com glória, quanto maior será a glória do que permanece!

[[v47-3-12]]

^<<v47-3-12,12>>^ Portanto, visto que temos tal esperança, mostramos muita confiança.

[[v47-3-13]]

^<<v47-3-13,13>>^ Não somos como Moisés, que colocava um véu sobre a face para que os israelitas não contemplassem o resplendor que se desvanecia.

[[v47-3-14]]

^<<v47-3-14,14>>^ Na verdade as mentes deles se fecharam, pois até hoje o mesmo véu permanece quando é lida a antiga aliança. Não foi retirado, porque é somente em Cristo que ele é removido.

[[v47-3-15]]

^<<v47-3-15,15>>^ De fato, até o dia de hoje, quando Moisés é lido, um véu cobre os seus corações.

[[v47-3-16]]

^<<v47-3-16,16>>^ Mas quando alguém se converte ao Senhor, o véu é retirado.

[[v47-3-17]]

^<<v47-3-17,17>>^ Ora, o Senhor é o Espírito e, onde está o Espírito do Senhor, ali há liberdade.

[[v47-3-18]]

^<<v47-3-18,18>>^ E todos nós, que com a face descoberta contemplamos a glória do Senhor, segundo a sua imagem estamos sendo transformados com glória cada vez maior, a qual vem do Senhor, que é o Espírito.

'''

xref:047-2-corintios/047-2-corintios-002.adoc#v47-2-0[&#60; Capítulo Anterior] | <<v47-3-0,Topo>> | xref:047-2-corintios/047-2-corintios-004.adoc#v47-4-0[Próximo Capítulo &#62;]