include::./index.adoc[]

[[v47-6-0]]
=== 2 Coríntios, 6
// nvi ?, NVI - Nova Versão Internacional

[[v47-6-1]]

^<<v47-6-1,1>>^ Como cooperadores de Deus, insistimos com vocês para não receberem em vão a graça de Deus.

[[v47-6-2]]

^<<v47-6-2,2>>^ Pois ele diz: "Eu o ouvi no tempo favorável e o socorri no dia da salvação". Digo-lhes que agora é o tempo favorável, agora é o dia da salvação!

[[v47-6-3]]

^<<v47-6-3,3>>^ Não damos motivo de escândalo a ninguém, em circunstância alguma, para que o nosso ministério não caia em descrédito.

[[v47-6-4]]

^<<v47-6-4,4>>^ Pelo contrário, como servos de Deus, recomendamo-nos de todas as formas: em muita perseverança; em sofrimentos, privações e tristezas;

[[v47-6-5]]

^<<v47-6-5,5>>^ em açoites, prisões e tumultos; em trabalhos árduos, noites sem dormir e jejuns;

[[v47-6-6]]

^<<v47-6-6,6>>^ em pureza, conhecimento, paciência e bondade; no Espírito Santo e no amor sincero;

[[v47-6-7]]

^<<v47-6-7,7>>^ na palavra da verdade e no poder de Deus; com as armas da justiça, quer de ataque, quer de defesa;

[[v47-6-8]]

^<<v47-6-8,8>>^ por honra e por desonra; por difamação e por boa fama; tidos por enganadores, sendo verdadeiros;

[[v47-6-9]]

^<<v47-6-9,9>>^ como desconhecidos, apesar de bem conhecidos; como morrendo, mas eis que vivemos; espancados, mas não mortos;

[[v47-6-10]]

^<<v47-6-10,10>>^ entristecidos, mas sempre alegres; pobres, mas enriquecendo a muitos; nada tendo, mas possuindo tudo.

[[v47-6-11]]

^<<v47-6-11,11>>^ Falamos abertamente a vocês, coríntios, e lhes abrimos todo o nosso coração!

[[v47-6-12]]

^<<v47-6-12,12>>^ Não lhes estamos limitando nosso afeto, mas vocês nos estão limitando o afeto que têm por nós.

[[v47-6-13]]

^<<v47-6-13,13>>^ Numa justa compensação, falo como a meus filhos, abram também o coração para nós!

[[v47-6-14]]

^<<v47-6-14,14>>^ Não se ponham em jugo desigual com descrentes. Pois o que têm em comum a justiça e a maldade? Ou que comunhão pode ter a luz com as trevas?

[[v47-6-15]]

^<<v47-6-15,15>>^ Que harmonia entre Cristo e Belial? Que há de comum entre o crente e o descrente?

[[v47-6-16]]

^<<v47-6-16,16>>^ Que acordo há entre o templo de Deus e os ídolos? Pois somos santuário do Deus vivo. Como disse Deus: "Habitarei com eles e entre eles andarei; serei o seu Deus, e eles serão o meu povo".

[[v47-6-17]]

^<<v47-6-17,17>>^ Portanto, "saiam do meio deles e separem-se", diz o Senhor. "Não toquem em coisas impuras, e eu os receberei"

[[v47-6-18]]

^<<v47-6-18,18>>^ "e lhes serei Pai, e vocês serão meus filhos e minhas filhas", diz o Senhor Todo-poderoso.

'''

xref:047-2-corintios/047-2-corintios-005.adoc#v47-5-0[&#60; Capítulo Anterior] | <<v47-6-0,Topo>> | xref:047-2-corintios/047-2-corintios-007.adoc#v47-7-0[Próximo Capítulo &#62;]