include::./index.adoc[]

[[v47-10-0]]
=== 2 Coríntios, 10
// nvi ?, NVI - Nova Versão Internacional

[[v47-10-1]]

^<<v47-10-1,1>>^ Eu, Paulo, pela mansidão e pela bondade de Cristo, apelo para vocês; eu, que sou "humilde" quando estou face a face com vocês, mas "audaz" quando ausente!

[[v47-10-2]]

^<<v47-10-2,2>>^ Rogo-lhes que, quando estiver presente, não me obriguem a agir com audácia, tal como penso que ousarei fazer, para com alguns que acham que procedemos segundo os padrões humanos.

[[v47-10-3]]

^<<v47-10-3,3>>^ Pois, embora vivamos como homens, não lutamos segundo os padrões humanos.

[[v47-10-4]]

^<<v47-10-4,4>>^ As armas com as quais lutamos não são humanas; pelo contrário, são poderosas em Deus para destruir fortalezas.

[[v47-10-5]]

^<<v47-10-5,5>>^ Destruímos argumentos e toda pretensão que se levanta contra o conhecimento de Deus, e levamos cativo todo pensamento, para torná-lo obediente a Cristo.

[[v47-10-6]]

^<<v47-10-6,6>>^ E estaremos prontos para punir todo ato de desobediência, uma vez completa a obediência de vocês.

[[v47-10-7]]

^<<v47-10-7,7>>^ Vocês observam apenas a aparência das coisas. Se alguém está convencido de que pertence a Cristo, deveria considerar novamente consigo mesmo que, assim como ele, nós também pertencemos a Cristo.

[[v47-10-8]]

^<<v47-10-8,8>>^ Pois mesmo que eu tenha me orgulhado um pouco mais da autoridade que o Senhor nos deu, não me envergonho disso, pois essa autoridade é para edificá-los, e não para destruí-los.

[[v47-10-9]]

^<<v47-10-9,9>>^ Não quero que pareça que estou tentando amedrontá-los com as minhas cartas.

[[v47-10-10]]

^<<v47-10-10,10>>^ Pois alguns dizem: "As cartas dele são duras e fortes, mas ele pessoalmente não impressiona, e a sua palavra é desprezível".

[[v47-10-11]]

^<<v47-10-11,11>>^ Saibam tais pessoas que aquilo que somos em cartas, quando estamos ausentes, seremos em atos, quando estivermos presentes.

[[v47-10-12]]

^<<v47-10-12,12>>^ Não temos a pretensão de nos igualar ou de nos comparar com alguns que se recomendam a si mesmos. Quando eles se medem e se comparam consigo mesmos, agem sem entendimento.

[[v47-10-13]]

^<<v47-10-13,13>>^ Nós, porém, não nos gloriaremos além do limite adequado, mas limitaremos nosso orgulho à esfera de ação que Deus nos confiou, a qual alcança vocês inclusive.

[[v47-10-14]]

^<<v47-10-14,14>>^ Não estamos indo longe demais em nosso orgulho, como seria o caso se não tivéssemos chegado até vocês, pois chegamos a vocês com o evangelho de Cristo.

[[v47-10-15]]

^<<v47-10-15,15>>^ Da mesma forma, não vamos além de nossos limites, gloriando-nos de trabalhos que outros fizeram. Nossa esperança é que, à medida que for crescendo a fé que vocês têm, nossa atuação entre vocês aumente ainda mais,

[[v47-10-16]]

^<<v47-10-16,16>>^ para que possamos pregar o evangelho nas regiões que estão além de vocês, sem nos vangloriarmos de trabalho já realizado em território de outro.

[[v47-10-17]]

^<<v47-10-17,17>>^ Contudo, "quem se gloriar, glorie-se no Senhor",

[[v47-10-18]]

^<<v47-10-18,18>>^ pois não é aprovado quem a si mesmo se recomenda, mas aquele a quem o Senhor recomenda.

'''

xref:047-2-corintios/047-2-corintios-009.adoc#v47-9-0[&#60; Capítulo Anterior] | <<v47-10-0,Topo>> | xref:047-2-corintios/047-2-corintios-011.adoc#v47-11-0[Próximo Capítulo &#62;]