include::./index.adoc[]

[[v47-7-0]]
=== 2 Coríntios, 7
// nvi ?, NVI - Nova Versão Internacional

[[v47-7-1]]

^<<v47-7-1,1>>^ Amados, visto que temos essas promessas, purifiquemo-nos de tudo o que contamina o corpo e o espírito, aperfeiçoando a santidade no temor de Deus.

[[v47-7-2]]

^<<v47-7-2,2>>^ Concedam-nos lugar no coração de vocês. A ninguém prejudicamos, a ninguém causamos dano, a ninguém exploramos.

[[v47-7-3]]

^<<v47-7-3,3>>^ Não digo isso para condená-los; já lhes disse que vocês estão em nosso coração para juntos morrermos ou vivermos.

[[v47-7-4]]

^<<v47-7-4,4>>^ Tenho grande confiança em vocês, e de vocês tenho muito orgulho. Sinto-me bastante encorajado; minha alegria transborda em todas as tribulações.

[[v47-7-5]]

^<<v47-7-5,5>>^ Pois, quando chegamos à Macedônia, não tivemos nenhum descanso, mas fomos atribulados de toda forma: conflitos externos, temores internos.

[[v47-7-6]]

^<<v47-7-6,6>>^ Deus, porém, que consola os abatidos, consolou-nos com a chegada de Tito,

[[v47-7-7]]

^<<v47-7-7,7>>^ e não apenas com a vinda dele, mas também com a consolação que vocês lhe ministraram. Ele nos falou da saudade, da tristeza e da preocupação de vocês por mim, de modo que a minha alegria se tornou ainda maior.

[[v47-7-8]]

^<<v47-7-8,8>>^ Mesmo que a minha carta lhes tenha causado tristeza, não me arrependo. É verdade que a princípio me arrependi, pois percebi que a minha carta os entristeceu, ainda que por pouco tempo. 9 Agora, porém, me alegro, não porque vocês foram entristecidos, mas porque a tristeza os levou ao arrependimento. Pois vocês se entristeceram como Deus desejava, e de forma alguma foram prejudicados por nossa causa.

[[v47-7-9]]

^<<v47-7-9,9>>^ A tristeza segundo Deus produz um arrependimento que leva à salvação e não remorso, mas a tristeza segundo o mundo produz morte.

[[v47-7-10]]

^<<v47-7-10,10>>^ Vejam o que esta tristeza segundo Deus produziu em vocês: que dedicação, que desculpas, que indignação, que temor, que saudade, que preocupação, que desejo de ver a justiça feita! Em tudo vocês se mostraram inocentes a esse respeito.

[[v47-7-11]]

^<<v47-7-11,11>>^ Assim, se lhes escrevi, não foi por causa daquele que cometeu o erro nem daquele que foi prejudicado, mas para que diante de Deus vocês pudessem ver por si próprios como são dedicados a nós.

[[v47-7-12]]

^<<v47-7-12,12>>^ Por isso tudo fomos revigorados.

[[v47-7-13]]

^<<v47-7-13,13>>^ de encorajados, ficamos mais contentes ainda ao ver como Tito estava alegre, porque seu espírito recebeu refrigério de todos vocês.

[[v47-7-14]]

^<<v47-7-14,14>>^ Eu lhe tinha dito que estava orgulhoso de vocês, e vocês não me decepcionaram. Da mesma forma como era verdade tudo o que lhes dissemos, o orgulho que temos de vocês diante de Tito também mostrou-se verdadeiro.

[[v47-7-15]]

^<<v47-7-15,15>>^ E a afeição dele por vocês fica maior ainda, quando lembra que todos vocês foram obedientes, recebendo-o com temor e tremor.

[[v47-7-16]]

^<<v47-7-16,16>>^ Alegro-me por poder ter plena confiança em vocês.

'''

xref:047-2-corintios/047-2-corintios-006.adoc#v47-6-0[&#60; Capítulo Anterior] | <<v47-7-0,Topo>> | xref:047-2-corintios/047-2-corintios-008.adoc#v47-8-0[Próximo Capítulo &#62;]