include::./index.adoc[]

[[v47-2-0]]
=== 2 Coríntios, 2
// nvi ?, NVI - Nova Versão Internacional

[[v47-2-1]]

^<<v47-2-1,1>>^ De modo que resolvi não lhes fazer outra visita que causasse tristeza.

[[v47-2-2]]

^<<v47-2-2,2>>^ Pois, se os entristeço, quem me alegrará senão vocês, a quem tenho entristecido?

[[v47-2-3]]

^<<v47-2-3,3>>^ Escrevi como escrevi para que, quando eu for, não seja entristecido por aqueles que deveriam alegrar-me. Estava confiante em que todos vocês compartilhariam da minha alegria.

[[v47-2-4]]

^<<v47-2-4,4>>^ Pois eu lhes escrevi com grande aflição e angústia de coração, e com muitas lágrimas: não para entristecê-los, mas para que soubessem como e profundo o meu amor por vocês.

[[v47-2-5]]

^<<v47-2-5,5>>^ Se alguém tem causado tristeza, não o tem causado apenas a mim, mas também, em parte, para eu não ser demasiadamente severo, a todos vocês.

[[v47-2-6]]

^<<v47-2-6,6>>^ A punição que lhe foi imposta pela maioria é suficiente.

[[v47-2-7]]

^<<v47-2-7,7>>^ Agora, pelo contrário, vocês devem perdoar-lhe e consolá-lo, para que ele não seja dominado por excessiva tristeza.

[[v47-2-8]]

^<<v47-2-8,8>>^ Portanto, eu lhes recomendo que reafirmem o amor que têm por ele.

[[v47-2-9]]

^<<v47-2-9,9>>^ Eu lhes escrevi com o propósito de saber se vocês seriam aprovados, isto é, se seriam obedientes em tudo.

[[v47-2-10]]

^<<v47-2-10,10>>^ Se vocês perdoam a alguém, eu também perdôo; e aquilo que perdoei, se é que havia alguma coisa para perdoar, perdoei na presença de Cristo, por amor a vocês,

[[v47-2-11]]

^<<v47-2-11,11>>^ a fim de que Satanás não tivesse vantagem sobre nós; pois não ignoramos as suas intenções.

[[v47-2-12]]

^<<v47-2-12,12>>^ Quando cheguei a Trôade para pregar o evangelho de Cristo e vi que o Senhor me havia aberto uma porta,

[[v47-2-13]]

^<<v47-2-13,13>>^ ainda assim, não tive sossego em meu espírito, porque não encontrei ali meu irmão Tito. Por isso, despedi-me deles e fui para a Macedônia.

[[v47-2-14]]

^<<v47-2-14,14>>^ Mas graças a Deus, que sempre nos conduz vitoriosamente em Cristo e por nosso intermédio exala em todo lugar a fragrância do seu conhecimento;

[[v47-2-15]]

^<<v47-2-15,15>>^ porque para Deus somos o aroma de Cristo entre os que estão sendo salvos e os que estão perecendo.

[[v47-2-16]]

^<<v47-2-16,16>>^ Para estes somos cheiro de morte; para aqueles fragrância de vida. Mas, quem está capacitado para tanto?

[[v47-2-17]]

^<<v47-2-17,17>>^ Ao contrário de muitos, não negociamos a palavra de Deus visando lucro; antes, em Cristo falamos diante de Deus com sinceridade, como homens enviados por Deus.

'''

xref:047-2-corintios/047-2-corintios-001.adoc#v47-1-0[&#60; Capítulo Anterior] | <<v47-2-0,Topo>> | xref:047-2-corintios/047-2-corintios-003.adoc#v47-3-0[Próximo Capítulo &#62;]