include::./index.adoc[]

[[v47-8-0]]
=== 2 Coríntios, 8
// nvi ?, NVI - Nova Versão Internacional

[[v47-8-1]]

^<<v47-8-1,1>>^ Agora, irmãos, queremos que vocês tomem conhecimento da graça que Deus concedeu às igrejas da Macedônia.

[[v47-8-2]]

^<<v47-8-2,2>>^ No meio da mais severa tribulação, a grande alegria e a extrema pobreza deles transbordaram em rica generosidade.

[[v47-8-3]]

^<<v47-8-3,3>>^ Pois dou testemunho de que eles deram tudo quanto podiam, e até além do que podiam. Por iniciativa própria

[[v47-8-4]]

^<<v47-8-4,4>>^ eles nos suplicaram insistentemente o privilégio de participar da assistência aos santos.

[[v47-8-5]]

^<<v47-8-5,5>>^ E não somente fizeram o que esperávamos, mas entregaram-se primeiramente a si mesmos ao Senhor e, depois, a nós, pela vontade de Deus.

[[v47-8-6]]

^<<v47-8-6,6>>^ Assim, recomendamos a Tito, visto que ele já havia começado, que completasse esse ato de graça da parte de vocês.

[[v47-8-7]]

^<<v47-8-7,7>>^ Todavia, assim como vocês se destacam em tudo: na fé, na palavra, no conhecimento, na dedicação completa e no amor que vocês têm por nós, destaquem-se também neste privilégio de contribuir.

[[v47-8-8]]

^<<v47-8-8,8>>^ Não lhes estou dando uma ordem, mas quero verificar a sinceridade do amor de vocês, comparando-o com a dedicação dos outros.

[[v47-8-9]]

^<<v47-8-9,9>>^ Pois vocês conhecem a graça de nosso Senhor Jesus Cristo que, sendo rico, se fez pobre por amor de vocês, para que por meio de sua pobreza vocês se tornassem ricos.

[[v47-8-10]]

^<<v47-8-10,10>>^ Este é meu conselho: convém que vocês contribuam, já que desde o ano passado vocês foram os primeiros, não somente a contribuir, mas também a propor esse plano.

[[v47-8-11]]

^<<v47-8-11,11>>^ Agora, completem a obra, para que a forte disposição de realizá-la seja igualada pelo zelo em concluí-la, de acordo com os bens que vocês possuem.

[[v47-8-12]]

^<<v47-8-12,12>>^ Porque, se há prontidão, a contribuição é aceitável de acordo com aquilo que alguém tem, e não de acordo com o que não tem.

[[v47-8-13]]

^<<v47-8-13,13>>^ Nosso desejo não é que outros sejam aliviados enquanto vocês são sobrecarregados, mas que haja igualdade.

[[v47-8-14]]

^<<v47-8-14,14>>^ No presente momento, a fartura de vocês suprirá a necessidade deles, para que, por sua vez, a fartura deles supra a necessidade de vocês. Então haverá igualdade,

[[v47-8-15]]

^<<v47-8-15,15>>^ como está escrito: "Quem tinha recolhido muito não teve demais, e não faltou a quem tinha recolhido pouco".

[[v47-8-16]]

^<<v47-8-16,16>>^ Agradeço a Deus, que pôs no coração de Tito o mesmo cuidado que tenho por vocês,

[[v47-8-17]]

^<<v47-8-17,17>>^ pois Tito não apenas aceitou o nosso pedido, mas está indo até vocês, com muito entusiasmo e por iniciativa própria.

[[v47-8-18]]

^<<v47-8-18,18>>^ Com ele estamos enviando o irmão que é recomendado por todas as igrejas por seu serviço no evangelho.

[[v47-8-19]]

^<<v47-8-19,19>>^ Não só por isso, mas ele também foi escolhido pelas igrejas para nos acompanhar quando formos ministrar esta doação, o que fazemos para honrar o próprio Senhor e mostrar a nossa disposição.

[[v47-8-20]]

^<<v47-8-20,20>>^ Queremos evitar que alguém nos critique quanto ao nosso modo de ministrar essa generosa oferta,

[[v47-8-21]]

^<<v47-8-21,21>>^ pois estamos tendo o cuidado de fazer o que é correto, não apenas aos olhos do Senhor, mas também aos olhos dos homens.

[[v47-8-22]]

^<<v47-8-22,22>>^ Além disso, estamos enviando com eles o nosso irmão que muitas vezes e de muitas maneiras já nos provou que é muito dedicado, e agora ainda mais, por causa da grande confiança que ele tem em vocês.

[[v47-8-23]]

^<<v47-8-23,23>>^ Quanto a Tito, ele é meu companheiro e cooperador entre vocês; quanto a nossos irmãos, eles são representantes das igrejas e uma honra para Cristo.

[[v47-8-24]]

^<<v47-8-24,24>>^ Portanto, diante das demais igrejas, demonstrem a esses irmãos a prova do amor que vocês têm e a razão do orgulho que temos de vocês.

'''

xref:047-2-corintios/047-2-corintios-007.adoc#v47-7-0[&#60; Capítulo Anterior] | <<v47-8-0,Topo>> | xref:047-2-corintios/047-2-corintios-009.adoc#v47-9-0[Próximo Capítulo &#62;]