include::./index.adoc[]

[[v10-10-0]]
=== 2 Samuel, 10
// nvi ?, NVI - Nova Versão Internacional

[[v10-10-1]]

^<<v10-10-1,1>>^ Algum tempo depois, o rei dos amonitas morreu, e seu filho Hanum foi o seu sucessor.

[[v10-10-2]]

^<<v10-10-2,2>>^ Davi pensou: "Serei bondoso com Hanum, filho de Naás, como seu pai foi bondoso comigo". Então Davi enviou uma delegação para transmitir a Hanum seu pesar pela morte do pai. Mas, quando os mensageiros de Davi chegaram à terra dos amonitas,

[[v10-10-3]]

^<<v10-10-3,3>>^ os líderes amonitas disseram a Hanum, seu senhor: "Achas que Davi está honrando teu pai ao enviar mensageiros para expressar condolências? Não é nada disso! Davi os enviou como espiões para examinar a cidade e destruí-la".

[[v10-10-4]]

^<<v10-10-4,4>>^ Então Hanum prendeu os mensageiros de Davi, rapou metade da barba de cada um, cortou metade de suas roupas até as nádegas, e os mandou embora.

[[v10-10-5]]

^<<v10-10-5,5>>^ Quando Davi soube disso, enviou mensageiros ao encontro deles, pois haviam sido profundamente humilhados, e lhes mandou dizer: "Fiquem em Jericó até que a barba cresça, e então voltem para casa".

[[v10-10-6]]

^<<v10-10-6,6>>^ Vendo que tinham atraído sobre si o ódio de Davi, os amonitas contrataram vinte mil soldados de infantaria dos arameus de Bete-Reobe e de Zobá, e mais mil homens do rei de Maaca e doze mil dos homens de Tobe.

[[v10-10-7]]

^<<v10-10-7,7>>^ Ao saber disso, Davi ordenou a Joabe que marchasse com todo o exército.

[[v10-10-8]]

^<<v10-10-8,8>>^ Os amonitas saíram e se puseram em posição de combate na entrada da cidade, e os arameus de Zobá e de Reobe e os homens de Tobe e de Maaca posicionaram-se em campo aberto.

[[v10-10-9]]

^<<v10-10-9,9>>^ Vendo Joabe que estava cercado pelas linhas de combate, escolheu alguns dos melhores soldados de Israel e os posicionou contra os arameus.

[[v10-10-10]]

^<<v10-10-10,10>>^ Pôs o restante dos homens sob o comando de seu irmão Abisai e os posicionou contra os amonitas.

[[v10-10-11]]

^<<v10-10-11,11>>^ E Joabe disse a Abisai: "Se os arameus forem fortes demais para mim, venha me ajudar; mas, se os amonitas forem fortes demais para você, eu irei ajudá-lo.

[[v10-10-12]]

^<<v10-10-12,12>>^ Seja forte e lutemos com bravura pelo nosso povo e pelas cidades do nosso Deus. E que o Senhor faça o que for de sua vontade".

[[v10-10-13]]

^<<v10-10-13,13>>^ Então Joabe e seus soldados avançaram contra os arameus, que fugiram dele.

[[v10-10-14]]

^<<v10-10-14,14>>^ Quando os amonitas viram que os arameus estavam fugindo de Joabe, também fugiram de seu irmão Abisai e entraram na cidade. Assim, Joabe parou a batalha contra os amonitas e voltou para Jerusalém.

[[v10-10-15]]

^<<v10-10-15,15>>^ Ao perceberem que haviam sido derrotados por Israel, os arameus tornaram a agrupar-se.

[[v10-10-16]]

^<<v10-10-16,16>>^ Hadadezer mandou trazer os arameus que viviam do outro lado do Eufrates. Estes chegaram a Helã, tendo à frente Soboque, comandante do exército de Hadadezer.

[[v10-10-17]]

^<<v10-10-17,17>>^ Informado disso, Davi reuniu todo o Israel, atravessou o Jordão e chegou a Helã. Os arameus estavam em posição de combate para enfrentá-lo,

[[v10-10-18]]

^<<v10-10-18,18>>^ mas acabaram fugindo de diante de Israel. E Davi matou setecentos condutores de carros de guerra e quarenta mil soldados de infantaria dos arameus. Soboque, o comandante do exército, também foi ferido e morreu ali mesmo.

[[v10-10-19]]

^<<v10-10-19,19>>^ Quando todos os reis vassalos de Hadadezer viram que tinham sido derrotados por Israel, fizeram a paz com os israelitas e sujeitaram-se a eles. E os arameus ficaram com medo de voltar a ajudar os amonitas.

'''

xref:010-2-samuel/010-2-samuel-009.adoc#v10-9-0[&#60; Capítulo Anterior] | <<v10-10-0,Topo>> | xref:010-2-samuel/010-2-samuel-011.adoc#v10-11-0[Próximo Capítulo &#62;]