include::./index.adoc[]

[[v10-6-0]]
=== 2 Samuel, 6
// nvi ?, NVI - Nova Versão Internacional

[[v10-6-1]]

^<<v10-6-1,1>>^ De novo Davi reuniu os melhores guerreiros de Israel, trinta mil ao todo.

[[v10-6-2]]

^<<v10-6-2,2>>^ Ele e todos os que o acompanhavam partiram para Baalim, em Judá, para buscar a arca de Deus, arca sobre a qual é invocado o nome do Senhor dos Exércitos, entronizado entre os querubins acima dela.

[[v10-6-3]]

^<<v10-6-3,3>>^ Puseram a arca de Deus num carroção novo e a levaram da casa de Abinadabe, na colina. Uzá e Aiô, filhos de Abinadabe, conduziam o carroção

[[v10-6-4]]

^<<v10-6-4,4>>^ com a arca de Deus; e Aiô andava na frente dela.

[[v10-6-5]]

^<<v10-6-5,5>>^ Davi e todos os israelitas iam cantando e dançando perante o Senhor, ao som de todo o tipo de instrumentos de pinho, harpas, liras, tamborins, chocalhos e címbalos.

[[v10-6-6]]

^<<v10-6-6,6>>^ Quando chegaram à eira de Nacom, Uzá esticou o braço e segurou a arca de Deus, porque os bois haviam tropeçado.

[[v10-6-7]]

^<<v10-6-7,7>>^ A ira do Senhor acendeu-se contra Uzá por seu ato de irreverência. Por isso Deus o feriu, e ele morreu ali mesmo, ao lado da arca de Deus.

[[v10-6-8]]

^<<v10-6-8,8>>^ Davi ficou contrariado porque o Senhor, em sua ira, havia fulminado Uzá. Até hoje aquele lugar é chamado Perez-Uzá.

[[v10-6-9]]

^<<v10-6-9,9>>^ Naquele dia, Davi teve medo do Senhor e se perguntou: "Como vou conseguir levar a arca do Senhor? "

[[v10-6-10]]

^<<v10-6-10,10>>^ Por isso ele desistiu de levar a arca do Senhor para a cidade de Davi. Em vez disso, levou-a para a casa de Obede-Edom, de Gate.

[[v10-6-11]]

^<<v10-6-11,11>>^ A arca do Senhor ficou na casa dele por três meses, e o Senhor o abençoou e a toda a sua família.

[[v10-6-12]]

^<<v10-6-12,12>>^ E disseram ao rei Davi: "O Senhor tem abençoado a família de Obede-Edom e tudo o que ele possui, por causa da arca de Deus". Então Davi, com grande festa, foi à casa de Obede-Edom e ordenou que levassem a arca de Deus para a cidade de Davi.

[[v10-6-13]]

^<<v10-6-13,13>>^ Quando os que carregavam a arca do Senhor davam seis passos, ele sacrificava um boi e um novilho gordo.

[[v10-6-14]]

^<<v10-6-14,14>>^ Davi, vestindo o colete sacerdotal de linho, foi dançando com todas as suas forças perante o Senhor,

[[v10-6-15]]

^<<v10-6-15,15>>^ enquanto ele e todos os israelitas levavam a arca do Senhor ao som de gritos de alegria e de trombetas.

[[v10-6-16]]

^<<v10-6-16,16>>^ Aconteceu que, entrando a arca do Senhor na cidade de Davi, Mical, filha de Saul, observava de uma janela. E, ao ver o rei Davi dançando e comemorando perante o Senhor, ela o desprezou em seu coração.

[[v10-6-17]]

^<<v10-6-17,17>>^ Eles trouxeram a arca do Senhor e a colocaram na tenda que Davi lhe havia preparado; e Davi ofereceu holocaustos e sacrifícios de comunhão perante o Senhor.

[[v10-6-18]]

^<<v10-6-18,18>>^ Após oferecer os holocaustos e os sacrifícios de comunhão, ele abençoou o povo em nome do Senhor dos Exércitos,

[[v10-6-19]]

^<<v10-6-19,19>>^ e deu um pão, um bolo de tâmaras e um bolo de uvas passas a cada homem e a cada mulher israelita. Então todo o povo partiu, cada um para a sua casa.

[[v10-6-20]]

^<<v10-6-20,20>>^ Voltando Davi para casa para abençoar sua família, Mical, filha de Saul, saiu ao seu encontro e lhe disse: "Como o rei de Israel se destacou hoje, tirando o manto na frente das escravas de seus servos, como um homem vulgar! "

[[v10-6-21]]

^<<v10-6-21,21>>^ Mas Davi disse a Mical: "Foi perante o Senhor que eu dancei, perante aquele que me escolheu em lugar de seu pai ou de qualquer outro da família dele, quando me designou soberano sobre o povo do Senhor, sobre Israel; perante o Senhor celebrarei

[[v10-6-22]]

^<<v10-6-22,22>>^ e me rebaixarei ainda mais, e me humilharei aos meus próprios olhos. Mas serei honrado por essas escravas que você mencionou".

[[v10-6-23]]

^<<v10-6-23,23>>^ E até o dia de sua morte, Mical, filha de Saul, jamais teve filhos.

'''

xref:010-2-samuel/010-2-samuel-005.adoc#v10-5-0[&#60; Capítulo Anterior] | <<v10-6-0,Topo>> | xref:010-2-samuel/010-2-samuel-007.adoc#v10-7-0[Próximo Capítulo &#62;]