include::./index.adoc[]

[[v10-8-0]]
=== 2 Samuel, 8
// nvi ?, NVI - Nova Versão Internacional

[[v10-8-1]]

^<<v10-8-1,1>>^ Depois disso, Davi derrotou os filisteus e os subjugou, e tirou do controle deles Metegue-Amá.

[[v10-8-2]]

^<<v10-8-2,2>>^ Davi derrotou também os moabitas. Ele os fez deitarem-se no chão e mandou que os medissem com uma corda; os moabitas que ficavam dentro das duas primeiras medidas da corda foram mortos, mas os que ficavam dentro da terceira foram poupados. Assim, os moabitas ficaram sujeitos a Davi, pagando-lhe impostos.

[[v10-8-3]]

^<<v10-8-3,3>>^ Além disso, Davi derrotou Hadadezer, filho de Reobe, rei de Zobá, quando Hadadezer tentava recuperar o controle na região do rio Eufrates.

[[v10-8-4]]

^<<v10-8-4,4>>^ Davi se apossou de mil dos seus carros de guerra, sete mil cavaleiros e vinte mil soldados de infantaria. Ainda levou cem cavalos de carros de guerra, e aleijou todos o outros.

[[v10-8-5]]

^<<v10-8-5,5>>^ Quando os arameus de Damasco vieram ajudar Hadadezer, rei de Zobá, Davi matou vinte e dois mil deles.

[[v10-8-6]]

^<<v10-8-6,6>>^ Em seguida estabeleceu guarnições militares no reino dos arameus de Damasco, sujeitando-os a lhe pagarem impostos. E o Senhor dava vitórias a Davi aonde quer que ele fosse.

[[v10-8-7]]

^<<v10-8-7,7>>^ Davi também levou para Jerusalém os escudos de ouro usados pelos oficiais de Hadadezer.

[[v10-8-8]]

^<<v10-8-8,8>>^ De Tebá e Berotai, cidades que pertenciam a Hadadezer, o rei Davi levou grande quantidade de bronze.

[[v10-8-9]]

^<<v10-8-9,9>>^ Quando Toú, rei de Hamate, soube que Davi tinha derrotado todo o exército de Hadadezer,

[[v10-8-10]]

^<<v10-8-10,10>>^ enviou seu filho Jorão ao rei Davi para saudá-lo e parabenizá-lo por sua vitória na batalha contra Hadadezer, que tinha estado em guerra com Toú. E, com Jorão, mandou todo tipo de utensílios de prata, de ouro e de bronze.

[[v10-8-11]]

^<<v10-8-11,11>>^ O rei Davi consagrou esses utensílios ao Senhor, como fizera com a prata e com o ouro tomados de todas as nações que havia subjugado:

[[v10-8-12]]

^<<v10-8-12,12>>^ Edom e Moabe, os amonitas e os filisteus, e Amaleque. Também consagrou os bens tomados de Hadadezer, filho de Reobe, rei de Zobá.

[[v10-8-13]]

^<<v10-8-13,13>>^ Davi ficou ainda mais famoso ao retornar da batalha em que matou dezoito mil edomitas no vale do Sal.

[[v10-8-14]]

^<<v10-8-14,14>>^ Ele estabeleceu guarnições militares por todo o território de Edom, sujeitando todos os edomitas. O Senhor dava vitórias a Davi aonde quer que ele fosse.

[[v10-8-15]]

^<<v10-8-15,15>>^ Davi reinou sobre todo o Israel, administrando o direito e a justiça a todo o seu povo.

[[v10-8-16]]

^<<v10-8-16,16>>^ Joabe, filho de Zeruia, era comandante do exército; Josafá, filho de Ailude, era o arquivista real;

[[v10-8-17]]

^<<v10-8-17,17>>^ Zadoque, filho de Aitube, e Aimeleque, filho de Abiatar, eram sacerdotes; Seraías era secretário;

[[v10-8-18]]

^<<v10-8-18,18>>^ Benaia, filho de Joiada, comandava os queretitas e os peletitas; e os filhos de Davi eram sacerdotes.

'''

xref:010-2-samuel/010-2-samuel-007.adoc#v10-7-0[&#60; Capítulo Anterior] | <<v10-8-0,Topo>> | xref:010-2-samuel/010-2-samuel-009.adoc#v10-9-0[Próximo Capítulo &#62;]