include::./index.adoc[]

[[v10-12-0]]
=== 2 Samuel, 12
// nvi ?, NVI - Nova Versão Internacional

[[v10-12-1]]

^<<v10-12-1,1>>^ E o Senhor enviou a Davi o profeta Natã. Ao chegar, ele disse a Davi: "Dois homens viviam numa cidade, um era rico e o outro, pobre.

[[v10-12-2]]

^<<v10-12-2,2>>^ O rico possuía muitas ovelhas e bois,

[[v10-12-3]]

^<<v10-12-3,3>>^ mas o pobre nada tinha, senão uma cordeirinha que havia comprado. Ele a criou, e ela cresceu com ele e com seus filhos. Ela comia junto dele, bebia do seu copo e até dormia em seus braços. Era como uma filha para ele.

[[v10-12-4]]

^<<v10-12-4,4>>^ "Certo dia, um viajante chegou à casa do rico, e este não quis pegar uma de suas próprias ovelhas ou do seus bois para preparar-lhe uma refeição. Em vez disso, preparou para o visitante a cordeira que pertencia ao pobre".

[[v10-12-5]]

^<<v10-12-5,5>>^ Então, Davi encheu-se de ira contra o homem e disse a Natã: "Juro pelo nome do Senhor que o homem que fez isso merece a morte!

[[v10-12-6]]

^<<v10-12-6,6>>^ Deverá pagar quatro vezes o preço da cordeira, porquanto agiu sem misericórdia".

[[v10-12-7]]

^<<v10-12-7,7>>^ Então Natã disse a Davi: "Você é esse homem! Assim diz o Senhor, o Deus de Israel: ‘Eu o ungi rei de Israel, e livrei-o das mãos de Saul.

[[v10-12-8]]

^<<v10-12-8,8>>^ Dei-lhe a casa e as mulheres do seu senhor. Dei-lhe a nação de Israel e Judá. E, se tudo isso não fosse suficiente, eu lhe teria dado mais ainda.

[[v10-12-9]]

^<<v10-12-9,9>>^ Por que você desprezou a palavra do Senhor, fazendo o que ele reprova? Você matou Urias, o hitita, com a espada dos amonitas e ficou com a mulher dele.

[[v10-12-10]]

^<<v10-12-10,10>>^ Por isso, a espada nunca se afastará de sua família, pois você me desprezou e tomou a mulher de Urias, o hitita, para ser sua mulher’.

[[v10-12-11]]

^<<v10-12-11,11>>^ "Assim diz o Senhor: ‘De sua própria família trarei desgraça sobre você. Tomarei as suas mulheres diante dos seus próprios olhos e as darei a outro; e ele se deitará com elas em plena luz do dia.

[[v10-12-12]]

^<<v10-12-12,12>>^ Você fez isso às escondidas, mas eu o farei diante de todo o Israel, em plena luz do dia’ ".

[[v10-12-13]]

^<<v10-12-13,13>>^ Então Davi disse a Natã: "Pequei contra o Senhor! " E Natã respondeu: "O Senhor perdoou o seu pecado. Você não morrerá.

[[v10-12-14]]

^<<v10-12-14,14>>^ Entretanto, uma vez que você insultou o Senhor, o menino morrerá".

[[v10-12-15]]

^<<v10-12-15,15>>^ Depois que Natã foi para casa, o Senhor fez adoecer o filho que a mulher de Urias dera a Davi.

[[v10-12-16]]

^<<v10-12-16,16>>^ E Davi implorou a Deus em favor da criança. Ele jejuou e, entrando em casa, passou a noite deitado no chão.

[[v10-12-17]]

^<<v10-12-17,17>>^ Os oficiais do palácio tentaram fazê-lo levantar-se do chão, mas ele não quis, e recusou comer.

[[v10-12-18]]

^<<v10-12-18,18>>^ Sete dias depois a criança morreu. Os conselheiros de Davi estavam com medo de dizer-lhe que a criança estava morta, e comentavam: "Enquanto a criança ainda estava viva, falamos com ele, e ele não quis escutar-nos. Como vamos dizer-lhe que a criança morreu? Ele poderá cometer alguma loucura! "

[[v10-12-19]]

^<<v10-12-19,19>>^ Davi, percebendo que seus conselheiros cochichavam entre si, compreendeu que a criança estava morta e perguntou: "A criança morreu? " "Sim, morreu", responderam eles.

[[v10-12-20]]

^<<v10-12-20,20>>^ Então Davi levantou-se do chão, lavou-se, perfumou-se e trocou de roupa. Depois entrou no santuário do Senhor e adorou. E voltando ao palácio, pediu que lhe preparassem uma refeição e comeu.

[[v10-12-21]]

^<<v10-12-21,21>>^ Seus conselheiros lhe perguntaram: "Por que ages assim? Enquanto a criança estava viva, jejuaste e choraste; mas, agora que a criança está morta, te levantas e comes! "

[[v10-12-22]]

^<<v10-12-22,22>>^ Ele respondeu: "Enquanto a criança ainda estava viva, jejuei e chorei. Eu pensava: ‘Quem sabe? Talvez o Senhor tenha misericórdia de mim e deixe a criança viver’.

[[v10-12-23]]

^<<v10-12-23,23>>^ Mas agora que ela morreu, por que deveria jejuar? Poderia eu trazê-la de volta à vida? Eu irei até ela, mas ela não voltará para mim".

[[v10-12-24]]

^<<v10-12-24,24>>^ Depois Davi consolou sua mulher Bate-Seba e deitou-se com ela, e ela teve um menino, a quem Davi deu o nome de Salomão. E o Senhor o amou

[[v10-12-25]]

^<<v10-12-25,25>>^ e, por isso, enviou o profeta Natã para dizer a Davi que, o menino deveria chamar-se Jedidias.

[[v10-12-26]]

^<<v10-12-26,26>>^ Enquanto isso, Joabe atacou Rabá dos amonitas e conquistou a fortaleza real.

[[v10-12-27]]

^<<v10-12-27,27>>^ Então mandou mensageiros a Davi, dizendo: "Lutei contra Rabá e apoderei-me dos seus reservatórios de água.

[[v10-12-28]]

^<<v10-12-28,28>>^ Agora, convoca o restante do exército, cerca a cidade e conquista-a. Se não, eu terei a fama de havê-la conquistado".

[[v10-12-29]]

^<<v10-12-29,29>>^ Então, Davi convocou todo o exército, foi a Rabá, atacou a cidade e a conquistou.

[[v10-12-30]]

^<<v10-12-30,30>>^ A seguir tirou a coroa da cabeça de Milcom, uma coroa de ouro de trinta e cinco quilos; ornamentada com pedras preciosas. E ela foi colocada na cabeça de Davi. Ele levou uma grande quantidade de bens da cidade

[[v10-12-31]]

^<<v10-12-31,31>>^ e levou também os seus habitantes, designando-lhes trabalhos com serras, picaretas e machados, além da fabricação de tijolos. Davi fez assim com todas as cidades amonitas. Depois voltou com todo o seu exército para Jerusalém.

'''

xref:010-2-samuel/010-2-samuel-011.adoc#v10-11-0[&#60; Capítulo Anterior] | <<v10-12-0,Topo>> | xref:010-2-samuel/010-2-samuel-013.adoc#v10-13-0[Próximo Capítulo &#62;]