include::./index.adoc[]

[[v10-7-0]]
=== 2 Samuel, 7
// nvi ?, NVI - Nova Versão Internacional

[[v10-7-1]]

^<<v10-7-1,1>>^ O rei Davi já morava em seu palácio e o Senhor lhe dera descanso de todos os seus inimigos ao redor.

[[v10-7-2]]

^<<v10-7-2,2>>^ Certo dia ele disse ao profeta Natã: "Aqui estou eu, morando num palácio de cedro, enquanto a arca do Senhor permanece numa simples tenda".

[[v10-7-3]]

^<<v10-7-3,3>>^ Natã respondeu ao rei: "Faze o que tiveres em mente, pois o Senhor está contigo".

[[v10-7-4]]

^<<v10-7-4,4>>^ E naquela mesma noite o Senhor falou a Natã:

[[v10-7-5]]

^<<v10-7-5,5>>^ "Vá dizer a meu servo Davi que assim diz o Senhor: Você construirá uma casa para eu morar?

[[v10-7-6]]

^<<v10-7-6,6>>^ Não tenho morado em nenhuma casa desde o dia em que tirei os israelitas do Egito. Tenho ido de uma tenda para outra, de um tabernáculo para outro.

[[v10-7-7]]

^<<v10-7-7,7>>^ Por onde tenho acompanhado os israelitas, alguma vez perguntei a algum líder deles, a quem ordenei que pastoreasse o meu povo Israel: "Por que você não me construiu um templo de cedro? "

[[v10-7-8]]

^<<v10-7-8,8>>^ "Agora, pois, diga ao meu servo Davi: Assim diz o Senhor dos Exércitos: Eu o tirei das pastagens, onde cuidava dos rebanhos, para ser o soberano do meu povo Israel.

[[v10-7-9]]

^<<v10-7-9,9>>^ Sempre estive com você por onde você andou, e eliminei todos os seus inimigos. Agora eu o farei tão famoso quanto os homens mais importantes da terra.

[[v10-7-10]]

^<<v10-7-10,10>>^ E providenciarei um lugar para o meu povo Israel e os plantarei lá, para que tenham o seu próprio lar e não mais sejam incomodados. Povos ímpios não mais os oprimirão, como fizeram no início

[[v10-7-11]]

^<<v10-7-11,11>>^ e têm feito desde a época em que nomeei juízes sobre o meu povo Israel. Também subjugarei todos os seus inimigos. Saiba também que eu, o Senhor, lhe estabelecerei uma dinastia.

[[v10-7-12]]

^<<v10-7-12,12>>^ Quando a sua vida chegar ao fim e você descansar com os seus antepassados, escolherei um dos seus filhos para sucedê-lo, um fruto do seu próprio corpo, e eu estabelecerei o reino dele.

[[v10-7-13]]

^<<v10-7-13,13>>^ Será ele quem construirá um templo em honra do meu nome, e eu firmarei o trono dele para sempre.

[[v10-7-14]]

^<<v10-7-14,14>>^ Eu serei seu pai, e ele será meu filho. Quando ele cometer algum erro, eu o punirei com o castigo dos homens, com açoites aplicados por homens.

[[v10-7-15]]

^<<v10-7-15,15>>^ Mas nunca retirarei dele o meu amor, como retirei de Saul, a quem tirei do seu caminho.

[[v10-7-16]]

^<<v10-7-16,16>>^ Quanto a você, sua dinastia e seu reino permanecerão para sempre diante de mim; o seu trono será estabelecido para sempre".

[[v10-7-17]]

^<<v10-7-17,17>>^ E Natã transmitiu a Davi tudo o que o Senhor lhe tinha falado e revelado.

[[v10-7-18]]

^<<v10-7-18,18>>^ Então o rei Davi entrou no tabernáculo, assentou-se diante do Senhor, e orou: "Quem sou eu, ó Soberano Senhor, e o que é a minha família, para que me trouxesses a este ponto?

[[v10-7-19]]

^<<v10-7-19,19>>^ E, como se isso não bastasse para ti, ó Soberano Senhor, também falaste sobre o futuro da família deste teu servo. É assim que procedes com os homens, ó Soberano Senhor?

[[v10-7-20]]

^<<v10-7-20,20>>^ "Que mais Davi poderá dizer-te? Tu conheces o teu servo, ó Soberano Senhor.

[[v10-7-21]]

^<<v10-7-21,21>>^ Por amor de tua palavra e de acordo com tua vontade, realizaste este feito grandioso e o revelaste ao teu servo.

[[v10-7-22]]

^<<v10-7-22,22>>^ "Quão grande és tu, ó Soberano Senhor! Não há ninguém como tu nem há outro Deus além de ti, conforme tudo o que sabemos.

[[v10-7-23]]

^<<v10-7-23,23>>^ E quem é como o teu povo Israel, a única nação da terra que tu, ó Deus, resgataste para dela fazeres um povo para ti mesmo, e assim tornaste o teu nome famoso, realizaste grandes e impressionantes maravilhas ao expulsar nações e seus deuses de diante dessa mesma nação que libertaste do Egito?

[[v10-7-24]]

^<<v10-7-24,24>>^ Tu mesmo fizeste de Israel o teu povo particular para sempre, e tu, ó Senhor, te tornaste o seu Deus.

[[v10-7-25]]

^<<v10-7-25,25>>^ "Agora, Senhor Deus, confirma para sempre a promessa que fizeste a respeito de teu servo e de sua descendência. Faze conforme prometeste,

[[v10-7-26]]

^<<v10-7-26,26>>^ para que o teu nome seja engrandecido para sempre e os homens digam: ‘O Senhor dos Exércitos é o Deus de Israel! ’ E a descendência de teu servo Davi se manterá firme diante de ti.

[[v10-7-27]]

^<<v10-7-27,27>>^ "Ó Senhor dos Exércitos, Deus de Israel, tu mesmo o revelaste a teu servo, quando disseste: ‘Estabelecerei uma dinastia para você’. Por isso o teu servo achou coragem para orar a ti.

[[v10-7-28]]

^<<v10-7-28,28>>^ Ó Soberano Senhor, tu és Deus! Tuas palavras são verdadeiras, e tu fizeste essa boa promessa a teu servo.

[[v10-7-29]]

^<<v10-7-29,29>>^ Agora, por tua bondade, abençoa a família de teu servo, para que ela continue para sempre na tua presença. Tu, ó Soberano Senhor, o prometeste! E, abençoada por ti, bendita será para sempre a família de teu servo".

'''

xref:010-2-samuel/010-2-samuel-006.adoc#v10-6-0[&#60; Capítulo Anterior] | <<v10-7-0,Topo>> | xref:010-2-samuel/010-2-samuel-008.adoc#v10-8-0[Próximo Capítulo &#62;]