include::./index.adoc[]

[[v10-13-0]]
=== 2 Samuel, 13
// nvi ?, NVI - Nova Versão Internacional

[[v10-13-1]]

^<<v10-13-1,1>>^ Depois de algum tempo, Amnom, filho de Davi, apaixonou-se por Tamar; ela era muito bonita e era irmã de Absalão, outro filho de Davi.

[[v10-13-2]]

^<<v10-13-2,2>>^ Amnom ficou angustiado a ponto de adoecer por causa de sua meio-irmã Tamar, pois ela era virgem, e parecia-lhe impossível aproximar-se dela.

[[v10-13-3]]

^<<v10-13-3,3>>^ Amnom tinha um amigo muito astuto chamado Jonadabe, filho de Siméia, irmão de Davi.

[[v10-13-4]]

^<<v10-13-4,4>>^ Ele perguntou a Amnom: "Filho do rei, por que todo dia você está abatido? Quer me contar o que se passa? " Amnom lhe disse: "Estou apaixonado por Tamar, irmã de meu irmão Absalão".

[[v10-13-5]]

^<<v10-13-5,5>>^ Então disse Jonadabe: "Vá para a cama e finja estar doente". "Quando seu pai vier visitá-lo, diga-lhe: Permite que minha irmã Tamar venha dar-me de comer. Gostaria que ela preparasse a comida aqui mesmo e me servisse. Assim poderei vê-la. "

[[v10-13-6]]

^<<v10-13-6,6>>^ Amnom atendeu e deitou-se na cama, fingindo-se doente. Quando o rei foi visitá-lo, Amnom lhe disse: "Eu gostaria que minha irmã Tamar viesse e preparasse dois bolos aqui mesmo e me servisse".

[[v10-13-7]]

^<<v10-13-7,7>>^ Davi mandou dizer a Tamar no palácio: "Vá à casa de seu irmão Amnom e prepare algo para ele comer".

[[v10-13-8]]

^<<v10-13-8,8>>^ Assim, Tamar foi à casa de seu irmão, que estava deitado. Ela amassou a farinha, preparou os bolos na presença dele e os assou.

[[v10-13-9]]

^<<v10-13-9,9>>^ Depois pegou a assadeira e lhe serviu os bolos, mas ele não quis comer. Então Amnom deu ordem para que todos saíssem; depois que todos saíram,

[[v10-13-10]]

^<<v10-13-10,10>>^ Amnom disse a Tamar: "Traga os bolos e sirva-me aqui no meu quarto". Tamar levou os bolos que havia preparado ao quarto de seu irmão.

[[v10-13-11]]

^<<v10-13-11,11>>^ Mas quando ela se aproximou para servi-lo, ele a agarrou e disse: "Deite-se comigo, minha irmã".

[[v10-13-12]]

^<<v10-13-12,12>>^ Mas ela lhe disse: "Não, meu irmão! Não me faça essa violência. Não se faz uma coisa dessas em Israel! Não cometa essa loucura.

[[v10-13-13]]

^<<v10-13-13,13>>^ O que seria de mim? Como eu poderia livrar-me da minha desonra? E o que seria de você? Você cairia em desgraça em Israel. Fale com o rei; ele deixará que eu me case com você".

[[v10-13-14]]

^<<v10-13-14,14>>^ Mas Amnom não quis ouvir e, sendo mais forte que ela, violentou-a.

[[v10-13-15]]

^<<v10-13-15,15>>^ Logo depois Amnom sentiu uma forte aversão por ela, mais forte que a paixão que sentira. E disse a ela: "Levante-se e saia! "

[[v10-13-16]]

^<<v10-13-16,16>>^ Mas ela lhe disse: "Não, meu irmão, mandar-me embora seria pior do que o mal que você já me fez". Ele, porém, não quis ouvi-la,

[[v10-13-17]]

^<<v10-13-17,17>>^ e chamando seu servo, disse-lhe: "Ponha esta mulher para fora daqui e tranque a porta".

[[v10-13-18]]

^<<v10-13-18,18>>^ Então o servo a pôs para fora e trancou a porta. Ela estava vestindo uma túnica longa, pois esse era o tipo de roupa que as filhas virgens do rei usavam desde a puberdade.

[[v10-13-19]]

^<<v10-13-19,19>>^ Tamar pôs cinza na cabeça, rasgou a túnica longa que estava usando e se pôs a caminho, com as mãos sobre a cabeça e chorando em alta voz.

[[v10-13-20]]

^<<v10-13-20,20>>^ Absalão, seu irmão, lhe perguntou: "Seu irmão, Amnom, lhe fez algum mal? Agora, acalme-se, minha irmã; ele é seu irmão! Não se deixe dominar pela angústia". E Tamar, muito triste, ficou na casa de seu irmão Absalão.

[[v10-13-21]]

^<<v10-13-21,21>>^ Ao saber de tudo isso, o rei Davi ficou furioso.

[[v10-13-22]]

^<<v10-13-22,22>>^ E Absalão não falou nada com Amnom, nem bem, nem mal, embora o odiasse por ter violentado sua irmã Tamar.

[[v10-13-23]]

^<<v10-13-23,23>>^ Dois anos depois, quando os tosquiadores de ovelhas de Absalão estavam em Baal-Hazor, perto da fronteira de Efraim, Absalão convidou todos os filhos do rei para se reunirem com ele.

[[v10-13-24]]

^<<v10-13-24,24>>^ Absalão foi ao rei e lhe disse: "Eu, teu servo, estou tosquiando as ovelhas e gostaria que o rei e os seus conselheiros estivessem comigo".

[[v10-13-25]]

^<<v10-13-25,25>>^ Respondeu o rei: "Não, meu filho. Não iremos todos, pois isso seria um peso para você". Embora Absalão insistisse, ele se recusou a ir, mas o abençoou.

[[v10-13-26]]

^<<v10-13-26,26>>^ Então Absalão lhe disse: "Se não queres ir, permite, por favor, que o meu irmão Amnom vá conosco". O rei perguntou: "Mas, por que ele iria com você? "

[[v10-13-27]]

^<<v10-13-27,27>>^ Mas Absalão insistiu tanto que o rei acabou deixando que Amnom e os seus outros filhos fossem com ele.

[[v10-13-28]]

^<<v10-13-28,28>>^ Absalão ordenou aos seus homens: "Ouçam! Quando Amnom estiver embriagado de vinho e eu disser: ‘Matem Amnom! ’, vocês o matarão. Não tenham medo; eu assumo a responsabilidade. Sejam fortes e corajosos! "

[[v10-13-29]]

^<<v10-13-29,29>>^ Assim os homens de Absalão mataram Amnom, obedecendo às suas ordens. Então todos os filhos do rei montaram em suas mulas e fugiram.

[[v10-13-30]]

^<<v10-13-30,30>>^ Estando eles ainda a caminho, chegou a seguinte notícia ao rei: "Absalão matou todos os teus filhos; nenhum deles escapou".

[[v10-13-31]]

^<<v10-13-31,31>>^ O rei levantou-se, rasgou as suas vestes, prostrou-se, e todos os conselheiros que estavam com ele também rasgaram as vestes.

[[v10-13-32]]

^<<v10-13-32,32>>^ Mas, Jonadabe, filho de Siméia, irmão de Davi, disse: "Não pense o meu senhor que mataram todos os teus filhos. Somente Amnom foi morto. Essa era a intenção de Absalão desde o dia em que Amnom violentou Tamar, irmã dele.

[[v10-13-33]]

^<<v10-13-33,33>>^ O rei, meu senhor, não deve acreditar que todos os seus filhos estão mortos. Apenas Amnom morreu".

[[v10-13-34]]

^<<v10-13-34,34>>^ Enquanto isso, Absalão fugiu. Nesse meio tempo o sentinela viu muita gente que vinha pela estrada de Horonaim, descendo pela encosta da colina, e disse ao rei: "Vejo homens vindo pela estrada de Horonaim, na encosta da colina".

[[v10-13-35]]

^<<v10-13-35,35>>^ E Jonadabe disse ao rei: "São os filhos do rei! Aconteceu como o teu servo disse".

[[v10-13-36]]

^<<v10-13-36,36>>^ Acabando de falar, os filhos do rei chegaram, chorando em alta voz. Também o rei e todos os seus conselheiros choraram muito.

[[v10-13-37]]

^<<v10-13-37,37>>^ Absalão fugiu para o território de Talmai, filho de Amiúde, rei de Gesur. E o rei Davi pranteava por seu filho todos os dias.

[[v10-13-38]]

^<<v10-13-38,38>>^ Depois que Absalão fugiu para Gesur, e lá permaneceu três anos,

[[v10-13-39]]

^<<v10-13-39,39>>^ a ira do rei contra Absalão cessou, pois ele se sentia consolado da morte de Amnom.

'''

xref:010-2-samuel/010-2-samuel-012.adoc#v10-12-0[&#60; Capítulo Anterior] | <<v10-13-0,Topo>> | xref:010-2-samuel/010-2-samuel-014.adoc#v10-14-0[Próximo Capítulo &#62;]