include::./index.adoc[]

[[v10-18-0]]
=== 2 Samuel, 18
// nvi ?, NVI - Nova Versão Internacional

[[v10-18-1]]

^<<v10-18-1,1>>^ Davi passou em revista o exército e nomeou comandantes de batalhões de mil e de cem.

[[v10-18-2]]

^<<v10-18-2,2>>^ Davi dividiu o exército em três companhias: uma sob o comando de Joabe, outra sob o comando de Abisai, irmão de Joabe, filho de Zeruia, e outra sob o comando de Itai, o giteu. Disse então o rei ao exército: "Eu também marcharei com vocês".

[[v10-18-3]]

^<<v10-18-3,3>>^ Mas os homens disseram: "Não faças isso! Se tivermos que fugir, eles não se preocuparão conosco, e mesmo que metade de nós morra em batalha, eles não se importarão. Tu, porém, vales por dez mil de nós. Melhor será que fiques na cidade e dali nos dês apoio".

[[v10-18-4]]

^<<v10-18-4,4>>^ O rei respondeu: "Farei o que acharem melhor". E o rei ficou junto à porta, enquanto os soldados marchavam, saindo em unidades de cem e de mil.

[[v10-18-5]]

^<<v10-18-5,5>>^ O rei ordenou a Joabe, a Abisai e a Itai: "Por amor a mim, tratem bem o jovem Absalão! " E todo o exército ouviu quando o rei deu essa ordem sobre Absalão a cada um dos comandantes.

[[v10-18-6]]

^<<v10-18-6,6>>^ O exército saiu a campo para enfrentar Israel, e a batalha aconteceu na floresta de Efraim,

[[v10-18-7]]

^<<v10-18-7,7>>^ onde o exército de Israel foi derrotado pelos soldados de Davi. Houve grande matança naquele dia, elevando-se o número de mortos a vinte mil.

[[v10-18-8]]

^<<v10-18-8,8>>^ A batalha espalhou-se por toda a região e, naquele dia, a floresta matou mais que a espada.

[[v10-18-9]]

^<<v10-18-9,9>>^ Durante a batalha, Absalão, montado em sua mula, encontrou-se com os soldados de Davi. Passando a mula debaixo dos galhos de uma grande árvore, e Absalão ficou preso pela cabeça nos galhos. Ele ficou pendurado entre o céu e a terra, e a mula prosseguiu.

[[v10-18-10]]

^<<v10-18-10,10>>^ Um homem o viu, e foi informar a Joabe: "Acabei de ver Absalão pendurado numa grande árvore".

[[v10-18-11]]

^<<v10-18-11,11>>^ "Você o viu? ", perguntou Joabe ao homem. "E por que não o matou ali mesmo? Eu teria dado a você dez peças de prata e um cinturão de guerreiro! "

[[v10-18-12]]

^<<v10-18-12,12>>^ Mas o homem respondeu: "Mesmo que fossem pesadas e colocadas em minhas mãos mil peças de prata, eu não levantaria a mão contra o filho do rei. Ouvimos o rei ordenar a ti, a Abisai e a Itai: ‘Protejam, por amor a mim, o jovem Absalão’.

[[v10-18-13]]

^<<v10-18-13,13>>^ Por outro lado, se eu tivesse atentado traiçoeiramente contra a vida dele, o rei ficaria sabendo, pois não se pode esconder nada dele, e tu mesmo ficarias contra mim".

[[v10-18-14]]

^<<v10-18-14,14>>^ E Joabe disse: "Não vou perder mais tempo com você". Então pegou três dardos e com eles traspassou o coração de Absalão, quando ele ainda estava vivo na árvore.

[[v10-18-15]]

^<<v10-18-15,15>>^ E dez dos escudeiros de Joabe cercaram Absalão e acabaram de matá-lo.

[[v10-18-16]]

^<<v10-18-16,16>>^ A seguir Joabe tocou a trombeta para que o exército parasse de perseguir Israel, e assim deteve o exército.

[[v10-18-17]]

^<<v10-18-17,17>>^ Retiraram o corpo de Absalão, jogaram-no num grande fosso na floresta e fizeram um grande monte de pedras sobre ele. Enquanto isso, todos os israelitas fugiam para casa.

[[v10-18-18]]

^<<v10-18-18,18>>^ Quando em vida, Absalão tinha levantado um monumento para si mesmo no vale do Rei, dizendo: "Não tenho nenhum filho para preservar a minha memória". Por isso deu à coluna o seu próprio nome. Chama-se ainda hoje Monumento de Absalão.

[[v10-18-19]]

^<<v10-18-19,19>>^ Então Aimaás, filho de Zadoque, disse: "Deixa-me correr e levar ao rei a notícia de que o Senhor lhe fez justiça, livrando-o de seus inimigos".

[[v10-18-20]]

^<<v10-18-20,20>>^ "Não é você quem deve levar a notícia hoje", disse-lhe Joabe. "Deixe isso para outra ocasião. Hoje não, porque o filho do rei morreu".

[[v10-18-21]]

^<<v10-18-21,21>>^ Então Joabe ordenou a um etíope: "Vá dizer ao rei o que você viu". O cuxita inclinou-se diante de Joabe e saiu correndo para levar as notícias.

[[v10-18-22]]

^<<v10-18-22,22>>^ Todavia Aimaás, filho de Zadoque, disse de novo a Joabe: "Não importa o que aconteça, deixa-me ir com o cuxita". Joabe, porém, respondeu: "Por que quer tanto ir, meu filho? Você não receberá nenhuma recompensa pela notícia".

[[v10-18-23]]

^<<v10-18-23,23>>^ Mas ele insistiu: "Não importa o que aconteça, quero ir". Disse então Joabe: "Pois vá! " E Aimaás correu pelo caminho da planície e passou à frente do cuxita.

[[v10-18-24]]

^<<v10-18-24,24>>^ Davi estava sentado entre a porta interna e a externa da cidade. E quando a sentinela subiu ao terraço sobre a porta, junto à muralha, viu um homem que vinha correndo sozinho.

[[v10-18-25]]

^<<v10-18-25,25>>^ A sentinela gritou, avisando o rei. O rei disse: "Se ele está sozinho, deve trazer boa notícia". E o homem foi se aproximando.

[[v10-18-26]]

^<<v10-18-26,26>>^ Então a sentinela viu outro homem que vinha correndo e gritou ao porteiro: "Vem outro homem correndo sozinho! " "Esse também deve estar trazendo boa notícia! ", exclamou o rei.

[[v10-18-27]]

^<<v10-18-27,27>>^ A sentinela disse: "Está me parecendo que, pelo jeito de correr, o da frente é Aimaás, filho de Zadoque". "É um bom homem", disse o rei. "Ele traz boas notícias".

[[v10-18-28]]

^<<v10-18-28,28>>^ Então Aimaás aproximou-se do rei e o saudou. Prostrou-se, rosto em terra, diante do rei e disse: "Bendito seja o Senhor teu Deus! Ele entregou os homens que se rebelaram contra o rei, meu senhor".

[[v10-18-29]]

^<<v10-18-29,29>>^ O rei perguntou: "O jovem Absalão está bem? " Aimaás respondeu: "Vi que houve grande confusão quando Joabe, o servo do rei, ia enviar teu servo, mas não sei o que aconteceu".

[[v10-18-30]]

^<<v10-18-30,30>>^ O rei disse: "Fique ali ao lado esperando". E Aimaás ficou esperando.

[[v10-18-31]]

^<<v10-18-31,31>>^ Então o cuxita chegou e disse: "Ó rei, meu senhor, ouve a boa notícia! Hoje o Senhor te livrou de todos os que se levantaram contra ti".

[[v10-18-32]]

^<<v10-18-32,32>>^ O rei perguntou ao cuxita: "O jovem Absalão está bem? " O cuxita respondeu: "Que os inimigos do rei meu senhor e todos que se levantam para lhe fazer mal acabem como aquele jovem! "

[[v10-18-33]]

^<<v10-18-33,33>>^ Então o rei, abalado, subiu ao quarto que ficava por cima da porta e chorou. Foi subindo e clamando: "Ah, meu filho Absalão! Meu filho, meu filho Absalão! Quem me dera ter morrido em seu lugar! Ah, Absalão, meu filho, meu filho! "

'''

xref:010-2-samuel/010-2-samuel-017.adoc#v10-17-0[&#60; Capítulo Anterior] | <<v10-18-0,Topo>> | xref:010-2-samuel/010-2-samuel-019.adoc#v10-19-0[Próximo Capítulo &#62;]