include::./index.adoc[]

[[v10-1-0]]
=== 2 Samuel, 1
// nvi ?, NVI - Nova Versão Internacional

[[v10-1-1]]

^<<v10-1-1,1>>^ Depois da morte de Saul, Davi retornou de sua vitória sobre os amalequitas. Fazia dois dias que ele estava em Ziclague

[[v10-1-2]]

^<<v10-1-2,2>>^ quando, no terceiro dia, chegou um homem que vinha do acampamento de Saul, com as roupas rasgadas e terra na cabeça. Ao aproximar-se de Davi, prostrou-se em terra, em sinal de respeito.

[[v10-1-3]]

^<<v10-1-3,3>>^ Davi então lhe perguntou: "De onde você vem? " Ele respondeu: "Fugi do acampamento israelita".

[[v10-1-4]]

^<<v10-1-4,4>>^ Disse Davi: "Conte-me o que aconteceu? " E o homem contou: "O nosso exército fugiu da batalha, e muitos morreram. Saul e Jônatas também estão mortos".

[[v10-1-5]]

^<<v10-1-5,5>>^ Então Davi perguntou ao jovem que lhe trouxera as notícias: "Como você sabe que Saul e Jônatas estão mortos? "

[[v10-1-6]]

^<<v10-1-6,6>>^ O jovem respondeu: "Cheguei por acaso ao monte Gilboa, e lá estava Saul, apoiado em sua lança. Os carros de guerra e os oficiais da cavalaria estavam a ponto de alcançá-lo.

[[v10-1-7]]

^<<v10-1-7,7>>^ Quando ele se virou e me viu, chamou-me, gritando, e eu disse: ‘Estou aqui’ ".

[[v10-1-8]]

^<<v10-1-8,8>>^ "Ele me perguntou: ‘Quem é você? ’ " ‘Sou um amalequita’, respondi.

[[v10-1-9]]

^<<v10-1-9,9>>^ "Então ele me ordenou: ‘Venha aqui e mate-me! Estou na angústia da morte, mas ainda vivo’.

[[v10-1-10]]

^<<v10-1-10,10>>^ "Por isso aproximei-me dele e o matei, pois sabia que ele não sobreviveria ao ferimento. Peguei a coroa e o bracelete dele e trouxe-os para ti, meu senhor. "

[[v10-1-11]]

^<<v10-1-11,11>>^ Então Davi rasgou suas vestes; e os homens que estavam com ele fizeram o mesmo.

[[v10-1-12]]

^<<v10-1-12,12>>^ E lamentaram, chorando e jejuando até o fim da tarde, por Saul e por seu filho Jônatas, pelo exército do Senhor e pelo povo de Israel, porque muitos haviam sido mortos à espada.

[[v10-1-13]]

^<<v10-1-13,13>>^ E Davi perguntou ao jovem que lhe trouxera as notícias: "De onde você é? " E ele respondeu: "Sou filho de um estrangeiro, sou amalequita".

[[v10-1-14]]

^<<v10-1-14,14>>^ Davi lhe perguntou: "Como você não temeu levantar a mão para matar o ungido do Senhor? "

[[v10-1-15]]

^<<v10-1-15,15>>^ Então Davi chamou um dos seus soldados e disse-lhe: "Venha aqui e mate-o! " O servo o feriu, e o homem morreu.

[[v10-1-16]]

^<<v10-1-16,16>>^ Davi tinha dito ao jovem: "Você é responsável por sua própria morte. Sua boca testemunhou contra você, quando disse: ‘Matei o ungido do Senhor’ ".

[[v10-1-17]]

^<<v10-1-17,17>>^ Davi cantou este lamento sobre Saul e seu filho Jônatas,

[[v10-1-18]]

^<<v10-1-18,18>>^ e ordenou que se ensinasse aos homens de Judá este Lamento do Arco, que foi registrado no Livro de Jasar:

[[v10-1-19]]

^<<v10-1-19,19>>^ "O seu esplendor, ó Israel, está morto sobre os seus montes. Como caíram os guerreiros!

[[v10-1-20]]

^<<v10-1-20,20>>^ "Não conte isso em Gate, não o proclame nas ruas de Ascalom, para que não se alegrem as filhas dos filisteus nem exultem as filhas dos incircuncisos.

[[v10-1-21]]

^<<v10-1-21,21>>^ "Ó colinas de Gilboa, nunca mais haja orvalho nem chuva sobre vocês, nem campos que produzam trigo para as ofertas. Porque ali foi profanado o escudo dos guerreiros, o escudo de Saul, que nunca mais será polido com óleo.

[[v10-1-22]]

^<<v10-1-22,22>>^ Do sangue dos mortos, da carne dos guerreiros, o arco de Jônatas nunca recuou, a espada de Saul sempre cumpriu a sua tarefa.

[[v10-1-23]]

^<<v10-1-23,23>>^ "Saul e Jônatas, mui amados, nem na vida nem na morte foram separados. Eram mais ágeis que as águias, mais fortes que os leões.

[[v10-1-24]]

^<<v10-1-24,24>>^ "Chorem por Saul, ó filhas de Israel! Chorem aquele que as vestia de rubros ornamentos, e suas roupas enfeitava com adornos de ouro.

[[v10-1-25]]

^<<v10-1-25,25>>^ "Como caíram os guerreiros no meio da batalha! Jônatas está morto sobre os montes de Israel.

[[v10-1-26]]

^<<v10-1-26,26>>^ Como estou triste por você, Jônatas, meu irmão! Como eu lhe queria bem! Sua amizade me era mais preciosa que o amor das mulheres!

[[v10-1-27]]

^<<v10-1-27,27>>^ "Caíram os guerreiros! As armas de guerra foram destruídas! "

'''

xref:009-1-samuel/009-1-samuel-031.adoc#v9-31-0[&#60; Capítulo Anterior] | <<v10-1-0,Topo>> | xref:010-2-samuel/010-2-samuel-002.adoc#v10-2-0[Próximo Capítulo &#62;]