include::./index.adoc[]

[[v10-3-0]]
=== 2 Samuel, 3
// nvi ?, NVI - Nova Versão Internacional

[[v10-3-1]]

^<<v10-3-1,1>>^ A guerra entre as famílias de Saul e Davi durou muito tempo. Davi tornava-se cada vez mais forte, enquanto que a família de Saul se enfraquecia.

[[v10-3-2]]

^<<v10-3-2,2>>^ Estes foram os filhos de Davi nascidos em Hebrom: O seu filho mais velho era Amnom, filho de Ainoã, de Jezreel;

[[v10-3-3]]

^<<v10-3-3,3>>^ o segundo, Quileabe, de Abigail, viúva de Nabal, de Carmelo; o terceiro, Absalão, de Maaca, filha de Talmai, rei de Gesur;

[[v10-3-4]]

^<<v10-3-4,4>>^ o quarto, Adonias, de Hagite; o quinto, Sefatias, de Abital;

[[v10-3-5]]

^<<v10-3-5,5>>^ e o sexto, Itreão, de sua mulher Eglá. Esses foram os filhos de Davi que lhe nasceram em Hebrom.

[[v10-3-6]]

^<<v10-3-6,6>>^ Enquanto transcorria a guerra entre as famílias de Saul e de Davi, Abner foi se tornando poderoso na família de Saul.

[[v10-3-7]]

^<<v10-3-7,7>>^ Saul tivera uma concubina chamada Rispa, filha de Aiá. Certa vez Is-Bosete perguntou a Abner: "Por que você se deitou com a concubina de meu pai? "

[[v10-3-8]]

^<<v10-3-8,8>>^ Abner ficou furioso com a pergunta de Is-Bosete e exclamou: "Por acaso eu sou um cão a serviço de Judá? Até agora tenho sido leal à família de Saul, seu pai, e aos parentes e amigos dele, e não deixei que você caísse nas mãos de Davi; e agora você me acusa de um delito envolvendo esta mulher!

[[v10-3-9]]

^<<v10-3-9,9>>^ Que Deus me castigue com todo rigor, se eu não fizer por Davi o que o Senhor lhe prometeu sob juramento,

[[v10-3-10]]

^<<v10-3-10,10>>^ tirar o reino da família de Saul e estabelecer o trono de Davi sobre Israel e Judá, de Dã a Berseba".

[[v10-3-11]]

^<<v10-3-11,11>>^ Is-Bosete não respondeu nada a Abner, pois tinha medo dele.

[[v10-3-12]]

^<<v10-3-12,12>>^ Então Abner enviou mensageiros a Davi com esta proposta: "A quem pertence esta terra? Faze um acordo comigo e eu te ajudarei a conseguir o apoio de todo o Israel".

[[v10-3-13]]

^<<v10-3-13,13>>^ "Está bem", disse Davi. "Farei um acordo com você, mas com uma condição: não compareça à minha presença sem trazer-me Mical, filha de Saul, quando você vier me ver. "

[[v10-3-14]]

^<<v10-3-14,14>>^ E Davi enviou mensageiros a Is-Bosete, filho de Saul, exigindo: "Entregue-me minha mulher Mical, com quem me casei pelo preço de cem prepúcios de filisteus".

[[v10-3-15]]

^<<v10-3-15,15>>^ Diante disso, Is-Bosete mandou que a tirassem do seu marido Paltiel, filho de Laís.

[[v10-3-16]]

^<<v10-3-16,16>>^ Mas Paltiel foi atrás dela, e a seguiu chorando até Baurim. Então Abner ordenou-lhe que voltasse para casa; e ele voltou.

[[v10-3-17]]

^<<v10-3-17,17>>^ Nesse meio tempo, Abner enviou esta mensagem às autoridades de Israel: "Já faz algum tempo que vocês querem Davi como rei.

[[v10-3-18]]

^<<v10-3-18,18>>^ Agora é o momento de agir! Porque o Senhor prometeu a Davi: ‘Por meio de Davi, meu servo, livrarei Israel do poder dos filisteus e de todos os seus inimigos’ ".

[[v10-3-19]]

^<<v10-3-19,19>>^ Abner também falou pessoalmente com os benjamitas. Depois foi a Hebrom dizer a Davi tudo o que Israel e a tribo de Benjamim haviam aprovado.

[[v10-3-20]]

^<<v10-3-20,20>>^ Quando Abner, acompanhado de vinte homens, apresentou-se a Davi em Hebrom, este ofereceu um banquete para ele e para os homens que o acompanhavam.

[[v10-3-21]]

^<<v10-3-21,21>>^ Disse então Abner a Davi: "Deixa que eu me vá e reúna todo o Israel, meu senhor, para que façam um acordo contigo, ó rei, e reines sobre tudo o que desejares". Davi o deixou ir, e ele se foi em paz.

[[v10-3-22]]

^<<v10-3-22,22>>^ Naquele momento, os soldados de Davi e Joabe voltavam de um ataque, trazendo muitos bens. Abner, porém, já não estava com Davi em Hebrom, porque Davi o tinha deixado partir em paz.

[[v10-3-23]]

^<<v10-3-23,23>>^ Quando Joabe chegou com todo o seu exército, contaram-lhe que Abner, filho de Ner, se apresentara ao rei, que o tinha deixado ir em paz.

[[v10-3-24]]

^<<v10-3-24,24>>^ Então Joabe foi falar com o rei e lhe disse: "Que foi que fizeste? Abner veio à tua presença e o deixaste ir?

[[v10-3-25]]

^<<v10-3-25,25>>^ Conheces Abner, filho de Ner; ele veio para enganá-lo, observar os teus movimentos e descobrir tudo o que estás fazendo".

[[v10-3-26]]

^<<v10-3-26,26>>^ Saindo da presença de Davi, Joabe enviou mensageiros atrás de Abner, e eles o trouxeram de volta, desde a cisterna de Sirá. Mas Davi não ficou sabendo disso.

[[v10-3-27]]

^<<v10-3-27,27>>^ Quando Abner retornou a Hebrom, Joabe o chamou à parte, na porta da cidade, sob o pretexto de falar-lhe em particular, e ali mesmo o feriu no estômago. E Abner morreu por ter derramado o sangue de Asael, irmão de Joabe.

[[v10-3-28]]

^<<v10-3-28,28>>^ Mais tarde, quando Davi soube o que tinha acontecido, disse: "Eu e o meu reino, perante o Senhor, somos para sempre inocentes do sangue de Abner, filho de Ner.

[[v10-3-29]]

^<<v10-3-29,29>>^ Caia a responsabilidade pela morte dele sobre a cabeça de Joabe e de toda a sua família! Jamais falte entre os seus descendentes quem sofra fluxo ou lepra, quem use muletas, quem morra pela espada, ou quem passe fome".

[[v10-3-30]]

^<<v10-3-30,30>>^ Assim, Joabe e seu irmão Abisai mataram Abner porque ele havia matado Asael, irmão deles, na batalha de Gibeom.

[[v10-3-31]]

^<<v10-3-31,31>>^ Então Davi disse a Joabe e a todo o exército que o acompanhava: "Rasguem suas vestes, vistam roupas de luto e vão chorando à frente de Abner". E o rei Davi seguiu atrás da maca que levava o corpo.

[[v10-3-32]]

^<<v10-3-32,32>>^ Enterraram-no em Hebrom, e o rei chorou em alta voz junto ao túmulo de Abner, como também todo o povo.

[[v10-3-33]]

^<<v10-3-33,33>>^ Então o rei cantou este lamento por Abner: "Por que morreu Abner como morrem os insensatos?

[[v10-3-34]]

^<<v10-3-34,34>>^ Suas mãos não estavam algemadas, nem seus pés acorrentados. Você caiu como quem cai perante homens perversos". E todo o povo chorou ainda mais por ele.

[[v10-3-35]]

^<<v10-3-35,35>>^ Depois, quando o povo insistiu com Davi que comesse alguma coisa enquanto ainda era dia, Davi fez este juramento: "Deus me castigue com todo rigor, caso eu prove pão ou qualquer outra coisa antes do pôr-do-sol! "

[[v10-3-36]]

^<<v10-3-36,36>>^ Todo o povo ouviu isso e aprovou; de fato, tudo o que o rei fazia o povo aprovava.

[[v10-3-37]]

^<<v10-3-37,37>>^ Assim, naquele dia, todo o povo e todo o Israel reconheceram que o rei não tivera participação no assassinato de Abner, filho de Ner.

[[v10-3-38]]

^<<v10-3-38,38>>^ Então o rei disse aos seus conselheiros: "Não percebem que caiu hoje em Israel um líder, um grande homem?

[[v10-3-39]]

^<<v10-3-39,39>>^ Embora rei ungido, ainda sou fraco, e esses filhos de Zeruia são mais fortes do que eu. Que o Senhor retribua ao malfeitor de acordo com as suas más obras! "

'''

xref:010-2-samuel/010-2-samuel-002.adoc#v10-2-0[&#60; Capítulo Anterior] | <<v10-3-0,Topo>> | xref:010-2-samuel/010-2-samuel-004.adoc#v10-4-0[Próximo Capítulo &#62;]