include::./index.adoc[]

[[v10-16-0]]
=== 2 Samuel, 16
// nvi ?, NVI - Nova Versão Internacional

[[v10-16-1]]

^<<v10-16-1,1>>^ Mal Davi tinha passado pelo alto do monte, lá estava à sua espera Ziba, criado de Mefibosete. Ele trazia dois jumentos carregando duzentos pães, cem bolos de uvas passas, cem frutas da estação e uma vasilha de couro cheia de vinho.

[[v10-16-2]]

^<<v10-16-2,2>>^ O rei perguntou a Ziba: "Por que você trouxe essas coisas? " Ziba respondeu: "Os jumentos servirão de montaria para a família do rei, os pães e as frutas são para os homens comerem, e o vinho servirá para reanimar os que ficarem exaustos no deserto".

[[v10-16-3]]

^<<v10-16-3,3>>^ O rei então perguntou: "Onde está Mefibosete, neto de seu senhor? " Respondeu-lhe Ziba: "Ele ficou em Jerusalém, pois acredita que os israelitas lhe restituirão o reino de seu avô ".

[[v10-16-4]]

^<<v10-16-4,4>>^ Então o rei disse a Ziba: "Tudo o que pertencia a Mefibosete agora é seu". "Humildemente me prostro", disse Ziba. "Que o rei, meu senhor, agrade-se de mim".

[[v10-16-5]]

^<<v10-16-5,5>>^ Chegando o rei Davi a Baurim, um homem do clã da família de Saul chamado Simei, filho de Gera, saiu da cidade proferindo maldições contra ele.

[[v10-16-6]]

^<<v10-16-6,6>>^ Ele atirava pedras em Davi e em todos os conselheiros do rei, embora todo o exército e a guarda de elite estivessem à direita e à esquerda de Davi.

[[v10-16-7]]

^<<v10-16-7,7>>^ Enquanto amaldiçoava, Simei dizia: "Saia daqui, saia daqui! Assassino! Bandido!

[[v10-16-8]]

^<<v10-16-8,8>>^ O Senhor retribuiu a você todo o sangue derramado na família de Saul, em cujo lugar você reinou. O Senhor entregou o reino nas mãos de seu filho Absalão. Você está arruinado porque é um assassino! "

[[v10-16-9]]

^<<v10-16-9,9>>^ Então Abisai, filho de Zeruia, disse ao rei: "Por que esse cão morto amaldiçoa o rei meu senhor? Permite que eu lhe corte a cabeça".

[[v10-16-10]]

^<<v10-16-10,10>>^ Mas o rei disse: "Que é que vocês têm com isso, filhos de Zeruia? Ele me amaldiçoa porque o Senhor lhe disse que amaldiçoasse Davi. Portanto, quem poderá questioná-lo? "

[[v10-16-11]]

^<<v10-16-11,11>>^ Disse então Davi a Abisai e a todos os seus conselheiros: "Até meu filho, sangue do meu sangue, procura matar-me. Quanto mais este benjamita! Deixem-no em paz! Que amaldiçoe, pois foi o que o Senhor lhe mandou fazer.

[[v10-16-12]]

^<<v10-16-12,12>>^ Talvez o Senhor considere a minha aflição e me retribua com o bem a maldição que hoje recebo".

[[v10-16-13]]

^<<v10-16-13,13>>^ Assim, Davi e os seus soldados prosseguiram pela estrada, enquanto Simei ia pela encosta do monte, no lado oposto, amaldiçoando, jogando pedras e terra.

[[v10-16-14]]

^<<v10-16-14,14>>^ O rei e todo o povo que estava com ele chegaram exaustos a seu destino. E lá descansaram.

[[v10-16-15]]

^<<v10-16-15,15>>^ Enquanto isso, Absalão e todos os homens de Israel entraram em Jerusalém, e Aitofel estava com eles.

[[v10-16-16]]

^<<v10-16-16,16>>^ Então Husai, o arquita, amigo de Davi, aproximou-se de Absalão e exclamou: "Viva o rei! Viva o rei! "

[[v10-16-17]]

^<<v10-16-17,17>>^ Mas Absalão disse a Husai: "É essa a lealdade que você tem para com o seu amigo? Por que você não foi com ele? "

[[v10-16-18]]

^<<v10-16-18,18>>^ Respondeu Husai: "Não! Sou do escolhido do Senhor, deste povo e de todos os israelitas; e com ele permanecerei.

[[v10-16-19]]

^<<v10-16-19,19>>^ Além disso, a quem devo servir? Não deveria eu servir o filho? Assim como servi a teu pai, também te servirei".

[[v10-16-20]]

^<<v10-16-20,20>>^ Então Absalão disse a Aitofel: "Dê-nos o seu conselho. Que devemos fazer? "

[[v10-16-21]]

^<<v10-16-21,21>>^ Aitofel respondeu: "Tenha relações com as concubinas de teu pai, que ele deixou para tomar conta do palácio. Então todo o Israel ficará sabendo que te tornaste repugnante para teu pai, e todos os que estão contigo se encherão de coragem".

[[v10-16-22]]

^<<v10-16-22,22>>^ E assim armaram uma tenda no terraço do palácio para Absalão, e ele teve relações com as concubinas de seu pai à vista de todo o Israel.

[[v10-16-23]]

^<<v10-16-23,23>>^ Naquela época, tanto Davi como Absalão consideravam os conselhos de Aitofel como se fossem a palavra do próprio Deus.

'''

xref:010-2-samuel/010-2-samuel-015.adoc#v10-15-0[&#60; Capítulo Anterior] | <<v10-16-0,Topo>> | xref:010-2-samuel/010-2-samuel-017.adoc#v10-17-0[Próximo Capítulo &#62;]