include::./index.adoc[]

[[v10-22-0]]
=== 2 Samuel, 22
// nvi ?, NVI - Nova Versão Internacional

[[v10-22-1]]

^<<v10-22-1,1>>^ Davi cantou ao Senhor este cântico, quando este o livrou das mãos de todos os seus inimigos e das mãos de Saul,

[[v10-22-2]]

^<<v10-22-2,2>>^ dizendo: "O Senhor é a minha rocha, a minha fortaleza e o meu libertador;

[[v10-22-3]]

^<<v10-22-3,3>>^ o meu Deus é a minha rocha, em que me refugio; o meu escudo e o meu poderoso salvador. Ele é a minha torre alta, o meu abrigo seguro. És o meu salvador, que me salva dos violentos.

[[v10-22-4]]

^<<v10-22-4,4>>^ Clamo ao Senhor, que é digno de louvor, e sou salvo dos meus inimigos.

[[v10-22-5]]

^<<v10-22-5,5>>^ "As ondas da morte me cercaram; as torrentes da destruição me aterrorizaram.

[[v10-22-6]]

^<<v10-22-6,6>>^ As cordas da sepultura me envolveram; as armadilhas da morte me confrontaram.

[[v10-22-7]]

^<<v10-22-7,7>>^ Na minha angústia, clamei ao Senhor; clamei ao meu Deus. Do seu templo ele ouviu a minha voz; o meu grito de socorro chegou aos seus ouvidos.

[[v10-22-8]]

^<<v10-22-8,8>>^ "A terra abalou-se e tremeu, os alicerces dos céus estremeceram; tremeram porque ele estava irado.

[[v10-22-9]]

^<<v10-22-9,9>>^ Das suas narinas saiu fumaça; da sua boca saiu fogo consumidor; dele saíram brasas vivas e flamejantes.

[[v10-22-10]]

^<<v10-22-10,10>>^ Ele abriu os céus e desceu; nuvens escuras estavam debaixo dos seus pés.

[[v10-22-11]]

^<<v10-22-11,11>>^ Montou sobre um querubim e voou; elevou-se sobre as asas do vento.

[[v10-22-12]]

^<<v10-22-12,12>>^ Pôs as trevas ao seu redor; das densas nuvens de chuva fez o seu abrigo.

[[v10-22-13]]

^<<v10-22-13,13>>^ Do brilho da sua presença flamejavam carvões em brasa.

[[v10-22-14]]

^<<v10-22-14,14>>^ Dos céus o Senhor trovejou; ressoou a voz do Altíssimo.

[[v10-22-15]]

^<<v10-22-15,15>>^ Ele atirou flechas e dispersou os inimigos, arremessou raios e os fez bater em retirada.

[[v10-22-16]]

^<<v10-22-16,16>>^ Os vales apareceram, e os fundamentos da terra foram expostos, diante da repreensão do Senhor, com o forte sopro de suas narinas.

[[v10-22-17]]

^<<v10-22-17,17>>^ "Das alturas estendeu a mão e me segurou; tirou-me de águas profundas.

[[v10-22-18]]

^<<v10-22-18,18>>^ Livrou-me do meu inimigo poderoso, dos meus adversários, que eram fortes demais para mim.

[[v10-22-19]]

^<<v10-22-19,19>>^ Eles me atacaram no dia da minha calamidade, mas o Senhor foi o meu amparo.

[[v10-22-20]]

^<<v10-22-20,20>>^ Deu-me ampla liberdade; livrou-me, pois me quer bem.

[[v10-22-21]]

^<<v10-22-21,21>>^ "O Senhor me tratou segundo a minha retidão; segundo a pureza das minhas mãos me recompensou.

[[v10-22-22]]

^<<v10-22-22,22>>^ Pois guardei os caminhos do Senhor; não cometi a perversidade de afastar-me do meu Deus.

[[v10-22-23]]

^<<v10-22-23,23>>^ Todos os seus mandamentos estão diante de mim; não me afastei dos seus decretos.

[[v10-22-24]]

^<<v10-22-24,24>>^ Tenho sido irrepreensível para com ele e guardei-me de pecar.

[[v10-22-25]]

^<<v10-22-25,25>>^ O Senhor recompensou-me segundo a minha retidão, segundo a pureza das minhas mãos perante ele.

[[v10-22-26]]

^<<v10-22-26,26>>^ "Ao fiel te revelas fiel, ao irrepreensível te revelas irrepreensível,

[[v10-22-27]]

^<<v10-22-27,27>>^ ao puro te revelas puro, mas ao perverso te revelas astuto.

[[v10-22-28]]

^<<v10-22-28,28>>^ Salvas os humildes, mas os teus olhos estão sobre os orgulhosos para os humilhar.

[[v10-22-29]]

^<<v10-22-29,29>>^ Tu és a minha lâmpada, ó Senhor! O Senhor ilumina-me as trevas.

[[v10-22-30]]

^<<v10-22-30,30>>^ Contigo posso avançar contra uma tropa; com o meu Deus posso transpor muralhas.

[[v10-22-31]]

^<<v10-22-31,31>>^ "Este é o Deus cujo caminho é perfeito; a palavra do Senhor é comprovadamente genuína. Ele é escudo para todos os que nele se refugiam.

[[v10-22-32]]

^<<v10-22-32,32>>^ Pois quem é Deus além do Senhor? E quem é Rocha senão o nosso Deus?

[[v10-22-33]]

^<<v10-22-33,33>>^ É Deus quem me reveste de força e torna perfeito o meu caminho.

[[v10-22-34]]

^<<v10-22-34,34>>^ Ele me faz correr veloz como a gazela e me firma os passos nos lugares altos.

[[v10-22-35]]

^<<v10-22-35,35>>^ É ele que treina as minhas mãos para a batalha, e assim os meus braços vergam o arco de bronze.

[[v10-22-36]]

^<<v10-22-36,36>>^ Tu me dás o teu escudo de livramento; a tua ajuda me fez forte.

[[v10-22-37]]

^<<v10-22-37,37>>^ Alargas sob mim o meu caminho, para que os meus tornozelos não se torçam.

[[v10-22-38]]

^<<v10-22-38,38>>^ "Persegui os meus inimigos e os derrotei; não voltei enquanto não foram destruídos.

[[v10-22-39]]

^<<v10-22-39,39>>^ Esmaguei-os completamente, e não puderam levantar-se; caíram debaixo dos meus pés.

[[v10-22-40]]

^<<v10-22-40,40>>^ Tu me revestiste de força para a batalha; fizeste cair aos meus pés os meus adversários.

[[v10-22-41]]

^<<v10-22-41,41>>^ Fizeste que os meus inimigos fugissem de mim; destruí os que me odiavam.

[[v10-22-42]]

^<<v10-22-42,42>>^ Gritaram por socorro, mas não havia quem os salvasse; gritaram ao Senhor, mas ele não respondeu.

[[v10-22-43]]

^<<v10-22-43,43>>^ Eu os reduzi a pó, como o pó da terra; esmaguei-os e os amassei como a lama das ruas.

[[v10-22-44]]

^<<v10-22-44,44>>^ "Tu me livraste dos ataques do meu povo; preservaste-me como líder de nações. Um povo que eu não conhecia me é sujeito.

[[v10-22-45]]

^<<v10-22-45,45>>^ Estrangeiros me bajulam; assim que me ouvem, me obedecem.

[[v10-22-46]]

^<<v10-22-46,46>>^ Todos eles perdem a coragem; saem tremendo das suas fortalezas.

[[v10-22-47]]

^<<v10-22-47,47>>^ "O Senhor vive! Bendita seja a minha Rocha! Exaltado seja Deus, a Rocha que me salva!

[[v10-22-48]]

^<<v10-22-48,48>>^ Este é o Deus que em meu favor executa vingança, que sujeita nações ao meu poder;

[[v10-22-49]]

^<<v10-22-49,49>>^ que me livrou dos meus inimigos. Tu me exaltaste acima dos meus agressores; de homens violentos me libertaste.

[[v10-22-50]]

^<<v10-22-50,50>>^ Por isso te louvarei entre as nações, ó Senhor; cantarei louvores ao teu nome.

[[v10-22-51]]

^<<v10-22-51,51>>^ Ele concede grandes vitórias ao seu rei; é bondoso com o seu ungido, Davi e seus descendentes para sempre".

'''

xref:010-2-samuel/010-2-samuel-021.adoc#v10-21-0[&#60; Capítulo Anterior] | <<v10-22-0,Topo>> | xref:010-2-samuel/010-2-samuel-023.adoc#v10-23-0[Próximo Capítulo &#62;]