include::./index.adoc[]

[[v10-15-0]]
=== 2 Samuel, 15
// nvi ?, NVI - Nova Versão Internacional

[[v10-15-1]]

^<<v10-15-1,1>>^ Algum tempo depois, Absalão adquiriu uma carruagem, cavalos e uma escolta de cinqüenta homens.

[[v10-15-2]]

^<<v10-15-2,2>>^ Ele se levantava cedo e ficava junto ao caminho que levava à porta da cidade. Sempre que alguém trazia uma causa para ser decidida pelo rei, Absalão o chamava e perguntava de que cidade vinha. A pessoa respondia que era de uma das tribos de Israel,

[[v10-15-3]]

^<<v10-15-3,3>>^ e Absalão dizia: "A sua causa é válida e legítima, mas não há nenhum representante do rei para ouvi-lo".

[[v10-15-4]]

^<<v10-15-4,4>>^ E Absalão acrescentava: "Quem me dera ser designado juiz desta terra! Todos os que tivessem uma causa ou uma questão legal viriam a mim, e eu lhe faria justiça".

[[v10-15-5]]

^<<v10-15-5,5>>^ E sempre que alguém se aproximava dele para prostrar-se em sinal de respeito, Absalão estendia a mão, abraçava-o e beijava-o.

[[v10-15-6]]

^<<v10-15-6,6>>^ Absalão agia assim com todos os israelitas que vinham pedir que o rei lhes fizesse justiça. Assim ele foi conquistando a lealdade dos homens de Israel.

[[v10-15-7]]

^<<v10-15-7,7>>^ Ao final de quatro anos, Absalão disse ao rei: "Deixa-me ir a Hebrom para cumprir um voto que fiz ao Senhor.

[[v10-15-8]]

^<<v10-15-8,8>>^ Quando o teu servo estava em Gesur, na Síria, fez este voto: Se o Senhor me permitir voltar a Jerusalém, prestarei culto a ele em Hebrom".

[[v10-15-9]]

^<<v10-15-9,9>>^ "Vá em paz! ", disse o rei. E ele foi para Hebrom.

[[v10-15-10]]

^<<v10-15-10,10>>^ Absalão enviou secretamente mensageiros a todas as tribos de Israel, dizendo: "Assim que vocês ouvirem o som das trombetas, digam: Absalão é rei em Hebrom".

[[v10-15-11]]

^<<v10-15-11,11>>^ Absalão levou duzentos homens de Jerusalém. Eles tinham sido convidados e nada sabiam nem suspeitavam do que estava acontecendo.

[[v10-15-12]]

^<<v10-15-12,12>>^ Depois de oferecer sacrifícios, Absalão mandou chamar da cidade de Gilo Aitofel, que era de Gilo, conselheiro de Davi. A conspiração ganhou força, e cresceu o número dos que seguiam Absalão.

[[v10-15-13]]

^<<v10-15-13,13>>^ Então um mensageiro chegou e disse a Davi: "Os israelitas estão com Absalão! "

[[v10-15-14]]

^<<v10-15-14,14>>^ Então Davi disse aos conselheiros que estavam com ele em Jerusalém: "Vamos fugir; caso contrário não escaparemos de Absalão. Se não partirmos imediatamente ele nos alcançará, causará a nossa ruína e matará o povo à espada".

[[v10-15-15]]

^<<v10-15-15,15>>^ Os conselheiros do rei lhe responderam: "Teus servos estão dispostos a fazer tudo o que o rei, nosso senhor, decidir".

[[v10-15-16]]

^<<v10-15-16,16>>^ O rei partiu, seguido por todos os de sua família; deixou, porém, dez concubinas para tomarem conta do palácio.

[[v10-15-17]]

^<<v10-15-17,17>>^ Assim, o rei partiu com todo o povo. Pararam na última casa da cidade,

[[v10-15-18]]

^<<v10-15-18,18>>^ e todos os seus soldados marcharam, passando por ele: todos os queretitas e peletitas, e os seiscentos giteus que o acompanhavam desde Gate.

[[v10-15-19]]

^<<v10-15-19,19>>^ O rei disse então a Itai, de Gate: "Por que você está indo conosco? Volte e fique com o novo rei, pois você é estrangeiro, um exilado de sua terra.

[[v10-15-20]]

^<<v10-15-20,20>>^ Faz pouco tempo que você chegou. Como eu poderia fazê-lo acompanhar-me? Volte e leve consigo os seus irmãos. Que o Senhor o trate com bondade e fidelidade! "

[[v10-15-21]]

^<<v10-15-21,21>>^ Itai, contudo, respondeu ao rei: "Juro pelo nome do Senhor e por tua vida que onde quer que o rei, meu senhor, esteja, ali estará o seu servo, para viver ou para morrer! "

[[v10-15-22]]

^<<v10-15-22,22>>^ Então Davi disse a Itai: "Está bem, pode ir adiante". E Itai, o giteu, marchou, com todos os seus soldados e com as famílias que estavam com ele.

[[v10-15-23]]

^<<v10-15-23,23>>^ Todo o povo do lugar chorava em alta voz enquanto o exército passava. O rei atravessou o vale do Cedrom e todo o povo foi com ele em direção ao deserto.

[[v10-15-24]]

^<<v10-15-24,24>>^ Zadoque também estava lá, e com ele todos os levitas que carregavam a arca da aliança de Deus; Abiatar também estava lá. Puseram no chão a arca de Deus até que todo o povo saísse da cidade.

[[v10-15-25]]

^<<v10-15-25,25>>^ Então o rei disse a Zadoque: "Leve a arca de Deus de volta para a cidade. Se o Senhor mostrar benevolência a mim, ele me trará de volta e me deixará ver a arca e o lugar onde ela deve permanecer.

[[v10-15-26]]

^<<v10-15-26,26>>^ Mas, se ele disser que já não sou do seu agrado, aqui estou! Faça ele comigo o que for de sua vontade".

[[v10-15-27]]

^<<v10-15-27,27>>^ Disse ainda o rei ao sacerdote Zadoque: "Fique alerta! Volte em paz para a cidade, você, Aimaás, seu filho, e Jônatas, filho de Abiatar.

[[v10-15-28]]

^<<v10-15-28,28>>^ Junto às torrentes do deserto ficarei esperando notícias de vocês".

[[v10-15-29]]

^<<v10-15-29,29>>^ Então Zadoque e Abiatar levaram a arca de Deus de volta para Jerusalém, e lá permaneceram.

[[v10-15-30]]

^<<v10-15-30,30>>^ Davi, porém, continuou subindo o monte das Oliveiras, caminhando e chorando, e com a cabeça coberta e os pés descalços. E todos os que iam com ele também tinham a cabeça coberta e subiam chorando.

[[v10-15-31]]

^<<v10-15-31,31>>^ Quando informaram a Davi que Aitofel era um dos conspiradores que apoiavam Absalão, Davi orou: "Ó Senhor, transforma em loucura os conselhos de Aitofel".

[[v10-15-32]]

^<<v10-15-32,32>>^ Quando Davi chegou ao alto do monte, ao lugar onde o povo costumava adorar a Deus, veio ao seu encontro o arquita Husai, com a roupa rasgada e com terra sobre a cabeça.

[[v10-15-33]]

^<<v10-15-33,33>>^ E Davi lhe disse: "Não adianta você vir comigo.

[[v10-15-34]]

^<<v10-15-34,34>>^ Mas se voltar à cidade, poderá dizer a Absalão: ‘Estarei a teu serviço, ó rei. No passado estive a serviço de teu pai, mas agora estarei a teu serviço’. Assim você me ajudará, frustrando o conselho de Aitofel.

[[v10-15-35]]

^<<v10-15-35,35>>^ Os sacerdotes Zadoque e Abiatar estarão lá com você. Informe-os do que você souber no palácio.

[[v10-15-36]]

^<<v10-15-36,36>>^ Também estão lá os dois filhos deles: Aimaás e Jônatas. Por meio deles me informe de tudo que você ouvir".

[[v10-15-37]]

^<<v10-15-37,37>>^ Então Husai, amigo de Davi, chegou a Jerusalém quando Absalão estava entrando na cidade.

'''

xref:010-2-samuel/010-2-samuel-014.adoc#v10-14-0[&#60; Capítulo Anterior] | <<v10-15-0,Topo>> | xref:010-2-samuel/010-2-samuel-016.adoc#v10-16-0[Próximo Capítulo &#62;]