include::./index.adoc[]

[[v10-14-0]]
=== 2 Samuel, 14
// nvi ?, NVI - Nova Versão Internacional

[[v10-14-1]]

^<<v10-14-1,1>>^ Joabe, filho de Zeruia, percebeu que o rei estava com saudade de Absalão,

[[v10-14-2]]

^<<v10-14-2,2>>^ então mandou buscar uma mulher astuta em Tecoa, e lhe disse: "Finja que está de luto: Vista-se de preto e não se perfume. Aja como uma mulher que há algum tempo está de luto.

[[v10-14-3]]

^<<v10-14-3,3>>^ Vá dizer ao rei estas palavras", e a instruiu sobre o que ela deveria dizer.

[[v10-14-4]]

^<<v10-14-4,4>>^ Quando a mulher apresentou-se ao rei, prostrou-se, rosto em terra, em sinal de respeito, e lhe disse: "Ajuda-me, ó rei! "

[[v10-14-5]]

^<<v10-14-5,5>>^ "Qual é o seu problema? ", perguntou-lhe o rei, e ela respondeu: "Sou viúva, meu marido morreu

[[v10-14-6]]

^<<v10-14-6,6>>^ deixando-me com dois filhos. Eles brigaram no campo e, não havendo ninguém para separá-los, um acabou matando o outro.

[[v10-14-7]]

^<<v10-14-7,7>>^ Agora, todo o clã levantou-se contra a tua serva, exigindo: ‘Entregue o assassino, para que o matemos pela vida do irmão, e nos livremos também do herdeiro’. Assim eles querem apagar a última centelha que me restou, deixando meu marido sem nome nem descendência na face da terra".

[[v10-14-8]]

^<<v10-14-8,8>>^ O rei disse à mulher: "Vá para casa. Eu mandarei que cuidem do seu caso".

[[v10-14-9]]

^<<v10-14-9,9>>^ Mas a mulher de Tecoa lhe disse: "Ó rei, meu senhor, é sobre mim e sobre a família de meu pai que pesará a iniqüidade; não pesa culpa sobre o rei e sobre o seu trono".

[[v10-14-10]]

^<<v10-14-10,10>>^ O rei respondeu: "Se alguém ameaçá-la, traga-o a mim, e ele não mais a incomodará".

[[v10-14-11]]

^<<v10-14-11,11>>^ Ela acrescentou: "Peço então ao rei que, em nome do Senhor, o seu Deus, não permita que o vingador da vítima cause maior destruição, matando meu outro filho". E disse ele: "Eu juro pelo nome do Senhor, que nem um só fio de cabelo da cabeça de seu filho cairá".

[[v10-14-12]]

^<<v10-14-12,12>>^ Disse-lhe ainda a mulher: "Permite que a tua serva fale mais uma coisa ao rei meu senhor". "Fale", respondeu ele.

[[v10-14-13]]

^<<v10-14-13,13>>^ Disse então a mulher: "Por que terá o rei agido contra o povo de Deus? O rei está se condenando com o que acaba de dizer, pois não permitiu a volta do que foi banido.

[[v10-14-14]]

^<<v10-14-14,14>>^ Que teremos que morrer um dia, é tão certo como não se pode recolher a água que se espalhou pela terra. Mas Deus não tira a vida; pelo contrário, cria meios para que o banido não permaneça afastado dele.

[[v10-14-15]]

^<<v10-14-15,15>>^ "E eu vim falar sobre isso ao rei, meu senhor, porque o povo me ameaçou. Tua serva pensou que se falasse com o rei, talvez ele atendesse o seu pedido,

[[v10-14-16]]

^<<v10-14-16,16>>^ e concordasse em livrar a sua serva das mãos do homem que está tentando eliminar tanto a mim como a meu filho da herança que Deus nos deu.

[[v10-14-17]]

^<<v10-14-17,17>>^ "E agora a tua serva diz: Traga-me descanso a decisão do rei, o meu senhor, pois o rei, meu senhor, é como um anjo de Deus, capaz de discernir entre o bem e o mal. Que o Senhor teu Deus esteja contigo! "

[[v10-14-18]]

^<<v10-14-18,18>>^ Então o rei disse à mulher: "Não me esconda nada do que vou lhe perguntar". "Fale o rei, meu senhor", disse a mulher.

[[v10-14-19]]

^<<v10-14-19,19>>^ O rei perguntou: "Não é Joabe que está por trás de tudo isso? " A mulher respondeu: "Juro por tua vida, ó rei, ninguém é capaz de desviar-se para a direita ou para a esquerda do que tu dizes. Sim, foi o teu servo Joabe quem me mandou aqui para dizer tudo isso.

[[v10-14-20]]

^<<v10-14-20,20>>^ O teu servo Joabe agiu assim para mudar essa situação. Mas o meu senhor é sábio como um anjo de Deus, e nada lhe escapa de tudo o que acontece em seu país".

[[v10-14-21]]

^<<v10-14-21,21>>^ Depois o rei disse a Joabe: "Muito bem, atenderei esse pedido. Vá e traga de volta o jovem Absalão".

[[v10-14-22]]

^<<v10-14-22,22>>^ Joabe prostrou-se, rosto em terra, abençoou o rei e disse: "Hoje o teu servo ficou sabendo que o vês com bons olhos, pois o rei atendeu o pedido de seu servo".

[[v10-14-23]]

^<<v10-14-23,23>>^ Então Joabe foi a Gesur e trouxe Absalão de volta para Jerusalém.

[[v10-14-24]]

^<<v10-14-24,24>>^ Mas o rei disse: "Ele irá para a casa dele; não virá à minha presença". Assim, Absalão foi para a sua casa e não compareceu mais à presença do rei.

[[v10-14-25]]

^<<v10-14-25,25>>^ Em todo o Israel não havia homem tão elogiado por sua beleza como Absalão. Da cabeça aos pés não havia nele nenhum defeito.

[[v10-14-26]]

^<<v10-14-26,26>>^ Sempre que o cabelo lhe ficava pesado demais, ele o cortava e o pesava: eram dois quilos e quatrocentos gramas, segundo o padrão do rei.

[[v10-14-27]]

^<<v10-14-27,27>>^ Ele teve três filhos e uma filha, chamada Tamar, que se tornou uma linda mulher.

[[v10-14-28]]

^<<v10-14-28,28>>^ Absalão morou dois anos em Jerusalém sem ser recebido pelo rei.

[[v10-14-29]]

^<<v10-14-29,29>>^ Então mandou chamar Joabe para enviá-lo ao rei, mas Joabe não quis ir. Mandou chamá-lo pela segunda vez, mas ele, novamente, não quis ir.

[[v10-14-30]]

^<<v10-14-30,30>>^ Então Absalão disse a seus servos: "Vejam, a propriedade de Joabe é vizinha da minha, e ele tem uma plantação de cevada. Tratem de incendiá-la". E os servos de Absalão puseram fogo na plantação.

[[v10-14-31]]

^<<v10-14-31,31>>^ Então Joabe foi à casa de Absalão e lhe perguntou: "Porque os seus servos puseram fogo na minha propriedade? "

[[v10-14-32]]

^<<v10-14-32,32>>^ Absalão respondeu: "Mandei chamá-lo para enviá-lo ao rei com a seguinte mensagem: ‘Por que voltei de Gesur? Melhor seria que eu lá permanecesse! ’ Quero ser recebido pelo rei; e, se eu for culpado de alguma coisa, que ele mande me matar".

[[v10-14-33]]

^<<v10-14-33,33>>^ Então Joabe foi contar tudo ao rei. Este mandou chamar Absalão, que entrou e prostrou-se, rosto em terra, perante o rei. E o rei saudou-o com um beijo.

'''

xref:010-2-samuel/010-2-samuel-013.adoc#v10-13-0[&#60; Capítulo Anterior] | <<v10-14-0,Topo>> | xref:010-2-samuel/010-2-samuel-015.adoc#v10-15-0[Próximo Capítulo &#62;]