include::./index.adoc[]

[[v30-6-0]]
=== Amós, 6
// nvi ?, NVI - Nova Versão Internacional

[[v30-6-1]]

^<<v30-6-1,1>>^ Ai de vocês que vivem tranqüilos em Sião, e que se sentem seguros no monte de Samaria; vocês, homens notáveis da primeira entre as nações, aos quais o povo de Israel recorre!

[[v30-6-2]]

^<<v30-6-2,2>>^ Vão a Calné e olhem para ela; depois prossigam até a grande Hamate e em seguida desçam até Gate, na Filístia. São elas melhores do que os seus dois reinos? O território delas é maior do que o de vocês?

[[v30-6-3]]

^<<v30-6-3,3>>^ Vocês acham que estão afastando o dia mau mas na verdade estão atraindo o reinado do terror.

[[v30-6-4]]

^<<v30-6-4,4>>^ Vocês se deitam em camas de marfim e se espreguiçam em seus sofás. Comem os melhores cordeiros e os novilhos mais gordos.

[[v30-6-5]]

^<<v30-6-5,5>>^ Dedilham em suas liras como Davi e improvisam em instrumentos musicais.

[[v30-6-6]]

^<<v30-6-6,6>>^ Vocês bebem vinho em grandes taças e se ungem com os mais finos óleos, mas não se entristecem com a ruína de José.

[[v30-6-7]]

^<<v30-6-7,7>>^ Por isso vocês estarão entre os primeiros a ir para o exílio; cessarão os banquetes dos que vivem no ócio.

[[v30-6-8]]

^<<v30-6-8,8>>^ O SENHOR Soberano jurou por si mesmo! Assim declara o SENHOR, o Deus dos Exércitos: "Eu detesto o orgulho de Jacó e odeio os seus palácios; entregarei a cidade e tudo que nela existe".

[[v30-6-9]]

^<<v30-6-9,9>>^ Se dez homens forem deixados numa casa, também eles morrerão.

[[v30-6-10]]

^<<v30-6-10,10>>^ E se um parente que tiver que queimar os corpos vier para tirá-los da casa e perguntar a alguém que ainda estiver escondido ali: "Há mais alguém com você? ", e a resposta for: "Não", ele dirá: "Calado! Não devemos sequer mencionar o nome do SENHOR".

[[v30-6-11]]

^<<v30-6-11,11>>^ Pois o SENHOR deu a ordem, e ele despedaçará a casa grande e fará em pedacinhos a casa pequena.

[[v30-6-12]]

^<<v30-6-12,12>>^ Acaso correm os cavalos sobre os rochedos? Poderá alguém ará-los com bois? Mas vocês transformaram o direito em veneno, e o fruto da justiça em amargura;

[[v30-6-13]]

^<<v30-6-13,13>>^ vocês que se regozijam pela conquista de Lo-Debara e dizem: "Acaso não conquistamos Carnaimb com a nossa própria força? "

[[v30-6-14]]

^<<v30-6-14,14>>^ Palavra do SENHOR, o Deus dos Exércitos: "Farei vir uma nação contra você, ó nação de Israel, e ela a oprimirá desde Lebo-Hamate até o vale da Arabá".

'''

xref:030-amos/030-amos-005.adoc#v30-5-0[&#60; Capítulo Anterior] | <<v30-6-0,Topo>> | xref:030-amos/030-amos-007.adoc#v30-7-0[Próximo Capítulo &#62;]