include::./index.adoc[]

[[v30-7-0]]
=== Amós, 7
// nvi ?, NVI - Nova Versão Internacional

[[v30-7-1]]

^<<v30-7-1,1>>^ Foi isto que o SENHOR, o Soberano, me mostrou: ele estava preparando enxames de gafanhotos depois da colheita do rei, justo quando brotava a segunda safra.

[[v30-7-2]]

^<<v30-7-2,2>>^ Depois que eles devoraram todas as plantas dos campos, eu clamei: "SENHOR Soberano, perdoa! Como Jacó poderá sobreviver? Ele é tão pequeno! "

[[v30-7-3]]

^<<v30-7-3,3>>^ Então o SENHOR arrependeu-se e declarou: "Isso não acontecerá".

[[v30-7-4]]

^<<v30-7-4,4>>^ O Soberano, o SENHOR, mostrou-me também que, para o julgamento, estava chamando o fogo, o qual secou o grande abismo e devorou a terra.

[[v30-7-5]]

^<<v30-7-5,5>>^ Então eu clamei: "Soberano SENHOR, eu te imploro que pares! Como Jacó poderá sobreviver? Ele é tão pequeno! "

[[v30-7-6]]

^<<v30-7-6,6>>^ Então o SENHOR arrependeu-se e declarou: "Isso também não acontecerá".

[[v30-7-7]]

^<<v30-7-7,7>>^ Ele me mostrou ainda isto: o Senhor, com um prumo na mão, estava junto a um muro construído no rigor do prumo.

[[v30-7-8]]

^<<v30-7-8,8>>^ E o SENHOR me perguntou: "O que você está vendo, Amós? " "Um prumo", respondi. Então disse o Senhor: "Veja! Estou pondo um prumo no meio de Israel, o meu povo; não vou poupá-lo mais.

[[v30-7-9]]

^<<v30-7-9,9>>^ "Os altares idólatras de Isaque serão destruídos, e os santuários de Israel ficarão em ruínas; com a espada me levantarei contra a dinastia de Jeroboão".

[[v30-7-10]]

^<<v30-7-10,10>>^ Então o sacerdote de Betel, Amazias, enviou esta mensagem a Jeroboão, rei de Israel: "Amós está tramando uma conspiração contra ti no centro de Israel. A nação não suportará as suas palavras.

[[v30-7-11]]

^<<v30-7-11,11>>^ Amós está dizendo o seguinte: ‘Jeroboão morrerá à espada, e certamente Israel irá para o exílio, para longe da sua terra natal’ ".

[[v30-7-12]]

^<<v30-7-12,12>>^ Depois Amazias disse a Amós: "Vá embora, vidente! Vá profetizar em Judá; vá ganhar lá o seu pão.

[[v30-7-13]]

^<<v30-7-13,13>>^ Não profetize mais em Betel, porque este é o santuário do rei e o templo do reino".

[[v30-7-14]]

^<<v30-7-14,14>>^ Amós respondeu a Amazias: "Eu não sou profeta nem pertenço a nenhum grupo de profetasc, apenas cuido do gado e faço colheita de figos silvestres.

[[v30-7-15]]

^<<v30-7-15,15>>^ Mas o SENHOR me tirou do serviço junto ao rebanho e me disse: ‘Vá, profetize a Israel, o meu povo’.

[[v30-7-16]]

^<<v30-7-16,16>>^ Agora ouça, então, a palavra do SENHOR. Você diz: " ‘Não profetize contra Israel, e pare de pregar contra a descendência de Isaque’.

[[v30-7-17]]

^<<v30-7-17,17>>^ "Mas, o SENHOR lhe diz: " ‘Sua mulher se tornará uma prostituta na cidade, e os seus filhos e as suas filhas morrerão à espada. Suas terras serão loteadas, e você mesmo morrerá numa terra pagãa. E Israel certamente irá para o exílio, para longe da sua terra natal’ ".

'''

xref:030-amos/030-amos-006.adoc#v30-6-0[&#60; Capítulo Anterior] | <<v30-7-0,Topo>> | xref:030-amos/030-amos-008.adoc#v30-8-0[Próximo Capítulo &#62;]