include::./index.adoc[]

[[v30-1-0]]
=== Amós, 1
// nvi ?, NVI - Nova Versão Internacional

[[v30-1-1]]

^<<v30-1-1,1>>^ Palavras que Amós, criador de ovelhas em Tecoa, recebeu em visões, a respeito de Israel dois anos antes do terremoto. Nesse tempo, Uzias era rei de Judá e Jeroboão, filho de Jeoás, era rei de Israel.

[[v30-1-2]]

^<<v30-1-2,2>>^ Ele disse: "O SENHOR ruge de Sião e troveja de Jerusalém; secam-se as pastagens dos pastores, e murcha o topo do Carmelo".

[[v30-1-3]]

^<<v30-1-3,3>>^ Assim diz o SENHOR: "Por três transgressões de Damasco e ainda mais por quatro, não anularei o castigo. Porque trilhou Gileade com trilhos de ferro pontudos,

[[v30-1-4]]

^<<v30-1-4,4>>^ porei fogo na casa de Hazael que consumirá as fortalezas de Ben-Hadade.

[[v30-1-5]]

^<<v30-1-5,5>>^ Derrubarei a porta de Damasco; destruirei o rei que está no vale de Áven e aquele que segura o cetro em Bete-Éden. O povo da Síria irá para o exílio em Quir", diz o SENHOR.

[[v30-1-6]]

^<<v30-1-6,6>>^ Assim diz o SENHOR: "Por três transgressões de Gaza, e ainda mais por quatro, não anularei o castigo. Porque levou cativas comunidades inteiras e as vendeu a Edom,

[[v30-1-7]]

^<<v30-1-7,7>>^ porei fogo nos muros de Gaza, que consumirá as suas fortalezas.

[[v30-1-8]]

^<<v30-1-8,8>>^ Destruirei o rei de Asdode e aquele que segura o cetro em Ascalom. Erguerei a minha mão contra Ecrom, até que morra o último dos filisteus", diz o SENHOR Soberano.

[[v30-1-9]]

^<<v30-1-9,9>>^ Assim diz o SENHOR: "Por três transgressões de Tiro, e ainda mais por quatro, não anularei o castigo. Porque vendeu comunidades inteiras de cativos a Edom, desprezando irmãos,

[[v30-1-10]]

^<<v30-1-10,10>>^ porei fogo nos muros de Tiro, que consumirá as suas fortalezas".

[[v30-1-11]]

^<<v30-1-11,11>>^ Assim diz o SENHOR: "Por três transgressões de Edom, e ainda mais por quatro, não anularei o castigo. Porque com a espada perseguiu seu irmão, e reprimiu toda a compaixão, mutilando-o furiosamente e perpetuando para sempre a sua ira,

[[v30-1-12]]

^<<v30-1-12,12>>^ porei fogo em Temã, que consumirá as fortalezas de Bozra".

[[v30-1-13]]

^<<v30-1-13,13>>^ Assim diz o SENHOR: "Por três transgressões de Amom, e ainda mais por quatro, não anularei o castigo. Porque rasgou ao meio as grávidas de Gileade a fim de ampliar as suas fronteiras,

[[v30-1-14]]

^<<v30-1-14,14>>^ porei fogo nos muros de Rabá, que consumirá as suas fortalezas em meio a gritos de guerra no dia do combate, em meio a ventos violentos num dia de tempestade.

[[v30-1-15]]

^<<v30-1-15,15>>^ O seu rei irá para o exílio, ele e toda a sua corte", diz o SENHOR.

'''

xref:029-joel/029-joel-003.adoc#v29-3-0[&#60; Capítulo Anterior] | <<v30-1-0,Topo>> | xref:030-amos/030-amos-002.adoc#v30-2-0[Próximo Capítulo &#62;]