include::./index.adoc[]

[[v30-3-0]]
=== Amós, 3
// nvi ?, NVI - Nova Versão Internacional

[[v30-3-1]]

^<<v30-3-1,1>>^ Ouçam esta palavra que o SENHOR falou contra vocês, ó israelitas; contra toda esta família que tirei do Egito:

[[v30-3-2]]

^<<v30-3-2,2>>^ "Escolhi apenas vocês de todas as famílias da terra; por isso eu os castigarei por causa de todas as suas maldades".

[[v30-3-3]]

^<<v30-3-3,3>>^ Duas pessoas andarão juntas se não tiverem de acordo?

[[v30-3-4]]

^<<v30-3-4,4>>^ O leão ruge na floresta se não apanhou presa alguma? O leão novo ruge em sua toca se nada caçou?

[[v30-3-5]]

^<<v30-3-5,5>>^ Cai o pássaro num laço se não há nenhuma armadilha? Será que a armadilha do laço se desarma se nada foi apanhado?

[[v30-3-6]]

^<<v30-3-6,6>>^ Quando a trombeta toca na cidade, o povo não treme? Ocorre alguma desgraça na cidade, sem que o SENHOR a tenha mandado?

[[v30-3-7]]

^<<v30-3-7,7>>^ Certamente o SENHOR Soberano não faz coisa alguma sem revelar o seu plano aos seus servos, os profetas.

[[v30-3-8]]

^<<v30-3-8,8>>^ O leão rugiu, quem não temerá? O SENHOR Soberano falou, quem não profetizará?

[[v30-3-9]]

^<<v30-3-9,9>>^ Proclamem os palácios de Asdode e do Egito: "Reúnam-se nos montes de Samaria para verem o grande tumulto que há ali e a opressão no meio do seu povo".

[[v30-3-10]]

^<<v30-3-10,10>>^ "Eles não sabem como agir direito", declara o SENHOR, "eles, que acumulam em seus palácios o que roubaram e saquearam".

[[v30-3-11]]

^<<v30-3-11,11>>^ Portanto, assim diz o SENHOR Soberano: "Um inimigo está cercando o país. Ele derrubará as suas fortalezas e saqueará os seus palácios".

[[v30-3-12]]

^<<v30-3-12,12>>^ Assim diz o SENHOR: "Assim como o pastor arranca da boca do leão só dois ossos da perna ou um pedaço da orelha, assim serão arrancados os israelitas de Samaria, com um canto de cama e um pedaço de sofá.

[[v30-3-13]]

^<<v30-3-13,13>>^ "Ouçam isto e testemunhem contra a descendência de Jacó", declara o SENHOR Soberano, o Deus dos Exércitos.

[[v30-3-14]]

^<<v30-3-14,14>>^ "No dia em que eu castigar Israel por causa dos seus pecados, destruirei os altares de Betel; as pontas do altar serão cortadas e cairão no chão.

[[v30-3-15]]

^<<v30-3-15,15>>^ Derrubarei a casa de inverno junto com a casa de verão; as casas enfeitadas de marfim serão destruídas, e as mansões desaparecerão", declara o SENHOR.

'''

xref:030-amos/030-amos-002.adoc#v30-2-0[&#60; Capítulo Anterior] | <<v30-3-0,Topo>> | xref:030-amos/030-amos-004.adoc#v30-4-0[Próximo Capítulo &#62;]