include::./index.adoc[]

[[v30-9-0]]
=== Amós, 9
// nvi ?, NVI - Nova Versão Internacional

[[v30-9-1]]

^<<v30-9-1,1>>^ Vi o Senhor junto ao altar, e ele disse: "Bata no topo das colunas para que tremam os umbrais. Faça que elas caiam sobre todos os presentes; e os que sobrarem matarei à espada. Ninguém fugirá, ninguém escapará.

[[v30-9-2]]

^<<v30-9-2,2>>^ Ainda que escavem até às profundezas, dali a minha mão irá tirá-los. Se subirem até os céus, de lá os farei descer.

[[v30-9-3]]

^<<v30-9-3,3>>^ Mesmo que se escondam no topo do Carmelo, lá os caçarei e os prenderei. Ainda que se escondam de mim no fundo do mar, ali ordenarei à serpente que os morda.

[[v30-9-4]]

^<<v30-9-4,4>>^ Mesmo que sejam levados ao exílio por seus inimigos, ali ordenarei que a espada os mate. Vou vigiá-los para lhes fazer o mal e não o bem".

[[v30-9-5]]

^<<v30-9-5,5>>^ Quanto ao Senhor, o SENHOR dos Exércitos, ele toca na terra, e ela se derrete, e todos os que nela vivem pranteiam; ele ergue toda a terra como o Nilo, e depois a afunda como o ribeiro do Egito.

[[v30-9-6]]

^<<v30-9-6,6>>^ Ele constrói suas câmaras altas, e firma a abóbada sobre a terra; ele reúne as águas do mar e as espalha sobre a superfície da terra. SENHOR é o seu nome.

[[v30-9-7]]

^<<v30-9-7,7>>^ "Vocês, israelitas, não são para mim melhores do que os etíopes", declara o SENHOR. "Eu tirei Israel do Egito, os filisteus de Caftor e os arameus de Quir.

[[v30-9-8]]

^<<v30-9-8,8>>^ "Sem dúvida, os olhos do SENHOR, o Soberano, se voltam para este reino pecaminoso. Eu o varrerei da superfície da terra, mas não destruirei totalmente a descendência de Jacó", declara o SENHOR.

[[v30-9-9]]

^<<v30-9-9,9>>^ "Pois darei a ordem, e sacudirei a nação de Israel entre todas as nações, tal como o trigo é abanado numa peneira, e nem um grão cai na terra.

[[v30-9-10]]

^<<v30-9-10,10>>^ Todos os pecadores que há no meio do meu povo morrerão à espada, todos os que dizem: ‘A desgraça não nos atingirá nem nos encontrará’.

[[v30-9-11]]

^<<v30-9-11,11>>^ "Naquele dia levantarei a tenda caída de Davi. Consertarei o que estiver quebrado, e restaurarei as suas ruínas. Eu a reerguerei, para que seja como era no passado,

[[v30-9-12]]

^<<v30-9-12,12>>^ para que o meu povo conquiste o remanescente de Edom e todas as nações que me pertencem", declara o SENHOR, que realizará essas coisas.

[[v30-9-13]]

^<<v30-9-13,13>>^ "Dias virão", declara o SENHOR, "em que a ceifa continuará até o tempo de arar, e o pisar das uvas até o tempo de semear. Vinho novo gotejará dos montes e fluirá de todas as colinas.

[[v30-9-14]]

^<<v30-9-14,14>>^ Trarei de volta Israel, o meu povo exilado, eles reconstruirão as cidades em ruínas e nelas viverão. Plantarão vinhas e beberão do seu vinho; cultivarão pomares e comerão do seu fruto.

[[v30-9-15]]

^<<v30-9-15,15>>^ Plantarei Israel em sua própria terra, para nunca mais ser desarraigado da terra que lhe dei", diz o SENHOR, o seu Deus.

'''

xref:030-amos/030-amos-008.adoc#v30-8-0[&#60; Capítulo Anterior] | <<v30-9-0,Topo>> | xref:031-obadias/031-obadias-001.adoc#v31-1-0[Próximo Capítulo &#62;]