include::./index.adoc[]

[[v66-20-0]]
=== Apocalipse, 20
// nvi ?, NVI - Nova Versão Internacional

[[v66-20-1]]

^<<v66-20-1,1>>^ Vi descer do céu um anjo que trazia na mão a chave do abismo e uma grande corrente.

[[v66-20-2]]

^<<v66-20-2,2>>^ Ele prendeu o dragão, a antiga serpente, que é o diabo, Satanás, e o acorrentou por mil anos;

[[v66-20-3]]

^<<v66-20-3,3>>^ lançou-o no abismo, fechou-o e pôs um selo sobre ele, para assim impedi-lo de enganar as nações até que terminassem os mil anos. Depois disso, é necessário que ele seja solto por um pouco de tempo.

[[v66-20-4]]

^<<v66-20-4,4>>^ Vi tronos em que se assentaram aqueles a quem havia sido dada autoridade para julgar. Vi as almas dos que foram decapitados por causa do testemunho de Jesus e da palavra de Deus. Eles não tinham adorado a besta nem a sua imagem, e não tinham recebido a sua marca na testa nem nas mãos. Eles ressuscitaram e reinaram com Cristo durante mil anos.

[[v66-20-5]]

^<<v66-20-5,5>>^ ( O restante dos mortos não voltou a viver até se completarem os mil anos. ) Esta é a primeira ressurreição.

[[v66-20-6]]

^<<v66-20-6,6>>^ Felizes e santos os que participam da primeira ressurreição! A segunda morte não tem poder sobre eles; serão sacerdotes de Deus e de Cristo, e reinarão com ele durante mil anos.

[[v66-20-7]]

^<<v66-20-7,7>>^ Quando terminarem os mil anos, Satanás será solto da sua prisão

[[v66-20-8]]

^<<v66-20-8,8>>^ e sairá para enganar as nações que estão nos quatro cantos da terra, Gogue e Magogue, a fim de reuni-las para a batalha. Seu número é como a areia do mar.

[[v66-20-9]]

^<<v66-20-9,9>>^ As nações marcharam por toda a superfície da terra e cercaram o acampamento dos santos, a cidade amada; mas um fogo desceu do céu e as devorou.

[[v66-20-10]]

^<<v66-20-10,10>>^ O diabo, que as enganava, foi lançado no lago de fogo que arde com enxofre, onde já haviam sido lançados a besta e o falso profeta. Eles serão atormentados dia e noite, para todo o sempre.

[[v66-20-11]]

^<<v66-20-11,11>>^ Depois vi um grande trono branco e aquele que nele estava assentado. A terra e o céu fugiram da sua presença, e não se encontrou lugar para eles.

[[v66-20-12]]

^<<v66-20-12,12>>^ Vi também os mortos, grandes e pequenos, de pé diante do trono, e livros foram abertos. Outro livro foi aberto, o livro da vida. Os mortos foram julgados de acordo com o que tinham feito, segundo o que estava registrado nos livros.

[[v66-20-13]]

^<<v66-20-13,13>>^ O mar entregou os mortos que nele havia, e a morte e o Hades entregaram os mortos que neles havia; e cada um foi julgado de acordo com o que tinha feito.

[[v66-20-14]]

^<<v66-20-14,14>>^ Então a morte e o Hades foram lançados no lago de fogo. O lago de fogo é a segunda morte.

[[v66-20-15]]

^<<v66-20-15,15>>^ Se o nome de alguém não foi encontrado no livro da vida, este foi lançado no lago de fogo.

'''

xref:066-apocalipse/066-apocalipse-019.adoc#v66-19-0[&#60; Capítulo Anterior] | <<v66-20-0,Topo>> | xref:066-apocalipse/066-apocalipse-021.adoc#v66-21-0[Próximo Capítulo &#62;]