include::./index.adoc[]

[[v66-6-0]]
=== Apocalipse, 6
// nvi ?, NVI - Nova Versão Internacional

[[v66-6-1]]

^<<v66-6-1,1>>^ Observei quando o Cordeiro abriu o primeiro dos sete selos. Então ouvi um dos seres viventes dizer com voz de trovão: "Venha! "

[[v66-6-2]]

^<<v66-6-2,2>>^ Olhei, e diante de mim estava um cavalo branco! Seu cavaleiro empunhava um arco, e foi-lhe dada uma coroa; ele cavalgava como vencedor determinado a vencer.

[[v66-6-3]]

^<<v66-6-3,3>>^ Quando o Cordeiro abriu o segundo selo, ouvi o segundo ser vivente dizer: "Venha! "

[[v66-6-4]]

^<<v66-6-4,4>>^ Então saiu outro cavalo; e este era vermelho. Seu cavaleiro recebeu poder para tirar a paz da terra e fazer que os homens se matassem uns aos outros. E lhe foi dada uma grande espada.

[[v66-6-5]]

^<<v66-6-5,5>>^ Quando o Cordeiro abriu o terceiro selo, ouvi o terceiro ser vivente dizer: "Venha! " Olhei, e diante de mim estava um cavalo preto. Seu cavaleiro tinha na mão uma balança.

[[v66-6-6]]

^<<v66-6-6,6>>^ Então ouvi o que parecia uma voz entre os quatro seres viventes, dizendo: "Um quilo de trigo por um denário, e três quilos de cevada por um denário, e não danifique o azeite e o vinho! "

[[v66-6-7]]

^<<v66-6-7,7>>^ Quando o Cordeiro abriu o quarto selo, ouvi a voz do quarto ser vivente dizer: "Venha! "

[[v66-6-8]]

^<<v66-6-8,8>>^ Olhei, e diante de mim estava um cavalo amarelo. Seu cavaleiro chamava-se Morte, e o Hades o seguia de perto. Foi-lhes dado poder sobre um quarto da terra para matar pela espada, pela fome, por pragas e por meio dos animais selvagens da terra.

[[v66-6-9]]

^<<v66-6-9,9>>^ Quando ele abriu o quinto selo, vi debaixo do altar as almas daqueles que haviam sido mortos por causa da palavra de Deus e do testemunho que deram.

[[v66-6-10]]

^<<v66-6-10,10>>^ Eles clamavam em alta voz: "Até quando, ó Soberano santo e verdadeiro, esperarás para julgar os habitantes da terra e vingar o nosso sangue? "

[[v66-6-11]]

^<<v66-6-11,11>>^ Então cada um deles recebeu uma veste branca, e foi-lhes dito que esperassem um pouco mais, até que se completasse o número dos seus conservos e irmãos, que deveriam ser mortos como eles.

[[v66-6-12]]

^<<v66-6-12,12>>^ Observei quando ele abriu o sexto selo. Houve um grande terremoto. O sol ficou escuro como tecido de crina negra, toda a lua tornou-se vermelha como sangue,

[[v66-6-13]]

^<<v66-6-13,13>>^ e as estrelas do céu caíram sobre a terra como figos verdes caem da figueira quando sacudidos por um vento forte.

[[v66-6-14]]

^<<v66-6-14,14>>^ O céu foi se recolhendo como se enrola um pergaminho, e todas as montanhas e ilhas foram removidas de seus lugares.

[[v66-6-15]]

^<<v66-6-15,15>>^ Então os reis da terra, os príncipes, os generais, os ricos, os poderosos — todos os homens, quer escravos, quer livres, esconderam-se em cavernas e entre as rochas das montanhas.

[[v66-6-16]]

^<<v66-6-16,16>>^ Eles gritavam às montanhas e às rochas: "Caiam sobre nós e escondam-nos da face daquele que está assentado no trono e da ira do Cordeiro!

[[v66-6-17]]

^<<v66-6-17,17>>^ Pois chegou o grande dia da ira deles; e quem poderá suportar? "

'''

xref:066-apocalipse/066-apocalipse-005.adoc#v66-5-0[&#60; Capítulo Anterior] | <<v66-6-0,Topo>> | xref:066-apocalipse/066-apocalipse-007.adoc#v66-7-0[Próximo Capítulo &#62;]