include::./index.adoc[]

[[v66-14-0]]
=== Apocalipse, 14
// nvi ?, NVI - Nova Versão Internacional

[[v66-14-1]]

^<<v66-14-1,1>>^ Então olhei, e diante de mim estava o Cordeiro, de pé sobre o monte Sião, e com ele cento e quarenta e quatro mil que traziam escritos na testa o nome dele e o nome de seu Pai.

[[v66-14-2]]

^<<v66-14-2,2>>^ Ouvi um som do céu como o de muitas águas e de um forte trovão. Era como o de harpistas tocando suas harpas.

[[v66-14-3]]

^<<v66-14-3,3>>^ Eles cantavam um cântico novo diante do trono, dos quatro seres viventes e dos anciãos. Ninguém podia aprender o cântico, a não ser os cento e quarenta e quatro mil que haviam sido comprados da terra.

[[v66-14-4]]

^<<v66-14-4,4>>^ Estes são os que não se contaminaram com mulheres, pois se conservaram castos e seguem o Cordeiro por onde quer que ele vá. Foram comprados dentre os homens e ofertados como primícias a Deus e ao Cordeiro.

[[v66-14-5]]

^<<v66-14-5,5>>^ Mentira nenhuma foi encontrada em suas bocas; são imaculados.

[[v66-14-6]]

^<<v66-14-6,6>>^ Então vi outro anjo, que voava pelo céu e tinha na mão o evangelho eterno para proclamar aos que habitam na terra, a toda nação, tribo, língua e povo.

[[v66-14-7]]

^<<v66-14-7,7>>^ Ele disse em alta voz: "Temam a Deus e glorifiquem-no, pois chegou a hora do seu juízo. Adorem aquele que fez os céus, a terra, o mar e as fontes das águas".

[[v66-14-8]]

^<<v66-14-8,8>>^ Um segundo anjo o seguiu, dizendo: "Caiu! Caiu a grande Babilônia que fez todas as nações beberem do vinho da fúria da sua prostituição! "

[[v66-14-9]]

^<<v66-14-9,9>>^ Um terceiro anjo os seguiu, dizendo em alta voz: "Se alguém adorar a besta e a sua imagem e receber a sua marca na testa ou na mão,

[[v66-14-10]]

^<<v66-14-10,10>>^ também beberá do vinho do furor de Deus que foi derramado sem mistura no cálice da sua ira. Será ainda atormentado com enxofre ardente na presença dos santos anjos e do Cordeiro,

[[v66-14-11]]

^<<v66-14-11,11>>^ e a fumaça do tormento de tais pessoas sobe para todo o sempre. Para todos os que adoram a besta e a sua imagem, e para quem recebe a marca do seu nome, não há descanso, dia e noite".

[[v66-14-12]]

^<<v66-14-12,12>>^ Aqui está a perseverança dos santos que obedecem aos mandamentos de Deus e permanecem fiéis a Jesus.

[[v66-14-13]]

^<<v66-14-13,13>>^ Então ouvi uma voz do céu dizendo: "Escreva: Felizes os mortos que morrem no Senhor de agora em diante". Diz o Espírito: "Sim, eles descansarão das suas fadigas, pois as suas obras os seguirão".

[[v66-14-14]]

^<<v66-14-14,14>>^ Olhei, e diante de mim estava uma nuvem branca e, assentado sobre a nuvem, alguém "semelhante a um filho de homem". Ele estava com uma coroa de ouro na cabeça e uma foice afiada na mão.

[[v66-14-15]]

^<<v66-14-15,15>>^ Então saiu do santuário um outro anjo, que bradou em alta voz àquele que estava assentado sobre a nuvem: "Tome a sua foice e faça a colheita, pois a safra da terra está madura; chegou a hora de colhê-la".

[[v66-14-16]]

^<<v66-14-16,16>>^ Assim, aquele que estava assentado sobre a nuvem passou sua foice pela terra, e a terra foi ceifada.

[[v66-14-17]]

^<<v66-14-17,17>>^ Outro anjo saiu do santuário do céu, trazendo também uma foice afiada.

[[v66-14-18]]

^<<v66-14-18,18>>^ E ainda outro anjo, que tem autoridade sobre o fogo, saiu do altar e bradou em alta voz àquele que tinha a foice afiada: "Tome sua foice afiada e ajunte os cachos de uva da videira da terra, porque as suas uvas estão maduras! "

[[v66-14-19]]

^<<v66-14-19,19>>^ O anjo passou a foice pela terra, ajuntou as uvas e as lançou no grande lagar da ira de Deus.

[[v66-14-20]]

^<<v66-14-20,20>>^ Elas foram pisadas no lagar, fora da cidade, e correu sangue do lagar, chegando ao nível dos freios dos cavalos, numa distância de cerca de trezentos quilômetros.

'''

xref:066-apocalipse/066-apocalipse-013.adoc#v66-13-0[&#60; Capítulo Anterior] | <<v66-14-0,Topo>> | xref:066-apocalipse/066-apocalipse-015.adoc#v66-15-0[Próximo Capítulo &#62;]