include::./index.adoc[]

[[v66-12-0]]
=== Apocalipse, 12
// nvi ?, NVI - Nova Versão Internacional

[[v66-12-1]]

^<<v66-12-1,1>>^ Apareceu no céu um sinal extraordinário: uma mulher vestida do sol, com a lua debaixo dos seus pés e uma coroa de doze estrelas sobre a cabeça.

[[v66-12-2]]

^<<v66-12-2,2>>^ Ela estava grávida e gritava de dor, pois estava para dar à luz.

[[v66-12-3]]

^<<v66-12-3,3>>^ Então apareceu no céu outro sinal: um enorme dragão vermelho com sete cabeças e dez chifres, tendo sobre as cabeças sete coroas.

[[v66-12-4]]

^<<v66-12-4,4>>^ Sua cauda arrastou consigo um terço das estrelas do céu, lançando-as na terra. O dragão colocou-se diante da mulher que estava para dar à luz, para devorar o seu filho no momento em que nascesse.

[[v66-12-5]]

^<<v66-12-5,5>>^ Ela deu à luz um filho, um homem, que governará todas as nações com cetro de ferro. Seu filho foi arrebatado para junto de Deus e de seu trono.

[[v66-12-6]]

^<<v66-12-6,6>>^ A mulher fugiu para o deserto, para um lugar que lhe havia sido preparado por Deus, para que ali a sustentassem durante mil duzentos e sessenta dias.

[[v66-12-7]]

^<<v66-12-7,7>>^ Houve então uma guerra no céu. Miguel e seus anjos lutaram contra o dragão, e o dragão e os seus anjos revidaram.

[[v66-12-8]]

^<<v66-12-8,8>>^ Mas estes não foram suficientemente fortes, e assim perderam o seu lugar no céu.

[[v66-12-9]]

^<<v66-12-9,9>>^ O grande dragão foi lançado fora. Ele é a antiga serpente chamada diabo ou Satanás, que engana o mundo todo. Ele e os seus anjos foram lançado à terra.

[[v66-12-10]]

^<<v66-12-10,10>>^ Então ouvi uma forte voz do céu que dizia: "Agora veio a salvação, o poder e o Reino do nosso Deus, e a autoridade do seu Cristo, pois foi lançado fora o acusador dos nossos irmãos, que os acusa diante do nosso Deus, dia e noite.

[[v66-12-11]]

^<<v66-12-11,11>>^ Eles o venceram pelo sangue do Cordeiro e pela palavra do testemunho que deram; diante da morte, não amaram a própria vida.

[[v66-12-12]]

^<<v66-12-12,12>>^ Portanto, celebrem, ó céus, e os que neles habitam! Mas, ai da terra e do mar, pois o diabo desceu até vocês! Ele está cheio de fúria, pois sabe que lhe resta pouco tempo".

[[v66-12-13]]

^<<v66-12-13,13>>^ Quando o dragão viu que havia sido lançado à terra, começou a perseguir a mulher que dera à luz o menino.

[[v66-12-14]]

^<<v66-12-14,14>>^ Foram dadas à mulher as duas asas da grande águia, para que ela pudesse voar para o lugar que lhe havia sido preparado no deserto, onde seria sustentada durante um tempo, tempos e meio tempo, fora do alcance da serpente.

[[v66-12-15]]

^<<v66-12-15,15>>^ Então a serpente fez jorrar da sua boca água como um rio, para alcançar a mulher e arrastá-la com a correnteza.

[[v66-12-16]]

^<<v66-12-16,16>>^ A terra, porém, ajudou a mulher, abrindo a boca e engolindo o rio que o dragão fizera jorrar da sua boca.

[[v66-12-17]]

^<<v66-12-17,17>>^ O dragão irou-se contra a mulher e saiu para guerrear contra o restante da sua descendência, os que obedecem aos mandamentos de Deus e se mantêm fiéis ao testemunho de Jesus.

[[v66-12-18]]

^<<v66-12-18,18>>^ Então o dragão se pôs em pé na areia do mar.

'''

xref:066-apocalipse/066-apocalipse-011.adoc#v66-11-0[&#60; Capítulo Anterior] | <<v66-12-0,Topo>> | xref:066-apocalipse/066-apocalipse-013.adoc#v66-13-0[Próximo Capítulo &#62;]