include::./index.adoc[]

[[v66-7-0]]
=== Apocalipse, 7
// nvi ?, NVI - Nova Versão Internacional

[[v66-7-1]]

^<<v66-7-1,1>>^ Depois disso vi quatro anjos de pé nos quatro cantos da terra, retendo os quatro ventos, para impedir que qualquer vento soprasse na terra, no mar ou em qualquer árvore.

[[v66-7-2]]

^<<v66-7-2,2>>^ Então vi outro anjo subindo do Oriente, tendo o selo do Deus vivo. Ele bradou em alta voz aos quatro anjos a quem havia sido dado poder para danificar a terra e o mar:

[[v66-7-3]]

^<<v66-7-3,3>>^ "Não danifiquem nem a terra, nem o mar nem as árvores, até que selemos as testas dos servos do nosso Deus".

[[v66-7-4]]

^<<v66-7-4,4>>^ Então ouvi o número dos que foram selados: cento e quarenta e quatro mil, de todas as tribos de Israel.

[[v66-7-5]]

^<<v66-7-5,5>>^ Da tribo de Judá foram selados doze mil, da tribo de Rúben, doze mil, da tribo de Gade, doze mil,

[[v66-7-6]]

^<<v66-7-6,6>>^ da tribo de Aser, doze mil, da tribo de Naftali, doze mil, da tribo de Manassés, doze mil,

[[v66-7-7]]

^<<v66-7-7,7>>^ da tribo de Simeão, doze mil, da tribo de Levi, doze mil, da tribo de Issacar, doze mil,

[[v66-7-8]]

^<<v66-7-8,8>>^ da tribo de Zebulom, doze mil, da tribo de José, doze mil, da tribo de Benjamim, doze mil.

[[v66-7-9]]

^<<v66-7-9,9>>^ Depois disso olhei, e diante de mim estava uma grande multidão que ninguém podia contar, de todas as nações, tribos, povos e línguas, de pé, diante do trono e do Cordeiro, com vestes brancas e segurando palmas.

[[v66-7-10]]

^<<v66-7-10,10>>^ E clamavam em alta voz: "A salvação pertence ao nosso Deus, que se assenta no trono, e ao Cordeiro".

[[v66-7-11]]

^<<v66-7-11,11>>^ Todos os anjos estavam de pé ao redor do trono, dos anciãos e dos quatro seres viventes. Eles se prostraram com o rosto em terra diante do trono e adoraram a Deus,

[[v66-7-12]]

^<<v66-7-12,12>>^ dizendo: "Amém! Louvor e glória, sabedoria, ação de graças, honra, poder e força sejam ao nosso Deus para todo o sempre. Amém! "

[[v66-7-13]]

^<<v66-7-13,13>>^ Então um dos anciãos me perguntou: "Quem são estes que estão vestidos de branco, e de onde vieram? "

[[v66-7-14]]

^<<v66-7-14,14>>^ Respondi: "Senhor, tu o sabes". E ele disse: "Estes são os que vieram da grande tribulação e lavaram as suas vestes e as branquearam no sangue do Cordeiro.

[[v66-7-15]]

^<<v66-7-15,15>>^ Por isso, eles estão diante do trono de Deus e o servem dia e noite em seu santuário; e aquele que está assentado no trono estenderá sobre eles o seu tabernáculo.

[[v66-7-16]]

^<<v66-7-16,16>>^ Nunca mais terão fome, nunca mais terão sede. Não cairá sobre eles sol, e nenhum calor abrasador,

[[v66-7-17]]

^<<v66-7-17,17>>^ pois o Cordeiro que está no centro do trono será o seu Pastor; ele os guiará às fontes de água viva. E Deus enxugará dos seus olhos toda lágrima".

'''

xref:066-apocalipse/066-apocalipse-006.adoc#v66-6-0[&#60; Capítulo Anterior] | <<v66-7-0,Topo>> | xref:066-apocalipse/066-apocalipse-008.adoc#v66-8-0[Próximo Capítulo &#62;]