include::./index.adoc[]

[[v66-22-0]]
=== Apocalipse, 22
// nvi ?, NVI - Nova Versão Internacional

[[v66-22-1]]

^<<v66-22-1,1>>^ Então o anjo me mostrou o rio da água da vida que, claro como cristal, fluía do trono de Deus e do Cordeiro,

[[v66-22-2]]

^<<v66-22-2,2>>^ no meio da rua principal da cidade. De cada lado do rio estava a árvore da vida, que dá doze colheitas, dando fruto todos os meses. As folhas da árvore servem para a cura das nações.

[[v66-22-3]]

^<<v66-22-3,3>>^ Já não haverá maldição nenhuma. O trono de Deus e do Cordeiro estará na cidade, e os seus servos o servirão.

[[v66-22-4]]

^<<v66-22-4,4>>^ Eles verão a sua face, e o seu nome estará em suas testas.

[[v66-22-5]]

^<<v66-22-5,5>>^ Não haverá mais noite. Eles não precisarão de luz de candeia nem da luz do sol, pois o Senhor Deus os iluminará; e eles reinarão para todo o sempre.

[[v66-22-6]]

^<<v66-22-6,6>>^ O anjo me disse: "Estas palavras são dignas de confiança e verdadeiras. O Senhor, o Deus dos espíritos dos profetas, enviou o seu anjo para mostrar aos seus servos as coisas que em breve hão de acontecer".

[[v66-22-7]]

^<<v66-22-7,7>>^ "Eis que venho em breve! Feliz é aquele que guarda as palavras da profecia deste livro".

[[v66-22-8]]

^<<v66-22-8,8>>^ Eu, João, sou aquele que ouviu e viu estas coisas. Tendo-as ouvido e visto, caí aos pés do anjo que me mostrou tudo aquilo para mim, para adorá-lo.

[[v66-22-9]]

^<<v66-22-9,9>>^ Mas ele me disse: "Não faça isso! Sou servo como você e seus irmãos, os profetas, e como os que guardam as palavras deste livro. Adore a Deus! "

[[v66-22-10]]

^<<v66-22-10,10>>^ Então me disse: "Não sele as palavras da profecia deste livro, pois o tempo está próximo.

[[v66-22-11]]

^<<v66-22-11,11>>^ Continue o injusto a praticar injustiça; continue o imundo na imundícia; continue o justo a praticar justiça; e continue o santo a santificar-se".

[[v66-22-12]]

^<<v66-22-12,12>>^ "Eis que venho em breve! A minha recompensa está comigo, e eu retribuirei a cada um de acordo com o que fez.

[[v66-22-13]]

^<<v66-22-13,13>>^ Eu sou o Alfa e o Ômega, o Primeiro e o Último, o Princípio e o Fim.

[[v66-22-14]]

^<<v66-22-14,14>>^ "Felizes os que lavam as suas vestes, para que tenham direito à árvore da vida e possam entrar na cidade pelas portas.

[[v66-22-15]]

^<<v66-22-15,15>>^ Fora ficam os cães, os que praticam feitiçaria, os que cometem imoralidades sexuais, os assassinos, os idólatras e todos os que amam e praticam a mentira.

[[v66-22-16]]

^<<v66-22-16,16>>^ "Eu, Jesus, enviei o meu anjo para dar a vocês este testemunho concernente às igrejas. Eu sou a Raiz e o Descendente de Davi, e a resplandecente Estrela da Manhã".

[[v66-22-17]]

^<<v66-22-17,17>>^ O Espírito e a noiva dizem: "Vem! " E todo aquele que ouvir diga: "Vem! " Quem tiver sede, venha; e quem quiser, beba de graça da água da vida.

[[v66-22-18]]

^<<v66-22-18,18>>^ Declaro a todos os que ouvem as palavras da profecia deste livro: se alguém lhe acrescentar algo, Deus lhe acrescentará as pragas descritas neste livro.

[[v66-22-19]]

^<<v66-22-19,19>>^ Se alguém tirar alguma palavra deste livro de profecia, Deus tirará dele a sua parte na árvore da vida e na cidade santa, que são descritas neste livro.

[[v66-22-20]]

^<<v66-22-20,20>>^ Aquele que dá testemunho destas coisas diz: "Sim, venho em breve! " Amém. Vem, Senhor Jesus!

[[v66-22-21]]

^<<v66-22-21,21>>^ A graça do Senhor Jesus seja com todos. Amém.

'''

xref:066-apocalipse/066-apocalipse-021.adoc#v66-21-0[&#60; Capítulo Anterior] | <<v66-22-0,Topo>> | **Próximo Capítulo &#62;**