include::./index.adoc[]

[[v66-2-0]]
=== Apocalipse, 2
// nvi ?, NVI - Nova Versão Internacional

[[v66-2-1]]

^<<v66-2-1,1>>^ Ao anjo da igreja em Éfeso escreva: Estas são as palavras daquele que tem as sete estrelas em sua mão direita e anda entre os sete candelabros de ouro.

[[v66-2-2]]

^<<v66-2-2,2>>^ Conheço as suas obras, o seu trabalho árduo e a sua perseverança. Sei que você não pode tolerar homens maus, que pôs à prova os que dizem ser apóstolos mas não são, e descobriu que eles eram impostores.

[[v66-2-3]]

^<<v66-2-3,3>>^ Você tem perseverado e suportado sofrimentos por causa do meu nome, e não tem desfalecido.

[[v66-2-4]]

^<<v66-2-4,4>>^ Contra você, porém, tenho isto: você abandonou o seu primeiro amor.

[[v66-2-5]]

^<<v66-2-5,5>>^ Lembre-se de onde caiu! Arrependa-se e pratique as obras que praticava no princípio. Se não se arrepender, virei a você e tirarei o seu candelabro do seu lugar.

[[v66-2-6]]

^<<v66-2-6,6>>^ Mas há uma coisa a seu favor: você odeia as práticas dos nicolaítas, como eu também as odeio.

[[v66-2-7]]

^<<v66-2-7,7>>^ Aquele que tem ouvidos ouça o que o Espírito diz às igrejas. Ao vencedor darei o direito de comer da árvore da vida, que está no paraíso de Deus.

[[v66-2-8]]

^<<v66-2-8,8>>^ Ao anjo da igreja em Esmirna escreva: Estas são as palavras daquele que é o Primeiro e o Último, que morreu e tornou a viver.

[[v66-2-9]]

^<<v66-2-9,9>>^ Conheço as suas aflições e a sua pobreza; mas você é rico! Conheço a blasfêmia dos que se dizem judeus mas não são, sendo antes sinagoga de Satanás.

[[v66-2-10]]

^<<v66-2-10,10>>^ Não tenha medo do que você está prestes a sofrer. Saibam que o diabo lançará alguns de vocês na prisão para prová-los, e vocês sofrerão perseguição durante dez dias. Seja fiel até a morte, e eu lhe darei a coroa da vida.

[[v66-2-11]]

^<<v66-2-11,11>>^ Aquele que tem ouvidos ouça o que o Espírito diz às igrejas. O vencedor de modo algum sofrerá a segunda morte.

[[v66-2-12]]

^<<v66-2-12,12>>^ Ao anjo da igreja em Pérgamo escreva: Estas são as palavras daquele que tem a espada afiada de dois gumes.

[[v66-2-13]]

^<<v66-2-13,13>>^ Sei onde você vive, onde está o trono de Satanás. Contudo, você permanece fiel ao meu nome e não renunciou à sua fé em mim, nem mesmo quando Antipas, minha fiel testemunha, foi morto nessa cidade, onde Satanás habita.

[[v66-2-14]]

^<<v66-2-14,14>>^ No entanto, tenho contra você algumas coisas: você tem aí pessoas que se apegam aos ensinos de Balaão, que ensinou Balaque a armar ciladas contra os israelitas, induzindo-os a comer alimentos sacrificados a ídolos e a praticar imoralidade sexual.

[[v66-2-15]]

^<<v66-2-15,15>>^ De igual modo você tem também os que se apegam aos ensinos dos nicolaítas.

[[v66-2-16]]

^<<v66-2-16,16>>^ Portanto, arrependa-se! Se não, virei em breve até você e lutarei contra eles com a espada da minha boca.

[[v66-2-17]]

^<<v66-2-17,17>>^ Aquele que tem ouvidos ouça o que o Espírito diz às igrejas. Ao vencedor darei do maná escondido. Também lhe darei uma pedra branca com um novo nome nela inscrito, conhecido apenas por aquele que o recebe.

[[v66-2-18]]

^<<v66-2-18,18>>^ Ao anjo da igreja em Tiatira escreva: Estas são as palavras do Filho de Deus, cujos olhos são como chama de fogo e os pés como bronze reluzente.

[[v66-2-19]]

^<<v66-2-19,19>>^ Conheço as suas obras, o seu amor, a sua fé, o seu serviço e a sua perseverança, e sei que você está fazendo mais agora do que no princípio.

[[v66-2-20]]

^<<v66-2-20,20>>^ No entanto, contra você tenho isto: você tolera Jezabel, aquela mulher que se diz profetisa. Com os seus ensinos, ela induz os meus servos à imoralidade sexual e a comerem alimentos sacrificados aos ídolos.

[[v66-2-21]]

^<<v66-2-21,21>>^ Dei-lhe tempo para que se arrependesse da sua imoralidade sexual, mas ela não quer se arrepender.

[[v66-2-22]]

^<<v66-2-22,22>>^ Por isso, vou fazê-la adoecer e trarei grande sofrimento aos que cometem adultério com ela, a não ser que se arrependam das obras que ela pratica.

[[v66-2-23]]

^<<v66-2-23,23>>^ Matarei os filhos dessa mulher. Então, todas as igrejas saberão que eu sou aquele que sonda mentes e corações, e retribuirei a cada um de vocês de acordo com as suas obras.

[[v66-2-24]]

^<<v66-2-24,24>>^ Aos demais que estão em Tiatira, a vocês que não seguem a doutrina dela e não aprenderam, como eles dizem, os profundos segredos de Satanás, digo: não porei outra carga sobre vocês;

[[v66-2-25]]

^<<v66-2-25,25>>^ tão-somente apeguem-se com firmeza ao que vocês têm, até que eu venha.

[[v66-2-26]]

^<<v66-2-26,26>>^ Àquele que vencer e fizer a minha vontade até o fim darei autoridade sobre as nações.

[[v66-2-27]]

^<<v66-2-27,27>>^ "Ele as governará com cetro de ferro e as despedaçará a um vaso de barro"

[[v66-2-28]]

^<<v66-2-28,28>>^ Eu lhes darei a mesma autoridade que recebi autoridade de meu Pai. Também lhe darei a estrela da manhã.

[[v66-2-29]]

^<<v66-2-29,29>>^ Aquele que tem ouvidos ouça o que o Espírito diz às igrejas.

'''

xref:066-apocalipse/066-apocalipse-001.adoc#v66-1-0[&#60; Capítulo Anterior] | <<v66-2-0,Topo>> | xref:066-apocalipse/066-apocalipse-003.adoc#v66-3-0[Próximo Capítulo &#62;]