include::./index.adoc[]

[[v66-16-0]]
=== Apocalipse, 16
// nvi ?, NVI - Nova Versão Internacional

[[v66-16-1]]

^<<v66-16-1,1>>^ Então ouvi uma forte voz que vinha do santuário dizendo aos sete anjos: "Vão derramar sobre a terra as sete taças da ira de Deus".

[[v66-16-2]]

^<<v66-16-2,2>>^ O primeiro anjo foi e derramou a sua taça pela terra, e abriram-se feridas malignas e dolorosas naqueles que tinham a marca da besta e adoravam a sua imagem.

[[v66-16-3]]

^<<v66-16-3,3>>^ O segundo anjo derramou a sua taça no mar, e este se transformou em sangue como de um morto, e morreu toda criatura que vivia no mar.

[[v66-16-4]]

^<<v66-16-4,4>>^ O terceiro anjo derramou a sua taça nos rios e nas fontes de águas, e eles se transformaram em sangue.

[[v66-16-5]]

^<<v66-16-5,5>>^ Então ouvi o anjo que tem autoridade sobre as águas dizer: "Tu és justo, tu, o Santo, que és e que eras, porque julgaste estas coisas;

[[v66-16-6]]

^<<v66-16-6,6>>^ pois eles derramaram o sangue dos teus santos e dos teus profetas, e tu lhes deste sangue para beber, como eles merecem".

[[v66-16-7]]

^<<v66-16-7,7>>^ E ouvi o altar responder: "Sim, Senhor Deus todo-poderoso, verdadeiros e justos são os teus juízos".

[[v66-16-8]]

^<<v66-16-8,8>>^ O quarto anjo derramou a sua taça no sol, e foi dado poder ao sol para queimar os homens com fogo.

[[v66-16-9]]

^<<v66-16-9,9>>^ Estes foram queimados pelo forte calor e amaldiçoaram o nome de Deus, que tem domínio sobre estas pragas; contudo se recusaram a se arrepender e a glorificá-lo.

[[v66-16-10]]

^<<v66-16-10,10>>^ O quinto anjo derramou a sua taça sobre o trono da besta, cujo reino ficou em trevas. De tanta agonia, os homens mordiam a própria língua,

[[v66-16-11]]

^<<v66-16-11,11>>^ e blasfemavam contra o Deus do céu, por causa das suas dores e das suas feridas; contudo, recusaram-se a arrepender-se das obras que haviam praticado.

[[v66-16-12]]

^<<v66-16-12,12>>^ O sexto anjo derramou a sua taça sobre o grande rio Eufrates, e secaram-se as suas águas para que fosse preparado o caminho para os reis que vêm do Oriente.

[[v66-16-13]]

^<<v66-16-13,13>>^ Então vi saírem da boca do dragão, da boca da besta e da boca do falso profeta três espíritos imundos semelhantes a rãs.

[[v66-16-14]]

^<<v66-16-14,14>>^ São espíritos de demônios que realizam sinais miraculosos; eles vão aos reis de todo o mundo, a fim de reuni-los para a batalha do grande dia do Deus todo-poderoso.

[[v66-16-15]]

^<<v66-16-15,15>>^ "Eis que venho como ladrão! Feliz aquele que permanece vigilante e conserva consigo as suas vestes, para que não ande nu e não seja vista a sua vergonha".

[[v66-16-16]]

^<<v66-16-16,16>>^ Então os três espíritos os reuniram no lugar que, em hebraico, é chamado Armagedom.

[[v66-16-17]]

^<<v66-16-17,17>>^ O sétimo anjo derramou a sua taça no ar, e do santuário saiu uma forte voz que vinha do trono, dizendo: "Está feito! "

[[v66-16-18]]

^<<v66-16-18,18>>^ Houve, então, relâmpagos, vozes, trovões e um forte terremoto. Nunca havia ocorrido um terremoto tão forte como esse desde que o homem existe sobre a terra.

[[v66-16-19]]

^<<v66-16-19,19>>^ A grande cidade foi fracionada em três partes, e as cidades das nações se desmoronaram. Deus lembrou-se da grande Babilônia e lhe deu o cálice do vinho do furor da sua ira.

[[v66-16-20]]

^<<v66-16-20,20>>^ Todas as ilhas fugiram, e as montanhas desapareceram.

[[v66-16-21]]

^<<v66-16-21,21>>^ Caíram sobre os homens, vindas do céu, enormes pedras de granizo, de cerca de trinta e cinco quilos cada; eles blasfemaram contra Deus por causa do granizo, pois a praga fora terrível.

'''

xref:066-apocalipse/066-apocalipse-015.adoc#v66-15-0[&#60; Capítulo Anterior] | <<v66-16-0,Topo>> | xref:066-apocalipse/066-apocalipse-017.adoc#v66-17-0[Próximo Capítulo &#62;]