include::./index.adoc[]

[[v66-17-0]]
=== Apocalipse, 17
// nvi ?, NVI - Nova Versão Internacional

[[v66-17-1]]

^<<v66-17-1,1>>^ Um dos sete anjos que tinham as sete taças aproximou-se e me disse: "Venha, eu lhe mostrarei o julgamento da grande prostituta que está sentada sobre muitas águas,

[[v66-17-2]]

^<<v66-17-2,2>>^ com quem os reis da terra se prostituíram; os habitantes da terra se embriagaram com o vinho da sua prostituição".

[[v66-17-3]]

^<<v66-17-3,3>>^ Então o anjo me levou no Espírito para um deserto. Ali vi uma mulher montada numa besta vermelha, que estava coberta de nomes blasfemos e que tinha sete cabeças e dez chifres.

[[v66-17-4]]

^<<v66-17-4,4>>^ A mulher estava vestida de azul e vermelho, e adornada de ouro, pedras preciosas e pérolas. Segurava um cálice de ouro, cheio de coisas repugnantes e da impureza da sua prostituição.

[[v66-17-5]]

^<<v66-17-5,5>>^ Em sua testa havia esta inscrição: MISTÉRIO: BABILÔNIA, A GRANDE; A MÃE DAS PROSTITUTAS E DAS PRÁTICAS REPUGNANTES DA TERRA.

[[v66-17-6]]

^<<v66-17-6,6>>^ Vi que a mulher estava embriagada com o sangue dos santos, o sangue das testemunhas de Jesus. Quando a vi, fiquei muito admirado.

[[v66-17-7]]

^<<v66-17-7,7>>^ Então o anjo me disse: "Por que você está admirado? Eu lhe explicarei o mistério dessa mulher e da besta sobre a qual ela está montada, que tem sete cabeças e dez chifres.

[[v66-17-8]]

^<<v66-17-8,8>>^ A besta que você viu, era e já não é. Ela está para subir do abismo e caminha para a perdição. Os habitantes da terra, cujos nomes não foram escritos no livro da vida desde a criação do mundo, ficarão admirados quando virem a besta, porque ela era, agora não é, e entretanto virá.

[[v66-17-9]]

^<<v66-17-9,9>>^ "Aqui se requer mente sábia. As sete cabeças são sete colinas sobre as quais está sentada a mulher.

[[v66-17-10]]

^<<v66-17-10,10>>^ São também sete reis. Cinco já caíram, um ainda existe, e o outro ainda não surgiu; mas, quando surgir, deverá permanecer durante pouco tempo.

[[v66-17-11]]

^<<v66-17-11,11>>^ A besta que era, e agora não é, é o oitavo rei. É um dos sete, e caminha para a perdição.

[[v66-17-12]]

^<<v66-17-12,12>>^ "Os dez chifres que você viu são dez reis que ainda não receberam reino, mas que por uma hora receberão autoridade como reis, juntamente com a besta.

[[v66-17-13]]

^<<v66-17-13,13>>^ Eles têm um único propósito, e darão seu poder e sua autoridade à besta.

[[v66-17-14]]

^<<v66-17-14,14>>^ Guerrearão contra o Cordeiro, mas o Cordeiro os vencerá, pois é o Senhor dos senhores e o Rei dos reis; e vencerão com ele os seus chamados, escolhidos e fiéis".

[[v66-17-15]]

^<<v66-17-15,15>>^ Então o anjo me disse: "As águas que você viu, onde está sentada a prostituta, são povos, multidões, nações e línguas.

[[v66-17-16]]

^<<v66-17-16,16>>^ A besta e os dez chifres que você viu odiarão a prostituta. Eles a levarão à ruína e a deixarão nua, comerão a sua carne e a destruirão com fogo,

[[v66-17-17]]

^<<v66-17-17,17>>^ pois Deus colocou no coração deles o desejo de realizar o propósito que ele tem, levando-os a concordarem em dar à besta o poder que eles têm para reinar até que se cumpram as palavras de Deus.

[[v66-17-18]]

^<<v66-17-18,18>>^ A mulher que você viu é a grande cidade que reina sobre os reis da terra".

'''

xref:066-apocalipse/066-apocalipse-016.adoc#v66-16-0[&#60; Capítulo Anterior] | <<v66-17-0,Topo>> | xref:066-apocalipse/066-apocalipse-018.adoc#v66-18-0[Próximo Capítulo &#62;]