include::./index.adoc[]

[[v66-3-0]]
=== Apocalipse, 3
// nvi ?, NVI - Nova Versão Internacional

[[v66-3-1]]

^<<v66-3-1,1>>^ Ao anjo da igreja em Sardes escreva: Estas são as palavras daquele que tem os sete espíritos de Deus e as sete estrelas. Conheço as suas obras; você tem fama de estar vivo, mas está morto.

[[v66-3-2]]

^<<v66-3-2,2>>^ Esteja atento! Fortaleça o que resta e que estava para morrer, pois não achei suas obras perfeitas aos olhos do meu Deus.

[[v66-3-3]]

^<<v66-3-3,3>>^ Lembre-se, portanto, do que você recebeu e ouviu; obedeça e arrependa-se. Mas se você não estiver atento, virei como um ladrão e você não saberá a que hora virei contra você.

[[v66-3-4]]

^<<v66-3-4,4>>^ No entanto, você tem aí em Sardes uns poucos que não contaminaram as suas vestes. Eles andarão comigo, vestidos de branco, pois são dignos.

[[v66-3-5]]

^<<v66-3-5,5>>^ O vencedor será igualmente vestido de branco. Jamais apagarei o seu nome do livro da vida, mas o reconhecerei diante do meu Pai e dos seus anjos.

[[v66-3-6]]

^<<v66-3-6,6>>^ Aquele que tem ouvidos ouça o que o Espírito diz às igrejas.

[[v66-3-7]]

^<<v66-3-7,7>>^ Ao anjo da igreja em Filadélfia escreva: Estas são as palavras daquele que é santo e verdadeiro, que tem a chave de Davi. O que ele abre ninguém pode fechar, e o que ele fecha ninguém pode abrir.

[[v66-3-8]]

^<<v66-3-8,8>>^ Conheço as suas obras. Eis que coloquei diante de você uma porta aberta que ninguém pode fechar. Sei que você tem pouca força, mas guardou a minha palavra e não negou o meu nome.

[[v66-3-9]]

^<<v66-3-9,9>>^ Vejam o que farei com aqueles que são sinagoga de Satanás e que se dizem judeus e não são, mas são mentirosos. Farei que se prostrem aos seus pés e reconheçam que eu amei você.

[[v66-3-10]]

^<<v66-3-10,10>>^ Visto que você guardou a minha palavra de exortação à perseverança, eu também o guardarei da hora da provação que está para vir sobre todo o mundo, para pôr à prova os que habitam na terra.

[[v66-3-11]]

^<<v66-3-11,11>>^ Venho em breve! Retenha o que você tem, para que ninguém tome a sua coroa.

[[v66-3-12]]

^<<v66-3-12,12>>^ Farei do vencedor uma coluna no santuário do meu Deus, e dali ele jamais sairá. Escreverei nele o nome do meu Deus e o nome da cidade do meu Deus, a nova Jerusalém, que desce do céu da parte de Deus; e também escreverei nele o meu novo nome.

[[v66-3-13]]

^<<v66-3-13,13>>^ Aquele que tem ouvidos ouça o que o Espírito diz às igrejas.

[[v66-3-14]]

^<<v66-3-14,14>>^ Ao anjo da igreja em Laodicéia escreva: Estas são as palavras do Amém, a testemunha fiel e verdadeira, o soberano da criação de Deus.

[[v66-3-15]]

^<<v66-3-15,15>>^ Conheço as suas obras, sei que você não é frio nem quente. Melhor seria que você fosse frio ou quente!

[[v66-3-16]]

^<<v66-3-16,16>>^ Assim, porque você é morno, nem frio nem quente, estou a ponto de vomitá-lo da minha boca.

[[v66-3-17]]

^<<v66-3-17,17>>^ Você diz: Estou rico, adquiri riquezas e não preciso de nada. Não reconhece, porém, que é miserável, digno de compaixão, pobre, cego e que está nu.

[[v66-3-18]]

^<<v66-3-18,18>>^ Dou-lhe este aconselho: Compre de mim ouro refinado no fogo e você se tornará rico; compre roupas brancas e vista-se para cobrir a sua vergonhosa nudez; e compre colírio para ungir os seus olhos e poder enxergar.

[[v66-3-19]]

^<<v66-3-19,19>>^ Repreendo e disciplino aqueles que eu amo. Por isso, seja diligente e arrependa-se.

[[v66-3-20]]

^<<v66-3-20,20>>^ Eis que estou à porta e bato. Se alguém ouvir a minha voz e abrir a porta, entrarei e cearei com ele, e ele comigo.

[[v66-3-21]]

^<<v66-3-21,21>>^ Ao vencedor darei o direito de sentar-se comigo em meu trono, assim como eu também venci e sentei-me com meu Pai em seu trono.

[[v66-3-22]]

^<<v66-3-22,22>>^ Aquele que tem ouvidos ouça o que o Espírito diz às igrejas.

'''

xref:066-apocalipse/066-apocalipse-002.adoc#v66-2-0[&#60; Capítulo Anterior] | <<v66-3-0,Topo>> | xref:066-apocalipse/066-apocalipse-004.adoc#v66-4-0[Próximo Capítulo &#62;]