include::./index.adoc[]

[[v66-19-0]]
=== Apocalipse, 19
// nvi ?, NVI - Nova Versão Internacional

[[v66-19-1]]

^<<v66-19-1,1>>^ Depois disso ouvi no céu algo semelhante à voz de uma grande multidão, que exclamava: "Aleluia! A salvação, a glória e o poder pertencem ao nosso Deus,

[[v66-19-2]]

^<<v66-19-2,2>>^ pois verdadeiros e justos são os seus juízos. Ele condenou a grande prostituta que corrompia a terra com a sua prostituição. Ele cobrou dela o sangue dos seus servos".

[[v66-19-3]]

^<<v66-19-3,3>>^ E mais uma vez a multidão exclamou: "Aleluia! A fumaça que dela vem, sobe para todo o sempre".

[[v66-19-4]]

^<<v66-19-4,4>>^ Os vinte e quatro anciãos e os quatro seres viventes prostraram-se e adoraram a Deus, que estava assentado no trono, e exclamaram: "Amém, Aleluia! "

[[v66-19-5]]

^<<v66-19-5,5>>^ Então veio do trono uma voz, conclamando: "Louvem o nosso Deus, todos vocês, seus servos, vocês que o temem, tanto pequenos como grandes! "

[[v66-19-6]]

^<<v66-19-6,6>>^ Então ouvi algo semelhante ao som de uma grande multidão, como o estrondo de muitas águas e fortes trovões, que bradava: "Aleluia! pois reina o Senhor, o nosso Deus, o Todo-poderoso.

[[v66-19-7]]

^<<v66-19-7,7>>^ Regozijemo-nos! Vamos nos alegrar e dar-lhe glória! Pois chegou a hora do casamento do Cordeiro, e a sua noiva já se aprontou.

[[v66-19-8]]

^<<v66-19-8,8>>^ Foi-lhe dado para vestir-se linho fino, brilhante e puro". O linho fino são os atos justos dos santos.

[[v66-19-9]]

^<<v66-19-9,9>>^ E o anjo me disse: "Escreva: Felizes os convidados para o banquete do casamento do Cordeiro! " E acrescentou: "Estas são as palavras verdadeiras de Deus".

[[v66-19-10]]

^<<v66-19-10,10>>^ Então caí aos seus pés para adorá-lo, mas ele me disse: "Não faça isso! Sou servo como você e como os seus irmãos que se mantêm fiéis ao testemunho de Jesus. Adore a Deus! O testemunho de Jesus é o espírito de profecia".

[[v66-19-11]]

^<<v66-19-11,11>>^ Vi o céu aberto e diante de mim um cavalo branco, cujo cavaleiro se chama Fiel e Verdadeiro. Ele julga e guerreia com justiça.

[[v66-19-12]]

^<<v66-19-12,12>>^ Seus olhos são como chamas de fogo, e em sua cabeça há muitas coroas e um nome que só ele conhece, e ninguém mais.

[[v66-19-13]]

^<<v66-19-13,13>>^ Está vestido com um manto tingido de sangue, e o seu nome é Palavra de Deus.

[[v66-19-14]]

^<<v66-19-14,14>>^ Os exércitos do céu o seguiam, vestidos de linho fino, branco e puro, e montados em cavalos brancos.

[[v66-19-15]]

^<<v66-19-15,15>>^ De sua boca sai uma espada afiada, com a qual ferirá as nações. "Ele as governará com cetro de ferro". Ele pisa o lagar do vinho do furor da ira do Deus todo-poderoso.

[[v66-19-16]]

^<<v66-19-16,16>>^ Em seu manto e em sua coxa está escrito este nome: REI DOS REIS E SENHOR DOS SENHORES.

[[v66-19-17]]

^<<v66-19-17,17>>^ Vi um anjo que estava de pé no sol e que clamava em alta voz a todas as aves que voavam pelo meio do céu: "Venham, reúnam-se para o grande banquete de Deus,

[[v66-19-18]]

^<<v66-19-18,18>>^ para comerem carne de reis, generais e poderosos, carne de cavalos e seus cavaleiros, carne de todos: livres e escravos, pequenos e grandes".

[[v66-19-19]]

^<<v66-19-19,19>>^ Então vi a besta, os reis da terra e os seus exércitos reunidos para guerrearem contra aquele que está montado no cavalo e contra o seu exército.

[[v66-19-20]]

^<<v66-19-20,20>>^ Mas a besta foi presa, e com ela o falso profeta que havia realizado os sinais miraculosos em nome dela, com os quais ele havia enganado os que receberam a marca da besta e adoraram a imagem dela. Os dois foram lançados vivos no lago de fogo que arde com enxofre.

[[v66-19-21]]

^<<v66-19-21,21>>^ Os demais foram mortos com a espada que saía da boca daquele que está montado no cavalo. E todas as aves se fartaram com a carne deles.

'''

xref:066-apocalipse/066-apocalipse-018.adoc#v66-18-0[&#60; Capítulo Anterior] | <<v66-19-0,Topo>> | xref:066-apocalipse/066-apocalipse-020.adoc#v66-20-0[Próximo Capítulo &#62;]