include::./index.adoc[]

[[v66-1-0]]
=== Apocalipse, 1
// nvi ?, NVI - Nova Versão Internacional

[[v66-1-1]]

^<<v66-1-1,1>>^ Revelação de Jesus Cristo, que Deus lhe deu para mostrar aos seus servos o que em breve há de acontecer. Ele enviou o seu anjo para torná-la conhecida ao seu servo João,

[[v66-1-2]]

^<<v66-1-2,2>>^ que dá testemunho de tudo o que viu, isto é, a palavra de Deus e o testemunho de Jesus Cristo.

[[v66-1-3]]

^<<v66-1-3,3>>^ Feliz aquele que lê as palavras desta profecia e felizes aqueles que ouvem e guardam o que nela está escrito, porque o tempo está próximo.

[[v66-1-4]]

^<<v66-1-4,4>>^ João às sete igrejas da província da Ásia: A vocês, graça e paz da parte daquele que é, que era e que há de vir, dos sete espíritos que estão diante do seu trono,

[[v66-1-5]]

^<<v66-1-5,5>>^ e de Jesus Cristo, que é a testemunha fiel, o primogênito dentre os mortos e o soberano dos reis da terra. Ele que nos ama e nos libertou dos nossos pecados por meio do seu sangue,

[[v66-1-6]]

^<<v66-1-6,6>>^ e nos constituiu reino e sacerdotes para servir a seu Deus e Pai. A ele sejam glória e poder para todo o sempre! Amém.

[[v66-1-7]]

^<<v66-1-7,7>>^ Eis que ele vem com as nuvens, e todo olho o verá, até mesmo aqueles que o traspassaram; e todos os povos da terra se lamentarão por causa dele. Assim será! Amém.

[[v66-1-8]]

^<<v66-1-8,8>>^ "Eu sou o Alfa e o Ômega", diz o Senhor Deus, "o que é, o que era e o que há de vir, o Todo-poderoso".

[[v66-1-9]]

^<<v66-1-9,9>>^ Eu, João, irmão e companheiro de vocês no sofrimento, no Reino e na perseverança em Jesus, estava na ilha de Patmos, por causa da palavra de Deus e do testemunho de Jesus.

[[v66-1-10]]

^<<v66-1-10,10>>^ No dia do Senhor achei-me no Espírito e ouvi por trás de mim uma voz forte, como de trombeta,

[[v66-1-11]]

^<<v66-1-11,11>>^ que dizia: "Escreva num livro o que você vê e envie a estas sete igrejas: Éfeso, Esmirna, Pérgamo, Tiatira, Sardes, Filadélfia e Laodicéia".

[[v66-1-12]]

^<<v66-1-12,12>>^ Voltei-me para ver quem falava comigo. Voltando-me, vi sete candelabros de ouro

[[v66-1-13]]

^<<v66-1-13,13>>^ e entre os candelabros alguém "semelhante a um filho de homem", com uma veste que chegava aos seus pés e um cinturão de ouro ao redor do peito.

[[v66-1-14]]

^<<v66-1-14,14>>^ Sua cabeça e seus cabelos eram brancos como a lã, tão brancos quanto a neve, e seus olhos eram como chama de fogo.

[[v66-1-15]]

^<<v66-1-15,15>>^ Seus pés eram como o bronze numa fornalha ardente e sua voz como o som de muitas águas.

[[v66-1-16]]

^<<v66-1-16,16>>^ Tinha em sua mão direita sete estrelas, e da sua boca saía uma espada afiada de dois gumes. Sua face era como o sol quando brilha em todo o seu fulgor.

[[v66-1-17]]

^<<v66-1-17,17>>^ Quando o vi, caí aos seus pés como morto. Então ele colocou sua mão direita sobre mim e disse: "Não tenha medo. Eu sou o primeiro e o último.

[[v66-1-18]]

^<<v66-1-18,18>>^ Sou aquele que vive. Estive morto mas agora estou vivo para todo o sempre! E tenho as chaves da morte e do Hades.

[[v66-1-19]]

^<<v66-1-19,19>>^ "Escreva, pois, as coisas que você viu, tanto as presentes como as que estão por vir.

[[v66-1-20]]

^<<v66-1-20,20>>^ Este é o mistério das sete estrelas que você viu em minha mão direita e dos sete candelabros: as sete estrelas são os anjos das sete igrejas, e os sete candelabros são as sete igrejas".

'''

xref:065-judas/065-judas-001.adoc#v65-1-0[&#60; Capítulo Anterior] | <<v66-1-0,Topo>> | xref:066-apocalipse/066-apocalipse-002.adoc#v66-2-0[Próximo Capítulo &#62;]