include::./index.adoc[]

[[v66-5-0]]
=== Apocalipse, 5
// nvi ?, NVI - Nova Versão Internacional

[[v66-5-1]]

^<<v66-5-1,1>>^ Então vi na mão direita daquele que está assentado no trono um livro em forma de rolo escrito de ambos os lados e selado com sete selos.

[[v66-5-2]]

^<<v66-5-2,2>>^ Vi um anjo poderoso, proclamando em alta voz: "Quem é digno de romper os selos e de abrir o livro? "

[[v66-5-3]]

^<<v66-5-3,3>>^ Mas não havia ninguém, nem no céu nem na terra nem debaixo da terra, que podia abrir o livro, ou sequer olhar para ele.

[[v66-5-4]]

^<<v66-5-4,4>>^ Eu chorava muito, porque não se encontrou ninguém que fosse digno de abrir o livro e de olhar para ele.

[[v66-5-5]]

^<<v66-5-5,5>>^ Então um dos anciãos me disse: "Não chore! Eis que o Leão da tribo de Judá, a Raiz de Davi, venceu para abrir o livro e os seus sete selos".

[[v66-5-6]]

^<<v66-5-6,6>>^ Então vi um Cordeiro, que parecia ter estado morto, de pé, no centro do trono, cercado pelos quatro seres viventes e pelos anciãos. Ele tinha sete chifres e sete olhos, que são os sete espíritos de Deus enviados a toda a terra.

[[v66-5-7]]

^<<v66-5-7,7>>^ Ele se aproximou e recebeu o livro da mão direita daquele que estava assentado no trono.

[[v66-5-8]]

^<<v66-5-8,8>>^ Ao recebê-lo, os quatro seres viventes e os vinte e quatro anciãos prostraram-se diante do Cordeiro. Cada um deles tinha uma harpa e taças de ouro cheias de incenso, que são as orações dos santos;

[[v66-5-9]]

^<<v66-5-9,9>>^ e eles cantavam um cântico novo: "Tu és digno de receber o livro e de abrir os seus selos, pois foste morto, e com teu sangue compraste para Deus homens de toda tribo, língua, povo e nação.

[[v66-5-10]]

^<<v66-5-10,10>>^ Tu os constituíste reino e sacerdotes para o nosso Deus, e eles reinarão sobre a terra".

[[v66-5-11]]

^<<v66-5-11,11>>^ Então olhei e ouvi a voz de muitos anjos, milhares de milhares e milhões de milhões. Eles rodeavam o trono, bem como os seres viventes e os anciãos,

[[v66-5-12]]

^<<v66-5-12,12>>^ e cantavam em alta voz: "Digno é o Cordeiro que foi morto de receber poder, riqueza, sabedoria, força, honra, glória e louvor! "

[[v66-5-13]]

^<<v66-5-13,13>>^ Depois ouvi todas as criaturas existentes no céu, na terra, debaixo da terra e no mar, e tudo o que neles há, que diziam: "Àquele que está assentado no trono e ao Cordeiro sejam o louvor, a honra, a glória e o poder, para todo o sempre! "

[[v66-5-14]]

^<<v66-5-14,14>>^ Os quatro seres viventes disseram: "Amém", e os anciãos prostraram-se e o adoraram.

'''

xref:066-apocalipse/066-apocalipse-004.adoc#v66-4-0[&#60; Capítulo Anterior] | <<v66-5-0,Topo>> | xref:066-apocalipse/066-apocalipse-006.adoc#v66-6-0[Próximo Capítulo &#62;]