include::./index.adoc[]

[[v66-4-0]]
=== Apocalipse, 4
// nvi ?, NVI - Nova Versão Internacional

[[v66-4-1]]

^<<v66-4-1,1>>^ Depois dessas coisas olhei, e diante de mim estava uma porta aberta no céu. A voz que eu tinha ouvido no princípio, falando comigo como trombeta, disse: "Suba para cá, e lhe mostrarei o que deve acontecer depois dessas coisas".

[[v66-4-2]]

^<<v66-4-2,2>>^ Imediatamente me vi tomado pelo Espírito, e diante de mim estava um trono no céu e nele estava assentado alguém.

[[v66-4-3]]

^<<v66-4-3,3>>^ Aquele que estava assentado era de aspecto semelhante a jaspe e sardônio. Um arco-íris, parecendo uma esmeralda, circundava o trono,

[[v66-4-4]]

^<<v66-4-4,4>>^ ao redor do qual estavam outros vinte e quatro tronos, e assentados neles havia vinte e quatro anciãos. Eles estavam vestidos de branco e tinham na cabeça coroas de ouro.

[[v66-4-5]]

^<<v66-4-5,5>>^ Do trono saíam relâmpagos, vozes e trovões. Diante dele estavam acesas sete lâmpadas de fogo, que são os sete espíritos de Deus.

[[v66-4-6]]

^<<v66-4-6,6>>^ Também diante do trono havia algo parecido com um mar de vidro, claro como cristal. No centro, ao redor do trono, havia quatro seres viventes cobertos de olhos, tanto na frente como atrás.

[[v66-4-7]]

^<<v66-4-7,7>>^ O primeiro ser parecia um leão, o segundo parecia um boi, o terceiro tinha rosto como de homem, o quarto parecia uma águia quando em vôo.

[[v66-4-8]]

^<<v66-4-8,8>>^ Cada um deles tinha seis asas e era cheio de olhos, tanto ao redor como por baixo das asas. Dia e noite repetem sem cessar: "Santo, santo, santo é o Senhor, o Deus todo-poderoso, que era, que é e que há de vir".

[[v66-4-9]]

^<<v66-4-9,9>>^ Toda vez que os seres viventes dão glória, honra e graças àquele que está assentado no trono e que vive para todo o sempre,

[[v66-4-10]]

^<<v66-4-10,10>>^ os vinte e quatro anciãos se prostram diante daquele que está assentado no trono e adoram aquele que vive para todo o sempre. Eles lançam as suas coroas diante do trono, dizem:

[[v66-4-11]]

^<<v66-4-11,11>>^ "Tu, Senhor e Deus nosso, és digno de receber a glória, a honra e o poder, porque criaste todas as coisas, e por tua vontade elas existem e foram criadas".

'''

xref:066-apocalipse/066-apocalipse-003.adoc#v66-3-0[&#60; Capítulo Anterior] | <<v66-4-0,Topo>> | xref:066-apocalipse/066-apocalipse-005.adoc#v66-5-0[Próximo Capítulo &#62;]