include::./index.adoc[]

[[v66-21-0]]
=== Apocalipse, 21
// nvi ?, NVI - Nova Versão Internacional

[[v66-21-1]]

^<<v66-21-1,1>>^ Então vi um novo céu e uma nova terra, pois o primeiro céu e a primeira terra tinham passado; e o mar já não existia.

[[v66-21-2]]

^<<v66-21-2,2>>^ Vi a cidade santa, a nova Jerusalém, que descia do céu, da parte de Deus, preparada como uma noiva adornada para o seu marido.

[[v66-21-3]]

^<<v66-21-3,3>>^ Ouvi uma forte voz que vinha do trono e dizia: "Agora o tabernáculo de Deus está com os homens, com os quais ele viverá. Eles serão os seus povos; o próprio Deus estará com eles e será o seu Deus.

[[v66-21-4]]

^<<v66-21-4,4>>^ Ele enxugará dos seus olhos toda lágrima. Não haverá mais morte, nem tristeza, nem choro, nem dor, pois a antiga ordem já passou".

[[v66-21-5]]

^<<v66-21-5,5>>^ Aquele que estava assentado no trono disse: "Estou fazendo novas todas as coisas! " E acrescentou: "Escreva isto, pois estas palavras são verdadeiras e dignas de confiança".

[[v66-21-6]]

^<<v66-21-6,6>>^ Disse-me ainda: "Está feito. Eu sou o Alfa e o Ômega, o Princípio e o Fim. A quem tiver sede, darei de beber gratuitamente da fonte da água da vida.

[[v66-21-7]]

^<<v66-21-7,7>>^ O vencedor herdará tudo isto, e eu serei seu Deus e ele será meu filho.

[[v66-21-8]]

^<<v66-21-8,8>>^ Mas os covardes, os incrédulos, os depravados, os assassinos, os que cometem imoralidade sexual, os que praticam feitiçaria, os idólatras e todos os mentirosos — o lugar deles será no lago de fogo que arde com enxofre. Esta é a segunda morte".

[[v66-21-9]]

^<<v66-21-9,9>>^ Um dos sete anjos que tinham as sete taças cheias das últimas sete pragas aproximou-se e me disse: "Venha, eu lhe mostrarei a noiva, a esposa do Cordeiro".

[[v66-21-10]]

^<<v66-21-10,10>>^ Ele me levou no Espírito a um grande e alto monte e mostrou-me a Cidade Santa, Jerusalém, que descia do céu, da parte de Deus.

[[v66-21-11]]

^<<v66-21-11,11>>^ Ela resplandecia com a glória de Deus, e o seu brilho era como o de uma jóia muito preciosa, como jaspe, clara como cristal.

[[v66-21-12]]

^<<v66-21-12,12>>^ Tinha uma grande e alta muralha com doze portas e doze anjos junto às portas. Nas portas estavam escritos os nomes das doze tribos de Israel.

[[v66-21-13]]

^<<v66-21-13,13>>^ Havia três portas ao oriente, três ao norte, três ao sul e três ao ocidente.

[[v66-21-14]]

^<<v66-21-14,14>>^ A muralha da cidade tinha doze fundamentos, e neles estavam os nomes dos doze apóstolos do Cordeiro.

[[v66-21-15]]

^<<v66-21-15,15>>^ O anjo que falava comigo tinha como medida uma vara feita de ouro, para medir a cidade, suas portas e seus muros.

[[v66-21-16]]

^<<v66-21-16,16>>^ A cidade era quadrangular, de comprimento e largura iguais. Ele mediu a cidade com a vara; tinha dois mil e duzentos quilômetros de comprimento; a largura e a altura eram iguais ao comprimento.

[[v66-21-17]]

^<<v66-21-17,17>>^ Ele mediu a muralha, e deu sessenta e cinco metros de espessura, segundo a medida humana que o anjo estava usando.

[[v66-21-18]]

^<<v66-21-18,18>>^ A muralha era feita de jaspe e a cidade de ouro puro, semelhante ao vidro puro.

[[v66-21-19]]

^<<v66-21-19,19>>^ Os fundamentos das muros da cidade eram ornamentados com toda sorte de pedras preciosas. O primeiro fundamento era ornamentado com jaspe; o segundo com safira; o terceiro com calcedônia; o quarto com esmeralda;

[[v66-21-20]]

^<<v66-21-20,20>>^ o quinto com sardônio; o sexto com sárdio; o sétimo com crisólito; o oitavo com berilo; o nono com topázio; o décimo com crisópraso; o décimo primeiro com jacinto; e o décimo segundo com ametista.

[[v66-21-21]]

^<<v66-21-21,21>>^ As doze portas eram doze pérolas, cada porta feita de uma única pérola. A rua principal da cidade era de ouro puro, como vidro transparente.

[[v66-21-22]]

^<<v66-21-22,22>>^ Não vi templo algum na cidade, pois o Senhor Deus todo-poderoso e o Cordeiro são o seu templo.

[[v66-21-23]]

^<<v66-21-23,23>>^ A cidade não precisa de sol nem de lua para brilharem sobre ela, pois a glória de Deus a ilumina, e o Cordeiro é a sua candeia.

[[v66-21-24]]

^<<v66-21-24,24>>^ As nações andarão em sua luz, e os reis da terra lhe trarão a sua glória.

[[v66-21-25]]

^<<v66-21-25,25>>^ Suas portas jamais se fecharão de dia, pois ali não haverá noite.

[[v66-21-26]]

^<<v66-21-26,26>>^ A glória e a honra das nações lhe serão trazidas.

[[v66-21-27]]

^<<v66-21-27,27>>^ Nela jamais entrará algo impuro, nem ninguém que pratique o que é vergonhoso ou enganoso, mas unicamente aqueles cujos nomes estão escritos no livro da vida do Cordeiro.

'''

xref:066-apocalipse/066-apocalipse-020.adoc#v66-20-0[&#60; Capítulo Anterior] | <<v66-21-0,Topo>> | xref:066-apocalipse/066-apocalipse-022.adoc#v66-22-0[Próximo Capítulo &#62;]