include::./index.adoc[]

[[v66-13-0]]
=== Apocalipse, 13
// nvi ?, NVI - Nova Versão Internacional

[[v66-13-1]]

^<<v66-13-1,1>>^ Vi uma besta que saía do mar. Tinha dez chifres e sete cabeças, com dez coroas, uma sobre cada chifre, e em cada cabeça um nome de blasfêmia.

[[v66-13-2]]

^<<v66-13-2,2>>^ A besta que vi era semelhante a um leopardo, mas tinha pés como os de urso e boca como a de leão. O dragão deu à besta o seu poder, o seu trono e grande autoridade.

[[v66-13-3]]

^<<v66-13-3,3>>^ Uma das cabeças da besta parecia ter sofrido um ferimento mortal, mas o ferimento mortal foi curado. Todo o mundo ficou maravilhado e seguiu a besta.

[[v66-13-4]]

^<<v66-13-4,4>>^ Adoraram o dragão, que tinha dado autoridade à besta, e também adoraram a besta, dizendo: "Quem é como a besta? Quem pode guerrear contra ela? "

[[v66-13-5]]

^<<v66-13-5,5>>^ À besta foi dada uma boca para falar palavras arrogantes e blasfemas, e lhe foi dada autoridade para agir durante quarenta e dois meses.

[[v66-13-6]]

^<<v66-13-6,6>>^ Ela abriu a boca para blasfemar contra Deus e amaldiçoar o seu nome e o seu tabernáculo, os que habitam no céu.

[[v66-13-7]]

^<<v66-13-7,7>>^ Foi-lhe dado poder para guerrear contra os santos e vencê-los. Foi-lhe dada autoridade sobre toda tribo, povo, língua e nação.

[[v66-13-8]]

^<<v66-13-8,8>>^ Todos os habitantes da terra adorarão a besta, a saber, todos aqueles que não tiveram seus nomes escritos no livro da vida do Cordeiro que foi morto desde a criação do mundo.

[[v66-13-9]]

^<<v66-13-9,9>>^ Aquele que tem ouvidos ouça:

[[v66-13-10]]

^<<v66-13-10,10>>^ Se alguém há de ir para o cativeiro, para o cativeiro irá. Se alguém há de ser morto à espada, à espada haverá de ser morto. Aqui estão a perseverança e a fidelidade dos santos.

[[v66-13-11]]

^<<v66-13-11,11>>^ Então vi outra besta que saía da terra, com dois chifres como cordeiro, mas que falava como dragão.

[[v66-13-12]]

^<<v66-13-12,12>>^ Exercia toda a autoridade da primeira besta, em nome dela, e fazia a terra e seus habitantes adorarem a primeira besta, cujo ferimento mortal havia sido curado.

[[v66-13-13]]

^<<v66-13-13,13>>^ E realizava grandes sinais, chegando a fazer descer fogo do céu à terra, à vista dos homens.

[[v66-13-14]]

^<<v66-13-14,14>>^ Por causa dos sinais que lhe foi permitido realizar em nome da primeira besta, ela enganou os habitantes da terra. Ordenou-lhes que fizessem uma imagem em honra da besta que fora ferida pela espada e contudo revivera.

[[v66-13-15]]

^<<v66-13-15,15>>^ Foi-lhe dado poder para dar fôlego à imagem da primeira besta, de modo que ela podia falar e fazer que fossem mortos todos os que se recusassem a adorar a imagem.

[[v66-13-16]]

^<<v66-13-16,16>>^ Também obrigou todos, pequenos e grandes, ricos e pobres, livres e escravos, a receberem certa marca na mão direita ou na testa,

[[v66-13-17]]

^<<v66-13-17,17>>^ para que ninguém pudesse comprar nem vender, a não ser quem tivesse a marca, que é o nome da besta ou o número do seu nome.

[[v66-13-18]]

^<<v66-13-18,18>>^ Aqui há sabedoria. Aquele que tem entendimento calcule o número da besta, pois é número de homem. Seu número é seiscentos e sessenta e seis.

'''

xref:066-apocalipse/066-apocalipse-012.adoc#v66-12-0[&#60; Capítulo Anterior] | <<v66-13-0,Topo>> | xref:066-apocalipse/066-apocalipse-014.adoc#v66-14-0[Próximo Capítulo &#62;]