include::./index.adoc[]

[[v66-10-0]]
=== Apocalipse, 10
// nvi ?, NVI - Nova Versão Internacional

[[v66-10-1]]

^<<v66-10-1,1>>^ Então vi outro anjo poderoso, que descia do céu. Ele estava envolto numa nuvem, e havia um arco-íris acima de sua cabeça. Sua face era como o sol, e suas pernas eram como colunas de fogo.

[[v66-10-2]]

^<<v66-10-2,2>>^ E ele segurava um livrinho, que estava aberto em sua mão. Colocou o pé direito sobre o mar e o pé esquerdo sobre a terra,

[[v66-10-3]]

^<<v66-10-3,3>>^ e deu um alto brado, como o rugido de um leão. Quando ele bradou, os sete trovões falaram.

[[v66-10-4]]

^<<v66-10-4,4>>^ Logo que os sete trovões falaram, eu estava prestes a escrever, mas ouvi uma voz do céu, que disse: "Sele o que disseram os sete trovões, e não o escreva".

[[v66-10-5]]

^<<v66-10-5,5>>^ Então o anjo que eu tinha visto de pé sobre o mar e sobre a terra levantou a mão direita para o céu

[[v66-10-6]]

^<<v66-10-6,6>>^ e jurou por aquele que vive para todo o sempre, que criou os céus e tudo o que neles há, a terra e tudo o que nela há, e o mar e tudo o que nele há, dizendo: "Não haverá mais demora!

[[v66-10-7]]

^<<v66-10-7,7>>^ Mas, nos dias em que o sétimo anjo estiver para tocar sua trombeta, vai se cumprir o mistério de Deus, da forma como ele o anunciou aos seus servos, os profetas".

[[v66-10-8]]

^<<v66-10-8,8>>^ Depois falou comigo mais uma vez a voz que eu tinha ouvido falar do céu: "Vá, pegue o livro aberto que está na mão do anjo que se encontra de pé sobre o mar e sobre a terra".

[[v66-10-9]]

^<<v66-10-9,9>>^ Assim me aproximei do anjo e lhe pedi que me desse o livrinho. Ele me disse: "Pegue-o e coma-o! Ele será amargo em seu estômago, mas em sua boca será doce como mel".

[[v66-10-10]]

^<<v66-10-10,10>>^ Peguei o livrinho da mão do anjo e o comi. Ele me pareceu doce como mel em minha boca; mas, ao comê-lo, senti que o meu estômago ficou amargo.

[[v66-10-11]]

^<<v66-10-11,11>>^ Então me foi dito: "É preciso que você profetize de novo acerca de muitos povos, nações, línguas e reis".

'''

xref:066-apocalipse/066-apocalipse-009.adoc#v66-9-0[&#60; Capítulo Anterior] | <<v66-10-0,Topo>> | xref:066-apocalipse/066-apocalipse-011.adoc#v66-11-0[Próximo Capítulo &#62;]