include::./index.adoc[]

[[v66-9-0]]
=== Apocalipse, 9
// nvi ?, NVI - Nova Versão Internacional

[[v66-9-1]]

^<<v66-9-1,1>>^ O quinto anjo tocou a sua trombeta, e vi uma estrela que havia caído do céu sobre a terra. À estrela foi dada a chave do poço do Abismo.

[[v66-9-2]]

^<<v66-9-2,2>>^ Quando ela abriu o Abismo, subiu dele fumaça como a de uma gigantesca fornalha. O sol e o céu escureceram com a fumaça que saía do abismo.

[[v66-9-3]]

^<<v66-9-3,3>>^ Da fumaça saíram gafanhotos que vieram sobre a terra, e lhes foi dado poder como o dos escorpiões da terra.

[[v66-9-4]]

^<<v66-9-4,4>>^ Eles receberam ordens para não causar dano nem à relva da terra nem a qualquer planta ou árvore, mas apenas àqueles que não tinham o selo de Deus na testa.

[[v66-9-5]]

^<<v66-9-5,5>>^ Não lhes foi dado poder para matá-los, mas sim para causar-lhes tormento durante cinco meses. A agonia que eles sofreram era como a da picada do escorpião.

[[v66-9-6]]

^<<v66-9-6,6>>^ Naqueles dias os homens procurarão a morte, mas não a encontrarão; desejarão morrer, mas a morte fugirá deles.

[[v66-9-7]]

^<<v66-9-7,7>>^ Os gafanhotos pareciam cavalos preparados para a batalha. Tinham sobre a cabeça algo como coroas de ouro, e o rosto deles parecia rosto humano.

[[v66-9-8]]

^<<v66-9-8,8>>^ Os cabelos deles eram como os de mulheres e os dentes como os de leão.

[[v66-9-9]]

^<<v66-9-9,9>>^ Tinham couraças como couraças de ferro, e o som das suas asas era como o barulho de muitos cavalos e carruagens correndo para a batalha.

[[v66-9-10]]

^<<v66-9-10,10>>^ Tinham caudas e ferrões como de escorpiões, e na cauda tinham poder para causar tormento aos homens durante cinco meses.

[[v66-9-11]]

^<<v66-9-11,11>>^ Tinham um rei sobre eles, o anjo do Abismo, cujo nome, em hebraico, é Abadom, e, em grego, Apoliom.

[[v66-9-12]]

^<<v66-9-12,12>>^ O primeiro ai passou; dois outros ais ainda estão por vir.

[[v66-9-13]]

^<<v66-9-13,13>>^ O sexto anjo tocou a sua trombeta, e ouvi uma voz que vinha das pontas do altar de ouro que está diante de Deus.

[[v66-9-14]]

^<<v66-9-14,14>>^ Ela disse ao sexto anjo que tinha a trombeta: "Solte os quatro anjos que estão amarrados junto ao grande rio Eufrates".

[[v66-9-15]]

^<<v66-9-15,15>>^ Os quatro anjos, que estavam preparados para aquela hora, dia, mês e ano, foram soltos para matar um terço da humanidade.

[[v66-9-16]]

^<<v66-9-16,16>>^ O número dos cavaleiros que compunham os exércitos era de duzentos milhões; eu ouvi o seu número.

[[v66-9-17]]

^<<v66-9-17,17>>^ Os cavalos e os cavaleiros que vi em minha visão tinham este aspecto: as suas couraças eram vermelhas como o fogo, azul-escuras, e amarelas como o enxofre. A cabeça dos cavalos parecia a cabeça de um leão, e da boca lançavam fogo, fumaça e enxofre.

[[v66-9-18]]

^<<v66-9-18,18>>^ Um terço da humanidade foi morto pelas três pragas de fogo, fumaça e enxofre que saíam das suas bocas.

[[v66-9-19]]

^<<v66-9-19,19>>^ O poder dos cavalos estava na boca e na cauda; pois as suas caudas eram como cobras; tinham cabeças com as quais feriam as pessoas.

[[v66-9-20]]

^<<v66-9-20,20>>^ O restante da humanidade que não morreu por essas pragas, nem assim se arrependeu das obras das suas mãos; eles não pararam de adorar os demônios e os ídolos de ouro, prata, bronze, pedra e madeira, ídolos que não podem ver nem ouvir nem andar.

[[v66-9-21]]

^<<v66-9-21,21>>^ Também não se arrependeram dos seus assassinatos, das suas feitiçarias, da sua imoralidade sexual e dos seus roubos.

'''

xref:066-apocalipse/066-apocalipse-008.adoc#v66-8-0[&#60; Capítulo Anterior] | <<v66-9-0,Topo>> | xref:066-apocalipse/066-apocalipse-010.adoc#v66-10-0[Próximo Capítulo &#62;]