include::./index.adoc[]

[[v46-5-0]]
=== 1 Coríntios, 5
// nvi ?, NVI - Nova Versão Internacional

[[v46-5-1]]

^<<v46-5-1,1>>^ Por toda parte se ouve que há imoralidade entre vocês, imoralidade que não ocorre nem entre os pagãos, a ponto de alguém de vocês possuir a mulher de seu pai.

[[v46-5-2]]

^<<v46-5-2,2>>^ E vocês estão orgulhosos! Não deviam, porém, estar cheios de tristeza e expulsar da comunhão aquele que fez isso?

[[v46-5-3]]

^<<v46-5-3,3>>^ Apesar de eu não estar presente fisicamente, estou com vocês em espírito. E já condenei aquele que fez isso, como se estivesse presente.

[[v46-5-4]]

^<<v46-5-4,4>>^ Quando vocês estiverem reunidos em nome de nosso Senhor Jesus, estando eu com vocês em espírito, estando presente também o poder de nosso Senhor Jesus Cristo,

[[v46-5-5]]

^<<v46-5-5,5>>^ entreguem esse homem a Satanás, para que o corpo seja destruído, e seu espírito seja salvo no dia do Senhor.

[[v46-5-6]]

^<<v46-5-6,6>>^ O orgulho de vocês não é bom. Vocês não sabem que um pouco de fermento faz toda a massa ficar fermentada?

[[v46-5-7]]

^<<v46-5-7,7>>^ Livrem-se do fermento velho, para que sejam massa nova e sem fermento, como realmente são. Pois Cristo, nosso Cordeiro pascal, foi sacrificado.

[[v46-5-8]]

^<<v46-5-8,8>>^ Por isso, celebremos a festa, não com o fermento velho, nem com o fermento da maldade e da perversidade, mas com os pães sem fermento da sinceridade e da verdade.

[[v46-5-9]]

^<<v46-5-9,9>>^ Já lhes disse por carta que vocês não devem associar-se com pessoas imorais.

[[v46-5-10]]

^<<v46-5-10,10>>^ Com isso não me refiro aos imorais deste mundo, nem aos avarentos, aos ladrões ou aos idólatras. Se assim fosse, vocês precisariam sair deste mundo.

[[v46-5-11]]

^<<v46-5-11,11>>^ Mas agora estou lhes escrevendo que não devem associar-se com qualquer que, dizendo-se irmão, seja imoral, avarento, idólatra, caluniador, alcoólatra ou ladrão. Com tais pessoas vocês nem devem comer.

[[v46-5-12]]

^<<v46-5-12,12>>^ Pois, como haveria eu de julgar os de fora da igreja? Não devem vocês julgar os que estão dentro?

[[v46-5-13]]

^<<v46-5-13,13>>^ Deus julgará os de fora. "Expulsem esse perverso do meio de vocês".

'''

xref:046-1-corintios/046-1-corintios-004.adoc#v46-4-0[&#60; Capítulo Anterior] | <<v46-5-0,Topo>> | xref:046-1-corintios/046-1-corintios-006.adoc#v46-6-0[Próximo Capítulo &#62;]