include::./index.adoc[]

[[v46-9-0]]
=== 1 Coríntios, 9
// nvi ?, NVI - Nova Versão Internacional

[[v46-9-1]]

^<<v46-9-1,1>>^ Não sou livre? Não sou apóstolo? Não vi Jesus, nosso Senhor? Não são vocês resultado do meu trabalho no Senhor?

[[v46-9-2]]

^<<v46-9-2,2>>^ Ainda que eu não seja apóstolo para outros, certamente o sou para vocês! Pois vocês são o selo do meu apostolado no Senhor.

[[v46-9-3]]

^<<v46-9-3,3>>^ Esta é minha defesa diante daqueles que me julgam.

[[v46-9-4]]

^<<v46-9-4,4>>^ Não temos nós o direito de comer e beber?

[[v46-9-5]]

^<<v46-9-5,5>>^ Não temos nós o direito de levar conosco uma esposa crente como fazem os outros apóstolos, os irmãos do Senhor e Pedro?

[[v46-9-6]]

^<<v46-9-6,6>>^ Ou será que apenas eu e Barnabé não temos o direito de deixar de trabalhar para termos sustento?

[[v46-9-7]]

^<<v46-9-7,7>>^ Quem serve como soldado às suas próprias custas? Quem planta uma vinha e não come do seu fruto? Quem apascenta um rebanho e não bebe do seu leite?

[[v46-9-8]]

^<<v46-9-8,8>>^ Não digo isso do ponto de vista meramente humano; a Lei não diz a mesma coisa?

[[v46-9-9]]

^<<v46-9-9,9>>^ Pois está escrito na Lei de Moisés: "Não amordace o boi enquanto ele estiver debulhando o cereal". Por acaso é com bois que Deus está preocupado?

[[v46-9-10]]

^<<v46-9-10,10>>^ Não é certamente por nossa causa que ele o diz? Sim, isso foi escrito em nosso favor. Porque "o lavrador quando ara e o debulhador quando debulha, devem fazê-lo na esperança de participar da colheita".

[[v46-9-11]]

^<<v46-9-11,11>>^ Se entre vocês semeamos coisas espirituais, seria demais colhermos de vocês coisas materiais?

[[v46-9-12]]

^<<v46-9-12,12>>^ Se outros têm direito de ser sustentados por vocês, não o temos nós ainda mais? Mas nós nunca usamos desse direito. Pelo contrário, suportamos tudo para não colocar obstáculo algum ao evangelho de Cristo.

[[v46-9-13]]

^<<v46-9-13,13>>^ Vocês não sabem que aqueles que trabalham no templo alimentam-se das coisas do templo, e que os que servem diante do altar participam do que é oferecido no altar?

[[v46-9-14]]

^<<v46-9-14,14>>^ Da mesma forma o Senhor ordenou àqueles que pregam o evangelho, que vivam do evangelho.

[[v46-9-15]]

^<<v46-9-15,15>>^ Mas eu não tenho usado de nenhum desses direitos. Não estou escrevendo na esperança de que vocês façam isso por mim. Prefiro morrer a permitir que alguém me prive deste meu orgulho.

[[v46-9-16]]

^<<v46-9-16,16>>^ Contudo, quando prego o evangelho, não posso me orgulhar, pois me é imposta a necessidade de pregar. Ai de mim se não pregar o evangelho!

[[v46-9-17]]

^<<v46-9-17,17>>^ Porque, se prego de livre vontade, tenho recompensa; contudo, como prego por obrigação, estou simplesmente cumprindo uma incumbência a mim confiada.

[[v46-9-18]]

^<<v46-9-18,18>>^ Qual é, pois, a minha recompensa? Apenas esta: que, pregando o evangelho, eu o apresente gratuitamente, não usando, assim, dos meus direitos ao pregá-lo.

[[v46-9-19]]

^<<v46-9-19,19>>^ Porque, embora seja livre de todos, fiz-me escravo de todos, para ganhar o maior número possível de pessoas.

[[v46-9-20]]

^<<v46-9-20,20>>^ Tornei-me judeu para os judeus, a fim de ganhar os judeus. Para os que estão debaixo da lei, tornei-me como se estivesse sujeito à lei, ( embora eu mesmo não esteja debaixo da lei ), a fim de ganhar os que estão debaixo da lei.

[[v46-9-21]]

^<<v46-9-21,21>>^ Para os que estão sem lei, tornei-me como sem lei ( embora não esteja livre da lei de Deus, mas sim sob a lei de Cristo ), a fim de ganhar os que não têm a lei.

[[v46-9-22]]

^<<v46-9-22,22>>^ Para com os fracos tornei-me fraco, para ganhar os fracos. Tornei-me tudo para com todos, para de alguma forma salvar alguns.

[[v46-9-23]]

^<<v46-9-23,23>>^ Faço tudo isso por causa do evangelho, para ser co-participante dele.

[[v46-9-24]]

^<<v46-9-24,24>>^ Vocês não sabem que dentre todos os que correm no estádio, apenas um ganha o prêmio? Corram de tal modo que alcancem o prêmio.

[[v46-9-25]]

^<<v46-9-25,25>>^ Todos os que competem nos jogos se submetem a um treinamento rigoroso, para obter uma coroa que logo perece; mas nós o fazemos para ganhar uma coroa que dura para sempre.

[[v46-9-26]]

^<<v46-9-26,26>>^ Sendo assim, não corro como quem corre sem alvo, e não luto como quem esmurra o ar.

[[v46-9-27]]

^<<v46-9-27,27>>^ Mas esmurro o meu corpo e faço dele meu escravo, para que, depois de ter pregado aos outros, eu mesmo não venha a ser reprovado.

'''

xref:046-1-corintios/046-1-corintios-008.adoc#v46-8-0[&#60; Capítulo Anterior] | <<v46-9-0,Topo>> | xref:046-1-corintios/046-1-corintios-010.adoc#v46-10-0[Próximo Capítulo &#62;]