include::./index.adoc[]

[[v46-2-0]]
=== 1 Coríntios, 2
// nvi ?, NVI - Nova Versão Internacional

[[v46-2-1]]

^<<v46-2-1,1>>^ Eu mesmo, irmãos, quando estive entre vocês, não fui com discurso eloqüente nem com muita sabedoria para lhes proclamar o mistério de Deus.

[[v46-2-2]]

^<<v46-2-2,2>>^ Pois decidi nada saber entre vocês, a não ser Jesus Cristo, e este, crucificado.

[[v46-2-3]]

^<<v46-2-3,3>>^ E foi com fraqueza, temor e com muito tremor que estive entre vocês.

[[v46-2-4]]

^<<v46-2-4,4>>^ Minha mensagem e minha pregação não consistiram de palavras persuasivas de sabedoria, mas consistiram de demonstração do poder do Espírito,

[[v46-2-5]]

^<<v46-2-5,5>>^ para que a fé que vocês têm não se baseasse na sabedoria humana, mas no poder de Deus.

[[v46-2-6]]

^<<v46-2-6,6>>^ Entretanto, falamos de sabedoria entre os maduros, mas não da sabedoria desta era ou dos poderosos desta era, que estão sendo reduzidos a nada.

[[v46-2-7]]

^<<v46-2-7,7>>^ Pelo contrário, falamos da sabedoria de Deus, do mistério que estava oculto, o qual Deus preordenou, antes do princípio das eras, para a nossa glória.

[[v46-2-8]]

^<<v46-2-8,8>>^ Nenhum dos poderosos desta era o entendeu, pois, se o tivessem entendido, não teriam crucificado o Senhor da glória.

[[v46-2-9]]

^<<v46-2-9,9>>^ Todavia, como está escrito: "Olho nenhum viu, ouvido nenhum ouviu, mente nenhuma imaginou o que Deus preparou para aqueles que o amam";

[[v46-2-10]]

^<<v46-2-10,10>>^ mas Deus o revelou a nós por meio do Espírito. O Espírito sonda todas as coisas, até mesmo as coisas mais profundas de Deus.

[[v46-2-11]]

^<<v46-2-11,11>>^ Pois, quem dentre os homens conhece as coisas do homem, a não ser o espírito do homem que nele está? Da mesma forma, ninguém conhece as coisas de Deus, a não ser o Espírito de Deus.

[[v46-2-12]]

^<<v46-2-12,12>>^ Nós, porém, não recebemos o espírito do mundo, mas o Espírito procedente de Deus, para que entendamos as coisas que Deus nos tem dado gratuitamente.

[[v46-2-13]]

^<<v46-2-13,13>>^ Delas também falamos, não com palavras ensinadas pela sabedoria humana, mas com palavras ensinadas pelo Espírito, interpretando verdades espirituais para os que são espirituais.

[[v46-2-14]]

^<<v46-2-14,14>>^ Quem não tem o Espírito não aceita as coisas que vêm do Espírito de Deus, pois lhe são loucura; e não é capaz de entendê-las, porque elas são discernidas espiritualmente.

[[v46-2-15]]

^<<v46-2-15,15>>^ Mas quem é espiritual discerne todas as coisas, e ele mesmo por ninguém é discernido; pois

[[v46-2-16]]

^<<v46-2-16,16>>^ "quem conheceu a mente do Senhor para que possa instruí-lo? " Nós, porém, temos a mente de Cristo.

'''

xref:046-1-corintios/046-1-corintios-001.adoc#v46-1-0[&#60; Capítulo Anterior] | <<v46-2-0,Topo>> | xref:046-1-corintios/046-1-corintios-003.adoc#v46-3-0[Próximo Capítulo &#62;]