include::./index.adoc[]

[[v46-8-0]]
=== 1 Coríntios, 8
// nvi ?, NVI - Nova Versão Internacional

[[v46-8-1]]

^<<v46-8-1,1>>^ Com respeito aos alimentos sacrificados aos ídolos, sabemos que todos temos conhecimento. O conhecimento traz orgulho, mas o amor edifica.

[[v46-8-2]]

^<<v46-8-2,2>>^ Quem pensa conhecer alguma coisa, ainda não conhece como deveria.

[[v46-8-3]]

^<<v46-8-3,3>>^ Mas quem ama a Deus, este é conhecido por Deus.

[[v46-8-4]]

^<<v46-8-4,4>>^ Portanto, em relação ao alimento sacrificado aos ídolos, sabemos que o ídolo não significa nada no mundo e que só existe um Deus.

[[v46-8-5]]

^<<v46-8-5,5>>^ Pois mesmo que haja os chamados deuses, quer no céu, quer na terra, ( como de fato há muitos "deuses" e muitos "senhores" ),

[[v46-8-6]]

^<<v46-8-6,6>>^ para nós, porém, há um único Deus, o Pai, de quem vêm todas as coisas e para quem vivemos; e um só Senhor, Jesus Cristo, por meio de quem vieram todas as coisas e por meio de quem vivemos.

[[v46-8-7]]

^<<v46-8-7,7>>^ Contudo, nem todos têm esse conhecimento. Alguns, ainda habituados com os ídolos, comem esse alimento como se fosse um sacrifício idólatra; e como a consciência deles é fraca, esta fica contaminada.

[[v46-8-8]]

^<<v46-8-8,8>>^ A comida, porém, não nos torna aceitáveis diante de Deus; não seremos piores se não comermos, nem melhores se comermos.

[[v46-8-9]]

^<<v46-8-9,9>>^ Contudo, tenham cuidado para que o exercício da liberdade de vocês não se torne uma pedra de tropeço para os fracos.

[[v46-8-10]]

^<<v46-8-10,10>>^ Pois, se alguém que tem a consciência fraca vir você que tem este conhecimento comer num templo de ídolos, não será induzido a comer do que foi sacrificado a ídolos?

[[v46-8-11]]

^<<v46-8-11,11>>^ Assim, esse irmão fraco, por quem Cristo morreu, é destruído por causa do conhecimento que você tem.

[[v46-8-12]]

^<<v46-8-12,12>>^ Quando você peca contra seus irmãos dessa maneira, ferindo a consciência fraca deles, peca contra Cristo.

[[v46-8-13]]

^<<v46-8-13,13>>^ Portanto, se aquilo que eu como leva o meu irmão a pecar, nunca mais comerei carne, para não fazer meu irmão tropeçar.

'''

xref:046-1-corintios/046-1-corintios-007.adoc#v46-7-0[&#60; Capítulo Anterior] | <<v46-8-0,Topo>> | xref:046-1-corintios/046-1-corintios-009.adoc#v46-9-0[Próximo Capítulo &#62;]