include::./index.adoc[]

[[v46-1-0]]
=== 1 Coríntios, 1
// nvi ?, NVI - Nova Versão Internacional

[[v46-1-1]]

^<<v46-1-1,1>>^ Paulo, chamado para ser apóstolo de Cristo Jesus pela vontade de Deus, e o irmão Sóstenes,

[[v46-1-2]]

^<<v46-1-2,2>>^ à igreja de Deus que está em Corinto, aos santificados em Cristo Jesus e chamados para serem santos, juntamente com todos os que, em toda parte, invocam o nome de nosso Senhor Jesus Cristo, Senhor deles e nosso:

[[v46-1-3]]

^<<v46-1-3,3>>^ A vocês, graça e paz da parte de Deus nosso Pai e do Senhor Jesus Cristo.

[[v46-1-4]]

^<<v46-1-4,4>>^ Sempre dou graças a meu Deus por vocês, por causa da graça que lhes foi dada por ele em Cristo Jesus.

[[v46-1-5]]

^<<v46-1-5,5>>^ Pois nele vocês foram enriquecidos em tudo, em toda palavra e em todo conhecimento,

[[v46-1-6]]

^<<v46-1-6,6>>^ porque o testemunho de Cristo foi confirmado entre vocês,

[[v46-1-7]]

^<<v46-1-7,7>>^ de modo que não lhes falta nenhum dom espiritual, enquanto vocês aguardam que o nosso Senhor Jesus Cristo seja revelado.

[[v46-1-8]]

^<<v46-1-8,8>>^ Ele os manterá firmes até o fim, de modo que vocês serão irrepreensíveis no dia de nosso Senhor Jesus Cristo.

[[v46-1-9]]

^<<v46-1-9,9>>^ Fiel é Deus, o qual os chamou à comunhão com seu Filho Jesus Cristo, nosso Senhor.

[[v46-1-10]]

^<<v46-1-10,10>>^ Irmãos, em nome de nosso Senhor Jesus Cristo suplico a todos vocês que concordem uns com os outros no que falam, para que não haja divisões entre vocês, e, sim, que todos estejam unidos num só pensamento e num só parecer.

[[v46-1-11]]

^<<v46-1-11,11>>^ Meus irmãos, fui informado por alguns da casa de Cloe de que há divisões entre vocês.

[[v46-1-12]]

^<<v46-1-12,12>>^ Com isso quero dizer que cada um de vocês afirma: "Eu sou de Paulo"; "eu de Apolo"; "eu de Pedro"; e "eu de Cristo".

[[v46-1-13]]

^<<v46-1-13,13>>^ Acaso Cristo está dividido? Foi Paulo crucificado em favor de vocês? Foram vocês batizados em nome de Paulo?

[[v46-1-14]]

^<<v46-1-14,14>>^ Dou graças a Deus por não ter batizado nenhum de vocês, exceto Crispo e Gaio;

[[v46-1-15]]

^<<v46-1-15,15>>^ de modo que ninguém pode dizer que foi batizado em meu nome.

[[v46-1-16]]

^<<v46-1-16,16>>^ ( Batizei também os da casa de Estéfanas; além destes, não me lembro se batizei alguém mais. )

[[v46-1-17]]

^<<v46-1-17,17>>^ Pois Cristo não me enviou para batizar, mas para pregar o evangelho, não com palavras de sabedoria humana, para que a cruz de Cristo não seja esvaziada. Cristo, Sabedoria e Poder de Deus

[[v46-1-18]]

^<<v46-1-18,18>>^ Pois a mensagem da cruz é loucura para os que estão perecendo, mas para nós, que estamos sendo salvos, é o poder de Deus.

[[v46-1-19]]

^<<v46-1-19,19>>^ Pois está escrito: "Destruirei a sabedoria dos sábios e rejeitarei a inteligência dos inteligentes".

[[v46-1-20]]

^<<v46-1-20,20>>^ Onde está o sábio? Onde está o erudito? Onde está o questionador desta era? Acaso não tornou Deus louca a sabedoria deste mundo?

[[v46-1-21]]

^<<v46-1-21,21>>^ Visto que, na sabedoria de Deus, o mundo não o conheceu por meio da sabedoria humana, agradou a Deus salvar aqueles que crêem por meio da loucura da pregação.

[[v46-1-22]]

^<<v46-1-22,22>>^ Os judeus pedem sinais miraculosos, e os gregos procuram sabedoria;

[[v46-1-23]]

^<<v46-1-23,23>>^ nós, porém, pregamos a Cristo crucificado, o qual, de fato, é escândalo para os judeus e loucura para os gentios

[[v46-1-24]]

^<<v46-1-24,24>>^ mas para os que foram chamados, tanto judeus como gregos, Cristo é o poder de Deus e a sabedoria de Deus.

[[v46-1-25]]

^<<v46-1-25,25>>^ Porque a loucura de Deus é mais sábia que a sabedoria humana, e a fraqueza de Deus é mais forte que a força do homem.

[[v46-1-26]]

^<<v46-1-26,26>>^ Irmãos, pensem no que vocês eram quando foram chamados. Poucos eram sábios segundo os padrões humanos; poucos eram poderosos; poucos eram de nobre nascimento.

[[v46-1-27]]

^<<v46-1-27,27>>^ Mas Deus escolheu as coisas loucas do mundo para envergonhar os sábios, e escolheu as coisas fracas do mundo para envergonhar as fortes.

[[v46-1-28]]

^<<v46-1-28,28>>^ Ele escolheu as coisas insignificantes do mundo, as desprezadas e as que nada são, para reduzir a nada as que são,

[[v46-1-29]]

^<<v46-1-29,29>>^ para que ninguém se vanglorie diante dele.

[[v46-1-30]]

^<<v46-1-30,30>>^ É, porém, por iniciativa dele que vocês estão em Cristo Jesus, o qual se tornou sabedoria de Deus para nós, isto é, justiça, santidade e redenção,

[[v46-1-31]]

^<<v46-1-31,31>>^ para que, como está escrito: "Quem se gloriar, glorie-se no Senhor".

'''

xref:045-romanos/045-romanos-016.adoc#v45-16-0[&#60; Capítulo Anterior] | <<v46-1-0,Topo>> | xref:046-1-corintios/046-1-corintios-002.adoc#v46-2-0[Próximo Capítulo &#62;]