include::./index.adoc[]

[[v46-7-0]]
=== 1 Coríntios, 7
// nvi ?, NVI - Nova Versão Internacional

[[v46-7-1]]

^<<v46-7-1,1>>^ Quanto aos assuntos sobre os quais vocês escreveram, é bom que o homem não toque em mulher,

[[v46-7-2]]

^<<v46-7-2,2>>^ mas, por causa da imoralidade, cada um deve ter sua esposa, e cada mulher o seu próprio marido.

[[v46-7-3]]

^<<v46-7-3,3>>^ O marido deve cumprir os seus deveres conjugais para com a sua mulher, e da mesma forma a mulher para com o seu marido.

[[v46-7-4]]

^<<v46-7-4,4>>^ A mulher não tem autoridade sobre o seu próprio corpo, mas sim o marido. Da mesma forma, o marido não tem autoridade sobre o seu próprio corpo, mas sim a mulher.

[[v46-7-5]]

^<<v46-7-5,5>>^ Não se recusem um ao outro, exceto por mútuo consentimento e durante certo tempo, para se dedicarem à oração. Depois, unam-se de novo, para que Satanás não os tente por não terem domínio próprio.

[[v46-7-6]]

^<<v46-7-6,6>>^ Digo isso como concessão, e não como mandamento.

[[v46-7-7]]

^<<v46-7-7,7>>^ Gostaria que todos os homens fossem como eu; mas cada um tem o seu próprio dom da parte de Deus; um de um modo, outro de outro.

[[v46-7-8]]

^<<v46-7-8,8>>^ Digo, porém, aos solteiros e às viúvas: é bom que permaneçam como eu.

[[v46-7-9]]

^<<v46-7-9,9>>^ Mas, se não conseguem controlar-se, devem casar-se, pois é melhor casar-se do que ficar ardendo de desejo.

[[v46-7-10]]

^<<v46-7-10,10>>^ Aos casados dou este mandamento, não eu, mas o Senhor: que a esposa não se separe do seu marido.

[[v46-7-11]]

^<<v46-7-11,11>>^ Mas, se o fizer, que permaneça sem se casar ou, então, reconcilie-se com o seu marido. E o marido não se divorcie da sua mulher.

[[v46-7-12]]

^<<v46-7-12,12>>^ Aos outros eu mesmo digo isto, e não o Senhor: se um irmão tem mulher descrente, e ela se dispõe a viver com ele, não se divorcie dela.

[[v46-7-13]]

^<<v46-7-13,13>>^ E, se uma mulher tem marido descrente, e ele se dispõe a viver com ela, não se divorcie dele.

[[v46-7-14]]

^<<v46-7-14,14>>^ Pois o marido descrente é santificado por meio da mulher, e a mulher descrente é santificada por meio do marido. Se assim não fosse, seus filhos seriam impuros, mas agora são santos.

[[v46-7-15]]

^<<v46-7-15,15>>^ Todavia, se o descrente separar-se, que se separe. Em tais casos, o irmão ou a irmã não fica debaixo de servidão; Deus nos chamou para vivermos em paz.

[[v46-7-16]]

^<<v46-7-16,16>>^ Você, mulher, como sabe se salvará seu marido? Ou você, marido, como sabe se salvará sua mulher?

[[v46-7-17]]

^<<v46-7-17,17>>^ Entretanto, cada um continue vivendo na condição que o Senhor lhe designou e de acordo com o chamado de Deus. Esta é a minha ordem para todas as igrejas.

[[v46-7-18]]

^<<v46-7-18,18>>^ Foi alguém chamado sendo já circunciso? Não desfaça a sua circuncisão. Foi alguém chamado sendo incircunciso? Não se circuncide.

[[v46-7-19]]

^<<v46-7-19,19>>^ A circuncisão não significa nada, e a incircuncisão também nada é; o que importa é obedecer aos mandamentos de Deus.

[[v46-7-20]]

^<<v46-7-20,20>>^ Cada um deve permanecer na condição em que foi chamado por Deus.

[[v46-7-21]]

^<<v46-7-21,21>>^ Foi você chamado sendo escravo? Não se incomode com isso. Mas, se você puder conseguir a liberdade, consiga-a.

[[v46-7-22]]

^<<v46-7-22,22>>^ Pois aquele que, sendo escravo, foi chamado pelo Senhor, é liberto e pertence ao Senhor; semelhantemente, aquele que era livre quando foi chamado, é escravo de Cristo.

[[v46-7-23]]

^<<v46-7-23,23>>^ Vocês foram comprados por alto preço; não se tornem escravos de homens.

[[v46-7-24]]

^<<v46-7-24,24>>^ Irmãos, cada um deve permanecer diante de Deus na condição em que foi chamado.

[[v46-7-25]]

^<<v46-7-25,25>>^ Quanto às pessoas virgens, não tenho mandamento do Senhor, mas dou meu parecer como alguém que, pela misericórdia de Deus, é digno de confiança.

[[v46-7-26]]

^<<v46-7-26,26>>^ Por causa dos problemas atuais, penso que é melhor o homem permanecer como está.

[[v46-7-27]]

^<<v46-7-27,27>>^ Você está casado? Não procure separar-se. Está solteiro? Não procure esposa.

[[v46-7-28]]

^<<v46-7-28,28>>^ Mas, se vier a casar-se, não comete pecado; e, se uma virgem se casar, também não comete pecado. Mas aqueles que se casarem enfrentarão muitas dificuldades na vida, e eu gostaria de poupá-los disso.

[[v46-7-29]]

^<<v46-7-29,29>>^ O que quero dizer é que o tempo é pouco. De agora em diante, aqueles que têm esposa, vivam como se não tivessem;

[[v46-7-30]]

^<<v46-7-30,30>>^ aqueles que choram, como se não chorassem; os que estão felizes, como se não estivessem; os que compram algo, como se nada possuíssem;

[[v46-7-31]]

^<<v46-7-31,31>>^ os que usam as coisas do mundo, como se não as usassem; porque a forma presente deste mundo está passando.

[[v46-7-32]]

^<<v46-7-32,32>>^ Gostaria de vê-los livres de preocupações. O homem que não é casado preocupa-se com as coisas do Senhor, em como agradar ao Senhor.

[[v46-7-33]]

^<<v46-7-33,33>>^ Mas o homem casado preocupa-se com as coisas deste mundo, em como agradar sua mulher,

[[v46-7-34]]

^<<v46-7-34,34>>^ e está dividido. Tanto a mulher não casada como a virgem preocupam-se com as coisas do Senhor, para serem santas no corpo e no espírito. Mas a casada preocupa-se com as coisas deste mundo, em como agradar seu marido.

[[v46-7-35]]

^<<v46-7-35,35>>^ Estou dizendo isso para o próprio bem de vocês; não para lhes impor restrições, mas para que vocês possam viver de maneira correta, em plena consagração ao Senhor.

[[v46-7-36]]

^<<v46-7-36,36>>^ Se alguém acha que não está tratando sua filha como é devido e que ela está numa idade madura, pelo que ele se sente obrigado a casá-la, faça como achar melhor. Com isso não peca. Deve permitir que se case.

[[v46-7-37]]

^<<v46-7-37,37>>^ Contudo, o que se mantém firme no seu propósito e não é dominado por seus impulsos mas domina sua própria vontade, e resolveu manter solteira sua filha, este também faz bem.

[[v46-7-38]]

^<<v46-7-38,38>>^ De modo que aquele que dá sua filha em casamento faz bem, mas o que não a dá em casamento faz melhor.

[[v46-7-39]]

^<<v46-7-39,39>>^ A mulher está ligada a seu marido enquanto ele viver. Mas, se o seu marido morrer, ela estará livre para se casar com quem quiser, contanto que ele pertença ao Senhor.

[[v46-7-40]]

^<<v46-7-40,40>>^ Em meu parecer, ela será mais feliz se permanecer como está; e penso que também tenho o Espírito de Deus.

'''

xref:046-1-corintios/046-1-corintios-006.adoc#v46-6-0[&#60; Capítulo Anterior] | <<v46-7-0,Topo>> | xref:046-1-corintios/046-1-corintios-008.adoc#v46-8-0[Próximo Capítulo &#62;]