include::./index.adoc[]

[[v46-12-0]]
=== 1 Coríntios, 12
// nvi ?, NVI - Nova Versão Internacional

[[v46-12-1]]

^<<v46-12-1,1>>^ Irmãos, quanto aos dons espirituais, não quero que vocês sejam ignorantes.

[[v46-12-2]]

^<<v46-12-2,2>>^ Vocês sabem que, quando eram pagãos, de uma forma ou de outra eram fortemente atraídos e levados para os ídolos mudos.

[[v46-12-3]]

^<<v46-12-3,3>>^ Por isso, eu lhes afirmo que ninguém que fala pelo Espírito de Deus diz: "Jesus seja amaldiçoado"; e ninguém pode dizer: "Jesus é Senhor", a não ser pelo Espírito Santo.

[[v46-12-4]]

^<<v46-12-4,4>>^ Há diferentes tipos de dons, mas o Espírito é o mesmo.

[[v46-12-5]]

^<<v46-12-5,5>>^ Há diferentes tipos de ministérios, mas o Senhor é o mesmo.

[[v46-12-6]]

^<<v46-12-6,6>>^ Há diferentes formas de atuação, mas é o mesmo Deus quem efetua tudo em todos.

[[v46-12-7]]

^<<v46-12-7,7>>^ A cada um, porém, é dada a manifestação do Espírito, visando ao bem comum.

[[v46-12-8]]

^<<v46-12-8,8>>^ Pelo Espírito, a um é dada a palavra de sabedoria; a outro, a palavra de conhecimento, pelo mesmo Espírito;

[[v46-12-9]]

^<<v46-12-9,9>>^ a outro, fé, pelo mesmo Espírito; a outro, dons de cura, pelo único Espírito;

[[v46-12-10]]

^<<v46-12-10,10>>^ a outro, poder para operar milagres; a outro, profecia; a outro, discernimento de espíritos; a outro, variedade de línguas; e ainda a outro, interpretação de línguas.

[[v46-12-11]]

^<<v46-12-11,11>>^ Todas essas coisas, porém, são realizadas pelo mesmo e único Espírito, e ele as distribui individualmente, a cada um, conforme quer.

[[v46-12-12]]

^<<v46-12-12,12>>^ Ora, assim como o corpo é uma unidade, embora tenha muitos membros, e todos os membros, mesmo sendo muitos, formam um só corpo, assim também com respeito a Cristo.

[[v46-12-13]]

^<<v46-12-13,13>>^ Pois em um só corpo todos nós fomos batizados em um único Espírito: quer judeus, quer gregos, quer escravos, quer livres. E a todos nós foi dado beber de um único Espírito.

[[v46-12-14]]

^<<v46-12-14,14>>^ O corpo não é composto de um só membro, mas de muitos.

[[v46-12-15]]

^<<v46-12-15,15>>^ Se o pé disser: "Porque não sou mão, não pertenço ao corpo", nem por isso deixa de fazer parte do corpo.

[[v46-12-16]]

^<<v46-12-16,16>>^ E se o ouvido disser: "Porque não sou olho, não pertenço ao corpo", nem por isso deixa de fazer parte do corpo.

[[v46-12-17]]

^<<v46-12-17,17>>^ Se todo o corpo fosse olho, onde estaria a audição? Se todo o corpo fosse ouvido, onde estaria o olfato?

[[v46-12-18]]

^<<v46-12-18,18>>^ De fato, Deus dispôs cada um dos membros no corpo, segundo a sua vontade.

[[v46-12-19]]

^<<v46-12-19,19>>^ Se todos fossem um só membro, onde estaria o corpo?

[[v46-12-20]]

^<<v46-12-20,20>>^ Assim, há muitos membros, mas um só corpo.

[[v46-12-21]]

^<<v46-12-21,21>>^ O olho não pode dizer à mão: "Não preciso de você! " Nem a cabeça pode dizer aos pés: "Não preciso de vocês! "

[[v46-12-22]]

^<<v46-12-22,22>>^ Pelo contrário, os membros do corpo que parecem mais fracos são indispensáveis,

[[v46-12-23]]

^<<v46-12-23,23>>^ e os membros que pensamos serem menos honrosos, tratamos com especial honra. E os membros que em nós são indecorosos são tratados com decoro especial,

[[v46-12-24]]

^<<v46-12-24,24>>^ enquanto os que em nós são decorosos não precisam ser tratados de maneira especial. Mas Deus estruturou o corpo dando maior honra aos membros que dela tinham falta,

[[v46-12-25]]

^<<v46-12-25,25>>^ a fim de que não haja divisão no corpo, mas, sim, que todos os membros tenham igual cuidado uns pelos outros.

[[v46-12-26]]

^<<v46-12-26,26>>^ Quando um membro sofre, todos os outros sofrem com ele; quando um membro é honrado, todos os outros se alegram com ele.

[[v46-12-27]]

^<<v46-12-27,27>>^ Ora, vocês são o corpo de Cristo, e cada um de vocês, individualmente, é membro desse corpo.

[[v46-12-28]]

^<<v46-12-28,28>>^ Assim, na igreja, Deus estabeleceu primeiramente apóstolos; em segundo lugar, profetas; em terceiro lugar, mestres; depois os que realizam milagres, os que têm dom de curar, os que têm dom de prestar ajuda, os que têm dons de administração e os que falam diversas línguas.

[[v46-12-29]]

^<<v46-12-29,29>>^ São todos apóstolos? São todos profetas? São todos mestres? Têm todos o dom de realizar milagres?

[[v46-12-30]]

^<<v46-12-30,30>>^ Têm todos dons de curar? Falam todos em línguas? Todos interpretam?

[[v46-12-31]]

^<<v46-12-31,31>>^ Entretanto, busquem com dedicação os melhores dons. Passo agora a mostrar-lhes um caminho ainda mais excelente.

'''

xref:046-1-corintios/046-1-corintios-011.adoc#v46-11-0[&#60; Capítulo Anterior] | <<v46-12-0,Topo>> | xref:046-1-corintios/046-1-corintios-013.adoc#v46-13-0[Próximo Capítulo &#62;]