include::./index.adoc[]

[[v46-4-0]]
=== 1 Coríntios, 4
// nvi ?, NVI - Nova Versão Internacional

[[v46-4-1]]

^<<v46-4-1,1>>^ Portanto, que todos nos considerem como servos de Cristo e encarregados dos mistérios de Deus.

[[v46-4-2]]

^<<v46-4-2,2>>^ O que se requer destes encarregados é que sejam fiéis.

[[v46-4-3]]

^<<v46-4-3,3>>^ Pouco me importa ser julgado por vocês ou por qualquer tribunal humano; de fato, nem eu julgo a mim mesmo.

[[v46-4-4]]

^<<v46-4-4,4>>^ Embora em nada minha consciência me acuse, nem por isso justifico a mim mesmo; o Senhor é quem me julga.

[[v46-4-5]]

^<<v46-4-5,5>>^ Portanto, não julguem nada antes da hora devida; esperem até que o Senhor venha. Ele trará à luz o que está oculto nas trevas e manifestará as intenções dos corações. Nessa ocasião, cada um receberá de Deus a sua aprovação.

[[v46-4-6]]

^<<v46-4-6,6>>^ Irmãos, apliquei essas coisas a mim e a Apolo por amor a vocês, para que aprendam de nós o que significa: "Não ultrapassem o que está escrito". Assim, ninguém se orgulhe a favor de um homem em detrimento de outro.

[[v46-4-7]]

^<<v46-4-7,7>>^ Pois, quem torna você diferente de qualquer outra pessoa? O que você tem que não tenha recebido? E se o recebeu, por que se orgulha, como se assim não fosse?

[[v46-4-8]]

^<<v46-4-8,8>>^ Vocês já têm tudo o que querem! Já se tornaram ricos! Chegaram a ser reis — e sem nós! Como eu gostaria que vocês realmente fossem reis, para que nós também reinássemos com vocês!

[[v46-4-9]]

^<<v46-4-9,9>>^ Porque me parece que Deus nos colocou a nós, os apóstolos, em último lugar, como condenados à morte. Temo-nos tornado um espetáculo para o mundo, tanto diante de anjos como de homens.

[[v46-4-10]]

^<<v46-4-10,10>>^ Nós somos loucos por causa de Cristo, mas vocês são sensatos em Cristo! Nós somos fracos, mas vocês são fortes! Vocês são respeitados, mas nós somos desprezados!

[[v46-4-11]]

^<<v46-4-11,11>>^ Até agora estamos passando fome, sede e necessidade de roupas, estamos sendo tratados brutalmente, não temos residência certa e

[[v46-4-12]]

^<<v46-4-12,12>>^ trabalhamos arduamente com nossas próprias mãos. Quando somos amaldiçoados, abençoamos; quando perseguidos, suportamos;

[[v46-4-13]]

^<<v46-4-13,13>>^ quando caluniados, respondemos amavelmente. Até agora nos tornamos a escória da terra, o lixo do mundo.

[[v46-4-14]]

^<<v46-4-14,14>>^ Não estou tentando envergonhá-los ao escrever estas coisas, mas procuro adverti-los, como a meus filhos amados.

[[v46-4-15]]

^<<v46-4-15,15>>^ Embora possam ter dez mil tutores em Cristo, vocês não têm muitos pais, pois em Cristo Jesus eu mesmo os gerei por meio do evangelho.

[[v46-4-16]]

^<<v46-4-16,16>>^ Portanto, suplico-lhes que sejam meus imitadores.

[[v46-4-17]]

^<<v46-4-17,17>>^ Por essa razão estou lhes enviando Timóteo, meu filho amado e fiel no Senhor, o qual lhes trará à lembrança a minha maneira de viver em Cristo Jesus, de acordo com o que eu ensino por toda parte, em todas as igrejas.

[[v46-4-18]]

^<<v46-4-18,18>>^ Alguns de vocês se tornaram arrogantes, como se eu não fosse mais visitá-los.

[[v46-4-19]]

^<<v46-4-19,19>>^ Mas irei muito em breve, se o Senhor permitir; então saberei não apenas o que estão falando esses arrogantes, mas que poder eles têm.

[[v46-4-20]]

^<<v46-4-20,20>>^ Pois o Reino de Deus não consiste de palavras, mas de poder.

[[v46-4-21]]

^<<v46-4-21,21>>^ Que é que vocês querem? Devo ir a vocês com vara, ou com amor e espírito de mansidão?

'''

xref:046-1-corintios/046-1-corintios-003.adoc#v46-3-0[&#60; Capítulo Anterior] | <<v46-4-0,Topo>> | xref:046-1-corintios/046-1-corintios-005.adoc#v46-5-0[Próximo Capítulo &#62;]