include::./index.adoc[]

[[v46-11-0]]
=== 1 Coríntios, 11
// nvi ?, NVI - Nova Versão Internacional

[[v46-11-1]]

^<<v46-11-1,1>>^ Tornem-se meus imitadores, como eu o sou de Cristo.

[[v46-11-2]]

^<<v46-11-2,2>>^ Eu os elogio por se lembrarem de mim em tudo e por se apegarem às tradições, exatamente como eu as transmiti a vocês.

[[v46-11-3]]

^<<v46-11-3,3>>^ Quero, porém, que entendam que o cabeça de todo homem é Cristo, e o cabeça da mulher é o homem, e o cabeça de Cristo é Deus.

[[v46-11-4]]

^<<v46-11-4,4>>^ Todo homem que ora ou profetiza com a cabeça coberta desonra a sua cabeça;

[[v46-11-5]]

^<<v46-11-5,5>>^ e toda mulher que ora ou profetiza com a cabeça descoberta desonra a sua cabeça; pois é como se a tivesse rapada.

[[v46-11-6]]

^<<v46-11-6,6>>^ Se a mulher não cobre a cabeça, deve também cortar o cabelo; se, porém, é vergonhoso para a mulher ter o cabelo cortado ou rapado, ela deve cobrir a cabeça.

[[v46-11-7]]

^<<v46-11-7,7>>^ O homem não deve cobrir a cabeça, visto que ele é imagem e glória de Deus; mas a mulher é glória do homem.

[[v46-11-8]]

^<<v46-11-8,8>>^ Pois o homem não se originou da mulher, mas a mulher do homem;

[[v46-11-9]]

^<<v46-11-9,9>>^ além disso, o homem não foi criado por causa da mulher, mas a mulher por causa do homem.

[[v46-11-10]]

^<<v46-11-10,10>>^ Por essa razão e por causa dos anjos, a mulher deve ter sobre a cabeça um sinal de autoridade.

[[v46-11-11]]

^<<v46-11-11,11>>^ No Senhor, todavia, a mulher não é independente do homem, nem o homem independente da mulher.

[[v46-11-12]]

^<<v46-11-12,12>>^ Pois, assim como a mulher proveio do homem, também o homem nasce da mulher. Mas tudo provém de Deus.

[[v46-11-13]]

^<<v46-11-13,13>>^ Julguem entre vocês mesmos: é apropriado a uma mulher orar a Deus com a cabeça descoberta?

[[v46-11-14]]

^<<v46-11-14,14>>^ A própria natureza das coisas não lhes ensina que é uma desonra para o homem ter cabelo comprido,

[[v46-11-15]]

^<<v46-11-15,15>>^ e que o cabelo comprido é uma glória para a mulher? Pois o cabelo comprido foi lhe dado como manto.

[[v46-11-16]]

^<<v46-11-16,16>>^ Mas se alguém quiser fazer polêmica a esse respeito, nós não temos esse costume, nem as igrejas de Deus.

[[v46-11-17]]

^<<v46-11-17,17>>^ Entretanto, nisto que lhes vou dizer não os elogio, pois as reuniões de vocês mais fazem mal do que bem.

[[v46-11-18]]

^<<v46-11-18,18>>^ Em primeiro lugar, ouço que, quando vocês se reúnem como igreja, há divisões entre vocês, e até certo ponto eu o creio.

[[v46-11-19]]

^<<v46-11-19,19>>^ Pois é necessário que haja divergências entre vocês, para que sejam conhecidos quais dentre vocês são aprovados.

[[v46-11-20]]

^<<v46-11-20,20>>^ Quando vocês se reúnem, não é para comer a ceia do Senhor,

[[v46-11-21]]

^<<v46-11-21,21>>^ porque cada um come sua própria ceia sem esperar pelos outros. Assim, enquanto um fica com fome, outro se embriaga.

[[v46-11-22]]

^<<v46-11-22,22>>^ Será que vocês não têm casa onde comer e beber? Ou desprezam a igreja de Deus e humilham os que nada têm? Que lhes direi? Eu os elogiarei por isso? Certamente que não!

[[v46-11-23]]

^<<v46-11-23,23>>^ Pois recebi do Senhor o que também lhes entreguei: que o Senhor Jesus, na noite em que foi traído, tomou o pão

[[v46-11-24]]

^<<v46-11-24,24>>^ e, tendo dado graças, partiu-o e disse: "Isto é o meu corpo, que é dado em favor de vocês; façam isto em memória de mim".

[[v46-11-25]]

^<<v46-11-25,25>>^ Da mesma forma, depois da ceia ele tomou o cálice e disse: "Este cálice é a nova aliança no meu sangue; façam isto, sempre que o beberem, em memória de mim".

[[v46-11-26]]

^<<v46-11-26,26>>^ Porque, sempre que comerem deste pão e beberem deste cálice, vocês anunciam a morte do Senhor até que ele venha.

[[v46-11-27]]

^<<v46-11-27,27>>^ Portanto, todo aquele que comer o pão ou beber o cálice do Senhor indignamente será culpado de pecar contra o corpo e o sangue do Senhor.

[[v46-11-28]]

^<<v46-11-28,28>>^ Examine-se o homem a si mesmo, e então coma do pão e beba do cálice.

[[v46-11-29]]

^<<v46-11-29,29>>^ Pois quem come e bebe sem discernir o corpo do Senhor, come e bebe para sua própria condenação.

[[v46-11-30]]

^<<v46-11-30,30>>^ Por isso há entre vocês muitos fracos e doentes, e vários já dormiram.

[[v46-11-31]]

^<<v46-11-31,31>>^ Mas, se nós nos examinássemos a nós mesmos, não receberíamos juízo.

[[v46-11-32]]

^<<v46-11-32,32>>^ Quando, porém, somos julgados pelo Senhor, estamos sendo disciplinados para que não sejamos condenados com o mundo.

[[v46-11-33]]

^<<v46-11-33,33>>^ Portanto, meus irmãos, quando vocês se reunirem para comer, esperem uns pelos outros.

[[v46-11-34]]

^<<v46-11-34,34>>^ Se alguém estiver com fome, coma em casa, para que, quando vocês se reunirem, isso não resulte em condenação. Quanto ao mais, quando eu for lhes darei instruções.

'''

xref:046-1-corintios/046-1-corintios-010.adoc#v46-10-0[&#60; Capítulo Anterior] | <<v46-11-0,Topo>> | xref:046-1-corintios/046-1-corintios-012.adoc#v46-12-0[Próximo Capítulo &#62;]