include::./index.adoc[]

[[v46-14-0]]
=== 1 Coríntios, 14
// nvi ?, NVI - Nova Versão Internacional

[[v46-14-1]]

^<<v46-14-1,1>>^ Sigam o caminho do amor e busquem com dedicação os dons espirituais, principalmente o dom de profecia.

[[v46-14-2]]

^<<v46-14-2,2>>^ Pois quem fala em língua não fala aos homens, mas a Deus. De fato, ninguém o entende; em espírito fala mistérios.

[[v46-14-3]]

^<<v46-14-3,3>>^ Mas quem profetiza o faz para a edificação, encorajamento e consolação dos homens.

[[v46-14-4]]

^<<v46-14-4,4>>^ Quem fala em língua a si mesmo se edifica, mas quem profetiza edifica a igreja.

[[v46-14-5]]

^<<v46-14-5,5>>^ Gostaria que todos vocês falassem em línguas, mas prefiro que profetizem. Quem profetiza é maior do que aquele que fala em línguas, a não ser que as interprete, para que a igreja seja edificada.

[[v46-14-6]]

^<<v46-14-6,6>>^ Agora, irmãos, se eu for visitá-los e falar em línguas, em que lhes serei útil, a não ser que lhes leve alguma revelação, ou conhecimento, ou profecia, ou doutrina?

[[v46-14-7]]

^<<v46-14-7,7>>^ Até no caso de coisas inanimadas que produzem sons, tais como a flauta ou a cítara, como alguém reconhecerá o que está sendo tocado, se os sons não forem distintos?

[[v46-14-8]]

^<<v46-14-8,8>>^ Além disso, se a trombeta não emitir um som claro, quem se preparará para a batalha?

[[v46-14-9]]

^<<v46-14-9,9>>^ Assim acontece com vocês. Se não proferirem palavras compreensíveis com a língua, como alguém saberá o que está sendo dito? Vocês estarão simplesmente falando ao ar.

[[v46-14-10]]

^<<v46-14-10,10>>^ Sem dúvida, há diversos idiomas no mundo; todavia, nenhum deles é sem sentido.

[[v46-14-11]]

^<<v46-14-11,11>>^ Portanto, se eu não entender o significado do que alguém está falando, serei estrangeiro para quem fala, e ele, estrangeiro para mim.

[[v46-14-12]]

^<<v46-14-12,12>>^ Assim acontece com vocês. Visto que estão ansiosos por terem dons espirituais, procurem crescer naqueles que trazem a edificação para a igreja.

[[v46-14-13]]

^<<v46-14-13,13>>^ Por isso, quem fala em língua, ore para que a possa interpretar.

[[v46-14-14]]

^<<v46-14-14,14>>^ Pois, se oro em língua, meu espírito ora, mas a minha mente fica infrutífera.

[[v46-14-15]]

^<<v46-14-15,15>>^ Então, que farei? Orarei com o espírito, mas também orarei com o entendimento; cantarei com o espírito, mas também cantarei com o entendimento.

[[v46-14-16]]

^<<v46-14-16,16>>^ Se você estiver louvando a Deus em espírito, como poderá aquele que está entre os não instruídos dizer o "Amém" à sua ação de graças, visto que não sabe o que você está dizendo?

[[v46-14-17]]

^<<v46-14-17,17>>^ Pode ser que você esteja dando graças muito bem, mas o outro não é edificado.

[[v46-14-18]]

^<<v46-14-18,18>>^ Dou graças a Deus por falar em línguas mais do que todos vocês.

[[v46-14-19]]

^<<v46-14-19,19>>^ Todavia, na igreja prefiro falar cinco palavras compreensíveis para instruir os outros a falar dez mil palavras em língua.

[[v46-14-20]]

^<<v46-14-20,20>>^ Irmãos, deixem de pensar como crianças. Com respeito ao mal, sejam crianças; mas, quanto ao modo de pensar, sejam adultos.

[[v46-14-21]]

^<<v46-14-21,21>>^ Pois está escrito na Lei: "Por meio de homens de outras línguas e por meio de lábios de estrangeiros falarei a este povo, mas, mesmo assim, eles não me ouvirão", diz o Senhor.

[[v46-14-22]]

^<<v46-14-22,22>>^ Portanto, as línguas são um sinal para os descrentes, e não para os que crêem; a profecia, porém, é para os que crêem, e não para os descrentes.

[[v46-14-23]]

^<<v46-14-23,23>>^ Assim, se toda a igreja se reunir e todos falarem em línguas, e entrarem alguns não instruídos ou descrentes não dirão que vocês estão loucos?

[[v46-14-24]]

^<<v46-14-24,24>>^ Mas se entrar algum descrente ou não instruído quando todos estiverem profetizando, ele por todos será convencido de que é pecador e por todos será julgado,

[[v46-14-25]]

^<<v46-14-25,25>>^ e os segredos do seu coração serão expostos. Assim, ele se prostrará, rosto em terra, e adorará a Deus, exclamando: "Deus realmente está entre vocês! "

[[v46-14-26]]

^<<v46-14-26,26>>^ Portanto, que diremos, irmãos? Quando vocês se reúnem, cada um de vocês tem um salmo, ou uma palavra de instrução, uma revelação, uma palavra em língua ou uma interpretação. Tudo seja feito para a edificação da igreja.

[[v46-14-27]]

^<<v46-14-27,27>>^ Se, porém, alguém falar em língua, devem falar dois, no máximo três, e alguém deve interpretar.

[[v46-14-28]]

^<<v46-14-28,28>>^ Se não houver intérprete, fique calado na igreja, falando consigo mesmo e com Deus.

[[v46-14-29]]

^<<v46-14-29,29>>^ Tratando-se de profetas, falem dois ou três, e os outros julguem cuidadosamente o que foi dito.

[[v46-14-30]]

^<<v46-14-30,30>>^ Se vier uma revelação a alguém que está sentado, cale-se o primeiro.

[[v46-14-31]]

^<<v46-14-31,31>>^ Pois vocês todos podem profetizar, cada um por sua vez, de forma que todos sejam instruídos e encorajados.

[[v46-14-32]]

^<<v46-14-32,32>>^ Os espíritos dos profetas estão sujeitos aos profetas.

[[v46-14-33]]

^<<v46-14-33,33>>^ Pois Deus não é Deus de desordem, mas de paz. Como em todas as congregações dos santos,

[[v46-14-34]]

^<<v46-14-34,34>>^ permaneçam as mulheres em silêncio nas igrejas, pois não lhes é permitido falar; antes permaneçam em submissão, como diz a lei.

[[v46-14-35]]

^<<v46-14-35,35>>^ Se quiserem aprender alguma coisa, que perguntem a seus maridos em casa; pois é vergonhoso uma mulher falar na igreja.

[[v46-14-36]]

^<<v46-14-36,36>>^ Acaso a palavra de Deus originou-se entre vocês? São vocês o único povo que ela alcançou?

[[v46-14-37]]

^<<v46-14-37,37>>^ Se alguém pensa que é profeta ou espiritual, reconheça que o que lhes estou escrevendo é mandamento do Senhor.

[[v46-14-38]]

^<<v46-14-38,38>>^ Se ignorar isso, ele mesmo será ignorado.

[[v46-14-39]]

^<<v46-14-39,39>>^ Portanto, meus irmãos, busquem com dedicação o profetizar e não proíbam o falar em línguas.

[[v46-14-40]]

^<<v46-14-40,40>>^ Mas tudo deve ser feito com decência e ordem.

'''

xref:046-1-corintios/046-1-corintios-013.adoc#v46-13-0[&#60; Capítulo Anterior] | <<v46-14-0,Topo>> | xref:046-1-corintios/046-1-corintios-015.adoc#v46-15-0[Próximo Capítulo &#62;]