include::./index.adoc[]

[[v46-10-0]]
=== 1 Coríntios, 10
// nvi ?, NVI - Nova Versão Internacional

[[v46-10-1]]

^<<v46-10-1,1>>^ Porque não quero, irmãos, que vocês ignorem o fato de que todos os nossos antepassados estiveram sob a nuvem e todos passaram pelo mar.

[[v46-10-2]]

^<<v46-10-2,2>>^ Em Moisés, todos eles foram batizados na nuvem e no mar.

[[v46-10-3]]

^<<v46-10-3,3>>^ Todos comeram do mesmo alimento espiritual

[[v46-10-4]]

^<<v46-10-4,4>>^ e beberam da mesma bebida espiritual; pois bebiam da rocha espiritual que os acompanhava, e essa rocha era Cristo.

[[v46-10-5]]

^<<v46-10-5,5>>^ Contudo, Deus não se agradou da maioria deles; por isso os seus corpos ficaram espalhados no deserto.

[[v46-10-6]]

^<<v46-10-6,6>>^ Essas coisas ocorreram como exemplos para nós, para que não cobicemos coisas más, como eles fizeram.

[[v46-10-7]]

^<<v46-10-7,7>>^ Não sejam idólatras, como alguns deles foram, conforme está escrito: "O povo se assentou para comer e beber, e levantou-se para se entregar à farra".

[[v46-10-8]]

^<<v46-10-8,8>>^ Não pratiquemos imoralidade, como alguns deles fizeram — e num só dia morreram vinte e três mil.

[[v46-10-9]]

^<<v46-10-9,9>>^ Não devemos pôr o Senhor à prova, como alguns deles fizeram — e foram mortos por serpentes.

[[v46-10-10]]

^<<v46-10-10,10>>^ E não se queixem, como alguns deles se queixaram — e foram mortos pelo anjo destruidor.

[[v46-10-11]]

^<<v46-10-11,11>>^ Essas coisas aconteceram a eles como exemplos e foram escritas como advertência para nós, sobre quem tem chegado o fim dos tempos.

[[v46-10-12]]

^<<v46-10-12,12>>^ Assim, aquele que julga estar firme, cuide-se para que não caia!

[[v46-10-13]]

^<<v46-10-13,13>>^ Não sobreveio a vocês tentação que não fosse comum aos homens. E Deus é fiel; ele não permitirá que vocês sejam tentados além do que podem suportar. Mas, quando forem tentados, ele lhes providenciará um escape, para que o possam suportar.

[[v46-10-14]]

^<<v46-10-14,14>>^ Por isso, meus amados irmãos, fujam da idolatria.

[[v46-10-15]]

^<<v46-10-15,15>>^ Estou falando a pessoas sensatas; julguem vocês mesmos o que estou dizendo.

[[v46-10-16]]

^<<v46-10-16,16>>^ Não é verdade que o cálice da bênção que abençoamos é uma participação no sangue de Cristo, e que o pão que partimos é uma participação no corpo de Cristo?

[[v46-10-17]]

^<<v46-10-17,17>>^ Por haver um único pão, nós, que somos muitos, somos um só corpo, pois todos participamos de um único pão.

[[v46-10-18]]

^<<v46-10-18,18>>^ Considerem o povo de Israel: os que comem dos sacrifícios não participam do altar?

[[v46-10-19]]

^<<v46-10-19,19>>^ Portanto, que estou querendo dizer? Será que o sacrifício oferecido a um ídolo é alguma coisa? Ou o ídolo é alguma coisa?

[[v46-10-20]]

^<<v46-10-20,20>>^ Não! Quero dizer que o que os pagãos sacrificam é oferecido aos demônios e não a Deus, e não quero que vocês tenham comunhão com os demônios.

[[v46-10-21]]

^<<v46-10-21,21>>^ Vocês não podem beber do cálice do Senhor e do cálice dos demônios; não podem participar da mesa do Senhor e da mesa dos demônios.

[[v46-10-22]]

^<<v46-10-22,22>>^ Porventura provocaremos o ciúme do Senhor? Somos mais fortes do que ele?

[[v46-10-23]]

^<<v46-10-23,23>>^ "Tudo é permitido", mas nem tudo convém. "Tudo é permitido", mas nem tudo edifica.

[[v46-10-24]]

^<<v46-10-24,24>>^ Ninguém deve buscar o seu próprio bem, mas sim o dos outros.

[[v46-10-25]]

^<<v46-10-25,25>>^ Comam de tudo o que se vende no mercado, sem fazer perguntas por causa da consciência,

[[v46-10-26]]

^<<v46-10-26,26>>^ pois "do Senhor é a terra e tudo o que nela existe".

[[v46-10-27]]

^<<v46-10-27,27>>^ Se algum descrente o convidar para uma refeição e você quiser ir, coma de tudo o que lhe for apresentado, sem nada perguntar por causa da consciência.

[[v46-10-28]]

^<<v46-10-28,28>>^ Mas se alguém lhe disser: "Isto foi oferecido em sacrifício", não coma, tanto por causa da pessoa que o comentou, como da consciência,

[[v46-10-29]]

^<<v46-10-29,29>>^ isto é, da consciência do outro e não da sua própria. Pois, por que minha liberdade deve ser julgada pela consciência dos outros?

[[v46-10-30]]

^<<v46-10-30,30>>^ Se participo da refeição com ação de graças, por que sou condenado por algo pelo qual dou graças a Deus?

[[v46-10-31]]

^<<v46-10-31,31>>^ Assim, quer vocês comam, bebam ou façam qualquer outra coisa, façam tudo para a glória de Deus.

[[v46-10-32]]

^<<v46-10-32,32>>^ Não se tornem motivo de tropeço, nem para judeus, nem para gregos, nem para a igreja de Deus.

[[v46-10-33]]

^<<v46-10-33,33>>^ Também eu procuro agradar a todos de todas as formas. Porque não estou procurando o meu próprio bem, mas o bem de muitos, para que sejam salvos.

'''

xref:046-1-corintios/046-1-corintios-009.adoc#v46-9-0[&#60; Capítulo Anterior] | <<v46-10-0,Topo>> | xref:046-1-corintios/046-1-corintios-011.adoc#v46-11-0[Próximo Capítulo &#62;]