include::./index.adoc[]

[[v9-24-0]]
=== 1 Samuel, 24
// nvi ?, NVI - Nova Versão Internacional

[[v9-24-1]]

^<<v9-24-1,1>>^ Saul voltou da luta contra os filisteus e disseram-lhe que Davi estava no deserto de En-Gedi.

[[v9-24-2]]

^<<v9-24-2,2>>^ Então Saul tomou três mil de seus melhores soldados de todo o Israel e partiu à procura de Davi e seus homens perto dos rochedos dos Bodes Selvagens.

[[v9-24-3]]

^<<v9-24-3,3>>^ Ele foi aos currais de ovelhas que ficavam junto ao caminho; havia ali uma caverna, e Saul entrou nela para fazer suas necessidades. Davi e seus soldados estavam bem no fundo da caverna.

[[v9-24-4]]

^<<v9-24-4,4>>^ Eles disseram: "Este é o dia sobre o qual o Senhor lhe falou: ‘Entregarei nas suas mãos seu inimigo para que você faça com ele o que quiser’ ". Então Davi foi com muito cuidado e cortou uma ponta do manto de Saul, sem que este percebesse.

[[v9-24-5]]

^<<v9-24-5,5>>^ Mas Davi sentiu bater-lhe o coração de remorso por ele ter cortado uma ponta do manto de Saul.

[[v9-24-6]]

^<<v9-24-6,6>>^ E então disse a seus soldados: "Que o SENHOR me livre de fazer tal coisa a meu senhor, de erguer a mão contra ele; pois é o ungido do Senhor".

[[v9-24-7]]

^<<v9-24-7,7>>^ Com essas palavras Davi repreendeu os soldados e não permitiu que atacassem Saul. E este saiu da caverna e seguiu seu caminho.

[[v9-24-8]]

^<<v9-24-8,8>>^ Então Davi saiu da caverna e gritou para Saul: "Ó rei, meu senhor! " Quando Saul olhou para trás, Davi inclinou-se, rosto em terra.

[[v9-24-9]]

^<<v9-24-9,9>>^ E depois disse: "Por que o rei dá atenção aos que dizem que eu pretendo lhe fazer mal?

[[v9-24-10]]

^<<v9-24-10,10>>^ Hoje o rei pode ver com os próprios olhos como o Senhor o entregou em minhas mãos na caverna. Alguns insistiram que eu o matasse, mas eu o poupei, pois disse: ‘Não erguerei a mão contra meu senhor, pois ele é o ungido do Senhor’.

[[v9-24-11]]

^<<v9-24-11,11>>^ Olha, meu pai, olha para este pedaço de teu manto em minha mão! Cortei a ponta de teu manto, mas não o matei. Agora entende e reconhece que não sou culpado de fazer o mal ou de rebelar-me. Não lhe fiz mal algum, embora estejas à minha procura para tirar-me a vida.

[[v9-24-12]]

^<<v9-24-12,12>>^ O Senhor julgue entre mim e ti. Vingue ele os males que tens feito contra mim, mas não levantarei a mão contra ti.

[[v9-24-13]]

^<<v9-24-13,13>>^ Como diz o provérbio antigo: ‘Dos ímpios vêm coisas ímpias’; por isso não levantarei a minha mão contra ti".

[[v9-24-14]]

^<<v9-24-14,14>>^ "Contra quem saiu o rei de Israel? A quem está perseguindo? A um cão morto! A uma pulga!

[[v9-24-15]]

^<<v9-24-15,15>>^ O Senhor seja o juiz e nos julgue. Considere ele minha causa e a sustente; que ele me julgue, livrando-me de tuas mãos. "

[[v9-24-16]]

^<<v9-24-16,16>>^ Tendo Davi falado todas essas palavras, Saul perguntou: "É você, meu filho Davi? " E chorou em voz alta.

[[v9-24-17]]

^<<v9-24-17,17>>^ "Você é mais justo do que eu", disse ele a Davi. "Você me tratou bem, mas eu o tratei mal. "

[[v9-24-18]]

^<<v9-24-18,18>>^ "Você acabou de mostrar o bem que me tem feito; o Senhor me entregou em suas mãos, mas você não me matou.

[[v9-24-19]]

^<<v9-24-19,19>>^ Quando um homem encontra um inimigo e o deixa ir sem fazer-lhe mal? O Senhor o recompense com o bem, pelo modo como você me tratou hoje.

[[v9-24-20]]

^<<v9-24-20,20>>^ Agora tenho certeza de que você será rei e de que o reino de Israel será firmado em suas mãos.

[[v9-24-21]]

^<<v9-24-21,21>>^ Portanto, jure-me pelo Senhor que você não eliminará meus descendentes nem fará meu nome desaparecer da família de meu pai".

[[v9-24-22]]

^<<v9-24-22,22>>^ Então Davi fez seu juramento a Saul. E este voltou para casa, mas Davi e seus soldados foram para a fortaleza.

'''

xref:009-1-samuel/009-1-samuel-023.adoc#v9-23-0[&#60; Capítulo Anterior] | <<v9-24-0,Topo>> | xref:009-1-samuel/009-1-samuel-025.adoc#v9-25-0[Próximo Capítulo &#62;]