include::./index.adoc[]

[[v9-15-0]]
=== 1 Samuel, 15
// nvi ?, NVI - Nova Versão Internacional

[[v9-15-1]]

^<<v9-15-1,1>>^ Samuel disse a Saul: "Eu sou aquele a quem o Senhor enviou para ungi-lo como rei de Israel, o povo dele; por isso escute agora a mensagem do Senhor.

[[v9-15-2]]

^<<v9-15-2,2>>^ Assim diz o Senhor dos Exércitos: ‘Castigarei os amalequitas pelo que fizeram a Israel, atacando-os quando saíam do Egito.

[[v9-15-3]]

^<<v9-15-3,3>>^ Agora vão, ataquem os amalequitas e consagrem ao SENHOR para destruição tudo o que lhes pertence. Não os poupem; matem homens, mulheres, crianças, recém-nascidos, bois, ovelhas, camelos e jumentos’ ".

[[v9-15-4]]

^<<v9-15-4,4>>^ Então convocou Saul os homens e os reuniu em Telaim: duzentos mil soldados de infantaria e dez mil homens de Judá.

[[v9-15-5]]

^<<v9-15-5,5>>^ Saul foi à cidade de Amaleque e armou uma emboscada no vale.

[[v9-15-6]]

^<<v9-15-6,6>>^ Então disse aos queneus: "Retirem-se, saiam do meio dos amalequitas para que eu não os destrua junto com eles; pois vocês foram bondosos com os israelitas, quando eles estavam vindo do Egito". Então os queneus saíram do meio dos amalequitas.

[[v9-15-7]]

^<<v9-15-7,7>>^ E Saul atacou os amalequitas por todo caminho desde Havilá até Sur, a leste do Egito.

[[v9-15-8]]

^<<v9-15-8,8>>^ Capturou vivo Agague, rei dos amalequitas, e exterminou o seu povo.

[[v9-15-9]]

^<<v9-15-9,9>>^ Mas Saul e o exército pouparam Agague e o melhor das ovelhas e dos bois, os bezerros gordos e os cordeiros. Pouparam tudo que era bom, mas a tudo que era desprezível e inútil destruíram por completo.

[[v9-15-10]]

^<<v9-15-10,10>>^ Então o Senhor falou a Samuel:

[[v9-15-11]]

^<<v9-15-11,11>>^ "Arrependo-me de ter constituído a Saul rei, pois ele me abandonou e não seguiu as minhas instruções". Samuel ficou irado e clamou ao Senhor toda aquela noite.

[[v9-15-12]]

^<<v9-15-12,12>>^ De madrugada Samuel foi ao encontro de Saul, mas lhe disseram: "Saul foi para o Carmelo, onde ergueu um monumento em sua própria honra e depois foi para Gilgal".

[[v9-15-13]]

^<<v9-15-13,13>>^ Quando Samuel o encontrou, Saul disse: "O Senhor o abençoe! Segui as instruções do Senhor".

[[v9-15-14]]

^<<v9-15-14,14>>^ Samuel, porém, perguntou: "Então que balido de ovelhas é esse que ouço com meus próprios ouvidos? Que mugido de bois é esse que estou ouvindo? "

[[v9-15-15]]

^<<v9-15-15,15>>^ Respondeu Saul: "Os soldados os trouxeram dos amalequitas; eles pouparam o melhor das ovelhas e dos bois para o sacrificarem ao Senhor seu Deus, mas destruímos totalmente o restante".

[[v9-15-16]]

^<<v9-15-16,16>>^ Samuel disse a Saul: "Fique quieto! Eu lhe direi o que o Senhor me falou esta noite". Respondeu Saul: "Diga-me".

[[v9-15-17]]

^<<v9-15-17,17>>^ E Samuel disse: "Embora pequeno aos seus próprios olhos, você não se tornou o líder das tribos de Israel? O Senhor o ungiu como rei sobre Israel

[[v9-15-18]]

^<<v9-15-18,18>>^ e o enviou numa missão, ordenando: ‘Vá e destrua completamente aquele povo ímpio, os amalequitas; guerreie contra eles, até que os tenha eliminado’.

[[v9-15-19]]

^<<v9-15-19,19>>^ Por que você não obedeceu ao Senhor? Por que se lançou sobre os despojos e fez o que o Senhor reprova? "

[[v9-15-20]]

^<<v9-15-20,20>>^ Disse Saul: "Mas eu obedeci ao Senhor! Cumpri a missão que o Senhor me designou. Trouxe Agague, o rei dos amalequitas, mas exterminei os amalequitas.

[[v9-15-21]]

^<<v9-15-21,21>>^ Os soldados tomaram ovelhas e bois do despojo, o melhor do que estava consagrado a Deus para destruição, a fim de os sacrificarem ao Senhor seu Deus, em Gilgal".

[[v9-15-22]]

^<<v9-15-22,22>>^ Samuel, porém, respondeu: "Acaso tem o Senhor tanto prazer em holocaustos e em sacrifícios quanto em que se obedeça à sua palavra? A obediência é melhor do que o sacrifício, e a submissão é melhor do que a gordura de carneiros.

[[v9-15-23]]

^<<v9-15-23,23>>^ Pois a rebeldia é como o pecado da feitiçaria, e a arrogância como o mal da idolatria. Assim como você rejeitou a palavra do Senhor, ele o rejeitou como rei".

[[v9-15-24]]

^<<v9-15-24,24>>^ "Pequei", disse Saul. "Violei a ordem do Senhor e as instruções que você me deu. Tive medo dos soldados e lhes atendi.

[[v9-15-25]]

^<<v9-15-25,25>>^ Agora eu lhe imploro, perdoe o meu pecado e volte comigo, para que eu adore o Senhor".

[[v9-15-26]]

^<<v9-15-26,26>>^ Samuel, contudo, lhe disse: "Não voltarei com você. Você rejeitou a palavra do Senhor, e o Senhor o rejeitou como rei de Israel! "

[[v9-15-27]]

^<<v9-15-27,27>>^ Quando Samuel se virou para sair, Saul agarrou-se à barra do manto dele, e o manto se rasgou.

[[v9-15-28]]

^<<v9-15-28,28>>^ E Samuel lhe disse: "O Senhor rasgou de você, hoje, o reino de Israel, e o entregou a alguém que é melhor que você.

[[v9-15-29]]

^<<v9-15-29,29>>^ Aquele que é a Glória de Israel não mente nem se arrepende, pois não é homem para se arrepender".

[[v9-15-30]]

^<<v9-15-30,30>>^ Saul repetiu: "Pequei. Agora, honra-me perante as autoridades do meu povo e perante Israel; volte comigo, para que eu possa adorar o Senhor seu Deus".

[[v9-15-31]]

^<<v9-15-31,31>>^ E assim Samuel voltou com ele, e Saul adorou o Senhor.

[[v9-15-32]]

^<<v9-15-32,32>>^ Então Samuel disse: "Traga-me Agague, o rei dos amalequitas". Agague veio confiante, pensando: "Com certeza já passou a amargura da morte".

[[v9-15-33]]

^<<v9-15-33,33>>^ Samuel, porém, disse: "Assim como a sua espada deixou mulheres sem filhos, também sua mãe ficará sem o seu filho, entre as mulheres". E Samuel despedaçou Agague perante o Senhor, em Gilgal.

[[v9-15-34]]

^<<v9-15-34,34>>^ Então Samuel partiu para Ramá, e Saul foi para sua casa, em Gibeá de Saul.

[[v9-15-35]]

^<<v9-15-35,35>>^ Nunca mais Samuel viu a Saul, até o dia de sua morte, embora se entristecesse por causa dele porque o Senhor arrependeu-se de ter estabelecido Saul como rei de Israel.

'''

xref:009-1-samuel/009-1-samuel-014.adoc#v9-14-0[&#60; Capítulo Anterior] | <<v9-15-0,Topo>> | xref:009-1-samuel/009-1-samuel-016.adoc#v9-16-0[Próximo Capítulo &#62;]