include::./index.adoc[]

[[v9-12-0]]
=== 1 Samuel, 12
// nvi ?, NVI - Nova Versão Internacional

[[v9-12-1]]

^<<v9-12-1,1>>^ Samuel disse a todo Israel: "Atendi tudo o que vocês me pediram e estabeleci um rei para vocês.

[[v9-12-2]]

^<<v9-12-2,2>>^ Agora vocês têm um rei que os governará. Quanto a mim, estou velho e de cabelos brancos, e meus filhos estão aqui com vocês. Tenho vivido diante de vocês desde a minha juventude até agora.

[[v9-12-3]]

^<<v9-12-3,3>>^ Aqui estou. Se tomei um boi ou um jumento de alguém, ou se explorei ou oprimi a alguém, ou se das mãos de alguém aceitei suborno, fechando os olhos para sua culpa, testemunhem contra mim na presença do Senhor e do seu ungido. Se alguma dessas coisas pratiquei, eu farei restituição".

[[v9-12-4]]

^<<v9-12-4,4>>^ E responderam: "Você não nos explorou nem nos oprimiu. Você não tirou coisa alguma das mãos de ninguém".

[[v9-12-5]]

^<<v9-12-5,5>>^ Samuel lhes disse: "O Senhor é testemunha diante de vocês, e bem como o seu ungido é hoje testemunha de que vocês não encontraram culpa alguma em minhas mãos". E disseram: "Ele é testemunha".

[[v9-12-6]]

^<<v9-12-6,6>>^ Então Samuel disse ao povo: "O Senhor designou Moisés e Arão e tirou os seus antepassados do Egito.

[[v9-12-7]]

^<<v9-12-7,7>>^ Agora, pois, fiquem aqui, porque vou entrar em julgamento com vocês, perante o Senhor, com base nos atos justos realizados pelo Senhor em favor de vocês e de seus antepassados.

[[v9-12-8]]

^<<v9-12-8,8>>^ Depois que Jacó entrou no Egito, eles clamaram ao Senhor, e ele enviou Moisés e Arão para tirar seus antepassados do Egito e os estabelecer neste lugar.

[[v9-12-9]]

^<<v9-12-9,9>>^ Seus antepassados, porém, se esqueceram do Senhor seu Deus; então ele os vendeu à Sísera, o comandante do exército de Hazor, e aos filisteus e ao rei de Moabe, que lutaram contra eles.

[[v9-12-10]]

^<<v9-12-10,10>>^ Eles clamaram ao Senhor, dizendo: ‘Pecamos, abandonando o Senhor e prestando culto aos baalins e aos postes sagrados. Agora, porém, liberta-nos das mãos dos nossos inimigos, e nós prestaremos culto a ti’.

[[v9-12-11]]

^<<v9-12-11,11>>^ Então o Senhor enviou Jerubaal, Baraque, Jefté e Samuel, e os libertou das mãos dos inimigos que os rodeavam, de modo que vocês viveram em segurança.

[[v9-12-12]]

^<<v9-12-12,12>>^ Quando, porém, vocês viram que Naás, rei dos amonitas, estava avançando contra vocês, então me disseram: ‘Não! Escolha um rei para nós’, embora o Senhor, o seu Deus, fosse o rei.

[[v9-12-13]]

^<<v9-12-13,13>>^ Agora, aqui está o rei que vocês escolheram, aquele que vocês pediram; o Senhor deu um rei a vocês.

[[v9-12-14]]

^<<v9-12-14,14>>^ Se vocês temerem, servirem e obedecerem ao Senhor, e não se rebelarem contra suas ordens, e, se vocês e o rei que reinar sobre vocês seguirem o Senhor, o seu Deus, tudo lhes irá bem!

[[v9-12-15]]

^<<v9-12-15,15>>^ Todavia, se vocês desobedecerem ao Senhor e se rebelarem contra o seu mandamento, sua mão se oporá a vocês da mesma forma como se opôs aos seus antepassados.

[[v9-12-16]]

^<<v9-12-16,16>>^ Agora, preparem-se para ver este grande feito que o Senhor vai realizar diante de vocês!

[[v9-12-17]]

^<<v9-12-17,17>>^ Agora não é a época da colheita do trigo? Pedirei ao Senhor que envie trovões e chuva para que vocês reconheçam que fizeram o que o Senhor reprova totalmente, quando pediram um rei".

[[v9-12-18]]

^<<v9-12-18,18>>^ Então Samuel clamou ao Senhor, e naquele mesmo dia o Senhor enviou trovões e chuva. E assim todo o povo temeu grandemente o Senhor e Samuel.

[[v9-12-19]]

^<<v9-12-19,19>>^ E todo o povo disse a Samuel: "Ore ao Senhor seu Deus em favor dos seus servos, para que não morramos, pois a todos os nossos pecados acrescentamos o mal de pedir um rei".

[[v9-12-20]]

^<<v9-12-20,20>>^ Respondeu Samuel: "Não tenham medo. De fato, vocês fizeram todo esse mal, mas não deixem de seguir o Senhor, antes, sirvam o Senhor de todo o coração.

[[v9-12-21]]

^<<v9-12-21,21>>^ Não se desviem, para seguir ídolos inúteis, que não têm qualquer proveito nem podem livrá-los, pois são inúteis.

[[v9-12-22]]

^<<v9-12-22,22>>^ Por causa de seu grande nome o Senhor não os rejeitará, pois o Senhor teve prazer em torná-los o seu próprio povo.

[[v9-12-23]]

^<<v9-12-23,23>>^ E longe de mim esteja pecar contra o Senhor, deixando de orar por vocês. Também lhes ensinarei o caminho que é bom e direito.

[[v9-12-24]]

^<<v9-12-24,24>>^ Somente temam o Senhor e o sirvam fielmente de todo o coração; e considerem as grandes coisas que ele tem feito por vocês.

[[v9-12-25]]

^<<v9-12-25,25>>^ Todavia, se insistirem em fazer o mal, tanto vocês quanto o seu rei serão destruídos".

'''

xref:009-1-samuel/009-1-samuel-011.adoc#v9-11-0[&#60; Capítulo Anterior] | <<v9-12-0,Topo>> | xref:009-1-samuel/009-1-samuel-013.adoc#v9-13-0[Próximo Capítulo &#62;]