include::./index.adoc[]

[[v9-6-0]]
=== 1 Samuel, 6
// nvi ?, NVI - Nova Versão Internacional

[[v9-6-1]]

^<<v9-6-1,1>>^ Quando já fazia sete meses que a arca do Senhor estava em território filisteu,

[[v9-6-2]]

^<<v9-6-2,2>>^ os filisteus chamaram os sacerdotes e adivinhos e disseram: "O que faremos com a arca do Senhor? Digam-nos com o que devemos mandá-la de volta a seu lugar".

[[v9-6-3]]

^<<v9-6-3,3>>^ Eles responderam: "Se vocês devolverem a arca do deus de Israel, não mandem de volta só a arca, mas enviem também uma oferta pela culpa. Então vocês serão curados e saberão por que a sua mão não tem se afastado de vocês".

[[v9-6-4]]

^<<v9-6-4,4>>^ Os filisteus perguntaram: "Que oferta pela culpa devemos lhe enviar? " Eles responderam: "Cinco tumores de ouro e cinco ratos de ouro, de acordo com o número de governantes filisteus, porquanto a mesma praga atingiu vocês e todos os seus governantes.

[[v9-6-5]]

^<<v9-6-5,5>>^ Façam imagens dos tumores e dos ratos que estão assolando o país e dêem glória ao deus de Israel. Talvez ele alivie a sua mão de sobre vocês, seus deuses e sua terra.

[[v9-6-6]]

^<<v9-6-6,6>>^ Por que ter o coração obstinado como os egípcios e o faraó? Somente quando esse deus os tratou severamente, eles deixaram os israelitas seguir o seu caminho.

[[v9-6-7]]

^<<v9-6-7,7>>^ Agora, então, preparem uma carroça nova, com duas vacas que deram cria e sobre as quais nunca foi colocado jugo. Amarrem-nas à carroça, mas afastem delas os seus bezerros e os ponham no curral.

[[v9-6-8]]

^<<v9-6-8,8>>^ Coloquem a arca do Senhor sobre a carroça, e ponham numa caixa ao lado os objetos de ouro que vocês estão lhe enviando como oferta pela culpa. Enviem a carroça,

[[v9-6-9]]

^<<v9-6-9,9>>^ e fiquem observando. Se ela for para seu próprio território, na direção de Bete-Semes, então foi o Senhor quem trouxe essa grande desgraça sobre nós. Mas, se ela não for, então saberemos que não foi a sua mão que nos atingiu e que isso aconteceu conosco por acaso".

[[v9-6-10]]

^<<v9-6-10,10>>^ E assim fizeram. Pegaram duas vacas com cria e as amarraram a uma carroça e prenderam seus bezerros no curral.

[[v9-6-11]]

^<<v9-6-11,11>>^ Colocaram a arca do Senhor na carroça e junto dela a caixa com os ratos de ouro e as imagens dos tumores.

[[v9-6-12]]

^<<v9-6-12,12>>^ Então as vacas foram diretamente para Bete-Semes, mantendo-se na estrada e mugindo por todo o caminho; não se desviaram para a direita nem para a esquerda. Os governantes dos filisteus as seguiram até a fronteira de Bete-Semes.

[[v9-6-13]]

^<<v9-6-13,13>>^ Ora, o povo de Bete-Semes estava colhendo trigo no vale e, quando olharam e viram a arca, alegraram-se muito.

[[v9-6-14]]

^<<v9-6-14,14>>^ A carroça chegou ao campo de Josué, de Bete-Semes, e ali parou ao lado de uma grande rocha. Então cortaram a madeira da carroça e ofereceram as vacas como holocausto ao Senhor.

[[v9-6-15]]

^<<v9-6-15,15>>^ Os levitas tinham descido a arca do Senhor e a caixa com os objetos de ouro e colocado sobre a grande rocha. Naquele dia, o povo de Bete-Semes ofereceu holocaustos e sacrifícios ao Senhor.

[[v9-6-16]]

^<<v9-6-16,16>>^ Os cinco governantes dos filisteus viram tudo isso e voltaram naquele mesmo dia a Ecrom.

[[v9-6-17]]

^<<v9-6-17,17>>^ Os filisteus enviaram ao Senhor como oferta pela culpa estes tumores de ouro: um por Asdode, outro por Gaza, outro por Ascalom, outro por Gate e outro por Ecrom.

[[v9-6-18]]

^<<v9-6-18,18>>^ O número dos ratos de ouro foi conforme o número das cidades filistéias que pertenciam aos cinco governantes; tanto as cidades fortificadas como os povoados no campo. A grande rocha, sobre a qual puseram a arca do Senhor, é até hoje uma testemunha no campo de Josué, de Bete-Semes.

[[v9-6-19]]

^<<v9-6-19,19>>^ Deus, contudo, feriu alguns dos homens de Bete-Semes, matando setenta deles, por terem olhado para dentro da arca do Senhor. O povo chorou por causa da grande matança que o Senhor fizera,

[[v9-6-20]]

^<<v9-6-20,20>>^ e os homens de Bete-Semes perguntaram: "Quem pode permanecer na presença do Senhor, esse Deus santo? Para quem enviamos a arca, para que se afaste de nós? "

[[v9-6-21]]

^<<v9-6-21,21>>^ Então enviaram mensageiros ao povo de Quiriate-Jearim, dizendo: "Os filisteus devolveram a arca do Senhor. Venham e a levem para vocês".

'''

xref:009-1-samuel/009-1-samuel-005.adoc#v9-5-0[&#60; Capítulo Anterior] | <<v9-6-0,Topo>> | xref:009-1-samuel/009-1-samuel-007.adoc#v9-7-0[Próximo Capítulo &#62;]