include::./index.adoc[]

[[v9-27-0]]
=== 1 Samuel, 27
// nvi ?, NVI - Nova Versão Internacional

[[v9-27-1]]

^<<v9-27-1,1>>^ Davi, contudo, pensou: "Algum dia serei morto por Saul. É melhor fugir para a terra dos filisteus. Então Saul desistirá de procurar-me por todo o Israel, e escaparei dele".

[[v9-27-2]]

^<<v9-27-2,2>>^ Assim, Davi e os seiscentos homens que estavam com ele foram até Aquis, filho de Maoque, rei de Gate.

[[v9-27-3]]

^<<v9-27-3,3>>^ Davi e seus soldados se estabeleceram com Aquis, em Gate. Cada homem levou sua família, e Davi, suas duas mulheres, Ainoã, de Jezreel, e Abigail, mulher de Nabal, de Carmelo.

[[v9-27-4]]

^<<v9-27-4,4>>^ Quando contaram a Saul que Davi havia fugido para Gate, ele parou de persegui-lo.

[[v9-27-5]]

^<<v9-27-5,5>>^ Então Davi disse a Aquis: "Se eu conto com a sua simpatia, dá-me um lugar numa das cidades desta terra onde eu possa viver. Por que este teu servo viveria contigo na cidade real? "

[[v9-27-6]]

^<<v9-27-6,6>>^ Naquele dia Aquis deu-lhe Ziclague. Por isso, Ziclague pertence aos reis de Judá até hoje.

[[v9-27-7]]

^<<v9-27-7,7>>^ Davi morou em território filisteu durante um ano e quatro meses.

[[v9-27-8]]

^<<v9-27-8,8>>^ Davi e seus soldados atacavam os gesuritas, os gersitas e os amalequitas, povos que, desde tempos antigos, habitavam a terra que se estende de Sur até o Egito.

[[v9-27-9]]

^<<v9-27-9,9>>^ Quando Davi atacava a região, não poupava homens nem mulheres, e tomava ovelhas, bois, jumentos, camelos e roupas. Então retornava a Aquis.

[[v9-27-10]]

^<<v9-27-10,10>>^ Quando Aquis perguntava: "Onde você atacou hoje? " Davi respondia: "O Neguebe de Judá" ou "O Neguebe de Jerameel" ou "O Neguebe dos queneus".

[[v9-27-11]]

^<<v9-27-11,11>>^ Ele matava a todos, homens e mulheres, para que não fossem levados a Gate, pois pensava: "Eles poderão denunciar-me". Este foi o seu procedimento enquanto viveu em território filisteu.

[[v9-27-12]]

^<<v9-27-12,12>>^ Aquis confiava em Davi e dizia: "Ele se tornou tão odiado por seu povo, os israelitas, que será meu servo para sempre".

'''

xref:009-1-samuel/009-1-samuel-026.adoc#v9-26-0[&#60; Capítulo Anterior] | <<v9-27-0,Topo>> | xref:009-1-samuel/009-1-samuel-028.adoc#v9-28-0[Próximo Capítulo &#62;]