include::./index.adoc[]

[[v9-28-0]]
=== 1 Samuel, 28
// nvi ?, NVI - Nova Versão Internacional

[[v9-28-1]]

^<<v9-28-1,1>>^ Naqueles dias os filisteus reuniram suas tropas para lutar contra Israel. Aquis disse a Davi: "Você deve saber que você e seus soldados me acompanharão no exército".

[[v9-28-2]]

^<<v9-28-2,2>>^ Disse Davi a Aquis: "Então tu saberás o que teu servo é capaz de fazer". Aquis respondeu-lhe: "Então, o colocarei como minha guarda pessoal permanente".

[[v9-28-3]]

^<<v9-28-3,3>>^ Samuel já havia morrido, e todo o Israel o havia pranteado e sepultado em Ramá, sua cidade natal. Saul havia expulsado do país os médiuns e os espíritas.

[[v9-28-4]]

^<<v9-28-4,4>>^ Depois que os filisteus se reuniram, vieram e acamparam em Suném, enquanto Saul reunia todos os israelitas e acampava em Gilboa.

[[v9-28-5]]

^<<v9-28-5,5>>^ Quando Saul viu o acampamento filisteu, teve medo; ficou apavorado.

[[v9-28-6]]

^<<v9-28-6,6>>^ Ele consultou o Senhor, mas este não lhe respondeu nem por sonhos nem por Urim nem por profetas.

[[v9-28-7]]

^<<v9-28-7,7>>^ Então Saul disse aos seus auxiliares: "Procurem uma mulher que invoca espíritos, para que eu a consulte". Eles disseram: "Existe uma em En-Dor".

[[v9-28-8]]

^<<v9-28-8,8>>^ Saul então se disfarçou, vestindo outras roupas, e foi à noite, com dois homens, até a casa da mulher. Ele disse a ela: "Invoque um espírito para mim, fazendo subir aquele cujo nome eu disser".

[[v9-28-9]]

^<<v9-28-9,9>>^ A mulher, porém, lhe disse: "Certamente você sabe o que Saul fez. Ele eliminou os médiuns e os espíritas da terra de Israel. Por que você está preparando uma armadilha contra mim que me levará à morte? "

[[v9-28-10]]

^<<v9-28-10,10>>^ Saul jurou-lhe pelo Senhor: "Juro pelo nome do Senhor que você não será punida por isso".

[[v9-28-11]]

^<<v9-28-11,11>>^ "Quem devo fazer subir? ", perguntou a mulher. Ele respondeu: "Samuel".

[[v9-28-12]]

^<<v9-28-12,12>>^ Quando a mulher viu Samuel, gritou e disse a Saul: "Por que me enganaste? Tu mesmo és Saul! "

[[v9-28-13]]

^<<v9-28-13,13>>^ O rei lhe disse: "Não tenha medo. O que você está vendo? " A mulher disse a Saul: "Vejo um ser que sobe do chão".

[[v9-28-14]]

^<<v9-28-14,14>>^ Ele perguntou: "Qual a aparência dele? " E disse ela: "Um ancião vestindo um manto está subindo". Então Saul ficou sabendo que era Samuel, inclinou-se e prostrou-se, rosto em terra.

[[v9-28-15]]

^<<v9-28-15,15>>^ Samuel perguntou a Saul: "Por que você me perturbou, fazendo-me subir? " Respondeu Saul: "Estou muito angustiado. Os filisteus estão me atacando e Deus se afastou de mim. Ele já não responde nem por profetas nem por sonhos; por isso o chamei para dizer-me o que fazer".

[[v9-28-16]]

^<<v9-28-16,16>>^ Disse Samuel: "Por que você me chamou, já que o Senhor se afastou de você e se tornou seu inimigo?

[[v9-28-17]]

^<<v9-28-17,17>>^ O Senhor fez o que predisse por meu intermédio: rasgou de suas mãos o reino e o deu a seu próximo, a Davi.

[[v9-28-18]]

^<<v9-28-18,18>>^ Porque você não obedeceu ao Senhor nem executou a grande ira dele contra os amalequitas, ele lhe faz isso hoje.

[[v9-28-19]]

^<<v9-28-19,19>>^ O Senhor entregará você e o povo de Israel nas mãos dos filisteus, e amanhã você e seus filhos estarão comigo. O Senhor também entregará o exército de Israel nas mãos dos filisteus".

[[v9-28-20]]

^<<v9-28-20,20>>^ Na mesma hora Saul caiu estendido no chão, aterrorizado pelas palavras de Samuel. Suas forças haviam se esgotado, pois ele tinha passado todo aquele dia e toda aquela noite sem comer.

[[v9-28-21]]

^<<v9-28-21,21>>^ Quando a mulher se aproximou de Saul e viu que ele estava profundamente perturbado, disse: "Olha, tua serva te obedeceu. Arrisquei minha vida e fiz o que me ordenaste.

[[v9-28-22]]

^<<v9-28-22,22>>^ Agora, por favor, ouve tua serva e come um pouco para que tenhas forças para seguir teu caminho".

[[v9-28-23]]

^<<v9-28-23,23>>^ Ele recusou e disse: "Não vou comer". Seus homens, porém, insistiram com ele, e a mulher também; e ele os atendeu. Ele se levantou do chão e sentou-se na cama.

[[v9-28-24]]

^<<v9-28-24,24>>^ A mulher matou depressa um bezerro gordo que tinha em casa; apanhou um pouco de farinha, amassou-a e assou pão sem fermento.

[[v9-28-25]]

^<<v9-28-25,25>>^ Então ela serviu a Saul e a seus homens, e eles comeram. E naquela mesma noite eles partiram.

'''

xref:009-1-samuel/009-1-samuel-027.adoc#v9-27-0[&#60; Capítulo Anterior] | <<v9-28-0,Topo>> | xref:009-1-samuel/009-1-samuel-029.adoc#v9-29-0[Próximo Capítulo &#62;]