include::./index.adoc[]

[[v9-11-0]]
=== 1 Samuel, 11
// nvi ?, NVI - Nova Versão Internacional

[[v9-11-1]]

^<<v9-11-1,1>>^ O amonita Naás avançou contra a cidade de Jabes-Gileade e a cercou. E os homens de Jabes lhe disseram: "Faça um tratado conosco, e nos sujeitaremos a você".

[[v9-11-2]]

^<<v9-11-2,2>>^ Contudo, Naás, o amonita, respondeu: "Só farei um tratado com vocês sob a condição de que eu arranque o olho direito de cada um de vocês e assim humilhei todo o Israel".

[[v9-11-3]]

^<<v9-11-3,3>>^ As autoridades de Jabes lhe disseram: "Dê-nos sete dias para que possamos enviar mensageiros a todo Israel; se ninguém vier nos socorrer, nós nos renderemos".

[[v9-11-4]]

^<<v9-11-4,4>>^ Quando os mensageiros chegaram a Gibeá, cidade de Saul, e relataram essas coisas ao povo, todos choraram em voz alta.

[[v9-11-5]]

^<<v9-11-5,5>>^ Naquele momento, Saul estava trazendo o gado do campo e perguntou: "O que há com o povo? Por que estão chorando? " Então lhe contaram o que os homens de Jabes tinham dito.

[[v9-11-6]]

^<<v9-11-6,6>>^ Quando Saul ouviu isso, o Espírito de Deus apoderou-se dele, e ele ficou furioso.

[[v9-11-7]]

^<<v9-11-7,7>>^ Apanhou dois bois, cortou-os em pedaços e, por meio dos mensageiros, enviou os pedaços a todo o Israel, proclamando: "Isto é o que acontecerá aos bois de quem não seguir Saul e Samuel". Então o temor do Senhor caiu sobre o povo, e eles vieram unânimes.

[[v9-11-8]]

^<<v9-11-8,8>>^ Quando Saul os reuniu em Bezeque, havia trezentos mil de Israel e trinta mil de Judá.

[[v9-11-9]]

^<<v9-11-9,9>>^ E disseram aos mensageiros de Jabes: "Digam aos homens de Jabes-Gileade: ‘Amanhã, na hora mais quente do dia, haverá libertação para vocês’ ". Quando relataram isso aos habitantes de Jabes, eles se alegraram.

[[v9-11-10]]

^<<v9-11-10,10>>^ Então, os homens de Jabes disseram aos amonitas: "Amanhã nós nos renderemos a vocês, e poderão fazer conosco o que quiserem".

[[v9-11-11]]

^<<v9-11-11,11>>^ No dia seguinte, Saul dividiu seus soldados em três grupos; entraram no acampamento amonita na alta madrugada e os mataram até a hora mais quente do dia. Aqueles que sobreviveram se dispersaram, de modo que não ficaram dois juntos.

[[v9-11-12]]

^<<v9-11-12,12>>^ Então o povo disse a Samuel: "Quem foi que perguntou: ‘Será que Saul vai reinar sobre nós? ’ Traga-nos esses homens, e nós os mataremos".

[[v9-11-13]]

^<<v9-11-13,13>>^ Saul, porém, disse: "Hoje ninguém será morto, pois neste dia o Senhor trouxe libertação a Israel".

[[v9-11-14]]

^<<v9-11-14,14>>^ Então Samuel disse ao povo: "Venham, vamos a Gilgal e reafirmemos ali o reino".

[[v9-11-15]]

^<<v9-11-15,15>>^ Assim, todo o povo foi a Gilgal e proclamou Saul como rei na presença do Senhor. Ali ofereceram sacrifícios de comunhão ao Senhor, e Saul e todos os israelitas se alegraram muito.

'''

xref:009-1-samuel/009-1-samuel-010.adoc#v9-10-0[&#60; Capítulo Anterior] | <<v9-11-0,Topo>> | xref:009-1-samuel/009-1-samuel-012.adoc#v9-12-0[Próximo Capítulo &#62;]