include::./index.adoc[]

[[v9-19-0]]
=== 1 Samuel, 19
// nvi ?, NVI - Nova Versão Internacional

[[v9-19-1]]

^<<v9-19-1,1>>^ Saul falou a seu filho Jônatas e a todos os seus conselheiros sobre a sua intenção de matar Davi. Jônatas, porém, gostava muito de Davi

[[v9-19-2]]

^<<v9-19-2,2>>^ e o alertou: "Meu pai, está procurando uma oportunidade para matá-lo. Tenha cuidado amanhã cedo. Vá para um esconderijo e fique por lá.

[[v9-19-3]]

^<<v9-19-3,3>>^ Sairei e ficarei com meu pai no campo onde você estiver. Falarei a ele sobre você e, depois, contarei a você o que eu descobrir".

[[v9-19-4]]

^<<v9-19-4,4>>^ Jônatas falou bem de Davi a Saul, seu pai, e lhe disse: "Que o rei não faça mal a seu servo Davi; ele não lhe fez mal nenhum. Ao contrário, o que ele fez trouxe grandes benefícios ao rei.

[[v9-19-5]]

^<<v9-19-5,5>>^ Ele arriscou a vida quando matou o filisteu. O Senhor trouxe grande vitória para todo o Israel; tu mesmo viste tudo e ficaste contente. Por que, então, farias mal a um inocente como Davi, matando-o sem motivo? "

[[v9-19-6]]

^<<v9-19-6,6>>^ Saul atendeu a Jônatas e fez este juramento: "Juro pelo nome do Senhor que Davi não será morto".

[[v9-19-7]]

^<<v9-19-7,7>>^ Então Jônatas chamou a Davi e lhe contou a conversa toda. Levou-o até Saul, e Davi voltou a servir a Saul como anteriormente.

[[v9-19-8]]

^<<v9-19-8,8>>^ E houve guerra outra vez, e Davi foi lutar com os filisteus. Ele lhes impôs uma grande derrota e eles fugiram dele.

[[v9-19-9]]

^<<v9-19-9,9>>^ Mas um espírito maligno mandado pelo Senhor apoderou-se de Saul quando ele estava sentado em sua casa, com sua lança na mão. Enquanto Davi estava tocando harpa,

[[v9-19-10]]

^<<v9-19-10,10>>^ Saul tentou encravá-lo na parede com sua lança, mas Davi desviou-se e a lança encravou na parede. E Davi conseguiu escapar. Naquela mesma noite,

[[v9-19-11]]

^<<v9-19-11,11>>^ Saul enviou alguns homens à casa de Davi para vigiá-lo e matá-lo de manhã; mas Mical, a mulher de Davi, o alertou: "Se você não fugir esta noite para salvar sua vida, amanhã estará morto".

[[v9-19-12]]

^<<v9-19-12,12>>^ Então Mical fez Davi descer por uma janela, e ele fugiu.

[[v9-19-13]]

^<<v9-19-13,13>>^ Depois Mical pegou um ídolo do clã e o deitou na cama, pôs uma almofada de pêlos de cabra na cabeceira e o cobriu com um manto.

[[v9-19-14]]

^<<v9-19-14,14>>^ Quando chegaram os homens que Saul tinha enviado para prenderem Davi, Mical disse: "Ele está doente".

[[v9-19-15]]

^<<v9-19-15,15>>^ Então Saul enviou os homens de volta para verem Davi dizendo: "Tragam-no até aqui em sua cama para que eu o mate".

[[v9-19-16]]

^<<v9-19-16,16>>^ Quando, porém, os homens entraram, o ídolo do clã estava na cama, e na cabeceira havia uma almofada de pêlos de cabra.

[[v9-19-17]]

^<<v9-19-17,17>>^ Saul disse a Mical: "Por que você me enganou desse modo e deixou que o meu inimigo escapasse? " Ela lhe respondeu: "Ele me disse que o deixasse, se não me mataria? "

[[v9-19-18]]

^<<v9-19-18,18>>^ Depois que fugiu, Davi foi falar com Samuel em Ramá, e contou-lhe tudo o que Saul lhe havia feito. Então ele e Samuel foram a Naiote e ficaram lá.

[[v9-19-19]]

^<<v9-19-19,19>>^ E Saul foi informado: "Davi está em Naiote, em Ramá".

[[v9-19-20]]

^<<v9-19-20,20>>^ Então Saul enviou alguns homens para capturá-lo. Todavia, quando viram um grupo de profetas profetizando, dirigidos por Samuel, o Espírito de Deus apoderou-se dos mensageiros de Saul e eles também entraram em transe profético.

[[v9-19-21]]

^<<v9-19-21,21>>^ Contaram isto a Saul, e ele enviou mais mensageiros, e estes também entraram em transe profético. Depois mandou um terceiro grupo e eles também entraram em transe profético.

[[v9-19-22]]

^<<v9-19-22,22>>^ Finalmente ele mesmo foi para Ramá. Chegando à grande cisterna do lugar chamado Seco, perguntou onde estavam Samuel e Davi. E lhe responderam: "Em Naiote de Ramá".

[[v9-19-23]]

^<<v9-19-23,23>>^ Então Saul foi para lá. Entretanto, o Espírito de Deus apoderou-se dele; e ele foi pelo caminho em transe profético, até chegar a Naiote.

[[v9-19-24]]

^<<v9-19-24,24>>^ E despindo-se de suas roupas, também profetizou em transe na presença de Samuel. Ele ficou deitado nu todo aquele dia e toda aquela noite. Por isso, o povo diz: "Está Saul também entre os profetas? "

'''

xref:009-1-samuel/009-1-samuel-018.adoc#v9-18-0[&#60; Capítulo Anterior] | <<v9-19-0,Topo>> | xref:009-1-samuel/009-1-samuel-020.adoc#v9-20-0[Próximo Capítulo &#62;]