include::./index.adoc[]

[[v9-3-0]]
=== 1 Samuel, 3
// nvi ?, NVI - Nova Versão Internacional

[[v9-3-1]]

^<<v9-3-1,1>>^ O menino Samuel ministrava perante o Senhor, sob a direção de Eli; naqueles dias raramente o Senhor falava, e as visões não eram freqüentes.

[[v9-3-2]]

^<<v9-3-2,2>>^ Certa noite, Eli, cujos olhos estavam ficando tão fracos que já não conseguia mais enxergar, estava deitado em seu lugar de costume.

[[v9-3-3]]

^<<v9-3-3,3>>^ A lâmpada de Deus ainda não havia se apagado, e Samuel estava deitado no santuário do Senhor, onde se encontrava a arca de Deus.

[[v9-3-4]]

^<<v9-3-4,4>>^ Então o Senhor chamou Samuel. Samuel respondeu: "Estou aqui".

[[v9-3-5]]

^<<v9-3-5,5>>^ E correu até Eli e disse: "Estou aqui; o senhor me chamou? " Eli, porém, disse: "Não o chamei; volte e deite-se". Então, ele foi e se deitou.

[[v9-3-6]]

^<<v9-3-6,6>>^ De novo o Senhor chamou: "Samuel! " E Samuel se levantou e foi até Eli e disse: "Estou aqui; o senhor me chamou? " Disse Eli: "Meu filho, não o chamei; volte e deite-se".

[[v9-3-7]]

^<<v9-3-7,7>>^ Ora, Samuel ainda não conhecia o Senhor. A palavra do Senhor ainda não lhe havia sido revelada.

[[v9-3-8]]

^<<v9-3-8,8>>^ O Senhor chamou Samuel pela terceira vez. Ele se levantou, foi até Eli e disse: "Estou aqui; o senhor me chamou? " Então Eli percebeu que o Senhor estava chamando o menino

[[v9-3-9]]

^<<v9-3-9,9>>^ e lhe disse: "Vá e deite-se; se ele chamá-lo, diga: ‘Fala, Senhor, pois o teu servo está ouvindo’ ". Então Samuel foi se deitar.

[[v9-3-10]]

^<<v9-3-10,10>>^ O Senhor voltou a chamá-lo como nas outras vezes: "Samuel, Samuel! " Então Samuel disse: "Fala, pois o teu servo está ouvindo".

[[v9-3-11]]

^<<v9-3-11,11>>^ E o Senhor disse a Samuel: "Vou realizar em Israel algo que fará tinir os ouvidos de todos os que ficarem sabendo.

[[v9-3-12]]

^<<v9-3-12,12>>^ Nessa ocasião executarei contra Eli tudo o que falei contra sua família, do começo ao fim.

[[v9-3-13]]

^<<v9-3-13,13>>^ Pois eu lhe disse que julgaria sua família para sempre, por causa do pecado dos seus filhos, do qual ele tinha consciência; seus filhos se fizeram desprezíveis, e ele não os repreendeu.

[[v9-3-14]]

^<<v9-3-14,14>>^ Por isso jurei à família de Eli: ‘Jamais se fará propiciação pela culpa da família de Eli mediante sacrifício ou oferta’ ".

[[v9-3-15]]

^<<v9-3-15,15>>^ Samuel ficou deitado até de manhã e então abriu as portas da casa do Senhor. Ele teve medo de contar a visão a Eli,

[[v9-3-16]]

^<<v9-3-16,16>>^ mas este o chamou e disse: "Samuel, meu filho". "Estou aqui", respondeu Samuel.

[[v9-3-17]]

^<<v9-3-17,17>>^ Eli perguntou: "O que o Senhor lhe disse? Não esconda de mim. Deus o castigue, e o faça com muita severidade, se você esconder de mim qualquer coisa que ele lhe falou".

[[v9-3-18]]

^<<v9-3-18,18>>^ Então, Samuel lhe contou tudo, e nada escondeu. Então Eli disse: "Ele é o Senhor; que faça o que lhe parecer melhor".

[[v9-3-19]]

^<<v9-3-19,19>>^ O Senhor estava com Samuel enquanto este crescia, e fazia com que todas as suas palavras se cumprissem.

[[v9-3-20]]

^<<v9-3-20,20>>^ Todo o Israel, de Dã até Berseba, reconhecia que Samuel estava confirmado como profeta do Senhor.

[[v9-3-21]]

^<<v9-3-21,21>>^ O Senhor continuou aparecendo em Siló, onde havia se revelado a Samuel por meio de sua palavra.

'''

xref:009-1-samuel/009-1-samuel-002.adoc#v9-2-0[&#60; Capítulo Anterior] | <<v9-3-0,Topo>> | xref:009-1-samuel/009-1-samuel-004.adoc#v9-4-0[Próximo Capítulo &#62;]