include::./index.adoc[]

[[v9-17-0]]
=== 1 Samuel, 17
// nvi ?, NVI - Nova Versão Internacional

[[v9-17-1]]

^<<v9-17-1,1>>^ Os filisteus juntaram suas forças para a guerra e reuniram-se em Socó de Judá. E acamparam em Efes-Damim, entre Socó e Azeca.

[[v9-17-2]]

^<<v9-17-2,2>>^ Saul e os israelitas reuniram-se e acamparam no vale de Elá, posicionando-se em linha de batalha para enfrentar os filisteus.

[[v9-17-3]]

^<<v9-17-3,3>>^ Os filisteus ocuparam uma colina e os israelitas outra, estando o vale entre eles.

[[v9-17-4]]

^<<v9-17-4,4>>^ Um guerreiro chamado Golias, que era de Gate, veio do acampamento filisteu. Tinha dois metros e noventa centímetros de altura.

[[v9-17-5]]

^<<v9-17-5,5>>^ Ele usava um capacete de bronze e vestia uma couraça de escamas de bronze que pesava sessenta quilos;

[[v9-17-6]]

^<<v9-17-6,6>>^ nas pernas usava caneleiras de bronze e tinha um dardo de bronze pendurado nas costas.

[[v9-17-7]]

^<<v9-17-7,7>>^ A haste de sua lança era parecida com uma lançadeira de tecelão, e sua ponta de ferro pesava sete quilos e duzentos gramas. Seu escudeiro ia à frente dele.

[[v9-17-8]]

^<<v9-17-8,8>>^ Golias parou e gritou às tropas de Israel: "Por que vocês estão se posicionando para a batalha? Não sou eu um filisteu, e vocês os servos de Saul? Escolham um homem para lutar comigo.

[[v9-17-9]]

^<<v9-17-9,9>>^ Se ele puder lutar e matar-me, nós seremos seus escravos; todavia, se eu o vencer e o matar, vocês serão nossos escravos e nos servirão".

[[v9-17-10]]

^<<v9-17-10,10>>^ E acrescentou: "Eu desafio hoje as tropas de Israel! Mandem-me um homem para lutar sozinho comigo".

[[v9-17-11]]

^<<v9-17-11,11>>^ Ao ouvirem as palavras do filisteu, Saul e todos os israelitas ficaram atônitos e apavorados.

[[v9-17-12]]

^<<v9-17-12,12>>^ Davi era filho de um efrateu, de Belém de Judá, chamado Jessé. Este tinha oito filhos e já era idoso na época de Saul.

[[v9-17-13]]

^<<v9-17-13,13>>^ Os três filhos mais velhos de Jessé tinham ido para a guerra com Saul: Eliabe, o mais velho, Abinadabe, o segundo e Samá, o terceiro.

[[v9-17-14]]

^<<v9-17-14,14>>^ Davi era o caçula. Os três mais velhos seguiram Saul,

[[v9-17-15]]

^<<v9-17-15,15>>^ mas Davi ia ao acampamento de Saul e voltava para apascentar as ovelhas de seu pai, em Belém.

[[v9-17-16]]

^<<v9-17-16,16>>^ Durante quarenta dias o filisteu aproximava-se, de manhã e de tarde, e tomava posição.

[[v9-17-17]]

^<<v9-17-17,17>>^ Nessa ocasião Jessé disse a seu filho Davi: "Pegue uma arroba de grãos tostados e dez pães e leve-os rapidamente para seus irmãos no acampamento.

[[v9-17-18]]

^<<v9-17-18,18>>^ Leve também estes dez queijos ao comandante da unidade deles. Veja como estão seus irmãos e traga-me alguma garantia de que estão bem.

[[v9-17-19]]

^<<v9-17-19,19>>^ Eles estão com Saul e com todos os homens de Israel no vale de Elá, lutando contra os filisteus".

[[v9-17-20]]

^<<v9-17-20,20>>^ Levantando-se de madrugada, Davi deixou o rebanho com outro pastor, pegou a carga e partiu, conforme Jessé lhe havia ordenado. Chegou ao acampamento na hora em que, com grito de batalha, o exército estava saindo para suas posições de combate.

[[v9-17-21]]

^<<v9-17-21,21>>^ Israel e os filisteus estavam se posicionando em linha de batalha, frente a frente.

[[v9-17-22]]

^<<v9-17-22,22>>^ Davi deixou o que havia trazido com o responsável pelos suprimentos, correu para a linha de batalha para saber como estavam seus irmãos.

[[v9-17-23]]

^<<v9-17-23,23>>^ Enquanto conversava com eles, Golias, o guerreiro filisteu de Gate, avançou e lançou seu desafio habitual; e Davi o ouviu.

[[v9-17-24]]

^<<v9-17-24,24>>^ Quando os israelitas viram o homem, todos fugiram com muito medo.

[[v9-17-25]]

^<<v9-17-25,25>>^ Os israelitas diziam entre si: "Vocês viram aquele homem? Ele veio desafiar Israel. O rei dará grandes riquezas a quem o matar. Também lhe dará sua filha em casamento e isentará de impostos em Israel a família de seu pai".

[[v9-17-26]]

^<<v9-17-26,26>>^ Davi perguntou aos soldados que estavam ali ao seu lado: "O que receberá o homem que matar esse filisteu e salvar a honra de Israel? Quem é esse filisteu incircunciso para desafiar os exércitos do Deus vivo? "

[[v9-17-27]]

^<<v9-17-27,27>>^ Repetiram a Davi o que haviam comentado e lhe disseram: "Isto é o que receberá o homem que matá-lo".

[[v9-17-28]]

^<<v9-17-28,28>>^ Quando Eliabe, o irmão mais velho, ouviu Davi falando com os soldados, ficou muito irritado com ele e perguntou: "Por que você veio até aqui? Com quem deixou aquelas poucas ovelhas no deserto? Sei que você é presunçoso e como seu coração é mau; você veio só para ver a batalha".

[[v9-17-29]]

^<<v9-17-29,29>>^ E disse Davi: "O que fiz agora? Será que não posso nem mesmo conversar? "

[[v9-17-30]]

^<<v9-17-30,30>>^ Ele então se virou para outro e perguntou a mesma coisa, e os homens responderam-lhe como antes.

[[v9-17-31]]

^<<v9-17-31,31>>^ As palavras de Davi chegaram aos ouvidos de Saul, que o mandou chamar.

[[v9-17-32]]

^<<v9-17-32,32>>^ Davi disse a Saul: "Ninguém deve ficar com o coração abatido por causa desse filisteu; teu servo irá e lutará com ele".

[[v9-17-33]]

^<<v9-17-33,33>>^ Respondeu Saul: "Você não tem condições de lutar contra este filisteu; você é apenas um rapaz, e ele é um guerreiro desde a mocidade".

[[v9-17-34]]

^<<v9-17-34,34>>^ Davi, entretanto, disse a Saul: "Teu servo toma conta das ovelhas de seu pai. Quando aparece um leão ou um urso e leva uma ovelha do rebanho,

[[v9-17-35]]

^<<v9-17-35,35>>^ eu vou atrás dele, atinjo-o com golpes e livro a ovelha de sua boca. Quando se vira contra mim, eu o pego pela juba, atinjo-o com golpes até matá-lo.

[[v9-17-36]]

^<<v9-17-36,36>>^ Teu servo é capaz de matar tanto um leão quanto um urso; esse filisteu incircunciso será como um deles, pois desafiou os exércitos do Deus vivo.

[[v9-17-37]]

^<<v9-17-37,37>>^ O Senhor que me livrou das garras do leão e das garras do urso me livrará das mãos desse filisteu". Diante disso Saul disse a Davi: "Vá, e que o Senhor esteja com você".

[[v9-17-38]]

^<<v9-17-38,38>>^ Então Saul vestiu Davi com sua própria túnica. Colocou-lhe uma armadura e um capacete de bronze na cabeça.

[[v9-17-39]]

^<<v9-17-39,39>>^ Davi prendeu sua espada sobre a túnica e tentou andar, pois não estava acostumado àquilo. E disse a Saul: "Não consigo andar com isto, pois não estou acostumado". Assim tirou tudo aquilo,

[[v9-17-40]]

^<<v9-17-40,40>>^ e em seguida pegou seu cajado, escolheu no riacho cinco pedras lisas, colocou-as na bolsa, isto é, no seu alforje de pastor e, com sua atiradeira na mão, aproximou-se do filisteu.

[[v9-17-41]]

^<<v9-17-41,41>>^ Enquanto isso, o filisteu, com seu escudeiro à frente, vinha se aproximando de Davi.

[[v9-17-42]]

^<<v9-17-42,42>>^ Olhou para Davi com desprezo, viu que era só um rapaz, ruivo e de boa aparência, e fez pouco caso dele.

[[v9-17-43]]

^<<v9-17-43,43>>^ E disse a Davi: "Por acaso sou um cão para que você venha contra mim com pedaços de pau? " E o filisteu amaldiçoou Davi invocando seus deuses,

[[v9-17-44]]

^<<v9-17-44,44>>^ e disse: "Venha aqui, e darei sua carne às aves do céu e aos animais do campo! "

[[v9-17-45]]

^<<v9-17-45,45>>^ E Davi disse ao filisteu: "Você vem contra mim com espada, com lança e com dardo, mas eu vou contra você em nome do Senhor dos Exércitos, o Deus dos exércitos de Israel, a quem você desafiou.

[[v9-17-46]]

^<<v9-17-46,46>>^ Hoje mesmo o Senhor o entregará nas minhas mãos, e eu o matarei e cortarei a sua cabeça. Hoje mesmo darei os cadáveres do exército filisteu às aves do céu e aos animais selvagens, e toda a terra saberá que há Deus em Israel.

[[v9-17-47]]

^<<v9-17-47,47>>^ Todos que estão aqui saberão que não é por espada ou por lança que o Senhor concede vitória; pois a batalha é do Senhor, e ele entregará todos vocês em nossas mãos".

[[v9-17-48]]

^<<v9-17-48,48>>^ Quando o filisteu começou a vir na direção de Davi, este correu depressa na direção da linha de batalha para enfrentá-lo.

[[v9-17-49]]

^<<v9-17-49,49>>^ Retirando uma pedra de seu alforje ele a arremessou com a atiradeira e atingiu o filisteu na testa, de tal modo que ela ficou encravada, e ele caiu com o rosto no chão.

[[v9-17-50]]

^<<v9-17-50,50>>^ Assim Davi venceu o filisteu com uma atiradeira e uma pedra; sem espada na mão ele derrubou o filisteu e o matou.

[[v9-17-51]]

^<<v9-17-51,51>>^ Davi correu e se pôs de pé sobre ele; e desembainhando a espada do filisteu acabou de matá-lo, cortando-lhe a cabeça com ela. Quando os filisteus viram que seu guerreiro estava morto, recuaram e fugiram.

[[v9-17-52]]

^<<v9-17-52,52>>^ Então os homens de Israel e de Judá deram o grito de guerra e perseguiram os filisteus até a entrada de Gate, e até as portas de Ecrom. Cadáveres de filisteus ficaram espalhados ao longo da estrada de Saaraim até Gate e Ecrom.

[[v9-17-53]]

^<<v9-17-53,53>>^ Quando os israelitas voltaram da perseguição aos filisteus, levaram tudo o que havia no acampamento deles.

[[v9-17-54]]

^<<v9-17-54,54>>^ Davi pegou a cabeça do filisteu, levou-a para Jerusalém e guardou as armas do filisteu em sua própria tenda.

[[v9-17-55]]

^<<v9-17-55,55>>^ Quando Saul viu Davi avançando para enfrentar o filisteu, perguntou a Abner, o comandante do exército: "Abner, quem é o pai daquele rapaz? " Abner respondeu: "Juro por tua vida, ó rei, que eu não sei".

[[v9-17-56]]

^<<v9-17-56,56>>^ E o rei ordenou-lhe: "Descubra quem é o pai dele".

[[v9-17-57]]

^<<v9-17-57,57>>^ Logo que Davi voltou, depois de ter matado o filisteu, Abner levou-o perante Saul. Davi ainda segurava a cabeça de Golias.

[[v9-17-58]]

^<<v9-17-58,58>>^ E Saul lhe perguntou: "De quem você é filho, meu jovem? " Respondeu Davi: "Sou filho de teu servo Jessé, de Belém".

'''

xref:009-1-samuel/009-1-samuel-016.adoc#v9-16-0[&#60; Capítulo Anterior] | <<v9-17-0,Topo>> | xref:009-1-samuel/009-1-samuel-018.adoc#v9-18-0[Próximo Capítulo &#62;]