include::./index.adoc[]

[[v9-14-0]]
=== 1 Samuel, 14
// nvi ?, NVI - Nova Versão Internacional

[[v9-14-1]]

^<<v9-14-1,1>>^ Certo dia, Jônatas, filho de Saul, disse ao seu jovem escudeiro: "Vamos ao destacamento filisteu, do outro lado". Ele, porém, não contou isto a seu pai.

[[v9-14-2]]

^<<v9-14-2,2>>^ Saul estava sentado debaixo de uma romãzeira na fronteira de Gibeá, em Migrom. Com ele estavam uns seiscentos soldados,

[[v9-14-3]]

^<<v9-14-3,3>>^ entre os quais Aías, que levava o colete sacerdotal. Ele era filho de Aitube, irmão de Icabode, filho de Finéias e neto de Eli, o sacerdote do Senhor em Siló. Ninguém sabia que Jônatas havia saído.

[[v9-14-4]]

^<<v9-14-4,4>>^ Em cada lado do desfiladeiro que Jônatas pretendia atravessar para chegar ao destacamento filisteu, havia um penhasco íngreme; um se chamava Bozez; o outro, Sené.

[[v9-14-5]]

^<<v9-14-5,5>>^ Havia um penhasco ao norte, na direção de Micmás, e outro ao sul, na direção de Geba.

[[v9-14-6]]

^<<v9-14-6,6>>^ E Jônatas disse a seu escudeiro: "Vamos ao destacamento daqueles incircuncisos. Talvez o Senhor aja em nosso favor, pois nada pode impedir o Senhor de salvar, seja com muitos ou com poucos".

[[v9-14-7]]

^<<v9-14-7,7>>^ Disse seu escudeiro: "Faze tudo o que tiveres em mente; eu irei contigo".

[[v9-14-8]]

^<<v9-14-8,8>>^ Jônatas disse: "Venha, vamos atravessar na direção dos soldados e deixaremos que nos avistem.

[[v9-14-9]]

^<<v9-14-9,9>>^ Se nos disserem: ‘Esperem aí até que cheguemos perto’, ficaremos onde estivermos e não avançaremos.

[[v9-14-10]]

^<<v9-14-10,10>>^ Mas, se disserem: ‘Subam até aqui’, subiremos, pois este será um sinal para nós de que o Senhor os entregou em nossas mãos".

[[v9-14-11]]

^<<v9-14-11,11>>^ Então os dois se deixaram ver pelo destacamento dos filisteus, que disseram: "Vejam, os hebreus estão saindo dos buracos onde estavam escondidos".

[[v9-14-12]]

^<<v9-14-12,12>>^ E gritaram para Jônatas e seu escudeiro: "Subam até aqui e lhes daremos uma lição". Diante disso, Jônatas disse a seu escudeiro: "Siga-me; o Senhor os entregou nas mãos de Israel".

[[v9-14-13]]

^<<v9-14-13,13>>^ Jônatas escalou, usando as mãos e os pés, e o escudeiro foi logo atrás. Jônatas começou a derrubá-los, e seu escudeiro, logo atrás dele, os matava.

[[v9-14-14]]

^<<v9-14-14,14>>^ Naquele primeiro ataque, Jônatas e seu escudeiro mataram cerca de vinte homens numa pequena área de terra.

[[v9-14-15]]

^<<v9-14-15,15>>^ Então caiu terror sobre todo o exército, tanto sobre os que estavam no acampamento e no campo, como sobre os que estavam nos destacamentos e até mesmo nas tropas de ataque. O chão tremeu e houve um pânico terrível.

[[v9-14-16]]

^<<v9-14-16,16>>^ As sentinelas de Saul em Gibeá de Benjamim viram o exército filisteu se dispersando, correndo em todas as direções.

[[v9-14-17]]

^<<v9-14-17,17>>^ Então Saul disse aos seus soldados: "Contem os soldados e vejam quem está faltando". Quando o fizeram, viram que Jônatas e seu escudeiro não estavam presentes.

[[v9-14-18]]

^<<v9-14-18,18>>^ Saul ordenou a Aías: "Traga a arca de Deus". Naquele tempo ela estava com os israelitas.

[[v9-14-19]]

^<<v9-14-19,19>>^ Enquanto Saul falava com o sacerdote, o tumulto no acampamento filisteu ia crescendo cada vez mais. Então Saul disse ao sacerdote: "Não precisa trazer a arca".

[[v9-14-20]]

^<<v9-14-20,20>>^ Então Saul e todos os soldados se reuniram e foram para a batalha. Encontraram os filisteus em total confusão, ferindo uns aos outros com suas espadas.

[[v9-14-21]]

^<<v9-14-21,21>>^ Alguns hebreus que antes estavam do lado dos filisteus e que com eles tinham ido ao acampamento filisteu, passaram para o lado dos israelitas que estavam com Saul e Jônatas.

[[v9-14-22]]

^<<v9-14-22,22>>^ Quando todos os israelitas que haviam se escondido nos montes de Efraim ouviram que os filisteus batiam em retirada, também entraram na batalha, perseguindo-os.

[[v9-14-23]]

^<<v9-14-23,23>>^ Assim o Senhor concedeu vitória a Israel naquele dia, e a batalha se espalhou para além de Bete-Áven.

[[v9-14-24]]

^<<v9-14-24,24>>^ Os homens de Israel estavam exaustos naquele dia, pois Saul havia lhes imposto um juramento, dizendo: "Maldito seja todo o que comer antes do anoitecer, antes que eu tenha me vingado de meus inimigos! " Por isso ninguém tinha comido nada.

[[v9-14-25]]

^<<v9-14-25,25>>^ O exército inteiro entrou num bosque, onde havia mel no chão.

[[v9-14-26]]

^<<v9-14-26,26>>^ Eles viram o mel escorrendo, contudo ninguém comeu pois temiam o juramento.

[[v9-14-27]]

^<<v9-14-27,27>>^ Jônatas, porém, não sabia do juramento que seu pai havia imposto ao exército de modo que estendeu a ponta da vara que tinha na mão e a molhou no favo de mel. Quando comeu seus olhos brilharam.

[[v9-14-28]]

^<<v9-14-28,28>>^ Então um dos soldados lhe disse: "Seu pai impôs ao exército um juramento severo, dizendo: ‘Maldito seja todo o que comer hoje! ’ Por isso os homens estão exaustos".

[[v9-14-29]]

^<<v9-14-29,29>>^ Jônatas disse: "Meu pai trouxe desgraça para nós. Veja como meus olhos brilham desde que provei um pouco deste mel.

[[v9-14-30]]

^<<v9-14-30,30>>^ Como teria sido bem melhor se os homens tivessem comido hoje um pouco do que tomaram dos seus inimigos. A matança de filisteus não teria sido ainda maior? "

[[v9-14-31]]

^<<v9-14-31,31>>^ Naquele dia, depois de derrotarem os filisteus, desde Micmás até Aijalom, os israelitas estavam completamente exaustos.

[[v9-14-32]]

^<<v9-14-32,32>>^ Eles então se lançaram sobre os despojos e pegaram ovelhas, bois e bezerros, e mataram-nos ali mesmo e comeram a carne com o sangue.

[[v9-14-33]]

^<<v9-14-33,33>>^ E alguém disse a Saul: "Veja, os soldados estão pecando contra o Senhor, comendo carne com sangue". Ele disse: "Vocês foram infiéis. Rolem uma grande pedra até aqui.

[[v9-14-34]]

^<<v9-14-34,34>>^ Saiam entre os soldados e digam-lhes: ‘Cada um traga a mim seu boi ou sua ovelha, abatam-nos e comam a carne aqui. Não pequem contra o Senhor comendo carne com sangue’ ". Assim, cada um levou seu boi naquela noite e ali os abateram.

[[v9-14-35]]

^<<v9-14-35,35>>^ Então, Saul edificou um altar para o Senhor; foi a primeira vez que fez isso.

[[v9-14-36]]

^<<v9-14-36,36>>^ Saul disse ainda: "Desçamos atrás dos filisteus, à noite, e os saqueemos até o amanhecer, e não deixemos vivo nem um só deles". Eles responderam: "Faze o que achares melhor". O sacerdote, porém, disse: "Consultemos aqui a Deus".

[[v9-14-37]]

^<<v9-14-37,37>>^ Então Saul perguntou a Deus: "Devo perseguir os filisteus? Tu os entregarás nas mãos de Israel? " Mas naquele dia Deus não lhe respondeu.

[[v9-14-38]]

^<<v9-14-38,38>>^ Disse então Saul: "Venham cá, todos vocês que são líderes do exército, e descubramos que pecado foi cometido hoje.

[[v9-14-39]]

^<<v9-14-39,39>>^ Juro pelo nome do Senhor, o libertador de Israel, mesmo que seja meu filho Jônatas, ele morrerá". Mas ninguém disse uma só palavra.

[[v9-14-40]]

^<<v9-14-40,40>>^ Então disse Saul a todos os israelitas: "Fiquem vocês de um lado; eu e meu filho Jônatas ficaremos do outro". E eles responderam: "Faze o que achares melhor".

[[v9-14-41]]

^<<v9-14-41,41>>^ E Saul orou ao Senhor, ao Deus de Israel: "Dá-me a resposta certa". A sorte caiu em Jônatas e Saul, e os soldados saíram livres.

[[v9-14-42]]

^<<v9-14-42,42>>^ Saul disse: "Tirem sortes entre mim e meu filho Jônatas". E Jônatas foi indicado.

[[v9-14-43]]

^<<v9-14-43,43>>^ Então Saul disse a Jônatas: "Diga-me o que você fez". E Jônatas lhe contou: "Eu provei um pouco de mel com a ponta de minha vara. Estou pronto para morrer".

[[v9-14-44]]

^<<v9-14-44,44>>^ Saul disse: "Que Deus me castigue com todo rigor, caso você não morra, Jônatas! "

[[v9-14-45]]

^<<v9-14-45,45>>^ Os soldados, porém, disseram a Saul: "Será que Jônatas, que trouxe esta grande libertação para Israel deve morrer? Nunca! Juramos pelo nome do Senhor, nem um só cabelo de sua cabeça cairá ao chão, pois ele fez isso hoje com o auxílio de Deus". Então os homens resgataram Jônatas, e ele não foi morto.

[[v9-14-46]]

^<<v9-14-46,46>>^ E Saul parou de perseguir os filisteus, e eles voltaram para sua própria terra.

[[v9-14-47]]

^<<v9-14-47,47>>^ Quando Saul assumiu o reinado sobre Israel, lutou contra os seus inimigos em redor: moabitas, amonitas, edomitas, os reis de Zobá e os filisteus. Para qualquer lado que fosse, infligia-lhes castigo.

[[v9-14-48]]

^<<v9-14-48,48>>^ Lutou corajosamente e derrotou os amalequitas, libertando Israel das mãos daqueles que os saqueavam.

[[v9-14-49]]

^<<v9-14-49,49>>^ Os filhos de Saul foram Jônatas, Isvi e Malquisua. O nome de sua filha mais velha era Merabe, e o da mais nova era Mical.

[[v9-14-50]]

^<<v9-14-50,50>>^ Sua mulher chamava-se Ainoã e era filha de Aimaás. O nome do comandante do exército de Saul era Abner, filho de Ner, tio de Saul.

[[v9-14-51]]

^<<v9-14-51,51>>^ Quis, pai de Saul, e Ner, pai de Abner, eram filhos de Abiel.

[[v9-14-52]]

^<<v9-14-52,52>>^ Houve guerra acirrada contra os filisteus durante todo o reinado de Saul. Por isso sempre que Saul conhecia um homem forte e corajoso, alistava-o no seu exército.

'''

xref:009-1-samuel/009-1-samuel-013.adoc#v9-13-0[&#60; Capítulo Anterior] | <<v9-14-0,Topo>> | xref:009-1-samuel/009-1-samuel-015.adoc#v9-15-0[Próximo Capítulo &#62;]