include::./index.adoc[]

[[v9-2-0]]
=== 1 Samuel, 2
// nvi ?, NVI - Nova Versão Internacional

[[v9-2-1]]

^<<v9-2-1,1>>^ Então Ana orou assim: "Meu coração exulta no Senhor; no Senhor minha força é exaltada. Minha boca se exalta sobre os meus inimigos, pois me alegro em tua libertação.

[[v9-2-2]]

^<<v9-2-2,2>>^ "Não há ninguém santo como o Senhor; não há outro além de ti; não há rocha alguma como o nosso Deus.

[[v9-2-3]]

^<<v9-2-3,3>>^ "Não falem tão orgulhosamente, nem saia de suas bocas tal arrogância, pois o Senhor é Deus sábio; é ele quem julga os atos dos homens.

[[v9-2-4]]

^<<v9-2-4,4>>^ "O arco dos fortes é quebrado, mas os fracos são revestidos de força.

[[v9-2-5]]

^<<v9-2-5,5>>^ Os que tinham muito, agora trabalham por comida, mas os que estavam famintos, agora não passam fome. A que era estéril deu à luz sete filhos, mas a que tinha muitos filhos ficou sem vigor.

[[v9-2-6]]

^<<v9-2-6,6>>^ "O Senhor mata e preserva a vida; ele faz descer à sepultura e dela resgata.

[[v9-2-7]]

^<<v9-2-7,7>>^ O Senhor é quem dá pobreza e riqueza; ele humilha e exalta.

[[v9-2-8]]

^<<v9-2-8,8>>^ Levanta do pó o necessitado e, do monte de cinzas ergue o pobre; ele os faz sentarem-se com príncipes e lhes dá lugar de honra. "Pois os alicerces da terra são do Senhor; sobre eles estabeleceu o mundo.

[[v9-2-9]]

^<<v9-2-9,9>>^ Ele guardará os pés dos seus santos, mas os ímpios serão silenciados nas trevas, pois não é pela força que o homem prevalece.

[[v9-2-10]]

^<<v9-2-10,10>>^ Aqueles que se opõem ao Senhor serão despedaçados. Ele trovejará do céu contra eles; o Senhor julgará até os confins da terra. Ele dará poder a seu rei e exaltará a força do seu ungido".

[[v9-2-11]]

^<<v9-2-11,11>>^ Então Elcana voltou para casa em Ramá; mas o menino começou a servir o Senhor sob a direção do sacerdote Eli.

[[v9-2-12]]

^<<v9-2-12,12>>^ Os filhos de Eli eram ímpios; não se importavam com o Senhor

[[v9-2-13]]

^<<v9-2-13,13>>^ nem cumpriam os deveres de sacerdotes para com o povo; sempre que alguém oferecia um sacrifício o auxiliar do sacerdote vinha com um garfo de três dentes,

[[v9-2-14]]

^<<v9-2-14,14>>^ e, enquanto a carne estava cozinhando, ele enfiava o garfo na panela, ou travessa, ou caldeirão, ou caçarola, e o sacerdote pegava para si tudo o que vinha no garfo. Assim faziam com todos os israelitas que iam a Siló.

[[v9-2-15]]

^<<v9-2-15,15>>^ Mas, antes mesmo de queimarem a gordura, vinha o auxiliar do sacerdote e dizia ao homem que estava oferecendo o sacrifício: "Dê um pedaço desta carne para o sacerdote assar; ele não aceitará de você carne cozida, somente crua".

[[v9-2-16]]

^<<v9-2-16,16>>^ Se o homem lhe dissesse: "Deixe primeiro a gordura se queimar e então pegue o que quiser", o auxiliar respondia: "Não. Entregue a carne agora. Se não, eu a tomarei à força".

[[v9-2-17]]

^<<v9-2-17,17>>^ O pecado desses jovens era muito grande à vista do Senhor, pois eles estavam tratando com desprezo a oferta do Senhor.

[[v9-2-18]]

^<<v9-2-18,18>>^ Samuel, contudo, ainda menino, ministrava perante o Senhor, vestindo uma túnica de linho.

[[v9-2-19]]

^<<v9-2-19,19>>^ Todos os anos sua mãe fazia uma pequena túnica e a levava para ele, quando subia a Siló com o marido para oferecer o sacrifício anual.

[[v9-2-20]]

^<<v9-2-20,20>>^ Eli abençoava Elcana e sua mulher, dizendo: "O Senhor dê a você filhos desta mulher no lugar daquele por quem ela pediu e dedicou ao Senhor". Então voltavam para casa.

[[v9-2-21]]

^<<v9-2-21,21>>^ O Senhor foi bondoso com Ana; ela engravidou e deu à luz três filhos e duas filhas. Enquanto isso, o menino Samuel crescia na presença do Senhor.

[[v9-2-22]]

^<<v9-2-22,22>>^ Eli, já bem idoso, ficou sabendo de tudo que seus filhos faziam a todo o Israel e que eles se deitavam com as mulheres que serviam na entrada da Tenda do Encontro.

[[v9-2-23]]

^<<v9-2-23,23>>^ Por isso lhes perguntou: "Por que vocês fazem estas coisas? De todo o povo ouço a respeito do mal que vocês fazem.

[[v9-2-24]]

^<<v9-2-24,24>>^ Não, meus filhos; não é bom o que escuto se espalhando entre o povo do Senhor.

[[v9-2-25]]

^<<v9-2-25,25>>^ Se um homem pecar contra outro homem, os juízes poderão intervir em seu favor; mas, se pecar contra o Senhor, quem intercederá por ele? " Seus filhos, contudo, não deram atenção à repreensão de seu pai, pois o Senhor queria matá-los.

[[v9-2-26]]

^<<v9-2-26,26>>^ E o menino Samuel continuava a crescer, sendo cada vez mais estimado pelo Senhor e pelo povo.

[[v9-2-27]]

^<<v9-2-27,27>>^ E veio um homem de Deus a Eli e lhe disse: "Assim diz o Senhor: ‘Acaso não me revelei claramente à família de seu pai, quando eles estavam no Egito, sob o domínio do faraó?

[[v9-2-28]]

^<<v9-2-28,28>>^ Escolhi seu pai dentre todas as tribos de Israel para ser o meu sacerdote, subir ao meu altar, queimar incenso e usar um colete sacerdotal na minha presença. Também dei à família de seu pai todas as ofertas preparadas no fogo pelos israelitas.

[[v9-2-29]]

^<<v9-2-29,29>>^ Por que vocês zombam de meu sacrifício e de minha oferta que determinei para a minha habitação? Por que você honra seus filhos mais do que a mim, deixando-os engordar com as melhores partes de todas as ofertas feitas pelo meu povo Israel? ’

[[v9-2-30]]

^<<v9-2-30,30>>^ Portanto, o Senhor, o Deus de Israel, declara: ‘Prometi à sua família e à linhagem de seu pai, que ministrariam diante de mim para sempre’. Mas agora o Senhor declara: ‘Longe de mim tal coisa! Honrarei aqueles que me honram, mas aqueles que me desprezam serão tratados com desprezo.

[[v9-2-31]]

^<<v9-2-31,31>>^ É chegada a hora em que eliminarei a sua força e a força da família de seu pai, e não haverá mais nenhum idoso na sua família,

[[v9-2-32]]

^<<v9-2-32,32>>^ e você verá aflição na minha habitação. Embora Israel prospere, na sua família ninguém alcançará idade avançada.

[[v9-2-33]]

^<<v9-2-33,33>>^ E todo descendente seu que eu não eliminar de meu altar será poupado apenas para lhe consumir os olhos com lágrimas e para lhe entristecer o coração, e todos os seus descendentes morrerão no vigor da vida.

[[v9-2-34]]

^<<v9-2-34,34>>^ E o que acontecer a seus dois filhos, Hofni e Finéias, será um sinal para você: os dois morrerão no mesmo dia.

[[v9-2-35]]

^<<v9-2-35,35>>^ Levantarei para mim um sacerdote fiel, que agirá de acordo com o meu coração e o meu pensamento. Edificarei firmemente a família dele, e ele ministrará sempre perante o meu rei ungido.

[[v9-2-36]]

^<<v9-2-36,36>>^ Então todo o que restar da sua família virá e se prostrará perante ele, para obter uma moeda de prata e um pedaço de pão. E lhe implorará que o ponha em alguma função sacerdotal, para ter o que comer’ ".

'''

xref:009-1-samuel/009-1-samuel-001.adoc#v9-1-0[&#60; Capítulo Anterior] | <<v9-2-0,Topo>> | xref:009-1-samuel/009-1-samuel-003.adoc#v9-3-0[Próximo Capítulo &#62;]