include::./index.adoc[]

[[v9-10-0]]
=== 1 Samuel, 10
// nvi ?, NVI - Nova Versão Internacional

[[v9-10-1]]

^<<v9-10-1,1>>^ Então Samuel apanhou um jarro de óleo, derramou-o sobre a cabeça de Saul e o beijou, dizendo: "O Senhor o tem ungido como líder da herança dele.

[[v9-10-2]]

^<<v9-10-2,2>>^ Hoje, quando você partir, encontrará dois homens perto do túmulo de Raquel, em Zelza, na fronteira de Benjamim. Eles lhe dirão: ‘As jumentas que você foi procurar já foram encontradas. Agora seu pai deixou de se importar com elas e está preocupado com vocês. Ele está perguntando: "Como encontrarei meu filho? "

[[v9-10-3]]

^<<v9-10-3,3>>^ Então, dali, você prosseguirá para o carvalho de Tabor. Três homens virão subindo ao santuário de Deus em Betel, e encontrarão você ali. Um estará levando três cabritos, outro três pães, e outro uma vasilha de couro cheia de vinho.

[[v9-10-4]]

^<<v9-10-4,4>>^ Eles o cumprimentarão e lhe oferecerão dois pães, que você deve aceitar.

[[v9-10-5]]

^<<v9-10-5,5>>^ Depois você irá a Gibeá de Deus, onde há um destacamento filisteu. Ao chegar à cidade, você encontrará um grupo de profetas descendo do altar no monte tocando liras, tamborins, flautas e harpas; e eles estarão profetizando.

[[v9-10-6]]

^<<v9-10-6,6>>^ O Espírito do Senhor se apossará de você, e com eles você profetizará em transe, e será um novo homem.

[[v9-10-7]]

^<<v9-10-7,7>>^ Assim que esses sinais tiverem se cumprido, faça o que achar melhor, pois Deus está com você.

[[v9-10-8]]

^<<v9-10-8,8>>^ Vá na minha frente até Gilgal. Depois eu irei também, para oferecer holocaustos e sacrifícios de comunhão, mas você deve esperar sete dias, até que eu chegue e lhe diga o que fazer".

[[v9-10-9]]

^<<v9-10-9,9>>^ Quando se virou para afastar-se de Samuel, Deus mudou o coração de Saul, e todos esses sinais se cumpriram naquele dia.

[[v9-10-10]]

^<<v9-10-10,10>>^ Chegando em Gibeá, um grupo de profetas o encontrou; o Espírito de Deus se apossou dele, e ele profetizou em transe no meio deles.

[[v9-10-11]]

^<<v9-10-11,11>>^ Quando os que já o conheciam viram-no profetizando com os profetas, perguntaram uns aos outros: "O que aconteceu ao filho de Quis? Saul também está entre os profetas? "

[[v9-10-12]]

^<<v9-10-12,12>>^ Um homem daquele lugar respondeu: "E quem é o pai deles? " De modo que isto se tornou um ditado: "Saul também está entre os profetas? "

[[v9-10-13]]

^<<v9-10-13,13>>^ Depois que Saul parou de profetizar, foi para o altar no monte.

[[v9-10-14]]

^<<v9-10-14,14>>^ Então o tio de Saul perguntou a ele e ao seu servo: "Aonde vocês foram? " Ele respondeu: "Procurar as jumentas. Quando, porém, vimos que não seriam encontradas, fomos falar com Samuel".

[[v9-10-15]]

^<<v9-10-15,15>>^ "O que Samuel lhe disse? ", perguntou o tio.

[[v9-10-16]]

^<<v9-10-16,16>>^ Saul respondeu: "Ele nos garantiu que as jumentas tinham sido encontradas". Todavia, Saul não contou ao tio o que Samuel tinha dito sobre o reino.

[[v9-10-17]]

^<<v9-10-17,17>>^ Samuel convocou o povo de Israel ao Senhor, em Mispá,

[[v9-10-18]]

^<<v9-10-18,18>>^ e lhes disse: "Assim diz o Senhor, o Deus de Israel: ‘Eu tirei Israel do Egito, e libertei vocês do poder do Egito e de todos os reinos que os oprimiam’.

[[v9-10-19]]

^<<v9-10-19,19>>^ Mas vocês agora rejeitaram o Deus que os salva de todas as suas desgraças e angústias. E disseram: ‘Não! Escolhe um rei para nós’. Por isso, agora, apresentem-se perante o Senhor, de acordo com as suas tribos e clãs".

[[v9-10-20]]

^<<v9-10-20,20>>^ Tendo Samuel feito todas as tribos de Israel se aproximarem, a de Benjamim foi escolhida.

[[v9-10-21]]

^<<v9-10-21,21>>^ Então fez ir à frente a tribo de Benjamim, clã por clã, e o clã de Matri foi escolhido. Finalmente foi escolhido Saul, filho de Quis. Quando, porém, o procuraram, ele não foi encontrado.

[[v9-10-22]]

^<<v9-10-22,22>>^ Então consultaram novamente o Senhor: "Ele já chegou? " E o Senhor disse: "Sim, ele está escondido no meio da bagagem".

[[v9-10-23]]

^<<v9-10-23,23>>^ Então correram e o tiraram de lá. Quando ficou de pé no meio do povo; os mais altos do povo batiam-lhe nos ombros.

[[v9-10-24]]

^<<v9-10-24,24>>^ E Samuel disse a todos: "Vocês vêem o homem que o Senhor escolheu? Não há ninguém como ele entre todo o povo". Então todos gritaram: "Viva o rei! "

[[v9-10-25]]

^<<v9-10-25,25>>^ Samuel expôs ao povo as leis do reino. Ele as escreveu num livro e o pôs perante o Senhor. Então Samuel mandou o povo de volta para suas casas.

[[v9-10-26]]

^<<v9-10-26,26>>^ Saul também foi para sua casa em Gibeá, acompanhado por guerreiros, cujos corações Deus tinha tocado.

[[v9-10-27]]

^<<v9-10-27,27>>^ Alguns vadios, porém, disseram: "Como este homem pode nos salvar? " Desprezaram-no e não lhe trouxeram presente algum. Mas Saul ficou calado.

'''

xref:009-1-samuel/009-1-samuel-009.adoc#v9-9-0[&#60; Capítulo Anterior] | <<v9-10-0,Topo>> | xref:009-1-samuel/009-1-samuel-011.adoc#v9-11-0[Próximo Capítulo &#62;]