include::./index.adoc[]

[[v9-4-0]]
=== 1 Samuel, 4
// nvi ?, NVI - Nova Versão Internacional

[[v9-4-1]]

^<<v9-4-1,1>>^ Os filisteus dispuseram suas forças em linha para enfrentar Israel, e, intensificando-se o combate, Israel foi derrotado pelos filisteus, que mataram cerca de quatro mil deles no campo de batalha.

[[v9-4-2]]

^<<v9-4-2,2>>^ Quando os soldados voltaram ao acampamento, as autoridades de Israel perguntaram: "Por que o Senhor deixou que os filisteus nos derrotassem? Vamos a Siló buscar a arca da aliança do Senhor, para que ele vá conosco e nos salve das mãos de nossos inimigos".

[[v9-4-3]]

^<<v9-4-3,3>>^ Então mandaram trazer de Siló a arca da aliança do Senhor dos Exércitos, que tem o seu trono entre os querubins. E os dois filhos de Eli, Hofni e Finéias, acompanharam a arca da aliança de Deus.

[[v9-4-4]]

^<<v9-4-4,4>>^ Quando a arca da aliança do Senhor entrou no acampamento, todos os israelitas gritaram tão alto que o chão estremeceu.

[[v9-4-5]]

^<<v9-4-5,5>>^ Os filisteus, ouvindo os gritos, perguntaram: "O que significam todos esses gritos no acampamento dos hebreus? "

[[v9-4-6]]

^<<v9-4-6,6>>^ souberam que a arca do Senhor viera para o acampamento,

[[v9-4-7]]

^<<v9-4-7,7>>^ os filisteus ficaram com medo e disseram: "Deuses chegaram ao acampamento. Ai de nós! Nunca nos aconteceu uma coisa dessas!

[[v9-4-8]]

^<<v9-4-8,8>>^ Ai de nós! Quem nos livrará das mãos desses deuses poderosos? São os deuses que feriram os egípcios com toda espécie de pragas, no deserto.

[[v9-4-9]]

^<<v9-4-9,9>>^ Sejam fortes, filisteus! Sejam homens ou vocês se tornarão escravos dos hebreus, assim como eles foram escravos de vocês. Sejam homens e lutem! "

[[v9-4-10]]

^<<v9-4-10,10>>^ Então os filisteus lutaram e Israel foi derrotado; cada homem fugiu para sua tenda. O massacre foi muito grande: Israel perdeu trinta mil homens de infantaria.

[[v9-4-11]]

^<<v9-4-11,11>>^ A arca de Deus foi tomada, e os dois filhos de Eli, Hofni e Finéias, morreram.

[[v9-4-12]]

^<<v9-4-12,12>>^ Naquele mesmo dia um benjamita correu da linha de batalha até Siló, com as roupas rasgadas e terra na cabeça.

[[v9-4-13]]

^<<v9-4-13,13>>^ Quando ele chegou, Eli estava sentado, observando sua cadeira, ao lado da estrada, pois seu coração temia pela arca de Deus. O homem entrou na cidade e contou o que havia acontecido, e a cidade começou a gritar.

[[v9-4-14]]

^<<v9-4-14,14>>^ Eli ouviu os gritos e perguntou: "O que significa esse tumulto? " O homem correu para contar tudo a Eli.

[[v9-4-15]]

^<<v9-4-15,15>>^ Eli tinha noventa e oito anos de idade e seus olhos estavam imóveis, e ele já não conseguia enxergar.

[[v9-4-16]]

^<<v9-4-16,16>>^ O homem lhe disse: "Acabei de chegar da linha de batalha; fugi de lá hoje mesmo". Eli perguntou: "O que aconteceu, meu filho? "

[[v9-4-17]]

^<<v9-4-17,17>>^ O mensageiro respondeu: "Israel fugiu dos filisteus, e houve uma grande matança entre os soldados. Também os seus dois filhos, Hofni e Finéias, estão mortos, e a arca de Deus foi tomada".

[[v9-4-18]]

^<<v9-4-18,18>>^ Quando ele mencionou a arca de Deus, Eli caiu da cadeira para trás, ao lado do portão, quebrou o pescoço, e morreu, pois era velho e pesado. Ele liderou Israel durante quarenta anos.

[[v9-4-19]]

^<<v9-4-19,19>>^ Sua nora, a mulher de Finéias, estava grávida e perto de dar à luz. Quando ouviu a notícia de que a arca de Deus havia sido tomada e que seu sogro e seu marido estavam mortos, entrou em trabalho de parto e deu à luz, mas não resistiu às dores do parto.

[[v9-4-20]]

^<<v9-4-20,20>>^ Enquanto morria, as mulheres que a ajudavam disseram: "Não se desespere; você teve um menino". Mas ela não respondeu nem deu atenção.

[[v9-4-21]]

^<<v9-4-21,21>>^ Ela deu ao menino o nome de Icabode, e disse: "A glória se foi de Israel". Porque a arca foi tomada e por causa da morte do sogro e do marido.

[[v9-4-22]]

^<<v9-4-22,22>>^ E ainda acrescentou: "A glória se foi de Israel, pois a arca de Deus foi tomada".

'''

xref:009-1-samuel/009-1-samuel-003.adoc#v9-3-0[&#60; Capítulo Anterior] | <<v9-4-0,Topo>> | xref:009-1-samuel/009-1-samuel-005.adoc#v9-5-0[Próximo Capítulo &#62;]