include::./index.adoc[]

[[v9-25-0]]
=== 1 Samuel, 25
// nvi ?, NVI - Nova Versão Internacional

[[v9-25-1]]

^<<v9-25-1,1>>^ Samuel morreu, e todo o Israel se reuniu e o pranteou; e o sepultaram onde vivia, em Ramá. Depois Davi foi para o deserto de Maom.

[[v9-25-2]]

^<<v9-25-2,2>>^ Certo homem de Maom, que tinha seus bens na cidade de Carmelo, era muito rico. Possuía mil cabras e três mil ovelhas, as quais estavam sendo tosquiadas em Carmelo.

[[v9-25-3]]

^<<v9-25-3,3>>^ Seu nome era Nabal e o nome de sua mulher era Abigail, mulher inteligente e bonita; mas seu marido, descendente de Calebe, era rude e mau.

[[v9-25-4]]

^<<v9-25-4,4>>^ No deserto, Davi ficou sabendo que Nabal estava tosquiando as ovelhas.

[[v9-25-5]]

^<<v9-25-5,5>>^ Por isso, enviou dez rapazes e lhes disse: "Levem minha mensagem a Nabal, em Carmelo, e o cumprimentem em meu nome.

[[v9-25-6]]

^<<v9-25-6,6>>^ Digam-lhe: ‘Longa vida para o senhor! Muita paz para o senhor e sua família! E muita prosperidade para tudo que é teu! ’

[[v9-25-7]]

^<<v9-25-7,7>>^ ‘Sei que estás tosquiando tuas ovelhas. Quando os teus pastores estavam conosco, nós não os maltratamos, e durante todo o tempo em que estiveram em Carmelo não se perdeu nada que fosse deles.

[[v9-25-8]]

^<<v9-25-8,8>>^ Pergunte a eles, e eles lhe dirão. Por isso, seja favorável, pois estamos vindo em época de festa. Por favor, dá a nós teus servos e a teu filho Davi o que puderes’ ".

[[v9-25-9]]

^<<v9-25-9,9>>^ Os rapazes foram e deram a Nabal essa mensagem, em nome de Davi. E ficaram esperando.

[[v9-25-10]]

^<<v9-25-10,10>>^ Nabal respondeu então aos servos de Davi: "Quem é Davi? Quem é esse filho de Jessé? Hoje em dia, muitos servos estão fugindo de seus senhores.

[[v9-25-11]]

^<<v9-25-11,11>>^ Por que deveria eu pegar meu pão e minha água, e a carne do gado que abati para meus tosquiadores, e dá-los a homens que vêm não se sabe de onde? "

[[v9-25-12]]

^<<v9-25-12,12>>^ Então, os mensageiros de Davi voltaram, e ao chegarem, relataram a ele cada uma dessas palavras.

[[v9-25-13]]

^<<v9-25-13,13>>^ Davi ordenou a seus homens: "Ponham suas espadas na cintura! " Assim eles fizeram e também Davi. Cerca de quatrocentos homens acompanharam Davi, enquanto duzentos permaneceram com a bagagem.

[[v9-25-14]]

^<<v9-25-14,14>>^ Um dos servos disse a Abigail, mulher de Nabal: "Do deserto, Davi enviou mensageiros para saudar o nosso senhor, mas ele os insultou.

[[v9-25-15]]

^<<v9-25-15,15>>^ No entanto, aqueles homens foram muito bons para conosco. Não nos maltrataram, e, durante todo o tempo em que estivemos com eles nos campos, nada perdemos.

[[v9-25-16]]

^<<v9-25-16,16>>^ Dia e noite eles eram como um muro ao nosso redor, durante todo o tempo em que estivemos com eles cuidando de nossas ovelhas.

[[v9-25-17]]

^<<v9-25-17,17>>^ Agora, leve isso em consideração e veja o que a senhora pode fazer, pois a destruição paira sobre o nosso senhor e sobre toda a sua família. Ele é um homem tão mau que ninguém consegue conversar com ele".

[[v9-25-18]]

^<<v9-25-18,18>>^ Imediatamente, Abigail pegou duzentos pães, duas vasilhas de couro cheias de vinho, cinco ovelhas preparadas, cinco medidas de grãos torrados, cem bolos de uvas passas e duzentos bolos de figos prensados, e os carregou em jumentos.

[[v9-25-19]]

^<<v9-25-19,19>>^ E disse a seus servos: "Vocês vão na frente; eu os seguirei". Ela, porém, nada disse a Nabal, seu marido.

[[v9-25-20]]

^<<v9-25-20,20>>^ Enquanto ela ia montada num jumento, encoberta pela montanha, Davi e seus soldados estavam descendo em sua direção, e ela os encontrou.

[[v9-25-21]]

^<<v9-25-21,21>>^ Davi tinha dito: "De nada adiantou proteger os bens daquele homem no deserto, para que nada se perdesse. Ele me pagou o bem com o mal.

[[v9-25-22]]

^<<v9-25-22,22>>^ Que Deus castigue a Davi, e o faça com muita severidade, caso até de manhã eu deixe vivo um só do sexo masculino de todos os que pertencem a Nabal! "

[[v9-25-23]]

^<<v9-25-23,23>>^ Quando Abigail viu Davi, desceu depressa do jumento e prostrou-se perante Davi, rosto em terra.

[[v9-25-24]]

^<<v9-25-24,24>>^ Ela caiu a seus pés e disse: "Meu senhor, a culpa é toda minha. Por favor, deixa a tua serva lhe falar; ouve o que ela tem a dizer.

[[v9-25-25]]

^<<v9-25-25,25>>^ Meu senhor, não dês atenção àquele homem mau, Nabal. Ele é insensato, conforme o seu nome significa; e a insensatez o acompanha. Contudo, eu, tua serva, não vi os rapazes que meu senhor enviou.

[[v9-25-26]]

^<<v9-25-26,26>>^ "Agora, meu senhor, juro pelo nome do Senhor e por tua vida que foi o Senhor que o impediu de derramar sangue e de vingar-se com tuas próprias mãos. Que teus inimigos e todos os que pretendem fazer-te mal sejam castigados como Nabal.

[[v9-25-27]]

^<<v9-25-27,27>>^ E que este presente que esta tua serva trouxe ao meu senhor seja dado aos homens que o seguem.

[[v9-25-28]]

^<<v9-25-28,28>>^ Esqueça, eu te suplico, a ofensa de tua serva, pois o Senhor certamente fará um reino duradouro para ti, que travas os combates do Senhor. E em toda a tua vida, nenhuma culpa se ache em ti.

[[v9-25-29]]

^<<v9-25-29,29>>^ Mesmo que alguém te persiga para tirar-te a vida, a vida de meu senhor estará firmemente segura como a dos que são protegidos pelo Senhor teu Deus. Mas a vida de teus inimigos será atirada para longe como por uma atiradeira.

[[v9-25-30]]

^<<v9-25-30,30>>^ Quando o Senhor tiver feito a meu senhor todo o bem que prometeu e te tiver nomeado líder sobre Israel,

[[v9-25-31]]

^<<v9-25-31,31>>^ meu senhor não terá no coração o peso de ter derramado sangue desnecessariamente nem de ter feito justiça com as próprias mãos. E, quando o Senhor tiver abençoado a ti, lembra-te de tua serva".

[[v9-25-32]]

^<<v9-25-32,32>>^ Davi disse a Abigail: "Bendito seja o Senhor, o Deus de Israel, que hoje a enviou ao meu encontro.

[[v9-25-33]]

^<<v9-25-33,33>>^ Seja você abençoada pelo seu bom senso e por evitar que eu hoje derrame sangue e me vingue com minhas próprias mãos.

[[v9-25-34]]

^<<v9-25-34,34>>^ De outro modo, juro pelo nome do Senhor, o Deus de Israel, que evitou que eu lhe fizesse mal, se você não tivesse vindo depressa encontrar-me, nem um só do sexo masculino pertencente a Nabal teria sido deixado vivo ao romper do dia".

[[v9-25-35]]

^<<v9-25-35,35>>^ Então Davi aceitou o que ela havia lhe trazido e disse: "Vá para sua casa em paz. Ouvi o que você disse e atenderei o seu pedido".

[[v9-25-36]]

^<<v9-25-36,36>>^ Quando Abigail retornou a Nabal, ele estava dando um banquete em casa, como um banquete de rei. Ele estava alegre e bastante bêbado, e ela nada lhe falou até o amanhecer.

[[v9-25-37]]

^<<v9-25-37,37>>^ De manhã, quando Nabal estava sóbrio, sua mulher lhe contou todas essas coisas; ele sofreu um ataque e ficou paralisado como uma pedra.

[[v9-25-38]]

^<<v9-25-38,38>>^ Cerca de dez dias depois, o Senhor feriu a Nabal, e ele morreu.

[[v9-25-39]]

^<<v9-25-39,39>>^ Quando Davi soube que Nabal estava morto, disse: "Bendito seja o Senhor, que defendeu a minha causa contra Nabal, por ter me tratado com desprezo. O Senhor impediu seu servo de praticar o mal e fez com que a maldade de Nabal caísse sobre sua própria cabeça". Então Davi enviou uma mensagem a Abigail, pedindo-lhe que se tornasse sua mulher.

[[v9-25-40]]

^<<v9-25-40,40>>^ Seus servos foram a Carmelo e disseram a Abigail: "Davi nos enviou a você para levá-la para tornar-se mulher dele".

[[v9-25-41]]

^<<v9-25-41,41>>^ Ela se levantou, depois inclinou-se rosto em terra e disse: "Aqui está a sua serva, pronta para servi-los e lavar os pés dos servos de meu senhor".

[[v9-25-42]]

^<<v9-25-42,42>>^ Abigail logo montou num jumento e, acompanhada por suas cinco servas, foi com os mensageiros de Davi e tornou-se sua mulher.

[[v9-25-43]]

^<<v9-25-43,43>>^ Davi também casou-se com Ainoã de Jezreel; e as duas foram suas mulheres.

[[v9-25-44]]

^<<v9-25-44,44>>^ Saul, porém, tinha dado sua filha Mical, mulher de Davi, a Paltiel, filho de Laís, de Galim.

'''

xref:009-1-samuel/009-1-samuel-024.adoc#v9-24-0[&#60; Capítulo Anterior] | <<v9-25-0,Topo>> | xref:009-1-samuel/009-1-samuel-026.adoc#v9-26-0[Próximo Capítulo &#62;]