include::./index.adoc[]

[[v9-1-0]]
=== 1 Samuel, 1
// nvi ?, NVI - Nova Versão Internacional

[[v9-1-1]]

^<<v9-1-1,1>>^ Havia certo homem de Ramataim, zufita, dos montes de Efraim, chamado Elcana, filho de Jeroão, neto de Eliú e bisneto de Toú, filho do efraimita Zufe.

[[v9-1-2]]

^<<v9-1-2,2>>^ Ele tinha duas mulheres; uma se chamava Ana, e a outra Penina. Penina tinha filhos, Ana, porém, não tinha.

[[v9-1-3]]

^<<v9-1-3,3>>^ Todos os anos esse homem subia de sua cidade a Siló para adorar e sacrificar ao Senhor dos Exércitos. Lá, Hofni e Finéias, os dois filhos de Eli, eram sacerdotes do Senhor.

[[v9-1-4]]

^<<v9-1-4,4>>^ No dia em que Elcana oferecia sacrifícios, dava porções à sua mulher Penina e a todos os filhos e filhas dela.

[[v9-1-5]]

^<<v9-1-5,5>>^ Mas a Ana dava uma porção dupla, porque a amava, mesmo que o Senhor a houvesse deixado estéril.

[[v9-1-6]]

^<<v9-1-6,6>>^ E porque o Senhor a tinha deixado estéril, sua rival a provocava continuamente, a fim de irritá-la.

[[v9-1-7]]

^<<v9-1-7,7>>^ Isso acontecia ano após ano. Sempre que Ana subia à casa do Senhor, sua rival a provocava e ela chorava e não comia.

[[v9-1-8]]

^<<v9-1-8,8>>^ Elcana, seu marido, lhe perguntava: "Ana, por que você está chorando? Por que não come? Por que está triste? Será que eu não sou melhor para você do que dez filhos? "

[[v9-1-9]]

^<<v9-1-9,9>>^ Certa vez quando terminou de comer e beber em Siló, estando o sacerdote Eli sentado numa cadeira junto à entrada do santuário do Senhor, Ana se levantou

[[v9-1-10]]

^<<v9-1-10,10>>^ e, com a alma amargurada, chorou muito e orou ao Senhor.

[[v9-1-11]]

^<<v9-1-11,11>>^ E fez um voto, dizendo: "Ó Senhor dos Exércitos, se tu deres atenção à humilhação de tua serva, te lembrares de mim e não te esqueceres de tua serva, mas lhe deres um filho, então eu o dedicarei ao Senhor por todos os dias de sua vida, e o seu cabelo e a sua barba nunca serão cortados".

[[v9-1-12]]

^<<v9-1-12,12>>^ Enquanto ela continuava a orar diante do Senhor, Eli observava sua boca.

[[v9-1-13]]

^<<v9-1-13,13>>^ Como Ana orava silenciosamente, seus lábios se mexiam mas não se ouvia sua voz. Então Eli pensou que ela estivesse embriagada

[[v9-1-14]]

^<<v9-1-14,14>>^ e lhe disse: "Até quando você continuará embriagada? Abandone o vinho! "

[[v9-1-15]]

^<<v9-1-15,15>>^ Ana respondeu: "Não se trata disso, meu senhor. Sou uma mulher muito angustiada. Não bebi vinho nem bebida fermentada; eu estava derramando minha alma diante do Senhor.

[[v9-1-16]]

^<<v9-1-16,16>>^ Não julgues tua serva uma mulher vadia; estou orando aqui até agora por causa de minha grande angústia e tristeza".

[[v9-1-17]]

^<<v9-1-17,17>>^ Eli respondeu: "Vá em paz, e que o Deus de Israel lhe conceda o que você pediu".

[[v9-1-18]]

^<<v9-1-18,18>>^ Ela disse: "Espero que sejas benevolente para com tua serva! " Então ela seguiu seu caminho, comeu, e seu rosto já não estava mais abatido.

[[v9-1-19]]

^<<v9-1-19,19>>^ Na manhã seguinte, eles se levantaram e adoraram ao Senhor; então voltaram para casa, em Ramá. Elcana teve relações com sua mulher Ana, e o Senhor se lembrou dela.

[[v9-1-20]]

^<<v9-1-20,20>>^ Assim Ana engravidou e, no devido tempo, deu à luz um filho. E deu-lhe o nome de Samuel, dizendo: "Eu o pedi ao Senhor".

[[v9-1-21]]

^<<v9-1-21,21>>^ Quando no ano seguinte Elcana subiu com toda a família para oferecer o sacrifício anual ao Senhor e para cumprir o seu voto,

[[v9-1-22]]

^<<v9-1-22,22>>^ Ana não foi e disse a seu marido: "Depois que o menino for desmamado, eu o levarei e o apresentarei ao Senhor, e ele morará ali para sempre".

[[v9-1-23]]

^<<v9-1-23,23>>^ Disse Elcana, seu marido: "Faça o que lhe parecer melhor. Fique aqui até desmamá-lo; que o Senhor apenas confirme a palavra dele! " Então ela ficou em casa e amamentou seu filho até que o desmamou.

[[v9-1-24]]

^<<v9-1-24,24>>^ Depois de desmamá-lo, levou o menino, ainda pequeno, à casa do Senhor, em Siló, com um novilho de três anos de idade, uma arroba de farinha e uma vasilha de couro cheia de vinho.

[[v9-1-25]]

^<<v9-1-25,25>>^ Eles sacrificaram o novilho e levaram o menino a Eli,

[[v9-1-26]]

^<<v9-1-26,26>>^ e ela lhe disse: "Meu senhor, juro por tua vida que eu sou a mulher que esteve aqui a teu lado, orando ao Senhor.

[[v9-1-27]]

^<<v9-1-27,27>>^ Era este menino que eu pedia, e o Senhor concedeu-me o pedido.

[[v9-1-28]]

^<<v9-1-28,28>>^ Por isso, agora, eu o dedico ao Senhor. Por toda a sua vida será dedicado ao Senhor". E ali adorou o Senhor.

'''

xref:008-rute/008-rute-004.adoc#v8-4-0[&#60; Capítulo Anterior] | <<v9-1-0,Topo>> | xref:009-1-samuel/009-1-samuel-002.adoc#v9-2-0[Próximo Capítulo &#62;]