include::./index.adoc[]

[[v8-4-0]]
=== Rute, 4
// nvi ?, NVI - Nova Versão Internacional

[[v8-4-1]]

^<<v8-4-1,1>>^ Enquanto isso, Boaz subiu à porta da cidade e sentou-se ali exatamente quando o resgatador que ele havia mencionado estava passando por ali. Boaz chamou-lhe e disse: "Meu amigo, venha cá e sente-se". Ele foi e sentou-se.

[[v8-4-2]]

^<<v8-4-2,2>>^ Boaz reuniu dez líderes da cidade e disse: "Sentem-se aqui". E eles se sentaram.

[[v8-4-3]]

^<<v8-4-3,3>>^ Depois disse ao resgatador: "Noemi, que voltou de Moabe, está vendendo o pedaço de terra que pertencia ao nosso irmão Elimeleque.

[[v8-4-4]]

^<<v8-4-4,4>>^ Pensei que devia trazer o assunto para a sua consideração e sugerir-lhe que o adquira, na presença destes que aqui estão sentados e na presença dos líderes do meu povo. Se quer resgatar esta propriedade, resgate-a. Se não, diga-me, para que eu o saiba. Pois ninguém tem esse direito, a não ser você; e depois eu". "Eu a resgatarei", respondeu ele.

[[v8-4-5]]

^<<v8-4-5,5>>^ Boaz, porém, lhe disse: "No dia em que você adquirir as terras de Noemi e da moabita Rute, estará adquirindo também a viúva do falecido, para manter o nome dele em sua herança".

[[v8-4-6]]

^<<v8-4-6,6>>^ Diante disso, o resgatador respondeu: "Nesse caso não poderei resgatá-la, pois poria em risco a minha propriedade. Resgate-a você mesmo. Eu não poderei fazê-lo! "

[[v8-4-7]]

^<<v8-4-7,7>>^ ( Antigamente, em Israel, para que o resgate e a transferência de propriedade fossem válidos, a pessoa tirava a sandália e a dava ao outro. Assim oficializavam os negócios em Israel. )

[[v8-4-8]]

^<<v8-4-8,8>>^ Quando, pois, o resgatador disse a Boaz: "Adquira-a você mesmo! ", ele também tirou a sandália.

[[v8-4-9]]

^<<v8-4-9,9>>^ Então Boaz anunciou aos líderes e a todo o povo ali presente: "Vocês hoje são testemunhas de que estou adquirindo de Noemi toda a propriedade de Elimeleque, de Quiliom e de Malom.

[[v8-4-10]]

^<<v8-4-10,10>>^ Também estou adquirindo o direito de ter como mulher a moabita Rute, viúva de Malom, para manter o nome do falecido sobre a sua herança e para que o seu nome não desapareça do meio da sua família ou dos registros da cidade. Vocês hoje são testemunhas disso! "

[[v8-4-11]]

^<<v8-4-11,11>>^ Os líderes e todos os que estavam na porta confirmaram: "Somos testemunhas! Faça o Senhor com essa mulher que está entrando em sua família, como fez com Raquel e Lia, que juntas formaram as tribos de Israel. Seja poderoso em Efrata e ganhe fama em Belém!

[[v8-4-12]]

^<<v8-4-12,12>>^ E com os filhos que o Senhor lhe conceder dessa jovem, seja a sua família como a de Perez, que Tamar deu a Judá! "

[[v8-4-13]]

^<<v8-4-13,13>>^ Boaz casou-se com Rute, e ela se tornou sua mulher. Boaz a possuiu, e o Senhor concedeu que ela engravidasse e desse à luz um filho.

[[v8-4-14]]

^<<v8-4-14,14>>^ As mulheres disseram a Noemi: "Louvado seja o Senhor, que hoje não a deixou sem resgatador! Que o seu nome seja celebrado em Israel!

[[v8-4-15]]

^<<v8-4-15,15>>^ O menino lhe dará nova vida e a sustentará na velhice, pois é filho da sua nora, que a ama e que lhe é melhor do que sete filhos! "

[[v8-4-16]]

^<<v8-4-16,16>>^ Noemi pôs o menino no colo, e passou a cuidar dele.

[[v8-4-17]]

^<<v8-4-17,17>>^ As mulheres da vizinhança celebraram o seu nome e disseram: "Noemi tem um filho! " e lhe deram o nome de Obede. Este foi o pai de Jessé, pai de Davi.

[[v8-4-18]]

^<<v8-4-18,18>>^ Esta é a história da descendência de Perez: Perez gerou Hezrom;

[[v8-4-19]]

^<<v8-4-19,19>>^ Hezrom gerou Rão; Rão gerou Aminadabe;

[[v8-4-20]]

^<<v8-4-20,20>>^ Aminadabe gerou Naassom; Naassom gerou Salmom;

[[v8-4-21]]

^<<v8-4-21,21>>^ Salmom gerou Boaz; Boaz gerou Obede;

[[v8-4-22]]

^<<v8-4-22,22>>^ Obede gerou Jessé; e Jessé gerou Davi.

'''

xref:008-rute/008-rute-003.adoc#v8-3-0[&#60; Capítulo Anterior] | <<v8-4-0,Topo>> | xref:009-1-samuel/009-1-samuel-001.adoc#v9-1-0[Próximo Capítulo &#62;]