include::./index.adoc[]

[[v8-1-0]]
=== Rute, 1
// nvi ?, NVI - Nova Versão Internacional

[[v8-1-1]]

^<<v8-1-1,1>>^ Na época dos juízes houve fome na terra. Um homem de Belém de Judá, com a mulher e os dois filhos, foi viver por algum tempo nas terras de Moabe.

[[v8-1-2]]

^<<v8-1-2,2>>^ O homem chamava-se Elimeleque, sua mulher Noemi e seus dois filhos Malom e Quiliom. Eram efrateus de Belém de Judá. Chegaram a Moabe, e lá ficaram.

[[v8-1-3]]

^<<v8-1-3,3>>^ Morreu Elimeleque, marido de Noemi, e ela ficou sozinha, com seus dois filhos.

[[v8-1-4]]

^<<v8-1-4,4>>^ Eles se casaram com mulheres moabitas, uma chamada Orfa e a outra Rute. Depois de terem morado lá por quase dez anos,

[[v8-1-5]]

^<<v8-1-5,5>>^ morreram também Malom e Quiliom, e Noemi ficou sozinha, sem os dois filhos e o seu marido.

[[v8-1-6]]

^<<v8-1-6,6>>^ Quando Noemi soube em Moabe que o Senhor viera em auxílio do seu povo, dando-lhe alimento, decidiu voltar com suas duas noras para a sua terra.

[[v8-1-7]]

^<<v8-1-7,7>>^ Assim ela, com as duas noras, partiu do lugar onde tinha morado. Enquanto voltavam para a terra de Judá,

[[v8-1-8]]

^<<v8-1-8,8>>^ Noemi disse às duas noras: "Vão! Voltem para a casa de suas mães! Que o Senhor seja leal com vocês, como vocês foram leais com os falecidos e comigo.

[[v8-1-9]]

^<<v8-1-9,9>>^ O Senhor conceda que cada uma de vocês encontre segurança no lar doutro marido". Então deu-lhes beijos de despedida. Mas elas começaram a chorar bem alto

[[v8-1-10]]

^<<v8-1-10,10>>^ e lhe disseram: "Não! Voltaremos com você para junto de seu povo! "

[[v8-1-11]]

^<<v8-1-11,11>>^ Disse, porém, Noemi: "Voltem, minhas filhas! Por que viriam comigo? Poderia eu ainda ter filhos, que viessem a ser seus maridos?

[[v8-1-12]]

^<<v8-1-12,12>>^ Voltem, minhas filhas! Vão! Estou velha demais para ter outro marido. E mesmo que eu pensasse que ainda há esperança para mim — ainda que eu me casasse esta noite e depois desse à luz filhos,

[[v8-1-13]]

^<<v8-1-13,13>>^ iriam vocês esperar até que eles crescessem? Ficariam sem se casar à espera deles? De jeito nenhum minhas filhas! Para mim é mais amargo do que para vocês, pois a mão do Senhor voltou-se contra mim! "

[[v8-1-14]]

^<<v8-1-14,14>>^ Elas então começaram a choram bem alto de novo. Depois Orfa deu um beijo de despedida em sua sogra, mas Rute ficou com ela.

[[v8-1-15]]

^<<v8-1-15,15>>^ Então Noemi a aconselhou: "Veja, sua concunhada está voltando para o seu povo e para o seu deus. Volte com ela! "

[[v8-1-16]]

^<<v8-1-16,16>>^ Rute, porém, respondeu: "Não insistas comigo que te deixe e não mais a acompanhe. Aonde fores irei, onde ficares ficarei! O teu povo será o meu povo e o teu Deus será o meu Deus!

[[v8-1-17]]

^<<v8-1-17,17>>^ Onde morreres morrerei, e ali serei sepultada. Que o Senhor me castigue com todo o rigor, se outra coisa que não a morte me separar de ti! "

[[v8-1-18]]

^<<v8-1-18,18>>^ Quando Noemi viu que Rute estava de fato decidida a acompanhá-la, não insistiu mais.

[[v8-1-19]]

^<<v8-1-19,19>>^ Prosseguiram, pois, as duas até Belém. Ali chegando, todo o povoado ficou alvoroçado por causa delas. "Será que é Noemi? ", perguntavam as mulheres.

[[v8-1-20]]

^<<v8-1-20,20>>^ Mas ela respondeu: "Não me chamem Noemi, chamem-me Mara, pois o Todo-poderoso tornou minha vida muito amarga!

[[v8-1-21]]

^<<v8-1-21,21>>^ De mãos cheias eu parti; mas de mãos vazias o Senhor me trouxe de volta. Por que me chamam Noemi? O Senhor colocou-se contra mim! O Todo-poderoso me trouxe desgraça! "

[[v8-1-22]]

^<<v8-1-22,22>>^ Foi assim que Noemi voltou das terras de Moabe, com sua nora Rute, a moabita. Elas chegaram a Belém no início da colheita da cevada.

'''

xref:007-juizes/007-juizes-021.adoc#v7-21-0[&#60; Capítulo Anterior] | <<v8-1-0,Topo>> | xref:008-rute/008-rute-002.adoc#v8-2-0[Próximo Capítulo &#62;]