include::./index.adoc[]

[[v12-11-0]]
=== 2 Reis, 11
// nvi ?, NVI - Nova Versão Internacional

[[v12-11-1]]

^<<v12-11-1,1>>^ Quando Atalia, mãe de Acazias, soube que seu filho estava morto, mandou matar toda a família real.

[[v12-11-2]]

^<<v12-11-2,2>>^ Mas Jeoseba, filha do rei Jeorão e irmã de Acazias, pegou Joás, um dos filhos do rei que iam ser assassinados, e o colocou num quarto, junto com a sua ama, para escondê-lo de Atalia; assim ele não foi morto.

[[v12-11-3]]

^<<v12-11-3,3>>^ Seis anos ele ficou escondido com ela no templo do Senhor, enquanto Atalia governava o país.

[[v12-11-4]]

^<<v12-11-4,4>>^ No sétimo ano, o sacerdote Joiada mandou chamar à sua presença no templo do Senhor os líderes dos batalhões de cem dos cários e dos guardas. E fez um acordo com eles, fazendo-os jurar no templo do Senhor. Então lhes mostrou o filho do rei

[[v12-11-5]]

^<<v12-11-5,5>>^ e lhes ordenou: "Vocês vão fazer o seguinte: Quando entrarem de serviço no sábado, uma companhia ficará de guarda no palácio real,

[[v12-11-6]]

^<<v12-11-6,6>>^ outra, na porta de Sur e a terceira, na porta atrás das outras companhias. Elas montarão guarda no templo por turnos.

[[v12-11-7]]

^<<v12-11-7,7>>^ As outras duas companhias que normalmente não estão de serviço no sábado ficarão de guarda no templo, para proteger o rei.

[[v12-11-8]]

^<<v12-11-8,8>>^ Posicionem-se ao redor do rei, de armas na mão. Matem todo o que se aproximar de suas fileiras. Acompanhem o rei aonde quer que ele for".

[[v12-11-9]]

^<<v12-11-9,9>>^ Os líderes dos batalhões de cem fizeram como o sacerdote Joiada havia ordenado. Cada um levou seus soldados, tanto os que estavam entrando de serviço no sábado como os que estavam saindo, ao sacerdote Joiada.

[[v12-11-10]]

^<<v12-11-10,10>>^ Então ele deu aos líderes dos batalhões de cem, as lanças e os escudos que haviam pertencido ao rei Davi, e que estavam no templo do Senhor.

[[v12-11-11]]

^<<v12-11-11,11>>^ Os guardas, todos de arma na mão, posicionaram-se em volta do rei, perto do altar e do templo, desde o lado sul até o lado norte do templo.

[[v12-11-12]]

^<<v12-11-12,12>>^ Depois Joiada trouxe para fora o filho do rei, colocou nele a coroa e entregou-lhe uma cópia da aliança. Então o proclamaram rei ungindo-o, e o povo aplaudia e gritava: "Viva o rei! "

[[v12-11-13]]

^<<v12-11-13,13>>^ Quando Atalia ouviu o barulho dos guardas e do povo, foi ao templo do Senhor, onde estava o povo.

[[v12-11-14]]

^<<v12-11-14,14>>^ Lá ela viu o rei, conforme o costume, de pé junto à coluna. Os oficiais e os tocadores de corneta estavam ao lado do rei, e todo o povo se alegrava ao som das cornetas. Então, Atalia rasgou suas vestes e gritou: "Traição! Traição! "

[[v12-11-15]]

^<<v12-11-15,15>>^ O sacerdote Joiada ordenou aos líderes dos batalhões de cem que estavam no comando das tropas: "Levem-na para fora por entre as fileiras, e matem à espada todo que a seguir". Pois o sacerdote dissera: "Ela não será morta no templo do Senhor".

[[v12-11-16]]

^<<v12-11-16,16>>^ Então eles a prenderam e a levaram ao lugar onde os cavalos entram no terreno do palácio, e lá a mataram.

[[v12-11-17]]

^<<v12-11-17,17>>^ E Joiada fez uma aliança entre o Senhor, o rei e o povo, para que fossem o povo do Senhor. Também fez um acordo entre o rei e o povo.

[[v12-11-18]]

^<<v12-11-18,18>>^ Então todo o povo foi ao templo de Baal e o derrubou. Despedaçaram os altares e os ídolos, e mataram Matã, sacerdote de Baal, em frente dos altares. E o sacerdote Joiada colocou guardas no templo do Senhor.

[[v12-11-19]]

^<<v12-11-19,19>>^ Levou consigo os líderes dos batalhões de cem dos cários, os guardas e todo o povo e, juntos, conduziram o rei do templo ao palácio, passando pela porta da guarda. O rei então ocupou seu lugar no trono real,

[[v12-11-20]]

^<<v12-11-20,20>>^ e todo o povo se alegrou. E a cidade acalmou-se depois que Atalia foi morta à espada no palácio.

[[v12-11-21]]

^<<v12-11-21,21>>^ Joás tinha sete anos de idade quando começou a reinar.

'''

xref:012-2-reis/012-2-reis-010.adoc#v12-10-0[&#60; Capítulo Anterior] | <<v12-11-0,Topo>> | xref:012-2-reis/012-2-reis-012.adoc#v12-12-0[Próximo Capítulo &#62;]