include::./index.adoc[]

[[v12-21-0]]
=== 2 Reis, 21
// nvi ?, NVI - Nova Versão Internacional

[[v12-21-1]]

^<<v12-21-1,1>>^ Manassés tinha doze anos de idade quando começou a reinar, e reinou cinqüenta e cinco anos em Jerusalém. O nome de sua mãe era Hefzibá.

[[v12-21-2]]

^<<v12-21-2,2>>^ Ele fez o que o Senhor reprova, imitando as práticas detestáveis das nações que o Senhor havia expulsado de diante dos israelitas.

[[v12-21-3]]

^<<v12-21-3,3>>^ Reconstruiu os altares idólatras que seu pai Ezequias havia demolido; também ergueu altares para Baal e fez um poste sagrado, como fizera Acabe, rei de Israel. Inclinou-se diante de todos os exércitos celestes e lhes prestou culto.

[[v12-21-4]]

^<<v12-21-4,4>>^ Construiu altares no templo do Senhor, do qual este tinha dito: "Em Jerusalém porei meu nome".

[[v12-21-5]]

^<<v12-21-5,5>>^ Nos dois pátios do templo do Senhor ele construiu altares para todos os exércitos celestes.

[[v12-21-6]]

^<<v12-21-6,6>>^ Chegou a queimar o próprio filho em sacrifício, praticou feitiçaria e adivinhação e consultou médiuns e espíritas. Fez o que o Senhor reprova, provocando-o à ira.

[[v12-21-7]]

^<<v12-21-7,7>>^ Ele tomou o poste sagrado que havia feito e o pôs no templo, do qual o Senhor tinha dito a Davi e a seu filho Salomão: "Neste templo e em Jerusalém, que escolhi dentre todas as tribos de Israel, porei meu nome para sempre.

[[v12-21-8]]

^<<v12-21-8,8>>^ Não farei os pés dos israelitas andarem errantes novamente, longe da terra que dei aos seus antepassados, se tão-somente tiverem o cuidado de fazer tudo o que lhes ordenei e obedecer à toda a Lei que meu servo Moisés lhes deu".

[[v12-21-9]]

^<<v12-21-9,9>>^ Mas o povo não quis ouvir. Manassés os desviou, a ponto de fazerem pior do que as nações que o Senhor havia destruído diante dos israelitas.

[[v12-21-10]]

^<<v12-21-10,10>>^ E o Senhor disse por meio dos seus servos, os profetas:

[[v12-21-11]]

^<<v12-21-11,11>>^ "Manassés, rei de Judá, cometeu esses atos repugnantes. Agiu pior do que os amorreus que o antecederam e também levou Judá a pecar com os ídolos que fizera.

[[v12-21-12]]

^<<v12-21-12,12>>^ Portanto, assim diz o Senhor, o Deus de Israel: Causarei uma tal desgraça em Jerusalém e em Judá que os ouvidos de quem ouvir a respeito ficarão zumbindo.

[[v12-21-13]]

^<<v12-21-13,13>>^ Estenderei sobre Jerusalém o fio de medir utilizado contra Samaria e o fio de prumo usado contra a família de Acabe. Limparei Jerusalém como se lava um prato, lavando-o e virando-o de cabeça para baixo.

[[v12-21-14]]

^<<v12-21-14,14>>^ Abandonarei o remanescente da minha herança e o entregarei nas mãos de seus inimigos. Serão despojados e saqueados por todos os seus adversários,

[[v12-21-15]]

^<<v12-21-15,15>>^ pois fizeram o que eu reprovo e me provocaram à ira, desde o dia em que seus antepassados saíram do Egito até hoje".

[[v12-21-16]]

^<<v12-21-16,16>>^ Manassés também derramou tanto sangue inocente que encheu Jerusalém de um lado a outro; além disso levou Judá a cometer pecado, a fim de que fizessem o que o Senhor reprova.

[[v12-21-17]]

^<<v12-21-17,17>>^ Os demais acontecimentos do reinado de Manassés e todas as suas realizações, inclusive o pecado que cometeu, estão escritos no livro dos registros históricos dos reis de Judá.

[[v12-21-18]]

^<<v12-21-18,18>>^ Manassés descansou com seus antepassados e foi sepultado no jardim do seu palácio, o jardim de Uzá. E seu filho Amom foi o seu sucessor.

[[v12-21-19]]

^<<v12-21-19,19>>^ Amom tinha vinte e dois anos de idade quando começou a reinar, e reinou dois anos em Jerusalém. O nome de sua mãe era Mesulemete, filha de Haruz; ela era de Jotbá.

[[v12-21-20]]

^<<v12-21-20,20>>^ Ele fez o que o Senhor reprova, como fizera Manassés, seu pai.

[[v12-21-21]]

^<<v12-21-21,21>>^ Imitou o seu pai em tudo; prestou culto aos ídolos aos quais seu pai havia cultuado e inclinou-se diante deles.

[[v12-21-22]]

^<<v12-21-22,22>>^ Abandonou o Senhor, o Deus de seus antepassados e não andou no caminho do Senhor.

[[v12-21-23]]

^<<v12-21-23,23>>^ Os oficiais de Amom conspiraram contra ele e o assassinaram em seu palácio.

[[v12-21-24]]

^<<v12-21-24,24>>^ Mas o povo matou todos os que haviam conspirado contra o rei Amom, e a seu filho Josias proclamou rei em seu lugar.

[[v12-21-25]]

^<<v12-21-25,25>>^ Os demais acontecimentos do reinado de Amom e as suas realizações, estão escritos no livro dos registros históricos dos reis de Judá.

[[v12-21-26]]

^<<v12-21-26,26>>^ Ele foi sepultado em seu túmulo no jardim de Uzá. Seu filho Josias foi o seu sucessor.

'''

xref:012-2-reis/012-2-reis-020.adoc#v12-20-0[&#60; Capítulo Anterior] | <<v12-21-0,Topo>> | xref:012-2-reis/012-2-reis-022.adoc#v12-22-0[Próximo Capítulo &#62;]