include::./index.adoc[]

[[v12-1-0]]
=== 2 Reis, 1
// nvi ?, NVI - Nova Versão Internacional

[[v12-1-1]]

^<<v12-1-1,1>>^ Depois da morte de Acabe, Moabe rebelou-se contra Israel.

[[v12-1-2]]

^<<v12-1-2,2>>^ Certo dia, Acazias caiu da sacada do seu quarto no palácio de Samaria, e ficou muito ferido. Então enviou mensageiros para consultar Baal-Zebube, deus de Ecrom, para saber se ele se recuperaria.

[[v12-1-3]]

^<<v12-1-3,3>>^ Mas o anjo do Senhor disse ao tesbita Elias: "Vá encontrar-se com os mensageiros do rei de Samaria e lhes pergunte: ‘Acaso não há Deus em Israel? Por que vocês vão consultar Baal-Zebube, deus de Ecrom? ’

[[v12-1-4]]

^<<v12-1-4,4>>^ Por isso, assim diz o Senhor: ‘Você não se levantará mais dessa cama e certamente morrerá! ’ " E assim Elias se foi.

[[v12-1-5]]

^<<v12-1-5,5>>^ Quando os mensageiros voltaram ao rei, ele lhes perguntou: "Por que vocês voltaram? "

[[v12-1-6]]

^<<v12-1-6,6>>^ Eles responderam: "Um homem veio ao nosso encontro e nos disse: ‘Voltem ao rei que os enviou e digam-lhe: Assim diz o Senhor: "Acaso não há Deus em Israel? Por que você mandou consultar Baal-Zebube, deus de Ecrom? Por isso você não se levantará mais dessa cama e certamente morrerá! " ’ "

[[v12-1-7]]

^<<v12-1-7,7>>^ O rei lhes perguntou: "Como era o homem que os encontrou e lhes disse isso? "

[[v12-1-8]]

^<<v12-1-8,8>>^ Eles responderam: "Ele vestia roupas de pêlos e usava um cinto de couro". O rei concluiu: "Era o tesbita Elias".

[[v12-1-9]]

^<<v12-1-9,9>>^ Em seguida mandou um oficial com cinqüenta soldados procurar Elias. O oficial o encontrou sentado no alto de uma colina, e lhe disse: "Homem de Deus, o rei ordena que você desça"

[[v12-1-10]]

^<<v12-1-10,10>>^ Elias respondeu ao oficial: "Se sou homem de Deus, que desça fogo do céu e consuma você e seus cinqüenta soldados! " E desceu fogo do céu e consumiu o oficial e seus soldados.

[[v12-1-11]]

^<<v12-1-11,11>>^ Depois disso o rei enviou outro oficial com mais cinqüenta soldados. E ele disse a Elias: "Homem de Deus o rei ordena que você desça imediatamente".

[[v12-1-12]]

^<<v12-1-12,12>>^ Respondeu Elias: "Se sou homem de Deus, que desça fogo do céu e consuma você e seus cinqüenta soldados! " De novo fogo de Deus desceu do céu e consumiu o oficial e seus soldados.

[[v12-1-13]]

^<<v12-1-13,13>>^ Então o rei enviou um terceiro oficial com outros cinqüenta soldados. O oficial subiu o monte, caiu de joelhos diante de Elias e implorou: "Homem de Deus, tenha consideração por minha vida e pela vida destes cinqüenta soldados, teus servos!

[[v12-1-14]]

^<<v12-1-14,14>>^ Sei que desceu fogo do céu e consumiu os dois primeiros oficiais com todos os seus soldados. Mas agora tenha consideração por minha vida! "

[[v12-1-15]]

^<<v12-1-15,15>>^ O anjo do Senhor disse a Elias: "Acompanhe-o; não tenha medo dele". Então Elias se levantou, desceu com ele e foi falar com o rei.

[[v12-1-16]]

^<<v12-1-16,16>>^ Ao chegar, disse ao rei: "Assim diz o Senhor: Acaso não há Deus em Israel? Por que você mandou consultar Baal-Zebube, deus de Ecrom? Por isso, você não se levantará mais dessa cama e certamente morrerá! "

[[v12-1-17]]

^<<v12-1-17,17>>^ E Acazias morreu, conforme a palavra do Senhor, anunciada por Elias. Como não tinha filhos, Jorão foi o seu sucessor no segundo ano do reinado de Jeorão, rei de Judá, filho de Josafá.

[[v12-1-18]]

^<<v12-1-18,18>>^ Os demais acontecimentos do reinado de Acazias e suas realizações estão escritos nos registros históricos dos reis de Israel.

'''

xref:011-1-reis/011-1-reis-022.adoc#v11-22-0[&#60; Capítulo Anterior] | <<v12-1-0,Topo>> | xref:012-2-reis/012-2-reis-002.adoc#v12-2-0[Próximo Capítulo &#62;]