include::./index.adoc[]

[[v12-14-0]]
=== 2 Reis, 14
// nvi ?, NVI - Nova Versão Internacional

[[v12-14-1]]

^<<v12-14-1,1>>^ No segundo ano do reinado de Jeoás, filho de Jeoacaz, rei de Israel, Amazias, filho de Joás, rei de Judá, começou a reinar.

[[v12-14-2]]

^<<v12-14-2,2>>^ Ele tinha vinte e cinco anos de idade quando começou a reinar, e reinou vinte e nove anos em Jerusalém. O nome de sua mãe era Jeoadã; ela era de Jerusalém.

[[v12-14-3]]

^<<v12-14-3,3>>^ Ele fez o que o Senhor aprova, mas não como Davi, seu predecessor. Em tudo seguiu o exemplo do seu pai Joás.

[[v12-14-4]]

^<<v12-14-4,4>>^ Contudo, os altares não foram derrubados; o povo continuava a oferecer sacrifícios e a queimar incenso neles.

[[v12-14-5]]

^<<v12-14-5,5>>^ Quando sentiu que tinha o reino sob pleno controle, mandou executar os oficiais que haviam assassinado o rei, seu pai.

[[v12-14-6]]

^<<v12-14-6,6>>^ Contudo, não matou os filhos dos assassinos, de acordo com o que está escrito no livro da Lei de Moisés, onde o Senhor ordenou: "Os pais não morrerão no lugar dos filhos, nem os filhos no lugar dos pais; cada um morrerá pelo seu próprio pecado".

[[v12-14-7]]

^<<v12-14-7,7>>^ Foi ele que derrotou dez mil edomitas no vale do Sal e conquistou a cidade de Selá em combate, dando-lhe o nome de Jocteel, nome que tem até hoje.

[[v12-14-8]]

^<<v12-14-8,8>>^ Então Amazias enviou mensageiros a Jeoás, filho de Jeoacaz e neto de Jeú, rei de Israel, com este desafio: "Venha me enfrentar".

[[v12-14-9]]

^<<v12-14-9,9>>^ Contudo, Jeoás respondeu a Amazias: "O espinheiro do Líbano enviou uma mensagem ao cedro do Líbano: ‘Dê sua filha em casamento a meu filho’. Mas um animal selvagem do Líbano veio e pisoteou o espinheiro.

[[v12-14-10]]

^<<v12-14-10,10>>^ De fato, você derrotou Edom e agora está arrogante. Comemore a sua vitória, mas fique em casa! Por que provocar uma desgraça que levará você e também Judá à ruína? "

[[v12-14-11]]

^<<v12-14-11,11>>^ Amazias, porém, não quis ouvi-lo, de modo que Jeoás, rei de Israel, o atacou. Ele e Amazias, rei de Judá, enfrentaram-se em Bete-Semes, em Judá.

[[v12-14-12]]

^<<v12-14-12,12>>^ Judá foi derrotado por Israel, e seus soldados fugiram para as suas casas.

[[v12-14-13]]

^<<v12-14-13,13>>^ Jeoás capturou Amazias, filho de Joás e neto de Acazias, em Bete-Semes. Então Jeoás foi a Jerusalém e derrubou cento e oitenta metros do muro da cidade, desde a porta de Efraim até a porta da Esquina.

[[v12-14-14]]

^<<v12-14-14,14>>^ Ele se apoderou de todo o ouro, de toda a prata e todos os utensílios encontrados no templo do Senhor e nos tesouros do palácio real. Também fez reféns e, então, voltou para Samaria.

[[v12-14-15]]

^<<v12-14-15,15>>^ Os demais acontecimentos do reinado de Jeoás, os seus feitos e todas as suas realizações, inclusive sua guerra contra Amazias, rei de Judá, estão escritos nos registros históricos dos reis de Israel.

[[v12-14-16]]

^<<v12-14-16,16>>^ Jeoás descansou com seus antepassados e foi sepultado com os reis de Israel em Samaria. E seu filho Jeroboão o sucedeu como rei.

[[v12-14-17]]

^<<v12-14-17,17>>^ Amazias, filho de Joás, rei de Judá, viveu ainda mais quinze anos depois da morte de Jeoás, filho de Jeoacaz, rei de Israel.

[[v12-14-18]]

^<<v12-14-18,18>>^ Os demais acontecimentos do reinado de Amazias estão escritos nos registros históricos dos reis de Judá.

[[v12-14-19]]

^<<v12-14-19,19>>^ Vítima de uma conspiração em Jerusalém, ele fugiu para Láquis, mas o perseguiram até lá e o mataram.

[[v12-14-20]]

^<<v12-14-20,20>>^ Ele foi trazido de volta a cavalo, e sepultado em Jerusalém junto aos seus antepassados, na cidade de Davi.

[[v12-14-21]]

^<<v12-14-21,21>>^ Então todo o povo de Judá proclamou rei a Azarias, de dezesseis anos de idade, no lugar de seu pai, Amazias.

[[v12-14-22]]

^<<v12-14-22,22>>^ Foi ele quem reconquistou e reconstruiu a cidade de Elate para Judá, depois que Amazias descansou com os seus antepassados.

[[v12-14-23]]

^<<v12-14-23,23>>^ No décimo quinto ano do reinado de Amazias, filho de Joás, rei de Judá, Jeroboão, filho de Jeoás, rei de Israel, tornou-se rei em Samaria e reinou quarenta e um anos.

[[v12-14-24]]

^<<v12-14-24,24>>^ Ele fez o que o Senhor reprova e não se desviou de nenhum dos pecados que Jeroboão, filho de Nebate, levara Israel a cometer.

[[v12-14-25]]

^<<v12-14-25,25>>^ Foi ele quem restabeleceu as fronteiras de Israel desde Lebo-Hamate até o mar da Arabá, conforme a palavra do Senhor, Deus de Israel, anunciada pelo seu servo Jonas, filho de Amitai, profeta de Gate-Héfer.

[[v12-14-26]]

^<<v12-14-26,26>>^ O Senhor viu a amargura com que todos em Israel, tanto escravos quanto livres, estavam sofrendo; não havia ninguém para socorrê-los.

[[v12-14-27]]

^<<v12-14-27,27>>^ Visto que o Senhor não dissera que apagaria o nome de Israel de debaixo do céu, ele os libertou pela mão de Jeroboão, filho de Jeoás.

[[v12-14-28]]

^<<v12-14-28,28>>^ Os demais acontecimentos do reinado de Jeroboão, os seus feitos e as suas realizações militares, inclusive a maneira pela qual recuperou para Israel Damasco e Hamate, que haviam pertencido a Iaudi, estão escritos nos registros históricos dos reis de Israel.

[[v12-14-29]]

^<<v12-14-29,29>>^ Jeroboão descansou com seus antepassados, os reis de Israel. Seu filho Zacarias foi o seu sucessor.

'''

xref:012-2-reis/012-2-reis-013.adoc#v12-13-0[&#60; Capítulo Anterior] | <<v12-14-0,Topo>> | xref:012-2-reis/012-2-reis-015.adoc#v12-15-0[Próximo Capítulo &#62;]