include::./index.adoc[]

[[v12-5-0]]
=== 2 Reis, 5
// nvi ?, NVI - Nova Versão Internacional

[[v12-5-1]]

^<<v12-5-1,1>>^ Naamã, comandante do exército do rei da Síria, era muito respeitado e honrado pelo seu senhor, pois por meio dele o Senhor dera vitória à Síria. Mas esse grande guerreiro ficou leproso.

[[v12-5-2]]

^<<v12-5-2,2>>^ Ora, tropas da Síria haviam atacado Israel e levado cativa uma menina, que passou a servir à mulher de Naamã.

[[v12-5-3]]

^<<v12-5-3,3>>^ Um dia ela disse à sua senhora: "Se o meu senhor procurasse o profeta que está em Samaria, ele o curaria da lepra".

[[v12-5-4]]

^<<v12-5-4,4>>^ Naamã foi contar ao seu senhor o que a menina israelita dissera.

[[v12-5-5]]

^<<v12-5-5,5>>^ O rei da Síria respondeu: "Vá. Eu lhe darei uma carta que você entregará ao rei de Israel". Então Naamã partiu, levando consigo trezentos e cinqüenta quilos de prata, setenta e dois quilos de ouro e dez mudas de roupas finas.

[[v12-5-6]]

^<<v12-5-6,6>>^ A carta que levou ao rei de Israel dizia: "Junto com esta carta estou te enviando meu oficial Naamã, para que o cures da lepra".

[[v12-5-7]]

^<<v12-5-7,7>>^ Assim que o rei de Israel leu a carta, rasgou as vestes e disse: "Por acaso sou Deus, capaz de conceder vida ou morte? Por que este homem me envia alguém para que eu o cure da lepra? Vejam como ele procura um motivo para se desentender comigo! "

[[v12-5-8]]

^<<v12-5-8,8>>^ Quando Eliseu, o homem de Deus, soube que o rei de Israel havia rasgado suas vestes, mandou-lhe esta mensagem: "Por que rasgaste tuas vestes? Envia o homem a mim, e ele saberá que há profeta em Israel".

[[v12-5-9]]

^<<v12-5-9,9>>^ Então, Naamã foi com seus cavalos e carros e parou à porta da casa de Eliseu.

[[v12-5-10]]

^<<v12-5-10,10>>^ Eliseu enviou um mensageiro para lhe dizer: "Vá e lave-se sete vezes no rio Jordão; sua pele será restaurada e você ficará purificado".

[[v12-5-11]]

^<<v12-5-11,11>>^ Mas Naamã ficou indignado e saiu dizendo: "Eu estava certo de que ele sairia para receber-me, invocaria de pé o nome do Senhor seu Deus, moveria a mão sobre o lugar afetado e me curaria da lepra.

[[v12-5-12]]

^<<v12-5-12,12>>^ Não são os rios Abana e Farfar, em Damasco, melhores do que todas as águas de Israel? Será que não poderia lavar-me neles e ser purificado? " Então, foi embora dali furioso.

[[v12-5-13]]

^<<v12-5-13,13>>^ Mas os seus servos lhe disseram: "Meu pai, se o profeta lhe tivesse pedido alguma coisa difícil, o senhor não faria? Quanto mais, quando ele apenas lhe diz para que se lave e seja purificado! "

[[v12-5-14]]

^<<v12-5-14,14>>^ Assim ele desceu ao Jordão e mergulhou sete vezes conforme a ordem do homem de Deus; ele foi purificado e sua pele tornou-se como a de uma criança.

[[v12-5-15]]

^<<v12-5-15,15>>^ Então Naamã e toda a sua comitiva voltaram à casa do homem de Deus. Ao chegar diante do profeta, Naamã lhe disse: "Agora sei que não há Deus em nenhum outro lugar, senão em Israel. Por favor, aceita um presente de teu servo".

[[v12-5-16]]

^<<v12-5-16,16>>^ O profeta respondeu: "Juro pelo nome do Senhor, a quem sirvo, que nada aceitarei". Embora Naamã insistisse, ele recusou.

[[v12-5-17]]

^<<v12-5-17,17>>^ E disse Naamã: "Já que não aceitas o presente, ao menos permite que eu leve duas mulas carregadas de terra, pois teu servo nunca mais fará holocaustos e sacrifícios a nenhum outro deus senão ao Senhor.

[[v12-5-18]]

^<<v12-5-18,18>>^ Mas que o Senhor me perdoe por uma única coisa: quando meu senhor vai adorar no templo de Rimom, eu também tenho que me ajoelhar ali pois ele se apóia em meu braço. Que o Senhor perdoe o teu servo por isso".

[[v12-5-19]]

^<<v12-5-19,19>>^ Disse Eliseu: "Vá em paz". Quando Naamã já estava a certa distância,

[[v12-5-20]]

^<<v12-5-20,20>>^ Geazi, servo de Eliseu, o homem de Deus, pensou: "Meu senhor foi bom demais para Naamã, aquele arameu, não aceitando o que ele lhe ofereceu. Juro pelo nome do Senhor que correrei atrás dele para ver se ganho alguma coisa".

[[v12-5-21]]

^<<v12-5-21,21>>^ Então Geazi correu para alcançar Naamã, que, vendo-o se aproximar, desceu da carruagem para encontrá-lo e perguntou: "Está tudo bem? "

[[v12-5-22]]

^<<v12-5-22,22>>^ Geazi respondeu: "Sim, tudo bem. Mas o meu senhor enviou-me para dizer que dois jovens, discípulos dos profetas, acabaram de chegar, vindos dos montes de Efraim. Por favor, dê-lhes trinta e cinco quilos de prata e duas mudas de roupas finas".

[[v12-5-23]]

^<<v12-5-23,23>>^ "Claro", respondeu Naamã, "leve setenta quilos". Ele insistiu com Geazi para que aceitasse e colocou os setenta quilos de prata em duas sacolas, com as duas mudas de roupas, entregando tudo a dois de seus servos, os quais foram à frente de Geazi, levando as sacolas.

[[v12-5-24]]

^<<v12-5-24,24>>^ Quando Geazi chegou à colina onde morava, pegou as sacolas dos servos e guardou-as em casa. Mandou os homens de volta, e eles partiram.

[[v12-5-25]]

^<<v12-5-25,25>>^ Então entrou e apresentou-se ao seu senhor Eliseu. E este perguntou: "Onde você esteve, Geazi? " Geazi respondeu: "Teu servo não foi a lugar algum".

[[v12-5-26]]

^<<v12-5-26,26>>^ Mas Eliseu lhe disse: "Você acha que eu não estava com você em espírito quando o homem desceu da carruagem para encontrar-se com você? Este não era o momento de aceitar prata nem roupas, nem de cobiçar olivais, vinhas, ovelhas, bois, servos e servas.

[[v12-5-27]]

^<<v12-5-27,27>>^ Por isso a lepra de Naamã atingirá você e os seus descendentes para sempre". Então Geazi saiu da presença de Eliseu já leproso, parecido com neve.

'''

xref:012-2-reis/012-2-reis-004.adoc#v12-4-0[&#60; Capítulo Anterior] | <<v12-5-0,Topo>> | xref:012-2-reis/012-2-reis-006.adoc#v12-6-0[Próximo Capítulo &#62;]