include::./index.adoc[]

[[v12-7-0]]
=== 2 Reis, 7
// nvi ?, NVI - Nova Versão Internacional

[[v12-7-1]]

^<<v12-7-1,1>>^ Eliseu respondeu: "Ouçam a palavra do Senhor! Assim diz o Senhor: Amanhã, por volta desta hora, na porta de Samaria, tanto uma medida de farinha como duas medidas de cevada serão vendidas por uma peça de prata".

[[v12-7-2]]

^<<v12-7-2,2>>^ O oficial, em cujo braço o rei estava se apoiando, disse ao homem de Deus: "Ainda que o Senhor abrisse as comportas do céu, será que isso poderia acontecer? " Mas Eliseu advertiu: "Você o verá com os próprios olhos, mas não comerá coisa alguma! "

[[v12-7-3]]

^<<v12-7-3,3>>^ Havia quatro leprosos junto à porta da cidade. Eles disseram uns aos outros: "Por que ficar aqui esperando a morte?

[[v12-7-4]]

^<<v12-7-4,4>>^ Se resolvermos entrar na cidade, morreremos de fome, mas se ficarmos aqui, também morreremos. Vamos, pois, ao acampamento dos arameus para nos render. Se eles nos pouparem, viveremos; se nos matarem, morreremos".

[[v12-7-5]]

^<<v12-7-5,5>>^ Ao anoitecer, eles foram ao acampamento dos arameus. Quando chegaram às imediações do acampamento, não havia ninguém ali,

[[v12-7-6]]

^<<v12-7-6,6>>^ pois o Senhor tinha feito os arameus ouvirem o ruído de um grande exército com cavalos e carros de guerra, de modo que disseram uns aos outros: "Ouçam, o rei de Israel contratou os reis dos hititas e dos egípcios para nos atacar! "

[[v12-7-7]]

^<<v12-7-7,7>>^ Então, para salvar suas vidas, fugiram ao anoitecer, abandonando tendas, cavalos e jumentos, deixando o acampamento como estava.

[[v12-7-8]]

^<<v12-7-8,8>>^ Tendo chegado às imediações do acampamento os leprosos entraram numa das tendas. Comeram e beberam; pegaram prata, ouro e roupas e saíram para esconder tudo. Depois voltaram e entraram noutra tenda, pegaram o que quiseram e esconderam isso também.

[[v12-7-9]]

^<<v12-7-9,9>>^ Então disseram uns aos outros: "Não estamos agindo certo. Este é um dia de boas notícias, e não podemos ficar calados. Se esperarmos até o amanhecer, seremos castigados. Vamos imediatamente contar tudo no palácio do rei".

[[v12-7-10]]

^<<v12-7-10,10>>^ Então foram e chamaram as sentinelas da porta da cidade e lhes contaram: "Entramos no acampamento arameu, e não vimos nem ouvimos ninguém. Havia apenas cavalos e jumentos amarrados, e tendas abandonadas".

[[v12-7-11]]

^<<v12-7-11,11>>^ As sentinelas da porta proclamaram a notícia, e ela foi anunciada dentro do palácio.

[[v12-7-12]]

^<<v12-7-12,12>>^ O rei se levantou de noite e disse aos seus conselheiros: "Eu lhes explicarei o que os arameus planejaram. Como sabem que estamos passando fome, deixaram o acampamento e se esconderam no campo, pensando: ‘Com certeza eles sairão, e então os pegaremos vivos e entraremos na cidade’ ".

[[v12-7-13]]

^<<v12-7-13,13>>^ Um de seus conselheiros respondeu: "Manda que alguns homens apanhem cinco dos cavalos que restam na cidade. O destino desses homens será o mesmo de todos os israelitas que ficarem, sim, como toda esta multidão condenada. Por isso vamos enviá-los para descobrir o que aconteceu".

[[v12-7-14]]

^<<v12-7-14,14>>^ Assim que prepararam dois carros de guerra com seus cavalos, o rei os enviou atrás do exército arameu, ordenando aos condutores: "Vão e descubram o que aconteceu".

[[v12-7-15]]

^<<v12-7-15,15>>^ Eles seguiram as pegadas do exército até o Jordão e encontraram todo o caminho cheio de roupas e armas que os arameus haviam deixado para trás enquanto fugiam. Os mensageiros voltaram e relataram tudo ao rei.

[[v12-7-16]]

^<<v12-7-16,16>>^ Então o povo saiu e saqueou o acampamento dos arameus. Assim, tanto uma medida de farinha como duas medidas de cevada passaram a ser vendidas por uma peça de prata, conforme o Senhor tinha dito.

[[v12-7-17]]

^<<v12-7-17,17>>^ Ora, o rei havia posto o oficial em cujo braço tinha se apoiado como encarregado da porta da cidade, mas quando o povo saiu, atropelou-o junto à porta, e ele morreu, conforme o homem de Deus havia predito quando o rei foi à sua casa.

[[v12-7-18]]

^<<v12-7-18,18>>^ Aconteceu conforme o homem de Deus dissera ao rei: "Amanhã, por volta desta hora, na porta de Samaria, tanto uma medida de farinha como duas medidas de cevada serão vendidas por uma peça de prata".

[[v12-7-19]]

^<<v12-7-19,19>>^ O oficial tinha contestado o homem de Deus perguntando: "Ainda que o Senhor abrisse as comportas do céu, será que isso poderia acontecer? " O homem de Deus havia respondido: "Você verá com os próprios olhos, mas não comerá coisa alguma! "

[[v12-7-20]]

^<<v12-7-20,20>>^ E foi exatamente isso que lhe aconteceu, pois o povo o pisoteou junto à porta da cidade, e ele morreu.

'''

xref:012-2-reis/012-2-reis-006.adoc#v12-6-0[&#60; Capítulo Anterior] | <<v12-7-0,Topo>> | xref:012-2-reis/012-2-reis-008.adoc#v12-8-0[Próximo Capítulo &#62;]