include::./index.adoc[]

[[v12-3-0]]
=== 2 Reis, 3
// nvi ?, NVI - Nova Versão Internacional

[[v12-3-1]]

^<<v12-3-1,1>>^ Jorão, filho de Acabe, tornou-se rei de Israel em Samaria no décimo oitavo ano de Josafá, rei de Judá, e reinou doze anos.

[[v12-3-2]]

^<<v12-3-2,2>>^ Fez o que o Senhor reprova, mas não como seu pai e sua mãe, pois derrubou a coluna sagrada de Baal, que seu pai havia feito.

[[v12-3-3]]

^<<v12-3-3,3>>^ No entanto, persistiu nos pecados que Jeroboão, filho de Nebate, levara Israel a cometer e deles não se afastou.

[[v12-3-4]]

^<<v12-3-4,4>>^ Ora, Messa, rei de Moabe, tinha muitos rebanhos e pagava como tributo ao rei de Israel cem mil cordeiros e a lã de cem mil carneiros.

[[v12-3-5]]

^<<v12-3-5,5>>^ Mas, depois que Acabe morreu, o rei de Moabe rebelou-se contra o rei de Israel.

[[v12-3-6]]

^<<v12-3-6,6>>^ E, naquela ocasião, o rei Jorão partiu de Samaria e mobilizou todo Israel.

[[v12-3-7]]

^<<v12-3-7,7>>^ Também enviou esta mensagem a Josafá, rei de Judá: "O rei de Moabe rebelou-se contra mim. Irás acompanhar-me na luta contra Moabe? " Ele respondeu: "Sim, eu irei. Serei teu aliado, os meus soldados e os teus, os meus cavalos e os teus serão um só exército".

[[v12-3-8]]

^<<v12-3-8,8>>^ E perguntou: "Por qual caminho atacaremos? " Respondeu Jorão: "Pelo deserto de Edom".

[[v12-3-9]]

^<<v12-3-9,9>>^ Então o rei de Israel partiu com os reis de Judá e de Edom. Depois de uma marcha de sete dias, já havia acabado a água para os homens e para os animais.

[[v12-3-10]]

^<<v12-3-10,10>>^ Exclamou, então, o rei de Israel: "E agora? Será que o Senhor ajuntou a nós, os três reis, para nos entregar nas mãos de Moabe? "

[[v12-3-11]]

^<<v12-3-11,11>>^ Mas Josafá perguntou: "Será que não há aqui profeta do Senhor, para que possamos consultar o Senhor por meio dele? " Um conselheiro do rei de Israel respondeu: "Eliseu, filho de Safate, está aqui. Ele era auxiliar de Elias".

[[v12-3-12]]

^<<v12-3-12,12>>^ Josafá prosseguiu: "A palavra do Senhor está com ele". Então o rei de Israel, Josafá e o rei de Edom foram falar com ele.

[[v12-3-13]]

^<<v12-3-13,13>>^ Eliseu disse ao rei de Israel: "Nada tenho a ver com você. Vá consultar os profetas de seu pai e de sua mãe". Mas o rei de Israel insistiu: "Não, pois foi o Senhor que ajuntou a nós, estes três reis, para entregar-nos nas mãos de Moabe".

[[v12-3-14]]

^<<v12-3-14,14>>^ Então Eliseu disse: "Juro pelo nome do Senhor dos Exércitos, a quem sirvo, que se não fosse por respeito a Josafá, rei de Judá, eu não olharia para você nem mesmo lhe daria atenção.

[[v12-3-15]]

^<<v12-3-15,15>>^ Mas agora tragam-me um harpista". Enquanto o harpista estava tocando, o poder do Senhor veio sobre Eliseu,

[[v12-3-16]]

^<<v12-3-16,16>>^ e ele disse: "Assim diz o Senhor: Cavem muitas cisternas neste vale.

[[v12-3-17]]

^<<v12-3-17,17>>^ Pois assim diz o Senhor: Vocês não verão vento nem chuva, contudo este vale ficará cheio de água, e vocês, seus rebanhos e seus outros animais beberão.

[[v12-3-18]]

^<<v12-3-18,18>>^ Mas para o Senhor isso ainda é pouco; ele também lhes entregará Moabe nas suas mãos.

[[v12-3-19]]

^<<v12-3-19,19>>^ Vocês destruirão todas as cidades fortificadas e todas as cidades importantes. Derrubarão toda árvore frutífera, taparão todas as fontes e encherão de pedras todas as terras de cultivo".

[[v12-3-20]]

^<<v12-3-20,20>>^ No dia seguinte, na hora do sacrifício da manhã, a água veio descendo da direção de Edom e alagou a região.

[[v12-3-21]]

^<<v12-3-21,21>>^ Quando os moabitas ficaram sabendo que os reis tinham vindo para atacá-los, todos os que eram capazes de empunhar armas, do mais jovem ao mais velho, foram convocados e posicionaram-se na fronteira.

[[v12-3-22]]

^<<v12-3-22,22>>^ Ao se levantarem na manhã seguinte, o sol refletia na água. Para os moabitas que estavam defronte dela, a água era vermelha como sangue.

[[v12-3-23]]

^<<v12-3-23,23>>^ Então gritaram: "É sangue! Os reis lutaram entre si e se mataram. Agora, ao saque, Moabe! "

[[v12-3-24]]

^<<v12-3-24,24>>^ Quando, porém, os moabitas chegaram ao acampamento de Israel, os israelitas os atacaram e os puseram em fuga. Entraram no território de Moabe e o arrasaram.

[[v12-3-25]]

^<<v12-3-25,25>>^ Destruíram as cidades, e quando passavam por um campo cultivável cada homem atirava uma pedra até que ficasse coberto. Taparam todas as fontes e derrubaram toda árvore frutífera. Só Quir-Haresete ficou com as pedras no lugar, mas homens armados de atiradeiras a cercaram e também a atacaram.

[[v12-3-26]]

^<<v12-3-26,26>>^ Quando o rei de Moabe viu que estava perdendo a batalha, reuniu setecentos homens armados de espadas para forçar a passagem, para alcançar o rei de Edom, mas fracassou.

[[v12-3-27]]

^<<v12-3-27,27>>^ Então pegou seu filho mais velho, que devia sucedê-lo como rei, e o sacrificou sobre o muro da cidade. Isso trouxe grande ira contra Israel, de modo que eles se retiraram e voltaram para sua própria terra.

'''

xref:012-2-reis/012-2-reis-002.adoc#v12-2-0[&#60; Capítulo Anterior] | <<v12-3-0,Topo>> | xref:012-2-reis/012-2-reis-004.adoc#v12-4-0[Próximo Capítulo &#62;]