include::./index.adoc[]

[[v12-2-0]]
=== 2 Reis, 2
// nvi ?, NVI - Nova Versão Internacional

[[v12-2-1]]

^<<v12-2-1,1>>^ Quando o Senhor levou Elias aos céus num redemoinho aconteceu o seguinte: Elias e Eliseu saíram de Gilgal,

[[v12-2-2]]

^<<v12-2-2,2>>^ e no caminho disse-lhe Elias: "Fique aqui, pois o Senhor me enviou a Betel". Eliseu, porém, disse: "Juro pelo nome do Senhor e por tua vida, que não te deixarei ir só". Então foram a Betel.

[[v12-2-3]]

^<<v12-2-3,3>>^ Em Betel os discípulos dos profetas foram falar com Eliseu e perguntaram: "Você sabe que hoje o Senhor vai levar para os céus o seu mestre, separando-o de você? " Respondeu Eliseu: "Sim, eu sei, mas não falem nisso".

[[v12-2-4]]

^<<v12-2-4,4>>^ Então Elias lhe disse: "Fique aqui, Eliseu, pois o Senhor me enviou a Jericó". Ele respondeu: "Juro pelo nome do Senhor e por tua vida, que não te deixarei ir só". Desceram então a Jericó.

[[v12-2-5]]

^<<v12-2-5,5>>^ Em Jericó os discípulos dos profetas foram falar com Eliseu e lhe perguntaram: "Você sabe que hoje o Senhor vai levar para os céus o seu mestre, separando-o de você? " Respondeu Eliseu: "Sim, eu sei, mas não falem nisso".

[[v12-2-6]]

^<<v12-2-6,6>>^ Em seguida Elias lhe disse: "Fique aqui, pois o Senhor me enviou ao rio Jordão". Ele respondeu: "Juro pelo nome do Senhor e por tua vida, que não te deixarei ir só! " Então partiram juntos.

[[v12-2-7]]

^<<v12-2-7,7>>^ Cinqüenta discípulos dos profetas os acompanharam e ficaram olhando a distância, quando Elias e Eliseu pararam à margem do Jordão.

[[v12-2-8]]

^<<v12-2-8,8>>^ Então Elias tirou o manto, enrolou-o e com ele bateu nas águas. As águas se dividiram, e os dois atravessaram a seco.

[[v12-2-9]]

^<<v12-2-9,9>>^ Depois de atravessar, Elias disse a Eliseu: "O que posso fazer por você antes que eu seja levado para longe de você? " Respondeu Eliseu: "Faze de mim o principal herdeiro de teu espírito profético".

[[v12-2-10]]

^<<v12-2-10,10>>^ Disse Elias: "Você fez um pedido difícil; mas, se você me vir quando eu for separado de você, terá o que pediu; do contrário, não será atendido".

[[v12-2-11]]

^<<v12-2-11,11>>^ De repente, enquanto caminhavam e conversavam, apareceu um carro de fogo, puxado por cavalos de fogo, que os separou, e Elias foi levado aos céus num redemoinho.

[[v12-2-12]]

^<<v12-2-12,12>>^ Quando viu isso, Eliseu gritou: "Meu pai! Meu pai! Tu eras como os carros de guerra e os cavaleiros de Israel! " E quando já não podia mais vê-lo, Eliseu pegou as próprias vestes e as rasgou ao meio.

[[v12-2-13]]

^<<v12-2-13,13>>^ Depois pegou o manto de Elias, que tinha caído, e voltou para a margem do Jordão.

[[v12-2-14]]

^<<v12-2-14,14>>^ Então bateu nas águas do rio com o manto e perguntou: "Onde está agora o Senhor, o Deus de Elias? " Tendo batido nas águas, essas se dividiram e ele atravessou.

[[v12-2-15]]

^<<v12-2-15,15>>^ Quando os discípulos dos profetas, vindos de Jericó, viram isso, disseram: "O espírito profético de Elias repousa sobre Eliseu". Então foram ao seu encontro, prostraram-se diante dele e disseram:

[[v12-2-16]]

^<<v12-2-16,16>>^ "Olha, nós, teus servos, temos cinqüenta homens fortes. Deixa-os sair à procura do teu mestre. Talvez o Espírito do Senhor o tenha levado e deixado em algum monte ou em algum vale". Respondeu Eliseu: "Não mandem ninguém".

[[v12-2-17]]

^<<v12-2-17,17>>^ Mas eles insistiram até que, constrangido, consentiu: "Podem mandar os homens". E mandaram cinqüenta homens, que procuraram Elias por três dias, mas não o encontraram.

[[v12-2-18]]

^<<v12-2-18,18>>^ Quando voltaram a Eliseu, que tinha ficado em Jericó, ele lhes falou: "Não lhes disse que não fossem? "

[[v12-2-19]]

^<<v12-2-19,19>>^ Alguns homens da cidade foram dizer a Eliseu: "Como podes ver, esta cidade está bem localizada, mas a água não é boa e a terra é improdutiva".

[[v12-2-20]]

^<<v12-2-20,20>>^ E disse ele: "Ponham sal numa tigela nova e tragam-na para mim". Quando a levaram,

[[v12-2-21]]

^<<v12-2-21,21>>^ ele foi à nascente, jogou o sal ali e disse: "Assim diz o Senhor: ‘Purifiquei esta água. Não causará mais mortes nem deixará a terra improdutiva’ ".

[[v12-2-22]]

^<<v12-2-22,22>>^ E até hoje a água permanece pura, conforme a palavra de Eliseu.

[[v12-2-23]]

^<<v12-2-23,23>>^ De Jericó Eliseu foi para Betel. No caminho, alguns meninos que vinham da cidade começaram a caçoar dele, gritando: "Suma daqui, careca! "

[[v12-2-24]]

^<<v12-2-24,24>>^ Voltando-se, olhou para eles e os amaldiçoou em nome do Senhor. Então, duas ursas saíram do bosque e despedaçaram quarenta e dois meninos.

[[v12-2-25]]

^<<v12-2-25,25>>^ De Betel prosseguiu até o monte Carmelo e dali voltou a Samaria.

'''

xref:012-2-reis/012-2-reis-001.adoc#v12-1-0[&#60; Capítulo Anterior] | <<v12-2-0,Topo>> | xref:012-2-reis/012-2-reis-003.adoc#v12-3-0[Próximo Capítulo &#62;]