include::./index.adoc[]

[[v12-15-0]]
=== 2 Reis, 15
// nvi ?, NVI - Nova Versão Internacional

[[v12-15-1]]

^<<v12-15-1,1>>^ No vigésimo sétimo ano do reinado de Jeroboão, rei de Israel, Azarias, filho de Amazias, rei de Judá, começou a reinar.

[[v12-15-2]]

^<<v12-15-2,2>>^ Tinha dezesseis anos de idade quando se tornou rei, e reinou cinqüenta e dois anos em Jerusalém. Sua mãe era de Jerusalém e chamava-se Jecolias.

[[v12-15-3]]

^<<v12-15-3,3>>^ Ele fez o que o Senhor aprova, tal como o seu pai Amazias.

[[v12-15-4]]

^<<v12-15-4,4>>^ Contudo, os altares idólatras não foram derrubados; o povo continuava a oferecer sacrifícios e a queimar incenso neles.

[[v12-15-5]]

^<<v12-15-5,5>>^ O Senhor feriu o rei com lepra, até o dia de sua morte. Durante todo esse tempo morou numa casa separada. Jotão, filho do rei, tomava conta do palácio e governava o povo.

[[v12-15-6]]

^<<v12-15-6,6>>^ Os demais acontecimentos do reinado de Azarias e todas as suas realizações, estão escritos nos registros históricos dos reis de Judá.

[[v12-15-7]]

^<<v12-15-7,7>>^ Azarias descansou com os seus antepassados e foi sepultado junto a eles na cidade de Davi. Seu filho Jotão foi o seu sucessor.

[[v12-15-8]]

^<<v12-15-8,8>>^ No trigésimo oitavo ano do reinado de Azarias, rei de Judá, Zacarias, filho de Jeroboão, tornou-se rei de Israel em Samaria, e reinou seis meses.

[[v12-15-9]]

^<<v12-15-9,9>>^ Ele fez o que o Senhor reprova, como seus antepassados haviam feito. Não se desviou dos pecados que Jeroboão, filho de Nebate, levara Israel a cometer.

[[v12-15-10]]

^<<v12-15-10,10>>^ Salum, filho de Jabes, conspirou contra Zacarias. Ele o atacou na frente do povo, assassinou-o e foi o seu sucessor.

[[v12-15-11]]

^<<v12-15-11,11>>^ Os demais acontecimentos do reinado de Zacarias estão escritos nos registros históricos dos reis de Israel.

[[v12-15-12]]

^<<v12-15-12,12>>^ Assim se cumpriu a palavra do Senhor anunciada a Jeú: "Seus descendentes ocuparão o trono de Israel até a quarta geração".

[[v12-15-13]]

^<<v12-15-13,13>>^ Salum, filho de Jabes, começou a reinar no trigésimo oitavo ano do reinado de Uzias, rei de Judá, e reinou um mês em Samaria.

[[v12-15-14]]

^<<v12-15-14,14>>^ Então Menaém, filho de Gadi, foi de Tirza a Samaria e atacou a Salum, filho de Jabes, assassinou-o e foi o seu sucessor.

[[v12-15-15]]

^<<v12-15-15,15>>^ Os demais acontecimentos do reinado de Salum e a conspiração que liderou estão escritos nos registros históricos dos reis de Israel.

[[v12-15-16]]

^<<v12-15-16,16>>^ Naquela ocasião, Menaém, partindo de Tirza, atacou Tifsa e todos que estavam na cidade e seus arredores, porque eles se recusaram a abrir as portas da cidade. Saqueou Tifsa e rasgou ao meio todas as mulheres grávidas.

[[v12-15-17]]

^<<v12-15-17,17>>^ No trigésimo nono ano do reinado de Azarias, rei de Judá, Menaém, filho de Gadi, tornou-se rei de Israel, e reinou dez anos em Samaria.

[[v12-15-18]]

^<<v12-15-18,18>>^ Ele fez o que o Senhor reprova. Durante todo o seu reinado não se desviou dos pecados que Jeroboão, filho de Nebate, levara Israel a cometer.

[[v12-15-19]]

^<<v12-15-19,19>>^ Então Pul, rei da Assíria, invadiu o país, e Menaém lhe deu trinta e cinco toneladas de prata para obter seu apoio e manter-se no trono.

[[v12-15-20]]

^<<v12-15-20,20>>^ Menaém cobrou essa quantia de Israel. Todos os homens de posses tiveram de contribuir com seiscentos gramas de prata no pagamento ao rei da Assíria. Então ele interrompeu a invasão e foi embora.

[[v12-15-21]]

^<<v12-15-21,21>>^ Os demais acontecimentos do reinado de Menaém e todas as suas realizações, estão escritos nos registros históricos dos reis de Israel.

[[v12-15-22]]

^<<v12-15-22,22>>^ Menaém descansou com seus antepassados, e seu filho Pecaías foi o seu sucessor.

[[v12-15-23]]

^<<v12-15-23,23>>^ No qüinquagésimo ano do reinado de Azarias, rei de Judá, Pecaías, filho de Menaém, tornou-se rei de Israel em Samaria, e reinou dois anos.

[[v12-15-24]]

^<<v12-15-24,24>>^ Pecaías fez o que o Senhor reprova. Não se desviou dos pecados que Jeroboão, filho de Nebate, levara Israel a cometer.

[[v12-15-25]]

^<<v12-15-25,25>>^ Um de seus principais oficiais, Peca, filho de Remalias, conspirou contra ele. Levando consigo cinqüenta homens de Gileade, assassinou Pecaías juntamente com Argobe e Arié, na cidadela do palácio real em Samaria. Assim Peca matou Pecaías e foi o seu sucessor.

[[v12-15-26]]

^<<v12-15-26,26>>^ Os demais acontecimentos do reinado de Pecaías e todas as suas realizações estão escritos nos registros históricos dos reis de Israel.

[[v12-15-27]]

^<<v12-15-27,27>>^ No qüinquagésimo segundo ano do reinado de Azarias, rei de Judá, Peca, filho de Remalias, tornou-se rei de Israel em Samaria, e reinou vinte anos.

[[v12-15-28]]

^<<v12-15-28,28>>^ Ele fez o que o Senhor reprova. Não se desviou dos pecados que Jeroboão, filho de Nebate, levara Israel a cometer.

[[v12-15-29]]

^<<v12-15-29,29>>^ Durante seu reinado, Tiglate-Pileser, rei da Assíria, invadiu e conquistou Ijom, Abel-Bete-Maaca, Janoa, Quedes e Hazor. Tomou Gileade e a Galiléia, inclusive toda a terra de Naftali, e deportou o povo para a Assíria.

[[v12-15-30]]

^<<v12-15-30,30>>^ Então Oséias, filho de Elá, conspirou contra Peca, filho de Remalias. Ele o atacou e o assassinou, tornando-se seu sucessor no vigésimo ano do reinado de Jotão, filho de Uzias.

[[v12-15-31]]

^<<v12-15-31,31>>^ Os demais acontecimentos do reinado de Peca e todas as suas realizações, estão escritos nos registros históricos dos reis de Israel.

[[v12-15-32]]

^<<v12-15-32,32>>^ No segundo ano do reinado de Peca, filho de Remalias, rei de Israel, Jotão, filho de Uzias, rei de Judá, começou a reinar.

[[v12-15-33]]

^<<v12-15-33,33>>^ Ele tinha vinte e cinco anos de idade quando começou a reinar, e reinou dezesseis anos em Jerusalém. O nome da sua mãe era Jerusa, filha de Zadoque.

[[v12-15-34]]

^<<v12-15-34,34>>^ Ele fez o que o Senhor aprova, tal como seu pai Uzias.

[[v12-15-35]]

^<<v12-15-35,35>>^ Contudo, os altares idólatras não foram derrubados; o povo continuou a oferecer sacrifícios e a queimar incenso neles. Jotão reconstruiu a porta superior do templo do Senhor.

[[v12-15-36]]

^<<v12-15-36,36>>^ Os demais acontecimentos do reinado de Jotão e as suas realizações, estão escritos nos registros históricos dos reis de Judá.

[[v12-15-37]]

^<<v12-15-37,37>>^ ( Naqueles dias o Senhor começou a enviar Rezim, rei da Síria, e Peca, filho de Remalias, contra Judá. )

[[v12-15-38]]

^<<v12-15-38,38>>^ Jotão descansou com os seus antepassados e foi sepultado junto a eles na cidade de Davi, cidade de seu pai. Seu filho Acaz foi o seu sucessor.

'''

xref:012-2-reis/012-2-reis-014.adoc#v12-14-0[&#60; Capítulo Anterior] | <<v12-15-0,Topo>> | xref:012-2-reis/012-2-reis-016.adoc#v12-16-0[Próximo Capítulo &#62;]