include::./index.adoc[]

[[v12-13-0]]
=== 2 Reis, 13
// nvi ?, NVI - Nova Versão Internacional

[[v12-13-1]]

^<<v12-13-1,1>>^ No vigésimo terceiro ano do reinado de Joás, filho de Acazias, rei de Judá, Jeoacaz, filho de Jeú, tornou-se rei de Israel em Samaria, e reinou dezessete anos.

[[v12-13-2]]

^<<v12-13-2,2>>^ E fez o que o Senhor reprova, seguindo os pecados que Jeroboão, filho de Nebate, levara Israel a cometer; e não se afastou deles.

[[v12-13-3]]

^<<v12-13-3,3>>^ Por isso a ira do Senhor se acendeu contra Israel, e por longo tempo ele os manteve sob o poder de Hazael, rei da Síria, e de seu filho Ben-Hadade.

[[v12-13-4]]

^<<v12-13-4,4>>^ Então Jeoacaz buscou o favor do Senhor, e este o ouviu, pois viu o quanto o rei da Síria oprimia Israel.

[[v12-13-5]]

^<<v12-13-5,5>>^ O Senhor providenciou um libertador para Israel, e eles escaparam do poder da Síria. Assim os israelitas moraram em suas casas como anteriormente.

[[v12-13-6]]

^<<v12-13-6,6>>^ Mas continuaram a praticar os pecados que a dinastia de Jeroboão havia levado Israel a cometer, permanecendo neles. Inclusive a coluna sagrada permanecia de pé em Samaria.

[[v12-13-7]]

^<<v12-13-7,7>>^ Nada havia sobrado do exército de Jeoacaz, com exceção de cinqüenta cavaleiros, dez carros de guerra e dez mil soldados de infantaria, pois o rei da Síria havia destruído o restante, reduzindo-o a pó.

[[v12-13-8]]

^<<v12-13-8,8>>^ Os demais acontecimentos do reinado de Jeoacaz, os seus feitos e tudo o que realizou, estão escritos nos registros históricos dos reis de Israel.

[[v12-13-9]]

^<<v12-13-9,9>>^ Jeoacaz descansou com seus antepassados e foi sepultado em Samaria. Seu filho Jeoás foi o seu sucessor.

[[v12-13-10]]

^<<v12-13-10,10>>^ No trigésimo sétimo ano do reinado de Joás, rei de Judá, Jeoás, filho de Jeoacaz, tornou-se rei de Israel em Samaria, e reinou dezesseis anos.

[[v12-13-11]]

^<<v12-13-11,11>>^ Ele fez o que o Senhor reprova e não se desviou de nenhum dos pecados que Jeroboão, filho de Nebate, levara Israel a cometer; antes permaneceu neles.

[[v12-13-12]]

^<<v12-13-12,12>>^ Os demais acontecimentos do reinado de Jeoás, os seus feitos e as suas realizações, inclusive sua guerra contra Amazias, rei de Judá, estão escritos no livro dos registros históricos dos reis de Israel.

[[v12-13-13]]

^<<v12-13-13,13>>^ Jeoás descansou com seus antepassados, e Jeroboão o sucedeu no trono. Jeoás foi sepultado com os reis de Israel, em Samaria.

[[v12-13-14]]

^<<v12-13-14,14>>^ Ora, Eliseu estava sofrendo da doença da qual morreria. Então Jeoás, rei de Israel, foi visitá-lo e, curvado sobre ele, chorou gritando: "Meu pai! Meu pai! Tu és como os carros e os cavaleiros de Israel! "

[[v12-13-15]]

^<<v12-13-15,15>>^ E Eliseu lhe disse: "Traga um arco e algumas flechas"; e ele assim fez.

[[v12-13-16]]

^<<v12-13-16,16>>^ "Pegue o arco em suas mãos", disse ao rei de Israel. Quando pegou, Eliseu pôs suas mãos sobre as mãos do rei

[[v12-13-17]]

^<<v12-13-17,17>>^ e lhe disse para abrir a janela que dava para o leste e atirar. O rei o fez, então Eliseu declarou: "Esta é a flecha da vitória do Senhor, a flecha da vitória sobre a Síria! Você destruirá totalmente os arameus, em Afeque".

[[v12-13-18]]

^<<v12-13-18,18>>^ Em seguida Eliseu mandou o rei pegar as flechas e golpear o chão. Ele golpeou o chão três vezes e parou.

[[v12-13-19]]

^<<v12-13-19,19>>^ O homem de Deus ficou irado com ele e disse: "Você deveria ter golpeado o chão cinco ou seis vezes; então iria derrotar a Síria e a destruiria completamente. Mas agora você a derrotará somente três vezes".

[[v12-13-20]]

^<<v12-13-20,20>>^ Então Eliseu morreu e foi sepultado. Ora, tropas moabitas costumavam entrar no país em todas as primaveras.

[[v12-13-21]]

^<<v12-13-21,21>>^ Certa vez, enquanto alguns israelitas sepultavam um homem, viram de repente uma dessas tropas; então jogaram o corpo do homem no túmulo de Eliseu e fugiram. Assim que o cadáver encostou nos ossos de Eliseu, o homem voltou à vida e se levantou.

[[v12-13-22]]

^<<v12-13-22,22>>^ Hazael, rei da Síria, oprimiu Israel durante todo o reinado de Jeoacaz.

[[v12-13-23]]

^<<v12-13-23,23>>^ Mas o Senhor foi bondoso para com eles, teve compaixão e mostrou preocupação por eles, por causa da sua aliança com Abraão, Isaque e Jacó. Até hoje ele não se dispôs a destruí-los ou eliminá-los de sua presença.

[[v12-13-24]]

^<<v12-13-24,24>>^ E Hazael, rei da Síria, morreu, e seu filho Ben-Hadade foi o seu sucessor.

[[v12-13-25]]

^<<v12-13-25,25>>^ Então Jeoás, filho de Jeoacaz, conquistou de Ben-Hadade, filho de Hazael, as cidades que, em combate, Hazael havia tomado de seu pai Jeoacaz. Três vezes Jeoás o derrotou e, assim, reconquistou essas cidades israelitas.

'''

xref:012-2-reis/012-2-reis-012.adoc#v12-12-0[&#60; Capítulo Anterior] | <<v12-13-0,Topo>> | xref:012-2-reis/012-2-reis-014.adoc#v12-14-0[Próximo Capítulo &#62;]