include::./index.adoc[]

[[v12-25-0]]
=== 2 Reis, 25
// nvi ?, NVI - Nova Versão Internacional

[[v12-25-1]]

^<<v12-25-1,1>>^ Então, no nono ano do reinado de Zedequias, no décimo dia do décimo mês, Nabucodonosor, rei da Babilônia, marchou contra Jerusalém com todo o seu exército. Ele acampou em frente da cidade e construiu rampas de ataque ao redor dela.

[[v12-25-2]]

^<<v12-25-2,2>>^ A cidade foi mantida sob cerco até o décimo primeiro ano do reinado de Zedequias.

[[v12-25-3]]

^<<v12-25-3,3>>^ No nono dia do quarto mês, a fome na cidade havia se tornado tão severa que não havia nada para o povo comer.

[[v12-25-4]]

^<<v12-25-4,4>>^ Então o muro da cidade foi rompido, e todos os soldados fugiram de noite pela porta entre os dois muros próximos ao jardim do rei, embora os babilônios estivessem em torno da cidade. Fugiram na direção da Arabá,

[[v12-25-5]]

^<<v12-25-5,5>>^ mas o exército babilônio perseguiu o rei e o alcançou nas planícies de Jericó. Todos os seus soldados o abandonaram,

[[v12-25-6]]

^<<v12-25-6,6>>^ e ele foi capturado. Foi levado até o rei da Babilônia, em Ribla, onde pronunciaram a sentença contra ele.

[[v12-25-7]]

^<<v12-25-7,7>>^ Executaram os filhos de Zedequias na sua frente; depois furaram seus olhos, prenderam-no com algemas de bronze e o levaram para a Babilônia.

[[v12-25-8]]

^<<v12-25-8,8>>^ No sétimo dia do quinto mês do décimo nono ano do reinado de Nabucodonosor, rei da Babilônia, Nebuzaradã, comandante da guarda imperial, conselheiro do rei da Babilônia, foi a Jerusalém.

[[v12-25-9]]

^<<v12-25-9,9>>^ Incendiou o templo do Senhor, o palácio real, todas as casas de Jerusalém e todos os edifícios importantes.

[[v12-25-10]]

^<<v12-25-10,10>>^ Todo o exército babilônio, que acompanhava Nebuzaradã derrubou os muros de Jerusalém.

[[v12-25-11]]

^<<v12-25-11,11>>^ E ele levou para o exílio o povo que sobrou na cidade, os que passaram para o lado do rei da Babilônia e o restante da população.

[[v12-25-12]]

^<<v12-25-12,12>>^ Mas alguns dos mais pobres do país o comandante deixou para trás, para trabalharem nas vinhas e nos campos.

[[v12-25-13]]

^<<v12-25-13,13>>^ Os babilônios destruíram as colunas de bronze, os suportes e o tanque de bronze que estavam no templo do Senhor, e levaram o bronze para a Babilônia.

[[v12-25-14]]

^<<v12-25-14,14>>^ Também levaram as panelas, as pás, os cortadores de pavio, as vasilhas e todos os utensílios de bronze utilizados no serviço do templo.

[[v12-25-15]]

^<<v12-25-15,15>>^ O comandante da guarda imperial levou os incensários e as bacias de aspersão, tudo o que era feito de ouro puro ou prata.

[[v12-25-16]]

^<<v12-25-16,16>>^ As duas colunas, o tanque e os suportes, que Salomão fizera para o templo do Senhor, eram mais do que podia ser pesado.

[[v12-25-17]]

^<<v12-25-17,17>>^ Cada coluna tinha oito metros e dez centímetros de altura. O capitel de bronze no alto de cada coluna tinha um metro e trinta e cinco centímetros de altura e era decorado com uma fileira de romãs de bronze ao redor.

[[v12-25-18]]

^<<v12-25-18,18>>^ O comandante da guarda levou como prisioneiros o sumo sacerdote, Seraías, Sofonias, o segundo sacerdote, e os três guardas da porta.

[[v12-25-19]]

^<<v12-25-19,19>>^ Dos que ainda estavam na cidade, ele levou o oficial responsável pelos homens de combate e cinco conselheiros reais. Também levou o secretário, principal líder responsável pelo alistamento militar no país e sessenta homens do povo.

[[v12-25-20]]

^<<v12-25-20,20>>^ O comandante Nebuzaradã levou a todos ao rei da Babilônia, em Ribla.

[[v12-25-21]]

^<<v12-25-21,21>>^ Lá, em Ribla, na terra de Hamate, o rei mandou executá-los. Assim Judá foi para o exílio, para longe de sua terra.

[[v12-25-22]]

^<<v12-25-22,22>>^ Nabucodonosor, rei da Babilônia, nomeou Gedalias, filho de Aicam e neto de Safã, como governador do povo que havia sido deixado em Judá.

[[v12-25-23]]

^<<v12-25-23,23>>^ Quando Ismael, filho de Netanias, Joanã, filho de Careá, Seraías, filho do netofatita Tanumete, e Jazanias, filho de um maacatita, todos os líderes do exército, souberam que o rei da Babilônia havia nomeado Gedalias como governador, eles e seus soldados foram falar com Gedalias em Mispá.

[[v12-25-24]]

^<<v12-25-24,24>>^ Gedalias fez um juramento a esses líderes e a seus soldados, dizendo: "Não tenham medo dos oficiais babilônios. Estabeleçam-se nesta terra e sirvam o rei da Babilônia, e tudo lhes irá bem".

[[v12-25-25]]

^<<v12-25-25,25>>^ Mas no sétimo mês, Ismael, filho de Netanias e neto de Elisama, que tinha sangue real, foi com dez homens e assassinou Gedalias e os judeus e os babilônios que estavam com ele em Mispá.

[[v12-25-26]]

^<<v12-25-26,26>>^ Então todo o povo, desde as crianças até os velhos, juntamente com os líderes do exército, fugiram para o Egito, com medo dos babilônios.

[[v12-25-27]]

^<<v12-25-27,27>>^ No trigésimo sétimo ano do exílio de Joaquim, rei de Judá, no ano em que Evil-Merodaque se tornou rei da Babilônia, ele tirou Joaquim da prisão, no dia vinte e sete do décimo segundo mês.

[[v12-25-28]]

^<<v12-25-28,28>>^ Ele lhe tratou com bondade e deu-lhe o lugar mais honrado entre os outros reis que estavam com ele na Babilônia.

[[v12-25-29]]

^<<v12-25-29,29>>^ Assim, Joaquim deixou suas vestes de prisão e pelo resto de sua vida comeu à mesa do rei.

[[v12-25-30]]

^<<v12-25-30,30>>^ E diariamente, enquanto viveu, Joaquim recebeu uma pensão do rei.

'''

xref:012-2-reis/012-2-reis-024.adoc#v12-24-0[&#60; Capítulo Anterior] | <<v12-25-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-001.adoc#v13-1-0[Próximo Capítulo &#62;]