include::./index.adoc[]

[[v12-24-0]]
=== 2 Reis, 24
// nvi ?, NVI - Nova Versão Internacional

[[v12-24-1]]

^<<v12-24-1,1>>^ Durante o reinado de Jeoaquim, Nabucodonosor, rei da Babilônia, invadiu o país, e Jeoaquim tornou-se seu vassalo por três anos. Então ele voltou atrás e rebelou-se contra Nabucodonosor.

[[v12-24-2]]

^<<v12-24-2,2>>^ O Senhor enviou contra ele tropas babilônicas, aramaicas, moabitas e amonitas, para destruir Judá, de acordo com a palavra do Senhor proclamada por seus servos, os profetas.

[[v12-24-3]]

^<<v12-24-3,3>>^ Com certeza isto aconteceu a Judá conforme a ordem do Senhor, a fim de removê-los da sua presença, por causa de todos os pecados que Manassés cometeu,

[[v12-24-4]]

^<<v12-24-4,4>>^ inclusive o derramamento de sangue inocente. Pois ele havia enchido Jerusalém de sangue inocente, e o Senhor não o quis perdoar.

[[v12-24-5]]

^<<v12-24-5,5>>^ Os demais acontecimentos do reinado de Jeoaquim e todas as suas realizações, estão escritos no livro dos registros históricos dos reis de Judá.

[[v12-24-6]]

^<<v12-24-6,6>>^ Jeoaquim descansou com seus antepassados. Seu filho Joaquim foi o seu sucessor.

[[v12-24-7]]

^<<v12-24-7,7>>^ O rei do Egito não mais se atreveu a sair com seu exército de suas próprias fronteiras, pois o rei da Babilônia havia ocupado todo o território entre o ribeiro do Egito e o rio Eufrates, que antes pertencera ao Egito.

[[v12-24-8]]

^<<v12-24-8,8>>^ Joaquim tinha dezoito anos de idade quando começou a reinar, e reinou três meses em Jerusalém. O nome da sua mãe era Neusta, filha de Elnatã; ela era de Jerusalém.

[[v12-24-9]]

^<<v12-24-9,9>>^ Ele fez o que o Senhor reprova, tal como seu pai.

[[v12-24-10]]

^<<v12-24-10,10>>^ Naquela ocasião os oficiais de Nabucodonosor, rei da Babilônia, avançaram até Jerusalém e a cercaram,

[[v12-24-11]]

^<<v12-24-11,11>>^ Enquanto seus oficiais a cercavam o próprio Nabucodonosor veio à cidade.

[[v12-24-12]]

^<<v12-24-12,12>>^ Então Joaquim, rei de Judá, sua mãe, seus conselheiros, seus nobres e seus oficiais se entregaram; todos se renderam a ele. No oitavo ano do reinado do rei da Babilônia, ele levou Joaquim como prisioneiro.

[[v12-24-13]]

^<<v12-24-13,13>>^ Conforme o Senhor tinha declarado, Nabucodonosor retirou todos os tesouros do templo do Senhor e do palácio real, quebrando todos os utensílios de ouro que Salomão, rei de Israel, fizera para o templo do Senhor.

[[v12-24-14]]

^<<v12-24-14,14>>^ Levou para o exílio toda Jerusalém: todos os líderes e os homens de combate, todos os artesãos e artífices. Era um total de dez mil pessoas; só ficaram os mais pobres.

[[v12-24-15]]

^<<v12-24-15,15>>^ Nabucodonosor levou prisioneiro Joaquim para a Babilônia. Também levou de Jerusalém para a Babilônia a mãe do rei, as mulheres do rei e os oficiais do rei e os líderes do país.

[[v12-24-16]]

^<<v12-24-16,16>>^ O rei da Babilônia também deportou para a Babilônia toda a força de sete mil homens de combate, homens fortes e preparados para a guerra, e mil artífices e artesãos.

[[v12-24-17]]

^<<v12-24-17,17>>^ Fez Matanias, tio de Joaquim, reinar em seu lugar, e mudou seu nome para Zedequias.

[[v12-24-18]]

^<<v12-24-18,18>>^ Zedequias tinha vinte e um anos de idade quando começou a reinar, e reinou onze anos em Jerusalém. O nome de sua mãe era Hamutal, filha de Jeremias; ela era de Libna.

[[v12-24-19]]

^<<v12-24-19,19>>^ Ele fez o que o Senhor reprova, tal como fizera Jeoaquim.

[[v12-24-20]]

^<<v12-24-20,20>>^ Por causa da ira do Senhor tudo isso aconteceu a Jerusalém e a Judá; por fim ele os lançou para longe da sua presença. Ora, Zedequias rebelou-se contra o rei da Babilônia.

'''

xref:012-2-reis/012-2-reis-023.adoc#v12-23-0[&#60; Capítulo Anterior] | <<v12-24-0,Topo>> | xref:012-2-reis/012-2-reis-025.adoc#v12-25-0[Próximo Capítulo &#62;]