include::./index.adoc[]

[[v12-6-0]]
=== 2 Reis, 6
// nvi ?, NVI - Nova Versão Internacional

[[v12-6-1]]

^<<v12-6-1,1>>^ Os discípulos dos profetas disseram a Eliseu: "Como vês, o lugar onde nos reunimos contigo é pequeno demais para nós.

[[v12-6-2]]

^<<v12-6-2,2>>^ Por que não vamos ao rio Jordão? Lá cada um de nós poderá cortar um tronco para construirmos ali um lugar de reuniões". Eliseu disse: "Podem ir".

[[v12-6-3]]

^<<v12-6-3,3>>^ Então um deles perguntou: "Não gostarias de ir com os teus servos? " "Sim", ele respondeu.

[[v12-6-4]]

^<<v12-6-4,4>>^ E foi com eles. Foram ao Jordão e começaram a derrubar árvores.

[[v12-6-5]]

^<<v12-6-5,5>>^ Quando um deles estava cortando um tronco, o ferro do machado caiu na água. E ele gritou: "Ah, meu senhor, era emprestado! "

[[v12-6-6]]

^<<v12-6-6,6>>^ O homem de Deus perguntou: "Onde caiu? " Quando ele lhe mostrou o lugar, Eliseu cortou um galho e o jogou ali, fazendo o ferro flutuar,

[[v12-6-7]]

^<<v12-6-7,7>>^ e disse: "Pegue-o". O homem esticou o braço e o pegou.

[[v12-6-8]]

^<<v12-6-8,8>>^ Ora, o rei da Síria estava em guerra contra Israel. Depois de deliberar com os seus conselheiros, dizia: "Montarei o meu acampamento em tal lugar".

[[v12-6-9]]

^<<v12-6-9,9>>^ Mas o homem de Deus mandava uma mensagem ao rei de Israel: "Evite passar por tal lugar, pois os arameus estão descendo para lá".

[[v12-6-10]]

^<<v12-6-10,10>>^ Assim, o rei de Israel investigava o lugar indicado pelo homem de Deus. Repetidas vezes Eliseu alertou o rei, que tomava as devidas precauções.

[[v12-6-11]]

^<<v12-6-11,11>>^ Isto enfureceu o rei da Síria, que, convocando seus conselheiros, lhes perguntou: "Vocês não me apontarão qual dos nossos está do lado do rei de Israel? "

[[v12-6-12]]

^<<v12-6-12,12>>^ Respondeu um dos conselheiros: "Nenhum de nós, majestade. É Eliseu, o profeta que está em Israel, que revela ao rei de Israel até as palavras que tu falas em teu quarto".

[[v12-6-13]]

^<<v12-6-13,13>>^ Ordenou o rei: "Descubram onde ele está, para que eu mande capturá-lo". Quando lhe informaram que o profeta estava em Dotã,

[[v12-6-14]]

^<<v12-6-14,14>>^ ele enviou para lá uma grande tropa com cavalos e carros de guerra. Eles chegaram de noite e cercaram a cidade.

[[v12-6-15]]

^<<v12-6-15,15>>^ O servo do homem de Deus levantou-se bem cedo pela manhã e, quando saía, viu que uma tropa com cavalos e carros de guerra havia cercado a cidade. Então ele exclamou: "Ah, meu senhor! O que faremos? "

[[v12-6-16]]

^<<v12-6-16,16>>^ O profeta respondeu: "Não tenha medo. Aqueles que estão conosco são mais numerosos do que eles".

[[v12-6-17]]

^<<v12-6-17,17>>^ E Eliseu orou: "Senhor, abre os olhos dele para que veja". Então o Senhor abriu os olhos do rapaz, que olhou e viu as colinas cheias de cavalos e carros de fogo ao redor de Eliseu.

[[v12-6-18]]

^<<v12-6-18,18>>^ Quando os arameus desceram na direção de Eliseu, ele orou ao Senhor: "Fere estes homens de cegueira". Então ele os feriu de cegueira, conforme Eliseu havia pedido.

[[v12-6-19]]

^<<v12-6-19,19>>^ Eliseu lhes disse: "Este não é o caminho nem esta é a cidade que procuram. Sigam-me, e eu os levarei ao homem que vocês estão procurando". E os guiou até a cidade de Samaria.

[[v12-6-20]]

^<<v12-6-20,20>>^ Assim que entraram na cidade, Eliseu disse: "Senhor, abre os olhos destes homens para que possam ver". Então o Senhor abriu-lhes os olhos, e eles viram que estavam dentro de Samaria.

[[v12-6-21]]

^<<v12-6-21,21>>^ Quando o rei de Israel os viu, perguntou a Eliseu: "Devo matá-los, meu pai? Devo matá-los? "

[[v12-6-22]]

^<<v12-6-22,22>>^ Ele respondeu: "Não! Costumas matar prisioneiros que capturas com a tua espada e o teu arco? Manda-lhes servir comida e bebida e deixa que voltem ao seu senhor".

[[v12-6-23]]

^<<v12-6-23,23>>^ Então preparou-lhes um grande banquete e, terminando eles de comer e beber, mandou-os de volta para o seu senhor. Assim, as tropas da Síria pararam de invadir o território de Israel.

[[v12-6-24]]

^<<v12-6-24,24>>^ Algum tempo depois, Ben-Hadade, rei da Síria, mobilizou todo o seu exército e cercou Samaria.

[[v12-6-25]]

^<<v12-6-25,25>>^ O cerco durou tanto e causou tamanha fome que uma cabeça de jumento chegou a valer oitenta peças de prata, e uma caneca de esterco de pomba, cinco peças de prata.

[[v12-6-26]]

^<<v12-6-26,26>>^ Um dia, quando o rei de Israel inspecionava os muros da cidade, uma mulher gritou para ele: "Socorro, majestade! "

[[v12-6-27]]

^<<v12-6-27,27>>^ O rei respondeu: "Se o Senhor não socorrê-la, como poderei ajudá-la? Acaso há trigo na eira ou vinho no lagar? "

[[v12-6-28]]

^<<v12-6-28,28>>^ Contudo ele perguntou: "Qual é o problema? " Ela respondeu: "Esta mulher me disse: ‘Vamos comer o seu filho hoje, e amanhã comeremos o meu’.

[[v12-6-29]]

^<<v12-6-29,29>>^ Então cozinhamos o meu filho e o comemos. No dia seguinte eu disse a ela que era a vez de comermos o seu filho, mas ela o havia escondido".

[[v12-6-30]]

^<<v12-6-30,30>>^ Quando o rei ouviu as palavras da mulher, rasgou as próprias vestes. Como estava sobre os muros, o povo viu que ele estava usando pano de saco por baixo, junto ao corpo.

[[v12-6-31]]

^<<v12-6-31,31>>^ E ele disse: "Deus me castigue com todo rigor, se a cabeça de Eliseu, filho de Safate, continuar hoje sobre seus ombros! "

[[v12-6-32]]

^<<v12-6-32,32>>^ Ora, Eliseu estava sentado em sua casa, reunido com as autoridades de Israel. O rei havia mandado um mensageiro à sua frente, mas, antes que ele chegasse, Eliseu disse às autoridades: "Aquele assassino mandou alguém para cortar-me a cabeça? Quando o mensageiro chegar, fechem a porta e mantenham-na trancada. Vocês não estão ouvindo os passos do seu senhor que vem atrás dele? "

[[v12-6-33]]

^<<v12-6-33,33>>^ Enquanto ainda lhes falava, o mensageiro chegou. Na mesma hora o rei disse: "Esta desgraça vem do Senhor. Por que devo ainda ter esperança no Senhor? "

'''

xref:012-2-reis/012-2-reis-005.adoc#v12-5-0[&#60; Capítulo Anterior] | <<v12-6-0,Topo>> | xref:012-2-reis/012-2-reis-007.adoc#v12-7-0[Próximo Capítulo &#62;]