include::./index.adoc[]

[[v12-22-0]]
=== 2 Reis, 22
// nvi ?, NVI - Nova Versão Internacional

[[v12-22-1]]

^<<v12-22-1,1>>^ Josias tinha oito anos de idade quando começou a reinar, e reinou trinta e um anos em Jerusalém. O nome de sua mãe era Jedida, filha de Adaías; ela era de Bozcate.

[[v12-22-2]]

^<<v12-22-2,2>>^ Ele fez o que o Senhor aprova e andou nos caminhos de Davi, seu predecessor, sem desviar-se nem para a direita nem para a esquerda.

[[v12-22-3]]

^<<v12-22-3,3>>^ No décimo oitavo ano do seu reinado, o rei Josias enviou o secretário Safã, filho de Azalias e neto de Mesulão, ao templo do Senhor, dizendo:

[[v12-22-4]]

^<<v12-22-4,4>>^ "Vá ao sumo sacerdote Hilquias e mande-o ajuntar a prata que foi trazida ao templo do Senhor, que os guardas das portas recolheram do povo.

[[v12-22-5]]

^<<v12-22-5,5>>^ Eles deverão entregar a prata aos homens nomeados para supervisionar a reforma do templo, para poderem pagar os trabalhadores que fazem os reparos no templo do Senhor:

[[v12-22-6]]

^<<v12-22-6,6>>^ os carpinteiros, os construtores e os pedreiros. Além disso comprarão madeira e pedras lavradas para os reparos no templo.

[[v12-22-7]]

^<<v12-22-7,7>>^ Mas eles não precisarão prestar contas da prata que lhes foi confiada, pois estão agindo com honestidade".

[[v12-22-8]]

^<<v12-22-8,8>>^ Então o sumo sacerdote Hilquias disse ao secretário Safã: "Encontrei o livro da Lei no templo do Senhor". Ele o entregou a Safã, que o leu.

[[v12-22-9]]

^<<v12-22-9,9>>^ O secretário Safã voltou ao rei e lhe informou: "Teus servos entregaram a prata que havia no templo do Senhor e a confiaram aos trabalhadores e supervisores no templo".

[[v12-22-10]]

^<<v12-22-10,10>>^ E o secretário Safã acrescentou: "O sacerdote Hilquias entregou-me um livro". E Safã o leu para o rei.

[[v12-22-11]]

^<<v12-22-11,11>>^ Assim que o rei ouviu as palavras do livro da Lei, rasgou suas vestes

[[v12-22-12]]

^<<v12-22-12,12>>^ e deu estas ordens ao sacerdote Hilquias, a Aicam, filho de Safã, a Acbor, filho de Micaías, ao secretário Safã e ao auxiliar real Asaías:

[[v12-22-13]]

^<<v12-22-13,13>>^ "Vão consultar o Senhor por mim, pelo povo e por todo Judá acerca do que está escrito neste livro que foi encontrado. A ira do Senhor contra nós deve ser grande, pois nossos antepassados não obedeceram às palavras deste livro, nem agiram de acordo com tudo que nele está escrito a nosso respeito".

[[v12-22-14]]

^<<v12-22-14,14>>^ O sacerdote Hilquias, Aicam, Acbor, Safã e Asaías foram falar com a profetisa Hulda, mulher de Salum, filho de Ticvá e neto de Harás, responsável pelo guarda-roupa do templo. Ela morava no bairro novo de Jerusalém.

[[v12-22-15]]

^<<v12-22-15,15>>^ Ela lhes disse: "Assim diz o Senhor, o Deus de Israel: ‘Digam ao homem que os enviou a mim:

[[v12-22-16]]

^<<v12-22-16,16>>^ Assim diz o Senhor: Eu vou trazer desgraça sobre este lugar e sobre seus habitantes; tudo o que está escrito no livro que o rei de Judá leu.

[[v12-22-17]]

^<<v12-22-17,17>>^ Porque me abandonaram e queimaram incenso a outros deuses, provocando-me à ira por meio de todos os ídolos que as mãos deles têm feito, minha ira arderá contra este lugar e não será apagada’.

[[v12-22-18]]

^<<v12-22-18,18>>^ Digam ao rei de Judá, que os enviou para consultar o Senhor: ‘Assim diz o Senhor, o Deus de Israel, acerca das palavras que você ouviu:

[[v12-22-19]]

^<<v12-22-19,19>>^ Já que o seu coração se abriu e você se humilhou diante do Senhor, ao ouvir o que falei contra este lugar e contra seus habitantes, que seriam arrasados e amaldiçoados, e porque você rasgou as vestes e chorou na minha presença, eu o ouvi, declara o Senhor.

[[v12-22-20]]

^<<v12-22-20,20>>^ Portanto, eu o reunirei aos seus antepassados, e você será sepultado em paz. Seus olhos não verão toda a desgraça que eu vou trazer sobre este lugar’ ". Então eles levaram a resposta ao rei.

'''

xref:012-2-reis/012-2-reis-021.adoc#v12-21-0[&#60; Capítulo Anterior] | <<v12-22-0,Topo>> | xref:012-2-reis/012-2-reis-023.adoc#v12-23-0[Próximo Capítulo &#62;]