include::./index.adoc[]

[[v12-8-0]]
=== 2 Reis, 8
// nvi ?, NVI - Nova Versão Internacional

[[v12-8-1]]

^<<v12-8-1,1>>^ Eliseu tinha prevenido a mãe do menino que ele havia ressuscitado: "Saia do país com sua família e vá morar onde puder, pois o Senhor determinou uma fome nesta terra, que durará sete anos".

[[v12-8-2]]

^<<v12-8-2,2>>^ A mulher seguiu o conselho do homem de Deus, partiu com sua família e passou sete anos na terra dos filisteus.

[[v12-8-3]]

^<<v12-8-3,3>>^ Ao final dos sete anos ela voltou a Israel e foi fazer um apelo ao rei para readquirir sua casa e sua propriedade.

[[v12-8-4]]

^<<v12-8-4,4>>^ O rei estava conversando com Geazi, servo do homem de Deus, e disse: "Conte-me todos os prodígios que Eliseu tem feito".

[[v12-8-5]]

^<<v12-8-5,5>>^ Enquanto Geazi contava ao rei como Eliseu havia ressuscitado o menino, a própria mãe do menino que Eliseu tinha ressuscitado, chegou para apresentar sua petição ao rei para readquirir sua casa e sua propriedade. Geazi exclamou: "Esta é a mulher, ó rei, meu senhor, e este é o filho dela, a quem Eliseu ressuscitou".

[[v12-8-6]]

^<<v12-8-6,6>>^ O rei pediu que ela contasse o ocorrido, e ela confirmou os fatos. Então ele designou um funcionário para cuidar do caso dela e lhe ordenou: "Devolva tudo o que lhe pertencia, inclusive toda a renda das colheitas, desde que ela saiu do país até hoje".

[[v12-8-7]]

^<<v12-8-7,7>>^ Certa ocasião, Eliseu foi a Damasco. Ben-Hadade, rei da Síria, estava doente. Quando disseram ao rei: "O homem de Deus está na cidade",

[[v12-8-8]]

^<<v12-8-8,8>>^ ele ordenou a Hazael: "Vá encontrar-se com o homem de Deus e leve-lhe um presente. Consulte o Senhor por meio dele: pergunte-lhe se vou me recuperar desta doença".

[[v12-8-9]]

^<<v12-8-9,9>>^ Hazael foi encontrar-se com Eliseu, levando consigo de tudo o que havia de melhor em Damasco, um presente carregado por quarenta camelos. Ao chegar diante dele Hazael disse: "Teu filho Ben-Hadade, rei da Síria, enviou-me para perguntar se ele vai recuperar-se de sua doença".

[[v12-8-10]]

^<<v12-8-10,10>>^ Eliseu respondeu: "Vá e diga-lhe: ‘Com certeza te recuperarás’, no entanto o Senhor me revelou que de fato ele vai morrer".

[[v12-8-11]]

^<<v12-8-11,11>>^ Eliseu ficou olhando fixamente para Hazael até deixá-lo constrangido. Então o homem de Deus começou a chorar.

[[v12-8-12]]

^<<v12-8-12,12>>^ E perguntou Hazael: "Por que meu senhor está chorando? " Ele respondeu: "Porque sei das coisas terríveis que você fará aos israelitas. Você incendiará suas fortalezas, matará seus jovens à espada, esmagará as crianças e rasgará o ventre de suas mulheres grávidas".

[[v12-8-13]]

^<<v12-8-13,13>>^ Hazael disse: "Como poderia teu servo, que não passa de um cão, realizar algo assim? " Respondeu Eliseu: "O Senhor me mostrou que você se tornará rei da Síria".

[[v12-8-14]]

^<<v12-8-14,14>>^ Então Hazael saiu dali e voltou para seu senhor. Quando Ben-Hadade perguntou: "O que Eliseu lhe disse? ", Hazael respondeu: "Ele me falou que certamente te recuperarás".

[[v12-8-15]]

^<<v12-8-15,15>>^ Mas, no dia seguinte, ele apanhou um cobertor, encharcou-o e com ele sufocou o rei, até matá-lo. E assim Hazael foi o seu sucessor.

[[v12-8-16]]

^<<v12-8-16,16>>^ No quinto ano de Jorão, filho de Acabe, rei de Israel, sendo Josafá rei de Judá, Jeorão, seu filho, começou a reinar em Judá.

[[v12-8-17]]

^<<v12-8-17,17>>^ Ele tinha trinta e dois anos de idade quando começou a reinar, e reinou oito anos em Jerusalém.

[[v12-8-18]]

^<<v12-8-18,18>>^ Andou nos caminhos dos reis de Israel, como a família de Acabe havia feito, pois se casou com uma filha de Acabe. E fez o que o Senhor reprova.

[[v12-8-19]]

^<<v12-8-19,19>>^ Entretanto, por amor ao seu servo Davi, o Senhor não quis destruir Judá. Ele havia prometido manter para sempre um descendente de Davi no trono.

[[v12-8-20]]

^<<v12-8-20,20>>^ Nos dias de Jeorão, os edomitas rebelaram-se contra o domínio de Judá, proclamando seu próprio rei.

[[v12-8-21]]

^<<v12-8-21,21>>^ Por isso, Jeorão foi a Zair com todos os seus carros de guerra. Lá os edomitas cercaram a ele e aos chefes dos seus carros de guerra, mas ele os atacou de noite e rompeu o cerco inimigo, e seu exército conseguiu fugir para casa.

[[v12-8-22]]

^<<v12-8-22,22>>^ E até hoje Edom continua independente de Judá. Nessa mesma época, a cidade de Libna também tornou-se independente.

[[v12-8-23]]

^<<v12-8-23,23>>^ Os demais acontecimentos do reinado de Jeorão e todas as suas realizações, estão escritos nos registros históricos dos reis de Judá.

[[v12-8-24]]

^<<v12-8-24,24>>^ Jeorão descansou com seus antepassados e foi sepultado com eles na cidade de Davi. E seu filho Acazias foi o seu sucessor.

[[v12-8-25]]

^<<v12-8-25,25>>^ No décimo segundo ano do reinado de Jorão, filho de Acabe, rei de Israel, Acazias, filho de Jeorão, rei de Judá, começou a reinar.

[[v12-8-26]]

^<<v12-8-26,26>>^ Ele tinha vinte e dois anos de idade quando começou a reinar, e reinou um ano em Jerusalém. O nome de sua mãe era Atalia, neta de Onri, rei de Israel.

[[v12-8-27]]

^<<v12-8-27,27>>^ Ele andou nos caminhos da família de Acabe e fez o que o Senhor reprova, como a família de Acabe havia feito, pois casou-se com uma mulher da família de Acabe.

[[v12-8-28]]

^<<v12-8-28,28>>^ Acazias aliou-se a Jorão, filho de Acabe, e saiu à guerra contra Hazael, rei da Síria, em Ramote-Gileade. Jorão foi ferido

[[v12-8-29]]

^<<v12-8-29,29>>^ e voltou a Jezreel para recuperar-se dos ferimentos sofridos em Ramote, na batalha contra Hazael, rei da Síria. Depois Acazias, rei de Judá, foi a Jezreel visitar Jorão, que se recuperava de seus ferimentos.

'''

xref:012-2-reis/012-2-reis-007.adoc#v12-7-0[&#60; Capítulo Anterior] | <<v12-8-0,Topo>> | xref:012-2-reis/012-2-reis-009.adoc#v12-9-0[Próximo Capítulo &#62;]