include::./index.adoc[]

[[v12-9-0]]
=== 2 Reis, 9
// nvi ?, NVI - Nova Versão Internacional

[[v12-9-1]]

^<<v12-9-1,1>>^ Enquanto isso o profeta Eliseu chamou um dos discípulos dos profetas e lhe disse: "Ponha a capa por dentro do cinto, pegue este frasco de óleo e vá a Ramote-Gileade.

[[v12-9-2]]

^<<v12-9-2,2>>^ Quando lá chegar, procure Jeú, filho de Josafá e neto de Ninsi. Dirija-se a ele e leve-o para uma sala longe dos seus companheiros.

[[v12-9-3]]

^<<v12-9-3,3>>^ Depois pegue o frasco, derrame o óleo sobre a cabeça dele e declare: ‘Assim diz o Senhor: Eu o estou ungindo rei sobre Israel’. Então abra a porta e fuja sem demora! "

[[v12-9-4]]

^<<v12-9-4,4>>^ Então o jovem profeta foi a Ramote-Gileade.

[[v12-9-5]]

^<<v12-9-5,5>>^ Ao chegar, encontrou os comandantes do exército reunidos e disse: "Trago uma mensagem para ti, comandante". "Para qual de nós? ", perguntou Jeú. Ele respondeu: "Para ti, comandante".

[[v12-9-6]]

^<<v12-9-6,6>>^ Jeú levantou-se e entrou na casa. Então o jovem profeta derramou o óleo na cabeça de Jeú e declarou-lhe: "Assim diz o Senhor, o Deus de Israel: ‘Eu o estou ungindo rei de Israel, o povo do Senhor.

[[v12-9-7]]

^<<v12-9-7,7>>^ Você dará fim à família de Acabe, seu senhor, e assim eu vingarei o sangue de meus servos, os profetas, e o sangue de todos os servos do Senhor, derramado por Jezabel.

[[v12-9-8]]

^<<v12-9-8,8>>^ Toda a família de Acabe perecerá. Eliminarei todos os de sexo masculino de sua família em Israel, seja escravo seja livre.

[[v12-9-9]]

^<<v12-9-9,9>>^ Tratarei a família de Acabe como tratei a de Jeroboão, filho de Nebate, e a de Baasa, filho de Aías.

[[v12-9-10]]

^<<v12-9-10,10>>^ E Jezabel será devorada por cães num terreno em Jezreel, e ninguém a sepultará’ ". Então ele abriu a porta e saiu correndo.

[[v12-9-11]]

^<<v12-9-11,11>>^ Quando Jeú voltou para junto dos outros oficiais do rei, um deles lhe perguntou: "Está tudo bem? O que esse louco queria com você? " Jeú respondeu: "Vocês conhecem essa gente e as coisas que dizem".

[[v12-9-12]]

^<<v12-9-12,12>>^ Mas insistiram: "Não nos engane! Conte-nos o que ele disse". Então Jeú contou: "Ele me disse o seguinte: ‘Assim diz o Senhor: Eu o estou ungindo rei sobre Israel’ ".

[[v12-9-13]]

^<<v12-9-13,13>>^ Imediatamente eles pegaram os seus mantos e os estenderam sobre os degraus diante dele. Em seguida tocaram a trombeta e gritaram: "Jeú é rei! "

[[v12-9-14]]

^<<v12-9-14,14>>^ Então Jeú, filho de Josafá e neto de Ninsi, começou uma conspiração contra o rei Jorão, na época em que este defendeu, com todo Israel, Ramote-Gileade contra Hazael, rei da Síria.

[[v12-9-15]]

^<<v12-9-15,15>>^ O rei Jorão tinha voltado a Jezreel para recuperar-se dos ferimentos sofridos na batalha contra Hazael, rei da Síria. Jeú propôs: "Se vocês me apóiam, não deixem ninguém sair escondido da cidade para nos denunciar em Jezreel".

[[v12-9-16]]

^<<v12-9-16,16>>^ Então ele subiu em seu carro e foi para Jezreel, porque Jorão estava lá se recuperando; e Acazias, rei de Judá, tinha ido visitá-lo.

[[v12-9-17]]

^<<v12-9-17,17>>^ Quando a sentinela que estava na torre de vigia de Jezreel percebeu a tropa de Jeú se aproximando, gritou: "Estou vendo uma tropa! " Jorão ordenou: "Chame um cavaleiro e envie-o ao encontro deles para perguntar se eles vêm em paz".

[[v12-9-18]]

^<<v12-9-18,18>>^ O cavaleiro foi ao encontro de Jeú e disse: "O rei pergunta: ‘Vocês vêm em paz? ’ " Jeú respondeu: "Não me venha falar em paz. Saia da minha frente". A sentinela relatou: "O mensageiro chegou a eles, mas não está voltando".

[[v12-9-19]]

^<<v12-9-19,19>>^ Então o rei enviou um segundo cavaleiro. Quando chegou a eles disse: "O rei pergunta: ‘Vocês vêm em paz? ’ " Jeú respondeu: "Não me venha falar em paz. Saia da minha frente".

[[v12-9-20]]

^<<v12-9-20,20>>^ A sentinela relatou: "Ele chegou a eles, mas também não está voltando". E acrescentou: "O jeito do chefe da tropa guiar o carro é como o de Jeú, neto de Ninsi; dirige como louco".

[[v12-9-21]]

^<<v12-9-21,21>>^ Jorão ordenou que preparassem seu carro de guerra. Assim que ficou pronto, Jorão, rei de Israel, e Acazias, rei de Judá, saíram, cada um em seu carro, ao encontro de Jeú. Eles o encontraram na propriedade que havia pertencido a Nabote, de Jezreel.

[[v12-9-22]]

^<<v12-9-22,22>>^ Quando Jorão viu Jeú, perguntou: "Você vem em paz, Jeú? " Jeú respondeu: "Como pode haver paz, enquanto continua toda a idolatria e as feitiçarias de sua mãe Jezabel? "

[[v12-9-23]]

^<<v12-9-23,23>>^ Jorão deu meia-volta e fugiu, gritando para Acazias: "Traição, Acazias! "

[[v12-9-24]]

^<<v12-9-24,24>>^ Então Jeú disparou seu arco com toda força e atingiu Jorão nas costas. A flecha atravessou-lhe o coração e ele caiu morto.

[[v12-9-25]]

^<<v12-9-25,25>>^ Jeú disse a Bidcar, seu oficial: "Pegue o cadáver e jogue-o nesta propriedade que pertencia a Nabote, de Jezreel. Lembre-se da advertência que o Senhor proferiu contra Acabe, pai dele, quando juntos acompanhávamos sua comitiva. Ele disse:

[[v12-9-26]]

^<<v12-9-26,26>>^ ‘Ontem, vi o sangue de Nabote e o sangue dos seus filhos, declara o Senhor, e com certeza farei você pagar por isso nesta mesma propriedade, declara o Senhor’. Agora, então, pegue o cadáver e jogue-o nesta propriedade, conforme a palavra do Senhor".

[[v12-9-27]]

^<<v12-9-27,27>>^ Vendo isso, Acazias, rei de Judá, fugiu na direção de Bete-Hagã. Mas Jeú o perseguiu, gritando: "Matem-no também! " Eles o atingiram em seu carro de guerra na subida para Gur, perto de Ibleã, mas ele conseguiu refugiar-se em Megido, onde morreu.

[[v12-9-28]]

^<<v12-9-28,28>>^ Seus oficiais o levaram até Jerusalém e o sepultaram com seus antepassados em seu túmulo, na cidade de Davi.

[[v12-9-29]]

^<<v12-9-29,29>>^ Acazias havia se tornado rei de Judá no décimo primeiro ano de Jorão, filho de Acabe.

[[v12-9-30]]

^<<v12-9-30,30>>^ Em seguida Jeú entrou em Jezreel. Ao saber disso, Jezabel pintou os olhos, arrumou o cabelo e ficou olhando de uma janela do palácio.

[[v12-9-31]]

^<<v12-9-31,31>>^ Quando Jeú passou pelo portão, ela gritou: "Como vai, Zinri, assassino do seu senhor? "

[[v12-9-32]]

^<<v12-9-32,32>>^ Ele ergueu os olhos para a janela e gritou: "Quem de vocês está do meu lado? " Dois ou três funcionários olharam para ele.

[[v12-9-33]]

^<<v12-9-33,33>>^ Então Jeú ordenou: "Joguem essa mulher para baixo! " Eles a jogaram e o sangue dela espirrou na parede e nos cavalos, e Jeú a atropelou.

[[v12-9-34]]

^<<v12-9-34,34>>^ Jeú entrou, comeu, bebeu e ordenou: "Peguem aquela maldita e sepultem-na, afinal era filha de rei".

[[v12-9-35]]

^<<v12-9-35,35>>^ Mas, quando foram sepultá-la, só encontraram o crânio, os pés e as mãos.

[[v12-9-36]]

^<<v12-9-36,36>>^ Então voltaram e contaram isso a Jeú, que disse: "Cumpriu-se a palavra do Senhor, anunciada por meio do seu servo Elias, o tesbita: Num terreno em Jezreel cães devorarão a carne de Jezabel,

[[v12-9-37]]

^<<v12-9-37,37>>^ os seus restos mortais serão espalhados num terreno em Jezreel, como esterco no campo, de modo que ninguém será capaz de dizer: ‘Esta é Jezabel’ ".

'''

xref:012-2-reis/012-2-reis-008.adoc#v12-8-0[&#60; Capítulo Anterior] | <<v12-9-0,Topo>> | xref:012-2-reis/012-2-reis-010.adoc#v12-10-0[Próximo Capítulo &#62;]