include::./index.adoc[]

[[v12-12-0]]
=== 2 Reis, 12
// nvi ?, NVI - Nova Versão Internacional

[[v12-12-1]]

^<<v12-12-1,1>>^ No sétimo ano do reinado de Jeú, Joás começou a reinar, e reinou quarenta anos em Jerusalém. O nome de sua mãe era Zíbia; ela era de Berseba.

[[v12-12-2]]

^<<v12-12-2,2>>^ Joás fez o que o Senhor aprova durante todos os anos em que o sacerdote Joiada o orientou.

[[v12-12-3]]

^<<v12-12-3,3>>^ Contudo, os altares idólatras não foram derrubados; o povo continuava a oferecer sacrifícios e a queimar incenso neles.

[[v12-12-4]]

^<<v12-12-4,4>>^ Joás ordenou aos sacerdotes: "Reúnam toda a prata trazida como dádivas sagradas ao templo do Senhor: a prata recolhida no recenseamento, a prata recebida de votos pessoais e a que foi trazida voluntariamente ao templo.

[[v12-12-5]]

^<<v12-12-5,5>>^ Cada sacerdote recolha a prata de um dos tesoureiros para que seja usada na reforma do templo".

[[v12-12-6]]

^<<v12-12-6,6>>^ Contudo, no vigésimo terceiro ano do reinado de Joás, os sacerdotes ainda não tinham feito as reformas.

[[v12-12-7]]

^<<v12-12-7,7>>^ Por isso, o rei Joás chamou o sacerdote Joiada e os outros sacerdotes e lhes perguntou: "Por que vocês não estão fazendo as reformas no templo? Não recolham mais prata com seus tesoureiros, mas deixem-na para as reformas".

[[v12-12-8]]

^<<v12-12-8,8>>^ Os sacerdotes concordaram em não mais receber nenhuma prata do povo e em não serem mais os encarregados dessas reformas.

[[v12-12-9]]

^<<v12-12-9,9>>^ Então o sacerdote Joiada pegou uma caixa, fez um furo na tampa e colocou-a ao lado do altar, à direita de quem entra no templo do Senhor. Os sacerdotes que guardavam a entrada colocavam na caixa toda a prata trazida ao templo do Senhor.

[[v12-12-10]]

^<<v12-12-10,10>>^ Sempre que havia uma grande quantidade de prata na caixa, o secretário real e o sumo sacerdote vinham, pesavam a prata trazida ao templo do Senhor e a colocavam em sacolas.

[[v12-12-11]]

^<<v12-12-11,11>>^ Depois de pesada, entregavam a prata aos supervisores do trabalho no templo. Assim pagavam aqueles que trabalhavam no templo do Senhor: os carpinteiros e construtores,

[[v12-12-12]]

^<<v12-12-12,12>>^ os pedreiros e cortadores de pedras. Também compravam madeira e pedras lavradas para os consertos no templo do Senhor e cobriam todas as outras despesas.

[[v12-12-13]]

^<<v12-12-13,13>>^ A prata trazida ao templo não era utilizada na confecção de bacias de prata, cortadores de pavio, bacias para aspersão, cornetas ou quaisquer outros utensílios de ouro ou prata para o templo do Senhor;

[[v12-12-14]]

^<<v12-12-14,14>>^ era usada como pagamento dos trabalhadores, que a empregavam para o reparo do templo.

[[v12-12-15]]

^<<v12-12-15,15>>^ Não se exigia prestação de contas dos que pagavam os trabalhadores, pois agiam com honestidade.

[[v12-12-16]]

^<<v12-12-16,16>>^ Mas a prata das ofertas pela culpa e das ofertas pelo pecado não era levada ao templo do Senhor, pois pertencia aos sacerdotes.

[[v12-12-17]]

^<<v12-12-17,17>>^ Nessa época, Hazael, rei da Síria, atacou Gate e a conquistou. Depois decidiu atacar Jerusalém.

[[v12-12-18]]

^<<v12-12-18,18>>^ Então Joás, rei de Judá, apanhou todos os objetos consagrados por seus antepassados Josafá, Jeorão e Acazias, reis de Judá, e os que ele mesmo havia consagrado e todo o ouro encontrado no depósito do templo do Senhor e do palácio real, e enviou tudo a Hazael, rei da Síria, que, assim, desistiu de atacar Jerusalém.

[[v12-12-19]]

^<<v12-12-19,19>>^ Os demais acontecimentos do reinado de Joás, e as suas realizações, estão todos escritos no livro dos registros históricos dos reis de Judá.

[[v12-12-20]]

^<<v12-12-20,20>>^ Dois de seus oficiais conspiraram contra ele e o assassinaram em Bete-Milo, no caminho que desce para Sila.

[[v12-12-21]]

^<<v12-12-21,21>>^ Os oficiais que o assassinaram foram Jozabade, filho de Simeate, e Jeozabade, filho de Somer. Ele morreu e foi sepultado junto aos seus antepassados na cidade de Davi. E seu filho Amazias foi o seu sucessor.

'''

xref:012-2-reis/012-2-reis-011.adoc#v12-11-0[&#60; Capítulo Anterior] | <<v12-12-0,Topo>> | xref:012-2-reis/012-2-reis-013.adoc#v12-13-0[Próximo Capítulo &#62;]