include::./index.adoc[]

[[v12-19-0]]
=== 2 Reis, 19
// nvi ?, NVI - Nova Versão Internacional

[[v12-19-1]]

^<<v12-19-1,1>>^ Ao ouvir o relato, o rei Ezequias rasgou as suas vestes, pôs roupas de luto e entrou no templo do Senhor.

[[v12-19-2]]

^<<v12-19-2,2>>^ Ele enviou o administrador do palácio, Eliaquim, o secretário Sebna e os sacerdotes principais, todos vestidos com pano de saco, ao profeta Isaías, filho de Amoz.

[[v12-19-3]]

^<<v12-19-3,3>>^ Eles lhe disseram: "Assim diz Ezequias: Hoje é dia de angústia, de repreensão e de humilhação; estamos como a mulher que está para dar à luz filhos, mas não tem forças para fazê-los nascer.

[[v12-19-4]]

^<<v12-19-4,4>>^ Talvez o Senhor seu Deus ouça todas as palavras do comandante de campo, a quem o senhor dele, o rei da Assíria, enviou para zombar do Deus vivo. E que o Senhor seu Deus o repreenda pelas palavras que ouviu. Portanto, suplique a Deus pelo remanescente que ainda sobrevive".

[[v12-19-5]]

^<<v12-19-5,5>>^ Quando os oficiais do rei Ezequias chegaram a Isaías,

[[v12-19-6]]

^<<v12-19-6,6>>^ este lhes disse: "Digam a seu senhor: ‘Assim diz o Senhor: Não tenha medo das palavras que você ouviu, das blasfêmias que os servos do rei da Assíria lançaram contra mim.

[[v12-19-7]]

^<<v12-19-7,7>>^ Ouça! Eu o farei tomar a decisão de retornar ao seu próprio país, quando ele ouvir certa notícia. E lá o farei morrer à espada’ ".

[[v12-19-8]]

^<<v12-19-8,8>>^ Quando o comandante de campo soube que o rei da Assíria havia partido de Láquis, retirou-se e encontrou o rei lutando contra Libna.

[[v12-19-9]]

^<<v12-19-9,9>>^ Ora, Senaqueribe fora informado de que Tiraca, rei etíope do Egito, estava vindo lutar contra ele, de modo que mandou novamente mensageiros a Ezequias com este recado:

[[v12-19-10]]

^<<v12-19-10,10>>^ "Digam a Ezequias, rei de Judá: Não deixe que o Deus no qual você confia o engane, quando diz: ‘Jerusalém não cairá nas mãos do rei da Assíria’.

[[v12-19-11]]

^<<v12-19-11,11>>^ Com certeza você ouviu o que os reis da Assíria têm feito a todas as nações, como as destruíram por completo. E você haveria de livrar-se?

[[v12-19-12]]

^<<v12-19-12,12>>^ Acaso os deuses das nações que foram destruídas por meus antepassados as livraram: os deuses de Gozã, Harã, Rezefe e do povo de Éden, que estava em Telassar?

[[v12-19-13]]

^<<v12-19-13,13>>^ Onde estão o rei de Hamate, o rei de Arpade, o rei da cidade de Sevarfaim, de Hena ou de Iva? "

[[v12-19-14]]

^<<v12-19-14,14>>^ Ezequias recebeu a carta das mãos dos mensageiros e a leu. Então subiu ao templo do Senhor e estendeu-a perante o Senhor.

[[v12-19-15]]

^<<v12-19-15,15>>^ E Ezequias orou ao Senhor: "Senhor, Deus de Israel, que reina em teu trono, entre os querubins, só tu és Deus sobre todos os reinos da terra. Tu criaste os céus e a terra.

[[v12-19-16]]

^<<v12-19-16,16>>^ Dá ouvidos, Senhor, e vê; ouve as palavras que Senaqueribe enviou para insultar o Deus vivo.

[[v12-19-17]]

^<<v12-19-17,17>>^ É verdade, Senhor, que os reis assírios fizeram de todas essas nações e seus territórios um deserto.

[[v12-19-18]]

^<<v12-19-18,18>>^ Atiraram os deuses delas no fogo e os destruíram, pois não eram deuses; eram apenas madeira e pedra moldadas por mãos humanas.

[[v12-19-19]]

^<<v12-19-19,19>>^ Agora, Senhor nosso Deus, salva-nos das mãos dele, para que todos os reinos da terra saibam que só tu, Senhor, és Deus".

[[v12-19-20]]

^<<v12-19-20,20>>^ Então Isaías, filho de Amoz, enviou uma mensagem a Ezequias: "Assim diz o Senhor, o Deus de Israel: Ouvi a sua oração acerca de Senaqueribe, o rei da Assíria.

[[v12-19-21]]

^<<v12-19-21,21>>^ Esta é a palavra que o Senhor falou contra ele: ‘A virgem, a filha de Sião, o despreza e zomba de você. A filha de Jerusalém meneia a cabeça enquanto você foge.

[[v12-19-22]]

^<<v12-19-22,22>>^ De quem você zombou e contra quem blasfemou? Contra quem você levantou a voz e contra quem ergueu o seu olhar arrogante? Contra o Santo de Israel!

[[v12-19-23]]

^<<v12-19-23,23>>^ Sim, você insultou o Senhor por meio dos seus mensageiros. E declarou: "Com carros sem conta subi, aos pontos mais elevados e às inacessíveis alturas do Líbano. Derrubei os seus mais altos cedros, os seus melhores pinheiros. Entrei em suas regiões mais remotas, e nas suas mais densas florestas.

[[v12-19-24]]

^<<v12-19-24,24>>^ Em terras estrangeiras cavei poços e bebi água. Com as solas de meus pés sequei todos os rios do Egito".

[[v12-19-25]]

^<<v12-19-25,25>>^ Você não percebe que há muito tempo eu já havia determinado tudo isso. Desde a antigüidade planejei o que agora faço acontecer, que você deixaria cidades fortificadas em ruínas.

[[v12-19-26]]

^<<v12-19-26,26>>^ Seus habitantes, sem forças, desanimam-se envergonhados. São como pastagens, como brotos tenros e verdes, como ervas no telhado, queimadas antes de crescer.

[[v12-19-27]]

^<<v12-19-27,27>>^ Eu, porém, sei onde você está, sei quando você sai e quando retorna; e como você se enfurece contra mim.

[[v12-19-28]]

^<<v12-19-28,28>>^ Sim, contra mim você se enfureceu e o seu atrevimento chegou aos meus ouvidos. Por isso porei o meu anzol em seu nariz e o meu freio em sua boca, e o farei voltar pelo caminho por onde veio.

[[v12-19-29]]

^<<v12-19-29,29>>^ A você, Ezequias, darei este sinal: Neste ano vocês comerão do que crescer por si, e no próximo o que daquilo brotar. Mas no terceiro ano semeiem e colham, plantem vinhas e comam o seu fruto.

[[v12-19-30]]

^<<v12-19-30,30>>^ Mais uma vez, um remanescente da tribo de Judá sobreviverá, lançará raízes na terra e se encherão de frutos os seus ramos.

[[v12-19-31]]

^<<v12-19-31,31>>^ De Jerusalém sairão sobreviventes, e um remanescente do monte Sião. O zelo do Senhor dos Exércitos o executará’.

[[v12-19-32]]

^<<v12-19-32,32>>^ Portanto, assim diz o Senhor acerca do rei da Assíria: ‘Ele não invadirá esta cidade nem disparará contra ela uma só flecha. Não a enfrentará com escudo nem construirá rampas de cerco contra ela.

[[v12-19-33]]

^<<v12-19-33,33>>^ Pelo caminho por onde veio voltará; não invadirá esta cidade’, declara o Senhor.

[[v12-19-34]]

^<<v12-19-34,34>>^ ‘Eu a defenderei e a salvarei, por amor de mim mesmo e do meu servo Davi’ ".

[[v12-19-35]]

^<<v12-19-35,35>>^ Naquela noite o anjo do Senhor saiu e matou cento e oitenta e cinco mil homens no acampamento assírio. Quando o povo se levantou na manhã seguinte, o lugar estava repleto de cadáveres!

[[v12-19-36]]

^<<v12-19-36,36>>^ Assim Senaqueribe, rei da Assíria, desmontou o acampamento e foi embora. Voltou para Nínive e lá ficou.

[[v12-19-37]]

^<<v12-19-37,37>>^ Certo dia, enquanto ele estava adorando no templo de seu deus Nisroque, seus filhos Adrameleque e Sarezer mataram-no à espada e fugiram para a terra de Ararate. Seu filho Esar-Hadom foi o seu sucessor.

'''

xref:012-2-reis/012-2-reis-018.adoc#v12-18-0[&#60; Capítulo Anterior] | <<v12-19-0,Topo>> | xref:012-2-reis/012-2-reis-020.adoc#v12-20-0[Próximo Capítulo &#62;]