include::./index.adoc[]

[[v12-23-0]]
=== 2 Reis, 23
// nvi ?, NVI - Nova Versão Internacional

[[v12-23-1]]

^<<v12-23-1,1>>^ Então o rei convocou todas as autoridades de Judá e de Jerusalém.

[[v12-23-2]]

^<<v12-23-2,2>>^ Depois o rei subiu ao templo do Senhor acompanhado por todos os homens de Judá, todo o povo de Jerusalém, os sacerdotes e os profetas; todo o povo, dos mais simples aos mais importantes. Para todos o rei leu em voz alta todas as palavras do Livro da Aliança, que havia sido encontrado no templo do Senhor.

[[v12-23-3]]

^<<v12-23-3,3>>^ O rei colocou-se junto à coluna real e, na presença do Senhor, fez uma aliança, comprometendo-se a seguir o Senhor e obedecer de todo o coração e de toda a alma aos seus mandamentos, seus preceitos e seus decretos, confirmando assim as palavras da aliança escritas naquele livro. Então todo o povo se comprometeu com a aliança.

[[v12-23-4]]

^<<v12-23-4,4>>^ O rei deu ordens ao sumo sacerdote Hilquias, aos sacerdotes auxiliares e aos guardas das portas que retirassem do templo do Senhor todos os utensílios feitos para Baal e Aserá e para todos os exércitos celestes. Ele os queimou fora de Jerusalém, nos campos do vale de Cedrom e levou as cinzas para Betel.

[[v12-23-5]]

^<<v12-23-5,5>>^ E eliminou os sacerdotes pagãos nomeados pelos reis de Judá para queimar incenso nos altares idólatras das cidades de Judá e dos arredores de Jerusalém, aqueles que queimavam incenso a Baal, ao sol e à lua, às constelações e a todos os exércitos celestes.

[[v12-23-6]]

^<<v12-23-6,6>>^ Também mandou levar o poste sagrado do templo do Senhor para o vale de Cedrom, fora de Jerusalém, para ser queimado e reduzido a cinzas, que foram espalhadas sobre os túmulos de um cemitério público.

[[v12-23-7]]

^<<v12-23-7,7>>^ Também derrubou as acomodações dos prostitutos cultuais, que ficavam no templo do Senhor, onde as mulheres teciam para Aserá.

[[v12-23-8]]

^<<v12-23-8,8>>^ Josias trouxe todos os sacerdotes das cidades de Judá e, desde Geba até Berseba, profanou os altares onde os sacerdotes haviam queimado incenso. Derrubou os altares idólatras junto às portas, inclusive o altar da entrada da porta de Josué, o governador da cidade, que fica à esquerda da porta da cidade.

[[v12-23-9]]

^<<v12-23-9,9>>^ Embora os sacerdotes dos altares não servissem no altar do Senhor em Jerusalém, comiam pães sem fermento junto com os sacerdotes, seus colegas.

[[v12-23-10]]

^<<v12-23-10,10>>^ Também profanou Tofete, que ficava no vale de Ben-Hinom, de modo que ninguém mais pudesse usá-lo para queimar seu filho ou filha em sacrifício a Moloque.

[[v12-23-11]]

^<<v12-23-11,11>>^ Acabou com os cavalos que os reis de Judá tinham consagrado ao sol. Estavam na entrada do templo do Senhor perto da sala de um oficial chamado Natã-Meleque. Também queimou as carruagens consagradas ao sol.

[[v12-23-12]]

^<<v12-23-12,12>>^ Derrubou os altares que os seus antecessores haviam erguido no terraço, em cima do quarto superior de Acaz, e os altares que Manassés havia construído nos dois pátios do templo do Senhor. Retirou-os dali, despedaçou-os e atirou o entulho no vale de Cedrom.

[[v12-23-13]]

^<<v12-23-13,13>>^ O rei também profanou os altares que ficavam a leste de Jerusalém no sul do monte da Destruição, os quais Salomão, rei de Israel, havia construído para o poste sagrado, a detestável deusa dos sidônios, para Camos, o detestável deus de Moabe, e para Moloque, o detestável deus do povo de Amom.

[[v12-23-14]]

^<<v12-23-14,14>>^ Josias despedaçou as colunas sagradas, derrubou os postes sagrados e cobriu os locais com ossos humanos.

[[v12-23-15]]

^<<v12-23-15,15>>^ Até o altar de Betel, o altar idólatra edificado por Jeroboão, filho de Nebate, que levou Israel a pecar; até aquele altar e o seu santuário, ele os demoliu. Queimou o santuário e o reduziu a pó, queimando também o poste sagrado.

[[v12-23-16]]

^<<v12-23-16,16>>^ Quando Josias olhou em volta e, viu os túmulos que havia na encosta da colina, mandou retirar os ossos dos túmulos e queimá-los no altar a fim de contaminá-lo, conforme a palavra do Senhor proclamada pelo homem de Deus que predisse essas coisas.

[[v12-23-17]]

^<<v12-23-17,17>>^ O rei perguntou: "Que monumento é este que estou vendo? " Os homens da cidade disseram: "É o túmulo do homem de Deus que veio de Judá e proclamou estas coisas que tu fizeste ao altar de Betel".

[[v12-23-18]]

^<<v12-23-18,18>>^ Então ele disse: "Deixem-no em paz. Ninguém toque nos seus ossos". Assim pouparam seus ossos bem como os do profeta que tinha vindo de Samaria.

[[v12-23-19]]

^<<v12-23-19,19>>^ Como havia feito em Betel, Josias tirou e profanou todos os santuários idólatras que os reis de Israel haviam construído nas cidades de Samaria e que provocaram o Senhor à ira.

[[v12-23-20]]

^<<v12-23-20,20>>^ Josias também mandou sacrificar todos os sacerdotes daqueles altares idólatras e queimou ossos humanos sobre os altares. Depois voltou a Jerusalém.

[[v12-23-21]]

^<<v12-23-21,21>>^ Então o rei deu a seguinte ordem a todo o povo: "Celebrem a Páscoa ao Senhor seu Deus, conforme está escrito neste livro da Aliança".

[[v12-23-22]]

^<<v12-23-22,22>>^ Nem nos dias dos juízes que lideraram Israel, nem durante todos os dias dos reis de Israel e dos reis de Judá, foi celebrada uma Páscoa como esta.

[[v12-23-23]]

^<<v12-23-23,23>>^ Mas no décimo oitavo ano do reinado de Josias, esta Páscoa foi celebrada ao Senhor em Jerusalém.

[[v12-23-24]]

^<<v12-23-24,24>>^ Além disso, Josias eliminou os médiuns, os espíritas, os ídolos da família, os ídolos e todas as outras coisas repugnantes que havia em Judá e em Jerusalém. Ele fez isto para cumprir as exigências da lei escritas no livro que o sacerdote Hilquias havia descoberto no templo do Senhor.

[[v12-23-25]]

^<<v12-23-25,25>>^ Nem antes nem depois de Josias houve um rei como ele, que se voltasse para o Senhor de todo o coração, de toda a alma e de todas as suas forças, de acordo com toda a Lei de Moisés.

[[v12-23-26]]

^<<v12-23-26,26>>^ Entretanto, o Senhor não voltou atrás do fogo de sua grande ira, que se acendeu contra Judá por causa de tudo o que Manassés fizera para provocá-lo à ira.

[[v12-23-27]]

^<<v12-23-27,27>>^ Por isso o Senhor disse: "Também retirarei Judá da minha presença, tal como retirei de Israel, e rejeitarei Jerusalém, a cidade que escolhi, e este templo, do qual eu disse: ‘Ali porei o meu nome’ ".

[[v12-23-28]]

^<<v12-23-28,28>>^ Os demais acontecimentos do reinado de Josias e todas as suas realizações, estão escritos no livro dos registros históricos dos reis de Judá.

[[v12-23-29]]

^<<v12-23-29,29>>^ Durante o seu reinado, o faraó Neco, rei do Egito, avançou até o rio Eufrates ao encontro do rei da Assíria. O rei Josias marchou para combatê-lo, mas o faraó Neco o enfrentou e o matou em Megido.

[[v12-23-30]]

^<<v12-23-30,30>>^ Os oficiais de Josias levaram o seu corpo de Megido para Jerusalém, e o sepultaram em seu próprio túmulo. O povo tomou Jeoacaz, filho de Josias, ungiu-o e o proclamou como rei no lugar de seu pai.

[[v12-23-31]]

^<<v12-23-31,31>>^ Jeoacaz tinha vinte e três anos de idade quando começou a reinar, e reinou três meses em Jerusalém. O nome de sua mãe era Hamutal, filha de Jeremias; ela era de Libna.

[[v12-23-32]]

^<<v12-23-32,32>>^ Ele fez o que o Senhor reprova, tal como seus antepassados.

[[v12-23-33]]

^<<v12-23-33,33>>^ O faraó Neco o prendeu em Ribla, na terra de Hamate, de modo que não mais reinou em Jerusalém. O faraó também impôs a Judá um tributo de três toneladas e meia de prata e trinta e cinco quilos de ouro.

[[v12-23-34]]

^<<v12-23-34,34>>^ Colocou Eliaquim, filho de Josias, como rei no lugar do seu pai Josias, e mudou o nome de Eliaquim para Jeoaquim. Mas levou Jeoacaz consigo para o Egito, onde ele morreu.

[[v12-23-35]]

^<<v12-23-35,35>>^ Jeoaquim pagou ao faraó Neco a prata e o ouro. Mas, para cumprir as exigências do faraó, Jeoaquim impôs tributos ao povo, cobrando a prata e o ouro, de cada um conforme suas posses.

[[v12-23-36]]

^<<v12-23-36,36>>^ Jeoaquim tinha vinte e cinco anos de idade quando começou a reinar, e reinou onze anos em Jerusalém. O nome de sua mãe era Zebida, filha de Pedaías; ela era de Ruma.

[[v12-23-37]]

^<<v12-23-37,37>>^ Ele fez o que o Senhor reprova, tal como seus antepassados.

'''

xref:012-2-reis/012-2-reis-022.adoc#v12-22-0[&#60; Capítulo Anterior] | <<v12-23-0,Topo>> | xref:012-2-reis/012-2-reis-024.adoc#v12-24-0[Próximo Capítulo &#62;]