include::./index.adoc[]

[[v12-4-0]]
=== 2 Reis, 4
// nvi ?, NVI - Nova Versão Internacional

[[v12-4-1]]

^<<v12-4-1,1>>^ Certo dia, a mulher de um dos discípulos dos profetas foi falar a Eliseu: "Teu servo, meu marido, morreu, e tu sabes que ele temia o Senhor. Mas agora veio um credor que está querendo levar meus dois filhos como escravos".

[[v12-4-2]]

^<<v12-4-2,2>>^ Eliseu perguntou-lhe: "Como posso ajudá-la? Diga-me, o que você tem em casa? " E ela respondeu: "Tua serva não tem nada além de uma vasilha de azeite".

[[v12-4-3]]

^<<v12-4-3,3>>^ Então disse Eliseu: "Vá pedir emprestadas vasilhas a todos os vizinhos. Mas, peça muitas.

[[v12-4-4]]

^<<v12-4-4,4>>^ Depois entre em casa com seus filhos e feche a porta. Derrame daquele azeite em cada vasilha e vá separando as que você for enchendo".

[[v12-4-5]]

^<<v12-4-5,5>>^ Depois disso, ela foi embora, fechou-se em casa com seus filhos e começou a encher as vasilhas que eles lhe traziam.

[[v12-4-6]]

^<<v12-4-6,6>>^ Quando todas as vasilhas estavam cheias, ela disse a um dos filhos: "Traga-me mais uma". Mas ele respondeu: "Já acabaram". Então o azeite parou de correr.

[[v12-4-7]]

^<<v12-4-7,7>>^ Ela foi e contou tudo ao homem de Deus, que lhe disse: "Vá, venda o azeite e pague suas dívidas. E você e seus filhos ainda poderão viver do que sobrar".

[[v12-4-8]]

^<<v12-4-8,8>>^ Certo dia, Eliseu foi a Suném, onde uma mulher rica insistiu que ele fosse tomar uma refeição em sua casa. Depois disso, sempre que passava por ali, ele parava para uma refeição.

[[v12-4-9]]

^<<v12-4-9,9>>^ De modo que ela disse ao marido: "Sei que esse homem que sempre vem aqui é um santo homem de Deus.

[[v12-4-10]]

^<<v12-4-10,10>>^ Vamos construir lá em cima um quartinho de tijolos e colocar nele uma cama, uma mesa, uma cadeira e uma lamparina para ele. Assim, sempre que nos visitar ele poderá ocupá-lo".

[[v12-4-11]]

^<<v12-4-11,11>>^ Um dia, quando Eliseu chegou, subiu ao seu quarto e deitou-se.

[[v12-4-12]]

^<<v12-4-12,12>>^ Ele mandou o seu servo Geazi chamar a sunamita. Então ele a chamou, e quando ela veio,

[[v12-4-13]]

^<<v12-4-13,13>>^ Eliseu mandou que Geazi dissesse a ela: "Você teve todo este trabalho por nossa causa. O que podemos fazer por você? Quer que eu interceda por você junto ao rei ou ao comandante do exército? " Ela respondeu: "Estou bem entre minha própria gente".

[[v12-4-14]]

^<<v12-4-14,14>>^ Mais tarde Eliseu perguntou a Geazi: "O que se pode fazer por ela? " Ele respondeu: "Bem, ela não tem filhos, e seu marido é idoso".

[[v12-4-15]]

^<<v12-4-15,15>>^ Então Eliseu mandou chamá-la de novo. Geazi a chamou, e ela veio até a porta.

[[v12-4-16]]

^<<v12-4-16,16>>^ E ele disse: "Por volta desta época, no ano que vem, você estará com um filho nos braços". Ela contestou: "Não, meu senhor. Não iludas a tua serva, ó homem de Deus! "

[[v12-4-17]]

^<<v12-4-17,17>>^ Mas, como Eliseu lhe dissera, a mulher engravidou e, no ano seguinte, por volta daquela mesma época, deu à luz um filho.

[[v12-4-18]]

^<<v12-4-18,18>>^ O menino cresceu e, certo dia, foi encontrar seu pai, que estava com os ceifeiros.

[[v12-4-19]]

^<<v12-4-19,19>>^ De repente, ele começou a chamar o pai, gritando: "Ai, minha cabeça! Ai, minha cabeça! " Então o pai disse a um servo: "Leve-o para a mãe dele".

[[v12-4-20]]

^<<v12-4-20,20>>^ O servo o pegou e o levou à mãe, o menino ficou no colo dela até o meio-dia, quando morreu.

[[v12-4-21]]

^<<v12-4-21,21>>^ Ela subiu ao quarto do homem de Deus, deitou o menino na cama, saiu e fechou a porta.

[[v12-4-22]]

^<<v12-4-22,22>>^ Ela chamou o marido e disse: "Preciso de um servo e uma jumenta para ir falar com o homem de Deus. Vou e volto depressa".

[[v12-4-23]]

^<<v12-4-23,23>>^ Ele perguntou: "Mas, por que hoje? Não é lua nova nem sábado! " Ela respondeu: "Não se preocupe".

[[v12-4-24]]

^<<v12-4-24,24>>^ Ela mandou selar a jumenta, e disse ao servo: "Vamos rápido, só pare quando eu mandar".

[[v12-4-25]]

^<<v12-4-25,25>>^ Assim ela partiu para encontrar-se com o homem de Deus no monte Carmelo. Quando ele a viu a distância, disse a seu servo Geazi: "Olhe! É a sunamita!

[[v12-4-26]]

^<<v12-4-26,26>>^ Corra ao encontro dela e lhe pergunte: ‘Está tudo bem com você? Tudo bem com seu marido? E com seu filho? ’ " Ela respondeu a Geazi: "Está tudo bem".

[[v12-4-27]]

^<<v12-4-27,27>>^ Ao encontrar o homem de Deus no monte, ela se abraçou aos seus pés. Geazi veio para afastá-la, mas o homem de Deus lhe disse: "Deixe-a em paz! Ela está muito angustiada, mas o Senhor nada me revelou e escondeu de mim a razão de sua angústia".

[[v12-4-28]]

^<<v12-4-28,28>>^ E disse a mulher: "Acaso eu te pedi um filho, meu senhor? Não te disse para não me dar falsas esperanças? "

[[v12-4-29]]

^<<v12-4-29,29>>^ Então Eliseu disse a Geazi: "Ponha a capa por dentro do cinto, pegue o meu cajado e corra. Se você encontrar alguém, não o cumprimente e, se alguém o cumprimentar, não responda. Quando lá chegar, ponha o meu cajado sobre o rosto do menino".

[[v12-4-30]]

^<<v12-4-30,30>>^ Mas a mãe do menino disse: "Juro pelo nome do Senhor e por tua vida que, se ficares, não irei". Então ele foi com ela.

[[v12-4-31]]

^<<v12-4-31,31>>^ Geazi chegou primeiro e pôs o cajado sobre o rosto do menino, mas ele não falou nem reagiu. Então Geazi voltou para encontrar-se com Eliseu e lhe disse: "O menino não voltou a si".

[[v12-4-32]]

^<<v12-4-32,32>>^ Quando Eliseu chegou à casa, lá estava o menino, morto, estendido na cama.

[[v12-4-33]]

^<<v12-4-33,33>>^ Ele entrou, fechou a porta e orou ao Senhor.

[[v12-4-34]]

^<<v12-4-34,34>>^ Então, deitou-se sobre o menino, boca a boca, olhos com olhos, mãos com mãos. Enquanto se debruçava sobre ele, o corpo do menino foi se aquecendo.

[[v12-4-35]]

^<<v12-4-35,35>>^ Eliseu levantou-se e começou a andar pelo quarto; depois subiu na cama e debruçou-se mais uma vez sobre ele. O menino espirrou sete vezes e abriu os olhos.

[[v12-4-36]]

^<<v12-4-36,36>>^ Eliseu chamou Geazi e o mandou chamar a sunamita. E ele obedeceu. Quando ela chegou, Eliseu disse: "Pegue seu filho".

[[v12-4-37]]

^<<v12-4-37,37>>^ Ela entrou, prostrou-se a seus pés, curvando-se até o chão. Então pegou o filho e saiu.

[[v12-4-38]]

^<<v12-4-38,38>>^ Depois Eliseu voltou a Gilgal. Nesse tempo a fome assolava a região. Quando os discípulos dos profetas estavam reunidos com ele, ordenou ao seu servo: "Ponha o caldeirão no fogo e faça um ensopado para estes homens".

[[v12-4-39]]

^<<v12-4-39,39>>^ Um deles foi ao campo apanhar legumes e encontrou uma trepadeira. Apanhou alguns de seus frutos e encheu deles o seu manto. Quando voltou, cortou-os em pedaços e colocou-os no caldeirão do ensopado, embora ninguém soubesse o que era.

[[v12-4-40]]

^<<v12-4-40,40>>^ O ensopado foi servido aos homens, mas, logo que o provaram, eles gritaram: "Homem de Deus, há morte na panela! " E não puderam mais tomá-lo.

[[v12-4-41]]

^<<v12-4-41,41>>^ Então Eliseu pediu um pouco de farinha, colocou no caldeirão e disse: "Sirvam a todos". E já não havia mais perigo no caldeirão.

[[v12-4-42]]

^<<v12-4-42,42>>^ Veio um homem de Baal-Salisa, trazendo ao homem de Deus vinte pães de cevada, feitos dos primeiros grãos da colheita, e também algumas espigas verdes. Então Eliseu ordenou ao seu servo: "Sirva a todos".

[[v12-4-43]]

^<<v12-4-43,43>>^ O auxiliar de Eliseu perguntou: "Como poderei servir isso a cem homens? " Eliseu, porém, respondeu: "Sirva a todos, pois assim diz o Senhor: ‘Eles comerão, e ainda sobrará’ ".

[[v12-4-44]]

^<<v12-4-44,44>>^ Então ele serviu a todos, e conforme a palavra do Senhor, eles comeram e ainda sobrou.

'''

xref:012-2-reis/012-2-reis-003.adoc#v12-3-0[&#60; Capítulo Anterior] | <<v12-4-0,Topo>> | xref:012-2-reis/012-2-reis-005.adoc#v12-5-0[Próximo Capítulo &#62;]