include::./index.adoc[]

[[v12-16-0]]
=== 2 Reis, 16
// nvi ?, NVI - Nova Versão Internacional

[[v12-16-1]]

^<<v12-16-1,1>>^ No décimo sétimo ano do reinado de Peca, filho de Remalias, Acaz, filho de Jotão, rei de Judá, começou a reinar.

[[v12-16-2]]

^<<v12-16-2,2>>^ Acaz tinha vinte anos de idade quando começou a reinar e reinou dezesseis anos em Jerusalém. Ao contrário de Davi, seu predecessor, não fez o que o Senhor seu Deus aprova.

[[v12-16-3]]

^<<v12-16-3,3>>^ Andou nos caminhos dos reis de Israel e chegou até a queimar o seu filho em sacrifício, imitando os costumes detestáveis das nações que o Senhor havia expulsado de diante dos israelitas.

[[v12-16-4]]

^<<v12-16-4,4>>^ Também ofereceu sacrifícios e queimou incenso nos altares idólatras, no alto das colinas e debaixo de toda árvore frondosa.

[[v12-16-5]]

^<<v12-16-5,5>>^ Então Rezim, rei da Síria, e Peca, filho de Remalias, rei de Israel, saíram para lutar contra Acaz e sitiaram Jerusalém, mas não conseguiram vencê-lo.

[[v12-16-6]]

^<<v12-16-6,6>>^ Naquela ocasião, Rezim recuperou Elate para a Síria, expulsando os homens de Judá. Os edomitas então se mudaram para Elate, onde vivem até hoje.

[[v12-16-7]]

^<<v12-16-7,7>>^ Acaz enviou mensageiros para dizer a Tiglate-Pileser, rei da Assíria: "Sou teu servo e teu vassalo. Vem salvar-me das mãos do rei da Síria e do rei de Israel, que estão me atacando".

[[v12-16-8]]

^<<v12-16-8,8>>^ Acaz ajuntou a prata e o ouro encontrados no templo do Senhor e nos tesouros do palácio real e enviou-os como presente para o rei da Assíria.

[[v12-16-9]]

^<<v12-16-9,9>>^ Este atendeu o pedido, atacou Damasco e a conquistou. Deportou seus habitantes para Quir e matou a Rezim.

[[v12-16-10]]

^<<v12-16-10,10>>^ Então o rei Acaz foi a Damasco encontrar-se com Tiglate-Pileser, rei da Assíria. Ele viu o altar que havia em Damasco e mandou ao sacerdote Urias um modelo do altar, com informações detalhadas para sua construção.

[[v12-16-11]]

^<<v12-16-11,11>>^ O sacerdote Urias construiu um altar conforme as instruções que o rei Acaz tinha enviado de Damasco e o terminou antes do retorno do rei Acaz.

[[v12-16-12]]

^<<v12-16-12,12>>^ Quando o rei voltou de Damasco e viu o altar, aproximou-se dele e apresentou ofertas sobre ele.

[[v12-16-13]]

^<<v12-16-13,13>>^ Ofereceu seu holocausto e sua oferta de cereal, derramou sua oferta de bebidas e aspergiu sobre o altar o sangue dos seus sacrifícios de comunhão.

[[v12-16-14]]

^<<v12-16-14,14>>^ Ele tirou da frente do templo, dentre o altar e o templo do Senhor, o altar de bronze que ficava diante do Senhor e o colocou no lado norte do altar.

[[v12-16-15]]

^<<v12-16-15,15>>^ Então o rei Acaz deu estas ordens ao sacerdote Urias: "No altar grande, ofereça o holocausto da manhã e a oferta de cereal da tarde, o holocausto do rei e sua oferta de cereal, e o holocausto, a oferta de cereal e a oferta derramada de todo o povo. Espalhe sobre o altar todo o sangue dos holocaustos e dos sacrifícios. Mas utilizarei o altar de bronze para buscar orientação".

[[v12-16-16]]

^<<v12-16-16,16>>^ E o sacerdote Urias fez como o rei Acaz tinha ordenado.

[[v12-16-17]]

^<<v12-16-17,17>>^ O rei tirou os painéis laterais e retirou as pias dos estrados móveis. Tirou o tanque de cima dos touros de bronze que o sustentavam e o colocou sobre uma base de pedra.

[[v12-16-18]]

^<<v12-16-18,18>>^ Por causa do rei da Assíria tirou a cobertura para ser usada no sábado, que fora construída no templo, e retirou a entrada real do lado de fora do templo do Senhor.

[[v12-16-19]]

^<<v12-16-19,19>>^ Os demais acontecimentos do reinado de Acaz, e suas realizações, estão escritos nos registros históricos dos reis de Judá.

[[v12-16-20]]

^<<v12-16-20,20>>^ Acaz descansou com seus antepassados e foi sepultado junto a eles na cidade de Davi. Seu filho Ezequias foi o seu sucessor.

'''

xref:012-2-reis/012-2-reis-015.adoc#v12-15-0[&#60; Capítulo Anterior] | <<v12-16-0,Topo>> | xref:012-2-reis/012-2-reis-017.adoc#v12-17-0[Próximo Capítulo &#62;]