include::./index.adoc[]

[[v1-44-0]]
=== Gênesis, 44
// nvi ?, NVI - Nova Versão Internacional

[[v1-44-1]]

^<<v1-44-1,1>>^ José deu as seguintes ordens ao administrador de sua casa: "Encha as bagagens desses homens com todo o mantimento que puderem carregar e coloque a prata de cada um na boca de sua bagagem.

[[v1-44-2]]

^<<v1-44-2,2>>^ Depois coloque a minha taça, a taça de prata, na boca da bagagem do caçula, juntamente com a prata paga pelo trigo". E ele fez tudo conforme as ordens de José.

[[v1-44-3]]

^<<v1-44-3,3>>^ Assim que despontou a manhã, despediram os homens com os seus jumentos.

[[v1-44-4]]

^<<v1-44-4,4>>^ Ainda não tinham se afastado da cidade, quando José disse ao administrador de sua casa: "Vá atrás daqueles homens e, quando os alcançar, diga-lhes: Por que retribuíram o bem com o mal?

[[v1-44-5]]

^<<v1-44-5,5>>^ Não é esta a taça que o meu senhor usa para beber e para fazer adivinhações? Vocês cometeram grande maldade! "

[[v1-44-6]]

^<<v1-44-6,6>>^ Quando ele os alcançou, repetiu-lhes essas palavras.

[[v1-44-7]]

^<<v1-44-7,7>>^ Mas eles lhe responderam: "Por que o meu senhor diz isso? Longe dos seus servos fazer tal coisa!

[[v1-44-8]]

^<<v1-44-8,8>>^ Nós lhe trouxemos de volta, da terra de Canaã, a prata que encontramos na boca de nossa bagagem. Como roubaríamos prata ou ouro da casa do seu senhor?

[[v1-44-9]]

^<<v1-44-9,9>>^ Se algum dos seus servos for encontrado com ela, morrerá; e nós, os demais, seremos escravos do meu senhor".

[[v1-44-10]]

^<<v1-44-10,10>>^ E disse ele: "Concordo. Somente quem for encontrado com ela será meu escravo; os demais estarão livres".

[[v1-44-11]]

^<<v1-44-11,11>>^ Cada um deles descarregou depressa a sua bagagem e abriu-a.

[[v1-44-12]]

^<<v1-44-12,12>>^ O administrador começou então a busca, desde a bagagem do mais velho até a do mais novo. E a taça foi encontrada na bagagem de Benjamim.

[[v1-44-13]]

^<<v1-44-13,13>>^ Diante disso, eles rasgaram as suas vestes. Em seguida, todos puseram a carga de novo em seus jumentos e retornaram à cidade.

[[v1-44-14]]

^<<v1-44-14,14>>^ Quando Judá e seus irmãos chegaram à casa de José, ele ainda estava lá. Então eles se lançaram ao chão perante ele.

[[v1-44-15]]

^<<v1-44-15,15>>^ E José lhes perguntou: "Que foi que vocês fizeram? Vocês não sabem que um homem como eu tem poder para adivinhar? "

[[v1-44-16]]

^<<v1-44-16,16>>^ Respondeu Judá: "O que diremos a meu senhor? Que podemos falar? Como podemos provar nossa inocência? Deus trouxe à luz a culpa dos teus servos. Agora somos escravos do meu senhor, como também aquele que foi encontrado com a taça".

[[v1-44-17]]

^<<v1-44-17,17>>^ Disse, porém, José: "Longe de mim fazer tal coisa! Somente aquele que foi encontrado com a taça será meu escravo. Os demais podem voltar em paz para a casa do seu pai".

[[v1-44-18]]

^<<v1-44-18,18>>^ Então Judá dirigiu-se a ele, dizendo: "Por favor, meu senhor, permite-me dizer-te uma palavra. Não se acenda a tua ira contra o teu servo, embora sejas igual ao próprio faraó.

[[v1-44-19]]

^<<v1-44-19,19>>^ Meu senhor perguntou a estes seus servos se ainda tínhamos pai e algum outro irmão.

[[v1-44-20]]

^<<v1-44-20,20>>^ E nós respondemos: Temos um pai já idoso, cujo filho caçula nasceu-lhe em sua velhice. O irmão deste já morreu, e ele é o único filho da mesma mãe que restou, e seu pai o ama muito.

[[v1-44-21]]

^<<v1-44-21,21>>^ "Então disseste a teus servos que o trouxessem a ti para que os teus olhos pudessem vê-lo.

[[v1-44-22]]

^<<v1-44-22,22>>^ E nós respondemos a meu senhor que o jovem não poderia deixar seu pai, pois, caso o fizesse, seu pai morreria.

[[v1-44-23]]

^<<v1-44-23,23>>^ Todavia disseste a teus servos que se o nosso irmão caçula não viesse conosco, nunca mais veríamos a tua face.

[[v1-44-24]]

^<<v1-44-24,24>>^ Quando voltamos a teu servo, a meu pai, contamos-lhe o que o meu senhor tinha dito.

[[v1-44-25]]

^<<v1-44-25,25>>^ "Quando o nosso pai nos mandou voltar para comprar um pouco mais de comida,

[[v1-44-26]]

^<<v1-44-26,26>>^ nós lhe dissemos: Só poderemos voltar para lá, se o nosso irmão caçula for conosco. Pois não poderemos ver a face daquele homem, a não ser que o nosso irmão caçula esteja conosco.

[[v1-44-27]]

^<<v1-44-27,27>>^ "Teu servo, meu pai, nos disse então: ‘Vocês sabem que minha mulher me deu apenas dois filhos.

[[v1-44-28]]

^<<v1-44-28,28>>^ Um deles se foi, e eu disse: Com certeza foi despedaçado. E até hoje, nunca mais o vi.

[[v1-44-29]]

^<<v1-44-29,29>>^ Se agora vocês também levarem este de mim, e algum mal lhe acontecer, a tristeza que me causarão fará com que os meus cabelos brancos desçam à sepultura’.

[[v1-44-30]]

^<<v1-44-30,30>>^ "Agora, pois, se eu voltar a teu servo, a meu pai, sem levar o jovem conosco, logo que meu pai, que é tão apegado a ele,

[[v1-44-31]]

^<<v1-44-31,31>>^ perceber que o jovem não está conosco, morrerá. Teus servos farão seu velho pai descer seus cabelos brancos à sepultura com tristeza.

[[v1-44-32]]

^<<v1-44-32,32>>^ "Além disso, teu servo garantiu a segurança do jovem a seu pai, dizendo-lhe: Se eu não o trouxer de volta, suportarei essa culpa diante de ti pelo resto da minha vida!

[[v1-44-33]]

^<<v1-44-33,33>>^ "Por isso agora te peço, por favor, deixa o teu servo ficar como escravo do meu senhor no lugar do jovem e permite que ele volte com os seus irmãos.

[[v1-44-34]]

^<<v1-44-34,34>>^ Como poderei eu voltar a meu pai sem levar o jovem comigo? Não! Não posso ver o mal que sobreviria a meu pai".

'''

xref:001-genesis/001-genesis-043.adoc#v1-43-0[&#60; Capítulo Anterior] | <<v1-44-0,Topo>> | xref:001-genesis/001-genesis-045.adoc#v1-45-0[Próximo Capítulo &#62;]