include::./index.adoc[]

[[v1-39-0]]
=== Gênesis, 39
// nvi ?, NVI - Nova Versão Internacional

[[v1-39-1]]

^<<v1-39-1,1>>^ José havia sido levado para o Egito, onde o egípcio Potifar, oficial do faraó e capitão da guarda, comprou-o dos ismaelitas que o tinham levado para lá.

[[v1-39-2]]

^<<v1-39-2,2>>^ O Senhor estava com José, de modo que este prosperou e passou a morar na casa do seu senhor egípcio.

[[v1-39-3]]

^<<v1-39-3,3>>^ Quando este percebeu que o Senhor estava com ele e que o fazia prosperar em tudo o que realizava,

[[v1-39-4]]

^<<v1-39-4,4>>^ agradou-se de José e tornou-o administrador de seus bens. Potifar deixou a seu cuidado a sua casa e lhe confiou tudo o que possuía.

[[v1-39-5]]

^<<v1-39-5,5>>^ Desde que o deixou cuidando de sua casa e de todos os seus bens, o Senhor abençoou a casa do egípcio por causa de José. A bênção do Senhor estava sobre tudo o que Potifar possuía, tanto em casa como no campo.

[[v1-39-6]]

^<<v1-39-6,6>>^ Assim, deixou ele aos cuidados de José tudo o que tinha, e não se preocupava com coisa alguma, exceto com sua própria comida. José era atraente e de boa aparência,

[[v1-39-7]]

^<<v1-39-7,7>>^ e, depois de certo tempo, a mulher do seu senhor começou a cobiçá-lo e o convidou: "Venha, deite-se comigo! "

[[v1-39-8]]

^<<v1-39-8,8>>^ Mas ele se recusou e lhe disse: "Meu senhor não se preocupa com coisa alguma de sua casa, e tudo o que tem deixou aos meus cuidados.

[[v1-39-9]]

^<<v1-39-9,9>>^ Ninguém desta casa está acima de mim. Ele nada me negou, a não ser a senhora, porque é a mulher dele. Como poderia eu, então, cometer algo tão perverso e pecar contra Deus? "

[[v1-39-10]]

^<<v1-39-10,10>>^ Assim, embora ela insistisse com José dia após dia, ele se recusava a deitar-se com ela e evitava ficar perto dela.

[[v1-39-11]]

^<<v1-39-11,11>>^ Um dia ele entrou na casa para fazer suas tarefas, e nenhum dos empregados ali se encontrava.

[[v1-39-12]]

^<<v1-39-12,12>>^ Ela o agarrou pelo manto e voltou a convidá-lo: "Vamos, deite-se comigo! " Mas ele fugiu da casa, deixando o manto na mão dela.

[[v1-39-13]]

^<<v1-39-13,13>>^ Quando ela viu que, ao fugir, ele tinha deixado o manto em sua mão,

[[v1-39-14]]

^<<v1-39-14,14>>^ chamou os empregados e lhes disse: "Vejam, este hebreu nos foi trazido para nos insultar! Ele entrou aqui e tentou abusar de mim, mas eu gritei.

[[v1-39-15]]

^<<v1-39-15,15>>^ Quando me ouviu gritar por socorro, largou seu manto ao meu lado e fugiu da casa".

[[v1-39-16]]

^<<v1-39-16,16>>^ Ela conservou o manto consigo até que o senhor de José chegasse em casa.

[[v1-39-17]]

^<<v1-39-17,17>>^ Então repetiu-lhe a história: "Aquele escravo hebreu que você nos trouxe aproximou-se de mim para me insultar.

[[v1-39-18]]

^<<v1-39-18,18>>^ Mas, quando gritei por socorro, ele largou seu manto ao meu lado e fugiu".

[[v1-39-19]]

^<<v1-39-19,19>>^ Quando o seu senhor ouviu o que a sua mulher lhe disse: "Foi assim que o seu escravo me tratou", ficou indignado.

[[v1-39-20]]

^<<v1-39-20,20>>^ Mandou buscar José e lançou-o na prisão em que eram postos os prisioneiros do rei. José ficou na prisão,

[[v1-39-21]]

^<<v1-39-21,21>>^ mas o Senhor estava com ele e o tratou com bondade, concedendo-lhe a simpatia do carcereiro.

[[v1-39-22]]

^<<v1-39-22,22>>^ Por isso o carcereiro encarregou José de todos os que estavam na prisão, e ele se tornou responsável por tudo o que lá sucedia.

[[v1-39-23]]

^<<v1-39-23,23>>^ O carcereiro não se preocupava com nada do que estava a cargo de José, porque o Senhor estava com José e lhe concedia bom êxito em tudo o que realizava.

'''

xref:001-genesis/001-genesis-038.adoc#v1-38-0[&#60; Capítulo Anterior] | <<v1-39-0,Topo>> | xref:001-genesis/001-genesis-040.adoc#v1-40-0[Próximo Capítulo &#62;]