include::./index.adoc[]

[[v1-28-0]]
=== Gênesis, 28
// nvi ?, NVI - Nova Versão Internacional

[[v1-28-1]]

^<<v1-28-1,1>>^ Então Isaque chamou Jacó, deu-lhe sua bênção e lhe ordenou: "Não se case com mulher cananéia.

[[v1-28-2]]

^<<v1-28-2,2>>^ Vá a Padã-Arã, à casa de Betuel, seu avô materno, e case-se com uma das filhas de Labão, irmão de sua mãe.

[[v1-28-3]]

^<<v1-28-3,3>>^ Que o Deus Todo-poderoso o abençoe, faça-o prolífero e multiplique os seus descendentes, para que você se torne uma comunidade de povos.

[[v1-28-4]]

^<<v1-28-4,4>>^ Que ele dê a você e a seus descendentes a bênção de Abraão, para que você tome posse da terra na qual vive como estrangeiro, a terra dada por Deus a Abraão".

[[v1-28-5]]

^<<v1-28-5,5>>^ Então Isaque despediu Jacó e este foi a Padã-Arã, a Labão, filho de Betuel, o arameu, e irmão de Rebeca, mãe de Jacó e Esaú.

[[v1-28-6]]

^<<v1-28-6,6>>^ Esaú viu que Isaque havia abençoado a Jacó e o havia mandado a Padã-Arã para escolher ali uma mulher e que, ao abençoá-lo, dera-lhe a ordem de não se casar com mulher cananéia.

[[v1-28-7]]

^<<v1-28-7,7>>^ Também soube que Jacó obedecera a seu pai e a sua mãe e fora para Padã-Arã.

[[v1-28-8]]

^<<v1-28-8,8>>^ Percebendo então Esaú que seu pai Isaque não aprovava as mulheres cananéias,

[[v1-28-9]]

^<<v1-28-9,9>>^ foi à casa de Ismael e tomou a Maalate, irmã de Nebaiote, filha de Ismael, filho de Abraão, além das outras mulheres que já tinha.

[[v1-28-10]]

^<<v1-28-10,10>>^ Jacó partiu de Berseba e foi para Harã.

[[v1-28-11]]

^<<v1-28-11,11>>^ Chegando a determinado lugar, parou para pernoitar, porque o sol já se havia posto. Tomando uma das pedras dali, usou-a como travesseiro e deitou-se.

[[v1-28-12]]

^<<v1-28-12,12>>^ E teve um sonho no qual viu uma escada apoiada na terra; o seu topo alcançava os céus, e os anjos de Deus subiam e desciam por ela.

[[v1-28-13]]

^<<v1-28-13,13>>^ Ao lado dele estava o Senhor, que lhe disse: "Eu sou o Senhor, o Deus de seu pai Abraão e o Deus de Isaque. Darei a você e a seus descendentes a terra na qual você está deitado.

[[v1-28-14]]

^<<v1-28-14,14>>^ Seus descendentes serão como o pó da terra, e se espalharão para o Oeste e para o Leste, para o Norte e para o Sul. Todos os povos da terra serão abençoados por meio de você e da sua descendência.

[[v1-28-15]]

^<<v1-28-15,15>>^ Estou com você e cuidarei de você, aonde quer que vá; e eu o trarei de volta a esta terra. Não o deixarei enquanto não fizer o que lhe prometi".

[[v1-28-16]]

^<<v1-28-16,16>>^ Quando Jacó acordou do sono, disse: "Sem dúvida o Senhor está neste lugar, mas eu não sabia! "

[[v1-28-17]]

^<<v1-28-17,17>>^ Teve medo e disse: "Temível é este lugar! Não é outro, senão a casa de Deus; esta é a porta dos céus".

[[v1-28-18]]

^<<v1-28-18,18>>^ Na manhã seguinte, Jacó pegou a pedra que tinha usado como travesseiro, colocou-a de pé como coluna e derramou óleo sobre o seu topo.

[[v1-28-19]]

^<<v1-28-19,19>>^ E deu o nome de Betel àquele lugar, embora a cidade anteriormente se chamasse Luz.

[[v1-28-20]]

^<<v1-28-20,20>>^ Então Jacó fez um voto, dizendo: "Se Deus estiver comigo, cuidar de mim nesta viagem que estou fazendo, prover-me de comida e roupa,

[[v1-28-21]]

^<<v1-28-21,21>>^ e levar-me de volta em segurança à casa de meu pai, então o Senhor será o meu Deus.

[[v1-28-22]]

^<<v1-28-22,22>>^ E esta pedra que hoje coloquei como coluna servirá de santuário de Deus; e de tudo o que me deres certamente te darei o dízimo".

'''

xref:001-genesis/001-genesis-027.adoc#v1-27-0[&#60; Capítulo Anterior] | <<v1-28-0,Topo>> | xref:001-genesis/001-genesis-029.adoc#v1-29-0[Próximo Capítulo &#62;]