include::./index.adoc[]

[[v1-43-0]]
=== Gênesis, 43
// nvi ?, NVI - Nova Versão Internacional

[[v1-43-1]]

^<<v1-43-1,1>>^ A fome continuava rigorosa na terra.

[[v1-43-2]]

^<<v1-43-2,2>>^ Assim, quando acabou todo o trigo que os filhos de Jacó tinham trazido do Egito, seu pai lhes disse: "Voltem e comprem um pouco mais de comida para nós".

[[v1-43-3]]

^<<v1-43-3,3>>^ Mas Judá lhe disse: "O homem nos advertiu severamente: ‘Não voltem à minha presença, a não ser que tragam o seu irmão’.

[[v1-43-4]]

^<<v1-43-4,4>>^ Se enviares o nosso irmão conosco, desceremos e compraremos comida para ti.

[[v1-43-5]]

^<<v1-43-5,5>>^ Mas se não o enviares conosco, não iremos, porque foi assim que o homem falou: ‘Não voltem à minha presença, a não ser que tragam o seu irmão’ ".

[[v1-43-6]]

^<<v1-43-6,6>>^ Israel perguntou: "Por que me causaram esse mal, contando àquele homem que tinham outro irmão? "

[[v1-43-7]]

^<<v1-43-7,7>>^ E lhe responderam: "Ele nos interrogou sobre nós e sobre nossa família. E também nos perguntou: ‘O pai de vocês ainda está vivo? Vocês têm outro irmão? ’ Nós simplesmente respondemos ao que ele nos perguntou. Como poderíamos saber que ele exigiria que levássemos o nosso irmão? "

[[v1-43-8]]

^<<v1-43-8,8>>^ Então disse Judá a Israel, seu pai: "Deixa o jovem ir comigo e partiremos imediatamente, a fim de que tu, nós e nossas crianças sobrevivamos e não venhamos a morrer.

[[v1-43-9]]

^<<v1-43-9,9>>^ Eu me comprometo pessoalmente pela segurança dele; podes me considerar responsável por ele. Se eu não o trouxer de volta e não o colocar bem aqui na tua presença, serei culpado diante de ti pelo resto da minha vida.

[[v1-43-10]]

^<<v1-43-10,10>>^ Como se vê, se não tivéssemos demorado tanto, já teríamos ido e voltado duas vezes".

[[v1-43-11]]

^<<v1-43-11,11>>^ Então Israel, seu pai, lhes disse: "Se tem que ser assim, que seja! Coloquem alguns dos melhores produtos da nossa terra na bagagem e levem-nos como presente ao tal homem: um pouco de bálsamo, um pouco de mel, algumas especiarias e mirra, algumas nozes de pistache e amêndoas.

[[v1-43-12]]

^<<v1-43-12,12>>^ Levem prata em dobro, e devolvam a prata que foi colocada de volta na boca da bagagem de vocês. Talvez isso tenha acontecido por engano.

[[v1-43-13]]

^<<v1-43-13,13>>^ Peguem também o seu irmão e voltem àquele homem.

[[v1-43-14]]

^<<v1-43-14,14>>^ Que o Deus Todo-poderoso lhes conceda misericórdia diante daquele homem, para que ele permita que o seu outro irmão e Benjamim voltem com vocês. Quanto a mim, se ficar sem filhos, sem filhos ficarei".

[[v1-43-15]]

^<<v1-43-15,15>>^ Então os homens desceram ao Egito, levando o presente, prata em dobro e Benjamim, e foram à presença de José.

[[v1-43-16]]

^<<v1-43-16,16>>^ Quando José viu Benjamim junto com eles, disse ao administrador de sua casa: "Leve estes homens à minha casa, mate um animal e prepare-o; eles almoçarão comigo ao meio-dia".

[[v1-43-17]]

^<<v1-43-17,17>>^ Ele fez o que lhe fora ordenado e levou-os à casa de José.

[[v1-43-18]]

^<<v1-43-18,18>>^ Eles ficaram com medo quando foram levados à casa de José, e pensaram: "Trouxeram-nos aqui por causa da prata que foi devolvida às nossas bagagens na primeira vez. Ele quer atacar-nos, subjugar-nos, tornar-nos escravos e tomar de nós os nossos jumentos".

[[v1-43-19]]

^<<v1-43-19,19>>^ Por isso, dirigiram-se ao administrador da casa de José e lhe disseram à entrada da casa:

[[v1-43-20]]

^<<v1-43-20,20>>^ "Ouça, senhor! A primeira vez que viemos aqui foi realmente para comprar comida.

[[v1-43-21]]

^<<v1-43-21,21>>^ Mas no lugar em que paramos para pernoitar, abrimos nossas bagagens e cada um de nós encontrou sua prata, na quantia exata. Por isso a trouxemos de volta conosco,

[[v1-43-22]]

^<<v1-43-22,22>>^ além de mais prata, para comprar comida. Não sabemos quem pôs a prata em nossa bagagem".

[[v1-43-23]]

^<<v1-43-23,23>>^ "Fiquem tranqüilos", disse o administrador. "Não tenham medo. O seu Deus, o Deus de seu pai, foi quem lhes deu um tesouro em suas bagagens, porque a prata de vocês eu recebi. " Então soltou Simeão e o levou à presença deles.

[[v1-43-24]]

^<<v1-43-24,24>>^ Em seguida os levou à casa de José, deu-lhes água para lavarem os pés e forragem para os seus jumentos.

[[v1-43-25]]

^<<v1-43-25,25>>^ Eles então prepararam o presente para a chegada de José ao meio-dia, porque ficaram sabendo que iriam almoçar ali.

[[v1-43-26]]

^<<v1-43-26,26>>^ Quando José chegou, eles o presentearam com o que tinham trazido e curvaram-se diante dele até o chão.

[[v1-43-27]]

^<<v1-43-27,27>>^ Ele então lhes perguntou como passavam e disse em seguida: "Como vai o pai de vocês, o homem idoso de quem me falaram? Ainda está vivo? "

[[v1-43-28]]

^<<v1-43-28,28>>^ Eles responderam: "Teu servo, nosso pai, ainda vive e passa bem". E se curvaram para prestar-lhe honra.

[[v1-43-29]]

^<<v1-43-29,29>>^ Olhando ao redor e vendo seu irmão Benjamim, filho de sua mãe, José perguntou: "É este o irmão caçula de quem me falaram? " E acrescentou: "Deus lhe conceda graça, meu filho".

[[v1-43-30]]

^<<v1-43-30,30>>^ Profundamente emocionado por causa de seu irmão, José apressou-se em sair à procura de um lugar para chorar, e entrando em seu quarto, chorou.

[[v1-43-31]]

^<<v1-43-31,31>>^ Depois de lavar o rosto, saiu e, controlando-se, disse: "Sirvam a comida".

[[v1-43-32]]

^<<v1-43-32,32>>^ Serviram a ele em separado dos seus irmãos e também dos egípcios que comiam com ele, porque os egípcios não podiam comer com os hebreus, pois isso era sacrilégio para eles.

[[v1-43-33]]

^<<v1-43-33,33>>^ Seus irmãos foram colocados à mesa perante ele por ordem de idade, do mais velho ao mais moço, e olhavam perplexos uns para os outros.

[[v1-43-34]]

^<<v1-43-34,34>>^ Então lhes serviram da comida da mesa de José, e a porção de Benjamim era cinco vezes maior que a dos outros. E eles festejaram e beberam à vontade.

'''

xref:001-genesis/001-genesis-042.adoc#v1-42-0[&#60; Capítulo Anterior] | <<v1-43-0,Topo>> | xref:001-genesis/001-genesis-044.adoc#v1-44-0[Próximo Capítulo &#62;]