include::./index.adoc[]

[[v1-49-0]]
=== Gênesis, 49
// nvi ?, NVI - Nova Versão Internacional

[[v1-49-1]]

^<<v1-49-1,1>>^ Então Jacó chamou seus filhos e disse: "Ajuntem-se a meu lado para que eu lhes diga o que lhes acontecerá nos dias que virão.

[[v1-49-2]]

^<<v1-49-2,2>>^ "Reúnam-se para ouvir, filhos de Jacó; ouçam o que diz seu pai Israel.

[[v1-49-3]]

^<<v1-49-3,3>>^ "Rúben, você é meu primogênito, minha força, o primeiro sinal do meu vigor, superior em honra, superior em poder.

[[v1-49-4]]

^<<v1-49-4,4>>^ Turbulento como as águas, já não será superior, porque você subiu à cama de seu pai, ao meu leito, e o desonrou.

[[v1-49-5]]

^<<v1-49-5,5>>^ "Simeão e Levi são irmãos; suas espadas são armas de violência.

[[v1-49-6]]

^<<v1-49-6,6>>^ Que eu não entre no conselho deles, nem participe da sua assembléia, porque em sua ira mataram homens e a bel-prazer aleijaram bois, cortando-lhes o tendão.

[[v1-49-7]]

^<<v1-49-7,7>>^ Maldita seja a sua ira, tão tremenda, e a sua fúria, tão cruel! Eu os dividirei pelas terras de Jacó e os dispersarei em Israel.

[[v1-49-8]]

^<<v1-49-8,8>>^ "Judá, seus irmãos o louvarão, sua mão estará sobre o pescoço dos seus inimigos; os filhos de seu pai se curvarão diante de você.

[[v1-49-9]]

^<<v1-49-9,9>>^ Judá é um leão novo. Você vem subindo, filho meu, depois de matar a presa. Como um leão, ele se assenta; e deita-se como uma leoa; quem tem coragem de acordá-lo?

[[v1-49-10]]

^<<v1-49-10,10>>^ O cetro não se apartará de Judá, nem o bastão de comando de seus descendentes, até que venha aquele a quem ele pertence, e a ele as nações obedecerão.

[[v1-49-11]]

^<<v1-49-11,11>>^ Ele amarrará seu jumento a uma videira e o seu jumentinho, ao ramo mais seleto; lavará no vinho as suas roupas, no sangue das uvas, as suas vestimentas.

[[v1-49-12]]

^<<v1-49-12,12>>^ Seus olhos serão mais escuros que o vinho; seus dentes, mais brancos que o leite.

[[v1-49-13]]

^<<v1-49-13,13>>^ "Zebulom morará à beira-mar e se tornará um porto para os navios; suas fronteiras se estenderão até Sidom.

[[v1-49-14]]

^<<v1-49-14,14>>^ "Issacar é um jumento forte, deitado entre as suas cargas.

[[v1-49-15]]

^<<v1-49-15,15>>^ Quando ele perceber como é bom o seu lugar de repouso e como é aprazível a sua terra, curvará seus ombros ao fardo e se submeterá a trabalhos forçados.

[[v1-49-16]]

^<<v1-49-16,16>>^ "Dã defenderá o direito do seu povo como qualquer das tribos de Israel.

[[v1-49-17]]

^<<v1-49-17,17>>^ Dã será uma serpente à beira da estrada, uma víbora à margem do caminho, que morde o calcanhar do cavalo e faz cair de costas o seu cavaleiro.

[[v1-49-18]]

^<<v1-49-18,18>>^ "Ó Senhor, eu espero a tua libertação!

[[v1-49-19]]

^<<v1-49-19,19>>^ "Gade será atacado por um bando, mas é ele que o atacará e o perseguirá.

[[v1-49-20]]

^<<v1-49-20,20>>^ "A mesa de Aser será farta; ele oferecerá manjares de rei.

[[v1-49-21]]

^<<v1-49-21,21>>^ "Naftali é uma gazela solta, que por isso faz festa.

[[v1-49-22]]

^<<v1-49-22,22>>^ "José é uma árvore frutífera, árvore frutífera à beira de uma fonte, cujos galhos passam por cima do muro.

[[v1-49-23]]

^<<v1-49-23,23>>^ Com rancor arqueiros o atacaram, atirando-lhe flechas com hostilidade.

[[v1-49-24]]

^<<v1-49-24,24>>^ Mas o seu arco permaneceu firme, os seus braços fortes, ágeis para atirar, pela mão do Poderoso de Jacó, pelo nome do Pastor, a Rocha de Israel,

[[v1-49-25]]

^<<v1-49-25,25>>^ pelo Deus de seu pai, que ajuda você, o Todo-poderoso, que o abençoa com bênçãos dos altos céus, bênçãos das profundezas, bênçãos da fertilidade e da fartura.

[[v1-49-26]]

^<<v1-49-26,26>>^ As bênçãos de seu pai são superiores às bênçãos dos montes antigos, às delícias das colinas eternas. Que todas essas bênçãos repousem sobre a cabeça de José, sobre a fronte daquele que foi separado de entre os seus irmãos.

[[v1-49-27]]

^<<v1-49-27,27>>^ "Benjamim é um lobo predador; pela manhã devora a presa e à tarde divide o despojo".

[[v1-49-28]]

^<<v1-49-28,28>>^ São esses os que formaram as doze tribos de Israel, e foi isso que seu pai lhes disse, ao abençoá-los, dando a cada um a bênção que lhe pertencia.

[[v1-49-29]]

^<<v1-49-29,29>>^ A seguir, Jacó deu-lhes estas instruções: "Estou para ser reunido aos meus antepassados. Sepultem-me junto aos meus pais na caverna do campo de Efrom, o hitita,

[[v1-49-30]]

^<<v1-49-30,30>>^ na caverna do campo de Macpela, perto de Manre, em Canaã, campo que Abraão comprou de Efrom, o hitita, como propriedade para sepultura.

[[v1-49-31]]

^<<v1-49-31,31>>^ Ali foram sepultados Abraão e Sara, sua mulher, e Isaque e Rebeca, sua mulher; ali também sepultei Lia.

[[v1-49-32]]

^<<v1-49-32,32>>^ "Tanto o campo como a caverna que nele está foram comprados dos hititas. "

[[v1-49-33]]

^<<v1-49-33,33>>^ Ao acabar de dar essas instruções a seus filhos, Jacó deitou-se, expirou e foi reunido aos seus antepassados.

'''

xref:001-genesis/001-genesis-048.adoc#v1-48-0[&#60; Capítulo Anterior] | <<v1-49-0,Topo>> | xref:001-genesis/001-genesis-050.adoc#v1-50-0[Próximo Capítulo &#62;]