include::./index.adoc[]

[[v1-35-0]]
=== Gênesis, 35
// nvi ?, NVI - Nova Versão Internacional

[[v1-35-1]]

^<<v1-35-1,1>>^ Deus disse a Jacó: "Suba a Betel e se estabeleça lá, e faça um altar ao Deus que lhe apareceu quando você fugia do seu irmão Esaú".

[[v1-35-2]]

^<<v1-35-2,2>>^ Disse, pois, Jacó aos de sua casa e a todos os que estavam com ele: "Livrem-se dos deuses estrangeiros que estão entre vocês, purifiquem-se e troquem de roupa.

[[v1-35-3]]

^<<v1-35-3,3>>^ Venham! Vamos subir a Betel, onde farei um altar ao Deus que me ouviu no dia da minha angústia e que tem estado comigo por onde tenho andado".

[[v1-35-4]]

^<<v1-35-4,4>>^ Então entregaram a Jacó todos os deuses estrangeiros que possuíam e os brincos que usavam nas orelhas, e Jacó os enterrou ao pé da grande árvore, próximo a Siquém.

[[v1-35-5]]

^<<v1-35-5,5>>^ Quando eles partiram, o terror de Deus caiu de tal maneira sobre as cidades ao redor que ninguém ousou perseguir os filhos de Jacó.

[[v1-35-6]]

^<<v1-35-6,6>>^ Jacó e todos os que com ele estavam chegaram a Luz, que é Betel, na terra de Canaã.

[[v1-35-7]]

^<<v1-35-7,7>>^ Nesse lugar construiu um altar e lhe deu o nome de El-Betel, porque ali Deus havia se revelado a ele, quando fugia do seu irmão.

[[v1-35-8]]

^<<v1-35-8,8>>^ Débora, ama de Rebeca, morreu e foi sepultada perto de Betel, ao pé do Carvalho, que por isso foi chamado Alom-Bacute.

[[v1-35-9]]

^<<v1-35-9,9>>^ Depois que Jacó retornou de Padã-Arã, Deus lhe apareceu de novo e o abençoou,

[[v1-35-10]]

^<<v1-35-10,10>>^ dizendo: "Seu nome é Jacó, mas você não será mais chamado Jacó; seu nome será Israel". Assim lhe deu o nome de Israel.

[[v1-35-11]]

^<<v1-35-11,11>>^ E Deus ainda lhe disse: "Eu sou o Deus Todo-poderoso; seja prolífero e multiplique-se. De você procederão uma nação e uma comunidade de nações, e reis estarão entre os seus descendentes.

[[v1-35-12]]

^<<v1-35-12,12>>^ A terra que dei a Abraão e a Isaque, dou a você; e também aos seus futuros descendentes darei esta terra".

[[v1-35-13]]

^<<v1-35-13,13>>^ A seguir, Deus elevou-se do lugar onde estivera falando com Jacó.

[[v1-35-14]]

^<<v1-35-14,14>>^ Jacó levantou uma coluna de pedra no lugar em que Deus lhe falara, e derramou sobre ela uma oferta de bebidas e a ungiu com óleo.

[[v1-35-15]]

^<<v1-35-15,15>>^ Jacó deu o nome de Betel ao lugar onde Deus tinha falado com ele.

[[v1-35-16]]

^<<v1-35-16,16>>^ Eles partiram de Betel, e quando ainda estavam a certa distância de Efrata, Raquel começou a dar à luz com grande dificuldade.

[[v1-35-17]]

^<<v1-35-17,17>>^ E, enquanto padecia muito, tentando dar à luz, a parteira lhe disse: "Não tenha medo, pois você ainda terá outro menino".

[[v1-35-18]]

^<<v1-35-18,18>>^ Já ao ponto de sair-lhe a vida, quando estava morrendo, deu ao filho o nome de Benoni. Mas o pai deu-lhe o nome de Benjamim.

[[v1-35-19]]

^<<v1-35-19,19>>^ Assim morreu Raquel e foi sepultada junto do caminho de Efrata, que é Belém.

[[v1-35-20]]

^<<v1-35-20,20>>^ Sobre a sua sepultura Jacó levantou uma coluna, e até o dia de hoje aquela coluna marca o túmulo de Raquel.

[[v1-35-21]]

^<<v1-35-21,21>>^ Israel partiu novamente e armou acampamento adiante de Migdal-Éder.

[[v1-35-22]]

^<<v1-35-22,22>>^ Na época em que Israel vivia naquela região, Rúben deitou-se com Bila, concubina de seu pai. E Israel ficou sabendo disso. Jacó teve doze filhos:

[[v1-35-23]]

^<<v1-35-23,23>>^ Estes foram seus filhos com Lia: Rúben, o filho mais velho de Jacó, Simeão, Levi, Judá, Issacar e Zebulom.

[[v1-35-24]]

^<<v1-35-24,24>>^ Estes foram seus filhos com Raquel: José e Benjamim.

[[v1-35-25]]

^<<v1-35-25,25>>^ Estes foram seus filhos com Bila, serva de Raquel: Dã e Naftali.

[[v1-35-26]]

^<<v1-35-26,26>>^ Estes foram seus filhos com Zilpa, serva de Lia: Gade e Aser. Foram esses os filhos de Jacó, nascidos em Padã-Arã.

[[v1-35-27]]

^<<v1-35-27,27>>^ Depois Jacó foi visitar seu pai Isaque em Manre, perto de Quiriate-Arba, que é Hebrom, onde Abraão e Isaque tinham morado.

[[v1-35-28]]

^<<v1-35-28,28>>^ Isaque viveu cento e oitenta anos.

[[v1-35-29]]

^<<v1-35-29,29>>^ Morreu em idade bem avançada e foi reunido aos seus antepassados. E seus filhos Esaú e Jacó o sepultaram.

'''

xref:001-genesis/001-genesis-034.adoc#v1-34-0[&#60; Capítulo Anterior] | <<v1-35-0,Topo>> | xref:001-genesis/001-genesis-036.adoc#v1-36-0[Próximo Capítulo &#62;]