include::./index.adoc[]

[[v1-17-0]]
=== Gênesis, 17
// nvi ?, NVI - Nova Versão Internacional

[[v1-17-1]]

^<<v1-17-1,1>>^ Quando Abrão estava com noventa e nove anos de idade o Senhor lhe apareceu e disse: "Eu sou o Deus Todo-poderoso; ande segundo a minha vontade e seja íntegro.

[[v1-17-2]]

^<<v1-17-2,2>>^ Estabelecerei a minha aliança entre mim e você e multiplicarei muitíssimo a sua descendência".

[[v1-17-3]]

^<<v1-17-3,3>>^ Abrão prostrou-se, rosto em terra, e Deus lhe disse:

[[v1-17-4]]

^<<v1-17-4,4>>^ "De minha parte, esta é a minha aliança com você. Você será o pai de muitas nações.

[[v1-17-5]]

^<<v1-17-5,5>>^ Não será mais chamado Abrão; seu nome será Abraão, porque eu o constituí pai de muitas nações.

[[v1-17-6]]

^<<v1-17-6,6>>^ Eu o tornarei extremamente prolífero; de você farei nações e de você procederão reis.

[[v1-17-7]]

^<<v1-17-7,7>>^ Estabelecerei a minha aliança como aliança eterna entre mim e você e os seus futuros descendentes, para ser o seu Deus e o Deus dos seus descendentes.

[[v1-17-8]]

^<<v1-17-8,8>>^ Toda a terra de Canaã, onde agora você é estrangeiro, darei como propriedade perpétua a você e a seus descendentes; e serei o Deus deles.

[[v1-17-9]]

^<<v1-17-9,9>>^ "De sua parte", disse Deus a Abraão, "guarde a minha aliança, tanto você como os seus futuros descendentes.

[[v1-17-10]]

^<<v1-17-10,10>>^ Esta é a minha aliança com você e com os seus descendentes, aliança que terá que ser guardada: Todos os do sexo masculino entre vocês serão circuncidados na carne.

[[v1-17-11]]

^<<v1-17-11,11>>^ Terão que fazer essa marca, que será o sinal da aliança entre mim e vocês.

[[v1-17-12]]

^<<v1-17-12,12>>^ Da sua geração em diante, todo menino de oito dias de idade entre vocês terá que ser circuncidado, tanto os nascidos em sua casa quanto os que forem comprados de estrangeiros e que não forem descendentes de vocês.

[[v1-17-13]]

^<<v1-17-13,13>>^ Sejam nascidos em sua casa, sejam comprados, terão que ser circuncidados. Minha aliança, marcada no corpo de vocês, será uma aliança perpétua.

[[v1-17-14]]

^<<v1-17-14,14>>^ Qualquer do sexo masculino que for incircunciso, que não tiver sido circuncidado, será eliminado do meio do seu povo; quebrou a minha aliança".

[[v1-17-15]]

^<<v1-17-15,15>>^ Disse também Deus a Abraão: "De agora em diante sua mulher já não se chamará Sarai; seu nome será Sara.

[[v1-17-16]]

^<<v1-17-16,16>>^ Eu a abençoarei e também por meio dela darei a você um filho. Sim, eu a abençoarei e dela procederão nações e reis de povos".

[[v1-17-17]]

^<<v1-17-17,17>>^ Abraão prostrou-se, rosto em terra; riu-se e disse a si mesmo: "Poderá um homem de cem anos de idade gerar filhos? Poderá Sara dar à luz aos noventa anos? "

[[v1-17-18]]

^<<v1-17-18,18>>^ E Abraão disse a Deus: "Permite que Ismael seja o meu herdeiro! "

[[v1-17-19]]

^<<v1-17-19,19>>^ Então Deus respondeu: "Na verdade Sara, sua mulher, lhe dará um filho, e você lhe chamará Isaque. Com ele estabelecerei a minha aliança, que será aliança eterna para os seus futuros descendentes.

[[v1-17-20]]

^<<v1-17-20,20>>^ E no caso de Ismael, levarei em conta o seu pedido. Também o abençoarei; eu o farei prolífero e multiplicarei muito a sua descendência. Ele será pai de doze príncipes e dele farei um grande povo.

[[v1-17-21]]

^<<v1-17-21,21>>^ Mas a minha aliança, eu a estabelecerei com Isaque, filho que Sara lhe dará no ano que vem, por esta época".

[[v1-17-22]]

^<<v1-17-22,22>>^ Quando terminou de falar com Abraão, Deus subiu e retirou-se da presença dele.

[[v1-17-23]]

^<<v1-17-23,23>>^ Naquele mesmo dia Abraão tomou seu filho Ismael, todos os nascidos em sua casa e os que foram comprados, todos os do sexo masculino de sua casa, e os circuncidou, como Deus lhe ordenara.

[[v1-17-24]]

^<<v1-17-24,24>>^ Abraão tinha noventa e nove anos quando foi circuncidado,

[[v1-17-25]]

^<<v1-17-25,25>>^ e seu filho Ismael tinha treze;

[[v1-17-26]]

^<<v1-17-26,26>>^ Abraão e seu filho Ismael foram circuncidados naquele mesmo dia.

[[v1-17-27]]

^<<v1-17-27,27>>^ E com ele foram circuncidados todos os de sua casa, tanto os nascidos em casa como os comprados de estrangeiros.

'''

xref:001-genesis/001-genesis-016.adoc#v1-16-0[&#60; Capítulo Anterior] | <<v1-17-0,Topo>> | xref:001-genesis/001-genesis-018.adoc#v1-18-0[Próximo Capítulo &#62;]