include::./index.adoc[]

[[v1-4-0]]
=== Gênesis, 4
// nvi ?, NVI - Nova Versão Internacional

[[v1-4-1]]

^<<v1-4-1,1>>^ Adão teve relações com Eva, sua mulher, e ela engravidou e deu à luz Caim. Disse ela: "Com o auxílio do Senhor tive um filho homem".

[[v1-4-2]]

^<<v1-4-2,2>>^ Voltou a dar à luz, desta vez a Abel, irmão dele. Abel tornou-se pastor de ovelhas, e Caim, agricultor.

[[v1-4-3]]

^<<v1-4-3,3>>^ Passado algum tempo, Caim trouxe do fruto da terra uma oferta ao Senhor.

[[v1-4-4]]

^<<v1-4-4,4>>^ Abel, por sua vez, trouxe as partes gordas das primeiras crias do seu rebanho. O Senhor aceitou com agrado Abel e sua oferta,

[[v1-4-5]]

^<<v1-4-5,5>>^ mas não aceitou Caim e sua oferta. Por isso Caim se enfureceu e o seu rosto se transtornou.

[[v1-4-6]]

^<<v1-4-6,6>>^ O Senhor disse a Caim: "Por que você está furioso? Por que se transtornou o seu rosto?

[[v1-4-7]]

^<<v1-4-7,7>>^ Se você fizer o bem, não será aceito? Mas se não o fizer, saiba que o pecado o ameaça à porta; ele deseja conquistá-lo, mas você deve dominá-lo".

[[v1-4-8]]

^<<v1-4-8,8>>^ Disse, porém, Caim a seu irmão Abel: "Vamos para o campo". Quando estavam lá, Caim atacou seu irmão Abel e o matou.

[[v1-4-9]]

^<<v1-4-9,9>>^ Então o Senhor perguntou a Caim: "Onde está seu irmão Abel? " Respondeu ele: "Não sei; sou eu o responsável por meu irmão? "

[[v1-4-10]]

^<<v1-4-10,10>>^ Disse o Senhor: "O que foi que você fez? Escute! Da terra o sangue do seu irmão está clamando.

[[v1-4-11]]

^<<v1-4-11,11>>^ Agora amaldiçoado é você pela terra, que abriu a boca para receber da sua mão o sangue do seu irmão.

[[v1-4-12]]

^<<v1-4-12,12>>^ Quando você cultivar a terra, esta não lhe dará mais da sua força. Você será um fugitivo errante pelo mundo".

[[v1-4-13]]

^<<v1-4-13,13>>^ Disse Caim ao Senhor: "Meu castigo é maior do que posso suportar.

[[v1-4-14]]

^<<v1-4-14,14>>^ Hoje me expulsas desta terra, e terei que me esconder da tua face; serei um fugitivo errante pelo mundo, e qualquer que me encontrar me matará".

[[v1-4-15]]

^<<v1-4-15,15>>^ Mas o Senhor lhe respondeu: "Não será assim; se alguém matar Caim, sofrerá sete vezes a vingança". E o Senhor colocou em Caim um sinal, para que ninguém que viesse a encontrá-lo o matasse.

[[v1-4-16]]

^<<v1-4-16,16>>^ Então Caim afastou-se da presença do Senhor e foi viver na terra de Node, a leste do Éden.

[[v1-4-17]]

^<<v1-4-17,17>>^ Caim teve relações com sua mulher, e ela engravidou e deu à luz Enoque. Depois Caim fundou uma cidade, à qual deu o nome do seu filho Enoque.

[[v1-4-18]]

^<<v1-4-18,18>>^ A Enoque nasceu-lhe Irade, Irade gerou a Meujael, Meujael a Metusael, e Metusael a Lameque.

[[v1-4-19]]

^<<v1-4-19,19>>^ Lameque tomou duas mulheres: uma chamava-se Ada e a outra, Zilá.

[[v1-4-20]]

^<<v1-4-20,20>>^ Ada deu à luz Jabal, que foi o pai daqueles que moram em tendas e criam rebanhos.

[[v1-4-21]]

^<<v1-4-21,21>>^ O nome do irmão dele era Jubal, que foi o pai de todos os que tocam harpa e flauta.

[[v1-4-22]]

^<<v1-4-22,22>>^ Zilá também deu à luz um filho, Tubalcaim, que fabricava todo tipo de ferramentas de bronze e de ferro. Tubalcaim teve uma irmã chamada Naamá.

[[v1-4-23]]

^<<v1-4-23,23>>^ Disse Lameque às suas mulheres: "Ada e Zilá, ouçam-me; mulheres de Lameque, escutem minhas palavras: Eu matei um homem porque me feriu, e um menino, porque me machucou.

[[v1-4-24]]

^<<v1-4-24,24>>^ Se Caim é vingado sete vezes, Lameque o será setenta e sete".

[[v1-4-25]]

^<<v1-4-25,25>>^ Novamente Adão teve relações com sua mulher, e ela deu à luz outro filho, a quem chamou Sete, dizendo: "Deus me concedeu um filho no lugar de Abel, visto que Caim o matou".

[[v1-4-26]]

^<<v1-4-26,26>>^ Também a Sete nasceu um filho, a quem deu o nome de Enos. Nessa época começou-se a invocar o nome do Senhor.

'''

xref:001-genesis/001-genesis-003.adoc#v1-3-0[&#60; Capítulo Anterior] | <<v1-4-0,Topo>> | xref:001-genesis/001-genesis-005.adoc#v1-5-0[Próximo Capítulo &#62;]