include::./index.adoc[]

[[v1-23-0]]
=== Gênesis, 23
// nvi ?, NVI - Nova Versão Internacional

[[v1-23-1]]

^<<v1-23-1,1>>^ Sara viveu cento e vinte e sete anos

[[v1-23-2]]

^<<v1-23-2,2>>^ e morreu em Quiriate-Arba, que é Hebrom, em Canaã; e Abraão foi lamentar e chorar por ela.

[[v1-23-3]]

^<<v1-23-3,3>>^ Depois Abraão deixou ali o corpo de sua mulher e foi falar com os hititas:

[[v1-23-4]]

^<<v1-23-4,4>>^ "Sou apenas um estrangeiro entre vocês. Cedam-me alguma propriedade para sepultura, para que eu tenha onde enterrar a minha mulher".

[[v1-23-5]]

^<<v1-23-5,5>>^ Responderam os hititas a Abraão:

[[v1-23-6]]

^<<v1-23-6,6>>^ "Ouça-nos, senhor; o senhor é um príncipe de Deus em nosso meio. Enterre a sua mulher numa de nossas sepulturas, na que lhe parecer melhor. Nenhum de nós recusará ceder-lhe sua sepultura para que enterre a sua mulher".

[[v1-23-7]]

^<<v1-23-7,7>>^ Abraão levantou-se, curvou-se perante o povo daquela terra, os hititas,

[[v1-23-8]]

^<<v1-23-8,8>>^ e disse-lhes: "Já que vocês me dão permissão para sepultar minha mulher, peço que intercedam por mim junto a Efrom, filho de Zoar,

[[v1-23-9]]

^<<v1-23-9,9>>^ a fim de que ele me ceda a caverna de Macpela, que lhe pertence e se encontra na divisa do seu campo. Peçam-lhe que a ceda a mim pelo preço justo, para que eu tenha uma propriedade para sepultura entre vocês".

[[v1-23-10]]

^<<v1-23-10,10>>^ Efrom, o hitita, estava sentado no meio do seu povo e respondeu a Abraão, sendo ouvido por todos os hititas que tinham vindo à porta da cidade:

[[v1-23-11]]

^<<v1-23-11,11>>^ "Não, meu senhor. Ouça-me, eu lhe cedo o campo e também a caverna que nele está. Cedo-os na presença do meu povo. Sepulte a sua mulher".

[[v1-23-12]]

^<<v1-23-12,12>>^ Novamente Abraão curvou-se perante o povo daquela terra

[[v1-23-13]]

^<<v1-23-13,13>>^ e disse a Efrom, sendo ouvido por todos: "Ouça-me, por favor. Pagarei o preço do campo. Aceite-o, para que eu possa sepultar a minha mulher".

[[v1-23-14]]

^<<v1-23-14,14>>^ Efrom respondeu a Abraão:

[[v1-23-15]]

^<<v1-23-15,15>>^ "Ouça-me, meu senhor: aquele pedaço de terra vale quatrocentas peças de prata, mas o que significa isso entre mim e você? Sepulte a sua mulher".

[[v1-23-16]]

^<<v1-23-16,16>>^ Abraão concordou com Efrom e pesou-lhe o valor por ele estipulado diante dos hititas: quatrocentas peças de prata, de acordo com o peso corrente entre os mercadores.

[[v1-23-17]]

^<<v1-23-17,17>>^ Assim o campo de Efrom em Macpela, perto de Manre, o próprio campo com a caverna que nele há e todas as árvores dentro das divisas do campo, foi transferido

[[v1-23-18]]

^<<v1-23-18,18>>^ a Abraão como sua propriedade diante de todos os hititas que tinham vindo à porta da cidade.

[[v1-23-19]]

^<<v1-23-19,19>>^ Depois disso, Abraão sepultou sua mulher Sara na caverna do campo de Macpela, perto de Manre, que se encontra em Hebrom, na terra de Canaã.

[[v1-23-20]]

^<<v1-23-20,20>>^ Assim o campo e a caverna que nele há foram transferidos a Abraão pelos hititas como propriedade para sepultura.

'''

xref:001-genesis/001-genesis-022.adoc#v1-22-0[&#60; Capítulo Anterior] | <<v1-23-0,Topo>> | xref:001-genesis/001-genesis-024.adoc#v1-24-0[Próximo Capítulo &#62;]