include::./index.adoc[]

[[v1-15-0]]
=== Gênesis, 15
// nvi ?, NVI - Nova Versão Internacional

[[v1-15-1]]

^<<v1-15-1,1>>^ Depois dessas coisas o Senhor falou a Abrão numa visão: "Não tenha medo, Abrão! Eu sou o seu escudo; grande será a sua recompensa! "

[[v1-15-2]]

^<<v1-15-2,2>>^ Mas Abrão perguntou: "Ó Soberano Senhor, que me darás, se continuo sem filhos e o herdeiro do que possuo é Eliézer de Damasco? "

[[v1-15-3]]

^<<v1-15-3,3>>^ E acrescentou: "Tu não me deste filho algum! Um servo da minha casa será o meu herdeiro! "

[[v1-15-4]]

^<<v1-15-4,4>>^ Então o Senhor deu-lhe a seguinte resposta: "Seu herdeiro não será esse. Um filho gerado por você mesmo será o seu herdeiro".

[[v1-15-5]]

^<<v1-15-5,5>>^ Levando-o para fora da tenda, disse-lhe: "Olhe para o céu e conte as estrelas, se é que pode contá-las". E prosseguiu: "Assim será a sua descendência".

[[v1-15-6]]

^<<v1-15-6,6>>^ Abrão creu no Senhor, e isso lhe foi creditado como justiça.

[[v1-15-7]]

^<<v1-15-7,7>>^ Disse-lhe ainda: "Eu sou o Senhor, que o tirei de Ur dos caldeus para dar-lhe esta terra como herança".

[[v1-15-8]]

^<<v1-15-8,8>>^ Perguntou-lhe Abrão: "Ó Soberano Senhor, como posso saber que tomarei posse dela? "

[[v1-15-9]]

^<<v1-15-9,9>>^ Respondeu-lhe o Senhor: "Traga-me uma novilha, uma cabra e um carneiro, todos com três anos de vida, e também uma rolinha e um pombinho".

[[v1-15-10]]

^<<v1-15-10,10>>^ Abrão trouxe todos esses animais, cortou-os ao meio e colocou cada metade em frente à outra; as aves, porém, ele não cortou.

[[v1-15-11]]

^<<v1-15-11,11>>^ Nisso, aves de rapina começaram a descer sobre os cadáveres, mas Abrão as enxotava.

[[v1-15-12]]

^<<v1-15-12,12>>^ Ao pôr-do-sol, Abrão foi tomado de sono profundo, e eis que vieram sobre ele trevas densas e apavorantes.

[[v1-15-13]]

^<<v1-15-13,13>>^ Então o Senhor lhe disse: "Saiba que os seus descendentes serão estrangeiros numa terra que não lhes pertencerá, onde também serão escravizados e oprimidos por quatrocentos anos.

[[v1-15-14]]

^<<v1-15-14,14>>^ Mas eu castigarei a nação a quem servirão como escravos e, depois de tudo, sairão com muitos bens.

[[v1-15-15]]

^<<v1-15-15,15>>^ Você, porém, irá em paz a seus antepassados e será sepultado em boa velhice.

[[v1-15-16]]

^<<v1-15-16,16>>^ Na quarta geração, os seus descendentes voltarão para cá, porque a maldade dos amorreus ainda não atingiu a medida completa".

[[v1-15-17]]

^<<v1-15-17,17>>^ Depois que o sol se pôs e veio a escuridão, eis que um fogareiro esfumaçante, com uma tocha acesa, passou por entre os pedaços dos animais.

[[v1-15-18]]

^<<v1-15-18,18>>^ Naquele dia o Senhor fez a seguinte aliança com Abrão: "Aos seus descendentes dei esta terra, desde o ribeiro do Egito até o grande rio, o Eufrates:

[[v1-15-19]]

^<<v1-15-19,19>>^ a terra dos queneus, dos quenezeus, dos cadmoneus,

[[v1-15-20]]

^<<v1-15-20,20>>^ dos hititas, dos ferezeus, dos refains,

[[v1-15-21]]

^<<v1-15-21,21>>^ dos amorreus, dos cananeus, dos girgaseus e dos jebuseus".

'''

xref:001-genesis/001-genesis-014.adoc#v1-14-0[&#60; Capítulo Anterior] | <<v1-15-0,Topo>> | xref:001-genesis/001-genesis-016.adoc#v1-16-0[Próximo Capítulo &#62;]