include::./index.adoc[]

[[v1-37-0]]
=== Gênesis, 37
// nvi ?, NVI - Nova Versão Internacional

[[v1-37-1]]

^<<v1-37-1,1>>^ Jacó habitou na terra de Canaã, onde seu pai tinha vivido como estrangeiro.

[[v1-37-2]]

^<<v1-37-2,2>>^ Esta é a história da família de Jacó: Quando José tinha dezessete anos, pastoreava os rebanhos com os seus irmãos. Ajudava os filhos de Bila e os filhos de Zilpa, mulheres de seu pai; e contava ao pai a má fama deles.

[[v1-37-3]]

^<<v1-37-3,3>>^ Ora, Israel gostava mais de José do que de qualquer outro filho, porque lhe havia nascido em sua velhice; por isso mandou fazer para ele uma túnica longa.

[[v1-37-4]]

^<<v1-37-4,4>>^ Quando os seus irmãos viram que o pai gostava mais dele do que de qualquer outro filho, odiaram-no e não conseguiam falar com ele amigavelmente.

[[v1-37-5]]

^<<v1-37-5,5>>^ Certa vez, José teve um sonho e, quando o contou a seus irmãos, eles passaram a odiá-lo ainda mais.

[[v1-37-6]]

^<<v1-37-6,6>>^ "Ouçam o sonho que tive", disse-lhes.

[[v1-37-7]]

^<<v1-37-7,7>>^ "Estávamos amarrando os feixes de trigo no campo, quando o meu feixe se levantou e ficou em pé, e os seus feixes se ajuntaram ao redor do meu e se curvaram diante dele".

[[v1-37-8]]

^<<v1-37-8,8>>^ Seus irmãos lhe disseram: "Então você vai reinar sobre nós? Quer dizer que você vai governar sobre nós? " E o odiaram ainda mais, por causa do sonho e do que tinha dito.

[[v1-37-9]]

^<<v1-37-9,9>>^ Depois teve outro sonho e o contou aos seus irmãos: "Tive outro sonho, e desta vez o sol, a lua e onze estrelas se curvavam diante de mim".

[[v1-37-10]]

^<<v1-37-10,10>>^ Quando o contou ao pai e aos irmãos, o pai o repreendeu e lhe disse: "Que sonho foi esse que você teve? Será que eu, sua mãe, e seus irmãos viremos a nos curvar até o chão diante de você? "

[[v1-37-11]]

^<<v1-37-11,11>>^ Assim seus irmãos tiveram ciúmes dele; o pai, no entanto, refletia naquilo.

[[v1-37-12]]

^<<v1-37-12,12>>^ Os irmãos de José tinham ido cuidar dos rebanhos do pai, perto de Siquém,

[[v1-37-13]]

^<<v1-37-13,13>>^ e Israel disse a José: "Como você sabe, seus irmãos estão apascentando os rebanhos perto de Siquém. Quero que você vá até lá". "Sim, senhor", respondeu ele.

[[v1-37-14]]

^<<v1-37-14,14>>^ Disse-lhe o pai: "Vá ver se está tudo bem com os seus irmãos e com os rebanhos, e traga-me notícias". Jacó o enviou quando estava no vale de Hebrom. Mas José se perdeu quando se aproximava de Siquém;

[[v1-37-15]]

^<<v1-37-15,15>>^ um homem o encontrou vagueando pelos campos e lhe perguntou: "Que é que você está procurando? "

[[v1-37-16]]

^<<v1-37-16,16>>^ Ele respondeu: "Procuro meus irmãos. Pode me dizer onde eles estão apascentando os rebanhos? "

[[v1-37-17]]

^<<v1-37-17,17>>^ Respondeu o homem: "Eles já partiram daqui. Eu os ouvi dizer: ‘Vamos para Dotã’ ". Assim José foi em busca dos seus irmãos e os encontrou perto de Dotã.

[[v1-37-18]]

^<<v1-37-18,18>>^ Mas eles o viram de longe e, antes que chegasse, planejaram matá-lo.

[[v1-37-19]]

^<<v1-37-19,19>>^ "Lá vem aquele sonhador! ", diziam uns aos outros.

[[v1-37-20]]

^<<v1-37-20,20>>^ "É agora! Vamos matá-lo e jogá-lo num destes poços, e diremos que um animal selvagem o devorou. Veremos então o que será dos seus sonhos. "

[[v1-37-21]]

^<<v1-37-21,21>>^ Quando Rúben ouviu isso, tentou livrá-lo das mãos deles, dizendo: "Não lhe tiremos a vida! "

[[v1-37-22]]

^<<v1-37-22,22>>^ E acrescentou: "Não derramem sangue. Joguem-no naquele poço no deserto, mas não toquem nele". Rúben propôs isso com a intenção de livrá-lo e levá-lo de volta ao pai.

[[v1-37-23]]

^<<v1-37-23,23>>^ Chegando José, seus irmãos lhe arrancaram a túnica longa,

[[v1-37-24]]

^<<v1-37-24,24>>^ agarraram-no e o jogaram no poço, que estava vazio e sem água.

[[v1-37-25]]

^<<v1-37-25,25>>^ Ao se assentarem para comer, viram ao longe uma caravana de ismaelitas que vinha de Gileade. Seus camelos estavam carregados de especiarias, bálsamo e mirra, que eles levavam para o Egito.

[[v1-37-26]]

^<<v1-37-26,26>>^ Judá disse então a seus irmãos: "Que ganharemos se matarmos o nosso irmão e escondermos o seu sangue?

[[v1-37-27]]

^<<v1-37-27,27>>^ Vamos vendê-lo aos ismaelitas. Não tocaremos nele, afinal é nosso irmão, é nosso próprio sangue". E seus irmãos concordaram.

[[v1-37-28]]

^<<v1-37-28,28>>^ Quando os mercadores ismaelitas de Midiã se aproximaram, seus irmãos tiraram José do poço e o venderam por vinte peças de prata aos ismaelitas, que o levaram para o Egito.

[[v1-37-29]]

^<<v1-37-29,29>>^ Quando Rúben voltou ao poço e viu que José não estava lá, rasgou suas vestes

[[v1-37-30]]

^<<v1-37-30,30>>^ e, voltando a seus irmãos, disse: "O jovem não está lá! Para onde irei agora? "

[[v1-37-31]]

^<<v1-37-31,31>>^ Então eles mataram um bode, mergulharam no sangue a túnica de José

[[v1-37-32]]

^<<v1-37-32,32>>^ e a mandaram ao pai com este recado: "Achamos isto. Veja se é a túnica de teu filho".

[[v1-37-33]]

^<<v1-37-33,33>>^ Ele a reconheceu e disse: "É a túnica de meu filho! Um animal selvagem o devorou! José foi despedaçado! "

[[v1-37-34]]

^<<v1-37-34,34>>^ Então Jacó rasgou suas vestes, vestiu-se de pano de saco e chorou muitos dias por seu filho.

[[v1-37-35]]

^<<v1-37-35,35>>^ Todos os seus filhos e filhas vieram consolá-lo, mas ele recusou ser consolado, dizendo: "Não! Chorando descerei à sepultura para junto de meu filho". E continuou a chorar por ele.

[[v1-37-36]]

^<<v1-37-36,36>>^ Nesse meio tempo, no Egito, os midianitas venderam José a Potifar, oficial do faraó e capitão da guarda.

'''

xref:001-genesis/001-genesis-036.adoc#v1-36-0[&#60; Capítulo Anterior] | <<v1-37-0,Topo>> | xref:001-genesis/001-genesis-038.adoc#v1-38-0[Próximo Capítulo &#62;]