include::./index.adoc[]

[[v1-13-0]]
=== Gênesis, 13
// nvi ?, NVI - Nova Versão Internacional

[[v1-13-1]]

^<<v1-13-1,1>>^ Saiu, pois, Abrão do Egito e foi para o Neguebe, com sua mulher e com tudo o que possuía, e Ló foi com ele.

[[v1-13-2]]

^<<v1-13-2,2>>^ Abrão tinha enriquecido muito, tanto em gado como em prata e ouro.

[[v1-13-3]]

^<<v1-13-3,3>>^ Ele partiu do Neguebe em direção a Betel, indo de um lugar a outro, até que chegou ao lugar entre Betel e Ai onde já havia armado acampamento anteriormente

[[v1-13-4]]

^<<v1-13-4,4>>^ e onde, pela primeira vez, tinha construído um altar. Ali Abrão invocou o nome do Senhor.

[[v1-13-5]]

^<<v1-13-5,5>>^ Ló, que acompanhava Abrão, também possuía rebanhos e tendas.

[[v1-13-6]]

^<<v1-13-6,6>>^ E não podiam morar os dois juntos na mesma região, porque possuíam tantos bens que a terra não podia sustentá-los.

[[v1-13-7]]

^<<v1-13-7,7>>^ Por isso surgiu uma desavença entre os pastores dos rebanhos de Abrão e os de Ló. Nessa época os cananeus e os ferezeus habitavam aquela terra.

[[v1-13-8]]

^<<v1-13-8,8>>^ Então Abrão disse a Ló: "Não haja desavença entre mim e você, ou entre os seus pastores e os meus; afinal somos irmãos!

[[v1-13-9]]

^<<v1-13-9,9>>^ Aí está a terra inteira diante de você. Vamos nos separar! Se você for para a esquerda, irei para a direita; se for para a direita, irei para a esquerda".

[[v1-13-10]]

^<<v1-13-10,10>>^ Olhou então Ló e viu todo o vale do Jordão, todo ele bem irrigado, até Zoar; era como o jardim do Senhor, como a terra do Egito. Isto se deu antes do Senhor destruir Sodoma e Gomorra.

[[v1-13-11]]

^<<v1-13-11,11>>^ Ló escolheu todo o vale do Jordão e partiu em direção ao Leste. Assim os dois se separaram:

[[v1-13-12]]

^<<v1-13-12,12>>^ Abrão ficou na terra de Canaã, mas Ló mudou seu acampamento para um lugar próximo a Sodoma, entre as cidades do vale.

[[v1-13-13]]

^<<v1-13-13,13>>^ Ora, os homens de Sodoma eram extremamente perversos e pecadores contra o Senhor.

[[v1-13-14]]

^<<v1-13-14,14>>^ Disse o Senhor a Abrão, depois que Ló separou-se dele: "De onde você está, olhe para o Norte, para o Sul, para o Leste e para o Oeste:

[[v1-13-15]]

^<<v1-13-15,15>>^ Toda a terra que você está vendo darei a você e à sua descendência para sempre.

[[v1-13-16]]

^<<v1-13-16,16>>^ Tornarei a sua descendência tão numerosa como o pó da terra. Se for possível contar o pó da terra, também se poderá contar a sua descendência.

[[v1-13-17]]

^<<v1-13-17,17>>^ Percorra esta terra de alto a baixo, de um lado a outro, porque eu a darei a você".

[[v1-13-18]]

^<<v1-13-18,18>>^ Então Abrão mudou seu acampamento e passou a viver próximo aos carvalhos de Manre, em Hebrom, onde construiu um altar dedicado ao Senhor.

'''

xref:001-genesis/001-genesis-012.adoc#v1-12-0[&#60; Capítulo Anterior] | <<v1-13-0,Topo>> | xref:001-genesis/001-genesis-014.adoc#v1-14-0[Próximo Capítulo &#62;]