include::./index.adoc[]

[[v1-12-0]]
=== Gênesis, 12
// nvi ?, NVI - Nova Versão Internacional

[[v1-12-1]]

^<<v1-12-1,1>>^ Então o Senhor disse a Abrão: "Saia da sua terra, do meio dos seus parentes e da casa de seu pai, e vá para a terra que eu lhe mostrarei.

[[v1-12-2]]

^<<v1-12-2,2>>^ "Farei de você um grande povo, e o abençoarei. Tornarei famoso o seu nome, e você será uma bênção.

[[v1-12-3]]

^<<v1-12-3,3>>^ Abençoarei os que o abençoarem, e amaldiçoarei os que o amaldiçoarem; e por meio de você todos os povos da terra serão abençoados".

[[v1-12-4]]

^<<v1-12-4,4>>^ Partiu Abrão, como lhe ordenara o Senhor, e Ló foi com ele. Abrão tinha setenta e cinco anos quando saiu de Harã.

[[v1-12-5]]

^<<v1-12-5,5>>^ Levou sua mulher Sarai, seu sobrinho Ló, todos os bens que haviam acumulado e os seus servos, comprados em Harã; partiram para a terra de Canaã e lá chegaram.

[[v1-12-6]]

^<<v1-12-6,6>>^ Abrão atravessou a terra até o lugar do Carvalho de Moré, em Siquém. Naquela época os cananeus habitavam essa terra.

[[v1-12-7]]

^<<v1-12-7,7>>^ O Senhor apareceu a Abrão e disse: "À sua descendência darei esta terra". Abrão construiu ali um altar dedicado ao Senhor, que lhe havia aparecido.

[[v1-12-8]]

^<<v1-12-8,8>>^ Dali prosseguiu em direção às colinas a leste de Betel, onde armou acampamento, tendo Betel a oeste e Ai a leste. Construiu ali um altar dedicado ao Senhor e invocou o nome do Senhor.

[[v1-12-9]]

^<<v1-12-9,9>>^ Depois Abrão partiu e prosseguiu em direção ao Neguebe.

[[v1-12-10]]

^<<v1-12-10,10>>^ Houve fome naquela terra, e Abrão desceu ao Egito para ali viver algum tempo, pois a fome era rigorosa.

[[v1-12-11]]

^<<v1-12-11,11>>^ Quando estava chegando ao Egito, disse a Sarai, sua mulher: "Bem sei que você é bonita.

[[v1-12-12]]

^<<v1-12-12,12>>^ Quando os egípcios a virem, dirão: ‘Esta é a mulher dele’. E me matarão, mas deixarão você viva.

[[v1-12-13]]

^<<v1-12-13,13>>^ Diga que é minha irmã, para que me tratem bem por amor a você e minha vida seja poupada por sua causa".

[[v1-12-14]]

^<<v1-12-14,14>>^ Quando Abrão chegou ao Egito, viram os egípcios que Sarai era uma mulher muito bonita.

[[v1-12-15]]

^<<v1-12-15,15>>^ Vendo-a, os homens da corte do faraó a elogiaram diante do faraó, e ela foi levada ao seu palácio.

[[v1-12-16]]

^<<v1-12-16,16>>^ Ele tratou bem a Abrão por causa dela, e Abrão recebeu ovelhas e bois, jumentos e jumentas, servos e servas, e camelos.

[[v1-12-17]]

^<<v1-12-17,17>>^ Mas o Senhor puniu o faraó e sua corte com graves doenças, por causa de Sarai, mulher de Abrão.

[[v1-12-18]]

^<<v1-12-18,18>>^ Por isso o faraó mandou chamar Abrão e disse: "O que você fez comigo? Por que não me falou que ela era sua mulher?

[[v1-12-19]]

^<<v1-12-19,19>>^ Por que disse que ela era sua irmã? Foi por isso que eu a tomei para ser minha mulher. Aí está a sua mulher. Tome-a e vá! "

[[v1-12-20]]

^<<v1-12-20,20>>^ A seguir o faraó deu ordens para que providenciassem o necessário para que Abrão partisse, com sua mulher e com tudo o que possuía.

'''

xref:001-genesis/001-genesis-011.adoc#v1-11-0[&#60; Capítulo Anterior] | <<v1-12-0,Topo>> | xref:001-genesis/001-genesis-013.adoc#v1-13-0[Próximo Capítulo &#62;]