include::./index.adoc[]

[[v1-22-0]]
=== Gênesis, 22
// nvi ?, NVI - Nova Versão Internacional

[[v1-22-1]]

^<<v1-22-1,1>>^ Passado algum tempo, Deus pôs Abraão à prova, dizendo-lhe: "Abraão! " Ele respondeu: "Eis-me aqui".

[[v1-22-2]]

^<<v1-22-2,2>>^ Então disse Deus: "Tome seu filho, seu único filho, Isaque, a quem você ama, e vá para a região de Moriá. Sacrifique-o ali como holocausto num dos montes que lhe indicarei".

[[v1-22-3]]

^<<v1-22-3,3>>^ Na manhã seguinte, Abraão levantou-se e preparou o seu jumento. Levou consigo dois de seus servos e Isaque seu filho. Depois de cortar lenha para o holocausto, partiu em direção ao lugar que Deus lhe havia indicado.

[[v1-22-4]]

^<<v1-22-4,4>>^ No terceiro dia de viagem, Abraão olhou e viu o lugar ao longe.

[[v1-22-5]]

^<<v1-22-5,5>>^ Disse ele a seus servos: "Fiquem aqui com o jumento enquanto eu e o rapaz vamos até lá. Depois de adorarmos, voltaremos".

[[v1-22-6]]

^<<v1-22-6,6>>^ Abraão pegou a lenha para o holocausto e a colocou nos ombros de seu filho Isaque, e ele mesmo levou as brasas para o fogo, e a faca. E caminhando os dois juntos,

[[v1-22-7]]

^<<v1-22-7,7>>^ Isaque disse a seu pai Abraão: "Meu pai! " "Sim, meu filho", respondeu Abraão. Isaque perguntou: "As brasas e a lenha estão aqui, mas onde está o cordeiro para o holocausto? "

[[v1-22-8]]

^<<v1-22-8,8>>^ Respondeu Abraão: "Deus mesmo há de prover o cordeiro para o holocausto, meu filho". E os dois continuaram a caminhar juntos.

[[v1-22-9]]

^<<v1-22-9,9>>^ Quando chegaram ao lugar que Deus lhe havia indicado, Abraão construiu um altar e sobre ele arrumou a lenha. Amarrou seu filho Isaque e o colocou sobre o altar, em cima da lenha.

[[v1-22-10]]

^<<v1-22-10,10>>^ Então estendeu a mão e pegou a faca para sacrificar seu filho.

[[v1-22-11]]

^<<v1-22-11,11>>^ Mas o Anjo do Senhor o chamou do céu: "Abraão! Abraão! " "Eis-me aqui", respondeu ele.

[[v1-22-12]]

^<<v1-22-12,12>>^ "Não toque no rapaz", disse o Anjo. "Não lhe faça nada. Agora sei que você teme a Deus, porque não me negou seu filho, o seu único filho. "

[[v1-22-13]]

^<<v1-22-13,13>>^ Abraão ergueu os olhos e viu um carneiro preso pelos chifres num arbusto. Foi lá, pegou-o e sacrificou-o como holocausto em lugar de seu filho.

[[v1-22-14]]

^<<v1-22-14,14>>^ Abraão deu àquele lugar o nome de "O Senhor proverá". Por isso até hoje se diz: "No monte do Senhor se proverá".

[[v1-22-15]]

^<<v1-22-15,15>>^ Pela segunda vez o Anjo do Senhor chamou do céu a Abraão

[[v1-22-16]]

^<<v1-22-16,16>>^ e disse: "Juro por mim mesmo", declara o Senhor, "que por ter feito o que fez, não me negando seu filho, o seu único filho,

[[v1-22-17]]

^<<v1-22-17,17>>^ esteja certo de que o abençoarei e farei seus descendentes tão numerosos como as estrelas do céu e como a areia das praias do mar. Sua descendência conquistará as cidades dos que lhe forem inimigos

[[v1-22-18]]

^<<v1-22-18,18>>^ e, por meio dela, todos povos da terra serão abençoados, porque você me obedeceu".

[[v1-22-19]]

^<<v1-22-19,19>>^ Então voltou Abraão a seus servos, e juntos partiram para Berseba, onde passou a viver.

[[v1-22-20]]

^<<v1-22-20,20>>^ Passado algum tempo, disseram a Abraão que Milca dera filhos a seu irmão Naor:

[[v1-22-21]]

^<<v1-22-21,21>>^ Uz, o mais velho, Buz, seu irmão, Quemuel, pai de Arã,

[[v1-22-22]]

^<<v1-22-22,22>>^ Quésede, Hazo, Pildas, Jidlafe e Betuel,

[[v1-22-23]]

^<<v1-22-23,23>>^ pai de Rebeca. Estes foram os oito filhos que Milca deu a Naor, irmão de Abraão.

[[v1-22-24]]

^<<v1-22-24,24>>^ E sua concubina, chamada Reumá, teve os seguintes filhos: Tebá, Gaã, Taás e Maaca.

'''

xref:001-genesis/001-genesis-021.adoc#v1-21-0[&#60; Capítulo Anterior] | <<v1-22-0,Topo>> | xref:001-genesis/001-genesis-023.adoc#v1-23-0[Próximo Capítulo &#62;]