include::./index.adoc[]

[[v1-1-0]]
=== Gênesis, 1
// nvi ?, NVI - Nova Versão Internacional

[[v1-1-1]]

^<<v1-1-1,1>>^ No princípio Deus criou os céus e a terra.

[[v1-1-2]]

^<<v1-1-2,2>>^ Era a terra sem forma e vazia; trevas cobriam a face do abismo, e o Espírito de Deus se movia sobre a face das águas.

[[v1-1-3]]

^<<v1-1-3,3>>^ Disse Deus: "Haja luz", e houve luz.

[[v1-1-4]]

^<<v1-1-4,4>>^ Deus viu que a luz era boa, e separou a luz das trevas.

[[v1-1-5]]

^<<v1-1-5,5>>^ Deus chamou à luz dia, e às trevas chamou noite. Passaram-se a tarde e a manhã; esse foi o primeiro dia.

[[v1-1-6]]

^<<v1-1-6,6>>^ Depois disse Deus: "Haja entre as águas um firmamento que separe águas de águas".

[[v1-1-7]]

^<<v1-1-7,7>>^ Então Deus fez o firmamento e separou as águas que estavam embaixo do firmamento das que estavam por cima. E assim foi.

[[v1-1-8]]

^<<v1-1-8,8>>^ Ao firmamento Deus chamou céu. Passaram-se a tarde e a manhã; esse foi o segundo dia.

[[v1-1-9]]

^<<v1-1-9,9>>^ E disse Deus: "Ajuntem-se num só lugar as águas que estão debaixo do céu, e apareça a parte seca". E assim foi.

[[v1-1-10]]

^<<v1-1-10,10>>^ À parte seca Deus chamou terra, e chamou mares ao conjunto das águas. E Deus viu que ficou bom.

[[v1-1-11]]

^<<v1-1-11,11>>^ Então disse Deus: "Cubra-se a terra de vegetação: plantas que dêem sementes e árvores cujos frutos produzam sementes de acordo com as suas espécies". E assim foi.

[[v1-1-12]]

^<<v1-1-12,12>>^ A terra fez brotar a vegetação: plantas que dão sementes de acordo com as suas espécies, e árvores cujos frutos produzem sementes de acordo com as suas espécies. E Deus viu que ficou bom.

[[v1-1-13]]

^<<v1-1-13,13>>^ Passaram-se a tarde e a manhã; esse foi o terceiro dia.

[[v1-1-14]]

^<<v1-1-14,14>>^ Disse Deus: "Haja luminares no firmamento do céu para separar o dia da noite. Sirvam eles de sinais para marcar estações, dias e anos,

[[v1-1-15]]

^<<v1-1-15,15>>^ e sirvam de luminares no firmamento do céu para iluminar a terra". E assim foi.

[[v1-1-16]]

^<<v1-1-16,16>>^ Deus fez os dois grandes luminares: o maior para governar o dia e o menor para governar a noite; fez também as estrelas.

[[v1-1-17]]

^<<v1-1-17,17>>^ Deus os colocou no firmamento do céu para iluminar a terra,

[[v1-1-18]]

^<<v1-1-18,18>>^ governar o dia e a noite, e separar a luz das trevas. E Deus viu que ficou bom.

[[v1-1-19]]

^<<v1-1-19,19>>^ Passaram-se a tarde e a manhã; esse foi o quarto dia.

[[v1-1-20]]

^<<v1-1-20,20>>^ Disse também Deus: "Encham-se as águas de seres vivos, e sobre a terra voem aves sob o firmamento do céu".

[[v1-1-21]]

^<<v1-1-21,21>>^ Assim Deus criou os grandes animais aquáticos e os demais seres vivos que povoam as águas, de acordo com as suas espécies; e todas as aves, de acordo com as suas espécies. E Deus viu que ficou bom.

[[v1-1-22]]

^<<v1-1-22,22>>^ Então Deus os abençoou, dizendo: "Sejam férteis e multipliquem-se! Encham as águas dos mares! E multipliquem-se as aves na terra".

[[v1-1-23]]

^<<v1-1-23,23>>^ Passaram-se a tarde e a manhã; esse foi o quinto dia.

[[v1-1-24]]

^<<v1-1-24,24>>^ E disse Deus: "Produza a terra seres vivos de acordo com as suas espécies: rebanhos domésticos, animais selvagens e os demais seres vivos da terra, cada um de acordo com a sua espécie". E assim foi.

[[v1-1-25]]

^<<v1-1-25,25>>^ Deus fez os animais selvagens de acordo com as suas espécies, os rebanhos domésticos de acordo com as suas espécies, e os demais seres vivos da terra de acordo com as suas espécies. E Deus viu que ficou bom.

[[v1-1-26]]

^<<v1-1-26,26>>^ Então disse Deus: "Façamos o homem à nossa imagem, conforme a nossa semelhança. Domine ele sobre os peixes do mar, sobre as aves do céu, sobre os animais grandes de toda a terra e sobre todos os pequenos animais que se movem rente ao chão".

[[v1-1-27]]

^<<v1-1-27,27>>^ Criou Deus o homem à sua imagem, à imagem de Deus o criou; homem e mulher os criou.

[[v1-1-28]]

^<<v1-1-28,28>>^ Deus os abençoou, e lhes disse: "Sejam férteis e multipliquem-se! Encham e subjuguem a terra! Dominem sobre os peixes do mar, sobre as aves do céu e sobre todos os animais que se movem pela terra".

[[v1-1-29]]

^<<v1-1-29,29>>^ Disse Deus: "Eis que lhes dou todas as plantas que nascem em toda a terra e produzem sementes, e todas as árvores que dão frutos com sementes. Elas servirão de alimento para vocês.

[[v1-1-30]]

^<<v1-1-30,30>>^ E dou todos os vegetais como alimento a tudo o que tem em si fôlego de vida: a todos os grandes animais da terra, a todas as aves do céu e a todas as criaturas que se movem rente ao chão". E assim foi.

[[v1-1-31]]

^<<v1-1-31,31>>^ E Deus viu tudo o que havia feito, e tudo havia ficado muito bom. Passaram-se a tarde e a manhã; esse foi o sexto dia.

'''

**&#60; Capítulo Anterior** | <<v1-1-0,Topo>> | xref:001-genesis/001-genesis-002.adoc#v1-2-0[Próximo Capítulo &#62;]