include::./index.adoc[]

[[v1-24-0]]
=== Gênesis, 24
// nvi ?, NVI - Nova Versão Internacional

[[v1-24-1]]

^<<v1-24-1,1>>^ Abraão já era velho, de idade bem avançada, e o Senhor em tudo o abençoara.

[[v1-24-2]]

^<<v1-24-2,2>>^ Disse ele ao servo mais velho de sua casa, que era o responsável por tudo quanto tinha: "Ponha a mão debaixo da minha coxa

[[v1-24-3]]

^<<v1-24-3,3>>^ e jure pelo Senhor, o Deus dos céus e o Deus da terra, que não buscará mulher para meu filho entre as filhas dos cananeus, no meio dos quais estou vivendo,

[[v1-24-4]]

^<<v1-24-4,4>>^ mas irá à minha terra e buscará entre os meus parentes uma mulher para meu filho Isaque".

[[v1-24-5]]

^<<v1-24-5,5>>^ O servo lhe perguntou: "E se a mulher não quiser vir comigo a esta terra? Devo então levar teu filho de volta à terra de onde vieste? "

[[v1-24-6]]

^<<v1-24-6,6>>^ "Cuidado! ", disse Abraão, "Não deixe o meu filho voltar para lá.

[[v1-24-7]]

^<<v1-24-7,7>>^ "O Senhor, o Deus dos céus, que me tirou da casa de meu pai e de minha terra natal e que me prometeu sob juramento que à minha descendência daria esta terra, enviará o seu anjo adiante de você para que de lá traga uma mulher para meu filho.

[[v1-24-8]]

^<<v1-24-8,8>>^ Se a mulher não quiser vir, você estará livre do juramento. Mas não leve o meu filho de volta para lá".

[[v1-24-9]]

^<<v1-24-9,9>>^ Então o servo pôs a mão debaixo da coxa de Abraão, seu senhor, e jurou cumprir aquela palavra.

[[v1-24-10]]

^<<v1-24-10,10>>^ O servo partiu, com dez camelos do seu senhor, levando também do que o seu senhor tinha de melhor. Partiu para a Mesopotâmia, em direção à cidade onde Naor tinha morado.

[[v1-24-11]]

^<<v1-24-11,11>>^ Ao cair da tarde, quando as mulheres costumam sair para buscar água, ele fez os camelos se ajoelharem junto ao poço que ficava fora da cidade.

[[v1-24-12]]

^<<v1-24-12,12>>^ Então orou: "SENHOR, Deus do meu senhor Abraão, dá-me neste dia bom êxito e seja bondoso com o meu senhor Abraão.

[[v1-24-13]]

^<<v1-24-13,13>>^ Como vês, estou aqui ao lado desta fonte, e as jovens do povo desta cidade estão vindo para tirar água.

[[v1-24-14]]

^<<v1-24-14,14>>^ Concede que a jovem a quem eu disser: ‘Por favor, incline o seu cântaro e dê-me de beber’, e ela me responder: ‘Bebe; também darei água aos teus camelos’, seja essa a que escolheste para teu servo Isaque. Saberei assim que foste bondoso com o meu senhor".

[[v1-24-15]]

^<<v1-24-15,15>>^ Antes que ele terminasse de orar, surgiu Rebeca, filha de Betuel, filho de Milca, mulher de Naor, irmão de Abraão, trazendo no ombro o seu cântaro.

[[v1-24-16]]

^<<v1-24-16,16>>^ A jovem era muito bonita e virgem; nenhum homem tivera relações com ela. Rebeca desceu à fonte, encheu seu cântaro e voltou.

[[v1-24-17]]

^<<v1-24-17,17>>^ O servo apressou-se ao encontro dela e disse: "Por favor, dê-me um pouco de água do seu cântaro".

[[v1-24-18]]

^<<v1-24-18,18>>^ "Beba, meu senhor", disse ela, e tirou rapidamente dos ombros o cântaro e o serviu.

[[v1-24-19]]

^<<v1-24-19,19>>^ Depois que lhe deu de beber, disse: "Tirarei água também para os seus camelos até saciá-los".

[[v1-24-20]]

^<<v1-24-20,20>>^ Assim ela esvaziou depressa seu cântaro no bebedouro e correu de volta ao poço para tirar mais água para todos os camelos.

[[v1-24-21]]

^<<v1-24-21,21>>^ Sem dizer nada, o homem a observava atentamente para saber se o Senhor tinha ou não coroado de êxito a sua missão.

[[v1-24-22]]

^<<v1-24-22,22>>^ Quando os camelos acabaram de beber, o homem deu à jovem um pendente de ouro de seis gramas e duas pulseiras de ouro de cento e vinte gramas,

[[v1-24-23]]

^<<v1-24-23,23>>^ e perguntou: "De quem você é filha? Diga-me, por favor, se há lugar na casa de seu pai para eu e meus companheiros passarmos a noite".

[[v1-24-24]]

^<<v1-24-24,24>>^ "Sou filha de Betuel, o filho que Milca deu a Naor", respondeu ela;

[[v1-24-25]]

^<<v1-24-25,25>>^ e acrescentou: "Temos bastante palha e forragem, e também temos lugar para vocês passarem a noite".

[[v1-24-26]]

^<<v1-24-26,26>>^ Então o homem curvou-se em adoração ao Senhor,

[[v1-24-27]]

^<<v1-24-27,27>>^ dizendo: "Bendito seja o Senhor, o Deus do meu senhor Abraão, que não retirou sua bondade e sua fidelidade do meu senhor. Quanto a mim, o Senhor me conduziu na jornada até a casa dos parentes do meu senhor".

[[v1-24-28]]

^<<v1-24-28,28>>^ A jovem correu para casa e contou tudo à família de sua mãe.

[[v1-24-29]]

^<<v1-24-29,29>>^ Rebeca tinha um irmão chamado Labão. Ele saiu apressado à fonte para conhecer o homem,

[[v1-24-30]]

^<<v1-24-30,30>>^ pois tinha visto o pendente, e as pulseiras no braço de sua irmã, e ouvira Rebeca contar o que o homem lhe dissera. Saiu, pois, e foi encontrá-lo parado junto à fonte, ao lado dos camelos.

[[v1-24-31]]

^<<v1-24-31,31>>^ E disse: "Venha, bendito do Senhor! Por que ficar aí fora? Já arrumei a casa e um lugar para os camelos".

[[v1-24-32]]

^<<v1-24-32,32>>^ Assim o homem dirigiu-se à casa, e os camelos foram descarregados. Deram palha e forragem aos camelos, e água ao homem e aos que estavam com ele para lavarem os pés.

[[v1-24-33]]

^<<v1-24-33,33>>^ Depois lhe trouxeram comida, mas ele disse: "Não comerei enquanto não disser o que tenho para dizer". Disse Labão: "Então fale".

[[v1-24-34]]

^<<v1-24-34,34>>^ E ele disse: "Sou servo de Abraão.

[[v1-24-35]]

^<<v1-24-35,35>>^ O Senhor o abençoou muito, e ele se tornou muito rico. Deu-lhe ovelhas e bois, prata e ouro, servos e servas, camelos e jumentos.

[[v1-24-36]]

^<<v1-24-36,36>>^ Sara, mulher do meu senhor, na velhice lhe deu um filho, que é o herdeiro de tudo o que Abraão possui.

[[v1-24-37]]

^<<v1-24-37,37>>^ E meu senhor fez-me jurar, dizendo: ‘Você não buscará mulher para meu filho entre as filhas dos cananeus, em cuja terra estou vivendo,

[[v1-24-38]]

^<<v1-24-38,38>>^ mas irá à família de meu pai, ao meu próprio clã, buscar uma mulher para meu filho’.

[[v1-24-39]]

^<<v1-24-39,39>>^ "Então perguntei a meu senhor: ‘E se a mulher não quiser me acompanhar? ’

[[v1-24-40]]

^<<v1-24-40,40>>^ "Ele respondeu: ‘O Senhor, a quem tenho servido, enviará seu anjo com você e coroará de êxito a sua missão, para que você traga para meu filho uma mulher do meu próprio clã, da família de meu pai.

[[v1-24-41]]

^<<v1-24-41,41>>^ Quando chegar aos meus parentes, você estará livre do juramento se eles se recusarem a entregá-la a você. Só então você estará livre do juramento’.

[[v1-24-42]]

^<<v1-24-42,42>>^ "Hoje, quando cheguei à fonte, eu disse: Ó Senhor, Deus do meu senhor Abraão, se assim desejares, dá êxito à missão de que fui incumbido.

[[v1-24-43]]

^<<v1-24-43,43>>^ Aqui estou em pé diante desta fonte; se uma moça vier tirar água e eu lhe disser: ‘Por favor, dê-me de beber um pouco de seu cântaro’,

[[v1-24-44]]

^<<v1-24-44,44>>^ e ela me responder: ‘Bebe. Também darei água aos teus camelos’, seja essa a que o Senhor escolheu para o filho do meu senhor.

[[v1-24-45]]

^<<v1-24-45,45>>^ "Antes de terminar de orar em meu coração, surgiu Rebeca, com o cântaro ao ombro. Dirigiu-se à fonte e tirou água, e eu lhe disse: Por favor, dê-me de beber.

[[v1-24-46]]

^<<v1-24-46,46>>^ "Ela se apressou a tirar o cântaro do ombro e disse: ‘Bebe; também darei água aos teus camelos’. Eu bebi, e ela deu de beber também aos camelos.

[[v1-24-47]]

^<<v1-24-47,47>>^ "Depois lhe perguntei: ‘De quem você é filha? ’ "Ela me respondeu: ‘De Betuel, filho de Naor e Milca’. "Então coloquei o pendente em seu nariz e as pulseiras em seus braços,

[[v1-24-48]]

^<<v1-24-48,48>>^ e curvei-me em adoração ao Senhor. Bendisse ao Senhor, o Deus do meu senhor Abraão, que me guiou pelo caminho certo para buscar para o filho dele a neta do irmão do meu senhor.

[[v1-24-49]]

^<<v1-24-49,49>>^ Agora, se quiserem mostrar fidelidade e bondade a meu senhor, digam-me; e, se não quiserem, digam-me também, para que eu decida o que fazer".

[[v1-24-50]]

^<<v1-24-50,50>>^ Labão e Betuel responderam: "Isso vem do Senhor; nada lhe podemos dizer, nem a favor, nem contra.

[[v1-24-51]]

^<<v1-24-51,51>>^ Aqui está Rebeca; leve-a com você e que ela se torne a mulher do filho do seu senhor, como disse o Senhor".

[[v1-24-52]]

^<<v1-24-52,52>>^ Quando o servo de Abraão ouviu o que disseram, curvou-se até ao chão diante do Senhor.

[[v1-24-53]]

^<<v1-24-53,53>>^ Então o servo deu jóias de ouro e de prata e vestidos a Rebeca; deu também presentes valiosos ao irmão dela e à sua mãe.

[[v1-24-54]]

^<<v1-24-54,54>>^ Depois ele e os homens que o acompanhavam comeram, beberam e ali passaram a noite. Ao se levantarem na manhã seguinte, ele disse: "Deixem-me voltar ao meu senhor".

[[v1-24-55]]

^<<v1-24-55,55>>^ Mas o irmão e a mãe dela responderam: "Deixe a jovem ficar mais uns dez dias conosco; então você poderá partir".

[[v1-24-56]]

^<<v1-24-56,56>>^ Mas ele disse: "Não me detenham, agora que o Senhor coroou de êxito a minha missão. Vamos despedir-nos, e voltarei ao meu senhor".

[[v1-24-57]]

^<<v1-24-57,57>>^ Então lhe disseram: "Vamos chamar a jovem e ver o que ela diz".

[[v1-24-58]]

^<<v1-24-58,58>>^ Chamaram Rebeca e lhe perguntaram: "Você quer ir com este homem? " "Sim, quero", respondeu ela.

[[v1-24-59]]

^<<v1-24-59,59>>^ Despediram-se, pois, de sua irmã Rebeca, de sua ama, do servo de Abraão e dos que o acompanhavam.

[[v1-24-60]]

^<<v1-24-60,60>>^ E abençoaram Rebeca, dizendo-lhe: "Que você cresça, nossa irmã, até ser milhares de milhares; e que a sua descendência conquiste as cidades dos seus inimigos".

[[v1-24-61]]

^<<v1-24-61,61>>^ Então Rebeca e suas servas se aprontaram, montaram seus camelos e partiram com o homem. E assim o servo partiu levando Rebeca.

[[v1-24-62]]

^<<v1-24-62,62>>^ Isaque tinha voltado de Beer-Laai-Roi, pois habitava no Neguebe.

[[v1-24-63]]

^<<v1-24-63,63>>^ Certa tarde, saiu ao campo para meditar. Ao erguer os olhos, viu que se aproximavam camelos.

[[v1-24-64]]

^<<v1-24-64,64>>^ Rebeca também ergueu os olhos e viu Isaque. Ela desceu do camelo

[[v1-24-65]]

^<<v1-24-65,65>>^ e perguntou ao servo: "Quem é aquele homem que vem pelo campo ao nosso encontro? " "É meu senhor", respondeu o servo. Então ela se cobriu com o véu.

[[v1-24-66]]

^<<v1-24-66,66>>^ Depois o servo contou a Isaque tudo o que havia feito.

[[v1-24-67]]

^<<v1-24-67,67>>^ Isaque levou Rebeca para a tenda de sua mãe Sara; fez dela sua mulher, e a amou; assim Isaque foi consolado após a morte de sua mãe.

'''

xref:001-genesis/001-genesis-023.adoc#v1-23-0[&#60; Capítulo Anterior] | <<v1-24-0,Topo>> | xref:001-genesis/001-genesis-025.adoc#v1-25-0[Próximo Capítulo &#62;]