include::./index.adoc[]

[[v1-14-0]]
=== Gênesis, 14
// nvi ?, NVI - Nova Versão Internacional

[[v1-14-1]]

^<<v1-14-1,1>>^ Naquela época Anrafel, rei de Sinear, Arioque, rei de Elasar, Quedorlaomer, rei de Elão, e Tidal, rei de Goim,

[[v1-14-2]]

^<<v1-14-2,2>>^ foram à guerra contra Bera, rei de Sodoma, contra Birsa, rei de Gomorra, contra Sinabe, rei de Admá, contra Semeber, rei de Zeboim, e contra o rei de Belá, que é Zoar.

[[v1-14-3]]

^<<v1-14-3,3>>^ Todos esses últimos juntaram suas tropas no vale de Sidim, onde fica o mar Salgado.

[[v1-14-4]]

^<<v1-14-4,4>>^ Doze anos estiveram sujeitos a Quedorlaomer, mas no décimo terceiro ano se rebelaram.

[[v1-14-5]]

^<<v1-14-5,5>>^ No décimo quarto ano, Quedorlaomer e os reis que a ele se aliaram derrotaram os refains em Asterote-Carnaim, os zuzins em Hã, os emins em Savé-Quiriataim

[[v1-14-6]]

^<<v1-14-6,6>>^ e os horeus desde os montes de Seir até El-Parã, próximo ao deserto.

[[v1-14-7]]

^<<v1-14-7,7>>^ Depois, voltaram e foram para En-Mispate, que é Cades, e conquistaram todo o território dos amalequitas e dos amorreus que viviam em Hazazom-Tamar.

[[v1-14-8]]

^<<v1-14-8,8>>^ Então os reis de Sodoma, de Gomorra, de Admá, de Zeboim e de Belá, que é Zoar, marcharam e tomaram posição de combate no vale de Sidim

[[v1-14-9]]

^<<v1-14-9,9>>^ contra Quedorlaomer, rei de Elão, contra Tidal, rei de Goim, contra Anrafel, rei de Sinear, e contra Arioque, rei de Elasar. Eram quatro reis contra cinco.

[[v1-14-10]]

^<<v1-14-10,10>>^ Ora, o vale de Sidim era cheio de poços de betume e, quando os reis de Sodoma e de Gomorra fugiram, alguns dos seus homens caíram nos poços e o restante escapou para os montes.

[[v1-14-11]]

^<<v1-14-11,11>>^ Os vencedores saquearam todos os bens de Sodoma e de Gomorra e todo o seu mantimento, e partiram.

[[v1-14-12]]

^<<v1-14-12,12>>^ Levaram também Ló, sobrinho de Abrão, e os bens que ele possuía, visto que morava em Sodoma.

[[v1-14-13]]

^<<v1-14-13,13>>^ Mas alguém que tinha escapado veio e relatou tudo a Abrão, o hebreu. Abrão vivia próximo aos carvalhos de Manre, o amorreu, irmão de Escol e de Aner, aliados de Abrão.

[[v1-14-14]]

^<<v1-14-14,14>>^ Quando Abrão ouviu que seu parente fora levado prisioneiro, mandou convocar os trezentos e dezoito homens treinados, nascidos em sua casa, e saiu em perseguição aos inimigos até Dã.

[[v1-14-15]]

^<<v1-14-15,15>>^ Atacou-os durante a noite em grupos, e assim os derrotou, perseguindo-os até Hobá, ao norte de Damasco.

[[v1-14-16]]

^<<v1-14-16,16>>^ Recuperou todos os bens e trouxe de volta seu parente Ló com tudo o que possuía, juntamente com as mulheres e o restante dos prisioneiros.

[[v1-14-17]]

^<<v1-14-17,17>>^ Voltando Abrão da vitória sobre Quedorlaomer e sobre os reis que a ele se haviam aliado, o rei de Sodoma foi ao seu encontro no vale de Savé, isto é, o vale do Rei.

[[v1-14-18]]

^<<v1-14-18,18>>^ Então Melquisedeque, rei de Salém e sacerdote do Deus Altíssimo, trouxe pão e vinho

[[v1-14-19]]

^<<v1-14-19,19>>^ e abençoou Abrão, dizendo: "Bendito seja Abrão pelo Deus Altíssimo, Criador dos céus e da terra.

[[v1-14-20]]

^<<v1-14-20,20>>^ E bendito seja o Deus Altíssimo, que entregou seus inimigos em suas mãos". E Abrão lhe deu o dízimo de tudo.

[[v1-14-21]]

^<<v1-14-21,21>>^ O rei de Sodoma disse a Abrão: "Dê-me as pessoas e pode ficar com os bens".

[[v1-14-22]]

^<<v1-14-22,22>>^ Mas Abrão respondeu ao rei de Sodoma: "De mãos levantadas ao Senhor, Deus Altíssimo, Criador dos céus e da terra, juro

[[v1-14-23]]

^<<v1-14-23,23>>^ que não aceitarei nada do que lhe pertence, nem mesmo um cordão ou uma correia de sandália, para que você jamais venha a dizer: ‘Eu enriqueci Abrão’.

[[v1-14-24]]

^<<v1-14-24,24>>^ Nada aceitarei, a não ser o que os meus servos comeram e a porção pertencente a Aner, Escol e Manre, os quais me acompanharam. Que eles recebam a sua porção".

'''

xref:001-genesis/001-genesis-013.adoc#v1-13-0[&#60; Capítulo Anterior] | <<v1-14-0,Topo>> | xref:001-genesis/001-genesis-015.adoc#v1-15-0[Próximo Capítulo &#62;]