include::./index.adoc[]

[[v1-31-0]]
=== Gênesis, 31
// nvi ?, NVI - Nova Versão Internacional

[[v1-31-1]]

^<<v1-31-1,1>>^ Jacó, porém, ouviu falar que os filhos de Labão estavam dizendo: "Jacó tomou tudo que o nosso pai tinha e juntou toda a sua riqueza à custa do nosso pai".

[[v1-31-2]]

^<<v1-31-2,2>>^ E Jacó percebeu que a atitude de Labão para com ele já não era a mesma de antes.

[[v1-31-3]]

^<<v1-31-3,3>>^ E o Senhor disse a Jacó: "Volte para a terra de seus pais e de seus parentes, e eu estarei com você".

[[v1-31-4]]

^<<v1-31-4,4>>^ Então Jacó mandou chamar Raquel e Lia para virem ao campo onde estavam os seus rebanhos,

[[v1-31-5]]

^<<v1-31-5,5>>^ e lhes disse: "Vejo que a atitude do seu pai para comigo não é mais a mesma, mas o Deus de meu pai tem estado comigo.

[[v1-31-6]]

^<<v1-31-6,6>>^ Vocês sabem que trabalhei para seu pai com todo o empenho,

[[v1-31-7]]

^<<v1-31-7,7>>^ mas ele tem me feito de tolo, mudando o meu salário dez vezes. Contudo, Deus não permitiu que ele me prejudicasse.

[[v1-31-8]]

^<<v1-31-8,8>>^ Se ele dizia: ‘As crias salpicadas serão o seu salário’, todos os rebanhos geravam filhotes salpicados; e se ele dizia: ‘As que têm listras serão o seu salário’, todos os rebanhos geravam filhotes com listras.

[[v1-31-9]]

^<<v1-31-9,9>>^ Foi assim que Deus tirou os rebanhos de seu pai e os deu a mim.

[[v1-31-10]]

^<<v1-31-10,10>>^ "Na época do acasalamento, tive um sonho em que olhei e vi que os machos que fecundavam o rebanho tinham listras, eram salpicados e malhados.

[[v1-31-11]]

^<<v1-31-11,11>>^ O anjo de Deus me disse no sonho: ‘Jacó! ’ Eu respondi: ‘Eis-me aqui! ’

[[v1-31-12]]

^<<v1-31-12,12>>^ Então ele disse: ‘Olhe e veja que todos os machos que fecundam o rebanho têm listras, são salpicados e malhados, porque tenho visto tudo o que Labão lhe fez.

[[v1-31-13]]

^<<v1-31-13,13>>^ Sou o Deus de Betel, onde você ungiu uma coluna e me fez um voto. Saia agora desta terra e volte para a sua terra natal’ ".

[[v1-31-14]]

^<<v1-31-14,14>>^ Raquel e Lia disseram a Jacó: "Temos ainda parte na herança dos bens de nosso pai?

[[v1-31-15]]

^<<v1-31-15,15>>^ Não nos trata ele como estrangeiras? Não apenas nos vendeu como também gastou tudo o que foi pago por nós!

[[v1-31-16]]

^<<v1-31-16,16>>^ Toda a riqueza que Deus tirou de nosso pai é nossa e de nossos filhos. Portanto, faça tudo quanto Deus lhe ordenou".

[[v1-31-17]]

^<<v1-31-17,17>>^ Então Jacó ajudou seus filhos e suas mulheres a montar nos camelos,

[[v1-31-18]]

^<<v1-31-18,18>>^ e conduziu todo o seu rebanho, junto com todos os bens que havia acumulado em Padã-Arã, para ir à terra de Canaã, à casa de seu pai Isaque.

[[v1-31-19]]

^<<v1-31-19,19>>^ Enquanto Labão tinha saído para tosquiar suas ovelhas, Raquel roubou de seu pai os ídolos do clã.

[[v1-31-20]]

^<<v1-31-20,20>>^ Foi assim que Jacó enganou a Labão, o arameu, fugindo sem lhe dizer nada.

[[v1-31-21]]

^<<v1-31-21,21>>^ Ele fugiu com tudo o que tinha e, atravessando o Eufrates, foi para os montes de Gileade.

[[v1-31-22]]

^<<v1-31-22,22>>^ Três dias depois, Labão foi informado de que Jacó tinha fugido.

[[v1-31-23]]

^<<v1-31-23,23>>^ Tomando consigo os homens de sua família, perseguiu Jacó por sete dias e o alcançou nos montes de Gileade.

[[v1-31-24]]

^<<v1-31-24,24>>^ Então, de noite, Deus veio em sonho a Labão, o arameu, e o advertiu: "Cuidado! Não diga nada a Jacó, não lhe faça promessas nem ameaças".

[[v1-31-25]]

^<<v1-31-25,25>>^ Labão alcançou Jacó, que estava acampado nos montes de Gileade. Então Labão e os homens se acamparam ali também.

[[v1-31-26]]

^<<v1-31-26,26>>^ Ele perguntou a Jacó: "Que foi que você fez? Não só me enganou como também raptou minhas filhas como se fossem prisioneiras de guerra.

[[v1-31-27]]

^<<v1-31-27,27>>^ Por que você me enganou, fugindo em segredo, sem avisar-me? Eu teria celebrado a sua partida com alegria e cantos, ao som dos tamborins e das harpas.

[[v1-31-28]]

^<<v1-31-28,28>>^ Você sequer me deixou beijar meus netos e minhas filhas para despedir-me deles. Você foi insensato.

[[v1-31-29]]

^<<v1-31-29,29>>^ Tenho poder para prejudicá-los; mas, na noite passada, o Deus do pai de vocês me advertiu: ‘Cuidado! Não diga nada a Jacó, não lhe faça promessas nem ameaças’.

[[v1-31-30]]

^<<v1-31-30,30>>^ Agora, se você partiu porque tinha saudade da casa de seu pai, por que roubou meus deuses? "

[[v1-31-31]]

^<<v1-31-31,31>>^ Jacó respondeu a Labão: "Tive medo, pois pensei que você tiraria suas filhas de mim à força.

[[v1-31-32]]

^<<v1-31-32,32>>^ Quanto aos seus deuses, quem for encontrado com eles não ficará vivo. Na presença dos nossos parentes, veja você mesmo se está aqui comigo qualquer coisa que lhe pertença, e, se estiver, leve-a de volta". Ora, Jacó não sabia que Raquel os havia roubado.

[[v1-31-33]]

^<<v1-31-33,33>>^ Então Labão entrou na tenda de Jacó, e nas tendas de Lia e de suas duas servas, mas nada encontrou. Depois de sair da tenda de Lia, entrou na tenda de Raquel.

[[v1-31-34]]

^<<v1-31-34,34>>^ Raquel tinha colocado os ídolos dentro da sela do seu camelo e estava sentada em cima. Labão vasculhou toda a tenda, mas nada encontrou.

[[v1-31-35]]

^<<v1-31-35,35>>^ Raquel disse ao pai: "Não se irrite, meu senhor, por não poder me levantar em sua presença, pois estou com o fluxo das mulheres". Ele procurou os ídolos, mas não os encontrou.

[[v1-31-36]]

^<<v1-31-36,36>>^ Jacó ficou irado e queixou-se a Labão: "Qual foi meu crime? Que pecado cometi para que você me persiga furiosamente?

[[v1-31-37]]

^<<v1-31-37,37>>^ Você já vasculhou tudo o que me pertence. Encontrou algo que lhe pertença? Então coloque tudo aqui na frente dos meus parentes e dos seus, e que eles julguem entre nós dois.

[[v1-31-38]]

^<<v1-31-38,38>>^ "Vinte anos estive com você. Suas ovelhas e cabras nunca abortaram, e jamais comi um só carneiro do seu rebanho.

[[v1-31-39]]

^<<v1-31-39,39>>^ Eu nunca levava a você os animais despedaçados por feras; eu mesmo assumia o prejuízo. E você pedia contas de todo animal roubado de dia ou de noite.

[[v1-31-40]]

^<<v1-31-40,40>>^ O calor me consumia de dia, e o frio, de noite, e o sono fugia dos meus olhos.

[[v1-31-41]]

^<<v1-31-41,41>>^ Foi assim nos vinte anos em que fiquei em sua casa. Trabalhei para você catorze anos em troca de suas duas filhas e seis anos por seus rebanhos, e dez vezes você alterou o meu salário.

[[v1-31-42]]

^<<v1-31-42,42>>^ Se o Deus de meu pai, o Deus de Abraão, o Temor de Isaque, não estivesse comigo, certamente você me despediria de mãos vazias. Mas Deus viu o meu sofrimento e o trabalho das minhas mãos e, na noite passada, ele manifestou a sua decisão".

[[v1-31-43]]

^<<v1-31-43,43>>^ Labão respondeu a Jacó: "As mulheres são minhas filhas, os filhos são meus, os rebanhos são meus. Tudo o que você vê é meu. Que posso fazer por essas minhas filhas ou pelos filhos que delas nasceram?

[[v1-31-44]]

^<<v1-31-44,44>>^ Façamos agora, eu e você, um acordo que sirva de testemunho entre nós dois".

[[v1-31-45]]

^<<v1-31-45,45>>^ Então Jacó tomou uma pedra e a colocou de pé como coluna.

[[v1-31-46]]

^<<v1-31-46,46>>^ E disse aos seus parentes: "Juntem algumas pedras". Eles apanharam pedras e as amontoaram. Depois comeram ali, ao lado do monte de pedras.

[[v1-31-47]]

^<<v1-31-47,47>>^ Labão o chamou Jegar-Saaduta, e Jacó o chamou Galeede.

[[v1-31-48]]

^<<v1-31-48,48>>^ Labão disse: "Este monte de pedras é uma testemunha entre mim e você, no dia de hoje". Por isso foi chamado Galeede.

[[v1-31-49]]

^<<v1-31-49,49>>^ Foi também chamado Mispá, porque ele declarou: "Que o Senhor nos vigie, a mim e a você, quando estivermos separados um do outro.

[[v1-31-50]]

^<<v1-31-50,50>>^ Se você maltratar minhas filhas ou menosprezá-las, tomando outras mulheres além delas, ainda que ninguém saiba, lembre-se de que Deus é testemunha entre mim e você".

[[v1-31-51]]

^<<v1-31-51,51>>^ Disse ainda Labão a Jacó: "Aqui estão este monte de pedras e esta coluna que coloquei entre mim e você.

[[v1-31-52]]

^<<v1-31-52,52>>^ São testemunhas de que não passarei para o lado de lá para prejudicá-lo, nem você passará para o lado de cá para prejudicar-me.

[[v1-31-53]]

^<<v1-31-53,53>>^ Que o Deus de Abraão, o Deus de Naor, o Deus do pai deles, julgue entre nós". Então Jacó fez um juramento em nome do Temor de seu pai Isaque.

[[v1-31-54]]

^<<v1-31-54,54>>^ Ofereceu um sacrifício no monte e chamou os parentes que lá estavam para uma refeição. Depois de comerem, passaram a noite ali.

[[v1-31-55]]

^<<v1-31-55,55>>^ Na manhã seguinte, Labão beijou seus netos e suas filhas e os abençoou, e depois voltou para a sua terra.

'''

xref:001-genesis/001-genesis-030.adoc#v1-30-0[&#60; Capítulo Anterior] | <<v1-31-0,Topo>> | xref:001-genesis/001-genesis-032.adoc#v1-32-0[Próximo Capítulo &#62;]