include::./index.adoc[]

[[v1-18-0]]
=== Gênesis, 18
// nvi ?, NVI - Nova Versão Internacional

[[v1-18-1]]

^<<v1-18-1,1>>^ O Senhor apareceu a Abraão perto dos carvalhos de Manre, quando ele estava sentado à entrada de sua tenda, na hora mais quente do dia.

[[v1-18-2]]

^<<v1-18-2,2>>^ Abraão ergueu os olhos e viu três homens em pé, a pouca distância. Quando os viu, saiu da entrada de sua tenda, correu ao encontro deles e curvou-se até ao chão.

[[v1-18-3]]

^<<v1-18-3,3>>^ Disse ele: "Meu senhor, se mereço o seu favor, não passe pelo seu servo sem fazer uma parada.

[[v1-18-4]]

^<<v1-18-4,4>>^ Mandarei buscar um pouco d’água para que lavem os pés e descansem debaixo desta árvore.

[[v1-18-5]]

^<<v1-18-5,5>>^ Vou trazer-lhes também o que comer, para que recobrem forças e prossigam pelo caminho, agora que já chegaram até este seu servo". "Está bem; faça como está dizendo", responderam.

[[v1-18-6]]

^<<v1-18-6,6>>^ Abraão foi apressadamente à tenda e disse a Sara: "Depressa, pegue três medidas da melhor farinha, amasse-a e faça uns pães".

[[v1-18-7]]

^<<v1-18-7,7>>^ Depois correu ao rebanho e escolheu o melhor novilho, e o deu a um servo, que se apressou em prepará-lo.

[[v1-18-8]]

^<<v1-18-8,8>>^ Trouxe então coalhada, leite e o novilho que havia sido preparado, e os serviu. Enquanto comiam, ele ficou perto deles em pé, debaixo da árvore.

[[v1-18-9]]

^<<v1-18-9,9>>^ "Onde está Sara, sua mulher? ", perguntaram. "Ali na tenda", respondeu ele.

[[v1-18-10]]

^<<v1-18-10,10>>^ Então disse o Senhor: "Voltarei a você na primavera, e Sara, sua mulher, terá um filho". Sara escutava à entrada da tenda, atrás dele.

[[v1-18-11]]

^<<v1-18-11,11>>^ Abraão e Sara já eram velhos, de idade bem avançada, e Sara já tinha passado da idade de ter filhos.

[[v1-18-12]]

^<<v1-18-12,12>>^ Por isso riu consigo mesma, quando pensou: "Depois de já estar velha e meu senhor já idoso, ainda terei esse prazer? "

[[v1-18-13]]

^<<v1-18-13,13>>^ Mas o Senhor disse a Abraão: "Por que Sara riu e disse: ‘Poderei realmente dar à luz, agora que sou idosa? ’

[[v1-18-14]]

^<<v1-18-14,14>>^ Existe alguma coisa impossível para o Senhor? Na primavera voltarei a você, e Sara terá um filho".

[[v1-18-15]]

^<<v1-18-15,15>>^ Sara teve medo, e por isso mentiu: "Eu não ri". Mas ele disse: "Não negue, você riu".

[[v1-18-16]]

^<<v1-18-16,16>>^ Quando os homens se levantaram para partir, avistaram lá embaixo Sodoma; e Abraão os acompanhou para despedir-se.

[[v1-18-17]]

^<<v1-18-17,17>>^ Então o Senhor disse: "Esconderei de Abraão o que estou para fazer?

[[v1-18-18]]

^<<v1-18-18,18>>^ Abraão será o pai de uma nação grande e poderosa, e por meio dele todas as nações da terra serão abençoadas.

[[v1-18-19]]

^<<v1-18-19,19>>^ Pois eu o escolhi, para que ordene aos seus filhos e aos seus descendentes que se conservem no caminho do Senhor, fazendo o que é justo e direito, para que o Senhor faça vir a Abraão o que lhe havia prometido".

[[v1-18-20]]

^<<v1-18-20,20>>^ Disse-lhe, pois, o Senhor: "As acusações contra Sodoma e Gomorra são tantas e o seu pecado é tão grave

[[v1-18-21]]

^<<v1-18-21,21>>^ que descerei para ver se o que eles têm feito corresponde ao que tenho ouvido. Se não, eu saberei".

[[v1-18-22]]

^<<v1-18-22,22>>^ Os homens partiram dali e foram para Sodoma, mas Abraão permaneceu diante do Senhor.

[[v1-18-23]]

^<<v1-18-23,23>>^ Abraão aproximou-se dele e disse: "Exterminarás o justo com o ímpio?

[[v1-18-24]]

^<<v1-18-24,24>>^ E se houver cinqüenta justos na cidade? Ainda a destruirás e não pouparás o lugar por amor aos cinqüenta justos que nele estão?

[[v1-18-25]]

^<<v1-18-25,25>>^ Longe de ti fazer tal coisa: matar o justo com o ímpio, tratando o justo e o ímpio da mesma maneira. Longe de ti! Não agirá com justiça o Juiz de toda a terra? "

[[v1-18-26]]

^<<v1-18-26,26>>^ Respondeu o Senhor: "Se eu encontrar cinqüenta justos em Sodoma, pouparei a cidade toda por amor a eles".

[[v1-18-27]]

^<<v1-18-27,27>>^ Mas Abraão tornou a falar: "Sei que já fui muito ousado a ponto de falar ao Senhor, eu que não passo de pó e cinza.

[[v1-18-28]]

^<<v1-18-28,28>>^ Ainda assim pergunto: E se faltarem cinco para completar os cinqüenta justos? Destruirás a cidade por causa dos cinco? " Disse ele: "Se encontrar ali quarenta e cinco, não a destruirei".

[[v1-18-29]]

^<<v1-18-29,29>>^ "E se encontrares apenas quarenta? ", insistiu Abraão. Ele respondeu: "Por amor aos quarenta não a destruirei".

[[v1-18-30]]

^<<v1-18-30,30>>^ Então continuou ele: "Não te ires, Senhor, mas permite-me falar. E se apenas trinta forem encontrados ali? " Ele respondeu: "Se encontrar trinta, não a destruirei".

[[v1-18-31]]

^<<v1-18-31,31>>^ Prosseguiu Abraão: "Agora que já fui tão ousado falando ao Senhor, pergunto: E se apenas vinte forem encontrados ali? " Ele respondeu: "Por amor aos vinte não a destruirei".

[[v1-18-32]]

^<<v1-18-32,32>>^ Então Abraão disse ainda: "Não te ires, Senhor, mas permite-me falar só mais uma vez. E se apenas dez forem encontrados? " Ele respondeu: "Por amor aos dez não a destruirei".

[[v1-18-33]]

^<<v1-18-33,33>>^ Tendo acabado de falar com Abraão, o Senhor partiu, e Abraão voltou para casa.

'''

xref:001-genesis/001-genesis-017.adoc#v1-17-0[&#60; Capítulo Anterior] | <<v1-18-0,Topo>> | xref:001-genesis/001-genesis-019.adoc#v1-19-0[Próximo Capítulo &#62;]