include::./index.adoc[]

[[v1-40-0]]
=== Gênesis, 40
// nvi ?, NVI - Nova Versão Internacional

[[v1-40-1]]

^<<v1-40-1,1>>^ Algum tempo depois, o copeiro e o padeiro do rei do Egito fizeram uma ofensa ao seu senhor, o rei do Egito.

[[v1-40-2]]

^<<v1-40-2,2>>^ O faraó irou-se com os dois oficiais, o chefe dos copeiros e o chefe dos padeiros,

[[v1-40-3]]

^<<v1-40-3,3>>^ e mandou prendê-los na casa do capitão da guarda, na prisão em que José estava.

[[v1-40-4]]

^<<v1-40-4,4>>^ O capitão da guarda os deixou aos cuidados de José, que os servia. Depois de certo tempo,

[[v1-40-5]]

^<<v1-40-5,5>>^ o copeiro e o padeiro do rei do Egito, que estavam na prisão, sonharam. Cada um teve um sonho, ambos na mesma noite, e cada sonho tinha a sua própria interpretação.

[[v1-40-6]]

^<<v1-40-6,6>>^ Quando José foi vê-los na manhã seguinte, notou que estavam abatidos.

[[v1-40-7]]

^<<v1-40-7,7>>^ Por isso perguntou aos oficiais do faraó que também estavam presos na casa do seu senhor: "Por que hoje vocês estão com o semblante triste? "

[[v1-40-8]]

^<<v1-40-8,8>>^ Eles responderam: "Tivemos sonhos, mas não há quem os interprete". Disse-lhes José: "Não são de Deus as interpretações? Contem-me os sonhos".

[[v1-40-9]]

^<<v1-40-9,9>>^ Então o chefe dos copeiros contou o seu sonho a José: "Em meu sonho vi diante de mim uma videira,

[[v1-40-10]]

^<<v1-40-10,10>>^ com três ramos. Ela brotou, floresceu e deu uvas que amadureciam em cachos.

[[v1-40-11]]

^<<v1-40-11,11>>^ A taça do faraó estava em minha mão. Peguei as uvas, e as espremi na taça do faraó, e a entreguei em sua mão".

[[v1-40-12]]

^<<v1-40-12,12>>^ Disse-lhe José: "Esta é a interpretação: Os três ramos são três dias.

[[v1-40-13]]

^<<v1-40-13,13>>^ Dentro de três dias o faraó vai exaltá-lo e restaurá-lo à sua posição; e você servirá a taça na mão dele, como costumava fazer quando era seu copeiro.

[[v1-40-14]]

^<<v1-40-14,14>>^ Quando tudo estiver indo bem com você, lembre-se de mim e seja bondoso comigo; fale de mim ao faraó e tire-me desta prisão,

[[v1-40-15]]

^<<v1-40-15,15>>^ pois fui trazido à força da terra dos hebreus, e também aqui nada fiz para ser jogado neste calabouço".

[[v1-40-16]]

^<<v1-40-16,16>>^ Ouvindo o chefe dos padeiros essa interpretação favorável, disse a José: "Eu também tive um sonho: Sobre a minha cabeça havia três cestas de pão branco.

[[v1-40-17]]

^<<v1-40-17,17>>^ Na cesta de cima havia todo tipo de pães e doces que o faraó aprecia, mas as aves vinham comer da cesta que eu trazia na cabeça".

[[v1-40-18]]

^<<v1-40-18,18>>^ E disse José: "Esta é a interpretação: As três cestas são três dias.

[[v1-40-19]]

^<<v1-40-19,19>>^ Dentro de três dias o faraó vai decapitá-lo e pendurá-lo numa árvore. E as aves comerão a sua carne".

[[v1-40-20]]

^<<v1-40-20,20>>^ Três dias depois era o aniversário do faraó, e ele ofereceu um banquete a todos os seus conselheiros. Na presença deles reapresentou o chefe dos copeiros e o chefe dos padeiros:

[[v1-40-21]]

^<<v1-40-21,21>>^ Restaurou à sua posição o chefe dos copeiros, de modo que ele voltou a ser aquele que servia a taça do faraó,

[[v1-40-22]]

^<<v1-40-22,22>>^ mas ao chefe dos padeiros mandou enforcar, como José lhes dissera em sua interpretação.

[[v1-40-23]]

^<<v1-40-23,23>>^ O chefe dos copeiros, porém, não se lembrou de José; ao contrário, esqueceu-se dele.

'''

xref:001-genesis/001-genesis-039.adoc#v1-39-0[&#60; Capítulo Anterior] | <<v1-40-0,Topo>> | xref:001-genesis/001-genesis-041.adoc#v1-41-0[Próximo Capítulo &#62;]