include::./index.adoc[]

[[v1-9-0]]
=== Gênesis, 9
// nvi ?, NVI - Nova Versão Internacional

[[v1-9-1]]

^<<v1-9-1,1>>^ Deus abençoou Noé e seus filhos, dizendo-lhes: "Sejam férteis, multipliquem-se e encham a terra.

[[v1-9-2]]

^<<v1-9-2,2>>^ Todos os animais da terra tremerão de medo diante de vocês: os animais selvagens, as aves do céu, as criaturas que se movem rente ao chão e os peixes do mar; eles estão entregues em suas mãos.

[[v1-9-3]]

^<<v1-9-3,3>>^ Tudo o que vive e se move lhes servirá de alimento. Assim como lhes dei os vegetais, agora lhes dou todas as coisas.

[[v1-9-4]]

^<<v1-9-4,4>>^ "Mas não comam carne com sangue, que é vida.

[[v1-9-5]]

^<<v1-9-5,5>>^ A todo que derramar sangue, tanto homem como animal, pedirei contas; a cada um pedirei contas da vida do seu próximo.

[[v1-9-6]]

^<<v1-9-6,6>>^ "Quem derramar sangue do homem, pelo homem seu sangue será derramado; porque à imagem de Deus foi o homem criado.

[[v1-9-7]]

^<<v1-9-7,7>>^ "Mas vocês, sejam férteis e multipliquem-se; espalhem-se pela terra e proliferem nela".

[[v1-9-8]]

^<<v1-9-8,8>>^ Então disse Deus a Noé e a seus filhos, que estavam com ele:

[[v1-9-9]]

^<<v1-9-9,9>>^ "Vou estabelecer a minha aliança com vocês e com os seus futuros descendentes,

[[v1-9-10]]

^<<v1-9-10,10>>^ e com todo ser vivo que está com vocês: as aves, os rebanhos domésticos e os animais selvagens, todos os que saíram da arca com vocês, todos os seres vivos da terra.

[[v1-9-11]]

^<<v1-9-11,11>>^ Estabeleço uma aliança com vocês: Nunca mais será ceifada nenhuma forma de vida pelas águas de um dilúvio; nunca mais haverá dilúvio para destruir a terra".

[[v1-9-12]]

^<<v1-9-12,12>>^ E Deus prosseguiu: "Este é o sinal da aliança que estou fazendo entre mim e vocês e com todos os seres vivos que estão com vocês, para todas as gerações futuras:

[[v1-9-13]]

^<<v1-9-13,13>>^ o meu arco que coloquei nas nuvens. Será o sinal da minha aliança com a terra.

[[v1-9-14]]

^<<v1-9-14,14>>^ Quando eu trouxer nuvens sobre a terra e nelas aparecer o arco-íris,

[[v1-9-15]]

^<<v1-9-15,15>>^ então me lembrarei da minha aliança com vocês e com os seres vivos de todas as espécies. Nunca mais as águas se tornarão um dilúvio para destruir toda forma de vida.

[[v1-9-16]]

^<<v1-9-16,16>>^ Toda vez que o arco-íris estiver nas nuvens, olharei para ele e me lembrarei da aliança eterna entre Deus e todos os seres vivos de todas as espécies que vivem na terra".

[[v1-9-17]]

^<<v1-9-17,17>>^ Concluindo, disse Deus a Noé: "Esse é o sinal da aliança que estabeleci entre mim e toda forma de vida que há sobre a terra".

[[v1-9-18]]

^<<v1-9-18,18>>^ Os filhos de Noé que saíram da arca foram Sem, Cam e Jafé. Cam é o pai de Canaã.

[[v1-9-19]]

^<<v1-9-19,19>>^ Esses foram os três filhos de Noé; a partir deles toda a terra foi povoada.

[[v1-9-20]]

^<<v1-9-20,20>>^ Noé, que era agricultor, foi o primeiro a plantar uma vinha.

[[v1-9-21]]

^<<v1-9-21,21>>^ Bebeu do vinho, embriagou-se e ficou nu dentro da sua tenda.

[[v1-9-22]]

^<<v1-9-22,22>>^ Cam, pai de Canaã, viu a nudez do pai e foi contar aos dois irmãos que estavam do lado de fora.

[[v1-9-23]]

^<<v1-9-23,23>>^ Mas Sem e Jafé pegaram a capa, levantaram-na sobre os ombros e, andando de costas para não verem a nudez do pai, cobriram-no.

[[v1-9-24]]

^<<v1-9-24,24>>^ Quando Noé acordou do efeito do vinho e descobriu o que seu filho caçula lhe havia feito,

[[v1-9-25]]

^<<v1-9-25,25>>^ disse: "Maldito seja Canaã! Escravo de escravos será para os seus irmãos".

[[v1-9-26]]

^<<v1-9-26,26>>^ Disse ainda: "Bendito seja o Senhor, o Deus de Sem! Seja Canaã seu escravo.

[[v1-9-27]]

^<<v1-9-27,27>>^ Amplie Deus o território de Jafé; habite ele nas tendas de Sem, e seja Canaã seu escravo".

[[v1-9-28]]

^<<v1-9-28,28>>^ Depois do Dilúvio Noé viveu trezentos e cinqüenta anos.

[[v1-9-29]]

^<<v1-9-29,29>>^ Viveu ao todo novecentos e cinqüenta anos e morreu.

'''

xref:001-genesis/001-genesis-008.adoc#v1-8-0[&#60; Capítulo Anterior] | <<v1-9-0,Topo>> | xref:001-genesis/001-genesis-010.adoc#v1-10-0[Próximo Capítulo &#62;]