include::./index.adoc[]

[[v1-46-0]]
=== Gênesis, 46
// nvi ?, NVI - Nova Versão Internacional

[[v1-46-1]]

^<<v1-46-1,1>>^ Israel partiu com tudo o que lhe pertencia. Ao chegar a Berseba, ofereceu sacrifícios ao Deus de Isaque, seu pai.

[[v1-46-2]]

^<<v1-46-2,2>>^ E Deus falou a Israel por meio de uma visão noturna: "Jacó! Jacó! " "Eis-me aqui", respondeu ele.

[[v1-46-3]]

^<<v1-46-3,3>>^ "Eu sou Deus, o Deus de seu pai", disse ele. "Não tenha medo de descer ao Egito, porque lá farei de você uma grande nação.

[[v1-46-4]]

^<<v1-46-4,4>>^ Eu mesmo descerei ao Egito com você e certamente o trarei de volta. E a mão de José fechará os seus olhos. "

[[v1-46-5]]

^<<v1-46-5,5>>^ Então Jacó partiu de Berseba. Os filhos de Israel levaram seu pai Jacó, seus filhos e as suas mulheres nas carruagens que o faraó tinha enviado.

[[v1-46-6]]

^<<v1-46-6,6>>^ Também levaram os seus rebanhos e os bens que tinham adquirido em Canaã. Assim Jacó foi para o Egito com toda a sua descendência.

[[v1-46-7]]

^<<v1-46-7,7>>^ Levou consigo para o Egito seus filhos, seus netos, suas filhas e suas netas, isto é, todos os seus descendentes.

[[v1-46-8]]

^<<v1-46-8,8>>^ Estes são os nomes dos israelitas, Jacó e seus descendentes, que foram para o Egito: Rúben, o filho mais velho de Jacó.

[[v1-46-9]]

^<<v1-46-9,9>>^ Estes foram os filhos de Rúben: Enoque, Palu, Hezrom e Carmi.

[[v1-46-10]]

^<<v1-46-10,10>>^ Estes foram os filhos de Simeão: Jemuel, Jamim, Oade, Jaquim, Zoar e Saul, filho de uma cananéia.

[[v1-46-11]]

^<<v1-46-11,11>>^ Estes foram os filhos de Levi: Gérson, Coate e Merari.

[[v1-46-12]]

^<<v1-46-12,12>>^ Estes foram os filhos de Judá: Er, Onã, Selá, Perez e Zerá. Er e Onã morreram na terra de Canaã. Estes foram os filhos de Perez: Hezrom e Hamul.

[[v1-46-13]]

^<<v1-46-13,13>>^ Estes foram os filhos de Issacar: Tolá, Puá, Jasube e Sinrom.

[[v1-46-14]]

^<<v1-46-14,14>>^ Estes foram os filhos de Zebulom: Serede, Elom e Jaleel.

[[v1-46-15]]

^<<v1-46-15,15>>^ Foram esses os filhos que Lia deu a Jacó em Padã-Arã, além de sua filha Diná. Seus descendentes eram ao todo trinta e três.

[[v1-46-16]]

^<<v1-46-16,16>>^ Estes foram os filhos de Gade: Zefom, Hagi, Suni, Esbom, Eri, Arodi e Areli.

[[v1-46-17]]

^<<v1-46-17,17>>^ Estes foram os filhos de Aser: Imna, Isvá, Isvi e Berias, e a irmã deles, Sera. Estes foram os filhos de Berias: Héber e Malquiel.

[[v1-46-18]]

^<<v1-46-18,18>>^ Foram esses os dezesseis descendentes que Zilpa, serva que Labão tinha dado à sua filha Lia, deu a Jacó.

[[v1-46-19]]

^<<v1-46-19,19>>^ Estes foram os filhos de Raquel, mulher de Jacó: José e Benjamim.

[[v1-46-20]]

^<<v1-46-20,20>>^ Azenate, filha de Potífera, sacerdote de Om, deu dois filhos a José no Egito: Manassés e Efraim.

[[v1-46-21]]

^<<v1-46-21,21>>^ Estes foram os filhos de Benjamim: Belá, Bequer, Asbel, Gera, Naamã, Eí, Rôs, Mupim, Hupim e Arde.

[[v1-46-22]]

^<<v1-46-22,22>>^ Foram esses os catorze descendentes que Raquel deu a Jacó.

[[v1-46-23]]

^<<v1-46-23,23>>^ O filho de Dã foi Husim.

[[v1-46-24]]

^<<v1-46-24,24>>^ Estes foram os filhos de Naftali: Jazeel, Guni, Jezer e Silém.

[[v1-46-25]]

^<<v1-46-25,25>>^ Foram esses os sete descendentes que Bila, serva que Labão tinha dado à sua filha Raquel, deu a Jacó.

[[v1-46-26]]

^<<v1-46-26,26>>^ Todos os que foram para o Egito com Jacó, todos os seus descendentes, sem contar as mulheres de seus filhos, totalizaram sessenta e seis pessoas.

[[v1-46-27]]

^<<v1-46-27,27>>^ Com mais os dois filhos que nasceram a José no Egito, os membros da família de Jacó que foram para o Egito chegaram a setenta.

[[v1-46-28]]

^<<v1-46-28,28>>^ Ora, Jacó enviou Judá à sua frente a José, para saber como ir a Gósen. Quando lá chegaram,

[[v1-46-29]]

^<<v1-46-29,29>>^ José, de carruagem pronta, partiu para Gósen para encontrar-se com seu pai Israel. Assim que o viu, correu para abraçá-lo e, abraçado a ele, chorou longamente.

[[v1-46-30]]

^<<v1-46-30,30>>^ Israel disse a José: "Agora já posso morrer, pois vi o seu rosto e sei que você ainda está vivo".

[[v1-46-31]]

^<<v1-46-31,31>>^ Então José disse aos seus irmãos e a toda família de seu pai: "Vou partir e informar ao faraó que os meus irmãos e toda a família de meu pai, que viviam em Canaã, vieram para cá.

[[v1-46-32]]

^<<v1-46-32,32>>^ Direi que os homens são pastores, cuidam de rebanhos, e trouxeram consigo suas ovelhas, seus bois e tudo quanto lhes pertence.

[[v1-46-33]]

^<<v1-46-33,33>>^ Quando o faraó mandar chamá-los e perguntar: ‘Em que vocês trabalham? ’,

[[v1-46-34]]

^<<v1-46-34,34>>^ respondam-lhe assim: ‘Teus servos criam rebanhos desde pequenos, como o fizeram nossos antepassados’. Assim lhes será permitido habitar na região de Gósen, pois todos os pastores são desprezados pelos egípcios".

'''

xref:001-genesis/001-genesis-045.adoc#v1-45-0[&#60; Capítulo Anterior] | <<v1-46-0,Topo>> | xref:001-genesis/001-genesis-047.adoc#v1-47-0[Próximo Capítulo &#62;]