include::./index.adoc[]

[[v1-21-0]]
=== Gênesis, 21
// nvi ?, NVI - Nova Versão Internacional

[[v1-21-1]]

^<<v1-21-1,1>>^ O Senhor foi bondoso com Sara, como lhe dissera, e fez por ela o que prometera.

[[v1-21-2]]

^<<v1-21-2,2>>^ Sara engravidou e deu um filho a Abraão em sua velhice, na época fixada por Deus em sua promessa.

[[v1-21-3]]

^<<v1-21-3,3>>^ Abraão deu o nome de Isaque ao filho que Sara lhe dera.

[[v1-21-4]]

^<<v1-21-4,4>>^ Quando seu filho Isaque tinha oito dias de vida, Abraão o circuncidou, conforme Deus lhe havia ordenado.

[[v1-21-5]]

^<<v1-21-5,5>>^ Estava ele com cem anos de idade quando lhe nasceu Isaque, seu filho.

[[v1-21-6]]

^<<v1-21-6,6>>^ E Sara disse: "Deus me encheu de riso, e todos os que souberem disso rirão comigo".

[[v1-21-7]]

^<<v1-21-7,7>>^ E acrescentou: "Quem diria a Abraão que Sara amamentaria filhos? Contudo eu lhe dei um filho em sua velhice! "

[[v1-21-8]]

^<<v1-21-8,8>>^ O menino cresceu e foi desmamado. No dia em que Isaque foi desmamado, Abraão deu uma grande festa.

[[v1-21-9]]

^<<v1-21-9,9>>^ Sara, porém, viu que o filho que Hagar, a egípcia, dera a Abraão estava rindo de Isaque,

[[v1-21-10]]

^<<v1-21-10,10>>^ e disse a Abraão: "Livre-se daquela escrava e do seu filho, porque ele jamais será herdeiro com o meu filho Isaque".

[[v1-21-11]]

^<<v1-21-11,11>>^ Isso perturbou demais Abraão, pois envolvia um filho seu.

[[v1-21-12]]

^<<v1-21-12,12>>^ Mas Deus lhe disse: "Não se perturbe por causa do menino e da escrava. Atenda a tudo o que Sara lhe pedir, porque será por meio de Isaque que a sua descendência há de ser considerada.

[[v1-21-13]]

^<<v1-21-13,13>>^ Mas também do filho da escrava farei um povo; afinal ele é seu descendente".

[[v1-21-14]]

^<<v1-21-14,14>>^ Na manhã seguinte, Abraão pegou alguns pães e uma vasilha de couro cheia d’água, entregou-os a Hagar e, tendo-os colocado nos ombros dela, despediu-a com o menino. Ela se pôs a caminho e ficou vagando pelo deserto de Berseba.

[[v1-21-15]]

^<<v1-21-15,15>>^ Quando acabou a água da vasilha, ela deixou o menino debaixo de um arbusto

[[v1-21-16]]

^<<v1-21-16,16>>^ e foi sentar-se perto dali, à distância de um tiro de flecha, porque pensou: "Não posso ver o menino morrer". Sentada ali perto, começou a chorar.

[[v1-21-17]]

^<<v1-21-17,17>>^ Deus ouviu o choro do menino, e o anjo de Deus, do céu, chamou Hagar e lhe disse: "O que a aflige, Hagar? Não tenha medo; Deus ouviu o menino chorar, lá onde você o deixou.

[[v1-21-18]]

^<<v1-21-18,18>>^ Levante o menino e tome-o pela mão, porque dele farei um grande povo".

[[v1-21-19]]

^<<v1-21-19,19>>^ Então Deus lhe abriu os olhos, e ela viu uma fonte. Foi até lá, encheu de água a vasilha e deu de beber ao menino.

[[v1-21-20]]

^<<v1-21-20,20>>^ Deus estava com o menino. Ele cresceu, viveu no deserto e tornou-se flecheiro.

[[v1-21-21]]

^<<v1-21-21,21>>^ Vivia no deserto de Parã, e sua mãe conseguiu-lhe uma mulher da terra do Egito.

[[v1-21-22]]

^<<v1-21-22,22>>^ Naquela ocasião, Abimeleque, acompanhado de Ficol, comandante do seu exército, disse a Abraão: "Deus está contigo em tudo o que fazes.

[[v1-21-23]]

^<<v1-21-23,23>>^ Agora, jura-me, diante de Deus, que não vais enganar-me, nem a mim nem a meus filhos e descendentes. Trata a nação que te acolheu como estrangeiro com a mesma bondade com que te tratei".

[[v1-21-24]]

^<<v1-21-24,24>>^ Respondeu Abraão: "Eu juro! "

[[v1-21-25]]

^<<v1-21-25,25>>^ Todavia Abraão reclamou com Abimeleque a respeito de um poço que os servos de Abimeleque lhe tinham tomado à força.

[[v1-21-26]]

^<<v1-21-26,26>>^ Mas Abimeleque lhe respondeu: "Não sei quem fez isso. Nunca me disseste nada, e só fiquei sabendo disso hoje".

[[v1-21-27]]

^<<v1-21-27,27>>^ Então Abraão trouxe ovelhas e bois, deu-os a Abimeleque, e os dois firmaram um acordo.

[[v1-21-28]]

^<<v1-21-28,28>>^ Abraão separou sete ovelhas do rebanho,

[[v1-21-29]]

^<<v1-21-29,29>>^ pelo que Abimeleque lhe perguntou: "Que significam estas sete ovelhas que separaste das demais? "

[[v1-21-30]]

^<<v1-21-30,30>>^ Ele respondeu: "Aceita estas sete ovelhas de minhas mãos como testemunho de que eu cavei este poço".

[[v1-21-31]]

^<<v1-21-31,31>>^ Por isso aquele lugar foi chamado Berseba, porque ali os dois fizeram um juramento.

[[v1-21-32]]

^<<v1-21-32,32>>^ Firmado esse acordo em Berseba, Abimeleque e Ficol, comandante das suas tropas, voltaram para a terra dos filisteus.

[[v1-21-33]]

^<<v1-21-33,33>>^ Abraão, por sua vez, plantou uma tamargueira em Berseba e ali invocou o nome do Senhor, o Deus Eterno.

[[v1-21-34]]

^<<v1-21-34,34>>^ E morou Abraão na terra dos filisteus por longo tempo.

'''

xref:001-genesis/001-genesis-020.adoc#v1-20-0[&#60; Capítulo Anterior] | <<v1-21-0,Topo>> | xref:001-genesis/001-genesis-022.adoc#v1-22-0[Próximo Capítulo &#62;]