include::./index.adoc[]

[[v1-29-0]]
=== Gênesis, 29
// nvi ?, NVI - Nova Versão Internacional

[[v1-29-1]]

^<<v1-29-1,1>>^ Então Jacó seguiu viagem e chegou à Mesopotâmia.

[[v1-29-2]]

^<<v1-29-2,2>>^ Certo dia, olhando ao redor, viu um poço no campo e três rebanhos de ovelhas deitadas por perto, pois os rebanhos bebiam daquele poço, que era tapado por uma grande pedra.

[[v1-29-3]]

^<<v1-29-3,3>>^ Por isso, quando todos os rebanhos se reuniam ali, os pastores rolavam a pedra da boca do poço e davam água às ovelhas. Depois recolocavam a pedra em seu lugar, sobre o poço.

[[v1-29-4]]

^<<v1-29-4,4>>^ Jacó perguntou aos pastores: "Meus amigos, de onde são vocês? " "Somos de Harã", responderam.

[[v1-29-5]]

^<<v1-29-5,5>>^ "Vocês conhecem Labão, neto de Naor? ", perguntou-lhes Jacó. Eles responderam: "Sim, nós o conhecemos".

[[v1-29-6]]

^<<v1-29-6,6>>^ Então Jacó perguntou: "Ele vai bem? " "Sim, vai bem", disseram eles, "e ali vem sua filha Raquel com as ovelhas".

[[v1-29-7]]

^<<v1-29-7,7>>^ Disse ele: "Olhem, o sol ainda vai alto e não é hora de recolher os rebanhos. Dêem de beber às ovelhas e levem-nas de volta ao pasto".

[[v1-29-8]]

^<<v1-29-8,8>>^ Mas eles responderam: "Não podemos, enquanto os rebanhos não se agruparem e a pedra não for removida da boca do poço. Só então daremos de beber às ovelhas".

[[v1-29-9]]

^<<v1-29-9,9>>^ Ele ainda estava conversando, quando chegou Raquel com as ovelhas de seu pai, pois ela era pastora.

[[v1-29-10]]

^<<v1-29-10,10>>^ Quando Jacó viu Raquel, filha de Labão, irmão de sua mãe, e as ovelhas de Labão, aproximou-se, removeu a pedra da boca do poço e deu de beber às ovelhas de seu tio Labão.

[[v1-29-11]]

^<<v1-29-11,11>>^ Depois Jacó beijou Raquel e começou a chorar bem alto.

[[v1-29-12]]

^<<v1-29-12,12>>^ Então contou a Raquel que era parente do pai dela e filho de Rebeca. E ela foi correndo contar tudo a seu pai.

[[v1-29-13]]

^<<v1-29-13,13>>^ Logo que Labão ouviu as notícias acerca de Jacó, seu sobrinho, correu ao seu encontro, abraçou-o e o beijou. Depois, levou-o para casa, e Jacó contou-lhe tudo o que havia ocorrido.

[[v1-29-14]]

^<<v1-29-14,14>>^ Então Labão lhe disse: "Você é sangue do meu sangue". Já fazia um mês que Jacó estava na casa de Labão,

[[v1-29-15]]

^<<v1-29-15,15>>^ quando este lhe disse: "Só por ser meu parente você vai trabalhar de graça? Diga-me qual deve ser o seu salário".

[[v1-29-16]]

^<<v1-29-16,16>>^ Ora, Labão tinha duas filhas; o nome da mais velha era Lia, e o da mais nova, Raquel.

[[v1-29-17]]

^<<v1-29-17,17>>^ Lia tinha olhos meigos, mas Raquel era bonita e atraente.

[[v1-29-18]]

^<<v1-29-18,18>>^ Como Jacó gostava muito de Raquel, disse: "Trabalharei sete anos em troca de Raquel, sua filha mais nova".

[[v1-29-19]]

^<<v1-29-19,19>>^ Labão respondeu: "Será melhor dá-la a você do que a algum outro homem. Fique aqui comigo".

[[v1-29-20]]

^<<v1-29-20,20>>^ Então Jacó trabalhou sete anos por Raquel, mas lhe pareceram poucos dias, pelo tanto que a amava.

[[v1-29-21]]

^<<v1-29-21,21>>^ Então disse Jacó a Labão: "Entregue-me a minha mulher. Cumpri o prazo previsto e quero deitar-me com ela".

[[v1-29-22]]

^<<v1-29-22,22>>^ Então Labão reuniu todo o povo daquele lugar e deu uma festa.

[[v1-29-23]]

^<<v1-29-23,23>>^ Mas quando a noite chegou, deu sua filha Lia a Jacó, e Jacó deitou-se com ela.

[[v1-29-24]]

^<<v1-29-24,24>>^ Labão também entregou sua serva Zilpa à sua filha, para que ficasse a serviço dela.

[[v1-29-25]]

^<<v1-29-25,25>>^ Quando chegou a manhã, lá estava Lia. Então Jacó disse a Labão: "Que foi que você me fez? Eu não trabalhei por Raquel? Por que você me enganou? "

[[v1-29-26]]

^<<v1-29-26,26>>^ Labão respondeu: "Aqui não é costume entregar em casamento a filha mais nova antes da mais velha.

[[v1-29-27]]

^<<v1-29-27,27>>^ Deixe passar esta semana de núpcias e lhe daremos também a mais nova, em troca de mais sete anos de trabalho".

[[v1-29-28]]

^<<v1-29-28,28>>^ Jacó concordou. Passou aquela semana de núpcias com Lia, e Labão lhe deu sua filha Raquel por mulher.

[[v1-29-29]]

^<<v1-29-29,29>>^ Labão deu a Raquel sua serva Bila, para que ficasse a serviço dela.

[[v1-29-30]]

^<<v1-29-30,30>>^ Jacó deitou-se também com Raquel, que era a sua preferida. E trabalhou para Labão outros sete anos.

[[v1-29-31]]

^<<v1-29-31,31>>^ Quando o Senhor viu que Lia era desprezada, concedeu-lhe filhos; Raquel, porém, era estéril.

[[v1-29-32]]

^<<v1-29-32,32>>^ Lia engravidou, deu à luz um filho, e deu-lhe o nome de Rúben, pois dizia: "O Senhor viu a minha infelicidade. Agora, certamente o meu marido me amará".

[[v1-29-33]]

^<<v1-29-33,33>>^ Lia engravidou de novo e, quando deu à luz outro filho, disse: "Porque o Senhor ouviu que sou desprezada, deu-me também este". Pelo que o chamou Simeão.

[[v1-29-34]]

^<<v1-29-34,34>>^ De novo engravidou e, quando deu à luz mais um filho, disse: "Agora, finalmente, meu marido se apegará a mim, porque já lhe dei três filhos". Por isso deu-lhe o nome de Levi.

[[v1-29-35]]

^<<v1-29-35,35>>^ Engravidou ainda outra vez e, quando deu à luz mais outro filho, disse: "Desta vez louvarei ao SENHOR". Assim deu-lhe o nome de Judá. Então parou de ter filhos.

'''

xref:001-genesis/001-genesis-028.adoc#v1-28-0[&#60; Capítulo Anterior] | <<v1-29-0,Topo>> | xref:001-genesis/001-genesis-030.adoc#v1-30-0[Próximo Capítulo &#62;]