include::./index.adoc[]

[[v1-45-0]]
=== Gênesis, 45
// nvi ?, NVI - Nova Versão Internacional

[[v1-45-1]]

^<<v1-45-1,1>>^ A essa altura, José já não podia mais conter-se diante de todos os que ali estavam, e gritou: "Façam sair a todos! " Assim, ninguém mais estava presente quando José se revelou a seus irmãos.

[[v1-45-2]]

^<<v1-45-2,2>>^ E ele se pôs a chorar tão alto que os egípcios o ouviram, e a notícia chegou ao palácio do faraó.

[[v1-45-3]]

^<<v1-45-3,3>>^ Então disse José a seus irmãos: "Eu sou José! Meu pai ainda está vivo? " Mas os seus irmãos ficaram tão pasmados diante dele que não conseguiam responder-lhe.

[[v1-45-4]]

^<<v1-45-4,4>>^ "Cheguem mais perto", disse José a seus irmãos. Quando eles se aproximaram, disse-lhes: "Eu sou José, seu irmão, aquele que vocês venderam ao Egito!

[[v1-45-5]]

^<<v1-45-5,5>>^ Agora, não se aflijam nem se recriminem por terem me vendido para cá, pois foi para salvar vidas que Deus me enviou adiante de vocês.

[[v1-45-6]]

^<<v1-45-6,6>>^ Já houve dois anos de fome na terra, e nos próximos cinco anos não haverá cultivo nem colheita.

[[v1-45-7]]

^<<v1-45-7,7>>^ Mas Deus me enviou à frente de vocês para lhes preservar um remanescente nesta terra e para salvar-lhes as vidas com grande livramento.

[[v1-45-8]]

^<<v1-45-8,8>>^ "Assim, não foram vocês que me mandaram para cá, mas sim o próprio Deus. Ele me tornou ministro do faraó, e me fez administrador de todo o palácio e governador de todo o Egito.

[[v1-45-9]]

^<<v1-45-9,9>>^ Voltem depressa a meu pai e digam-lhe: Assim diz o seu filho José: Deus me fez senhor de todo o Egito. Vem para cá, não te demores.

[[v1-45-10]]

^<<v1-45-10,10>>^ Tu viverás na região de Gósen e ficarás perto de mim — tu, os teus filhos, os teus netos, as tuas ovelhas, os teus bois e todos os teus bens.

[[v1-45-11]]

^<<v1-45-11,11>>^ Eu te sustentarei ali, porque ainda haverá cinco anos de fome. Do contrário, tu, a tua família e todos os teus rebanhos acabarão na miséria.

[[v1-45-12]]

^<<v1-45-12,12>>^ "Vocês estão vendo com os seus próprios olhos, e meu irmão Benjamim também, que realmente sou eu que estou falando com vocês.

[[v1-45-13]]

^<<v1-45-13,13>>^ Contem a meu pai quanta honra me prestam no Egito e tudo o que vocês mesmos testemunharam. E tragam meu pai para cá depressa".

[[v1-45-14]]

^<<v1-45-14,14>>^ Então ele se lançou chorando sobre o seu irmão Benjamim e o abraçou, e Benjamim também o abraçou, chorando.

[[v1-45-15]]

^<<v1-45-15,15>>^ Em seguida beijou todos os seus irmãos e chorou com eles. E só depois os seus irmãos conseguiram conversar com ele.

[[v1-45-16]]

^<<v1-45-16,16>>^ Quando se ouviu no palácio do faraó que os irmãos de José haviam chegado, o faraó e todos os seus conselheiros se alegraram.

[[v1-45-17]]

^<<v1-45-17,17>>^ Disse então o faraó a José: "Diga a seus irmãos que ponham as cargas nos seus animais, voltem para a terra de Canaã

[[v1-45-18]]

^<<v1-45-18,18>>^ e retornem para cá, trazendo seu pai e suas famílias. Eu lhes darei o melhor da terra do Egito e vocês poderão desfrutar a fartura desta terra.

[[v1-45-19]]

^<<v1-45-19,19>>^ "Mande-os também levar carruagens do Egito para trazerem as suas mulheres, os seus filhos e seu pai.

[[v1-45-20]]

^<<v1-45-20,20>>^ Não se preocupem com os seus bens, pois o melhor de todo o Egito será de vocês".

[[v1-45-21]]

^<<v1-45-21,21>>^ Assim fizeram os filhos de Israel. José lhes providenciou carruagens, como o faraó tinha ordenado, e também mantimentos para a viagem.

[[v1-45-22]]

^<<v1-45-22,22>>^ A cada um deu uma muda de roupa nova, mas a Benjamim deu trezentas peças de prata e cinco mudas de roupa nova.

[[v1-45-23]]

^<<v1-45-23,23>>^ E a seu pai enviou dez jumentos carregados com o melhor do que havia no Egito e dez jumentas carregadas de trigo, pão e outras provisões para a viagem.

[[v1-45-24]]

^<<v1-45-24,24>>^ Depois despediu-se dos seus irmãos e, ao partirem, disse-lhes: "Não briguem pelo caminho! "

[[v1-45-25]]

^<<v1-45-25,25>>^ Assim partiram do Egito e voltaram a seu pai Jacó, na terra de Canaã,

[[v1-45-26]]

^<<v1-45-26,26>>^ e lhe deram a notícia: "José ainda está vivo! Na verdade ele é o governador de todo o Egito". O coração de Jacó quase parou! Não podia acreditar neles.

[[v1-45-27]]

^<<v1-45-27,27>>^ Mas, quando lhe relataram tudo o que José lhes dissera, e vendo Jacó, seu pai, as carruagens que José enviara para buscá-lo, seu espírito reviveu.

[[v1-45-28]]

^<<v1-45-28,28>>^ E Israel disse: "Basta! Meu filho José ainda está vivo. Irei vê-lo antes que eu morra".

'''

xref:001-genesis/001-genesis-044.adoc#v1-44-0[&#60; Capítulo Anterior] | <<v1-45-0,Topo>> | xref:001-genesis/001-genesis-046.adoc#v1-46-0[Próximo Capítulo &#62;]