include::./index.adoc[]

[[v1-2-0]]
=== Gênesis, 2
// nvi ?, NVI - Nova Versão Internacional

[[v1-2-1]]

^<<v1-2-1,1>>^ Assim foram concluídos os céus e a terra, e tudo o que neles há.

[[v1-2-2]]

^<<v1-2-2,2>>^ No sétimo dia Deus já havia concluído a obra que realizara, e nesse dia descansou.

[[v1-2-3]]

^<<v1-2-3,3>>^ Abençoou Deus o sétimo dia e o santificou, porque nele descansou de toda a obra que realizara na criação.

[[v1-2-4]]

^<<v1-2-4,4>>^ Esta é a história das origens dos céus e da terra, no tempo em que foram criados: Quando o Senhor Deus fez a terra e os céus,

[[v1-2-5]]

^<<v1-2-5,5>>^ ainda não tinha brotado nenhum arbusto no campo, e nenhuma planta havia germinado, porque o Senhor Deus ainda não tinha feito chover sobre a terra, e também não havia homem para cultivar o solo.

[[v1-2-6]]

^<<v1-2-6,6>>^ Todavia brotava água da terra e irrigava toda a superfície do solo.

[[v1-2-7]]

^<<v1-2-7,7>>^ Então o Senhor Deus formou o homem do pó da terra e soprou em suas narinas o fôlego de vida, e o homem se tornou um ser vivente.

[[v1-2-8]]

^<<v1-2-8,8>>^ Ora, o Senhor Deus tinha plantado um jardim no Éden, para os lados do leste; e ali colocou o homem que formara.

[[v1-2-9]]

^<<v1-2-9,9>>^ O Senhor Deus fez nascer então do solo todo tipo de árvores agradáveis aos olhos e boas para alimento. E no meio do jardim estavam a árvore da vida e a árvore do conhecimento do bem e do mal.

[[v1-2-10]]

^<<v1-2-10,10>>^ No Éden nascia um rio que irrigava o jardim, e depois se dividia em quatro.

[[v1-2-11]]

^<<v1-2-11,11>>^ O nome do primeiro é Pisom. Ele percorre toda a terra de Havilá, onde existe ouro.

[[v1-2-12]]

^<<v1-2-12,12>>^ O ouro daquela terra é excelente; lá também existem o bdélio e a pedra de ônix.

[[v1-2-13]]

^<<v1-2-13,13>>^ O segundo, que percorre toda a terra de Cuxe, é o Giom.

[[v1-2-14]]

^<<v1-2-14,14>>^ O terceiro, que corre pelo lado leste da Assíria, é o Tigre. E o quarto rio é o Eufrates.

[[v1-2-15]]

^<<v1-2-15,15>>^ O Senhor Deus colocou o homem no jardim do Éden para cuidar dele e cultivá-lo.

[[v1-2-16]]

^<<v1-2-16,16>>^ E o Senhor Deus ordenou ao homem: "Coma livremente de qualquer árvore do jardim,

[[v1-2-17]]

^<<v1-2-17,17>>^ mas não coma da árvore do conhecimento do bem e do mal, porque no dia em que dela comer, certamente você morrerá".

[[v1-2-18]]

^<<v1-2-18,18>>^ Então o Senhor Deus declarou: "Não é bom que o homem esteja só; farei para ele alguém que o auxilie e lhe corresponda".

[[v1-2-19]]

^<<v1-2-19,19>>^ Depois que formou da terra todos os animais do campo e todas as aves do céu, o Senhor Deus os trouxe ao homem para ver como este lhes chamaria; e o nome que o homem desse a cada ser vivo, esse seria o seu nome.

[[v1-2-20]]

^<<v1-2-20,20>>^ Assim o homem deu nomes a todos os rebanhos domésticos, às aves do céu e a todos os animais selvagens. Todavia não se encontrou para o homem alguém que o auxiliasse e lhe correspondesse.

[[v1-2-21]]

^<<v1-2-21,21>>^ Então o Senhor Deus fez o homem cair em profundo sono e, enquanto este dormia, tirou-lhe uma das costelas, fechando o lugar com carne.

[[v1-2-22]]

^<<v1-2-22,22>>^ Com a costela que havia tirado do homem, o Senhor Deus fez uma mulher e a trouxe a ele.

[[v1-2-23]]

^<<v1-2-23,23>>^ Disse então o homem: "Esta, sim, é osso dos meus ossos e carne da minha carne! Ela será chamada mulher, porque do homem foi tirada".

[[v1-2-24]]

^<<v1-2-24,24>>^ Por essa razão, o homem deixará pai e mãe e se unirá à sua mulher, e eles se tornarão uma só carne.

[[v1-2-25]]

^<<v1-2-25,25>>^ O homem e sua mulher viviam nus, e não sentiam vergonha.

'''

xref:001-genesis/001-genesis-001.adoc#v1-1-0[&#60; Capítulo Anterior] | <<v1-2-0,Topo>> | xref:001-genesis/001-genesis-003.adoc#v1-3-0[Próximo Capítulo &#62;]