include::./index.adoc[]

[[v1-34-0]]
=== Gênesis, 34
// nvi ?, NVI - Nova Versão Internacional

[[v1-34-1]]

^<<v1-34-1,1>>^ Certa vez, Diná, a filha que Lia dera a Jacó, saiu para conhecer as mulheres daquela terra.

[[v1-34-2]]

^<<v1-34-2,2>>^ Siquém, filho de Hamor, o heveu, governador daquela região, viu-a, agarrou-a e violentou-a.

[[v1-34-3]]

^<<v1-34-3,3>>^ Mas o seu coração foi atraído por Diná, filha de Jacó, e ele amou a moça e falou-lhe com ternura.

[[v1-34-4]]

^<<v1-34-4,4>>^ Por isso Siquém foi dizer a seu pai Hamor: "Consiga-me aquela moça para que seja minha mulher".

[[v1-34-5]]

^<<v1-34-5,5>>^ Quando Jacó soube que sua filha Diná tinha sido desonrada, seus filhos estavam no campo, com os rebanhos; por isso esperou calado, até que regressassem.

[[v1-34-6]]

^<<v1-34-6,6>>^ Então Hamor, pai de Siquém, foi conversar com Jacó.

[[v1-34-7]]

^<<v1-34-7,7>>^ Quando os filhos de Jacó voltaram do campo e souberam de tudo, ficaram profundamente entristecidos e irados, porque Siquém tinha cometido um ato vergonhoso em Israel, ao deitar-se com a filha de Jacó — coisa que não se faz.

[[v1-34-8]]

^<<v1-34-8,8>>^ Mas Hamor lhes disse: "Meu filho Siquém apaixonou-se pela filha de vocês. Por favor, entreguem-na a ele para que seja sua mulher.

[[v1-34-9]]

^<<v1-34-9,9>>^ Casem-se entre nós; dêem-nos suas filhas e tomem para si as nossas.

[[v1-34-10]]

^<<v1-34-10,10>>^ Estabeleçam-se entre nós. A terra está aberta para vocês: Habitem-na, façam comércio nela e adquiram propriedades".

[[v1-34-11]]

^<<v1-34-11,11>>^ Então Siquém disse ao pai e aos irmãos de Diná: "Concedam-me este favor, e eu lhes darei o que me pedirem.

[[v1-34-12]]

^<<v1-34-12,12>>^ Aumentem quanto quiserem o preço e o presente pela noiva, e pagarei o que me pedirem. Tão-somente me dêem a moça por mulher".

[[v1-34-13]]

^<<v1-34-13,13>>^ Os filhos de Jacó, porém, responderam com falsidade a Siquém e a seu pai Hamor, por ter Siquém desonrado Diná, a irmã deles.

[[v1-34-14]]

^<<v1-34-14,14>>^ Disseram: "Não podemos fazer isso; jamais entregaremos nossa irmã a um homem que não seja circuncidado. Seria uma vergonha para nós.

[[v1-34-15]]

^<<v1-34-15,15>>^ Daremos nosso consentimento a vocês com uma condição: que vocês se tornem como nós, circuncidando todos os do sexo masculino.

[[v1-34-16]]

^<<v1-34-16,16>>^ Só então lhes daremos as nossas filhas e poderemos casar-nos com as suas. Nós nos estabeleceremos entre vocês e seremos um só povo.

[[v1-34-17]]

^<<v1-34-17,17>>^ Mas se não aceitarem circuncidar-se, tomaremos nossa irmã e partiremos".

[[v1-34-18]]

^<<v1-34-18,18>>^ A proposta deles pareceu boa a Hamor e a seu filho Siquém.

[[v1-34-19]]

^<<v1-34-19,19>>^ O jovem, que era o mais respeitado de todos os da casa de seu pai, não demorou em cumprir o que pediram, porque realmente gostava da filha de Jacó.

[[v1-34-20]]

^<<v1-34-20,20>>^ Assim Hamor e seu filho Siquém dirigiram-se à porta da cidade para conversar com os seus concidadãos. E disseram:

[[v1-34-21]]

^<<v1-34-21,21>>^ "Esses homens são de paz. Permitam que eles habitem em nossa terra e façam comércio entre nós; a terra tem bastante lugar para eles. Poderemos casar com as suas filhas, e eles com as nossas.

[[v1-34-22]]

^<<v1-34-22,22>>^ Mas eles só consentirão em viver conosco como um só povo sob a condição de que todos os nossos homens sejam circuncidados, como eles.

[[v1-34-23]]

^<<v1-34-23,23>>^ Lembrem-se de que os seus rebanhos, os seus bens e todos os seus outros animais passarão a ser nossos. Aceitemos então a condição para que se estabeleçam em nosso meio".

[[v1-34-24]]

^<<v1-34-24,24>>^ Todos os que saíram para reunir-se à porta da cidade concordaram com Hamor e com seu filho Siquém, e todos os homens e meninos da cidade foram circuncidados.

[[v1-34-25]]

^<<v1-34-25,25>>^ Três dias depois, quando ainda sofriam dores, dois filhos de Jacó, Simeão e Levi, irmãos de Diná, pegaram suas espadas e atacaram a cidade desprevenida, matando todos os homens.

[[v1-34-26]]

^<<v1-34-26,26>>^ Mataram ao fio da espada Hamor e seu filho Siquém, tiraram Diná da casa de Siquém e partiram.

[[v1-34-27]]

^<<v1-34-27,27>>^ Vieram então os outros filhos de Jacó e, passando pelos corpos, saquearam a cidade onde sua irmã tinha sido desonrada.

[[v1-34-28]]

^<<v1-34-28,28>>^ Apoderaram-se das ovelhas, dos bois e dos jumentos, e de tudo o que havia na cidade e no campo.

[[v1-34-29]]

^<<v1-34-29,29>>^ Levaram as mulheres e as crianças, e saquearam todos os bens e tudo o que havia nas casas.

[[v1-34-30]]

^<<v1-34-30,30>>^ Então Jacó disse a Simeão e a Levi: "Vocês me puseram em grandes apuros, atraindo sobre mim o ódio dos cananeus e dos ferezeus, habitantes desta terra. Somos poucos, e se eles juntarem suas forças e nos atacarem, eu e a minha família seremos destruídos".

[[v1-34-31]]

^<<v1-34-31,31>>^ Mas eles responderam: "Está certo ele tratar nossa irmã como uma prostituta? "

'''

xref:001-genesis/001-genesis-033.adoc#v1-33-0[&#60; Capítulo Anterior] | <<v1-34-0,Topo>> | xref:001-genesis/001-genesis-035.adoc#v1-35-0[Próximo Capítulo &#62;]