include::./index.adoc[]

[[v1-6-0]]
=== Gênesis, 6
// nvi ?, NVI - Nova Versão Internacional

[[v1-6-1]]

^<<v1-6-1,1>>^ Quando os homens começaram a multiplicar-se na terra e lhes nasceram filhas,

[[v1-6-2]]

^<<v1-6-2,2>>^ os filhos de Deus viram que as filhas dos homens eram bonitas e escolheram para si aquelas que lhes agradaram.

[[v1-6-3]]

^<<v1-6-3,3>>^ Então disse o Senhor: "Por causa da perversidade do homem, meu Espírito não contenderá com ele para sempre; e ele só viverá cento e vinte anos".

[[v1-6-4]]

^<<v1-6-4,4>>^ Naqueles dias havia nefilins na terra, e também posteriormente, quando os filhos de Deus possuíram as filhas dos homens e elas lhes deram filhos. Eles foram os heróis do passado, homens famosos.

[[v1-6-5]]

^<<v1-6-5,5>>^ O Senhor viu que a perversidade do homem tinha aumentado na terra e que toda a inclinação dos pensamentos do seu coração era sempre e somente para o mal.

[[v1-6-6]]

^<<v1-6-6,6>>^ Então o Senhor arrependeu-se de ter feito o homem sobre a terra; e isso cortou-lhe o coração.

[[v1-6-7]]

^<<v1-6-7,7>>^ Disse o Senhor: "Farei desaparecer da face da terra o homem que criei, os homens e também os animais grandes, os animais pequenos e as aves do céu. Arrependo-me de havê-los feito".

[[v1-6-8]]

^<<v1-6-8,8>>^ A Noé, porém, o Senhor mostrou benevolência.

[[v1-6-9]]

^<<v1-6-9,9>>^ Esta é a história da família de Noé: Noé era homem justo, íntegro entre o povo da sua época; ele andava com Deus.

[[v1-6-10]]

^<<v1-6-10,10>>^ Noé gerou três filhos: Sem, Cam e Jafé.

[[v1-6-11]]

^<<v1-6-11,11>>^ Ora, a terra estava corrompida aos olhos de Deus e cheia de violência.

[[v1-6-12]]

^<<v1-6-12,12>>^ Ao ver como a terra se corrompera, pois toda a humanidade havia corrompido a sua conduta,

[[v1-6-13]]

^<<v1-6-13,13>>^ Deus disse a Noé: "Darei fim a todos os seres humanos, porque a terra encheu-se de violência por causa deles. Eu os destruirei juntamente com a terra.

[[v1-6-14]]

^<<v1-6-14,14>>^ Você, porém, fará uma arca de madeira de cipreste; divida-a em compartimentos e revista-a de piche por dentro e por fora.

[[v1-6-15]]

^<<v1-6-15,15>>^ Faça-a com cento e trinta e cinco metros de comprimento, vinte e dois metros e meio de largura e treze metros e meio de altura.

[[v1-6-16]]

^<<v1-6-16,16>>^ Faça-lhe um teto com um vão de quarenta e cinco centímetros entre o teto e corpo da arca. Coloque uma porta lateral na arca e faça um andar superior, um médio e um inferior.

[[v1-6-17]]

^<<v1-6-17,17>>^ "Eis que vou trazer águas sobre a terra, o Dilúvio, para destruir debaixo do céu toda criatura que tem fôlego de vida. Tudo o que há na terra perecerá.

[[v1-6-18]]

^<<v1-6-18,18>>^ Mas com você estabelecerei a minha aliança, e você entrará na arca com seus filhos, sua mulher e as mulheres de seus filhos.

[[v1-6-19]]

^<<v1-6-19,19>>^ Faça entrar na arca um casal de cada um dos seres vivos, macho e fêmea, para conservá-los vivos com você.

[[v1-6-20]]

^<<v1-6-20,20>>^ De cada espécie de ave, de cada espécie de animal grande e de cada espécie de animal pequeno que se move rente ao chão virá um casal a você para que sejam conservados vivos.

[[v1-6-21]]

^<<v1-6-21,21>>^ E armazene todo tipo de alimento, para que você e eles tenham mantimento".

[[v1-6-22]]

^<<v1-6-22,22>>^ Noé fez tudo exatamente como Deus lhe tinha ordenado.

'''

xref:001-genesis/001-genesis-005.adoc#v1-5-0[&#60; Capítulo Anterior] | <<v1-6-0,Topo>> | xref:001-genesis/001-genesis-007.adoc#v1-7-0[Próximo Capítulo &#62;]