include::./index.adoc[]

[[v1-20-0]]
=== Gênesis, 20
// nvi ?, NVI - Nova Versão Internacional

[[v1-20-1]]

^<<v1-20-1,1>>^ Abraão partiu dali para a região do Neguebe e foi viver entre Cades e Sur. Depois morou algum tempo em Gerar.

[[v1-20-2]]

^<<v1-20-2,2>>^ Ele dizia que Sara, sua mulher, era sua irmã. Então Abimeleque, rei de Gerar, mandou buscar Sara e tomou-a para si.

[[v1-20-3]]

^<<v1-20-3,3>>^ Certa noite Deus veio a Abimeleque num sonho e lhe disse: "Você morrerá! A mulher que você tomou é casada".

[[v1-20-4]]

^<<v1-20-4,4>>^ Mas Abimeleque, que ainda não havia tocado nela, disse: "Senhor, destruirias um povo inocente?

[[v1-20-5]]

^<<v1-20-5,5>>^ Não foi ele que me disse: ‘Ela é minha irmã’? E ela também não disse: ‘Ele é meu irmão’? O que fiz foi de coração puro e de mãos limpas".

[[v1-20-6]]

^<<v1-20-6,6>>^ Então Deus lhe respondeu no sonho: "Sim, eu sei que você fez isso de coração puro. Eu mesmo impedi que você pecasse contra mim e por isso não lhe permiti tocá-la.

[[v1-20-7]]

^<<v1-20-7,7>>^ Agora devolva a mulher ao marido dela. Ele é profeta, e orará em seu favor, para que você não morra. Mas se não a devolver, esteja certo de que você e todos os seus morrerão".

[[v1-20-8]]

^<<v1-20-8,8>>^ Na manhã seguinte, Abimeleque convocou todos os seus conselheiros e, quando lhes contou tudo o que acontecera, tiveram muito medo.

[[v1-20-9]]

^<<v1-20-9,9>>^ Depois Abimeleque chamou Abraão e disse: "O que fizeste conosco? Em que foi que pequei contra ti para que trouxesses tamanha culpa sobre mim e sobre o meu reino? O que me fizeste não se faz a ninguém! "

[[v1-20-10]]

^<<v1-20-10,10>>^ E perguntou Abimeleque a Abraão: "O que te levou a fazer isso? "

[[v1-20-11]]

^<<v1-20-11,11>>^ Abraão respondeu: "Eu disse a mim mesmo: Certamente ninguém teme a Deus neste lugar, e irão matar-me por causa da minha mulher.

[[v1-20-12]]

^<<v1-20-12,12>>^ Além disso, na verdade ela é minha irmã por parte de pai, mas não por parte de mãe; e veio a ser minha mulher.

[[v1-20-13]]

^<<v1-20-13,13>>^ E quando Deus me fez sair errante da casa de meu pai, eu disse a ela: Assim você me provará sua lealdade: em qualquer lugar aonde formos, diga que sou seu irmão".

[[v1-20-14]]

^<<v1-20-14,14>>^ Então Abimeleque trouxe ovelhas e bois, servos e servas, deu-os a Abraão e devolveu-lhe Sara, sua mulher.

[[v1-20-15]]

^<<v1-20-15,15>>^ E disse Abimeleque: "Minha terra está diante de ti; podes ficar onde quiseres".

[[v1-20-16]]

^<<v1-20-16,16>>^ A Sara ele disse: "Estou dando a seu irmão mil peças de prata, para reparar a ofensa feita a você diante de todos os seus; assim todos saberão que você é inocente".

[[v1-20-17]]

^<<v1-20-17,17>>^ A seguir Abraão orou a Deus, e Deus curou Abimeleque, sua mulher e suas servas, de forma que puderam novamente ter filhos,

[[v1-20-18]]

^<<v1-20-18,18>>^ porque o Senhor havia tornado estéreis todas as mulheres da casa de Abimeleque por causa de Sara, mulher de Abraão.

'''

xref:001-genesis/001-genesis-019.adoc#v1-19-0[&#60; Capítulo Anterior] | <<v1-20-0,Topo>> | xref:001-genesis/001-genesis-021.adoc#v1-21-0[Próximo Capítulo &#62;]