include::./index.adoc[]

[[v1-8-0]]
=== Gênesis, 8
// nvi ?, NVI - Nova Versão Internacional

[[v1-8-1]]

^<<v1-8-1,1>>^ Então Deus lembrou-se de Noé e de todos os animais selvagens e rebanhos domésticos que estavam com ele na arca, e enviou então um vento sobre a terra, e as águas começaram a baixar.

[[v1-8-2]]

^<<v1-8-2,2>>^ As fontes das profundezas e as comportas do céu se fecharam, e a chuva parou.

[[v1-8-3]]

^<<v1-8-3,3>>^ As águas foram baixando pouco a pouco sobre a terra. Ao fim de cento e cinqüenta dias, as águas tinham diminuído,

[[v1-8-4]]

^<<v1-8-4,4>>^ e, no décimo sétimo dia do sétimo mês, a arca pousou nas montanhas de Ararate.

[[v1-8-5]]

^<<v1-8-5,5>>^ As águas continuaram a baixar até o décimo mês, e no primeiro dia do décimo mês apareceram os topos das montanhas.

[[v1-8-6]]

^<<v1-8-6,6>>^ Passados quarenta dias, Noé abriu a janela que fizera na arca.

[[v1-8-7]]

^<<v1-8-7,7>>^ Esperando que a terra já tivesse aparecido, Noé soltou um corvo, mas este ficou dando voltas.

[[v1-8-8]]

^<<v1-8-8,8>>^ Depois soltou uma pomba para ver se as águas tinham diminuído na superfície da terra.

[[v1-8-9]]

^<<v1-8-9,9>>^ Mas a pomba não encontrou lugar onde pousar os pés porque as águas ainda cobriam toda a superfície da terra e, por isso, voltou para a arca, a Noé. Ele estendeu a mão para fora, apanhou a pomba e a trouxe de volta para dentro da arca.

[[v1-8-10]]

^<<v1-8-10,10>>^ Noé esperou mais sete dias e soltou novamente a pomba.

[[v1-8-11]]

^<<v1-8-11,11>>^ Ao entardecer, quando a pomba voltou, trouxe em seu bico uma folha nova de oliveira. Noé então ficou sabendo que as águas tinham diminuído sobre a terra.

[[v1-8-12]]

^<<v1-8-12,12>>^ Esperou ainda outros sete dias e de novo soltou a pomba, mas desta vez ela não voltou.

[[v1-8-13]]

^<<v1-8-13,13>>^ No primeiro dia do primeiro mês do ano seiscentos e um da vida de Noé, secaram-se as águas na terra. Noé então removeu o teto da arca e viu que a superfície da terra estava seca.

[[v1-8-14]]

^<<v1-8-14,14>>^ No vigésimo sétimo dia do segundo mês, a terra estava completamente seca.

[[v1-8-15]]

^<<v1-8-15,15>>^ Então Deus disse a Noé:

[[v1-8-16]]

^<<v1-8-16,16>>^ "Saia da arca, você e sua mulher, seus filhos e as mulheres deles.

[[v1-8-17]]

^<<v1-8-17,17>>^ Faça que saiam também todos os animais que estão com você: as aves, os animais grandes e os animais pequenos que se movem rente ao chão. Faça-os sair para que se espalhem pela terra, sejam férteis e se multipliquem".

[[v1-8-18]]

^<<v1-8-18,18>>^ Então Noé saiu da arca com sua mulher e seus filhos e as mulheres deles,

[[v1-8-19]]

^<<v1-8-19,19>>^ e com todos os animais grandes, todos os animais pequenos que se movem rente ao chão e todas as aves. Tudo o que se move sobre a terra saiu da arca, uma espécie após outra.

[[v1-8-20]]

^<<v1-8-20,20>>^ Depois Noé construiu um altar dedicado ao Senhor e, tomando alguns animais e aves puros, ofereceu-os como holocausto, queimando-os sobre o altar.

[[v1-8-21]]

^<<v1-8-21,21>>^ O Senhor sentiu o aroma agradável e disse a si mesmo: "Nunca mais amaldiçoarei a terra por causa do homem, pois o seu coração é inteiramente inclinado para o mal desde a infância. E nunca mais destruirei todos os seres vivos como fiz desta vez.

[[v1-8-22]]

^<<v1-8-22,22>>^ "Enquanto durar a terra, plantio e colheita, frio e calor, verão e inverno, dia e noite jamais cessarão".

'''

xref:001-genesis/001-genesis-007.adoc#v1-7-0[&#60; Capítulo Anterior] | <<v1-8-0,Topo>> | xref:001-genesis/001-genesis-009.adoc#v1-9-0[Próximo Capítulo &#62;]