include::./index.adoc[]

[[v1-30-0]]
=== Gênesis, 30
// nvi ?, NVI - Nova Versão Internacional

[[v1-30-1]]

^<<v1-30-1,1>>^ Quando Raquel viu que não dava filhos a Jacó, teve inveja de sua irmã. Por isso disse a Jacó: "Dê-me filhos ou morrerei! "

[[v1-30-2]]

^<<v1-30-2,2>>^ Jacó ficou irritado e disse: "Por acaso estou no lugar de Deus, que a impediu de ter filhos? "

[[v1-30-3]]

^<<v1-30-3,3>>^ Então ela respondeu: "Aqui está Bila, minha serva. Deite-se com ela, para que tenha filhos em meu lugar e por meio dela eu também possa formar família".

[[v1-30-4]]

^<<v1-30-4,4>>^ Por isso ela deu a Jacó sua serva Bila por mulher. Ele deitou-se com ela,

[[v1-30-5]]

^<<v1-30-5,5>>^ Bila engravidou e deu-lhe um filho.

[[v1-30-6]]

^<<v1-30-6,6>>^ Então Raquel disse: "Deus me fez justiça, ouviu o meu clamor e deu-me um filho". Por isso deu-lhe o nome de Dã.

[[v1-30-7]]

^<<v1-30-7,7>>^ Bila, serva de Raquel, engravidou novamente e deu a Jacó o segundo filho.

[[v1-30-8]]

^<<v1-30-8,8>>^ Então disse Raquel: "Tive grande luta com minha irmã e venci". Pelo que o chamou Naftali.

[[v1-30-9]]

^<<v1-30-9,9>>^ Quando Lia viu que tinha parado de ter filhos, tomou sua serva Zilpa e a deu a Jacó por mulher.

[[v1-30-10]]

^<<v1-30-10,10>>^ Zilpa, serva de Lia, deu a Jacó um filho.

[[v1-30-11]]

^<<v1-30-11,11>>^ Então disse Lia: "Que grande sorte! " Por isso o chamou Gade.

[[v1-30-12]]

^<<v1-30-12,12>>^ Zilpa, serva de Lia, deu a Jacó mais um filho.

[[v1-30-13]]

^<<v1-30-13,13>>^ Então Lia exclamou: "Como sou feliz! As mulheres dirão que sou feliz". Por isso lhe deu o nome de Aser.

[[v1-30-14]]

^<<v1-30-14,14>>^ Durante a colheita do trigo, Rúben saiu ao campo, encontrou algumas mandrágoras e as trouxe a Lia, sua mãe. Então Raquel disse a Lia: "Dê-me algumas mandrágoras do seu filho".

[[v1-30-15]]

^<<v1-30-15,15>>^ Mas ela respondeu: "Não lhe foi suficiente tomar de mim o marido? Vai tomar também as mandrágoras que o meu filho trouxe? " Então disse Raquel: "Jacó se deitará com você esta noite, em troca das mandrágoras trazidas pelo seu filho".

[[v1-30-16]]

^<<v1-30-16,16>>^ Quando Jacó chegou do campo naquela tarde, Lia saiu ao seu encontro e lhe disse: "Hoje você me possuirá, pois eu comprei esse direito com as mandrágoras do meu filho". E naquela noite ele se deitou com ela.

[[v1-30-17]]

^<<v1-30-17,17>>^ Deus ouviu Lia, e ela engravidou e deu a Jacó o quinto filho.

[[v1-30-18]]

^<<v1-30-18,18>>^ Disse Lia: "Deus me recompensou por ter dado a minha serva ao meu marido". Por isso deu-lhe o nome de Issacar.

[[v1-30-19]]

^<<v1-30-19,19>>^ Lia engravidou de novo e deu a Jacó o sexto filho.

[[v1-30-20]]

^<<v1-30-20,20>>^ Disse Lia: "Deus presenteou-me com uma dádiva preciosa. Agora meu marido me tratará melhor; afinal já lhe dei seis filhos". Por isso deu-lhe o nome de Zebulom.

[[v1-30-21]]

^<<v1-30-21,21>>^ Algum tempo depois, ela deu à luz uma menina a quem chamou Diná.

[[v1-30-22]]

^<<v1-30-22,22>>^ Então Deus lembrou-se de Raquel. Deus ouviu o seu clamor e a tornou fértil.

[[v1-30-23]]

^<<v1-30-23,23>>^ Ela engravidou, e deu à luz um filho e disse: "Deus tirou de mim a minha humilhação".

[[v1-30-24]]

^<<v1-30-24,24>>^ Deu-lhe o nome de José e disse: "Que o Senhor me acrescente ainda outro filho".

[[v1-30-25]]

^<<v1-30-25,25>>^ Depois que Raquel deu à luz José, Jacó disse a Labão: "Deixe-me voltar para a minha terra natal.

[[v1-30-26]]

^<<v1-30-26,26>>^ Dê-me as minhas mulheres, pelas quais o servi, e os meus filhos, e partirei. Você bem sabe quanto trabalhei para você".

[[v1-30-27]]

^<<v1-30-27,27>>^ Mas Labão lhe disse: "Se mereço sua consideração, peço-lhe que fique. Por meio de adivinhação descobri que o Senhor me abençoou por sua causa".

[[v1-30-28]]

^<<v1-30-28,28>>^ E acrescentou: "Diga o seu salário, e eu lhe pagarei".

[[v1-30-29]]

^<<v1-30-29,29>>^ Jacó lhe respondeu: "Você sabe quanto trabalhei para você e como os seus rebanhos cresceram sob os meus cuidados.

[[v1-30-30]]

^<<v1-30-30,30>>^ O pouco que você possuía antes da minha chegada aumentou muito, pois o Senhor o abençoou depois que vim para cá. Contudo, quando farei algo em favor da minha própria família? "

[[v1-30-31]]

^<<v1-30-31,31>>^ Então Labão perguntou: "Que você quer que eu lhe dê? " "Não me dê coisa alguma", respondeu Jacó. "Voltarei a cuidar dos seus rebanhos se você concordar com o seguinte:

[[v1-30-32]]

^<<v1-30-32,32>>^ Hoje passarei por todos os seus rebanhos e tirarei do meio deles todas as ovelhas salpicadas e pintadas, todos os cordeiros pretos e todas as cabras pintadas e salpicadas. Eles serão o meu salário.

[[v1-30-33]]

^<<v1-30-33,33>>^ E a minha honestidade dará testemunho de mim no futuro, toda vez que você resolver verificar o meu salário. Se estiver em meu poder alguma cabra que não seja salpicada ou pintada, e algum cordeiro que não seja preto, poderá considerá-los roubados. "

[[v1-30-34]]

^<<v1-30-34,34>>^ E disse Labão: "De acordo. Seja como você disse".

[[v1-30-35]]

^<<v1-30-35,35>>^ Naquele mesmo dia Labão separou todos os bodes que tinham listras ou manchas brancas, todas as cabras que tinham pintas ou manchas brancas, e todos os cordeiros pretos e os colocou aos cuidados de seus filhos.

[[v1-30-36]]

^<<v1-30-36,36>>^ Afastou-se então de Jacó, à distância equivalente a três dias de viagem, e Jacó continuou a apascentar o resto dos rebanhos de Labão.

[[v1-30-37]]

^<<v1-30-37,37>>^ Jacó pegou galhos verdes de estoraque, amendoeira e plátano e neles fez listras brancas, descascando-os parcialmente e expondo assim a parte branca interna dos galhos.

[[v1-30-38]]

^<<v1-30-38,38>>^ Depois fixou os galhos descascados junto aos bebedouros, na frente dos rebanhos, no lugar onde costumavam beber água. Na época do cio, os rebanhos vinham beber e

[[v1-30-39]]

^<<v1-30-39,39>>^ se acasalavam diante dos galhos. E geravam filhotes listrados, salpicados e pintados.

[[v1-30-40]]

^<<v1-30-40,40>>^ Jacó separava os filhotes do rebanho dos demais, e fazia com que esses ficassem juntos dos animais listrados e pretos de Labão. Assim foi formando o seu próprio rebanho que separou do de Labão.

[[v1-30-41]]

^<<v1-30-41,41>>^ Toda vez que as fêmeas mais fortes estavam no cio, Jacó colocava os galhos nos bebedouros, em frente dos animais, para que estes se acasalassem perto dos galhos;

[[v1-30-42]]

^<<v1-30-42,42>>^ mas, se os animais eram fracos, não os colocava ali. Desse modo, os animais fracos ficavam para Labão e os mais fortes para Jacó.

[[v1-30-43]]

^<<v1-30-43,43>>^ Assim o homem ficou extremamente rico, tornando-se dono de grandes rebanhos e de servos e servas, camelos e jumentos.

'''

xref:001-genesis/001-genesis-029.adoc#v1-29-0[&#60; Capítulo Anterior] | <<v1-30-0,Topo>> | xref:001-genesis/001-genesis-031.adoc#v1-31-0[Próximo Capítulo &#62;]