include::./index.adoc[]

[[v1-19-0]]
=== Gênesis, 19
// nvi ?, NVI - Nova Versão Internacional

[[v1-19-1]]

^<<v1-19-1,1>>^ Os dois anjos chegaram a Sodoma ao anoitecer, e Ló estava sentado à porta da cidade. Quando os avistou, levantou-se e foi recebê-los. Prostrou-se, rosto em terra,

[[v1-19-2]]

^<<v1-19-2,2>>^ e disse: "Meus senhores, por favor, acompanhem-me à casa do seu servo. Lá poderão lavar os pés, passar a noite e, pela manhã, seguir caminho. Não, passaremos a noite na praça", responderam.

[[v1-19-3]]

^<<v1-19-3,3>>^ Mas ele insistiu tanto com eles que, finalmente, o acompanharam e entraram em sua casa. Ló mandou preparar-lhes uma refeição e assar pão sem fermento, e eles comeram.

[[v1-19-4]]

^<<v1-19-4,4>>^ Ainda não tinham ido deitar-se, quando todos os homens de toda parte da cidade de Sodoma, dos mais jovens aos mais velhos, cercaram a casa.

[[v1-19-5]]

^<<v1-19-5,5>>^ Chamaram Ló e lhe disseram: "Onde estão os homens que vieram à sua casa esta noite? Traga-os para nós aqui fora para que tenhamos relações com eles".

[[v1-19-6]]

^<<v1-19-6,6>>^ Ló saiu da casa, fechou a porta atrás de si

[[v1-19-7]]

^<<v1-19-7,7>>^ e lhes disse: "Não, meus amigos! Não façam essa perversidade!

[[v1-19-8]]

^<<v1-19-8,8>>^ Olhem, tenho duas filhas que ainda são virgens. Vou trazê-las para que vocês façam com elas o que bem entenderem. Mas não façam nada a estes homens, porque se acham debaixo da proteção do meu teto".

[[v1-19-9]]

^<<v1-19-9,9>>^ "Saia da frente! ", gritaram. E disseram: "Este homem chegou aqui como estrangeiro, e agora quer ser o juiz! Faremos a você pior do que a eles". Então empurraram Ló com violência e avançaram para arrombar a porta.

[[v1-19-10]]

^<<v1-19-10,10>>^ Nisso, os dois visitantes agarraram Ló, puxaram-no para dentro e fecharam a porta.

[[v1-19-11]]

^<<v1-19-11,11>>^ Depois feriram de cegueira os homens que estavam à porta da casa, dos mais jovens aos mais velhos, de maneira que não conseguiam encontrar a porta.

[[v1-19-12]]

^<<v1-19-12,12>>^ Os dois homens perguntaram a Ló: "Você tem mais alguém na cidade — genros, filhos ou filhas, ou qualquer outro parente? Tire-os daqui,

[[v1-19-13]]

^<<v1-19-13,13>>^ porque estamos para destruir este lugar. As acusações feitas ao Senhor contra este povo são tantas que ele nos enviou para destruir a cidade".

[[v1-19-14]]

^<<v1-19-14,14>>^ Então Ló foi falar com seus genros, os quais iam casar-se com suas filhas, e lhes disse: "Saiam imediatamente deste lugar, porque o Senhor está para destruir a cidade! " Mas eles pensaram que ele estava brincando.

[[v1-19-15]]

^<<v1-19-15,15>>^ Ao raiar do dia, os anjos insistiam com Ló, dizendo: "Depressa! Leve daqui sua mulher e suas duas filhas, ou vocês também serão mortos quando a cidade for castigada".

[[v1-19-16]]

^<<v1-19-16,16>>^ Tendo ele hesitado, os homens o agarraram pela mão, como também a mulher e as duas filhas, e os tiraram dali à força e os deixaram fora da cidade, porque o Senhor teve misericórdia deles.

[[v1-19-17]]

^<<v1-19-17,17>>^ Assim que os tiraram da cidade, um deles disse a Ló: "Fuja por amor à vida! Não olhe para trás e não pare em lugar nenhum da planície! Fuja para as montanhas, ou você será morto! "

[[v1-19-18]]

^<<v1-19-18,18>>^ Ló, porém, lhes disse: "Não, meu senhor!

[[v1-19-19]]

^<<v1-19-19,19>>^ Seu servo foi favorecido por sua benevolência, pois o senhor foi bondoso comigo, poupando-me a vida. Não posso fugir para as montanhas, se não esta calamidade cairá sobre mim, e morrerei.

[[v1-19-20]]

^<<v1-19-20,20>>^ Aqui perto há uma cidade pequena. Está tão próxima que dá para correr até lá. Deixe-me ir para lá! Mesmo sendo tão pequena, lá estarei a salvo".

[[v1-19-21]]

^<<v1-19-21,21>>^ "Está bem", respondeu ele. "Também lhe atenderei esse pedido; não destruirei a cidade da qual você fala.

[[v1-19-22]]

^<<v1-19-22,22>>^ Fuja depressa, porque nada poderei fazer enquanto você não chegar lá". Por isso a cidade foi chamada Zoar.

[[v1-19-23]]

^<<v1-19-23,23>>^ Quando Ló chegou a Zoar, o sol já havia nascido sobre a terra.

[[v1-19-24]]

^<<v1-19-24,24>>^ Então o Senhor, o próprio Senhor, fez chover do céu fogo e enxofre sobre Sodoma e Gomorra.

[[v1-19-25]]

^<<v1-19-25,25>>^ Assim ele destruiu aquelas cidades e toda a planície, com todos os habitantes das cidades e a vegetação.

[[v1-19-26]]

^<<v1-19-26,26>>^ Mas a mulher de Ló olhou para trás e se transformou numa coluna de sal.

[[v1-19-27]]

^<<v1-19-27,27>>^ Na manhã seguinte, Abraão se levantou e voltou ao lugar onde tinha estado diante do Senhor.

[[v1-19-28]]

^<<v1-19-28,28>>^ E olhou para Sodoma e Gomorra, para toda a planície, e viu uma densa fumaça subindo da terra, como fumaça de uma fornalha.

[[v1-19-29]]

^<<v1-19-29,29>>^ Quando Deus arrasou as cidades da planície, lembrou-se de Abraão e tirou Ló do meio da catástrofe que destruiu as cidades onde Ló vivia.

[[v1-19-30]]

^<<v1-19-30,30>>^ Ló partiu de Zoar com suas duas filhas e passou a viver nas montanhas, porque tinha medo de permanecer em Zoar. Ele e suas duas filhas ficaram morando numa caverna.

[[v1-19-31]]

^<<v1-19-31,31>>^ Um dia, a filha mais velha disse à mais jovem: "Nosso pai já está velho, e não há homens nas redondezas que nos possuam, segundo o costume de toda a terra.

[[v1-19-32]]

^<<v1-19-32,32>>^ Vamos dar vinho a nosso pai e então nos deitaremos com ele para preservar a linhagem de nosso pai".

[[v1-19-33]]

^<<v1-19-33,33>>^ Naquela noite deram vinho ao pai, e a filha mais velha entrou e se deitou com ele. E ele não percebeu quando ela se deitou nem quando se levantou.

[[v1-19-34]]

^<<v1-19-34,34>>^ No dia seguinte a filha mais velha disse à mais nova: "Ontem à noite deitei-me com meu pai. Vamos dar-lhe vinho também esta noite, e você se deitará com ele, para que preservemos a linhagem de nosso pai".

[[v1-19-35]]

^<<v1-19-35,35>>^ Então, outra vez deram vinho ao pai naquela noite, e a mais nova foi e se deitou com ele. E ele não percebeu quando ela se deitou nem quando se levantou.

[[v1-19-36]]

^<<v1-19-36,36>>^ Assim, as duas filhas de Ló engravidaram do próprio pai.

[[v1-19-37]]

^<<v1-19-37,37>>^ A mais velha teve um filho, e deu-lhe o nome de Moabe; este é o pai dos moabitas de hoje.

[[v1-19-38]]

^<<v1-19-38,38>>^ A mais nova também teve um filho, e deu-lhe o nome de Ben-Ami; este é o pai dos amonitas de hoje.

'''

xref:001-genesis/001-genesis-018.adoc#v1-18-0[&#60; Capítulo Anterior] | <<v1-19-0,Topo>> | xref:001-genesis/001-genesis-020.adoc#v1-20-0[Próximo Capítulo &#62;]