include::./index.adoc[]

[[v51-4-0]]
=== Colossenses, 4
// nvi ?, NVI - Nova Versão Internacional

[[v51-4-1]]

^<<v51-4-1,1>>^ Senhores, dêem aos seus escravos o que é justo e direito, sabendo que vocês também têm um Senhor no céu.

[[v51-4-2]]

^<<v51-4-2,2>>^ Dediquem-se à oração, estejam alertas e sejam agradecidos.

[[v51-4-3]]

^<<v51-4-3,3>>^ Ao mesmo tempo, orem também por nós, para que Deus abra uma porta para a nossa mensagem, a fim de que possamos proclamar o mistério de Cristo, pelo qual estou preso.

[[v51-4-4]]

^<<v51-4-4,4>>^ Orem para que eu possa manifestá-lo abertamente, como me cumpre fazê-lo.

[[v51-4-5]]

^<<v51-4-5,5>>^ Sejam sábios no procedimento para com os de fora; aproveitem ao máximo todas as oportunidades.

[[v51-4-6]]

^<<v51-4-6,6>>^ O seu falar seja sempre agradável e temperado com sal, para que saibam como responder a cada um.

[[v51-4-7]]

^<<v51-4-7,7>>^ Tíquico lhes informará todas as coisas a meu respeito. Ele é um irmão amado, ministro fiel e cooperador no serviço do Senhor.

[[v51-4-8]]

^<<v51-4-8,8>>^ Eu o envio a vocês precisamente com o propósito de que saibam de tudo o que se passa conosco, e para que ele fortaleça os seus corações.

[[v51-4-9]]

^<<v51-4-9,9>>^ Ele irá com Onésimo, fiel e amado irmão, que é um de vocês. Eles irão contar-lhes tudo o que está acontecendo aqui.

[[v51-4-10]]

^<<v51-4-10,10>>^ Aristarco, meu companheiro de prisão, envia-lhes saudações, bem como Marcos, primo de Barnabé. Vocês receberam instruções a respeito de Marcos, e se ele for visitá-los, recebam-no.

[[v51-4-11]]

^<<v51-4-11,11>>^ Jesus, chamado Justo, também envia saudações. Estes são os únicos da circuncisão que são meus cooperadores em favor do Reino de Deus. Eles têm sido uma fonte de ânimo para mim.

[[v51-4-12]]

^<<v51-4-12,12>>^ Epafras, que é um de vocês e servo de Cristo Jesus, envia saudações. Ele está sempre batalhando por vocês em oração, para que, como pessoas maduras e plenamente convictas, continuem firmes em toda a vontade de Deus.

[[v51-4-13]]

^<<v51-4-13,13>>^ Dele dou testemunho de que se esforça muito por vocês e pelos que estão em Laodicéia e em Hierápolis.

[[v51-4-14]]

^<<v51-4-14,14>>^ Lucas, o médico amado, e Demas, enviam saudações.

[[v51-4-15]]

^<<v51-4-15,15>>^ Saúdem os irmãos de Laodicéia, bem como Ninfa e a igreja que se reúne em sua casa.

[[v51-4-16]]

^<<v51-4-16,16>>^ Depois que esta carta for lida entre vocês, façam que também seja lida na igreja dos laodicenses, e que vocês igualmente leiam a carta de Laodicéia.

[[v51-4-17]]

^<<v51-4-17,17>>^ Digam a Arquipo: "Cuide em cumprir o ministério que você recebeu no Senhor".

[[v51-4-18]]

^<<v51-4-18,18>>^ Eu, Paulo, escrevo esta saudação de próprio punho. Lembrem-se das minhas algemas. A graça seja com vocês.

'''

xref:051-colossenses/051-colossenses-003.adoc#v51-3-0[&#60; Capítulo Anterior] | <<v51-4-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-001.adoc#v52-1-0[Próximo Capítulo &#62;]