include::./index.adoc[]

[[v51-1-0]]
=== Colossenses, 1
// nvi ?, NVI - Nova Versão Internacional

[[v51-1-1]]

^<<v51-1-1,1>>^ Paulo, apóstolo de Cristo Jesus pela vontade de Deus, e o irmão Timóteo,

[[v51-1-2]]

^<<v51-1-2,2>>^ aos santos e fiéis irmãos em Cristo que estão em Colossos: A vocês, graça e paz da parte de Deus nosso Pai e do Senhor Jesus Cristo.

[[v51-1-3]]

^<<v51-1-3,3>>^ Sempre agradecemos a Deus, o Pai de nosso Senhor Jesus Cristo, quando oramos por vocês,

[[v51-1-4]]

^<<v51-1-4,4>>^ pois temos ouvido falar da fé que vocês têm em Cristo Jesus e do amor por todos os santos,

[[v51-1-5]]

^<<v51-1-5,5>>^ por causa da esperança que lhes está reservada nos céus, a respeito da qual vocês ouviram por meio da palavra da verdade, o evangelho

[[v51-1-6]]

^<<v51-1-6,6>>^ que chegou até vocês. Por todo o mundo este evangelho vai frutificando e crescendo, como também ocorre entre vocês, desde o dia em que o ouviram e entenderam a graça de Deus em toda a sua verdade.

[[v51-1-7]]

^<<v51-1-7,7>>^ Vocês o aprenderam de Epafras, nosso amado cooperador, fiel ministro de Cristo para conosco,

[[v51-1-8]]

^<<v51-1-8,8>>^ que também nos falou do amor que vocês têm no Espírito.

[[v51-1-9]]

^<<v51-1-9,9>>^ Por essa razão, desde o dia em que o ouvimos, não deixamos de orar por vocês e de pedir que sejam cheios do pleno conhecimento da vontade de Deus, com toda a sabedoria e entendimento espiritual.

[[v51-1-10]]

^<<v51-1-10,10>>^ E isso para que vocês vivam de maneira digna do Senhor e em tudo possam agradá-lo, frutificando em toda boa obra, crescendo no conhecimento de Deus e

[[v51-1-11]]

^<<v51-1-11,11>>^ sendo fortalecidos com todo o poder, de acordo com a força da sua glória, para que tenham toda a perseverança e paciência com alegria,

[[v51-1-12]]

^<<v51-1-12,12>>^ dando graças ao Pai, que nos tornou dignos de participar da herança dos santos no reino da luz.

[[v51-1-13]]

^<<v51-1-13,13>>^ Pois ele nos resgatou do domínio das trevas e nos transportou para o Reino do seu Filho amado,

[[v51-1-14]]

^<<v51-1-14,14>>^ em quem temos a redenção, a saber, o perdão dos pecados.

[[v51-1-15]]

^<<v51-1-15,15>>^ Ele é a imagem do Deus invisível, o primogênito de toda a criação,

[[v51-1-16]]

^<<v51-1-16,16>>^ pois nele foram criadas todas as coisas nos céus e na terra, as visíveis e as invisíveis, sejam tronos ou soberanias, poderes ou autoridades; todas as coisas foram criadas por ele e para ele.

[[v51-1-17]]

^<<v51-1-17,17>>^ Ele é antes de todas as coisas, e nele tudo subsiste.

[[v51-1-18]]

^<<v51-1-18,18>>^ Ele é a cabeça do corpo, que é a igreja; é o princípio e o primogênito dentre os mortos, para que em tudo tenha a supremacia.

[[v51-1-19]]

^<<v51-1-19,19>>^ Pois foi do agrado de Deus que nele habitasse toda a plenitude,

[[v51-1-20]]

^<<v51-1-20,20>>^ e por meio dele reconciliasse consigo todas as coisas, tanto as que estão na terra quanto as que estão no céu, estabelecendo a paz pelo seu sangue derramado na cruz.

[[v51-1-21]]

^<<v51-1-21,21>>^ Antes vocês estavam separados de Deus e, em suas mentes, eram inimigos por causa do mau procedimento de vocês.

[[v51-1-22]]

^<<v51-1-22,22>>^ Mas agora ele os reconciliou pelo corpo físico de Cristo, mediante a morte, para apresentá-los diante dele santos, inculpáveis e livres de qualquer acusação,

[[v51-1-23]]

^<<v51-1-23,23>>^ desde que continuem alicerçados e firmes na fé, sem se afastarem da esperança do evangelho, que vocês ouviram e que tem sido proclamado a todos os que estão debaixo do céu. Esse é o evangelho do qual eu, Paulo, me tornei ministro.

[[v51-1-24]]

^<<v51-1-24,24>>^ Agora me alegro em meus sofrimentos por vocês, e completo no meu corpo o que resta das aflições de Cristo, em favor do seu corpo, que é a igreja.

[[v51-1-25]]

^<<v51-1-25,25>>^ Dela me tornei ministro de acordo com a responsabilidade por Deus a mim atribuída de apresentar-lhes plenamente a palavra de Deus,

[[v51-1-26]]

^<<v51-1-26,26>>^ o mistério que esteve oculto durante épocas e gerações, mas que agora foi manifestado a seus santos.

[[v51-1-27]]

^<<v51-1-27,27>>^ A eles quis Deus dar a conhecer entre os gentios a gloriosa riqueza deste mistério, que é Cristo em vocês, a esperança da glória.

[[v51-1-28]]

^<<v51-1-28,28>>^ Nós o proclamamos, advertindo e ensinando a cada um com toda a sabedoria, a fim de que apresentemos todo homem perfeito em Cristo.

[[v51-1-29]]

^<<v51-1-29,29>>^ Para isso eu me esforço, lutando conforme a sua força, que atua poderosamente em mim.

'''

xref:050-filipenses/050-filipenses-004.adoc#v50-4-0[&#60; Capítulo Anterior] | <<v51-1-0,Topo>> | xref:051-colossenses/051-colossenses-002.adoc#v51-2-0[Próximo Capítulo &#62;]