include::./index.adoc[]

[[v51-3-0]]
=== Colossenses, 3
// nvi ?, NVI - Nova Versão Internacional

[[v51-3-1]]

^<<v51-3-1,1>>^ Portanto, já que vocês ressuscitaram com Cristo, procurem as coisas que são do alto, onde Cristo está assentado à direita de Deus.

[[v51-3-2]]

^<<v51-3-2,2>>^ Mantenham o pensamento nas coisas do alto, e não nas coisas terrenas.

[[v51-3-3]]

^<<v51-3-3,3>>^ Pois vocês morreram, e agora a sua vida está escondida com Cristo em Deus.

[[v51-3-4]]

^<<v51-3-4,4>>^ Quando Cristo, que é a sua vida, for manifestado, então vocês também serão manifestados com ele em glória.

[[v51-3-5]]

^<<v51-3-5,5>>^ Assim, façam morrer tudo o que pertence à natureza terrena de vocês: imoralidade sexual, impureza, paixão, desejos maus e a ganância, que é idolatria.

[[v51-3-6]]

^<<v51-3-6,6>>^ É por causa dessas coisas que vem a ira de Deus sobre os que vivem na desobediência,

[[v51-3-7]]

^<<v51-3-7,7>>^ as quais vocês praticaram no passado, quando costumavam viver nelas.

[[v51-3-8]]

^<<v51-3-8,8>>^ Mas agora, abandonem todas estas coisas: ira, indignação, maldade, maledicência e linguagem indecente no falar.

[[v51-3-9]]

^<<v51-3-9,9>>^ Não mintam uns aos outros, visto que vocês já se despiram do velho homem com suas práticas

[[v51-3-10]]

^<<v51-3-10,10>>^ e se revestiram do novo, o qual está sendo renovado em conhecimento, à imagem do seu Criador.

[[v51-3-11]]

^<<v51-3-11,11>>^ Nessa nova vida já não há diferença entre grego e judeu, circunciso e incircunciso, bárbaro e cita, escravo e livre, mas Cristo é tudo e está em todos.

[[v51-3-12]]

^<<v51-3-12,12>>^ Portanto, como povo escolhido de Deus, santo e amado, revistam-se de profunda compaixão, bondade, humildade, mansidão e paciência.

[[v51-3-13]]

^<<v51-3-13,13>>^ Suportem-se uns aos outros e perdoem as queixas que tiverem uns contra os outros. Perdoem como o Senhor lhes perdoou.

[[v51-3-14]]

^<<v51-3-14,14>>^ Acima de tudo, porém, revistam-se do amor, que é o elo perfeito.

[[v51-3-15]]

^<<v51-3-15,15>>^ Que a paz de Cristo seja o juiz em seus corações, visto que vocês foram chamados a viver em paz, como membros de um só corpo. E sejam agradecidos.

[[v51-3-16]]

^<<v51-3-16,16>>^ Habite ricamente em vocês a palavra de Cristo; ensinem e aconselhem-se uns aos outros com toda a sabedoria, e cantem salmos, hinos e cânticos espirituais com gratidão a Deus em seus corações.

[[v51-3-17]]

^<<v51-3-17,17>>^ Tudo o que fizerem, seja em palavra ou em ação, façam-no em nome do Senhor Jesus, dando por meio dele graças a Deus Pai.

[[v51-3-18]]

^<<v51-3-18,18>>^ Mulheres, sujeitem-se a seus maridos, como convém a quem está no Senhor.

[[v51-3-19]]

^<<v51-3-19,19>>^ Maridos, amem suas mulheres e não as tratem com amargura.

[[v51-3-20]]

^<<v51-3-20,20>>^ Filhos, obedeçam a seus pais em tudo, pois isso agrada ao Senhor.

[[v51-3-21]]

^<<v51-3-21,21>>^ Pais, não irritem seus filhos, para que eles não se desanimem.

[[v51-3-22]]

^<<v51-3-22,22>>^ Escravos, obedeçam em tudo a seus senhores terrenos, não somente para agradar os homens quando eles estão observando, mas com sinceridade de coração, pelo fato de vocês temerem ao Senhor.

[[v51-3-23]]

^<<v51-3-23,23>>^ Tudo o que fizerem, façam de todo o coração, como para o Senhor, e não para os homens,

[[v51-3-24]]

^<<v51-3-24,24>>^ sabendo que receberão do Senhor a recompensa da herança. É a Cristo, o Senhor, que vocês estão servindo.

[[v51-3-25]]

^<<v51-3-25,25>>^ Quem cometer injustiça receberá de volta injustiça, e não haverá exceção para ninguém.

'''

xref:051-colossenses/051-colossenses-002.adoc#v51-2-0[&#60; Capítulo Anterior] | <<v51-3-0,Topo>> | xref:051-colossenses/051-colossenses-004.adoc#v51-4-0[Próximo Capítulo &#62;]