include::./index.adoc[]

[[v51-2-0]]
=== Colossenses, 2
// nvi ?, NVI - Nova Versão Internacional

[[v51-2-1]]

^<<v51-2-1,1>>^ Quero que vocês saibam quanto estou lutando por vocês, pelos que estão em Laodicéia e por todos os que ainda não me conhecem pessoalmente.

[[v51-2-2]]

^<<v51-2-2,2>>^ Esforço-me para que eles sejam fortalecidos em seus corações, estejam unidos em amor e alcancem toda a riqueza do pleno entendimento, a fim de conhecerem plenamente o mistério de Deus, a saber, Cristo.

[[v51-2-3]]

^<<v51-2-3,3>>^ Nele estão escondidos todos os tesouros da sabedoria e do conhecimento.

[[v51-2-4]]

^<<v51-2-4,4>>^ Eu lhes digo isso para que ninguém os engane com argumentos aparentemente convincentes.

[[v51-2-5]]

^<<v51-2-5,5>>^ Porque, embora esteja fisicamente ausente, estou presente com vocês em espírito, e alegro-me em ver como estão vivendo em ordem e como está firme a fé que vocês têm em Cristo.

[[v51-2-6]]

^<<v51-2-6,6>>^ Portanto, assim como vocês receberam a Cristo Jesus, o Senhor, continuem a viver nele,

[[v51-2-7]]

^<<v51-2-7,7>>^ enraizados e edificados nele, firmados na fé, como foram ensinados, transbordando de gratidão.

[[v51-2-8]]

^<<v51-2-8,8>>^ Tenham cuidado para que ninguém os escravize a filosofias vãs e enganosas, que se fundamentam nas tradições humanas e nos princípios elementares deste mundo, e não em Cristo.

[[v51-2-9]]

^<<v51-2-9,9>>^ Pois em Cristo habita corporalmente toda a plenitude da divindade,

[[v51-2-10]]

^<<v51-2-10,10>>^ e, por estarem nele, que é o Cabeça de todo poder e autoridade, vocês receberam a plenitude.

[[v51-2-11]]

^<<v51-2-11,11>>^ Nele também vocês foram circuncidados, não com uma circuncisão feita por mãos humanas, mas com a circuncisão feita por Cristo, que é o despojar do corpo da carne.

[[v51-2-12]]

^<<v51-2-12,12>>^ Isso aconteceu quando vocês foram sepultados com ele no batismo, e com ele foram ressuscitados mediante a fé no poder de Deus que o ressuscitou dentre os mortos.

[[v51-2-13]]

^<<v51-2-13,13>>^ Quando vocês estavam mortos em pecados e na incircuncisão da sua carne, Deus os vivificou juntamente com Cristo. Ele nos perdoou todas as transgressões,

[[v51-2-14]]

^<<v51-2-14,14>>^ e cancelou a escrita de dívida, que consistia em ordenanças, e que nos era contrária. Ele a removeu, pregando-a na cruz,

[[v51-2-15]]

^<<v51-2-15,15>>^ e, tendo despojado os poderes e as autoridades, fez deles um espetáculo público, triunfando sobre eles na cruz.

[[v51-2-16]]

^<<v51-2-16,16>>^ Portanto, não permitam que ninguém os julgue pelo que vocês comem ou bebem, ou com relação a alguma festividade religiosa ou à celebração das luas novas ou dos dias de sábado.

[[v51-2-17]]

^<<v51-2-17,17>>^ Estas coisas são sombras do que haveria de vir; a realidade, porém, encontra-se em Cristo.

[[v51-2-18]]

^<<v51-2-18,18>>^ Não permitam que ninguém que tenha prazer numa falsa humildade e na adoração de anjos os impeça de alcançar o prêmio. Tal pessoa conta detalhadamente suas visões, e sua mente carnal a torna orgulhosa.

[[v51-2-19]]

^<<v51-2-19,19>>^ Trata-se de alguém que não está unido à Cabeça, a partir da qual todo o corpo, sustentado e unido por seus ligamentos e juntas, efetua o crescimento dado por Deus.

[[v51-2-20]]

^<<v51-2-20,20>>^ Já que vocês morreram com Cristo para os princípios elementares deste mundo, por que é que vocês, então, como se ainda pertencessem a ele, se submetem a regras:

[[v51-2-21]]

^<<v51-2-21,21>>^ "Não manuseie! " "Não prove! " "Não toque! "?

[[v51-2-22]]

^<<v51-2-22,22>>^ Todas essas coisas estão destinadas a perecer pelo uso, pois se baseiam em mandamentos e ensinos humanos.

[[v51-2-23]]

^<<v51-2-23,23>>^ Essas regras têm, de fato, aparência de sabedoria, com sua pretensa religiosidade, falsa humildade e severidade com o corpo, mas não têm valor algum para refrear os impulsos da carne.

'''

xref:051-colossenses/051-colossenses-001.adoc#v51-1-0[&#60; Capítulo Anterior] | <<v51-2-0,Topo>> | xref:051-colossenses/051-colossenses-003.adoc#v51-3-0[Próximo Capítulo &#62;]