include::./index.adoc[]

[[v35-3-0]]
=== Habacuque, 3
// nvi ?, NVI - Nova Versão Internacional

[[v35-3-1]]

^<<v35-3-1,1>>^ Oração do profeta Habacuque. Uma confissão.

[[v35-3-2]]

^<<v35-3-2,2>>^ Senhor, ouvi falar da tua fama; temo diante dos teus atos, Senhor. Realiza de novo, em nossa época, as mesmas obras, faze-as conhecidas em nosso tempo; em tua ira, lembra-te da misericórdia.

[[v35-3-3]]

^<<v35-3-3,3>>^ Deus veio de Temã, o Santo veio do monte Parã. Pausa Sua glória cobriu os céus e seu louvor encheu a terra.

[[v35-3-4]]

^<<v35-3-4,4>>^ Seu esplendor era como a luz do sol; raios lampejavam de sua mão, onde se escondia o seu poder.

[[v35-3-5]]

^<<v35-3-5,5>>^ Pragas iam adiante dele; doenças terríveis seguiam os seus passos.

[[v35-3-6]]

^<<v35-3-6,6>>^ Ele parou, e a terra tremeu; olhou, e fez estremecer as nações. Montes antigos se desmancharam; colinas antiqüíssimas se desfizeram. Os caminhos dele são eternos.

[[v35-3-7]]

^<<v35-3-7,7>>^ Vi a aflição das tendas de Cuchã; tremiam as cortinas das tendas de Midiã.

[[v35-3-8]]

^<<v35-3-8,8>>^ Era com os rios que estavas irado, Senhor? Era contra os riachos o teu furor? Foi contra o mar que a tua fúria transbordou quando cavalgaste com os teus cavalos e com os teus carros vitoriosos?

[[v35-3-9]]

^<<v35-3-9,9>>^ Preparaste o teu arco; pediste muitas flechas. Pausa Fendeste a terra com rios;

[[v35-3-10]]

^<<v35-3-10,10>>^ os montes te viram e se contorceram. Torrentes de água desceram com violência; o abismo estrondou erguendo as suas ondas.

[[v35-3-11]]

^<<v35-3-11,11>>^ O sol e lua pararam em suas moradas, diante do reflexo de tuas flechas voadoras, diante do lampejo da tua lança reluzente.

[[v35-3-12]]

^<<v35-3-12,12>>^ Com ira andaste a passos largos por toda a terra e com indignação pisoteaste as nações.

[[v35-3-13]]

^<<v35-3-13,13>>^ Saíste para salvar o teu povo, para libertar o teu ungido. Esmagaste o líder da nação ímpia, tu o desnudaste da cabeça aos pés. Pausa

[[v35-3-14]]

^<<v35-3-14,14>>^ Com as suas próprias flechas lhe atravessaste a cabeça, quando os seus guerreiros saíram como um furacão para nos espalhar, com maldoso prazer, como se estivessem para devorar o necessitado em seu esconderijo.

[[v35-3-15]]

^<<v35-3-15,15>>^ Pisaste o mar com teus cavalos, agitando as grandes águas.

[[v35-3-16]]

^<<v35-3-16,16>>^ Ouvi isso, e o meu íntimo estremeceu, meus lábios tremeram; os meus ossos desfaleceram; minhas pernas vacilavam. Tranqüilo esperarei o dia da desgraça que virá sobre o povo que nos ataca.

[[v35-3-17]]

^<<v35-3-17,17>>^ Mesmo não florescendo a figueira, não havendo uvas nas videiras; mesmo falhando a safra de azeitonas, não havendo produção de alimento nas lavouras, nem ovelhas no curral nem bois nos estábulos,

[[v35-3-18]]

^<<v35-3-18,18>>^ ainda assim eu exultarei no Senhor e me alegrarei no Deus da minha salvação.

[[v35-3-19]]

^<<v35-3-19,19>>^ O Senhor Soberano é a minha força; ele faz os meus pés como os do cervo; ele me habilita a andar em lugares altos. Para o mestre de música. Para os meus instrumentos de cordas.

'''

xref:035-habacuque/035-habacuque-002.adoc#v35-2-0[&#60; Capítulo Anterior] | <<v35-3-0,Topo>> | xref:036-sofonias/036-sofonias-001.adoc#v36-1-0[Próximo Capítulo &#62;]