include::./index.adoc[]

[[v35-2-0]]
=== Habacuque, 2
// nvi ?, NVI - Nova Versão Internacional

[[v35-2-1]]

^<<v35-2-1,1>>^ Ficarei no meu posto de sentinela e tomarei posição sobre a muralha; aguardarei para ver o que ele me dirá e que resposta terei à minha queixa.

[[v35-2-2]]

^<<v35-2-2,2>>^ Então o Senhor respondeu: "Escreva claramente a visão em tabuinhas, para que se leia facilmente.

[[v35-2-3]]

^<<v35-2-3,3>>^ Pois a visão aguarda um tempo designado; ela fala do fim, e não falhará. Ainda que se demore, espere-a; porque ela certamente virá e não se atrasará".

[[v35-2-4]]

^<<v35-2-4,4>>^ Escreva: "O ímpio está envaidecido; seus desejos não são bons; mas o justo viverá pela sua fidelidade.

[[v35-2-5]]

^<<v35-2-5,5>>^ De fato, a riqueza é ilusória, e o ímpio é arrogante e não descansa; ele é voraz como a sepultura e como a morte. Nunca se satisfaz; apanha para si todas as nações e ajunta para si todos os povos.

[[v35-2-6]]

^<<v35-2-6,6>>^ "Todos estes povos um dia rirão dele com canções de zombaria e dirão: " ‘Ai daquele que amontoa bens roubados e se enriquece mediante extorsão! Até quando isto continuará assim? ’

[[v35-2-7]]

^<<v35-2-7,7>>^ Seus credores não se levantarão de repente? Não despertarão os que o fazem tremer? Agora você se tornará vítima deles.

[[v35-2-8]]

^<<v35-2-8,8>>^ Porque você saqueou muitas nações, todos os povos que restaram o saquearão. Pois você derramou muito sangue, e cometeu violência contra terras, cidades e seus habitantes.

[[v35-2-9]]

^<<v35-2-9,9>>^ "Ai daquele que obtém lucros injustos para a sua casa, para pôr seu ninho no alto e escapar das garras do mal!

[[v35-2-10]]

^<<v35-2-10,10>>^ Você tramou a ruína de muitos povos, envergonhando a sua própria casa e pecando contra a sua própria vida.

[[v35-2-11]]

^<<v35-2-11,11>>^ Pois as pedras clamarão da parede, e as vigas responderão do madeiramento contra você.

[[v35-2-12]]

^<<v35-2-12,12>>^ "Ai daquele que edifica uma cidade com sangue e a estabelece com crime!

[[v35-2-13]]

^<<v35-2-13,13>>^ Acaso não vem do Senhor dos Exércitos, que o trabalho dos povos seja só para satisfazer o fogo, e que as nações se afadiguem em vão?

[[v35-2-14]]

^<<v35-2-14,14>>^ E a terra se encherá do conhecimento da glória do Senhor, como as águas enchem o mar.

[[v35-2-15]]

^<<v35-2-15,15>>^ "Ai daquele que dá bebida ao seu próximo, misturando-a com o seu furor, até que ele fique bêbado, para lhe contemplar a nudez.

[[v35-2-16]]

^<<v35-2-16,16>>^ Beba bastante vergonha, em vez de glória! Sim! Beba você também e se exponha! A taça da mão direita do Senhor lhe é dada. Muita vergonha cobrirá a sua glória.

[[v35-2-17]]

^<<v35-2-17,17>>^ A violência que você cometeu contra o Líbano o alcançará, e você ficará apavorado com a destruição de animais, que você fez. Pois você derramou muito sangue, e cometeu violência contra terras, cidades e seus habitantes.

[[v35-2-18]]

^<<v35-2-18,18>>^ "De que vale uma imagem feita por um escultor? Ou um ídolo de metal que ensina mentiras? Pois aquele que o faz confia em sua própria criação, fazendo ídolos incapazes de falar.

[[v35-2-19]]

^<<v35-2-19,19>>^ Ai daquele que diz à madeira: "Desperte! Ou à pedra sem vida: Acorde! " Poderá isso dar orientação? Está coberta de ouro e prata, mas não respira.

[[v35-2-20]]

^<<v35-2-20,20>>^ Mas o Senhor está em seu santo templo; diante dele fique em silêncio toda a terra".

'''

xref:035-habacuque/035-habacuque-001.adoc#v35-1-0[&#60; Capítulo Anterior] | <<v35-2-0,Topo>> | xref:035-habacuque/035-habacuque-003.adoc#v35-3-0[Próximo Capítulo &#62;]