include::./index.adoc[]

[[v35-1-0]]
=== Habacuque, 1
// nvi ?, NVI - Nova Versão Internacional

[[v35-1-1]]

^<<v35-1-1,1>>^ Advertência do profeta Habacuque.

[[v35-1-2]]

^<<v35-1-2,2>>^ Até quando, Senhor, clamarei por socorro, sem que tu ouças? Até quando gritarei a ti: "Violência! " sem que tragas salvação?

[[v35-1-3]]

^<<v35-1-3,3>>^ Por que me fazes ver a injustiça, e contemplar a maldade? A destruição e a violência estão diante de mim; há luta e conflito por todo lado.

[[v35-1-4]]

^<<v35-1-4,4>>^ Por isso a lei se enfraquece e a justiça nunca prevalece. Os ímpios prejudicam os justos, e assim a justiça é pervertida.

[[v35-1-5]]

^<<v35-1-5,5>>^ "Olhem as nações e contemplem-nas, fiquem atônitos e pasmem; pois nos dias de vocês farei algo em que não creriam, se lhes fosse contado.

[[v35-1-6]]

^<<v35-1-6,6>>^ Estou trazendo os babilônios, nação cruel e impetuosa, que marcha por toda a extensão da terra para apoderar-se de moradias que não lhe pertencem.

[[v35-1-7]]

^<<v35-1-7,7>>^ É uma nação apavorante e temível, que cria a sua própria justiça e promove a sua própria honra.

[[v35-1-8]]

^<<v35-1-8,8>>^ Seus cavalos são mais velozes que os leopardos, mais ferozes que os lobos no crepúsculo. Sua cavalaria vem de longe. Seus cavalos vêm a galope; vêm voando como ave de rapina que mergulha para devorar;

[[v35-1-9]]

^<<v35-1-9,9>>^ todos vêm prontos para a violência. Suas hordas avançam como o vento do deserto e fazendo tantos prisioneiros como a areia da praia.

[[v35-1-10]]

^<<v35-1-10,10>>^ Menosprezam os reis e zombam dos governantes. Riem de todas as cidades fortificadas, pois constroem rampas de terra e por elas as conquistam.

[[v35-1-11]]

^<<v35-1-11,11>>^ Depois passam como o vento e prosseguem; homens carregados de culpa, e que têm por deus a sua própria força".

[[v35-1-12]]

^<<v35-1-12,12>>^ Senhor, tu não és desde a eternidade? Meu Deus, meu Santo, tu não morrerás. Senhor, tu designaste essa nação para executar juízo; ó Rocha, determinaste a ela que aplicasse castigo.

[[v35-1-13]]

^<<v35-1-13,13>>^ Teus olhos são tão puros, que não suportam ver o mal; não podes tolerar a maldade. Por que toleras então esses perversos? Por que ficas calado enquanto os ímpios engolem os que são mais justos do que eles?

[[v35-1-14]]

^<<v35-1-14,14>>^ Tornaste os homens como peixes do mar, como animais, que não são governados por ninguém.

[[v35-1-15]]

^<<v35-1-15,15>>^ Esses ímpios puxam a todos com anzóis, apanham-nos em suas redes e nelas os arrastam; então alegram-se e exultam.

[[v35-1-16]]

^<<v35-1-16,16>>^ E por essa razão eles oferecem sacrifício às suas redes e queimam incenso em sua honra, pois, graças às suas redes, vivem em grande conforto e desfrutam iguarias.

[[v35-1-17]]

^<<v35-1-17,17>>^ Mas, continuará ele esvaziando a sua rede, destruindo sem misericórdia as nações?

'''

xref:034-naum/034-naum-003.adoc#v34-3-0[&#60; Capítulo Anterior] | <<v35-1-0,Topo>> | xref:035-habacuque/035-habacuque-002.adoc#v35-2-0[Próximo Capítulo &#62;]