include::./index.adoc[]

[[v33-2-0]]
=== Miquéias, 2
// nvi ?, NVI - Nova Versão Internacional

[[v33-2-1]]

^<<v33-2-1,1>>^ Ai daqueles que planejam maldade, dos que tramam o mal em suas camas! Quando alvorece, eles o executam, porque isso eles podem fazer.

[[v33-2-2]]

^<<v33-2-2,2>>^ Cobiçam terrenos e se apoderam deles; cobiçam casas e as tomam. Fazem violência ao homem e à sua família, a ele e aos seus herdeiros.

[[v33-2-3]]

^<<v33-2-3,3>>^ Portanto, assim diz o Senhor: "Estou planejando contra essa gente uma desgraça, da qual vocês não poderão salvar-se. Vocês já não vão andar com arrogância, pois será tempo de desgraça.

[[v33-2-4]]

^<<v33-2-4,4>>^ Naquele dia vocês serão ridicularizados; zombarão de vocês com esta triste canção: ‘Estamos totalmente arruinados; dividida foi a propriedade do meu povo. Ele tirou-a de mim! Entregou a invasores as nossas terras’ ".

[[v33-2-5]]

^<<v33-2-5,5>>^ Portanto, vocês não estarão na assembléia do Senhor para a divisão da terra por sorteio.

[[v33-2-6]]

^<<v33-2-6,6>>^ "Não preguem", dizem os seus profetas. "Não preguem acerca dessas coisas; a desgraça não nos alcançará". Ó descendência de Jacó,

[[v33-2-7]]

^<<v33-2-7,7>>^ é isto que está sendo falado: "O Espírito do Senhor perdeu a paciência? É assim que ele age? " "As minhas palavras não fazem bem àquele cujos caminhos são retos?

[[v33-2-8]]

^<<v33-2-8,8>>^ Mas ultimamente como inimigos vocês atacam o meu povo. Além da túnica arrancam a capa daqueles que passam confiantes, como quem volta da guerra.

[[v33-2-9]]

^<<v33-2-9,9>>^ Vocês tiram as mulheres do meu povo de seus lares agradáveis. De seus filhos vocês removem a minha dignidade para sempre.

[[v33-2-10]]

^<<v33-2-10,10>>^ Levantem-se, vão embora! Pois este não é o lugar de descanso, porque ele está contaminado, está arruinado, sem que haja remédio.

[[v33-2-11]]

^<<v33-2-11,11>>^ Se um mentiroso e enganador vier e disser: ‘Eu pregarei para vocês fartura de vinho e de bebida fermentada’, ele será o profeta deste povo! "

[[v33-2-12]]

^<<v33-2-12,12>>^ "Eu vou de fato ajuntar todos vocês, ó Jacó; sim, vou reunir o remanescente de Israel. Eu os ajuntarei como ovelhas num aprisco, como um rebanho numa pastagem; haverá barulho de muita gente.

[[v33-2-13]]

^<<v33-2-13,13>>^ Aquele que abre o caminho irá adiante deles; passarão pela porta e sairão. O rei deles, o Senhor, os guiará".

'''

xref:033-miqueias/033-miqueias-001.adoc#v33-1-0[&#60; Capítulo Anterior] | <<v33-2-0,Topo>> | xref:033-miqueias/033-miqueias-003.adoc#v33-3-0[Próximo Capítulo &#62;]