include::./index.adoc[]

[[v33-5-0]]
=== Miquéias, 5
// nvi ?, NVI - Nova Versão Internacional

[[v33-5-1]]

^<<v33-5-1,1>>^ Reúna suas tropas, ó cidade das tropas, pois há um cerco contra nós. O líder de Israel será ferido na face, com uma vara.

[[v33-5-2]]

^<<v33-5-2,2>>^ "Mas tu, Belém-Efrata, embora sejas pequena entre os clãs de Judá, de ti virá para mim aquele que será o governante sobre Israel. Suas origens estão no passado distante, em tempos antigos. "

[[v33-5-3]]

^<<v33-5-3,3>>^ Por isso os israelitas serão abandonados até que dê à luz a que está em trabalho de parto. Então o restante dos irmãos do governante voltarão para unir-se aos israelitas.

[[v33-5-4]]

^<<v33-5-4,4>>^ Ele se estabelecerá e os pastoreará na força do Senhor, na majestade do nome do Senhor, o seu Deus. E eles viverão em segurança, pois a grandeza dele alcançará os confins da terra.

[[v33-5-5]]

^<<v33-5-5,5>>^ Ele será a sua paz. Quando os assírios invadirem a nossa terra e marcharem sobre as nossas fortalezas, levantaremos contra eles sete pastores, até oito líderes escolhidos.

[[v33-5-6]]

^<<v33-5-6,6>>^ Eles pastorearão a Assíria com a espada, e a terra de Ninrode com a espada empunhada. Eles nos livrarão quando os assírios invadirem a nossa terra, e entrarem por nossas fronteiras.

[[v33-5-7]]

^<<v33-5-7,7>>^ O remanescente de Jacó estará no meio de muitos povos como orvalho da parte do Senhor, como aguaceiro sobre a relva; não porá sua esperança no homem nem dependerá dos seres humanos.

[[v33-5-8]]

^<<v33-5-8,8>>^ O remanescente de Jacó estará entre as nações, no meio de muitos povos, como um leão entre os animais da floresta, como um leão forte entre rebanhos de ovelhas, leão que, quando ataca, destroça e mutila a presa, sem que ninguém a possa livrar.

[[v33-5-9]]

^<<v33-5-9,9>>^ Sua mão se levantará contra os seus adversários, e todos os seus inimigos serão destruídos.

[[v33-5-10]]

^<<v33-5-10,10>>^ "Naquele dia", declara o Senhor, "matarei os seus cavalos e destruirei os seus carros de guerra.

[[v33-5-11]]

^<<v33-5-11,11>>^ Destruirei também as cidades da sua terra e arrasarei todas as suas fortalezas.

[[v33-5-12]]

^<<v33-5-12,12>>^ Acabarei com a sua feitiçaria, e vocês não farão mais adivinhações.

[[v33-5-13]]

^<<v33-5-13,13>>^ Destruirei as suas imagens esculpidas e as suas colunas sagradas; vocês não se curvarão mais diante da obra de suas mãos.

[[v33-5-14]]

^<<v33-5-14,14>>^ Desarraigarei do meio de vocês os seus postes sagrados e derrubarei os seus ídolos.

[[v33-5-15]]

^<<v33-5-15,15>>^ Com ira e indignação me vingarei das nações que não me obedeceram. "

'''

xref:033-miqueias/033-miqueias-004.adoc#v33-4-0[&#60; Capítulo Anterior] | <<v33-5-0,Topo>> | xref:033-miqueias/033-miqueias-006.adoc#v33-6-0[Próximo Capítulo &#62;]