include::./index.adoc[]

[[v33-4-0]]
=== Miquéias, 4
// nvi ?, NVI - Nova Versão Internacional

[[v33-4-1]]

^<<v33-4-1,1>>^ Nos últimos dias acontecerá que o monte do templo do Senhor será estabelecido como o principal entre os montes; e se elevará acima das colinas, e os povos a ele acorrerão.

[[v33-4-2]]

^<<v33-4-2,2>>^ Muitas nações virão, dizendo: "Venham, subamos ao monte do Senhor, ao templo do Deus de Jacó. Ele nos ensinará os seus caminhos, para que andemos nas suas veredas". Pois a lei virá de Sião, a palavra do Senhor, de Jerusalém.

[[v33-4-3]]

^<<v33-4-3,3>>^ Ele julgará entre muitos povos e resolverá contendas entre nações poderosas e distantes. Das suas espadas, farão arados, e das suas lanças, foices. Nenhuma nação erguerá a espada contra outra, e não aprenderão mais a guerra.

[[v33-4-4]]

^<<v33-4-4,4>>^ Todo homem poderá sentar-se debaixo da sua videira e debaixo da sua figueira, e ninguém os incomodará, pois assim falou o Senhor dos Exércitos.

[[v33-4-5]]

^<<v33-4-5,5>>^ Pois todas as nações andam, cada uma em nome dos seus deuses, mas nós andaremos no nome do Senhor, o nosso Deus, para todo o sempre.

[[v33-4-6]]

^<<v33-4-6,6>>^ "Naquele dia", declara o Senhor, "ajuntarei os que tropeçam e reunirei os dispersos, aqueles a quem afligi.

[[v33-4-7]]

^<<v33-4-7,7>>^ Farei dos que tropeçam um remanescente, e dos dispersos, uma nação forte. O Senhor reinará sobre eles no monte Sião, daquele dia em diante e para sempre.

[[v33-4-8]]

^<<v33-4-8,8>>^ Quanto a você, ó torre do rebanho, ó fortaleza da cidade de Sião, o antigo domínio lhe será restaurado; a realeza virá para a cidade de Jerusalém. "

[[v33-4-9]]

^<<v33-4-9,9>>^ Agora, por que gritar tão alto? Você não tem rei? Seu conselheiro morreu, para que a dor seja tão forte como a de uma mulher em trabalho de parto?

[[v33-4-10]]

^<<v33-4-10,10>>^ Contorça-se em agonia, ó cidade de Sião, como a mulher em trabalho de parto, porque agora terá que deixar os seus muros para habitar em campo aberto. Você irá para a Babilônia, e lá você será libertada. Lá o Senhor a resgatará da mão dos seus inimigos.

[[v33-4-11]]

^<<v33-4-11,11>>^ Mas agora muitas nações estão reunidas contra você. Elas dizem: "Que Sião seja profanada, e que isso aconteça diante dos nossos olhos! "

[[v33-4-12]]

^<<v33-4-12,12>>^ Mas elas não conhecem os pensamentos do Senhor; não compreendem o plano daquele que as ajunta como feixes para a eira.

[[v33-4-13]]

^<<v33-4-13,13>>^ "Levante-se e debulhe, ó cidade de Sião, pois eu darei a você chifres de ferro; e cascos de bronze para despedaçar muitas nações". Você consagrará ao Senhor os ganhos ilícitos delas, e a riqueza delas ao Soberano de toda a terra.

'''

xref:033-miqueias/033-miqueias-003.adoc#v33-3-0[&#60; Capítulo Anterior] | <<v33-4-0,Topo>> | xref:033-miqueias/033-miqueias-005.adoc#v33-5-0[Próximo Capítulo &#62;]