include::./index.adoc[]

[[v33-1-0]]
=== Miquéias, 1
// nvi ?, NVI - Nova Versão Internacional

[[v33-1-1]]

^<<v33-1-1,1>>^ A palavra do Senhor que veio a Miquéias de Moresete durante os reinados de Jotão, Acaz e Ezequias, reis de Judá; a visão que ele teve acerca de Samaria e de Jerusalém:

[[v33-1-2]]

^<<v33-1-2,2>>^ Ouçam, todos os povos; prestem atenção, ó terra e todos os que nela habitam; que o Senhor Soberano, do seu santo templo, testemunhe contra vocês.

[[v33-1-3]]

^<<v33-1-3,3>>^ Vejam! O Senhor já está saindo da sua habitação; ele desce e pisa os lugares altos da terra.

[[v33-1-4]]

^<<v33-1-4,4>>^ Debaixo dele os montes se derretem como cera diante do fogo, e os vales racham ao meio, como que rasgados pelas águas que descem velozes encosta abaixo.

[[v33-1-5]]

^<<v33-1-5,5>>^ Tudo por causa da transgressão de Jacó, dos pecados da nação de Israel. Qual é a transgressão de Jacó? Acaso não é Samaria? Qual é o altar idólatra de Judá? Acaso não é Jerusalém?

[[v33-1-6]]

^<<v33-1-6,6>>^ "Por isso farei de Samaria um monte de entulho em campo aberto, um lugar para plantação de vinhas; atirarei as suas pedras no vale e porei a descoberto os seus alicerces.

[[v33-1-7]]

^<<v33-1-7,7>>^ Todas as suas imagens esculpidas serão despedaçadas e todos os seus ganhos imorais serão consumidos pelo fogo; destruirei todas as suas imagens. Visto que o que ela ajuntou foi como ganho da prostituição, como salário de prostituição tornará a ser usado. "

[[v33-1-8]]

^<<v33-1-8,8>>^ Por causa disso chorarei e lamentarei; andarei descalço e nu. Uivarei como um chacal e gemerei como um filhote de coruja.

[[v33-1-9]]

^<<v33-1-9,9>>^ Pois a ferida de Samaria é incurável; e chegou a Judá. O flagelo alcançou até mesmo a porta do meu povo, até a própria Jerusalém!

[[v33-1-10]]

^<<v33-1-10,10>>^ Não contem isso em Gate, e não chorem. Habitantes de Bete-Ofra, revolvam-se no pó.

[[v33-1-11]]

^<<v33-1-11,11>>^ Saiam nus e cobertos de vergonha, vocês que moram em Safir. Os habitantes de Zaanã não sairão de sua cidade. Bete-Ezel está em prantos; foi-lhe tirada a proteção.

[[v33-1-12]]

^<<v33-1-12,12>>^ Os que vivem em Marote se contorcem de dor aguardando alívio, porque a desgraça veio da parte do Senhor até às portas de Jerusalém.

[[v33-1-13]]

^<<v33-1-13,13>>^ Habitantes de Láquis, atrelem aos carros as parelhas de cavalos. Esse foi o início do pecado da cidade de Sião, pois as transgressões de Israel foram aprendidas com vocês.

[[v33-1-14]]

^<<v33-1-14,14>>^ Por isso vocês darão presentes de despedida a Moresete-Gate. A cidade de Aczibe se revelará enganosa aos reis de Israel.

[[v33-1-15]]

^<<v33-1-15,15>>^ Trarei um conquistador contra vocês, que vivem em Maressa. A glória de Israel irá a Adulão.

[[v33-1-16]]

^<<v33-1-16,16>>^ Rapem as suas cabeças em pranto por causa dos filhos nos quais vocês se tanto alegram; fiquem calvos como a águia, pois eles serão levados de vocês para o exílio.

'''

xref:032-jonas/032-jonas-004.adoc#v32-4-0[&#60; Capítulo Anterior] | <<v33-1-0,Topo>> | xref:033-miqueias/033-miqueias-002.adoc#v33-2-0[Próximo Capítulo &#62;]