include::./index.adoc[]

[[v33-6-0]]
=== Miquéias, 6
// nvi ?, NVI - Nova Versão Internacional

[[v33-6-1]]

^<<v33-6-1,1>>^ Ouçam o que diz o Senhor: "Fique de pé, abra processo perante os montes; que as colinas ouçam o que você tem a dizer.

[[v33-6-2]]

^<<v33-6-2,2>>^ Ouçam, ó montes, a acusação do Senhor; escutem, alicerces eternos da terra. Pois o Senhor tem uma acusação contra o seu povo; ele está entrando em juízo contra Israel.

[[v33-6-3]]

^<<v33-6-3,3>>^ "Meu povo, que foi que eu fiz contra você? Fui muito exigente? Responda-me.

[[v33-6-4]]

^<<v33-6-4,4>>^ Eu o tirei do Egito, e o redimi da terra da escravidão; enviei Moisés, Arão e Miriã para conduzi-lo.

[[v33-6-5]]

^<<v33-6-5,5>>^ Meu povo, lembre-se do que Balaque, rei de Moabe, pediu e do que Balaão, filho de Beor, respondeu. Recorde a viagem que você fez desde Sitim até Gilgal, e reconheça que os atos do Senhor são justos".

[[v33-6-6]]

^<<v33-6-6,6>>^ Com que eu poderia comparecer diante do Senhor e curvar-me perante o Deus exaltado? Deveria oferecer holocaustos de bezerros de um ano?

[[v33-6-7]]

^<<v33-6-7,7>>^ Ficaria o Senhor satisfeito com milhares de carneiros, com dez mil ribeiros de azeite? Devo oferecer o meu filho mais velho por causa da minha transgressão, o fruto do meu corpo por causa do meu próprio pecado?

[[v33-6-8]]

^<<v33-6-8,8>>^ Ele mostrou a você, ó homem, o que é bom e o que o Senhor exige: Pratique a justiça, ame a fidelidade e ande humildemente com o seu Deus.

[[v33-6-9]]

^<<v33-6-9,9>>^ A voz do Senhor está clamando à cidade; é sensato temer o teu nome! "Ouçam, tribo de Judá e assembléia da cidade!

[[v33-6-10]]

^<<v33-6-10,10>>^ Não há, na casa do ímpio, o tesouro da impiedade, e a medida falsificada, que é maldita?

[[v33-6-11]]

^<<v33-6-11,11>>^ Poderia alguém ser puro com balanças desonestas e pesos falsos?

[[v33-6-12]]

^<<v33-6-12,12>>^ Os ricos dentre vocês são violentos; o seu povo é mentiroso, e as suas línguas falam enganosamente.

[[v33-6-13]]

^<<v33-6-13,13>>^ Por isso, eu mesmo os farei sofrer e os arruinarei por causa dos seus pecados.

[[v33-6-14]]

^<<v33-6-14,14>>^ Vocês comerão, mas não ficarão satisfeitos; continuarão de estômago vazio. Vocês ajuntarão, mas nada preservarão, porquanto o que guardarem, à espada entregarei.

[[v33-6-15]]

^<<v33-6-15,15>>^ Vocês plantarão, mas não colherão; espremerão azeitonas, mas não se ungirão com o azeite; espremerão uvas, mas não beberão o vinho.

[[v33-6-16]]

^<<v33-6-16,16>>^ Porque vocês têm obedecido aos decretos de Onri e a todas as práticas da família de Acabe, e têm seguido as tradições deles. Por isso os entregarei à ruína e o seu povo ao desprezo; vocês sofrerão a zombaria das nações. "

'''

xref:033-miqueias/033-miqueias-005.adoc#v33-5-0[&#60; Capítulo Anterior] | <<v33-6-0,Topo>> | xref:033-miqueias/033-miqueias-007.adoc#v33-7-0[Próximo Capítulo &#62;]