include::./index.adoc[]

[[v49-2-0]]
=== Efésios, 2
// nvi ?, NVI - Nova Versão Internacional

[[v49-2-1]]

^<<v49-2-1,1>>^ Vocês estavam mortos em suas transgressões e pecados,

[[v49-2-2]]

^<<v49-2-2,2>>^ nos quais costumavam viver, quando seguiam a presente ordem deste mundo e o príncipe do poder do ar, o espírito que agora está atuando nos que vivem na desobediência.

[[v49-2-3]]

^<<v49-2-3,3>>^ Anteriormente, todos nós também vivíamos entre eles, satisfazendo as vontades da nossa carne, seguindo os seus desejos e pensamentos. Como os outros, éramos por natureza merecedores da ira.

[[v49-2-4]]

^<<v49-2-4,4>>^ Todavia, Deus, que é rico em misericórdia, pelo grande amor com que nos amou,

[[v49-2-5]]

^<<v49-2-5,5>>^ deu-nos vida juntamente com Cristo, quando ainda estávamos mortos em transgressões — pela graça vocês são salvos.

[[v49-2-6]]

^<<v49-2-6,6>>^ Deus nos ressuscitou com Cristo e com ele nos fez assentar nos lugares celestiais em Cristo Jesus,

[[v49-2-7]]

^<<v49-2-7,7>>^ para mostrar, nas eras que hão de vir, a incomparável riqueza de sua graça, demonstrada em sua bondade para conosco em Cristo Jesus.

[[v49-2-8]]

^<<v49-2-8,8>>^ Pois vocês são salvos pela graça, por meio da fé, e isto não vem de vocês, é dom de Deus;

[[v49-2-9]]

^<<v49-2-9,9>>^ não por obras, para que ninguém se glorie.

[[v49-2-10]]

^<<v49-2-10,10>>^ Porque somos criação de Deus realizada em Cristo Jesus para fazermos boas obras, as quais Deus preparou de antemão para que nós as praticássemos.

[[v49-2-11]]

^<<v49-2-11,11>>^ Portanto, lembrem-se de que anteriormente vocês eram gentios por nascimento e chamados incircuncisão pelos que se chamam circuncisão, feita no corpo por mãos humanas, e que

[[v49-2-12]]

^<<v49-2-12,12>>^ naquela época vocês estavam sem Cristo, separados da comunidade de Israel, sendo estrangeiros quanto às alianças da promessa, sem esperança e sem Deus no mundo.

[[v49-2-13]]

^<<v49-2-13,13>>^ Mas agora, em Cristo Jesus, vocês, que antes estavam longe, foram aproximados mediante o sangue de Cristo.

[[v49-2-14]]

^<<v49-2-14,14>>^ Pois ele é a nossa paz, o qual de ambos fez um e destruiu a barreira, o muro de inimizade,

[[v49-2-15]]

^<<v49-2-15,15>>^ anulando em seu corpo a lei dos mandamentos expressa em ordenanças. O objetivo dele era criar em si mesmo, dos dois, um novo homem, fazendo a paz,

[[v49-2-16]]

^<<v49-2-16,16>>^ e reconciliar com Deus os dois em um corpo, por meio da cruz, pela qual ele destruiu a inimizade.

[[v49-2-17]]

^<<v49-2-17,17>>^ Ele veio e anunciou paz a vocês que estavam longe e paz aos que estavam perto,

[[v49-2-18]]

^<<v49-2-18,18>>^ pois por meio dele tanto nós como vocês temos acesso ao Pai, por um só Espírito.

[[v49-2-19]]

^<<v49-2-19,19>>^ Portanto, vocês já não são estrangeiros nem forasteiros, mas concidadãos dos santos e membros da família de Deus,

[[v49-2-20]]

^<<v49-2-20,20>>^ edificados sobre o fundamento dos apóstolos e dos profetas, tendo Jesus Cristo como pedra angular,

[[v49-2-21]]

^<<v49-2-21,21>>^ no qual todo o edifício é ajustado e cresce para tornar-se um santuário santo no Senhor.

[[v49-2-22]]

^<<v49-2-22,22>>^ Nele vocês também estão sendo juntamente edificados, para se tornarem morada de Deus por seu Espírito.

'''

xref:049-efesios/049-efesios-001.adoc#v49-1-0[&#60; Capítulo Anterior] | <<v49-2-0,Topo>> | xref:049-efesios/049-efesios-003.adoc#v49-3-0[Próximo Capítulo &#62;]