include::./index.adoc[]

[[v49-6-0]]
=== Efésios, 6
// nvi ?, NVI - Nova Versão Internacional

[[v49-6-1]]

^<<v49-6-1,1>>^ Filhos, obedeçam a seus pais no Senhor, pois isso é justo.

[[v49-6-2]]

^<<v49-6-2,2>>^ "Honra teu pai e tua mãe", este é o primeiro mandamento com promessa:

[[v49-6-3]]

^<<v49-6-3,3>>^ "para que tudo te corra bem e tenhas longa vida sobre a terra".

[[v49-6-4]]

^<<v49-6-4,4>>^ Pais, não irritem seus filhos; antes criem-nos segundo a instrução e o conselho do Senhor.

[[v49-6-5]]

^<<v49-6-5,5>>^ Escravos, obedeçam a seus senhores terrenos com respeito e temor, com sinceridade de coração, como a Cristo.

[[v49-6-6]]

^<<v49-6-6,6>>^ Obedeçam-lhes não apenas para agradá-los quando eles os observam, mas como escravos de Cristo, fazendo de coração a vontade de Deus.

[[v49-6-7]]

^<<v49-6-7,7>>^ Sirvam aos seus senhores de boa vontade, como ao Senhor, e não aos homens,

[[v49-6-8]]

^<<v49-6-8,8>>^ porque vocês sabem que o Senhor recompensará a cada um pelo bem que praticar, seja escravo, seja livre.

[[v49-6-9]]

^<<v49-6-9,9>>^ Vocês, senhores, tratem seus escravos da mesma forma. Não os ameacem, uma vez que vocês sabem que o Senhor deles e de vocês está nos céus, e ele não faz diferença entre as pessoas.

[[v49-6-10]]

^<<v49-6-10,10>>^ Finalmente, fortaleçam-se no Senhor e no seu forte poder.

[[v49-6-11]]

^<<v49-6-11,11>>^ Vistam toda a armadura de Deus, para poderem ficar firmes contra as ciladas do diabo,

[[v49-6-12]]

^<<v49-6-12,12>>^ pois a nossa luta não é contra pessoas, mas contra os poderes e autoridades, contra os dominadores deste mundo de trevas, contra as forças espirituais do mal nas regiões celestiais.

[[v49-6-13]]

^<<v49-6-13,13>>^ Por isso, vistam toda a armadura de Deus, para que possam resistir no dia mau e permanecer inabaláveis, depois de terem feito tudo.

[[v49-6-14]]

^<<v49-6-14,14>>^ Assim, mantenham-se firmes, cingindo-se com o cinto da verdade, vestindo a couraça da justiça

[[v49-6-15]]

^<<v49-6-15,15>>^ e tendo os pés calçados com a prontidão do evangelho da paz.

[[v49-6-16]]

^<<v49-6-16,16>>^ Além disso, usem o escudo da fé, com o qual vocês poderão apagar todas as setas inflamadas do Maligno.

[[v49-6-17]]

^<<v49-6-17,17>>^ Usem o capacete da salvação e a espada do Espírito, que é a palavra de Deus.

[[v49-6-18]]

^<<v49-6-18,18>>^ Orem no Espírito em todas as ocasiões, com toda oração e súplica; tendo isso em mente, estejam atentos e perseverem na oração por todos os santos.

[[v49-6-19]]

^<<v49-6-19,19>>^ Orem também por mim, para que, quando eu falar, seja-me dada a mensagem a fim de que, destemidamente, torne conhecido o mistério do evangelho,

[[v49-6-20]]

^<<v49-6-20,20>>^ pelo qual sou embaixador preso em correntes. Orem para que, permanecendo nele, eu fale com coragem, como me cumpre fazer.

[[v49-6-21]]

^<<v49-6-21,21>>^ Tíquico, o irmão amado e fiel servo do Senhor, lhes informará tudo, para que vocês também saibam qual é a minha situação e o que estou fazendo.

[[v49-6-22]]

^<<v49-6-22,22>>^ Enviei-o a vocês por essa mesma razão, para que saibam como estamos e para que ele os encoraje.

[[v49-6-23]]

^<<v49-6-23,23>>^ Paz seja com os irmãos, e amor com fé da parte de Deus Pai e do Senhor Jesus Cristo.

[[v49-6-24]]

^<<v49-6-24,24>>^ A graça seja com todos os que amam a nosso Senhor Jesus Cristo com amor incorruptível.

'''

xref:049-efesios/049-efesios-005.adoc#v49-5-0[&#60; Capítulo Anterior] | <<v49-6-0,Topo>> | xref:050-filipenses/050-filipenses-001.adoc#v50-1-0[Próximo Capítulo &#62;]