include::./index.adoc[]

[[v49-1-0]]
=== Efésios, 1
// nvi ?, NVI - Nova Versão Internacional

[[v49-1-1]]

^<<v49-1-1,1>>^ Paulo, apóstolo de Cristo Jesus pela vontade de Deus, aos santos e fiéis em Cristo Jesus que estão em Éfeso:

[[v49-1-2]]

^<<v49-1-2,2>>^ A vocês, graça e paz da parte de Deus nosso Pai e do Senhor Jesus Cristo.

[[v49-1-3]]

^<<v49-1-3,3>>^ Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, que nos abençoou com todas as bênçãos espirituais nas regiões celestiais em Cristo.

[[v49-1-4]]

^<<v49-1-4,4>>^ Porque Deus nos escolheu nele antes da criação do mundo, para sermos santos e irrepreensíveis em sua presença.

[[v49-1-5]]

^<<v49-1-5,5>>^ Em amor nos predestinou para sermos adotados como filhos por meio de Jesus Cristo, conforme o bom propósito da sua vontade,

[[v49-1-6]]

^<<v49-1-6,6>>^ para o louvor da sua gloriosa graça, a qual nos deu gratuitamente no Amado.

[[v49-1-7]]

^<<v49-1-7,7>>^ Nele temos a redenção por meio de seu sangue, o perdão dos pecados, de acordo com as riquezas da graça de Deus,

[[v49-1-8]]

^<<v49-1-8,8>>^ a qual ele derramou sobre nós com toda a sabedoria e entendimento.

[[v49-1-9]]

^<<v49-1-9,9>>^ E nos revelou o mistério da sua vontade, de acordo com o seu bom propósito que ele estabeleceu em Cristo,

[[v49-1-10]]

^<<v49-1-10,10>>^ isto é, de fazer convergir em Cristo todas as coisas, celestiais ou terrenas, na dispensação da plenitude dos tempos.

[[v49-1-11]]

^<<v49-1-11,11>>^ Nele fomos também escolhidos, tendo sido predestinados conforme o plano daquele que faz todas as coisas segundo o propósito da sua vontade,

[[v49-1-12]]

^<<v49-1-12,12>>^ a fim de que nós, os que primeiro esperamos em Cristo, sejamos para o louvor da sua glória.

[[v49-1-13]]

^<<v49-1-13,13>>^ Nele, quando vocês ouviram e creram na palavra da verdade, o evangelho que os salvou, vocês foram selados com o Espírito Santo da promessa,

[[v49-1-14]]

^<<v49-1-14,14>>^ que é a garantia da nossa herança até a redenção daqueles que pertencem a Deus, para o louvor da sua glória.

[[v49-1-15]]

^<<v49-1-15,15>>^ Por essa razão, desde que ouvi falar da fé que vocês têm no Senhor Jesus e do amor que demonstram para com todos os santos,

[[v49-1-16]]

^<<v49-1-16,16>>^ não deixo de dar graças por vocês, mencionando-os em minhas orações.

[[v49-1-17]]

^<<v49-1-17,17>>^ Peço que o Deus de nosso Senhor Jesus Cristo, o glorioso Pai, lhes dê espírito de sabedoria e de revelação, no pleno conhecimento dele.

[[v49-1-18]]

^<<v49-1-18,18>>^ Oro também para que os olhos do coração de vocês sejam iluminados, a fim de que vocês conheçam a esperança para a qual ele os chamou, as riquezas da gloriosa herança dele nos santos

[[v49-1-19]]

^<<v49-1-19,19>>^ e a incomparável grandeza do seu poder para conosco, os que cremos, conforme a atuação da sua poderosa força.

[[v49-1-20]]

^<<v49-1-20,20>>^ Esse poder ele exerceu em Cristo, ressuscitando-o dos mortos e fazendo-o assentar-se à sua direita, nas regiões celestiais,

[[v49-1-21]]

^<<v49-1-21,21>>^ muito acima de todo governo e autoridade, poder e domínio, e de todo nome que se possa mencionar, não apenas nesta era, mas também na que há de vir.

[[v49-1-22]]

^<<v49-1-22,22>>^ Deus colocou todas as coisas debaixo de seus pés e o designou como cabeça de todas as coisas para a igreja,

[[v49-1-23]]

^<<v49-1-23,23>>^ que é o seu corpo, a plenitude daquele que enche todas as coisas, em toda e qualquer circunstância.

'''

xref:048-galatas/048-galatas-006.adoc#v48-6-0[&#60; Capítulo Anterior] | <<v49-1-0,Topo>> | xref:049-efesios/049-efesios-002.adoc#v49-2-0[Próximo Capítulo &#62;]