include::./index.adoc[]

[[v49-4-0]]
=== Efésios, 4
// nvi ?, NVI - Nova Versão Internacional

[[v49-4-1]]

^<<v49-4-1,1>>^ Como prisioneiro no Senhor, rogo-lhes que vivam de maneira digna da vocação que receberam.

[[v49-4-2]]

^<<v49-4-2,2>>^ Sejam completamente humildes e dóceis, e sejam pacientes, suportando uns aos outros com amor.

[[v49-4-3]]

^<<v49-4-3,3>>^ Façam todo o esforço para conservar a unidade do Espírito pelo vínculo da paz.

[[v49-4-4]]

^<<v49-4-4,4>>^ Há um só corpo e um só Espírito, assim como a esperança para a qual vocês foram chamados é uma só;

[[v49-4-5]]

^<<v49-4-5,5>>^ há um só Senhor, uma só fé, um só batismo,

[[v49-4-6]]

^<<v49-4-6,6>>^ um só Deus e Pai de todos, que é sobre todos, por meio de todos e em todos.

[[v49-4-7]]

^<<v49-4-7,7>>^ E a cada um de nós foi concedida a graça, conforme a medida repartida por Cristo.

[[v49-4-8]]

^<<v49-4-8,8>>^ Por isso é que foi dito: "Quando ele subiu em triunfo às alturas, levou cativo muitos prisioneiros, e deu dons aos homens".

[[v49-4-9]]

^<<v49-4-9,9>>^ ( Que significa "ele subiu", senão que também descera às profundezas da terra?

[[v49-4-10]]

^<<v49-4-10,10>>^ Aquele que desceu é o mesmo que subiu acima de todos os céus, a fim de encher todas as coisas. )

[[v49-4-11]]

^<<v49-4-11,11>>^ E ele designou alguns para apóstolos, outros para profetas, outros para evangelistas, e outros para pastores e mestres,

[[v49-4-12]]

^<<v49-4-12,12>>^ com o fim de preparar os santos para a obra do ministério, para que o corpo de Cristo seja edificado,

[[v49-4-13]]

^<<v49-4-13,13>>^ até que todos alcancemos a unidade da fé e do conhecimento do Filho de Deus, e cheguemos à maturidade, atingindo a medida da plenitude de Cristo.

[[v49-4-14]]

^<<v49-4-14,14>>^ O propósito é que não sejamos mais como crianças, levados de um lado para outro pelas ondas, nem jogados para cá e para lá por todo vento de doutrina e pela astúcia e esperteza de homens que induzem ao erro.

[[v49-4-15]]

^<<v49-4-15,15>>^ Antes, seguindo a verdade em amor, cresçamos em tudo naquele que é a cabeça, Cristo.

[[v49-4-16]]

^<<v49-4-16,16>>^ Dele todo o corpo, ajustado e unido pelo auxílio de todas as juntas, cresce e edifica-se a si mesmo em amor, na medida em que cada parte realiza a sua função.

[[v49-4-17]]

^<<v49-4-17,17>>^ Assim, eu lhes digo, e no Senhor insisto, que não vivam mais como os gentios, que vivem na futilidade dos seus pensamentos.

[[v49-4-18]]

^<<v49-4-18,18>>^ Eles estão obscurecidos no entendimento e separados da vida de Deus por causa da ignorância em que estão, devido ao endurecimento dos seus corações.

[[v49-4-19]]

^<<v49-4-19,19>>^ Tendo perdido toda a sensibilidade, ele se entregaram à depravação, cometendo com avidez toda espécie de impureza.

[[v49-4-20]]

^<<v49-4-20,20>>^ Todavia, não foi assim que vocês aprenderam de Cristo.

[[v49-4-21]]

^<<v49-4-21,21>>^ De fato, vocês ouviram falar dele, e nele foram ensinados de acordo com a verdade que está em Jesus.

[[v49-4-22]]

^<<v49-4-22,22>>^ Quanto à antiga maneira de viver, vocês foram ensinados a despir-se do velho homem, que se corrompe por desejos enganosos,

[[v49-4-23]]

^<<v49-4-23,23>>^ a serem renovados no modo de pensar e

[[v49-4-24]]

^<<v49-4-24,24>>^ a revestir-se do novo homem, criado para ser semelhante a Deus em justiça e em santidade provenientes da verdade.

[[v49-4-25]]

^<<v49-4-25,25>>^ Portanto, cada um de vocês deve abandonar a mentira e falar a verdade ao seu próximo, pois todos somos membros de um mesmo corpo.

[[v49-4-26]]

^<<v49-4-26,26>>^ "Quando vocês ficarem irados, não pequem". Apazigüem a sua ira antes que o sol se ponha,

[[v49-4-27]]

^<<v49-4-27,27>>^ e não dêem lugar ao diabo.

[[v49-4-28]]

^<<v49-4-28,28>>^ O que furtava não furte mais; antes trabalhe, fazendo algo de útil com as mãos, para que tenha o que repartir com quem estiver em necessidade.

[[v49-4-29]]

^<<v49-4-29,29>>^ Nenhuma palavra torpe saia da boca de vocês, mas apenas a que for útil para edificar os outros, conforme a necessidade, para que conceda graça aos que a ouvem.

[[v49-4-30]]

^<<v49-4-30,30>>^ Não entristeçam o Espírito Santo de Deus, com o qual vocês foram selados para o dia da redenção.

[[v49-4-31]]

^<<v49-4-31,31>>^ Livrem-se de toda amargura, indignação e ira, gritaria e calúnia, bem como de toda maldade.

[[v49-4-32]]

^<<v49-4-32,32>>^ Sejam bondosos e compassivos uns para com os outros, perdoando-se mutuamente, assim como Deus perdoou vocês em Cristo.

'''

xref:049-efesios/049-efesios-003.adoc#v49-3-0[&#60; Capítulo Anterior] | <<v49-4-0,Topo>> | xref:049-efesios/049-efesios-005.adoc#v49-5-0[Próximo Capítulo &#62;]