include::./index.adoc[]

[[v49-3-0]]
=== Efésios, 3
// nvi ?, NVI - Nova Versão Internacional

[[v49-3-1]]

^<<v49-3-1,1>>^ Por essa razão, eu, Paulo, prisioneiro de Cristo Jesus por amor de vocês, gentios —

[[v49-3-2]]

^<<v49-3-2,2>>^ Certamente vocês ouviram falar da responsabilidade imposta a mim em favor de vocês pela graça de Deus,

[[v49-3-3]]

^<<v49-3-3,3>>^ isto é, o mistério que me foi dado a conhecer por revelação, como já lhes escrevi brevemente.

[[v49-3-4]]

^<<v49-3-4,4>>^ Ao lerem isso vocês poderão entender a minha compreensão do mistério de Cristo.

[[v49-3-5]]

^<<v49-3-5,5>>^ Esse mistério não foi dado a conhecer aos homens doutras gerações, mas agora foi revelado pelo Espírito aos santos apóstolos e profetas de Deus,

[[v49-3-6]]

^<<v49-3-6,6>>^ a saber, que mediante o evangelho os gentios são co-herdeiros com Israel, membros do mesmo corpo, e co-participantes da promessa em Cristo Jesus.

[[v49-3-7]]

^<<v49-3-7,7>>^ Deste me tornei ministro pelo dom da graça de Deus, a mim concedida pela operação de seu poder.

[[v49-3-8]]

^<<v49-3-8,8>>^ Embora eu seja o menor dos menores dentre todos os santos, foi-me concedida esta graça de anunciar aos gentios as insondáveis riquezas de Cristo

[[v49-3-9]]

^<<v49-3-9,9>>^ e esclarecer a todos a administração deste mistério que, durante as épocas passadas, foi mantido oculto em Deus, que criou todas as coisas.

[[v49-3-10]]

^<<v49-3-10,10>>^ A intenção dessa graça era que agora, mediante a igreja, a multiforme sabedoria de Deus se tornasse conhecida dos poderes e autoridades nas regiões celestiais,

[[v49-3-11]]

^<<v49-3-11,11>>^ de acordo com o seu eterno plano que ele realizou em Cristo Jesus, nosso Senhor,

[[v49-3-12]]

^<<v49-3-12,12>>^ por intermédio de quem temos livre acesso a Deus em confiança, pela fé nele.

[[v49-3-13]]

^<<v49-3-13,13>>^ Portanto, peço-lhes que não se desanimem por causa das minhas tribulações em seu favor, pois elas são uma glória para vocês.

[[v49-3-14]]

^<<v49-3-14,14>>^ Por essa razão, ajoelho-me diante do Pai,

[[v49-3-15]]

^<<v49-3-15,15>>^ do qual recebe o nome toda a família nos céus e na terra.

[[v49-3-16]]

^<<v49-3-16,16>>^ Oro para que, com as suas gloriosas riquezas, ele os fortaleça no íntimo do seu ser com poder, por meio do seu Espírito,

[[v49-3-17]]

^<<v49-3-17,17>>^ para que Cristo habite em seus corações mediante a fé; e oro para que vocês, arraigados e alicerçados em amor,

[[v49-3-18]]

^<<v49-3-18,18>>^ possam, juntamente com todos os santos, compreender a largura, o comprimento, a altura e a profundidade,

[[v49-3-19]]

^<<v49-3-19,19>>^ e conhecer o amor de Cristo que excede todo conhecimento, para que vocês sejam cheios de toda a plenitude de Deus.

[[v49-3-20]]

^<<v49-3-20,20>>^ Àquele que é capaz de fazer infinitamente mais do que tudo o que pedimos ou pensamos, de acordo com o seu poder que atua em nós,

[[v49-3-21]]

^<<v49-3-21,21>>^ a ele seja a glória na igreja e em Cristo Jesus, por todas as gerações, para todo o sempre! Amém!

'''

xref:049-efesios/049-efesios-002.adoc#v49-2-0[&#60; Capítulo Anterior] | <<v49-3-0,Topo>> | xref:049-efesios/049-efesios-004.adoc#v49-4-0[Próximo Capítulo &#62;]