include::./index.adoc[]

[[v37-2-0]]
=== Ageu, 2
// nvi ?, NVI - Nova Versão Internacional

[[v37-2-1]]

^<<v37-2-1,1>>^ No dia vinte e um do sétimo mês, veio a palavra do Senhor por meio do profeta Ageu:

[[v37-2-2]]

^<<v37-2-2,2>>^ "Pergunte ao governador de Judá, Zorobabel, filho de Sealtiel, ao sumo sacerdote Josué, filho de Jeozadaque, e ao restante do povo, o seguinte:

[[v37-2-3]]

^<<v37-2-3,3>>^ ‘Quem de vocês viu este templo em seu primeiro esplendor? Comparado com ele, não é como nada o que vocês vêem agora?

[[v37-2-4]]

^<<v37-2-4,4>>^ "Coragem, Zorobabel", declara o Senhor. "Coragem, sumo sacerdote Josué, filho de Jeozadaque. Coragem! Ao trabalho, ó povo da terra! ", declara o Senhor. "Porque eu estou com vocês", declara o Senhor dos Exércitos.

[[v37-2-5]]

^<<v37-2-5,5>>^ Esta é a aliança que fiz com vocês quando vocês saíram do Egito: "Meu espírito está entre vocês. Não tenham medo".

[[v37-2-6]]

^<<v37-2-6,6>>^ Assim diz o Senhor dos Exércitos: "Dentro de pouco tempo farei tremer o céu, a terra, o mar e o continente.

[[v37-2-7]]

^<<v37-2-7,7>>^ Farei tremer todas as nações, que trarão para cá os seus tesouros, e encherei este templo de glória", diz o Senhor dos Exércitos.

[[v37-2-8]]

^<<v37-2-8,8>>^ "Tanto a prata quanto o ouro me pertencem", declara o Senhor dos Exércitos.

[[v37-2-9]]

^<<v37-2-9,9>>^ "A glória deste novo templo será maior do que a do antigo", diz o Senhor dos Exércitos. "E neste lugar estabelecerei a paz", declara o Senhor dos Exércitos.

[[v37-2-10]]

^<<v37-2-10,10>>^ No dia vinte e quatro do nono mês, no segundo ano do reinado de Dario, a palavra do Senhor veio ao profeta Ageu:

[[v37-2-11]]

^<<v37-2-11,11>>^ "Assim diz o Senhor dos Exércitos: ‘Pergunte aos sacerdotes sobre a seguinte questão da Lei:

[[v37-2-12]]

^<<v37-2-12,12>>^ Se alguém levar carne consagrada na borda de suas vestes, e com ela tocar num pão, ou em algo cozido, ou em vinho, ou em azeite ou em qualquer comida, isso ficará consagrado? ’ " Os sacerdotes responderam: "Não".

[[v37-2-13]]

^<<v37-2-13,13>>^ Em seguida perguntou Ageu: "Se alguém ficar impuro por tocar num cadáver e depois tocar em alguma dessas coisas, ela ficará impura? "Sim", responderam os sacerdotes, "ficará impura".

[[v37-2-14]]

^<<v37-2-14,14>>^ Então disse Ageu: "É o que acontece com este povo e com esta nação", declara o Senhor. "Tudo o que fazem e tudo o que me oferecem é impuro".

[[v37-2-15]]

^<<v37-2-15,15>>^ "Agora prestem atenção: de hoje em diante reconsiderem. Como eram as coisas antes que se colocasse pedra sobre pedra no templo do Senhor?

[[v37-2-16]]

^<<v37-2-16,16>>^ Quando alguém chegava a um monte de trigo procurando vinte medidas, havia apenas dez. Quando alguém ia ao depósito de vinho para tirar cinqüenta medidas, só encontrava vinte.

[[v37-2-17]]

^<<v37-2-17,17>>^ Eu destruí todo o trabalho das mãos de vocês, com mofo, ferrugem e granizo, mas vocês não se voltaram para mim", declara o Senhor.

[[v37-2-18]]

^<<v37-2-18,18>>^ "A partir de hoje, dia vinte e quatro do nono mês, atentem para o dia em que os fundamentos do templo do Senhor foram lançados. Reconsiderem:

[[v37-2-19]]

^<<v37-2-19,19>>^ Ainda há alguma semente no celeiro? Até hoje a videira, a figueira, a romeira e a oliveira não têm dado fruto. Mas, de hoje em diante, abençoarei vocês".

[[v37-2-20]]

^<<v37-2-20,20>>^ A palavra do Senhor veio a Ageu pela segunda vez, no dia vinte e quatro do nono mês:

[[v37-2-21]]

^<<v37-2-21,21>>^ "Diga a Zorobabel, governador de Judá, que eu farei tremer o céu e a terra.

[[v37-2-22]]

^<<v37-2-22,22>>^ Derrubarei tronos e destruirei o poder dos reinos estrangeiros. Virarei os carros e os seus condutores; os cavalos e os seus cavaleiros cairão, cada um pela espada do seu companheiro".

[[v37-2-23]]

^<<v37-2-23,23>>^ "Naquele dia", declara o Senhor dos Exércitos, "eu o tomarei, meu servo Zorobabel, filho de Sealtiel", declara o Senhor, "e farei de você um anel de selar, porque o tenho escolhido", declara o Senhor dos Exércitos.

'''

xref:037-ageu/037-ageu-001.adoc#v37-1-0[&#60; Capítulo Anterior] | <<v37-2-0,Topo>> | xref:038-zacarias/038-zacarias-001.adoc#v38-1-0[Próximo Capítulo &#62;]