include::./index.adoc[]

[[v37-1-0]]
=== Ageu, 1
// nvi ?, NVI - Nova Versão Internacional

[[v37-1-1]]

^<<v37-1-1,1>>^ No primeiro dia do sexto mês do segundo ano do reinado de Dario, a palavra do Senhor veio por meio do profeta Ageu ao governador de Judá, Zorobabel, filho de Sealtiel, e ao sumo sacerdote Josué, filho de Jeozadaque, dizendo:

[[v37-1-2]]

^<<v37-1-2,2>>^ "Assim diz o Senhor dos Exércitos: Este povo afirma: ‘Ainda não chegou o tempo de reconstruir a casa do Senhor’ ".

[[v37-1-3]]

^<<v37-1-3,3>>^ Por isso, a palavra do Senhor veio novamente por meio do profeta Ageu:

[[v37-1-4]]

^<<v37-1-4,4>>^ "Acaso é tempo de vocês morarem em casas de fino acabamento, enquanto a minha casa continua destruída? "

[[v37-1-5]]

^<<v37-1-5,5>>^ Agora, assim diz o Senhor dos Exércitos: "Vejam aonde os seus caminhos os levaram.

[[v37-1-6]]

^<<v37-1-6,6>>^ Vocês têm plantado muito, e colhido pouco. Vocês comem, mas não se fartam. Bebem, mas não se satisfazem. Vestem-se, mas não se aquecem. Aquele que recebe salário, recebe-o para colocá-lo numa bolsa furada".

[[v37-1-7]]

^<<v37-1-7,7>>^ Assim diz o Senhor dos Exércitos: "Vejam aonde os seus caminhos os levaram!

[[v37-1-8]]

^<<v37-1-8,8>>^ Subam o monte para trazer madeira. Construam o templo, para que eu me alegre e nele seja glorificado", diz o Senhor.

[[v37-1-9]]

^<<v37-1-9,9>>^ "Vocês esperavam muito, mas, para surpresa de vocês, acabou sendo pouco. E o que vocês trouxeram para casa eu dissipei com um sopro. E por que fiz isso? ", pergunta o Senhor dos Exércitos. "Por causa do meu templo, que ainda está destruído, enquanto cada um de vocês se ocupa com a sua própria casa.

[[v37-1-10]]

^<<v37-1-10,10>>^ Por isso, por causa de vocês, o céu reteu o orvalho e a terra deixou de dar o seu fruto.

[[v37-1-11]]

^<<v37-1-11,11>>^ Provoquei uma seca nos campos e nos montes, que atingiu o trigo, o vinho, o azeite e tudo mais que a terra produz, e também os homens e o gado. O trabalho das mãos de vocês foi prejudicado".

[[v37-1-12]]

^<<v37-1-12,12>>^ Zorobabel, filho de Sealtiel, o sumo sacerdote Josué, filho de Jeozadaque, e todo o restante do povo obedeceram à voz do Senhor, o seu Deus, por causa das palavras do profeta Ageu, a quem o Senhor, o seu Deus, enviara. E o povo temeu ao Senhor.

[[v37-1-13]]

^<<v37-1-13,13>>^ Então Ageu, o mensageiro do Senhor, trouxe esta mensagem do Senhor para o povo: "Eu estou com vocês", declara o Senhor.

[[v37-1-14]]

^<<v37-1-14,14>>^ Assim o Senhor encorajou o governador de Judá, Zorobabel, filho de Sealtiel, o sumo sacerdote Josué, filho de Jeozadaque, e todo o restante do povo, de modo que eles começaram a trabalhar no templo do Senhor dos Exércitos, o seu Deus,

[[v37-1-15]]

^<<v37-1-15,15>>^ no dia vinte e quatro do sexto mês do segundo ano do reinado de Dario.

'''

xref:036-sofonias/036-sofonias-003.adoc#v36-3-0[&#60; Capítulo Anterior] | <<v37-1-0,Topo>> | xref:037-ageu/037-ageu-002.adoc#v37-2-0[Próximo Capítulo &#62;]