include::./index.adoc[]

[[v60-5-0]]
=== 1 Pedro, 5
// nvi ?, NVI - Nova Versão Internacional

[[v60-5-1]]

^<<v60-5-1,1>>^ Portanto, apelo para os presbíteros que há entre vocês, e o faço na qualidade de presbítero como eles e testemunha dos sofrimentos de Cristo, como alguém que participará da glória a ser revelada:

[[v60-5-2]]

^<<v60-5-2,2>>^ Pastoreiem o rebanho de Deus que está aos seus cuidados. Olhem por ele, não por obrigação, mas de livre vontade, como Deus quer. Não façam isso por ganância, mas com o desejo de servir.

[[v60-5-3]]

^<<v60-5-3,3>>^ Não ajam como dominadores dos que lhes foram confiados, mas como exemplos para o rebanho.

[[v60-5-4]]

^<<v60-5-4,4>>^ Quando se manifestar o Supremo Pastor, vocês receberão a imperecível coroa da glória.

[[v60-5-5]]

^<<v60-5-5,5>>^ Da mesma forma jovens, sujeitem-se aos mais velhos. Sejam todos humildes uns para com os outros, porque "Deus se opõe aos orgulhosos, mas concede graça aos humildes".

[[v60-5-6]]

^<<v60-5-6,6>>^ Portanto, humilhem-se debaixo da poderosa mão de Deus, para que ele os exalte no tempo devido.

[[v60-5-7]]

^<<v60-5-7,7>>^ Lancem sobre ele toda a sua ansiedade, porque ele tem cuidado de vocês.

[[v60-5-8]]

^<<v60-5-8,8>>^ Sejam sóbrios e vigiem. O diabo, o inimigo de vocês, anda ao redor como leão, rugindo e procurando a quem possa devorar.

[[v60-5-9]]

^<<v60-5-9,9>>^ Resistam-lhe, permanecendo firmes na fé, sabendo que os irmãos que vocês têm em todo o mundo estão passando pelos mesmos sofrimentos.

[[v60-5-10]]

^<<v60-5-10,10>>^ O Deus de toda a graça, que os chamou para a sua glória eterna em Cristo Jesus, depois de terem sofrido durante pouco de tempo, os restaurará, os confirmará, lhes dará forças e os porá sobre firmes alicerces.

[[v60-5-11]]

^<<v60-5-11,11>>^ A ele seja o poder para todo o sempre. Amém.

[[v60-5-12]]

^<<v60-5-12,12>>^ Com a ajuda de Silvano, a quem considero irmão fiel, eu lhes escrevi resumidamente, encorajando-os e testemunhando que esta é a verdadeira graça de Deus. Mantenham-se firmes na graça de Deus.

[[v60-5-13]]

^<<v60-5-13,13>>^ Aquela que está em Babilônia, também eleita, envia-lhes saudações, e também Marcos, meu filho.

[[v60-5-14]]

^<<v60-5-14,14>>^ Saúdem uns aos outros com beijo de santo amor. Paz a todos vocês que estão em Cristo.

'''

xref:060-1-pedro/060-1-pedro-004.adoc#v60-4-0[&#60; Capítulo Anterior] | <<v60-5-0,Topo>> | xref:061-2-pedro/061-2-pedro-001.adoc#v61-1-0[Próximo Capítulo &#62;]