include::./index.adoc[]

[[v60-2-0]]
=== 1 Pedro, 2
// nvi ?, NVI - Nova Versão Internacional

[[v60-2-1]]

^<<v60-2-1,1>>^ Livrem-se, pois, de toda maldade e de todo engano, hipocrisia, inveja e toda espécie de maledicência.

[[v60-2-2]]

^<<v60-2-2,2>>^ Como crianças recém-nascidas, desejem de coração o leite espiritual puro, para que por meio dele cresçam para a salvação,

[[v60-2-3]]

^<<v60-2-3,3>>^ agora que provaram que o Senhor é bom.

[[v60-2-4]]

^<<v60-2-4,4>>^ À medida que se aproximam dele, a pedra viva — rejeitada pelos homens, mas escolhida por Deus e preciosa para ele —

[[v60-2-5]]

^<<v60-2-5,5>>^ vocês também estão sendo utilizados como pedras vivas na edificação de uma casa espiritual para serem sacerdócio santo, oferecendo sacrifícios espirituais aceitáveis a Deus, por meio de Jesus Cristo.

[[v60-2-6]]

^<<v60-2-6,6>>^ Pois assim é dito na Escritura: "Eis que ponho em Sião uma pedra angular, escolhida e preciosa, e aquele que nela confia jamais será envergonhado".

[[v60-2-7]]

^<<v60-2-7,7>>^ Portanto, para vocês, os que crêem, esta pedra é preciosa; mas para os que não crêem, "a pedra que os construtores rejeitaram tornou-se a pedra angular",

[[v60-2-8]]

^<<v60-2-8,8>>^ e, "pedra de tropeço e rocha que faz cair". Os que não crêem tropeçam, porque desobedecem à mensagem; para o que também foram destinados.

[[v60-2-9]]

^<<v60-2-9,9>>^ Vocês, porém, são geração eleita, sacerdócio real, nação santa, povo exclusivo de Deus, para anunciar as grandezas daquele que os chamou das trevas para a sua maravilhosa luz.

[[v60-2-10]]

^<<v60-2-10,10>>^ Antes vocês nem sequer eram povo, mas agora são povo de Deus; não haviam recebido misericórdia, mas agora a receberam.

[[v60-2-11]]

^<<v60-2-11,11>>^ Amados, insisto em que, como estrangeiros e peregrinos no mundo, vocês se abstenham dos desejos carnais que guerreiam contra a alma.

[[v60-2-12]]

^<<v60-2-12,12>>^ Vivam entre os pagãos de maneira exemplar para que, naquilo em que eles os acusam de praticarem o mal, observem as boas obras que vocês praticam e glorifiquem a Deus no dia da sua intervenção.

[[v60-2-13]]

^<<v60-2-13,13>>^ Por causa do Senhor, sujeitem-se a toda autoridade constituída entre os homens; seja ao rei, como autoridade suprema,

[[v60-2-14]]

^<<v60-2-14,14>>^ seja aos governantes, como por ele enviados para punir os que praticam o mal e honrar os que praticam o bem.

[[v60-2-15]]

^<<v60-2-15,15>>^ Pois é da vontade de Deus que, praticando o bem, vocês silenciem a ignorância dos insensatos.

[[v60-2-16]]

^<<v60-2-16,16>>^ Vivam como pessoas livres, mas não usem a liberdade como desculpa para fazer o mal; vivam como servos de Deus.

[[v60-2-17]]

^<<v60-2-17,17>>^ Tratem a todos com o devido respeito: amem os irmãos, temam a Deus e honrem o rei.

[[v60-2-18]]

^<<v60-2-18,18>>^ Escravos, sujeitem-se a seus senhores com todo o respeito, não apenas aos bons e amáveis, mas também aos maus.

[[v60-2-19]]

^<<v60-2-19,19>>^ Porque é louvável que, por motivo de sua consciência para com Deus, alguém suporte aflições sofrendo injustamente.

[[v60-2-20]]

^<<v60-2-20,20>>^ Pois que vantagem há em suportar açoites recebidos por terem cometido o mal? Mas se vocês suportam o sofrimento por terem feito o bem, isso é louvável diante de Deus.

[[v60-2-21]]

^<<v60-2-21,21>>^ Para isso vocês foram chamados, pois também Cristo sofreu no lugar de vocês, deixando-lhes exemplo, para que sigam os seus passos.

[[v60-2-22]]

^<<v60-2-22,22>>^ "Ele não cometeu pecado algum, e nenhum engano foi encontrado em sua boca".

[[v60-2-23]]

^<<v60-2-23,23>>^ Quando insultado, não revidava; quando sofria, não fazia ameaças, mas entregava-se àquele que julga com justiça.

[[v60-2-24]]

^<<v60-2-24,24>>^ Ele mesmo levou em seu corpo os nossos pecados sobre o madeiro, a fim de que morrêssemos para os pecados e vivêssemos para a justiça; por suas feridas vocês foram curados.

[[v60-2-25]]

^<<v60-2-25,25>>^ Pois vocês eram como ovelhas desgarradas, mas agora se converteram ao Pastor e Bispo de suas almas.

'''

xref:060-1-pedro/060-1-pedro-001.adoc#v60-1-0[&#60; Capítulo Anterior] | <<v60-2-0,Topo>> | xref:060-1-pedro/060-1-pedro-003.adoc#v60-3-0[Próximo Capítulo &#62;]