include::./index.adoc[]

[[v60-1-0]]
=== 1 Pedro, 1
// nvi ?, NVI - Nova Versão Internacional

[[v60-1-1]]

^<<v60-1-1,1>>^ Pedro, apóstolo de Jesus Cristo, aos eleitos de Deus, peregrinos dispersos no Ponto, na Galácia, na Capadócia, na província da Ásia e na Bitínia,

[[v60-1-2]]

^<<v60-1-2,2>>^ escolhidos de acordo com a pré-conhecimento de Deus Pai, pela obra santificadora do Espírito, para a obediência a Jesus Cristo e a aspersão do seu sangue: Graça e paz lhes sejam multiplicadas.

[[v60-1-3]]

^<<v60-1-3,3>>^ Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo! Conforme a sua grande misericórdia, ele nos regenerou para uma esperança viva, por meio da ressurreição de Jesus Cristo dentre os mortos,

[[v60-1-4]]

^<<v60-1-4,4>>^ para uma herança que jamais poderá perecer, macular-se ou perder o seu valor. Herança guardada nos céus para vocês

[[v60-1-5]]

^<<v60-1-5,5>>^ que, mediante a fé, são protegidos pelo poder de Deus até chegar a salvação prestes a ser revelada no último tempo.

[[v60-1-6]]

^<<v60-1-6,6>>^ Nisso vocês exultam, ainda que agora, por um pouco de tempo, devam ser entristecidos por todo tipo de provação.

[[v60-1-7]]

^<<v60-1-7,7>>^ Assim acontece para que fique comprovado que a fé que vocês têm, muito mais valiosa do que o ouro que perece, mesmo que refinado pelo fogo, é genuína e resultará em louvor, glória e honra, quando Jesus Cristo for revelado.

[[v60-1-8]]

^<<v60-1-8,8>>^ Mesmo não o tendo visto, vocês o amam; e apesar de não o verem agora, crêem nele e exultam com alegria indizível e gloriosa,

[[v60-1-9]]

^<<v60-1-9,9>>^ pois vocês estão alcançando o alvo da sua fé, a salvação das suas almas.

[[v60-1-10]]

^<<v60-1-10,10>>^ Foi a respeito dessa salvação que os profetas que falaram da graça destinada a vocês investigaram e examinaram,

[[v60-1-11]]

^<<v60-1-11,11>>^ procurando saber o tempo e as circunstâncias para os quais apontava o Espírito de Cristo que neles estava, quando lhes predisse os sofrimentos de Cristo e as glórias que se seguiriam àqueles sofrimentos.

[[v60-1-12]]

^<<v60-1-12,12>>^ A eles foi revelado que estavam ministrando, não para si próprios, mas para vocês, quando falaram das coisas que agora lhes foram anunciadas por meio daqueles que lhes pregaram o evangelho pelo Espírito Santo enviado do céu; coisas que até os anjos anseiam observar.

[[v60-1-13]]

^<<v60-1-13,13>>^ Portanto, estejam com a mente preparada, prontos para a ação; sejam sóbrios e coloquem toda a esperança na graça que lhes será dada quando Jesus Cristo for revelado.

[[v60-1-14]]

^<<v60-1-14,14>>^ Como filhos obedientes, não se deixem amoldar pelos maus desejos de outrora, quando viviam na ignorância.

[[v60-1-15]]

^<<v60-1-15,15>>^ Mas, assim como é santo aquele que os chamou, sejam santos vocês também em tudo o que fizerem,

[[v60-1-16]]

^<<v60-1-16,16>>^ pois está escrito: "Sejam santos, porque eu sou santo".

[[v60-1-17]]

^<<v60-1-17,17>>^ Uma vez que vocês chamam Pai aquele que julga imparcialmente as obras de cada um, portem-se com temor durante a jornada terrena de vocês.

[[v60-1-18]]

^<<v60-1-18,18>>^ Pois vocês sabem que não foi por meio de coisas perecíveis como prata ou ouro que vocês foram redimidos da sua maneira vazia de viver que lhes foi transmitida por seus antepassados,

[[v60-1-19]]

^<<v60-1-19,19>>^ mas pelo precioso sangue de Cristo, como de um cordeiro sem mancha e sem defeito,

[[v60-1-20]]

^<<v60-1-20,20>>^ conhecido antes da criação do mundo, revelado nestes últimos tempos em favor de vocês.

[[v60-1-21]]

^<<v60-1-21,21>>^ Por meio dele vocês crêem em Deus, que o ressuscitou dentre os mortos e o glorificou, de modo que a fé e a esperança de vocês estão em Deus.

[[v60-1-22]]

^<<v60-1-22,22>>^ Agora que vocês purificaram as suas vidas pela obediência à verdade, visando ao amor fraternal e sincero, amem sinceramente uns aos outros e de todo o coração.

[[v60-1-23]]

^<<v60-1-23,23>>^ Pois vocês foram regenerados, não de uma semente perecível, mas imperecível, por meio da palavra de Deus, viva e permanente.

[[v60-1-24]]

^<<v60-1-24,24>>^ Pois, "toda a humanidade é como a relva, e toda a sua glória, como a flor da relva; a relva murcha e cai a sua flor,

[[v60-1-25]]

^<<v60-1-25,25>>^ mas a palavra do Senhor permanece para sempre". Essa é a palavra que lhes foi anunciada.

'''

xref:059-tiago/059-tiago-005.adoc#v59-5-0[&#60; Capítulo Anterior] | <<v60-1-0,Topo>> | xref:060-1-pedro/060-1-pedro-002.adoc#v60-2-0[Próximo Capítulo &#62;]