include::./index.adoc[]

[[v60-3-0]]
=== 1 Pedro, 3
// nvi ?, NVI - Nova Versão Internacional

[[v60-3-1]]

^<<v60-3-1,1>>^ Do mesmo modo, mulheres, sujeitem-se a seus maridos, a fim de que, se alguns deles não obedecem à palavra, sejam ganhos sem palavras, pelo procedimento de sua mulher,

[[v60-3-2]]

^<<v60-3-2,2>>^ observando a conduta honesta e respeitosa de vocês.

[[v60-3-3]]

^<<v60-3-3,3>>^ A beleza de vocês não deve estar nos enfeites exteriores, como cabelos trançados e jóias de ouro ou roupas finas.

[[v60-3-4]]

^<<v60-3-4,4>>^ Pelo contrário, esteja no ser interior, que não perece, beleza demonstrada num espírito dócil e tranqüilo, o que é de grande valor para Deus.

[[v60-3-5]]

^<<v60-3-5,5>>^ Pois era assim que também costumavam adornar-se as santas mulheres do passado, que colocavam a sua esperança em Deus. Elas se sujeitavam a seus maridos,

[[v60-3-6]]

^<<v60-3-6,6>>^ como Sara, que obedecia a Abraão e lhe chamava senhor. Dela vocês serão filhas, se praticarem o bem e não derem lugar ao medo.

[[v60-3-7]]

^<<v60-3-7,7>>^ Do mesmo modo vocês, maridos, sejam sábios no convívio com suas mulheres e tratem-nas com honra, como parte mais frágil e co-herdeiras do dom da graça da vida, de forma que não sejam interrompidas as suas orações.

[[v60-3-8]]

^<<v60-3-8,8>>^ Quanto ao mais, tenham todos o mesmo modo de pensar, sejam compassivos, amem-se fraternalmente, sejam misericordiosos e humildes.

[[v60-3-9]]

^<<v60-3-9,9>>^ Não retribuam mal com mal nem insulto com insulto; pelo contrário, bendigam; pois para isso vocês foram chamados, para receberem bênção por herança.

[[v60-3-10]]

^<<v60-3-10,10>>^ Pois, "quem quiser amar a vida e ver dias felizes, guarde a sua língua do mal e os seus lábios da falsidade.

[[v60-3-11]]

^<<v60-3-11,11>>^ Afaste-se do mal e faça o bem; busque a paz com perseverança.

[[v60-3-12]]

^<<v60-3-12,12>>^ Porque os olhos do Senhor estão sobre os justos e os seus ouvidos estão atentos à sua oração, mas o rosto do Senhor volta-se contra os que praticam o mal".

[[v60-3-13]]

^<<v60-3-13,13>>^ Quem há de maltratá-los, se vocês forem zelosos na prática do bem?

[[v60-3-14]]

^<<v60-3-14,14>>^ Todavia, mesmo que venham a sofrer porque praticam a justiça, vocês serão felizes. "Não temam aquilo que eles temem, não fiquem amedrontados. "

[[v60-3-15]]

^<<v60-3-15,15>>^ Antes, santifiquem Cristo como Senhor no coração. Estejam sempre preparados para responder a qualquer que lhes pedir a razão da esperança que há em vocês.

[[v60-3-16]]

^<<v60-3-16,16>>^ Contudo, façam isso com mansidão e respeito, conservando boa consciência, de forma que os que falam maldosamente contra o bom procedimento de vocês, porque estão em Cristo, fiquem envergonhados de suas calúnias.

[[v60-3-17]]

^<<v60-3-17,17>>^ É melhor sofrer por fazer o bem, se for da vontade de Deus, do que por fazer o mal.

[[v60-3-18]]

^<<v60-3-18,18>>^ Pois também Cristo sofreu pelos pecados uma vez por todas, o justo pelos injustos, para conduzir-nos a Deus. Ele foi morto no corpo, mas vivificado pelo Espírito,

[[v60-3-19]]

^<<v60-3-19,19>>^ no qual também foi e pregou aos espíritos em prisão

[[v60-3-20]]

^<<v60-3-20,20>>^ que há muito tempo desobederam, quando Deus esperava pacientemente nos dias de Noé, enquanto a arca era construída. Nela apenas algumas pessoas, a saber, oito, foram salvas por meio da água,

[[v60-3-21]]

^<<v60-3-21,21>>^ e isso é representado pelo batismo que agora também salva vocês — não a remoção da sujeira do corpo, mas o compromisso de uma boa consciência diante de Deus — por meio da ressurreição de Jesus Cristo,

[[v60-3-22]]

^<<v60-3-22,22>>^ que subiu ao céu e está à direita de Deus; a ele estão sujeitos anjos, autoridades e poderes.

'''

xref:060-1-pedro/060-1-pedro-002.adoc#v60-2-0[&#60; Capítulo Anterior] | <<v60-3-0,Topo>> | xref:060-1-pedro/060-1-pedro-004.adoc#v60-4-0[Próximo Capítulo &#62;]