include::./index.adoc[]

[[v45-10-0]]
=== Romanos, 10
// nvi ?, NVI - Nova Versão Internacional

[[v45-10-1]]

^<<v45-10-1,1>>^ Irmãos, o desejo do meu coração e a minha oração a Deus pelos israelitas é que eles sejam salvos.

[[v45-10-2]]

^<<v45-10-2,2>>^ Pois posso testemunhar que eles têm zelo por Deus, mas o seu zelo não se baseia no conhecimento.

[[v45-10-3]]

^<<v45-10-3,3>>^ Porquanto, ignorando a justiça que vem de Deus e procurando estabelecer a sua própria, não se submeteram à justiça de Deus.

[[v45-10-4]]

^<<v45-10-4,4>>^ Porque o fim da lei é Cristo, para a justificação de todo o que crê.

[[v45-10-5]]

^<<v45-10-5,5>>^ Moisés descreve desta forma a justiça que vem da lei: "O homem que fizer estas coisas viverá por meio delas".

[[v45-10-6]]

^<<v45-10-6,6>>^ Mas a justiça que vem da fé diz: "Não diga em seu coração: ‘Quem subirá ao céu? ’ ( isto é, para fazer Cristo descer )

[[v45-10-7]]

^<<v45-10-7,7>>^ ou ‘Quem descerá ao abismo? ’ " ( isto é, para fazer subir Cristo dentre os mortos ).

[[v45-10-8]]

^<<v45-10-8,8>>^ Mas o que ela diz? "A palavra está perto de você; está em sua boca e em seu coração", isto é, a palavra da fé que estamos proclamando:

[[v45-10-9]]

^<<v45-10-9,9>>^ Se você confessar com a sua boca que Jesus é Senhor e crer em seu coração que Deus o ressuscitou dentre os mortos, será salvo.

[[v45-10-10]]

^<<v45-10-10,10>>^ Pois com o coração se crê para justiça, e com a boca se confessa para salvação.

[[v45-10-11]]

^<<v45-10-11,11>>^ Como diz a Escritura: "Todo o que nele confia jamais será envergonhado".

[[v45-10-12]]

^<<v45-10-12,12>>^ Não há diferença entre judeus e gentios, pois o mesmo Senhor é Senhor de todos e abençoa ricamente todos os que o invocam,

[[v45-10-13]]

^<<v45-10-13,13>>^ porque "todo aquele que invocar o nome do Senhor será salvo".

[[v45-10-14]]

^<<v45-10-14,14>>^ Como, pois, invocarão aquele em quem não creram? E como crerão naquele de quem não ouviram falar? E como ouvirão, se não houver quem pregue?

[[v45-10-15]]

^<<v45-10-15,15>>^ E como pregarão, se não forem enviados? Como está escrito: "Como são belos os pés dos que anunciam boas novas! "

[[v45-10-16]]

^<<v45-10-16,16>>^ No entanto, nem todos os israelitas aceitaram as boas novas. Pois Isaías diz: "Senhor, quem creu em nossa mensagem? "

[[v45-10-17]]

^<<v45-10-17,17>>^ Conseqüentemente, a fé vem por ouvir a mensagem, e a mensagem é ouvida mediante a palavra de Cristo.

[[v45-10-18]]

^<<v45-10-18,18>>^ Mas eu pergunto: Eles não a ouviram? Claro que sim: "A sua voz ressoou por toda a terra, e as suas palavras, até os confins do mundo".

[[v45-10-19]]

^<<v45-10-19,19>>^ Novamente pergunto: Será que Israel não entendeu? Moisés foi o primeiro que disse: "Farei que tenham ciúmes de quem não é meu povo; eu os provocarei à ira por meio de um povo sem entendimento".

[[v45-10-20]]

^<<v45-10-20,20>>^ E Isaías diz ousadamente: "Fui achado por aqueles que não me procuravam; revelei-me àqueles que não perguntavam por mim".

[[v45-10-21]]

^<<v45-10-21,21>>^ Mas a respeito de Israel, ele diz: "O tempo todo estendi as mãos a um povo desobediente e rebelde".

'''

xref:045-romanos/045-romanos-009.adoc#v45-9-0[&#60; Capítulo Anterior] | <<v45-10-0,Topo>> | xref:045-romanos/045-romanos-011.adoc#v45-11-0[Próximo Capítulo &#62;]