include::./index.adoc[]

[[v45-3-0]]
=== Romanos, 3
// nvi ?, NVI - Nova Versão Internacional

[[v45-3-1]]

^<<v45-3-1,1>>^ Que vantagem há então em ser judeu, ou que utilidade há na circuncisão?

[[v45-3-2]]

^<<v45-3-2,2>>^ Muita, em todos os sentidos! Principalmente porque aos judeus foram confiadas as palavras de Deus.

[[v45-3-3]]

^<<v45-3-3,3>>^ Que importa se alguns deles foram infiéis? A sua infidelidade anulará a fidelidade de Deus?

[[v45-3-4]]

^<<v45-3-4,4>>^ De maneira nenhuma! Seja Deus verdadeiro, e todo homem mentiroso. Como está escrito: "De modo que são justas as tuas palavras e prevaleces quando julgas".

[[v45-3-5]]

^<<v45-3-5,5>>^ Mas, se a nossa injustiça ressalta de maneira ainda mais clara a justiça de Deus, que diremos? Que Deus é injusto por aplicar a sua ira? ( Estou usando um argumento humano. )

[[v45-3-6]]

^<<v45-3-6,6>>^ Claro que não! Se fosse assim, como Deus iria julgar o mundo?

[[v45-3-7]]

^<<v45-3-7,7>>^ Alguém pode alegar ainda: "Se a minha mentira ressalta a veracidade de Deus, aumentando assim a sua glória, por que sou condenado como pecador? "

[[v45-3-8]]

^<<v45-3-8,8>>^ Por que não dizer como alguns caluniosamente afirmam que dizemos: "Façamos o mal, para que nos venha o bem"? A condenação dos tais é merecida.

[[v45-3-9]]

^<<v45-3-9,9>>^ Que concluiremos então? Estamos em posição de vantagem? Não! Já demonstramos que tanto judeus quanto gentios estão debaixo do pecado.

[[v45-3-10]]

^<<v45-3-10,10>>^ Como está escrito: "Não há nenhum justo, nem um sequer;

[[v45-3-11]]

^<<v45-3-11,11>>^ não há ninguém que entenda, ninguém que busque a Deus.

[[v45-3-12]]

^<<v45-3-12,12>>^ Todos se desviaram, tornaram-se juntamente inúteis; não há ninguém que faça o bem, não há nem um sequer".

[[v45-3-13]]

^<<v45-3-13,13>>^ "Suas gargantas são um túmulo aberto; com suas línguas enganam". "Veneno de serpentes está em seus lábios".

[[v45-3-14]]

^<<v45-3-14,14>>^ "Suas bocas estão cheias de maldição e amargura".

[[v45-3-15]]

^<<v45-3-15,15>>^ "Seus pés são ágeis para derramar sangue;

[[v45-3-16]]

^<<v45-3-16,16>>^ ruína e desgraça marcam os seus caminhos,

[[v45-3-17]]

^<<v45-3-17,17>>^ e não conhecem o caminho da paz".

[[v45-3-18]]

^<<v45-3-18,18>>^ "Aos seus olhos é inútil temer a Deus".

[[v45-3-19]]

^<<v45-3-19,19>>^ Sabemos que tudo o que a lei diz, o diz àqueles que estão debaixo dela, para que toda boca se cale e todo o mundo esteja sob o juízo de Deus.

[[v45-3-20]]

^<<v45-3-20,20>>^ Portanto, ninguém será declarado justo diante dele baseando-se na obediência à lei, pois é mediante a lei que nos tornamos plenamente conscientes do pecado.

[[v45-3-21]]

^<<v45-3-21,21>>^ Mas agora se manifestou uma justiça que provém de Deus, independente da lei, da qual testemunham a Lei e os Profetas,

[[v45-3-22]]

^<<v45-3-22,22>>^ justiça de Deus mediante a fé em Jesus Cristo para todos os que crêem. Não há distinção,

[[v45-3-23]]

^<<v45-3-23,23>>^ pois todos pecaram e estão destituídos da glória de Deus,

[[v45-3-24]]

^<<v45-3-24,24>>^ sendo justificados gratuitamente por sua graça, por meio da redenção que há em Cristo Jesus.

[[v45-3-25]]

^<<v45-3-25,25>>^ Deus o ofereceu como sacrifício para propiciação mediante a fé, pelo seu sangue, demonstrando a sua justiça. Em sua tolerância, havia deixado impunes os pecados anteriormente cometidos;

[[v45-3-26]]

^<<v45-3-26,26>>^ mas, no presente, demonstrou a sua justiça, a fim de ser justo e justificador daquele que tem fé em Jesus.

[[v45-3-27]]

^<<v45-3-27,27>>^ Onde está, então, o motivo de vanglória? É excluído. Baseado em que princípio? No da obediência à lei? Não, mas no princípio da fé.

[[v45-3-28]]

^<<v45-3-28,28>>^ Pois sustentamos que o homem é justificado pela fé, independente da obediência à lei.

[[v45-3-29]]

^<<v45-3-29,29>>^ Deus é Deus apenas dos judeus? Ele não é também o Deus dos gentios? Sim, dos gentios também,

[[v45-3-30]]

^<<v45-3-30,30>>^ visto que existe um só Deus, que pela fé justificará os circuncisos e os incircuncisos.

[[v45-3-31]]

^<<v45-3-31,31>>^ Anulamos então a lei pela fé? De maneira nenhuma! Pelo contrário, confirmamos a lei.

'''

xref:045-romanos/045-romanos-002.adoc#v45-2-0[&#60; Capítulo Anterior] | <<v45-3-0,Topo>> | xref:045-romanos/045-romanos-004.adoc#v45-4-0[Próximo Capítulo &#62;]