include::./index.adoc[]

[[v45-9-0]]
=== Romanos, 9
// nvi ?, NVI - Nova Versão Internacional

[[v45-9-1]]

^<<v45-9-1,1>>^ Digo a verdade em Cristo, não minto; minha consciência o confirma no Espírito Santo:

[[v45-9-2]]

^<<v45-9-2,2>>^ tenho grande tristeza e constante angústia em meu coração.

[[v45-9-3]]

^<<v45-9-3,3>>^ Pois eu até desejaria ser amaldiçoado e separado de Cristo por amor de meus irmãos, os de minha raça,

[[v45-9-4]]

^<<v45-9-4,4>>^ o povo de Israel. Deles é a adoção de filhos; deles é a glória divina, as alianças, a concessão da lei, a adoração no templo e as promessas.

[[v45-9-5]]

^<<v45-9-5,5>>^ Deles são os patriarcas, e a partir deles se traça a linhagem humana de Cristo, que é Deus acima de tudo, bendito para sempre! Amém.

[[v45-9-6]]

^<<v45-9-6,6>>^ Não pensemos que a palavra de Deus falhou. Pois nem todos os descendentes de Israel são Israel.

[[v45-9-7]]

^<<v45-9-7,7>>^ Nem por serem descendentes de Abraão passaram todos a ser filhos de Abraão. Pelo contrário: "Por meio de Isaque a sua descendência será considerada".

[[v45-9-8]]

^<<v45-9-8,8>>^ Noutras palavras, não são os filhos naturais que são filhos de Deus, mas os filhos da promessa é que são considerados descendência de Abraão.

[[v45-9-9]]

^<<v45-9-9,9>>^ Pois foi assim que a promessa foi feita: "no tempo devido virei novamente, e Sara terá um filho".

[[v45-9-10]]

^<<v45-9-10,10>>^ E esse não foi o único caso; também os filhos de Rebeca tiveram um mesmo pai, nosso pai Isaque.

[[v45-9-11]]

^<<v45-9-11,11>>^ Todavia, antes que os gêmeos nascessem ou fizessem qualquer coisa boa ou má — a fim de que o propósito de Deus conforme a eleição permanecesse,

[[v45-9-12]]

^<<v45-9-12,12>>^ não por obras, mas por aquele que chama — foi dito a ela: "O mais velho servirá ao mais novo".

[[v45-9-13]]

^<<v45-9-13,13>>^ Como está escrito: "Amei Jacó, mas rejeitei Esaú".

[[v45-9-14]]

^<<v45-9-14,14>>^ E então, que diremos? Acaso Deus é injusto? De maneira nenhuma!

[[v45-9-15]]

^<<v45-9-15,15>>^ Pois ele diz a Moisés: "Terei misericórdia de quem eu quiser ter misericórdia e terei compaixão de quem eu quiser ter compaixão".

[[v45-9-16]]

^<<v45-9-16,16>>^ Portanto, isso não depende do desejo ou do esforço humano, mas da misericórdia de Deus.

[[v45-9-17]]

^<<v45-9-17,17>>^ Pois a Escritura diz ao faraó: "Eu o levantei exatamente com este propósito: mostrar em você o meu poder, e para que o meu nome seja proclamado em toda a terra".

[[v45-9-18]]

^<<v45-9-18,18>>^ Portanto, Deus tem misericórdia de quem ele quer, e endurece a quem ele quer.

[[v45-9-19]]

^<<v45-9-19,19>>^ Mas algum de vocês me dirá: "Então, por que Deus ainda nos culpa? Pois, quem resiste à sua vontade? "

[[v45-9-20]]

^<<v45-9-20,20>>^ Mas quem é você, ó homem, para questionar a Deus? "Acaso aquilo que é formado pode dizer ao que o formou: ‘Por que me fizeste assim? ’ "

[[v45-9-21]]

^<<v45-9-21,21>>^ O oleiro não tem direito de fazer do mesmo barro um vaso para fins nobres e outro para uso desonroso?

[[v45-9-22]]

^<<v45-9-22,22>>^ E se Deus, querendo mostrar a sua ira e tornar conhecido o seu poder, suportou com grande paciência os vasos de sua ira, preparados para destruição?

[[v45-9-23]]

^<<v45-9-23,23>>^ Que dizer, se ele fez isto para tornar conhecidas as riquezas de sua glória aos vasos de sua misericórdia, que preparou de antemão para glória,

[[v45-9-24]]

^<<v45-9-24,24>>^ ou seja, a nós, a quem também chamou, não apenas dentre os judeus, mas também dentre os gentios?

[[v45-9-25]]

^<<v45-9-25,25>>^ Como ele diz em Oséias: "Chamarei ‘meu povo’ a quem não é meu povo; e chamarei ‘minha amada’ a quem não é minha amada",

[[v45-9-26]]

^<<v45-9-26,26>>^ e: "Acontecerá que, no mesmo lugar em que se lhes declarou: ‘Vocês não são meu povo’, eles serão chamados ‘filhos do Deus vivo’. "

[[v45-9-27]]

^<<v45-9-27,27>>^ Isaías exclama com relação a Israel: "Embora o número dos israelitas seja como a areia do mar, apenas o remanescente será salvo.

[[v45-9-28]]

^<<v45-9-28,28>>^ Pois o Senhor executará na terra a sua sentença, rápida e definitivamente".

[[v45-9-29]]

^<<v45-9-29,29>>^ Como anteriormente disse Isaías: "Se o Senhor dos Exércitos não nos tivesse deixado descendentes, já estaríamos como Sodoma, e semelhantes a Gomorra".

[[v45-9-30]]

^<<v45-9-30,30>>^ Que diremos, então? Os gentios, que não buscavam justiça, a obtiveram, uma justiça que vem da fé;

[[v45-9-31]]

^<<v45-9-31,31>>^ mas Israel, que buscava uma lei que trouxesse justiça, não a alcançou.

[[v45-9-32]]

^<<v45-9-32,32>>^ Por que não? Porque não a buscava pela fé, mas como se fosse por obras. Eles tropeçaram na "pedra de tropeço".

[[v45-9-33]]

^<<v45-9-33,33>>^ Como está escrito: "Eis que ponho em Sião uma pedra de tropeço e uma rocha que faz cair; e aquele que nela confia jamais será envergonhado".

'''

xref:045-romanos/045-romanos-008.adoc#v45-8-0[&#60; Capítulo Anterior] | <<v45-9-0,Topo>> | xref:045-romanos/045-romanos-010.adoc#v45-10-0[Próximo Capítulo &#62;]