include::./index.adoc[]

[[v45-15-0]]
=== Romanos, 15
// nvi ?, NVI - Nova Versão Internacional

[[v45-15-1]]

^<<v45-15-1,1>>^ Nós, que somos fortes, devemos suportar as fraquezas dos fracos, e não agradar a nós mesmos.

[[v45-15-2]]

^<<v45-15-2,2>>^ Cada um de nós deve agradar ao seu próximo para o bem dele, a fim de edificá-lo.

[[v45-15-3]]

^<<v45-15-3,3>>^ Pois também Cristo não agradou a si próprio, mas, como está escrito: "Os insultos daqueles que te insultam caíram sobre mim".

[[v45-15-4]]

^<<v45-15-4,4>>^ Pois tudo o que foi escrito no passado, foi escrito para nos ensinar, de forma que, por meio da perseverança e do bom ânimo procedentes das Escrituras, mantenhamos a nossa esperança.

[[v45-15-5]]

^<<v45-15-5,5>>^ O Deus que concede perseverança e ânimo dê-lhes um espírito de unidade, segundo Cristo Jesus,

[[v45-15-6]]

^<<v45-15-6,6>>^ para que com um só coração e uma só boca vocês glorifiquem ao Deus e Pai de nosso Senhor Jesus Cristo.

[[v45-15-7]]

^<<v45-15-7,7>>^ Portanto, aceitem-se uns aos outros, da mesma forma como Cristo os aceitou, a fim de que vocês glorifiquem a Deus.

[[v45-15-8]]

^<<v45-15-8,8>>^ Pois eu lhes digo que Cristo se tornou servo dos que são da circuncisão, por amor à verdade de Deus, para confirmar as promessas feitas aos patriarcas,

[[v45-15-9]]

^<<v45-15-9,9>>^ a fim de que os gentios glorifiquem a Deus por sua misericórdia, como está escrito: "Por isso, eu te louvarei entre os gentios; Cantarei louvores ao teu nome".

[[v45-15-10]]

^<<v45-15-10,10>>^ E também diz: "Cantem de alegria, ó gentios, com o povo dele".

[[v45-15-11]]

^<<v45-15-11,11>>^ E mais: "Louvem o Senhor, todos vocês, gentios; cantem louvores a ele todos os povos".

[[v45-15-12]]

^<<v45-15-12,12>>^ E Isaías também diz: "Brotará a raiz de Jessé, aquele que se levantará para reinar sobre os gentios; estes colocarão nele a sua esperança".

[[v45-15-13]]

^<<v45-15-13,13>>^ Que o Deus da esperança os encha de toda alegria e paz, por sua confiança nele, para que vocês transbordem de esperança, pelo poder do Espírito Santo.

[[v45-15-14]]

^<<v45-15-14,14>>^ Meus irmãos, eu mesmo estou convencido de que vocês estão cheios de bondade e plenamente instruídos, sendo capazes de aconselhar-se uns aos outros.

[[v45-15-15]]

^<<v45-15-15,15>>^ A respeito de alguns assuntos, eu lhes escrevi com toda a franqueza, como para fazê-los lembrar-se novamente deles, por causa da graça que Deus me deu,

[[v45-15-16]]

^<<v45-15-16,16>>^ de ser um ministro de Cristo Jesus para os gentios, com o dever sacerdotal de proclamar o evangelho de Deus, para que os gentios se tornem uma oferta aceitável a Deus, santificados pelo Espírito Santo.

[[v45-15-17]]

^<<v45-15-17,17>>^ Portanto, eu me glorio em Cristo Jesus, em meu serviço a Deus.

[[v45-15-18]]

^<<v45-15-18,18>>^ Não me atrevo a falar de nada, exceto daquilo que Cristo realizou por meu intermédio em palavra e em ação, a fim de levar os gentios a obedecerem a Deus:

[[v45-15-19]]

^<<v45-15-19,19>>^ pelo poder de sinais e maravilhas e por meio do poder do Espírito de Deus. Assim, desde Jerusalém e arredores, até o Ilírico, proclamei plenamente o evangelho de Cristo.

[[v45-15-20]]

^<<v45-15-20,20>>^ Sempre fiz questão de pregar o evangelho onde Cristo ainda não era conhecido, de forma que não estivesse edificando sobre alicerce de outro.

[[v45-15-21]]

^<<v45-15-21,21>>^ Mas antes, como está escrito: "Hão de vê-lo aqueles que não tinham ouvido falar dele, e o entenderão aqueles que não o haviam escutado".

[[v45-15-22]]

^<<v45-15-22,22>>^ É por isso que muitas vezes fui impedido de chegar até vocês.

[[v45-15-23]]

^<<v45-15-23,23>>^ Mas agora, não havendo nestas regiões nenhum lugar em que precise trabalhar, e visto que há muitos anos anseio vê-los,

[[v45-15-24]]

^<<v45-15-24,24>>^ planejo fazê-lo quando for à Espanha. Espero visitá-los de passagem e dar-lhes a oportunidade de me ajudar em minha viagem para lá, depois de ter desfrutado um pouco da companhia de vocês.

[[v45-15-25]]

^<<v45-15-25,25>>^ Agora, porém, estou de partida para Jerusalém, a serviço dos santos.

[[v45-15-26]]

^<<v45-15-26,26>>^ Pois a Macedônia e a Acaia tiveram a alegria de contribuir para os pobres dentre os santos de Jerusalém.

[[v45-15-27]]

^<<v45-15-27,27>>^ Eles tiveram prazer nisso, e de fato são devedores a eles. Pois se os gentios participaram das bênçãos espirituais dos judeus, devem também servir aos judeus com seus bens materiais.

[[v45-15-28]]

^<<v45-15-28,28>>^ Assim, depois de completar essa tarefa e de ter a certeza de que eles receberam esse fruto, irei à Espanha e visitarei vocês de passagem.

[[v45-15-29]]

^<<v45-15-29,29>>^ Sei que, quando for visitá-los, irei na plenitude da bênção de Cristo.

[[v45-15-30]]

^<<v45-15-30,30>>^ Recomendo-lhes, irmãos, por nosso Senhor Jesus Cristo e pelo amor do Espírito, que se unam a mim em minha luta, orando a Deus em meu favor.

[[v45-15-31]]

^<<v45-15-31,31>>^ Orem para que eu esteja livre dos descrentes da Judéia e que o meu serviço em Jerusalém seja aceitável aos santos,

[[v45-15-32]]

^<<v45-15-32,32>>^ de forma que, pela vontade de Deus, eu os visite com alegria e juntamente com vocês desfrute de um período de refrigério.

[[v45-15-33]]

^<<v45-15-33,33>>^ O Deus da paz seja com todos vocês. Amém.

'''

xref:045-romanos/045-romanos-014.adoc#v45-14-0[&#60; Capítulo Anterior] | <<v45-15-0,Topo>> | xref:045-romanos/045-romanos-016.adoc#v45-16-0[Próximo Capítulo &#62;]