include::./index.adoc[]

[[v45-14-0]]
=== Romanos, 14
// nvi ?, NVI - Nova Versão Internacional

[[v45-14-1]]

^<<v45-14-1,1>>^ Aceitem o que é fraco na fé, sem discutir assuntos controvertidos.

[[v45-14-2]]

^<<v45-14-2,2>>^ Um crê que pode comer de tudo; já outro, cuja fé é fraca, come apenas alimentos vegetais.

[[v45-14-3]]

^<<v45-14-3,3>>^ Aquele que come de tudo não deve desprezar o que não come, e aquele que não come de tudo não deve condenar aquele que come, pois Deus o aceitou.

[[v45-14-4]]

^<<v45-14-4,4>>^ Quem é você para julgar o servo alheio? É para o seu senhor que ele está de pé ou cai. E ficará de pé, pois o Senhor é capaz de o sustentar.

[[v45-14-5]]

^<<v45-14-5,5>>^ Há quem considere um dia mais sagrado que outro; há quem considere iguais todos os dias. Cada um deve estar plenamente convicto em sua própria mente.

[[v45-14-6]]

^<<v45-14-6,6>>^ Aquele que considera um dia como especial, para o Senhor assim o faz. Aquele que come carne, come para o Senhor, pois dá graças a Deus; e aquele que se abstém, para o Senhor se abstém, e dá graças a Deus.

[[v45-14-7]]

^<<v45-14-7,7>>^ Pois nenhum de nós vive apenas para si, e nenhum de nós morre apenas para si.

[[v45-14-8]]

^<<v45-14-8,8>>^ Se vivemos, vivemos para o Senhor; e, se morremos, morremos para o Senhor. Assim, quer vivamos, quer morramos, pertencemos ao Senhor.

[[v45-14-9]]

^<<v45-14-9,9>>^ Por esta razão Cristo morreu e voltou a viver, para ser Senhor de vivos e de mortos.

[[v45-14-10]]

^<<v45-14-10,10>>^ Portanto, você, por que julga seu irmão? E por que despreza seu irmão? Pois todos compareceremos diante do tribunal de Deus.

[[v45-14-11]]

^<<v45-14-11,11>>^ Porque está escrito: " ‘Por mim mesmo jurei’, diz o Senhor, ‘diante de mim todo joelho se dobrará e toda língua confessará que sou Deus’ ".

[[v45-14-12]]

^<<v45-14-12,12>>^ Assim, cada um de nós prestará contas de si mesmo a Deus.

[[v45-14-13]]

^<<v45-14-13,13>>^ Portanto, deixemos de julgar uns aos outros. Em vez disso, façamos o propósito de não colocar pedra de tropeço ou obstáculo no caminho do irmão.

[[v45-14-14]]

^<<v45-14-14,14>>^ Como alguém que está no Senhor Jesus, tenho plena convicção de que nenhum alimento é por si mesmo impuro, a não ser para quem assim o considere; para ele é impuro.

[[v45-14-15]]

^<<v45-14-15,15>>^ Se o seu irmão se entristece devido ao que você come, você já não está agindo por amor. Por causa da sua comida, não destrua seu irmão, por quem Cristo morreu.

[[v45-14-16]]

^<<v45-14-16,16>>^ Aquilo que é bom para vocês não se torne objeto de maledicência.

[[v45-14-17]]

^<<v45-14-17,17>>^ Pois o Reino de Deus não é comida nem bebida, mas justiça, paz e alegria no Espírito Santo;

[[v45-14-18]]

^<<v45-14-18,18>>^ aquele que assim serve a Cristo é agradável a Deus e aprovado pelos homens.

[[v45-14-19]]

^<<v45-14-19,19>>^ Por isso, esforcemo-nos em promover tudo quanto conduz à paz e à edificação mútua.

[[v45-14-20]]

^<<v45-14-20,20>>^ Não destrua a obra de Deus por causa da comida. Todo alimento é puro, mas é errado comer qualquer coisa que faça os outros tropeçarem.

[[v45-14-21]]

^<<v45-14-21,21>>^ É melhor não comer carne nem beber vinho, nem fazer qualquer outra coisa que leve seu irmão a cair.

[[v45-14-22]]

^<<v45-14-22,22>>^ Assim, seja qual for o seu modo de crer a respeito destas coisas, que isso permaneça entre você e Deus. Feliz é o homem que não se condena naquilo que aprova.

[[v45-14-23]]

^<<v45-14-23,23>>^ Mas aquele que tem dúvida é condenado se comer, porque não come com fé; e tudo o que não provém da fé é pecado.

'''

xref:045-romanos/045-romanos-013.adoc#v45-13-0[&#60; Capítulo Anterior] | <<v45-14-0,Topo>> | xref:045-romanos/045-romanos-015.adoc#v45-15-0[Próximo Capítulo &#62;]