include::./index.adoc[]

[[v45-7-0]]
=== Romanos, 7
// nvi ?, NVI - Nova Versão Internacional

[[v45-7-1]]

^<<v45-7-1,1>>^ Meus irmãos, falo a vocês como a pessoas que conhecem a lei. Acaso vocês não sabem que a lei tem autoridade sobre alguém apenas enquanto ele vive?

[[v45-7-2]]

^<<v45-7-2,2>>^ Por exemplo, pela lei a mulher casada está ligada a seu marido enquanto ele estiver vivo; mas, se o marido morrer, ela estará livre da lei do casamento.

[[v45-7-3]]

^<<v45-7-3,3>>^ Por isso, se ela se casar com outro homem enquanto seu marido ainda estiver vivo, será considerada adúltera. Mas se o marido morrer, ela estará livre daquela lei, e mesmo que venha a se casar com outro homem, não será adúltera.

[[v45-7-4]]

^<<v45-7-4,4>>^ Assim, meus irmãos, vocês também morreram para a lei, por meio do corpo de Cristo, para pertencerem a outro, àquele que ressuscitou dos mortos, a fim de que venhamos a dar fruto para Deus.

[[v45-7-5]]

^<<v45-7-5,5>>^ Pois quando éramos controlados pela carne, as paixões pecaminosas despertadas pela lei atuavam em nossos corpos, de forma que dávamos fruto para a morte.

[[v45-7-6]]

^<<v45-7-6,6>>^ Mas agora, morrendo para aquilo que antes nos prendia, fomos libertados da lei, para que sirvamos conforme o novo modo do Espírito, e não segundo a velha forma da lei escrita.

[[v45-7-7]]

^<<v45-7-7,7>>^ Que diremos então? A lei é pecado? De maneira nenhuma! De fato, eu não saberia o que é pecado, a não ser por meio da lei. Pois, na realidade, eu não saberia o que é cobiça, se a lei não dissesse: "Não cobiçarás".

[[v45-7-8]]

^<<v45-7-8,8>>^ Mas o pecado, aproveitando a oportunidade dada pelo mandamento, produziu em mim todo tipo de desejo cobiçoso. Pois, sem a lei, o pecado está morto.

[[v45-7-9]]

^<<v45-7-9,9>>^ Antes, eu vivia sem a lei, mas quando o mandamento veio, o pecado reviveu, e eu morri.

[[v45-7-10]]

^<<v45-7-10,10>>^ Descobri que o próprio mandamento, destinado a produzir vida, na verdade produziu morte.

[[v45-7-11]]

^<<v45-7-11,11>>^ Pois o pecado, aproveitando a oportunidade dada pelo mandamento, enganou-me e por meio do mandamento me matou.

[[v45-7-12]]

^<<v45-7-12,12>>^ De fato a lei é santa, e o mandamento é santo, justo e bom.

[[v45-7-13]]

^<<v45-7-13,13>>^ E então, o que é bom se tornou em morte para mim? De maneira nenhuma! Mas, para que o pecado se mostrasse como pecado, ele produziu morte em mim por meio do que era bom, de modo que por meio do mandamento ele se mostrasse extremamente pecaminoso.

[[v45-7-14]]

^<<v45-7-14,14>>^ Sabemos que a lei é espiritual; eu, contudo, não o sou, pois fui vendido como escravo ao pecado.

[[v45-7-15]]

^<<v45-7-15,15>>^ Não entendo o que faço. Pois não faço o que desejo, mas o que odeio.

[[v45-7-16]]

^<<v45-7-16,16>>^ E, se faço o que não desejo, admito que a lei é boa.

[[v45-7-17]]

^<<v45-7-17,17>>^ Neste caso, não sou mais eu quem o faz, mas o pecado que habita em mim.

[[v45-7-18]]

^<<v45-7-18,18>>^ Sei que nada de bom habita em mim, isto é, em minha carne. Porque tenho o desejo de fazer o que é bom, mas não consigo realizá-lo.

[[v45-7-19]]

^<<v45-7-19,19>>^ Pois o que faço não é o bem que desejo, mas o mal que não quero fazer, esse eu continuo fazendo.

[[v45-7-20]]

^<<v45-7-20,20>>^ Ora, se faço o que não quero, já não sou eu quem o faz, mas o pecado que habita em mim.

[[v45-7-21]]

^<<v45-7-21,21>>^ Assim, encontro esta lei que atua em mim: Quando quero fazer o bem, o mal está junto a mim.

[[v45-7-22]]

^<<v45-7-22,22>>^ Pois, no íntimo do meu ser tenho prazer na lei de Deus;

[[v45-7-23]]

^<<v45-7-23,23>>^ mas vejo outra lei atuando nos membros do meu corpo, guerreando contra a lei da minha mente, tornando-me prisioneiro da lei do pecado que atua em meus membros.

[[v45-7-24]]

^<<v45-7-24,24>>^ Miserável homem eu que sou! Quem me libertará do corpo sujeito a esta morte?

[[v45-7-25]]

^<<v45-7-25,25>>^ Graças a Deus por Jesus Cristo, nosso Senhor! De modo que, com a mente, eu próprio sou escravo da lei de Deus; mas, com a carne, da lei do pecado.

'''

xref:045-romanos/045-romanos-006.adoc#v45-6-0[&#60; Capítulo Anterior] | <<v45-7-0,Topo>> | xref:045-romanos/045-romanos-008.adoc#v45-8-0[Próximo Capítulo &#62;]