include::./index.adoc[]

[[v45-11-0]]
=== Romanos, 11
// nvi ?, NVI - Nova Versão Internacional

[[v45-11-1]]

^<<v45-11-1,1>>^ Pergunto, pois: Acaso Deus rejeitou o seu povo? De maneira nenhuma! Eu mesmo sou israelita, descendente de Abraão, da tribo de Benjamim.

[[v45-11-2]]

^<<v45-11-2,2>>^ Deus não rejeitou o seu povo, o qual de antemão conheceu. Ou vocês não sabem como Elias clamou a Deus contra Israel, conforme diz a Escritura?

[[v45-11-3]]

^<<v45-11-3,3>>^ "Senhor, mataram os teus profetas e derrubaram os teus altares; sou o único que sobrou, e agora estão procurando matar-me".

[[v45-11-4]]

^<<v45-11-4,4>>^ E qual foi a resposta divina? "Reservei para mim sete mil homens que não dobraram os joelhos diante de Baal".

[[v45-11-5]]

^<<v45-11-5,5>>^ Assim, hoje também há um remanescente escolhido pela graça.

[[v45-11-6]]

^<<v45-11-6,6>>^ E, se é pela graça, já não é mais pelas obras; se fosse, a graça já não seria graça.

[[v45-11-7]]

^<<v45-11-7,7>>^ Que dizer então? Israel não conseguiu aquilo que tanto buscava, mas os eleitos o obtiveram. Os demais foram endurecidos,

[[v45-11-8]]

^<<v45-11-8,8>>^ como está escrito: "Deus lhes deu um espírito de atordoamento, olhos para não ver e ouvidos para não ouvir, até o dia de hoje".

[[v45-11-9]]

^<<v45-11-9,9>>^ E Davi diz: "Que a mesa deles se transforme em laço e armadilha, pedra de tropeço e retribuição para eles.

[[v45-11-10]]

^<<v45-11-10,10>>^ Escurençam-se os seus olhos, para que não consigam ver, e suas costas fiquem encurvadas para sempre".

[[v45-11-11]]

^<<v45-11-11,11>>^ Novamente pergunto: Acaso tropeçaram para que ficassem caídos? De maneira nenhuma! Ao contrário, por causa da transgressão deles, veio salvação para os gentios, para provocar ciúme em Israel.

[[v45-11-12]]

^<<v45-11-12,12>>^ Mas se a transgressão deles significa riqueza para o mundo, e o seu fracasso, riqueza para os gentios, quanto mais significará a sua plenitude!

[[v45-11-13]]

^<<v45-11-13,13>>^ Estou falando a vocês, gentios. Visto que sou apóstolo para os gentios, exalto o meu ministério,

[[v45-11-14]]

^<<v45-11-14,14>>^ na esperança de que de alguma forma possa provocar ciúme em meu próprio povo e salvar alguns deles.

[[v45-11-15]]

^<<v45-11-15,15>>^ Pois se a rejeição deles é a reconciliação do mundo, o que será a sua aceitação, senão vida dentre os mortos?

[[v45-11-16]]

^<<v45-11-16,16>>^ Se é santa a parte da massa que é oferecida como primeiros frutos, toda a massa também o é; se a raiz é santa, os ramos também o serão.

[[v45-11-17]]

^<<v45-11-17,17>>^ Se alguns ramos foram cortados, e você, sendo oliveira brava, foi enxertado entre os outros e agora participa da seiva que vem da raiz da oliveira,

[[v45-11-18]]

^<<v45-11-18,18>>^ não se glorie contra esses ramos. Se o fizer, saiba que não é você quem sustenta a raiz, mas a raiz a você.

[[v45-11-19]]

^<<v45-11-19,19>>^ Então você dirá: "Os ramos foram cortados, para que eu fosse enxertado".

[[v45-11-20]]

^<<v45-11-20,20>>^ Está certo. Eles, porém, foram cortados devido à incredulidade, e você permanece pela fé. Não se orgulhe, mas tema.

[[v45-11-21]]

^<<v45-11-21,21>>^ Pois se Deus não poupou os ramos naturais, também não poupará você.

[[v45-11-22]]

^<<v45-11-22,22>>^ Portanto, considere a bondade e a severidade de Deus: severidade para com aqueles que caíram, mas bondade para com você, desde que permaneça na bondade dele. De outra forma, você também será cortado.

[[v45-11-23]]

^<<v45-11-23,23>>^ E quanto a eles, se não continuarem na incredulidade, serão enxertados, pois Deus é capaz de enxertá-los outra vez.

[[v45-11-24]]

^<<v45-11-24,24>>^ Afinal de contas, se você foi cortado de uma oliveira brava por natureza e, de maneira antinatural, foi enxertado numa oliveira cultivada, quanto mais serão enxertados os ramos naturais em sua própria oliveira?

[[v45-11-25]]

^<<v45-11-25,25>>^ Irmãos, não quero que ignorem este mistério, para que não se tornem presunçosos: Israel experimentou um endurecimento em parte, até que chegasse a plenitude dos gentios.

[[v45-11-26]]

^<<v45-11-26,26>>^ E assim todo o Israel será salvo, como está escrito: "Virá de Sião o redentor que desviará de Jacó a impiedade.

[[v45-11-27]]

^<<v45-11-27,27>>^ E esta é a minha aliança com eles quando eu remover os seus pecados".

[[v45-11-28]]

^<<v45-11-28,28>>^ Quanto ao evangelho, eles são inimigos por causa de vocês; mas quanto à eleição, são amados por causa dos patriarcas,

[[v45-11-29]]

^<<v45-11-29,29>>^ pois os dons e o chamado de Deus são irrevogáveis.

[[v45-11-30]]

^<<v45-11-30,30>>^ Assim como vocês, que antes eram desobedientes a Deus mas agora receberam misericórdia, graças à desobediência deles,

[[v45-11-31]]

^<<v45-11-31,31>>^ assim também agora eles se tornaram desobedientes, a fim de que também recebam agora misericórdia, graças à misericórdia de Deus para com vocês.

[[v45-11-32]]

^<<v45-11-32,32>>^ Pois Deus colocou todos sob a desobediência, para exercer misericórdia para com todos.

[[v45-11-33]]

^<<v45-11-33,33>>^ Ó profundidade da riqueza da sabedoria e do conhecimento de Deus! Quão insondáveis são os seus juízos, e inescrutáveis os seus caminhos!

[[v45-11-34]]

^<<v45-11-34,34>>^ "Quem conheceu a mente do Senhor? Ou quem foi seu conselheiro? "

[[v45-11-35]]

^<<v45-11-35,35>>^ "Quem primeiro lhe deu, para que ele o recompense? "

[[v45-11-36]]

^<<v45-11-36,36>>^ Pois dele, por ele e para ele são todas as coisas. A ele seja a glória para sempre! Amém.

'''

xref:045-romanos/045-romanos-010.adoc#v45-10-0[&#60; Capítulo Anterior] | <<v45-11-0,Topo>> | xref:045-romanos/045-romanos-012.adoc#v45-12-0[Próximo Capítulo &#62;]