include::./index.adoc[]

[[v45-6-0]]
=== Romanos, 6
// nvi ?, NVI - Nova Versão Internacional

[[v45-6-1]]

^<<v45-6-1,1>>^ Que diremos então? Continuaremos pecando para que a graça aumente?

[[v45-6-2]]

^<<v45-6-2,2>>^ De maneira nenhuma! Nós, os que morremos para o pecado, como podemos continuar vivendo nele?

[[v45-6-3]]

^<<v45-6-3,3>>^ Ou vocês não sabem que todos nós, que fomos batizados em Cristo Jesus, fomos batizados em sua morte?

[[v45-6-4]]

^<<v45-6-4,4>>^ Portanto, fomos sepultados com ele na morte por meio do batismo, a fim de que, assim como Cristo foi ressuscitado dos mortos mediante a glória do Pai, também nós vivamos uma vida nova.

[[v45-6-5]]

^<<v45-6-5,5>>^ Se dessa forma fomos unidos a ele na semelhança da sua morte, certamente o seremos também na semelhança da sua ressurreição.

[[v45-6-6]]

^<<v45-6-6,6>>^ Pois sabemos que o nosso velho homem foi crucificado com ele, para que o corpo do pecado seja destruído, e não mais sejamos escravos do pecado;

[[v45-6-7]]

^<<v45-6-7,7>>^ pois quem morreu, foi justificado do pecado.

[[v45-6-8]]

^<<v45-6-8,8>>^ Ora, se morremos com Cristo, cremos que também com ele viveremos.

[[v45-6-9]]

^<<v45-6-9,9>>^ Pois sabemos que, tendo sido ressuscitado dos mortos, Cristo não pode morrer outra vez: a morte não tem mais domínio sobre ele.

[[v45-6-10]]

^<<v45-6-10,10>>^ Porque morrendo, ele morreu para o pecado uma vez por todas; mas vivendo, vive para Deus.

[[v45-6-11]]

^<<v45-6-11,11>>^ Da mesma forma, considerem-se mortos para o pecado, mas vivos para Deus em Cristo Jesus.

[[v45-6-12]]

^<<v45-6-12,12>>^ Portanto, não permitam que o pecado continue dominando os seus corpos mortais, fazendo que vocês obedeçam aos seus desejos.

[[v45-6-13]]

^<<v45-6-13,13>>^ Não ofereçam os membros dos seus corpos ao pecado, como instrumentos de injustiça; antes ofereçam-se a Deus como quem voltou da morte para a vida; e ofereçam os membros dos seus corpos a ele, como instrumentos de justiça.

[[v45-6-14]]

^<<v45-6-14,14>>^ Pois o pecado não os dominará, porque vocês não estão debaixo da lei, mas debaixo da graça.

[[v45-6-15]]

^<<v45-6-15,15>>^ E então? Vamos pecar porque não estamos debaixo da lei, mas debaixo da graça? De maneira nenhuma!

[[v45-6-16]]

^<<v45-6-16,16>>^ Não sabem que, quando vocês se oferecem a alguém para lhe obedecer como escravos, tornam-se escravos daquele a quem obedecem: escravos do pecado que leva à morte, ou da obediência que leva à justiça?

[[v45-6-17]]

^<<v45-6-17,17>>^ Mas, graças a Deus, porque, embora vocês tenham sido escravos do pecado, passaram a obedecer de coração à forma de ensino que lhes foi transmitida.

[[v45-6-18]]

^<<v45-6-18,18>>^ Vocês foram libertados do pecado e tornaram-se escravos da justiça.

[[v45-6-19]]

^<<v45-6-19,19>>^ Falo isso em termos humanos por causa das suas limitações humanas. Assim como vocês ofereceram os membros dos seus corpos em escravidão à impureza e à maldade que leva à maldade, ofereçam-nos agora em escravidão à justiça que leva à santidade.

[[v45-6-20]]

^<<v45-6-20,20>>^ Quando vocês eram escravos do pecado, estavam livres da justiça.

[[v45-6-21]]

^<<v45-6-21,21>>^ Que fruto colheram então das coisas das quais agora vocês se envergonham? O fim delas é a morte!

[[v45-6-22]]

^<<v45-6-22,22>>^ Mas agora que vocês foram libertados do pecado e se tornaram escravos de Deus, o fruto que colhem leva à santidade, e o seu fim é a vida eterna.

[[v45-6-23]]

^<<v45-6-23,23>>^ Pois o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus, nosso Senhor.

'''

xref:045-romanos/045-romanos-005.adoc#v45-5-0[&#60; Capítulo Anterior] | <<v45-6-0,Topo>> | xref:045-romanos/045-romanos-007.adoc#v45-7-0[Próximo Capítulo &#62;]