include::./index.adoc[]

[[v45-12-0]]
=== Romanos, 12
// nvi ?, NVI - Nova Versão Internacional

[[v45-12-1]]

^<<v45-12-1,1>>^ Portanto, irmãos, rogo-lhes pelas misericórdias de Deus que se ofereçam em sacrifício vivo, santo e agradável a Deus; este é o culto racional de vocês.

[[v45-12-2]]

^<<v45-12-2,2>>^ Não se amoldem ao padrão deste mundo, mas transformem-se pela renovação da sua mente, para que sejam capazes de experimentar e comprovar a boa, agradável e perfeita vontade de Deus.

[[v45-12-3]]

^<<v45-12-3,3>>^ Pois pela graça que me foi dada digo a todos vocês: ninguém tenha de si mesmo um conceito mais elevado do que deve ter; mas, pelo contrário, tenha um conceito equilibrado, de acordo com a medida da fé que Deus lhe concedeu.

[[v45-12-4]]

^<<v45-12-4,4>>^ Assim como cada um de nós tem um corpo com muitos membros e esses membros não exercem todos a mesma função,

[[v45-12-5]]

^<<v45-12-5,5>>^ assim também em Cristo nós, que somos muitos, formamos um corpo, e cada membro está ligado a todos os outros.

[[v45-12-6]]

^<<v45-12-6,6>>^ Temos diferentes dons, de acordo com a graça que nos foi dada. Se alguém tem o dom de profetizar, use-o na proporção da sua fé.

[[v45-12-7]]

^<<v45-12-7,7>>^ Se o seu dom é servir, sirva; se é ensinar, ensine;

[[v45-12-8]]

^<<v45-12-8,8>>^ se é dar ânimo, que assim faça; se é contribuir, que contribua generosamente; se é exercer liderança, que a exerça com zelo; se é mostrar misericórdia, que o faça com alegria.

[[v45-12-9]]

^<<v45-12-9,9>>^ O amor deve ser sincero. Odeiem o que é mau; apeguem-se ao que é bom.

[[v45-12-10]]

^<<v45-12-10,10>>^ Dediquem-se uns aos outros com amor fraternal. Prefiram dar honra aos outros mais do que a si próprios.

[[v45-12-11]]

^<<v45-12-11,11>>^ Nunca lhes falte o zelo, sejam fervorosos no espírito, sirvam ao Senhor.

[[v45-12-12]]

^<<v45-12-12,12>>^ Alegrem-se na esperança, sejam pacientes na tribulação, perseverem na oração.

[[v45-12-13]]

^<<v45-12-13,13>>^ Compartilhem o que vocês têm com os santos em suas necessidades. Pratiquem a hospitalidade.

[[v45-12-14]]

^<<v45-12-14,14>>^ Abençoem aqueles que os perseguem; abençoem, e não os amaldiçoem.

[[v45-12-15]]

^<<v45-12-15,15>>^ Alegrem-se com os que se alegram; chorem com os que choram.

[[v45-12-16]]

^<<v45-12-16,16>>^ Tenham uma mesma atitude uns para com os outros. Não sejam orgulhosos, mas estejam dispostos a associar-se a pessoas de posição inferior. Não sejam sábios aos seus próprios olhos.

[[v45-12-17]]

^<<v45-12-17,17>>^ Não retribuam a ninguém mal por mal. Procurem fazer o que é correto aos olhos de todos.

[[v45-12-18]]

^<<v45-12-18,18>>^ Façam todo o possível para viver em paz com todos.

[[v45-12-19]]

^<<v45-12-19,19>>^ Amados, nunca procurem vingar-se, mas deixem com Deus a ira, pois está escrito: "Minha é a vingança; eu retribuirei", diz o Senhor.

[[v45-12-20]]

^<<v45-12-20,20>>^ Pelo contrário: "Se o seu inimigo tiver fome, dê-lhe de comer; se tiver sede, dê-lhe de beber. Fazendo isso, você amontoará brasas vivas sobre a cabeça dele".

[[v45-12-21]]

^<<v45-12-21,21>>^ Não se deixem vencer pelo mal, mas vençam o mal com o bem.

'''

xref:045-romanos/045-romanos-011.adoc#v45-11-0[&#60; Capítulo Anterior] | <<v45-12-0,Topo>> | xref:045-romanos/045-romanos-013.adoc#v45-13-0[Próximo Capítulo &#62;]