include::./index.adoc[]

[[v45-1-0]]
=== Romanos, 1
// nvi ?, NVI - Nova Versão Internacional

[[v45-1-1]]

^<<v45-1-1,1>>^ Paulo, servo de Cristo Jesus, chamado para ser apóstolo, separado para o evangelho de Deus,

[[v45-1-2]]

^<<v45-1-2,2>>^ o qual foi prometido por ele de antemão por meio dos seus profetas nas Escrituras Sagradas,

[[v45-1-3]]

^<<v45-1-3,3>>^ acerca de seu Filho, que, como homem, era descendente de Davi,

[[v45-1-4]]

^<<v45-1-4,4>>^ e que mediante o Espírito de santidade foi declarado Filho de Deus com poder, pela sua ressurreição dentre os mortos: Jesus Cristo, nosso Senhor.

[[v45-1-5]]

^<<v45-1-5,5>>^ Por meio dele e por causa do seu nome, recebemos graça e apostolado para chamar dentre todas as nações um povo para a obediência que vem pela fé.

[[v45-1-6]]

^<<v45-1-6,6>>^ E vocês também estão entre os chamados para pertencerem a Jesus Cristo.

[[v45-1-7]]

^<<v45-1-7,7>>^ A todos os que em Roma são amados de Deus e chamados para serem santos: A vocês, graça e paz da parte de Deus nosso Pai e do Senhor Jesus Cristo.

[[v45-1-8]]

^<<v45-1-8,8>>^ Antes de tudo, sou grato a meu Deus, mediante Jesus Cristo, por todos vocês, porque em todo o mundo está sendo anunciada a fé que vocês têm.

[[v45-1-9]]

^<<v45-1-9,9>>^ Deus, a quem sirvo de todo o coração pregando o evangelho de seu Filho, é minha testemunha de como sempre me lembro de vocês

[[v45-1-10]]

^<<v45-1-10,10>>^ em minhas orações; e peço que agora, finalmente, pela vontade de Deus, seja-me aberto o caminho para que eu possa visitá-los.

[[v45-1-11]]

^<<v45-1-11,11>>^ Anseio vê-los, a fim de compartilhar com vocês algum dom espiritual, para fortalecê-los,

[[v45-1-12]]

^<<v45-1-12,12>>^ isto é, para que eu e vocês sejamos mutuamente encorajados pela fé.

[[v45-1-13]]

^<<v45-1-13,13>>^ Quero que vocês saibam, irmãos, que muitas vezes planejei visitá-los, mas fui impedido de fazê-lo até agora. Meu propósito é colher algum fruto entre vocês, assim como tenho colhido entre os demais gentios.

[[v45-1-14]]

^<<v45-1-14,14>>^ Sou devedor tanto a gregos como a bárbaros, tanto a sábios como a ignorantes.

[[v45-1-15]]

^<<v45-1-15,15>>^ Por isso estou disposto a pregar o evangelho também a vocês que estão em Roma.

[[v45-1-16]]

^<<v45-1-16,16>>^ Não me envergonho do evangelho, porque é o poder de Deus para a salvação de todo aquele que crê: primeiro do judeu, depois do grego.

[[v45-1-17]]

^<<v45-1-17,17>>^ Porque no evangelho é revelada a justiça de Deus, uma justiça que do princípio ao fim é pela fé, como está escrito: "O justo viverá pela fé".

[[v45-1-18]]

^<<v45-1-18,18>>^ Portanto, a ira de Deus é revelada do céu contra toda impiedade e injustiça dos homens que suprimem a verdade pela injustiça,

[[v45-1-19]]

^<<v45-1-19,19>>^ pois o que de Deus se pode conhecer é manifesto entre eles, porque Deus lhes manifestou.

[[v45-1-20]]

^<<v45-1-20,20>>^ Pois desde a criação do mundo os atributos invisíveis de Deus, seu eterno poder e sua natureza divina, têm sido vistos claramente, sendo compreendidos por meio das coisas criadas, de forma que tais homens são indesculpáveis;

[[v45-1-21]]

^<<v45-1-21,21>>^ porque, tendo conhecido a Deus, não o glorificaram como Deus, nem lhe renderam graças, mas os seus pensamentos tornaram-se fúteis e os seus corações insensatos se obscureceram.

[[v45-1-22]]

^<<v45-1-22,22>>^ Dizendo-se sábios, tornaram-se loucos

[[v45-1-23]]

^<<v45-1-23,23>>^ e trocaram a glória do Deus imortal por imagens feitas segundo a semelhança do homem mortal, bem como de pássaros, quadrúpedes e répteis.

[[v45-1-24]]

^<<v45-1-24,24>>^ Por isso Deus os entregou à impureza sexual, segundo os desejos pecaminosos dos seus corações, para a degradação dos seus corpos entre si.

[[v45-1-25]]

^<<v45-1-25,25>>^ Trocaram a verdade de Deus pela mentira, e adoraram e serviram a coisas e seres criados, em lugar do Criador, que é bendito para sempre. Amém.

[[v45-1-26]]

^<<v45-1-26,26>>^ Por causa disso Deus os entregou a paixões vergonhosas. Até suas mulheres trocaram suas relações sexuais naturais por outras, contrárias à natureza.

[[v45-1-27]]

^<<v45-1-27,27>>^ Da mesma forma, os homens também abandonaram as relações naturais com as mulheres e se inflamaram de paixão uns pelos outros. Começaram a cometer atos indecentes, homens com homens, e receberam em si mesmos o castigo merecido pela sua perversão.

[[v45-1-28]]

^<<v45-1-28,28>>^ Além do mais, visto que desprezaram o conhecimento de Deus, ele os entregou a uma disposição mental reprovável, para praticarem o que não deviam.

[[v45-1-29]]

^<<v45-1-29,29>>^ Tornaram-se cheios de toda sorte de injustiça, maldade, ganância e depravação. Estão cheios de inveja, homicídio, rivalidades, engano e malícia. São bisbilhoteiros,

[[v45-1-30]]

^<<v45-1-30,30>>^ caluniadores, inimigos de Deus, insolentes, arrogantes e presunçosos; inventam maneiras de praticar o mal; desobedecem a seus pais;

[[v45-1-31]]

^<<v45-1-31,31>>^ são insensatos, desleais, sem amor pela família, implacáveis.

[[v45-1-32]]

^<<v45-1-32,32>>^ Embora conheçam o justo decreto de Deus, de que as pessoas que praticam tais coisas merecem a morte, não somente continuam a praticá-las, mas também aprovam aqueles que as praticam.

'''

xref:044-atos/044-atos-028.adoc#v44-28-0[&#60; Capítulo Anterior] | <<v45-1-0,Topo>> | xref:045-romanos/045-romanos-002.adoc#v45-2-0[Próximo Capítulo &#62;]