include::./index.adoc[]

[[v45-13-0]]
=== Romanos, 13
// nvi ?, NVI - Nova Versão Internacional

[[v45-13-1]]

^<<v45-13-1,1>>^ Todos devem sujeitar-se às autoridades governamentais, pois não há autoridade que não venha de Deus; as autoridades que existem foram por ele estabelecidas.

[[v45-13-2]]

^<<v45-13-2,2>>^ Portanto, aquele que se rebela contra a autoridade está se colocando contra o que Deus instituiu, e aqueles que assim procedem trazem condenação sobre si mesmos.

[[v45-13-3]]

^<<v45-13-3,3>>^ Pois os governantes não devem ser temidos, a não ser pelos que praticam o mal. Você quer viver livre do medo da autoridade? Pratique o bem, e ela o enaltecerá.

[[v45-13-4]]

^<<v45-13-4,4>>^ Pois é serva de Deus para o seu bem. Mas se você praticar o mal, tenha medo, pois ela não porta a espada sem motivo. É serva de Deus, agente da justiça para punir quem pratica o mal.

[[v45-13-5]]

^<<v45-13-5,5>>^ Portanto, é necessário que sejamos submissos às autoridades, não apenas por causa da possibilidade de uma punição, mas também por questão de consciência.

[[v45-13-6]]

^<<v45-13-6,6>>^ É por isso também que vocês pagam imposto, pois as autoridades estão a serviço de Deus, sempre dedicadas a esse trabalho.

[[v45-13-7]]

^<<v45-13-7,7>>^ Dêem a cada um o que lhe é devido: Se imposto, imposto; se tributo, tributo; se temor, temor; se honra, honra.

[[v45-13-8]]

^<<v45-13-8,8>>^ Não devam nada a ninguém, a não ser o amor de uns pelos outros, pois aquele que ama seu próximo tem cumprido a lei.

[[v45-13-9]]

^<<v45-13-9,9>>^ Pois estes mandamentos: "Não adulterarás", "não matarás", "não furtarás", "não cobiçarás", e qualquer outro mandamento, todos se resumem neste preceito: "Ame o seu próximo como a si mesmo".

[[v45-13-10]]

^<<v45-13-10,10>>^ O amor não pratica o mal contra o próximo. Portanto, o amor é o cumprimento da lei.

[[v45-13-11]]

^<<v45-13-11,11>>^ Façam isso, compreendendo o tempo em que vivemos. Chegou a hora de vocês despertarem do sono, porque agora a nossa salvação está mais próxima do que quando cremos.

[[v45-13-12]]

^<<v45-13-12,12>>^ A noite está quase acabando; o dia logo vem. Portanto, deixemos de lado as obras das trevas e vistamo-nos a armadura da luz.

[[v45-13-13]]

^<<v45-13-13,13>>^ Comportemo-nos com decência, como quem age à luz do dia, não em orgias e bebedeiras, não em imoralidade sexual e depravação, não em desavença e inveja.

[[v45-13-14]]

^<<v45-13-14,14>>^ Pelo contrário, revistam-se do Senhor Jesus Cristo, e não fiquem premeditando como satisfazer os desejos da carne.

'''

xref:045-romanos/045-romanos-012.adoc#v45-12-0[&#60; Capítulo Anterior] | <<v45-13-0,Topo>> | xref:045-romanos/045-romanos-014.adoc#v45-14-0[Próximo Capítulo &#62;]