include::./index.adoc[]

[[v45-4-0]]
=== Romanos, 4
// nvi ?, NVI - Nova Versão Internacional

[[v45-4-1]]

^<<v45-4-1,1>>^ Portanto, que diremos do nosso antepassado Abraão?

[[v45-4-2]]

^<<v45-4-2,2>>^ Se de fato Abraão foi justificado pelas obras, ele tem do que se gloriar, mas não diante de Deus.

[[v45-4-3]]

^<<v45-4-3,3>>^ Que diz a Escritura? "Abraão creu em Deus, e isso lhe foi creditado como justiça".

[[v45-4-4]]

^<<v45-4-4,4>>^ Ora, o salário do homem que trabalha não é considerado como favor, mas como dívida.

[[v45-4-5]]

^<<v45-4-5,5>>^ Todavia, àquele que não trabalha, mas confia em Deus que justifica o ímpio, sua fé lhe é creditada como justiça.

[[v45-4-6]]

^<<v45-4-6,6>>^ Davi diz a mesma coisa, quando fala da felicidade do homem a quem Deus credita justiça independente de obras:

[[v45-4-7]]

^<<v45-4-7,7>>^ "Como são felizes aqueles que têm suas transgressões perdoadas, cujos pecados são apagados.

[[v45-4-8]]

^<<v45-4-8,8>>^ Como é feliz aquele a quem o Senhor não atribui culpa".

[[v45-4-9]]

^<<v45-4-9,9>>^ Destina-se esta felicidade apenas aos circuncisos ou também aos incircuncisos? Já dissemos que, no caso de Abraão, a fé lhe foi creditada como justiça.

[[v45-4-10]]

^<<v45-4-10,10>>^ Sob quais circunstâncias? Antes ou depois de ter sido circuncidado? Não foi depois, mas antes!

[[v45-4-11]]

^<<v45-4-11,11>>^ Assim ele recebeu a circuncisão como sinal, como selo da justiça que ele tinha pela fé, quando ainda não fora circuncidado. Portanto, ele é o pai de todos os que crêem, sem terem sido circuncidados, a fim de que a justiça fosse creditada também a eles;

[[v45-4-12]]

^<<v45-4-12,12>>^ e é igualmente o pai dos circuncisos que não somente são circuncisos, mas também andam nos passos da fé que teve nosso pai Abraão antes de passar pela circuncisão.

[[v45-4-13]]

^<<v45-4-13,13>>^ Não foi mediante a lei que Abraão e a sua descendência receberam a promessa de que ele seria o herdeiro do mundo, mas mediante a justiça que vem da fé.

[[v45-4-14]]

^<<v45-4-14,14>>^ Pois se os que vivem pela lei são herdeiros, a fé não tem valor, e a promessa é inútil;

[[v45-4-15]]

^<<v45-4-15,15>>^ porque a lei produz a ira. E onde não há lei, não há transgressão.

[[v45-4-16]]

^<<v45-4-16,16>>^ Portanto, a promessa vem pela fé, para que seja de acordo com a graça e seja assim garantida a toda a descendência de Abraão; não apenas aos que estão sob o regime da lei, mas também aos que têm a fé que Abraão teve. Ele é o pai de todos nós.

[[v45-4-17]]

^<<v45-4-17,17>>^ Como está escrito: "Eu o constituí pai de muitas nações". Ele é nosso pai aos olhos de Deus, em quem creu, o Deus que dá vida aos mortos e chama à existência coisas que não existem, como se existissem.

[[v45-4-18]]

^<<v45-4-18,18>>^ Abraão, contra toda esperança, em esperança creu, tornando-se assim pai de muitas nações, como foi dito a seu respeito: "Assim será a sua descendência".

[[v45-4-19]]

^<<v45-4-19,19>>^ Sem se enfraquecer na fé, reconheceu que o seu corpo já estava sem vitalidade, pois já contava cerca de cem anos de idade, e que também o ventre de Sara já estava sem vitalidade.

[[v45-4-20]]

^<<v45-4-20,20>>^ Mesmo assim não duvidou nem foi incrédulo em relação à promessa de Deus, mas foi fortalecido em sua fé e deu glória a Deus,

[[v45-4-21]]

^<<v45-4-21,21>>^ estando plenamente convencido de que ele era poderoso para cumprir o que havia prometido.

[[v45-4-22]]

^<<v45-4-22,22>>^ Em conseqüência, "isso lhe foi também creditado como justiça".

[[v45-4-23]]

^<<v45-4-23,23>>^ As palavras "lhe foi creditado" não foram escritas apenas para ele,

[[v45-4-24]]

^<<v45-4-24,24>>^ mas também para nós, a quem Deus creditará justiça, para nós, que cremos naquele que ressuscitou dos mortos a Jesus, nosso Senhor.

[[v45-4-25]]

^<<v45-4-25,25>>^ Ele foi entregue à morte por nossos pecados e ressuscitado para nossa justificação.

'''

xref:045-romanos/045-romanos-003.adoc#v45-3-0[&#60; Capítulo Anterior] | <<v45-4-0,Topo>> | xref:045-romanos/045-romanos-005.adoc#v45-5-0[Próximo Capítulo &#62;]