include::./index.adoc[]

[[v45-16-0]]
=== Romanos, 16
// nvi ?, NVI - Nova Versão Internacional

[[v45-16-1]]

^<<v45-16-1,1>>^ Recomendo-lhes nossa irmã Febe, serva da igreja em Cencréia.

[[v45-16-2]]

^<<v45-16-2,2>>^ Peço que a recebam no Senhor, de maneira digna dos santos, e lhe prestem a ajuda de que venha a necessitar; pois tem sido de grande auxílio para muita gente, inclusive para mim.

[[v45-16-3]]

^<<v45-16-3,3>>^ Saúdem Priscila e Áqüila, meus colaboradores em Cristo Jesus.

[[v45-16-4]]

^<<v45-16-4,4>>^ Arriscaram a vida por mim. Sou grato a eles; não apenas eu, mas todas as igrejas dos gentios.

[[v45-16-5]]

^<<v45-16-5,5>>^ Saúdem também a igreja que se reúne na casa deles. Saúdem meu amado irmão Epêneto, que foi o primeiro convertido a Cristo na província da Ásia.

[[v45-16-6]]

^<<v45-16-6,6>>^ Saúdem Maria, que trabalhou arduamente por vocês.

[[v45-16-7]]

^<<v45-16-7,7>>^ Saúdem Andrônico e Júnias, meus parentes que estiveram na prisão comigo. São notáveis entre os apóstolos, e estavam em Cristo antes de mim.

[[v45-16-8]]

^<<v45-16-8,8>>^ Saúdem Amplíato, meu amado irmão no Senhor.

[[v45-16-9]]

^<<v45-16-9,9>>^ Saúdem Urbano, nosso cooperador em Cristo, e meu amado irmão Estáquis.

[[v45-16-10]]

^<<v45-16-10,10>>^ Saúdem Apeles, aprovado em Cristo. Saúdem os que pertencem à casa de Aristóbulo.

[[v45-16-11]]

^<<v45-16-11,11>>^ Saúdem Herodião, meu parente. Saúdem os da casa de Narciso, que estão no Senhor.

[[v45-16-12]]

^<<v45-16-12,12>>^ Saúdem Trifena e Trifosa, mulheres que trabalham arduamente no Senhor. Saúdem a amada Pérside, outra que trabalhou arduamente no Senhor.

[[v45-16-13]]

^<<v45-16-13,13>>^ Saúdem Rufo, eleito no Senhor, e sua mãe, que tem sido mãe também para mim.

[[v45-16-14]]

^<<v45-16-14,14>>^ Saúdem Asíncrito, Flegonte, Hermes, Pátrobas, Hermas e os irmãos que estão com eles.

[[v45-16-15]]

^<<v45-16-15,15>>^ Saúdem Filólogo, Júlia, Nereu e sua irmã, e também Olimpas e todos os santos que estão com eles.

[[v45-16-16]]

^<<v45-16-16,16>>^ Saúdem uns aos outros com beijo santo. Todas as igrejas de Cristo enviam-lhes saudações.

[[v45-16-17]]

^<<v45-16-17,17>>^ Recomendo-lhes, irmãos, que tomem cuidado com aqueles que causam divisões e colocam obstáculos ao ensino que vocês têm recebido. Afastem-se deles.

[[v45-16-18]]

^<<v45-16-18,18>>^ Pois essas pessoas não estão servindo a Cristo, nosso Senhor, mas a seus próprios apetites. Mediante palavras suaves e bajulação, enganam os corações dos ingênuos.

[[v45-16-19]]

^<<v45-16-19,19>>^ Todos têm ouvido falar da obediência de vocês, por isso estou muito alegre; mas quero que sejam sábios em relação ao que é bom, e sem malícia em relação ao que é mau.

[[v45-16-20]]

^<<v45-16-20,20>>^ Em breve o Deus da paz esmagará Satanás debaixo dos pés de vocês. A graça de nosso Senhor Jesus seja com vocês.

[[v45-16-21]]

^<<v45-16-21,21>>^ Timóteo, meu cooperador, envia-lhes saudações, bem como Lúcio, Jasom e Sosípatro, meus parentes.

[[v45-16-22]]

^<<v45-16-22,22>>^ Eu, Tércio, que redigi esta carta, saúdo vocês no Senhor.

[[v45-16-23]]

^<<v45-16-23,23>>^ Gaio, cuja hospitalidade eu e toda a igreja desfrutamos, envia-lhes saudações. Erasto, administrador da cidade, e nosso irmão Quarto enviam-lhes saudações.

[[v45-16-24]]

^<<v45-16-24,24>>^ Que a graça de nosso Senhor Jesus Cristo seja com vocês todos. Amém.

[[v45-16-25]]

^<<v45-16-25,25>>^ Ora, àquele que tem poder para confirmá-los pelo meu evangelho e pela proclamação de Jesus Cristo, de acordo com a revelação do mistério oculto nos tempos passados,

[[v45-16-26]]

^<<v45-16-26,26>>^ mas agora revelado e dado a conhecer pelas Escrituras proféticas por ordem do Deus eterno, para que todas as nações venham a crer nele e a obedecer-lhe,

[[v45-16-27]]

^<<v45-16-27,27>>^ ao único Deus sábio seja dada glória para todo o sempre, por meio de Jesus Cristo. Amém.

'''

xref:045-romanos/045-romanos-015.adoc#v45-15-0[&#60; Capítulo Anterior] | <<v45-16-0,Topo>> | xref:046-1-corintios/046-1-corintios-001.adoc#v46-1-0[Próximo Capítulo &#62;]