include::./index.adoc[]

[[v45-2-0]]
=== Romanos, 2
// nvi ?, NVI - Nova Versão Internacional

[[v45-2-1]]

^<<v45-2-1,1>>^ Portanto, você, que julga, os outros é indesculpável; pois está condenando a si mesmo naquilo em que julga, visto que você, que julga, pratica as mesmas coisas.

[[v45-2-2]]

^<<v45-2-2,2>>^ Sabemos que o juízo de Deus contra os que praticam tais coisas é conforme a verdade.

[[v45-2-3]]

^<<v45-2-3,3>>^ Assim, quando você, um simples homem, os julga, mas pratica as mesmas coisas, pensa que escapará do juízo de Deus?

[[v45-2-4]]

^<<v45-2-4,4>>^ Ou será que você despreza as riquezas da sua bondade, tolerância e paciência, não reconhecendo que a bondade de Deus o leva ao arrependimento?

[[v45-2-5]]

^<<v45-2-5,5>>^ Contudo, por causa da sua teimosia e do seu coração obstinado, você está acumulando ira contra si mesmo, para o dia da ira de Deus, quando se revelará o seu justo julgamento.

[[v45-2-6]]

^<<v45-2-6,6>>^ Deus "retribuirá a cada um conforme o seu procedimento".

[[v45-2-7]]

^<<v45-2-7,7>>^ Ele dará vida eterna aos que, persistindo em fazer o bem, buscam glória, honra e imortalidade.

[[v45-2-8]]

^<<v45-2-8,8>>^ Mas haverá ira e indignação para os que são egoístas, que rejeitam a verdade e seguem a injustiça.

[[v45-2-9]]

^<<v45-2-9,9>>^ Haverá tribulação e angústia para todo ser humano que pratica o mal: primeiro para o judeu, depois para o grego;

[[v45-2-10]]

^<<v45-2-10,10>>^ mas glória, honra e paz para todo o que pratica o bem: primeiro para o judeu, depois para o grego.

[[v45-2-11]]

^<<v45-2-11,11>>^ Pois em Deus não há parcialidade.

[[v45-2-12]]

^<<v45-2-12,12>>^ Todo aquele que pecar sem a lei, sem a lei também perecerá, e todo aquele que pecar sob a lei, pela lei será julgado.

[[v45-2-13]]

^<<v45-2-13,13>>^ Porque não são os que ouvem a Lei que são justos aos olhos de Deus; mas os que obedecem à lei, estes serão declarados justos.

[[v45-2-14]]

^<<v45-2-14,14>>^ ( De fato, quando os gentios, que não têm a lei, praticam naturalmente o que ela ordena, tornam-se lei para si mesmos, embora não possuam a lei;

[[v45-2-15]]

^<<v45-2-15,15>>^ pois mostram que as exigências da lei estão gravadas em seus corações. Disso dão testemunho também a consciência e os pensamentos deles, ora acusando-os, ora defendendo-os. )

[[v45-2-16]]

^<<v45-2-16,16>>^ Isso acontecerá no dia em que Deus julgar os segredos dos homens, mediante Jesus Cristo, conforme o declara o meu evangelho.

[[v45-2-17]]

^<<v45-2-17,17>>^ Ora, você que leva o nome de judeu, apóia-se na lei e orgulha-se em Deus;

[[v45-2-18]]

^<<v45-2-18,18>>^ se você conhece a vontade de Deus e aprova o que é superior, porque é instruído pela lei;

[[v45-2-19]]

^<<v45-2-19,19>>^ se está convencido de que é guia de cegos, luz para os que estão em trevas,

[[v45-2-20]]

^<<v45-2-20,20>>^ instrutor de insensatos, mestre de crianças, porque tem na lei a expressão do conhecimento e da verdade;

[[v45-2-21]]

^<<v45-2-21,21>>^ então você, que ensina os outros, não ensina a si mesmo? Você, que prega contra o furto, furta?

[[v45-2-22]]

^<<v45-2-22,22>>^ Você, que diz que não se deve adulterar, adultera? Você, que detesta ídolos, rouba-lhes os templos?

[[v45-2-23]]

^<<v45-2-23,23>>^ Você, que se orgulha na lei, desonra a Deus, desobedecendo à lei?

[[v45-2-24]]

^<<v45-2-24,24>>^ Como está escrito: "O nome de Deus é blasfemado entre os gentios por causa de vocês".

[[v45-2-25]]

^<<v45-2-25,25>>^ A circuncisão tem valor se você obedece à lei; mas, se você desobedece à lei, a sua circuncisão já se tornou incircuncisão.

[[v45-2-26]]

^<<v45-2-26,26>>^ Se aqueles que não são circuncidados obedecem aos preceitos da lei, não serão eles considerados circuncidados?

[[v45-2-27]]

^<<v45-2-27,27>>^ Aquele que não é circuncidado fisicamente, mas obedece à lei, condenará você que, tendo a lei escrita e a circuncisão, é transgressor da lei.

[[v45-2-28]]

^<<v45-2-28,28>>^ Não é judeu quem o é apenas exteriormente, nem é circuncisão a que é meramente exterior e física.

[[v45-2-29]]

^<<v45-2-29,29>>^ Não! Judeu é quem o é interiormente, e circuncisão é a operada no coração, pelo Espírito, e não pela lei escrita. Para estes o louvor não provém dos homens, mas de Deus.

'''

xref:045-romanos/045-romanos-001.adoc#v45-1-0[&#60; Capítulo Anterior] | <<v45-2-0,Topo>> | xref:045-romanos/045-romanos-003.adoc#v45-3-0[Próximo Capítulo &#62;]