include::./index.adoc[]

[[v45-5-0]]
=== Romanos, 5
// nvi ?, NVI - Nova Versão Internacional

[[v45-5-1]]

^<<v45-5-1,1>>^ Tendo sido, pois, justificados pela fé, temos paz com Deus, por nosso Senhor Jesus Cristo,

[[v45-5-2]]

^<<v45-5-2,2>>^ por meio de quem obtivemos acesso pela fé a esta graça na qual agora estamos firmes; e nos gloriamos na esperança da glória de Deus.

[[v45-5-3]]

^<<v45-5-3,3>>^ Não só isso, mas também nos gloriamos nas tribulações, porque sabemos que a tribulação produz perseverança;

[[v45-5-4]]

^<<v45-5-4,4>>^ a perseverança, um caráter aprovado; e o caráter aprovado, esperança.

[[v45-5-5]]

^<<v45-5-5,5>>^ E a esperança não nos decepciona, porque Deus derramou seu amor em nossos corações, por meio do Espírito Santo que ele nos concedeu.

[[v45-5-6]]

^<<v45-5-6,6>>^ De fato, no devido tempo, quando ainda éramos fracos, Cristo morreu pelos ímpios.

[[v45-5-7]]

^<<v45-5-7,7>>^ Dificilmente haverá alguém que morra por um justo; pelo homem bom talvez alguém tenha coragem de morrer.

[[v45-5-8]]

^<<v45-5-8,8>>^ Mas Deus demonstra seu amor por nós: Cristo morreu em nosso favor quando ainda éramos pecadores.

[[v45-5-9]]

^<<v45-5-9,9>>^ Como agora fomos justificados por seu sangue, muito mais ainda seremos salvos da ira de Deus por meio dele!

[[v45-5-10]]

^<<v45-5-10,10>>^ Se quando éramos inimigos de Deus fomos reconciliados com ele mediante a morte de seu Filho, quanto mais agora, tendo sido reconciliados, seremos salvos por sua vida!

[[v45-5-11]]

^<<v45-5-11,11>>^ Não apenas isso, mas também nos gloriamos em Deus, por meio de nosso Senhor Jesus Cristo, mediante quem recebemos agora a reconciliação.

[[v45-5-12]]

^<<v45-5-12,12>>^ Portanto, da mesma forma como o pecado entrou no mundo por um homem, e pelo pecado a morte, assim também a morte veio a todos os homens, porque todos pecaram;

[[v45-5-13]]

^<<v45-5-13,13>>^ pois antes de ser dada a lei, o pecado já estava no mundo. Mas o pecado não é levado em conta quando não existe lei.

[[v45-5-14]]

^<<v45-5-14,14>>^ Todavia, a morte reinou desde o tempo de Adão até o de Moisés, mesmo sobre aqueles que não cometeram pecado semelhante à transgressão de Adão, o qual era um tipo daquele que haveria de vir.

[[v45-5-15]]

^<<v45-5-15,15>>^ Entretanto, não há comparação entre a dádiva e a transgressão. Pois se muitos morreram por causa da transgressão de um só, muito mais a graça de Deus, isto é, a dádiva pela graça de um só homem, Jesus Cristo, transbordou para muitos!

[[v45-5-16]]

^<<v45-5-16,16>>^ Não se pode comparar a dádiva de Deus com a conseqüência do pecado de um só homem: por um pecado veio o julgamento que trouxe condenação, mas a dádiva decorreu de muitas transgressões e trouxe justificação.

[[v45-5-17]]

^<<v45-5-17,17>>^ Se pela transgressão de um só a morte reinou por meio dele, muito mais aqueles que recebem de Deus a imensa provisão da graça e a dádiva da justiça reinarão em vida por meio de um único homem, Jesus Cristo.

[[v45-5-18]]

^<<v45-5-18,18>>^ Conseqüentemente, assim como uma só transgressão resultou na condenação de todos os homens, assim também um só ato de justiça resultou na justificação que traz vida a todos os homens.

[[v45-5-19]]

^<<v45-5-19,19>>^ Logo, assim como por meio da desobediência de um só homem muitos foram feitos pecadores, assim também, por meio da obediência de um único homem muitos serão feitos justos.

[[v45-5-20]]

^<<v45-5-20,20>>^ A lei foi introduzida para que a transgressão fosse ressaltada. Mas onde aumentou o pecado, transbordou a graça,

[[v45-5-21]]

^<<v45-5-21,21>>^ a fim de que, assim como o pecado reinou na morte, também a graça reine pela justiça para conceder vida eterna, mediante Jesus Cristo, nosso Senhor.

'''

xref:045-romanos/045-romanos-004.adoc#v45-4-0[&#60; Capítulo Anterior] | <<v45-5-0,Topo>> | xref:045-romanos/045-romanos-006.adoc#v45-6-0[Próximo Capítulo &#62;]