include::./index.adoc[]

[[v52-5-0]]
=== 1 Tessalonicenses, 5
// nvi ?, NVI - Nova Versão Internacional

[[v52-5-1]]

^<<v52-5-1,1>>^ Irmãos, quanto aos tempos e épocas, não precisamos escrever-lhes,

[[v52-5-2]]

^<<v52-5-2,2>>^ pois vocês mesmos sabem perfeitamente que o dia do Senhor virá como ladrão à noite.

[[v52-5-3]]

^<<v52-5-3,3>>^ Quando disserem: "Paz e segurança", então, de repente, a destruição virá sobre eles, como dores à mulher grávida; e de modo nenhum escaparão.

[[v52-5-4]]

^<<v52-5-4,4>>^ Mas vocês, irmãos, não estão nas trevas, para que esse dia os surpreenda como ladrão.

[[v52-5-5]]

^<<v52-5-5,5>>^ Vocês todos são filhos da luz, filhos do dia. Não somos da noite nem das trevas.

[[v52-5-6]]

^<<v52-5-6,6>>^ Portanto, não durmamos como os demais, mas estejamos atentos e sejamos sóbrios;

[[v52-5-7]]

^<<v52-5-7,7>>^ pois os que dormem, dormem de noite, e os que se embriagam, embriagam-se de noite.

[[v52-5-8]]

^<<v52-5-8,8>>^ Nós, porém, que somos do dia, sejamos sóbrios, vestindo a couraça da fé e do amor e o capacete da esperança da salvação.

[[v52-5-9]]

^<<v52-5-9,9>>^ Porque Deus não nos destinou para a ira, mas para recebermos a salvação por meio de nosso Senhor Jesus Cristo.

[[v52-5-10]]

^<<v52-5-10,10>>^ Ele morreu por nós para que, quer estejamos acordados quer dormindo, vivamos unidos a ele.

[[v52-5-11]]

^<<v52-5-11,11>>^ Por isso, exortem-se e edifiquem-se uns aos outros, como de fato vocês estão fazendo.

[[v52-5-12]]

^<<v52-5-12,12>>^ Agora lhes pedimos, irmãos, que tenham consideração para com os que se esforçam no trabalho entre vocês, que os lideram no Senhor e os aconselham.

[[v52-5-13]]

^<<v52-5-13,13>>^ Tenham-nos na mais alta estima, com amor, por causa do trabalho deles. Vivam em paz uns com os outros.

[[v52-5-14]]

^<<v52-5-14,14>>^ Exortamos vocês, irmãos, a que advirtam os ociosos, confortem os desanimados, auxiliem os fracos, sejam pacientes para com todos.

[[v52-5-15]]

^<<v52-5-15,15>>^ Tenham cuidado para que ninguém retribua o mal com o mal, mas sejam sempre bondosos uns para com os outros e para com todos.

[[v52-5-16]]

^<<v52-5-16,16>>^ Alegrem-se sempre.

[[v52-5-17]]

^<<v52-5-17,17>>^ Orem continuamente.

[[v52-5-18]]

^<<v52-5-18,18>>^ Dêem graças em todas as circunstâncias, pois esta é a vontade de Deus para vocês em Cristo Jesus.

[[v52-5-19]]

^<<v52-5-19,19>>^ Não apaguem o Espírito.

[[v52-5-20]]

^<<v52-5-20,20>>^ Não tratem com desprezo as profecias,

[[v52-5-21]]

^<<v52-5-21,21>>^ mas ponham à prova todas as coisas e fiquem com o que é bom.

[[v52-5-22]]

^<<v52-5-22,22>>^ Afastem-se de toda forma de mal.

[[v52-5-23]]

^<<v52-5-23,23>>^ Que o próprio Deus da paz os santifique inteiramente. Que todo o espírito, alma e corpo de vocês seja conservado irrepreensível na vinda de nosso Senhor Jesus Cristo.

[[v52-5-24]]

^<<v52-5-24,24>>^ Aquele que os chama é fiel, e fará isso.

[[v52-5-25]]

^<<v52-5-25,25>>^ Irmãos, orem por nós.

[[v52-5-26]]

^<<v52-5-26,26>>^ Saúdem todos os irmãos com beijo santo.

[[v52-5-27]]

^<<v52-5-27,27>>^ Responsabilizo-os diante do Senhor para que esta carta seja lida a todos os irmãos.

[[v52-5-28]]

^<<v52-5-28,28>>^ A graça de nosso Senhor Jesus Cristo seja com vocês.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-004.adoc#v52-4-0[&#60; Capítulo Anterior] | <<v52-5-0,Topo>> | xref:053-2-tessalonicenses/053-2-tessalonicenses-001.adoc#v53-1-0[Próximo Capítulo &#62;]