include::./index.adoc[]

[[v52-2-0]]
=== 1 Tessalonicenses, 2
// nvi ?, NVI - Nova Versão Internacional

[[v52-2-1]]

^<<v52-2-1,1>>^ Irmãos, vocês mesmos sabem que a visita que lhes fizemos não foi inútil.

[[v52-2-2]]

^<<v52-2-2,2>>^ Apesar de termos sido maltratados e insultados em Filipos, como vocês sabem, com a ajuda de nosso Deus tivemos coragem de anunciar-lhes o evangelho de Deus, em meio a muita luta.

[[v52-2-3]]

^<<v52-2-3,3>>^ Pois nossa exortação não tem origem no erro nem em motivos impuros, nem temos intenção de enganá-los;

[[v52-2-4]]

^<<v52-2-4,4>>^ pelo contrário, como homens aprovados por Deus, a ponto de nos ter sido confiado por ele o evangelho, não falamos para agradar a pessoas, mas a Deus, que prova os nossos corações.

[[v52-2-5]]

^<<v52-2-5,5>>^ Vocês bem sabem a nossa linguagem nunca foi de bajulação nem de pretexto para ganância; Deus é testemunha.

[[v52-2-6]]

^<<v52-2-6,6>>^ Nem buscamos reconhecimento humano, quer de vocês quer de outros.

[[v52-2-7]]

^<<v52-2-7,7>>^ Embora, como apóstolos de Cristo, pudéssemos ter sido um peso, tornamo-nos bondosos entre vocês, como uma mãe que cuida dos próprios filhos.

[[v52-2-8]]

^<<v52-2-8,8>>^ Sentindo, assim, tanta afeição por vocês, decidimos dar-lhes não somente o evangelho de Deus, mas também a nossa própria vida, porque vocês se tornaram muito amados por nós.

[[v52-2-9]]

^<<v52-2-9,9>>^ Irmãos, certamente vocês se lembram do nosso trabalho esgotante e da nossa fadiga; trabalhamos noite e dia para não sermos pesados a ninguém, enquanto lhes pregávamos o evangelho de Deus.

[[v52-2-10]]

^<<v52-2-10,10>>^ Tanto vocês como Deus são testemunhas de como nos portamos de maneira santa, justa e irrepreensível entre vocês, os que crêem.

[[v52-2-11]]

^<<v52-2-11,11>>^ Pois vocês sabem que tratamos cada um como um pai trata seus filhos,

[[v52-2-12]]

^<<v52-2-12,12>>^ exortando, consolando e dando testemunho, para que vocês vivam de maneira digna de Deus, que os chamou para o seu Reino e glória.

[[v52-2-13]]

^<<v52-2-13,13>>^ Também agradecemos a Deus sem cessar, pois, ao receberem de nossa parte a palavra de Deus, vocês a aceitaram não como palavra de homens, mas segundo verdadeiramente é, como palavra de Deus, que atua com eficácia em vocês, os que crêem.

[[v52-2-14]]

^<<v52-2-14,14>>^ Porque vocês, irmãos, tornaram-se imitadores das igrejas de Deus em Cristo Jesus que estão na Judéia. Vocês sofreram da parte dos seus próprios conterrâneos as mesmas coisas que aquelas igrejas sofreram da parte dos judeus,

[[v52-2-15]]

^<<v52-2-15,15>>^ que mataram o Senhor Jesus e os profetas, e também nos perseguiram. Eles desagradam a Deus e são hostis a todos,

[[v52-2-16]]

^<<v52-2-16,16>>^ esforçando-se para nos impedir que falemos aos gentios, e estes sejam salvos. Dessa forma, vão sempre completando a medida dos seus pecados. Sobre eles, finalmente, veio a ira.

[[v52-2-17]]

^<<v52-2-17,17>>^ Nós, porém, irmãos, privados da companhia de vocês por breve tempo, em pessoa, mas não no coração, esforçamo-nos ainda mais para vê-los pessoalmente, pela saudade que temos de vocês.

[[v52-2-18]]

^<<v52-2-18,18>>^ Quisemos visitá-los. Eu mesmo, Paulo o quis, e não apenas uma vez, mas duas; Satanás, porém, nos impediu.

[[v52-2-19]]

^<<v52-2-19,19>>^ Pois quem é a nossa esperança, alegria ou coroa em que nos gloriamos perante o Senhor Jesus na sua vinda? Não são vocês?

[[v52-2-20]]

^<<v52-2-20,20>>^ De fato, vocês são a nossa glória e a nossa alegria.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-001.adoc#v52-1-0[&#60; Capítulo Anterior] | <<v52-2-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-003.adoc#v52-3-0[Próximo Capítulo &#62;]