include::./index.adoc[]

[[v52-3-0]]
=== 1 Tessalonicenses, 3
// nvi ?, NVI - Nova Versão Internacional

[[v52-3-1]]

^<<v52-3-1,1>>^ Por isso, quando não pudemos mais suportar, achamos por bem permanecer sozinhos em Atenas

[[v52-3-2]]

^<<v52-3-2,2>>^ e, assim, enviamos Timóteo, nosso irmão e cooperador de Deus no evangelho de Cristo, para fortalecê-los e dar-lhes ânimo na fé,

[[v52-3-3]]

^<<v52-3-3,3>>^ para que ninguém seja abalado por essas tribulações. Vocês sabem muito bem que fomos designados para isso.

[[v52-3-4]]

^<<v52-3-4,4>>^ Quando estávamos com vocês, já lhes dizíamos que seríamos perseguidos, o que realmente aconteceu, como vocês sabem.

[[v52-3-5]]

^<<v52-3-5,5>>^ Por essa razão, não suportando mais, enviei Timóteo para saber a respeito da fé que vocês têm, a fim de que o tentador não os seduzisse, tornando inútil o nosso esforço.

[[v52-3-6]]

^<<v52-3-6,6>>^ Agora, porém, Timóteo acaba de chegar da parte de vocês, dando-nos boas notícias a respeito da fé e do amor que vocês têm. Ele nos falou que vocês sempre guardam boas recordações de nós, desejando ver-nos, assim como nós queremos vê-los.

[[v52-3-7]]

^<<v52-3-7,7>>^ Por isso, irmãos, em toda a nossa necessidade e tribulação temos bom ânimo a seu respeito, por sabermos da sua fé;

[[v52-3-8]]

^<<v52-3-8,8>>^ pois agora vivemos, visto que vocês estão firmes no Senhor.

[[v52-3-9]]

^<<v52-3-9,9>>^ Como podemos ser suficientemente gratos a Deus por vocês, por toda a alegria que temos diante dele por causa de vocês?

[[v52-3-10]]

^<<v52-3-10,10>>^ Noite e dia com perseverança oramos para que possamos vê-los pessoalmente e suprir o que falta à sua fé.

[[v52-3-11]]

^<<v52-3-11,11>>^ Que o próprio Deus, nosso Pai, e nosso Senhor Jesus preparem o nosso caminho até vocês.

[[v52-3-12]]

^<<v52-3-12,12>>^ Que o Senhor faça crescer e transbordar o amor que vocês têm uns para com os outros e para com todos, a exemplo do nosso amor por vocês.

[[v52-3-13]]

^<<v52-3-13,13>>^ Que ele fortaleça os seus corações para serem irrepreensíveis em santidade diante de nosso Deus e Pai, na vinda de nosso Senhor Jesus com todos os seus santos.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-002.adoc#v52-2-0[&#60; Capítulo Anterior] | <<v52-3-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-004.adoc#v52-4-0[Próximo Capítulo &#62;]