include::./index.adoc[]

[[v52-4-0]]
=== 1 Tessalonicenses, 4
// nvi ?, NVI - Nova Versão Internacional

[[v52-4-1]]

^<<v52-4-1,1>>^ Quanto ao mais, irmãos, já os instruímos acerca de como viver a fim de agradar a Deus e, de fato, assim vocês estão procedendo. Agora lhes pedimos e exortamos no Senhor Jesus que cresçam nisso cada vez mais.

[[v52-4-2]]

^<<v52-4-2,2>>^ Pois vocês conhecem os mandamentos que lhes demos pela autoridade do Senhor Jesus.

[[v52-4-3]]

^<<v52-4-3,3>>^ A vontade de Deus é que vocês sejam santificados: abstenham-se da imoralidade sexual.

[[v52-4-4]]

^<<v52-4-4,4>>^ Cada um saiba controlar o próprio corpo de maneira santa e honrosa,

[[v52-4-5]]

^<<v52-4-5,5>>^ não com a paixão de desejo desenfreado, como os pagãos que desconhecem a Deus.

[[v52-4-6]]

^<<v52-4-6,6>>^ Neste assunto, ninguém prejudique a seu irmão nem dele se aproveite. O Senhor castigará todas essas práticas, como já lhes dissemos e asseguramos.

[[v52-4-7]]

^<<v52-4-7,7>>^ Porque Deus não nos chamou para a impureza, mas para a santidade.

[[v52-4-8]]

^<<v52-4-8,8>>^ Portanto, aquele que rejeita estas coisas não está rejeitando o homem, mas a Deus, que lhes dá o seu Espírito Santo.

[[v52-4-9]]

^<<v52-4-9,9>>^ Quanto ao amor fraternal, não precisamos escrever-lhes, pois vocês mesmos já foram ensinados por Deus a se amarem uns aos outros.

[[v52-4-10]]

^<<v52-4-10,10>>^ E, de fato, vocês amam a todos os irmãos em toda a Macedônia. Contudo, irmãos, insistimos com vocês que cada vez mais assim procedam.

[[v52-4-11]]

^<<v52-4-11,11>>^ Esforcem-se para ter uma vida tranqüila, cuidar dos seus próprios negócios e trabalhar com as próprias mãos, como nós os instruímos;

[[v52-4-12]]

^<<v52-4-12,12>>^ a fim de que andem decentemente aos olhos dos que são de fora e não dependam de ninguém.

[[v52-4-13]]

^<<v52-4-13,13>>^ Irmãos, não queremos que vocês sejam ignorantes quanto aos que dormem, para que não se entristeçam como os outros que não têm esperança.

[[v52-4-14]]

^<<v52-4-14,14>>^ Se cremos que Jesus morreu e ressurgiu, cremos também que Deus trará, mediante Jesus e juntamente com ele, aqueles que nele dormiram.

[[v52-4-15]]

^<<v52-4-15,15>>^ Dizemos a vocês, pela palavra do Senhor, que nós, os que estivermos vivos, os que ficarmos até a vinda do Senhor, certamente não precederemos os que dormem.

[[v52-4-16]]

^<<v52-4-16,16>>^ Pois, dada a ordem, com a voz do arcanjo e o ressoar da trombeta de Deus, o próprio Senhor descerá do céu, e os mortos em Cristo ressuscitarão primeiro.

[[v52-4-17]]

^<<v52-4-17,17>>^ Depois disso, os que estivermos vivos seremos arrebatados juntamente com eles nas nuvens, para o encontro com o Senhor nos ares. E assim estaremos com o Senhor para sempre.

[[v52-4-18]]

^<<v52-4-18,18>>^ Consolem-se uns aos outros com estas palavras.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-003.adoc#v52-3-0[&#60; Capítulo Anterior] | <<v52-4-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-005.adoc#v52-5-0[Próximo Capítulo &#62;]