include::./index.adoc[]

[[v18-37-0]]
=== Jó, 37
// nvi ?, NVI - Nova Versão Internacional

[[v18-37-1]]

^<<v18-37-1,1>>^ "Diante disso o meu coração bate aceleradamente e salta do seu lugar.

[[v18-37-2]]

^<<v18-37-2,2>>^ Ouça! Escute o estrondo da sua voz, o trovejar da sua boca.

[[v18-37-3]]

^<<v18-37-3,3>>^ Ele solta os seus relâmpagos por baixo de toda a extensão do céu e os manda para os confins da terra.

[[v18-37-4]]

^<<v18-37-4,4>>^ Depois vem o som do seu grande estrondo: ele troveja com sua majestosa voz. Quando a sua voz ressoa, nada o faz recuar.

[[v18-37-5]]

^<<v18-37-5,5>>^ A voz de Deus troveja maravilhosamente; ele faz coisas grandiosas, acima do nosso entendimento.

[[v18-37-6]]

^<<v18-37-6,6>>^ Ele diz à neve: ‘Caia sobre a terra’, e à chuva: ‘Seja um forte aguaceiro’.

[[v18-37-7]]

^<<v18-37-7,7>>^ Ele paralisa o trabalho de cada homem, a fim de que todos os que ele criou conheçam a sua obra.

[[v18-37-8]]

^<<v18-37-8,8>>^ Os animais vão para os seus esconderijos; e ficam nas suas tocas.

[[v18-37-9]]

^<<v18-37-9,9>>^ A tempestade sai da sua câmara, e dos ventos vem o frio.

[[v18-37-10]]

^<<v18-37-10,10>>^ O sopro de Deus produz gelo, e as vastas águas se congelam.

[[v18-37-11]]

^<<v18-37-11,11>>^ Também carrega de umidade as nuvens, e entre elas espalha os seus relâmpagos.

[[v18-37-12]]

^<<v18-37-12,12>>^ Ele as faz girar, circulando sobre a superfície de toda a terra, para fazerem tudo o que ele lhes ordenar.

[[v18-37-13]]

^<<v18-37-13,13>>^ Ele traz as nuvens, ora para castigar os homens, ora para regar a sua terra e mostrar o seu amor.

[[v18-37-14]]

^<<v18-37-14,14>>^ "Escute isto, Jó; pare e reflita nas maravilhas de Deus.

[[v18-37-15]]

^<<v18-37-15,15>>^ Acaso você sabe como Deus comanda as nuvens e faz brilhar os seus relâmpagos?

[[v18-37-16]]

^<<v18-37-16,16>>^ Você sabe como ficam suspensas as nuvens, essas maravilhas daquele que tem perfeito conhecimento?

[[v18-37-17]]

^<<v18-37-17,17>>^ Você, que em sua roupa desfalece de calor quando a terra fica amortecida sob o vento sul,

[[v18-37-18]]

^<<v18-37-18,18>>^ pode ajudá-lo a estender os céus, duros como espelho de bronze?

[[v18-37-19]]

^<<v18-37-19,19>>^ "Diga-nos o que devemos dizer a ele; não podemos elaborar a nossa defesa por causa das nossas trevas.

[[v18-37-20]]

^<<v18-37-20,20>>^ Deve-se dizer-lhe o que lhe quero falar? Quem pediria para ser devorado?

[[v18-37-21]]

^<<v18-37-21,21>>^ Ninguém pode olhar para o fulgor do sol nos céus, depois que o vento os clareia.

[[v18-37-22]]

^<<v18-37-22,22>>^ Do norte vem luz dourada; Deus vem em temível majestade.

[[v18-37-23]]

^<<v18-37-23,23>>^ Fora de nosso alcance está o Todo-poderoso, exaltado em poder; mas, em sua justiça e retidão, não oprime ninguém.

[[v18-37-24]]

^<<v18-37-24,24>>^ Por isso os homens o temem; não dá ele atenção a todos os sábios de coração? "

'''

xref:018-jo/018-jo-036.adoc#v18-36-0[&#60; Capítulo Anterior] | <<v18-37-0,Topo>> | xref:018-jo/018-jo-038.adoc#v18-38-0[Próximo Capítulo &#62;]