include::./index.adoc[]

[[v18-3-0]]
=== Jó, 3
// nvi ?, NVI - Nova Versão Internacional

[[v18-3-1]]

^<<v18-3-1,1>>^ Depois disso Jó abriu a boca e amaldiçoou o dia do seu nascimento,

[[v18-3-2]]

^<<v18-3-2,2>>^ dizendo:

[[v18-3-3]]

^<<v18-3-3,3>>^ "Pereça o dia do meu nascimento e a noite em que se disse: ‘Nasceu um menino! ’

[[v18-3-4]]

^<<v18-3-4,4>>^ Transforme-se aquele dia em trevas, e Deus, lá do alto, não se importe com ele; não resplandeça a luz sobre ele.

[[v18-3-5]]

^<<v18-3-5,5>>^ Chamem-no de volta as trevas e a mais densa escuridão; coloque-se uma nuvem sobre ele e o negrume aterrorize a sua luz.

[[v18-3-6]]

^<<v18-3-6,6>>^ Apoderem-se daquela noite densas trevas! Não seja ela incluída entre os dias do ano, nem faça parte de nenhum dos meses.

[[v18-3-7]]

^<<v18-3-7,7>>^ Seja aquela noite estéril, e nela não se ouçam brados de alegria.

[[v18-3-8]]

^<<v18-3-8,8>>^ Amaldiçoem aquele dia os que amaldiçoam os dias e são capazes de atiçar o Leviatã.

[[v18-3-9]]

^<<v18-3-9,9>>^ Fiquem escuras as suas estrelas matutinas, e espere ele em vão pela luz do sol e não veja os primeiros raios da alvorada,

[[v18-3-10]]

^<<v18-3-10,10>>^ pois não fechou as portas do ventre materno para evitar que eu contemplasse males.

[[v18-3-11]]

^<<v18-3-11,11>>^ "Por que não morri ao nascer, e não pereci quando saí do ventre?

[[v18-3-12]]

^<<v18-3-12,12>>^ Por que houve joelhos para me receberem e seios para me amamentarem?

[[v18-3-13]]

^<<v18-3-13,13>>^ Agora eu bem poderia estar deitado em paz e achar repouso

[[v18-3-14]]

^<<v18-3-14,14>>^ junto aos reis e conselheiros da terra, que construíram para si lugares que agora jazem em ruínas,

[[v18-3-15]]

^<<v18-3-15,15>>^ com governantes que possuíam ouro, que enchiam suas casas de prata.

[[v18-3-16]]

^<<v18-3-16,16>>^ Por que não me sepultaram como criança abortada, como um bebê que nunca viu a luz do dia?

[[v18-3-17]]

^<<v18-3-17,17>>^ Ali os ímpios já não se agitam, e ali os cansados permanecem em repouso;

[[v18-3-18]]

^<<v18-3-18,18>>^ os prisioneiros também desfrutam sossego, já não ouvem mais os gritos do feitor de escravos.

[[v18-3-19]]

^<<v18-3-19,19>>^ Os simples e os poderosos ali estão, e o escravo está livre de seu senhor.

[[v18-3-20]]

^<<v18-3-20,20>>^ "Por que se dá luz aos infelizes, e vida aos de alma amargurada,

[[v18-3-21]]

^<<v18-3-21,21>>^ aos que anseiam pela morte, e esta não vem, e a procuram mais do que a um tesouro oculto,

[[v18-3-22]]

^<<v18-3-22,22>>^ aos que se enchem de alegria e exultam quando vão para a sepultura?

[[v18-3-23]]

^<<v18-3-23,23>>^ Por que se dá vida àquele cujo caminho é oculto, e a quem Deus fechou as saídas?

[[v18-3-24]]

^<<v18-3-24,24>>^ Pois me vêm suspiros em vez de comida; meus gemidos transbordam como água.

[[v18-3-25]]

^<<v18-3-25,25>>^ O que eu temia veio sobre mim; o que eu receava me aconteceu.

[[v18-3-26]]

^<<v18-3-26,26>>^ Não tenho paz, nem tranqüilidade, nem descanso; somente inquietação".

'''

xref:018-jo/018-jo-002.adoc#v18-2-0[&#60; Capítulo Anterior] | <<v18-3-0,Topo>> | xref:018-jo/018-jo-004.adoc#v18-4-0[Próximo Capítulo &#62;]