include::./index.adoc[]

[[v18-15-0]]
=== Jó, 15
// nvi ?, NVI - Nova Versão Internacional

[[v18-15-1]]

^<<v18-15-1,1>>^ Então Elifaz, de Temã, respondeu:

[[v18-15-2]]

^<<v18-15-2,2>>^ "Responderia o sábio com idéias vãs, ou encheria o estômago com o vento?

[[v18-15-3]]

^<<v18-15-3,3>>^ Será que argumentaria com palavras inúteis, com discursos sem valor?

[[v18-15-4]]

^<<v18-15-4,4>>^ Mas você sufoca a piedade e diminui a devoção a Deus.

[[v18-15-5]]

^<<v18-15-5,5>>^ O seu pecado motiva a sua boca; você adota a linguagem dos astutos.

[[v18-15-6]]

^<<v18-15-6,6>>^ É a sua própria boca que o condena, e não a minha; os seus próprios lábios depõem contra você.

[[v18-15-7]]

^<<v18-15-7,7>>^ "Será que você foi o primeiro a nascer? Acaso foi gerado antes das colinas?

[[v18-15-8]]

^<<v18-15-8,8>>^ Você costuma ouvir o conselho secreto de Deus? Só a você pertence a sabedoria?

[[v18-15-9]]

^<<v18-15-9,9>>^ Que é que você sabe, que nós não sabemos? Que compreensão têm você, que nós não temos?

[[v18-15-10]]

^<<v18-15-10,10>>^ Temos do nosso lado homens de cabelos brancos, muito mais velhos que o seu pai.

[[v18-15-11]]

^<<v18-15-11,11>>^ Não lhe bastam as consolações divinas, e as nossas palavras amáveis?

[[v18-15-12]]

^<<v18-15-12,12>>^ Por que você se deixa levar pelo coração, e por que esse brilho nos seus olhos?

[[v18-15-13]]

^<<v18-15-13,13>>^ Pois contra Deus é que você dirige a sua ira e despeja da sua boca essas palavras!

[[v18-15-14]]

^<<v18-15-14,14>>^ "Como o homem pode ser puro? Como pode ser justo quem nasce de mulher?

[[v18-15-15]]

^<<v18-15-15,15>>^ Pois se nem nos seus Deus confia, e se nem os céus são puros aos seus olhos,

[[v18-15-16]]

^<<v18-15-16,16>>^ quanto menos o homem, que é impuro e corrupto, e que bebe iniqüidade como água.

[[v18-15-17]]

^<<v18-15-17,17>>^ "Escute-me, e eu lhe explicarei; vou dizer-lhe o que vi,

[[v18-15-18]]

^<<v18-15-18,18>>^ o que os sábios declaram, sem esconder o que receberam dos seus pais,

[[v18-15-19]]

^<<v18-15-19,19>>^ a quem foi dada a terra, e a mais ninguém; nenhum estrangeiro passou entre eles:

[[v18-15-20]]

^<<v18-15-20,20>>^ O ímpio sofre tormentos a vida toda, como também o homem cruel, nos poucos anos que lhe são reservados.

[[v18-15-21]]

^<<v18-15-21,21>>^ Só ouve ruídos aterrorizantes; quando se sente em paz, ladrões o atacam.

[[v18-15-22]]

^<<v18-15-22,22>>^ Não tem esperança de escapar das trevas; sente-se destinado ao fio da espada.

[[v18-15-23]]

^<<v18-15-23,23>>^ Fica perambulando; é comida para os abutres; sabe muito bem que logo virão sobre ele as trevas.

[[v18-15-24]]

^<<v18-15-24,24>>^ A aflição e a angústia o apavoram e o dominam; como um rei pronto para bater,

[[v18-15-25]]

^<<v18-15-25,25>>^ porque agitou os punhos contra Deus, e desafiou o Todo-poderoso,

[[v18-15-26]]

^<<v18-15-26,26>>^ afrontando-o com arrogância com um escudo grosso e resistente.

[[v18-15-27]]

^<<v18-15-27,27>>^ "Apesar de ter o rosto coberto de gordura e a cintura estufada de carne,

[[v18-15-28]]

^<<v18-15-28,28>>^ habitará em cidades prestes a arruinar-se, em casas inabitáveis, caindo aos pedaços.

[[v18-15-29]]

^<<v18-15-29,29>>^ Nunca mais será rico; sua riqueza não durará, e os seus bens não se propagarão pela terra.

[[v18-15-30]]

^<<v18-15-30,30>>^ Não poderá escapar das trevas; o fogo chamuscará os seus renovos, e o sopro da boca de Deus o arrebatará.

[[v18-15-31]]

^<<v18-15-31,31>>^ Que ele não se iluda em confiar no que não tem valor, pois nada receberá como compensação.

[[v18-15-32]]

^<<v18-15-32,32>>^ Terá completa paga antes do tempo, e os seus ramos não florescerão.

[[v18-15-33]]

^<<v18-15-33,33>>^ Ele será como a vinha despojada de suas uvas verdes, como a oliveira que perdeu a sua floração,

[[v18-15-34]]

^<<v18-15-34,34>>^ pois o companheirismo dos ímpios nada lhe trará, e o fogo devorará as tendas dos que gostam de subornar.

[[v18-15-35]]

^<<v18-15-35,35>>^ Eles concebem maldade e dão à luz a iniqüidade; seu ventre gera engano".

'''

xref:018-jo/018-jo-014.adoc#v18-14-0[&#60; Capítulo Anterior] | <<v18-15-0,Topo>> | xref:018-jo/018-jo-016.adoc#v18-16-0[Próximo Capítulo &#62;]