include::./index.adoc[]

[[v18-22-0]]
=== Jó, 22
// nvi ?, NVI - Nova Versão Internacional

[[v18-22-1]]

^<<v18-22-1,1>>^ Então, de Temã, Elifaz respondeu:

[[v18-22-2]]

^<<v18-22-2,2>>^ "Pode alguém ser útil a Deus? Mesmo um sábio, pode ser-lhe de algum proveito?

[[v18-22-3]]

^<<v18-22-3,3>>^ Que prazer você daria ao Todo-poderoso se você fosse justo? Que é que ele ganharia se os seus caminhos fossem irrepreensíveis?

[[v18-22-4]]

^<<v18-22-4,4>>^ "É por sua piedade que ele o repreende e lhe faz acusações?

[[v18-22-5]]

^<<v18-22-5,5>>^ Não é grande a sua maldade? Não são infindos os seus pecados?

[[v18-22-6]]

^<<v18-22-6,6>>^ Sem motivo você exigia penhores dos seus irmãos; você despojava das roupas os que quase nenhuma tinham.

[[v18-22-7]]

^<<v18-22-7,7>>^ Você não deu água ao sedento e reteve a comida do faminto,

[[v18-22-8]]

^<<v18-22-8,8>>^ sendo você poderoso, e dono de terras, delas vivendo, e honrado diante de todos.

[[v18-22-9]]

^<<v18-22-9,9>>^ Você mandou embora de mãos vazias as viúvas e quebrou a força dos órfãos.

[[v18-22-10]]

^<<v18-22-10,10>>^ Por isso está cercado de armadilhas e o perigo repentino o apavora.

[[v18-22-11]]

^<<v18-22-11,11>>^ Também por isso você se vê envolto em escuridão que o cega, e o cobrem as águas, em tremenda inundação.

[[v18-22-12]]

^<<v18-22-12,12>>^ "Não está Deus nas alturas dos céus? E em que altura estão as estrelas mais distantes!

[[v18-22-13]]

^<<v18-22-13,13>>^ Contudo você diz: ‘Que é que Deus sabe? Poderá julgar através de tão grande escuridão?

[[v18-22-14]]

^<<v18-22-14,14>>^ Nuvens espessas o cobrem, e ele não pode nos ver, quando percorre a abóbada dos céus’.

[[v18-22-15]]

^<<v18-22-15,15>>^ Você vai continuar no velho caminho que os perversos palmilharam?

[[v18-22-16]]

^<<v18-22-16,16>>^ Estes foram levados antes da hora; seus alicerces foram arrastados por uma enchente.

[[v18-22-17]]

^<<v18-22-17,17>>^ Eles disseram a Deus: ‘Deixa-nos! Que é que o Todo-poderoso poderá fazer conosco? ’

[[v18-22-18]]

^<<v18-22-18,18>>^ Contudo, foi ele que encheu de bens as casas deles; por isso fico longe do conselho dos ímpios.

[[v18-22-19]]

^<<v18-22-19,19>>^ "Os justos vêem a ruína deles, e se regozijam; os inocentes zombam deles, dizendo:

[[v18-22-20]]

^<<v18-22-20,20>>^ ‘Certo é que os nossos inimigos foram destruídos, e o fogo devorou a sua riqueza’.

[[v18-22-21]]

^<<v18-22-21,21>>^ "Sujeite-se a Deus, fique em paz com ele, e a prosperidade virá a você.

[[v18-22-22]]

^<<v18-22-22,22>>^ Aceite a instrução que vem da sua boca e ponha no coração as suas palavras.

[[v18-22-23]]

^<<v18-22-23,23>>^ Se você voltar-se para o Todo-poderoso, voltará ao seu lugar: Se afastar da sua tenda a injustiça,

[[v18-22-24]]

^<<v18-22-24,24>>^ lançar ao pó as suas pepitas, o seu ouro puro de Ofir às rochas dos vales,

[[v18-22-25]]

^<<v18-22-25,25>>^ o Todo-poderoso será o seu ouro, será para você prata seleta.

[[v18-22-26]]

^<<v18-22-26,26>>^ É certo que você achará prazer no Todo-poderoso e erguerá o rosto para Deus.

[[v18-22-27]]

^<<v18-22-27,27>>^ A ele orará, e ele o ouvirá, e você cumprirá os seus votos.

[[v18-22-28]]

^<<v18-22-28,28>>^ O que você decidir se fará, e a luz brilhará em seus caminhos.

[[v18-22-29]]

^<<v18-22-29,29>>^ Quando os homens forem humilhados e você disser: ‘Levanta-os! ’, ele salvará o abatido.

[[v18-22-30]]

^<<v18-22-30,30>>^ Livrará até o que não é inocente, que será liberto graças à pureza que há nas suas mãos".

'''

xref:018-jo/018-jo-021.adoc#v18-21-0[&#60; Capítulo Anterior] | <<v18-22-0,Topo>> | xref:018-jo/018-jo-023.adoc#v18-23-0[Próximo Capítulo &#62;]