include::./index.adoc[]

[[v18-11-0]]
=== Jó, 11
// nvi ?, NVI - Nova Versão Internacional

[[v18-11-1]]

^<<v18-11-1,1>>^ Então Zofar, de Naamate, respondeu:

[[v18-11-2]]

^<<v18-11-2,2>>^ "Ficarão sem resposta todas essas palavras? Irá se confirmar o que esse tagarela diz?

[[v18-11-3]]

^<<v18-11-3,3>>^ Sua conversa tola calará os homens? Ninguém o repreenderá por sua zombaria?

[[v18-11-4]]

^<<v18-11-4,4>>^ Você diz a Deus: ‘A doutrina que eu aceito é perfeita, e sou puro aos teus olhos’.

[[v18-11-5]]

^<<v18-11-5,5>>^ Ah, se Deus lhe falasse, se abrisse os lábios contra você

[[v18-11-6]]

^<<v18-11-6,6>>^ e lhe revelasse os segredos da sabedoria! Pois a verdadeira sabedoria é complexa. Fique sabendo que Deus esqueceu alguns dos seus pecados.

[[v18-11-7]]

^<<v18-11-7,7>>^ "Você consegue perscrutar os mistérios de Deus? Pode sondar os limites do Todo-poderoso?

[[v18-11-8]]

^<<v18-11-8,8>>^ São mais altos que os céus! Que é que você poderá fazer? São mais profundos que as profundezas! O que você poderá saber?

[[v18-11-9]]

^<<v18-11-9,9>>^ Seu comprimento é maior do que a terra e a sua largura é maior do que o mar.

[[v18-11-10]]

^<<v18-11-10,10>>^ "Se ele ordena uma prisão e convoca o tribunal, quem poderá opor-se?

[[v18-11-11]]

^<<v18-11-11,11>>^ Pois ele identifica os enganadores; e não reconhece a iniqüidade logo que a vê?

[[v18-11-12]]

^<<v18-11-12,12>>^ Mas o tolo só será sábio quando a cria do jumento selvagem nascer homem.

[[v18-11-13]]

^<<v18-11-13,13>>^ "Contudo, se você lhe consagrar o coração, e estender as mãos para ele;

[[v18-11-14]]

^<<v18-11-14,14>>^ se afastar das suas mãos o pecado, e não permitir que a maldade habite em sua tenda,

[[v18-11-15]]

^<<v18-11-15,15>>^ então você levantará o rosto sem envergonhar-se; serás firme e destemido.

[[v18-11-16]]

^<<v18-11-16,16>>^ Você esquecerá as suas desgraças, lembrando-as apenas como águas passadas.

[[v18-11-17]]

^<<v18-11-17,17>>^ A vida será mais refulgente que o meio-dia, e as trevas serão como a manhã que brilha.

[[v18-11-18]]

^<<v18-11-18,18>>^ Você estará confiante, graças a esperança que haverá; olhará ao redor, e repousará em segurança.

[[v18-11-19]]

^<<v18-11-19,19>>^ Você se deitará, e ninguém lhe causará medo, e muitos procurarão o seu favor.

[[v18-11-20]]

^<<v18-11-20,20>>^ Mas os olhos dos ímpios fenecerão, e em vão procurarão refúgio; o suspiro da morte será a esperança que terão".

'''

xref:018-jo/018-jo-010.adoc#v18-10-0[&#60; Capítulo Anterior] | <<v18-11-0,Topo>> | xref:018-jo/018-jo-012.adoc#v18-12-0[Próximo Capítulo &#62;]