include::./index.adoc[]

[[v18-7-0]]
=== Jó, 7
// nvi ?, NVI - Nova Versão Internacional

[[v18-7-1]]

^<<v18-7-1,1>>^ "Não é pesado o labor do homem na terra? Seus dias não são como os de um assalariado?

[[v18-7-2]]

^<<v18-7-2,2>>^ Como o escravo que anseia pelas sombras do entardecer, ou como o assalariado que espera ansioso pelo pagamento,

[[v18-7-3]]

^<<v18-7-3,3>>^ assim me deram meses de ilusão, e noites de desgraça me foram destinadas.

[[v18-7-4]]

^<<v18-7-4,4>>^ Quando me deito, fico pensando: ‘Quanto vai demorar para eu me levantar? ’ A noite se arrasta, e eu fico me virando na cama até o amanhecer.

[[v18-7-5]]

^<<v18-7-5,5>>^ Meu corpo está coberto de vermes e cascas de ferida, minha pele está rachada e vertendo pus.

[[v18-7-6]]

^<<v18-7-6,6>>^ "Meus dias correm mais depressa que a lançadeira do tecelão, e chegam ao fim sem nenhuma esperança.

[[v18-7-7]]

^<<v18-7-7,7>>^ Lembra-te, ó Deus, de que a minha vida não passa de um sopro; meus olhos jamais tornarão a ver a felicidade.

[[v18-7-8]]

^<<v18-7-8,8>>^ Os que agora me vêem, nunca mais me verão; puseste o teu olhar em mim, e já não existo.

[[v18-7-9]]

^<<v18-7-9,9>>^ Assim como a nuvem esvai-se e desaparece, assim quem desce à sepultura não volta.

[[v18-7-10]]

^<<v18-7-10,10>>^ Nunca mais voltará ao seu lar; a sua habitação não mais o conhecerá.

[[v18-7-11]]

^<<v18-7-11,11>>^ "Por isso não me calo; na aflição do meu espírito me desabafarei, na amargura da minha alma farei as minhas queixas.

[[v18-7-12]]

^<<v18-7-12,12>>^ Sou eu o mar, ou o monstro das profundezas, para que me ponhas sob guarda?

[[v18-7-13]]

^<<v18-7-13,13>>^ Quando penso que a minha cama me consolará e que o meu leito aliviará a minha queixa,

[[v18-7-14]]

^<<v18-7-14,14>>^ mesmo aí me assustas com sonhos e me aterrorizas com visões.

[[v18-7-15]]

^<<v18-7-15,15>>^ Prefiro ser estrangulado e morrer do que sofrer assim;

[[v18-7-16]]

^<<v18-7-16,16>>^ sinto desprezo pela minha vida! Não vou viver para sempre; deixa-me, pois os meus dias não têm sentido.

[[v18-7-17]]

^<<v18-7-17,17>>^ "Que é o homem, para que lhe dês importância e atenção,

[[v18-7-18]]

^<<v18-7-18,18>>^ para que o examines a cada manhã e o proves a cada instante?

[[v18-7-19]]

^<<v18-7-19,19>>^ Nunca desviarás de mim o teu olhar? Nunca me deixarás a sós, nem por um instante?

[[v18-7-20]]

^<<v18-7-20,20>>^ Se pequei, que mal te causei, ó tu que vigias os homens? Por que me tornaste teu alvo? Acaso tornei-me um fardo para ti?

[[v18-7-21]]

^<<v18-7-21,21>>^ Por que não perdoas as minhas ofensas e não apagas os meus pecados? Pois logo me deitarei no pó; tu me procurarás, mas eu já não existirei".

'''

xref:018-jo/018-jo-006.adoc#v18-6-0[&#60; Capítulo Anterior] | <<v18-7-0,Topo>> | xref:018-jo/018-jo-008.adoc#v18-8-0[Próximo Capítulo &#62;]