include::./index.adoc[]

[[v18-13-0]]
=== Jó, 13
// nvi ?, NVI - Nova Versão Internacional

[[v18-13-1]]

^<<v18-13-1,1>>^ "Meus olhos viram tudo isso, meus ouvidos o ouviram e entenderam.

[[v18-13-2]]

^<<v18-13-2,2>>^ O que vocês sabem, eu também sei; não sou inferior a vocês.

[[v18-13-3]]

^<<v18-13-3,3>>^ Mas desejo falar ao Todo-poderoso e defender a minha causa diante de Deus.

[[v18-13-4]]

^<<v18-13-4,4>>^ Vocês, porém, me difamam com mentiras; todos vocês são médicos que de nada valem!

[[v18-13-5]]

^<<v18-13-5,5>>^ Se tão-somente ficassem calados! Mostrariam sabedoria.

[[v18-13-6]]

^<<v18-13-6,6>>^ Escutem agora o meu argumento; prestem atenção à réplica de meus lábios.

[[v18-13-7]]

^<<v18-13-7,7>>^ Vocês vão falar com maldade em nome de Deus? Vão falar enganosamente a favor dele?

[[v18-13-8]]

^<<v18-13-8,8>>^ Vão revelar parcialidade por ele? Vão defender a causa a favor de Deus?

[[v18-13-9]]

^<<v18-13-9,9>>^ Tudo iria bem, se ele os examinasse? Vocês conseguiriam enganá-lo, como podem enganar os homens?

[[v18-13-10]]

^<<v18-13-10,10>>^ Com certeza ele os repreenderia, se no íntimo vocês fossem parciais.

[[v18-13-11]]

^<<v18-13-11,11>>^ O esplendor dele não os aterrorizaria? O pavor dele não cairia sobre vocês?

[[v18-13-12]]

^<<v18-13-12,12>>^ As máximas que vocês citam são provérbios de cinza; suas defesas não passam de barro.

[[v18-13-13]]

^<<v18-13-13,13>>^ "Aquietem-se e deixem-me falar; e aconteça-me o que me acontecer.

[[v18-13-14]]

^<<v18-13-14,14>>^ Por que me ponho em perigo e tomo a minha vida em minhas mãos?

[[v18-13-15]]

^<<v18-13-15,15>>^ Embora ele me mate, ainda assim esperarei nele; certo é que defenderei os meus caminhos diante dele.

[[v18-13-16]]

^<<v18-13-16,16>>^ Aliás, isso será a minha libertação, pois nenhum ímpio ousaria apresentar-se a ele!

[[v18-13-17]]

^<<v18-13-17,17>>^ Escutem atentamente as minhas palavras; que os seus ouvidos acolham o que eu digo.

[[v18-13-18]]

^<<v18-13-18,18>>^ Agora que preparei a minha defesa, sei que serei justificado.

[[v18-13-19]]

^<<v18-13-19,19>>^ Haverá quem me acuse? Se houver, ficarei calado e morrerei.

[[v18-13-20]]

^<<v18-13-20,20>>^ "Concede-me só estas duas coisas, ó Deus, e não me esconderei de ti:

[[v18-13-21]]

^<<v18-13-21,21>>^ Afasta de mim a tua mão, e não mais me assuste com os teus terrores.

[[v18-13-22]]

^<<v18-13-22,22>>^ Chama-me, e eu responderei, ou deixa-me falar, e tu responderás.

[[v18-13-23]]

^<<v18-13-23,23>>^ Quantos erros e pecados cometi? Mostra-me a minha falta e o meu pecado.

[[v18-13-24]]

^<<v18-13-24,24>>^ Por que escondes o teu rosto e consideras-me teu inimigo?

[[v18-13-25]]

^<<v18-13-25,25>>^ Atormentarás uma folha levada pelo vento? Perseguirás a palha?

[[v18-13-26]]

^<<v18-13-26,26>>^ Pois fazes constar contra mim coisas amargas e fazes-me herdar os pecados da minha juventude.

[[v18-13-27]]

^<<v18-13-27,27>>^ Acorrentas os meus pés e vigias todos os meus caminhos, pondo limites aos meus passos.

[[v18-13-28]]

^<<v18-13-28,28>>^ "Assim o homem se consome como coisa podre, como a roupa que a traça vai roendo.

'''

xref:018-jo/018-jo-012.adoc#v18-12-0[&#60; Capítulo Anterior] | <<v18-13-0,Topo>> | xref:018-jo/018-jo-014.adoc#v18-14-0[Próximo Capítulo &#62;]