include::./index.adoc[]

[[v18-41-0]]
=== Jó, 41
// nvi ?, NVI - Nova Versão Internacional

[[v18-41-1]]

^<<v18-41-1,1>>^ "Você consegue pescar com anzol o leviatã ou prender sua língua com uma corda?

[[v18-41-2]]

^<<v18-41-2,2>>^ Consegue fazer passar um cordão pelo seu nariz ou atravessar seu queixo com um gancho?

[[v18-41-3]]

^<<v18-41-3,3>>^ Pensa que ele vai lhe implorar misericórdia e lhe vai falar palavras amáveis?

[[v18-41-4]]

^<<v18-41-4,4>>^ Acha que ele vai fazer acordo com você, para que você o tenha como escravo pelo resto da vida?

[[v18-41-5]]

^<<v18-41-5,5>>^ Acaso você consegue fazer dele um bichinho de estimação, como se ele fosse um passarinho, ou pôr-lhe uma coleira para as suas filhas?

[[v18-41-6]]

^<<v18-41-6,6>>^ Poderão os negociantes vendê-lo? Ou reparti-lo entre os comerciantes?

[[v18-41-7]]

^<<v18-41-7,7>>^ Você consegue encher de arpões o seu couro, e de lanças de pesca a sua cabeça?

[[v18-41-8]]

^<<v18-41-8,8>>^ Se puser a mão nele, a luta ficará em sua memória, e nunca mais você tornará a fazê-lo.

[[v18-41-9]]

^<<v18-41-9,9>>^ Esperar vencê-lo é ilusão; só vê-lo já é assustador.

[[v18-41-10]]

^<<v18-41-10,10>>^ Ninguém é suficientemente corajoso para despertá-lo. Quem então será capaz de resistir a mim?

[[v18-41-11]]

^<<v18-41-11,11>>^ Quem primeiro me deu alguma coisa, que eu lhe deva pagar? Tudo o que há debaixo dos céus me pertence.

[[v18-41-12]]

^<<v18-41-12,12>>^ "Não deixarei de falar de seus membros, de sua força e de seu porte gracioso.

[[v18-41-13]]

^<<v18-41-13,13>>^ Quem consegue arrancar sua capa externa? Quem se aproximaria dele com uma rédea?

[[v18-41-14]]

^<<v18-41-14,14>>^ Quem ousa abrir as portas de sua boca, cercada com seus dentes temíveis?

[[v18-41-15]]

^<<v18-41-15,15>>^ Suas costas possuem fileiras de escudos firmemente unidos;

[[v18-41-16]]

^<<v18-41-16,16>>^ cada um está tão junto do outro que nem o ar passa entre eles;

[[v18-41-17]]

^<<v18-41-17,17>>^ estão tão interligados, que é impossível separá-los.

[[v18-41-18]]

^<<v18-41-18,18>>^ Seu forte sopro atira lampejos de luz; seus olhos são como os raios da alvorada.

[[v18-41-19]]

^<<v18-41-19,19>>^ Tições saem da sua boca; fagulhas de fogo estalam.

[[v18-41-20]]

^<<v18-41-20,20>>^ Das suas narinas sai fumaça como de panela fervente sobre fogueira de juncos.

[[v18-41-21]]

^<<v18-41-21,21>>^ Seu sopro faz o carvão pegar fogo, e da sua boca saltam chamas.

[[v18-41-22]]

^<<v18-41-22,22>>^ Tanta força reside em seu pescoço que o terror vai adiante dele.

[[v18-41-23]]

^<<v18-41-23,23>>^ As dobras da sua carne são fortemente unidas; são tão firmes que não se movem.

[[v18-41-24]]

^<<v18-41-24,24>>^ Seu peito é duro como pedra, rijo como a pedra inferior do moinho.

[[v18-41-25]]

^<<v18-41-25,25>>^ Quando ele se ergue, os poderosos se apavoram; fogem com medo dos seus golpes.

[[v18-41-26]]

^<<v18-41-26,26>>^ A espada que o atinge não lhe faz nada, nem a lança nem a flecha nem o dardo.

[[v18-41-27]]

^<<v18-41-27,27>>^ Ferro ele trata como palha, e bronze como madeira podre.

[[v18-41-28]]

^<<v18-41-28,28>>^ As flechas não o afugentam, as pedras das fundas são como cisco para ele.

[[v18-41-29]]

^<<v18-41-29,29>>^ O bastão lhe parece fiapo de palha; o brandir da grande lança o faz rir.

[[v18-41-30]]

^<<v18-41-30,30>>^ Seu ventre é como caco denteado, e deixa rastro na lama como o trilho de debulhar.

[[v18-41-31]]

^<<v18-41-31,31>>^ Ele faz as profundezas se agitarem como caldeirão fervente, e revolve o mar como pote de ungüento.

[[v18-41-32]]

^<<v18-41-32,32>>^ Deixa atrás de si um rastro cintilante; como se fossem os cabelos brancos do abismo.

[[v18-41-33]]

^<<v18-41-33,33>>^ Nada na terra se equipara a ele; criatura destemida!

[[v18-41-34]]

^<<v18-41-34,34>>^ Com desdém olha todos os altivos; reina soberano sobre todos os orgulhosos".

'''

xref:018-jo/018-jo-040.adoc#v18-40-0[&#60; Capítulo Anterior] | <<v18-41-0,Topo>> | xref:018-jo/018-jo-042.adoc#v18-42-0[Próximo Capítulo &#62;]