include::./index.adoc[]

[[v18-36-0]]
=== Jó, 36
// nvi ?, NVI - Nova Versão Internacional

[[v18-36-1]]

^<<v18-36-1,1>>^ Disse mais Eliú:

[[v18-36-2]]

^<<v18-36-2,2>>^ "Peço-lhe que seja um pouco mais paciente comigo, e lhe mostrarei que se pode dizer mais verdades em defesa de Deus.

[[v18-36-3]]

^<<v18-36-3,3>>^ Vem de longe o meu conhecimento; atribuirei justiça ao meu Criador.

[[v18-36-4]]

^<<v18-36-4,4>>^ Não tenha dúvida de que as minhas palavras não são falsas; quem está com você é a perfeição no conhecimento.

[[v18-36-5]]

^<<v18-36-5,5>>^ "Deus é poderoso, mas não despreza os homens; é poderoso e firme em seu propósito.

[[v18-36-6]]

^<<v18-36-6,6>>^ Não poupa a vida dos ímpios, mas garante os direitos dos aflitos.

[[v18-36-7]]

^<<v18-36-7,7>>^ Não tira os seus olhos do justo; ele o coloca nos tronos com os reis e o exalta para sempre.

[[v18-36-8]]

^<<v18-36-8,8>>^ Mas, se os homens forem acorrentados, presos firmemente com as cordas da aflição,

[[v18-36-9]]

^<<v18-36-9,9>>^ e lhes dirá o que fizeram, que pecaram com arrogância.

[[v18-36-10]]

^<<v18-36-10,10>>^ Ele os fará ouvir a correção e lhes ordenará que se arrependam do mal que praticaram.

[[v18-36-11]]

^<<v18-36-11,11>>^ Se lhe obedecerem e o servirem, serão prósperos até o fim dos seus dias e terão contentamento nos anos que lhes restam.

[[v18-36-12]]

^<<v18-36-12,12>>^ Mas, se não obedecerem, perecerão à espada e morrerão na ignorância.

[[v18-36-13]]

^<<v18-36-13,13>>^ "Os que têm coração ímpio guardam ressentimento; mesmo quando ele os agrilhoa eles não clamam por socorro.

[[v18-36-14]]

^<<v18-36-14,14>>^ Morrem em plena juventude entre os prostitutos dos santuários.

[[v18-36-15]]

^<<v18-36-15,15>>^ Mas aos que sofrem ele os livra em meio ao sofrimento; em sua aflição ele lhes fala.

[[v18-36-16]]

^<<v18-36-16,16>>^ "Ele está atraindo você para longe das mandíbulas da aflição, para um lugar amplo e livre, para o conforto da mesa farta e seleta que você terá.

[[v18-36-17]]

^<<v18-36-17,17>>^ Mas agora, farto sobre você é o julgamento que cabe aos ímpios; o julgamento e a justiça o pegaram.

[[v18-36-18]]

^<<v18-36-18,18>>^ Cuidado! Que ninguém o seduza com riquezas; não se deixe desviar por suborno, por maior que este seja.

[[v18-36-19]]

^<<v18-36-19,19>>^ Acaso a sua riqueza, ou mesmo todos os seus grandes esforços, dariam a você apoio e alívio da aflição?

[[v18-36-20]]

^<<v18-36-20,20>>^ Não anseie pela noite, quando o povo é tirado dos seus lares.

[[v18-36-21]]

^<<v18-36-21,21>>^ Cuidado! Não se volte para a iniqüidade, que você parece preferir à aflição.

[[v18-36-22]]

^<<v18-36-22,22>>^ "Deus é exaltado em seu poder. Quem é mestre como ele?

[[v18-36-23]]

^<<v18-36-23,23>>^ Quem lhe prescreveu os seus caminhos, ou lhe disse: ‘Agiste mal’?

[[v18-36-24]]

^<<v18-36-24,24>>^ Lembre-se de exaltar as suas obras, às quais os homens dedicam cânticos de louvor.

[[v18-36-25]]

^<<v18-36-25,25>>^ Toda a humanidade as vê; de lugares distantes os homens as contemplam.

[[v18-36-26]]

^<<v18-36-26,26>>^ Como Deus é grande! Ultrapassa o nosso entendimento! Não há como calcular os anos da sua existência.

[[v18-36-27]]

^<<v18-36-27,27>>^ "Ele atrai as gotas de água, que se dissolvem e descem como chuva para os regatos;

[[v18-36-28]]

^<<v18-36-28,28>>^ as nuvens as despejam em aguaceiros sobre a humanidade.

[[v18-36-29]]

^<<v18-36-29,29>>^ Quem pode entender como ele estende as suas nuvens, como ele troveja desde o seu pavilhão?

[[v18-36-30]]

^<<v18-36-30,30>>^ Observe como ele espalha os seus relâmpagos ao redor, iluminando até as profundezas do mar.

[[v18-36-31]]

^<<v18-36-31,31>>^ É assim que ele governa as nações e lhes fornece grande fartura.

[[v18-36-32]]

^<<v18-36-32,32>>^ Ele enche as mãos de relâmpagos e lhes determina o alvo que deverão atingir.

[[v18-36-33]]

^<<v18-36-33,33>>^ Seu trovão anuncia a tempestade que está a caminho; até o gado a pressente.

'''

xref:018-jo/018-jo-035.adoc#v18-35-0[&#60; Capítulo Anterior] | <<v18-36-0,Topo>> | xref:018-jo/018-jo-037.adoc#v18-37-0[Próximo Capítulo &#62;]