include::./index.adoc[]

[[v18-39-0]]
=== Jó, 39
// nvi ?, NVI - Nova Versão Internacional

[[v18-39-1]]

^<<v18-39-1,1>>^ "Você sabe quando as cabras monteses dão à luz? Você está atento quando a corça tem o seu filhote?

[[v18-39-2]]

^<<v18-39-2,2>>^ Acaso você conta os meses até elas darem à luz? Sabe em que época elas têm as suas crias?

[[v18-39-3]]

^<<v18-39-3,3>>^ Elas se agacham, dão à luz os seus filhotes, e suas dores se vão.

[[v18-39-4]]

^<<v18-39-4,4>>^ Seus filhotes crescem nos campos e ficam fortes; partem, e não voltam mais.

[[v18-39-5]]

^<<v18-39-5,5>>^ "Quem pôs em liberdade o jumento selvagem? Quem soltou suas cordas?

[[v18-39-6]]

^<<v18-39-6,6>>^ Eu lhe dei o deserto como lar, os leito seco de lagos salgados como sua morada.

[[v18-39-7]]

^<<v18-39-7,7>>^ Ele se ri da agitação da cidade; não ouve os gritos do tropeiro.

[[v18-39-8]]

^<<v18-39-8,8>>^ Vagueia pelas colinas em busca de pasto e vai em busca daquilo que é verde.

[[v18-39-9]]

^<<v18-39-9,9>>^ "Será que o boi selvagem consentirá em servir você? e em passar a noite ao lado dos cochos do seu curral?

[[v18-39-10]]

^<<v18-39-10,10>>^ Poderá você prendê-lo com arreio na vala? Irá atrás de você arando os vales?

[[v18-39-11]]

^<<v18-39-11,11>>^ Você vai confiar nele, por causa da sua grande força? Vai deixar a cargo dele o trabalho pesado que você tem que fazer?

[[v18-39-12]]

^<<v18-39-12,12>>^ Poderá você estar certo de que ele recolherá o seu trigo e o ajuntará na sua eira?

[[v18-39-13]]

^<<v18-39-13,13>>^ "A avestruz bate as asas alegremente. Que se dirá então das asas e da plumagem da cegonha?

[[v18-39-14]]

^<<v18-39-14,14>>^ Ela abandona os ovos no chão e deixa que a areia os aqueça,

[[v18-39-15]]

^<<v18-39-15,15>>^ esquecida de que um pé poderá esmagá-los, que algum animal selvagem poderá pisoteá-los.

[[v18-39-16]]

^<<v18-39-16,16>>^ Ela trata mal os seus filhotes, como se não fossem dela, e não se importa se o seu trabalho é inútil.

[[v18-39-17]]

^<<v18-39-17,17>>^ Isso porque Deus não lhe deu sabedoria nem parcela alguma de bom senso.

[[v18-39-18]]

^<<v18-39-18,18>>^ Contudo, quando estende as penas para correr, ela ri do cavalo e daquele que o cavalga.

[[v18-39-19]]

^<<v18-39-19,19>>^ "É você que dá força ao cavalo ou veste o seu pescoço com sua crina tremulante?

[[v18-39-20]]

^<<v18-39-20,20>>^ Você o faz saltar como gafanhoto, espalhando terror com o seu orgulhoso resfolegar?

[[v18-39-21]]

^<<v18-39-21,21>>^ Ele escarva com fúria, mostra com prazer a sua força, e sai para enfrentar as armas.

[[v18-39-22]]

^<<v18-39-22,22>>^ Ele ri do medo, e nada teme; não recua diante da espada.

[[v18-39-23]]

^<<v18-39-23,23>>^ A aljava balança ao seu lado, com a lança e o dardo flamejantes.

[[v18-39-24]]

^<<v18-39-24,24>>^ Num furor frenético ele devora o chão; não consegue esperar pelo toque da trombeta.

[[v18-39-25]]

^<<v18-39-25,25>>^ Ao toque da trombeta, ele relincha: ‘Eia! ’ De longe sente cheiro de combate, o brado de comando e o grito de guerra.

[[v18-39-26]]

^<<v18-39-26,26>>^ "É graças a inteligência que você tem que o falcão alça vôo e estende as asas rumo sul?

[[v18-39-27]]

^<<v18-39-27,27>>^ É porque você manda, que a águia se eleva, e no alto constrói o seu ninho?

[[v18-39-28]]

^<<v18-39-28,28>>^ Um penhasco é sua morada, e ali passa a noite; uma escarpa rochosa é a sua fortaleza.

[[v18-39-29]]

^<<v18-39-29,29>>^ De lá sai ela em busca de alimento; de longe os seus olhos o vêem.

[[v18-39-30]]

^<<v18-39-30,30>>^ Seus filhotes bebem sangue, e, onde há mortos, ali ela está".

'''

xref:018-jo/018-jo-038.adoc#v18-38-0[&#60; Capítulo Anterior] | <<v18-39-0,Topo>> | xref:018-jo/018-jo-040.adoc#v18-40-0[Próximo Capítulo &#62;]