include::./index.adoc[]

[[v18-4-0]]
=== Jó, 4
// nvi ?, NVI - Nova Versão Internacional

[[v18-4-1]]

^<<v18-4-1,1>>^ Então respondeu Elifaz, de Temã:

[[v18-4-2]]

^<<v18-4-2,2>>^ "Se alguém se aventurar a dizer-lhe uma palavra, você ficará impaciente? Mas quem pode refrear as palavras?

[[v18-4-3]]

^<<v18-4-3,3>>^ Pense bem! Você ensinou a tantos; fortaleceu mãos fracas.

[[v18-4-4]]

^<<v18-4-4,4>>^ Suas palavras davam firmeza aos que tropeçavam; você fortaleceu joelhos vacilantes.

[[v18-4-5]]

^<<v18-4-5,5>>^ Mas agora que se vê em dificuldade, você se desanima; quando você é atingido, fica prostrado.

[[v18-4-6]]

^<<v18-4-6,6>>^ Sua vida piedosa não lhe inspira confiança, e o seu procedimento irrepreensível não lhe dá esperança?

[[v18-4-7]]

^<<v18-4-7,7>>^ "Reflita agora: Qual foi o inocente que chegou a perecer? Onde foi que os íntegros sofreram destruição?

[[v18-4-8]]

^<<v18-4-8,8>>^ Pelo que tenho observado, quem cultiva o mal e semeia maldade, isso também colherá.

[[v18-4-9]]

^<<v18-4-9,9>>^ Pelo sopro de Deus são destruídos; pelo vento de sua ira eles perecem.

[[v18-4-10]]

^<<v18-4-10,10>>^ Os leões podem rugir e rosnar, mas até os dentes dos leões fortes se quebram.

[[v18-4-11]]

^<<v18-4-11,11>>^ O leão morre por falta de presa, e os filhotes da leoa se dispersam.

[[v18-4-12]]

^<<v18-4-12,12>>^ "Disseram-me uma palavra em segredo, da qual os meus ouvidos captaram um murmúrio.

[[v18-4-13]]

^<<v18-4-13,13>>^ Em meio a sonhos perturbadores da noite, quando cai sono profundo sobre os homens,

[[v18-4-14]]

^<<v18-4-14,14>>^ temor e tremor se apoderaram de mim e fizeram estremecer todos os meus ossos.

[[v18-4-15]]

^<<v18-4-15,15>>^ Um espírito roçou o meu rosto, e os pêlos do meu corpo se arrepiaram.

[[v18-4-16]]

^<<v18-4-16,16>>^ Ele parou, mas não pude identificá-lo. Um vulto se pôs diante dos meus olhos, e ouvi uma voz suave, que dizia:

[[v18-4-17]]

^<<v18-4-17,17>>^ ‘Poderá algum mortal ser mais justo que Deus? Poderá algum homem ser mais puro que o seu Criador?

[[v18-4-18]]

^<<v18-4-18,18>>^ Se Deus não confia em seus servos, se vê erro em seus anjos e os acusa,

[[v18-4-19]]

^<<v18-4-19,19>>^ quanto mais nos que moram em casas de barro, cujos alicerces estão no pó! São mais facilmente esmagados que uma traça!

[[v18-4-20]]

^<<v18-4-20,20>>^ Entre o alvorecer e o crepúsculo são despedaçados; perecem para sempre, sem sequer serem notados.

[[v18-4-21]]

^<<v18-4-21,21>>^ Não é certo que as cordas de suas tendas são arrancadas, e eles morrem sem sabedoria? ’

'''

xref:018-jo/018-jo-003.adoc#v18-3-0[&#60; Capítulo Anterior] | <<v18-4-0,Topo>> | xref:018-jo/018-jo-005.adoc#v18-5-0[Próximo Capítulo &#62;]