include::./index.adoc[]

[[v18-19-0]]
=== Jó, 19
// nvi ?, NVI - Nova Versão Internacional

[[v18-19-1]]

^<<v18-19-1,1>>^ Então Jó respondeu:

[[v18-19-2]]

^<<v18-19-2,2>>^ "Até quando vocês continuarão a atormentar-me, e a esmagar-me com palavras?

[[v18-19-3]]

^<<v18-19-3,3>>^ Vocês já me repreenderam dez vezes; não se envergonham de agredir-me!

[[v18-19-4]]

^<<v18-19-4,4>>^ Se é verdade que me desviei, meu erro só interessa a mim.

[[v18-19-5]]

^<<v18-19-5,5>>^ Se de fato vocês se exaltam acima de mim e usam contra mim a minha humilhação,

[[v18-19-6]]

^<<v18-19-6,6>>^ saibam que foi Deus que me tratou mal e me envolveu em sua rede.

[[v18-19-7]]

^<<v18-19-7,7>>^ "Se grito: É injustiça! Não obtenho resposta; clamo por socorro, todavia não há justiça.

[[v18-19-8]]

^<<v18-19-8,8>>^ Ele bloqueou o meu caminho, e não consigo passar; cobriu de trevas as minhas veredas.

[[v18-19-9]]

^<<v18-19-9,9>>^ Despiu-me da minha honra e tirou a coroa de minha cabeça.

[[v18-19-10]]

^<<v18-19-10,10>>^ Ele me arrasa por todos os lados, enquanto eu não me vou; desarraiga a minha esperança como se arranca uma planta.

[[v18-19-11]]

^<<v18-19-11,11>>^ Sua ira acendeu-se contra mim; ele me vê como inimigo.

[[v18-19-12]]

^<<v18-19-12,12>>^ Suas tropas avançam poderosamente; cercam-me e acampam ao redor da minha tenda.

[[v18-19-13]]

^<<v18-19-13,13>>^ "Ele afastou de mim os meus irmãos; até os meus conhecidos estão longe de mim.

[[v18-19-14]]

^<<v18-19-14,14>>^ Os meus parentes me abandonaram e os meus amigos esqueceram-se de mim.

[[v18-19-15]]

^<<v18-19-15,15>>^ Os meus hóspedes e as minhas servas consideram-me estrangeiro; vêem-me como um estranho.

[[v18-19-16]]

^<<v18-19-16,16>>^ Chamo o meu servo, mas ele não me responde, ainda que eu lhe implore pessoalmente.

[[v18-19-17]]

^<<v18-19-17,17>>^ Minha mulher acha repugnante o meu hálito; meus próprios irmãos têm nojo de mim.

[[v18-19-18]]

^<<v18-19-18,18>>^ Até os meninos zombam de mim, e dão risada quando apareço.

[[v18-19-19]]

^<<v18-19-19,19>>^ Todos os meus amigos chegados me detestam; aqueles a quem amo voltaram-se contra mim.

[[v18-19-20]]

^<<v18-19-20,20>>^ Não passo de pele e ossos; só escapei com a pele dos meus dentes.

[[v18-19-21]]

^<<v18-19-21,21>>^ "Misericórdia, meus amigos! Misericórdia! Pois a mão de Deus me feriu.

[[v18-19-22]]

^<<v18-19-22,22>>^ Por que vocês me perseguem como Deus o faz? Nunca vão saciar-se da minha carne?

[[v18-19-23]]

^<<v18-19-23,23>>^ "Quem dera as minhas palavras fossem registradas! Quem dera fossem escritas num livro,

[[v18-19-24]]

^<<v18-19-24,24>>^ fossem talhadas a ferro no chumbo, ou gravadas para sempre na rocha!

[[v18-19-25]]

^<<v18-19-25,25>>^ Eu sei que o meu Redentor vive, e que no fim se levantará sobre a terra.

[[v18-19-26]]

^<<v18-19-26,26>>^ E depois que o meu corpo estiver destruído e sem carne, verei a Deus.

[[v18-19-27]]

^<<v18-19-27,27>>^ Eu o verei, com os meus próprios olhos; eu mesmo, e não outro! Como anseia no meu peito o coração!

[[v18-19-28]]

^<<v18-19-28,28>>^ "Se vocês disserem: ‘Vejamos como vamos persegui-lo, pois a raiz do problema está nele’,

[[v18-19-29]]

^<<v18-19-29,29>>^ melhor será que temam a espada, porquanto por meio dela a ira lhes trará castigo, e então vocês saberão que há julgamento".

'''

xref:018-jo/018-jo-018.adoc#v18-18-0[&#60; Capítulo Anterior] | <<v18-19-0,Topo>> | xref:018-jo/018-jo-020.adoc#v18-20-0[Próximo Capítulo &#62;]