include::./index.adoc[]

[[v18-10-0]]
=== Jó, 10
// nvi ?, NVI - Nova Versão Internacional

[[v18-10-1]]

^<<v18-10-1,1>>^ "Minha vida só me dá desgosto; por isso darei vazão à minha queixa e de alma amargurada me expressarei.

[[v18-10-2]]

^<<v18-10-2,2>>^ Direi a Deus: Não me condenes, revela-me que acusações tens contra mim.

[[v18-10-3]]

^<<v18-10-3,3>>^ Tens prazer em oprimir-me, em rejeitar a obra de tuas mãos, enquanto sorris para o plano dos ímpios?

[[v18-10-4]]

^<<v18-10-4,4>>^ Acaso tens olhos de carne? Enxergas como os mortais?

[[v18-10-5]]

^<<v18-10-5,5>>^ Teus dias são como os de qualquer mortal? Os anos de tua vida são como os do homem?

[[v18-10-6]]

^<<v18-10-6,6>>^ Pois investigas a minha iniqüidade e vasculhas o meu pecado,

[[v18-10-7]]

^<<v18-10-7,7>>^ embora saibas que não sou culpado e que ninguém pode livrar-me das tuas mãos.

[[v18-10-8]]

^<<v18-10-8,8>>^ "Foram as tuas mãos que me formaram e me fizeram. Irás agora voltar-te e destruir-me?

[[v18-10-9]]

^<<v18-10-9,9>>^ Lembra-te de que me moldaste como o barro, e agora me farás voltar ao pó?

[[v18-10-10]]

^<<v18-10-10,10>>^ Acaso não me despejaste como leite e não me coalhaste como queijo?

[[v18-10-11]]

^<<v18-10-11,11>>^ Não me vestiste de pele e carne e não me juntaste com ossos e tendões?

[[v18-10-12]]

^<<v18-10-12,12>>^ Deste-me vida e foste bondoso para comigo, e na tua providência cuidaste do meu espírito.

[[v18-10-13]]

^<<v18-10-13,13>>^ "Mas algo escondeste em teu coração, e bem sei que és tu:

[[v18-10-14]]

^<<v18-10-14,14>>^ Se eu pecasse, me estarias observando e não deixarias sem punição a minha ofensa.

[[v18-10-15]]

^<<v18-10-15,15>>^ Se eu fosse culpado, ai de mim! Mesmo sendo inocente, não posso erguer a cabeça, pois estou dominado pela vergonha e mergulhado na minha aflição.

[[v18-10-16]]

^<<v18-10-16,16>>^ Se mantenho a cabeça erguida, ficas à minha espreita como um leão, e de novo manifestas contra mim o teu poder tremendo.

[[v18-10-17]]

^<<v18-10-17,17>>^ Trazes novas testemunhas contra mim e contra mim aumentas a tua ira; teus exércitos atacam-me, em batalhões sucessivos.

[[v18-10-18]]

^<<v18-10-18,18>>^ "Então, por que me fizeste sair do ventre? Eu preferia ter morrido antes que pudesse ser visto.

[[v18-10-19]]

^<<v18-10-19,19>>^ Se tão-somente eu jamais tivesse existido, ou fosse levado direto do ventre para a sepultura!

[[v18-10-20]]

^<<v18-10-20,20>>^ Já estariam no fim os meus poucos dias? Afasta-te de mim, para que eu tenha um instante de alegria,

[[v18-10-21]]

^<<v18-10-21,21>>^ antes que eu vá para o lugar do qual não há retorno, para a terra de sombras e densas trevas,

[[v18-10-22]]

^<<v18-10-22,22>>^ para a terra tenebrosa como a noite, terra de trevas e de caos, onde até mesmo a luz é trevas".

'''

xref:018-jo/018-jo-009.adoc#v18-9-0[&#60; Capítulo Anterior] | <<v18-10-0,Topo>> | xref:018-jo/018-jo-011.adoc#v18-11-0[Próximo Capítulo &#62;]