include::./index.adoc[]

[[v18-20-0]]
=== Jó, 20
// nvi ?, NVI - Nova Versão Internacional

[[v18-20-1]]

^<<v18-20-1,1>>^ Então Zofar, de Naamate, respondeu:

[[v18-20-2]]

^<<v18-20-2,2>>^ "Agitam-se os meus pensamentos e levam-me a responder porque estou profundamente perturbado.

[[v18-20-3]]

^<<v18-20-3,3>>^ Ouvi uma repreensão que me desonra, e o meu entendimento faz-me contestar.

[[v18-20-4]]

^<<v18-20-4,4>>^ "Certamente você sabe que sempre foi assim, desde a antigüidade; desde que o homem foi posto na terra,

[[v18-20-5]]

^<<v18-20-5,5>>^ o riso dos maus é passageiro, e a alegria dos ímpios dura apenas um instante.

[[v18-20-6]]

^<<v18-20-6,6>>^ Mesmo que o seu orgulho chegue aos céus e a sua cabeça toque as nuvens,

[[v18-20-7]]

^<<v18-20-7,7>>^ ele perecerá para sempre, como o seu próprio excremento; os que o tinham visto perguntarão: ‘Onde ele foi parar? ’

[[v18-20-8]]

^<<v18-20-8,8>>^ Ele voa e vai-se como um sonho, para nunca mais ser encontrado, banido como uma visão noturna.

[[v18-20-9]]

^<<v18-20-9,9>>^ O olho que o viu não o verá mais, nem o seu lugar o tornará a ver.

[[v18-20-10]]

^<<v18-20-10,10>>^ Seus filhos têm que indenizar os pobres; ele próprio, com suas mãos, terá que refazer sua riqueza.

[[v18-20-11]]

^<<v18-20-11,11>>^ O vigor juvenil que enche os seus ossos jazerá com ele no pó.

[[v18-20-12]]

^<<v18-20-12,12>>^ "Mesmo que o mal seja doce em sua boca e ele o esconda sob a língua,

[[v18-20-13]]

^<<v18-20-13,13>>^ mesmo que o retenha na boca para saboreá-lo,

[[v18-20-14]]

^<<v18-20-14,14>>^ ainda assim a sua comida azedará no estômago; e será como veneno de cobra em seu interior.

[[v18-20-15]]

^<<v18-20-15,15>>^ Ele vomitará as riquezas que engoliu; Deus fará seu estômago lançá-las fora.

[[v18-20-16]]

^<<v18-20-16,16>>^ Sugará veneno de cobra; as presas de uma víbora o matarão.

[[v18-20-17]]

^<<v18-20-17,17>>^ Não terá gosto na contemplação dos regatos, e dos rios que vertem mel e nata.

[[v18-20-18]]

^<<v18-20-18,18>>^ Terá que devolver aquilo pelo que lutou, sem aproveitá-lo, e não desfrutará dos lucros do seu comércio.

[[v18-20-19]]

^<<v18-20-19,19>>^ Sim, pois ele tem oprimido os pobres e os tem deixado desamparados; apoderou-se de casas que não construiu.

[[v18-20-20]]

^<<v18-20-20,20>>^ "Certo é que a sua cobiça não lhe trará descanso, e o seu tesouro não o salvará.

[[v18-20-21]]

^<<v18-20-21,21>>^ Nada lhe restou para devorar; sua prosperidade não durará muito.

[[v18-20-22]]

^<<v18-20-22,22>>^ Em meio à sua fartura, a aflição o dominará; a força total da desgraça o atingirá.

[[v18-20-23]]

^<<v18-20-23,23>>^ Quando ele estiver de estômago cheio, Deus dará vazão às tremendas chamas de sua ira, e sobre ele despejará o seu furor.

[[v18-20-24]]

^<<v18-20-24,24>>^ Se escapar da arma de ferro, o bronze da sua flecha o atravessará.

[[v18-20-25]]

^<<v18-20-25,25>>^ Ele o arrancará das suas costas, a ponta reluzente saindo do seu fígado. Grande pavor virá sobre ele;

[[v18-20-26]]

^<<v18-20-26,26>>^ densas trevas estarão à espera dos seus tesouros. Um fogo não assoprado o consumirá e devorará o que sobrar em sua tenda.

[[v18-20-27]]

^<<v18-20-27,27>>^ Os céus porão à mostra a sua culpa; a terra se levantará contra ele.

[[v18-20-28]]

^<<v18-20-28,28>>^ Uma inundação arrastará a sua casa, águas avassaladoras, no dia da ira de Deus.

[[v18-20-29]]

^<<v18-20-29,29>>^ Esse é o destino que Deus dá aos ímpios, é a herança designada por Deus para eles".

'''

xref:018-jo/018-jo-019.adoc#v18-19-0[&#60; Capítulo Anterior] | <<v18-20-0,Topo>> | xref:018-jo/018-jo-021.adoc#v18-21-0[Próximo Capítulo &#62;]