include::./index.adoc[]

[[v18-33-0]]
=== Jó, 33
// nvi ?, NVI - Nova Versão Internacional

[[v18-33-1]]

^<<v18-33-1,1>>^ "Mas agora, Jó, escute as minhas palavras; preste atenção a tudo o que vou dizer.

[[v18-33-2]]

^<<v18-33-2,2>>^ Estou prestes a abrir a boca; minhas palavras estão na ponta da língua.

[[v18-33-3]]

^<<v18-33-3,3>>^ Minhas palavras procedem de um coração íntegro; meus lábios falam com sinceridade o que eu sei.

[[v18-33-4]]

^<<v18-33-4,4>>^ O Espírito de Deus me fez; o sopro do Todo-poderoso me dá vida.

[[v18-33-5]]

^<<v18-33-5,5>>^ Responda-me, então, se puder; prepare-se para enfrentar-me.

[[v18-33-6]]

^<<v18-33-6,6>>^ Sou igual a você diante de Deus; eu também fui feito do barro.

[[v18-33-7]]

^<<v18-33-7,7>>^ Por isso não lhe devo inspirar temor, e a minha mão não há de ser pesada sobre você.

[[v18-33-8]]

^<<v18-33-8,8>>^ "Mas você disse ao meu alcance, eu ouvi bem as palavras:

[[v18-33-9]]

^<<v18-33-9,9>>^ ‘Estou limpo e sem pecado; estou puro e sem culpa.

[[v18-33-10]]

^<<v18-33-10,10>>^ Contudo, Deus procurou em mim motivos para inimizade; ele me considera seu inimigo.

[[v18-33-11]]

^<<v18-33-11,11>>^ Ele acorrenta os meus pés; vigia de perto todos os meus caminhos. ’

[[v18-33-12]]

^<<v18-33-12,12>>^ "Mas eu lhe digo que você não está certo, porquanto Deus é maior do que o homem.

[[v18-33-13]]

^<<v18-33-13,13>>^ Por que você se queixa a ele de que não responde às palavras dos homens?

[[v18-33-14]]

^<<v18-33-14,14>>^ Pois a verdade é que Deus fala, ora de um modo, ora de outro, mesmo que o homem não o perceba.

[[v18-33-15]]

^<<v18-33-15,15>>^ Em sonho ou em visão durante a noite, quando o sono profundo cai sobre os homens e eles dormem em suas camas,

[[v18-33-16]]

^<<v18-33-16,16>>^ ele pode falar aos ouvidos deles e aterrorizá-los com advertências

[[v18-33-17]]

^<<v18-33-17,17>>^ para previnir o homem das suas más ações e livrá-lo do orgulho,

[[v18-33-18]]

^<<v18-33-18,18>>^ para preservar da cova a sua alma, e a sua vida da espada.

[[v18-33-19]]

^<<v18-33-19,19>>^ Ou o homem pode ser castigado no leito de dor, com os seus ossos em constante agonia,

[[v18-33-20]]

^<<v18-33-20,20>>^ levando-o a achar a comida repulsiva e a detestar na alma sua refeição preferida.

[[v18-33-21]]

^<<v18-33-21,21>>^ Já não se vê sua carne, e seus ossos, que não se viam, agora aparecem.

[[v18-33-22]]

^<<v18-33-22,22>>^ Sua alma aproxima-se da cova, e sua vida, dos mensageiros da morte.

[[v18-33-23]]

^<<v18-33-23,23>>^ "Havendo, porém, um anjo ao seu lado, como mediador dentre mil, que diga ao homem o que é certo a seu respeito,

[[v18-33-24]]

^<<v18-33-24,24>>^ para ser-lhe favorável e dizer: ‘Poupa-o de descer à cova; encontrei resgate para ele’,

[[v18-33-25]]

^<<v18-33-25,25>>^ então sua carne se renova voltando a ser como de criança; ele se rejuvenece.

[[v18-33-26]]

^<<v18-33-26,26>>^ Ele ora a Deus e recebe o seu favor; vê o rosto de Deus e dá gritos de alegria, e Deus lhe restitui a condição de justo.

[[v18-33-27]]

^<<v18-33-27,27>>^ Depois ele vem aos homens e diz: ‘Pequei e torci o que era certo, mas ele não me deu o que eu merecia.

[[v18-33-28]]

^<<v18-33-28,28>>^ Ele resgatou a minha alma, impedindo-a de descer à cova, e viverei para desfrutar a luz’.

[[v18-33-29]]

^<<v18-33-29,29>>^ "Deus faz dessas coisas ao homem, duas ou três vezes,

[[v18-33-30]]

^<<v18-33-30,30>>^ para recuperar sua alma da cova, a fim de que refulja sobre ele a luz da vida.

[[v18-33-31]]

^<<v18-33-31,31>>^ "Preste atenção, Jó, e escute-me; fique em silêncio, e falarei.

[[v18-33-32]]

^<<v18-33-32,32>>^ Se você tem algo para dizer, responda-me; fale logo, pois quero que você seja absolvido.

[[v18-33-33]]

^<<v18-33-33,33>>^ Se não tem nada a dizer, ouça-me, fique em silêncio, e eu lhe ensinarei a sabedoria".

'''

xref:018-jo/018-jo-032.adoc#v18-32-0[&#60; Capítulo Anterior] | <<v18-33-0,Topo>> | xref:018-jo/018-jo-034.adoc#v18-34-0[Próximo Capítulo &#62;]