include::./index.adoc[]

[[v18-18-0]]
=== Jó, 18
// nvi ?, NVI - Nova Versão Internacional

[[v18-18-1]]

^<<v18-18-1,1>>^ Então Bildade, de Suá, respondeu:

[[v18-18-2]]

^<<v18-18-2,2>>^ "Quando você vai parar de falar? Proceda com sensatez, e depois poderemos conversar.

[[v18-18-3]]

^<<v18-18-3,3>>^ Por que somos considerados como animais, e somos ignorantes aos seus olhos?

[[v18-18-4]]

^<<v18-18-4,4>>^ Ah você, que se dilacera de ira! Deve-se abandonar a terra por sua causa? Ou devem as rochas mudar de lugar?

[[v18-18-5]]

^<<v18-18-5,5>>^ "A lâmpada do ímpio se apaga, e a chama do seu fogo se extingue.

[[v18-18-6]]

^<<v18-18-6,6>>^ Na sua tenda a luz se escurece; a lâmpada de sua vida se apaga.

[[v18-18-7]]

^<<v18-18-7,7>>^ O vigor dos seus passos se enfraquece, e os seus próprios planos lançam por terra.

[[v18-18-8]]

^<<v18-18-8,8>>^ Por seus próprios pés você se prende na rede, e se perde na sua malha.

[[v18-18-9]]

^<<v18-18-9,9>>^ A armadilha o pega pelo calcanhar; o laço o prende firme.

[[v18-18-10]]

^<<v18-18-10,10>>^ O nó corredio está escondido na terra para pegá-lo, há uma armadilha em seu caminho.

[[v18-18-11]]

^<<v18-18-11,11>>^ Terrores de todos os lados o assustam e o perseguem em todos os seus passos.

[[v18-18-12]]

^<<v18-18-12,12>>^ A calamidade tem fome para alcançá-la, e a desgraça está à espera de sua queda.

[[v18-18-13]]

^<<v18-18-13,13>>^ Ela consome partes da sua pele; o primogênito da morte devora os membros do seu corpo.

[[v18-18-14]]

^<<v18-18-14,14>>^ Ele é arrancado da segurança de sua tenda, e o levam à força ao rei dos terrores.

[[v18-18-15]]

^<<v18-18-15,15>>^ O fogo mora na tenda dele; espalham enxofre ardente sobre a sua habitação.

[[v18-18-16]]

^<<v18-18-16,16>>^ Suas raízes secam-se embaixo, e seus ramos murcham em cima.

[[v18-18-17]]

^<<v18-18-17,17>>^ Sua lembrança desaparece da terra, e nome não tem, em parte alguma.

[[v18-18-18]]

^<<v18-18-18,18>>^ É lançado da luz para as trevas; é banido do mundo.

[[v18-18-19]]

^<<v18-18-19,19>>^ Não tem filhos nem descendentes entre o seu povo, nem lhe restou sobrevivente algum nos lugares onde antes vivia.

[[v18-18-20]]

^<<v18-18-20,20>>^ Os homens do ocidente assustam-se com a sua ruína, e os do oriente enchem-se de pavor.

[[v18-18-21]]

^<<v18-18-21,21>>^ É assim a habitação do perverso; essa é a situação de quem não conhece a Deus".

'''

xref:018-jo/018-jo-017.adoc#v18-17-0[&#60; Capítulo Anterior] | <<v18-18-0,Topo>> | xref:018-jo/018-jo-019.adoc#v18-19-0[Próximo Capítulo &#62;]