include::./index.adoc[]

[[v18-9-0]]
=== Jó, 9
// nvi ?, NVI - Nova Versão Internacional

[[v18-9-1]]

^<<v18-9-1,1>>^ Então Jó respondeu:

[[v18-9-2]]

^<<v18-9-2,2>>^ "Bem sei que isso é verdade. Mas como pode o mortal ser justo diante de Deus?

[[v18-9-3]]

^<<v18-9-3,3>>^ Ainda que quisesse discutir com ele, não conseguiria argumentar nem uma vez em mil.

[[v18-9-4]]

^<<v18-9-4,4>>^ Sua sabedoria é profunda, seu poder é imenso. Quem tentou resisti-lo e saiu ileso?

[[v18-9-5]]

^<<v18-9-5,5>>^ Ele transporta montanhas sem que elas o saibam, e em sua ira as põe de cabeça para baixo.

[[v18-9-6]]

^<<v18-9-6,6>>^ Sacode a terra e a tira do lugar, e faz suas colunas tremerem.

[[v18-9-7]]

^<<v18-9-7,7>>^ Fala com o sol, e ele não brilha; ele veda e esconde a luz das estrelas.

[[v18-9-8]]

^<<v18-9-8,8>>^ Só ele estende os céus e anda sobre as ondas do mar.

[[v18-9-9]]

^<<v18-9-9,9>>^ Ele é o Criador da Ursa e do Órion, das Plêiades e das constelações do sul.

[[v18-9-10]]

^<<v18-9-10,10>>^ Realiza maravilhas que não se podem perscrutar, milagres incontáveis.

[[v18-9-11]]

^<<v18-9-11,11>>^ Quando passa por mim, não posso vê-lo; se passa junto de mim, não o percebo.

[[v18-9-12]]

^<<v18-9-12,12>>^ Se ele apanha algo, quem pode pará-lo? Quem pode dizer-lhe: ‘O que fazes? ’

[[v18-9-13]]

^<<v18-9-13,13>>^ Deus não refreia a sua ira; até o séquito de Raabe encolheu-se diante dos seus pés.

[[v18-9-14]]

^<<v18-9-14,14>>^ "Como então poderei eu discutir com ele? Como achar palavras para com ele argumentar?

[[v18-9-15]]

^<<v18-9-15,15>>^ Embora inocente, eu seria incapaz de responder-lhe; poderia apenas implorar misericórdia ao meu Juiz.

[[v18-9-16]]

^<<v18-9-16,16>>^ Mesmo que eu o chamasse e ele me respondesse, não creio que me daria ouvidos.

[[v18-9-17]]

^<<v18-9-17,17>>^ Ele me esmagaria com uma tempestade e sem motivo multiplicaria minhas feridas.

[[v18-9-18]]

^<<v18-9-18,18>>^ Não me permitiria recuperar o fôlego, mas me engolfaria em agruras.

[[v18-9-19]]

^<<v18-9-19,19>>^ Se é questão de força, ele é poderoso! E se é questão de justiça, quem o intimará?

[[v18-9-20]]

^<<v18-9-20,20>>^ Mesmo sendo eu inocente, minha boca me condenaria; se eu fosse íntegro, ela me declararia culpado.

[[v18-9-21]]

^<<v18-9-21,21>>^ "Conquanto eu seja íntegro, já não me importo comigo; desprezo a minha própria vida.

[[v18-9-22]]

^<<v18-9-22,22>>^ É tudo a mesma coisa; por isso digo: Ele destrói tanto o íntegro como o ímpio.

[[v18-9-23]]

^<<v18-9-23,23>>^ Quando um flagelo causa morte repentina, ele zomba do desespero dos inocentes.

[[v18-9-24]]

^<<v18-9-24,24>>^ Quando um país cai nas mãos dos ímpios, ele venda os olhos de seus juízes. Se não é ele, quem é então? "

[[v18-9-25]]

^<<v18-9-25,25>>^ "Meus dias correm mais velozes que um atleta; eles voam sem um vislumbre de alegria.

[[v18-9-26]]

^<<v18-9-26,26>>^ Passam como barcos de papiro, como águias que mergulham sobre as presas.

[[v18-9-27]]

^<<v18-9-27,27>>^ Se eu disser: Vou esquecer a minha queixa, vou mudar o meu semblante e sorrir,

[[v18-9-28]]

^<<v18-9-28,28>>^ ainda assim me apavoro com todos os meus sofrimentos, pois sei que não me considerarás inocente.

[[v18-9-29]]

^<<v18-9-29,29>>^ Uma vez que já fui considerado culpado, por que deveria eu lutar em vão?

[[v18-9-30]]

^<<v18-9-30,30>>^ Mesmo que eu me lavasse com sabão e limpasse as minhas mãos com soda de lavadeira,

[[v18-9-31]]

^<<v18-9-31,31>>^ tu me atirarias num poço de lodo, para que até as minhas roupas me detestassem.

[[v18-9-32]]

^<<v18-9-32,32>>^ "Ele não é homem como eu, para que eu lhe responda, e nos enfrentemos em juízo.

[[v18-9-33]]

^<<v18-9-33,33>>^ Se tão-somente houvesse alguém para servir de árbitro entre nós, para impor as mãos sobre nós dois,

[[v18-9-34]]

^<<v18-9-34,34>>^ alguém que afastasse de mim a vara de Deus, para que o seu terror não mais me assustasse!

[[v18-9-35]]

^<<v18-9-35,35>>^ Então eu falaria sem medo; mas não é esse o caso.

'''

xref:018-jo/018-jo-008.adoc#v18-8-0[&#60; Capítulo Anterior] | <<v18-9-0,Topo>> | xref:018-jo/018-jo-010.adoc#v18-10-0[Próximo Capítulo &#62;]