include::./index.adoc[]

[[v18-5-0]]
=== Jó, 5
// nvi ?, NVI - Nova Versão Internacional

[[v18-5-1]]

^<<v18-5-1,1>>^ "Clame, se quiser, mas quem o ouvirá? Para qual dos seres celestes você se voltará?

[[v18-5-2]]

^<<v18-5-2,2>>^ O ressentimento mata o insensato, e a inveja destrói o tolo.

[[v18-5-3]]

^<<v18-5-3,3>>^ Eu mesmo já vi um insensato lançar raízes, mas de repente a sua casa foi amaldiçoada.

[[v18-5-4]]

^<<v18-5-4,4>>^ Seus filhos longe estão de desfrutar segurança, maltratados nos tribunais, não há quem os defenda.

[[v18-5-5]]

^<<v18-5-5,5>>^ Os famintos devoram a sua colheita, tirando-a até do meio dos espinhos, e os sedentos sugam a sua riqueza.

[[v18-5-6]]

^<<v18-5-6,6>>^ Pois o sofrimento não brota do pó, e as dificuldades não nascem do chão.

[[v18-5-7]]

^<<v18-5-7,7>>^ No entanto o homem nasce para as dificuldades tão certamente como as fagulhas voam para cima.

[[v18-5-8]]

^<<v18-5-8,8>>^ "Mas, se fosse comigo, eu apelaria para Deus; apresentaria a ele a minha causa.

[[v18-5-9]]

^<<v18-5-9,9>>^ Ele realiza maravilhas insondáveis, milagres que não se pode contar.

[[v18-5-10]]

^<<v18-5-10,10>>^ Derrama chuva sobre a terra, e envia água sobre os campos.

[[v18-5-11]]

^<<v18-5-11,11>>^ Os humildes, ele os exalta, e traz os que pranteiam a um lugar de segurança.

[[v18-5-12]]

^<<v18-5-12,12>>^ Ele frustra os planos dos astutos, para que fracassem as mãos deles.

[[v18-5-13]]

^<<v18-5-13,13>>^ Apanha os sábios na astúcia deles, e as maquinações dos astutos são malogradas por sua precipitação.

[[v18-5-14]]

^<<v18-5-14,14>>^ As trevas vêm sobre eles em pleno dia; ao meio-dia eles tateiam como se fosse noite.

[[v18-5-15]]

^<<v18-5-15,15>>^ Ele salva o oprimido da espada que trazem na boca; salva-o das garras dos poderosos.

[[v18-5-16]]

^<<v18-5-16,16>>^ Por isso os pobres têm esperança, e a injustiça cala a boca.

[[v18-5-17]]

^<<v18-5-17,17>>^ "Como é feliz o homem a quem Deus corrige; portanto, não despreze a disciplina do Todo-poderoso.

[[v18-5-18]]

^<<v18-5-18,18>>^ Pois ele fere, mas dela vem tratar; ele machuca, mas suas mãos também curam.

[[v18-5-19]]

^<<v18-5-19,19>>^ De seis desgraças ele o livrará; em sete delas você nada sofrerá.

[[v18-5-20]]

^<<v18-5-20,20>>^ Na fome ele o livrará da morte, e na guerra o livrará do golpe da espada.

[[v18-5-21]]

^<<v18-5-21,21>>^ Você será protegido do açoite da língua, e não precisará ter medo quando a destruição chegar.

[[v18-5-22]]

^<<v18-5-22,22>>^ Você rirá da destruição e da fome, e não precisará temer as feras da terra.

[[v18-5-23]]

^<<v18-5-23,23>>^ Pois fará aliança com as pedras do campo, e os animais selvagens estarão em paz com você.

[[v18-5-24]]

^<<v18-5-24,24>>^ Você saberá que a sua tenda é segura; contará os seus bens da tua morada e de nada achará falta.

[[v18-5-25]]

^<<v18-5-25,25>>^ Você saberá que os seus filhos serão muitos, e que os seus descendentes serão como a relva da terra.

[[v18-5-26]]

^<<v18-5-26,26>>^ Você irá para a sepultura em pleno vigor, como um feixe recolhido no devido tempo.

[[v18-5-27]]

^<<v18-5-27,27>>^ "Foi isso que verificamos ser verdade. Portanto, ouça e aplique isso à sua vida".

'''

xref:018-jo/018-jo-004.adoc#v18-4-0[&#60; Capítulo Anterior] | <<v18-5-0,Topo>> | xref:018-jo/018-jo-006.adoc#v18-6-0[Próximo Capítulo &#62;]