include::./index.adoc[]

[[v18-28-0]]
=== Jó, 28
// nvi ?, NVI - Nova Versão Internacional

[[v18-28-1]]

^<<v18-28-1,1>>^ "Existem minas de prata e locais onde se refina ouro.

[[v18-28-2]]

^<<v18-28-2,2>>^ O ferro é extraído da terra, e do minério se funde o cobre.

[[v18-28-3]]

^<<v18-28-3,3>>^ O homem dá fim à escuridão; e vasculha os recônditos mais remotos em busca de minério, nas mais escuras trevas.

[[v18-28-4]]

^<<v18-28-4,4>>^ Longe das moradias ele cava um poço, em local esquecido pelos pés dos homens; longe de todos, ele se pendura e balança.

[[v18-28-5]]

^<<v18-28-5,5>>^ A terra, da qual vem o alimento, é revolvida embaixo como que pelo fogo;

[[v18-28-6]]

^<<v18-28-6,6>>^ das suas rochas saem safiras, e seu pó contém pepitas de ouro.

[[v18-28-7]]

^<<v18-28-7,7>>^ Nenhuma ave de rapina conhece aquele caminho oculto, e os olhos de nenhum falcão o viram.

[[v18-28-8]]

^<<v18-28-8,8>>^ Os animais altivos não põem os pés nele, e nenhum leão ronda por ali.

[[v18-28-9]]

^<<v18-28-9,9>>^ As mãos dos homens atacam a pederneira e transtornam as raízes das montanhas.

[[v18-28-10]]

^<<v18-28-10,10>>^ Fazem túneis através da rocha, e os seus olhos enxergam todos os tesouros dali.

[[v18-28-11]]

^<<v18-28-11,11>>^ Eles vasculham as nascentes dos rios e trazem à luz coisas ocultas.

[[v18-28-12]]

^<<v18-28-12,12>>^ "Onde, porém, se poderá achar a sabedoria? Onde habita o entendimento?

[[v18-28-13]]

^<<v18-28-13,13>>^ O homem não percebe o valor da sabedoria; ela não se encontra na terra dos viventes.

[[v18-28-14]]

^<<v18-28-14,14>>^ O abismo diz: ‘Em mim não está’; o mar diz: ‘Não está comigo’.

[[v18-28-15]]

^<<v18-28-15,15>>^ Não pode ser comprada, mesmo com o ouro mais puro, nem se pode pesar o seu preço em prata.

[[v18-28-16]]

^<<v18-28-16,16>>^ Não pode ser comprada nem com o ouro puro de Ofir, nem com o precioso ônix ou com safiras.

[[v18-28-17]]

^<<v18-28-17,17>>^ O ouro e o cristal não se comparam com ela, e é impossível tê-la em troca de jóias de ouro.

[[v18-28-18]]

^<<v18-28-18,18>>^ O coral e o jaspe nem merecem menção; o preço da sabedoria ultrapassa o dos rubis.

[[v18-28-19]]

^<<v18-28-19,19>>^ O topázio da Etiópia não se compara com ela; não se compra a sabedoria nem com ouro puro!

[[v18-28-20]]

^<<v18-28-20,20>>^ "De onde vem, então, a sabedoria? Onde habita o entendimento?

[[v18-28-21]]

^<<v18-28-21,21>>^ Escondida está dos olhos de toda criatura viva, até das aves dos céus.

[[v18-28-22]]

^<<v18-28-22,22>>^ A Destruição e a Morte dizem: ‘Aos nossos ouvidos só chegou um leve rumor dela’.

[[v18-28-23]]

^<<v18-28-23,23>>^ Deus conhece o caminho; só ele sabe onde ela habita,

[[v18-28-24]]

^<<v18-28-24,24>>^ pois ele enxerga os confins da terra e vê tudo o que há debaixo dos céus.

[[v18-28-25]]

^<<v18-28-25,25>>^ Quando ele determinou a força do vento e estabeleceu a medida exata para as águas,

[[v18-28-26]]

^<<v18-28-26,26>>^ quando fez um decreto para a chuva e o caminho para a tempestade trovejante,

[[v18-28-27]]

^<<v18-28-27,27>>^ ele olhou para a sabedoria e a avaliou; confirmou-a e a pôs à prova.

[[v18-28-28]]

^<<v18-28-28,28>>^ Disse então ao homem: ‘No temor do Senhor está a sabedoria, e evitar o mal é ter entendimento’ ".

'''

xref:018-jo/018-jo-027.adoc#v18-27-0[&#60; Capítulo Anterior] | <<v18-28-0,Topo>> | xref:018-jo/018-jo-029.adoc#v18-29-0[Próximo Capítulo &#62;]