include::./index.adoc[]

[[v18-2-0]]
=== Jó, 2
// nvi ?, NVI - Nova Versão Internacional

[[v18-2-1]]

^<<v18-2-1,1>>^ Num outro dia os anjos vieram apresentar-se ao Senhor, e Satanás também veio com eles para apresentar-se.

[[v18-2-2]]

^<<v18-2-2,2>>^ E o Senhor disse a Satanás, "De onde você vem? " Satanás respondeu ao Senhor: "De perambular pela terra e andar por ela".

[[v18-2-3]]

^<<v18-2-3,3>>^ Disse então o Senhor a Satanás: "Reparou em meu servo Jó? Não há ninguém na terra como ele, irrepreensível, íntegro, homem que teme a Deus e evita o mal. Ele se mantém íntegro, apesar de você me haver instigado contra ele para arruiná-lo sem motivo".

[[v18-2-4]]

^<<v18-2-4,4>>^ "Pele por pele! ", respondeu Satanás. "Um homem dará tudo o que tem por sua vida.

[[v18-2-5]]

^<<v18-2-5,5>>^ Estende a tua mão e fere a sua carne e os seus ossos, e com certeza ele te amaldiçoará na tua face. "

[[v18-2-6]]

^<<v18-2-6,6>>^ O Senhor disse a Satanás: "Pois bem, ele está nas suas mãos; apenas poupe a vida dele".

[[v18-2-7]]

^<<v18-2-7,7>>^ Saiu, pois, Satanás da presença do Senhor e afligiu Jó com feridas terríveis, da sola dos pés ao alto da cabeça.

[[v18-2-8]]

^<<v18-2-8,8>>^ Então Jó apanhou um caco de louça com o qual se raspava, sentado entre as cinzas.

[[v18-2-9]]

^<<v18-2-9,9>>^ Então sua mulher lhe disse: "Você ainda mantém a sua integridade? Amaldiçoe a Deus, e morra! "

[[v18-2-10]]

^<<v18-2-10,10>>^ Ele respondeu: "Você fala como uma insensata. Aceitaremos o bem dado por Deus, e não o mal? " Em tudo isso Jó não pecou com os lábios.

[[v18-2-11]]

^<<v18-2-11,11>>^ Quando três amigos de Jó, Elifaz, de Temã, Bildade, de Suá, e Zofar, de Naamate, souberam de todos os males que o haviam atingido, saíram, cada um da sua região, e combinaram encontrar-se para mostrar solidariedade a Jó e consolá-lo.

[[v18-2-12]]

^<<v18-2-12,12>>^ Quando o viram à distância, mal puderam reconhecê-lo e começaram a chorar em alta voz. Cada um deles rasgou o manto e colocou terra sobre a cabeça.

[[v18-2-13]]

^<<v18-2-13,13>>^ Depois se assentaram no chão com ele, durante sete dias e sete noites. Ninguém lhe disse uma palavra, pois viam como era grande o seu sofrimento.

'''

xref:018-jo/018-jo-001.adoc#v18-1-0[&#60; Capítulo Anterior] | <<v18-2-0,Topo>> | xref:018-jo/018-jo-003.adoc#v18-3-0[Próximo Capítulo &#62;]