include::./index.adoc[]

[[v18-32-0]]
=== Jó, 32
// nvi ?, NVI - Nova Versão Internacional

[[v18-32-1]]

^<<v18-32-1,1>>^ Então esses três homens pararam de responder a Jó, pois este se julgava justo.

[[v18-32-2]]

^<<v18-32-2,2>>^ Mas Eliú, filho de Baraquel, de Buz, da família de Rão, indignou-se muito contra Jó, porque este se justificava a si mesmo diante de Deus.

[[v18-32-3]]

^<<v18-32-3,3>>^ Também se indignou contra os três amigos, pois não encontraram meios de refutar a Jó, e mesmo assim o tinham condenado.

[[v18-32-4]]

^<<v18-32-4,4>>^ Eliú tinha ficado esperando para falar a Jó, porque eles eram mais velhos que ele.

[[v18-32-5]]

^<<v18-32-5,5>>^ Mas, quando viu que os três não tinham mais nada a dizer, indignou-se.

[[v18-32-6]]

^<<v18-32-6,6>>^ Então Eliú, filho de Baraquel, de Buz, falou: "Eu sou jovem, vocês têm idade. Por isso tive receio e não ousei dizer-lhes o que sei.

[[v18-32-7]]

^<<v18-32-7,7>>^ Os que têm idade é que devem falar, pensava eu, os anos avançados é que devem ensinar sabedoria.

[[v18-32-8]]

^<<v18-32-8,8>>^ Mas é o espírito dentro do homem que lhe dá entendimento, o sopro do Todo-poderoso.

[[v18-32-9]]

^<<v18-32-9,9>>^ Não são só os mais velhos, os sábios, não são só os de idade que entendem o que é certo.

[[v18-32-10]]

^<<v18-32-10,10>>^ "Por isso digo: Escutem-me; também vou dizer o que sei.

[[v18-32-11]]

^<<v18-32-11,11>>^ Enquanto vocês estavam falando, esperei; fiquei ouvindo os seus arrazoados; enquanto vocês estavam procurando palavras,

[[v18-32-12]]

^<<v18-32-12,12>>^ dei-lhes total atenção. Mas não é que nenhum de vocês demonstrou que Jó está errado? Nenhum de vocês respondeu aos seus argumentos.

[[v18-32-13]]

^<<v18-32-13,13>>^ Não digam: ‘Encontramos a sabedoria; que Deus o refute, não o homem’.

[[v18-32-14]]

^<<v18-32-14,14>>^ Só que não foi contra mim que Jó dirigiu as suas palavras, e não vou responder a ele com os argumentos de vocês.

[[v18-32-15]]

^<<v18-32-15,15>>^ "Vejam eles estão consternados e não têm mais o que dizer; as palavras lhes fugiram.

[[v18-32-16]]

^<<v18-32-16,16>>^ Devo aguardar, agora que estão calados e sem resposta?

[[v18-32-17]]

^<<v18-32-17,17>>^ Também vou dar a minha opinião, também vou dizer o que sei,

[[v18-32-18]]

^<<v18-32-18,18>>^ pois não me faltam palavras, e dentro de mim o espírito me impulsiona.

[[v18-32-19]]

^<<v18-32-19,19>>^ Por dentro estou como vinho arrolhado, como vasilhas de couro novas prestes a romper.

[[v18-32-20]]

^<<v18-32-20,20>>^ Tenho que falar. Isso me aliviará. Tenho que abrir os lábios e responder.

[[v18-32-21]]

^<<v18-32-21,21>>^ Não serei parcial com ninguém, e a ninguém bajularei,

[[v18-32-22]]

^<<v18-32-22,22>>^ porque não sou bom em bajular; se fosse, o meu Criador em breve me levaria.

'''

xref:018-jo/018-jo-031.adoc#v18-31-0[&#60; Capítulo Anterior] | <<v18-32-0,Topo>> | xref:018-jo/018-jo-033.adoc#v18-33-0[Próximo Capítulo &#62;]