include::./index.adoc[]

[[v18-30-0]]
=== Jó, 30
// nvi ?, NVI - Nova Versão Internacional

[[v18-30-1]]

^<<v18-30-1,1>>^ "Mas agora eles zombam de mim, homens mais jovens que eu, homens cujos pais eu teria rejeitado, não lhes permitindo sequer estar com os cães de guarda do rebanho.

[[v18-30-2]]

^<<v18-30-2,2>>^ De que me serviria a força de suas mãos, já que desapareceu o seu vigor?

[[v18-30-3]]

^<<v18-30-3,3>>^ Desfigurados de tanta necessidade e fome, perambulavam pela terra ressequida, em sombrios e devastados desertos.

[[v18-30-4]]

^<<v18-30-4,4>>^ Nos campos de mato rasteiro colhiam ervas, e a raiz da giesta era a sua comida.

[[v18-30-5]]

^<<v18-30-5,5>>^ Da companhia dos amigos foram expulsos aos gritos, como se fossem ladrões.

[[v18-30-6]]

^<<v18-30-6,6>>^ Foram forçados a morar nos leitos secos dos rios, entre as rochas e nos buracos da terra.

[[v18-30-7]]

^<<v18-30-7,7>>^ Rugiam entre os arbustos e se encolhiam sob a vegetação.

[[v18-30-8]]

^<<v18-30-8,8>>^ Prole desprezível e sem nome, foram expulsos da terra.

[[v18-30-9]]

^<<v18-30-9,9>>^ "E agora os filhos deles zombam de mim com suas canções; tornei-me um provérbio entre eles.

[[v18-30-10]]

^<<v18-30-10,10>>^ Eles me detestam e se mantêm à distância; não hesitam em cuspir em meu rosto.

[[v18-30-11]]

^<<v18-30-11,11>>^ Agora que Deus afrouxou a corda do meu arco e me afligiu, eles ficam sem freios na minha presença.

[[v18-30-12]]

^<<v18-30-12,12>>^ À direita os embrutecidos me atacam; preparam armadilhas para os meus pés, e constroem rampas de cerco contra mim.

[[v18-30-13]]

^<<v18-30-13,13>>^ Destroem o meu caminho; conseguem destruir-me, sem a ajuda de ninguém.

[[v18-30-14]]

^<<v18-30-14,14>>^ Avançam como através de uma grande brecha; arrojam-se entre as ruínas.

[[v18-30-15]]

^<<v18-30-15,15>>^ Pavores apoderam-se de mim; a minha dignidade é levada como pelo vento, a minha segurança se desfaz como nuvem.

[[v18-30-16]]

^<<v18-30-16,16>>^ "E agora esvai-se a minha vida; estou preso a dias de sofrimento.

[[v18-30-17]]

^<<v18-30-17,17>>^ A noite penetra os meus ossos; minhas dores me corroem sem cessar.

[[v18-30-18]]

^<<v18-30-18,18>>^ Em seu grande poder Deus é como a minha roupa; ele me envolve como a gola da minha veste.

[[v18-30-19]]

^<<v18-30-19,19>>^ Lança-me na lama, e sou reduzido a pó e cinza.

[[v18-30-20]]

^<<v18-30-20,20>>^ "Clamo a ti, ó Deus, mas não respondes; fico de pé, mas apenas olhas para mim.

[[v18-30-21]]

^<<v18-30-21,21>>^ Contra mim te voltas com dureza e me atacas com a força de tua mão.

[[v18-30-22]]

^<<v18-30-22,22>>^ Tu me apanhas e me levas contra o vento, e me jogas de um lado a outro na tempestade.

[[v18-30-23]]

^<<v18-30-23,23>>^ Sei que me farás descer até a morte, ao lugar destinado a todos os viventes.

[[v18-30-24]]

^<<v18-30-24,24>>^ "A verdade é que ninguém dá a mão ao homem arruinado, quando este, em sua aflição, grita por socorro.

[[v18-30-25]]

^<<v18-30-25,25>>^ Não é certo que chorei por causa dos que passavam dificuldade? E que a minha alma entristeceu-se por causa dos pobres?

[[v18-30-26]]

^<<v18-30-26,26>>^ Mesmo assim, quando eu esperava o bem, veio o mal; quando eu procurava luz, vieram trevas.

[[v18-30-27]]

^<<v18-30-27,27>>^ Nunca pára a agitação dentro de mim; dias de sofrimento me confrontam.

[[v18-30-28]]

^<<v18-30-28,28>>^ Perambulo escurecido, mas não pelo sol; levanto-me na assembléia e clamo por ajuda.

[[v18-30-29]]

^<<v18-30-29,29>>^ Tornei-me irmão dos chacais, companheiro das corujas.

[[v18-30-30]]

^<<v18-30-30,30>>^ Minha pele escurece e cai; meu corpo queima de febre.

[[v18-30-31]]

^<<v18-30-31,31>>^ Minha harpa está afinada para cantos fúnebres, e minha flauta para o som de pranto.

'''

xref:018-jo/018-jo-029.adoc#v18-29-0[&#60; Capítulo Anterior] | <<v18-30-0,Topo>> | xref:018-jo/018-jo-031.adoc#v18-31-0[Próximo Capítulo &#62;]