include::./index.adoc[]

[[v18-40-0]]
=== Jó, 40
// nvi ?, NVI - Nova Versão Internacional

[[v18-40-1]]

^<<v18-40-1,1>>^ O Senhor disse a Jó:

[[v18-40-2]]

^<<v18-40-2,2>>^ "Aquele que contende com o Todo-poderoso poderá repreendê-lo? Que responda a Deus aquele que o acusa! "

[[v18-40-3]]

^<<v18-40-3,3>>^ Então Jó respondeu ao Senhor:

[[v18-40-4]]

^<<v18-40-4,4>>^ "Sou indigno; como posso responder-te? Ponho a mão sobre a minha boca.

[[v18-40-5]]

^<<v18-40-5,5>>^ Falei uma vez, mas não tenho resposta; sim, duas vezes, mas não direi mais nada".

[[v18-40-6]]

^<<v18-40-6,6>>^ Depois, o Senhor falou a Jó do meio da tempestade:

[[v18-40-7]]

^<<v18-40-7,7>>^ "Prepare-se como simples homem que é; eu lhe farei perguntas, e você me responderá.

[[v18-40-8]]

^<<v18-40-8,8>>^ "Você vai pôr em dúvida a minha justiça? Vai condenar-me para justificar-se?

[[v18-40-9]]

^<<v18-40-9,9>>^ Seu braço é como o de Deus, e sua voz pode trovejar como a dele?

[[v18-40-10]]

^<<v18-40-10,10>>^ Adorne-se, então, de esplendor e glória, e vista-se de majestade e honra.

[[v18-40-11]]

^<<v18-40-11,11>>^ Derrame a fúria da sua ira, olhe para todo orgulhoso e lance-o por terra,

[[v18-40-12]]

^<<v18-40-12,12>>^ olhe para todo orgulhoso e humilhe-o, esmague os ímpios onde estiverem.

[[v18-40-13]]

^<<v18-40-13,13>>^ Enterre-os todos juntos no pó; encubra os rostos deles no túmulo.

[[v18-40-14]]

^<<v18-40-14,14>>^ Então admitirei que a sua mão direita pode salvar você.

[[v18-40-15]]

^<<v18-40-15,15>>^ "Veja o Beemote que criei quando criei você e que come de capim como o boi.

[[v18-40-16]]

^<<v18-40-16,16>>^ Que força ele tem em seus lombos! Que poder nos músculos do seu ventre!

[[v18-40-17]]

^<<v18-40-17,17>>^ A cauda dele balança como o cedro; os nervos de suas coxas são firmemente entrelaçados.

[[v18-40-18]]

^<<v18-40-18,18>>^ Seus ossos são canos de bronze, seus membros são varas de ferro.

[[v18-40-19]]

^<<v18-40-19,19>>^ Ele ocupa o primeiro lugar entre as obras de Deus. No entanto, o seu Criador pode chegar a ele com sua espada.

[[v18-40-20]]

^<<v18-40-20,20>>^ Os montes lhe oferecem os seus produtos, e todos os animais selvagens brincam por perto.

[[v18-40-21]]

^<<v18-40-21,21>>^ Sob os lotos se deita, oculto entre os juncos do brejo.

[[v18-40-22]]

^<<v18-40-22,22>>^ Os lotos o escondem à sua sombra; os salgueiros junto ao regato o cercam.

[[v18-40-23]]

^<<v18-40-23,23>>^ Quando o rio se enfurece, ele não se abala; mesmo que o Jordão encrespe as ondas contra a sua boca, ele se mantém calmo.

[[v18-40-24]]

^<<v18-40-24,24>>^ Poderá alguém capturá-lo pelos olhos, ou prendê-lo em armadilha e enganchá-lo pelo nariz?

'''

xref:018-jo/018-jo-039.adoc#v18-39-0[&#60; Capítulo Anterior] | <<v18-40-0,Topo>> | xref:018-jo/018-jo-041.adoc#v18-41-0[Próximo Capítulo &#62;]