include::./index.adoc[]

[[v18-27-0]]
=== Jó, 27
// nvi ?, NVI - Nova Versão Internacional

[[v18-27-1]]

^<<v18-27-1,1>>^ E Jó prosseguiu em seu discurso:

[[v18-27-2]]

^<<v18-27-2,2>>^ "Pelo Deus vivo, que me negou justiça, pelo Todo-poderoso, que deu amargura à minha alma,

[[v18-27-3]]

^<<v18-27-3,3>>^ enquanto eu tiver vida em mim, o sopro de Deus em minhas narinas,

[[v18-27-4]]

^<<v18-27-4,4>>^ meus lábios não falarão maldade, e minha língua não proferirá nada que seja falso.

[[v18-27-5]]

^<<v18-27-5,5>>^ Nunca darei razão a vocês! Minha integridade não negarei jamais, até à morte.

[[v18-27-6]]

^<<v18-27-6,6>>^ Manterei minha retidão, e nunca a deixarei; enquanto eu viver, a minha consciência não me repreenderá.

[[v18-27-7]]

^<<v18-27-7,7>>^ "Sejam os meus inimigos como os ímpios, e os meus adversários como os injustos!

[[v18-27-8]]

^<<v18-27-8,8>>^ Pois, qual é a esperança do ímpio, quando é eliminado, quando Deus lhe tira a vida?

[[v18-27-9]]

^<<v18-27-9,9>>^ Ouvirá Deus o seu clamor, quando vier sobre ele a aflição?

[[v18-27-10]]

^<<v18-27-10,10>>^ Terá ele prazer no Todo-poderoso? Chamará a Deus a cada instante?

[[v18-27-11]]

^<<v18-27-11,11>>^ "Eu os ensinarei sobre o poder de Deus; não esconderei de vocês os caminhos do Todo-poderoso.

[[v18-27-12]]

^<<v18-27-12,12>>^ Pois a verdade é que todos vocês já viram isso. Por que então essa conversa sem sentido?

[[v18-27-13]]

^<<v18-27-13,13>>^ "Este é o destino que Deus determinou para o ímpio, a herança que o mau recebe do Todo-poderoso:

[[v18-27-14]]

^<<v18-27-14,14>>^ Por mais filhos que tenha, o destino deles é a espada; sua prole jamais terá comida suficiente.

[[v18-27-15]]

^<<v18-27-15,15>>^ A epidemia sepultará aqueles que lhe sobreviverem, e as suas viúvas não chorarão por eles.

[[v18-27-16]]

^<<v18-27-16,16>>^ Ainda que ele acumule prata como pó e roupas como barro, amontoe;

[[v18-27-17]]

^<<v18-27-17,17>>^ o que ele armazenar ficará para os justos, e os inocentes dividirão sua prata.

[[v18-27-18]]

^<<v18-27-18,18>>^ A casa que ele constrói é como casulo de traça, como cabana feita pela sentinela.

[[v18-27-19]]

^<<v18-27-19,19>>^ Rico ele se deita, mas nunca mais será! Quando abre os olhos, tudo se foi.

[[v18-27-20]]

^<<v18-27-20,20>>^ Pavores vêm sobre ele como uma enchente; de noite a tempestade o leva de roldão.

[[v18-27-21]]

^<<v18-27-21,21>>^ O vento oriental o leva, e ele desaparece; arranca-o do seu lugar.

[[v18-27-22]]

^<<v18-27-22,22>>^ Atira-se contra ele sem piedade, enquanto ele foge às pressas do seu poder.

[[v18-27-23]]

^<<v18-27-23,23>>^ Bate palmas contra ele e com assobios o expele do seu lugar.

'''

xref:018-jo/018-jo-026.adoc#v18-26-0[&#60; Capítulo Anterior] | <<v18-27-0,Topo>> | xref:018-jo/018-jo-028.adoc#v18-28-0[Próximo Capítulo &#62;]