include::./index.adoc[]

[[v18-23-0]]
=== Jó, 23
// nvi ?, NVI - Nova Versão Internacional

[[v18-23-1]]

^<<v18-23-1,1>>^ Então Jó respondeu:

[[v18-23-2]]

^<<v18-23-2,2>>^ "Até agora me queixo com amargura; a mão dele é pesada, a despeito de meu gemido.

[[v18-23-3]]

^<<v18-23-3,3>>^ Se tão-somente eu soubesse onde encontrá-lo e ir à sua habitação!

[[v18-23-4]]

^<<v18-23-4,4>>^ Eu lhe apresentaria a minha causa e encheria a minha boca de argumentos.

[[v18-23-5]]

^<<v18-23-5,5>>^ Estudaria o que ele me respondesse e analisaria o que me dissesse.

[[v18-23-6]]

^<<v18-23-6,6>>^ Será que ele se oporia a mim com grande poder? Não, ele não me faria acusações.

[[v18-23-7]]

^<<v18-23-7,7>>^ O homem íntegro poderia apresentar-lhe sua causa; eu seria liberto para sempre de quem me julga.

[[v18-23-8]]

^<<v18-23-8,8>>^ "Mas, se vou para o oriente, lá ele não está; se vou para o ocidente, não o encontro.

[[v18-23-9]]

^<<v18-23-9,9>>^ Quando ele está em ação no norte, não o enxergo; quando vai para o sul, nem sombra dele eu vejo!

[[v18-23-10]]

^<<v18-23-10,10>>^ Mas ele conhece o caminho por onde ando; se me puser à prova, aparecerei como o ouro.

[[v18-23-11]]

^<<v18-23-11,11>>^ Meus pés seguiram de perto as suas pegadas; mantive-me no seu caminho, sem desviar-me.

[[v18-23-12]]

^<<v18-23-12,12>>^ Não me afastei dos mandamentos dos seus lábios; dei mais valor às palavras de sua boca, do que ao meu pão de cada dia.

[[v18-23-13]]

^<<v18-23-13,13>>^ "Mas ele é ele! Quem poderá fazer-lhe oposição? Ele faz o que quer.

[[v18-23-14]]

^<<v18-23-14,14>>^ Executa o seu decreto contra mim, e tem muitos outros semelhantes.

[[v18-23-15]]

^<<v18-23-15,15>>^ Por isso fico apavorado diante dele; pensar nisso me enche de medo.

[[v18-23-16]]

^<<v18-23-16,16>>^ Deus fez desmaiar o meu coração; o Todo-poderoso causou-me pavor.

[[v18-23-17]]

^<<v18-23-17,17>>^ Contudo não fui silenciado pelas trevas, pelas densas trevas que cobrem o meu rosto.

'''

xref:018-jo/018-jo-022.adoc#v18-22-0[&#60; Capítulo Anterior] | <<v18-23-0,Topo>> | xref:018-jo/018-jo-024.adoc#v18-24-0[Próximo Capítulo &#62;]