include::./index.adoc[]

[[v18-24-0]]
=== Jó, 24
// nvi ?, NVI - Nova Versão Internacional

[[v18-24-1]]

^<<v18-24-1,1>>^ "Por que o Todo-poderoso não marca as datas para julgamento? Por que aqueles que o conhecem não chegam a vê-las?

[[v18-24-2]]

^<<v18-24-2,2>>^ Há os que mudam os marcos dos limites e apascentam rebanhos que eles roubaram.

[[v18-24-3]]

^<<v18-24-3,3>>^ Levam o jumento que pertence ao órfão e tomam o boi da viúva como penhor.

[[v18-24-4]]

^<<v18-24-4,4>>^ Forçam os necessitados a saírem do caminho e os pobres da terra a esconder-se.

[[v18-24-5]]

^<<v18-24-5,5>>^ Como jumentos selvagens no deserto, os pobres vão em busca de comida; da terra deserta a obtêm para os seus filhos.

[[v18-24-6]]

^<<v18-24-6,6>>^ Juntam forragem nos campos e respigam nas vinhas dos ímpios.

[[v18-24-7]]

^<<v18-24-7,7>>^ Pela falta de roupas, passam a noite nus; não têm com que cobrir-se no frio.

[[v18-24-8]]

^<<v18-24-8,8>>^ Encharcados pelas chuvas das montanhas, abraçam-se às rochas por falta de abrigo.

[[v18-24-9]]

^<<v18-24-9,9>>^ A criança órfã é arrancada do seio de sua mãe; o recém-nascido do pobre é tomado para pagar uma dívida.

[[v18-24-10]]

^<<v18-24-10,10>>^ Por falta de roupas, andam nus; carregam os feixes, mas continuam famintos.

[[v18-24-11]]

^<<v18-24-11,11>>^ Espremem azeitonas dentro dos seus muros; pisam uvas nos lagares, mas assim mesmo sofrem sede.

[[v18-24-12]]

^<<v18-24-12,12>>^ Sobem da cidade os gemidos dos que estão para morrer, e as almas dos feridos clamam por socorro. Mas Deus não vê mal nisso.

[[v18-24-13]]

^<<v18-24-13,13>>^ "Há os que se revoltam contra a luz, não conhecem os caminhos dela e não permanecem em suas veredas.

[[v18-24-14]]

^<<v18-24-14,14>>^ De manhã o assassino se levanta e mata os pobres e os necessitados; de noite age como ladrão.

[[v18-24-15]]

^<<v18-24-15,15>>^ Os olhos do adúltero ficam à espera do crepúsculo; ‘Nenhum olho me verá’, pensa ele; e mantém oculto o rosto.

[[v18-24-16]]

^<<v18-24-16,16>>^ No escuro os homens invadem casas, mas de dia se enclausuram; não querem saber da luz.

[[v18-24-17]]

^<<v18-24-17,17>>^ Para eles a manhã é tremenda escuridão; eles são amigos dos pavores das trevas.

[[v18-24-18]]

^<<v18-24-18,18>>^ "São, porém, como espuma sobre as águas; sua parte da terra foi amaldiçoada, e por isso ninguém vai às vinhas.

[[v18-24-19]]

^<<v18-24-19,19>>^ Assim como o calor e a seca depressa consomem a neve derretida, assim a sepultura consome os que pecaram.

[[v18-24-20]]

^<<v18-24-20,20>>^ Sua mãe os esquece, os vermes se banqueteiam neles. Ninguém se lembra dos maus; quebram-se como árvores.

[[v18-24-21]]

^<<v18-24-21,21>>^ Devoram a estéril e sem filhos e não mostram bondade para com a viúva.

[[v18-24-22]]

^<<v18-24-22,22>>^ Mas Deus, por seu poder, os arranca; embora firmemente estabelecidos, a vida deles não tem segurança.

[[v18-24-23]]

^<<v18-24-23,23>>^ Ele poderá deixá-los descansar, sentindo-se seguros, mas os vigia atento nos caminhos que seguem.

[[v18-24-24]]

^<<v18-24-24,24>>^ Por um breve instante são exaltados, e depois se vão; colhidos como todos os demais; ceifados como espigas de cereal.

[[v18-24-25]]

^<<v18-24-25,25>>^ "Se não é assim, quem poderá provar que minto e reduzir a nada as minhas palavras? "

'''

xref:018-jo/018-jo-023.adoc#v18-23-0[&#60; Capítulo Anterior] | <<v18-24-0,Topo>> | xref:018-jo/018-jo-025.adoc#v18-25-0[Próximo Capítulo &#62;]