include::./index.adoc[]

[[v18-31-0]]
=== Jó, 31
// nvi ?, NVI - Nova Versão Internacional

[[v18-31-1]]

^<<v18-31-1,1>>^ "Fiz acordo com os meus olhos de não olhar com cobiça para as moças.

[[v18-31-2]]

^<<v18-31-2,2>>^ Pois qual é a porção que o homem recebe de Deus, lá de cima? Qual a sua herança do Todo-poderoso, que habita nas alturas?

[[v18-31-3]]

^<<v18-31-3,3>>^ Não é ruína para os ímpios, desgraça para os que fazem o mal?

[[v18-31-4]]

^<<v18-31-4,4>>^ Não vê ele os meus caminhos, e não considera cada um de meus passos?

[[v18-31-5]]

^<<v18-31-5,5>>^ "Se me conduzi com falsidade, ou se meus pés se apressaram a enganar,

[[v18-31-6]]

^<<v18-31-6,6>>^ Deus me pese em balança justa, e saberá que não tenho culpa;

[[v18-31-7]]

^<<v18-31-7,7>>^ se meus passos desviaram-se do caminho, se o meu coração foi conduzido por meus olhos, ou se minhas mãos foram contaminadas,

[[v18-31-8]]

^<<v18-31-8,8>>^ que outros comam o que semeei, e que as minhas plantações sejam arrancadas pelas raízes.

[[v18-31-9]]

^<<v18-31-9,9>>^ "Se o meu coração foi seduzido por mulher, ou se fiquei à espreita junto à porta do meu próximo,

[[v18-31-10]]

^<<v18-31-10,10>>^ que a minha esposa moa cereal de outro homem, e que outros durmam com ela.

[[v18-31-11]]

^<<v18-31-11,11>>^ Pois fazê-lo seria vergonhoso, crime merecedor de julgamento.

[[v18-31-12]]

^<<v18-31-12,12>>^ Isso é um fogo que consome até a Destruição; teria extirpado a minha colheita.

[[v18-31-13]]

^<<v18-31-13,13>>^ "Se neguei justiça aos meus servos e servas, quando reclamaram contra mim,

[[v18-31-14]]

^<<v18-31-14,14>>^ que farei quando Deus me confrontar? Que responderei quando chamado a prestar contas?

[[v18-31-15]]

^<<v18-31-15,15>>^ Aquele que me fez no ventre materno não fez também a eles? Não foi ele quem formou a mim e a eles No interior de nossas mães?

[[v18-31-16]]

^<<v18-31-16,16>>^ "Se não atendi aos desejos do pobre, ou se fatiguei os olhos da viúva,

[[v18-31-17]]

^<<v18-31-17,17>>^ se comi meu pão sozinho, sem compartilhá-lo com o órfão,

[[v18-31-18]]

^<<v18-31-18,18>>^ sendo que desde a minha juventude o criei como se fosse seu pai, e desde o nascimento guiei a viúva;

[[v18-31-19]]

^<<v18-31-19,19>>^ se vi alguém morrendo por falta de roupa, ou um necessitado sem cobertor,

[[v18-31-20]]

^<<v18-31-20,20>>^ e o seu coração não me abençoou porque o aqueci com a lã de minhas ovelhas,

[[v18-31-21]]

^<<v18-31-21,21>>^ se levantei a mão contra o órfão, ciente da minha influência no tribunal,

[[v18-31-22]]

^<<v18-31-22,22>>^ que o meu braço descaia do ombro, e se quebre nas juntas.

[[v18-31-23]]

^<<v18-31-23,23>>^ Pois eu tinha medo que Deus me destruísse, e, temendo o seu esplendor, não podia fazer tais coisas.

[[v18-31-24]]

^<<v18-31-24,24>>^ "Se pus no ouro a minha confiança e disse ao ouro puro: Você é a minha garantia,

[[v18-31-25]]

^<<v18-31-25,25>>^ se me regozijei por ter grande riqueza, pela fortuna que as minhas mãos obtiveram,

[[v18-31-26]]

^<<v18-31-26,26>>^ se contemplei o sol em seu fulgor e a lua a mover-se esplêndida,

[[v18-31-27]]

^<<v18-31-27,27>>^ e em segredo o meu coração foi seduzido e a minha mão lhes ofereceu beijos de veneração,

[[v18-31-28]]

^<<v18-31-28,28>>^ esses também seriam pecados merecedores de condenação, pois eu teria sido infiel a Deus, que está nas alturas.

[[v18-31-29]]

^<<v18-31-29,29>>^ "Se a desgraça do meu inimigo me alegrou, ou se os problemas que teve me deram prazer;

[[v18-31-30]]

^<<v18-31-30,30>>^ eu, que nunca deixei minha boca pecar, lançando maldição sobre ele;

[[v18-31-31]]

^<<v18-31-31,31>>^ se os que moram em minha casa nunca tivessem dito: ‘Quem não recebeu de Jó um pedaço de carne? ’,

[[v18-31-32]]

^<<v18-31-32,32>>^ sendo que nenhum estrangeiro teve que passar a noite na rua, pois a minha porta sempre esteve aberta para o viajante;

[[v18-31-33]]

^<<v18-31-33,33>>^ se escondi o meu pecado, como outros fazem, acobertando no coração a minha culpa,

[[v18-31-34]]

^<<v18-31-34,34>>^ com tanto medo da multidão e do desprezo dos familiares que me calei e não saí de casa...

[[v18-31-35]]

^<<v18-31-35,35>>^ ( "Ah, se alguém me ouvisse! Agora assino a minha defesa. Que o Todo-poderoso me responda; que o meu acusador faça a acusação por escrito.

[[v18-31-36]]

^<<v18-31-36,36>>^ Eu bem que a levaria nos ombros e a usaria como coroa.

[[v18-31-37]]

^<<v18-31-37,37>>^ Eu lhe falaria sobre todos os meus passos; como um príncipe eu me aproximaria dele. )

[[v18-31-38]]

^<<v18-31-38,38>>^ "Se a minha terra se queixar de mim e todos os seus sulcos chorarem,

[[v18-31-39]]

^<<v18-31-39,39>>^ se consumi os seus produtos sem nada pagar, ou se causei desânimo aos seus ocupantes,

[[v18-31-40]]

^<<v18-31-40,40>>^ que me venham espinhos em lugar de trigo e ervas daninhas em lugar de cevada". Aqui terminam as palavras de Jó.

'''

xref:018-jo/018-jo-030.adoc#v18-30-0[&#60; Capítulo Anterior] | <<v18-31-0,Topo>> | xref:018-jo/018-jo-032.adoc#v18-32-0[Próximo Capítulo &#62;]