include::./index.adoc[]

[[v18-26-0]]
=== Jó, 26
// nvi ?, NVI - Nova Versão Internacional

[[v18-26-1]]

^<<v18-26-1,1>>^ Então Jó respondeu:

[[v18-26-2]]

^<<v18-26-2,2>>^ Grande foi a ajuda que você deu ao desvalido! Que socorro você prestou ao braço frágil!

[[v18-26-3]]

^<<v18-26-3,3>>^ Belo conselho você ofereceu a quem não é sábio, e que grande sabedoria você revelou!

[[v18-26-4]]

^<<v18-26-4,4>>^ Quem o ajudou a proferir essas palavras, e por meio de que espírito você falou?

[[v18-26-5]]

^<<v18-26-5,5>>^ "Os mortos estão em grande angústia sob as águas e os que nelas vivem.

[[v18-26-6]]

^<<v18-26-6,6>>^ Nu está o Sheol diante de Deus, e nada encobre a Destruição.

[[v18-26-7]]

^<<v18-26-7,7>>^ Ele estende os céus do norte sobre o espaço vazio; suspende a terra sobre o nada.

[[v18-26-8]]

^<<v18-26-8,8>>^ Envolve as águas em suas nuvens, e estas não se rompem sob o peso delas.

[[v18-26-9]]

^<<v18-26-9,9>>^ Ele cobre a face da lua cheia estendendo sobre ela as suas nuvens.

[[v18-26-10]]

^<<v18-26-10,10>>^ Traça o horizonte sobre a superfície das águas para servir de limite entre a luz e as trevas.

[[v18-26-11]]

^<<v18-26-11,11>>^ As colunas dos céus estremecem e ficam perplexas diante da sua repreensão.

[[v18-26-12]]

^<<v18-26-12,12>>^ Com seu poder agitou violentamente o mar; com sua sabedoria despedaçou Raabe.

[[v18-26-13]]

^<<v18-26-13,13>>^ Com seu sopro os céus ficaram límpidos; sua mão feriu a serpente arisca.

[[v18-26-14]]

^<<v18-26-14,14>>^ E isso tudo é apenas a borda das suas obras! Um suave sussurro é o que ouvimos dele. Mas quem poderá compreender o trovão do seu poder? "

'''

xref:018-jo/018-jo-025.adoc#v18-25-0[&#60; Capítulo Anterior] | <<v18-26-0,Topo>> | xref:018-jo/018-jo-027.adoc#v18-27-0[Próximo Capítulo &#62;]