include::./index.adoc[]

[[v54-5-0]]
=== 1 Timóteo, 5
// nvi ?, NVI - Nova Versão Internacional

[[v54-5-1]]

^<<v54-5-1,1>>^ Não repreenda asperamente ao homem idoso, mas exorte-o como se ele fosse seu pai; trate os jovens como a irmãos;

[[v54-5-2]]

^<<v54-5-2,2>>^ as mulheres idosas, como a mães; e as moças, como a irmãs, com toda a pureza.

[[v54-5-3]]

^<<v54-5-3,3>>^ Trate adequadamente as viúvas que são realmente necessitadas.

[[v54-5-4]]

^<<v54-5-4,4>>^ Mas se uma viúva tem filhos ou netos, que estes aprendam primeiramente a colocar a sua religião em prática, cuidando de sua própria família e retribuindo o bem recebido de seus pais e avós, pois isso agrada a Deus.

[[v54-5-5]]

^<<v54-5-5,5>>^ A viúva realmente necessitada e desamparada põe sua esperança em Deus e persiste dia e noite em oração e em súplica.

[[v54-5-6]]

^<<v54-5-6,6>>^ Mas a que vive para os prazeres, ainda que esteja viva, está morta.

[[v54-5-7]]

^<<v54-5-7,7>>^ Ordene estas coisas para que sejam irrepreensíveis.

[[v54-5-8]]

^<<v54-5-8,8>>^ Se alguém não cuida de seus parentes, e especialmente dos de sua própria família, negou a fé e é pior que um descrente.

[[v54-5-9]]

^<<v54-5-9,9>>^ Nenhuma mulher deve ser inscrita na lista de viúvas, a não ser que tenha mais de sessenta anos de idade, tenha sido fiel a seu marido

[[v54-5-10]]

^<<v54-5-10,10>>^ e seja bem conhecida por suas boas obras, tais como criar filhos, ser hospitaleira, lavar os pés dos santos, socorrer os atribulados e dedicar-se a todo tipo de boa obra.

[[v54-5-11]]

^<<v54-5-11,11>>^ Não inclua nessa lista as viúvas mais jovens, pois, quando os seus desejos sensuais superam a sua dedicação a Cristo, querem se casar.

[[v54-5-12]]

^<<v54-5-12,12>>^ Assim, elas trazem condenação sobre si, por haverem rompido seu primeiro compromisso.

[[v54-5-13]]

^<<v54-5-13,13>>^ Além disso, aprendem a ficar ociosas, andando de casa em casa; e não se tornam apenas ociosas, mas também fofoqueiras e indiscretas, falando coisas que não devem.

[[v54-5-14]]

^<<v54-5-14,14>>^ Portanto, aconselho que as viúvas mais jovens se casem, tenham filhos, administrem suas casas e não dêem ao inimigo nenhum motivo para maledicência.

[[v54-5-15]]

^<<v54-5-15,15>>^ Algumas, na verdade, já se desviaram, para seguir a Satanás.

[[v54-5-16]]

^<<v54-5-16,16>>^ Se alguma mulher crente tem viúvas em sua família, deve ajudá-las. Não seja a igreja sobrecarregada com elas, a fim de que as viúvas realmente necessitadas sejam auxiliadas.

[[v54-5-17]]

^<<v54-5-17,17>>^ Os presbíteros que lideram bem a igreja são dignos de dupla honra, especialmente aqueles cujo trabalho é a pregação e o ensino,

[[v54-5-18]]

^<<v54-5-18,18>>^ pois a Escritura diz: "Não amordace o boi enquanto está debulhando o cereal", e "o trabalhador merece o seu salário".

[[v54-5-19]]

^<<v54-5-19,19>>^ Não aceite acusação contra um presbítero, se não for apoiada por duas ou três testemunhas.

[[v54-5-20]]

^<<v54-5-20,20>>^ Os que pecarem deverão ser repreendidos em público, para que os demais também temam.

[[v54-5-21]]

^<<v54-5-21,21>>^ Eu o exorto solenemente, diante de Deus, de Cristo Jesus e dos anjos eleitos, a que procure observar essas instruções sem parcialidade; e não faça nada por favoritismo.

[[v54-5-22]]

^<<v54-5-22,22>>^ Não se precipite em impor as mãos sobre ninguém e não participe dos pecados dos outros. Conserve-se puro.

[[v54-5-23]]

^<<v54-5-23,23>>^ Não continue a beber somente água; tome também um pouco de vinho, por causa do seu estômago e das suas freqüentes enfermidades.

[[v54-5-24]]

^<<v54-5-24,24>>^ Os pecados de alguns são evidentes, mesmo antes de serem submetidos a julgamento; enquanto que os pecados de outros se manifestam posteriormente.

[[v54-5-25]]

^<<v54-5-25,25>>^ Da mesma forma, as boas obras são evidentes, e as que não o são não podem permanecer ocultas.

'''

xref:054-1-timoteo/054-1-timoteo-004.adoc#v54-4-0[&#60; Capítulo Anterior] | <<v54-5-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-006.adoc#v54-6-0[Próximo Capítulo &#62;]