include::./index.adoc[]

[[v54-2-0]]
=== 1 Timóteo, 2
// nvi ?, NVI - Nova Versão Internacional

[[v54-2-1]]

^<<v54-2-1,1>>^ Antes de tudo, recomendo que se façam súplicas, orações, intercessões e ação de graças por todos os homens;

[[v54-2-2]]

^<<v54-2-2,2>>^ pelos reis e por todos os que exercem autoridade, para que tenhamos uma vida tranqüila e pacífica, com toda a piedade e dignidade.

[[v54-2-3]]

^<<v54-2-3,3>>^ Isso é bom e agradável perante Deus, nosso Salvador,

[[v54-2-4]]

^<<v54-2-4,4>>^ que deseja que todos os homens sejam salvos e cheguem ao conhecimento da verdade.

[[v54-2-5]]

^<<v54-2-5,5>>^ Pois há um só Deus e um só mediador entre Deus e os homens: o homem Cristo Jesus,

[[v54-2-6]]

^<<v54-2-6,6>>^ o qual se entregou a si mesmo como resgate por todos. Esse foi o testemunho dado em seu próprio tempo.

[[v54-2-7]]

^<<v54-2-7,7>>^ Para isso fui designado pregador e apóstolo mestre da verdadeira fé aos gentios. Digo-lhes a verdade, não minto.

[[v54-2-8]]

^<<v54-2-8,8>>^ Quero, pois, que os homens orem em todo lugar, levantando mãos santas, sem ira e sem discussões.

[[v54-2-9]]

^<<v54-2-9,9>>^ Da mesma forma quero que as mulheres se vistam modestamente, com decência e discrição, não se adornando com tranças, nem ouro, nem pérolas, nem roupas caras,

[[v54-2-10]]

^<<v54-2-10,10>>^ mas com boas obras, como convém a mulheres que professam adorar a Deus.

[[v54-2-11]]

^<<v54-2-11,11>>^ A mulher deve aprender em silêncio, com toda a sujeição.

[[v54-2-12]]

^<<v54-2-12,12>>^ Não permito que a mulher ensine, nem que tenha autoridade sobre o homem. Esteja, porém, em silêncio.

[[v54-2-13]]

^<<v54-2-13,13>>^ Porque primeiro foi formado Adão, e depois Eva.

[[v54-2-14]]

^<<v54-2-14,14>>^ E Adão não foi enganado, mas sim a mulher, que, tendo sido enganada, tornou-se transgressora.

[[v54-2-15]]

^<<v54-2-15,15>>^ Entretanto, a mulher será salva dando à luz filhos — se elas permanecerem na fé, no amor e na santidade, com bom senso.

'''

xref:054-1-timoteo/054-1-timoteo-001.adoc#v54-1-0[&#60; Capítulo Anterior] | <<v54-2-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-003.adoc#v54-3-0[Próximo Capítulo &#62;]