include::./index.adoc[]

[[v54-6-0]]
=== 1 Timóteo, 6
// nvi ?, NVI - Nova Versão Internacional

[[v54-6-1]]

^<<v54-6-1,1>>^ Todos os que estão sob o jugo da escravidão devem considerar seus senhores como dignos de todo o respeito, para que o nome de Deus e o nosso ensino não sejam blasfemados.

[[v54-6-2]]

^<<v54-6-2,2>>^ Os que têm senhores crentes não devem ter por eles menos respeito, pelo fato de serem irmãos; pelo contrário, devem servi-los ainda melhor, porque os que se beneficiam do seu serviço são fiéis e amados. Ensine e recomende essas coisas.

[[v54-6-3]]

^<<v54-6-3,3>>^ Se alguém ensina falsas doutrinas e não concorda com a sã doutrina de nosso Senhor Jesus Cristo e com o ensino que é segundo a piedade,

[[v54-6-4]]

^<<v54-6-4,4>>^ é orgulhoso e nada entende. Esse tal mostra um interesse doentio por controvérsias e contendas acerca de palavras, que resultam em inveja, brigas, difamações, suspeitas malignas

[[v54-6-5]]

^<<v54-6-5,5>>^ e atritos constantes entre pessoas que têm a mente corrompida e que são privados da verdade, os quais pensam que a piedade é fonte de lucro.

[[v54-6-6]]

^<<v54-6-6,6>>^ De fato, a piedade com contentamento é grande fonte de lucro,

[[v54-6-7]]

^<<v54-6-7,7>>^ pois nada trouxemos para este mundo e dele nada podemos levar;

[[v54-6-8]]

^<<v54-6-8,8>>^ por isso, tendo o que comer e com que vestir-nos, estejamos com isso satisfeitos.

[[v54-6-9]]

^<<v54-6-9,9>>^ Os que querem ficar ricos caem em tentação, em armadilhas e em muitos desejos descontrolados e nocivos, que levam os homens a mergulharem na ruína e na destruição,

[[v54-6-10]]

^<<v54-6-10,10>>^ pois o amor ao dinheiro é raiz de todos os males. Algumas pessoas, por cobiçarem o dinheiro, desviaram-se da fé e se atormentaram a si mesmas com muitos sofrimentos.

[[v54-6-11]]

^<<v54-6-11,11>>^ Você, porém, homem de Deus, fuja de tudo isso e busque a justiça, a piedade, a fé, o amor, a perseverança e a mansidão.

[[v54-6-12]]

^<<v54-6-12,12>>^ Combata o bom combate da fé. Tome posse da vida eterna, para a qual você foi chamado e fez a boa confissão na presença de muitas testemunhas.

[[v54-6-13]]

^<<v54-6-13,13>>^ Diante de Deus, que a tudo dá vida, e de Cristo Jesus, que diante de Pôncio Pilatos fez a boa confissão, eu lhe recomendo:

[[v54-6-14]]

^<<v54-6-14,14>>^ Guarde este mandamento imaculado, irrepreensível, até a manifestação de nosso Senhor Jesus Cristo,

[[v54-6-15]]

^<<v54-6-15,15>>^ a qual Deus fará se cumprir no seu devido tempo. Ele é o bendito e único Soberano, o Rei dos reis e Senhor dos senhores,

[[v54-6-16]]

^<<v54-6-16,16>>^ o único que é imortal e habita em luz inacessível, a quem ninguém viu nem pode ver. A ele sejam honra e poder para sempre. Amém.

[[v54-6-17]]

^<<v54-6-17,17>>^ Ordene aos que são ricos no presente mundo que não sejam arrogantes, nem ponham sua esperança na incerteza da riqueza, mas em Deus, que de tudo nos provê ricamente, para a nossa satisfação.

[[v54-6-18]]

^<<v54-6-18,18>>^ Ordene-lhes que pratiquem o bem, sejam ricos em boas obras, generosos e prontos para repartir.

[[v54-6-19]]

^<<v54-6-19,19>>^ Dessa forma, eles acumularão um tesouro para si mesmos, um firme fundamento para a era que há de vir, e assim alcançarão a verdadeira vida.

[[v54-6-20]]

^<<v54-6-20,20>>^ Timóteo, guarde o que lhe foi confiado. Evite as conversas inúteis e profanas e as idéias contraditórias do que é falsamente chamado conhecimento;

[[v54-6-21]]

^<<v54-6-21,21>>^ professando-o, alguns desviaram-se da fé. A graça seja com vocês.

'''

xref:054-1-timoteo/054-1-timoteo-005.adoc#v54-5-0[&#60; Capítulo Anterior] | <<v54-6-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-001.adoc#v55-1-0[Próximo Capítulo &#62;]