include::./index.adoc[]

[[v54-3-0]]
=== 1 Timóteo, 3
// nvi ?, NVI - Nova Versão Internacional

[[v54-3-1]]

^<<v54-3-1,1>>^ Esta afirmação é digna de confiança: se alguém deseja ser bispo, deseja uma nobre função.

[[v54-3-2]]

^<<v54-3-2,2>>^ É necessário, pois, que o bispo seja irrepreensível, marido de uma só mulher, sóbrio, prudente, respeitável, hospitaleiro e apto para ensinar;

[[v54-3-3]]

^<<v54-3-3,3>>^ não deve ser apegado ao vinho, nem violento, mas sim amável, pacífico e não apegado ao dinheiro.

[[v54-3-4]]

^<<v54-3-4,4>>^ Ele deve governar bem sua própria família, tendo os filhos sujeitos a ele, com toda a dignidade.

[[v54-3-5]]

^<<v54-3-5,5>>^ Pois, se alguém não sabe governar sua própria família, como poderá cuidar da igreja de Deus?

[[v54-3-6]]

^<<v54-3-6,6>>^ Não pode ser recém-convertido, para que não se ensoberbeça e caia na mesma condenação em que caiu o diabo.

[[v54-3-7]]

^<<v54-3-7,7>>^ Também deve ter boa reputação perante os de fora, para que não caia em descrédito nem na cilada do diabo.

[[v54-3-8]]

^<<v54-3-8,8>>^ Os diáconos igualmente devem ser dignos, homens de palavra, não amigos de muito vinho nem de lucros desonestos.

[[v54-3-9]]

^<<v54-3-9,9>>^ Devem apegar-se ao mistério da fé com a consciência limpa.

[[v54-3-10]]

^<<v54-3-10,10>>^ Devem ser primeiramente experimentados; depois, se não houver nada contra eles, que atuem como diáconos.

[[v54-3-11]]

^<<v54-3-11,11>>^ As mulheres igualmente sejam dignas, não caluniadoras, mas sóbrias e confiáveis em tudo.

[[v54-3-12]]

^<<v54-3-12,12>>^ O diácono deve ser marido de uma só mulher e governar bem seus filhos e sua própria casa.

[[v54-3-13]]

^<<v54-3-13,13>>^ Os que servirem bem alcançarão uma excelente posição e grande determinação na fé em Cristo Jesus.

[[v54-3-14]]

^<<v54-3-14,14>>^ Escrevo-lhe estas coisas embora espere ir vê-lo em breve;

[[v54-3-15]]

^<<v54-3-15,15>>^ mas, se eu demorar, saiba como as pessoas devem comportar-se na casa de Deus, que é a igreja do Deus vivo, coluna e fundamento da verdade.

[[v54-3-16]]

^<<v54-3-16,16>>^ Não há dúvida de que é grande o mistério da piedade: Deus foi manifestado em corpo, justificado no Espírito, visto pelos anjos, pregado entre as nações, crido no mundo, recebido na glória.

'''

xref:054-1-timoteo/054-1-timoteo-002.adoc#v54-2-0[&#60; Capítulo Anterior] | <<v54-3-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-004.adoc#v54-4-0[Próximo Capítulo &#62;]