include::./index.adoc[]

[[v54-1-0]]
=== 1 Timóteo, 1
// nvi ?, NVI - Nova Versão Internacional

[[v54-1-1]]

^<<v54-1-1,1>>^ Paulo, apóstolo de Cristo Jesus, por ordem de Deus, nosso Salvador, e de Cristo Jesus, a nossa esperança,

[[v54-1-2]]

^<<v54-1-2,2>>^ a Timóteo, meu verdadeiro filho na fé: Graça, misericórdia e paz da parte de Deus Pai e de Cristo Jesus, o nosso Senhor.

[[v54-1-3]]

^<<v54-1-3,3>>^ Partindo eu para a Macedônia, roguei-lhe que permanecesse em Éfeso para ordenar a certas pessoas que não mais ensinem doutrinas falsas,

[[v54-1-4]]

^<<v54-1-4,4>>^ e que deixem de dar atenção a mitos e genealogias intermináveis, que causam controvérsias em vez de promoverem a obra de Deus, que é pela fé.

[[v54-1-5]]

^<<v54-1-5,5>>^ O objetivo desta instrução é o amor que procede de um coração puro, de uma boa consciência e de uma fé sincera.

[[v54-1-6]]

^<<v54-1-6,6>>^ Alguns se desviaram dessas coisas, voltando-se para discussões inúteis,

[[v54-1-7]]

^<<v54-1-7,7>>^ querendo ser mestres da lei, quando não compreendem nem o que dizem nem as coisas acerca das quais fazem afirmações tão categóricas.

[[v54-1-8]]

^<<v54-1-8,8>>^ Sabemos que a lei é boa, se alguém a usa de maneira adequada.

[[v54-1-9]]

^<<v54-1-9,9>>^ Também sabemos que ela não é feita para os justos, mas para os transgressores e insubordinados, para os ímpios e pecadores, para os profanos e irreverentes, para os que matam pai e mãe, para os homicidas,

[[v54-1-10]]

^<<v54-1-10,10>>^ para os que praticam imoralidade sexual e os homossexuais, para os seqüestradores, para os mentirosos e os que juram falsamente; e para todo aquele que se opõe à sã doutrina.

[[v54-1-11]]

^<<v54-1-11,11>>^ Essa sã doutrina se vê no glorioso evangelho que me foi confiado, o evangelho do Deus bendito.

[[v54-1-12]]

^<<v54-1-12,12>>^ Dou graças a Cristo Jesus, nosso Senhor, que me deu forças e me considerou fiel, designando-me para o ministério,

[[v54-1-13]]

^<<v54-1-13,13>>^ a mim que anteriormente fui blasfemo, perseguidor e insolente; mas alcancei misericórdia, porque o fiz por ignorância e na minha incredulidade;

[[v54-1-14]]

^<<v54-1-14,14>>^ contudo, a graça de nosso Senhor transbordou sobre mim, juntamente com a fé e o amor que estão em Cristo Jesus.

[[v54-1-15]]

^<<v54-1-15,15>>^ Esta afirmação é fiel e digna de toda aceitação: Cristo Jesus veio ao mundo para salvar os pecadores, dos quais eu sou o pior.

[[v54-1-16]]

^<<v54-1-16,16>>^ Mas, por isso mesmo alcancei misericórdia, para que em mim, o pior dos pecadores, Cristo Jesus demonstrasse toda a grandeza da sua paciência, usando-me como um exemplo para aqueles que nele haveriam de crer para a vida eterna.

[[v54-1-17]]

^<<v54-1-17,17>>^ Ao Rei eterno, ao Deus único, imortal e invisível, sejam honra e glória para todo o sempre. Amém.

[[v54-1-18]]

^<<v54-1-18,18>>^ Timóteo, meu filho, dou-lhe esta instrução, segundo as profecias já proferidas a seu respeito, para que, seguindo-as, você combata o bom combate,

[[v54-1-19]]

^<<v54-1-19,19>>^ mantendo a fé e a boa consciência que alguns rejeitaram e, por isso, naufragaram na fé.

[[v54-1-20]]

^<<v54-1-20,20>>^ Entre eles estão Himeneu e Alexandre, os quais entreguei a Satanás, para que aprendam a não blasfemar.

'''

xref:053-2-tessalonicenses/053-2-tessalonicenses-003.adoc#v53-3-0[&#60; Capítulo Anterior] | <<v54-1-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-002.adoc#v54-2-0[Próximo Capítulo &#62;]