include::./index.adoc[]

[[v54-4-0]]
=== 1 Timóteo, 4
// nvi ?, NVI - Nova Versão Internacional

[[v54-4-1]]

^<<v54-4-1,1>>^ O Espírito diz claramente que nos últimos tempos alguns abandonarão a fé e seguirão espíritos enganadores e doutrinas de demônios.

[[v54-4-2]]

^<<v54-4-2,2>>^ Tais ensinamentos vêm de homens hipócritas e mentirosos, que têm a consciência cauterizada

[[v54-4-3]]

^<<v54-4-3,3>>^ e proíbem o casamento e o consumo de alimentos que Deus criou para serem recebidos com ação de graças pelos que crêem e conhecem a verdade.

[[v54-4-4]]

^<<v54-4-4,4>>^ Pois tudo o que Deus criou é bom, e nada deve ser rejeitado, se for recebido com ação de graças,

[[v54-4-5]]

^<<v54-4-5,5>>^ pois é santificado pela palavra de Deus e pela oração.

[[v54-4-6]]

^<<v54-4-6,6>>^ Se você transmitir essas instruções aos irmãos, será um bom ministro de Cristo Jesus, nutrido com as verdades da fé e da boa doutrina que tem seguido.

[[v54-4-7]]

^<<v54-4-7,7>>^ Rejeite, porém, as fábulas profanas de velhas e exercite-se na piedade.

[[v54-4-8]]

^<<v54-4-8,8>>^ O exercício físico é de pouco proveito; a piedade, porém, para tudo é proveitosa, porque tem promessa da vida presente e da futura.

[[v54-4-9]]

^<<v54-4-9,9>>^ Esta é uma afirmação fiel e digna de plena aceitação.

[[v54-4-10]]

^<<v54-4-10,10>>^ Se trabalhamos e lutamos é porque temos colocado a nossa esperança no Deus vivo, o Salvador de todos os homens, especialmente dos que crêem.

[[v54-4-11]]

^<<v54-4-11,11>>^ Ordene e ensine estas coisas.

[[v54-4-12]]

^<<v54-4-12,12>>^ Ninguém o despreze pelo fato de você ser jovem, mas seja um exemplo para os fiéis na palavra, no procedimento, no amor, na fé e na pureza.

[[v54-4-13]]

^<<v54-4-13,13>>^ Até a minha chegada, dedique-se à leitura pública da Escritura, à exortação e ao ensino.

[[v54-4-14]]

^<<v54-4-14,14>>^ Não negligencie o dom que lhe foi dado por mensagem profética com imposição de mãos dos presbíteros.

[[v54-4-15]]

^<<v54-4-15,15>>^ Seja diligente nestas coisas; dedique-se inteiramente a elas, para que todos vejam o seu progresso.

[[v54-4-16]]

^<<v54-4-16,16>>^ Atente bem para a sua própria vida e para a doutrina, perseverando nesses deveres, pois, fazendo isso, você salvará tanto a si mesmo quanto aos que o ouvem.

'''

xref:054-1-timoteo/054-1-timoteo-003.adoc#v54-3-0[&#60; Capítulo Anterior] | <<v54-4-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-005.adoc#v54-5-0[Próximo Capítulo &#62;]