include::./index.adoc[]

[[v44-27-0]]
=== Atos, 27
// nvi ?, NVI - Nova Versão Internacional

[[v44-27-1]]

^<<v44-27-1,1>>^ Quando ficou decidido que navegaríamos para a Itália, Paulo e alguns outros presos foram entregues a um centurião chamado Júlio, que pertencia ao Regimento Imperial.

[[v44-27-2]]

^<<v44-27-2,2>>^ Embarcamos num navio de Adramítio, que estava de partida para alguns lugares da província da Ásia, e saímos ao mar, estando conosco Aristarco, um macedônio de Tessalônica.

[[v44-27-3]]

^<<v44-27-3,3>>^ No dia seguinte, ancoramos em Sidom; e Júlio, num gesto de bondade para com Paulo, permitiu-lhe que fosse ao encontro dos seus amigos, para que estes suprissem as suas necessidades.

[[v44-27-4]]

^<<v44-27-4,4>>^ Quando partimos de lá, passamos ao norte de Chipre, porque os ventos nos eram contrários.

[[v44-27-5]]

^<<v44-27-5,5>>^ Tendo atravessado o mar aberto ao longo da Cilícia e da Panfília, ancoramos em Mirra, na Lícia.

[[v44-27-6]]

^<<v44-27-6,6>>^ Ali, o centurião encontrou um navio alexandrino que estava de partida para a Itália e nele nos fez embarcar.

[[v44-27-7]]

^<<v44-27-7,7>>^ Navegamos vagarosamente por muitos dias e tivemos dificuldade para chegar a Cnido. Não sendo possível prosseguir em nossa rota, devido aos ventos contrários, navegamos ao sul de Creta, defronte a Salmona.

[[v44-27-8]]

^<<v44-27-8,8>>^ Costeamos a ilha com dificuldade e chegamos a um lugar chamado Bons Portos, perto da cidade de Laséia.

[[v44-27-9]]

^<<v44-27-9,9>>^ Tínhamos perdido muito tempo, e agora a navegação se tornara perigosa, pois já havia passado o Jejum. Por isso Paulo os advertiu:

[[v44-27-10]]

^<<v44-27-10,10>>^ "Senhores, vejo que a nossa viagem será desastrosa e acarretará grande prejuízo para o navio, para a carga e também para as nossas vidas".

[[v44-27-11]]

^<<v44-27-11,11>>^ Mas o centurião, em vez de ouvir o que Paulo falava, seguiu o conselho do piloto e do dono do navio.

[[v44-27-12]]

^<<v44-27-12,12>>^ Visto que o porto não era próprio para passar o inverno, a maioria decidiu que deveríamos continuar navegando, com a esperança de alcançar Fenice e ali passar o inverno. Este era um porto de Creta, que dava para sudoeste e noroeste.

[[v44-27-13]]

^<<v44-27-13,13>>^ Começando a soprar suavemente o vento sul, eles pensaram que haviam obtido o que desejavam; por isso levantaram âncoras e foram navegando ao longo da costa de Creta.

[[v44-27-14]]

^<<v44-27-14,14>>^ Pouco tempo depois, desencadeou-se da ilha um vento muito forte, chamado Nordeste.

[[v44-27-15]]

^<<v44-27-15,15>>^ O navio foi arrastado pela tempestade, sem poder resistir ao vento; assim, cessamos as manobras e ficamos à deriva.

[[v44-27-16]]

^<<v44-27-16,16>>^ Passando ao sul de uma pequena ilha chamada Clauda, foi com dificuldade que conseguimos recolher o barco salva-vidas.

[[v44-27-17]]

^<<v44-27-17,17>>^ Levantando-o, lançaram mão de todos os meios para reforçar o navio com cordas; e temendo que ele encalhasse nos bancos de areia de Sirte, baixaram as velas e deixaram o navio à deriva.

[[v44-27-18]]

^<<v44-27-18,18>>^ No dia seguinte, sendo violentamente castigados pela tempestade, começaram a lançar fora a carga.

[[v44-27-19]]

^<<v44-27-19,19>>^ No terceiro dia, lançaram fora, com as próprias mãos, a armação do navio.

[[v44-27-20]]

^<<v44-27-20,20>>^ Não aparecendo nem sol nem estrelas por muitos dias, e continuando a abater-se sobre nós grande tempestade, finalmente perdemos toda a esperança de salvamento.

[[v44-27-21]]

^<<v44-27-21,21>>^ Visto que os homens tinham passado muito tempo sem comer, Paulo levantou-se diante deles e disse: "Os senhores deviam ter aceitado o meu conselho de não partir de Creta, pois assim teriam evitado este dano e prejuízo.

[[v44-27-22]]

^<<v44-27-22,22>>^ Mas agora recomendo-lhes que tenham coragem, pois nenhum de vocês perderá a vida; apenas o navio será destruído.

[[v44-27-23]]

^<<v44-27-23,23>>^ Pois ontem à noite apareceu-me um anjo do Deus a quem pertenço e a quem adoro, dizendo-me:

[[v44-27-24]]

^<<v44-27-24,24>>^ ‘Paulo, não tenha medo. É preciso que você compareça perante César; Deus, por sua graça, deu-lhe as vidas de todos os que estão navegando com você’.

[[v44-27-25]]

^<<v44-27-25,25>>^ Assim, tenham ânimo, senhores! Creio em Deus que acontecerá do modo como me foi dito.

[[v44-27-26]]

^<<v44-27-26,26>>^ Devemos ser arrastados para alguma ilha".

[[v44-27-27]]

^<<v44-27-27,27>>^ Na décima quarta noite, ainda estávamos sendo levados de um lado para outro no mar Adriático, quando, por volta da meia-noite, os marinheiros imaginaram que estávamos próximos da terra.

[[v44-27-28]]

^<<v44-27-28,28>>^ Lançando a sonda, verificaram que a profundidade era de trinta e sete metros; pouco tempo depois, lançaram novamente a sonda e encontraram vinte e sete metros.

[[v44-27-29]]

^<<v44-27-29,29>>^ Temendo que fôssemos jogados contra as pedras, lançaram quatro âncoras da popa e faziam preces para que amanhecesse o dia.

[[v44-27-30]]

^<<v44-27-30,30>>^ Tentando escapar do navio, os marinheiros baixaram o barco salva-vidas ao mar, a pretexto de lançar âncoras da proa.

[[v44-27-31]]

^<<v44-27-31,31>>^ Então Paulo disse ao centurião e aos soldados: "Se estes homens não ficarem no navio, vocês não poderão salvar-se".

[[v44-27-32]]

^<<v44-27-32,32>>^ Com isso os soldados cortaram as cordas que prendiam o barco salva-vidas e o deixaram cair.

[[v44-27-33]]

^<<v44-27-33,33>>^ Pouco antes do amanhecer, Paulo insistia que todos se alimentassem, dizendo: "Hoje faz catorze dias que vocês têm estado em vigília constante, sem nada comer.

[[v44-27-34]]

^<<v44-27-34,34>>^ Agora eu os aconselho a comerem algo, pois só assim poderão sobreviver. Nenhum de vocês perderá um fio de cabelo sequer".

[[v44-27-35]]

^<<v44-27-35,35>>^ Tendo dito isso, tomou pão e deu graças a Deus diante de todos. Então o partiu e começou a comer.

[[v44-27-36]]

^<<v44-27-36,36>>^ Todos se reanimaram e também comeram algo.

[[v44-27-37]]

^<<v44-27-37,37>>^ Estavam a bordo duzentas e setenta e seis pessoas.

[[v44-27-38]]

^<<v44-27-38,38>>^ Depois de terem comido até ficarem satisfeitos, aliviaram o peso do navio, atirando todo o trigo ao mar.

[[v44-27-39]]

^<<v44-27-39,39>>^ Quando amanheceu não reconheceram a terra, mas viram uma enseada com uma praia, para onde decidiram conduzir o navio, se fosse possível.

[[v44-27-40]]

^<<v44-27-40,40>>^ Cortando as âncoras, deixaram-nas no mar, desatando ao mesmo tempo as cordas que prendiam os lemes. Então, alçando a vela da proa ao vento, dirigiram-se para a praia.

[[v44-27-41]]

^<<v44-27-41,41>>^ Mas o navio encalhou num banco de areia, onde tocou o fundo. A proa encravou-se e ficou imóvel, e a popa foi quebrada pela violência das ondas.

[[v44-27-42]]

^<<v44-27-42,42>>^ Os soldados resolveram matar os presos para impedir que algum deles fugisse, jogando-se ao mar.

[[v44-27-43]]

^<<v44-27-43,43>>^ Mas o centurião queria poupar a vida de Paulo e os impediu de executar o plano. Então ordenou aos que sabiam nadar que se lançassem primeiro ao mar em direção à terra.

[[v44-27-44]]

^<<v44-27-44,44>>^ Os outros teriam que salvar-se em tábuas ou em pedaços do navio. Dessa forma, todos chegaram a salvo em terra.

'''

xref:044-atos/044-atos-026.adoc#v44-26-0[&#60; Capítulo Anterior] | <<v44-27-0,Topo>> | xref:044-atos/044-atos-028.adoc#v44-28-0[Próximo Capítulo &#62;]