include::./index.adoc[]

[[v44-12-0]]
=== Atos, 12
// nvi ?, NVI - Nova Versão Internacional

[[v44-12-1]]

^<<v44-12-1,1>>^ Nessa ocasião, o rei Herodes prendeu alguns que pertenciam à igreja, com a intenção de maltratá-los,

[[v44-12-2]]

^<<v44-12-2,2>>^ e mandou matar à espada Tiago, irmão de João.

[[v44-12-3]]

^<<v44-12-3,3>>^ Vendo que isso agradava aos judeus, prosseguiu, prendendo também Pedro, durante a festa dos pães sem fermento.

[[v44-12-4]]

^<<v44-12-4,4>>^ Tendo-o prendido, lançou-o no cárcere, entregando-o para ser guardado por quatro escoltas de quatro soldados cada uma. Herodes pretendia submetê-lo a julgamento público depois da Páscoa.

[[v44-12-5]]

^<<v44-12-5,5>>^ Pedro, então, ficou detido na prisão, mas a igreja orava intensamente a Deus por ele.

[[v44-12-6]]

^<<v44-12-6,6>>^ Na noite anterior ao dia em que Herodes iria submetê-lo a julgamento, Pedro estava dormindo entre dois soldados, preso com duas algemas, e sentinelas montavam guarda à entrada do cárcere.

[[v44-12-7]]

^<<v44-12-7,7>>^ Repentinamente apareceu um anjo do Senhor, e uma luz brilhou na cela. Ele tocou no lado de Pedro e o acordou. "Depressa, levante-se! ", disse ele. Então as algemas caíram dos punhos de Pedro.

[[v44-12-8]]

^<<v44-12-8,8>>^ O anjo lhe disse: "Vista-se e calce as sandálias". E Pedro assim fez. Disse-lhe ainda o anjo: "Ponha a capa e siga-me".

[[v44-12-9]]

^<<v44-12-9,9>>^ E, saindo, Pedro o seguiu, não sabendo que era real o que se fazia por meio do anjo; tudo lhe parecia uma visão.

[[v44-12-10]]

^<<v44-12-10,10>>^ Passaram a primeira e a segunda guarda, e chegaram ao portão de ferro que dava para a cidade. Este se abriu por si mesmo para eles, e passaram. Tendo saído, caminharam ao longo de uma rua, e de repente, o anjo o deixou.

[[v44-12-11]]

^<<v44-12-11,11>>^ Então Pedro caiu em si e disse: "Agora sei, sem nenhuma dúvida, que o Senhor enviou o seu anjo e me libertou das mãos de Herodes e de tudo o que o povo judeu esperava".

[[v44-12-12]]

^<<v44-12-12,12>>^ Percebendo isso, ele se dirigiu à casa de Maria, mãe de João, também chamado Marcos, onde muita gente se havia reunido e estava orando.

[[v44-12-13]]

^<<v44-12-13,13>>^ Pedro bateu à porta do alpendre, e uma serva chamada Rode veio atender.

[[v44-12-14]]

^<<v44-12-14,14>>^ Ao reconhecer a voz de Pedro, tomada de alegria, ela correu de volta, sem abrir a porta, e exclamou: "Pedro está à porta! "

[[v44-12-15]]

^<<v44-12-15,15>>^ Eles porém lhe disseram: "Você está fora de si! " Insistindo ela em afirmar que era Pedro, disseram-lhe: "Deve ser o anjo dele".

[[v44-12-16]]

^<<v44-12-16,16>>^ Mas Pedro continuou batendo e, quando abriram a porta e o viram, ficaram perplexos.

[[v44-12-17]]

^<<v44-12-17,17>>^ Mas ele, fazendo-lhes sinal para que se calassem, descreveu como o Senhor o havia tirado da prisão e disse: "Contem isso a Tiago e aos irmãos". Então saiu e foi para outro lugar.

[[v44-12-18]]

^<<v44-12-18,18>>^ De manhã, não foi pequeno o alvoroço entre os soldados quanto ao que tinha acontecido a Pedro.

[[v44-12-19]]

^<<v44-12-19,19>>^ Fazendo uma busca completa e não o encontrando, Herodes fez uma investigação entre os guardas e ordenou que fossem executados. Depois Herodes foi da Judéia para Cesaréia e permaneceu ali durante algum tempo.

[[v44-12-20]]

^<<v44-12-20,20>>^ Ele estava cheio de ira contra o povo de Tiro e Sidom; contudo, eles haviam se reunido e procuravam ter uma audiência com ele. Tendo conseguido o apoio de Blasto, homem de confiança do rei, pediram paz, porque dependiam das terras do rei para obter alimento.

[[v44-12-21]]

^<<v44-12-21,21>>^ No dia marcado, Herodes, vestindo seus trajes reais, sentou-se em seu trono e fez um discurso ao povo.

[[v44-12-22]]

^<<v44-12-22,22>>^ Eles começaram a gritar: "É voz de deus, e não de homem".

[[v44-12-23]]

^<<v44-12-23,23>>^ Visto que Herodes não glorificou a Deus, imediatamente um anjo do Senhor o feriu; e ele morreu comido por vermes.

[[v44-12-24]]

^<<v44-12-24,24>>^ Entretanto, a palavra de Deus continuava a crescer e a espalhar-se.

[[v44-12-25]]

^<<v44-12-25,25>>^ Tendo terminado sua missão, Barnabé e Saulo voltaram de Jerusalém, levando consigo João, também chamado Marcos.

'''

xref:044-atos/044-atos-011.adoc#v44-11-0[&#60; Capítulo Anterior] | <<v44-12-0,Topo>> | xref:044-atos/044-atos-013.adoc#v44-13-0[Próximo Capítulo &#62;]