include::./index.adoc[]

[[v44-20-0]]
=== Atos, 20
// nvi ?, NVI - Nova Versão Internacional

[[v44-20-1]]

^<<v44-20-1,1>>^ Cessado o tumulto, Paulo mandou chamar os discípulos e, depois de encorajá-los, despediu-se e partiu para a Macedônia.

[[v44-20-2]]

^<<v44-20-2,2>>^ Viajou por aquela região, encorajando os irmãos com muitas palavras e, por fim, chegou à Grécia,

[[v44-20-3]]

^<<v44-20-3,3>>^ onde ficou três meses. Quando estava a ponto de embarcar para a Síria, os judeus fizeram uma conspiração contra ele; por isso decidiu voltar pela Macedônia,

[[v44-20-4]]

^<<v44-20-4,4>>^ sendo acompanhado por Sópatro, filho de Pirro, de Beréia; Aristarco e Secundo, de Tessalônica; Gaio, de Derbe; e Timóteo, além de Tíquico e Trófimo, da província da Ásia.

[[v44-20-5]]

^<<v44-20-5,5>>^ Esses homens foram adiante e nos esperaram em Trôade.

[[v44-20-6]]

^<<v44-20-6,6>>^ Navegamos de Filipos, após a festa dos pães sem fermento, e cinco dias depois nos reunimos com os outros em Trôade, onde ficamos sete dias.

[[v44-20-7]]

^<<v44-20-7,7>>^ No primeiro dia da semana reunimo-nos para partir o pão, e Paulo falou ao povo. Pretendendo partir no dia seguinte, continuou falando até à meia-noite.

[[v44-20-8]]

^<<v44-20-8,8>>^ Havia muitas candeias no piso superior onde estávamos reunidos.

[[v44-20-9]]

^<<v44-20-9,9>>^ Um jovem chamado Êutico, que estava sentado numa janela, adormeceu profundamente durante o longo discurso de Paulo. Vencido pelo sono, caiu do terceiro andar. Quando o levantaram, estava morto.

[[v44-20-10]]

^<<v44-20-10,10>>^ Paulo desceu, inclinou-se sobre o rapaz e o abraçou, dizendo: "Não fiquem alarmados! Ele está vivo! "

[[v44-20-11]]

^<<v44-20-11,11>>^ Então subiu novamente, partiu o pão e comeu. Depois, continuou a falar até o amanhecer e foi embora.

[[v44-20-12]]

^<<v44-20-12,12>>^ Levaram vivo o jovem, o que muito os consolou.

[[v44-20-13]]

^<<v44-20-13,13>>^ Quanto a nós, fomos até o navio e embarcamos para Assôs, onde iríamos receber Paulo a bordo. Assim ele tinha determinado, tendo preferido ir a pé.

[[v44-20-14]]

^<<v44-20-14,14>>^ Quando nos encontrou em Assôs, nós o recebemos a bordo e prosseguimos até Mitilene.

[[v44-20-15]]

^<<v44-20-15,15>>^ No dia seguinte navegamos dali e chegamos defronte de Quio; no outro dia atravessamos para Samos e, um dia depois, chegamos a Mileto.

[[v44-20-16]]

^<<v44-20-16,16>>^ Paulo tinha decidido não aportar em Éfeso, para não se demorar na província da Ásia, pois estava com pressa de chegar a Jerusalém, se possível antes do dia de Pentecoste.

[[v44-20-17]]

^<<v44-20-17,17>>^ De Mileto, Paulo mandou chamar os presbíteros da igreja de Éfeso.

[[v44-20-18]]

^<<v44-20-18,18>>^ Quando chegaram, ele lhes disse: "Vocês sabem como vivi todo o tempo em que estive com vocês, desde o primeiro dia em que cheguei à província da Ásia.

[[v44-20-19]]

^<<v44-20-19,19>>^ Servi ao Senhor com toda a humildade e com lágrimas, sendo severamente provado pelas conspirações dos judeus.

[[v44-20-20]]

^<<v44-20-20,20>>^ Vocês sabem que não deixei de pregar-lhes nada que fosse proveitoso, mas ensinei-lhes tudo publicamente e de casa em casa.

[[v44-20-21]]

^<<v44-20-21,21>>^ Testifiquei, tanto a judeus como a gregos, que eles precisam converter-se a Deus com arrependimento e fé em nosso Senhor Jesus.

[[v44-20-22]]

^<<v44-20-22,22>>^ "Agora, compelido pelo Espírito, estou indo para Jerusalém, sem saber o que me acontecerá ali,

[[v44-20-23]]

^<<v44-20-23,23>>^ senão que, em todas as cidades, o Espírito Santo me avisa que prisões e sofrimentos me esperam.

[[v44-20-24]]

^<<v44-20-24,24>>^ Todavia, não me importo, nem considero a minha vida de valor algum para mim mesmo, se tão-somente puder terminar a corrida e completar o ministério que o Senhor Jesus me confiou, de testemunhar do evangelho da graça de Deus.

[[v44-20-25]]

^<<v44-20-25,25>>^ "Agora sei que nenhum de vocês, entre os quais passei pregando o Reino, verá novamente a minha face.

[[v44-20-26]]

^<<v44-20-26,26>>^ Portanto, eu lhes declaro hoje que estou inocente do sangue de todos.

[[v44-20-27]]

^<<v44-20-27,27>>^ Pois não deixei de proclamar-lhes toda a vontade de Deus.

[[v44-20-28]]

^<<v44-20-28,28>>^ Cuidem de vocês mesmos e de todo o rebanho sobre o qual o Espírito Santo os colocou como bispos, para pastorearem a igreja de Deus, que ele comprou com o seu próprio sangue.

[[v44-20-29]]

^<<v44-20-29,29>>^ Sei que, depois da minha partida, lobos ferozes penetrarão no meio de vocês e não pouparão o rebanho.

[[v44-20-30]]

^<<v44-20-30,30>>^ E dentre vocês mesmos se levantarão homens que torcerão a verdade, a fim de atrair os discípulos.

[[v44-20-31]]

^<<v44-20-31,31>>^ Por isso, vigiem! Lembrem-se de que durante três anos jamais cessei de advertir a cada um de vocês disso, noite e dia, com lágrimas.

[[v44-20-32]]

^<<v44-20-32,32>>^ "Agora, eu os entrego a Deus e à palavra da sua graça, que pode edificá-los e dar-lhes herança entre todos os que são santificados.

[[v44-20-33]]

^<<v44-20-33,33>>^ Não cobicei a prata nem o ouro nem as roupas de ninguém.

[[v44-20-34]]

^<<v44-20-34,34>>^ Vocês mesmos sabem que estas minhas mãos supriram minhas necessidades e as de meus companheiros.

[[v44-20-35]]

^<<v44-20-35,35>>^ Em tudo o que fiz, mostrei-lhes que mediante trabalho árduo devemos ajudar os fracos, lembrando as palavras do próprio Senhor Jesus, que disse: ‘Há maior felicidade em dar do que em receber’ ".

[[v44-20-36]]

^<<v44-20-36,36>>^ Tendo dito isso, ajoelhou-se com todos eles e orou.

[[v44-20-37]]

^<<v44-20-37,37>>^ Todos choraram muito e, abraçando-o, o beijavam.

[[v44-20-38]]

^<<v44-20-38,38>>^ O que mais os entristeceu foi a declaração de que nunca mais veriam a sua face. Então o acompanharam até o navio.

'''

xref:044-atos/044-atos-019.adoc#v44-19-0[&#60; Capítulo Anterior] | <<v44-20-0,Topo>> | xref:044-atos/044-atos-021.adoc#v44-21-0[Próximo Capítulo &#62;]