include::./index.adoc[]

[[v44-10-0]]
=== Atos, 10
// nvi ?, NVI - Nova Versão Internacional

[[v44-10-1]]

^<<v44-10-1,1>>^ Havia em Cesaréia um homem chamado Cornélio, centurião do regimento conhecido como Italiano.

[[v44-10-2]]

^<<v44-10-2,2>>^ Ele e toda a sua família eram piedosos e tementes a Deus; dava muitas esmolas ao povo e orava continuamente a Deus.

[[v44-10-3]]

^<<v44-10-3,3>>^ Certo dia, por volta das três horas da tarde, ele teve uma visão. Viu claramente um anjo de Deus que se aproximava dele e dizia: "Cornélio! "

[[v44-10-4]]

^<<v44-10-4,4>>^ Atemorizado, Cornélio olhou para ele e perguntou: "Que é, Senhor? " O anjo respondeu: "Suas orações e esmolas subiram como oferta memorial diante de Deus.

[[v44-10-5]]

^<<v44-10-5,5>>^ Agora, mande alguns homens a Jope para trazerem um certo Simão, também conhecido como Pedro,

[[v44-10-6]]

^<<v44-10-6,6>>^ que está hospedado na casa de Simão, o curtidor de couro, que fica perto do mar".

[[v44-10-7]]

^<<v44-10-7,7>>^ Depois que o anjo que lhe falou se foi, Cornélio chamou dois dos seus servos e um soldado piedoso dentre os seus auxiliares,

[[v44-10-8]]

^<<v44-10-8,8>>^ e, contando-lhes tudo o que tinha acontecido, enviou-os a Jope.

[[v44-10-9]]

^<<v44-10-9,9>>^ No dia seguinte, por volta do meio dia, enquanto eles viajavam e se aproximavam da cidade, Pedro subiu ao terraço para orar.

[[v44-10-10]]

^<<v44-10-10,10>>^ Tendo fome, queria comer; enquanto a refeição estava sendo preparada, caiu em êxtase.

[[v44-10-11]]

^<<v44-10-11,11>>^ Viu o céu aberto e algo semelhante a um grande lençol que descia à terra, preso pelas quatro pontas,

[[v44-10-12]]

^<<v44-10-12,12>>^ contendo toda espécie de quadrúpedes, bem como de répteis da terra e aves do céu.

[[v44-10-13]]

^<<v44-10-13,13>>^ Então uma voz lhe disse: "Levante-se, Pedro; mate e coma".

[[v44-10-14]]

^<<v44-10-14,14>>^ Mas Pedro respondeu: "De modo nenhum, Senhor! Jamais comi algo impuro ou imundo! "

[[v44-10-15]]

^<<v44-10-15,15>>^ A voz lhe falou segunda vez: "Não chame impuro ao que Deus purificou".

[[v44-10-16]]

^<<v44-10-16,16>>^ Isso aconteceu três vezes, e em seguida o lençol foi recolhido ao céu.

[[v44-10-17]]

^<<v44-10-17,17>>^ Enquanto Pedro estava refletindo no significado da visão, os homens enviados por Cornélio descobriram onde era a casa de Simão e chegaram à porta.

[[v44-10-18]]

^<<v44-10-18,18>>^ Chamando, perguntaram se ali estava hospedado Simão, conhecido como Pedro.

[[v44-10-19]]

^<<v44-10-19,19>>^ Enquanto Pedro ainda estava pensando na visão, o Espírito lhe disse: "Simão, três homens estão procurando por você.

[[v44-10-20]]

^<<v44-10-20,20>>^ Portanto, levante-se e desça. Não hesite em ir com eles, pois eu os enviei".

[[v44-10-21]]

^<<v44-10-21,21>>^ Pedro desceu e disse aos homens: "Eu sou quem vocês estão procurando. Por que motivo vieram? "

[[v44-10-22]]

^<<v44-10-22,22>>^ Os homens responderam: "Viemos da parte do centurião Cornélio. Ele é um homem justo e temente a Deus, respeitado por todo o povo judeu. Um santo anjo lhe disse que o chamasse à sua casa, para que ele ouça o que você tem para dizer".

[[v44-10-23]]

^<<v44-10-23,23>>^ Pedro os convidou a entrar e os hospedou. No dia seguinte Pedro partiu com eles, e alguns dos irmãos de Jope o acompanharam.

[[v44-10-24]]

^<<v44-10-24,24>>^ No outro dia chegaram a Cesaréia. Cornélio os esperava com seus parentes e amigos mais íntimos que tinha convidado.

[[v44-10-25]]

^<<v44-10-25,25>>^ Quando Pedro ia entrando na casa, Cornélio dirigiu-se a ele e prostrou-se aos seus pés, adorando-o.

[[v44-10-26]]

^<<v44-10-26,26>>^ Mas Pedro o fez levantar-se, dizendo: "Levante-se, eu sou homem como você".

[[v44-10-27]]

^<<v44-10-27,27>>^ Conversando com ele, Pedro entrou e encontrou ali reunidas muitas pessoas

[[v44-10-28]]

^<<v44-10-28,28>>^ e lhes disse: "Vocês sabem muito bem que é contra a nossa lei um judeu associar-se a um gentio ou mesmo visitá-lo. Mas Deus me mostrou que eu não deveria chamar impuro ou imundo a homem nenhum.

[[v44-10-29]]

^<<v44-10-29,29>>^ Por isso, quando fui procurado, vim sem qualquer objeção. Posso perguntar por que vocês me mandaram buscar? "

[[v44-10-30]]

^<<v44-10-30,30>>^ Cornélio respondeu: "Há quatro dias eu estava em minha casa orando a esta hora, às três horas da tarde. De repente, colocou-se diante de mim um homem com roupas resplandecentes

[[v44-10-31]]

^<<v44-10-31,31>>^ e disse: ‘Cornélio, Deus ouviu sua oração e lembrou-se de suas esmolas.

[[v44-10-32]]

^<<v44-10-32,32>>^ Mande buscar em Jope a Simão, chamado Pedro. Ele está hospedado na casa de Simão, o curtidor de couro, que mora perto do mar’.

[[v44-10-33]]

^<<v44-10-33,33>>^ Assim, mandei buscar-te imediatamente, e foi bom que tenhas vindo. Agora estamos todos aqui na presença de Deus, para ouvir tudo que o Senhor te mandou dizer-nos".

[[v44-10-34]]

^<<v44-10-34,34>>^ Então Pedro começou a falar: "Agora percebo verdadeiramente que Deus não trata as pessoas com parcialidade,

[[v44-10-35]]

^<<v44-10-35,35>>^ mas de todas as nações aceita todo aquele que o teme e faz o que é justo.

[[v44-10-36]]

^<<v44-10-36,36>>^ Vocês conhecem a mensagem enviada por Deus ao povo de Israel, que fala das boas novas de paz por meio de Jesus Cristo, Senhor de todos.

[[v44-10-37]]

^<<v44-10-37,37>>^ Sabem o que aconteceu em toda a Judéia, começando na Galiléia, depois do batismo que João pregou,

[[v44-10-38]]

^<<v44-10-38,38>>^ como Deus ungiu a Jesus de Nazaré com o Espírito Santo e poder, e como ele andou por toda parte fazendo o bem e curando todos os oprimidos pelo diabo, porque Deus estava com ele.

[[v44-10-39]]

^<<v44-10-39,39>>^ "Nós somos testemunhas de tudo o que ele fez na terra dos judeus e em Jerusalém, onde o mataram, suspendendo-o num madeiro.

[[v44-10-40]]

^<<v44-10-40,40>>^ Deus, porém, o ressuscitou no terceiro dia e fez que ele fosse visto,

[[v44-10-41]]

^<<v44-10-41,41>>^ não por todo o povo, mas por testemunhas que designara de antemão, por nós que comemos e bebemos com ele depois que ressuscitou dos mortos.

[[v44-10-42]]

^<<v44-10-42,42>>^ Ele nos mandou pregar ao povo e testemunhar que este é aquele a quem Deus constituiu juiz de vivos e de mortos.

[[v44-10-43]]

^<<v44-10-43,43>>^ Todos os profetas dão testemunho dele, de que todo aquele que nele crê recebe o perdão dos pecados mediante o seu nome".

[[v44-10-44]]

^<<v44-10-44,44>>^ Enquanto Pedro ainda estava falando estas palavras, o Espírito Santo desceu sobre todos os que ouviam a mensagem.

[[v44-10-45]]

^<<v44-10-45,45>>^ Os judeus convertidos que vieram com Pedro ficaram admirados de que o dom do Espírito Santo fosse derramado até sobre os gentios,

[[v44-10-46]]

^<<v44-10-46,46>>^ pois os ouviam falando em línguas e exaltando a Deus. A seguir Pedro disse:

[[v44-10-47]]

^<<v44-10-47,47>>^ "Pode alguém negar a água, impedindo que estes sejam batizados? Eles receberam o Espírito Santo como nós! "

[[v44-10-48]]

^<<v44-10-48,48>>^ Então ordenou que fossem batizados em nome de Jesus Cristo. Depois pediram a Pedro que ficasse com eles alguns dias.

'''

xref:044-atos/044-atos-009.adoc#v44-9-0[&#60; Capítulo Anterior] | <<v44-10-0,Topo>> | xref:044-atos/044-atos-011.adoc#v44-11-0[Próximo Capítulo &#62;]