include::./index.adoc[]

[[v44-28-0]]
=== Atos, 28
// nvi ?, NVI - Nova Versão Internacional

[[v44-28-1]]

^<<v44-28-1,1>>^ Uma vez em terra, descobrimos que a ilha se chamava Malta.

[[v44-28-2]]

^<<v44-28-2,2>>^ Os habitantes da ilha mostraram extraordinária bondade para conosco. Fizeram uma fogueira e receberam bem a todos nós, pois estava chovendo e fazia frio.

[[v44-28-3]]

^<<v44-28-3,3>>^ Paulo ajuntou um monte de gravetos; quando os colocava no fogo, uma víbora, fugindo do calor, prendeu-se à sua mão.

[[v44-28-4]]

^<<v44-28-4,4>>^ Quando os habitantes da ilha viram a cobra agarrada na mão de Paulo, disseram uns aos outros: "Certamente este homem é assassino, pois, tendo escapado do mar, a Justiça não lhe permite viver".

[[v44-28-5]]

^<<v44-28-5,5>>^ Mas Paulo, sacudindo a cobra no fogo, não sofreu mal nenhum.

[[v44-28-6]]

^<<v44-28-6,6>>^ Eles, porém, esperavam que ele começasse a inchar ou que caísse morto de repente, mas, tendo esperado muito tempo e vendo que nada de estranho lhe sucedia, mudaram de idéia e passaram a dizer que ele era um deus.

[[v44-28-7]]

^<<v44-28-7,7>>^ Próximo dali havia uma propriedade pertencente a Públio, o homem principal da ilha. Ele nos convidou a ficar em sua casa e, por três dias, bondosamente nos recebeu e nos hospedou.

[[v44-28-8]]

^<<v44-28-8,8>>^ Seu pai estava doente, acamado, sofrendo de febre e disenteria. Paulo entrou para vê-lo e, depois de orar, impôs-lhe as mãos e o curou.

[[v44-28-9]]

^<<v44-28-9,9>>^ Tendo acontecido isso, os outros doentes da ilha vieram e foram curados.

[[v44-28-10]]

^<<v44-28-10,10>>^ Eles nos prestaram muitas honras e, quando estávamos para embarcar, forneceram-nos os suprimentos que necessitávamos.

[[v44-28-11]]

^<<v44-28-11,11>>^ Passados três meses, embarcamos num navio que tinha passado o inverno na ilha; era um navio alexandrino, que tinha por emblema os deuses gêmeos Castor e Pólux.

[[v44-28-12]]

^<<v44-28-12,12>>^ Aportando em Siracusa, ficamos ali três dias.

[[v44-28-13]]

^<<v44-28-13,13>>^ Dali partimos e chegamos a Régio. No dia seguinte, soprando o vento sul, prosseguimos, chegando a Potéoli no segundo dia.

[[v44-28-14]]

^<<v44-28-14,14>>^ Ali encontramos alguns irmãos que nos convidaram a passar uma semana com eles. E depois fomos para Roma.

[[v44-28-15]]

^<<v44-28-15,15>>^ Os irmãos dali tinham ouvido falar que estávamos chegando e foram até a praça de Ápio e às Três Vendas para nos encontrar. Vendo-os, Paulo deu graças a Deus e sentiu-se encorajado.

[[v44-28-16]]

^<<v44-28-16,16>>^ Quando chegamos a Roma, Paulo recebeu permissão para morar por conta própria, sob a custódia de um soldado.

[[v44-28-17]]

^<<v44-28-17,17>>^ Três dias depois, ele convocou os líderes dos judeus. Quando estes se reuniram, Paulo lhes disse: "Meus irmãos, embora eu não tenha feito nada contra o nosso povo nem contra os costumes dos nossos antepassados, fui preso em Jerusalém e entregue aos romanos.

[[v44-28-18]]

^<<v44-28-18,18>>^ Eles me interrogaram e queriam me soltar, porque eu não era culpado de crime algum que merecesse pena de morte.

[[v44-28-19]]

^<<v44-28-19,19>>^ Todavia, tendo os judeus feito objeção, fui obrigado a apelar para César, não porém, por ter alguma acusação contra o meu próprio povo.

[[v44-28-20]]

^<<v44-28-20,20>>^ Por essa razão pedi para vê-los e conversar com vocês. Por causa da esperança de Israel é que estou preso com estas algemas".

[[v44-28-21]]

^<<v44-28-21,21>>^ Eles responderam: "Não recebemos nenhuma carta da Judéia a seu respeito, e nenhum dos irmãos que vieram de lá relatou ou disse qualquer coisa de mal contra você.

[[v44-28-22]]

^<<v44-28-22,22>>^ Todavia, queremos ouvir de sua parte o que você pensa, pois sabemos que por todo lugar há gente falando contra esta seita".

[[v44-28-23]]

^<<v44-28-23,23>>^ Assim combinaram encontrar-se com Paulo em dia determinado, indo em grupo ainda mais numeroso ao lugar onde ele estava. Desde a manhã até à tarde ele lhes deu explicações e lhes testemunhou do Reino de Deus, procurando convencê-los a respeito de Jesus, com base na Lei de Moisés e nos Profetas.

[[v44-28-24]]

^<<v44-28-24,24>>^ Alguns foram convencidos pelo que ele dizia, mas outros não creram.

[[v44-28-25]]

^<<v44-28-25,25>>^ Discordaram entre si mesmos e começaram a ir embora, depois de Paulo ter feito esta declaração final: "Bem que o Espírito Santo falou aos seus antepassados, por meio do profeta Isaías:

[[v44-28-26]]

^<<v44-28-26,26>>^ ‘Vá a este povo e diga: "Ainda que estejam sempre ouvindo, vocês nunca entenderão; ainda que estejam sempre vendo, jamais perceberão".

[[v44-28-27]]

^<<v44-28-27,27>>^ Pois o coração deste povo se tornou insensível; de má vontade ouviram com os seus ouvidos, e fecharam os seus olhos. Se assim não fosse, poderiam ver com os olhos, ouvir com os ouvidos, entender com o coração e converter-se, e eu os curaria’.

[[v44-28-28]]

^<<v44-28-28,28>>^ "Portanto, quero que saibam que esta salvação de Deus é enviada aos gentios; eles a ouvirão! "

[[v44-28-29]]

^<<v44-28-29,29>>^ Depois que ele disse isto, os judeus se retiraram, discutindo intensamente entre si.

[[v44-28-30]]

^<<v44-28-30,30>>^ Por dois anos inteiros Paulo permaneceu na casa que havia alugado, e recebia a todos os que iam vê-lo.

[[v44-28-31]]

^<<v44-28-31,31>>^ Pregava o Reino de Deus e ensinava a respeito do Senhor Jesus Cristo, abertamente e sem impedimento algum.

'''

xref:044-atos/044-atos-027.adoc#v44-27-0[&#60; Capítulo Anterior] | <<v44-28-0,Topo>> | xref:045-romanos/045-romanos-001.adoc#v45-1-0[Próximo Capítulo &#62;]