include::./index.adoc[]

[[v44-9-0]]
=== Atos, 9
// nvi ?, NVI - Nova Versão Internacional

[[v44-9-1]]

^<<v44-9-1,1>>^ Enquanto isso, Saulo ainda respirava ameaças de morte contra os discípulos do Senhor. Dirigindo-se ao sumo sacerdote,

[[v44-9-2]]

^<<v44-9-2,2>>^ pediu-lhe cartas para as sinagogas de Damasco, de maneira que, caso encontrasse ali homens ou mulheres que pertencessem ao Caminho, pudesse levá-los presos para Jerusalém.

[[v44-9-3]]

^<<v44-9-3,3>>^ Em sua viagem, quando se aproximava de Damasco, de repente brilhou ao seu redor uma luz vinda do céu.

[[v44-9-4]]

^<<v44-9-4,4>>^ Ele caiu por terra e ouviu uma voz que lhe dizia: "Saulo, Saulo, por que você me persegue? "

[[v44-9-5]]

^<<v44-9-5,5>>^ Saulo perguntou: "Quem és tu, Senhor? " Ele respondeu: "Eu sou Jesus, a quem você persegue.

[[v44-9-6]]

^<<v44-9-6,6>>^ Levante-se, entre na cidade; alguém lhe dirá o que você deve fazer".

[[v44-9-7]]

^<<v44-9-7,7>>^ Os homens que viajavam com Saulo pararam emudecidos; ouviam a voz mas não viam ninguém.

[[v44-9-8]]

^<<v44-9-8,8>>^ Saulo levantou-se do chão e, abrindo os olhos, não conseguia ver nada. E eles o levaram pela mão até Damasco.

[[v44-9-9]]

^<<v44-9-9,9>>^ Por três dias ele esteve cego, não comeu nem bebeu.

[[v44-9-10]]

^<<v44-9-10,10>>^ Em Damasco havia um discípulo chamado Ananias. O Senhor o chamou numa visão: "Ananias! " "Eis-me aqui, Senhor", respondeu ele.

[[v44-9-11]]

^<<v44-9-11,11>>^ O Senhor lhe disse: "Vá à casa de Judas, na rua chamada Direita, e pergunte por um homem de Tarso chamado Saulo. Ele está orando;

[[v44-9-12]]

^<<v44-9-12,12>>^ numa visão viu um homem chamado Ananias chegar e impor-lhe as mãos para que voltasse a ver".

[[v44-9-13]]

^<<v44-9-13,13>>^ Respondeu Ananias: "Senhor, tenho ouvido muita coisa a respeito desse homem e de todo o mal que ele tem feito aos teus santos em Jerusalém.

[[v44-9-14]]

^<<v44-9-14,14>>^ Ele chegou aqui com autorização dos chefes dos sacerdotes para prender todos os que invocam o teu nome".

[[v44-9-15]]

^<<v44-9-15,15>>^ Mas o Senhor disse a Ananias: "Vá! Este homem é meu instrumento escolhido para levar o meu nome perante os gentios e seus reis, e perante o povo de Israel.

[[v44-9-16]]

^<<v44-9-16,16>>^ Mostrarei a ele o quanto deve sofrer pelo meu nome".

[[v44-9-17]]

^<<v44-9-17,17>>^ Então Ananias foi, entrou na casa, impôs as mãos sobre Saulo e disse: "Irmão Saulo, o Senhor Jesus, que lhe apareceu no caminho por onde você vinha, enviou-me para que você volte a ver e seja cheio do Espírito Santo".

[[v44-9-18]]

^<<v44-9-18,18>>^ Imediatamente, algo como escamas caiu dos olhos de Saulo e ele passou a ver novamente. Levantando-se, foi batizado

[[v44-9-19]]

^<<v44-9-19,19>>^ e, depois de comer, recuperou as forças. Saulo passou vários dias com os discípulos em Damasco.

[[v44-9-20]]

^<<v44-9-20,20>>^ Logo começou a pregar nas sinagogas que Jesus é o Filho de Deus.

[[v44-9-21]]

^<<v44-9-21,21>>^ Todos os que o ouviam ficavam perplexos e perguntavam: "Não é ele o homem que procurava destruir em Jerusalém aqueles que invocam este nome? E não veio para cá justamente para levá-los presos aos chefes dos sacerdotes? "

[[v44-9-22]]

^<<v44-9-22,22>>^ Todavia, Saulo se fortalecia cada vez mais e confundia os judeus que viviam em Damasco, demonstrando que Jesus é o Cristo.

[[v44-9-23]]

^<<v44-9-23,23>>^ Decorridos muitos dias, os judeus decidiram de comum acordo matá-lo,

[[v44-9-24]]

^<<v44-9-24,24>>^ mas Saulo ficou sabendo do plano deles. Dia e noite eles vigiavam as portas da cidade a fim de matá-lo.

[[v44-9-25]]

^<<v44-9-25,25>>^ Mas os seus discípulos o levaram de noite e o fizeram descer num cesto, através de uma abertura na muralha.

[[v44-9-26]]

^<<v44-9-26,26>>^ Quando chegou a Jerusalém, tentou reunir-se aos discípulos, mas todos estavam com medo dele, não acreditando que fosse realmente um discípulo.

[[v44-9-27]]

^<<v44-9-27,27>>^ Então Barnabé o levou aos apóstolos e lhes contou como, no caminho, Saulo vira o Senhor, que lhe falara, e como em Damasco ele havia pregado corajosamente em nome de Jesus.

[[v44-9-28]]

^<<v44-9-28,28>>^ Assim, Saulo ficou com eles, e andava com liberdade em Jerusalém, pregando corajosamente em nome do Senhor.

[[v44-9-29]]

^<<v44-9-29,29>>^ Falava e discutia com os judeus de fala grega, mas estes tentavam matá-lo.

[[v44-9-30]]

^<<v44-9-30,30>>^ Sabendo disso, os irmãos o levaram para Cesaréia e o enviaram para Tarso.

[[v44-9-31]]

^<<v44-9-31,31>>^ A igreja passava por um período de paz em toda a Judéia, Galiléia e Samaria. Ela se edificava e, encorajada pelo Espírito Santo, crescia em número, vivendo no temor do Senhor.

[[v44-9-32]]

^<<v44-9-32,32>>^ Viajando por toda parte, Pedro foi visitar os santos que viviam em Lida.

[[v44-9-33]]

^<<v44-9-33,33>>^ Ali encontrou um paralítico chamado Enéias, que estava acamado fazia oito anos.

[[v44-9-34]]

^<<v44-9-34,34>>^ Disse-lhe Pedro: "Enéias, Jesus Cristo vai curá-lo! Levante-se e arrume a sua cama". Ele se levantou imediatamente.

[[v44-9-35]]

^<<v44-9-35,35>>^ Todos os que viviam em Lida e Sarona o viram e se converteram ao Senhor.

[[v44-9-36]]

^<<v44-9-36,36>>^ Em Jope havia uma discípula chamada Tabita, que em grego é Dorcas, que se dedicava a praticar boas obras e dar esmolas.

[[v44-9-37]]

^<<v44-9-37,37>>^ Naqueles dias ela ficou doente e morreu, e seu corpo foi lavado e colocado num quarto do andar superior.

[[v44-9-38]]

^<<v44-9-38,38>>^ Lida ficava perto de Jope, e quando os discípulos ouviram falar que Pedro estava em Lida, mandaram-lhe dois homens dizer-lhe: "Não se demore em vir até nós".

[[v44-9-39]]

^<<v44-9-39,39>>^ Pedro foi com eles e, quando chegou, foi levado para o quarto do andar superior. Todas as viúvas o rodearam, chorando e mostrando-lhe os vestidos e outras roupas que Dorcas tinha feito quando ainda estava com elas.

[[v44-9-40]]

^<<v44-9-40,40>>^ Pedro mandou que todos saíssem do quarto; depois, ajoelhou-se e orou. Voltando-se para a mulher morta, disse: "Tabita, levante-se". Ela abriu os olhos e, vendo Pedro, sentou-se.

[[v44-9-41]]

^<<v44-9-41,41>>^ Tomando-a pela mão, ajudou-a a pôr-se de pé. Então, chamando os santos e as viúvas, apresentou-a viva.

[[v44-9-42]]

^<<v44-9-42,42>>^ Este fato se tornou conhecido em toda a cidade de Jope, e muitos creram no Senhor.

[[v44-9-43]]

^<<v44-9-43,43>>^ Pedro ficou em Jope durante algum tempo, com um curtidor de couro chamado Simão.

'''

xref:044-atos/044-atos-008.adoc#v44-8-0[&#60; Capítulo Anterior] | <<v44-9-0,Topo>> | xref:044-atos/044-atos-010.adoc#v44-10-0[Próximo Capítulo &#62;]