include::./index.adoc[]

[[v44-14-0]]
=== Atos, 14
// nvi ?, NVI - Nova Versão Internacional

[[v44-14-1]]

^<<v44-14-1,1>>^ Em Icônio, Paulo e Barnabé, como de costume, foram à sinagoga judaica. Ali falaram de tal modo que veio a crer grande multidão de judeus e gentios.

[[v44-14-2]]

^<<v44-14-2,2>>^ Mas os judeus que se tinham recusado a crer incitaram os gentios e irritaram-lhes os ânimos contra os irmãos.

[[v44-14-3]]

^<<v44-14-3,3>>^ Paulo e Barnabé passaram bastante tempo ali, falando corajosamente do Senhor, que confirmava a mensagem de sua graça realizando sinais e maravilhas pelas mãos deles.

[[v44-14-4]]

^<<v44-14-4,4>>^ O povo da cidade ficou dividido: alguns estavam a favor dos judeus, outros a favor dos apóstolos.

[[v44-14-5]]

^<<v44-14-5,5>>^ Formou-se uma conspiração de gentios e judeus, juntamente com os seus líderes, para maltratá-los e apedrejá-los.

[[v44-14-6]]

^<<v44-14-6,6>>^ Quando eles souberam disso, fugiram para as cidades licaônicas de Listra e Derbe, e seus arredores,

[[v44-14-7]]

^<<v44-14-7,7>>^ onde continuaram a pregar as boas novas.

[[v44-14-8]]

^<<v44-14-8,8>>^ Em Listra havia um homem paralítico dos pés, aleijado desde o nascimento, que vivia ali sentado e nunca tinha andado.

[[v44-14-9]]

^<<v44-14-9,9>>^ Ele ouvira Paulo falar. Quando Paulo olhou diretamente para ele e viu que o homem tinha fé para ser curado,

[[v44-14-10]]

^<<v44-14-10,10>>^ disse em alta voz: "Levante-se! Fique de pé! " Com isso, o homem deu um salto e começou a andar.

[[v44-14-11]]

^<<v44-14-11,11>>^ Ao ver o que Paulo fizera, a multidão começou a gritar em língua licaônica: "Os deuses desceram até nós em forma humana! "

[[v44-14-12]]

^<<v44-14-12,12>>^ A Barnabé chamavam Zeus e a Paulo Hermes, porque era ele quem trazia a palavra.

[[v44-14-13]]

^<<v44-14-13,13>>^ O sacerdote de Zeus, cujo templo ficava diante da cidade, trouxe bois e coroas de flores à porta da cidade, porque ele e a multidão queriam oferecer-lhes sacrifícios.

[[v44-14-14]]

^<<v44-14-14,14>>^ Ouvindo isso, os apóstolos Barnabé e Paulo rasgaram as roupas e correram para o meio da multidão, gritando:

[[v44-14-15]]

^<<v44-14-15,15>>^ "Homens, por que vocês estão fazendo isso? Nós também somos humanos como vocês. Estamos trazendo boas novas para vocês, dizendo-lhes que se afastem dessas coisas vãs e se voltem para o Deus vivo, que fez o céu, a terra, o mar e tudo o que neles há.

[[v44-14-16]]

^<<v44-14-16,16>>^ No passado ele permitiu que todas as nações seguissem os seus próprios caminhos.

[[v44-14-17]]

^<<v44-14-17,17>>^ Contudo, não ficou sem testemunho: mostrou sua bondade, dando-lhes chuva do céu e colheitas no tempo certo, concedendo-lhes sustento com fartura e enchendo de alegria os seus corações".

[[v44-14-18]]

^<<v44-14-18,18>>^ Apesar dessas palavras, eles tiveram dificuldade para impedir que a multidão lhes oferecesse sacrifícios.

[[v44-14-19]]

^<<v44-14-19,19>>^ Então alguns judeus chegaram de Antioquia e de Icônio e mudaram o ânimo das multidões. Apedrejaram Paulo e o arrastaram para fora da cidade, pensando que estivesse morto.

[[v44-14-20]]

^<<v44-14-20,20>>^ Mas quando os discípulos se ajuntaram em volta de Paulo, ele se levantou e voltou à cidade. No dia seguinte, ele e Barnabé partiram para Derbe.

[[v44-14-21]]

^<<v44-14-21,21>>^ Eles pregaram as boas novas naquela cidade e fizeram muitos discípulos. Então voltaram para Listra, Icônio e Antioquia,

[[v44-14-22]]

^<<v44-14-22,22>>^ fortalecendo os discípulos e encorajando-os a permanecer na fé, dizendo: "É necessário que passemos por muitas tribulações para entrarmos no Reino de Deus".

[[v44-14-23]]

^<<v44-14-23,23>>^ Paulo e Barnabé designaram-lhes presbíteros em cada igreja; tendo orado e jejuado, eles os encomendaram ao Senhor, em quem haviam confiado.

[[v44-14-24]]

^<<v44-14-24,24>>^ Passando pela Pisídia, chegaram à Panfília

[[v44-14-25]]

^<<v44-14-25,25>>^ e, tendo pregado a palavra em Perge, desceram para Atália.

[[v44-14-26]]

^<<v44-14-26,26>>^ De Atália navegaram de volta a Antioquia, onde tinham sido recomendados à graça de Deus para a missão que agora haviam completado.

[[v44-14-27]]

^<<v44-14-27,27>>^ Chegando ali, reuniram a igreja e relataram tudo o que Deus tinha feito por meio deles e como abrira a porta da fé aos gentios.

[[v44-14-28]]

^<<v44-14-28,28>>^ E ficaram ali muito tempo com os discípulos.

'''

xref:044-atos/044-atos-013.adoc#v44-13-0[&#60; Capítulo Anterior] | <<v44-14-0,Topo>> | xref:044-atos/044-atos-015.adoc#v44-15-0[Próximo Capítulo &#62;]