include::./index.adoc[]

[[v44-7-0]]
=== Atos, 7
// nvi ?, NVI - Nova Versão Internacional

[[v44-7-1]]

^<<v44-7-1,1>>^ Então o sumo sacerdote perguntou a Estêvão: "São verdadeiras estas acusações? "

[[v44-7-2]]

^<<v44-7-2,2>>^ A isso ele respondeu: "Irmãos e pais, ouçam-me! O Deus glorioso apareceu a Abraão, nosso pai, estando ele ainda na Mesopotâmia, antes de morar em Harã, e lhe disse:

[[v44-7-3]]

^<<v44-7-3,3>>^ ‘Saia da sua terra e do meio dos seus parentes e vá para a terra que eu lhe mostrarei’.

[[v44-7-4]]

^<<v44-7-4,4>>^ "Então, ele saiu da terra dos caldeus e se estabeleceu em Harã. Depois da morte de seu pai, Deus o trouxe a esta terra, onde vocês agora vivem.

[[v44-7-5]]

^<<v44-7-5,5>>^ Deus não lhe deu nenhuma herança aqui, nem mesmo o espaço de um pé. Mas lhe prometeu que ele e, depois dele, seus descendentes, possuiriam a terra, embora, naquele tempo, Abraão não tivesse filhos.

[[v44-7-6]]

^<<v44-7-6,6>>^ Deus lhe falou desta forma: ‘Seus descendentes serão peregrinos numa terra estrangeira, e serão escravizados e maltratados por quatrocentos anos.

[[v44-7-7]]

^<<v44-7-7,7>>^ Mas eu castigarei a nação a quem servirão como escravos, e depois sairão dali e me adorarão neste lugar’.

[[v44-7-8]]

^<<v44-7-8,8>>^ E deu a Abraão a aliança da circuncisão. Por isso, Abraão gerou Isaque e o circuncidou oito dias depois do seu nascimento. Mais tarde, Isaque gerou Jacó, e este os doze patriarcas.

[[v44-7-9]]

^<<v44-7-9,9>>^ "Os patriarcas, tendo inveja de José, venderam-no como escravo para o Egito. Mas Deus estava com ele

[[v44-7-10]]

^<<v44-7-10,10>>^ e o libertou de todas as suas tribulações, dando a José favor e sabedoria diante do faraó, rei do Egito; este o tornou governador do Egito e de todo o seu palácio.

[[v44-7-11]]

^<<v44-7-11,11>>^ "Depois houve fome em todo o Egito e em Canaã, trazendo consigo grande sofrimento, e os nossos antepassados não encontravam alimento.

[[v44-7-12]]

^<<v44-7-12,12>>^ Ouvindo que havia trigo no Egito, Jacó enviou nossos antepassados em sua primeira viagem.

[[v44-7-13]]

^<<v44-7-13,13>>^ Na segunda viagem deles, José fez-se reconhecer por seus irmãos, e o faraó pôde conhecer a família de José.

[[v44-7-14]]

^<<v44-7-14,14>>^ Depois disso, José mandou buscar seu pai Jacó e toda a sua família, que eram setenta e cinco pessoas.

[[v44-7-15]]

^<<v44-7-15,15>>^ Então Jacó desceu ao Egito, onde faleceram ele e os nossos antepassados.

[[v44-7-16]]

^<<v44-7-16,16>>^ Seus corpos foram levados de volta a Siquém e colocados no túmulo que Abraão havia comprado ali dos filhos de Hamor, por certa quantia.

[[v44-7-17]]

^<<v44-7-17,17>>^ "Ao se aproximar o tempo em que Deus cumpriria sua promessa a Abraão, aumentou muito o número do nosso povo no Egito.

[[v44-7-18]]

^<<v44-7-18,18>>^ Então outro rei, que nada sabia a respeito de José, passou a governar o Egito.

[[v44-7-19]]

^<<v44-7-19,19>>^ Ele agiu traiçoeiramente para com o nosso povo e oprimiu os nossos antepassados, obrigando-os a abandonar os seus recém-nascidos, para que não sobrevivessem.

[[v44-7-20]]

^<<v44-7-20,20>>^ "Naquele tempo nasceu Moisés, que era um menino extraordinário. Por três meses ele foi criado na casa de seu pai.

[[v44-7-21]]

^<<v44-7-21,21>>^ Quando foi abandonado, a filha do faraó o tomou e o criou como seu próprio filho.

[[v44-7-22]]

^<<v44-7-22,22>>^ Moisés foi educado em toda a sabedoria dos egípcios e veio a ser poderoso em palavras e obras.

[[v44-7-23]]

^<<v44-7-23,23>>^ "Ao completar quarenta anos, Moisés decidiu visitar seus irmãos israelitas.

[[v44-7-24]]

^<<v44-7-24,24>>^ Ao ver um deles sendo maltratado por um egípcio, saiu em defesa do oprimido e o vingou, matando o egípcio.

[[v44-7-25]]

^<<v44-7-25,25>>^ Ele pensava que seus irmãos compreenderiam que Deus o estava usando para salvá-los, mas eles não o compreenderam.

[[v44-7-26]]

^<<v44-7-26,26>>^ No dia seguinte, Moisés dirigiu-se a dois israelitas que estavam brigando, e tentou reconciliá-los, dizendo: ‘Homens, vocês são irmãos; por que ferem um ao outro? ’

[[v44-7-27]]

^<<v44-7-27,27>>^ "Mas o homem que maltratava o outro empurrou Moisés e disse: ‘Quem o nomeou líder e juiz sobre nós?

[[v44-7-28]]

^<<v44-7-28,28>>^ Quer matar-me como matou o egípcio ontem? ’

[[v44-7-29]]

^<<v44-7-29,29>>^ Ouvindo isso, Moisés fugiu para Midiã, onde ficou morando como estrangeiro e teve dois filhos.

[[v44-7-30]]

^<<v44-7-30,30>>^ "Passados quarenta anos, apareceu a Moisés um anjo nas labaredas de uma sarça em chamas no deserto, perto do monte Sinai.

[[v44-7-31]]

^<<v44-7-31,31>>^ Vendo aquilo, ficou atônito. E, aproximando-se para observar, ouviu a voz do Senhor:

[[v44-7-32]]

^<<v44-7-32,32>>^ ‘Eu sou o Deus dos seus antepassados, o Deus de Abraão, o Deus de Isaque e o Deus de Jacó’. Moisés, tremendo de medo, não ousava olhar.

[[v44-7-33]]

^<<v44-7-33,33>>^ "Então o Senhor lhe disse: ‘Tire as sandálias dos pés, porque o lugar em que você está é terra santa.

[[v44-7-34]]

^<<v44-7-34,34>>^ De fato tenho visto a opressão sobre o meu povo no Egito. Ouvi seus gemidos e desci para livrá-lo. Venha agora, e eu o enviarei de volta ao Egito’.

[[v44-7-35]]

^<<v44-7-35,35>>^ "Este é o mesmo Moisés que tinham rejeitado com estas palavras: ‘Quem o nomeou líder e juiz? ’ Ele foi enviado pelo próprio Deus para ser líder e libertador deles, por meio do anjo que lhe tinha aparecido na sarça.

[[v44-7-36]]

^<<v44-7-36,36>>^ Ele os tirou de lá, fazendo maravilhas e sinais no Egito, no mar Vermelho e no deserto durante quarenta anos.

[[v44-7-37]]

^<<v44-7-37,37>>^ "Este é aquele Moisés que disse aos israelitas: ‘Deus lhes levantará dentre seus irmãos um profeta como eu’.

[[v44-7-38]]

^<<v44-7-38,38>>^ Ele estava na congregação, no deserto, com o anjo que lhe falava no monte Sinai e com os nossos antepassados, e recebeu palavras vivas, para transmiti-las a nós.

[[v44-7-39]]

^<<v44-7-39,39>>^ "Mas nossos antepassados se recusaram a obedecer-lhe; pelo contrário, rejeitaram-no, e em seus corações voltaram para o Egito.

[[v44-7-40]]

^<<v44-7-40,40>>^ Disseram a Arão: ‘Faça para nós deuses que nos conduzam, pois a esse Moisés que nos tirou do Egito, não sabemos o que lhe aconteceu! ’

[[v44-7-41]]

^<<v44-7-41,41>>^ Naquela ocasião fizeram um ídolo em forma de bezerro. Trouxeram-lhe sacrifícios e fizeram uma celebração em honra ao que suas mãos tinham feito.

[[v44-7-42]]

^<<v44-7-42,42>>^ Mas Deus afastou-se deles e os entregou à adoração dos astros, conforme o que foi escrito no livro dos profetas: ‘Foi a mim que vocês apresentaram sacrifícios e ofertas durante os quarenta anos no deserto, Ó nação de Israel?

[[v44-7-43]]

^<<v44-7-43,43>>^ Ao invés disso, levantaram o santuário de Moloque e a estrela do seu deus Renfã, ídolos que vocês fizeram para adorar! Portanto, eu os enviarei para o exílio, para além da Babilônia’.

[[v44-7-44]]

^<<v44-7-44,44>>^ "No deserto os nossos antepassados tinham o tabernáculo da aliança, que fora feito segundo a ordem de Deus a Moisés, de acordo com o modelo que ele tinha visto.

[[v44-7-45]]

^<<v44-7-45,45>>^ Tendo recebido o tabernáculo, nossos antepassados o levaram, sob a liderança de Josué, quando tomaram a terra das nações que Deus expulsou de diante deles. Esse tabernáculo permaneceu na terra até a época de Davi,

[[v44-7-46]]

^<<v44-7-46,46>>^ que encontrou graça diante de Deus e pediu que ele lhe permitisse providenciar uma habitação para o Deus de Jacó.

[[v44-7-47]]

^<<v44-7-47,47>>^ Mas foi Salomão quem lhe construiu a casa.

[[v44-7-48]]

^<<v44-7-48,48>>^ "Todavia, o Altíssimo não habita em casas feitas por homens. Como diz o profeta:

[[v44-7-49]]

^<<v44-7-49,49>>^ ‘O céu é o meu trono, e a terra, o estrado dos meus pés. Que espécie de casa vocês me edificarão? diz o Senhor, ou onde seria meu lugar de descanso?

[[v44-7-50]]

^<<v44-7-50,50>>^ Não foram as minhas mãos que fizeram todas estas coisas? ’

[[v44-7-51]]

^<<v44-7-51,51>>^ "Povo rebelde, obstinado de coração e de ouvidos! Vocês são iguais aos seus antepassados: sempre resistem ao Espírito Santo!

[[v44-7-52]]

^<<v44-7-52,52>>^ Qual dos profetas os seus antepassados não perseguiram? Eles mataram aqueles que prediziam a vinda do Justo, de quem agora vocês se tornaram traidores e assassinos —

[[v44-7-53]]

^<<v44-7-53,53>>^ vocês, que receberam a Lei por intermédio de anjos, mas não lhe obedeceram".

[[v44-7-54]]

^<<v44-7-54,54>>^ Ouvindo isso, ficavam furiosos e rangiam os dentes contra ele.

[[v44-7-55]]

^<<v44-7-55,55>>^ Mas Estêvão, cheio do Espírito Santo, levantou os olhos para o céu e viu a glória de Deus, e Jesus de pé, à direita de Deus,

[[v44-7-56]]

^<<v44-7-56,56>>^ e disse: "Vejo o céu aberto e o Filho do homem de pé, à direita de Deus".

[[v44-7-57]]

^<<v44-7-57,57>>^ Mas eles taparam os ouvidos e, gritando bem alto, lançaram-se todos juntos contra ele,

[[v44-7-58]]

^<<v44-7-58,58>>^ arrastaram-no para fora da cidade e começaram a apedrejá-lo. As testemunhas deixaram seus mantos aos pés de um jovem chamado Saulo.

[[v44-7-59]]

^<<v44-7-59,59>>^ Enquanto apedrejavam Estêvão, este orava: "Senhor Jesus, recebe o meu espírito".

[[v44-7-60]]

^<<v44-7-60,60>>^ Então caiu de joelhos e bradou: "Senhor, não os consideres culpados deste pecado". E, dizendo isso, adormeceu.

'''

xref:044-atos/044-atos-006.adoc#v44-6-0[&#60; Capítulo Anterior] | <<v44-7-0,Topo>> | xref:044-atos/044-atos-008.adoc#v44-8-0[Próximo Capítulo &#62;]