include::./index.adoc[]

[[v44-1-0]]
=== Atos, 1
// nvi ?, NVI - Nova Versão Internacional

[[v44-1-1]]

^<<v44-1-1,1>>^ Em meu livro anterior, Teófilo, escrevi a respeito de tudo o que Jesus começou a fazer e a ensinar,

[[v44-1-2]]

^<<v44-1-2,2>>^ até o dia em que foi elevado ao céu, depois de ter dado instruções por meio do Espírito Santo aos apóstolos que havia escolhido.

[[v44-1-3]]

^<<v44-1-3,3>>^ Depois do seu sofrimento, Jesus apresentou-se a eles e deu-lhes muitas provas indiscutíveis de que estava vivo. Apareceu-lhes por um período de quarenta dias falando-lhes acerca do Reino de Deus.

[[v44-1-4]]

^<<v44-1-4,4>>^ Certa ocasião, enquanto comia com eles, deu-lhes esta ordem: "Não saiam de Jerusalém, mas esperem pela promessa de meu Pai, da qual lhes falei.

[[v44-1-5]]

^<<v44-1-5,5>>^ Pois João batizou com água, mas dentro de poucos dias vocês serão batizados com o Espírito Santo".

[[v44-1-6]]

^<<v44-1-6,6>>^ Então os que estavam reunidos lhe perguntaram: "Senhor, é neste tempo que vais restaurar o reino a Israel? "

[[v44-1-7]]

^<<v44-1-7,7>>^ Ele lhes respondeu: "Não lhes compete saber os tempos ou as datas que o Pai estabeleceu pela sua própria autoridade.

[[v44-1-8]]

^<<v44-1-8,8>>^ Mas receberão poder quando o Espírito Santo descer sobre vocês, e serão minhas testemunhas em Jerusalém, em toda a Judéia e Samaria, e até os confins da terra".

[[v44-1-9]]

^<<v44-1-9,9>>^ Tendo dito isso, foi elevado às alturas enquanto eles olhavam, e uma nuvem o encobriu da vista deles.

[[v44-1-10]]

^<<v44-1-10,10>>^ E eles ficaram com os olhos fixos no céu enquanto ele subia. De repente surgiram diante deles dois homens vestidos de branco,

[[v44-1-11]]

^<<v44-1-11,11>>^ que lhes disseram: "Galileus, por que vocês estão olhando para o céu? Este mesmo Jesus, que dentre vocês foi elevado ao céu, voltará da mesma forma como o viram subir".

[[v44-1-12]]

^<<v44-1-12,12>>^ Então eles voltaram para Jerusalém, vindo do monte chamado das Oliveiras, que fica perto da cidade, cerca de um quilômetro.

[[v44-1-13]]

^<<v44-1-13,13>>^ Quando chegaram, subiram ao aposento onde estavam hospedados. Achavam-se presentes Pedro, João, Tiago e André; Filipe, Tomé, Bartolomeu e Mateus; Tiago, filho de Alfeu, Simão, o zelote, e Judas, filho de Tiago.

[[v44-1-14]]

^<<v44-1-14,14>>^ Todos eles se reuniam sempre em oração, com as mulheres, inclusive Maria, a mãe de Jesus, e com os irmãos de Jesus.

[[v44-1-15]]

^<<v44-1-15,15>>^ Naqueles dias Pedro levantou-se entre os irmãos, um grupo de cerca de cento e vinte pessoas,

[[v44-1-16]]

^<<v44-1-16,16>>^ e disse: "Irmãos, era necessário que se cumprisse a Escritura que o Espírito Santo predisse por boca de Davi, a respeito de Judas, que serviu de guia aos que prenderam Jesus.

[[v44-1-17]]

^<<v44-1-17,17>>^ Ele foi contado como um dos nossos e teve participação neste ministério".

[[v44-1-18]]

^<<v44-1-18,18>>^ ( Com a recompensa que recebeu pelo seu pecado, Judas comprou um campo. Ali caiu de cabeça, seu corpo partiu-se ao meio, e as suas vísceras se derramaram.

[[v44-1-19]]

^<<v44-1-19,19>>^ Todos em Jerusalém ficaram sabendo disso, de modo que, na língua deles, esse campo passou a chamar-se Aceldama, isto é, campo de Sangue. )

[[v44-1-20]]

^<<v44-1-20,20>>^ "Porque", prosseguiu Pedro, "está escrito no Livro de Salmos: ‘Fique deserto o seu lugar, e não haja ninguém que nele habite’; e ainda: ‘Que outro ocupe o seu lugar’.

[[v44-1-21]]

^<<v44-1-21,21>>^ Portanto, é necessário que escolhamos um dos homens que estiveram conosco durante todo o tempo em que o Senhor Jesus viveu entre nós,

[[v44-1-22]]

^<<v44-1-22,22>>^ desde o batismo de João até o dia em que Jesus foi elevado dentre nós às alturas. É preciso que um deles seja conosco testemunha de sua ressurreição".

[[v44-1-23]]

^<<v44-1-23,23>>^ Então indicaram dois nomes: José, chamado Barsabás, também conhecido como Justo, e Matias.

[[v44-1-24]]

^<<v44-1-24,24>>^ Depois oraram: "Senhor, tu conheces o coração de todos. Mostra-nos qual destes dois tens escolhido

[[v44-1-25]]

^<<v44-1-25,25>>^ para assumir este ministério apostólico que Judas abandonou, indo para o lugar que lhe era devido".

[[v44-1-26]]

^<<v44-1-26,26>>^ Então tiraram sortes, e a sorte caiu sobre Matias; assim, ele foi acrescentado aos onze apóstolos.

'''

xref:043-joao/043-joao-021.adoc#v43-21-0[&#60; Capítulo Anterior] | <<v44-1-0,Topo>> | xref:044-atos/044-atos-002.adoc#v44-2-0[Próximo Capítulo &#62;]