include::./index.adoc[]

[[v44-23-0]]
=== Atos, 23
// nvi ?, NVI - Nova Versão Internacional

[[v44-23-1]]

^<<v44-23-1,1>>^ Paulo, fixando os olhos no Sinédrio, disse: "Meus irmãos, tenho cumprido meu dever para com Deus com toda a boa consciência, até o dia de hoje".

[[v44-23-2]]

^<<v44-23-2,2>>^ Diante disso o sumo sacerdote Ananias deu ordens aos que estavam perto de Paulo para que lhe batessem na boca.

[[v44-23-3]]

^<<v44-23-3,3>>^ Então Paulo lhe disse: "Deus te ferirá, parede branqueada! Estás aí sentado para me julgar conforme a lei, mas contra a lei me mandas ferir? "

[[v44-23-4]]

^<<v44-23-4,4>>^ Os que estavam perto de Paulo disseram: "Você ousa insultar o sumo sacerdote de Deus? "

[[v44-23-5]]

^<<v44-23-5,5>>^ Paulo respondeu: "Irmãos, eu não sabia que ele era o sumo sacerdote, pois está escrito: ‘Não fale mal de uma autoridade do seu povo’ ".

[[v44-23-6]]

^<<v44-23-6,6>>^ Então Paulo, sabendo que alguns deles eram saduceus e os outros fariseus, bradou no Sinédrio: "Irmãos, sou fariseu, filho de fariseu. Estou sendo julgado por causa da minha esperança na ressurreição dos mortos! "

[[v44-23-7]]

^<<v44-23-7,7>>^ Dizendo isso, surgiu uma violenta discussão entre os fariseus e os saduceus, e a assembléia ficou dividida.

[[v44-23-8]]

^<<v44-23-8,8>>^ ( Os saduceus dizem que não há ressurreição nem anjos nem espíritos, mas os fariseus admitem todas essas coisas. )

[[v44-23-9]]

^<<v44-23-9,9>>^ Houve um grande alvoroço, e alguns dos mestres da lei que eram fariseus se levantaram e começaram a discutir intensamente, dizendo: "Não encontramos nada de errado neste homem. Quem sabe se algum espírito ou anjo falou com ele? "

[[v44-23-10]]

^<<v44-23-10,10>>^ A discussão tornou-se tão violenta que o comandante teve medo que Paulo fosse despedaçado por eles. Então ordenou que as tropas descessem e o retirassem à força do meio deles, levando-o para a fortaleza.

[[v44-23-11]]

^<<v44-23-11,11>>^ Na noite seguinte o Senhor, pondo-se ao lado dele, disse: "Coragem! Assim como você testemunhou a meu respeito em Jerusalém, deverá testemunhar também em Roma".

[[v44-23-12]]

^<<v44-23-12,12>>^ Na manhã seguinte os judeus tramaram uma conspiração e juraram solenemente que não comeriam nem beberiam enquanto não matassem Paulo.

[[v44-23-13]]

^<<v44-23-13,13>>^ Mais de quarenta homens estavam envolvidos nessa conspiração.

[[v44-23-14]]

^<<v44-23-14,14>>^ E, dirigindo-se aos chefes dos sacerdotes e aos líderes dos judeus, disseram: "Juramos solenemente, sob maldição, que não comeremos nada enquanto não matarmos Paulo.

[[v44-23-15]]

^<<v44-23-15,15>>^ Agora, portanto, vocês e o Sinédrio peçam ao comandante que o faça comparecer diante de vocês com o pretexto de obter informações mais exatas sobre o seu caso. Estaremos prontos para matá-lo antes que ele chegue aqui".

[[v44-23-16]]

^<<v44-23-16,16>>^ Entretanto, o sobrinho de Paulo, filho de sua irmã, teve conhecimento dessa conspiração, foi à fortaleza e contou tudo a Paulo,

[[v44-23-17]]

^<<v44-23-17,17>>^ que, chamando um dos centuriões, disse: "Leve este rapaz ao comandante; ele tem algo para lhe dizer".

[[v44-23-18]]

^<<v44-23-18,18>>^ Assim ele o levou ao comandante. Então disse o centurião: "Paulo, o prisioneiro, chamou-me, pediu-me que te trouxesse este rapaz, pois ele tem algo para te falar".

[[v44-23-19]]

^<<v44-23-19,19>>^ O comandante tomou o rapaz pela mão, levou-o à parte e perguntou: "Que você tem para me dizer? "

[[v44-23-20]]

^<<v44-23-20,20>>^ Ele respondeu: "Os judeus planejaram pedir-te que apresentes Paulo ao Sinédrio amanhã, sob pretexto de buscar informações mais exatas a respeito dele.

[[v44-23-21]]

^<<v44-23-21,21>>^ Não te deixes convencer, pois mais de quarenta deles estão preparando uma emboscada contra Paulo. Eles juraram solenemente não comer nem beber enquanto não o matarem. Estão preparados agora, esperando que prometas atender-lhes o pedido".

[[v44-23-22]]

^<<v44-23-22,22>>^ O comandante despediu o rapaz e recomendou-lhe: "Não diga a ninguém que você me contou isso".

[[v44-23-23]]

^<<v44-23-23,23>>^ Então ele chamou dois de seus centuriões e ordenou-lhes: "Preparem um destacamento de duzentos soldados, setenta cavaleiros e duzentos lanceiros a fim de irem para Cesaréia esta noite, às nove horas da noite.

[[v44-23-24]]

^<<v44-23-24,24>>^ Providenciem montarias para Paulo, e levem-no em segurança ao governador Félix".

[[v44-23-25]]

^<<v44-23-25,25>>^ O comandante escreveu uma carta nestes termos:

[[v44-23-26]]

^<<v44-23-26,26>>^ Cláudio Lísias, ao Excelentíssimo Governador Félix, Saudações.

[[v44-23-27]]

^<<v44-23-27,27>>^ Este homem foi preso pelos judeus, que estavam prestes a matá-lo quando eu, chegando com minhas tropas, o resgatei, pois soube que ele é cidadão romano.

[[v44-23-28]]

^<<v44-23-28,28>>^ Querendo saber por que o estavam acusando, levei-o ao Sinédrio deles.

[[v44-23-29]]

^<<v44-23-29,29>>^ Descobri que ele estava sendo acusado em questões acerca da lei deles, mas não havia contra ele nenhuma acusação que merecesse morte ou prisão.

[[v44-23-30]]

^<<v44-23-30,30>>^ Quando fui informado de que estava sendo preparada uma cilada contra ele, enviei-o imediatamente a Vossa Excelência. Também ordenei que os seus acusadores apresentassem a Vossa Excelência aquilo que têm contra ele.

[[v44-23-31]]

^<<v44-23-31,31>>^ Os soldados, cumprindo o seu dever, levaram Paulo durante a noite, e chegaram a Antipátride.

[[v44-23-32]]

^<<v44-23-32,32>>^ No dia seguinte deixaram a cavalaria prosseguir com ele, e voltaram para a fortaleza.

[[v44-23-33]]

^<<v44-23-33,33>>^ Quando a cavalaria chegou a Cesaréia, deu a carta ao governador e lhe entregou Paulo.

[[v44-23-34]]

^<<v44-23-34,34>>^ O governador leu a carta e perguntou de que província era ele. Informado de que era da Cilícia,

[[v44-23-35]]

^<<v44-23-35,35>>^ disse: "Ouvirei seu caso quando os seus acusadores chegarem aqui". Então ordenou que Paulo fosse mantido sob custódia no palácio de Herodes.

'''

xref:044-atos/044-atos-022.adoc#v44-22-0[&#60; Capítulo Anterior] | <<v44-23-0,Topo>> | xref:044-atos/044-atos-024.adoc#v44-24-0[Próximo Capítulo &#62;]