include::./index.adoc[]

[[v44-16-0]]
=== Atos, 16
// nvi ?, NVI - Nova Versão Internacional

[[v44-16-1]]

^<<v44-16-1,1>>^ Chegou a Derbe e depois a Listra, onde vivia um discípulo chamado Timóteo. Sua mãe era uma judia convertida e seu pai era grego.

[[v44-16-2]]

^<<v44-16-2,2>>^ Os irmãos de Listra e Icônio davam bom testemunho dele.

[[v44-16-3]]

^<<v44-16-3,3>>^ Paulo, querendo levá-lo na viagem, circuncidou-o por causa dos judeus que viviam naquela região, pois todos sabiam que seu pai era grego.

[[v44-16-4]]

^<<v44-16-4,4>>^ Nas cidades por onde passavam, transmitiam as decisões tomadas pelos apóstolos e presbíteros em Jerusalém, para que fossem obedecidas.

[[v44-16-5]]

^<<v44-16-5,5>>^ Assim as igrejas eram fortalecidas na fé e cresciam em número cada dia.

[[v44-16-6]]

^<<v44-16-6,6>>^ Paulo e seus companheiros viajaram pela região da Frígia e da Galácia, tendo sido impedidos pelo Espírito Santo de pregar a palavra na província da Ásia.

[[v44-16-7]]

^<<v44-16-7,7>>^ Quando chegaram à fronteira da Mísia, tentaram entrar na Bitínia, mas o Espírito de Jesus os impediu.

[[v44-16-8]]

^<<v44-16-8,8>>^ Então, contornaram a Mísia e desceram a Trôade.

[[v44-16-9]]

^<<v44-16-9,9>>^ Durante a noite Paulo teve uma visão, na qual um homem da Macedônia estava em pé e lhe suplicava: "Passe à Macedônia e ajude-nos".

[[v44-16-10]]

^<<v44-16-10,10>>^ Depois que Paulo teve essa visão, preparamo-nos imediatamente para partir para a Macedônia, concluindo que Deus nos tinha chamado para lhes pregar o evangelho.

[[v44-16-11]]

^<<v44-16-11,11>>^ Partindo de Trôade, navegamos diretamente para Samotrácia e, no dia seguinte, para Neápolis.

[[v44-16-12]]

^<<v44-16-12,12>>^ Dali partimos para Filipos, na Macedônia, que é colônia romana e a principal cidade daquele distrito. Ali ficamos vários dias.

[[v44-16-13]]

^<<v44-16-13,13>>^ No sábado saímos da cidade e fomos para a beira do rio, onde esperávamos encontrar um lugar de oração. Sentamo-nos e começamos a conversar com as mulheres que se haviam reunido ali.

[[v44-16-14]]

^<<v44-16-14,14>>^ Uma das que ouviam era uma mulher temente a Deus chamada Lídia, vendedora de tecido de púrpura, da cidade de Tiatira. O Senhor abriu seu coração para atender à mensagem de Paulo.

[[v44-16-15]]

^<<v44-16-15,15>>^ Tendo sido batizada, bem como os de sua casa, ela nos convidou, dizendo: "Se os senhores me consideram uma crente no Senhor, venham ficar em minha casa". E nos convenceu.

[[v44-16-16]]

^<<v44-16-16,16>>^ Certo dia, indo nós para o lugar de oração, encontramos uma escrava que tinha um espírito pelo qual predizia o futuro. Ela ganhava muito dinheiro para os seus senhores com adivinhações.

[[v44-16-17]]

^<<v44-16-17,17>>^ Essa moça seguia a Paulo e a nós, gritando: "Estes homens são servos do Deus Altíssimo e lhes anunciam o caminho da salvação".

[[v44-16-18]]

^<<v44-16-18,18>>^ Ela continuou fazendo isso por muitos dias. Finalmente, Paulo ficou indignado, voltou-se e disse ao espírito: "Em nome de Jesus Cristo eu lhe ordeno que saia dela! " No mesmo instante o espírito a deixou.

[[v44-16-19]]

^<<v44-16-19,19>>^ Percebendo que a sua esperança de lucro tinha se acabado, os donos da escrava agarraram Paulo e Silas e os arrastaram para a praça principal, diante das autoridades.

[[v44-16-20]]

^<<v44-16-20,20>>^ E, levando-os aos magistrados, disseram: "Estes homens são judeus e estão perturbando a nossa cidade,

[[v44-16-21]]

^<<v44-16-21,21>>^ propagando costumes que a nós, romanos, não é permitido aceitar nem praticar".

[[v44-16-22]]

^<<v44-16-22,22>>^ A multidão ajuntou-se contra Paulo e Silas, e os magistrados ordenaram que se lhes tirassem as roupas e fossem açoitados.

[[v44-16-23]]

^<<v44-16-23,23>>^ Depois de serem severamente açoitados, foram lançados na prisão. O carcereiro recebeu instrução para vigiá-los com cuidado.

[[v44-16-24]]

^<<v44-16-24,24>>^ Tendo recebido tais ordens, ele os lançou no cárcere interior e lhes prendeu os pés no tronco.

[[v44-16-25]]

^<<v44-16-25,25>>^ Por volta da meia-noite, Paulo e Silas estavam orando e cantando hinos a Deus; os outros presos os ouviam.

[[v44-16-26]]

^<<v44-16-26,26>>^ De repente, houve um terremoto tão violento que os alicerces da prisão foram abalados. Imediatamente todas as portas se abriram, e as correntes de todos se soltaram.

[[v44-16-27]]

^<<v44-16-27,27>>^ O carcereiro acordou e, vendo abertas as portas da prisão, desembainhou sua espada para se matar, porque pensava que os presos tivessem fugido.

[[v44-16-28]]

^<<v44-16-28,28>>^ Mas Paulo gritou: "Não faça isso! Estamos todos aqui! "

[[v44-16-29]]

^<<v44-16-29,29>>^ O carcereiro pediu luz, entrou correndo e, trêmulo, prostrou-se diante de Paulo e Silas.

[[v44-16-30]]

^<<v44-16-30,30>>^ Então levou-os para fora e perguntou: "Senhores, que devo fazer para ser salvo? "

[[v44-16-31]]

^<<v44-16-31,31>>^ Eles responderam: "Creia no Senhor Jesus, e serão salvos, você e os de sua casa".

[[v44-16-32]]

^<<v44-16-32,32>>^ E pregaram a palavra de Deus, a ele e a todos os de sua casa.

[[v44-16-33]]

^<<v44-16-33,33>>^ Naquela mesma hora da noite o carcereiro lavou as feridas deles; em seguida, ele e todos os seus foram batizados.

[[v44-16-34]]

^<<v44-16-34,34>>^ Então os levou para a sua casa, serviu-lhes uma refeição e com todos os de sua casa alegrou-se muito por haver crido em Deus.

[[v44-16-35]]

^<<v44-16-35,35>>^ Quando amanheceu, os magistrados mandaram os seus soldados ao carcereiro com esta ordem: "Solte estes homens".

[[v44-16-36]]

^<<v44-16-36,36>>^ O carcereiro disse a Paulo: "Os magistrados deram ordens para que você e Silas sejam libertados. Agora podem sair. Vão em paz".

[[v44-16-37]]

^<<v44-16-37,37>>^ Mas Paulo disse aos soldados: "Sendo nós cidadãos romanos, eles nos açoitaram publicamente sem processo formal e nos lançaram na prisão. E agora querem livrar-se de nós secretamente? Não! Venham eles mesmos e nos libertem".

[[v44-16-38]]

^<<v44-16-38,38>>^ Os soldados relataram isso aos magistrados, os quais, ouvindo que Paulo e Silas eram romanos, ficaram atemorizados.

[[v44-16-39]]

^<<v44-16-39,39>>^ Vieram para se desculpar diante deles e, conduzindo-os para fora da prisão, pediram-lhes que saíssem da cidade.

[[v44-16-40]]

^<<v44-16-40,40>>^ Depois de saírem da prisão, Paulo e Silas foram à casa de Lídia, onde se encontraram com os irmãos e os encorajaram. E então partiram.

'''

xref:044-atos/044-atos-015.adoc#v44-15-0[&#60; Capítulo Anterior] | <<v44-16-0,Topo>> | xref:044-atos/044-atos-017.adoc#v44-17-0[Próximo Capítulo &#62;]