include::./index.adoc[]

[[v44-6-0]]
=== Atos, 6
// nvi ?, NVI - Nova Versão Internacional

[[v44-6-1]]

^<<v44-6-1,1>>^ Naqueles dias, crescendo o número de discípulos, os judeus de fala grega entre eles queixaram-se dos judeus de fala hebraica, porque suas viúvas estavam sendo esquecidas na distribuição diária de alimento.

[[v44-6-2]]

^<<v44-6-2,2>>^ Por isso os Doze reuniram todos os discípulos e disseram: "Não é certo negligenciarmos o ministério da palavra de Deus, a fim de servir às mesas.

[[v44-6-3]]

^<<v44-6-3,3>>^ Irmãos, escolham entre vocês sete homens de bom testemunho, cheios do Espírito e de sabedoria. Passaremos a eles essa tarefa

[[v44-6-4]]

^<<v44-6-4,4>>^ e nos dedicaremos à oração e ao ministério da palavra".

[[v44-6-5]]

^<<v44-6-5,5>>^ Tal proposta agradou a todos. Então escolheram Estêvão, homem cheio de fé e do Espírito Santo, além de Filipe, Prócoro, Nicanor, Timom, Pármenas e Nicolau, um convertido ao judaísmo, proveniente de Antioquia.

[[v44-6-6]]

^<<v44-6-6,6>>^ Apresentaram esses homens aos apóstolos, os quais oraram e lhes impuseram as mãos.

[[v44-6-7]]

^<<v44-6-7,7>>^ Assim, a palavra de Deus se espalhava. Crescia rapidamente o número de discípulos em Jerusalém; também um grande número de sacerdotes obedecia à fé.

[[v44-6-8]]

^<<v44-6-8,8>>^ Estêvão, homem cheio da graça e do poder de Deus, realizava grandes maravilhas e sinais entre o povo.

[[v44-6-9]]

^<<v44-6-9,9>>^ Contudo, levantou-se oposição dos membros da chamada Sinagoga dos Libertos, dos judeus de Cirene e de Alexandria, bem como das províncias da Cilícia e da Ásia. Esses homens começaram a discutir com Estêvão,

[[v44-6-10]]

^<<v44-6-10,10>>^ mas não podiam resistir à sabedoria e ao Espírito com que ele falava.

[[v44-6-11]]

^<<v44-6-11,11>>^ Então subornaram alguns homens para dizerem: "Ouvimos Estêvão falar palavras blasfemas contra Moisés e contra Deus".

[[v44-6-12]]

^<<v44-6-12,12>>^ Com isso agitaram o povo, os líderes religiosos e os mestres da lei. E, prendendo Estêvão, levaram-no ao Sinédrio.

[[v44-6-13]]

^<<v44-6-13,13>>^ Ali apresentaram falsas testemunhas que diziam: "Este homem não pára de falar contra este lugar santo e contra a lei.

[[v44-6-14]]

^<<v44-6-14,14>>^ Pois o ouvimos dizer que esse Jesus, o Nazareno, destruirá este lugar e mudará os costumes que Moisés nos legou".

[[v44-6-15]]

^<<v44-6-15,15>>^ Olhando para ele, todos os que estavam sentados no Sinédrio viram que o seu rosto parecia o rosto de um anjo.

'''

xref:044-atos/044-atos-005.adoc#v44-5-0[&#60; Capítulo Anterior] | <<v44-6-0,Topo>> | xref:044-atos/044-atos-007.adoc#v44-7-0[Próximo Capítulo &#62;]