include::./index.adoc[]

[[v44-26-0]]
=== Atos, 26
// nvi ?, NVI - Nova Versão Internacional

[[v44-26-1]]

^<<v44-26-1,1>>^ Então Agripa disse a Paulo: "Você tem permissão para falar em sua defesa". A seguir, Paulo fez sinal com a mão e começou a sua defesa:

[[v44-26-2]]

^<<v44-26-2,2>>^ "Rei Agripa, considero-me feliz por poder estar hoje em tua presença, para fazer a minha defesa contra todas as acusações dos judeus,

[[v44-26-3]]

^<<v44-26-3,3>>^ e especialmente porque estás bem familiarizado com todos os costumes e controvérsias deles. Portanto, peço que me ouças pacientemente.

[[v44-26-4]]

^<<v44-26-4,4>>^ "Todos os judeus sabem como tenho vivido desde pequeno, tanto em minha terra natal como em Jerusalém.

[[v44-26-5]]

^<<v44-26-5,5>>^ Eles me conhecem há muito tempo e podem testemunhar, se quiserem, que, como fariseu, vivi de acordo com a seita mais severa da nossa religião.

[[v44-26-6]]

^<<v44-26-6,6>>^ Agora, estou sendo julgado por causa da minha esperança no que Deus prometeu aos nossos antepassados.

[[v44-26-7]]

^<<v44-26-7,7>>^ Esta é a promessa que as nossas doze tribos esperam que se cumpra, cultuando a Deus com fervor, dia e noite. É por causa desta esperança, ó rei, que estou sendo acusado pelos judeus.

[[v44-26-8]]

^<<v44-26-8,8>>^ Por que os senhores acham impossível que Deus ressuscite os mortos?

[[v44-26-9]]

^<<v44-26-9,9>>^ "Eu também estava convencido de que deveria fazer todo o possível para me opor ao nome de Jesus, o Nazareno.

[[v44-26-10]]

^<<v44-26-10,10>>^ E foi exatamente isso que fiz em Jerusalém. Com autorização dos chefes dos sacerdotes lancei muitos santos na prisão, e quando eles eram condenados à morte eu dava o meu voto contra eles.

[[v44-26-11]]

^<<v44-26-11,11>>^ Muitas vezes ia de uma sinagoga para outra a fim de castigá-los, e tentava forçá-los a blasfemar. Em minha fúria contra eles, cheguei a ir a cidades estrangeiras para persegui-los.

[[v44-26-12]]

^<<v44-26-12,12>>^ "Numa dessas viagens eu estava indo para Damasco, com autorização e permissão dos chefes dos sacerdotes.

[[v44-26-13]]

^<<v44-26-13,13>>^ Por volta do meio-dia, ó rei, estando eu a caminho, vi uma luz do céu, mais resplandecente que o sol, brilhando ao meu redor e ao redor dos que iam comigo.

[[v44-26-14]]

^<<v44-26-14,14>>^ Todos caímos por terra. Então ouvi uma voz que me dizia em aramaico. ‘Saulo, Saulo, por que você está me perseguindo? Resistir ao aguilhão só lhe trará dor! ’

[[v44-26-15]]

^<<v44-26-15,15>>^ "Então perguntei: Quem és tu, Senhor? "Respondeu o Senhor: ‘Sou Jesus, a quem você está perseguindo.

[[v44-26-16]]

^<<v44-26-16,16>>^ Agora, levante-se, fique de pé. Eu lhe apareci para constituí-lo servo e testemunha do que você viu a meu respeito e do que lhe mostrarei.

[[v44-26-17]]

^<<v44-26-17,17>>^ Eu o livrarei do seu próprio povo e dos gentios, aos quais eu o envio

[[v44-26-18]]

^<<v44-26-18,18>>^ para abrir-lhes os olhos e convertê-los das trevas para a luz, e do poder de Satanás para Deus, a fim de que recebam o perdão dos pecados e herança entre os que são santificados pela fé em mim’.

[[v44-26-19]]

^<<v44-26-19,19>>^ "Assim, rei Agripa, não fui desobediente à visão celestial.

[[v44-26-20]]

^<<v44-26-20,20>>^ Preguei em primeiro lugar aos que estavam em Damasco, depois aos que estavam em Jerusalém e em toda a Judéia, e também aos gentios, dizendo que se arrependessem e se voltassem para Deus, praticando obras que mostrassem o seu arrependimento.

[[v44-26-21]]

^<<v44-26-21,21>>^ Por isso os judeus me prenderam no pátio do templo e tentaram matar-me.

[[v44-26-22]]

^<<v44-26-22,22>>^ Mas tenho contado com a ajuda de Deus até o dia de hoje, e, por este motivo, estou aqui e dou testemunho tanto a gente simples como a gente importante. Não estou dizendo nada além do que os profetas e Moisés disseram que haveria de acontecer:

[[v44-26-23]]

^<<v44-26-23,23>>^ que o Cristo haveria de sofrer e, sendo o primeiro a ressuscitar dentre os mortos, proclamaria luz para o seu próprio povo e para os gentios".

[[v44-26-24]]

^<<v44-26-24,24>>^ A esta altura Festo interrompeu a defesa de Paulo e disse em alta voz: "Você está louco, Paulo! As muitas letras o estão levando à loucura! "

[[v44-26-25]]

^<<v44-26-25,25>>^ Respondeu Paulo: "Não estou louco, excelentíssimo Festo. O que estou dizendo é verdadeiro e de bom senso.

[[v44-26-26]]

^<<v44-26-26,26>>^ O rei está familiarizado com essas coisas, e lhe posso falar abertamente. Estou certo de que nada disso escapou do seu conhecimento, pois nada se passou num lugar qualquer.

[[v44-26-27]]

^<<v44-26-27,27>>^ Rei Agripa, crês nos profetas? Eu sei que sim".

[[v44-26-28]]

^<<v44-26-28,28>>^ Então Agripa disse a Paulo: "Você acha que em tão pouco tempo pode convencer-me a tornar-me cristão? "

[[v44-26-29]]

^<<v44-26-29,29>>^ Paulo respondeu: "Em pouco ou em muito, peço a Deus que não apenas tu, mas todos os que hoje me ouvem se tornem como eu, menos estas algemas".

[[v44-26-30]]

^<<v44-26-30,30>>^ O rei se levantou, e com ele o governador e Berenice, como também os que estavam assentados com eles.

[[v44-26-31]]

^<<v44-26-31,31>>^ Saindo do salão, comentavam entre si: "Este homem não fez nada que mereça morte ou prisão".

[[v44-26-32]]

^<<v44-26-32,32>>^ Agripa disse a Festo: "Ele poderia ser posto em liberdade, se não tivesse apelado para César".

'''

xref:044-atos/044-atos-025.adoc#v44-25-0[&#60; Capítulo Anterior] | <<v44-26-0,Topo>> | xref:044-atos/044-atos-027.adoc#v44-27-0[Próximo Capítulo &#62;]