include::./index.adoc[]

[[v44-18-0]]
=== Atos, 18
// nvi ?, NVI - Nova Versão Internacional

[[v44-18-1]]

^<<v44-18-1,1>>^ Depois disso Paulo saiu de Atenas e foi para Corinto.

[[v44-18-2]]

^<<v44-18-2,2>>^ Ali, encontrou um judeu chamado Áqüila, natural do Ponto, que havia chegado recentemente da Itália com Priscila, sua mulher, pois Cláudio havia ordenado que todos os judeus saíssem de Roma. Paulo foi vê-los

[[v44-18-3]]

^<<v44-18-3,3>>^ e, uma vez que tinham a mesma profissão, ficou morando e trabalhando com eles, pois eram fabricantes de tendas.

[[v44-18-4]]

^<<v44-18-4,4>>^ Todos os sábados ele debatia na sinagoga, e convencia judeus e gregos.

[[v44-18-5]]

^<<v44-18-5,5>>^ Depois que Silas e Timóteo chegaram da Macedônia, Paulo se dedicou exclusivamente à pregação, testemunhando aos judeus que Jesus era o Cristo.

[[v44-18-6]]

^<<v44-18-6,6>>^ Opondo-se eles e lançando maldições, Paulo sacudiu a roupa e lhes disse: "Caia sobre a cabeça de vocês o seu próprio sangue! Estou livre da minha responsabilidade. De agora em diante irei para os gentios".

[[v44-18-7]]

^<<v44-18-7,7>>^ Então Paulo saiu da sinagoga e foi para a casa de Tício Justo, que era temente a Deus e que morava ao lado da sinagoga.

[[v44-18-8]]

^<<v44-18-8,8>>^ Crispo, chefe da sinagoga, creu no Senhor, ele e toda a sua casa; e dos coríntios que o ouviam, muitos criam e eram batizados.

[[v44-18-9]]

^<<v44-18-9,9>>^ Certa noite o Senhor falou a Paulo em visão: "Não tenha medo, continue falando e não fique calado,

[[v44-18-10]]

^<<v44-18-10,10>>^ pois estou com você, e ninguém vai lhe fazer mal ou feri-lo, porque tenho muita gente nesta cidade".

[[v44-18-11]]

^<<v44-18-11,11>>^ Assim, Paulo ficou ali durante um ano e meio, ensinando-lhes a palavra de Deus.

[[v44-18-12]]

^<<v44-18-12,12>>^ Sendo Gálio procônsul da Acaia, os judeus fizeram em conjunto um levante contra Paulo e o levaram ao tribunal, fazendo a seguinte acusação:

[[v44-18-13]]

^<<v44-18-13,13>>^ "Este homem está persuadindo o povo a adorar a Deus de maneira contrária à lei".

[[v44-18-14]]

^<<v44-18-14,14>>^ Quando Paulo ia começar a falar, Gálio disse aos judeus: "Se vocês, judeus, estivessem apresentando queixa de algum delito ou crime grave, seria razoável que eu os ouvisse.

[[v44-18-15]]

^<<v44-18-15,15>>^ Mas, visto que se trata de uma questão de palavras e nomes de sua própria lei, resolvam o problema vocês mesmos. Não serei juiz dessas coisas".

[[v44-18-16]]

^<<v44-18-16,16>>^ E mandou expulsá-los do tribunal.

[[v44-18-17]]

^<<v44-18-17,17>>^ Então todos se voltaram contra Sóstenes, o chefe da sinagoga, e o espancaram diante do tribunal. Mas Gálio não demonstrava nenhuma preocupação com isso.

[[v44-18-18]]

^<<v44-18-18,18>>^ Paulo permaneceu em Corinto por algum tempo. Depois despediu-se dos irmãos e navegou para a Síria, acompanhado de Priscila e Áqüila. Antes de embarcar, rapou a cabeça em Cencréia, devido a um voto que havia feito.

[[v44-18-19]]

^<<v44-18-19,19>>^ Chegaram a Éfeso, onde Paulo deixou Priscila e Áqüila. Ele, porém, entrando na sinagoga, começou a debater com os judeus.

[[v44-18-20]]

^<<v44-18-20,20>>^ Pedindo eles que ficasse mais tempo, não cedeu.

[[v44-18-21]]

^<<v44-18-21,21>>^ Mas, ao partir, prometeu: "Voltarei, se for da vontade de Deus". Então, embarcando, partiu de Éfeso.

[[v44-18-22]]

^<<v44-18-22,22>>^ Ao chegar a Cesaréia, subiu até a igreja para saudá-la, e depois desceu para Antioquia.

[[v44-18-23]]

^<<v44-18-23,23>>^ Depois de passar algum tempo em Antioquia, Paulo partiu dali e viajou por toda a região da Galácia e da Frígia, fortalecendo todos os discípulos.

[[v44-18-24]]

^<<v44-18-24,24>>^ Enquanto isso, um judeu chamado Apolo, natural de Alexandria, chegou a Éfeso. Ele era homem culto e tinha grande conhecimento das Escrituras.

[[v44-18-25]]

^<<v44-18-25,25>>^ Fora instruído no caminho do Senhor e com grande fervor falava e ensinava com exatidão acerca de Jesus, embora conhecesse apenas o batismo de João.

[[v44-18-26]]

^<<v44-18-26,26>>^ Logo começou a falar corajosamente na sinagoga. Quando Priscila e Áqüila o ouviram, convidaram-no para ir à sua casa e lhe explicaram com mais exatidão o caminho de Deus.

[[v44-18-27]]

^<<v44-18-27,27>>^ Querendo ele ir para a Acaia, os irmãos o encorajaram e escreveram aos discípulos que o recebessem. Ao chegar, ele auxiliou muito os que pela graça haviam crido,

[[v44-18-28]]

^<<v44-18-28,28>>^ pois refutava vigorosamente os judeus em debate público, provando pelas Escrituras que Jesus é o Cristo.

'''

xref:044-atos/044-atos-017.adoc#v44-17-0[&#60; Capítulo Anterior] | <<v44-18-0,Topo>> | xref:044-atos/044-atos-019.adoc#v44-19-0[Próximo Capítulo &#62;]