include::./index.adoc[]

[[v44-3-0]]
=== Atos, 3
// nvi ?, NVI - Nova Versão Internacional

[[v44-3-1]]

^<<v44-3-1,1>>^ Certo dia Pedro e João estavam subindo ao templo na hora da oração, às três horas da tarde.

[[v44-3-2]]

^<<v44-3-2,2>>^ Estava sendo levado para a porta do templo chamada Formosa um aleijado de nascença, que ali era colocado todos os dias para pedir esmolas aos que entravam no templo.

[[v44-3-3]]

^<<v44-3-3,3>>^ Vendo que Pedro e João iam entrar no pátio do templo, pediu-lhes esmola.

[[v44-3-4]]

^<<v44-3-4,4>>^ Pedro e João olharam bem para ele e, então, Pedro disse: "Olhe para nós! "

[[v44-3-5]]

^<<v44-3-5,5>>^ O homem olhou para eles com atenção, esperando receber deles alguma coisa.

[[v44-3-6]]

^<<v44-3-6,6>>^ Disse Pedro: "Não tenho prata nem ouro, mas o que tenho, isto lhe dou. Em nome de Jesus Cristo, o Nazareno, ande".

[[v44-3-7]]

^<<v44-3-7,7>>^ Segurando-o pela mão direita, ajudou-o a levantar-se, e imediatamente os pés e os tornozelos do homem ficaram firmes.

[[v44-3-8]]

^<<v44-3-8,8>>^ E de um salto pôs-se de pé e começou a andar. Depois entrou com eles no pátio do templo, andando, saltando e louvando a Deus.

[[v44-3-9]]

^<<v44-3-9,9>>^ Quando todo o povo o viu andando e louvando a Deus,

[[v44-3-10]]

^<<v44-3-10,10>>^ reconheceu que era ele o mesmo homem que costumava mendigar sentado à porta do templo chamada Formosa. Todos ficaram perplexos e muito admirados com o que lhe tinha acontecido.

[[v44-3-11]]

^<<v44-3-11,11>>^ Apegando-se o mendigo a Pedro e João, todo o povo ficou maravilhado e correu até eles, ao lugar chamado Pórtico de Salomão.

[[v44-3-12]]

^<<v44-3-12,12>>^ Vendo isso, Pedro lhes disse: "Israelitas, por que isto os surpreende? Por que vocês estão olhando para nós, como se tivéssemos feito este homem andar por nosso próprio poder ou piedade?

[[v44-3-13]]

^<<v44-3-13,13>>^ O Deus de Abraão, de Isaque e de Jacó, o Deus dos nossos antepassados, glorificou seu servo Jesus, a quem vocês entregaram para ser morto e negaram perante Pilatos, embora ele tivesse decidido soltá-lo.

[[v44-3-14]]

^<<v44-3-14,14>>^ Vocês negaram publicamente o Santo e Justo e pediram que lhes fosse libertado um assassino.

[[v44-3-15]]

^<<v44-3-15,15>>^ Vocês mataram o autor da vida, mas Deus o ressuscitou dos mortos. E nós somos testemunhas disso.

[[v44-3-16]]

^<<v44-3-16,16>>^ Pela fé no nome de Jesus, o Nome curou este homem que vocês vêem e conhecem. A fé que vem por meio dele lhe deu esta saúde perfeita, como todos podem ver.

[[v44-3-17]]

^<<v44-3-17,17>>^ "Agora, irmãos, eu sei que vocês agiram por ignorância, bem como os seus líderes.

[[v44-3-18]]

^<<v44-3-18,18>>^ Mas foi assim que Deus cumpriu o que tinha predito por todos os profetas, dizendo que o seu Cristo haveria de sofrer.

[[v44-3-19]]

^<<v44-3-19,19>>^ Arrependam-se, pois, e voltem-se para Deus, para que os seus pecados sejam cancelados,

[[v44-3-20]]

^<<v44-3-20,20>>^ para que venham tempos de descanso da parte do Senhor, e ele mande o Cristo, o qual lhes foi designado, Jesus.

[[v44-3-21]]

^<<v44-3-21,21>>^ É necessário que ele permaneça no céu até que chegue o tempo em que Deus restaurará todas as coisas, como falou há muito tempo, por meio dos seus santos profetas.

[[v44-3-22]]

^<<v44-3-22,22>>^ Pois disse Moisés: ‘O Senhor Deus lhes levantará dentre seus irmãos um profeta como eu; ouçam-no em tudo o que ele lhes disser.

[[v44-3-23]]

^<<v44-3-23,23>>^ Quem não ouvir esse profeta, será eliminado do meio do seu povo’.

[[v44-3-24]]

^<<v44-3-24,24>>^ "De fato, todos os profetas, de Samuel em diante, um por um, falaram e predisseram estes dias.

[[v44-3-25]]

^<<v44-3-25,25>>^ E vocês são herdeiros dos profetas e da aliança que Deus fez com os seus antepassados. Ele disse a Abraão: ‘Por meio da sua descendência todos os povos da terra serão abençoados’.

[[v44-3-26]]

^<<v44-3-26,26>>^ Tendo Deus ressuscitado o seu Servo, enviou-o primeiramente a vocês, para abençoá-los, convertendo cada um de vocês das suas maldades".

'''

xref:044-atos/044-atos-002.adoc#v44-2-0[&#60; Capítulo Anterior] | <<v44-3-0,Topo>> | xref:044-atos/044-atos-004.adoc#v44-4-0[Próximo Capítulo &#62;]