include::./index.adoc[]

[[v44-13-0]]
=== Atos, 13
// nvi ?, NVI - Nova Versão Internacional

[[v44-13-1]]

^<<v44-13-1,1>>^ Na igreja de Antioquia havia profetas e mestres: Barnabé, Simeão, chamado Níger, Lúcio de Cirene, Manaém, que fora criado com Herodes, o tetrarca, e Saulo.

[[v44-13-2]]

^<<v44-13-2,2>>^ Enquanto adoravam ao Senhor e jejuavam, disse o Espírito Santo: "Separem-me Barnabé e Saulo para a obra a que os tenho chamado".

[[v44-13-3]]

^<<v44-13-3,3>>^ Assim, depois de jejuar e orar, impuseram-lhes as mãos e os enviaram.

[[v44-13-4]]

^<<v44-13-4,4>>^ Enviados pelo Espírito Santo, desceram a Selêucia e dali navegaram para Chipre.

[[v44-13-5]]

^<<v44-13-5,5>>^ Chegando em Salamina, proclamaram a palavra de Deus nas sinagogas judaicas. João estava com eles como auxiliar.

[[v44-13-6]]

^<<v44-13-6,6>>^ Viajaram por toda a ilha, até que chegaram a Pafos. Ali encontraram um judeu, chamado Barjesus, que praticava magia e era falso profeta.

[[v44-13-7]]

^<<v44-13-7,7>>^ Ele era assessor do procônsul Sérgio Paulo. O procônsul, sendo homem culto, mandou chamar Barnabé e Saulo, porque queria ouvir a palavra de Deus.

[[v44-13-8]]

^<<v44-13-8,8>>^ Mas Elimas, o mágico ( esse é o significado do seu nome ) opôs-se a eles e tentava desviar da fé o procônsul.

[[v44-13-9]]

^<<v44-13-9,9>>^ Então Saulo, também chamado Paulo, cheio do Espírito Santo, olhou firmemente para Elimas e disse:

[[v44-13-10]]

^<<v44-13-10,10>>^ "Filho do diabo e inimigo de tudo o que é justo! Você está cheio de toda espécie de engano e maldade. Quando é que vai parar de perverter os retos caminhos do Senhor?

[[v44-13-11]]

^<<v44-13-11,11>>^ Saiba agora que a mão do Senhor está contra você, e você ficará cego e incapaz de ver a luz do sol durante algum tempo". Imediatamente vieram sobre ele névoa e escuridão, e ele, tateando, procurava quem o guiasse pela mão.

[[v44-13-12]]

^<<v44-13-12,12>>^ O procônsul, vendo o que havia acontecido, creu, profundamente impressionado com o ensino do Senhor.

[[v44-13-13]]

^<<v44-13-13,13>>^ De Pafos, Paulo e seus companheiros navegaram para Perge, na Panfília. João os deixou ali e voltou para Jerusalém.

[[v44-13-14]]

^<<v44-13-14,14>>^ De Perge prosseguiram até Antioquia da Pisídia. No sábado, entraram na sinagoga e se assentaram.

[[v44-13-15]]

^<<v44-13-15,15>>^ Depois da leitura da Lei e dos Profetas, os chefes da sinagoga lhes mandaram dizer: "Irmãos, se vocês têm uma mensagem de encorajamento para o povo, falem".

[[v44-13-16]]

^<<v44-13-16,16>>^ Pondo-se de pé, Paulo fez sinal com a mão e disse: "Israelitas e gentios que temem a Deus, ouçam-me!

[[v44-13-17]]

^<<v44-13-17,17>>^ O Deus do povo de Israel escolheu nossos antepassados, e exaltou o povo durante a sua permanência no Egito; com grande poder os fez sair daquele país

[[v44-13-18]]

^<<v44-13-18,18>>^ e os aturou no deserto durante cerca de quarenta anos.

[[v44-13-19]]

^<<v44-13-19,19>>^ Ele destruiu sete nações em Canaã e deu a terra delas como herança ao seu povo.

[[v44-13-20]]

^<<v44-13-20,20>>^ Tudo isso levou cerca de quatrocentos e cinqüenta anos. "Depois disso, ele lhes deu juízes até o tempo do profeta Samuel.

[[v44-13-21]]

^<<v44-13-21,21>>^ Então o povo pediu um rei, e Deus lhes deu Saul, filho de Quis, da tribo de Benjamim, que reinou quarenta anos.

[[v44-13-22]]

^<<v44-13-22,22>>^ Depois de rejeitar Saul, levantou-lhes Davi como rei, sobre quem testemunhou: ‘Encontrei Davi, filho de Jessé, homem segundo o meu coração; ele fará tudo o que for da minha vontade’.

[[v44-13-23]]

^<<v44-13-23,23>>^ "Da descendência desse homem Deus trouxe a Israel o Salvador Jesus, como prometera.

[[v44-13-24]]

^<<v44-13-24,24>>^ Antes da vinda de Jesus, João pregou um batismo de arrependimento para todo o povo de Israel.

[[v44-13-25]]

^<<v44-13-25,25>>^ Quando estava completando sua carreira, João disse: ‘Quem vocês pensam que eu sou? Não sou quem vocês pensam. Mas eis que vem depois de mim aquele cujas sandálias não sou digno nem de desamarrar’.

[[v44-13-26]]

^<<v44-13-26,26>>^ "Irmãos, filhos de Abraão, e gentios que temem a Deus, a nós foi enviada esta mensagem de salvação.

[[v44-13-27]]

^<<v44-13-27,27>>^ O povo de Jerusalém e seus governantes não reconheceram Jesus, mas, ao condená-lo, cumpriram as palavras dos profetas, que são lidas todos os sábados.

[[v44-13-28]]

^<<v44-13-28,28>>^ Mesmo não achando motivo legal para uma sentença de morte, pediram a Pilatos que o mandasse executar.

[[v44-13-29]]

^<<v44-13-29,29>>^ Tendo cumprido tudo o que estava escrito a respeito dele, tiraram-no do madeiro e o colocaram num sepulcro.

[[v44-13-30]]

^<<v44-13-30,30>>^ Mas Deus o ressuscitou dos mortos,

[[v44-13-31]]

^<<v44-13-31,31>>^ e, por muitos dias, foi visto por aqueles que tinham ido com ele da Galiléia para Jerusalém. Eles agora são testemunhas dele para o povo.

[[v44-13-32]]

^<<v44-13-32,32>>^ "Nós lhes anunciamos as boas novas: o que Deus prometeu a nossos antepassados

[[v44-13-33]]

^<<v44-13-33,33>>^ ele cumpriu para nós, seus filhos, ressuscitando Jesus, como está escrito no Salmo segundo: ‘Tu és meu filho; eu hoje te gerei’.

[[v44-13-34]]

^<<v44-13-34,34>>^ O fato de que Deus o ressuscitou dos mortos, para que nunca entrasse em decomposição, é declarado nestas palavras: ‘Eu lhes dou as santas e fiéis bênçãos prometidas a Davi’.

[[v44-13-35]]

^<<v44-13-35,35>>^ Assim ele diz noutra passagem: ‘Não permitirás que o teu Santo sofra decomposição’.

[[v44-13-36]]

^<<v44-13-36,36>>^ "Tendo, pois, Davi servido ao propósito de Deus em sua geração, adormeceu, foi sepultado com os seus antepassados e seu corpo se decompôs.

[[v44-13-37]]

^<<v44-13-37,37>>^ Mas aquele a quem Deus ressuscitou não sofreu decomposição.

[[v44-13-38]]

^<<v44-13-38,38>>^ "Portanto, meus irmãos, quero que saibam que mediante Jesus lhes é proclamado o perdão dos pecados.

[[v44-13-39]]

^<<v44-13-39,39>>^ Por meio dele, todo aquele que crê é justificado de todas as coisas das quais não podiam ser justificados pela lei de Moisés.

[[v44-13-40]]

^<<v44-13-40,40>>^ Cuidem para que não lhes aconteça o que disseram os profetas:

[[v44-13-41]]

^<<v44-13-41,41>>^ ‘Olhem, escarnecedores, admirem-se e pereçam; pois nos dias de vocês farei algo que vocês jamais creriam se alguém lhes contasse! ’"

[[v44-13-42]]

^<<v44-13-42,42>>^ Quando Paulo e Barnabé estavam saindo da sinagoga, o povo os convidou a falar mais a respeito dessas coisas no sábado seguinte.

[[v44-13-43]]

^<<v44-13-43,43>>^ Despedida a congregação, muitos dos judeus e estrangeiros piedosos convertidos ao judaísmo seguiram Paulo e Barnabé. Estes conversavam com eles, recomendando-lhes que continuassem na graça de Deus.

[[v44-13-44]]

^<<v44-13-44,44>>^ No sábado seguinte, quase toda a cidade se reuniu para ouvir a palavra do Senhor.

[[v44-13-45]]

^<<v44-13-45,45>>^ Quando os judeus viram a multidão, ficaram cheios de inveja e, blasfemando, contradiziam o que Paulo estava dizendo.

[[v44-13-46]]

^<<v44-13-46,46>>^ Então Paulo e Barnabé lhes responderam corajosamente: "Era necessário anunciar primeiro a vocês a palavra de Deus; uma vez que a rejeitam e não se julgam dignos da vida eterna, agora nos voltamos para os gentios.

[[v44-13-47]]

^<<v44-13-47,47>>^ Pois assim o Senhor nos ordenou: ‘Eu fiz de você luz para os gentios, para que você leve a salvação até aos confins da terra’ ".

[[v44-13-48]]

^<<v44-13-48,48>>^ Ouvindo isso, os gentios alegraram-se e bendisseram a palavra do Senhor; e creram todos os que haviam sido designados para a vida eterna.

[[v44-13-49]]

^<<v44-13-49,49>>^ A palavra do Senhor se espalhava por toda a região.

[[v44-13-50]]

^<<v44-13-50,50>>^ Mas os judeus incitaram as mulheres piedosas de elevada posição e os principais da cidade. E, provocando perseguição contra Paulo e Barnabé, os expulsaram do seu território.

[[v44-13-51]]

^<<v44-13-51,51>>^ Estes sacudiram o pó dos seus pés em protesto contra eles e foram para Icônio.

[[v44-13-52]]

^<<v44-13-52,52>>^ Os discípulos continuavam cheios de alegria e do Espírito Santo.

'''

xref:044-atos/044-atos-012.adoc#v44-12-0[&#60; Capítulo Anterior] | <<v44-13-0,Topo>> | xref:044-atos/044-atos-014.adoc#v44-14-0[Próximo Capítulo &#62;]