include::./index.adoc[]

[[v44-21-0]]
=== Atos, 21
// nvi ?, NVI - Nova Versão Internacional

[[v44-21-1]]

^<<v44-21-1,1>>^ Depois de nos separarmos deles, embarcamos e navegamos diretamente para Cós. No dia seguinte fomos para Rodes, e dali até Pátara.

[[v44-21-2]]

^<<v44-21-2,2>>^ Encontrando um navio que ia fazer a travessia para a Fenícia, embarcamos nele e partimos.

[[v44-21-3]]

^<<v44-21-3,3>>^ Depois de avistarmos Chipre e seguirmos rumo sul, navegamos para a Síria. Desembarcamos em Tiro, onde o nosso navio deveria deixar sua carga.

[[v44-21-4]]

^<<v44-21-4,4>>^ Encontrando os discípulos dali, ficamos com eles sete dias. Eles, pelo Espírito, recomendavam a Paulo que não fosse a Jerusalém.

[[v44-21-5]]

^<<v44-21-5,5>>^ Mas quando terminou o nosso tempo ali, partimos e continuamos nossa viagem. Todos os discípulos, com suas mulheres e filhos, nos acompanharam até fora da cidade, e ali na praia nos ajoelhamos e oramos.

[[v44-21-6]]

^<<v44-21-6,6>>^ Depois de nos despedirmos, embarcamos, e eles voltaram para casa.

[[v44-21-7]]

^<<v44-21-7,7>>^ Demos prosseguimento à nossa viagem partindo de Tiro, e aportamos em Ptolemaida, onde saudamos os irmãos e passamos um dia com eles.

[[v44-21-8]]

^<<v44-21-8,8>>^ Partindo no dia seguinte, chegamos a Cesaréia e ficamos na casa de Filipe, o evangelista, um dos sete.

[[v44-21-9]]

^<<v44-21-9,9>>^ Ele tinha quatro filhas virgens, que profetizavam.

[[v44-21-10]]

^<<v44-21-10,10>>^ Depois de passarmos ali vários dias, desceu da Judéia um profeta chamado Ágabo.

[[v44-21-11]]

^<<v44-21-11,11>>^ Vindo ao nosso encontro, tomou o cinto de Paulo e, amarrando as suas próprias mãos e pés, disse: "Assim diz o Espírito Santo: ‘Desta maneira os judeus amarrarão o dono deste cinto em Jerusalém e o entregarão aos gentios’ ".

[[v44-21-12]]

^<<v44-21-12,12>>^ Quando ouvimos isso, nós e o povo dali rogamos a Paulo que não subisse para Jerusalém.

[[v44-21-13]]

^<<v44-21-13,13>>^ Então Paulo respondeu: "Por que vocês estão chorando e partindo o meu coração? Estou pronto não apenas para ser amarrado, mas também para morrer em Jerusalém pelo nome do Senhor Jesus".

[[v44-21-14]]

^<<v44-21-14,14>>^ Como não pudemos dissuadi-lo, desistimos e dissemos: "Seja feita a vontade do Senhor".

[[v44-21-15]]

^<<v44-21-15,15>>^ Depois disso, preparamo-nos e subimos para Jerusalém.

[[v44-21-16]]

^<<v44-21-16,16>>^ Alguns dos discípulos de Cesaréia nos acompanharam e nos levaram à casa de Mnasom, onde devíamos ficar. Ele era natural de Chipre e um dos primeiros discípulos.

[[v44-21-17]]

^<<v44-21-17,17>>^ Quando chegamos em Jerusalém, os irmãos nos receberam com alegria.

[[v44-21-18]]

^<<v44-21-18,18>>^ No dia seguinte Paulo foi conosco encontrar-se com Tiago, e todos os presbíteros estavam presentes.

[[v44-21-19]]

^<<v44-21-19,19>>^ Paulo os saudou e relatou minuciosamente o que Deus havia feito entre os gentios por meio do seu ministério.

[[v44-21-20]]

^<<v44-21-20,20>>^ Ouvindo isso, eles louvaram a Deus e disseram a Paulo: "Veja, irmão, quantos milhares de judeus creram, e todos eles são zelosos da lei.

[[v44-21-21]]

^<<v44-21-21,21>>^ Eles foram informados de que você ensina todos os judeus que vivem entre os gentios a se afastarem de Moisés, dizendo-lhes que não circuncidem seus filhos nem vivam de acordo com os nossos costumes.

[[v44-21-22]]

^<<v44-21-22,22>>^ Que faremos? Certamente eles saberão que você chegou;

[[v44-21-23]]

^<<v44-21-23,23>>^ portanto, faça o que lhe dizemos. Estão conosco quatro homens que fizeram um voto.

[[v44-21-24]]

^<<v44-21-24,24>>^ Participe com esses homens dos rituais de purificação e pague as despesas deles, para que rapem a cabeça. Então todos saberão que não é verdade o que falam de você, mas que você continua vivendo em obediência à lei.

[[v44-21-25]]

^<<v44-21-25,25>>^ Quanto aos gentios convertidos, já lhes escrevemos a nossa decisão de que eles devem abster-se de comida sacrificada aos ídolos, do sangue, da carne de animais estrangulados e da imoralidade sexual".

[[v44-21-26]]

^<<v44-21-26,26>>^ No dia seguinte Paulo tomou aqueles homens e purificou-se juntamente com eles. Depois foi ao templo para declarar o prazo do cumprimento dos dias da purificação e da oferta que seria feita individualmente em favor deles.

[[v44-21-27]]

^<<v44-21-27,27>>^ Quando já estavam para terminar os sete dias, alguns judeus da Província da Ásia, vendo Paulo no templo, agitaram toda a multidão e o agarraram,

[[v44-21-28]]

^<<v44-21-28,28>>^ gritando: "Israelitas, ajudem-nos! Este é o homem que ensina a todos em toda parte contra o nosso povo, contra a nossa lei e contra este lugar. Além disso, ele fez entrar gregos no templo e profanou este santo lugar".

[[v44-21-29]]

^<<v44-21-29,29>>^ Anteriormente eles haviam visto o efésio Trófimo na cidade com Paulo e julgaram que Paulo o tinha introduzido no templo.

[[v44-21-30]]

^<<v44-21-30,30>>^ Toda a cidade ficou alvoroçada, e juntou-se uma multidão. Agarrando Paulo, arrastaram-no para fora do templo, e imediatamente as portas foram fechadas.

[[v44-21-31]]

^<<v44-21-31,31>>^ Tentando eles matá-lo, chegaram notícias ao comandante das tropas romanas de que toda a cidade de Jerusalém estava em tumulto.

[[v44-21-32]]

^<<v44-21-32,32>>^ Ele reuniu imediatamente alguns oficiais e soldados, e com eles correu para o meio da multidão. Quando viram o comandante e os seus soldados, pararam de espancar Paulo.

[[v44-21-33]]

^<<v44-21-33,33>>^ O comandante chegou, prendeu-o e ordenou que ele fosse amarrado com duas correntes. Então perguntou quem era ele e o que tinha feito.

[[v44-21-34]]

^<<v44-21-34,34>>^ Alguns da multidão gritavam uma coisa, outros gritavam outra; não conseguindo saber ao certo o que havia acontecido, por causa do tumulto, o comandante ordenou que Paulo fosse levado para a fortaleza.

[[v44-21-35]]

^<<v44-21-35,35>>^ Quando chegou às escadas, a violência do povo era tão grande que ele precisou ser carregado pelos soldados.

[[v44-21-36]]

^<<v44-21-36,36>>^ A multidão que o seguia continuava gritando: "Acaba com ele! "

[[v44-21-37]]

^<<v44-21-37,37>>^ Quando os soldados estavam para introduzir Paulo na fortaleza, ele perguntou ao comandante: "Posso dizer-te algo? " "Você fala grego? ", perguntou ele.

[[v44-21-38]]

^<<v44-21-38,38>>^ "Não é você o egípcio que iniciou uma revolta e há algum tempo levou quatro mil assassinos para o deserto? "

[[v44-21-39]]

^<<v44-21-39,39>>^ Paulo respondeu: "Sou judeu, cidadão de Tarso, cidade importante da Cilícia. Permite-me falar ao povo".

[[v44-21-40]]

^<<v44-21-40,40>>^ Tendo recebido permissão do comandante, Paulo levantou-se na escadaria e fez sinal à multidão. Quando todos fizeram silêncio, dirigiu-se a eles em aramaico:

'''

xref:044-atos/044-atos-020.adoc#v44-20-0[&#60; Capítulo Anterior] | <<v44-21-0,Topo>> | xref:044-atos/044-atos-022.adoc#v44-22-0[Próximo Capítulo &#62;]