include::./index.adoc[]

[[v44-11-0]]
=== Atos, 11
// nvi ?, NVI - Nova Versão Internacional

[[v44-11-1]]

^<<v44-11-1,1>>^ Os apóstolos e os irmãos de toda a Judéia ouviram falar que os gentios também haviam recebido a palavra de Deus.

[[v44-11-2]]

^<<v44-11-2,2>>^ Assim, quando Pedro subiu a Jerusalém, os que eram do partido dos circuncisos o criticavam, dizendo:

[[v44-11-3]]

^<<v44-11-3,3>>^ "Você entrou na casa de homens incircuncisos e comeu com eles".

[[v44-11-4]]

^<<v44-11-4,4>>^ Pedro, então, começou a explicar-lhes exatamente como tudo havia acontecido:

[[v44-11-5]]

^<<v44-11-5,5>>^ "Eu estava na cidade de Jope orando; caindo em êxtase, tive uma visão. Vi algo parecido com um grande lençol sendo baixado do céu, preso pelas quatro pontas, e que vinha até o lugar onde eu estava.

[[v44-11-6]]

^<<v44-11-6,6>>^ Olhei para dentro dele e notei que havia ali quadrúpedes da terra, animais selvagens, répteis e aves do céu.

[[v44-11-7]]

^<<v44-11-7,7>>^ Então ouvi uma voz que me dizia: ‘Levante-se, Pedro; mate e coma’.

[[v44-11-8]]

^<<v44-11-8,8>>^ "Eu respondi: De modo nenhum, Senhor! Nunca entrou em minha boca algo impuro ou imundo.

[[v44-11-9]]

^<<v44-11-9,9>>^ "A voz falou do céu segunda vez: ‘Não chame impuro ao que Deus purificou’.

[[v44-11-10]]

^<<v44-11-10,10>>^ Isso aconteceu três vezes, e então tudo foi recolhido ao céu.

[[v44-11-11]]

^<<v44-11-11,11>>^ "Na mesma hora chegaram à casa em que eu estava hospedado três homens que me haviam sido enviados de Cesaréia.

[[v44-11-12]]

^<<v44-11-12,12>>^ O Espírito me disse que não hesitasse em ir com eles. Estes seis irmãos também foram comigo, e entramos na casa de um certo homem.

[[v44-11-13]]

^<<v44-11-13,13>>^ Ele nos contou como um anjo lhe tinha aparecido em sua casa e dissera: ‘Mande buscar, em Jope, a Simão, chamado Pedro.

[[v44-11-14]]

^<<v44-11-14,14>>^ Ele lhe trará uma mensagem por meio da qual serão salvos você e todos os da sua casa’.

[[v44-11-15]]

^<<v44-11-15,15>>^ "Quando comecei a falar, o Espírito Santo desceu sobre eles como sobre nós no princípio.

[[v44-11-16]]

^<<v44-11-16,16>>^ Então me lembrei do que o Senhor tinha dito: ‘João batizou com água, mas vocês serão batizados com o Espírito Santo’.

[[v44-11-17]]

^<<v44-11-17,17>>^ Se, pois, Deus lhes deu o mesmo dom que nos dera quando cremos no Senhor Jesus Cristo, quem era eu para pensar em opor-me a Deus? "

[[v44-11-18]]

^<<v44-11-18,18>>^ Ouvindo isso, não apresentaram mais objeções e louvaram a Deus, dizendo: "Então, Deus concedeu arrependimento para a vida até mesmo aos gentios! "

[[v44-11-19]]

^<<v44-11-19,19>>^ Os que tinham sido dispersos por causa da perseguição desencadeada com a morte de Estêvão chegaram até à Fenícia, Chipre e Antioquia, anunciando a mensagem apenas aos judeus.

[[v44-11-20]]

^<<v44-11-20,20>>^ Alguns deles, todavia, cipriotas e cireneus, foram a Antioquia e começaram a falar também aos gregos, contando-lhes as boas novas a respeito do Senhor Jesus.

[[v44-11-21]]

^<<v44-11-21,21>>^ A mão do Senhor estava com eles, e muitos creram e se converteram ao Senhor.

[[v44-11-22]]

^<<v44-11-22,22>>^ Notícias desse fato chegaram aos ouvidos da igreja em Jerusalém, e eles enviaram Barnabé a Antioquia.

[[v44-11-23]]

^<<v44-11-23,23>>^ Este, ali chegando e vendo a graça de Deus, ficou alegre e os animou a permanecerem fiéis ao Senhor, de todo o coração.

[[v44-11-24]]

^<<v44-11-24,24>>^ Ele era um homem bom, cheio do Espírito Santo e de fé; e muitas pessoas foram acrescentadas ao Senhor.

[[v44-11-25]]

^<<v44-11-25,25>>^ Então Barnabé foi a Tarso procurar Saulo

[[v44-11-26]]

^<<v44-11-26,26>>^ e, quando o encontrou, levou-o para Antioquia. Assim, durante um ano inteiro Barnabé e Saulo se reuniram com a igreja e ensinaram a muitos. Em Antioquia, os discípulos foram pela primeira vez chamados cristãos.

[[v44-11-27]]

^<<v44-11-27,27>>^ Naqueles dias alguns profetas desceram de Jerusalém para Antioquia.

[[v44-11-28]]

^<<v44-11-28,28>>^ Um deles, Ágabo, levantou-se e pelo Espírito predisse que uma grande fome sobreviria a todo o mundo romano, o que aconteceu durante o reinado de Cláudio.

[[v44-11-29]]

^<<v44-11-29,29>>^ Os discípulos, cada um segundo as suas possibilidades, decidiram providenciar ajuda para os irmãos que viviam na Judéia.

[[v44-11-30]]

^<<v44-11-30,30>>^ E o fizeram, enviando suas ofertas aos presbíteros pelas mãos de Barnabé e Saulo.

'''

xref:044-atos/044-atos-010.adoc#v44-10-0[&#60; Capítulo Anterior] | <<v44-11-0,Topo>> | xref:044-atos/044-atos-012.adoc#v44-12-0[Próximo Capítulo &#62;]