include::./index.adoc[]

[[v44-2-0]]
=== Atos, 2
// nvi ?, NVI - Nova Versão Internacional

[[v44-2-1]]

^<<v44-2-1,1>>^ Chegando o dia de Pentecoste, estavam todos reunidos num só lugar.

[[v44-2-2]]

^<<v44-2-2,2>>^ De repente veio do céu um som, como de um vento muito forte, e encheu toda a casa na qual estavam assentados.

[[v44-2-3]]

^<<v44-2-3,3>>^ E viram o que parecia línguas de fogo, que se separaram e pousaram sobre cada um deles.

[[v44-2-4]]

^<<v44-2-4,4>>^ Todos ficaram cheios do Espírito Santo e começaram a falar noutras línguas, conforme o Espírito os capacitava.

[[v44-2-5]]

^<<v44-2-5,5>>^ Havia em Jerusalém judeus, tementes a Deus, vindos de todas as nações do mundo.

[[v44-2-6]]

^<<v44-2-6,6>>^ Ouvindo-se este som, ajuntou-se uma multidão que ficou perplexa, pois cada um os ouvia falar em sua própria língua.

[[v44-2-7]]

^<<v44-2-7,7>>^ Atônitos e maravilhados, eles perguntavam: "Acaso não são galileus todos estes homens que estão falando?

[[v44-2-8]]

^<<v44-2-8,8>>^ Então, como os ouvimos, cada um de nós, em nossa própria língua materna?

[[v44-2-9]]

^<<v44-2-9,9>>^ Partos, medos e elamitas; habitantes da Mesopotâmia, Judéia e Capadócia, Ponto e da província da Ásia,

[[v44-2-10]]

^<<v44-2-10,10>>^ Frígia e Panfília, Egito e das partes da Líbia próximas a Cirene; visitantes vindos de Roma,

[[v44-2-11]]

^<<v44-2-11,11>>^ tanto judeus como convertidos ao judaísmo; cretenses e árabes. Nós os ouvimos declarar as maravilhas de Deus em nossa própria língua! "

[[v44-2-12]]

^<<v44-2-12,12>>^ Atônitos e perplexos, todos perguntavam uns aos outros: "Que significa isto? "

[[v44-2-13]]

^<<v44-2-13,13>>^ Alguns, todavia, zombavam deles e diziam: "Eles beberam vinho demais".

[[v44-2-14]]

^<<v44-2-14,14>>^ Então Pedro levantou-se com os Onze e, em alta voz, dirigiu-se à multidão: "Homens da Judéia e todos os que vivem em Jerusalém, deixem-me explicar-lhes isto! Ouçam com atenção:

[[v44-2-15]]

^<<v44-2-15,15>>^ estes homens não estão bêbados, como vocês supõem. Ainda são nove horas da manhã!

[[v44-2-16]]

^<<v44-2-16,16>>^ Pelo contrário, isto é o que foi predito pelo profeta Joel:

[[v44-2-17]]

^<<v44-2-17,17>>^ ‘Nos últimos dias, diz Deus, derramarei do meu Espírito sobre todos os povos. Os seus filhos e as suas filhas profetizarão, os jovens terão visões, os velhos terão sonhos.

[[v44-2-18]]

^<<v44-2-18,18>>^ Sobre os meus servos e as minhas servas derramarei do meu Espírito naqueles dias, e eles profetizarão.

[[v44-2-19]]

^<<v44-2-19,19>>^ Mostrarei maravilhas em cima no céu e sinais em baixo, na terra, sangue, fogo e nuvens de fumaça.

[[v44-2-20]]

^<<v44-2-20,20>>^ O sol se tornará em trevas e a lua em sangue, antes que venha o grande e glorioso dia do Senhor.

[[v44-2-21]]

^<<v44-2-21,21>>^ E todo aquele que invocar o nome do Senhor será salvo! ’

[[v44-2-22]]

^<<v44-2-22,22>>^ "Israelitas, ouçam estas palavras: Jesus de Nazaré foi aprovado por Deus diante de vocês por meio de milagres, maravilhas e sinais, que Deus fez entre vocês por intermédio dele, como vocês mesmos sabem.

[[v44-2-23]]

^<<v44-2-23,23>>^ Este homem lhes foi entregue por propósito determinado e pré-conhecimento de Deus; e vocês, com a ajuda de homens perversos, o mataram, pregando-o na cruz.

[[v44-2-24]]

^<<v44-2-24,24>>^ Mas Deus o ressuscitou dos mortos, rompendo os laços da morte, porque era impossível que a morte o retivesse.

[[v44-2-25]]

^<<v44-2-25,25>>^ A respeito dele, disse Davi: ‘Eu sempre via o Senhor diante de mim. Porque ele está à minha direita, não serei abalado.

[[v44-2-26]]

^<<v44-2-26,26>>^ Por isso o meu coração está alegre e a minha língua exulta; o meu corpo também repousará em esperança,

[[v44-2-27]]

^<<v44-2-27,27>>^ porque tu não me abandonarás no sepulcro, nem permitirás que o teu Santo sofra decomposição.

[[v44-2-28]]

^<<v44-2-28,28>>^ Tu me fizeste conhecer os caminhos da vida e me encherás de alegria na tua presença’.

[[v44-2-29]]

^<<v44-2-29,29>>^ "Irmãos, posso dizer-lhes com franqueza que o patriarca Davi morreu e foi sepultado, e o seu túmulo está entre nós até o dia de hoje.

[[v44-2-30]]

^<<v44-2-30,30>>^ Mas ele era profeta e sabia que Deus lhe prometera sob juramento que colocaria um dos seus descendentes em seu trono.

[[v44-2-31]]

^<<v44-2-31,31>>^ Prevendo isso, falou da ressurreição do Cristo, que não foi abandonado no sepulcro e cujo corpo não sofreu decomposição.

[[v44-2-32]]

^<<v44-2-32,32>>^ Deus ressuscitou este Jesus, e todos nós somos testemunhas desse fato.

[[v44-2-33]]

^<<v44-2-33,33>>^ Exaltado à direita de Deus, ele recebeu do Pai o Espírito Santo prometido e derramou o que vocês agora vêem e ouvem.

[[v44-2-34]]

^<<v44-2-34,34>>^ Pois Davi não subiu ao céu, mas ele mesmo declarou: ‘O Senhor disse ao meu Senhor: Senta-te à minha direita

[[v44-2-35]]

^<<v44-2-35,35>>^ até que eu ponha os teus inimigos como estrado para os teus pés’.

[[v44-2-36]]

^<<v44-2-36,36>>^ "Portanto, que todo Israel fique certo disto: Este Jesus, a quem vocês crucificaram, Deus o fez Senhor e Cristo".

[[v44-2-37]]

^<<v44-2-37,37>>^ Quando ouviram isso, os seus corações ficaram aflitos, e eles perguntaram a Pedro e aos outros apóstolos: "Irmãos, que faremos? "

[[v44-2-38]]

^<<v44-2-38,38>>^ Pedro respondeu: "Arrependam-se, e cada um de vocês seja batizado em nome de Jesus Cristo, para perdão dos seus pecados, e receberão o dom do Espírito Santo.

[[v44-2-39]]

^<<v44-2-39,39>>^ Pois a promessa é para vocês, para os seus filhos e para todos os que estão longe, para todos quantos o Senhor, o nosso Deus chamar".

[[v44-2-40]]

^<<v44-2-40,40>>^ Com muitas outras palavras os advertia e insistia com eles: "Salvem-se desta geração corrompida! "

[[v44-2-41]]

^<<v44-2-41,41>>^ Os que aceitaram a mensagem foram batizados, e naquele dia houve um acréscimo de cerca de três mil pessoas.

[[v44-2-42]]

^<<v44-2-42,42>>^ Eles se dedicavam ao ensino dos apóstolos e à comunhão, ao partir do pão e às orações.

[[v44-2-43]]

^<<v44-2-43,43>>^ Todos estavam cheios de temor, e muitas maravilhas e sinais eram feitos pelos apóstolos.

[[v44-2-44]]

^<<v44-2-44,44>>^ Todos os que criam mantinham-se unidos e tinham tudo em comum.

[[v44-2-45]]

^<<v44-2-45,45>>^ Vendendo suas propriedades e bens, distribuíam a cada um conforme a sua necessidade.

[[v44-2-46]]

^<<v44-2-46,46>>^ Todos os dias, continuavam a reunir-se no pátio do templo. Partiam o pão em suas casas, e juntos participavam das refeições, com alegria e sinceridade de coração,

[[v44-2-47]]

^<<v44-2-47,47>>^ louvando a Deus e tendo a simpatia de todo o povo. E o Senhor lhes acrescentava todos os dias os que iam sendo salvos.

'''

xref:044-atos/044-atos-001.adoc#v44-1-0[&#60; Capítulo Anterior] | <<v44-2-0,Topo>> | xref:044-atos/044-atos-003.adoc#v44-3-0[Próximo Capítulo &#62;]