include::./index.adoc[]

[[v44-25-0]]
=== Atos, 25
// nvi ?, NVI - Nova Versão Internacional

[[v44-25-1]]

^<<v44-25-1,1>>^ Três dias depois de chegar à província, Festo subiu de Cesaréia para Jerusalém,

[[v44-25-2]]

^<<v44-25-2,2>>^ onde os chefes dos sacerdotes e os judeus mais importantes compareceram diante dele, apresentando as acusações contra Paulo.

[[v44-25-3]]

^<<v44-25-3,3>>^ Pediram a Festo o favor de transferir Paulo para Jerusalém, contra os interesses do próprio Paulo, pois estavam preparando uma emboscada para matá-lo no caminho.

[[v44-25-4]]

^<<v44-25-4,4>>^ Festo respondeu: "Paulo está preso em Cesaréia, e eu mesmo vou para lá em breve.

[[v44-25-5]]

^<<v44-25-5,5>>^ Desçam comigo alguns dos seus líderes e apresentem ali as acusações que têm contra esse homem, se realmente ele fez algo de errado".

[[v44-25-6]]

^<<v44-25-6,6>>^ Tendo passado com eles oito a dez dias, desceu para Cesaréia e, no dia seguinte, convocou o tribunal e ordenou que Paulo fosse trazido perante ele.

[[v44-25-7]]

^<<v44-25-7,7>>^ Quando Paulo apareceu, os judeus que tinham chegado de Jerusalém se aglomeraram ao seu redor, fazendo contra ele muitas e graves acusações que não podiam provar.

[[v44-25-8]]

^<<v44-25-8,8>>^ Então Paulo fez sua defesa: "Nada fiz de errado contra a lei dos judeus, contra o templo ou contra César".

[[v44-25-9]]

^<<v44-25-9,9>>^ Festo, querendo prestar um favor aos judeus, perguntou a Paulo: "Você está disposto a ir a Jerusalém e ali ser julgado diante de mim, acerca destas acusações? "

[[v44-25-10]]

^<<v44-25-10,10>>^ Paulo respondeu: "Estou agora diante do tribunal de César, onde devo ser julgado. Não fiz nenhum mal aos judeus, como bem sabes.

[[v44-25-11]]

^<<v44-25-11,11>>^ Se, de fato, sou culpado de ter feito algo que mereça pena de morte, não me recuso a morrer. Mas se as acusações feitas contra mim por estes judeus não são verdadeiras, ninguém tem o direito de me entregar a eles. Apelo para César! "

[[v44-25-12]]

^<<v44-25-12,12>>^ Depois de ter consultado seus conselheiros, Festo declarou: "Você apelou para César, para César irá! "

[[v44-25-13]]

^<<v44-25-13,13>>^ Alguns dias depois, o rei Agripa e Berenice chegaram a Cesaréia para saudar Festo.

[[v44-25-14]]

^<<v44-25-14,14>>^ Visto que estavam passando muitos dias ali, Festo explicou o caso de Paulo ao rei: "Há aqui um homem que Félix deixou preso.

[[v44-25-15]]

^<<v44-25-15,15>>^ Quando fui a Jerusalém, os chefes dos sacerdotes e os líderes dos judeus fizeram acusações contra ele, pedindo que fosse condenado.

[[v44-25-16]]

^<<v44-25-16,16>>^ "Eu lhes disse que não é costume romano condenar ninguém antes que ele se defronte pessoalmente com seus acusadores e tenha a oportunidade de se defender das acusações que lhe fazem.

[[v44-25-17]]

^<<v44-25-17,17>>^ Vindo eles comigo para cá, não retardei o caso; convoquei o tribunal no dia seguinte e ordenei que o homem fosse apresentado.

[[v44-25-18]]

^<<v44-25-18,18>>^ Quando os seus acusadores se levantaram para falar, não o acusaram de nenhum dos crimes que eu esperava.

[[v44-25-19]]

^<<v44-25-19,19>>^ Pelo contrário, tinham alguns pontos de divergência com ele acerca de sua própria religião e de um certo Jesus, já morto, o qual Paulo insiste que está vivo.

[[v44-25-20]]

^<<v44-25-20,20>>^ Fiquei sem saber como investigar tais assuntos; por isso perguntei-lhe se ele estaria disposto a ir a Jerusalém e ser julgado ali acerca destas acusações.

[[v44-25-21]]

^<<v44-25-21,21>>^ Apelando Paulo para que fosse guardado até a decisão do Imperador, ordenei que ficasse sob custódia até que eu pudesse enviá-lo a César".

[[v44-25-22]]

^<<v44-25-22,22>>^ Então Agripa disse a Festo: "Eu também gostaria de ouvir esse homem". Ele respondeu: "Amanhã o ouvirás".

[[v44-25-23]]

^<<v44-25-23,23>>^ No dia seguinte, Agripa e Berenice vieram com grande pompa e entraram na sala de audiências com os altos oficiais e os homens importantes da cidade. Por ordem de Festo, Paulo foi trazido.

[[v44-25-24]]

^<<v44-25-24,24>>^ Então Festo disse: "Ó rei Agripa e todos os senhores aqui presentes conosco, vejam este homem! Toda a comunidade judaica me fez petições a respeito dele em Jerusalém e aqui em Cesaréia, gritando que ele não deveria mais viver.

[[v44-25-25]]

^<<v44-25-25,25>>^ Mas verifiquei que ele nada fez que mereça pena de morte; todavia, porque apelou para o Imperador, decidi enviá-lo a Roma.

[[v44-25-26]]

^<<v44-25-26,26>>^ No entanto, não tenho nada definido a respeito dele para escrever a Sua Majestade. Por isso, eu o trouxe diante dos senhores, e especialmente diante de ti, rei Agripa, de forma que, feita esta investigação, eu tenha algo para escrever.

[[v44-25-27]]

^<<v44-25-27,27>>^ Pois não me parece razoável enviar um preso sem especificar as acusações contra ele".

'''

xref:044-atos/044-atos-024.adoc#v44-24-0[&#60; Capítulo Anterior] | <<v44-25-0,Topo>> | xref:044-atos/044-atos-026.adoc#v44-26-0[Próximo Capítulo &#62;]