include::./index.adoc[]

[[v44-4-0]]
=== Atos, 4
// nvi ?, NVI - Nova Versão Internacional

[[v44-4-1]]

^<<v44-4-1,1>>^ Enquanto Pedro e João falavam ao povo, chegaram os sacerdotes, o capitão da guarda do templo e os saduceus.

[[v44-4-2]]

^<<v44-4-2,2>>^ Eles estavam muito perturbados porque os apóstolos estavam ensinando o povo e proclamando em Jesus a ressurreição dos mortos.

[[v44-4-3]]

^<<v44-4-3,3>>^ Agarraram Pedro e João e, como já estava anoitecendo, os colocaram na prisão até o dia seguinte.

[[v44-4-4]]

^<<v44-4-4,4>>^ Mas, muitos dos que tinham ouvido a mensagem creram, chegando o número dos homens que creram a perto de cinco mil.

[[v44-4-5]]

^<<v44-4-5,5>>^ No dia seguinte, as autoridades, os líderes religiosos e os mestres da lei reuniram-se em Jerusalém.

[[v44-4-6]]

^<<v44-4-6,6>>^ Estavam ali Anás, o sumo sacerdote, bem como Caifás, João, Alexandre e todos os que eram da família do sumo sacerdote.

[[v44-4-7]]

^<<v44-4-7,7>>^ Mandaram trazer Pedro e João diante deles e começaram a interrogá-los: "Com que poder ou em nome de quem vocês fizeram isso? "

[[v44-4-8]]

^<<v44-4-8,8>>^ Então Pedro, cheio do Espírito Santo, disse-lhes: "Autoridades e líderes do povo!

[[v44-4-9]]

^<<v44-4-9,9>>^ Visto que hoje somos chamados para prestar contas de um ato de bondade em favor de um aleijado, sendo interrogados acerca de como ele foi curado,

[[v44-4-10]]

^<<v44-4-10,10>>^ saibam os senhores e todo o povo de Israel que por meio do nome de Jesus Cristo, o Nazareno, a quem os senhores crucificaram, mas a quem Deus ressuscitou dos mortos, este homem está aí curado diante dos senhores.

[[v44-4-11]]

^<<v44-4-11,11>>^ Este Jesus é ‘a pedra que vocês, construtores, rejeitaram, e que se tornou a pedra angular’.

[[v44-4-12]]

^<<v44-4-12,12>>^ Não há salvação em nenhum outro, pois, debaixo do céu não há nenhum outro nome dado aos homens pelo qual devamos ser salvos".

[[v44-4-13]]

^<<v44-4-13,13>>^ Vendo a coragem de Pedro e de João, e percebendo que eram homens comuns e sem instrução, ficaram admirados e reconheceram que eles haviam estado com Jesus.

[[v44-4-14]]

^<<v44-4-14,14>>^ E como podiam ver ali com eles o homem que fora curado, nada podiam dizer contra eles.

[[v44-4-15]]

^<<v44-4-15,15>>^ Assim, ordenaram que se retirassem do Sinédrio e começaram a discutir,

[[v44-4-16]]

^<<v44-4-16,16>>^ perguntando: "Que faremos com esses homens? Todos os que moram em Jerusalém sabem que eles realizaram um milagre notório que não podemos negar.

[[v44-4-17]]

^<<v44-4-17,17>>^ Todavia, para impedir que isso se espalhe ainda mais entre o povo, precisamos adverti-los de que não falem mais com ninguém sobre esse nome".

[[v44-4-18]]

^<<v44-4-18,18>>^ Então, chamando-os novamente, ordenaram-lhes que não falassem nem ensinassem em nome de Jesus.

[[v44-4-19]]

^<<v44-4-19,19>>^ Mas Pedro e João responderam: "Julguem os senhores mesmos se é justo aos olhos de Deus obedecer aos senhores e não a Deus.

[[v44-4-20]]

^<<v44-4-20,20>>^ Pois não podemos deixar de falar do que vimos e ouvimos".

[[v44-4-21]]

^<<v44-4-21,21>>^ Depois de mais ameaças, eles os deixaram ir. Não tinham como castigá-los, porque todo o povo estava louvando a Deus pelo que acontecera.

[[v44-4-22]]

^<<v44-4-22,22>>^ Pois o homem que fora curado milagrosamente tinha mais de quarenta anos de idade.

[[v44-4-23]]

^<<v44-4-23,23>>^ Quando foram soltos, Pedro e João voltaram para os seus e contaram tudo o que os chefes dos sacerdotes e os líderes religiosos lhes tinham dito.

[[v44-4-24]]

^<<v44-4-24,24>>^ Ouvindo isso, levantaram juntos a voz a Deus, dizendo: "Ó Soberano, tu fizeste o céu, a terra, o mar e tudo o que neles há!

[[v44-4-25]]

^<<v44-4-25,25>>^ Tu falaste pelo Espírito Santo por boca do teu servo, nosso pai Davi: ‘Por que se enfurecem as nações, e os povos conspiram em vão?

[[v44-4-26]]

^<<v44-4-26,26>>^ Os reis da terra se levantam, e os governantes se reúnem contra o Senhor e contra o seu Ungido’.

[[v44-4-27]]

^<<v44-4-27,27>>^ De fato, Herodes e Pôncio Pilatos reuniram-se com os gentios e com os povos de Israel nesta cidade, para conspirar contra o teu santo servo Jesus, a quem ungiste.

[[v44-4-28]]

^<<v44-4-28,28>>^ Fizeram o que o teu poder e a tua vontade haviam decidido de antemão que acontecesse.

[[v44-4-29]]

^<<v44-4-29,29>>^ Agora, Senhor, considera as ameaças deles e capacita os teus servos para anunciarem a tua palavra corajosamente.

[[v44-4-30]]

^<<v44-4-30,30>>^ Estende a tua mão para curar e realizar sinais e maravilhas por meio do nome do teu santo servo Jesus".

[[v44-4-31]]

^<<v44-4-31,31>>^ Depois de orarem, tremeu o lugar em que estavam reunidos; todos ficaram cheios do Espírito Santo e anunciavam corajosamente a palavra de Deus.

[[v44-4-32]]

^<<v44-4-32,32>>^ Da multidão dos que creram, uma era a mente e um o coração. Ninguém considerava unicamente sua coisa alguma que possuísse, mas compartilhavam tudo o que tinham.

[[v44-4-33]]

^<<v44-4-33,33>>^ Com grande poder os apóstolos continuavam a testemunhar da ressurreição do Senhor Jesus, e grandiosa graça estava sobre todos eles.

[[v44-4-34]]

^<<v44-4-34,34>>^ Não havia pessoas necessitadas entre eles, pois os que possuíam terras ou casas as vendiam, traziam o dinheiro da venda

[[v44-4-35]]

^<<v44-4-35,35>>^ e o colocavam aos pés dos apóstolos, que o distribuíam segundo a necessidade de cada um.

[[v44-4-36]]

^<<v44-4-36,36>>^ José, um levita de Chipre a quem os apóstolos deram o nome de Barnabé, que significa encorajador,

[[v44-4-37]]

^<<v44-4-37,37>>^ vendeu um campo que possuía, trouxe o dinheiro e o colocou aos pés dos apóstolos.

'''

xref:044-atos/044-atos-003.adoc#v44-3-0[&#60; Capítulo Anterior] | <<v44-4-0,Topo>> | xref:044-atos/044-atos-005.adoc#v44-5-0[Próximo Capítulo &#62;]