include::./index.adoc[]

[[v44-24-0]]
=== Atos, 24
// nvi ?, NVI - Nova Versão Internacional

[[v44-24-1]]

^<<v44-24-1,1>>^ Cinco dias depois, o sumo sacerdote Ananias desceu a Cesaréia com alguns dos líderes dos judeus e um advogado chamado Tértulo, os quais apresentaram ao governador suas acusações contra Paulo.

[[v44-24-2]]

^<<v44-24-2,2>>^ Quando Paulo foi chamado, Tértulo apresentou sua causa a Félix: "Temos desfrutado de um longo período de paz durante o teu governo, e o teu providente cuidado resultou em reformas nesta nação.

[[v44-24-3]]

^<<v44-24-3,3>>^ Em tudo e em toda parte, excelentíssimo Félix, reconhecemos estes benefícios com profunda gratidão.

[[v44-24-4]]

^<<v44-24-4,4>>^ Todavia, a fim de não tomar-te mais tempo, peço-te o favor de ouvir-nos apenas por um pouco.

[[v44-24-5]]

^<<v44-24-5,5>>^ "Verificamos que este homem é um perturbador, que promove tumultos entre os judeus pelo mundo todo. Ele é o principal cabeça da seita dos nazarenos

[[v44-24-6]]

^<<v44-24-6,6>>^ e tentou até mesmo profanar o templo; então o prendemos e quisemos julgá-lo segundo a nossa lei.

[[v44-24-7]]

^<<v44-24-7,7>>^ Mas o comandante Lísias interveio, e com muita força o arrebatou de nossas mãos e ordenou que os seus acusadores se apresentassem.

[[v44-24-8]]

^<<v44-24-8,8>>^ Se tu mesmo o interrogares, poderás verificar a verdade a respeito de todas estas acusações que estamos fazendo contra ele".

[[v44-24-9]]

^<<v44-24-9,9>>^ Os judeus confirmaram a acusação, garantindo que as afirmações eram verdadeiras.

[[v44-24-10]]

^<<v44-24-10,10>>^ Quando o governador lhe deu sinal para que falasse, Paulo declarou: "Sei que há muitos anos tens sido juiz nesta nação; por isso, de bom grado faço minha defesa.

[[v44-24-11]]

^<<v44-24-11,11>>^ Facilmente poderás verificar que há menos de doze dias subi a Jerusalém para adorar a Deus.

[[v44-24-12]]

^<<v44-24-12,12>>^ Meus acusadores não me encontraram discutindo com ninguém no templo, nem incitando uma multidão nas sinagogas ou em qualquer outro lugar na cidade.

[[v44-24-13]]

^<<v44-24-13,13>>^ Nem tampouco podem provar-te as acusações que agora estão levantando contra mim.

[[v44-24-14]]

^<<v44-24-14,14>>^ Confesso-te, porém, que adoro o Deus dos nossos antepassados como seguidor do Caminho, a que chamam seita. Creio em tudo o que concorda com a Lei e no que está escrito nos Profetas,

[[v44-24-15]]

^<<v44-24-15,15>>^ e tenho em Deus a mesma esperança desses homens: de que haverá ressurreição tanto de justos como de injustos.

[[v44-24-16]]

^<<v44-24-16,16>>^ Por isso procuro sempre conservar minha consciência limpa diante de Deus e dos homens.

[[v44-24-17]]

^<<v44-24-17,17>>^ "Depois de estar ausente por vários anos, vim a Jerusalém para trazer esmolas ao meu povo e apresentar ofertas.

[[v44-24-18]]

^<<v44-24-18,18>>^ Enquanto fazia isso, já cerimonialmente puro, encontraram-me no templo, sem envolver-me em nenhum ajuntamento ou tumulto.

[[v44-24-19]]

^<<v44-24-19,19>>^ Mas há alguns judeus da província da Ásia que deveriam estar aqui diante de ti e apresentar acusações, se é que têm algo contra mim.

[[v44-24-20]]

^<<v44-24-20,20>>^ Ou os que aqui se acham deveriam declarar que crime encontraram em mim quando fui levado perante o Sinédrio,

[[v44-24-21]]

^<<v44-24-21,21>>^ a não ser que tenha sido este: quando me apresentei a eles, bradei: Por causa da ressurreição dos mortos estou sendo julgado hoje diante de vocês".

[[v44-24-22]]

^<<v44-24-22,22>>^ Então Félix, que tinha bom conhecimento do Caminho, adiou a causa e disse: "Quando chegar o comandante Lísias, decidirei o caso de vocês".

[[v44-24-23]]

^<<v44-24-23,23>>^ E ordenou ao centurião que mantivesse Paulo sob custódia, mas que lhe desse certa liberdade e permitisse que os seus amigos o servissem.

[[v44-24-24]]

^<<v44-24-24,24>>^ Vários dias depois, Félix veio com Drusila sua mulher, que era judia, mandou chamar Paulo e o ouviu falar sobre a fé em Cristo Jesus.

[[v44-24-25]]

^<<v44-24-25,25>>^ Quando Paulo se pôs a discorrer acerca da justiça, do domínio próprio e do juízo vindouro, Félix teve medo e disse: "Basta, por enquanto! Pode sair. Quando achar conveniente, mandarei chamá-lo de novo".

[[v44-24-26]]

^<<v44-24-26,26>>^ Ao mesmo tempo esperava que Paulo lhe oferecesse algum dinheiro, pelo que mandava buscá-lo freqüentemente e conversava com ele.

[[v44-24-27]]

^<<v44-24-27,27>>^ Passados dois anos, Félix foi sucedido por Pórcio Festo; todavia, porque desejava manter a simpatia dos judeus, Félix deixou Paulo na prisão.

'''

xref:044-atos/044-atos-023.adoc#v44-23-0[&#60; Capítulo Anterior] | <<v44-24-0,Topo>> | xref:044-atos/044-atos-025.adoc#v44-25-0[Próximo Capítulo &#62;]