include::./index.adoc[]

[[v44-22-0]]
=== Atos, 22
// nvi ?, NVI - Nova Versão Internacional

[[v44-22-1]]

^<<v44-22-1,1>>^ "Irmãos e pais, ouçam agora a minha defesa".

[[v44-22-2]]

^<<v44-22-2,2>>^ Quando ouviram que lhes falava em aramaico, ficaram em absoluto silêncio. Então Paulo disse:

[[v44-22-3]]

^<<v44-22-3,3>>^ "Sou judeu, nascido em Tarso da Cilícia, mas criado nesta cidade. Fui instruído rigorosamente por Gamaliel na lei de nossos antepassados, sendo tão zeloso por Deus quanto qualquer de vocês hoje.

[[v44-22-4]]

^<<v44-22-4,4>>^ Persegui os seguidores deste Caminho até a morte, prendendo tanto homens como mulheres e lançando-os na prisão,

[[v44-22-5]]

^<<v44-22-5,5>>^ como o podem testemunhar o sumo sacerdote e todo o Conselho, de quem cheguei a obter cartas para seus irmãos em Damasco e fui até lá, a fim de trazer essas pessoas a Jerusalém como prisioneiras, para serem punidas.

[[v44-22-6]]

^<<v44-22-6,6>>^ "Por volta do meio-dia, eu me aproximava de Damasco, quando de repente uma forte luz vinda do céu brilhou ao meu redor.

[[v44-22-7]]

^<<v44-22-7,7>>^ Caí por terra e ouvi uma voz que me dizia: ‘Saulo, Saulo! por que você está me perseguindo? ’

[[v44-22-8]]

^<<v44-22-8,8>>^ Então perguntei: Quem és tu, Senhor? E ele respondeu: ‘Eu sou Jesus, o Nazareno, a quem você persegue’.

[[v44-22-9]]

^<<v44-22-9,9>>^ Os que me acompanhavam viram a luz, mas não entenderam a voz daquele que falava comigo.

[[v44-22-10]]

^<<v44-22-10,10>>^ "Assim perguntei: Que devo fazer, Senhor? Disse o Senhor: ‘Levante-se, entre em Damasco, onde lhe será dito o que você deve fazer’.

[[v44-22-11]]

^<<v44-22-11,11>>^ Os que estavam comigo me levaram pela mão até Damasco, porque o resplendor da luz me deixara cego.

[[v44-22-12]]

^<<v44-22-12,12>>^ "Um homem chamado Ananias, piedoso segundo a lei e muito respeitado por todos os judeus que ali viviam,

[[v44-22-13]]

^<<v44-22-13,13>>^ veio ver-me e, pondo-se junto a mim, disse: ‘Irmão Saulo, recupere a visão’. Naquele mesmo instante pude vê-lo.

[[v44-22-14]]

^<<v44-22-14,14>>^ "Então ele disse: ‘O Deus dos nossos antepassados o escolheu para conhecer a sua vontade, ver o Justo e ouvir as palavras de sua boca.

[[v44-22-15]]

^<<v44-22-15,15>>^ Você será testemunha dele a todos os homens, daquilo que viu e ouviu.

[[v44-22-16]]

^<<v44-22-16,16>>^ E agora, que está esperando? Levante-se, seja batizado e lave os seus pecados, invocando o nome dele’.

[[v44-22-17]]

^<<v44-22-17,17>>^ "Quando voltei a Jerusalém, estando eu a orar no templo, caí em êxtase e

[[v44-22-18]]

^<<v44-22-18,18>>^ vi o Senhor que me dizia: ‘Depressa! Saia de Jerusalém imediatamente, pois não aceitarão seu testemunho a meu respeito’.

[[v44-22-19]]

^<<v44-22-19,19>>^ "Eu respondi: Senhor, estes homens sabem que eu ia de uma sinagoga a outra, a fim de prender e açoitar os que crêem em ti.

[[v44-22-20]]

^<<v44-22-20,20>>^ E quando foi derramado o sangue de tua testemunha Estêvão, eu estava lá, dando minha aprovação e cuidando das roupas dos que o matavam.

[[v44-22-21]]

^<<v44-22-21,21>>^ "Então o Senhor me disse: ‘Vá, eu o enviarei para longe, aos gentios’ ".

[[v44-22-22]]

^<<v44-22-22,22>>^ A multidão ouvia Paulo até que ele disse isso. Então todos levantaram a voz e gritaram: "Tira esse homem da face da terra! Ele não merece viver! "

[[v44-22-23]]

^<<v44-22-23,23>>^ Estando eles gritando, tirando suas capas e lançando poeira para o ar,

[[v44-22-24]]

^<<v44-22-24,24>>^ o comandante ordenou que Paulo fosse levado à fortaleza e fosse açoitado e interrogado, para saber por que o povo gritava daquela forma contra ele.

[[v44-22-25]]

^<<v44-22-25,25>>^ Enquanto o amarravam a fim de açoitá-lo, Paulo disse ao centurião que ali estava: "Vocês têm o direito de açoitar um cidadão romano sem que ele tenha sido condenado? "

[[v44-22-26]]

^<<v44-22-26,26>>^ Ao ouvir isso, o centurião foi prevenir o comandante: "Que vais fazer? Este homem é cidadão romano".

[[v44-22-27]]

^<<v44-22-27,27>>^ O comandante dirigiu-se a Paulo e perguntou: "Diga-me, você é cidadão romano? " Ele respondeu: "Sim, sou".

[[v44-22-28]]

^<<v44-22-28,28>>^ Então o comandante disse: "Eu precisei pagar um elevado preço por minha cidadania". Respondeu Paulo: "Eu a tenho por direito de nascimento".

[[v44-22-29]]

^<<v44-22-29,29>>^ Os que iam interrogá-lo retiraram-se imediatamente. O próprio comandante ficou alarmado, ao saber que havia prendido um cidadão romano.

[[v44-22-30]]

^<<v44-22-30,30>>^ No dia seguinte, visto que o comandante queria descobrir exatamente por que Paulo estava sendo acusado pelos judeus, libertou-o e ordenou que se reunissem os chefes dos sacerdotes e todo o Sinédrio. Então, trazendo Paulo, apresentou-o a eles.

'''

xref:044-atos/044-atos-021.adoc#v44-21-0[&#60; Capítulo Anterior] | <<v44-22-0,Topo>> | xref:044-atos/044-atos-023.adoc#v44-23-0[Próximo Capítulo &#62;]