include::./index.adoc[]

[[v65-1-0]]
=== Judas, 1
// nvi ?, NVI - Nova Versão Internacional

[[v65-1-1]]

^<<v65-1-1,1>>^ Judas, servo de Jesus Cristo e irmão de Tiago, aos que foram chamados, amados por Deus Pai e guardados por Jesus Cristo:

[[v65-1-2]]

^<<v65-1-2,2>>^ Misericórdia, paz e amor lhes sejam multiplicados.

[[v65-1-3]]

^<<v65-1-3,3>>^ Amados, embora estivesse muito ansioso por lhes escrever acerca da salvação que compartilhamos, senti que era necessário escrever-lhes insistindo que batalhassem pela fé uma vez por todas confiada aos santos.

[[v65-1-4]]

^<<v65-1-4,4>>^ Pois certos homens, cuja condenação já estava sentenciada há muito tempo, infiltraram-se dissimuladamente no meio de vocês. Estes são ímpios, e transformam a graça de nosso Deus em libertinagem e negam Jesus Cristo, nosso único Soberano e Senhor.

[[v65-1-5]]

^<<v65-1-5,5>>^ Embora vocês já tenham conhecimento de tudo isso, quero lembrar-lhes que o Senhor libertou um povo do Egito mas, posteriormente, destruiu os que não creram.

[[v65-1-6]]

^<<v65-1-6,6>>^ E aos anjos que não conservaram suas posições de autoridade mas abandonaram sua própria morada, ele os tem guardado em trevas, presos com correntes eternas para o juízo do grande Dia.

[[v65-1-7]]

^<<v65-1-7,7>>^ De modo semelhante a estes, Sodoma e Gomorra e as cidades em redor se entregaram à imoralidade e a relações sexuais antinaturais. Estando sob o castigo do fogo eterno, elas servem de exemplo.

[[v65-1-8]]

^<<v65-1-8,8>>^ Da mesma forma, estes sonhadores contaminam seus próprios corpos, rejeitam as autoridades e difamam os seres celestiais.

[[v65-1-9]]

^<<v65-1-9,9>>^ Contudo, nem mesmo o arcanjo Miguel, quando estava disputando com o diabo acerca do corpo de Moisés, ousou fazer acusação injuriosa contra ele, mas disse: "O Senhor o repreenda! "

[[v65-1-10]]

^<<v65-1-10,10>>^ Todavia, esses tais difamam tudo o que não entendem; e as coisas que entendem por instinto, como animais irracionais, nessas mesmas coisas se corrompem.

[[v65-1-11]]

^<<v65-1-11,11>>^ Ai deles! Pois seguiram o caminho de Caim, buscando o lucro, caíram no erro de Balaão e foram destruídos na rebelião de Corá.

[[v65-1-12]]

^<<v65-1-12,12>>^ Esses homens são rochas submersas nas festas de fraternidade que vocês fazem, comendo com vocês de maneira desonrosa. São pastores que só cuidam de si mesmos. São nuvens sem água, impelidas pelo vento; árvores de outono, sem frutos, duas vezes mortas, arrancadas pela raiz.

[[v65-1-13]]

^<<v65-1-13,13>>^ São ondas bravias do mar, espumando seus próprios atos vergonhosos; estrelas errantes, para as quais estão reservadas para sempre as mais densas trevas.

[[v65-1-14]]

^<<v65-1-14,14>>^ Enoque, o sétimo a partir de Adão, profetizou acerca deles: "Vejam, o Senhor vem com milhares de milhares de seus santos,

[[v65-1-15]]

^<<v65-1-15,15>>^ para julgar a todos e convencer a todos os ímpios a respeito de todos os atos de impiedade que eles cometeram impiamente e acerca de todas as palavras insolentes que os pecadores ímpios falaram contra ele".

[[v65-1-16]]

^<<v65-1-16,16>>^ Essas pessoas vivem se queixando e são descontentes com a sua sorte, seguem os seus próprios desejos impuros; são cheias de si e adulam os outros por interesse.

[[v65-1-17]]

^<<v65-1-17,17>>^ Todavia, amados, lembrem-se do que foi predito pelos apóstolos de nosso Senhor Jesus Cristo.

[[v65-1-18]]

^<<v65-1-18,18>>^ Eles diziam a vocês: "Nos últimos tempos haverá zombadores que seguirão os seus próprios desejos ímpios".

[[v65-1-19]]

^<<v65-1-19,19>>^ Estes são os que causam divisões entre vocês, os quais seguem a tendência da sua própria alma e não têm o Espírito.

[[v65-1-20]]

^<<v65-1-20,20>>^ Edifiquem-se, porém, amados, na santíssima fé que vocês têm, orando no Espírito Santo.

[[v65-1-21]]

^<<v65-1-21,21>>^ Mantenham-se no amor de Deus, enquanto esperam que a misericórdia de nosso Senhor Jesus Cristo os leve para a vida eterna.

[[v65-1-22]]

^<<v65-1-22,22>>^ Tenham compaixão daqueles que duvidam;

[[v65-1-23]]

^<<v65-1-23,23>>^ a outros, salvem-nos, arrebatando-os do fogo; a outros ainda, mostrem misericórdia com temor, odiando até a roupa contaminada pela carne.

[[v65-1-24]]

^<<v65-1-24,24>>^ Àquele que é poderoso para impedi-los de cair e para apresentá-los diante da sua glória sem mácula e com grande alegria,

[[v65-1-25]]

^<<v65-1-25,25>>^ ao único Deus, nosso Salvador, sejam glória, majestade, poder e autoridade, mediante Jesus Cristo, nosso Senhor, antes de todos os tempos, agora e para todo o sempre! Amém.

'''

xref:064-3-joao/064-3-joao-001.adoc#v64-1-0[&#60; Capítulo Anterior] | <<v65-1-0,Topo>> | xref:066-apocalipse/066-apocalipse-001.adoc#v66-1-0[Próximo Capítulo &#62;]