include::./index.adoc[]

[[v14-20-0]]
=== 2 Crônicas, 20
// nvi ?, NVI - Nova Versão Internacional

[[v14-20-1]]

^<<v14-20-1,1>>^ Depois disso, os moabitas e os amonitas, com alguns dos meunitas, entraram em guerra contra Josafá.

[[v14-20-2]]

^<<v14-20-2,2>>^ Então informaram a Josafá: "Um exército enorme vem contra ti de Edom, do outro lado do mar Morto. Já está em Hazazom-Tamar, isto é, En-Gedi".

[[v14-20-3]]

^<<v14-20-3,3>>^ Alarmado, Josafá decidiu consultar o Senhor e proclamou um jejum em todo o reino de Judá.

[[v14-20-4]]

^<<v14-20-4,4>>^ Reuniu-se, pois, o povo, vindo de todas as cidades de Judá para buscar a ajuda do Senhor.

[[v14-20-5]]

^<<v14-20-5,5>>^ Então Josafá levantou-se na assembléia de Judá e de Jerusalém, no templo do Senhor, na frente do pátio novo,

[[v14-20-6]]

^<<v14-20-6,6>>^ e orou: "Senhor, Deus dos nossos antepassados, não és tu o Deus que está nos céus? Tu governas sobre todos os reinos do mundo. Força e poder estão em tuas mãos, e ninguém pode opor-se a ti.

[[v14-20-7]]

^<<v14-20-7,7>>^ Não és tu o nosso Deus, que expulsaste os habitantes desta terra perante Israel, teu povo, e a deste para sempre aos descendentes de teu amigo Abraão?

[[v14-20-8]]

^<<v14-20-8,8>>^ Eles a têm habitado e nela construíram um santuário em honra do teu nome, dizendo:

[[v14-20-9]]

^<<v14-20-9,9>>^ ‘Se alguma desgraça nos atingir, seja o castigo da espada, seja a peste, seja a fome, nós nos colocaremos em tua presença diante deste templo, pois ele leva o teu nome, e clamaremos a ti em nossa angústia, e tu nos ouvirás e nos salvarás’.

[[v14-20-10]]

^<<v14-20-10,10>>^ "Mas agora, aí estão amonitas, moabitas e habitantes dos montes de Seir, cujos territórios não permitiste que Israel invadisse quando vinha do Egito; por isso os israelitas se desviaram deles e não os destruíram.

[[v14-20-11]]

^<<v14-20-11,11>>^ Vê agora como estão nos retribuindo, ao virem expulsar-nos da terra que nos deste por herança.

[[v14-20-12]]

^<<v14-20-12,12>>^ Ó nosso Deus, não irás tu julgá-los? Pois não temos força para enfrentar esse exército imenso que está nos atacando. Não sabemos o que fazer, mas os nossos olhos se voltam para ti".

[[v14-20-13]]

^<<v14-20-13,13>>^ Todos os homens de Judá, com suas mulheres e seus filhos, até os de colo, estavam ali de pé, diante do Senhor.

[[v14-20-14]]

^<<v14-20-14,14>>^ Então o Espírito do Senhor veio sobre Jaaziel, filho de Zacarias, neto de Benaia, bisneto de Jeiel e trineto de Matanias, levita e descendente de Asafe, no meio da assembléia.

[[v14-20-15]]

^<<v14-20-15,15>>^ Ele disse: "Escutem, todos os que vivem em Judá e em Jerusalém e o rei Josafá! Assim lhes diz o Senhor: ‘Não tenham medo nem fiquem desanimados por causa desse exército enorme. Pois a batalha não é de vocês, mas de Deus.

[[v14-20-16]]

^<<v14-20-16,16>>^ Amanhã, desçam contra eles. Eles virão pela subida de Ziz, e vocês os encontrarão no fim do vale, em frente do deserto de Jeruel.

[[v14-20-17]]

^<<v14-20-17,17>>^ Vocês não precisarão lutar nessa batalha. Tomem suas posições; permaneçam firmes e vejam o livramento que o Senhor lhes dará, ó Judá, ó Jerusalém. Não tenham medo nem se desanimem. Saiam para enfrentá-los amanhã, e o Senhor estará com vocês’ ".

[[v14-20-18]]

^<<v14-20-18,18>>^ Josafá prostrou-se, rosto em terra, e todo o povo de Judá e de Jerusalém prostrou-se em adoração perante o Senhor.

[[v14-20-19]]

^<<v14-20-19,19>>^ Então os levitas descendentes dos coatitas e dos coreítas levantaram-se e louvaram o Senhor, o Deus de Israel, em alta voz.

[[v14-20-20]]

^<<v14-20-20,20>>^ De madrugada partiram para o deserto de Tecoa. Quando estavam saindo, Josafá lhes disse: "Escutem-me, Judá e povo de Jerusalém! Tenham fé no Senhor, o seu Deus, e vocês serão sustentados; tenham fé nos profetas dele e vocês terão a vitória".

[[v14-20-21]]

^<<v14-20-21,21>>^ Depois de consultar o povo, Josafá nomeou alguns homens para cantarem ao Senhor e o louvarem pelo esplendor de sua santidade, indo à frente do exército, cantando: "Dêem graças ao Senhor, pois o seu amor dura para sempre".

[[v14-20-22]]

^<<v14-20-22,22>>^ Quando começaram a cantar e a entoar louvores, o Senhor preparou emboscadas contra os homens de Amom, de Moabe e dos montes de Seir que estavam invadindo Judá, e eles foram derrotados.

[[v14-20-23]]

^<<v14-20-23,23>>^ Os amonitas e os moabitas atacaram os dos montes de Seir para destruí-los e aniquilá-los. Depois de massacrarem os homens de Seir, destruiram-se uns aos outros.

[[v14-20-24]]

^<<v14-20-24,24>>^ Quando os homens de Judá foram para o lugar de onde se avista o deserto e olharam para o imenso exército, viram somente cadáveres no chão; ninguém havia escapado.

[[v14-20-25]]

^<<v14-20-25,25>>^ Então, Josafá e os seus soldados foram saquear os cadáveres e encontraram entre eles grande quantidade de equipamentos e roupas, e também objetos de valor; passaram três dias saqueando, mas havia mais do que eram capazes de levar.

[[v14-20-26]]

^<<v14-20-26,26>>^ No quarto dia eles se reuniram no vale de Beraca, onde louvaram o Senhor. Por isso até hoje ele é chamado vale de Beraca.

[[v14-20-27]]

^<<v14-20-27,27>>^ Depois sob a liderança de Josafá, todos os homens de Judá e de Jerusalém voltaram alegres para Jerusalém, pois o Senhor lhes enchera de alegria, dando-lhes vitória sobre os seus inimigos.

[[v14-20-28]]

^<<v14-20-28,28>>^ Entraram em Jerusalém e foram ao templo do Senhor, ao som de liras, harpas e cornetas.

[[v14-20-29]]

^<<v14-20-29,29>>^ O temor de Deus veio sobre todas as nações, quando souberam como o Senhor havia lutado contra os inimigos de Israel.

[[v14-20-30]]

^<<v14-20-30,30>>^ E o reino de Josafá manteve-se em paz, pois o seu Deus lhe concedeu paz em todas as suas fronteiras.

[[v14-20-31]]

^<<v14-20-31,31>>^ Assim Josafá reinou sobre Judá. Ele tinha trinta e cinco anos de idade quando se tornou rei, e reinou vinte e cinco anos em Jerusalém. O nome da sua mãe era Azuba, filha de Sili.

[[v14-20-32]]

^<<v14-20-32,32>>^ Ele andou nos caminhos de Asa, seu pai, e não se desviou deles; fez o que o Senhor aprova.

[[v14-20-33]]

^<<v14-20-33,33>>^ Contudo, não acabou com os altares idólatras, e o povo ainda não havia firmado o coração no Deus dos seus antepassados.

[[v14-20-34]]

^<<v14-20-34,34>>^ Os demais acontecimentos do reinado de Josafá, do início ao fim, estão escritos nos relatos de Jeú, filho de Hanani, e incluídos nos registros históricos dos reis de Israel.

[[v14-20-35]]

^<<v14-20-35,35>>^ Posteriormente, Josafá, rei de Judá, fez um tratado com Acazias, rei de Israel, que tinha vida ímpia.

[[v14-20-36]]

^<<v14-20-36,36>>^ Era um tratado para a construção de navios mercantes. Depois de serem construídos os navios em Eziom-Geber,

[[v14-20-37]]

^<<v14-20-37,37>>^ Eliézer, filho de Dodava de Maressa, profetizou contra Josafá, dizendo: "Por haver feito um tratado com Acazias, o Senhor destruirá o que você fez". Assim, os navios naufragaram e não puderam sair para negociar.

'''

xref:014-2-cronicas/014-2-cronicas-019.adoc#v14-19-0[&#60; Capítulo Anterior] | <<v14-20-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-021.adoc#v14-21-0[Próximo Capítulo &#62;]