include::./index.adoc[]

[[v14-29-0]]
=== 2 Crônicas, 29
// nvi ?, NVI - Nova Versão Internacional

[[v14-29-1]]

^<<v14-29-1,1>>^ Ezequias tinha vinte e cinco anos de idade quando começou a reinar, e reinou vinte e nove anos em Jerusalém. O nome de sua mãe era Abia, filha de Zacarias.

[[v14-29-2]]

^<<v14-29-2,2>>^ Ele fez o que o Senhor aprova, tal como tinha feito Davi, seu predecessor.

[[v14-29-3]]

^<<v14-29-3,3>>^ No primeiro mês do primeiro ano de seu reinado, ele reabriu as portas do templo do Senhor e as consertou.

[[v14-29-4]]

^<<v14-29-4,4>>^ Convocou os sacerdotes e os levitas, reuniu-os na praça que fica no lado leste

[[v14-29-5]]

^<<v14-29-5,5>>^ e disse: "Escutem-me, levitas! Consagrem-se agora e consagrem o templo do Senhor, o Deus dos seus antepassados. Retirem tudo o que é impuro do santuário.

[[v14-29-6]]

^<<v14-29-6,6>>^ Nossos pais foram infiéis; fizeram o que o Senhor, o nosso Deus, reprova e o abandonaram. Desviaram o rosto do local da habitação do Senhor e deram-lhe as costas.

[[v14-29-7]]

^<<v14-29-7,7>>^ Também fecharam as portas do pórtico e apagaram as lâmpadas. Não queimaram incenso nem apresentaram holocausto no santuário para o Deus de Israel.

[[v14-29-8]]

^<<v14-29-8,8>>^ Por isso, a ira do Senhor caiu sobre Judá e sobre Jerusalém; e ele fez deles objeto de espanto, horror e zombaria, conforme vocês podem ver com os seus próprios olhos.

[[v14-29-9]]

^<<v14-29-9,9>>^ Por isso os nossos pais caíram à espada e os nossos filhos, as nossas filhas e as nossas mulheres foram levadas como prisioneiras.

[[v14-29-10]]

^<<v14-29-10,10>>^ Pretendo, pois, agora fazer uma aliança com o Senhor, o Deus de Israel, para que o fogo da sua ira se afaste de nós.

[[v14-29-11]]

^<<v14-29-11,11>>^ Meus filhos, não sejam negligentes agora, pois o Senhor os escolheu para estarem diante dele e o servirem, para ministrarem perante ele e queimarem incenso".

[[v14-29-12]]

^<<v14-29-12,12>>^ Então estes levitas puseram-se a trabalhar: dentre os descendentes de Coate: Maate, filho de Amasai, e Joel, filho de Azarias; dentre os descendentes de Merari: Quis, filho de Abdi, e Azarias, filho de Jealelel; dentre os descendentes de Gérson: Joá, filho de Zima, e Éden, filho de Joá;

[[v14-29-13]]

^<<v14-29-13,13>>^ dentre os descendentes de Elisafã: Sinri e Jeuel; dentre os descendentes de Asafe: Zacarias e Matanias;

[[v14-29-14]]

^<<v14-29-14,14>>^ dentre os descendentes de Hemã: Jeuel e Simei; dentre os descendentes de Jedutum: Semaías e Uziel.

[[v14-29-15]]

^<<v14-29-15,15>>^ Tendo reunido e consagrado os seus parentes, os levitas foram purificar o templo do Senhor, conforme o rei havia ordenado em obediência à palavra do Senhor.

[[v14-29-16]]

^<<v14-29-16,16>>^ Os sacerdotes entraram no santuário do Senhor para purificá-lo e trouxeram para o pátio do templo do Senhor todas as coisas impuras que lá havia, e os levitas as levaram para o vale de Cedrom.

[[v14-29-17]]

^<<v14-29-17,17>>^ Começaram a consagração no dia primeiro do primeiro mês, e no oitavo dia chegaram ao pórtico do Senhor. Durante mais oito dias consagraram o templo do Senhor propriamente dito, terminando tudo no dia dezesseis.

[[v14-29-18]]

^<<v14-29-18,18>>^ Depois foram falar com o rei Ezequias e lhe relataram: "Purificamos todo o templo do Senhor, o altar dos holocaustos e a mesa do pão consagrado, ambos com todos seus utensílios.

[[v14-29-19]]

^<<v14-29-19,19>>^ Preparamos e consagramos todos os utensílios que o rei Acaz, em sua infidelidade, retirou durante o seu reinado. Eles estão em frente do altar do Senhor".

[[v14-29-20]]

^<<v14-29-20,20>>^ Cedo, na manhã seguinte, o rei Ezequias reuniu os líderes da cidade e, juntos, subiram ao templo do Senhor,

[[v14-29-21]]

^<<v14-29-21,21>>^ levando sete novilhos, sete carneiros, sete cordeiros e sete bodes como oferta pelo pecado, em favor da realeza, do santuário e de Judá. O rei ordenou que os sacerdotes, descendentes de Arão, sacrificassem os animais no altar do Senhor.

[[v14-29-22]]

^<<v14-29-22,22>>^ Então os sacerdotes abateram os novilhos e aspergiram o sangue sobre o altar; em seguida fizeram o mesmo com os carneiros e com os cordeiros.

[[v14-29-23]]

^<<v14-29-23,23>>^ Depois, os bodes para a oferta pelo pecado foram levados para diante do rei e da assembléia, que impuseram as mãos sobre eles.

[[v14-29-24]]

^<<v14-29-24,24>>^ Os sacerdotes abateram os bodes e apresentaram o sangue sobre o altar como oferta pelo pecado, para fazer propiciação por todo o Israel, pois era em favor de todo o Israel que o rei havia ordenado o holocausto e a oferta pelo pecado.

[[v14-29-25]]

^<<v14-29-25,25>>^ O rei posicionou os levitas no templo do Senhor, com címbalos, liras e harpas, segundo a prescrição de Davi, de Gade, vidente do rei, e do profeta Natã; isso foi ordenado pelo Senhor, por meio de seus profetas.

[[v14-29-26]]

^<<v14-29-26,26>>^ Assim os levitas ficaram em pé, preparados com os instrumentos de Davi, e os sacerdotes com as cornetas.

[[v14-29-27]]

^<<v14-29-27,27>>^ Então Ezequias ordenou que sacrificassem o holocausto sobre o altar. Iniciado o sacrifício, começou também o canto ao Senhor, ao som das cornetas e dos instrumentos de Davi, rei de Israel.

[[v14-29-28]]

^<<v14-29-28,28>>^ Toda a assembléia prostrou-se em adoração, enquanto os músicos cantavam e os corneteiros tocavam, até que terminou o holocausto.

[[v14-29-29]]

^<<v14-29-29,29>>^ Então o rei e todos os presentes ajoelharam-se e adoraram.

[[v14-29-30]]

^<<v14-29-30,30>>^ O rei Ezequias e seus oficiais ordenaram aos levitas que louvassem o Senhor com as palavras de Davi e do vidente Asafe. Eles louvaram com alegria, depois inclinaram suas cabeças e adoraram.

[[v14-29-31]]

^<<v14-29-31,31>>^ Disse então Ezequias: "Agora que vocês se dedicaram ao Senhor, tragam sacrifícios e ofertas de gratidão ao templo do Senhor". Assim, a comunidade levou sacrifícios e ofertas de gratidão, e alguns, espontaneamente, levaram também holocaustos.

[[v14-29-32]]

^<<v14-29-32,32>>^ Esses holocaustos que a assembléia ofertou ao Senhor foram setenta bois, cem carneiros e duzentos cordeiros.

[[v14-29-33]]

^<<v14-29-33,33>>^ Os animais consagrados como sacrifícios chegaram a seiscentos bois e três mil ovelhas e bodes.

[[v14-29-34]]

^<<v14-29-34,34>>^ Como os sacerdotes eram muito poucos para tirar a pele de todos os holocaustos, os seus parentes, os levitas, os ajudaram até o fim da tarefa e até que outros sacerdotes se consagrassem, pois os levitas demoraram menos para se consagrarem do que os sacerdotes.

[[v14-29-35]]

^<<v14-29-35,35>>^ Houve holocaustos em grande quantidade, oferecidos com a gordura das ofertas de comunhão e com as ofertas derramadas que acompanhavam esses holocaustos. Assim foi restabelecido o culto no templo do Senhor.

[[v14-29-36]]

^<<v14-29-36,36>>^ Ezequias e todo o povo regozijavam-se com o que Deus havia feito por seu povo, e tudo em tão pouco tempo.

'''

xref:014-2-cronicas/014-2-cronicas-028.adoc#v14-28-0[&#60; Capítulo Anterior] | <<v14-29-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-030.adoc#v14-30-0[Próximo Capítulo &#62;]