include::./index.adoc[]

[[v14-28-0]]
=== 2 Crônicas, 28
// nvi ?, NVI - Nova Versão Internacional

[[v14-28-1]]

^<<v14-28-1,1>>^ Acaz tinha vinte anos de idade quando começou a reinar, e reinou dezesseis anos em Jerusalém. Ao contrário de Davi, seu predecessor, não fez o que o Senhor aprova.

[[v14-28-2]]

^<<v14-28-2,2>>^ Ele andou nos caminhos dos reis de Israel e fez ídolos de metal para adorar os baalins.

[[v14-28-3]]

^<<v14-28-3,3>>^ Queimou sacrifícios no vale de Ben-Hinom e chegou até a queimar seus filhos em sacrifício, imitando os costumes detestáveis das nações que o Senhor havia expulsado de diante dos israelitas.

[[v14-28-4]]

^<<v14-28-4,4>>^ Também ofereceu sacrifícios e queimou incenso nos altares idólatras, no alto das colinas e debaixo de toda árvore frondosa.

[[v14-28-5]]

^<<v14-28-5,5>>^ Por isso o Senhor, o seu Deus, entregou-o nas mãos do rei da Síria. Os arameus o derrotaram, fizeram muitos prisioneiros entre o seu povo e os levaram para Damasco. Israel também lhe infligiu grande derrota.

[[v14-28-6]]

^<<v14-28-6,6>>^ Num único dia, Peca, filho de Remalias, matou cento e vinte mil soldados corajosos de Judá; pois Judá havia abandonado o Senhor, o Deus dos seus antepassados.

[[v14-28-7]]

^<<v14-28-7,7>>^ Zicri, guerreiro efraimita, matou Maaséias, filho do rei, Azricão, oficial encarregado do palácio, e Elcana, o braço direito do rei.

[[v14-28-8]]

^<<v14-28-8,8>>^ Os israelitas levaram para Samaria duzentos mil prisioneiros dentre os seus parentes, incluindo mulheres, meninos e meninas. Também levaram muitos despojos.

[[v14-28-9]]

^<<v14-28-9,9>>^ Mas um profeta do Senhor, chamado Odede, estava em Samaria e saiu ao encontro do exército. Ele lhes disse: "Estando irado contra Judá, o Senhor, o Deus dos seus antepassados, entregou-os nas mãos de vocês. Mas a fúria com que vocês os mataram chegou aos céus.

[[v14-28-10]]

^<<v14-28-10,10>>^ E agora ainda pretendem escravizar homens e mulheres de Judá e de Jerusalém. Vocês também não são culpados de pecados contra o Senhor, o seu Deus?

[[v14-28-11]]

^<<v14-28-11,11>>^ Agora, ouçam-me! Mandem de volta seus irmãos que vocês fizeram prisioneiros, pois o fogo da ira do Senhor está sobre vocês".

[[v14-28-12]]

^<<v14-28-12,12>>^ Então Azarias, filho de Joanã, Berequias, filho de Mesilemote, Jeizquias, filho de Salum, e Amasa, filho de Hadlai, que eram alguns dos chefes de Efraim, questionaram os que estavam chegando da guerra, dizendo:

[[v14-28-13]]

^<<v14-28-13,13>>^ "Não tragam os prisioneiros para cá. Caso contrário seremos culpados diante do Senhor. Vocês querem aumentar ainda mais o nosso pecado e a nossa culpa? A nossa culpa já é grande, e o fogo da sua ira está sobre Israel".

[[v14-28-14]]

^<<v14-28-14,14>>^ Então os soldados libertaram os prisioneiros e colocaram os despojos na presença dos líderes e de toda a assembléia.

[[v14-28-15]]

^<<v14-28-15,15>>^ Os homens citados nominalmente apanharam os prisioneiros e com as roupas e as sandálias dos despojos vestiram todos os que estavam nus. Deram-lhes comida, bebida, e bálsamo medicinal. Puseram sobre jumentos todos aqueles que estavam fracos. Assim os levaram de volta a seus patrícios residentes em Jericó, a cidade das Palmeiras, e voltaram para Samaria.

[[v14-28-16]]

^<<v14-28-16,16>>^ Nessa época, o rei Acaz enviou mensageiros ao rei da Assíria para pedir-lhe ajuda.

[[v14-28-17]]

^<<v14-28-17,17>>^ Os edomitas tinham voltado a atacar Judá fazendo prisioneiros,

[[v14-28-18]]

^<<v14-28-18,18>>^ e os filisteus atacaram cidades na Sefelá e no sul de Judá. Conquistaram e ocuparam Bete-Semes, Aijalom e Gederote, bem como Socó, Timna e Ginzo, com os seus povoados ao redor.

[[v14-28-19]]

^<<v14-28-19,19>>^ O Senhor humilhou Judá por causa de Acaz, rei de Israel, por sua conduta desregrada em Judá, muito infiel ao Senhor.

[[v14-28-20]]

^<<v14-28-20,20>>^ Quando chegou Tiglate-Pileser, rei da Assíria, causou-lhe problemas em vez de ajudá-lo.

[[v14-28-21]]

^<<v14-28-21,21>>^ Acaz apanhou algumas coisas do templo do Senhor, do palácio real e dos líderes e ofereceu-as ao rei da Assíria, mas isso não adiantou.

[[v14-28-22]]

^<<v14-28-22,22>>^ Mesmo nessa época em que passou por tantas dificuldades, o rei Acaz tornou-se ainda mais infiel ao Senhor.

[[v14-28-23]]

^<<v14-28-23,23>>^ Ele ofereceu sacrifícios aos deuses de Damasco que o haviam derrotado, pois pensava: "Já que os deuses da Síria os têm ajudado, oferecerei sacrifícios a eles para que me ajudem também". Mas eles foram a causa da sua ruína e da ruína de todo o Israel.

[[v14-28-24]]

^<<v14-28-24,24>>^ Acaz juntou os utensílios do templo de Deus e os retirou de lá. Trancou as portas do templo do Senhor e ergueu altares em todas as esquinas de Jerusalém.

[[v14-28-25]]

^<<v14-28-25,25>>^ Em todas as cidades de Judá construiu altares idólatras para queimar sacrifícios a outros deuses e provocou a ira do Senhor, o Deus dos seus antepassados.

[[v14-28-26]]

^<<v14-28-26,26>>^ Os demais acontecimentos de seu reinado e todos os seus atos, do início ao fim, estão escritos nos registros históricos dos reis de Judá e de Israel.

[[v14-28-27]]

^<<v14-28-27,27>>^ Acaz descansou com os seus antepassados e foi sepultado na cidade de Jerusalém, mas não nos túmulos dos reis de Israel. Seu filho Ezequias foi o seu sucessor.

'''

xref:014-2-cronicas/014-2-cronicas-027.adoc#v14-27-0[&#60; Capítulo Anterior] | <<v14-28-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-029.adoc#v14-29-0[Próximo Capítulo &#62;]