include::./index.adoc[]

[[v14-5-0]]
=== 2 Crônicas, 5
// nvi ?, NVI - Nova Versão Internacional

[[v14-5-1]]

^<<v14-5-1,1>>^ Terminada toda a obra que Salomão havia realizado para o templo do Senhor, ele trouxe as coisas que seu pai Davi tinha consagrado e colocou junto com os tesouros do templo de Deus: a prata, o ouro e todos os utensílios.

[[v14-5-2]]

^<<v14-5-2,2>>^ Então Salomão reuniu em Jerusalém as autoridades de Israel e todos os líderes das tribos e os chefes das famílias israelitas, para levarem de Sião, a cidade de Davi, a arca da aliança do Senhor.

[[v14-5-3]]

^<<v14-5-3,3>>^ E todos os homens de Israel uniram-se ao rei por ocasião da festa, no sétimo mês.

[[v14-5-4]]

^<<v14-5-4,4>>^ Quando todas as autoridades de Israel chegaram, os levitas pegaram a arca

[[v14-5-5]]

^<<v14-5-5,5>>^ e a levaram, com a Tenda do Encontro e com todos os seus utensílios sagrados. Foram os sacerdotes levitas que levaram tudo.

[[v14-5-6]]

^<<v14-5-6,6>>^ O rei Salomão e toda a comunidade de Israel que se havia reunido a ele diante da arca, sacrificaram tantas ovelhas e bois que nem era possível contar.

[[v14-5-7]]

^<<v14-5-7,7>>^ Os sacerdotes levaram a arca da aliança do Senhor para o seu lugar no santuário interno do templo, no Lugar Santíssimo, e a colocaram debaixo das asas dos querubins.

[[v14-5-8]]

^<<v14-5-8,8>>^ Os querubins tinham suas asas estendidas sobre o lugar da arca e cobriam a arca e as varas utilizadas para o transporte.

[[v14-5-9]]

^<<v14-5-9,9>>^ Essas varas eram tão compridas que as suas pontas, que se estendiam para fora da arca, podiam ser vistas da frente do santuário interno, mas não de fora dele; e elas estão lá até hoje.

[[v14-5-10]]

^<<v14-5-10,10>>^ Na arca havia só as duas tábuas que Moisés tinha colocado quando estava em Horebe, onde o Senhor fez uma aliança com os israelitas depois que saíram do Egito.

[[v14-5-11]]

^<<v14-5-11,11>>^ Então os sacerdotes saíram do Lugar Santo. Todos eles haviam se consagrado, não importando a divisão a que pertenciam.

[[v14-5-12]]

^<<v14-5-12,12>>^ E, todos os levitas que eram músicos — Asafe, Hemã, Jedutum e os filhos e parentes deles — ficaram a leste do altar, vestidos de linho fino, tocando címbalos, harpas e liras, e os acompanhavam cento e vinte sacerdotes tocando cornetas.

[[v14-5-13]]

^<<v14-5-13,13>>^ Os que tocavam cornetas e os cantores, em uníssono, louvaram e agradeceram ao Senhor. Ao som de cornetas, címbalos e outros instrumentos, levantaram suas vozes em louvor ao Senhor e cantaram: "Ele é bom; o seu amor dura para sempre". Então uma nuvem encheu o templo do Senhor,

[[v14-5-14]]

^<<v14-5-14,14>>^ de forma que os sacerdotes não podiam desempenhar o seu serviço, pois a glória do Senhor encheu o templo de Deus.

'''

xref:014-2-cronicas/014-2-cronicas-004.adoc#v14-4-0[&#60; Capítulo Anterior] | <<v14-5-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-006.adoc#v14-6-0[Próximo Capítulo &#62;]