include::./index.adoc[]

[[v14-12-0]]
=== 2 Crônicas, 12
// nvi ?, NVI - Nova Versão Internacional

[[v14-12-1]]

^<<v14-12-1,1>>^ Depois que Roboão se fortaleceu, firmou-se como rei, ele e todo o Israel abandonaram a lei do Senhor.

[[v14-12-2]]

^<<v14-12-2,2>>^ Por terem sido infiéis ao Senhor, Sisaque, rei do Egito, atacou Jerusalém no quinto ano do reinado de Roboão.

[[v14-12-3]]

^<<v14-12-3,3>>^ Com mil e duzentos carros de guerra, sessenta mil cavaleiros e um exército incontável de líbios, suquitas e etíopes, que vieram do Egito com ele,

[[v14-12-4]]

^<<v14-12-4,4>>^ conquistou as cidades fortificadas de Judá e chegou até Jerusalém.

[[v14-12-5]]

^<<v14-12-5,5>>^ Então o profeta Semaías apresentou-se a Roboão e aos líderes de Judá que se haviam reunido em Jerusalém, fugindo de Sisaque, e lhes disse: "Assim diz o Senhor: ‘Vocês me abandonaram; por isso eu agora os abandono, entregando-os a Sisaque’ ".

[[v14-12-6]]

^<<v14-12-6,6>>^ Os líderes de Israel e o rei se humilharam e disseram: "O Senhor é justo".

[[v14-12-7]]

^<<v14-12-7,7>>^ Quando o Senhor viu que eles se humilharam, veio a Semaías esta palavra do Senhor: "Visto que eles se humilharam, não os destruirei, mas em breve lhes darei livramento. Minha ira não será derramada sobre Jerusalém por meio de Sisaque.

[[v14-12-8]]

^<<v14-12-8,8>>^ Eles, contudo, ficarão sujeitos a ele, para que aprendam a diferença entre servir a mim e servir aos reis de outras terras".

[[v14-12-9]]

^<<v14-12-9,9>>^ Quando Sisaque, rei do Egito, atacou Jerusalém, levou todos os tesouros do templo do Senhor e do palácio real, inclusive os escudos de ouro que Salomão havia feito.

[[v14-12-10]]

^<<v14-12-10,10>>^ Por isso o rei Roboão mandou fazer escudos de bronze para substituí-los, e os entregou aos chefes da guarda da entrada do palácio real.

[[v14-12-11]]

^<<v14-12-11,11>>^ Sempre que o rei ia ao templo do Senhor, os guardas empunhavam os escudos, e, em seguida, os devolviam à sala da guarda.

[[v14-12-12]]

^<<v14-12-12,12>>^ Como Roboão se humilhou, a ira do Senhor afastou-se dele, e ele não foi totalmente destruído. Aliás, ainda havia algo de bom em Judá.

[[v14-12-13]]

^<<v14-12-13,13>>^ O rei Roboão firmou-se no poder em Jerusalém e continuou a reinar. Tinha quarenta e um anos de idade quando começou a reinar, e reinou dezessete anos em Jerusalém, cidade que o Senhor havia escolhido dentre todas as tribos de Israel para nela pôr o seu nome. Sua mãe, uma amonita, chamava-se Naamá.

[[v14-12-14]]

^<<v14-12-14,14>>^ Ele agiu mal porque não dispôs o seu coração para buscar o Senhor.

[[v14-12-15]]

^<<v14-12-15,15>>^ Os demais acontecimentos do reinado de Roboão, do início ao fim, estão escritos nos relatos do profeta Semaías e do vidente Ido, que tratam de genealogias. Houve guerra constante entre Roboão e Jeroboão.

[[v14-12-16]]

^<<v14-12-16,16>>^ Roboão descansou com os seus antepassados e foi sepultado na cidade de Davi; seu filho Abias foi o seu sucessor.

'''

xref:014-2-cronicas/014-2-cronicas-011.adoc#v14-11-0[&#60; Capítulo Anterior] | <<v14-12-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-013.adoc#v14-13-0[Próximo Capítulo &#62;]