include::./index.adoc[]

[[v14-25-0]]
=== 2 Crônicas, 25
// nvi ?, NVI - Nova Versão Internacional

[[v14-25-1]]

^<<v14-25-1,1>>^ Amazias tinha vinte e cinco anos de idade quando começou a reinar, e reinou vinte e nove anos em Jerusalém. O nome de sua mãe era Jeoadã; ela era de Jerusalém.

[[v14-25-2]]

^<<v14-25-2,2>>^ Ele fez o que o Senhor aprova, mas não de todo o coração.

[[v14-25-3]]

^<<v14-25-3,3>>^ Quando sentiu que tinha o reino sob pleno controle, mandou executar os oficiais que haviam assassinado o rei, seu pai.

[[v14-25-4]]

^<<v14-25-4,4>>^ Contudo, não matou os filhos dos assassinos, de acordo com o que está escrito na Lei, no livro de Moisés, onde o Senhor ordenou: "Os pais não morrerão no lugar dos filhos, nem os filhos no lugar dos pais; cada um morrerá pelo seu próprio pecado".

[[v14-25-5]]

^<<v14-25-5,5>>^ Amazias reuniu os homens de Judá e, de acordo com as suas respectivas famílias, nomeou chefes de mil e de cem em todo o Judá e Benjamim. Então convocou todos os de vinte anos para cima e constatou que havia trezentos mil homens prontos para o serviço militar, capazes de empunhar a lança e o escudo.

[[v14-25-6]]

^<<v14-25-6,6>>^ Também contratou em Israel cem mil homens de combate pelo valor de três toneladas e meia de prata.

[[v14-25-7]]

^<<v14-25-7,7>>^ Entretanto, um homem de Deus foi até ele e lhe disse: "Ó, rei, essas tropas de Israel não devem marchar com você, pois o Senhor não está com Israel; não está com ninguém do povo de Efraim.

[[v14-25-8]]

^<<v14-25-8,8>>^ Mesmo que vá e combata corajosamente, Deus o derrotará diante do inimigo, pois tem poder para dar a vitória e a derrota".

[[v14-25-9]]

^<<v14-25-9,9>>^ Amazias perguntou ao homem de Deus: "Mas, e as três toneladas e meia de prata que paguei a estas tropas israelitas? " Ele respondeu: "O Senhor pode dar-lhe muito mais que isso".

[[v14-25-10]]

^<<v14-25-10,10>>^ Amazias, mandou então de volta os soldados de Efraim. Eles ficaram furiosos com Judá e foram embora indignados.

[[v14-25-11]]

^<<v14-25-11,11>>^ Amazias encheu-se de coragem e conduziu o seu exército até o vale do Sal, onde matou dez mil homens de Seir.

[[v14-25-12]]

^<<v14-25-12,12>>^ Também capturou outros dez mil, que levou para o alto de um penhasco e os atirou de lá, e todos eles se espatifaram.

[[v14-25-13]]

^<<v14-25-13,13>>^ Enquanto isso, as tropas que Amazias havia mandado de volta não lhes permitindo participar da guerra, atacaram cidades de Judá, desde Samaria até Bete-Horom. Mataram três mil pessoas e levaram grande quantidade de despojos.

[[v14-25-14]]

^<<v14-25-14,14>>^ Amazias voltou da matança dos edomitas trazendo os deuses do povo de Seir, os quais estabeleceu como seus próprios deuses, inclinou-se diante deles e lhes queimou incenso.

[[v14-25-15]]

^<<v14-25-15,15>>^ Então a ira do Senhor acendeu-se contra Amazias, e ele lhe enviou um profeta, que disse ao rei: "Por que você consulta os deuses desse povo, os quais nem o povo deles puderam salvar de suas mãos? "

[[v14-25-16]]

^<<v14-25-16,16>>^ Enquanto ele ainda falava, o rei o interrompeu: "Por acaso nós o nomeamos conselheiro do rei? Pare! Por que você quer ser morto? " O profeta parou, mas disse: "Sei que Deus decidiu destruí-lo, porque você fez tudo isso e não deu atenção ao meu conselho".

[[v14-25-17]]

^<<v14-25-17,17>>^ Depois de consultar os seus conselheiros, Amazias, rei de Judá, enviou mensageiros a Jeoás, filho de Jeoacaz e neto de Jeú, rei de Israel, com este desafio: "Venha me enfrentar".

[[v14-25-18]]

^<<v14-25-18,18>>^ Contudo, Jeoás, respondeu a Amazias: "O espinheiro do Líbano enviou uma mensagem ao cedro do Líbano: ‘Dê sua filha em casamento a meu filho’. Mas um animal selvagem do Líbano veio e pisoteou o espinheiro.

[[v14-25-19]]

^<<v14-25-19,19>>^ Você diz a si mesmo que derrotou Edom, e agora está arrogante e orgulhoso. Mas fique em casa! Por que provocar uma desgraça que levará você e também Judá à ruína? "

[[v14-25-20]]

^<<v14-25-20,20>>^ Amazias, porém, não quis ouvi-lo, pois Deus mesmo queria entregar Amazias e seu povo a Jeoás, pois pediram conselhos aos deuses de Edom.

[[v14-25-21]]

^<<v14-25-21,21>>^ Então Jeoás, rei de Israel, o atacou. Ele e Amazias, rei de Judá, enfrentaram-se em Bete-Semes, em Judá.

[[v14-25-22]]

^<<v14-25-22,22>>^ Judá foi derrotado por Israel, e seus soldados fugiram para as suas casas.

[[v14-25-23]]

^<<v14-25-23,23>>^ Jeoás capturou Amazias, filho de Joás e neto de Acazias, em Bete-Semes. Então Jeoás levou-o para Jerusalém e derrubou cento e oitenta metros do muro da cidade, desde a porta de Efraim até a porta da Esquina.

[[v14-25-24]]

^<<v14-25-24,24>>^ Ele se apoderou de todo o ouro, de toda a prata e de todos os utensílios encontrados no templo de Deus, que haviam estado sob a guarda de Obede-Edom, e ainda dos tesouros do palácio real. Também fez reféns e, então, voltou para Samaria.

[[v14-25-25]]

^<<v14-25-25,25>>^ Amazias, filho de Joás, rei de Judá, viveu ainda mais quinze anos depois da morte de Jeoás, filho de Jeoacaz, rei de Israel.

[[v14-25-26]]

^<<v14-25-26,26>>^ Os demais acontecimentos do reinado de Amazias, do início ao fim, estão escritos nos registros históricos dos reis de Judá e de Israel.

[[v14-25-27]]

^<<v14-25-27,27>>^ A partir do momento em que Amazias deixou de seguir o Senhor, conspiraram contra ele em Jerusalém, e ele fugiu para Láquis, mas o perseguiram até lá e o mataram.

[[v14-25-28]]

^<<v14-25-28,28>>^ Ele foi trazido de volta a cavalo, e sepultado junto aos seus antepassados na cidade de Judá.

'''

xref:014-2-cronicas/014-2-cronicas-024.adoc#v14-24-0[&#60; Capítulo Anterior] | <<v14-25-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-026.adoc#v14-26-0[Próximo Capítulo &#62;]