include::./index.adoc[]

[[v14-4-0]]
=== 2 Crônicas, 4
// nvi ?, NVI - Nova Versão Internacional

[[v14-4-1]]

^<<v14-4-1,1>>^ Salomão também mandou fazer um altar de bronze de nove metros de comprimento, nove metros de largura e quatro metros e meio de altura.

[[v14-4-2]]

^<<v14-4-2,2>>^ Fez o tanque de metal fundido, redondo, medindo quatro metros e meio de diâmetro e dois metros e vinte e cinco centímetros de altura. Era preciso um fio de treze metros e meio para medir a sua circunferência.

[[v14-4-3]]

^<<v14-4-3,3>>^ Abaixo da borda e ao seu redor havia figuras de touro, de cinco em cinco centímetros. Os touros foram fundidos em duas fileiras numa só peça com o tanque.

[[v14-4-4]]

^<<v14-4-4,4>>^ O tanque ficava sobre doze touros, três voltados para o norte, três para o oeste, três para o sul e três para o leste. Ficava em cima deles, e as pernas traseiras dos touros eram voltadas para o centro.

[[v14-4-5]]

^<<v14-4-5,5>>^ A espessura do tanque era de quatro dedos, e sua borda era como a borda de um cálice, como uma flor de lírio. Tinha capacidade de sessenta e seis mil litros.

[[v14-4-6]]

^<<v14-4-6,6>>^ Fez dez pias, colocando cinco no lado sul e cinco no lado norte. Nelas tudo o que era usado nos holocaustos era lavado, enquanto que o tanque servia para os sacerdotes se lavarem.

[[v14-4-7]]

^<<v14-4-7,7>>^ Fez dez candelabros de ouro, de acordo com as especificações, e colocou-os no templo, cinco no lado sul e cinco no lado norte.

[[v14-4-8]]

^<<v14-4-8,8>>^ Fez dez mesas e colocou-as no templo, cinco no lado sul e cinco no lado norte. Também fez cem bacias de ouro para aspersão.

[[v14-4-9]]

^<<v14-4-9,9>>^ E fez o pátio dos sacerdotes e o pátio principal com suas portas, e revestiu de bronze as suas portas.

[[v14-4-10]]

^<<v14-4-10,10>>^ Pôs o tanque no lado sul, no canto sudeste do templo.

[[v14-4-11]]

^<<v14-4-11,11>>^ Também fez os jarros, as pás e as bacias para aspersão. Assim, Hirão terminou o trabalho de que fora encarregado pelo rei Salomão, no templo de Deus:

[[v14-4-12]]

^<<v14-4-12,12>>^ as duas colunas; os dois capitéis em forma de taça no alto das colunas; os dois conjuntos de correntes que decoravam os dois capitéis;

[[v14-4-13]]

^<<v14-4-13,13>>^ as quatrocentas romãs para os dois conjuntos de correntes, sendo duas fileiras de romãs para cada conjunto;

[[v14-4-14]]

^<<v14-4-14,14>>^ os dez carrinhos com as suas dez pias;

[[v14-4-15]]

^<<v14-4-15,15>>^ o tanque e os doze touros debaixo dele;

[[v14-4-16]]

^<<v14-4-16,16>>^ e os jarros, as pás, os garfos de carne e todos os utensílios afins. Todos esses utensílios que Hirão-Abi fez a pedido do rei Salomão, para o templo do Senhor, eram de bronze polido.

[[v14-4-17]]

^<<v14-4-17,17>>^ Foi na planície do Jordão, entre Sucote e Zeredá, que o rei os mandou fundir, em moldes de barro.

[[v14-4-18]]

^<<v14-4-18,18>>^ Salomão os fez em tão grande quantidade, a ponto de não se poder determinar o peso do bronze utilizado.

[[v14-4-19]]

^<<v14-4-19,19>>^ Além desses, Salomão mandou fazer também todos estes outros utensílios para o templo de Deus: o altar de ouro; as mesas sobre as quais ficavam os pães da Presença;

[[v14-4-20]]

^<<v14-4-20,20>>^ os candelabros de ouro puro com suas lâmpadas, para iluminarem diante do santuário interno, conforme determinado;

[[v14-4-21]]

^<<v14-4-21,21>>^ as flores, as lâmpadas e as tenazes de ouro maciço;

[[v14-4-22]]

^<<v14-4-22,22>>^ os cortadores de pavio, as bacias para aspersão, as tigelas, os incensários de ouro puro e as portas de ouro do templo: tanto as portas da sala interna, o Lugar Santíssimo, quanto as portas do átrio principal.

'''

xref:014-2-cronicas/014-2-cronicas-003.adoc#v14-3-0[&#60; Capítulo Anterior] | <<v14-4-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-005.adoc#v14-5-0[Próximo Capítulo &#62;]