include::./index.adoc[]

[[v14-26-0]]
=== 2 Crônicas, 26
// nvi ?, NVI - Nova Versão Internacional

[[v14-26-1]]

^<<v14-26-1,1>>^ Então todo o povo de Judá proclamou rei a Uzias, de dezesseis anos de idade, no lugar de seu pai, Amazias.

[[v14-26-2]]

^<<v14-26-2,2>>^ Foi ele quem reconquistou e reconstruiu a cidade de Elate para Judá, depois que Amazias descansou com os seus antepassados.

[[v14-26-3]]

^<<v14-26-3,3>>^ Uzias tinha dezesseis anos de idade quando se tornou rei, e reinou cinqüenta e dois anos em Jerusalém. Sua mãe era de Jerusalém e chamava-se Jecolias.

[[v14-26-4]]

^<<v14-26-4,4>>^ Ele fez o que o Senhor aprova, tal como o seu pai Amazias;

[[v14-26-5]]

^<<v14-26-5,5>>^ e buscou a Deus durante a vida de Zacarias, que o instruiu no temor de Deus. Enquanto buscou o Senhor, Deus o fez prosperar.

[[v14-26-6]]

^<<v14-26-6,6>>^ Ele saiu à guerra contra os filisteus e derrubou os muros de Gate, de Jabne e de Asdode. Depois reconstruiu cidades próximo a Asdode e em outros lugares do território filisteu.

[[v14-26-7]]

^<<v14-26-7,7>>^ Deus o ajudou contra os filisteus, contra os árabes que viviam em Gur-Baal e contra os meunitas.

[[v14-26-8]]

^<<v14-26-8,8>>^ Os amonitas pagavam tributo a Uzias, e sua fama estendeu-se até a fronteira do Egito, pois havia se tornado muito poderoso.

[[v14-26-9]]

^<<v14-26-9,9>>^ Uzias construiu torres fortificadas em Jerusalém, na porta da Esquina, na porta do Vale e no canto do muro.

[[v14-26-10]]

^<<v14-26-10,10>>^ Também construiu torres no deserto e cavou muitas cisternas, pois ele possuía muitos rebanhos na Sefelá e na planície. Ele mantinha trabalhadores em seus campos e em suas vinhas, nas colinas e nas terras férteis, pois gostava da agricultura.

[[v14-26-11]]

^<<v14-26-11,11>>^ Uzias possuía um exército bem preparado, organizado em divisões de acordo com o número dos soldados convocados pelo secretário Jeiel e pelo oficial Maaséias, sob o comando de Hananias, um dos oficiais do rei.

[[v14-26-12]]

^<<v14-26-12,12>>^ O total de chefes de família no comando dos homens de combate era de dois mil e seiscentos.

[[v14-26-13]]

^<<v14-26-13,13>>^ Sob o comando deles estava um exército de trezentos e sete mil e quinhentos homens treinados para a guerra, uma força poderosíssima que apoiava o rei contra os seus inimigos.

[[v14-26-14]]

^<<v14-26-14,14>>^ Uzias providenciou escudos, lanças, capacetes, couraças, arcos e atiradeiras de pedras para todo o exército.

[[v14-26-15]]

^<<v14-26-15,15>>^ Em Jerusalém, construiu máquinas projetadas por peritos para serem usadas nas torres e nas defesas das esquinas, máquinas que atiravam flechas e grandes pedras. Ele foi extraordinariamente ajudado, e assim tornou-se muito poderoso e a sua fama espalhou-se para longe.

[[v14-26-16]]

^<<v14-26-16,16>>^ Entretanto, depois que Uzias se tornou poderoso, o seu orgulho provocou a sua queda. Ele foi infiel ao Senhor, ao seu Deus, e entrou no templo do Senhor para queimar incenso no altar de incenso.

[[v14-26-17]]

^<<v14-26-17,17>>^ O sumo sacerdote Azarias, e outros oitenta corajosos sacerdotes do Senhor, foram atrás dele.

[[v14-26-18]]

^<<v14-26-18,18>>^ Eles o enfrentaram e disseram: "Não é certo que você, Uzias, queime incenso ao Senhor. Isto é tarefa dos sacerdotes, os descendentes de Arão consagrados para queimar incenso. Saia do santuário, pois você foi infiel e não será honrado por Deus, o Senhor".

[[v14-26-19]]

^<<v14-26-19,19>>^ Uzias, que estava com um incensário na mão, pronto para queimar o incenso, irritou-se e indignou-se contra os sacerdotes; e na mesma hora, na presença deles, diante do altar de incenso no templo do Senhor, surgiu lepra em sua testa.

[[v14-26-20]]

^<<v14-26-20,20>>^ Quando o sumo sacerdote Azarias e todos os outros sacerdotes viram a lepra, expulsaram-no imediatamente do templo. Na verdade, ele mesmo ficou ansioso para sair, pois o Senhor o havia ferido.

[[v14-26-21]]

^<<v14-26-21,21>>^ O rei Uzias sofreu de lepra até o dia em que morreu. Durante todo esse tempo morou numa casa separada, leproso e excluído do templo do Senhor. Seu filho Jotão tomava conta do palácio e governava o povo.

[[v14-26-22]]

^<<v14-26-22,22>>^ Os demais acontecimentos do reinado de Uzias, do início ao fim, foram registrados pelo profeta Isaías, filho de Amoz.

[[v14-26-23]]

^<<v14-26-23,23>>^ Uzias descansou com os seus antepassados e foi sepultado perto deles, num cemitério que pertencia aos reis, pois o povo dizia: "Ele tinha lepra". Seu filho Jotão foi o seu sucessor.

'''

xref:014-2-cronicas/014-2-cronicas-025.adoc#v14-25-0[&#60; Capítulo Anterior] | <<v14-26-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-027.adoc#v14-27-0[Próximo Capítulo &#62;]