include::./index.adoc[]

[[v14-11-0]]
=== 2 Crônicas, 11
// nvi ?, NVI - Nova Versão Internacional

[[v14-11-1]]

^<<v14-11-1,1>>^ Quando Roboão chegou em Jerusalém, convocou cento e oitenta mil homens de combate, das tribos de Judá e de Benjamim, para guerrearem contra Israel e recuperarem o reino para Roboão.

[[v14-11-2]]

^<<v14-11-2,2>>^ Entretanto, veio esta palavra do Senhor a Semaías, homem de Deus:

[[v14-11-3]]

^<<v14-11-3,3>>^ "Diga a Roboão, filho de Salomão, rei de Judá, e a todos os israelitas de Judá e de Benjamim:

[[v14-11-4]]

^<<v14-11-4,4>>^ ‘Assim diz o Senhor: Não saiam à guerra contra os seus irmãos. Voltem para casa, todos vocês, pois fui eu que fiz isso’ ". E eles obedeceram à palavra do Senhor e desistiram de marchar contra Jeroboão.

[[v14-11-5]]

^<<v14-11-5,5>>^ Roboão morou em Jerusalém e reconstruiu algumas cidades para a defesa de Judá. Foram elas:

[[v14-11-6]]

^<<v14-11-6,6>>^ Belém, Etã, Tecoa,

[[v14-11-7]]

^<<v14-11-7,7>>^ Bete-Zur, Socó, Adulão,

[[v14-11-8]]

^<<v14-11-8,8>>^ Gate, Maressa, Zife,

[[v14-11-9]]

^<<v14-11-9,9>>^ Adoraim, Láquis, Azeca,

[[v14-11-10]]

^<<v14-11-10,10>>^ Zorá, Aijalom e Hebrom. Essas cidades foram fortificadas em Judá e em Benjamim.

[[v14-11-11]]

^<<v14-11-11,11>>^ Ele fortaleceu as suas defesas e nelas colocou comandantes, com suprimentos de alimentos, azeite e vinho.

[[v14-11-12]]

^<<v14-11-12,12>>^ Armazenou escudos grandes e lanças em todas as cidades, tornando-as muito fortes. Assim, Judá e Benjamim continuaram sob o seu domínio.

[[v14-11-13]]

^<<v14-11-13,13>>^ Os sacerdotes e os levitas de todos os distritos de Israel o apoiaram.

[[v14-11-14]]

^<<v14-11-14,14>>^ Os levitas chegaram até a abandonar as suas pastagens e os seus bens, e foram para Judá e para Jerusalém, porque Jeroboão e seus filhos os haviam rejeitado como sacerdotes do Senhor,

[[v14-11-15]]

^<<v14-11-15,15>>^ nomeando seus próprios sacerdotes para os altares idólatras e para os ídolos que haviam feito em forma de bodes e de bezerros.

[[v14-11-16]]

^<<v14-11-16,16>>^ De todas as tribos de Israel aqueles que estavam realmente dispostos a buscar o Senhor, o Deus de Israel, seguiram os levitas até Jerusalém para oferecerem sacrifícios ao Senhor, ao Deus dos seus antepassados.

[[v14-11-17]]

^<<v14-11-17,17>>^ Eles fortaleceram o reino de Judá e durante três anos apoiaram Roboão, filho de Salomão, andando nos caminhos de Davi e de Salomão durante esse tempo.

[[v14-11-18]]

^<<v14-11-18,18>>^ Roboão casou-se com Maalate, filha de Jeremote e neta de Davi. A mãe de Maalate era Abiail, filha de Eliabe e neta de Jessé.

[[v14-11-19]]

^<<v14-11-19,19>>^ Ela deu-lhe três filhos: Jeús, Semarias e Zaão.

[[v14-11-20]]

^<<v14-11-20,20>>^ Depois ele casou-se com Maaca, filha de Absalão, a qual lhe deu os filhos Abias, Atai, Ziza e Selomite.

[[v14-11-21]]

^<<v14-11-21,21>>^ Roboão amava Maaca, filha de Absalão, mais do que a qualquer outra de suas esposas e concubinas. Ao todo ele teve dezoito esposas e sessenta concubinas, vinte e oito filhos e sessenta filhas.

[[v14-11-22]]

^<<v14-11-22,22>>^ Roboão nomeou Abias, filho de Maaca, o chefe entre os seus irmãos, com o intuito de fazê-lo rei.

[[v14-11-23]]

^<<v14-11-23,23>>^ Ele agiu com sabedoria, dispersando seus filhos pelos distritos de Judá e de Benjamim, e pelas cidades fortificadas. Garantiu-lhes fartas provisões e lhes conseguiu muitas mulheres.

'''

xref:014-2-cronicas/014-2-cronicas-010.adoc#v14-10-0[&#60; Capítulo Anterior] | <<v14-11-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-012.adoc#v14-12-0[Próximo Capítulo &#62;]