include::./index.adoc[]

[[v14-23-0]]
=== 2 Crônicas, 23
// nvi ?, NVI - Nova Versão Internacional

[[v14-23-1]]

^<<v14-23-1,1>>^ No sétimo ano Joiada encorajou-se e fez um acordo com os líderes dos batalhões de cem: Azarias, filho de Jeroão, Ismael, filho de Joanã, Azarias, filho de Obede, Maaséias, filho de Adaías, e Elisafate, filho de Zicri.

[[v14-23-2]]

^<<v14-23-2,2>>^ Eles percorreram todo o Judá e reuniram de todas as cidades, os levitas e os chefes das famílias israelitas. Quando chegaram a Jerusalém,

[[v14-23-3]]

^<<v14-23-3,3>>^ toda a assembléia fez um acordo com o rei no templo de Deus. Joiada lhes disse: "Reinará o filho do rei, conforme o Senhor prometeu acerca dos descendentes de Davi.

[[v14-23-4]]

^<<v14-23-4,4>>^ Vocês vão fazer o seguinte: Um terço de vocês, sacerdotes e levitas que entrarão de serviço no sábado, deverá ficar vigiando nas portas do templo;

[[v14-23-5]]

^<<v14-23-5,5>>^ um terço, no palácio real; e um terço, na porta do Alicerce; e todo o povo estará nos pátios do templo do Senhor.

[[v14-23-6]]

^<<v14-23-6,6>>^ Ninguém deverá entrar no templo do Senhor, exceto os sacerdotes e os levitas de serviço; esses podem entrar porque são consagrados, mas o povo deverá observar o que o Senhor lhes determinou.

[[v14-23-7]]

^<<v14-23-7,7>>^ Os levitas deverão posicionar-se em torno do rei, todos de armas na mão. Matem todo aquele que entrar no templo. Acompanhem o rei aonde quer que ele for".

[[v14-23-8]]

^<<v14-23-8,8>>^ Os levitas e todos os homens de Judá fizeram como o sacerdote Joiada havia ordenado. Cada um levou seus soldados, tanto os que estavam entrando de serviço no sábado como os que estavam saindo, pois o sacerdote Joiada não havia dispensado nenhuma das divisões.

[[v14-23-9]]

^<<v14-23-9,9>>^ Então ele deu aos líderes dos batalhões de cem, as lanças e os escudos grandes e pequenos que haviam pertencido ao rei Davi, e que estavam no templo de Deus.

[[v14-23-10]]

^<<v14-23-10,10>>^ Posicionou todos os homens, todos de arma na mão, em volta do rei, perto do altar e do templo, desde o lado sul até o lado norte do templo.

[[v14-23-11]]

^<<v14-23-11,11>>^ Joiada e seus filhos trouxeram o filho do rei e o coroaram; entregaram-lhe uma cópia da aliança e o proclamaram rei, ungindo-o e gritando: "Viva o rei! "

[[v14-23-12]]

^<<v14-23-12,12>>^ Quando Atalia ouviu o barulho do povo correndo e aclamando o rei, foi ao templo do Senhor, onde estava o povo.

[[v14-23-13]]

^<<v14-23-13,13>>^ Lá ela viu o rei à entrada, de pé junto à coluna. Os oficiais e tocadores de cornetas estavam ao lado do rei, e todo o povo se alegrava ao som das cornetas; os músicos com seus instrumentos musicais dirigiam os louvores. Então Atalia rasgou suas vestes e gritou: "Traição! Traição! "

[[v14-23-14]]

^<<v14-23-14,14>>^ O sacerdote Joiada ordenou aos líderes dos batalhões de cem que estavam no comando das tropas: "Levem-na para fora por entre as fileiras, e matem à espada todo que a seguir". Pois o sacerdote dissera: "Não a matem no templo do Senhor".

[[v14-23-15]]

^<<v14-23-15,15>>^ Então eles a prenderam e levaram à porta dos Cavalos, no terreno do palácio, e lá a mataram.

[[v14-23-16]]

^<<v14-23-16,16>>^ E Joiada fez um acordo pelo qual ele, o povo e o rei seriam o povo do Senhor.

[[v14-23-17]]

^<<v14-23-17,17>>^ Então todo o povo foi ao templo de Baal e o derrubou. Despedaçaram os altares e os ídolos, e mataram Matã, sacerdote de Baal, em frente dos altares.

[[v14-23-18]]

^<<v14-23-18,18>>^ E Joiada confiou a supervisão do templo do Senhor aos sacerdotes levitas, aos quais Davi tinha atribuído tarefas no templo, para apresentarem os holocaustos ao Senhor, conforme está escrito na lei de Moisés, com júbilo e cânticos, segundo as instruções de Davi.

[[v14-23-19]]

^<<v14-23-19,19>>^ Também pôs guardas nas portas do templo do Senhor para que não entrasse ninguém que de alguma forma estivesse impuro.

[[v14-23-20]]

^<<v14-23-20,20>>^ Levou consigo os líderes dos batalhões de cem, os nobres, os governantes do povo e todo o povo e, juntos, conduziram o rei do templo do Senhor ao palácio, passando pela porta superior, e instalaram o rei no trono;

[[v14-23-21]]

^<<v14-23-21,21>>^ e todo o povo se alegrou. A cidade acalmou-se depois que Atalia foi morta à espada.

'''

xref:014-2-cronicas/014-2-cronicas-022.adoc#v14-22-0[&#60; Capítulo Anterior] | <<v14-23-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-024.adoc#v14-24-0[Próximo Capítulo &#62;]