include::./index.adoc[]

[[v14-9-0]]
=== 2 Crônicas, 9
// nvi ?, NVI - Nova Versão Internacional

[[v14-9-1]]

^<<v14-9-1,1>>^ A rainha de Sabá soube da fama de Salomão, e foi a Jerusalém para pô-lo à prova com perguntas difíceis. Quando chegou, acompanhada de uma enorme caravana, com camelos carregados de especiarias, grande quantidade de ouro e pedras preciosas, foi até Salomão e lhe fez todas as perguntas que tinha em mente.

[[v14-9-2]]

^<<v14-9-2,2>>^ Salomão respondeu a todas; nenhuma lhe foi tão difícil que não pudesse responder.

[[v14-9-3]]

^<<v14-9-3,3>>^ Vendo a sabedoria de Salomão, bem como o palácio que ele havia construído,

[[v14-9-4]]

^<<v14-9-4,4>>^ o que era servido em sua mesa, o lugar de seus oficiais, os criados e copeiros, todos uniformizados, e os holocaustos que ele fazia no templo do Senhor, ela ficou impressionada.

[[v14-9-5]]

^<<v14-9-5,5>>^ Disse ela então ao rei: "Tudo o que ouvi em meu país acerca de tuas realizações e de tua sabedoria era verdade.

[[v14-9-6]]

^<<v14-9-6,6>>^ Mas eu não acreditava no que diziam, até ver com os meus próprios olhos. Na realidade, não me contaram nem a metade da grandeza de tua sabedoria; tu ultrapassas em muito o que ouvi.

[[v14-9-7]]

^<<v14-9-7,7>>^ Como devem ser felizes os homens da tua corte, que continuamente estão diante de ti e ouvem a tua sabedoria!

[[v14-9-8]]

^<<v14-9-8,8>>^ Bendito seja o Senhor, o teu Deus, que se agradou de ti e te colocou no trono dele para reinar pelo Senhor, pelo teu Deus. Por causa do amor de teu Deus para com Israel e do seu desejo de preservá-lo para sempre, ele te fez rei, para manter a justiça e a retidão".

[[v14-9-9]]

^<<v14-9-9,9>>^ E ela deu ao rei quatro toneladas e duzentos quilos de ouro e grande quantidade de especiarias e de pedras preciosas. Nunca se viu tantas especiarias tais como aquelas que a rainha de Sabá deu ao rei Salomão.

[[v14-9-10]]

^<<v14-9-10,10>>^ ( Os marinheiros de Hirão e de Salomão trouxeram ouro de Ofir, e também madeira de junípero e pedras preciosas.

[[v14-9-11]]

^<<v14-9-11,11>>^ O rei utilizou a madeira para fazer a escadaria do templo do Senhor e a do palácio real, além de harpas e liras para os músicos. Nunca se havia visto algo semelhante em Judá. )

[[v14-9-12]]

^<<v14-9-12,12>>^ O rei Salomão deu à rainha de Sabá tudo o que ela desejou e pediu; muito mais do que ela lhe tinha trazido. Então ela e seus servos voltaram para o seu país.

[[v14-9-13]]

^<<v14-9-13,13>>^ O peso do ouro que Salomão recebia anualmente era de vinte e três toneladas e trezentos quilos,

[[v14-9-14]]

^<<v14-9-14,14>>^ fora o que os mercadores e os comerciantes traziam. Também todos os reis da Arábia e os governadores do país traziam ouro e prata para Salomão.

[[v14-9-15]]

^<<v14-9-15,15>>^ O rei Salomão fez duzentos escudos grandes de ouro batido, utilizando três quilos e seiscentos gramas de ouro em cada um.

[[v14-9-16]]

^<<v14-9-16,16>>^ Também fez trezentos escudos pequenos de ouro batido, com um quilo e oitocentos gramas de ouro em cada um. O rei os colocou no Palácio da Floresta do Líbano.

[[v14-9-17]]

^<<v14-9-17,17>>^ O rei mandou fazer ainda um grande trono de marfim revestido de ouro puro.

[[v14-9-18]]

^<<v14-9-18,18>>^ O trono tinha seis degraus, e um estrado de ouro fixo nele. Nos dois lados do assento havia braços, com um leão junto a cada braço.

[[v14-9-19]]

^<<v14-9-19,19>>^ Doze leões ficavam nos seis degraus, um de cada lado. Nada igual havia sido feito em nenhum outro reino.

[[v14-9-20]]

^<<v14-9-20,20>>^ Todas as taças do rei Salomão eram de ouro, bem como todos os utensílios do Palácio da Floresta do Líbano. Não havia nada de prata, pois a prata quase não tinha valor nos dias de Salomão.

[[v14-9-21]]

^<<v14-9-21,21>>^ O rei tinha uma frota de navios mercantes tripulados por marinheiros do rei Hirão. Cada três anos a frota voltava, trazendo ouro, prata, marfim, macacos e pavões.

[[v14-9-22]]

^<<v14-9-22,22>>^ O rei Salomão era o mais rico e o mais sábio de todos os reis da terra.

[[v14-9-23]]

^<<v14-9-23,23>>^ Esses pediam audiência a Salomão, para ouvirem a sabedoria que Deus lhe tinha dado.

[[v14-9-24]]

^<<v14-9-24,24>>^ Ano após ano, todos os que vinham traziam algum presente: utensílios de prata e de ouro, mantos, armas e especiarias, cavalos e mulas.

[[v14-9-25]]

^<<v14-9-25,25>>^ Salomão possuía quatro mil estábulos para cavalos e carros, e doze mil cavalos, dos quais mantinha uma parte nas guarnições de algumas cidades e a outra perto dele, em Jerusalém.

[[v14-9-26]]

^<<v14-9-26,26>>^ Ele dominava sobre todos os reis desde o Eufrates até a terra dos filisteus, junto à fronteira do Egito.

[[v14-9-27]]

^<<v14-9-27,27>>^ O rei tornou a prata tão comum em Jerusalém quanto as pedras, e o cedro tão numeroso quanto as figueiras bravas da Sefelá.

[[v14-9-28]]

^<<v14-9-28,28>>^ Os cavalos de Salomão eram importados do Egito e de todos os outros países.

[[v14-9-29]]

^<<v14-9-29,29>>^ Os demais acontecimentos do reinado de Salomão, desde o início até o fim, estão escritos nos relatos do profeta Natã, nas profecias do silonita Aías e nas visões do vidente Ido acerca de Jeroboão, filho de Nebate.

[[v14-9-30]]

^<<v14-9-30,30>>^ Salomão reinou quarenta anos em Jerusalém, sobre todo o Israel.

[[v14-9-31]]

^<<v14-9-31,31>>^ Então descansou com os seus antepassados e foi sepultado na cidade de Davi, seu pai. E o seu filho Roboão foi o seu sucessor.

'''

xref:014-2-cronicas/014-2-cronicas-008.adoc#v14-8-0[&#60; Capítulo Anterior] | <<v14-9-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-010.adoc#v14-10-0[Próximo Capítulo &#62;]