include::./index.adoc[]

[[v14-7-0]]
=== 2 Crônicas, 7
// nvi ?, NVI - Nova Versão Internacional

[[v14-7-1]]

^<<v14-7-1,1>>^ Assim que Salomão acabou de orar, desceu fogo do céu e consumiu o holocausto e os sacrifícios, e a glória do Senhor encheu o templo.

[[v14-7-2]]

^<<v14-7-2,2>>^ Os sacerdotes não conseguiam entrar no templo do Senhor, porque a glória do Senhor o enchia.

[[v14-7-3]]

^<<v14-7-3,3>>^ Quando todos os israelitas viram o fogo descendo e a glória do Senhor sobre o templo, ajoelharam-se no pavimento, chegando o rosto ao chão, adoraram e deram graças ao Senhor, dizendo: "Ele é bom; o seu amor dura para sempre".

[[v14-7-4]]

^<<v14-7-4,4>>^ Então o rei e todo o Israel ofereceram sacrifícios ao Senhor.

[[v14-7-5]]

^<<v14-7-5,5>>^ O rei Salomão ofereceu em sacrifício vinte e dois mil bois e cento e vinte mil ovelhas. Assim o rei e todo o povo fizeram a dedicação do templo de Deus.

[[v14-7-6]]

^<<v14-7-6,6>>^ Os sacerdotes tomaram seus lugares, bem como os levitas, com os instrumentos musicais do Senhor feitos pelo rei Davi para louvar o Senhor cantando: "O seu amor dura para sempre". No outro lado, de frente para os levitas, os sacerdotes tocavam suas cornetas. Todo o povo estava de pé.

[[v14-7-7]]

^<<v14-7-7,7>>^ Salomão consagrou a parte central do pátio, que ficava na frente do templo do Senhor, e ali ofereceu holocaustos e a gordura das ofertas de comunhão, pois o altar de bronze que Salomão tinha construído não comportava os holocaustos, as ofertas de cereal e as porções de gordura.

[[v14-7-8]]

^<<v14-7-8,8>>^ Durante sete dias, Salomão, juntamente com todo o Israel, celebrou a festa; era uma grande multidão, gente vinda desde Lebo-Hamate até o ribeiro do Egito.

[[v14-7-9]]

^<<v14-7-9,9>>^ No oitavo dia realizaram uma assembléia solene. Levaram sete dias para a dedicação do altar, e a festa se prolongou por mais sete dias.

[[v14-7-10]]

^<<v14-7-10,10>>^ No dia vinte e três do sétimo mês, ele mandou o povo para as suas casas. E todos se foram, jubilosos e de coração alegre pelas coisas boas que o Senhor havia feito por Davi e Salomão e por seu povo Israel.

[[v14-7-11]]

^<<v14-7-11,11>>^ Quando Salomão acabou de construir o templo do Senhor e o palácio real, executando bem tudo o que tinha em mente realizar no templo do Senhor e em seu próprio palácio,

[[v14-7-12]]

^<<v14-7-12,12>>^ o Senhor lhe apareceu de noite e disse: "Ouvi sua oração, e escolhi este lugar para mim, como um templo para sacrifícios.

[[v14-7-13]]

^<<v14-7-13,13>>^ "Se eu fechar o céu para que não chova ou mandar que os gafanhotos devorem o país ou sobre o meu povo enviar uma praga,

[[v14-7-14]]

^<<v14-7-14,14>>^ se o meu povo, que se chama pelo meu nome, se humilhar e orar, buscar a minha face e se afastar dos seus maus caminhos, dos céus o ouvirei, perdoarei o seu pecado e curarei a sua terra.

[[v14-7-15]]

^<<v14-7-15,15>>^ De hoje em diante os meus olhos estarão abertos e os meus ouvidos atentos às orações feitas neste lugar.

[[v14-7-16]]

^<<v14-7-16,16>>^ Escolhi e consagrei este templo para que o meu nome esteja nele para sempre. Meus olhos e meu coração nele sempre estarão.

[[v14-7-17]]

^<<v14-7-17,17>>^ "E se você andar segundo a minha vontade como fez seu pai Davi e fizer tudo o que eu lhe ordeno, obedecendo aos meus decretos e às minhas leis,

[[v14-7-18]]

^<<v14-7-18,18>>^ firmarei o seu trono, conforme a aliança que fiz com Davi, seu pai, quando lhe disse: ‘Você nunca deixará de ter um descendente para governar Israel’.

[[v14-7-19]]

^<<v14-7-19,19>>^ "Mas, se vocês se afastarem de mim e abandonarem os decretos e os mandamentos que lhes dei, e prestarem culto a outros deuses e adorá-los,

[[v14-7-20]]

^<<v14-7-20,20>>^ desarraigarei Israel da minha terra, que lhes dei, e lançarei para longe da minha presença este templo que consagrei ao meu nome. Farei que ele se torne motivo de zombaria entre todos os povos.

[[v14-7-21]]

^<<v14-7-21,21>>^ E embora agora este templo seja imponente, todos os que passarem por ele ficarão espantados e perguntarão: ‘Por que o Senhor fez uma coisa dessas a esta terra e a este templo? ’

[[v14-7-22]]

^<<v14-7-22,22>>^ E a resposta será: ‘Porque abandonaram o Senhor, o Deus dos seus antepassados, que os tirou do Egito, e se apegaram a outros deuses, adorando-os e prestando-lhes culto; por isso ele trouxe sobre eles toda esta desgraça’ ".

'''

xref:014-2-cronicas/014-2-cronicas-006.adoc#v14-6-0[&#60; Capítulo Anterior] | <<v14-7-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-008.adoc#v14-8-0[Próximo Capítulo &#62;]