include::./index.adoc[]

[[v14-17-0]]
=== 2 Crônicas, 17
// nvi ?, NVI - Nova Versão Internacional

[[v14-17-1]]

^<<v14-17-1,1>>^ Josafá, filho de Asa, foi o seu sucessor e fortaleceu-se contra Israel.

[[v14-17-2]]

^<<v14-17-2,2>>^ Posicionou tropas em todas as cidades fortificadas de Judá e pôs guarnições em Judá e nas cidades de Efraim que seu pai, Asa, tinha conquistado.

[[v14-17-3]]

^<<v14-17-3,3>>^ O Senhor esteve com Josafá porque, em seus primeiros anos, ele andou nos caminhos que seu pai Davi tinha seguido. Não consultou os baalins,

[[v14-17-4]]

^<<v14-17-4,4>>^ mas buscou o Deus de seu pai e obedeceu aos seus mandamentos, e não imitou as práticas de Israel.

[[v14-17-5]]

^<<v14-17-5,5>>^ O Senhor firmou o reino de Josafá, e todo o Judá lhe trazia presentes, de maneira que teve grande riqueza e honra.

[[v14-17-6]]

^<<v14-17-6,6>>^ Ele seguiu corajosamente os caminhos do Senhor; além disso, retirou de Judá os altares idólatras e os postes sagrados.

[[v14-17-7]]

^<<v14-17-7,7>>^ No terceiro ano de seu reinado, ele enviou seus oficiais Bene-Hail, Obadias, Zacarias, Natanael e Micaías para ensinarem nas cidades de Judá.

[[v14-17-8]]

^<<v14-17-8,8>>^ Com eles foram os levitas Semaías, Netanias, Zebadias, Asael, Semiramote, Jônatas, Adonias, Tobias, Tobe-Adonias e os sacerdotes Elisama e Jeorão.

[[v14-17-9]]

^<<v14-17-9,9>>^ Eles percorreram todas as cidades do reino de Judá, levando consigo o Livro da Lei do Senhor e ensinando o povo.

[[v14-17-10]]

^<<v14-17-10,10>>^ O temor do Senhor caiu sobre todos os reinos ao redor de Judá, de forma que não entraram em guerra contra Josafá.

[[v14-17-11]]

^<<v14-17-11,11>>^ Alguns filisteus levaram presentes a Josafá, além da prata que lhe deram como tributo, e os árabes levaram-lhe rebanhos: sete mil e setecentos carneiros e sete mil e setecentos bodes.

[[v14-17-12]]

^<<v14-17-12,12>>^ Josafá foi se tornando cada vez mais poderoso; construiu fortalezas e cidades-armazéns em Judá,

[[v14-17-13]]

^<<v14-17-13,13>>^ onde guardava enorme quantidade de suprimentos. Também mantinha em Jerusalém homens de combate experientes.

[[v14-17-14]]

^<<v14-17-14,14>>^ A lista desses homens, por famílias, era a seguinte: De Judá, líderes de batalhões de 1. 000: o líder Adna, com 300. 000 homens de combate;

[[v14-17-15]]

^<<v14-17-15,15>>^ em seguida, o líder Joanã, com 280. 000;

[[v14-17-16]]

^<<v14-17-16,16>>^ depois, Amasias, filho de Zicri, que se apresentou voluntariamente para o serviço do Senhor, com 200. 000.

[[v14-17-17]]

^<<v14-17-17,17>>^ De Benjamim: Eliada, um guerreiro valente, com 200. 000 homens armados com arcos e escudos;

[[v14-17-18]]

^<<v14-17-18,18>>^ Jeozabade, com 180. 000 homens armados para a batalha.

[[v14-17-19]]

^<<v14-17-19,19>>^ Esses eram os homens que serviam o rei, além dos que estavam posicionados nas cidades fortificadas em todo o Judá.

'''

xref:014-2-cronicas/014-2-cronicas-016.adoc#v14-16-0[&#60; Capítulo Anterior] | <<v14-17-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-018.adoc#v14-18-0[Próximo Capítulo &#62;]