include::./index.adoc[]

[[v14-35-0]]
=== 2 Crônicas, 35
// nvi ?, NVI - Nova Versão Internacional

[[v14-35-1]]

^<<v14-35-1,1>>^ Josias celebrou a Páscoa do Senhor em Jerusalém, e o cordeiro da Páscoa foi abatido no dia catorze do primeiro mês.

[[v14-35-2]]

^<<v14-35-2,2>>^ Ele nomeou os sacerdotes para as suas responsabilidades e os encorajou a dedicar-se ao serviço no templo do Senhor.

[[v14-35-3]]

^<<v14-35-3,3>>^ Ele disse aos levitas que instruíam todo Israel e haviam sido consagrados ao Senhor: "Ponham a arca sagrada no templo construído por Salomão, filho de Davi, rei de Israel. Vocês não precisam mais levá-la de um lado para outro sobre os ombros. Agora sirvam ao Senhor, ao seu Deus, e ao povo dele, Israel.

[[v14-35-4]]

^<<v14-35-4,4>>^ Preparem-se por famílias, em suas divisões, de acordo com a orientação escrita por Davi, rei de Israel, e por seu filho Salomão.

[[v14-35-5]]

^<<v14-35-5,5>>^ "Fiquem no lugar santo com um grupo de levitas para cada subdivisão das famílias do povo.

[[v14-35-6]]

^<<v14-35-6,6>>^ Abatam os cordeiros da Páscoa, consagrem-se e preparem os cordeiros para os seus irmãos israelitas, fazendo o que o Senhor ordenou por meio de Moisés".

[[v14-35-7]]

^<<v14-35-7,7>>^ Josias deu a todo o povo que ali estava um total de trinta mil ovelhas e cabritos para as ofertas da Páscoa, além de três mil bois; tudo foi tirado dos bens pessoais do rei.

[[v14-35-8]]

^<<v14-35-8,8>>^ Seus oficiais também contribuíram voluntariamente para o povo, para os sacerdotes e para os levitas. Hilquias, Zacarias e Jeiel, os administradores do templo de Deus, deram aos sacerdotes duas mil e seiscentas ovelhas e cabritos e trezentos bois.

[[v14-35-9]]

^<<v14-35-9,9>>^ Também Conanias, junto com seus irmãos Semaías, Natanael e com os líderes dos levitas, Hasabias, Jeiel e Jozabade, ofereceram aos levitas cinco mil ovelhas e cabritos e quinhentos bois.

[[v14-35-10]]

^<<v14-35-10,10>>^ O serviço foi organizado e os sacerdotes assumiram os seus lugares com os levitas em seus turnos, conforme o rei ordenara.

[[v14-35-11]]

^<<v14-35-11,11>>^ Os cordeiros da Páscoa foram abatidos, e os sacerdotes aspergiram o sangue que lhes fora entregue, enquanto os levitas tiravam a pele dos animais.

[[v14-35-12]]

^<<v14-35-12,12>>^ Eles separaram também os holocaustos para dá-los aos grupos das famílias do povo, para que essas os oferecessem ao Senhor, conforme está escrito no livro de Moisés; e fizeram o mesmo com os bois.

[[v14-35-13]]

^<<v14-35-13,13>>^ Assaram os animais da Páscoa sobre o fogo, conforme prescrito, cozinharam as ofertas sagradas em potes, caldeirões e panelas, e serviram rapidamente a todo o povo.

[[v14-35-14]]

^<<v14-35-14,14>>^ Depois disso, os levitas prepararam a parte deles e a dos sacerdotes, pois estes, descendentes de Arão, ficaram sacrificando os holocaustos e as porções de gordura até o anoitecer. Foi por isso que os levitas prepararam a parte deles e a dos sacerdotes, descendentes de Arão.

[[v14-35-15]]

^<<v14-35-15,15>>^ Os músicos, descendentes de Asafe, estavam nos locais prescritos por Davi, e por Asafe, Hemã e Jedutum, videntes do rei. Os porteiros que guardavam cada porta não precisaram deixar os seus postos, pois os seus colegas levitas prepararam as ofertas para eles.

[[v14-35-16]]

^<<v14-35-16,16>>^ Assim, naquele dia, todo o serviço do Senhor foi executado para a celebração da Páscoa e para a apresentação de holocaustos no altar do Senhor, conforme o rei Josias havia ordenado.

[[v14-35-17]]

^<<v14-35-17,17>>^ Os israelitas que estavam presentes celebraram a Páscoa naquele dia e durante sete dias celebraram a festa dos pães sem fermento.

[[v14-35-18]]

^<<v14-35-18,18>>^ A Páscoa não havia sido celebrada dessa maneira em Israel desde os dias do profeta Samuel; e nenhum dos reis de Israel havia celebrado uma Páscoa como esta, como o fez Josias, com os sacerdotes, os levitas e todo o Judá e Israel que estavam ali com o povo de Jerusalém.

[[v14-35-19]]

^<<v14-35-19,19>>^ Esta Páscoa foi celebrada no décimo oitavo ano do reinado de Josias.

[[v14-35-20]]

^<<v14-35-20,20>>^ Depois de tudo o que Josias fez, e depois de colocar em ordem o templo, Neco, rei do Egito, saiu para lutar em Carquemis, junto ao Eufrates, e Josias marchou para combatê-lo.

[[v14-35-21]]

^<<v14-35-21,21>>^ Neco, porém, enviou-lhe mensageiros, dizendo: "Não interfiras nisso, ó rei de Judá. Desta vez não estou atacando a ti, mas a outro reino com o qual estou em guerra. Deus me disse que me apressasse; por isso pára de opor-se a Deus, que está comigo; caso contrário ele o destruirá".

[[v14-35-22]]

^<<v14-35-22,22>>^ Josias, contudo, não quis voltar atrás, e disfarçou-se para enfrentá-lo em combate. Ele não quis ouvir o que Neco lhe disse por ordem de Deus, mas foi combatê-lo na planície de Megido.

[[v14-35-23]]

^<<v14-35-23,23>>^ E na batalha, flecheiros atingiram o rei Josias, pelo que disse aos seus oficiais: "Tirem-me daqui. Estou gravemente ferido".

[[v14-35-24]]

^<<v14-35-24,24>>^ Eles o tiraram do seu carro, colocaram-no em outro e o levaram para Jerusalém, onde morreu. Ele foi sepultado nos túmulos dos seus antepassados, e todos os moradores de Judá e de Jerusalém choraram por ele.

[[v14-35-25]]

^<<v14-35-25,25>>^ Jeremias compôs um cântico de lamento em homenagem a Josias, e até hoje todos os cantores e cantoras homenageiam Josias com cânticos de lamento. Estes se tornaram uma tradição em Israel e estão escritos na Coletânea das Lamentações.

[[v14-35-26]]

^<<v14-35-26,26>>^ Os demais acontecimentos do reinado de Josias e os seus atos piedosos, de acordo com o que está escrito na Lei do Senhor,

[[v14-35-27]]

^<<v14-35-27,27>>^ todos os acontecimentos, do início ao fim, estão escritos nos registros históricos dos reis de Israel e de Judá.

'''

xref:014-2-cronicas/014-2-cronicas-034.adoc#v14-34-0[&#60; Capítulo Anterior] | <<v14-35-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-036.adoc#v14-36-0[Próximo Capítulo &#62;]