include::./index.adoc[]

[[v14-31-0]]
=== 2 Crônicas, 31
// nvi ?, NVI - Nova Versão Internacional

[[v14-31-1]]

^<<v14-31-1,1>>^ Quando a festa acabou, os israelitas saíram pelas cidades de Judá e despedaçaram as pedras sagradas e derrubaram os postes sagrados. Eles destruíram os altares idólatras em todo o Judá e Benjamim, e em Efraim e Manassés. Depois de destruírem tudo, voltaram para as suas cidades, cada um para a sua propriedade.

[[v14-31-2]]

^<<v14-31-2,2>>^ Ezequias designou os sacerdotes e os levitas por turnos, cada um de acordo com os seus deveres, para apresentarem holocaustos e sacrifícios de comunhão, ministrarem, darem graças e cantarem louvores junto às portas da habitação do Senhor.

[[v14-31-3]]

^<<v14-31-3,3>>^ O rei contribuía com seus próprios bens para os holocaustos da manhã e da tarde e para os holocaustos dos sábados, das Luas Novas e das festas fixas, conforme o que está escrito na Lei do Senhor.

[[v14-31-4]]

^<<v14-31-4,4>>^ Ele ordenou ao povo de Jerusalém que desse aos sacerdotes e aos levitas a porção que lhes era devida a fim de que pudessem dedicar-se à Lei do Senhor.

[[v14-31-5]]

^<<v14-31-5,5>>^ Assim que se divulgou essa ordem, os israelitas deram com generosidade o melhor do trigo, do vinho, do óleo, do mel e de tudo o que os campos produziam. Trouxeram o dízimo de tudo. Era uma grande quantidade.

[[v14-31-6]]

^<<v14-31-6,6>>^ Os habitantes de Israel e de Judá que viviam nas cidades de Judá também levaram o dízimo de todos os seus rebanhos e das coisas sagradas dedicadas ao Senhor, o seu Deus, ajuntando-os em muitas pilhas.

[[v14-31-7]]

^<<v14-31-7,7>>^ Começaram a fazer isso no terceiro mês e terminaram no sétimo.

[[v14-31-8]]

^<<v14-31-8,8>>^ Quando Ezequias e os seus oficiais chegaram e viram as pilhas de ofertas, louvaram o Senhor e abençoaram Israel, o seu povo.

[[v14-31-9]]

^<<v14-31-9,9>>^ Ezequias perguntou aos sacerdotes e aos levitas sobre essas ofertas;

[[v14-31-10]]

^<<v14-31-10,10>>^ o sumo sacerdote Azarias, da família de Zadoque, respondeu: "Desde que o povo começou a trazer suas contribuições ao templo do Senhor, temos tido o suficiente para comer e ainda tem sobrado muito, pois o Senhor tem abençoado o seu povo, e esta é a grande quantidade que sobra".

[[v14-31-11]]

^<<v14-31-11,11>>^ Ezequias ordenou que preparassem despensas no templo do Senhor, e assim foi feito.

[[v14-31-12]]

^<<v14-31-12,12>>^ Então recolheram fielmente as contribuições, os dízimos e os presentes dedicados. O levita Conanias foi encarregado dessas coisas, e seu irmão Simei era o seu auxiliar.

[[v14-31-13]]

^<<v14-31-13,13>>^ Jeiel, Azazias, Naate, Asael, Jeremote, Jozabade, Eliel, Ismaquias, Maate e Benaia eram supervisores, subordinados a Conanias e ao seu irmão Simei, por nomeação do rei Ezequias e de Azarias, o oficial encarregado do templo de Deus.

[[v14-31-14]]

^<<v14-31-14,14>>^ Coré, filho do levita Imna, guarda da porta leste, foi encarregado das ofertas voluntárias feitas a Deus, distribuindo as contribuições dedicadas ao Senhor e as ofertas consagradas.

[[v14-31-15]]

^<<v14-31-15,15>>^ Sob o comando dele estavam Éden, Miniamim, Jesua, Semaías, Amarias e Secanias, que, nas cidades dos sacerdotes, com toda a fidelidade distribuíam ofertas aos seus colegas sacerdotes de acordo com seus turnos, tanto aos idosos quanto aos jovens.

[[v14-31-16]]

^<<v14-31-16,16>>^ Eles as distribuíram aos homens e aos meninos de três anos para cima, cujos nomes estavam nos registros genealógicos, também a todos os que entravam no templo do Senhor para realizar suas várias tarefas diárias, de acordo com suas responsabilidades e seus turnos.

[[v14-31-17]]

^<<v14-31-17,17>>^ Os registros genealógicos dos sacerdotes eram feitos segundo suas famílias, o dos levitas de vinte anos para cima, de acordo com suas responsabilidades e seus turnos.

[[v14-31-18]]

^<<v14-31-18,18>>^ O registro incluía todos os filhos pequenos, as mulheres, e os filhos e filhas de todo o grupo, pois os sacerdotes e os levitas haviam sido fiéis em se consagrarem.

[[v14-31-19]]

^<<v14-31-19,19>>^ Entre os sacerdotes, descendentes de Arão, que viviam nas terras de pastagem ao redor de suas cidades, foram nomeados alguns deles, de cidade em cidade, para distribuírem as ofertas a todos os sacerdotes e a todos os que estavam registrados nas genealogias dos levitas.

[[v14-31-20]]

^<<v14-31-20,20>>^ Foi isso que Ezequias fez em todo o reino de Judá. Ele fez o que era bom e certo, e em tudo foi fiel diante do Senhor, do seu Deus.

[[v14-31-21]]

^<<v14-31-21,21>>^ Em tudo o que ele empreendeu no serviço do templo de Deus e na obediência à lei e aos mandamentos, ele buscou o seu Deus e trabalhou de todo o coração; e por isso prosperou.

'''

xref:014-2-cronicas/014-2-cronicas-030.adoc#v14-30-0[&#60; Capítulo Anterior] | <<v14-31-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-032.adoc#v14-32-0[Próximo Capítulo &#62;]