include::./index.adoc[]

[[v14-34-0]]
=== 2 Crônicas, 34
// nvi ?, NVI - Nova Versão Internacional

[[v14-34-1]]

^<<v14-34-1,1>>^ Josias tinha oito anos de idade quando começou a reinar, e reinou trinta e um anos em Jerusalém.

[[v14-34-2]]

^<<v14-34-2,2>>^ Ele fez o que o Senhor aprova e andou nos caminhos de Davi, seu predecessor, sem desviar-se nem para a direita nem para a esquerda.

[[v14-34-3]]

^<<v14-34-3,3>>^ No oitavo ano do seu reinado, sendo ainda bem jovem, ele começou a buscar o Deus de Davi, seu predecessor. No décimo segundo ano, começou a purificar Judá e Jerusalém dos altares idólatras, dos postes sagrados, das imagens esculpidas e dos ídolos de metal.

[[v14-34-4]]

^<<v14-34-4,4>>^ Sob as suas ordens foram derrubados os altares dos baalins; além disso, ele despedaçou os altares de incenso que ficavam acima deles. Também despedaçou e reduziu a pó os postes sagrados, as imagens esculpidas e os ídolos de metal, e os espalhou sobre os túmulos daqueles que lhes haviam oferecido sacrifícios.

[[v14-34-5]]

^<<v14-34-5,5>>^ Depois queimou os ossos dos sacerdotes sobre esses altares, purificando assim Judá e Jerusalém.

[[v14-34-6]]

^<<v14-34-6,6>>^ Nas cidades das tribos de Manassés, de Efraim e de Simeão, e até mesmo de Naftali, e nas ruínas ao redor delas,

[[v14-34-7]]

^<<v14-34-7,7>>^ derrubou os altares e os postes sagrados, esmagou os ídolos, reduzindo-os a pó, e despedaçou todos os altares de incenso espalhados por Israel. Então voltou para Jerusalém.

[[v14-34-8]]

^<<v14-34-8,8>>^ No décimo oitavo ano do seu reinado, a fim de purificar o país e o templo, ele enviou Safã, filho de Azalias, e Maaséias, governador da cidade, junto com Joá, filho do arquivista real Joacaz, para restaurarem o templo do Senhor, do seu Deus.

[[v14-34-9]]

^<<v14-34-9,9>>^ Eles foram entregar ao sumo sacerdote Hilquias a prata que havia sido trazida ao templo de Deus e que os porteiros levitas haviam recolhido das ofertas do povo de Manassés e de Efraim, e de todo o remanescente de Israel, e também de todo o povo de Judá e de Benjamim e dos habitantes de Jerusalém.

[[v14-34-10]]

^<<v14-34-10,10>>^ Então confiaram a prata aos homens nomeados para supervisionarem a reforma no templo do Senhor, que pagavam os trabalhadores que faziam os reparos no templo.

[[v14-34-11]]

^<<v14-34-11,11>>^ Também deram dessa prata aos carpinteiros e aos construtores para comprarem pedras lavradas, e madeira para as juntas e as vigas dos edifícios que os reis de Judá haviam deixado ficar em ruínas.

[[v14-34-12]]

^<<v14-34-12,12>>^ Esses homens fizeram o trabalho com fidelidade. Eram dirigidos por Jaate e Obadias, levitas descendentes de Merari, e Zacarias e Mesulão, descendentes de Coate. Todos os levitas que sabiam tocar instrumentos musicais

[[v14-34-13]]

^<<v14-34-13,13>>^ estavam encarregados dos operários e supervisionavam todos os trabalhadores em todas as funções. Outros levitas eram secretários, oficiais e porteiros.

[[v14-34-14]]

^<<v14-34-14,14>>^ Enquanto recolhiam a prata que tinha sido levada para o templo do Senhor, o sacerdote Hilquias encontrou o livro da Lei do Senhor que havia sido dada por meio de Moisés.

[[v14-34-15]]

^<<v14-34-15,15>>^ Hilquias disse ao secretário Safã: "Encontrei o livro da Lei no templo do Senhor". E o entregou a Safã.

[[v14-34-16]]

^<<v14-34-16,16>>^ Então Safã levou o livro ao rei e lhe informou: "Teus servos estão fazendo tudo o que lhes foi ordenado.

[[v14-34-17]]

^<<v14-34-17,17>>^ Fundiram a prata que estava no templo do Senhor e a confiaram aos supervisores e aos trabalhadores".

[[v14-34-18]]

^<<v14-34-18,18>>^ E acrescentou: "O sacerdote Hilquias entregou-me um livro". E Safã leu trechos do livro para o rei.

[[v14-34-19]]

^<<v14-34-19,19>>^ Assim que o rei ouviu as palavras da Lei, rasgou suas vestes

[[v14-34-20]]

^<<v14-34-20,20>>^ e deu estas ordens a Hilquias, a Aicam, filho de Safã, a Abdom, filho de Mica, ao secretário Safã e ao auxiliar real Asaías:

[[v14-34-21]]

^<<v14-34-21,21>>^ "Vão consultar o Senhor por mim e pelo remanescente de Israel e de Judá acerca do que está escrito neste livro que foi encontrado. A ira do Senhor contra nós deve ser grande, pois os nossos antepassados não obedeceram à palavra do Senhor e não agiram de acordo com tudo o que está escrito neste livro".

[[v14-34-22]]

^<<v14-34-22,22>>^ Hilquias e aqueles que o rei tinha enviado com ele foram falar com a profetisa Hulda, mulher de Salum, responsável pelo guarda-roupa do templo, filho de Tocate e neto de Harás. Ela morava no bairro novo de Jerusalém.

[[v14-34-23]]

^<<v14-34-23,23>>^ Ela lhes disse: "Assim diz o Senhor, o Deus de Israel: ‘Digam ao homem que os enviou a mim:

[[v14-34-24]]

^<<v14-34-24,24>>^ Assim diz o Senhor: Eu vou trazer uma desgraça sobre este lugar e sobre seus habitantes; todas as maldições escritas no livro que foi lido na presença do rei de Judá.

[[v14-34-25]]

^<<v14-34-25,25>>^ Porque me abandonaram e queimaram incenso a outros deuses, provocando-me a ira por meio de todos os ídolos que as mãos deles têm feito, minha ira arderá contra este lugar e não será apagada’.

[[v14-34-26]]

^<<v14-34-26,26>>^ Digam ao rei de Judá, que os enviou para consultar o Senhor: ‘Assim diz o Senhor, o Deus de Israel, acerca das palavras que você ouviu:

[[v14-34-27]]

^<<v14-34-27,27>>^ Já que o seu coração se abriu e você se humilhou diante de Deus quando ouviu o que ele falou contra este lugar e contra os seus habitantes, e você se humilhou diante de mim, rasgou as suas vestes e chorou na minha presença, eu o ouvi, declara o Senhor.

[[v14-34-28]]

^<<v14-34-28,28>>^ Portanto, eu o reunirei aos seus antepassados, e você será sepultado em paz. Seus olhos não verão a desgraça que trarei sobre este lugar e sobre seus habitantes’ ". Então eles levaram a resposta ao rei.

[[v14-34-29]]

^<<v14-34-29,29>>^ Então o rei convocou todas as autoridades de Judá e de Jerusalém.

[[v14-34-30]]

^<<v14-34-30,30>>^ Depois subiu ao templo do Senhor acompanhado por todos os homens de Judá, todo o povo de Jerusalém, os sacerdotes e os levitas: todo o povo, dos mais simples aos mais importantes. Para todos o rei leu em voz alta todas as palavras do Livro da Aliança, que havia sido encontrado no templo do Senhor.

[[v14-34-31]]

^<<v14-34-31,31>>^ Ele tomou o seu lugar e, na presença do Senhor, fez uma aliança, comprometendo-se a seguir o Senhor e obedecer de todo o coração e de toda a alma aos seus mandamentos, seus testemunhos e seus decretos, cumprindo as palavras da aliança escritas naquele livro.

[[v14-34-32]]

^<<v14-34-32,32>>^ Depois fez com que todos em Jerusalém e em Benjamim se comprometessem com a aliança; os habitantes de Jerusalém passaram a cumprir a aliança de Deus, o Deus dos seus antepassados.

[[v14-34-33]]

^<<v14-34-33,33>>^ Josias retirou todos os ídolos detestáveis de todo o território dos israelitas e obrigou todos os que estavam em Israel a servirem ao Senhor, ao seu Deus. E enquanto ele viveu, o povo não deixou de seguir o Senhor, o Deus dos seus antepassados.

'''

xref:014-2-cronicas/014-2-cronicas-033.adoc#v14-33-0[&#60; Capítulo Anterior] | <<v14-34-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-035.adoc#v14-35-0[Próximo Capítulo &#62;]