include::./index.adoc[]

[[v14-19-0]]
=== 2 Crônicas, 19
// nvi ?, NVI - Nova Versão Internacional

[[v14-19-1]]

^<<v14-19-1,1>>^ Quando Josafá, rei de Judá, voltou em segurança ao seu palácio em Jerusalém,

[[v14-19-2]]

^<<v14-19-2,2>>^ o vidente Jeú, filho de Hanani, saiu ao seu encontro e lhe disse: "Será que você devia ajudar os ímpios e amar aqueles que odeiam o Senhor? Por causa disso, a ira do Senhor está sobre você.

[[v14-19-3]]

^<<v14-19-3,3>>^ Contudo, existe em você algo de bom, pois você livrou a terra dos postes sagrados e buscou a Deus de todo o seu coração".

[[v14-19-4]]

^<<v14-19-4,4>>^ Josafá morava em Jerusalém; e saiu de novo entre o povo, desde Berseba até os montes de Efraim, fazendo-o voltar para o Senhor, o Deus dos seus antepassados.

[[v14-19-5]]

^<<v14-19-5,5>>^ Ele nomeou juízes, em cada uma das cidades fortificadas de Judá,

[[v14-19-6]]

^<<v14-19-6,6>>^ dizendo-lhes: "Considerem atentamente aquilo que fazem, pois vocês não estão julgando para o homem, mas para o Senhor, que estará com vocês sempre que derem um veredicto.

[[v14-19-7]]

^<<v14-19-7,7>>^ Agora, que o temor do Senhor esteja sobre vocês. Julguem com cuidado, pois com o Senhor, o nosso Deus, não há injustiça nem parcialidade nem suborno".

[[v14-19-8]]

^<<v14-19-8,8>>^ Também em Jerusalém nomeou Josafá alguns dos levitas, dos sacerdotes e dos chefes de famílias israelitas para julgarem questões da lei do Senhor e resolverem pendências dos habitantes.

[[v14-19-9]]

^<<v14-19-9,9>>^ Deu-lhes as seguintes ordens: "Vocês devem servir com fidelidade e com coração íntegro, no temor do Senhor.

[[v14-19-10]]

^<<v14-19-10,10>>^ Em cada caso que chegar a vocês da parte dos seus irmãos israelitas das outras cidades, seja caso de derramamento de sangue sejam questões referentes à lei, aos mandamentos, aos decretos ou às ordenanças, vocês deverão adverti-los de que não pequem contra o Senhor; caso contrário a ira dele virá sobre vocês e sobre eles. Façam assim, e vocês não pecarão.

[[v14-19-11]]

^<<v14-19-11,11>>^ "Amarias, o sumo sacerdote, estará com vocês para decidir qualquer questão referente à lei do Senhor; Zebadias, filho de Ismael, líder da tribo de Judá, estará com vocês para decidir qualquer questão civil; e os levitas atuarão como oficiais diante de vocês. Cumpram seus deveres com coragem, e esteja o Senhor com aqueles que agirem corretamente".

'''

xref:014-2-cronicas/014-2-cronicas-018.adoc#v14-18-0[&#60; Capítulo Anterior] | <<v14-19-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-020.adoc#v14-20-0[Próximo Capítulo &#62;]