include::./index.adoc[]

[[v14-36-0]]
=== 2 Crônicas, 36
// nvi ?, NVI - Nova Versão Internacional

[[v14-36-1]]

^<<v14-36-1,1>>^ E o povo tomou Jeoacaz, filho de Josias, e proclamou-o rei em Jerusalém, no lugar de seu pai.

[[v14-36-2]]

^<<v14-36-2,2>>^ Jeoacaz tinha vinte e três anos de idade quando começou a reinar, e reinou três meses em Jerusalém.

[[v14-36-3]]

^<<v14-36-3,3>>^ O rei do Egito destronou-o em Jerusalém e impôs a Judá um tributo de três toneladas e meia de prata e trinta e cinco quilos de ouro.

[[v14-36-4]]

^<<v14-36-4,4>>^ O rei do Egito proclamou Eliaquim, irmão de Jeoacaz, rei sobre Judá e sobre Jerusalém, e mudou-lhe o nome para Jeoaquim. Mas Neco levou Jeoacaz, irmão de Eliaquim, para o Egito.

[[v14-36-5]]

^<<v14-36-5,5>>^ Jeoaquim tinha vinte e cinco anos de idade quando começou a reinar, e reinou onze anos em Jerusalém. Ele fez o que o Senhor, o seu Deus, reprova.

[[v14-36-6]]

^<<v14-36-6,6>>^ Nabucodonosor, rei da Babilônia, atacou-o e prendeu-o com algemas de bronze para levá-lo para a Babilônia.

[[v14-36-7]]

^<<v14-36-7,7>>^ E levou também para a Babilônia objetos do templo do Senhor e os colocou no seu templo.

[[v14-36-8]]

^<<v14-36-8,8>>^ Os demais acontecimentos do reinado de Jeoaquim, as coisas detestáveis que fez e tudo o que foi achado contra ele, estão escritos nos registros históricos dos reis de Israel e de Judá. Seu filho Joaquim foi o seu sucessor.

[[v14-36-9]]

^<<v14-36-9,9>>^ Joaquim tinha dezoito anos de idade quando começou a reinar; e reinou três meses e dez dias em Jerusalém. Ele fez o que o Senhor reprova.

[[v14-36-10]]

^<<v14-36-10,10>>^ Na primavera o rei Nabucodonosor mandou levá-lo para a Babilônia, junto com objetos de valor retirados do templo do Senhor, e proclamou Zedequias, tio de Joaquim, rei sobre Judá e sobre Jerusalém.

[[v14-36-11]]

^<<v14-36-11,11>>^ Zedequias tinha vinte e um anos de idade quando começou a reinar, e reinou onze anos em Jerusalém.

[[v14-36-12]]

^<<v14-36-12,12>>^ Ele fez o que o Senhor, o seu Deus, reprova, e não se humilhou diante do profeta Jeremias, que lhe falava como porta-voz do Senhor.

[[v14-36-13]]

^<<v14-36-13,13>>^ Também se revoltou contra o rei Nabucodonosor, que o havia obrigado a fazer um juramento em nome de Deus. Tornou-se muito obstinado e não quis se voltar para o Senhor, o Deus de Israel.

[[v14-36-14]]

^<<v14-36-14,14>>^ Além disso, todos os líderes dos sacerdotes e o povo se tornaram cada vez mais infiéis, seguindo todas as práticas detestáveis das outras nações e contaminando o templo do Senhor, consagrado por ele em Jerusalém.

[[v14-36-15]]

^<<v14-36-15,15>>^ O Senhor, o Deus dos seus antepassados, advertiu-os várias vezes por meio de seus mensageiros, pois ele tinha compaixão de seu povo e do lugar de sua habitação.

[[v14-36-16]]

^<<v14-36-16,16>>^ Mas eles zombaram dos mensageiros de Deus, desprezaram as palavras dele e expuseram ao ridículo os seus profetas, até que a ira do Senhor se levantou contra o seu povo, e já não houve remédio.

[[v14-36-17]]

^<<v14-36-17,17>>^ Ele enviou contra eles o rei dos babilônios, que no santuário matou os seus jovens à espada. Não poupou nem rapazes, nem moças, nem adultos, nem velhos. Deus entregou todos eles nas mãos de Nabucodonosor;

[[v14-36-18]]

^<<v14-36-18,18>>^ este levou para a Babilônia todos os utensílios do templo de Deus, tanto os pequenos como os grandes, juntamente com os tesouros do templo do Senhor, os do rei e os de seus oficiais.

[[v14-36-19]]

^<<v14-36-19,19>>^ Os babilônios incendiaram o templo de Deus e derrubaram o muro de Jerusalém; queimaram todos os palácios e destruíram todos os utensílios de valor que havia neles.

[[v14-36-20]]

^<<v14-36-20,20>>^ Nabucodonosor levou para o exílio, na Babilônia, os remanescentes, que escaparam da espada, para serem seus escravos e dos seus descendentes, até à época do domínio persa.

[[v14-36-21]]

^<<v14-36-21,21>>^ A terra desfrutou os seus descansos sabáticos; descansou durante todo o tempo de sua desolação, até que os setenta anos se completaram, em cumprimento da palavra do Senhor anunciada por Jeremias.

[[v14-36-22]]

^<<v14-36-22,22>>^ No primeiro ano do reinado de Ciro, rei da Pérsia, para que se cumprisse a palavra do Senhor anunciada por Jeremias, o Senhor tocou no coração de Ciro, rei da Pérsia, para que fizesse uma proclamação em todo o território de seu domínio e a pusesse por escrito, nestes termos:

[[v14-36-23]]

^<<v14-36-23,23>>^ "Assim declaro Ciro, rei da Pérsia: ‘O Senhor, o Deus dos céus, deu-me todos os reinos da terra e designou-me para construir-lhe um templo em Jerusalém, na terra de Judá. Quem dentre vocês pertencer ao seu povo vá para Jerusalém, e que o Senhor, o seu Deus, esteja com ele’ ".

'''

xref:014-2-cronicas/014-2-cronicas-035.adoc#v14-35-0[&#60; Capítulo Anterior] | <<v14-36-0,Topo>> | xref:015-esdras/015-esdras-001.adoc#v15-1-0[Próximo Capítulo &#62;]