include::./index.adoc[]

[[v14-15-0]]
=== 2 Crônicas, 15
// nvi ?, NVI - Nova Versão Internacional

[[v14-15-1]]

^<<v14-15-1,1>>^ O Espírito de Deus veio sobre Azarias, filho de Odede.

[[v14-15-2]]

^<<v14-15-2,2>>^ Ele saiu para encontrar-se com Asa e lhe disse: "Escutem-me, Asa e todo o povo de Judá e de Benjamim. O Senhor está com vocês quando vocês estão com ele. Se o buscarem, ele deixará que o encontrem, mas, se o abandonarem, ele os abandonará.

[[v14-15-3]]

^<<v14-15-3,3>>^ Durante muito tempo Israel esteve sem o verdadeiro Deus, sem sacerdote para ensiná-lo e sem a Lei.

[[v14-15-4]]

^<<v14-15-4,4>>^ Mas em sua angústia eles se voltaram para o Senhor, o Deus de Israel; buscaram-no, e ele deixou que o encontrassem.

[[v14-15-5]]

^<<v14-15-5,5>>^ Naqueles dias não era seguro viajar, pois muitos distúrbios afligiam a todos os habitantes do território.

[[v14-15-6]]

^<<v14-15-6,6>>^ Nações e cidades se destruíam umas às outras, pois Deus as estava afligindo com toda espécie de desgraças.

[[v14-15-7]]

^<<v14-15-7,7>>^ Mas, vocês devem ser fortes e não se desanimar, pois o trabalho de vocês será recompensado".

[[v14-15-8]]

^<<v14-15-8,8>>^ Assim que ouviu as palavras e a profecia do profeta Azarias, filho de Odede, o rei Asa encheu-se de coragem. Retirou os ídolos repugnantes de toda a terra de Judá e de Benjamim, e das cidades que havia conquistado nos montes de Efraim, e restaurou o altar do Senhor que estava em frente do pórtico do templo do Senhor.

[[v14-15-9]]

^<<v14-15-9,9>>^ Depois reuniu todo o povo de Judá e de Benjamim; convocou também os que pertenciam a Efraim, a Manassés e a Simeão que viviam entre eles, pois muitos de Israel tinham passado para o lado do rei Asa, ao verem que o Senhor, o seu Deus, estava com ele.

[[v14-15-10]]

^<<v14-15-10,10>>^ Eles se reuniram em Jerusalém no terceiro mês do décimo quinto ano do reinado de Asa.

[[v14-15-11]]

^<<v14-15-11,11>>^ Naquela ocasião sacrificaram ao Senhor setecentos bois e sete mil ovelhas e cabras, do saque que haviam feito.

[[v14-15-12]]

^<<v14-15-12,12>>^ Fizeram um acordo de todo o coração e de toda a alma de buscar o Senhor, o Deus dos seus antepassados.

[[v14-15-13]]

^<<v14-15-13,13>>^ Todo aquele que não buscasse o Senhor, o Deus de Israel, deveria ser morto, gente simples ou importante, homem ou mulher.

[[v14-15-14]]

^<<v14-15-14,14>>^ Fizeram esse juramento ao Senhor em voz alta, bradando ao som de cornetas e trombetas.

[[v14-15-15]]

^<<v14-15-15,15>>^ Todo o povo de Judá alegrou-se com o juramento, pois o havia feito de todo o coração. Eles buscaram a Deus com toda disposição; então ele deixou que o encontrassem e lhes concedeu paz em suas fronteiras.

[[v14-15-16]]

^<<v14-15-16,16>>^ O rei Asa chegou até a depor sua avó Maaca da posição de rainha-mãe, pois ela havia feito um poste sagrado repugnante. Asa derrubou o poste, despedaçou-o e queimou-o no vale do Cedrom.

[[v14-15-17]]

^<<v14-15-17,17>>^ Embora os altares idólatras não tenham sido eliminados de Israel, o coração de Asa foi totalmente dedicado ao Senhor durante toda a sua vida.

[[v14-15-18]]

^<<v14-15-18,18>>^ Ele trouxe para o templo de Deus a prata, o ouro e os utensílios que ele e seu pai haviam consagrado.

[[v14-15-19]]

^<<v14-15-19,19>>^ E não houve mais nenhuma guerra até o trigésimo quinto ano do seu reinado.

'''

xref:014-2-cronicas/014-2-cronicas-014.adoc#v14-14-0[&#60; Capítulo Anterior] | <<v14-15-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-016.adoc#v14-16-0[Próximo Capítulo &#62;]