include::./index.adoc[]

[[v14-32-0]]
=== 2 Crônicas, 32
// nvi ?, NVI - Nova Versão Internacional

[[v14-32-1]]

^<<v14-32-1,1>>^ Depois de tudo o que Ezequias fez com tanta fidelidade, Senaqueribe, rei da Assíria, invadiu Judá. Ele sitiou as cidades fortificadas para conquistá-las.

[[v14-32-2]]

^<<v14-32-2,2>>^ Quando Ezequias viu que Senaqueribe pretendia guerrear contra Jerusalém,

[[v14-32-3]]

^<<v14-32-3,3>>^ consultou os seus oficiais e os comandantes do exército sobre a idéia de mandar fechar a passagem de água das fontes do lado de fora da cidade; e eles concordaram.

[[v14-32-4]]

^<<v14-32-4,4>>^ Assim, ajuntaram-se muitos homens, e fecharam todas as fontes e o riacho que atravessava a região. Eles diziam: "Por que deixar que os reis da Assíria venham e encontrem toda essa água? "

[[v14-32-5]]

^<<v14-32-5,5>>^ Depois, com grande empenho consertou todos os trechos quebrados do muro e construiu torres sobre ele. Construiu outro muro do lado de fora do primeiro e reforçou os muros de arrimo da cidade de Davi; e mandou fazer também muitas lanças e muitos escudos.

[[v14-32-6]]

^<<v14-32-6,6>>^ Nomeou sobre o povo oficiais militares e os reuniu na praça, junto à porta da cidade, animando-os com estas palavras:

[[v14-32-7]]

^<<v14-32-7,7>>^ "Sejam fortes e corajosos. Não tenham medo nem se desanimem por causa do rei da Assíria e do enorme exército que está com ele, pois conosco está um poder maior do que o que está com ele.

[[v14-32-8]]

^<<v14-32-8,8>>^ Com ele está somente o poder humano, mas conosco está o Senhor, o nosso Deus, para nos ajudar e para travar as nossas batalhas". E o povo ganhou confiança com o que disse Ezequias, rei de Judá.

[[v14-32-9]]

^<<v14-32-9,9>>^ Mais tarde, quando Senaqueribe, rei da Assíria, e todas as suas forças estavam sitiando Láquis, mandou oficiais a Jerusalém com a seguinte mensagem a Ezequias e a todo o povo de Judá que morava lá:

[[v14-32-10]]

^<<v14-32-10,10>>^ "Assim diz Senaqueribe, rei da Assíria: Em que vocês baseiam a sua confiança, para permanecerem cercados em Jerusalém?

[[v14-32-11]]

^<<v14-32-11,11>>^ Quando Ezequias diz: ‘O Senhor, o nosso Deus, nos salvará das mãos do rei da Assíria’, ele os está enganando, para deixá-los morrer de fome e de sede.

[[v14-32-12]]

^<<v14-32-12,12>>^ Mas não foi o próprio Ezequias que retirou os altares desse deus, dizendo a Judá e a Jerusalém: ‘Vocês devem adorar diante de um só altar e sobre ele queimar incenso’? "

[[v14-32-13]]

^<<v14-32-13,13>>^ "Vocês não sabem o que eu e os meus antepassados fizemos a todos os povos das outras terras? Acaso alguma vez os deuses daquelas nações conseguiram livrar das minhas mãos a terra deles?

[[v14-32-14]]

^<<v14-32-14,14>>^ De todos os deuses das nações que os meus antepassados destruíram, qual deles conseguiu salvar o seu povo de mim? Como então o deus de vocês poderá livrá-los das minhas mãos?

[[v14-32-15]]

^<<v14-32-15,15>>^ Portanto, não deixem Ezequias enganá-los ou iludi-los dessa maneira. Não acreditem nele, pois nenhum deus de qualquer nação ou reino jamais conseguiu livrar o seu povo das minhas mãos ou das mãos de meus antepassados. Muito menos o deus de vocês conseguirá livrá-los das minhas mãos! "

[[v14-32-16]]

^<<v14-32-16,16>>^ Os oficiais de Senaqueribe desafiaram ainda mais a Deus, ao Senhor, e ao seu servo Ezequias.

[[v14-32-17]]

^<<v14-32-17,17>>^ Senaqueribe também escreveu cartas insultando o Senhor, o Deus de Israel, e o desafiando: "Assim como os deuses dos povos das outras terras não livraram o povo deles das minhas mãos, também o deus de Ezequias não livrará o seu povo das minhas mãos".

[[v14-32-18]]

^<<v14-32-18,18>>^ Então os oficiais gritaram na língua dos judeus ao povo de Jerusalém que estava sobre o muro, para assustá-lo e amedrontá-lo, com o intuito de conquistarem a cidade.

[[v14-32-19]]

^<<v14-32-19,19>>^ Referiram-se ao Deus de Jerusalém como falavam dos deuses dos outros povos da terra, que não passam de obra das mãos dos homens.

[[v14-32-20]]

^<<v14-32-20,20>>^ Por tudo isso o rei Ezequias e o profeta Isaías, filho de Amoz, clamaram em oração aos céus.

[[v14-32-21]]

^<<v14-32-21,21>>^ E o Senhor enviou um anjo, que matou todos os homens de combate e todos os líderes e oficiais no acampamento do rei assírio, de forma que este se retirou envergonhado para a sua terra. E certo dia, ao adentrar o templo do seu deus, alguns dos seus filhos o mataram à espada.

[[v14-32-22]]

^<<v14-32-22,22>>^ Assim o Senhor salvou Ezequias e o povo de Jerusalém das mãos de Senaqueribe, rei da Assíria, e das mãos de todos os outros; e cuidou deles em todas as fronteiras.

[[v14-32-23]]

^<<v14-32-23,23>>^ Muitos levaram a Jerusalém ofertas para o Senhor e presentes valiosos para Ezequias, rei de Judá. Daquela ocasião em diante ele foi muito respeitado por todas as nações.

[[v14-32-24]]

^<<v14-32-24,24>>^ Naquele tempo Ezequias ficou doente, e quase morreu. Ele orou ao Senhor, que lhe respondeu dando-lhe um sinal miraculoso.

[[v14-32-25]]

^<<v14-32-25,25>>^ Mas Ezequias tornou-se orgulhoso, e não correspondeu à bondade com que foi tratado; por isso a ira do Senhor veio sobre ele, sobre Judá e sobre Jerusalém.

[[v14-32-26]]

^<<v14-32-26,26>>^ Então Ezequias humilhou-se reconhecendo o seu orgulho, como também o povo de Jerusalém; por isso a ira do Senhor não veio sobre eles durante o reinado de Ezequias.

[[v14-32-27]]

^<<v14-32-27,27>>^ Possuía Ezequias muitíssimas riquezas e glória; construiu depósitos para guardar prata, ouro, pedras preciosas, especiarias, escudos e todo tipo de objetos de valor.

[[v14-32-28]]

^<<v14-32-28,28>>^ Também construiu armazéns para estocar trigo, vinho e azeite; fez ainda estábulos para os seus diversos rebanhos e para as ovelhas.

[[v14-32-29]]

^<<v14-32-29,29>>^ Construiu cidades e adquiriu muitos rebanhos, pois Deus lhe dera muitas riquezas.

[[v14-32-30]]

^<<v14-32-30,30>>^ Foi Ezequias que bloqueou o manancial superior da fonte de Giom e, canalizou a água para a parte oeste da cidade de Davi. Ele foi bem sucedido em tudo o que se propôs a fazer.

[[v14-32-31]]

^<<v14-32-31,31>>^ Mas, quando os governantes da Babilônia enviaram uma delegação para perguntar-lhe acerca do sinal miraculoso que havia ocorrido no país, Deus o deixou, para prová-lo e para saber tudo o que havia em seu coração.

[[v14-32-32]]

^<<v14-32-32,32>>^ Os demais acontecimentos do reinado de Ezequias e os seus atos piedosos, estão escritos na visão do profeta Isaías, filho de Amoz, no livro dos reis de Judá e de Israel.

[[v14-32-33]]

^<<v14-32-33,33>>^ Ezequias descansou com os seus antepassados e foi sepultado na colina onde estão os túmulos dos descendentes de Davi. Todo o Judá e o povo de Jerusalém prestaram-lhe homenagens por ocasião da sua morte. E o seu filho Manassés foi o seu sucessor.

'''

xref:014-2-cronicas/014-2-cronicas-031.adoc#v14-31-0[&#60; Capítulo Anterior] | <<v14-32-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-033.adoc#v14-33-0[Próximo Capítulo &#62;]