include::./index.adoc[]

[[v14-16-0]]
=== 2 Crônicas, 16
// nvi ?, NVI - Nova Versão Internacional

[[v14-16-1]]

^<<v14-16-1,1>>^ No trigésimo sexto ano do reinado de Asa, Baasa, rei de Israel, invadiu Judá e fortificou Ramá, para que ninguém pudesse entrar nem sair do território de Asa, rei de Judá.

[[v14-16-2]]

^<<v14-16-2,2>>^ Então Asa ajuntou a prata e o ouro do tesouro do templo do Senhor e do seu próprio palácio e os enviou a Ben-Hadade, rei da Síria, que governava em Damasco, com uma mensagem que dizia:

[[v14-16-3]]

^<<v14-16-3,3>>^ "Façamos um tratado, como fizeram meu pai e o teu. Estou te enviando prata e ouro. Agora, rompe o tratado que tens com Baasa, rei de Israel, para que ele saia do meu país".

[[v14-16-4]]

^<<v14-16-4,4>>^ Ben-Hadade aceitou a proposta do rei Asa e ordenou aos comandantes das suas forças que atacassem as cidades de Israel. Eles conquistaram Ijom, Dã, Abel-Maim e todas as cidades-armazéns de Naftali.

[[v14-16-5]]

^<<v14-16-5,5>>^ Quando Baasa soube disso, abandonou a construção dos muros de Ramá.

[[v14-16-6]]

^<<v14-16-6,6>>^ Então o rei Asa reuniu todos os homens de Judá, e eles retiraram de Ramá as pedras e a madeira que Baasa estivera usando. Com esse material Asa fortificou Geba e Mispá.

[[v14-16-7]]

^<<v14-16-7,7>>^ Naquela época, o vidente Hanani foi dizer a Asa, rei de Judá: "Por você ter pedido ajuda ao rei da Síria e não ao Senhor, ao seu Deus, o exército do rei da Síria escapou de suas mãos.

[[v14-16-8]]

^<<v14-16-8,8>>^ Por acaso os etíopes e os líbios não eram um exército poderoso, com uma grande multidão de carros e cavalos? Contudo, quando você pediu ajuda ao Senhor, ele os entregou em suas mãos.

[[v14-16-9]]

^<<v14-16-9,9>>^ Pois os olhos do Senhor estão atentos sobre toda a terra para fortalecer aqueles que lhe dedicam totalmente o coração. Nisso você cometeu uma loucura. De agora em diante terás que enfrentar guerras".

[[v14-16-10]]

^<<v14-16-10,10>>^ Asa irritou-se contra o vidente por causa disso; ficou tão indignado que mandou prendê-lo. Nessa época Asa oprimiu brutalmente alguns do povo.

[[v14-16-11]]

^<<v14-16-11,11>>^ Os demais acontecimentos do reinado de Asa, do início ao fim, estão escritos nos registros históricos dos reis de Judá e de Israel.

[[v14-16-12]]

^<<v14-16-12,12>>^ No trigésimo nono ano de seu reinado, Asa foi atacado por uma doença nos pés. Embora a sua doença fosse grave, não buscou ajuda do Senhor, mas só dos médicos.

[[v14-16-13]]

^<<v14-16-13,13>>^ Então, no quadragésimo primeiro ano do seu reinado, Asa morreu e descansou com os seus antepassados.

[[v14-16-14]]

^<<v14-16-14,14>>^ Sepultaram-no no túmulo que ele havia mandado cavar para si na cidade de Davi. Deitaram-no num leito coberto de especiarias e de vários perfumes de fina mistura, e fizeram uma imensa fogueira em sua honra.

'''

xref:014-2-cronicas/014-2-cronicas-015.adoc#v14-15-0[&#60; Capítulo Anterior] | <<v14-16-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-017.adoc#v14-17-0[Próximo Capítulo &#62;]