include::./index.adoc[]

[[v14-10-0]]
=== 2 Crônicas, 10
// nvi ?, NVI - Nova Versão Internacional

[[v14-10-1]]

^<<v14-10-1,1>>^ Roboão foi a Siquém, onde todos os israelitas tinham se reunido para proclamá-lo rei.

[[v14-10-2]]

^<<v14-10-2,2>>^ Assim que Jeroboão, filho de Nebate, que estava no Egito fugindo do rei Salomão, soube disso, voltou de lá.

[[v14-10-3]]

^<<v14-10-3,3>>^ E mandaram chamá-lo. Então ele e todo o Israel foram ao encontro de Roboão e disseram:

[[v14-10-4]]

^<<v14-10-4,4>>^ "Teu pai colocou sobre nós um jugo pesado, mas agora diminui o trabalho árduo e este jugo pesado, e nós te serviremos".

[[v14-10-5]]

^<<v14-10-5,5>>^ Roboão respondeu: "Voltem a mim daqui a três dias". Então o povo foi embora.

[[v14-10-6]]

^<<v14-10-6,6>>^ O rei Roboão perguntou às autoridades que haviam servido ao seu pai Salomão durante a vida dele: "Como vocês me aconselham a responder a este povo? "

[[v14-10-7]]

^<<v14-10-7,7>>^ Eles responderam: "Se hoje fores bom para esse povo, se o agradares e lhe deres resposta favorável, eles sempre serão teus servos".

[[v14-10-8]]

^<<v14-10-8,8>>^ Roboão, contudo, rejeitou o conselho que as autoridades de Israel lhe tinham dado e consultou os jovens que haviam crescido com ele e o estavam servindo.

[[v14-10-9]]

^<<v14-10-9,9>>^ Perguntou-lhes: "Qual é o conselho de vocês? Como devemos responder a este povo que me diz: ‘Diminui o jugo que teu pai colocou sobre nós’? "

[[v14-10-10]]

^<<v14-10-10,10>>^ Os jovens que haviam crescido com ele responderam: "A este povo que te disse: ‘Teu pai colocou sobre nós um jugo pesado; torna-o mais leve’ — dize: ‘Meu dedo mínimo é mais grosso do que a cintura do meu pai.

[[v14-10-11]]

^<<v14-10-11,11>>^ Pois bem, meu pai lhes impôs um jugo pesado; eu o tornarei ainda mais pesado. Meu pai os castigou com simples chicotes; eu os castigarei com chicotes pontiagudos’ ".

[[v14-10-12]]

^<<v14-10-12,12>>^ Três dias depois, Jeroboão e todo o povo voltaram a Roboão, segundo a orientação dada pelo rei: "Voltem a mim daqui a três dias".

[[v14-10-13]]

^<<v14-10-13,13>>^ Mas o rei lhes respondeu asperamente. Rejeitando o conselho das autoridades de Israel,

[[v14-10-14]]

^<<v14-10-14,14>>^ seguiu o conselho dos jovens e disse: "Meu pai lhes tornou pesado o jugo; eu o tornarei ainda mais pesado. Meu pai os castigou com simples chicotes; eu os castigarei com chicotes pontiagudos".

[[v14-10-15]]

^<<v14-10-15,15>>^ E o rei não ouviu o povo, pois esta mudança nos acontecimentos vinha da parte de Deus, para que se cumprisse a palavra que o Senhor havia falado a Jeroboão, filho de Nebate, por meio do silonita Aías.

[[v14-10-16]]

^<<v14-10-16,16>>^ Quando todo o Israel viu que o rei se recusava a ouvi-los, responderam ao rei: "Que temos em comum com Davi? Que temos em comum com o filho de Jessé? Para as suas tendas, ó Israel! Cuide da sua própria casa, ó Davi! " E assim os israelitas foram para as suas casas.

[[v14-10-17]]

^<<v14-10-17,17>>^ Quanto, porém, aos israelitas que moravam nas cidades de Judá, Roboão continuou como rei deles.

[[v14-10-18]]

^<<v14-10-18,18>>^ O rei Roboão enviou Adonirão, chefe de trabalhos forçados, mas todo o Israel o apedrejou até à morte. O rei, contudo, conseguiu subir em sua carruagem e fugir para Jerusalém.

[[v14-10-19]]

^<<v14-10-19,19>>^ Desta forma Israel se rebelou contra a dinastia de Davi, e assim permanece até hoje.

'''

xref:014-2-cronicas/014-2-cronicas-009.adoc#v14-9-0[&#60; Capítulo Anterior] | <<v14-10-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-011.adoc#v14-11-0[Próximo Capítulo &#62;]