include::./index.adoc[]

[[v14-13-0]]
=== 2 Crônicas, 13
// nvi ?, NVI - Nova Versão Internacional

[[v14-13-1]]

^<<v14-13-1,1>>^ No décimo oitavo ano do reinado de Jeroboão, Abias tornou-se rei de Judá,

[[v14-13-2]]

^<<v14-13-2,2>>^ e reinou três anos em Jerusalém. O nome de sua mãe era Maaca, filha de Uriel, de Gibeá. E houve guerra entre Abias e Jeroboão.

[[v14-13-3]]

^<<v14-13-3,3>>^ Abias entrou em combate levando uma força de quatrocentos mil excelentes guerreiros, e Jeroboão foi enfrentá-lo com oitocentos mil excelentes guerreiros.

[[v14-13-4]]

^<<v14-13-4,4>>^ Abias subiu o monte Zemaraim, nos montes de Efraim, e gritou: "Jeroboão e todo o Israel, ouçam-me!

[[v14-13-5]]

^<<v14-13-5,5>>^ Vocês não sabem que o Senhor, o Deus de Israel, deu para sempre o reino de Israel a Davi e a seus descendentes mediante uma aliança irrevogável?

[[v14-13-6]]

^<<v14-13-6,6>>^ Mesmo assim, Jeroboão, filho de Nebate, servo de Salomão, filho de Davi, rebelou-se contra o seu senhor.

[[v14-13-7]]

^<<v14-13-7,7>>^ Alguns homens vadios e imprestáveis juntaram-se a ele e se opuseram a Roboão, filho de Salomão, quando ainda era jovem, indeciso e incapaz de oferecer-lhes resistência.

[[v14-13-8]]

^<<v14-13-8,8>>^ "E agora vocês pretendem resistir ao reino do Senhor, que está nas mãos dos descendentes de Davi. Vocês são de fato uma multidão imensa e têm os bezerros de ouro que Jeroboão fez para serem os seus deuses.

[[v14-13-9]]

^<<v14-13-9,9>>^ Mas, não foram vocês que expulsaram os sacerdotes do Senhor, os descendentes de Arão, e os levitas, e escolheram os seus próprios sacerdotes, como fazem os outros povos? Quem quer que se consagre com um novilho e sete carneiros pode tornar-se sacerdote daqueles que não são deuses.

[[v14-13-10]]

^<<v14-13-10,10>>^ "Quanto a nós, o Senhor é o nosso Deus, e não o abandonamos. Os nossos sacerdotes, que servem ao Senhor auxiliados pelos levitas, são descendentes de Arão.

[[v14-13-11]]

^<<v14-13-11,11>>^ Todas as manhãs e todas as tardes eles apresentam holocaustos e incenso aromático ao Senhor, arrumam os pães sobre a mesa cerimonialmente pura e todas as tardes acendem as lâmpadas do candelabro de ouro. Pois nós observamos as exigências do Senhor, o nosso Deus, enquanto que vocês o abandonaram.

[[v14-13-12]]

^<<v14-13-12,12>>^ E vejam bem! Deus está conosco; ele é o nosso chefe. Os sacerdotes dele, com suas cornetas, farão soar o grito de guerra contra vocês. Israelitas, não lutem contra o Senhor, o Deus dos seus antepassados, pois vocês não terão êxito! "

[[v14-13-13]]

^<<v14-13-13,13>>^ Enquanto isso, Jeroboão tinha mandado tropas para a retaguarda do exército de Judá, de forma que ele estava em frente de Judá e a emboscada estava atrás.

[[v14-13-14]]

^<<v14-13-14,14>>^ Quando o exército de Judá virou-se e viu que estava sendo atacado pela frente e pela retaguarda, clamou ao Senhor. Os sacerdotes tocaram suas cornetas,

[[v14-13-15]]

^<<v14-13-15,15>>^ e os homens de Judá deram o grito de guerra. Ao som do grito de guerra, Deus derrotou Jeroboão e todo o Israel diante de Abias e de Judá.

[[v14-13-16]]

^<<v14-13-16,16>>^ Os israelitas fugiram dos soldados de Judá, e Deus os entregou nas mãos deles.

[[v14-13-17]]

^<<v14-13-17,17>>^ Abias e os seus soldados lhes infligiram grande derrota; quinhentos mil excelentes guerreiros de Israel foram mortos.

[[v14-13-18]]

^<<v14-13-18,18>>^ Os israelitas foram subjugados naquela ocasião, e os homens de Judá tiveram força para vencer, pois confiaram no Senhor, o Deus dos seus antepassados.

[[v14-13-19]]

^<<v14-13-19,19>>^ Abias perseguiu Jeroboão e tomou-lhe as cidades de Betel, Jesana e Efrom, com os seus povoados ao redor.

[[v14-13-20]]

^<<v14-13-20,20>>^ Durante o reinado de Abias, Jeroboão não recuperou o seu poder; até que o Senhor o feriu, e ele morreu.

[[v14-13-21]]

^<<v14-13-21,21>>^ Abias, ao contrário, fortaleceu-se. Ele se casou com catorze mulheres e teve vinte e dois filhos e dezesseis filhas.

[[v14-13-22]]

^<<v14-13-22,22>>^ Os demais acontecimentos do reinado de Abias, o que ele fez e o que disse, estão escritos nos relatos do profeta Ido.

'''

xref:014-2-cronicas/014-2-cronicas-012.adoc#v14-12-0[&#60; Capítulo Anterior] | <<v14-13-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-014.adoc#v14-14-0[Próximo Capítulo &#62;]