include::./index.adoc[]

[[v14-18-0]]
=== 2 Crônicas, 18
// nvi ?, NVI - Nova Versão Internacional

[[v14-18-1]]

^<<v14-18-1,1>>^ Josafá tinha grande riqueza e honra, e aliou-se a Acabe mediante casamento.

[[v14-18-2]]

^<<v14-18-2,2>>^ Alguns anos depois, ele foi visitar Acabe em Samaria. Acabe abateu muitas ovelhas e bois para receber a ele e à sua comitiva, e insistiu que atacasse Ramote-Gileade.

[[v14-18-3]]

^<<v14-18-3,3>>^ Acabe, rei de Israel, perguntou a Josafá, rei de Judá: "Irás comigo lutar contra Ramote-Gileade? " Josafá respondeu: "Sou como tu, e meu povo é como o teu povo; estaremos contigo na guerra".

[[v14-18-4]]

^<<v14-18-4,4>>^ Mas acrescentou: "Peço-te que busques primeiro o conselho do Senhor".

[[v14-18-5]]

^<<v14-18-5,5>>^ Então o rei de Israel reuniu quatrocentos profetas, e lhes perguntou: "Devemos ir à guerra contra Ramote-Gileade, ou não? " Eles responderam: "Sim, pois Deus a entregará nas mãos do rei".

[[v14-18-6]]

^<<v14-18-6,6>>^ Josafá, porém, perguntou: "Não existe aqui mais nenhum profeta do Senhor, a quem possamos consultar? "

[[v14-18-7]]

^<<v14-18-7,7>>^ O rei de Israel respondeu a Josafá: "Ainda há um homem por meio de quem podemos consultar o Senhor, mas eu o odeio, porque nunca profetiza coisas boas a meu respeito, mas sempre coisas ruins. É Micaías, filho de Inlá". "O rei não deveria dizer isso", Josafá respondeu.

[[v14-18-8]]

^<<v14-18-8,8>>^ Então o rei de Israel chamou um dos seus oficiais e disse: "Traga Micaías, filho de Inlá, imediatamente".

[[v14-18-9]]

^<<v14-18-9,9>>^ Usando vestes reais, o rei de Israel e Josafá, rei de Judá, estavam sentados em seus tronos, na eira, junto à porta de Samaria, e todos os profetas estavam profetizando em transe diante deles.

[[v14-18-10]]

^<<v14-18-10,10>>^ E Zedequias, filho de Quenaaná, tinha feito chifres de ferro, e declarou: "Assim diz o Senhor: ‘Com estes chifres tu ferirás os arameus até que sejam destruídos’ ".

[[v14-18-11]]

^<<v14-18-11,11>>^ Todos os outros profetas estavam profetizando a mesma coisa, dizendo: "Ataca Ramote-Gileade, e serás vitorioso, pois o Senhor a entregará nas mãos do rei".

[[v14-18-12]]

^<<v14-18-12,12>>^ O mensageiro que tinha ido chamar Micaías lhe disse: "Veja, todos os outros profetas estão predizendo que o rei terá sucesso. Sua palavra também deve ser favorável".

[[v14-18-13]]

^<<v14-18-13,13>>^ Micaías, porém, disse: "Juro pelo nome do Senhor, que direi o que o meu Deus mandar".

[[v14-18-14]]

^<<v14-18-14,14>>^ Quando ele chegou, o rei lhe perguntou: "Micaías, devemos ir à guerra contra Ramote-Gileade, ou não? " Ele respondeu: "Atacai, e sereis vitoriosos, pois eles serão entregues em vossas mãos".

[[v14-18-15]]

^<<v14-18-15,15>>^ O rei lhe disse: "Quantas vezes devo fazer você jurar que me irá dizer somente a verdade em nome do Senhor? "

[[v14-18-16]]

^<<v14-18-16,16>>^ Então Micaías respondeu: "Vi todo o Israel espalhado pelas colinas, como ovelhas sem pastor, e o Senhor dizer: ‘Estes não têm dono. Cada um volte para casa em paz’ ".

[[v14-18-17]]

^<<v14-18-17,17>>^ O rei de Israel disse a Josafá: "Não lhe disse que ele nunca profetiza nada de bom a meu respeito, mas apenas coisas ruins? "

[[v14-18-18]]

^<<v14-18-18,18>>^ Micaías prosseguiu: "Ouçam a palavra do Senhor: Vi o Senhor assentado em seu trono, com todo o exército dos céus à sua direita e à sua esquerda.

[[v14-18-19]]

^<<v14-18-19,19>>^ E o Senhor disse: ‘Quem enganará Acabe, rei de Israel, para que ataque Ramote-Gileade e morra lá? ’ "E um sugeria uma coisa, outro sugeria outra, até que,

[[v14-18-20]]

^<<v14-18-20,20>>^ finalmente, um espírito colocou-se diante do Senhor e disse: ‘Eu o enganarei’. " ‘De que maneira? ’, perguntou o Senhor.

[[v14-18-21]]

^<<v14-18-21,21>>^ "Ele respondeu: ‘Irei e serei um espírito mentiroso na boca de todos os profetas do rei’. "Disse o Senhor: ‘Você conseguirá enganá-lo; vá e engane-o’.

[[v14-18-22]]

^<<v14-18-22,22>>^ "E o Senhor pôs um espírito mentiroso na boca destes seus profetas. O Senhor decretou a sua desgraça".

[[v14-18-23]]

^<<v14-18-23,23>>^ Então Zedequias, filho de Quenaaná, aproximou-se, deu um tapa no rosto de Micaías e perguntou: "Por qual caminho foi o espírito da parte do Senhor, quando saiu de mim para falar a você? "

[[v14-18-24]]

^<<v14-18-24,24>>^ Micaías respondeu: "Você descobrirá no dia em que estiver se escondendo de quarto em quarto".

[[v14-18-25]]

^<<v14-18-25,25>>^ O rei de Israel então ordenou: "Enviem Micaías de volta a Amom, o governador da cidade, e a Joás, filho do rei,

[[v14-18-26]]

^<<v14-18-26,26>>^ e digam: Assim diz o rei: Ponham este homem na prisão a pão e água, até que eu volte em segurança".

[[v14-18-27]]

^<<v14-18-27,27>>^ Micaías declarou: "Se você de fato voltar em segurança, o Senhor não falou por meu intermédio". E acrescentou: "Ouçam o que estou dizendo, todos vocês! "

[[v14-18-28]]

^<<v14-18-28,28>>^ Então o rei de Israel e Josafá, rei de Judá, foram atacar Ramote-Gileade.

[[v14-18-29]]

^<<v14-18-29,29>>^ E o rei de Israel disse a Josafá: "Entrarei disfarçado em combate, mas tu, usa as tuas vestes reais". O rei de Israel disfarçou-se, e ambos foram para o combate.

[[v14-18-30]]

^<<v14-18-30,30>>^ O rei da Síria havia ordenado a seus chefes dos carros de guerra: "Não lutem contra ninguém, seja soldado seja oficial, senão contra o rei de Israel".

[[v14-18-31]]

^<<v14-18-31,31>>^ Quando os chefes dos carros viram Josafá, pensaram: "É o rei de Israel", e o cercaram para atacá-lo, mas Josafá clamou, e o Senhor o ajudou. Deus os afastou dele,

[[v14-18-32]]

^<<v14-18-32,32>>^ pois, quando os comandantes dos carros viram que não era o rei de Israel, deixaram de persegui-lo.

[[v14-18-33]]

^<<v14-18-33,33>>^ De repente, um soldado disparou seu arco ao acaso, e atingiu o rei de Israel entre os encaixes da sua armadura. Então o rei disse ao condutor do seu carro: "Tire-me do combate. Fui ferido! "

[[v14-18-34]]

^<<v14-18-34,34>>^ A batalha foi violenta durante todo o dia, e assim, o rei de Israel teve que enfrentar os arameus em pé no seu carro, até à tarde. E, ao pôr-do-sol, ele morreu.

'''

xref:014-2-cronicas/014-2-cronicas-017.adoc#v14-17-0[&#60; Capítulo Anterior] | <<v14-18-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-019.adoc#v14-19-0[Próximo Capítulo &#62;]