include::./index.adoc[]

[[v14-6-0]]
=== 2 Crônicas, 6
// nvi ?, NVI - Nova Versão Internacional

[[v14-6-1]]

^<<v14-6-1,1>>^ E Salomão exclamou: "O Senhor disse que habitaria numa nuvem escura!

[[v14-6-2]]

^<<v14-6-2,2>>^ Na realidade construí para ti um templo magnífico, um lugar para nele habitares para sempre! "

[[v14-6-3]]

^<<v14-6-3,3>>^ Depois o rei virou-se e abençoou toda a assembléia de Israel, que estava ali de pé.

[[v14-6-4]]

^<<v14-6-4,4>>^ E disse: "Bendito seja o Senhor, o Deus de Israel, que por suas mãos cumpriu o que prometeu com sua própria boca a meu pai Davi, quando lhe disse:

[[v14-6-5]]

^<<v14-6-5,5>>^ ‘Desde o dia em que tirei meu povo do Egito, não escolhi nenhuma cidade das tribos de Israel para nela construir um templo em honra do meu nome, nem escolhi ninguém para ser o líder do meu povo Israel.

[[v14-6-6]]

^<<v14-6-6,6>>^ Mas, agora, escolhi Jerusalém para o meu nome ali estar e escolhi Davi para governar Israel, o meu povo’.

[[v14-6-7]]

^<<v14-6-7,7>>^ "Meu pai Davi tinha no coração o propósito de construir um templo em honra do nome do Senhor, o Deus de Israel.

[[v14-6-8]]

^<<v14-6-8,8>>^ Mas o Senhor lhe disse: ‘Você fez bem em ter no coração o plano de construir um templo em honra do meu nome;

[[v14-6-9]]

^<<v14-6-9,9>>^ no entanto, não será você que o construirá, mas o seu filho, que procederá de você; ele construirá o templo em honra do meu nome’.

[[v14-6-10]]

^<<v14-6-10,10>>^ "E o Senhor cumpriu a sua promessa. Sou o sucessor de meu pai Davi, e agora ocupo o trono de Israel, como o Senhor tinha prometido, e construí o templo em honra do nome do Senhor, o Deus de Israel.

[[v14-6-11]]

^<<v14-6-11,11>>^ Coloquei nele a arca, na qual estão as tábuas da aliança do Senhor, aliança que ele fez com os israelitas".

[[v14-6-12]]

^<<v14-6-12,12>>^ Depois Salomão colocou-se diante do altar do Senhor, diante de toda a assembléia de Israel, e levantou as mãos para orar.

[[v14-6-13]]

^<<v14-6-13,13>>^ Ele havia mandado fazer uma plataforma de bronze com dois metros e vinte e cinco centímetros de comprimento e de largura, e um metro e trinta e cinco centímetros de altura, no centro do pátio externo. Ele ficou de pé na plataforma, depois ajoelhou-se diante de toda a assembléia de Israel, levantou as mãos para o céu,

[[v14-6-14]]

^<<v14-6-14,14>>^ e orou: "Senhor, Deus de Israel, não há Deus como tu nos céus e na terra! Tu que guardas a tua aliança de amor com os teus servos que, de todo o coração, andam segundo a tua vontade.

[[v14-6-15]]

^<<v14-6-15,15>>^ Cumpriste a tua promessa a teu servo Davi, meu pai; com tua boca prometeste e com tua mão a cumpriste, conforme hoje se vê.

[[v14-6-16]]

^<<v14-6-16,16>>^ "Agora, Senhor, Deus de Israel, cumpre a outra promessa que fizeste a teu servo Davi, meu pai, quando disseste: ‘Você nunca deixará de ter, diante de mim, um descendente que se assente no trono de Israel, se tão-somente os seus descendentes tiverem o cuidado de, em tudo, andarem segundo a minha lei, como você tem feito’.

[[v14-6-17]]

^<<v14-6-17,17>>^ Agora, ó Senhor, Deus de Israel, que se confirme a palavra que falaste a teu servo Davi.

[[v14-6-18]]

^<<v14-6-18,18>>^ "Mas será possível que Deus habite na terra com os homens? Os céus, mesmo os mais altos céus, não podem conter-te. Muito menos este templo que construí!

[[v14-6-19]]

^<<v14-6-19,19>>^ Ainda assim, atende à oração do teu servo e ao seu pedido de misericórdia, ó Senhor, meu Deus. Ouve o clamor e a oração que teu servo faz hoje na tua presença.

[[v14-6-20]]

^<<v14-6-20,20>>^ Estejam os teus olhos voltados dia e noite para este templo, lugar do qual disseste que nele porias o teu nome, para que ouças a oração que o teu servo fizer voltado para este lugar.

[[v14-6-21]]

^<<v14-6-21,21>>^ Ouve as súplicas do teu servo e de Israel, teu povo, quando orarem voltados para este lugar. Ouve desde os céus, lugar da tua habitação, e quando ouvires, dá-lhes o teu perdão.

[[v14-6-22]]

^<<v14-6-22,22>>^ "Quando um homem pecar contra seu próximo e tiver que fazer um juramento, e vier jurar diante do teu altar neste templo,

[[v14-6-23]]

^<<v14-6-23,23>>^ ouve dos céus e age. Julga os teus servos; retribui ao culpado, fazendo recair sobre a sua própria cabeça o resultado da sua conduta, e declara sem culpa o inocente, dando-lhe o que a sua inocência merece.

[[v14-6-24]]

^<<v14-6-24,24>>^ "Quando Israel, o teu povo, for derrotado por um inimigo por ter pecado contra ti, e voltar-se para ti e invocar o teu nome, orando e suplicando a ti neste templo,

[[v14-6-25]]

^<<v14-6-25,25>>^ ouve dos céus e perdoa o pecado de Israel, teu povo, e traze-o de volta à terra que deste a ele e aos seus antepassados.

[[v14-6-26]]

^<<v14-6-26,26>>^ "Quando fechar-se o céu, e não houver chuva por haver o teu povo pecado contra ti, e, se o teu povo, voltado para este lugar, invocar o teu nome e afastar-se do seu pecado por o haveres castigado,

[[v14-6-27]]

^<<v14-6-27,27>>^ ouve dos céus e perdoa o pecado dos teus servos, do teu povo Israel. Ensina-lhes o caminho certo e envia chuva sobre a tua terra, que deste por herança ao teu povo.

[[v14-6-28]]

^<<v14-6-28,28>>^ "Quando houver fome ou praga no país, ferrugem e mofo, gafanhotos peregrinos e gafanhotos devastadores, ou quando inimigos sitiarem suas cidades, quando, em meio a qualquer praga ou epidemia,

[[v14-6-29]]

^<<v14-6-29,29>>^ uma oração ou uma súplica por misericórdia for feita por um israelita ou por todo o teu povo Israel, cada um sentindo as suas próprias aflições e dores, estendendo as mãos na direção deste templo,

[[v14-6-30]]

^<<v14-6-30,30>>^ ouve dos céus, o lugar da tua habitação. Perdoa e trata cada um de acordo com o que merece, visto que conheces o seu coração. Sim, só tu conheces o coração do homem.

[[v14-6-31]]

^<<v14-6-31,31>>^ Assim eles te temerão, e andarão segundo a tua vontade durante todo o tempo em que viverem na terra que deste aos nossos antepassados.

[[v14-6-32]]

^<<v14-6-32,32>>^ "Quanto ao estrangeiro, que não pertence a teu povo Israel, e que veio de uma terra distante por causa do teu grande nome, da tua mão poderosa e do teu braço forte; quando ele vier e orar voltado para este templo,

[[v14-6-33]]

^<<v14-6-33,33>>^ ouve dos céus, lugar da tua habitação, e atende o pedido do estrangeiro, a fim de que todos os povos da terra conheçam o teu nome e te temam, como faz Israel, teu povo, e saibam que este templo que construí traz o teu nome.

[[v14-6-34]]

^<<v14-6-34,34>>^ "Quando o teu povo for à guerra contra os seus inimigos, por onde quer que tu o enviares, e orar a ti, voltado para a cidade que escolheste e para o templo que construí em honra do teu nome,

[[v14-6-35]]

^<<v14-6-35,35>>^ então ouve dos céus a sua oração e a sua súplica, e defende a sua causa.

[[v14-6-36]]

^<<v14-6-36,36>>^ "Quando pecarem contra ti, pois não há ninguém que não peque, e ficares irado com eles e os entregares ao inimigo, que os leve prisioneiros para uma terra distante ou próxima;

[[v14-6-37]]

^<<v14-6-37,37>>^ se eles caírem em si, na terra para a qual foram deportados, e se arrependerem e lá orarem: ‘Pecamos, praticamos o mal e fomos rebeldes’;

[[v14-6-38]]

^<<v14-6-38,38>>^ e se lá eles se voltarem para ti de todo o coração e de toda a sua alma, na terra de seu cativeiro para onde foram levados, e orarem voltados para a terra que deste aos seus antepassados, para a cidade que escolheste e para o templo que construí em honra do teu nome,

[[v14-6-39]]

^<<v14-6-39,39>>^ então, dos céus, lugar da tua habitação, ouve a sua oração e a sua súplica, e defende a sua causa. Perdoa o teu povo, que pecou contra ti.

[[v14-6-40]]

^<<v14-6-40,40>>^ "Assim, meu Deus, que os teus olhos estejam abertos e teus ouvidos atentos às orações feitas neste lugar.

[[v14-6-41]]

^<<v14-6-41,41>>^ "Agora, levanta-te, ó Senhor, ó Deus, e vem para o teu lugar de descanso, tu e a arca do teu poder. Estejam os teus sacerdotes vestidos de salvação, ó Senhor, ó Deus; que os teus santos se regozijem em tua bondade.

[[v14-6-42]]

^<<v14-6-42,42>>^ Ó Senhor, ó Deus, não rejeites o teu ungido. Lembra-te da fidelidade prometida a teu servo Davi".

'''

xref:014-2-cronicas/014-2-cronicas-005.adoc#v14-5-0[&#60; Capítulo Anterior] | <<v14-6-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-007.adoc#v14-7-0[Próximo Capítulo &#62;]