include::./index.adoc[]

[[v14-8-0]]
=== 2 Crônicas, 8
// nvi ?, NVI - Nova Versão Internacional

[[v14-8-1]]

^<<v14-8-1,1>>^ Depois de vinte anos, durante os quais Salomão construiu o templo do Senhor e o seu próprio palácio,

[[v14-8-2]]

^<<v14-8-2,2>>^ ele reconstruiu as cidades que Hirão lhe tinha dado, e nelas estabeleceu israelitas.

[[v14-8-3]]

^<<v14-8-3,3>>^ Depois atacou Hamate-Zobá e a conquistou.

[[v14-8-4]]

^<<v14-8-4,4>>^ Também reconstruiu Tadmor, no deserto, e todas as cidades-armazéns que havia construído em Hamate.

[[v14-8-5]]

^<<v14-8-5,5>>^ Reconstruiu Bete-Horom Alta e Bete-Horom Baixa, cidades fortificadas com muros, portas e trancas,

[[v14-8-6]]

^<<v14-8-6,6>>^ e também Baalate e todas as cidades-armazéns que possuía, e todas as cidades onde ficavam os seus carros e os seus cavalos. Construiu tudo o que desejou em Jerusalém, no Líbano e em todo o território que governou.

[[v14-8-7]]

^<<v14-8-7,7>>^ Todos os não israelitas, descendentes dos hititas, dos amorreus, dos ferezeus, dos heveus e dos jebuseus,

[[v14-8-8]]

^<<v14-8-8,8>>^ que não tinham sido mortos pelos israelitas, Salomão recrutou para o trabalho forçado, como continuam até hoje.

[[v14-8-9]]

^<<v14-8-9,9>>^ Mas Salomão não obrigou nenhum israelita a trabalhos forçados; eles eram seus homens de guerra, chefes de seus capitães, comandantes dos seus carros e condutores de carros.

[[v14-8-10]]

^<<v14-8-10,10>>^ Também eram israelitas os principais funcionários do rei Salomão, duzentos e cinqüenta funcionários que supervisionavam os trabalhadores.

[[v14-8-11]]

^<<v14-8-11,11>>^ Salomão levou a filha do faraó da cidade de Davi para o palácio que ele havia construído para ela, pois dissera: "Minha mulher não deve morar no palácio de Davi, rei de Israel, pois os lugares onde entrou a arca do Senhor são sagrados".

[[v14-8-12]]

^<<v14-8-12,12>>^ Sobre o altar do Senhor, que havia construído diante do pórtico, Salomão passou a sacrificar holocaustos ao Senhor,

[[v14-8-13]]

^<<v14-8-13,13>>^ conforme as determinações de Moisés acerca das ofertas diárias e dos sábados, das luas novas e das três festas anuais: a festa dos pães sem fermento, a festa das semanas e a festa das cabanas.

[[v14-8-14]]

^<<v14-8-14,14>>^ De acordo com a ordem de seu pai Davi, designou os grupos dos sacerdotes para as suas tarefas, e os levitas para conduzirem o louvor e ajudarem os sacerdotes, conforme as determinações diárias. Também designou, por divisões, os porteiros das várias portas, conforme o que Davi, homem de Deus, tinha ordenado.

[[v14-8-15]]

^<<v14-8-15,15>>^ Todas as ordens dadas pelo rei aos sacerdotes e aos levitas, inclusive as ordens relativas aos tesouros, foram seguidas à risca.

[[v14-8-16]]

^<<v14-8-16,16>>^ Todo o trabalho de Salomão foi executado, desde o dia em que foram lançados os alicerces do templo do Senhor até seu término. Assim foi concluído o templo do Senhor.

[[v14-8-17]]

^<<v14-8-17,17>>^ Depois Salomão foi a Eziom-Geber e a Elate, no litoral de Edom.

[[v14-8-18]]

^<<v14-8-18,18>>^ E Hirão enviou-lhe navios comandados por seus próprios marinheiros, homens que conheciam o mar. Eles navegavam com os marinheiros de Salomão até Ofir, e de lá trouxeram quinze toneladas e setecentos e cinqüenta quilos de ouro para o rei Salomão.

'''

xref:014-2-cronicas/014-2-cronicas-007.adoc#v14-7-0[&#60; Capítulo Anterior] | <<v14-8-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-009.adoc#v14-9-0[Próximo Capítulo &#62;]