include::./index.adoc[]

[[v14-1-0]]
=== 2 Crônicas, 1
// nvi ?, NVI - Nova Versão Internacional

[[v14-1-1]]

^<<v14-1-1,1>>^ Salomão, filho de Davi, estabeleceu-se com firmeza sobre o seu reino, pois o Senhor, o seu Deus, estava com ele e tornou-o muito poderoso.

[[v14-1-2]]

^<<v14-1-2,2>>^ Salomão reuniu todo o Israel: os líderes de mil e de cem, os juízes, todos os líderes de Israel e os chefes de famílias.

[[v14-1-3]]

^<<v14-1-3,3>>^ E foi com toda a assembléia ao lugar sagrado, no alto de Gibeom, pois ali estava a Tenda do Encontro que Moisés, servo do Senhor, havia feito no deserto.

[[v14-1-4]]

^<<v14-1-4,4>>^ Davi tinha transportado a arca de Deus de Quiriate-Jearim para a tenda que ele tinha armado para ela em Jerusalém.

[[v14-1-5]]

^<<v14-1-5,5>>^ O altar de bronze que Bezalel, filho de Uri e neto de Hur, fizera, estava em Gibeom, em frente do tabernáculo do Senhor; ali Salomão e a assembléia consultaram o Senhor.

[[v14-1-6]]

^<<v14-1-6,6>>^ Salomão ofereceu ao Senhor mil holocaustos sobre o altar de bronze, na Tenda do Encontro.

[[v14-1-7]]

^<<v14-1-7,7>>^ Naquela noite Deus apareceu a Salomão e lhe disse: "Peça-me o que quiser, e eu lhe darei".

[[v14-1-8]]

^<<v14-1-8,8>>^ Salomão respondeu: "Tu foste muito bondoso para com meu pai Davi e me fizeste rei em seu lugar.

[[v14-1-9]]

^<<v14-1-9,9>>^ Agora, Senhor Deus, que se confirme a tua promessa a meu pai Davi, pois me fizeste rei sobre um povo tão numeroso quanto o pó da terra.

[[v14-1-10]]

^<<v14-1-10,10>>^ Dá-me sabedoria e conhecimento, para que eu possa liderar esta nação, pois, quem pode governar este teu grande povo? "

[[v14-1-11]]

^<<v14-1-11,11>>^ Deus disse a Salomão: "Já que este é o desejo de seu coração e você não pediu riquezas, nem bens, nem honra, nem a morte dos seus inimigos, nem vida longa, mas sabedoria e conhecimento para governar o meu povo, sobre o qual o fiz rei,

[[v14-1-12]]

^<<v14-1-12,12>>^ você receberá o que pediu, mas também lhe darei riquezas, bens e honra, como nenhum rei antes de você teve e nenhum depois de você terá".

[[v14-1-13]]

^<<v14-1-13,13>>^ Então Salomão voltou de Gibeom, de diante da Tenda do Encontro, para Jerusalém. E reinou sobre Israel.

[[v14-1-14]]

^<<v14-1-14,14>>^ Salomão juntou carros e cavalos; possuía mil e quatrocentos carros e doze mil cavalos, dos quais mantinha uma parte nas guarnições de algumas cidades e a outra perto dele, em Jerusalém.

[[v14-1-15]]

^<<v14-1-15,15>>^ O rei tornou tão comuns a prata e o ouro em Jerusalém quanto as pedras, e o cedro tão numeroso quanto as figueiras bravas da Sefelá.

[[v14-1-16]]

^<<v14-1-16,16>>^ Os cavalos de Salomão eram importados do Egito e da Cilícia, onde os fornecedores do rei os compravam.

[[v14-1-17]]

^<<v14-1-17,17>>^ Importavam do Egito um carro por sete quilos e duzentos gramas de prata, e um cavalo por um quilo e oitocentos gramas, e os exportavam para todos os reis dos hititas e dos arameus.

'''

xref:013-1-cronicas/013-1-cronicas-029.adoc#v13-29-0[&#60; Capítulo Anterior] | <<v14-1-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-002.adoc#v14-2-0[Próximo Capítulo &#62;]