include::./index.adoc[]

[[v14-24-0]]
=== 2 Crônicas, 24
// nvi ?, NVI - Nova Versão Internacional

[[v14-24-1]]

^<<v14-24-1,1>>^ Joás tinha sete anos de idade quando se tornou rei, e reinou quarenta anos em Jerusalém. O nome de sua mãe era Zíbia; ela era de Berseba.

[[v14-24-2]]

^<<v14-24-2,2>>^ Joás fez o que o Senhor aprova enquanto viveu o sacerdote Joiada.

[[v14-24-3]]

^<<v14-24-3,3>>^ Joiada escolheu para ele duas mulheres, e ele teve filhos e filhas.

[[v14-24-4]]

^<<v14-24-4,4>>^ Algum tempo depois Joás decidiu fazer reparos no templo do Senhor.

[[v14-24-5]]

^<<v14-24-5,5>>^ Ele reuniu os sacerdotes e os levitas e lhes disse: "Vão às cidades de Judá e recolham o imposto devido anualmente por todo o Israel, para fazer reparos no templo de seu Deus. Vão agora mesmo! " Os levitas, porém, não agiram imediatamente.

[[v14-24-6]]

^<<v14-24-6,6>>^ Por isso, o rei convocou Joiada, o sumo sacerdote, e lhe perguntou: "Por que você não exigiu que os levitas trouxessem de Judá e de Jerusalém o imposto determinado por Moisés, servo do Senhor, e pela assembléia de Israel para a tenda da arca da aliança? "

[[v14-24-7]]

^<<v14-24-7,7>>^ De fato, Atalia, aquela mulher ímpia, e os seus filhos tinham arrombado o templo de Deus e tinham até usado os seus objetos sagrados para cultuar os baalins.

[[v14-24-8]]

^<<v14-24-8,8>>^ Então, por ordem do rei, fizeram uma caixa e a colocaram do lado de fora, à entrada do templo do Senhor.

[[v14-24-9]]

^<<v14-24-9,9>>^ Fez-se então uma proclamação em Judá e em Jerusalém para que trouxessem ao Senhor o imposto que Moisés, servo do Senhor, havia exigido de Israel no deserto.

[[v14-24-10]]

^<<v14-24-10,10>>^ Todos os líderes e todo o povo trouxeram com alegria as suas contribuições, colocando-as na caixa até enchê-la.

[[v14-24-11]]

^<<v14-24-11,11>>^ Sempre que os levitas levavam a caixa até os supervisores do rei, e esses viam que havia muita prata, o secretário real e o oficial do sumo sacerdote esvaziavam-na e a levavam de volta. Fazendo isso regularmente, ajuntaram uma grande quantidade de prata.

[[v14-24-12]]

^<<v14-24-12,12>>^ O rei e Joiada entregavam essa prata aos homens que executavam os trabalhos necessários no templo do Senhor. Eles contratavam pedreiros, carpinteiros e também operários que trabalham em ferro e em bronze para restaurarem o templo do Senhor.

[[v14-24-13]]

^<<v14-24-13,13>>^ Os homens encarregados do trabalho eram diligentes, o que garantiu o progresso da obra de reforma. Eles reconstruíram o templo de Deus de acordo com o modelo original e o reforçaram.

[[v14-24-14]]

^<<v14-24-14,14>>^ Quando terminaram, trouxeram o restante da prata ao rei e a Joiada, e com ela foram feitos utensílios para o templo do Senhor; utensílios para o serviço e para os holocaustos, além de tigelas e outros objetos de ouro e prata. Enquanto Joiada viveu, holocaustos foram apresentados continuamente no templo do Senhor.

[[v14-24-15]]

^<<v14-24-15,15>>^ Joiada chegou à idade avançada, e morreu com cento e trinta anos.

[[v14-24-16]]

^<<v14-24-16,16>>^ Ele foi sepultado com os reis na cidade de Davi, em atenção ao bem que havia feito em Israel em favor de Deus e do seu templo.

[[v14-24-17]]

^<<v14-24-17,17>>^ Depois da morte de Joiada, os líderes de Judá foram falar com o rei e lhe prestaram reverências, e ele aceitou o que disseram.

[[v14-24-18]]

^<<v14-24-18,18>>^ Então abandonaram o templo do Senhor, o Deus dos seus antepassados, e prestaram culto aos postes sagrados e aos ídolos. Por culpa deles, a ira de Deus veio sobre Judá e Jerusalém.

[[v14-24-19]]

^<<v14-24-19,19>>^ Embora o Senhor tivesse enviado profetas ao povo para trazê-los de volta para ele e os profetas tivessem testemunhado contra eles, o povo não quis ouvi-los.

[[v14-24-20]]

^<<v14-24-20,20>>^ Então o Espírito de Deus apoderou-se de Zacarias, filho do sacerdote Joiada. Ele se colocou diante do povo e disse: "Isto é o que Deus diz: ‘Por que vocês desobedecem aos mandamentos do Senhor? Vocês não prosperarão. Já que abandonaram o Senhor, ele os abandonará’ ".

[[v14-24-21]]

^<<v14-24-21,21>>^ Mas, alguns conspiraram contra ele e, por ordem do rei, apedrejaram-no até à morte no pátio do templo do Senhor.

[[v14-24-22]]

^<<v14-24-22,22>>^ O rei Joás não levou em conta que Joiada, pai de Zacarias, tinha sido bondoso com ele, e matou o seu filho. Este, ao morrer, exclamou: "Veja isto o Senhor e faça justiça! "

[[v14-24-23]]

^<<v14-24-23,23>>^ Na virada do ano, o exército arameu marchou contra Joás; invadiu Judá e Jerusalém, matou todos os líderes do povo, e enviou para Damasco, para o seu rei, tudo o que saqueou.

[[v14-24-24]]

^<<v14-24-24,24>>^ Embora o exército arameu fosse pequeno, o Senhor entregou nas mãos dele um exército muito maior, por haver Judá abandonado o Senhor, o Deus dos seus antepassados. Assim o juízo foi executado sobre Joás.

[[v14-24-25]]

^<<v14-24-25,25>>^ Quando os arameus foram embora, deixaram Joás seriamente ferido. Seus oficiais conspiraram contra ele, porque ele tinha assassinado o filho do sacerdote Joiada, e o mataram em sua cama. Assim ele morreu e foi sepultado na cidade de Davi, mas não nos túmulos dos reis.

[[v14-24-26]]

^<<v14-24-26,26>>^ Os que conspiraram contra ele foram Zabade, filho da amonita Simeate, e Jeozabade, filho da moabita Sinrite.

[[v14-24-27]]

^<<v14-24-27,27>>^ Quanto a seus filhos, às muitas profecias a seu respeito e ao relato da restauração do templo, tudo está escrito nas anotações dos livros dos reis. E seu filho Amazias foi o seu sucessor.

'''

xref:014-2-cronicas/014-2-cronicas-023.adoc#v14-23-0[&#60; Capítulo Anterior] | <<v14-24-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-025.adoc#v14-25-0[Próximo Capítulo &#62;]