include::./index.adoc[]

[[v14-14-0]]
=== 2 Crônicas, 14
// nvi ?, NVI - Nova Versão Internacional

[[v14-14-1]]

^<<v14-14-1,1>>^ Abias descansou com os seus antepassados e foi sepultado na cidade de Davi. E o seu filho Asa foi o seu sucessor, e em seu reinado o país esteve em paz durante dez anos.

[[v14-14-2]]

^<<v14-14-2,2>>^ Asa fez o que o Senhor, o seu Deus, aprova.

[[v14-14-3]]

^<<v14-14-3,3>>^ Retirou os altares dos deuses estrangeiros e os altares idólatras que havia nos montes, despedaçou as colunas sagradas e derrubou os postes sagrados.

[[v14-14-4]]

^<<v14-14-4,4>>^ Ordenou ao povo de Judá que buscasse o Senhor, o Deus dos seus antepassados, e que obedecesse às leis e aos mandamentos dele.

[[v14-14-5]]

^<<v14-14-5,5>>^ Retirou os altares idólatras e os altares de incenso de todas as cidades de Judá, e o reino esteve em paz durante o seu governo.

[[v14-14-6]]

^<<v14-14-6,6>>^ Também construiu cidades fortificadas em Judá, aproveitando esse período de paz. Ninguém entrou em guerra com ele durante aqueles anos, pois o Senhor lhe deu descanso.

[[v14-14-7]]

^<<v14-14-7,7>>^ Disse ele ao povo de Judá: "Vamos construir estas cidades com muros ao redor, fortificadas com torres, portas e trancas. A terra ainda é nossa, porque temos buscado o Senhor, o nosso Deus; nós o buscamos, e ele nos tem concedido paz em nossas fronteiras". Eles então as construíram e prosperaram.

[[v14-14-8]]

^<<v14-14-8,8>>^ Asa tinha um exército de trezentos mil homens de Judá, equipados com escudos grandes e lanças, e duzentos e oitenta mil de Benjamim, armados com escudos pequenos e arcos. Todos eram valentes homens de combate.

[[v14-14-9]]

^<<v14-14-9,9>>^ O etíope Zerá marchou contra eles com um exército de um milhão de soldados e trezentos carros de guerra, e chegou a Maressa.

[[v14-14-10]]

^<<v14-14-10,10>>^ Asa saiu para enfrentá-lo, e eles se puseram em posição de combate no vale de Zefatá, perto de Maressa.

[[v14-14-11]]

^<<v14-14-11,11>>^ Então Asa clamou ao Senhor, o seu Deus: "Senhor, não há ninguém como tu para ajudar os fracos contra os poderosos. Ajuda-nos, ó Senhor, ó nosso Deus, pois em ti pomos a nossa confiança, e em teu nome viemos contra este imenso exército. Ó Senhor, tu és o nosso Deus; não deixes o homem prevalecer contra ti".

[[v14-14-12]]

^<<v14-14-12,12>>^ O Senhor derrotou os etíopes diante de Asa e de Judá. Os etíopes fugiram,

[[v14-14-13]]

^<<v14-14-13,13>>^ e Asa e seu exército os perseguiram até Gerar. E caíram tantos deles que o exército não conseguiu recuperar-se; foram destruídos perante o Senhor e suas forças. E os homens de Judá saquearam muitos bens.

[[v14-14-14]]

^<<v14-14-14,14>>^ Destruíram todas as cidades ao redor de Gerar, pois o terror do Senhor havia caído sobre elas. Saquearam todas essas cidades, pois havia nelas muitos despojos.

[[v14-14-15]]

^<<v14-14-15,15>>^ Também atacaram os acampamentos onde havia gado e se apoderaram de muitas ovelhas, cabras e camelos. E então voltaram para Jerusalém.

'''

xref:014-2-cronicas/014-2-cronicas-013.adoc#v14-13-0[&#60; Capítulo Anterior] | <<v14-14-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-015.adoc#v14-15-0[Próximo Capítulo &#62;]