include::./index.adoc[]

[[v14-22-0]]
=== 2 Crônicas, 22
// nvi ?, NVI - Nova Versão Internacional

[[v14-22-1]]

^<<v14-22-1,1>>^ O povo de Jerusalém proclamou Acazias, filho mais novo de Jeorão, rei em seu lugar, uma vez que as tropas que vieram com os árabes haviam matado todos os outros filhos dele. Assim começou a reinar Acazias, filho de Jeorão, rei de Judá.

[[v14-22-2]]

^<<v14-22-2,2>>^ Acazias tinha vinte e dois anos de idade quando começou a reinar, e reinou um ano em Jerusalém. O nome de sua mãe era Atalia, neta de Onri.

[[v14-22-3]]

^<<v14-22-3,3>>^ Ele também andou nos caminhos da família de Acabe, pois sua mãe lhe dava maus conselhos.

[[v14-22-4]]

^<<v14-22-4,4>>^ Ele fez o que o Senhor reprova, como a família de Acabe havia feito, pois, depois da morte de seu pai, eles se tornaram seus conselheiros, para sua ruína.

[[v14-22-5]]

^<<v14-22-5,5>>^ Ele também seguiu o conselho deles quando aliou-se a Jorão, filho de Acabe, rei de Israel, e saiu à guerra contra Hazael, rei da Síria, em Ramote-Gileade. Jorão foi ferido

[[v14-22-6]]

^<<v14-22-6,6>>^ e voltou a Jezreel para recuperar-se dos ferimentos sofridos em Ramote, na batalha contra Hazael, rei da Síria. Depois Acazias, rei de Judá, foi a Jezreel visitar Jorão, que se recuperava de seus ferimentos.

[[v14-22-7]]

^<<v14-22-7,7>>^ Por meio dessa visita, Deus provocou a queda de Acazias. Quando ele chegou, saiu com Jorão ao encontro de Jeú, filho de Ninsi, a quem o Senhor havia ungido para destruir a família de Acabe.

[[v14-22-8]]

^<<v14-22-8,8>>^ Quando Jeú estava executando juízo sobre a família de Acabe, encontrou os líderes de Judá e os filhos dos parentes de Acazias, que o serviam, e os matou.

[[v14-22-9]]

^<<v14-22-9,9>>^ Saiu então em busca de Acazias, e seus soldados o capturaram em Samaria, onde estava escondido. Levado a Jeú, Acazias foi morto. Mas não lhe negaram sepultura, pois disseram: "Ele era neto de Josafá, que buscou o Senhor de todo o coração". Assim, a família de Acazias não tinha mais ninguém que pudesse ser rei.

[[v14-22-10]]

^<<v14-22-10,10>>^ Quando Atalia, mãe de Acazias, soube que seu filho estava morto, mandou matar toda a família real de Judá.

[[v14-22-11]]

^<<v14-22-11,11>>^ Mas Jeoseba, filha do rei Jeorão, pegou Joás, um dos filhos do rei Acazias que iam ser assassinados, e o colocou num quarto, junto com a sua ama. Assim Jeoseba, filha do rei Jeorão, mulher do sacerdote Joiada e irmã de Acazias, escondeu Joás de Atalia, de forma que ela não pôde matá-lo.

[[v14-22-12]]

^<<v14-22-12,12>>^ Seis anos ele ficou escondido com elas no templo de Deus, enquanto Atalia governava o país.

'''

xref:014-2-cronicas/014-2-cronicas-021.adoc#v14-21-0[&#60; Capítulo Anterior] | <<v14-22-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-023.adoc#v14-23-0[Próximo Capítulo &#62;]