include::./index.adoc[]

[[v14-21-0]]
=== 2 Crônicas, 21
// nvi ?, NVI - Nova Versão Internacional

[[v14-21-1]]

^<<v14-21-1,1>>^ Josafá descansou com seus antepassados e foi sepultado junto deles na cidade de Davi, e seu filho Jeorão foi o seu sucessor.

[[v14-21-2]]

^<<v14-21-2,2>>^ Os irmãos de Jeorão, filhos de Josafá, foram Azarias, Jeiel, Zacarias, Azarias, Micael e Sefatias. Todos eles foram filhos de Josafá, rei de Israel.

[[v14-21-3]]

^<<v14-21-3,3>>^ Ele deu-lhes muitos presentes de prata e ouro e objetos de valor, bem como cidades fortificadas em Judá, mas o reino deu a Jeorão, porque este era seu filho mais velho.

[[v14-21-4]]

^<<v14-21-4,4>>^ Logo Jeorão se fortaleceu no reino de seu pai, e matou à espada todos os seus irmãos, juntamente com alguns dos líderes de Israel.

[[v14-21-5]]

^<<v14-21-5,5>>^ Ele tinha trinta e dois anos de idade quando começou a reinar, e reinou oito anos em Jerusalém.

[[v14-21-6]]

^<<v14-21-6,6>>^ Andou nos caminhos dos reis de Israel, como a família de Acabe havia feito, pois se casou com uma filha de Acabe. E fez o que o Senhor reprova.

[[v14-21-7]]

^<<v14-21-7,7>>^ Entretanto, por causa da aliança que havia feito com Davi, o Senhor não quis destruir a dinastia dele. Ele havia prometido manter para sempre um descendente de Davi no trono.

[[v14-21-8]]

^<<v14-21-8,8>>^ Nos dias de Jeorão, os edomitas rebelaram-se contra o domínio de Judá, proclamando seu próprio rei.

[[v14-21-9]]

^<<v14-21-9,9>>^ Por isso, Jeorão foi combatê-los com seus líderes e com todos os seus carros de guerra. Os edomitas cercaram a ele e aos chefes de seus carros de guerra, mas ele os atacou de noite e rompeu o cerco inimigo.

[[v14-21-10]]

^<<v14-21-10,10>>^ E até hoje Edom continua independente de Judá. Nessa mesma época, a cidade de Libna também tornou-se independente, pois Jeorão havia abandonado o Senhor, o Deus dos seus antepassados.

[[v14-21-11]]

^<<v14-21-11,11>>^ Ele até construiu altares idólatras nas colinas de Judá, levando o povo de Jerusalém a prostituir-se e Judá a desviar-se.

[[v14-21-12]]

^<<v14-21-12,12>>^ Então Jeorão recebeu uma carta do profeta Elias, que dizia: "Assim diz o Senhor, o Deus de Davi, seu antepassado: ‘Você não tem andado nos caminhos de seu pai Josafá nem de Asa, rei de Judá.

[[v14-21-13]]

^<<v14-21-13,13>>^ Mas sim nos caminhos dos reis de Israel, e levou Judá e o povo de Jerusalém a se prostituírem na idolatria como a família de Acabe. E ainda assassinou seus próprios irmãos, membros da família de seu pai, homens que eram melhores do que você.

[[v14-21-14]]

^<<v14-21-14,14>>^ Por isso, o Senhor vai ferir terrivelmente seu povo, seus filhos, suas mulheres e tudo o que é seu.

[[v14-21-15]]

^<<v14-21-15,15>>^ Você ficará muito doente; terá uma enfermidade no ventre, que irá piorar até que saiam os seus intestinos’ ".

[[v14-21-16]]

^<<v14-21-16,16>>^ O Senhor despertou contra Jeorão a hostilidade dos filisteus e dos árabes que viviam perto dos etíopes.

[[v14-21-17]]

^<<v14-21-17,17>>^ Eles atacaram o reino de Judá, invadiram-no e levaram todos os bens que encontraram no palácio do rei, juntamente com suas mulheres e seus filhos. Só ficou Acazias, o filho mais novo.

[[v14-21-18]]

^<<v14-21-18,18>>^ Depois disso tudo, o Senhor afligiu Jeorão com uma doença incurável nos intestinos.

[[v14-21-19]]

^<<v14-21-19,19>>^ Algum tempo depois, ao fim do segundo ano, tanto se agravou a doença que os seus intestinos saíram, e ele morreu sofrendo dores horríveis. Seu povo não fez nenhuma fogueira em sua homenagem, como havia feito para os seus antepassados.

[[v14-21-20]]

^<<v14-21-20,20>>^ Jeorão tinha trinta e dois anos de idade quando começou a reinar, e reinou oito anos em Jerusalém. Morreu sem que ninguém o lamentasse, e foi sepultado na cidade de Davi, mas não nos túmulos dos reis.

'''

xref:014-2-cronicas/014-2-cronicas-020.adoc#v14-20-0[&#60; Capítulo Anterior] | <<v14-21-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-022.adoc#v14-22-0[Próximo Capítulo &#62;]