include::./index.adoc[]

[[v14-2-0]]
=== 2 Crônicas, 2
// nvi ?, NVI - Nova Versão Internacional

[[v14-2-1]]

^<<v14-2-1,1>>^ Salomão deu ordens para a construção de um templo em honra do nome do Senhor e de um palácio para si mesmo.

[[v14-2-2]]

^<<v14-2-2,2>>^ Ele designou setenta mil homens como carregadores, oitenta mil como cortadores de pedras nas colinas e três mil e seiscentos como capatazes.

[[v14-2-3]]

^<<v14-2-3,3>>^ Depois Salomão enviou esta mensagem a Hirão, rei de Tiro: "Envia-me cedros como fizeste para meu pai Davi, quando da construção do palácio dele.

[[v14-2-4]]

^<<v14-2-4,4>>^ Agora estou para construir um templo em honra do nome do Senhor, o meu Deus, e dedicá-lo a ele, para queimar incenso aromático diante dele, apresentar regularmente o pão consagrado e fazer holocaustos todas as manhãs e todas as tardes, nos sábados, nas luas novas e nas festas fixas do Senhor, o nosso Deus. Esse é um decreto perpétuo para Israel.

[[v14-2-5]]

^<<v14-2-5,5>>^ "O templo que vou construir será grande, pois o nosso Deus é maior do que todos os outros deuses.

[[v14-2-6]]

^<<v14-2-6,6>>^ Mas quem é capaz de construir um templo para ele, visto que os céus não podem contê-lo, nem mesmo os mais altos céus? Quem sou eu, então, para lhe construir um templo, a não ser como um lugar para queimar sacrifícios perante ele?

[[v14-2-7]]

^<<v14-2-7,7>>^ "Por isso, manda-me um homem competente no trabalho com ouro, com prata, com bronze, com ferro e com tecido roxo, vermelho e azul, e experiente em esculturas, para trabalhar em Judá e em Jerusalém com os meus hábeis artesãos, preparados por meu pai Davi.

[[v14-2-8]]

^<<v14-2-8,8>>^ "Também envia-me do Líbano madeira de cedro, de pinho e de junípero, pois eu sei que os teus servos são hábeis em cortar a madeira de lá. Os meus servos trabalharão com os teus

[[v14-2-9]]

^<<v14-2-9,9>>^ para me fornecerem madeira em grande quantidade, pois é preciso que o templo que vou edificar seja grande e imponente.

[[v14-2-10]]

^<<v14-2-10,10>>^ E eu darei como sustento a teus servos, os lenhadores, vinte mil tonéis de trigo, vinte mil tonéis de cevada, dois mil barris de vinho e dois mil barris de azeite".

[[v14-2-11]]

^<<v14-2-11,11>>^ Hirão, rei de Tiro, respondeu por carta a Salomão: "O Senhor ama o seu povo, e por isso te fez rei sobre ele".

[[v14-2-12]]

^<<v14-2-12,12>>^ E acrescentou: "Bendito seja o Senhor, o Deus de Israel, que fez os céus e a terra, pois deu ao rei Davi um filho sábio, que tem inteligência e discernimento, e que vai construir um templo para o Senhor e um palácio para si.

[[v14-2-13]]

^<<v14-2-13,13>>^ "Estou te enviando Hirão-Abi, homem de grande habilidade.

[[v14-2-14]]

^<<v14-2-14,14>>^ Sua mãe era de Dã e seu pai, de Tiro. Ele foi treinado para trabalhar com ouro e prata, bronze e ferro, pedra e madeira, e em tecido roxo, azul e vermelho, e em linho fino e em todo tipo de entalhe. Ele pode executar qualquer projeto que lhe for dado. Trabalhará com os teus artesãos e com os de meu senhor Davi, teu pai.

[[v14-2-15]]

^<<v14-2-15,15>>^ "Agora, envie meu senhor a seus servos o trigo, a cevada, o azeite e o vinho que prometeste,

[[v14-2-16]]

^<<v14-2-16,16>>^ e cortaremos toda a madeira do Líbano necessária, e a faremos flutuar em jangadas pelo mar, descendo até Jope. De lá poderás levá-la a Jerusalém".

[[v14-2-17]]

^<<v14-2-17,17>>^ Salomão fez um recenseamento de todos os estrangeiros que viviam em Israel, como o que fizera seu pai Davi; e descobriu-se que eram cento e cinqüenta e três mil e seiscentos.

[[v14-2-18]]

^<<v14-2-18,18>>^ Ele designou setenta mil deles para serem carregadores e oitenta mil para serem cortadores de pedras nas colinas, com três mil e seiscentos capatazes para manter o povo trabalhando.

'''

xref:014-2-cronicas/014-2-cronicas-001.adoc#v14-1-0[&#60; Capítulo Anterior] | <<v14-2-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-003.adoc#v14-3-0[Próximo Capítulo &#62;]