include::./index.adoc[]

[[v14-3-0]]
=== 2 Crônicas, 3
// nvi ?, NVI - Nova Versão Internacional

[[v14-3-1]]

^<<v14-3-1,1>>^ Então Salomão começou a construir o templo do Senhor em Jerusalém, no monte Moriá, onde o Senhor havia aparecido a seu pai Davi, na eira de Araúna, o jebuseu. Local providenciado por Davi.

[[v14-3-2]]

^<<v14-3-2,2>>^ Ele começou a construir no segundo dia do segundo mês do quarto ano de seu reinado.

[[v14-3-3]]

^<<v14-3-3,3>>^ Os alicerces que Salomão lançou para o templo de Deus tinham vinte e sete metros de comprimento e nove metros de largura, pela medida antiga.

[[v14-3-4]]

^<<v14-3-4,4>>^ O pórtico da entrada do templo tinha nove metros de largura e nove metros de altura. Ele revestiu de ouro puro o seu interior.

[[v14-3-5]]

^<<v14-3-5,5>>^ Recobriu de pinho o átrio principal, revestiu-o de ouro puro e o decorou com desenhos de tamareiras e correntes.

[[v14-3-6]]

^<<v14-3-6,6>>^ Ornamentou o templo com pedras preciosas. O ouro utilizado era de Parvaim.

[[v14-3-7]]

^<<v14-3-7,7>>^ Também revestiu de ouro as vigas do forro, os batentes, as paredes e as portas do templo, e esculpiu querubins nas paredes.

[[v14-3-8]]

^<<v14-3-8,8>>^ Fez o Lugar Santíssimo, com nove metros de comprimento e nove metros de largura, igual à largura do templo. Revestiu de vinte e uma toneladas de ouro puro o seu interior.

[[v14-3-9]]

^<<v14-3-9,9>>^ Os pregos de ouro pesavam seiscentos gramas. Também revestiu de ouro as salas superiores.

[[v14-3-10]]

^<<v14-3-10,10>>^ No Lugar Santíssimo esculpiu e revestiu de ouro dois querubins,

[[v14-3-11]]

^<<v14-3-11,11>>^ os quais, de asas abertas, mediam juntos nove metros. Cada asa, de dois metros e vinte e cinco centímetros, tocava, de um lado, na parede do templo,

[[v14-3-12]]

^<<v14-3-12,12>>^ e do outro lado, na asa do outro querubim.

[[v14-3-13]]

^<<v14-3-13,13>>^ Assim os querubins, com asas que se estendiam por nove metros, estavam de pé, de frente para o átrio principal.

[[v14-3-14]]

^<<v14-3-14,14>>^ Ele fez o véu de tecido azul, roxo, vermelho e linho fino com querubins desenhados nele.

[[v14-3-15]]

^<<v14-3-15,15>>^ Fez na frente do templo duas colunas, que juntas tinham dezesseis metros, cada uma tendo em cima um capitel com dois metros e vinte e cinco centímetros.

[[v14-3-16]]

^<<v14-3-16,16>>^ E fez correntes entrelaçadas e colocou-as no alto das colunas. Fez também cem romãs, colocando-as nas correntes.

[[v14-3-17]]

^<<v14-3-17,17>>^ Então levantou as colunas na frente do templo, uma ao sul, outra ao norte; à que ficava ao sul deu o nome de Jaquim, e à que ficava ao norte, Boaz.

'''

xref:014-2-cronicas/014-2-cronicas-002.adoc#v14-2-0[&#60; Capítulo Anterior] | <<v14-3-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-004.adoc#v14-4-0[Próximo Capítulo &#62;]