include::./index.adoc[]

[[v2-30-0]]
=== Êxodo, 30
// nvi ?, NVI - Nova Versão Internacional

[[v2-30-1]]

^<<v2-30-1,1>>^ "Faça um altar de madeira de acácia para queimar incenso.

[[v2-30-2]]

^<<v2-30-2,2>>^ Será quadrado, com quarenta e cinco centímetros de cada lado e noventa centímetros de altura; suas pontas formarão com ele uma só peça.

[[v2-30-3]]

^<<v2-30-3,3>>^ Revista de ouro puro a parte superior, todos os lados e as pontas, e faça uma moldura de ouro ao seu redor.

[[v2-30-4]]

^<<v2-30-4,4>>^ Faça duas argolas de ouro de cada lado do altar, abaixo da moldura, que sustentem as varas utilizadas para carregá-lo,

[[v2-30-5]]

^<<v2-30-5,5>>^ e use madeira de acácia para fazer as varas e revista-as de ouro.

[[v2-30-6]]

^<<v2-30-6,6>>^ Coloque o altar em frente do véu que se encontra diante da arca da aliança, diante da tampa que está sobre ele, onde me encontrarei com você.

[[v2-30-7]]

^<<v2-30-7,7>>^ "Arão queimará incenso aromático sobre o altar todas as manhãs, quando vier cuidar das lâmpadas,

[[v2-30-8]]

^<<v2-30-8,8>>^ e também quando acendê-las ao entardecer. Será queimado incenso continuamente perante o Senhor, pelas suas gerações.

[[v2-30-9]]

^<<v2-30-9,9>>^ Não ofereçam nesse altar nenhum outro tipo de incenso nem holocausto nem oferta de cereal nem derramem sobre ele ofertas de bebidas.

[[v2-30-10]]

^<<v2-30-10,10>>^ Uma vez por ano, Arão fará propiciação sobre as pontas do altar. Essa propiciação anual será realizada com o sangue da oferta para propiciação pelo pecado, geração após geração. Esse altar é santíssimo ao Senhor. "

[[v2-30-11]]

^<<v2-30-11,11>>^ Disse então o Senhor a Moisés:

[[v2-30-12]]

^<<v2-30-12,12>>^ "Quando você fizer o recenseamento dos israelitas, cada um deles terá que pagar ao Senhor um preço pelo resgate por sua vida quando for contado. Dessa forma nenhuma praga virá sobre eles quando você os contar.

[[v2-30-13]]

^<<v2-30-13,13>>^ Cada recenseado contribuirá com seis gramas, com base no peso padrão do santuário, que tem doze gramas. As seis gramas são uma oferta ao Senhor.

[[v2-30-14]]

^<<v2-30-14,14>>^ Todos os alistados, da idade de vinte anos para cima, darão ao Senhor essa oferta.

[[v2-30-15]]

^<<v2-30-15,15>>^ Os ricos não contribuirão com mais, nem os pobres darão menos que seis gramas, quando apresentarem a oferta ao Senhor como propiciação por suas vidas.

[[v2-30-16]]

^<<v2-30-16,16>>^ Receba dos israelitas o preço da propiciação e use-o para o serviço da Tenda do Encontro. Será um memorial perante o Senhor em favor dos israelitas, para fazerem propiciação por suas vidas".

[[v2-30-17]]

^<<v2-30-17,17>>^ Disse então o Senhor a Moisés:

[[v2-30-18]]

^<<v2-30-18,18>>^ "Faça uma bacia de bronze com uma base de bronze, para se lavarem. Coloque-a entre a Tenda do Encontro e o altar, e mande enchê-la de água.

[[v2-30-19]]

^<<v2-30-19,19>>^ Arão e seus filhos lavarão as mãos e os pés com a água da bacia.

[[v2-30-20]]

^<<v2-30-20,20>>^ Toda vez que entrarem na Tenda do Encontro, terão que lavar-se com água, para que não morram. Quando também se aproximarem do altar para ministrar ao Senhor, apresentando uma oferta preparada no fogo,

[[v2-30-21]]

^<<v2-30-21,21>>^ lavarão as mãos e os pés para que não morram. Esse é um decreto perpétuo, para Arão e os seus descendentes, geração após geração".

[[v2-30-22]]

^<<v2-30-22,22>>^ Em seguida o Senhor disse a Moisés:

[[v2-30-23]]

^<<v2-30-23,23>>^ "Junte as seguintes especiarias: seis quilos de mirra líquida, a metade disso, ou seja, três quilos de canela, três quilos de cana aromática,

[[v2-30-24]]

^<<v2-30-24,24>>^ seis quilos de cássia, com base no peso padrão do santuário, e um galão de azeite de oliva.

[[v2-30-25]]

^<<v2-30-25,25>>^ Faça com eles o óleo sagrado para as unções, uma mistura de aromas, obra de perfumista. Este será o óleo sagrado para as unções.

[[v2-30-26]]

^<<v2-30-26,26>>^ Use-o para ungir a Tenda do Encontro, a arca da aliança,

[[v2-30-27]]

^<<v2-30-27,27>>^ a mesa e todos os seus utensílios, o candelabro e os seus utensílios, o altar do incenso,

[[v2-30-28]]

^<<v2-30-28,28>>^ o altar do holocausto e todos os seus utensílios, e a bacia com a sua base.

[[v2-30-29]]

^<<v2-30-29,29>>^ Você os consagrará e serão santíssimos, e tudo o que neles tocar se tornará santo.

[[v2-30-30]]

^<<v2-30-30,30>>^ "Unja Arão e seus filhos e consagre-os para que me sirvam como sacerdotes.

[[v2-30-31]]

^<<v2-30-31,31>>^ Diga aos israelitas: Este será o meu óleo sagrado para as unções, geração após geração.

[[v2-30-32]]

^<<v2-30-32,32>>^ Não o derramem sobre nenhum outro homem, e não façam nenhum outro óleo com a mesma composição. É óleo sagrado, e assim vocês devem considerá-lo.

[[v2-30-33]]

^<<v2-30-33,33>>^ Quem fizer óleo como esse ou usá-lo em alguém que não seja sacerdote, será eliminado do meio do seu povo".

[[v2-30-34]]

^<<v2-30-34,34>>^ Disse ainda o Senhor a Moisés: "Junte as seguintes essências: bálsamo, ônica, gálbano e incenso puro, todos em quantidades iguais,

[[v2-30-35]]

^<<v2-30-35,35>>^ e faça um incenso de mistura aromática, obra de perfumista. Levará sal, será puro e santo.

[[v2-30-36]]

^<<v2-30-36,36>>^ Moa parte dele, até virar pó, e coloque-o diante das tábuas da aliança, na Tenda do Encontro, onde me encontrarei com você. O incenso lhes será santíssimo.

[[v2-30-37]]

^<<v2-30-37,37>>^ Não façam nenhum outro incenso com a mesma composição para uso pessoal; considerem-no sagrado, reservado para o Senhor.

[[v2-30-38]]

^<<v2-30-38,38>>^ Quem fizer um incenso semelhante, para usufruir sua fragrância, será eliminado do seu povo".

'''

xref:002-exodo/002-exodo-029.adoc#v2-29-0[&#60; Capítulo Anterior] | <<v2-30-0,Topo>> | xref:002-exodo/002-exodo-031.adoc#v2-31-0[Próximo Capítulo &#62;]