include::./index.adoc[]

[[v2-27-0]]
=== Êxodo, 27
// nvi ?, NVI - Nova Versão Internacional

[[v2-27-1]]

^<<v2-27-1,1>>^ "Faça um altar de madeira de acácia. Será quadrado, com dois metros e vinte e cinco centímetros de largura e um metro e trinta e cinco centímetros de altura.

[[v2-27-2]]

^<<v2-27-2,2>>^ Faça uma ponta em forma de chifre em cada um dos quatro cantos, formando uma só peça com o altar, que será revestido de bronze.

[[v2-27-3]]

^<<v2-27-3,3>>^ Faça de bronze todos os seus utensílios: os recipientes para recolher cinzas, as pás, as bacias de aspersão, os garfos para carne e os braseiros.

[[v2-27-4]]

^<<v2-27-4,4>>^ Faça também para ele uma grelha de bronze em forma de rede e uma argola de bronze em cada um dos quatro cantos da grelha.

[[v2-27-5]]

^<<v2-27-5,5>>^ Coloque-a abaixo da beirada do altar, de maneira que fique a meia altura do altar.

[[v2-27-6]]

^<<v2-27-6,6>>^ Faça varas de madeira de acácia para o altar e revista-as de bronze.

[[v2-27-7]]

^<<v2-27-7,7>>^ Estas varas serão colocadas nas argolas, dos dois lados do altar, quando este for carregado.

[[v2-27-8]]

^<<v2-27-8,8>>^ Faça o altar oco e de tábuas, conforme lhe foi mostrado no monte.

[[v2-27-9]]

^<<v2-27-9,9>>^ "Faça um pátio para o tabernáculo. O lado sul terá quarenta e cinco metros de comprimento, e cortinas externas de linho fino trançado,

[[v2-27-10]]

^<<v2-27-10,10>>^ com vinte colunas e vinte bases de bronze, com ganchos e ligaduras de prata nas colunas.

[[v2-27-11]]

^<<v2-27-11,11>>^ O lado norte também terá quarenta e cinco metros de comprimento e cortinas externas, com vinte colunas e vinte bases de bronze, com ganchos e ligaduras de prata nas colunas.

[[v2-27-12]]

^<<v2-27-12,12>>^ "O lado ocidental, com as suas cortinas externas, terá vinte e dois metros e meio de largura, com dez colunas e dez bases.

[[v2-27-13]]

^<<v2-27-13,13>>^ O lado oriental, que dá para o nascente, também terá vinte e dois metros e meio de largura.

[[v2-27-14]]

^<<v2-27-14,14>>^ Haverá cortinas de seis metros e setenta e cinco centímetros de comprimento num dos lados da entrada, com três colunas e três bases,

[[v2-27-15]]

^<<v2-27-15,15>>^ e cortinas externas de seis metros e setenta e cinco centímetros de comprimento no outro lado, também com três colunas e três bases.

[[v2-27-16]]

^<<v2-27-16,16>>^ "Na entrada do pátio, haverá uma cortina de nove metros de comprimento, de linho fino trançado e de fios de tecido azul, roxo e vermelho, obra de bordador, com quatro colunas e quatro bases.

[[v2-27-17]]

^<<v2-27-17,17>>^ Todas as colunas ao redor do pátio terão ligaduras e ganchos de prata e bases de bronze.

[[v2-27-18]]

^<<v2-27-18,18>>^ O pátio terá quarenta e cinco metros de comprimento e vinte e dois metros e meio de largura, com cortinas de linho fino trançado de dois metros e vinte e cinco centímetros de altura e bases de bronze.

[[v2-27-19]]

^<<v2-27-19,19>>^ Todos os utensílios para o serviço do tabernáculo, inclusive todas as estacas da tenda e as do pátio, serão feitos de bronze.

[[v2-27-20]]

^<<v2-27-20,20>>^ "Ordene aos israelitas que lhe tragam azeite puro de oliva batida para a iluminação, para que as lâmpadas fiquem sempre acesas.

[[v2-27-21]]

^<<v2-27-21,21>>^ Na Tenda do Encontro, do lado de fora do véu que se encontra diante das tábuas da aliança, Arão e seus filhos manterão acesas as lâmpadas diante do Senhor, do entardecer até de manhã. Este será um decreto perpétuo entre os israelitas, geração após geração. "

'''

xref:002-exodo/002-exodo-026.adoc#v2-26-0[&#60; Capítulo Anterior] | <<v2-27-0,Topo>> | xref:002-exodo/002-exodo-028.adoc#v2-28-0[Próximo Capítulo &#62;]