include::./index.adoc[]

[[v2-31-0]]
=== Êxodo, 31
// nvi ?, NVI - Nova Versão Internacional

[[v2-31-1]]

^<<v2-31-1,1>>^ Disse então o Senhor a Moisés:

[[v2-31-2]]

^<<v2-31-2,2>>^ "Eu escolhi a Bezalel, filho de Uri, filho de Hur, da tribo de Judá,

[[v2-31-3]]

^<<v2-31-3,3>>^ e o enchi do Espírito de Deus, dando-lhes destreza, habilidade e plena capacidade artística

[[v2-31-4]]

^<<v2-31-4,4>>^ para desenhar e executar trabalhos em ouro, prata e bronze,

[[v2-31-5]]

^<<v2-31-5,5>>^ para talhar e esculpir pedras, para entalhar madeira e executar todo tipo de obra artesanal.

[[v2-31-6]]

^<<v2-31-6,6>>^ Além disso, designei Aoliabe, filho de Aisamaque, da tribo de Dã, para auxiliá-lo. Também capacitei a todos os artesãos para que executem tudo o que lhe ordenei:

[[v2-31-7]]

^<<v2-31-7,7>>^ A Tenda do Encontro, a arca da aliança e a tampa que está sobre ela, e todos os outros utensílios da tenda —

[[v2-31-8]]

^<<v2-31-8,8>>^ a mesa com os seus utensílios, o candelabro de ouro puro e os seus utensílios, o altar do incenso,

[[v2-31-9]]

^<<v2-31-9,9>>^ o altar do holocausto com os seus utensílios, a bacia com a sua base —

[[v2-31-10]]

^<<v2-31-10,10>>^ assim como as vestes litúrgicas, tanto as vestes sagradas para Arão, o sacerdote, como as vestes para os seus filhos, quando servirem como sacerdotes,

[[v2-31-11]]

^<<v2-31-11,11>>^ bem como o óleo para as unções e o incenso aromático para o Lugar Santo. Tudo deve ser feito exatamente como eu lhe ordenei".

[[v2-31-12]]

^<<v2-31-12,12>>^ Disse ainda o Senhor a Moisés:

[[v2-31-13]]

^<<v2-31-13,13>>^ "Diga aos israelitas que guardem os meus sábados. Isso será um sinal entre mim e vocês, geração após geração, a fim de que saibam que eu sou o Senhor, que os santifica.

[[v2-31-14]]

^<<v2-31-14,14>>^ "Guardem o sábado, pois para vocês é santo. Aquele que o profanar terá que ser executado; quem fizer algum trabalho nesse dia será eliminado do meio do seu povo.

[[v2-31-15]]

^<<v2-31-15,15>>^ Em seis dias qualquer trabalho poderá ser feito, mas o sétimo dia é o sábado, o dia de descanso, consagrado ao Senhor. Quem fizer algum trabalho no sábado terá que ser executado.

[[v2-31-16]]

^<<v2-31-16,16>>^ Os israelitas terão que guardar o sábado, eles e os seus descendentes, como uma aliança perpétua.

[[v2-31-17]]

^<<v2-31-17,17>>^ Isso será um sinal perpétuo entre mim e os israelitas, pois em seis dias o Senhor fez os céus e a terra, e no sétimo dia ele não trabalhou e descansou".

[[v2-31-18]]

^<<v2-31-18,18>>^ Quando o Senhor terminou de falar com Moisés no monte Sinai, deu-lhe as duas tábuas da aliança, tábuas de pedra, escritas pelo dedo de Deus.

'''

xref:002-exodo/002-exodo-030.adoc#v2-30-0[&#60; Capítulo Anterior] | <<v2-31-0,Topo>> | xref:002-exodo/002-exodo-032.adoc#v2-32-0[Próximo Capítulo &#62;]