include::./index.adoc[]

[[v2-12-0]]
=== Êxodo, 12
// nvi ?, NVI - Nova Versão Internacional

[[v2-12-1]]

^<<v2-12-1,1>>^ O Senhor disse a Moisés e a Arão, no Egito:

[[v2-12-2]]

^<<v2-12-2,2>>^ "Este deverá ser o primeiro mês do ano para vocês.

[[v2-12-3]]

^<<v2-12-3,3>>^ Digam a toda a comunidade de Israel que no décimo dia deste mês todo homem deverá separar um cordeiro ou um cabrito, para a sua família, um para cada casa.

[[v2-12-4]]

^<<v2-12-4,4>>^ Se uma família for pequena demais para um animal inteiro, deve dividi-lo com seu vizinho mais próximo, conforme o número de pessoas e conforme o que cada um puder comer.

[[v2-12-5]]

^<<v2-12-5,5>>^ O animal escolhido será macho de um ano, sem defeito, e pode ser cordeiro ou cabrito.

[[v2-12-6]]

^<<v2-12-6,6>>^ Guardem-no até o décimo quarto dia do mês, quando toda a comunidade de Israel irá sacrificá-lo, ao pôr-do-sol.

[[v2-12-7]]

^<<v2-12-7,7>>^ Passem, então, um pouco do sangue nas laterais e nas vigas superiores das portas das casas nas quais vocês comerão o animal.

[[v2-12-8]]

^<<v2-12-8,8>>^ Naquela mesma noite comerão a carne assada no fogo, juntamente com ervas amargas e pão sem fermento.

[[v2-12-9]]

^<<v2-12-9,9>>^ Não comam a carne crua, nem cozida em água, mas assada no fogo: cabeça, pernas e vísceras.

[[v2-12-10]]

^<<v2-12-10,10>>^ Não deixem sobrar nada até pela manhã; caso isso aconteça, queimem o que restar.

[[v2-12-11]]

^<<v2-12-11,11>>^ Ao comerem, estejam prontos para sair: cinto no lugar, sandálias nos pés e cajado na mão. Comam apressadamente. Esta é a Páscoa do Senhor.

[[v2-12-12]]

^<<v2-12-12,12>>^ "Naquela mesma noite passarei pelo Egito e matarei todos os primogênitos, tanto dos homens como dos animais, e executarei juízo sobre todos os deuses do Egito. Eu sou o Senhor!

[[v2-12-13]]

^<<v2-12-13,13>>^ O sangue será um sinal para indicar as casas em que vocês estiverem; quando eu vir o sangue, passarei adiante. A praga de destruição não os atingirá quando eu ferir o Egito.

[[v2-12-14]]

^<<v2-12-14,14>>^ "Este dia será um memorial que vocês e todos os seus descendentes o comemorarão como festa ao Senhor. Comemorem-no como decreto perpétuo.

[[v2-12-15]]

^<<v2-12-15,15>>^ Durante sete dias comam pão sem fermento. No primeiro dia tirem de casa o fermento, porque quem comer qualquer coisa fermentada, do primeiro ao sétimo dia, será eliminado de Israel.

[[v2-12-16]]

^<<v2-12-16,16>>^ Convoquem uma reunião santa no primeiro dia e outra no sétimo. Não façam nenhum trabalho nesses dias, exceto o da preparação da comida para todos. É só o que poderão fazer.

[[v2-12-17]]

^<<v2-12-17,17>>^ "Celebrem a festa dos pães sem fermento, porque foi nesse mesmo dia que eu tirei os exércitos de vocês do Egito. Celebrem esse dia como decreto perpétuo por todas as suas gerações.

[[v2-12-18]]

^<<v2-12-18,18>>^ No primeiro mês comam pão sem fermento, desde o entardecer do décimo quarto dia até o entardecer do vigésimo primeiro.

[[v2-12-19]]

^<<v2-12-19,19>>^ Durante sete dias vocês não deverão ter fermento em casa. Quem comer qualquer coisa fermentada será eliminado da comunidade de Israel, seja estrangeiro, seja natural da terra.

[[v2-12-20]]

^<<v2-12-20,20>>^ Não comam nada fermentado. Onde quer que morarem, comam apenas pão sem fermento".

[[v2-12-21]]

^<<v2-12-21,21>>^ Então Moisés convocou todas as autoridades de Israel e lhes disse: "Escolham um cordeiro ou um cabrito para cada família. Sacrifiquem-no para celebrar a Páscoa!

[[v2-12-22]]

^<<v2-12-22,22>>^ Molhem um feixe de hissopo no sangue que estiver na bacia e passem o sangue na viga superior e nas laterais das portas. Nenhum de vocês poderá sair de casa até o amanhecer.

[[v2-12-23]]

^<<v2-12-23,23>>^ Quando o Senhor passar pela terra para matar os egípcios, verá o sangue na viga superior e nas laterais da porta e passará sobre aquela porta; e não permitirá que o destruidor entre na casa de vocês para matá-los.

[[v2-12-24]]

^<<v2-12-24,24>>^ "Obedeçam a estas instruções como decreto perpétuo para vocês e para os seus descendentes.

[[v2-12-25]]

^<<v2-12-25,25>>^ Quando entrarem na terra que o Senhor prometeu lhes dar, celebrem essa cerimônia.

[[v2-12-26]]

^<<v2-12-26,26>>^ Quando os seus filhos lhes perguntarem: ‘O que significa esta cerimônia? ’,

[[v2-12-27]]

^<<v2-12-27,27>>^ respondam-lhes: É o sacrifício da Páscoa ao Senhor, que passou sobre as casas dos israelitas no Egito e poupou nossas casas quando matou os egípcios". Então o povo curvou-se em adoração.

[[v2-12-28]]

^<<v2-12-28,28>>^ Depois os israelitas se retiraram e fizeram conforme o Senhor tinha ordenado a Moisés e a Arão.

[[v2-12-29]]

^<<v2-12-29,29>>^ Então, à meia-noite, o Senhor matou todos os primogênitos do Egito, desde o filho mais velho do faraó, herdeiro do trono, até o filho mais velho do prisioneiro que estava no calabouço, e também todas as primeiras crias do gado.

[[v2-12-30]]

^<<v2-12-30,30>>^ No meio da noite o faraó, todos os seus conselheiros e todos os egípcios se levantaram. E houve grande pranto no Egito, pois não havia casa que não houvesse um morto.

[[v2-12-31]]

^<<v2-12-31,31>>^ Naquela mesma noite o faraó mandou chamar Moisés e Arão e lhes disse: "Saiam imediatamente do meio do meu povo, vocês e os israelitas! Vão prestar culto ao Senhor, como vocês pediram.

[[v2-12-32]]

^<<v2-12-32,32>>^ Levem os seus rebanhos, como tinham dito, e abençoem a mim também".

[[v2-12-33]]

^<<v2-12-33,33>>^ Os egípcios pressionavam o povo para que se apressasse em sair do país, dizendo: "Todos nós morreremos! "

[[v2-12-34]]

^<<v2-12-34,34>>^ Então o povo tomou a massa de pão ainda sem fermento e a carregou nos ombros, nas amassadeiras embrulhadas em suas roupas.

[[v2-12-35]]

^<<v2-12-35,35>>^ Os israelitas obedeceram à ordem de Moisés e pediram aos egípcios objetos de prata e de ouro, bem como roupas.

[[v2-12-36]]

^<<v2-12-36,36>>^ O Senhor concedeu ao povo uma disposição favorável da parte dos egípcios, de modo que lhes davam o que pediam; assim eles despojaram os egípcios.

[[v2-12-37]]

^<<v2-12-37,37>>^ Os israelitas foram de Ramessés até Sucote. Havia cerca de seiscentos mil homens a pé, além de mulheres e crianças.

[[v2-12-38]]

^<<v2-12-38,38>>^ Grande multidão de estrangeiros de todo tipo seguiu com eles, além de grandes rebanhos, tanto de bois como de ovelhas e cabras.

[[v2-12-39]]

^<<v2-12-39,39>>^ Com a massa que haviam trazido do Egito, fizeram pães sem fermento. A massa não tinha fermentado, pois eles foram expulsos do Egito e não tiveram tempo de preparar comida.

[[v2-12-40]]

^<<v2-12-40,40>>^ Ora, o período que os israelitas viveram no Egito foi de quatrocentos e trinta anos.

[[v2-12-41]]

^<<v2-12-41,41>>^ No dia quando se completaram os quatrocentos e trinta anos, todos os exércitos do Senhor saíram do Egito.

[[v2-12-42]]

^<<v2-12-42,42>>^ Assim como o Senhor passou em vigília aquela noite para tirar do Egito os israelitas, estes também devem passar em vigília essa mesma noite, para honrar ao Senhor, por todas as suas gerações.

[[v2-12-43]]

^<<v2-12-43,43>>^ Disse o Senhor a Moisés e a Arão: "Estas são as leis da Páscoa: Nenhum estrangeiro poderá comê-la.

[[v2-12-44]]

^<<v2-12-44,44>>^ O escravo comprado poderá comer da Páscoa, depois de circuncidado,

[[v2-12-45]]

^<<v2-12-45,45>>^ mas o residente temporário e o trabalhador contratado dela não comerão.

[[v2-12-46]]

^<<v2-12-46,46>>^ "Vocês a comerão numa só casa; não levem nenhum pedaço de carne para fora da casa, nem quebrem nenhum dos ossos.

[[v2-12-47]]

^<<v2-12-47,47>>^ Toda a comunidade de Israel terá que celebrar a Páscoa.

[[v2-12-48]]

^<<v2-12-48,48>>^ "Qualquer estrangeiro residente entre vocês que quiser celebrar a Páscoa do Senhor terá que circuncidar todos os do sexo masculino da sua família; então poderá participar como o natural da terra. Nenhum incircunciso poderá participar.

[[v2-12-49]]

^<<v2-12-49,49>>^ A mesma lei se aplicará ao natural da terra e ao estrangeiro residente".

[[v2-12-50]]

^<<v2-12-50,50>>^ Todos os israelitas fizeram como o Senhor tinha ordenado a Moisés e a Arão.

[[v2-12-51]]

^<<v2-12-51,51>>^ No mesmo dia o Senhor tirou os israelitas do Egito, organizados segundo as suas divisões.

'''

xref:002-exodo/002-exodo-011.adoc#v2-11-0[&#60; Capítulo Anterior] | <<v2-12-0,Topo>> | xref:002-exodo/002-exodo-013.adoc#v2-13-0[Próximo Capítulo &#62;]