include::./index.adoc[]

[[v2-28-0]]
=== Êxodo, 28
// nvi ?, NVI - Nova Versão Internacional

[[v2-28-1]]

^<<v2-28-1,1>>^ "Chame seu irmão Arão e separe-o dentre os israelitas, e também os seus filhos Nadabe e Abiú, Eleazar e Itamar, para que me sirvam como sacerdotes.

[[v2-28-2]]

^<<v2-28-2,2>>^ Para o seu irmão Arão, faça vestes sagradas que lhe confiram dignidade e honra.

[[v2-28-3]]

^<<v2-28-3,3>>^ Diga a todos os homens capazes, aos quais dei habilidade, que façam vestes para a consagração de Arão, para que me sirva como sacerdote.

[[v2-28-4]]

^<<v2-28-4,4>>^ São estas as vestes que farão: um peitoral, um colete sacerdotal, um manto, uma túnica bordada, um turbante e um cinturão. Para que o sacerdote Arão e seus filhos me sirvam como sacerdotes, eles farão essas vestes sagradas

[[v2-28-5]]

^<<v2-28-5,5>>^ e usarão linho fino, fios de ouro e fios de tecido azul, roxo e vermelho.

[[v2-28-6]]

^<<v2-28-6,6>>^ "Faça o colete sacerdotal de linho fino trançado e de fios de ouro e de fios de tecido azul, roxo e vermelho, trabalho artesanal.

[[v2-28-7]]

^<<v2-28-7,7>>^ Terá duas ombreiras atadas às suas duas extremidades para uni-lo bem.

[[v2-28-8]]

^<<v2-28-8,8>>^ O cinturão e o colete que por ele é preso serão feitos da mesma peça. O cinturão também será de linho fino trançado, de fios de ouro e de fios de tecido azul, roxo e vermelho.

[[v2-28-9]]

^<<v2-28-9,9>>^ "Grave em duas pedras de ônix os nomes dos filhos de Israel,

[[v2-28-10]]

^<<v2-28-10,10>>^ por ordem de nascimento: seis nomes numa pedra e seis na outra.

[[v2-28-11]]

^<<v2-28-11,11>>^ Grave os nomes dos filhos de Israel nas duas pedras como o lapidador grava um selo. Em seguida prenda-as com filigranas de ouro,

[[v2-28-12]]

^<<v2-28-12,12>>^ costurando-as nas ombreiras do colete sacerdotal, como pedras memoriais para os filhos de Israel. Assim Arão levará os nomes em seus ombros como memorial diante do Senhor.

[[v2-28-13]]

^<<v2-28-13,13>>^ Faça filigranas de ouro

[[v2-28-14]]

^<<v2-28-14,14>>^ e duas correntes de ouro puro, entrelaçadas como uma corda; e prenda as correntes às filigranas.

[[v2-28-15]]

^<<v2-28-15,15>>^ "Faça um peitoral de decisões, trabalho artesanal. Faça-o como o colete sacerdotal: de linho fino trançado e de fios de ouro e de fios de tecido azul, roxo e vermelho.

[[v2-28-16]]

^<<v2-28-16,16>>^ Será quadrado, com um palmo de comprimento e um palmo de largura, e dobrado em dois.

[[v2-28-17]]

^<<v2-28-17,17>>^ Em seguida, fixe nele quatro fileiras de pedras preciosas. Na primeira fileira haverá um rubi, um topázio e um berilo;

[[v2-28-18]]

^<<v2-28-18,18>>^ na segunda, uma turquesa, uma safira e um diamante;

[[v2-28-19]]

^<<v2-28-19,19>>^ na terceira, um jacinto, uma ágata e uma ametista;

[[v2-28-20]]

^<<v2-28-20,20>>^ na quarta, um crisólito, um ônix e um jaspe.

[[v2-28-21]]

^<<v2-28-21,21>>^ Serão doze pedras, uma para cada um dos nomes dos filhos de Israel, cada uma gravada como um selo, com o nome de uma das doze tribos.

[[v2-28-22]]

^<<v2-28-22,22>>^ "Faça para o peitoral correntes de ouro puro trançadas como cordas.

[[v2-28-23]]

^<<v2-28-23,23>>^ Faça também duas argolas de ouro e prenda-as às duas extremidades do peitoral.

[[v2-28-24]]

^<<v2-28-24,24>>^ Prenda as duas correntes de ouro às argolas nas extremidades do peitoral,

[[v2-28-25]]

^<<v2-28-25,25>>^ e as outras extremidades das correntes, às duas filigranas, unindo-as às peças das ombreiras do colete sacerdotal, na parte da frente.

[[v2-28-26]]

^<<v2-28-26,26>>^ Faça outras duas argolas de ouro e prenda-as às outras duas extremidades do peitoral, na borda interna, próxima ao colete sacerdotal.

[[v2-28-27]]

^<<v2-28-27,27>>^ Faça mais duas argolas de ouro e prenda-as na parte inferior das ombreiras, na frente do colete sacerdotal, próximas da costura, logo acima do cinturão do colete sacerdotal.

[[v2-28-28]]

^<<v2-28-28,28>>^ As argolas do peitoral serão amarradas às argolas do colete com um cordão azul, ligando-o ao cinturão, para que o peitoral não se separe do colete sacerdotal.

[[v2-28-29]]

^<<v2-28-29,29>>^ "Toda vez que Arão entrar no Lugar Santo, levará os nomes dos filhos de Israel sobre o seu coração no peitoral de decisões, como memorial permanente perante o Senhor.

[[v2-28-30]]

^<<v2-28-30,30>>^ Ponha também o Urim e o Tumim no peitoral das decisões, para que estejam sobre o coração de Arão sempre que ele entrar na presença do Senhor. Assim, Arão levará sempre sobre o coração, na presença do Senhor, os meios para tomar decisões em Israel. "

[[v2-28-31]]

^<<v2-28-31,31>>^ "Faça o manto do colete sacerdotal inteiramente de fios de tecido azul,

[[v2-28-32]]

^<<v2-28-32,32>>^ com uma abertura para a cabeça no centro. Ao redor dessa abertura haverá uma dobra tecida, como uma gola, para que não se rasgue.

[[v2-28-33]]

^<<v2-28-33,33>>^ Faça romãs de fios de tecido azul, roxo e vermelho em volta da borda do manto, intercaladas com pequenos sinos de ouro.

[[v2-28-34]]

^<<v2-28-34,34>>^ Os sinos de ouro e as romãs se alternarão por toda a volta da borda do manto.

[[v2-28-35]]

^<<v2-28-35,35>>^ Arão o vestirá quando ministrar. O som dos sinos será ouvido quando ele entrar no Lugar Santo diante do Senhor e quando sair, para que não morra.

[[v2-28-36]]

^<<v2-28-36,36>>^ "Faça um diadema de ouro puro e grave nele como se grava um selo: Consagrado ao Senhor.

[[v2-28-37]]

^<<v2-28-37,37>>^ Prenda-o na parte da frente do turbante com uma fita azul.

[[v2-28-38]]

^<<v2-28-38,38>>^ Estará sobre a testa de Arão; assim ele levará a culpa de qualquer pecado que os israelitas cometerem em relação às coisas sagradas, ao fazerem todas as suas ofertas. Estará sempre sobre a testa de Arão, para que as ofertas sejam aceitas pelo Senhor.

[[v2-28-39]]

^<<v2-28-39,39>>^ "Teça a túnica e o turbante com linho fino. O cinturão será feito por um bordador.

[[v2-28-40]]

^<<v2-28-40,40>>^ Faça também túnicas, cinturões e gorros para os filhos de Arão, para conferir-lhes honra e dignidade.

[[v2-28-41]]

^<<v2-28-41,41>>^ Depois de vestir seu irmão Arão e os filhos dele, unja-os e consagre-os, para que me sirvam como sacerdotes.

[[v2-28-42]]

^<<v2-28-42,42>>^ "Faça-lhes calções de linho que vão da cintura até a coxa, para cobrirem a sua nudez.

[[v2-28-43]]

^<<v2-28-43,43>>^ Arão e seus filhos terão que vesti-los sempre que entrarem na Tenda do Encontro ou quando se aproximarem do altar para ministrar no Lugar Santo, para que não incorram em culpa e morram. "Este é um decreto perpétuo para Arão e para os seus descendentes. "

'''

xref:002-exodo/002-exodo-027.adoc#v2-27-0[&#60; Capítulo Anterior] | <<v2-28-0,Topo>> | xref:002-exodo/002-exodo-029.adoc#v2-29-0[Próximo Capítulo &#62;]