include::./index.adoc[]

[[v2-10-0]]
=== Êxodo, 10
// nvi ?, NVI - Nova Versão Internacional

[[v2-10-1]]

^<<v2-10-1,1>>^ O Senhor disse a Moisés: "Vá ao faraó, pois tornei obstinado o coração dele e o de seus conselheiros, a fim de realizar estes meus prodígios entre eles,

[[v2-10-2]]

^<<v2-10-2,2>>^ para que você possa contar a seus filhos e netos como zombei dos egípcios e como realizei meus milagres entre eles. Assim vocês saberão que eu sou o Senhor".

[[v2-10-3]]

^<<v2-10-3,3>>^ Dirigiram-se, pois, Moisés e Arão ao faraó e lhe disseram: "Assim diz o Senhor, o Deus dos hebreus: ‘Até quando você se recusará a humilhar-se perante mim? Deixe ir o meu povo, para que me preste culto.

[[v2-10-4]]

^<<v2-10-4,4>>^ Se você não quiser deixá-lo ir, farei vir gafanhotos sobre o seu território amanhã.

[[v2-10-5]]

^<<v2-10-5,5>>^ Eles cobrirão a face da terra até não se poder enxergar o solo. Devorarão tanto o pouco que ainda lhes restou da tempestade de granizo como todas as árvores que estiverem brotando nos campos.

[[v2-10-6]]

^<<v2-10-6,6>>^ Encherão os seus palácios e as casas de todos os seus conselheiros e de todos os egípcios: algo que nem os seus pais nem os seus antepassados jamais viram, desde o dia em que se fixaram nesta terra até o dia de hoje’ ". A seguir Moisés virou as costas e saiu da presença do faraó.

[[v2-10-7]]

^<<v2-10-7,7>>^ Os conselheiros do faraó lhe disseram: "Até quando este homem será uma ameaça para nós? Deixa os homens irem prestar culto ao Senhor Deus deles. Não percebes que o Egito está arruinado? "

[[v2-10-8]]

^<<v2-10-8,8>>^ Então Moisés e Arão foram trazidos de volta à presença do faraó, que lhes disse: "Vão e prestem culto ao Senhor, ao seu Deus. Mas, digam-me, quem irá? "

[[v2-10-9]]

^<<v2-10-9,9>>^ Moisés respondeu: "Temos que levar todos: os jovens e os velhos, os nossos filhos e as nossas filhas, as nossas ovelhas e os nossos bois, pois celebraremos uma festa ao Senhor".

[[v2-10-10]]

^<<v2-10-10,10>>^ Disse-lhes o faraó: "Vocês vão mesmo precisar do Senhor quando eu deixá-los ir com as mulheres e crianças! É claro que vocês estão com más intenções.

[[v2-10-11]]

^<<v2-10-11,11>>^ De forma alguma! Só os homens podem ir prestar culto ao Senhor, como vocês têm pedido". E Moisés e Arão foram expulsos da presença do faraó.

[[v2-10-12]]

^<<v2-10-12,12>>^ Mas o Senhor disse a Moisés: "Estenda a mão sobre o Egito para que os gafanhotos venham sobre a terra e devorem toda a vegetação, tudo o que foi deixado pelo granizo".

[[v2-10-13]]

^<<v2-10-13,13>>^ Moisés estendeu a vara sobre o Egito, e o Senhor fez soprar sobre a terra um vento oriental durante todo aquele dia e toda aquela noite. Pela manhã, o vento havia trazido os gafanhotos,

[[v2-10-14]]

^<<v2-10-14,14>>^ os quais invadiram todo o Egito e desceram em grande número sobre toda a sua extensão. Nunca antes houve tantos gafanhotos, nem jamais haverá.

[[v2-10-15]]

^<<v2-10-15,15>>^ Eles cobriram toda a face da terra de tal forma que essa escureceu. Devoraram tudo o que o granizo tinha deixado: toda a vegetação e todos os frutos das árvores. Não restou nada verde nas árvores nem nas plantas do campo, em toda a terra do Egito.

[[v2-10-16]]

^<<v2-10-16,16>>^ O faraó mandou chamar Moisés e Arão imediatamente e disse-lhes: "Pequei contra o Senhor seu Deus e contra vocês!

[[v2-10-17]]

^<<v2-10-17,17>>^ Agora perdoem ainda esta vez o meu pecado e orem ao Senhor seu Deus para que leve esta praga mortal para longe de mim".

[[v2-10-18]]

^<<v2-10-18,18>>^ Moisés saiu da presença do faraó e orou ao Senhor.

[[v2-10-19]]

^<<v2-10-19,19>>^ E o Senhor fez soprar com muito mais força o vento ocidental, e este envolveu os gafanhotos e os lançou no mar Vermelho. Não restou um gafanhoto sequer em toda a extensão do Egito.

[[v2-10-20]]

^<<v2-10-20,20>>^ Mas o Senhor endureceu o coração do faraó, e ele não deixou que os israelitas saíssem.

[[v2-10-21]]

^<<v2-10-21,21>>^ O Senhor disse a Moisés: "Estenda a mão para o céu, e trevas cobrirão o Egito, trevas tais que poderão ser apalpadas".

[[v2-10-22]]

^<<v2-10-22,22>>^ Moisés estendeu a mão para o céu, e por três dias houve densas trevas em todo o Egito.

[[v2-10-23]]

^<<v2-10-23,23>>^ Ninguém pôde ver ninguém, nem sair do seu lugar durante três dias. Todavia, todos os israelitas tinham luz nos locais em que habitavam.

[[v2-10-24]]

^<<v2-10-24,24>>^ Então o faraó mandou chamar Moisés e disse: "Vão e prestem culto ao Senhor. Deixem somente as ovelhas e os bois; as mulheres e as crianças podem ir".

[[v2-10-25]]

^<<v2-10-25,25>>^ Mas Moisés contestou: "Tu mesmo nos darás os animais para os nossos sacrifícios e holocaustos que ofereceremos ao Senhor.

[[v2-10-26]]

^<<v2-10-26,26>>^ Além disso, os nossos rebanhos também irão conosco; nem um casco de animal será deixado. Temos que escolher alguns deles para prestar culto ao Senhor nosso Deus e, enquanto não chegarmos ao local, não saberemos quais animais sacrificaremos".

[[v2-10-27]]

^<<v2-10-27,27>>^ Mas o Senhor endureceu o coração do faraó, e ele se recusou a deixá-los ir.

[[v2-10-28]]

^<<v2-10-28,28>>^ Disse o faraó a Moisés: "Saia da minha presença! Trate de não aparecer nunca mais diante de mim! No dia em que vir a minha face, você morrerá".

[[v2-10-29]]

^<<v2-10-29,29>>^ Respondeu Moisés: "Será como disseste; nunca mais verei a tua face".

'''

xref:002-exodo/002-exodo-009.adoc#v2-9-0[&#60; Capítulo Anterior] | <<v2-10-0,Topo>> | xref:002-exodo/002-exodo-011.adoc#v2-11-0[Próximo Capítulo &#62;]