include::./index.adoc[]

[[v2-16-0]]
=== Êxodo, 16
// nvi ?, NVI - Nova Versão Internacional

[[v2-16-1]]

^<<v2-16-1,1>>^ Toda a comunidade de Israel partiu de Elim e chegou ao deserto de Sim, que fica entre Elim e o Sinai. Foi no décimo quinto dia do segundo mês, depois que saíram do Egito.

[[v2-16-2]]

^<<v2-16-2,2>>^ No deserto, toda a comunidade de Israel reclamou a Moisés e Arão.

[[v2-16-3]]

^<<v2-16-3,3>>^ Disseram-lhes os israelitas: "Quem dera a mão do Senhor nos tivesse matado no Egito! Lá nos sentávamos ao redor das panelas de carne e comíamos pão à vontade, mas vocês nos trouxeram a este deserto para fazer morrer de fome toda esta multidão! "

[[v2-16-4]]

^<<v2-16-4,4>>^ Disse, porém, o Senhor a Moisés: "Eu lhes farei chover pão do céu. O povo sairá e recolherá diariamente a porção necessária para aquele dia. Com isso os porei à prova para ver se seguem ou não as minhas instruções.

[[v2-16-5]]

^<<v2-16-5,5>>^ No sexto dia trarão para ser preparado o dobro do que recolhem nos outros dias".

[[v2-16-6]]

^<<v2-16-6,6>>^ Assim Moisés e Arão disseram a todos os israelitas: "Ao entardecer, vocês saberão que foi o Senhor quem os tirou do Egito,

[[v2-16-7]]

^<<v2-16-7,7>>^ e amanhã cedo verão a glória do Senhor, porque o Senhor ouviu a queixa de vocês contra ele. Quem somos nós para que vocês reclamem a nós? "

[[v2-16-8]]

^<<v2-16-8,8>>^ Disse ainda Moisés: "O Senhor lhes dará carne para comer ao entardecer e pão à vontade pela manhã, porque ele ouviu as suas queixas contra ele. Quem somos nós? Vocês não estão reclamando de nós, mas do Senhor".

[[v2-16-9]]

^<<v2-16-9,9>>^ Disse Moisés a Arão: "Diga a toda a comunidade de Israel que se apresente ao Senhor, pois ele ouviu as suas queixas".

[[v2-16-10]]

^<<v2-16-10,10>>^ Enquanto Arão falava a toda a comunidade, todos olharam em direção ao deserto, e a glória do Senhor apareceu na nuvem.

[[v2-16-11]]

^<<v2-16-11,11>>^ E o Senhor disse a Moisés:

[[v2-16-12]]

^<<v2-16-12,12>>^ "Ouvi as queixas dos israelitas. Responda-lhes que ao pôr-do-sol vocês comerão carne, e ao amanhecer se fartarão de pão. Assim saberão que eu sou o Senhor seu Deus".

[[v2-16-13]]

^<<v2-16-13,13>>^ No final da tarde, apareceram codornizes que cobriram o lugar onde estavam acampados; ao amanhecer havia uma camada de orvalho ao redor do acampamento.

[[v2-16-14]]

^<<v2-16-14,14>>^ Depois que o orvalho secou, flocos finos semelhantes a geada estavam sobre a superfície do deserto.

[[v2-16-15]]

^<<v2-16-15,15>>^ Quando os israelitas viram aquilo, começaram a perguntar uns aos outros: "Que é isso? ", pois não sabiam do que se tratava. Disse-lhes Moisés: "Este é o pão que o Senhor lhes deu para comer.

[[v2-16-16]]

^<<v2-16-16,16>>^ Assim ordenou o Senhor: ‘Cada chefe de família recolha o quanto precisar: um jarro para cada pessoa da sua tenda’ ".

[[v2-16-17]]

^<<v2-16-17,17>>^ Os israelitas fizeram como lhes fora dito; alguns recolheram mais, outros menos.

[[v2-16-18]]

^<<v2-16-18,18>>^ Quando mediram com o jarro, quem tinha recolhido muito não teve demais, e não faltou a quem tinha recolhido pouco. Cada um recolheu tanto quanto precisava.

[[v2-16-19]]

^<<v2-16-19,19>>^ "Ninguém deve guardar nada para a manhã seguinte", ordenou-lhes Moisés.

[[v2-16-20]]

^<<v2-16-20,20>>^ Todavia, alguns deles não deram atenção a Moisés e guardaram um pouco até a manhã seguinte, mas aquilo criou bicho e começou a cheirar mal. Por isso Moisés irou-se contra eles.

[[v2-16-21]]

^<<v2-16-21,21>>^ Cada manhã todos recolhiam o quanto precisavam, pois quando o sol esquentava, aquilo se derretia.

[[v2-16-22]]

^<<v2-16-22,22>>^ No sexto dia recolheram o dobro: dois jarros para cada pessoa; e os líderes da comunidade foram contar isso a Moisés,

[[v2-16-23]]

^<<v2-16-23,23>>^ que lhes explicou: "Foi isto que o Senhor ordenou: ‘Amanhã será dia de descanso, sábado consagrado ao Senhor. Assem e cozinhem o que quiserem. Guardem o que sobrar até a manhã seguinte’ ".

[[v2-16-24]]

^<<v2-16-24,24>>^ E eles o guardaram até a manhã seguinte, como Moisés tinha ordenado, e não cheirou mal nem criou bicho.

[[v2-16-25]]

^<<v2-16-25,25>>^ "Comam-no hoje", disse Moisés, "pois hoje é o sábado do Senhor. Hoje, vocês não o encontrarão no terreno.

[[v2-16-26]]

^<<v2-16-26,26>>^ Durante seis dias vocês podem recolhê-lo, mas, no sétimo dia, o sábado, nada acharão. "

[[v2-16-27]]

^<<v2-16-27,27>>^ Apesar disso, alguns deles saíram no sétimo dia para recolhê-lo, mas não encontraram nada.

[[v2-16-28]]

^<<v2-16-28,28>>^ Então o Senhor disse a Moisés: "Até quando vocês se recusarão a obedecer aos meus mandamentos e às minhas instruções?

[[v2-16-29]]

^<<v2-16-29,29>>^ Vejam que o Senhor lhes deu o sábado; e por isso, no sexto dia, ele lhes dá pão para dois dias. No sétimo dia, fiquem todos onde estiverem; ninguém deve sair".

[[v2-16-30]]

^<<v2-16-30,30>>^ Então o povo descansou no sétimo dia.

[[v2-16-31]]

^<<v2-16-31,31>>^ O povo de Israel chamou maná àquele pão. Era branco como semente de coentro e tinha gosto de bolo de mel.

[[v2-16-32]]

^<<v2-16-32,32>>^ Disse Moisés: "O Senhor ordenou-lhes que recolham um jarro de maná e guardem-no para as futuras gerações, para que vejam o pão que lhes dei no deserto, quando os tirei do Egito".

[[v2-16-33]]

^<<v2-16-33,33>>^ Então Moisés disse a Arão: "Ponha numa vasilha a medida de um jarro de maná, e coloque-a diante do Senhor, para que seja conservado para as futuras gerações".

[[v2-16-34]]

^<<v2-16-34,34>>^ Em obediência ao que o Senhor tinha ordenado a Moisés, Arão colocou o maná junto às tábuas da aliança, para ali ser guardado.

[[v2-16-35]]

^<<v2-16-35,35>>^ Os israelitas comeram maná durante quarenta anos, até chegarem a uma terra habitável; comeram maná até chegarem às fronteiras de Canaã.

[[v2-16-36]]

^<<v2-16-36,36>>^ ( O jarro é a décima parte de uma arroba. )

'''

xref:002-exodo/002-exodo-015.adoc#v2-15-0[&#60; Capítulo Anterior] | <<v2-16-0,Topo>> | xref:002-exodo/002-exodo-017.adoc#v2-17-0[Próximo Capítulo &#62;]