include::./index.adoc[]

[[v2-34-0]]
=== Êxodo, 34
// nvi ?, NVI - Nova Versão Internacional

[[v2-34-1]]

^<<v2-34-1,1>>^ Disse o Senhor a Moisés: "Talhe duas tábuas de pedra semelhantes às primeiras, e nelas escreverei as palavras que estavam nas primeiras tábuas que você quebrou.

[[v2-34-2]]

^<<v2-34-2,2>>^ Esteja pronto pela manhã para subir ao monte Sinai. E lá mesmo, no alto do monte, apresente-se a mim.

[[v2-34-3]]

^<<v2-34-3,3>>^ Ninguém poderá ir com você nem ficar em lugar algum do monte; nem mesmo ovelhas e bois deverão pastar diante do monte".

[[v2-34-4]]

^<<v2-34-4,4>>^ Assim Moisés lavrou duas tábuas de pedra semelhantes às primeiras e subiu ao monte Sinai, logo de manhã, como o Senhor lhe havia ordenado, levando nas mãos as duas tábuas de pedra.

[[v2-34-5]]

^<<v2-34-5,5>>^ Então o Senhor desceu na nuvem, permaneceu ali com ele e proclamou o seu nome: o Senhor.

[[v2-34-6]]

^<<v2-34-6,6>>^ E passou diante de Moisés, proclamando: "Senhor, Senhor, Deus compassivo e misericordioso, paciente, cheio de amor e de fidelidade,

[[v2-34-7]]

^<<v2-34-7,7>>^ que mantém o seu amor a milhares e perdoa a maldade, a rebelião e o pecado. Contudo, não deixa de punir o culpado; castiga os filhos e os netos pelo pecado de seus pais, até a terceira e a quarta gerações".

[[v2-34-8]]

^<<v2-34-8,8>>^ Imediatamente Moisés prostrou-se, rosto em terra, e o adorou, dizendo:

[[v2-34-9]]

^<<v2-34-9,9>>^ "Senhor, se de fato me aceitas com agrado, acompanha-nos o Senhor. Mesmo sendo esse um povo obstinado, perdoa a nossa maldade e o nosso pecado e faze de nós a tua herança".

[[v2-34-10]]

^<<v2-34-10,10>>^ "Faço com vocês uma aliança", disse o Senhor. "Diante de todo o seu povo farei maravilhas jamais realizadas na presença de nenhum outro povo do mundo. O povo no meio do qual você habita verá a obra maravilhosa que eu, o Senhor, farei.

[[v2-34-11]]

^<<v2-34-11,11>>^ Obedeça às ordens que hoje lhe dou. Expulsarei de diante de você os amorreus, os cananeus, os hititas, os ferezeus, os heveus e os jebuseus.

[[v2-34-12]]

^<<v2-34-12,12>>^ Acautele-se para não fazer acordo com aqueles que vivem na terra para a qual você está indo, pois eles se tornariam uma armadilha.

[[v2-34-13]]

^<<v2-34-13,13>>^ Pelo contrário, derrube os altares deles, quebre as suas colunas sagradas e corte os seus postes sagrados.

[[v2-34-14]]

^<<v2-34-14,14>>^ Nunca adore nenhum outro deus, porque o Senhor, cujo nome é Zeloso, é de fato Deus zeloso.

[[v2-34-15]]

^<<v2-34-15,15>>^ "Acautele-se para não fazer acordo com aqueles que já vivem na terra; pois quando eles se prostituírem, seguindo aos seus deuses e lhes oferecerem sacrifícios, convidarão você e poderão levá-lo a comer dos seus sacrifícios

[[v2-34-16]]

^<<v2-34-16,16>>^ e escolher para os seus filhos mulheres dentre as filhas deles. Quando elas se prostituírem, seguindo aos seus deuses, poderão levar os seus filhos a se prostituírem também.

[[v2-34-17]]

^<<v2-34-17,17>>^ "Não faça ídolos de metal para você.

[[v2-34-18]]

^<<v2-34-18,18>>^ "Celebre a festa dos pães sem fermento. Durante sete dias coma pão sem fermento, como lhe ordenei. Faça isso no tempo certo, no mês de abibe, porquanto naquele mês você saiu do Egito.

[[v2-34-19]]

^<<v2-34-19,19>>^ "O primeiro a nascer de cada ventre me pertence, todos os machos dentre as primeiras crias dos seus rebanhos: bezerros, cordeiros e cabritos.

[[v2-34-20]]

^<<v2-34-20,20>>^ Resgate com um cordeiro cada primeiro jumentinho que nascer; mas se não o resgatar, quebre-lhe o pescoço. Resgate todos os seus primogênitos. "Ninguém compareça perante mim de mãos vazias.

[[v2-34-21]]

^<<v2-34-21,21>>^ "Trabalhe seis dias, mas descanse no sétimo; tanto na época de arar como na da colheita.

[[v2-34-22]]

^<<v2-34-22,22>>^ "Celebre a festa das semanas, na ocasião dos primeiros frutos da colheita do trigo, e a festa do encerramento da colheita, no fim do ano.

[[v2-34-23]]

^<<v2-34-23,23>>^ Três vezes por ano todos os homens do seu povo comparecerão diante do Soberano Senhor, o Deus de Israel.

[[v2-34-24]]

^<<v2-34-24,24>>^ Expulsarei nações de diante de você e ampliarei o seu território. Quando você subir três vezes por ano para apresentar-se ao Senhor, o seu Deus, ninguém cobiçará a sua terra.

[[v2-34-25]]

^<<v2-34-25,25>>^ "Não me ofereça o sangue de nenhum sacrifício misturado com algo fermentado, e não deixe sobra alguma do sacrifício da festa da Páscoa até a manhã seguinte.

[[v2-34-26]]

^<<v2-34-26,26>>^ "Traga o melhor dos primeiros frutos da terra ao santuário do Senhor, o seu Deus. "Não cozinhe o cabrito no leite da própria mãe. "

[[v2-34-27]]

^<<v2-34-27,27>>^ Disse o Senhor a Moisés: "Escreva essas palavras; porque é de acordo com elas que faço aliança com você e com Israel".

[[v2-34-28]]

^<<v2-34-28,28>>^ Moisés ficou ali com o Senhor quarenta dias e quarenta noites, sem comer pão e sem beber água. E escreveu nas tábuas as palavras da aliança: os Dez Mandamentos.

[[v2-34-29]]

^<<v2-34-29,29>>^ Ao descer do monte Sinai com as duas tábuas da aliança nas mãos, Moisés não sabia que o seu rosto resplandecia por ter conversado com o Senhor.

[[v2-34-30]]

^<<v2-34-30,30>>^ Quando Arão e todos os israelitas viram Moisés, com o rosto resplandecente, tiveram medo de aproximar-se dele.

[[v2-34-31]]

^<<v2-34-31,31>>^ Ele, porém, os chamou; Arão e os líderes da comunidade atenderam, e Moisés falou com eles.

[[v2-34-32]]

^<<v2-34-32,32>>^ Depois, todos os israelitas se aproximaram, e ele lhes transmitiu todos os mandamentos que o Senhor lhe tinha dado no monte Sinai.

[[v2-34-33]]

^<<v2-34-33,33>>^ Quando acabou de falar com eles, cobriu o rosto com um véu.

[[v2-34-34]]

^<<v2-34-34,34>>^ Mas toda vez que entrava para estar na presença do Senhor e falar com ele, tirava o véu até sair. Sempre que saía e contava aos israelitas tudo o que lhe havia sido ordenado,

[[v2-34-35]]

^<<v2-34-35,35>>^ eles viam que o seu rosto resplandecia. Então, de novo Moisés cobria o rosto com o véu até entrar de novo para falar com o Senhor.

'''

xref:002-exodo/002-exodo-033.adoc#v2-33-0[&#60; Capítulo Anterior] | <<v2-34-0,Topo>> | xref:002-exodo/002-exodo-035.adoc#v2-35-0[Próximo Capítulo &#62;]