include::./index.adoc[]

[[v2-29-0]]
=== Êxodo, 29
// nvi ?, NVI - Nova Versão Internacional

[[v2-29-1]]

^<<v2-29-1,1>>^ "Assim você os consagrará, para que me sirvam como sacerdotes: separe um novilho e dois cordeiros sem defeito.

[[v2-29-2]]

^<<v2-29-2,2>>^ Com a melhor farinha de trigo, sem fermento, faça pães e bolos amassados com azeite, e pães finos, untados com azeite.

[[v2-29-3]]

^<<v2-29-3,3>>^ Coloque-os numa cesta e ofereça-os dentro dela; também ofereça o novilho e os dois cordeiros.

[[v2-29-4]]

^<<v2-29-4,4>>^ Depois traga Arão e seus filhos à entrada da Tenda do Encontro e mande-os se lavar.

[[v2-29-5]]

^<<v2-29-5,5>>^ Pegue as vestes e vista Arão com a túnica e o peitoral. Prenda o colete sacerdotal sobre ele com o cinturão.

[[v2-29-6]]

^<<v2-29-6,6>>^ Ponha-lhe o turbante na cabeça e prenda a coroa sagrada ao turbante.

[[v2-29-7]]

^<<v2-29-7,7>>^ Unja-o com o óleo da unção, derramando-o sobre a cabeça de Arão.

[[v2-29-8]]

^<<v2-29-8,8>>^ Traga os filhos dele, vista a cada um com uma túnica

[[v2-29-9]]

^<<v2-29-9,9>>^ e um gorro na cabeça. Ponha também os cinturões em Arão e em seus filhos. O sacerdócio lhes pertence como ordenança perpétua. Assim você dedicará Arão e seus filhos.

[[v2-29-10]]

^<<v2-29-10,10>>^ "Traga o novilho para a frente da Tenda do Encontro. Arão e seus filhos colocarão as mãos sobre a cabeça do novilho,

[[v2-29-11]]

^<<v2-29-11,11>>^ e você o sacrificará na presença do Senhor, defronte da Tenda do Encontro.

[[v2-29-12]]

^<<v2-29-12,12>>^ Com o dedo, coloque um pouco do sangue do novilho nas pontas do altar e derrame o resto do sangue na base do altar.

[[v2-29-13]]

^<<v2-29-13,13>>^ Depois tire toda a gordura que cobre as vísceras, o lóbulo do fígado, e os dois rins com a gordura que os envolve, e queime-os no altar.

[[v2-29-14]]

^<<v2-29-14,14>>^ Mas queime a carne, o couro e o excremento do novilho fora do acampamento; é oferta pelo pecado.

[[v2-29-15]]

^<<v2-29-15,15>>^ "Separe um dos cordeiros sobre cuja cabeça Arão e seus filhos terão que colocar as mãos.

[[v2-29-16]]

^<<v2-29-16,16>>^ Sacrifique-o, pegue o sangue e jogue-o nos lados do altar.

[[v2-29-17]]

^<<v2-29-17,17>>^ Corte o cordeiro em pedaços, lave as vísceras e as pernas e coloque-as ao lado da cabeça e das outras partes.

[[v2-29-18]]

^<<v2-29-18,18>>^ Depois queime o cordeiro inteiro sobre o altar; é holocausto dedicado ao Senhor; é oferta de aroma agradável dedicada ao Senhor, preparada no fogo.

[[v2-29-19]]

^<<v2-29-19,19>>^ "Pegue depois o outro cordeiro. Arão e seus filhos colocarão as mãos sobre a cabeça do animal,

[[v2-29-20]]

^<<v2-29-20,20>>^ e você o sacrificará. Pegue do sangue e coloque-o na ponta da orelha direita de Arão e dos seus filhos, no polegar da mão direita e do pé direito de cada um deles. Depois derrame o resto do sangue nos lados do altar.

[[v2-29-21]]

^<<v2-29-21,21>>^ Pegue, então, um pouco do sangue do altar e um pouco do óleo da unção, e faça aspersão com eles sobre Arão e suas vestes, sobre seus filhos e as vestes deles. Assim serão consagrados, ele e suas vestes, seus filhos e as vestes deles.

[[v2-29-22]]

^<<v2-29-22,22>>^ "Tire desse cordeiro a gordura, a parte gorda da cauda, a gordura que cobre as vísceras, o lóbulo do fígado, os dois rins e a gordura que os envolve, e a coxa direita. Este é o cordeiro da oferta de ordenação.

[[v2-29-23]]

^<<v2-29-23,23>>^ Tire da cesta de pães sem fermento um pão, um bolo assado com azeite e um pão fino.

[[v2-29-24]]

^<<v2-29-24,24>>^ Coloque tudo nas mãos de Arão e de seus filhos, e apresente-os como oferta ritualmente movida perante o Senhor.

[[v2-29-25]]

^<<v2-29-25,25>>^ Em seguida retome-o das mãos deles e queime os pães no altar com o holocausto de aroma agradável ao Senhor; é oferta dedicada ao Senhor, preparada no fogo.

[[v2-29-26]]

^<<v2-29-26,26>>^ Tire o peito do cordeiro para a ordenação de Arão e mova-o perante o Senhor, como gesto ritual de apresentação; essa parte pertencerá a você.

[[v2-29-27]]

^<<v2-29-27,27>>^ "Consagre aquelas partes do cordeiro da ordenação que pertencem a Arão e a seus filhos: o peito e a coxa movidos como oferta.

[[v2-29-28]]

^<<v2-29-28,28>>^ Essas partes sempre serão dadas pelos israelitas a Arão e a seus filhos. É a contribuição obrigatória que lhes farão, das suas ofertas de comunhão ao Senhor.

[[v2-29-29]]

^<<v2-29-29,29>>^ "As vestes sagradas de Arão passarão aos seus descendentes, que, com elas serão ungidos e consagrados.

[[v2-29-30]]

^<<v2-29-30,30>>^ O filho que o suceder como sacerdote e vier à Tenda do Encontro para ministrar no Lugar Santo terá que usá-las durante sete dias.

[[v2-29-31]]

^<<v2-29-31,31>>^ "Pegue o cordeiro da ordenação e cozinhe a sua carne num lugar sagrado.

[[v2-29-32]]

^<<v2-29-32,32>>^ À entrada da Tenda do Encontro, Arão e seus filhos deverão comer a carne do cordeiro e o pão que está na cesta.

[[v2-29-33]]

^<<v2-29-33,33>>^ Eles comerão dessas ofertas com as quais se fez propiciação para sua ordenação e consagração; somente os sacerdotes poderão comê-las, pois são sagradas.

[[v2-29-34]]

^<<v2-29-34,34>>^ Se sobrar da carne do cordeiro da ordenação ou do pão até a manhã seguinte, queime a sobra. Não se deve comê-la, visto que é sagrada.

[[v2-29-35]]

^<<v2-29-35,35>>^ "Para a ordenação de Arão e seus filhos, faça durante sete dias tudo o que lhe mandei.

[[v2-29-36]]

^<<v2-29-36,36>>^ Sacrifique um novilho por dia como oferta pelo pecado para fazer propiciação. Purifique o altar, fazendo propiciação por ele, e unja-o para consagrá-lo.

[[v2-29-37]]

^<<v2-29-37,37>>^ Durante sete dias faça propiciação pelo altar, consagrando-o. Então o altar será santíssimo, e tudo o que nele tocar será santo.

[[v2-29-38]]

^<<v2-29-38,38>>^ "Eis o que você terá que sacrificar regularmente sobre o altar: a cada dia dois cordeiros de um ano.

[[v2-29-39]]

^<<v2-29-39,39>>^ Ofereça um de manhã e o outro ao entardecer.

[[v2-29-40]]

^<<v2-29-40,40>>^ Com o primeiro cordeiro ofereça um jarro da melhor farinha misturada com um litro de azeite de olivas moídas, e um litro de vinho como oferta derramada.

[[v2-29-41]]

^<<v2-29-41,41>>^ Ofereça o outro cordeiro ao entardecer com uma oferta de cereal e uma oferta derramada, como de manhã. É oferta de aroma agradável ao Senhor, preparada no fogo.

[[v2-29-42]]

^<<v2-29-42,42>>^ "De geração em geração esse holocausto deverá ser feito regularmente à entrada da Tenda do Encontro, diante do Senhor. Nesse local eu os encontrarei e falarei com você;

[[v2-29-43]]

^<<v2-29-43,43>>^ ali me encontrarei com os israelitas, e o lugar será consagrado pela minha glória.

[[v2-29-44]]

^<<v2-29-44,44>>^ "Assim consagrarei a Tenda do Encontro e o altar, e consagrarei também Arão e seus filhos para me servirem como sacerdotes.

[[v2-29-45]]

^<<v2-29-45,45>>^ E habitarei no meio dos israelitas e lhes serei o seu Deus.

[[v2-29-46]]

^<<v2-29-46,46>>^ Saberão que eu sou o Senhor, o seu Deus, que os tirou do Egito para habitar no meio deles. Eu sou o Senhor, o seu Deus. "

'''

xref:002-exodo/002-exodo-028.adoc#v2-28-0[&#60; Capítulo Anterior] | <<v2-29-0,Topo>> | xref:002-exodo/002-exodo-030.adoc#v2-30-0[Próximo Capítulo &#62;]