include::./index.adoc[]

[[v2-9-0]]
=== Êxodo, 9
// nvi ?, NVI - Nova Versão Internacional

[[v2-9-1]]

^<<v2-9-1,1>>^ Depois o Senhor disse a Moisés: "Vá ao faraó e diga-lhe que assim diz o Senhor, o Deus dos hebreus: Deixe o meu povo ir para que me preste culto.

[[v2-9-2]]

^<<v2-9-2,2>>^ Se você ainda não quiser deixá-lo ir e continuar a impedi-lo,

[[v2-9-3]]

^<<v2-9-3,3>>^ saiba que a mão do Senhor trará uma praga terrível sobre os rebanhos do faraó que estão nos campos: os cavalos, os jumentos, os camelos, os bois e as ovelhas.

[[v2-9-4]]

^<<v2-9-4,4>>^ Mas o Senhor fará distinção entre os rebanhos de Israel e os do Egito. Nenhum animal dos israelitas morrerá".

[[v2-9-5]]

^<<v2-9-5,5>>^ O Senhor estabeleceu um prazo: "Amanhã o Senhor fará o que prometeu nesta terra".

[[v2-9-6]]

^<<v2-9-6,6>>^ No dia seguinte o Senhor o fez. Todos os rebanhos dos egípcios morreram, mas nenhum rebanho dos israelitas morreu.

[[v2-9-7]]

^<<v2-9-7,7>>^ O faraó mandou verificar e constatou que nenhum animal dos israelitas havia morrido. Mesmo assim, seu coração continuou obstinado e não deixou o povo ir.

[[v2-9-8]]

^<<v2-9-8,8>>^ Disse mais o Senhor a Moisés e a Arão: "Tirem um punhado de cinza de uma fornalha, e Moisés a espalhará no ar, diante do faraó.

[[v2-9-9]]

^<<v2-9-9,9>>^ Ela se tornará como um pó fino sobre toda a terra do Egito, e feridas purulentas surgirão nos homens e nos animais em todo o Egito".

[[v2-9-10]]

^<<v2-9-10,10>>^ Eles tiraram cinza duma fornalha e se puseram diante do faraó. Moisés a espalhou pelo ar, e feridas purulentas começaram a estourar nos homens e nos animais.

[[v2-9-11]]

^<<v2-9-11,11>>^ Nem os magos podiam manter-se diante de Moisés, porque ficaram cobertos de feridas, como os demais egípcios.

[[v2-9-12]]

^<<v2-9-12,12>>^ Mas o Senhor endureceu o coração do faraó, e ele se recusou a atender Moisés e Arão, conforme o Senhor tinha dito a Moisés.

[[v2-9-13]]

^<<v2-9-13,13>>^ Disse o Senhor a Moisés: "Levante-se logo cedo, apresente-se ao faraó e diga-lhe que assim diz o Senhor, o Deus dos hebreus: Deixe o meu povo ir para que me preste culto.

[[v2-9-14]]

^<<v2-9-14,14>>^ Caso contrário, mandarei desta vez todas as minhas pragas contra você, contra os seus conselheiros e contra o seu povo, para que você saiba que em toda a terra não há ninguém como eu.

[[v2-9-15]]

^<<v2-9-15,15>>^ Porque eu já poderia ter estendido a mão, ferindo você e o seu povo com uma praga que teria eliminado você da terra.

[[v2-9-16]]

^<<v2-9-16,16>>^ Mas eu o mantive de pé exatamente com este propósito: mostrar-lhe o meu poder e fazer que o meu nome seja proclamado em toda a terra.

[[v2-9-17]]

^<<v2-9-17,17>>^ Contudo você ainda insiste em colocar-se contra o meu povo e não o deixa ir.

[[v2-9-18]]

^<<v2-9-18,18>>^ Amanhã, a esta hora, enviarei a pior tempestade de granizo que já caiu sobre o Egito, desde o dia da sua fundação até hoje.

[[v2-9-19]]

^<<v2-9-19,19>>^ Agora, mande recolher os seus rebanhos e tudo o que você tem nos campos. Todos os homens e animais que estiverem nos campos, que não tiverem sido abrigados, serão atingidos pelo granizo e morrerão".

[[v2-9-20]]

^<<v2-9-20,20>>^ Os conselheiros do faraó que temiam a palavra do Senhor apressaram-se em recolher aos abrigos os seus rebanhos e os seus escravos.

[[v2-9-21]]

^<<v2-9-21,21>>^ Mas os que não se importaram com a palavra do Senhor deixaram os seus escravos e os seus rebanhos no campo.

[[v2-9-22]]

^<<v2-9-22,22>>^ Então o Senhor disse a Moisés: "Estenda a mão para o céu, e cairá granizo sobre toda a terra do Egito: sobre homens, sobre animais e sobre toda a vegetação do Egito".

[[v2-9-23]]

^<<v2-9-23,23>>^ Quando Moisés estendeu a vara para o céu, o Senhor fez vir trovões e granizo, e raios caíam sobre a terra. Assim o Senhor fez chover granizo sobre a terra do Egito.

[[v2-9-24]]

^<<v2-9-24,24>>^ Caiu granizo, e raios cortavam o céu em todas as direções. Nunca houve uma tempestade de granizo como aquela em todo o Egito, desde que este se tornou uma nação.

[[v2-9-25]]

^<<v2-9-25,25>>^ Em todo o Egito o granizo atingiu tudo o que havia nos campos, tanto homens como animais; destruiu toda a vegetação, além de quebrar todas as árvores.

[[v2-9-26]]

^<<v2-9-26,26>>^ Somente na terra de Gósen, onde estavam os israelitas, não caiu granizo.

[[v2-9-27]]

^<<v2-9-27,27>>^ Então o faraó mandou chamar Moisés e Arão e disse-lhes: "Desta vez eu pequei. O Senhor é justo; eu e o meu povo é que somos culpados.

[[v2-9-28]]

^<<v2-9-28,28>>^ Orem ao Senhor! Os trovões de Deus e o granizo já são demais. Eu os deixarei ir; não precisam mais ficar aqui".

[[v2-9-29]]

^<<v2-9-29,29>>^ Moisés respondeu: "Assim que eu tiver saído da cidade, erguerei as mãos em oração ao Senhor. Os trovões cessarão e não cairá mais granizo, para que saibas que a terra pertence ao Senhor.

[[v2-9-30]]

^<<v2-9-30,30>>^ Mas eu bem sei que tu e os teus conselheiros ainda não sabem o que é tremer diante do Senhor Deus! "

[[v2-9-31]]

^<<v2-9-31,31>>^ ( O linho e a cevada foram destruídos, pois a cevada já havia amadurecido e o linho estava em flor.

[[v2-9-32]]

^<<v2-9-32,32>>^ Todavia, o trigo e o centeio nada sofreram, pois só amadurecem mais tarde. )

[[v2-9-33]]

^<<v2-9-33,33>>^ Assim Moisés deixou o faraó, saiu da cidade, e ergueu as mãos ao Senhor. Os trovões e o granizo cessaram, e a chuva parou.

[[v2-9-34]]

^<<v2-9-34,34>>^ Quando o faraó viu que a chuva, o granizo e os trovões haviam cessado, pecou novamente e obstinou-se em seu coração, ele e os seus conselheiros.

[[v2-9-35]]

^<<v2-9-35,35>>^ O coração do faraó continuou endurecido, e ele não deixou que os israelitas saíssem, como o Senhor tinha dito por meio de Moisés.

'''

xref:002-exodo/002-exodo-008.adoc#v2-8-0[&#60; Capítulo Anterior] | <<v2-9-0,Topo>> | xref:002-exodo/002-exodo-010.adoc#v2-10-0[Próximo Capítulo &#62;]