include::./index.adoc[]

[[v2-5-0]]
=== Êxodo, 5
// nvi ?, NVI - Nova Versão Internacional

[[v2-5-1]]

^<<v2-5-1,1>>^ Depois disso Moisés e Arão foram falar com o faraó e disseram: "Assim diz o Senhor, o Deus de Israel: ‘Deixe o meu povo ir para celebrar-me uma festa no deserto’ ".

[[v2-5-2]]

^<<v2-5-2,2>>^ O faraó respondeu: "Quem é o Senhor, para que eu lhe obedeça e deixe Israel sair? Não conheço o Senhor, e não deixarei Israel sair".

[[v2-5-3]]

^<<v2-5-3,3>>^ Eles insistiram: "O Deus dos hebreus veio ao nosso encontro. Agora, permite-nos caminhar três dias no deserto, para oferecer sacrifícios ao Senhor, o nosso Deus; caso contrário, ele nos atingirá com pragas ou com a espada".

[[v2-5-4]]

^<<v2-5-4,4>>^ Mas o rei do Egito respondeu: "Moisés e Arão, por que vocês estão fazendo o povo interromper suas tarefas? Voltem ao trabalho! "

[[v2-5-5]]

^<<v2-5-5,5>>^ E acrescentou: "Essa gente já é tão numerosa, e vocês ainda os fazem parar de trabalhar! "

[[v2-5-6]]

^<<v2-5-6,6>>^ No mesmo dia o faraó deu a seguinte ordem aos feitores e capatazes responsáveis pelo povo:

[[v2-5-7]]

^<<v2-5-7,7>>^ "Não forneçam mais palha ao povo para fazer tijolos, como faziam antes. Eles que tratem de ajuntar palha!

[[v2-5-8]]

^<<v2-5-8,8>>^ Mas exijam que continuem a fazer a mesma quantidade de tijolos; não reduzam a cota. São preguiçosos, e por isso estão clamando: ‘Iremos oferecer sacrifícios ao nosso Deus’.

[[v2-5-9]]

^<<v2-5-9,9>>^ Aumentem a carga de trabalho dessa gente para que cumpram suas tarefas e não dêem atenção a mentiras".

[[v2-5-10]]

^<<v2-5-10,10>>^ Os feitores e os capatazes foram dizer ao povo: "Assim diz o faraó: ‘Já não lhes darei palha.

[[v2-5-11]]

^<<v2-5-11,11>>^ Saiam e recolham-na onde puderem achá-la, pois o trabalho de vocês em nada será reduzido’ ".

[[v2-5-12]]

^<<v2-5-12,12>>^ O povo então espalhou-se por todo o Egito, a fim de ajuntar restolho em lugar da palha.

[[v2-5-13]]

^<<v2-5-13,13>>^ Enquanto isso, os feitores os pressionavam, dizendo: "Completem a mesma tarefa diária que lhes foi exigida quando tinham palha".

[[v2-5-14]]

^<<v2-5-14,14>>^ Os capatazes israelitas indicados pelos feitores do faraó eram espancados e interrogados: "Por que não completaram ontem e hoje a mesma cota de tijolos dos dias anteriores? "

[[v2-5-15]]

^<<v2-5-15,15>>^ Então os capatazes israelitas foram apelar para o faraó: "Por que tratas os teus servos dessa maneira?

[[v2-5-16]]

^<<v2-5-16,16>>^ Não se fornece a nós, teus servos, a palha, e contudo nos dizem: ‘Façam tijolos! ’ Os teus servos têm sido espancados, mas a culpa é do teu próprio povo".

[[v2-5-17]]

^<<v2-5-17,17>>^ Respondeu o faraó: "Preguiçosos, é o que vocês são! Preguiçosos! Por isso andam dizendo: ‘Iremos oferecer sacrifícios ao Senhor’.

[[v2-5-18]]

^<<v2-5-18,18>>^ Agora, voltem ao trabalho. Vocês não receberão palha alguma! Continuem a produzir a cota integral de tijolos! "

[[v2-5-19]]

^<<v2-5-19,19>>^ Os capatazes israelitas se viram em dificuldade quando lhes disseram que não poderiam reduzir a quantidade de tijolos exigida a cada dia.

[[v2-5-20]]

^<<v2-5-20,20>>^ Ao saírem da presença do faraó, encontraram-se com Moisés e Arão, que estavam à espera deles,

[[v2-5-21]]

^<<v2-5-21,21>>^ e lhes disseram: "O Senhor os examine e os julgue! Vocês atraíram o ódio do faraó e dos seus conselheiros sobre nós, e lhes puseram nas mãos uma espada para que nos matem".

[[v2-5-22]]

^<<v2-5-22,22>>^ Moisés voltou-se para o Senhor e perguntou: "Senhor, por que maltrataste a este povo? Afinal, por que me enviaste?

[[v2-5-23]]

^<<v2-5-23,23>>^ Desde que me dirigi ao faraó para falar em teu nome, ele tem maltratado a este povo, e tu de modo algum libertaste o teu povo! "

'''

xref:002-exodo/002-exodo-004.adoc#v2-4-0[&#60; Capítulo Anterior] | <<v2-5-0,Topo>> | xref:002-exodo/002-exodo-006.adoc#v2-6-0[Próximo Capítulo &#62;]