include::./index.adoc[]

[[v2-8-0]]
=== Êxodo, 8
// nvi ?, NVI - Nova Versão Internacional

[[v2-8-1]]

^<<v2-8-1,1>>^ O Senhor falou a Moisés: "Vá ao faraó e diga-lhe que assim diz o Senhor: Deixe o meu povo ir para que me preste culto.

[[v2-8-2]]

^<<v2-8-2,2>>^ Se você não quiser deixá-lo ir, mandarei sobre todo o seu território uma praga de rãs.

[[v2-8-3]]

^<<v2-8-3,3>>^ O Nilo ficará infestado de rãs. Elas subirão e entrarão em seu palácio, em seu quarto, e até em sua cama; estarão também nas casas dos seus conselheiros e do seu povo, dentro dos seus fornos e nas suas amassadeiras.

[[v2-8-4]]

^<<v2-8-4,4>>^ As rãs subirão em você, em seus conselheiros e em seu povo".

[[v2-8-5]]

^<<v2-8-5,5>>^ Depois o Senhor disse a Moisés: "Diga a Arão que estenda a mão com a vara sobre os rios, sobre os canais e sobre os açudes, e faça subir deles rãs sobre a terra do Egito".

[[v2-8-6]]

^<<v2-8-6,6>>^ Assim Arão estendeu a mão sobre as águas do Egito, e as rãs subiram e cobriram a terra do Egito.

[[v2-8-7]]

^<<v2-8-7,7>>^ Mas os magos fizeram a mesma coisa por meio das suas ciências ocultas: fizeram subir rãs sobre a terra do Egito.

[[v2-8-8]]

^<<v2-8-8,8>>^ O faraó mandou chamar Moisés e Arão e disse: "Orem ao Senhor para que ele tire estas rãs de mim e do meu povo; então deixarei o povo ir e oferecer sacrifícios ao Senhor".

[[v2-8-9]]

^<<v2-8-9,9>>^ Moisés disse ao faraó: "Tua é a honra de dizer-me quando devo orar por ti, por teus conselheiros e por teu povo para que tu e tuas casas fiquem livres das rãs e sobrem apenas as que estão no rio".

[[v2-8-10]]

^<<v2-8-10,10>>^ "Amanhã", disse o faraó. Moisés respondeu: "Será como tu dizes, para que saibas que não há ninguém como o Senhor nosso Deus.

[[v2-8-11]]

^<<v2-8-11,11>>^ As rãs deixarão a ti, às tuas casas, a teus conselheiros e a teu povo; sobrarão apenas as que estão no rio".

[[v2-8-12]]

^<<v2-8-12,12>>^ Depois que Moisés e Arão saíram da presença do faraó, Moisés clamou ao Senhor por causa das rãs que enviara sobre o faraó.

[[v2-8-13]]

^<<v2-8-13,13>>^ E o Senhor atendeu o pedido de Moisés; morreram as rãs que estavam nas casas, nos pátios e nos campos.

[[v2-8-14]]

^<<v2-8-14,14>>^ Foram ajuntadas em montões e, por isso, a terra cheirou mal.

[[v2-8-15]]

^<<v2-8-15,15>>^ Mas quando o faraó percebeu que houve alívio, obstinou-se em seu coração e não deu mais ouvidos a Moisés e a Arão, conforme o Senhor tinha dito.

[[v2-8-16]]

^<<v2-8-16,16>>^ Então o Senhor disse a Moisés: "Diga a Arão que estenda a sua vara e fira o pó da terra, e o pó se transformará em piolhos por toda a terra do Egito".

[[v2-8-17]]

^<<v2-8-17,17>>^ Assim fizeram, e quando Arão estendeu a mão e com a vara feriu o pó da terra, surgiram piolhos nos homens e nos animais. Todo o pó de toda a terra do Egito transformou-se em piolhos.

[[v2-8-18]]

^<<v2-8-18,18>>^ Mas, quando os magos tentaram fazer surgir piolhos por meio das suas ciências ocultas, não conseguiram. E os piolhos infestavam os homens e os animais.

[[v2-8-19]]

^<<v2-8-19,19>>^ Os magos disseram ao faraó: "Isso é o dedo de Deus". Mas o coração do faraó permaneceu endurecido, e ele não quis ouvi-los, conforme o Senhor tinha dito.

[[v2-8-20]]

^<<v2-8-20,20>>^ Depois o Senhor disse a Moisés: "Levante-se bem cedo e apresente-se ao faraó, quando ele estiver indo às águas. Diga-lhe que assim diz o Senhor: Deixe o meu povo ir para que me preste culto.

[[v2-8-21]]

^<<v2-8-21,21>>^ Se você não deixar meu povo ir, enviarei enxames de moscas para atacar você, os seus conselheiros, o seu povo e as suas casas. As casas dos egípcios, bem como o chão em que pisam, se encherão de moscas.

[[v2-8-22]]

^<<v2-8-22,22>>^ "Mas naquele dia tratarei de maneira diferente a terra de Gósen, onde habita o meu povo; nenhum enxame de moscas se achará ali, para que você saiba que eu, o Senhor, estou nesta terra.

[[v2-8-23]]

^<<v2-8-23,23>>^ Farei distinção entre o meu povo e o seu. Este sinal miraculoso acontecerá amanhã".

[[v2-8-24]]

^<<v2-8-24,24>>^ E assim fez o Senhor. Grandes enxames de moscas invadiram o palácio do faraó e as casas de seus conselheiros, e em todo o Egito a terra foi arruinada pelas moscas.

[[v2-8-25]]

^<<v2-8-25,25>>^ Então o faraó mandou chamar Moisés e Arão e disse: "Vão oferecer sacrifícios ao seu Deus, mas não saiam do país".

[[v2-8-26]]

^<<v2-8-26,26>>^ "Isso não seria sensato", respondeu Moisés; "os sacrifícios que oferecemos ao nosso Deus são um sacrilégio para os egípcios. Se oferecermos sacrifícios que lhes pareçam sacrilégio, isso não os levará a nos apedrejar?

[[v2-8-27]]

^<<v2-8-27,27>>^ Faremos três dias de viagem no deserto, e ofereceremos sacrifícios ao Senhor nosso Deus, como ele nos ordena. "

[[v2-8-28]]

^<<v2-8-28,28>>^ Disse o faraó: "Eu os deixarei ir e oferecer sacrifícios ao Senhor seu Deus no deserto, mas não se afastem muito e orem por mim também".

[[v2-8-29]]

^<<v2-8-29,29>>^ Moisés respondeu: "Assim que sair da tua presença, orarei ao Senhor, e amanhã os enxames de moscas deixarão o faraó, teus conselheiros e teu povo. Que somente o faraó não volte a agir com falsidade, impedindo que o povo vá oferecer sacrifícios ao Senhor".

[[v2-8-30]]

^<<v2-8-30,30>>^ Então Moisés saiu da presença do faraó e orou ao Senhor,

[[v2-8-31]]

^<<v2-8-31,31>>^ e o Senhor atendeu o seu pedido: as moscas deixaram o faraó, seus conselheiros e seu povo; não restou uma só mosca.

[[v2-8-32]]

^<<v2-8-32,32>>^ Mas também dessa vez o faraó obstinou-se em seu coração e não deixou que o povo saísse.

'''

xref:002-exodo/002-exodo-007.adoc#v2-7-0[&#60; Capítulo Anterior] | <<v2-8-0,Topo>> | xref:002-exodo/002-exodo-009.adoc#v2-9-0[Próximo Capítulo &#62;]