include::./index.adoc[]

[[v2-18-0]]
=== Êxodo, 18
// nvi ?, NVI - Nova Versão Internacional

[[v2-18-1]]

^<<v2-18-1,1>>^ Jetro, sacerdote de Midiã e sogro de Moisés, soube de tudo o que Deus tinha feito por Moisés e pelo povo de Israel, como o Senhor havia tirado Israel do Egito.

[[v2-18-2]]

^<<v2-18-2,2>>^ Moisés tinha mandado Zípora, sua mulher, para a casa de seu sogro Jetro, que a recebeu

[[v2-18-3]]

^<<v2-18-3,3>>^ juntamente com os seus dois filhos. Um deles chamava-se Gérson, pois Moisés dissera: "Tornei-me imigrante em terra estrangeira";

[[v2-18-4]]

^<<v2-18-4,4>>^ e o outro chamava-se Eliézer, pois dissera: "O Deus de meu pai foi o meu ajudador; livrou-me da espada do faraó".

[[v2-18-5]]

^<<v2-18-5,5>>^ Jetro, sogro de Moisés, veio com os filhos e a mulher de Moisés encontrá-lo no deserto, onde estava acampado, perto do monte de Deus.

[[v2-18-6]]

^<<v2-18-6,6>>^ E Jetro mandou dizer-lhe: "Eu, seu sogro Jetro, estou indo encontrá-lo, e comigo vão sua mulher e seus dois filhos".

[[v2-18-7]]

^<<v2-18-7,7>>^ Então Moisés saiu ao encontro do sogro, curvou-se e beijou-o; trocaram saudações e depois entraram na tenda.

[[v2-18-8]]

^<<v2-18-8,8>>^ Então Moisés contou ao sogro tudo quanto o Senhor tinha feito ao faraó e aos egípcios por amor a Israel e também todas as dificuldades que tinham enfrentado pelo caminho e como o Senhor os livrara.

[[v2-18-9]]

^<<v2-18-9,9>>^ Jetro alegrou-se ao ouvir todas as coisas boas que o Senhor tinha feito a Israel, libertando-o das mãos dos egípcios.

[[v2-18-10]]

^<<v2-18-10,10>>^ Disse ele: "Bendito seja o Senhor que os libertou das mãos dos egípcios e do faraó; que livrou o povo das mãos dos egípcios!

[[v2-18-11]]

^<<v2-18-11,11>>^ Agora sei que o Senhor é maior do que todos os outros deuses, pois ele os superou exatamente naquilo de que se vangloriavam".

[[v2-18-12]]

^<<v2-18-12,12>>^ Então Jetro, sogro de Moisés, ofereceu um holocausto e sacrifícios a Deus, e Arão veio com todas as autoridades de Israel para comerem com o sogro de Moisés na presença de Deus.

[[v2-18-13]]

^<<v2-18-13,13>>^ No dia seguinte Moisés assentou-se para julgar as questões do povo, e este permaneceu de pé diante dele, desde a manhã até o cair da tarde.

[[v2-18-14]]

^<<v2-18-14,14>>^ Quando o seu sogro viu tudo o que ele estava fazendo pelo povo, disse: "Que é que você está fazendo? Por que só você se assenta para julgar, e todo este povo o espera de pé, desde a manhã até o cair da tarde? "

[[v2-18-15]]

^<<v2-18-15,15>>^ Moisés lhe respondeu: "O povo me procura para que eu consulte a Deus.

[[v2-18-16]]

^<<v2-18-16,16>>^ Toda vez que alguém tem uma questão, esta me é trazida, e eu decido entre as partes, e ensino-lhes os decretos e leis de Deus".

[[v2-18-17]]

^<<v2-18-17,17>>^ Respondeu o sogro de Moisés: "O que você está fazendo não é bom.

[[v2-18-18]]

^<<v2-18-18,18>>^ Você e o seu povo ficarão esgotados, pois esta tarefa lhe é pesada demais. Você não pode executá-la sozinho.

[[v2-18-19]]

^<<v2-18-19,19>>^ Agora, ouça-me! Eu lhe darei um conselho, e que Deus esteja com você! Seja você o representante do povo diante de Deus e leve a Deus as suas questões.

[[v2-18-20]]

^<<v2-18-20,20>>^ Oriente-os quanto aos decretos e leis, mostrando-lhes como devem viver e o que devem fazer.

[[v2-18-21]]

^<<v2-18-21,21>>^ Mas escolha dentre todo o povo homens capazes, tementes a Deus, dignos de confiança e inimigos de ganho desonesto. Estabeleça-os como chefes de mil, de cem, de cinqüenta e de dez.

[[v2-18-22]]

^<<v2-18-22,22>>^ Eles estarão sempre à disposição do povo para julgar as questões. Trarão a você apenas as questões difíceis; as mais simples decidirão sozinhos. Isso tornará mais leve o seu fardo, porque eles o dividirão com você.

[[v2-18-23]]

^<<v2-18-23,23>>^ Se você assim fizer, e se assim Deus ordenar, você será capaz de suportar as dificuldades, e todo este povo voltará para casa satisfeito".

[[v2-18-24]]

^<<v2-18-24,24>>^ Moisés aceitou o conselho do sogro e fez tudo como ele tinha sugerido.

[[v2-18-25]]

^<<v2-18-25,25>>^ Escolheu homens capazes de todo o Israel e colocou-os como líderes do povo: chefes de mil, de cem, de cinqüenta e de dez.

[[v2-18-26]]

^<<v2-18-26,26>>^ Estes ficaram como juízes permanentes do povo. As questões difíceis levavam a Moisés; as mais simples, porém, eles mesmos resolviam.

[[v2-18-27]]

^<<v2-18-27,27>>^ Então Moisés e seu sogro se despediram, e este voltou para a sua terra.

'''

xref:002-exodo/002-exodo-017.adoc#v2-17-0[&#60; Capítulo Anterior] | <<v2-18-0,Topo>> | xref:002-exodo/002-exodo-019.adoc#v2-19-0[Próximo Capítulo &#62;]