include::./index.adoc[]

[[v2-21-0]]
=== Êxodo, 21
// nvi ?, NVI - Nova Versão Internacional

[[v2-21-1]]

^<<v2-21-1,1>>^ "São estas as leis que você proclamará ao povo:

[[v2-21-2]]

^<<v2-21-2,2>>^ "Se você comprar um escravo hebreu, ele o servirá por seis anos. Mas no sétimo ano será liberto, sem precisar pagar nada.

[[v2-21-3]]

^<<v2-21-3,3>>^ Se chegou solteiro, solteiro receberá liberdade; mas se chegou casado, sua mulher irá com ele.

[[v2-21-4]]

^<<v2-21-4,4>>^ Se o seu senhor lhe tiver dado uma mulher, e esta lhe tiver dado filhos ou filhas, a mulher e os filhos pertencerão ao senhor; somente o homem sairá livre.

[[v2-21-5]]

^<<v2-21-5,5>>^ "Se, porém, o escravo declarar: ‘Eu amo o meu senhor, a minha mulher e os meus filhos, e não quero sair livre’,

[[v2-21-6]]

^<<v2-21-6,6>>^ o seu senhor o levará perante os juízes. Terá que levá-lo à porta ou à lateral da porta e furar a sua orelha. Assim, ele será seu escravo por toda a vida.

[[v2-21-7]]

^<<v2-21-7,7>>^ "Se um homem vender sua filha como escrava, ela não será liberta como os escravos homens.

[[v2-21-8]]

^<<v2-21-8,8>>^ Se ela não agradar ao seu senhor que a escolheu, ele deverá permitir que ela seja resgatada. Não poderá vendê-la a estrangeiros, pois isso seria deslealdade para com ela.

[[v2-21-9]]

^<<v2-21-9,9>>^ Se o seu senhor a escolher para seu filho, lhe dará os direitos de uma filha.

[[v2-21-10]]

^<<v2-21-10,10>>^ Se o senhor tomar uma segunda mulher, não poderá privar a primeira de alimento, de roupas e dos direitos conjugais.

[[v2-21-11]]

^<<v2-21-11,11>>^ Se não lhe garantir essas três coisas, ela poderá ir embora sem precisar pagar nada.

[[v2-21-12]]

^<<v2-21-12,12>>^ "Quem ferir um homem, vindo a matá-lo, terá que ser executado.

[[v2-21-13]]

^<<v2-21-13,13>>^ Todavia, se não o fez intencionalmente, mas Deus o permitiu, designei um lugar para onde poderá fugir.

[[v2-21-14]]

^<<v2-21-14,14>>^ Mas se alguém tiver planejado matar outro deliberadamente, tire-o até mesmo do meu altar e mate-o.

[[v2-21-15]]

^<<v2-21-15,15>>^ "Quem agredir o próprio pai ou a própria mãe terá que ser executado.

[[v2-21-16]]

^<<v2-21-16,16>>^ "Aquele que seqüestrar alguém e vendê-lo ou for apanhado com ele em seu poder, terá que ser executado.

[[v2-21-17]]

^<<v2-21-17,17>>^ "Quem amaldiçoar seu pai ou sua mãe terá que ser executado.

[[v2-21-18]]

^<<v2-21-18,18>>^ "Se dois homens brigarem e um deles ferir o outro com uma pedra ou com o punho e o outro não morrer, mas cair de cama,

[[v2-21-19]]

^<<v2-21-19,19>>^ aquele que o feriu será absolvido, se o outro se levantar e caminhar com o auxílio de uma bengala; todavia ele terá que indenizar o homem ferido pelo tempo que este perdeu e responsabilizar-se por sua completa recuperação.

[[v2-21-20]]

^<<v2-21-20,20>>^ "Se alguém ferir seu escravo ou escrava com um pedaço de pau, e como resultado o escravo morrer, será punido;

[[v2-21-21]]

^<<v2-21-21,21>>^ mas se o escravo sobreviver um ou dois dias, não será punido, visto que é sua propriedade.

[[v2-21-22]]

^<<v2-21-22,22>>^ "Se homens brigarem e ferirem uma mulher grávida, e ela der à luz prematuramente, não havendo, porém, nenhum dano sério, o ofensor pagará a indenização que o marido daquela mulher exigir, conforme a determinação dos juízes.

[[v2-21-23]]

^<<v2-21-23,23>>^ Mas, se houver danos graves, a pena será vida por vida,

[[v2-21-24]]

^<<v2-21-24,24>>^ olho por olho, dente por dente, mão por mão, pé por pé,

[[v2-21-25]]

^<<v2-21-25,25>>^ queimadura por queimadura, ferida por ferida, contusão por contusão.

[[v2-21-26]]

^<<v2-21-26,26>>^ "Se alguém ferir o seu escravo ou sua escrava no olho e o cegar, terá que libertar o escravo como compensação pelo olho.

[[v2-21-27]]

^<<v2-21-27,27>>^ Se quebrar um dente de um escravo ou de uma escrava, terá que libertar o escravo como compensação pelo dente.

[[v2-21-28]]

^<<v2-21-28,28>>^ "Se um boi chifrar um homem ou uma mulher, causando-lhe a morte, o boi terá que ser apedrejado até a morte, e a sua carne não poderá ser comida. Mas o dono do boi será absolvido.

[[v2-21-29]]

^<<v2-21-29,29>>^ Se, todavia, o boi costumava chifrar e o dono, ainda que alertado, não o manteve preso, e o boi matar um homem ou uma mulher, o boi será apedrejado e o dono também terá que ser morto.

[[v2-21-30]]

^<<v2-21-30,30>>^ Caso, porém, lhe pedirem um pagamento, poderá resgatar a sua vida pagando o que for exigido.

[[v2-21-31]]

^<<v2-21-31,31>>^ Esta sentença também se aplica no caso de um boi chifrar um menino ou uma menina.

[[v2-21-32]]

^<<v2-21-32,32>>^ Se o boi chifrar um escravo ou escrava, o dono do animal terá que pagar trezentos e sessenta gramas de prata ao dono do escravo, e o boi será apedrejado.

[[v2-21-33]]

^<<v2-21-33,33>>^ "Se alguém abrir ou deixar aberta uma cisterna, não tendo o cuidado de tampá-la, e um jumento ou um boi nela cair,

[[v2-21-34]]

^<<v2-21-34,34>>^ o dono da cisterna terá que pagar o prejuízo indenizando o dono do animal, e ficará com o animal morto.

[[v2-21-35]]

^<<v2-21-35,35>>^ "Se o boi de alguém ferir o boi de outro e o matar, venderão o boi vivo e o dividirão em partes iguais, tanto o valor como o animal morto.

[[v2-21-36]]

^<<v2-21-36,36>>^ Contudo, se o boi costumava chifrar, e o dono não o manteve preso, este terá que pagar boi por boi, e ficará com o que morreu. "

'''

xref:002-exodo/002-exodo-020.adoc#v2-20-0[&#60; Capítulo Anterior] | <<v2-21-0,Topo>> | xref:002-exodo/002-exodo-022.adoc#v2-22-0[Próximo Capítulo &#62;]