include::./index.adoc[]

[[v2-24-0]]
=== Êxodo, 24
// nvi ?, NVI - Nova Versão Internacional

[[v2-24-1]]

^<<v2-24-1,1>>^ Depois Deus disse a Moisés: "Subam o monte para encontrar-se com o Senhor, você e Arão, Nadabe e Abiú, e setenta autoridades de Israel. Adorem à distância.

[[v2-24-2]]

^<<v2-24-2,2>>^ Somente Moisés se aproximará do Senhor; os outros não. O povo também não subirá com ele".

[[v2-24-3]]

^<<v2-24-3,3>>^ Quando Moisés se dirigiu ao povo e transmitiu-lhes todas as palavras e ordenanças do Senhor, eles responderam em uníssono: "Faremos tudo o que o Senhor ordenou".

[[v2-24-4]]

^<<v2-24-4,4>>^ Moisés, então, escreveu tudo o que o Senhor dissera. Na manhã seguinte Moisés levantou-se, construiu um altar ao pé do monte e ergueu doze colunas de pedra, representando as doze tribos de Israel.

[[v2-24-5]]

^<<v2-24-5,5>>^ Em seguida enviou jovens israelitas, que ofereceram holocaustos e novilhos como sacrifícios de comunhão ao Senhor.

[[v2-24-6]]

^<<v2-24-6,6>>^ Moisés colocou metade do sangue em tigelas e a outra metade derramou sobre o altar.

[[v2-24-7]]

^<<v2-24-7,7>>^ Em seguida, leu o Livro da Aliança para o povo, e eles disseram: "Faremos fielmente tudo o que o Senhor ordenou".

[[v2-24-8]]

^<<v2-24-8,8>>^ Depois Moisés aspergiu o sangue sobre o povo, dizendo: "Este é o sangue da aliança que o Senhor fez com vocês de acordo com todas essas palavras".

[[v2-24-9]]

^<<v2-24-9,9>>^ Moisés, Arão, Nadabe, Abiú e setenta autoridades de Israel subiram

[[v2-24-10]]

^<<v2-24-10,10>>^ e viram o Deus de Israel, sob cujos pés havia algo semelhante a um pavimento de safira, como o céu em seu esplendor.

[[v2-24-11]]

^<<v2-24-11,11>>^ Deus, porém, não estendeu a mão para punir esses líderes do povo de Israel; eles viram a Deus, e depois comeram e beberam.

[[v2-24-12]]

^<<v2-24-12,12>>^ Disse o Senhor a Moisés: "Suba a mim, ao monte, e fique aqui; e lhe darei as tábuas de pedra com a lei e os mandamentos que escrevi para a instrução do povo".

[[v2-24-13]]

^<<v2-24-13,13>>^ Moisés partiu com Josué, seu auxiliar, e subiu ao monte de Deus.

[[v2-24-14]]

^<<v2-24-14,14>>^ Disse ele às autoridades de Israel: "Esperem-nos aqui, até que retornemos. Arão e Hur ficarão com vocês; quem tiver alguma questão para resolver, poderá procurá-los".

[[v2-24-15]]

^<<v2-24-15,15>>^ Quando Moisés subiu, a nuvem cobriu o monte,

[[v2-24-16]]

^<<v2-24-16,16>>^ e a glória do Senhor permaneceu sobre o monte Sinai. Durante seis dias a nuvem cobriu o monte. No sétimo dia o Senhor chamou Moisés do interior da nuvem.

[[v2-24-17]]

^<<v2-24-17,17>>^ Aos olhos dos israelitas a glória do Senhor parecia um fogo consumidor no topo do monte.

[[v2-24-18]]

^<<v2-24-18,18>>^ Moisés entrou na nuvem e foi subindo o monte. E permaneceu no monte quarenta dias e quarenta noites.

'''

xref:002-exodo/002-exodo-023.adoc#v2-23-0[&#60; Capítulo Anterior] | <<v2-24-0,Topo>> | xref:002-exodo/002-exodo-025.adoc#v2-25-0[Próximo Capítulo &#62;]