include::./index.adoc[]

[[v2-39-0]]
=== Êxodo, 39
// nvi ?, NVI - Nova Versão Internacional

[[v2-39-1]]

^<<v2-39-1,1>>^ Com fios de tecido azul, roxo e vermelho fizeram as vestes litúrgicas para ministrar no Lugar Santo. Também fizeram as vestes sagradas de Arão, como o Senhor tinha ordenado a Moisés.

[[v2-39-2]]

^<<v2-39-2,2>>^ Fez o colete sacerdotal de linho fino trançado e de fios de ouro e de fios de tecidos azul, roxo e vermelho.

[[v2-39-3]]

^<<v2-39-3,3>>^ E bateu o ouro em finas placas das quais cortaram fios de ouro para serem bordados no linho fino com os fios de tecido azul, roxo e vermelho, obra artesanal.

[[v2-39-4]]

^<<v2-39-4,4>>^ Fizeram as ombreiras para o colete sacerdotal, atadas às suas duas extremidades, para que pudessem ser amarradas.

[[v2-39-5]]

^<<v2-39-5,5>>^ O cinturão e o colete por ele preso foram feitos da mesma peça. O cinturão também foi feito de linho fino trançado e de fios de ouro e de fios de tecido azul, roxo e vermelho, como o Senhor tinha ordenado a Moisés.

[[v2-39-6]]

^<<v2-39-6,6>>^ Prenderam as pedras de ônix em filigranas de ouro e nelas gravaram os nomes dos filhos de Israel, como um lapidador grava um selo.

[[v2-39-7]]

^<<v2-39-7,7>>^ Então as costuraram nas ombreiras do colete sacerdotal, como pedras memoriais para os filhos de Israel, como o Senhor tinha ordenado a Moisés.

[[v2-39-8]]

^<<v2-39-8,8>>^ Fez o peitoral, trabalho artesanal, como o colete sacerdotal: de linho fino trançado, de fios de ouro e de fios de tecidos azul, roxo e vermelho.

[[v2-39-9]]

^<<v2-39-9,9>>^ Era quadrado, com um palmo de comprimento e um palmo de largura, e dobrado em dois.

[[v2-39-10]]

^<<v2-39-10,10>>^ Em seguida fixaram nele quatro fileiras de pedras preciosas. Na primeira fileira havia um rubi, um topázio e um berilo;

[[v2-39-11]]

^<<v2-39-11,11>>^ na segunda, uma turquesa, uma safira e um diamante;

[[v2-39-12]]

^<<v2-39-12,12>>^ na terceira, um jacinto, uma ágata e uma ametista;

[[v2-39-13]]

^<<v2-39-13,13>>^ na quarta, um crisólito, um ônix e um jaspe, todas fixadas em filigranas de ouro.

[[v2-39-14]]

^<<v2-39-14,14>>^ Havia doze pedras, uma para cada nome dos filhos de Israel, cada uma gravada como um lapidador grava um selo, com o nome de uma das doze tribos.

[[v2-39-15]]

^<<v2-39-15,15>>^ Para o peitoral fizeram correntes trançadas de ouro puro, como cordas.

[[v2-39-16]]

^<<v2-39-16,16>>^ De ouro fizeram duas filigranas e duas argolas, as quais prenderam às duas extremidades do peitoral.

[[v2-39-17]]

^<<v2-39-17,17>>^ Prenderam as duas correntes de ouro às duas argolas nas extremidades do peitoral,

[[v2-39-18]]

^<<v2-39-18,18>>^ e as outras extremidades das correntes, às duas filigranas, unindo-as às peças das ombreiras do colete sacerdotal, na parte da frente.

[[v2-39-19]]

^<<v2-39-19,19>>^ Fizeram outras duas argolas de ouro e as prenderam às duas extremidades do peitoral na borda interna, próxima ao colete sacerdotal.

[[v2-39-20]]

^<<v2-39-20,20>>^ Depois fizeram mais duas argolas de ouro e as prenderam na parte inferior das ombreiras, na frente do colete sacerdotal, próximas da costura, logo acima do cinturão do colete sacerdotal.

[[v2-39-21]]

^<<v2-39-21,21>>^ Amarraram as argolas do peitoral às argolas do colete com um cordão azul, ligando-o ao cinturão, para que o peitoral não se separasse do colete sacerdotal, como o Senhor tinha ordenado a Moisés.

[[v2-39-22]]

^<<v2-39-22,22>>^ Fizeram o manto do colete sacerdotal inteiramente de fios de tecido azul, obra de tecelão,

[[v2-39-23]]

^<<v2-39-23,23>>^ com uma abertura no centro. Ao redor dessa abertura havia uma dobra tecida, como uma gola, para que não se rasgasse.

[[v2-39-24]]

^<<v2-39-24,24>>^ Fizeram romãs de linho fino trançado e de fios de tecido azul, roxo e vermelho em volta da borda do manto.

[[v2-39-25]]

^<<v2-39-25,25>>^ Fizeram ainda pequenos sinos de ouro puro, atando-os em volta da borda, entre as romãs.

[[v2-39-26]]

^<<v2-39-26,26>>^ Os sinos e as romãs se alternavam por toda a borda do manto. Tudo feito para ser usado ao se ministrar, como o Senhor tinha ordenado a Moisés.

[[v2-39-27]]

^<<v2-39-27,27>>^ Para Arão e seus filhos fizeram de linho fino as túnicas, obra de tecelão,

[[v2-39-28]]

^<<v2-39-28,28>>^ o turbante, os gorros e os calções, de linho fino trançado.

[[v2-39-29]]

^<<v2-39-29,29>>^ O cinturão também era de linho fino trançado e de fios de tecido azul, roxo e vermelho, obra de bordador, como o Senhor tinha ordenado a Moisés.

[[v2-39-30]]

^<<v2-39-30,30>>^ Fizeram de ouro puro o diadema sagrado, e gravaram nele como se grava um selo: Consagrado ao Senhor.

[[v2-39-31]]

^<<v2-39-31,31>>^ Depois usaram um cordão azul para prendê-lo na parte de cima do turbante, como o Senhor tinha ordenado a Moisés.

[[v2-39-32]]

^<<v2-39-32,32>>^ Assim foi encerrada toda a obra do tabernáculo, a Tenda do Encontro. Os israelitas fizeram tudo conforme o Senhor tinha ordenado a Moisés.

[[v2-39-33]]

^<<v2-39-33,33>>^ Então trouxeram o tabernáculo a Moisés; a tenda e todos os seus utensílios, os ganchos, as molduras, os travessões, as colunas e as bases,

[[v2-39-34]]

^<<v2-39-34,34>>^ a cobertura de pele de carneiro tingida de vermelho, a cobertura de couro e o véu protetor,

[[v2-39-35]]

^<<v2-39-35,35>>^ a arca da aliança com as suas varas e a tampa,

[[v2-39-36]]

^<<v2-39-36,36>>^ a mesa com todos os seus utensílios e os pães da Presença,

[[v2-39-37]]

^<<v2-39-37,37>>^ o candelabro de ouro puro com a sua fileira de lâmpadas e todos os seus utensílios e o óleo para iluminação,

[[v2-39-38]]

^<<v2-39-38,38>>^ o altar de ouro, o óleo da unção, o incenso aromático e a cortina de entrada para a tenda,

[[v2-39-39]]

^<<v2-39-39,39>>^ o altar de bronze com a sua grelha, as suas varas e todos os seus utensílios, a bacia e a sua base,

[[v2-39-40]]

^<<v2-39-40,40>>^ as cortinas externas do pátio com as suas colunas e bases e a cortina para a entrada do pátio, as cordas e estacas da tenda do pátio, todos os utensílios para o tabernáculo, a Tenda do Encontro,

[[v2-39-41]]

^<<v2-39-41,41>>^ e as vestes litúrgicas para ministrar no Lugar Santo, tanto as vestes sagradas para Arão, o sacerdote, como as vestes de seus filhos, para quando servissem como sacerdotes.

[[v2-39-42]]

^<<v2-39-42,42>>^ Os israelitas fizeram todo o trabalho conforme o Senhor tinha ordenado a Moisés.

[[v2-39-43]]

^<<v2-39-43,43>>^ Moisés inspecionou a obra e viu que tinham feito tudo como o Senhor tinha ordenado. Então Moisés os abençoou.

'''

xref:002-exodo/002-exodo-038.adoc#v2-38-0[&#60; Capítulo Anterior] | <<v2-39-0,Topo>> | xref:002-exodo/002-exodo-040.adoc#v2-40-0[Próximo Capítulo &#62;]