include::./index.adoc[]

[[v2-2-0]]
=== Êxodo, 2
// nvi ?, NVI - Nova Versão Internacional

[[v2-2-1]]

^<<v2-2-1,1>>^ Um homem da tribo de Levi casou-se com uma mulher da mesma tribo,

[[v2-2-2]]

^<<v2-2-2,2>>^ e ela engravidou e deu à luz um filho. Vendo que era bonito, ela o escondeu por três meses.

[[v2-2-3]]

^<<v2-2-3,3>>^ Quando já não podia mais escondê-lo, pegou um cesto feito de junco e o vedou com piche e betume. Colocou nele o menino e deixou o cesto entre os juncos, à margem do Nilo.

[[v2-2-4]]

^<<v2-2-4,4>>^ A irmã do menino ficou observando de longe para ver o que lhe aconteceria.

[[v2-2-5]]

^<<v2-2-5,5>>^ A filha do faraó descera ao Nilo para tomar banho. Enquanto isso as suas servas andavam pela margem do rio. Nisso viu o cesto entre os juncos e mandou sua criada apanhá-lo.

[[v2-2-6]]

^<<v2-2-6,6>>^ Ao abri-lo viu um bebê chorando. Ficou com pena dele e disse: "Este menino é dos hebreus".

[[v2-2-7]]

^<<v2-2-7,7>>^ Então a irmã do menino aproximou-se e perguntou à filha do faraó: "A senhora quer que eu vá chamar uma mulher dos hebreus para amamentar e criar o menino? "

[[v2-2-8]]

^<<v2-2-8,8>>^ "Quero", respondeu ela. E a moça foi chamar a mãe do menino.

[[v2-2-9]]

^<<v2-2-9,9>>^ Então a filha do faraó disse à mulher: "Leve este menino e amamente-o para mim, e eu lhe pagarei por isso". A mulher levou o menino e o amamentou.

[[v2-2-10]]

^<<v2-2-10,10>>^ Tendo o menino crescido, ela o levou à filha do faraó, que o adotou e lhe deu o nome de Moisés, dizendo: "Porque eu o tirei das águas".

[[v2-2-11]]

^<<v2-2-11,11>>^ Certo dia, sendo Moisés já adulto, foi ao lugar onde estavam os seus irmãos hebreus e descobriu como era pesado o trabalho que realizavam. Viu também um egípcio espancar um dos hebreus.

[[v2-2-12]]

^<<v2-2-12,12>>^ Correu o olhar por todos os lados e, não vendo ninguém, matou o egípcio e o escondeu na areia.

[[v2-2-13]]

^<<v2-2-13,13>>^ No dia seguinte saiu e viu dois hebreus brigando. Então perguntou ao agressor: "Por que você está espancando o seu companheiro? "

[[v2-2-14]]

^<<v2-2-14,14>>^ O homem respondeu: "Quem o nomeou líder e juiz sobre nós? Quer matar-me como matou o egípcio? " Moisés teve medo e pensou: "Com certeza tudo já foi descoberto! "

[[v2-2-15]]

^<<v2-2-15,15>>^ Quando o faraó soube disso, procurou matar Moisés, mas este fugiu e foi morar na terra de Midiã. Ali assentou-se à beira de um poço.

[[v2-2-16]]

^<<v2-2-16,16>>^ Ora, o sacerdote de Midiã tinha sete filhas. Elas foram buscar água para encher os bebedouros e dar de beber ao rebanho de seu pai.

[[v2-2-17]]

^<<v2-2-17,17>>^ Alguns pastores se aproximaram e começaram a expulsá-las dali; Moisés, porém, veio em auxílio delas e deu água ao rebanho.

[[v2-2-18]]

^<<v2-2-18,18>>^ Quando as moças voltaram a seu pai Reuel, este lhes perguntou: "Por que voltaram tão cedo hoje? "

[[v2-2-19]]

^<<v2-2-19,19>>^ Elas responderam: "Um egípcio defendeu-nos dos pastores e ainda tirou água do poço para nós e deu de beber ao rebanho".

[[v2-2-20]]

^<<v2-2-20,20>>^ "Onde está ele? ", perguntou o pai a elas. "Por que o deixaram lá? Convidem-no para comer conosco. "

[[v2-2-21]]

^<<v2-2-21,21>>^ Moisés aceitou e concordou também em morar na casa daquele homem; este lhe deu por mulher sua filha Zípora.

[[v2-2-22]]

^<<v2-2-22,22>>^ Ela deu à luz um menino, a quem Moisés deu o nome de Gérson, dizendo: "Sou imigrante em terra estrangeira".

[[v2-2-23]]

^<<v2-2-23,23>>^ Muito tempo depois, morreu o rei do Egito. Os israelitas gemiam e clamavam debaixo da escravidão; e o seu clamor subiu até Deus.

[[v2-2-24]]

^<<v2-2-24,24>>^ Ouviu Deus o lamento deles e lembrou-se da aliança que fizera com Abraão, Isaque e Jacó.

[[v2-2-25]]

^<<v2-2-25,25>>^ Deus olhou para os israelitas e viu qual era a situação deles.

'''

xref:002-exodo/002-exodo-001.adoc#v2-1-0[&#60; Capítulo Anterior] | <<v2-2-0,Topo>> | xref:002-exodo/002-exodo-003.adoc#v2-3-0[Próximo Capítulo &#62;]