include::./index.adoc[]

[[v2-3-0]]
=== Êxodo, 3
// nvi ?, NVI - Nova Versão Internacional

[[v2-3-1]]

^<<v2-3-1,1>>^ Moisés pastoreava o rebanho de seu sogro Jetro, que era sacerdote de Midiã. Um dia levou o rebanho para o outro lado do deserto e chegou a Horebe, o monte de Deus.

[[v2-3-2]]

^<<v2-3-2,2>>^ Ali o Anjo do Senhor lhe apareceu numa chama de fogo que saía do meio de uma sarça. Moisés viu que, embora a sarça estivesse em chamas, esta não era consumida pelo fogo.

[[v2-3-3]]

^<<v2-3-3,3>>^ "Que impressionante! ", pensou. "Por que a sarça não se queima? Vou ver isso de perto. "

[[v2-3-4]]

^<<v2-3-4,4>>^ O Senhor viu que ele se aproximava para observar. E então, do meio da sarça Deus o chamou: "Moisés, Moisés! " "Eis-me aqui", respondeu ele.

[[v2-3-5]]

^<<v2-3-5,5>>^ Então disse Deus: "Não se aproxime. Tire as sandálias dos pés, pois o lugar em que você está é terra santa".

[[v2-3-6]]

^<<v2-3-6,6>>^ Disse ainda: "Eu sou o Deus de seu pai, o Deus de Abraão, o Deus de Isaque, o Deus de Jacó". Então Moisés cobriu o rosto, pois teve medo de olhar para Deus.

[[v2-3-7]]

^<<v2-3-7,7>>^ Disse o Senhor: "De fato tenho visto a opressão sobre o meu povo no Egito, e também tenho escutado o seu clamor, por causa dos seus feitores, e sei quanto eles estão sofrendo.

[[v2-3-8]]

^<<v2-3-8,8>>^ Por isso desci para livrá-lo das mãos dos egípcios e tirá-los daqui para uma terra boa e vasta, onde manam leite e mel: a terra dos cananeus, dos hititas, dos amorreus, dos ferezeus, dos heveus e dos jebuseus.

[[v2-3-9]]

^<<v2-3-9,9>>^ Pois agora o clamor dos israelitas chegou a mim, e tenho visto como os egípcios os oprimem.

[[v2-3-10]]

^<<v2-3-10,10>>^ Vá, pois, agora; eu o envio ao faraó para tirar do Egito o meu povo, os israelitas".

[[v2-3-11]]

^<<v2-3-11,11>>^ Moisés, porém, respondeu a Deus: "Quem sou eu para apresentar-me ao faraó e tirar os israelitas do Egito? "

[[v2-3-12]]

^<<v2-3-12,12>>^ Deus afirmou: "Eu estarei com você. Esta é a prova de que sou eu quem o envia: quando você tirar o povo do Egito, vocês prestarão culto a Deus neste monte".

[[v2-3-13]]

^<<v2-3-13,13>>^ Moisés perguntou: "Quando eu chegar diante dos israelitas e lhes disser: O Deus dos seus antepassados me enviou a vocês, e eles me perguntarem: ‘Qual é o nome dele? ’ Que lhes direi? "

[[v2-3-14]]

^<<v2-3-14,14>>^ Disse Deus a Moisés: "Eu Sou o que Sou. É isto que você dirá aos israelitas: Eu Sou me enviou a vocês".

[[v2-3-15]]

^<<v2-3-15,15>>^ Disse também Deus a Moisés: "Diga aos israelitas: O Senhor, o Deus dos seus antepassados, o Deus de Abraão, o Deus de Isaque, o Deus de Jacó, enviou-me a vocês. Esse é o meu nome para sempre, nome pelo qual serei lembrado de geração em geração.

[[v2-3-16]]

^<<v2-3-16,16>>^ "Vá, reúna as autoridades de Israel e diga-lhes: O Senhor, o Deus dos seus antepassados, o Deus de Abraão, de Isaque e de Jacó, apareceu a mim e disse: Eu virei em auxílio de vocês; pois vi o que lhes tem sido feito no Egito.

[[v2-3-17]]

^<<v2-3-17,17>>^ Prometi tirá-los da opressão do Egito para a terra dos cananeus, dos hititas, dos amorreus, dos ferezeus, dos heveus e dos jebuseus, terra onde manam leite e mel.

[[v2-3-18]]

^<<v2-3-18,18>>^ "As autoridades de Israel o atenderão. Depois você irá com elas ao rei do Egito e lhe dirá: O Senhor, o Deus dos hebreus, veio ao nosso encontro. Agora, deixe-nos fazer uma caminhada de três dias, adentrando o deserto, para oferecermos sacrifícios ao Senhor nosso Deus.

[[v2-3-19]]

^<<v2-3-19,19>>^ Eu sei que o rei do Egito não os deixará sair, a não ser que uma poderosa mão o force.

[[v2-3-20]]

^<<v2-3-20,20>>^ Por isso estenderei a minha mão e ferirei os egípcios com todas as maravilhas que realizarei no meio deles. Depois disso ele os deixará sair.

[[v2-3-21]]

^<<v2-3-21,21>>^ "E farei que os egípcios tenham boa-vontade para com o povo, de modo que, quando vocês saírem, não sairão de mãos vazias.

[[v2-3-22]]

^<<v2-3-22,22>>^ Todas as israelitas pedirão às suas vizinhas, e às mulheres que estiverem hospedando em casa, objetos de prata e de ouro, e roupas, que vocês porão em seus filhos e em suas filhas. Assim vocês despojarão os egípcios".

'''

xref:002-exodo/002-exodo-002.adoc#v2-2-0[&#60; Capítulo Anterior] | <<v2-3-0,Topo>> | xref:002-exodo/002-exodo-004.adoc#v2-4-0[Próximo Capítulo &#62;]