include::./index.adoc[]

[[v2-1-0]]
=== Êxodo, 1
// nvi ?, NVI - Nova Versão Internacional

[[v2-1-1]]

^<<v2-1-1,1>>^ São estes, pois, os nomes dos filhos de Israel que entraram com Jacó no Egito, cada um com a sua respectiva família:

[[v2-1-2]]

^<<v2-1-2,2>>^ Rúben, Simeão, Levi e Judá;

[[v2-1-3]]

^<<v2-1-3,3>>^ Issacar, Zebulom e Benjamim;

[[v2-1-4]]

^<<v2-1-4,4>>^ Dã, Naftali, Gade e Aser.

[[v2-1-5]]

^<<v2-1-5,5>>^ Ao todo, os descendentes de Jacó eram setenta; José, porém, já se encontrava no Egito.

[[v2-1-6]]

^<<v2-1-6,6>>^ Ora, morreram José, todos os seus irmãos e toda aquela geração.

[[v2-1-7]]

^<<v2-1-7,7>>^ Os israelitas, porém, eram férteis, proliferaram, tornaram-se numerosos e fortaleceram-se muito, tanto que encheram o país.

[[v2-1-8]]

^<<v2-1-8,8>>^ Então subiu ao trono do Egito um novo rei, que nada sabia sobre José.

[[v2-1-9]]

^<<v2-1-9,9>>^ Disse ele ao seu povo: "Vejam! O povo israelita é agora numeroso e mais forte que nós.

[[v2-1-10]]

^<<v2-1-10,10>>^ Temos de agir com astúcia, para que não se tornem ainda mais numerosos e, no caso de guerra, aliem-se aos nossos inimigos, lutem contra nós e fujam do país".

[[v2-1-11]]

^<<v2-1-11,11>>^ Estabeleceram, pois, sobre eles chefes de trabalhos forçados, para os oprimir com tarefas pesadas. E assim os israelitas construíram para o faraó as cidades-celeiros de Pitom e Ramessés.

[[v2-1-12]]

^<<v2-1-12,12>>^ Todavia, quanto mais eram oprimidos, mais numerosos se tornavam e mais se espalhavam. Por isso os egípcios passaram a temer os israelitas,

[[v2-1-13]]

^<<v2-1-13,13>>^ e os sujeitaram a cruel escravidão.

[[v2-1-14]]

^<<v2-1-14,14>>^ Tornaram-lhes a vida amarga, impondo-lhes a árdua tarefa de preparar o barro e fazer tijolos, e executar todo tipo de trabalho agrícola; em tudo os egípcios os sujeitavam a cruel escravidão.

[[v2-1-15]]

^<<v2-1-15,15>>^ O rei do Egito ordenou às parteiras dos hebreus, que se chamavam Sifrá e Puá:

[[v2-1-16]]

^<<v2-1-16,16>>^ "Quando vocês ajudarem as hebréias a dar à luz, verifiquem se é menino. Se for, matem-no; se for menina, deixem-na viver".

[[v2-1-17]]

^<<v2-1-17,17>>^ Todavia, as parteiras temeram a Deus e não obedeceram às ordens do rei do Egito; deixaram viver os meninos.

[[v2-1-18]]

^<<v2-1-18,18>>^ Então o rei do Egito convocou as parteiras e lhes perguntou: "Por que vocês fizeram isso? Por que deixaram viver os meninos? "

[[v2-1-19]]

^<<v2-1-19,19>>^ Responderam as parteiras do faraó: "As mulheres hebréias não são como as egípcias. São cheias de vigor e dão à luz antes de chegarem as parteiras".

[[v2-1-20]]

^<<v2-1-20,20>>^ Deus foi bondoso com as parteiras; e o povo ia se tornando ainda mais numeroso, cada vez mais forte.

[[v2-1-21]]

^<<v2-1-21,21>>^ Visto que as parteiras temeram a Deus, ele concedeu-lhes que tivessem suas próprias famílias.

[[v2-1-22]]

^<<v2-1-22,22>>^ Por isso o faraó ordenou a todo o seu povo: "Lancem ao Nilo todo menino recém-nascido, mas deixem viver as meninas".

'''

xref:001-genesis/001-genesis-050.adoc#v1-50-0[&#60; Capítulo Anterior] | <<v2-1-0,Topo>> | xref:002-exodo/002-exodo-002.adoc#v2-2-0[Próximo Capítulo &#62;]