include::./index.adoc[]

[[v2-40-0]]
=== Êxodo, 40
// nvi ?, NVI - Nova Versão Internacional

[[v2-40-1]]

^<<v2-40-1,1>>^ Disse o Senhor a Moisés:

[[v2-40-2]]

^<<v2-40-2,2>>^ "Arme o tabernáculo, a Tenda do Encontro, no primeiro dia do primeiro mês.

[[v2-40-3]]

^<<v2-40-3,3>>^ Coloque nele a arca da aliança e proteja-a com o véu.

[[v2-40-4]]

^<<v2-40-4,4>>^ Traga a mesa e arrume sobre ela tudo o que lhe pertence. Depois traga o candelabro e coloque as suas lâmpadas.

[[v2-40-5]]

^<<v2-40-5,5>>^ Ponha o altar de ouro para o incenso diante da arca da aliança e pendure a cortina na entrada do tabernáculo.

[[v2-40-6]]

^<<v2-40-6,6>>^ "Coloque o altar dos holocaustos em frente da entrada do tabernáculo, da Tenda do Encontro;

[[v2-40-7]]

^<<v2-40-7,7>>^ ponha a bacia entre a Tenda do Encontro e o altar, e encha-a de água.

[[v2-40-8]]

^<<v2-40-8,8>>^ Arme ao seu redor o pátio e coloque a cortina na entrada do pátio.

[[v2-40-9]]

^<<v2-40-9,9>>^ "Unja com o óleo da unção o tabernáculo e tudo o que nele há; consagre-o juntamente com tudo o que lhe pertence, e ele será sagrado.

[[v2-40-10]]

^<<v2-40-10,10>>^ Depois unja o altar dos holocaustos e todos os seus utensílios; consagre o altar, e ele será santíssimo.

[[v2-40-11]]

^<<v2-40-11,11>>^ Unja também a bacia com a sua base e consagre-a.

[[v2-40-12]]

^<<v2-40-12,12>>^ "Traga Arão e seus filhos à entrada da Tenda do Encontro e mande-os se lavar.

[[v2-40-13]]

^<<v2-40-13,13>>^ Vista depois Arão com as vestes sagradas, unja-o e consagre-o para que me sirva como sacerdote.

[[v2-40-14]]

^<<v2-40-14,14>>^ Traga os filhos dele e vista-os com túnicas.

[[v2-40-15]]

^<<v2-40-15,15>>^ Unja-os como você ungiu o pai deles, para que me sirvam como sacerdotes. A unção deles será para um sacerdócio perpétuo, geração após geração".

[[v2-40-16]]

^<<v2-40-16,16>>^ Moisés fez tudo conforme o Senhor lhe havia ordenado.

[[v2-40-17]]

^<<v2-40-17,17>>^ Assim, o tabernáculo foi armado no primeiro dia do primeiro mês do segundo ano.

[[v2-40-18]]

^<<v2-40-18,18>>^ Moisés armou o tabernáculo, colocou as bases em seus lugares, armou as molduras, colocou as vigas e levantou as colunas.

[[v2-40-19]]

^<<v2-40-19,19>>^ Depois estendeu a tenda sobre o tabernáculo e colocou a cobertura sobre ela, como o Senhor tinha ordenado.

[[v2-40-20]]

^<<v2-40-20,20>>^ Colocou também as tábuas da aliança na arca, fixou nela as varas, e pôs sobre ela a tampa.

[[v2-40-21]]

^<<v2-40-21,21>>^ Em seguida trouxe a arca para dentro do tabernáculo e pendurou o véu protetor, cobrindo a arca da aliança, como o Senhor tinha ordenado.

[[v2-40-22]]

^<<v2-40-22,22>>^ Moisés colocou a mesa na Tenda do Encontro, no lado norte do tabernáculo, do lado de fora do véu,

[[v2-40-23]]

^<<v2-40-23,23>>^ e sobre ela colocou os pães da Presença, diante do Senhor, como o Senhor tinha ordenado.

[[v2-40-24]]

^<<v2-40-24,24>>^ Pôs o candelabro na Tenda do Encontro, em frente da mesa, no lado sul do tabernáculo,

[[v2-40-25]]

^<<v2-40-25,25>>^ e colocou as lâmpadas diante do Senhor, como o Senhor tinha ordenado.

[[v2-40-26]]

^<<v2-40-26,26>>^ Moisés também pôs o altar de ouro na Tenda do Encontro, diante do véu,

[[v2-40-27]]

^<<v2-40-27,27>>^ e nele queimou incenso aromático, como o Senhor tinha ordenado.

[[v2-40-28]]

^<<v2-40-28,28>>^ Pôs também a cortina à entrada do tabernáculo.

[[v2-40-29]]

^<<v2-40-29,29>>^ Montou o altar de holocaustos à entrada do tabernáculo, a Tenda do Encontro, e sobre ele ofereceu holocaustos e ofertas de cereal, como o Senhor tinha ordenado.

[[v2-40-30]]

^<<v2-40-30,30>>^ Colocou a bacia entre a Tenda do Encontro e o altar, e encheu-a de água;

[[v2-40-31]]

^<<v2-40-31,31>>^ Moisés, Arão e os filhos deste usavam-na para lavar as mãos e os pés.

[[v2-40-32]]

^<<v2-40-32,32>>^ Sempre que entravam na Tenda do Encontro e se aproximavam do altar, eles se lavavam, como o Senhor tinha ordenado a Moisés.

[[v2-40-33]]

^<<v2-40-33,33>>^ Finalmente, Moisés armou o pátio ao redor do tabernáculo e colocou a cortina à entrada do pátio. Assim, Moisés terminou a obra.

[[v2-40-34]]

^<<v2-40-34,34>>^ Então a nuvem cobriu a Tenda do Encontro, e a glória do Senhor encheu o tabernáculo.

[[v2-40-35]]

^<<v2-40-35,35>>^ Moisés não podia entrar na Tenda do Encontro, porque a nuvem estava sobre ela, e a glória do Senhor enchia o tabernáculo.

[[v2-40-36]]

^<<v2-40-36,36>>^ Sempre que a nuvem se erguia sobre o tabernáculo os israelitas seguiam viagem;

[[v2-40-37]]

^<<v2-40-37,37>>^ mas se a nuvem não se erguia, eles não prosseguiam; só partiam no dia em que ela se erguesse.

[[v2-40-38]]

^<<v2-40-38,38>>^ De dia a nuvem do Senhor ficava sobre o tabernáculo, e de noite havia fogo na nuvem, à vista de toda a nação de Israel, em todas as suas viagens.

'''

xref:002-exodo/002-exodo-039.adoc#v2-39-0[&#60; Capítulo Anterior] | <<v2-40-0,Topo>> | xref:003-levitico/003-levitico-001.adoc#v3-1-0[Próximo Capítulo &#62;]