include::./index.adoc[]

[[v2-11-0]]
=== Êxodo, 11
// nvi ?, NVI - Nova Versão Internacional

[[v2-11-1]]

^<<v2-11-1,1>>^ Disse então o Senhor a Moisés: "Enviarei ainda mais uma praga sobre o faraó e sobre o Egito. Somente depois desta ele os deixará sair daqui e até os expulsará totalmente.

[[v2-11-2]]

^<<v2-11-2,2>>^ Diga ao povo, tanto aos homens como às mulheres, que peça aos seus vizinhos objetos de prata e de ouro".

[[v2-11-3]]

^<<v2-11-3,3>>^ O Senhor tornou os egípcios favoráveis ao povo, e o próprio Moisés era tido em alta estima no Egito pelos conselheiros do faraó e pelo povo.

[[v2-11-4]]

^<<v2-11-4,4>>^ Disse, pois, Moisés ao faraó: "Assim diz o Senhor: ‘Por volta da meia-noite, passarei por todo o Egito.

[[v2-11-5]]

^<<v2-11-5,5>>^ Todos os primogênitos do Egito morrerão, desde o filho mais velho do faraó, herdeiro do trono, até o filho mais velho da escrava que trabalha no moinho, e também todas as primeiras crias do gado.

[[v2-11-6]]

^<<v2-11-6,6>>^ Haverá grande pranto em todo o Egito, como nunca houve antes nem jamais haverá.

[[v2-11-7]]

^<<v2-11-7,7>>^ Entre os israelitas, porém, nem sequer um cão latirá contra homem ou animal’. Então vocês saberão que o Senhor faz distinção entre o Egito e Israel!

[[v2-11-8]]

^<<v2-11-8,8>>^ Todos esses seus conselheiros virão a mim e se ajoelharão diante de mim, suplicando: ‘Saiam você e todo o povo que o segue! ’ Só então eu sairei". E, com grande ira, Moisés saiu da presença do faraó.

[[v2-11-9]]

^<<v2-11-9,9>>^ O Senhor tinha dito a Moisés: "O faraó não lhes dará ouvidos, a fim de que os meus prodígios se multipliquem no Egito".

[[v2-11-10]]

^<<v2-11-10,10>>^ Moisés e Arão realizaram todos esses prodígios diante do faraó, mas o Senhor lhe endureceu o coração, e ele não quis deixar os israelitas saírem do país.

'''

xref:002-exodo/002-exodo-010.adoc#v2-10-0[&#60; Capítulo Anterior] | <<v2-11-0,Topo>> | xref:002-exodo/002-exodo-012.adoc#v2-12-0[Próximo Capítulo &#62;]