include::./index.adoc[]

[[v2-37-0]]
=== Êxodo, 37
// nvi ?, NVI - Nova Versão Internacional

[[v2-37-1]]

^<<v2-37-1,1>>^ Bezalel fez a arca com madeira de acácia, com um metro e dez centímetros de comprimento, setenta centímetros de largura e setenta centímetros de altura.

[[v2-37-2]]

^<<v2-37-2,2>>^ Revestiu-a de ouro puro, por dentro e por fora, e fez uma moldura de ouro ao seu redor.

[[v2-37-3]]

^<<v2-37-3,3>>^ Fundiu quatro argolas de ouro para ela, prendendo-as a seus quatro pés, com duas argolas de um lado e duas do outro.

[[v2-37-4]]

^<<v2-37-4,4>>^ Depois fez varas de madeira de acácia e revestiu-as de ouro

[[v2-37-5]]

^<<v2-37-5,5>>^ e colocou-as nas argolas laterais da arca para que pudesse ser carregada.

[[v2-37-6]]

^<<v2-37-6,6>>^ Fez a tampa de ouro puro com um metro e dez centímetros de comprimento por setenta centímetros de largura.

[[v2-37-7]]

^<<v2-37-7,7>>^ Fez também dois querubins de ouro batido nas extremidades da tampa.

[[v2-37-8]]

^<<v2-37-8,8>>^ Fez ainda um querubim numa extremidade e o segundo na outra, formando uma só peça com a tampa.

[[v2-37-9]]

^<<v2-37-9,9>>^ Os querubins tinham as asas estendidas para cima, cobrindo com elas a tampa. Estavam de frente um para o outro, com o rosto voltado para a tampa.

[[v2-37-10]]

^<<v2-37-10,10>>^ Fez a mesa com madeira de acácia com noventa centímetros de comprimento, quarenta e cinco centímetros de largura e setenta centímetros de altura.

[[v2-37-11]]

^<<v2-37-11,11>>^ Revestiu-a de ouro puro e fez uma moldura de ouro ao seu redor.

[[v2-37-12]]

^<<v2-37-12,12>>^ Fez também ao seu redor uma borda com a largura de quatro dedos e uma moldura de ouro para essa borda.

[[v2-37-13]]

^<<v2-37-13,13>>^ Fundiu quatro argolas de ouro para a mesa e prendeu-as nos quatro cantos, onde estavam os seus quatro pés.

[[v2-37-14]]

^<<v2-37-14,14>>^ As argolas foram presas próximas da borda, para que sustentassem as varas usadas para carregar a mesa.

[[v2-37-15]]

^<<v2-37-15,15>>^ Fez as varas para carregar a mesa de madeira de acácia, revestidas de ouro.

[[v2-37-16]]

^<<v2-37-16,16>>^ E de ouro puro fez os utensílios para a mesa: seus pratos e recipientes para incenso, tigelas e as bacias nas quais se derramam as ofertas de bebidas.

[[v2-37-17]]

^<<v2-37-17,17>>^ Fez o candelabro de ouro puro e batido. O pedestal, a haste, as taças, as flores e os botões formavam com ele uma só peça.

[[v2-37-18]]

^<<v2-37-18,18>>^ Seis braços saíam do candelabro: três de um lado e três do outro.

[[v2-37-19]]

^<<v2-37-19,19>>^ Havia três taças com formato de flor de amêndoa, num dos braços, cada uma com botão e flor, e três taças com formato de flor de amêndoa no braço seguinte, cada uma com botão e flor. Assim será com os seis braços que saem do candelabro.

[[v2-37-20]]

^<<v2-37-20,20>>^ Na haste do candelabro havia quatro taças com formato de flor de amêndoa, cada uma com flor e botão.

[[v2-37-21]]

^<<v2-37-21,21>>^ Havia um botão debaixo de cada par dos seis braços que saíam do candelabro.

[[v2-37-22]]

^<<v2-37-22,22>>^ Os braços com seus botões formavam uma só peça com o candelabro, tudo feito de ouro puro e batido.

[[v2-37-23]]

^<<v2-37-23,23>>^ Fez de ouro puro suas sete lâmpadas, seus cortadores de pavio e seus apagadores.

[[v2-37-24]]

^<<v2-37-24,24>>^ Com trinta e cinco quilos de ouro puro fez o candelabro com seus botões e todos esses utensílios.

[[v2-37-25]]

^<<v2-37-25,25>>^ Fez ainda o altar de incenso de madeira de acácia. Era quadrado, com quarenta e cinco centímetros de cada lado e noventa centímetros de altura; suas pontas formavam com ele uma só peça.

[[v2-37-26]]

^<<v2-37-26,26>>^ Revestiu de ouro puro a parte superior, todos os lados e as pontas, e fez uma moldura de ouro ao seu redor.

[[v2-37-27]]

^<<v2-37-27,27>>^ Fez também duas argolas de ouro de cada lado do altar, abaixo da moldura, para sustentar as varas utilizadas para carregá-lo,

[[v2-37-28]]

^<<v2-37-28,28>>^ e usou madeira de acácia para fazer as varas e revestiu-as de ouro.

[[v2-37-29]]

^<<v2-37-29,29>>^ Fez ainda o óleo sagrado para as unções e o incenso puro e aromático, obra de perfumista.

'''

xref:002-exodo/002-exodo-036.adoc#v2-36-0[&#60; Capítulo Anterior] | <<v2-37-0,Topo>> | xref:002-exodo/002-exodo-038.adoc#v2-38-0[Próximo Capítulo &#62;]