include::./index.adoc[]

[[v2-14-0]]
=== Êxodo, 14
// nvi ?, NVI - Nova Versão Internacional

[[v2-14-1]]

^<<v2-14-1,1>>^ Disse o Senhor a Moisés:

[[v2-14-2]]

^<<v2-14-2,2>>^ "Diga aos israelitas que mudem o rumo e acampem perto de Pi-Hairote, entre Migdol e o mar. Acampem à beira-mar, defronte de Baal-Zefom.

[[v2-14-3]]

^<<v2-14-3,3>>^ O faraó pensará que os israelitas estão vagando confusos, cercados pelo deserto.

[[v2-14-4]]

^<<v2-14-4,4>>^ Então endurecerei o coração do faraó, e ele os perseguirá. Todavia, eu serei glorificado por meio do faraó e de todo o seu exército; e os egípcios saberão que eu sou o Senhor". E assim fizeram os israelitas.

[[v2-14-5]]

^<<v2-14-5,5>>^ Contaram ao rei do Egito que o povo havia fugido. Então o faraó e os seus conselheiros mudaram de idéia e disseram: "O que foi que fizemos? Deixamos os israelitas saírem e perdemos os nossos escravos! "

[[v2-14-6]]

^<<v2-14-6,6>>^ Então o faraó mandou aprontar a sua carruagem, e levou consigo o seu exército.

[[v2-14-7]]

^<<v2-14-7,7>>^ Levou todos os carros de guerra do Egito, inclusive seiscentos dos melhores desses carros, cada um com um oficial no seu comando.

[[v2-14-8]]

^<<v2-14-8,8>>^ O Senhor endureceu o coração do faraó, rei do Egito, e este perseguiu os israelitas, que marchavam triunfantemente.

[[v2-14-9]]

^<<v2-14-9,9>>^ Os egípcios, com todos os cavalos e carros de guerra do faraó, os cavaleiros e a infantaria, saíram em perseguição aos israelitas e os alcançaram quando estavam acampados à beira-mar, perto de Pi-Hairote, defronte de Baal-Zefom.

[[v2-14-10]]

^<<v2-14-10,10>>^ Ao aproximar-se o faraó, os israelitas olharam e avistaram os egípcios que marchavam na direção deles. E, aterrorizados, clamaram ao Senhor.

[[v2-14-11]]

^<<v2-14-11,11>>^ Disseram a Moisés: "Foi por falta de túmulos no Egito que você nos trouxe para morrermos no deserto? O que você fez conosco, tirando-nos de lá?

[[v2-14-12]]

^<<v2-14-12,12>>^ Já não lhe tínhamos dito no Egito: Deixe-nos em paz! Seremos escravos dos egípcios! Antes ser escravos dos egípcios do que morrer no deserto! "

[[v2-14-13]]

^<<v2-14-13,13>>^ Moisés respondeu ao povo: "Não tenham medo. Fiquem firmes e vejam o livramento que o Senhor lhes trará hoje, porque vocês nunca mais verão os egípcios que hoje vêem.

[[v2-14-14]]

^<<v2-14-14,14>>^ O Senhor lutará por vocês; tão-somente acalmem-se".

[[v2-14-15]]

^<<v2-14-15,15>>^ Disse então o Senhor a Moisés: "Por que você está clamando a mim? Diga aos israelitas que sigam avante.

[[v2-14-16]]

^<<v2-14-16,16>>^ Erga a sua vara e estenda a mão sobre o mar, e as águas se dividirão para que os israelitas atravessem o mar em terra seca.

[[v2-14-17]]

^<<v2-14-17,17>>^ Eu, porém, endurecerei o coração dos egípcios e eles os perseguirão. E serei glorificado com a derrota do faraó e de todo o seu exército, com seus carros de guerra e seus cavaleiros.

[[v2-14-18]]

^<<v2-14-18,18>>^ Os egípcios saberão que eu sou o Senhor quando eu for glorificado com a derrota do faraó, com seus carros de guerra e seus cavaleiros".

[[v2-14-19]]

^<<v2-14-19,19>>^ A seguir o anjo de Deus que ia à frente dos exércitos de Israel retirou-se, colocando-se atrás deles. A coluna de nuvem também saiu da frente deles e se pôs atrás,

[[v2-14-20]]

^<<v2-14-20,20>>^ entre os egípcios e os israelitas. A nuvem trouxe trevas para um e luz para o outro, de modo que os egípcios não puderam aproximar-se dos israelitas durante toda a noite.

[[v2-14-21]]

^<<v2-14-21,21>>^ Então Moisés estendeu a mão sobre o mar, e o Senhor afastou o mar e o tornou em terra seca, com um forte vento oriental que soprou toda aquela noite. As águas se dividiram,

[[v2-14-22]]

^<<v2-14-22,22>>^ e os israelitas atravessaram pelo meio do mar em terra seca, tendo uma parede de água à direita e outra à esquerda.

[[v2-14-23]]

^<<v2-14-23,23>>^ Os egípcios os perseguiram, e todos os cavalos, carros de guerra e cavaleiros do faraó foram atrás deles até o meio do mar.

[[v2-14-24]]

^<<v2-14-24,24>>^ No fim da madrugada, do alto da coluna de fogo e de nuvem, o Senhor viu o exército dos egípcios e o pôs em confusão.

[[v2-14-25]]

^<<v2-14-25,25>>^ Fez que as rodas dos seus carros começassem a soltar-se, de forma que tinham dificuldades em conduzi-los. E os egípcios gritaram: "Vamos fugir dos israelitas! O Senhor está lutando por eles contra o Egito".

[[v2-14-26]]

^<<v2-14-26,26>>^ Mas o Senhor disse a Moisés: "Estenda a mão sobre o mar para que as águas voltem sobre os egípcios, sobre os seus carros de guerra e sobre os seus cavaleiros".

[[v2-14-27]]

^<<v2-14-27,27>>^ Moisés estendeu a mão sobre o mar, e ao raiar do dia o mar voltou ao seu lugar. Quando os egípcios estavam fugindo, foram de encontro às águas, e o Senhor os lançou ao mar.

[[v2-14-28]]

^<<v2-14-28,28>>^ As águas voltaram e encobriram os seus carros de guerra e os seus cavaleiros, todo o exército do faraó que havia perseguido os israelitas mar adentro. Ninguém sobreviveu.

[[v2-14-29]]

^<<v2-14-29,29>>^ Mas os israelitas atravessaram o mar pisando em terra seca, tendo uma parede de água à direita e outra à esquerda.

[[v2-14-30]]

^<<v2-14-30,30>>^ Naquele dia o Senhor salvou Israel das mãos dos egípcios, e os israelitas viram os egípcios mortos na praia.

[[v2-14-31]]

^<<v2-14-31,31>>^ Israel viu o grande poder do Senhor contra os egípcios, temeu ao Senhor e pôs nele a sua confiança, como também em Moisés, seu servo.

'''

xref:002-exodo/002-exodo-013.adoc#v2-13-0[&#60; Capítulo Anterior] | <<v2-14-0,Topo>> | xref:002-exodo/002-exodo-015.adoc#v2-15-0[Próximo Capítulo &#62;]