include::./index.adoc[]

[[v2-17-0]]
=== Êxodo, 17
// nvi ?, NVI - Nova Versão Internacional

[[v2-17-1]]

^<<v2-17-1,1>>^ Toda a comunidade de Israel partiu do deserto de Sim, andando de um lugar para outro, conforme a ordem do Senhor. Acamparam em Refidim, mas lá não havia água para beber.

[[v2-17-2]]

^<<v2-17-2,2>>^ Por essa razão queixaram-se a Moisés e exigiram: "Dê-nos água para beber". Ele respondeu: "Por que se queixam a mim? Por que colocam o Senhor à prova? "

[[v2-17-3]]

^<<v2-17-3,3>>^ Mas o povo estava sedento e reclamou a Moisés: "Por que você nos tirou do Egito? Foi para matar de sede a nós, aos nossos filhos e aos nossos rebanhos? "

[[v2-17-4]]

^<<v2-17-4,4>>^ Então Moisés clamou ao Senhor: "Que farei com este povo? Estão a ponto de apedrejar-me! "

[[v2-17-5]]

^<<v2-17-5,5>>^ Respondeu-lhe o Senhor: "Passe à frente do povo. Leve com você algumas das autoridades de Israel, tenha na mão a vara com a qual você feriu o Nilo e vá adiante.

[[v2-17-6]]

^<<v2-17-6,6>>^ Eu estarei à sua espera no alto da rocha que está em Horebe. Bata na rocha, e dela sairá água para o povo beber". Assim fez Moisés, à vista das autoridades de Israel.

[[v2-17-7]]

^<<v2-17-7,7>>^ E chamou aquele lugar Massá e Meribá, porque ali os israelitas reclamaram e puseram o Senhor à prova, dizendo: "O Senhor está entre nós, ou não? "

[[v2-17-8]]

^<<v2-17-8,8>>^ Sucedeu que os amalequitas vieram atacar os israelitas em Refidim.

[[v2-17-9]]

^<<v2-17-9,9>>^ Então Moisés disse a Josué: "Escolha alguns dos nossos homens e lute contra os amalequitas. Amanhã tomarei posição no alto da colina, com a vara de Deus em minhas mãos".

[[v2-17-10]]

^<<v2-17-10,10>>^ Josué foi então lutar contra os amalequitas, conforme Moisés tinha ordenado. Moisés, Arão e Hur, porém, subiram ao alto da colina.

[[v2-17-11]]

^<<v2-17-11,11>>^ Enquanto Moisés mantinha as mãos erguidas, os israelitas venciam; quando, porém, as abaixava, os amalequitas venciam.

[[v2-17-12]]

^<<v2-17-12,12>>^ Quando as mãos de Moisés já estavam cansadas, eles pegaram uma pedra e a colocaram debaixo dele, para que nela se assentasse. Arão e Hur mantinham erguidas as mãos de Moisés, um de cada lado, de modo que as mãos permaneceram firmes até o pôr-do-sol.

[[v2-17-13]]

^<<v2-17-13,13>>^ E Josué derrotou o exército amalequita ao fio da espada.

[[v2-17-14]]

^<<v2-17-14,14>>^ Depois o Senhor disse a Moisés: "Escreva isto num rolo, como memorial, e declare a Josué que farei que os amalequitas sejam esquecidos para sempre debaixo do céu".

[[v2-17-15]]

^<<v2-17-15,15>>^ Moisés construiu um altar e chamou-lhe "o Senhor é minha bandeira".

[[v2-17-16]]

^<<v2-17-16,16>>^ E jurou: "Pelo trono do Senhor! O Senhor fará guerra contra os amalequitas de geração em geração".

'''

xref:002-exodo/002-exodo-016.adoc#v2-16-0[&#60; Capítulo Anterior] | <<v2-17-0,Topo>> | xref:002-exodo/002-exodo-018.adoc#v2-18-0[Próximo Capítulo &#62;]