include::./index.adoc[]

[[v2-35-0]]
=== Êxodo, 35
// nvi ?, NVI - Nova Versão Internacional

[[v2-35-1]]

^<<v2-35-1,1>>^ Moisés reuniu toda a comunidade de Israel e lhes disse: "Estas são as coisas que o Senhor os mandou fazer:

[[v2-35-2]]

^<<v2-35-2,2>>^ Em seis dias qualquer trabalho poderá ser feito, mas o sétimo dia lhes será santo, um sábado de descanso consagrado ao Senhor. Todo aquele que trabalhar nesse dia terá que ser morto.

[[v2-35-3]]

^<<v2-35-3,3>>^ Nem sequer acendam fogo em nenhuma de suas casas no dia de sábado! "

[[v2-35-4]]

^<<v2-35-4,4>>^ Disse Moisés a toda a comunidade de Israel: "Foi isto que o Senhor ordenou:

[[v2-35-5]]

^<<v2-35-5,5>>^ Separem dentre os seus bens uma oferta para o Senhor. Todo aquele que, de coração, estiver disposto, trará como oferta ao Senhor ouro, prata e bronze;

[[v2-35-6]]

^<<v2-35-6,6>>^ fios de tecido azul, roxo e vermelho; linho fino e pêlos de cabra;

[[v2-35-7]]

^<<v2-35-7,7>>^ peles de carneiro tingidas de vermelho e couro; madeira de acácia;

[[v2-35-8]]

^<<v2-35-8,8>>^ óleo para a iluminação; especiarias para o óleo da unção e para o incenso aromático;

[[v2-35-9]]

^<<v2-35-9,9>>^ pedras de ônix e outras pedras preciosas para serem encravadas no colete sacerdotal e no peitoral.

[[v2-35-10]]

^<<v2-35-10,10>>^ "Todos os que dentre vocês forem capazes virão fazer tudo quanto o Senhor ordenou:

[[v2-35-11]]

^<<v2-35-11,11>>^ o tabernáculo com sua tenda e sua cobertura, os ganchos, as armações, os travessões, as colunas e as bases;

[[v2-35-12]]

^<<v2-35-12,12>>^ a arca com suas varas, a tampa e o véu que a protege;

[[v2-35-13]]

^<<v2-35-13,13>>^ a mesa com suas varas e todos os seus utensílios, e os pães da Presença;

[[v2-35-14]]

^<<v2-35-14,14>>^ o candelabro com seus utensílios, as lâmpadas e o óleo para iluminação;

[[v2-35-15]]

^<<v2-35-15,15>>^ o altar do incenso com suas varas, o óleo da unção e o incenso aromático; a cortina divisória à entrada do tabernáculo;

[[v2-35-16]]

^<<v2-35-16,16>>^ o altar de holocaustos com sua grelha de bronze, suas varas e todos os seus utensílios; a bacia de bronze e sua base;

[[v2-35-17]]

^<<v2-35-17,17>>^ as cortinas externas do pátio com suas colunas e bases, e a cortina da entrada para o pátio;

[[v2-35-18]]

^<<v2-35-18,18>>^ as estacas do tabernáculo e do pátio e suas cordas;

[[v2-35-19]]

^<<v2-35-19,19>>^ as vestes litúrgicas para ministrar no Lugar Santo, tanto as vestes sagradas de Arão, o sacerdote, como as vestes de seus filhos, para quando servirem como sacerdotes".

[[v2-35-20]]

^<<v2-35-20,20>>^ Então toda a comunidade de Israel saiu da presença de Moisés,

[[v2-35-21]]

^<<v2-35-21,21>>^ e todos os que estavam dispostos, cujo coração os impeliu a isso, trouxeram uma oferta ao Senhor para a obra na Tenda do Encontro, para todos os seus serviços e para as vestes sagradas.

[[v2-35-22]]

^<<v2-35-22,22>>^ Todos os que se dispuseram, tanto homens como mulheres, trouxeram jóias de ouro de todos os tipos: broches, brincos, anéis e ornamentos; e apresentaram seus objetos de ouro como oferta ritualmente movida perante o Senhor.

[[v2-35-23]]

^<<v2-35-23,23>>^ Todos os que possuíam fios de tecido azul, roxo e vermelho, ou linho fino, ou pêlos de cabra, peles de carneiro tingidas de vermelho ou couro, trouxeram-nos.

[[v2-35-24]]

^<<v2-35-24,24>>^ Aqueles que apresentaram oferta de prata ou de bronze trouxeram-na como oferta ao Senhor, e todo aquele que possuía madeira de acácia para qualquer das partes da obra, também a trouxe.

[[v2-35-25]]

^<<v2-35-25,25>>^ Todas as mulheres capazes teceram com suas mãos e trouxeram o que haviam feito: tecidos azul, roxo e vermelho e linho fino.

[[v2-35-26]]

^<<v2-35-26,26>>^ Todas as mulheres que se dispuseram e que tinham habilidade teceram os pêlos de cabra.

[[v2-35-27]]

^<<v2-35-27,27>>^ Os líderes trouxeram pedras de ônix e outras pedras preciosas para serem encravadas no colete sacerdotal e no peitoral.

[[v2-35-28]]

^<<v2-35-28,28>>^ Trouxeram também especiarias e azeite de oliva para iluminação, para o óleo da unção e para o incenso aromático.

[[v2-35-29]]

^<<v2-35-29,29>>^ Todos os israelitas que se dispuseram, tanto homens como mulheres, trouxeram ao Senhor ofertas voluntárias para toda a obra que o Senhor, por meio de Moisés, ordenou-lhes que fizessem.

[[v2-35-30]]

^<<v2-35-30,30>>^ Disse então Moisés aos israelitas: "O Senhor escolheu Bezalel, filho de Uri, neto de Hur, da tribo de Judá,

[[v2-35-31]]

^<<v2-35-31,31>>^ e o encheu do Espírito de Deus, dando-lhe destreza, habilidade e plena capacidade artística,

[[v2-35-32]]

^<<v2-35-32,32>>^ para desenhar e executar trabalhos em ouro, prata e bronze,

[[v2-35-33]]

^<<v2-35-33,33>>^ para talhar e lapidar pedras, entalhar madeira para todo tipo de obra artesanal.

[[v2-35-34]]

^<<v2-35-34,34>>^ E concedeu tanto a ele como a Aoliabe, filho de Aisamaque, da tribo de Dã, a habilidade de ensinar os outros.

[[v2-35-35]]

^<<v2-35-35,35>>^ A todos esses deu capacidade para realizar todo tipo de obra como artesãos, projetistas, bordadores de linho fino e de fios de tecido azul, roxo e vermelho, e como tecelões. Eram capazes para projetar e executar qualquer trabalho artesanal".

'''

xref:002-exodo/002-exodo-034.adoc#v2-34-0[&#60; Capítulo Anterior] | <<v2-35-0,Topo>> | xref:002-exodo/002-exodo-036.adoc#v2-36-0[Próximo Capítulo &#62;]