include::./index.adoc[]

[[v2-4-0]]
=== Êxodo, 4
// nvi ?, NVI - Nova Versão Internacional

[[v2-4-1]]

^<<v2-4-1,1>>^ Moisés respondeu: "E se eles não acreditarem em mim nem quiserem me ouvir e disserem: ‘O Senhor não lhe apareceu’? "

[[v2-4-2]]

^<<v2-4-2,2>>^ Então o Senhor lhe perguntou: "Que é isso em sua mão? " "Uma vara", respondeu ele.

[[v2-4-3]]

^<<v2-4-3,3>>^ Disse o Senhor: "Jogue-a ao chão". Moisés jogou-a, e ela se transformou numa serpente. Moisés fugiu dela,

[[v2-4-4]]

^<<v2-4-4,4>>^ mas o Senhor lhe disse: "Estenda a mão e pegue-a pela cauda". Moisés estendeu a mão, pegou a serpente e esta se transformou numa vara em sua mão.

[[v2-4-5]]

^<<v2-4-5,5>>^ E disse o Senhor: "Isso é para que eles acreditem que o Deus dos seus antepassados, o Deus de Abraão, o Deus de Isaque, o Deus de Jacó, apareceu a você".

[[v2-4-6]]

^<<v2-4-6,6>>^ Disse-lhe mais o Senhor: "Coloque a mão no peito". Moisés obedeceu e, quando a retirou, ela estava leprosa; parecia neve.

[[v2-4-7]]

^<<v2-4-7,7>>^ Ordenou-lhe depois: "Agora, coloque de novo a mão no peito". Moisés tornou a pôr a mão no peito e, quando a tirou, ela estava novamente como o restante da sua pele.

[[v2-4-8]]

^<<v2-4-8,8>>^ Prosseguiu o Senhor: "Se eles não acreditarem em você nem derem atenção ao primeiro sinal miraculoso, acreditarão no segundo.

[[v2-4-9]]

^<<v2-4-9,9>>^ E se ainda assim não acreditarem nestes dois sinais nem lhe derem ouvidos, tire um pouco de água do Nilo e derrame-a em terra seca. Quando você derramar essa água em terra seca ela se transformará em sangue".

[[v2-4-10]]

^<<v2-4-10,10>>^ Disse, porém, Moisés ao Senhor: "Ó Senhor! Nunca tive facilidade para falar, nem no passado nem agora que falaste a teu servo. Não consigo falar bem! "

[[v2-4-11]]

^<<v2-4-11,11>>^ Disse-lhe o Senhor: "Quem deu boca ao homem? Quem o fez surdo ou mudo? Quem lhe concede vista ou o torna cego? Não sou eu, o Senhor?

[[v2-4-12]]

^<<v2-4-12,12>>^ Agora, pois, vá; eu estarei com você, ensinando-lhe o que dizer".

[[v2-4-13]]

^<<v2-4-13,13>>^ Respondeu-lhe, porém, Moisés: "Ah Senhor! Peço-te que envies outra pessoa".

[[v2-4-14]]

^<<v2-4-14,14>>^ Então o Senhor se irou com Moisés e lhe disse: "Você não tem o seu irmão Arão, o levita? Eu sei que ele fala bem. Ele já está vindo ao seu encontro e se alegrará ao vê-lo.

[[v2-4-15]]

^<<v2-4-15,15>>^ Você falará com ele e lhe dirá o que ele deve dizer; eu estarei com vocês quando falarem, e lhes direi o que fazer.

[[v2-4-16]]

^<<v2-4-16,16>>^ Assim como Deus fala ao profeta, você falará a seu irmão, e ele será o seu porta-voz diante do povo.

[[v2-4-17]]

^<<v2-4-17,17>>^ E leve na mão esta vara; com ela você fará os sinais miraculosos".

[[v2-4-18]]

^<<v2-4-18,18>>^ Depois Moisés voltou a Jetro, seu sogro, e lhe disse: "Preciso voltar ao Egito para ver se meus parentes ainda vivem". Jetro lhe respondeu: "Vá em paz! "

[[v2-4-19]]

^<<v2-4-19,19>>^ Ora, o Senhor tinha dito a Moisés, em Midiã: "Volte ao Egito, pois já morreram todos os que procuravam matá-lo".

[[v2-4-20]]

^<<v2-4-20,20>>^ Então Moisés levou sua mulher e seus filhos montados num jumento e partiu de volta ao Egito. Levava na mão a vara de Deus.

[[v2-4-21]]

^<<v2-4-21,21>>^ Disse mais o Senhor a Moisés: "Quando você voltar ao Egito, tenha o cuidado de fazer diante do faraó todas as maravilhas que concedi a você o poder de realizar. Mas eu vou endurecer o coração dele, para não deixar o povo ir.

[[v2-4-22]]

^<<v2-4-22,22>>^ Depois diga ao faraó que assim diz o Senhor: Israel é o meu primeiro filho,

[[v2-4-23]]

^<<v2-4-23,23>>^ e eu já lhe disse que deixe o meu filho ir para prestar-me culto. Mas você não quis deixá-lo ir; por isso matarei o seu primeiro filho! "

[[v2-4-24]]

^<<v2-4-24,24>>^ Numa hospedaria ao longo do caminho, o Senhor foi ao encontro de Moisés e procurou matá-lo.

[[v2-4-25]]

^<<v2-4-25,25>>^ Mas Zípora pegou uma pedra afiada, cortou o prepúcio de seu filho e tocou os pés de Moisés. E disse: "Você é para mim um marido de sangue! "

[[v2-4-26]]

^<<v2-4-26,26>>^ Ela disse "marido de sangue", referindo-se à circuncisão. Nessa ocasião o Senhor o deixou.

[[v2-4-27]]

^<<v2-4-27,27>>^ Então o Senhor disse a Arão: "Vá ao deserto encontrar-se com Moisés". Ele foi, encontrou-se com Moisés no monte de Deus, e o saudou com um beijo.

[[v2-4-28]]

^<<v2-4-28,28>>^ Moisés contou a Arão tudo o que o Senhor lhe tinha mandado dizer, e também falou-lhe de todos os sinais miraculosos que lhe havia ordenado realizar.

[[v2-4-29]]

^<<v2-4-29,29>>^ Assim Moisés e Arão foram e reuniram todas as autoridades dos israelitas,

[[v2-4-30]]

^<<v2-4-30,30>>^ e Arão lhes contou tudo o que o Senhor dissera a Moisés. Em seguida Moisés também realizou os sinais diante do povo,

[[v2-4-31]]

^<<v2-4-31,31>>^ e eles creram. Quando o povo soube que o Senhor decidira vir em auxílio deles e tinha visto a sua opressão, curvou-se em adoração.

'''

xref:002-exodo/002-exodo-003.adoc#v2-3-0[&#60; Capítulo Anterior] | <<v2-4-0,Topo>> | xref:002-exodo/002-exodo-005.adoc#v2-5-0[Próximo Capítulo &#62;]