include::./index.adoc[]

[[v2-33-0]]
=== Êxodo, 33
// nvi ?, NVI - Nova Versão Internacional

[[v2-33-1]]

^<<v2-33-1,1>>^ Depois ordenou o Senhor a Moisés: "Saia deste lugar, com o povo que você tirou do Egito, e vá para a terra que prometi com juramento a Abraão, a Isaque e a Jacó, dizendo: Eu a darei a seus descendentes.

[[v2-33-2]]

^<<v2-33-2,2>>^ Mandarei à sua frente um anjo e expulsarei os cananeus, os amorreus, os hititas, os ferezeus, os heveus e os jebuseus.

[[v2-33-3]]

^<<v2-33-3,3>>^ Vão para a terra onde manam leite e mel. Mas eu não irei com vocês, pois vocês são um povo obstinado, e eu poderia destruí-los no caminho".

[[v2-33-4]]

^<<v2-33-4,4>>^ Quando o povo ouviu essas palavras terríveis, começou a chorar, e ninguém usou enfeite algum.

[[v2-33-5]]

^<<v2-33-5,5>>^ Isso porque o Senhor ordenara que Moisés dissesse aos israelitas: "Vocês são um povo obstinado. Se eu fosse com vocês, ainda que por um só momento, eu os destruiria. Agora tirem os seus enfeites, e eu decidirei o que fazer com vocês".

[[v2-33-6]]

^<<v2-33-6,6>>^ Por isso, do monte Horebe em diante, os israelitas não usaram mais nenhum enfeite.

[[v2-33-7]]

^<<v2-33-7,7>>^ Moisés costumava montar uma tenda do lado de fora do acampamento; ele a chamava Tenda do Encontro. Quem quisesse consultar a Deus ia à tenda, fora do acampamento.

[[v2-33-8]]

^<<v2-33-8,8>>^ Sempre que Moisés ia até lá, todo o povo se levantava e ficava de pé à entrada de suas tendas, observando-o, até que ele entrasse na tenda.

[[v2-33-9]]

^<<v2-33-9,9>>^ Assim que Moisés entrava, a coluna de nuvem descia e ficava à entrada da tenda, enquanto o Senhor falava com Moisés.

[[v2-33-10]]

^<<v2-33-10,10>>^ Quando o povo via a coluna de nuvem parada à entrada da tenda, todos prestavam adoração de pé, cada qual na entrada de sua própria tenda.

[[v2-33-11]]

^<<v2-33-11,11>>^ O Senhor falava com Moisés face a face, como quem fala com seu amigo. Depois Moisés voltava ao acampamento; mas Josué, filho de Num, que lhe servia como auxiliar, não se afastava da tenda.

[[v2-33-12]]

^<<v2-33-12,12>>^ Disse Moisés ao Senhor: "Tu me ordenaste: ‘Conduza este povo’, mas não me permites saber quem enviarás comigo. Disseste: ‘Eu o conheço pelo nome e de você tenho me agradado’.

[[v2-33-13]]

^<<v2-33-13,13>>^ Se me vês com agrado, revela-me os teus propósitos, para que eu te conheça e continue sendo aceito por ti. Lembra-te de que esta nação é o teu povo".

[[v2-33-14]]

^<<v2-33-14,14>>^ Respondeu o Senhor: "Eu mesmo o acompanharei, e lhe darei descanso".

[[v2-33-15]]

^<<v2-33-15,15>>^ Então Moisés lhe declarou: "Se não fores conosco não nos envies.

[[v2-33-16]]

^<<v2-33-16,16>>^ Como se saberá que eu e o teu povo podemos contar com o teu favor, se não nos acompanhares? Que mais poderá distinguir a mim e a teu povo de todos os demais povos da face da terra? "

[[v2-33-17]]

^<<v2-33-17,17>>^ O Senhor disse a Moisés: "Farei o que me pede, porque tenho me agradado de você e o conheço pelo nome".

[[v2-33-18]]

^<<v2-33-18,18>>^ Então disse Moisés: "Peço-te que me mostres a tua glória".

[[v2-33-19]]

^<<v2-33-19,19>>^ E Deus respondeu: "Diante de você farei passar toda a minha bondade, e diante de você proclamarei o meu nome: o Senhor. Terei misericórdia de quem eu quiser ter misericórdia, e terei compaixão de quem eu quiser ter compaixão".

[[v2-33-20]]

^<<v2-33-20,20>>^ E acrescentou: "Você não poderá ver a minha face, porque ninguém poderá ver-me e continuar vivo".

[[v2-33-21]]

^<<v2-33-21,21>>^ E prosseguiu o Senhor: "Há aqui um lugar perto de mim, onde você ficará, em cima de uma rocha.

[[v2-33-22]]

^<<v2-33-22,22>>^ Quando a minha glória passar, eu o colocarei numa fenda da rocha e o cobrirei com a minha mão até que eu tenha acabado de passar.

[[v2-33-23]]

^<<v2-33-23,23>>^ Então tirarei a minha mão e você verá as minhas costas; mas a minha face ninguém poderá ver".

'''

xref:002-exodo/002-exodo-032.adoc#v2-32-0[&#60; Capítulo Anterior] | <<v2-33-0,Topo>> | xref:002-exodo/002-exodo-034.adoc#v2-34-0[Próximo Capítulo &#62;]