include::./index.adoc[]

[[v2-38-0]]
=== Êxodo, 38
// nvi ?, NVI - Nova Versão Internacional

[[v2-38-1]]

^<<v2-38-1,1>>^ Fez um altar de madeira de acácia para os holocaustos, com um metro e trinta e cinco centímetros de altura; era quadrado, com dois metros e vinte e cinco centímetros de cada lado.

[[v2-38-2]]

^<<v2-38-2,2>>^ E fez uma ponta em forma de chifre em cada um dos quatro cantos, formando uma só peça com o altar, o qual revestiu de bronze.

[[v2-38-3]]

^<<v2-38-3,3>>^ De bronze fez todos os seus utensílios: os recipientes para recolher cinzas, as pás, as bacias de aspersão, os garfos para carne e os braseiros.

[[v2-38-4]]

^<<v2-38-4,4>>^ Fez uma grelha de bronze para o altar em forma de rede, abaixo da sua beirada, a meia altura do altar.

[[v2-38-5]]

^<<v2-38-5,5>>^ Fundiu quatro argolas de bronze para sustentar as varas nos quatro cantos da grelha de bronze.

[[v2-38-6]]

^<<v2-38-6,6>>^ Fez as varas de madeira de acácia, revestiu-as de bronze

[[v2-38-7]]

^<<v2-38-7,7>>^ e colocou-as nas argolas, nos dois lados do altar, para que o pudessem carregar. O altar era oco, feito de tábuas.

[[v2-38-8]]

^<<v2-38-8,8>>^ Fez a bacia de bronze e a sua base com os espelhos das mulheres que serviam à entrada da Tenda do Encontro.

[[v2-38-9]]

^<<v2-38-9,9>>^ Fez também o pátio. O lado sul tinha quarenta e cinco metros de comprimento e cortinas externas de linho fino trançado,

[[v2-38-10]]

^<<v2-38-10,10>>^ com vinte colunas e vinte bases de bronze, com ganchos e ligaduras de prata nas colunas.

[[v2-38-11]]

^<<v2-38-11,11>>^ O lado norte também tinha quarenta e cinco metros de comprimento, com vinte colunas e vinte bases de bronze. Os ganchos e as ligaduras das colunas eram de prata.

[[v2-38-12]]

^<<v2-38-12,12>>^ O lado ocidental, com suas cortinas externas, tinha vinte e dois metros e meio de largura, com dez colunas e dez bases, com ganchos e ligaduras de prata nas colunas.

[[v2-38-13]]

^<<v2-38-13,13>>^ O lado oriental, que dá para o nascente, também tinha vinte e dois metros e meio de largura.

[[v2-38-14]]

^<<v2-38-14,14>>^ Havia cortinas de seis metros e setenta e cinco centímetros de comprimento num dos lados da entrada, com três colunas e três bases,

[[v2-38-15]]

^<<v2-38-15,15>>^ e cortinas de seis metros e setenta e cinco centímetros de comprimento no outro lado da entrada do pátio, também com três colunas e três bases.

[[v2-38-16]]

^<<v2-38-16,16>>^ Todas as cortinas ao redor do pátio eram feitas de linho fino trançado.

[[v2-38-17]]

^<<v2-38-17,17>>^ As bases das colunas eram de bronze. Os ganchos e as ligaduras das colunas eram de prata, e o topo das colunas também eram revestidos de prata; de modo que todas as colunas do pátio tinham ligaduras de prata.

[[v2-38-18]]

^<<v2-38-18,18>>^ Na entrada do pátio havia uma cortina de linho fino trançado e de fios de tecidos azul, roxo e vermelho, obra de bordador. Tinha nove metros de comprimento e, à semelhança das cortinas do pátio, tinha dois metros e vinte e cinco centímetros de altura,

[[v2-38-19]]

^<<v2-38-19,19>>^ com quatro colunas e quatro bases de bronze. Seus ganchos e ligaduras eram de prata, e o topo das colunas também era revestido de prata.

[[v2-38-20]]

^<<v2-38-20,20>>^ Todas as estacas da tenda do tabernáculo e do pátio que o rodeava eram de bronze.

[[v2-38-21]]

^<<v2-38-21,21>>^ Esta é a relação do material usado para o tabernáculo, o tabernáculo da aliança, registrada por ordem de Moisés pelos levitas, sob a direção de Itamar, filho de Arão, o sacerdote.

[[v2-38-22]]

^<<v2-38-22,22>>^ Bezalel, filho de Uri, neto de Hur, da tribo de Judá, fez tudo o que o Senhor tinha ordenado a Moisés.

[[v2-38-23]]

^<<v2-38-23,23>>^ Com ele estava Aoliabe, filho de Aisamaque, da tribo de Dã, artesão e projetista, e também bordador em linho fino e de fios de tecido azul, roxo e vermelho.

[[v2-38-24]]

^<<v2-38-24,24>>^ O peso total do ouro recebido na oferta movida e utilizado para a obra do santuário foi de uma tonelada, com base no peso padrão do santuário.

[[v2-38-25]]

^<<v2-38-25,25>>^ O peso da prata recebida dos que foram contados no recenseamento da comunidade foi superior a três toneladas e meia, com base no peso padrão do santuário:

[[v2-38-26]]

^<<v2-38-26,26>>^ seis gramas para cada um dos recenseados, seiscentos e três mil, quinhentos e cinqüenta homens de vinte anos de idade para cima.

[[v2-38-27]]

^<<v2-38-27,27>>^ As três toneladas e meia de prata foram usadas para fundir as bases do santuário e do véu: cem bases feitas das três toneladas e meia, trinta e cinco quilos para cada base.

[[v2-38-28]]

^<<v2-38-28,28>>^ Vinte quilos e trezentos gramas foram usados para fazer os ganchos para as colunas, para revestir a parte superior das colunas e para fazer as suas ligaduras.

[[v2-38-29]]

^<<v2-38-29,29>>^ O peso do bronze da oferta movida foi de duas toneladas e meia.

[[v2-38-30]]

^<<v2-38-30,30>>^ Ele o utilizou para fazer as bases da entrada da Tenda do Encontro, o altar de bronze, a sua grelha e todos os seus utensílios,

[[v2-38-31]]

^<<v2-38-31,31>>^ as bases do pátio ao redor e da sua entrada, e todas as estacas do tabernáculo e do pátio em derredor.

'''

xref:002-exodo/002-exodo-037.adoc#v2-37-0[&#60; Capítulo Anterior] | <<v2-38-0,Topo>> | xref:002-exodo/002-exodo-039.adoc#v2-39-0[Próximo Capítulo &#62;]