include::./index.adoc[]

[[v2-26-0]]
=== Êxodo, 26
// nvi ?, NVI - Nova Versão Internacional

[[v2-26-1]]

^<<v2-26-1,1>>^ "Faça o tabernáculo com dez cortinas internas de linho fino trançado e de fios de tecido azul, roxo e vermelho, e nelas mande bordar querubins.

[[v2-26-2]]

^<<v2-26-2,2>>^ Todas as cortinas internas terão a mesma medida: doze metros e sessenta centímetros de comprimento e um metro e oitenta centímetros de largura.

[[v2-26-3]]

^<<v2-26-3,3>>^ Prenda cinco dessas cortinas internas uma com a outra e faça o mesmo com as outra cinco.

[[v2-26-4]]

^<<v2-26-4,4>>^ Faça laçadas de tecido azul ao longo da borda da cortina interna, na extremidade do primeiro conjunto de cortinas internas; o mesmo será feito à cortina interna na extremidade do outro conjunto.

[[v2-26-5]]

^<<v2-26-5,5>>^ Faça cinqüenta laçadas numa cortina interna e cinqüenta laçadas na cortina interna que está na extremidade do outro conjunto, de modo que as laçadas estarão opostas umas às outras.

[[v2-26-6]]

^<<v2-26-6,6>>^ Faça também cinqüenta colchetes de ouro com os quais se prenderão as cortinas internas uma na outra, para que o tabernáculo seja um todo.

[[v2-26-7]]

^<<v2-26-7,7>>^ "Com o total de onze cortinas internas de pêlos de cabra faça uma tenda para cobrir o tabernáculo.

[[v2-26-8]]

^<<v2-26-8,8>>^ As onze cortinas internas terão o mesmo tamanho: treze metros e meio de comprimento e um metro e oitenta centímetros de largura.

[[v2-26-9]]

^<<v2-26-9,9>>^ Prenda de um lado cinco cortinas internas e também as outras seis do outro lado. Dobre em duas partes a sexta cortina interna na frente da tenda.

[[v2-26-10]]

^<<v2-26-10,10>>^ Faça cinqüenta laçadas ao longo da borda da cortina interna na extremidade do primeiro conjunto de cortinas, e também ao longo da borda da cortina interna do outro conjunto.

[[v2-26-11]]

^<<v2-26-11,11>>^ Em seguida faça cinqüenta colchetes de bronze e ponha-os nas laçadas para unir a tenda como um todo.

[[v2-26-12]]

^<<v2-26-12,12>>^ Quanto à sobra no comprimento das cortinas internas da tenda, a meia cortina interna que sobrar será pendurada na parte de trás do tabernáculo.

[[v2-26-13]]

^<<v2-26-13,13>>^ As dez cortinas internas serão quarenta e cinco centímetros mais compridas de cada lado; e o que sobrar será pendurado nos dois lados do tabernáculo, para cobri-lo.

[[v2-26-14]]

^<<v2-26-14,14>>^ Faça também para a tenda uma cobertura de pele de carneiro tingida de vermelho, e por cima desta uma cobertura de couro.

[[v2-26-15]]

^<<v2-26-15,15>>^ "Faça armações verticais de madeira de acácia para o tabernáculo.

[[v2-26-16]]

^<<v2-26-16,16>>^ Cada armação terá quatro metros e meio de comprimento por setenta centímetros de largura,

[[v2-26-17]]

^<<v2-26-17,17>>^ com dois encaixes paralelos um ao outro. Todas as armações do tabernáculo devem ser feitas dessa maneira.

[[v2-26-18]]

^<<v2-26-18,18>>^ Faça vinte armações para o lado sul do tabernáculo

[[v2-26-19]]

^<<v2-26-19,19>>^ e quarenta bases de prata debaixo delas: duas bases para cada armação, uma debaixo de cada encaixe.

[[v2-26-20]]

^<<v2-26-20,20>>^ Para o outro lado, o lado norte do tabernáculo, faça vinte armações

[[v2-26-21]]

^<<v2-26-21,21>>^ e quarenta bases de prata, duas debaixo de cada armação.

[[v2-26-22]]

^<<v2-26-22,22>>^ Faça seis armações para o lado ocidental do tabernáculo,

[[v2-26-23]]

^<<v2-26-23,23>>^ e duas armações na parte de trás, nos cantos.

[[v2-26-24]]

^<<v2-26-24,24>>^ As armações nesses dois cantos serão duplas, desde a parte inferior até a superior, colocadas numa única argola; ambas serão assim.

[[v2-26-25]]

^<<v2-26-25,25>>^ Desse modo, haverá oito armações e dezesseis bases de prata, duas debaixo de cada armação.

[[v2-26-26]]

^<<v2-26-26,26>>^ "Faça também travessões de madeira de acácia: cinco para as armações de um lado do tabernáculo,

[[v2-26-27]]

^<<v2-26-27,27>>^ cinco para as do outro lado e cinco para as do lado ocidental, na parte de trás do tabernáculo.

[[v2-26-28]]

^<<v2-26-28,28>>^ O travessão central se estenderá de uma extremidade à outra entre as armações.

[[v2-26-29]]

^<<v2-26-29,29>>^ Revista de ouro as armações e faça argolas de ouro para sustentar os travessões, os quais também terão que ser revestidos de ouro.

[[v2-26-30]]

^<<v2-26-30,30>>^ "Faça o tabernáculo de acordo com o modelo que lhe foi mostrado no monte.

[[v2-26-31]]

^<<v2-26-31,31>>^ "Faça um véu de linho fino trançado e de fios de tecido azul, roxo e vermelho, e mande bordar nele querubins.

[[v2-26-32]]

^<<v2-26-32,32>>^ Pendure-o com ganchos de ouro em quatro colunas de madeira de acácia revestidas de ouro e fincadas em quatro bases de prata.

[[v2-26-33]]

^<<v2-26-33,33>>^ Pendure o véu pelos colchetes e coloque atrás do véu a arca da aliança. O véu separará o Lugar Santo do Lugar Santíssimo.

[[v2-26-34]]

^<<v2-26-34,34>>^ Coloque a tampa sobre a arca da aliança no Lugar Santíssimo.

[[v2-26-35]]

^<<v2-26-35,35>>^ Coloque a mesa do lado de fora do véu, no lado norte do tabernáculo; e o candelabro em frente dela, no lado sul.

[[v2-26-36]]

^<<v2-26-36,36>>^ "Para a entrada da tenda faça uma cortina de linho fino trançado e de fios de tecido azul, roxo e vermelho, obra de bordador.

[[v2-26-37]]

^<<v2-26-37,37>>^ Faça ganchos de ouro para essa cortina e cinco colunas de madeira de acácia revestidas de ouro. Mande fundir para eles cinco bases de bronze. "

'''

xref:002-exodo/002-exodo-025.adoc#v2-25-0[&#60; Capítulo Anterior] | <<v2-26-0,Topo>> | xref:002-exodo/002-exodo-027.adoc#v2-27-0[Próximo Capítulo &#62;]