include::./index.adoc[]

[[v2-36-0]]
=== Êxodo, 36
// nvi ?, NVI - Nova Versão Internacional

[[v2-36-1]]

^<<v2-36-1,1>>^ "Assim farão Bezalel, Aoliabe e todos os homens capazes, a quem o Senhor concedeu destreza e habilidade para fazerem toda a obra de construção do santuário, realizarão a obra como o Senhor ordenou. "

[[v2-36-2]]

^<<v2-36-2,2>>^ Então Moisés chamou Bezalel e Aoliabe e todos os homens capazes a quem o Senhor dera habilidade e que estavam dispostos a vir realizar a obra.

[[v2-36-3]]

^<<v2-36-3,3>>^ Receberam de Moisés todas as ofertas que os israelitas tinham trazido para a obra de construção do santuário. E o povo continuava a trazer voluntariamente ofertas, manhã após manhã.

[[v2-36-4]]

^<<v2-36-4,4>>^ Por isso, todos os artesãos habilidosos que trabalhavam no santuário interromperam o trabalho

[[v2-36-5]]

^<<v2-36-5,5>>^ e disseram a Moisés: "O povo está trazendo mais do que o suficiente para realizar a obra que o Senhor ordenou".

[[v2-36-6]]

^<<v2-36-6,6>>^ Então Moisés ordenou que fosse feita esta proclamação em todo o acampamento: "Nenhum homem ou mulher deverá fazer mais nada para ser oferecido ao santuário". Assim, o povo foi impedido de trazer mais,

[[v2-36-7]]

^<<v2-36-7,7>>^ pois o que já haviam recebido era mais que suficiente para realizar toda a obra.

[[v2-36-8]]

^<<v2-36-8,8>>^ Todos os homens capazes dentre os trabalhadores fizeram o tabernáculo com dez cortinas internas de linho fino trançado e de fios de tecido azul, roxo e vermelho, com os querubins bordados sobre eles.

[[v2-36-9]]

^<<v2-36-9,9>>^ Todas as cortinas internas tinham o mesmo tamanho: doze metros e sessenta centímetros de comprimento por um metro e oitenta centímetros de largura.

[[v2-36-10]]

^<<v2-36-10,10>>^ Prendeu cinco cortinas internas, e fez o mesmo com as outras cinco.

[[v2-36-11]]

^<<v2-36-11,11>>^ Em seguida fez laçadas de tecido azul ao longo da borda da última cortina interna do primeiro conjunto de cortinas internas, fazendo o mesmo com o segundo conjunto.

[[v2-36-12]]

^<<v2-36-12,12>>^ Fez também cinqüenta laçadas na primeira cortina interna e cinqüenta laçadas na última cortina interna do segundo conjunto; as laçadas estavam opostas umas às outras.

[[v2-36-13]]

^<<v2-36-13,13>>^ Depois fez cinqüenta ganchos de ouro e com eles prendeu um conjunto de cortinas internas ao outro, para que o tabernáculo formasse um todo.

[[v2-36-14]]

^<<v2-36-14,14>>^ Com o total de onze cortinas internas de pêlos de cabra fez uma tenda para cobrir o tabernáculo.

[[v2-36-15]]

^<<v2-36-15,15>>^ As onze cortinas internas tinham a mesma medida: treze metros e meio de comprimento por um metro e oitenta centímetros de largura.

[[v2-36-16]]

^<<v2-36-16,16>>^ Prendeu cinco cortinas internas num conjunto e as outras seis noutro conjunto.

[[v2-36-17]]

^<<v2-36-17,17>>^ Depois fez cinqüenta laçadas em volta da borda da última cortina interna de um dos conjuntos e também na borda da última cortina interna do outro conjunto.

[[v2-36-18]]

^<<v2-36-18,18>>^ Fez também cinqüenta ganchos de bronze para unir a tenda, formando um todo.

[[v2-36-19]]

^<<v2-36-19,19>>^ Em seguida fez para a tenda uma cobertura de pele de carneiro tingida de vermelho, e por cima desta uma cobertura de couro.

[[v2-36-20]]

^<<v2-36-20,20>>^ Fez ainda armações verticais de madeira de acácia para o tabernáculo.

[[v2-36-21]]

^<<v2-36-21,21>>^ Cada armação tinha quatro metros e meio de comprimento por setenta centímetros de largura,

[[v2-36-22]]

^<<v2-36-22,22>>^ com dois encaixes paralelos um ao outro. E fez todas as armações do tabernáculo dessa madeira.

[[v2-36-23]]

^<<v2-36-23,23>>^ Fez também vinte armações para o lado sul do tabernáculo

[[v2-36-24]]

^<<v2-36-24,24>>^ e quarenta bases de prata para serem colocadas debaixo delas; duas bases para cada armação, uma debaixo de cada encaixe.

[[v2-36-25]]

^<<v2-36-25,25>>^ Para o outro lado, o lado norte do tabernáculo, fez vinte armações

[[v2-36-26]]

^<<v2-36-26,26>>^ e quarenta bases de prata, duas debaixo de cada armação.

[[v2-36-27]]

^<<v2-36-27,27>>^ Fez ainda seis armações na parte de trás do tabernáculo, isto é, para o lado ocidental,

[[v2-36-28]]

^<<v2-36-28,28>>^ e duas armações foram montadas nos cantos, na parte de trás do tabernáculo.

[[v2-36-29]]

^<<v2-36-29,29>>^ Nesses dois cantos as armações eram duplas, desde a parte inferior até a mais alta, colocadas numa só argola, ambas feitas do mesmo modo.

[[v2-36-30]]

^<<v2-36-30,30>>^ Havia, pois, oito armações e dezesseis bases de prata, duas debaixo de cada armação.

[[v2-36-31]]

^<<v2-36-31,31>>^ Também fez travessões de madeira de acácia: cinco para as armações de um lado do tabernáculo,

[[v2-36-32]]

^<<v2-36-32,32>>^ cinco para as do outro lado e cinco para as do lado ocidental, na parte de trás do tabernáculo.

[[v2-36-33]]

^<<v2-36-33,33>>^ Fez o travessão central de uma extremidade à outra, passando pelo meio das armações.

[[v2-36-34]]

^<<v2-36-34,34>>^ Revestiu de ouro as armações e fez argolas de ouro para sustentar os travessões, os quais também revestiu de ouro.

[[v2-36-35]]

^<<v2-36-35,35>>^ Fez o véu de linho fino trançado e de fios de tecido azul, roxo e vermelho, e mandou bordar nele querubins.

[[v2-36-36]]

^<<v2-36-36,36>>^ Fez-lhe quatro colunas de madeira de acácia e as revestiu de ouro. Fez-lhe ainda ganchos de ouro e fundiu as suas bases de prata.

[[v2-36-37]]

^<<v2-36-37,37>>^ Para a entrada da tenda fez uma cortina de linho fino trançado e de fios de tecido azul, roxo e vermelho, obra de bordador;

[[v2-36-38]]

^<<v2-36-38,38>>^ e fez-lhe cinco colunas com ganchos. Revestiu de ouro as partes superior e lateral das colunas e fez de bronze as suas cinco bases.

'''

xref:002-exodo/002-exodo-035.adoc#v2-35-0[&#60; Capítulo Anterior] | <<v2-36-0,Topo>> | xref:002-exodo/002-exodo-037.adoc#v2-37-0[Próximo Capítulo &#62;]