include::./index.adoc[]

[[v2-6-0]]
=== Êxodo, 6
// nvi ?, NVI - Nova Versão Internacional

[[v2-6-1]]

^<<v2-6-1,1>>^ Então o Senhor disse a Moisés: "Agora você verá o que farei ao faraó: Por minha mão poderosa, ele os deixará ir; por minha mão poderosa, ele os expulsará do seu país".

[[v2-6-2]]

^<<v2-6-2,2>>^ Disse Deus ainda a Moisés: "Eu sou o Senhor.

[[v2-6-3]]

^<<v2-6-3,3>>^ Apareci a Abraão, a Isaque e a Jacó como o Deus Todo-poderoso, mas pelo meu nome, o Senhor, não me revelei a eles.

[[v2-6-4]]

^<<v2-6-4,4>>^ Depois estabeleci com eles a minha aliança para dar-lhes a terra de Canaã, terra onde viveram como estrangeiros.

[[v2-6-5]]

^<<v2-6-5,5>>^ E agora ouvi o lamento dos israelitas, a quem os egípcios mantêm escravos, e lembrei-me da minha aliança.

[[v2-6-6]]

^<<v2-6-6,6>>^ "Por isso, diga aos israelitas: Eu sou o Senhor. Eu os livrarei do trabalho imposto pelos egípcios. Eu os libertarei da escravidão e os resgatarei com braço forte e com poderosos atos de juízo.

[[v2-6-7]]

^<<v2-6-7,7>>^ Eu os farei meu povo e serei o Deus de vocês. Então vocês saberão que eu sou o Senhor, o Deus de vocês, que os livra do trabalho imposto pelos egípcios.

[[v2-6-8]]

^<<v2-6-8,8>>^ E os farei entrar na terra que, com mão levantada, jurei que daria a Abraão, a Isaque e a Jacó. Eu a darei a vocês como propriedade. Eu sou o Senhor".

[[v2-6-9]]

^<<v2-6-9,9>>^ Moisés declarou isso aos israelitas, mas eles não lhe deram ouvidos, por causa da angústia e da cruel escravidão que sofriam.

[[v2-6-10]]

^<<v2-6-10,10>>^ Então o Senhor ordenou a Moisés:

[[v2-6-11]]

^<<v2-6-11,11>>^ "Vá dizer ao faraó, rei do Egito, que deixe os israelitas saírem do país".

[[v2-6-12]]

^<<v2-6-12,12>>^ Moisés, porém, disse na presença do Senhor: "Se os israelitas não me dão ouvidos, como me ouvirá o faraó? Ainda mais que não tenho facilidade para falar! "

[[v2-6-13]]

^<<v2-6-13,13>>^ Mas, o Senhor ordenou a Moisés e a Arão que dissessem aos israelitas e ao faraó, rei do Egito, que tinham ordem para tirar do Egito os israelitas.

[[v2-6-14]]

^<<v2-6-14,14>>^ Estes foram os chefes das famílias israelitas: Os filhos de Rúben, filho mais velho de Israel, foram: Enoque, Palu, Hezrom e Carmi. Esses foram os clãs de Rúben.

[[v2-6-15]]

^<<v2-6-15,15>>^ Os filhos de Simeão foram: Jemuel, Jamim, Oade, Jaquim, Zoar e Saul, filho de uma cananéia. Esses foram os clãs de Simeão.

[[v2-6-16]]

^<<v2-6-16,16>>^ Estes, pois, são os nomes dos filhos de Levi, por ordem de nascimento: Gérson, Coate e Merari. Levi viveu cento e trinta e sete anos.

[[v2-6-17]]

^<<v2-6-17,17>>^ Os filhos de Gérson, conforme seus clãs, foram Libni e Simei.

[[v2-6-18]]

^<<v2-6-18,18>>^ Os filhos de Coate foram Anrão, Isar, Hebrom e Uziel. Coate viveu cento e trinta e três anos.

[[v2-6-19]]

^<<v2-6-19,19>>^ Os filhos de Merari foram Mali e Musi. Esses foram os clãs de Levi, por ordem de nascimento.

[[v2-6-20]]

^<<v2-6-20,20>>^ Anrão tomou por mulher sua tia Joquebede, que lhe deu à luz Arão e Moisés. Anrão viveu cento e trinta e sete anos.

[[v2-6-21]]

^<<v2-6-21,21>>^ Os filhos de Isar foram Corá, Nefegue e Zicri.

[[v2-6-22]]

^<<v2-6-22,22>>^ Os filhos de Uziel foram Misael, Elzafã e Sitri.

[[v2-6-23]]

^<<v2-6-23,23>>^ Arão tomou por mulher a Eliseba, filha de Aminadabe, irmã de Naassom, e ela lhe deu à luz Nadabe, Abiú, Eleazar e Itamar.

[[v2-6-24]]

^<<v2-6-24,24>>^ Os filhos de Corá foram Assir, Elcana e Abiasafe. Esses foram os clãs dos coraítas.

[[v2-6-25]]

^<<v2-6-25,25>>^ Eleazar, filho de Arão, tomou por mulher uma das filhas de Futiel, e ela lhe deu à luz Finéias. Esses foram os chefes das famílias dos levitas, conforme seus clãs.

[[v2-6-26]]

^<<v2-6-26,26>>^ Foi a este Arão e a este Moisés que o Senhor disse: "Tirem os israelitas do Egito, organizados segundo as suas divisões".

[[v2-6-27]]

^<<v2-6-27,27>>^ Foram eles, Moisés e Arão, que falaram ao faraó, rei do Egito, a fim de tirar os israelitas do Egito.

[[v2-6-28]]

^<<v2-6-28,28>>^ Ora, quando o Senhor falou com Moisés no Egito,

[[v2-6-29]]

^<<v2-6-29,29>>^ disse-lhe: "Eu sou o Senhor. Diga ao faraó, rei do Egito, tudo o que eu lhe disser".

[[v2-6-30]]

^<<v2-6-30,30>>^ Moisés, porém, perguntou ao Senhor: "Como o faraó me dará ouvidos, se não tenho facilidade para falar? "

'''

xref:002-exodo/002-exodo-005.adoc#v2-5-0[&#60; Capítulo Anterior] | <<v2-6-0,Topo>> | xref:002-exodo/002-exodo-007.adoc#v2-7-0[Próximo Capítulo &#62;]