include::./index.adoc[]

[[v7-21-0]]
=== Juízes, 21
// nvi ?, NVI - Nova Versão Internacional

[[v7-21-1]]

^<<v7-21-1,1>>^ Os homens de Israel tinham feito este juramento em Mispá: "Nenhum de nós dará sua filha em casamento a um benjamita".

[[v7-21-2]]

^<<v7-21-2,2>>^ O povo foi a Betel, onde esteve sentado perante o Senhor até à tarde, chorando bem alto e amargamente.

[[v7-21-3]]

^<<v7-21-3,3>>^ "Ó Senhor, Deus de Israel", lamentaram, "por que aconteceu isso em Israel? Por que teria que faltar hoje uma tribo em Israel? "

[[v7-21-4]]

^<<v7-21-4,4>>^ Na manhã do dia seguinte o povo se levantou cedo, construiu um altar e apresentou holocaustos e ofertas de comunhão.

[[v7-21-5]]

^<<v7-21-5,5>>^ Os israelitas perguntaram: "Quem dentre todas as tribos de Israel deixou de vir à assembléia perante o Senhor? " Pois tinham feito um juramento solene de que qualquer que deixasse de se reunir perante o Senhor em Mispá seria morto.

[[v7-21-6]]

^<<v7-21-6,6>>^ Os israelitas prantearam pelos seus irmãos benjamitas. "Hoje uma tribo foi eliminada de Israel", diziam.

[[v7-21-7]]

^<<v7-21-7,7>>^ "Como poderemos conseguir mulheres para os sobreviventes, visto que juramos pelo Senhor não lhes dar em casamento nenhuma de nossas filhas? "

[[v7-21-8]]

^<<v7-21-8,8>>^ Então perguntaram: "Qual das tribos de Israel deixou de reunir-se perante o Senhor em Mispá? " Descobriu-se então que ninguém de Jabes-Gileade tinha vindo ao acampamento para a assembléia.

[[v7-21-9]]

^<<v7-21-9,9>>^ Quando contaram o povo, verificaram que ninguém do povo de Jabes-Gileade estava ali.

[[v7-21-10]]

^<<v7-21-10,10>>^ Então a comunidade enviou doze mil homens de guerra com instruções para irem a Jabes-Gileade e matarem à espada todos os que viviam lá, inclusive mulheres e crianças.

[[v7-21-11]]

^<<v7-21-11,11>>^ "É isto o que vocês deverão fazer", disseram, "matem todos os homens e todas as mulheres que não forem virgens".

[[v7-21-12]]

^<<v7-21-12,12>>^ Entre o povo que vivia em Jabes-Gileade encontraram quatrocentas moças virgens e as levaram para o acampamento de Siló, em Canaã.

[[v7-21-13]]

^<<v7-21-13,13>>^ Depois a comunidade toda enviou uma oferta de comunhão aos benjamitas que estavam na rocha de Rimom.

[[v7-21-14]]

^<<v7-21-14,14>>^ Os benjamitas voltaram naquela ocasião e receberam as mulheres de Jabes-Gileade que tinham sido poupadas. Mas não havia suficientes mulheres para todos eles.

[[v7-21-15]]

^<<v7-21-15,15>>^ O povo pranteou Benjamim, pois o Senhor tinha aberto uma lacuna nas tribos de Israel.

[[v7-21-16]]

^<<v7-21-16,16>>^ E os líderes da comunidade disseram: "Mortas as mulheres de Benjamim, como conseguiremos mulheres para os homens que restaram?

[[v7-21-17]]

^<<v7-21-17,17>>^ Os benjamitas sobreviventes precisam ter herdeiros, para que uma tribo de Israel não seja destruída.

[[v7-21-18]]

^<<v7-21-18,18>>^ Não podemos dar-lhes nossas filhas em casamento, pois nós israelitas fizemos este juramento: Maldito seja todo aquele que der mulher a um benjamita.

[[v7-21-19]]

^<<v7-21-19,19>>^ Há, porém, a festa anual do Senhor em Siló, ao norte de Betel, a leste da estrada que vai de Betel a Siquém, e ao sul de Lebona".

[[v7-21-20]]

^<<v7-21-20,20>>^ Então mandaram para lá os benjamitas, dizendo: "Vão, escondam-se nas vinhas

[[v7-21-21]]

^<<v7-21-21,21>>^ e fiquem observando. Quando as moças de Siló forem para as danças, saiam correndo das vinhas e cada um de vocês apodere-se de uma das moças de Siló e vá para a terra de Benjamim.

[[v7-21-22]]

^<<v7-21-22,22>>^ Quando os pais ou irmãos delas se queixarem a nós diremos: Tenham misericórdia deles, pois não conseguimos mulheres para eles durante a guerra, e vocês são inocentes, visto que não lhes deram suas filhas".

[[v7-21-23]]

^<<v7-21-23,23>>^ Foi o que os benjamitas fizeram. Quando as moças estavam dançando, cada homem tomou uma para fazer dela sua mulher. Depois voltaram para a sua herança, reconstruíram as cidades e se estabeleceram nelas.

[[v7-21-24]]

^<<v7-21-24,24>>^ Na mesma ocasião os israelitas saíram daquele local e voltaram para as suas tribos e para os seus clãs, cada um para a sua própria herança.

[[v7-21-25]]

^<<v7-21-25,25>>^ Naquela época não havia rei em Israel; cada um fazia o que lhe parecia certo.

'''

xref:007-juizes/007-juizes-020.adoc#v7-20-0[&#60; Capítulo Anterior] | <<v7-21-0,Topo>> | xref:008-rute/008-rute-001.adoc#v8-1-0[Próximo Capítulo &#62;]