include::./index.adoc[]

[[v7-17-0]]
=== Juízes, 17
// nvi ?, NVI - Nova Versão Internacional

[[v7-17-1]]

^<<v7-17-1,1>>^ Havia um homem chamado Mica, dos montes de Efraim,

[[v7-17-2]]

^<<v7-17-2,2>>^ que disse certa vez à sua mãe: "Os treze quilos de prata que lhe foram roubados e pelos quais eu a ouvi pronunciar uma maldição. Na verdade a prata está comigo; eu a peguei". Disse-lhe sua mãe: "O Senhor o abençoe, meu filho! "

[[v7-17-3]]

^<<v7-17-3,3>>^ Quando ele devolveu os treze quilos de prata à mãe, ela disse: "Consagro solenemente a minha prata ao Senhor para que o meu filho faça uma imagem esculpida e um ídolo de metal. Eu a devolvo a você".

[[v7-17-4]]

^<<v7-17-4,4>>^ Mas ele devolveu a prata à sua mãe, e ela separou dois quilos e quatrocentos gramas, e os deu a um ourives, que deles fez a imagem e o ídolo. E estes foram postos na casa de Mica.

[[v7-17-5]]

^<<v7-17-5,5>>^ Ora, esse homem, Mica, possuía um santuário, e fez um manto sacerdotal e alguns ídolos da família e pôs um dos seus filhos como seu sacerdote.

[[v7-17-6]]

^<<v7-17-6,6>>^ Naquela época não havia rei em Israel; cada um fazia o que lhe parecia certo.

[[v7-17-7]]

^<<v7-17-7,7>>^ Um jovem levita de Belém de Judá, procedente do clã de Judá,

[[v7-17-8]]

^<<v7-17-8,8>>^ saiu daquela cidade em busca de outro lugar para morar. Em sua viagem, chegou à casa de Mica, nos montes de Efraim.

[[v7-17-9]]

^<<v7-17-9,9>>^ Mica lhe perguntou: "De onde você vem? " "Sou levita, de Belém de Judá", respondeu ele. "Estou procurando um lugar para morar. "

[[v7-17-10]]

^<<v7-17-10,10>>^ "Fique comigo", disse-lhe Mica. "Seja meu pai e sacerdote, e eu lhe darei cento e vinte gramas de prata por ano, roupas e comida. "

[[v7-17-11]]

^<<v7-17-11,11>>^ O jovem levita concordou em ficar com Mica, e tornou-se como um dos seus filhos.

[[v7-17-12]]

^<<v7-17-12,12>>^ Mica acolheu o levita, e o jovem se tornou seu sacerdote, e ficou morando em sua casa.

[[v7-17-13]]

^<<v7-17-13,13>>^ E Mica disse: "Agora sei que o Senhor me tratará com bondade, pois esse levita se tornou meu sacerdote".

'''

xref:007-juizes/007-juizes-016.adoc#v7-16-0[&#60; Capítulo Anterior] | <<v7-17-0,Topo>> | xref:007-juizes/007-juizes-018.adoc#v7-18-0[Próximo Capítulo &#62;]