include::./index.adoc[]

[[v7-15-0]]
=== Juízes, 15
// nvi ?, NVI - Nova Versão Internacional

[[v7-15-1]]

^<<v7-15-1,1>>^ Algum tempo depois, na época da colheita do trigo, Sansão foi visitar a sua mulher e levou-lhe um cabrito. "Vou ao quarto da minha mulher", disse ele. Mas o pai dela não quis deixá-lo entrar.

[[v7-15-2]]

^<<v7-15-2,2>>^ "Eu estava tão certo de que você a odiava", disse ele, "que a dei ao seu amigo. A sua irmã mais nova não é mais bonita? Fique com esta no lugar da irmã".

[[v7-15-3]]

^<<v7-15-3,3>>^ Sansão lhes disse: "Desta vez ninguém poderá me culpar quando acertar as contas com os filisteus! "

[[v7-15-4]]

^<<v7-15-4,4>>^ Então saiu, capturou trezentas raposas e as amarrou aos pares pela cauda. Depois prendeu uma tocha em cada par de caudas,

[[v7-15-5]]

^<<v7-15-5,5>>^ acendeu as tochas e soltou as raposas no meio das plantações dos filisteus. Assim ele queimou os feixes, o cereal que iam colher, e também as vinhas e os olivais.

[[v7-15-6]]

^<<v7-15-6,6>>^ Os filisteus perguntaram: "Quem fez isso? ", responderam-lhes: "Foi Sansão, o genro do timnita, porque a sua mulher foi dada ao seu amigo". Então os filisteus foram e queimaram a mulher e seu pai.

[[v7-15-7]]

^<<v7-15-7,7>>^ Sansão lhes disse: "Já que fizeram isso, não sossegarei enquanto não me vingar de vocês".

[[v7-15-8]]

^<<v7-15-8,8>>^ Ele os atacou sem dó nem piedade e fez terrível matança. Depois desceu e ficou numa caverna da rocha de Etã.

[[v7-15-9]]

^<<v7-15-9,9>>^ Os filisteus foram para Judá e lá acamparam, espalhando-se pelas proximidades de Leí.

[[v7-15-10]]

^<<v7-15-10,10>>^ Os homens de Judá perguntaram: "Por que vocês vieram lutar contra nós? " Eles responderam: "Queremos levar Sansão amarrado, para tratá-lo como ele nos tratou".

[[v7-15-11]]

^<<v7-15-11,11>>^ Três mil homens de Judá desceram então à caverna da rocha de Etã e disseram a Sansão: "Você não sabe que os filisteus dominam sobre nós? Você viu o que nos fez? " Ele respondeu: "Fiz a eles apenas o que eles me fizeram".

[[v7-15-12]]

^<<v7-15-12,12>>^ Disseram-lhe: "Viemos amarrá-lo para entregá-lo aos filisteus". Sansão disse: "Jurem-me que vocês mesmos não me matarão".

[[v7-15-13]]

^<<v7-15-13,13>>^ "Certamente que não! ", responderam. "Somente vamos amarrá-lo e entregá-lo nas mãos deles. Não o mataremos. " E o prenderam com duas cordas novas e o fizeram sair da rocha.

[[v7-15-14]]

^<<v7-15-14,14>>^ Quando ia chegando a Leí, os filisteus foram ao encontro dele aos gritos. Mas o Espírito do Senhor apossou-se dele. As cordas em seus braços se tornaram como fibra de linho queimada, e os laços caíram das suas mãos.

[[v7-15-15]]

^<<v7-15-15,15>>^ Encontrando a carcaça de um jumento, pegou a queixada e com ela matou mil homens.

[[v7-15-16]]

^<<v7-15-16,16>>^ Disse ele então: "Com uma queixada de jumento fiz deles montões. Com uma queixada de jumento matei mil homens".

[[v7-15-17]]

^<<v7-15-17,17>>^ Quando acabou de falar, jogou fora a queixada; e o local foi chamado Ramate-Leí.

[[v7-15-18]]

^<<v7-15-18,18>>^ Sansão estava com muita sede e clamou ao Senhor: "Deste pela mão de teu servo esta grande vitória. Morrerei eu agora de sede para cair nas mãos dos incircuncisos? "

[[v7-15-19]]

^<<v7-15-19,19>>^ Deus então abriu a rocha que há em Leí, e dela saiu água. Sansão bebeu, suas forças voltaram, e ele recobrou o ânimo. Por esse motivo essa fonte foi chamada En-Hacoré, e ainda lá está, em Leí.

[[v7-15-20]]

^<<v7-15-20,20>>^ Sansão liderou Israel durante vinte anos no tempo do domínio dos filisteus.

'''

xref:007-juizes/007-juizes-014.adoc#v7-14-0[&#60; Capítulo Anterior] | <<v7-15-0,Topo>> | xref:007-juizes/007-juizes-016.adoc#v7-16-0[Próximo Capítulo &#62;]