include::./index.adoc[]

[[v7-7-0]]
=== Juízes, 7
// nvi ?, NVI - Nova Versão Internacional

[[v7-7-1]]

^<<v7-7-1,1>>^ De madrugada Jerubaal, isto é, Gideão, e todo o seu exército acampou junto à fonte de Harode. O acampamento de Midiã estava ao norte deles, no vale, perto do monte Moré.

[[v7-7-2]]

^<<v7-7-2,2>>^ E o Senhor disse a Gideão: "Você tem gente demais, para eu entregar Midiã nas suas mãos. A fim de que Israel não se orgulhe contra mim, dizendo que a sua própria força o libertou,

[[v7-7-3]]

^<<v7-7-3,3>>^ anuncie, pois, ao povo que todo aquele que estiver tremendo de medo poderá ir embora do monte Gileade". Então vinte e dois mil homens partiram, e ficaram apenas dez mil.

[[v7-7-4]]

^<<v7-7-4,4>>^ Mas o Senhor tornou a dizer a Gideão: "Ainda há gente demais. Desça com eles à beira d’água, e eu separarei os que ficarão com você. Se eu disser: Este irá com você, ele irá; mas, se eu disser: Este não irá com você, ele não irá".

[[v7-7-5]]

^<<v7-7-5,5>>^ Assim Gideão levou os homens à beira d’água, e o Senhor lhe disse: "Separe os que beberem a água lambendo-a como faz o cachorro, daqueles que se ajoelharem para beber".

[[v7-7-6]]

^<<v7-7-6,6>>^ O número dos que lamberam a água levando-a com as mãos à boca foi de trezentos homens. Todos os demais se ajoelharam para beber.

[[v7-7-7]]

^<<v7-7-7,7>>^ O Senhor disse a Gideão: "Com os trezentos homens que lamberam a água livrarei vocês e entregarei os midianitas nas suas mãos. Mande para casa todos os outros homens".

[[v7-7-8]]

^<<v7-7-8,8>>^ Gideão mandou os israelitas para as suas tendas, mas reteve os trezentos. E estes ficaram com as provisões e as trombetas dos que partiram. O acampamento de Midiã ficava abaixo deles, no vale.

[[v7-7-9]]

^<<v7-7-9,9>>^ Naquela noite o Senhor disse a Gideão: "Levante-se, e desça ao acampamento, pois vou entregá-lo nas suas mãos.

[[v7-7-10]]

^<<v7-7-10,10>>^ Se você está com medo de atacá-los, desça ao acampamento com o seu servo Pura

[[v7-7-11]]

^<<v7-7-11,11>>^ e ouça o que estiverem dizendo. Depois disso você terá coragem para atacar". Então ele e o seu servo Pura desceram até os postos avançados do acampamento.

[[v7-7-12]]

^<<v7-7-12,12>>^ Os midianitas, os amalequitas e todos os outros povos que vinham do leste haviam se instalado no vale; eram numerosos como nuvens de gafanhotos. Assim como não se pode contar a areia da praia, também não se podia contar os seus camelos.

[[v7-7-13]]

^<<v7-7-13,13>>^ Gideão chegou bem no momento em que um homem estava contando seu sonho a um amigo. "Tive um sonho", dizia ele. "Um pão de cevada vinha rolando dentro do acampamento midianita, e atingiu a tenda com tanta força que ela tombou e se desmontou".

[[v7-7-14]]

^<<v7-7-14,14>>^ Seu amigo respondeu: "Não pode ser outra coisa senão a espada de Gideão, filho de Joás, o israelita. Deus entregou os midianitas e todo o acampamento nas mãos dele".

[[v7-7-15]]

^<<v7-7-15,15>>^ Quando Gideão ouviu o sonho e a sua interpretação, adorou a Deus. Voltou para o acampamento de Israel e gritou: "Levantem-se! O Senhor entregou o acampamento midianita nas suas mãos".

[[v7-7-16]]

^<<v7-7-16,16>>^ Dividiu os trezentos homens em três companhias, pôs nas mãos de todos eles trombetas e jarros vazios, com tochas dentro.

[[v7-7-17]]

^<<v7-7-17,17>>^ E ele lhes disse: "Observem-me. Façam o que eu fizer. Quando eu chegar à extremidade do acampamento, façam o que eu fizer.

[[v7-7-18]]

^<<v7-7-18,18>>^ Quando eu e todos os que estiverem comigo tocarmos as nossas trombetas ao redor do acampamento, toquem as suas, e gritem: Pelo Senhor e por Gideão! "

[[v7-7-19]]

^<<v7-7-19,19>>^ Gideão e os cem homens que o acompanhavam chegaram aos postos avançados do acampamento pouco depois da meia noite, assim que foram trocadas as sentinelas. Tocaram as suas trombetas e quebraram os jarros que tinham nas mãos;

[[v7-7-20]]

^<<v7-7-20,20>>^ as três companhias tocaram as trombetas e despedaçaram os jarros. Empunhando as tochas com a mão esquerda e as trombetas com a direita, gritaram: "À espada, pelo Senhor e por Gideão! "

[[v7-7-21]]

^<<v7-7-21,21>>^ Cada homem mantinha a sua posição em torno do acampamento, e todos os midianitas fugiam correndo e gritando.

[[v7-7-22]]

^<<v7-7-22,22>>^ Quando as trezentas trombetas soaram, o Senhor fez que em todo o acampamento os homens se voltassem uns contra os outros com as suas espadas. Mas muitos fugiram para Bete-Sita, na direção de Zererá, até a fronteira de Abel-Meolá, perto de Tabate.

[[v7-7-23]]

^<<v7-7-23,23>>^ Os israelitas de Naftali, de Aser e de todo o Manassés foram convocados, e perseguiram os midianitas.

[[v7-7-24]]

^<<v7-7-24,24>>^ Gideão enviou mensageiros a todos os montes de Efraim, dizendo: "Desçam para atacar os midianitas e cerquem as águas do Jordão à frente deles até Bete-Bara". Foram, pois, convocados todos os homens de Efraim, e eles ocuparam as águas do Jordão até Bete-Bara.

[[v7-7-25]]

^<<v7-7-25,25>>^ Eles prenderam dois líderes midianitas, Orebe e Zeebe. Mataram Orebe na rocha de Orebe, e Zeebe no tanque de prensar uvas de Zeebe. E, depois de perseguir os midianitas, trouxeram a cabeça de Orebe e a de Zeebe a Gideão, que estava do outro lado do Jordão.

'''

xref:007-juizes/007-juizes-006.adoc#v7-6-0[&#60; Capítulo Anterior] | <<v7-7-0,Topo>> | xref:007-juizes/007-juizes-008.adoc#v7-8-0[Próximo Capítulo &#62;]