include::./index.adoc[]

[[v7-1-0]]
=== Juízes, 1
// nvi ?, NVI - Nova Versão Internacional

[[v7-1-1]]

^<<v7-1-1,1>>^ Depois da morte de Josué, os israelitas perguntaram ao Senhor: "Quem de nós será o primeiro a atacar os cananeus? "

[[v7-1-2]]

^<<v7-1-2,2>>^ O Senhor respondeu: "Judá será o primeiro; eu entreguei a terra em suas mãos".

[[v7-1-3]]

^<<v7-1-3,3>>^ Então os homens de Judá disseram aos seus irmãos de Simeão: "Venham conosco ao território que nos foi designado por sorteio, e lutemos contra os cananeus. Iremos com vocês para o território que lhes foi dado". E os homens de Simeão foram com eles.

[[v7-1-4]]

^<<v7-1-4,4>>^ Quando os homens de Judá atacaram, o Senhor entregou os cananeus e os ferezeus nas mãos deles, e eles mataram dez mil homens em Bezeque.

[[v7-1-5]]

^<<v7-1-5,5>>^ Foi lá que encontraram Adoni-Bezeque, lutaram contra ele e derrotaram os cananeus e os ferezeus.

[[v7-1-6]]

^<<v7-1-6,6>>^ Adoni-Bezeque fugiu, mas eles o perseguiram e o prenderam, e lhe cortaram os polegares das mãos e dos pés.

[[v7-1-7]]

^<<v7-1-7,7>>^ Então Adoni-Bezeque disse: "Setenta reis com os polegares das mãos e dos pés cortados apanhavam migalhas debaixo da minha mesa. Agora Deus me retribuiu por aquilo que lhes fiz". Eles o levaram para Jerusalém, onde morreu.

[[v7-1-8]]

^<<v7-1-8,8>>^ Os homens de Judá atacaram também Jerusalém e a conquistaram. Mataram seus habitantes ao fio da espada e a incendiaram.

[[v7-1-9]]

^<<v7-1-9,9>>^ Depois disso eles desceram para lutar contra os cananeus que viviam na serra, no Neguebe e na Sefelá.

[[v7-1-10]]

^<<v7-1-10,10>>^ Avançaram contra os cananeus que viviam em Hebrom, anteriormente chamada Quiriate-Arba, e derrotaram Sesai, Aimã e Talmai.

[[v7-1-11]]

^<<v7-1-11,11>>^ Dali avançaram contra o povo que morava em Debir, anteriormente chamada Quiriate-Sefer.

[[v7-1-12]]

^<<v7-1-12,12>>^ E disse Calebe: "Darei minha filha Acsa em casamento ao homem que atacar e conquistar Quiriate-Sefer".

[[v7-1-13]]

^<<v7-1-13,13>>^ Otoniel, filho de Quenaz, irmão mais novo de Calebe, conquistou a cidade; por isso Calebe lhe deu sua filha Acsa por mulher.

[[v7-1-14]]

^<<v7-1-14,14>>^ Um dia, quando já vivia com Otoniel, ela o persuadiu a pedir um campo ao pai dela. Assim que ela desceu do jumento, Calebe lhe perguntou: "O que você quer? "

[[v7-1-15]]

^<<v7-1-15,15>>^ Ela respondeu: "Dê-me um presente. Já que o senhor me deu terras no Neguebe, dê-me também fontes de água". Assim Calebe lhe deu as fontes superiores e as inferiores.

[[v7-1-16]]

^<<v7-1-16,16>>^ Os descendentes do sogro de Moisés, o queneu, saíram da Cidade das Palmeiras com os homens de Judá e passaram a viver entre o povo do deserto de Judá, no Neguebe, perto de Arade.

[[v7-1-17]]

^<<v7-1-17,17>>^ Depois os homens de Judá foram com seus irmãos de Simeão e derrotaram os cananeus que viviam em Zefate, e destruíram totalmente a cidade. Por essa razão ela foi chamada Hormá.

[[v7-1-18]]

^<<v7-1-18,18>>^ Os homens de Judá também conquistaram Gaza, Ascalom e Ecrom, com os seus territórios.

[[v7-1-19]]

^<<v7-1-19,19>>^ O Senhor estava com os homens de Judá. Eles ocuparam a serra central, mas não conseguiram expulsar os habitantes dos vales, pois estes possuíam carros de guerra feitos de ferro.

[[v7-1-20]]

^<<v7-1-20,20>>^ Conforme Moisés havia prometido, Hebrom foi dada a Calebe, que expulsou de lá os três filhos de Enaque.

[[v7-1-21]]

^<<v7-1-21,21>>^ Já os benjamitas deixaram de expulsar os jebuseus que estavam morando em Jerusalém. Os jebuseus vivem ali com os benjamitas até o dia de hoje.

[[v7-1-22]]

^<<v7-1-22,22>>^ Os homens das tribos de José, por sua vez, atacaram Betel, e o Senhor estava com eles.

[[v7-1-23]]

^<<v7-1-23,23>>^ Enviaram espias a Betel, anteriormente chamada Luz.

[[v7-1-24]]

^<<v7-1-24,24>>^ Quando os espias viram um homem saindo da cidade disseram-lhe: "Mostre-nos como entrar na cidade, e nós lhe pouparemos a vida".

[[v7-1-25]]

^<<v7-1-25,25>>^ Ele mostrou como entrar, e eles mataram os habitantes da cidade ao fio da espada, mas pouparam o homem e toda a sua família.

[[v7-1-26]]

^<<v7-1-26,26>>^ Ele foi, então, para a terra dos hititas, onde fundou uma cidade e lhe deu o nome de Luz, que é o seu nome até o dia de hoje.

[[v7-1-27]]

^<<v7-1-27,27>>^ Manassés, porém, não expulsou o povo de Bete-Seã nem o de Taanaque nem o de Dor nem o de Ibleã nem o de Megido, nem tampouco o dos povoados ao redor dessas cidades, pois os cananeus estavam decididos a permanecer naquela terra.

[[v7-1-28]]

^<<v7-1-28,28>>^ Quando Israel se tornou forte, impôs trabalhos forçados aos cananeus, mas não os expulsou completamente.

[[v7-1-29]]

^<<v7-1-29,29>>^ Efraim também não expulsou os cananeus que viviam em Gezer, mas os cananeus continuaram a viver entre eles.

[[v7-1-30]]

^<<v7-1-30,30>>^ Nem Zebulom expulsou os cananeus que viviam em Quitrom e em Naalol, mas estes permaneceram entre eles, e foram submetidos a trabalhos forçados.

[[v7-1-31]]

^<<v7-1-31,31>>^ Nem Aser expulsou os que viviam em Aco, Sidom, Alabe, Aczibe, Helba, Afeque e Reobe,

[[v7-1-32]]

^<<v7-1-32,32>>^ e, por esse motivo, o povo de Aser vivia entre os cananeus que habitavam naquela terra.

[[v7-1-33]]

^<<v7-1-33,33>>^ Nem Naftali expulsou os que viviam em Bete-Semes e em Bete-Anate; mas o povo de Naftali também vivia entre os cananeus que habitavam a terra, e aqueles que viviam em Bete-Semes e em Bete-Anate passaram a fazer trabalhos forçados para eles.

[[v7-1-34]]

^<<v7-1-34,34>>^ Os amorreus confinaram a tribo de Dã à serra central, não permitindo que descessem ao vale.

[[v7-1-35]]

^<<v7-1-35,35>>^ E os amorreus igualmente estavam decididos a resistir no monte Heres, em Aijalom e em Saalbim, mas, quando as tribos de José ficaram mais poderosas, eles também foram submetidos a trabalhos forçados.

[[v7-1-36]]

^<<v7-1-36,36>>^ A fronteira dos amorreus ia da subida de Acrabim até Selá, e mais adiante.

'''

xref:006-josue/006-josue-024.adoc#v6-24-0[&#60; Capítulo Anterior] | <<v7-1-0,Topo>> | xref:007-juizes/007-juizes-002.adoc#v7-2-0[Próximo Capítulo &#62;]