include::./index.adoc[]

[[v7-13-0]]
=== Juízes, 13
// nvi ?, NVI - Nova Versão Internacional

[[v7-13-1]]

^<<v7-13-1,1>>^ Os israelitas voltaram a fazer o que o Senhor reprova, e por isso o Senhor os entregou nas mãos dos filisteus durante quarenta anos.

[[v7-13-2]]

^<<v7-13-2,2>>^ Certo homem de Zorá, chamado Manoá, do clã da tribo de Dã, tinha mulher estéril.

[[v7-13-3]]

^<<v7-13-3,3>>^ Certo dia o anjo do Senhor apareceu a ela e lhe disse: "Você é estéril, não tem filhos, mas engravidará e dará à luz um filho.

[[v7-13-4]]

^<<v7-13-4,4>>^ Todavia, tenha cuidado, não beba vinho nem outra bebida fermentada, e não coma nada impuro;

[[v7-13-5]]

^<<v7-13-5,5>>^ e não se passará navalha na cabeça do filho que você vai ter, porque o menino será nazireu, consagrado a Deus desde o nascimento; ele iniciará a libertação de Israel das mãos dos filisteus".

[[v7-13-6]]

^<<v7-13-6,6>>^ Então a mulher foi contar tudo ao seu marido: "Um homem de Deus veio falar comigo. Era como um anjo de Deus, de aparência impressionante. Não lhe perguntei de onde tinha vindo, e ele não me disse o seu nome,

[[v7-13-7]]

^<<v7-13-7,7>>^ mas ele me assegurou: ‘Você engravidará e dará à luz um filho. Todavia, não beba vinho nem outra bebida fermentada, e não coma nada impuro, porque o menino será nazireu, consagrado a Deus, desde o nascimento até o dia da sua morte’ ".

[[v7-13-8]]

^<<v7-13-8,8>>^ Então Manoá orou ao Senhor: "Senhor, eu te imploro que o homem de Deus que enviaste volte para nos instruir sobre o que fazer com o menino que vai nascer".

[[v7-13-9]]

^<<v7-13-9,9>>^ Deus ouviu a oração de Manoá, e o anjo de Deus veio novamente falar com a mulher quando ela estava sentada no campo; Manoá, seu marido, não estava com ela.

[[v7-13-10]]

^<<v7-13-10,10>>^ Mas ela foi correndo contar ao marido: "O homem que me apareceu outro dia está aqui! "

[[v7-13-11]]

^<<v7-13-11,11>>^ Manoá levantou-se e seguiu a mulher. Quando se aproximou do homem, perguntou: "És tu o que falaste com a minha mulher? " "Sim", disse ele.

[[v7-13-12]]

^<<v7-13-12,12>>^ "Quando as suas palavras se cumprirem", Manoá perguntou, "como devemos criar o menino? O que ele deverá fazer? "

[[v7-13-13]]

^<<v7-13-13,13>>^ O Anjo do Senhor respondeu: "Sua mulher terá que seguir tudo o que eu lhe ordenei.

[[v7-13-14]]

^<<v7-13-14,14>>^ Ela não poderá comer nenhum produto da videira, nem vinho ou bebida fermentada, nem comer nada impuro. Terá que obedecer a tudo o que lhe ordenei".

[[v7-13-15]]

^<<v7-13-15,15>>^ Manoá disse ao Anjo do Senhor: "Gostaríamos que ficasses conosco; queremos oferecer-te um cabrito".

[[v7-13-16]]

^<<v7-13-16,16>>^ O anjo do Senhor respondeu: "Se eu ficar, não comerei nada. Mas, se você preparar um holocausto, ofereça-o ao Senhor". Manoá não sabia que ele era o anjo do Senhor.

[[v7-13-17]]

^<<v7-13-17,17>>^ Então Manoá perguntou ao anjo do Senhor: "Qual é o teu nome, para que te prestemos homenagem quando se cumprir a tua palavra? "

[[v7-13-18]]

^<<v7-13-18,18>>^ Ele respondeu: "Por que pergunta o meu nome? Meu nome está além do entendimento".

[[v7-13-19]]

^<<v7-13-19,19>>^ Então Manoá apanhou um cabrito e a oferta de cereal, e os ofereceu ao Senhor sobre uma rocha. E o Senhor fez algo estranho enquanto Manoá e sua mulher observavam:

[[v7-13-20]]

^<<v7-13-20,20>>^ Quando a chama do altar subiu ao céu, o Anjo do Senhor subiu na chama. Vendo isso, Manoá e à sua mulher prostraram-se, rosto em terra.

[[v7-13-21]]

^<<v7-13-21,21>>^ Como o Anjo do Senhor não voltou a manifestar-se a Manoá e à sua mulher, Manoá percebeu que era o Anjo do Senhor.

[[v7-13-22]]

^<<v7-13-22,22>>^ "Sem dúvida vamos morrer! " disse ele à mulher, "pois vimos a Deus! "

[[v7-13-23]]

^<<v7-13-23,23>>^ Mas a sua mulher respondeu: "Se o Senhor tivesse a intenção de nos matar, não teria aceitado o holocausto e a oferta de cereal das nossas mãos, nem nos teria mostrado todas essas coisas, nem nos teria revelado o que agora nos revelou".

[[v7-13-24]]

^<<v7-13-24,24>>^ A mulher deu à luz um menino e pôs-lhe o nome de Sansão. Ele cresceu, e o Senhor o abençoou,

[[v7-13-25]]

^<<v7-13-25,25>>^ e o Espírito do Senhor começou a agir nele quando ele se achava em Maané-Dã, entre Zorá e Estaol.

'''

xref:007-juizes/007-juizes-012.adoc#v7-12-0[&#60; Capítulo Anterior] | <<v7-13-0,Topo>> | xref:007-juizes/007-juizes-014.adoc#v7-14-0[Próximo Capítulo &#62;]