include::./index.adoc[]

[[v7-2-0]]
=== Juízes, 2
// nvi ?, NVI - Nova Versão Internacional

[[v7-2-1]]

^<<v7-2-1,1>>^ O anjo do Senhor subiu de Gilgal a Boquim e disse: "Tirei vocês do Egito e os trouxe para a terra que prometi com juramento que daria a seus antepassados. Eu disse: Jamais quebrarei a minha aliança com vocês.

[[v7-2-2]]

^<<v7-2-2,2>>^ E vocês não farão acordo com o povo desta terra, mas demolirão os altares deles. Por quê vocês não me obedeceram?

[[v7-2-3]]

^<<v7-2-3,3>>^ Portanto, agora lhes digo que não os expulsarei da presença de vocês; eles serão seus adversários, e os deuses deles serão uma armadilha para vocês".

[[v7-2-4]]

^<<v7-2-4,4>>^ Quando o anjo do Senhor acabou de falar a todos os israelitas, o povo chorou em alta voz,

[[v7-2-5]]

^<<v7-2-5,5>>^ e ao lugar chamaram Boquim. Ali ofereceram sacrifícios ao Senhor.

[[v7-2-6]]

^<<v7-2-6,6>>^ Depois que Josué despediu os israelitas, eles saíram para ocupar a terra, cada um a sua herança.

[[v7-2-7]]

^<<v7-2-7,7>>^ O povo prestou culto ao Senhor durante toda a vida de Josué e dos líderes que continuaram vivos depois de Josué e que tinham visto todos os grandes feitos que o Senhor realizara em favor de Israel.

[[v7-2-8]]

^<<v7-2-8,8>>^ Josué, filho de Num, servo do Senhor, morreu com a idade de cento e dez anos.

[[v7-2-9]]

^<<v7-2-9,9>>^ Foi sepultado na terra de sua herança, em Timnate-Heres, nos montes de Efraim, ao norte do monte Gaás.

[[v7-2-10]]

^<<v7-2-10,10>>^ Depois que toda aquela geração foi reunida a seus antepassados, surgiu uma nova geração que não conhecia o Senhor e o que ele havia feito por Israel.

[[v7-2-11]]

^<<v7-2-11,11>>^ Então os israelitas fizeram o que o Senhor reprova e prestaram culto aos baalins.

[[v7-2-12]]

^<<v7-2-12,12>>^ Abandonaram o Senhor, o Deus dos seus antepassados, que os havia tirado do Egito, e seguiram e adoraram vários deuses dos povos ao seu redor, provocando a ira do Senhor.

[[v7-2-13]]

^<<v7-2-13,13>>^ Abandonaram o Senhor e prestaram culto a Baal e aos postes sagrados.

[[v7-2-14]]

^<<v7-2-14,14>>^ A ira do Senhor se acendeu contra Israel, e ele os entregou nas mãos de invasores que os saquearam. Ele os entregou aos inimigos ao seu redor, aos quais já não conseguiam resistir.

[[v7-2-15]]

^<<v7-2-15,15>>^ Sempre que os israelitas saíam para a batalha, a mão do Senhor era contra eles para derrotá-los, conforme lhes havia advertido e jurado. Grande angústia os dominava.

[[v7-2-16]]

^<<v7-2-16,16>>^ Então o Senhor levantou juízes, que os libertaram das mãos daqueles que os atacavam.

[[v7-2-17]]

^<<v7-2-17,17>>^ Mesmo assim eles não quiseram ouvir os juízes, antes se prostituíram com outros deuses e os adoraram. Ao contrário dos seus antepassados, logo se desviaram do caminho pelo qual os seus antepassados tinham andado, o caminho da obediência aos mandamentos do Senhor.

[[v7-2-18]]

^<<v7-2-18,18>>^ Sempre que o Senhor lhes levantava um juiz, ele estava com o juiz e os salvava das mãos de seus inimigos enquanto o juiz vivia; pois o Senhor tinha misericórdia por causa dos gemidos deles diante daqueles que os oprimiam e os afligiam.

[[v7-2-19]]

^<<v7-2-19,19>>^ Mas, quando o juiz morria, o povo voltava a caminhos ainda piores do que os caminhos dos seus antepassados, seguindo outros deuses, prestando-lhes culto e adorando-os. Recusavam-se a abandonar suas práticas e seu caminho obstinado.

[[v7-2-20]]

^<<v7-2-20,20>>^ Por isso a ira do Senhor acendeu-se contra Israel, e ele disse: "Como este povo violou a aliança que fiz com os seus antepassados e não tem ouvido a minha voz,

[[v7-2-21]]

^<<v7-2-21,21>>^ não expulsarei de diante deles nenhuma das nações que Josué deixou quando morreu.

[[v7-2-22]]

^<<v7-2-22,22>>^ Eu as usarei para pôr Israel à prova e ver se guardarão o caminho do Senhor e se andarão nele como o fizeram os seus antepassados".

[[v7-2-23]]

^<<v7-2-23,23>>^ O Senhor havia permitido que essas nações permanecessem; não as expulsou de imediato, e não as entregou nas mãos de Josué.

'''

xref:007-juizes/007-juizes-001.adoc#v7-1-0[&#60; Capítulo Anterior] | <<v7-2-0,Topo>> | xref:007-juizes/007-juizes-003.adoc#v7-3-0[Próximo Capítulo &#62;]