include::./index.adoc[]

[[v7-6-0]]
=== Juízes, 6
// nvi ?, NVI - Nova Versão Internacional

[[v7-6-1]]

^<<v7-6-1,1>>^ De novo os israelitas fizeram o que o Senhor reprova, e durante sete anos ele os entregou nas mãos dos midianitas.

[[v7-6-2]]

^<<v7-6-2,2>>^ Os midianitas dominaram Israel; por isso os israelitas fizeram para si esconderijos nas montanhas, nas cavernas e nas fortalezas.

[[v7-6-3]]

^<<v7-6-3,3>>^ Sempre que os israelitas faziam as suas plantações, os midianitas, os amalequitas e outros povos da região a leste deles as invadiam.

[[v7-6-4]]

^<<v7-6-4,4>>^ Acampavam na terra e destruíam as plantações ao longo de todo o caminho, até Gaza, e não deixavam nada vivo em Israel, nem ovelhas nem gado nem jumentos.

[[v7-6-5]]

^<<v7-6-5,5>>^ Eles subiam trazendo os seus animais e suas tendas, e vinham como enxames de gafanhotos; era impossível contar os homens e os seus camelos. Invadiam a terra para devastá-la.

[[v7-6-6]]

^<<v7-6-6,6>>^ Por causa de Midiã, Israel empobreceu tanto que os israelitas clamaram por socorro ao Senhor.

[[v7-6-7]]

^<<v7-6-7,7>>^ Quando os israelitas clamaram ao Senhor por causa de Midiã,

[[v7-6-8]]

^<<v7-6-8,8>>^ ele lhes enviou um profeta, que disse: "Assim diz o Senhor, o Deus de Israel: ‘Tirei vocês do Egito, da terra da escravidão.

[[v7-6-9]]

^<<v7-6-9,9>>^ Eu os livrei do poder do Egito e das mãos de todos os seus opressores. Expulsei-os e dei a vocês a terra deles.

[[v7-6-10]]

^<<v7-6-10,10>>^ E também disse a vocês: Eu sou o Senhor, o seu Deus; não adorem os deuses dos amorreus, em cuja terra vivem, mas vocês não me deram ouvidos’ ".

[[v7-6-11]]

^<<v7-6-11,11>>^ Então o Anjo do Senhor veio e sentou-se sob a grande árvore de Ofra, que pertencia ao abiezrita Joás. Gideão, filho de Joás, estava malhando o trigo num tanque de prensar uvas, para escondê-lo dos midianitas.

[[v7-6-12]]

^<<v7-6-12,12>>^ Então o anjo do Senhor apareceu a Gideão e lhe disse: "O Senhor está com você, poderoso guerreiro".

[[v7-6-13]]

^<<v7-6-13,13>>^ "Ah, Senhor", Gideão respondeu, "se o Senhor está conosco, por que aconteceu tudo isso? Onde estão todas as suas maravilhas que os nossos pais nos contam quando dizem: ‘Não foi o Senhor que nos tirou do Egito? ’ Mas agora o Senhor nos abandonou e nos entregou nas mãos de Midiã".

[[v7-6-14]]

^<<v7-6-14,14>>^ O Senhor se voltou para ele e disse: "Com a força que você tem, vá libertar Israel das mãos de Midiã. Não sou eu quem o está enviando? "

[[v7-6-15]]

^<<v7-6-15,15>>^ "Ah, Senhor", respondeu Gideão, "como posso libertar Israel? Meu clã é o menos importante de Manassés, e eu sou o menor da minha família".

[[v7-6-16]]

^<<v7-6-16,16>>^ "Eu estarei com você", respondeu o Senhor, "e você derrotará todos os midianitas como se fossem um só homem".

[[v7-6-17]]

^<<v7-6-17,17>>^ E Gideão prosseguiu: "Se de fato posso contar com o teu favor, dá-me um sinal de que és tu que está falando comigo.

[[v7-6-18]]

^<<v7-6-18,18>>^ Peço-te que não vás embora até que eu volte e traga minha oferta e a coloque diante de ti". E o Senhor respondeu: "Esperarei até você voltar".

[[v7-6-19]]

^<<v7-6-19,19>>^ Gideão foi para casa, preparou um cabrito, e com uma arroba de farinha fez pães sem fermento. Pôs a carne num cesto e o caldo numa panela, trouxe-os para fora e ofereceu-os a ele sob a grande árvore.

[[v7-6-20]]

^<<v7-6-20,20>>^ E o Anjo de Deus lhe disse: "Apanhe a carne e os pães sem fermento, ponha-os sobre esta rocha e derrame o caldo". Gideão assim o fez.

[[v7-6-21]]

^<<v7-6-21,21>>^ Com a ponta do cajado que estava em sua mão, o Anjo do Senhor tocou a carne e os pães sem fermento. Fogo subiu da rocha, consumindo a carne e os pães. E o Anjo do Senhor desapareceu.

[[v7-6-22]]

^<<v7-6-22,22>>^ Quando Gideão viu que era o Anjo do Senhor, exclamou: "Ah, Senhor Soberano! Vi o Anjo do Senhor face a face! "

[[v7-6-23]]

^<<v7-6-23,23>>^ Disse-lhe, porém, o Senhor: "Paz seja com você! Não tenha medo. Você não morrerá".

[[v7-6-24]]

^<<v7-6-24,24>>^ Gideão construiu ali um altar em honra do Senhor e lhe deu este nome: O Senhor é Paz. Até hoje o altar está em Ofra dos abiezritas.

[[v7-6-25]]

^<<v7-6-25,25>>^ Naquela mesma noite o Senhor lhe disse: "Separe o segundo novilho do rebanho de seu pai, aquele de sete anos de idade. Despedace o altar de Baal, que pertence a seu pai, e corte o poste sagrado que está ao lado do altar.

[[v7-6-26]]

^<<v7-6-26,26>>^ Depois faça um altar para o Senhor, para o seu Deus, no topo desta elevação. Ofereça o segundo novilho em holocausto com a madeira do poste sagrado que você irá cortar".

[[v7-6-27]]

^<<v7-6-27,27>>^ Assim Gideão chamou dez dos seus servos e fez como o Senhor lhe ordenara. Mas, com medo da sua família e dos homens da cidade, fez tudo de noite, e não durante o dia.

[[v7-6-28]]

^<<v7-6-28,28>>^ De manhã, quando os homens da cidade se levantaram, lá estava demolido o altar de Baal, com o poste sagrado ao seu lado, cortado, e com o segundo novilho sacrificado no altar recém-construído!

[[v7-6-29]]

^<<v7-6-29,29>>^ Perguntaram uns aos outros: "Quem fez isso? " Depois de investigar, concluíram: "Foi Gideão, filho de Joás".

[[v7-6-30]]

^<<v7-6-30,30>>^ Os homens da cidade disseram a Joás: "Traga seu filho para fora. Ele deve morrer, pois derrubou o altar de Baal e quebrou o poste sagrado que ficava ao seu lado".

[[v7-6-31]]

^<<v7-6-31,31>>^ Joás, porém, respondeu à multidão hostil que o cercava, "Vocês vão defender a causa de Baal? Estão tentando salvá-lo? Quem lutar por ele será morto pela manhã! Se Baal fosse realmente um deus, poderia defender-se quando derrubaram o seu altar".

[[v7-6-32]]

^<<v7-6-32,32>>^ Por isso naquele dia chamaram Gideão de "Jerubaal", dizendo: "Que Baal dispute com ele, pois derrubou o altar de Baal".

[[v7-6-33]]

^<<v7-6-33,33>>^ Nesse meio tempo, todos os midianitas, amalequitas e outros povos que vinham do leste uniram os seus exércitos, atravessaram o Jordão e acamparam no vale de Jezreel.

[[v7-6-34]]

^<<v7-6-34,34>>^ Então o Espírito do Senhor apoderou-se de Gideão, e ele, com toque de trombeta, convocou os abiezritas para segui-lo.

[[v7-6-35]]

^<<v7-6-35,35>>^ Enviou mensageiros a todo o Manassés, chamando-o às armas, e também a Aser, a Zebulom e a Naftali, que também subiram ao seu encontro.

[[v7-6-36]]

^<<v7-6-36,36>>^ E Gideão disse a Deus: "Quero saber se vais libertar Israel por meu intermédio, como prometeste.

[[v7-6-37]]

^<<v7-6-37,37>>^ Vê, colocarei uma porção de lã na eira. Se o orvalho molhar apenas a lã e todo o chão estiver seco, saberei que tu libertarás Israel por meu intermédio, como prometeste".

[[v7-6-38]]

^<<v7-6-38,38>>^ E assim aconteceu. Gideão levantou-se logo cedo no dia seguinte, torceu a lã e encheu uma tigela de água do orvalho.

[[v7-6-39]]

^<<v7-6-39,39>>^ Disse ainda Gideão a Deus: "Não se acenda a tua ira contra mim. Deixa-me fazer só mais um pedido. Permite-me fazer mais um teste com a lã. Desta vez faze ficar seca a lã e o chão coberto de orvalho".

[[v7-6-40]]

^<<v7-6-40,40>>^ E Deus assim fez naquela noite. Somente a lã estava seca; o chão estava todo coberto de orvalho.

'''

xref:007-juizes/007-juizes-005.adoc#v7-5-0[&#60; Capítulo Anterior] | <<v7-6-0,Topo>> | xref:007-juizes/007-juizes-007.adoc#v7-7-0[Próximo Capítulo &#62;]