include::./index.adoc[]

[[v7-20-0]]
=== Juízes, 20
// nvi ?, NVI - Nova Versão Internacional

[[v7-20-1]]

^<<v7-20-1,1>>^ Então todos os israelitas, de Dã a Berseba, e de Gileade, saíram como um só homem e se reuniram em assembléia perante o Senhor em Mispá.

[[v7-20-2]]

^<<v7-20-2,2>>^ Os líderes de todo o povo das tribos de Israel tomaram seus lugares na assembléia do povo de Deus, quatrocentos mil soldados armados de espada.

[[v7-20-3]]

^<<v7-20-3,3>>^ ( Os benjamitas souberam que os israelitas haviam subido a Mispá. ) Os israelitas perguntaram: "Como aconteceu essa perversidade? "

[[v7-20-4]]

^<<v7-20-4,4>>^ Então o levita, marido da mulher assassinada, disse: "Eu e a minha concubina chegamos a Gibeá de Benjamim para passar a noite.

[[v7-20-5]]

^<<v7-20-5,5>>^ Durante a noite os homens de Gibeá vieram para atacar-me e cercaram a casa, com a intenção de matar-me. Então violentaram minha concubina, e ela morreu.

[[v7-20-6]]

^<<v7-20-6,6>>^ Peguei minha concubina, cortei-a em pedaços e enviei um pedaço a cada região da herança de Israel, pois eles cometeram essa perversidade e esse ato vergonhoso em Israel.

[[v7-20-7]]

^<<v7-20-7,7>>^ Agora, todos vocês israelitas, manifestem-se e dêem o seu veredicto".

[[v7-20-8]]

^<<v7-20-8,8>>^ Todo o povo se levantou como se fosse um só homem, dizendo: "Nenhum de nós irá para casa. Nenhum de nós voltará para o seu lar.

[[v7-20-9]]

^<<v7-20-9,9>>^ Mas é isto que faremos agora contra Gibeá: Separaremos, por sorteio, de todas as tribos de Israel,

[[v7-20-10]]

^<<v7-20-10,10>>^ de cada cem homens dez homens, de cada mil homens cem, de cada dez mil homens mil, para conseguirem provisões para o exército poder chegar a Gibeá de Benjamim e dar a eles o que merecem por todo esse ato vergonhoso cometido em Israel".

[[v7-20-11]]

^<<v7-20-11,11>>^ E todos os israelitas se ajuntaram e se uniram como um só homem contra a cidade.

[[v7-20-12]]

^<<v7-20-12,12>>^ As tribos de Israel enviaram homens a toda a tribo de Benjamim, dizendo: "O que vocês dizem dessa maldade terrível que foi cometido no meio de vocês?

[[v7-20-13]]

^<<v7-20-13,13>>^ Agora, entreguem esses canalhas de Gibeá, para que os matemos e eliminemos esse mal de Israel". Mas os benjamitas não quiseram ouvir seus irmãos israelitas.

[[v7-20-14]]

^<<v7-20-14,14>>^ Vindos de suas cidades, reuniram-se em Gibeá para lutar contra os israelitas.

[[v7-20-15]]

^<<v7-20-15,15>>^ Naquele dia os benjamitas mobilizaram vinte e seis mil homens armados de espada que vieram das suas cidades, além dos setecentos melhores soldados que viviam em Gibeá.

[[v7-20-16]]

^<<v7-20-16,16>>^ Dentre todos esses soldados havia setecentos canhotos, muito hábeis, e cada um deles podia atirar uma pedra com a funda num cabelo sem errar.

[[v7-20-17]]

^<<v7-20-17,17>>^ Israel, sem contar os de Benjamim, convocou quatrocentos mil homens armados de espada, todos eles homens de guerra.

[[v7-20-18]]

^<<v7-20-18,18>>^ Os israelitas subiram a Betel e consultaram a Deus. "Quem de nós irá lutar primeiro contra os benjamitas? ", perguntaram. O Senhor respondeu: "Judá irá primeiro".

[[v7-20-19]]

^<<v7-20-19,19>>^ Na manhã seguinte os israelitas se levantaram e armaram acampamento perto de Gibeá.

[[v7-20-20]]

^<<v7-20-20,20>>^ Os homens de Israel saíram para lutar contra os benjamitas e tomaram posição de combate contra eles em Gibeá.

[[v7-20-21]]

^<<v7-20-21,21>>^ Os benjamitas saíram de Gibeá e naquele dia mataram vinte e dois mil israelitas no campo de batalha.

[[v7-20-22]]

^<<v7-20-22,22>>^ Mas os homens de Israel procuraram animar-se uns aos outros, e novamente ocuparam as mesmas posições do primeiro dia.

[[v7-20-23]]

^<<v7-20-23,23>>^ Os israelitas subiram e choraram perante o Senhor até a tarde, e consultaram o Senhor: "Devemos atacar de novo os nossos irmãos benjamitas? " O Senhor respondeu: "Vocês devem atacar".

[[v7-20-24]]

^<<v7-20-24,24>>^ Então os israelitas avançaram contra os benjamitas no segundo dia.

[[v7-20-25]]

^<<v7-20-25,25>>^ Dessa vez, quando os benjamitas saíram de Gibeá para enfrentá-los, derrubaram outros dezoito mil israelitas, todos eles armados de espada.

[[v7-20-26]]

^<<v7-20-26,26>>^ Então todos os israelitas subiram a Betel, e ali se assentaram, chorando perante o Senhor. Naquele dia jejuaram até à tarde e apresentaram holocaustos e ofertas de comunhão ao Senhor.

[[v7-20-27]]

^<<v7-20-27,27>>^ E os israelitas consultaram ao Senhor. ( Naqueles dias a arca da aliança estava ali,

[[v7-20-28]]

^<<v7-20-28,28>>^ e Finéias, filho de Eleazar, filho de Arão, ministrava perante ela. ) Perguntaram: "Sairemos de novo ou não, para lutar contra os nossos irmãos benjamitas? " O Senhor respondeu: "Vão, pois amanhã eu os entregarei nas suas mãos".

[[v7-20-29]]

^<<v7-20-29,29>>^ Então os israelitas armaram uma emboscada em torno de Gibeá.

[[v7-20-30]]

^<<v7-20-30,30>>^ Avançaram contra os benjamitas no terceiro dia e tomaram posição contra Gibeá, como tinham feito antes.

[[v7-20-31]]

^<<v7-20-31,31>>^ Os benjamitas saíram para enfrentá-los e foram atraídos para longe da cidade. Começaram a ferir alguns dos israelitas como tinham feito antes, e uns trinta homens foram mortos em campo aberto e nas estradas, uma que vai para Betel e a outra que vai para Gibeá.

[[v7-20-32]]

^<<v7-20-32,32>>^ Enquanto os benjamitas diziam: "Nós os derrotamos como antes", os israelitas diziam: "Vamos retirar-nos e atraí-los para longe da cidade, para as estradas".

[[v7-20-33]]

^<<v7-20-33,33>>^ Todos os homens de Israel saíram dos seus lugares e ocuparam posições em Baal-Tamar, e a emboscada israelita atacou da sua posição a oeste de Gibeá.

[[v7-20-34]]

^<<v7-20-34,34>>^ Então dez mil dos melhores soldados de Israel iniciaram um ataque frontal contra Gibeá. O combate foi duro, e os benjamitas não perceberam que a desgraça estava próxima deles.

[[v7-20-35]]

^<<v7-20-35,35>>^ O Senhor derrotou Benjamim perante Israel, e naquele dia os israelitas feriram vinte e cinco mil e cem benjamitas, todos armados de espada.

[[v7-20-36]]

^<<v7-20-36,36>>^ Então os benjamitas viram que estavam derrotados. Os israelitas bateram em retirada diante de Benjamim, pois confiavam na emboscada que tinham preparado perto de Gibeá.

[[v7-20-37]]

^<<v7-20-37,37>>^ Os da emboscada avançaram repentinamente para dentro de Gibeá, espalharam-se e mataram todos os habitantes da cidade à espada.

[[v7-20-38]]

^<<v7-20-38,38>>^ Os israelitas tinham combinado com os da emboscada que estes fariam subir da cidade uma grande nuvem de fumaça,

[[v7-20-39]]

^<<v7-20-39,39>>^ e então os israelitas voltariam a combater. Os benjamitas tinham começado a ferir os israelitas, matando cerca de trinta deles, e disseram: "Nós os derrotamos como na primeira batalha".

[[v7-20-40]]

^<<v7-20-40,40>>^ Mas, quando a coluna de fumaça começou a se levantar da cidade, os benjamitas se viraram e viram a fumaça subindo ao céu.

[[v7-20-41]]

^<<v7-20-41,41>>^ Então os israelitas se voltaram contra eles, e os homens de Benjamim ficaram apavorados, pois perceberam que a sua desgraça havia chegado.

[[v7-20-42]]

^<<v7-20-42,42>>^ Assim, fugiram da presença dos israelitas tomando o caminho do deserto, mas não conseguiram escapar do combate. E os homens de Israel que saíram das cidades os mataram ali.

[[v7-20-43]]

^<<v7-20-43,43>>^ Cercaram os benjamitas e os perseguiram, e facilmente os alcançaram nas proximidades de Gibeá, no lado leste.

[[v7-20-44]]

^<<v7-20-44,44>>^ Dezoito mil benjamitas morreram, todos eles soldados valentes.

[[v7-20-45]]

^<<v7-20-45,45>>^ Quando se viraram e fugiram rumo ao deserto, para a rocha de Rimom, os israelitas abateram cinco mil homens ao longo das estradas. Até Gidom eles pressionaram os benjamitas e mataram mais de dois mil homens.

[[v7-20-46]]

^<<v7-20-46,46>>^ Naquele dia vinte e cinco mil benjamitas que portavam espada morreram, todos eles soldados valentes.

[[v7-20-47]]

^<<v7-20-47,47>>^ Seiscentos homens, porém, viraram as costas e fugiram para o deserto, para a rocha de Rimom, onde ficaram durante quatro meses.

[[v7-20-48]]

^<<v7-20-48,48>>^ Os israelitas voltaram a Benjamim e passaram todas as cidades à espada, matando inclusive os animais e tudo o que encontraram nelas. E incendiaram todas as cidades por onde passaram.

'''

xref:007-juizes/007-juizes-019.adoc#v7-19-0[&#60; Capítulo Anterior] | <<v7-20-0,Topo>> | xref:007-juizes/007-juizes-021.adoc#v7-21-0[Próximo Capítulo &#62;]