include::./index.adoc[]

[[v7-18-0]]
=== Juízes, 18
// nvi ?, NVI - Nova Versão Internacional

[[v7-18-1]]

^<<v7-18-1,1>>^ Naquela época não havia rei em Israel, e a tribo de Dã estava procurando um local onde estabelecer-se, pois ainda não tinha recebido herança entre as tribos de Israel.

[[v7-18-2]]

^<<v7-18-2,2>>^ Então enviaram cinco guerreiros de Zorá e de Estaol para espionarem a terra e explorá-la. Esses homens representavam todos os clãs da tribo. Disseram-lhes: "Vão, explorem a terra". Os homens chegaram aos montes de Efraim e foram à casa de Mica, onde passaram a noite.

[[v7-18-3]]

^<<v7-18-3,3>>^ Quando estavam perto da casa de Mica, reconheceram a voz do jovem levita; aproximaram-se e lhe perguntaram: "Quem o trouxe para cá? O que você está fazendo neste lugar? Por que você está aqui? "

[[v7-18-4]]

^<<v7-18-4,4>>^ O jovem lhes contou o que Mica fizera por ele, e disse: "Ele me contratou, e eu sou seu sacerdote".

[[v7-18-5]]

^<<v7-18-5,5>>^ Então eles lhe pediram: "Pergunte a Deus, se a nossa viagem será bem sucedida".

[[v7-18-6]]

^<<v7-18-6,6>>^ O sacerdote lhes respondeu: "Vão em paz. Sua viagem tem a aprovação do Senhor".

[[v7-18-7]]

^<<v7-18-7,7>>^ Os cinco homens partiram e chegaram a Laís, onde viram que o povo vivia em segurança, como os sidônios, despreocupado e tranqüilo, e que gozava prosperidade, pois a sua terra não lhe deixava faltar nada. Viram também que o povo vivia longe dos sidônios e não tinha relações com nenhum outro povo.

[[v7-18-8]]

^<<v7-18-8,8>>^ Quando voltaram a Zorá e a Estaol, seus irmãos lhes perguntaram: "O que descobriram? "

[[v7-18-9]]

^<<v7-18-9,9>>^ Eles responderam: "Vamos atacá-los! Vimos que a terra é muito boa. Vocês vão ficar aí sem fazer nada? Não hesitem em ir apossar-se dela.

[[v7-18-10]]

^<<v7-18-10,10>>^ Chegando lá, vocês encontrarão um povo despreocupado e uma terra espaçosa que Deus pôs nas mãos de vocês, terra onde não falta coisa alguma! "

[[v7-18-11]]

^<<v7-18-11,11>>^ Então seiscentos homens da tribo de Dã, partiram de Zorá e de Estaol, armados para guerra.

[[v7-18-12]]

^<<v7-18-12,12>>^ Na viagem armaram acampamento perto de Quiriate-Jearim, em Judá. É por isso que até hoje o local, a oeste de Quiriate-Jearim, é chamado Maané-Dã.

[[v7-18-13]]

^<<v7-18-13,13>>^ Dali foram para os montes de Efraim e chegaram à casa de Mica.

[[v7-18-14]]

^<<v7-18-14,14>>^ Os cinco homens que haviam espionado a terra de Laís disseram a seus irmãos: "Vocês sabiam que numa dessas casas há um manto sacerdotal, ídolos da família, uma imagem esculpida e um ídolo de metal? Agora vocês sabem o que devem fazer".

[[v7-18-15]]

^<<v7-18-15,15>>^ Então eles se aproximaram e foram à casa do jovem levita, à casa de Mica, e o saudaram.

[[v7-18-16]]

^<<v7-18-16,16>>^ Os seiscentos homens de Dã, armados para a guerra, ficaram junto à porta.

[[v7-18-17]]

^<<v7-18-17,17>>^ Os cinco homens que haviam espionado a terra entraram e apanharam a imagem, o manto sacerdotal, os ídolos da família e o ídolo de metal, enquanto o sacerdote e os seiscentos homens armados permaneciam à porta.

[[v7-18-18]]

^<<v7-18-18,18>>^ Quando os homens entraram na casa de Mica e apanharam a imagem, o manto sacerdotal, os ídolos da família e o ídolo de metal, o sacerdote lhes perguntou: "Que é que vocês estão fazendo? "

[[v7-18-19]]

^<<v7-18-19,19>>^ Eles lhe responderam: "Silêncio! Não diga nada. Venha conosco, e seja nosso pai e sacerdote. Não será melhor para você servir como sacerdote uma tribo e um clã de Israel do que apenas a família de um só homem? "

[[v7-18-20]]

^<<v7-18-20,20>>^ Então o sacerdote se alegrou, apanhou o manto sacerdotal, os ídolos da família e a imagem esculpida e se juntou à tropa.

[[v7-18-21]]

^<<v7-18-21,21>>^ Pondo os seus filhos, os seus animais e os seus bens na frente deles, partiram de volta.

[[v7-18-22]]

^<<v7-18-22,22>>^ Quando já estavam a certa distância da casa, os homens que moravam perto de Mica foram convocados e alcançaram os homens de Dã.

[[v7-18-23]]

^<<v7-18-23,23>>^ Como vinham gritando atrás deles, estes se voltaram e perguntaram a Mica: "Qual é o seu problema? Por quê convocou os seus homens para lutar? "

[[v7-18-24]]

^<<v7-18-24,24>>^ Ele respondeu: "Vocês estão levando embora os deuses que fiz e o meu sacerdote. O que me sobrou? Como é que ainda podem perguntar: ‘Qual é o seu problema? ’ "

[[v7-18-25]]

^<<v7-18-25,25>>^ Os homens de Dã responderam: "Não discuta conosco, senão alguns homens de temperamento violento o atacarão, e você e a sua família perderão a vida".

[[v7-18-26]]

^<<v7-18-26,26>>^ E assim os homens de Dã seguiram seu caminho. Vendo que eles eram fortes demais para ele, Mica virou-se e voltou para casa.

[[v7-18-27]]

^<<v7-18-27,27>>^ Os homens de Dã levaram o que Mica fizera e o seu sacerdote, e foram para Laís, lugar de um povo pacífico e despreocupado. Eles mataram todos ao fio da espada e queimaram a cidade.

[[v7-18-28]]

^<<v7-18-28,28>>^ Não houve quem os livrasse, pois viviam longe de Sidom e não tinham relações com nenhum outro povo. A cidade ficava num vale que se estende até Bete-Reobe. Os homens de Dã reconstruíram a cidade e se estabeleceram nela.

[[v7-18-29]]

^<<v7-18-29,29>>^ Deram à cidade anteriormente chamada Laís o nome de Dã, em homenagem a seu antepassado Dã, filho de Israel.

[[v7-18-30]]

^<<v7-18-30,30>>^ Eles levantaram para si o ídolo, e Jônatas, filho de Gérson, neto de Moisés, e os seus filhos foram sacerdotes da tribo de Dã até que o povo foi para o exílio.

[[v7-18-31]]

^<<v7-18-31,31>>^ Ficaram com o ídolo feito por Mica durante todo o tempo em que o santuário de Deus esteve em Siló.

'''

xref:007-juizes/007-juizes-017.adoc#v7-17-0[&#60; Capítulo Anterior] | <<v7-18-0,Topo>> | xref:007-juizes/007-juizes-019.adoc#v7-19-0[Próximo Capítulo &#62;]