include::./index.adoc[]

[[v7-5-0]]
=== Juízes, 5
// nvi ?, NVI - Nova Versão Internacional

[[v7-5-1]]

^<<v7-5-1,1>>^ Naquele dia Débora e Baraque, filho de Abinoão, entoaram este cântico:

[[v7-5-2]]

^<<v7-5-2,2>>^ "Consagrem-se para a guerra os chefes de Israel. Voluntariamente o povo se apresenta. Louvem o Senhor!

[[v7-5-3]]

^<<v7-5-3,3>>^ "Ouçam, ó reis! Governantes, escutem! Cantarei ao Senhor, cantarei; comporei músicas ao Senhor, ao Deus de Israel.

[[v7-5-4]]

^<<v7-5-4,4>>^ "Ó Senhor, quando saíste de Seir, quando marchaste desde os campos de Edom, a terra estremeceu, os céus gotejaram, as nuvens despejaram água!

[[v7-5-5]]

^<<v7-5-5,5>>^ Os montes tremeram perante o Senhor, o Deus do Sinai, perante o Senhor, o Deus de Israel.

[[v7-5-6]]

^<<v7-5-6,6>>^ "Nos dias de Sangar, filho de Anate, nos dias de Jael, as estradas estavam desertas; os que viajavam seguiam caminhos tortuosos.

[[v7-5-7]]

^<<v7-5-7,7>>^ Já tinham desistido os camponeses de Israel, já tinham desistido, até que eu, Débora, me levantei; levantou-se uma mãe em Israel.

[[v7-5-8]]

^<<v7-5-8,8>>^ Quando escolheram novos deuses, a guerra chegou às portas, e não se via um só escudo ou lança entre quarenta mil de Israel.

[[v7-5-9]]

^<<v7-5-9,9>>^ Meu coração está com os comandantes de Israel, com os voluntários dentre o povo. Louvem o Senhor!

[[v7-5-10]]

^<<v7-5-10,10>>^ "Vocês, que cavalgam em brancos jumentos, assentam-se em ricos tapetes, que caminham pela estrada, considerem!

[[v7-5-11]]

^<<v7-5-11,11>>^ Mais alto que a voz dos que distribuem água junto aos bebedouros, recitem-se os justos feitos do Senhor, os justos feitos em favor dos camponeses de Israel. "Então o povo do Senhor desceu às portas.

[[v7-5-12]]

^<<v7-5-12,12>>^ ‘Desperte, Débora! Desperte! Desperte, desperte, irrompa em cânticos! Levante-se, Baraque! Leve presos os seus prisioneiros, ó filho de Abinoão! ’

[[v7-5-13]]

^<<v7-5-13,13>>^ "Então desceram os restantes e foram aos nobres; o povo do Senhor veio a mim contra os poderosos.

[[v7-5-14]]

^<<v7-5-14,14>>^ Alguns vieram de Efraim, das raízes de Amaleque; Benjamim estava com o povo que seguiu você. De Maquir desceram comandantes; de Zebulom, os que levam a vara de oficial.

[[v7-5-15]]

^<<v7-5-15,15>>^ Os líderes de Issacar estavam com Débora; sim, Issacar também estava com Baraque, apressando-se após ele até o vale. Nas divisões de Rúben houve muita inquietação.

[[v7-5-16]]

^<<v7-5-16,16>>^ Por que vocês permaneceram entre as fogueiras a ouvir o balido dos rebanhos? Nas divisões de Rúben houve muita indecisão.

[[v7-5-17]]

^<<v7-5-17,17>>^ Gileade permaneceu do outro lado do Jordão. E Dã, por que se deteve junto aos navios? Aser permaneceu no litoral e em suas enseadas ficou.

[[v7-5-18]]

^<<v7-5-18,18>>^ O povo de Zebulom arriscou a vida; como o fez Naftali nas altas regiões do campo.

[[v7-5-19]]

^<<v7-5-19,19>>^ "Vieram reis e lutaram. Os reis de Canaã lutaram em Taanaque, junto às águas de Megido, mas não levaram prata alguma, despojo algum.

[[v7-5-20]]

^<<v7-5-20,20>>^ Desde o céu lutaram as estrelas, desde as suas órbitas lutaram contra Sísera.

[[v7-5-21]]

^<<v7-5-21,21>>^ O rio Quisom os levou, o antigo rio, o rio Quisom. Avante, minh’alma! Seja forte!

[[v7-5-22]]

^<<v7-5-22,22>>^ Os cascos dos cavalos faziam tremer o chão; galopavam, galopavam os seus poderosos cavalos.

[[v7-5-23]]

^<<v7-5-23,23>>^ ‘Amaldiçoem Meroz’, disse o anjo do Senhor. ‘Amaldiçoem o seu povo, pois não vieram ajudar o Senhor, ajudar o Senhor contra os poderosos. ’

[[v7-5-24]]

^<<v7-5-24,24>>^ "Que Jael seja a mais bendita das mulheres, Jael, mulher de Héber, o queneu! Seja ela bendita entre as mulheres que habitam em tendas!

[[v7-5-25]]

^<<v7-5-25,25>>^ Ele pediu água, e ela lhe deu leite; numa tigela digna de príncipes trouxe-lhe coalhada.

[[v7-5-26]]

^<<v7-5-26,26>>^ Ela estendeu a mão e apanhou a estaca da tenda; e com a mão direita o martelo do trabalhador. Golpeou Sísera, esmigalhou sua cabeça, esmagou e traspassou suas têmporas.

[[v7-5-27]]

^<<v7-5-27,27>>^ Aos seus pés ele se curvou, caiu e ali ficou prostrado. Aos seus pés ele se curvou e caiu; onde caiu, ali ficou, morto!

[[v7-5-28]]

^<<v7-5-28,28>>^ "Pela janela olhava a mãe de Sísera; atrás da grade ela exclamava: ‘Por que o seu carro se demora tanto? Por que custa a chegar o ruído de seus carros? ’

[[v7-5-29]]

^<<v7-5-29,29>>^ As mais sábias de suas damas responderam, e ela continuava falando consigo mesma:

[[v7-5-30]]

^<<v7-5-30,30>>^ ‘Estarão achando e repartindo os despojos? Uma moça ou duas moças para cada homem, roupas coloridas como despojo para Sísera, roupas coloridas e bordadas, tecidos bordados para o meu pescoço, tudo isso como despojo? ’

[[v7-5-31]]

^<<v7-5-31,31>>^ "Assim pereçam todos os teus inimigos, ó Senhor! Mas os que te amam sejam como o sol quando se levanta na sua força". E a terra teve paz durante quarenta anos.

'''

xref:007-juizes/007-juizes-004.adoc#v7-4-0[&#60; Capítulo Anterior] | <<v7-5-0,Topo>> | xref:007-juizes/007-juizes-006.adoc#v7-6-0[Próximo Capítulo &#62;]