include::./index.adoc[]

[[v7-10-0]]
=== Juízes, 10
// nvi ?, NVI - Nova Versão Internacional

[[v7-10-1]]

^<<v7-10-1,1>>^ Depois de Abimeleque, um homem de Issacar chamado Tolá, filho de Puá, filho de Dodô, levantou-se para libertar Israel. Ele morava em Samir, nos montes de Efraim,

[[v7-10-2]]

^<<v7-10-2,2>>^ e liderou Israel durante vinte e três anos; então morreu e foi sepultado em Samir.

[[v7-10-3]]

^<<v7-10-3,3>>^ Depois dele veio Jair, de Gileade, que liderou Israel durante vinte e dois anos.

[[v7-10-4]]

^<<v7-10-4,4>>^ Teve trinta filhos, que montavam trinta jumentos. Eles tinham autoridade sobre trinta cidades, as quais até hoje são chamadas povoados de Jair e ficam em Gileade.

[[v7-10-5]]

^<<v7-10-5,5>>^ Quando Jair morreu, foi sepultado em Camom.

[[v7-10-6]]

^<<v7-10-6,6>>^ Mais uma vez os israelitas fizeram o que o Senhor reprova. Serviram aos baalins e aos postes sagrados, e aos deuses de Arã, aos deuses de Sidom, aos deuses de Moabe, aos deuses dos amonitas e aos deuses dos filisteus. E como os israelitas abandonaram o Senhor e não mais lhe prestaram culto,

[[v7-10-7]]

^<<v7-10-7,7>>^ a ira do Senhor se acendeu contra eles. Ele os entregou nas mãos dos filisteus e dos amonitas,

[[v7-10-8]]

^<<v7-10-8,8>>^ que naquele ano os humilharam e os oprimiram. Durante dezoito anos oprimiram a todos os israelitas do lado leste do Jordão, em Gileade, terra dos amorreus.

[[v7-10-9]]

^<<v7-10-9,9>>^ Os amonitas também atravessaram o Jordão para lutar contra Judá, contra Benjamim e contra a tribo de Efraim; e grande angústia dominou Israel.

[[v7-10-10]]

^<<v7-10-10,10>>^ Então os israelitas clamaram ao Senhor, dizendo: "Temos pecado contra ti, pois abandonamos o nosso Deus e prestamos culto aos baalins! "

[[v7-10-11]]

^<<v7-10-11,11>>^ O Senhor respondeu: "Quando os egípcios, os amorreus, os amonitas, os filisteus,

[[v7-10-12]]

^<<v7-10-12,12>>^ os sidônios, os amalequitas e os maonitas os oprimiram, e vocês clamaram a mim, e eu os libertei das mãos deles.

[[v7-10-13]]

^<<v7-10-13,13>>^ Mas vocês me abandonaram e prestaram culto a outros deuses. Por isso não os livrarei mais.

[[v7-10-14]]

^<<v7-10-14,14>>^ Clamem aos deuses que vocês escolheram. Que eles os livrem na hora do aperto! "

[[v7-10-15]]

^<<v7-10-15,15>>^ Os israelitas, porém, disseram ao Senhor: "Nós pecamos. Faze conosco o que achares melhor, mas te rogamos, livra-nos agora".

[[v7-10-16]]

^<<v7-10-16,16>>^ Então eles se desfizeram dos deuses estrangeiros que havia entre eles e prestaram culto ao Senhor. E ele não pôde mais suportar o sofrimento de Israel.

[[v7-10-17]]

^<<v7-10-17,17>>^ Quando os amonitas foram convocados e acamparam em Gileade, os israelitas reuniram-se e acamparam em Mispá.

[[v7-10-18]]

^<<v7-10-18,18>>^ Os líderes do povo de Gileade disseram uns aos outros: "Quem iniciar o ataque contra os amonitas será chefe dos que vivem em Gileade".

'''

xref:007-juizes/007-juizes-009.adoc#v7-9-0[&#60; Capítulo Anterior] | <<v7-10-0,Topo>> | xref:007-juizes/007-juizes-011.adoc#v7-11-0[Próximo Capítulo &#62;]