include::./index.adoc[]

[[v7-8-0]]
=== Juízes, 8
// nvi ?, NVI - Nova Versão Internacional

[[v7-8-1]]

^<<v7-8-1,1>>^ Os efraimitas perguntaram então a Gideão: "Por que você nos tratou dessa forma? Por que não nos chamou quando foi lutar contra Midiã? " E o criticaram duramente.

[[v7-8-2]]

^<<v7-8-2,2>>^ Ele, porém, lhes respondeu: "Que é que eu fiz, em comparação com vocês? O resto das uvas de Efraim não são melhores do que toda a colheita de Abiezer?

[[v7-8-3]]

^<<v7-8-3,3>>^ Deus entregou os líderes midianitas Orebe e Zeebe nas mãos de vocês. O que pude fazer não se compara com o que vocês fizeram? " Diante disso, acalmou-se a indignação deles contra Gideão.

[[v7-8-4]]

^<<v7-8-4,4>>^ Gideão e seus trezentos homens, já exaustos, continuaram a perseguição, chegaram ao Jordão e o atravessaram.

[[v7-8-5]]

^<<v7-8-5,5>>^ Em Sucote, disse ele aos homens dali: "Peço-lhes um pouco de pão para as minhas tropas; os homens estão cansados, e eu ainda estou perseguindo os reis de Midiã, Zeba e Zalmuna".

[[v7-8-6]]

^<<v7-8-6,6>>^ Os líderes de Sucote, porém, disseram: "Ainda não estão em seu poder Zeba e Zalmuna? Por que deveríamos dar pão às suas tropas? "

[[v7-8-7]]

^<<v7-8-7,7>>^ "É assim? ", replicou Gideão. "Quando o Senhor entregar Zeba e Zalmuna em minhas mãos, rasgarei a carne de vocês com espinhos e espinheiros do deserto. "

[[v7-8-8]]

^<<v7-8-8,8>>^ Dali subiu a Peniel e fez o mesmo pedido aos homens de Peniel, mas eles responderam como os de Sucote.

[[v7-8-9]]

^<<v7-8-9,9>>^ Aos homens de Peniel ele disse: "Quando eu voltar triunfante, destruirei esta fortaleza".

[[v7-8-10]]

^<<v7-8-10,10>>^ Ora, Zeba e Zalmuna estavam em Carcor, e com eles cerca de quinze mil homens. Estes foram todos os que sobraram dos exércitos dos povos que vinham do leste, pois cento e vinte mil homens que portavam espada tinham sido mortos.

[[v7-8-11]]

^<<v7-8-11,11>>^ Gideão subiu pela rota dos nômades, a leste de Noba e Jogbeá, e atacou de surpresa o exército.

[[v7-8-12]]

^<<v7-8-12,12>>^ Zeba e Zalmuna, os dois reis de Midiã, fugiram, mas ele os perseguiu e os capturou; derrotando também o exército.

[[v7-8-13]]

^<<v7-8-13,13>>^ Depois Gideão, filho de Joás, voltou da batalha pela subida de Heres.

[[v7-8-14]]

^<<v7-8-14,14>>^ Ele capturou um jovem de Sucote e o interrogou, e o jovem escreveu para Gideão os nomes dos setenta e sete líderes e autoridades da cidade.

[[v7-8-15]]

^<<v7-8-15,15>>^ Gideão foi então a Sucote e disse aos homens de lá: "Aqui estão Zeba e Zalmuna, acerca dos quais vocês zombaram de mim, dizendo: ‘Ainda não estão em seu poder Zeba e Zalmuna? Por que deveríamos dar pão aos seus homens exaustos? ’ "

[[v7-8-16]]

^<<v7-8-16,16>>^ Gideão prendeu os líderes da cidade de Sucote, castigando-os com espinhos e espinheiros do deserto;

[[v7-8-17]]

^<<v7-8-17,17>>^ derrubou a fortaleza de Peniel e matou os homens daquela cidade.

[[v7-8-18]]

^<<v7-8-18,18>>^ Então perguntou a Zeba e a Zalmuna: "Como eram os homens que vocês mataram em Tabor? " "Eram como você", responderam, "cada um tinha o porte de um príncipe".

[[v7-8-19]]

^<<v7-8-19,19>>^ Gideão prosseguiu: "Aqueles homens eram meus irmãos, filhos de minha própria mãe. Juro pelo nome do Senhor que, se vocês tivessem poupado a vida deles, eu não mataria vocês".

[[v7-8-20]]

^<<v7-8-20,20>>^ E Gideão voltou-se para Jéter, seu filho mais velho, e lhe disse: "Mate-os! " Jéter, porém, teve medo e não desembainhou a espada, pois era muito jovem.

[[v7-8-21]]

^<<v7-8-21,21>>^ Mas Zeba e Zalmuna disseram: "Venha, mate-nos você mesmo. Isso exige coragem de homem". Então Gideão avançou e os matou, e tirou os enfeites do pescoço dos camelos deles.

[[v7-8-22]]

^<<v7-8-22,22>>^ Os israelitas disseram a Gideão, "Reine sobre nós! você, seu filho e seu neto, pois você nos libertou das mãos de Midiã".

[[v7-8-23]]

^<<v7-8-23,23>>^ "Não reinarei sobre vocês", respondeu-lhes Gideão, "nem meu filho reinará sobre vocês. O Senhor reinará sobre vocês. "

[[v7-8-24]]

^<<v7-8-24,24>>^ E prosseguiu: "Só lhes faço um pedido: que cada um de vocês me dê um brinco da sua parte dos despojos". ( Os ismaelitas costumavam usar brincos de ouro. )

[[v7-8-25]]

^<<v7-8-25,25>>^ Eles responderam: "De boa vontade os daremos a você! " Então estenderam uma capa, e cada homem jogou sobre ela um brinco tirado de seus despojos.

[[v7-8-26]]

^<<v7-8-26,26>>^ O peso dos brincos de ouro chegou a vinte quilos e meio, sem contar os enfeites, os pendentes e as roupas de púrpura que os reis de Midiã usavam e os colares que estavam no pescoço de seus camelos.

[[v7-8-27]]

^<<v7-8-27,27>>^ Gideão usou o ouro para fazer um manto sacerdotal, que ele colocou em sua cidade, em Ofra. Todo o Israel prostituiu-se, fazendo dele objeto de adoração; e veio a ser uma armadilha para Gideão e sua família.

[[v7-8-28]]

^<<v7-8-28,28>>^ Assim Midiã foi subjugado pelos israelitas, e não tornou a erguer a cabeça. Durante a vida de Gideão a terra desfrutou paz quarenta anos.

[[v7-8-29]]

^<<v7-8-29,29>>^ Jerubaal, filho de Joás, retirou-se e foi para casa, onde ficou morando.

[[v7-8-30]]

^<<v7-8-30,30>>^ Teve setenta filhos, todos gerados por ele, pois tinha muitas mulheres.

[[v7-8-31]]

^<<v7-8-31,31>>^ Sua concubina, que morava em Siquém, também lhe deu um filho, a quem ele deu o nome de Abimeleque.

[[v7-8-32]]

^<<v7-8-32,32>>^ Gideão, filho de Joás, morreu em idade avançada e foi sepultado no túmulo de seu pai, Joás, em Ofra dos abiezritas.

[[v7-8-33]]

^<<v7-8-33,33>>^ Logo depois que Gideão morreu, os israelitas voltaram a prostituir-se com os baalins, cultuando-os. Ergueram Baal-Berite como seu deus, e

[[v7-8-34]]

^<<v7-8-34,34>>^ não se lembraram do Senhor, do seu Deus, que os tinha livrado das mãos dos seus inimigos em redor.

[[v7-8-35]]

^<<v7-8-35,35>>^ Também não foram bondosos com a família de Jerubaal, isto é, Gideão, reconhecendo todo o bem que ele tinha feito por Israel.

'''

xref:007-juizes/007-juizes-007.adoc#v7-7-0[&#60; Capítulo Anterior] | <<v7-8-0,Topo>> | xref:007-juizes/007-juizes-009.adoc#v7-9-0[Próximo Capítulo &#62;]