include::./index.adoc[]

[[v7-12-0]]
=== Juízes, 12
// nvi ?, NVI - Nova Versão Internacional

[[v7-12-1]]

^<<v7-12-1,1>>^ Os homens de Efraim foram convocados para a batalha; dirigiram-se para Zafom e disseram a Jefté: "Por que você foi lutar contra os amonitas sem nos chamar para irmos juntos? Vamos queimar a sua casa e você junto! "

[[v7-12-2]]

^<<v7-12-2,2>>^ Jefté respondeu: "Eu e meu povo estávamos envolvidos numa grande contenda com os amonitas, e, embora eu os tenha chamado, vocês não me livraram das mãos deles.

[[v7-12-3]]

^<<v7-12-3,3>>^ Quando vi que vocês não ajudariam, arrisquei a vida e fui lutar contra os amonitas, e o Senhor me deu a vitória sobre eles. E, por que vocês vieram para cá hoje? Para lutar contra mim? "

[[v7-12-4]]

^<<v7-12-4,4>>^ Jefté reuniu então todos os homens de Gileade e lutou contra Efraim. Os gileaditas feriram os efraimitas porque estes tinham dito: "Vocês, gileaditas, são desertores de Efraim e de Manassés".

[[v7-12-5]]

^<<v7-12-5,5>>^ Os gileaditas tomaram as passagens do Jordão que conduziam a Efraim. Sempre que um fugitivo de Efraim dizia: "Deixem-me atravessar", os homens de Gileade perguntavam: "Você é efraimita? " Se respondesse que não,

[[v7-12-6]]

^<<v7-12-6,6>>^ diziam "Então diga: ‘Chibolete’ ". Se ele dissesse: "Sibolete", sem conseguir pronunciar corretamente a palavra, prendiam-no e matavam-no no lugar de passagem do Jordão. Quarenta e dois mil efraimitas foram mortos naquela ocasião.

[[v7-12-7]]

^<<v7-12-7,7>>^ Jefté liderou Israel durante seis anos. Então o gileadita Jefté morreu, e foi sepultado numa cidade de Gileade.

[[v7-12-8]]

^<<v7-12-8,8>>^ Depois de Jefté, Ibsã, de Belém, liderou Israel.

[[v7-12-9]]

^<<v7-12-9,9>>^ Teve trinta filhos e trinta filhas. Deu suas filhas em casamento a homens de fora do seu clã, e trouxe para os seus filhos trinta mulheres de fora do seu clã. Ibsã liderou Israel durante sete anos.

[[v7-12-10]]

^<<v7-12-10,10>>^ Então Ibsã morreu, e foi sepultado em Belém.

[[v7-12-11]]

^<<v7-12-11,11>>^ Depois dele, Elom, da tribo de Zebulom, liderou Israel durante dez anos.

[[v7-12-12]]

^<<v7-12-12,12>>^ Elom morreu, e foi sepultado em Aijalom, na terra de Zebulom.

[[v7-12-13]]

^<<v7-12-13,13>>^ Depois dele, Abdom, filho de Hilel, de Piratom, liderou Israel.

[[v7-12-14]]

^<<v7-12-14,14>>^ Teve quarenta filhos e trinta netos, que montavam setenta jumentos. Abdom liderou Israel durante oito anos.

[[v7-12-15]]

^<<v7-12-15,15>>^ Então Abdom, filho de Hilel, morreu, e foi sepultado em Piratom, na terra de Efraim, na serra dos amalequitas.

'''

xref:007-juizes/007-juizes-011.adoc#v7-11-0[&#60; Capítulo Anterior] | <<v7-12-0,Topo>> | xref:007-juizes/007-juizes-013.adoc#v7-13-0[Próximo Capítulo &#62;]