include::./index.adoc[]

[[v7-9-0]]
=== Juízes, 9
// nvi ?, NVI - Nova Versão Internacional

[[v7-9-1]]

^<<v7-9-1,1>>^ Abimeleque, filho de Jerubaal, foi aos irmãos de sua mãe em Siquém e disse a eles e a todo o clã da família de sua mãe:

[[v7-9-2]]

^<<v7-9-2,2>>^ "Perguntem a todos os cidadãos de Siquém: O que é melhor para vocês: ter todos os setenta filhos de Jerubaal governando sobre vocês, ou somente um homem? Lembrem-se de que eu sou sua própria carne".

[[v7-9-3]]

^<<v7-9-3,3>>^ Os irmãos de sua mãe repetiram tudo aos cidadãos de Siquém, e estes se mostraram propensos a seguir Abimeleque, pois disseram: "Ele é nosso irmão".

[[v7-9-4]]

^<<v7-9-4,4>>^ Deram-lhe setenta peças de prata tiradas do templo de Baal-Berite, as quais Abimeleque usou para contratar alguns desocupados e vadios, que se tornaram seus seguidores.

[[v7-9-5]]

^<<v7-9-5,5>>^ Foi à casa de seu pai em Ofra e matou seus setenta irmãos, filhos de Jerubaal, sobre uma rocha. Mas Jotão, o filho mais novo de Jerubaal, escondeu-se e escapou.

[[v7-9-6]]

^<<v7-9-6,6>>^ Então todos os cidadãos de Siquém e de Bete-Milo reuniram-se ao lado do Carvalho, junto à coluna de Siquém, para coroar Abimeleque rei.

[[v7-9-7]]

^<<v7-9-7,7>>^ Quando Jotão soube disso, subiu ao topo do monte Gerizim e gritou para eles: "Ouçam-me, cidadãos de Siquém, para que Deus os ouça.

[[v7-9-8]]

^<<v7-9-8,8>>^ Certo dia as árvores saíram para ungir um rei para si. Disseram à oliveira: ‘Seja o nosso rei! ’

[[v7-9-9]]

^<<v7-9-9,9>>^ "A oliveira, porém, respondeu: ‘Deveria eu renunciar ao meu azeite, com o qual se presta honra aos deuses e aos homens, para dominar sobre as árvores? ’

[[v7-9-10]]

^<<v7-9-10,10>>^ "Então as árvores disseram à figueira: ‘Venha ser o nosso rei! ’

[[v7-9-11]]

^<<v7-9-11,11>>^ "A figueira, porém, respondeu: ‘Deveria eu renunciar ao meu fruto saboroso e doce, para dominar sobre as árvores? ’

[[v7-9-12]]

^<<v7-9-12,12>>^ "Depois as árvores disseram à videira: ‘Venha ser o nosso rei! ’

[[v7-9-13]]

^<<v7-9-13,13>>^ "A videira, porém, respondeu: ‘Deveria eu renunciar ao meu vinho, que alegra os deuses e os homens, para ter domínio sobre as árvores? ’

[[v7-9-14]]

^<<v7-9-14,14>>^ "Finalmente todas as árvores disseram ao espinheiro: ‘Venha ser o nosso rei! ’

[[v7-9-15]]

^<<v7-9-15,15>>^ "O espinheiro disse às árvores: ‘Se querem realmente ungir-me rei sobre vocês, venham abrigar-se à minha sombra; do contrário, sairá fogo do espinheiro e consumirá até os cedros do Líbano! ’

[[v7-9-16]]

^<<v7-9-16,16>>^ "Será que vocês agiram de fato com sinceridade quando fizeram Abimeleque rei? Foram justos com Jerubaal e sua família, como ele merecia?

[[v7-9-17]]

^<<v7-9-17,17>>^ Meu pai lutou por vocês e arriscou a vida para livrá-los das mãos de Midiã,

[[v7-9-18]]

^<<v7-9-18,18>>^ hoje, porém, vocês se revoltaram contra a família de meu pai, mataram seus setenta filhos sobre a mesma rocha, e proclamaram Abimeleque, o filho de sua escrava, rei sobre os cidadãos de Siquém pelo fato de ser irmão de vocês.

[[v7-9-19]]

^<<v7-9-19,19>>^ Se hoje vocês de fato agiram com sinceridade para com Jerubaal e sua família, alegrem-se com Abimeleque, e alegre-se ele com vocês!

[[v7-9-20]]

^<<v7-9-20,20>>^ Entretanto, se não foi assim, que saia fogo de Abimeleque e consuma os cidadãos de Siquém e de Bete-Milo, e que saia fogo dos cidadãos de Siquém e de Bete-Milo, e consuma Abimeleque! "

[[v7-9-21]]

^<<v7-9-21,21>>^ Depois Jotão fugiu para Beer, e foi morar ali, longe de seu irmão Abimeleque.

[[v7-9-22]]

^<<v7-9-22,22>>^ Fazia três anos que Abimeleque governava Israel,

[[v7-9-23]]

^<<v7-9-23,23>>^ quando Deus enviou um espírito maligno entre Abimeleque e os cidadãos de Siquém, e estes agiram traiçoeiramente contra Abimeleque.

[[v7-9-24]]

^<<v7-9-24,24>>^ Isso aconteceu para que o crime contra os setenta filhos de Jerubaal, o derramamento do sangue deles, fosse vingado em seu irmão Abimeleque e nos cidadãos de Siquém que o ajudaram a assassinar os seus irmãos.

[[v7-9-25]]

^<<v7-9-25,25>>^ Os cidadãos de Siquém enviaram homens para o alto das colinas para emboscarem os que passassem por ali, e Abimeleque foi informado disso.

[[v7-9-26]]

^<<v7-9-26,26>>^ Nesse meio tempo Gaal, filho de Ebede, mudou-se com seus parentes para Siquém, cujos cidadãos confiavam nele.

[[v7-9-27]]

^<<v7-9-27,27>>^ Sucedeu que foram ao campo, colheram uvas, pisaram-nas, e fizeram uma festa no templo do seu deus. Comendo e bebendo, amaldiçoaram Abimeleque.

[[v7-9-28]]

^<<v7-9-28,28>>^ Então Gaal, filho de Ebede, disse: "Quem é Abimeleque para que o sirvamos? E quem é Siquém? Não é ele o filho de Jerubaal, e não é Zebul o seu representante? Sirvam aos homens de Hamor, o pai de Siquém! Por que servir a Abimeleque?

[[v7-9-29]]

^<<v7-9-29,29>>^ Ah! Se eu tivesse esse povo sob o meu comando! Eu me livraria dele. E diria a Abimeleque: ‘Mobilize o seu exército e venha! ’"

[[v7-9-30]]

^<<v7-9-30,30>>^ Quando Zebul, o governante da cidade, ouviu o que dizia Gaal, filho de Ebede, ficou indignado.

[[v7-9-31]]

^<<v7-9-31,31>>^ Secretamente enviou mensageiros a Abimeleque dizendo: "Gaal, filho de Ebede, e seus parentes vieram a Siquém e estão agitando a cidade contra você.

[[v7-9-32]]

^<<v7-9-32,32>>^ Venha de noite, você e seus homens, e fiquem à espera no campo.

[[v7-9-33]]

^<<v7-9-33,33>>^ De manhã, ao nascer do sol, avance contra a cidade. Quando Gaal e sua tropa atacarem, faça com eles o que achar melhor".

[[v7-9-34]]

^<<v7-9-34,34>>^ E assim Abimeleque e todas as suas tropas partiram de noite e prepararam emboscadas perto de Siquém, em quatro companhias.

[[v7-9-35]]

^<<v7-9-35,35>>^ Ora, Gaal, filho de Ebede, tinha saído e estava à porta da cidade quando Abimeleque e seus homens saíram da sua emboscada.

[[v7-9-36]]

^<<v7-9-36,36>>^ Quando Gaal os viu, disse a Zebul: "Veja, vem gente descendo do alto das colinas! " Zebul, porém, respondeu: "Você está confundindo as sombras dos montes com homens".

[[v7-9-37]]

^<<v7-9-37,37>>^ Mas Gaal tornou a falar: "Veja, vem gente descendo da parte central do território, e uma companhia está vindo pelo caminho do carvalho dos Adivinhadores".

[[v7-9-38]]

^<<v7-9-38,38>>^ Disse-lhe Zebul: "Onde está toda aquela sua conversa? Você dizia: ‘Quem é Abimeleque, para que o sirvamos? ’ Não são estes os homens que você ridicularizou? Saia e lute contra eles! "

[[v7-9-39]]

^<<v7-9-39,39>>^ Então Gaal conduziu para fora os cidadãos de Siquém e lutou contra Abimeleque.

[[v7-9-40]]

^<<v7-9-40,40>>^ Abimeleque o perseguiu, e ele fugiu. Muitos dos homens de Siquém caíram mortos ao longo de todo o caminho, até à porta da cidade.

[[v7-9-41]]

^<<v7-9-41,41>>^ Abimeleque permaneceu em Arumá. E Zebul expulsou Gaal e os seus parentes de Siquém.

[[v7-9-42]]

^<<v7-9-42,42>>^ No dia seguinte o povo de Siquém saiu aos campos, e Abimeleque ficou sabendo disso.

[[v7-9-43]]

^<<v7-9-43,43>>^ Então dividiu os seus homens em três companhias e armou emboscadas no campo. Quando viu o povo saindo da cidade, levantou-se contra ele e atacou-o.

[[v7-9-44]]

^<<v7-9-44,44>>^ Abimeleque e as tropas que estavam com ele avançaram até à porta da cidade. Então duas companhias avançaram sobre os que estavam nos campos e os mataram.

[[v7-9-45]]

^<<v7-9-45,45>>^ E Abimeleque atacou a cidade o dia todo, até conquistá-la e matar o seu povo. Depois destruiu a cidade e espalhou sal sobre ela.

[[v7-9-46]]

^<<v7-9-46,46>>^ Ao saberem disso, os cidadãos que estavam na torre de Siquém entraram na fortaleza do templo de El-Berite.

[[v7-9-47]]

^<<v7-9-47,47>>^ Quando Abimeleque soube que se haviam reunido lá,

[[v7-9-48]]

^<<v7-9-48,48>>^ ele e todos os seus homens subiram o monte Zalmom. Ele apanhou um machado e cortou um galho de árvore e o pôs nos ombros. Então deu esta ordem aos homens que estavam com ele: "Rápido! Façam o que eu fizer! "

[[v7-9-49]]

^<<v7-9-49,49>>^ Todos os homens cortaram galhos e seguiram Abimeleque. Empilharam os galhos junto à fortaleza e a incendiaram. Assim morreu também o povo que estava na torre de Siquém, cerca de mil homens e mulheres.

[[v7-9-50]]

^<<v7-9-50,50>>^ A seguir Abimeleque foi a Tebes, sitiou-a e conquistou-a.

[[v7-9-51]]

^<<v7-9-51,51>>^ Mas dentro da cidade havia uma torre bastante forte, para a qual fugiram todos os homens e mulheres, todo o povo da cidade. Trancaram-se por dentro e subiram para o telhado da torre.

[[v7-9-52]]

^<<v7-9-52,52>>^ Abimeleque foi para a torre e atacou-a. E, quando se aproximava da entrada da torre para incendiá-la,

[[v7-9-53]]

^<<v7-9-53,53>>^ uma mulher jogou-lhe uma pedra de moinho na cabeça, que lhe rachou o crânio.

[[v7-9-54]]

^<<v7-9-54,54>>^ Imediatamente ele chamou seu escudeiro e lhe ordenou: "Tire a espada e mate-me, para que não digam que uma mulher me matou". Então o jovem o atravessou, e ele morreu.

[[v7-9-55]]

^<<v7-9-55,55>>^ Quando os israelitas viram que Abimeleque estava morto, voltaram para casa.

[[v7-9-56]]

^<<v7-9-56,56>>^ Assim Deus retribuiu a maldade que Abimeleque praticara contra o seu pai, matando os seus setenta irmãos.

[[v7-9-57]]

^<<v7-9-57,57>>^ Deus fez também os homens de Siquém pagarem por toda a sua maldade. A maldição de Jotão, filho de Jerubaal, caiu sobre eles.

'''

xref:007-juizes/007-juizes-008.adoc#v7-8-0[&#60; Capítulo Anterior] | <<v7-9-0,Topo>> | xref:007-juizes/007-juizes-010.adoc#v7-10-0[Próximo Capítulo &#62;]