include::./index.adoc[]

[[v7-3-0]]
=== Juízes, 3
// nvi ?, NVI - Nova Versão Internacional

[[v7-3-1]]

^<<v7-3-1,1>>^ São estas as nações que o Senhor deixou para pôr à prova todos os israelitas que não tinham visto nenhuma das guerras em Canaã

[[v7-3-2]]

^<<v7-3-2,2>>^ ( fez isso apenas para treinar na guerra os descendentes dos israelitas, pois não tinham tido experiência anterior de combate ):

[[v7-3-3]]

^<<v7-3-3,3>>^ os cinco governantes dos filisteus, todos os cananeus, os sidônios e os heveus que viviam nos montes do Líbano, desde o monte Baal-Hermom até Lebo-Hamate.

[[v7-3-4]]

^<<v7-3-4,4>>^ Essas nações foram deixadas para que por elas os israelitas fossem postos à prova, se obedeceriam aos mandamentos que o Senhor dera aos seus antepassados por meio de Moisés.

[[v7-3-5]]

^<<v7-3-5,5>>^ Os israelitas viviam entre os cananeus, os hititas, os amorreus, os ferezeus, os heveus e os jebuseus.

[[v7-3-6]]

^<<v7-3-6,6>>^ Tomaram as filhas deles em casamento e deram suas filhas aos filhos deles, e prestaram culto aos deuses deles.

[[v7-3-7]]

^<<v7-3-7,7>>^ Os israelitas fizeram o que o Senhor reprova, pois esqueceram-se do Senhor seu Deus e prestaram culto aos baalins e aos postes sagrados.

[[v7-3-8]]

^<<v7-3-8,8>>^ Acendeu-se a ira do Senhor de tal forma contra Israel que ele os entregou nas mãos de Cuchã-Risataim, rei da Mesopotâmia, por quem os israelitas foram subjugados durante oito anos.

[[v7-3-9]]

^<<v7-3-9,9>>^ Mas, quando clamaram ao Senhor, ele lhes levantou um libertador, Otoniel, filho de Quenaz, o irmão mais novo de Calebe, que os libertou.

[[v7-3-10]]

^<<v7-3-10,10>>^ O Espírito do Senhor veio sobre ele, de modo que liderou Israel e foi à guerra. O Senhor entregou Cuchã-Risataim, rei de Arã, nas mãos de Otoniel, que prevaleceu contra ele.

[[v7-3-11]]

^<<v7-3-11,11>>^ E a terra teve paz durante quarenta anos, até a morte de Otoniel, filho de Quenaz.

[[v7-3-12]]

^<<v7-3-12,12>>^ Mais uma vez os israelitas fizeram o que o Senhor reprova, e por isso o Senhor deu a Eglom, rei de Moabe, poder sobre Israel.

[[v7-3-13]]

^<<v7-3-13,13>>^ Conseguindo uma aliança com os amonitas e com os amalequitas, Eglom veio e derrotou Israel, e conquistou a Cidade das Palmeiras.

[[v7-3-14]]

^<<v7-3-14,14>>^ Os israelitas ficaram sob o domínio de Eglom, rei de Moabe, durante dezoito anos.

[[v7-3-15]]

^<<v7-3-15,15>>^ Novamente os israelitas clamaram ao Senhor, que lhes deu um libertador chamado Eúde, homem canhoto, filho do benjamita Gera. Os israelitas o enviaram com o pagamento de tributos a Eglom, rei de Moabe.

[[v7-3-16]]

^<<v7-3-16,16>>^ Eúde havia feito uma espada de dois gumes, de quarenta e cinco centímetros de comprimento, e a tinha amarrado na coxa direita, debaixo da roupa.

[[v7-3-17]]

^<<v7-3-17,17>>^ Ele entregou o tributo a Eglom, rei de Moabe, homem muito gordo.

[[v7-3-18]]

^<<v7-3-18,18>>^ Em seguida, Eúde mandou embora os carregadores.

[[v7-3-19]]

^<<v7-3-19,19>>^ Junto aos ídolos que estão perto de Gilgal, ele voltou e disse: "Tenho uma mensagem secreta para ti, ó rei". O rei respondeu: "Calado! " E todos os seus auxiliares saíram de sua presença.

[[v7-3-20]]

^<<v7-3-20,20>>^ Eúde aproximou-se do rei, que estava sentado sozinho na sala superior do palácio de verão, e repetiu: "Tenho uma mensagem de Deus para ti". Quando o rei se levantou do trono,

[[v7-3-21]]

^<<v7-3-21,21>>^ Eúde estendeu a mão esquerda, apanhou a espada de sua coxa direita e cravou-a na barriga do rei.

[[v7-3-22]]

^<<v7-3-22,22>>^ Até o cabo penetrou com a lâmina; e, como não tirou a espada, a gordura se fechou sobre ela.

[[v7-3-23]]

^<<v7-3-23,23>>^ Então Eúde saiu para o pórtico, depois de fechar e trancar as portas da sala atrás de si.

[[v7-3-24]]

^<<v7-3-24,24>>^ Depois que ele saiu, vieram os servos e encontraram trancadas as portas da sala superior, e disseram: "Ele deve estar fazendo suas necessidades em seu cômodo privativo".

[[v7-3-25]]

^<<v7-3-25,25>>^ Cansaram-se de esperar, e como ele não abria a porta da sala, pegaram a chave e a abriram. E lá estava o seu senhor, caído no chão, morto!

[[v7-3-26]]

^<<v7-3-26,26>>^ Enquanto esperavam, Eúde escapou. Passou pelos ídolos e fugiu para Seirá.

[[v7-3-27]]

^<<v7-3-27,27>>^ Quando chegou, tocou a trombeta nos montes de Efraim, e os israelitas desceram dos montes, com ele à sua frente.

[[v7-3-28]]

^<<v7-3-28,28>>^ "Sigam-me", ordenou, "pois o Senhor entregou Moabe, o inimigo de vocês, em suas mãos. " Eles o seguiram e, tomaram posse do lugar de passagem do Jordão que levava a Moabe, e não deixaram ninguém atravessar o rio.

[[v7-3-29]]

^<<v7-3-29,29>>^ Naquela ocasião mataram cerca de dez mil moabitas, todos eles fortes e vigorosos; nem um só homem escapou.

[[v7-3-30]]

^<<v7-3-30,30>>^ Naquele dia Moabe foi subjugado por Israel, e a terra teve paz durante oitenta anos.

[[v7-3-31]]

^<<v7-3-31,31>>^ Depois de Eúde veio Sangar, filho de Anate, que matou seiscentos filisteus com uma aguilhada de bois. Ele também libertou Israel.

'''

xref:007-juizes/007-juizes-002.adoc#v7-2-0[&#60; Capítulo Anterior] | <<v7-3-0,Topo>> | xref:007-juizes/007-juizes-004.adoc#v7-4-0[Próximo Capítulo &#62;]