include::./index.adoc[]

[[v29-2-0]]
=== Joel, 2
// nvi ?, NVI - Nova Versão Internacional

[[v29-2-1]]

^<<v29-2-1,1>>^ Toquem a trombeta em Sião; dêem o alarme no meu santo monte. Tremam todos os habitantes do país, pois o dia do Senhor está chegando. Está próximo!

[[v29-2-2]]

^<<v29-2-2,2>>^ É dia de trevas e de escuridão, dia de nuvens e negridão. Assim como a luz da aurora estende-se pelos montes, um grande e poderoso exército se aproxima, como nunca antes se viu nem jamais se verá nas gerações futuras.

[[v29-2-3]]

^<<v29-2-3,3>>^ Diante deles o fogo devora, atrás deles arde uma chama. Diante deles a terra é como o jardim do Éden, atrás deles, um deserto arrasado; nada lhes escapa.

[[v29-2-4]]

^<<v29-2-4,4>>^ Eles têm a aparência de cavalos; como cavalaria, atacam galopando.

[[v29-2-5]]

^<<v29-2-5,5>>^ Com um barulho semelhante ao de carros saltam sobre os cumes dos montes, como um fogo crepitante que consome o restolho, como um exército poderoso em posição de combate.

[[v29-2-6]]

^<<v29-2-6,6>>^ Diante deles povos se contorcem angustiados; todos os rostos ficam pálidos de medo.

[[v29-2-7]]

^<<v29-2-7,7>>^ Eles atacam como guerreiros; escalam muralhas como soldados. Todos eles marcham em linha, sem desviar-se do curso.

[[v29-2-8]]

^<<v29-2-8,8>>^ Não se empurram uns aos outros; cada um marcha sempre em frente. Avançam por entre os dardos sem desfazer a formação.

[[v29-2-9]]

^<<v29-2-9,9>>^ Lançam-se sobre a cidade; correm ao longo da muralha. Sobem nas casas; como ladrões entram pelas janelas.

[[v29-2-10]]

^<<v29-2-10,10>>^ Diante deles a terra treme, o céu estremece, o sol e a lua escurecem, e as estrelas param de brilhar.

[[v29-2-11]]

^<<v29-2-11,11>>^ O Senhor levanta a sua voz à frente do seu exército; Como é grande o seu exército! Como são poderosos os que obedecem à sua ordem! Como é grande o dia do Senhor! Como será terrível! Quem poderá suportá-lo?

[[v29-2-12]]

^<<v29-2-12,12>>^ "Agora, porém", declara o Senhor, "voltem-se para mim de todo o coração, com jejum, lamento e pranto. "

[[v29-2-13]]

^<<v29-2-13,13>>^ Rasguem o coração, e não as vestes. Voltem-se para o Senhor, para o seu Deus, pois ele é misericordioso e compassivo, muito paciente e cheio de amor; arrepende-se, e não envia a desgraça.

[[v29-2-14]]

^<<v29-2-14,14>>^ Talvez ele volte atrás, arrependa-se, e ao passar deixe uma bênção. Assim vocês poderão fazer ofertas de cereal e ofertas derramadas para o Senhor, o seu Deus.

[[v29-2-15]]

^<<v29-2-15,15>>^ Toquem a trombeta em Sião, decretem jejum santo, convoquem uma assembléia sagrada.

[[v29-2-16]]

^<<v29-2-16,16>>^ Reúnam o povo, consagrem a assembléia; ajuntem os anciãos, reúnam as crianças, aquelas que mamam no peito. Até os recém-casados devem deixar os seus aposentos.

[[v29-2-17]]

^<<v29-2-17,17>>^ Que os sacerdotes, que ministram perante o Senhor, chorem entre o pórtico do templo e o altar, orando: "Poupa o teu povo, Senhor. Não faças da tua herança motivo de zombaria e de piada entre as nações. Porque se haveria de dizer entre os povos: ‘Onde está o Deus deles? ’ "

[[v29-2-18]]

^<<v29-2-18,18>>^ Então o Senhor mostrou zelo por sua terra e teve piedade do seu povo.

[[v29-2-19]]

^<<v29-2-19,19>>^ O Senhor respondeu ao seu povo: "Estou lhes enviando trigo, vinho novo e azeite, o suficiente para satisfazê-los plenamente; nunca mais farei de vocês motivo de zombaria para as nações.

[[v29-2-20]]

^<<v29-2-20,20>>^ "Levarei o invasor que vem do norte para longe de vocês, empurrando-o para uma terra seca e estéril, a vanguarda para o mar oriental e a retaguarda para o mar ocidental. E a sua podridão subirá; o seu mau cheiro se espalhará". Ele tem feito coisas grandiosas!

[[v29-2-21]]

^<<v29-2-21,21>>^ Não tenha medo, ó terra; regozije-se e alegre-se. O Senhor tem feito coisas grandiosas!

[[v29-2-22]]

^<<v29-2-22,22>>^ Não tenham medo, animais do campo, pois as pastagens estão ficando verdes. As árvores estão dando os seus frutos; a figueira e a videira ficam carregadas.

[[v29-2-23]]

^<<v29-2-23,23>>^ Ó povo de Sião, alegre-se e regozije-se no Senhor, no seu Deus, pois ele lhe dá as chuvas de outono, conforme a sua justiça. Ele lhe envia muitas chuvas, as de outono e as de primavera, como antes fazia.

[[v29-2-24]]

^<<v29-2-24,24>>^ As eiras ficarão cheias de trigo; os tonéis transbordarão de vinho novo e de azeite.

[[v29-2-25]]

^<<v29-2-25,25>>^ "Vou compensá-los pelos anos de colheitas que os gafanhotos destruíram: o gafanhoto peregrino, o gafanhoto devastador, o gafanhoto devorador e o gafanhoto cortador, o meu grande exército que enviei contra vocês.

[[v29-2-26]]

^<<v29-2-26,26>>^ Vocês comerão até ficarem satisfeitos, e louvarão o nome do Senhor, o seu Deus, que fez maravilhas em favor de vocês; nunca mais o meu povo será humilhado.

[[v29-2-27]]

^<<v29-2-27,27>>^ Então vocês saberão que eu estou no meio de Israel. Eu sou o Senhor, o seu Deus, e não há nenhum outro; nunca mais o meu povo será humilhado.

[[v29-2-28]]

^<<v29-2-28,28>>^ "E, depois disso, derramarei do meu Espírito sobre todos os povos. Os seus filhos e as suas filhas profetizarão, os velhos terão sonhos, os jovens terão visões.

[[v29-2-29]]

^<<v29-2-29,29>>^ Até sobre os servos e as servas derramarei do meu Espírito naqueles dias.

[[v29-2-30]]

^<<v29-2-30,30>>^ Mostrarei maravilhas no céu e na terra, sangue, fogo e nuvens de fumaça.

[[v29-2-31]]

^<<v29-2-31,31>>^ O sol se tornará em trevas, e a lua em sangue; antes que venha o grande e terrível dia do Senhor.

[[v29-2-32]]

^<<v29-2-32,32>>^ E todo aquele que invocar o nome do Senhor será salvo, pois, conforme prometeu o Senhor, no monte Sião e em Jerusalém haverá livramento para os sobreviventes, para aqueles a quem o Senhor chamar.

'''

xref:029-joel/029-joel-001.adoc#v29-1-0[&#60; Capítulo Anterior] | <<v29-2-0,Topo>> | xref:029-joel/029-joel-003.adoc#v29-3-0[Próximo Capítulo &#62;]