include::./index.adoc[]

[[v29-3-0]]
=== Joel, 3
// nvi ?, NVI - Nova Versão Internacional

[[v29-3-1]]

^<<v29-3-1,1>>^ "Sim, naqueles dias e naquele tempo, quando eu restaurar a sorte de Judá e de Jerusalém,

[[v29-3-2]]

^<<v29-3-2,2>>^ reunirei todos os povos e os farei descer ao vale de Josafá. Ali os julgarei por causa da minha herança, Israel, o meu povo pois espalharam o meu povo entre as nações e repartiram entre si a minha terra.

[[v29-3-3]]

^<<v29-3-3,3>>^ Tiraram sortes sobre o meu povo e deram meninos em troca de prostitutas; venderam meninas por vinho, para se embriagarem.

[[v29-3-4]]

^<<v29-3-4,4>>^ "Que é que vocês têm contra mim, Tiro, Sidom, e todas as regiões da Filístia? Vocês estão me retribuindo por algo que eu lhes fiz? Se estão querendo vingar-se de mim, com agilidade e rapidez me vingarei do que vocês têm feito.

[[v29-3-5]]

^<<v29-3-5,5>>^ Pois roubaram a minha prata e o meu ouro e levaram para os seus templos os meus tesouros mais valiosos.

[[v29-3-6]]

^<<v29-3-6,6>>^ Vocês venderam o povo de Judá e de Jerusalém aos gregos, mandando-os para longe da sua terra natal.

[[v29-3-7]]

^<<v29-3-7,7>>^ "Vou tirá-los dos lugares para onde os venderam, e sobre vocês farei cair o que fizeram:

[[v29-3-8]]

^<<v29-3-8,8>>^ Venderei os filhos e as filhas de vocês ao povo de Judá, e eles os venderão à distante nação dos sabeus". Assim disse o Senhor.

[[v29-3-9]]

^<<v29-3-9,9>>^ Proclamem isto entre as nações: Preparem-se para a guerra! Despertem os guerreiros! Todos os homens de guerra aproximem-se e ataquem.

[[v29-3-10]]

^<<v29-3-10,10>>^ Forjem os seus arados, fazendo deles espadas; e de suas foices, façam lanças. Diga o fraco: "Sou um guerreiro! "

[[v29-3-11]]

^<<v29-3-11,11>>^ Venham depressa, vocês, nações vizinhas, e reúnam-se ali. Faze descer os teus guerreiros, ó Senhor!

[[v29-3-12]]

^<<v29-3-12,12>>^ "Despertem, nações; avancem para o vale de Josafá, pois ali me sentarei para julgar todas as nações vizinhas.

[[v29-3-13]]

^<<v29-3-13,13>>^ Lancem a foice, pois a colheita está madura. Venham, pisem com força as uvas, pois o lagar está cheio e os tonéis transbordam, tão grande é a maldade dessas nações! "

[[v29-3-14]]

^<<v29-3-14,14>>^ Multidões, multidões no vale da Decisão! Pois o dia do Senhor está próximo, no vale da Decisão.

[[v29-3-15]]

^<<v29-3-15,15>>^ O sol e a lua escurecerão, e as estrelas já não brilharão.

[[v29-3-16]]

^<<v29-3-16,16>>^ O Senhor rugirá de Sião e de Jerusalém levantará a sua voz; a terra e o céu tremerão. Mas o Senhor será um refúgio para o seu povo, uma fortaleza para Israel.

[[v29-3-17]]

^<<v29-3-17,17>>^ "Então vocês saberão que eu sou o Senhor, o seu Deus, que habito em Sião, o meu santo monte. Jerusalém será santa; e estrangeiros jamais a conquistarão".

[[v29-3-18]]

^<<v29-3-18,18>>^ "Naquele dia os montes gotejarão vinho novo; das colinas manará leite; todos os ribeiros de Judá terão água corrente. Uma fonte fluirá do templo do Senhor e regará o vale das Acácias.

[[v29-3-19]]

^<<v29-3-19,19>>^ Mas o Egito ficará desolado, Edom será um deserto arrasado, por causa da violência feita ao povo de Judá, em cuja terra derramaram sangue inocente.

[[v29-3-20]]

^<<v29-3-20,20>>^ Judá será habitada para sempre e Jerusalém por todas as gerações.

[[v29-3-21]]

^<<v29-3-21,21>>^ Sua culpa de sangue, ainda não perdoada, eu a perdoarei. " O Senhor habita em Sião!

'''

xref:029-joel/029-joel-002.adoc#v29-2-0[&#60; Capítulo Anterior] | <<v29-3-0,Topo>> | xref:030-amos/030-amos-001.adoc#v30-1-0[Próximo Capítulo &#62;]