include::./index.adoc[]

[[v23-23-0]]
=== Isaías, 23
// nvi ?, NVI - Nova Versão Internacional

[[v23-23-1]]

^<<v23-23-1,1>>^ Advertência contra Tiro: Pranteiem, navios de Társis! Pois Tiro foi destruída e ficou sem casa e sem porto. De Chipre lhe veio essa mensagem.

[[v23-23-2]]

^<<v23-23-2,2>>^ Fiquem calados, habitantes das regiões litorâneas, e vocês, mercadores de Sidom, enriquecidos pelos que atravessam o mar

[[v23-23-3]]

^<<v23-23-3,3>>^ e as grandes águas. O trigo de Sior e a colheita do Nilo eram a sua renda, e vocês se tornaram o suprimento das nações.

[[v23-23-4]]

^<<v23-23-4,4>>^ Envergonhe-se, Sidom, pois o mar, a fortaleza do mar, falou: "Não estive em trabalho de parto nem dei à luz; não criei filhos nem eduquei filhas".

[[v23-23-5]]

^<<v23-23-5,5>>^ Quando a notícia chegar ao Egito, ficarão angustiados com as novidades de Tiro.

[[v23-23-6]]

^<<v23-23-6,6>>^ Cruzem o mar para Társis; pranteiem, vocês, habitantes das regiões litorâneas.

[[v23-23-7]]

^<<v23-23-7,7>>^ É esta a cidade jubilosa que existe desde tempos muito antigos, cujos pés levaram a conquistar terras distantes?

[[v23-23-8]]

^<<v23-23-8,8>>^ Quem planejou isso contra Tiro, contra aquela que dava coroas, cujos comerciantes são príncipes, cujos negociantes são famosos em toda terra?

[[v23-23-9]]

^<<v23-23-9,9>>^ O Senhor dos Exércitos o planejou para abater todo orgulho e vaidade e humilhar todos os que tem fama na terra.

[[v23-23-10]]

^<<v23-23-10,10>>^ Cultive a sua terra como se cultiva as margens do Nilo, ó povo de Társis, pois você não tem mais porto.

[[v23-23-11]]

^<<v23-23-11,11>>^ O Senhor estendeu a mão sobre o mar e fez tremer seus reinos. Acerca da Fenícia ordenou que as suas fortalezas sejam destruídas,

[[v23-23-12]]

^<<v23-23-12,12>>^ e disse: "Você não se alegrará mais, ó cidade de Sidom, virgem derrotada! "Levante-se, atravesse o mar até Chipre; nem lá você terá descanso".

[[v23-23-13]]

^<<v23-23-13,13>>^ Olhem para a terra dos babilônios, esse é o povo que não existe mais! Os assírios o deixaram para as criaturas do deserto; ergueram torres de vigia, despojaram suas cidadelas e fizeram dela uma ruína.

[[v23-23-14]]

^<<v23-23-14,14>>^ Pranteiem, vocês, navios de Társis; destruída está a sua fortaleza!

[[v23-23-15]]

^<<v23-23-15,15>>^ Naquele tempo Tiro será esquecida por setenta anos, o tempo da vida de um rei. Mas no fim dos setenta anos, acontecerá com Tiro o que diz a canção da prostituta:

[[v23-23-16]]

^<<v23-23-16,16>>^ "Pegue a harpa, vá pela cidade, ó prostituta esquecida; toque a harpa, cante muitas canções, para se lembrarem de você".

[[v23-23-17]]

^<<v23-23-17,17>>^ No fim dos setenta anos o Senhor se lembrará de Tiro. Esta voltará ao seu ofício de prostituta e servirá a todos os reinos que há na face da terra.

[[v23-23-18]]

^<<v23-23-18,18>>^ Mas o seu lucro e a sua renda serão separados para o Senhor; não serão guardados nem depositados. Seus lucros irão para os que vivem na presença do Senhor, para que tenham bastante comida e roupas finas.

'''

xref:023-isaias/023-isaias-022.adoc#v23-22-0[&#60; Capítulo Anterior] | <<v23-23-0,Topo>> | xref:023-isaias/023-isaias-024.adoc#v23-24-0[Próximo Capítulo &#62;]