include::./index.adoc[]

[[v23-53-0]]
=== Isaías, 53
// nvi ?, NVI - Nova Versão Internacional

[[v23-53-1]]

^<<v23-53-1,1>>^ Quem creu em nossa mensagem e a quem foi revelado o braço do Senhor?

[[v23-53-2]]

^<<v23-53-2,2>>^ Ele cresceu diante dele como um broto tenro, e como uma raiz saída de uma terra seca. Ele não tinha qualquer beleza ou majestade que nos atraísse, nada em sua aparência para que o desejássemos.

[[v23-53-3]]

^<<v23-53-3,3>>^ Foi desprezado e rejeitado pelos homens, um homem de tristeza e familiarizado com o sofrimento. Como alguém de quem os homens escondem o rosto, foi desprezado, e nós não o tínhamos em estima.

[[v23-53-4]]

^<<v23-53-4,4>>^ Certamente ele tomou sobre si as nossas enfermidades e sobre si levou as nossas doenças, contudo nós o consideramos castigado por Deus, por ele atingido e afligido.

[[v23-53-5]]

^<<v23-53-5,5>>^ Mas ele foi transpassado por causa das nossas transgressões, foi esmagado por causa de nossas iniqüidades; o castigo que nos trouxe paz estava sobre ele, e pelas suas feridas fomos curados.

[[v23-53-6]]

^<<v23-53-6,6>>^ Todos nós, tal qual ovelhas, nos desviamos, cada um de nós se voltou para o seu próprio caminho; e o Senhor fez cair sobre ele a iniqüidade de todos nós.

[[v23-53-7]]

^<<v23-53-7,7>>^ Ele foi oprimido e afligido, contudo não abriu a sua boca; como um cordeiro foi levado para o matadouro, e como uma ovelha que diante de seus tosquiadores fica calada, ele não abriu a sua boca.

[[v23-53-8]]

^<<v23-53-8,8>>^ Com julgamento opressivo ele foi levado. E quem pode falar dos seus descendentes? Pois ele foi eliminado da terra dos viventes; por causa da transgressão do meu povo ele foi golpeado.

[[v23-53-9]]

^<<v23-53-9,9>>^ Foi-lhe dado um túmulo com os ímpios, e com os ricos em sua morte, embora não tivesse cometido qualquer violência nem houvesse qualquer mentira em sua boca.

[[v23-53-10]]

^<<v23-53-10,10>>^ Contudo foi da vontade do Senhor esmagá-lo e fazê-lo sofrer, e, embora o Senhor faça da vida dele uma oferta pela culpa, ele verá sua prole e prolongará seus dias, e a vontade do Senhor prosperará em sua mão.

[[v23-53-11]]

^<<v23-53-11,11>>^ Depois do sofrimento de sua alma, ele verá a luz e ficará satisfeito; pelo seu conhecimento meu servo justo justificará a muitos, e levará a iniqüidade deles.

[[v23-53-12]]

^<<v23-53-12,12>>^ Por isso eu lhe darei uma porção entre os grandes, e ele dividirá os despojos com os fortes, porquanto ele derramou sua vida até à morte, e foi contado entre os transgressores. Pois ele carregou o pecado de muitos, e intercedeu pelos transgressores.

'''

xref:023-isaias/023-isaias-052.adoc#v23-52-0[&#60; Capítulo Anterior] | <<v23-53-0,Topo>> | xref:023-isaias/023-isaias-054.adoc#v23-54-0[Próximo Capítulo &#62;]