include::./index.adoc[]

[[v23-4-0]]
=== Isaías, 4
// nvi ?, NVI - Nova Versão Internacional

[[v23-4-1]]

^<<v23-4-1,1>>^ Naquele dia sete mulheres agarrarão um homem e dirão: "Nós mesmas providenciaremos nossa comida e nossas roupas; apenas case-se conosco e livre-nos da vergonha de sermos solteiras! "

[[v23-4-2]]

^<<v23-4-2,2>>^ Naquele dia o Renovo do Senhor será belo e glorioso, e o fruto da terra será o orgulho e a glória dos sobreviventes de Israel.

[[v23-4-3]]

^<<v23-4-3,3>>^ Os que forem deixados em Sião e ficarem em Jerusalém serão chamados santos: todos os inscritos para viverem em Jerusalém.

[[v23-4-4]]

^<<v23-4-4,4>>^ Quando o Senhor tiver lavado a impureza das mulheres de Sião, e tiver limpado por meio de um espírito de julgamento e de um espírito de fogo o sangue derramado em Jerusalém,

[[v23-4-5]]

^<<v23-4-5,5>>^ o Senhor criará sobre todo o monte Sião e sobre aqueles que se reunirem ali uma nuvem de dia e um clarão de fogo de noite. A glória tudo cobrirá

[[v23-4-6]]

^<<v23-4-6,6>>^ e será um abrigo e sombra para o calor do dia, refúgio e esconderijo contra a tempestade e a chuva.

'''

xref:023-isaias/023-isaias-003.adoc#v23-3-0[&#60; Capítulo Anterior] | <<v23-4-0,Topo>> | xref:023-isaias/023-isaias-005.adoc#v23-5-0[Próximo Capítulo &#62;]