include::./index.adoc[]

[[v23-22-0]]
=== Isaías, 22
// nvi ?, NVI - Nova Versão Internacional

[[v23-22-1]]

^<<v23-22-1,1>>^ Advertência contra o vale da Visão: O que está perturbando vocês agora, o que os levou a se refugiarem nos terraços,

[[v23-22-2]]

^<<v23-22-2,2>>^ cidade cheia de agitação cidade de tumulto e alvoroço? Na verdade, seus mortos não foram mortos à espada, nem morreram em combate.

[[v23-22-3]]

^<<v23-22-3,3>>^ Todos os seus líderes fugiram juntos; foram capturados sem resistência. Todos vocês que foram encontrados e presos, ainda que tivessem fugido para bem longe.

[[v23-22-4]]

^<<v23-22-4,4>>^ Por isso eu disse: Afastem-se de mim; deixem-me chorar amargamente. Não tentem consolar-me pela destruição do meu povo.

[[v23-22-5]]

^<<v23-22-5,5>>^ Pois o Soberano, o Senhor dos Exércitos enviou um dia de tumulto, pisoteamento e pavor ao vale da Visão; dia de derrubar muros e de gritar por socorro pelos montes.

[[v23-22-6]]

^<<v23-22-6,6>>^ Elão apanhou a aljava, e avança com seus carros e cavalos; Quir ostenta o escudo.

[[v23-22-7]]

^<<v23-22-7,7>>^ Os vales mais férteis de Judá ficaram cheios de carros, e cavaleiros tomaram posição junto às portas das cidades;

[[v23-22-8]]

^<<v23-22-8,8>>^ Judá ficou sem defesas. Naquele dia vocês olharam para as armas do palácio da Floresta

[[v23-22-9]]

^<<v23-22-9,9>>^ e viram que a cidade de Davi tinha muitas brechas em seus muros. Vocês armazenaram água no açude inferior,

[[v23-22-10]]

^<<v23-22-10,10>>^ contaram as casas de Jerusalém e derrubaram algumas para fortalecer os muros.

[[v23-22-11]]

^<<v23-22-11,11>>^ Vocês construíram um reservatório entre os dois muros para a água do açude velho, mas não olharam para aquele que fez estas coisas, nem deram atenção àquele que há muito as planejou.

[[v23-22-12]]

^<<v23-22-12,12>>^ Naquele dia o Soberano, o Senhor dos Exércitos, os chamou para que chorassem e pranteassem, arrancassem os seus cabelos e usassem vestes de lamento.

[[v23-22-13]]

^<<v23-22-13,13>>^ Mas, ao contrário, houve júbilo e alegria, abate de gado e matança de ovelhas, muita carne e muito vinho! E vocês diziam: "Comamos e bebamos, porque amanhã morreremos".

[[v23-22-14]]

^<<v23-22-14,14>>^ O Senhor dos Exércitos revelou-me isso: "Até o dia de sua morte não haverá propiciação em favor desse pecado", diz o Soberano, o Senhor dos Exércitos.

[[v23-22-15]]

^<<v23-22-15,15>>^ Assim diz o Soberano, o Senhor dos Exércitos: "Vá, dizer a esse administrador do palácio de Sebna:

[[v23-22-16]]

^<<v23-22-16,16>>^ Que faz você aqui, e quem lhe deu permissão para abrir aqui um túmulo, você que o está lavrando no alto do monte e talhando na rocha o seu lugar de descanso?

[[v23-22-17]]

^<<v23-22-17,17>>^ "Veja que o Senhor vai agarrar você e atirá-lo para bem longe, ó homem poderoso!

[[v23-22-18]]

^<<v23-22-18,18>>^ Ele o embrulhará como uma bola e o atirará num vasto campo. Lá você morrerá e lá os seus poderosos carros se tornarão a vergonha da casa do seu senhor!

[[v23-22-19]]

^<<v23-22-19,19>>^ Eu o demitirei das suas funções, e do seu cargo você será deposto.

[[v23-22-20]]

^<<v23-22-20,20>>^ "Naquele dia convocarei o meu servo Eliaquim, filho de Hilquias.

[[v23-22-21]]

^<<v23-22-21,21>>^ Eu o vestirei com o manto que pertencia a você, com o seu cinto o revestirei de força e a ele entregarei a autoridade que você exercia. Ele será um pai para os habitantes de Jerusalém e para os moradores de Judá.

[[v23-22-22]]

^<<v23-22-22,22>>^ Porei sobre os ombros dele a chave do reino de Davi; o que ele abrir ninguém conseguirá fechar, e o que ele fechar ninguém conseguirá abrir.

[[v23-22-23]]

^<<v23-22-23,23>>^ Eu o fincarei como uma estaca em terreno firme; ele será para o reino de seu pai um trono de glória.

[[v23-22-24]]

^<<v23-22-24,24>>^ Toda a glória de sua família dependerá dele: sua prole e seus descendentes — todos os seus utensílios menores, das bacias aos jarros.

[[v23-22-25]]

^<<v23-22-25,25>>^ "Naquele dia", anuncia o Senhor dos Exércitos, "a estaca fincada em terreno firme cederá; será arrebentada e desabará, e o peso sobre ela cairá. " Pois o Senhor o declarou.

'''

xref:023-isaias/023-isaias-021.adoc#v23-21-0[&#60; Capítulo Anterior] | <<v23-22-0,Topo>> | xref:023-isaias/023-isaias-023.adoc#v23-23-0[Próximo Capítulo &#62;]