include::./index.adoc[]

[[v23-38-0]]
=== Isaías, 38
// nvi ?, NVI - Nova Versão Internacional

[[v23-38-1]]

^<<v23-38-1,1>>^ Naqueles dias Ezequias ficou doente, à beira da morte. O profeta Isaías, filho de Amoz, foi visitá-lo e lhe disse: "Assim diz o Senhor: Ponha a casa em ordem, porque você vai morrer; você não se recuperará".

[[v23-38-2]]

^<<v23-38-2,2>>^ Ezequias virou o rosto para a parede e orou ao Senhor:

[[v23-38-3]]

^<<v23-38-3,3>>^ "Lembra-te, Senhor, de como tenho te servido com fidelidade e com devoção sincera, e tenho feito o que tu aprovas". E Ezequias chorou amargamente.

[[v23-38-4]]

^<<v23-38-4,4>>^ Então a palavra do Senhor veio a Isaías:

[[v23-38-5]]

^<<v23-38-5,5>>^ "Vá dizer a Ezequias: ‘Assim diz o Senhor, o Deus de seu antepassado Davi: Ouvi sua oração e vi suas lágrimas; acrescentarei quinze anos à sua vida.

[[v23-38-6]]

^<<v23-38-6,6>>^ E eu livrarei você e esta cidade das mãos do rei da Assíria. Eu defenderei esta cidade.

[[v23-38-7]]

^<<v23-38-7,7>>^ " ‘Este é o sinal de que o Senhor fará o que prometeu:

[[v23-38-8]]

^<<v23-38-8,8>>^ Farei a sombra do sol retroceder os dez degraus que ela já cobriu na escadaria de Acaz’ ". E a luz do sol retrocedeu os dez degraus que tinha avançado.

[[v23-38-9]]

^<<v23-38-9,9>>^ Depois de recuperar-se dessa doença, Ezequias, rei de Judá, escreveu o seguinte:

[[v23-38-10]]

^<<v23-38-10,10>>^ Eu disse: "No vigor da minha vida tenho que passar pelas portas da sepultura e ser roubado do restante dos meus anos? "

[[v23-38-11]]

^<<v23-38-11,11>>^ Eu disse: "Não tornarei a ver o Senhor, o Senhor, na terra dos viventes; não olharei mais para a humanidade nem estarei mais com os que agora habitam neste mundo.

[[v23-38-12]]

^<<v23-38-12,12>>^ A minha casa foi derrubada e tirada de mim, como se fosse uma tenda de pastor. A minha vida foi enovelada, como faz o tecelão, e ele me cortou como um pedaço de tecido; dia e noite foste acabando comigo.

[[v23-38-13]]

^<<v23-38-13,13>>^ Esperei pacientemente até o alvorecer, mas como um leão ele quebrou todos os meus ossos; dia e noite foste acabando comigo.

[[v23-38-14]]

^<<v23-38-14,14>>^ Gritei como um andorinhão, como um tordo; gemi como uma pomba chorosa. Olhando para os céus, enfraqueceram-se os meus olhos. Estou aflito, ó Senhor, vem em meu auxílio! "

[[v23-38-15]]

^<<v23-38-15,15>>^ Mas, que posso dizer? Ele falou comigo, e ele mesmo fez isso. Andarei humildemente toda a minha vida, por causa dessa aflição da minha alma.

[[v23-38-16]]

^<<v23-38-16,16>>^ Senhor, por tais coisas os homens vivem, e por elas também vive o meu espírito. Tu me restauraste a saúde e deixaste-me viver.

[[v23-38-17]]

^<<v23-38-17,17>>^ Foi para o meu benefício que tanto sofri. Em teu amor me guardaste da cova da destruição; lançaste para trás de ti todos os meus pecados,

[[v23-38-18]]

^<<v23-38-18,18>>^ pois a sepultura não pode louvar-te, a morte não pode cantar o teu louvor. Aqueles que descem à cova não podem esperar pela tua fidelidade.

[[v23-38-19]]

^<<v23-38-19,19>>^ Os vivos, somente os vivos, te louvam, como hoje estou fazendo; os pais contam a tua fidelidade a seus filhos.

[[v23-38-20]]

^<<v23-38-20,20>>^ O Senhor me salvou. Cantaremos com instrumentos de corda todos os dias de nossa vida no templo do Senhor.

[[v23-38-21]]

^<<v23-38-21,21>>^ Isaías dissera: "Apliquem um emplastro de figos no furúnculo, e ele se recuperará".

[[v23-38-22]]

^<<v23-38-22,22>>^ Ezequias tinha perguntado: "Qual será o sinal de que subirei ao templo do Senhor? "

'''

xref:023-isaias/023-isaias-037.adoc#v23-37-0[&#60; Capítulo Anterior] | <<v23-38-0,Topo>> | xref:023-isaias/023-isaias-039.adoc#v23-39-0[Próximo Capítulo &#62;]