include::./index.adoc[]

[[v23-51-0]]
=== Isaías, 51
// nvi ?, NVI - Nova Versão Internacional

[[v23-51-1]]

^<<v23-51-1,1>>^ "Escutem-me, vocês que buscam a retidão e procuram pelo Senhor: Olhem para a rocha da qual foram cortados e para a pedreira de onde foram cavados;

[[v23-51-2]]

^<<v23-51-2,2>>^ olhem para Abraão, seu pai, e para Sara, que lhes deu à luz. Quando eu o chamei, ele era apenas um, e eu o abençoei e o tornei muitos.

[[v23-51-3]]

^<<v23-51-3,3>>^ Com certeza o Senhor consolará Sião e olhará com compaixão para todas as ruínas dela; ele tornará seus desertos como o Éden, seus ermos, como o jardim do Senhor. Alegria e contentamento serão achados nela, ações de graças e o som de canções.

[[v23-51-4]]

^<<v23-51-4,4>>^ "Escute-me, meu povo; ouça-me, minha nação: A lei sairá de mim; minha justiça se tornará uma luz para as nações.

[[v23-51-5]]

^<<v23-51-5,5>>^ Minha retidão logo virá, minha salvação está a caminho, e meu braço trará justiça às nações. As ilhas esperarão em mim e aguardarão esperançosamente pelo meu braço.

[[v23-51-6]]

^<<v23-51-6,6>>^ Ergam os olhos para os céus, olhem para baixo, para a terra; os céus desaparecerão como fumaça, a terra se gastará como uma roupa, e seus habitantes morrerão como moscas. Mas a minha salvação durará para sempre, a minha retidão jamais falhará.

[[v23-51-7]]

^<<v23-51-7,7>>^ "Ouçam-me, vocês que sabem o que é direito, vocês, povo que têm a minha lei no coração: Não temam a censura de homens nem fiquem aterrorizados com seus insultos.

[[v23-51-8]]

^<<v23-51-8,8>>^ Pois a traça os comerá como a uma roupa; o verme os devorará como à lã. Mas a minha retidão durará para sempre, a minha salvação de geração a geração. "

[[v23-51-9]]

^<<v23-51-9,9>>^ Desperta! Desperta! Veste-te de força, ó braço do Senhor; acorda, como em dias passados, como em gerações de outrora. Não foste tu que cortaste o Monstro dos Mares em pedaços, que traspassaste aquela serpente aquática?

[[v23-51-10]]

^<<v23-51-10,10>>^ Não foste tu que secaste o mar, as águas do grande abismo, que fizeste uma estrada nas profundezas do mar para que os redimidos pudessem atravessar?

[[v23-51-11]]

^<<v23-51-11,11>>^ Os resgatados do Senhor voltarão. Entrarão em Sião com cântico; alegria eterna coroará suas cabeças. Júbilo e alegria se apossarão deles, tristeza e suspiro deles fugirão.

[[v23-51-12]]

^<<v23-51-12,12>>^ "Eu, eu mesmo, sou quem a consola. Quem é você para que tema homens mortais, os filhos de homens, que não passam de relva,

[[v23-51-13]]

^<<v23-51-13,13>>^ para que você esqueça o Senhor, aquele que fez você, que estendeu os céus e lançou os alicerces da terra, para que viva diariamente, constantemente apavorado por causa da ira do opressor, que está inclinado a destruir? Pois onde está a ira do opressor?

[[v23-51-14]]

^<<v23-51-14,14>>^ Os prisioneiros encolhidos logo serão postos em liberdade; não morrerão em sua masmorra, nem terão falta de pão.

[[v23-51-15]]

^<<v23-51-15,15>>^ Pois eu sou o Senhor, o seu Deus, que agito o mar para que suas ondas rujam, o Senhor dos Exércitos é o seu nome.

[[v23-51-16]]

^<<v23-51-16,16>>^ Pus minhas palavras em sua boca e o cobri com a sombra da minha mão, eu que pus os céus no lugar, que lancei os alicerces da terra, e que digo a Sião: ‘Você é o meu povo’. "

[[v23-51-17]]

^<<v23-51-17,17>>^ Desperte, desperte! Levante-se, ó Jerusalém, você que bebeu da mão do Senhor o cálice da ira dele, você que engoliu até a última gota, a taça que faz os homens cambalearem.

[[v23-51-18]]

^<<v23-51-18,18>>^ De todos os filhos que ela teve não houve nenhum para guiá-la; de todos os filhos que criou não houve nenhum para tomá-la pela mão.

[[v23-51-19]]

^<<v23-51-19,19>>^ Quem poderá consolá-la dessas duas degraças que a atingiram? Ruína e destruição, fome e espada, quem poderá consolá-la?

[[v23-51-20]]

^<<v23-51-20,20>>^ Seus filhos desmaiaram; eles jazem no início de cada rua, como antílope pego numa rede. Estão cheios da ira do Senhor e com a repreensão do seu Deus.

[[v23-51-21]]

^<<v23-51-21,21>>^ Portanto, ouça isto, você, aflita, embriagada, mas não com vinho.

[[v23-51-22]]

^<<v23-51-22,22>>^ Assim diz o seu Soberano Senhor, o seu Deus, que defende o seu povo: "Veja que eu tirei da sua mão o cálice que faz cambalear; dele, do cálice da minha ira, você nunca mais beberá.

[[v23-51-23]]

^<<v23-51-23,23>>^ Eu a porei nas mãos dos seus atormentadores, que lhe disseram: ‘Caia prostrada para que andemos sobre você’. E você fez as suas costas como chão, como uma rua para nela se andar".

'''

xref:023-isaias/023-isaias-050.adoc#v23-50-0[&#60; Capítulo Anterior] | <<v23-51-0,Topo>> | xref:023-isaias/023-isaias-052.adoc#v23-52-0[Próximo Capítulo &#62;]