include::./index.adoc[]

[[v23-5-0]]
=== Isaías, 5
// nvi ?, NVI - Nova Versão Internacional

[[v23-5-1]]

^<<v23-5-1,1>>^ Cantarei para o meu amigo o seu cântico a respeito de sua vinha: Meu amigo tinha uma vinha na encosta de uma fértil colina.

[[v23-5-2]]

^<<v23-5-2,2>>^ Ele cavou a terra, tirou as pedras e plantou as melhores videiras. Construiu uma torre de sentinela e também fez um tanque de prensar uvas. Ele esperava que desse uvas boas, mas só deu uvas azedas.

[[v23-5-3]]

^<<v23-5-3,3>>^ "Agora, habitantes de Jerusalém e homens de Judá, julguem entre mim e a minha vinha.

[[v23-5-4]]

^<<v23-5-4,4>>^ Que mais se poderia fazer por ela que eu não tenha feito? Então, por que só produziu uvas azedas, quando eu esperava uvas boas?

[[v23-5-5]]

^<<v23-5-5,5>>^ Pois, eu lhes digo o que vou fazer com a minha vinha: Derrubarei sua cerca para que ela seja tranformada em pasto; derrubarei o seu muro para que seja pisoteada.

[[v23-5-6]]

^<<v23-5-6,6>>^ Farei dela um terreno baldio; não será podada nem capinada, espinheiros e ervas daninhas crescerão nela. Também ordenarei às nuvens que não derramem chuva sobre ela".

[[v23-5-7]]

^<<v23-5-7,7>>^ Pois bem, a vinha do Senhor dos Exércitos é a nação de Israel, e os homens de Judá são a plantação que ele amava. Ele esperava justiça, mas houve derramamento de sangue; esperava retidão, mas ouviu gritos de aflição.

[[v23-5-8]]

^<<v23-5-8,8>>^ Ai de vocês que adquirem casas e mais casas, propriedades e mais propriedades até não haver mais lugar para ninguém e vocês se tornarem os senhores absolutos da terra.

[[v23-5-9]]

^<<v23-5-9,9>>^ O Senhor dos Exércitos me disse: "Sem dúvida muitas casas ficarão abandonadas, as casas belas e grandes ficarão sem moradores.

[[v23-5-10]]

^<<v23-5-10,10>>^ Uma vinha de dez alqueires só produzirá um pote de vinho, um barril de semente só dará uma arroba de trigo".

[[v23-5-11]]

^<<v23-5-11,11>>^ Ai dos que se levantam cedo para embebedar-se, e se esquentam com o vinho até à noite.

[[v23-5-12]]

^<<v23-5-12,12>>^ Harpas e liras, tamborins, flautas e vinho há em suas festas, mas não se importam com os atos do Senhor, nem atentam para obra que as suas mãos realizam.

[[v23-5-13]]

^<<v23-5-13,13>>^ Portanto, o meu povo vai para o exílio, por falta de conhecimento; a elite morrerá de fome, e as multidões, de sede.

[[v23-5-14]]

^<<v23-5-14,14>>^ Por isso o Sheol aumenta o seu apetite e escancara a sua boca. Para dentro dele descerão o esplendor da cidade e a sua riqueza, o seu barulho e os que se divertem.

[[v23-5-15]]

^<<v23-5-15,15>>^ Por isso o homem será abatido, a humanidade se curvará, e os arrogantes terão que baixar os olhos.

[[v23-5-16]]

^<<v23-5-16,16>>^ Mas o Senhor dos Exércitos será exaltado em sua justiça; o Deus santo se mostrará santo em sua retidão.

[[v23-5-17]]

^<<v23-5-17,17>>^ Então ovelhas pastarão ali como em sua própria pastagem; cordeiros comerão nas ruínas dos ricos.

[[v23-5-18]]

^<<v23-5-18,18>>^ Ai dos que se prendem à iniqüidade com cordas de engano, e ao pecado com cordas de carroça,

[[v23-5-19]]

^<<v23-5-19,19>>^ e dizem: "Que Deus apresse a realização da sua obra para que a vejamos; que se cumpra o plano do Santo de Israel, para que o conheçamos".

[[v23-5-20]]

^<<v23-5-20,20>>^ Ai dos que chamam ao mal bem e ao bem, mal, que fazem das trevas luz e da luz, trevas, do amargo, doce e do doce, amargo.

[[v23-5-21]]

^<<v23-5-21,21>>^ Ai dos que são sábios aos seus próprios olhos e inteligentes em sua própria opinião.

[[v23-5-22]]

^<<v23-5-22,22>>^ Ai dos que são campeões em beber vinho e mestres em misturar bebidas,

[[v23-5-23]]

^<<v23-5-23,23>>^ dos que por suborno absolvem o culpado, mas negam justiça ao inocente.

[[v23-5-24]]

^<<v23-5-24,24>>^ Por isso, assim como a palha é consumida pelo fogo e o restolho é devorado pelas chamas, assim também as suas raízes apodrecerão e as suas flores, como pó, serão levadas pelo vento; pois rejeitaram a lei do Senhor dos Exércitos, desprezaram a palavra do Santo de Israel.

[[v23-5-25]]

^<<v23-5-25,25>>^ Por tudo isso a ira do Senhor acendeu-se contra o seu povo, e ele levantou sua mão para os ferir. Os montes tremeram, e os seus cadáveres estão como o lixo nas ruas. Apesar disso tudo, a ira dele não se desviou; sua mão continua erguida.

[[v23-5-26]]

^<<v23-5-26,26>>^ Ele levanta uma bandeira convocando uma nação distante e assobia para um povo dos confins da terra. Aí vêm eles rapidamente!

[[v23-5-27]]

^<<v23-5-27,27>>^ Nenhum dos seus soldados se cansa nem tropeça, nenhum deles cochila nem dorme, nenhum afrouxa o cinto, nenhum desamarra a correia das sandálias.

[[v23-5-28]]

^<<v23-5-28,28>>^ As flechas deles estão afiadas, preparados estão todos os seus arcos; os cascos dos seus cavalos são duros como pedra, as rodas de seus carros são como um furacão.

[[v23-5-29]]

^<<v23-5-29,29>>^ O rugido deles é como o do leão; rugem como leões ferozes; rosnam enquanto se apoderam da presa e a arrastam, sem que ninguém possa livrá-la.

[[v23-5-30]]

^<<v23-5-30,30>>^ Naquele dia rugirão sobre Judá como o rugir do mar. E, se alguém olhar para a terra de Israel, verá trevas e aflição; até a luz do dia será obscurecida pelas nuvens.

'''

xref:023-isaias/023-isaias-004.adoc#v23-4-0[&#60; Capítulo Anterior] | <<v23-5-0,Topo>> | xref:023-isaias/023-isaias-006.adoc#v23-6-0[Próximo Capítulo &#62;]