include::./index.adoc[]

[[v23-57-0]]
=== Isaías, 57
// nvi ?, NVI - Nova Versão Internacional

[[v23-57-1]]

^<<v23-57-1,1>>^ O justo perece, e ninguém pondera sobre isso em seu coração; homens piedosos são tirados, e ninguém entende que os justos são tirados para serem poupados do mal.

[[v23-57-2]]

^<<v23-57-2,2>>^ Aqueles que andam retamente entrarão na paz; acharão descanso na morte.

[[v23-57-3]]

^<<v23-57-3,3>>^ "Mas vocês, aproximem-se, vocês, filhos de adivinhas, vocês, prole de adúlteros e prostitutas!

[[v23-57-4]]

^<<v23-57-4,4>>^ De quem vocês estão zombando? De quem fazem pouco caso? E para quem mostram a língua? Não são vocês uma ninhada de rebeldes, uma prole de mentirosos?

[[v23-57-5]]

^<<v23-57-5,5>>^ Vocês ardem de desejo entre os carvalhos e debaixo de toda árvore frondosa; vocês sacrificam seus filhos nos vales e debaixo de penhascos salientes.

[[v23-57-6]]

^<<v23-57-6,6>>^ Os ídolos entre as pedras lisas dos vales são a sua porção; são a sua parte. Isso mesmo! Para eles você derramou ofertas de bebidas e apresentou ofertas de cereal. Poderei eu contentar-me com isso?

[[v23-57-7]]

^<<v23-57-7,7>>^ Você fez o leito numa colina alta e soberba; ali você subiu para oferecer sacrifícios.

[[v23-57-8]]

^<<v23-57-8,8>>^ Atrás de suas portas e dos seus batentes você pôs os seus símbolos pagãos. Ao me abandonar, você descobriu seu leito, subiu nele e o deixou escancarado; fez acordo com aqueles cujas camas você ama, e dos quais contemplou a nudez.

[[v23-57-9]]

^<<v23-57-9,9>>^ Você foi até Moloque com azeite de oliva e multiplicou os seus perfumes. Você enviou seus embaixadores a lugares distantes; você desceu ao fundo do poço!

[[v23-57-10]]

^<<v23-57-10,10>>^ Você ficou exausta com todos os seus caminhos, mas não quis dizer: "Não há esperança! " Você recuperou as forças, e por isso não esmoreceu.

[[v23-57-11]]

^<<v23-57-11,11>>^ "De quem você teve tanto medo e tremor, a ponto de ser falsa comigo, não se lembrar de mim e não ponderar isso em seu coração? Não será por que há muito estou calado que você não me teme?

[[v23-57-12]]

^<<v23-57-12,12>>^ Sua retidão e sua justiça exporei, e elas não a beneficiarão.

[[v23-57-13]]

^<<v23-57-13,13>>^ Quando você clamar por ajuda, que a sua coleção de ídolos a salve! O vento levará todos eles, um simples sopro os arrebatará. Mas o homem que faz de mim o seu refúgio receberá a terra por herança e possuirá o meu santo monte. "

[[v23-57-14]]

^<<v23-57-14,14>>^ E se dirá: "Aterrem, aterrem, preparem o caminho! Tirem os obstáculos do caminho do meu povo".

[[v23-57-15]]

^<<v23-57-15,15>>^ Pois assim diz o Alto e Sublime, que vive para sempre, e cujo nome é santo: "Habito num lugar alto e santo, mas habito também com o contrito e humilde de espírito, para dar novo ânimo ao espírito do humilde e novo alento ao coração do contrito.

[[v23-57-16]]

^<<v23-57-16,16>>^ Não farei litígio para sempre, nem permanecerei irado, porque, se não, o espírito do homem esmoreceria diante de mim, bem como o sopro do homem que eu criei!

[[v23-57-17]]

^<<v23-57-17,17>>^ Por causa da sua cobiça pervesa fiquei indignado e o feri; fiquei irado e escondi o meu rosto. Mas ele continuou extraviado, seguindo os caminhos que escolheu.

[[v23-57-18]]

^<<v23-57-18,18>>^ Eu vi os seus caminhos, mas vou curá-lo; eu o guiarei e tornarei a dar-lhe consolo,

[[v23-57-19]]

^<<v23-57-19,19>>^ criando louvor nos lábios dos pranteadores de Israel. Paz, paz, aos de longe e aos de perto", diz o Senhor. "Quanto a ele, eu o curarei. "

[[v23-57-20]]

^<<v23-57-20,20>>^ Mas os ímpios são como o mar agitado, incapaz de sossegar e cujas águas expelem lama e lodo.

[[v23-57-21]]

^<<v23-57-21,21>>^ "Para os ímpios não há paz", diz o meu Deus.

'''

xref:023-isaias/023-isaias-056.adoc#v23-56-0[&#60; Capítulo Anterior] | <<v23-57-0,Topo>> | xref:023-isaias/023-isaias-058.adoc#v23-58-0[Próximo Capítulo &#62;]