include::./index.adoc[]

[[v23-31-0]]
=== Isaías, 31
// nvi ?, NVI - Nova Versão Internacional

[[v23-31-1]]

^<<v23-31-1,1>>^ Ai dos que descem ao Egito em busca de ajuda, que contam com cavalos. Eles confiam na multidão dos seus carros e na grande força dos seus cavaleiros, mas não olham para o Santo de Israel, nem buscam a ajuda que vem do Senhor!

[[v23-31-2]]

^<<v23-31-2,2>>^ Contudo, ele também é sábio e pode trazer a desgraça; ele não volta atrás em suas palavras. Ele se levantará contra a casa dos perversos, contra quem ajuda os maus.

[[v23-31-3]]

^<<v23-31-3,3>>^ Mas os egípcios são homens, e não Deus; seus cavalos são carne, e não espírito. Quando o Senhor estender a mão, aquele que ajuda tropeçará, aquele que é ajudado cairá; ambos perecerão juntos.

[[v23-31-4]]

^<<v23-31-4,4>>^ Assim me diz o Senhor: "Assim como quando o leão, o leão grande, ruge ao lado da presa, e contra ele se junta um bando de pastores, e ele não se intimida com os gritos deles nem se perturba com o seu clamor, assim o Senhor dos Exércitos descerá para combater nas alturas do monte Sião.

[[v23-31-5]]

^<<v23-31-5,5>>^ Como as aves dão proteção aos filhotes com suas asas, o Senhor dos Exércitos protegerá Jerusalém; ele a protegerá e a livrará; ele a poupará e a salvará".

[[v23-31-6]]

^<<v23-31-6,6>>^ Voltem para aquele contra quem vocês se revoltaram tão tremendamente, ó israelitas!

[[v23-31-7]]

^<<v23-31-7,7>>^ Pois naquele dia cada um de vocês rejeitará os ídolos de prata e de ouro que as mãos pecaminosas de vocês fizeram.

[[v23-31-8]]

^<<v23-31-8,8>>^ "A Assíria cairá por uma espada que não é de homem; uma espada, não de mortais, a devorará. Todos fugirão da espada e os seus jovens serão sujeitos a trabalhos forçados.

[[v23-31-9]]

^<<v23-31-9,9>>^ Sua fortaleza cairá por causa do pavor; ao verem a bandeira da batalha, seus líderes entrarão em pânico", anuncia o Senhor, cujo fogo está em Sião, cuja fornalha está em Jerusalém.

'''

xref:023-isaias/023-isaias-030.adoc#v23-30-0[&#60; Capítulo Anterior] | <<v23-31-0,Topo>> | xref:023-isaias/023-isaias-032.adoc#v23-32-0[Próximo Capítulo &#62;]