include::./index.adoc[]

[[v23-52-0]]
=== Isaías, 52
// nvi ?, NVI - Nova Versão Internacional

[[v23-52-1]]

^<<v23-52-1,1>>^ Desperte! Desperte!, ó Sião, vista-se de força. Vista suas roupas de esplendor, ó Jerusalém, cidade santa. Os incircuncisos e os impuros não tornarão a entrar em você.

[[v23-52-2]]

^<<v23-52-2,2>>^ Sacuda para longe a sua poeira; levante-se, sente-se entronizada, ó Jerusalém. Livre-se das correntes em seu pescoço, ó cidade cativa de Sião.

[[v23-52-3]]

^<<v23-52-3,3>>^ Pois assim diz o Senhor: "Vocês foram vendidos por nada, e sem dinheiro vocês serão resgatados".

[[v23-52-4]]

^<<v23-52-4,4>>^ Pois assim diz o Soberano Senhor: "No início o meu povo desceu para morar no Egito; ultimamente a Assíria os tem oprimido.

[[v23-52-5]]

^<<v23-52-5,5>>^ "E agora o que tenho aqui? ", pergunta o Senhor. "Pois o meu povo foi levado por nada, e aqueles que os dominam zombam", diz o Senhor. "E o dia inteiro o meu nome é constantemente blasfemado.

[[v23-52-6]]

^<<v23-52-6,6>>^ Por isso o meu povo conhecerá o meu nome; naquele dia eles saberão que sou eu que o previ. Sim, sou eu. "

[[v23-52-7]]

^<<v23-52-7,7>>^ Como são belos nos montes os pés daqueles que anunciam boas novas, que proclamam a paz, que trazem boas notícias, que proclamam salvação, que dizem a Sião: "O seu Deus reina! "

[[v23-52-8]]

^<<v23-52-8,8>>^ Escutem! Suas sentinelas erguem a voz; juntas gritam de alegria. Quando o Senhor voltar a Sião, elas o verão com os próprios olhos.

[[v23-52-9]]

^<<v23-52-9,9>>^ Cantem juntamente de alegria, vocês, ruínas de Jerusalém, pois o Senhor consolou o seu povo, ele resgatou Jerusalém.

[[v23-52-10]]

^<<v23-52-10,10>>^ O Senhor desnudará seu santo braço à vista de todas as nações, e todos os confins da terra verão a salvação de nosso Deus.

[[v23-52-11]]

^<<v23-52-11,11>>^ Afastem-se, afastem-se, saiam daqui! Não toquem em coisas impuras! Saiam dela e sejam puros, vocês, que transportam os utensílios do Senhor.

[[v23-52-12]]

^<<v23-52-12,12>>^ Mas vocês não partirão apressadamente, nem sairão em fuga; pois o Senhor irá à frente de vocês, o Deus de Israel será a sua retaguarda.

[[v23-52-13]]

^<<v23-52-13,13>>^ Vejam, o meu servo agirá com sabedoria; será levantado e erguido e muitíssimo exaltado.

[[v23-52-14]]

^<<v23-52-14,14>>^ Assim como houve muitos que ficaram pasmados diante dele; sua aparência estava tão desfigurada, que ele se tornou irreconhecível como homem; não parecia um ser humano;

[[v23-52-15]]

^<<v23-52-15,15>>^ de igual modo ele aspergirá muitas nações, e reis calarão a boca por causa dele. Pois aquilo que não lhes foi dito verão, e o que não ouviram compreenderão.

'''

xref:023-isaias/023-isaias-051.adoc#v23-51-0[&#60; Capítulo Anterior] | <<v23-52-0,Topo>> | xref:023-isaias/023-isaias-053.adoc#v23-53-0[Próximo Capítulo &#62;]