include::./index.adoc[]

[[v23-34-0]]
=== Isaías, 34
// nvi ?, NVI - Nova Versão Internacional

[[v23-34-1]]

^<<v23-34-1,1>>^ Aproximem-se, nações, e escutem: prestem atenção, ó povos! Que o ouçam a terra e tudo o que nela há, o mundo e tudo o que dele procede!

[[v23-34-2]]

^<<v23-34-2,2>>^ O Senhor está indignado contra todas as nações; sua ira está contra todos os seus exércitos. Ele os destruirá totalmente, ele os entregará à matança.

[[v23-34-3]]

^<<v23-34-3,3>>^ Seus mortos serão lançados fora e os seus cadáveres exalarão mau cheiro; os montes se encharcarão do sangue deles.

[[v23-34-4]]

^<<v23-34-4,4>>^ As estrelas dos céus serão todas dissolvidas, e os ceús se enrolarão como um pergaminho; todo o exército celeste cairá como folhas secas da videira e da figueira.

[[v23-34-5]]

^<<v23-34-5,5>>^ Quando minha espada embriagar-se nos céus, saibam que ela descerá para julgar Edom, povo que condenei à destruição.

[[v23-34-6]]

^<<v23-34-6,6>>^ A espada do Senhor está banhada em sangue, está coberta de gordura, sangue de cordeiros e de bodes, gordura dos rins de carneiros. Pois o Senhor exige sacrifício em Bozra e grande matança em Edom.

[[v23-34-7]]

^<<v23-34-7,7>>^ E os bois selvagens cairão com eles, e os novilhos com os touros. A terra deles ficará ensopada de sangue, e o pó se encharcará de gordura.

[[v23-34-8]]

^<<v23-34-8,8>>^ Pois o Senhor terá seu dia de vingança, um ano de retribuição, para defender a causa de Sião.

[[v23-34-9]]

^<<v23-34-9,9>>^ Os riachos de Edom se transformarão em piche, em enxofre, o seu pó; sua terra se tornará betume ardente!

[[v23-34-10]]

^<<v23-34-10,10>>^ Não se apagará de dia nem de noite; sua fumaça subirá para sempre. De geração em geração ficará abandonada; ninguém voltará a passar por ela.

[[v23-34-11]]

^<<v23-34-11,11>>^ A coruja-do-deserto e a coruja estridente a possuirão; o corujão e o corvo farão nela os seus ninhos. Deus estenderá sobre Edom o caos como linha de medir, e a desolação como fio de prumo.

[[v23-34-12]]

^<<v23-34-12,12>>^ Seus nobres nada terão ali que possa chamar-se reino, e todos os seus líderes desaparecerão.

[[v23-34-13]]

^<<v23-34-13,13>>^ Espinhos tomarão de assalto as suas cidadelas; urtigas e sarças cobrirão as suas fortalezas. Será um antro de chacais e moradia de corujas.

[[v23-34-14]]

^<<v23-34-14,14>>^ Criaturas do deserto se encontrarão com hienas, e bodes selvagens balirão uns para os outros; ali também descansarão as criaturas noturnas e acharão para si locais de descanso.

[[v23-34-15]]

^<<v23-34-15,15>>^ Nela a coruja fará ninho, chocará seus ovos e cuidará dos seus filhotes à sombra de suas asas; os falcões também se ajuntarão ali, cada um com o seu par.

[[v23-34-16]]

^<<v23-34-16,16>>^ Procurem no livro do Senhor e leiam: Nenhum deles estará faltando; nenhum estará sem o seu par. Pois foi a sua boca que deu a ordem, e o seu Espírito os ajuntará.

[[v23-34-17]]

^<<v23-34-17,17>>^ Ele designa as porções de cada um; sua mão os distribui por medida. Eles se apossarão dela para sempre, e ali habitarão de geração em geração.

'''

xref:023-isaias/023-isaias-033.adoc#v23-33-0[&#60; Capítulo Anterior] | <<v23-34-0,Topo>> | xref:023-isaias/023-isaias-035.adoc#v23-35-0[Próximo Capítulo &#62;]