include::./index.adoc[]

[[v23-18-0]]
=== Isaías, 18
// nvi ?, NVI - Nova Versão Internacional

[[v23-18-1]]

^<<v23-18-1,1>>^ Ai da terra do zumbido de insetos ao longo dos rios da Etiópia,

[[v23-18-2]]

^<<v23-18-2,2>>^ que manda emissários pelo mar em barcos de papiro sobre as águas. Vão, ágeis mensageiros, a um povo alto e de pele macia, a um povo temido pelos que estão perto e pelos que estão longe, nação agressiva e de fala estranha, cuja terra é dividida por rios.

[[v23-18-3]]

^<<v23-18-3,3>>^ Todos vocês, habitantes do mundo, vocês que vivem na terra, quando a bandeira for erguida sobre os montes, vocês a verão, e, quando soar a trombeta, vocês a ouvirão.

[[v23-18-4]]

^<<v23-18-4,4>>^ Assim diz o Senhor: "Do lugar onde moro ficarei olhando, quieto como o ardor do sol reluzente, como a nuvem de orvalho no calor do tempo da colheita".

[[v23-18-5]]

^<<v23-18-5,5>>^ Pois, antes da colheita, quando a floração der lugar ao fruto e as uvas amadurecerem, ele cortará os brotos com a podadeira e tirará os ramos longos.

[[v23-18-6]]

^<<v23-18-6,6>>^ Serão todos entregues aos abutres das montanhas e aos animais selvagens; as aves se alimentarão delas todo o verão, e os animais selvagens, todo o inverno.

[[v23-18-7]]

^<<v23-18-7,7>>^ Naquela ocasião dádivas serão trazidas ao Senhor dos Exércitos da parte de um povo alto e de pele macia, da parte de um povo temido pelos que estão perto e pelos que estão longe, nação agressiva e de fala estranha, cuja terra é dividida por rios. As dádivas serão trazidas ao monte Sião, ao local do nome do Senhor dos Exércitos.

'''

xref:023-isaias/023-isaias-017.adoc#v23-17-0[&#60; Capítulo Anterior] | <<v23-18-0,Topo>> | xref:023-isaias/023-isaias-019.adoc#v23-19-0[Próximo Capítulo &#62;]