include::./index.adoc[]

[[v23-33-0]]
=== Isaías, 33
// nvi ?, NVI - Nova Versão Internacional

[[v23-33-1]]

^<<v23-33-1,1>>^ Ai de você, destruidor, que ainda não foi destruído! Ai de você, traidor, que não foi traído! Quando você parar de destruir, será destruído; quando parar de trair, será traído.

[[v23-33-2]]

^<<v23-33-2,2>>^ Senhor, tem misericórdia de nós; pois por ti esperamos! Sê tu a nossa força cada manhã, nossa salvação na hora do perigo.

[[v23-33-3]]

^<<v23-33-3,3>>^ Diante do trovão da tua voz, os povos fogem; quando te levantas, dispersam-se as nações.

[[v23-33-4]]

^<<v23-33-4,4>>^ O seu despojo, ó nações, será reunido como fazem os gafanhotos novos; como gafanhotos em nuvem, dele se apoderam os homens.

[[v23-33-5]]

^<<v23-33-5,5>>^ O Senhor é exaltado, pois habita no alto; ele encherá Sião de retidão e justiça.

[[v23-33-6]]

^<<v23-33-6,6>>^ Ele será o firme fundamento nos tempos a que você pertence, uma grande riqueza de salvação, sabedoria e conhecimento; o temor do Senhor é a chave desse tesouro.

[[v23-33-7]]

^<<v23-33-7,7>>^ Vejam! Os seus heróis gritam nas ruas; os embaixadores da paz choram amargamente.

[[v23-33-8]]

^<<v23-33-8,8>>^ As estradas estão abandonadas, ninguém viaja por elas. Rompeu-se o acordo, suas testemunhas são desprezadas, não se respeita ninguém.

[[v23-33-9]]

^<<v23-33-9,9>>^ A terra pranteia e fraqueja, o Líbano murcha, envergonhado; Sarom é como a Arabá, e Basã e o Carmelo perdem sua folhagem.

[[v23-33-10]]

^<<v23-33-10,10>>^ "Agora me levantarei", diz o Senhor. "Agora eu me erguerei; agora serei exaltado.

[[v23-33-11]]

^<<v23-33-11,11>>^ Vocês concebem palha, e dão à luz restolho; seu sopro é um fogo que o consome.

[[v23-33-12]]

^<<v23-33-12,12>>^ Os povos serão queimados como se faz com a cal; como espinheiros cortados, serão postos no fogo. "

[[v23-33-13]]

^<<v23-33-13,13>>^ Vocês que estão longe, atentem para o que eu fiz! Vocês, que estão perto, reconheçam o meu poder!

[[v23-33-14]]

^<<v23-33-14,14>>^ Em Sião os pecadores estão aterrorizados; o tremor se apodera dos ímpios: "Quem de nós pode conviver com o fogo consumidor? Quem de nós pode conviver com a chama eterna? "

[[v23-33-15]]

^<<v23-33-15,15>>^ Aquele que anda corretamente e fala o que é reto, que recusa o lucro injusto, cuja mão não aceita suborno, que tapa os ouvidos para as tramas de assassinatos e fecha os olhos para não contemplar o mal,

[[v23-33-16]]

^<<v23-33-16,16>>^ é esse o homem que habitará nas alturas; seu refúgio será a fortaleza das rochas; terá suprimento de pão, e água não lhe faltará.

[[v23-33-17]]

^<<v23-33-17,17>>^ Seus olhos verão o rei em seu esplendor e vislumbrarão o território em toda a sua extensão.

[[v23-33-18]]

^<<v23-33-18,18>>^ Em seus pensamentos você lembrará terrores passados: "Onde está o oficial maior? Onde está o que recebia tributos? Onde o encarregado das torres? "

[[v23-33-19]]

^<<v23-33-19,19>>^ Você não tornará a ver aquele povo arrogante, aquele povo de fala obscura, com sua língua estranha, incompreensível.

[[v23-33-20]]

^<<v23-33-20,20>>^ Olhe para Sião, a cidade das nossas festas; seus olhos verão Jerusalém, morada pacífica, tenda que não será removida; suas estacas jamais serão arrancadas, nem se romperá nenhuma de suas cordas.

[[v23-33-21]]

^<<v23-33-21,21>>^ Ali o Senhor será o Poderoso para nós. Será como uma região de rios e canais largos, mas nenhum navio a remo os percorrerá, e nenhuma nau poderosa velejará neles.

[[v23-33-22]]

^<<v23-33-22,22>>^ Pois o Senhor é o nosso juiz, o Senhor é o nosso legislador, o Senhor é o nosso rei; é ele que nos salvará.

[[v23-33-23]]

^<<v23-33-23,23>>^ Suas cordas se afrouxam: O mastro não está firme, as velas não estão estendidas. Então será dividida grande quantidade de despojos, e até o aleijado levará sua presa.

[[v23-33-24]]

^<<v23-33-24,24>>^ Nenhum morador de Sião dirá: "Estou doente! " E os pecados dos que ali habitam serão perdoados.

'''

xref:023-isaias/023-isaias-032.adoc#v23-32-0[&#60; Capítulo Anterior] | <<v23-33-0,Topo>> | xref:023-isaias/023-isaias-034.adoc#v23-34-0[Próximo Capítulo &#62;]