include::./index.adoc[]

[[v23-17-0]]
=== Isaías, 17
// nvi ?, NVI - Nova Versão Internacional

[[v23-17-1]]

^<<v23-17-1,1>>^ Advertência contra Damasco: "Damasco deixará de ser cidade; e se tornará um monte de ruínas.

[[v23-17-2]]

^<<v23-17-2,2>>^ Suas cidades serão abandonadas; serão entregues aos rebanhos que ali se deitarão, e ninguém os espantará.

[[v23-17-3]]

^<<v23-17-3,3>>^ Efraim deixará de ser uma fortaleza, e Damasco uma realeza; o remanescente de Arã será como a glória dos israelitas", anuncia o Senhor dos Exércitos.

[[v23-17-4]]

^<<v23-17-4,4>>^ "Naquele dia a glória de Jacó se definhará, e a gordura do seu corpo se consumirá.

[[v23-17-5]]

^<<v23-17-5,5>>^ Será como quando um ceifeiro junta o trigo e colhe as espigas com o braço, como quando se apanham os feixes de trigo no vale de Refaim.

[[v23-17-6]]

^<<v23-17-6,6>>^ Contudo, restarão algumas espigas, como quando se sacode uma oliveira, ficam duas ou três azeitonas nos galhos mais altos e umas quatro ou cinco nos ramos mais produtivos", anuncia o Senhor, o Deus de Israel.

[[v23-17-7]]

^<<v23-17-7,7>>^ Naquele dia os homens olharão para aquele que os fez e voltarão os olhos para o Santo de Israel.

[[v23-17-8]]

^<<v23-17-8,8>>^ Não olharão para os altares, obra de suas mãos, e não darão a mínima atenção aos postes sagrados e aos altares de incenso que os seus dedos fizeram.

[[v23-17-9]]

^<<v23-17-9,9>>^ Naquele dia as suas cidades fortes, que tinham sido abandonadas por causa dos israelitas, serão como lugares entregues aos bosques e ao mato. E tudo será desolação.

[[v23-17-10]]

^<<v23-17-10,10>>^ Porque vocês se esqueceram de Deus, do seu Salvador e não se lembraram da Rocha, da fortaleza de vocês; então vocês cultivarão as melhores plantas, videiras importadas.

[[v23-17-11]]

^<<v23-17-11,11>>^ No dia em que as semearem as farão crescer, e de manhã florescerão. Contudo, não haverá colheita no dia da tristeza e do mal irremediável.

[[v23-17-12]]

^<<v23-17-12,12>>^ Ah! O bramido das numerosas nações; bramam como o mar! Ah, o rugido dos povos; rugem como águas impetuosas!

[[v23-17-13]]

^<<v23-17-13,13>>^ Embora os povos rujam como ondas encapeladas, quando ele os repreender, fugirão para longe, carregados pelo vento como palha nas colinas, como galhos arrancados pela ventania.

[[v23-17-14]]

^<<v23-17-14,14>>^ Ao cair da tarde, pavor repentino! Antes do amanhecer, já se foram! Esse é o destino dos que nos saqueiam, essa é a parte que caberá aos que roubam.

'''

xref:023-isaias/023-isaias-016.adoc#v23-16-0[&#60; Capítulo Anterior] | <<v23-17-0,Topo>> | xref:023-isaias/023-isaias-018.adoc#v23-18-0[Próximo Capítulo &#62;]