include::./index.adoc[]

[[v23-45-0]]
=== Isaías, 45
// nvi ?, NVI - Nova Versão Internacional

[[v23-45-1]]

^<<v23-45-1,1>>^ "Assim diz o Senhor ao seu ungido: a Ciro, cuja mão direita seguro com firmeza para subjugar as nações diante dele e arrancar a armadura de seus reis, para abrir portas diante dele, de modo que as portas não estejam trancadas:

[[v23-45-2]]

^<<v23-45-2,2>>^ Eu irei adiante de você e aplainarei montes; derrubarei portas de bronze e romperei trancas de ferro.

[[v23-45-3]]

^<<v23-45-3,3>>^ Darei a você os tesouros das trevas, riquezas armazenadas em locais secretos, para que você saiba que eu sou o Senhor, o Deus de Israel, que o convoca pelo nome.

[[v23-45-4]]

^<<v23-45-4,4>>^ Por amor de meu servo Jacó, de meu escolhido Israel, eu o convoco pelo nome e concedo-lhe um título de honra, embora você não me reconheça.

[[v23-45-5]]

^<<v23-45-5,5>>^ Eu sou o Senhor, e não há nenhum outro; além de mim não há Deus. Eu o fortalecerei, ainda que você não tenha me admitido,

[[v23-45-6]]

^<<v23-45-6,6>>^ de forma que do nascente ao poente saibam todos que não há ninguém além de mim. Eu sou o Senhor, e não há nenhum outro.

[[v23-45-7]]

^<<v23-45-7,7>>^ Eu formo a luz e crio as trevas, promovo a paz e causo a desgraça; eu, o Senhor, faço todas essas coisas. "

[[v23-45-8]]

^<<v23-45-8,8>>^ "Vocês, céus elevados, façam chover justiça; derramem-na as nuvens. Abra-se a terra, brote a salvação, cresça a retidão com ela; eu, o Senhor, a criei. "

[[v23-45-9]]

^<<v23-45-9,9>>^ "Ai daquele que contende com seu Criador, daquele que não passa de um caco entre os cacos no chão. Acaso o barro pode dizer ao oleiro: ‘O que você está fazendo? ’ Será que a obra que você faz pode dizer: ‘Ele não tem mãos? ’

[[v23-45-10]]

^<<v23-45-10,10>>^ Ai daquele que diz a seu pai: ‘O que você gerou? ’, ou à sua mãe: ‘O que você deu à luz? ’ "

[[v23-45-11]]

^<<v23-45-11,11>>^ "Assim diz o Senhor, o Santo de Israel, o seu Criador: A respeito de coisas vindouras, você me pergunta sobre meus filhos, ou me dá ordens sobre o trabalho de minhas mãos?

[[v23-45-12]]

^<<v23-45-12,12>>^ Fui eu que fiz a terra e nela criei a humanidade. Minhas próprias mãos estenderam os céus; eu dispus o seu exército de estrelas.

[[v23-45-13]]

^<<v23-45-13,13>>^ Eu levantarei esse homem em minha retidão: Farei direitos todos os seus caminhos. Ele reconstruirá minha cidade e libertará os exilados, sem exigir pagamento nem qualquer recompensa, diz o Senhor dos Exércitos. "

[[v23-45-14]]

^<<v23-45-14,14>>^ Assim diz o Senhor: "Os produtos do Egito e as mercadorias da Etiópia, e aqueles altos sabeus, passarão para o seu lado e lhe pertencerão, ó Jerusalém; eles a seguirão, acorrentados, passarão para o seu lado. Eles se inclinarão diante de vocês e implorarão a você, dizendo: ‘Certamente Deus está com você, e não há outro; não há nenhum outro Deus’ ".

[[v23-45-15]]

^<<v23-45-15,15>>^ Verdadeiramente tu és um Deus que se esconde, ó Deus e Salvador de Israel.

[[v23-45-16]]

^<<v23-45-16,16>>^ Todos os que fazem ídolos serão envergonhados e constrangidos; juntos cairão em constrangimento.

[[v23-45-17]]

^<<v23-45-17,17>>^ Mas Israel será salvo pelo Senhor com uma salvação eterna; vocês jamais serão envergonhados ou constrangidos, por toda a eternidade.

[[v23-45-18]]

^<<v23-45-18,18>>^ Pois assim diz o Senhor, que criou os céus, ele é Deus; que moldou a terra e a fez, ele a fundou; ele não a criou para estar vazia, mas a formou para ser habitada; ele diz: "Eu sou o Senhor, e não há nenhum outro.

[[v23-45-19]]

^<<v23-45-19,19>>^ Não falei secretamente, de algum lugar numa terra de trevas; eu não disse aos descendentes de Jacó: ‘Procurem-me à toa’. Eu, o SENHOR, falo a verdade; eu anuncio o que é certo".

[[v23-45-20]]

^<<v23-45-20,20>>^ "Ajuntem-se e venham; reúnam-se, vocês, fugitivos das nações. Ignorantes são aqueles que levam de um lado para outro imagens de madeira, que oram a deuses que não podem salvar.

[[v23-45-21]]

^<<v23-45-21,21>>^ Declarem o que deve ser, apresentem provas. Que eles juntamente se aconselhem. Quem há muito predisse isto, quem o declarou desde o passado distante? Não fui eu, o Senhor? E não há outro Deus além de mim, um Deus justo e salvador; não há outro além de mim.

[[v23-45-22]]

^<<v23-45-22,22>>^ "Voltem-se para mim e sejam salvos, todos vocês, confins da terra; pois eu sou Deus, e não há nenhum outro.

[[v23-45-23]]

^<<v23-45-23,23>>^ Por mim mesmo eu jurei, a minha boca pronunciou com toda integridade uma palavra que não será revogada: Diante de mim todo joelho se dobrará; junto a mim toda língua jurará.

[[v23-45-24]]

^<<v23-45-24,24>>^ Dirão a meu respeito: ‘Somente no Senhor estão a justiça e a força’. " Todos os que o odeiam virão a ele e serão envergonhados.

[[v23-45-25]]

^<<v23-45-25,25>>^ Mas no Senhor todos os descendentes de Israel serão considerados justos e exultarão.

'''

xref:023-isaias/023-isaias-044.adoc#v23-44-0[&#60; Capítulo Anterior] | <<v23-45-0,Topo>> | xref:023-isaias/023-isaias-046.adoc#v23-46-0[Próximo Capítulo &#62;]