include::./index.adoc[]

[[v23-29-0]]
=== Isaías, 29
// nvi ?, NVI - Nova Versão Internacional

[[v23-29-1]]

^<<v23-29-1,1>>^ Ai de Ariel! Ariel, a cidade onde acampou Davi. Acrescentem um ano a outro e deixem seguir o seu ciclo de festas.

[[v23-29-2]]

^<<v23-29-2,2>>^ Mas eu sitiarei Ariel, que vai chorar e lamentar-se, e vai ser para mim como uma fornalha de altar.

[[v23-29-3]]

^<<v23-29-3,3>>^ Acamparei ao seu redor; eu a cercarei de torres e instalarei contra você minhas obras de cerco.

[[v23-29-4]]

^<<v23-29-4,4>>^ Lançada ao chão, de lá você falará; do pó virão em murmúrio as suas palavras. Fantasmagórica, subirá sua voz da terra; um sussurro vindo do pó será sua voz.

[[v23-29-5]]

^<<v23-29-5,5>>^ Mas os seus muitos inimigos se tornarão como o pó fino, as hordas cruéis, como palha levada pelo vento. Repentinamente, de golpe,

[[v23-29-6]]

^<<v23-29-6,6>>^ o Senhor dos Exércitos virá com trovões e terremoto e estrondoso ruído, com tempestade e furacão e chamas de um fogo devorador.

[[v23-29-7]]

^<<v23-29-7,7>>^ Então as hordas de todas as nações que lutam contra Ariel, que investem contra ele e contra a sua fortaleza e a sitiam, serão como acontece num sonho, numa visão noturna,

[[v23-29-8]]

^<<v23-29-8,8>>^ como quando um homem faminto sonha que está comendo, mas acorda e sua fome continua; como quando um homem sedento sonha que está bebendo, mas acorda enfraquecido, sem ter saciado a sede. Assim será com as hordas de todas as nações que lutam contra o monte Sião.

[[v23-29-9]]

^<<v23-29-9,9>>^ Pasmem e fiquem atônitos! Ceguem-se a si mesmos e continuem cegos! Estão bêbados, não porém de vinho, cambaleiam, mas não pela bebida fermentada.

[[v23-29-10]]

^<<v23-29-10,10>>^ O Senhor trouxe sobre vocês um sono profundo: fechou os olhos de vocês, profetas; cobriu as cabeças de vocês, videntes.

[[v23-29-11]]

^<<v23-29-11,11>>^ Para vocês toda esta visão não passa de palavras seladas num livro. E se vocês derem o livro a alguém que saiba ler e lhe disserem: "Leia, por favor", ele responderá: "Não posso; está lacrado".

[[v23-29-12]]

^<<v23-29-12,12>>^ Ou, se vocês derem o livro a alguém que não saiba ler e lhe disserem: "Leia, por favor", ele responderá: "Não sei ler".

[[v23-29-13]]

^<<v23-29-13,13>>^ O Senhor diz:  "Esse povo se aproxima de mim com a boca e me honra com os lábios, mas o seu coração está longe de mim. A adoração que me prestam só é feita de regras ensinadas por homens.

[[v23-29-14]]

^<<v23-29-14,14>>^ Por isso uma vez mais deixarei atônito esse povo com maravilha e mais maravilha; a sabedoria dos sábios perecerá, a inteligência dos inteligentes se desvanecerá".

[[v23-29-15]]

^<<v23-29-15,15>>^ Ai daqueles que descem às profundezas para esconder seus planos do Senhor, que agem nas trevas e pensam: "Quem é que nos vê? Quem ficará sabendo? "

[[v23-29-16]]

^<<v23-29-16,16>>^ Vocês viram as coisas de cabeça para baixo! Como se fosse possível imaginar que o oleiro é igual ao barro! Acaso o objeto formado Pode dizer àquele que o formou: "Ele não me fez"? E o vaso poderá dizer do oleiro: "Ele nada sabe"?

[[v23-29-17]]

^<<v23-29-17,17>>^ Acaso o Líbano não será logo transformado em campo fértil, e não se pensará que o campo fértil é uma floresta?

[[v23-29-18]]

^<<v23-29-18,18>>^ Naquele dia os surdos ouvirão as palavras do livro, e, não mais em trevas e escuridão, os olhos dos cegos tornarão a ver.

[[v23-29-19]]

^<<v23-29-19,19>>^ Mais uma vez os humildes se alegrarão no Senhor, e os necessitados exultarão no Santo de Israel.

[[v23-29-20]]

^<<v23-29-20,20>>^ Será o fim do cruel, o zombador desaparecerá e todos os de olhos inclinados para o mal serão eliminados,

[[v23-29-21]]

^<<v23-29-21,21>>^ os quais com uma palavra tornam réu o inocente, no tribunal trapaceiam contra o defensor e com testemunho falso impedem que se faça justiça ao inocente.

[[v23-29-22]]

^<<v23-29-22,22>>^ Por isso o Senhor, que redimiu Abraão, diz à descendência de Jacó: "Jacó não será mais humilhado; e o seu rosto não tornará a empalidecer.

[[v23-29-23]]

^<<v23-29-23,23>>^ Quando ele vir em seu meio os seus filhos, a obra de minhas mãos, proclamarão o meu santo nome; reconhecerão a santidade do Santo de Jacó,

[[v23-29-24]]

^<<v23-29-24,24>>^ e no temor do Deus de Israel permanecerão. Os desorientados de espírito obterão entendimento; e os queixosos vão aceitar instrução".

'''

xref:023-isaias/023-isaias-028.adoc#v23-28-0[&#60; Capítulo Anterior] | <<v23-29-0,Topo>> | xref:023-isaias/023-isaias-030.adoc#v23-30-0[Próximo Capítulo &#62;]