include::./index.adoc[]

[[v23-32-0]]
=== Isaías, 32
// nvi ?, NVI - Nova Versão Internacional

[[v23-32-1]]

^<<v23-32-1,1>>^ Vejam! Um rei reinará com retidão, e príncipes governarão com justiça.

[[v23-32-2]]

^<<v23-32-2,2>>^ Cada homem será como um esconderijo contra o vento e um abrigo contra a tempestade, como correntes de água numa terra seca e como a sombra de uma grande rocha no deserto.

[[v23-32-3]]

^<<v23-32-3,3>>^ Então os olhos dos que vêem não estarão mais fechados, e os ouvidos dos que ouvem escutarão.

[[v23-32-4]]

^<<v23-32-4,4>>^ A mente do precipitado saberá julgar, e a língua gaguejante falará com facilidade e clareza.

[[v23-32-5]]

^<<v23-32-5,5>>^ O tolo já não será chamado nobre e o homem sem caráter não será tido em alta estima.

[[v23-32-6]]

^<<v23-32-6,6>>^ Pois o insensato fala com insensatez e só pensa no mal: Ele pratica a maldade e espalha mentiras sobre o Senhor; deixa o faminto sem nada e priva de água o sedento.

[[v23-32-7]]

^<<v23-32-7,7>>^ As artimanhas do homem sem caráter são perversas; ele inventa planos maldosos para destruir com mentiras o pobre, mesmo quando a súplica deste é justa.

[[v23-32-8]]

^<<v23-32-8,8>>^ Mas o homem nobre faz planos nobres, e graças aos seus feitos nobres permanece firme.

[[v23-32-9]]

^<<v23-32-9,9>>^ Vocês, mulheres tão complacentes, levantem-se e escutem-me! Vocês, filhas que se sentem seguras, ouçam o que lhes vou dizer!

[[v23-32-10]]

^<<v23-32-10,10>>^ Daqui a pouco mais de um ano, vocês, que se sentem seguras, ficarão apavoradas; a colheita de uvas falhará, e a colheita de frutas não virá.

[[v23-32-11]]

^<<v23-32-11,11>>^ Tremam, vocês, mulheres tranqüilas! Estremeçam, vocês, que se sentem seguras! Arranquem suas vestes, e vistam roupas de lamento na cintura.

[[v23-32-12]]

^<<v23-32-12,12>>^ Batam no peito e chorem pelos campos agradáveis, pelas videiras frutíferas

[[v23-32-13]]

^<<v23-32-13,13>>^ e pela terra do meu povo, terra infestada de espinhos e roseiras bravas; sim, pranteiem por todas as casas cheias de júbilo e por esta cidade exultante.

[[v23-32-14]]

^<<v23-32-14,14>>^ A fortaleza será abandonada, a cidade barulhenta ficará deserta, a cidadela e a torre de sentinela se tornarão covis, uma delícia para os jumentos, uma pastagem para os rebanhos,

[[v23-32-15]]

^<<v23-32-15,15>>^ até que sobre nós o Espírito seja derramado do alto, e o deserto se transforme em campo fértil, e o campo fértil pareça uma floresta.

[[v23-32-16]]

^<<v23-32-16,16>>^ A justiça habitará no deserto, e a retidão viverá no campo fértil.

[[v23-32-17]]

^<<v23-32-17,17>>^ O fruto da justiça será paz; o resultado da justiça será tranqüilidade e confiança para sempre.

[[v23-32-18]]

^<<v23-32-18,18>>^ O meu povo viverá em locais pacíficos, em casas seguras, em tranqüilos lugares de descanso,

[[v23-32-19]]

^<<v23-32-19,19>>^ mesmo que a saraiva arrase a floresta e a cidade seja nivelada ao pó.

[[v23-32-20]]

^<<v23-32-20,20>>^ Como vocês serão felizes, semeando perto das águas, e deixando soltos os bois e os jumentos!

'''

xref:023-isaias/023-isaias-031.adoc#v23-31-0[&#60; Capítulo Anterior] | <<v23-32-0,Topo>> | xref:023-isaias/023-isaias-033.adoc#v23-33-0[Próximo Capítulo &#62;]