include::./index.adoc[]

[[v23-14-0]]
=== Isaías, 14
// nvi ?, NVI - Nova Versão Internacional

[[v23-14-1]]

^<<v23-14-1,1>>^ O Senhor terá compaixão de Jacó; tornará a escolher Israel e os estabelecerá em sua própria terra. Os estrangeiros se juntarão a eles e farão parte da descendência de Jacó.

[[v23-14-2]]

^<<v23-14-2,2>>^ Povos os apanharão e os levarão ao seu próprio lugar. E a descendência de Israel possuirá os povos como servos e servas na terra do Senhor. Farão prisioneiros os seus captores e dominarão sobre os seus opressores.

[[v23-14-3]]

^<<v23-14-3,3>>^ No dia em que o Senhor lhe der descanso do sofrimento, da perturbação e da cruel escravidão que sobre você foi imposta,

[[v23-14-4]]

^<<v23-14-4,4>>^ assim você zombará do rei da Babilônia: Como chegou ao fim o opressor! Sua arrogância acabou-se!

[[v23-14-5]]

^<<v23-14-5,5>>^ O Senhor quebrou a vara dos ímpios, o cetro dos governantes,

[[v23-14-6]]

^<<v23-14-6,6>>^ que irados feriram os povos com golpes incessantes, e enfurecidos subjugaram as nações com perseguição implacável.

[[v23-14-7]]

^<<v23-14-7,7>>^ Toda a terra descansa tranqüila, todos irrompem em gritos de alegria.

[[v23-14-8]]

^<<v23-14-8,8>>^ Até os pinheiros e os cedros do Líbano alegram-se por sua causa e dizem: "Agora que você foi derrubado, nenhum lenhador vem derrubar-nos! "

[[v23-14-9]]

^<<v23-14-9,9>>^ Nas profundezas o Sheol está todo agitado para recebê-lo quando chegar. Por sua causa ele desperta os espíritos dos mortos, todos os governantes da terra. Ele os faz levantar-se dos seus tronos, todos os reis dos povos.

[[v23-14-10]]

^<<v23-14-10,10>>^ Todos responderão e lhe dirão: "Você também perdeu as forças como nós, e tornou-se como um de nós".

[[v23-14-11]]

^<<v23-14-11,11>>^ Sua soberba foi lançada na sepultura, junto com o som das suas liras; sua cama é de larvas, sua coberta, de vermes.

[[v23-14-12]]

^<<v23-14-12,12>>^ Como você caiu dos céus, ó estrela da manhã, filho da alvorada! Como foi atirado à terra, você, que derrubava as nações!

[[v23-14-13]]

^<<v23-14-13,13>>^ Você que dizia no seu coração: "Subirei aos céus; erguerei o meu trono acima das estrelas de Deus; eu me assentarei no monte da assembléia, no ponto mais elevado do monte santo.

[[v23-14-14]]

^<<v23-14-14,14>>^ Subirei mais alto que as mais altas nuvens; serei como o Altíssimo".

[[v23-14-15]]

^<<v23-14-15,15>>^ Mas às profundezas do Sheol você será levado, irá ao fundo do abismo!

[[v23-14-16]]

^<<v23-14-16,16>>^ Os que olham para você admiram-se da sua situação, e a seu respeito ponderam: "É esse o homem que fazia tremer a terra e abalava os reinos,

[[v23-14-17]]

^<<v23-14-17,17>>^ e fez do mundo um deserto, conquistou cidades e não deixou que os seus prisioneiros voltassem para casa? "

[[v23-14-18]]

^<<v23-14-18,18>>^ Todos os reis das nações jazem honrosamente, cada um em seu próprio túmulo.

[[v23-14-19]]

^<<v23-14-19,19>>^ Mas você é atirado fora do seu túmulo, como um galho rejeitado; como as roupas dos mortos que foram feridos pela espada; como os que descem às pedras da cova; como um cadáver pisoteado,

[[v23-14-20]]

^<<v23-14-20,20>>^ você não se unirá a eles num sepultamento, pois destruiu a sua própria terra, e matou o seu próprio povo. Nunca se mencione a descendência dos malfeitores!

[[v23-14-21]]

^<<v23-14-21,21>>^ Preparem um local para matar os filhos dele por causa da iniqüidade dos seus antepassados; para que eles não se levantem para herdar a terra e a cobrirem de cidades.

[[v23-14-22]]

^<<v23-14-22,22>>^ "Eu me levantarei contra eles", diz o Senhor dos Exércitos. "Eliminarei da Babilônia o seu nome e os seus sobreviventes, sua prole e os seus descendentes", diz o Senhor.

[[v23-14-23]]

^<<v23-14-23,23>>^ "Farei dela um lugar para corujas e uma terra pantanosa; vou varrê-la com a vassoura da destruição", diz o Senhor dos Exércitos.

[[v23-14-24]]

^<<v23-14-24,24>>^ O Senhor dos Exércitos jurou: "Certamente, como planejei, assim acontecerá, e, como pensei, assim será.

[[v23-14-25]]

^<<v23-14-25,25>>^ Esmagarei a Assíria na minha terra; nos meus montes a pisotearei. O seu jugo será tirado do meu povo, e o seu fardo dos ombros deles".

[[v23-14-26]]

^<<v23-14-26,26>>^ Esse é o plano estabelecido para toda a terra; essa é a mão estendida sobre todas as nações.

[[v23-14-27]]

^<<v23-14-27,27>>^ Pois esse é o propósito do Senhor dos Exércitos; quem pode impedi-lo? Sua mão está estendida; quem pode fazê-la recuar?

[[v23-14-28]]

^<<v23-14-28,28>>^ Esta advertência veio no ano em que o rei Acaz morreu:

[[v23-14-29]]

^<<v23-14-29,29>>^ Vocês, filisteus, todos vocês, não se alegrem porque a vara que os feria está quebrada! Da raiz da cobra brotará uma víbora, e o seu fruto será uma serpente veloz.

[[v23-14-30]]

^<<v23-14-30,30>>^ O mais pobre dos pobres achará pastagem, e os necessitados descansarão em segurança. Mas eu matarei de fome a raiz de vocês, e ela matará os seus sobreviventes.

[[v23-14-31]]

^<<v23-14-31,31>>^ Lamente, ó porta! Clame, ó cidade! Derretam-se todos vocês, filisteus! Do norte vem um exército, e ninguém desertou de suas fileiras.

[[v23-14-32]]

^<<v23-14-32,32>>^ Que resposta se dará aos emissários daquela nação? Esta: "O Senhor estabeleceu Sião, e nela encontrarão refúgio os aflitos do seu povo".

'''

xref:023-isaias/023-isaias-013.adoc#v23-13-0[&#60; Capítulo Anterior] | <<v23-14-0,Topo>> | xref:023-isaias/023-isaias-015.adoc#v23-15-0[Próximo Capítulo &#62;]