include::./index.adoc[]

[[v23-13-0]]
=== Isaías, 13
// nvi ?, NVI - Nova Versão Internacional

[[v23-13-1]]

^<<v23-13-1,1>>^ Advertência contra a Babilônia, que Isaías, filho de Amoz, recebeu em visão:

[[v23-13-2]]

^<<v23-13-2,2>>^ Levantem uma bandeira no topo de uma colina desnuda, gritem a eles; chamem-nos com um aceno, para que entrem pelas portas dos nobres.

[[v23-13-3]]

^<<v23-13-3,3>>^ Eu mesmo ordenei aos meus santos; para executarem a minha ira já convoquei os meus guerreiros, os que se regozijam com o meu triunfo.

[[v23-13-4]]

^<<v23-13-4,4>>^ Escutem! Há um barulho nos montes como o de uma grande multidão! Escutem! É uma gritaria entre os reinos, como nações formando uma imensa multidão! O Senhor dos Exércitos está reunindo um exército para a guerra.

[[v23-13-5]]

^<<v23-13-5,5>>^ Eles vêm de terras distantes, lá dos confins dos céus; o Senhor e as armas da sua ira, para destruírem todo o país.

[[v23-13-6]]

^<<v23-13-6,6>>^ Chorem, pois o dia do Senhor está perto; virá como destruição da parte do Todo-poderoso.

[[v23-13-7]]

^<<v23-13-7,7>>^ Por isso, todas as mãos ficarão trêmulas, o coração de todos os homens se derreterá.

[[v23-13-8]]

^<<v23-13-8,8>>^ Ficarão apavorados, dores e aflições os dominarão; eles se contorcerão como a mulher em trabalho de parto. Olharão chocados uns para os outros, com os rostos em fogo.

[[v23-13-9]]

^<<v23-13-9,9>>^ Vejam! O dia do Senhor está perto, dia cruel, de ira e grande furor, para devastar a terra e destruir os seus pecadores.

[[v23-13-10]]

^<<v23-13-10,10>>^ As estrelas do céu e as suas constelações não mostrarão a sua luz. O sol nascente escurecerá, e a lua não fará brilhar a sua luz.

[[v23-13-11]]

^<<v23-13-11,11>>^ Castigarei o mundo por causa da sua maldade, os ímpios pela sua iniqüidade. Darei fim à arrogância dos altivos e humilharei o orgulho dos cruéis.

[[v23-13-12]]

^<<v23-13-12,12>>^ Tornarei o homem mais escasso do que o ouro puro, mais raro do que o ouro de Ofir.

[[v23-13-13]]

^<<v23-13-13,13>>^ Por isso farei o céu tremer; e a terra se moverá do seu lugar diante da ira do Senhor dos Exércitos, no dia do furor da sua ira.

[[v23-13-14]]

^<<v23-13-14,14>>^ Como a gazela perseguida, como a ovelha que ninguém recolhe, cada um voltará para o seu povo, cada um fugirá para a sua terra.

[[v23-13-15]]

^<<v23-13-15,15>>^ Todo o que for capturado será traspassado; todos os que forem apanhados cairão à espada.

[[v23-13-16]]

^<<v23-13-16,16>>^ Seus bebês serão despedaçados diante dos seus olhos; suas casas serão saqueadas e suas mulheres violentadas.

[[v23-13-17]]

^<<v23-13-17,17>>^ Vejam! Eu despertarei contra eles os medos, que não se interessam pela prata nem se deleitam com o ouro.

[[v23-13-18]]

^<<v23-13-18,18>>^ Seus arcos ferirão os jovens, e eles não terão misericórdia dos bebês, nem olharão com compaixão para as crianças.

[[v23-13-19]]

^<<v23-13-19,19>>^ Babilônia, a jóia dos reinos, o esplendor do orgulho dos babilônios. será destruída por Deus à semelhança de Sodoma e Gomorra.

[[v23-13-20]]

^<<v23-13-20,20>>^ Nunca mais será repovoada nem habitada, de geração em geração; o árabe não armará ali a sua tenda e o pastor não fará descansar ali o seu rebanho.

[[v23-13-21]]

^<<v23-13-21,21>>^ Mas as criaturas do deserto lá estarão, e as suas casas se encherão de chacais; nela habitarão corujas e saltarão bodes selvagens.

[[v23-13-22]]

^<<v23-13-22,22>>^ As hienas uivarão em suas fortalezas, e os chacais em seus luxuosos palácios. O tempo dela está terminando, e os seus dias não serão prolongados.

'''

xref:023-isaias/023-isaias-012.adoc#v23-12-0[&#60; Capítulo Anterior] | <<v23-13-0,Topo>> | xref:023-isaias/023-isaias-014.adoc#v23-14-0[Próximo Capítulo &#62;]