include::./index.adoc[]

[[v23-58-0]]
=== Isaías, 58
// nvi ?, NVI - Nova Versão Internacional

[[v23-58-1]]

^<<v23-58-1,1>>^ "Grite alto, não se contenha! Levante a voz como trombeta. Anuncie ao meu povo a rebelião dele, e à comunidade de Jacó, os seus pecados.

[[v23-58-2]]

^<<v23-58-2,2>>^ Pois dia a dia me procuram; parecem desejosos de conhecer os meus caminhos, como se fossem uma nação que faz o que é direito e que não abandonou os mandamentos do seu Deus. Pedem-me decisões justas e parecem desejosos de que Deus se aproxime deles.

[[v23-58-3]]

^<<v23-58-3,3>>^ ‘Por que jejuamos’, dizem, ‘e não o viste? Por que nos humilhamos, e não reparaste? ’ Contudo, no dia do seu jejum vocês fazem o que é do agrado de vocês, e exploram os seus empregados.

[[v23-58-4]]

^<<v23-58-4,4>>^ Seu jejum termina em discussão e rixa, e em brigas de socos brutais. Vocês não podem jejuar como fazem hoje e esperar que a sua voz seja ouvida no alto.

[[v23-58-5]]

^<<v23-58-5,5>>^ Será esse o jejum que escolhi, que apenas um dia o homem se humilhe, incline a cabeça como o junco e se deite sobre pano de saco e cinzas? É isso que vocês chamam jejum, um dia aceitável ao Senhor?

[[v23-58-6]]

^<<v23-58-6,6>>^ "O jejum que desejo não é este: soltar as correntes da injustiça, desatar as cordas do jugo, pôr em liberdade os oprimidos e romper todo jugo?

[[v23-58-7]]

^<<v23-58-7,7>>^ Não é partilhar sua comida com o faminto, abrigar o pobre desamparado, vestir o nu que você encontrou, e não recusar ajuda ao próximo?

[[v23-58-8]]

^<<v23-58-8,8>>^ Aí sim, a sua luz irromperá como a alvorada, e prontamente surgirá a sua cura; a sua retidão irá adiante de você, e a glória do Senhor estará na sua retaguarda.

[[v23-58-9]]

^<<v23-58-9,9>>^ Aí sim, você clamará ao Senhor, e ele responderá; você gritará por socorro, e ele dirá: Aqui estou. "Se você eliminar do seu meio o jugo opressor, o dedo acusador e a falsidade do falar;

[[v23-58-10]]

^<<v23-58-10,10>>^ se com renúncia própria você beneficiar os famintos e satisfizer o anseio dos aflitos, então a sua luz despontará nas trevas, e a sua noite será como o meio-dia.

[[v23-58-11]]

^<<v23-58-11,11>>^ O Senhor o guiará constantemente; satisfará os seus desejos numa terra ressequida pelo sol e fortalecerá os seus ossos. Você será como um jardim bem regado, como uma fonte cujas águas nunca faltam.

[[v23-58-12]]

^<<v23-58-12,12>>^ Seu povo reconstruirá as velhas ruínas e restaurará os alicerces antigos; você será chamado reparador de muros, restaurador de ruas e moradias.

[[v23-58-13]]

^<<v23-58-13,13>>^ "Se você vigiar seus pés para não profanar o sábado e para não fazer o que bem quiser em meu santo dia; se você chamar delícia o sábado e honroso o santo dia do Senhor, e se honrá-lo, deixando de seguir seu próprio caminho, de fazer o que bem quiser e de falar futilidades,

[[v23-58-14]]

^<<v23-58-14,14>>^ então você terá no Senhor a sua alegria, e eu farei com que você cavalgue nos altos da terra e se banqueteie com a herança de Jacó, seu pai. " Pois é o Senhor quem fala.

'''

xref:023-isaias/023-isaias-057.adoc#v23-57-0[&#60; Capítulo Anterior] | <<v23-58-0,Topo>> | xref:023-isaias/023-isaias-059.adoc#v23-59-0[Próximo Capítulo &#62;]