include::./index.adoc[]

[[v23-27-0]]
=== Isaías, 27
// nvi ?, NVI - Nova Versão Internacional

[[v23-27-1]]

^<<v23-27-1,1>>^ Naquele dia, o Senhor com sua espada severa, longa e forte, castigará o Leviatã, serpente veloz, o Leviatã, serpente tortuosa; matará no mar a serpente aquática.

[[v23-27-2]]

^<<v23-27-2,2>>^ Naquele dia, cantem sobre a vinha frutífera:

[[v23-27-3]]

^<<v23-27-3,3>>^ "Eu, o Senhor, sou o seu vigia, rego-a constantemente e a protejo dia e noite para impedir que lhe façam dano.

[[v23-27-4]]

^<<v23-27-4,4>>^ Não estou irado. Se espinheiros e roseiras bravas me enfrentassem, eu marcharia contra eles em combate e poria fogo neles todos.

[[v23-27-5]]

^<<v23-27-5,5>>^ Se não, que venham buscar refúgio em mim; que façam as pazes comigo. Sim, que façam as pazes comigo".

[[v23-27-6]]

^<<v23-27-6,6>>^ Nos dias vindouros Jacó lançará raízes, Israel terá botões e flores e encherá o mundo de frutos.

[[v23-27-7]]

^<<v23-27-7,7>>^ Acaso o Senhor o feriu como feriu aqueles que o feriram? Acaso ele foi morto como foram mortos os que o feriram?

[[v23-27-8]]

^<<v23-27-8,8>>^ Pelo desterro e pelo exílio o julga, com seu sopro violento ele o expulsa, como num dia de rajadas do vento oriental.

[[v23-27-9]]

^<<v23-27-9,9>>^ Assim será perdoada a maldade de Jacó, e será este o fruto da remoção do seu pecado: Quando ele fizer com que as pedras do altar sejam esmigalhadas e fiquem como pó de giz, os postes sagrados e os altares de incenso não ficarão de pé.

[[v23-27-10]]

^<<v23-27-10,10>>^ A cidade fortificada está abandonada, desabitada e esquecida como o deserto; ali os bezerros pastam e se deitam, e desfolham os seus ramos.

[[v23-27-11]]

^<<v23-27-11,11>>^ Quando os seus ramos estão secos e quebram-se, as mulheres fazem fogo com eles, pois esse é um povo sem entendimento. Por isso aquele que o fez não tem compaixão dele, aquele que o formou não lhe mostra misericórdia.

[[v23-27-12]]

^<<v23-27-12,12>>^ Naquele dia o Senhor debulhará desde as margens do Eufrates até o ribeiro do Egito, e vocês, israelitas, serão ajuntados um a um.

[[v23-27-13]]

^<<v23-27-13,13>>^ E naquele dia soará uma grande trombeta. Os que estavam perecendo na Assíria e os que estavam exilados no Egito virão e adorarão o Senhor no monte santo, em Jerusalém.

'''

xref:023-isaias/023-isaias-026.adoc#v23-26-0[&#60; Capítulo Anterior] | <<v23-27-0,Topo>> | xref:023-isaias/023-isaias-028.adoc#v23-28-0[Próximo Capítulo &#62;]