include::./index.adoc[]

[[v23-60-0]]
=== Isaías, 60
// nvi ?, NVI - Nova Versão Internacional

[[v23-60-1]]

^<<v23-60-1,1>>^ "Levante-se, refulja! Porque chegou a sua luz, e a glória do Senhor raia sobre você.

[[v23-60-2]]

^<<v23-60-2,2>>^ Olhe! A escuridão cobre a terra, dessas trevas envolvem os povos, mas sobre você raia o Senhor, e sobre você se vê a sua glória.

[[v23-60-3]]

^<<v23-60-3,3>>^ As nações virão à sua luz e os reis ao fulgor do sua alvorecer.

[[v23-60-4]]

^<<v23-60-4,4>>^ "Olhe ao redor, e veja: Todos se reúnem e vêm a você; de longe vêm os seus filhos, e as suas filhas vêm carregadas nos braços.

[[v23-60-5]]

^<<v23-60-5,5>>^ Então o verás e ficarás radiante; o seu coração pulsará forte e se encherá de alegria, porque a riqueza dos mares lhe será trazida, e a você virão as riquezas das nações.

[[v23-60-6]]

^<<v23-60-6,6>>^ Manadas de camelos cobrirão a sua terra, camelos novos de Midiã e de Efá. Virão todos os de Sabá carregando ouro e incenso e proclamando o louvor do Senhor.

[[v23-60-7]]

^<<v23-60-7,7>>^ Todos os rebanhos de Quedar se reunirão junto de você, e os carneiros de Nebaiote a servirão; serão aceitos como ofertas em meu altar, e adornarei o meu glorioso templo.

[[v23-60-8]]

^<<v23-60-8,8>>^ "Quem são estes que voam como nuvens, que voam como pombas para os seus ninhos?

[[v23-60-9]]

^<<v23-60-9,9>>^ Pois as ilhas esperam em mim; à frente vêm os navios de Társis, trazendo de longe os seus filhos, com prata e ouro, para a honra do Senhor, o seu Deus, o Santo de Israel, porque ele se revestiu de esplendor.

[[v23-60-10]]

^<<v23-60-10,10>>^ "Estrangeiros reconstruirão os seus muros, e seus reis a servirão. Com ira eu a feri, mas com amor lhe mostrarei compaixão.

[[v23-60-11]]

^<<v23-60-11,11>>^ As suas portas permanecerão abertas; jamais serão fechadas, dia e noite, para que lhe tragam as riquezas das nações, com seus reis e seu séquito.

[[v23-60-12]]

^<<v23-60-12,12>>^ Pois a nação e o reino que não a servirem perecerão; serão totalmente exterminados.

[[v23-60-13]]

^<<v23-60-13,13>>^ "A glória do Líbano virá a você, juntos virão o pinheiro, o abeto e o cipreste, para adornarem o lugar do meu santuário; e eu glorificarei o local em que pisam os meus pés.

[[v23-60-14]]

^<<v23-60-14,14>>^ Os filhos dos seus opressores virão e se inclinarão diante de você; todos os que a desprezam se curvarão aos seus pés e a chamarão cidade do Senhor, Sião do Santo de Israel.

[[v23-60-15]]

^<<v23-60-15,15>>^ "Em vez de abandonada e odiada, sem que ninguém a percorresse, farei de você um orgulho, uma alegria para todas as gerações.

[[v23-60-16]]

^<<v23-60-16,16>>^ Você beberá o leite das nações e será amamentada por mulheres nobres. Então você saberá que eu, o Senhor, sou o seu Salvador, o seu Redentor, o Poderoso de Jacó.

[[v23-60-17]]

^<<v23-60-17,17>>^ Em vez de bronze eu lhe trarei ouro, e em vez de ferro, prata. Em vez de madeira eu lhe trarei bronze, e em vez de pedras, ferro. Farei da paz o seu dominador, da justiça, o seu governador.

[[v23-60-18]]

^<<v23-60-18,18>>^ Não se ouvirá mais falar de violência em sua terra, nem de ruína e destruição dentro de suas fronteiras. Os seus muros você chamará salvação, e as suas portas, louvor.

[[v23-60-19]]

^<<v23-60-19,19>>^ O sol não será mais a sua luz de dia, e você não terá mais o brilho do luar, pois o Senhor será a sua luz para sempre; o seu Deus será a sua glória.

[[v23-60-20]]

^<<v23-60-20,20>>^ O seu sol nunca se porá, e a sua lua nunca desaparecerá, porque o Senhor será a sua luz, para sempre e os seus dias de tristeza terão fim.

[[v23-60-21]]

^<<v23-60-21,21>>^ Então todo o seu povo será justo, e possuirá a terra para sempre. Ele é o renovo que plantei, obra das minhas mãos, para manifestação da minha glória.

[[v23-60-22]]

^<<v23-60-22,22>>^ O mais pequenino se tornará mil, o menor será uma nação poderosa. Eu sou o Senhor; na hora certa farei que isso aconteça depressa. "

'''

xref:023-isaias/023-isaias-059.adoc#v23-59-0[&#60; Capítulo Anterior] | <<v23-60-0,Topo>> | xref:023-isaias/023-isaias-061.adoc#v23-61-0[Próximo Capítulo &#62;]