include::./index.adoc[]

[[v23-30-0]]
=== Isaías, 30
// nvi ?, NVI - Nova Versão Internacional

[[v23-30-1]]

^<<v23-30-1,1>>^ "Ai dos filhos obstinados", declara o Senhor, "que executam planos que não são meus, fazem acordo sem minha aprovação, para ajuntar pecado sobre pecado,

[[v23-30-2]]

^<<v23-30-2,2>>^ que descem ao Egito sem consultar-me, para buscar proteção no poder do faraó, e refúgio na sombra do Egito.

[[v23-30-3]]

^<<v23-30-3,3>>^ Mas a proteção do faraó lhes trará vergonha, e a sombra do Egito lhe causará humilhação.

[[v23-30-4]]

^<<v23-30-4,4>>^ Embora seus líderes tenham ido à Zoa e seus enviados tenham chegado a Hanes,

[[v23-30-5]]

^<<v23-30-5,5>>^ todos se envergonharão por causa de um povo que lhes é inútil, que não traz ajuda nem vantagem, mas apenas vergonha e zombaria. "

[[v23-30-6]]

^<<v23-30-6,6>>^ Advertência contra os animais do Neguebe: Atravessando uma terra hostil e severa, de leões e leoas, de víboras e serpentes velozes, os enviados transportam suas riquezas no lombo de jumentos, seus tesouros nas corcovas de camelos, para aquela nação inútil,

[[v23-30-7]]

^<<v23-30-7,7>>^ o Egito, cujo socorro é totalmente inútil. Por isso eu o chamo Raabe, fera que nada faz.

[[v23-30-8]]

^<<v23-30-8,8>>^ Agora vá, escreva isso numa tabuinha para eles, registre-o num livro, para que nos dias vindouros seja um testemunho eterno.

[[v23-30-9]]

^<<v23-30-9,9>>^ Esse povo é rebelde; são filhos mentirosos, filhos que não querem saber da instrução do Senhor.

[[v23-30-10]]

^<<v23-30-10,10>>^ Eles dizem aos videntes: "Não tenham mais visões! " e aos profetas: "Não nos revelem o que é certo! Falem-nos coisas agradáveis, profetizem ilusões.

[[v23-30-11]]

^<<v23-30-11,11>>^ Deixem esse caminho, abandonem essa vereda, e parem de confrontar-nos com o Santo de Israel! "

[[v23-30-12]]

^<<v23-30-12,12>>^ Por isso diz o Santo de Israel: "Como vocês rejeitaram esta mensagem, apelaram para a opressão e confiaram nos perversos,

[[v23-30-13]]

^<<v23-30-13,13>>^ este pecado será para vocês como um muro alto, rachado e torto, que de repente desaba, inesperadamente.

[[v23-30-14]]

^<<v23-30-14,14>>^ Ele o fará em pedaços como um vaso de barro, tão esmigalhado que entre os seus pedaços não se achará um caco que sirva para pegar brasas de uma lareira ou para tirar água da cisterna".

[[v23-30-15]]

^<<v23-30-15,15>>^ Diz o Soberano Senhor, o Santo de Israel: "No arrependimento e no descanso está a salvação de vocês, na quietude e na confiança está o seu vigor, mas vocês não quiseram.

[[v23-30-16]]

^<<v23-30-16,16>>^ Vocês disseram: ‘Não, nós vamos fugir a cavalo’. E fugirão! Vocês disseram: ‘Cavalgaremos cavalos velozes’. Velozes serão os seus perseguidores!

[[v23-30-17]]

^<<v23-30-17,17>>^ Mil fugirão diante da ameaça de um; diante da ameaça de cinco todos vocês fugirão, até que vocês sejam deixados como um mastro no alto de um monte, como uma bandeira numa colina".

[[v23-30-18]]

^<<v23-30-18,18>>^ Contudo, o Senhor espera o momento de ser bondoso com vocês; ele ainda se levantará para mostrar-lhes compaixão. Pois o Senhor é Deus de justiça. Como são felizes todos os que nele esperam!

[[v23-30-19]]

^<<v23-30-19,19>>^ Ó povo de Sião, que mora em Jerusalém, você não vai chorar mais. Como ele será bondoso quando você clamar por socorro! Assim que ele ouvir, lhe responderá.

[[v23-30-20]]

^<<v23-30-20,20>>^ Embora o Senhor lhe dê o pão da adversidade e a água da aflição, o seu mestre não se esconderá mais; com seus próprios olhos vocês o verão.

[[v23-30-21]]

^<<v23-30-21,21>>^ Quer você se volte para a direita quer para a esquerda, uma voz atrás de você lhe dirá: "Este é o caminho; siga-o".

[[v23-30-22]]

^<<v23-30-22,22>>^ Então você tratará como impuras as suas imagens revestidas de prata e os seus ídolos recobertos de ouro; você os jogará fora como um trapo imundo e lhes dirá: "Fora! "

[[v23-30-23]]

^<<v23-30-23,23>>^ Ele também lhe mandará chuva para a semente que você semear, e a terra dará alimento rico e farto. Naquele dia o seu gado pastará em grandes prados.

[[v23-30-24]]

^<<v23-30-24,24>>^ Os bois e os jumentos que lavram o solo comerão forragem e sal espalhados com forcado e pá.

[[v23-30-25]]

^<<v23-30-25,25>>^ No dia do grande massacre, quando caírem as torres, regatos de água fluirão sobre todo monte elevado e sobre toda colina altaneira.

[[v23-30-26]]

^<<v23-30-26,26>>^ A luz da lua brilhará como o sol, e a luz do sol será sete vezes mais brilhante, como a luz de sete dias completos, quando o Senhor cuidar das contusões do seu povo e curar as feridas que lhe causou.

[[v23-30-27]]

^<<v23-30-27,27>>^ Vejam! De longe vem o Nome do Senhor, com sua ira em chamas, e densas nuvens de fumaça; seus lábios estão cheios de ira, e sua língua é fogo consumidor.

[[v23-30-28]]

^<<v23-30-28,28>>^ Seu sopro é como uma torrente impetuosa, que sobe até o pescoço. Ele faz sacudir as nações na peneira da destruição; ele coloca na boca dos povos um freio que os desencaminha.

[[v23-30-29]]

^<<v23-30-29,29>>^ E vocês cantarão como em noite de festa sagrada; seus corações se regozijarão como quando se vai, ao som da flauta, ao monte do Senhor, à Rocha de Israel.

[[v23-30-30]]

^<<v23-30-30,30>>^ O Senhor fará que os homens ouçam sua voz majestosa e os levará a ver seu braço descendo com ira impetuosa e fogo consumidor, com aguaceiro, tempestades de raios e saraiva.

[[v23-30-31]]

^<<v23-30-31,31>>^ A voz do Senhor despedaçará a Assíria; com seu cetro a ferirá.

[[v23-30-32]]

^<<v23-30-32,32>>^ Cada pancada que com a vara o Senhor desferir para a castigar será dada ao som de tamborins e harpas, enquanto a estiver combatendo com os golpes do seu braço.

[[v23-30-33]]

^<<v23-30-33,33>>^ Tofete está pronta já faz tempo; foi preparada para o rei. Sua fogueira é funda e larga, com muita lenha e muito fogo; o sopro do Senhor, como uma torrente de enxofre ardente, a incendeia.

'''

xref:023-isaias/023-isaias-029.adoc#v23-29-0[&#60; Capítulo Anterior] | <<v23-30-0,Topo>> | xref:023-isaias/023-isaias-031.adoc#v23-31-0[Próximo Capítulo &#62;]