include::./index.adoc[]

[[v23-64-0]]
=== Isaías, 64
// nvi ?, NVI - Nova Versão Internacional

[[v23-64-1]]

^<<v23-64-1,1>>^ Ah, se rompesses os céus e descesses! Os montes tremeriam diante de ti!

[[v23-64-2]]

^<<v23-64-2,2>>^ Como quando o fogo acende os gravetos e faz a água ferver, desce, para que os teus inimigos conheçam o teu nome e as nações tremam diante de ti!

[[v23-64-3]]

^<<v23-64-3,3>>^ Pois, quando fizeste coisas tremendas, coisas que não esperávamos, desceste, e os montes tremeram diante de ti.

[[v23-64-4]]

^<<v23-64-4,4>>^ Desde os tempos antigos ninguém ouviu, nenhum ouvido percebeu, e olho nenhum viu outro Deus, além de ti, que trabalha para aqueles que nele esperam.

[[v23-64-5]]

^<<v23-64-5,5>>^ Vens ajudar aqueles que praticam a justiça com alegria, que se lembram de ti e dos teus caminhos. Mas, prosseguindo nós em nossos pecados, tu te iraste. Como, então, seremos salvos?

[[v23-64-6]]

^<<v23-64-6,6>>^ Somos como o impuro — todos nós! Todos os nossos atos de justiça são como trapo imundo. Murchamos como folhas, e como o vento as nossas iniqüidades nos levam para longe.

[[v23-64-7]]

^<<v23-64-7,7>>^ Não há ninguém que clame pelo teu nome, que se anime a apegar-se a ti, pois escondeste de nós o teu rosto e nos deixaste perecer por causa das nossas iniqüidades.

[[v23-64-8]]

^<<v23-64-8,8>>^ Contudo, Senhor, tu és o nosso Pai. Nós somos o barro; tu és o oleiro. Todos nós somos obra das tuas mãos.

[[v23-64-9]]

^<<v23-64-9,9>>^ Não te ires demais, ó Senhor! Não te lembres constantemente das nossas maldades. Olha para nós! Somos o teu povo!

[[v23-64-10]]

^<<v23-64-10,10>>^ As tuas cidades sagradas transformaram-se em deserto. Até Sião virou um deserto, e Jerusalém, uma desolação!

[[v23-64-11]]

^<<v23-64-11,11>>^ O nosso templo santo e glorioso, onde os nossos antepassados te louvavam, foi destruído pelo fogo, e tudo o que nos era precioso está em ruínas.

[[v23-64-12]]

^<<v23-64-12,12>>^ e depois disso tudo, Senhor, ainda irás te conter? Ficarás calado e nos castigarás além da conta?

'''

xref:023-isaias/023-isaias-063.adoc#v23-63-0[&#60; Capítulo Anterior] | <<v23-64-0,Topo>> | xref:023-isaias/023-isaias-065.adoc#v23-65-0[Próximo Capítulo &#62;]