include::./index.adoc[]

[[v23-15-0]]
=== Isaías, 15
// nvi ?, NVI - Nova Versão Internacional

[[v23-15-1]]

^<<v23-15-1,1>>^ Advertência contra Moabe: Sim, na noite em que foi destruída, Ar, em Moabe, ficou arruinada! E na noite em que foi destruída, Quir, em Moabe, ficou arruinada!

[[v23-15-2]]

^<<v23-15-2,2>>^ Sobe-se ao templo em Dibom, a seus altares idólatras, para chorar; Por causa de Nebo e de Medeba Moabe pranteia. Todas as cabeças estão rapadas e toda barba foi cortada.

[[v23-15-3]]

^<<v23-15-3,3>>^ Nas ruas andam vestidos de roupas de lamento; nos terraços e nas praças públicas todos pranteiam e se prostram chorando.

[[v23-15-4]]

^<<v23-15-4,4>>^ Hesbom e Eleale clamam; até Jaaz as suas vozes são ouvidas. Por isso os homens armados de Moabe gritam, e o coração deles treme.

[[v23-15-5]]

^<<v23-15-5,5>>^ O meu coração clama por causa de Moabe! Os seus fugitivos vão até Zoar, até Eglate-Selisia. Sobem pelo caminho de Luíte, caminhando e chorando. Pela estrada de Horonaim levantam clamor em face da destruição,

[[v23-15-6]]

^<<v23-15-6,6>>^ porque as águas de Ninrim secaram-se, a pastagem secou-se e a vegetação morreu; todo o verde desapareceu!

[[v23-15-7]]

^<<v23-15-7,7>>^ Por isso, a riqueza que adquiriram e armazenaram eles levam para além do riacho dos Salgueiros.

[[v23-15-8]]

^<<v23-15-8,8>>^ Com efeito, seu clamor espalha-se por todo o território de Moabe; sua lamentação até Eglaim, até Beer-Elim.

[[v23-15-9]]

^<<v23-15-9,9>>^ Ainda que as águas de Dimom estejam cheias de sangue, trarei mais mal sobre Dimom; um leão sobre os fugitivos de Moabe e sobre aqueles que permanecem na terra.

'''

xref:023-isaias/023-isaias-014.adoc#v23-14-0[&#60; Capítulo Anterior] | <<v23-15-0,Topo>> | xref:023-isaias/023-isaias-016.adoc#v23-16-0[Próximo Capítulo &#62;]