include::./index.adoc[]

[[v23-7-0]]
=== Isaías, 7
// nvi ?, NVI - Nova Versão Internacional

[[v23-7-1]]

^<<v23-7-1,1>>^ Quando Acaz, filho de Jotão, e neto de Uzias, era rei de Judá, o rei Rezim, da Síria, e Peca, filho de Remalias, rei de Israel, atacaram Jerusalém, mas não puderam vencê-la.

[[v23-7-2]]

^<<v23-7-2,2>>^ Informaram ao rei: "A Síria montou acampamento em Efraim". Com isso o coração de Acaz e do seu povo agitou-se, como as árvores da floresta agitam-se com o vento.

[[v23-7-3]]

^<<v23-7-3,3>>^ Então o Senhor disse a Isaías: "Saiam, você e seu filho Sear-Jasube, e vão encontrar-se com Acaz no final do aqueduto do açude Superior, na estrada que vai para o campo do Lavandeiro.

[[v23-7-4]]

^<<v23-7-4,4>>^ Diga a ele: ‘Tenha cuidado, acalme-se e não tenha medo. Que o seu coração não se desanime por causa do furor destes restos de lenha fumegantes: Rezim, a Síria e o filho de Remalias.

[[v23-7-5]]

^<<v23-7-5,5>>^ " ‘Porque a Síria, Efraim e o filho de Remalias têm tramado a sua ruína, dizendo:

[[v23-7-6]]

^<<v23-7-6,6>>^ "Vamos invadir o reino de Judá; vamos rasgá-lo e dividi-lo entre nós, e fazer o filho de Tabeel reinar sobre ele".

[[v23-7-7]]

^<<v23-7-7,7>>^ Assim diz o Soberano Senhor: " ‘Não será assim, isso não acontecerá,

[[v23-7-8]]

^<<v23-7-8,8>>^ pois a cabeça da Síria é Damasco, e a cabeça de Damasco é Rezim. Em sessenta e cinco anos Efraim estará destruído demais para ser um povo.

[[v23-7-9]]

^<<v23-7-9,9>>^ A cabeça de Efraim é Samaria, e a cabeça de Samaria é o filho de Remalias. Se vocês não ficarem firmes na fé, com certeza não resistirão! ’ "

[[v23-7-10]]

^<<v23-7-10,10>>^ Disse ainda o Senhor a Acaz:

[[v23-7-11]]

^<<v23-7-11,11>>^ "Peça ao Senhor, ao seu Deus, um sinal miraculoso, seja das maiores profundezas, seja das alturas mais elevadas".

[[v23-7-12]]

^<<v23-7-12,12>>^ Mas Acaz disse: "Não pedirei; não porei o Senhor à prova".

[[v23-7-13]]

^<<v23-7-13,13>>^ Disse então Isaías: "Ouçam agora, descendentes de Davi! Não basta abusarem da paciência dos homens? Também vão abusar da paciência do meu Deus?

[[v23-7-14]]

^<<v23-7-14,14>>^ Por isso o Senhor mesmo lhes dará um sinal: a virgem ficará grávida e dará à luz um filho, e o chamará Emanuel.

[[v23-7-15]]

^<<v23-7-15,15>>^ Ele comerá coalhada e mel até a idade em que saiba rejeitar o erro e escolher o que é certo.

[[v23-7-16]]

^<<v23-7-16,16>>^ Mas antes que o menino saiba rejeitar o erro e escolher o que é certo, a terra dos dois reis que você teme ficará deserta.

[[v23-7-17]]

^<<v23-7-17,17>>^ O Senhor trará o rei da Assíria sobre você e sobre o seu povo e sobre a descendência de seu pai. Serão dias como nunca houve, desde que Efraim se separou de Judá".

[[v23-7-18]]

^<<v23-7-18,18>>^ Naquele dia o Senhor assobiará para chamar as moscas dos distantes rios do Egito e as abelhas da Assíria.

[[v23-7-19]]

^<<v23-7-19,19>>^ Todas virão e pousarão nos vales íngremes e nas fendas das rochas, em todos os espinheiros e em todas as cisternas.

[[v23-7-20]]

^<<v23-7-20,20>>^ Naquele dia o Senhor utilizará uma navalha alugada de além do Eufrates, o rei da Assíria, para rapar a sua cabeça e os pêlos de suas pernas e da sua barba.

[[v23-7-21]]

^<<v23-7-21,21>>^ Naquele dia o homem que tiver uma vaca e duas cabras

[[v23-7-22]]

^<<v23-7-22,22>>^ terá coalhada para comer, graças à fartura de leite que elas darão. Todos os que ficarem na terra comerão coalhada e mel.

[[v23-7-23]]

^<<v23-7-23,23>>^ Naquele dia, todo lugar onde havia mil videiras no valor de doze quilos de prata será deixado para as roseiras bravas e para os espinheiros.

[[v23-7-24]]

^<<v23-7-24,24>>^ Os homens entrarão ali com arcos e flechas, pois todo o país estará coberto de roseiras bravas e de espinheiros.

[[v23-7-25]]

^<<v23-7-25,25>>^ E às colinas antes lavradas com enxada você não irá mais, porque terá medo das roseiras bravas e dos espinheiros; nesses lugares os bois ficarão à solta e as ovelhas correrão livremente.

'''

xref:023-isaias/023-isaias-006.adoc#v23-6-0[&#60; Capítulo Anterior] | <<v23-7-0,Topo>> | xref:023-isaias/023-isaias-008.adoc#v23-8-0[Próximo Capítulo &#62;]