include::./index.adoc[]

[[v23-24-0]]
=== Isaías, 24
// nvi ?, NVI - Nova Versão Internacional

[[v23-24-1]]

^<<v23-24-1,1>>^ Vejam! O Senhor vai arrasar a terra e devastá-la; arruinará sua superfície e espalhará seus habitantes.

[[v23-24-2]]

^<<v23-24-2,2>>^ Será o mesmo para o sacerdote e o povo, para o senhor e o servo, para a senhora e a serva, para o vendedor e o comprador, para quem toma emprestado e quem empresta, para o devedor e o credor.

[[v23-24-3]]

^<<v23-24-3,3>>^ A terra será completamente arrasada e totalmente saqueada. Quem falou esta palavra foi o Senhor.

[[v23-24-4]]

^<<v23-24-4,4>>^ A terra seca-se e murcha, o mundo definha e murcha, definham os nobres da terra.

[[v23-24-5]]

^<<v23-24-5,5>>^ A terra está contaminada pelos seus habitantes, porque desobedeceram às leis, violaram os decretos e quebraram a aliança eterna.

[[v23-24-6]]

^<<v23-24-6,6>>^ Por isso a maldição consome a terra, e seu povo é culpado. Por isso os habitantes da terra são consumidos pelo fogo, ao ponto de sobrarem pouquíssimos.

[[v23-24-7]]

^<<v23-24-7,7>>^ O vinho novo vai-se, e a videira murcha; todos os que se divertiam gemem.

[[v23-24-8]]

^<<v23-24-8,8>>^ O som festivo dos tamborins foi silenciado, o barulho dos que se alegram parou, a harpa cheia de júbilo está muda.

[[v23-24-9]]

^<<v23-24-9,9>>^ Já não bebem vinho entoando canções; a bebida fermentada é amarga para os que a bebem.

[[v23-24-10]]

^<<v23-24-10,10>>^ A cidade vã está em ruínas; a entrada de cada casa está fechada.

[[v23-24-11]]

^<<v23-24-11,11>>^ Nas ruas clamam por vinho; toda a alegria chegou ao fim, toda celebração foi eliminada da terra.

[[v23-24-12]]

^<<v23-24-12,12>>^ A cidade foi deixada em ruínas, sua porta feita em pedaços.

[[v23-24-13]]

^<<v23-24-13,13>>^ Assim será na terra, entre as nações, como quando se usa a vara na oliveira ou se buscam os restos das uvas após a colheita.

[[v23-24-14]]

^<<v23-24-14,14>>^ Erguem as vozes, cantam de alegria; desde o Ocidente aclamam a majestade do Senhor.

[[v23-24-15]]

^<<v23-24-15,15>>^ Dêem glória, pois, ao Senhor no Oriente, e nas ilhas do mar exaltem o nome do Senhor, o Deus de Israel.

[[v23-24-16]]

^<<v23-24-16,16>>^ Desde os confins da terra ouvimos cantarem: "Glória seja dada ao Justo! " Mas eu disse: "Que desgraça! Que desgraça! Ai de mim! Os traidores traem! Os traidores agem traiçoeiramente! "

[[v23-24-17]]

^<<v23-24-17,17>>^ Pavor, cova e laço o aguardam, ó habitantes da terra!

[[v23-24-18]]

^<<v23-24-18,18>>^ Quem fugir ao grito de terror cairá na cova; quem sair da cova será pego no laço. Abertas estão as comportas dos céus; tremem os alicerces da terra.

[[v23-24-19]]

^<<v23-24-19,19>>^ A terra foi despedaçada, está destruída, totalmente abalada!

[[v23-24-20]]

^<<v23-24-20,20>>^ A terra cambaleia como um bêbado, balança como uma cabana ao vento; tão pesada sobre ela é a culpa de sua rebelião que cai para nunca mais se levantar!

[[v23-24-21]]

^<<v23-24-21,21>>^ Naquele dia o Senhor castigará os poderes em cima nos céus e os reis em baixo na terra.

[[v23-24-22]]

^<<v23-24-22,22>>^ Eles serão arrebanhados como prisioneiros numa masmorra, trancados numa prisão e castigados depois de muitos dias.

[[v23-24-23]]

^<<v23-24-23,23>>^ A lua ficará humilhada, e o sol, envergonhado; pois o Senhor dos Exércitos reinará no monte Sião e em Jerusalém, glorioso na presença dos seus líderes!

'''

xref:023-isaias/023-isaias-023.adoc#v23-23-0[&#60; Capítulo Anterior] | <<v23-24-0,Topo>> | xref:023-isaias/023-isaias-025.adoc#v23-25-0[Próximo Capítulo &#62;]