include::./index.adoc[]

[[v23-8-0]]
=== Isaías, 8
// nvi ?, NVI - Nova Versão Internacional

[[v23-8-1]]

^<<v23-8-1,1>>^ O Senhor me disse: "Tome uma placa de bom tamanho e nela escreva de forma legível: Maher-Shalal-Hash-Baz.

[[v23-8-2]]

^<<v23-8-2,2>>^ E chame o sacerdote Urias, e Zacarias, filho de Jeberequias, como testemunhas de confiança".

[[v23-8-3]]

^<<v23-8-3,3>>^ Então deitei-me com a profetisa, minha mulher, e ela engravidou e deu à luz um filho. E o Senhor me disse: "Dê-lhe o nome de Maher-Shalal-Hash-Baz.

[[v23-8-4]]

^<<v23-8-4,4>>^ Pois antes que o menino saiba dizer ‘papai’ ou ‘mamãe’, a riqueza de Damasco e os bens de Samaria serão levados pelo rei da Assíria".

[[v23-8-5]]

^<<v23-8-5,5>>^ O Senhor tornou a falar-me:

[[v23-8-6]]

^<<v23-8-6,6>>^ "Já que este povo rejeitou as águas de Siloé, que fluem mansamente, e alegrou-se com Rezim e com o filho de Remalias,

[[v23-8-7]]

^<<v23-8-7,7>>^ o Senhor está trazendo contra eles as poderosas e devastadoras águas do Eufrates, o rei da Assíria com todo o seu poderio. Elas transbordarão em todos os seus canais, encobrirão todas as suas margens

[[v23-8-8]]

^<<v23-8-8,8>>^ e inundarão Judá cobrindo tudo até o pescoço. Seus braços abertos se espalharão por toda a tua terra, ó Emanuel! "

[[v23-8-9]]

^<<v23-8-9,9>>^ Continuem a fazer o mal, ó nações, e vocês serão destruídas! Escutem, terras distantes: Ainda que vocês se preparem para o combate, serão destruídas! Sim, mesmo que se preparem para o combate, vocês serão destruídas!

[[v23-8-10]]

^<<v23-8-10,10>>^ Mesmo que vocês criem estratégias, elas serão frustradas; mesmo que façam planos, não terão sucesso, pois Deus está conosco!

[[v23-8-11]]

^<<v23-8-11,11>>^ O Senhor falou comigo com veemência, advertindo-me a não seguir o caminho desse povo. Ele disse:

[[v23-8-12]]

^<<v23-8-12,12>>^ "Não chamem conspiração tudo o que esse povo chama conspiração; não temam aquilo que eles temem, nem se apavorem.

[[v23-8-13]]

^<<v23-8-13,13>>^ Ao Senhor dos Exércitos é que vocês devem considerar santo, a ele é que vocês devem temer, dele é que vocês devem ter pavor.

[[v23-8-14]]

^<<v23-8-14,14>>^ Para os dois reinos de Israel ele será um santuário, mas também uma pedra de tropeço, uma rocha que faz cair. E para os habitantes de Jerusalém ele será uma armadilha e um laço.

[[v23-8-15]]

^<<v23-8-15,15>>^ Muitos deles tropeçarão, cairão e serão despedaçados, presos no laço e capturados".

[[v23-8-16]]

^<<v23-8-16,16>>^ Guarde o mandamento com cuidado e sele a lei entre os meus discípulos.

[[v23-8-17]]

^<<v23-8-17,17>>^ Esperarei pelo Senhor, que está escondendo o seu rosto da descendência de Jacó. Nele porei a minha esperança.

[[v23-8-18]]

^<<v23-8-18,18>>^ Aqui estou eu com os filhos que o Senhor me deu. Em Israel somos sinais e símbolos da parte do Senhor dos Exércitos, que habita no monte Sião.

[[v23-8-19]]

^<<v23-8-19,19>>^ Quando disserem a vocês: "Consultem médiuns e espíritas que murmuram encantamentos, pois todos procuram seus deuses e os mortos em favor dos vivos".

[[v23-8-20]]

^<<v23-8-20,20>>^ Respondam: "À lei e aos mandamentos! " Se eles não falarem conforme esta palavra, vocês jamais verão a luz!

[[v23-8-21]]

^<<v23-8-21,21>>^ Aflitos e famintos vaguearão pela terra; quando estiverem famintos, ficarão irados e, olhando para cima, amaldiçoarão o seu rei e o seu Deus.

[[v23-8-22]]

^<<v23-8-22,22>>^ Depois olharão para a terra e só verão aflição, trevas e temível escuridão, e serão atirados em densas trevas.

'''

xref:023-isaias/023-isaias-007.adoc#v23-7-0[&#60; Capítulo Anterior] | <<v23-8-0,Topo>> | xref:023-isaias/023-isaias-009.adoc#v23-9-0[Próximo Capítulo &#62;]