include::./index.adoc[]

[[v23-21-0]]
=== Isaías, 21
// nvi ?, NVI - Nova Versão Internacional

[[v23-21-1]]

^<<v23-21-1,1>>^ Advertência contra o deserto junto ao mar: Como um vendaval em redemoinhos que varre todo o Neguebe, um invasor vem do deserto, de uma terra pavorosa.

[[v23-21-2]]

^<<v23-21-2,2>>^ Eu tive uma visão terrível: O traidor fora traído, o saqueador saqueado. Elão, vá à luta! Média, feche o cerco! Pois, ponho fim a todo gemido que ela provocou.

[[v23-21-3]]

^<<v23-21-3,3>>^ Diante disso fiquei tomado de angústia, Tive dores como as de uma mulher em trabalho de parto; estou tão transtornado que não posso ouvir, tão atônito que não posso ver.

[[v23-21-4]]

^<<v23-21-4,4>>^ O meu coração se estremece, o temor toma conta de mim; o anoitecer que tanto aguardava transformou-se em terror para mim.

[[v23-21-5]]

^<<v23-21-5,5>>^ Eles põem as mesas, estendem a toalha, comem, bebem! Levantem-se, líderes, preparem os escudos!

[[v23-21-6]]

^<<v23-21-6,6>>^ Assim me diz o Senhor: "Vá, coloque um vigia de prontidão para que anuncie tudo o que se aproximar.

[[v23-21-7]]

^<<v23-21-7,7>>^ Quando ele vir carros com parelhas de cavalos, homens montados em jumentos ou em camelos, fique alerta, bem alerta".

[[v23-21-8]]

^<<v23-21-8,8>>^ Então o vigia gritou: "Dia após dia, meu senhor, eu fico na torre de vigia; todas as noites permaneço em meu posto.

[[v23-21-9]]

^<<v23-21-9,9>>^ Veja! Ali vem um homem num carro com uma parelha de cavalos. E ele responde: ‘Caiu! A Babilônia caiu! Todas as imagens dos seus deuses estão despedaçados no chão! ’ "

[[v23-21-10]]

^<<v23-21-10,10>>^ Ah, meu povo malhado na eira! Eu lhes conto o que ouvi da parte do Senhor dos Exércitos, da parte do Deus de Israel.

[[v23-21-11]]

^<<v23-21-11,11>>^ Advertência contra Dumá: Alguém de Seir me pergunta: "Guarda, quanto ainda falta para acabar a noite? Guarda, quanto falta para acabar a noite? "

[[v23-21-12]]

^<<v23-21-12,12>>^ O guarda responde: "Logo chega o dia mas a noite também vem. Se vocês quiserem perguntar de novo, voltem e perguntem".

[[v23-21-13]]

^<<v23-21-13,13>>^ Advertência contra a Arábia: Vocês, caravanas de dedanitas, que acampam nos bosques da Arábia,

[[v23-21-14]]

^<<v23-21-14,14>>^ tragam água para os sedentos; vocês, que vivem em Temá, tragam comida para os fugitivos.

[[v23-21-15]]

^<<v23-21-15,15>>^ Eles fogem da espada, da espada desembainhada, do arco preparado e da crueldade da batalha.

[[v23-21-16]]

^<<v23-21-16,16>>^ Assim me diz o Senhor: "Dentro de um ano, e nem um dia a mais, toda a pompa de Quedar chegará ao fim.

[[v23-21-17]]

^<<v23-21-17,17>>^ Poucos serão os sobreviventes dos flecheiros, dos guerreiros de Quedar". O Senhor, o Deus de Israel, falou.

'''

xref:023-isaias/023-isaias-020.adoc#v23-20-0[&#60; Capítulo Anterior] | <<v23-21-0,Topo>> | xref:023-isaias/023-isaias-022.adoc#v23-22-0[Próximo Capítulo &#62;]