include::./index.adoc[]

[[v23-10-0]]
=== Isaías, 10
// nvi ?, NVI - Nova Versão Internacional

[[v23-10-1]]

^<<v23-10-1,1>>^ Ai daqueles que fazem leis injustas, que escrevem decretos opressores,

[[v23-10-2]]

^<<v23-10-2,2>>^ para privar os pobres dos seus direitos e da justiça os oprimidos do meu povo, fazendo das viúvas sua presa e roubando dos órfãos!

[[v23-10-3]]

^<<v23-10-3,3>>^ Que farão vocês no dia do castigo, quando a destruição vier de um lugar distante? Atrás de quem vocês correrão em busca de ajuda? Onde deixarão todas as suas riquezas?

[[v23-10-4]]

^<<v23-10-4,4>>^ Nada poderão fazer, a não ser encolher-se entre os prisioneiros ou cair entre os mortos. Apesar disso tudo, a ira divina não se desviou; sua mão continua erguida.

[[v23-10-5]]

^<<v23-10-5,5>>^ "Ai dos assírios, a vara do meu furor, em cujas mãos está o bastão da minha ira!

[[v23-10-6]]

^<<v23-10-6,6>>^ Eu os envio contra uma nação ímpia, contra um povo que me enfurece, para saqueá-lo e arrancar-lhe os bens, e para pisoteá-lo como a lama das ruas.

[[v23-10-7]]

^<<v23-10-7,7>>^ Mas não é o que eles pretendem, não é o que têm planejado; antes, o seu propósito é destruir e dar fim a muitas nações.

[[v23-10-8]]

^<<v23-10-8,8>>^ ‘Os nossos comandantes não são todos reis? ’, eles perguntam.

[[v23-10-9]]

^<<v23-10-9,9>>^ ‘Acaso não aconteceu a Calno o mesmo que a Carquemis? Hamate não é como Arpade e Samaria como Damasco?

[[v23-10-10]]

^<<v23-10-10,10>>^ Assim como a minha mão conquistou esses reinos idólatras, reinos cujas imagens eram mais numerosas que as de Jerusalém e de Samaria,

[[v23-10-11]]

^<<v23-10-11,11>>^ eu tratarei Jerusalém e suas imagens como tratei Samaria e seus ídolos’ ".

[[v23-10-12]]

^<<v23-10-12,12>>^ Quando o Senhor terminar toda a sua obra contra o monte Sião e contra Jerusalém, ele dirá: "Castigarei o rei da Assíria pelo orgulho obstinado de seu coração e pelo seu olhar arrogante.

[[v23-10-13]]

^<<v23-10-13,13>>^ Pois ele diz: " ‘Com a força da minha mão eu o fiz, e com a minha sabedoria, porque tenho entendimento. Removi as fronteiras das nações, saqueei os seus tesouros; como um poderoso subjuguei seus habitantes.

[[v23-10-14]]

^<<v23-10-14,14>>^ Como se estica o braço para alcançar um ninho, assim estiquei o braço para apanhar a riqueza das nações; como os que ajuntam ovos abandonados, assim ajuntei toda a terra; não houve ninguém que batesse as asas ou que desse um pio’ ".

[[v23-10-15]]

^<<v23-10-15,15>>^ Será que o machado se exalta acima daquele que o maneja, ou a serra se vangloria contra aquele que a usa? Seria como se uma vara manejasse quem a ergue, ou o bastão levantasse quem não é madeira!

[[v23-10-16]]

^<<v23-10-16,16>>^ Por isso o Soberano, o Senhor dos Exércitos, enviará uma enfermidade devastadora sobre os seus fortes guerreiros; no lugar da sua glória se acenderá um fogo como chama abrasadora.

[[v23-10-17]]

^<<v23-10-17,17>>^ A Luz de Israel se tornará um fogo; o seu Santo, uma chama. Num único dia ela queimará e consumirá os seus espinheiros e as suas roseiras bravas.

[[v23-10-18]]

^<<v23-10-18,18>>^ A glória das suas florestas e dos seus campos férteis se extinguirá totalmente, como definha um enfermo.

[[v23-10-19]]

^<<v23-10-19,19>>^ E as árvores que sobrarem nas suas florestas serão tão poucas que até uma criança poderá contá-las.

[[v23-10-20]]

^<<v23-10-20,20>>^ Naquele dia o remanescente de Israel, os sobreviventes da descendência de Jacó, já não confiarão naquele que os feriu, antes confiarão no Senhor, no Santo de Israel, com toda a fidelidade.

[[v23-10-21]]

^<<v23-10-21,21>>^ Um remanescente voltará, sim, o remanescente de Jacó voltará para o Deus Poderoso.

[[v23-10-22]]

^<<v23-10-22,22>>^ Embora o seu povo, ó Israel, seja como a areia do mar, apenas um remanescente voltará. A destruição já foi decretada, e virá transbordante de justiça.

[[v23-10-23]]

^<<v23-10-23,23>>^ O Senhor, o Senhor dos Exércitos, executará a destruição decretada sobre todo o país.

[[v23-10-24]]

^<<v23-10-24,24>>^ Por isso o Senhor, o Senhor dos Exércitos, diz: "Povo meu que vive em Sião, não tenham medo dos assírios, quando eles os espancam com uma vara e erguem contra vocês um bastão, como fez o Egito.

[[v23-10-25]]

^<<v23-10-25,25>>^ Muito em breve o meu furor passará, e a minha ira se voltará para a destruição deles".

[[v23-10-26]]

^<<v23-10-26,26>>^ O Senhor dos Exércitos os flagelará com um chicote, como fez quando feriu Midiã na rocha de Orebe; ele erguerá o seu cajado contra o mar, como fez no Egito.

[[v23-10-27]]

^<<v23-10-27,27>>^ Naquele dia o fardo deles será tirado dos seus ombros, e o jugo deles do seu pescoço; o jugo se quebrará porque vocês estarão muito gordos!

[[v23-10-28]]

^<<v23-10-28,28>>^ Eles entram em Aiate; passam por Migrom; guardam suprimentos em Micmás.

[[v23-10-29]]

^<<v23-10-29,29>>^ Atravessam o vale e dizem: "Passaremos a noite acampados em Geba". Ramá treme; Gibeá de Saul foge.

[[v23-10-30]]

^<<v23-10-30,30>>^ Clamem, ó habitantes de Galim! Escute, ó Laís! Pobre Anatote!

[[v23-10-31]]

^<<v23-10-31,31>>^ Madmena está em fuga; o povo de Gebim esconde-se.

[[v23-10-32]]

^<<v23-10-32,32>>^ Hoje eles vão parar em Nobe; sacudirão o punho para o monte da cidade de Sião, para a colina de Jerusalém.

[[v23-10-33]]

^<<v23-10-33,33>>^ Vejam! O Soberano, o Senhor dos Exércitos, cortará os galhos com grande força. As árvores altivas serão derrubadas, as altas serão lançadas por terra.

[[v23-10-34]]

^<<v23-10-34,34>>^ Com um machado ele ceifará a floresta; o Líbano cairá diante do Poderoso.

'''

xref:023-isaias/023-isaias-009.adoc#v23-9-0[&#60; Capítulo Anterior] | <<v23-10-0,Topo>> | xref:023-isaias/023-isaias-011.adoc#v23-11-0[Próximo Capítulo &#62;]