include::./index.adoc[]

[[v23-48-0]]
=== Isaías, 48
// nvi ?, NVI - Nova Versão Internacional

[[v23-48-1]]

^<<v23-48-1,1>>^ "Escute isto, ó comunidade de Jacó, vocês que são chamados pelo nome de Israel e vêm da linhagem de Judá, vocês que fazem juramentos pelo nome do Senhor e invocam o Deus de Israel, mas não em verdade ou retidão;

[[v23-48-2]]

^<<v23-48-2,2>>^ vocês que chamam a si mesmos cidadãos da cidade santa e dependem do Deus de Israel; o Senhor dos Exércitos é o seu nome:

[[v23-48-3]]

^<<v23-48-3,3>>^ Eu predisse há muito as coisas passadas, minha boca as anunciou, e eu as fiz conhecidas; então repentinamente agi, e elas aconteceram.

[[v23-48-4]]

^<<v23-48-4,4>>^ Pois eu sabia o quão obstinado você era; os tendões de seu pescoço eram ferro, a sua testa era bronze.

[[v23-48-5]]

^<<v23-48-5,5>>^ Por isso há muito lhe contei essas coisas; antes que acontecessem eu as anunciei a você para que você não pudesse dizer: ‘Meus ídolos as fizeram; minha imagem de madeira e meu deus de metal as determinaram’.

[[v23-48-6]]

^<<v23-48-6,6>>^ Você tem ouvido essas coisas; olhe para todas elas. Você não irá admiti-las? De agora em diante eu lhe contarei coisas novas, coisas ocultas, que você desconhece.

[[v23-48-7]]

^<<v23-48-7,7>>^ Elas foram criadas agora, e não há muito tempo; você nunca os conheceu antes. Por isso você não pode dizer: ‘Sim, eu as conhecia’.

[[v23-48-8]]

^<<v23-48-8,8>>^ Você não tinha conhecimento nem entendimento; desde a antigüidade, o seu ouvido tem se fechado. Sei quão traiçoeiro você é; desde o nascimento você foi chamado rebelde.

[[v23-48-9]]

^<<v23-48-9,9>>^ Por amor do meu próprio nome eu adio a minha ira; por amor de meu louvor eu a contive, para que você não fosse eliminado.

[[v23-48-10]]

^<<v23-48-10,10>>^ Veja, eu refinei você, embora não como prata; eu o provei na fornalha da aflição.

[[v23-48-11]]

^<<v23-48-11,11>>^ Por amor de mim mesmo, por amor de mim mesmo, eu faço isso. Como posso permitir que eu mesmo seja difamado? Não darei minha glória a um outro.

[[v23-48-12]]

^<<v23-48-12,12>>^ "Escute-me, ó Jacó, Israel, a quem chamei: Eu sou sempre o mesmo; eu sou o primeiro e eu sou o último.

[[v23-48-13]]

^<<v23-48-13,13>>^ Minha própria mão lançou os alicerces da terra, e a minha mão direita estendeu os céus; quando eu os convoco, todos juntos se põem de pé.

[[v23-48-14]]

^<<v23-48-14,14>>^ "Reúnam-se, todos vocês, e escutem: Qual dos ídolos predisse essas coisas? O amado do Senhor cumprirá seu propósito contra a Babilônia; seu braço será contra os babilônios.

[[v23-48-15]]

^<<v23-48-15,15>>^ Eu, eu mesmo, falei; sim, eu o chamei. Eu o trarei, e ele será bem sucedido em sua missão.

[[v23-48-16]]

^<<v23-48-16,16>>^ "Aproximem-se de mim e escutem isto: "Desde o primeiro anúncio não falei secretamente; na hora em que acontecer, estarei ali. " E agora o Soberano Senhor me enviou, com seu Espírito.

[[v23-48-17]]

^<<v23-48-17,17>>^ Assim diz o Senhor, o seu redentor, o Santo de Israel: "Eu sou o Senhor, o seu Deus, que lhe ensina o que é melhor para você, que o dirige no caminho em que você deve ir.

[[v23-48-18]]

^<<v23-48-18,18>>^ Se tão-somente você tivesse prestado atenção às minhas ordens, sua paz seria como um rio, sua retidão, como as ondas do mar.

[[v23-48-19]]

^<<v23-48-19,19>>^ Seus descendentes seriam como a areia, seus filhos, como seus inúmeros grãos; o nome deles jamais seria eliminado nem destruído de diante de mim".

[[v23-48-20]]

^<<v23-48-20,20>>^ Deixem a Babilônia, fujam do meio dos babilônios! Anunciem isso com gritos de alegria e o proclamem. Enviem-no aos confins da terra; digam: "O Senhor resgatou seu servo Jacó".

[[v23-48-21]]

^<<v23-48-21,21>>^ Não tiveram sede quando ele os conduziu através dos desertos; ele fez água fluir da rocha para eles; fendeu a rocha, e a água jorrou.

[[v23-48-22]]

^<<v23-48-22,22>>^ "Não há paz alguma para os ímpios", diz o Senhor.

'''

xref:023-isaias/023-isaias-047.adoc#v23-47-0[&#60; Capítulo Anterior] | <<v23-48-0,Topo>> | xref:023-isaias/023-isaias-049.adoc#v23-49-0[Próximo Capítulo &#62;]