include::./index.adoc[]

[[v23-65-0]]
=== Isaías, 65
// nvi ?, NVI - Nova Versão Internacional

[[v23-65-1]]

^<<v23-65-1,1>>^ "Fiz-me acessível aos que não perguntavam por mim; fui achado pelos que não me procuravam. A uma nação que não clamava pelo meu nome eu disse: Eis-me aqui, eis-me aqui.

[[v23-65-2]]

^<<v23-65-2,2>>^ O tempo todo estendi as mãos a um povo obstinado, que anda por um caminho que não é bom, seguindo as suas inclinações;

[[v23-65-3]]

^<<v23-65-3,3>>^ esse povo que sem cessar me provoca na minha frente, oferecendo sacrifícios em jardins e queimando incenso em altares de tijolos;

[[v23-65-4]]

^<<v23-65-4,4>>^ povo que vive nos túmulos e à noite se oculta nas covas, que come carne de porco, e em suas panelas tem sopa de carne impura;

[[v23-65-5]]

^<<v23-65-5,5>>^ esse povo diz: ‘Afasta-te! Não te aproximes de mim, pois eu sou santo! ’ Essa gente é fumaça no meu nariz! É fogo que queima o tempo todo!

[[v23-65-6]]

^<<v23-65-6,6>>^ "Vejam, porém! Escrito está diante de mim: Não ficarei calado, mas darei plena retribuição; eu lhes darei total retribuição,

[[v23-65-7]]

^<<v23-65-7,7>>^ tanto por seus pecados como pelos pecados dos seus antepassados", diz o Senhor. "Uma vez que eles queimaram incenso nos montes e me desafiaram nas colinas, eu os farei pagar pelos seus feitos anteriores. "

[[v23-65-8]]

^<<v23-65-8,8>>^ Assim diz o Senhor: "Quando ainda se acha suco num cacho de uvas, os homens dizem: ‘Não o destruam, pois ainda há algo bom’; assim farei em favor dos meus servos; não os destruirei totalmente.

[[v23-65-9]]

^<<v23-65-9,9>>^ Farei surgir descendentes de Jacó, e de Judá quem recebe por herança as minhas montanhas. Os meus escolhidos as herdarão, e ali viverão os meus servos.

[[v23-65-10]]

^<<v23-65-10,10>>^ Para o meu povo que me buscou, Sarom será um pasto para os rebanhos, e o vale de Acor um lugar de descanso para o gado.

[[v23-65-11]]

^<<v23-65-11,11>>^ "Mas vocês, que abandonam o Senhor e esquecem o meu santo monte, que põem a mesa para a deusa Sorte e enchem taças de vinho para o deus Destino,

[[v23-65-12]]

^<<v23-65-12,12>>^ eu os destinarei à espada, e todos vocês se dobrarão para a degola. Pois eu os chamei, e vocês nem responderam, falei, e não me deram ouvidos. Vocês fizeram o mal diante de mim e escolheram o que me desagrada".

[[v23-65-13]]

^<<v23-65-13,13>>^ Portanto, assim diz o Soberano Senhor: "Os meus servos comerão, e vocês passarão fome; os meus servos beberão, e vocês passarão sede; os meus servos se regozijarão, e vocês passarão vergonha;

[[v23-65-14]]

^<<v23-65-14,14>>^ os meus servos cantarão com alegria no coração, e vocês se lamentarão com angústia no coração e uivarão pelo quebrantamento de espírito.

[[v23-65-15]]

^<<v23-65-15,15>>^ Vocês deixarão seu nome como uma maldição para os meus escolhidos; o Soberano Senhor dará cabo de vocês, mas aos seus servos dará outro nome.

[[v23-65-16]]

^<<v23-65-16,16>>^ Quem pedir bênção para si na terra, que o faça pelo Deus da verdade; quem fizer juramento na terra, que o faça pelo Deus da verdade. Porquanto as aflições passadas serão esquecidas e estarão ocultas aos meus olhos.

[[v23-65-17]]

^<<v23-65-17,17>>^ "Pois vejam! Criarei novos céus e nova terra, e as coisas passadas não serão lembradas. Jamais virão à mente!

[[v23-65-18]]

^<<v23-65-18,18>>^ Alegrem-se, porém, e regozijem-se para sempre no que vou criar, porque vou criar Jerusalém para regozijo, e seu povo para alegria.

[[v23-65-19]]

^<<v23-65-19,19>>^ Por Jerusalém me regozijarei e em meu povo terei prazer; nunca mais se ouvirão nela voz de pranto e choro de tristeza.

[[v23-65-20]]

^<<v23-65-20,20>>^ "Nunca mais haverá nela uma criança que viva poucos dias, e um idoso que não complete os seus anos de idade; quem morrer aos cem anos ainda será jovem, e quem não chegar aos cem será maldito.

[[v23-65-21]]

^<<v23-65-21,21>>^ Construirão casas e nelas habitarão; plantarão vinhas e comerão do seu fruto.

[[v23-65-22]]

^<<v23-65-22,22>>^ Já não construirão casas para outros ocuparem, nem plantarão para outros comerem. Pois o meu povo terá vida longa como as árvores; os meus escolhidos esbanjarão o fruto do seu trabalho.

[[v23-65-23]]

^<<v23-65-23,23>>^ Não labutarão inutilmente, nem gerarão filhos para a infelicidade; pois serão um povo abençoado pelo Senhor, eles e os seus descendentes.

[[v23-65-24]]

^<<v23-65-24,24>>^ Antes de clamarem, eu responderei; ainda não estarão falando, e eu os ouvirei.

[[v23-65-25]]

^<<v23-65-25,25>>^ O lobo e o cordeiro comerão juntos, e o leão comerá feno, como o boi, mas o pó será a comida da serpente. Não farão nem mal nem destruição em todo o meu santo monte", diz o Senhor.

'''

xref:023-isaias/023-isaias-064.adoc#v23-64-0[&#60; Capítulo Anterior] | <<v23-65-0,Topo>> | xref:023-isaias/023-isaias-066.adoc#v23-66-0[Próximo Capítulo &#62;]