include::./index.adoc[]

[[v23-41-0]]
=== Isaías, 41
// nvi ?, NVI - Nova Versão Internacional

[[v23-41-1]]

^<<v23-41-1,1>>^ "Calem-se diante de mim, ó ilhas! Que as nações renovem as suas forças! Que elas se apresentem para se defender; vamos nos encontrar para decidir a questão.

[[v23-41-2]]

^<<v23-41-2,2>>^ "Quem despertou o que vem do oriente, e chamou-o em retidão ao seu serviço, entregando-lhe nações e subjugando reis diante dele? Com a espada ele os reduz a pó, com o arco os dispersa como palha.

[[v23-41-3]]

^<<v23-41-3,3>>^ Ele os persegue e avança em segurança, por um caminho que seus pés jamais percorreram.

[[v23-41-4]]

^<<v23-41-4,4>>^ Quem fez tudo isso? Quem chama as gerações à existência desde o princípio? Fui eu mesmo, o Senhor, o primeiro, que continuarei sendo, até mesmo com os últimos. "

[[v23-41-5]]

^<<v23-41-5,5>>^ As ilhas viram isso e temem; os confins da terra tremem. Eles se aproximam e vêm à frente;

[[v23-41-6]]

^<<v23-41-6,6>>^ cada um ajuda o outro e diz a seu irmão: "Seja forte! "

[[v23-41-7]]

^<<v23-41-7,7>>^ O artesão encoraja o ourives, e aquele que alisa com o martelo incentiva o que bate na bigorna. Ele diz acerca da soldagem: "Está boa. " E fixa o ídolo com prego para que não tombe.

[[v23-41-8]]

^<<v23-41-8,8>>^ "Você, porém, ó Israel, meu servo, Jacó, a quem escolhi, vocês, descendentes de Abraão, meu amigo,

[[v23-41-9]]

^<<v23-41-9,9>>^ eu os tirei dos confins da terra, de seus recantos mais distantes eu os chamei. Eu disse: "Você é meu servo"; eu o escolhi e não o rejeitei.

[[v23-41-10]]

^<<v23-41-10,10>>^ Por isso não tema, pois estou com você; não tenha medo, pois sou o seu Deus. Eu o fortalecerei e o ajudarei; Eu o segurarei com a minha mão direita vitoriosa.

[[v23-41-11]]

^<<v23-41-11,11>>^ "Todos os que o odeiam certamente serão humilhados e constrangidos; aqueles que se opõem a você serão como nada e perecerão.

[[v23-41-12]]

^<<v23-41-12,12>>^ Embora procure os seus inimigos, você não os encontrará. Os que guerreiam contra você serão reduzidos a nada.

[[v23-41-13]]

^<<v23-41-13,13>>^ Pois eu sou o Senhor, o seu Deus, que o segura pela mão direita e lhe diz: Não tema; eu o ajudarei.

[[v23-41-14]]

^<<v23-41-14,14>>^ Não tenha medo, ó verme Jacó, ó pequeno Israel, pois eu mesmo o ajudarei", declara o Senhor, seu Redentor, o Santo de Israel.

[[v23-41-15]]

^<<v23-41-15,15>>^ "Veja, eu o tornarei um debulhador, novo e cortante, com muitos dentes. Você debulhará os montes e os esmagará, e reduzirá as colinas a palha.

[[v23-41-16]]

^<<v23-41-16,16>>^ Você irá peneirá-los, o vento os levará, e uma ventania os espalhará. Mas você se regozijará no Senhor e no Santo de Israel se gloriará.

[[v23-41-17]]

^<<v23-41-17,17>>^ "O pobre e o necessitado buscam água, e não encontram! Suas línguas estão ressequidas de sede. Mas eu, o Senhor, lhes responderei; eu, o Deus de Israel, não os abandonarei.

[[v23-41-18]]

^<<v23-41-18,18>>^ Abrirei rios nas colinas estéreis, e fontes nos vales. Transformarei o deserto num lago, e o chão ressequido em mananciais.

[[v23-41-19]]

^<<v23-41-19,19>>^ Porei no deserto o cedro, a acácia, a murta e a oliveira. Colocarei juntos no ermo o cipreste, o abeto e o pinheiro,

[[v23-41-20]]

^<<v23-41-20,20>>^ para que o povo veja e saiba, e todos vejam e saibam, que a mão do Senhor fez isso, que o Santo de Israel o criou.

[[v23-41-21]]

^<<v23-41-21,21>>^ "Exponham a sua causa", diz o Senhor. "Apresentem as suas provas", diz o rei de Jacó.

[[v23-41-22]]

^<<v23-41-22,22>>^ "Tragam os seus ídolos para nos dizerem o que vai acontecer. Que eles nos contem como eram as coisas anteriores, para que as consideremos e saibamos o seu resultado final; ou que nos declarem as coisas vindouras,

[[v23-41-23]]

^<<v23-41-23,23>>^ revelem-nos o futuro, para que saibamos que vocês são deuses. Façam alguma coisa, boa ou má, para que nos rendamos, cheios de temor.

[[v23-41-24]]

^<<v23-41-24,24>>^ Mas vejam só! Vocês não são nada, e as suas obras são totalmente nulas; detestável é aquele que os escolhe!

[[v23-41-25]]

^<<v23-41-25,25>>^ "Despertei um homem, e do norte ele vem; desde o nascente proclamará o meu nome. Pisa em governantes como em argamassa, como o oleiro amassa o barro.

[[v23-41-26]]

^<<v23-41-26,26>>^ Quem falou disso desde o princípio, para que o soubéssemos, ou antecipadamente, para que pudéssemos dizer: "Ele estava certo"? Ninguém o revelou, ninguém o fez ouvir, ninguém ouviu palavra alguma de vocês.

[[v23-41-27]]

^<<v23-41-27,27>>^ Desde o princípio eu disse a Sião: "Veja, estas coisas acontecendo! " A Jerusalém eu darei um mensageiro de boas novas.

[[v23-41-28]]

^<<v23-41-28,28>>^ Olho, e não há ninguém entre eles, nenhum conselheiro que dê resposta quando pergunto.

[[v23-41-29]]

^<<v23-41-29,29>>^ Veja, são todos falsos! Seus feitos são nulos; suas imagens fundidas não passam de um sopro e nulidade!

'''

xref:023-isaias/023-isaias-040.adoc#v23-40-0[&#60; Capítulo Anterior] | <<v23-41-0,Topo>> | xref:023-isaias/023-isaias-042.adoc#v23-42-0[Próximo Capítulo &#62;]