include::./index.adoc[]

[[v23-28-0]]
=== Isaías, 28
// nvi ?, NVI - Nova Versão Internacional

[[v23-28-1]]

^<<v23-28-1,1>>^ Ai daquela coroa, orgulho dos bêbados de Efraim, e de sua magnífica beleza, situada nos altos de um vale fértil e que agora é como uma flor murcha, Ai dos que são dominados pelo vinho!

[[v23-28-2]]

^<<v23-28-2,2>>^ Vejam! O Senhor envia alguém que é poderoso e forte. Como chuva de granizo e vento destruidor, como violento aguaceiro e tromba d’água inundante, ele a lançará com força ao chão.

[[v23-28-3]]

^<<v23-28-3,3>>^ A coroa orgulhosa dos bêbados de Efraim será pisoteada.

[[v23-28-4]]

^<<v23-28-4,4>>^ Sua magnífica beleza, localizada na cabeça de um vale fértil, é agora uma flor que murcha. Ela será como figo maduro antes da colheita, quem o vê, logo o apanha e o come.

[[v23-28-5]]

^<<v23-28-5,5>>^ Naquele dia o Senhor dos Exércitos será uma coroa gloriosa, um belo diadema para o remanescente do seu povo.

[[v23-28-6]]

^<<v23-28-6,6>>^ Ele será um espírito de justiça para aquele que se assenta para julgar, e força para os que fazem recuar das portas a guerra.

[[v23-28-7]]

^<<v23-28-7,7>>^ E estes também cambaleiam pelo efeito do vinho, e não ficam de pé por causa da bebida fermentada: Os sacerdotes e os profetas cambaleiam por causa da bebida fermentada e estão desorientados devido ao vinho; eles não conseguem ficar de pé por causa da bebida fermentada, confundem-se quando têm visões, tropeçam quando devem dar um veredicto.

[[v23-28-8]]

^<<v23-28-8,8>>^ Todas as mesas estão cobertas de vômito e não há um só lugar limpo.

[[v23-28-9]]

^<<v23-28-9,9>>^ "Quem é que ele está tentando ensinar? A quem está explicando a sua mensagem? A crianças desmamadas e a bebês recém-tirados do seio materno?

[[v23-28-10]]

^<<v23-28-10,10>>^ Pois o que se diz é: ‘Ordem sobre ordem, ordem sobre ordem, regra e mais regra, regra e mais regra; um pouco aqui, um pouco ali’. "

[[v23-28-11]]

^<<v23-28-11,11>>^ Pois bem, com lábios trôpegos e língua estranha Deus falará a este povo,

[[v23-28-12]]

^<<v23-28-12,12>>^ ao qual dissera: "Este é o lugar de descanso. Deixem descansar o exausto. Este é o lugar de repouso! " Mas eles não quiseram ouvir.

[[v23-28-13]]

^<<v23-28-13,13>>^ Por isso o Senhor lhes dirá: "Ordem sobre ordem, ordem sobre ordem, regra e mais regra, regra e mais regra; um pouco aqui, um pouco ali", para que saiam, caiam de costas, firam-se, fiquem presos no laço e sejam capturados.

[[v23-28-14]]

^<<v23-28-14,14>>^ Portanto, ouçam a palavra do Senhor, zombadores, vocês, que dominam este povo em Jerusalém.

[[v23-28-15]]

^<<v23-28-15,15>>^ Vocês se vangloriam, dizendo: "Fizemos um pacto com a morte, com a sepultura fizemos um acordo. Quando vier a calamidade destruidora, não nos atingirá, pois da mentira fizemos o nosso refúgio e na falsidade temos o nosso esconderijo".

[[v23-28-16]]

^<<v23-28-16,16>>^ Por isso diz o Soberano Senhor: "Eis que ponho em Sião uma pedra, uma pedra já experimentada, uma preciosa pedra angular para alicerce seguro; aquele que confia, jamais será abalado.

[[v23-28-17]]

^<<v23-28-17,17>>^ Farei do juízo a linha de medir e da justiça o fio de prumo; o granizo varrerá o seu falso refúgio, e as águas inundarão o seu abrigo.

[[v23-28-18]]

^<<v23-28-18,18>>^ Seu pacto com a morte será anulado; seu acordo com a sepultura não subsistirá. Quando vier a calamidade destruidora, vocês serão arrastados por ela.

[[v23-28-19]]

^<<v23-28-19,19>>^ Todas as vezes que vier, os arrastará; passará manhã após manhã, de dia e de noite". A compreensão desta mensagem trará pavor total.

[[v23-28-20]]

^<<v23-28-20,20>>^ A cama é curta demais para alguém deitar-se, e o cobertor é estreito demais para cobrir-se.

[[v23-28-21]]

^<<v23-28-21,21>>^ O Senhor se levantará como fez no monte Perazim, mostrará sua ira como no vale de Gibeom, para realizar sua obra, obra muito estranha, e cumprir sua tarefa, tarefa misteriosa.

[[v23-28-22]]

^<<v23-28-22,22>>^ Agora, parem com a zombaria; caso contrário, as suas correntes ficarão mais pesadas; o Senhor, o Senhor dos Exércitos falou-me da destruição decretada contra o território inteiro.

[[v23-28-23]]

^<<v23-28-23,23>>^ Ouçam, escutem a minha voz; prestem atenção, ouçam o que eu digo.

[[v23-28-24]]

^<<v23-28-24,24>>^ Quando o agricultor ara a terra para o plantio, só faz isso o tempo todo? Só fica abrindo sulcos e gradeando o solo?

[[v23-28-25]]

^<<v23-28-25,25>>^ Depois de nivelado o solo, ele não semeia o endro e não espalha as sementes do cominho? Não planta o trigo no lugar certo, a cevada no terreno próprio e o trigo duro nas bordas?

[[v23-28-26]]

^<<v23-28-26,26>>^ O seu Deus o instrui e lhe ensina o caminho.

[[v23-28-27]]

^<<v23-28-27,27>>^ Não se debulha o endro com trilhadeira, e sobre o cominho não se faz passar roda de carro; tira-se o endro com vara, e o cominho com um pedaço de pau.

[[v23-28-28]]

^<<v23-28-28,28>>^ É preciso moer o cereal para fazer pão; por isso ninguém o fica trilhando para sempre. Fazem passar as rodas da trilhadeira sobre o trigo, mas os seus cavalos não o trituram.

[[v23-28-29]]

^<<v23-28-29,29>>^ Isso tudo vem da parte do Senhor dos Exércitos, maravilhoso em conselhos e magnífico em sabedoria.

'''

xref:023-isaias/023-isaias-027.adoc#v23-27-0[&#60; Capítulo Anterior] | <<v23-28-0,Topo>> | xref:023-isaias/023-isaias-029.adoc#v23-29-0[Próximo Capítulo &#62;]