include::./index.adoc[]

[[v23-42-0]]
=== Isaías, 42
// nvi ?, NVI - Nova Versão Internacional

[[v23-42-1]]

^<<v23-42-1,1>>^ "Eis o meu servo, a quem sustento, o meu escolhido, em quem tenho prazer. Porei nele o meu Espírito, e ele trará justiça às nações.

[[v23-42-2]]

^<<v23-42-2,2>>^ Não gritará nem clamará, nem erguerá a voz nas ruas.

[[v23-42-3]]

^<<v23-42-3,3>>^ Não quebrará o caniço rachado, e não apagará o pavio fumegante. Com fidelidade fará justiça;

[[v23-42-4]]

^<<v23-42-4,4>>^ não mostrará fraqueza nem se deixará ferir, até que estabeleça a justiça sobre a terra. Em sua lei as ilhas porão sua esperança. "

[[v23-42-5]]

^<<v23-42-5,5>>^ É o que diz Deus, o Senhor, aquele que criou o céu e o estendeu, que espalhou a terra e tudo o que dela procede, que dá fôlego aos seus moradores e vida aos que andam nela:

[[v23-42-6]]

^<<v23-42-6,6>>^ "Eu, o Senhor, o chamei em retidão; segurarei firme a sua mão. Eu o guardarei e farei de você um mediador para o povo e uma luz para os gentios,

[[v23-42-7]]

^<<v23-42-7,7>>^ para abrir os olhos aos cegos, para libertar da prisão os cativos e para livrar do calabouço os que habitam na escuridão.

[[v23-42-8]]

^<<v23-42-8,8>>^ "Eu sou o Senhor; esse é o meu nome! Não darei a outro a minha glória nem a imagens o meu louvor.

[[v23-42-9]]

^<<v23-42-9,9>>^ Vejam! As profecias antigas aconteceram, e novas eu anuncio; antes de surgirem, eu as declaro a vocês".

[[v23-42-10]]

^<<v23-42-10,10>>^ Cantem ao Senhor um novo cântico, seu louvor desde os confins da terra, vocês, que navegam no mar, e tudo o que nele existe, vocês, ilhas, e todos os seus habitantes.

[[v23-42-11]]

^<<v23-42-11,11>>^ Que o deserto e as suas cidades ergam a sua voz; regozijem-se os povoados habitados por Quedar. Cante de alegria o povo de Selá, gritem pelos altos dos montes.

[[v23-42-12]]

^<<v23-42-12,12>>^ Dêem glória ao Senhor e nas ilhas proclamem seu louvor.

[[v23-42-13]]

^<<v23-42-13,13>>^ O Senhor sairá como homem poderoso, como guerreiro despertará o seu zelo; com forte brado e o grito de guerra triunfará sobre os seus inimigos.

[[v23-42-14]]

^<<v23-42-14,14>>^ "Fiquei muito tempo em silêncio, e me contive, calado. Mas agora, como mulher em trabalho de parto, eu grito, gemo e respiro ofegante.

[[v23-42-15]]

^<<v23-42-15,15>>^ Arrasarei os montes e as colinas e secarei toda sua vegetação; tornarei rios em ilhas e secarei os açudes.

[[v23-42-16]]

^<<v23-42-16,16>>^ Conduzirei os cegos por caminhos que eles não conheceram, por veredas desconhecidas eu os guiarei; transformarei as trevas em luz diante deles e tornarei retos os lugares acidentados. Essas são as coisas que farei; não os abandonarei.

[[v23-42-17]]

^<<v23-42-17,17>>^ Mas retrocederão em vergonha total aqueles que confiam em imagens esculpidas, que dizem aos ídolos fundidos: ‘Vocês são nossos deuses’. "

[[v23-42-18]]

^<<v23-42-18,18>>^ "Ouçam, surdos; olhem, cegos, e vejam!

[[v23-42-19]]

^<<v23-42-19,19>>^ Quem é cego senão o meu servo e surdo senão o mensageiro que enviei? Quem é cego como aquele Que é consagrado a mim, cego como o servo do Senhor?

[[v23-42-20]]

^<<v23-42-20,20>>^ Você viu muitas coisas, mas não deu qualquer atenção; seus ouvidos estão abertos, mas você não ouve nada. "

[[v23-42-21]]

^<<v23-42-21,21>>^ Foi do agrado do Senhor, por amor de sua retidão, tornar grande e gloriosa a sua lei.

[[v23-42-22]]

^<<v23-42-22,22>>^ Mas este é um povo saqueado e roubado; foram apanhados em cavernas e escondidos em prisões. Eles se tornaram presa, sem ninguém para resgatá-los; eles se tornaram despojo, sem que ninguém reclamasse: "Devolvam".

[[v23-42-23]]

^<<v23-42-23,23>>^ Qual de vocês escutará isso ou prestará muita atenção no tempo vindouro?

[[v23-42-24]]

^<<v23-42-24,24>>^ Quem entregou Jacó para tornar-se despojo, e Israel aos saqueadores? Não foi o Senhor, contra quem temos pecado? Pois eles não quiseram seguir os seus caminhos; não obedeceram à sua lei.

[[v23-42-25]]

^<<v23-42-25,25>>^ De modo que ele lançou sobre eles o seu furor, a violência da guerra. Ele os envolveu em chamas, contudo nada aprenderam; ela os consumiu, e ainda assim, não levaram isso a sério.

'''

xref:023-isaias/023-isaias-041.adoc#v23-41-0[&#60; Capítulo Anterior] | <<v23-42-0,Topo>> | xref:023-isaias/023-isaias-043.adoc#v23-43-0[Próximo Capítulo &#62;]