include::./index.adoc[]

[[v23-12-0]]
=== Isaías, 12
// nvi ?, NVI - Nova Versão Internacional

[[v23-12-1]]

^<<v23-12-1,1>>^ Naquele dia você dirá: "Eu te louvarei, Senhor! Pois estavas irado contra mim, mas a tua ira desviou-se, e tu me consolaste.

[[v23-12-2]]

^<<v23-12-2,2>>^ Deus é a minha salvação; terei confiança e não temerei. O Senhor, sim, o Senhor é a minha força e o meu cântico; ele é a minha salvação! "

[[v23-12-3]]

^<<v23-12-3,3>>^ Com alegria vocês tirarão água das fontes da salvação.

[[v23-12-4]]

^<<v23-12-4,4>>^ Naquele dia vocês dirão: "Louvem ao Senhor, invoquem o seu nome; anunciem entre as nações os seus feitos, e façam-nas saber que o seu nome é exaltado.

[[v23-12-5]]

^<<v23-12-5,5>>^ Cantem louvores ao Senhor, pois ele tem feito coisas gloriosas, sejam elas conhecidas em todo o mundo.

[[v23-12-6]]

^<<v23-12-6,6>>^ Gritem bem alto e cantem de alegria, habitantes de Sião, pois grande é o Santo de Israel no meio de vocês".

'''

xref:023-isaias/023-isaias-011.adoc#v23-11-0[&#60; Capítulo Anterior] | <<v23-12-0,Topo>> | xref:023-isaias/023-isaias-013.adoc#v23-13-0[Próximo Capítulo &#62;]