include::./index.adoc[]

[[v23-55-0]]
=== Isaías, 55
// nvi ?, NVI - Nova Versão Internacional

[[v23-55-1]]

^<<v23-55-1,1>>^ "Venham, todos vocês que estão com sede, venham às águas; e, vocês que não possuem dinheiro algum, venham, comprem e comam! Venham, comprem vinho e leite sem dinheiro e sem custo.

[[v23-55-2]]

^<<v23-55-2,2>>^ Por que gastar dinheiro naquilo que não é pão e o seu trabalho árduo naquilo que não satisfaz? Escutem, escutem-me, e comam o que é bom, e a alma de vocês se deliciará na mais fina refeição.

[[v23-55-3]]

^<<v23-55-3,3>>^ Dêem ouvidos e venham a mim; ouçam-me, para que sua alma viva. Farei uma aliança eterna com vocês, minha fidelidade prometida a Davi.

[[v23-55-4]]

^<<v23-55-4,4>>^ Vejam, eu o fiz uma testemunha aos povos, um líder e governante dos povos.

[[v23-55-5]]

^<<v23-55-5,5>>^ Com certeza você convocará nações que você não conhece, e nações que não o conhecem se apressarão até você, por causa do Senhor, o seu Deus, o Santo de Israel, pois ele lhe concedeu esplendor. "

[[v23-55-6]]

^<<v23-55-6,6>>^ Busquem o Senhor enquanto se pode achá-lo; clamem por ele enquanto está perto.

[[v23-55-7]]

^<<v23-55-7,7>>^ Que o ímpio abandone seu caminho, e o homem mau, os seus pensamentos. Volte-se ele para o Senhor, que terá misericórdia dele; volte-se para o nosso Deus, pois ele perdoará de bom grado.

[[v23-55-8]]

^<<v23-55-8,8>>^ "Pois os meus pensamentos não são os pensamentos de vocês, nem os seus caminhos são os meus caminhos", declara o Senhor.

[[v23-55-9]]

^<<v23-55-9,9>>^ "Assim como os céus são mais altos do que a terra, também os meus caminhos são mais altos do que os seus caminhos e os meus pensamentos mais altos do que os seus pensamentos.

[[v23-55-10]]

^<<v23-55-10,10>>^ Assim como a chuva e a neve descem dos céus e não voltam para ele sem regarem a terra e fazerem-na brotar e florescer, para ela produzir semente para o semeador e pão para o que come,

[[v23-55-11]]

^<<v23-55-11,11>>^ assim também ocorre com a palavra que sai da minha boca: Ela não voltará para mim vazia, mas fará o que desejo e atingirá o propósito para o qual a enviei.

[[v23-55-12]]

^<<v23-55-12,12>>^ Vocês sairão em júbilo e serão conduzidos em paz; os montes e colinas irromperão em canto diante de vocês, e todas as árvores do campo baterão palmas.

[[v23-55-13]]

^<<v23-55-13,13>>^ No lugar do espinheiro crescerá o pinheiro, e em vez de roseiras bravas crescerá a murta. Isso resultará em renome para o Senhor, para sinal eterno, que não será destruído. "

'''

xref:023-isaias/023-isaias-054.adoc#v23-54-0[&#60; Capítulo Anterior] | <<v23-55-0,Topo>> | xref:023-isaias/023-isaias-056.adoc#v23-56-0[Próximo Capítulo &#62;]