include::./index.adoc[]

[[v23-11-0]]
=== Isaías, 11
// nvi ?, NVI - Nova Versão Internacional

[[v23-11-1]]

^<<v23-11-1,1>>^ Um ramo surgirá do tronco de Jessé, e das suas raízes brotará um renovo.

[[v23-11-2]]

^<<v23-11-2,2>>^ O Espírito do Senhor repousará sobre ele, o Espírito que dá sabedoria e entendimento, o Espírito que traz conselho e poder, o Espírito que dá conhecimento e temor do Senhor.

[[v23-11-3]]

^<<v23-11-3,3>>^ E ele se inspirará no temor do Senhor. Não julgará pela aparência, nem decidirá com base no que ouviu;

[[v23-11-4]]

^<<v23-11-4,4>>^ mas com retidão julgará os necessitados, com justiça tomará decisões em favor dos pobres. Com suas palavras, como se fossem um cajado, ferirá a terra; com o sopro de sua boca matará os ímpios.

[[v23-11-5]]

^<<v23-11-5,5>>^ A retidão será a faixa de seu peito, e a fidelidade o seu cinturão.

[[v23-11-6]]

^<<v23-11-6,6>>^ O lobo viverá com o cordeiro, o leopardo se deitará com o bode, o bezerro, o leão e o novilho gordo pastarão juntos; e uma criança os guiará.

[[v23-11-7]]

^<<v23-11-7,7>>^ A vaca se alimentará com o urso, seus filhotes se deitarão juntos, e o leão comerá palha como o boi.

[[v23-11-8]]

^<<v23-11-8,8>>^ A criancinha brincará perto do esconderijo da cobra, a criança colocará a mão no ninho da víbora.

[[v23-11-9]]

^<<v23-11-9,9>>^ Ninguém fará nenhum mal, nem destruirá coisa alguma em todo o meu santo monte, pois a terra se encherá do conhecimento do Senhor como as águas cobrem o mar.

[[v23-11-10]]

^<<v23-11-10,10>>^ Naquele dia as nações buscarão a Raiz de Jessé, que será como uma bandeira para os povos, e o seu lugar de descanso será glorioso.

[[v23-11-11]]

^<<v23-11-11,11>>^ Naquele dia o Senhor estenderá o braço pela segunda vez para reivindicar o remanescente do seu povo que for deixado na Assíria, no Egito, em Patros, na Etiópia, em Elão, em Sinear, em Hamate e nas ilhas do mar.

[[v23-11-12]]

^<<v23-11-12,12>>^ Ele erguerá uma bandeira para as nações a fim de reunir os exilados de Israel; ajuntará o povo disperso de Judá desde os quatro cantos da terra.

[[v23-11-13]]

^<<v23-11-13,13>>^ O ciúme de Efraim desaparecerá, e a hostilidade de Judá será eliminada; Efraim não terá ciúme de Judá, nem Judá será hostil a Efraim.

[[v23-11-14]]

^<<v23-11-14,14>>^ Eles se infiltrarão pelas encostas da Filístia, a oeste; juntos saquearão o povo do leste. Porão as mãos sobre Edom e Moabe, e os amonitas lhes estarão sujeitos.

[[v23-11-15]]

^<<v23-11-15,15>>^ O Senhor fará secar o golfo do mar do Egito; com um forte vento varrerá com a mão o Eufrates, e o dividirá em sete riachos, para que se possa atravessá-lo de sandálias.

[[v23-11-16]]

^<<v23-11-16,16>>^ Haverá uma estrada para o remanescente do seu povo que for deixado na Assíria, como houve para Israel quando saiu do Egito.

'''

xref:023-isaias/023-isaias-010.adoc#v23-10-0[&#60; Capítulo Anterior] | <<v23-11-0,Topo>> | xref:023-isaias/023-isaias-012.adoc#v23-12-0[Próximo Capítulo &#62;]