include::./index.adoc[]

[[v23-3-0]]
=== Isaías, 3
// nvi ?, NVI - Nova Versão Internacional

[[v23-3-1]]

^<<v23-3-1,1>>^ Vejam! O Soberano, o Senhor dos Exércitos, logo irá retirar de Jerusalém e de Judá todo o seu sustento, tanto o suprimento de comida como o suprimento de água,

[[v23-3-2]]

^<<v23-3-2,2>>^ e também o herói e o guerreiro, o juiz e o profeta, o adivinho e a autoridade,

[[v23-3-3]]

^<<v23-3-3,3>>^ o capitão e o nobre, o conselheiro, o conhecedor de magia e o perito em maldições.

[[v23-3-4]]

^<<v23-3-4,4>>^ Porei jovens no governo; irresponsáveis dominarão.

[[v23-3-5]]

^<<v23-3-5,5>>^ O povo oprimirá a si mesmo: homem contra homem, cada um contra o seu próximo. O jovem se levantará contra o idoso, o desprezível contra o nobre.

[[v23-3-6]]

^<<v23-3-6,6>>^ Um homem agarrará seu irmão; um da família de seu pai, e lhe dirá: "Você pelo menos tem um manto, seja o nosso governante; assuma o poder sobre este monte de ruínas! "

[[v23-3-7]]

^<<v23-3-7,7>>^ Mas naquele dia ele exclamará: "Não tenho remédios, não há comida nem roupa em minha casa; não me nomeiem governante do povo".

[[v23-3-8]]

^<<v23-3-8,8>>^ Jerusalém está em ruínas, e o povo de Judá está caído; suas palavras e suas ações são contra o Senhor, desafiando a sua presença gloriosa.

[[v23-3-9]]

^<<v23-3-9,9>>^ O jeito que olham testifica contra eles; mostram seu pecado como Sodoma, sem nada esconder. Ai deles! Pois trouxeram desgraça sobre si mesmos.

[[v23-3-10]]

^<<v23-3-10,10>>^ Digam aos justos que tudo lhes irá bem, pois comerão do fruto de suas ações.

[[v23-3-11]]

^<<v23-3-11,11>>^ Mas, ai dos ímpios! Pois tudo lhes irá mal! Terão a retribuição pelo que fizeram as suas mãos.

[[v23-3-12]]

^<<v23-3-12,12>>^ Meu povo é oprimido por uma criança; mulheres dominam sobre ele. Meu povo, os seus guias o enganam, e o desviam do caminho.

[[v23-3-13]]

^<<v23-3-13,13>>^ O Senhor toma o seu lugar no tribunal; levanta-se para julgar os povos.

[[v23-3-14]]

^<<v23-3-14,14>>^ O Senhor entra em juízo contra as autoridades e contra os líderes do seu povo. "Vocês arruinaram a vinha, e o que foi roubado dos necessitados está nas suas casas.

[[v23-3-15]]

^<<v23-3-15,15>>^ Que pretendem vocês, ao esmagarem o meu povo, e ao moerem o rosto dos necessitados? " Quem pergunta é o Senhor, o Senhor dos Exércitos.

[[v23-3-16]]

^<<v23-3-16,16>>^ O Senhor diz: "Por causa da arrogância das mulheres de Sião, que caminham de cabeça erguida, flertando com os olhos, desfilando com passos curtos, com enfeites tinindo em seus calcanhares,

[[v23-3-17]]

^<<v23-3-17,17>>^ o Senhor rapará a cabeça das mulheres de Sião; o Senhor porá a descoberto as suas vergonhas".

[[v23-3-18]]

^<<v23-3-18,18>>^ Naquele dia o Senhor arrancará os enfeites delas: as pulseiras, as testeiras e os colares;

[[v23-3-19]]

^<<v23-3-19,19>>^ os pendentes, os braceletes e os véus,

[[v23-3-20]]

^<<v23-3-20,20>>^ os enfeites de cabeça, as correntinhas de tornozelo, os cintos, os talismãs e os amuletos;

[[v23-3-21]]

^<<v23-3-21,21>>^ os anéis e os enfeites para o nariz;

[[v23-3-22]]

^<<v23-3-22,22>>^ as roupas caras, as capas, as mantilhas, e as bolsas;

[[v23-3-23]]

^<<v23-3-23,23>>^ os espelhos, as roupas de linho, as tiaras e os xales.

[[v23-3-24]]

^<<v23-3-24,24>>^ Em vez de perfume haverá mau cheiro, em vez de cintos, corda, em vez de belos penteados, calvície, em vez de roupas finas, vestes de lamento, em vez de beleza, cicatrizes.

[[v23-3-25]]

^<<v23-3-25,25>>^ Seus homens cairão ao fio da espada; seus guerreiros morrerão no combate.

[[v23-3-26]]

^<<v23-3-26,26>>^ As portas de Sião lamentarão e prantearão por causa disso; e sem nada, ela se assentará no chão.

'''

xref:023-isaias/023-isaias-002.adoc#v23-2-0[&#60; Capítulo Anterior] | <<v23-3-0,Topo>> | xref:023-isaias/023-isaias-004.adoc#v23-4-0[Próximo Capítulo &#62;]