include::./index.adoc[]

[[v23-50-0]]
=== Isaías, 50
// nvi ?, NVI - Nova Versão Internacional

[[v23-50-1]]

^<<v23-50-1,1>>^ Assim diz o Senhor: "Onde está a certidão de divórcio de sua mãe com a qual eu a mandei embora? A qual de meus credores eu vendi vocês? Por causa de seus pecados vocês foram vendidos; por causa das transgressões de vocês sua mãe foi mandada embora.

[[v23-50-2]]

^<<v23-50-2,2>>^ Quando eu vim, por que não encontrei ninguém? Quando eu chamei, por que ninguém respondeu? Será que meu braço era curto demais para resgatá-los? Será que me falta a força para redimi-los? Com uma simples repreensão eu seco o mar, transformo rios em deserto; seus peixes apodrecem por falta de água e morrem de sede.

[[v23-50-3]]

^<<v23-50-3,3>>^ Visto os céus com trevas e faço da veste de lamento a sua coberta".

[[v23-50-4]]

^<<v23-50-4,4>>^ O Soberano Senhor deu-me uma língua instruída, para conhecer a palavra que sustém o exausto. Ele me acorda manhã após manhã, desperta meu ouvido para escutar como alguém que é ensinado.

[[v23-50-5]]

^<<v23-50-5,5>>^ O Soberano Senhor abriu os meus ouvidos, e eu não tenho sido rebelde; eu não me afastei.

[[v23-50-6]]

^<<v23-50-6,6>>^ Ofereci minhas costas para aqueles que me batiam, meu rosto para aqueles que arrancavam minha barba; não escondi a face da zombaria e da cuspida.

[[v23-50-7]]

^<<v23-50-7,7>>^ Porque o Senhor Soberano me ajuda, não serei constrangido. Por isso eu me opus firmemente como pederneira, e sei que não serei envergonhado.

[[v23-50-8]]

^<<v23-50-8,8>>^ Aquele que defende o meu nome está perto. Quem então trará acusações contra mim? Encaremo-nos um ao outro! Quem é meu acusador? Que ele me enfrente!

[[v23-50-9]]

^<<v23-50-9,9>>^ É o Soberano Senhor que me ajuda. Quem irá me condenar? Todos eles se desgastam como uma roupa; as traças os consumirão.

[[v23-50-10]]

^<<v23-50-10,10>>^ Quem entre vocês teme o Senhor e obedece à palavra de seu servo? Que aquele que anda no escuro, que não tem luz alguma, confie no nome do Senhor e dependa de seu Deus.

[[v23-50-11]]

^<<v23-50-11,11>>^ Mas agora, todos vocês que acendem fogo e fornecem a si mesmos tochas acesas, vão, andem na luz de seus fogos e das tochas que vocês acenderam. Isso é o que receberão da minha mão: vocês deitarão atormentados.

'''

xref:023-isaias/023-isaias-049.adoc#v23-49-0[&#60; Capítulo Anterior] | <<v23-50-0,Topo>> | xref:023-isaias/023-isaias-051.adoc#v23-51-0[Próximo Capítulo &#62;]