include::./index.adoc[]

[[v23-2-0]]
=== Isaías, 2
// nvi ?, NVI - Nova Versão Internacional

[[v23-2-1]]

^<<v23-2-1,1>>^ Foi isto que Isaías, filho de Amoz, viu a respeito de Judá e de Jerusalém:

[[v23-2-2]]

^<<v23-2-2,2>>^ Nos últimos dias o monte do templo do Senhor será estabelecido como o principal; será elevado acima das colinas, e todas as nações correrão para ele.

[[v23-2-3]]

^<<v23-2-3,3>>^ Virão muitos povos e dirão: "Venham, subamos ao monte do Senhor, ao templo do Deus de Jacó, para que ele nos ensine os seus caminhos, e assim andemos em suas veredas". Pois, a lei sairá de Sião, de Jerusalém virá a palavra do Senhor.

[[v23-2-4]]

^<<v23-2-4,4>>^ Ele julgará entre as nações e resolverá contendas de muitos povos. Eles farão de suas espadas arados, e de suas lanças foices. Uma nação não mais pegará em armas para atacar outra nação, elas jamais tornarão a preparar-se para a guerra.

[[v23-2-5]]

^<<v23-2-5,5>>^ Venha, ó descendência de Jacó, andemos na luz do Senhor!

[[v23-2-6]]

^<<v23-2-6,6>>^ Certamente abandonaste o teu povo, os descendentes de Jacó, porque eles se encheram de superstições dos povos do leste, praticam adivinhações como os filisteus e fazem acordos com pagãos.

[[v23-2-7]]

^<<v23-2-7,7>>^ Sua terra está cheia de prata e ouro; seus tesouros são incontáveis. Sua terra está cheia de cavalos; seus carros não têm fim.

[[v23-2-8]]

^<<v23-2-8,8>>^ Sua terra está cheia de ídolos. Eles se inclinam diante da obra das suas mãos, diante do que os seus dedos fizeram.

[[v23-2-9]]

^<<v23-2-9,9>>^ Por isso a humanidade será abatida e o homem será humilhado; não os perdoes!

[[v23-2-10]]

^<<v23-2-10,10>>^ Entre no meio das rochas, esconda-se no pó, por causa do terror que vem do Senhor e do esplendor da sua majestade!

[[v23-2-11]]

^<<v23-2-11,11>>^ O olhos do arrogante serão humilhados e o orgulho dos homens será abatido; somente o Senhor será exaltado naquele dia.

[[v23-2-12]]

^<<v23-2-12,12>>^ O Senhor dos Exércitos tem um dia reservado para todos os orgulhosos e altivos, para tudo o que é exaltado para que eles sejam humilhados;

[[v23-2-13]]

^<<v23-2-13,13>>^ para todos os cedros do Líbano, altos e altivos, e todos os carvalhos de Basã,

[[v23-2-14]]

^<<v23-2-14,14>>^ para todos os montes elevados e todas as colinas altas,

[[v23-2-15]]

^<<v23-2-15,15>>^ para toda torre imponente e todo muro fortificado,

[[v23-2-16]]

^<<v23-2-16,16>>^ para todo navio mercante e todo barco de luxo.

[[v23-2-17]]

^<<v23-2-17,17>>^ A arrogância dos homens será abatida, e o seu orgulho será humilhado. Somente o Senhor será exaltado naquele dia,

[[v23-2-18]]

^<<v23-2-18,18>>^ e os ídolos desaparecerão por completo.

[[v23-2-19]]

^<<v23-2-19,19>>^ Os homens fugirão para as cavernas das rochas e para os buracos da terra, por causa do terror que vem do Senhor e do esplendor da sua majestade, quando ele se levantar para sacudir a terra.

[[v23-2-20]]

^<<v23-2-20,20>>^ Naquele dia os homens atirarão aos ratos e aos morcegos os ídolos de prata e os ídolos de ouro, que fizeram para adorar.

[[v23-2-21]]

^<<v23-2-21,21>>^ Fugirão para as cavernas das rochas e para as brechas dos penhascos, por causa do terror que vem do Senhor e do esplendor da sua majestade, quando ele se levantar para sacudir a terra.

[[v23-2-22]]

^<<v23-2-22,22>>^ Parem de confiar no homem, cuja vida não passa de um sopro em suas narinas. Que valor ele tem?

'''

xref:023-isaias/023-isaias-001.adoc#v23-1-0[&#60; Capítulo Anterior] | <<v23-2-0,Topo>> | xref:023-isaias/023-isaias-003.adoc#v23-3-0[Próximo Capítulo &#62;]