include::./index.adoc[]

[[v23-19-0]]
=== Isaías, 19
// nvi ?, NVI - Nova Versão Internacional

[[v23-19-1]]

^<<v23-19-1,1>>^ Advertência contra o Egito: Vejam! O Senhor cavalga numa nuvem veloz que vai para o Egito. Os ídolos do Egito tremem diante dele, e os corações dos egípcios se derretem no íntimo.

[[v23-19-2]]

^<<v23-19-2,2>>^ "Incitarei egípcio contra egípcio; cada um lutará contra seu irmão, vizinho lutará contra vizinho, cidade contra cidade, reino contra reino.

[[v23-19-3]]

^<<v23-19-3,3>>^ Os egípcios ficarão desanimados, e farei que os seus planos resultem em nada. Depois eles consultarão os ídolos e os necromantes, os médiuns e os adivinhos,

[[v23-19-4]]

^<<v23-19-4,4>>^ então eu entregarei os egípcios nas mãos de um senhor cruel, e um rei feroz dominará sobre eles", anuncia o Soberano, o Senhor dos Exércitos.

[[v23-19-5]]

^<<v23-19-5,5>>^ As águas do rio vão secar-se; o leito do rio ficará completamente seco.

[[v23-19-6]]

^<<v23-19-6,6>>^ Os canais terão mau cheiro; os riachos do Egito vão diminuir até secarem-se; os juncos e as canas murcharão.

[[v23-19-7]]

^<<v23-19-7,7>>^ Haverá lugares secos ao longo do Nilo e na própria foz do rio. Tudo o que for semeado ao longo do Nilo se ressecará, será levado pelo vento e desaparecerá.

[[v23-19-8]]

^<<v23-19-8,8>>^ Os pescadores gemerão e se lamentarão como também todos os que lançam anzóis no Nilo; os que lançam redes na água se desanimarão.

[[v23-19-9]]

^<<v23-19-9,9>>^ Os que trabalham com linho e os tecelões de algodão se desesperarão.

[[v23-19-10]]

^<<v23-19-10,10>>^ Os nobres ficarão deprimidos, e todos os assalariados ficarão abatidos.

[[v23-19-11]]

^<<v23-19-11,11>>^ Os líderes de Zoa não passam de insensatos; os sábios conselheiros do faraó dão conselhos tolos. Como, então, vocês podem dizer ao faraó: "Sou sábio, sou discípulo dos reis da antigüidade"?

[[v23-19-12]]

^<<v23-19-12,12>>^ Onde estão agora os seus sábios? Que lhe mostrem, se é que eles tem conhecimento do que o Senhor dos Exércitos tem planejado contra o Egito.

[[v23-19-13]]

^<<v23-19-13,13>>^ Tornaram-se tolos os líderes de Zoã, e os de Mênfis são enganados; os chefes dos seus clãs induziram o Egito ao erro.

[[v23-19-14]]

^<<v23-19-14,14>>^ O Senhor derramou dentro deles um espírito que os deixou desorientados; eles levam o Egito a cambalear em tudo quanto faz, como cambaleia o bêbado em volta do seu vômito.

[[v23-19-15]]

^<<v23-19-15,15>>^ Não há nada que o Egito possa fazer, nada que a cabeça ou a cauda, a palma ou o junco possam fazer.

[[v23-19-16]]

^<<v23-19-16,16>>^ Naquele dia os egípcios serão como mulheres. Tremerão de medo diante do agitar da mão do Senhor dos Exércitos, que se levantará contra eles.

[[v23-19-17]]

^<<v23-19-17,17>>^ Judá trará pavor aos egípcios; todo aquele que mencionar o nome de Judá ficará apavorado, por causa do plano do Senhor dos Exércitos contra eles.

[[v23-19-18]]

^<<v23-19-18,18>>^ Naquele dia cinco cidades do Egito falarão a língua de Canaã e jurarão lealdade ao Senhor dos Exércitos. Uma delas será chamada cidade do Sol.

[[v23-19-19]]

^<<v23-19-19,19>>^ Naquele dia haverá um altar dedicado ao Senhor no centro do Egito, e em sua fronteira, um monumento ao Senhor.

[[v23-19-20]]

^<<v23-19-20,20>>^ Serão um sinal e um testemunho para o Senhor dos Exércitos na terra do Egito. Quando eles clamarem ao Senhor por causa dos seus opressores, ele lhes enviará um salvador e defensor que os libertará.

[[v23-19-21]]

^<<v23-19-21,21>>^ Assim o Senhor se dará a conhecer aos egípcios, e naquele dia eles saberão quem é o Senhor. A ele prestarão culto com sacrifícios e ofertas de cereal; farão votos ao Senhor e os cumprirão.

[[v23-19-22]]

^<<v23-19-22,22>>^ O Senhor ferirá os egípcios; ele os ferirá e os curará. Eles se voltarão para o Senhor, e ele responderá às suas súplicas e os curará.

[[v23-19-23]]

^<<v23-19-23,23>>^ Naquele dia haverá uma estrada do Egito para a Assíria. Os assírios irão para o Egito, e os egípcios para a Assíria, e os egípcios e os assírios cultuarão juntos.

[[v23-19-24]]

^<<v23-19-24,24>>^ Naquele dia Israel será um mediador entre o Egito e a Assíria, uma bênção na terra.

[[v23-19-25]]

^<<v23-19-25,25>>^ O Senhor dos Exércitos os abençoará, dizendo: "Bendito seja o Egito, meu povo, a Assíria, obra de minhas mãos, e Israel, minha herança".

'''

xref:023-isaias/023-isaias-018.adoc#v23-18-0[&#60; Capítulo Anterior] | <<v23-19-0,Topo>> | xref:023-isaias/023-isaias-020.adoc#v23-20-0[Próximo Capítulo &#62;]