include::./index.adoc[]

[[v23-35-0]]
=== Isaías, 35
// nvi ?, NVI - Nova Versão Internacional

[[v23-35-1]]

^<<v23-35-1,1>>^ O deserto e a terra ressequida se regozijarão; o ermo exultará e florescerá como a tulipa;

[[v23-35-2]]

^<<v23-35-2,2>>^ irromperá em flores, mostrará grande regozijo e cantará de alegria. A glória do Líbano lhe será dada, como também o resplendor do Carmelo e de Sarom; verão a glória do Senhor, o resplendor do nosso Deus.

[[v23-35-3]]

^<<v23-35-3,3>>^ Fortaleçam as mãos cansadas, firmem os joelhos vacilantes;

[[v23-35-4]]

^<<v23-35-4,4>>^ digam aos desanimados de coração: "Sejam fortes, não temam! Seu Deus virá, virá com vingança; com divina retribuição virá para salvá-los".

[[v23-35-5]]

^<<v23-35-5,5>>^ Então se abrirão os olhos dos cegos e se destaparão os ouvidos dos surdos.

[[v23-35-6]]

^<<v23-35-6,6>>^ Então os coxos saltarão como o cervo, e a língua do mudo cantará de alegria. Águas irromperão no ermo e riachos no deserto.

[[v23-35-7]]

^<<v23-35-7,7>>^ A areia abrasadora se tornará um lago; a terra seca, fontes borbulhantes. Nos antros onde outrora havia chacais, crescerão a relva, o junco e o papiro.

[[v23-35-8]]

^<<v23-35-8,8>>^ E ali haverá uma grande estrada, um caminho que será chamado Caminho de Santidade. Os impuros não passarão por ele; servirá apenas aos que são do Caminho; os insensatos não o tomarão.

[[v23-35-9]]

^<<v23-35-9,9>>^ Ali não haverá leão algum, e nenhum animal feroz passará por ele; não se acharão ali. Só os redimidos andarão por ele,

[[v23-35-10]]

^<<v23-35-10,10>>^ e os que o Senhor resgatou voltarão. Entrarão em Sião com cantos de alegria; duradoura alegria coroará suas cabeças. Júbilo e alegria se apoderarão deles, e a tristeza e o suspiro fugirão.

'''

xref:023-isaias/023-isaias-034.adoc#v23-34-0[&#60; Capítulo Anterior] | <<v23-35-0,Topo>> | xref:023-isaias/023-isaias-036.adoc#v23-36-0[Próximo Capítulo &#62;]