include::./index.adoc[]

[[v23-25-0]]
=== Isaías, 25
// nvi ?, NVI - Nova Versão Internacional

[[v23-25-1]]

^<<v23-25-1,1>>^ Senhor, tu és o meu Deus; eu te exaltarei e louvarei o teu nome, pois com grande perfeição tens feito maravilhas, coisas há muito planejadas.

[[v23-25-2]]

^<<v23-25-2,2>>^ Fizeste da cidade um monte de entulho, da cidade fortificada uma ruína, da cidadela dos estrangeiros uma cidade inexistente, que jamais será reconstruída.

[[v23-25-3]]

^<<v23-25-3,3>>^ Por isso um povo forte te honrará; a cidade das nações cruéis te temerá.

[[v23-25-4]]

^<<v23-25-4,4>>^ Tens sido refúgio para os pobres, refúgio para o necessitado em sua aflição, abrigo contra a tempestade e sombra contra o calor quando o sopro dos cruéis é como tempestade contra um muro

[[v23-25-5]]

^<<v23-25-5,5>>^ e como o calor do deserto. Tu silencias o bramido dos estrangeiros; assim como diminui o calor com a sombra de uma nuvem, também a canção dos temíveis é emudecida.

[[v23-25-6]]

^<<v23-25-6,6>>^ Neste monte o Senhor dos Exércitos preparará um farto banquete para todos os povos, um banquete de vinho envelhecido, com carnes suculentas e o melhor vinho.

[[v23-25-7]]

^<<v23-25-7,7>>^ Neste monte ele destruirá o véu que envolve todos os povos, a cortina que cobre todas as nações;

[[v23-25-8]]

^<<v23-25-8,8>>^ destruirá a morte para sempre. O Soberano Senhor enxugará as lágrimas de todo o rosto e retirará de toda a terra a zombaria do seu povo. Foi o Senhor quem disse!

[[v23-25-9]]

^<<v23-25-9,9>>^ Naquele dia dirão: "Esse é o nosso Deus; nós confiamos nele, e ele nos salvou. Esse é o Senhor, nós confiamos nele; exultemos e alegremo-nos, pois ele nos salvou".

[[v23-25-10]]

^<<v23-25-10,10>>^ Pois a mão do Senhor repousará sobre este monte; mas Moabe será pisoteado em seu próprio lugar, como a palha é pisoteada na esterqueira.

[[v23-25-11]]

^<<v23-25-11,11>>^ Ali Moabe estenderá as mãos, como faz o nadador para nadar, mas o Senhor abaterá o seu orgulho, apesar da habilidade das suas mãos.

[[v23-25-12]]

^<<v23-25-12,12>>^ Abaterá as torres altas dos seus altos muros e os derrubará; ele os lançará ao pó da terra.

'''

xref:023-isaias/023-isaias-024.adoc#v23-24-0[&#60; Capítulo Anterior] | <<v23-25-0,Topo>> | xref:023-isaias/023-isaias-026.adoc#v23-26-0[Próximo Capítulo &#62;]