include::./index.adoc[]

[[v23-49-0]]
=== Isaías, 49
// nvi ?, NVI - Nova Versão Internacional

[[v23-49-1]]

^<<v23-49-1,1>>^ Escutem-me, vocês, ilhas; ouçam, vocês, nações distantes: Antes de eu nascer o Senhor me chamou; desde o meu nascimento ele fez menção de meu nome.

[[v23-49-2]]

^<<v23-49-2,2>>^ Ele fez de minha boca uma espada afiada, na sombra de sua mão ele me escondeu; ele me tornou uma flecha polida e escondeu-me na sua aljava.

[[v23-49-3]]

^<<v23-49-3,3>>^ Ele me disse: "Você é meu servo, Israel, em quem mostrarei o meu esplendor".

[[v23-49-4]]

^<<v23-49-4,4>>^ Mas eu disse: "Tenho me afadigado sem qualquer propósito; tenho gasto minha força em vão e para nada. Contudo, o que me é devido está na mão do Senhor, e a minha recompensa está com o meu Deus".

[[v23-49-5]]

^<<v23-49-5,5>>^ E agora o Senhor diz, aquele que me formou no ventre para ser o seu servo para trazer de volta Jacó e reunir Israel a ele mesmo, pois sou honrado aos olhos do Senhor, e o meu Deus tem sido a minha força;

[[v23-49-6]]

^<<v23-49-6,6>>^ ele diz: "É coisa pequena demais para você ser meu servo para restaurar as tribos de Jacó e trazer de volta aqueles de Israel que eu guardei. Também farei de você uma luz para os gentios, para que você leve a minha salvação até aos confins da terra".

[[v23-49-7]]

^<<v23-49-7,7>>^ Assim diz o Senhor, o Redentor e o Santo de Israel, àquele que foi desprezado e detestado pela nação, ao servo de governantes: "Reis o verão e se levantarão, líderes verão e se encurvarão, por causa do Senhor, que é fiel, o Santo de Israel, que o escolheu".

[[v23-49-8]]

^<<v23-49-8,8>>^ Assim diz o Senhor: "No tempo favorável eu lhe responderei, e no dia da salvação eu o ajudarei; eu o guardarei e farei que você seja uma aliança para o povo, para restaurar a terra e distribuir suas propriedades abandonadas,

[[v23-49-9]]

^<<v23-49-9,9>>^ para dizer aos cativos: "Saiam", e para aqueles que estão nas trevas: "Apareçam! " "Eles se apascentarão junto aos caminhos e acharão pastagem em toda colina estéril.

[[v23-49-10]]

^<<v23-49-10,10>>^ Não terão fome nem sede, o calor do deserto e o sol os atingirá. Aquele que tem compaixão deles os guiará e os conduzirá para as fontes de água.

[[v23-49-11]]

^<<v23-49-11,11>>^ Transformarei todos os meus montes em estradas, e os meus caminhos serão erguidos.

[[v23-49-12]]

^<<v23-49-12,12>>^ Veja, eles virão de bem longe alguns do norte, alguns do oeste, alguns de Assuã".

[[v23-49-13]]

^<<v23-49-13,13>>^ Gritem de alegria, ó céus, regozije-se, ó terra; irrompam em canção, ó montes! Pois o Senhor consola o seu povo e terá compaixão de seus afligidos.

[[v23-49-14]]

^<<v23-49-14,14>>^ Sião, porém, disse: "O Senhor me abandonou, o Senhor me desamparou".

[[v23-49-15]]

^<<v23-49-15,15>>^ "Será que uma mãe pode esquecer do seu bebê que ainda mama e não ter compaixão do filho que gerou? Embora ela possa se esquecer, eu não me esquecerei de você!

[[v23-49-16]]

^<<v23-49-16,16>>^ Veja, eu gravei você nas palmas das minhas mãos; seus muros estão sempre diante de mim.

[[v23-49-17]]

^<<v23-49-17,17>>^ Seus filhos apressam-se em voltar, e aqueles que a despojaram afastam-se de você.

[[v23-49-18]]

^<<v23-49-18,18>>^ Erga os olhos e olhe ao redor; todos os seus filhos se ajuntam e vêm até você. Juro pela minha vida Que você vestirá a todos como ornamento; você os vestirá como uma noiva", declara o Senhor.

[[v23-49-19]]

^<<v23-49-19,19>>^ "Embora você estivesse arruinada e fosse abandonada e sua terra fosse arrasada, agora você será pequena demais para o seu povo, e aqueles que a devoraram estarão bem distantes.

[[v23-49-20]]

^<<v23-49-20,20>>^ Os filhos nascidos durante seu luto ainda dirão ao alcance de seus ouvidos: ‘Este lugar é pequeno demais para nós; dê-nos mais espaço para nele vivermos’.

[[v23-49-21]]

^<<v23-49-21,21>>^ Então você dirá em seu coração: ‘Quem me gerou estes filhos? Eu estava enlutada e estéril; estava exilada e rejeitada. Quem os criou? Fui deixada totalmente só, mas estes... de onde vieram? ’ "

[[v23-49-22]]

^<<v23-49-22,22>>^ Assim diz o Soberano Senhor: "Veja, eu acenarei para os gentios, erguerei minha bandeira para os povos; eles trarão nos braços os seus filhos e carregarão nos ombros as suas filhas.

[[v23-49-23]]

^<<v23-49-23,23>>^ Reis serão os seus padrastos, e suas rainhas serão as suas amas de leite. Eles se inclinarão diante de você, com o rosto em terra; lamberão o pó dos seus pés. Então você saberá que eu sou o Senhor; aqueles que esperam em mim não ficarão decepcionados".

[[v23-49-24]]

^<<v23-49-24,24>>^ Será que se pode tirar o despojo dos guerreiros, ou serem os prisioneiros resgatados do poder dos violentos?

[[v23-49-25]]

^<<v23-49-25,25>>^ Assim, porém, diz o Senhor:

[[v23-49-26]]

^<<v23-49-26,26>>^ "Sim, prisioneiros serão tirados de guerreiros, e despojo será retomado dos violentos; brigarei com os que brigam com você, e seus filhos, eu os salvarei. Farei seus opressores comerem sua própria carne; ficarão bêbados com seu próprio sangue, como com vinho. Então todo mundo saberá que eu, o Senhor, sou o seu Salvador, seu Redentor, o Poderoso de Jacó".

'''

xref:023-isaias/023-isaias-048.adoc#v23-48-0[&#60; Capítulo Anterior] | <<v23-49-0,Topo>> | xref:023-isaias/023-isaias-050.adoc#v23-50-0[Próximo Capítulo &#62;]