include::./index.adoc[]

[[v23-56-0]]
=== Isaías, 56
// nvi ?, NVI - Nova Versão Internacional

[[v23-56-1]]

^<<v23-56-1,1>>^ Assim diz o Senhor: "Mantenham a justiça e pratiquem o que é direito, pois a minha salvação está perto, e logo será revelada a minha retidão.

[[v23-56-2]]

^<<v23-56-2,2>>^ Feliz aquele que age assim, o homem que nisso permanece firme, observando o sábado, para não profaná-lo, e vigiando sua mão, para não cometer nenhum mal".

[[v23-56-3]]

^<<v23-56-3,3>>^ Que nenhum estrangeiro que se disponha a unir-se ao Senhor venha a dizer: "É certo que o Senhor me excluirá do seu povo". E que nenhum eunuco se queixe: "Não passo de uma árvore seca".

[[v23-56-4]]

^<<v23-56-4,4>>^ Pois assim diz o Senhor: "Aos eunucos que guardarem os meus sábados, que escolherem o que me agrada e se apegarem à minha aliança,

[[v23-56-5]]

^<<v23-56-5,5>>^ a eles darei, dentro de meu templo e dos seus muros, um memorial e um nome melhor do que filhos e filhas, um nome eterno, que não será eliminado.

[[v23-56-6]]

^<<v23-56-6,6>>^ E os estrangeiros que se unirem ao Senhor para servi-lo, para amarem o nome do Senhor e para prestar-lhe culto, todos os que guardarem o sábado sem profaná-lo, e que se apegarem à minha aliança,

[[v23-56-7]]

^<<v23-56-7,7>>^ esses eu trarei ao meu santo monte e lhes darei alegria em minha casa de oração. Seus holocaustos e seus sacrifícios serão aceitos em meu altar; pois a minha casa será chamada casa de oração para todos os povos".

[[v23-56-8]]

^<<v23-56-8,8>>^ Palavra do Soberano Senhor, daquele que reúne os exilados de Israel: "Reunirei ainda outros àqueles que já foram reunidos".

[[v23-56-9]]

^<<v23-56-9,9>>^ Venham todos vocês, animais do campo; todos vocês, animais da floresta, venham comer!

[[v23-56-10]]

^<<v23-56-10,10>>^ As sentinelas de Israel estão cegas e não têm conhecimento; todas elas são como cães mudos, incapazes de latir. Deitam-se e sonham; só querem dormir.

[[v23-56-11]]

^<<v23-56-11,11>>^ São cães devoradores, insaciáveis. São pastores sem entendimento; todos seguem seu próprio caminho, cada um procura vantagem própria.

[[v23-56-12]]

^<<v23-56-12,12>>^ "Venham", cada um grita, "tragam-me vinho! Bebamos nossa dose de bebida fermentada, que amanhã será como hoje, e até muito melhor! "

'''

xref:023-isaias/023-isaias-055.adoc#v23-55-0[&#60; Capítulo Anterior] | <<v23-56-0,Topo>> | xref:023-isaias/023-isaias-057.adoc#v23-57-0[Próximo Capítulo &#62;]