include::./index.adoc[]

[[v23-36-0]]
=== Isaías, 36
// nvi ?, NVI - Nova Versão Internacional

[[v23-36-1]]

^<<v23-36-1,1>>^ No décimo quarto ano do reinado de Ezequias, Senaqueribe, rei da Assíria, atacou todas as cidades fortificadas de Judá e se apossou delas.

[[v23-36-2]]

^<<v23-36-2,2>>^ Então o rei da Assíria enviou de Láquis ao rei Ezequias, em Jerusalém, seu comandante com um grande exército. Quando o comandante parou no aqueduto do açude superior, na estrada que leva ao campo do Lavandeiro,

[[v23-36-3]]

^<<v23-36-3,3>>^ o administrador do palácio, Eliaquim, filho de Hilquias, o secretário Sebna e o arquivista real Joá, filho de Asafe, foram ao encontro dele.

[[v23-36-4]]

^<<v23-36-4,4>>^ E o comandante de campo falou: "Digam a Ezequias: "Assim diz o grande rei, o rei da Assíria: ‘Em que você está baseando essa sua confiança?

[[v23-36-5]]

^<<v23-36-5,5>>^ Você diz que tem estratégia e força militar; mas só palavras vãs. Em quem você confia, para rebelar-se contra mim?

[[v23-36-6]]

^<<v23-36-6,6>>^ Pois veja! Agora você está confiando no Egito, aquela cana esmagada, que fura a mão de quem nela se apóia! Assim é o faraó, o rei do Egito, para todos os que dele dependem.

[[v23-36-7]]

^<<v23-36-7,7>>^ E se você me disser: "No Senhor, o nosso Deus, confiamos"; não são dele os altos e os altares que Ezequias removeu, dizendo a Judá e a Jerusalém: "Vocês devem adorar aqui, diante deste altar"? ’

[[v23-36-8]]

^<<v23-36-8,8>>^ "Façamos agora um tratado com o meu senhor, o rei da Assíria: Eu lhe darei dois mil cavalos — se você puder pôr cavaleiros neles!

[[v23-36-9]]

^<<v23-36-9,9>>^ Como então você poderá repelir um só dos menores oficiais do meu senhor, confiando que o Egito lhe dará carros e cavaleiros?

[[v23-36-10]]

^<<v23-36-10,10>>^ Além disso, você pensa que vim atacar e destruir esta nação sem o Senhor? O próprio Senhor me mandou marchar contra esta nação e destruí-la".

[[v23-36-11]]

^<<v23-36-11,11>>^ Então Eliaquim, Sebna e Joá disseram ao comandante: "Por favor, fala com os seus servos em aramaico, pois entendemos essa língua. Não fales em hebraico, pois assim o povo que está sobre os muros entenderá".

[[v23-36-12]]

^<<v23-36-12,12>>^ O comandante, porém, respondeu: "Pensam que o meu senhor mandou-me dizer estas coisas só a vocês e ao seu senhor, e não aos homens que estão sentados no muro? Pois, como vocês, eles terão que comer as próprias fezes e beber a própria urina! "

[[v23-36-13]]

^<<v23-36-13,13>>^ E o comandante se pôs de pé e falou alto, em hebraico: "Ouçam as palavras do grande rei, do rei da Assíria!

[[v23-36-14]]

^<<v23-36-14,14>>^ Não deixem que Ezequias os engane. Ele não poderá livrá-los!

[[v23-36-15]]

^<<v23-36-15,15>>^ Não deixem Ezequias convencê-los a confiar no Senhor, quando diz: ‘Certamente o Senhor nos livrará; esta cidade não será entregue nas mãos do rei da Assíria’.

[[v23-36-16]]

^<<v23-36-16,16>>^ "Não dêem atenção a Ezequias. Assim diz o rei da Assíria: ‘Venham fazer as pazes comigo. Então cada um de vocês comerá de sua própria videira e de sua própria figueira, e beberá água de sua própria cisterna,

[[v23-36-17]]

^<<v23-36-17,17>>^ até que eu os leve a uma terra como a de vocês: terra de cereal e de vinho, terra de pão e de vinhas.

[[v23-36-18]]

^<<v23-36-18,18>>^ " ‘Não deixem que Ezequias os engane quando diz que o Senhor os livrará. Alguma vez o deus de qualquer nação livrou sua terra das mãos do rei da Assíria?

[[v23-36-19]]

^<<v23-36-19,19>>^ Onde estão os deuses de Hamate e de Arpade? Onde estão os deuses de Sefarvaim? Eles livraram Samaria das minhas mãos?

[[v23-36-20]]

^<<v23-36-20,20>>^ Quem dentre todos os deuses dessas nações conseguiu livrar a sua terra? Como então o Senhor poderá livrar Jerusalém das minhas mãos? ’ "

[[v23-36-21]]

^<<v23-36-21,21>>^ Mas o povo ficou em silêncio e nada respondeu, porque o rei dera esta ordem: "Não lhe respondam".

[[v23-36-22]]

^<<v23-36-22,22>>^ Então o administrador do palácio, Eliaquim, filho de Hilquias, o secretário Sebna e o arquivista Joá, filho de Asafe, com as vestes rasgadas, foram contar a Ezequias o que dissera o comandante.

'''

xref:023-isaias/023-isaias-035.adoc#v23-35-0[&#60; Capítulo Anterior] | <<v23-36-0,Topo>> | xref:023-isaias/023-isaias-037.adoc#v23-37-0[Próximo Capítulo &#62;]