include::./index.adoc[]

[[v24-24-0]]
=== Jeremias, 24
// nvi ?, NVI - Nova Versão Internacional

[[v24-24-1]]

^<<v24-24-1,1>>^ E o Senhor mostrou-me dois cestos de figos postos diante do templo do Senhor. Isso aconteceu depois que Nabucodonosor levou de Jerusalém, para o exílio na Babilônia, Joaquim, filho de Jeoaquim, rei de Judá, os líderes de Judá, e os artesãos e artífices.

[[v24-24-2]]

^<<v24-24-2,2>>^ Um cesto continha figos muito bons, como os que amadurecem no princípio da colheita; os figos do outro cesto eram ruins e intragáveis.

[[v24-24-3]]

^<<v24-24-3,3>>^ Então o Senhor me perguntou: "O que você vê, Jeremias? " Eu respondi: "Figos. Os bons são muitos bons, mas os ruins são intragáveis. "

[[v24-24-4]]

^<<v24-24-4,4>>^ Então o Senhor me dirigiu a palavra, dizendo:

[[v24-24-5]]

^<<v24-24-5,5>>^ "Assim diz o Senhor, o Deus de Israel: ‘Considero como esses figos bons os exilados de Judá, os quais expulsei deste lugar para a terra dos babilônios, a fim de fazer-lhes bem.

[[v24-24-6]]

^<<v24-24-6,6>>^ Olharei favoravelmente para eles, e não os trarei de volta a esta terra. Eu os edificarei e não os derrubarei; eu os plantarei e não os arrancarei.

[[v24-24-7]]

^<<v24-24-7,7>>^ Eu lhes darei coração capaz de conhecer-me e de saber que eu sou o Senhor. Serão o meu povo, e eu serei o seu Deus, pois eles se voltarão para mim de todo o coração.

[[v24-24-8]]

^<<v24-24-8,8>>^ " ‘Mas como se faz com os figos ruins e intragáveis’, diz o Senhor, ‘assim lidarei com Zedequias, rei de Judá, com os seus líderes e com os sobreviventes de Jerusalém, tanto os que permanecem nesta terra como os que vivem no Egito.

[[v24-24-9]]

^<<v24-24-9,9>>^ Eu os tornarei objeto de terror e de desgraça para todos os reinos da terra. Para onde quer que eu os expulsar, serão uma afronta e servirão de exemplo, ridículo e maldição.

[[v24-24-10]]

^<<v24-24-10,10>>^ Enviarei contra eles a guerra, a fome e a peste até que sejam eliminados da terra que dei a eles e aos seus antepassados’ ".

'''

xref:024-jeremias/024-jeremias-023.adoc#v24-23-0[&#60; Capítulo Anterior] | <<v24-24-0,Topo>> | xref:024-jeremias/024-jeremias-025.adoc#v24-25-0[Próximo Capítulo &#62;]