include::./index.adoc[]

[[v24-15-0]]
=== Jeremias, 15
// nvi ?, NVI - Nova Versão Internacional

[[v24-15-1]]

^<<v24-15-1,1>>^ Então o Senhor me disse: "Ainda que Moisés e Samuel estivessem diante de mim, intercedendo por este povo, eu não lhes mostraria favor. Expulse-os da minha presença! Que saiam!

[[v24-15-2]]

^<<v24-15-2,2>>^ E, se lhe perguntarem: ‘Para onde iremos? ’, diga-lhes: ‘Assim diz o Senhor: " ‘Os destinados à morte, para a morte; os destinados à espada, para a espada; os destinados à fome, para a fome; os destinados ao cativeiro, para o cativeiro’.

[[v24-15-3]]

^<<v24-15-3,3>>^ "Enviarei quatro tipos de destruidores contra eles", declara o Senhor: "a espada para matar, os cães para dilacerar, as aves do céu e os animais selvagens para devorar e destruir.

[[v24-15-4]]

^<<v24-15-4,4>>^ Eu farei deles uma causa de terror para todas as nações da terra, por tudo o que Manassés, filho de Ezequias, rei de Judá, fez em Jerusalém.

[[v24-15-5]]

^<<v24-15-5,5>>^ "Quem terá compaixão de você, ó Jerusalém? Quem se lamentará por você? Quem vai parar e perguntar como você está?

[[v24-15-6]]

^<<v24-15-6,6>>^ Você me rejeitou", diz o Senhor; "Você vive se desviando. Por isso, porei as mãos em você e a destruirei; cansei-me de mostrar compaixão.

[[v24-15-7]]

^<<v24-15-7,7>>^ Eu os espalhei ao vento como palha nas cidades desta terra. Deixei-os sem filhos; destruí o meu povo, pois não se converteram de seus caminhos.

[[v24-15-8]]

^<<v24-15-8,8>>^ Fiz com que as suas viúvas se tornassem mais numerosas do que a areia do mar. Ao meio-dia, trouxe um destruidor contra as mães dos jovens guerreiros; fiz cair sobre elas repentina angústia e pavor.

[[v24-15-9]]

^<<v24-15-9,9>>^ A mãe de sete filhos desmaiou e está ofegante. Para ela o sol se pôs enquanto ainda era dia; ela foi envergonhada e humilhada. Entregarei os sobreviventes à espada diante dos seus inimigos", declara o Senhor

[[v24-15-10]]

^<<v24-15-10,10>>^ Ai de mim, minha mãe, por me haver dado à luz! Pois sou um homem em luta e em contenda com a terra toda! Nunca emprestei nem tomei emprestado, e assim mesmo todos me amaldiçoam.

[[v24-15-11]]

^<<v24-15-11,11>>^ O Senhor disse: "Eu certamente o fortaleci para o bem e intervim por você, na época da desgraça e da adversidade, por causa do inimigo.

[[v24-15-12]]

^<<v24-15-12,12>>^ "Será alguém capaz de quebrar o ferro, o ferro que vem do norte, ou o bronze?

[[v24-15-13]]

^<<v24-15-13,13>>^ Diga a esse povo: Darei de graça a sua riqueza e os seus tesouros como despojo, por causa de todos os seus pecados, por toda a sua terra.

[[v24-15-14]]

^<<v24-15-14,14>>^ Eu os tornarei escravos de seus inimigos, numa terra que vocês não conhecem, pois a minha ira acenderá um fogo que arderá contra vocês".

[[v24-15-15]]

^<<v24-15-15,15>>^ Tu me conheces, Senhor; lembra-te de mim e vem em meu auxílio e vinga-me dos meus perseguidores. Que, pela tua paciência para com eles, eu não seja eliminado. Sabes que sofro afronta por tua causa.

[[v24-15-16]]

^<<v24-15-16,16>>^ Quando as tuas palavras foram encontradas eu as comi; elas são a minha alegria e o meu júbilo, pois pertenço a ti, Senhor Deus dos Exércitos.

[[v24-15-17]]

^<<v24-15-17,17>>^ Jamais me sentei na companhia dos que se divertem, nunca festejei com eles. Sentei-me sozinho, porque a tua mão estava sobre mim e me encheste de indignação.

[[v24-15-18]]

^<<v24-15-18,18>>^ Por que é permanente a minha dor, e a minha ferida é grave e incurável? Por que te tornaste para mim como um riacho seco, cujos mananciais falham?

[[v24-15-19]]

^<<v24-15-19,19>>^ Assim respondeu o Senhor: "Se você se arrepender, eu o restaurarei para que possa me servir; se você disser palavras de valor, e não indignas, será o meu porta-voz. Deixe esse povo voltar-se para você, mas não se volte para eles.

[[v24-15-20]]

^<<v24-15-20,20>>^ Eu farei de você uma muralha de bronze fortificada diante deste povo; lutarão contra você, mas não o vencerão, pois estou com você para resgatá-lo e salvá-lo", declara o Senhor.

[[v24-15-21]]

^<<v24-15-21,21>>^ "Eu o livrarei das mãos dos ímpios e o resgatarei das garras dos violentos".

'''

xref:024-jeremias/024-jeremias-014.adoc#v24-14-0[&#60; Capítulo Anterior] | <<v24-15-0,Topo>> | xref:024-jeremias/024-jeremias-016.adoc#v24-16-0[Próximo Capítulo &#62;]