include::./index.adoc[]

[[v24-16-0]]
=== Jeremias, 16
// nvi ?, NVI - Nova Versão Internacional

[[v24-16-1]]

^<<v24-16-1,1>>^ Então o Senhor me dirigiu a palavra, dizendo:

[[v24-16-2]]

^<<v24-16-2,2>>^ "Não se case nem tenha filhos ou filhas neste lugar";

[[v24-16-3]]

^<<v24-16-3,3>>^ porque assim diz o Senhor a respeito dos filhos e filhas nascidos nesta terra, e a respeito das mulheres que forem suas mães e dos homens que forem seus pais:

[[v24-16-4]]

^<<v24-16-4,4>>^ "Eles morrerão de doenças graves; ninguém pranteará por eles; não serão sepultados, mas servirão de esterco para o solo. Perecerão pela espada e pela fome, e os seus cadáveres serão o alimento das aves e dos animais".

[[v24-16-5]]

^<<v24-16-5,5>>^ Porque assim diz o Senhor: "Não entre numa casa onde há luto; não vá prantear nem mostrar condolências, porque retirei a minha paz, o meu amor leal e a minha compaixão desse povo", declara o Senhor.

[[v24-16-6]]

^<<v24-16-6,6>>^ "Tanto grandes como pequenos morrerão nesta terra; não serão sepultados nem se pranteará por eles; não se farão incisões nem se rapará a cabeça por causa deles.

[[v24-16-7]]

^<<v24-16-7,7>>^ Ninguém oferecerá comida para fortalecer os que pranteiam pelos mortos; ninguém dará de beber do cálice da consolação nem mesmo pelo pai ou pela mãe.

[[v24-16-8]]

^<<v24-16-8,8>>^ "Não entre numa casa em que há um banquete para se assentar com eles a fim de comer e beber.

[[v24-16-9]]

^<<v24-16-9,9>>^ Porque assim diz o Senhor dos Exércitos, o Deus de Israel: Farei cessar neste lugar, diante dos olhos de vocês e durante a vida de vocês, a voz de júbilo e a voz de alegria, a voz do noivo e a voz da noiva.

[[v24-16-10]]

^<<v24-16-10,10>>^ "Quando você falar todas essas coisas a este povo e eles lhe perguntarem: ‘Por que o Senhor determinou uma desgraça tão terrível contra nós? Que delito ou pecado cometemos contra o Senhor, contra o nosso Deus? ’,

[[v24-16-11]]

^<<v24-16-11,11>>^ diga-lhes: ‘Foi porque os seus antepassados me abandonaram’, diz o Senhor, ‘e seguiram outros deuses, aos quais prestaram culto e adoraram. Eles me abandonaram e não obedeceram à minha lei.

[[v24-16-12]]

^<<v24-16-12,12>>^ Mas vocês têm feito coisas piores do que os seus antepassados: cada um segue a rebeldia do seu coração mau, em vez de obedecer-me.

[[v24-16-13]]

^<<v24-16-13,13>>^ Por isso os lançarei fora desta terra, para uma terra que vocês e os seus antepassados desconhecem; lá vocês servirão a outros deuses dia e noite, pois não terei misericórdia de vocês’.

[[v24-16-14]]

^<<v24-16-14,14>>^ "Contudo, vêm dias", declara o Senhor, "quando já não mais se dirá: ‘Juro pelo nome do Senhor, que trouxe os israelitas do Egito’.

[[v24-16-15]]

^<<v24-16-15,15>>^ Antes dirão: ‘Juro pelo nome do Senhor, que trouxe os israelitas do norte e de todos os países para onde ele os havia expulsado’. Eu os conduzirei de volta para a sua terra, terra que dei aos seus antepassados.

[[v24-16-16]]

^<<v24-16-16,16>>^ "Mas agora mandarei chamar muitos pescadores", declara o Senhor, "e eles os pescarão. Depois disso mandarei chamar muitos caçadores, e eles os caçarão em cada monte e colina e nas fendas das rochas.

[[v24-16-17]]

^<<v24-16-17,17>>^ Os meus olhos vêem todos os seus caminhos; eles não estão escondidos de mim, nem a sua iniqüidade está oculta aos meus olhos.

[[v24-16-18]]

^<<v24-16-18,18>>^ Eu lhes retribuirei em dobro pela sua impiedade e pelo seu pecado, porque contaminaram a minha terra com as carcaças de seus ídolos detestáveis e encheram a minha herança com as suas abominações. "

[[v24-16-19]]

^<<v24-16-19,19>>^ Senhor, minha força e minha fortaleza, meu abrigo seguro na hora da adversidade, a ti virão as nações desde os confins da terra e dirão: "Nossos antepassados possuíam deuses falsos, ídolos inúteis, que não lhes fizeram bem algum.

[[v24-16-20]]

^<<v24-16-20,20>>^ Pode o homem mortal fazer os seus próprios deuses? Sim, mas estes não seriam deuses! "

[[v24-16-21]]

^<<v24-16-21,21>>^ "Portanto eu lhes ensinarei; desta vez eu lhes ensinarei sobre o meu poder e sobre a minha força. Então saberão que o meu nome é Senhor.

'''

xref:024-jeremias/024-jeremias-015.adoc#v24-15-0[&#60; Capítulo Anterior] | <<v24-16-0,Topo>> | xref:024-jeremias/024-jeremias-017.adoc#v24-17-0[Próximo Capítulo &#62;]