include::./index.adoc[]

[[v24-41-0]]
=== Jeremias, 41
// nvi ?, NVI - Nova Versão Internacional

[[v24-41-1]]

^<<v24-41-1,1>>^ No sétimo mês, Ismael, filho de Netanias, filho de Elisama, que era de sangue real e tinha sido um dos oficiais do rei, foi até Gedalias, filho de Aicam, em Mispá, levando consigo dez homens. Enquanto comiam juntos,

[[v24-41-2]]

^<<v24-41-2,2>>^ Ismael, filho de Netanias, e os dez homens que estavam com ele se levantaram e feriram à espada Gedalias, filho de Aicam, neto de Safã, matando aquele que o rei da Babilônia tinha nomeado governador de Judá.

[[v24-41-3]]

^<<v24-41-3,3>>^ Ismael também matou todos os judeus que estavam com Gedalias em Mispá, bem como os soldados babilônios que ali estavam.

[[v24-41-4]]

^<<v24-41-4,4>>^ No dia seguinte ao assassinato de Gedalias, antes que alguém o soubesse,

[[v24-41-5]]

^<<v24-41-5,5>>^ oitenta homens que haviam rapado a barba, rasgado suas roupas e feito cortes no corpo, vieram de Siquém, de Siló e de Samaria, trazendo ofertas de cereal e incenso para oferecer no templo do Senhor.

[[v24-41-6]]

^<<v24-41-6,6>>^ Ismael, filho de Netanias, saiu de Mispá para encontrá-los, chorando enquanto caminhava. Quando os encontrou, disse: "Venham até onde se encontra Gedalias, filho de Aicam".

[[v24-41-7]]

^<<v24-41-7,7>>^ Quando entraram na cidade, Ismael, filho de Netanias, e os homens que estavam com ele os mataram e os atiraram numa cisterna.

[[v24-41-8]]

^<<v24-41-8,8>>^ Mas dez deles disseram a Ismael: "Não nos mate! Temos trigo e cevada, azeite e mel, escondidos num campo". Então ele os deixou em paz e não os matou com os demais.

[[v24-41-9]]

^<<v24-41-9,9>>^ A cisterna na qual ele jogou os corpos dos homens que havia matado, juntamente com o de Gedalias, tinha sido cavada pelo rei Asa para defender-se de Baasa, rei de Israel. Ismael, filho de Netanias, encheu-a com os mortos.

[[v24-41-10]]

^<<v24-41-10,10>>^ Ismael tomou como prisioneiros todo o restante do povo que estava em Mispá, inclusive as filhas do rei, sobre os quais Nebuzaradã, o comandante da guarda imperial, havia nomeado Gedalias, filho de Aicam, governador. Ismael, filho de Netanias, levou-os como prisioneiros e partiu para o território de Amom.

[[v24-41-11]]

^<<v24-41-11,11>>^ Quando Joanã, filho de Careá, e todos os comandantes do exército, que com ele estavam, souberam do crime que Ismael, filho de Netanias, tinha cometido,

[[v24-41-12]]

^<<v24-41-12,12>>^ convocaram todos os seus soldados para lutar contra ele. Eles o alcançaram perto do grande açude de Gibeom.

[[v24-41-13]]

^<<v24-41-13,13>>^ Quando todo o povo, que Ismael tinha levado como prisioneiro, viu Joanã, filho de Careá, e os comandantes do exército que estavam com ele, alegrou-se.

[[v24-41-14]]

^<<v24-41-14,14>>^ Todo o povo que Ismael tinha levado como prisioneiro de Mispá se voltou e passou para o lado de Joanã, filho de Careá.

[[v24-41-15]]

^<<v24-41-15,15>>^ Mas Ismael, filho de Netanias, e oito de seus homens escaparam de Joanã e fugiram para o território de Amom

[[v24-41-16]]

^<<v24-41-16,16>>^ Então, Joanã, filho de Careá, e todos os comandantes do exército que com ele estavam levaram todos os que tinham restado em Mispá, os quais ele tinha resgatado de Ismael, filho de Netanias, depois que este havia assassinado Gedalias, filho de Aicam: os soldados, as mulheres, as crianças e os oficiais do palácio real, que ele tinha trazido de Gibeom.

[[v24-41-17]]

^<<v24-41-17,17>>^ E eles prosseguiram, parando em Gerute-Quimã, perto de Belém, a caminho do Egito,

[[v24-41-18]]

^<<v24-41-18,18>>^ Queriam escapar dos babilônios. Estavam com medo porque Ismael, filho de Netanias, tinha matado Gedalias, filho de Aicam, a quem o rei da Babilônia nomeara governador de Judá.

'''

xref:024-jeremias/024-jeremias-040.adoc#v24-40-0[&#60; Capítulo Anterior] | <<v24-41-0,Topo>> | xref:024-jeremias/024-jeremias-042.adoc#v24-42-0[Próximo Capítulo &#62;]