include::./index.adoc[]

[[v24-4-0]]
=== Jeremias, 4
// nvi ?, NVI - Nova Versão Internacional

[[v24-4-1]]

^<<v24-4-1,1>>^ "Se você voltar, ó Israel, volte para mim", diz o Senhor. "Se você afastar para longe de minha vista os seus ídolos detestáveis, e não se desviar,

[[v24-4-2]]

^<<v24-4-2,2>>^ se você jurar pelo nome do Senhor, com fidelidade, justiça e retidão, então as nações serão por ele abençoadas e nele se gloriarão. "

[[v24-4-3]]

^<<v24-4-3,3>>^ Assim diz o Senhor ao povo de Judá e de Jerusalém: "Lavrem seus campos não arados e não semeiem entre espinhos.

[[v24-4-4]]

^<<v24-4-4,4>>^ Purifiquem-se para o Senhor, sejam fiéis à aliança, homens de Judá e habitantes de Jerusalém! Se não fizerem isso, a minha ira se acenderá e queimará como fogo, por causa do mal que vocês fizeram; queimará e ninguém conseguirá apagá-la.

[[v24-4-5]]

^<<v24-4-5,5>>^ "Anunciem em Judá! Proclamem em Jerusalém: ‘Toquem a trombeta por toda esta terra! ’ Gritem bem alto e digam: ‘Reúnam-se! Fujamos para as cidades fortificadas! ’

[[v24-4-6]]

^<<v24-4-6,6>>^ Ergam o sinal indicando Sião. Fujam sem demora em busca de abrigo! Porque do Norte eu estou trazendo desgraça, uma grande destruição".

[[v24-4-7]]

^<<v24-4-7,7>>^ Um leão saiu da sua toca, um destruidor de nações se pôs a caminho. Ele saiu de onde vive para arrasar a sua terra. Suas cidades ficarão em ruínas e sem habitantes.

[[v24-4-8]]

^<<v24-4-8,8>>^ Por isso, ponham vestes de lamento, chorem e gritem, pois o fogo da ira do Senhor não se desviou de nós.

[[v24-4-9]]

^<<v24-4-9,9>>^ "Naquele dia", diz o Senhor, "o rei e os seus oficiais perderão a coragem, os sacerdotes ficarão horrorizados e os profetas, perplexos. "

[[v24-4-10]]

^<<v24-4-10,10>>^ Então eu disse: "Ah, Soberano Senhor, como enganaste completamente este povo e a Jerusalém dizendo: ‘Vocês terão paz’, quando a espada está em nossa garganta".

[[v24-4-11]]

^<<v24-4-11,11>>^ Naquela época será dito a este povo e a Jerusalém: "Um vento escaldante, que vem das dunas do deserto, sopra na direção da minha filha, do meu povo, mas não para peneirar nem para limpar.

[[v24-4-12]]

^<<v24-4-12,12>>^ É um vento forte demais, que vem da minha parte. Agora eu pronunciarei as minhas sentenças contra eles".

[[v24-4-13]]

^<<v24-4-13,13>>^ Vejam! Ele avança como as nuvens; os seus carros de guerra são como um furacão e os seus cavalos são mais velozes do que as águias. Ai de nós! Estamos perdidos!

[[v24-4-14]]

^<<v24-4-14,14>>^ Ó Jerusalém, lave o mal do seu coração para que você seja salva. Até quando você vai acolher projetos malignos no íntimo?

[[v24-4-15]]

^<<v24-4-15,15>>^ Ouve-se uma voz proclamando desde Dã, desde os montes de Efraim se anuncia calamidade.

[[v24-4-16]]

^<<v24-4-16,16>>^ "Relatem isso a esta nação e proclamem contra Jerusalém: ‘Um exército inimigo está vindo de uma terra distante, dando seu grito de guerra contra as cidades de Judá.

[[v24-4-17]]

^<<v24-4-17,17>>^ Eles a cercam como homens que guardam um campo, pois ela se rebelou contra mim’ ", declara o Senhor.

[[v24-4-18]]

^<<v24-4-18,18>>^ "A sua própria conduta e as suas ações trouxeram isso sobre você. Como é amargo este seu castigo! Ele atinge até o seu coração! "

[[v24-4-19]]

^<<v24-4-19,19>>^ Ah, minha angústia, minha angústia! Eu me contorço de dor. Ó paredes do meu coração! O meu coração dispara dentro de mim; não posso ficar calado. Ouvi o som da trombeta, ouvi o grito de guerra.

[[v24-4-20]]

^<<v24-4-20,20>>^ Um desastre depois do outro; toda a minha terra foi devastada. Num instante as minhas tendas foram destruídas, e os meus abrigos num momento.

[[v24-4-21]]

^<<v24-4-21,21>>^ Até quando verei o sinal levantado e ouvirei o som da trombeta?

[[v24-4-22]]

^<<v24-4-22,22>>^ "O meu povo é tolo, eles não me conhecem. São crianças insensatas que nada compreendem. São hábeis para praticar o mal, mas não sabem fazer o bem. "

[[v24-4-23]]

^<<v24-4-23,23>>^ Olhei para a terra e ela era sem forma e vazia; e para os céus, e a sua luz tinha desaparecido.

[[v24-4-24]]

^<<v24-4-24,24>>^ Olhei para os montes e eles estavam tremendo; todas as colinas estavam oscilando.

[[v24-4-25]]

^<<v24-4-25,25>>^ Olhei, e não havia mais gente; todas as aves do céu tinham fugido em revoada.

[[v24-4-26]]

^<<v24-4-26,26>>^ Olhei, e a terra fértil era deserto; todas as suas cidades estavam em ruínas por causa do Senhor, por causa do fogo da sua ira.

[[v24-4-27]]

^<<v24-4-27,27>>^ Assim diz o Senhor: "Toda esta terra ficará devastada, embora eu não vá destruí-la completamente.

[[v24-4-28]]

^<<v24-4-28,28>>^ Por causa disso, a terra ficará de luto e o céu, em cima, se escurecerá; porque eu falei, e não me arrependi, decidi, e não voltei atrás".

[[v24-4-29]]

^<<v24-4-29,29>>^ Quando se ouvem os cavaleiros e os flecheiros, todos os habitantes da cidade fogem. Alguns vão para o meio dos arbustos; outros escalam as rochas. Todas as cidades são abandonadas, e ficam sem habitantes.

[[v24-4-30]]

^<<v24-4-30,30>>^ O que você está fazendo, ó cidade devastada? Por que se veste de vermelho e se enfeita com jóias de ouro? Por que você passa sombra nos olhos? Você se embeleza em vão, pois os seus amantes a desprezam e querem tirar-lhe a vida.

[[v24-4-31]]

^<<v24-4-31,31>>^ Ouvi um grito, como de mulher em trabalho de parto, como a agonia de uma mulher ao dar à luz o primeiro filho. É o grito da cidade de Sião, que está ofegante e estende as mãos, dizendo: "Ai de mim! Estou desfalecendo. Minha vida está nas mãos de assassinos! "

'''

xref:024-jeremias/024-jeremias-003.adoc#v24-3-0[&#60; Capítulo Anterior] | <<v24-4-0,Topo>> | xref:024-jeremias/024-jeremias-005.adoc#v24-5-0[Próximo Capítulo &#62;]