include::./index.adoc[]

[[v24-22-0]]
=== Jeremias, 22
// nvi ?, NVI - Nova Versão Internacional

[[v24-22-1]]

^<<v24-22-1,1>>^ Assim diz o Senhor: "Desça ao palácio do rei de Judá e proclame ali esta mensagem:

[[v24-22-2]]

^<<v24-22-2,2>>^ ‘Ouça a palavra do Senhor, ó rei de Judá, tu que te assentas no trono de Davi; tu e teus conselheiros, e teu povo que passa por estas portas.

[[v24-22-3]]

^<<v24-22-3,3>>^ Assim diz o Senhor: Administrem a justiça e o direito: livrem o explorado das mãos do opressor. Não oprimam nem maltratem o estrangeiro, o órfão ou a viúva; nem derramem sangue inocente neste lugar.

[[v24-22-4]]

^<<v24-22-4,4>>^ Porque, se vocês tiverem o cuidado de cumprir essas ordens, então os reis que se assentarem no trono de Davi entrarão pelas portas deste palácio em carruagens e cavalos, em companhia de seus conselheiros e de seu povo.

[[v24-22-5]]

^<<v24-22-5,5>>^ Mas se vocês desobedecerem a essas ordens, declara o Senhor, juro por mim mesmo que este palácio ficará deserto’ ".

[[v24-22-6]]

^<<v24-22-6,6>>^ Porque assim diz o Senhor a respeito do palácio real de Judá: "Apesar de você ser para mim como Gileade e como o topo do Líbano, certamente farei de você um deserto, uma cidade desabitada.

[[v24-22-7]]

^<<v24-22-7,7>>^ Prepararei destruidores contra você, cada um com as suas armas; eles cortarão o melhor dos seus cedros e o lançarão ao fogo.

[[v24-22-8]]

^<<v24-22-8,8>>^ "De numerosas nações muitos passarão por esta cidade e perguntarão uns aos outros: ‘Por que o Senhor fez uma coisa dessas a esta grande cidade? ’

[[v24-22-9]]

^<<v24-22-9,9>>^ E lhes responderão: ‘Foi porque abandonaram a aliança do Senhor, do seu Deus, e adoraram outros deuses e prestaram-lhes culto’ ".

[[v24-22-10]]

^<<v24-22-10,10>>^ Não chorem pelo rei morto nem lamentem sua perda. Chorem amargamente, porém, por aquele que está indo para o exílio, porque jamais voltará nem verá sua terra natal.

[[v24-22-11]]

^<<v24-22-11,11>>^ Porque assim diz o Senhor acerca de Salum, rei de Judá, sucessor de seu pai Josias, que partiu deste lugar: "Ele jamais voltará.

[[v24-22-12]]

^<<v24-22-12,12>>^ Morrerá no lugar para onde o levaram prisioneiro; não verá novamente esta terra".

[[v24-22-13]]

^<<v24-22-13,13>>^ "Ai daquele que constrói o seu palácio por meios corruptos, seus aposentos, pela injustiça, fazendo os seus compatriotas trabalharem por nada, sem pagar-lhes o devido salário.

[[v24-22-14]]

^<<v24-22-14,14>>^ Ele diz: ‘Construirei para mim um grande palácio, com aposentos espaçosos’. Faz amplas janelas, reveste o palácio de cedro e pinta-o de vermelho.

[[v24-22-15]]

^<<v24-22-15,15>>^ "Você acha que acumular cedro faz de você um rei? O seu pai não teve comida e bebida? Ele fez o que era justo e certo, e tudo ia bem com ele.

[[v24-22-16]]

^<<v24-22-16,16>>^ Ele defendeu a causa do pobre e do necessitado, e, assim, tudo corria bem. Não é isso que significa conhecer-me? ", declara o Senhor.

[[v24-22-17]]

^<<v24-22-17,17>>^ "Mas você não vê nem pensa noutra coisa além de lucro desonesto, derramar sangue inocente, opressão e extorsão. "

[[v24-22-18]]

^<<v24-22-18,18>>^ Portanto, assim diz o Senhor a respeito de Jeoaquim, filho de Josias, rei de Judá: "Não se lamentarão por ele, clamando: ‘Ah, meu irmão! ’ ou ‘Ah, minha irmã! ’ Nem se lamentarão, clamando: ‘Ah, meu senhor! ’ ou ‘Ah, sua majestade! ’

[[v24-22-19]]

^<<v24-22-19,19>>^ Ele terá o enterro de um jumento: arrastado e lançado fora das portas de Jerusalém!

[[v24-22-20]]

^<<v24-22-20,20>>^ "Jerusalém, suba ao Líbano e clame, seja ouvida a sua voz em Basã, clame desde Abarim, pois todos os seus aliados foram esmagados.

[[v24-22-21]]

^<<v24-22-21,21>>^ Eu a adverti quando você se sentiu segura, mas você não quis ouvir-me. Esse foi sempre o seu procedimento, pois desde a sua juventude você não me obedece.

[[v24-22-22]]

^<<v24-22-22,22>>^ O vento conduzirá para longe todos os governantes que conduzem você, e os seus aliados irão para o exílio. Então você será envergonhada e humilhada por causa de todas as suas maldades.

[[v24-22-23]]

^<<v24-22-23,23>>^ Você que está entronizada no Líbano, que está aninhada em prédios de cedro, como você gemerá quando lhe vierem as dores de parto, dores como as de uma mulher que está para dar à luz!

[[v24-22-24]]

^<<v24-22-24,24>>^ "Juro pelo meu nome", diz o Senhor, "que ainda que você, Joaquim, filho de Jeoaquim, rei de Judá, fosse um anel de selar em minha mão direita, eu o arrancaria.

[[v24-22-25]]

^<<v24-22-25,25>>^ Eu o entregarei nas mãos daqueles que querem tirar-lhe a vida, daqueles que você teme, nas mãos de Nabucodonosor, rei da Babilônia, e dos babilônios

[[v24-22-26]]

^<<v24-22-26,26>>^ Expulsarei você e sua mãe, a mulher que lhe deu à luz, para um outro país onde vocês não nascerão, e no qual ambos morrerão.

[[v24-22-27]]

^<<v24-22-27,27>>^ Jamais retornarão à terra à qual anseiam voltar".

[[v24-22-28]]

^<<v24-22-28,28>>^ É Joaquim um vaso desprezível e quebrado, um utensílio que ninguém quer? Por que ele e os seus descendentes serão expulsos e lançados num país que não conhecem?

[[v24-22-29]]

^<<v24-22-29,29>>^ Ó terra, terra, terra, ouça a palavra do Senhor!

[[v24-22-30]]

^<<v24-22-30,30>>^ Assim diz o Senhor: "Registrem esse homem como homem sem filhos. Ele não prosperará em toda a sua vida; nenhum dos seus descendentes prosperará nem se assentará no trono de Davi nem governará em Judá".

'''

xref:024-jeremias/024-jeremias-021.adoc#v24-21-0[&#60; Capítulo Anterior] | <<v24-22-0,Topo>> | xref:024-jeremias/024-jeremias-023.adoc#v24-23-0[Próximo Capítulo &#62;]