include::./index.adoc[]

[[v24-30-0]]
=== Jeremias, 30
// nvi ?, NVI - Nova Versão Internacional

[[v24-30-1]]

^<<v24-30-1,1>>^ Esta é a palavra que veio a Jeremias da parte do Senhor:

[[v24-30-2]]

^<<v24-30-2,2>>^ "Assim diz o Senhor, o Deus de Israel: ‘Escreva num livro todas as palavras que eu lhe falei.

[[v24-30-3]]

^<<v24-30-3,3>>^ Certamente vêm os dias’, diz o Senhor, ‘em que mudarei a sorte do meu povo, Israel e Judá, e os farei retornar à terra que dei aos seus antepassados, e eles a possuirão’, declara o Senhor".

[[v24-30-4]]

^<<v24-30-4,4>>^ Estas são as palavras que o Senhor falou acerca de Israel e de Judá:

[[v24-30-5]]

^<<v24-30-5,5>>^ "Assim diz o Senhor: " ‘Ouvem-se gritos de pânico, de pavor e não de paz.

[[v24-30-6]]

^<<v24-30-6,6>>^ Pergunte e veja: Pode um homem dar à luz? Por que vejo, então, todos os homens com as mãos no estômago, como uma mulher em trabalho de parto? Por que estão pálidos todos os rostos?

[[v24-30-7]]

^<<v24-30-7,7>>^ Como será terrível aquele dia! Sem comparação! Será tempo de angústia para Jacó; mas ele será salvo.

[[v24-30-8]]

^<<v24-30-8,8>>^ " ‘Naquele dia’, declara o Senhor dos Exércitos, ‘quebrarei o jugo que está sobre o pescoço deles e arrebentarei as suas correntes; não mais serão escravizados pelos estrangeiros.

[[v24-30-9]]

^<<v24-30-9,9>>^ Servirão ao Senhor, ao seu Deus, e a Davi, seu rei, que darei a eles.

[[v24-30-10]]

^<<v24-30-10,10>>^ " ‘Por isso, não tema Jacó, meu servo! Não fique assustado, ó Israel! ’, declara o Senhor. ‘Eu o salvarei de um lugar distante, e os seus descendentes, da terra do seu exílio. Jacó voltará e ficará em paz e em segurança; ninguém o inquietará.

[[v24-30-11]]

^<<v24-30-11,11>>^ Porque eu estou com você e o salvarei’, diz o Senhor. ‘Destruirei completamente todas as nações entre as quais eu o dispersei; mas a você não destruirei completamente. Eu o disciplinarei, como você merece. Não o deixarei impune. ’

[[v24-30-12]]

^<<v24-30-12,12>>^ "Assim diz o Senhor: " ‘Seu ferimento é grave, sua ferida, incurável.

[[v24-30-13]]

^<<v24-30-13,13>>^ Não há quem defenda a sua causa; não há remédio para a sua ferida, que não cicatriza.

[[v24-30-14]]

^<<v24-30-14,14>>^ Todos os seus amantes esqueceram-se de você; eles não se importam com você. Eu a golpeei como faz um inimigo; dei-lhe um castigo cruel, porque é grande a sua iniqüidade e numerosos são os seus pecados.

[[v24-30-15]]

^<<v24-30-15,15>>^ Por que você grita por causa do seu ferimento, por sua ferida incurável? Fiz essas coisas a você porque é grande a sua iniqüidade e numerosos são os seus pecados.

[[v24-30-16]]

^<<v24-30-16,16>>^ " ‘Mas todos os que a devoram serão devorados; todos os seus adversários irão para o exílio. Aqueles que a saqueiam serão saqueados; eu despojarei todos os que a despojam.

[[v24-30-17]]

^<<v24-30-17,17>>^ Farei cicatrizar o seu ferimento e curarei as suas feridas’, declara o Senhor, ‘porque a você, Sião, chamam de rejeitada, aquela por quem ninguém se importa’.

[[v24-30-18]]

^<<v24-30-18,18>>^ "Assim diz o Senhor: " ‘Mudarei a sorte das tendas de Jacó e terei compaixão das suas moradas. A cidade será reconstruída sobre as suas ruínas e o palácio no seu devido lugar.

[[v24-30-19]]

^<<v24-30-19,19>>^ Deles virão ações de graça e o som de regozijo. Eu os farei aumentar e eles não diminuirão; eu os honrarei e eles não serão desprezados.

[[v24-30-20]]

^<<v24-30-20,20>>^ Seus filhos serão como nos dias do passado, e a sua comunidade será firmada diante de mim; castigarei todos aqueles que os oprimem.

[[v24-30-21]]

^<<v24-30-21,21>>^ Seu líder será um dentre eles; seu governante virá do meio deles. Eu o trarei para perto e ele se aproximará de mim; pois quem se arriscaria a aproximar-se de mim? ’, pergunta o Senhor.

[[v24-30-22]]

^<<v24-30-22,22>>^ Por isso vocês serão o meu povo, e eu serei o seu Deus’ ".

[[v24-30-23]]

^<<v24-30-23,23>>^ Vejam, a tempestade do Senhor! Sua fúria está a solta! Um vendaval vem sobre a cabeça dos ímpios.

[[v24-30-24]]

^<<v24-30-24,24>>^ A ira do Senhor não se afastará até que ele tenha completado os seus propósitos. Em dias vindouros vocês compreenderão isso.

'''

xref:024-jeremias/024-jeremias-029.adoc#v24-29-0[&#60; Capítulo Anterior] | <<v24-30-0,Topo>> | xref:024-jeremias/024-jeremias-031.adoc#v24-31-0[Próximo Capítulo &#62;]