include::./index.adoc[]

[[v24-6-0]]
=== Jeremias, 6
// nvi ?, NVI - Nova Versão Internacional

[[v24-6-1]]

^<<v24-6-1,1>>^ "Fuja para um lugar seguro, povo de Benjamim! Fuja de Jerusalém! Toquem a trombeta em Tecoa! Ponham sinal em Bete-Haquerém! Porque já se vê a desgraça que vem do Norte, uma terrível destruição!

[[v24-6-2]]

^<<v24-6-2,2>>^ Destruirei a cidade de Sião; você é como uma bela pastagem,

[[v24-6-3]]

^<<v24-6-3,3>>^ para onde os pastores vêm com os seus rebanhos; armam as suas tendas ao redor dela e apascentam, cada um no seu lugar.

[[v24-6-4]]

^<<v24-6-4,4>>^ "Preparem-se para enfrentá-la na batalha! Vamos, ataquemos ao meio-dia! Ai de nós! O dia declina e as sombras da tarde já se estendem.

[[v24-6-5]]

^<<v24-6-5,5>>^ Vamos, ataquemos de noite! Destruamos as suas fortalezas! "

[[v24-6-6]]

^<<v24-6-6,6>>^ Assim diz o Senhor dos Exércitos: "Derrubem as árvores e construam rampas de cerco contra Jerusalém. Ó cidade da falsidade! Ela está cheia de opressão.

[[v24-6-7]]

^<<v24-6-7,7>>^ Assim como um poço produz água, também ela produz sua maldade. Violência! Destruição! É o que se ouve dentro dela; doenças e feridas estão sempre diante de mim.

[[v24-6-8]]

^<<v24-6-8,8>>^ Ouça a minha advertência, ó Jerusalém! Do contrário eu me afastarei inteiramente de você e farei de você uma desolação, uma terra desabitada".

[[v24-6-9]]

^<<v24-6-9,9>>^ Assim diz o Senhor dos Exércitos: "Rebusque-se o remanescente de Israel tão completamente, como se faz com uma videira, como faz quem colhe uvas: repassa os ramos cacho por cacho".

[[v24-6-10]]

^<<v24-6-10,10>>^ A quem posso eu falar ou advertir? Quem me escutará? Os ouvidos deles são obstinados, e eles não podem ouvir. A palavra do Senhor é para eles desprezível, não encontram nela motivo de prazer.

[[v24-6-11]]

^<<v24-6-11,11>>^ Mas a ira do Senhor dentro de mim transborda, já não posso retê-la. "Derrama-a sobre as crianças na rua e sobre os jovens reunidos em grupos; pois eles também serão pegos juntos com os maridos e as mulheres, os velhos e os de idade bem avançada.

[[v24-6-12]]

^<<v24-6-12,12>>^ As casas deles serão entregues a outros, juntamente com os seus campos e as suas mulheres, quando eu estender a minha mão contra os que vivem nesta terra", declara o Senhor.

[[v24-6-13]]

^<<v24-6-13,13>>^ "Desde o menor até o maior, todos são gananciosos; profetas e sacerdotes igualmente, todos praticam o engano.

[[v24-6-14]]

^<<v24-6-14,14>>^ Eles tratam da ferida do meu povo como se não fosse grave. ‘Paz, paz’, dizem, quando não há paz alguma.

[[v24-6-15]]

^<<v24-6-15,15>>^ Ficarão eles envergonhados da sua conduta detestável? Não, eles não sentem vergonha alguma, nem mesmo sabem corar. Portanto, cairão entre os que caem; serão humilhados quando eu os castigar", declara o Senhor.

[[v24-6-16]]

^<<v24-6-16,16>>^ Assim diz o Senhor: "Ponham-se nas encruzilhadas e olhem; perguntem pelos caminhos antigos, perguntem pelo bom caminho. Sigam-no e acharão descanso". Mas vocês disseram: ‘Não seguiremos! ’

[[v24-6-17]]

^<<v24-6-17,17>>^ Coloquei sentinelas entre vocês e disse: Prestem atenção ao som da trombeta! Mas vocês disseram: ‘Não daremos atenção’.

[[v24-6-18]]

^<<v24-6-18,18>>^ Vejam, ó nações; observe, ó assembléia, o que acontecerá a eles.

[[v24-6-19]]

^<<v24-6-19,19>>^ Ouça, ó terra: Vou trazer desgraça sobre este povo, o fruto das suas maquinações, porque não deram atenção às minhas palavras e rejeitaram a minha lei.

[[v24-6-20]]

^<<v24-6-20,20>>^ De que me serve o incenso trazido de Sabá, ou o cálamo aromático de uma terra distante? Os seus holocaustos não são aceitáveis nem me agradam as suas ofertas".

[[v24-6-21]]

^<<v24-6-21,21>>^ Assim diz o Senhor: "Estou colocando obstáculos diante deste povo. Pais e filhos tropeçarão neles; vizinhos e amigos perecerão".

[[v24-6-22]]

^<<v24-6-22,22>>^ Assim diz o Senhor: "Veja! Um exército vem do Norte; uma grande nação está sendo mobilizada desde os confins da terra.

[[v24-6-23]]

^<<v24-6-23,23>>^ Eles empunham o arco e a lança; são cruéis e sem misericórdia, e o barulho que fazem é como o bramido do mar. Vêm montando os seus cavalos em formação de batalha, para atacá-la, ó cidade de Sião. "

[[v24-6-24]]

^<<v24-6-24,24>>^ Ouvimos os relatos sobre eles, e as nossas mãos amoleceram. A angústia tomou conta de nós, dores como as da mulher que está dando à luz.

[[v24-6-25]]

^<<v24-6-25,25>>^ Não saiam aos campos nem andem pelas estradas, pois o inimigo traz a espada e há terror por todos os lados.

[[v24-6-26]]

^<<v24-6-26,26>>^ Ó minha filha, meu povo, ponha vestes de lamento e revolva-se em cinza. Lamente-se com choro amargurado, como quem chora por um filho único, pois subitamente o destruidor virá sobre nós.

[[v24-6-27]]

^<<v24-6-27,27>>^ "Eu o designei como examinador de metais, provador do meu povo para que você examine e ponha à prova a conduta deles.

[[v24-6-28]]

^<<v24-6-28,28>>^ Todos eles são rebeldes obstinados, e propagadores de calúnias. Estão endurecidos como o bronze e o ferro. Todos eles são corruptos.

[[v24-6-29]]

^<<v24-6-29,29>>^ O fole sopra com força para separar o chumbo com o fogo, mas o refino prossegue em vão; os ímpios não são expurgados.

[[v24-6-30]]

^<<v24-6-30,30>>^ São chamados prata rejeitada, porque o Senhor os rejeitou. "

'''

xref:024-jeremias/024-jeremias-005.adoc#v24-5-0[&#60; Capítulo Anterior] | <<v24-6-0,Topo>> | xref:024-jeremias/024-jeremias-007.adoc#v24-7-0[Próximo Capítulo &#62;]