include::./index.adoc[]

[[v24-33-0]]
=== Jeremias, 33
// nvi ?, NVI - Nova Versão Internacional

[[v24-33-1]]

^<<v24-33-1,1>>^ Jeremias ainda estava preso no pátio da guarda quando o Senhor lhe dirigiu a palavra pela segunda vez:

[[v24-33-2]]

^<<v24-33-2,2>>^ "Assim diz o Senhor que fez a terra, o Senhor que a formou e a firmou; seu nome é Senhor:

[[v24-33-3]]

^<<v24-33-3,3>>^ ‘Clame a mim e eu responderei e lhe direi coisas grandiosas e insondáveis que você não conhece’.

[[v24-33-4]]

^<<v24-33-4,4>>^ Porque assim diz o Senhor, o Deus de Israel, a respeito das casas desta cidade e dos palácios reais de Judá, que foram derrubados para servirem de defesa contra as rampas de cerco e a espada,

[[v24-33-5]]

^<<v24-33-5,5>>^ na luta contra os babilônios: ‘Elas ficarão cheias de cadáveres dos homens que matarei no meu furor. Ocultarei desta cidade o meu rosto por causa de toda a sua maldade.

[[v24-33-6]]

^<<v24-33-6,6>>^ " ‘Todavia, trarei restauração e cura para ela; curarei o meu povo e lhe darei muita prosperidade e segurança.

[[v24-33-7]]

^<<v24-33-7,7>>^ Mudarei a sorte de Judá e de Israel e os reconstruirei como antigamente.

[[v24-33-8]]

^<<v24-33-8,8>>^ Eu os purificarei de todo o pecado que cometeram contra mim e perdoarei todos os seus pecados de rebelião contra mim.

[[v24-33-9]]

^<<v24-33-9,9>>^ Então Jerusalém será para mim uma fonte de alegria, de louvor e de glória, diante de todas as nações da terra que ouvirem acerca de todos os benefícios que faço por ela. Elas temerão e tremerão diante da paz e da prosperidade que eu lhe concedo’.

[[v24-33-10]]

^<<v24-33-10,10>>^ "Assim diz o Senhor: ‘Vocês dizem que este lugar está devastado, e ficará sem homens nem animais. Contudo, nas cidades de Judá e nas ruas de Jerusalém, que estão devastadas, desabitadas, sem homens nem animais, mais uma vez se ouvirão

[[v24-33-11]]

^<<v24-33-11,11>>^ as vozes de júbilo e de alegria, do noivo e da noiva, e as vozes daqueles que trazem ofertas de ação de graças para o templo do Senhor, dizendo: "Dêem graças ao Senhor dos Exércitos, pois ele é bom; o seu amor leal dura para sempre". Porque eu mudarei a sorte desta terra como antigamente’, declara o Senhor.

[[v24-33-12]]

^<<v24-33-12,12>>^ "Assim diz o Senhor dos Exércitos: ‘Neste lugar desolado, sem homens nem animais, haverá novamente pastagens onde os pastores farão descansar os seus rebanhos, em todas as suas cidades.

[[v24-33-13]]

^<<v24-33-13,13>>^ Tanto nas cidades dos montes, da Sefelá, do Neguebe e do território de Benjamim, como nos povoados ao redor de Jerusalém e nas cidades de Judá, novamente passarão ovelhas sob as mãos daquele que as conta’, diz o Senhor.

[[v24-33-14]]

^<<v24-33-14,14>>^ " ‘Dias virão’, declara o Senhor, ‘em que cumprirei a promessa que fiz à comunidade de Israel e à comunidade de Judá.

[[v24-33-15]]

^<<v24-33-15,15>>^ " ‘Naqueles dias e naquela época farei brotar um Renovo justo da linhagem de Davi; ele fará o que é justo e certo na terra.

[[v24-33-16]]

^<<v24-33-16,16>>^ Naqueles dias Judá será salva e Jerusalém viverá em segurança, e este é o nome pelo qual ela será chamada: O Senhor é a Nossa Justiça’.

[[v24-33-17]]

^<<v24-33-17,17>>^ "Porque assim diz o Senhor: ‘Davi jamais deixará de ter um descendente que se assente no trono de Israel,

[[v24-33-18]]

^<<v24-33-18,18>>^ nem os sacerdotes, que são levitas, deixarão de ter descendente que esteja diante de mim para oferecer, continuamente, holocaustos, queimar ofertas de cereal e apresentar sacrifícios’ ".

[[v24-33-19]]

^<<v24-33-19,19>>^ O Senhor dirigiu a palavra a Jeremias:

[[v24-33-20]]

^<<v24-33-20,20>>^ "Assim diz o Senhor: ‘Se vocês puderem romper a minha aliança com o dia e a minha aliança com a noite, de modo que nem o dia nem a noite aconteçam no tempo que lhes está determinado,

[[v24-33-21]]

^<<v24-33-21,21>>^ então poderá ser quebrada a minha aliança com o meu servo Davi, e neste caso ele não mais terá um descendente que reine no seu trono; e também será quebrada a minha aliança com os levitas que são sacerdotes e que me servem.

[[v24-33-22]]

^<<v24-33-22,22>>^ Farei os descendentes do meu servo Davi e os levitas, que me servem, tão numerosos como as estrelas do céu e incontáveis como a areia das praias do mar’ ".

[[v24-33-23]]

^<<v24-33-23,23>>^ O Senhor dirigiu a palavra a Jeremias:

[[v24-33-24]]

^<<v24-33-24,24>>^ "Você reparou que essas pessoas estão dizendo que o Senhor rejeitou os dois reinos que tinha escolhido? Por isso desprezam o meu povo e não mais o considera como nação.

[[v24-33-25]]

^<<v24-33-25,25>>^ Assim diz o Senhor: ‘Se a minha aliança com o dia e com a noite não mais vigorasse, se eu não tivesse estabelecido as leis fixas do céu e da terra,

[[v24-33-26]]

^<<v24-33-26,26>>^ então eu rejeitaria os descendentes de Jacó e do meu servo Davi, e não escolheria um dos seus descendentes para que governasse os descendentes de Abraão, de Isaque e de Jacó. Mas eu restaurarei a sorte deles e lhes manifestarei a minha compaixão’ ".

'''

xref:024-jeremias/024-jeremias-032.adoc#v24-32-0[&#60; Capítulo Anterior] | <<v24-33-0,Topo>> | xref:024-jeremias/024-jeremias-034.adoc#v24-34-0[Próximo Capítulo &#62;]