include::./index.adoc[]

[[v24-27-0]]
=== Jeremias, 27
// nvi ?, NVI - Nova Versão Internacional

[[v24-27-1]]

^<<v24-27-1,1>>^ No início do reinado de Zedequias, filho de Josias, rei de Judá, veio esta palavra a Jeremias da parte do Senhor:

[[v24-27-2]]

^<<v24-27-2,2>>^ Assim me ordenou o Senhor: "Faça para você um jugo com cordas e madeira e ponha-o sobre o pescoço.

[[v24-27-3]]

^<<v24-27-3,3>>^ Depois mande uma mensagem aos reis de Edom, de Moabe, de Amom, de Tiro e de Sidom, por meio dos embaixadores que vieram a Jerusalém para ver Zedequias, rei de Judá.

[[v24-27-4]]

^<<v24-27-4,4>>^ Esta é a mensagem que deverão transmitir aos seus senhores: Assim diz o Senhor dos Exércitos, o Deus de Israel:

[[v24-27-5]]

^<<v24-27-5,5>>^ ‘Eu fiz a terra, os seres humanos e os animais que nela estão, com o meu grande poder e com meu braço estendido, e eu a dou a quem eu quiser.

[[v24-27-6]]

^<<v24-27-6,6>>^ Agora, sou eu mesmo que entrego todas essas nações nas mãos do meu servo Nabucodonosor, rei da Babilônia; sujeitei a ele até mesmo os animais selvagens.

[[v24-27-7]]

^<<v24-27-7,7>>^ Todas as nações estarão sujeitas a ele, a seu filho e a seu neto; até que chegue a hora em que a terra dele seja subjugada por muitas nações e por reis poderosos.

[[v24-27-8]]

^<<v24-27-8,8>>^ " ‘Se, porém, alguma nação ou reino não se sujeitar a Nabucodonosor, rei da Babilônia, nem colocar o pescoço sob o seu jugo, eu castigarei aquela nação com a guerra, a fome e a peste’, declara o Senhor, ‘e por meio dele eu a destruirei completamente.

[[v24-27-9]]

^<<v24-27-9,9>>^ Não ouçam os seus profetas, os seus adivinhos, os seus intérpretes de sonhos, os seus médiuns e os seus feiticeiros, os quais lhes dizem para não se sujeitar ao rei da Babilônia.

[[v24-27-10]]

^<<v24-27-10,10>>^ Porque são mentiras o que eles profetizam para vocês, o que os levará para longe de sua terra. Eu banirei vocês, e vocês perecerão.

[[v24-27-11]]

^<<v24-27-11,11>>^ Mas, se alguma nação colocar o pescoço sob o jugo do rei da Babilônia e a ele se sujeitar, então deixarei aquela nação permanecer na sua própria terra para cultivá-la e nela viver’, declara o Senhor".

[[v24-27-12]]

^<<v24-27-12,12>>^ Entreguei a mesma mensagem a Zedequias, rei de Judá, dizendo-lhe: Coloquem o pescoço sob o jugo do rei da Babilônia, sujeitem-se a ele e ao seu povo, e vocês viverão.

[[v24-27-13]]

^<<v24-27-13,13>>^ Por que razão você e o seu povo morreriam pela guerra, pela fome e pela peste, com as quais o Senhor ameaça a nação que não se sujeitar ao rei da Babilônia?

[[v24-27-14]]

^<<v24-27-14,14>>^ Não dêem atenção às palavras dos profetas que dizem que vocês não devem sujeitar-se ao rei da Babilônia; estão profetizando mentiras.

[[v24-27-15]]

^<<v24-27-15,15>>^ "Eu não os enviei! ", declara o Senhor. "Eles profetizam mentiras em meu nome. Por isso, eu banirei vocês, e vocês perecerão juntamente com os profetas que lhes estão profetizando".

[[v24-27-16]]

^<<v24-27-16,16>>^ Então eu disse aos sacerdotes e a todo este povo: Assim diz o Senhor: "Não ouçam os seus profetas que dizem que em breve os utensílios do templo do Senhor serão trazidos de volta da Babilônia. Eles estão profetizando mentiras".

[[v24-27-17]]

^<<v24-27-17,17>>^ Não os ouçam. Sujeitem-se ao rei da Babilônia, e vocês viverão. Por que deveria esta cidade ficar em ruínas?

[[v24-27-18]]

^<<v24-27-18,18>>^ Se eles são profetas e têm a palavra do Senhor, que implorem ao Senhor dos Exércitos, pedindo que os utensílios que restam no templo do Senhor no palácio do rei de Judá e em Jerusalém não sejam levados para a Babilônia.

[[v24-27-19]]

^<<v24-27-19,19>>^ Porque assim diz o Senhor dos Exércitos acerca das colunas, do tanque, dos suportes e dos outros utensílios que foram deixados nesta cidade,

[[v24-27-20]]

^<<v24-27-20,20>>^ os quais Nabucodonosor, rei da Babilônia, não levou consigo de Jerusalém para a Babilônia, quando exilou Joaquim, filho de Jeoaquim, rei de Judá, com os nobres de Judá e de Jerusalém.

[[v24-27-21]]

^<<v24-27-21,21>>^ Sim, assim diz o Senhor dos Exércitos, Deus de Israel, acerca dos utensílios que restaram no templo do Senhor e no palácio do rei de Judá e em Jerusalém:

[[v24-27-22]]

^<<v24-27-22,22>>^ "Serão levados para a Babilônia e ali ficarão até o dia em que eu os quiser buscar", declara o Senhor. "Então os trarei de volta e os restabelecerei a este lugar".

'''

xref:024-jeremias/024-jeremias-026.adoc#v24-26-0[&#60; Capítulo Anterior] | <<v24-27-0,Topo>> | xref:024-jeremias/024-jeremias-028.adoc#v24-28-0[Próximo Capítulo &#62;]