include::./index.adoc[]

[[v24-52-0]]
=== Jeremias, 52
// nvi ?, NVI - Nova Versão Internacional

[[v24-52-1]]

^<<v24-52-1,1>>^ Zedequias tinha vinte e um anos quando se tornou rei, e reinou onze anos em Jerusalém. O nome de sua mãe era Hamutal, filha de Jeremias, de Libna.

[[v24-52-2]]

^<<v24-52-2,2>>^ Ele fez o que o Senhor reprova, assim como fez Jeoaquim.

[[v24-52-3]]

^<<v24-52-3,3>>^ A ira do Senhor tem sido provocada em Jerusalém e em Judá de tal forma que tenho que tirá-los da minha frente. Zedequias se rebelou contra o rei da Babilônia.

[[v24-52-4]]

^<<v24-52-4,4>>^ Então, no nono ano do reinado de Zedequias, no décimo mês, Nabucodonosor, rei da Babilônia, marchou contra Jerusalém com todo o seu exército. Acamparam fora da cidade e construíram torres de assalto ao redor dela.

[[v24-52-5]]

^<<v24-52-5,5>>^ A cidade ficou sob cerco até o décimo primeiro ano do rei Zedequias.

[[v24-52-6]]

^<<v24-52-6,6>>^ Ao chegar o nono dia do quarto mês a fome era tão severa que não havia comida para o povo.

[[v24-52-7]]

^<<v24-52-7,7>>^ Então o muro da cidade foi rompido. O rei e todos os soldados fugiram e saíram da cidade, à noite, na direção do jardim real, pela porta entre os dois muros, embora os babilônios estivessem cercando a cidade. Foram para a Arabá,

[[v24-52-8]]

^<<v24-52-8,8>>^ mas os babilônios perseguiram o rei Zedequias e o alcançaram na planície de Jericó. Todos os seus soldados se separaram dele e se dispersaram,

[[v24-52-9]]

^<<v24-52-9,9>>^ e ele foi capturado. Ele foi levado ao rei da Babilônia em Ribla, na terra de Hamate, que o sentenciou.

[[v24-52-10]]

^<<v24-52-10,10>>^ Em Ribla, o rei da Babilônia mandou executar os filhos de Zedequias diante de seus olhos, e também matou todos os nobres de Judá.

[[v24-52-11]]

^<<v24-52-11,11>>^ Então mandou furar os olhos de Zedequias e prendê-lo com correntes de bronze e o levou para a Babilônia, onde o manteve na prisão até o dia de sua morte.

[[v24-52-12]]

^<<v24-52-12,12>>^ No décimo dia do quinto mês, no décimo nono ano de Nabucodonosor, rei da Babilônia, Nebuzaradã, comandante da guarda imperial, que servia o rei da Babilônia, veio a Jerusalém.

[[v24-52-13]]

^<<v24-52-13,13>>^ Ele incendiou o templo do Senhor, o palácio real e todas as casas de Jerusalém. Todo o edifício importante foi incendiado por ele.

[[v24-52-14]]

^<<v24-52-14,14>>^ Todo o exército babilônio, sob o comandante da guarda imperial, derrubou todos os muros em torno de Jerusalém.

[[v24-52-15]]

^<<v24-52-15,15>>^ Nebuzaradã, o comandante da guarda imperial, deportou para a Babilônia alguns dos mais pobres e o povo que restou na cidade, juntamente com o restante dos artesãos e aqueles que tinham se rendido ao rei da Babilônia.

[[v24-52-16]]

^<<v24-52-16,16>>^ Mas Nebuzaradã deixou para trás o restante dos mais pobres da terra para trabalhar nas vinhas e campos.

[[v24-52-17]]

^<<v24-52-17,17>>^ Os babilônios despedaçaram as colunas de bronze, os estrados móveis e o mar de bronze que ficavam no templo do Senhor e levaram todo o bronze para a Babilônia.

[[v24-52-18]]

^<<v24-52-18,18>>^ Também levaram embora as panelas, pás, tesouras de pavio, bacias de aspersão, tigelas e todos os utensílios de bronze usados no serviço do templo.

[[v24-52-19]]

^<<v24-52-19,19>>^ O comandante da guarda imperial levou embora as pias, os incensários, as bacias de aspersão, as panelas, os candeeiros, as tigelas e as bacias usadas para as ofertas derramadas, tudo que era feito de ouro puro ou de prata.

[[v24-52-20]]

^<<v24-52-20,20>>^ O bronze tirado das duas colunas, o mar e os doze touros de bronze debaixo dele, e os estrados móveis, que o rei Salomão fizera para o templo do Senhor, eram mais do que se podia pesar.

[[v24-52-21]]

^<<v24-52-21,21>>^ Cada uma das colunas tinha oito metros e dez centímetros de altura e cinco metros e quarenta centímetros de circunferência; cada uma tinha quadro dedos de espessura e era oca.

[[v24-52-22]]

^<<v24-52-22,22>>^ O capitel de bronze no alto de uma coluna tinha dois metros e vinte e cinco centímetros de altura e era ornamentado com um trabalho entrelaçado e romãs de bronze em volta, tudo de bronze. A outra coluna, com suas romãs, era igual.

[[v24-52-23]]

^<<v24-52-23,23>>^ Havia noventa e seis romãs nos lados; o número total de romãs acima do trabalho entrelaçado ao redor era de cem.

[[v24-52-24]]

^<<v24-52-24,24>>^ O comandante da guarda tomou como prisioneiros o sumo sacerdote Seraías, o sacerdote adjunto Sofonias e os três guardas das portas.

[[v24-52-25]]

^<<v24-52-25,25>>^ Dos que ainda estavam na cidade, tomou o oficial encarregado dos homens de combate e sete conselheiros reais. Também tomou o secretário que era o oficial maior encarregado do alistamento do povo da terra e sessenta de seus homens que foram encontrados na cidade.

[[v24-52-26]]

^<<v24-52-26,26>>^ O comandante Nebuzaradã tomou todos eles e os levou ao rei da Babilônia em Ribla.

[[v24-52-27]]

^<<v24-52-27,27>>^ Ali em Ribla, na terra de Hamate, o rei fez com que fossem executados. Assim Judá foi para o cativeiro, longe de sua terra.

[[v24-52-28]]

^<<v24-52-28,28>>^ Este é o número dos que Nebuzaradã levou para o exílio: no sétimo ano, 3. 023 judeus;

[[v24-52-29]]

^<<v24-52-29,29>>^ no décimo oitavo ano de Nabucodonosor, 832 de Jerusalém;

[[v24-52-30]]

^<<v24-52-30,30>>^ em seu vigésimo terceiro ano, 745 judeus levados ao exílio pelo comandante da guarda imperial Nebuzaradã. Foram ao todo 4. 600 judeus.

[[v24-52-31]]

^<<v24-52-31,31>>^ No ano trinta e sete do exílio do rei Joaquim de Judá, no ano em que Evil-Merodaque tornou-se rei de Babilônia, ele libertou o rei Joaquim de Judá da prisão no dia vinte e cinco do décimo segundo mês.

[[v24-52-32]]

^<<v24-52-32,32>>^ Ele falou bondosamente com ele e deu-lhe um assento de honra mais elevado do que os dos outros reis que estavam com ele na Babilônia.

[[v24-52-33]]

^<<v24-52-33,33>>^ Desse modo Joaquim tirou as roupas da prisão e pelo resto da vida comeu à mesa do rei.

[[v24-52-34]]

^<<v24-52-34,34>>^ Dia após dia o rei da Babilônia deu a Joaquim uma pensão diária enquanto ele viveu, até o dia de sua morte.

'''

xref:024-jeremias/024-jeremias-051.adoc#v24-51-0[&#60; Capítulo Anterior] | <<v24-52-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-001.adoc#v25-1-0[Próximo Capítulo &#62;]