include::./index.adoc[]

[[v24-5-0]]
=== Jeremias, 5
// nvi ?, NVI - Nova Versão Internacional

[[v24-5-1]]

^<<v24-5-1,1>>^ "Percorram as ruas de Jerusalém, olhem e observem. Procurem em suas praças para ver se podem encontrar alguém que aja com honestidade e que busque a verdade. Então eu perdoarei a cidade.

[[v24-5-2]]

^<<v24-5-2,2>>^ Embora digam: ‘Juro pelo nome do Senhor’, ainda assim estão jurando falsamente. "

[[v24-5-3]]

^<<v24-5-3,3>>^ Senhor, não é fidelidade que os teus olhos procuram? Tu os feriste, mas eles nada sentiram; tu os deixaste esgotados, mas eles recusaram a correção. Endureceram o rosto, mais que a rocha e recusaram arrepender-se.

[[v24-5-4]]

^<<v24-5-4,4>>^ Pensei: Esses são apenas pobres e ignorantes, não conhecem o caminho do Senhor, as exigências do seu Deus.

[[v24-5-5]]

^<<v24-5-5,5>>^ Irei aos nobres e falarei com eles, pois, sem dúvida, eles conhecem o caminho do Senhor, as exigências do seu Deus. Mas todos eles também quebraram o jugo e romperam as amarras.

[[v24-5-6]]

^<<v24-5-6,6>>^ Por isso, um leão da floresta os atacará, um lobo da estepe os arrasará, um leopardo ficará à espreita, nos arredores das suas cidades, para despedaçar qualquer pessoa que delas sair. Porque a rebeldia deles é grande e muitos são os seus desvios.

[[v24-5-7]]

^<<v24-5-7,7>>^ "Por que deveria eu perdoar-lhe isso? Seus filhos me abandonaram e juraram por aqueles que não são deuses. Embora eu tenha suprido as suas necessidades, eles cometeram adultério e freqüentaram as casas de prostituição.

[[v24-5-8]]

^<<v24-5-8,8>>^ Eles são garanhões bem-alimentados e excitados, cada um relinchando para a mulher do próximo.

[[v24-5-9]]

^<<v24-5-9,9>>^ Não devo eu castigá-los por isso? ", pergunta o Senhor. "Não devo eu vingar-me de uma nação como esta?

[[v24-5-10]]

^<<v24-5-10,10>>^ "Vão por entre as suas vinhas e destruam-nas, mas não acabem totalmente com elas. Cortem os seus ramos, pois eles não pertencem ao Senhor.

[[v24-5-11]]

^<<v24-5-11,11>>^ Porque a comunidade de Israel e a comunidade de Judá têm-me traído", declara o Senhor.

[[v24-5-12]]

^<<v24-5-12,12>>^ Mentiram acerca do Senhor, dizendo: "Ele não vai fazer nada! Nenhum mal nos acontecerá; jamais veremos espada ou fome.

[[v24-5-13]]

^<<v24-5-13,13>>^ Os profetas não passam de vento, e a palavra não está neles; por isso aconteça com eles o que dizem".

[[v24-5-14]]

^<<v24-5-14,14>>^ Portanto, assim diz o Senhor dos Exércitos: "Porque falaram essas palavras, farei com que as minhas palavras em sua boca sejam fogo, e este povo seja a lenha que o fogo consome.

[[v24-5-15]]

^<<v24-5-15,15>>^ "Ó comunidade de Israel", declara o Senhor. "estou trazendo de longe uma nação para atacá-la: uma nação muito antiga e invencível, uma nação cuja língua você não conhece e cuja fala você não entende.

[[v24-5-16]]

^<<v24-5-16,16>>^ Sua aljava é como um túmulo aberto; toda ela é composta de guerreiros.

[[v24-5-17]]

^<<v24-5-17,17>>^ Devorarão as suas colheitas e os seus alimentos; devorarão os seus filhos e as suas filhas; devorarão as suas ovelhas e os seus bois; devorarão as suas videiras e as suas figueiras. Destruirão pela espada as cidades fortificadas nas quais vocês confiam.

[[v24-5-18]]

^<<v24-5-18,18>>^ "Contudo, mesmo naqueles dias não os destruirei completamente", declara o Senhor.

[[v24-5-19]]

^<<v24-5-19,19>>^ "E, quando perguntarem: ‘Por que o Senhor, o nosso Deus, fez isso conosco? ’, você lhes dirá: ‘Assim como vocês me abandonaram e serviram deuses estrangeiros em sua própria terra, também agora vocês servirão estrangeiros numa terra que não é de vocês’.

[[v24-5-20]]

^<<v24-5-20,20>>^ "Anunciem isto à comunidade de Jacó e proclamem-no em Judá:

[[v24-5-21]]

^<<v24-5-21,21>>^ Ouçam isto, vocês, povo tolo e insensato, que têm olhos mas não vêem, têm ouvidos mas não ouvem:

[[v24-5-22]]

^<<v24-5-22,22>>^ Acaso vocês não me temem? ", pergunta o Senhor. "Não tremem diante da minha presença? Porque fui eu que fiz da areia um limite para o mar, um decreto eterno que ele não pode ultrapassar. As ondas podem quebrar, mas não podem prevalecer, podem bramir, mas não podem ultrapassá-lo.

[[v24-5-23]]

^<<v24-5-23,23>>^ Mas este povo tem coração obstinado e rebelde; eles se afastaram e foram embora.

[[v24-5-24]]

^<<v24-5-24,24>>^ Não dizem no seu íntimo: ‘Temamos o Senhor, o nosso Deus: aquele que dá as chuvas do outono e da primavera no tempo certo, e assegura-nos as semanas certas da colheita’.

[[v24-5-25]]

^<<v24-5-25,25>>^ Mas os pecados de vocês têm afastado essas coisas; as faltas de vocês os têm privado desses bens.

[[v24-5-26]]

^<<v24-5-26,26>>^ "Há ímpios no meio do meu povo: homens que ficam à espreita como num esconderijo de caçadores de pássaros; preparam armadilhas para capturar gente.

[[v24-5-27]]

^<<v24-5-27,27>>^ Suas casas estão cheias de engano, como gaiolas cheias de pássaros. E assim eles se tornaram poderosos e ricos,

[[v24-5-28]]

^<<v24-5-28,28>>^ estão gordos e bem-alimentados. Não há limites para as suas obras más. Não se empenham pela causa do órfão, nem defendem os direitos do pobre.

[[v24-5-29]]

^<<v24-5-29,29>>^ Não devo eu castigá-los? ", pergunta o Senhor. "Não devo eu vingar-me de uma nação como essa?

[[v24-5-30]]

^<<v24-5-30,30>>^ "Uma coisa espantosa e horrível acontece nesta terra:

[[v24-5-31]]

^<<v24-5-31,31>>^ Os profetas profetizam mentiras, os sacerdotes governam por sua própria autoridade, e o meu povo gosta dessas coisas. Mas o que vocês farão quando tudo isso chegar ao fim?

'''

xref:024-jeremias/024-jeremias-004.adoc#v24-4-0[&#60; Capítulo Anterior] | <<v24-5-0,Topo>> | xref:024-jeremias/024-jeremias-006.adoc#v24-6-0[Próximo Capítulo &#62;]