include::./index.adoc[]

[[v24-31-0]]
=== Jeremias, 31
// nvi ?, NVI - Nova Versão Internacional

[[v24-31-1]]

^<<v24-31-1,1>>^ "Naquele tempo", diz o Senhor, "serei o Deus de todas as famílias de Israel, e eles serão o meu povo. "

[[v24-31-2]]

^<<v24-31-2,2>>^ Assim diz o Senhor: "O povo que escapou da morte achou favor no deserto". Quando Israel buscava descanso,

[[v24-31-3]]

^<<v24-31-3,3>>^ o Senhor lhe apareceu no passado, dizendo: "Eu a amei com amor eterno; com amor leal a atrai.

[[v24-31-4]]

^<<v24-31-4,4>>^ Eu a edificarei mais uma vez, ó virgem, Israel! Você será reconstruída! Mais uma vez você se enfeitará com guizos e sairá dançando com os que se alegram.

[[v24-31-5]]

^<<v24-31-5,5>>^ De novo você plantará videiras nas colinas de Samaria; videiras que os lavradores que as tinham plantado antes profanaram.

[[v24-31-6]]

^<<v24-31-6,6>>^ Porque vai chegando o dia em que os sentinelas gritarão nas colinas de Efraim: ‘Venham e subamos a Sião, à presença do Senhor, do nosso Deus’ ".

[[v24-31-7]]

^<<v24-31-7,7>>^ Assim diz o Senhor: "Cantem de alegria por causa de Jacó; gritem, exaltando a principal das nações! Proclamem e dêem louvores dizendo: ‘O Senhor salvou o seu povo, o remanescente de Israel’.

[[v24-31-8]]

^<<v24-31-8,8>>^ Vejam, eu os trarei da terra do norte e os reunirei dos confins da terra. Entre eles estarão o cego e o aleijado, mulheres grávidas e em trabalho de parto; uma grande multidão voltará.

[[v24-31-9]]

^<<v24-31-9,9>>^ Voltarão com choro, mas eu os conduzirei em consolações. Eu os conduzirei às correntes de água por um caminho plano, onde não tropeçarão, porque sou pai para Israel e Efraim é o meu filho mais velho.

[[v24-31-10]]

^<<v24-31-10,10>>^ "Ouçam a palavra do Senhor, ó nações, e proclamem nas ilhas distantes: ‘Aquele que dispersou Israel os reunirá e, como pastor, vigiará o seu rebanho’.

[[v24-31-11]]

^<<v24-31-11,11>>^ O Senhor resgatou Jacó e o libertou das mãos do que é mais forte do que ele.

[[v24-31-12]]

^<<v24-31-12,12>>^ Eles virão e cantarão de alegria nos altos de Sião; ficarão radiantes de alegria pelos muitos bens dados pelo Senhor: o cereal, o vinho novo, o azeite puro, as crias das ovelhas e das vacas. Serão como um jardim bem regado, e não mais se entristecerão.

[[v24-31-13]]

^<<v24-31-13,13>>^ Então as moças dançarão de alegria, como também os jovens e os velhos. Transformarei o lamento deles em júbilo; eu lhes darei consolo e alegria em vez de tristeza.

[[v24-31-14]]

^<<v24-31-14,14>>^ Satisfarei os sacerdotes com fartura; e o meu povo será saciado pela minha bondade", declara o Senhor.

[[v24-31-15]]

^<<v24-31-15,15>>^ Assim diz o Senhor: "Ouve-se uma voz em Ramá, pranto e amargo choro; é Raquel que chora por seus filhos e recusa ser consolada, porque os seus filhos já não existem".

[[v24-31-16]]

^<<v24-31-16,16>>^ Assim diz o Senhor: "Contenha o seu choro e as suas lágrimas, pois o seu sofrimento será recompensado", declara o Senhor. "Eles voltarão da terra do inimigo.

[[v24-31-17]]

^<<v24-31-17,17>>^ Por isso há esperança para o seu futuro", declara o Senhor. "Seus filhos voltarão para a sua pátria.

[[v24-31-18]]

^<<v24-31-18,18>>^ "Ouvi claramente Efraim lamentando-se: ‘Tu me disciplinaste como a um bezerro indomado, e fui disciplinado. Traze-me de volta, e voltarei, porque tu és o Senhor, o meu Deus.

[[v24-31-19]]

^<<v24-31-19,19>>^ De fato, depois de desviar-me, eu me arrependi; depois que entendi, bati no meu peito. Estou envergonhado e humilhado porque trago sobre mim a desgraça da minha juventude’.

[[v24-31-20]]

^<<v24-31-20,20>>^ Não é Efraim o meu filho querido? O filho em quem tenho prazer? Cada vez que eu falo sobre ele, mais intensamente me lembro dele. Por isso o meu coração por ele anseia; tenho por ele grande compaixão", declara o Senhor.

[[v24-31-21]]

^<<v24-31-21,21>>^ "Coloque marcos e ponha sinais nas estradas, Preste atenção no caminho que você trilhou. Volte, ó Virgem, Israel! Volte para as suas cidades.

[[v24-31-22]]

^<<v24-31-22,22>>^ Até quando você vagará, ó filha rebelde? O Senhor criou algo novo nesta terra: uma mulher abraça um guerreiro. "

[[v24-31-23]]

^<<v24-31-23,23>>^ Assim diz o Senhor dos Exércitos, o Deus de Israel: "Quando eu os trouxer de volta do cativeiro, o povo de Judá e de suas cidades dirá novamente: ‘O Senhor a abençoe, ó morada justa, ó monte sagrado’.

[[v24-31-24]]

^<<v24-31-24,24>>^ O povo viverá em Judá e em todas as suas cidades, tanto os lavradores como os que conduzem os rebanhos.

[[v24-31-25]]

^<<v24-31-25,25>>^ Restaurarei o exausto e saciarei o enfraquecido".

[[v24-31-26]]

^<<v24-31-26,26>>^ Então acordei e olhei em redor. Meu sono tinha sido agradável.

[[v24-31-27]]

^<<v24-31-27,27>>^ "Virão dias", diz o Senhor, "em que semearei na comunidade de Israel e na comunidade de Judá homens e animais.

[[v24-31-28]]

^<<v24-31-28,28>>^ Assim como os vigiei para arrancar e despedaçar, para derrubar, destruir e trazer a desgraça, também os vigiarei para edificar e plantar", declara o Senhor.

[[v24-31-29]]

^<<v24-31-29,29>>^ "Naqueles dias não se dirá mais: ‘Os pais comeram uvas verdes, e os dentes dos filhos se mancharam’.

[[v24-31-30]]

^<<v24-31-30,30>>^ Ao contrário, cada um morrerá por causa do seu próprio pecado. Os dentes de todo aquele que comer uvas verdes se mancharam.

[[v24-31-31]]

^<<v24-31-31,31>>^ "Estão chegando os dias", declara o Senhor, "quando farei uma nova aliança com a comunidade de Israel e com a comunidade de Judá".

[[v24-31-32]]

^<<v24-31-32,32>>^ "Não será como a aliança que fiz com os seus antepassados quando os tomei pela mão para tirá-los do Egito; porque quebraram a minha aliança, apesar de eu ser o Senhor deles", diz o Senhor.

[[v24-31-33]]

^<<v24-31-33,33>>^ "Esta é a aliança que farei com a comunidade de Israel depois daqueles dias", declara o Senhor: "Porei a minha lei no íntimo deles e a escreverei nos seus corações. Serei o Deus deles, e eles serão o meu povo.

[[v24-31-34]]

^<<v24-31-34,34>>^ Ninguém mais ensinará ao seu próximo nem ao seu irmão, dizendo: ‘Conheça ao Senhor’, porque todos eles me conhecerão, desde o menor até o maior", diz o Senhor. "Porque eu lhes perdoarei a maldade e não me lembrarei mais dos seus pecados. "

[[v24-31-35]]

^<<v24-31-35,35>>^ Assim diz o Senhor, aquele que designou o sol para brilhar de dia, que decretou que a lua e as estrelas brilhem de noite, que agita o mar para que as suas ondas rujam; o seu nome é o Senhor dos Exércitos:

[[v24-31-36]]

^<<v24-31-36,36>>^ "Somente se esses decretos desaparecerem de diante de mim", declara o Senhor, "deixarão os descendentes de Israel de ser uma nação diante de mim para sempre".

[[v24-31-37]]

^<<v24-31-37,37>>^ Assim diz o Senhor: "Se os céus em cima puderem ser medidos, e os alicerces da terra embaixo puderem ser sondados, então eu rejeitarei os descendentes de Israel, por causa de tudo o que eles têm feito", diz o Senhor.

[[v24-31-38]]

^<<v24-31-38,38>>^ "Estão chegando os dias", declara o Senhor, "em que esta cidade será reconstruída para o Senhor, desde a torre de Hananeel até à porta da Esquina.

[[v24-31-39]]

^<<v24-31-39,39>>^ A corda de medir será estendida diretamente até a colina de Garebe, indo na direção de Goa.

[[v24-31-40]]

^<<v24-31-40,40>>^ Todo o vale, onde cadáveres e cinzas são jogados, e todos os terraços que dão para o vale do Cedrom a leste, até a esquina da porta dos Cavalos, serão consagrados ao Senhor. A cidade nunca mais será arrasada ou destruída. "

'''

xref:024-jeremias/024-jeremias-030.adoc#v24-30-0[&#60; Capítulo Anterior] | <<v24-31-0,Topo>> | xref:024-jeremias/024-jeremias-032.adoc#v24-32-0[Próximo Capítulo &#62;]