include::./index.adoc[]

[[v24-47-0]]
=== Jeremias, 47
// nvi ?, NVI - Nova Versão Internacional

[[v24-47-1]]

^<<v24-47-1,1>>^ Esta é a palavra do Senhor que veio ao profeta Jeremias acerca dos filisteus, antes do ataque do faraó a Gaza:

[[v24-47-2]]

^<<v24-47-2,2>>^ Assim diz o Senhor: "Vejam como as águas estão subindo do norte; elas se tornam uma torrente transbordante. Inundarão esta terra e tudo o que nela existe; as cidades e os seus habitantes. O povo clamará, gritarão todos os habitantes desta terra,

[[v24-47-3]]

^<<v24-47-3,3>>^ ao estrondo dos cascos dos seus cavalos galopando, ao barulho dos seus carros de guerra, e ao estampido de suas rodas. Os pais não se voltarão para ajudar seus filhos; pois suas mãos estão fracas.

[[v24-47-4]]

^<<v24-47-4,4>>^ Pois chegou o dia de destruir todos os filisteus e de eliminar todos os sobreviventes que poderiam ajudar Tiro e Sidom. O Senhor destruirá os filisteus, o remanescente da ilha de Caftor.

[[v24-47-5]]

^<<v24-47-5,5>>^ Os habitantes de Gaza rasparam a cabeça; Ascalom está calada. Ó remanescentes da planície, até quando você fará incisões no próprio corpo? "

[[v24-47-6]]

^<<v24-47-6,6>>^ " ‘Ah, espada do Senhor, quando você descansará? Volte à sua bainha, acalme-se e repouse. ’

[[v24-47-7]]

^<<v24-47-7,7>>^ Mas como poderá ela descansar quando o Senhor lhe deu ordens, quando ele lhe ordenou que ataque Ascalom e o litoral? "

'''

xref:024-jeremias/024-jeremias-046.adoc#v24-46-0[&#60; Capítulo Anterior] | <<v24-47-0,Topo>> | xref:024-jeremias/024-jeremias-048.adoc#v24-48-0[Próximo Capítulo &#62;]