include::./index.adoc[]

[[v24-28-0]]
=== Jeremias, 28
// nvi ?, NVI - Nova Versão Internacional

[[v24-28-1]]

^<<v24-28-1,1>>^ No quinto mês daquele mesmo ano, o quarto ano, no início do reinado de Zedequias, rei de Judá, Hananias, filho de Azur, profeta natural de Gibeom, disse-me no templo do Senhor, na presença dos sacerdotes e de todo o povo:

[[v24-28-2]]

^<<v24-28-2,2>>^ "Assim diz o Senhor dos Exércitos, Deus de Israel: ‘Quebrarei o jugo do rei da Babilônia.

[[v24-28-3]]

^<<v24-28-3,3>>^ Em dois anos trarei de volta a este lugar todos os utensílios do templo do Senhor que Nabucodonosor, rei da Babilônia, tirou daqui e levou para a Babilônia.

[[v24-28-4]]

^<<v24-28-4,4>>^ Também trarei de volta para este lugar Joaquim, filho de Jeoaquim, rei de Judá, e todos os exilados de Judá que foram para a Babilônia’, diz o Senhor, ‘pois quebrarei o jugo do rei da Babilônia’ ".

[[v24-28-5]]

^<<v24-28-5,5>>^ Então o profeta Jeremias respondeu ao profeta Hananias diante dos sacerdotes e de todo o povo que estava no templo do Senhor:

[[v24-28-6]]

^<<v24-28-6,6>>^ "Amém! Que assim faça o Senhor! Que o Senhor cumpra as palavras que você profetizou, trazendo os utensílios do templo do Senhor e todos os exilados da Babilônia para este lugar.

[[v24-28-7]]

^<<v24-28-7,7>>^ Entretanto, ouça o que tenho a dizer a você e a todo o povo:

[[v24-28-8]]

^<<v24-28-8,8>>^ Os profetas que precederam a você e a mim, desde os tempos antigos, profetizaram guerra, desgraça e peste contra muitas nações e grandes reinos.

[[v24-28-9]]

^<<v24-28-9,9>>^ Mas o profeta que profetiza prosperidade será reconhecido como verdadeiro enviado do Senhor se aquilo que profetizou se realizar".

[[v24-28-10]]

^<<v24-28-10,10>>^ Então o profeta Hananias tirou o jugo do pescoço de Jeremias e o quebrou,

[[v24-28-11]]

^<<v24-28-11,11>>^ e disse diante de todo o povo: "Assim diz o Senhor: ‘É deste modo que quebrarei o jugo de Nabucodonosor, rei da Babilônia, e o tirarei do pescoço de todas as nações no prazo de dois anos’ ". Diante disso, o profeta Jeremias retirou-se.

[[v24-28-12]]

^<<v24-28-12,12>>^ Depois que o profeta Hananias quebrou o jugo do pescoço do profeta Jeremias, o Senhor dirigiu a palavra a Jeremias:

[[v24-28-13]]

^<<v24-28-13,13>>^ "Vá dizer a Hananias: ‘Assim diz o Senhor: Você quebrou um jugo de madeira, mas em seu lugar você fará um jugo de ferro.

[[v24-28-14]]

^<<v24-28-14,14>>^ Assim diz o Senhor dos Exércitos, o Deus de Israel: Porei um jugo sobre o pescoço de todas essas nações, para fazê-las sujeitas a Nabucodonosor, rei da Babilônia, e elas se sujeitarão a ele. Até mesmo os animais selvagens estarão sujeitos a ele’ ".

[[v24-28-15]]

^<<v24-28-15,15>>^ Disse, pois, o profeta Jeremias ao profeta Hananias: "Escute, Hananias! O Senhor não o enviou, mas assim mesmo você persuadiu esta nação a confiar em mentiras.

[[v24-28-16]]

^<<v24-28-16,16>>^ Por isso, assim diz Senhor: ‘Vou tirá-lo da face da terra. Este ano você morrerá, porque pregou rebelião contra o Senhor’ ".

[[v24-28-17]]

^<<v24-28-17,17>>^ E o profeta Hananias morreu no sétimo mês daquele mesmo ano.

'''

xref:024-jeremias/024-jeremias-027.adoc#v24-27-0[&#60; Capítulo Anterior] | <<v24-28-0,Topo>> | xref:024-jeremias/024-jeremias-029.adoc#v24-29-0[Próximo Capítulo &#62;]