include::./index.adoc[]

[[v24-29-0]]
=== Jeremias, 29
// nvi ?, NVI - Nova Versão Internacional

[[v24-29-1]]

^<<v24-29-1,1>>^ Este é o conteúdo da carta que o profeta Jeremias enviou de Jerusalém aos líderes, que ainda restavam entre os exilados, aos sacerdotes, aos profetas e a todo o povo que Nabucodonosor deportara de Jerusalém para a Babilônia.

[[v24-29-2]]

^<<v24-29-2,2>>^ Isso aconteceu depois que o rei Joaquim e a rainha-mãe, os oficiais do palácio real, os líderes de Judá e Jerusalém, os artesãos e os artífices foram sido deportados de Jerusalém para a Babilônia.

[[v24-29-3]]

^<<v24-29-3,3>>^ Ele enviou a carta por intermédio de Eleasá, filho de Safã, e Gemarias, filho de Hilquias, os quais Zedequias, rei de Judá, mandou a Nabucodonosor, rei da Babilônia. A carta dizia o seguinte:

[[v24-29-4]]

^<<v24-29-4,4>>^ Assim diz o Senhor dos Exércitos, o Deus de Israel, a todos os exilados, que deportei de Jerusalém para a Babilônia:

[[v24-29-5]]

^<<v24-29-5,5>>^ "Construam casas e habitem nelas; plantem jardins e comam de seus frutos.

[[v24-29-6]]

^<<v24-29-6,6>>^ Casem-se e tenham filhos e filhas; escolham mulheres para casar-se com seus filhos e dêem as suas filhas em casamento, para que também tenham filhos e filhas. Multipliquem-se e não diminuam.

[[v24-29-7]]

^<<v24-29-7,7>>^ Busquem a prosperidade da cidade para a qual eu os deportei e orem ao Senhor em favor dela, porque a prosperidade de vocês depende da prosperidade dela".

[[v24-29-8]]

^<<v24-29-8,8>>^ Porque assim diz o Senhor dos Exércitos, o Deus de Israel: "Não deixem que os profetas e adivinhos que há no meio de vocês os enganem. Não dêem atenção aos sonhos que vocês os encorajam a terem.

[[v24-29-9]]

^<<v24-29-9,9>>^ Eles estão profetizando mentiras em meu nome. Eu não os enviei", declara o Senhor.

[[v24-29-10]]

^<<v24-29-10,10>>^ Assim diz o Senhor: "Quando se completarem os setenta anos da Babilônia, eu cumprirei a minha promessa em favor de vocês, de trazê-los de volta para este lugar.

[[v24-29-11]]

^<<v24-29-11,11>>^ Porque sou eu que conheço os planos que tenho para vocês", diz o Senhor, "planos de fazê-los prosperar e não de lhes causar dano, planos de dar-lhes esperança e um futuro.

[[v24-29-12]]

^<<v24-29-12,12>>^ Então vocês clamarão a mim, virão orar a mim, e eu os ouvirei.

[[v24-29-13]]

^<<v24-29-13,13>>^ Vocês me procurarão e me acharão quando me procurarem de todo o coração.

[[v24-29-14]]

^<<v24-29-14,14>>^ Eu me deixarei ser encontrado por vocês", declara o Senhor, "e os trarei de volta do cativeiro. Eu os reunirei de todas as nações e de todos os lugares para onde eu os dispersei, e os trarei de volta para o lugar de onde os deportei", diz o Senhor.

[[v24-29-15]]

^<<v24-29-15,15>>^ Vocês podem dizer: "O Senhor levantou profetas para nós na Babilônia",

[[v24-29-16]]

^<<v24-29-16,16>>^ mas assim diz o Senhor sobre o rei que se assenta no trono de Davi e sobre todo o povo que permanece nesta cidade, seus compatriotas que não foram com vocês para o exílio;

[[v24-29-17]]

^<<v24-29-17,17>>^ assim diz o Senhor dos Exércitos: "Enviarei a guerra, a fome e a peste contra eles; lidarei com eles como se lida com figos ruins, que são intragáveis.

[[v24-29-18]]

^<<v24-29-18,18>>^ Eu os perseguirei com a guerra, a fome e a peste; farei deles objeto de terror para todos os reinos da terra, maldição e exemplo, zombaria e afronta entre todas as nações para onde eu os dispersei.

[[v24-29-19]]

^<<v24-29-19,19>>^ Porque eles não deram atenção às minhas palavras", declara o Senhor, "palavras que lhes enviei pelos meus servos, os profetas. E vocês também não deram atenção! ", diz o Senhor.

[[v24-29-20]]

^<<v24-29-20,20>>^ Ouçam, agora, a palavra do Senhor, todos vocês exilados, que deportei de Jerusalém para a Babilônia!

[[v24-29-21]]

^<<v24-29-21,21>>^ Assim diz o Senhor dos Exércitos, o Deus de Israel, a respeito de Acabe, filho de Colaías, e a respeito de Zedequias, filho de Maaséias, os quais estão profetizando mentiras a vocês em meu nome: "Eu os entregarei nas mãos de Nabucodonosor, rei da Babilônia, e ele os matará diante de vocês.

[[v24-29-22]]

^<<v24-29-22,22>>^ Em razão disso, os exilados de Judá que estão na Babilônia usarão esta maldição: ‘Que o Senhor o trate como tratou Zedequias e Acabe, os quais o rei da Babilônia queimou vivos’.

[[v24-29-23]]

^<<v24-29-23,23>>^ Porque cometeram loucura em Israel: adulteraram com as mulheres de seus amigos e em meu nome falaram mentiras, que eu não ordenei que falassem. Mas eu estou sabendo; sou testemunha disso", declara o Senhor.

[[v24-29-24]]

^<<v24-29-24,24>>^ Diga a Semaías, de Neelam:

[[v24-29-25]]

^<<v24-29-25,25>>^ "Assim diz o Senhor dos Exércitos, o Deus de Israel: Você enviou cartas em seu próprio nome a todo o povo de Jerusalém, a Sofonias, filho do sacerdote Maaséias, e a todos os sacerdotes. Você disse a Sofonias:

[[v24-29-26]]

^<<v24-29-26,26>>^ ‘O Senhor o designou sacerdote em lugar de Joiada como encarregado do templo do Senhor; você deveria prender no tronco, com correntes de ferro, qualquer doido que agisse como profeta.

[[v24-29-27]]

^<<v24-29-27,27>>^ E por que você não repreendeu Jeremias de Anatote, que se apresenta como profeta entre vocês?

[[v24-29-28]]

^<<v24-29-28,28>>^ Ele até mandou esta mensagem para nós que estamos na Babilônia: "O exílio será longo. Construam casas e habitem nelas; plantem jardins e comam de seus frutos" ’ ".

[[v24-29-29]]

^<<v24-29-29,29>>^ O sacerdote Sofonias leu a carta ao profeta Jeremias.

[[v24-29-30]]

^<<v24-29-30,30>>^ Então o Senhor dirigiu a palavra a Jeremias:

[[v24-29-31]]

^<<v24-29-31,31>>^ "Envie esta mensagem a todos os exilados: ‘Assim diz o Senhor sobre Semaías, de Neelam: Embora eu não o tenha enviado, Semaías profetizou a vocês e fez com que vocês cressem numa mentira,

[[v24-29-32]]

^<<v24-29-32,32>>^ por isso, assim diz o Senhor: Castigarei Semaías, de Neelam, e os seus descendentes. Não lhe restará ninguém entre este povo, e ele não verá as coisas boas que vou fazer em favor de meu povo’, declara o Senhor, ‘porque ele pregou rebelião contra o Senhor’ ".

'''

xref:024-jeremias/024-jeremias-028.adoc#v24-28-0[&#60; Capítulo Anterior] | <<v24-29-0,Topo>> | xref:024-jeremias/024-jeremias-030.adoc#v24-30-0[Próximo Capítulo &#62;]