include::./index.adoc[]

[[v24-32-0]]
=== Jeremias, 32
// nvi ?, NVI - Nova Versão Internacional

[[v24-32-1]]

^<<v24-32-1,1>>^ Esta é a palavra que o Senhor dirigiu a Jeremias no décimo ano do reinado de Zedequias, rei de Judá, que foi o ano décimo oitavo de Nabucodonosor.

[[v24-32-2]]

^<<v24-32-2,2>>^ Naquela época, o exército do rei da Babilônia sitiava Jerusalém e o profeta Jeremias estava preso no pátio da guarda, no palácio real de Judá.

[[v24-32-3]]

^<<v24-32-3,3>>^ Zedequias, rei de Judá, havia aprisionado Jeremias acusando-o de profetizar que o Senhor iria entregar a cidade nas mãos do rei da Babilônia, e que este a conquistaria;

[[v24-32-4]]

^<<v24-32-4,4>>^ que Zedequias, rei de Judá, não escaparia das mãos dos babilônios, mas certamente seria entregue nas mãos do rei da Babilônia, falaria com ele face a face, e o veria com os próprios olhos;

[[v24-32-5]]

^<<v24-32-5,5>>^ e que ele levaria Zedequias para a Babilônia, onde este ficaria até que o Senhor cuidasse da situação dele; e, ainda, que se eles lutassem contra os babilônios não seriam bem-sucedidos.

[[v24-32-6]]

^<<v24-32-6,6>>^ E Jeremias disse: "O Senhor dirigiu-me a palavra nos seguintes termos:

[[v24-32-7]]

^<<v24-32-7,7>>^ Hanameel, filho de seu tio Salum, virá ao seu encontro e dirá: ‘Compre a propriedade que tenho em Anatote, porque, sendo o parente mais próximo, você tem o direito e o dever de comprá-la’.

[[v24-32-8]]

^<<v24-32-8,8>>^ "Conforme o Senhor tinha dito, meu primo Hanameel veio ao meu encontro no pátio da guarda e disse: ‘Compre a propriedade que tenho em Anatote, no território de Benjamim, porque é seu o direito de posse e de resgate. Compre-a! ’ "Então, compreendi que essa era a palavra do Senhor.

[[v24-32-9]]

^<<v24-32-9,9>>^ Assim, comprei do meu primo Hanameel a propriedade que ele possuía em Anatote. Pesei a prata e lhe paguei dezessete peças de prata.

[[v24-32-10]]

^<<v24-32-10,10>>^ Assinei e selei a escritura, e pesei a prata na balança, diante de testemunhas por mim chamadas.

[[v24-32-11]]

^<<v24-32-11,11>>^ Peguei a escritura, a cópia selada com os termos e condições da compra, bem como a cópia não selada,

[[v24-32-12]]

^<<v24-32-12,12>>^ e entreguei essa escritura de compra a Baruque, filho de Nerias, filho de Maaséias, na presença de meu primo Hanameel, das testemunhas que tinham assinado a escritura e de todos os judeus que estavam sentados no pátio da guarda.

[[v24-32-13]]

^<<v24-32-13,13>>^ "Na presença deles dei as seguintes instruções a Baruque:

[[v24-32-14]]

^<<v24-32-14,14>>^ ‘Assim diz o Senhor dos Exércitos, Deus de Israel: Tome estes documentos, tanto a cópia selada como a não selada da escritura de compra, e coloque-os num jarro de barro para que se conservem por muitos anos.

[[v24-32-15]]

^<<v24-32-15,15>>^ Porque assim diz o Senhor dos Exércitos, Deus de Israel: Casas, campos e vinhas tornarão a ser comprados nesta terra.

[[v24-32-16]]

^<<v24-32-16,16>>^ "Depois que entreguei a escritura de compra a Baruque, filho de Nerias, orei ao Senhor:

[[v24-32-17]]

^<<v24-32-17,17>>^ "Ah! Soberano Senhor, tu fizeste os céus e a terra pelo teu grande poder e por teu braço estendido. Nada é difícil demais para ti.

[[v24-32-18]]

^<<v24-32-18,18>>^ Mostras bondade até mil gerações, mas lanças os pecados dos pais sobre os seus filhos. Ó grande e poderoso Deus, cujo nome é o Senhor dos Exércitos,

[[v24-32-19]]

^<<v24-32-19,19>>^ grandes são os teus propósitos e poderosos os teus feitos. Os teus olhos estão atentos aos atos dos homens; tu retribuis a cada um de acordo com a sua conduta, de acordo com os efeitos das suas obras.

[[v24-32-20]]

^<<v24-32-20,20>>^ Realizaste sinais e maravilhas no Egito e continuas a fazê-los até hoje, tanto em Israel como entre toda a humanidade, e alcançaste o renome que hoje tens.

[[v24-32-21]]

^<<v24-32-21,21>>^ Tiraste o teu povo do Egito com sinais e maravilhas, com mão poderosa e braço estendido, causando grande pavor.

[[v24-32-22]]

^<<v24-32-22,22>>^ Deste a eles esta terra, que sob juramento prometeste aos seus antepassados; uma terra onde manam leite e mel.

[[v24-32-23]]

^<<v24-32-23,23>>^ Eles vieram e tomaram posse dela, mas não te obedeceram nem seguiram a tua lei. Não fizeram nada daquilo que lhes ordenaste. Por isso trouxeste toda esta desgraça sobre eles.

[[v24-32-24]]

^<<v24-32-24,24>>^ "As rampas de cerco são erguidas pelos inimigos para tomarem a cidade, e pela guerra, pela fome e pela peste, ela será entregue nas mãos dos babilônios que a atacam. Cumpriu-se aquilo que disseste, como vês.

[[v24-32-25]]

^<<v24-32-25,25>>^ Ainda assim, ó Soberano Senhor, tu me mandaste comprar a propriedade e convocar testemunhas do negócio, embora a cidade esteja entregue nas mãos dos babilônios! "

[[v24-32-26]]

^<<v24-32-26,26>>^ A palavra do Senhor veio a mim, dizendo:

[[v24-32-27]]

^<<v24-32-27,27>>^ "Eu sou o Senhor, o Deus de toda a humanidade. Há alguma coisa difícil demais para mim?

[[v24-32-28]]

^<<v24-32-28,28>>^ Portanto, assim diz o Senhor: ‘Estou entregando esta cidade nas mãos dos babilônios e de Nabucodonosor, rei da Babilônia, que a conquistará.

[[v24-32-29]]

^<<v24-32-29,29>>^ Os babilônios, que estão atacando esta cidade, entrarão e a incendiarão. Eles a queimarão juntamente com as casas nas quais o povo provocou a minha ira queimando incenso a Baal nos seus terraços, e derramando ofertas de bebida em honra de outros deuses.

[[v24-32-30]]

^<<v24-32-30,30>>^ "Desde a sua juventude o povo de Israel e de Judá nada tem feito senão aquilo que eu considero mau; de fato, o povo de Israel nada tem feito além de provocar-me à ira", declara o Senhor.

[[v24-32-31]]

^<<v24-32-31,31>>^ Desde o dia em que foi construída até hoje, esta cidade tem despertado o meu furor de tal forma que tenho que tirá-la da minha frente.

[[v24-32-32]]

^<<v24-32-32,32>>^ O povo de Israel e de Judá tem provocado a minha ira por causa de todo o mal que tem feito, tanto eles como os seus reis e os seus líderes, os seus sacerdotes e os seus profetas, os homens de Judá e os habitantes de Jerusalém.

[[v24-32-33]]

^<<v24-32-33,33>>^ Voltaram as costas para mim e não o rosto; embora eu os tenha ensinado vez após vez, não quiseram ouvir-me nem aceitaram a correção.

[[v24-32-34]]

^<<v24-32-34,34>>^ Profanaram o templo que leva o meu nome, colocando nele as imagens de seus ídolos.

[[v24-32-35]]

^<<v24-32-35,35>>^ Construíram o alto para Baal no vale de Ben-Hinom, para sacrificarem a Moloque os seus filhos e as suas filhas, coisa que nunca ordenei, prática repugnante que jamais imaginei; e, assim, levaram Judá a pecar".

[[v24-32-36]]

^<<v24-32-36,36>>^ Portanto, assim diz o Senhor a esta cidade, sobre a qual vocês estão dizendo que será entregue nas mãos dos babilônios por meio da guerra, da fome e da peste:

[[v24-32-37]]

^<<v24-32-37,37>>^ "Certamente eu os reunirei de todas as terras para onde os dispersei na minha ardente ira e no meu grande furor; eu os trarei de volta a este lugar e permitirei que vivam em segurança.

[[v24-32-38]]

^<<v24-32-38,38>>^ Eles serão o meu povo, e eu serei o seu Deus.

[[v24-32-39]]

^<<v24-32-39,39>>^ Darei a eles um só pensamento e uma só conduta, para que me temam durante toda a sua vida, para o seu próprio bem e o de seus filhos e descendentes.

[[v24-32-40]]

^<<v24-32-40,40>>^ Farei com eles uma aliança permanente: Jamais deixarei de fazer o bem a eles, e farei com que me temam de coração, para que jamais se desviem de mim.

[[v24-32-41]]

^<<v24-32-41,41>>^ Terei alegria em fazer-lhes o bem, e os plantarei firmemente nesta terra de todo o meu coração e de toda a minha alma. Sim, é o que farei.

[[v24-32-42]]

^<<v24-32-42,42>>^ "Assim diz o Senhor: Assim como eu trouxe toda esta grande desgraça sobre este povo, também lhes darei a prosperidade que lhes prometo.

[[v24-32-43]]

^<<v24-32-43,43>>^ De novo serão compradas propriedades nesta terra da qual vocês dizem: ‘É uma terra arrasada, sem homens nem animais, pois foi entregue nas mãos dos babilônios’.

[[v24-32-44]]

^<<v24-32-44,44>>^ Propriedades serão compradas por prata e escrituras serão assinadas, seladas diante de testemunhas no território de Benjamim, nos povoados ao redor de Jerusalém, nas cidades de Judá, e nas cidades dos montes, da Sefelá e do Neguebe, porque eu restaurarei a sorte deles", declara o Senhor.

'''

xref:024-jeremias/024-jeremias-031.adoc#v24-31-0[&#60; Capítulo Anterior] | <<v24-32-0,Topo>> | xref:024-jeremias/024-jeremias-033.adoc#v24-33-0[Próximo Capítulo &#62;]