include::./index.adoc[]

[[v24-12-0]]
=== Jeremias, 12
// nvi ?, NVI - Nova Versão Internacional

[[v24-12-1]]

^<<v24-12-1,1>>^ Tu és justo, Senhor, quando apresento uma causa diante de ti. Contudo, eu gostaria de discutir contigo sobre a tua justiça. Por que o caminho dos ímpios prospera? Por que todos os traidores vivem sem problemas?

[[v24-12-2]]

^<<v24-12-2,2>>^ Tu os plantaste, e eles criaram raízes; crescem e dão fruto. Tu estás sempre perto dos seus lábios, mas longe dos seus corações.

[[v24-12-3]]

^<<v24-12-3,3>>^ Tu, porém, me conheces, Senhor; tu me vês e provas a minha atitude para contigo. Arranca os ímpios como a ovelhas destinadas ao matadouro! Reserva-os para o dia da matança!

[[v24-12-4]]

^<<v24-12-4,4>>^ Até quando a terra ficará de luto e a relva de todo o campo estará seca? Perecem os animais e as aves por causa da maldade dos que habitam nesta terra, pois eles disseram: ‘Ele não verá o fim que nos espera’.

[[v24-12-5]]

^<<v24-12-5,5>>^ "Se você correu com homens e eles o cansaram, como poderá competir com cavalos? Se você tropeça em terreno seguro, o que fará nos matagais junto ao Jordão?

[[v24-12-6]]

^<<v24-12-6,6>>^ Até mesmo os seus irmãos e a sua própria família traíram você e o perseguem aos gritos. Não confie neles, mesmo quando lhe dizem coisas boas.

[[v24-12-7]]

^<<v24-12-7,7>>^ "Abandonei a minha família, deixei a minha propriedade e entreguei aquela a quem amo nas mãos dos seus inimigos.

[[v24-12-8]]

^<<v24-12-8,8>>^ O povo de minha propriedade tornou-se para mim como um leão na floresta. Ele ruge contra mim, por isso eu o odeio.

[[v24-12-9]]

^<<v24-12-9,9>>^ O povo de minha propriedade tornou-se para mim como uma toca de hiena, sobre pairam a qual as aves de rapina. Reúnam todos os animais selvagens; tragam-nos para o banquete.

[[v24-12-10]]

^<<v24-12-10,10>>^ A minha vinha foi destruída por muitos pastores, os quais pisotearam a minha propriedade. Eles tornaram a minha preciosa propriedade num deserto devastado.

[[v24-12-11]]

^<<v24-12-11,11>>^ Fizeram dela uma terra devastada; e devastada ela pranteia diante de mim. A terra toda foi devastada, mas não há quem se importe com isso.

[[v24-12-12]]

^<<v24-12-12,12>>^ Destruidores vieram sobre todas as planícies do deserto, pois a espada do Senhor devora esta terra de uma extremidade à outra; ninguém está seguro.

[[v24-12-13]]

^<<v24-12-13,13>>^ Semearam trigo, mas colheram espinhos; cansaram-se de trabalhar para nada produzir. Estão desapontados com a colheita por causa do fogo da ira do Senhor. "

[[v24-12-14]]

^<<v24-12-14,14>>^ Assim diz o Senhor a respeito de todos os meus vizinhos, as nações ímpias que se apoderam da herança que dei a Israel, meu povo: "Eu os arrancarei da sua terra, e arrancarei Judá do meio deles.

[[v24-12-15]]

^<<v24-12-15,15>>^ Mas, depois de arrancá-los, terei compaixão de novo e os farei voltar, cada um à sua propriedade e à sua terra.

[[v24-12-16]]

^<<v24-12-16,16>>^ E se aprenderem a comportar-se como meu povo, e jurarem pelo nome do Senhor, dizendo: ‘Juro pelo nome do Senhor’ — como antes ensinaram o meu povo a jurar por Baal — então eles serão estabelecidos no meio do meu povo.

[[v24-12-17]]

^<<v24-12-17,17>>^ Mas se não me ouvirem, eu arrancarei completamente aquela nação e a destruirei", declara o Senhor.

'''

xref:024-jeremias/024-jeremias-011.adoc#v24-11-0[&#60; Capítulo Anterior] | <<v24-12-0,Topo>> | xref:024-jeremias/024-jeremias-013.adoc#v24-13-0[Próximo Capítulo &#62;]