include::./index.adoc[]

[[v24-46-0]]
=== Jeremias, 46
// nvi ?, NVI - Nova Versão Internacional

[[v24-46-1]]

^<<v24-46-1,1>>^ Esta é a mensagem do Senhor que veio ao profeta Jeremias acerca das nações:

[[v24-46-2]]

^<<v24-46-2,2>>^ Acerca do Egito: Esta é a mensagem contra o exército do rei do Egito, o faraó Neco, que foi derrotado em Carquemis, junto ao rio Eufrates, por Nabucodonosor, rei da Babilônia, no quarto ano do reinado de Jeoaquim, filho de Josias, rei de Judá:

[[v24-46-3]]

^<<v24-46-3,3>>^ "Preparem seus escudos, os grandes e os pequenos, e marchem para a batalha!

[[v24-46-4]]

^<<v24-46-4,4>>^ Selem os cavalos e montem! Tomem posição e coloquem o capacete! Passem óleo na ponta de suas lanças e vistam a armadura!

[[v24-46-5]]

^<<v24-46-5,5>>^ Mas o que vejo? Eles estão apavorados, estão se retirando, seus guerreiros estão derrotados. Fogem às pressas, sem olhar para trás; há terror por todos os lados", declara o Senhor.

[[v24-46-6]]

^<<v24-46-6,6>>^ "O ágil não consegue fugir, nem o forte escapar. No norte, junto ao rio Eufrates, eles tropeçam e caem.

[[v24-46-7]]

^<<v24-46-7,7>>^ "Quem é aquele que se levanta como o Nilo, como rios de águas agitadas?

[[v24-46-8]]

^<<v24-46-8,8>>^ O Egito se levanta como o Nilo, como rios de águas agitadas. Ele diz: ‘Eu me levantarei e cobrirei a terra; destruirei as cidades e os seus habitantes’.

[[v24-46-9]]

^<<v24-46-9,9>>^ Ao ataque, cavalos! Avancem, carros de guerra! Marchem em frente, guerreiros! Homens da Etiópia e da Líbia, que levam escudos; homens da Lídia, que empunham o arco!

[[v24-46-10]]

^<<v24-46-10,10>>^ Mas aquele dia pertence ao Soberano, ao Senhor dos Exércitos. Será um dia de vingança, para vingar-se dos seus adversários. A espada devorará até saciar-se, até satisfazer sua sede de sangue. Porque o Soberano, o Senhor dos Exércitos, fará um banquete na terra do norte, junto ao rio Eufrates.

[[v24-46-11]]

^<<v24-46-11,11>>^ "Suba a Gileade em busca de bálsamo, ó virgem, filha do Egito! Você multiplica remédios em vão; não há cura para você.

[[v24-46-12]]

^<<v24-46-12,12>>^ As nações ouviram da tua humilhação; os seus gritos encheram a terra, quando um guerreiro tropeçou noutro guerreiro e ambos caíram. "

[[v24-46-13]]

^<<v24-46-13,13>>^ Esta é a mensagem que o Senhor falou ao profeta Jeremias acerca da vinda de Nabucodonosor, rei da Babilônia para atacar o Egito:

[[v24-46-14]]

^<<v24-46-14,14>>^ "Anunciem isto no Egito e proclamem-no em Migdol; proclamem-no também em Mênfis e em Tafnes: ‘Assumam posição! Preparem-se! Porque a espada devora aqueles que estão ao seu redor’.

[[v24-46-15]]

^<<v24-46-15,15>>^ Por que o deus Ápis fugiu? O seu touro não resistiu, porque o Senhor o derrubou.

[[v24-46-16]]

^<<v24-46-16,16>>^ Tropeçam e caem, caem uns sobre os outros. Eles dizem: ‘Levantem-se. Vamos voltar para nosso próprio povo e para nossa terra natal, para longe da espada do opressor.

[[v24-46-17]]

^<<v24-46-17,17>>^ O faraó, rei do Egito, é barulho e nada mais! Ele perdeu a sua oportunidade’.

[[v24-46-18]]

^<<v24-46-18,18>>^ "Juro pela minha vida", declara o Rei, cujo nome é o Senhor dos Exércitos, "ele virá como o Tabor entre os montes, como o Carmelo junto ao mar.

[[v24-46-19]]

^<<v24-46-19,19>>^ Arrumem a bagagem para o exílio, vocês que vivem no Egito, pois Mênfis será arrasada, ficará desolada e desabitada.

[[v24-46-20]]

^<<v24-46-20,20>>^ "O Egito é uma linda novilha, mas do norte a ataca uma mutuca.

[[v24-46-21]]

^<<v24-46-21,21>>^ Os mercenários em suas fileiras são como bezerros gordos. Eles também darão meia volta e juntos fugirão; não defenderão suas posições, pois o dia da derrota deles está chegando, a hora de serem castigados.

[[v24-46-22]]

^<<v24-46-22,22>>^ O Egito silvará como uma serpente em fuga à medida que o inimigo avança com grande força. Virão sobre ele com machados, como os homens que derrubam árvores.

[[v24-46-23]]

^<<v24-46-23,23>>^ Eles derrubarão sua floresta", declara o Senhor, "por mais densa que seja. São mais que os gafanhotos; são incontáveis!

[[v24-46-24]]

^<<v24-46-24,24>>^ A cidade do Egito será envergonhada, será entregue nas mãos do povo do norte".

[[v24-46-25]]

^<<v24-46-25,25>>^ O Senhor dos Exércitos, o Deus de Israel, diz: "Castigarei Amom, deus de Tebas, o faraó, o Egito, seus deuses e seus reis, e também os que confiam no faraó.

[[v24-46-26]]

^<<v24-46-26,26>>^ Eu os entregarei nas mãos daqueles que desejam tirar-lhes a vida; nas mãos de Nabucodonosor, rei da Babilônia, e de seus oficiais. Mais tarde, porém, o Egito será habitado como em épocas passadas", declara o Senhor.

[[v24-46-27]]

^<<v24-46-27,27>>^ "Quanto a você, não tema, meu servo Jacó! Não fique assustado, ó Israel! Eu o salvarei de um lugar distante, e os seus descendentes da terra do seu exílio. Jacó voltará e ficará em paz e em segurança; ninguém o inquietará.

[[v24-46-28]]

^<<v24-46-28,28>>^ Não tema, meu servo Jacó! Eu estou com você", declara o Senhor. "Destruirei completamente todas as nações entre as quais eu o dispersei; mas a você, não destruirei completamente. Eu o disciplinarei, como você merece; não serei severo demais. "

'''

xref:024-jeremias/024-jeremias-045.adoc#v24-45-0[&#60; Capítulo Anterior] | <<v24-46-0,Topo>> | xref:024-jeremias/024-jeremias-047.adoc#v24-47-0[Próximo Capítulo &#62;]