include::./index.adoc[]

[[v24-1-0]]
=== Jeremias, 1
// nvi ?, NVI - Nova Versão Internacional

[[v24-1-1]]

^<<v24-1-1,1>>^ As palavras de Jeremias, filho de Hilquias, um dos sacerdotes de Anatote, no território de Benjamim.

[[v24-1-2]]

^<<v24-1-2,2>>^ A palavra do Senhor veio a ele no décimo terceiro ano do reinado de Josias, filho de Amom, rei de Judá,

[[v24-1-3]]

^<<v24-1-3,3>>^ e durante o reinado de Jeoaquim, filho de Josias, rei de Judá, até o quinto mês do décimo primeiro ano de Zedequias, filho de Josias, rei de Judá, quando os habitantes de Jerusalém foram levados para o exílio.

[[v24-1-4]]

^<<v24-1-4,4>>^ A palavra do Senhor veio a mim, dizendo:

[[v24-1-5]]

^<<v24-1-5,5>>^ "Antes de formá-lo no ventre eu o escolhi; antes de você nascer, eu o separei e o designei profeta às nações".

[[v24-1-6]]

^<<v24-1-6,6>>^ Mas eu disse: "Ah, Soberano Senhor! Eu não sei falar, pois ainda sou muito jovem".

[[v24-1-7]]

^<<v24-1-7,7>>^ O Senhor, porém, me disse: "Não diga que é muito jovem. A todos a quem eu o enviar você irá e dirá tudo o que eu lhe ordenar.

[[v24-1-8]]

^<<v24-1-8,8>>^ Não tenha medo deles, pois eu estou com você para protegê-lo", diz o Senhor.

[[v24-1-9]]

^<<v24-1-9,9>>^ O Senhor estendeu a mão, tocou a minha boca e disse-me: "Agora ponho em sua boca as minhas palavras.

[[v24-1-10]]

^<<v24-1-10,10>>^ Veja! Eu hoje dou a você autoridade sobre nações e reinos, para arrancar, despedaçar, arruinar e destruir; para edificar e para plantar".

[[v24-1-11]]

^<<v24-1-11,11>>^ E a palavra do Senhor veio a mim: "O que você vê, Jeremias? " "Vejo o ramo de uma amendoeira", respondi.

[[v24-1-12]]

^<<v24-1-12,12>>^ O Senhor me disse: "Você viu bem, pois estou vigiando para que a minha palavra se cumpra".

[[v24-1-13]]

^<<v24-1-13,13>>^ A palavra do Senhor veio a mim pela segunda vez, dizendo: "O que você vê? " E eu respondi: "Vejo uma panela fervendo; ela está inclinada do norte para cá".

[[v24-1-14]]

^<<v24-1-14,14>>^ O Senhor me disse: "Do norte se derramará a desgraça sobre todos os habitantes desta terra.

[[v24-1-15]]

^<<v24-1-15,15>>^ Estou convocando todos os povos dos reinos do norte", diz o Senhor. "Cada um virá e colocará o seu trono diante das portas de Jerusalém, virão contra todas as muralhas que a cercam e contra todas as cidades de Judá.

[[v24-1-16]]

^<<v24-1-16,16>>^ Pronunciarei a minha sentença contra o meu povo por todas as suas maldades; porque me abandonaram, queimaram incenso a outros deuses, e adoraram deuses que as suas mãos fizeram".

[[v24-1-17]]

^<<v24-1-17,17>>^ "E você, prepare-se! Vá dizer-lhes tudo o que eu ordenar. Não fique aterrorizado por causa deles, senão eu o aterrorizarei diante deles.

[[v24-1-18]]

^<<v24-1-18,18>>^ E hoje eu faço de você uma cidade fortificada, uma coluna de ferro e um muro de bronze, contra toda a terra: contra os reis de Judá, seus oficiais, seus sacerdotes e o povo da terra.

[[v24-1-19]]

^<<v24-1-19,19>>^ Eles lutarão contra você, mas não o vencerão, pois eu estou com você e o protegerei", diz o Senhor.

'''

xref:023-isaias/023-isaias-066.adoc#v23-66-0[&#60; Capítulo Anterior] | <<v24-1-0,Topo>> | xref:024-jeremias/024-jeremias-002.adoc#v24-2-0[Próximo Capítulo &#62;]