include::./index.adoc[]

[[v24-36-0]]
=== Jeremias, 36
// nvi ?, NVI - Nova Versão Internacional

[[v24-36-1]]

^<<v24-36-1,1>>^ No quarto ano do reinado de Jeoaquim, filho de Josias, rei de Judá, o Senhor dirigiu esta palavra a Jeremias:

[[v24-36-2]]

^<<v24-36-2,2>>^ "Pegue um rolo e escreva nele todas as palavras que lhe falei a respeito de Israel, de Judá e de todas as outras nações, desde que comecei a falar a você, durante o reinado de Josias, até hoje.

[[v24-36-3]]

^<<v24-36-3,3>>^ Talvez, quando o povo de Judá souber de cada uma das desgraças que planejo trazer sobre eles, cada um se converta de sua má conduta e eu perdoe a iniqüidade e o pecado deles".

[[v24-36-4]]

^<<v24-36-4,4>>^ Então Jeremias chamou Baruque, filho de Nerias, para que escrevesse no rolo, conforme Jeremias ditava, todas as palavras que o Senhor lhe havia falado.

[[v24-36-5]]

^<<v24-36-5,5>>^ Depois Jeremias disse a Baruque: "Estou preso; não posso ir ao templo do Senhor.

[[v24-36-6]]

^<<v24-36-6,6>>^ Por isso, vá ao templo do Senhor no dia do jejum e leia ao povo as palavras do Senhor que eu ditei, as quais você escreveu. Você também as lerá a todo o povo de Judá que vem de suas cidades.

[[v24-36-7]]

^<<v24-36-7,7>>^ Talvez a súplica deles chegue diante do Senhor, e cada um se converta de sua má conduta, pois é grande o furor anunciado pelo Senhor contra este povo".

[[v24-36-8]]

^<<v24-36-8,8>>^ E Baruque, filho de Nerias, fez exatamente tudo aquilo que o profeta Jeremias lhe mandou fazer, e leu as palavras do Senhor.

[[v24-36-9]]

^<<v24-36-9,9>>^ No nono mês do quinto ano do reinado de Jeoaquim, filho de Josias, rei de Judá, foi proclamado um jejum perante o Senhor para todo o povo de Jerusalém e para todo o povo que vinha das cidades de Judá para Jerusalém.

[[v24-36-10]]

^<<v24-36-10,10>>^ Baruque leu a todo o povo as palavras de Jeremias escritas no rolo. Ele as leu no templo do Senhor, da sala de Gemarias, filho do secretário Safã. A sala ficava no pátio superior, na porta Nova do templo.

[[v24-36-11]]

^<<v24-36-11,11>>^ Quando Micaías, filho de Gemarias, filho de Safã, ouviu todas as palavras do Senhor,

[[v24-36-12]]

^<<v24-36-12,12>>^ desceu à sala do secretário, no palácio real, onde todos os líderes estavam sentados: o secretário Elisama, Delaías, filho de Semaías, Elnatã, filho de Acbor, Gemarias, filho de Safã, Zedequias, filho de Hananias, e todos os outros líderes.

[[v24-36-13]]

^<<v24-36-13,13>>^ Micaías relatou-lhes tudo o que tinha ouvido quando Baruque leu ao povo o que estava escrito.

[[v24-36-14]]

^<<v24-36-14,14>>^ Então todos os líderes mandaram por intermédio de Jeudi, filho de Netanias, neto de Selemias, bisneto de Cuchi, a seguinte mensagem a Baruque: "Pegue o rolo que você leu ao povo e venha aqui". Baruque, filho de Nerias, pegou o rolo e foi até eles.

[[v24-36-15]]

^<<v24-36-15,15>>^ Disseram-lhe: "Sente-se, e leia-o para nós". Então Baruque o leu para eles.

[[v24-36-16]]

^<<v24-36-16,16>>^ Quando ouviram todas aquelas palavras, entreolharam-se com medo e disseram a Baruque: "É absolutamente necessário que relatemos ao rei todas essas palavras".

[[v24-36-17]]

^<<v24-36-17,17>>^ Perguntaram a Baruque: "Diga-nos, como você escreveu tudo isso? Foi Jeremias quem o ditou a você? "

[[v24-36-18]]

^<<v24-36-18,18>>^ "Sim", Baruque respondeu, "ele ditou todas essas palavras, e eu as escrevi com tinta no rolo. "

[[v24-36-19]]

^<<v24-36-19,19>>^ Os líderes disseram a Baruque: "Vá esconder-se com Jeremias; e que ninguém saiba onde vocês estão".

[[v24-36-20]]

^<<v24-36-20,20>>^ Então deixaram o rolo na sala de Elisama, o secretário, e foram ao pátio do palácio real, e relataram tudo ao rei.

[[v24-36-21]]

^<<v24-36-21,21>>^ O rei mandou Jeudi pegar o rolo, e Jeudi o trouxe da sala de Elisama, o secretário, e o leu ao rei e a todos os líderes que estavam a seu serviço.

[[v24-36-22]]

^<<v24-36-22,22>>^ Isso aconteceu no nono mês. O rei estava sentado em seu apartamento do inverno, perto de um braseiro aceso.

[[v24-36-23]]

^<<v24-36-23,23>>^ Assim que Jeudi terminava de ler três ou quatro colunas, o rei as cortava com uma faca de escrivão e as atirava no braseiro, até que o rolo inteiro foi queimado no braseiro.

[[v24-36-24]]

^<<v24-36-24,24>>^ O rei e todos os seus conselheiros que ouviram todas aquelas palavras não ficaram alarmados nem rasgaram as suas roupas, lamentando-se.

[[v24-36-25]]

^<<v24-36-25,25>>^ Embora Elnatã, Delaías e Gemarias tivessem insistido com o rei que não queimasse o rolo, ele não quis ouvi-los.

[[v24-36-26]]

^<<v24-36-26,26>>^ Em vez disso, o rei ordenou a Jerameel, filho do rei, Seraías, filho de Azriel, e Selemias, filho de Abdeel, que prendessem o escriba Baruque e o profeta Jeremias. Mas o Senhor os tinha escondido.

[[v24-36-27]]

^<<v24-36-27,27>>^ Depois que o rei queimou o rolo que continha as palavras que Jeremias ditou e Baruque escreveu, o Senhor dirigiu esta palavra a Jeremias:

[[v24-36-28]]

^<<v24-36-28,28>>^ "Pegue outro rolo e escreva nele todas as palavras que estavam no primeiro, que Jeoaquim, rei de Judá, queimou.

[[v24-36-29]]

^<<v24-36-29,29>>^ Também diga a Jeoaquim, rei de Judá: ‘Assim diz o Senhor: Você queimou aquele rolo e perguntou: "Por que você escreveu nele que o rei da Babilônia virá e destruirá esta terra e dela eliminará tanto homens como animais? "

[[v24-36-30]]

^<<v24-36-30,30>>^ Pois assim diz o Senhor acerca de Jeoaquim, rei de Judá: Ele não terá nenhum descendente para sentar-se no trono de Davi; seu corpo será lançado fora e exposto ao calor de dia e à geada de noite.

[[v24-36-31]]

^<<v24-36-31,31>>^ Eu castigarei a ele, aos seus filhos e aos seus conselheiros por causa dos seus pecados. Trarei sobre eles e sobre os habitantes de Jerusalém e sobre os homens de Judá toda a desgraça que pronunciei contra eles, porquanto não me deram atenção’ ".

[[v24-36-32]]

^<<v24-36-32,32>>^ Então Jeremias pegou outro rolo e o deu ao escriba Baruque, filho de Nerias, para que escrevesse nele, conforme Jeremias ditava, todas as palavras do livro que Jeoaquim, rei de Judá, tinha queimado, além de muitas outras palavras semelhantes que foram acrescentadas.

'''

xref:024-jeremias/024-jeremias-035.adoc#v24-35-0[&#60; Capítulo Anterior] | <<v24-36-0,Topo>> | xref:024-jeremias/024-jeremias-037.adoc#v24-37-0[Próximo Capítulo &#62;]