include::./index.adoc[]

[[v24-48-0]]
=== Jeremias, 48
// nvi ?, NVI - Nova Versão Internacional

[[v24-48-1]]

^<<v24-48-1,1>>^ Acerca de Moabe assim diz o Senhor dos Exércitos, Deus de Israel: "Ai de Nebo, pois ficou em ruínas. Quiriataim foi derrotada e capturada; a fortaleza foi derrotada e destroçada.

[[v24-48-2]]

^<<v24-48-2,2>>^ Moabe não é mais louvada; em Hesbom tramam a sua ruína: ‘Venham! Vamos dar fim àquela nação’. Você também ficará calada, ó Madmém; a espada a perseguirá.

[[v24-48-3]]

^<<v24-48-3,3>>^ Ouçam os gritos de Horonaim: ‘Devastação! Grande destruição!

[[v24-48-4]]

^<<v24-48-4,4>>^ Moabe está destruída! ’ É o grito que se ouve até em Zoar.

[[v24-48-5]]

^<<v24-48-5,5>>^ Eles sobem pelo caminho para Luíte, chorando amargamente enquanto seguem; na estrada que desce a Horonaim ouvem-se gritos angustiados por causa da destruição.

[[v24-48-6]]

^<<v24-48-6,6>>^ Fujam! Corram para salvar suas vidas; tornem-se como um arbusto no deserto.

[[v24-48-7]]

^<<v24-48-7,7>>^ Uma vez que vocês confiam em seus feitos e em suas riquezas, vocês também serão capturados, e Camos irá para o exílio, junto com seus sacerdotes e líderes.

[[v24-48-8]]

^<<v24-48-8,8>>^ O destruidor virá contra todas as cidades, e nenhuma escapará. O vale se tornará ruínas, e o planalto será destruído, como o Senhor falou.

[[v24-48-9]]

^<<v24-48-9,9>>^ Ponham sal sobre Moabe, pois ela será deixada em ruínas; suas cidades ficarão devastadas, sem nenhum habitante.

[[v24-48-10]]

^<<v24-48-10,10>>^ "Maldito o que faz com negligência o trabalho do Senhor! Maldito aquele que impede a sua espada de derramar sangue!

[[v24-48-11]]

^<<v24-48-11,11>>^ "Moabe tem estado tranqüila desde a sua juventude, como o vinho deixado com os seus resíduos; não foi mudada de vasilha em vasilha. Nunca foi para o exílio; por isso, o seu sabor permanece o mesmo e o seu cheiro não mudou.

[[v24-48-12]]

^<<v24-48-12,12>>^ Portanto, certamente vêm os dias", declara o Senhor, "quando enviarei decantadores que o decantarão; esvaziarão as suas jarras e as despedaçarão.

[[v24-48-13]]

^<<v24-48-13,13>>^ Então Moabe se decepcionará com Camos, assim como Israel se decepcionou com Betel, em quem confiava.

[[v24-48-14]]

^<<v24-48-14,14>>^ "Como vocês podem dizer: ‘Somos guerreiros, somos homens de guerra’?

[[v24-48-15]]

^<<v24-48-15,15>>^ Moabe foi destruída e suas cidades serão invadidas; o melhor dos seus jovens desceu para a matança", declara o Rei, cujo nome é o Senhor dos Exércitos.

[[v24-48-16]]

^<<v24-48-16,16>>^ "A derrota de Moabe está próxima; a sua desgraça vem rapidamente.

[[v24-48-17]]

^<<v24-48-17,17>>^ Lamentem por ela, todos os seus vizinhos, todos os que conhecem a sua fama. Digam: ‘Como está quebrado o cajado poderoso, o cetro glorioso! ’

[[v24-48-18]]

^<<v24-48-18,18>>^ "Desçam de sua glória e sentem-se sobre o chão ressequido, ó moradores da cidade de Dibom, pois o destruidor de Moabe veio para atacá-los e destruir as suas fortalezas.

[[v24-48-19]]

^<<v24-48-19,19>>^ Fiquem junto à estrada e vigiem, vocês que vivem em Aroer. Perguntem ao homem que foge e à mulher que escapa, perguntem a eles: ‘O que aconteceu? ’

[[v24-48-20]]

^<<v24-48-20,20>>^ Moabe ficou envergonhada, pois está destroçada. Gritem e clamem! Anunciem junto ao Arnom que Moabe foi destruída.

[[v24-48-21]]

^<<v24-48-21,21>>^ O julgamento chegou ao planalto: a Holom, Jaza e Mefaate,

[[v24-48-22]]

^<<v24-48-22,22>>^ a Dibom, Nebo e Bete-Diblataim,

[[v24-48-23]]

^<<v24-48-23,23>>^ a Quiriataim, Bete-Gamul e Bete-Meom,

[[v24-48-24]]

^<<v24-48-24,24>>^ a Queriote e Bozra, a todas as cidades de Moabe, distantes e próximas.

[[v24-48-25]]

^<<v24-48-25,25>>^ O poder de Moabe foi eliminado; seu braço está quebrado", declara o Senhor.

[[v24-48-26]]

^<<v24-48-26,26>>^ "Embriaguem-na, pois ela desafiou o Senhor. Moabe se revolverá no seu vômito e será objeto de ridículo.

[[v24-48-27]]

^<<v24-48-27,27>>^ Não foi Israel objeto de ridículo para você? Foi ele encontrado em companhia de ladrões para que você sacuda a cabeça sempre que fala dele?

[[v24-48-28]]

^<<v24-48-28,28>>^ Abandonem as cidades! Habitem entre as rochas, vocês que moram em Moabe! Sejam como uma pomba que faz o seu ninho nas bordas de um precipício.

[[v24-48-29]]

^<<v24-48-29,29>>^ "Temos ouvido do orgulho de Moabe: da sua extrema arrogância, do seu orgulho e soberba, e do seu espírito de superioridade.

[[v24-48-30]]

^<<v24-48-30,30>>^ Conheço bem a sua arrogância", declara o Senhor. "A sua tagarelice sem fundamento e as suas ações que nada alcançam.

[[v24-48-31]]

^<<v24-48-31,31>>^ Por isso, lamentarei por Moabe, gritarei por causa de toda a terra de Moabe, prantearei pelos habitantes de Quir-Heres.

[[v24-48-32]]

^<<v24-48-32,32>>^ Chorarei por vocês mais do que choro por Jazar, ó videiras de Sibma. Os seus ramos se estendiam até o mar, e chegavam até Jazar. O destruidor caiu sobre as suas frutas e sobre as suas uvas.

[[v24-48-33]]

^<<v24-48-33,33>>^ A alegria e a satisfação se foram das terras férteis de Moabe. Interrompi a produção de vinho nos lagares. Ninguém mais pisa as uvas com gritos de alegria; embora haja gritos, não são de alegria.

[[v24-48-34]]

^<<v24-48-34,34>>^ "O grito de Hesbom é ouvido em Eleale e Jaaz, desde Zoar até Horonaim e Eglate-Selisia, pois até as águas do Ninrim secaram.

[[v24-48-35]]

^<<v24-48-35,35>>^ Em Moabe darei fim àqueles que fazem ofertas nos altares idólatras e queimam incenso a seus deuses", declara o Senhor.

[[v24-48-36]]

^<<v24-48-36,36>>^ "Por isso o meu coração lamenta-se por Moabe, como uma flauta; lamenta-se como uma flauta pelos habitantes de Quir-Heres. A riqueza que acumularam se foi.

[[v24-48-37]]

^<<v24-48-37,37>>^ Toda cabeça foi rapada e toda barba foi cortada; toda mão sofreu incisões e toda cintura foi coberta com veste de lamento.

[[v24-48-38]]

^<<v24-48-38,38>>^ Em todos os terraços de Moabe e nas praças não há nada senão pranto, pois despedacei Moabe como a um jarro que ninguém deseja", declara o Senhor.

[[v24-48-39]]

^<<v24-48-39,39>>^ "Como ela foi destruída! Como lamentam! Como Moabe dá as costas, envergonhada! Moabe tornou-se objeto de ridículo e de pavor para todos os seus vizinhos. "

[[v24-48-40]]

^<<v24-48-40,40>>^ Assim diz o Senhor: "Vejam! Uma águia planando estende as asas sobre Moabe.

[[v24-48-41]]

^<<v24-48-41,41>>^ Queriote será capturada, e as fortalezas serão tomadas. Naquele dia, a coragem dos guerreiros de Moabe será como a de uma mulher em trabalho de parto.

[[v24-48-42]]

^<<v24-48-42,42>>^ Moabe será destruída como nação pois ela desafiou o Senhor.

[[v24-48-43]]

^<<v24-48-43,43>>^ Terror e cova e laço esperam por você, ó povo de Moabe", declara o Senhor.

[[v24-48-44]]

^<<v24-48-44,44>>^ "Quem fugir do terror cairá numa cova, e quem sair da cova será apanhado num laço. Trarei sobre Moabe a hora do seu castigo", declara o Senhor.

[[v24-48-45]]

^<<v24-48-45,45>>^ "Na sombra de Hesbom os fugitivos se encontram desamparados, pois um fogo saiu de Hesbom, uma labareda do meio de Seom; e queima as testas dos homens de Moabe e os crânios de homens turbulentos.

[[v24-48-46]]

^<<v24-48-46,46>>^ Ai de você, ó Moabe! O povo de Camos está destruído; Seus filhos são levados para o exílio, e suas filhas para o cativeiro.

[[v24-48-47]]

^<<v24-48-47,47>>^ "Contudo, restaurarei a sorte de Moabe em dias vindouros", declara o Senhor. Aqui termina a sentença sobre Moabe.

'''

xref:024-jeremias/024-jeremias-047.adoc#v24-47-0[&#60; Capítulo Anterior] | <<v24-48-0,Topo>> | xref:024-jeremias/024-jeremias-049.adoc#v24-49-0[Próximo Capítulo &#62;]