include::./index.adoc[]

[[v24-23-0]]
=== Jeremias, 23
// nvi ?, NVI - Nova Versão Internacional

[[v24-23-1]]

^<<v24-23-1,1>>^ "Ai dos pastores que destróem e dispersam as ovelhas do meu pasto! ", diz o Senhor.

[[v24-23-2]]

^<<v24-23-2,2>>^ Portanto, assim diz o Senhor, Deus de Israel, aos pastores que tomam conta do meu povo: "Foram vocês que dispersaram e expulsaram o meu rebanho, e não cuidaram dele. Mas eu cuidarei de vocês pelos seus maus procedimentos", declara o Senhor.

[[v24-23-3]]

^<<v24-23-3,3>>^ "Eu mesmo reunirei os remanescentes do meu rebanho de todas as terras para onde os expulsei e os trarei de volta à sua pastagem, a fim de que cresçam e se multipliquem.

[[v24-23-4]]

^<<v24-23-4,4>>^ Estabelecerei sobre eles pastores que cuidarão deles. E eles não mais terão medo ou pavor, e nenhum deles faltará", declara o Senhor.

[[v24-23-5]]

^<<v24-23-5,5>>^ "Dias virão", declara o Senhor, "em que levantarei para Davi um Renovo justo, um rei que reinará com sabedoria e fará o que é justo e certo na terra.

[[v24-23-6]]

^<<v24-23-6,6>>^ Em seus dias Judá será salva, Israel viverá em segurança, e este é o nome pelo qual será chamado: O Senhor é a Nossa Justiça.

[[v24-23-7]]

^<<v24-23-7,7>>^ "Portanto, vêm dias", diz o Senhor, "em que não mais se dirá: ‘Juro pelo nome do Senhor, que trouxe os israelitas do Egito’,

[[v24-23-8]]

^<<v24-23-8,8>>^ mas se dirá: ‘Juro pelo nome do Senhor, que trouxe os descendentes de Israel da terra do norte e de todas as nações para onde os expulsou’. E eles viverão na sua própria terra. "

[[v24-23-9]]

^<<v24-23-9,9>>^ Acerca dos profetas: Meu coração está partido dentro de mim; todos os meus ossos tremem. Sou como um bêbado, como um homem dominado pelo vinho, por causa do Senhor e de suas santas palavras.

[[v24-23-10]]

^<<v24-23-10,10>>^ A terra está cheia de adúlteros, e por causa disso a terra chora e as pastagens do deserto estão secas. Seu modo de vida é perveso e o seu poder é ilegítimo.

[[v24-23-11]]

^<<v24-23-11,11>>^ "Tanto o profeta como o sacerdote são profanos; até no meu templo encontro as iniqüidades deles", declara o Senhor.

[[v24-23-12]]

^<<v24-23-12,12>>^ "Por isso, o caminho deles será como lugares escorregadios nas trevas, para as quais serão banidos, e nelas cairão. Trarei a desgraça sobre eles, no ano do seu castigo", declara o Senhor.

[[v24-23-13]]

^<<v24-23-13,13>>^ "Entre os profetas de Samaria vi algo repugnante: Eles profetizaram por Baal e desviaram Israel, o meu povo.

[[v24-23-14]]

^<<v24-23-14,14>>^ E entre os profetas de Jerusalém vi algo horrível: Eles cometem adultério e vivem uma mentira. Encorajam os que praticam o mal, para que nenhum deles se converta de sua impiedade. Para mim são todos como Sodoma; o povo de Jerusalém é como Gomorra. "

[[v24-23-15]]

^<<v24-23-15,15>>^ Por isso assim diz o Senhor dos Exércitos acerca dos profetas: "Eu os farei comer comida amarga e beber água envenenada, porque dos profetas de Jerusalém a impiedade se espalhou por toda esta terra".

[[v24-23-16]]

^<<v24-23-16,16>>^ Assim diz o Senhor dos Exércitos: "Não ouçam o que os profetas estão profetizando para vocês; eles os enchem de falsas esperanças. Falam de visões inventadas por eles mesmos, e que não vêm da boca do Senhor.

[[v24-23-17]]

^<<v24-23-17,17>>^ Vivem dizendo àqueles que desprezam a palavra do Senhor: ‘Vocês terão paz’. E a todos os que seguem a obstinação dos seus corações dizem: ‘Vocês não sofrerão desgraça alguma’.

[[v24-23-18]]

^<<v24-23-18,18>>^ Mas qual deles esteve no conselho do Senhor para ver ou ouvir a sua palavra? Quem deu atenção e obedeceu à minha palavra?

[[v24-23-19]]

^<<v24-23-19,19>>^ Vejam, a tempestade do Senhor! A sua fúria está à solta! Um vendaval vem sobre a cabeça dos ímpios.

[[v24-23-20]]

^<<v24-23-20,20>>^ A ira do Senhor não se afastará até que ele tenha completado os seus propósitos. Em dias vindouros vocês o compreenderão claramente.

[[v24-23-21]]

^<<v24-23-21,21>>^ Não enviei esses profetas, mas eles foram correndo levar sua mensagem; não falei com eles, mas eles profetizaram.

[[v24-23-22]]

^<<v24-23-22,22>>^ Mas se eles tivessem comparecido ao meu conselho, anunciariam as minhas palavras ao meu povo e teriam feito com que se convertessem do seu mau procedimento e das suas obras más.

[[v24-23-23]]

^<<v24-23-23,23>>^ "Sou eu apenas um Deus de perto", pergunta o Senhor, "e não também um Deus de longe?

[[v24-23-24]]

^<<v24-23-24,24>>^ Poderá alguém esconder-se sem que eu o veja? ", pergunta o Senhor. "Não sou eu aquele que enche os céus e a terra? ", pergunta o Senhor.

[[v24-23-25]]

^<<v24-23-25,25>>^ "Ouvi o que dizem os profetas, que profetizam mentiras em meu nome, dizendo: ‘Tive um sonho! Tive um sonho! ’

[[v24-23-26]]

^<<v24-23-26,26>>^ Até quando os profetas continuarão a profetizar mentiras e as ilusões de suas próprias mentes?

[[v24-23-27]]

^<<v24-23-27,27>>^ Eles imaginam que os sonhos que contam uns aos outros farão o povo esquecer o meu nome, assim como os seus antepassados esqueceram o meu nome por causa de Baal.

[[v24-23-28]]

^<<v24-23-28,28>>^ O profeta que tem um sonho, conte o sonho, e o que tem a minha palavra, fale a minha palavra com fidelidade. Pois o que tem a palha com o trigo? ", pergunta o Senhor.

[[v24-23-29]]

^<<v24-23-29,29>>^ "Não é a minha palavra como o fogo", pergunta o Senhor, "e como um martelo que despedaça a rocha?

[[v24-23-30]]

^<<v24-23-30,30>>^ "Portanto", declara o Senhor, "estou contra os profetas que roubam uns dos outros as minhas palavras.

[[v24-23-31]]

^<<v24-23-31,31>>^ Sim", declara o Senhor, "estou contra os profetas que com as suas próprias línguas declaram oráculos.

[[v24-23-32]]

^<<v24-23-32,32>>^ Sim, estou contra os que profetizam sonhos falsos", declara o Senhor. "Eles os relatam e com as suas mentiras irresponsáveis desviam o meu povo. Eu não os enviei nem lhes autorizei; e eles não trazem benefício algum a este povo", declara o Senhor.

[[v24-23-33]]

^<<v24-23-33,33>>^ "Quando este povo ou um profeta ou um sacerdote lhe perguntar: ‘Qual é a mensagem pesada da qual o Senhor lhe encarregou? ’, diga-lhes: ‘Vocês são o peso! E eu os abandonarei’, declara o Senhor.

[[v24-23-34]]

^<<v24-23-34,34>>^ Se um profeta ou um sacerdote ou alguém do povo afirmar ‘Esta é a mensagem da qual o Senhor me encarregou’, eu castigarei esse homem e a sua família.

[[v24-23-35]]

^<<v24-23-35,35>>^ Assim dirá cada um de vocês ao seu amigo ou parente: ‘O que o Senhor respondeu? O que o Senhor falou? ’

[[v24-23-36]]

^<<v24-23-36,36>>^ Nunca mais mencionem a expressão ‘Esta é a mensagem da qual o Senhor me encarregou’, senão essa palavra se tornará uma ‘carga’ para aquele que a proferir; porque vocês distorcem as palavras do Deus vivo, do Senhor dos Exércitos, do nosso Deus.

[[v24-23-37]]

^<<v24-23-37,37>>^ É assim que vocês dirão ao profeta: ‘Qual é a resposta do Senhor para você? ’ ou ‘O que o Senhor falou? ’

[[v24-23-38]]

^<<v24-23-38,38>>^ Mas se vocês disserem ‘Esta é a mensagem da qual o Senhor me encarregou’, assim diz o Senhor: Vocês dizem: ‘Esta é a mensagem da qual o Senhor me encarregou’, quando eu lhes adverti que não dissessem isso.

[[v24-23-39]]

^<<v24-23-39,39>>^ Por isso me esquecerei de vocês e os lançarei fora da minha presença, juntamente com a cidade que dei a vocês e aos seus antepassados.

[[v24-23-40]]

^<<v24-23-40,40>>^ Trarei sobre vocês humilhação perpétua, vergonha permanente, que jamais será esquecida. "

'''

xref:024-jeremias/024-jeremias-022.adoc#v24-22-0[&#60; Capítulo Anterior] | <<v24-23-0,Topo>> | xref:024-jeremias/024-jeremias-024.adoc#v24-24-0[Próximo Capítulo &#62;]