include::./index.adoc[]

[[v24-3-0]]
=== Jeremias, 3
// nvi ?, NVI - Nova Versão Internacional

[[v24-3-1]]

^<<v24-3-1,1>>^ "Se um homem se divorciar de sua mulher, e, se ela, depois de deixá-lo, casar-se com outro homem, poderá o primeiro marido voltar para ela? Não seria a terra totalmente contaminada? Mas você tem se prostituído com muitos amantes e, agora, quer voltar para mim? ", pergunta o Senhor.

[[v24-3-2]]

^<<v24-3-2,2>>^ "Olhe para o campo e veja: Há algum lugar onde você não foi desonrada? À beira do caminho você se assentou à espera de amantes, assentou-se como um nômade no deserto. Você contaminou a terra com sua prostituição e impiedade.

[[v24-3-3]]

^<<v24-3-3,3>>^ Por isso as chuvas foram retidas, e não veio chuva na primavera. Mas você, apresentando-se declaradamente como prostituta, recusa-se a corar de vergonha.

[[v24-3-4]]

^<<v24-3-4,4>>^ Você não acabou de me chamar: ‘Meu pai, amigo da minha juventude,

[[v24-3-5]]

^<<v24-3-5,5>>^ ficarás irado para sempre? Teu ressentimento permanecerá até o fim? ’ É assim que você fala, mas faz todo o mal que pode. "

[[v24-3-6]]

^<<v24-3-6,6>>^ Durante o reinado do rei Josias, o Senhor me disse: "Você viu o que fez Israel, a infiel? Subiu todo monte elevado e foi para debaixo de toda árvore verdejante para prostituir-se.

[[v24-3-7]]

^<<v24-3-7,7>>^ Depois de ter feito tudo isso, pensei que ela voltaria para mim, mas não voltou. E a sua irmã traidora, Judá, viu essas coisas.

[[v24-3-8]]

^<<v24-3-8,8>>^ Viu também que dei à infiel Israel uma certidão de divórcio e a mandei embora, por causa de todos os seus adultérios. Entretanto, a sua irmã Judá, a traidora, e também se prostituiu, sem temor algum.

[[v24-3-9]]

^<<v24-3-9,9>>^ E por ter feito pouco caso da imoralidade, Judá contaminou a terra, cometendo adultério com ídolos de pedra e madeira.

[[v24-3-10]]

^<<v24-3-10,10>>^ Apesar de tudo isso, sua irmã Judá, a traidora, não voltou para mim todo o coração, mas sim com fingimento", declara o Senhor.

[[v24-3-11]]

^<<v24-3-11,11>>^ O Senhor me disse: "Israel, a infiel, é melhor do que Judá, a traidora.

[[v24-3-12]]

^<<v24-3-12,12>>^ Vá e proclame esta mensagem para os lados do norte: " ‘Volte, ó infiel Israel’, declara o Senhor, ‘Não mais franzirei a testa cheio de ira contra vocês, pois eu sou fiel’, declara o Senhor, ‘Não ficarei irado para sempre.

[[v24-3-13]]

^<<v24-3-13,13>>^ Mas reconheça o seu pecado: você se rebelou contra o Senhor, o seu Deus, e ofereceu os seus favores a deuses estranhos, debaixo de toda árvore verdejante, e não me obedeceu’ ", declara o Senhor.

[[v24-3-14]]

^<<v24-3-14,14>>^ "Voltem, filhos rebeldes! Pois eu sou o senhor de vocês", declara o Senhor. "Tomarei vocês, um de cada cidade e dois de cada clã, e os trarei de volta a Sião.

[[v24-3-15]]

^<<v24-3-15,15>>^ Então eu lhes darei governantes conforme a minha vontade, que os dirigirão com sabedoria e com entendimento.

[[v24-3-16]]

^<<v24-3-16,16>>^ Quando vocês aumentarem e se multiplicarem na sua terra naqueles dias", declara o Senhor, "não dirão mais: ‘A arca da aliança do Senhor’. Não pensarão mais nisso nem se lembrarão dela; não sentirão sua falta nem será feita outra arca.

[[v24-3-17]]

^<<v24-3-17,17>>^ Naquela época, chamarão Jerusalém ‘O Trono do Senhor’, e todas as nações se reunirão para honrar o nome do Senhor em Jerusalém. Não mais viverão segundo a obstinação de seus corações para fazer o mal.

[[v24-3-18]]

^<<v24-3-18,18>>^ Naqueles dias a comunidade de Judá caminhará com a comunidade de Israel, e juntas voltarão do norte para a terra que dei como herança aos seus antepassados. "

[[v24-3-19]]

^<<v24-3-19,19>>^ "Eu mesmo disse: "Com que alegria eu a trataria como se tratam filhos e lhe daria uma terra aprazível, a mais bela herança entre as nações. Pensei que você me chamaria de ‘Pai’ e que não deixaria de seguir-me.

[[v24-3-20]]

^<<v24-3-20,20>>^ Mas, como a mulher que trai o marido, assim vocês têm sido infiéis comigo, ó comunidade de Israel", declara o Senhor.

[[v24-3-21]]

^<<v24-3-21,21>>^ Ouve-se um choro no campo, o pranto de súplica dos israelitas, porque perverteram os seus caminhos e esqueceram o Senhor, o seu Deus.

[[v24-3-22]]

^<<v24-3-22,22>>^ "Voltem, filhos rebeldes! Eu os curarei da sua rebeldia. "Sim! Nós viremos a ti, pois tu és o Senhor, o nosso Deus.

[[v24-3-23]]

^<<v24-3-23,23>>^ De fato, a agitação idólatra nas colinas e o murmúrio nos montes é um engano. No Senhor, no nosso Deus, está a salvação de Israel.

[[v24-3-24]]

^<<v24-3-24,24>>^ Desde a nossa juventude, Baal, o deus da vergonha, tem consumido o fruto do trabalho dos nossos antepassados: as ovelhas, os bois, os seus filhos e as suas filhas.

[[v24-3-25]]

^<<v24-3-25,25>>^ Seja a vergonha a nossa cama e a desonra, o nosso cobertor. Pecamos contra o Senhor, o nosso Deus, tanto nós como os nossos antepassados, desde a nossa juventude até ao dia de hoje; e não temos obedecido ao Senhor, ao nosso Deus. "

'''

xref:024-jeremias/024-jeremias-002.adoc#v24-2-0[&#60; Capítulo Anterior] | <<v24-3-0,Topo>> | xref:024-jeremias/024-jeremias-004.adoc#v24-4-0[Próximo Capítulo &#62;]