include::./index.adoc[]

[[v24-2-0]]
=== Jeremias, 2
// nvi ?, NVI - Nova Versão Internacional

[[v24-2-1]]

^<<v24-2-1,1>>^ A palavra do Senhor veio a mim:

[[v24-2-2]]

^<<v24-2-2,2>>^ "Vá proclamar aos ouvidos de Jerusalém: "Eu me lembro de sua fidelidade quando você era jovem: como noiva, você me amava e me seguia pelo deserto, por uma terra não semeada.

[[v24-2-3]]

^<<v24-2-3,3>>^ Israel era santo para o Senhor, os primeiros frutos de sua colheita; todos os que o devoravam eram considerados culpados, e a desgraça os alcançava", declara o Senhor.

[[v24-2-4]]

^<<v24-2-4,4>>^ Ouçam a palavra do Senhor, ó comunidade de Jacó, todos os clãs da comunidade de Israel.

[[v24-2-5]]

^<<v24-2-5,5>>^ Assim diz o Senhor: "Que falta os seus antepassados encontraram em mim, para que me deixassem e se afastassem de mim? Eles seguiram ídolos sem valor, tornando-se eles próprios sem valor.

[[v24-2-6]]

^<<v24-2-6,6>>^ Eles não perguntaram: ‘Onde está o Senhor, que nos trouxe do Egito e nos conduziu pelo deserto, por uma terra árida e cheia de covas, terra de seca e de trevas, terra pela qual ninguém passa e onde ninguém vive? ’

[[v24-2-7]]

^<<v24-2-7,7>>^ Eu trouxe vocês a uma terra fértil, para que comessem dos seus frutos e dos seus bons produtos. Entretanto, vocês contaminaram a minha terra; tornaram a minha herança repugnante.

[[v24-2-8]]

^<<v24-2-8,8>>^ Os sacerdotes não perguntaram pelo Senhor; os intérpretes da lei não me conheciam, e os líderes do povo se rebelaram contra mim. Os profetas profetizavam em nome de Baal, seguindo deuses inúteis.

[[v24-2-9]]

^<<v24-2-9,9>>^ "Por isso, eu ainda faço denúncias contra vocês", diz o Senhor, "e farei denúncias contra os seus descendentes.

[[v24-2-10]]

^<<v24-2-10,10>>^ Atravessem o mar até o litoral de Chipre e vejam; mandem observadores a Quedar e reparem de perto; e vejam se alguma vez aconteceu algo assim:

[[v24-2-11]]

^<<v24-2-11,11>>^ Alguma nação já trocou os seus deuses? E eles nem sequer são deuses! Mas o meu povo trocou a sua Glória por deuses inúteis.

[[v24-2-12]]

^<<v24-2-12,12>>^ Espantem-se diante disso, ó céus! Fiquem horrorizados e abismados", diz o Senhor.

[[v24-2-13]]

^<<v24-2-13,13>>^ "O meu povo cometeu dois crimes: eles me abandonaram, a mim, a fonte de água viva; e cavaram as suas próprias cisternas, cisternas rachadas que não retêm água.

[[v24-2-14]]

^<<v24-2-14,14>>^ Acaso é Israel escravo, escravo de nascimento? Por que foi então que se tornou presa

[[v24-2-15]]

^<<v24-2-15,15>>^ de leões que rugem e urram contra ela? Arrasaram a sua terra, queimaram as suas cidades e as deixaram desabitadas.

[[v24-2-16]]

^<<v24-2-16,16>>^ Até mesmo os homens de Mênfis e de Tafnes raparam o seu crânio.

[[v24-2-17]]

^<<v24-2-17,17>>^ Não foi você mesma a responsável pelo que lhe aconteceu, ao abandonar o Senhor, o seu Deus?

[[v24-2-18]]

^<<v24-2-18,18>>^ Agora, por que você vai ao Egito para beber água do Nilo? E por que vai à Assíria para beber água do Eufrates?

[[v24-2-19]]

^<<v24-2-19,19>>^ O seu crime a castigará e a sua rebelião a repreenderá. Compreenda e veja como é mau e amargo abandonar o Senhor, o seu Deus, e não ter temor de mim", diz o Soberano, o Senhor dos Exércitos.

[[v24-2-20]]

^<<v24-2-20,20>>^ "Há muito tempo, eu quebrei o seu jugo e despedacei as correias que a prendiam. Mas você disse: "Eu não servirei! " Ao contrário, em todo monte elevado e debaixo de toda árvore verdejante, você se deitava como uma prostituta.

[[v24-2-21]]

^<<v24-2-21,21>>^ Eu a plantei como uma videira seleta, de semente absolutamente pura. Como, então, contra mim você se tornou uma videira degenerada e selvagem?

[[v24-2-22]]

^<<v24-2-22,22>>^ Mesmo que você se lave com soda e com muito sabão, a mancha da sua iniqüidade permanecerá diante de mim", diz o Soberano Senhor.

[[v24-2-23]]

^<<v24-2-23,23>>^ "Como você pode dizer que não está contaminada e que não correu atrás dos baalins? Reveja o seu procedimento no vale e considere o que você tem feito. Você é como uma camela jovem e arisca que corre para todos os lados;

[[v24-2-24]]

^<<v24-2-24,24>>^ como uma jumenta selvagem habituada ao deserto, cheirando o vento em seu desejo. Quem é capaz de controlá-la quando está no cio? Os machos que a procuram não precisam se cansar, porque logo encontrarão a que está no mês do cio.

[[v24-2-25]]

^<<v24-2-25,25>>^ Não deixe que os seus pés se esfolem nem que a sua garganta fique seca. Mas você disse: ‘Não adianta! Eu amo os deuses estrangeiros, e continuarei a ir atrás deles’.

[[v24-2-26]]

^<<v24-2-26,26>>^ "Assim como o ladrão fica envergonhado quando é apanhado em flagrante, também a comunidade de Israel ficará envergonhada: seus reis e oficiais, seus sacerdotes e profetas.

[[v24-2-27]]

^<<v24-2-27,27>>^ Pois dizem à madeira: ‘Você é meu pai’ e à pedra: ‘Você me deu à luz’. Voltaram para mim as costas e não o rosto, mas na hora da adversidade dizem: ‘Vem salvar-nos! ’

[[v24-2-28]]

^<<v24-2-28,28>>^ E onde estão os deuses que você fabricou para si? Que eles venham, se puderem salvá-la na hora da adversidade! Porque os seus deuses são tão numerosos como as suas cidades, ó Judá!

[[v24-2-29]]

^<<v24-2-29,29>>^ "Por que vocês fazem denúncias contra mim? Todos vocês se rebelaram contra mim", declara o Senhor.

[[v24-2-30]]

^<<v24-2-30,30>>^ "De nada adiantou castigar o seu povo, eles não aceitaram a correção. A sua espada tem destruído os seus profetas como um leão devorador.

[[v24-2-31]]

^<<v24-2-31,31>>^ "Vocês, desta geração, considerem a palavra do Senhor: "Tenho sido um deserto para Israel? Uma terra de grandes trevas? Por que o meu povo diz: ‘Nós assumimos o controle! Não mais viremos a ti’?

[[v24-2-32]]

^<<v24-2-32,32>>^ Será que uma jovem se esquece das suas jóias, ou uma noiva, de seus enfeites nupciais? Contudo, o meu povo esqueceu-se de mim, por dias sem fim.

[[v24-2-33]]

^<<v24-2-33,33>>^ Com quanta habilidade você busca o amor! Mesmo as mulheres da pior espécie aprenderam com o seu procedimento.

[[v24-2-34]]

^<<v24-2-34,34>>^ Nas suas roupas encontrou-se o sangue de pobres inocentes, os quais não foram flagrados arrombando casas. Contudo, apesar de tudo isso,

[[v24-2-35]]

^<<v24-2-35,35>>^ você diz: ‘Sou inocente; ele não está irado comigo’. Mas eu passarei sentença contra você porque você disse que não pecou.

[[v24-2-36]]

^<<v24-2-36,36>>^ Por que você não leva a sério a sua mudança de rumo? Você ficará decepcionada com o Egito, como ficou com a Assíria.

[[v24-2-37]]

^<<v24-2-37,37>>^ Você também deixará aquele lugar, com as mãos na cabeça, pois o Senhor rejeitou aqueles em quem você confia; você não receberá a ajuda deles.

'''

xref:024-jeremias/024-jeremias-001.adoc#v24-1-0[&#60; Capítulo Anterior] | <<v24-2-0,Topo>> | xref:024-jeremias/024-jeremias-003.adoc#v24-3-0[Próximo Capítulo &#62;]