include::./index.adoc[]

[[v24-25-0]]
=== Jeremias, 25
// nvi ?, NVI - Nova Versão Internacional

[[v24-25-1]]

^<<v24-25-1,1>>^ A palavra veio a Jeremias a respeito de todo o povo de Judá no quarto ano de Jeoaquim, filho de Josias, rei de Judá, que foi o primeiro ano de Nabucodonosor, rei da Babilônia.

[[v24-25-2]]

^<<v24-25-2,2>>^ O que o profeta Jeremias anunciou a todo o povo de Judá e aos habitantes de Jerusalém foi isto:

[[v24-25-3]]

^<<v24-25-3,3>>^ Durante vinte e três anos a palavra do Senhor tem vindo a mim, desde o décimo terceiro ano de Josias, filho de Amom, rei de Judá, até o dia de hoje. E eu a tenho anunciado a vocês, dia após dia, mas vocês não me deram ouvidos.

[[v24-25-4]]

^<<v24-25-4,4>>^ Embora o Senhor tenha enviado a vocês os seus servos, os profetas, dia após dia, vocês não os ouviram nem lhes deram atenção,

[[v24-25-5]]

^<<v24-25-5,5>>^ quando disseram: "Converta-se cada um do seu caminho mau e de suas más obras, e vocês permanecerão na terra que o Senhor deu a vocês e aos seus antepassados para sempre.

[[v24-25-6]]

^<<v24-25-6,6>>^ Não sigam outros deuses para prestar-lhes culto e adorá-los; não provoquem a minha ira com ídolos feitos por vocês. E eu não trarei desgraça sobre vocês".

[[v24-25-7]]

^<<v24-25-7,7>>^ "Mas vocês não me deram ouvidos e me provocaram à ira com os ídolos que vocês fizeram, trazendo desgraça sobre si mesmos", declara o Senhor.

[[v24-25-8]]

^<<v24-25-8,8>>^ Portanto, assim diz o Senhor dos Exércitos: "Visto que vocês não ouviram as minhas palavras,

[[v24-25-9]]

^<<v24-25-9,9>>^ convocarei todos os povos do norte e o meu servo Nabucodonosor, rei da Babilônia", declara o Senhor, "e os trarei para atacar esta terra, os seus habitantes e todas as nações ao redor. Eu os destruirei completamente e os farei um objeto de pavor e de zombaria, e uma ruína permanente.

[[v24-25-10]]

^<<v24-25-10,10>>^ Darei fim às vozes de júbilo e de alegria, às vozes do noivo e da noiva, ao som do moinho e à luz das candeias.

[[v24-25-11]]

^<<v24-25-11,11>>^ Toda esta terra se tornará uma ruína desolada, e essas nações estarão sujeitas ao rei da Babilônia durante setenta anos.

[[v24-25-12]]

^<<v24-25-12,12>>^ "Quando se completarem os setenta anos, castigarei o rei da Babilônia e a sua nação, a terra dos babilônios, por causa de suas iniqüidades", declara o Senhor, "e a deixarei arrasada para sempre.

[[v24-25-13]]

^<<v24-25-13,13>>^ Cumprirei naquela terra tudo o que falei contra ela, tudo o que está escrito neste livro e que Jeremias profetizou contra todas as nações.

[[v24-25-14]]

^<<v24-25-14,14>>^ Porque os próprios babilônios serão escravizados por muitas nações e grandes reis; eu lhes retribuirei conforme as suas ações e as suas obras".

[[v24-25-15]]

^<<v24-25-15,15>>^ Assim me disse o Senhor, o Deus de Israel: "Pegue de minha mão este cálice com o vinho da minha ira e faça com que bebam dele todas as nações a quem eu o envio.

[[v24-25-16]]

^<<v24-25-16,16>>^ Quando o beberem, ficarão cambaleando, enlouquecidos por causa da espada que enviarei entre elas".

[[v24-25-17]]

^<<v24-25-17,17>>^ Então peguei o cálice da mão do Senhor, e fiz com que dele bebessem todas as nações às quais o Senhor me enviou:

[[v24-25-18]]

^<<v24-25-18,18>>^ Jerusalém e as cidades de Judá, seus reis e seus líderes, para fazer deles uma desolação e um objeto de pavor, zombaria e maldição, como hoje acontece;

[[v24-25-19]]

^<<v24-25-19,19>>^ o faraó, o rei do Egito, seus conselheiros e seus líderes, todo o seu povo,

[[v24-25-20]]

^<<v24-25-20,20>>^ e todos os estrangeiros que lá residem; todos os reis de Uz; todos os reis dos filisteus: de Ascalom, Gaza, Ecrom e o povo que restou em Asdode;

[[v24-25-21]]

^<<v24-25-21,21>>^ Edom, Moabe e os amonitas,

[[v24-25-22]]

^<<v24-25-22,22>>^ os reis de Tiro e de Sidom; os reis das ilhas e das terras de além do mar;

[[v24-25-23]]

^<<v24-25-23,23>>^ Dedã, Temá, Buz e todos os que rapam a cabeça;

[[v24-25-24]]

^<<v24-25-24,24>>^ e os reis da Arábia e todos os reis dos estrangeiros que vivem no deserto;

[[v24-25-25]]

^<<v24-25-25,25>>^ todos os reis de Zinri, de Elão e da Média;

[[v24-25-26]]

^<<v24-25-26,26>>^ e todos os reis do norte, próximos ou distantes, um após outro; e todos os reinos da face da terra. Depois de todos eles, o rei de Sesaque também beberá do cálice.

[[v24-25-27]]

^<<v24-25-27,27>>^ "A seguir diga-lhes: ‘Assim diz o Senhor dos Exércitos, o Deus de Israel: Bebam, embriaguem-se, vomitem, caiam e não mais se levantem, por causa da espada que envio no meio de vocês’.

[[v24-25-28]]

^<<v24-25-28,28>>^ Mas se eles se recusarem a beber, diga-lhes: ‘Assim diz o Senhor dos Exércitos: Vocês vão bebê-lo!

[[v24-25-29]]

^<<v24-25-29,29>>^ Começo a trazer desgraça sobre a cidade que leva o meu nome; e vocês sairiam impunes? Sem dúvida não ficarão sem castigo! Estou trazendo a espada contra todos os habitantes da terra’, declara o Senhor dos Exércitos.

[[v24-25-30]]

^<<v24-25-30,30>>^ "E você, profetize todas estas palavras contra eles, dizendo: " ‘O Senhor ruge do alto; troveja de sua santa morada; ruge poderosamente contra a sua propriedade. Ele grita como os que pisam as uvas; grita contra todos os habitantes da terra.

[[v24-25-31]]

^<<v24-25-31,31>>^ Um tumulto ressoa até os confins da terra, pois o Senhor faz acusações contra as nações, e julga toda a humanidade: ele entregará os ímpios à espada’, declara o Senhor. "

[[v24-25-32]]

^<<v24-25-32,32>>^ Assim diz o Senhor: "Vejam! A desgraça está se espalhando de nação em nação; uma terrível tempestade se levanta desde os confins da terra".

[[v24-25-33]]

^<<v24-25-33,33>>^ Naquela dia, os mortos pelo Senhor estarão em todo lugar, de um lado ao outro da terra. Ninguém pranteará por eles, e não serão recolhidos e sepultados, mas servirão de esterco sobre o solo.

[[v24-25-34]]

^<<v24-25-34,34>>^ Lamentem-se e gritem, pastores! Rolem no pó, chefes do rebanho! Porque chegou para vocês o dia da matança e da sua dispersão; vocês cairão e serão esmigalhados como vasos finos.

[[v24-25-35]]

^<<v24-25-35,35>>^ Não haverá refúgio para os pastores nem escapatória para os chefes do rebanho.

[[v24-25-36]]

^<<v24-25-36,36>>^ Ouvem-se os gritos dos pastores e o lamento dos chefes do rebanho, pois o Senhor está destruindo as pastagens deles.

[[v24-25-37]]

^<<v24-25-37,37>>^ Os pastos tranqüilos estão devastados por causa do fogo da ira do Senhor.

[[v24-25-38]]

^<<v24-25-38,38>>^ Como um leão, ele saiu de sua toca; a terra deles ficou devastada, por causa da espada do opressor e do fogo de sua ira.

'''

xref:024-jeremias/024-jeremias-024.adoc#v24-24-0[&#60; Capítulo Anterior] | <<v24-25-0,Topo>> | xref:024-jeremias/024-jeremias-026.adoc#v24-26-0[Próximo Capítulo &#62;]