include::./index.adoc[]

[[v24-21-0]]
=== Jeremias, 21
// nvi ?, NVI - Nova Versão Internacional

[[v24-21-1]]

^<<v24-21-1,1>>^ Esta é a palavra que veio a Jeremias da parte do Senhor, quando o rei Zedequias enviou-lhe Pasur, filho de Malquias, e o sacerdote Sofonias, filho de Maaséias. Eles disseram:

[[v24-21-2]]

^<<v24-21-2,2>>^ "Consulte agora o Senhor por nós porque Nabucodonosor, rei da Babilônia, está nos atacando. Talvez o Senhor faça por nós uma de suas maravilhas e, assim, ele se retire de nós".

[[v24-21-3]]

^<<v24-21-3,3>>^ Jeremias, porém, respondeu-lhes: "Digam a Zedequias:

[[v24-21-4]]

^<<v24-21-4,4>>^ ‘Assim diz o Senhor, o Deus de Israel: Estou a ponto de voltar contra vocês as armas de guerra que estão em suas mãos, as quais vocês estão usando para combater o rei da Babilônia e os babilônios, os quais cercam vocês do lado de fora do muro. E eu os reunirei dentro desta cidade.

[[v24-21-5]]

^<<v24-21-5,5>>^ Eu mesmo lutarei contra vocês com mão poderosa e braço forte, com ira, furor e grande indignação.

[[v24-21-6]]

^<<v24-21-6,6>>^ Matarei os habitantes desta cidade, tanto homens como animais; eles morrerão de uma peste terrível.

[[v24-21-7]]

^<<v24-21-7,7>>^ Depois disso, declara o Senhor, entregarei Zedequias, rei de Judá, seus conselheiros e o povo desta cidade que sobreviver, à peste, à espada e à fome, e nas mãos de Nabucodonosor, rei da Babilônia, dos inimigos deles e daqueles que querem tirar-lhes a vida. Ele os matará à espada sem piedade nem misericórdia; não terá deles nenhuma compaixão’.

[[v24-21-8]]

^<<v24-21-8,8>>^ "Diga a este povo: ‘Assim diz o Senhor: Ponho diante de vocês o caminho da vida e o caminho da morte.

[[v24-21-9]]

^<<v24-21-9,9>>^ Todo aquele que ficar nesta cidade morrerá pela espada, pela fome ou pela peste. Mas todo o que sair e render-se aos babilônios, que os cercam vocês, viverá; este escapará com vida.

[[v24-21-10]]

^<<v24-21-10,10>>^ Decidi fazer o mal e não o bem a esta cidade, diz o Senhor. Ela será entregue nas mãos do rei da Babilônia, e ele a incendiará’.

[[v24-21-11]]

^<<v24-21-11,11>>^ "Digam à casa real de Judá: ‘Ouçam a palavra do Senhor.

[[v24-21-12]]

^<<v24-21-12,12>>^ Ó dinastia de Davi, assim diz o Senhor: " ‘Administrem justiça cada manhã: livrem o explorado das mãos do opressor; se não a minha ira se acenderá e queimará como fogo inextinguível, por causa do mal que vocês têm feito.

[[v24-21-13]]

^<<v24-21-13,13>>^ Eu estou contra você, Jerusalém! Você que está entronizada acima deste vale, na rocha do planalto, declara o Senhor, vocês que dizem: "Quem nos atacará? Quem poderá invadir nossas moradas? "

[[v24-21-14]]

^<<v24-21-14,14>>^ Eu os castigarei de acordo com as suas obras, diz o Senhor, Porei fogo em sua floresta, que consumirá tudo ao redor’ ".

'''

xref:024-jeremias/024-jeremias-020.adoc#v24-20-0[&#60; Capítulo Anterior] | <<v24-21-0,Topo>> | xref:024-jeremias/024-jeremias-022.adoc#v24-22-0[Próximo Capítulo &#62;]