include::./index.adoc[]

[[v24-9-0]]
=== Jeremias, 9
// nvi ?, NVI - Nova Versão Internacional

[[v24-9-1]]

^<<v24-9-1,1>>^ Ah, se a minha cabeça fosse uma fonte de água e os meus olhos um manancial de lágrimas! Eu choraria noite e dia pelos mortos do meu povo.

[[v24-9-2]]

^<<v24-9-2,2>>^ Ah, se houvesse um alojamento para mim no deserto, para que eu pudesse deixar o meu povo e afastar-me dele. São todos adúlteros, um bando de traidores!

[[v24-9-3]]

^<<v24-9-3,3>>^ "A língua deles é como um arco pronto para atirar. É a falsidade, não a verdade, que prevalece nesta terra. Eles vão de um crime a outro; eles não me reconhecem", declara o Senhor.

[[v24-9-4]]

^<<v24-9-4,4>>^ "Cuidado com os seus amigos, não confie em seus parentes. Porque cada parente é um enganador, e cada amigo um caluniador.

[[v24-9-5]]

^<<v24-9-5,5>>^ Amigo engana amigo, ninguém fala a verdade. Eles treinaram a língua para mentir; e, sendo perversos, eles se cansam demais para se converterem.

[[v24-9-6]]

^<<v24-9-6,6>>^ De opressão em opressão, de engano em engano, eles se recusam a reconhecer-me", declara o Senhor.

[[v24-9-7]]

^<<v24-9-7,7>>^ Portanto, assim diz o Senhor dos Exércitos: "Vejam, sou eu que os refinarei e os provarei. Que mais posso eu fazer pelo meu povo?

[[v24-9-8]]

^<<v24-9-8,8>>^ A língua deles é uma flecha mortal; eles falam traiçoeiramente. Cada um mostra-se cordial com o seu próximo, mas no íntimo lhe prepara uma armadilha.

[[v24-9-9]]

^<<v24-9-9,9>>^ Deixarei eu de castigá-los? ", pergunta o Senhor. "Não me vingarei de uma nação como essa? "

[[v24-9-10]]

^<<v24-9-10,10>>^ Chorarei, prantearei e me lamentarei pelos montes por causa das pastagens da estepe; pois estão abandonadas e ninguém mais as percorre. Não se ouve o mugir do gado; tanto as aves como os animais fugiram.

[[v24-9-11]]

^<<v24-9-11,11>>^ "Farei de Jerusalém um amontoado de ruínas, uma habitação de chacais. Devastarei as cidades de Judá até não restar nenhum morador. "

[[v24-9-12]]

^<<v24-9-12,12>>^ Quem é bastante sábio para compreender isso? Quem foi instruído pelo Senhor, que possa explicá-lo? Por que a terra está arruinada e devastada como um deserto pelo qual ninguém passa?

[[v24-9-13]]

^<<v24-9-13,13>>^ O Senhor disse: "Foi porque abandonaram a minha lei, que estabeleci diante deles; não me obedeceram nem seguiram a minha lei.

[[v24-9-14]]

^<<v24-9-14,14>>^ Em vez disso, seguiram a dureza de seus próprios corações, indo atrás dos baalins, como os seus antepassados lhes ensinaram".

[[v24-9-15]]

^<<v24-9-15,15>>^ Por isso, assim diz o Senhor dos Exércitos, o Deus de Israel: "Vejam! Farei este povo comer comida amarga e beber água envenenada.

[[v24-9-16]]

^<<v24-9-16,16>>^ Eu os espalharei entre nações que nem eles nem os seus antepassados conheceram; e enviarei contra eles a espada até exterminá-los".

[[v24-9-17]]

^<<v24-9-17,17>>^ Assim diz o Senhor dos Exércitos: "Considerem: Chamem as pranteadoras profissionais; mandem chamar as mais hábeis entre elas.

[[v24-9-18]]

^<<v24-9-18,18>>^ Venham elas depressa e lamentem por nós, até que os nossos olhos transbordem de lágrimas e águas corram de nossas pálpebras.

[[v24-9-19]]

^<<v24-9-19,19>>^ O som de lamento se ouve desde Sião: ‘Como estamos arruinados! Como é grande a nossa humilhação! Deixamos a nossa terra porque as nossas casas estão em ruínas’ ".

[[v24-9-20]]

^<<v24-9-20,20>>^ Ó mulheres, ouçam agora a palavra do Senhor; abram os ouvidos às palavras de sua boca. Ensinem suas filhas a lamentar-se; ensinem umas as outras a prantear.

[[v24-9-21]]

^<<v24-9-21,21>>^ A morte subiu e penetrou pelas nossas janelas e invadiu as nossas fortalezas, eliminando das ruas as crianças e das praças, os rapazes.

[[v24-9-22]]

^<<v24-9-22,22>>^ "Diga: ‘Assim declara o Senhor: " ‘Cadáveres ficarão estirados como esterco em campo aberto, como o trigo deixado para trás pelo ceifeiro, sem que ninguém o ajunte’. "

[[v24-9-23]]

^<<v24-9-23,23>>^ Assim diz o Senhor: "Não se glorie o sábio em sua sabedoria nem o forte em sua força nem o rico em sua riqueza,

[[v24-9-24]]

^<<v24-9-24,24>>^ mas quem se gloriar, glorie-se nisto: em compreender-me e conhecer-me, pois eu sou o Senhor, e ajo com lealdade, com justiça e com retidão sobre a terra, pois é dessas coisas que me agrado", declara o Senhor.

[[v24-9-25]]

^<<v24-9-25,25>>^ "Vêm chegando os dias", declara o Senhor, "em que castigarei todos os que são circuncidados apenas no corpo,

[[v24-9-26]]

^<<v24-9-26,26>>^ como também o Egito, Judá, Edom, Amom, Moabe e todos os que rapam a cabeça e vivem no deserto; porque todas essas nações são incircuncisas, e a comunidade de Israel tem o coração obstinado. "

'''

xref:024-jeremias/024-jeremias-008.adoc#v24-8-0[&#60; Capítulo Anterior] | <<v24-9-0,Topo>> | xref:024-jeremias/024-jeremias-010.adoc#v24-10-0[Próximo Capítulo &#62;]