include::./index.adoc[]

[[v24-49-0]]
=== Jeremias, 49
// nvi ?, NVI - Nova Versão Internacional

[[v24-49-1]]

^<<v24-49-1,1>>^ Acerca dos amonitas, assim diz o Senhor: "Por acaso Israel não tem filhos? Será que não tem herdeiros? Por que será então que Moloque se apossou de Gade? Por que seu povo vive nas cidades de Gade?

[[v24-49-2]]

^<<v24-49-2,2>>^ Portanto, certamente vêm os dias", declara o Senhor, "em que farei soar o grito de guerra contra Rabá dos amonitas; ela virá a ser uma pilha de ruínas, e os seus povoados ao redor serão incendiados. Então Israel expulsará aqueles que o expulsaram", diz o Senhor.

[[v24-49-3]]

^<<v24-49-3,3>>^ "Lamente, ó Hesbom, pois Ai está destruída! Gritem, ó moradores de Rabá! Ponham veste de lamento e chorem! Corram desorientados, pois Moloque irá para o exílio com os seus sacerdotes e os seus oficiais.

[[v24-49-4]]

^<<v24-49-4,4>>^ Por que você se orgulha de seus vales? Por que se orgulha de seus vales tão frutíferos? Ó filha infiel! Você confia em suas riquezas e diz: ‘Quem me atacará? ’

[[v24-49-5]]

^<<v24-49-5,5>>^ Farei com que você tenha pavor de tudo o que está a sua volta", diz o Senhor, o Senhor dos Exércitos. "Vocês serão dispersos, cada um numa direção, e ninguém conseguirá reunir os fugitivos.

[[v24-49-6]]

^<<v24-49-6,6>>^ "Contudo, depois disso, restaurarei a sorte dos amonitas", declara o Senhor.

[[v24-49-7]]

^<<v24-49-7,7>>^ Acerca de Edom, assim diz o Senhor dos Exércitos: "Será que já não há mais sabedoria em Temã? Será que o conselho desapareceu dos prudentes? A sabedoria deles deteriorou-se?

[[v24-49-8]]

^<<v24-49-8,8>>^ Voltem-se e fujam, escondam-se em cavernas profundas, vocês que moram em Dedã, pois trarei a ruína sobre Esaú na hora em que eu o castigar.

[[v24-49-9]]

^<<v24-49-9,9>>^ Se os que colhem uvas viessem até você, não deixariam eles apenas umas poucas uvas? Se os ladrões viessem durante a noite, não roubariam apenas o quanto desejassem?

[[v24-49-10]]

^<<v24-49-10,10>>^ Mas eu despi Esaú e descobri os seus esconderijos, para que ele não mais se esconda. Os seus filhos, parentes e vizinhos foram destruídos. Ninguém restou para dizer:

[[v24-49-11]]

^<<v24-49-11,11>>^ ‘Deixe os seus órfãos; eu protegerei a vida deles. As suas viúvas também podem confiar em mim’ ".

[[v24-49-12]]

^<<v24-49-12,12>>^ Assim diz o Senhor: "Se aqueles para quem o cálice não era reservado tiveram que bebê-lo, por que você deveria ficar impune? Você não ficará sem castigo, mas irá bebê-lo.

[[v24-49-13]]

^<<v24-49-13,13>>^ Eu juro por mim mesmo", declara o Senhor, "que Bozra ficará em ruínas e desolada; ela se tornará objeto de afronta e de maldição, e todas as suas cidades serão ruínas para sempre".

[[v24-49-14]]

^<<v24-49-14,14>>^ Ouvi uma mensagem da parte do Senhor: Um mensageiro foi mandado às nações para dizer: "Reúnam-se para atacar Edom! Preparem-se para a batalha! "

[[v24-49-15]]

^<<v24-49-15,15>>^ "Agora eu faço de você uma nação pequena entre as demais, desprezada pelos homens.

[[v24-49-16]]

^<<v24-49-16,16>>^ O pavor que você inspira e o orgulho de seu coração o enganaram, a você, que vive nas fendas das rochas, que ocupa os altos das colinas. Ainda que você, como a águia, faça o seu ninho nas alturas, de lá eu o derrubarei", declara o Senhor.

[[v24-49-17]]

^<<v24-49-17,17>>^ "Edom se tornará objeto de terror; todos os que por ali passarem ficarão chocados e zombarão por causa de todas as suas feridas.

[[v24-49-18]]

^<<v24-49-18,18>>^ Como a destruição de Sodoma e Gomorra, e as cidades vizinhas", diz o Senhor, "ninguém mais habitará ali, nenhum homem residirá nela.

[[v24-49-19]]

^<<v24-49-19,19>>^ "Assim como um leão que sobe da mata do Jordão em direção aos pastos verdejantes, subitamente eu caçarei Edom para fora de sua terra. Quem é o escolhido que designarei para isso? Quem é como eu que possa me desafiar? E que pastor pode me resistir? "

[[v24-49-20]]

^<<v24-49-20,20>>^ Por isso, ouçam o que o Senhor planejou contra Edom, o que preparou contra os habitantes de Temã: Os menores do rebanho serão arrastados, e as pastagens ficarão devastadas por causa deles.

[[v24-49-21]]

^<<v24-49-21,21>>^ Ao som de sua queda a terra tremerá; o grito deles ressoará até o mar Vermelho.

[[v24-49-22]]

^<<v24-49-22,22>>^ Vejam! Uma águia, subindo e planando, estende as asas sobre Bozra. Naquele dia, a coragem dos guerreiros de Edom será como a de uma mulher dando à luz.

[[v24-49-23]]

^<<v24-49-23,23>>^ Acerca de Damasco: "Hamate e Arpade estão atônitas, pois ouviram más notícias. Estão desencorajadas, perturbadas como o mar agitado.

[[v24-49-24]]

^<<v24-49-24,24>>^ Damasco tornou-se frágil, ela se virou para fugir, e o pânico tomou conta dela; angústia e dor dela se apoderaram, dor como a de uma mulher em trabalho de parto.

[[v24-49-25]]

^<<v24-49-25,25>>^ Como está abandonada a cidade famosa, a cidade da alegria!

[[v24-49-26]]

^<<v24-49-26,26>>^ Por isso, os seus jovens cairão nas ruas e todos os seus guerreiros se calarão naquele dia", declara o Senhor dos exércitos.

[[v24-49-27]]

^<<v24-49-27,27>>^ "Porei fogo nas muralhas de Damasco, que consumirá as fortalezas de Ben-Hadade. "

[[v24-49-28]]

^<<v24-49-28,28>>^ Acerca de Quedar e os reinos de Hazor, que Nabucodonosor, rei da Babilônia, derrotou, assim diz o Senhor: "Preparem-se, ataquem Quedar e destruam o povo do oriente.

[[v24-49-29]]

^<<v24-49-29,29>>^ Tomem suas tendas e seus rebanhos, suas cortinas com todos os seus utensílios e camelos. Gritam contra eles: ‘Há terror por todos os lados! ’

[[v24-49-30]]

^<<v24-49-30,30>>^ "Fujam rapidamente! Escondam-se em cavernas profundas, vocês habitantes de Hazor", diz o Senhor. "Nabucodonosor, rei da Babilônia, fez planos e projetos contra vocês.

[[v24-49-31]]

^<<v24-49-31,31>>^ "Preparem-se e ataquem uma nação que vive tranqüila e confiante", declara o Senhor, "uma nação que não tem portas nem trancas, e que vive sozinha.

[[v24-49-32]]

^<<v24-49-32,32>>^ Seus camelos se tornarão despojo e suas grandes manadas, espólio. Espalharei ao vento aqueles que raspam a cabeça, e de todos os lados trarei a ruína deles", declara o Senhor.

[[v24-49-33]]

^<<v24-49-33,33>>^ "Hazor se tornará uma habitação de chacais, uma ruína para sempre. Ninguém mais habitará ali, nenhum homem residirá nela. "

[[v24-49-34]]

^<<v24-49-34,34>>^ Esta é a palavra do Senhor que veio ao profeta Jeremias acerca de Elão, no início do reinado de Zedequias, rei de Judá:

[[v24-49-35]]

^<<v24-49-35,35>>^ Assim diz o Senhor dos Exércitos: "Vejam, quebrarei o arco de Elão, a base de seu poder.

[[v24-49-36]]

^<<v24-49-36,36>>^ Farei com que os quatro ventos, que vêm dos quatro cantos do céu, soprem contra Elão. E eu os dispersarei aos quatro ventos, e não haverá nenhuma nação para onde os exilados de Elão não forem.

[[v24-49-37]]

^<<v24-49-37,37>>^ Farei com que Elão trema diante dos seus inimigos, diante daqueles que desejam tirar-lhes a vida. Trarei a desgraça sobre eles, a minha ira ardente", declara o Senhor. "Farei com que a espada os persiga até que eu os tenha eliminado.

[[v24-49-38]]

^<<v24-49-38,38>>^ Porei meu trono em Elão e destruirei seu rei e líderes", declara o Senhor.

[[v24-49-39]]

^<<v24-49-39,39>>^ "Contudo restaurarei a sorte de Elão em dias vindouros", declara o Senhor.

'''

xref:024-jeremias/024-jeremias-048.adoc#v24-48-0[&#60; Capítulo Anterior] | <<v24-49-0,Topo>> | xref:024-jeremias/024-jeremias-050.adoc#v24-50-0[Próximo Capítulo &#62;]