include::./index.adoc[]

[[v24-13-0]]
=== Jeremias, 13
// nvi ?, NVI - Nova Versão Internacional

[[v24-13-1]]

^<<v24-13-1,1>>^ Assim me disse o Senhor: "Vá comprar um cinto de linho e ponha-o em volta da cintura, mas não o deixe encostar na água".

[[v24-13-2]]

^<<v24-13-2,2>>^ Comprei um cinto e o pus em volta da cintura, como o Senhor me havia instruído.

[[v24-13-3]]

^<<v24-13-3,3>>^ O Senhor me dirigiu a palavra pela segunda vez, dizendo:

[[v24-13-4]]

^<<v24-13-4,4>>^ "Pegue o cinto que você comprou e está usando, vá agora a Perate e esconda-o ali numa fenda da rocha".

[[v24-13-5]]

^<<v24-13-5,5>>^ Assim, fui e o escondi em Perate, conforme o Senhor me havia ordenado.

[[v24-13-6]]

^<<v24-13-6,6>>^ Depois de muitos dias, o Senhor me disse: "Vá agora a Perate e pegue o cinto que lhe ordenei que escondesse ali".

[[v24-13-7]]

^<<v24-13-7,7>>^ Então fui a Perate, desenterrei o cinto e o tirei do lugar em que o havia escondido. O cinto estava podre e se tornara completamente inútil.

[[v24-13-8]]

^<<v24-13-8,8>>^ E o Senhor dirigiu-me a palavra, dizendo:

[[v24-13-9]]

^<<v24-13-9,9>>^ "Assim diz o Senhor: Do mesmo modo também arruinarei o orgulho de Judá e o orgulho desmedido de Jerusalém.

[[v24-13-10]]

^<<v24-13-10,10>>^ Este povo ímpio, que se recusa a ouvir as minhas palavras, que age segundo a dureza de seus corações, seguindo outros deuses para prestar-lhes culto e adorá-los, que este povo seja como aquele cinto: completamente inútil!

[[v24-13-11]]

^<<v24-13-11,11>>^ Assim como um cinto se apega à cintura de um homem, da mesma forma fiz com que toda a comunidade de Israel e toda a comunidade de Judá se apegasse a mim, para que fosse o meu povo para o meu renome, louvor e honra. Mas eles não me ouviram", declara o Senhor.

[[v24-13-12]]

^<<v24-13-12,12>>^ "Diga-lhes também: ‘Assim diz o Senhor, o Deus de Israel: Deve-se encher de vinho toda vasilha de couro’. E, se eles lhe disserem: ‘Será que não sabemos que se deve encher de vinho toda vasilha de couro? ’

[[v24-13-13]]

^<<v24-13-13,13>>^ Então você lhes dirá: ‘Assim diz o Senhor: Farei com que fiquem totalmente embriagados todos os habitantes desta terra, bem como os reis que se assentam no trono de Davi, os sacerdotes, os profetas e todos os habitantes de Jerusalém.

[[v24-13-14]]

^<<v24-13-14,14>>^ Eu os despedaçarei, colocando uns contra os outros, os pais e os filhos, diz o Senhor. Nem a piedade, nem a misericórdia nem a compaixão me impedirão de destruí-los’ ".

[[v24-13-15]]

^<<v24-13-15,15>>^ Escutem e dêem atenção, não sejam arrogantes, pois o Senhor falou.

[[v24-13-16]]

^<<v24-13-16,16>>^ Dêem glória ao Senhor, ao seu Deus, antes que ele traga trevas, antes que os pés de vocês tropecem nas colinas ao escurecer. Vocês esperam a luz, mas ele fará dela uma escuridão profunda sim, ele a transformará em densas trevas.

[[v24-13-17]]

^<<v24-13-17,17>>^ Mas, se vocês não ouvirem, eu chorarei em segredo por causa do orgulho de vocês. Chorarei amargamente, e de lágrimas os meus olhos transbordarão, porque o rebanho do Senhor foi levado para o cativeiro.

[[v24-13-18]]

^<<v24-13-18,18>>^ Diga-se ao rei e à rainha-mãe: "Desçam do trono, pois as suas coroas gloriosas caíram de suas cabeças".

[[v24-13-19]]

^<<v24-13-19,19>>^ As cidades do Neguebe estão bloqueadas e não há quem nelas consiga entrar. Todo o Judá foi levado para o exílio, todos os exilados.

[[v24-13-20]]

^<<v24-13-20,20>>^ Erga os olhos, Jerusalém, e veja aqueles que vêm do norte. Onde está o rebanho que lhe foi confiado, as ovelhas das quais você se orgulhava?

[[v24-13-21]]

^<<v24-13-21,21>>^ O que você dirá quando sobre você dominarem aqueles que você sempre teve como aliados? Você não irá sentir dores como as de uma mulher em trabalho de parto?

[[v24-13-22]]

^<<v24-13-22,22>>^ E se você se perguntar: ‘Por que aconteceu isso comigo? ’, saiba que foi por causa dos seus muitos pecados que as suas vestes foram levantadas e você foi violentada.

[[v24-13-23]]

^<<v24-13-23,23>>^ Será que o etíope pode mudar a sua pele? Ou o leopardo as suas pintas? Assim também vocês são incapazes de fazer o bem, vocês que estão acostumados a praticar o mal.

[[v24-13-24]]

^<<v24-13-24,24>>^ "Espalharei vocês como a palha levada pelo vento do deserto.

[[v24-13-25]]

^<<v24-13-25,25>>^ Esta é a sua parte, a porção que lhe determinei", declara o Senhor, "porque você se esqueceu de mim e confiou em deuses falsos.

[[v24-13-26]]

^<<v24-13-26,26>>^ Eu mesmo levantarei as suas vestes até o seu rosto para que as suas vergonhas sejam expostas,

[[v24-13-27]]

^<<v24-13-27,27>>^ Tenho visto os seus atos repugnantes os seus adultérios, os seus relinchos, a sua prostituição desavergonhada sobre as colinas e nos campos. Ai de você, Jerusalém! Até quando você continuará impura? "

'''

xref:024-jeremias/024-jeremias-012.adoc#v24-12-0[&#60; Capítulo Anterior] | <<v24-13-0,Topo>> | xref:024-jeremias/024-jeremias-014.adoc#v24-14-0[Próximo Capítulo &#62;]