include::./index.adoc[]

[[v24-14-0]]
=== Jeremias, 14
// nvi ?, NVI - Nova Versão Internacional

[[v24-14-1]]

^<<v24-14-1,1>>^ Esta é a palavra que o Senhor dirigiu a Jeremias acerca da seca:

[[v24-14-2]]

^<<v24-14-2,2>>^ "Judá pranteia, as suas cidades estão definhando e os seus habitantes se lamentam, prostrados no chão! O grito de Jerusalém sobe.

[[v24-14-3]]

^<<v24-14-3,3>>^ Os nobres mandam os seus servos à procura de água; eles vão às cisternas mas nada encontram. Voltam com os potes vazios, e, decepcionados e desesperados, cobrem a cabeça.

[[v24-14-4]]

^<<v24-14-4,4>>^ A terra nada produziu, porque não houve chuva; e os lavradores, decepcionados, cobrem a cabeça.

[[v24-14-5]]

^<<v24-14-5,5>>^ Até mesmo a corça no campo abandona a cria recém-nascida, porque não há capim.

[[v24-14-6]]

^<<v24-14-6,6>>^ Os jumentos selvagens permanecem nos altos, farejando o vento como os chacais, mas a sua visão falha, por falta de pastagem".

[[v24-14-7]]

^<<v24-14-7,7>>^ Embora os nossos pecados nos acusem, age por amor do teu nome, ó Senhor! Nossas infidelidades são muitas; temos pecado contra ti.

[[v24-14-8]]

^<<v24-14-8,8>>^ Ó Esperança de Israel, tu que o salvas na hora da adversidade, por que te comportas como um estrangeiro na terra, ou como um viajante que fica somente uma noite?

[[v24-14-9]]

^<<v24-14-9,9>>^ Por que ages como um homem que foi pego de surpresa, como um guerreiro que não pode salvar? Tu estás em nosso meio, ó Senhor, e nós pertencemos a ti; não nos abandones!

[[v24-14-10]]

^<<v24-14-10,10>>^ Assim diz o Senhor acerca deste povo: "Eles gostam muito de vaguear; não controlam os pés. Por isso o Senhor não os aceita; agora ele se lembrará da iniqüidade deles e os castigará por causa dos seus pecados".

[[v24-14-11]]

^<<v24-14-11,11>>^ Então o Senhor me disse: "Não ore pelo bem-estar deste povo.

[[v24-14-12]]

^<<v24-14-12,12>>^ Ainda que jejuem, não escutarei o clamor deles; ainda que ofereçam holocaustos e ofertas de cereal, não os aceitarei. Mas eu os destruirei pela guerra, pela fome e pela peste".

[[v24-14-13]]

^<<v24-14-13,13>>^ Mas eu disse: "Ah, Soberano Senhor, os profetas estão dizendo a eles: ‘Vocês não verão a guerra nem a fome; eu lhes darei prosperidade duradoura neste lugar’ ".

[[v24-14-14]]

^<<v24-14-14,14>>^ Então o Senhor me disse: "É mentira o que os profetas estão profetizando em meu nome. Eu não os enviei nem lhes dei ordem nenhuma, nem falei com eles. Eles estão profetizando para vocês falsas visões, adivinhações inúteis e ilusões de suas próprias mentes".

[[v24-14-15]]

^<<v24-14-15,15>>^ Por isso, assim diz o Senhor: "Quanto aos profetas que estão profetizando em meu nome, embora eu não os tenha enviado, e que dizem: ‘Nem guerra nem fome alcançarão esta terra’, aqueles mesmos profetas perecerão pela guerra e pela fome!

[[v24-14-16]]

^<<v24-14-16,16>>^ E aqueles a quem estão profetizando serão jogados nas ruas de Jerusalém, por causa da fome e da guerra. E não haverá ninguém para sepultá-los, nem para sepultar as suas mulheres, os seus filhos e as suas filhas. Despejarei sobre eles o castigo que merecem.

[[v24-14-17]]

^<<v24-14-17,17>>^ "Diga-lhes isto: " ‘Que os meus olhos derramem lágrimas, noite e dia sem cessar; pois a minha filha virgem, o meu povo, sofreu um ferimento terrível, um golpe fatal.

[[v24-14-18]]

^<<v24-14-18,18>>^ Se vou para o campo, vejo os que morreram pela espada; se entro na cidade, vejo a devastação da fome. Tanto o profeta como o sacerdote percorrem a terra sem nada compreender’ ".

[[v24-14-19]]

^<<v24-14-19,19>>^ Rejeitaste Judá completamente? Desprezaste Sião? Por que nos feriste a ponto de não podermos ser curados? Esperávamos a paz, mas não veio bem algum; esperávamos um tempo de cura, mas há somente terror.

[[v24-14-20]]

^<<v24-14-20,20>>^ Senhor, reconhecemos a nossa impiedade e a iniqüidade dos nossos pais; temos de fato pecado contra ti.

[[v24-14-21]]

^<<v24-14-21,21>>^ Por amor do teu nome não nos desprezes; não desonres o teu trono glorioso. Lembra-te da tua aliança conosco e não a quebres.

[[v24-14-22]]

^<<v24-14-22,22>>^ Entre os ídolos inúteis das nações, existe algum que possa trazer chuva? Podem os céus, por si mesmos, produzir chuvas copiosas? Somente tu o podes, Senhor, nosso Deus! Portanto, a nossa esperança está em ti, pois tu fazes todas essas coisas.

'''

xref:024-jeremias/024-jeremias-013.adoc#v24-13-0[&#60; Capítulo Anterior] | <<v24-14-0,Topo>> | xref:024-jeremias/024-jeremias-015.adoc#v24-15-0[Próximo Capítulo &#62;]