include::./index.adoc[]

[[v24-35-0]]
=== Jeremias, 35
// nvi ?, NVI - Nova Versão Internacional

[[v24-35-1]]

^<<v24-35-1,1>>^ Durante o reinado de Jeoaquim, filho de Josias, rei de Judá, o Senhor dirigiu esta palavra a Jeremias:

[[v24-35-2]]

^<<v24-35-2,2>>^ "Vá à comunidade dos recabitas e convide-os a virem a uma das salas do templo do Senhor, e ofereça-lhes vinho para beber".

[[v24-35-3]]

^<<v24-35-3,3>>^ Então busquei Jazanias, filho de Jeremias, filho de Habazinias, seus irmãos e todos os seus filhos e toda a comunidade dos recabitas.

[[v24-35-4]]

^<<v24-35-4,4>>^ Eu os levei ao templo do Senhor, à sala dos filhos de Hanã, filho de Jigdalias, homem de Deus. A sala ficava ao lado da sala dos líderes e debaixo da sala de Maaséias, filho de Salum, o porteiro.

[[v24-35-5]]

^<<v24-35-5,5>>^ Então, coloquei vasilhas cheias de vinho e alguns copos diante dos membros da comunidade dos recabitas e lhes pedi que bebessem.

[[v24-35-6]]

^<<v24-35-6,6>>^ Eles, porém, disseram: "Não bebemos vinho porque o nosso antepassado Jonadabe, filho de Recabe, nos deu esta ordem: ‘Nem vocês nem os seus descendentes beberão vinho.

[[v24-35-7]]

^<<v24-35-7,7>>^ Vocês não construirão casas nem semearão; não plantarão vinhas nem as possuirão; mas vocês sempre habitarão em tendas. Assim vocês viverão por muito tempo na terra na qual são nômades’.

[[v24-35-8]]

^<<v24-35-8,8>>^ Temos obedecido a tudo o que nos ordenou nosso antepassado Jonadabe, filho de Recabe. Nós, nossas mulheres, nossos filhos e nossas filhas jamais bebemos vinho em toda a nossa vida,

[[v24-35-9]]

^<<v24-35-9,9>>^ não construímos casas para nossa moradia nem possuímos vinhas, campos ou plantações.

[[v24-35-10]]

^<<v24-35-10,10>>^ Temos vivido em tendas e obedecido fielmente a tudo o que nosso antepassado Jonadabe nos ordenou.

[[v24-35-11]]

^<<v24-35-11,11>>^ Mas, quando Nabucodonosor, rei da Babilônia, invadiu esta terra, dissemos: ‘Venham, vamos para Jerusalém para escapar dos exércitos dos babilônios e dos sírios’. Assim, permanecemos em Jerusalém".

[[v24-35-12]]

^<<v24-35-12,12>>^ O Senhor dirigiu a palavra a Jeremias, dizendo:

[[v24-35-13]]

^<<v24-35-13,13>>^ "Assim diz o Senhor dos Exércitos, Deus de Israel: Vá dizer aos homens de Judá e aos habitantes de Jerusalém: ‘Será que vocês não vão aprender a lição e obedecer às minhas palavras? ’, pergunta o Senhor.

[[v24-35-14]]

^<<v24-35-14,14>>^ ‘Jonadabe, filho de Recabe, ordenou a seus filhos que não bebessem vinho, e essa ordem tem sido obedecida até hoje. Eles não bebem vinho porque obedecem à ordem do seu antepassado. Mas eu tenho falado a vocês repetidas vezes, e, contudo, vocês não me obedecem.

[[v24-35-15]]

^<<v24-35-15,15>>^ Enviei a vocês, repetidas vezes, todos os meus servos, os profetas. Eles lhes diziam que cada um de vocês deveria converter-se da sua má conduta, corrigir as suas ações e deixar de seguir outros deuses para prestar-lhes culto. Assim, vocês habitariam na terra que dei a vocês e a seus antepassados. Mas vocês não me deram atenção nem me obedeceram.

[[v24-35-16]]

^<<v24-35-16,16>>^ Os descendentes de Jonadabe, filho de Recabe, cumprem a ordem que o seu antepassado lhes deu, mas este povo não me obedece. ’

[[v24-35-17]]

^<<v24-35-17,17>>^ "Portanto, assim diz o Senhor dos Exércitos, Deus de Israel: ‘Trarei sobre Judá e sobre todos os habitantes de Jerusalém toda a desgraça da qual os adverti; porque falei a eles, mas não me ouviram, chamei-os, mas não me responderam’ ".

[[v24-35-18]]

^<<v24-35-18,18>>^ Jeremias disse à comunidade dos recabitas: "Assim diz o Senhor dos Exércitos, Deus de Israel: ‘Vocês têm obedecido àquele que ordenou o seu antepassado Jonadabe; têm cumprido todas as suas instruções e têm feito tudo o que ele ordenou’.

[[v24-35-19]]

^<<v24-35-19,19>>^ Por isso, assim diz o Senhor dos Exércitos, Deus de Israel: ‘Jamais faltará a Jonadabe, filho de Recabe, um descendente que me sirva’ ".

'''

xref:024-jeremias/024-jeremias-034.adoc#v24-34-0[&#60; Capítulo Anterior] | <<v24-35-0,Topo>> | xref:024-jeremias/024-jeremias-036.adoc#v24-36-0[Próximo Capítulo &#62;]