include::./index.adoc[]

[[v24-7-0]]
=== Jeremias, 7
// nvi ?, NVI - Nova Versão Internacional

[[v24-7-1]]

^<<v24-7-1,1>>^ Esta é a palavra que veio a Jeremias da parte do Senhor:

[[v24-7-2]]

^<<v24-7-2,2>>^ "Fique junto à porta o templo do Senhor e proclame esta mensagem: " ‘Ouçam a palavra do Senhor, todos vocês de Judá que atravessam estas portas para adorar o Senhor.

[[v24-7-3]]

^<<v24-7-3,3>>^ Assim diz o Senhor dos Exércitos, o Deus de Israel: Corrijam a sua conduta e as suas ações, eu os farei habitar neste lugar.

[[v24-7-4]]

^<<v24-7-4,4>>^ Não confiem em palavras enganosas: "Este é o templo do Senhor, o templo do Senhor, o templo do Senhor! "

[[v24-7-5]]

^<<v24-7-5,5>>^ Mas se vocês realmente corrigirem a sua conduta e as suas ações, e se, de fato, tratarem uns aos outros com justiça,

[[v24-7-6]]

^<<v24-7-6,6>>^ se não oprimirem o estrangeiro, o órfão e a viúva e não derramarem sangue inocente neste lugar, e se vocês não seguirem outros deuses para a sua própria ruína,

[[v24-7-7]]

^<<v24-7-7,7>>^ então eu os farei habitar neste lugar, na terra que dei aos seus antepassados desde a antigüidade e para sempre.

[[v24-7-8]]

^<<v24-7-8,8>>^ Mas vejam! Vocês confiam em palavras enganosas e inúteis.

[[v24-7-9]]

^<<v24-7-9,9>>^ " ‘Vocês pensam que podem roubar e matar, cometer adultério e jurar falsamente, queimar incenso a Baal e seguir outros deuses que vocês não conheceram,

[[v24-7-10]]

^<<v24-7-10,10>>^ e depois vir e permanecer perante mim neste templo, que leva o meu nome, e dizer: Estamos seguros!, seguros para continuar com todas essas práticas repugnantes?

[[v24-7-11]]

^<<v24-7-11,11>>^ Esse templo, que leva o meu nome, tornou-se para vocês um covil de ladrões? Cuidado! Eu mesmo estou vendo isso’ ", declara o Senhor.

[[v24-7-12]]

^<<v24-7-12,12>>^ " ‘Portanto, vão agora a Siló, o meu lugar de adoração, onde primeiro fiz uma habitação em honra do meu nome, e vejam o que eu lhe fiz por causa da impiedade de Israel, meu povo.

[[v24-7-13]]

^<<v24-7-13,13>>^ Mas agora, visto que vocês fizeram todas essas coisas, diz o Senhor, apesar de eu lhes ter falado repetidas vezes, e vocês não me terem dado atenção, e de eu lhes ter chamado, e vocês não me terem respondido,

[[v24-7-14]]

^<<v24-7-14,14>>^ eu farei a este templo que leva o meu nome, no qual vocês confiam, o lugar de adoração que dei a vocês e aos seus antepassados, o mesmo que fiz a Siló.

[[v24-7-15]]

^<<v24-7-15,15>>^ Expulsarei vocês da minha presença, como fiz com todos os seus compatriotas, o povo de Efraim’.

[[v24-7-16]]

^<<v24-7-16,16>>^ "Mas a você, Jeremias, não ore por este povo nem faça súplicas ou pedidos em favor dele, nem interceda por ele junto a mim, pois eu não o ouvirei.

[[v24-7-17]]

^<<v24-7-17,17>>^ Não vê o que estão fazendo nas cidades de Judá e nas ruas de Jerusalém?

[[v24-7-18]]

^<<v24-7-18,18>>^ Os filhos ajuntam a lenha, os pais acendem o fogo, e as mulheres preparam a massa e fazem bolos para a Rainha dos Céus. Além disso, derramam ofertas a outros deuses para provocarem a minha ira.

[[v24-7-19]]

^<<v24-7-19,19>>^ Mas será que é a mim que eles estão provocando?, pergunta o Senhor. Não é a si mesmos, para a sua própria vergonha?

[[v24-7-20]]

^<<v24-7-20,20>>^ " ‘Portanto, assim diz o Soberano Senhor: A minha ardente ira será derramada sobre este lugar, sobre os homens, os animais, e as árvores do campo, como também sobre o produto do solo; ela arderá como fogo, e não poderá ser extinguida.

[[v24-7-21]]

^<<v24-7-21,21>>^ " ‘Assim diz o Senhor dos Exércitos, o Deus de Israel: Juntem os seus holocaustos aos outros sacrifícios e comam a carne vocês mesmos!

[[v24-7-22]]

^<<v24-7-22,22>>^ Quando tirei do Egito os seus antepassados, nada lhes falei nem lhes ordenei quanto a holocaustos e sacrifícios.

[[v24-7-23]]

^<<v24-7-23,23>>^ Dei-lhes, entretanto, esta ordem: Obedeçam-me, e eu serei o seu Deus e vocês serão o meu povo. Vocês andarão em todo o caminho que eu lhes ordenar, para que tudo lhes vá bem.

[[v24-7-24]]

^<<v24-7-24,24>>^ Mas eles não me ouviram nem me deram atenção. Antes, seguiram o raciocínio rebelde dos seus corações maus. Andaram para trás e não para a frente.

[[v24-7-25]]

^<<v24-7-25,25>>^ Desde a época em que os seus antepassados saíram do Egito até o dia de hoje, eu lhes enviei os meus servos, os profetas, dia após dia.

[[v24-7-26]]

^<<v24-7-26,26>>^ Mas eles não me ouviram nem me deram atenção. Antes tornaram-se obstinados e foram piores do que os antepassados deles’.

[[v24-7-27]]

^<<v24-7-27,27>>^ "Quando você lhes disser tudo isso, eles não o escutarão; quando você os chamar, não responderão.

[[v24-7-28]]

^<<v24-7-28,28>>^ Portanto, diga a eles: ‘Esta é uma nação que não obedeceu ao Senhor, ao seu Deus, nem aceitou a correção. A verdade foi destruída e desapareceu dos seus lábios.

[[v24-7-29]]

^<<v24-7-29,29>>^ Cortem os seus cabelos consagrados e joguem-os fora. Lamentem-se sobre os montes estéreis, pois o Senhor rejeitou e abandonou esta geração que provocou a sua ira.

[[v24-7-30]]

^<<v24-7-30,30>>^ " ‘Os de Judá fizeram o que eu reprovo, declara o Senhor. Profanaram o templo que leva o meu nome, colocando nele as imagens dos seus ídolos.

[[v24-7-31]]

^<<v24-7-31,31>>^ Construíram o alto de Tofete no vale de Ben-Hinom, para queimarem em sacrifício os seus filhos e as suas filhas, coisa que nunca ordenei e que jamais me veio à mente.

[[v24-7-32]]

^<<v24-7-32,32>>^ Por isso, certamente vêm os dias, declara o Senhor, em que não mais chamarão este lugar Tofete ou vale de Ben-Hinom, mas vale da Matança, pois ali enterrarão cadáveres até que não haja mais lugar.

[[v24-7-33]]

^<<v24-7-33,33>>^ Então os cadáveres deste povo servirão de comida para as aves e para os animais, e não haverá quem os afugente.

[[v24-7-34]]

^<<v24-7-34,34>>^ Darei fim às vozes de júbilo e de alegria, às vozes do noivo e da noiva nas cidades de Judá e nas ruas de Jerusalém, pois esta terra se tornará um deserto.

'''

xref:024-jeremias/024-jeremias-006.adoc#v24-6-0[&#60; Capítulo Anterior] | <<v24-7-0,Topo>> | xref:024-jeremias/024-jeremias-008.adoc#v24-8-0[Próximo Capítulo &#62;]