include::./index.adoc[]

[[v24-51-0]]
=== Jeremias, 51
// nvi ?, NVI - Nova Versão Internacional

[[v24-51-1]]

^<<v24-51-1,1>>^ Assim diz o Senhor: "Vejam! Levantarei um vento destruidor contra a Babilônia, contra o povo de Lebe-Camai.

[[v24-51-2]]

^<<v24-51-2,2>>^ Enviarei estrangeiros para a Babilônia a fim de peneirá-la como trigo e devastar a sua terra. No dia de sua desgraça virão contra ela de todos os lados.

[[v24-51-3]]

^<<v24-51-3,3>>^ Que o arqueiro não arme o seu arco nem vista a sua armadura. Não poupem os seus jovens guerreiros, destruam completamente o seu exército.

[[v24-51-4]]

^<<v24-51-4,4>>^ Eles cairão mortos na Babilônia, mortalmente feridos em suas ruas.

[[v24-51-5]]

^<<v24-51-5,5>>^ Israel e Judá não foram abandonadas como viúvas pelo seu Deus, o Senhor dos Exércitos, embora a terra dos babilônios esteja cheia de culpa diante do Santo de Israel.

[[v24-51-6]]

^<<v24-51-6,6>>^ "Fujam da Babilônia! Cada um por si! Não sejam destruídos por causa da iniqüidade dela. É hora da vingança do Senhor; ele pagará a ela o que ela merece.

[[v24-51-7]]

^<<v24-51-7,7>>^ A Babilônia era um cálice de ouro nas mãos do Senhor; ela embriagou a terra toda. As nações beberam o seu vinho; por isso agora, enlouqueceram.

[[v24-51-8]]

^<<v24-51-8,8>>^ A Babilônia caiu de repente e ficou arruinada. Lamentem por ela! Consigam bálsamo para a ferida dela; talvez ela possa ser curada.

[[v24-51-9]]

^<<v24-51-9,9>>^ "Gostaríamos de ter curado Babilônia, mas ela não pode ser curada; deixem-na e vamos cada um para a sua própria terra, pois o julgamento dela chega ao céu, eleva-se tão alto quanto as nuvens.

[[v24-51-10]]

^<<v24-51-10,10>>^ "O Senhor defendeu o nosso nome; venham, contemos em Sião o que o Senhor, o nosso Deus, tem feito.

[[v24-51-11]]

^<<v24-51-11,11>>^ "Afiem as flechas, peguem os escudos! O Senhor incitou o espírito dos reis dos medos, porque seu propósito é destruir a Babilônia. O Senhor se vingará, se vingará de seu templo.

[[v24-51-12]]

^<<v24-51-12,12>>^ Ergam o sinal para atacar as muralhas da Babilônia! Reforcem a guarda! Posicionem as sentinelas! Preparem uma emboscada! O Senhor executará o seu plano, o que ameaçou fazer contra os habitantes da Babilônia.

[[v24-51-13]]

^<<v24-51-13,13>>^ Você que vive junto a muitas águas e está rico de tesouros, chegou o seu fim, a hora de você ser eliminado.

[[v24-51-14]]

^<<v24-51-14,14>>^ O Senhor dos Exércitos jurou por si mesmo: com certeza a encherei de homens, como com um enxame de gafanhotos, e eles gritarão triunfante sobre você.

[[v24-51-15]]

^<<v24-51-15,15>>^ "Mas foi Deus quem fez a terra com o seu poder; firmou o mundo com a sua sabedoria e estendeu os céus com o seu entendimento.

[[v24-51-16]]

^<<v24-51-16,16>>^ Ao som do seu trovão, as águas no céu rugem; ele faz com que as nuvens se levantem desde os confins da terra. Ele faz relâmpagos para a chuva e faz sair o vento de seus depósitos.

[[v24-51-17]]

^<<v24-51-17,17>>^ "São todos eles estúpidos e ignorantes; cada ourives é envergonhado pela imagem que esculpiu. Suas imagens esculpidas são uma fraude, elas não têm fôlego de vida.

[[v24-51-18]]

^<<v24-51-18,18>>^ Elas são inúteis, são objetos de zombaria. Quando vier o julgamento delas, perecerão.

[[v24-51-19]]

^<<v24-51-19,19>>^ Aquele que é a Porção de Jacó não é como esses, pois ele é quem forma todas as coisas, e Israel é a tribo de sua propriedade; o Senhor dos Exércitos é o seu nome.

[[v24-51-20]]

^<<v24-51-20,20>>^ "Você é o meu martelo, a minha arma de guerra. Com você eu despedaço nações, com você eu destruo reinos,

[[v24-51-21]]

^<<v24-51-21,21>>^ com você despedaço cavalo e cavaleiro, com você despedaço carro de guerra e cocheiro,

[[v24-51-22]]

^<<v24-51-22,22>>^ com você despedaço homem e mulher, com você despedaço velho e jovem, com você despedaço rapaz e moça,

[[v24-51-23]]

^<<v24-51-23,23>>^ com você despedaço pastor e rebanho, com você despedaço lavrador e bois, com você despedaço governadores e oficiais.

[[v24-51-24]]

^<<v24-51-24,24>>^ "Retribuirei à Babilônia e a todos os que vivem na Babilônia por toda a maldade que fizeram em Sião diante dos olhos de vocês", declara o Senhor.

[[v24-51-25]]

^<<v24-51-25,25>>^ "Estou contra você, ó montanha destruidora, você que destrói a terra inteira", declara o Senhor. "Estenderei minha mão contra você, eu a farei rolar dos penhascos, e farei de você uma montanha calcinada.

[[v24-51-26]]

^<<v24-51-26,26>>^ Nenhuma pedra sua será cortada para servir de pedra angular, nem para um alicerce, pois você estará arruinada para sempre", declara o Senhor.

[[v24-51-27]]

^<<v24-51-27,27>>^ "Ergam um estandarte na terra! Toquem a trombeta entre as nações! Preparem as nações para o combate contra ela; convoquem contra ela estes reinos: Ararate, Mini e Asquenaz. Nomeiem um comandante contra ela; lancem os cavalos ao ataque como um enxame de gafanhotos.

[[v24-51-28]]

^<<v24-51-28,28>>^ Preparem as nações para o combate contra ela: os reis dos medos, seus governadores e todos os seus oficiais, e todos os países que governam.

[[v24-51-29]]

^<<v24-51-29,29>>^ A terra treme e se contorce de dor, pois permanecem de pé os planos do Senhor contra a Babilônia: desolar a terra da Babilônia para que fique desabitada.

[[v24-51-30]]

^<<v24-51-30,30>>^ Os guerreiros da Babilônia pararam de lutar; permanecem em suas fortalezas. A força deles acabou; tornaram-se como mulheres. As habitações dela estão incendiadas; as trancas de suas portas estão quebradas.

[[v24-51-31]]

^<<v24-51-31,31>>^ Um emissário vai após outro, e um mensageiro sai após outro mensageiro para anunciar ao rei da Babilônia que sua cidade inteira foi capturada,

[[v24-51-32]]

^<<v24-51-32,32>>^ os pontos de cruzar o rio foram tomados, a vegetação dos pântanos foi incendiada, e os soldados ficaram aterrorizados. "

[[v24-51-33]]

^<<v24-51-33,33>>^ Assim diz o Senhor dos Exércitos, Deus de Israel: "A cidade de Babilônia é como uma eira a época da colheita logo chegará para ela.

[[v24-51-34]]

^<<v24-51-34,34>>^ "Nabucodonosor, rei da Babilônia, devorou-nos, lançou-nos em confusão, fez de nós um jarro vazio. Tal como uma serpente ele nos engoliu e encheu seu estômago com nossas finas comidas e então nos vomitou.

[[v24-51-35]]

^<<v24-51-35,35>>^ Que a violência cometida à nossa carne esteja sobre a Babilônia", dizem os habitantes de Sião. "Que o nosso sangue esteja sobre aqueles que moram na Babilônia", diz Jerusalém.

[[v24-51-36]]

^<<v24-51-36,36>>^ Por isso, assim diz o Senhor: "Vejam, defenderei a causa de vocês e os vingarei; secarei o seu mar e esgotarei as suas fontes.

[[v24-51-37]]

^<<v24-51-37,37>>^ A Babilônia se tornará um amontoado de ruínas, uma habitação de chacais, objeto de pavor e de zombaria, um lugar onde ninguém vive.

[[v24-51-38]]

^<<v24-51-38,38>>^ O seu povo todo ruge como leõezinhos, rosnam como filhotes de leão.

[[v24-51-39]]

^<<v24-51-39,39>>^ Mas, enquanto estiverem excitados, prepararei um banquete para eles e os deixarei bêbados, para que fiquem bem alegres e, então, durmam e jamais acordem", declara o Senhor.

[[v24-51-40]]

^<<v24-51-40,40>>^ "Eu os levarei como cordeiros para o matadouro, como carneiros e bodes.

[[v24-51-41]]

^<<v24-51-41,41>>^ "Como Sesaque será capturada, o orgulho de toda a terra tomado! Que horror a Babilônia será entre as nações!

[[v24-51-42]]

^<<v24-51-42,42>>^ O mar se levantará sobre a Babilônia; suas ondas agitadas a cobrirão.

[[v24-51-43]]

^<<v24-51-43,43>>^ Suas cidades serão arrasadas, uma terra seca e deserta, uma terra onde ninguém mora, pela qual nenhum homem passa.

[[v24-51-44]]

^<<v24-51-44,44>>^ Castigarei Bel na Babilônia e o farei vomitar o que engoliu. As nações não mais acorrerão a ele. E a muralha da Babilônia cairá.

[[v24-51-45]]

^<<v24-51-45,45>>^ "Saia dela, meu povo! Cada um salve a sua própria vida, da ardente ira do Senhor.

[[v24-51-46]]

^<<v24-51-46,46>>^ Não desanimem nem tenham medo quando ouvirem rumores na terra; um rumor chega este ano, outro no próximo, rumor de violência na terra e de governante contra governante.

[[v24-51-47]]

^<<v24-51-47,47>>^ Portanto, certamente vêm os dias quando castigarei as imagens esculpidas da Babilônia; toda a sua terra será envergonhada, e todos os seus mortos jazerão caídos dentro dela.

[[v24-51-48]]

^<<v24-51-48,48>>^ Então o céu e a terra e tudo o que existe neles gritará de alegria por causa da Babilônia, pois do norte destruidores a atacarão", declara o Senhor.

[[v24-51-49]]

^<<v24-51-49,49>>^ "A Babilônia cairá por causa dos mortos de Israel, assim como os mortos de toda a terra caíram por causa da Babilônia.

[[v24-51-50]]

^<<v24-51-50,50>>^ Vocês que escaparam da espada, saiam! Não permaneçam! Lembrem-se do Senhor numa terra distante, e pensem em Jerusalém.

[[v24-51-51]]

^<<v24-51-51,51>>^ "Estamos envergonhados pois fomos insultados e a vergonha cobre o nosso rosto, porque estrangeiros penetraram nos lugares santos do templo do Senhor.

[[v24-51-52]]

^<<v24-51-52,52>>^ "Portanto, centamente vêm os dias", declara o Senhor, "quando castigarei as suas imagens esculpidas, e por toda a sua terra os feridos gemerão.

[[v24-51-53]]

^<<v24-51-53,53>>^ Mesmo que a Babilônia chegue ao céu e fortifique no alto a sua fortaleza, enviarei destruidores contra ela", declara o Senhor.

[[v24-51-54]]

^<<v24-51-54,54>>^ "Vem da Babilônia o som de um grito, o som de grande destruição vem da terra dos babilônios.

[[v24-51-55]]

^<<v24-51-55,55>>^ O Senhor destruirá a Babilônia; ele silenciará o seu grande ruído. Ondas de inimigos avançarão como grandes águas; o rugir de suas vozes ressoará.

[[v24-51-56]]

^<<v24-51-56,56>>^ Um destruidor virá contra a Babilônia; seus guerreiros serão capturados, e seus arcos serão quebrados. Pois o Senhor é um Deus de retribuição; ele retribuirá plenamente.

[[v24-51-57]]

^<<v24-51-57,57>>^ Embebedarei os seus líderes e os seus sábios; os seus governadores, os seus oficiais e os seus guerreiros. Eles dormirão para sempre e jamais acordarão", declara o Rei, cujo nome é Senhor dos Exércitos.

[[v24-51-58]]

^<<v24-51-58,58>>^ Assim diz o Senhor dos Exércitos: "A larga muralha da Babilônia será desmantelada e suas altas portas serão incendiadas. Os povos se exaurem por nada, o trabalho das nações não passa de combustível para as chamas".

[[v24-51-59]]

^<<v24-51-59,59>>^ Esta é a mensagem que Jeremias deu ao responsável pelo acampamento Seraías, filho de Nerias, filho de Maaséias, quando ele foi à Babilônia com o rei Zedequias de Judá no quarto ano do seu reinado.

[[v24-51-60]]

^<<v24-51-60,60>>^ Jeremias escreveu num rolo todas as desgraças que sobreviriam à Babilônia, tudo que fora registrado acerca da Babilônia.

[[v24-51-61]]

^<<v24-51-61,61>>^ Ele disse a Seraías: "Quando você chegar à Babilônia, tenha o cuidado de ler todas estas palavras em voz alta.

[[v24-51-62]]

^<<v24-51-62,62>>^ Então diga: ‘Ó Senhor, disseste que destruirás este lugar, para que nem homem nem animal viva nele, pois ficará em ruínas para sempre’.

[[v24-51-63]]

^<<v24-51-63,63>>^ Quando você terminar de ler este rolo, amarre nele uma pedra e atire-o no Eufrates.

[[v24-51-64]]

^<<v24-51-64,64>>^ Então diga: ‘Assim Babilônia afundará para não mais se erguer, por causa da desgraça que trarei sobre ela. E seu povo cairá’ ". Aqui terminam as palavras de Jeremias.

'''

xref:024-jeremias/024-jeremias-050.adoc#v24-50-0[&#60; Capítulo Anterior] | <<v24-51-0,Topo>> | xref:024-jeremias/024-jeremias-052.adoc#v24-52-0[Próximo Capítulo &#62;]