include::./index.adoc[]

[[v24-18-0]]
=== Jeremias, 18
// nvi ?, NVI - Nova Versão Internacional

[[v24-18-1]]

^<<v24-18-1,1>>^ Esta é a palavra que veio a Jeremias da parte do Senhor:

[[v24-18-2]]

^<<v24-18-2,2>>^ "Vá à casa do oleiro, e ali você ouvirá a minha mensagem".

[[v24-18-3]]

^<<v24-18-3,3>>^ Então fui à casa do oleiro, e o vi trabalhando com a roda.

[[v24-18-4]]

^<<v24-18-4,4>>^ Mas o vaso de barro que ele estava formando se estragou-se em suas mãos; e ele o refez, moldando outro vaso de acordo com a sua vontade.

[[v24-18-5]]

^<<v24-18-5,5>>^ Então o Senhor dirigiu-me a palavra:

[[v24-18-6]]

^<<v24-18-6,6>>^ "Ó comunidade de Israel, será que não posso eu agir com vocês como fez o oleiro? ", pergunta o Senhor. "Como barro nas mãos do oleiro, assim são vocês nas minhas mãos, ó comunidade de Israel.

[[v24-18-7]]

^<<v24-18-7,7>>^ Se em algum momento eu decretar que uma nação ou um reino seja arrancado, despedaçado e arruinado,

[[v24-18-8]]

^<<v24-18-8,8>>^ e se essa nação que eu adverti converter-se da sua perversidade, então eu me arrependerei e não trarei sobre ela a desgraça que eu tinha planejado.

[[v24-18-9]]

^<<v24-18-9,9>>^ E, se noutra ocasião eu decretar que uma nação ou um reino seja edificado e plantado,

[[v24-18-10]]

^<<v24-18-10,10>>^ e se ele fizer o que eu reprovo e não me obedecer, então me arrependerei do bem que eu pretendia fazer em favor dele.

[[v24-18-11]]

^<<v24-18-11,11>>^ "Agora, portanto, diga ao povo de Judá e aos habitantes de Jerusalém: ‘Assim diz o Senhor: Estou preparando uma desgraça e fazendo um plano contra vocês. Por isso, converta-se cada um de seu mau procedimento e corrija a sua conduta e as suas ações’.

[[v24-18-12]]

^<<v24-18-12,12>>^ Mas eles responderão: ‘Não adianta. Continuaremos com os nossos próprios planos; cada um de nós seguirá a rebeldia do seu coração mau’. "

[[v24-18-13]]

^<<v24-18-13,13>>^ Portanto, assim diz o Senhor: "Perguntem entre as nações se alguém já ouviu uma coisa dessas; coisa tremendamente horrível fez a virgem, Israel!

[[v24-18-14]]

^<<v24-18-14,14>>^ Poderá desaparecer a neve do Líbano de suas encostas rochosas? Poderá parar de fluir suas águas frias, vindas de lugares distantes?

[[v24-18-15]]

^<<v24-18-15,15>>^ Contudo, o meu povo esqueceu-se de mim: queimam incenso a ídolos inúteis, que os fazem tropeçar em seus caminhos e nas antigas veredas, para que andem em desvios, em estradas não aterradas.

[[v24-18-16]]

^<<v24-18-16,16>>^ A terra deles ficará deserta e será tema de permanente zombaria. Todos os que por ela passarem ficarão chocados e balançarão a cabeça.

[[v24-18-17]]

^<<v24-18-17,17>>^ Como o vento leste, eu os dispersarei diante dos inimigos; eu lhes mostrarei as costas e não o rosto, no dia da sua derrota".

[[v24-18-18]]

^<<v24-18-18,18>>^ Então disseram: "Venham! Façamos planos contra Jeremias, pois não cessará o ensino da lei pelo sacerdote nem o conselho do sábio nem a mensagem do profeta. Venham! Façamos acusações contra ele e não ouçamos nada do que ele disser".

[[v24-18-19]]

^<<v24-18-19,19>>^ Atende-me, ó Senhor; ouve o que os meus acusadores estão dizendo!

[[v24-18-20]]

^<<v24-18-20,20>>^ Acaso se paga o bem com o mal? Mas eles cavaram uma cova para mim. Lembra-te de que eu compareci diante de ti para interceder em favor deles, para que desviasses deles a tua ira.

[[v24-18-21]]

^<<v24-18-21,21>>^ Por isso entrega os filhos deles à fome e ao poder da espada. Que as suas mulheres fiquem sem filhos e viúvas; que os seus homens sejam mortos, e os seus rapazes sejam mortos pela espada na batalha.

[[v24-18-22]]

^<<v24-18-22,22>>^ Seja ouvido o grito que vem de suas casas, quando repentinamente trouxeres invasores contra eles; pois cavaram uma cova para me capturarem e esconderam armadilhas para os meus pés.

[[v24-18-23]]

^<<v24-18-23,23>>^ Mas tu conheces, ó Senhor, todas as suas conspirações para me matarem. Não perdoes os seus crimes nem apagues de diante da tua vista os seus pecados. Sejam eles derrubados diante de ti; age contra eles na hora da tua ira!

'''

xref:024-jeremias/024-jeremias-017.adoc#v24-17-0[&#60; Capítulo Anterior] | <<v24-18-0,Topo>> | xref:024-jeremias/024-jeremias-019.adoc#v24-19-0[Próximo Capítulo &#62;]