include::./index.adoc[]

[[v24-10-0]]
=== Jeremias, 10
// nvi ?, NVI - Nova Versão Internacional

[[v24-10-1]]

^<<v24-10-1,1>>^ Ouçam o que o Senhor diz a vocês, ó comunidade de Israel!

[[v24-10-2]]

^<<v24-10-2,2>>^ Assim diz o Senhor: "Não aprendam as práticas das nações nem se assustem com os sinais no céu, embora as nações se assustem com eles.

[[v24-10-3]]

^<<v24-10-3,3>>^ Os costumes religiosos das nações são inúteis: corta-se uma árvore da floresta, um artesão a modela com seu formão;

[[v24-10-4]]

^<<v24-10-4,4>>^ enfeitam-na com prata e ouro, prendendo tudo com martelo e pregos para que não balance.

[[v24-10-5]]

^<<v24-10-5,5>>^ Como um espantalho numa plantação de pepinos, os ídolos são incapazes de falar, e têm que ser transportados porque não conseguem andar. Não tenham medo deles, pois não podem fazer nem mal nem bem".

[[v24-10-6]]

^<<v24-10-6,6>>^ Não há absolutamente ninguém comparável a ti, ó Senhor; tu és grande, e grande é o poder do teu nome.

[[v24-10-7]]

^<<v24-10-7,7>>^ Quem não te temerá, ó rei das nações? Esse temor te é devido. Entre todos os sábios das nações e entre todos os seus reinos não há absolutamente ninguém comparável a ti.

[[v24-10-8]]

^<<v24-10-8,8>>^ São todos insensatos e tolos; querem ser ensinados por ídolos inúteis. Os deuses deles não passam de madeira.

[[v24-10-9]]

^<<v24-10-9,9>>^ Prata batida é trazida de Társis, e ouro, de Ufaz. A obra do artesão e do ourives é vestida de azul e de vermelho; tudo não passa de obra de hábeis artesãos.

[[v24-10-10]]

^<<v24-10-10,10>>^ Mas o Senhor é o Deus verdadeiro; ele é o Deus vivo; o rei eterno. Quando ele se ira, a terra treme; as nações não podem suportar o seu furor.

[[v24-10-11]]

^<<v24-10-11,11>>^ "Digam-lhes isto: ‘Esses deuses, que não fizeram nem os céus nem a terra, desaparecerão da terra e de debaixo dos céus’. "

[[v24-10-12]]

^<<v24-10-12,12>>^ Mas foi Deus quem fez a terra com o seu poder, firmou o mundo com a sua sabedoria e estendeu os céus com o seu entendimento.

[[v24-10-13]]

^<<v24-10-13,13>>^ Ao som do seu trovão, as águas no céu rugem, e formam-se nuvens desde os confins da terra. Ele faz os relâmpagos para a chuva e dos seus depósitos faz sair o vento.

[[v24-10-14]]

^<<v24-10-14,14>>^ Esses homens todos são estúpidos e ignorantes; cada ourives é envergonhado pela imagem que esculpiu. Suas imagens esculpidas são uma fraude, elas não têm fôlego de vida.

[[v24-10-15]]

^<<v24-10-15,15>>^ São inúteis, são objetos de zombaria. Quando vier o julgamento delas, perecerão.

[[v24-10-16]]

^<<v24-10-16,16>>^ Aquele que é a porção de Jacó nem se compara a essas imagens, pois ele é quem forma todas as coisas, e Israel é a tribo de sua propriedade, o Senhor dos Exércitos é o seu nome.

[[v24-10-17]]

^<<v24-10-17,17>>^ Ajunte os seus pertences para deixar a terra, você que vive sitiada.

[[v24-10-18]]

^<<v24-10-18,18>>^ Porque assim diz o Senhor: "Desta vez lançarei fora os que vivem nesta terra. Trarei aflição sobre eles, e serão capturados".

[[v24-10-19]]

^<<v24-10-19,19>>^ Ai de mim! Estou ferido! O meu ferimento é incurável! Apesar disso eu dizia: Esta é a minha enfermidade e tenho que suportá-la.

[[v24-10-20]]

^<<v24-10-20,20>>^ A minha tenda foi destruída; todas as cordas da minha tenda estão arrebentadas. Os meus filhos me deixaram e já não existem; não restou ninguém para armar a minha tenda e montar o meu abrigo.

[[v24-10-21]]

^<<v24-10-21,21>>^ Os líderes do povo são insensatos e não consultam o Senhor; por isso não prosperam e todo o seu rebanho está disperso.

[[v24-10-22]]

^<<v24-10-22,22>>^ Escutem! Estão chegando notícias: uma grande agitação vem do norte! As cidades de Judá serão arrasadas e transformadas em morada de chacais.

[[v24-10-23]]

^<<v24-10-23,23>>^ Eu sei, Senhor, que a vida do homem não lhe pertence; não compete ao homem dirigir os seus passos.

[[v24-10-24]]

^<<v24-10-24,24>>^ Corrige-me, Senhor, mas somente com justiça, não com ira, para que não me reduzas a nada.

[[v24-10-25]]

^<<v24-10-25,25>>^ Derrama a tua ira sobre as nações que não te conhecem, sobre os povos que não invocam o teu nome; pois eles devoraram Jacó, devoraram-no completamente e destruíram a sua terra natal.

'''

xref:024-jeremias/024-jeremias-009.adoc#v24-9-0[&#60; Capítulo Anterior] | <<v24-10-0,Topo>> | xref:024-jeremias/024-jeremias-011.adoc#v24-11-0[Próximo Capítulo &#62;]