include::./index.adoc[]

[[v24-11-0]]
=== Jeremias, 11
// nvi ?, NVI - Nova Versão Internacional

[[v24-11-1]]

^<<v24-11-1,1>>^ Esta é a palavra que veio a Jeremias da parte do Senhor:

[[v24-11-2]]

^<<v24-11-2,2>>^ "Ouçam os termos desta aliança; e, você, repita-os ao povo de Judá e aos habitantes de Jerusalém.

[[v24-11-3]]

^<<v24-11-3,3>>^ Diga-lhes que assim diz o Senhor, o Deus de Israel: ‘Maldito é aquele que não obedecer aos termos desta aliança,

[[v24-11-4]]

^<<v24-11-4,4>>^ os quais ordenei aos antepassados de vocês, quando eu os tirei do Egito, da fornalha de fundir ferro’. Eu disse: Obedeçam-me e façam tudo o que lhes ordeno, e vocês serão o meu povo, e eu serei o seu Deus.

[[v24-11-5]]

^<<v24-11-5,5>>^ Então cumprirei a promessa que fiz sob juramento aos antepassados de vocês, de dar-lhes uma terra onde manam leite e mel, a terra que vocês hoje possuem". Então respondi: "Amém, Senhor".

[[v24-11-6]]

^<<v24-11-6,6>>^ O Senhor me disse: "Proclame todas estas palavras nas cidades de Judá e nas ruas de Jerusalém: ‘Ouçam os termos desta aliança e cumpram-nos.

[[v24-11-7]]

^<<v24-11-7,7>>^ Desde a época em que tirei os seus antepassados do Egito até hoje, repetidas vezes os adverti, dizendo: Obedeçam-me.

[[v24-11-8]]

^<<v24-11-8,8>>^ Mas eles não me ouviram nem me deram atenção; pelo contrário, seguiram os seus corações duros e maus. Por isso eu trouxe sobre eles todas as maldições desta aliança, que eu tinha ordenado que cumprissem, mas que eles não cumpriram’ ".

[[v24-11-9]]

^<<v24-11-9,9>>^ Então o Senhor me disse: "Há uma conspiração entre o povo de Judá e os habitantes de Jerusalém.

[[v24-11-10]]

^<<v24-11-10,10>>^ Eles retornaram aos pecados de seus antepassados, que recusaram das ouvidos às minhas palavras e seguiram outros deuses para prestar-lhes culto. Tanto a comunidade de Israel como a de Judá quebraram a aliança que eu fiz com os antepassados deles".

[[v24-11-11]]

^<<v24-11-11,11>>^ Por isso, assim diz o Senhor: "Trarei sobre eles uma desgraça da qual não poderão escapar. Ainda que venham a clamar a mim, eu não os ouvirei.

[[v24-11-12]]

^<<v24-11-12,12>>^ Então as cidades de Judá e os habitantes de Jerusalém clamarão aos deuses, aos quais queimam incenso, mas eles não poderão salvá-los quando a desgraça os atingir.

[[v24-11-13]]

^<<v24-11-13,13>>^ Você tem tantos deuses quantas são as suas cidades, ó Judá; e os altares que você construiu para queimar incenso àquela coisa vergonhosa chamada Baal são tantos quantas são as ruas de Jerusalém.

[[v24-11-14]]

^<<v24-11-14,14>>^ "E você, Jeremias, não ore em favor desse povo nem ofereça súplica ou petição alguma por eles, porque eu não ouvirei quando clamarem a mim na hora da desgraça. "

[[v24-11-15]]

^<<v24-11-15,15>>^ "O que a minha amada faz no meu templo, com intenção enganosa? Será que os votos e a carne consagrada evitarão o castigo? Poderá você, então, exultar? "

[[v24-11-16]]

^<<v24-11-16,16>>^ O Senhor a chamou de oliveira verdejante, ornada de belos e bons frutos. Mas com o estrondo de um grande tumulto, ele a incendiará, e os seus ramos serão quebrados.

[[v24-11-17]]

^<<v24-11-17,17>>^ O Senhor dos Exércitos, que a plantou, anunciou-lhe desgraça, porque a comunidade de Israel e a comunidade de Judá fizeram o que é reprovável e provocaram a minha ira, queimando incenso a Baal.

[[v24-11-18]]

^<<v24-11-18,18>>^ Fiquei sabendo porque o Senhor me revelou; tu me mostraste o que eles estavam fazendo.

[[v24-11-19]]

^<<v24-11-19,19>>^ Eu era como um cordeiro manso levado ao matadouro; não tinha percebido que tramavam contra mim, dizendo: "Destruamos a árvore e a sua seiva, vamos cortá-lo da terra dos viventes para que o seu nome não seja mais lembrado".

[[v24-11-20]]

^<<v24-11-20,20>>^ Ó Senhor dos Exércitos, justo juiz que provas o coração e a mente, espero ver a tua vingança sobre eles, pois a ti expus a minha causa.

[[v24-11-21]]

^<<v24-11-21,21>>^ Em vista disso, assim diz o Senhor a respeito dos homens de Anatote que querem tirar a sua vida, e que dizem: "Não profetize em nome do Senhor, se não nós o mataremos";

[[v24-11-22]]

^<<v24-11-22,22>>^ assim diz o Senhor dos Exércitos: "Eu os castigarei. Seus jovens morrerão à espada; seus filhos e suas filhas, de fome.

[[v24-11-23]]

^<<v24-11-23,23>>^ Nem mesmo um remanescente lhes restará, porque trarei a desgraça sobre os homens de Anatote no ano do seu castigo".

'''

xref:024-jeremias/024-jeremias-010.adoc#v24-10-0[&#60; Capítulo Anterior] | <<v24-11-0,Topo>> | xref:024-jeremias/024-jeremias-012.adoc#v24-12-0[Próximo Capítulo &#62;]